### ISSUE TITLE
Snippets stop working after a while

### ISSUE THREAD

**Issue by antonioOrtiz** [microsoft/vscode#74217]
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: macOS Mojave 10.14.4

Strangely the following Node related extensions; [express snippet extension][1],  [expressjs4-snippets][2] and [Node Snippets][3] simply stop working after a while. My react snippets are fine, but not these three.

Below is my `settings.json` config file:

    {
         // //editor fontSize and tabSize configs
         "editor.fontSize": 14,
         "terminal.integrated.fontSize": 14,
         "window.zoomLevel": -1,
         "[Log]": {
             "editor.fontSize": 14
         },
    
        // Controls if suggestions should be accepted on 'Enter' - in addition to 'Tab'. Helps to avoid ambiguity between inserting new lines or accepting suggestions. The value 'smart' means only accept a suggestion with Enter when it makes a textual change
        "editor.acceptSuggestionOnEnter": "on",
        "editor.autoIndent": true,
        "editor.emptySelectionClipboard": false,
    
        "editor.formatOnPaste": true,
        "editor.multiCursorModifier": "ctrlCmd",
        "editor.renderIndentGuides": true,
        "editor.renderWhitespace": "none",
        "editor.renderControlCharacters": false,
        "editor.scrollBeyondLastLine": true,
        "editor.showFoldingControls": "always",
        "editor.showUnused": true,
    
        // Controls the delay in ms after which quick suggestions will show up.
        "editor.quickSuggestionsDelay": 10,
        // Controls if quick suggestions should show up while typing
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": false
        },
        // Controls if suggestions should automatically show up when typing trigger characters
        "editor.suggestOnTriggerCharacters": true,
        // Controls if pressing tab inserts the best suggestion and if tab cycles through other suggestions
        "editor.tabCompletion": "on",
        "editor.trimAutoWhitespace": false,
        "editor.wordWrap": "on",
        // Controls whether sorting favours words that appear close to the cursor
        "editor.suggest.localityBonus": true,
        "editor.wordBasedSuggestions": true,
        
        // Tab config
        // The number of spaces a tab is equal to. This setting is overridden
        // based on the file contents when `editor.detectIndentation` is true.
        "editor.tabSize": 2,
        // Insert spaces when pressing Tab. This setting is overriden
        // based on the file contents when `editor.detectIndentation` is true.
        "editor.insertSpaces": true,
        // When opening a file, `editor.tabSize` and `editor.insertSpaces`
        // will be detected based on the file contents. Set to false to keep
        // the values you've explicitly set, above.
        "editor.detectIndentation": false,
        // emmet
        // When enabled, Emmet abbreviations are expanded when pressing TAB.
        "emmet.triggerExpansionOnTab": true,
        "emmet.syntaxProfiles": {
            "javascript": "jsx",
            "xml": {
                "attr_quotes": "single"
            }
        },
        "emmet.includeLanguages": {
            "javascript": "javascriptreact"
        },
        
        
        // Enable ESLint (with Prettier plugin) to format code on save
        "eslint.alwaysShowStatus": true,
        "eslint.autoFixOnSave": true,
        "eslint.enable": true,
        "eslint.nodePath": "/Users/antonio-pavicevac-ortiz/.nvm/versions/node/v9.0.0/bin/eslint",
        "files.autoSave": "onFocusChange",
        "files.hotExit": "off",
        "files.trimTrailingWhitespace": true,
        "files.insertFinalNewline": true,
        "files.associations": {
          "*.js": "javascriptreact",
          ".gitignore": "shellscript"
        },
        // Disable default VSCode formatting for JavaScript
        "[javascript]": {
          "editor.formatOnSave": false
        },
        "javascript.validate.enable": true, // this controls having your unused imports or variables to appear grey
        "html.format.enable": true,
        "html-css-class-completion.enableEmmetSupport": true,
        // //php settings
        "php.executablePath": "/usr/bin/php",
        "prettier.disableLanguages": [
          "javascript",
          "javascriptreact",
          "json"
        ],
        
    
        "editor.suggestSelection": "first",
        "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
        "workbench.colorTheme": "Night Owl",
        "sync.gist": "8e227eee246912533620000ceb348981" 
    }

**Steps to Reproduce:**

I actually quit vs code and then go to (on a MacOS Mojave version 10.14.3) ***home folder > Library > Application Support > Code*** and trash that folder. It essentially will regenerate upon start up.

That ***CODE*** folder contains a ***USER*** folder. In that folder are the ***keybindings.json*** and the ***settings.json*** files which is where one overrides the defaults and tweak preferences of the extensions. 

In my case because I'm using [Settings-Sync][4] (It allows ones extensions and settings to be saved in a gist on github, to be shared by multiple computers and teams!!!) so it's not too bad to get everything back. 

  [1]: htts://github.com/vladmrnv/ExpressSnippet
  [2]: https://github.com/gurayyarar/expressjs4-snippets#demo
  [3]: https://github.com/softchris/node-snippets#node-snippets
  [4]: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

Does this issue occur when all extensions are disabled?: Yes

Any help would be appreciated!

**Comment by jrieken** [comment]
I don't understand the issue here

**Comment by antonioOrtiz** [comment]
@jrieken What other information do you need?
