### ISSUE TITLE
Attempting to create a new file immediately after opening a folder causes the entry box to close (focus loss)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#74218]
Issue Type: <b>Bug</b>

Originally reported https://github.com/eamodio/vscode-gitlens/issues/726, https://github.com/eamodio/vscode-gitlens/issues/753

1. Open a folder
1. Immediate try to create a new file
1. 🐛 The input will show up and you can start typing, but it will disappear as focus seems to get lost

VS Code version: Code - Insiders 1.35.0-insider (94f7de61ece171f4390ece488a220d22cbb0fddd, 2019-05-23T05:19:33.101Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/72139
