### ISSUE TITLE
detect when its only identation diff

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/vscode#74211]
Issue Type: <b>Feature Request</b>

In Diff mode detect when its only identation diff, thats have only changing spaces or tabs and use another color classic Red(remove) green(add) this is will be easy to identify when its a real code update or only identation.

Concept picture
![image](https://user-images.githubusercontent.com/13587928/58270286-c7440680-7d5f-11e9-8312-90ab3d3c9d55.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexandrudima** [comment]
Leading / Trailing whitespace can be ignored in the diff computation (and they are ignored by default) -- just press this toggle button --

![image](https://user-images.githubusercontent.com/5047891/61771825-0e4a8880-adf1-11e9-823b-4ed55b57abd8.png)
