### ISSUE TITLE
Use upcoming Windows Terminal font as default

### ISSUE THREAD

**Issue by f1amy** [microsoft/vscode#74212]
A while ago, at Build 2019 Microsoft mentioned that they are going to release a new open source monospaced font with programming ligatures for new Windows Terminal.
It would be great if, after the font is released, it will be used by default in VS Code instead of Consolas.
[Blog post about new Windows Terminal](https://devblogs.microsoft.com/commandline/introducing-windows-terminal/)

**Comment by Tyriar** [comment]
We might do this, we can evaluate once it's a thing
