### ISSUE TITLE
Latest update breaks Objective-C++ syntax highlighting

### ISSUE THREAD

**Issue by Muirey03** [microsoft/vscode#74219]
In the latest update to VS Code (including the insiders build), when using Objective-C++ syntax highlighting, all the text is the same colour. Objective-C syntax highlighting still works fine however.

[Here is a screenshot using Objective-C++ syntax highlighting, demonstrating the issue](https://gyazo.com/5c7b066657bdbbdf10d6bbbf3cde0ee7).

[Here is a screenshot of the same code using Objective-C syntax highlighting](https://gyazo.com/9c09bfb5a10d82eb1b6c00b245bf4880).

**Comment by Muirey03** [comment]
I can also confirm that I am not the only person to experience this issue, after talking to other people about it. I don't think you'll find it too challenging to reproduce.

**Comment by ambershark-mike** [comment]
I can confirm this as well.  Here is a screen shot of it happening. Mine at least seems based on escaping quotes inside a string with backslash.  The highlighted block is where it gets broken.

![image](https://user-images.githubusercontent.com/20294359/58362965-60534a00-7e52-11e9-9366-3959aeffb537.png)

Here's the code in text if you want to reproduce easily:

```
- (nonnull NSArray<NSString *> *)getCameras {
    // get list of regular cameras
    AVCaptureDeviceDiscoverySession *session = [AVCaptureDeviceDiscoverySession 
        discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeBuiltInWideAngleCamera]
        mediaType:AVMediaTypeVideo 
        position:AVCaptureDevicePositionUnspecified];

    // create json object for each camera
    NSMutableArray<NSString *> *lst = [[NSMutableArray alloc] init];
    for (AVCaptureDevice *device in session.devices) {
        NSString *s = @"{ ";
        s = [s stringByAppendingFormat:@"\"id\": %@, ", device.uniqueID];
        s = [s stringByAppendingFormat:@"\"facing\": %@, ", device.position == AVCaptureDevicePositionFront ? @"front" : @"back"];
        s = [s stringByAppendingFormat:@"\"orientation\": 0, "];
        s = [s stringByAppendingFormat:@"\"forcedShutterSound\": false"];
        s = [s stringByAppendingString:@" }"];
        [lst addObject:s];
    }

    return lst;
}
```

**Comment by alexr00** [comment]
I can reproduce the bad objective-c highlighting. Not sure what's going on yet. @jeff-hykin and @matter123 since the C++ grammar is the only thing that's changed here.

**Comment by Muirey03** [comment]
It makes sense that it was caused by a change in the C++ syntax highlighting, as the bug only occurs with objective-c++ syntax highlighting, not objective-c syntax highlighting.

**Comment by jeff-hykin** [comment]
We'll get right on this.

One of the bug fixes on C++ caused this, however its not so much a mistake as it is a conflict. Reverting to fix Objective-C++ is necessarily going to cause bugs in the C++ syntax ☹️

A similar situation existed between C++ and C and we had to separate them to fix both.

**Comment by jeff-hykin** [comment]
Okay a work in progress has been made, I added the Objective-C++ syntax to the `Better C++ Syntax` repo and its currently being compiled with an old version of the C++ syntax. This should mean that its it is the same as it was before the changes to C++ were made, but I didn't have time to fully verify that yet.

Any issues you're still experiencing, do report them to https://github.com/jeff-hykin/cpp-textmate-grammar I created a `Objective-C++` label just for them.

On Tue or Wed I'll be able to take more time an get a more solid solution for this (either creating a separate repo or renaming the repo to `c-based-syntaxes` and doing research on the relationship between Objective-C++ and C++)

**Comment by Muirey03** [comment]
@jeff-hykin I don't think the strings in that example are correct. Using the objective-c highlighting, the `@"` should be the same colour as the rest of the string. I think a good reference will be simply that it should look identical to the normal objective-c syntax highlighting.

**Comment by jeff-hykin** [comment]
Oh it should show up that way (strings all one color) on everyone else's. I had a custom textmate setting that I forgot to disable before taking the screenshot.

Here's what it looks like with my settings disabled.
<img width="1359" alt="Screen Shot 2019-05-27 at 10 57 39 PM" src="https://user-images.githubusercontent.com/17692058/58447651-16c56200-80d3-11e9-9aa3-ccbf7c537539.png">

**Comment by ambershark-mike** [comment]
@jeff-hykin Thanks!  I downgraded my vscode but will re-enable it in pacman tonight and update.  I'll let you know but it looks good to me in the screenshot. :)

**Comment by alexr00** [comment]
@ambershark-mike @Muirey03 I'm rolling back to the old atom C++ grammar for _just_ the Objective C++ highlighting.  All the good improvements for C++ will be kept. That way we still have reasonable highlighting out of the box for both languages. Once @jeff-hykin has a solution for the C++ vs Objective C++ conflict I can change it back.

**Comment by Muirey03** [comment]
@alexr00 Thank you, sounds good to me.
