### ISSUE TITLE
Vscode auto import node_module gets nested into lib folder instead of coming from root

### ISSUE THREAD

**Issue by tgreen7** [microsoft/vscode#74227]
Issue Type: <b>Bug</b>

<img width="713" alt="Screen Shot 2019-05-23 at 12 37 15 PM" src="https://user-images.githubusercontent.com/10415101/58281241-83e59a00-7d57-11e9-90bc-829c27df9143.png">

This happens even though the package teselagen-react-components exports everything from the src/index.js and the lib/index.js files. The import should be direct like ```import { SwitchField } from "teselagen-react-components"```

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.5.1
react-pure-to-class-vscode|ang|1.1.8
insertnumbers|Asu|0.9.1
All-Autocomplete|Ati|0.0.18
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|1.4.2
bracket-select|chu|2.0.1
swap-word|dav|0.1.2
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.9.0
vscode-diff|fab|1.4.0
vscode-terminals|fab|1.12.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
code-runner|for|0.9.9
shell-format|fox|4.0.11
vscode-pull-request-github|Git|0.7.0
css2react|got|0.0.6
vscode-auto-open-markdown-preview|hnw|0.0.4
easy-icons|jam|0.3.1
vscode-text-pastry|jkj|1.2.0
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.26
recent-files|jun|1.1.10
graphql-for-vscode|kum|1.13.1
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
extension-manifest-editor|ms-|0.1.5
sublime-keybindings|ms-|4.0.0
vsliveshare|ms-|1.0.249
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.7.0
sass-indented|rob|1.5.1
nunjucks|ron|0.2.3
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
vscode-fileutils|sle|2.13.7
open-in-browser|tec|2.0.0
vscode-bio-utils|tes|0.0.9
vs-code-node-require|tgr|1.4.0
vscode-terminal-here|Tyr|0.1.1
vscodeintellicode|Vis|1.1.6
change-case|wma|1.0.0
convert-object-to-jsx|zac|1.0.0

(6 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I cannot repo this in VS Code 1.35 using the buildin TypeScript 3.5 version. 

Are you still seeing this? If so, please share your `jsconfig` or `tsconfig`:

![Screen Shot 2019-06-26 at 3 02 30 PM](https://user-images.githubusercontent.com/12821956/60218187-74101880-9823-11e9-8bb9-bb4b48380df6.png)
