### ISSUE TITLE
Allow menu contributions to custom viewContainer title bar

### ISSUE THREAD

**Issue by JarrettSpiker** [microsoft/vscode#74221]
Currently, it is possible for extensions to contribute custom views, as well as add menu items to those custom views. These menu items appear as icons in the view title bar, which trigger commands when clicked.

For example, I can create a custom view "Jarrett's Example View" and have a refresh action available in the title bar of that view:

![currentView](https://user-images.githubusercontent.com/10147422/58275486-5fd38a00-7d52-11e9-9dbe-980c9f068a5f.png)

I would like to request that the same functionality be available for custom view containers. That is, **I want to be able to add menu items to custom view containers which trigger my commands**

We see this functionality in the native view containers. For example, the "Search" view container has 3 icons in its title bar:

![searchView](https://user-images.githubusercontent.com/10147422/58275727-015adb80-7d53-11e9-839a-42eeb57951aa.png)

but I don't see a way to mimic this in custom view containers. Being able to do so would be helpful for providing actions global to a particular view container, or to the extension contributing a view container.

For example, I would like to have an icon which will jump you straight to the settings for my extension, and one which will open a help page. These both make sense to associate with my view container, not necessarily individual views.

Thanks for your time

**Comment by sandy081** [comment]
I see your point, but the actions are associated to views and its same with Search view. Not sure this use case (showing settings of an extension) is strong enough to show actions for container. It might also happen that extensions can contribute views to your view container or in future we can also allow user moving views in which case these actions become irrelevant.
