### ISSUE TITLE
remote development git change tracking

### ISSUE THREAD

**Issue by OneCyrus** [microsoft/vscode#74225]
- VSCode Version: 1.35 insiders (23.5.19)
- OS Version: Windows 10 1903
- Remote Server: Ubuntu Server 18.04

Steps to Reproduce:

1. cloning a git repo on a remote development ssh server
2. changing git tracked files
3. git side bar doesn't show change files
4. clicking the refresh button we see the changed files

expectation:
vs code should show the tracked changes without manual refreshing

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-remote-release/issues/314
