### ISSUE TITLE
Select all find matches -->Nothing Happening when i press ALT+ENTER

### ISSUE THREAD

**Issue by vinod-a-ext** [Microsoft/vscode#7422]
- VSCode Version:May Version
- OS Version:win 7

Steps to Reproduce:
1. Update VS CODE to MAY Version
2. Press ALT+enter 

Actual:Nothing Happening
Excepted :Show Input Box To select a string to replace

**Comment by alexandrudima** [comment]
This works for me. Alt+Enter adds a cursor to all of the found matches:

![alt-enter](https://cloud.githubusercontent.com/assets/5047891/24920903/43478e78-1ee9-11e7-81e3-bcabfec6aa82.gif)
