### ISSUE TITLE
Respect "underline access keys when available" setting on win10

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#74232]
reported here: https://twitter.com/fiecila/status/1131623092298633217

windows 10
Settings -> Keyboard

turn on the "Underline access keys when available" option

![image](https://user-images.githubusercontent.com/1487073/58287648-74218200-7d66-11e9-9ff1-6ccda6918e98.png)

Result: we should see the underline on the menus, they should all be visible all the time, but they are not

![image](https://user-images.githubusercontent.com/1487073/58287714-974c3180-7d66-11e9-9b0a-b924ec9dae17.png)

here is what is expected with the option on (i simply pressed the `Alt` key to get this picture):

![image](https://user-images.githubusercontent.com/1487073/58287761-ad59f200-7d66-11e9-9576-3b563c3bdb54.png)

**Comment by sbatten** [comment]
@chrisdias I added this in February so I'm not sure what version they are running

**Comment by chrisdias** [comment]
ok, i checked again and found that Notepad will change the menus as you toggle the setting and bring Notepad to the foreground.  

With VS Code you need to reload the window for the setting to take effect.

**Comment by sbatten** [comment]
@chrisdias I don't really intend on fixing the reload requirement since we'd have to listen to reg key changes in order to do that.
