### ISSUE TITLE
C++ Pointer Arrays Break Syntax Highlighting

### ISSUE THREAD

**Issue by Pecacheu** [microsoft/vscode#74234]
Issue Type: <b>Bug</b>

When you create a C-style array of pointers in a C++ file it breaks VS Code's syntax highlighting, for example:

    uint32_t *uintArray = new uint32_t[len]; //This works.
    uint32_t **uintPArray = new uint32_t*[len]; //But this breaks all following syntax highlighting in the file.

I thought something like `(new uint32_t*)[len];` would be a temporary workaround, my Windows toolchain took that, however my Linux GCC didn't accept that as valid syntax, so the above is definitely how it's supposed to be done.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.23.1
code-spell-checker|str|1.7.10

</details>

**Comment by alexr00** [comment]
Fixed in insiders already. We need more C++ users on Insiders to help catch issues like this before they make it to stable. Insiders and stable can be installed side by side. If you're interested, you can get insiders [here](https://code.visualstudio.com/insiders/).
