### ISSUE TITLE
Run Above / Run Below accidental hits

### ISSUE THREAD

**Issue by acesnik** [microsoft/vscode#74236]
Issue Type: <b>Feature Request</b>

I frequently accidentally click on "Run Above" and "Run Below" above cells within python notebooks, and then have to wait several minutes for those cells to finish before continuing to work (interrupting the Jupyter Notebook kernel doesn't always work). I think the "Run Cell" feature is useful, but you really could dump the other two and leave them in a drop-down menu.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
Run above and run below are part of the Python extension.
