### ISSUE TITLE
Allow shift-enter in terminal for multiline input to PowerShell

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#74230]
- VSCode Version: 1.34.0
- OS Version: Win 10 1903 (RTM)

Steps to Reproduce:

1. Use a PowerShell terminal with PSReadLine supported
2. attempt to use SHIFT-ENTER to insert a line break

A Shift-Enter in the normal Windows console would signal PSReadLine to create a multiline command, inserting a line break at the current cursor position.   This seems to be unavailable while using the terminal console of VS Code.

This could be either a bug, or a feature request, or I am just missing some setting I haven't found yet.

**Comment by Tyriar** [comment]
@TylerLeonhardt I think we spoke about this one briefly, I don't think there is a shift+enter VT sequence I can send, however if it makes sense we could add a VS Code keybinding to send anything we want to powershell:

```json
{
  "key": "shift+enter",
  "command": "workbench.action.terminal.sendSequence",
  "args": { "text": "something powershell interprets as shift+enter" },
  "when": "terminalFocus"
}
```

This probably makes sense to inside the powershell extension.

**Comment by TylerLeonhardt** [comment]
Yeah that sounds right to me. Shift+Enter is an important one since it allows for multi-lined command statements. 

I forget where we landed on this... Did PSRL need to add some obscure keybinding like `ctrl+☕` and then this vscode binding would route `shift+enter` to that?

**Comment by Tyriar** [comment]
@TylerLeonhardt for other keys I think we could make it work by switching psreadline's mode over to unix or something, but for shift+space we can't encode it. Can your extension intercept and modify the incoming text stream? If so you could intercept something, eg. using a ["privacy message"](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) like `\x1b^powershell_shift_space\x1b\` which are ignored by shells.
