### ISSUE TITLE
Open editor close by .MD file preview

### ISSUE THREAD

**Issue by muhammaddicky** [microsoft/vscode#74235]
All open editor close when open 1 or more .md file preview.

**Comment by mjbvz** [comment]
Please explain step-by-step what is not working

/needsMoreInfo

**Comment by muhammaddicky** [comment]
@mjbvz When open .md file like README.md it will open preview tab for that .md file automatic, when open more .md file it will cause all open editor close except that .md file that already open before. knowing that there is no issus before about this, i dont know if another user experience this kind of issue.

**Comment by mjbvz** [comment]
Sorry but I don't understand what you are describing. Please put together a step-by-step list of how to reproduce this issue and explain what the expected behavior is compared to the actual behavior. Screenshots may also help explain
