### ISSUE TITLE
line number and fold/unfold button are clashing with more than 10k lines

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#7424]
- VSCode Version: Version 1.2.0
Commit 809e7b30e928e0c430141b3e6abf1f63aaf55589
Date 2016-06-07T08:47:59.517Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. open a file w/ more than 10k lines
2. the fold/unfold button for arrays and objects is clashing with the line number, see the attached image.

![screenshot from 2016-06-08 17 01 24](https://cloud.githubusercontent.com/assets/984628/15899073/e38a0442-2d9a-11e6-8dbe-2e7abcb0c360.png)

**Comment by alexandrudima** [comment]
To verify easily, create a file:
* on line 1 use `var bug = {`
* on lines 1-100k use `\tsomething`
* on line 100001 use `}`

**Comment by phra** [comment]
great!
