### ISSUE TITLE
Remote-SSH disconnect

### ISSUE THREAD

**Issue by rhyswat** [microsoft/vscode#74256]
I'd like the ability to disconnect from a Remote-SSH session from within VS-Code, and the ability to connect to the same or different session after disconnection. This actually applies to Remote-* but my immediate use case is SSH to a number of different hosts.

This has several parts, which may be separate bugs/features:
 - firstly the ability to disconnect (or stop) a remote session without exiting VS Code;
 - secondly to prevent VS Code from trying to reconnect to the previous session on relaunch

**Use case**
1.  open a Remote-SSH session to host A
2.  do some work
3.  now I need to do some work on host B
4.  so I disconnect from A (possibly via the green 'remote' control in the bottom left corner of VS code)
5.  and start a new remote session on host B (again possibly from the bottom left corner control)
6.  (or potentially a new Docker session, or a local folder, or quit VS Code, etc)

Currently I have to exit VS Code to achieve step 4, and restart to achieve step 5.

This feels like it ought to be covered but I couldn't find an obvious duplicate in the issues list.

Current setup:
Version: 1.35.0-insider
Commit: 5e1f9440d280b0b04cba843df6a0032bf517a2f0
Date: 2019-05-24T05:15:28.438Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-50-generic

**Comment by roblourens** [comment]
You can open a new session on B in the same window with the "Connect current window to host" command, which isn't under the status bar indicator button but you can search for it in the command palette (F1). Or by right clicking B in the ssh explorer (which you have to enable with the `remote.SSH.enableHostsExplorer` setting). You don't have to "disconnect" from A before connecting to B. You can also just open B in a new window with the "Connect to host" command.

**Comment by rhyswat** [comment]
Thanks Rob. I had missed the A to B switch you describe and that covers part of the issue.

However, this doesn’t quite address my two points because VS Code would still try to reconnect to B automatically on restart. That is not always desirable; in fact it’s rarely what I want because I’m usually hopping between several environments. Naturally, that is not something VS can be expected to predict.

By “disconnect” I mean something a bit stronger, something more than merely terminating an SSH session or Docker instance. I am looking for the ability to tell VS to  “stop this SSH session, don’t connect to a new host  _and don’t try to start a session automatically next time_”.

Hopefully this clarifies this issue a little better.

**Comment by roblourens** [comment]
I understand, thanks. You might also like setting `window.restoreWindows` to `none` which will cause vscode to never reopen the previous opened folders (or remotes).

Also discussing a similar issue in https://github.com/microsoft/vscode-remote-release/issues/501

**Comment by rhyswat** [comment]
Yes, it is similar to the other issue especially this comment: https://github.com/microsoft/vscode-remote-release/issues/501#issuecomment-497073773

Feel free to close/merge/whatever.

Thanks.
