### ISSUE TITLE
Pressing tab in debug console input changes focus

### ISSUE THREAD

**Issue by wlgrd** [microsoft/vscode#74259]
- VSCode Version: 1.33.1 (51b0b281)
- OS Version: Windows 10 x64 10.0.17763

Found this: https://github.com/microsoft/vscode/issues/10326#issuecomment-243109723 but I wasn't able to find the setting for not having it change focus. I found toggleTabFocusMode, but that does not change focusMode for the debug console.

Steps to Reproduce:

1. Start a debug session using e.g gdb, and debug console opens
2. Place cursor at input and start writing, then press tab. The line input is no longer active.

Does this issue occur when all extensions are disabled?: Yes

GDB supports using Tab to jump to next known command/input, as any terminal does. I need the same behavior for the debug console, as with the integrated terminal: Where pressing tab does not change focus.

**Comment by isidorn** [comment]
Currently our editor by default tab does not switch focus. The toggleTabFocusMode setting changes that so the editor would switch focus when a user presses tab.

The debug console is different. By default the tab switces focus and there is no setting. Also it does not support the editor setting.
If the inteli-sense is open in the debug console tab will be used to complete the item. And that is sort of like jumping to the known command.
When the inteli-sense is not shown then we really do not know what is the next known command usually. 
Hope this somehow clarifies the current behavior.

I can keep this open as a feature request to introduce a setting.

**Comment by wlgrd** [comment]
Thank you, think I got that. I would like for this to stay open then, and active as a feature request.
