### ISSUE TITLE
tasks failing to run when workspace is on UNC path

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#74253]
- VSCode Version: 1.34.0
- OS Version: Win 10 1903 RTM

Steps to Reproduce:

1. Have a workspace that is located via a UNC path
2. Create tasks
3. Attempt to execute those tasks

In this case my shell is Windows PowerShell.  The tasks are 'shell' based tasks, and the command only attempts to execute a script file.

The only result is:
```
> Executing task: Set-ExecutionPolicy Bypass Process -Force; ./install.ps1 <

The terminal process terminated with exit code: 2
```

I cannot even make a simple `echo hello` task work if I am on the UNC path.

Reference: #19964, #48351.
Side note: #49712

And to set the story straight …  CMD.EXE does support UNC paths, just not for the CWD (which means you cannot do relative paths).

**Comment by alexr00** [comment]
Possibly related https://github.com/microsoft/vscode/issues/48351
