### ISSUE TITLE
Blue loading bar keep on showing 

### ISSUE THREAD

**Issue by mani-vandrangi** [microsoft/vscode#74254]
Issue Type: <b>Bug</b>

* Open a nodejs file
* write a require() with uninstalled node module
* click on the node-module

Behavior:
Blue loading bar starts on top of the file and will be keep on loading thereby unable to navigate to any of the symbols furthermore. 

Recovery:
Restart studio

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (5.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.1
dotenv|mik|1.0.1
vscode-docker|Pet|0.6.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mani-vandrangi** [comment]
I am unable to reproduce with insiders build
