### ISSUE TITLE
SCM: opening a binary diff looses focus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74268]
Steps to Reproduce:

1. have a change to a binary resource (e.g. PNG)
2. click it
3. :bug: changes view looses focus

**Comment by joaomoreno** [comment]
As always, this is invoking `vscode.diff` with `{preserveFocus: true}`. That seems to have broken.

**Comment by joaomoreno** [comment]
@bpasero This is being hit: https://github.com/Microsoft/vscode/commit/4929acf926a938505653ae20eff6fe18577a6044#diff-0f1abf8ff5283dac48ea3231f2dddfa0R217

**Comment by bpasero** [comment]
Up for grab.

**Comment by bpasero** [comment]
@sandy081 looks like this came in a long time ago via https://github.com/microsoft/vscode/commit/8692734a1b88a8e73045a739bb91589e8bb73eb9

I do not understand why the editor would need to give itself `focus()`. Typically that should not be needed as the container of editors will call `focus()` as needed.

**Comment by sandy081** [comment]
Honestly, I do not remember why the change is but I think the change is for side by side settings editor. Settings editor is no longer using `SideBySideEditor`. So this line can be removed.
