### ISSUE TITLE
outputChannel clear api can not work for large content in the outputChannel

### ISSUE THREAD

**Issue by chongchai** [microsoft/vscode#74262]
- VSCode Version: 1.31.1
- OS Version: windows 10

Steps to Reproduce:

1.  use `outputChannel.append()` to append large content(A) in the output. (content is about 40MB)
2.  use `outputChannel.clear()` to empty the outputChannel
3.  use `outputChannel.appen()` to append a small content (B)
4.  the output will show small content (B) and large content(A). It seems the clear api is not working here.

I read the source code and find the file `https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/output/node/outputAppender.ts` limit the file size to `1024 * 1024 * 30`. Is this size cause my problem?

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
Yeah output channel max out at 30 MB. It is recommended to append small chunks to data in output channel. Let me know if that works

**Comment by chongchai** [comment]
@sandy081  Thanks for your reply. 
I did append small chunks, while total data is about 40MB. After invoke clear() api, I append small data to the output channel, the output shows the old content which should be cleared.

Two questions.
1. Is output channel's showing content will be not correct after data size over 30MB？
ps: I have the same extension behavior in the old vscode release (1.25.1). The content in the output is correct after data size over 30MB.

2. Can clear() api really empty the log file?

**Comment by sandy081** [comment]
@chongchai Can you please provide me the steps and set up to repro?
