### ISSUE TITLE
Improve Html editot

### ISSUE THREAD

**Issue by zareshahi** [microsoft/vscode#74261]
Issue Type: <b>Feature Request</b>

Hello Dear
I'm a web frontend develepor. I used phpstorm and webStorm before vscode and they was better than vscode in css and html autoComplete , refrences , auto rename tags and linking but vscode placed this featured in extentions and dont have this features basically.
please improve html and css edditing experience and intelligence as well as webstorm and phpstorm without any extra extentions.
i wish see my favorite editor in the top 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.19.0-5-amd64

**Comment by octref** [comment]
Please give specific feature requests.
