### ISSUE TITLE
Files owned by root in $HOME/.vscode/extensions causes error "We cannot connect to the Extensions Marketplace"

### ISSUE THREAD

**Issue by kbakk** [microsoft/vscode#74266]
- VSCode Version: 1.34.0
- OS Version: macOS 10.14.5

Steps to Reproduce:

I am not certain what caused this, but symptomes were:

* Listing `@installed` in Extensions would show error `We cannot connect to the Extensions Marketplace at this time, please try again later.`
* Already installed extensions would show an _Install_ button next to it in the extensions list
* Files owned by root in `$HOME/.vscode/extensions`: 

        ls -la /Users/kristofferb/.vscode/extensions/
        total 8
        drwxr-xr-x  49 kristofferb  staff  1568 May  7 10:56 .
        drwxr-xr-x   4 kristofferb  staff   128 Apr  5  2018 ..
        -rw-r--r--   1 root         staff   231 May  7 12:43 .obsolete
        drwxr-xr-x   9 kristofferb  staff   288 Oct 20  2018 adamhartford.vscode-base64-0.1.0
        drwxr-xr-x  11 kristofferb  staff   352 Feb 16 19:13 akamud.vscode-theme-onelight-2.1.0
        drwxr-xr-x   7 kristofferb  staff   224 Jul  9  2018 bibhasdn.unique-lines-1.0.0
        drwxr-xr-x  16 kristofferb  staff   512 Dec  7 13:26 bungcip.better-toml-0.3.2
        drwxr-xr-x  12 kristofferb  staff   384 Apr  7 08:10 castwide.solargraph-0.19.6
        drwxr-xr-x  10 kristofferb  staff   320 Mar 12 09:36 cstuder.gitlab-ci-validator-1.0.0
        drwxr-xr-x  12 kristofferb  staff   384 Apr  8 09:23 davidanson.vscode-markdownlint-0.26.0
        drwxr-xr-x  11 kristofferb  staff   352 Mar  8 14:20 dbaeumer.vscode-eslint-1.8.2
        drwxr-xr-x  26 kristofferb  staff   832 Feb 19 14:29 donjayamanne.githistory-0.4.6
        drwxr-xr-x  16 kristofferb  staff   512 Dec 17 11:43 dotjoshjohnson.xml-2.4.0
        drwxr-xr-x  10 kristofferb  staff   320 Apr 23 13:58 eamodio.gitlens-9.6.3
        drwxr-xr-x  10 root         staff   320 May  7 10:56 eamodio.gitlens-9.7.1

The reason files are owned by root is probably that VS Code has been launched as root at some point (May 7th apparently), and updated extensions. 

Does this issue occur when all extensions are disabled?: Not able to reproduce, can't check

Workaround:

I was able to fix this by running

```sh
sudo find $HOME/.vscode/extensions -user root -exec chown $USERNAME {} \;
```

**Comment by joaomoreno** [comment]
@kbakk Did you run Code as `sudo` at any point in time?

@sandy081 We should fix the error message.

**Comment by joaomoreno** [comment]
> The reason files are owned by root is probably that VS Code has been launched as root at some point (May 7th apparently), and updated extensions.

Yup.. that seems to have been the problem.

**Comment by sandy081** [comment]
Fixed it by showing the appropriate message for the request

![image](https://user-images.githubusercontent.com/10746682/58822667-555d9e00-8638-11e9-930c-a52677195bfb.png)

![image](https://user-images.githubusercontent.com/10746682/58822799-9b1a6680-8638-11e9-9327-1e4727b91cb2.png)
