### ISSUE TITLE
Broken one line structs declaration highlighting in C\C++

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode#74260]
- VSCode Version: 1.34.0
- OS Version: Linux x64 5.0.16-300.fc30.x86_64
![Screenshot from 2019-05-24 10-36-15](https://user-images.githubusercontent.com/31858171/58310641-c8347100-7e0f-11e9-9e51-896af03b41ab.png)

**Comment by alexr00** [comment]
Fixed in insiders already. We need more C++ users on Insiders to help catch issues like this before they make it to stable. Insiders and stable can be installed side by side. If you're interested, you can get insiders [here](https://code.visualstudio.com/insiders/).

**Comment by Iipal** [comment]
@alexr00 thanks a lot
