### ISSUE TITLE
Terminal starts with weird font

### ISSUE THREAD

**Issue by Haroenv** [microsoft/vscode#74267]
Issue Type: <b>Bug</b>

The terminal font seems to not be remembered. It's set to `SF Mono` as my editor font, and if I set something (doesn't matter what) as terminal font, and then remove it again, it works like it used to 

<img width="701" alt="Screenshot 2019-05-24 at 11 25 54" src="https://user-images.githubusercontent.com/6270048/58317854-f4072500-7e16-11e9-8096-34eb2e593f87.png">

It also happens upon opening a new terminal, with the same "fix"

VS Code version: Code - Insiders 1.35.0-insider (94f7de61ece171f4390ece488a220d22cbb0fddd, 2019-05-23T05:15:43.589Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 6, 4|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
fish|Ted|0.0.4
lorem-ipsum|Tyr|1.2.0
markdown-checkbox|bie|0.1.3
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.1
prettier-vscode|esb|1.9.0
flow-for-vscode|flo|1.1.1
reasonml|fre|1.0.38
vscode-pull-request-github|Git|0.7.0
vscode-hacker-typer|jev|0.1.1
theme-karyfoundation-themes|kar|18.2.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
cpptools|ms-|0.23.1
vscode-typescript-tslint-plugin|ms-|1.1.0
vetur|oct|0.21.0
laravel-blade|one|1.20.0
vscode-jest|Ort|2.9.2
vscode-code-outline|pat|0.2.1
sass-indented|rob|1.5.1
slim|sia|0.1.2
mdx|sil|0.1.0
code-spell-checker|str|1.7.10
ab-html-formatter|zov|0.0.2

(2 theme extensions excluded)

</details>

**Comment by Haroenv** [comment]
I just updated to VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:15:17.681Z)
OS version: Darwin x64 18.2.0 and it still happens :)

**Comment by richardchien** [comment]
I have the same problem after upgrading to 1.35.0-insider:

![image](https://user-images.githubusercontent.com/5317095/58325908-d90bd380-7e5d-11e9-8213-e0915aaa3b32.png)

The terminal:

![image](https://user-images.githubusercontent.com/5317095/58325959-05275480-7e5e-11e9-8644-5f408bce39d5.png)

It only happens while I am using Remote Developement SSH, and is normal when opening PowerShell on Windows.

**Comment by Haroenv** [comment]
seems like this is a duplicate of https://github.com/microsoft/vscode/issues/74183
