### ISSUE TITLE
ubuntu19.04 space is too small

### ISSUE THREAD

**Issue by yueshuiniao** [microsoft/vscode#74278]
- VSCode Version: 1.34.0
- OS Version: ubuntu 19.04

版本: 1.34.0
提交: a622c65b2c713c890fcf4fbf07cf34049d5fe758
日期: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-15-generic

Does this issue occur when all extensions are disabled?: Yes

The space is small, only half a letter long
![image](https://user-images.githubusercontent.com/17233090/58327843-3a827100-7e63-11e9-8aef-bf27c2669139.png)

**Comment by alexandrudima** [comment]
@yueshuiniao The width of the space character is determined by the font. Also from your screenshot I can see that the space character is quite thin in other places (like in the line `const fs = require('fs')`). What font family are you using? Have you tried other fonts? Monospace fonts tend to have a wide space character, but it looks like you're not using a monospace font.

**Comment by yueshuiniao** [comment]
@alexandrudima yes, you are right, it's the problem of the fonts. My fonts setting is 
    'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'
I try to remove 'Droid Sans Mono',  and it is normal, great!
Thank you very much!
