### ISSUE TITLE
Running SQL code has stopped working

### ISSUE THREAD

**Issue by RogerSpencelayh** [microsoft/vscode#74279]
Issue Type: <b>Bug</b>

Running a .sql query using the mssql extension, no data is showing in the Results window. I am running the latest Insiders release, updated about 07:00 this morning UK time. It was working fine yesterday, and is working in the production version of VSCode.

VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:18:40.781Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer|Coe|1.0.61
vbscript|Dar|1.0.4
vscode-markdownlint|Dav|0.26.0
xml|Dot|2.4.0
sepaswitch|Fut|1.0.2
gc-excelviewer|Gra|2.1.32
vscode-peacock|joh|2.1.2
VBScript|lug|0.0.2
rainbow-csv|mec|1.0.0
mssql|ms-|1.6.0
powershell|ms-|2.0.2
snippet-creator|nik|0.0.5
printcode|nob|3.0.0
indent-rainbow|ode|7.4.0
sql-snippets|sad|0.0.4
vba|spe|1.2.0
vba-snippets|spe|1.0.1
vscode-vba-icons|spe|1.0.2
vscode-icons|vsc|8.6.0
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by alexr00** [comment]
It looks like that extension recently updated too. Can you confirm that you have the same version of the extension in both Insiders and in the production version of VS Code?
