### ISSUE TITLE
Add string to selection with CTRL + double click?

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#7427]
In every advanced text editor I've used in the last few years holding CTRL and double clicking adds the string under the cursor to the current selection.

Is there a reason this doesn't work in VS Code or has it not been implemented yet?

**Comment by alexandrudima** [comment]
@Instagit would ALT + double clicking do the trick for you? The reason is that CTRL + clicking is taken by the go to definition feature. I have a feature request to allow to customize the mouse bindings, and we need to do that soon

**Comment by Instagit** [comment]
Thanks for looking into this. ALT + double click will do just fine. When it's configurable some time in the future, that'll be perfect :)

**Comment by alexandrudima** [comment]
This is customizable since quite some time via `editor.multiCursorModifier`
