### ISSUE TITLE
Terminal crashed when opened first time (Windows)

### ISSUE THREAD

**Issue by rulyotano** [microsoft/vscode#74276]
Issue Type: <b>Bug</b>

* Open first time VS or open a new terminal
* When start writing text appear in anywhere long away from where it should be
* After executing first command all work as expected, so we can deal with it

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
clipboard-history|Anj|1.0.7
simple-react-snippets|bur|1.2.2
vscode-postgres|cko|1.1.10
xml|Dot|2.4.0
es7-react-js-snippets|dsz|2.3.0
vscode-npm-script|eg2|0.3.7
beautify|Hoo|1.5.0
vscode-regexp-preivew|le0|0.0.3
csharp|ms-|1.19.1
material-icon-theme|PKi|3.7.0
code-spell-checker|str|1.7.10
blueprint|tea|3.0.0
vscode-todo-highlight|way|1.0.4
ReactSnippets|xab|2.3.0

</details>

**Comment by songmikim24** [comment]
i have the same bug.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by sptndc** [comment]
I have same issue after update Windows 10 to new version.
