### ISSUE TITLE
[dot net WEBAPI project]Invoke WebApi from postman 

### ISSUE THREAD

**Issue by sonisudarshan0** [microsoft/vscode#74275]
🚨 The issue tracker is not for questions 🚨

I created New DotNet WebApi project using visual studio code version 1.34.0 in .Net Core and trying to get response from postman 

when i tried to run dotnet application using `dotnet run` command in terminal window it shows :+1: 
![Untitled2](https://user-images.githubusercontent.com/50704950/58321869-fe3c1a00-7e3c-11e9-81b4-76cff02f4ec8.png)

Result is `Application started. Press Ctrl+C to shut down.` and when i tried to GET response by using postman it shows:-1:

`Could not get any response
There was an error connecting to http://localhost:5000/api/values.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General`

![Untitled](https://user-images.githubusercontent.com/50704950/58322042-71de2700-7e3d-11e9-91dd-c8ca21c3a1c2.png)

Where as in visual studio code it shows
 `info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
  Request starting HTTP/1.1 GET http://localhost:5000/api/values
  info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
  Request finished in 11.8395ms 307` when i hit that **Send** button in POSTMAN

![Untitled2](https://user-images.githubusercontent.com/50704950/58322391-73f4b580-7e3e-11e9-809c-d35e3a0a8577.png)

**Comment by alexr00** [comment]
Since this question is about .NET, please create the issue in that extension's repository.
