### ISSUE TITLE
Exception in terminal alt buffer

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#74273]
@Tyriar Something has changed lately. The tmux issue we talked about (render missing) now often doesn't even resolve itself when resizing the pane. I noticed this in the dev tools, maybe it helps:

![image](https://user-images.githubusercontent.com/22350/58321351-354f0300-7e1e-11e9-87a0-55ab7bad10f6.png)

Can't figure out repro steps tho... not sure what triggers this state and what causes the terminal to get out of it.

**Comment by Tyriar** [comment]
I think this is related to a fix for tasks that @alexr00 and I did, I'll be more defensive.

**Comment by Tyriar** [comment]
Verification:

1. Run tmux
3. Run some commands
