### ISSUE TITLE
Suggest: missing highlights on auto mode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#74271]
1. Open a .ts file
2. Type console.l

Highlights are missing. Pressing <kbd>Escape</kbd> and <kbd>Ctrl Space</kbd> will show the highlights.

![image](https://user-images.githubusercontent.com/22350/58320358-c5d81400-7e1b-11e9-9ab4-1ffad6a18617.png)

@jrieken I noticed some work was done here lately. Adding you in case it rings any bells.

**Comment by jrieken** [comment]
sure you are on latest **!** insider?

**Comment by joaomoreno** [comment]
Fixed in latest.
