### ISSUE TITLE
Git: Commit Multi-line Support

### ISSUE THREAD

**Issue by fordarnold** [microsoft/vscode#74286]
Support for [git commit -m "Message..." -m "Longer message..."](https://twitter.com/meridiansw/status/1131925711105736705).

Hey @joaomoreno, I'm hoping this issue isn't a duplicate for https://github.com/microsoft/vscode/issues/2718... 

This feature would be a major boost, because at the moment, I always have to go back to the terminal and type it (git commit -m "Message..." -m "Longer message...") myself. I'm thinking the git commit text-box could be extended to support this multi-line, instead of single-line only (see image below).

Thanks.

![git commit UI on VS Code](https://www.virtualizationhowto.com/wp-content/uploads/2017/08/Type-commit-and-enter-to-finalize-the-commit.png)

**Comment by msftrncs** [comment]
@fordarnold, have you tried to use the SVM viewlet to commit?   I always post multiline comments when I commit.

![image](https://user-images.githubusercontent.com/26179051/58355649-b9af7f00-7e3a-11e9-9f41-d08c457be1d3.png)

**Comment by joaomoreno** [comment]
Yeah, multiline is supported in the view itself.

**Comment by fordarnold** [comment]
Woooooah, nice!!! I'd never seen in all my days of using VS Code 🤦‍♂ 😁

Thanks @msftrncs @joaomoreno !

![VS Code - git multiline commit](https://user-images.githubusercontent.com/1271441/58414660-57de5780-807c-11e9-9955-e3cb061d4b74.png)
