### ISSUE TITLE
Incorrect error when spreading a string

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#74283]
Issue Type: <b>Bug</b>

Please consider this bit of code:

```typescript
const str = 'yolo';
console.log([...str]);
```

On the second line, it will show red curlies with an error popup saying

> Type '"yolo"' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators. ts(2569)

That's not correct. Type `"yolo"` is definitely a string type. But let's try giving it what it wants:

```typescript
const str: string = 'yolo';
console.log([...str]);
```

Now `str` is explicitly a string, right? The curlies remain, but the error behind them is different:

> Type 'string' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators. ts(2569)

Type string is not a string type. Are you kidding me?

I'm not doing anything with a compiler. Just testing the editor. But if you must know: this code (both cases) compiles perfectly well, and *works* too. VSCode is using its own built-in typescript 3.4.5.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.4.3
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
duplicate|gee|1.0.1
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.9
vscode-svg-previewer|vit|0.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Same root cause as https://github.com/microsoft/TypeScript/issues/31656, `"target": "es5"`

Just add a  `"downlevelIteration": true` flag if you need to still target `es5`
