### ISSUE TITLE
UX: switch to octicons for all icons in the status bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74285]
This ensures that everything in the status bar is nicely aligned. Currently I always feel like the problems entry as well as the "Send Feedback" smiley are not aligned properly:

![image](https://user-images.githubusercontent.com/900690/58332521-b36dd280-7e3b-11e9-8333-3ee2f039dd18.png)

Steps:
* add required icons to our font
* adopt in everywhere we use a SVG icon

PR: https://github.com/microsoft/vscode/commit/350708a11f68a836e2196ce8a8239d6a76344325

**Comment by misolori** [comment]
I've updated Octicons to include these:

<img width="152" alt="image" src="https://user-images.githubusercontent.com/35271042/58375884-57c24880-7f12-11e9-81bd-b5f88083db99.png">

**Comment by bpasero** [comment]
@misolori can you give me a hint where we are using the gear icon and where we are using the download icon? I could only find the task icons and smiley.

PS: we would also need an info icon, tasks can show info/warning/error.

**Comment by misolori** [comment]
I got the gear from the tasks folder here:

https://github.com/microsoft/vscode/tree/master/src/vs/workbench/contrib/tasks/common/media

It appears though that it's used in the quick pick only. I also didn't realize we already have a gear in Octicons so I can remove this. The download/task icon is from here:

https://github.com/microsoft/vscode/blob/8369f6e7fe71b529ce05018b51ebae9445e63fd5/src/vs/workbench/contrib/tasks/common/media/task.contribution.css#L26-L33

I've seen that task icon before but can't get it to come up again, maybe @alexr00 can tell us.

For the info, can we use the existing `info` Octicon?

<img width="100" alt="image" src="https://user-images.githubusercontent.com/35271042/58385316-6442b180-7fa3-11e9-8635-a31505123371.png">

**Comment by bpasero** [comment]
@misolori yeah I guess we can use existing icons for that

**Comment by alexr00** [comment]
I don't see the download/task icon used anywhere.

**Comment by bpasero** [comment]
**Verification:** there are no more SVGs used in the status bar, specifically:
* errors, warnings and infos are shown with their icons and clicking toggles the problems view
* you see the "Send Feedback" smiley properly and can click it
* running something from debug shows the current launch config in the status bar with a play icon to the left
* running something from the debug shows "Building" briefly and indicates active tasks (try with typescript generated extension)

**Comment by bpasero** [comment]
/cc @dbaeumer @alexr00 on https://github.com/microsoft/vscode/commit/8c358072716a394625c800b8276ac34d29ffd671 and https://github.com/microsoft/vscode/commit/af9cd4e8f23757a146f7849805364e802be3985b. The task related status bar contributions are no longer in need to render the full contents, rather they now use the more lightweight `IStatusBarEntry` where you can set properties as JSON.

The biggest change was around the status bar entry for showing errors, warnings and infos. Previously this where a couple of HTML elements / icons, and now it is just one label with octicons. I tried to preserve the behaviour we currently have. One thing to reconsider is to maybe move the "Building..." decoration that seems to be there when a task is active out. We have a progress service that can render progress messages on the status bar.

**Comment by dbaeumer** [comment]
Will make sure I have an eye on it the next days.

**Comment by alexr00** [comment]
I've taken a look and the task use of the status bar and it still looks ok!
