### ISSUE TITLE
Make SourceControlResourceGroup collapsible

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#74280]
Issue Type: <b>Feature Request</b>

Please add twisties to each SourceControlResourceGroup so the user can collapse the group instead of having to scroll past it.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/14582
