### ISSUE TITLE
Visual Studio Code Insiders Remote Development fails with multiple ssh_config aliases

### ISSUE THREAD

**Issue by jethrogillgren** [microsoft/vscode#74288]
- VSCode Version: 1.35.0-insider 
- OS Version:  Mac OS Mojave 10.14.5

Steps to Reproduce:

1. Follow the instructions for remote code development: https://code.visualstudio.com/docs/remote/ssh
2. Edit your ~/.ssh/config file to use multiple aliases, for example:

```
    host server018 mongodb-box
        hostname 192.168.3.1
```

The error reads:

> Can't connect to server018 mongodb-box : unreachable or not Linux x86_64 (bash: mongodb-box: command not found)

Does this issue occur when all extensions are disabled?: N/A - Issue is with an extension.

**Comment by roblourens** [comment]
This works for me, can you share the full log from the Remote-SSH output channel?
