### ISSUE TITLE
Standard themes force SourceControlResourceGroup titles to UPPERCASE

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#74281]
Issue Type: <b>Bug</b>

We are developing an extension that implements a source control provider.  It  successfully adds `SourceControlResourceGroup`s to its section. However the standard themes display the group captions in UPPERCASE by styling them with `text-transform: uppercase`

For our use case it's important to show the group captions in their actual case. AFAIK there isn't a way for our extension to make that happen.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
Yeah... let's then change the casing style and just uppercase them on the Git extension directly.

**Comment by skprabhanjan** [comment]
@joaomoreno , Removing the styling [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/scm/browser/media/scmViewlet.css#L76), is that it or I should add it somewhere ? Because you said 

>  just uppercase them on the Git extension directly

**Comment by joaomoreno** [comment]
Yeah we want to keep the git extension section as `CHANGES`, etc.

**Comment by skprabhanjan** [comment]
@joaomoreno , Could not find the exact detail of what to remove.
Removing the style [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/scm/browser/media/scmViewlet.css#L76) will remove it in all places , so that is not correct. I dont understand what **group captions** actually mean ( CC : @gjsjohnmurray , if you could help )
I found there are these ResourceGroup (` merge,index and workingTree`) for which the style is applied. 
Please help me out with this on the correct approach.

**Comment by gjsjohnmurray** [comment]
@skprabhanjan I think @joaomoreno proposes that you **do** remove that style, but that you also change the code [here](https://github.com/microsoft/vscode/blob/2e61cfb5dc9ee22341b8ab423b23cc5018a83bf8/extensions/git/src/repository.ts#L586) to explicitly uppercase the localized captions of the the three `SourceControlResourceGroup` items being created there.

With those changes Git users won't see any change of behaviour, but other SCM extensions can set mixed-case captions and have them display to the end user.

**Comment by skprabhanjan** [comment]
@gjsjohnmurray , Sorry got confused with the group captions , Sent a PR to fix this !

**Comment by gjsjohnmurray** [comment]
@skprabhanjan I'd love to see your PR get merged, but for some reason I don't understand it apparently failed in the Windows part of Azure Pipelines. @joaomoreno can you help get this moving?

**Comment by skprabhanjan** [comment]
> but for some reason I don't understand it apparently failed in the Windows part of Azure Pipelines

The windows build error might be some random errors , Happened in one more PR ( https://github.com/microsoft/vscode/pull/74795#issuecomment-499435726)
I guess that is not an issue and @joaomoreno should confirm that.
