### ISSUE TITLE
Freezes on macOS 10.13.6 wake from sleep

### ISSUE THREAD

**Issue by tedfitzpatrick** [microsoft/vscode#74294]
- VSCode Version: 1.34.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open files from network shares then put Mac to sleep
2. Awaken Mac from sleep

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by sampotts** [comment]
This is still an issue in the latest version (1.35.1) on 10.14.5. Is there any work in progress on it? It seems that the wake from sleep will disconnect the network shares (main issue) and then Code freezes and shows the "not responding" message with options to wait , reload or close. If you reconnect the SMB share and then reload, you'd expect the same files to reopen but they don't. Previous behaviour seemed to be that Code would complain the file wasn't found and reconnecting the network share would resume normal behaviour. Any way we could revert to that?
