### ISSUE TITLE
Offline Release

### ISSUE THREAD

**Issue by jose-pr** [microsoft/vscode#74296]
Related issue:
 https://github.com/Microsoft/vscode/issues/54354 Was worked stop for this?
https://github.com/MicrosoftDocs/intellicode/issues/102 Is actually for an extension but it is the same problem (download of schemas and none included by default) and is code by Microsoft too.
So it looks like a trend to require downloads after installation for features to work instead of providing a base copy of the schemas and features that dont actually require internet connection to work out of the box. 

This feature is needed for highly protected networks with extremely limited access to the internet such as countries like China, corporate sensitive networks, or even government networks with limited to no access to the internet.

Maybe make the schemas their own package so you can download them and any extensions that needs them can use them/have the package as a dependency?

**Comment by alexandrudima** [comment]
@jose-pr I can think of the following steps:
1. Have a machine without internet
2. Install VS Code
3. "something" does not work

What exactly is the "something" that does not work so I can route this issue to the right owner?
