### ISSUE TITLE
Debug: introduce setting to not save before starting debugging

### ISSUE THREAD

**Issue by dhasilva** [microsoft/vscode#74299]
As in https://github.com/Microsoft/vscode/issues/21681, whenever the debugger connects, all my unsaved files are automatically saved, even though I have explicitly set `files.autoSave` to `off`.
My use case is that I keep the debugger waiting for a connection. Whenever I save a file it triggers my test runner (`mocha` with `--inspect` flag) to run the tests for that file **only**.

Expected behavior is `files.autoSave = false` to be respected at all times, without VSCode saving my files without my consent. When VSCode saves my unsaved files it triggers all the tests and I lose track of what I was doing since I'm editing multiple files at once. I need a way (maybe a separate option?) to disable this behavior, as this is seriously disrupting my workflow.

- VSCode Version: 1.26.1
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Have an unsaved named .js file
2. Attach the debugger

My `launch.json` configuration:
```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach debugger to app (Docker)",
      "type": "node",
      "request": "attach",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/app",
      "port": 9222,
      "restart": true,
      "skipFiles": [
        "<node_internals>/**/*.js",
      ],
      "timeout": 28800000 // 8 hours
    },
    {
      "name": "Attach debugger to mocha (Docker)",
      "type": "node",
      "request": "attach",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/app",
      "port": 9223,
      "restart": true,
      "skipFiles": [
        "<node_internals>/**/*.js",
      ],
      "timeout": 28800000 // 8 hours
    }
  ]
}
```

**Comment by isidorn** [comment]
VSCode always saves all files before starting debugging.
I will leave this issue open as a feature request to introduce a setting to disable vscode debug doing the save.
