### ISSUE TITLE
ctrl-c in terminal

### ISSUE THREAD

**Issue by zorban** [microsoft/vscode#74298]
Issue Type: <b>Feature Request</b>

Please make ctrl-c clears text entered in terminal.

e.g. if you accidentally enter (paste) some text you have to delete it using backspace.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
