### ISSUE TITLE
Can't search.exclude top level workspace directories

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#74307]
I have a project with the following directory structure

```
- test/
  source.cpp
  - build/
    - generated/
       generated.h
        ... lots of files ...
```

I have a workspace with `test/` (`build/` is in `files.exclude`) and `generated/` as top level folders. I don't want to see 90% of `build/` but there are a few generated special files I want to be able to easily open and inspect. Everything up to this point works fine.

The issue is that I don't wanted the contents of files in `generated/` showing up when I search. Since the glob patterns appear to be relative to top level directories I can't find any way to exclude the contents of `generated/` from search.

Example attached.
[test.zip](https://github.com/microsoft/vscode/files/3218817/test.zip)

**Comment by roblourens** [comment]
Sorry for the delayed response. I think you just want to add `"search.exclude": { "**": true } ` in generated's folder settings (`.vscode/settings.json`) right?

You are right that there is no way to set folder-specific settings in a workspace. That shouldn't be necessary because folder-specific settings already exist. Maybe you would want different settings applied to a folder in a workspace context vs single folder context. There is also https://github.com/microsoft/vscode/issues/70438 for this

**Comment by akbyrd** [comment]
I don't think I'm asking for "folder specific settings in a workspace". That's certainly a possible solution and one that is more general, but I think a smaller, more targeted solution is reasonable here. All I want is for settings with paths such as `files.exclude` and `search/exclude` to accept paths that start with the top level folder. It's possible to do this without changing the current default behavior and without causing the behavior to differ in single root and multi root scenarios.

There are a couple issues with expecting the settings to be in individual sub-folders
* They aren't always 'projects' with their own settings. I don't want to have an extra directory and settings file in a folder just because I want to hide some files in a workspace.
* When the folder is a generated any local settings will get deleted on clean builds.
* It doesn't interact well with version control. Now I have to version settings inside a generated folder that shouldn't be in VCS.
* I'm hoisting sub-folders up to top level workspace folders. Needing to put the settings in the folder implies that I'd have nested folder settings. (e.g. project/ would have settings and project/build/generated/ would have settings).

Another way of looking at this problem is that things like `search.exclude` can be contextual based on your current workspace and therefore should be configurable from the workspace settings. For example, I have a workspace that is primarily made to work on Project A, but I have Project B included as a top level folder. However, I really only want to see files from Project A in Quick Open and Search. Project B is only there to occasionally get to files in the Explorer.

This happens to be quite close to the common way I structure my workspaces.

**Comment by roblourens** [comment]
Let's continue this in #70438 in case others have a comment as well. Copying your reply.
