### ISSUE TITLE
Terminal (powershell) weird behavior

### ISSUE THREAD

**Issue by Rod-Sychev** [microsoft/vscode#74300]
Issue Type: <b>Bug</b>

Basically when using terminal (I use it for powershell scripting) every once in a while I see that upon entering (or pasting) a command the gap appears (about half a screen size) between the lines on the screen that is rather inconvenient and looks bizarre.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
azds|azu|1.0.120190514
EditorConfig|Edi|0.13.0
cshtml-tm|fir|1.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
azure-pipelines|ms-|1.152.0
vscode-kubernetes-tools|ms-|1.0.0
azurecli|ms-|0.4.5
csharp|ms-|1.19.1
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|1.12.1
team|ms-|1.149.2
webapplicationservices|Opa|6.10.0
vscode-docker|Pet|0.6.2
vscode-yaml|red|0.4.0
opa|tsa|0.2.2

</details>

![Capture-1](https://user-images.githubusercontent.com/6485837/58352192-e2367980-7e38-11e9-8b13-db83221695d9.JPG)
![Capture-2](https://user-images.githubusercontent.com/6485837/58352193-e2cf1000-7e38-11e9-8538-6f0473e64aee.JPG)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
