### ISSUE TITLE
Test JS/TS smart select 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74309]
Test for #74243 

- [x] any @roblourens
- [x] any @chrmarti

Complexity: 2

**Overview**
Smart select is now enabled for javascript and typescript. Try using this feature in a variety of js/ts files and note if it does not work as expected

**Comment by diabolicle** [comment]
Using smart select before a word separator now selects the separator instead of the word before the separator. For example:

```
item|(arg)
```

Running smart select on the above selects "(" instead of "item" -- a behavior I find inconvenient as I've grown used to selecting words when the cursor is after the word.
