### ISSUE TITLE
Test DocumentLink.tooltip proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74311]
Test for #72824

- [x] Mac @bowdenk7
- [x] Linux @Tyriar
- [x] Windows @sana-ajani

Complexity: 3

**Overview**
#72824 tracks a new proposal to add a `DocumentLink.tooltip` field. This lets extensions customize the hover text of document links

**Testing**
Use the [ContentProviderSample](https://github.com/microsoft/vscode-extension-samples/tree/master/contentprovider-sample) and set a `tooltip` on the document links. Confirm that the tooltip is rendered as expected in the UI

Look over the api. Do you understand the property and how it should be used

**Comment by bowdenk7** [comment]
Looks great! The only thing that tripped me up was the `cmd + click to {0}` syntax mentioned [here](https://github.com/microsoft/vscode/issues/72824#issuecomment-495407641). Initially my tooltip was "cmd + click to see tooltip" which yielded `cmd + click to cmd + click to see tooltip`. This seems easy to solve with documentation, but I'm not sure I understand how localization impacts how I should phrase my tooltip.

Also, is there a reason this isn't an optional argument in the constructor?

**Comment by mjbvz** [comment]
The `cmd +click` text changes based on OS and some user settings so I think it needs to come from VS Code. I'll add a note on this to the `tooltip `property documentation
