### ISSUE TITLE
Terminal font messed up in WSL windows

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#74319]
Issue Type: <b>Bug</b>

Three simple steps:

1. Open WSL remote window
2. Look at terminal
3. Cringe

;-)

This is how the terminal looks on a local window:

![image](https://user-images.githubusercontent.com/6010463/58367561-182f3880-7ee1-11e9-9dd1-6cfb82528a26.png)

And this is on the remote window:

![image](https://user-images.githubusercontent.com/6010463/58367568-1feedd00-7ee1-11e9-85b2-da787e830d55.png)

Note that the colors are gone and a non-monospaced font is used which makes the output pretty unreadable. Also the cursor is invisible.

This seems to be a regression because it worked previously just fine.

This happens only in the terminal, by the way. The code editor displays normally. Also, it seems to happen only with WSL, not with SSH. (I didn't test the other remote options.)

**Update:**

The whole terminal style tag seems to be missing.

DOM tree on local window:

![image](https://user-images.githubusercontent.com/6010463/58367663-482b0b80-7ee2-11e9-863f-3446e1e0489c.png)

DOM tree on remote window:

![image](https://user-images.githubusercontent.com/6010463/58367667-4feab000-7ee2-11e9-8b9b-191b45c43beb.png)

No errors in the devtools other than #74321 which doesn't seem to be connected (I fixed it temporarily and the terminal was still broken).

VS Code version: Code - Insiders 1.35.0-insider (6b081a9f0089062b2cd105e1f1ab366591291534, 2019-05-24T21:28:41.464Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (4.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (4.64GB free)|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Doxygen|bbe|1.0.0
vscode-standardjs-snippets|cap|0.8.4
LogFileHighlighter|emi|2.5.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
VBScript|lug|0.0.2
dotenv|mik|1.0.1
remote-containers|ms-|0.54.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.36.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
ejs-language-support|Qas|0.0.1
vscode-autohotkey|sle|0.2.2
vscode-todo-highlight|way|1.0.4
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
Bookmarks|ale|10.4.3
vscode-color|ans|0.4.5
htmltagwrap|bra|0.0.7
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
bracket-select|chu|2.0.1
jsrefactor|cms|2.18.2
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.26.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
xml|Dot|2.4.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
RelativePath|jak|1.4.0
hungry-delete|jas|1.6.0
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
edge|luo|0.3.2
rainbow-csv|mec|1.1.1
ecdc|mit|1.0.5
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
node-modules-resolve|nau|1.0.2
prettier-standard-vscode|num|0.5.0
quicktype|qui|12.0.46
java|red|0.45.0
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.3.1
rewrap|stk|1.9.1
ignore-gitignore|stu|1.0.1
sort-lines|Tyr|1.8.0
bracket-padder|via|0.1.0
vscode-java-debug|vsc|0.18.0
quokka-vscode|Wal|1.0.216
change-case|wma|1.0.0
join-lines|wma|0.2.2
FilterText|yhi|0.0.14
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gwk** [comment]
I am also seeing messed up terminal text on macOS, on Insiders build for the last several days at least. In contrast to the original report, this is happening for me locally.

It is a problem even when running with extensions disabled.

Rendering looks messed up; selection is broken; ANSI colors are broken.

For example, in Apple terminal:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/406380/58370190-94ba1b00-7ed1-11e9-8d5c-749ccc742e55.png">

In VSCode:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/406380/58370197-a3083700-7ed1-11e9-8a32-1a2e3ce09186.png">

Build 6b081a9f0089062b2cd105e1f1ab366591291534.

**Comment by maxencefrenette** [comment]
Editing the `terminal.integrated.fontFamily` config setting works for me as a temporary fix. Every time I open a vscode instance, I simply edit the value of that setting and then set it back to my preferred value.

Also, this only seems to be happening when `terminal.integrated.rendererType` is set to `dom`.

**Comment by CherryDT** [comment]
Interesting. Because I tried setting the font too and that didn't change anything for me.

**Comment by kumarharsh** [comment]
I'm facing the same issue. This is not happening in the stable build, but only in the insider build

```
Version: 1.35.0-insider (user setup)
Commit: 16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
Date: 2019-05-27T05:19:20.616Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```

![image](https://user-images.githubusercontent.com/760112/58409419-9fb9aa80-808d-11e9-993e-4a15c1a1da03.png)

When I edit the settings to change the **Terminal > Integrated: Font Family** setting, the font magically gets fixed but only until the next start. FYI, I'm using the "Iosevka SS07" font for the terminal.

**Comment by kumarharsh** [comment]
As a workaround, you can set the **Terminal > Integrated: Renderer Type** to **Canvas** in settings to fix it for now.
