### ISSUE TITLE
Terminal UTF Broken

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#74318]
Issue Type: <b>Bug</b>

Seems the terminal got a bit of a damage.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/30625381/58366212-3d1ab000-7ecf-11e9-9e1a-309b1f662114.png">
<img width="134" alt="image" src="https://user-images.githubusercontent.com/30625381/58366222-5c194200-7ecf-11e9-9d0b-e245d78d4cc2.png">

VS Code version: Code - Insiders 1.35.0-insider (5e1f9440d280b0b04cba843df6a0032bf517a2f0, 2019-05-24T05:15:17.681Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|48, 19, 7|
|Memory (System)|16.00GB (3.62GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
pm2-explorer|ale|0.0.6
makeRunner|ale|0.1.2
sort-imports|ama|6.0.1
vscode-apollo|apo|1.6.9
atlascode|atl|1.4.0
vscode-custom-css|be5|3.0.4
better-phpunit|cal|1.4.0
twigcs|cer|0.4.2
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-storybook|cst|0.0.5
vscode-eslint|dba|1.9.0
vscode-dash|dee|2.1.0
gitlens|eam|9.8.1
toggle-excluded-files|eam|1.6.0
graphviz-preview|EFa|1.3.2
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
graphviz-markdown-preview|gee|0.0.7
vscode-architect|gil|0.0.4
vscode-pull-request-github|Git|0.7.0
sass-lint|gle|1.0.5
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
rest-client|hum|0.21.3
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
jenkinsfile-support|ivo|0.4.4
svelte-vscode|Jam|0.9.1
jenkins-pipeline-linter-connector|jan|1.1.7
webcomponent-generator|jer|1.0.4
puppet-vscode|jpo|0.18.0
vscode-gutter-preview|kis|0.19.0
vscode-commitizen|Kni|0.8.2
twig-language-2|mbl|0.8.6
dotenv|mik|1.0.1
remote-containers|ms-|0.54.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
vscode-remote-extensionpack|ms-|0.14.0
references-view|ms-|0.0.27
vsliveshare|ms-|1.0.249
debugger-for-chrome|msj|4.11.3
vscode-stencil-tools|nat|2.0.1
ts-prop-dag|nat|1.0.4
gremlins|nho|0.10.0
vscode-json-editor|nic|0.2.3
vscode-tap|num|1.0.2
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.7.0
vscode-css-peek|pra|2.2.0
ruby|reb|0.22.3
vscode-yaml|red|0.4.1
elastic|ria|0.13.3
make-auto-vars|rop|1.0.0
code-settings-sync|Sha|3.2.9
sourcegraph|sou|1.0.14
vscode-taskexplorer|spm|1.18.10
easy-snippet-maker|tar|0.0.6
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.6.0
snippet|vsc|0.5.1
vim|vsc|1.8.1
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3

(2 theme extensions excluded)

</details>

**Comment by gwk** [comment]
#74319 is probably the same issue.
