### ISSUE TITLE
Simple dialog breaks when typing in folder quickly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#74315]
SSH to local VM typing "dev/Tyriar"

![Kapture 2019-05-24 at 22 49 07](https://user-images.githubusercontent.com/2193314/58365251-3d3a9180-7e76-11e9-9762-79d962091a0a.gif)

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode-remote-release/issues/339
