### ISSUE TITLE
Ctrl+Alt+Arrow for multi-select fails on laptops and tablets

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode#7431]
- VSCode Version: 1.2.0
- OS Version: Windows 10 10586

I can't use keyboard based multi-select in the editor on my laptop (desktop is fine). Whenever I use Ctrl+Alt+Down instead of multi-select, my screen turns upside down. It's a Windows shortcut key to invert a screen. 

Visual Studio doesn't have this problem because it uses Alt+Shift+Arrow as the shortcut for multi-select.

**Comment by alexandrudima** [comment]
All keybindings can be customized. https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts

This issue is most likely caused by some Display Driver which can be configured to not globally react to these keybindings if you don't find the screen rotation useful.
