### ISSUE TITLE
Terminal: Emoji layout is not correct on Windows 10 1903

### ISSUE THREAD

**Issue by fcharlie** [microsoft/vscode#74314]
- VSCode Version:
```bat
:: code --version
1.34.0
a622c65b2c713c890fcf4fbf07cf34049d5fe758
x64
```

- OS Version:
```bat
:: cmd ver
Microsoft Windows [版本 10.0.18362.145]
```

I have a simple code to verify that the terminal supports displaying emoji. Visual Studio Code 1.34 does display emoji on Windows 10 1903, but the layout of emoji is confusing, which is characterized by insufficient character width or partial garbled display.

The complete example can clone [fcharlie/bela](https://github.com/fcharlie/bela) and then use cmake to build and run the corresponding fmt_test.exe.

**The final output uses WriteConsoleW**: [https://github.com/fcharlie/bela/blob/master/src/bela/stdwriter.cc](https://github.com/fcharlie/bela/blob/master/src/bela/stdwriter.cc)

**Windows Terminal** [commitid: 4c47631bf4aa907aad4f7088bc7edc7e5cde11b9](https://github.com/microsoft/terminal/commit/4c47631bf4aa907aad4f7088bc7edc7e5cde11b9) In addition to some emoji is too small, other emoji displays are correct. As shown below:

![image](https://user-images.githubusercontent.com/6904176/58364416-a2c66680-7ee6-11e9-9eb7-619bc9531524.png)

Visual Studio Code shows that emoji is confusing：
![image](https://user-images.githubusercontent.com/6904176/58364489-9bec2380-7ee7-11e9-8e5a-7b7ab23cea09.png)

The errors between [**Terminus**](https://github.com/Eugeny/terminus) and Visual Studio Code are the same as the following:
![image](https://user-images.githubusercontent.com/6904176/58364480-75c68380-7ee7-11e9-8d43-17ffb743bca2.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by fcharlie** [comment]
@Tyriar This should be the problem caused by xterm.js.

**Comment by Tyriar** [comment]
Unicode version detection is tricky, this is tracked in https://github.com/xtermjs/xterm.js/issues/1709
