### ISSUE TITLE
Exception: I see an error in the devtools:  TypeError: (intermediate value) is not a function

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#74321]
Issue Type: <b>Bug</b>

I see an error in the devtools:

```
  ERR (intermediate value) is not a function: TypeError: (intermediate value) is not a function
    at G.<anonymous> (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5514:813)
    at Generator.next (<anonymous>)
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:621
    at new Promise (<anonymous>)
    at n (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:34:398)
    at lifecycleService.when.then (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5514:699)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It seems to originate from here:

![image](https://user-images.githubusercontent.com/6010463/58367772-241bfa00-7ee3-11e9-89d2-12050309fccc.png)

To my knowing, `new Promise(...)` indeed yields a promise and not a function, so `new Promise(...)()` won't do any good...

VS Code version: Code - Insiders 1.35.0-insider (6b081a9f0089062b2cd105e1f1ab366591291534, 2019-05-24T21:28:41.464Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (4.70GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.83GB (4.68GB free)|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
Doxygen|bbe|1.0.0
vscode-standardjs-snippets|cap|0.8.4
LogFileHighlighter|emi|2.5.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
VBScript|lug|0.0.2
dotenv|mik|1.0.1
remote-containers|ms-|0.54.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.36.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
ejs-language-support|Qas|0.0.1
vscode-autohotkey|sle|0.2.2
vscode-todo-highlight|way|1.0.4
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
Bookmarks|ale|10.4.3
vscode-color|ans|0.4.5
htmltagwrap|bra|0.0.7
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
bracket-select|chu|2.0.1
jsrefactor|cms|2.18.2
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
vscode-markdownlint|Dav|0.26.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
xml|Dot|2.4.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
RelativePath|jak|1.4.0
hungry-delete|jas|1.6.0
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
edge|luo|0.3.2
rainbow-csv|mec|1.1.1
ecdc|mit|1.0.5
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
node-modules-resolve|nau|1.0.2
prettier-standard-vscode|num|0.5.0
quicktype|qui|12.0.46
java|red|0.45.0
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.3.1
rewrap|stk|1.9.1
ignore-gitignore|stu|1.0.1
sort-lines|Tyr|1.8.0
bracket-padder|via|0.1.0
vscode-java-debug|vsc|0.18.0
quokka-vscode|Wal|1.0.216
change-case|wma|1.0.0
join-lines|wma|0.2.2
FilterText|yhi|0.0.14
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bpasero** [comment]
Wow, another issue with our minifier it seems. I pushed a change that hope fixes it.
