### ISSUE TITLE
Electron 5.0.x: V8 Array.sort() implementation has changed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74324]
This explains 1 of the 3 test failures we see on the `electron-5.0.x `branch.

Upstream issue: https://github.com/nodejs/node/issues/27871

This is likely a fix on our end that we need to do by checking for each usage of sort and ensuring that we adhere to the spec which says: `compareFunction(a, b) must always return the same value when given a specific pair of elements a and b as its two arguments. If inconsistent results are returned, then the sort order is undefined.`

**Comment by bpasero** [comment]
I pushed a change for the test failure but we still need to make a pass over our code and ensure we do not have another case like that...

**Comment by devsnek** [comment]
quick correction: it changed in node 11.0.0

**Comment by bpasero** [comment]
I think we have to live with this change and be aware of regressions.
