### ISSUE TITLE
Test: Electron 4.0.x update

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74320]
- [x] Mac @weinand
- [x] Linux @rebornix
- [x] Windows @alexr00

Complexity: 3

We plan to update to Electron 4.0.x in June. Download the latest released **Code Exploration** build from [here](https://builds.code.visualstudio.com/builds/exploration) with commit: [`a2873dc8ba39ecacd83de7c8e431e5f5a3107d86`](https://github.com/Microsoft/vscode/commit/a2873dc8ba39ecacd83de7c8e431e5f5a3107d86).

**Verify:**
* our smoke tests pass when run against this build (in case of an error, compare with insiders to see if it is Electron related or not)
* do some exploratory testing covering some native pieces of the application
  * debugging (both a simple node.js application and a hello world extension): breakpoints, stepping etc.
  * keybindings
  * drag and drop
  * menus and context menus (native)
  * window management and multiple windows
  * fullscreen (macOS: also simple fullscreen via settings: `window.nativeFullScreen: false`)
  * macOS: Sierra Native Tabs (enable via settings: `window.nativeTabs: true`)
  * UI regressions
  * accessibility regressions (e.g. NVDA / macOS Speech)

**Comment by weinand** [comment]
The "'All References' to 'app'" smoke test failed (at least on macOS), but the same happened in Insiders too.

**Comment by bpasero** [comment]
Yeah thanks I noticed this as well. /cc @jrieken

**Comment by rebornix** [comment]
Didn't find any major issue and the only failing test is the same as above.
