### ISSUE TITLE
After installing the plug-in, vscode path awareness repeats.

### ISSUE THREAD

**Issue by qq326943819** [microsoft/vscode#74327]
- VSCode Version:1.34.0 (system setup)
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1.Install the plug-in Path Autocomplete
2.like this
![image](https://user-images.githubusercontent.com/32457006/58372186-98d74e80-7f4c-11e9-86cf-5fc422e5fea1.png)
3.I want to turn off the default path awareness in vscode.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Set `"javascript.suggest.paths": false` to disable builtin path intellisense

**Comment by qq326943819** [comment]
> 设置`"javascript.suggest.paths": false`为禁用内置路径智能感知

Thinks
