### ISSUE TITLE
'Go to Definition' feature should leverage existing open instances/tabs of a file instead of opening a new one

### ISSUE THREAD

**Issue by kavehv** [Microsoft/vscode#7432]
- VSCode Version: 1.3.0-insiders
- OS Version: 10.11.6
2481a7dad82f8e8d105c5329b4b6f20e15e9b27c
Steps to Reproduce:

1. Open a split screen editing instance with two C files, one that uses a function defined in the other.
2. Right click and hit "Go To Definition", this should move focus to the other already open file in the editor, not open another instance of the same file in the same side of the split.

**Comment by jrieken** [comment]
I like

**Comment by jrieken** [comment]
Stretch for June...

**Comment by jrieken** [comment]
2nd try in July

**Comment by kavehv** [comment]
Thank you so much for trying to get this in so quickly.  I'm running the insiders build, and this only half works.  If you have the source file with the function definition already showing in the second pane and hit "Go To Definition" on the first pane, it behaves as desired.  However, if the source file with the function definition is in open in a tab but is not the one displayed in the second pane, "Go To Definition" will still open a second instance of the file in the first pane.

**Comment by jrieken** [comment]
Fair request when using tabs tho bad when not using tabs. @bpasero - it seems the new `revealIfOpen` flag should behave different if tabs are enabled or not.

**Comment by jrieken** [comment]
Closing as I believe the current implemented does a good job. When using `tabs` an open tab is revealed, when not we don't jump to another editor slot (view column) cos that can be very distracting.

**Comment by kavehv** [comment]
Will there be another issue tracking the fix to 'revealIfOpen' flag?

**Comment by jrieken** [comment]
You mean 'revealIfOpen' as 'reveal in any editor pane if open', correct? I not a fan of that since a local command (like go to definition) should stay local (within that editor).

**Comment by kavehv** [comment]
No, I mean 'reveal in this editor (window) if it has a tab in any pane containing the file needed'.  All bets are off if the file is open in another window.

**Comment by Tyriar** [comment]
Verified. The fallback behavior is nice: It will open the definition if the file is open in the current group *unless* there is another editor group open with that file active.
