### ISSUE TITLE
Deleting item from Watch sometimes doesn't work

### ISSUE THREAD

**Issue by brunojuliao** [microsoft/vscode#74325]
Issue Type: <b>Bug</b>

I added an expression on Watch. Later, I asked to delete it. The expression remains there.
My project is a Flutter project.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
dart-code|Dar|3.0.2
flutter|Dar|3.0.2
githistory|don|0.4.6
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
angular-essentials|joh|0.6.1
Angular2|joh|7.1.6
vscode-peacock|joh|2.1.2
python|ms-|2019.4.12954
csharp|ms-|1.19.1
powershell|ms-|1.12.1
vscode-typescript-tslint-plugin|ms-|1.1.0
vsliveshare|ms-|1.0.249
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
angular-console|nrw|7.4.29
material-icon-theme|PKi|3.7.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can not reproduce.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please post the exact steps to reproduce this?
Thanks
