### ISSUE TITLE
find reference not work

### ISSUE THREAD

**Issue by cnjeffliu** [microsoft/vscode#74326]
Issue Type: <b>Bug</b>

Find all references returns no result 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.8.1
code-runner|for|0.9.9
referenceshelper|gay|0.2.3
CppSnippets|har|0.0.14
auto-comment-blocks|kev|1.0.1
vscode-clang|mit|0.2.3
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
Go|ms-|0.10.2
material-icon-theme|PKi|3.7.0
java|red|0.45.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-proto3|zxh|0.2.2

(1 theme extensions excluded)

</details>

**Comment by cnjeffliu** [comment]
Search the reference of anything, eg: variable, obj, function,  and get nothing.

**Comment by mjbvz** [comment]
Those are not steps to reproduce. See the guide. For example: what language are you working in?

**Comment by chiragkadam10** [comment]
I update vs code but this issue is not resolve....
