### ISSUE TITLE
VS Code failed to update: Failed to create file handle

### ISSUE THREAD

**Issue by aheil** [microsoft/vscode#74333]
VS fails to update due to a locked file handle.

![image](https://user-images.githubusercontent.com/509229/58374468-e056de00-7f3e-11e9-8576-a861e8d221f3.png)

This happens with every update attempt by VS Code.

[vscode-inno-updater-1558816621.log](https://github.com/microsoft/vscode/files/3219732/vscode-inno-updater-1558816621.log)

**Comment by joaomoreno** [comment]
If this keeps happening, I suggest to switch back to the System Setup, unfortunately.

/duplicate #47841
