### ISSUE TITLE
Very slow when opening large files

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#74331]
When I open a large file like `bootstrap.css` file it becomes very slow and sometimes it freezes like that

![m](https://user-images.githubusercontent.com/42807112/58373873-3161d480-7f35-11e9-839b-f2f8b27776a0.jpeg)

**Comment by minkir014** [comment]
Any look at this issue.

**Comment by alexandrudima** [comment]
@minkir014 Which bootstrap.css file do you open, specifically?

I have tried `bootstrap.min.css` (just remove the `.txt` ending)
[bootstrap.min.css.txt](https://github.com/microsoft/vscode/files/3430499/bootstrap.min.css.txt)

By default, the long line is not colorized (144k characters), but other than that the editor is responsive for me:
![image](https://user-images.githubusercontent.com/5047891/61858646-c5fd9a00-aec6-11e9-8d0e-471a916657ee.png)

**Comment by minkir014** [comment]
No, I mean the big one `bootstrap.css`

**Comment by alexandrudima** [comment]
Do you mean this one?
[bootstrap.css.txt](https://github.com/microsoft/vscode/files/3477742/bootstrap.css.txt)

This opens quickly for me and the editor is responsive:
![image](https://user-images.githubusercontent.com/5047891/62635936-ebfc5300-b938-11e9-8526-a3884fe66278.png)
