### ISSUE TITLE
Webview not given all theme variables

### ISSUE THREAD

**Issue by jertje260** [microsoft/vscode#74334]
- VSCode Version: 1.35.0-insider
- OS Version: windows 10

Steps to Reproduce:

1. Create a webview with an extension
2. check the style variables

Does this issue occur when all extensions are disabled?: Yes

The theme variables are not all passed along. They are listed [here](https://code.visualstudio.com/api/references/theme-color#lists-and-trees). For example the variable `--vscode-list-inactiveSelectionForeground` should be available, but only the background counterpart (`--vscode-list-inactiveSelectionBackground`) is availabe.

Below is a screenshot taken from the developer tools styles
![Code_-_Insiders_JL5FDQgoEy.png](https://puu.sh/DxeTQ/9a66fd1a0f.png)

**Comment by mjbvz** [comment]
@aeschli These theme colors do not have any set values by default (but some themes may customize them). Do you think there's a better way to surface this in webviews? I think omitting the variable if it is not set is reasonable

**Comment by aeschli** [comment]
You could set them to fully transparant. (#0000)

**Comment by mjbvz** [comment]
Thanks. I thought about this more and think that's ultimately worse than not setting the variable at it blocks you from using the `var(...)` fallback mechanism. 

Closing this as by-design. The expected approach would be to use `var(--vscode-list-inactiveSelectionForeground, #0000)` with whatever fallback value you wish to use
