### ISSUE TITLE
To exclude symlinks from files.exclude

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#74335]
Hello!

Excluding symlinks is possible only in the options `files.watcherEXclude`, `search.exclude` and in the `search.followSymlinks`. 

I want to exclude the symlinks from editor viewer in the option `files.exclude`.

**Comment by isidorn** [comment]
@roblourens are you doing something special for symlinks in `search.exclude`?

**Comment by gusbemacbe** [comment]
> how do you exclude symlinks with those options that do support it?

There are two alternatives:

1. Like `search.followSymlinks`, I would set `"files.followSymlinks": false"` in the `settings.json` file. In the command palette, I would select `Show symlinks in the editor view` or `Hide symlinks in the editor view`. 
2. The option `files.exclude` should be like:

```javascript
    "files.exclude": 
    {
        "**/.DS_Store": false,
        "**/.git": false
        "symlinks": true
    }
```

**Comment by isidorn** [comment]
Got it. This is a fair feature request. Leaving it open.
