### ISSUE TITLE
cursorWordLeftSelect (and the like) don't work everywhere

### ISSUE THREAD

**Issue by drew-wallace** [Microsoft/vscode#7433]
VSCode version: 1.2.0
OS: Mac OSX 10.11.3

Affected commands:  
- cursorWordEndLeftSelect  
- cursorWordLeftSelect  
- cursorWordRightSelect  
- cursorWordStartRightSelect

I overwrote the below commands so I could highlight words. I left out the `when` key so it would work in places other than the editor but it's inconsistent.

`{"key": "shift+alt+left", "command": "cursorWordLeftSelect" },`
`{"key": "shift+alt+right", "command": "cursorWordRightSelect" },`

Places it works:  
- editor

Places it doesn't:  
- find in file (used to work at some point, not sure why it stopped)  
- global find  
- git commit text box
- command box
- maybe more?

**Comment by alexandrudima** [comment]
The places where this doesn't work are implemented as native `<input>`s

**Comment by drew-wallace** [comment]
The default Mac select word is alt+shift+left and that doesn't work in those boxes.

**Comment by drew-wallace** [comment]
If I remove my override, it works. Strange...

**Comment by mitchellpalermo** [comment]
I'm having this same issue. Is anyone else seeing this behavior with VSCode? 

When i go to set a keyboard binding, I can type alt+shift, and it will show up in the dialogue box, but when I press the left arrow key, nothing shows up. I can however set alt+shift+{any other arrow key}.

![img_8224](https://user-images.githubusercontent.com/20684298/44621731-0ac12100-a871-11e8-87f9-011139cf36d2.JPG)
![img_8225](https://user-images.githubusercontent.com/20684298/44621732-0ac12100-a871-11e8-9ac0-155e369e843d.JPG)

Running MacOS 10.13.6
Running VSCode 1.26.1

Any suggestions?

**Comment by alexandrudima** [comment]
@mitchellpalermo This indicates that you have other software on your OS that is "eating up" these keybindings. Have you been successful in using these keybindings in other software on the same machine?

**Comment by jaqra** [comment]
@alexandrudima out of date issue
