### ISSUE TITLE
Sorted/prioritized completions

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#74348]
@mjbvz since https://github.com/microsoft/TypeScript/pull/31484 is already merged it will be enabled by default with 3.5 TS, or something should be done additionally from VS Code side?

Also, how it will work with locality bonus setting or it will be deprecated?

**Comment by mjbvz** [comment]
We designed it so no work is required on the vs code side

**Comment by svipas** [comment]
@mjbvz Amazing, so it will be enabled by default with TS 3.5? Also, what about locality bonus setting, it's still relevant?
