### ISSUE TITLE
Quick Open performance regression

### ISSUE THREAD

**Issue by raiskila** [microsoft/vscode#74349]
- VSCode Version: 1.34.20-insider, 1.35.0-insider
- OS Version: macOS 10.14.5 (18F132)

### Steps to Reproduce:

1. `git clone git@github.com:facebook/react.git`
2. `/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin/code --disable-extensions --user-data-dir /tmp/a-new-directory react`
3. Press <kbd>⌘</kbd>+<kbd>P</kbd> and type a word, say "create".
4. Observe how quickly the file list populates.

### Expected Behavior
The quick open file list populates fast. Recording from 1.34.0-insider:

![1.34.0-insider](https://user-images.githubusercontent.com/351598/58378443-93095980-7f9c-11e9-9054-27bf97904290.gif)

### Actual Behavior
The quick open file list only populates after a delay after you stop typing. Running "Clear Editor History" seems to make the next invocation of Quick Open work faster, but the slowness returns. Recording from 1.34.20-insider:

![1.34.20-insider](https://user-images.githubusercontent.com/351598/58378446-9866a400-7f9c-11e9-9e6c-7838537250fd.gif)

I think I was able to isolate this to a difference between 1.34.0-insider and 1.34.20-insider. However, I had some trouble getting VSCode to honor the `--user-data-dir` flag, and it seemed to be partially using the "~/Library/Application Support/Code - insiders" directory until I deleted it.

**Comment by bpasero** [comment]
Yeah this is on me and should be fixed with https://github.com/microsoft/vscode/commit/0c53423cc480d760027f725406e428411b754116

**Comment by raiskila** [comment]
The issue is gone after updating to 1.36.0-insider. Thanks!
