### ISSUE TITLE
Automatic Space in the end of line when saving a code

### ISSUE THREAD

**Issue by Tukizz** [microsoft/vscode#74346]
i write code PHP every single i save a code automatic blank space in the end of line, when i not change my code or undo the code and doing action ctrl+s it automatic blank space in end of line

**Comment by rebornix** [comment]
sorry for coming back to the issue late, do you mean you the whitespace was added automatically by mistake?

**Comment by Tukizz** [comment]
maybe yes, before the update my code don't have a whitespace in the end of line, when a new update, every i open, change a little bit my code or close a tab or save it, it's automatic create a whitespace in end of line in bottom of code, it waste of push to git without my knowledge if it's just changing whitespace in end of line in bottom my code

**Comment by salavat706** [comment]
just was replaced line endings

> maybe yes, before the update my code don't have a whitespace in the end of line, when a new update, every i open, change a little bit my code or close a tab or save it, it's automatic create a whitespace in end of line in bottom of code, it waste of push to git without my knowledge if it's just changing whitespace in end of line in bottom my code

was replaced line endings by CRLF or LF

**Comment by salavat706** [comment]
vs code formats line endings when opening a file
