### ISSUE TITLE
Linux bad terminal and NavigationBar rendering

### ISSUE THREAD

**Issue by yuyoDev** [microsoft/vscode#74358]
- VSCode Version: 1.34.0
- OS Version: Archlinux kernel 5.1.4-arch1-1-ARCH kde-plasma 5.15.5

Steps to Reproduce:

1. update

Does this issue occur when all extensions are disabled?: Yes

![Screenshot_20190526_101159](https://user-images.githubusercontent.com/17438270/58383818-acaca000-7fa0-11e9-9a46-0c45f080f6d2.png)
![Screenshot_20190526_101341](https://user-images.githubusercontent.com/17438270/58383819-ae766380-7fa0-11e9-9929-3de2135fdcbf.png)
![Screenshot_20190526_101414](https://user-images.githubusercontent.com/17438270/58383823-b2a28100-7fa0-11e9-9ce3-ecbdb247b480.png)
Sorry for the report so vague, I do not know if it's due to my drivers or another factor, only vscode and os were updated.

**Comment by primos63** [comment]
@yuyoDev I have the same issue with my Arch system. Go to File->Preferences->Settings and search for terminal (Features->Terminal). There is a setting Terminal>Integrated: Renderer Type. Set that to dom. If the characters in the terminal aren't looking correct, scroll up to Terminal>Integrated: Font Family and change it to monospace or some other monospaced font.  I suspect there is some issue with the canvas rendering.

**Comment by yuyoDev** [comment]
Thanks for the suggestion @primos63 , I made the change to a monospace as you say, but the error persists.

**Comment by primos63** [comment]
Did you also change the Renderer Type to dom?

**Comment by yuyoDev** [comment]
Thanks @primos63 , that worked, but something slower. But it allows me to continue working :)

**Comment by primos63** [comment]
@yuyoDev Great! Would you happen to be using an AMD graphics card? The same version of vscode runs fine on my other linux systems (swag arch and ubuntu) but they are using nvidia and intel gpu. I suspect the last Arch update is causing the issue. I just installed the Discord app and the graphics on the startup screen were showing artifacts like the integrated terminal showed.

**Comment by yuyoDev** [comment]
Yes, I use integrated graphics AMD Ryzen 5 2500u, I also have those problems with the Brave browser.
One of the last updates was with mesa, vulkan and opengl.

**Comment by galileo-pkm** [comment]
For a temporary fix start it with code --disable-gpu

**Comment by Tyriar** [comment]
This looks like a driver issue that we can't do much about, here are your options which were already pointed out:

- Update graphics drivers
- rendererType to dom (slower is expected)
- `code --disable-gpu` (using dom renderer would probably be better than this, it might do good to disable GPU anyway though if you're having issues)
