### ISSUE TITLE
Some of the css syntax is dropped

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#74351]
Some of the `CSS` syntax is dropped like that

![m](https://user-images.githubusercontent.com/42807112/58380949-56e3f200-7fb8-11e9-9b52-5e549d54cedd.jpeg)

![m1](https://user-images.githubusercontent.com/42807112/58380952-5ea39680-7fb8-11e9-8a91-e11e3a7c6164.jpeg)

Neither autocompletion nor linting works right.
Please look at these issues.

**Comment by octref** [comment]
`@custom-selector` is not in CSS spec. You might be interested in https://github.com/microsoft/vscode-css-languageservice/blob/master/docs/customData.md
