### ISSUE TITLE
Tab with Find

### ISSUE THREAD

**Issue by Ilias48rus** [microsoft/vscode#74359]
Issue Type: <b>Bug</b>

The Find field allow to insert Tabs, but do not recognize/find them.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (4.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/62173838-5fc0af00-b2ec-11e9-8cdd-729e367292f2.png)

I can't reproduce this issue. Please provide more info about how to reproduce this issue.
