### ISSUE TITLE
Option to don't automatically remove an item from "Files -> Open Recent" 

### ISSUE THREAD

**Issue by DominikPalo** [microsoft/vscode#74350]
I use VSCode for editing network files or files on external drives. But sometimes I forget to mount a network drive before opening a file located on that drive. So here is my usual scenario:

1. Navigate to "Files -> Open Recent"
2. Click to some network file (e.g. `/Volumes/homeassistant/configuration.yaml`)
3. Alert "Path does not exist" pop-ups, because the parent drive is not currently mounted (see the screenshot below) 
4. Click OK
5. Mount the drive
6. Navigate again to "Files -> Open Recent"
7. Observe, that the `/Volumes/homeassistant/configuration.yaml` item is missing (it was removed due to the failed attempt to open it)

So it would be useful to have an option in the VSCode Settings to disable that automatic removal of items which failed to open

<img width="421" alt="vscode" src="https://user-images.githubusercontent.com/1623257/58380234-03b97180-7faf-11e9-80af-aa20f74a5eb7.png">

**Comment by jadeGeist** [comment]
I'd like to give this a try!

**Comment by freekvh** [comment]
+1 for this, I have this problem when I forget to enable the VPN (or it is temporarily disconnected) and my network share is unavailable. This happens to me a couple of times a week... Another solution would be a favorites menu (bookmarks?) that is fully controlled and does not automatically change.
