### ISSUE TITLE
Terminal color theming is inconsistent for local and remote sessions

### ISSUE THREAD

**Issue by mattall** [microsoft/vscode#74368]
My local computer's terminal is on the left, and an ssh session to another machine is on the right.

![terminal_colors](https://user-images.githubusercontent.com/13005813/58387788-bac2e680-7fc9-11e9-995c-dfc740642b44.png)

Note: The colors in the SSH session are generated based on my Theme. If I change from high-contrast to solarized light... my ssh terminal changes, but my local session doesn't.

**Comment by Tyriar** [comment]
It's a different computer and has a different prompt set up, look into customizing your $PS1 env var.
