### ISSUE TITLE
cursorWordLeft and cursorWordLeftSelect do not behave consistently

### ISSUE THREAD

**Issue by brian-mann** [microsoft/vscode#74369]
Issue Type: <b>Bug</b>

Given the following keybindings...

```json
{
  "key": "alt+left",
  "command": "cursorWordLeft",
  "when": "inputFocus"
},
{
  "key": "shift+alt+left",
  "command": "cursorWordLeftSelect",
  "when": "inputFocus"
}
```

Moving from right to left using `cursorWordLeft` moves the cursor like so...

```
this.is.a.test|
this.is.a.|test
this.is.|a.test
this.|is.a.test
|this.is.a.test
```

This is great - this is exactly what I want.

However moving from right to left with select using `cursorWordLeftSelect` moves the cursor like so...

```
this.is.a.test|
this.is.a.|test
this.is.a|.test
this.is.|a.test
this.is|.a.test
this.|is.a.test
this|.is.a.test
|this.is.a.test
```

It takes `7` keystrokes using select vs the `4` you get with just regular cursor word left.

**Note: this bug applies ONLY to moving from right to left.** Moving the opposite direction with `select` works perfectly fine.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

**Comment by zhangkaiyulw** [comment]
Hi @brian-mann, this is interesting and I think they do this by design. How about having a toggle setting in the setting to toggle the behavior? It's by default behaves like normal and when it's on, it behaves exactly what you want: always move active point of the selection one char left or right regardless where the anchor point is.

**Comment by brian-mann** [comment]
I don't think this is by design - because moving from right to left works identically with both cursor movements and the movements with select.

In fact - I'm pretty sure this is behaving as the `cursorMoveEndLeft`, which is wrong because they are supposed to behave differently.
