### ISSUE TITLE
High CPU usage on mount.ntfs process (ASP.NET Core + Angular project)

### ISSUE THREAD

**Issue by mdx0111** [microsoft/vscode#74361]
Issue Type: <b>Bug</b>

Environment: Fedora 30 - 16GB Ram - Intel i7 7th gen
VSCode details:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.17-300.fc30.x86_64

I have a ntfs drive that's mounted throuth fstab:
UUID=the drive uuid /media/workspace ntfs rw,auto,users,exec,nls=utf8,umask=003,gid=46,uid=1000    0   0

I've an ASP.NET Core + Angular project stored on this ntfs drive and when I open it in VSCode, the CPU usage for mount.ntfs increased massively. This doesn't happen for smaller projects and wasn't an issue in previous versions of VSCode.

I wonder if you could look into this problem please.

Many thanks.  

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.17-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3199)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.55GB (9.94GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|9.8.1
vscode-html-css|ecm|0.2.0
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.0
docomment|k--|0.1.7
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.249
vsliveshare-audio|ms-|0.1.50
debugger-for-chrome|msj|4.11.3
vscode-icons|vsc|8.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by kieferrm** [comment]
Pls have a look at https://github.com/microsoft/vscode/wiki/Performance-Issues and provide additional details. Thanks!
