### ISSUE TITLE
Lost highlighting syntax with typescript

### ISSUE THREAD

**Issue by keyduq** [Microsoft/vscode#7436]
- VSCode Version: 1.2.0
- OS Version: Microsoft Windows 10

Steps to Reproduce:

1. Go to [https://www.typescriptlang.org/play/index.html](https://www.typescriptlang.org/play/index.html)

2. Copy the code of "Building a Raytracer" and paste in Visual Studio Code

3. See how after the line 261 VSCode lost the highlighting syntax with the operator `<=`

![2016-06-08](https://cloud.githubusercontent.com/assets/4933682/15910103/72f4585c-2d97-11e6-9f64-90a3d105650a.png)

**Comment by Andi-Lo** [comment]
I got the same problem for php syntax highlighting since the 1.2 update that I installed today.

![unbenannt](https://cloud.githubusercontent.com/assets/7545568/15933143/cfbf22d4-2e5e-11e6-95a5-be849a012c7d.PNG)

normally the <?php ?> would be color highlighted.

**Comment by aeschli** [comment]
@Andi-Lo HTML/PHP and TypeScript highlighting are not related. Please file a separate issue.

**Comment by Andi-Lo** [comment]
You're right, I will delete the post and open a new issue.

**Comment by aeschli** [comment]
The raytracer issue got fixed with the latest grammar update.
