### ISSUE TITLE
API request: will change selection

### ISSUE THREAD

**Issue by zhangkaiyulw** [microsoft/vscode#74379]
Hi,

I'm creating a plugin named 'Selection Mode'. The behavior is: 
1. User press a keystroke to active this mode and saves current anchor positions.
2. When it's active, every cursor moving command extends selections. 
3. When insertion or deletion (aka edition) happens, exits this mode.
4. When user press <kbd>escape</kbd>, exits this mode.
5. If user press the original keystroke during the mode, alter saved current anchor positions.

I'm currently using `onDidChangeTextEditorSelection`, there are some problems:
1. It flashes when modifies selection.
2. I need to manually checking if this selection change is triggered by me.

If there is a `onWillChangeTextEditorSelection` callback, I can modify selections before rerendering and editor state changing.

It's better to have this event on TextEditor class, not Workspace or Window. Because this behavior is really local to this editor instance. I only listen to this event when the mode is on. And it's nice to register this event with `vscode.commands.registerTextEditorCommand`.

For different event listeners that modifies the original selections, just pass the original selections in the event object, and user can get the current selections state with the textEditor instance. 

This event may have performance issue if plugin user doesn't use it correctly. But this event is only useful for text editing plugins that deeply modifies the cursor behavior.

**Comment by jrieken** [comment]
> This event may have performance issue if plugin user doesn't use it correctly. 

Yes and that's why we are unlikely to add such events. @rebornix This reminds me of VIM and you can maybe advise here

**Comment by rebornix** [comment]
I'm not a fan of this api, and you are correct, if the plugin uses the api improperly, it will lead to performance issue and even if the plugin does everything correct, it might still behave poorly visually, for example, the extension host is busy with some tasks executed by other extensions (synchronously) and takes 200ms to deal with them, users will see noticeable latency for just moving the cursor.

For short, Vim has known performance issues when working with some other extensions as a mild 100ms synchronous job in extension host will slow down Vim experience.

**Comment by zhangkaiyulw** [comment]
Hi @rebornix, thanks for replying and explaining in this detail. 
Do you think a plugin that implements `When mode is active, turn every cursor move commands into selection changing commands.` makes sense?
Is there any way or mechanism that VSCode provide that I can create a feature like this for my plugin?

Thanks
