### ISSUE TITLE
Unsupported font in open file/folder dialog

### ISSUE THREAD

**Issue by SpiritualDixit** [microsoft/vscode#74377]
Getting unknown font in open/save file/folder dialog.
Please take a look to the attached screenshot
![VS-code-issue](https://user-images.githubusercontent.com/12416924/58394723-48521500-8062-11e9-9d34-f86f5d49df26.png)

**Comment by alexr00** [comment]
What OS is this on? Do you have any additional repro steps?

**Comment by SpiritualDixit** [comment]
I am using Debian distribution: 
Here is the package information:-

1.2.1-1465908640 (main_binary-amd64_Packages)

Steps to reproduce:
- Installed Visual Studio Code using command line
  user@workstation $ sudo apt-get install visual-studio-code

- Trying to open existing folder from File > Open Folder

**Comment by alexr00** [comment]
Please see our [supported ways to install](https://code.visualstudio.com/docs/setup/linux)!
