### ISSUE TITLE
Intellisense does not show up after 

### ISSUE THREAD

**Issue by evanfurbeyre** [microsoft/vscode#74370]
- VSCode Version: 1.35.0-insider
- OS Version: macOs Mojave 10.14.3

Expected Behavior:
Intellisense to give code-completion options after a user snippet, as if you had manually typed code in.

Steps to Reproduce:
1. Paste following into User Snippets for Javascript
```javascript	
"Test": {
	"prefix": "test",
	"body": [
		"console.log($1);"
	]
},
```
2. In a blank .js file, declare a variable
```javascript
 const abcd = null;
```
3. Below variable declaration, type in 'test', and then tab-to-complete
4. Type in first letter of variable, observe that no Intellisense window opens up

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions in snippets
