### ISSUE TITLE
Integrated Terminal text and color problems

### ISSUE THREAD

**Issue by emeidell** [microsoft/vscode#74374]
- VSCode Version: 1.35.0-insider (1.35.0-insider)
- OS Version: MacOs Mojave 10.14.5 (18F132)

Steps to Reproduce:

1. Open Integrated Terminal

Does this issue occur when all extensions are disabled?: Yes

<img width="608" alt="image" src="https://user-images.githubusercontent.com/24320206/58388614-53636180-7fde-11e9-94f3-17f88d562652.png">

**Comment by emeidell** [comment]
The odd spacing and lack of color makes it a bit hard to read terminal prompts. I have tried uninstalling and reinstalling code to fix the problem. This is only happening on Insiders though. When I download regular code it works just fine.

**Comment by etisdew** [comment]
Can reproduce on all available means of install on Arch. Seem to be out an integrated terminal right now. :(

**Comment by etisdew** [comment]
ping for updates editted in above

**Comment by CoaPsyFactor** [comment]
I managed to fix it by changing terminal font (in vs settings) to "Monaco"

**Comment by emeidell** [comment]
Can confirm that changing font fixes the bug. I would have never thought to change the font to fix this.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/74183

Please comment more details on your build in that issue, specifically the commit and date of the build (can find in About)
