### ISSUE TITLE
Can't use system environment variables in tasks.json -> options -> env

### ISSUE THREAD

**Issue by xcjiang** [microsoft/vscode#74375]
- VSCode Version:
1.34.0
- OS Version:
windows 7

Steps to Reproduce:
my tasks.json like :

```
{
    "options": {
        "env": {
            "sdk-root": "${env:SDK_HOME}"
        }
    },
    "tasks": [
        {
            "type": "shell",
            "label": "run sdk",
            "command": "${env:sdk-root}\\make.exe",
            "args": [
            ]
        }
    ],
    "version": "2.0.0"
}
```

SDK_HOME is an environment variable that has already been added in the system. But when I run this task,  sdk-root is always empty.  
It works well if I replace ${env:sdk-root} with ${env:SDK_HOME} .

**Comment by alexr00** [comment]
The documentation describes this as the intended behavior https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks
