### ISSUE TITLE
Sidebar (preview) glitch on Linux

### ISSUE THREAD

**Issue by ranolfi** [microsoft/vscode#74378]
I just noticed a glitch on the scroll/preview sidebar under Arch Linux / Cinnamon. Instead of displaying a preview of the codefile, it displays random garbage from the gpu buffer.

![image](https://user-images.githubusercontent.com/8507649/58394761-4a44b580-801b-11e9-8eb1-b689243804b7.png)

(I recognized some of these sprites from Counter-Strike Source, which I had been playing hours ago)

I found that expanding and then hiding the Extensions view (or any other left-side view) will often temporarily fix this, albeit not consistently.

Also, after closing all files I managed to make it display a previously opened file:

![image](https://user-images.githubusercontent.com/8507649/58394990-6ac13f80-801c-11e9-93b6-206ba647016b.png)

Let me know if I can provide any other useful info.

- VSCode version: `1.34.0` (also tested with version `1.35.0-insider`)
- OS Version: `Linux x64 5.0.13-arch1-1-ARCH`; `Cinnamon 4.0.10`; `Mesa 19.0.5`
- AMD FX 6350; AMD RX 550 2GB

```

CPUs | AMD FX(tm)-6350 Six-Core Processor (6 x 3780)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: unavailable_offviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 2, 1, 1
Memory (System) | 7.75GB (0.64GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%

```

Steps to Reproduce:

1. Open any document, by any means, on VS Code
2. Notice the scroll sidebar.

Also occurs with all extensions disabled.

(Additional screenshots)

![image](https://user-images.githubusercontent.com/8507649/58394948-3cdbfb00-801c-11e9-8b0d-80138f62217c.png)

**Comment by leafi** [comment]
I'm experiencing this, too.

I'm also on Arch Linux, using GNOME 3, completely up-to-date (Arch is a rolling release distro).

My graphics card is a Radeon RX 580. I have multiple monitors attached.

This started happening, oh, about a week ago? I suspect a mesa bug, or possibly a bug in the Linux amdgpu driver. But I haven't seen visual corruption in any other applications.

```
[leaf@alicorn ~]$ yay -Qs mesa
local/glu 9.0.0-5
    Mesa OpenGL Utility library
local/lib32-glu 9.0.0-4
    Mesa OpenGL utility library (32 bits)
local/lib32-mesa 19.0.5-1
    An open-source implementation of the OpenGL specification (32-bit)
local/lib32-vulkan-radeon 19.0.5-1
    Radeon's Vulkan mesa driver (32-bit)
local/mesa 19.0.5-1
    An open-source implementation of the OpenGL specification
local/mesa-demos 8.4.0-1
    Mesa demos and tools incl. glxinfo + glxgears
local/vulkan-radeon 19.0.5-1
    Radeon's Vulkan mesa driver
[leaf@alicorn ~]$ yay -Qs radeon
local/lib32-vulkan-radeon 19.0.5-1
    Radeon's Vulkan mesa driver (32-bit)
local/radeontool 1.6.3-3
    Lowlevel tools to tweak register and dump state on radeon GPUs
local/vulkan-radeon 19.0.5-1
    Radeon's Vulkan mesa driver
[leaf@alicorn ~]$ yay -Qs vscode
local/visual-studio-code-bin 1.34.0-2
    Visual Studio Code (vscode): Editor for building and debugging modern web
    and cloud applications (official binary version)
# ^ this is from the AUR: https://aur.archlinux.org/packages/visual-studio-code-bin/
[leaf@alicorn ~]$ yay -Q linux
linux 5.1.4.arch1-1
```

For me, the minimap is always corrupt (or does not update correctly) when the VSCode window is bigger in width or bigger in height than my smallest screen, and never corrupt when the window is smaller.

I've attached a .flv video capture (open in VLC or whatever) (zipped because of GitHub) with the characteristic failures.

[2019-05-27 19-19-16.zip](https://github.com/microsoft/vscode/files/3224718/2019-05-27.19-19-16.zip)

@ranolfi Do you have multiple monitors, and are they of different sizes?

**Comment by ranolfi** [comment]
@leafi Thanks for confirming this is not just me. No, I have only one monitor at this moment.

May I ask, have you restarted your machine (full AC power off cycle) since you last updated your mesa package? I would do this myself but I can't for another day or so.

**Comment by leafi** [comment]
I did restart, yeah - since I updated mesa, and just before adding to this
bug issue to see if it would clear up. No effect.

OK, it's probably not a multi-monitor thing then...

Have you looked at your terminal tab? Mine's pretty glitchy in much the
same way as the minimap.

**Comment by ranolfi** [comment]
> Have you looked at your terminal tab? Mine's pretty glitchy in much the same way as the minimap.

Just did; it is indeed!

**Comment by ryanobeirne** [comment]
I also have this issue with the gitchy minimap:

- Arch Linux w/ KDE Plasma 5.15 (Everything is up to date)
- VSCode version 1.34.0
- Linux 5.1.5
- MacBook Pro 8,2 (2011)
- Inte Corel i7 (Sandy Bridge)
- ATI Radeon HD6770M

Additionally, I'm using the OneDark Pro color scheme and some `"workbench.colorCustomizations"`. Most of the backgrounds are usually a dark blue color, but now everything is a sort of pinkish purple color. I haven't changed those settings.

**Comment by JAicewizard** [comment]
also RX580, only happens on the visual-studio-code-bin package, not the open-source code(which is in the official arch repo) even though they are at the same version. I don't know exactly what terminal tab, but for me it doesn't happen in the integrated/external terminal or just urxvt which is my terminal.
