### ISSUE TITLE
Improve Syntax Coloring Scope

### ISSUE THREAD

**Issue by andremacola** [microsoft/vscode#74382]
![54168483-781f5280-444d-11e9-8868-390dcc20b940](https://user-images.githubusercontent.com/3408809/58397043-a7456900-8025-11e9-8804-85e17d2dbe6d.png)

Copy and paste the code below. The brackets are with the wrong color

```
<?php if ($test) { ?>
	<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae ipsam eius quos voluptate hic recusandae excepturi cum. Dolores vitae sunt optio assumenda soluta aliquam numquam voluptatum modi minima, labore illo.</p>
<?php } else { ?>
	<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae ipsam eius quos voluptate hic recusandae excepturi cum. Dolores vitae sunt optio assumenda soluta aliquam numquam voluptatum modi minima, labore illo.</p>
<?php } ?>
```

<img width="356" alt="54559784-1f0d6c80-49c1-11e9-8a34-b807e081b18e" src="https://user-images.githubusercontent.com/3408809/58397063-bc21fc80-8025-11e9-9560-4ee4182e2b53.png">

<img width="290" alt="54559671-d81f7700-49c0-11e9-8152-5d4f059ab28f" src="https://user-images.githubusercontent.com/3408809/58397070-c217dd80-8025-11e9-96c3-dbaede0fccea.png">

As you can see it provides us just a generic source.php `meta.embedded.line.phpthat` we can't target. This is sort of bug because the second curly bracket (the opening one) have a different scope.

**Comment by rzhao271** [comment]
Closing this issue because it seems to be fixed on the latest version of Insiders.
@andremacola feel free to reply if this issue still occurs for you after updating.

**Comment by andremacola** [comment]
@rzhao271 nope, the scope still wrong in 1.51.0-insiders. Some themes you can't notice the problem but if you show the TM Scope you see the problem.

**Comment by roblourens** [comment]
Filed upstream https://github.com/atom/language-php/issues/402
