### ISSUE TITLE
API request: on will change text document

### ISSUE THREAD

**Issue by zhangkaiyulw** [microsoft/vscode#74381]
Hi,

I want to save any thing user is deleting into the `deletion history` or `kill ring`. If I just alter `Cut` and any deletion commands, user may even has his own `delete-to-the-second-char-of-the-line`. It will cause inconsistency experience for user. When using `onDidChangeTextDocument` API, I cannot figure out what's being deleted. 

In the `onWillChangeTextDocument` API, I'm not going to read what's being deleted unless it's a pure deletion edition and it's length is >= 2 characters. So it will not have performance issues.

The API is not interruptible, for interruptible behavior, we may have an API named "shouldChangeTextDocument", if plugin writers don't use this API correctly, it confuses user and decreases VSCode user experience.

**Comment by jrieken** [comment]
You the `type` command, see the VIM extension(s) for samples

**Comment by zhangkaiyulw** [comment]
Hi @jrieken, I'm sorry that you misunderstood the problem. I don't mean to track user input. But I want to track any deletion to code. And deletions may come from commands from another plugin, or builtin commands. `type` is the command that normal key board keys triggers, am I right?

**Comment by jrieken** [comment]
Ok, the refer to the `delete` command. That should help. As inspiration, that's what I have used for vscode backspace: https://github.com/microsoft/vscode-backspace

**Comment by zhangkaiyulw** [comment]
Hi @jrieken,

I've looked at your example for creating command based on `deleteLeft`. I want to track changes for example user executes `deleteAllRight` or `editor.action.clipboardCutAction`, I don't want to track what `deleteLeft` or `deleteRight` does.
