### ISSUE TITLE
when a task started using visual studio code tasks , environment variables aren't working

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7438]
- VSCode Version:1.2.0
- OS Version: ubuntu 15.10

Steps to Reproduce:

1. create gulp tasks
2. user exec in a task and set env option to exec as process.env
3. run the task by issuing gulp command from terminal (it works)
4. run task from visual studio interface by using shortcut key (environment variables are not set !!!)

**Comment by dbaeumer** [comment]
Dups #6110
