### ISSUE TITLE
New '.sh' files default to CRLF

### ISSUE THREAD

**Issue by pasisavolainen** [microsoft/vscode#74385]
Issue Type: <b>Bug</b>

- New file
- Save as "something.sh"

-> line endings are CRLF; this doesn't work and produces very weird results

changing line ending to LF and resaving the file makes executing of script work.

VS Code version: Code - Insiders 1.35.0-insider (16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9, 2019-05-27T05:19:20.616Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (13.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
mssql|ms-|1.6.0
python|ms-|2019.4.12954
vscode-docker|Pet|0.6.2
trailing-spaces|sha|0.3.1

</details>

**Comment by alexr00** [comment]
On Windows, all new files are defaulted to CRLF since that is most often what you will want on Windows.
