### ISSUE TITLE
terminal rgb color render bug

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode#74386]
# terminal rgb color render bug

VS Code Version: 1.34.0 (user setup)
OS: Windows_NT x64 10.0.17134

## Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - H:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - H:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - H:\Program Files\nodejs\npm.CMD

## Steps to Reproduce:

1. install `chalk`
2. console.log rgb text

https://github.com/chalk/chalk/issues/346#issuecomment-496098068

## CMD is OK

![OK](https://user-images.githubusercontent.com/7291672/58403920-75b8b600-8096-11e9-9b90-3011add5e4da.png)

## VS code Terminal is Error

![Error](https://user-images.githubusercontent.com/7291672/58399927-4b61fb00-808c-11e9-9182-6d071fafba37.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
