### ISSUE TITLE
I have update visual studio code , later when doing work its hanging very badly

### ISSUE THREAD

**Issue by dotnetmaheshbabu** [microsoft/vscode#74383]
Issue Type: <b>Bug</b>

update with latest version , then start working 
u can see the hanging experience 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.86GB (11.30GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43

</details>
<!-- generated b

**Comment by alexr00** [comment]
Please collect a performance trace as described [here](https://github.com/microsoft/vscode/wiki/Performance-Issues).
