### ISSUE TITLE
FEATURE REQUEST: Copy permalink

### ISSUE THREAD

**Issue by allanchau** [microsoft/vscode#74380]
It would be good if we could copy the permalink for a line right from the editor.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/1763968/58396672-d9d67c80-808c-11e9-9af9-f18318114cf6.png">

I'd imagine the requirements would be the line has been pushed to a git repo, otherwise the context menu would be greyed out.

**Comment by joaomoreno** [comment]
I suggest to suggest this to GitLens.
