### ISSUE TITLE
live share uninstall bug

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode#74389]
# live share uninstall bug

> very stuck

![](https://img2018.cnblogs.com/blog/740516/201905/740516-20190527163324804-483472634.png)

**Comment by xgqfrms** [comment]
## Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - H:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - H:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - H:\Program Files\nodejs\npm.CMD

**Comment by sandy081** [comment]
@xgqfrms Looks like you have an extension `Live Share Audio` installed which is depending on this extension. Hence you cannot uninstall it. To uninstall it, you first uninstall the depending extension.
