### ISSUE TITLE
Allow to run the web client out of master (yarn web)

### ISSUE THREAD

**Issue by yunliang-ding** [microsoft/vscode#74393]
Sorry I can't find remoteExtensionAgent.sh in ./scripts/code-web.js
When I try to run vscode in 
http://127.0.0.1:8080/out/vs/code/browser/workbench/workbench.html

**Comment by bpasero** [comment]
Yeah this is not ready for prime time yet.

**Comment by bpasero** [comment]
I will rename this, unfortunately currently we do not support running the web client out of `master`.

**Comment by frank-dspeed** [comment]
is Related: https://github.com/microsoft/vscode/issues/81310

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/82569
