### ISSUE TITLE
Recent history: Improve storage of labels

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74399]
* open `storage.json`
* it seems that paths are stored as `workspaces3` and that path labels are stored as sibling property (`workspaceLabels`) and that alignment happens with `null` placeholder. I have many, many rows just print `null`

<img width="1511" alt="Screenshot 2019-05-27 at 12 33 13" src="https://user-images.githubusercontent.com/1794099/58414413-9de6eb80-807b-11e9-98e8-879f02952eff.png">

**Comment by jrieken** [comment]
File: [storage.json.txt](https://github.com/microsoft/vscode/files/3223385/storage.json.txt)

**Comment by bpasero** [comment]
Moving to @aeschli, I have lost track of the format of the recently opened files. I think we keep a lot of legacy around that we should probably drop and cut backwards compat.

**Comment by aeschli** [comment]
Yes, that's the current, intended format. When adding the labels (only used for remote) I didn't want to change the existing 'workspaces3' array as to avoid breaking old clients.
Agree that there's probably a smarter solution, but lots of nulls are also not that much of a waste.
No action planed for the moment

**Comment by aeschli** [comment]
no action planned for now.
