### ISSUE TITLE
Duplicates in recently opened list

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74397]
Not sure why but I see vscode.proposed.d.ts two times in the list (it does open the same file)

<img width="718" alt="Screenshot 2019-05-27 at 11 28 33" src="https://user-images.githubusercontent.com/1794099/58410521-a38c0380-8072-11e9-987b-3d9933ede175.png">

**Comment by bpasero** [comment]
@jrieken can you check the contents of `storage.json` in the app data root to see if the URI has differences?

**Comment by jrieken** [comment]
Not even in there

<img width="1445" alt="Screenshot 2019-05-27 at 12 31 05" src="https://user-images.githubusercontent.com/1794099/58414321-4d6f8e00-807b-11e9-97ae-633d8746f1c0.png">

**Comment by bpasero** [comment]
@jrieken sorry, wrong file. Can you check the contents of local storage (via "Developer: Log Storage...") and the key would be: `"history.entries"` from the workspace storage table.

**Comment by jrieken** [comment]
Yeah, seems like the UI treats them as equal... Tho, unsure where they come from

<img width="654" alt="Screenshot 2019-05-27 at 12 38 06" src="https://user-images.githubusercontent.com/1794099/58414667-5ad94800-807c-11e9-8530-31668a94a4e1.png">


<img width="1309" alt="Screenshot 2019-05-27 at 12 38 34" src="https://user-images.githubusercontent.com/1794099/58414671-5d3ba200-807c-11e9-9b8f-8a7763bf01b3.png">

**Comment by bpasero** [comment]
@jrieken the second URI has arguments appended to it (via `?path...`) so they are different at least when comparing by their serialized form. I need to check who is passing URIs with query arguments around, might be me from one of the changes this milestone.

**Comment by bpasero** [comment]
@jrieken did you maybe have dirty changes in the file, restarted (= hot exit)? I recently changed a few things there to encode some more metadata.

**Comment by jrieken** [comment]
Not sure, but it's likely that hot exit happened for that file

**Comment by bpasero** [comment]
@RMacfarlane @rebornix it looks like the pull request extension is potentially asking the workbench to open a URI with query parameters (see `isOutdated` in the screenshot from Joh). This is not good, as the document will appear duplicate even though it points to the same file. The extension should never tamper with a resource it does not own. Can you please take a look?

**Comment by rebornix** [comment]
@bpasero the current implementation tweaks `Uri.query` to support both file editing (`file://`) and comments loading (`query` carries pull request information). The new implementation will not do that any more, with the new implementation

* GH PR provides `pr://` and `review://`
* `file` are not touched.

**Comment by bpasero** [comment]
Great, when will this happen?

**Comment by RMacfarlane** [comment]
We have an issue tracking this in the PR extension: https://github.com/microsoft/vscode-pull-request-github/issues/1099

**Comment by rebornix** [comment]
@bpasero after we release 1.35 and then we can safely publish a new version of GH PR to adopt the api. As there is nothing actionable in VS Code side, close this one and track in GH PR.

**Comment by rebornix** [comment]
Added this to the May iteration plan for GH PR as well https://github.com/microsoft/vscode-pull-request-github/issues/1154 .
