### ISSUE TITLE
enable display  of spaces

### ISSUE THREAD

**Issue by prashanjitghosh** [microsoft/vscode#74391]
Issue Type: <b>Feature Request</b>

would be nice if we can have the feature for any source file to show the invisible space characters so that formatting can be easy.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexr00** [comment]
This exists already: View: Toggle Render Whitespace.

**Comment by prashanjitghosh** [comment]
Thanks a lot @Alex Ross .

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
