### ISSUE TITLE
unable to use \r (carriage return) with pcre2 enabled in search.

### ISSUE THREAD

**Issue by goyaltushar92** [microsoft/vscode#74395]
Issue Type: <b>Bug</b>

1. enable PCRE2 in search settings.
2. search `>[\r\s]` in sidebar will give `PCRE2: error compiling pattern at offset 18: unmatched closing parenthesis` error.

with in `[]` `\r` is always throwing this error.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (21.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.1.11
svn-scm|joh|1.48.6
vscode-typescript-tslint-plugin|ms-|1.1.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
debugger-for-edge|msj|1.0.9
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.6
change-case|wma|1.0.0
clang-format|xav|1.9.0

</details>

**Comment by roblourens** [comment]
This is a problem with `\s` not `\r`
