### ISSUE TITLE
Extensions list should ignore openMode and enablePreview settings

### ISSUE THREAD

**Issue by georgir** [microsoft/vscode#74394]
Currently if you set `"workbench.list.openMode": "doubleClick"` or `"workbench.editor.enablePreview": false` it also affects the extensions list, making it more inconvenient to browse extensions. I think it would be better if extensions were still previewed on a single click, with the preview "editor" reused.

**Comment by sandy081** [comment]
Its a design decision to respect these settings in all list-like views and editors.

**Comment by georgir** [comment]
For what it's worth, this was a feature request, not a bug report. There never was a claim of it not working "as designed", just that the current design is lacking.

The design decision to respect these settings in all list-like views and editors should perhaps be reconsidered for editors that aren't actually allowing editing but are just a html page and for list views where you aren't expected to want to work with multiple items at once. Or specifically for this case. I don't think going for some perceived consistency here warrants the decreased convenience.

**Comment by sandy081** [comment]
@georgir I can open it as a feature request but I am sorry to say that we do not have plans to consider this and will be tagged as out of scope. In order to consider we might wait until it is highly requested by other users.
