### ISSUE TITLE
Add -w / --wait Command line argument

### ISSUE THREAD

**Issue by Lichtjaeger** [Microsoft/vscode#744]
I wants to use vscode as my git-cli editor. So I need an option that the calling process get stoped until the file I want to edit is closed.

I modified the bin\code.js in this form:
```javascript
delete process.env['ATOM_SHELL_INTERNAL_RUN_AS_NODE'];
require('child_process')
    .spawn(require('path').resolve(__dirname, '..', 'Code.exe'), process.argv.slice(2), {
        detached: true,
        stdio: 'ignore'
    })
    .on('close', process.exit);
if (process.argv.indexOf('-w')===-1&&process.argv.indexOf('--wait')===-1) {process.exit(0);}
```

But it only works if there are no other arguments and vscode is not already open.

**Comment by bpasero** [comment]
This requires a lot more than just -w, especially when code is already running.

**Comment by Lichtjaeger** [comment]
Thanks for response. Atom is also based on Electron and with Atom [it's possible](https://help.github.com/articles/associating-text-editors-with-git). So I thought it should be posible to use vscode the same way.

I look forward to the implementation.

**Comment by felixfbecker** [comment]
Yes please. Along with syntax highlighting for git commit messages and hunks (`git add -p`).

**Comment by kitsonk** [comment]
Thanks for the 0.10.10 release and a better wrapped command line, but this feature is still missing which of course means it is not possible to use VSCode as an editor for command line git and I am afraid, no matter how much you try, you can't break me of my love of the command line!

**Comment by Tyriar** [comment]
Landed, this should be in the March release. Thanks for pinging @kitsonk, it was trivial to implement after the Feb command line improvements :smiley:

**Comment by bpasero** [comment]
@Tyriar we have to handle the case where VS Code is already running. In that case, running code from command line will terminate instantly and delegate the opening of another window to the already running process.

**Comment by Tyriar** [comment]
@bpasero can it be launched as a standalone process instead of a shared process if `--wait` is present? I'm assuming sharedProcess.ts is responsible for this?

**Comment by bpasero** [comment]
It cannot because there is an application shared folder for chrome where e.g. local storage and index dB goes. I am not sure how that folder reacts to 2 processes fighting over its resources. Maybe we can still signal to the launch script when the window closes, e.g. through a named pipe / socket.

**Comment by kitsonk** [comment]
We had an Electron client project which had a similar requirement (it was protocol handlers that were launching other instances of the app).  @devpaul was able to deal with it.  He is on vacation this week, but maybe he might see it and can provide some advice.

**Comment by joaomoreno** [comment]
@Tyriar @bpasero When using `-w`, I suggest that: [when Code detects that there is a running instance](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L203), it should [send its `pid` over along with the `cliArgs` and `env`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L219) and instead of [killing itself](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L221), it just stands idly waiting for a `SIGTERM` from the outside. The main process would open a new window with the file to be edited. Upon closing that window, it then sends the `SIGTERM` to the waiting process.

**Comment by joaomoreno** [comment]
@bpasero raises the issue of IndexDB locking and multiple Electron instances, which is super valid.

I then suggest to move the [whole IPC dance](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/main.ts#L196) over to the [cli code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-main/cli.ts), making all of that happen before it even gets to Electron. We'd even get some performance out of it.

What do you think?

**Comment by bpasero** [comment]
@joaomoreno well we cannot do that because not in every case are we using the cli code when starting VS Code?

**Comment by joaomoreno** [comment]
Yeah if you use the `.exe` directly it won't work. But we can rely on people not doing that and using the shortcuts we set out for them in the `bin` folder.

**Comment by bpasero** [comment]
@joaomoreno wait, what about double click on the icon in the task bar, or right-click > open with, etc?

**Comment by felixfbecker** [comment]
Please don't do anything that prevents me from associating file types with `Code.exe`
(I was so happy when you finally ditched Squirrel because it always versioned the binaries and that made it impossible to associate file types. Please don't break this again)

**Comment by joaomoreno** [comment]
Yes you're right, great points. We can't move the IPC dance over the to cli code. But we can still run it there when using the `-w` flag. Otherwise, just run it as today. That would work, right?

**Comment by bpasero** [comment]
Yes, that sounds like a good approach :).

**Comment by bpasero** [comment]
@Tyriar I am currently looking into a solution for the case of Code already running. It looks like it is OK to let the second process run as long as it does not open a renderer. I can do a PR later hopefully.

**Comment by Tyriar** [comment]
@bpasero OK, great. I'll assign to you then.

**Comment by bpasero** [comment]
Closing this, as general functionality is there. Test plan: https://github.com/Microsoft/vscode/issues/4006
