### ISSUE TITLE
File type for Jinja template file set as html

### ISSUE THREAD

**Issue by rbhanot4739** [microsoft/vscode#74402]
- VSCode Version: 1.34.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open any Jinja template file in VsCode.
2. Check the file type at the bottom right corner, which will be HTML

This does not seem correct as the correct file type should be Jinja. 

There is another issue which is when I manually change the file type to Jinja, and then try to comment a line, it uses incorrect comment string as `#` whereas the correct comment string should be `{# #}`.

**Comment by kieferrm** [comment]
Do you use any extensions related to Jinja/Python?

**Comment by rbhanot4739** [comment]
I am using Jinja ane vs-python

**Comment by kieferrm** [comment]
@rbhanot4739 thanks for the quick response. Please move the issue to the appropriate extension. Thanks!
