### ISSUE TITLE
Terminal instantly closes

### ISSUE THREAD

**Issue by congrady** [Microsoft/vscode#7440]
- VSCode Version: both 1.2.0 and latest insiders
- OS Version: Windows 10, latest updates

Steps to Reproduce:

1. Try to open terminal (both ctrl+` and view -> ...)

It just shows terminal for a brief moment (few miliseconds) and then it closes.
I'm (sometimes, not everytime I try to open it) getting error "write EPIPE".
(this might be cause by holding the key binding button).

I dont have anything else bound to ctrl + `.
Tried restarting, reinstalling, restarting PC.
Tried using both powershell and cmd. (as described in your post).

Thank you for looking at this isuue. (or possibly telling me what am I doing wrong).

**Comment by Tyriar** [comment]
It seems you're experiencing https://github.com/Microsoft/vscode/issues/6621, I have hit it before but it seemed to just go away one day. It also has not been reported much so I'm looking for some reliable repro steps or clues before investigating it again.
