### ISSUE TITLE
Bug when opening terminal

### ISSUE THREAD

**Issue by LucaFilitz** [microsoft/vscode#74408]
Issue Type: <b>Bug</b>

When I open the terminal the first line is written with like 8 tabs distance to the left. The second line is then back to normal

Steps to reproduce:

1. Open Code
2. Toggle Termianl
3. Write something

VS Code version: Code - Insiders 1.35.0-insider (16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9, 2019-05-27T05:19:20.616Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.69GB (18.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
