### ISSUE TITLE
Automatically updating references after renaming folder/file fails

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#74409]
Having Visual Studio Code rename all references in our TypeScript project causes all references to `node_modules` being altered wrong. But, apparently, only in unopened files:
<br/>

![VS Code reference renaming issue](https://user-images.githubusercontent.com/9283914/58424314-6f770980-8097-11e9-801b-f7fa061e979d.png)

Visual Studio Code seems to prepend `node_modules` references with some project relative path. Moreover, the new, project relative, path isn't even correct (see the red squiggles in the screenshot).

### OS/VSCode Version:
```
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by SetTrend** [comment]
I couldn't find docs on how to install the Insiders version next to the regular version.

Just to make sure: I'm going to try this on a live development system. A system which must not fail. How can I install Insiders aside to the regular release version?

**Comment by mjbvz** [comment]
Just install it the same as you installed regular VS Code. It will not conflict with your normal Code install

**Comment by SetTrend** [comment]
I just tested with Insiders. Same (faulty) result:

![image](https://user-images.githubusercontent.com/9283914/58975657-c7172280-87c5-11e9-9ee8-ec050872692c.png)

No extensions were installed.

**Comment by mjbvz** [comment]
@SetTrend Can you share your project, or at least your `tsconfig` and a description of the project layout

**Comment by SetTrend** [comment]
@mjbvz : At this time we're in a critical project phase at my customers'. I currently don't have time/resources to create a sample project.

Will it be possible to re-open this issue later?

Won't someone in the team be able to find the bug right from the description I gave?
