### ISSUE TITLE
error occurs when close terminal ,console or cmd

### ISSUE THREAD

**Issue by HikariXu** [microsoft/vscode#74403]
Issue Type: <b>Bug</b>
Every time I close the terminal, console or cmd window , it doesn't work.  And vscode shows a noticification :"The terminal process terminated with exit code: 3221225786". The terminal windows didn't close until close it for the second time. This never happened in the older versions. I have reinstall vscode and win10 system for times, and noting changed.
Another issue, I can't input anything in integratedinterminal. Whatever key I press in integratedTerminal, it closes by itself.
My os version is win10 1903.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (11.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.9.9
vscode-language-pack-zh-hans|MS-|1.34.2
cpptools|ms-|0.23.1

</details>

**Comment by HikariXu** [comment]
> Issue Type: Bug
> Every time I close the terminal, console or cmd window , it doesn't work. And vscode shows a noticification :"The terminal process terminated with exit code: 3221225786". The terminal windows didn't close until close it for the second time. This never happened in the older versions. I have reinstall vscode and win10 system for times, and noting changed.
> Another issue, I can't input anything in integratedinterminal. Whatever key I press in integratedTerminal, it closes by itself.
> My os version is win10 1903.
> 
> VS Code version: Code 1.34.0 ([a622c65](https://github.com/microsoft/vscode/commit/a622c65b2c713c890fcf4fbf07cf34049d5fe758), 2019-05-15T21:59:37.030Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info
> Extensions (4)

when I change "Terminal › Integrated › Shell: Windows" in the setting, it goes right.But still can't use terminal. I select "terminal"  below. An window is opened. but in the "setting" I selected Integrated-Terminal.

**Comment by Tyriar** [comment]
Can you share your settings.json file and a screenshot of what it looks like when you can't use it as in https://github.com/microsoft/vscode/issues/74403#issuecomment-496202009?

**Comment by HikariXu** [comment]
[settings.zip](https://github.com/microsoft/vscode/files/3239698/settings.zip)
![image](https://user-images.githubusercontent.com/45059926/58681389-b702db80-839e-11e9-9030-59b18b74a4e2.png)
Here it is. I've changed terminal into git-bash and chosen integrated-terminal in the Settings. And when I click termial below, the window of git-bash emerges( you can see it on the screenshoot attached)
Now I change the terminal back to cmd. When opening vscode, cmd ermerges by itself. And I close cmd next. But doesn't work. You could see this situation on the screenshoot below:
![image](https://user-images.githubusercontent.com/45059926/58681756-5ffe0600-83a0-11e9-8641-5d6a385e40b1.png)
I close for the second time. It finally works. Then something unusaul happens.The output area disappears. See this on the picture below:
![image](https://user-images.githubusercontent.com/45059926/58681843-da2e8a80-83a0-11e9-9838-cab20b983097.png)
Then it runs the same way like the Git-bash. It never runs in the integrated-terminal whenever I chose Integrated terminal or external terminal. I remember when window of terminal didn't emerge, I press one key in integrated terminal, the terminal close byself. Just like the second picture I upload.
Sorry for my poor English.

**Comment by HikariXu** [comment]
I uninstall vscode and delete all the files related. Then I install it again. Change nothing. Only add the laun.json and task.json and C/C+ extension. Then I run helloworld.cpp. problem stiil exist.
The second time I install vscode, I still change noting. Only add C/C++ extension and code runner extension. I didn't add launch.json and task.json. Just use code runner to run cpp file, but I click terminal, the window of terminal appears. Code can run without input feature. I change the setting of code runner "run in terminal", which means I could input. But now, still no input, and can't run. I changed nothing else. .json file is attched.
[launch&tasks_json_file.zip](https://github.com/microsoft/vscode/files/3239949/launch.tasks_json_file.zip)

When I use vscode in Ubuntu, everything works perfectly. I just can't figure out why, last month, everything on windows platform worked fine as well. Hope this can have a help. THank you for your work!

**Comment by HikariXu** [comment]
@
