### ISSUE TITLE
Bottom left branch name should show current tree view directory branch

### ISSUE THREAD

**Issue by baelter** [microsoft/vscode#74406]
Selecting a dir in tree view does not update statusbar branch.

**Comment by joaomoreno** [comment]
What do you mean? Are you in a multi-folder workspace?

**Comment by baelter** [comment]
Yes, I think it would make sense that the branch of the selected file/folder in the tree view should be shown in the status bar.

**Comment by joaomoreno** [comment]
Currently the status bar tracks the active editor. I'm not sure there is enough infrastructure to track the active selected file in the explorer, from an extension. cc @isidorn for expertise

**Comment by isidorn** [comment]
There is no infrastructure to track the active selected file in the explorer from an extension.
Also all the items in the status bar are related to the active edtior. So the git status bar should not be an exception and should be scoped to the active editor imho.

**Comment by joaomoreno** [comment]
> Also all the items in the status bar are related to the active edtior. So the git status bar should not be an exception and should be scoped to the active editor imho.

Closing as per above.
