### ISSUE TITLE
May 2019 Endgame

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#74412]
This is the endgame schedule for [May 2019 Iteration](https://github.com/Microsoft/vscode/issues/74143).

## Schedule

- End game master: @rebornix / Redmond
- End game buddy: @aeschli / Zurich
- 05/28 Code freeze for the endgame
- 05/31 [Endgame done](https://github.com/Microsoft/vscode/wiki/Development-Process#inside-an-iteration)
- 06/06 Expected release date (this may change)

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Tuesday 05/28
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) **@aeschli**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at **5pm CET**
- [x] Ensure we have a green build on all platforms at 5pm CET
- [x] All test items contain test meta data by **5pm CET** and sufficiently comprehensive test descriptions by 8am CET
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] Test build starts at 6pm CET
- [x] Test plan ready by 6pm CET
- [x] Testing
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] [Verification needed for Remote](https://github.com/Microsoft/vscode-remote-release/issues?utf8=✓&q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed+)

##### Wednesday
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22May+2019%22+)
- [x] [Verification for Remote](https://github.com/Microsoft/vscode-remote-release/issues?utf8=✓&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22May+2019%22+)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22May+2019%22+)
- [ ] All issues [verified](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aerror-telemetry+-label%3Aduplicate+-label%3A*duplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22May+2019%22+)

- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) and pass list of changed OSS usage (https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/license/third_party_1.nn.0_diff.txt) to @isidorn for verification **@rebornix**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [x] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows 
  - [x] OS X 
  - [x] Linux 
- [ ] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). ⚠️We are now doing release notes via **Git LFS**. Please read what this means here: https://github.com/Microsoft/vscode-docs/blob/vnext/README.md#git-lfs-setup⚠️
  - [x] @aeschli
  - [ ] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @deepak1556
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [ ] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [ ] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **@aeschli**
  - [x] vscode-node-debug **@weinand**
  - [ ] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@chrisdias**
  - [ ] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [ ] vscode-recipes **@auchenberg**
  - [x] localization **@shawndon**
  - [x] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [x] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **@aeschli**
- [x] Acknowledge issue trackers from the community **@chrmarti**
- [x] Add notable fixes to the release notes **all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@aeschli**

##### Friday/Monday
- [x] Branch code to `release/<x.y> **@rebornix**
- [x] Bump up the version in package.json - **@rebornix**
- [x] Announce master is open for business **@rebornix**
- [x] Polish release notes **redmond**

##### Monday - Wednesday
- [x] Polish release notes **redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@rebornix**
- [x] Build `Insider` from `release/<x.y>` **@rebornix**
- [x] Manually release `Insider` **@rebornix**
- [x] Build stable for all platforms as new candidate issues come in **@rebornix**
- [ ] Documentation updated
  - [x] @aeschli
  - [ ] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [x] @deepak1556
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @mjbvz
  - [ ] @octref
  - [x] @rebornix
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [ ] @sandy081
  - [x] @sbatten
  - [x] @tyriar
  - [ ] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **@rebornix**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@RMacfarlane**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit
    - [x] signed installer 64-bit @sbatten
    - [x] signed user installer 32-bit
    - [x] signed user installer 64-bit @sbatten
    - [x] zip 32-bit 
    - [x] zip 64-bit @sbatten
  - [x] OS X
  - [x] Linux
    - [x] deb package 32-bit
    - [x] deb package 64-bit
    - [x] rpm package 64-bit @RMacfarlane
    - [x] rpm package 32-bit @RMacfarlane 
    - [x] archive 32-bit @RMacfarlane 
	- [x] archive 64-bit
- [x] Publish website **@gregvanl**
- [x] Publish Localization language pack **@shawndon**
- [x] Publish to stable **@rebornix**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  **@rebornix**
- [x] Publish `@types/vscode@<x.y>` @rebornix 
- [x] Publish rpm to repository manually **@RMacfarlane**
- [x] Enable scheduled `insider` builds **@rebornix**
- [x] Twitter announcement **@auchenberg**

**Comment by gjsjohnmurray** [comment]
Can this be pinned, i.e. so it appears at the top of Issues? maybe the Iteration Plan (#74143) too? That has been done on previous iterations.

**Comment by tristan957** [comment]
Do the iteration plans typically lag VSCode releases? 1.35 is available on the website, but hasn't been updated in the DNF repo (Fedora).

**Comment by lig** [comment]
@tristan957 I guess, this line in the plan is somewhat relevant
```
Publish rpm to repository manually @RMacfarlane 
```

**Comment by Tyriar** [comment]
@tristan957 @lig we're still waiting on the signing to be completed, it will probably be published today.

**Comment by tristan957** [comment]
Did the update get published? I see from the checklist that the signing got completed?

**Comment by Tyriar** [comment]
We're still waiting on the signing unfortunately, hopefully Monday.

**Comment by RMacfarlane** [comment]
@tristan957 The rpm is now published.

**Comment by rebornix** [comment]
May release is out and closed in favor of https://github.com/microsoft/vscode/issues/75285 .
