### ISSUE TITLE
Doesn't open second file in the same folder/project

### ISSUE THREAD

**Issue by IlyaTurshatov** [microsoft/vscode#74414]
- VSCode Version: 1.34.0 (1.35.0-insider too)
- OS Version: only OSX (works on Windows)

Steps to Reproduce:

1. Create a folder (`/Test`) with 2 files in it (`test1.cs` and `test2.cs`)
2. Open `test1.cs`" using terminal : 
    >> open "/Applications/Visual Studio Code.app" --args "/Test" -g "/Test/test1.cs":1:0
3. Open `test2.cs` using terminal : 
    >> open "/Applications/Visual Studio Code.app" --args "/Test" -g "/Test/test2.cs":1:0

Expected result: step 3 opens `test2.cs` in existing vscode instance from step 2
Actual result:  step 3 opens existing vscode instance with `test1.cs` shown 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@IlyaTurshatov can you reproduce when you try this:
* `code-insiders /Users/bpasero/Desktop/Test/ -g /Users/bpasero/Desktop/Test/test1.cs:1:0 `
* `code-insiders /Users/bpasero/Desktop/Test/ -g /Users/bpasero/Desktop/Test/test2.cs:1:0`

?

**Comment by IlyaTurshatov** [comment]
This approach works.
Is it possible make "open" command behaving the same way?

**Comment by bpasero** [comment]
I am not sure, but we only officially support our own CLI script when using our CLI arguments.
