### ISSUE TITLE
Cmd rendering issue

### ISSUE THREAD

**Issue by Cophla** [microsoft/vscode#74416]
Issue Type: <b>Bug</b>

Open terminal: select default shell
change default shell to cmd or powershell
press the terminal + button to add cmd terminal 
a black box is shown until i press enter to render and display cmd data

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
project-manager|ale|10.5.1
react-pure-to-class-vscode|ang|1.1.8
lit-html|bie|1.11.0
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
supersharp|cra|0.1.4
angular-schematics|cyr|1.23.0
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|7.2.0
netcore-extension-pack|dog|0.8.0
netcore-snippets|dog|0.2.4
git-extension-pack|don|0.1.3
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
pack-javascript|end|1.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.0
css2react|got|0.0.6
angular2-switcher|inf|0.2.0
search-node-modules|jas|1.3.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-styled-components|jpo|0.0.26
docomment|k--|0.1.7
csharpfixformat|Leo|0.0.81
angular-extension-pack|loi|0.7.1
vscode-styled-components-snippets|lXS|1.0.2
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.5.5
yarn-lock-syntax|mar|0.1.3
Angular-BeastCode|Mik|8.0.7
csharp|ms-|1.19.1
notepadplusplus-keybindings|ms-|1.0.3
typescript-javascript-grammar|ms-|0.0.50
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
ng-fortytwo-vscode-extension|NG-|0.0.9
convert-css-in-js|pau|1.1.3
java|red|0.45.0
vscode-sort-json|ric|1.13.0
aspnet-helper|sch|0.6.4
msbuild-project-tools|tin|0.2.55
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
vscode-icons|vsc|8.7.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by Tyriar** [comment]
Can you show a screenshot?

**Comment by Cophla** [comment]
![vscode_bug](https://user-images.githubusercontent.com/16767283/58450576-2915bf00-8118-11e9-9274-1423b5f74721.png)

**Comment by Cophla** [comment]
Same for powershell:
![vscode_bug2](https://user-images.githubusercontent.com/16767283/58450665-8ad62900-8118-11e9-8f4c-2865e6b49b4a.png)

**Comment by Cophla** [comment]
But for Git Bash its working normally without any issue

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
