### ISSUE TITLE
Outline remember previous file scroll position

### ISSUE THREAD

**Issue by hwhung0111** [microsoft/vscode#74410]
- VSCode Version: 1.35.0-insider (16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open two files in the same group
2. scroll the outline in file1 to the bottom, then click file2.
- if the outline list in file1 is more than file2, the outline in file2 will scroll to the bottom.
- if the outline list in file1 is less than file2, the outline in file2 will scroll to the same file1 outline position.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
Sorry, I don't understand. Can you attach a gif? Also do you have 'Follow Cursor' enabled?
<img width="492" alt="Screenshot 2019-05-28 at 09 59 59" src="https://user-images.githubusercontent.com/1794099/58461195-5cb01380-812f-11e9-92bb-e5ff360d4965.png">

**Comment by hwhung0111** [comment]
@jrieken The outline view will remember the previous file scroll position. 
![VS](https://user-images.githubusercontent.com/17689651/58480343-c3afe580-818c-11e9-99c6-82339e652115.gif)

**Comment by jrieken** [comment]
> @jrieken The outline view will remember the previous file scroll position.

Yes, that a feature and by design. What's wrong with that?

**Comment by hwhung0111** [comment]
@jrieken I think every file remember their own scroll position is more reasonable.

**Comment by jrieken** [comment]
Do you have 'Follow Cursor' enabled?

**Comment by hwhung0111** [comment]
No, I didn't enable 'follow cursor'.

**Comment by jrieken** [comment]
That's weird - I can only reproduce this when following the cursor (which is then also the correct behaviour).

**Comment by hwhung0111** [comment]
My setting: 

- disable 'follow cursor'
- double click two files to let it stay on the editor (fileA has 50 items in Outline and fileB has 100 items)
- scroll fileA's outline to 10th item and click fileB, it will scroll 10th item in fileB.
- scroll fileB's outline to the last item and click fileA, it will scroll to 50th item in fileA. (because fileA doesn't have 100 items.)
- scroll fileA's outline to 1st item and click fileB, it will also scroll to the first item in fileB instead of remembering last scroll position in fileB.

**Comment by jrieken** [comment]
Ah, same editor... Now I understand

**Comment by jrieken** [comment]
@joaomoreno `IDataTreeViewState` doesn't store the scroll position but I think it would makes sense to do so.

**Comment by joaomoreno** [comment]
You got it. We have it in the async data tree: https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/tree/asyncDataTree.ts#L268 It's just a matter of porting it.

**Comment by jrieken** [comment]
@joaomoreno Please double check the change I have pushed 🤞

**Comment by joaomoreno** [comment]
Awesome @jrieken, thanks!
