### ISSUE TITLE
When in CSS document  letter l is always on CAPS (L) 

### ISSUE THREAD

**Issue by Pontiaco** [microsoft/vscode#74424]
When in CSS document,  letter "l" is always on CAPS (L).  When pasted in a clipboard or other external document the letter l is back to normal (not in CAPS).  The other way around is also true.  When copy from the clipboard in normal letter "l", when in CSS then becomes "L"

I have restarted my computer by the way......several times.....

**Comment by jrieken** [comment]
Can you attached a screen shot and sample code?

**Comment by Pontiaco** [comment]
Hi Johannes;

I am sending you the website files and the videos (one showing the bug and
the other showing the extensions).
Hope you can tell me what to do next.

Regards

 main.css - website1 - Visual Studio Code 2019-0...
<https://drive.google.com/file/d/1T03YOz-9YiQLcztjEJMPi5Vu0Ul5Z6Os/view?usp=drive_web>
 ● main.css - website1 - Visual Studio Code 2019...
<https://drive.google.com/file/d/1zrxmn4PWPyKtrfnjGujAV9m269tDir1J/view?usp=drive_web>

**Comment by jrieken** [comment]
The font you are using isn't the default font but seems to the root of your problem. Not sure how that happened, but open the settings editor (F1 > Settings), search for "font", and change it back to another font

**Comment by Pontiaco** [comment]
You were right!  Changing fonts had the desired effect.  Thanks a lot for
your help.
By the way I am now using: Monaco, Menlo, "Droid Sans Mono" (in that order)
The trio before was: Consolas,'Courier New',monospace'
