### ISSUE TITLE
Notepad++ "Define your Language"

### ISSUE THREAD

**Issue by ramiroagm** [microsoft/vscode#74429]
There is a feature in Notepad++ that allow me to customize the display information, colors and fonts for certain types of files.

IE. I have  some .out files that show some logs that I've created in other applications. Those have certain structure, and I'd like to customize certain parts of the file so I easily can read a log while I program on other window.

**Comment by ramiroagm** [comment]
@kieferrm That is an approach of what I want.
I can't find configuration for changing elements by specific words.
Is there any or I just can't find them?

**Comment by kieferrm** [comment]
Can you point me to a description of the Notepad++ feature? Thanks.

**Comment by ramiroagm** [comment]
Language --> Define your language...

**Comment by ramiroagm** [comment]
😢
