### ISSUE TITLE
Out of memory when keeping file open while it's being updated

### ISSUE THREAD

**Issue by LunaLovegoood** [microsoft/vscode#74427]
I have a script which updates file every second. It runs for a quite long time.
Recently I've launched script, opened file in VSCode and left for about two hours. When i came back, VSCode terminated due to the out of memory issue.
Then I've done same thing again but after about 20 minutes I've launched 'Open process exporer' command and it clearly stated that window with that file consumed a lot of memory.
I think that cause for this problem may be that VSCode keeps snapshots of file in memory for undo functionality.

- VSCode Version: 1.34.0
- OS Version: Windows 10

Steps to Reproduce:

1. Launch script to keep contstantly updating same file for a long time.
2. Open that file in VSCode and leave it open for a while.

**Comment by LunaLovegoood** [comment]
Any information about it so far?

**Comment by rebornix** [comment]
you are right, we track edit history and more than that, our internal data structure for text buffer also grows when there are new edits happening but for every edit, it grows tens/hundreds of bytes. Could you please open Developer Tools and go to Memory tab to create a heap snapshot to help us locate exactly the root cause?

**Comment by LunaLovegoood** [comment]
I'm currently unable to do it, I'll create a snapshot in about 2 weeks.

**Comment by LunaLovegoood** [comment]
Here's memory snapshot after about 30 minutes of app running.

Code used:
```
const fileAppender = new fileSystem.FileAppender();

const fd = await fileSystem.openFile('test.txt', 'w+') // alias for fs.open
fileAppender.setFile(fd);

const writeLoop = async () => {
    fileAppender.reset(); // resets position in file
    await fileSystem.clearFile(fd); // alias for fs.ftruncate

    for (let i = 0; i < 50; ++i) {
        await fileAppender.append(`${Date.now()}\n`); // uses fs.write
    }

    setTimeout(writeLoop, 1000);
};

writeLoop();
```
[Heap-20190731T105442.zip](https://github.com/microsoft/vscode/files/3450443/Heap-20190731T105442.zip)
