### ISSUE TITLE
In the case of Chinese input, a few times after pressing "shift"+"-, there will be a stuck phenomenon.

### ISSUE THREAD

**Issue by kingkongshan** [microsoft/vscode#74432]
Issue Type: <b>Bug</b>

In the case of Chinese input, a few times after pressing "shit"+"-, there will be a stuck phenomenon.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
debugger-for-chrome|msj|4.11.3
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@kingkongshan can you provide more info of what happened? A recording/gif can help with better troubleshooting.
