### ISSUE TITLE
split settings.json file

### ISSUE THREAD

**Issue by shenhai-ran** [microsoft/vscode#74434]
I thought this must be requested, but I really didn't find any open issues.

After I start to use and customize VSCode for a while, especially with some extensions installed, my _settings.json_ becomes very long and also difficult to maintain. Would it be good if I can split the _settings.json_ files into smaller ones, probably for different extensions.

I can image two approaches, either:
add include/load _/path/to/my/extensions.settings.json_ method inside global _settings.json_;
or/and:
the global _settings.json_ file can automatic append any _*.settings.json_ files in the same folder.
For instance, if I have a _latex.settings.json_ with settings I want, _settings.json_ will include it without any explicit statement. It would be much easier to maintain and modify settings for extensions.
 
Hope it is not duplicate request, otherwise kindly close it.

Cheers,

**Comment by sandy081** [comment]
@shenhai-ran There is a settings UI editor to solve such issues. Let us know if it is not helpful in this case?

**Comment by shenhai-ran** [comment]
@sandy081 Thanks for you feedback. Indeed the ui editor is quite good, but some extensions, such as **LaTeX Workshop**, it still needs to edit settings.json . 

For instance in the following configuration of LaTeX Workshop in the UI editor, if I want to add any build command, I still need to open the settings.json file and expand it to very very long.
![Code_n0OfehcCUU](https://user-images.githubusercontent.com/8853417/58555964-23ed6880-821b-11e9-8447-b3696280129b.png)

That's why I thought if I can put all my latex settings into a latex.settings.json file and can be read in automatically.

**Comment by sandy081** [comment]
Is not this only for some settings which do not have UI support? I dont think it is worth to introduce a new feature for this. Instead we can improve the existing settings UI say

- Add support in the UI for such settings
- Edit in settings.json link focuses directly at the location where setting is defined, if not, add the entry with default value.

@roblourens FYI
