### ISSUE TITLE
Test @types/vscode and vscode-test

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#74436]
Test for #71048

- [x] Mac @Tyriar
- [x] Linux @aeschli 
- [x] Windows @bpasero 

Complexity: 2

Overview: `vscode` has been split into `@types/vscode` and `vscode-test`. See the reasoning here: https://github.com/microsoft/vscode-extension-vscode/issues/147

[Release notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#splitting-vscode-package-into-typesvscode-and-vscode-test) | [Docs](https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md)

Please test:
- run `npm install -g generator-code@next`
This should install `generator-code@1.2.0-next.0`
- `yo code` with TS/JS generates an extension with `@types/vscode` and with integration tests setup using `vscode-test`
- You can run the integration test (`yarn test` or running it from debug target) in https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
- You can modify the test script and test runner following the [documentation](https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md)
- You can easily understand the purpose and usage of https://github.com/microsoft/vscode-dts (
- `vsce` prevents you from publishing an extension when you have `@types/vscode` > `engines.vscode` in package.json.

**Comment by bpasero** [comment]
I skiped over the "VSCE" part.

**Comment by aeschli** [comment]
(Documentation link](https://github.com/microsoft/vscode-docs/blob/octref/vscode-test/api/working-with-extensions/testing-extension.md) does not work for me

**Comment by octref** [comment]
Fixed link

**Comment by octref** [comment]
I thought it's mostly going to be small changes, but the API parts need some discussion which I don't have bandwidth for. I pulled it out from release notes and will continue in June. Thanks for testing!

**Comment by aeschli** [comment]
Created https://github.com/microsoft/vscode-generator-code/tree/vscode-test-and-types-at-code with all the commits.
Set master back to the previous version to avoid that the changes get pushed inadvertently
