### ISSUE TITLE
Terminal render issue

### ISSUE THREAD

**Issue by tuananh** [microsoft/vscode#74437]
- VSCode Version: Version 1.35.0-insider (1.35.0-insider) 16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Toggle integrated terminal on

Screenshot

![image](https://user-images.githubusercontent.com/627278/58448541-9b939880-8132-11e9-875f-59313cc93432.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tuananh** [comment]
Fixed by changing renderer type from `dom` to `auto`

**Comment by yairEO** [comment]
OMG I have wasted so many hours yesterday and today trying to figure out this!

So annoying, the integrated Terminal ignores all font settings, unless a change is made in any of VSCODE Terminal font settings, but this only fixes already-open terminals and new ones will again render with incorrect fonts.

MacOS `10.14.4`
VSCODE `1.35.0 insiders`

![settings json — backoffice-v2 2019-05-28 11-13-54](https://user-images.githubusercontent.com/845031/58462276-35127880-813a-11e9-9aa0-7160173da498.png)

**Comment by tuananh** [comment]
> OMG I have wasted so many hours yesterday and today trying to figure this out!
> 
> So annoying, the integrated Terminal ignores all font settings, unless a change is made in any of VSCODE Terminal font settings, but this only fixes already-open terminals and new ones will again render with incorrect fonts.
> 
> MacOS `10.14.4`
> VSCODE `1.35.0 insiders`
> 
> ![settings json — backoffice-v2 2019-05-28 11-13-54](https://user-images.githubusercontent.com/845031/58462276-35127880-813a-11e9-9aa0-7160173da498.png)

that's what happened with me as well

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/74183

@yairEO thanks for the effort, that's very useful to help diagnose 👍
