### ISSUE TITLE
Terminal not displaying properly after latest update.

### ISSUE THREAD

**Issue by cjlaborde** [microsoft/vscode#74431]
- VSCode Version: May 2019 (version 1.35)
- OS Version: Ubuntu Linux 18.04

Steps to Reproduce:

1. Open terminal in visual studio code

Does this issue occur when all extensions are disabled?: Yes/No
Yes, even with extensions disabled same issue.
As well preview when I type letter not displaying properly.
Left is latest version. Right older version
https://i.imgur.com/1ZnwxCJ.png

**Comment by cjlaborde** [comment]
Fixed it by changing  terminal render setting from dom to auto setting https://i.imgur.com/ttsl8PO.png
It changed the setting on it's on after reset.

**Comment by julianlam** [comment]
@cjlaborde Thanks! Was wondering why my terminal went back to the dark ages all of a sudden. I think the option to switch to the DOM renderer was presented during high CPU (or OOM scenarios).
