### ISSUE TITLE
Random texture appearing in some parts of the vs code window

### ISSUE THREAD

**Issue by allen505** [microsoft/vscode#74433]
Whenever I am using VS Code(VSC) and then I put the laptop to sleep, and after a while I open and unlock my laptop, some random texture appears over the window in some parts as shown in the picture. The texture appearing is also not part of any background app or the wallpaper.
Interestingly, some texture goes away way I bring my mouse over it and some go away when I click it. Clicking it becomes a problem coz idk what I am clicking over and sometimes leads to closing something I am working on.
Also the internal terminal seems all cleared out.
This does not happen in other windows/programs so must not be an OS related or DE bug. 
![vs_code](https://user-images.githubusercontent.com/36478181/58444648-ccfe6b00-8116-11e9-91b4-a53409928154.png)

- VSCode Version:1.34.0
- OS Version:Linux x64 4.15.0-50-generic
                     Linux Mint 19.1 Cinnamon

Steps to Reproduce:

1.Open VS Code
2.Turn the laptop to sleep
3.Reopen the laptop and unlock to open vs code

Does this issue occur when all extensions are disabled?: Yes

**Comment by OnlyLys** [comment]
Are you on Linux? This appears to be a problem with Mesa. 

More info here: https://www.reddit.com/r/archlinux/comments/btnbpr/awful_artifacts_lately_in_all_chromium_based/

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by orpiske** [comment]
I believe I have the same issue. In my case, the problem happens only on the terminal. I have the same VS code version on my laptop and it does not have the issue. 

@bpasero if you have an RPM version of the exploration builds, I can give it a try as well.

**Comment by bpasero** [comment]
@orpiske https://az764295.vo.msecnd.net/exploration/fb34c44351af7e0abdf493d6fd70072b35f93edf/code-exploration-1.35.0-1559036183.el7.x86_64.rpm

**Comment by orpiske** [comment]
@bpasero Thanks. I verified that the problem persists with the exploration build. I attached the screenshot for reference.

![terminal-problem](https://user-images.githubusercontent.com/1851560/58494937-7b85c880-8176-11e9-97eb-be81a5e94309.png)

**Comment by allen505** [comment]
> Do you also get this problem with other Chromium based apps? This appears to be a problem with Mesa.
> 
> More info here: https://www.reddit.com/r/archlinux/comments/btnbpr/awful_artifacts_lately_in_all_chromium_based/

I don't really know what electron here means. I have spotify but that does not have this problem. About messa, I am using Linux Mint which is based off of Ubuntru and Debian but the post is from Arch Linux. so I'm guessing it's not it. Not sure what Messa means either.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

**Comment by orpiske** [comment]
> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

This solves the problem for me.
