### ISSUE TITLE
Open Editor edge case usability issue

### ISSUE THREAD

**Issue by steodor** [microsoft/vscode#74444]
#### VSCode > About:
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:
1. open a single file in a deeper folder structure and/or with a long name (so that it triggers horizontal scrolling in the Open Editors area
2. try to use the Open Editors area to scroll horizontally or close the file ([see screenshot here](https://content.screencast.com/users/teodor.sandu/folders/Jing/media/e3147196-6f8f-484c-b4f1-a1861c47d46e/2019-05-28_1109.png))

The scrollbar is semi-transparent but the fact that it covers half of the writing makes it weird to read. The mouse pointer gets in the way too, while using it to scroll horizontally. It's also easy to miss the scrollbar since it's not very clearly delimited, and instead of grabbing it, to grab the file.

I understand that you calculate the height of the area based on the number of files in it, but if it has horizontal scrolling, could you factor its height in the calculation so that it doesn't overlap the files - and hence not trigger vertical scrolling?

I'm thinking that you may be doing this to save a few pixels of vertical space, so maybe do it as an opt-in user-configurable behavior? Personally i would trade a dozen pixels for better readability.

Thank you for your time :)

**Comment by isidorn** [comment]
Search for "horizontal scroll bar" and "tree" to find the duplicate

**Comment by steodor** [comment]
There are indeed similar issues but none quite the same, which is probably why you pointed me in a general direction instead of providing a specific issue that this one supposedly mirrors. However, i do understand that you have thousands of open issues which you probably struggle to prioritize so you don't have the necessary time to carefully read and cross-check everything. Also, this is only an annoyance rather than a critical issue, so let's leave it closed. Thanks again for your time, and have a nice day :)
