### ISSUE TITLE
Access to electron 'systemPreferences' API

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#74447]
I would like to access this electron API to subscribe to `AppleInterfaceThemeChangedNotification` OS event.

```js
systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', () => {
        const isDarkMode = systemPreferences.isDarkMode()
      });
```

**Comment by jrieken** [comment]
These issues aren't within the scope of VS Code and it's (general purpose) extension API. It seems you have something in mind that respects ambient light and theme information and I would suggest that you propose to implement that (describe your plans first, e.g. feature request) inside VS Code itself

**Comment by yifengyou** [comment]
Why can't call the electron api?
