### ISSUE TITLE
Snap package uses old icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74442]
The blurb on the snap package uses the old icon, it installs with the new icon tho

<img width="516" alt="Screenshot 2019-05-28 at 09 26 47" src="https://user-images.githubusercontent.com/1794099/58460393-d5ae6b80-812d-11e9-903d-6eeabedff73e.png">

**Comment by joaomoreno** [comment]
This needs to be updated in the snap's admin page: https://snapcraft.io/code-insiders/listing

I have updated Insiders. Let's leave this open for Stable. @misolori Is the icon coming out in the next stable?

**Comment by bpasero** [comment]
@joaomoreno yes we updated it in our distro for all our flavours.

**Comment by joaomoreno** [comment]
Given than even the [Twitter account](https://twitter.com/code) already shows the new icon, I've updated all snap icons:

![Screenshot from 2019-05-29 09-30-47](https://user-images.githubusercontent.com/22350/58537995-78312200-81f4-11e9-8418-429760980aa9.png)

**Comment by joaomoreno** [comment]
![Screenshot from 2019-05-29 09-31-59](https://user-images.githubusercontent.com/22350/58538057-a0208580-81f4-11e9-91ba-7a7bf2aa8a55.png)
