### ISSUE TITLE
Status zoom button should be a IStatusbarEntry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74454]
I noticed that [`ZoomStatusbarItem`](https://github.com/Microsoft/vscode/blob/f5bc332/src/vs/workbench/browser/parts/editor/resourceViewer.ts#L237) is a `IStatusbarItem`. This one is typically when you need full control over the rendering of the item, but it seems you are only using text. I suggest to change this to `IStatusbarEntry` and use `IStatusbarService#addEntry()` to show and hide it dynamically. You can also update properties dynamically on the returned object.

I had to push https://github.com/microsoft/vscode/commit/4eb7879ae17b2218b0d7c965040313b12894cdd7 because I noticed that some style changes broke the visual appearance of this item. We could avoid issues like these in the future by switching to the same model e.g. extensions are using too.

Is there anything that blocks us from going there? I could not see anything when I was checking the implementation quickly.

**Comment by mjbvz** [comment]
Thanks for the heads up. No blockers that I know of, I think I  just copied what other places in the code were doing

**Comment by skprabhanjan** [comment]
@mjbvz , I can take a look at this, Will do initial analysis and let you know. 
Any pointers from your side will also be helpful.

**Comment by mjbvz** [comment]
Start by looking at some of the other places we use  `IStatusbarEntry` in the codebase, such as [here](https://github.com/microsoft/vscode/blob/beae0293938db02a1f176bda489acc9ca1d6393e/src/vs/workbench/browser/parts/notifications/notificationsStatus.ts#L74) or [here](https://github.com/microsoft/vscode/blob/959246744ba70c4d8288921c0a04d9edbc1a894a/src/vs/workbench/contrib/tasks/electron-browser/task.contribution.ts#L110) to understand how to use the new API. Then see if you can convert the logic from the existing `IStatusbarItem` to use an `IStatusbarEntry` instead. 

One good initiail approach would be to convert the methods of `ZoomStatusbarItem` such as `show` and `hide` to use an `IStatusbarEntry` internally

**Comment by bpasero** [comment]
@mjbvz @skprabhanjan one potential issue I can forsee is that we seem to be opening a context menu from the position of the status bar element and with the other API you do not get any hold of that element.

However we can trick the API and simply put the id of the status bar entry as actual DOM ID to the status element (somewhere in `statusbarPart.ts`) and then use `document.getElementById()` with that ID to show the menu properly.

**Comment by burknator** [comment]
@skprabhanjan Are you working on this?

**Comment by skprabhanjan** [comment]
@burknator , Please feel free to work on it.
