### ISSUE TITLE
Print dialog opening cmd-P when cmd-tab'ing into vscode

### ISSUE THREAD

**Issue by lmapii** [microsoft/vscode#74456]
This might be related to the unresolved issue #26242

- VSCode Version: 1.34.0 (1.34.0)
- OS Version: macos 10.14.4 (18E226)

Steps to Reproduce:

1. Open vscode, open some file
2. cmd-tab to a different application (for me any application worked)
3. cmd-tab back to vscode
4. hit cmd-p to quick-nav
5. Empty print dialog appears (see screenshot)

Does this issue occur when all extensions are disabled?: **Yes**

When dismissing the dialog and staying within vscode the cmd-P binding works fine, the print dialog doesn't appear. Only when tabbing between apps (which I do a **lot**) the dialog appears again - which is very annoying.
<img width="1044" alt="Screenshot 2019-05-28 at 13 21 39" src="https://user-images.githubusercontent.com/7037131/58474841-980d0b00-814c-11e9-8355-6fe73a3874ed.png">

**Comment by kieferrm** [comment]
Can you provide us with any additional information you have?  We have no reproducible scenario. What you describe works just fine for me.

**Comment by lmapii** [comment]
Sadly I can't ... The problem disappeared after the second reboot, I'm no longer seeing the behaviour. Might not be vscode directly but something related to electron.

**Comment by kieferrm** [comment]
Bummer.
