### ISSUE TITLE
"s" key wont work

### ISSUE THREAD

**Issue by Ryezenburgslab** [microsoft/vscode#74453]
Issue Type: <b>Bug</b>

"s" key wont work upon installation or re installation. No idea how to reproduce the problem since its always been there.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_4625513|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|1.8.1

</details>

**Comment by gjsjohnmurray** [comment]
Is your vim extension doing something with that key?

Do you get the same problem if you disable the extension?

**Comment by kieferrm** [comment]
Pls try to reproduce the problem when starting Code with `code --disable-extensions` from the terminal.

**Comment by Ryezenburgslab** [comment]
I disabled all of the extensions and still no luck. Every time I press the s key it masks the next key press then allows me to keep typing.

**Comment by kieferrm** [comment]
@Ryezenburgslab I wonder if `s` is bound to any command. Let's find out:

1) Try <kbd>F1</kbd> > `Preferences: Open Keyboard Shortcuts`. This opens the keybinding editor.
2) In the search field, select the first icon on the right (Record Keys). 
3) Type `s`. 

Is `s` a keyboard shortcut bound to any command?

**Comment by Ryezenburgslab** [comment]
just checked and there is no shortcut appearing. I'm not sure what else to try? I cant find this problem anywhere else on the web and even a reset of the software wont work.

**Comment by kieferrm** [comment]
@rebornix any idea?

**Comment by rebornix** [comment]
I don't know what might be broken in this case .@Ryezenburgslab can you help with following questions

* What keyboard are you using?
* When you type `s` in Keybinding Shorcuts editor, do you see the same issue or it works fine?
* Can you please try typing in Integrated terminal and Settings Editor to see if you can reproduce?

**Comment by Ryezenburgslab** [comment]
@rebornix I am on a macbook pro 
When I am in the editor and press "s" in the footer it says "(s) was pressed. waiting for second key of cord..."
apologies, but I don't know how to do that last step.

**Comment by rebornix** [comment]
@Ryezenburgslab the information is helpful enough

> (s) was pressed. waiting for second key of cord...

It means there is a custom keybinding which uses `s` as the leader key. Can you run `Open Keyboard Shortcuts (JSON)` and search for `s`? I think you can find some keybindings like `"key": "s ... "`

**Comment by Ryezenburgslab** [comment]
Hell ya @rebornix!! I found the custom keybinding. Kinda feel like an idiot for it taking me this long, but thank you guys for all of the help. Yet again Github saves the day haha!

**Comment by rebornix** [comment]
@Ryezenburgslab good to hear it works for you ;)

**Comment by edgargrs** [comment]
https://github.com/microsoft/vscode/issues/63779
I was suffering for the same thing with dash (-)
thank you very much to all :+1:
