### ISSUE TITLE
Remove atom/language-c grammar from objective-c extension

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#74450]
See https://github.com/microsoft/vscode/issues/74219 for details.

**Comment by alexr00** [comment]
I have checked that our test .mm file looks ok, but I don't use Objective-C++ often. @ambershark-mike @Muirey03 if you are interested/willing to sanity check the Objective-C++ syntax highlighting that would be very helpful! I have just brought in the changes that we talked about about [here](https://github.com/microsoft/vscode/issues/74219). The insiders build tomorrow will have the changes.

**Comment by Muirey03** [comment]
Sure, I'll check it out tomorrow then, thank you.

**Comment by ambershark-mike** [comment]
Thanks @alexr00!  I'll try to check it out as well.  I don't use obj-c very often either.  I try to write more cross platform code (usually C++), but sometimes get stuck in a platform specific language.  I know just enough objective-c to be dangerous (and frustrated). :laughing:

**Comment by Muirey03** [comment]
I tried it out a bit and everything seemed to be working correctly, thank you. @alexr00
