### ISSUE TITLE
Debug status should be IStatusbarEntry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74455]
I noticed that [`DebugStatus`](https://github.com/Microsoft/vscode/blob/4eb7879/src/vs/workbench/contrib/debug/browser/debugStatus.ts#L19) is a `IStatusbarItem`. This one is typically when you need full control over the rendering of the item, but it seems you are only using text and an icon we probably already have in our octicon set. I suggest to change this to `IStatusbarEntry` and use `IStatusbarService#addEntry()` to show and hide it dynamically. You can also update properties dynamically on the returned object.

If the icon is missing we can add it to our set. Just using icons from our octicon set ensures that they all look good when compared to each other.

//cc @misolori

**Comment by isidorn** [comment]
Makes sense, let's do this next week in debt week.

**Comment by isidorn** [comment]
Much cleaner now 🙌

**Comment by bpasero** [comment]
@isidorn thanks!
