### ISSUE TITLE
Octicons: ensure size is proper relative to others

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74463]
Noticed that some of the icons in the octicon set seem to appear larger, e.g.:

![image](https://user-images.githubusercontent.com/900690/58487478-ee3b7780-8167-11e9-8e43-d244f045cb6e.png)

I suggest to:
* fake a status entry that shows all icons next to each other
* tweak those that appear relatively larger/smaller

With the end result that all icons are relatively the same size to each other 👍

**Comment by misolori** [comment]
Refs: #74285
