### ISSUE TITLE
Test: True color in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#74467]
Test for https://github.com/microsoft/vscode/issues/18544

Complexity: 3

- [x] mac/Linux @kieferrm
- [x] Windows (use WSL in terminal) @sbatten 

The integrated terminal now supports true color (24-bit) rendering, please verify that the colors are working in both the DOM renderer\* and canvas renderer:

```
"terminal.integrated.rendererType": "dom",
"terminal.integrated.rendererType": "canvas",
```

Print colors in this mode to the terminal uses the `CSI Pm m` escape sequence where Pm is:

- `Pm = 3 8 ; 2 ; Pr ; Pg ; Pb` -> Set foreground color to RGB Pr/Pg/Pb.
- `Pm = 4 8 ; 2 ; Pr ; Pg ; Pb` -> Set background color to RGB Pr/Pg/Pb.

The easiest way to test this is via `echo -e`:

```
echo -e '\x1b[38;2;255;0;0mrgb(255, 0, 0) red foreground'
echo -e '\x1b[48;2;0;0;255mrgb(0, 0, 255) blue background'
```

Experiment with mixing true color with other colors, for example true color foreground and ansi background `\x1b[38;2;255;0;0m\x1b[42m`. For ANSI color mode use `\x1b[3${x}m` (fg) and `\x1b[4${x}m` (bg), for 256 color mode (a fixed palette) use `\x1b[38;5;${num}m` (fg) and `\x1b[48;5;${num}m` (bg).

More details/references:

- Search "(SGR)" on https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
- https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9
- https://askubuntu.com/a/821163/409516

\* You may run into this issue in the DOM renderer https://github.com/microsoft/vscode/issues/74183, it will be fixed in tomorrow's build.

**Comment by kieferrm** [comment]
This works as expected in all variations. CPU consumption when scrolling large colored output goes up to 100% in canvas mode and beyond that in dom mode. Dom mode in general is significantly slower.

**Comment by Tyriar** [comment]
The slow down is expected for canvas as it only caches the first 16 colors, the webgl renderer caches everything.
