### ISSUE TITLE
remove deleted folders from recent

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#74465]
1. create a folder
2. open in folder vscode
3. close vscode
4. delete folder
5. open vscode

observe that the folder is in recents, autocompletes when clicking on "more" too. Ideally for it to be removed. Feature request is to remove it from recents so it doesn't bug me when I search for projects.

Thank you.

**Comment by roblourens** [comment]
You can have many folders in your recents and we shouldn't hit the disk many times for each one when you open a vscode window. So instead if you try to open it and we find that it doesn't exist anymore, then we remove it from the list.
