### ISSUE TITLE
Test go to definition enhancements

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74466]
refs: https://github.com/microsoft/vscode/issues/74072, https://github.com/microsoft/vscode/issues/57537, https://github.com/microsoft/vscode/issues/53164, https://github.com/microsoft/vscode/issues/52743

- [x] any @mjbvz
- [x] any @dbaeumer

Complexity: 2

Many small improvements have gone into go to definition and friends. Test that

* you can cancel a request when hitting ESC (test when TS is starting or with your own LSP server)
* go to definition honours the `workbench.editor.revealIfOpen` setting, e.g reuses an editor from another group when `revealIfOpen` is set
* when having multiple results and when using peek you can now filter the RHS tree using the tree filter tools
* when having multiple results and when not using peek (`"editor.gotoLocation.multiple": "goto"`) you can navigate all results using F12. A status message should provide guidance. ESC or cursors moves leave this mode

**Comment by dbaeumer** [comment]
Nice improvements!
