### ISSUE TITLE
Intellisense on nodejs app files with no extension

### ISSUE THREAD

**Issue by davidmcl** [Microsoft/vscode#7446]
- VSCode Version: 1.2.0
- OS Version: CentOS 7 -- NodeJS app

Steps to Reproduce:

1.  Use express-generator to create a nodejs app; it creates a bin/www file with no extension
2.  When editing the bin/www file, with language mode as JavaScript, the require, process, etc. entries are indicated as errors.
3.  If a .js extension is added to the bin/www file - the intellisense no longer shows the entries as errors

A bit strange (at least from my perspective) as one would think that intellisense would be driven from the Language Mode not the extension, or lack thereof. "Normal" javascript intellisense is active BTW, it just seems to not be picking up the nodejs references.

Really like VSCode, VS Community just seems "too heavy" for a lot of small-medium projects.

Thanks,
David

![screenshot from 2016-06-09 00-46-02](https://cloud.githubusercontent.com/assets/2047925/15915910/e3c364ca-2ddc-11e6-83c6-101a1099c9a2.png)
![screenshot from 2016-06-09 00-46-29](https://cloud.githubusercontent.com/assets/2047925/15915913/e7b01d94-2ddc-11e6-8032-0a4f7fe49137.png)
![screenshot from 2016-06-09 00-53-52](https://cloud.githubusercontent.com/assets/2047925/15915914/eacc2e6e-2ddc-11e6-8eb5-c149a16dcee0.png)

**Comment by dbaeumer** [comment]
We can now send the mode kind in an open. Need to see if this fixes it.

**Comment by dbaeumer** [comment]
Sending the mode kind is only available in TS 2.0. Need to wait until it is officially available.

**Comment by dbaeumer** [comment]
Unfortunately this will not make the August milestone since TS is not ready yet.

**Comment by dbaeumer** [comment]
This got fixed for 1.6 release.
