### ISSUE TITLE
Adding expression to watch is broken

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#74478]
Issue Type: <b>Bug</b>

1. Start debug process
2. Press the plus button to add an expression, clear it without entering anything
3. Press add again, it doesn't appear.
4. Press clear again.
5. Repeat 3 + 4 a much as possible.
6. Double click the watch box, you will see the expression text boxes are just stacking.

VS Code version: Code - Insiders 1.35.0-insider (84deb302d7e9ea991a1d0edfd4b4261143f659ff, 2019-05-28T05:16:57.050Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (14.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment]
This is fixed in latest via https://github.com/microsoft/vscode/commit/8fd154e360dee40b123018f5396906fb3f3d655e Broken by disposable store change
fyi @mattbierner 

Thanks for reporting
