### ISSUE TITLE
Test: Better Merge complete diff view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#74473]
Refs: https://github.com/microsoft/vscode/pull/74231

- [x] any @mjbvz 

Authors: @rebornix 

Complexity: 2

Previously when you try to compare changes of a merge conflict, there is no context around the changed/modified code and it always shows in current active editor. This month we improved the experience by

* When we compare the change in a merge conflict, we show complete diff of the whole document and scroll to the position of the merge conflict
* User can use `merge-conflict.diffViewPosition` to control the position of the diff view, we now support three values with the api limitation 
  * "Current", which is the legacy behavior
  * "Beside", depends on the value of `workbench.editor.openSideBySideDirection` and it will not create a new editor group if the sibling editor group exits
  * "Below", it will always create a editor group below

**Comment by gjsjohnmurray** [comment]
> "Besides", depends on the value of workbench.editor.openSideBySideDirection and it will not create a new editor group if the sibling editor group exits

Looking at the [code](https://github.com/microsoft/vscode/blob/c3fe962b89dcab0f1ba765e0728c11fddffa2a4a/extensions/merge-conflict/package.json#L122) it seems this option is "Beside" :+1: - so "Besides" is just a typo in this testplan item.

**Comment by rebornix** [comment]
@gjsjohnmurray thanks for the spell checking ;)
