### ISSUE TITLE
Problems markers onthe scrollbar are too dim or too bright

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#74477]
Issue Type: <b>Bug</b>

With out of the box Dark theme problems (infos,warnings) are too dim:
![image](https://user-images.githubusercontent.com/7345761/58498242-513c0700-8186-11e9-835a-65f66ed709fc.png)

And with out of the box Light theme these items (infos,warnings) are too bright, it's hard to find more important markers like currently selected word or search item:
![image](https://user-images.githubusercontent.com/7345761/58498272-644ed700-8186-11e9-8b69-2aab4f1f4be8.png)

These markers should be themable and/or default themes should be fixed

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.0-15-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3811)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (1.51GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
atlascode|atl|1.4.0
better-toml|bun|0.3.2
ccls|ccl|0.1.26
path-intellisense|chr|1.4.2
doxdocgen|csc|0.4.2
vscode-eslint|dba|1.9.0
vscode-dash|dee|2.1.0
java-decompiler|dgi|0.0.2
xml|Dot|2.4.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
code-runner|for|0.9.9
kotlin|fwc|0.1.13
kotlindebug|fwc|0.2.2
code-file-nav|jak|0.7.2
svn-scm|joh|2.48.1
language-haskell|jus|2.6.0
favorites|kdc|2.4.5
saltstack|kor|0.0.5
sftp|lix|1.12.7
AWK|lug|0.0.2
bash-ide-vscode|mad|1.3.3
vscode-todo-parser|min|1.9.1
vscode-remote-workspace|mkl|0.42.0
vscode-language-pack-ru|MS-|1.34.2
vscode-kubernetes-tools|ms-|1.0.0
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
Go|ms-|0.10.2
vscode-typescript-tslint-plugin|ms-|1.1.0
gradle-language|nac|0.2.3
printcode|nob|3.0.0
vscode-subword-navigation|ow|1.2.0
vscode-docker|Pet|0.6.2
java|red|0.45.0
vscode-yaml|red|0.4.1
vscode-sort-json|ric|1.13.0
perl|ric|0.9.0
bash-debug|rog|0.3.5
rust|rus|0.6.1
bash-beautify|sha|0.1.1
vscode-hexdump|sle|1.7.2
shellcheck|tim|0.6.0
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
sort-lines|Tyr|1.8.0
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
debug|web|0.23.1
jinja|who|0.0.8
clang-format|xav|1.9.0
vscode-proto3|zxh|0.2.2

(2 theme extensions excluded)

</details>

**Comment by misolori** [comment]
Thanks for the feedback, please see #66223 for theming decorations in the scrollbar.
