### ISSUE TITLE
Python extension is not working

### ISSUE THREAD

**Issue by anonymous432** [Microsoft/vscode#7447]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. I don't have any idea about it.
2. But in others like javascript, c# I can get the extension.

**Comment by alexandrudima** [comment]
@anonymous432 What is the id of the python extension you are using?

**Comment by dbaeumer** [comment]
Closing. Did not receive a response in 14 days.
