### ISSUE TITLE
Autocomplete Not Working Within User Snippets Until Pressing Esc

### ISSUE THREAD

**Issue by tobyjug** [microsoft/vscode#74475]
- VSCode Version: 1.34.0
- OS Version: 10.14.5

Steps to Reproduce:

1. Trigger Snippet
2. Start typing (no autocomplete)
3. Press `esc`
4. Start typing (autocomplete works)

Does this issue occur when all extensions are disabled?: Yes

CSS example (first without pressing `esc`, then deleting, pressing `esc` and trying again):

![2019-05-28 16-58-18 2019-05-28 16_59_14](https://user-images.githubusercontent.com/8949669/58493020-fd232980-8169-11e9-90da-44abac49d29e.gif)

**Comment by mjbvz** [comment]
Set `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions in snippets
