### ISSUE TITLE
Switch native keyboard bindings?

### ISSUE THREAD

**Issue by TomasPuverle** [microsoft/vscode#74470]
I work across multiple OSs but would like to avoid having to learn three separate sets of keybindings.

Is there a clean way to say, e.g. on Windows, "use the Linux key bindings"?  I know I could copy all of them to my user settings, but that seems... a bit clunky?  Also, it would mean the bindings could diverge over time etc.

Thank you.

**Comment by atomgalaxy** [comment]
I agree this would be nice to have. CLion offers this and it's great.
