### ISSUE TITLE
Allow to provide custom activity bar Icons

### ISSUE THREAD

**Issue by austincondiff** [microsoft/vscode#74488]
In my opinion, the activity bar icons are too big and it becomes a distraction because they consume too much visual weight.

I'd like the ability to theme the icons, and customize their size, padding, color, etc.

**Comment by austincondiff** [comment]
For example, I'd like to do something like this...

![framer-vscode@2x](https://user-images.githubusercontent.com/806104/58577722-b63a4000-820c-11e9-80c8-d57a4cc5b40c.jpg)

**Comment by bpasero** [comment]
//cc @misolori

**Comment by JonathanTroyer** [comment]
Honestly, being able to change all icons in VSCode (not just the file icons) would be fantastic.

**Comment by JonathanTroyer** [comment]
Duplicate of...?

**Comment by misolori** [comment]
Duplicate of #79130

**Comment by austincondiff** [comment]
Is it though? I am referring to the navigation icons to the left #79130 is talking about the expand/collapse icons.

**Comment by misolori** [comment]
@austincondiff it's titled "Allow configuration of product icons" so any issues asking to provide custom icons are being pointed there. If you also read the comments people are asking for the same thing.
