### ISSUE TITLE
Extension pack details page show duplicate extensions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74485]
Testing https://github.com/microsoft/vscode-remote-release/issues/466

**repo**
1. In VS Code, browse to the `Angular essentials` pack
1. Open the `Extension pack` details section

**Bug**
Contributed extensions are duplicated in the list. Here's another extension pack for example:

![Screen Shot 2019-05-28 at 11 39 01 AM](https://user-images.githubusercontent.com/12821956/58503269-38f3ca00-813d-11e9-9b68-2ff1eacc4fb8.png)

**Comment by sandy081** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/9741ce6a20066e46e95b1400a23ca7d9adf7df09
