### ISSUE TITLE
Line breaks in terminal window when changed editor-fontsize in settings.json .

### ISSUE THREAD

**Issue by leedonhyun** [Microsoft/vscode#7448]
- VSCode Version:

Version 1.3.0-insider
Commit 7c75479a06da31ac73c8ac372acf37fc380e8091
Date 2016-06-09T02:08:47.725Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
 Windows 10

1. 
![animation](https://cloud.githubusercontent.com/assets/8449892/15918165/fd8984f4-2e3e-11e6-9710-024ad41bd779.gif)

2.

**Comment by Tyriar** [comment]
@leedonhyun that was fast :) this is an upstream issue with the new framework https://github.com/sourcelair/xterm.js/issues/62

**Comment by Tyriar** [comment]
This should be fixed in v1.3.0, you can verify on the Insiders build.
