### ISSUE TITLE
Java Extension pack does not show contributed extensions 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74489]
**repo**
1. Open `java extension pack` in VS Code

**Bug**
The extension details page only shows a `contributions` section, and there is no information about which extensions it contributes

![image](https://user-images.githubusercontent.com/12821956/58504681-05666f00-8140-11e9-8ced-480b1ce8b592.png)

**Comment by sandy081** [comment]
Filed against java extension pack extension.
