### ISSUE TITLE
DocumentLink ranges aren't accurate when used in tooltip?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#74483]
Ubuntu 19.04

#74311

I added the following to show where the link was going:

```ts
	provideDocumentLinks(document: vscode.TextDocument, token: vscode.CancellationToken): vscode.DocumentLink[] | undefined {
		// While building the virtual document we have already created the links.
		// Those are composed from the range inside the document and a target uri
		// to which they point
		const doc = this._documents.get(document.uri.toString());
		if (doc) {
			doc.links.forEach(element => {
				element.tooltip = `Hello from ${element.target!.fsPath}:${element.range.start.line}:${element.range.start.character}`;
			});
			return doc.links;
		}
	}
```

I thought it was going to show where the link was going to be, but was not:

![image](https://user-images.githubusercontent.com/2193314/58501400-30999000-8139-11e9-8f97-88014bf524a0.png)

![image](https://user-images.githubusercontent.com/2193314/58501394-2c6d7280-8139-11e9-855d-3018ddf20f13.png)

Codebase: https://github.com/Microsoft/node-pty

**Comment by mjbvz** [comment]
Is that bug that we are rendering this as plaintext, not markdown?

**Comment by Tyriar** [comment]
`emitter.event...` on line `22` is showing in the tooltip that the line is `28` and the character position is `18`

**Comment by mjbvz** [comment]
Aren't you hovering over `event` on line 29?

**Comment by Tyriar** [comment]
Yes, in the references view it's line 29, but it says that the reference is on line 22, but the tooltip (from `element.range.start.line`) says 28?

**Comment by mjbvz** [comment]
As we discussed offline, in this case `range` is range of the link itself, not the reference it points to
