### ISSUE TITLE
Fedora 30 (Gnome) graphics bug

### ISSUE THREAD

**Issue by danieldaeschle** [microsoft/vscode#74481]
- VSCode Version: 1.34
- OS Version: Fedora 30

#### Launch with `code --disable-extensions` to check.
Does this issue occur when all extensions are disabled?: No (disable GPU also doesn't working)

Behaviour:
![image](https://user-images.githubusercontent.com/30751516/58500934-8d219d00-8183-11e9-8c85-d301cf97e42e.png)

**Comment by danieldaeschle** [comment]
Only Minimap and Terminal looks like this.

**Comment by kieferrm** [comment]
@danieldaeschle What does the terminal look like when you change the terminal renderer to `dom` in your user settings?
```json
"terminal.integrated.rendererType": "dom"
```

**Comment by Tyriar** [comment]
I'm surprised to hear `code --disable-gpu` doesn't work, that's meant to disable GPU rendering in Chromium and that's the only way that artifacts like this would show AFAIK. Some other options:

- Update drivers (if possible)
- Set `"terminal.integrated.rendererType": "dom"`

@danieldaeschle is it always like this or just after sleeping and resuming your PC?

**Comment by Lunrtick** [comment]
Hi - I recently opened #74480 . I just tested with `--disable-gpu`, and that fixes my issue.

For some extra info, I am using a Vega 56 with Mesa 19.0.5, Kernel 5.0.17-300.fc30.x86_64 .

**Comment by Tyriar** [comment]
Ah ok, so this is either a driver problem or a chromium should be disabling your GPU problem. Hopefully the latter should be fixed when we update Electron and if you see it in Chrome as well you should report there.

**Comment by danieldaeschle** [comment]
I also think that this is a driver bug, because i downgraded the version which works in past but now it won't. I have the newest graphics drivers (amd). But i can't do anything.

**Comment by danieldaeschle** [comment]
Sorry, --disable-gpu worked. Maybe i had a type on first try.
