### ISSUE TITLE
Code overview visual issues when fullscreen

### ISSUE THREAD

**Issue by Lunrtick** [microsoft/vscode#74480]
- VSCode Version: 1.34.0
- OS Version: Fedora 30, Gnome 3.32.2, 5.0.17-300

Steps to Reproduce:
1. Open vscode windowed but covering full screen width (1920x1080)
2. See issues with overview/code map scroller on right side
3. Make window smaller - no more issues
4. See different problem with .js file - no strange characters, but very jumpy/jittery.

I've attached a gif showing this issue - look at the code overview on the right (the pixelated nature of the gif is because I converted it from a screen recording).
![EwUZqWGZBgh5QO5tHIVoZ3eYWzCELJj4GKX2DSBo](https://user-images.githubusercontent.com/31224135/58500893-6e230b00-8183-11e9-9d7b-cceea954397b.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
See also #74481.

**Comment by Tyriar** [comment]
Same root cause:

/duplicate https://github.com/microsoft/vscode/issues/74481
