### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by stax76** [microsoft/vscode#74486]
First of all Visual Studio Code is amazing! I don't have a real issue like a bug or something, just maybe the icon color is too similar too Visual Studio, maybe a totally different color would work better.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vs-code-xml-format|fab|0.1.5
python|ms-|2019.4.12954
powershell|ms-|1.12.1

**Comment by misolori** [comment]
@stax76 can you post a screenshot? Do you mean that the VS Code blue is too similar to the VS purple?

**Comment by stax76** [comment]
> Do you mean that the VS Code blue is too similar to the VS purple?

Yes, I mean that.

**Comment by misolori** [comment]
Thanks for the feedback. We’re hoping to update our product icon in then next release which makes the colors a bit more vibrant and modifies the shape to make it more noticeable next to the VS icon. Will close this issue but feel free to post any additional comments in #71827.
