### ISSUE TITLE
Blank editor opened when quickly clicking "Compare changes"

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74499]
Issue Type: <b>Bug</b>

Testing #74473

**Repo**
1. Set `"merge-conflict.diffViewPosition": "Below"`
1. Open a file with merge conflicts:

```
<<<<<<< HEAD
blafasdfas
=======
fdsaffasdfas
>>>>>>> master
```

1. Quickly click the `Compare Changes` code lens twice

**Bug**
Two editors open below, but the first editor is blank:

![Screen Shot 2019-05-28 at 2 21 56 PM](https://user-images.githubusercontent.com/12821956/58513296-fee1f280-8153-11e9-968b-c44838e29784.png)

VS Code version: Code - Insiders 1.35.0-insider (a429fd13565d3392c87e31228ec9e8a2bf3708d5, 2019-05-28T16:36:39.818Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.93GB free)|
|Process Argv|-psn_0_28347143|
|Screen Reader|no|
|VM|18%|
</details>

**Comment by mjbvz** [comment]
I believe the expected behavior is that only a single editor should open when clicking this command multiple times. You can open multiple editors when using `"merge-conflict.diffViewPosition": "Beside"` and quickly clicking `compare changes` too, but all the editors in that case have content

**Comment by rebornix** [comment]
Agree that we should do what's being suggested above. Currently an extension doesn't have info about the visible editors or editor groups so we can't archive that with current API. Closing it as it's not actionable at this moment.
