### ISSUE TITLE
Unable to install remote debugging extension on VS code 1.34.0

### ISSUE THREAD

**Issue by skasturi** [microsoft/vscode#74498]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Steps to reproduce: 
1. Go to Extensions and search for "remote development"
2. Open "Remote development 0.14.0"
3. Click on "Install" 
4. The icon changes to "Installing" and switches back to "Install" 
5. VS code shows the following error below

![image](https://user-images.githubusercontent.com/482709/58513163-b7f3fd00-8153-11e9-88c8-3888d9ab829f.png)

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/58533792-54181580-81e1-11e9-9979-cd411ca6c9ab.png)

You're not using Insiders.

**Comment by skasturi** [comment]
Thank you @gjsjohnmurray . That worked.
