### ISSUE TITLE
increaseIndentPattern cannot be case insensitive

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#74493]
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open language-configuration.json
2. Go to indentationRules > increaseIndentPattern
3. Write something super basic like `(?i)function`
4. Writing `function` in your does not indent correctly

No matter what I write or try; having increaseIndentPattern case insensitive never works.
If I remove (?i) it works but is of course case sensitive.

Video demonstration: [video](http://hezkore.com/junk/2019-05-28_21-47-03.mp4)

**Comment by gjsjohnmurray** [comment]
This might already be possible using a not-yet-documented feature I found when logging #72989
 
The clue I found is in [this comment on #27591](https://github.com/microsoft/vscode/issues/27591#issuecomment-305175307).

**Comment by Hezkore** [comment]
Any update on this?
This is still very much an issue for me.

**Comment by larshp** [comment]
the linked comment above works, example

```
    "indentationRules": {
      "increaseIndentPattern": {
        "pattern": "^\\s*(METHOD|IF|LOOP|CLASS|CASE)\\s+.+\\.$",
        "flags": "i"
      },
      "decreaseIndentPattern": {
        "pattern": "^\\s*(ENDMETHOD|ENDIF|ENDLOOP|ENDCLASS|ENDCASE)\\.$$",
        "flags": "i"
      }
    }
```

**Comment by Hezkore** [comment]
Yeah using flags do work, which should really be documented.
Should we perhaps close this then?
