### ISSUE TITLE
ctrl+` has to be pressed twice when terminal is not in foucs

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode#74491]
- VSCode Version: 1.35.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open file
2. Open terminal using ctrl+`
3. Click on the file
4. Attempt to close terminal using ctrl+`. It will not close. 

If the terminal is in focus, pressing ctrl+\` works fine to show/hide the terminal. If the terminal is not in focus, you have to hit ctrl+\` twice and then it will hide (showing still only requires a single press). 

The action should be consistent regardless of whether or not the terminal is in focus, especially since it is not easy to see if the terminal is in focus or not, so you don't know how many times you will need to hit ctrl+`.

**Comment by Tyriar** [comment]
Try this keybinding

```
{ "key": "ctrl+`",           "command": "workbench.action.terminal.focus", "when": "!terminalFocus" },
```
