### ISSUE TITLE
Option to hide terminal when clicking on something other than the terminal

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode#74492]
It would be great if there was an option to hide the terminal if you click on a window other than the terminal itself. It is really annoying when you click on a file tab, and the terminal is still showing (I usually have the terminal as large as possible so the only thing I see is the file tabs). 

Another way to set this option would be to have a button on the terminal that if pressed, would cause this action to take place. This way you could toggle between this if you wanted (for example if you want to temporarily turn this off so that you can cut/paste between the terminal and a file). Having to hit ctrl+\` every time I want to show/hide the terminal is too slow.

**Comment by Tyriar** [comment]
This is basically https://github.com/microsoft/vscode/issues/3742 but for the panel instead of side bar, you could also accomplish this by hitting ctrl+` to hide, which I think will focus the last active editor group.
