### ISSUE TITLE
New insiders icon does not look great with yellow warning modal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74490]
Issue Type: <b>Bug</b>

**Repo**
1. Create a multi folder workspace
1. Then try opening another folder
1. This should trigger a modal asking if you want to save the workspace

**Bug**
Nit but the blue/green icon does not look great with the yellow alert icon in the modal:

![Screen Shot 2019-05-28 at 12 00 15 PM](https://user-images.githubusercontent.com/12821956/58504841-5fffcb00-8140-11e9-85a8-5c3bb5e1e69c.png)

VS Code version: Code - Insiders 1.35.0-insider (a429fd13565d3392c87e31228ec9e8a2bf3708d5, 2019-05-28T16:36:39.818Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_28347143|
|Screen Reader|no|
|VM|18%|

|Item|Value|
|---|---|
|Remote|SSH: az-box1|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.79GB (5.02GB free)|
|VM|0%|
</details>

**Comment by misolori** [comment]
@bpasero can we provide a custom icon for the native warning dialogs?

**Comment by bpasero** [comment]
@misolori not to my knowledge, maybe @deepak1556 knows

**Comment by bpasero** [comment]
Actually I take it back, it looks like Electron dialogs can have an `icon` property. This one does not seem to be documented though, so it is unclear if it will end up being an overlay over the warning icon or replace it entirely. I think we need to experiment.

From https://github.com/electron/electron/blob/3-0-x/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback

**Comment by misolori** [comment]
Since we don't plan on updating our logo (insiders logo has transparency) will close this as `won't fix`.

**Comment by misolori** [comment]
Forgot that this now fixed in the recent macOS icon update:

![image](https://user-images.githubusercontent.com/35271042/113225583-d9880900-9242-11eb-8117-7cf132edf051.png)
