### ISSUE TITLE
Search input field with weird left margin

### ISSUE THREAD

**Issue by filipetoyoshima** [microsoft/vscode#74496]
Issue Type: <b>Bug</b>

Just use the search tool by clicking on the magnifying glass icon and type something that should fill all the input field.

![Peek 2019-05-28 17-51](https://user-images.githubusercontent.com/29482983/58511431-2dba9180-8171-11e9-849a-e43267c706d2.gif)

VS Code version: Code - Exploration 1.32.0-exploration (14236f9f44cc7c94055bb8e65ebda29a4a91ddc7, 2019-02-18T11:47:59.892Z)
OS version: Linux x64 4.15.0-50-generic

**Obs:** On regular VSCode, it works finely

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2147)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|7.71GB (0.47GB free)|
|Process Argv|. --no-extensions|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
That looks like a very old exploration build, and this has been fixed already, why are you using the exploration build? Can you update it?
