### ISSUE TITLE
Terminal: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7450]
Seeing this when making the terminal visible in selfhost after having quite some output. It seems to try to access a div that is not existing in the array:

<img width="1458" alt="screen shot 2016-06-09 at 07 44 54" src="https://cloud.githubusercontent.com/assets/900690/15919920/173df0b6-2e16-11e6-90e8-dededd2c457a.png">

**Comment by Tyriar** [comment]
Duplicate, already fixed https://github.com/Microsoft/vscode/issues/7357
