### ISSUE TITLE
Extensions panel missing Icons

### ISSUE THREAD

**Issue by DianaNites** [microsoft/vscode#74502]
Issue Type: <b>Bug</b>

I'm on Gentoo Linux and downloaded the 64bit tar.gz and ran ./code

Everything works, but the extension marketplace has no icons at all, and the space where they should be is missing.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.19.27-gentoo-r1

**Comment by kieferrm** [comment]
@DianaNites can you pls add a screenshot to this issue? I wonder how wide you made your side bar. We do hide the icons when the side bar is too narrow.

**Comment by DianaNites** [comment]
Whatever the default size is, i hadnt changed it. To my knowledge, it works fine on windows by default. Though i havnt newly installed VSCode on there recently, so can't say for sure.

> We do hide the icons when the side bar is too narrow.

That, I was unaware of, and resizing it to be *slightly* wider fixed the issue. Never even occurred to me to do that, thanks.

For reference, my screen resoultion is 1366x768 and using X11.
