### ISSUE TITLE
Python Interactive Illegal value for token color

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#74509]
Issue Type: <b>Bug</b>

I've encountered another issue after updating to 1.34.0

Every time I try and run code in `Python Interactive` i.e. select code and Ctrl+Enter I get the following message in the `Python Interactive` window.

Error: Illegal value for token color:  at 
  
    in MonacoEditor
    in div
    in Code
    in div
    in div
    in div
    in div
    in div
    in Cell
    in ErrorBoundary
    in div
    in div
    in div
    in ContentPanel
    in div
    in div
    in MainPanel

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.33GB (6.56GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.10
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.66
paredit-revived|cos|0.1.22
gitlens|eam|9.8.1
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.9.0
flatbuffers|gab|0.1.0
vscode-test-explorer|hbe|2.11.0
pgsql-html|hub|0.0.7
rest-client|hum|0.21.3
latex-workshop|Jam|7.0.0
vscode-cudacpp|kri|0.1.1
restructuredtext|lex|109.0.0
rainbow-csv|mec|1.1.1
python|ms-|2019.5.17059
cpptools|ms-|0.23.1
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0
rust|rus|0.6.1
code-spell-checker|str|1.7.12
cmake|twx|0.0.17
vscode-lldb|vad|1.2.3
vscode-icons|vsc|8.7.0
debug|web|0.23.1
markdown-all-in-one|yzh|2.3.1

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@david-waterworth please move the issue to the python extension https://github.com/Microsoft/vscode-python/issues. Thanks!
