### ISSUE TITLE
textDocument/codeAction, documentSymbol, documentHighlight get sent before didOpen

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#74504]
- VSCode Version: 1.34.0 (probably others)
- OS Version: Windows (probably others)

Steps to Reproduce:

1. Open a document with some LSP provider like the C/C++ extension.

Bug: VS Code sends our C/C++ extension textDocument/codeAction and textDocument/documentSymbol messages for the opened file before it sends a textDocument/didOpen. If the file was previously opened with the cursor on an identifier then it will also send a textDocument/documentHighlight message. It seems buggy to us to not send the didOpen first, because we aren't able to properly handle the other messages without processing the didOpen.

FYI, this is a low-priority issue for us because we can workaround the early messages by ignoring them -- VS Code resends the messages after the didOpen….it just caused an unexpected bug in our development builds because we weren't properly handling for this unexpected message ordering.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
I doubt this is true but it then must be an LSP client lib issue. The implementation for things like hover work with the document instance which, when set/added fires the event.

**Comment by dbaeumer** [comment]
Actually, this is very wired and shouldn't happen. I will check this in the LSP test bed. @sean-mcmanus I know that you do a lot of tricks in our custom middleware. Have you checked that the reordering is not caused there?

**Comment by sean-mcmanus** [comment]
@dbaeumer  Oops, sorry for the false report -- yeah, our protocolFilter.ts didOpen handler makes an async call that delays sending the didOpen.

**Comment by mjbvz** [comment]
Changing this to be marked as `upstream`
