### ISSUE TITLE
Support fixed width terminal windows

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#74501]
Issue Type: <b>Feature Request</b>

For the integrated terminal, please add an option to set a fixed _logical_ width, and a horizontal scroll bar when the terminal window is smaller than the logical width. Related to #46192 (but specific to the integrated terminal). 

Seems also likely that this is what #48897 was asking for.

Thanks.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Tyriar** [comment]
@tlemo I'm interested in your use case? Do you just use small windows and/or some program is better on wide?

**Comment by tlemo** [comment]
Hi Daniel,

It's both. Perhaps a bit ironically, but on widescreen monitors it's nice
to be able to use the terminal on the side (instead of top/bottom docking).

And building from the command line can easily produce lines longer than
100+ columns. Same with some non-build logs. The general case of
line-oriented output, where line wrapping can be jarring.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/79246

**Comment by jagdishrajan** [comment]
> @tlemo I'm interested in your use case? Do you just use small windows and/or some program is better on wide?

@Tyriar, I create PS functions that output other context specific PS commands that are quite long (because of  blob paths, connection strings etc.)  These then need to be copied and pasted in a single  line, so having the original output wrap disrupts this methodology.

**Comment by Tyriar** [comment]
@jagdishrajan you're meant to be able to be easily copy wrapped lines by double clicking them, is PS's table formatting preventing that or something?

**Comment by ultraGentle** [comment]
Integrated terminal with (1) no line wrapping + (2) horizontal scroll would also be useful to me.  

**Use case** 
I'm using the Google Firebase local emulator, and logs are output to the terminal.  

Logs may include long strings: urls, ids, tokens, etc. -- also, nested JSON.    

I don't need to see all their contents; I just need to be able to see back up the history of logs.  

With line wrap, the visual structure is disrupted and it's hard to see what's going on.  

I'm on a small laptop, and I have the terminal as a column at the right.  

**Current workaround**
`tput rmam` command truncates long lines -- but then you can't see what's to the right, if you need it.

**Comment by tony-bony** [comment]
I often print in the Terminal the contents of a pandas `DataFrame`. Wrapping the output makes the dataframe totally unreadable.

**Comment by jagdishrajan** [comment]
@Tyriar, terminal output can be used for many purposes such as reviewing results, copying portions of results or "other commands as results" and re-pasting them.  As @tony-bony said columnar output that's aligned is difficult to review when wrapped.

It's also important to select and copy multiple lines and vertical selection of results.  When selecting these results switching to the mouse rather continuing to use the keyboard is inconvenient. (Vscode editor has works well with its Ctrl+Alt+Shift+arrow shortcut for this).

**Comment by codeRSH** [comment]
My requirement is also similar to what @tony-bony has suggested above. 

VScode should allow to at least use the full width of the screen when Terminal docked at the bottom. It's not happening right now. 

Any workaround or timeline for this fix of terminal width?

**Comment by Tyriar** [comment]
@codeRSH no timeline, this is the issue tracking why canvas/webgl don't fill the full width https://github.com/microsoft/vscode/issues/86425

**Comment by wmertens** [comment]
This would also be great for vs live sessions, most of the time the shared terminal ends up being 40x10 or something terrible like that.

**Comment by Sampath-Lokuge** [comment]
Yes, this is super annoying to brake the line even though it has a huge space to go. I have a 22-inch monitor and you can see that how many spaces on the right-hand side. I don't know why you cannot give to adjust this width to the user?

![vs](https://user-images.githubusercontent.com/5206526/88319969-89af8480-cd3a-11ea-9ebe-1d788114e7a8.png)

**Comment by CTownsdin** [comment]
I would like to see a button which toggles wrap on/off entirely.

When one is scrolling and skimming the terminal output, no wrap is nicer.

When one needs to see the output of a particular line, wrap becomes necessary.

A button or even just a keyboard shortcut to toggle line wraps in the integrated terminal on/off would be a nice feature.

**Comment by cstmgl** [comment]
> Yes, this is super annoying to brake the line even though it has a huge space to go. I have a 22-inch monitor and you can see that how many spaces on the right-hand side. I don't know why you cannot give to adjust this width to the user?
> 
> ![vs](https://user-images.githubusercontent.com/5206526/88319969-89af8480-cd3a-11ea-9ebe-1d788114e7a8.png)

just out of curiosity how do you get that? for me it does not go in the next line it goes back to the beginning and starts overwriting what I have there, incredibly annoying. I really would like to not have any wrap at all.

**Comment by Tyriar** [comment]
@cstmgl see https://github.com/microsoft/vscode/issues/106668

**Comment by ahmedhassan-eng** [comment]
+1: I'm outputting from PC Lint Plus and using the tasks' problem catcher with regex. This all breaks down when I get new lines inserted anywhere for no obvious reasons (other than it wraps based on terminal width pixel count).

**Comment by jwarkentin** [comment]
I'm trying to compare output lines for mistakes that could cause a problem and it's difficult when lines suddenly wrap at an arbitrary point in the middle of a word. Also, some lines I'm dealing with are rather long and quickly make the task impossible when a single line wraps enough times to consume my entire visible terminal space vertically. Additionally, with line wrapping it's not always clear when I'm dealing with a new line of output versus the continuation of a wrapped line, depending on the length of the lines and how they begin and end.

I can bail to an external terminal for now but that creates a lot of back-and-forth context switching that interrupts my flow.

**Comment by testforstephen** [comment]
This could benefit the debugger feature "Run in Terminal" too. 

See the issue https://github.com/microsoft/vscode/issues/100522, multiple extensions (such as JS, Dart, Java) are complaining that the startup command is very verbose, occupies multiple lines in the terminal and pollutes the program output.
<img alt="Screenshot 2020-07-09 at 13 30 06" width="1406" src="https://user-images.githubusercontent.com/1078012/87040286-64723080-c1e8-11ea-8fd4-f351375bde31.png">

![image](https://user-images.githubusercontent.com/14052197/104554019-8f957b00-5676-11eb-85cb-3fa374c3cf8e.png)

If it only renders the startup command in one line, that will mitigate the pain point. So allow disabling line wrapping in integrated terminal could make the terminal more clean.

**Comment by Tyriar** [comment]
@testforstephen but it would need to be switched to wrapped after anyway which would wrap the line, otherwise the whole terminal would act differently to other terminals.

**Comment by testforstephen** [comment]
> but it would need to be switched to wrapped after anyway which would wrap the line, otherwise the whole terminal would act differently to other terminals.

Is it possible to turn off wrap on a certain line and still have all other lines wrapped? If not, I would like to have a user setting to control the line wrap for all terminals.

**Comment by Tyriar** [comment]
@testforstephen this feature is about being able to control the dimensions of the terminal (and having a scroll bar), there definitely isn't ever going to be any mixed wrapping or line wrapping setting because that's not how terminals work.

**Comment by testforstephen** [comment]
I commented to this feature request because i saw multiple issues about "Disable line wrap in integrated terminal" were marked as duplicates with this one. Do you need us to reopen an issue about "Disable line wrap in integrated terminal" for more discussion there again?

**Comment by Tyriar** [comment]
@testforstephen disabling line wrap is not a feature we can support, the program running within the terminal controls that.

**Comment by i-schuetz** [comment]
I'm displaying ASCII tables, which break when there's not enough space.

**Comment by mew1033** [comment]
I just hit this as well. My terminal is huge, but it breaks and wraps at 80 characters, leaving 2/3 of the terminal area unused.

**Comment by dvianaVST** [comment]
> I just hit this as well. My terminal is huge, but it breaks and wraps at 80 characters, leaving 2/3 of the terminal area unused.



> > Yes, this is super annoying to brake the line even though it has a huge space to go. I have a 22-inch monitor and you can see that how many spaces on the right-hand side. I don't know why you cannot give to adjust this width to the user?
> > ![vs](https://user-images.githubusercontent.com/5206526/88319969-89af8480-cd3a-11ea-9ebe-1d788114e7a8.png)
> 
> just out of curiosity how do you get that? for me it does not go in the next line it goes back to the beginning and starts overwriting what I have there, incredibly annoying.
> it just seems that you managed to make it wrap into a new line but mine just wraps on top
> 
> ![image](https://user-images.githubusercontent.com/33542778/94237930-df0d3b00-ff0f-11ea-9eed-ed18177644a3.png)
> 
> I really would like to not have any wrap at all.

I have just run into the same problem "... it does not go in the next line it goes back to the beginning and starts overwriting what I have there, incredibly annoying...."  with the version 1.55.1 . Super annoying. Anyone knows how to solve this?

Thanks in advance ;)

**Comment by AriFordsham** [comment]
@Tyriar @testforstephen To clarify, doing anything complex with wrapping e.g. breaking lines on whitespace is (for our purposes) impossible. What **is** possible implementing a setting that sets the logical width of the terminal and a horizontal scrollbar to scroll this, so lines can extend beyond thew width of the visible terminal.

Is this correct?

Is there any interest/plan for implementing this?

**Comment by andrewmcdonald-oxb** [comment]
I'm also interested in this. We use GLog for output which emits quite a lot of boilerplate at the start of each entry (timestamp, thread ID, source file & line number). The source file in particular has a variable length, which makes the payload text in each output entry inconsistently indented. To help me parse quickly, I'd really like one line per output entry, with no wrapping. Being able to set a massive fixed output width and use a scrollbar would help enormously.

**Comment by Thatkookooguy** [comment]
I have the same issue when viewing test outputs when running jest in watch mode.
I don't want to see the coverage table wrapping up and looking all  broken.

With wrapping:

<img src="https://user-images.githubusercontent.com/10427304/116060058-2ddba880-a68a-11eb-945e-de8713866717.png" width="50%" />

without wrapping:

<img src="https://user-images.githubusercontent.com/10427304/116060280-68454580-a68a-11eb-86f6-29a1fadb6af2.png" width="50%" />

**Comment by Metadorius** [comment]
Just got hit by similiar issue. Newlines just break problem matching, producing (sometimes funny) error messages.
![image](https://user-images.githubusercontent.com/17500545/121900085-b3481480-cd2d-11eb-9f1f-fba076d44e0e.png)
![image](https://user-images.githubusercontent.com/17500545/121900120-bc38e600-cd2d-11eb-9ef9-a578fbdb2cb9.png)

**Comment by kMutagene** [comment]
This becomes an issue when looking at structured print output for data frames. it is important to be able to take a look at structured data while analyzing/transforming/visualizing it.

Here is a wide data frame print in F# via Deedle in comparison to a terminal that implements a horizontal scrollbar:

- VSCode: 
![image](https://user-images.githubusercontent.com/21338071/126959820-a87f36a7-e4dd-45da-a3c9-fa65e953dccc.png)

- Visual Studio:
![image](https://user-images.githubusercontent.com/21338071/126959954-03b1765c-8d86-4429-a35e-279682e57917.png)

removing wrap / setting a very large fixed with with a horizontal scrollbar would come a long way for data analysis in VSCode for me.

**Comment by jwarkentin** [comment]
A horizontal scrollbar would be awesome but even without that, if it's too technically complex for some reason, just having the option to have the terminal cut off lines rather than wrap them would go a very long way.

**Comment by ADTC** [comment]
I see that the **Debug Console** has an option to disable wrapping. Why not the **Output** and **Terminal** too?

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/3464

**Comment by andrewmcdonald-oxb** [comment]
Great, looking forward to seeing it in action!
