### ISSUE TITLE
Settings "python.autoComplete.extraPaths" support GLOB wildcard

### ISSUE THREAD

**Issue by r-bit-rry** [microsoft/vscode#74518]
We use a local eggs folder for each projects which stores all the dependencies for that project.
However when I specify the path to this eggs folder, autocomplete does not recognize the underlying packages folders (unless I specify each one manually).
This can be solved by GLOB pattern/wildcard support.

for example this is what I specify that works:
`"python.autoComplete.extraPaths": [
    "${workspaceFolder}/src",
    "${workspaceFolder}/eggs/pycparser-2.19-py2.7.egg",
    "${workspaceFolder}/eggs/asn1crypto-0.24.0-py2.7.egg",
    "${workspaceFolder}/eggs/ipaddress-1.0.22-py2.7.egg"]
`
And this doesn't work:
`"python.autoComplete.extraPaths": [
    "${workspaceFolder}/src",
    "${workspaceFolder}/eggs"]
`

**Comment by kieferrm** [comment]
@r-bit-rry pls move the issue to the Python extension https://github.com/Microsoft/vscode-python/issues. Thanks!
