### ISSUE TITLE
problems all ftp extentions in version vscode 1.31 and highter

### ISSUE THREAD

**Issue by AndryWJ** [microsoft/vscode#74517]
- VSCode Version: 1.30
- OS Version: Win 10

Steps to Reproduce:

1. Install any ftp extension (ftp-kr, sftp ...)
2. Look at the improper operation of the extension, ftp-kr - endless download to the server, sftp - meddirovannaya work 30 seconds to download any file even 1k

https://github.com/microsoft/vscode/issues/68401
This is not an extension problem, I have not found one working normally with ftp for versions 1.31 and higher.

I'm still on version 1.30 waiting for a solution.
version 1.34 still has problems.
I would be very grateful if you pay attention to this.

**Comment by gjsjohnmurray** [comment]
I have used the ftp capabilities of **Remote FS** without problems on 1.34.

Have you logged your problems with the extension providers?

**Comment by AndryWJ** [comment]
> I have used the ftp capabilities of **Remote FS** without problems on 1.34.
> 
> Have you logged your problems with the extension providers?

Remote FS did not try, thanks. here is an developer comment sftp: https://github.com/liximomo/vscode-sftp/issues/454#issuecomment-490817602

problem ftp-kr: 
https://github.com/karikera/ftp-kr/issues/119

**Comment by AndryWJ** [comment]
Remote FS - I do not see the possibility of synchronization, only direct work with a remote server

**Comment by gjsjohnmurray** [comment]
@AndryWJ yes, Remote FS is a different beast. It implements a `FileSystemProvider`.

I think your best hope is that @liximomo or the creator of one of the other extensions apparently impacted by a change at 1.31 will manage to track down the cause, then raise it here.

**Comment by AndryWJ** [comment]
This problem has not been solved for a long time. =(
What causes most ftp extensions in version 1.31 and above to crash? maybe vscode developers have an answer?

**Comment by kieliszek85** [comment]
I found out that this issue is related to host's FTP server.
For example pure-ftpd works ok, but pro-ftpd works very slowly.
I have checked vscode-sftp and vs-deploy. It seems to be related to FTP server's configuration, but I am unable to figure out which FTP option causes this issue.

**Comment by Balya** [comment]
Same problem with vscode-sftp plugin: https://github.com/liximomo/vscode-sftp/issues/454#issuecomment-488815897
Forced to use the old version of VSCode.

**Comment by kieferrm** [comment]
There is nothing we can do here if we don't have more detailed information about what's wrong in our code. So far, it still seems that what you describe are extension issues.

**Comment by kieliszek85** [comment]
@kieferrm It affects every extension and it is related to FTP configuration. This issue does not occur with vscode before 1.31

**Comment by AndryWJ** [comment]
vscode 1.35 — Problem solved
