### ISSUE TITLE
terminal.integrated.lineHeight has no effect

### ISSUE THREAD

**Issue by tomByrer** [microsoft/vscode#74513]
Issue Type: <b>Bug</b>

Win10 Home, bash (WSL I assume), font: Fira Code
"editor.lineHeight": 0
"terminal.integrated.lineHeight": 0.5

In editor view, line vertical spacing is by default snug; the way I like.  In Terminal, seems lineHeight is 1.5, with large spacing, despite my setting.  (Restarted terminal in New Window).

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.91GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
google-search-ext|ade|0.2.1
vscode-toggle-quotes|Bri|0.3.2
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.8.1
svg|joc|0.1.4
vscode-github|Kni|0.30.2
rainbow-csv|mec|1.1.1
indent-rainbow|ode|7.4.0
vscode-versionlens|pfl|0.23.0
partial-diff|ryu|1.4.0
es-quotes|vil|0.2.6
glean|wix|4.11.0

(6 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
1 is the minimum line height for the terminal by design, it uses a pretty different system to the editor.
