### ISSUE TITLE
Forcing `setBreakpoints` request on sources change

### ISSUE THREAD

**Issue by awto** [microsoft/vscode#74516]
I now work on JavaScript debugger plugin based on code instrumentation, this should allow time traveling and hot reloading during a debugging session.

I reload modules using Hot Module Replacement keeping all the state from the former version. This works except if I add a new line into a source all breakpoints become unverified, which is obviously right since their position is changed. Toggling one them sends `setBreakpoints` for the whole module and they are back verified and functioning. 

I can workaround this using 'breakpoint' event, however, the back-end doesn't know its new correct position, resetting it to the former line looks pretty random.

Is there is some way to force resending `setBreakpoints` for a changed module?  Or can the client send it on, say, `loadedSource` event?

**Comment by isidorn** [comment]
Currently we send the `setBreakpoints` request when the user has manually changed breakpoints in some way (by adding them, disabling/enabling them...).
When the `initiazlied` event arrives. When the file with breakpoints got deleted.
Currently the client does not send them for the `loadedSource` event and there is no way to force the cliend to send the `setBreakpoints` request programatically.
Thus leaving this open as a feature request.

**Comment by awto** [comment]
@isidorn would you accept a PR if I do this?

**Comment by isidorn** [comment]
@awto not at the moment. Since this feature is not requested and we did not plan to have it yet.
Maybe in the future we might reconsider. Thanks

**Comment by awto** [comment]
@isidorn do you mean the code hot swapping feature isn't requested? Many debuggers has it and it is actually great. In fact this issue looks more like a bug to me not a feature, why do you need loadedSources event after all. 

But ok, for now I'm going to hack this by toggling some breakpoint twice via debugger service, my adapter runs in the same process. If there is some other better way to convey the new breakpoint positions, I would be happy to know. 

Thanks.

**Comment by isidorn** [comment]
@awto there is currenly no feature reqeust for code how swapping as far as I know. Though feel free to open a new feature request.
Thanks

**Comment by awto** [comment]
@isidorn I work now on a JS debugger which supports hot swapping among a few other nice things, and the hot swapping does already work there. Except all the breakpoints are deactivated, untill I toggle one of them (so "setBreakpoints" is sent again).

I'm not sure if such feature request really belongs here, as this is a feature of an adapter (and debuggee). From the vscode side every feature needed is already there, except this small issue - no way to update breakpoints position. Which I would guess should be a part of loadedSources response, so I wouldn't call this issue a feature at all.

I can workaround this (if my adapter runs in the same process), but the purposes of loadedSources event isn't clear though.

**Comment by isidorn** [comment]
Why dont you just send a [`breakpoint event`](https://github.com/Microsoft/vscode/blob/3b473663d99e2b951bac456a6cb5b2d3fb786c2c/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L220) and update all the breakpoints that you want?
How do the breakpoint get deactivated? Do they say `Unverified breakpoint. File is modified, please restart debug session` on hover or something else?

**Comment by awto** [comment]
> Why dont you just send a breakpoint event and update all the breakpoints that you want?

I can, and I tried this, but since on adapter and debuggee sides I don't know the new breakpoint positions, if someone, say, adds a line into text. So I tried to resend the same positions I know from the last `setBreakpoints`, this sets their possition on a quite random looking line.

> Do they say Unverified breakpoint. File is modified, please restart debug session on hover or something else?

yes, this message, and when I toggle one of them everything is back to normal, since the setBreakpoints request is resent.

**Comment by awto** [comment]
@isidorn I've just checked the recent version and IDE does send now `setBreakpoints` on source file changed. This is not on `loadedSource` event though, but it is pretty enough for me. I don't know, maybe this didn't work the same on May, or it is just me. Thanks a lot!

**Comment by isidorn** [comment]
Welcome. I have been doing some refactoring in that area and seems like I fixed it hooray.
