### ISSUE TITLE
Octicons: need a "Info" icon that has full background

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74510]
Just tracking as bug here that the adoption of the tasks status item needs the previous info icon we had that has full white background.

@misolori that actually makes me wonder if we should revisit some of the octicons that are partially transparent? E.g. in general I think they do not look very good in our status bar, for example:

![image](https://user-images.githubusercontent.com/900690/58531670-71e67a00-81e3-11e9-85b7-d53fb2e3524e.png)

![image](https://user-images.githubusercontent.com/900690/58531674-7874f180-81e3-11e9-999b-9271b4a0a49e.png)

Instead of adding new icons we could simply fix those that are not fully with a background.

**Comment by misolori** [comment]
We could do that, however one thing to consider is other extensions (like LiveShare) use certain icons in their custom viewlet (like the sharing & people icons). We’d just need to be sure to communicate that with them as they use those same icons in VS (I believe). 

At the minimum we could replace the info and smile icons. Planning on pushing those changes tomorrow.

**Comment by bpasero** [comment]
Yeah good point, these icons are used in different contexts (even quick pick). Alternatively, we could:
* identify the icons that do not fully have a background
* introduce variants that have a full background
* rewrite any octicon in the statusbar to use that variant to enforce a consistent look down there
* do not change the look in other places

I guess this depends on how much such a change would break existing UX. We should maybe do an experiment how a solid-background icon looks like in quick pick and custom views compared to the current ones and then decide.

**Comment by DanTup** [comment]
I just noticed in Insiders this info icon looks weird. I don't know if it falls under this issue (which talks about the BG), but it seems to be too close to the number to its left, and also seems larger than the others.

![info](https://user-images.githubusercontent.com/1078012/58539303-f4286b80-81ee-11e9-8b5d-62a7a7a7616b.png)

**Comment by bpasero** [comment]
@DanTup yeah thanks for posting the screenshot, this issue is about fixing exactly that. The margins should be equal to make this look good.
