### ISSUE TITLE
Command palette: `remote container` yields incomplete results

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#74523]
Testing https://github.com/microsoft/vscode-remote-release/issues/474

When searching for `remote container`:

![image](https://user-images.githubusercontent.com/22350/58547007-d961f100-8206-11e9-9a0a-5c3aacd88074.png)

When search for `remote-container`:

![image](https://user-images.githubusercontent.com/22350/58547019-e088ff00-8206-11e9-91d7-6c8d7ca324ca.png)

Possible fixes:

- Make quick open jump over the `-` when searching
- Change the category of that extension to `Remote Containers`

**Comment by bpasero** [comment]
Moving to @roblourens given prior art in https://github.com/microsoft/vscode/issues/27636

**Comment by joaomoreno** [comment]
@bpasero @chrmarti Why not removing that `-`?

**Comment by bpasero** [comment]
Yeah I thought this would already happen via https://github.com/microsoft/vscode/commit/9d64a3be869c8fee828455339f3e15c1715166c6

**Comment by roblourens** [comment]
Uh, weird I'll have to debug

**Comment by roblourens** [comment]
Even though `-` is considered a word separator, the logic here wants to match each character in the query with an exactly matching character in the target:

https://github.com/microsoft/vscode/blob/9be296470a4cfe73590086ab064c9d11bfcc0e0a/src/vs/base/common/filters.ts#L301

Does it make sense to replace 

```
else if (word[i] !== target[j]) {
    return null;
}
```

with a check that allows both characters to be whitespace/word separators, even if they are not the same character? Then it will pass when `word[i] === ' '` and `target[j] === '-'`.

**Comment by bpasero** [comment]
Sorry, I am a bit lost. If `-` is considered a word separator, how does "remote container" not match "remote-container"?

**Comment by roblourens** [comment]
As I understand it, we are trying to match every character in the query with some exact same character in the target. We just use word separators to try to match against the next word if we didn't match something in the current word, because we try to start matching at the beginnings of words.

**Comment by roblourens** [comment]
So my proposal is to extend this

> we are trying to match every character in the query with some exact same character in the target.

to say that a word separator can match any word separator.

**Comment by bpasero** [comment]
Yeah I think that makes sense, that would mean "Remote-Containers" would match "Remote+Containers"?

**Comment by roblourens** [comment]
Yes

**Comment by roblourens** [comment]
Is it annoying that the `:` is now highlighted in this case?

![image](https://user-images.githubusercontent.com/323878/60408028-055bf380-9b72-11e9-8cd0-3a674ab0c399.png)

If ` ` can now match `:` then the colon is found first and becomes part of the match.

Not really clear how to avoid it. We could look ahead to detect this specific case. If the current query character is a ` ` and the target character is a non-whitespace word separator like `:`, but it is followed by a ` `, then we ignore the `:` and skip ahead to the ` `.

It would get odd if the query has multiple whitespace/word-separator characters in it. For example the query 

```
a  b
```

(with two spaces) would not match `a: b`. I don't think that's a problem. Any other ideas?

**Comment by bpasero** [comment]
I do not think this is too bad.

**Comment by roblourens** [comment]
Ok I will go with the simple fix for now
