### ISSUE TITLE
[C#] "this" will autocomplete as "ThreadStaticAttribute" when writing ternary expressions before ending semi-colon has been added

### ISSUE THREAD

**Issue by divillysausages** [microsoft/vscode#74520]
Issue Type: <b>Bug</b>

It happens mostly when writing ternary expressions (e.g. `(condition) ? doThis() : orThat()`) or when using `()` brackets in an assignment, _but before the ending semi-colon has been added._

When it happens, auto-complete doesn't seem to recognise that `this` exists, but will only show something like `ThreadStaticAttribute` (if there's a `using System;` directive at the top of the file) or `ThreadPriority`;

This is a default Unity project using VSCode, but it might be possible to reproduce in a pure C# environment.

Steps to reproduce:

- Create a MonoBehaviour such as:

```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MyBehaviour : MonoBehaviour {
	// Use this for initialization
	void Start () {
	}
}
```

- Inside the `Start()` method, start to write a ternary expression using `this` in the condition:

```
int foo = (this) // proposes "ThreadStaticAttribute"
```

- Instead of auto-completing the `this`, VSCode will only propose `ThreadStaticAttribute`. It will also automatically replace `this` with `ThreadStaticAttribute` if you hit Space or Tab, so you need to explicitly hit Esc before moving on
- Writing the ternary with the `;` already added (not the default behaviour) will properly offer `this` as an option:

```
int foo = (this); // autocompletes
```

- Writing without the brackets will also properly offer `this` as an option:

```
int foo = this // autocompletes
```

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (19.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.19.1
LiveServer|rit|5.6.1
unity-debug|Uni|2.7.2

</details>

**Comment by kieferrm** [comment]
@divillysausages thanks for the detailed issue. Can you please move the issue over to https://github.com/OmniSharp/omnisharp-vscode/issues? Thanks!
