### ISSUE TITLE
Breakpoints no longer hit in activate() method when debugging extension (possibly since webpack?)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74525]
Today I noticed that breakpoints aren't working in the activate method of my extension if they are in early-running code (though they work fine in code that runs "later").

For example in this code I added tow breakpoints, but only the second one (shown here) was hit:

<img width="720" alt="Screenshot 2019-05-29 at 10 54 43 am" src="https://user-images.githubusercontent.com/1078012/58547986-589ff680-8200-11e9-9266-936ab89a4345.png">

I don't know if it's started happening since I started using webpack and I can't reproduce it in the webpack-sample extension, so I need some pointers on how to track down what's wrong. I have seen this in the past, but it was fixed (https://github.com/microsoft/vscode/issues/23730).

**Comment by weinand** [comment]
There seems to be a timing issue: when setting breakpoints in startup/activation code, the code has been already executed before the breakpoints are registered properly.

In theory that should never happen because we are always using the "--inspect-brk" option which stops the debugger on entry and gives us time to registering breakpoints properly.

I need to do some deeper investigation why this strategy doesn't work anymore.

**Comment by DanTup** [comment]
Ok, let me know if you need any more info from me. I'm actually seeing other weird issues (presumably webpack related), like making code changes and clicking the Restart icon does reload the extension in the host, but breakpoints and source maps seem to get messed up, and sometimes it seems like it's still running old code (even though the disk seems correct, and I saw webpack do the recompile). I'll file separate issues about this after I try to make a small repro though.

**Comment by weinand** [comment]
The "breakpoint not hit in activation issue" is unrelated to Webpack. I can reproduce in an extension that doesn't use Webpack.

**Comment by DanTup** [comment]
Ah, great! I couldn't repro in a small sample so wasn't sure what was causing it.

**Comment by weinand** [comment]
@roblourens I've investigated this and here are my findings:

I can reproduce this problem on my (fast) MacBook Pro but not on Windows or Linux (both running in Parallel VMs). @isidorn is not able to reproduce on a slightly slower MacBook Pro. So most likely this is a timing issue.

Here is the reproducible setup:
- create "Hello World" extension
- set breakpoints in line 12 on the "console.log" call and line 21 on the "showInformationMessage" call.
- press F5
- in the new window press F1, type "Hello" and execute "Hello World" command

Observe:
breakpoint is not hit but "Hello World" notification appears.

Here is the resulting trace (without a stopped event):
[vscode-node-debug2.txt](https://github.com/microsoft/vscode/files/3252188/vscode-node-debug2.txt)

- press F1 and execute "Hello World" command again

Observe:
now the 2nd breakpoint is hit.

Here is the resulting trace (with a stopped event):
[vscode-node-debug2.txt](https://github.com/microsoft/vscode/files/3252196/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
Problem: `SourceMaps: expanded globs and found 0 scripts`

**Comment by roblourens** [comment]
But I can't repro: `SourceMaps: expanded globs and found 3 scripts`

**Comment by roblourens** [comment]
Can you check that `"outFiles":["/Users/weinand/MS/Projects/Scenarios/extensions/hello2/out/src/**/*.js"]` is correct?

**Comment by weinand** [comment]
@roblourens good catch! My "outFiles" was wrong.

**Comment by DanTup** [comment]
I'm confused :) How does outfiles being wrong cause one breakpoint not to be hit, but another to be in the same file? Is this likely what's up with mine? (I thought I'd fixed outfiles, because after I changed to webpack my debugging was completely broken.. now it all works, except for this).

**Comment by weinand** [comment]
"outfFles" is important for registering breakpoints in locations that haven't been loaded into the runtime. This is the case **before** the extension has been activated.
If the extension has been activated, "outfFles" is less important...

**Comment by DanTup** [comment]
Aha! I had messed with outfiles when setting up webpack, so it seems it was related. I just noticed I had missed `out` out of the path name 🤦‍♀️

Working fine now, sorry for the bother! :-)

**Comment by weinand** [comment]
Great to hear that this works now!
