### ISSUE TITLE
Issue with regex in files search

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#74522]
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Datum: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Go to Search for files and input "=>\n([\t ]+)array\(" as regex-option (you don't need search / press enter)
2. Go to Explorer (Icon in sidebar) and go back to search (Icon in sidebar)
or
2. Click on loupe icon again for _fullscreen_ and click again for show sidebar

Result:

Initial input was
`=>\n([\t ]+)array\(`
after step 2 its lock so:
`=>\\n\(\[\\t \]\+\)array\\\(`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
I tried unsuccessfully to reproduce this, but while doing do I logged #74527. Is it significant here that your regex is invalid?

Can you post an animated gif of what you're doing?

**Comment by Daijobou** [comment]
After restart vscode its gone. I report again with animated gif if I found a way to reproduce this again.
