### ISSUE TITLE
Go to file shortcut not working anymore

### ISSUE THREAD

**Issue by Tony-Truand** [microsoft/vscode#74521]
Issue Type: <b>Bug</b>

Desipte many restarts, erasing custom shortcuts (that weren't touching this one) The super handy shortcut Ctrl+P doesn't work any more, whereas the menu item is, but I'd like the keybord one to get back functioning

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.74GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-twig-pack|baj|1.0.0
vscode-eslint|dba|1.9.0
json-tools|eri|1.0.2
php-debug|fel|1.13.0
netbeans-keybindings|gro|0.0.4
ftp-simple|hum|0.7.0
sshextension|kon|0.5.0
vscode-apache|mrm|1.2.0
vscode-json5|mrm|1.0.0
vscode-language-pack-fr|MS-|1.34.2
python|ms-|2019.5.17059
vscode-mongodb|ms-|0.0.2
cpptools|ms-|0.23.1
node-debug2|ms-|1.33.0
debugger-for-chrome|msj|4.11.3
vscode-react-native|msj|0.9.3
nunjucks|ron|0.2.3
addDocComments|ste|0.0.8
python|tht|0.2.3
vscode-arduino|vsc|0.2.25

</details>

**Comment by alexandrudima** [comment]
@Tony-Truand Have you tried disabling all extensions?

Keybindings come from multiple sources:
- core keybindings
- built-in extensions
- user installed extensions
- user keybindings

If you have verified that the user keybindings are not touching `ctrl+p`, it would be good to also search for "ctrl+p" in the keybindings editor (ctrl+k ctrl+s) and check that no extension is binding it. You can also try to disable all extensions to see if the keybinding is freed up.

**Comment by Tony-Truand** [comment]
Thanks for the hint, I've reboot and haven't heard for this bug since.

Le mar. 30 juil. 2019 à 09:45, Alexandru Dima <notifications@github.com> a
écrit :
