### ISSUE TITLE
Enabling Regular Expression mode on Search while field contains invalid regex gives endless "busy" indication

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#74527]
Issue Type: <b>Bug</b>

1. On Search sidebar with 'Use Regular Expression' option **not selected** paste `=>\n([\t ]+)array(`
2. Select 'Use Regular Expression' option and observe animated horizontal indicator run perpetually. The Stop button above it has no effect.
3. Deselect RE option and blank out the search field.
4. Select  RE option and then paste `=>\n([\t ]+)array(` into the search field. You are correctly warned that the regex is invalid.

Presumably it is the invalidity of the regex that causes the progress indicator logic to malfunction in step 2.  We should probably get the invalid regex message when enabling RE option while field contains bad regex.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-3420M APU with Radeon(tm) HD Graphics (4 x 1497)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.47GB (0.89GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
thefoldingstuff|geo|0.1.0
vscode-serenji|geo|3.0.3
guides|spy|0.9.3
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by gjsjohnmurray** [comment]
No longer able to recreate this on latest Insiders.

Version: 1.38.0-insider (user setup)
Commit: ba69d8dcccaebbfaa94906503728eb7c3e45b9c1
Date: 2019-08-14T07:18:43.039Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
I think I fixed this in another issue. Sorry I missed this one somehow.
