### ISSUE TITLE
Error list explodes in a vscode extension development environment

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7452]
It's linting all of the downloaded VSCode-linux-x64 folder, .vscode-test should be ignored.

![image](https://cloud.githubusercontent.com/assets/2193314/15920309/aabb9292-2dcd-11e6-8725-a4f5e3b132bb.png)

**Comment by sandy081** [comment]
Duplicating with 7457 as at the end they are similar - ignoring files

duplicates #7457

**Comment by sandy081** [comment]
Reopening this as #7457 is a different

**Comment by sandy081** [comment]
@Tyriar I would like to reproduce this and see where and how these errors are generated from.. Can you please provide steps how you got this?

Thanks

**Comment by Tyriar** [comment]
@sandy081 try clone Tyriar/vscode-xml, run npm install, npm test and then open declares.d.ts

**Comment by sandy081** [comment]
@Tyriar Typescript compiler is compiling all folders except node modules folder.. After updating tsconfig everything looks good

{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "outDir": "out",
    "noLib": true,
    "sourceMap": true,
    "rootDir": "."
  },
  "exclude": [
    "node_modules",
    ".vscode-test"
  ]
}

**Comment by Tyriar** [comment]
Created https://github.com/Microsoft/vscode-generator-code/issues/42 to fix the problem at the yeoman generator then. Thanks.
