### ISSUE TITLE
Electron 4: Shift + click on open VS Code in task bar doesn't open a new window.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#74536]
Found testing https://github.com/microsoft/vscode/issues/74320

In Windows, when you Shift+click on a running item in the task bar it opens a new window of that item.

**Comment by bpasero** [comment]
@alexr00 I cannot reproduce on my Windows 10 box, but this used to be an area of issues. Both things work for me:
* shift-click
* middle mouse click

Do you have Code exploration pinned to the Windows dock?

Ping @the-ress as we had https://github.com/microsoft/vscode/pull/15407 which I think is related. 

//cc @deepak1556

**Comment by alexr00** [comment]
Code exploration is not pinned. Code exploration and insiders were both running (1 window each). Windows version 10.0.18362 Build 18362, aka 1903.

I used the 64 bit Windows archive to install the exploration. 

Version: 1.35.0-exploration
Commit: a2873dc8ba39ecacd83de7c8e431e5f5a3107d86
Date: 2019-05-29T05:57:26.707Z
Electron: 4.2.2
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@alexr00 oh this may not work with just the archive, can you try with using the installer?

**Comment by alexr00** [comment]
Works with installer!

**Comment by alexr00** [comment]
Shouldn't it also work with the archive?

**Comment by bpasero** [comment]
@alexr00 I believe this feature is tied to being installed and having an entry in the windows registry, not sure why.
