### ISSUE TITLE
[vscode-uri] breaking change landed in a patch release

### ISSUE THREAD

**Issue by web-padawan** [microsoft/vscode#74533]
Hi everyone. Not sure where should I ask about [vscode-uri](https://github.com/microsoft/vscode-uri) (the repo does not have open issue tracker) so asking here. If it's not a proper place, please forward me to the right direction .

Problem is that `vscode-uri` has been recently bumped to `1.0.7` and included breaking changes in a patch release.  See the commit: https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634

In particular, default export has been removed and changed to named export.
As a result, the following code (which is still [listed in README](https://github.com/microsoft/vscode-uri#usage)) no longer works:

```js
import Uri from 'vscode-uri';

// create an Uri from a fs path

let uri = Uri.file('/users/me/c#-projects/');
```

The missing default export result in following error:

```console
TypeError: Cannot read property 'file' of undefined
```

This breaks semver, and should have been released as `2.0` instead.
Could you revert that change, bump `1.0.8` and then do a major bump properly?

**Comment by jrieken** [comment]
ops - that unintentional. I will push a fix asap

**Comment by jrieken** [comment]
published as 1.0.8

**Comment by jrieken** [comment]
also published 2.0.0 without the default export

**Comment by web-padawan** [comment]
That was fast! Thanks 👍

**Comment by jrieken** [comment]
Thanks you for the quick error report
