### ISSUE TITLE
vscode-dts causing compile errors due to downloading vscode.d.ts into root of folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74534]
Refs: https://github.com/microsoft/vscode/issues/74436

Steps:
* be on Windows
* yo code a hello world TS extension
* open in VSCode
* run it once from debug, should work fine
* run `npx vscode-dts release/1.32`
* run it again from debug

=> 🐛 I am seeing a lot of errors:

![image](https://user-images.githubusercontent.com/900690/58551689-ec79be80-8210-11e9-8b0b-bfc6590996f1.png)

It looks like the npx command results in `vscode.d.ts` downloaded into the root of the project, is that correct?

![image](https://user-images.githubusercontent.com/900690/58551782-2d71d300-8211-11e9-8231-e1deb9c184fd.png)

**Comment by bpasero** [comment]
Btw cc @joaomoreno @sandy081 for broken tree

**Comment by octref** [comment]
I think that's as-designed. Do you think we should add correct `@types/vscode` dependency instead of downloading raw dts in this case? I thought vscode-dts as an alternative to `@types/vscode`, not something on top of it.

**Comment by bpasero** [comment]
@octref I see 2 usecases:
* to download from master
* to download proposed

Either way, the vscode.d.ts should go into the types folder otherwise we can end up having vscode.d.ts twice (once top level and once in node modules folder)

**Comment by octref** [comment]
OK, here's the plan:

- I'll limit `vscode-dts` to only downloading master / proposed.
- I'll print a warning if `node_modules/@types/vscode` is detected when downloading master dts. The old behavior of downloading file into `node_modules/vscode` had been confusing, and if you reinstall dependencies the types are gone again.

**Comment by bpasero** [comment]
@octref I actually suggest to print the warning but also just remove the folder `node_modules/@types/vscode` as part of the operation.

**Comment by octref** [comment]
Made a small CLI prompt and released in 0.2.0.

![prompt](https://user-images.githubusercontent.com/4033249/60120441-a3e0f280-9735-11e9-9c3b-2c58e96cf241.gif)
