### ISSUE TITLE
Precondition in comments/commentThread/context doesn't seem to work

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#74541]
Testing https://github.com/microsoft/vscode/issues/74472

I added the following command to the comments/commentThread/context:

```				{
					"command": "mywiki.createDocument",
					"group": "inline",
					"precondition": "commentIsEmpty",
					"when": "commentThreadIsEmpty"
				}
```

However the command is not disabled (visually) when the comment changes from empty to non empty

**Comment by RMacfarlane** [comment]
"precondition" was renamed to "enablement", updated the sample
