### ISSUE TITLE
It is unclear what valid values are for contextValue

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#74542]
Testing https://github.com/microsoft/vscode/issues/74472

It looks like from reading the doc that `editable` is a valid value. However there is no indication if this is the only valid value. And if not which the other values are.

**Comment by dbaeumer** [comment]
Actually now I found out how this works: user can have their own sets of `contextValues`. I would suggest to make this more clear in the JS doc by including the JS/TS code that actually set the value. Otherwise users might think (like I did) that `editable` is a given value.

**Comment by RMacfarlane** [comment]
Closing as `vscode.d.ts` already includes a JS doc comment with an example usage
