### ISSUE TITLE
Smart select on `|"non-empty-string"` selects entire file

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#74549]
[...]
Also, running smart select on `|"non-empty-string"` results in the entire file being selected and the following error:

```
ERR INVALID selection range, must contain the previous range: Error: INVALID selection range, must contain the previous range
	at define.provideSelectionRanges.a.asPromise.then.e (/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:585:31)
```

_Originally posted by @diabolicle in https://github.com/microsoft/vscode/issues/74309#issuecomment-495870586_

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/31657
