### ISSUE TITLE
Wrong editor content or header

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#74548]
![capture](https://user-images.githubusercontent.com/1931590/58556597-afb3c480-821c-11e9-802a-735316aa6293.png)
Happened when testing https://github.com/microsoft/vscode/issues/74466

See the attached screen shot: The header talks about protocol.ts but the content is clearly the setting.json file which I had open. I did move files around using D&D

**Comment by jrieken** [comment]
errors on the console?

**Comment by bpasero** [comment]
@dbaeumer not good, any chance you can distill some steps how to reproduce this?

**Comment by dbaeumer** [comment]
Yes, I do have `"workbench.editor.revealIfOpen": true`. Will try to get some repro steps today.

**Comment by dbaeumer** [comment]
I got it again. Here is the screen shot

and here the console

**Comment by dbaeumer** [comment]
Will try to destill steps

**Comment by dbaeumer** [comment]
Here are some steps:

- clone https://github.com/Microsoft/vscode-languageserver-node.git
- open workspace
- I have no tabs
- open settings.json
- open protocol.ts
- open settings.json to the side
- open protocol.callHiararchy.proposed.ts (same column as the settings.json)
- bring setting settings to front in the second column
- d&d the second column onto the first

You get:

**Comment by bpasero** [comment]
@dbaeumer phew, thanks for finding this. A regression from async/await where I probably either had too many coffee or not enough...
