### ISSUE TITLE
Monaco API request : allow html content renderer to accept raw innerHtml

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#7454]
This file : https://github.com/Microsoft/vscode/blob/5cd6e6edb3e027b8ade2d888d4e457b2256d50fd/src/vs/base/browser/htmlContentRenderer.ts

E.g. it is used in information on hover. For [alm.tools](http://alm.tools/) I have my own `toHtml` function: https://github.com/alm-tools/alm/blob/5fef6d6b0f52ae08b52cea23241ed2d5f56d7236/src/app/markdown/markdown.tsx#L31-L44 (its worked for me `¯\_(ツ)_/¯`) that I'd like to continue to use. 

If you want feel free to call it `dangerouslySetInnerHtml` (https://facebook.github.io/react/tips/dangerously-set-inner-html.html). Would help with the migration https://github.com/alm-tools/alm/pull/121 :rose:

### More reasons 
*PS the built in `markdown` support in the standalone editor doesn't work*

Exhibit : 

my code 
![image](https://cloud.githubusercontent.com/assets/874898/15921045/025c01d2-2e62-11e6-8199-d00c3e96b82f.png)
usage: 
![image](https://cloud.githubusercontent.com/assets/874898/15921072/292fcb18-2e62-11e6-9649-ac8d6798c0a5.png)
I get the stars: 
![image](https://cloud.githubusercontent.com/assets/874898/15921076/2eb6221c-2e62-11e6-94e9-f8b1143967ea.png)

*I really like github style code blocks* 

![image](https://cloud.githubusercontent.com/assets/874898/15921110/70ce0732-2e62-11e6-9716-97593c299651.png)

**Comment by basarat** [comment]
I see the latest api allows raw markdown so that does what ever I wanted to use the innerHTML for. So closing :rose:

**Comment by alexandrudima** [comment]
fyi @aeschli - thanks for the marked string!
