### ISSUE TITLE
Add support of Task Lists to Markdown editor/preview.

### ISSUE THREAD

**Issue by yatagarasu25** [microsoft/vscode#74540]
Issue Type: <b>Feature Request</b>

Please add support of Task Lists to Markdown preview

Like they do that in github
https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

Just displaying checkboxes will be ok.
Can be usefull for editiong local todo lists.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Just use this extension https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
