### ISSUE TITLE
Monaco Hover API : trims text leaving dangling `:`

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#7455]
Sample : 

![image](https://cloud.githubusercontent.com/assets/874898/15921170/f1da1460-2e62-11e6-86e5-f96b0e1f44c2.png)

I sent it the complete `name` (i.e. `(parameter) props: AvatarProps`) but it trimmed out the type name leaving a dangling `:` at the end. 

I'd rather it not eat anything ever, even in this case: 

![image](https://cloud.githubusercontent.com/assets/874898/15921211/49e02a0a-2e63-11e6-860a-0eabcaac187c.png)

Again thanks for making it all OSS my journey continues https://github.com/alm-tools/alm/pull/121 :rose:

**Comment by basarat** [comment]
A more significant problem when the type is inferred 

![image](https://cloud.githubusercontent.com/assets/874898/15921428/c06ae8da-2e64-11e6-93e3-30be443dd9f5.png)

**Comment by alexandrudima** [comment]
Looks like the hover is wrapping the last word

**Comment by basarat** [comment]
> Looks like the hover is wrapping the last word

I fixed it locally by just adding to the calculations that `hoverWidget` makes :rose:
