### ISSUE TITLE
runTests.d.ts spec not consistent with code

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#74555]
Testing https://github.com/microsoft/vscode/issues/74436

- create a TS extension as described in #74436 and look at runTest.ts
'runTests' is called with testRunnerPath.
The hover of `testRunnerPath` says:
```ts
    /**
     * Absolute path to the test suite folder. Must include an `index.js` that
     * exports a test runner, such as:
     *
     * ```ts
     * import * as testRunner from 'vscode/lib/testrunner';
     * module.exports = testRunner;
     * ```
     */
```

Looking at [suite/index.ts](https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/src/test/suite/index.ts) I don't see a testRunner exported.

**Comment by aeschli** [comment]
Ok, thanks.
But now my question is about
 `run(testsRoot: string, cb: (error: any, failures?: number) => void)` 

What is the `testsRoot`? How does the user define it? Is it necessary?

Why do we use the `cb` style. Our APIs typically use Promises...

**Comment by aeschli** [comment]
So the testRunner is the module name passed to `--extensionTestsPath`.

Did we change the contract? Before it had to export a test runner, now it is a export with run?

**Comment by octref** [comment]
We didn't. That's what the old test runner does: https://github.com/microsoft/vscode-extension-vscode/blob/master/lib/testrunner.ts.

We use the old API since we don't want to break backwards compat. I'd suggest we come up with a better API (see my comment here: https://github.com/microsoft/vscode-extension-samples/pull/186), but it has to be a different name, such as `runTest`. 

Here's the relevant code: https://github.com/microsoft/vscode/blob/ac6237c706ff8803cc0ce34e8b7a1d62fa285754/src/vs/workbench/api/node/extHostExtensionService.ts#L521-L560.

**Comment by octref** [comment]
I don't really like us having to have this API, but for people who are still importing from `vscode/lib/testrunner`, if they don't migrate we don't want to break them.

**Comment by octref** [comment]
Actually, for people who have been importing from `vscode/lib/testrunner`, they haven't used the `run` signature directly. So if we do add a better signature with a different name such as `runTest`, we might not need to expose `run`.

**Comment by octref** [comment]
The change is to add a new function signature for `run`:

```ts
interface ITestRunner {
	/** Old test runner API, as exported from `vscode/lib/testrunner` */
	run(testsRoot: string, clb: (error: Error, failures?: number) => void): void;
}

interface INewTestRunner {
	/** New test runner API, as explained in the extension test doc */
	run(): Promise<void>;
}
```

When the function returns a promise, wait for the promise, otherwise use the old logic.
