### ISSUE TITLE
Debug console should be cleared as soon as the new session starts

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode#74551]
- VSCode Version: 1.34.0
- OS Version: Windows 10, Ubuntu 18, macOS 10.14.4

Steps to Reproduce:

1. Install [Cordova Tools](https://marketplace.visualstudio.com/items?itemName=msjsdiag.cordova-tools) extension
1. Install Cordova cli `npm i -g cordova`
1. Clone demo app with `git clone https://github.com/SounD120/vscodecordovatoolsrepro.git` command
1. Run `cd vscodecordovatoolsrepro && npm install` command
1. Open app in VS Code with command `code .`
1. Run debug with `Run Browser` debug scenario once, wait until output appears in Debug Console, stop debugging, then run debug configuration again. Between starting debug configuration and attaching to app debug console won't be cleared.

This behaviour appeared since VS Code 1.29.0 and looks like this now:
![Cordova_Debug_Console_VSCode_1 34 0](https://user-images.githubusercontent.com/32372875/58556497-dbd34380-8224-11e9-994c-8b5906ed91dc.gif)

This is how it looked in VS Code 1.28.0:
![Cordova_Debug_Console_VSCode_1 28 0](https://user-images.githubusercontent.com/32372875/58556521-e4c41500-8224-11e9-8e5f-70a87ba5a6e6.gif)

As you can see, in 1.28 there were no such problems.

For writing the extension debug logs we use `sendEvent` function from `ChromeDebugSession` in which we send `OutputEvents`.

Since this behavior happened after the update, we are thinking that it might be connected with changes in VS Code core that processes debug adapter's debug sessions.
Could you please help us to find out what might cause this, because it may lead to the scenarios where there are some build errors in application, but debug console doesn't render error message and it is pretty hard to find out what is the core of the problem. Also, when debug output isn't cleared between debug runs it confuses users.

**Comment by isidorn** [comment]
Ok so let me get this clear. This only happens if you stop the debug session while it is initialising? If you stop it after some time, and start again the console will get properly cleared. Correct?

**Comment by SounD120** [comment]
@isidorn The problem is that the previous session's logs are not being cleared when we are running the new one until the new session is attached to the debuggee process. All the time it takes to attach (which may consist of application build, code bundling, etc) users can't see any changes in debug console until they click on the clear button themselves. In cases when there are build errors or other issues happened before attach, debug process will be simply interrupted without any error messages in debug console, because debug logs from the old debug session are still in there.

**Comment by isidorn** [comment]
@SounD120 got it. Renaming to make the issue more clear and assigning to June to fix then.

**Comment by isidorn** [comment]
I have pushed a fix for this.
Please try it out with Friday's vscode insiders since that one will contain the fix and let me know if it is better for you. If not I have other ideas, so please just try it out on Friday - thanks!

**Comment by SounD120** [comment]
Hi @isidorn . I have tested your fix on latest master VS Code build. Debug console works as expected now. Thanks!

**Comment by isidorn** [comment]
@SounD120 even better to try out from source. Thanks a lot!
Adding verified label.
