### ISSUE TITLE
comments/commentThread/actions and comments/comment/actions not fully supported

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74556]
Refs: https://github.com/microsoft/vscode/issues/74472

`comments/commentThread/actions` and `comments/comment/actions` seem to be new names for `comments/commentThread/context` and `comments/comment/context`. This is great, because the old name is not good - it is not a context menu and can be easily confused. 

However the new menu title id simply does not work, while the old one works. So it seems to not be fully supported yet. 
The json schema works with the new name `actions`. Great

Also when updating to the new name make sure to update the comment sample her https://github.com/microsoft/vscode-extension-samples/tree/048fa2f156090c43cbe56bc4e2788aa77c091a5d/comment-sample

![Screenshot 2019-05-29 at 15 39 51](https://user-images.githubusercontent.com/1926584/58561713-04a90800-8228-11e9-94bb-4da5c88e9bc4.png)

**Comment by RMacfarlane** [comment]
Fixed with 2185280ed5783338b418ecdb8f62c4a13a2b560b
