### ISSUE TITLE
Change all occurences and Command Palette is in every editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74558]
Refs: https://github.com/microsoft/vscode/issues/74472

Notice how the context menu in the comment input box is pretty useless. It has all the unrelated actions. And we have  similar problem in the debug console input box.

I belive the Change all occurences and the Command Palette belong only in the main editor and they should be removed from all others.
@bpasero @jrieken On what context keys do we contribute these commands. Can we fine tune them so they do not appear in every editor?

![Screenshot 2019-05-29 at 15 45 02](https://user-images.githubusercontent.com/1926584/58562353-5f8f2f00-8229-11e9-9aec-1f8c4d6d9c0d.png)

**Comment by bpasero** [comment]
Makes sense to not have them in there. I would think there should be a context key set whenever the editor is not used as a real text editor and then we can change those registrations.

**Comment by isidorn** [comment]
There should be a context keys for this. Every editor should have this property is simple widget something.
I can look into adding this context keys for the two actions.

**Comment by rebornix** [comment]
There is a context key `isInEmbeddedEditor` https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/editorContextKeys.ts#L31 but it's only used in Playground/Walkthrough. We should probably make better use of it.

**Comment by isidorn** [comment]
I can look into this this mielstone, thus assignign to October and removing other asignees.

**Comment by isidorn** [comment]
@rebornix please review the fix. I checked out how it beahves and it seems good

**Comment by rebornix** [comment]
Thanks, I’ll take a look.

**Comment by rebornix** [comment]
@isidorn not sure if I understand it incorrectly, restricting the command to `ContextKeyExpr.and(EditorContextKeys.writable, EditorContextKeys.editorTextFocus) ` doesn't filter it out from Comment Editor, right?

**Comment by isidorn** [comment]
I believe it does. Because the editorTextFocus is set only when the editor is not a simple widget. Check it out here https://github.com/Microsoft/vscode/blob/f554449e3baa6db81c04ed2c321c60ec3a8e9b9f/src/vs/editor/browser/widget/codeEditorWidget.ts#L1640

And I hope the comment editor is a simple editor widget like the repl input is. I set this here https://github.com/Microsoft/vscode/blob/f554449e3baa6db81c04ed2c321c60ec3a8e9b9f/src/vs/workbench/contrib/codeEditor/browser/simpleEditorOptions.ts#L43

**Comment by rebornix** [comment]
I did use the simple editor by following repl input but turned out that language features won't be enabled when doing so. But we may still want to do so otherwise it's polluting the extension API.

**Comment by rebornix** [comment]
@isidorn thanks, I changed it to simple editor and considering we only need suggestion / snippet, it should be fine.

**Comment by isidorn** [comment]
@rebornix great, thanks for doing that.
