### ISSUE TITLE
The order in which the terminal starts the conda environment during debugging

### ISSUE THREAD

**Issue by skywolf123** [microsoft/vscode#74557]
Issue Type: <b>Bug</b>

In the anaconda environment, press F5 to start debugging, but the error "DLL load failed" seems to be that the debugging terminal failed to start the conda environment at the first startup, but first executed the python code and then tried "conda activate base".

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.34.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.5.17059
vscode-yaml|red|0.4.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode-python
