### ISSUE TITLE
Test Runner: error when reading fake asar

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#74563]
Testing https://github.com/microsoft/vscode/issues/74436

Ubuntu

- open https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
- `npm install`, `npm run compile`, `npm test`

tests pass, but terminal prints:
```
Extension Test Suite
    ✓ Sample test
  1 passing (39ms)

Spawn Error: [0529/163955.968798:ERROR:archive.cc(167)] Failed to parse header size from /home/aeschli/workspaces/vscode-distro/extensions/css-language-features/server/test/pathCompletionFixtures/src/data/foo.asar

Exit code:   0
Done
```

foo.asar is a fake asar (for testing reasons).
Strange that the test runner would try to load it.

**Comment by octref** [comment]
I can't really repro this. How does your `runTest` look like?

**Comment by aeschli** [comment]
I still get that. The test runner is as in the example: https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample/src/test/runTest.ts

What happens is that the vscode instance is started without any workspace/folder and seems to use the my `vscode` source folder instead (probably because it's in the recent history).
I suspect it's the filewatcher that tries to read into the ASAR because it uses Electron as node.

**Comment by octref** [comment]
That's an error from vscode itself.

```
 vscode > ./scripts/code.sh 
[09:56:45] Syncronizing built-in extensions...
[09:56:45] You can manage built-in extensions with the --builtin flag
[09:56:45] [marketplace] ms-vscode.node-debug@1.35.3 ✔︎
[09:56:45] [marketplace] ms-vscode.node-debug2@1.33.0 ✔︎
[09:56:45] [marketplace] ms-vscode.references-view@0.0.27 ✔︎
[main 2019-06-25T16:56:45.672Z] update#ctor - updates are disabled as there is no update URL
[69483:0625/095647.901455:INFO:CONSOLE(219)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:///Users/octref/Code/work/vscode/out/vs/workbench/servic
es/extensions/electron-browser/extensionHost.js (219)
[69483:0625/095648.245662:INFO:CONSOLE(131)] "%c[Extension Host] %cdebugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws
=127.0.0.1:5870/2a9d842a-092c-4ac2-ba8f-90a4ee97fa79", source: file:///Users/octref/Code/work/vscode/out/vs/workbench/services/extensions/electron-browser/extensionHost.j
s (131)
[0625/095649.878275:ERROR:archive.cc(168)] Failed to parse header size from /Users/octref/Code/work/vscode/extensions/css-language-features/server/test/pathCompletionFixt
ures/src/data/foo.asar
```

To repro:

- Run `scripts/code.sh`
- Open vscode folder in OSS
- Open `foo.asar` in OSS
- Close OSS
- Run `scripts/code.sh` again

@aeschli Why did we add `foo.asar` for path completion fixture? Can't we use something like `foo.data`? I guess we can't blame vscode for opening an `.asar` file using electron's [archive loading](https://github.com/electron/electron/blob/ab5ec0af3331f8dd4f144af5cf62d387737261b2/shell/common/asar/archive.cc#L168).

**Comment by aeschli** [comment]
I'm pretty sure this comes from the watcher process when it stumbles over our fake asar file. As all the processes that we fork, this is an electron node process and as such it considers every `.asar` file as a folder.

If we wanted to fix it we could run the watcher process with `ELECTRON_NO_ASAR: 'true',` but then have to make sure that our builder doesn't put `chockidar` and `nsfw` in the asar archive.

@bpasero you decide

**Comment by bpasero** [comment]
@aeschli this is very likely coming from chokidar because that is the only watcher using node APIs for reading the file system. Why don't we simply hardcode `*.asar` to the list of ignored things?

**Comment by aeschli** [comment]
@bpasero Sounds good!

**Comment by bpasero** [comment]
@aeschli I cannot fix this unfortunately without setting process.noAsar which does not work because we use ASAR for module loading. Have to close this as wont fix, if you feel strong about it, I suggest you remove the broken ASAR from our sources (why do we actually have it after all?).
