### ISSUE TITLE
VS Code terminal highlighted prompt

### ISSUE THREAD

**Issue by githublloyd** [microsoft/vscode#74567]
Issue Type: <b>Bug</b>

After accepting the recent Windows 10 update, my VS Code editor terminal has changed colours and contrast. Any attempt at changing the Theme still has the command prompt highlight in these inverted/obnoxious colours (dirs, files are hard to see).

It happened just after updating my Windows 10 OS; That spec - Windows 10 Enterprise, Version 1809, Installed on 29/05/2019, OS Build 17763.529

My VS Code application spec - Version 1.34.0 (user setup), commit a622c65...ending in 5fe758

Image - https://i.stack.imgur.com/MUSqt.png

Thanks in advance!

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|mau|1.3.11
python|ms-|2019.5.17059

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What's you in your settings.json file?

**Comment by gusbemacbe** [comment]
Hi @Tyriar 

I also have this problem that @githublloyd has. Here is the GIF:

![bug-terminal](https://user-images.githubusercontent.com/2257024/58605143-36908d80-826d-11e9-92ef-74edcffe944f.gif)

* **VSCode Version:** 1.35.0-insider 6b081a9 x64
* **OS Version:** Arch Linux 64 bits Budgie

<details>
 <summary> Extensions </summary>

AndersEAndersen.html-class-suggestions
abusaidm.html-snippets
acarreiro.calculate
adamvoss.vscode-languagetool
adamvoss.vscode-languagetool-en
adamvoss.vscode-languagetool-nl
adamvoss.vscode-languagetool-pt
alexdima.copy-relative-path
anseki.vscode-color
arcticicestudio.nord-visual-studio-code
austin.code-gnu-global
ban.spellright
be5invis.vscode-custom-css
bibhasdn.django-html
bibhasdn.django-snippets
bierner.markdown-preview-github-styles
brapifra.phpserver
brunnerh.file-properties-viewer
dbaeumer.jshint
dbaeumer.vscode-eslint
dustinsanders.an-old-hope-theme-vscode
eiminsasete.apacheconf-snippets
Equinusocio.vsc-material-theme
felixfbecker.php-debug
felixfbecker.php-intellisense
felixfbecker.php-pack
gusbemacbe.sort-selection-comma
gusbemacbe.sort-selection-semicolon
HookyQR.beautify
idleberg.emoji-code
iseos.noname-ui
jakeboone02.cypher-query-language
James-Yu.latex-workshop
jchannon.csharpextensions
jock.svg
jsaulou.theme-by-language
junstyle.php-cs-fixer
karigari.chat
LeCrunchic.mariana-nord
lunarlimbo.banner-comments-plus
mrmlnc.vscode-apache
mrmlnc.vscode-attrs-sorter
mrmlnc.vscode-csscomb
mrmlnc.vscode-duplicate
MS-CEINTL.vscode-language-pack-en-GB
ms-python.python
ms-vscode.atom-keybindings
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.Go
ms-vscode.wordcount
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
naumovs.color-highlight
ohansemmanuel.css-grid-snippets
PKief.material-icon-theme
pranaygp.vscode-css-peek
raymondcamden.languagetool
rbalet.code-spell-checker-fullstack
redhat.vscode-xml
rickynormandeau.mariana-pro
ritwickdey.live-sass
ritwickdey.LiveServer
robinbentley.sass-indented
sidthesloth.svg-snippets
simonguo.vscode-markdown-table-sort
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-dutch
streetsidesoftware.code-spell-checker-portuguese
streetsidesoftware.code-spell-checker-portuguese-brazilian
vayan.haml
vincaslt.highlight-matching-tag
WakaTime.vscode-wakatime
wmaurer.change-case
yzhang.markdown-all-in-one
Zignd.html-css-class-completion

</details>

<details>
   <summary> <code>settings.json</code> </summary>

```json
// Artoo:               #4FB4D7;
// Death Star           #B6B18B;
// Luke:                #EF7C2A;
// Millennium Falcon    #A9B8BA;  
// Threepio:            #E5CD52;
// Vader:               #EB3D54;  
// Yoda:                #78BD65; 
{
    "[css]":
    {
        "editor.defaultFormatter": "mrmlnc.vscode-csscomb"
    },
    "[html]": 
    {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[javascript]":
    {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[markdown]": 
    {
        "editor.defaultFormatter": "yzhang.markdown-all-in-one"
    },
    "[xml]":
    {
        "editor.defaultFormatter": "mrmlnc.vscode-csscomb"
    },
    "atomKeymap.promptV3Features": true,
    "attrsSorter.order": ["alt", "class", "http-equiv", "id", "iname", "name", "rel", "src", "type", "href"],
    "banner-comments-plus.commentStyle": "both",
    "banner-comments-plus.font": "Small Slant",
    "banner-comments-plus.trimEmptyLines": true,
    "banner-comments-plus.trimTrailingWhitespace": true,
    "css.validate": false,
    "editor.autoIndent": false,
    "editor.colorDecorators": false,
    "editor.cursorStyle": "line",
    "editor.fontFamily": "'Fira Code', 'M++ Nerd Font', 'EmojiOne Color', monospace",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
    "editor.matchBrackets": false,
    "editor.minimap.enabled": false,
    "editor.minimap.renderCharacters": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.quickSuggestions":true,
    "editor.renderLineHighlight": "gutter",
    "editor.selectionHighlight": false,
    "editor.smoothScrolling": true,
    "editor.tabCompletion": "on",
    "editor.tabSize": 2,
    "emmet.excludeLanguages": [""],
    "emmet.includeLanguages": {"markdown": "html", "md": "html", "vue-html": "html"},
    "emmet.showSuggestionsAsSnippets": true,
    "emmet.triggerExpansionOnTab": true,
    "explorer.autoReveal": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.openEditors.visible": 0,
    "extensions.ignoreRecommendations": true,
    "files.autoSave": "onFocusChange",
    "files.exclude": 
    {
        "**/.DS_Store": false,
        "**/.git": false
    },
    "git.autofetch": true,
    "git.autorefresh": true,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "html-css-class-completion.enableEmmetSupport": true,
    "html.format.indentInnerHtml": true,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
    "latex-workshop.hover.preview.cursor.color": "blue",
    "latex-workshop.latex.autoBuild.run": "never",
    "latex-workshop.latex.autoClean.run": "onBuilt",
    "latex-workshop.latex.clean.fileTypes": 
    [
        "*.acn",
        "*.acr",
        "*.alg",
        "*.aux",
        "*.bcf",
        "*.bbl",
        "*.blg",
        ".DS_Store",
        "*.fdb_latexmk",
        "*.fls",
        "*.glg",
        "*.glo",
        "*.gls",
        "*.idx",
        "*.ind",
        "*.ist",
        "*.lof",
        "*.log",
        "*.lol",
        "*.lot",
        "*.out",
        "*.run.xml",
        "*.toc",
        "*/*.aux",
        "*/.DS_Store"
    ],
    "latex-workshop.latex.recipes": 
    [
        {
        "name": "xelatex",
        "tools": 
        [
            "xelatex"
        ]
        },
        {
        "name": "xelatex -> biber -> xelatex*2",
        "tools": 
        [
            "xelatex",
            "biber",
            "xelatex",
            "xelatex"
        ]
        },
        {
        "name": "xelatex -> -> makeglossaries > biber -> xelatex*2",
        "tools": 
        [
            "xelatex",
            "makeglossaries",
            "biber",
            "xelatex",
            "xelatex"
        ]
        }
    ],
    "latex-workshop.latex.tools": 
    [
        {
        "name": "xelatex",
        "command": "xelatex",
        "args": 
        [
            "-synctex=1",
            "-halt-on-error",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf",
            "-shell-escape",
            "%DOC%"
        ]
        },
        {
        "name": "biber",
        "command": "biber",
        "args": 
        [
            "%DOCFILE%"
        ]
        },
        {
        "name": "makeglossaries",
        "command": "makeglossaries",
        "args": 
        [
            "%DOCFILE%"
        ]
        }
    ],
    "latex-workshop.message.update.show": false,
    "latex-workshop.view.outline.sections": 
    [
        "chapter",
        "section",
        "subsection",
        "subsubsection",
        "subsubsubsection",
        "subsubsubsubsection"
    ],
    "latex-workshop.view.pdf.viewer": "browser",
    "liveServer.settings.donotVerifyTags": true,
    "liveServer.settings.donotShowInfoMsg": true,
    "markdown.extension.print.imgToBase64": false,
    "markdown.extension.print.onFileSave": false,
    "markdown.extension.syntax.plainTheme": true,
    "markdown.extension.toc.githubCompatibility": true,
    "markdown.preview.markEditorSelection": false,
    "material-icon-theme.activeIconPack": "react",
    "material-icon-theme.files.associations": 
    {
        "changelog.php": "changelog",
        "Änderungsprotokoll.md": "changelog",
        "Journal des Modifications.md": "changelog",
        "Registro de Cambios.md": "changelog",
    },
    "material-icon-theme.folders.associations": 
    {
        "fontes": "font",
        "idiomas": "i18n",
        "imagens": "images",
        "javascript": "javascript",
        "language": "i18n",
        "teste": "test"
    },
    "material-icon-theme.folders.color": "#E5CD52",
    "materialTheme.accent": "Acid Lime",
    "phpserver.browser": "firefox",
    "phpserver.port": 8200,
    "php-cs-fixer.autoFixByBracket": true,
    "php-cs-fixer.config": "/home/gusbemacbe/php_cs.dist",
    "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
    "php-cs-fixer.formatHtml": true,
    "php-cs-fixer.lastDownload": 1555451751386,
    "search.followSymlinks": false,
    "search.location": "panel",
    "spellright.documentTypes": 
    [
        "css",
        "html",
        "markdown",
        "latex",
        "python"
    ],
    "terminal.explorerKind": "external",
    "terminal.external.linuxExec": "gnome-terminal",
    "terminal.integrated.fontFamily": "'M++ Nerd Font Mono', 'EmojiOne Color', monospace",
    "terminal.integrated.fontSize": 11,
    "terminal.integrated.env.linux": 
    {
        "LESSCHARSET": "utf-8"
    },
    "terminal.integrated.experimentalRefreshOnResume": true,
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.shell.linux": "/usr/bin/zsh",
    "vscode_custom_css.imports": ["file:///home/gusbemacbe/.vscode-insiders/themes/emojione.css"],
    "vscode_custom_css.policy": true,
    "window.menuBarVisibility": "visible",
    "window.zoomLevel": 1,
    "workbench.activityBar.visible": true,
    // An Old Hope Theme
    // "workbench.colorCustomizations": 
    // {
    //     "activityBarBadge.background": "#E5CD52",
    //     "activityBar.border": "#E5CD52",
    //     "activityBar.foreground": "#A9B8BA",
    //     "scrollbarSlider.background": "#E5CD52",
    //     "scrollbarSlider.hoverBackground": "#4FB4D7"
    // },
    // "Material Theme Darker High Contrast"
    "workbench.colorCustomizations": 
    {
        "activityBarBadge.background": "#C6FF00",
        "activityBar.border": "#E5CD52",
        "activityBar.foreground": "#A9B8BA",
        "breadcrumb.activeSelectionForeground": "#C6FF00",
        "editorSuggestWidget.highlightForeground": "#C6FF00",
        "editorWidget.border": "#C6FF00",
        "editorWidget.resizeBorder": "#C6FF00",
        "list.activeSelectionForeground": "#C6FF00",
        "list.highlightForeground": "#C6FF00",
        "list.inactiveSelectionForeground": "#C6FF00",
        "menu.selectionForeground": "#C6FF00",
        "menubar.selectionForeground": "#C6FF00",
        "notificationLink.foreground": "#C6FF00",
        "panelTitle.activeBorder": "#C6FF00",
        "pickerGroup.foreground": "#C6FF00",
        "progressBar.background": "#C6FF00",
        "scrollbarSlider.activeBackground": "#C6FF0050",
        "scrollbarSlider.background": "#E5CD52",
        "scrollbarSlider.hoverBackground": "#4FB4D7",
        "settings.headerForeground": "#C6FF00",
        "settings.modifiedItemForeground": "#C6FF00",
        "settings.modifiedItemIndicator": "#C6FF00",
        "tab.activeBorder": "#C6FF00",
        "textLink.foreground": "#C6FF00"
    },
    "workbench.colorTheme": "Mariana Nord",
    "workbench.editor.enablePreview": false,
    // "workbench.fontAliasing": "antialiased",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.settings.editor": "json",
    "workbench.startupEditor": "none",
    "workbench.quickOpen.preserveInput": true
}
```

</details>

**Comment by githublloyd** [comment]
> What's you in your settings.json file?

@Tyriar thanks for replying, here is my settings.json

{
    "editor.minimap.enabled": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
    "git.path": "C:\\Users\\obrienl\\.vscode\\git.bat",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.windowsEnableConpty": false,
    "editor.accessibilitySupport": "on"
}

**Comment by Tyriar** [comment]
@gusbemacbe that bug's fixed in the latest insiders (https://github.com/microsoft/vscode/issues/74183)

@githublloyd this looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
