### ISSUE TITLE
Terminal not cleared when re-opened after 'clear'

### ISSUE THREAD

**Issue by tophattom** [Microsoft/vscode#7456]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Open integrated terminal
2. Run some commands
3. Run `clear`
4. Close terminal
5. Re-open terminal

Here's a link to a video demonstrating the bug: [https://gfycat.com/LargeMilkyBuck](https://gfycat.com/LargeMilkyBuck)

**Comment by Tyriar** [comment]
This is fixed in master, coming in June :fireworks:
