### ISSUE TITLE
WebviewPanel Webview postMessage doesn't post a message

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#74568]
Testing https://github.com/microsoft/vscode/issues/47534

The existing doRefactor method in the coding cat sample doesn't successfully post a message. If you put a console.log() in onDidReceiveMessage you'll see that the message never reaches that point when you run the Refactor command.

**Comment by mjbvz** [comment]
`postMessage` goes to the webview content so you need to add the `console.log` here inside the webview javascript: https://github.com/microsoft/vscode-extension-samples/blob/f63e84e288af649e64d44448a6a1ff744c8faa5d/webview-sample/media/main.js#L30
