### ISSUE TITLE
Update message for `editor.gotoLocation.multiple`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74566]
See screen shot. The message is now out dated as we allow to cycle through other results pressing F12

<img width="501" alt="Screenshot 2019-05-29 at 17 20 39" src="https://user-images.githubusercontent.com/1794099/58569280-1a252e80-8236-11e9-840d-4c42cb8659e7.png">

**Comment by yilikunNEO** [comment]
This option is not working
![image](https://user-images.githubusercontent.com/43943437/68729989-6ad2ed00-0606-11ea-9ce0-32bc0b2791d9.png)
![image](https://user-images.githubusercontent.com/43943437/68730141-d2893800-0606-11ea-842b-084158dd37e9.png)
vscode info:
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
