### ISSUE TITLE
Use `uri`, not resource

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74561]
re https://github.com/microsoft/vscode/blob/4c5705f4f8700672b9eaddeefc2a687a23cbedd4/src/vs/vscode.d.ts#L8986

we use `uri` in most cases, in two other cases we use `resourceUri`. `resource` is never used

**Comment by rebornix** [comment]
@jrieken thanks, I saw the misalign in the code so picked one, forgot about that we renamed it to `uri` last week.
