### ISSUE TITLE
Broken behavior of ctrl+click multiselection in explorer

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#74573]
**Actual behavior**
First `ctrl+click` in explorer opens to side, then multiselect.

**Desired behavior**
Ctrl+click in explorer should begin multiselection from first ctrl+click as it is set as `multiSelectModifier` not  `firstOpenToSideThenMultiSelectModifier`.

[My settings](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e#file-settings-json)

**Comment by usernamehw** [comment]
duplicate of #66925 ?

**Comment by isidorn** [comment]
@usernamehw thanks
