### ISSUE TITLE
VSCode freezes system when launching from CLI on macOS

### ISSUE THREAD

**Issue by ExiaSR** [microsoft/vscode#74575]
- VSCode Version: `1.34.0`, `1.35.0-insider`
- OS Version: `macOS 10.14.5`

Steps to Reproduce:

1. Open terminal
2. Run `code-insiders --disable-extension --disable-gpu --verbose`
3. Throughout the process, the system is completely unusable 1 to 3 times, each last for a few seconds.

Does this issue occur when all extensions are disabled?: Yes

[vscode-insider log dump](https://gist.github.com/ExiaSR/353cad19982a16f2b9c2e206f06cb0e4)

Launch VSCode from GUI is fine.

~Also, not sure if this is related. I ran `ps -ax | grep "Visual Studio Code.app"` to check whether there is any hangout process. There is a hangout process in the background even I quit VSCode. The `pid` changes every time I ran the `ps` command, so it is impossible to kill the process.~ never mind this, it was just the `grep` process.
```
 6812 ttys000    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn Visual Studio Code.app
```

**Comment by kieferrm** [comment]
@ExiaSR `htop` is a good tool get find and kill processes that match a certain search term. Pls quit VS Code and kill all remaining processes. Keep `htop` running and relauch VS Code. Which processes are consuming all the CPU?

**Comment by ExiaSR** [comment]
> @ExiaSR `htop` is a good tool get find and kill processes that match a certain search term. Pls quit VS Code and kill all remaining processes. Keep `htop` running and relauch VS Code. Which processes are consuming all the CPU?

Hi @kieferrm 
I am afraid it is impossible to use `htop` to debug this issue. When launching VS Code, everything freeze, so we will not be able to monitor processes in real time.

But I was able to use the `Instruments` tool from XCode to record the CPU activities if that is helpful.

https://send.firefox.com/download/79ac2e9e48322ed0/#pDuZ3WPUW981yctgNXG9ow

**Comment by jrieken** [comment]
> When launching VS Code, everything freeze (besides the pointer, but no UI element is interactable or changed/refreshed),

That means it freezes your operating system? All apps are dead?

> https://send.firefox.com/download/79ac2e9e48322ed0/#pDuZ3WPUW981yctgNXG9ow

⬆️ that link is defunct, please attach a zip to this issue

**Comment by ExiaSR** [comment]
> > When launching VS Code, everything freeze (besides the pointer, but no UI element is interactable or changed/refreshed),
> 
> That means it freezes your operating system? All apps are dead?
> 
> > [send.firefox.com/download/79ac2e9e48322ed0/#pDuZ3WPUW981yctgNXG9ow](https://send.firefox.com/download/79ac2e9e48322ed0/#pDuZ3WPUW981yctgNXG9ow)
> 
> ⬆️ that link is defunct, please attach a zip to this issue

@jrieken 
Here's the updated link https://send.firefox.com/download/44791efaced4f430/#ZbTNU8uS3LL9FlsGp7toRA

**Comment by jrieken** [comment]
> Yes, the entire OS is frozen, all Apps

Cannot be - how would Instruments record something then. Looking at your trace, there are 2 vs code processes, taking ~10% CPU time, then other taking more CPU time. What kind of machine is this? How many cores do have?

<img width="639" alt="Screenshot 2019-05-31 at 09 26 05" src="https://user-images.githubusercontent.com/1794099/58689019-3f28b700-8386-11e9-9be6-102a02d3d5c4.png">

<img width="665" alt="Screenshot 2019-05-31 at 09 26 12" src="https://user-images.githubusercontent.com/1794099/58689044-4c45a600-8386-11e9-8b6b-020c0cfc10bc.png">

**Comment by ExiaSR** [comment]
> > Yes, the entire OS is frozen, all Apps
> 
> Cannot be - how would Instruments record something then. Looking at your trace, there are 2 vs code processes, taking ~10% CPU time, then other taking more CPU time. What kind of machine is this? How many cores do have?
> 
> <img alt="Screenshot 2019-05-31 at 09 26 05" width="639" src="https://user-images.githubusercontent.com/1794099/58689019-3f28b700-8386-11e9-9be6-102a02d3d5c4.png">
> 
> <img alt="Screenshot 2019-05-31 at 09 26 12" width="665" src="https://user-images.githubusercontent.com/1794099/58689044-4c45a600-8386-11e9-8b6b-020c0cfc10bc.png">

By freeze I mean, the apps (at least the UI) are unresponsive no matter where I click. Once the VS Code is completely opened, all apps work again. I guess it was the UI thread is somehow blocked?

It's a 2017 MacBook Pro (Touch Bar), 2.7 GHz, 4-core, i7.

**Comment by jrieken** [comment]
> Also to clarify, the freeze thing only happens when I open VS Code from CLI. It works fine when I open it from GUI, such as Spotlight, Launchpad, and Alfred.

That makes this more interesting... Adding @joaomoreno who know what we are doing then

**Comment by ExiaSR** [comment]
Please let me know if you need anything else. I’m happy to provide more detail. Thanks.

**Comment by joaomoreno** [comment]
Can you try creating a new user in your system and see if that user also gets the same behaviour?

**Comment by ExiaSR** [comment]
> Can you try creating a new user in your system and see if that user also gets the same behaviour?

Yes, the same thing happened.

**Comment by joaomoreno** [comment]
We actually do much less when running from the CLI... :thinking: 

Can you maybe run it with `time `?

**Comment by ExiaSR** [comment]
```
code-insiders --disable-extension --disable-gpu  0.15s user 0.07s system 96% cpu 0.230 total

code-insiders --disable-extension --disable-gpu  0.15s user 0.09s system 91% cpu 0.263 total

code-insiders --disable-extension --disable-gpu  0.15s user 0.08s system 85% cpu 0.269 total
```

It looks good to me 🤔

**Comment by joaomoreno** [comment]
Could you maybe record a video with your phone? I'd like to see what you see as well.

**Comment by ExiaSR** [comment]
@joaomoreno https://send.firefox.com/download/1d2a58b27b8aeae6/#ZGd__uX300L57qUpQMWxbw

**Comment by joaomoreno** [comment]
I am clueless on this. Pinging @jrieken, since there are more details. Pinging @bpasero and @deepak1556 for ideas.

**Comment by bpasero** [comment]
Does this reproduce when running a bare Electron application from the command line?

**Comment by ExiaSR** [comment]
@bpasero actually, yes. I tried spinning up the [quick start example](https://github.com/electron/electron-quick-start), it froze the system as VSCode did.

Below is the runtime info,

```
Node.js 12.0.0, Chromium 73.0.3683.121, and Electron 5.0.4
```

AFAIK VSCode is the only Electron app that freezes my system, things like Slack, Discord, and Franz are fine (tho they are closed source, not sure how to tell why not)

**Comment by joaomoreno** [comment]
> Does this reproduce when running a bare Electron application from the command line?

Great question!

Maybe it's version dependent. Could you try spawning different versions using Electron Fiddle? https://github.com/electron/fiddle/releases/tag/v0.8.1

**Comment by ExiaSR** [comment]
@joaomoreno 

After some experiment, it turns out the freeze only happens on iTerm2 nightly build (I guess I have to downgrade to the stable release). So I am closing this for now. Thank you so much for your help.
