### ISSUE TITLE
Git Badge and File List Doesn't Update if Files Committed from Another Application

### ISSUE THREAD

**Issue by rrmanthonyc** [microsoft/vscode#74577]
Issue Type: <b>Bug</b>

If changes are made to files in a git repository, then committed in another application (in my case Sourcetree) the badge indicator and file list in the git tab don't update. It still shows that there are files that needed to be committed. It also still shows the edited lines indicators in the editor.

![Bug Screenshot](https://user-images.githubusercontent.com/43010898/58582581-dc5ce180-8206-11e9-8ba9-54df919ceb27.png)

Attached is a screenshot of the git tab after the changes have been committed in Sourcetree. The filename has been blocked out for privacy reasons, but is a `.sql` file. Quitting VS Code and reopening fixes the issue.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|
</details>Extensions: none

**Comment by kieferrm** [comment]
@rrmanthonyc a couple of questions:
- Is the root of the git repository the same as the folder you have open?
- When you refresh using the circled arrow next to the checkbox (in the screenshot above) does the git view correctly update?
- What is the value of your `git.autorefresh` user setting?

**Comment by rrmanthonyc** [comment]
Hello @kieferrm, thank you for the reply.

- No, I'm a couple folders deeper.
- I have not tried that, but I will and get back with you if I can.
- Auto Refresh is turned on.

**Comment by rrmanthonyc** [comment]
The git view correctly updates when I hit the refresh button.

**Comment by joaomoreno** [comment]
> No, I'm a couple folders deeper.

That's the main issue. https://github.com/microsoft/vscode/issues/41085

**Comment by rrmanthonyc** [comment]
Sounds good. Thanks.
