### ISSUE TITLE
TaskRunner: PowerShell does not execute local binaries without ".\" prefix

### ISSUE THREAD

**Issue by TheTyrius** [microsoft/vscode#74571]
- VSCode Version: 1.33.1
- OS Version: Win10 Version 10.0.17763 Build 17763

Steps to Reproduce:

1. Install local binary, in my case "npm install --save-dev TypeScript", which gives me 'tsc' in the root folder where I am trying to execute it
2. When I invoke the taskrunner it can't use the binary: 
```
> Executing task in folder ProtoTool: tsc -p <redacted path>\tsconfig.json <

tsc : The term 'tsc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ tsc -p <redacted path>\tsconfig.json
+ ~~~
    + CategoryInfo          : ObjectNotFound: (tsc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

When I switch the default shell to cmd.exe this built-in command execution works as expected.
Manually calling the command reveals this Powershell "regression":
```
Suggestion [3,General]: The command tsc was not found, but does exist in the current location.
Windows PowerShell does not load commands from the current location by default. 
If you trust this command, instead type: ".\tsc". See "get-help about_Command_Precedence" for more details.
```

Does this issue occur when all extensions are disabled?: Yes

Since I never chaged this setting before I assume PowerShell is the default at this time.
Is this simply a limitation of this shell, or is there anything you can do about how tasks are invoked if the binaries are local?

Best Regards,
Tyrius

**Comment by alexr00** [comment]
PowerShell is the default shell in VS Code on Windows, but as you found you can switch it. Since this is considered to be a PowerShell security feature, we shouldn't change the behavior for VS Code. 

I did find this though: https://superuser.com/questions/1373012/avoid-dot-backslash-windows-10-powershell
