### ISSUE TITLE
DocumentLink.toolip wrapping

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#74579]
Testing #74311

OS Version: Windows Enterprise

With wrapping for long tooltips (if the title has space in it)
![image](https://user-images.githubusercontent.com/9721254/58585613-1087d080-820e-11e9-8af3-fc1701a3404c.png)

If I have a long link without spacing in it, there's no wrapping and the scroll bar shows up only if you hover by the tooltip.
![image](https://user-images.githubusercontent.com/9721254/58585797-7e33fc80-820e-11e9-99b2-9bbf3a455c22.png)

Thoughts on wrapping? @misolori @mattbierner

**Comment by mjbvz** [comment]
After thinking about this a bit more, I'd say we should wrap long words / links

**Comment by mjbvz** [comment]
Pushing to June since the change will effect some core styling
