### ISSUE TITLE
Better handling of markers from temporary or in memory files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#7457]
I think the editor does not show problems in non file resources but the problems view does. In this case there is a warning in the default settings file (readonly) and the problems view shows the warning but the editor does not:

![image](https://cloud.githubusercontent.com/assets/900690/15921485/1da85250-2e22-11e6-9717-b36b7a833b8c.png)

**Comment by sandy081** [comment]
After taking to @dbaeumer I made this issue specific to temporary files.. I do not think the problems view should be filtering them and neither the editor. Better solution for this could be

- Let the markers owner (linters) remove them on the files when they are closed

@aeschli FYI

**Comment by bpasero** [comment]
@sandy081 sometimes I seem to have markers for files that do not exist anymore, maybe as a workaround could the problems view offer an action to delete markers? that is currently the only way of getting rid of markers.

**Comment by sandy081** [comment]
@bpasero This workaround could help the current problem but I think it would open doors for other new things. Currently the view is just a representation of the markers generated by the sources.. It is expected that all markers are valid and users are supposed to fix them in the files. 

I think we need to come up with a nice story around managing markers.. May be more customizations or open apis or adding more capabilities to current view as you said.

**Comment by jrieken** [comment]
I'd say this is better or covered in enough other issues
