### ISSUE TITLE
Warning color is inconsistent in peek

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#74580]
I've never understood why there was an inconsistency in our warning colors. Yellow is typically used for warning, and we use a yellow icon but use green in the editor/decoration/peek error view:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/35271042/58587150-7f1a5d80-8211-11e9-8c78-82ec44b99bd4.png">

My proposal is to make it all consistently yellow or green (I prefer yellow since it's more common):

<img width="453" alt="image" src="https://user-images.githubusercontent.com/35271042/58587026-3662a480-8211-11e9-8a42-cc92971af621.png">

**Comment by sandy081** [comment]
No objections. @jrieken FYI.

**Comment by jrieken** [comment]
Good for me

**Comment by sandy081** [comment]
@misolori Please give me the new default warning peek colours for dark and light themes.

**Comment by misolori** [comment]
@sandy081 I was thinking we could use `#FFCC00` for dark and `#E9A700` for light:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/35271042/58849085-d703fa80-863d-11e9-925a-4c743c9e1ae8.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/35271042/58849401-0ebf7200-863f-11e9-98f6-e6e7a44e4e63.png">

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/58974263-4c003d00-87c2-11e9-8af9-dc84465ebdee.png)

![image](https://user-images.githubusercontent.com/10746682/58974289-5ae6ef80-87c2-11e9-8f19-d9114d731014.png)

**Comment by bpasero** [comment]
> I've never understood why there was an inconsistency in our warning colors. Yellow is typically used for warning, and we use a yellow icon but use green in the editor/decoration/peek error view:

My guess would be that Visual Studio is using green, at least from my memories (cc @stevencl)

**Comment by stevencl** [comment]
No, the outline for peek definition in VS is blue. There also isn't a peek view to view warnings and errors in the editor.

**Comment by bpasero** [comment]
@misolori from your screenshot I thought we are changing the color of the squiggleys too? Maybe not?

**Comment by stevencl** [comment]
I see, in that case green is used for warnings.

![image](https://user-images.githubusercontent.com/1704059/58976347-245ba580-87bf-11e9-9924-f577d19c251a.png)

**Comment by misolori** [comment]
@bpasero yes, squiggleys as well since them main issue was about making them consistent

**Comment by sandy081** [comment]
Changed the color in overview ruler to make it consistent.

![image](https://user-images.githubusercontent.com/10746682/58989084-76162700-87e3-11e9-9d2f-057975a56874.png)
