### ISSUE TITLE
Runaway terminalProcess processes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7458]
These processes linger around long after I shutdown Code:

![image](https://cloud.githubusercontent.com/assets/22350/15921488/229a06c8-2e22-11e6-82a9-7bbec9ea3330.png)

We usually [detect whether the parent process is dead](https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/sharedProcessMain.ts#L31) to suicide a process.

**Comment by Tyriar** [comment]
Good find, thanks for the link :)

**Comment by Tyriar** [comment]
@joaomoreno please verify when you get a chance
