### ISSUE TITLE
Tree UI

### ISSUE THREAD

**Issue by nzrubin** [microsoft/vscode#74587]
Issue Type: <b>Feature Request</b>

Hello admin
could you please change the Files tree structure at the explorer .
add either colors or bigger indent.
very hard to navigate around the folders! 
it is actully very annoying and very DUMB of the UI designer to make a tree look like that! 
in a such a complex software this kind of UI elements should be the simplest and not noticable by user

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
/duplicate of #17777

@nzrubin you might also try increasing the workbench.tree.indent setting, which defaults to 8.

**Comment by nzrubin** [comment]
oh! That is better! good job
