### ISSUE TITLE
Code Helper CPU usage constantly high even though nothing in process explorer

### ISSUE THREAD

**Issue by jscheel** [microsoft/vscode#74581]
Code Helper is constantly using high cpu (~103%), even though the process explorer is showing nothing. Even after quitting vscode, the helper is still running and still consuming an entire cpu. Happens with extensions disabled as well.

- VSCode Version: 1.34.0
- OS Version: macOS 10.12.5

```
[59236:0529/145609.221034:WARNING:dns_config_service_posix.cc(174)] dns_config has unhandled options!
Version:          Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS Version:       Darwin x64 16.6.0
CPUs:             Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)
Memory (System):  16.00GB (0.03GB free)
Load (avg):       3, 4, 4
VM:               20%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    enabled
                  rasterization:                enabled
                  surface_synchronization:      enabled_on
                  video_decode:                 enabled
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	    98	 58926	code main
    0	    66	 58932	   gpu-process
    0	   147	 58941	   window (view.jsx — mobile-frontend)
    0	    98	 58952	     extensionHost
    0	   786	 58956	       electron_node tsserver.js
    0	    66	 58983	         electron_node typingsInstaller.js typesMap.js
    0	    82	 58958	       electron_node eslintServer.js
    0	    33	 59024	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=58952
    0	    33	 58953	     watcherService
    0	    33	 58987	     searchService
    0	    49	 58954	   shared-process
    0	    82	 59133	   window (Process Explorer)

Workspace Stats:
|  Window (view.jsx — mobile-frontend)
|    Folder (mobile-frontend): 9278 files
|      File types: json(5184) jsx(1240) js(1235) svg(306) png(223) woff(218)
|                  ttf(180) eot(179) css(158) less(148)
|      Conf files: makefile(1) jsconfig.json(1) package.json(1)
|                  webpack.config.js(1) launch.json(1) settings.json(1)
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by jscheel** [comment]
@mjbvz yep, I have tested on the latest insiders build, with extension disabled.

![Screen Shot 2019-05-30 at 10 19 46 AM](https://user-images.githubusercontent.com/211478/58643240-83ec1980-82c4-11e9-9685-081117d39a7e.png)

**Comment by dfrsol** [comment]
My co-workers and I are experiencing the same high CPU usage caused by Code Helper, we've tried the recommended fix of downgrading the Typescript version and disabling extensions but neither of those seems to resolve the issue. This issue was occurring intermittently the past two months but recently it happens pretty much any time we use VSCode.

**Comment by jscheel** [comment]
Some news, I wiped by typescript cache and have not seen sustained cpu usage since. I'll report back after using for a bit.

**Comment by mjbvz** [comment]
@jscheel  Are you using a custom typescript version in your workspace?

**Comment by JulesAU** [comment]
@jscheel How do I clear the TS cache?

I'm experiencing the same high CPI problem as others in this thread - with all extensions disabled.

**Comment by jscheel** [comment]
@mjbvz nope, I don’t even use TS yet.

@JulesAU it depends on what OS you are on. On my phone right now, so best bet is for you to search the repo issues here, that’s where I found it.

**Comment by Aleksion** [comment]
I'm experiencing the same thing. But it started happening after the update to 1.33 (it's still there in 1.34).
1.32.3 works perfectly with low CPU usage.

Some notes:

- Typescript is updated to the latest version (3.5.1)
- We're using styled-components (some users have reported this might be the culprit)

Even if styled-components is the culprit, I don't understand why the regression happened between 1.32.3 and the newer versions.

**Comment by mjbvz** [comment]
@jscheel Can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a `tsserver.log` file

 If you can share the log, I can also take a look to see if anything stands out that 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by jscheel** [comment]
Since clearing my typescript cache, I haven’t had the issue return. I’ll keep an eye out though.

**Comment by jscheel** [comment]
Well, the issue has returned. It seems to be caused by switching branches in my repo. I already had terse reporting on, and I'm noticing a couple of interesting things from the logs:

1. It seems to be watching files in the `.git` directory (e.g. `DirectoryWatcher:: Triggered with /users/jscheel/projects/***/mobile-frontend/.git/index :: WatchInfo: /users/jscheel/projects/***/mobile-frontend 1 Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json WatchType: Wild card directory`)`

2. It seems to be constantly updating the graph worker. There are tons of lines like this, interspersed with the first note about changes in the git directory:
```
Info 16417[15:46:49.184] Starting updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json
Info 16418[15:46:51.357] Finishing updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json Version: 2136 structureChanged: false Elapsed: 2173ms
Info 16419[15:46:51.507] Starting updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json
Info 16420[15:46:55.11] Finishing updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json Version: 2137 structureChanged: false Elapsed: 3504ms
Info 16421[15:46:55.193] Starting updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json
Info 16422[15:46:57.338] Finishing updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json Version: 2138 structureChanged: false Elapsed: 2145ms
Info 16423[15:46:57.568] Starting updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json
Info 16424[15:47:1.113] Finishing updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json Version: 2139 structureChanged: false Elapsed: 3545ms
Info 16425[15:47:1.297] Starting updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json
Info 16426[15:47:3.929] Finishing updateGraphWorker: Project: /Users/jscheel/Projects/***/mobile-frontend/jsconfig.json Version: 2140 structureChanged: false Elapsed: 2632ms
```


Here is my `jsconfig.json` file:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./src",
    "jsx": "react",
    "module": "es6",
    "target": "es2018",
    "moduleResolution": "node"
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by AndrewRayCode** [comment]
Seeing the same thing, and I didn't realize the helper continues to run even after Visual Studio Code is closed until I saw it in this thread.

<img width="809" alt="Screen Shot 2019-07-06 at 1 02 07 PM" src="https://user-images.githubusercontent.com/79215/60760693-8beb5780-9fee-11e9-98d2-c32d7494f544.png">
<img width="1271" alt="Screen Shot 2019-07-06 at 1 01 58 PM" src="https://user-images.githubusercontent.com/79215/60760694-8beb5780-9fee-11e9-9486-1115a5965159.png">
