### ISSUE TITLE
Can't left-click on lightbulbs anymore

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#74595]
Issue Type: <b>Bug</b>

Left-clicking still works in the stable build, so I assume this wasn't intentional.

**Steps to reproduce:**
1. Place the cursor on any code with a quick fix available.
2. Attempt to left-click on the lightbulb.

**Notes:**
- Right-clicking still works.

VS Code version: Code - Insiders 1.35.0-insider (6964233e81c68f5a5f34e7eb1da0836e1d539f14, 2019-05-29T05:18:15.943Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by mjbvz** [comment]
@sbatten I believe this is the same problem that was discussed in #71580

**Comment by sbatten** [comment]
@mjbvz Yea that one won't get closed so let's keep this one open to be verified since this has now been fixed.
