### ISSUE TITLE
editor.wordBasedSuggestions shows up last in default settings?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7459]
I would expect settings to be grouped together but `editor.wordBasedSuggestions` shows up last:

![image](https://cloud.githubusercontent.com/assets/900690/15921591/be7815da-2e22-11e6-8d2e-4c20119c7623.png)

**Comment by bpasero** [comment]
Looks like we have different files where settings are contributed from (in this case https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/suggestSupport.ts#L25) but I think that should not make a difference.

**Comment by aeschli** [comment]
There is a 'order' property on the configuration settings. Editor settings have order 5. So to appear just after the editor settings use 5.1.
@jrieken FYI

**Comment by jrieken** [comment]
wow - I always thought it's by alphabet...
