### ISSUE TITLE
vscode-uri > 1.0.6 breaking language servers

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#74596]
please consider to unpublish 1.0.7 and 1.0.8 in favour of 2.0.0

Breaking for example via [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node/blob/71f8ee79c31f2b96f0c814d27cb66fe252403d08/server/package.json#L21) or [directly](https://github.com/theia-ide/typescript-language-server/blob/958bbb883af5724450932e3c25fb9832dacf62b1/server/package.json#L24)

**Comment by jrieken** [comment]
@akosyakov - I published 1.0.8 to mitigate a breakage in 1.0.7 (see https://github.com/microsoft/vscode/issues/74533) and I am not entirely sure what 1.0.8 breakage you are referring to?

**Comment by jrieken** [comment]
maybe this: https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634#r33726484

**Comment by akosyakov** [comment]
There is not default export anymore for `URI`. imports like `import Uri from 'vscode-uri'` don't work anymore.

**Comment by jrieken** [comment]
> There is not default export anymore for URI. imports like import Uri from 'vscode-uri' don't work anymore.

That's why there is 1.0.8 - it fixes the default export issue

**Comment by akosyakov** [comment]
ok, we use old Monaco, it is compatible with `vscode-uri` now, will fix on our side

**Comment by jrieken** [comment]
Thanks for the quick response!
