### ISSUE TITLE
copy, paste and cut stops to work in the inputs after assign them another key

### ISSUE THREAD

**Issue by zhangkaiyulw** [microsoft/vscode#74599]
- VSCode Version: 1.34.0
- OS Version: 10.14.5

Steps to Reproduce:

1. Assign `editor.action.clipboardCopyAction`, `editor.action.clipboardPasteAction`, `editor.action.clipboardCutAction`, `editor.action.selectAll` another key
For example: ctrl-w for cut, alt-w for copy, ctrl-y for paste
2. Make sure when `Open Keyboard Shortcuts` opens, there is double records for each command. Aka, *DO NOT OVERWIRTE DEFAULT KEY BINDING*.
3. Open search panel, try `cmd+c`, `cmd+a`, `cmd+v`, `cmd+x`, they all lose the ability to do its actions. same for all inputs and terminals. 
4. After assign these commands another key shortcut, in terminals or active inputs, they cannot do their own job anymore.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@zhangkaiyulw

This is unfortunately some funny Electron behaviour. Input boxes (`<input>`) such as the one used as input in the search panel actually do not have a `cmd+c`, `cmd+v`, `cmd+x` default action, so those inputs are piggy-backing on the fact that we have a menu entry for copy/paste/cut, which ends up triggering the default behaviour. You can see that the Edit menu is flashing when you press those keys... 

When you bind other keybindings to copy, paste, cut, we render the most "recent" keybindings in the menus (the last ones that appear in `keybindings.json`), so the Edit menu will no longer contain `cmd+c`, `cmd+v`, `cmd+x`.

There is one possible workaround you could use, which is to repeat the default keybindings later:
```
	{
		"key": "alt+w",
		"command": "editor.action.clipboardCopyAction",
		"when": "textInputFocus"
	},
	{
		"key": "cmd+c",
		"command": "editor.action.clipboardCopyAction",
		"when": "textInputFocus"
	},
```

This will make it that the Edit menu still uses `cmd+c` for the copy, which will make native `<input>` elements support the keybinding, and will bind `alt+w` for copying in the editor too.

**Comment by zhangkaiyulw** [comment]
Thanks! @alexandrudima
