### ISSUE TITLE
[Performance] searching for a file by ctrl+p is really really slow

### ISSUE THREAD

**Issue by wwm0609** [microsoft/vscode#74598]
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

Disk type: HDD
File system: ext4
Project:  Android/AOSP

Searching for certain java files is too slooooow!
BTW, using `find -type -f -name ...`  in terminal only takes 4~5 seconds;
Really don't get the reason why vscode could be this slow? Doesn't it cache? then what it is doing exactly during file indexing when launching a project?

**Comment by wwm0609** [comment]
already exlcuded the out folder and .repo folder:
```bash
    "files.exclude": {
        "out/*": true,
        ".repo/*":true,
        ".CCACHE/*":true,
        "cts/*":true,
    },
    "files.watcherExclude": {
        "out/*": true,
        ".repo/*":true,
        ".CCACHE/*":true,
        "cts/*":true,
    },
```

**Comment by wwm0609** [comment]
I don't think installing plugins like `Fuzzy File Search` (no offence, which is handy for now) is the only solution

**Comment by roblourens** [comment]
How long does it take? Is your project on a networked file share or something like that? Is text search also slow?

Also have some tips here: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by wwm0609** [comment]
tooks long enough (more than 10 sec and no any search results) before I give up
the project is on my local disk;
Text search is ok;

**Comment by roblourens** [comment]
So text search is much faster?

Also please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by wwm0609** [comment]
@roblourens Thanks for the reply.

After googled, found vscode native file picker uses `rg` (ripgrep)  to search files (every time after the input pattern changed ?) which might not be fast enough for large projects,  especially when the underlying disk is not ssd; 
So I wrote my own file picker extension, and it meets my own requirement, so just close this issue now.
