### ISSUE TITLE
Attach an object to a QuickPickItem

### ISSUE THREAD

**Issue by lszomoru** [Microsoft/vscode#746]
The QuickPick widget is a great extensibility point but I was wondering if there are any plans to allow attaching an arbitrary object to a QuickPickItem which would then be passed along when the item is selected? Thanks!

**Comment by jrieken** [comment]
It already does. The signature is `<T extends QuickPickItem>` (https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2799) allowing you pass in any object extending quick pick item

**Comment by lszomoru** [comment]
you are right, my bad. Thanks Jo!

**Comment by jrieken** [comment]
no worries, Happy Coding

**Comment by Jakobud** [comment]
How do you use QuickPickItems? I cannot figure it out or find documentation on it beyond the API docs. I tried this:

```
var items = [];
var item = new vscode.workspace.QuickPickItem({
  'description': 'test',
  'detail': 'test2',
  'label': 'test3'
});
items.push(item);
vscode.window.showQuickPick(items)
.then(function(value){
  console.log(value);
});
```

I'm using JS instead of TS. Does that make a difference?

**Comment by jrieken** [comment]
The [`QuickPickItem`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1329) is defines as an interface (thing of a struct) which means it isn't callable/newable. Simply have a object literal that as the required properties, like

```
{
  'description': 'test',
  'detail': 'test2',
  'label': 'test3'
}
```

**Comment by Jakobud** [comment]
Okay so I was messing with this a bit more. Is `QuickPickItem` only available using TypeScript? I could get it to work like this:

```
var item: vscode.QuickPickItem = { ..... };
```

How would I do the same thing using just JS? Are you saying I could just pass an array of objects to the `showQuickPick` ?

```
var items = [];
items.push({
  'description': 'test',
  'detail': 'test2',
  'label': 'test3'
}];
vscode.showQuickPick(items).then((item)=> { ... });
```

? Sorry, it's just that there doesn't seem to be a lot of documentation on that yet. I found the code somewhere online for using it with TypeScript but I couldn't figure it out with JavaScript. Speaking of which, which version of Node.js is running under Code? How much ES6 syntax can be used?
