### ISSUE TITLE
`search.exclude` doesn't work as expected

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#74600]
Issue Type: <b>Bug</b>

I'm trying to exclude a folder from search results, but can't make it happen. I think the video explains it best:
https://www.dropbox.com/s/f9nvdnxvaevasc8/VS%20Code%20Settings.mov?dl=0

I've checked and the JSON settings indeed show the "**/coverage" as a value, but the folder is still not excluded from searching.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-erb-beautify|ali|0.2.0
vscode-toggle-quotes|Bri|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
LogFileHighlighter|emi|2.5.0
prettier-vscode|esb|1.9.0
vscode-markdown-todo|fab|1.1.0
vscode-projects-plus|fab|1.22.0
vscode-pull-request-github|Git|0.7.0
vscode-language-babel|mgm|0.0.22
ruby-rubocop|mis|0.8.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
vscode-versionlens|pfl|0.23.0
ruby|reb|0.22.3
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
code-spell-checker|str|1.7.12
ada-lightbulb|vfo|0.4.0

</details>

**Comment by gjsjohnmurray** [comment]
It looks like you haven't set this button:
![image](https://user-images.githubusercontent.com/6726799/58623745-949d8f00-82c6-11e9-8843-08755fc8d389.png)

**Comment by vfonic** [comment]
What should I set it to? Shouldn't the settings be respected in case nothing is selected through that button? Why am I not getting results from `node_modules` then, if that field is empty? It seems inconsistent. I just think there's something off with the way I set `coverage` folder to be excluded.

**Comment by gjsjohnmurray** [comment]
You don't need to put anything into the field, but you **do** need to make sure the toggle-button is in the "selected" state (blue border). Otherwise the exclude settings in your User/Workspace settings and your 'ignore' files won't be applied, meaning your search will cover a lot more code than you probably expected.

**Comment by vfonic** [comment]
@gjsjohnmurray thanks for the tip!

I had no idea what that button does. (nor whether it's actually needed, but that's a different discussion)

Thanks!

**Comment by gjsjohnmurray** [comment]
[Doc pointer](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options)
