### ISSUE TITLE
Issue running yarn command during Build

### ISSUE THREAD

**Issue by Mohit-Nain** [microsoft/vscode#74601]
I was trying to set up VSCode locally in my workstation, currently i was under restricted network as per organization policies. Therefore running the yarn command to build the code locally in machine was not working, post setting up the proxies it worked fine.
Ideally Yarn command should run under open network as it needs to fetch packages to build the code. Therefore i suggest we include the section in the documentation which informs the user to either use proxy or use Open network when they are running the yarn command.

**Comment by kieferrm** [comment]
I added a note to the [prerequisite section](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) on the wiki.
