### ISSUE TITLE
Tasks: consider to use status progress for "Building..." entry

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74602]
Today there is a "Building..." label appearing around the problems entry when building a project. I think this originates from a time where we did not have support to show progress in the status bar.

![before](https://user-images.githubusercontent.com/900690/58615481-7d0cd900-82bb-11e9-82d0-d77352505a92.gif)

I suggest to move this out of the problems marker and into the status progress facility via `IProgressService.withProgress(ProgressLocation.Window)`

//cc @dbaeumer

**Comment by dbaeumer** [comment]
Makes sense to me.
