### ISSUE TITLE
Integrated PowerShell terminal %PATH% environment variable not matching PowerShell ones

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode#74606]
This is a very weird issue, but one, which causes me real problems (basically, as a result of this issue, I cannot use `npm start` in a project of mine anymore).

When I run `$Env:Path` in normal PowerShell terminal window (not the VS Code integrated terminal) and I check the results, it perfectly matches system and user variables as seen in Computer > Manage > Environment Variables according to this algorithm:

- Take all system variables
- Take all user variables except for ones already present in system (but take ones duplicate in user)

This is probably some internal PowerShell behavior for resolving PATH from system and user variables, it's not that important really, the important thing is:

In the VS Code integrated terminal using PowerShell, when running `$Env:Path` and comparing that to the system and user values - at least in my case, I find that the system values are repeated several times and not as a whole set of values in the system PATH variable, but instead there are like three different chunks from the system PATH (incomplete, not the whole set shuffled) which all repeat several times in random order.

That along is very weird to me, but that is not the whole issue, on top of that, **not all user PATH values show up**!

I know this is hard to imagine, so I will attach the output of all 4: user PATH, system PATH, VS Code integrated PowerShell terminal PATH and PowerShell proper PATH. You can see the VS Code file is missing `C:\Users\tohubelb\Desktop\%PATH%`.

I am not sure how, but somehow my `npm start` problem is related to this, because it works in normal PowerShell but not the VS Code one.

Is this a known issue, integrated PowerShell terminal missing user PATH values and having such a weird PATH as opposed to normal PowerShell?

- VSCode Version: 1.34.0 and 1.35.0-insider
- OS Version: Windows 10, version 1809, build 17763.437

Steps to Reproduce:

1. In Code: `$Env:Path > code.txt` and then replace `;` with `\n`
2. In PowerShell: `$Env:Path > pwsh.txt` and then replace `;` with `\n`
3. Compare

[pwsh-core.txt](https://github.com/microsoft/vscode/files/3236098/pwsh-core.txt)
[system.txt](https://github.com/microsoft/vscode/files/3236099/system.txt)
[user.txt](https://github.com/microsoft/vscode/files/3236100/user.txt)
[code.txt](https://github.com/microsoft/vscode/files/3236101/code.txt)
[code-insiders.txt](https://github.com/microsoft/vscode/files/3236102/code-insiders.txt)
[pwsh.txt](https://github.com/microsoft/vscode/files/3236103/pwsh.txt)

**Comment by TomasHubelbauer** [comment]
I've struggled with this for the past three days after doing some manual adjustments to my PATH. The last two days I just reinstalled NPM and kept reinstalling the OS and Code until things worked. This morning I took the above logs after running into it again and right now I restarted VS Code and it started working so I took a log of a working case as well.
[code-works.txt](https://github.com/microsoft/vscode/files/3236150/code-works.txt)
As you can see, it is identical to the PowerShell output.
I have no idea what causes VS Code integrated PowerShell terminal to have the `code.txt` PATH values versus `code-works.txt` PATH values, unfortunately.
I am willing to do more digging/debugging when guided.

**Comment by TomasHubelbauer** [comment]
I think this might also be a PowerShell issue and the order in which I tried things made it always seem like it was only happening in VS Code but I have yet to repro this in the actual PowerShell terminal so for now this looks like a VS Code issue to me. If I do manage to prove this to be a general PowerShell issue, I will close this one.

**Comment by Tyriar** [comment]
I've received a few reports about this for Windows but don't understand why it's happening yet. It's similar to https://github.com/Microsoft/vscode/issues/70248 but I don't think that's how it works on Windows.

**Comment by arseneyr** [comment]
I'm also seeing this issue while using cmd as the integrated terminal, so I don't think it's Powershell specific. However, I'm only seeing it when launching VS Code from the start menu. When launching from a cmd terminal (e.g. `code .`), the PATH is correct.

**Comment by Tyriar** [comment]
@arseneyr it's expected that you won't see rust show up until you close all VS Code windows and then reopen them.

**Comment by TomasHubelbauer** [comment]
Today this started happening for me in the actual PowerShell terminal window, not the VS Code integrated terminal, so this cannot be a VS Code issue I think. Funny thing is in CMD these PATH binaries are not even visible. Not sure what's up with all that but I messed up my system good it seems like.

@Tyriar 	I am closing this, if you want to keep investigating (you said you got more reports), feel free to reopen.
