### ISSUE TITLE
Associate custom shortcuts to custom tasks not yet possible.

### ISSUE THREAD

**Issue by Oni** [Microsoft/vscode#7460]
- VSCode Version: 1.2.0
- OS Version: Win 10 64 bit

Steps to Reproduce:

1. crate a new task named "myTask"
2. add a shortcut like this: { "key": "ctrl+shift+b", "command": "workbench.action.tasks.myTask" }

The command associated to the shortcut isn't recognized.

**Comment by Oni** [comment]
It should be noted that there are now two "special tasks" marked with:
isBuildCommand?:boolean;
isTestCommand?: boolean;
that get linked to the "ctrl+shift+b" and "ctrl+shift+t" shortcuts.

If it's possible to add arbitrary shortcuts to named tasks, I wonder if they are still necessary.

**Comment by dbaeumer** [comment]
Dups: #6550
