### ISSUE TITLE
Line position after ctrl+click in problemMatcher output is not correct if VS connected remotely.

### ISSUE THREAD

**Issue by sergju** [microsoft/vscode#74605]
After ctrl+click file opened correctly, but position always is first line.
If open the same project with VSCode 1.34 all ok.
- VSCode Version: 1.35.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Make build task for makefile and c/cpp file
2. Make error in c/cpp file code
3. Run build task
4. Ctrl-click on problem line.
5. VSCode open proper file, but line position is always 1

    "tasks": [
        {
            "label": "make",
            "type": "shell",
            "command": "make",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "absolute"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]

test.cpp
#include <iostream>

int main()
{
    std::cou t << "Hello world\n";
    return 0;
}

makefile
all: test

CXX=clang++
CXXFLAGS=-g -O0 -std=c++14
# -fno-exceptions

test: ${PWD}/test.cpp makefile
	$(CXX) $(CXXFLAGS) $(LDFLAGS) ${PWD}/test.cpp -o $@

clean:
	$(RM) -rf *.o test

![image](https://user-images.githubusercontent.com/25798315/58618801-2f4c9c80-82cc-11e9-812e-6e56122657b2.png)

**Comment by alexr00** [comment]
I tested this with the hello world sample without tasks. In the terminal I just ran `echo "src/extension.ts:15"` while connected to a remote and not while connected to a remote. Only while not connected does it go to the correct line when ctrl+click.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/136
