### ISSUE TITLE
Terminal URI auto decode

### ISSUE THREAD

**Issue by hushaoqing** [microsoft/vscode#74604]
- VSCode Version:1.33
- OS Version: macOS Mojave version 10.14.3 (18D42)

Steps to Reproduce:

1. open Terminal
2. type `echo "http://example.com?a=JGPD%2B%2B%2BfS45rQEtkhKPjJw7vwCUsQ%3D"`, then `Cmd + click to follow link` in Terminal
3. in browser, it will become `http://example.com/?a=JGPD+++fS45rQEtkhKPjJw7vwCUsQ=`

Does this issue occur when all extensions are disabled?: Yes

When i use `Cmd + click to follow link` in Terminal, the URI in Firefox browser will auto decode. Is this a feature or a bug ?

**Comment by Tyriar** [comment]
@hushaoqing just to clarify, the auto decode breaks the link?

**Comment by hushaoqing** [comment]
@Tyriar yes, for me, the auto decode breaks the links.  I need the link keep encoded and consistent in Terminal and Browser when i use `Cmd + click to follow link` in Terminal. It's an unclear behavior. The links should be consistent in Terminal and Browser.

**Comment by Tyriar** [comment]
This happens because the links go into one of our URI objects but I'm convinced after many reports like this that we're doing the wrong thing.

**Comment by Tyriar** [comment]
Actually there's nothing I can do here as I'm just leveraging the generic opener service. You would need to convince the entire editor to change how links are handled which has already failed several times.

**Comment by jrieken** [comment]
@Tyriar fyi - I have a fix for this in `joh/opener`, https://github.com/microsoft/vscode/commit/65159d001a60c01985666dbdde7b14ba24262399. Initial progress looks good but I need to build up more confidence before merging

**Comment by Tyriar** [comment]
@jrieken great, thanks!
