### ISSUE TITLE
Request a Portable version of vs code exploration builds

### ISSUE THREAD

**Issue by skotlex** [microsoft/vscode#74608]
I need a portable version, not an installer, to deploy the same environment to multiple people.

https://github.com/microsoft/vscode/issues/73211
I already have the requested record on the issue, but I did not receive an answer.
Because most of the places I work are Windows 7, I need a portable version of an election 4.0.x.

**Comment by kieferrm** [comment]
This is the latest exploration build as an [zip archive](https://az764295.vo.msecnd.net/exploration/7b78242a5f63fd40322ff93e5be2b687fb3778cd/VSCode-win32-x64-1.35.0-exploration.zip) so that you can setup portable mode.
