### ISSUE TITLE
working with visval sterminal

### ISSUE THREAD

**Issue by dalekkrish** [microsoft/vscode#74612]
Issue Type: <b>Performance Issue</b>

when i am working with angular framework i am using shortcut to terminate (ctrl+c) then its showing terminate yes or now option but irrespective of my choice it terminating my terminal

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.14393

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
