### ISSUE TITLE
Popup Error Messages Persist

### ISSUE THREAD

**Issue by gray-sanborn-work** [microsoft/vscode#74618]
Issue Type: <b>Bug</b>

1. Open the Source Control tab.
2. Type a message > 72 characters.
3. An alert message appears.
4. Remove text in message.

* Expected result: alert disappears.
* Actual result: alert persists until another alert is activated (ex: feedback popup)

VS Code version: Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:18:06.502Z)
OS version: Darwin x64 18.6.0

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
markdown-toc|Ala|1.5.6
solargraph|cas|0.19.6
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.26.0
gitlens|eam|9.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-yarn|gam|1.6.0
vscode-pull-request-github|Git|0.7.0
rainbow-csv|mec|1.1.1
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.311
vscode-docker|Pet|0.6.2
polacode|pnp|0.3.2
ruby|reb|0.22.3
java|red|0.45.0
markdown-preview-enhanced|shd|0.4.0
code-spell-checker|str|1.7.12
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-icons|vsc|8.7.0
vim|vsc|1.8.1

(1 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
This is a duplicate of #74617

**Comment by gray-sanborn-work** [comment]
@lramos15 Ah, beat by 3 minutes. I'll close this as a duplicate.
