### ISSUE TITLE
Inform the user when all merge heads are fixed

### ISSUE THREAD

**Issue by GeorgeWL** [microsoft/vscode#74613]
I cannot imagine any time where after merging a file you wouldn't want to know that it's still got merge headers that were missed

It is useful for me at least to know when I have resolved all conflicts so I save the file and add it to the index. 

On large files I find myself searching the codemap for other conflicts (or doing git diff).

**Comment by roblourens** [comment]
Can you explain exactly what you want to happen? Not sure what you are asking for. A popup message every time I resolve the last conflict would be really annoying. If you try to add the file when it still has merge markers then you will get a warning.

**Comment by GeorgeWL** [comment]
Possibly just a small toast message?

Kind Regards,

George W Langham
