### ISSUE TITLE
Windows Installer has two times a checkbox to launch after installation

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#7461]
The first one is "Launch Code after installation" somewhere before the installation begins
The second one is after the installation and reads "Launch Visual Studio Code - Insiders"

**Comment by joaomoreno** [comment]
Yeah... it's sad, but I'll close as designed. I remember I ended up having to leave both for some strange and exoteric reason.

**Comment by AmadeusW** [comment]
Just came here to create an issue about this annoyance. Launch checkbox should be available only at the end of the wizard. 

Can anyone contribute to development of the install wizard? Or is the installer off limits?

**Comment by joaomoreno** [comment]
It's, unfortunately, off limits.

I'll take another look at it, then, if it bothers more than one person.

**Comment by Tyriar** [comment]
@joaomoreno I want to get off Windows whenever I see it https://github.com/Microsoft/vscode/issues/2795 😉

**Comment by joaomoreno** [comment]
This was **way** more complicated than it should be.
