### ISSUE TITLE
git bash terminal issue

### ISSUE THREAD

**Issue by sourabhpatole** [microsoft/vscode#74619]
Issue Type: <b>Feature Request</b>

when i started terminal there is close immediatly what i do 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Tyriar** [comment]
What's in your settings.json file? Do you get a notification when it happens and does anything show up in the console (Help > toggle developer tools)?
