### ISSUE TITLE
Max length commit message doesn't go away

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#74617]
Issue Type: <b>Bug</b>

The max length commit warning seems to be very slow at updating when typing and moving down, but that's a small grievance. The bug is that upon deleting the extra characters I can only seem to get the commit warning down to 1 characters over 50 in the current line (this should also probably say 1 character, not 1 characters). If I command/ctrl + a and then delete the message doesn't even update despite the box being empty. This warning box also follows me outside of the source control view and into the explorer / debugger forcing me to quit VS Code.

Steps:
1. Enter a commit message larger than 50 characters
2. Select all via cmd/ctrl + a and delete the commit message.

The warning will still be there with no way to get rid of it.

VS Code version: Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:18:06.502Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by mjbvz** [comment]
This seems to be caused by d70b0f1ecdebc58935fdcfcc88877725ec88f691, specifically this line: https://github.com/microsoft/vscode/blob/31777858c754a3d204116b59ae0da16615c09cbc/src/vs/base/browser/ui/inputbox/inputBox.ts#L436

/cc @sbatten

**Comment by sbatten** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Good catch!
