### ISSUE TITLE
editor.wordWrap: "off"  does not work for HTML

### ISSUE THREAD

**Issue by mickeyjohn** [microsoft/vscode#74615]
Hi,
The editor.wordWrap: "off" does not turn off the auto wrapping on HTML. I tried this setting off for both in the Settings and the user settings file but when pressing Ctrl-Shift-I html text within a p tag still wrapped. If I turn off default format for html, It will not wrap the html content as expected. 
Thanks.

**Comment by octref** [comment]
You are probably looking for `"html.format.wrapLineLength"`.

**Comment by mickeyjohn** [comment]
Hi @octref,
I tried settings "html.format.wrapLineLength" =0 or 9999999999999. "Wrap attributes": "auto". "WordWrap": "off". These still wrap the content of a tag after pressing Ctrl+Alt+I. How do you suggest  that worked at your testing ?
Thanks.

**Comment by octref** [comment]
After setting

```
  "html.format.enable": true,
  "html.format.wrapLineLength": 2000,
```

It doesn't wrap for me.

Maybe you have other formatter extensions installed? Can you show me the output of `code --list-extensions`?

**Comment by mickeyjohn** [comment]
Hi @octref,

Now after checking all against WorkSpace settings, I found that the cause was "Wrap Line Length": 160. It is weird that the settings for user did not overwrite this. Now it works properly.

```
code --list-extensions:
Angular.ng-template
christian-kohler.npm-intellisense
ecmel.vscode-html-css
emmanuelbeziat.vscode-great-icons
humao.rest-client
johnstoncode.svn-scm
MikeBovenlander.formate
mikeburgh.xml-format
ms-vscode.cpptools
msjsdiag.debugger-for-chrome
rintoj.json-organizer
ritwickdey.LiveServer
sanderledegen.angular-follow-selector
WallabyJs.quokka-vscode
yzhang.markdown-all-in-one
```

Thank you very much.

**Comment by octref** [comment]
> settings for user did not overwrite this

https://code.visualstudio.com/docs/getstarted/settings
User setting is global and workspace setting always take precedence.

**Comment by mickeyjohn** [comment]
Thanks @octref. Now I learned that. :)
