### ISSUE TITLE
Syntax Color customization does not work

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#74610]
I have a fresh VSCode install and just want to customize my syntax highlighting formatting. 

> First switch to the color theme to customize and use the editor.tokenColorCustomizations settings.
> Changes are applied live to your VS Code instance and no refreshing or reloading is necessary.

I've switched to the color theme to customize (`Dark+`) and added a simple
```
    "editor.tokenColorCustomizations": {
        "[Dark+]": {
            "editor.background": "#ffffff"
        }
    },
```
to my settgins to test, and nothing changes.
Do I have to do anything more that's not specified in the docs?

[My settings](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e#file-settings-json-L14-L19)

**Comment by usernamehw** [comment]
`editor.background` - is a property of `workbench.colorCustomizations`.

`Dark+` color theme name is `[Default Dark+]` - there's autocomplete available.

```json
"workbench.colorCustomizations": {
    "[Default Dark+]": {
        "editor.background": "#ffffff"
    },
}
```

**Comment by inwardmovement** [comment]
That wasn't that intuitive to guess, I guess I missed something in the docs... thank you very much!

**Comment by usernamehw** [comment]
They have autocomplete

![Screenshot (124)](https://user-images.githubusercontent.com/9638156/58634814-e6f5a480-82f4-11e9-94f6-194aa7bbc17b.png)

![Screenshot (125)](https://user-images.githubusercontent.com/9638156/58634819-ea892b80-82f4-11e9-92df-51cabb2c8419.png)

If the docs are not intuitive - then you should create issues there: https://github.com/Microsoft/vscode-docs
