### ISSUE TITLE
Backspace only removing one line in a selection of manyu

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/vscode#74625]
Issue Type: <b>Bug</b>

So, you know how you can select an entire column of text using alt + shift? And then you can manipulate the entire column, moving it forward, moving it back, tabbing it around, and so forth. Super useful! However, it looks like, for some reason, when an entire column is selected, and the backspace is used, only the top line is backspaced, even though the entire column should be backspaced (since the entire column is cursor'd). 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (16.28GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
vscode-markdownlint|Dav|0.26.0
docs-article-templates|doc|0.2.2
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.5
docs-preview|doc|0.3.19
docs-yaml|doc|0.2.1
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.12

</details>

here's a gif demonstrating the behavior: 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/32783170/58649044-fb6b7a00-82bf-11e9-98d5-079ca9d65702.gif)

**Comment by kieferrm** [comment]
@MashaMSFT can you enabled the following in your user settings:
```json
"editor.renderWhitespace": "all"
```
I wonder if there is a spaces/tab issue between the lines.

**Comment by MashaMSFT** [comment]
Hi @kieferrm, i think i did it: 
![image](https://user-images.githubusercontent.com/32783170/58671358-3f2da600-82f7-11e9-974b-65f9ff783611.png)

However, the issue persists :( 

Thanks!

**Comment by kieferrm** [comment]
Yes, that won't remove the problem but it shows what characters the whitespace left of your cursors is made of. Can you add a screenshot large enough so that it shows the rendered whitespace?

**Comment by MashaMSFT** [comment]
![image](https://user-images.githubusercontent.com/32783170/58674119-36db6800-8303-11e9-8d70-402a2e07bea2.png)

**Comment by alexandrudima** [comment]
@MashaMSFT I think you have an extension that is binding backspace to some other command. Can you please search of backspace in the keybindings editor (Ctrl+K Ctrl+S). Does this reproduce when you disable extensions?

**Comment by MashaMSFT** [comment]
![image](https://user-images.githubusercontent.com/32783170/62719591-27d8fc00-b9bd-11e9-99fc-07ee9b53853a.png)

interesting... the behavior does NOT reproduce after disabling all extensions... I did some more testing and found that the behavior is caused by the docs authoring pack. Let me forward this information to the owners of the extension :) thank you for your help! I think we can consider this issue closed, unless you have some ideas for how to circumvent this? thanks!

**Comment by alexandrudima** [comment]
@MashaMSFT Yes, you can remove their keybinding (all keybindings are 100% editable in VS Code). Right click on the last binding and choose remove.
