### ISSUE TITLE
Vscode seems to have problems with big folders

### ISSUE THREAD

**Issue by pelos6** [microsoft/vscode#74626]
Issue Type: <b>Bug</b>

I am facing a similar issue than https://github.com/microsoft/vscode/issues/74291 but a bit different.
In my case there is not relation with uppercase characters as you can see on the screenshot.
My folder is a big one whith more than 853 files and 51 folders.
![errorExploradorVisualStudioCode](https://user-images.githubusercontent.com/3807895/58649121-950c4900-830b-11e9-8f61-417633621c99.png)
I must say thet this only happen sometimes most time at first minutes of use of the program.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.96GB (4.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
spellright|ban|3.0.38
unique-lines|bib|1.0.0
better-toml|bun|0.3.2
plsql|cas|0.0.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.4.0
permute-lines|ear|0.0.10
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
githd|hui|2.1.0
vscode-insertdatestring|jsy|2.2.4
vscode-language-pack-es|MS-|1.34.2
vscode-jsp|pth|0.0.2
java|red|0.45.0
code-settings-sync|Sha|3.2.9
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
vscode-icons|vsc|8.7.0

</details>

**Comment by Tyriar** [comment]
What's the problem?

**Comment by pelos6** [comment]
The problem is that sometimes the folder called content seems to be empty but this folder contains more than 850 files and 15 subfolders.
![errorExploradorVisualStudioCodeConsole](https://user-images.githubusercontent.com/3807895/58684463-9d4e9d80-8378-11e9-8dfd-62dc09e264d6.png)
I have to update explorer to see the files ans subfolders of this folder
![errorExploradorVisualStudioCodeCorrecto1](https://user-images.githubusercontent.com/3807895/58684476-a8093280-8378-11e9-9959-cca528f5d717.png)
This doesn`t happen whith other folders

**Comment by Tyriar** [comment]
Is that really Windows 10.0.17134 (1803)? The taskbar looks like Vista?

**Comment by pelos6** [comment]
I use visual studio code mostly in two pc,  one whith Windows 10 and the other one whith Windows 7.
In both whith the same behavior

**Comment by IAmStrong** [comment]
I have the same issue starting from the update a few month ago when the Navigator has been completely refactored. It's a nightmare, in my case the folder doesn't open even after hitting the refresh button.
macOS Mojave 10.14.5

**Comment by IAmStrong** [comment]
Is this issue gonna be ever fixed?
