### ISSUE TITLE
Introduce a file scheme to open files in diff mode

### ISSUE THREAD

**Issue by jepetty** [microsoft/vscode#74627]
If a language provider has files in its result set that should be opened in 'diff mode', there's currently no way to specify this in the URI - the command "vscode.diff" must be executed, which isn't sufficient when all that can be returned is a list of URIs.

This can be accomplished with support for a new scheme, "compare", that provides the files to be opened in the left and right side in the URI query. Then, the editor service will be able to handle those URIs appropriately rather than relying upon an explicit command.

@bpasero @jrieken

**Comment by gjsjohnmurray** [comment]
Interesting idea.

If it's decided to add another "built-in" schema I'd suggest the team also establishes a naming convention (e.g. a "vscode-" prefix) to use for this and future additions. Then we extension developers will know to avoid that range when picking our own schema names (e.g. for a `FileSystemProvider`)

**Comment by bpasero** [comment]
As discussed, this makes sense to me. Feel free to start a PR on this and I can chime in for help. I am not sure about the scheme we should pick in the end, I feel @gjsjohnmurray brings up a valid point that we should maybe prefix reserved schemes.

**Comment by homitc** [comment]
How will peek definition be handled if we provide a file with the new compare scheme? Will the peek window contain a diff view or will the diff view only be presented if the action is go to def? I worry the peek window may become cluttered, but I would want vscode to honor when someone sends a compare scheme. Ideally I'd be able to tell when the action was a peek or go to def action and choose in my implementation of provideDefinition to not send a compare scheme if it's a peek action, but currently I'm not aware of a way to differentiate peek and go to def.

**Comment by bpasero** [comment]
The peek view does not support a side-by-side editor to my knowledge.

**Comment by bpasero** [comment]
@jepetty are you still interested in providing a PR?
