### ISSUE TITLE
colorPresentation LSP request doesn't handle line numbers properly

### ISSUE THREAD

**Issue by Trzyipolkostkicukru** [microsoft/vscode#74622]
Issue Type: <b>Bug</b>

If you use color picker multiple times without closing it, the range parameter for textDocument/colorPresentation doesn't have the line number updated, which breaks your code if the color thingie is more than a single line long. Problem isn't only with the CSS files.

How to reproduce:
- open CSS file
- write this:
```
h1 {
  color: rgb(0,
  0,255);
}
thisIsSomeCodeThatIDontWantDestroyed {
}
```
- hover over rgb
- change color three times (without leaving the picker)

Result:
```
h1 {
  color: rgb(68, 68, 184)ntDestroyed {
}
```

Expected result:
```
h1 {
  color: rgb(68, 68, 184);
}
thisIsSomeCodeThatIDontWantDestroyed {
}
```

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.1
vscode-back-forward-button|gri|0.1.2
errorlens|Phi|1.1.3
rust|rus|0.6.1
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.2.3

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@rebornix The problem is that the color picker reuses the same color range after applying the new color. It has to make a new request to the documentColor provider to get a the new range. Resusing the range works if the range has the same length and no new lines.
