### ISSUE TITLE
Terminal Issue - Does not show the current directory

### ISSUE THREAD

**Issue by thediveshsoni** [microsoft/vscode#74624]
On opening terminal it does not show the path initially but once i execute a command it shows the directory.

![Screenshot (131)](https://user-images.githubusercontent.com/33605250/58648498-787e0a00-8327-11e9-8f2b-82a15f0c7902.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
