### ISSUE TITLE
hyphen symbol is not recognized as a word delimiter

### ISSUE THREAD

**Issue by iliazlobin** [microsoft/vscode#74621]
When I specify the setting `"editor.wordSeparators": "-",` in the settings.json, I expect the part of a compound word (*one-large-word*) to be selected. But it doesn't happen. It's probably a bug. Everything works fine in the not insider version - 1.34.0.

VSCode Version where the bug has been found: **1.35.0-insider**

**Comment by rebornix** [comment]
@iliazlobin can you share more details for better troubleshooting

* which platform you are on
* can you search `word separators` in Settings editor to see if there is workspace setting override it

I didn't reproduce this issue in latest Insiders on both macOS and Windows.
