### ISSUE TITLE
Terminal color error in Windows

### ISSUE THREAD

**Issue by abersheeran** [microsoft/vscode#74631]
- VSCode Version: 1.34.0
- OS Version: Windows10

![image](https://user-images.githubusercontent.com/25364828/58652753-dd952800-8346-11e9-8511-0354bfbebfe8.png)

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/25364828/58652912-3369d000-8347-11e9-802f-bf6ad418ebd3.png)

![image](https://user-images.githubusercontent.com/25364828/58652948-45e40980-8347-11e9-9c1f-43686d677c28.png)

When I try WSL, it's still happening.

![image](https://user-images.githubusercontent.com/25364828/58653052-7c218900-8347-11e9-8bed-459393f97fff.png)

![image](https://user-images.githubusercontent.com/25364828/58653077-8774b480-8347-11e9-9208-e244404ae16c.png)

This happened after my Windows10 update.

![image](https://user-images.githubusercontent.com/25364828/58653223-d1f63100-8347-11e9-8700-890fabfe1ddf.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
