### ISSUE TITLE
Refresh folder button won't work

### ISSUE THREAD

**Issue by softshape** [Microsoft/vscode#7463]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open some folder in VSCode
2. Create some file in this folder outside of VSCode (i.e. with Windows Explorer)
3. Hit refresh button.

You won't see this new file until you restart VSCode.

**Comment by bpasero** [comment]
This does not reproduce easily so it needs a lot more information about your setup.

![editors](https://cloud.githubusercontent.com/assets/900690/15924761/145f9624-2e34-11e6-8888-3b8c47bc45ef.gif)

Maybe you also record a video :)?

**Comment by softshape** [comment]
Just tested this and can't reproduce either. It seems like the bug appears randomly after VSCode is running for some time (2-3 days in my case).

**Comment by bpasero** [comment]
@softshape if that happens again please open the chrome developer console to see if something gets logged. You can open it from the help menu. Lets reopen when you have more info.
