### ISSUE TITLE
File rename warning box can get stuck on screen

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74638]
Issue Type: <b>Bug</b>

**Repo**
1. Create a file called `x.ts`
1. Create a file caled `y.ts`
1. Rename `y.ts` to `x.ts` in the explorer
1. See the red warning popup about not being able to rename
1. Hit enter while the red warning is showing

**Bug**
Rename stops, but the box is still showing

![Screen Shot 2019-05-30 at 1 20 12 PM](https://user-images.githubusercontent.com/12821956/58661835-b0f8f600-82dd-11e9-94dc-50ae55179ba1.png)

VS Code version: Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:18:06.502Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|

|Item|Value|
|---|---|
|Remote|SSH: az-box1|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.79GB (5.48GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Same with source control warning
![image](https://user-images.githubusercontent.com/641685/58662028-3f2da600-82f7-11e9-983f-c303cad4b2ab.png)

**Comment by gjsjohnmurray** [comment]
#74617

**Comment by mjbvz** [comment]
Same root cause in code as #74617, but keeping this issue around as it should be verified separately

**Comment by sbatten** [comment]
resolved with fix for #74617
