### ISSUE TITLE
Comment thread range doesn't follow the comment edit box

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#74641]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.35.0-insider (e9c50663154c369a06355ce752b447af5b580dc3, 2019-05-30T05:19:53.372Z)
OS version: Windows_NT x64 10.0.17763

**Repro:**
Using comment-sample extension from vscode-extension-samples on latest VSCode Insiders:
1. Open a document.
2. Start a new comment thread, input some text in the comment edit box, do not create the thread yet.
3. Edit the text in the document above the comment thread, add some lines. This will move the comment edit box down as expected, it flows along with the text in the document.
4. Now create the comment thread.

**Expected:**
The comment thread is created in its current location, where the comment edit box is.

**Actual:**
The comment thread is created in the location where the user clicked on the comment `[*]` button first, it doesn't follow the comment edit box.

**Comment by IlyaBiryukov** [comment]
cc @rebornix

**Comment by rebornix** [comment]
Fixed already.

**Comment by alexr00** [comment]
It looks like that commit is in a separate branch and isn't in master. I can also still repro the original issue.
