### ISSUE TITLE
CompletionItem.FilterText cannot begin with @, otherwise broken suggestions on re-invoke

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode#74648]
Issue Type: <b>Bug</b>

1. Update the common VSCode [completion-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) to return the following completion:
```JavaScript
const brokenCompletion = new vscode.CompletionItem('@key');
brokenCompletion.filterText = '@key';
```
and
```JavaScript
// return all completion items as array
return [
	simpleCompletion,
	snippetCompletion,
	commitCharacterCompletion,
	commandCompletion,
	brokenCompletion
];
```

2. Run the extension
3. Ctrl + n to create an untitled document
4. Type @
5. Invoke completion, notice `@key` is included
6. Dismiss completion
7. Add a `k` so you now have `@k` with your cursor at the end of the `k`.
8. Invoke completion

You get no suggestions available.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (15.96GB free)|
|Process Argv|--folder-uri file:///c%3A/GitHub/Razor.VSCode|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
csharp|ms-|1.19.1
debugger-for-chrome|msj|4.11.3

</details>

**Comment by NTaylorMullen** [comment]
It looks like `@` symbols also bust the way commits occur. Meaning if you try changing the filter text to `key` and then commit it you get `@@key` instead of `@key`

**Comment by jrieken** [comment]
Using `filterText` without `range` is error prone because the range defaults to the word range and that usually doesn't include characters like `@` etc. The range defines what portion of the text is selected to be compared with the `filterText`

**Comment by NTaylorMullen** [comment]
> Using `filterText` without `range` is error prone because the range defaults to the word range and that usually doesn't include characters like `@` etc.

`range` is not part of the language server protocol spec though.

**Comment by jrieken** [comment]
> range is not part of the language server protocol spec though.

It surely is but @dbaeumer might be using `textEdit#range` (which we have deprecated in favour of just `range` in vscode.d.ts-land)

**Comment by NTaylorMullen** [comment]
> It surely is

Wait whaa, is it in a newer revision that hasn't been published yet?



> @dbaeumer might be using `textEdit#range` (which we have deprecated in favour of just `range` in vscode.d.ts-land)

If I were to take a dependency on `textEdit#range` for completion items (my language server is in C# which aligns with the latest [LSP protocol here](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)) I'd probably risk getting broken in the near future no?

**Comment by jrieken** [comment]
> I'd probably risk getting broken in the near future no?

No. Deprecated != broken, `textEdit#range` is still supported and will be

**Comment by jrieken** [comment]
> I'd probably risk getting broken in the near future no?

No. Deprecated != broken, `textEdit#range` is still supported and will be

**Comment by NTaylorMullen** [comment]
> No. Deprecated != broken, `textEdit#range` is still supported and will be

I see alright, that's great to know. Going to take a dependency on that then. Lets see how it turns out 😄

**Comment by dbaeumer** [comment]
To clarify: using `textEdit#range` is correct in LSP. We try whenever possible to not break things in the protocol. And if we have to the it will be announced via a client capability.
