### ISSUE TITLE
Tasks documentation for ProblemPattern should explicit mandatory "attributes"

### ISSUE THREAD

**Issue by Oni** [Microsoft/vscode#7464]
- VSCode Version: 1.2.0

When creating a task with a ProblemMatcher and a ProblemPattern, the documentation should explicit the fact that the attributes "file", "line" and "message" are mandatory and must be extracted from the "regexp", otherwise the GUI won't mark the errors or warnings matched by ProblemPattern.

Documentation involved:
https://code.visualstudio.com/Docs/editor/tasks
https://code.visualstudio.com/docs/editor/tasks_appendix

**Comment by dbaeumer** [comment]
Agree.

**Comment by dbaeumer** [comment]
Fixed for June.
