### ISSUE TITLE
Keep multiple search result

### ISSUE THREAD

**Issue by manuelcanepa** [microsoft/vscode#74645]
Like notepad++, tabular results or similar will be great. Sometimes i need to search twice the same string or regex, in big project this is a problem.

### Expected
- Search "A"
- The results will show as a tab in the search bar
- Search "B"
- The results will show as a tab in the search bar
- Clic on "A" results will show the first save result

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/16488
