### ISSUE TITLE
editor.lineHeight or editor.fontSize affects tooltip in editor (screenshot added)

### ISSUE THREAD

**Issue by InFerYes** [Microsoft/vscode#7465]
- VSCode Version: Version 1.2.0
  Commit 809e7b30e928e0c430141b3e6abf1f63aaf55589
  Date 2016-06-06T13:26:59.802Z
  Shell 0.37.6
  Renderer 49.0.2623.75
  Node 5.10.0
- OS Version: Win7 SP1

Steps to Reproduce:
1. Set the editor.lineHeight to 12 in settings.json
2. Set the editor.fontSize to 12 in settings.json
3. Set the editor.fontFamiliy to [ProFontWindows](http://www.tobias-jung.de/seekingprofont/) (may not be necessary)
4. Hover over items in the editor (tested with Javascript)

You may need to fiddle with the lineHeight and fontSize settings if you are using a different font.

[Example 1](http://i.imgur.com/PBBokpf.png)
[Example 2](http://i.imgur.com/gyC7GIe.png)

**Comment by alexandrudima** [comment]
This works as expected now thanks to @joaomoreno 

![image](https://cloud.githubusercontent.com/assets/5047891/24910897/809b0cb6-1ec9-11e7-8067-bb02255808ce.png)
