### ISSUE TITLE
Feature Request: Open Recent Project improvement

### ISSUE THREAD

**Issue by shabbir-dhangot** [microsoft/vscode#74658]
Current Behaviour 
When we opening open recent project its directly opening into current window. So if we want to open it new window we need to open new window and then need to select project. 

Expected Behaviour 
It should ask open project in same window or new window. Open of selecting window is commonly supported by many IDE. eg. Android studio

![image](https://user-images.githubusercontent.com/8267282/58683668-e14e9c00-8392-11e9-8d91-1a9a6cf8005f.png)

**Comment by usernamehw** [comment]
It's possible to use modifier key to open it in the new window. For me it works by pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd>

The input tooltip should say that:

![Screenshot (126)](https://user-images.githubusercontent.com/9638156/58703255-b70bd700-83b0-11e9-97f5-79437733b3d4.png)

**Comment by kieferrm** [comment]
@shabbir-dhangot pls see the previous comment, it correctly describes how it works.

**Comment by shabbir-dhangot** [comment]
@bot. This is not an issue. I have requested for feature. As this most common method when you trying to open new project when another project is in the background. 

Expected behaviour I already written on the question. You can search what other IDE behaviour while open recent. 

This should be open as feature request.
