### ISSUE TITLE
Side Bar with Lists, Checkboxes, Text

### ISSUE THREAD

**Issue by ShMcK** [microsoft/vscode#74656]
Currently, extension authors seem to be limited to TreeViews in the VSCode Side Bar. Correct me if I'm wrong.

Feature Request:
I'm developing an extension that requires **more diverse UI in the Side Bar**. Nothing complicated, just basic:
- lists
- checkboxes
- text (currently limited to a single TreeItem line with no formatting)

Notice that several of these requested items already exist in the side panel of core features which do not share the same limitations of extensions:

- lists in the extension view
![image](https://user-images.githubusercontent.com/4660659/58682466-7d41be80-8325-11e9-9cca-64512fe66824.png)

- checkboxes in the debugger via a webviewlet
![image](https://user-images.githubusercontent.com/4660659/58682376-263be980-8325-11e9-99d1-cd47ce4fe5d0.png)

A Side Bar that can only use TreeView's is extremely limiting. 

Is it possible to add non-TreeView UI to the Side Bar in current extensions? If so, can the documentation be amended in the "Extending Workbench" section to accomodate how? Happy to help contribute docs with some guidance.

If not, can I help contribute to VSCode in any way to help make any of the above functionality possible?

**Comment by kieferrm** [comment]
We only support tree views right now. 

See also https://github.com/microsoft/vscode/issues/46585 and https://github.com/microsoft/vscode/issues/1833.

**Comment by ShMcK** [comment]
I assume this limitation exists for a reason. If not, let me know if there is any way I can contribute to creating a more dynamic Side Bar.
