### ISSUE TITLE
Errno 22

### ISSUE THREAD

**Issue by Fabhi** [microsoft/vscode#74653]
Issue Type: <b>Bug</b>

Can't debug with Python. Getting this output on using F5 key.
C:\Python\python.exe: can't open file '"c:/Users/XXXXX/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py"': [Errno 22] Invalid argument

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.9.0
code-runner|for|0.9.9
python|ms-|2019.5.17517
material-icon-theme|PKi|3.8.0
ayu|tea|0.18.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Pls move this issue to the python extension. Thanks!
