### ISSUE TITLE
Click twice to get cursor from terminal to editor

### ISSUE THREAD

**Issue by kirtangajjar** [Microsoft/vscode#7466]
- VSCode Version: 1.2
- OS Version: Ubuntu 16.04

We need to click twice to get our cursor from integrated terminal to the file we are editing

Steps to Reproduce:

1. Open a file to edit
2. Open embedded terminal
3. Click on terminal and type something.
4. Click on editor(Just above terminal)

If you are editing any *.c file, and you click on opening round bracket, then it will highlight the closing bracket, however the cursor will neither be on terminal nor on editor pane. 

5. Click on editor pane again.

Now the cursor will be on editor pane.
![workspace 1_002](https://cloud.githubusercontent.com/assets/8456197/15923763/609fb114-2e4c-11e6-8be6-2b8531b82927.png)

**Comment by vicodinchik** [comment]
Same issue in the OS X version

**Comment by mdickin** [comment]
Same thing in Windows. Here's a screen capture
![terminal focus](https://cloud.githubusercontent.com/assets/16612667/15931662/506a550c-2e1e-11e6-8bc2-f77e867f8d7a.gif)

Note that after selecting the text in the editor, I started hitting "a" repeatedly. Only the first appears in the console.

**Comment by Tyriar** [comment]
Fixed in the latest insiders already :sparkles:

Thanks a lot for the gif @mdickin, made it really easy to repro.

**Comment by Tyriar** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/7684
