### ISSUE TITLE
Quoting error : error 22 when running Python script

### ISSUE THREAD

**Issue by MagixInTheAir** [microsoft/vscode#74666]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Full details are here : https://stackoverflow.com/questions/56386110

**Comment by kieferrm** [comment]
Pls move the issue to the Python extension. Thanks!
