### ISSUE TITLE
[Bug] Searching and replacing something in all files once for all cause VSCode to freeze

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#74669]
Before, in reference to the issues following: #30874, #39929, #45309 and #45690. But unfortunately, it still has these problem, but in case of replacing something in **all files once for all**. 

- VSCode Version: 1.35.0-insider 5c65d9b
- OS Version: Arch Linux Budgie 64bits Linux Kernel 5.1.5

Steps to Reproduce:

1. Download the small package [16.zip](https://github.com/microsoft/vscode/files/3240565/16.zip);
2. Extract and open the folder with VSCode;
3. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>;
4. Put `^(\s)*$\n` in the search box and enable regex;
5. Leave empty replace box and select to *replace all* once for all.
6. You will receive a warning dialog that VSCode is freezing and must be closed or reopen. 

* Does this issue occur when all extensions are disabled?
Yes

**Comment by roblourens** [comment]
Works fine for me, just takes a few seconds, which is expected since vscode has to open and save lots of files. Do you see some process using high CPU when this happens? Which one?

**Comment by gusbemacbe** [comment]
Hi @roblourens 

Which command for "System Info" so I will attach the file for you?

**Comment by roblourens** [comment]
- Help > Open process explorer
- Look for a process using high cpu, right click to copy

**Comment by gusbemacbe** [comment]
Hello

Before replacing:

```
CPU %	Memory (MB)	pid	Name
0	158	18790	code-insiders main
0	39	18794	     zygote
0	244	18840	         window (16 - Visual Studio Code - Insiders)
0	315	19456	             extensionHost
0	55	21434	                 /opt/visual-studio-code-insiders/code-insiders /opt/visual-studio-code-insiders/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=19456
0	166	21436	                 PHP Language Server
0	71	19457	             watcherService
0	63	20066	             searchService
0	0	21506	             /usr/bin/zsh
0	118	19433	         shared-process
0	95	22032	         window (Process Explorer)
0	103	18826	     gpu-process
0	0	22627	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

After:


![image](https://user-images.githubusercontent.com/2257024/58841219-3f9fa700-863f-11e9-8a2b-c07eabd5f2c4.png)
![image](https://user-images.githubusercontent.com/2257024/58841265-737acc80-863f-11e9-97d7-8d5236b9e160.png)

**Comment by roblourens** [comment]
> You will receive a warning dialog that VSCode is freezing and must be closed or reopen.

Does the dialog give you an option to wait? What happens if you wait for a bit? It might be that it just takes a bit longer than the OS expects a process to be blocked for.

**Comment by gusbemacbe** [comment]
> Does the dialog give you an option to wait? What happens if you wait for a bit? It might be that it just takes a bit longer than the OS expects a process to be blocked for.

Yes, I do. I then click to keep waiting, but I receive again another same dialog, I click again to keep waiting and the same dialog opens.... Infinite loop at the style of battle between Dormannu and Doctor Strange. 

![image](https://user-images.githubusercontent.com/2257024/58842126-3284b700-8643-11e9-90ee-eba1f6115519.png)

**Comment by roblourens** [comment]
Hm, do you see the progress bar at the top of the search view while this is running?

**Comment by gusbemacbe** [comment]
Hi @roblourens 

Yes, I do, but the progress bar always is keeping the same after clicking to keepw waiting 5 or more times.

**Comment by roblourens** [comment]
@sandy081 do you know why this would make the window stop responding when the bulk edit service seems to handle each edit asynchronously? It must be that it's actually stuck somewhere, not that it's just slow to handle lots of edits.

**Comment by gusbemacbe** [comment]
To stop the freeze and the infinite loop and abort the replacing, I had to click `Reopen`. But after clicking `Reopen` or `Close`, when I open VSCode, it opens the cached window with the same folder, it freezes, it keeps replacing and sending me the same dialog. Then I had to open with a new folder to stop the freeze and the infinite loop or to clean the cache and cookie to restore the window.

**Comment by gusbemacbe** [comment]
```bash
System:
  Host: gusbemacbe-hp Kernel: 5.1.5-arch1-2-ARCH x86_64 bits: 64 
  compiler: gcc v: 8.3.0 Desktop: Budgie 10.5 Distro: Arch Linux Linux 
Machine:
  Type: Laptop System: Hewlett-Packard product: HP EliteBook 8460p 
  v: A0001D02 serial: <filter> 
  Mobo: Hewlett-Packard model: 161C v: KBC Version 97.4E serial: <filter> 
  BIOS: Hewlett-Packard v: 68SCF Ver. F.65 date: 04/06/2017 
Battery:
  ID-1: BAT0 charge: 30.3 Wh condition: 30.3/30.3 Wh (100%) 
  model: Hewlett-Packard Primary status: Full 
CPU:
  Topology: Dual Core model: Intel Core i5-2520M bits: 64 type: MT MCP 
  arch: Sandy Bridge rev: 7 L2 cache: 3072 KiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19961 
  Speed: 2993 MHz min/max: 800/3200 MHz Core speeds (MHz): 1: 2993 2: 2993 
  3: 2993 4: 2993 
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  vendor: Hewlett-Packard driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.20.5 driver: intel 
  unloaded: fbdev,modesetting,vesa resolution: 1600x900~60Hz 
  OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 19.0.5 
  direct render: Yes 
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio 
  vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
  Sound Server: ALSA v: k5.1.5-arch1-2-ARCH 
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Hewlett-Packard 
  driver: e1000e v: 3.2.6-k port: 4060 bus ID: 00:19.0 
  IF: enp0s25 state: down mac: <filter> 
  Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi 
  v: kernel port: 4040 bus ID: 24:00.0 
  IF: wlo1 state: up mac: <filter> 
Drives:
  Local Storage: total: 530.98 GiB used: 47.04 GiB (8.9%) 
  ID-1: /dev/sda vendor: Hitachi model: HTS723232A7A364 size: 298.09 GiB 
  ID-2: /dev/sdb vendor: Samsung model: SSD 860 EVO 250GB size: 232.89 GiB 
Partition:
  ID-1: / size: 220.89 GiB used: 13.53 GiB (6.1%) fs: ext4 dev: /dev/sdb2 
  ID-2: /home size: 175.07 GiB used: 31.97 GiB (18.3%) fs: ext4 
  dev: /dev/sda3 
  ID-3: /opt size: 58.42 GiB used: 1.12 GiB (1.9%) fs: ext4 dev: /dev/sda2 
  ID-4: swap-1 size: 7.45 GiB used: 71.8 MiB (0.9%) fs: swap dev: /dev/sdb1 
Sensors:
  System Temperatures: cpu: 67.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 217 Uptime: 4h 59m Memory: 7.70 GiB used: 2.20 GiB (28.5%) 
  Init: systemd Compilers: gcc: 8.3.0 clang: 8.0.0 Shell: zsh v: 5.7.1 
  inxi: 3.0.34

**Comment by sandy081** [comment]
Is it possible to get the profile to know where it is getting stuck?

**Comment by gusbemacbe** [comment]
Are you asking to me, @sandy081?

**Comment by sandy081** [comment]
@gusbemacbe Yes. Sorry as I am not clear.

**Comment by gusbemacbe** [comment]
Then, no, I can not open anything while it is stuck, therefore, I take a profile. I have to open the profile before I begin to replace.

**Comment by roblourens** [comment]
I still can't reproduce it, sorry
