### ISSUE TITLE
#57803 Terminal bug still happening on 1.34

### ISSUE THREAD

**Issue by SLotman** [microsoft/vscode#74667]
Issue Type: <b>Bug</b>

Just open a new terminal. This is what is shown: https://ibb.co/8N73XDJ

Its the same bug reported here: https://github.com/microsoft/vscode/issues/57803

Hitting 'enter' will 'fix' the display. Setting "terminal.integrated.windowsEnableConpty" to true or false doesn't change anything.

VSCode 1.34. Windows 10 Home, 1809. 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.43GB free)|
|Process Argv|C:\Mygames\game|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
