### ISSUE TITLE
Command enablement not checked when assigning keybinding

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74670]
* contribute command that uses enablement
* assign a keybinding, via package.json ~~or as user~~
* :bug: enablement isn't honoured

**Comment by jrieken** [comment]
When users configure keybindings it that we allow them to change preconditions as well, e.g rename requires an editable document so I don't plan to have a different strategy for contributed commands

**Comment by alexr00** [comment]
I don't see the nice "Command 'Hello World' is  not enabled in the current context." info toast when I try the keybinding though. I only see that message when I try to run it from the command palette. The command correctly doesn't run when not enabled though.

**Comment by jrieken** [comment]
Yeah, that's the design. Keybindings don't show messages
