### ISSUE TITLE
Switching from multiple to single column layout shows the wrong editor

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/vscode#74677]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Switch to a multiple editor layout, open a file in each group (anything other than Single causes the bug)
2. Focus the first group
3. Switch to Single Column Editor Layout

**Expected behaviour:**
VSCode switches to showing a single group and the editor from the first group is shown

**Actual behaviour:**
VSCode switches to showing a single group and the editor from the last group is shown even though the tab bar shows the correct editor to be active.

![2019-05-31_153946](https://user-images.githubusercontent.com/16286572/58706345-744efc80-83ba-11e9-8e4a-a37e2bc9e60d.png)

![2019-05-31_153955](https://user-images.githubusercontent.com/16286572/58706343-744efc80-83ba-11e9-87c7-c2733b9c2833.png)

Tested with extensions disabled, bug still manifests.
Tested with 1.34.0 on the stable branch, bug doesn't manifest.

VS Code version: Code - Insiders 1.35.0-insider (2737cde4facc8411982862742f5c6cd3dabef323, 2019-05-31T05:20:32.786Z)
OS version: Windows_NT x64 10.0.18908

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/74548

**Comment by kamenminkov** [comment]
Sorry for the dupe, I searched a bit, but couldn't find that one.
