### ISSUE TITLE
Extensions gone after opening vscode as root

### ISSUE THREAD

**Issue by rafaelyates** [microsoft/vscode#74673]
Issue Type: <b>Bug</b>

Basically from terminal:

- sudo code /etc/hosts
- code ~/workspace/my_project

It seems that the extensions are still installed, but they are no longer listed.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
Don't launch vscode with sudo, open it work `code /etc/hosts` and elevate during a save

<img width="449" alt="Screen Shot 2019-05-31 at 9 47 56 AM" src="https://user-images.githubusercontent.com/2193314/58721210-2f5ea200-8389-11e9-90a6-57de98498f55.png">
