### ISSUE TITLE
Editor to support mutiple language mode

### ISSUE THREAD

**Issue by nicholas-george** [microsoft/vscode#74678]
Was wondering if it will be possible to support mutiple language modes in the editor.
The use case seems real, at least to me.  I write javascript. But in the middle  one wil be creating css strings as literals or html code to insert. Since the editor is on javscript mode, much errors happen. If only I can mark a portion of my code and say 'follow CSS rules for this' or follow HTML rules for this. 

Thanx. Just a thought

**Comment by kieferrm** [comment]
Support for nested languages is up to the individual language extensions. There is no generic support and there is no planned at this time. In your example, you can have a look at  https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components.
