### ISSUE TITLE
Javascript sintax highlighting stopped due to for with &&

### ISSUE THREAD

**Issue by dpierangeli** [Microsoft/vscode#7467]
- VSCode Version: 1.2.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open the attached js file with VSCode
2. The sintax hilighting stops at the line "for (var i=0; i<n && !ok; i++)"

No extensions installed

![cattura](https://cloud.githubusercontent.com/assets/9047951/15925940/97fd0372-2e39-11e6-84a8-3ab566fead3d.PNG)

[jvs.zip](https://github.com/Microsoft/vscode/files/306612/jvs.zip)

**Comment by dpierangeli** [comment]
Also in this case, if needed i can attach the source.

![cattura2](https://cloud.githubusercontent.com/assets/9047951/15926152/ac07dc4c-2e3a-11e6-8569-e1146f817177.PNG)

**Comment by alexandrudima** [comment]
```
if (this.PListCells.length<value && (!this.ListList || !this.DelayedUpdate))
{
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/15971317/cb56bee8-2f38-11e6-8e39-fff6e925745f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#182
