### ISSUE TITLE
Behaviour of selection to next find match using command

### ISSUE THREAD

**Issue by mohdabdulraheem7u** [microsoft/vscode#74674]
![Expected](https://user-images.githubusercontent.com/43752866/58703090-2c81a280-83c5-11e9-9ad0-78c85f1e9152.JPG)   Excected
![Actual](https://user-images.githubusercontent.com/43752866/58703089-2c81a280-83c5-11e9-80ac-39d5cc85c141.JPG)   Actual
![TaskBar](https://user-images.githubusercontent.com/43752866/59339871-93d31700-8d22-11e9-8d40-bce4652a96d0.jpg)

**Trying:** I want to check for the next to find a match.
It is happening, by selecting from the taskbar
But I if do by using the Keyboard shortcuts command, which is shown just beside the taskbar.
Keyboard shortcuts: Command CTRL+D is not giving as output as expected.
I have attached the files in for better understanding.

**Comment by kieferrm** [comment]
I can't reproduce the behavior you show. Pls provide a concrete sample with instructions. Thanks!
