### ISSUE TITLE
Allow to drag the application window from the activity bar

### ISSUE THREAD

**Issue by Azarlak** [microsoft/vscode#74680]
There's a lot of empty space on the Activity Bar(for me at least). It would be nice if we could use that empty space to drag the window around, in addition to the Menu Bar, especially given that the Activity Bar is a bit wider than the Menu Bar and thus easier/faster to click accurately.

I imagine that it would work something like the sidebar on the Opera browser, which exhibits this behavior.

[Here's a short video demonstration, in case my explanation was unclear](https://www.youtube.com/watch?v=jLdbeCl4y8M)

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

EDIT: Added technical information as generated by the built-in issue reporter.

**Comment by isidorn** [comment]
this is a fair feature request
fyi @bpasero @sbatten

**Comment by FloEdelmann** [comment]
@isidorn Why is this considered out of scope?

I use [KDE](https://kde.org/), where you can drag windows from all empty areas by default (see https://github.com/kde/breeze/blob/v5.18.4.1/kstyle/breeze.kcfg#L137-L145, the other options are "Title bar only" and "Title bar and toolbars").

VS Code feels out of place, and I often try to drag the window from the empty space in the tab bar just to recognize that I have to use the window title bar.

In my opinion, the window should be draggable from these areas:

1. Empty space in editor's tab bar (or top editor groups' tab bars)
2. The heading of the explorer
3. Empty space in the sidebar

Related issues: #12377, #43154
