### ISSUE TITLE
Add more spacing between branch and sync icons in SCM viewlet

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#74681]
The spacing between the branch and sync icons in the SCM viewlet appears too crammed and does not match the spacing in the status bar. We should at the minimum increase the margins a big:

![image](https://user-images.githubusercontent.com/35271042/58718438-59f92c80-8382-11e9-871c-136fdbae92c6.png)

FYI @joaomoreno @bpasero. This also came up in the icon user study.

**Comment by bpasero** [comment]
Not sure statusbar and tree actions should have consistent spacing, what is the rationale?

**Comment by misolori** [comment]
Sorry, I didn’t mean that they should have the exact same spacing, more that we should increase the spacing like in the status bar. Right now it’s so crammed that it looks like one big button. I think adding a few pixels (~4px) would make it look clearer and more visually appealing.

**Comment by bpasero** [comment]
@misolori got it. I am not sure how straight forward this change would be as the component that contains these actions is our generic action bar used everywhere.

**Comment by misolori** [comment]
I should be able to do this by adding `.scm-viewlet .monaco-list-row > .scm-provider > .monaco-action-bar .action-label` to [scmViewlet.css](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/scm/browser/media/scmViewlet.css). I'll also adjust the font-size for the icons since the label text is smaller here (11px). 

Preview:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/35271042/66351978-8f56ed80-e913-11e9-8b1b-6b77402c8b0a.png">

**Comment by misolori** [comment]
This is now updated to add more spacing:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/35271042/66670714-4357c180-ec0f-11e9-871c-28988f6de22a.png">

And when it gets narrow:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/35271042/66670722-494da280-ec0f-11e9-8dcf-58cc71f23274.png">

**Comment by Tyriar** [comment]
Truncation doesn't appear to work properly anymore:

![image](https://user-images.githubusercontent.com/2193314/67814277-e0648800-fa60-11e9-921b-0de4ec3b900e.png)

**Comment by misolori** [comment]
Let's try this again 😄 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/35271042/67874343-05eda200-faf2-11e9-9f69-71e26131e699.png">

**Comment by misolori** [comment]
I think that's how text overflow + flex box works. In the first screenshot, the sync icon doesn't have any additional text to ellipse so it will ellipse the icon (because the box is now smaller). In the second screenshot, there is text so then it ellipsis that text (notice how the branch text is now ellipsed as well since there is less space in the parent container.

**Comment by misolori** [comment]
It's also worth noting that this behaves the same way in Stable.
