### ISSUE TITLE
Please re-open #73805

### ISSUE THREAD

**Issue by aakash-shah** [microsoft/vscode#74683]
Please re-open #73805 - I just added additional information to that issue.

Per https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md, I am creating a new issue for this since this issue was closed out.

Also, it would be helpful if the system sent a second follow up before an issue is closed, or allowing the creator to re-open the issue.

Thanks!

**Comment by Tyriar** [comment]
It's only been 13 minutes and Zurich is off for the weekend, a notification is waiting for Monday.

**Comment by aakash-shah** [comment]
@Tyriar Hello!  To clarify, if I add an update to a closed ticket, does the MS representative assigned to the issue get notified to help re-open it?  If so, I wasn't aware of that and will wait a few days in the future before requesting that the issue be re-opened.  It may also help to clarify this at https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md.

Thanks!

**Comment by Tyriar** [comment]
@aakash-shah anyone who has interacted with the issue on GitHub will get a notification when a comment is made, even if it's closed (unless they have unsubscribed).

**Comment by aakash-shah** [comment]
Ahh thanks for clarifying that!
