### ISSUE TITLE
Default shortcut for open file and folder on Linux

### ISSUE THREAD

**Issue by ShangxuanWu** [microsoft/vscode#74687]
Hi,

On Mac, we are using the same keyboard shortcut for opening file and folders.
On Linux, we are not.

Can we combine the two shortcuts on Linux?

**Comment by kieferrm** [comment]
@ShangxuanWu We are using native dialogs for opening files and folders. Only on macOS the dialog can deal with files or folders while on Windows and Linux the dialog can open either one or the other.
