### ISSUE TITLE
Current Nightly Version?

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#7468]
How can we find out what's the current Nightly version? I'm pretty sure there's a Nightly, newer than the one I have, but mine VCCode doesn't want to download it (and I recall seeing an issue where someone's OS X system wasn't downloading the nightly's for some reason).

Would be nice if a version number was posted (ie. Version 1.3.0-insider (1.3.0-insider); 2481a7dad82f8e8d105c5329b4b6f20e15e9b27c; 2016-06-08T02:01:49.534Z)

**Comment by bpasero** [comment]
There is a newer insiders build but we have issues signing it for Mac so the nightly of today is not released for Mac yet. Stay tuned 👍

**Comment by jtsom** [comment]
Excellent. (And I just realized the number in the About dialog is the commit...) Is there a particular time that the nightly is put out? Looking at the list of commits, the nightly seems randomly in the list.

Thanks!

**Comment by bpasero** [comment]
Currently it runs once per day automated 7 AM Zurich time. If it fails there is no nightly (depending on test failures or signing issues).

**Comment by joaomoreno** [comment]
```
https://vscode-update.azurewebsites.net/api/update/win32/insider/latest
```
