### ISSUE TITLE
CSS Selectors in media queries completion

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#74682]
When I type a selector outside a media query completion works perfectly but when I want to type a selector inside a media query. Completion doesn't work lie this

![ua](https://user-images.githubusercontent.com/42807112/58719507-2218d600-83d0-11e9-9e9a-0c7abfd0751e.jpeg)

Here it must complete the word to `div` but it doesn't work.

**Comment by octref** [comment]
That's where you would type an selector, not properties, so there's no property completion.

**Comment by minkir014** [comment]
Okay. I know but where is the completion for CSS selectors like "div". Re-see the title of the issue "CSS Selectors"

**Comment by octref** [comment]
@minkir014 Please don't update closed issue. Open new feature requests.
