### ISSUE TITLE
Start-Transcript in Integrated Terminal does not capture all output

### ISSUE THREAD

**Issue by johnwildes** [microsoft/vscode#74698]
Issue Type: <b>Bug</b>

I have a powershell profile configured on my workstation.  When I launch PowerShell Core 6.2.1 outside of VSCode it loads my profile.  Part of this profile is start-transcript.  When this runs in the PowerShell cmd window outside of VSCode all output is logged to the transcript as expected.

When the same profile is loaded in the VS integrated terminal window, the only thing that gets logged are the commands typed at the prompt and none of the output.  

In this specific case I was running Terraform operations, and wanted to review previous histories, and found that it was not saving it in the transcript.  If I run Terraform operations from the normal PowerShell cmd window, all that output is saved. 

I've attached the PowerShell transcript file, as well as a graphical output of what should have been in that file from the integrated terminal window

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
[PowerShell_transcript.LOKI.RqwwF6bX.20190531153831.txt](https://github.com/microsoft/vscode/files/3242847/PowerShell_transcript.LOKI.RqwwF6bX.20190531153831.txt)
![TranscriptOutputIssue-2019-05-31_15-56-25](https://user-images.githubusercontent.com/1375512/58734329-cee95800-83bc-11e9-85ec-b705aece0476.png)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-toc|cil|1.5.0
vscode-markdownlint|Dav|0.27.0
docs-article-templates|doc|0.2.2
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.5
docs-preview|doc|0.3.19
docs-yaml|doc|0.2.1
gitlens|eam|9.8.1
vsc-material-theme|Equ|2.9.0
terraform|mau|1.3.11
azure-pipelines|ms-|1.152.0
vscode-azureappservice|ms-|0.14.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-azureterraform|ms-|0.2.3
vscode-cosmosdb|ms-|0.10.2
vscode-logicapps|ms-|0.1.22
vscode-kubernetes-tools|ms-|1.0.0
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
Go|ms-|0.10.2
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.6
vscode-typescript-tslint-plugin|ms-|1.1.0
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.6.0
vscode-docker|Pet|0.6.2
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.12
azure-iot-toolkit|vsc|2.7.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@johnwildes 

> I've attached the PowerShell transcript file, as well as a graphical output of what should have been in that file from the integrated terminal window

Can you pls attach the files? Thanks!

**Comment by Tyriar** [comment]
Also does the terminal dropdown say "powershell" or "PowerShell Integrated Console"?

**Comment by johnwildes** [comment]
@Tyriar the terminal says "pwsh" 

@kieferrm Sorry I attached these files last week but then Github blocked my account as "spam" 😂 let me know if they don't attach again

![TranscriptOutputIssue-2019-05-31_15-56-25](https://user-images.githubusercontent.com/1375512/58891284-d86f0a80-86b1-11e9-8725-18b501dae331.png)

[PowerShell_transcript.LOKI.RqwwF6bX.20190531153831.txt](https://github.com/microsoft/vscode/files/3253164/PowerShell_transcript.LOKI.RqwwF6bX.20190531153831.txt)

**Comment by johnwildes** [comment]
What you see above (in the graphic) is the ouptut in the terminal window of VSCODE, and WHAT SHOULD BE in the attached transcript file, but is not.

**Comment by Tyriar** [comment]
@TylerLeonhardt any idea what's happening here? The command output isn't showing up in pwsh

**Comment by TylerLeonhardt** [comment]
@johnwildes I’d like to get a smaller repro as I don’t have terraform expertise. Can you see if this behavior repros with an in-box native utility… like maybe `where.exe` or `net.exe`?

**Comment by johnwildes** [comment]
@TylerLeonhardt I've attached a screenshot that shows running a terraform init, and none of the output is there. In the same shell I ran a `net use` a `dir` and a `get-module -listavailable | more` , all output from those is correctly captured.  

<img width="837" alt="GithubIssue74698-pwshoutputissues-2019-07-11_16-25-47" src="https://user-images.githubusercontent.com/1375512/61086825-854b4e80-a3f9-11e9-942e-08fa994b4a41.png">

[PowerShell_transcript.LOKI.t3+zhJgk.20190711162201.txt](https://github.com/microsoft/vscode/files/3384043/PowerShell_transcript.LOKI.t3%2BzhJgk.20190711162201.txt)

**Comment by johnwildes** [comment]
Sorry, should have just clicked comment...re-opening.

**Comment by johnwildes** [comment]
@TylerLeonhardt to answer your question, it DOES NOT repro with an inbox utility.  That information seems to output correctly.

**Comment by johnwildes** [comment]
@TylerLeonhardt attached here is a transcript run in the actual Powershell Window, and the terraform commands and output are captured along with the native cmds.

[PowerShell_transcript.LOKI.v_LQueBg.20190711162220.txt](https://github.com/microsoft/vscode/files/3384060/PowerShell_transcript.LOKI.v_LQueBg.20190711162220.txt)

**Comment by johnwildes** [comment]
For repro sake I did this on another workstation.  With VSCODE v1.36.1, same powershell setup, same TF version.  
Repro is same result.   Most of the TF output doesn't come into the transcript.

![ENTDesktopOutput-GithubIssue-74698-2019-07-11_17-48-11](https://user-images.githubusercontent.com/1375512/61090495-80d86300-a404-11e9-90a7-1ee4a03558cd.png)


[PowerShell_transcript.ENTDESKTOP.Q8rvgzqT.20190711174704.txt](https://github.com/microsoft/vscode/files/3384261/PowerShell_transcript.ENTDESKTOP.Q8rvgzqT.20190711174704.txt)

**Comment by TylerLeonhardt** [comment]
For testing purposes, instead of using `Start-Transcript`, what happens if you pipe the output to a file?

Try:

```pwsh
terraform init | Out-File foo.txt
terraform init > foo.txt
```

**Comment by johnwildes** [comment]
@TylerLeonhardt attached are three output files from running 

terraform init | out-file output.txt
terraform plan | out-file output2.txt
terraform plan > output3.txt

This is the content in output.txt.
[output2.txt](https://github.com/microsoft/vscode/files/3388762/output2.txt)
[output3.txt](https://github.com/microsoft/vscode/files/3388763/output3.txt)
[output.txt](https://github.com/microsoft/vscode/files/3388764/output.txt)


-----

```
[0m[1mInitializing modules...[0m
- module.HubUS
- module.SpokeEUR
- module.SpokeASIA
- module.SpokeEMEA

[0m[1mInitializing provider plugins...[0m

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
```
Below is what appears in the terminal window

![image](https://user-images.githubusercontent.com/1375512/61171583-635be400-a53f-11e9-949f-c9c43629f997.png)

**Comment by johnwildes** [comment]
@TylerLeonhardt let me know if you need anything more from me.

**Comment by Tyriar** [comment]
I don't think the vscode team can action this, the root cause is likely either powershell or [conpty](https://github.com/microsoft/terminal)

**Comment by miniGweek** [comment]
> Issue Type: Bug
> 
> I have a powershell profile configured on my workstation. When I launch PowerShell Core 6.2.1 outside of VSCode it loads my profile. Part of this profile is start-transcript. When this runs in the PowerShell cmd window outside of VSCode all output is logged to the transcript as expected.
> 
> When the same profile is loaded in the VS integrated terminal window, the only thing that gets logged are the commands typed at the prompt and none of the output.
> 
> In this specific case I was running Terraform operations, and wanted to review previous histories, and found that it was not saving it in the transcript. If I run Terraform operations from the normal PowerShell cmd window, all that output is saved.
> 
> I've attached the PowerShell transcript file, as well as a graphical output of what should have been in that file from the integrated terminal window
> 
> VS Code version: Code 1.34.0 ([a622c65](https://github.com/microsoft/vscode/commit/a622c65b2c713c890fcf4fbf07cf34049d5fe758), 2019-05-15T21:59:37.030Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info
> Extensions (31)

Event though this ticket is closed, I am trying to achieve exactly the same thing. i want to log all my terraform commands and their outputs for traceability on my local workstation. Did you figure it out how to get it to work ?

**Comment by TylerLeonhardt** [comment]
Sorry for the delay! You could also try:

```
terraform init *> foo.txt
# or
terraform init *>&1 | Out-String | Out-File foo.txt
```

Though I suspect a similar result...

**Comment by miniGweek** [comment]
@TylerLeonhardt 
Ok So I came up with an alternative ... using the Tee-Object and Powershell profiles..
Here's what I coded up in last couple of hours... hope it helps
fzf.vim
https://github.com/miniGweek/windows-terraform-logger
