### ISSUE TITLE
editor.occurrencesHighlight based on file type

### ISSUE THREAD

**Issue by rightaway** [microsoft/vscode#74694]
It should be possible to configure which file types editor.occurrencesHighlight should be active on. For example if you don't want it in markdown files or text files (where it's less useful) but do want it in others.

There should also be a command in the command palette for toggling this on and off in the current file (or globally).

**Comment by usernamehw** [comment]
```json
"[markdown]": {
    "editor.occurrencesHighlight": false,
},
```
