### ISSUE TITLE
Terminal progress new line for progress when line too long

### ISSUE THREAD

**Issue by ChristopherKiss** [microsoft/vscode#74695]
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Run a task with progress and make the terminal width small so that the full line would wrap
2. Observe that a new line is created for every step

![image](https://user-images.githubusercontent.com/24984762/58733296-815e0100-8437-11e9-9b3a-3f3b489e0bcf.png)

3. Make the terminal width larger so that the lines would not wrap
4. Run the command again
5. Observe that the progress correctly overwrites the current line

![image](https://user-images.githubusercontent.com/24984762/58733301-858a1e80-8437-11e9-8a54-91f90672c433.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
I think this is working as expected and it's either conpty or the program misbehaving.
