### ISSUE TITLE
Prevent editor pane from scrolling so far 

### ISSUE THREAD

**Issue by FlorianLoch** [Microsoft/vscode#7469]
I often use my trackpad to scroll down to the end of document - and I am used to editors that scroll until the last line is at the bottom of the editor, which I think makes sense and is more useful than scrolling until the last line of the document is at the top of the editor. What do others think of this?

<img width="392" alt="screen shot 2016-06-09 at 13 09 33" src="https://cloud.githubusercontent.com/assets/5587805/15927706/7127250c-2e43-11e6-8792-f94d3a0251b7.png">

- VSCode Version: 1.2
- OS Version: OSX 10.11

Steps to Reproduce:

1. Open a document
2. Scroll to the end

**Comment by alexandrudima** [comment]
@FlorianLoch There is a "hidden" setting `editor.scrollBeyondLastLine` that you can set to `false`.

**Comment by FlorianLoch** [comment]
@alexandrudima Great! Thanks for the hint!
