### ISSUE TITLE
Provide a way for the user to assign layering priorities on highlighters

### ISSUE THREAD

**Issue by Geobert** [microsoft/vscode#74692]
When using let's say https://marketplace.visualstudio.com/items?itemName=evgeniypeshkov.syntax-highlighter and https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight

We have a conflict one is overriding the other. 

Can we have a priority setting to defined which one override the others?

**Comment by kieferrm** [comment]
@Geobert 'we' meaning the user?

**Comment by Geobert** [comment]
Yes, the user :)
