### ISSUE TITLE
Support object types for `TreeItem.contextValue`

### ISSUE THREAD

**Issue by dave-bartolomeo** [microsoft/vscode#74699]
This is a duplicate of #46236. That issue has been auto-closed, apparently due to inactivity, but I have more information about the scenario and am willing to offer a pull request.

I have an extension that contributes a treeview to the Test Explorer container. Each `TreeItem` represents a test, and different tests need different context menu items enabled based on properties of those tests. For example, some tests have expected output that can be compared with the actual output in a diff view, and some don't. Failed tests need an option to accept the new output as expected, but passed tests don't. The node for a test needs different options from the node for a test suite.

Today, I can sort of make this work by giving each `TreeItem` a `contextValue` string with a space-separated list of tags, and using regular expressions in my `when` condition to look for the interesting tags or lack thereof.

What I'd prefer is to specify an object as the value for `contextValue`, and be able to access individual properties of that object using `viewItem.propName`, similar to the existing support for `context.propName` that already exists.

Proposed changes:
- Change the type of `TreeItem.contextValue` to `any` (or some suitably restricted type that allows an object type)
- Within a `when` condition, `viewItem.propName` accesses the property named `propName` on `TreeItem.contextValue`, if `TreeItem.contextValue` is an object type.

If this sounds like a reasonable feature, I'm willing to contribute the PR to implement it.

**Comment by sandy081** [comment]
This can be accepted as PR.

**Comment by dave-bartolomeo** [comment]
Great. I'll try to put something together over the next few days.

**Comment by urbanfly** [comment]
@dave-bartolomeo was the PR more difficult than you had assumed? is there any reason why this feature doesn't exist yet?
