### ISSUE TITLE
vscode Remote Development

### ISSUE THREAD

**Issue by 836056404** [microsoft/vscode#74709]
![image](https://user-images.githubusercontent.com/30099739/58743196-a6666a00-845f-11e9-836e-23a57ed808a7.png)

**Comment by supperchong** [comment]
settings 
![image](https://user-images.githubusercontent.com/26317926/58743282-1a554200-8461-11e9-981e-321e08fda2a3.png)

**Comment by 836056404** [comment]
Thank you
