### ISSUE TITLE
TERMINAL

### ISSUE THREAD

**Issue by KienKse** [microsoft/vscode#74701]
Issue Type: <b>Bug</b>

"terminal.integrated.cwd": "C:\\Program Files\\Git\\bin\\bash"
 I cant open my terminal integrated its broked

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.98GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.43
terminal|for|0.0.10
mssql|ms-|1.6.0
vetur|oct|0.21.0
salesforcedx-vscode-core|sal|45.15.1
salesforcedx-vscode-visualforce|sal|45.15.1
markdown-preview-enhanced|shd|0.4.0
vscode-autohotkey|sle|0.2.2
autoimport|ste|1.5.3
vscode-icons|vsc|8.7.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
cwd is current working directory, that should be a folder. You probably want switch shells, try F1 and search for "default shell"
