### ISSUE TITLE
Save file even without file changes - so that Nodemon, Gulp, Chokidar and other file watchers restart

### ISSUE THREAD

**Issue by Arrow7000** [Microsoft/vscode#7470]
It would be very useful to have VSCode save a file even when no file changes have taken place, because when an error occurs, Nodemon crashes and doesn't restart the app until a save has taken place. 

So even if you want to restart the server without making any file changes - sometimes bugs happen due to a runtime event, it's not always an obvious bug in your code, you have to make some kind of unnecessary change, like typing a space before being able to save, which is annoying.

**Comment by chrisdchristo** [comment]
+1

Needed for gulp watching.

**Comment by Izhaki** [comment]
+1

Need for chokidar-cli used in npm scripts

**Comment by bpasero** [comment]
Verify: you can save files that are not dirty and their mtime/atime changes on disk. E.g. install an external node watcher and verify it fires.

**Comment by PunchyRascal** [comment]
Well that's basically what my setup is (I use https://github.com/guard/guard) and it does not detect any change and so does not run any tests. Just now I tried to save file without any changes and there is no change to any of the dates either on remote or local drive.

**Comment by bpasero** [comment]
@PunchyRascal you can verify this tomorrow from our insider build when it lands. 

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by PunchyRascal** [comment]
Work perfectly with
 - VSCode Version: Code - Insiders 1.6.0-insider (0a0bfedbc64ba8fd0c3e6f42befb200a0b36ffb0, 2016-09-20T06:11:03.267Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by bpasero** [comment]
@PunchyRascal thanks, marking as verified.
