### ISSUE TITLE
remote-ssh: Add ability to open a file from from the embedded terminal using `code <filename>`

### ISSUE THREAD

**Issue by marccampbell** [microsoft/vscode#74704]
When using VSCode Remote SSH functionality, the embedded terminal is connected to a session on the server over SSH. It would be a great feature to be able to navigate to any other directory on the server, and open a file in the current editor using the code CLI.

For example, if I'm in a project named "web", but then, using the embedded terminal window, if I `code /etc/hosts`, it should open a new editor tab in my current window with the hosts file.

**Comment by supperchong** [comment]
you can use  `code-insiders`
