### ISSUE TITLE
Mac remote smoketest failures

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74703]
**Repo**
1. Run the `--remote` smoke tests on mac

**Bug**

I'm seeing the following failures that are unique to `--remote`

```
  1) Data Migration: This test MUST run before releasing by providing the --stable-build command line argument
       verifies that 'hot exit' works for dirty files:
     Error: Timeout: get elements 'div[aria-label="Quick Picker"] .monaco-tree-rows.show-twisties .monaco-tree-row .quick-open-entry .label-name' after 20 seconds.
      at /Users/matb/projects/vscode/test/smoke/out/vscode/code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  3) Running Code
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[aria-label="vscode-smoketest-check. Press enter for extension details."] .extension li[class='action-item'] .extension-action.install' after 20 seconds.
      at /Users/matb/projects/vscode/test/smoke/out/vscode/code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  4) Running Code
       Multiroot
         shows results from all folders:
     Error: Timeout: get elements 'div[aria-label="Quick Picker"] .monaco-tree-rows.show-twisties .monaco-tree-row .quick-open-entry .label-name' after 20 seconds.
      at /Users/matb/projects/vscode/test/smoke/out/vscode/code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  5) Running Code
       Localization
         "before all" hook:
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at /Users/matb/projects/vscode/test/smoke/out/vscode/code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
```

From my quick investigation into these:

1. This seems to be caused by quick open not finding a file when triggered quickly?
2. Is #74702. Also happens locally
3.  Not sure. Is the extension already installed before this test is triggered perhaps?
4. Looks like the same issues a 1
5. Also not sure about this one, but it seems like it could be related to 3

Adding @chrmarti for quick open / quick input, @sandy081 for the extension issue, and @dbaeumer for the language pack issue

**Comment by dbaeumer** [comment]
@aeschli can you shed some light onto how the --remote smoke test works

**Comment by aeschli** [comment]
Fixed the remote smoke tests:
- run against sources (`yarn smoketest --remote`) works on all platforms
- run against a build ('yarn smoketest --remote --build locationOBuild`:
    - works on Linux and Window, debug tests fail on Mac: https://github.com/microsoft/vscode/issues/74884
   - issue with find in files in the multiroot tests: workaround commited, opened 
https://github.com/microsoft/vscode/issues/74875

**Comment by aeschli** [comment]
Test failures on Mac was a problem with a process lurking around.

**Comment by aeschli** [comment]
Only remaining issue is #74875. Workaround is pushed.
Closing.
