### ISSUE TITLE
Save highlighted code as snippet

### ISSUE THREAD

**Issue by Trevinlc1997** [microsoft/vscode#74711]
My idea was a simpler way to working with snippets. When you highlight a piece a code you should be able to go into the command pallet and have an option that says "Save as code snippet". Which would open a menu to enter the name for the snippet.  (The snippet would be associated with what ever language was used for the file.)

Then you can quickly access your new snippet with "Insert Snippet".

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/26706
