### ISSUE TITLE
Drag and drop TypeScript file does not move associated .js and .map file

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#7471]
- VSCode Version: 1.2.0
- OS Version: MacOSX current

Steps to Reproduce:
1. Drag drop typescript file from one folder to another
2. The old location still holds the corresponding .js and .map files. they don't get moved (or deleted) and start to appear in the tree view even if .js file display is disabled.

I think they should either be moved or deleted from the old location. Now it requires laborious process of deleting 2 files for each drag drop.

**Comment by dbaeumer** [comment]
Implementing this needs to consider the outDir property of the tsconfig.json file.

**Comment by mjbvz** [comment]
Closing this as a feature that would fall under file nesting: #6328

An extension would be the best implementer of this sort of functionality currently
