### ISSUE TITLE
find with Regular expression. the result is wrong.

### ISSUE THREAD

**Issue by JunjieShii** [microsoft/vscode#74715]
find with "\d*" in 
10.243.30.10
10.243.30.102
10.243.30.103
10.243.30.104
10.243.30.105
10.243.30.106
10.243.30.107
10.243.30.108
10.243.30.109
10.243.30.110
10.243.30.111
10.243.30.112
10.243.30.114
10.243.30.117
10.243.30.118
10.243.30.119
10.243.30.12
10.243.30.120
10.243.30.121
10.243.30.122
10.243.30.123
10.243.30.124
10.243.30.125
10.243.30.126
the result is wrong。

**Comment by rebornix** [comment]
Verifiers: we don't support displaying zero-length search result in the editor right now so even though `\d*` should match every boundary of non-digit characters, we don't show them as search results.

**Comment by JunjieShii** [comment]
I still think this is incorrect，Beacause it can not display results that "\d+" can search.

**Comment by rebornix** [comment]
@JunjieShii I already pushed a fix which can display all matched numbers, for example, searching in `10.243.30.10` will give you `10`, `243`, `30` and `10`.
