### ISSUE TITLE
VSCode Saves The File Endlessly

### ISSUE THREAD

**Issue by litopjos** [microsoft/vscode#74720]
- VSCode Version:
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

-OS: Windows 10

Steps to Reproduce:

1. Open a .css file and make a minor change.
2. Save the file.

Note VSCode endlessly saving the file. The only way I can stop it is to close the window containing the file.

Further notes:
- It doesnt happen for every file, but its happens more often when saving a css file.

- I have already disabled all extensions to no effect.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@bpasero any idea?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by litopjos** [comment]
Thank you, Benjamin, for replying.

I got rid of the problem by re-installing vscode.  Here is my current working version:

Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

________________________________
