### ISSUE TITLE
Markdown preview does not show <iframe>

### ISSUE THREAD

**Issue by tchaffee** [microsoft/vscode#74727]
Issue Type: <b>Bug</b>

Create a new file and save it with an `.md` extension.

Add a valid <iframe> tag such as:

```
<iframe width="100%" height="300" src="https://jsfiddle.net/tchaffee/L4h60y79/embedded/js/" allowfullscreen="allowfullscreen" frameborder="0"></iframe>
```

You will see a warning about not showing non-secure content. 

Change the Markdown preview security settings to allow non-secure content.

The warning remains and the preview is still blank.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-50-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3459)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.27GB (0.61GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
cucumber|ste|0.11.5
code-spell-checker|str|1.7.12
vscode-wakatime|Wak|2.1.2

</details>

**Comment by mjbvz** [comment]
You need to full disable the markdown preview's security settings if you wish iframes to be displayed

<img width="738" alt="Screen Shot 2019-06-03 at 12 08 38 AM" src="https://user-images.githubusercontent.com/12821956/58782534-c139fb00-8593-11e9-8fc0-e206cee6eaa9.png">

**Comment by tchaffee** [comment]
That does not work. The iframe is still not displayed in the Markdown Preview.

**Comment by mjbvz** [comment]
![Screen Shot 2019-06-03 at 11 45 03 AM](https://user-images.githubusercontent.com/12821956/58826214-0b9f9400-85f5-11e9-8d89-b18b694b3d6e.png)

**Comment by tchaffee** [comment]
@mjbvz It's not working for me. Any ideas what I'm doing differently from you? Could it be a version difference with VS Code?
