### ISSUE TITLE
CS0579 - (wrongly flagged) duplicate attribute

### ISSUE THREAD

**Issue by ron-b** [microsoft/vscode#74729]
Issue Type: <b>Bug</b>

On a dotnet core console application, I've got both obj/Debug and obj/Release folders (since I've published it as well) - all the attributes under MyProjectName.AssemblyInfo.cs under release are flagged as duplicate, for example:
Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute (CS0579) [MyProjectName]

I suspect it mixed it up with the debug file, though I'm not sure.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-pull-request-github|Git|0.7.0
csharp|ms-|1.19.1
team|ms-|1.149.2

</details>

**Comment by mjbvz** [comment]
Please file this against the C# extension

**Comment by ron-b** [comment]
Found this issue for OmniSharp: OmniSharp/omnisharp-vscode#3050
