### ISSUE TITLE
Quickopen search for an absolute path (\ or C:\) fails with non-file scheme uris

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#74726]
Issue Type: <b>Bug</b>

Here is the error you will see
```
\[UriError\]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
```

Here is the offending code:
https://github.com/Microsoft/vscode/blob/f41d86384917ab177313d4126860c45de8b9c254/src/vs/workbench/contrib/search/browser/openFileHandler.ts#L190-L194

On line 193 it is creating a new uri, but with the unsanitized input.

//cc @roblourens 

VS Code version: Code - Insiders 1.35.0-insider (0284236851a94b116f468345f6e98688a737015d, 2019-05-31T21:32:42.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Not sure what you are trying exactly. Is this in a remote window? Searching with an /absolute path in remote works fine for me, and we don't have a scenario where a remote is the windows platform.

In this case does it work with `C:/`?

**Comment by eamodio** [comment]
I saw the issue with RemoteHub -- when I tried to search for a file with a leading `\` (I was making sure my search worked regardless of which slash was used).

**Comment by roblourens** [comment]
You mean `/` right?

**Comment by eamodio** [comment]
No `\` -- because that takes it down the "absolute" code path

See here
![image](https://user-images.githubusercontent.com/641685/58820585-fa5c8480-8600-11e9-936c-24df3f06f10b.png)

**Comment by roblourens** [comment]
Huh, I didn't know that `\` could start absolute paths on windows

**Comment by roblourens** [comment]
I think this works now. I think it was fixed in uri.ts. Let me know if I am not doing it right.

![image](https://user-images.githubusercontent.com/323878/64464152-becbcd80-d0bb-11e9-806e-59660f3d4bda.png)

**Comment by eamodio** [comment]
Yup, looks good now -- thanks!
