### ISSUE TITLE
Function Outline highlight function in the code window

### ISSUE THREAD

**Issue by ebmarquez** [microsoft/vscode#74725]
Feature Request: 
I'll have multiple functions collapsed and at the time I still have to search for where the function is on the main window.  I would like to see the function name get highlighted so I can quickly identify where it is on the main page.  I hope this makes sense.  Image included showing what I'm talking about.

![image](https://user-images.githubusercontent.com/15785107/58752713-97d08080-8468-11e9-9601-5cb5e6a347ff.png)

**Comment by mjbvz** [comment]
@ebmarquez The editor breadcrumbs show this information:

<img width="280" alt="Screen Shot 2019-06-03 at 12 13 39 AM" src="https://user-images.githubusercontent.com/12821956/58782857-766cb300-8594-11e9-8f0a-e1dfb6ebc376.png">

Enable them with `"breadcrumbs.enabled": true`

Assigning @jrieken for tracking the current cursor position in the outline view too

**Comment by jrieken** [comment]
> Assigning @jrieken for tracking the current cursor position in the outline view too

There is "Follow Cursor" for that...
 
<img width="367" alt="Screenshot 2019-06-03 at 09 15 39" src="https://user-images.githubusercontent.com/1794099/58783009-37644f00-85e0-11e9-9d21-cbf297490598.png">

**Comment by jrieken** [comment]
anything else needed here?
