### ISSUE TITLE
Pasting whole line does not replace selection

### ISSUE THREAD

**Issue by Mudassar045** [microsoft/vscode#74722]
- VSCode Version: 1.34.0
- OS Version:  Windows 8.1 Pro (Windows_NT ia32 6.3.9600) and Windows 10 Pro

Steps to Reproduce:

1. copy or cut a line using CTRL+C or CTRL+X from current cursor without selecting text, paste/replace with selected text using CTRL+V, it will not replace the selected text but paste the copied/cut line with new line.
2. copy or cut a line using CTRL + CTRL+X, paste inside ( ), it will not paste/replace inside the braces.  

Does this issue occur when all extensions are disabled?: Yes

Check out below my github repository for detailed problem and solution suggestion.

[Github/Mudassar045](https://github.com/Mudassar045/learningvscode)

**Comment by byehack** [comment]
yeah. it is really a bug. for me too and this happened
