### ISSUE TITLE
Automatic installation of plugin fails on Fedora due to incorrect Linux cli (apt-get vs dnf)

### ISSUE THREAD

**Issue by mrummuka** [microsoft/vscode#74738]
Issue Type: <b>Bug</b>

Install Visual Studio Code to Fedora.
Start editing python source
after a while, a popup "Install CTAGs support" is shown
Accept installation => Terminal opens with 
"sudo apt-get install exuberant-ctags"
bash: sudo apt-get install exuberant-ctags: command not found...

Problem: Fedora doesn't use apt-get. Fedora uses DNF. The installation method(s) should be distro specific or at least identify which installation method is currently in use.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.9-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2584)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (2.82GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.4.0
beautify|Hoo|1.5.0
language-julia|jul|0.11.6
restructuredtext|lex|109.0.0
python|ms-|2019.5.17517
vscode-docker|Pet|0.6.2
bash-beautify|sha|0.1.1
shellcheck|tim|0.6.0

</details>

**Comment by kieferrm** [comment]
This comes from an extension. It's not part of VS Code out-of-the-box. Given you explanation, I guess the python extension generates the popup and implements the installation. Please move the issue over there. Thanks a ton!
