### ISSUE TITLE
Downloads broken on code.visualstudio.com (All Links)

### ISSUE THREAD

**Issue by tom-corwin** [microsoft/vscode#74732]
Download links on code.visualstudio.com are broken.

Affected links:

  - https://update.code.visualstudio.com/latest/win32-x64-user/stable
  - https://update.code.visualstudio.com/latest/win32-x64/stable
  - https://update.code.visualstudio.com/latest/win32-x64-archive/stable
  - https://update.code.visualstudio.com/latest/linux-deb-x64/stable
  - https://update.code.visualstudio.com/latest/linux-rpm-x64/stable
  - https://update.code.visualstudio.com/latest/linux-x64/stable
  - https://update.code.visualstudio.com/latest/darwin/stable

I'm not listing them here, but Insider build downloads are broken also, for all platforms.

**Comment by Toxicable** [comment]
This is also breaking Remote - SSH
```
> Downloading with wget
> https://update.code.visualstudio.com/commit:94f7de61ece171f4390ece488a220d22cbb0fddd/server-linux-x64/insider: 2019-06-02 16:21:10 ERROR 500: Internal Server Error.
```

**Comment by hiraqdev** [comment]
@Toxicable also breaking `Remote - WSL` 

![wslerror](https://user-images.githubusercontent.com/39719575/58757301-3f66b500-8534-11e9-8dcf-80c0ef4c2e2d.PNG)

**Comment by justClouds** [comment]
I can confirm that it breaks Remote-SSH downloading/updating. Same 500 error response.

**Comment by flynnham** [comment]
As an aside, I really hope that this brittleness is removed once Remote goes live. There's no redundancies in place here, it should be checking if a slightly older version of the code is already located on said instances within an expected range.

I can't think of a worse nightmare than having to `vim` my way around WSL or a remote host because there's some third-party issue way out of my control.

**Comment by xxxxx-qin** [comment]
It can download now!

**Comment by hiraqdev** [comment]
It looks like this issue is solved just now.  I've tried to restart my `Insider` with `Remote WSL` enabled , and everything is normal now.  I also trying to some of links mentioned above, and it works now.

**Comment by tom-corwin** [comment]
Then I will close this (unless there's an underlying problem and this should be open for reference). Glad to see everything working normally.

**Comment by tom-corwin** [comment]
If this happens again I'm going to reopen this issue, since I see atleast 5 previous issues with the reliability of the `update.code.visualstudio.com`.
