### ISSUE TITLE
Error: NativeScript CLI not found

### ISSUE THREAD

**Issue by tosho** [Microsoft/vscode#7473]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 16.04 x64
- npm version: 3.9.5
- NodeJS version: 5.11.0

Steps to Reproduce:
1. install official .deb package from 
2. install [NativeScript](https://github.com/NativeScript/nativescript-cli#install-the-nativescript-cli) extension with npm -g i nativescript 

I had the same issue with previous version 1.1 which was installed with Ubuntu's umake tool. I solved the issue with removing VSCode and install it again from Microsoft's .deb package.
version 1.2. bring this problem again. It can't find globally installed nodes modules. I have same issue/error with other extensions.

I don't have this problem with NativeScript extensions on Windows 10.

**Comment by Tyriar** [comment]
What happens exactly and how is this related to vscode? Does vscode not find the CLI, if so what do you do to trigger the error?

**Comment by tosho** [comment]
@Tyriar 
Yes. I think vscode can't find the cli. Those extensions are working great on Windows 10 (same versions - ext+vscode+node+npm).
the NativeScript error appears every time I open vscode or open a project folder.
the ESLint error appears every time I open .js file:
"Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then press Retry."
`http://imgur.com/nHiEAUE`

**Comment by dbaeumer** [comment]
@Tyriar assiging to you because of the deb package mentioning.

**Comment by Tyriar** [comment]
@dbaeumer can you link where eslint is called into that triggers this error in the extension?

**Comment by dbaeumer** [comment]
@tosho if you open a terminal on the same workspace and type eslint --version what do you get ? And what do you see with which eslint. This might be an environment problem as well.

**Comment by tosho** [comment]
@dbaeumer 
`tosho@T440:~$ eslint -v
v2.13.1`

I also have tried to install Color Picker - https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color
which again gives me error - ` [processBridge]: Error: Cannot get npm `
I don't know if it's relative.

**Comment by dbaeumer** [comment]
I am closing this issue since it is fairly old. @tosho if you are still affected by this please ping and I will reopen.

**Comment by fvonberg** [comment]
I had the same issue with nativescript: It works for me, if I start visual code via "code ." from the nativescript app root folder in a terminal.
