### ISSUE TITLE
Can't download Visual Studio Code 2019

### ISSUE THREAD

**Issue by thirst4combat** [microsoft/vscode#74736]
So I heard VS code was the best editor at the moment, however, when I go to download it takes me to the download page only for a split second then redirects me to a blank page that just says not found. I am using google chrome as my browser and I have already tried to download while disabling VPNs. Not sure what to do.

**Comment by Xiaoqii** [comment]
![image](https://user-images.githubusercontent.com/26139504/58757398-8d80b600-853e-11e9-9ea7-0d8897eb2426.png)
Can't download Visual Studio

**Comment by justmao945** [comment]
+1

**Comment by llussy** [comment]
+1

**Comment by justClouds** [comment]
Duplicate of [#74732](https://github.com/microsoft/vscode/issues/74732) and [#74734](https://github.com/microsoft/vscode/issues/74734) and [#74737](https://github.com/microsoft/vscode/issues/74737).

**Comment by jebai0521** [comment]
+1

**Comment by sfdkems4263** [comment]
Having the same issue

**Comment by 372338552** [comment]
+1

**Comment by stephwongwt** [comment]
+1

**Comment by lifanping** [comment]
+1

**Comment by RussellOng95** [comment]
+1

**Comment by SHawnHardy** [comment]
same here

**Comment by llussy** [comment]
Can be downloaded！

**Comment by stephwongwt** [comment]
Can confirm it works now!

**Comment by stephwongwt** [comment]
Can confirm it works now!

**Comment by justmao945** [comment]
Can confirm it works now!
