### ISSUE TITLE
vs code don't show suggestion for variable of type object in typescript.

### ISSUE THREAD

**Issue by tulshidas** [microsoft/vscode#74739]
- VSCode Version:1.34.0
- OS Version:Window 10 Pro

Steps to Reproduce:

1.
```ts
let obj:object = {
    a:100,
    b:"second atribute",
    f:function(x){
        console.log('value:'+x);
    }
};
```
in this case when i write obj.  it don't give suggestion for property of the object.
2.
```ts
let obj = {
    a:100,
    b:"second atribute",
    f:function(x){
        console.log('value:'+x);
    }
};
```
in this case suggestion works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by-design. When you declare that the type is `object`, you have said that it can essentially have any properties, not just the properties listed in the object literal
