### ISSUE TITLE
Linux Deb download Broken

### ISSUE THREAD

**Issue by subodhp** [microsoft/vscode#74737]
https://update.code.visualstudio.com/latest/linux-deb-x64/stable is broken, file is not found.

Please suggest.

**Comment by justClouds** [comment]
Duplicate of [#74732](https://github.com/microsoft/vscode/issues/74732) and [#74734](https://github.com/microsoft/vscode/issues/74734),

**Comment by StijnMaenhaut** [comment]
Same for the macOS download

**Comment by subodhp** [comment]
Closing this, the Debian Deb download is working now.
