### ISSUE TITLE
Terminal having some display issue

### ISSUE THREAD

**Issue by raju-thorat** [microsoft/vscode#74731]
![vs terminal](https://user-images.githubusercontent.com/4756746/58755550-b59ef380-8503-11e9-9118-80a29e42ecfb.PNG)
Issue Type: <b>Bug</b>

Open new terminal.
start typing something

Expected : I should be able to see proper view of terminal.
Actual  : I can see only the command i typed. Everything else is blank.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3

(1 theme extensions excluded)

</details>

**Comment by ozyx** [comment]
I'm having the same issue with latest release on Windows 10.

Problem exists with both cmd shell

![image](https://user-images.githubusercontent.com/9259993/59052751-a5a94b80-8844-11e9-81f2-e878f7851553.png)

... and powershell

![image](https://user-images.githubusercontent.com/9259993/59052788-c1145680-8844-11e9-87e9-32d8219fb1ca.png)

Seems the initial command prompt line is not displaying. After submitting one command the terminal displays as expected.

**Comment by efrees** [comment]
I've had this same issue for several months at least. It appears to depend on the height of the terminal pane when it is first initialized, but is not fixed by resizing the pane without deleting and reinitializing the terminal session. (See gif showing the three different behaviors I see based on height.)
![Code_TerminalDisplayIssue](https://user-images.githubusercontent.com/973319/59365293-f0700b00-8cfd-11e9-804c-fd36d4480b7b.gif)

Commands work fine, but the display is messed up until after submitting the first command.

**Comment by MiroJ** [comment]
I see the same issue. The only thing I want to add is that the prompt path is at the top of the window but hidden above the top edge of the Terminal window. Scrolling it up will show it. 

![Untitled](https://user-images.githubusercontent.com/1686322/59385720-fa603100-8d32-11e9-8bf0-1928e83e43f1.jpg)

It appears that the cursor is 4-5 lines lower than `path>` but no extra spaces are present. The cursor appears to be at the beginning of the line, at the exact position from the beginning of the line.

I start it with Ctrl+`, if that's important for someone.

**Environment info:**
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by didorothy** [comment]
I'm having this issue also. However, I was playing around with settings and it appears that when I turn on "Terminal > Integrated > Enable Latency Mitigation" that the prompt shows up like it should. It does not eliminate the extra blank lines.

I am running PoshGit and making the git status show in my prompt so there may be what the integrated terminal considers latency while PoshGit determines the status.

Hopefully this helps someone.

**Comment by ozyx** [comment]
> 
> 
> I'm having this issue also. However, I was playing around with settings and it appears that when I turn on "Terminal > Integrated > Enable Latency Mitigation" that the prompt shows up like it should. It does not eliminate the extra blank lines.
> 
> I am running PoshGit and making the git status show in my prompt so there may be what the integrated terminal considers latency while PoshGit determines the status.
> 
> Hopefully this helps someone.

Unfortunately this does not fix the issue for me. Maybe it's a fix for a separate issue?

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
