### ISSUE TITLE
VS Code Terminal, g++ malfunctioning, output file .exe not responding, Error message Entry Point Not Found

### ISSUE THREAD

**Issue by BenisonBesra** [microsoft/vscode#74740]
Tools |Version
------|-------
Version of VS Code: |1.34.0 (user setup)
Electron: |3.1.8
Node.js: |10.2.0
V8: |6.6.346.32
OS: |Windows_NT x64 10.0.17134
Extensions: |none (Disable all and checked).
Reproducible: |started coding md, xml, xhtml, html, css, js
Terminal: |Using Git Bash.
Program Language | C++
Error | Entry Point Not Found

#### Expected:
In c++ code , working executable to be generated in the terminal by command <code>g++ beta.cpp -o beta.exe -Wall</code>.
#### Actually saw:
1. beta.exe was generated but it was not executed form the terminal. As though it was ignored.
1. when opened the file beta.exe directly from the folder got an error popup message "Entry Point Not Found". With discription reading [the procedure entry point __gxx_personality_v0 could not be located in the dynamic link library C:\beta\beta.exe].
1. the same c++ code (or simple Hello World program also) when compiled and run from other IDE (like DevC++) it generates the output file (beta.exe) that works just fine.
1. All was fine about one month back but now, don't know what made the git bash go rouge.

#### Images:
1. Extensions disable
![1 Extensions](https://user-images.githubusercontent.com/48669663/58757642-548c1580-852d-11e9-9af9-f23a24359759.png)
1. Terminal Ignore
![2 TerminalIgnore](https://user-images.githubusercontent.com/48669663/58757645-5eae1400-852d-11e9-9e26-bbcbc46b920d.png)
1. Entry Point Not Found
![3 EntryPointNotFound](https://user-images.githubusercontent.com/48669663/58757647-65d52200-852d-11e9-926b-8352e78d9cb5.png)

#### Sample Code Link: https://github.com/BenisonBesra/vscode/blob/master/beta/beta.cpp
```
#include <iostream>
using namespace std;

class beta
{
private:
  /* data */
public:
  beta(/* args */);
  ~beta();
  int display();
};

beta::beta(/* args */)
{
}

beta::~beta()
{
}

int beta::display()
{
  cout<<"Hello"<<endl;
  cout<<"Test for compilation error and run"<<endl;
  return 0;
}

int main()
{
  beta obj;
  obj.display();
  return 0;
}
```

#### Full code + Error Images uploaded at:
https://github.com/BenisonBesra/vscode

#### Note:
1. g++ output generation used to work fine for me before one month in this same process. Now when the output is opened directly from the folder manually it generated Error Saying "Entry Point Not Found". 
1. I changed and tried with the other "terminal.integrated.shell.windows" also but no luck. I tried with the following:-
   * Git Bash
   * PowerShell
   * MinGW installed separately
   * DevC MinGW

#### ToDo
1. One thing left to do i.e. REINSTALL.

**Comment by BenisonBesra** [comment]
Checked in Linux platform.
Observation: The g++ compiler in vscode terminal is working just fine in Ubuntu 18.04.2 LTS.
![Screenshot from 2019-06-20 15-54-50](https://user-images.githubusercontent.com/48669663/59842268-d1175480-9373-11e9-9305-ac6d861fb88c.png)

**Comment by Tyriar** [comment]
I suspect this is some obscure issue relating to winpty, the old backend for windows terminals. Once you're on Windows 10 1903 you'll be able to use conpty which is maintained by the MS console team and we should be able to investigate these sorts of issues.

**Comment by Tyriar** [comment]
My saved reply for winpty issues:

This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
