### ISSUE TITLE
Multi GIT repos per project broken

### ISSUE THREAD

**Issue by smxsm** [microsoft/vscode#74745]
Issue Type: <b>Bug</b>

Open a folder with more than one GIT repositories inside (different GIT repo in a subfolder). Sometimes it works for the first time (if you just setup the project and clone both repos) and the two repos are shown in the SCP view and changes in both repos are recognized. But if you close and reopen the folder/workspace or if you just open an existing folder containing more than one GIT repo, only the base GIT repo is detected and no change in any subrepo is shown. So you cannot switch between repos in the SCP view anymore and you can only commit to the base repo. It also doesn't help to change the settings how sub-repos are detected (auto / folder change,...)
On the console it is working, if you do a `git status` or `git remote -v` in the sub folder, the correct repo is detected, you can commit/push to the different repos via console, but not from VSCode. The **Gitlens** plugin is also working btw., it also shows the different repos - but not the main VSCode GIT SCP view.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.27.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
todo-tree|Gru|0.0.132
vscode-auto-open-markdown-preview|hnw|0.0.4
composer|ika|0.7.1
phpcs|ika|1.0.5
smarty|imp|0.3.0
encdetectjp|ino|0.0.1
intellij-idea-keybindings|k--|0.2.32
changeEncode|lan|0.0.8
VS-code-vagrantfile|mar|0.0.7
terraform|mau|1.3.11
twig-language-2|mbl|0.8.8
gitignore|mic|1.0.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-de|MS-|1.34.2
mssql|ms-|1.6.0
python|ms-|2019.5.17517
azure-account|ms-|0.8.4
php-docblocker|nei|1.8.0
vetur|oct|0.21.0
vscode-phpcbf|per|0.0.8
vscode-docker|Pet|0.6.2
vscode-php-getters-setters|php|1.2.3
polacode|pnp|0.3.2
git-file-history|pom|1.0.1
java|red|0.45.0
yo|sam|0.9.3
code-settings-sync|Sha|3.2.9
language-stylus|sys|1.11.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
vscode-icons|vsc|8.7.0
vuetify-vscode|vue|0.2.0
gitblame|wad|2.7.0
save-and-run|wk-|0.0.21
upload|wuw|0.1.5
linecount|yyc|0.1.7

(1 theme extensions excluded)

</details>

**Comment by smxsm** [comment]
Just checked - the workaround with a ".gitmodules" file [here](https://github.com/microsoft/vscode/issues/37947#issuecomment-460340426) works ...

**Comment by joaomoreno** [comment]
Are the git repos within a top-level git repo?

**Comment by smxsm** [comment]
@joaomoreno Yes, there is one top-level git repo (project root) and another repo in a subfolder. The sub-repo is only recognized if you add a .gitmodules file in the root dir.

**Comment by joaomoreno** [comment]
#37947
