### ISSUE TITLE
tokenColorCustomizations strange mixing behavior

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#74749]
`tokenColorCustomizations` has a strange behavior with colors "mixing" each others, see screen capture bellow:

![vsc_color](https://user-images.githubusercontent.com/9438102/58760824-59f15c00-853d-11e9-81a2-eda6ece52cf9.gif)

What is interfering and how can I prevent it?

[My settings](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e#file-settings-json)

**Comment by usernamehw** [comment]
Take a look at warnings.

**Comment by inwardmovement** [comment]
Ok I managed to find the right synthax, but it was hard (the warnings weren't very precise):
```
"textMateRules": [
        {"scope": "entity.name.tag", "settings": {"foreground": "#8cc3ff"}},
        {"scope": "entity.other.attribute-name", "settings": {"foreground": "#ffc68c"}},
        {"scope": "punctuation.definition.tag", "settings": {"foreground": "#8cc3ff"}},
      ]
```

Thanks again for your help!
