### ISSUE TITLE
Integrated terminal seems to clear at startup

### ISSUE THREAD

**Issue by FuriouZz** [microsoft/vscode#74748]
## Environment

- VSCode Version: 1.34.0
- OS Version: Windows 10

## Problem description

The integrated terminal seems to truncate output. At VSCode startup or Reload Windows, the terminal does not show anything. I got a big blank space. If I pressed "Enter", it outputs something.

![Capture_2019-06-02_13 49 06](https://user-images.githubusercontent.com/1800468/58760818-447c3200-853d-11e9-9eaf-fc95a4e7594e.gif)

The problem seems to be the same with tasks, I got a big blank space but I do not have the output of the task.

![Capture_2019-06-02_13 32 20](https://user-images.githubusercontent.com/1800468/58760655-4c3ad700-853b-11e9-85c7-07b11b095624.gif)

Instead of :

![Capture_2019-06-02_13 32 45](https://user-images.githubusercontent.com/1800468/58760659-552ba880-853b-11e9-89f1-da2ddac824b0.gif)

The result is same with `powershell.exe` and `cmd.exe`. I do not have the problem with `wsl.exe`, exception for the task that did not found `cargo`...different problem I suppose...

## Steps to reproduce

* Set your shell to powershell.exe
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```
* Restart VSCode/Reload VSCode windows and display the terminal

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
