### ISSUE TITLE
Diff is broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7474]
From https://twitter.com/k_cieslak/status/740857901351329793

Insiders build (post 1.2.0)

![bug](https://pbs.twimg.com/media/CkgOVQIVAAEBA70.jpg:large)

Easily reproducible

**Comment by joaomoreno** [comment]
cc @egamma @bpasero

**Comment by joaomoreno** [comment]
@alexandrudima: `git bisect` told me that 13cb5df0ae6c67d03b9248907bf428ff1df8585c seems to be the culprit...

It reproduces about 50% of the times I try, so there's some race condition somewhere... here are the repro steps:

1. Have a modified file in a git repo
2. Open that file in Code
3. Reload the window.
4. Sometimes the file is opened and you won't see the diff decorations in the gutter. If you still see changes, reload the window until you don't see them.

**Comment by alexandrudima** [comment]
Ok, I will look into it

**Comment by alexandrudima** [comment]
@joaomoreno I've tried reloading at least 20 times on both `master` and on the `insider` build from yesterday:
![image](https://cloud.githubusercontent.com/assets/5047891/15935842/15fabf38-2e69-11e6-8317-dd2da8181c80.png)

Can this be mac specific?

**Comment by Krzysztof-Cieslak** [comment]
My screen was from Windows.

**Comment by alexandrudima** [comment]
Ok, I don't know what I did but I ended up reproducing it. Debugging shows that the worker initialization request got cancelled.

**Comment by alexandrudima** [comment]
Steps that work more reliable for me:

Reload followed by quickly pressing `Ctrl+Shift+<` repeatedly before the editor has loaded.

**Comment by joaomoreno** [comment]
Great to know you were able to catch it! 👍
