### ISSUE TITLE
Docstring Tooltip not shown under Python 2 but under Python 3

### ISSUE THREAD

**Issue by Acidham** [microsoft/vscode#74741]
Issue Type: <b>Bug</b>

When I am working under Python 2.7 the docstring tooltip is just showing the method name but not the docstring. When I am working under Python 3.7 it works. 

## Python 2.7
![Screen Shot 2019-06-02 at 09 30 12](https://user-images.githubusercontent.com/17712121/58758309-f86bc600-8519-11e9-8cda-60a5a2d0e4d4.png)

## Python 3.7
![Screen Shot 2019-06-02 at 09 31 46](https://user-images.githubusercontent.com/17712121/58758313-03bef180-851a-11e9-9cf2-1b1388190acb.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 9, 9|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
arepl|alm|1.0.14
vscode-open-file-folder|auc|0.0.4
scratchpads|bue|0.0.7
bracket-pair-colorizer-2|Coe|0.0.28
goto-documentation|cxf|0.0.1
vscode-markdownlint|Dav|0.27.0
todo-tree|Gru|0.0.132
Python-autopep8|him|1.0.2
vscode-auto-open-markdown-preview|hnw|0.0.4
python-coding-conventions|igr|0.0.4
vsc-python-indent|Kev|0.7.0
dotenv|mik|1.0.1
vscode-open-in-git-tower|mor|0.6.0
vscode-duplicate|mrm|1.2.1
python|ms-|2019.5.17517
Go|ms-|0.10.2
reload|nat|0.0.6
autodocstring|njp|0.3.0
vscode-gitignore-generator|pio|1.0.1
material-icon-theme|PKi|3.8.0
vscode-text-tables|Rom|0.1.5
code-settings-sync|Sha|3.2.9
markdown-preview-enhanced|shd|0.4.0
vscode-table-formatter|shu|1.2.1
vscode-workspace-explorer|tom|1.2.1
snippet-creator|vin|0.0.1
vscodeintellicode|Vis|1.1.6
propertylist|zho|0.0.2

(3 theme extensions excluded)

</details>

**Comment by Acidham** [comment]
In the meantime I tried with setting up a python 2.7 virtualenv and now I am receiving following error. Maybe this has something to do with the misbehavior?

`Traceback (most recent call last): File "/Users/jjung/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/sortImports.py", line 11, in <module> import isort.main File "/Users/jjung/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/lib/python/isort/__init__.py", line 26, in <module> from .isort import SortImports # noqa: F401 File "/Users/jjung/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/lib/python/isort/isort.py", line 41, in <module> from .finders import FindersManager File "/Users/jjung/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/lib/python/isort/finders.py", line 35, in <module> from backports.functools_lru_cache import lru_cache ImportError: No module named backports.functools_lru_cache`

**Comment by mjbvz** [comment]
Please file this against the python extension

**Comment by Acidham** [comment]
The error above was thrown by #2022 but I assume this has nothing to do with the my first post.
