### ISSUE TITLE
[json] Allow full glob filtering for fileMatch in json.schemas

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode#74744]
This would be a variation on #44135
Currently in https://github.com/Azure/azure-rest-api-specs/blob/f58c2f349207bda6f5ca4c010dd7f56c38ddb70e/.vscode/settings.json
Any of the example files match both the swagger
```json
        {
            "fileMatch":[
                "/**/specification/*.json"
            ],
            "url":"https://raw.githubusercontent.com/Azure/autorest/master/schema/swagger-extensions.json"
        },
```
and the example file schema
```json
        {
            "fileMatch":[
                "/**/examples/*.json"
            ],
            "url":"https://raw.githubusercontent.com/Azure/autorest/master/schema/example-schema.json"
        },
```
The current matching doesn't allow both schemas to not collide.
Tried some things that should probably be possible if a full glob pattern match would work
```json
        {
            "fileMatch":[
                "/**/specification/*/resource-manager/*/preview/*/*.json",
                "/**/specification/*/resource-manager/*/stable/*/*.json"
            ],
            "url":"https://raw.githubusercontent.com/Azure/autorest/master/schema/swagger-extensions.json"
        },
```
Same issue trying for negation matches with `!` with the current parsing

**Comment by JanChvala** [comment]
We are working with complex structure of JSON files and JSON Schemas in our projests. Without this option it is impossible to map correctly the schemas to correct JSON files without forcing the naming of those files to special suffixes.

**Comment by ssbarnea** [comment]
Any update on this? I am facing the same problem where without more advanced matching patterns is impossible to correctly determine if a file should use one schema or another one.
