### ISSUE TITLE
git stage selected ranges not working with wslgit

### ISSUE THREAD

**Issue by carlolars** [microsoft/vscode#74758]
- VSCode Version: 1.34.0
- OS Version: 10.0.17134
- git.path set to wslgit.exe [andy-5/wslgit](https://github.com/andy-5/wslgit)

Steps to Reproduce:

1. Modify a tracked file.
2. Use 'Stage Selected Ranges'.

Does this issue occur when all extensions are disabled?: Yes

The failure produces this in the git output log:
```
> git update-index --cacheinfo 100644 34d84665cf8b0b17044053c861f3bbbf06590033
 readme.txt
error: option 'cacheinfo' expects <mode>,<sha1>,<path>
usage: git update-index [<options>] [--] [<file>...]

    -q                    continue refresh even when index needs update
... (removed for readability)
    --no-fsmonitor-valid  clear fsmonitor valid bit

/bin/bash: line 1: readme.txt: command not found
```

There is a newline before the _path_ argument causing it to be interpreted as a new command rather than an argument to `git update-index`.  
Sure one could argue that this is a flaw in *wslgit.exe*, that it can't handle a newline in the arguments, but at the same time I cannot think of any reason that justifies the newline.  

All other git commands that I've used with this setup works as expected.

**Comment by joaomoreno** [comment]
WSL git is not supported. Only Git for Windows. If you'd like to use Git inside WSL, please check out our Remote Development support: https://code.visualstudio.com/blogs/2019/05/02/remote-development
