### ISSUE TITLE
Other NSDocument apps don't recognize when VS Code changes a document

### ISSUE THREAD

**Issue by NilsEnevoldsen** [microsoft/vscode#74759]
- VSCode Version: 1.34.0
- OS Version: macOS Mojave 10.14.5 

Steps to Reproduce:

1. Open a document with an NSDocument-aware app such as TextEdit
2. (Optionally, open that document with a second NSDocument-aware window)
3. Open that document with VS Code
4. (Optionally, open that document with a second VS Code window)
5. (Optionally, edit and save the document in the first app, observe that all VS Code windows update)
6. Edit and save the document in VS Code, observe that **the first app doesn't update** (but all other VS Code windows update)
7. (Optionally, re-save the document in the first app. Observe that, _prior to interacting with the warning dialog_, all other NSDocument-aware windows update.)

This bug impairs working with the same file in multiple applications on macOS.

This may be related to NSFilePresenter and presentedItemDidChange of NSDocument.

Does this issue occur when all extensions are disabled?: Yes

![Screen Recording 2019-06-02 at 2 40 49 PM](https://user-images.githubusercontent.com/222743/58766124-ff5dfd00-8548-11e9-8d06-0c38f7942367.gif)

**Comment by kieferrm** [comment]
@NilsEnevoldsen We don't go through the macOS libraries. We read and write the files directly. We have no plans to change this at this point.
