### ISSUE TITLE
Could not find the task 'tsc: build - tsconfig.json'

### ISSUE THREAD

**Issue by levrik** [microsoft/vscode#74756]
I followed the tutorial at https://code.visualstudio.com/docs/typescript/typescript-debugging but it doesn't work. It just shows the error mentioned in the issue title.

This issue is different from #69572. It also happens with `launch.json` configured and the tsc autodetect enabled.

Maybe notable: I'm using a VS Code workspace. Didn't try outside a workspace yet.

_Edit:_ Also happens outside a workspace.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I followed the linked tutorial on windows 10 with VS Code 1.38 (the current insiders build) and debugging / launch seems to work fine.

Are you still seeing this issue? If so please provide more information about what is going wrong
