### ISSUE TITLE
Enable copy/paste in code sections in Extension view

### ISSUE THREAD

**Issue by maggot99999** [microsoft/vscode#74754]
### REASON:
Sometimes you need trickery to install properly an extension and so extensions provide code snippets to copy and paste to settings.json/terminal and so on in README.md file.

### FEATURE REQUEST:
Add the ability to easily copy code snippets in extension pages in VSCode. So developers won't need to rewrite it either themselves or open repository in browser and copy-paste from there. 
Right now it's not even possible to copy. Checked on macOS and Windows.

**Comment by usernamehw** [comment]
<kbd>Ctrl</kbd>+<kbd>C</kbd> works for me.

There's also #65310
