### ISSUE TITLE
Markdown preview syntax highlighting fails for javascript under specific circumstances

### ISSUE THREAD

**Issue by bheisen** [microsoft/vscode#74757]
Issue Type: <b>Bug</b>

Reproduce:

Use javascript code snippet and include a template string variable with an inline division like so:

```javascript
console.log(`Bad ${foo / 1000}`)
const highlighting = 'broken'
```
The rest still is ok.

Expected:

Syntax highlighting should work as is regular javascript.

Observed:

Broken highlighting. Everything below renders in the same color (here orange).

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.10.0-35-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.44GB (0.33GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
empty-indent|Dmi|0.2.0
swagger-viewer|Arj|2.2.2
code-gnu-global|aus|0.2.2
vscode-standard-format|che|0.0.12
githistory|don|0.4.6
gitlens|eam|9.8.1
node-version|fiv|0.0.1
docker-explorer|for|0.1.6
restructuredtext|lex|109.0.0
dotenv|mik|1.0.1
vscode-clang|mit|0.2.3
python|ms-|2019.5.17517
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
Go|ms-|0.10.2
vscode-docker|Pet|0.6.2
java|red|0.45.0
reloaded-cpp|rel|0.1.9
missinglineendoffile|ric|0.3.1
standard|shi|0.2.3
gitconfig|sid|2.0.0
rewrap|stk|1.9.1
code-spell-checker|str|1.7.12
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
JavaScriptSnippets|xab|1.7.2
highlight-trailing-white-spaces|yba|0.0.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
We use highlight.js for syntax highlighting in the preview. I've opened https://github.com/highlightjs/highlight.js/issues/2050 to track this issue upstream
