### ISSUE TITLE
Unverified breakpoint

### ISSUE THREAD

**Issue by 1dnmr** [Microsoft/vscode#7475]
- VSCode Version: 1.2.0
- OS Version: OS X Yosemite 10.10.5

Steps to Reproduce:

1. Install latest version of Visual Studio Code with all necessary extension for Go lang developing according to this article https://github.com/Microsoft/vscode-go

2. Set breakpoint and start debugging. 

Breakpoint become grey. If point cursor on them you will see "Unverified Breakpoint" hint appears.
I've searched how to fix it but nothing is helped.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-go#360
