### ISSUE TITLE
Right-click shows black rectangle instead of context menus

### ISSUE THREAD

**Issue by Gregor812** [microsoft/vscode#74751]
- VSCode Version: 1.34.0
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Open any file (I open .c/.cpp)
2. Do right click on a function or a type name

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/9018071/58762092-a6946180-8554-11e9-8029-02da139bf27c.png)

**Comment by kieferrm** [comment]
@Gregor812 do you use native or custom menus?

**Comment by Gregor812** [comment]
@kieferrm yes, I'm using native menus without any themes

**Comment by singh-arulraj** [comment]
I too am facing similar Issue. Do let me know what information is needed.
I am running it on Ubuntu 16.04.
Other INformation
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic
