### ISSUE TITLE
Only show extension recommendations when there are no extensions already installed

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#74763]
After installing the [Binary Plist](https://marketplace.visualstudio.com/items?itemName=dnicolson.binary-plist) extension the following message is displayed when opening `plist` files.

"The Marketplace has extensions that can help with '.plist' files"

Clicking the `Search Marketplace` results in a `ext:plist` search in the Marketplace and it shows the extension that has already been installed.

**Comment by kieferrm** [comment]
Agree, it shouldn't. We actually do check if you have extensions installed that handle the language the file is in. So, in this case, for whatever reason, we think you don't have any.
