### ISSUE TITLE
Allow extension developers access and change layout dimensions

### ISSUE THREAD

**Issue by austincondiff** [microsoft/vscode#74762]
I am creating a theme/extension that changes the UI a bit to replicate the UI found in Framer X.
<img width="1584" alt="Screen Shot 2019-06-02 at 3 37 57 PM" src="https://user-images.githubusercontent.com/806104/58767166-1acb0700-854d-11e9-8bf9-b07aa7eb69fd.png">

I am having trouble modifying the dimensions of some elements because of the nature of the workbench layout. It positions absolutely and explicitly sets a width and height for everything, making it next to impossible to style certain elements without throwing off the layout.

For example if I increase the height of a panel heading to give the text a bit more breathing room, it overhangs the bottom because it is still accounting for the original height.
<img width="343" alt="Screen Shot 2019-06-02 at 3 35 36 PM" src="https://user-images.githubusercontent.com/806104/58767202-beb4b280-854d-11e9-8b6e-7d4b01995f3e.png">

Additionally, as stated in other issues, I would like to be able to set me titlebar to custom inset on macOS as shown (I manually modified workbench.main.js). This would go along nicely with the look I am after for this theme.

When laying out elements in the workbench, I suggest getting the height of elements that must be manually positioned so that it enables extension developers to be more creative in theming the UI.

**Comment by austincondiff** [comment]
There are extensions like this out there that modify the source code automatically. 
https://github.com/lehni/vscode-titlebar-less-macos
This is far from ideal and should not be required to get the functionality that this extension offers.

**Comment by isidorn** [comment]
When designing the vscode extensions API we decided to put some limits on what extensions can do, and too much UX customisation is not something we wanted to allow. More about this can be found here and in our docs
https://code.visualstudio.com/api

Due to the above I have to close this as out of scope
