### ISSUE TITLE
Visual studio code crash message

### ISSUE THREAD

**Issue by adhivenkatesh** [microsoft/vscode#74777]
Issue Type: <b>Bug</b>

Team tegging visual studio while opening crash message and  unable to rund
ANGULAR PROJECTS while running ng serve command its running  10% only instead of 100% , i am using windows 7 updating regularly , please solve the issues.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.45GB free)|
|Process Argv|--folder-uri file:///d%3A/AngularProjects/RoutProject|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.9.0
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
@adhivenkatesh please describe the problem you are observing in more details
