### ISSUE TITLE
Markdown checkbox

### ISSUE THREAD

**Issue by MajorTom327** [microsoft/vscode#74776]
Issue Type: <b>Bug</b>

Create a basic markdown with a list of task like this one:
```markdown
# test
- [ ] checkbox
- [x] checked checkbox
- li
```
open the preview on the side
The checkbox aren't parsed anymore and show `[ ]` or `[x]` instead

![image](https://user-images.githubusercontent.com/16199396/58783619-a42c1900-85e1-11e9-875a-14f9dd30a896.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (9.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.1
vscode-npm-script|eg2|0.3.7
vs-code-http-server-and-html-preview|Fli|2.2.2
beautify|Hoo|1.5.0
electron-debug|kod|18.11.1
code-beautifier|mic|2.2.1
mssql|ms-|1.6.0
csharp|ms-|1.19.1
vetur|oct|0.21.0

</details>

**Comment by usernamehw** [comment]
I don't think they are part of Markdown standard language, but rather a part of GFM.

https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
