### ISSUE TITLE
Unwanted Formatting of JS1.7/ES2015 Destructuring Assignment Pattern

### ISSUE THREAD

**Issue by MannikJ** [Microsoft/vscode#7477]
- VSCode Version: 1.2.0
- OS Version: Windows 10

The built-in formatter does not recognize the new destructuring assignment syntax with curly braces and formats it like normal code blocks, which is potentially unwanted in most of the cases.
It would be perfect to be able to switch it on or of, or even to set a limit, so that it is only formatted as blocks, if there are more than the specified number of items in the list. 

Steps to Reproduce:

1. Create an example .js file with desired formatting like this: 
    ```
    const electron = require('electron');
    const {app} = electron;
    ```

2. Format the file via _Alt+Shift+F_ resulting in:
    ```
    const electron = require('electron');
    const {
        app
    } = electron;
```

PS: I just found out that the code highlighting is also different when block-formatted:
![image](https://cloud.githubusercontent.com/assets/1841856/15931729/3aad32c6-2e59-11e6-8073-e9e42785672a.png)
vs.
![image](https://cloud.githubusercontent.com/assets/1841856/15931768/604a6c7e-2e59-11e6-9160-3fbdef5a4c14.png)

**Comment by dbaeumer** [comment]
Formatter is maintained by the TS team. Moving...

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9120
