### ISSUE TITLE
Error message on valid dynamic import

### ISSUE THREAD

**Issue by graphicsxp** [microsoft/vscode#74779]
This bug is the same as #70806 (but this one is closed and I cannot folllow-up on it).

I've just upgraded from Angular 7 to Angular 8, which now supports dynamic import for lazy-loaded modules :

<code>
{
                path: 'task', loadChildren: () => import('../tasks/tasks.module').then(m => m.TasksModule)
            },
</code>

which gives the error : 

`Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.ts(1323)`

This is because the tsconfig file in my source code directory is named tsconfig.app.json instead of tsconfig.json
However this is the Angular naming convention so I cannot change it.

Could this be handled by VSCode  ?

**Comment by mjbvz** [comment]
Try creating a `tsconfig.json` that uses `extends` to share the settings from`tsconfig.app.json` :

```json
{
    "extends": "tsconfig.app.json"
}
```

**Comment by RinMinase** [comment]
Why is this issue closed? The answer commented above does not work.
