### ISSUE TITLE
Support of Snapshot debugging

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/vscode#74771]
Use-case: microservices development. day 2 maintenance scenario support. Crash and customer issues analyzes caused by  bugs in implementation of microservice already deployed to cloud infrastructure. 
Expected capability: create duplicate container instance available for analyzes, debugging and correction without temporary denial user from service via creating separate container instance  available to developer only. Developer can modify state of such container without service denial.
Reference capabilities:
Microsoft Azure Snapshot debugger and Google StackDriver debugger
Technical barrier:
developer can't attach debugger to stopped or crashed container used by microservice user because afinity mechanism will require transfer afinity cookies from user to another person which is strictly prohibited from security point-of-view. 
Feature is supported by Cloud infrastructures: Azure & Kubernetes via public API.
Preliminary efforts estimations:
UI extension - small
DAP protocol extension - small
Debug adapter implementation extension - large

**Comment by weinand** [comment]
Snapshot debugging can be done as a debug adapter/extension.
