### ISSUE TITLE
Remote ext host starts with a delay

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#74772]
Version: 1.35.0-insider (user setup)
Commit: 0284236851a94b116f468345f6e98688a737015d
Date: 2019-05-31T21:32:42.295Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

- install the remote wsl extension
- open a wsl remote window to ensure that the remote server is installed. Close the remote window
- open a WSL shell and type `code-insiders .`
- in the opened window the resolver finishes very quickly, but often it takes quite a while for the remote ext host to come up.

The terminal says `Starting...`
The output views don't contain the remote logs
When opening the `main` log it says

Unable to read file (Error: File not found (c:\Users\aeschli\AppData\Roaming\Code - Insiders\logs\20190603T070956\main.log))

After a while the ext host comes up.

**Comment by sandy081** [comment]
Fixed the log output channels to be available only when the log files are available.
