### ISSUE TITLE
Investigate: macOS notarization

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74782]
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

and

https://github.com/electron/electron/issues/18609

//cc @joaomoreno 

If VSCode fails to launch VSCode on macOS Catalina do this:

![image](https://user-images.githubusercontent.com/900690/60642008-9e1e9780-9e2e-11e9-9a4d-9eac92078894.png)

**Comment by bpasero** [comment]
Looks like this is only required beginning 2020: https://developer.apple.com/news/?id=09032019a

**Comment by andrewpeterprifer** [comment]
@bpasero only the notarization prerequisites have been loosened till 2020, notarization is still very much required if we want to get rid of the security warning.

**Comment by cutecycle** [comment]
We're having this issue on a Catalina upgrade, except we can't even open the application.

**Comment by misolori** [comment]
@cutecycle see the main issue description for how to get around this. You can also right-click on the app and click "Open" to get the option to open it:

![image](https://user-images.githubusercontent.com/35271042/66606616-4bf4bd00-eb67-11e9-9b5e-8a8346eb5f67.png)

**Comment by cutecycle** [comment]
@misolori Open Anyway doesn't appear in Catalina.

**Comment by misolori** [comment]
@cutecycle does the right-click method work for you?

**Comment by erised** [comment]
@misolori No. Open does not even appear anymore. Right click doesn't works as well. 
![image](https://user-images.githubusercontent.com/37252657/66702195-8eaec480-ed22-11e9-9c15-4c90416ddca8.png)

**Comment by bkowshik** [comment]
I was able to install Visual Studio Code on Catalina using the following steps:
1. Double-click the installer to get, `“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.` message
2. Open `Security & Privacy` settings page to see the **`Open Anyway`** button
3. One more window and one should be inside VS Code

**Comment by yrest** [comment]
Same issue, workaround works fine! Any update on plans to submit VSCode to Apple?

**Comment by noelrappin** [comment]
This workaround doesn't work for me -- Open Anyway gives me the open dialog again, but that dialog appears to do nothing and I'm back to the same problem, only trying to open VS Code fails silently

**Comment by meguroyama** [comment]
Hi as @bpasero noted and @andrewpeterprifer pointed out that the application should be [notarized](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution) moving forward. Are there any official plans to get vscode notarized in the future?

**Comment by bpasero** [comment]
ETA: November

**Comment by bpasero** [comment]
This may slip to December, but @joaomoreno already started on this 🍻

**Comment by justlurking** [comment]
> This may slip to December, but @joaomoreno already started on this 🍻

Any update on this @joaomoreno @bpasero? Hoping this will be resolved in 1.41.1 before the holidays and we won't have to wait until January?

**Comment by bpasero** [comment]
This is in progress and should be done by our January release.

**Comment by bpasero** [comment]
Related issues for entitlements:
* https://github.com/electron-userland/electron-builder/issues/4040
* https://github.com/electron-userland/electron-builder/issues/3989

**Comment by joaomoreno** [comment]
Starting next week, insider builds should be properly notarized. :heavy_check_mark:
