### ISSUE TITLE
breadcrumbs and uris that aren't backed by a file system

### ISSUE THREAD

**Issue by WarHatch** [microsoft/vscode#74789]
Issue Type: <b>Bug</b>

* Source control tab > click on file to show changes
* File changes are show but no breadcrumbs bar is available

I'm guessing this is because a read-only editor is shown for showing file changes

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-faker|dee|1.3.0
githistory|don|0.4.6
prettier-vscode|esb|1.9.0
todo-tree|Gru|0.0.132
open-file-from-path|jac|1.3.0
break-from-comma|jza|1.1.6
vscode-typescript-tslint-plugin|ms-|1.1.0
vscode-docker|Pet|0.6.2

</details>

**Comment by jrieken** [comment]
works for me

<img width="840" alt="Screenshot 2019-06-03 at 15 50 30" src="https://user-images.githubusercontent.com/1794099/58806865-5205ea80-8617-11e9-97be-45cf7fbe4cfa.png">

**Comment by WarHatch** [comment]
Staged changes compare mode opens in read-only mode, which might be causing the problem
<img width="1324" alt="Screenshot 2019-06-04 at 09 32 02" src="https://user-images.githubusercontent.com/20258194/58856750-2719a600-86ac-11e9-8108-e1ff7325df55.png">

It works fine if I compare just 'changes'

**Comment by jrieken** [comment]
Yeah, the issue is that the git-stage document come from a document provider and not from a file system. Without file system support breadcrumbs cannot do much because there is no way to navigate siblings (except for symbols). Not sure what to do here...

**Comment by WarHatch** [comment]
Thanks for the explanation. That makes a lot of sense. This does not prevent me from doing further work, so I'll close this issue.
