### ISSUE TITLE
Html shows errors 

### ISSUE THREAD

**Issue by DuncanFaulkner** [microsoft/vscode#74784]
Hi Receiving error below, have noticed this for a while, if I open an html page in VS Code I sometimes get lots of red squiggly lines, the error messages vary but the gist of the error message is the same.

Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".Angular
Can't bind to 'ngIf' since it isn't a known property of 'div'.Angular

If I close VS Code then the error goes away.

Version: 1.35.0-insider
Commit: 0284236851a94b116f468345f6e98688a737015d
Date: 2019-05-31T21:25:54.986Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-50-generic

Open html page

**Comment by kieferrm** [comment]
@DuncanFaulkner do you use the Angular extension?

**Comment by DuncanFaulkner** [comment]
Hi @kieferrm Yes, well it's installed, this seems to be very much like the 
Cannot read property 'isSkipSelf' of nullAngular error

**Comment by DuncanFaulkner** [comment]
This seems to happen when I open an html page, I have disabled the angular extension, I'm currently running 7.2.15

**Comment by kieferrm** [comment]
@DuncanFaulkner the way I read what you say is that the issue is with the Angular extension. Please move the issue over there. Thanks!

**Comment by DuncanFaulkner** [comment]
Closing this ticket it seems to be the Angular Language Service, it updated to @angular/language-service@8.0.x and typescript@3.4.x. My project is currently on version 7 (looking to upgrade shortly)
