### ISSUE TITLE
Linked files in toolbar? (dreamwever-like)

### ISSUE THREAD

**Issue by skini82** [microsoft/vscode#74780]
Hello,
it would be easier for us mantaining some old php application, to have a dreamweaver-like toolbar wich links all the "include/" files, .css and .js linked files and so on.

Maybe there's already a solution for that, but it was unable to find for me, not on VSCode, neither on extensions for VSCode.

![DW-related-files-bar](https://user-images.githubusercontent.com/5445572/58793212-f70fcb80-85f5-11e9-8405-6c4b04fcf628.jpg)

**Comment by kieferrm** [comment]
There is no such thing today.  We provide different ways how you can access the outline (through the outline view, the bread crump, or the quick outline (<kbd>Cmd+Shift+0</kbd>) and I'd expect the includes to show up there. From there you would have to use <kbd>Cmd</kbd>+mouse click to jump to the reference. The PHP extension(s) you use could provide a custom tree view just listing the references. Pls file that as a feature request against the PHP extension.
