### ISSUE TITLE
Rename Symbol goes to undesired places

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#7478]
- VSCode Version: 1.2.0
- OS Version: Win10x64

``Rename Symbol`` can wander off into files, that are undesired to change. Just now I had several lines using ``__dirname`` global variable, I decided to use an another user defined variable ``settings.paths.root`` and used ``Rename Symbol`` it worked fine, except it also went into ``.\typings\node\node.d.ts`` and changed it there as well... This happens even if I exclude the ``typings`` dir in ``.vscode\settings.json``

**Comment by dbaeumer** [comment]
Rename operation is provided by the TS server. Moving...

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9119
