### ISSUE TITLE
Intellisense stoped working

### ISSUE THREAD

**Issue by shivakumar5** [microsoft/vscode#74791]
Issue Type: <b>Bug</b>

Intellisense stoped working, not getting any suggestions

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (19.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
vscode-github|Kni|0.30.2
Go|ms-|0.10.2

</details>

**Comment by jrieken** [comment]
not getting anything out of this report @shivakumar5 please file issues like you would like to receive issues yourself

**Comment by donnisnoni95** [comment]
> Issue Type: Bug
> 
> Intellisense stoped working, not getting any suggestions
> 
> VS Code version: Code 1.34.0 ([a622c65](https://github.com/microsoft/vscode/commit/a622c65b2c713c890fcf4fbf07cf34049d5fe758), 2019-05-15T21:59:37.030Z)
> OS version: Windows_NT x64 10.0.16299
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)
> GPU Status	2d_canvas: enabled
> checker_imaging: disabled_off
> flash_3d: enabled
> flash_stage3d: enabled
> flash_stage3d_baseline: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> native_gpu_memory_buffers: disabled_software
> rasterization: enabled
> surface_synchronization: enabled_on
> video_decode: enabled
> webgl: enabled
> webgl2: enabled
> Load (avg)	undefined
> Memory (System)	31.85GB (19.12GB free)
> Process Argv	.
> Screen Reader	no
> VM	0%
> Extensions (3)
> Extension	Author (truncated)	Version
> prettier-vscode	esb	1.9.0
> vscode-github	Kni	0.30.2
> Go	ms-	0.10.2

hi @shivakumar5 ..  go to your developer tools by hitting  `Ctrl+Shift+I` and see the `error` log, if the error there, then copy and iclude that on you submitted issue

**Comment by shivakumar5** [comment]
Hi @donnisnoni95 ,

I'm not seeing any errors
