### ISSUE TITLE
html failed to save due to unknown file system error. it has been consistent with every html file I created and edited with VSCode.

### ISSUE THREAD

**Issue by Pavelbure34** [microsoft/vscode#74793]
- VSCode Version:1.34
- OS Version:Windows 10 Pro

Steps to Reproduce:

1.write anything on index.html
2.save it then sometime soon eventually it cannot be saved.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
@Pavelbure34 same happens when you start VS Code from the command line with `code --disable-extensions`?
