### ISSUE TITLE
Deleting a modified file asks if you would like to save the file

### ISSUE THREAD

**Issue by duncanjbrown** [Microsoft/vscode#748]
To reproduce:

* open a file
* make a change
* delete the file from the 'explore' panel

This results in 2 dialog boxes.

First I confirm I want to delete it:

<img width="436" alt="screen shot 2015-11-27 at 15 01 39" src="https://cloud.githubusercontent.com/assets/642279/11443788/dd72c16e-9517-11e5-83f5-512c510b0f44.png">

Then I'm asked if I would like to save my changes to the deleted file

<img width="473" alt="screen shot 2015-11-27 at 15 01 45" src="https://cloud.githubusercontent.com/assets/642279/11443787/dd619146-9517-11e5-81d1-d2ef1bf88efe.png">

**Comment by pcgeek86** [comment]
+1 I have seen this behavior as well. The user shouldn't be prompted to save the file if the instruction was to delete it.

Cheers,
Trevor Sullivan

**Comment by bpasero** [comment]
Wont fix. Since deleting the file means data loss (the changes you made in the document) we can not avoid asking you to make the decision to save or not.

Btw Sublime seems to behave the same way.
