### ISSUE TITLE
Arrow keys dont work in windows terminal window when running yeoman

### ISSUE THREAD

**Issue by rickhodder** [Microsoft/vscode#7480]
- VSCode Version: 1.2.0
- OS Version: Windows 7

Steps to Reproduce:

1. Install yeoman 
2. Open terminal window
3. yo <enter>

Yeoman pops up, but you cannot use arrow keys to move between options

**Comment by Tyriar** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/7077

**Comment by Tyriar** [comment]
I believe this is already fixed (works on Linux), can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
