### ISSUE TITLE
Error: EIO: i/o error, read

### ISSUE THREAD

**Issue by donnisnoni95** [microsoft/vscode#74804]
I just fount it on vscode developer tools console.. 

[Link to log file](https://termbin.com/1uzc)

**Comment by donnisnoni95** [comment]
@mjbvz I font that error after open vscode

**Comment by mjbvz** [comment]
Please follow the issue reporting guide 

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by donnisnoni95** [comment]
I think its not an error from vscode, instead the `quokka` extension... thank you..:)
