### ISSUE TITLE
Unable to Pin Code to Start Menu

### ISSUE THREAD

**Issue by systo** [microsoft/vscode#74807]
Currently unable to pin Code to StartMenu.  Can pin to taskbar, but not windows 10 Start.
Windows 10 (Version 1903). 
![image](https://user-images.githubusercontent.com/15274015/58832461-9774e880-8614-11e9-9f31-33813c34aa4b.png)

Can others replicate?

**Comment by alexr00** [comment]
Using 1903, I was able to pin VS Code and Insiders to the start menu, no problems. Did you try rebooting and then trying again? How did you try to pin it?

**Comment by systo** [comment]
Rebooted, still unable.
- v1.34, 64-bit system installer used.
- tried updating to v1.35 via help menu > install update
- Confirmed version 1903
- OS build 18362.113
![image](https://user-images.githubusercontent.com/15274015/59003108-46165600-87da-11e9-8c73-d537c9bb0c50.png)

**Comment by systo** [comment]
Reboot after vs 1.35 update now allows. No icon present.
![image](https://user-images.githubusercontent.com/15274015/59003429-888c6280-87db-11e9-97a9-3ce1eac0d9d6.png)

**Comment by alexr00** [comment]
I'm on the same Windows build and I tried both the System and the User installer:
![image](https://user-images.githubusercontent.com/38270282/59037100-e0c17400-8870-11e9-85f8-489577541353.png)

Did you originally install from https://code.visualstudio.com/ ?

**Comment by systo** [comment]
Yes. Trying to reinstall now.

**Comment by alexr00** [comment]
I can't get VS Code to show up in the start menu if I check that box during install, which means I can't get a repro of this. It looks like the issue might be resolved though since you have the pin icon and name now.
