### ISSUE TITLE
npm update: npm ERR! Error: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by hidegh** [microsoft/vscode#74803]
Angular app, issues when updating node_modules with error:
npm ERR! Error: EPERM: operation not permitted, unlink ...

Steps to Reproduce:
1. open any TS file from the node_modules folder
2. even if you close the files, and move away from that folder, some reference (**open file/folder handle**) still remains valid, the only way to do a npm update is to: close VSCode, do update, restart VSCode.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by hidegh** [comment]
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by hidegh** [comment]
![image](https://user-images.githubusercontent.com/6331063/58829052-28fd4e00-8647-11e9-9473-8e65c96a0e22.png)

**Comment by mjbvz** [comment]
Please try this in VS Code insiders, what all extensions disabled
