### ISSUE TITLE
workbench.action.files.save command: execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by CSchank** [microsoft/vscode#74812]
Apologies if this is a duplicate, I do realize there are many similar issues. However, I haven't been able to find an issue directly related to the `workbench.action.files.save` command, nor a solution to the other "execvp(3) failed.: No such file or directory" problems which solved it for me.

- VSCode Version: 1.34.0
- OS Version: macOS 10.13.6
- Happens when setting both `zsh` (oh my zsh) and `bash` as the Integrated Shell in settings.

Steps to Reproduce:
1. Create a task for saving files: 
```
//In Tasks.json
...
       {
        "label": "save_file",
        "command": "workbench.action.files.save"
       },
...
```
2. Create another task, which depends on that one:
```
//In Tasks.json
       {
            "label": "build",
            "command": "(redacted)/build.sh",
            "args": [
                "${file}"
            ],
            "type": "shell",
            "presentation": {
               "reveal": "silent",
            },
            "dependsOn":[
                "save_file"
            ]
        },
```

3. Create a keyboard shortcut to run this command:
```
//In Keybindings.json
    {
        "key":"ctrl+shift+b",
        "command": "workbench.action.tasks.runTask",
        "args": "build"
    },
```
4. Press `Ctrl+Shift+b`.
5. Task terminal opens up and says:
```
> Executing task: workbench.action.files.save  <

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Does this issue occur when all extensions are disabled?: Yes

Thanks in advance for helping to solve this problem.

**Comment by alexr00** [comment]
Please see the tasks documentation for `command` and `type`: https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

**Comment by CSchank** [comment]
@alexr00 thank you very much. I missed that. I was basing this off of a post I found from a while back. Either it was wrong or the tasks format has changed since then. Best regards.
