### ISSUE TITLE
Terminal doesn't work correctly when I open new terminal.

### ISSUE THREAD

**Issue by TheMisir** [microsoft/vscode#74819]
Issue Type: <b>Bug</b>

1. Open terminal (cmd)
2. When I start typing current directory part (`C:\Users\misir\Desktop\web-server>`) gone.
![image](https://user-images.githubusercontent.com/29130291/58852068-123a1400-86a6-11e9-805f-7c9510d27afc.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.22GB free)|
|Process Argv|C:\Users\misir\Desktop\web-server|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.0.14
dart-code|Dar|3.1.0
flutter|Dar|3.1.0
vscode-npm|fkn|3.3.0
formate|Mik|1.1.1
dotenv|mik|1.0.1
easy-less|mrc|1.4.5
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vscode-react-native|msj|0.9.3
LiveServer|rit|5.6.1
nunjucks|ron|0.2.3

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by TheMisir** [comment]
Ok, thanks 🙂
