### ISSUE TITLE
Cut off clock symbol in search viewlet

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#74815]
- Move search to panel
- Run slow search
- See this instead of progress bar

![image](https://user-images.githubusercontent.com/323878/58842294-626f9280-8622-11e9-99f8-d70fe8266ed4.png)

**Comment by roblourens** [comment]
@bpasero https://github.com/microsoft/vscode/commit/1ce1371dc3393a4f3bc50852c0840f4ea3c54717?

**Comment by bpasero** [comment]
@roblourens uh oh, yeah likely. We can possibly add a CSS rule [here](https://github.com/Microsoft/vscode/blob/49f4073/src/vs/workbench/services/progress/browser/media/progressService.css#L14) to not show this unless the progress badge is in the sidebar?

**Comment by bpasero** [comment]
Possible candidate maybe for recovery if too many people complain...

**Comment by bpasero** [comment]
This was a bit more changes, we actually never supported progress in panel area. I fixed that.

**Comment by RMacfarlane** [comment]
Still able to repro this in the current insiders

Version: 1.36.0-insider
Commit: e80dd4f217db6e230d311a87fdf4276f740f6445
Date: 2019-06-25T05:20:16.601Z

**Comment by bpasero** [comment]
@RMacfarlane good catch, however I do not see this after a window reload. It seems like a one-time issue as long as the workbench is not restarted. I extracted https://github.com/microsoft/vscode/issues/76150

**Verifier**: do a window reload after moving search.
