### ISSUE TITLE
Squiggle lines do not appear

### ISSUE THREAD

**Issue by ramaadarsh** [microsoft/vscode#74823]
Issue Type: <b>Bug</b>

The quick fix light bulb and the red squiggle lines does not appears in my code

Extension version: 1.3.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

What Language Mode displays at the right-hand end of the status bar?

Are you working on files in the local filesystem, or using one of the extensions that handles code on remote systems?

Consider adding screenshots here to show what you are seeing.
