### ISSUE TITLE
No IntelliSense for "export from" syntax

### ISSUE THREAD

**Issue by ChenMachluf** [Microsoft/vscode#7482]
Hi,
I'm using the "export from" syntax and it seems that it doesn't working well with the intellisense.
For now I'm using a workaround by importing and then exporting in two separate lines.

![animation4](https://cloud.githubusercontent.com/assets/6990608/15934122/feaaa8b4-2e6a-11e6-8026-dfe90e51de03.gif)

tnx 

- VSCode Version: 1.2.0
- OS Version: Windows 10

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9115
