### ISSUE TITLE
Hash Sum mismatch on packages.microsoft.com

### ISSUE THREAD

**Issue by jean** [microsoft/vscode#74826]
> Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Hash Sum mismatch
> Some index files failed to download. They have been ignored, or old ones used instead.

Previously:

- https://github.com/microsoft/vscode/issues/70584
- https://github.com/microsoft/vscode/issues/66339
- https://github.com/microsoft/vscode/issues/66238
- https://github.com/microsoft/vscode/issues/41117
- https://github.com/microsoft/vscode/issues/25883

**Comment by Tyriar** [comment]
I let the linux repo admins know again
