### ISSUE TITLE
In Ubuntu context menu not highlighting

### ISSUE THREAD

**Issue by manojp1988** [microsoft/vscode#74837]
I'm using vscode in ubuntu 16.04. If I right click any file, context menu appears, but if I hover over the menus, it is not hightlighting.. If I click any menu, menu action is working fine without any problem.. Only problem is not highlighting the menu. This is problem appears in quick fix menu in when using typescript.

![image](https://user-images.githubusercontent.com/1810503/58874152-a37cab00-86e5-11e9-91eb-7b0e4a2b5fea.png)

**Comment by manojp1988** [comment]
No, it is not related to the vscodebot suggestion.

**Comment by manojp1988** [comment]
Linux NGKW-LP 4.15.0-50-generic #54~16.04.1-Ubuntu SMP Wed May 8 15:55:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sbatten** [comment]
@manojp1988 can you provide the following?

1) Your GTK theme
2) Your titlebar style setting (window.titleBarStyle) in VS Code
3) Your VS Code Version
4) Does this apply to all context menus?

**Comment by manojp1988** [comment]
GTK Theme => Ambiance
VSCode Version => 1.35.1
Title bar style => native.
Yes It applies in all context menus, and import suggestions.

**Comment by manojp1988** [comment]
Problem is in the snap package version. I downloaded tar.gz file, it is looking fine.

**Comment by sbatten** [comment]
FYI @joaomoreno
