### ISSUE TITLE
Show popup message when VSCode Updates are found

### ISSUE THREAD

**Issue by cyfrost** [microsoft/vscode#74838]
**Enhancement maybe?**

Hi,

When a user does `Help > Check for Updates`, if no updates are found, it says so by displaying this useful popup message:

![image](https://user-images.githubusercontent.com/12471103/58873708-91e6d380-86e4-11e9-8b87-0156f8da50ed.png)

But when updates are, indeed, found, it'll say nothing except for updating the Settings wheel icon in the left menu with a banner count like this:

![image](https://user-images.githubusercontent.com/12471103/58873804-c195db80-86e4-11e9-9393-2339fad24184.png)

I was wondering if this scenario could be improved by showing a popup message that better indicated availability of new updates and that the way to start the update could be one of many ways (updating via flatpak/system's package manager/silent update for windows/...etc) ?

This could be a very minor UX enhancement but welcome nonetheless.

Might also be useful to look at #30143 which talks about progress indicators in UI while an update is ongoing.

Edit: This issue is neither related nor a duplicate of #44685

**Comment by egamma** [comment]
Showing a pop-up when an update is available would be too distracting.

**Comment by cyfrost** [comment]
> Showing a pop-up when an update is available would be too distracting.

Looks like you haven't read what I wrote properly. I said WHEN THE USER CLICKS on check for updates. That's an on-demand request and that must be met with a interactive popup message.

The next time you close issues in toxicity before letting the OP respond, don't.

**Comment by cyfrost** [comment]
> Showing a pop-up when an update is available would be too distracting.

I EXPLICITLY mentioned in the OP that a user triggers update check via `Help > Check for Updates...`

What you say makes sense in that VSCode shouldn't bug me with Pending Update popups when an automatic update check happens, but this issue is about when update check is triggered manually.
