### ISSUE TITLE
VSC keeps opening three files each time i open a new file

### ISSUE THREAD

**Issue by thwebamp** [microsoft/vscode#74836]
Everytime i open up VSC it opens three files which each is named "Visual" "Studio" "Code".
They are empty and it is quite annoying. Im not sure if this is a feature or a bug.. But it's annoying.

**Comment by gjsjohnmurray** [comment]
What platform?

How do you open up VSC? Command-line? Desktop shortcut?

If you explicitly close those three tabs ("Visual", "Studio" and "Code"), then close VSC, then launch it again, do they reappear?

Consider adding screenshots here to help us understand what you're seeing?

**Comment by thwebamp** [comment]
I re-installed it and it and it has disappeared.
