### ISSUE TITLE
react fragment breaks code formatting

### ISSUE THREAD

**Issue by ozluy** [microsoft/vscode#74839]
Version: 1.34.0 (user setup)
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. when you create a React Fragment `<>  </>` it breaks code formatting

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by mjbvz** [comment]
So this only happens when you have extensions enabled? Can you try tracking down which one is causing this? Likely either a formatter or a linter

/needsMoreInfo
