### ISSUE TITLE
Multi-line raw strings prevent function collapsing

### ISSUE THREAD

**Issue by snrob** [microsoft/vscode#74831]
A raw multi-line string can prevent a function from collapsing correctly.
Source:
```
def demo():
    my_string = """
a multi-line
raw string"""
```
This collapses to:
```
def demo():
a multi-line
raw string"""
```
Expected:
```
def demo():
```
This code collapses correctly in Visual Studio Enterprise 2019.

**Comment by gjsjohnmurray** [comment]
What language? And what extension (built-in or not) is providing the language services?

A quote from [the documentation](https://code.visualstudio.com/docs/editor/codebasics#_folding) about folding:

> Folding ranges are by default evaluated based on the indentation of lines. A folding range starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

> Since the 1.22 release, folding ranges can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding: Markdown, HTML, CSS, LESS, SCSS, and JSON.

If the language you're seeing the issue with is the responsibility of an extension that has its own GitHub project, please raise the matter there and close this issue.

**Comment by snrob** [comment]
I'm using the "Python extension for Visual Studio Code" from Microsoft. I'll re-submit against the Python extension.

**Comment by snrob** [comment]
For anyone else who's interested: https://github.com/microsoft/vscode-python/issues/5894
