### ISSUE TITLE
Remove heap service

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74846]
In the lack of properly defined lifecycles we have added [`gc-signals`](https://github.com/Microsoft/node-gc-signals) and the [`IHeapService`](https://github.com/microsoft/vscode/blob/676368aa81485b8a1282a51d96f3562c8b161a76/src/vs/workbench/services/heap/common/heap.ts#L24). Apart from this being debt-ish it won't work on the web. There are two consumer left on the main side so its time for more lifecycle 💪 

Direct and indirect user of the heap service

* [x] code lens
* [x] completions
* [x] code actions (@mjbvz)
* [x] signature help (@mjbvz)
* [x] SCM (via [`CommandsConverter#toInternal`](https://github.com/microsoft/vscode/blob/9ec785ea5c03459524241412cef476ca9573bc83/src/vs/workbench/api/common/extHostCommands.ts#L247))
* [x] TreeViews (via [`CommandsConverter#toInternal`](https://github.com/microsoft/vscode/blob/9ec785ea5c03459524241412cef476ca9573bc83/src/vs/workbench/api/common/extHostCommands.ts#L247))
* [x] Comments (via [`CommandsConverter#toInternal`](https://github.com/microsoft/vscode/blob/9ec785ea5c03459524241412cef476ca9573bc83/src/vs/workbench/api/common/extHostCommands.ts#L247))

**Comment by jrieken** [comment]
@joaomoreno @sandy081 @rebornix Your use-cases are a bit special because on the extension host `toInternal` is being used but without using `IHeapService` on the renderer side. This means that command arguments always leak. Not sure how this happened but I believe a long time ago the `IHeapService` used to spy at IPC messages

I have added `CommandsConverter.toInternal2` which expects a `DisposableStore`. That should help having a lifecycle. In other cases a `WeakMap` might be helpful - e.g not using toInternal2

**Comment by joaomoreno** [comment]
@jrieken I've read this a couple times over and I've seen your changes as well. Unfortunately I still don't understand what to do here. A few questions:

- Why does `toInternal2` expect a `DisposableStore`?
- How exactly can we get around `toInternal2` using a `WeakMap`?
- What is your recommendation for each of the use-cases? What is the basis for deciding between `toInternal2` and `WeakMap`?

**Comment by jrieken** [comment]
It really depends on your code. A `WeakMap` might (!) help if you keep the parent nodes (e.g tree items) and if they control the lifecycle of the commands (e.g. in case commands go away when items go away). In that case you basically do what `CommandsConverter` does: (1) create one dummy command, (2) convert all commands to that command with (3) a argument that allows you to look up the real command.

But as said, that might work but the best is to have a real, well-defined lifecycle that allows you to dispose these things correctly.

**Comment by akosyakov** [comment]
Will you expose corresponding `dispose` methods in Monaco services as well, e.g. for code lenses?

**Comment by jrieken** [comment]
Yes - those changes will tickle down to monaco. The general pattern is that we add result objects with a dispose-functions, e.g. [`CodeLensList#dispose`](https://github.com/microsoft/vscode/blob/622f08313b01d4b73b6e38efc4dfca01c9422dc1/src/vs/editor/common/modes.ts#L1474-L1477)

**Comment by jrieken** [comment]
@mjbvz also found this https://github.com/microsoft/vscode/blob/1ad12b24a6e8543e5e177b78c97c7788fc30be16/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L787

**Comment by jrieken** [comment]
Only comments is left. @rebornix @RMacfarlane please fix those leaks!

**Comment by rebornix** [comment]
I'm on it.
