### ISSUE TITLE
Mute individual participants in Audio Call

### ISSUE THREAD

**Issue by Namstel** [microsoft/vscode#74841]
I'd like to be able to mute individual participants in the Audio Call.

Sometimes I'm in a room with several developers and one or more developers are remote. It would be nice if I could mute the participants I'm in the room with, so I don't hear them twice (once IRL and once via the Audio Call).

**Comment by weinand** [comment]
@Namstel How is this related to VS Code?

**Comment by egamma** [comment]
If this is an issue against the https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-audio extension then please report an issue against this extension.
