### ISSUE TITLE
Specify ordering of suggestions Intellisense

### ISSUE THREAD

**Issue by aravindnujella** [microsoft/vscode#74848]
How can I customize order in which suggestions are displayed. For example, I prefer having word based suggestions above every other suggestions.
![image](https://user-images.githubusercontent.com/12129609/58897391-d3dc3d80-8715-11e9-8df1-1c0bd28b70d2.png)
I would like to get 'node_left' as top suggestion when I type 'nl' much like Sublime Text.

**Comment by egamma** [comment]
Have you tried to enable the setting `editor.suggest.localityBonus`?

**Comment by aravindnujella** [comment]
Yes, I've tried the option. I'm still getting the same order as shown in the image.
