### ISSUE TITLE
TypeScript/JavaScript Language Features Extension Ignores TSConfig Excludes

### ISSUE THREAD

**Issue by ryuhhnn** [microsoft/vscode#74847]
- VSCode Version: 1.34.0
- OS Version: macOS Mojave 10.14.5 (18F203)

Steps to Reproduce:
Project File Structure:
```
/node_modules
/packages
    /package_1
        /node_modules
    /package_2
        /node_modules
tsconfig.json
```

tsconfig.json:
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "rootDir": ".",
    "typeRoots": ["**/*.d.ts/*"],
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["es2017", "dom"],
    "allowJs": true,
    "checkJs": false,
    "noEmit": true,
    "strict": false,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "esModuleInterop": true
  },
  "include": ["**/*.js", "**/*.ts", "node_modules/@open-wc/**/*.js"],
  "exclude": ["**/node_modules/*"]
}
```

VSCode warns for "Configure Excludes" with message (despite excludes being configured):
```
To enable project-wide JavaScript/TypeScript language features, exclude large folders with source files that you do not work on.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you check the contents of your TypeScript project using the  TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a file called `tsserver.log`.

Look through that log file for the a line near the end that section a set of projects and the files that make them up. It should look like:

```
Info 420  [20:39:6.291] Project '/dev/null/inferredProject1*' (Inferred) 0
Info 420  [20:39:6.291] 	Files (24)
	/Users/matb/projects/san/node_modules/typescript/lib/lib.es5.d.ts
	/Users/matb/projects/san/node_modules/typescript/lib/lib.es2015.d.ts
```

Does this list contain unexpected entries? If you can share the file list, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Also be sure to test all this on VS Code 1.35

**Comment by ryuhhnn** [comment]
I for some reason can't seem to recreate this any more, so I'll go ahead and close this
