### ISSUE TITLE
Interactive Playground: Errors and Warnings section shows no errors or warnings

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#74840]
Issue Type: <b>Bug</b>

1. From Help menu, launch Interactive Playground
2. Scroll down to Errors and Warnings section
3. Look in vain for squiggles
![image](https://user-images.githubusercontent.com/6726799/58874454-bf218a80-86c0-11e9-8daa-bdc786ff636d.png)
4. Click into the code, then press the F8 key mentioned in the descriptive text.
![image](https://user-images.githubusercontent.com/6726799/58874635-3c4cff80-86c1-11e9-9246-7efa4dbe4fe4.png)
5. Be confused about what is being displayed.
6. Note the red entry in OPEN EDITORS and the problem count of 1.
7. Click left end of status bar to reveal Problems tab:
![image](https://user-images.githubusercontent.com/6726799/58874785-9bab0f80-86c1-11e9-9544-53ab91cc1ba9.png)
8. Click "Disable Files Exclude Filter" hyperlink, but see no change to screen.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

Steps 1-3 also reproduce on 1.35 Insiders, but on that version 5-8 don't occur.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-3420M APU with Radeon(tm) HD Graphics (4 x 1497)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.47GB (0.39GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by serendatapy** [comment]
My problem was perhaps worse, all the code in the playground was white, I tried to reinstall on top, nothing changed. When I created a new file, however, it seems that all the playground syntax became coloured and the wiggly lines appeared.

**Comment by chrmarti** [comment]
Consolidating with #83025.
