### ISSUE TITLE
Support Custom Link Matchers in Terminal via API

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/vscode#74849]
I would like to be able to register custom link matchers in the terminal when authoring VS Code extensions. 

For example, the [Bot Framework Emulator](https://github.com/microsoft/botframework-emulator) uses a custom URI Protocol, `bfemulator://`. I would like the ability to register a custom link matcher so that when `bfemulator://**` is displayed in the terminal, a user can ctrl+click it to open. 

Similar Issues:

* #18454 - Closed as out-of-scope, although I'm not sure why. There was some talk about this maybe being supported in Tasks, but I haven't found a way to implement it.
* #70411 - @Tyriar mentioned he doesn't want expose the `registerLinkMatcher` API, but didn't really explain why. This was closed as a duplicate, but I'm also not sure why.
* #21928 - This one is still open, but hasn't been updated since Dec 2017.

**Comment by Tyriar** [comment]
No plans to add this, the reason https://github.com/microsoft/vscode/issues/70411 was closed as the underlying registerLinkMatcher API will likely change, so naturally I don't want to propagate it into the VS Code API until that is worked out (depends on what happens in https://github.com/xtermjs/xterm.js/issues/583).
