### ISSUE TITLE
Integrated Terminal consumes a lot of memory

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7484]
- VSCode Version: VS Code 1.2
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. open integrated terminal
2. run `ls -lR /Applications` 
3. watch Electron Helpers growing quickly in Activity Monitor:

![2016-06-09_17-19-13](https://cloud.githubusercontent.com/assets/1898161/15935062/4b8280a8-2e66-11e6-84e3-fb06abb7f779.png)

Before opening the terminal the renderer was at 169 MB, the 2.24 GB are after about 5 minutes. 

The first process is the Renderer and the second the terminalProcess:

36471 ??         8:11.00 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --background-color=#FFFFFF --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=36422.3.135030966

38929 ??         0:11.76 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper ./terminalProcess

/cc @alexandrudima

**Comment by Tyriar** [comment]
@weinand is your terminal shell bash? Were you running anything in particular or just idling?

**Comment by weinand** [comment]
@Tyriar I tried with bash and csh but did not see a difference.
I was running a recursive ls. See step 2. from above.

**Comment by Tyriar** [comment]
@weinand thanks, just woke up :stuck_out_tongue:

**Comment by Tyriar** [comment]
Running `ls -lR /usr/share` on Linux I saw the renderer process max out a CPU while the command was running, but memory stayed relatively low at around ~150MiB max terminalProcess (average around 80) and 250MiB for renderer (average around 200). terminalProcess dropped to 55MiB when it was done.

**Comment by Tyriar** [comment]
This is likely related to https://github.com/Microsoft/vscode/issues/7554

**Comment by Tyriar** [comment]
Max CPU is fixed by my PR https://github.com/sourcelair/xterm.js/pull/128

**Comment by Tyriar** [comment]
This will probably be fixed by sourcelair/xterm.js#128 as well as there will no longer be a bazillion DOM manipulations when running `ls -lR /usr/share`.
