### ISSUE TITLE
Debugging an extension steps into extensionHostProcess.js and then has poor performance

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74845]
This may be related to https://github.com/microsoft/vscode/issues/53414.. Sometimes when I'm debugging an extension and I press Step Into, it will step into the `extensionHostProcess.js` file. This file is huge and causes really bad performance (the syntax colouring goes wonky too - I don't know if that's related to the poor performance).

I don't ever want to step into this file. If I'm stepping through my TS and pressing Step Into, it's probably because I expect it to skip VS Code's JS and just step into my own functions when they come up (this is faster than having to swap between pressing F10 and F11 when trying to get to the right place).

<img width="1355" alt="Screenshot 2019-06-04 at 2 05 57 pm" src="https://user-images.githubusercontent.com/1078012/58881674-91454180-86d2-11e9-80cc-17775608aeba.png">

<img width="1226" alt="Screenshot 2019-06-04 at 2 09 48 pm" src="https://user-images.githubusercontent.com/1078012/58881739-b46ff100-86d2-11e9-94f4-009baebef4df.png">

I can't see any obvious way to prevent this (since https://github.com/microsoft/vscode/issues/53414 seems like it was designed to do this). Is it possible? (I have `smartStep: true` in my launch config, though I think that's default now anyway).

**Comment by weinand** [comment]
The issue is missing sourcemaps (which we are going to add again soon).

**Comment by DanTup** [comment]
In most cases I don't want to step into this code at all (I wanted to treat it like external code, similar to in C# ticking "just my code" in Visual Studio). Is there a way to do that? The issue here isn't just the perf issue, but the confusion of stepping through your own code and ending up in someone elses.

**Comment by weinand** [comment]
@DanTup please see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome

**Comment by DanTup** [comment]
Aha, thanks! Though it's not obvious the best way to skip for the VS sources... Something like `**/app/out/vs/**.js`? (seems like the more specific I can be the better, but since this will be committed in launch.json, it should be fairly portable, inc. between macOS and Windows, so no hard-coding the Code install location!).
