### ISSUE TITLE
Editor font-family 'Droid Sans Mono' is not working without installing the font on OS

### ISSUE THREAD

**Issue by renanbaggio** [Microsoft/vscode#7485]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 16.04 (Linux 4.4.0)

I have been using Visual Studio Code v1.1 about a month and after I updated it to v1.2 the font 'Droid Sans Mono' is not working on editor, having fallback to monospace:

![vs-code-editor-font](https://cloud.githubusercontent.com/assets/2215806/15936524/bc8dc750-2e41-11e6-8346-988b2fd8491d.png)

I installed then the 'Droid Sans Mono' font on my OS and is working now, but I think this could be a problem to other people

**Comment by renanbaggio** [comment]
I guess this is not an issue. Sorry for the misunderstanding

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/5742
