### ISSUE TITLE
Runaway tsserver.js process using >300% of CPU 

### ISSUE THREAD

**Issue by danrosenthal** [microsoft/vscode#74854]
Issue Type: <b>Performance Issue</b>

`399	2130	60823	             electron_node tsserver.js `

Opening VSCode in any project on my machine results in a runaway process that consumes a huge amount of CPU. This is without running anything on my machine, only opening `@shopify/polaris-react` library. It breaks TypeScript functionality (type peaking, etc.), intellisense, etc., and makes my computer's fan sound like it is about to achieve low earth orbit.

I've seen a number of other issues related to this process, so it's clearly not just a problem for me.

Things I've done to attempt to fix:

- disable all extensions
- nuke node_modules and reinstall
- kill runaway processes
- using VSCode's TS version (3.4.5) instead of ours (3.2.4)

None of it resolves. The next time I open VSCode it's right back up over 300% CPU usage. Please fix this

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   115	 58696	code main
    0	    98	 58807	   gpu-process
    0	   311	 58839	   window (InterimTheme.tsx — polaris-react)
    0	     0	 58843	     /usr/local/bin/bash -l
    0	   311	 58853	     extensionHost
    0	    98	 59227	       electron_node server.js 
    0	   147	 59228	       electron_node eslintServer.js 
    0	    49	 60506	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=58853
  385	  2130	 60637	       electron_node tsserver.js 
    0	    82	 60640	         electron_node typingsInstaller.js typesMap.js 
    0	    49	 58975	     watcherService
    0	    49	 59230	     searchService
    0	    82	 59223	   shared-process
    0	    82	 60524	   window (Process Explorer)
    0	    82	 60792	   window (Issue Reporter)
    0	     0	 60800	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (InterimTheme.tsx — polaris-react)
|    Folder (polaris-react): 16662 files
|      File types: map(4179) js(3906) gz(1579) scss(927) ts(759) html(410)
|                  tsx(326) md(174) json(89) svg(42)
|      Conf files: package.json(4) tsconfig.json(3) webpack.config.js(2)
|                  launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
vscode-scss|mrm|0.6.2
vsliveshare|ms-|1.0.311
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.3.2
vscode-jest|Ort|2.9.2
vscode-graphql|Pri|0.1.8
stylelint|shi|0.49.0
spellchecker|swy|1.2.13

(1 theme extensions excluded)

</details>

**Comment by danrosenthal** [comment]
|Code process explorer|
|-|
|<img width="912" alt="Screen Shot 2019-06-04 at 4 34 35 PM" src="https://user-images.githubusercontent.com/1403188/58912207-8b0d9000-86e7-11e9-98c1-bd5428282260.png">|

**Comment by danrosenthal** [comment]
|VSCode's TypeScript Output console|
|-|
|<img width="1165" alt="Screen Shot 2019-06-04 at 4 41 48 PM" src="https://user-images.githubusercontent.com/1403188/58912292-b85a3e00-86e7-11e9-9557-fbaf02b3c5d5.png">|

**Comment by danrosenthal** [comment]
https://www.youtube.com/watch?v=1Isjgc0oX0s

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mjbvz** [comment]
Also, what version of TypeScript are you using in your workspace?

**Comment by danrosenthal** [comment]
>  Also, what version of TypeScript are you using in your workspace?

Workspace version is `3.2.4`

**Comment by danrosenthal** [comment]
> Does this reproduce in the latest VS Code insiders build?

@mjbvz yes 

|Insiders build process explorer|
|-|
|<img width="912" alt="Screen Shot 2019-06-04 at 4 53 22 PM" src="https://user-images.githubusercontent.com/1403188/58913033-5d294b00-86e9-11e9-81f5-b2e543119f24.png">|

**Comment by mjbvz** [comment]
@danrosenthal And this was using the latest TS (3.5.1) on the insiders build?

**Comment by danrosenthal** [comment]
@danrosenthal And this was using the latest TS (3.5.1) on the insiders build?

That's right

**Comment by danrosenthal** [comment]
Any more information I can give you @mjbvz?

**Comment by Aleksion** [comment]
I left a comment of one of the many other issues regarding this:

- Started happening AFTER 1.33 (downgrading to 1.32.3 completely solves this)
- Happens with TS 3.5.1 as well as 3.3.3 (though 3.5.1 seems to run stable for longer

I wasn't running tsserver with verbose when it happened last so I don't have a usable log. But when it happens the `electron_node tsserver.js` spikes up to 100-300% of CPU

<img width="710" alt="Screen Shot 2019-06-04 at 6 32 26 PM" src="https://user-images.githubusercontent.com/3367641/58924498-e3995900-86f8-11e9-9cf0-7b573f7cb43b.png">
 
I might try again, but the editor gets completely unusable for me so I'm downgrading to 1.32.3 in the interrim

**Comment by danrosenthal** [comment]
Thanks for the tip @Aleksion! I'll downgrade as well so I can continue working, as this problem also makes the editor unusable for me.

For anyone else struggling with this, here's a guide on how to downgrade: https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode

**Comment by danrosenthal** [comment]
Unfortunately I'm still seeing massive CPU spikes in `1.32.3` as well.

|:crying:|
|-|
|<img width="897" alt="Screen Shot 2019-06-05 at 8 25 03 AM" src="https://user-images.githubusercontent.com/1403188/58956089-7ffc4380-876b-11e9-91e2-2741745b8e40.png">|

**Comment by danrosenthal** [comment]
Unfortunately this did not solve for me. Still seeing massive CPU spikes, and the editor is still unusable.

|:cry:
|-|
|<img width="897" alt="Screen Shot 2019-06-05 at 8 25 03 AM" src="https://user-images.githubusercontent.com/1403188/58956359-247e8580-876c-11e9-8460-2ad76e5ad522.png">|

**Comment by danrosenthal** [comment]
For now, I'll just be over here using Atom with the https://atom.io/packages/atom-typescript plugin

**Comment by danrosenthal** [comment]
Quick update, I seem to have found a happy place having upgrading our TS version to 3.5.1 and using the Insiders Build of VSCode which also runs 3.5.1. It's a bit of a bandaid, but I'm at least back to being able to work productively

**Comment by mjbvz** [comment]
Yes, please make sure you are using the latest TS version (3.5.1) on the latest VS Code version (1.3.5). There are some important performance fixes in these latest versions. Let me know if you see this again with those versions or newer
