### ISSUE TITLE
Feat req: "Organize All Imports Within Folder"

### ISSUE THREAD

**Issue by corysimmons** [microsoft/vscode#74855]
Organize Imports is really nice, but would be better as a lint tool (kinda annoying when it trashes useful imports while I'm tinkering around, and all anyone should really care about is organizing all this stuff as a `precommit` lint step).

Is this code available anywhere that could be broken out into a CLI? Or added to the context menu of folders in the sidebar?

Thanks for all your hard work.

**Comment by egamma** [comment]
@corysimmons what language/what extension are you using?

**Comment by corysimmons** [comment]
I'm using Javascript and currently doing:

```
"editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
```

This works as expected on file save.

My question is more about adding new functionality: add a command when you right-click on a folder in the sidebar to _"Organize Imports in all files recursively in this folder"_

Alternatively, and better, point me to your existing `organizeImports` code, and as long as it's JS, I can pull it out and create a CLI to put on npm, so people can do something like:

```js
// package.json
{
  "scripts": {
    "precommit": "organize-imports ./src/**/*"
  }
}
```

The reason I'd like to do this is because I will _frequently_ be tinkering around with something and comment out some code that might include a function, then VSCode's `organizeImports` will remove the function I just wanted to temporarily comment out.... so I have to type it back in every time...

This sucks:

```js
import { truncate } from 'lodash'
import truncate as truncate2  from 'truncate'

console.log(truncate('hi-diddly-ho there, neighborino'))
console.log(truncate2('hi-diddly-ho there, neighborino'), 4)
```

```js
// Might want to comment out one line and just see what the other produces

import { truncate } from 'lodash'
import truncate as truncate2  from 'truncate'

console.log(truncate('hi-diddly-ho there, neighborino'))
// console.log(truncate2('hi-diddly-ho there, neighborino'), 4)
```

```js
import { truncate } from 'lodash'
⚠️

console.log(truncate('hi-diddly-ho there, neighborino'))
// console.log(truncate2('hi-diddly-ho there, neighborino'), 4)
```

```js
// Might want to uncomment it and comment out the other
⚠️
⚠️

// console.log(truncate('hi-diddly-ho there, neighborino'))
console.log(truncate2('hi-diddly-ho there, neighborino'), 4) // crap I lost truncate2 earlier... time to retype `import truncate at truncate2 from 'truncate'`
```

Seems stupid, but installing/importing an npm pkg to try it out in place of another pkg pops up _a lot_ for me, and I find myself retyping imports all the time.

**Comment by corysimmons** [comment]
All this to say, if you guys release a CLI like https://npm.im/@microsfot/organize-imports-cli I think almost everyone would migrate from using the VSCode onSave setting, to just doing `"scripts": { "precommit": "organize-imports ./src/**/*" }` and it'd be a much nicer experience.

**Comment by mjbvz** [comment]
For use in VS Code, try this extension: https://marketplace.visualstudio.com/items?itemName=bierner.folder-source-actions

We don't have any plans to make an organize imports command line tool part of VS Code, but this is something TypeScript is exploring: https://github.com/microsoft/TypeScript/issues/29288

**Comment by corysimmons** [comment]
Amazing they are already talking about it. Thanks.

**Comment by thorn0** [comment]
@corysimmons Have a look at https://www.npmjs.com/package/organize-imports-cli

**Comment by corysimmons** [comment]
Nice! https://github.com/aladdin-add/eslint-plugin-autofix also supports this functionality for anyone interested.
