### ISSUE TITLE
Explorer does reveal on refresh even when auto-reveal is turned off

### ISSUE THREAD

**Issue by mhermher** [microsoft/vscode#74851]
Issue Type: <b>Bug</b>

Turn off `Explorer : Auto Reveal` in preferences

Open a file leave it in focus.
Scroll explorer to another location.
Refresh explorer.

The bug:
The explorer jumps to the location of the in-focus file rather than staying in place.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.4.1
xml|Dot|2.5.0
gitlens|eam|9.8.1
gc-excelviewer|Gra|2.1.32
vscode-ebnf|igo|1.0.3
r|Iku|1.0.9
sublime-babel-vscode|jos|0.2.10
linter-gfortran|krv|2.1.0
python|ms-|2019.5.17517
cpptools|ms-|0.23.1
vsliveshare|ms-|1.0.311
material-icon-theme|PKi|3.8.0
vscode-yaml|red|0.4.1
r-lsp|REd|0.1.0
vba|spe|1.2.0
pdf|tom|0.5.0
highlight-matching-tag|vin|0.9.2
markdown-pdf|yza|1.2.0

</details>

**Comment by isidorn** [comment]
I can not reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Can you reproduce, or are you doing something different than me?

![hello](https://user-images.githubusercontent.com/1926584/58941380-ee490200-877b-11e9-98d8-e7a0ed8f2c2a.gif)

**Comment by mhermher** [comment]
Sorry, I was unclear. I mean the the refresh button 🔄 (next to a few other buttons like new file, etc.) on the explorer pane which just refreshes the explorer pane, not the entire window. Don't really know how to make a high res gif like yours to demonstrate. But here is an image of the button:

![Screen Shot 2019-06-05 at 9 32 15 AM](https://user-images.githubusercontent.com/10067803/58973487-edf93880-8774-11e9-827c-86d584c9da0f.png)

**Comment by isidorn** [comment]
@mhermher thanks for claryfing.. You can try vscode insiders next week since it will have the fix for this issue.
