### ISSUE TITLE
Inconsistent IntelliSense Performance

### ISSUE THREAD

**Issue by purplecones** [microsoft/vscode#74852]
- VSCode Version: Version 1.34.0 (1.34.0)
- OS Version: 10.14.5

Steps to Reproduce:

1. run 'code --disable-extensions'
2. Open any .js file in the project
3. Type 'log'

![2019-06-04 11 54 33](https://user-images.githubusercontent.com/136654/58906707-80003300-86da-11e9-9b25-a25b5831cdb1.gif)

Notice how the first time it was pretty quick but the subsequent IntelliSense popups are delayed. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) (VS Code 1.35)?

**Comment by purplecones** [comment]
Sorry, I had checked that link and saw version 1.34 at the top and thought I was running the latest version already. I don't experience this issue with VSCode Insiders so thank you for the suggestion.
