### ISSUE TITLE
Macros not working in remote development

### ISSUE THREAD

**Issue by tjcarskadon** [microsoft/vscode#74856]
- VSCode Version: 1.35.0-insider
- OS Version: macOS 10.14.5

Steps to Reproduce
1.  Create a macro in settings.json
2. Create a keyboard shortcut to trigger that macro
3. Connect to remote host
4. Trigger macro

You should see an error that says `macros.TheNewMacroYouMade` not found

Does this issue occur when all extensions are disabled?: Yes

I found this when trying to trigger the macro I use to return to Normal mode in vscodevim.  However I tested it using native functionality. 

Here is the macro I set up from my `settings.json`
```
"macros": {
        "macroTest": [
            "workbench.action.terminal.new"
        ]
    },
```
Then  in ` keybindings.json` I have this:

```
{
    "key": "shift+alt+cmd+s",
    "command": "macros.macroTest"
},

```

Would be really great to have macros back.

Thanks!!!

**Comment by egamma** [comment]
>Create a macro in settings.json

VS Code doesn't support macros, what extension are you using?

**Comment by tjcarskadon** [comment]
Oh no!!  I set this up so long ago I forgot it was an extension.  

Sorry for bothering you with a non issue.  I got it to work.  

Thanks for the quick response
