### ISSUE TITLE
[Improvement] The `.desktop` extension as a properties file, is incorrectly highlighted

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#74866]
- VSCode Version: VSCode Insiders 1.35.0-insider 0284236851a
- OS Version: Arch Linux 64bits

Notice that the tags with brackets are not correctly highlighted and the first word in the keywords is not grey and italic:

![image](https://user-images.githubusercontent.com/2257024/58921927-30882a00-870f-11e9-8e68-70723cdb24e9.png)

@remcohaszing, @roblourens, @alexandrudima and @aeschli

**Comment by egamma** [comment]
The .desktop file suffix is defined as an ini file type in the bundled ini extension

**Comment by alexr00** [comment]
Based on some [documentation of .desktop files](https://wiki.archlinux.org/index.php/Desktop_entries), .desktop should not be an ini file type. In ini, comments are done with `;` but in .desktop, `;` is a list separator.

I'll remove `.desktop` from the ini extension. I don't see a better place for it, so it will go back to unhighlighted.

**Comment by gusbemacbe** [comment]
@alexr00 

Hey, no, here Gedit (official text editor of GNOME and Ubuntu), Kate (official of KDE environment) and Medit syntax-highlights `.desktop` files. Here is like in Gedit:

![image](https://user-images.githubusercontent.com/2257024/58976985-1ac24580-879f-11e9-80d4-5ba476d2dd57.png)

**Comment by alexr00** [comment]
Highlighting .desktop files correctly is a great candidate for an extension: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
