### ISSUE TITLE
SyntaxError: Unexpected identifier error in integrated terminal

### ISSUE THREAD

**Issue by Piscean** [Microsoft/vscode#7486]
- VSCode Version: 1.2.0
- OS Version: 1511 (10586.420 Enterprise)

Steps to Reproduce:
1. Set VS Code as the system's default app for opening .txt files
2. Launch the integrated terminal
3. CD to a directory with a .txt file  
4. Type the txt file name and hit Enter

Output in terminal:
C:\Temp>C:\Temp\test.txt:2
 More characters. More characters. More characters.
      ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:154:18)
    at node.js:416:3

**Comment by Tyriar** [comment]
@piscean does this same occur using a regular cmd prompt? I'm assuming this us Windows.

**Comment by Piscean** [comment]
Yes, Windows.

When I do this from a regular cmd prompt, it works correctly.  There is the debug spew mentioned in https://github.com/Microsoft/vscode/issues/5698, but not the syntax error dump mentioned above.

**Comment by Tyriar** [comment]
Closing as this was likely fixed after the winpty upgrade.
