### ISSUE TITLE
Support icon definition per folder in workspaces

### ISSUE THREAD

**Issue by michaeljota** [microsoft/vscode#74863]
Currently, only one icon definition can live at the same time. As this is fine in most use cases, as developer we could have different kind of projects that might have name-sake files but with different meaning for those files.

For a clear example of this look: vscode-icons/vscode-icons#1925

TL;DR: The use case exposed there is this one: 
- You have an Angular project and a NestJS project in the same folder. 
- You have installed vsicons for Icons definitions.
- You want to be able to tell vsicons to use the Angular definition in the Angular folder, and the NestJS definition in the Nest folder. 

Current: You can only choose one of two, and save it in the settings file (or folder.code-workspace file)

Desired: Be able to define the icon definition per folder. 

```md
| - angular
  | - setting.json // icon: preset angular
| - nest
  | - setting.json // icon: preset vscode

```
PD: I try to search about this, but I didn't find any thing. Sorry if this is duplicated.

**Comment by McVulcan** [comment]
Need this... Want to use both angular and nest preset together
