### ISSUE TITLE
There is no way to enable the context menu in "Variables"

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#74876]
- VSCode Version: 1.34.0
- OS Version: win10

Steps to Reproduce:
1. Open the sample "Mock debug" project
2. set some break points in "readme.md" file
3. debug the readme.md
4. right click on the items in "variables" window

result: The "copy value" menu item is always disabled
![image](https://user-images.githubusercontent.com/2315155/58938810-4eee3400-87a8-11e9-964d-ad97c6f8dc6a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
The "Copy Value" is not enabled because the "Variables" returned from the Mock Debug Adapter don't return an "evaluateName" attribute. Without that VS Code doesn't know how to evaluate a variable in order to get its value.

**Comment by whlkw** [comment]
Thanks! It works!
