### ISSUE TITLE
Remote Smoke: Goto page finds welcome page on remove

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#74875]
Running the remote smoketest against a build shows that search returns more results in a remote window than in a local window.

In a remote window, the results contains the welcome page, where as in a regular window they don't.

- checkout distro
- Run `yarn smoketest --remote --build ~/vscode/1.35.0-insiders/VSCode-linux-x64/`

I added a workaround so the smoke tests passes: 
https://github.com/microsoft/vscode/blob/be547e26fcdea146dab7abad622a9cf8ff187ac9/test/smoke/src/areas/multiroot/multiroot.test.ts#L50

**Comment by roblourens** [comment]
We handle this for text search but not file search. I can't repro in the product with `*.*` but I can by just searching 'welcome' with the welcome page open.

**Comment by aeschli** [comment]
The workaround is still there:
https://github.com/microsoft/vscode/issues/74875#L50

Shouldn't it be gone a result of the fix?

**Comment by roblourens** [comment]
Fixed, thanks
