### ISSUE TITLE
No borders in zen mode when unmaximised

### ISSUE THREAD

**Issue by tejasvi** [microsoft/vscode#74877]
I sometimes snap the window to right while looking something up in the browser to the left. Therefore the borders in zen mode are unhelpful here.

**Comment by isidorn** [comment]
Can not reproduce.
First of all, if the window is no longer full screen zen mode will exit automatically.

What platform are you on? Please provide exact reproducable steps.

**Comment by tejasvi** [comment]
> Operating System: Kubuntu 19.04
> KDE Plasma Version: 5.15.4
> KDE Frameworks Version: 5.56.0
> Qt Version: 5.12.2
1. Open vscode.
2. Toggle zen mode.
3. Win + > (Shortcut to snap window to the left)

**Comment by isidorn** [comment]
This is an electron issue, that on your OS the snap window to the left is not detected as an onDidChangeFullscreen event.  Please file this against electron https://github.com/electron/electron
You can use electron fiddle to create a reproducable sample https://github.com/electron/fiddle

Unless you have some vscode settings which you did not share here. If that is the case please let me know and I can reopen.
