### ISSUE TITLE
Auto reveal the file in errors view on open

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#7487]
Auto reveal the file in errors view on open

**Comment by Tyriar** [comment]
@sandy081 should probably reuse `explorer.autoReveal` rather than adding a new config imo.

**Comment by sandy081** [comment]
@Tyriar Yah I thought so initially and in favor of doing that. But I felt users would like to have a separate conf as they are two independent features.

I will also take the team's opinion today and change it as per that.

Thanks.

**Comment by joaomoreno** [comment]
@Tyriar this is to reveal the file **in the errors view** not the explorer.

Separate setting makes sense to me. `problems.autoReveal`, `boolean`.
