### ISSUE TITLE
Multiple Tabs showing during extention installation

### ISSUE THREAD

**Issue by kamleshvaghela-crest** [microsoft/vscode#74873]
Install SQL Server Extention and click on various tabs like details, contribution, etc..

**Comment by kamleshvaghela-crest** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/15341238/58938023-a0d78f80-8791-11e9-96da-b8c9a9d85262.png)

Attaching Screenshot

**Comment by sandy081** [comment]
@kamleshvaghela-crest I cannot reproduce this. Which version of VS Code are you on?

**Comment by kamleshvaghela-crest** [comment]
@sandy081 
Version: 1.34.0 (system setup)

![Screenshot (36)](https://user-images.githubusercontent.com/15341238/59021295-2da14c80-8869-11e9-97e5-9e8d39adcacd.png)

**Comment by sandy081** [comment]
Can you please try with latest stable? 
Also open the dev tools to see if there are any errors?
Is it happening only with this extension or others too?
