### ISSUE TITLE
during debugging the process cannot open directory after a space 

### ISSUE THREAD

**Issue by DipadityaDas** [microsoft/vscode#74879]
Dipaditya Das@DIPADITYA-PC MINGW64 ~/Documents/Python Programs
$ cd "c:\Users\Dipaditya Das\Documents\Python Programs" ; env PYTHONIOENCODING=
UTF-8 PYTHONUNBUFFERED=1 C://intelpython3//python.exe "\"c:/Users/Dipaditya Das
/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py
\"" --default --client --host localhost --port 53905 "c:\Users\Dipaditya Das\Do
cuments\Python Programs\app.py"
C:\intelpython3\python.exe: can't open file '"c:/Users/Dipaditya Das/.vscode/extensions/ms-python.python-2019.5.17517/pythonFiles/ptvsd_launcher.py"': [Errno 22] Invalid argument
![Screenshot (56)](https://user-images.githubusercontent.com/32407694/58939895-ce263c80-8795-11e9-8bb3-268a18b2e200.png)
![Screenshot (57)](https://user-images.githubusercontent.com/32407694/58939896-ce263c80-8795-11e9-8b2b-a8242db8423b.png)

**Comment by weinand** [comment]
@DipadityaDas This should be fixed in Insiders and the upcoming May stable release.
