### ISSUE TITLE
Allow to disable the snapping feature of parts when using the mouse to reveal/hide

### ISSUE THREAD

**Issue by kalpaj12** [microsoft/vscode#74874]
Vscode version: 1.34.0
OS: Linux x64 5.0.0-15-generic

Can [this](https://drive.google.com/open?id=1qBM9Xdz9k4M47m8iSyQurSPfaT6EvnQe) be fixed? 

P.s. if the video doesn't load, please try downloading it. Option to download is available on the top right in the link.

**Comment by egamma** [comment]
Video loads fine, thanks. Can you please be more specific about what you want to see fixed in the video.

**Comment by kalpaj12** [comment]
In the video, do you see the mouse dragging an invisible portion and then all of a sudden the sidebar shows up? 

Could the side bar be displayed from the beginning of the drag?
