### ISSUE TITLE
New files no longer auto detect language

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#74882]
Issue Type: <b>Bug</b>

When creating a new file, i.e *.scss, *.js, VSCode no longer applies the correct language highlighting and remains at the program's default language, in my case this is HTML Liquid.

It requires manually selecting the correct language from the bottom right corner. (Note: When doing this, the "Auto Detect" option works as expected.

![image](https://user-images.githubusercontent.com/18140157/58941469-c2298300-8773-11e9-9bca-7cb148e63998.png)
![image](https://user-images.githubusercontent.com/18140157/58941484-cce41800-8773-11e9-902c-74c4dbca56b3.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
language-hugo-vscode|bud|0.11.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
octobercms-template-language|dqs|0.2.3
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
vscode-cdnjs|Jak|0.18.0
vscode-liquid-snippets|kil|1.2.0
vue|liu|0.1.5
rainbow-csv|mec|1.1.1
dotenv|mik|1.0.1
vscode-autoprefixer|mrm|2.2.0
vuejs-extension-pack|mub|1.1.3
language-liquid|nei|0.1.1
vetur|oct|0.21.0
laravel-blade|one|1.20.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.2.9
stylelint|shi|0.49.0
shopify-liquid|sis|1.6.5
vscode-status-bar-format-toggle|tom|1.5.0
json2yaml|tux|0.2.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Cannot reproduce. I tried:

- Create a new `test.js` file in the explorer
- Add some JS code

The file is properly colored.
Do this steps not work for you?
Can you try with disabled extensions?
What are your steps to reproduce the problem.

**Comment by ConduciveMammal** [comment]
> * Create a new `test.js` file in the explorer
> * Add some JS code

Hey @egamma,

So it seems like this problem occurs when creating the file from within VSCode.

Ahh! I just disabled my extensions and it's worked. Hmmm it must be one of them then.

**Comment by egamma** [comment]
I suggest to selectively disable the extensions in the Extensions Viewlet and then to report the issue against the extension.
