### ISSUE TITLE
Make problems/errors more visible (red icon in statusbar)

### ISSUE THREAD

**Issue by joeytwiddle** [microsoft/vscode#74886]
The problem: Sometimes I have a compilation error in my app (TS code), but I am not aware of it because VSCode does not make it clear enough.

Currently VSCode displays errors in the following places:
- The list in the Problems panel
- A red highlight and a count on the file in the file explorer (and containing folders)
- Wiggly underlines in the file itself
- Error and warnings counts in the left of the sidebar (see image below)

But they all have limitations:
- I don't have enough screen space to keep the problems panel open, so I only open it when I need it.
- A change I make might break a different file which is out of view in the file explorer.
- The wiggly lines don't help if I don't currently have that file open, or they are offscreen
- Therefore I am only left with the counts in the status bar. These are always visible. But they are too small to notice the change from 0 to 1.

Here are some suggestions, any one of which could help. My preference is for the first one.

1. **Offer a different colour for the statusbar counts, if the count is non-zero**.

   For example, I would use bright red for >0 errors, but a gentle indication for warnings.

   <img src="https://user-images.githubusercontent.com/911799/58944042-8e6e4d80-87b3-11e9-8775-e20b95961b92.png" width="200" /> Before

   <img src="https://user-images.githubusercontent.com/911799/58944115-b362c080-87b3-11e9-85d1-b8934df8adfa.png" width="200" /> After (not a huge difference, but should stand out just enough)

   Related: #64636 wants to hide the statusbar icons when the counts are zero.

2. Allow the list of problems to appear in the sidebar, below the Outline and Npm-scripts panes. (Even if closed, perhaps its title could display counts. and change colour.)

   <img src="https://user-images.githubusercontent.com/911799/58945319-384ed980-87b6-11e9-834c-c095dc615690.png" width="130" />

3. Display some red text in the statusbar when there are outstanding problems, perhaps showing the first one. ([This plugin](https://marketplace.visualstudio.com/items?itemName=JoeBerria.statusbarerror) has the right idea, but it only works for the current line!)

   <img src="https://user-images.githubusercontent.com/911799/58944637-d6da3b00-87b4-11e9-9055-d0de92091e69.png" width="370" />

4. Highlight tabs containing errors like we highlight files now. WebStorm does this. It might be nice, but I don't think it really solves the original problem, because these could still be out of view.

I am more concerned about errors than warnings, but other users may feel differently.

**Comment by misolori** [comment]
I could see us potentially adding a way to theme the problems/warning icons + text when an item appears. @sandy081 maybe this could fit in #74921 as well.

**Comment by sandy081** [comment]
Yeah this can be made a dup of #74921

/duplicate

**Comment by misolori** [comment]
Re-opening since the original duplicate only handled icons. A few thoughts on the original proposal:

> Offer a different colour for the statusbar counts, if the count is non-zero.

We could offer this as an optional theme color token but our default themes would not get this as we use blue in our status bar and any other foreground color would make it unreadable.

> Allow the list of problems to appear in the sidebar, below the Outline and Npm-scripts panes

This should already be possible in the next release (1.42) with https://github.com/microsoft/vscode/issues/85164

> Display some red text in the statusbar when there are outstanding problems

Coloured text is the same as the first ask, and showing problems for the current line is already possible via `problems.showCurrentInStatus`

> Highlight tabs containing errors like we highlight files now

I don't think we'd be able to do this as we already use highlighted tabs for active tabs and that would not make it accessible (can't use color alone to define meaning)
