### ISSUE TITLE
Unable to "Reset Zoom" on macOS with Cmd+0

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74885]
If I zoom with `Cmd`+`=` on macOS, I can't reset the zoom with `Cmd`+`0` (which I'm reasonable sure used to work). Nothing happens.

Interestingly the keybinding in the menu shows as `Cmd`+`NumPad0` so I don't know if that's why - but on a MacBook there is no number pad.

I'm guessing it's unintentional for `Cmd`+`0` not to reset here?

**Comment by sercheo87** [comment]
@DanTup The key binding system is written in such a way that you can change absolutely everything and this use-case is one of the most simple:

Open _Preferences_ > _Keyboard Shortcuts_
Type "**Reset Zoom**"
Click the **edit icon**
Record new keybinding
Done!

**Comment by DanTup** [comment]
I understand that, but I'm questioning the default :-) I'm pretty certain it never used to be this, and I'm not sure if the change was accidental.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by DanTup** [comment]
@bpasero it's exactly the same there. Though I noticed that Cmd+0 is actually bound to "View: Focus into Side Bar" now.

So it seems like this may be deliberate, however it seems like a weird change given most laptops don't have a number pad and `Cmd`+`0` resets zoom in other apps.

**Comment by DanTup** [comment]
Looks like there were some comments about this here from @sandy081 and @alexandrudima:

https://github.com/microsoft/vscode/issues/14979#issuecomment-265709227

Based on the date, it seems like it must've been broken for way longer than I thought, but it still seems like a strange choice :(

**Comment by bpasero** [comment]
Also adding @rebornix since Alex is out.

**Comment by rebornix** [comment]
Like Alex mentioned in #14979, we use cmd+0 for focusing into the side bar and we use `cmd+digit` for focusing view parts all over the place. That's why we can't bind `cmd+0` to reset zoom.

**Comment by alexandrudima** [comment]
Well, `cmd+0` is bound by default to "Focus into Side Bar" and I think that was there since before we added zooming actions:
![image](https://user-images.githubusercontent.com/5047891/62113953-e4dca180-b2b5-11e9-98d0-4ac859eb2dd4.png)

I agree that the situation is not great, but I won't tweak the default keybindings since anyone can easily tweak them on their machine.
