### ISSUE TITLE
Timeout due to certificate error during "ext install"

### ISSUE THREAD

**Issue by KeithBallard** [Microsoft/vscode#7489]
- VSCode Version: 1.2
- OS Version: Windows 7

I realize that this has been brought up tangentially in a few other issues (#69 and #155).  However, the issues resolved in both of those are not my current issue.

At my company, market.visualstudio.com is issued a certificate after the https traffic is intercepted.  It seems that VS Code uses the IP 191.238.172.191 when trying to browse/install extensions, which causes a cert problem because the cert was issued to market.visualstudio.com, causing a mismatch.  If I browse to 191.238.172.191, IE and firefox complain, but market.visualstudio.com works just fine.  The computer does not use any proxy settings so the "http.proxyStrictSSL": false setting does not help.  Why is the IP address being used in the first place instead of the hostname?

Any suggestions?

**Comment by joaomoreno** [comment]
We use the address. Your computer resolves it to that IP address.

Can you show us a screenshot of the error?

**Comment by KeithBallard** [comment]
The error looks like:
![vscodeerror](https://cloud.githubusercontent.com/assets/19842971/16011063/261cbeb8-3141-11e6-9776-e0ee529befb7.PNG)

Any browser or utility I use (like ping) does not resolve it to the IP (as I understand it).  If I go to market.visualstudio.com in a browser, all is good.  If I use the IP there is a cert error because my company assigned the cert to "market.visualstudio.com" not the ip.  Maybe I am misunderstanding something.

**Comment by joaomoreno** [comment]
So... if you run `ping marketplace.visualstudio.com` what IP do you get?

**Comment by KeithBallard** [comment]
Ah, I have misunderstood some things.  Sorry about that.  First, you question was on point: I am using a proxy, though it is automatically detected by most applications.  There is no system level proxy settings.  This is not a VS Code problem, but an issue with proxy settings.

I will close this in a bit or you can close it, but I was wondering as an aside: will auto detect proxy settings make it into VS Code at some point?

**Comment by joaomoreno** [comment]
Yes we absolutely want to get there. Can you show me how your wpad proxy is configured in your system?

**Comment by KeithBallard** [comment]
Well, I can't link my companies wpad file, but it was located at http://wpad/wpad.dat and contained what appears to be a JavaScript function?  I am no expect in WPAD files, but it looks like JS.  

The function:
 1) Calls for the DNS to resolve the hostname
 2) Checks that the URL meets on of many criteria (in network, ftp, etc.) returns "DIRECT"
 3) If not matched with a special case then it returns "PROXY <proxy hostname>:<proxy port>"

Does that help?  That is about all the info I can give on our WPAD, but I would assume it would be similar for other companies.  Let me know if that helps.
