### ISSUE TITLE
Problem with completion

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#74894]
sometime javascript doesn't complete some functions. See the next picture.

![er](https://user-images.githubusercontent.com/42807112/58958366-097b3800-87a3-11e9-96f1-f52b070bc5f2.jpeg)

It must complete `charAt` function but it doesn't. So, is there a solution to this problem?

**Comment by mjbvz** [comment]
You need to mark `str` as a string using a [jsdoc](http://usejsdoc.org) annotation:

```js
/**
 * @param {string} str
 */
function foo(str) {...}
```

There is not enough context in your code to infer that `str` should be a string otherwise

**Comment by minkir014** [comment]
but I noticed another problem with hovering like this



![er](https://user-images.githubusercontent.com/42807112/58993709-93042780-87ee-11e9-85e4-bd7fea7b2361.jpeg)



It must tell me that the function returns number not any.
