### ISSUE TITLE
Delete vscode-nsfw

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#74897]
I tried investigating what is the difference between `nsfw` and `vscode-nsfw`. I might be wrong, but there seems to be no different right now, so it looks like `vscode-nsfw` is just debt. Commits from @Tyriar and @alexandrudima are in the upstream project.

I suggest to just depend on `nsfw` and delete `vscode-nsfw` from npm and github.

**Comment by Tyriar** [comment]
Here's the diff, we're 2 commits ahead and 18 behind (removing win_delay_load_hook and updating nan):

https://github.com/Axosoft/nsfw/compare/master...microsoft:vscode

The win_delay_load_hook thing is on the upstream (https://github.com/Axosoft/nsfw/commit/c3fa0754953f13262cb3b4995b5fec5b5ae6de1a) but the update to nan isn't so I don't think we can update and keep Electron 5 support?

**Comment by bpasero** [comment]
We should not invest here, but rather make chokidar work. I posted my initial testing results in https://github.com/paulmillr/chokidar/issues/860

I suggest to close this item given we still have changes in `vscode-nsfw` that are not upstream.

**Comment by joaomoreno** [comment]
My bad!
