### ISSUE TITLE
Feature request: command to focus "other" editor

### ISSUE THREAD

**Issue by photex** [Microsoft/vscode#749]
Howdy!

I see workbench actions for focusing left, right, or by a specific index, but not one to just hop to the "other" editor. 
The behavior I'm looking for is to hop between any open editors, but not automatically make another (as when I tried to just keep focusing to the right to see if it would just wrap around).

I'd be willing to work on this myself and generate a PR if someone has a hint on where to start looking into this.

**Comment by jrieken** [comment]
Did you try Cmd+1, Cmd+2, and Cmd+3?

**Comment by photex** [comment]
@jrieken yes, this is what I was referring to when I said "by specific index".
I'm interested in something more like cycling through opened editors, so if there are 2 editors and I'm in editor 1, triggering this would move to editor 2, triggering it again would move me back to editor 1.
If there are three, I'd hop from 1 -> 2 -> 3 -> 1 -> ... and so on.
I work on multiple platforms, so most keys that use Cmd I typically don't use. But Cmd+1/Cmd+2 are certainly handy.

**Comment by photex** [comment]
@jrieken as soon as I said "cycle" I realized what the search for! "workbench.action.cycleEditor"

**Comment by jrieken** [comment]
:-)
