### ISSUE TITLE
Compute number of problems after filter

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#74902]
Issue Type: <b>Feature Request</b>

The number of problems is written next to the Problem tab (see screenshot)

![Screenshot from 2019-06-05 16-50-40](https://user-images.githubusercontent.com/15984272/58966251-3daa2500-87b2-11e9-9ab0-b2968f5317c1.png)

It shows the number of problems before filtering them out.

This is great if one uses the filter like this:

> I have too many errors, I just want to look-up the one that interests me

But this is not great if one uses the filter like me:

> I have unwanted errors because of whatever reason, I will filter the _false positives_ out.

In this example I will think there are 3 errors while there isn't any:

![Screenshot from 2019-06-05 16-51-50](https://user-images.githubusercontent.com/15984272/58966257-3edb5200-87b2-11e9-92a4-69dd8c9eefd7.png)

In a perfect world there wouldn't be any false positives but the filter works perfectly for this.

Could we have a setting like `problems.computeNumberAfterFilter`?

Thank you

<details>
<summary>Version Info</summary>
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)

OS version: Linux x64 4.15.0-51-generic
</details>

**Comment by hwhung0111** [comment]
I'll take this.
