### ISSUE TITLE
Remote WSL: cannot start gdb for debugging

### ISSUE THREAD

**Issue by junfengy** [microsoft/vscode#74904]
- VSCode Version:  1.35.0-insider (user setup)
  Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
  Date: 2019-06-04T00:13:30.572Z
  Electron: 3.1.8
  Chrome: 66.0.3359.181
  Node.js: 10.2.0
  V8: 6.6.346.32

- OS Version: Windows_NT x64 10.0.18362

- launch.json attached.

Steps to reproduce:
1. Install Remote WSL extension
2. Install C/C++ extension in WSL
3. Try to debug a C/C++ program

Debug console outputs the following after I turned on logging:

1: (180) LaunchOptions</LocalLaunchOptions>
--> E (output): {"event":"output","body":{"category":"console","output":"1: (339) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 ; cd /home/junfeng/projects/p ; DbgTerm=`tty` ; set -o monitor ; trap 'rm /tmp/Microsoft-MIEngine-In-nll01xne.gc0 /tmp/Microsoft-MIEngine-Out-tyx7yb5g.3j2 /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 /tmp/Microsoft-MIEngine-Cmd-3tdso0q5.a4n' EXIT ; /usr/bin/gdb --interpreter=mi --tty=$DbgTerm < /tmp/Microsoft-MIEngine-In-nll01xne.gc0 > /tmp/Microsoft-MIEngine-Out-tyx7yb5g.3j2 & clear; pid=$! ; echo $pid > /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 ; wait $pid; \n"},"seq":28,"type":"event"}
1: (339) DbgCmd:echo $$ > /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 ; cd /home/junfeng/projects/p ; DbgTerm=`tty` ; set -o monitor ; trap 'rm /tmp/Microsoft-MIEngine-In-nll01xne.gc0 /tmp/Microsoft-MIEngine-Out-tyx7yb5g.3j2 /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 /tmp/Microsoft-MIEngine-Cmd-3tdso0q5.a4n' EXIT ; /usr/bin/gdb --interpreter=mi --tty=$DbgTerm < /tmp/Microsoft-MIEngine-In-nll01xne.gc0 > /tmp/Microsoft-MIEngine-Out-tyx7yb5g.3j2 & clear; pid=$! ; echo $pid > /tmp/Microsoft-MIEngine-Pid-mwewwoqm.bu4 ; wait $pid; 

![Capture](https://user-images.githubusercontent.com/3514460/58970178-e478cc00-8786-11e9-9697-981df88fe850.PNG)

**Comment by weinand** [comment]
Please set "externalConsole" to false.

**Comment by junfengy** [comment]
That fixed the issue.  Thanks!  I followed the docs at https://code.visualstudio.com/docs/cpp/config-wsl, which shows a launch.json with ""externalConsole": true".  It may need an update.

**Comment by weinand** [comment]
@gregvanl yes, we should mention in the doc that `"externalConsole": true"` doesn't make sense in remote scenarios.
