### ISSUE TITLE
PHP markdown bug with MySQL query inside a string combined with a single grave accent

### ISSUE THREAD

**Issue by pixelomer** [microsoft/vscode#74909]
- VSCode Version: 1.35.0
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

![An image is worth a thousand words](https://user-images.githubusercontent.com/37103802/58983039-824bb580-87de-11e9-9492-f52a80ec9988.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandhoners123** [comment]
ummm... not a duplicate

**Comment by sandhoners123** [comment]
not a duplicate

**Comment by alexr00** [comment]
This appears to be an issue with the PHP grammar. I have copied the issue to that repository.
