### ISSUE TITLE
Feature request: find: add a delete button (not replace with nothing)

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#74900]
OK, so you're a programmer, and I'm a programmer, and we've been programming forever, and we know that to remove something, you find it and replace it with nothing. In sed or vim you'd do `s/something//g`. 

In vscode you'd do:

![image](https://user-images.githubusercontent.com/172594/58965453-8a88fe00-87a8-11e9-944b-94d9f1e3f9e5.png)

I was using this recently and remembered something: **replace with nothing is really weird for new programmers**.

> How do I remove a word?

> Oh you just replace it with nothing

> 🤨

I know it's not a common feature in code editors, but **new programmers could be helped by adding an 'x' botton that removes the thing being looked for**.

This would do the same thing as replace with nothing, but be more intuitive.

**Comment by dmkato** [comment]
I'll take this one!
