### ISSUE TITLE
Language - Localization issue

### ISSUE THREAD

**Issue by yakubovski** [microsoft/vscode#74908]
Issue Type: <b>Bug</b>

After today's update my russian version of the editor looks like partly russian partly english (menus/dropdown menus/annotations etc). Can you fix this?

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:53.881Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-5200 APU with Radeon(TM) HD Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.46GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
vscode-language-pack-ru|MS-|1.34.2

</details>

**Comment by dbaeumer** [comment]
@danyeh are new language packs already published ?

**Comment by dbaeumer** [comment]
@yakubovski you need to make sure that you have the latest language pack (1.35) for Russian as well.

https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ru

**Comment by dbaeumer** [comment]
@danyeh looks like they are.

**Comment by danyeh** [comment]
Assume the new version of language pack fix the issue you encountered. @yakubovski , let us know if you still see issue.
CC: @weeteckt
