### ISSUE TITLE
[feature request] Outline view: multi-key sort

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#74907]
Currently (vscode 1.34), the items in the outline view can be sorted by:
* Position
* Name
* Type

It's great that I can select any sort key, but the problems is these sort keys are currently made exclusive, meaning that I cannot select 2 or more sort keys.

As a result one cannot sort the items by both Name and Type, like first by Type, then by Name. Additionally, if none of the sort options is selected, the items should be presented in their natural order, as if sorted by Position.

A mapping table between the proposed sort options and the old ones would be:

| Proposed | Old | Notes |
| --- | --- | --- |
| by Name | by Name | almost same, but with Position as implicit 2nd key |
| by Type | by Type | almost same, but with Position as implicit 2nd key |
| NONE | by Position | equivalent, i.e., remove by Position |
| by Name + Type | N/A | new, first by Type then by Name preferred |

By the way, when sorting by Type, it seems the methods are listed before the fields, why not the reverse? this is really a question though.

Thanks

**Comment by egamma** [comment]
// fyi @jrieken

**Comment by garkin** [comment]
4 states switch selector should enough:
- by Position, default
- by Name
- by Type and Position
- by Type and Name
