### ISSUE TITLE
Common breakpoint operations should be available in the command palette 

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#7490]
- VSCode Version: 1.2.0
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Open up the command palette
2. In the command portion type "breakpoint"
3. Notice that common breakpoint operations are not available

### Justification

VS Code does a great job of allowing the user to stay away from the mouse and have a keyboard-only experience.  There are common breakpoint operations (delete all breakpoints, disable all breakpoints, etc.) that developers use frequently to debug.  I believe that these common operations should be available in the command palette and also have configurable key bindings.

**Comment by isidorn** [comment]
@tstringer agree and I think this is a good opportunity for a PR - we already register other debug actions in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L105

So it should not be a lot of work to just add the ones which are missing in your opinion

**Comment by tstringer** [comment]
@isidorn :+1: sounds good, appreciate your support on this!  I'll start working on the code and get the PR through as soon as possible.

**Comment by tstringer** [comment]
@isidorn I've created the PR here: https://github.com/Microsoft/vscode/pull/7627 Let me know if this looks good or if there's something you want me to change. Thanks!
