### ISSUE TITLE
f string / extended unpacking *

### ISSUE THREAD

**Issue by mikheil83** [microsoft/vscode#74906]
Issue Type: <b>Bug</b>

f string and extended unpacking * yields to syntaxerror

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 1537)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|2.71GB (0.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.2
emojisense|bie|0.5.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.10
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-github|Kni|0.30.2
python|ms-|2019.5.18426
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.2.9
vscode-smoothtype|spi|1.2.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.7.0
jinja|who|0.0.8

(3 theme extensions excluded)

</details>

**Comment by egamma** [comment]
what language are you using? please provide steps for how to reproduce the problem.
