### ISSUE TITLE
'Run Python File in Terminal'not working

### ISSUE THREAD

**Issue by skmcgowan** [microsoft/vscode#74917]
Issue Type: <b>Bug</b>

After updating to version 1.35 (portable) right clicking and selecting 'run python file in terminal' is no longer working.  

Steps to reproduce:

Open a python file.
Right click in the editor.
Select 'Run python file in terminal'.
Focus is returned to the editor and no terminal opens.

The expected behavior is that the python file is executed in a new terminal window.
This is still present when disabling extensions (except the Python extension).

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2693)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
vscode-mysql|for|0.4.0
docs-yaml|Giz|0.1.12
vscode-simple-icons|Lau|1.11.7
dotenv|mik|1.0.1
python|ms-|2019.5.18426
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.1.0
autodocstring|njp|0.3.0
vscode-yaml|red|0.4.1
jinjahtml|sam|0.10.3
addDocComments|ste|0.0.8

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-python/issues/5916
