### ISSUE TITLE
Poor Terminal Performance

### ISSUE THREAD

**Issue by emreaydinceren** [microsoft/vscode#74914]
- VSCode Version:  1.35.0
- OS Version: Win 10 19H1

Tried with --disable-gpu,  didn't make any difference.
Tried with terminal.integrated.rendererType = dom , didn't make any difference.

Steps to Reproduce:

1. Open powershell in terminal
2. dir -Recurse

Does this issue occur when all extensions are disabled?: Yes
[Benchmark Profile-Fast.zip](https://github.com/microsoft/vscode/files/3258971/Benchmark.Profile-Fast.zip)
[Profile-Slow.zip](https://github.com/microsoft/vscode/files/3258972/Profile-Slow.zip)

**Comment by Tyriar** [comment]
So the fast one is using the canvas renderer and the slow one is using the DOM renderer. Could you set `terminal.integrated.rendererType` to `canvas` and do another profile on the slow machine?

**Comment by Tyriar** [comment]
Something else to try is setting `terminal.integrated.windowsEnableConpty` to false and relaunching the terminal, if that fixes the problem then this is a duplicate of https://github.com/microsoft/vscode/issues/74620

**Comment by emreaydinceren** [comment]
setting terminal.integrated.windowsEnableConpty to false fixed the issue

**Comment by reinux** [comment]
How long is it supposed to take to print 10,000 lines of ints?

This (F#) code takes upwards of 2 seconds to complete in F# Interactive in VSCode and 0.08 seconds in VS2019:

``for i in 1..10000 do printfn "%A" i`

VSCode:
![2019-07-01_12-41-42](https://user-images.githubusercontent.com/5127297/60462258-aa6fde00-9bfd-11e9-9812-2f6afa98954d.gif)

VS2019:
![2019-07-01_12-43-10](https://user-images.githubusercontent.com/5127297/60462318-d3906e80-9bfd-11e9-81db-cc790812f301.gif)

Tried --disable-gpu, turning off windowsEnableConpty, changing renderType, uninstalling VSCode and removing %appdata% and .vscode, a different computer...

**Comment by Tyriar** [comment]
@reinux that looks like https://github.com/microsoft/vscode/issues/74620
