### ISSUE TITLE
Unable to work with files in mac native Terminal while they are opened in Vscode

### ISSUE THREAD

**Issue by josephfelixbamba** [microsoft/vscode#74910]
- VSCode Version: 1.35
- OS Version: MacOS Majove

Steps to Reproduce:

1. Open a folder in VS Code
2. Launch terminal (MacOs native terminal)
3. CD in that same folder you opend in vscode
4. Try runnin the 'tree' command to see file structure in MacOs Terminal

Basically I don't use the integrated terminal in vscode that much. I like my native mac terminal. The problem is whenever I have a folder opened in vscode, the files become unavailable in my native Mac terminal. I am having to close vsCose in order to have my files appear in my native Terminal as the vsCose terminal is sometime limited for some tasks

**Comment by Tyriar** [comment]
I don't have tree installed, does `ls`/`ls -R` show the files?
