### ISSUE TITLE
Missing source maps in vscode stable

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#74919]
Since a couple releases ago vscode stable (not sure about insiders) doesn't ship with source maps anymore in the developer tools.
- vscode 1.31.1
![vscode1 31 1](https://user-images.githubusercontent.com/25115070/58995030-2a01bd00-87b8-11e9-9fcb-3acd706ece5b.png)
- vscode 1.35 
![vscode1 35](https://user-images.githubusercontent.com/25115070/58995042-36861580-87b8-11e9-8b75-a679bc7641c6.png)

**Comment by aeschli** [comment]
fixed in distro
