### ISSUE TITLE
No option to refresh list of available environments

### ISSUE THREAD

**Issue by shermansiu-tgam** [microsoft/vscode#74912]
Issue Type: <b>Bug</b>

After creating or removing an Anaconda environment, the list of available environments doesn't get updated. There is no option to refresh this list either.

I haven't checked if this also applies to virtualenv environments yet.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_684199|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.1
gc-excelviewer|Gra|2.1.32
python|ms-|2019.5.18426
vscode-docker|Pet|0.6.2
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.7.0

</details>

**Comment by egamma** [comment]
Please file the issue against the python extension.
