### ISSUE TITLE
Keybindings for `ctrl`+`tab`, `ctrl`+`shift`+`tab` do not comply with operating system norms

### ISSUE THREAD

**Issue by develleoper** [microsoft/vscode#74916]
Issue Type: <b>Bug</b>

The default keybindings for `ctrl`+`tab` and `ctrl`+`shift`+`tab` do not comply with Windows / OSX operating system norms. Standard tabbed application behavior on those platforms is `workbench.action.previousEditor` / `workbench.action.nextEditor`, which VS Code should respect.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.1
vsc-material-theme|Equ|2.9.0

</details>

**Comment by bpasero** [comment]
Keybindings are configurable.
