### ISSUE TITLE
Release 1.999.0?

### ISSUE THREAD

**Issue by FFY00** [microsoft/vscode#74915]
https://github.com/microsoft/vscode/releases/tag/1.999.0

What is this? One doesn't simply typo the release `1.999.0` and if something like that actually were to happen, a release could just be taken back.

**Comment by octref** [comment]
Seems gone already.

**Comment by FFY00** [comment]
It is still there.

**Comment by octref** [comment]
Should be gone now. Seems last time it came back since someone pushed 1.999 tag again.
