### ISSUE TITLE
Theme error/warning/info icons

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#74921]
Theme error/warning/info icons

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/59019411-4a795800-8848-11e9-9785-27d369fc2043.png)

@misolori @bpasero Any opinions

**Comment by bpasero** [comment]
LGTM. This may ask for trouble because the icon is used in many places where the background is also themable and one color might not fit all.

**Comment by sandy081** [comment]
A new identifier can be used at those places if they have themable background ?

**Comment by bpasero** [comment]
But then we would still have places where the icon looks different, that is odd no?

**Comment by sandy081** [comment]
By default all of them inherit the same color as the places where the severity icons appear has same background. Like 
- Problems
- Editor
- Notifications
- Extensions Viewlet

Only other place which I know of is Status Bar and which we want to use black and white by default and authors can color them in their themes if they want

**Comment by misolori** [comment]
I like this, since we're going to be updating our icons soon, we'll be using a single color for the icon so I'm wondering if we should account for that now (it looks like the icon is using two colors, green and black).

**Comment by misolori** [comment]
Also, I would love to see this dynamic styling for icons applied to all of our icons at some point (part of restructuring our icon system).

**Comment by joeytwiddle** [comment]
Agree, making them **dynamic** was my hope for #74886

When there is a non-zero count, that's when I want the icon(s) to attract my attention (by changing to a bright colour).

<img src="https://user-images.githubusercontent.com/911799/58944115-b362c080-87b3-11e9-85d1-b8934df8adfa.png" width="200">

The rest of the time I am actually fine with them looking like everything else in the statusbar. (But sure if they were themable, I might fade them out a bit.)
