### ISSUE TITLE
PanelService.hideActivePanel is not hiding the complete panel

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#74920]
Instead of using layoutService use panelService.hideActivePanel at the following line 

https://github.com/microsoft/vscode/blob/58459705911b17ffd141ab50a3d3a3ff14c32ad7/src/vs/workbench/contrib/markers/browser/markers.contribution.ts#L267

Now toggle on markers info on status icon. When problems view is shown, clicking on markers info will not hide the complete panel, instead it hides just the content of the problems view.

**Comment by isidorn** [comment]
Good catch. Thanks.
