### ISSUE TITLE
I can‘t debug the vscode.

### ISSUE THREAD

**Issue by Dr-Harris** [microsoft/vscode#74928]
I wanted to debug the vscode source code through vscode, but when I chose `Launch VS Code` and pressed `F5`，I only get part of the workbench. It probably happened yesterday.(2019-06-05).
My os is win10 64bit.
![image](https://user-images.githubusercontent.com/22830171/59004718-3be16f80-884d-11e9-9d4d-3a6ecd2a6f17.png)

**Comment by Dr-Harris** [comment]
But, I can run the source code through the command-line,like `yarn watch + ./script/code.bat`.

**Comment by weinand** [comment]
Please read https://github.com/microsoft/vscode/wiki/How-to-Contribute#debugging
