### ISSUE TITLE
No breadcrumbs for empty, untitled files

### ISSUE THREAD

**Issue by Eldaw** [microsoft/vscode#74924]
After upgrading from v1.34 to v1.35, I now have an empty gap above the first line of text.
![image](https://user-images.githubusercontent.com/3789849/58997796-1aa16480-87f6-11e9-9b68-76ef691e4487.png)

If I right click on that empty gap, then it gets a blue selection border around it:
![image](https://user-images.githubusercontent.com/3789849/58997768-05c4d100-87f6-11e9-98a9-b1ac23c2571f.png)

I'm running VS Code on Windows 10 1903.

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_35#_breadcrumbs-displayed

**Comment by rebornix** [comment]
@jrieken for untitled files, we probably don't want to show the breadcrumb zone.

**Comment by jrieken** [comment]
Yeah, it's tricky. We do show breadcrumbs for untitled files because once they have contents we could show outline information. Tho, for empty, untitled files it doesn't make sense to show them. This is also inconsistent with how we deal with files from document providers

**Comment by jrieken** [comment]
I will push a fix that disables breadcrumbs for untitled files because (1) they have no file system information yet which mean no parent folders nor sibling files/folders can be shown and (2) most language server do not profile symbols for untitled, non-empty, files. This change undoes what we have done in https://github.com/microsoft/vscode/issues/54094

**Comment by garyking** [comment]
@jrieken 	I could've sworn that breadcrumbs previously appeared for untitled Markdown files? Is there any way of enabling them for those again?

**Comment by jrieken** [comment]
Currently not, we wanna bring them back when an untitled file has meaningful symbols. For now all untitled files are treated equal and have no more breadcrumbs (since most have no symbols)
