### ISSUE TITLE
clone to new folder crashes vscode

### ISSUE THREAD

**Issue by ranjanmicrosoft** [microsoft/vscode#74923]
Issue Type: <b>Bug</b>

click a 'clone in vscode' link from azure devops
navigated to C: drive created new folder
rename new folder and select it to use as repository location

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.79GB (36.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.1
tslint|eg2|1.0.43
Angular2|joh|7.1.6

</details>

**Comment by Tyriar** [comment]
Can you be a little more explicit with the repro steps? At which point does VS Code launch? (I'm not familiar with the devops intergration)

**Comment by ranjanmicrosoft** [comment]
the devops integration is just a link of the form vscode://vscode.git/clone?url...
link should trigger vscode to open.

**Comment by joaomoreno** [comment]
> crashes vscode

What do you mean by crashes? Can you show me a screen recording?
