### ISSUE TITLE
Editor freeze on deleted image if extension contributes language filenamePattern

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#74926]
Issue Type: <b>Bug</b>

This relates to https://github.com/microsoft/vscode/issues/69334, which was resolved but recurs in this specific situation.  See also https://github.com/Azure/vscode-kubernetes-tools/issues/558 which is how it came to me.

Steps to reproduce:

1. Create a git repo.  Add an image (e.g. JPEG) to it and commit.  Delete the image and do *not* commit.  If you click on the deleted file diff in the SCM explorer, VS Code will show the deleted image.  This is all as expected so far.

2. Create a new VS Code extension and add the following contribution:

```
        "languages": [
            {
                "id": "hanglywangly",
                "filenamePatterns": [
                    "**/foo/*.hanglywangly"
                ]
            }
        ]
```

(I have provided an extension which reproduces the problem at https://github.com/itowlson/git-deleted-image-hang-o-matic.)

3. Run the extension in the Extension Development Host.

4. In the Extension Development Host, open the git repo from step 1, go to the SCM view and click on the deleted image.

VS Code freezes up as described in https://github.com/microsoft/vscode/issues/69334.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Merging this back into https://github.com/microsoft/vscode/issues/69334
