### ISSUE TITLE
Make sure that Actions are properly disposed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74922]
**Problem**
`Action` is a subclass of disposable because a few of its subclasses register listeners or other handlers that should be disposed of. However while investigating leakage of disposables, I noticed that we are not calling dispose on many actions that are created.

I'm not sure if this is causing any issues currently as only a subset of `Action` subclasses actually need to be disposable. 

**Repo**
1. Enable the `TRACK_DISPOSABLES` flag here: 
https://github.com/microsoft/vscode/blob/2641bd536d53d34962b7a09496c1f421d9dfd0e3/src/vs/base/common/lifecycle.ts#L15
 
    Note that this results in a lot of logging of false positives

1.  Open OSS build and open a single editor
1. Open dev tools and wait a moment for the `__is_disposable_tracked__` messages to stop being printing. Then clear the dev tools console
1. Now split the editor and then close the split editor quickly to return to the original state

**Bug**
Note the warnings in the devtools console about various subclasses of `Action` not being disposed of properly. The printed call stack will start with:

```
at trackDisposable (lifecycle.ts:38)
    at new Disposable (lifecycle.ts:132)
    at new Action (actions.ts:68)
    ...
```

<img width="690" alt="Screen Shot 2019-06-05 at 4 18 54 PM" src="https://user-images.githubusercontent.com/12821956/58996574-a216b580-87ad-11e9-9879-bd34e08bb21b.png">

I've also confirmed this issue by adding some tracking in `Action` itself:

```diff
diff --git a/src/vs/base/common/actions.ts b/src/vs/base/common/actions.ts
index 778a4e9f14..a8278b6215 100644
--- a/src/vs/base/common/actions.ts
+++ b/src/vs/base/common/actions.ts
@@ -48,6 +48,8 @@ export interface IActionChangeEvent {
 	radio?: boolean;
 }
 
+let actionCount = 0;
+
 export class Action extends Disposable implements IAction {
 
 	protected _onDidChange = this._register(new Emitter<IActionChangeEvent>());
@@ -64,6 +66,7 @@ export class Action extends Disposable implements IAction {
 
 	constructor(id: string, label: string = '', cssClass: string = '', enabled: boolean = true, actionCallback?: (event?: any) => Promise<any>) {
 		super();
+		++actionCount ;
 		this._id = id;
 		this._label = label;
 		this._cssClass = cssClass;
@@ -71,6 +74,12 @@ export class Action extends Disposable implements IAction {
 		this._actionCallback = actionCallback;
 	}
 
+	dispose() {
+		--actionCount;
+		console.log(`Actions = ${actionCount }`);
+		super.dispose();
+	}
+
 	get id(): string {
 		return this._id;
 	}
```

**Comment by mjbvz** [comment]
Adding @sbatten because many of the potential leaks are from the menus

**Comment by mjbvz** [comment]
Another option would be to remove `Disposable` as a base class for `Action` given that most actions are not disposable. We should still handle the actions that are really disposable, but I need to double check that these also are never disposed

**Comment by bpasero** [comment]
@mjbvz it would be great if `Action` does not need to be disposed :+1:. At the same time it would be great if `run()` would not force me to return a `Promise<boolean>`. These two things have frustrated me a lot over time.

**Comment by mjbvz** [comment]
Actually it is not the subclasses that required `Action`  to `extend` `Disposable`. The `IAction` interface itself extends `IDisposable` so we really should be disposing of these objects. Additionally, `Action` itself has a private `_onDidChange` emitter that should be disposed of

**Comment by bpasero** [comment]
@mjbvz I do not really understand how this tracking works. To reduce the console spam a little bit, I have commented out [`getEditorActions`](https://github.com/Microsoft/vscode/blob/81d7885dc2e9dc617e1522697a2966bc4025a45d/src/vs/workbench/browser/parts/editor/titleControl.ts#L220). Then I enable the tracking and start with one editor and then I clear the console. Now I hit Cmd+2 to open an empty group (NO editor yet), I already see something printed to the console (why?). Then I close the editor and get entries such as:

```
Error
    at trackDisposable (lifecycle.js:34)
    at new Disposable (lifecycle.js:116)
    at new StatusbarEntryItem (statusbarPart.js:489)
    at InstantiationService._createInstance (instantiationService.js:82)
    at InstantiationService.createInstance (instantiationService.js:53)
    at StatusbarPart.doAddEntry (statusbarPart.js:284)
    at StatusbarPart.addEntry (statusbarPart.js:256)
    at EditorStatus.updateElement (editorStatus.js:404)
    at EditorStatus.updateIndentationElement (editorStatus.js:341)
    at EditorStatus.doRenderNow (editorStatus.js:434)
    at AnimationFrameQueueItem.delayedRender.dom_1.runAtThisOrScheduleAtNextAnimationFrame [as _runner] (editorStatus.js:423)
    at AnimationFrameQueueItem.execute (dom.js:237)
    at animationFrameRunner (dom.js:273)
```

Which seems to indicate to me that possibly editor status entries are leaking? But I do not see that leak when checking the [code](https://github.com/Microsoft/vscode/blob/81d7885dc2e9dc617e1522697a2966bc4025a45d/src/vs/workbench/browser/parts/editor/editorStatus.ts#L436).

**Comment by mjbvz** [comment]
@bpasero The tracking does the following:

* For every `Disposable` that is created
* Add a check that runs after a three seconds that sees if that disposable store has either been registered on another `Disposable` or disposed of. If neither of these is true, then we consider the disposable effectively leaked as we cannot say for sure that `dispose` will be called on it

Any manual management of disposables will not be covered by this, so there are a lot of false positives with this approach

**Comment by bpasero** [comment]
@mjbvz so the instructions are as follows, can you confirm?
* do something that results in disposables to get registered
* do something that should result in these disposables to get disposed faster than 3 seconds from the time the disposable got created
* if something is printed, it means the disposable is either leaking or disposed async

?

**Comment by bpasero** [comment]
@jrieken what is the contract of `fillInActionBarActions` exactly? I see this being printed to the console many times, e.g. when I:
* start with 1 editor
* Cmd+2 to open an empty second group
* close that group

E.g. 

```
lifecycle.js:37 Error
    at trackDisposable (lifecycle.js:34)
    at new Disposable (lifecycle.js:116)
    at new Action (actions.js:18)
    at new ExecuteCommandAction (actions.js:146)
    at new MenuItemAction (actions.js:166)
    at Menu.getActions (menuService.js:83)
    at Object.fillInActionBarActions (menuEntryActionViewItem.js:70)
    at ElectronWindow.doUpdateTouchbarMenu (window.js:285)
```

Should I always dispose the menu before calling into `fillInActionBarActions`? I would assume that method needs to give me some kind of disposable that I can call before calling it again, or even better that method disposes the actions for me?

**Comment by jrieken** [comment]
> @jrieken what is the contract of fillInActionBarActions exactly?

Well, it calls `getActions` (which creates new actions, maybe plan to rename to *create*Actions) and it then sorts them into provided buckets. E.g it help you with primary and secondary action containers

**Comment by bpasero** [comment]
@jrieken renaming this to `createXY` would help understand that there is a lifecycle associated with it. Can this method return a `IDisposable` so that it is easier to dispose whatever this method does within?

**Comment by jrieken** [comment]
Pushed a change that renames the functions to `createAndFillInXYZ`, they also now return a disposable.

**Comment by jrieken** [comment]
An alternative (and maybe better) approach might be to make `IAction` not be an `IDisposable` and make the `Menu#getAction` return `IAction[]` instead of `Action[]`.  The latter is only a disposable because it has an event emitter which signals things like label change etc and that's something the menu/command world doesn't make use of. That would be less code and less complications IMO but I unsure how good our downlevel code like action bars etc work with `IAction` as opposed to `Action`...

**Comment by bpasero** [comment]
Yeah as I mentioned in https://github.com/microsoft/vscode/issues/74922#issuecomment-499380302 I would like action to not be a disposable and not return an artificial `Promise<boolean>` from the `run` method. Replacing `Action` with `IAction` in certain places seems like a good idea to get there, but we are probably in need of the events e.g. for action bar to update enablement, so this may not be as straightforward.

**Comment by jrieken** [comment]
> but we are probably in need of the events e.g. for action bar to update enablement, so this may not be as straightforward.

Actually not, the design is that the menu fires an event and that you need to call `getActions` again. Indeed the whole design of the `MenuItem` and `Commands` world was to get rid of the stateful `Action`-type. The `getActions`-function only exists to match our `Action`-based rendering, like the context menu service which works with actions, not with menus...

**Comment by bpasero** [comment]
@mjbvz there are still other owners of `createAndFill`... that should now be aware that this method returns a `IDisposable`. I can look into mine, but please update the owners of this issue based on that.

The other one that is concerning is callers of [`IMenu.getActions()`](https://github.com/Microsoft/vscode/blob/2b03e7165e88a01ad5706135ea60d7bf3d4d3c5a/src/vs/platform/actions/common/actions.ts#L112). This seems to be the actual core method creating actions that are typically not being disposed:

https://github.com/microsoft/vscode/blob/2b03e7165e88a01ad5706135ea60d7bf3d4d3c5a/src/vs/platform/actions/common/menuService.ts#L109

**Comment by sbatten** [comment]
will look into calls to getActions() from menu and menubar perspective

**Comment by sbatten** [comment]
after investigation, realized that `getActions()` returns `MenuItemAction` and `SubmenuItemAction` which no longer extend `Action` and therefore no longer need to be disposed.
