### ISSUE TITLE
extend skipFiles support to Python

### ISSUE THREAD

**Issue by eldeesmith** [microsoft/vscode#74927]
Like javascript, Python relies heavily on third party modules which come with their own set of quirks and caveats. Debugging a python application is extremely difficult in VSCode when you can't trigger breakpoints on any raised exception due to a third party module raising exceptions, especially in Python where raising exceptions is standard practice for certain design patterns (such is the case with GeneratorExit exceptions).

Please consider extending skipFiles support to the Python debugger, this would make our lives much easier and would allow me to ditch sublime and anaconda once and for all.

**Comment by weinand** [comment]
skipFiles is not a VS Code feature, but a Node.js extension feature. It cannot be "extended" to another language. But the Python extension can easily implement it itself.
