### ISSUE TITLE
In DEBUG CONSOLE, it should be find keyword features (Mac OS X).

### ISSUE THREAD

**Issue by yudizvipulp** [microsoft/vscode#74936]
Issue Type: <b>Feature Request</b>

It would be glad to me and other developers to add "Find" features in "DEBUG CONSOLE".

Right now, it's difficult to find any keywords in "DEBUG CONSOLE" specifically when lots of logs using API response etc...

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

**Comment by yudizvipulp** [comment]
I can't find helpful information from existing one.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/4338
