### ISSUE TITLE
"{git}{hg}" in termal window output

### ISSUE THREAD

**Issue by sethreidnz** [Microsoft/vscode#7493]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:
1. Open vscode
2. Click the menu view -> toggle integrated terminal

Produces this  in the output:

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

c:\dev\SchneiderSummerEvent\frontend-site {git}{hg}
```

An the cursor is a few tabs in on the line under that.

Doesn't really effect the terminal in any other way. Just for context I have seen this before when using [cmder](http://cmder.net/) when I switched to Windows 10. Had something to do with Clink.

**Comment by Tyriar** [comment]
I think I've seen {lambda} before too. @justsayno is Clink what powers cmder?

**Comment by justsayno** [comment]
Yes it is. For all I know its completely unrelated (I don't know anything about how this integrated console works exactly). But it is quite similar to this:

https://github.com/cmderdev/cmder/issues/223

**Comment by Tyriar** [comment]
@justsayno thanks for the link.

I'm going to mark as help wanted if anyone wants to contribute as I won't realistically have time to look at this for a long time.

**Comment by harry008** [comment]
I'm having the same issue with the integrated terminal.

![code_2016-12-02_23-23-06](https://cloud.githubusercontent.com/assets/8999668/20844599/9d11f808-b8e6-11e6-80a7-428b81fe7fbd.png)

But when I use `cmder` in the project directory, its not showing me {git}{hg} in console.

![conemu_2016-12-02_23-24-41](https://cloud.githubusercontent.com/assets/8999668/20844641/d9e97c06-b8e6-11e6-8db4-4467ccea571d.png)

**Comment by Tyriar** [comment]
Closing off, I believe this is related to special character sequences supported in cmder that turn into unicode chars. We have no plans to support these.
