### ISSUE TITLE
zoom out button for alt working the other way

### ISSUE THREAD

**Issue by fyrepenguin** [microsoft/vscode#74932]
Issue Type: <b>Bug</b>

zooming out using right alt key is showing minus icon on magnifier but its zooming in
right ctrl is working fine for zooming out

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Sounds like image zoom.

**Comment by gjsjohnmurray** [comment]
Maybe #73676 so I suggest @fyrepenguin re-tests after updating to 1.35, which just released.

**Comment by mjbvz** [comment]
@fyrepenguin Can you please test this with VS Code 1.35

**Comment by fyrepenguin** [comment]
> @fyrepenguin Can you please test this with VS Code 1.35

I have updated to 1.35.1 and it still works the same nothing's changed
I used right alt key to zoom out.
The zoom icon is set to minus icon but it zooms in every time I click

**Comment by mjbvz** [comment]
Does this match how zoom works in other programs on your machine, such as photoshop?

**Comment by fyrepenguin** [comment]
> Does this match how zoom works in other programs on your machine, such as photoshop?

no every other works fine in XD and photoshop

**Comment by mjbvz** [comment]
Let's get some other users to confirm this because I feel like we've already flipped the scrolling once or twice before...
