### ISSUE TITLE
breadcrumbs.selectEditor command doesn't work when focused on last element

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#74934]
![breadcrum](https://user-images.githubusercontent.com/25115070/59008402-1c682980-87f0-11e9-8331-77905f2a4ac1.gif)

**Comment by jrieken** [comment]
What is your assigned keybinding? Is it `Esc` or all those buttons together? Are you really pressing `Shift`, `Ctrl`, `Alt`, and `Esc` at the same time?

**Comment by jeanp413** [comment]
All keybinding are default. I'm pressing
- `ctrl` + `shift` + `.` to focus on the breadcrumb
- `esc` for `breadcrumbs.selectEditor`

**Comment by jrieken** [comment]
Still unclear if you press just `ESC` or `ESC` with `Shift`, `Ctrl`, `Alt` held?

**Comment by jeanp413** [comment]
Just `Esc` in the gif `Shift`, `Ctrl`, `Alt` are grayed out which means not pressed.

**Comment by jrieken** [comment]
Ok, does ESC work inside the editor? E.g select text and press ESC? What version is this? Does this happen without extensions enabled?

**Comment by jrieken** [comment]
Also, run F1 > Log Level > Trace, then repro this issue and open the Window Log. It should show what it has executed, something like this

```
[2019-06-07 17:56:34.688] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"breadcrumbs.focusAndSelect","from":"keybinding"}
[2019-06-07 17:56:34.688] [renderer1] [trace] telemetry/breadcrumbs/select {"type":"symbol"}
[2019-06-07 17:56:36.277] [renderer1] [trace] CommandService#executeCommand breadcrumbs.selectEditor
[2019-06-07 17:56:36.281] [renderer1] [trace] telemetry/workbenchActionExecuted {"id":"breadcrumbs.selectEditor","from":"keybinding"}
```

**Comment by jeanp413** [comment]
- Yes `esc` works in the editor
- Version 1.35
- Doesn't happen with extensions disabled because then the last element with the symbols list is not available
- Logs aren't really helpful, when I press `esc` doesn't show nothing
```
[2019-06-07 11:12:00.768] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2019-06-07 11:12:01.760] [renderer1] [trace] CommandService#executeCommand breadcrumbs.focusAndSelect
[2019-06-07 11:12:02.694] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2019-06-07 11:12:03.391] [renderer1] [trace] CommandService#executeCommand list.focusDown
[2019-06-07 11:12:03.690] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
[2019-06-07 11:12:03.781] [renderer1] [trace] CommandService#executeCommand list.focusUp
[2019-06-07 11:12:04.421] [renderer1] [trace] CommandService#executeCommand list.focusDown
[2019-06-07 11:12:05.197] [renderer1] [trace] CommandService#executeCommand _executeCodeLensProvider
```

**Comment by jrieken** [comment]
> Doesn't happen with extensions disabled because then the last element with the symbols list is not available

Well, you should always see the file path with its last element. When it comes to ESC there is no difference if its a file or symbol. So, please try that again

**Comment by jeanp413** [comment]
>Doesn't happen with extensions disabled because then the last element with the symbols list is not available

⬆️ This only happens when I tested it with a C++ project.

With a typescript project (vscode project) it happens even with extensions disabled because I still get the symbols list.

![breadcrum_2](https://user-images.githubusercontent.com/25115070/59395525-10c5b700-8d4a-11e9-9d32-2361799469c7.gif)

**Comment by jrieken** [comment]
Well, idk - it seems like Esc isn't being dispatched at all. Does it work with other things? Eg. select some text in the editor, hit Esc, and the selection should collapse back into a cursor

**Comment by jeanp413** [comment]
Yes, `Esc` works as expected in any other case. In the gif you can see I use it to close the notifications and also when invoking `breadcrumbs.selectEditor` on the `browser` and `repl.ts` breadcrumbs but does not work when `SelectReplAction` and `run` breadcrumbs are focused (symbols list displayed).

**Comment by jeanp413** [comment]
@jrieken  I did some debugging and found the root cause. It's because the `BreadcrumbsOutlinePicker` tree is using `OutlineNavigationLabelProvider` which has a method `mightProducePrintableCharacter` that calls [this](https://github.com/microsoft/vscode/blob/402aa47b262601bf7569a5558d42b398e418361e/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L429-L448) which is saying the `esc` key is a printable character causing `abstractTree` to catch that keydown event and calling `stopPropagation()`.

**Comment by jrieken** [comment]
Wow - that's a solid investigation. Thanks. The context is that when pressing a key we need to know if you wanna filter/find in the tree or not. That's why we call the infamous `mightProducePrintableCharacter` function. If we believe that you are typing "visible" characters the tree consumes the event and start filtering - in your case using `Esc`. Now the question is why is that? We do have a native module that computes what physical key (and key combination) produces what character. Can you check this troubleshooting guide which is about keybinding issues: https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings. Can you also debug till here https://github.com/microsoft/vscode/blob/402aa47b262601bf7569a5558d42b398e418361e/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L444 and share the `keyInfo`, esp its value?

**Comment by jeanp413** [comment]
I followed the guide and tried using `"keyboard.dispatch": "keyCode"` but didn't help.
`keyInfo.value` =>
![Screenshot from 2019-06-13 20-29-03](https://user-images.githubusercontent.com/25115070/59477932-1809c500-8e1d-11e9-851b-1aa36bd0b42e.png)

Also the `keyboardNavigationLabelProvider` provided to the `BreadcrumbsFilePicker` tree doesn't have a `mightProducePrintableCharacter` method  and uses [this one from listWidget](https://github.com/microsoft/vscode/blob/09158c5b7aefa2de9e66f4905d67c6c4a54fbe6c/src/vs/base/browser/ui/list/listWidget.ts#L326-L334) instead [here](https://github.com/microsoft/vscode/blob/09158c5b7aefa2de9e66f4905d67c6c4a54fbe6c/src/vs/base/browser/ui/tree/abstractTree.ts#L506).

**Comment by jeanp413** [comment]
@jrieken Summarizing what I found until now:
1.  `OutlineNavigationLabelProvider` doesn't need to have `mightProducePrintableCharacter` defined because it will be overwritten here either way https://github.com/microsoft/vscode/blob/3718e799834243b2124e51a1505bc13d796d3eb8/src/vs/platform/list/browser/listService.ts#L215-L222
2. `BreadcrumbsFilePicker` works as expected because the underlying tree which is `AsyncDataTree` ignores the `mightProducePrintableCharacter` method 
https://github.com/microsoft/vscode/blob/6a7020dd4a11e0f33b157b3df4baeec90d85701b/src/vs/base/browser/ui/tree/asyncDataTree.ts#L227-L231 and uses this one instead https://github.com/microsoft/vscode/blob/6a7020dd4a11e0f33b157b3df4baeec90d85701b/src/vs/base/browser/ui/list/listWidget.ts#L326-L334

**Comment by jrieken** [comment]
Yeah, the irony is that the simple implementations, as in `listWidget`, are actually more error prone because they miss things like `ü`, `ß`, `ø` etc. That's why we use information "from the keyboard/os" instead of just assumptions. 

So, the real question is still why doesn't `Esc` produce a printable character on your machine and how can we workaround this. We could simply hardcode `Esc` to be ignored - I think that's a fair assumption and I don't know anyone that rebinds `Esc` to lets say "f"

**Comment by jrieken** [comment]
I have pushed a workaround, this is something @rebornix or @alexandrudima need to look into tho. Not sure if this is an issue with our key mapping or your setup...
