### ISSUE TITLE
Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin

### ISSUE THREAD

**Issue by kenshohara** [microsoft/vscode#74933]
- VSCode Version: 1.35.0
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. Opening vscode from finder.
2. Executing "build with recipe" of the LaTeX Workshop extension.
3. [13:50:18] LaTeX build process spawned. PID: undefined.
    [13:50:18] LaTeX fatal error: spawn latexmk ENOENT, . PID: undefined.
    [13:50:18] Does the executable exist? PATH: /usr/bin:/bin:/usr/sbin:/sbin
4. Then, opening vscode from terminal using ```code```.
5. "build with recipe" works correctly.

My login shell is fish. In my fish shell, $PATH includes ```/Library/TeX/texbin```. However, $PATH ? of vscode opened from finder does not include the path. That of vscode opened from terminal includes it.

How can I fix this? Is this a specific problem to the LaTeX Workshop extension?

**Comment by Tyriar** [comment]
Can you share your settings.json file and also `echo $SHELL` in a system terminal? Did you change your default shell to fish or did you run it in your `~/.bashrc` or something?

**Comment by kenshohara** [comment]
Yes, I changed my default shell to fish.
```
❯ echo $SHELL
/usr/local/bin/fish
```

This is my settings.json.
```
{
    "editor.fontSize": 16,
    "editor.fontFamily": "Source Han Mono",
    "editor.renderWhitespace": "boundary",
    "editor.cursorStyle": "line-thin",
    "editor.wordWrap": "on",
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style=google"
    ],
    "latex-workshop.intellisense.citation.label": "title",
    "latex-workshop.latex.recipes": [
        {
            "name": "pdflatex",
            "tools": [
                "latexmk_pdflatex"
            ]
        },
        {
            "name": "uplatex",
            "tools": [
                "latexmk_uplatex"
            ]
        },
        {
            "name": "platex",
            "tools": [
                "latexmk_platex"
            ]
        },
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk_pdflatex",
            "command": "latexmk",
            "args": [
                "-pdf",
                "%DOC%"
            ]
        },
        {
            "name": "latexmk_uplatex",
            "command": "latexmk",
            "args": [
                "-pdfdvi",
                "%DOC%"
            ]
        },
        {
            "name": "latexmk_platex",
            "command": "latexmk",
            "args": [
                "-pdfdvi",
                "-latex='platex'",
                "-latexoption='-kanji=utf8 -no-guess-input-env'",
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-halt-on-error",
                "%DOC%"
            ]
        },
    ],
    "workbench.startupEditor": "newUntitledFile",
    "latex-workshop.latex.recipe.default": "lastUsed",
    "latex-workshop.view.pdf.viewer": "tab",
    "workbench.colorTheme": "Nord",
}
```

**Comment by Tyriar** [comment]
Seems related to get shell env

**Comment by Tyriar** [comment]
@kenshohara where did you add `/Library/TeX/texbin`? The terminal on macOS runs a login shell which should execute your profile.

**Comment by joaomoreno** [comment]
When you open Code, can you run `Developer: Toggle Developer Tools`. Is there any error in the console?
