### ISSUE TITLE
Collapse summary / JSDoc comment for JS prototype

### ISSUE THREAD

**Issue by HeheCnC** [microsoft/vscode#74935]
**New Feature / BUG?**

![image](https://user-images.githubusercontent.com/51432894/59008597-41c65900-882b-11e9-8050-97558974ffd3.png)

On the picture I tried to describe the issue, with old type of JS class definition it's not possible to collapse JSDoc summary for functions/parameters of prototype definitions.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/31786 to track this upstream
