### ISSUE TITLE
Broken colours when using fish shell in the integrated terminal

### ISSUE THREAD

**Issue by knadh** [microsoft/vscode#74940]
- VSCode Version: 1.3.50 (commit #6d357d)
- OS Version: Ubuntu 19.04
- fish Version: 3.0.2

Steps to Reproduce:

1. Set `terminal.integrated.shell.linux: /usr/bin/fish`
2. Invoke the integrated terminal and run the `reset` command. The colours fade out. All subsequent commands break the colour rendering in random ways.

**Screenshots**
1. On launch of the integrated terminal
![image](https://user-images.githubusercontent.com/547147/59013352-5b7d9580-8857-11e9-9bc2-feeb874b2b83.png)

2. After running `reset`
![image](https://user-images.githubusercontent.com/547147/59013393-7c45eb00-8857-11e9-8834-0062629dc314.png)

3. Subsequent commands
![image](https://user-images.githubusercontent.com/547147/59013573-e199dc00-8857-11e9-9886-cc751e5c3976.png)

![image](https://user-images.githubusercontent.com/547147/59013627-0aba6c80-8858-11e9-910f-a80e1f1a4c6a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by adelphes** [comment]
I think terminal coloring is completely broken in the latest version.

![image](https://user-images.githubusercontent.com/13035517/59033691-2d04b800-8861-11e9-87be-a9490e9006f5.png)

Typing the `reset` command does not help either.
