### ISSUE TITLE
Bring VSCODE to foreground and get focus automatically

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#74945]
- VSCode Version: 1.34.0
- OS Version: win10

Steps to Reproduce:
I am implementing a LISP debugging extension. It needs to do some inter-operate between VSCODE and the debugging app:
1. set breakpoints in vscode
2. hit F5 and the app prompts user to select a file
3. after select the file, it will trigger the breakpoint added by step1

Result: it needs an API to bring the VSCODE to foreground, but I didn't find an API in vscode doc.
(it needs a API like this window API https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setforegroundwindow)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
maybe something for debug but it's unlikely that we give general purpose API for such a sharp knife

**Comment by weinand** [comment]
VS Code brings itself to front automatically when a breakpoint bis hit.
See this:

![2019-06-06_11-13-00 (1)](https://user-images.githubusercontent.com/1898161/59021512-3cc5d180-884c-11e9-98ca-e1b1dd03136c.gif)

Is this not working for you?

**Comment by whlkw** [comment]
Thanks for your information!

It looks like sometime the VSCODE only become to yellow in windows task bar and flash it. It doesn't bring to foreground.

**Comment by whlkw** [comment]
Thanks for your suggestions!
