### ISSUE TITLE
"Start extension host profile" doesn't work if extension host is paused

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#74946]
If you try to start profiling from the Running Extensions list when you're stopped a breakpoint, it doesn't work, writing `ERR: runtime is paused` to the dev tools console.

This makes it difficult to capture a profile during a test run, since you really want to stop at a breakpoint, start a profile, then have it stop at another breakpoint for you to stop/save the profile before Code terminates.

If this isn't fixable, is it possible to expose some way to either start/stop/save profiles in extension/test code, or something to pass through in the tests launch config to do this?

(@jrieken maybe there's already a way I can do this? I'm happy to call internal commands that may break, this isn't for code that'll ship to users :-))

**Comment by jrieken** [comment]
Yes - that the design/limitation of the runtime.

**Comment by DanTup** [comment]
@jrieken then is it possible to expose commands to allow us to start/stop/save these (it's fine if they're "private" and have no guarantees about breaks). The easier it is for us to profile our extensions, the faster they're likely to be :-)

**Comment by jrieken** [comment]
did you try https://developer.mozilla.org/en-US/docs/Web/API/Console/profile?

**Comment by DanTup** [comment]
It throws "console.profile is not a function" (though also, it doesn't seem to support saving, so it'd have similar drawbacks to doing it manually, having to ensure the test run doesn't complete and close VS Code while you save the results).
