### ISSUE TITLE
Reveal in Explorer does not bring the File Explorer window to the foreground

### ISSUE THREAD

**Issue by ChrisGuzak** [Microsoft/vscode#7494]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Right click on a file in the files list, choose "Reveal in Explorer"

observe that the explorer window opened does not come to the foreground.

Usually this type of problem us due to not passing the foreground privilege on correct. If COM is used to transport the call from one thread to another use CoAllowSetForegroundWindow() on the COM object that will invoke the API that opens File Explorer.
Also verify you are using SHOpenFolderAndSelectItems API to open the window and select the file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/929
