### ISSUE TITLE
Use Map over Object {}

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74948]
Scanning for patterns such as `const mapEntryToPath: { [path: string]: QuickOpenEntry; } = {};` that can be written using `Map` instead.

* `compositePart` @isidorn 
* `quickOpenController` @bpasero 
* `themeCompatibility` @aeschli 

There may be more, these are the ones I found searching for `map.*= \{\}`

**Comment by isidorn** [comment]
@bpasero thanks, I have changed the `compositePart`. I found some other places where I still use Object {}. Will update them as well.

**Comment by isidorn** [comment]
I have polished some usages of map in debug land.
Changed an Object to a Map in the loadedScriptView.ts fyi @weinand

**Comment by mjbvz** [comment]
One tip when making these changes: Set `suppressImplicitAnyIndexErrors: false` in `tsconfig.base.json`. This will help catch errors where you accidentally are still using`['key']` on a map object instead of calling `get`

**Comment by bpasero** [comment]
A much better query I found for finding these: `\{ \[.+string\]:`

Looks like we have tons of usages:

![image](https://user-images.githubusercontent.com/900690/59082326-d3e56480-88f2-11e9-8023-21a729a7d67c.png)

**Comment by aeschli** [comment]
I prefer {} over Map...

**Comment by bpasero** [comment]
@aeschli fair. though, as long as we do not have `suppressImplicitAnyIndexErrors` enabled you do not get any null-checking from TypeScript. In other words, code that is using `Object` instead of `Map` is not checked for null errors. Converting towards `Map` brings us closer to eventually having `strict: true`.
