### ISSUE TITLE
No preferences top level menu when building out of source

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74949]
OS X, latest source

1. Run vscde out of source `scripts/code.sh`
2. There is no Preferences menu under the Code - OSS top level menu

fyi @bpasero

![Screenshot 2019-06-06 at 10 35 05](https://user-images.githubusercontent.com/1926584/59018698-c5417380-8846-11e9-924c-8ab3baffa7d5.png)

**Comment by bpasero** [comment]
Seems to be there in the Exploration build at least, so maybe not an Electron update issue, but could be.

**Comment by isidorn** [comment]
Also in latest insiders

**Comment by isidorn** [comment]
Adding label bug and verified.
