### ISSUE TITLE
Error icon is not consistent

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#74950]
We show error icon at couple of places 
- Problems view
- Editor
- Notifications
- Extensions view

Notifications has different icon than others.

![image](https://user-images.githubusercontent.com/10746682/59019028-83fd9380-8847-11e9-953b-614f1ed59df2.png)

![image](https://user-images.githubusercontent.com/10746682/59019044-8b24a180-8847-11e9-836a-863e4ac06314.png)

If we use the same icon as others then it will be as follows

![image](https://user-images.githubusercontent.com/10746682/59019223-efdffc00-8847-11e9-9196-23a0eb4538f8.png)

**Comment by sandy081** [comment]
@misolori FYI

**Comment by bpasero** [comment]
I personally don't mind that the icon appears larger in notifications, it is still the same icon after all.

**Comment by misolori** [comment]
Having the same icon consistent is fine, but I do also like that it's slightly larger in notifications since they need to stand out a bit more.

**Comment by sandy081** [comment]
@misolori Will this be redundant if we use new icons?

**Comment by misolori** [comment]
@sandy081 I would just use existing icons for now, I'll update all of our icons to the new ones.

**Comment by sandy081** [comment]
Ok, since we will use new ones which makes it consistent across. Closing this.
