### ISSUE TITLE
node_modules内所有JS文件报错

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [microsoft/vscode#74954]
VSCode版本： 1.35.0 (1.35.0)
OS版本：10.14.5

问题:
打开node_modules文件夹里面的所有JS全都报错
![image](https://user-images.githubusercontent.com/41282358/59022089-b62ae780-887f-11e9-83d2-3ca282d3562b.png)

禁用所有扩展时是否会出现此问题？：是

**Comment by xiaoyouyu** [comment]
![image](https://user-images.githubusercontent.com/23133668/59022689-d313ea80-8880-11e9-9994-43e7fa91049e.png)
@GaoXiaoBoGitHub

**Comment by GaoXiaoBoGitHub** [comment]
![image](https://user-images.githubusercontent.com/41282358/59023257-f9865580-8881-11e9-838e-3ecf873f9f12.png)

**Comment by egamma** [comment]
/needsMoreInfo please report the issue in English
