### ISSUE TITLE
Terminal consumes a lot of CPU when editing in vim

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#74955]
- VSCode Version: 1.35.0
- OS Version: kubuntu 19.04

Steps to Reproduce:

1. open vscode full screen, terminal should be big enough
2. open file with name `env.conf` and content below in vim
3. terminal will feel slow, code process consumes 100% cpu of 1 core.

screencast
![Peek 2019-06-06 12-42](https://user-images.githubusercontent.com/7345761/59023649-e612c480-8858-11e9-93ff-0b96e0819a4a.gif)

content:
```
#JAVA_HOME=/usr/java/jdk1.6
HADOOP_OPTS=-Djava.net.preferIPv4Stack=true

#LD_LIBRARY_PATH=/usr/local/gcc-4.7.3/lib64
LD_LIBRARY_PATH=/usr/local/lib64

CXX=/usr/local/bin/g++
CC=/usr/local/bin/gcc

#PATH=/usr/local/lib/ccache/:/usr/local/gcc-4.7.3/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CCACHE_COMPRESS=true
CCACHE_SLOPPINESS=no_system_headers
# CCACHE_DISABLE=true
```

Noticed since 1.34 I guess

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Can you open devtools and run a perf timeline while editing vim, save it and upload it? That should show what functions it's busy in.

**Comment by Yanpas** [comment]
Done 
[Profile-20190611T150659.json.txt.gz](https://github.com/microsoft/vscode/files/3276379/Profile-20190611T150659.json.txt.gz)

**Comment by Tyriar** [comment]
Are you using a network drive or something? I see a lot of blocking readdir calls taking very long:

<img width="914" alt="Screen Shot 2019-07-05 at 11 58 27 AM" src="https://user-images.githubusercontent.com/2193314/60740897-3fcfe280-9f1c-11e9-8f4f-896b167c2f9c.png">

**Comment by Yanpas** [comment]
No, I'm using local drive definitely. No matter If I edit this file in /home partition or in /usr/etc - it still feels slow

**Comment by stouf** [comment]
Same issue happening here. The bigger the terminal gets, the slower vim becomes. Please find information about my environment below; I hope it helps:

- Operation System: Mac OS 10.14.6
- VSCode:
  - Version: 1.37.1
  - Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
  - Date: 2019-08-15T16:16:34.800Z
  - Electron: 4.2.7
  - Chrome: 69.0.3497.128
  - Node.js: 10.11.0
  - V8: 6.9.427.31-electron.0
  - OS: Darwin x64 18.7.0

**Comment by yuqian90** [comment]
This issue and the duplicate issue that was closed have something in common: https://github.com/microsoft/vscode/issues/79547

The integrated terminals in both these issues have a lot of text that look like paths. So I believe offering an option to turn off the `terminal.links` feature in integrated terminal can be a temporary stop gap measure to let people continue to use the integrated terminal while waiting for a better fix.

**Comment by Tyriar** [comment]
Done, try out `terminal.integrated.enableFileLinks` in [Insiders](https://code.visualstudio.com/insiders). I'll keep this open for a more robust solution in the future (detecting slowness, auto disabling for network drives, etc.), maybe with reverting to linkifying all potential paths without validation.

**Comment by yuqian90** [comment]
Is this feature available in the insders version? i tried it today but the editor said `terminal.integrated.enableFileLinks` is an "Unknown Configuration Setting". The version I tried is September 2019 (version 1.39) on OSX.

Am I missing something?

**Comment by Tyriar** [comment]
@yuqian90 it should be in today's build yes, looks like you tried before our daily build went out.

**Comment by yuqian90** [comment]
Thanks @Tyriar  started trying the insider version with`"terminal.integrated.enableFileLinks": false`. Works like a charm so far.

**Comment by Tyriar** [comment]
@yuqian90 great!

**Comment by yuqian90** [comment]
@Tyriar I have been using the insider version for a few days. So far I have not seen the previous problem where Code Helper use a lot of CPU and dtruss shows lots of stat64 operations. However, I still saw at least twice vscode froze (I could not save modified files or open new files, but the editor looks normal otherwise).

Maybe the `terminal.integrated.enableFileLinks` is not the only issue. I'll try to come up with perf timeline when I have time.

**Comment by Tyriar** [comment]
@yuqian90 that sounds like it would be another issue, maybe one of the existing electron-related ones? I haven't seen any freezing like that on my mac.

**Comment by Tyriar** [comment]
Let's call this fixed with the new setting now.

**Comment by stouf** [comment]
I gave a try to the new option this morning, but it doesn't seem to change anything on my system; vim is still very slow and one of the Code Helper process uses near 100% of my CPU 😕

Mac OS 10.15
Version: 1.39.0
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:57:43.593Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Comment by Tyriar** [comment]
@stouf looks like you're seeing the slowness with drawing background colors for all cells, https://github.com/xtermjs/xterm.js/issues/2033 should hopefully fix that one eventually.

**Comment by stouf** [comment]
@Tyriar Great! Thank you for the reference, I'll follow 🙂
