### ISSUE TITLE
Duplicate and move selected code by side

### ISSUE THREAD

**Issue by GregorBiswanger** [microsoft/vscode#74959]
I love to use "duplicate line", but I miss often a "dublicate code by side" feature.
The same with move the selected word by side.

**Comment by egamma** [comment]
@GregorBiswanger 

>I miss often a "dublicate code by side" feature.

Can you illustrate this is in more details pls.

**Comment by GregorBiswanger** [comment]
I do not have the best example right now, but the following scenario describes what I would like:

I have an array with a value that I select and want to duplicate, right or left. Or mark a value and move it right or left.

select 'Item'

`['Item', ];`

duplicate to right:

`['Item', 'Item'];`

Or for TypeScript scenaries. I write a variable name that is the same as the type name. Then I would like to duplicate to the right.

`customer: customer`

If the type is capitalized at the beginning, all I have to do is replace the first character.

**Comment by GregorBiswanger** [comment]
Today I had such a case again where I needed the lateral move:

**Before:**
I insert a span element with emmet and want my item declaration as content of span.

`<span></span> {{ item }}`

**Later:**
I mark the item and want to move it sideways to the left.

`<span>{{ item }}</span>`

Sure, I could cut it out. However, then the clipboard is dirty.

**Comment by egamma** [comment]
I suggest to prototype this feature in extension. It should be straightforward to implement this using the extension API. Based on the feedback on the extension we can then decide whether this should be promoted to a built-in feature.

**Comment by GregorBiswanger** [comment]
Thank you Erich! :)
