### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by NitsanBaleli** [microsoft/vscode#74956]
- VSCode Version: Version: 1.36.0-insider
Commit: bd39f3d7a1fb9de4c16608db454c6025ab85149d
Date: 2019-06-06T05:16:20.809Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-46-generic
- OS Version: ubuntu 18

Steps to Reproduce:

1. try to do a global find

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/3227826/59023936-7d781780-8859-11e9-9d54-4ab16a11f9f3.png)

**Comment by bpasero** [comment]
Think this is fixed in latest.

**Comment by NitsanBaleli** [comment]
no vscode entry when I `apt-get update`

**Comment by bpasero** [comment]
Might take a bit of time until it travels.

**Comment by NitsanBaleli** [comment]
fixed thank you
