### ISSUE TITLE
Issue When Committing Changes

### ISSUE THREAD

**Issue by cajunitalian** [Microsoft/vscode#7495]
- VSCode Version:  1.2.0
- OS Version:  Windows 10

Can't reproduce because this is permanent and won't go away after I upgraded to 1.2.0.

I am working with some powershell code but the modified items keep appearing even though I haven't touched them:

![image](https://cloud.githubusercontent.com/assets/1809840/15945425/132bd208-2e58-11e6-85b1-205dc90d9163.png)

These are folders ^ I can get them to clean, commit, push etc.

**Comment by joaomoreno** [comment]
If you go to the command line, what do you get when running `git status`?

**Comment by cajunitalian** [comment]
I get this:

![image](https://cloud.githubusercontent.com/assets/1809840/15973247/f8dbd866-2f07-11e6-98f4-f8b27e35c608.png)

**Comment by joaomoreno** [comment]
For some reason, each of those folders seem to be git repository in themselves (they contain a `.git`). At the same time, the folder in which they are contained is also a git repository (containing a `.git`).

This is very strange and an invalid git scenario, unless you are attempting to create git submodules.

I suggest to either remove the top level `.git` folder in the containing folder, and open each one of those folders in Code; or vice-versa: remove each of the subfolders' `.git` folders and keep opening the containing folder.
