### ISSUE TITLE
Syntax highlighting error with single quotes

### ISSUE THREAD

**Issue by ChTosar** [microsoft/vscode#74961]
Issue Type: <b>Bug</b>

```php
$db->query("UPDATE x WHERE id='".$x."' AND x LIKE '".someF('{"This Double quotes produce an error"}')."' LIMIT 1");
```

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.1
vscode-todo-plus|fab|4.13.0
php-debug|fel|1.13.0

</details>

**Comment by egamma** [comment]
In what kind of source file do you see this behaviour?
Please add a snippet so that we can reproduce the issue without having to type in the test case.
