### ISSUE TITLE
run code have take error with c++/cpp

### ISSUE THREAD

**Issue by xia1065** [microsoft/vscode#74963]
what c++ runner code  happen  a error?

PS C:\Users\xxx> cd "f:\cpp\" && g++ 1007.cpp -o 1007 && "f:\cpp\"1007
所在位置 行:1 字符: 14
+ cd "f:\cpp\" && g++ 1007.cpp -o 1007 && "f:\cpp\"1007
+              ~~
标记“&&”不是此版本中的有效语句分隔符。
所在位置 行:1 字符: 38
+ cd "f:\cpp\" && g++ 1007.cpp -o 1007 && "f:\cpp\"1007
+                                      ~~
标记“&&”不是此版本中的有效语句分隔符。
所在位置 行:1 字符: 41
+ cd "f:\cpp\" && g++ 1007.cpp -o 1007 && "f:\cpp\"1007
+                                         ~~~~~~~~~
只允许将表达式作为管道的第一个元素。
所在位置 行:1 字符: 50
+ cd "f:\cpp\" && g++ 1007.cpp -o 1007 && "f:\cpp\"1007
+                                                  ~~~~
表达式或语句中包含意外的标记“1007”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

**Comment by egamma** [comment]
Please report the issue against the C++ extension and I suggest to add more detailed steps.
