### ISSUE TITLE
Weird behaviour of cygwin compiler shell

### ISSUE THREAD

**Issue by ScruffR** [microsoft/vscode#74965]
I have found a "duplicate" but since that's closed and locked for further comments but appears still unresolved I'm "forced" to open a new issue

Original
https://github.com/microsoft/vscode/issues/68817

- VSCode Version:1.35.0
- OS Version: Windows 10Pro 64bit on Surface Pro 2017 with 1903 update and most recent available insider builds (latest builds are not supported by MS' own hardware????)

![image](https://user-images.githubusercontent.com/6604878/59032193-eb2a4080-8865-11e9-99f0-839309603303.png)

After installing latest insider preview for my device
![image](https://user-images.githubusercontent.com/6604878/59061271-5f370980-88a3-11e9-99dc-6df1ab3552cd.png)

In cygwin compiler shell [BACKSPACE] does *not* move back and delete character left of carret and when entering longish commands it starts spontaneously adding parts of the already typed command.

Tried both `"terminal.integrated.windowsEnableConpty": true` and `"terminal.integrated.windowsEnableConpty": false` - same behaviour.

**Comment by busticated** [comment]
@Tyriar - apologies for the ping :pray: is this still the right place to raise this issue? anything we can do over here to mitigate this behavior short-term?

**Comment by Tyriar** [comment]
I can't seem to repro, it's just typing and pressing backspace? Are you on the latest cygwin?

![cygwin](https://user-images.githubusercontent.com/2193314/60835254-7ce3e100-a177-11e9-987f-f0a7eff8fa1b.gif)

**Comment by busticated** [comment]
@Tyriar thanks for taking a look :pray:

weird. perhaps we're not configuring things properly? what exact shell configs are you using?

btw, if it helps you can repro like this:

1. install Particle Workbench ([link](https://marketplace.visualstudio.com/items?itemName=particle.particle-vscode-pack))
2. install dependencies when prompted
3. run the `Particle: Launch Compiler Shell` command and type away in the terminal instance that launches

**Comment by Tyriar** [comment]
@busticated here's the shell I was using:

```
"terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe"
```

**Comment by busticated** [comment]
hm. ok. we're using the `window.createTerminal()` api directly passing in the following `TerminalOptions`:

```
{
    "name": "Particle Local Compiler (stroby)",
    "shellPath": "C:\\Users\\me\\.particle\\toolchains\\buildtools\\1.0.3\\bin\\bash.exe",
    "shellArgs": [
        "--noprofile",
        "--norc"
    ],
    "shellQuoting": {
        "escape": {
            "escapeChar": "\\",
            "charsToEscape": " \"'"
        },
        "strong": "'",
        "weak": "\""
    },
    "env": {
        "Path": "C:\\Users\\me\\.vscode\\extensions\\particle.particle-vscode-core-1.4.8\\src\\cli\\bin\\windows\\amd64;C:\\Users\\me\\.particle\\toolchains\\gcc-arm\\5.3.1\\bin;C:\\Users\\me\\.particle\\toolchains\\buildtools\\1.0.3\\bin;C:\\Users\\me\\.particle\\toolchains\\openocd\\0.10.0-particle.1\\bin;C:\\Program Files (x86)\\Google\\Chrome\\Application;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;",
        "PLATFORM": "photon",
        "PLATFORM_ID": "6",
        "PARTICLE_CLI_PATH": "C:/Users/me/.vscode/extensions/particle.particle-vscode-core-1.4.8/src/cli/bin/windows/amd64/particle.exe",
        "DEVICE_OS_PATH": "C:/Users/me/.particle/toolchains/deviceOS/1.1.1/firmware-1.1.1",
        "GCC_ARM_PATH": "C:/Users/me/.particle/toolchains/gcc-arm/5.3.1/bin/",
        "APPDIR": "c:/Users/me/projects/stroby",
        "PARTICLE_MAKEFILE": "C:/Users/me/.particle/toolchains/buildscripts/1.5.1/Makefile"
    }
}
```

but those seem to align with what you are doing.

over in powershell, running `PS C:\Users\me> C:\Users\me\.particle\toolchains\buildtools\1.0.3\bin\bash.exe --version` returns:

```
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  
```

which on the face of it seems correct 🤷‍♂

**Comment by Tyriar** [comment]
@busticated it's probably an issue with your bash.exe then, backspace should be sending the right stuff to bash, it's just responding incorrectly. Also FYI `shellQuoting` doesn't do anything there.

**Comment by busticated** [comment]
@Tyriar ok i'll dig in. thanks again :pray:

**Comment by Tyriar** [comment]
Closing as this isn't actionable for us
