### ISSUE TITLE
React/JSX Support for Color Highlight & Color Picker

### ISSUE THREAD

**Issue by Riseley** [microsoft/vscode#74964]
Hi, the color highlighter (and its left box) doesn't show up in .js, particularly JSX files, same goes to the color picker.

A possible quick solution:
1. Currently, the color highlight part can be easily fixed by installing the amazing "Color Highlight" extension.

2. The "Color Picker" extension is sometimes unreliable (3/5 stars) and depends on Node, which is not ideal because not all users know or want to install Node. And other similar extensions have critical flaws. **So the quickest solution is to have a shortcut that allow us to bring up the built in color picker.**

**Comment by SupinePandora43** [comment]
color picker extension uses electron?! ....... electron app (vscode) needs start new electron app (color picker) .... for picking color?! why extension can't just show picker in vscode?!

**Comment by Riseley** [comment]
I am very sorry that you misunderstood my problem. Especially that I think the bot misunderstood the issue because it is unrelated to extensions. Please reopen this issue.

This issue is about:
1. Color highlight support for JSX because it currently does not work in React environment. It is a bug.
2. Allow shortcut to bring up the internal color picker.

**Comment by egamma** [comment]
@Riseley please illustrate your issue with screenshots.

**Comment by SupinePandora43** [comment]
this issue is feature request for allowing using vscode's color picker (allowed in css) in js/jsx ?!

**Comment by Riseley** [comment]
@egamma 
Here's a screenshot of the color highlighter not working:
https://imgur.com/m1Ty0rq

**Comment by Riseley** [comment]
@SupinePandora43 this is a bug report.
See https://imgur.com/m1Ty0rq

**Comment by SupinePandora43** [comment]
@Riseley i think vscode show default color highlighter only in styles files, e.g. css,scss

**Comment by Riseley** [comment]
Oh well.
