### ISSUE TITLE
Refresh icon in the explorer a bit too large

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74968]
Notice how the refresh icon is a bit too large in the explorer. IMHO it should be 10% smaller. Due to its size it does not look aligned and feels alien.
Same for refresh in search

fyi @roblourens @bpasero

![Screenshot 2019-06-06 at 15 05 14](https://user-images.githubusercontent.com/1926584/59034955-8c1bfa00-886c-11e9-8e4d-a08d3f06e961.png)

**Comment by misolori** [comment]
Here's what that would look like if it was smaller:

![image](https://user-images.githubusercontent.com/35271042/59048750-5f9bba00-883b-11e9-94cd-68474deac24a.png)

**Comment by isidorn** [comment]
This looks great.

**Comment by bpasero** [comment]
@misolori may I ask how this slipped? I would think that every icon is somewhat the same size? I do not think the set should contain any icon that appears larger. We should try to make them consistent, maybe by putting them all next to each other and seeing how they align on a horizontal line to the top and to the bottom?

**Comment by misolori** [comment]
@bpasero it's not that this slipped, it's that icons that are circular appear to take up more space and can "appear" larger. All of the icons are designed at 14x14 and then centered on a 16x16 square (that's how they were before) but some icons, depending on their nature, have to be adjusted to be a bit smaller to avoid pixelation or to not appear as large. Here's what it was before I decreased it (the red is the margin around the icons):

![image](https://user-images.githubusercontent.com/35271042/59064066-4e17d980-885e-11e9-9b1f-1fcdebdbfbb6.png)


**Comparison (Left is before, Right is after)**
![image](https://user-images.githubusercontent.com/35271042/59064118-6b4ca800-885e-11e9-8726-e94788a88aa4.png)

**Comment by bpasero** [comment]
Thanks for the detailed explanation 👍

**Comment by isidorn** [comment]
@misolori makes sense. Thanks for fixing and explaining.
