### ISSUE TITLE
Initialize repository icon looks our of style

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74978]
Have a repository with no git source control. Open git viewlet -> notice the git icon. It looks out of place compared to the other lean icons imho. Though I would be interested what @joaomoreno thinks

I suggest to use the same recognisable git icon, just styled in a way that matches our theme better.
fyi @bpasero

![Screenshot 2019-06-06 at 15 30 08](https://user-images.githubusercontent.com/1926584/59036698-19148280-8870-11e9-9a2f-5c69a9f70eb4.png)

**Comment by misolori** [comment]
Ah, I totally missed this icon. Thanks for catching that.

**Comment by misolori** [comment]
So either we go with one of the branch/fork/repo icons like so:

![image](https://user-images.githubusercontent.com/35271042/59071779-f5077000-8874-11e9-9ff6-56e5a94e6831.png)

or use their logo:
https://git-scm.com/downloads/logos

@joaomoreno thougts?

**Comment by isidorn** [comment]
Since this is a source contorl tab and git is still not choosen we should not make any assumptions about the user going for git. He might choose tfs.
imho we should go with your proposed solution of using the same activity bar icon. Though I leave it up for @joaomoreno 
btw he is on vacation so he will reply on Tuesady

**Comment by misolori** [comment]
We could alternately use a `+`:

![image](https://user-images.githubusercontent.com/35271042/59134668-dcf52680-8930-11e9-960f-b6fca6854aae.png)

**Comment by misolori** [comment]
Went with the plus for now, we can change it later if think we find a better option.

**Comment by mittalyashu** [comment]
@misolori based on the current icon design pattern you can design a custom icon for git logo with an outline.

![image](https://user-images.githubusercontent.com/29014463/59141856-e5516e00-89d1-11e9-8d54-832e1ede1d43.png)

**Comment by misolori** [comment]
@mittalyashu we need to provide an icon that applies to all SCM providers, not just git as there are many (tfs, svn, etc.):

![image](https://user-images.githubusercontent.com/35271042/59141997-ae487180-896b-11e9-817b-c7d2f2bebe4f.png)

**Comment by isidorn** [comment]
@misoguy  I like the plus.
