### ISSUE TITLE
Debug start and stop icons need weight

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74977]
I understand that due to consistency the debug start and stop icon are lean and not filled.
However these actions have a stronger effect than the usual workbench action. They start the whole program, or kill it.
Users over time have trained their eyes to search for the green triangle or the red rectangle.

Due to that I believe these two icons should be filled.

The blue continue is fine imho

fyi @weinand @bpasero

![Screenshot 2019-06-06 at 15 28 57](https://user-images.githubusercontent.com/1926584/59036566-d2268d00-886f-11e9-9a4c-5d590e0672aa.png)

**Comment by misolori** [comment]
I think you could argue that users have trained to use the solid icons everywhere else, i think this is something that users can get adjusted to overtime. However I do think that the debug controls could be bumped up a bit as they feel *really* thin.

**Comment by isidorn** [comment]
Yeah, let's start with adding more weight to them.

**Comment by roblourens** [comment]
I noticed this with the start debug icon too (on the left). First it feels a bit pixelated on my non-retina display due to being so small/thin and angular, and secondly it doesn't stand out as much as it used to. Tweaking the color might help with the second point? Like if it was a slightly lighter green that might help it stand out more.

**Comment by misolori** [comment]
Made the icons a little thicker, this may make pause/stop a little blurry on non-retina screens:

![image](https://user-images.githubusercontent.com/35271042/59131542-87684c00-8927-11e9-8afa-867ae4010081.png)

**Comment by isidorn** [comment]
Looks better to me. Thanks
