### ISSUE TITLE
Mouse right button is causing "double click" in menu

### ISSUE THREAD

**Issue by mrclolveira** [microsoft/vscode#74979]
- VSCode Version: 1.35.0 and older 
- OS Version: Linux x64 4.15.0-50-generic snap (Ubuntu 16.04)

Steps to Reproduce:

1. With many extensions that adds options in right button menu installed 
2. Click in any part of code with the right button

I believe that, when the menu shows not at the same position as cursor, a option is selected and the release mouse event is causing a click.

![right-button-bug](https://user-images.githubusercontent.com/10092172/59036682-49075a00-885f-11e9-8611-bb95ee80ce41.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by sbatten** [comment]
this was addressed elsewhere
