### ISSUE TITLE
New git icons look too large and clunky

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74976]
Compared to the rest of the workbench the git icons look large and clunky. While the other good icons I would describe as lean and precise. Just personal prefernce.

The + icon is also too large in the watch expressions.

So my suggestions is to simply decrese the size of these a bit.

fyi @joaomoreno @bpasero

![Screenshot 2019-06-06 at 15 20 21](https://user-images.githubusercontent.com/1926584/59035949-a35be700-886e-11e9-9832-ec1e2f123da9.png)

**Comment by misolori** [comment]
@isidorn are you referring to all of the icons in your screenshot or just the discard and plus icon?

**Comment by isidorn** [comment]
The Check box and the refresh primarily. The discard and plus are slightly better.

**Comment by misolori** [comment]
All of our icons are now the same size and stroke weight:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/35271042/60482603-11fe4b80-9c47-11e9-9f7e-806ae4d26b2f.png">

**Comment by isidorn** [comment]
The scm title icons from that picture still look very wide. Though leaving that up to @joaomoreno
