### ISSUE TITLE
Search stop icon too hollow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74970]
The search stop icon which appears for a long runnign search is too hollow. It does not asociate a stop, but I first thought it was a UX glitch.

I suggest to use a filled icon.

fyi @roblourens @bpasero

**Comment by roblourens** [comment]
I disagree, I think a filled icon would look out of place next to our new thin line icons. I like the new one.

**Comment by isidorn** [comment]
We don't have to fill it fully, but it at least deserves more weight imho

**Comment by misolori** [comment]
We've made all of the icons the same size and stroke weight, so this fits in with the rest of our icons:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/60482697-715c5b80-9c47-11e9-9d67-c5a9b63a220a.png" />
