### ISSUE TITLE
Debug console icon needs to be a bit larger

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74973]
I think the debug console icon is like 10% smaller than all the other icons. I believe that is due to the fact that this icon is not new, we are using an old one.
Due to the size it also does not look well alignd

fyi @weinand @bpasero

![Screenshot 2019-06-06 at 15 14 32](https://user-images.githubusercontent.com/1926584/59035586-e2d60380-886d-11e9-94b3-132907d6e450.png)

**Comment by misolori** [comment]
Yes, we did use the same height of the previous one. I can make this larger to match the height of the rest.

**Comment by isidorn** [comment]
That would be great.

**Comment by isidorn** [comment]
This looks better now, however they do not look to be 100% aligned.
Like the debug console should go 1px down. Might that be the centering in the icon?

![Screenshot 2019-06-07 at 09 54 50](https://user-images.githubusercontent.com/1926584/59089414-588fad00-890a-11e9-8d95-4fdda36e327d.png)

**Comment by misolori** [comment]
So this one of the ones that is off by a pixel to avoid pixelation (we center it on the pixel grid). Here's an example:

![image](https://user-images.githubusercontent.com/35271042/59119635-21b89780-8908-11e9-8051-0eeb9cfe3683.png)

The one on the far right is if we make it centered with the gear, however that makes the `>` in the middle very blurry. So we avoid this (or make it less worse) by centering the `>` on the grid, which makes it short by 1px. We do this in other instances (split icons, preview, etc.)

**Comment by isidorn** [comment]
Ok, makes sense. Thanks for the explanation.
Even though for me when it is zomed in the right most looks good. Though I do believe you that it is not optimal when used as an regulard sized icon.

I would even argue that the best solution would be the correct border as in the right option. And the arrow from the left option moved down one pixel. That way the border is centered, but the > will be one px down, but not blurry. This way I believe the eyes will not so easily detect that it is not centered. What do you think about this?

**Comment by misolori** [comment]
To me, this looks off because it's not centered and I'm sure we'd get more people telling us the `>` is not centered 😄:

![image](https://user-images.githubusercontent.com/35271042/59204102-ca5b3700-8b54-11e9-82b4-8fb244e4c775.png)

**Comment by isidorn** [comment]
Yeah this is also not ideal.
I leave the decision up to you, whatever looks best for your eyes. Thanks

**Comment by misolori** [comment]
Ok, I'll leave it like before where the `>` is centered and see what others think. Thanks!
