### ISSUE TITLE
Provide library of icons for extension authors

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74974]
Since we have now changed our icons all the extensions icons which tried to look like our old icons look very alien.

I suggest that once we agree on the new icons (which I love btw) we shuold ping all the popular extensions that they also do an icon pass and update their icons.

fyi @microsoft/vscode

Here's an example of an ssh icon which does not fit to the new style

![Screenshot 2019-06-06 at 15 16 42](https://user-images.githubusercontent.com/1926584/59035779-4bbd7b80-886e-11e9-9f8e-b7eddf37a427.png)

**Comment by misolori** [comment]
Yes, we'll need to provide guidelines for extension authors to follow. In addition, I would love to create a library of icons for extensions to use, but one step at a time 😄

**Comment by isidorn** [comment]
One step at a time makes sense, but I would prefer if we have some guidelines or even better a library of icons before we release this to stable. Since when we release to stable the momentum will be the greatest and we should try to pass the momentum to the extensions.

**Comment by bpasero** [comment]
+1 for providing a library of icons so that extensions can pick a consistent set 👍

**Comment by mittalyashu** [comment]
@misolori Can you also design an icon for VS Live Share since it's part of VS & VS Code.

**Comment by misolori** [comment]
@mittalyashu unfortunately that is an extension that we don't own, it would be up to the LiveShare team to make the change. When the new icons are out you can send out a [feature request on their repo](https://github.com/MicrosoftDocs/live-share/issues/new?template=feature_request.md).

**Comment by eamodio** [comment]
@misolori in the interim could we get access to the figma (or is there a folder of svgs) for the vscode icons so extension can easily use time today?

**Comment by misolori** [comment]
@eamodio that’s what this issue is tracking. We’re currently just waiting to get clearance from our legal time and then we’ll release them via a repo + Figma file. Hoping we release them this week.

**Comment by johnletey** [comment]
That's wonderful news @misolori ... I really looking forward to having this!

**Comment by misolori** [comment]
We’ve finally got a repository with all of our icons and a link to our Figma library:

https://github.com/microsoft/vscode-icons

[image](https://user-images.githubusercontent.com/35271042/63165742-986ec100-c02c-11e9-874a-bb4f5897ac5a.png)

Will close this issue now since the main goal was a repo with all of our icons.
