### ISSUE TITLE
I cannot clone github repository https://github.com/kosiwojciech/Hello-World.git

### ISSUE THREAD

**Issue by kosiwojciech** [microsoft/vscode#74982]
Hello, 
While I try to clone github repository to work on my computer I receive fatal error with information below: 
git clone https://github.com/kosiwojciech/Hello-World.git c:\Users\A311992\Desktop\EDX kurs\HelloWorld\Hello-World
Cloning into 'c:\Users\A311992\Desktop\EDX kurs\HelloWorld\Hello-World'...
fatal: unable to access 'https://github.com/kosiwojciech/Hello-World.git/': Could not resolve host: github.com
What I can do with that to work on my repository from GitHub with Visual Studio on my computer? 
WK

**Comment by mjbvz** [comment]
This seems unrelated to VS Code. Please try asking on stackoverflow to start and post back here if you only see this while using VS Code
