### ISSUE TITLE
Right-Click menu items are not clickable when the main window is laying at the bottom right of the Desktop

### ISSUE THREAD

**Issue by supYI** [microsoft/vscode#74980]
Issue Type: <b>Bug</b>

Repeatable steps:
1. Resize the main window, but not maximized. And drag the window to the bottom right of the Desktop. 
2. Right click at the workspace.

Result:
Some bottom menu items can't be clicked because which are beyoond the Desktop.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.84GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.5.18678
vscode-yaml|red|0.4.1

</details>

**Comment by sbatten** [comment]
@supYI can you please provide a screenshot?
