### ISSUE TITLE
Black glitch in problems view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74989]
Latest insiders, open problems view with some problems. The icons are not shown but a black box making a glitch

fyi @misolori 

![Screenshot 2019-06-06 at 16 00 40](https://user-images.githubusercontent.com/1926584/59039020-4fec9780-8874-11e9-9f5a-afdd88ad8220.png)

**Comment by misolori** [comment]
This is due to the icon exploration and @sandy081's changes to the problems view. I'll fix it.

**Comment by isidorn** [comment]
@misolori it's fine now, thanks for the fix.
