### ISSUE TITLE
Notification bell icon and the creapy smile need update

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74987]
Now that my eyes are acustomed to the new lean and hollow icons I am distrubted by the strong notification bell and the feedback smile in the status bar.
I understand they are probably Octicons, but can we find some octicons which fit the new icons better? These now just look out of place

@bpasero

![Screenshot 2019-06-06 at 15 51 47](https://user-images.githubusercontent.com/1926584/59038371-39920c00-8873-11e9-9bd9-12d747c946d1.png)

**Comment by misolori** [comment]
Status bar icons haven't been updated at all but will be eventually updated.

**Comment by isidorn** [comment]
Yeah. we can do this next milestone.

**Comment by bpasero** [comment]
@isidorn in what theme is that?

**Comment by isidorn** [comment]
GitHub Plus while debugging.
Though I was not aiming for the color here, but for the fullnes of the octicons. They should be less heavy.

**Comment by bpasero** [comment]
I am not sure I agree, it looks great for me in the light theme:

![image](https://user-images.githubusercontent.com/900690/59091824-6ea06c00-8910-11e9-9586-f80e0d3886b9.png)

**Comment by isidorn** [comment]
@bpasero well that is how they looked from day 1. I am not saying they do not look great, but they look alien compared to the other new icons. No icon we have now is filled and this ones are, doesn't that look odd to you?

**Comment by bpasero** [comment]
Yeah, I think if there is a proposal for changing the octicons I would like to see it in action and then judge based on that.

**Comment by misolori** [comment]
Closing this in favor of https://github.com/microsoft/vscode/issues/76909
