### ISSUE TITLE
All breakpoint icons should have same size

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74984]
Currently the breakpoint icon and the conditional breakpoint icon have a different size. Resulting in the effect that after you add a condition to a breakpoint the whole icon jumps

fyi @bpasero @weinand 

![breakpoints](https://user-images.githubusercontent.com/1926584/59037336-5299bd80-8871-11e9-9c96-760f5e532dca.gif)

**Comment by misolori** [comment]
Same problem as #74981, fixed via https://github.com/microsoft/vscode/commit/3959ab1fec82121f51d1aa654f69b991b37bf139
