### ISSUE TITLE
Diff editor title icons need an update

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74988]
1. Have some changes, open the file in the diff view

Notice the icons. The one of them has a blue thing which is out of space with our monochrome icons and the other to show whitespace is designed by @alexandrudima  some years ago and I think the whole team was looking forward to getting a nicer icon for this :)

Also the arrows look too strong and should be a bit lighter.

fyi @joaomoreno @bpasero 

![Screenshot 2019-06-06 at 15 54 38](https://user-images.githubusercontent.com/1926584/59038618-9a214900-8873-11e9-8a51-ca4456ff83cc.png)

**Comment by isidorn** [comment]
I suggest to use the same arrows that are used in the find widget

![Screenshot 2019-06-06 at 15 59 24](https://user-images.githubusercontent.com/1926584/59038922-19168180-8874-11e9-82bb-00ae2b92a148.png)

**Comment by bpasero** [comment]
They where not updated yet, or where they?

**Comment by misolori** [comment]
Ah, this is because I missed the icons in the mode when tabs are not visible. These are in the regular view:

![image](https://user-images.githubusercontent.com/35271042/59064438-16f5f800-885f-11e9-9d3e-f94699d1f1d7.png)

**Comment by misolori** [comment]
The question here: should we consistently use the ⬆️⬇️ or ⬅️➡️ for next/prev? I personally prefer ⬆️⬇️ since they use the space better and allow for some spacing.

**Comment by isidorn** [comment]
This is better now, however the up down and the whitespace funnky one look a bit too large compared to the two outer neighbors. I think similar to the explorer refresh they need to be reduced a bit. Due to that reopening so we discuss.

As for the position of the arrows, I like that here we start using up and down arrows. Feel free to change, now is the best time since we are changing all the icons.

I would also change it for the find widget. Created https://github.com/microsoft/vscode/issues/75056 for that one

![Screenshot 2019-06-07 at 10 38 01](https://user-images.githubusercontent.com/1926584/59091803-63e5d700-8910-11e9-8499-19159e91f1b6.png)

**Comment by bpasero** [comment]
Yes they seem overly large.

**Comment by misolori** [comment]
They're all actually relatively the same size, but they can appear smaller:

![image](https://user-images.githubusercontent.com/35271042/59122043-88d94a80-890e-11e9-8457-dea112929400.png)

Here's what it would look like if we reduce the size of the arrows and whitespace icon: 

<img width="50%" src="https://user-images.githubusercontent.com/35271042/59122176-f9806700-890e-11e9-9522-6948e5830d75.png">

I think they look too small at this point, I'd rather leave them the way they are. Thoughts?

**Comment by isidorn** [comment]
I would reduce the size of the arrows, but keep the larger size of the whitespace icon.
Just personal preference and what I think would be best for my eyes.

**Comment by misolori** [comment]
These were updated so all icons are the same size and stroke weight:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/35271042/60482108-1d507780-9c45-11e9-81f2-b7dba367253a.png">



<img width="217" alt="image" src="https://user-images.githubusercontent.com/35271042/60467646-09d4ea80-9c0c-11e9-95fc-b1ea1819d46d.png">
