### ISSUE TITLE
Disconnect icon is too smart and hollow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74985]
Same as the stop and start the disconnect also needs to be filled.
Other than that previously I really liked it that the stop and disconnect icons where very simmilar. WHile that is no longer the case I fear the users might be surprised when they see the disconnect for the first time.
IMHO this icon is too smart, and we should make one which looks more similar like a stop but has some differentation

fyi @weinand @bpasero

![Screenshot 2019-06-06 at 15 44 09](https://user-images.githubusercontent.com/1926584/59038012-a658d680-8872-11e9-8c0d-4a24b6da755e.png)

**Comment by misolori** [comment]
As with #74977, I do think there is an adjustment period so I would wait to try to change icons back to the solid versions. Maybe come back in a week after trying this out to see how it feels?

**Comment by isidorn** [comment]
I think this will feel the same in a week. I tried out all the icons with an open mind and liked most of them.
This is the one which I just find cute but not working. So imho we should change it.

Though let's wait and see what @weinand and @roblourens have to say.

**Comment by misolori** [comment]
We've made all of the debug icons have a slightly stronger weight to stand out (these are the only exception):

<img width="484" alt="image" src="https://user-images.githubusercontent.com/35271042/60482756-ab2d6200-9c47-11e9-9428-bc1bc2577e58.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/35271042/60482787-cd26e480-9c47-11e9-88bb-ce9bfb7e1b1d.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/35271042/60482834-ef206700-9c47-11e9-89f9-c9d94f67df4b.png">
