### ISSUE TITLE
./scripts/code.sh crashes when '1' is the first arg

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7498]
Accidentally hit 1:

![image](https://cloud.githubusercontent.com/assets/2193314/15946497/f7b07f26-2e4b-11e6-8a42-ecb476300dc2.png)

**Comment by bpasero** [comment]
For some reason "1" becomes "typeof number" when we parse arguments.

**Comment by joaomoreno** [comment]
@bpasero Adding you as an assignee in case you want to fix this for June. Else, unassign yourself and put it for July.

**Comment by bpasero** [comment]
Pushed a workaround. Moving to July.
