### ISSUE TITLE
Output title icons do not look vertically aligned

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74990]
The output panel title icons do not look vertically aligned. This is probably due to the fact that the lock / unlock icon looks a bit larger than its neighbours. I suggest to decrease the size of this icon a bit.

fyi @bpasero 

![Screenshot 2019-06-06 at 16 02 12](https://user-images.githubusercontent.com/1926584/59039127-81656300-8874-11e9-9740-12daada382c3.png)

**Comment by misolori** [comment]
These icons are now vertically centered:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/35271042/60482407-2e4db880-9c46-11e9-9f37-8bdaaf019f4e.png">
