### ISSUE TITLE
Keytar is a layer breaker

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#74997]
See https://github.com/microsoft/vscode/blob/078da2bca6c1f2d52c1293f1dff964f6dcb54b1e/src/vs/workbench/api/browser/mainThreadKeytar.ts#L24-L26

This needs a different solution, something like a credentials service with some implementation for the web.

cc @bpasero

**Comment by jrieken** [comment]
Volunteers? @chrmarti

**Comment by bpasero** [comment]
Yes this sounds like a candidate for yet another service for that matter, ideally async.

**Comment by chrmarti** [comment]
@jrieken I don't know why this was put in `browser`.

@bpasero Could you tell me where the different pieces for a service should go? Like an example I can copy from.

**Comment by jrieken** [comment]
@alexandrudima moved this here, probably an oversight. I just pushed a fix for this, adding a credentials service for, having an implementation for node-only

**Comment by jrieken** [comment]
For the future we should look into this new, emerging API https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API

**Comment by bpasero** [comment]
Thanks 👍

**Comment by jrieken** [comment]
interesting read: https://blog.arnellebalane.com/the-credential-management-api-7eb5650d23ca
