### ISSUE TITLE
[json] schema not loading behind working proxy everything else works fine

### ISSUE THREAD

**Issue by kemotoe** [microsoft/vscode#74991]
- VSCode Version: 1.35.0 (user setup)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

Corporate proxy + PC with Windows properly configured to use the proxy.
No problem to search and install vscode extensions or auto update

Problem only arises when trying to load any json schema I get the following error:

Problems loading reference 'https://schemastore.azurewebsites.net/schemas/json/package.json': Request vscode/content failed unexpectedly without providing any details

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rmcc13** [comment]
I get the same error with the same message when trying to load either  http://json.schemastore.org/prettierrc or https://json.schemastore.org/prettierrc. This is also behind a corporate proxy

**Comment by jtulk** [comment]
Think I have a similar error: 

`Problems loading reference 'https://raw.githubusercontent.com/json-schema-org/json-schema-spec/master/meta/validation': Request vscode/content failed unexpectedly without providing any details.`

**Comment by kabel** [comment]
Same issue here. Further details:

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

Problem Detail:
```
unable to get local issuer certificate(768)
```

Extension Host Log:
```
[exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
```

**Comment by retifrav** [comment]
I also have this error:

```
[exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
```

Visual Studio Code: 1.37.0
OS: Windows 10.0.18362.267 x64

Just in case I tested it with an internet connection shared from my phone to exclude the corporate network interference - it is still reproducible. And there is no proxy set in the system.

**Comment by chrmarti** [comment]
Looks like https://github.com/microsoft/vscode/issues/79044.

Is this still a problem in the latest insiders build? https://code.visualstudio.com/insiders/

**Comment by retifrav** [comment]
I installed **1.38.0-insider** and didn't get the `ProxyResolver#getCertificates` error with this one, so apparently it's fixed there.

**Comment by chrmarti** [comment]
/duplicate #79044

Thanks @retifrav.
