### ISSUE TITLE
Angular 7 Breakpoints are not hit

### ISSUE THREAD

**Issue by Javaman2** [microsoft/vscode#74993]
Issue Type: <b>Bug</b>

1) I start up my backend in ASP.NET Core 2.2 (no issues)
2) I type in NG Serve (no issues)
3) I then use open debugger and select the "Launch Chrome against localhost with sourcemaps" 
4) Browser opens fine, but no breakpoints in application are hit.
 
I suspect this has something to do with WebPack but am not sure.

Here's the launch.json
`{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Launch Chrome against localhost, with sourcemaps",
          "type": "chrome",
          "request": "launch",
          "url": "http://localhost:8080/dashboard",
          "sourceMaps": true,
          "webRoot": "${workspaceFolder}/somepath/src/app"
      },
      
  ]
}`

I am able to set break points in Chrome where the TS SourceMaps work as expected.

Expected Results: Breakpoints should be hit in Visual Studio Code.
Actual Results: Once browser opens, the breakpoints all become greyed out.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (22.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.19.1
powershell|ms-|2019.5.0
debugger-for-chrome|msj|4.11.3
csharp2ts|raf|0.0.22
markdown-preview-enhanced|shd|0.4.1
vscode-scss-formatter|sib|1.4.1
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by roblourens** [comment]
Do any of the debugging tips on https://github.com/microsoft/vscode-chrome-debug#the-scripts-command help? How did you pick that webRoot?

**Comment by Javaman2** [comment]
.scripts command not found in Debug console.
          "sourceMaps": true,
          "webRoot": "${workspaceFolder}/UI/projectname/src/app"

When I set a breakpoint, the breakpoint window shows the path and is enabled.  Those paths all contain the webRoot as shown above, but as soon as debug starts those breakpoints are disabled.

**Comment by roblourens** [comment]
> .scripts command not found in Debug console.

Are you sure you typed it correctly?

**Comment by Javaman2** [comment]
How could I not type .scripts correctly? Debug console gave me the error.

**Comment by roblourens** [comment]
Sorry, I just have to ask the obvious question because I am not sure what the problem would be. What error exactly do you see when you type `.scripts`?

**Comment by roblourens** [comment]
Also you can set `"trace": true` in your launch config and upload the log here. It writes the log path to the debug console.
