### ISSUE TITLE
Unequal length of the filename tabs

### ISSUE THREAD

**Issue by eloyucu** [microsoft/vscode#74994]
Hi everyone.

The lenght of the tabs of the files opened in a session is dependent on the name of the file, and this is good because you can see the whole name of the file (even part of the route if files with same name are opened at same time). 

![image](https://user-images.githubusercontent.com/2331045/59041998-f38c7680-8879-11e9-8864-f868631ac20d.png)

The thing is that sometime I would like to close some of this tabs by clicking (because the options on the right click are not enough sometimes). Then, it could be great that the length of all of the  tabs was the same to don´t need to move the mouse to search the X when you try to close some adjacents tabs.

My proposal is to let the current dynamic length by default, but if you are over the "tabs zone" for 2~3 seconds these tabs will adjust their lenght to a fixed and equal. I hope you like!! :)

**Comment by gjsjohnmurray** [comment]
How about you set `workbench.editor.tabCloseButton` to `left`?

**Comment by egamma** [comment]
Does the suggestions from @gjsjohnmurray work for you and addresses your issue?

**Comment by eloyucu** [comment]
Thanks @gjsjohnmurray it works perfectly!!! 👍 :)
