### ISSUE TITLE
typescript build in prelaunchtask fails

### ISSUE THREAD

**Issue by dhananjay1405** [microsoft/vscode#74995]
Issue Type: <b>Bug</b>

Before this update, i had configured tsc: build in prelaunchtask in launch.json and there was no need to include it in task.json, but post this update, this fails. Also configuring typescript as task in task.json fails to attach debugger and gives build error

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vsc-material-theme|Equ|2.9.0
vsc-material-theme-icons|equ|1.0.4
code-beautifier|mic|2.2.1
vscode-scss|mrm|0.6.2
indent-one-space|use|0.2.5

</details>

**Comment by mjbvz** [comment]
Please share information about the error and your general project structure

**Comment by dhananjay1405** [comment]
The issue got fixed after changing preLaunchTask value like this
**Before:** tsc: build - server\\tsconfig.json
**After:** tsc: build - server/tsconfig.json

replacing backslash (windows style) with forward slash (unix style) fixed the issue.

**Feature Request:** Can VS Code parse both type of file path (i.e. Windows and Unix style). If not possible it would be appreciated if VS Code could generate specific error for such scenario (alteast for few builds until everyone migrates to complete Unix style file paths)

**Comment by alexr00** [comment]
I will add an error for all typescript tasks that have "\\" in them.

**Comment by alexr00** [comment]
To verify use Windows and the VS Code project. Add the following task to your tasks.json then try to run it. You should get a nice message telling you what's wrong.
```
		{
			"type": "typescript",
			"tsconfig": "src\\tsconfig.json",
			"option": "watch",
			"problemMatcher": [
				"$tsc-watch"
			]
		}
```

**Comment by dhananjay1405** [comment]
@alexr00 which build / version of VS Code (stable release) this fix will be rolled-out ?

**Comment by alexr00** [comment]
It should be in 1.37.0.
