### ISSUE TITLE
Extension Marketplace is not DNSSEC validated

### ISSUE THREAD

**Issue by remus32** [microsoft/vscode#74996]
Issue Type: <b>Bug</b>

marketplace.visualstudio.com hasn't got DNSSEC set up, so the extensions pane shows 'We cannot connect to the Extensions Marketplace', a quite common problem.
It isn't a real source code issue, but wanted to report it anyway.

I use Arch Linux, with DNSSEC validation enabled in systemd-resolved.
Obviously affects both the OSS build and the Microsoft binary. 

Cheers

VS Code version: Code - OSS 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-21T12:30:20.933Z)
OS version: Linux x64 5.1.7-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 2683)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (8.00GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by egamma** [comment]
I'll forward the issue to the marketplace team.

Closing since it is not a VS Code issue.

**Comment by Hardhik** [comment]
Hi Remus,

Thanks for reporting this issue. We are currently dependent on the Azure DNS which unfortunately does not have this support yet. Although Azure has long term plans to support this, I cannot provide you an ETA.

Please feel free to reach out to me if you have any other concerns/questions reg. Marketplace.

Thanks,
Hardhik.

**Comment by remus32** [comment]
Ok, thanks
