### ISSUE TITLE
Allow overriding hardcoded jsconfig/tsconfig defaults

### ISSUE THREAD

**Issue by yamalight** [Microsoft/vscode#75]
I'm writing pretty much all of my projects using ES6.
So if I want to use Code, I need to add `jsconfig.json` file that contains following snippet to every project I work on:
```
{
  "compilerOptions": {
    "target": "es6"
  }
}
```
Doing this over and over again is annoying to say the least.

I had a quick look at the code and from what I'd grasped the current defaults are hardcoded.
Can we instead have a global default `jsonfig.json` in user folder (e.g. next to user config) that'll override hardcoded defaults if present? 
Or perhaps part of user config can allow overriding values in it (e.g. `javascript.compilerOptions.target`)?

**Comment by voidpp** [comment]
+1, if jsconfig could be defined in the user config, or something else globally, will be very useful. I have several es6 projects, inside different folders with a lot of other projects, result of I have to open the root folder with thousands of files, result of the code completion, code snippets, etc is unusable.

**Comment by jrieken** [comment]
We have made ES6 the default. It should address the wish addressed in this issue.
