### ISSUE TITLE
Question: Where in the code is 'Install Extension'?

### ISSUE THREAD

**Issue by dfinke** [Microsoft/vscode#750]
I'm working with implementing functionality around QuickPickItem and would like to add indicators and links in a similar way, readme, download and last updated

![image](https://cloud.githubusercontent.com/assets/67258/11443986/de2746d4-94ef-11e5-9fd0-4eb300222f3d.png)

**Comment by jrieken** [comment]
Check `~/.vscode/extensions/`

**Comment by mikemimik** [comment]
May I please ask for clarification, @jrieken. What is one supposed to find in `~/.vscode/extensions/`?

**Comment by egamma** [comment]
The extension folder doesn't help a lot here :smile:, but we made the QuickPick item support more rich in 0.10.8.

From https://code.visualstudio.com/Updates#_extension-authoring
>You can now validate user input, get called when an item is focused in Quick Pick, and Quick Pick now has room for additional details. Also Quick Pick now supports GitHub Octicons like the Status Bar.
