### ISSUE TITLE
Add option to quick open files in edit mode instead of preview

### ISSUE THREAD

**Issue by snortblt** [microsoft/vscode#75003]
It would be convenient to be able to open files directly in Edit mode instead of Preview mode via Quick Open on a per-file basis. I'm aware of the `enablePreviewFromQuickOpen` setting, but I'd like to have a keyboard` shift+enter`/`shift+click` command to toggle that behavior temporarily while quick opening a file. In other words, whatever `enablePreviewFromQuickOpen` is set to, if I hold `shift` down I could get the inverse behavior for that file.

**Comment by eamodio** [comment]
@snortblt While it isn't exactly what you are asking for, but you can quickly open files from the QuickOpen as pinned (in "Edit mode") by pressing the right-arrow key. This has the added benefit of keeping the QuickOpen open so that you can do it for many files at once.

Also note that pressing `alt` (`option` on mac) opens the file in a new editor group pinned as well.

Hope that helps

**Comment by egamma** [comment]
@snortblt does the explanation given in by @eamodio cover your issue?

**Comment by snortblt** [comment]
Thanks @eamodio. It's a great tip, but I don't necessarily want to have it pinned. Unpinned edit mode is by far the way I work with files the most.

**Comment by eamodio** [comment]
@snortblt I'm not sure I understand. Maybe the terminology is confusing things -- AFAIK, there are only 2 editor tab modes, preview (unpinned) and not preview (pinned). I thought that "edit mode" meant that the editor wasn't a preview tab. Is that the case or are you asking for something else?

**Comment by snortblt** [comment]
@eamodio Yes. Terminology is the issue here. My bad. Your suggestion of using the right arrow is doing the basic behavior I'm looking for (now that I actually tried it). There are only two file modes but my understanding was that they are referred to as "preview" and "edit". When you said "pinned" I assumed you were referring to the full VS pinning behavior which has been requested at https://github.com/Microsoft/vscode/issues/12622. Didn't realize VS Code does _not_ have that feature. Thanks again for the tip.
