### ISSUE TITLE
Invoking mvn command using right-click on POM failing - Parent/Child Maven Project 

### ISSUE THREAD

**Issue by bigtfromaz** [microsoft/vscode#75007]
Version information:
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open parent/child Maven project folder
2. Right-click on any of the POM files and perform any command, compile, clean...

Error message box pops up with this text:  `Command "maven.goal.xxxxx" fails.  Cannot read property 'endsWith' of null`

The same command from the Terminal window runs correctly.  This may be an issue launching the command.

Unsure if this is an issue with the plug-in or VSCode 

Does this issue occur when all extensions are disabled?: Unsure,Maven and Java extensions are needed to recreate.

**Comment by bigtfromaz** [comment]
#Here is an image of the message box.  Unfortunately I upgraded VS Code and then converted an existing project to be parent child.  I cannot tell you if this problem existed before putting in the latest upgrade.
 
![ErrorMessage](https://user-images.githubusercontent.com/7926086/59054537-c1165580-8848-11e9-98fb-5e2e21c8c59d.PNG)

**Comment by oliver-zhao** [comment]
I have the same issue after vscode update.

**Comment by bigozzi-inspect** [comment]
Me too

**Comment by achukov** [comment]
same error

**Comment by ryjo1026** [comment]
Looks like this is the same issue: https://github.com/microsoft/vscode-maven/issues/337. I fixed this by manually setting the integrated shell in settings.json:
```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
```

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-maven/issues/337
