### ISSUE TITLE
Copy Columns 

### ISSUE THREAD

**Issue by PIMarine73** [microsoft/vscode#75002]
In powershell 5.1 I can get results with multiple columns and highlight just one column and copy it. In VSCode when I try it copies the whole line, not just the column I am trying to copy. Would like to be able to do this in VSCode
![image](https://user-images.githubusercontent.com/51454740/59050529-89170e80-8858-11e9-9172-70f08c37e245.png)

![image](https://user-images.githubusercontent.com/51454740/59050494-700e5d80-8858-11e9-9078-9f8098fb39aa.png)

**Comment by egamma** [comment]
this is supported, pls see https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection
