### ISSUE TITLE
File watcher crashes when opening Large folder

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#75004]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I opened the root folder of my disk by mistake and then file watcher and rg blew my machine.

![image](https://user-images.githubusercontent.com/876920/59051103-f4ed7d00-8840-11e9-8334-288a24a0817b.png)

VS Code version: Code - Insiders 1.36.0-insider (7a5bca9fafbbb23de289179be95e9c4832540c02, 2019-06-06T11:36:26.351Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 4.15.0-50-generic
Remote OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 12, 10|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|-psn_0_3937217|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: penlvdevbox|
|OS|Linux x64 4.15.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|7.75GB (1.92GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: penlvdevbox|
|OS|Linux x64 4.15.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 3599)|
|Memory (System)|7.75GB (1.92GB free)|
|VM|0%|
</details>

**Comment by rebornix** [comment]
Assigned to @roblourens first as the screenshot said `rg` but actually I received OOM from chokidar.

**Comment by roblourens** [comment]
`rg` would be from an extension or a workspaceContains clause. But those are limited to 5 seconds. File watcher crash seems like a real issue though. I don't know what to do about that.

**Comment by rebornix** [comment]
Close as it's not operational.
