### ISSUE TITLE
Breadcrumbs view show duplication of entire file twice in TypeScript

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#75019]
Issue Type: <b>Bug</b>

(Using Fedora Linux)

As soon as I updated to 1.35 I started to use the breadcrumbs and playing with the ctrl-left collapse all shortcut. Within a few minutes I had a weird case of the entire file being duplicated twice in the breadcrumbs view. See the screenshot.

![Screenshot from 2019-06-06 20-16-14](https://user-images.githubusercontent.com/12832280/59060591-5a6d5800-8899-11e9-8f52-f8f1b7da74de.png)

While in this state I can scroll up and down the bottom part, but the identical top part is not reachable.

If I can reproduce it I will add to this report.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 5.0.9-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.66GB (1.30GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
markdown-preview-github-styles|bie|0.1.6
vscode-dash|dee|2.1.0
prettier-vscode|esb|1.9.0
shell-format|fox|5.0.1
vsliveshare|ms-|1.0.337
debugger-for-chrome|msj|4.11.3
LiveServer|rit|5.6.1
shellcheck|tim|0.6.0
quokka-vscode|Wal|1.0.224

</details>

**Comment by mjbvz** [comment]
I can't repo this. Please share some example code if you see this again so we can investigate

**Comment by jeanp413** [comment]
I think this is the same as #75263

**Comment by mjbvz** [comment]
Closing as potential duplicate
