### ISSUE TITLE
Latest version is using significant system resources

### ISSUE THREAD

**Issue by rjucf** [microsoft/vscode#75011]
Issue Type: <b>Bug</b>

When I start up Visual Studio Code on my mac laptop my cpu fan sounds like it is going to take off even after disabling all extensions.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 7|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Hi, can you please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Start by sharing the output of running `code --status`

**Comment by UncleKo** [comment]
I'm having the same issue after the last update: 1.36.0-insider on Windows10 Home 1903 (build 18362.175). It stops when I close Insiders.
