### ISSUE TITLE
Can't tell when error and warning and both present

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#75010]
With the new warning color, the error blends into the warning, and it's hard to tell at a glance that they are both there:

![image](https://user-images.githubusercontent.com/323878/59054460-9af0b580-8848-11e9-9991-b8f72bf39781.png)

vs

![image](https://user-images.githubusercontent.com/323878/59054453-94623e00-8848-11e9-9f5f-6972b7952254.png)

**Comment by roblourens** [comment]
Not sure what the solution is, maybe we only draw the error and not the warning. Even then the colors are a bit similar.

**Comment by roblourens** [comment]
I can also override this in my own theme settings...

**Comment by misolori** [comment]
I agree that we should only draw one at a time, I think this would look better:

![image](https://user-images.githubusercontent.com/35271042/59055397-93caa700-884a-11e9-9b8b-ca470713f7a6.png)

**Comment by roblourens** [comment]
Yeah, people might want to know when both are present, but I don't know if the old way of overlaying them is that useful for that anyway.

**Comment by misolori** [comment]
Yea that would depend on if that is useful. We could shift the errors below if there are warnings on the same line?

![image](https://user-images.githubusercontent.com/35271042/59055820-9b3e8000-884b-11e9-9694-44d15da69c9c.png)

**Comment by misolori** [comment]
@sandy081 @bpasero we should discuss this in the upcoming ux sync

**Comment by misolori** [comment]
Not sure if this is still a common issue that needs to be addressed? Personally, I've yet to see this.

**Comment by roblourens** [comment]
I can't think of a time in real life when it's been an issue

**Comment by sandy081** [comment]
Ok, Closing this as it is not seen in real time.
