### ISSUE TITLE
VSCode integrated terminal clearing all text on first use

### ISSUE THREAD

**Issue by matrizx** [microsoft/vscode#75015]
When I launch up VSCode, and first type something into the integrated terminal on Windows 10 the text clears. It looks like this:
![ezgif-2-a47c443f02bc](https://user-images.githubusercontent.com/47290299/59057052-6122ad80-884e-11e9-8c53-556076ecb9f6.gif)

I tried this on two Windows 10 machines, it does this on both of them, and then tried it on an Arch Linux machine and an Ubuntu machine and it does not do it on either.

- VSCode Version: 1.36.0
- OS Version: Windows 10 1809

Steps to Reproduce:
1. open VSCode on Windows and open the integrated terminal
2. enter some text into it

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
