### ISSUE TITLE
Reduce activity bar size for icon explorations

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#75013]
From https://github.com/microsoft/vscode/issues/74969#issuecomment-499489483

We should adjust the size of the activity bar since the icons are lighter and smaller:

<img width="25%" src="https://user-images.githubusercontent.com/35271042/59056389-ee650280-884c-11e9-83a4-8040231b6abb.png" />

**Comment by isidorn** [comment]
Yes, save me some pixels and I might actually consider to show the activity bar again like I did in my youth.

**Comment by ipstone** [comment]
Where did you get the smaller icon? I don't have that in my vscode! - I like smaller icons.

**Comment by misolori** [comment]
@ipstone this is part of our icon exploration, see #8017 for more info

**Comment by sbatten** [comment]
@misolori at 46px
![image](https://user-images.githubusercontent.com/6561887/59892426-d5506b80-938d-11e9-85d3-d6ae085fac97.png)

**Comment by misolori** [comment]
Since the activity bar icons are now 24x24 I've reduced the activity bar to 48px and also reduced the size of the activity bar badges:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/35271042/60482285-ab2c6280-9c45-11e9-941b-532b82835eab.png">
