### ISSUE TITLE
Search in Files, Match Whole Word, Cyrillic characters

### ISSUE THREAD

**Issue by rousni** [microsoft/vscode#75016]
- VSCode Version: 1.35.0
- OS Version: Windows 1903

Steps to Reproduce:

1. Open a folder containing text files with Cyrillic characters in the files' content
2. Search in Files, Match Whole Word - the option is ineffective
[http://web.uni-plovdiv.bg/rousni/screenshot.png](url)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/27280
