### ISSUE TITLE
Default terminal attribute messes up after a reset

### ISSUE THREAD

**Issue by ivangonzalezg** [microsoft/vscode#75021]
After using the "reset" command in the terminal all the fonts are in bold, even in the new terminals

![Before reset](https://user-images.githubusercontent.com/42500072/59062002-64c42d80-886a-11e9-8b8f-de35f1946bfe.png)
![After reset](https://user-images.githubusercontent.com/42500072/59062003-64c42d80-886a-11e9-9ebd-885f07c511da.png)

**Comment by Tyriar** [comment]
Thanks for the report, created an upstream issue https://github.com/xtermjs/xterm.js/issues/2196

**Comment by adelphes** [comment]
@Tyriar is this fix likely to make it into a May Recovery build? It's making the integrated terminal pretty much unusable after any executing command outputting colors.

**Comment by Tyriar** [comment]
@adelphes yes. Also it should be fixed in Insiders today if you want to verify it.

**Comment by Tyriar** [comment]
Fixed in release/1.35, this is coming in 1.35.1.

To verify:

1. On mac/linux open a terminal
2. Setup a $PS1 prompt variable with color if you haven't yet
3. Run `reset`
4. Type in some text and make sure the color is fine
5. Create a new terminal and make sure the color is fine
