### ISSUE TITLE
Terminal renderers' line wrapping breaks when using git-bash-prompt

### ISSUE THREAD

**Issue by amyspark** [microsoft/vscode#75028]
- VSCode Version: 1.36.0-insider (7a5bca9fafbbb23de289179be95e9c4832540c02)
- OS Version: MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Install [`bash-git-prompt`](https://github.com/magicmonty/bash-git-prompt) and enable it in your shell.
2. Open Visual Studio Code inside a Git repository with a reasonably lengthy state (e.g. with stashed, modified, and untracked files).
3. Do many things so that the cursor is in the last visible line of its console.
3. Write a lengthy command that forces a line wrap e.g. `rails g model Sector id:string area:references description:string`.

You'll see that it wraps over the same line instead of generating a new one.

Does this issue occur when all extensions are disabled?: Yes

This issue exists with both renderers (canvas and DOM-based), only when writing a command line. Both work correctly when browsing the command history.

**Comment by Tyriar** [comment]
@amyspark can you show a screenshot of what it looks like in VS Code and what it looks like in the default mac terminal?

**Comment by amyspark** [comment]
@Tyriar , sure. The following is with brewed Bash 5.0.7.

Terminal in High Sierra never occupies the last line:
<img src="https://user-images.githubusercontent.com/13498015/59120729-aece1180-8945-11e9-9c18-059895af7396.jpg" width="512px" />

This is VS Code with the canvas-based renderer.
<img src="https://user-images.githubusercontent.com/13498015/59120730-af66a800-8945-11e9-9173-fdc5bf9f1cda.jpg" width="512px" />

Do notice I'm using emojis for the Git statuses. This is my `.git-prompt-colors.sh`:
```bash
# This is a theme for gitprompt.sh,
# it uses the default Gentoo bash prompt style.

override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Single_line_NoExitState_Gentoo"
  GIT_PROMPT_BRANCH="${Cyan}"
  GIT_PROMPT_MASTER_BRANCH="${GIT_PROMPT_BRANCH}"
  GIT_PROMPT_UNTRACKED=" ${Cyan}?"
  GIT_PROMPT_CHANGED=" ${Yellow}+"
  GIT_PROMPT_STAGED=" ${Magenta}●"
  GIT_PROMPT_STASHED=" 📦 "
  GIT_PROMPT_SEPARATOR=":"
  GIT_PROMPT_SYMBOLS_AHEAD="📤 "
  GIT_PROMPT_SYMBOLS_BEHIND="📥 "

  GIT_PROMPT_START_USER="${BoldGreen}\u@\h:${BrightBlue}\w${ResetColor}"
  GIT_PROMPT_START_ROOT="${BoldRed}\h:${BrightBlue}\w${ResetColor}"

  GIT_PROMPT_END_USER="${ResetColor} \$ "
  GIT_PROMPT_END_ROOT="${ResetColor} \# "
}

reload_git_prompt_colors "Single_line_NoExitState_Gentoo"
```

**Comment by Tyriar** [comment]
Oh yeah, it's the emojis unfortunately as we need to improve unicode width detection. This is tracked in https://github.com/xtermjs/xterm.js/issues/1709
