### ISSUE TITLE
[coffeescript] syntax coloring support for ES6

### ISSUE THREAD

**Issue by shakvaal** [Microsoft/vscode#7502]
Standard `tmLanguage` syntax definitions don't support ES6 syntax, e.g. keyword `yield`, classes `ArrayBuffer` and `Symbol`, etc.

For Coffeescript [this](https://github.com/aponxi/sublime-better-coffeescript/blob/master/CoffeeScript.tmLanguage) could be used, as for JS and TS - I have no suggestions, because I don't use those.

**Comment by aeschli** [comment]
`yield` is now colored in TS and JS. For coffeescript we use the grammar from https://github.com/textmate/coffee-script.tmbundle. I suggest to file an issue there.

**Comment by aeschli** [comment]
I changed the grammar to https://github.com/atom/language-coffee-script with support for 'yield' and 'ArrayBuffer'.
Please file additional issues directly against that grammar.
