### ISSUE TITLE
Allow option to set titlebar to custom inset

### ISSUE THREAD

**Issue by austincondiff** [microsoft/vscode#75022]
An option to set the titlebar to custom inset as is in Atom would give users the option to have a larger titlebar if desired.

**Comment by egamma** [comment]
@austincondiff are you using the custom titlebar?

//fyi @sbatten

**Comment by austincondiff** [comment]
Currently I am using the custom title bar. However it is 22px tall. The custom inset title bar is 36px tall and the traffic lights are inset to be equidistant to the top left and bottom.
