### ISSUE TITLE
vscode-uri escapes colon in drive letter

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#75027]
We are trying to use vscode-uri in the debug adapter, and one issue is that vscode-uri uri-encodes the colon after the drive letter in a windows file uri which causes issues downstream. 

I see https://github.com/microsoft/vscode/issues/2990#issuecomment-204295374 but I'm worried that will just cause other issues by not encoding other characters. And I'm wondering why we do this by default, this file URI scheme spec calls out `file:///c:/foo` as being a valid file URI. https://tools.ietf.org/html/rfc8089

**Comment by jrieken** [comment]
> issues by not encoding other characters

Like which? Do you have sample?

**Comment by jrieken** [comment]
> which causes issues downstream

What issues are those?

**Comment by roblourens** [comment]
If we use `toString(true)` then we would get `"file:///c:/foo blah/bar"` instead of `"file:///c:/foo%20blah/bar"` for example which Chrome doesn't recognize.

Also Chrome uses the format `"file:///c:/foo/bar"` so if we ask it to set a breakpoint in `"file:///c%3A/foo/bar"` it doesn't recognize that script.

We can work around it on our end, this is more just a question about why it's done that way.

**Comment by jrieken** [comment]
I always only looked https://tools.ietf.org/html/rfc3986 and there is no clear word on how aggressive to encode. My guarantee is that we decode whatever gets encoded, e.g preserving the identify. The challenge is when urls as strings get send around esp to different systems or when uris are compared in string form. All of that wasn't part of the original work...

We can consider making this change (I have already done some similar changes this milestone) but I am always afraid that vscode has persist uris as string that it compare such uris - as strings, not revising them first.

**Comment by jrieken** [comment]
Closing as designed, after the recent avalanche of regressions after some URI changes I am too scared to change more here. For the future we can consider adding another overload to the toString-function
