### ISSUE TITLE
When Debug Toolbar is docked show all the time

### ISSUE THREAD

**Issue by velara3** [microsoft/vscode#75020]
When the debug toolbar is docked make it show all the time.

My work flow is:

- Edit code with the Explorer open
- Click the debug button on the side of VSC
- Click the launch / debug configuration
- Test the application and find a bug
- Open the Explorer view and repeat these step ad infinitum

If you watched my workflow I'm constantly switching back and forth between the Explorer and Debug view. Having the debug toolbar docked I don't have to switch views.

**Comment by velara3** [comment]
It's not the same as #69298.

**Comment by isidorn** [comment]
So you bascially want to show the debug toolbar also in the explorer.
This is a fair feature request. However it is not on our immediate plan, thus assigning to backlog.

**Comment by tp** [comment]
@velara3 I was also looking for this feature.

As it turns out though for me there is a decent workaround of moving the floating debug bar like this:

![image](https://user-images.githubusercontent.com/52437/62949919-615b9e00-bde7-11e9-95da-97183c2fc82e.png)
