### ISSUE TITLE
My variables conflicts with system variables

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#75025]
I have a variable called `name` and it seems to be duplicated with a const in `lib.dom.d.ts` and this affects some functions in vs code like hovering and going to definition.
See this picture that shows the problem of hovering

![er](https://user-images.githubusercontent.com/42807112/59069411-52bcac00-88b7-11e9-9abf-38181b92f463.jpeg)

and this shows the problem of going to definition when I press `F12` It goes to this file

![err](https://user-images.githubusercontent.com/42807112/59069457-741d9800-88b7-11e9-8916-ab95839e95c2.jpeg)

I started a previous issue and it was transferred to `typescript`. This is the issue https://github.com/microsoft/TypeScript/issues/31783

According to what was said in this issue, It isn't a `typescript` issue. It works well in webstorm. So, I opened another issue here again to see what's the problem.

**Comment by egamma** [comment]
This is a problem in your code, you cannot redeclare this globally declared variable. I suggest to enable //@ts-check, see below

![image](https://user-images.githubusercontent.com/172399/59092932-00a97400-8913-11e9-9a3c-e3c2d357e46b.png)

**Comment by minkir014** [comment]
@egamma This works in webstorm and the compiler understands that and mange it well. And what's the problem with typescript? I am not using typescript. I am using javascript only.

**Comment by minkir014** [comment]
@egamma  please respond as fast as you can.
