### ISSUE TITLE
When Auto Reveal is off, I can no longer use Ctrl+0 to quickly reveal the file in explorer

### ISSUE THREAD

**Issue by nickj41** [microsoft/vscode#75032]
Issue Type: <b>Bug</b>

1) Turn off the Explorer: Auto Reveal setting
2) Open file that exists in the workspace
3) Scroll the workspace so that the file is out of view in the explorer
3) Try to use Ctrl+0 shortcut to quickly scroll the explorer back to the file

I don't like using the auto-reveal feature, but I do want to still be able to use a keyboard shortcut to quickly scroll the explorer to the current file.  I would expect that auto-reveal being off would not prevent me from using the keyboard shortcut as needed

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|2.9.0
todo-tree|Gru|0.0.134
debugger-for-chrome|msj|4.11.3
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This is designed behavior. Just use Reveal ACtive file in Sidebar.
You can also bind ctrl + 0 to trigger Reveal Active file in Sidebar which will get you the desired behavior
