### ISSUE TITLE
Terminal true colors not working

### ISSUE THREAD

**Issue by ncarandini** [microsoft/vscode#75034]
Issue Type: <b>Bug</b>

1. Create a true-color-test.sh file with the code found in the answer of this [Unix and Linux Stackexchange question](https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern).
2. Execute it on the WSL terminal

### Actual result
Colors aren't true (24bit)

### Expected result
A gradient color scale in true colors as the one showed in the release notes.

### Note
I've also tested it within the Ubuntu WSL windows and the result is fine.

![image](https://user-images.githubusercontent.com/139274/59073220-75a28c80-88c6-11e9-9bad-5b68d39db4ad.png)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.46GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/ncara/OneDrive/Desktop/FullColors|
|Screen Reader|no|
|VM|0%|
</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vscode-wasm|dts|1.2.1
vscode-peacock|joh|2.2.3
chat|kar|0.15.4
vsls-pomodoro|los|0.1.0
vsls-whiteboard|los|0.0.8
azure-pipelines|ms-|1.152.0
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.337
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.3.2
team|ms-|1.149.2
sass-indented|rob|1.5.1
rust|rus|0.6.1
vscode-hexdump|sle|1.7.2
shell-launcher|Tyr|0.3.0

</details>

**Comment by Tyriar** [comment]
@ncarandini did you run wsl inside of cmd as that may not work? If so could you try switch your default shell (via the dropdown) and create a new terminal to check?

**Comment by Tyriar** [comment]
Oh actually you're on Windows 1809, you need to wait for Windows 1903 which will have conpty enabled by default which supports true color.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
