### ISSUE TITLE
Markdown: Webview: Cannot load resource outside of protocol root

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#75039]
VSCode 1.35.0

1. File: New Untitled File
2. `![avatar](/Users/xx/Documents/1.png)`
3. Change Language Mode to Markdown
4. Markdown: Open Preview

Webview: Cannot load resource outside of protocol root

**Comment by mjbvz** [comment]
This is done by-design for security reasons. Markdown previews use webviews to render the preview, and webviews should not be able to read arbitrary files on your computer
