### ISSUE TITLE
Search in sidebar in explorer view (Not search view) doesn't return all results

### ISSUE THREAD

**Issue by kiranjulapalli** [microsoft/vscode#75030]
Issue Type: <b>Bug</b>

I have a folder open that has a lot of files and about 15+ csproj files for the csharp projects in the folder hierarchy. When I set focus on side bar and type csproj for search, it doesn't show all results. Here is one of the files it doesn't show in search results: Microsoft.Product.Service.Component.Abstractions.csproj. I changed the names of product service etc.. But that is the pattern of files not found. Not sure if there is any length issue or pattern matching issue

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz (16 x 3696)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
This just search/filters the nodes that have been expanded and loaded into memory. It's not intended to search the whole workspace.
