### ISSUE TITLE
Visual Studio Code Icon 

### ISSUE THREAD

**Issue by exalca** [microsoft/vscode#75047]
Issue Type: <b>Bug</b>

Visual Studio icon is blurred now after latest update

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.16299

**Comment by mjbvz** [comment]
Can you please provide a screenshot of this issue
