### ISSUE TITLE
Can't specify language type of the new created and not saved file.

### ISSUE THREAD

**Issue by igoodwin** [microsoft/vscode#75044]
Issue Type: <b>Feature Request</b>

New file creates without any extension with 'Untiled-1' name. If I want to work with code from the clipboard only and dont't want to save it on the drive it's not so conveniently: it has no language features as highlighting, element navigation etc. It could be nice if you add a feature to customize language without saving file.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

**Comment by egamma** [comment]
You can assign the language type by clicking on the language status bar item, see below

![image](https://user-images.githubusercontent.com/172399/59093219-aa890080-8913-11e9-9216-db39d57fe8f8.png)
