### ISSUE TITLE
Installation of extension only works if home-data-dir already exists

### ISSUE THREAD

**Issue by Cyber1000** [Microsoft/vscode#7505]
- VSCode Version: 1.2
- OS Version: Ubuntu LTS 14.04

Steps to Reproduce:

1. Don't open vscode (at least don't install an extension via vscode-gui)
2. from console: code --install-extension eg2.tslint
3. you get an error - no such file or directory: /home/vagrant/.vscode/extensions

Temporary fix for me (I'm using this in vagrant):
mkdir -p /home/vagrant/.vscode/extensions
code --install-extension eg2.tslint

So I do a mkdir beforehand, so the install won't fail.

Thanks!

**Comment by joaomoreno** [comment]
Great catch!

**Comment by Cyber1000** [comment]
Just rerun my vagrant configuration from scratch and found out that /home/vagrant/.config/Code/User is missing too, if you never started vscode before.

**Comment by joaomoreno** [comment]
Verification: install an extension from the command line, into an extensions folder that does not exist yet, eg `--extensionHomePath ~/extensions --install-extension tinkertrain.theme-panda`.
