### ISSUE TITLE
#70772 is not fixed

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#75050]
@isidorn , #70772 is not fixed as of version 1.35.0. I would have commented on that issue directly, but I'm locked out. Feel free to delete this issue.

**Comment by egamma** [comment]
reopening #70772 and closing this one.

**Comment by devuxer** [comment]
@isidorn , Still unable to comment on #70772, but I just tried the insider's build you linked to, and it's still not fixed. The stop button does show the connect icon, but I don't get the menu that allows switching between debug processes unless I undock and re-dock the debug controls.

**Comment by isidorn** [comment]
There is no insiders build with my fix, I appologies. Please try it out again from Tuesday.

**Comment by devuxer** [comment]
@isidorn 

No worries...I'll try again Tuesday and let you know.

**Comment by devuxer** [comment]
@isidorn , Just downloaded today's insider, and the problem does seem to be fixed! Thanks for your work on this 👍
