### ISSUE TITLE
Find/Replace with regex doesn't work

### ISSUE THREAD

**Issue by LoganFievez** [microsoft/vscode#75058]
- VSCode Version: 1.35.0
- OS Version: window 10

Steps to Reproduce:

1. Use regex to find in all file (ctrl+shift+F by default)
2. `(<)(.|)(split)` to find `split` or `split`
3. Use regex to replace in all file 
4. `${1}${2}as-${3}` to replace into `<as-split` and `</as-split`

Does this issue occur when all extensions are disabled?: **Yes**

It worked in the previous version of vscode

Here is the test of the regex to check if it works : https://regex101.com/r/x64S75/1

Thank you !

**Comment by roblourens** [comment]
You just need to use `$1` not `${1}`. I don't think that format has ever worked.
