### ISSUE TITLE
Toogle simple full screen very slow since electron 4 update

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75054]
macOS

Have the following setting
`"window.nativeFullScreen": false`
F1 > toggle full screen

Wait for 2 seconds -> the screen is full screen.
I can repro 100% of time.

Can not repro with stable, so I think electron 4 is to blame.

![slowFullScreen](https://user-images.githubusercontent.com/1926584/59091155-01400b80-890f-11e9-9e0c-dc864af9df0a.gif)

**Comment by bpasero** [comment]
@deepak1556 this looks awfully similar to the native tabs issue, can you check?

**Comment by deepak1556** [comment]
I was able to repo with minimal electron app with 4.x , but it does seem fixed with 5.x and higher. I will try to narrow down the fix

```
const {app, BrowserWindow} = require('electron')

app.on('ready', () => {
  win = new BrowserWindow({
    fullscreenable: false
  })

  win.loadURL('https://google.com')

  win.webContents.on('did-finish-load', () => {
    win.setSimpleFullScreen(true)
  })
})
```

**Comment by bpasero** [comment]
I have pushed a change to disable support for simple fullscreen for now. We can bring it back after Deepaks fix ends up in a release. I also added the setting to the collection of settings keys we track for telemetry.

**Comment by Tsmith18256** [comment]
Is there any other way to enable this functionality in 1.36? I understand the concern that the 2 second delay is an issue, but if I only toggle into fullscreen once at the start of the day, I don't mind waiting 2 seconds and would rather that than lose the option to do it altogether.

**Comment by bpasero** [comment]
When I tested it the delay was easily >5s. I would like to wait for a proper fix.

**Comment by voxpelli** [comment]
@bpasero You mentioned that @deepak1556 had a fix for this? Where can one follow the progress on that fix getting released and possibly implemented here?

**Comment by bpasero** [comment]
With Electron update, this seems to work fine again. I enabled this setting again.

**Comment by isidorn** [comment]
Works gresat with latest electron, thanks a lot.
