### ISSUE TITLE
Insiders - We cannot connect to the Extensions Marketplace

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode#75057]
- Version: 1.36.0-insider (user setup)
- Commit: 7a5bca9fafbbb23de289179be95e9c4832540c02
- Date: 2019-06-06T10:06:28.360Z
- Electron: 4.2.3
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Visual Studio Code - Insiders
2. Open extensions bar

Can't connect to the extensions marketplace but only in vscode insiders

![image](https://user-images.githubusercontent.com/30405149/59092433-6c86df00-8909-11e9-952b-a68673dd19c6.png)

**Comment by scrossan-crown** [comment]
It's not covered by the above issue

**Comment by WSLUser** [comment]
Doesn't repro for me, I uninstalled an extension, searched the marketplace and re-enabled it just fine. Using same VSCode version on Windows. I'd check your network connections. A proxy or something else may be getting in the way or may be bug when using proxies since I do not use one for updating.

**Comment by scrossan-crown** [comment]
I would agree with that but the stable version of vscode is connecting just fine

![image](https://user-images.githubusercontent.com/30405149/59105546-0fe8eb80-892c-11e9-9e78-92395e9cece2.png)

**Comment by guidoffm** [comment]
I have the same problem here. I get the message: "Cannot read property 'local' of undefined."

For getting started with the WSL extension I had to add the https_proxy variable to the file wslDownload.sh.

**Comment by sandy081** [comment]
@scrossan-crown Do you see any errors in the developer tools? Also please check the logs in the output panel in the bottom and see if there are any errors?

**Comment by scrossan-crown** [comment]
@sandy081 I'm not having the issue any more.

**Comment by sandy081** [comment]
Ok closing this.
