### ISSUE TITLE
light bulb icon is too hollow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#75067]
At first sight this looked like screen cheese, not like help

<img width="75" alt="Screenshot 2019-06-07 at 12 37 56" src="https://user-images.githubusercontent.com/1794099/59098654-276ea700-8921-11e9-8dae-2fa803bc3188.png">

**Comment by misolori** [comment]
Filled in the top of these so they look better when on top of text:

![image](https://user-images.githubusercontent.com/35271042/59129861-bb8d3e00-8922-11e9-8782-203b782e22e0.png)

![image](https://user-images.githubusercontent.com/35271042/59129904-e5466500-8922-11e9-8f4c-3a9cb1b29f2f.png)

cc @mjbvz
