### ISSUE TITLE
Syntax hilighting / tokenizer extremely slow

### ISSUE THREAD

**Issue by d0ggie** [microsoft/vscode#75069]
Issue Type: <b>Performance Issue</b>

Hi, update to the most recent build, I'm pretty sure this has surfaced within the last week or so.

On certain C/C++ files syntax hilighting becomes extremely slow, rendering VSCode almost unusable. Just opening the file or typing certain characters such as "(" (which likely cause some parsing to take place) takes several seconds.

Quickly run profiling. In this example, all extensions disabled, I typed "(" and nothing else (and it took over 3 seconds) on an existing (header) file (which by itself is just a couple of kilobytes), which is a part of a large project. I suspect size of the project / being referenced by other files plays an important role, as if I copy the file contents, place it elsewhere (so that it's not used by the project) everything works silky smooth.

![profile](https://user-images.githubusercontent.com/31200622/59101085-a4554d00-8930-11e9-96e6-db5db1cb5a15.png)

I could not immediately identify any particular pattern that would trigger this problem.

Edit: If I'd like to type "()", and type it backwards so to speak, i.e. type at first ")" and only after that "(" there's no hesitation. The normal way around as soon as I hit "(" everything stops for a quite long while. Perhaps this is related to brace / scope matching on some level? Also brackets "{}" behave like this, too.

VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.17763

**Comment by egamma** [comment]
@d0ggie can you please include the list of extensions you have installed?

**Comment by jeff-hykin** [comment]
@d0ggie  I manage the upstream of the C/C++ syntax. I couldn't reproduce immediately, although I may need to install a fresh version of VS Code.

If you install the [Better Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) Extension it will give you latest of the C/C++ Syntax. If its still an issue even with the extension, let me know and I'll figure out what's going on.

**Comment by d0ggie** [comment]
@egamma Ok, I think I was able to narrow it down to:

```c
#define a a                                                                    \
````

If feeling lazy, just copy paste that line to any file that has C/C++ syntax enabled.

The trailing escape is not important (just to make sure spaces are not trimmed off). What triggers the problem is that the define has many spaces after the first "regular" character, doesn't even have to be trailing spaces. (I played with this for a while, and is not simply the sole number of embedded spaces that count, and certain patterns, that one might usually expect, make the problem go away.) Simply start typing `#define a a' (also, the macro name / content does not matter, so it's not a funny recursion problem, at least in that sense) and carefully begin typing spaces, I presume one does not easily hit an 80-column mark. I tried a fresh install on an another machine (I also did at the very first thing to disable all extensions, as mentioned in my first message) and it did this, too.

@jeff-hykin Better Syntax shares this same problem.

**Comment by jeff-hykin** [comment]
@d0ggie Thanks thats a perfect amount of information, and this is actually a serious problem. I'm going to dive into it tomorrow and hopefully have a solution by the end of tomorrow. I've created an issue to track it [here](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/235)

**Comment by alexr00** [comment]
@jeff-hykin thank you for jumping on this so quickly! I've pulled in your changes.
