### ISSUE TITLE
Creating shortcuts to open workspaces

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#75064]
When working on multiple projects, people tend to have multiple workspaces. Opening VSCode opens the last opened workspace. Would it be possible to make a shortcut desktop icon for desired workspaces so that we can open a workspace without having to shift from the previously opened workspace?

**Comment by egamma** [comment]
@infixint943 have you tried File>Open Recent for switching between workspaces? Notice pressing `CTRL` will open the workspace in another window.

On windows you can create an alias yourself for a particular workspace use the `code workspacepath` as the alias command.
