### ISSUE TITLE
Control-Backslash has entirely wrong behaviour

### ISSUE THREAD

**Issue by 4avka** [microsoft/vscode#75074]
https://askubuntu.com/questions/341189/why-does-ctrl-backslash-not-kill-the-process-any-more

As the post above points out, SIGQUIT *can* be caught by a program, which is fine, for this reason, it really should not be 'open new terminal pane' by default, especially for developing applications that catch this signal to shut down in the case that Ctrl-C (SIGSTOP) is being caught and incorrectly handled (a common issue for Go developers working with concurrency, where I find this a very irritating default).

On linux, there isn't anything resembling a standard key for splitting a multi-pane terminal in this way, but it certainly would not be Ctrl-\ especially not in a development environment.

I'm not really sure if this should be a 'feature request' since actually I am requesting a default key simply be removed as it conflicts with a standard (years old) key combination to send SIGQUIT to a unix application.

**Comment by ahmed-masud** [comment]
If you HAVE to have a default perhaps it should be something close to what others are used. I suggest the intuitive choices like:

 `Ctrl-|` for vertical split and `Ctrl--` for horizontal split (as used by tmux and other terminals)

**Comment by Tyriar** [comment]
I've been thinking about this lately as I rarely use SIGQUIT but tried to and realized that the split keybinding conflicts with it. I think we should probably switch the default, it's just a shame that we can't match the editor split keybinding.

In the meantime you can remove the default keybinding which should make it work by adding this:

```json
{
  "key": "ctrl+\\",
  "command": "-workbench.action.terminal.split",
  "when": "terminalFocus" 
}
```

**Comment by alexr00** [comment]
Just out of curiosity: why ctrl+shift+5?

**Comment by Tyriar** [comment]
The `%` char looks like it's splitting, I believe I saw this used in some Linux terminals
