### ISSUE TITLE
VS Code Causing BSOD (VIDEO_TDR_FAILURE)

### ISSUE THREAD

**Issue by GalihFajar** [microsoft/vscode#75075]
I recently working with VS Code to work on Javascript. My problem is, whenever i try to switch between programs while vs code window still open, there's a chance that the screen will blink several times, and may trigger a blue screen. Is there any way to fix this?
Thank You.

**Comment by egamma** [comment]
What platform are you running on?
Please illustrate your issue in more detail.

**Comment by GalihFajar** [comment]
> What platform are you running on?
> Please illustrate your issue in more detail.

I am running on windows 10, by a dell laptop with some decent specs (an i7 with gtx 850m if that matters).
When I try to code Javascript, it is very common to switch the window to browser
When I did that, the screen is flickering for few seconds and have a chance to trigger BSOD with the same error code. Some say it has to do with extensions, which I have bunch of extensions put on it (mostly themes). Do I have to uninstall them?

**Comment by GalihFajar** [comment]
Turns out there are some extensions related to JS that was causing blue screen.
