### ISSUE TITLE
[API] Terminal.name returns empty string after calling createTerminal()

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#75071]
- VSCode Version: 1.35
- OS Version: Windows

Steps to Reproduce:

1. calling createTerminal()
2. check the value of Terminal.name is empty string **(which is not expected)**
3. wait for some time, the value of Terminal.name becomes normal

Related to https://github.com/microsoft/vscode/issues/74233#issuecomment-497527337, as we could not use `terminal.integrated.shell.<platform>`. However, we could not use `Terminal.name`.

This issue has affect the Code Runner and Maven extension:

- https://github.com/formulahendry/vscode-code-runner/issues/491
- https://github.com/formulahendry/vscode-code-runner/issues/492
- https://github.com/microsoft/vscode/issues/75007

**Comment by Tyriar** [comment]
This is as designed since `createTerminal` is synchronous but setting of the name only happens once the process has launched (async). For now you can workaround this by polling until name is set.
