### ISSUE TITLE
typescript: languages provided by plugins not synced

### ISSUE THREAD

**Issue by kyliau** [microsoft/vscode#75088]
tsserver [plugins](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins) could provide a list of languages so that when a document other than `.js[x]` and `ts[x]` is opened, the plugins would be notified.

Angular language service relies on this to parse `.html` files in Angular templates.

```
  "contributes": {
    "typescriptServerPlugins": [
      {
        "name": "@angular/language-service",
        "enableForWorkspaceTypeScriptVersions": true,
        "languages": [
          "html"
        ]
      }
    ]
  },
```

There seems to be a regression whereby languages provided by tsserver plugins are no longer synced (does not have buffer sync support).

This was brought to light by @andrius-pra in https://github.com/angular/vscode-ng-language-service/issues/338#issuecomment-499364844

For potential fix, please see https://github.com/microsoft/vscode/commit/a5853d6ebe8419a0e0338824cc7ecec0d7efe39e

cc: @mjbvz

**Comment by mjbvz** [comment]
Related https://github.com/microsoft/TypeScript/issues/17151

We only prototyped the support for external languages in TypeScript so this is not really an official API. You'd have to check with the TS team to see if this is still something they are interested in properly supporting as there is other work required beyond this

**Comment by mjbvz** [comment]
I merged a pr that fixes this so you can test it and provide feedback, but you must not ship anything to customers that relies on this API. It is not official and may be changed or be removed at any point in the future

**Comment by kyliau** [comment]
@mjbvz Thanks for the update. I'll test it out locally.
I'd like to organize a meeting to finalize the design with the Typescript team, so that we can move on with the implementation.
