### ISSUE TITLE
[Feature Request] Working on multiple devices or Team

### ISSUE THREAD

**Issue by PinkelNet** [microsoft/vscode#75089]
I've multiple devices and work on them. Also working with an Team (2 or more people) on the same script. The settings/profile and the installed tools and language are not roaming or cannot be exchanged with the Team. Is it possible to do so?

**Comment by egamma** [comment]
VS Code support workspace specific settings that are shared with all the users of the repository
https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings.

To use settings on multiple machines we recommend the settings synch extension https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
