### ISSUE TITLE
Paste in 64bit PowerShell Terminal duplicates text pasted.

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#7508]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Copy text
2. Paste into 64bit powershell terminal.
3. Text that is pasted is duplicated 1-2 times. 

This is what is copied for example.
```powershell
// Place your settings in this file to overwrite default and user settings.
{
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

```powershell
// Place your settings in this file to overwrite default and user settings.
{
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
}// Place your settings in this file to overwrite default and user settings.
{
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
}// Place your settings in this file to overwrite default and user settings.
{
   "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

and the above might be the results. Tested on multiple computers with the latest build

**Comment by Tyriar** [comment]
This seems to be working fine using the new xterm-level copy and paste. The keybinding is currently <kbd>ctrl</kbd>+<kbd>ins</kbd> for copy and <kbd>shift</kbd>+<kbd>ins</kbd> to paste but I plan on making this configurable in https://github.com/Microsoft/vscode/issues/6451 and https://github.com/sourcelair/xterm.js/issues/118
