### ISSUE TITLE
VS Code crash and locks guest VM - running on linux through virtualbox

### ISSUE THREAD

**Issue by davidmcl** [Microsoft/vscode#7509]
- VSCode Version:1.2.0
- OS Version: both linux mint 17.3 and centos 7

I believe this is related to issue #5126. 

This is an issue that I have all the time when, running a linux vm under virtualbox -- since vbox additions 5.0.20 (although I believe on 5.0.18 as well).

While I suspect that it's upstream, I was hoping to find a way to turn off hardware acceleration on VS Code - which is why I was out here looking for a related issue. 

Is there a switch or config option to turn off hardware acceleration for VS Code and that would let Code run? Would this be something that could be added?

For me, on a virtualbox linux vm, both the Chrome browser and VS Code lock completely and only runs correctly when either...
1) I turn off 3D display acceleration for the the whole guest vm in the settings, then both run OK, or...
2) I run virtualbox guest additions 5.0.16 or earlier, then both run OK
3) I can turn off hardware acceleration for the Chrome browser, in Chrome settings, then Chrome browser runs OK, even with the 3D accel on for the rest of the client vm - which is why I was looking for an option to turn it off in VS Code

In all cases, the vbox host is windows 10 pro

Hope that makes sense.

thanks,
David

**Comment by alexandrudima** [comment]
Maybe launching with `--disable-gpu` would help in this case ?

**Comment by davidmcl** [comment]
Perfect.  That did the trick. 

Thanks much,
David

**Comment by aozgaa** [comment]
Reproduced today with the following parameters:

Host: Win10 Pro
Guest: Ubuntu 16.04, with guest additions installed.
Virtualization: VirtualBox 5.1.6.

It sounds like this is an upstream issue, but I would be happy to provide any logs or other information that might help.

**Comment by mdunc** [comment]
This still happens even with --disable-gpu.  The VS Code window appears (no contents at all though;  Only the window frame with the VS Code theme background color filled in) and then the entire VM locks up.  If audio is playing, the same few milliseconds of audio will skip endlessly.
