### ISSUE TITLE
Terminal Ansi True-Color Escapes on Windows 10 Don't Work

### ISSUE THREAD

**Issue by ronklogan** [microsoft/vscode#75096]
Issue Type: <b>Bug</b>

Create a nodejs file:

```
const len = process.stdout.columns;
for (col = 0; col < len; ++col) {
  const r = Math.round(255-(col*255/(len - 1)));
  let g = Math.round((col*510/(len - 1)));
  const b = Math.round((col*255/(len - 1)));
  if (g > 255) g = 510 - g;

  process.stdout.write(`\x1b[48;2;${r};${g};${b}m`);
  process.stdout.write(`\x1b[38;2;${255-r};${255-g};${255-b}m`);
  process.stdout.write(col % 2 ? '/' : '\\');
}
process.stdout.write(`\x1b[m\n`);
```

Run it in a CMD.exe prompt and see the pretty rainbow. Run it in a VS Code Terminal window... and it's just not right. The Release Notes for 1.35.0 say this has been fixed, and I can verify that on my MacBook it looks right; but on my Windows 10 machine this is still broken. 

![win10-cmd](https://user-images.githubusercontent.com/6216389/59129668-29c50700-8909-11e9-9e63-fb39db402cc9.PNG)
![win10-vs-code-term](https://user-images.githubusercontent.com/6216389/59129845-8a544400-8909-11e9-9b0f-361b2e78f701.PNG)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
vscode-raml|blz|3.0.1
xml|Dot|2.5.0
csharp|ms-|1.19.1
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.1.0
iis-express|war|1.1.2

</details>

**Comment by Tyriar** [comment]
You're still on the old "winpty" backend which doesn't support true color, once you update to Windows 10 1903 you should get it.
