### ISSUE TITLE
APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL set to "true" for launch configs

### ISSUE THREAD

**Issue by csuich2** [microsoft/vscode#75097]
- VSCode Version: 1.35
- OS Version: MacOS 10.14.5

Does this issue occur when all extensions are disabled?: Yes

I noticed that my Application Insight auto dependency collection wasn't working with my NodeJS application. I'm fairly confident it was previously working, but didn't appear to be now - although I'm not sure when it stopped.

I noticed that `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL` was set to `"false"` which disables AI's auto dependency collection. There is no where in my code or config setting this, so I tried manually setting it to "false" in my run configuration and behold, it worked.

Searching the VS Code codebase turns up https://github.com/microsoft/vscode/blob/03a9aca859485979f20b9f037587310aced33eab/src/bootstrap.js#L301 where the environment variable is set.

It appears that this environment variable is propagated to processes spawned from launch configs, which is less than desirable and certainly caused me a good deal of confusion.

It would be nice if users didn't have to manually set this environment variable, given that AI's default is for it to be enabled.

**Comment by roblourens** [comment]
@isidorn I think there is a list of VSCODE_ environment variables that get excluded from debug sessions right?

**Comment by chrobles** [comment]
Had a similar issue, running my app in the integrated terminal resulted in console and logger tracking not being collected

**Comment by sbatten** [comment]
talked to @connor4312, we can just reset the variable in js-debug
