### ISSUE TITLE
Expose default shell API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75091]
/cc @DonJayamanne 

## Why?

The reason we need this is because the default for `terminal.integrated.shell.*` became `null` in 1.35 in order to get default shell detection working for remote scenarios.

## Proposal

```ts
export namespace window {
	/**
	 * The detected default shell for the extension host, this is overridden by the
	 * `terminal.integrated.shell` setting for the extension host's platform.
	 */
	export const shell: string;
}
```

The fix I'm proposing is to have an `window.shell` exposed which will return the exact shell that would be launched by opening a terminal, that way extensions can launch terminals like `createTerminal({ shellPath: window.shell })`. I thought about using `env.shell` but that would be away from the rest of the terminal options, plus this value can differ between windows.

## Alternatives considered

As for alternatives, I looked into registering the setting with the default shell on start up, then having the ext host send the correct shells and deregistering/registering the setting again with the new default. This approach has problems though:

- Terminals restored on start up in remote workspaces will launch with the local default, not the remote one.
- Using local Uris as the cwd in the terminal will not use the correct _local_ default shell

## Related issues

- The original discussion https://github.com/microsoft/vscode/issues/74233
- The python issue/workaround https://github.com/microsoft/vscode-python/issues/5743
- vscode-maven discussion https://github.com/microsoft/vscode-maven/issues/337

**Comment by jrieken** [comment]
Maybe better in the `env` namespace?

**Comment by Tyriar** [comment]
@jrieken will make the change 👍 

Reopening since I want to make sure we talk about it in the sync
