### ISSUE TITLE
Return me to the last line of any reverted change

### ISSUE THREAD

**Issue by datocrats-org** [microsoft/vscode#75098]
Step 0. Version 1.35.0 with extensions disabled.
Step 1. Open a file with changes committed in git
Step 2. Use ALT+F3 to navigate to the next change in-line
Step 3. Click Revert Change 
Step 4. find the line number you were on and move your cursor there, then hit ALT+F3 again

I would like vscode to remember where I was whenever I revert a change, then return me to that place, so that I can see the change disappear and so that I can proceed using hotkey to the next change.

**Comment by joaomoreno** [comment]
We might just have to set the cursor in that position, should be simple. Would you like to submit a PR?

**Comment by ankurmittal092** [comment]
@joaomoreno I can take a look at this.. As this will be my first pull request here in vscode repo, I will require some help. 
Do let me know a good starting point for this..

**Comment by Wowol** [comment]
Hi, I would like to work on this issue. I'll submit a PR soon.

**Comment by Wowol** [comment]
@joaomoreno Do we want to fix this for 'stage change' functionality too? It behaves now the same way as 'revert change' - it starts searching from the beginning, instead of placing cursor in staged line position.

**Comment by joaomoreno** [comment]
@Wowol Sounds good.
