### ISSUE TITLE
Option to open file on click filename in source control tab

### ISSUE THREAD

**Issue by cino** [microsoft/vscode#75093]
When clicking on a filename in the source control tab the editor opens a "Working Tree" view in one of the editor groups. While this feature is great I'd much rather use the "Open file" option to easily navigate between the files I've changed.

My suggestion here is to add an option in the settings to replace the actions of these clicks. When this option would be selected, clicking the filename opens the file and the "Open file" button would be replaced with a "Show Working Tree" kinda button.

If this is a feature with the chance of being merged I'd be willing to put in the work for a PR.

**Comment by usernamehw** [comment]
```json
"git.openDiffOnClick": false,
```

**Comment by cino** [comment]
@usernamehw My bad, thanks!
