### ISSUE TITLE
Allow to save with UTF-8 + BOM encoding

### ISSUE THREAD

**Issue by kmpm** [Microsoft/vscode#751]
In version 0.10.2 I am having issues with making sure a file is saved with UTF-8 and BOM character encoding.

Please add such an option.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
I mean :+1: for having such an option, but :-1: for any tool that needs BOMs :)

**Comment by vilic** [comment]
@bpasero LOL, like powershell.

**Comment by bpasero** [comment]
My strong position against BOMs is company agnostic ;)

**Comment by roslanr18** [comment]
.

**Comment by lv7777** [comment]
I want to this feature too
 :+1:

**Comment by iDiver76** [comment]
I really need this encoding type too. Is it planned in a future release?

**Comment by xavierclotet** [comment]
need too :[

**Comment by mgreenegit** [comment]
Having this capability would unblock PowerShell Script Analyzer identifying a Warning for new scripts authored using VSCode.

[Use BOM For Unicode Encoded File](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/Rules/UseBOMForUnicodeEncodedFile.cs)

**Comment by bpasero** [comment]
Pushed a change that allows to set a new setting `files.bom` to one of:
* `preserve` (default): keep any existing UTF-8 BOM, but not add it
* `insert`: always add a UTF-8 BOM
* `remove`: always remove any found UTF-8 BOM

**Comment by vilic** [comment]
:+1:

**Comment by bpasero** [comment]
Discussed with the team and we favor a different approach that does not include a new setting, instead we piggy back on the existing encoding option and add a new option `UTF8 with BOM`. This has several advantages:

* you can easily see if a file has a UTF 8 BOM or not by looking at the status bar encoding info
* you can actually convert a file between UTF 8 and UTF 8 BOM by using the `Save with Encoding` action from the status bar picker

**Comment by xavierclotet** [comment]
Now is better! you have to be able to save with BOM and save with BOM if the file already has it.
