### ISSUE TITLE
Error Running the contributed command when accepting js/ts suggestions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#75106]
Issue Type: <b>Bug</b>

### Repo
1. Open a js file
1. Trigger suggestions and accept
1. Open dev tools console

### Bug
See issue about running the contributed command:

![Screen Shot 2019-06-07 at 6 42 40 PM](https://user-images.githubusercontent.com/12821956/59140545-230fb180-8954-11e9-9f09-1b3a81926182.png)

VS Code version: code-oss-dev 1.36.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 7|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|29%|
</details>

**Comment by mjbvz** [comment]
All js/ts completions register a command so I believe this is related to the lifecycle work. I added some `console.log` in the suggest logic, and from this I believe that we dispose of the `CompletionList` before reaching `executeCommand`. I don't understand the code well enough to fix this however

**Comment by mjbvz** [comment]
I believe this was introduced by 6a4467da59c164bc1197d3b8d6354d79a9975120. The bug is in the current insiders too but doesn't seem to be causing too much trouble

**Comment by jrieken** [comment]
Yeah, problem is that inserting a suggestion trigger cancel to be called and that during that dispose is being called. Before running and awaiting the command.

**Comment by jrieken** [comment]
A bit tacky but for now the suggest model isn't dispose until the next request is made (or until the suggest model/controller is being disposed). This will work but there is some debt which still needs to be removed...
