### ISSUE TITLE
Find & Replace All Incorrectly Replacing Lines

### ISSUE THREAD

**Issue by ryangreenhill** [microsoft/vscode#75101]
Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Extensions: ESLint 1.9.0

Steps to Reproduce:

Unfortunately, this is somewhat intermittent, I've had it happen a handful of times, but I cannot reproduce.

1. Find & Replace using the find sidebar, and clicking the replace all icon across a relatively large number of instances across a large number of files. This instance was triggered off of 273 results in 23 files.
2. Some, but not all F&R's also replace the next line down, regardless of whether it is a match or not. Instances of the error are confined to a single file.
2a. Incorrect replacement did not occur on lines below that were if statements.

![vscode](https://user-images.githubusercontent.com/26419814/59129966-0d35c880-8923-11e9-8af1-92e3211a3a43.png)

**Comment by ryangreenhill** [comment]
![image](https://user-images.githubusercontent.com/26419814/59393279-be779c80-8d2f-11e9-84d7-5d201f3ce817.png)

Additional Information: Find appears to be finding the same line multiple times, which best guess is what's triggering the double replacement effect. Still can't get it to reproduce.

**Comment by rebornix** [comment]
Turns out to be a search issue.

**Comment by roblourens** [comment]
Next time you see it, could you check whether it reproduces with the same search multiple times in a row?

Is it possible that your files have some CR-only newlines?

**Comment by ryangreenhill** [comment]
A \r(?!\n) search turned up nothing, so I'm fairly confident it's not CR-only.

I don't remember if searching the exact same term again triggered the same result, but I do know that changing the search term and going back to the original search term after encountering it returns correct search results instead of the improper ones.

**Comment by ryangreenhill** [comment]
Finally had a re-occurrence. This was in version 1.38.0

Did a search that returned 48 matches and hit the replace all button.
Error occurred in a file I had open in the editor, replacing the next line down.
Immediately saw and discarded all changes through git.
Performed same search again, and only received 47 matches, did not happen again when replace-all clicked.

**Comment by roblourens** [comment]
Any idea @sandy081?

**Comment by sandy081** [comment]
@ryangreenhill 

> Find appears to be finding the same line multiple times

Is it the case again?

**Comment by ryangreenhill** [comment]
@sandy081 

Yes, It found 2 items in a file with only 1 actual item.

**Comment by roblourens** [comment]
When you see the same result twice in the editor, could you try 
- Right click on the results
- Copy all

just to see if there's any discrepency or useful info in seeing the actual lines and columns that it thinks it has.
