### ISSUE TITLE
some bug with creating file

### ISSUE THREAD

**Issue by gordonwalkedby** [microsoft/vscode#75104]
Issue Type: <b>Bug</b>

as this GIF: 
![](https://s2.ax1x.com/2019/06/08/VBV5jI.gif)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8300 Eight-Core Processor            (8 x 3322)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
glua|aci|0.1.7
beautify|Hoo|1.5.0
reg|ion|0.0.2
code-settings-sync|Sha|3.2.9
vscode-lua|tri|0.12.4
markdown-all-in-one|yzh|2.3.1

</details>

**Comment by jeanp413** [comment]
@gordonwalkedby I think this is the same as  #75038.

**Comment by egamma** [comment]
@gordonwalkedby can you confirm that this is the same as #75038 (thanks @jeanp413).
