### ISSUE TITLE
"Unexpected resource git:" when using workspace symbol search in left side of git split diff editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#75107]
Issue Type: <b>Bug</b>

### Repo
1. In a git repo
1. Make a change in a js or ts file
1. Open a split diff view from the git changes
1. Click into the left editor
1. Trigger workspace symbol search with cmd+t

### Bug
No symbols are found. In the dev tools console, see:

![Screen Shot 2019-06-07 at 7 02 48 PM](https://user-images.githubusercontent.com/12821956/59140780-2c4e4d80-8957-11e9-8700-8e59dd118587.png)

For split diff views, I believe that workspace symbol search should just use the right editor instead

VS Code version: code-oss-dev 1.36.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|29%|
</details>

**Comment by alexandrudima** [comment]
cmd+T is `workbench.action.showAllSymbols`

**Comment by roblourens** [comment]
Why is this on me?
