### ISSUE TITLE
Add git status decorations to icons in sidebar

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#75102]
I like using monochrome icon themes, because otherwise the abundance of colours becomes too distracting.

However, it would be great if the icons could take on the colour of the git decoration of the file.

Observe this difference between VSCode and Atom:

![image](https://user-images.githubusercontent.com/490562/59136605-f7360f80-89d7-11e9-911e-f52b3a428e25.png)

![image](https://user-images.githubusercontent.com/490562/59136615-09b04900-89d8-11e9-820d-d92903e14583.png)

Because the icons are coloured as well, providing a larger area of contrasting colour, it becomes visually much more obvious which files are modified and which aren't. 

Would be great if VSCode could adopt this, or if an icon theme could somehow implement this.

**Comment by jrieken** [comment]
@aeschli Can icons be colors? Only when using an icon font?

**Comment by aeschli** [comment]
@jrieken The color is currently only defined by the file icon theme (when using fonts) or by the image file.

**Comment by tpisto** [comment]
This would be great feature - with .svg icons this should be quite simple addition.

**Comment by Gninoskcaj** [comment]
This would be a great feature.

**Comment by Luxcium** [comment]
> @jrieken The color is currently only defined by the file icon theme (when using fonts) or by the image file. There's currently no mechanism to override it. Not too hard when it's a font (with CSS), tricker when it's an image (mask...).

With CSS when it is a font?  what if it is SVG?  I am curious about the point @tpisto  is bringing if it could be possible or what is the difference with the font vs the SVG?
