### ISSUE TITLE
ctrl+r is causing the window to reload in latest master

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7511]
- VSCode Version: 7d56f33e508930d3727064481a7525344a227f10
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Build vscode
2. Run ./scripts/code.sh
3. Press <kbd>ctrl</kbd>+<kbd>r</kbd>, the window reloads, nothing related in console

I checked keybindings.json and there is nothing bound to <kbd>ctrl</kbd>+<kbd>r</kbd>

**Comment by Tyriar** [comment]
This is blocking me fixing https://github.com/sourcelair/xterm.js/issues/108

**Comment by bpasero** [comment]
We do this when "running out of sources" in https://github.com/Microsoft/vscode/blob/ben/7182/src/vs/workbench/electron-browser/index.html#L88 so that you can always reload even if the workbench fails to come up.

**Comment by Tyriar** [comment]
@bpasero is it possible to test <kbd>ctrl</kbd>+<kbd>r</kbd> in the terminal without it reloading? Do I just need to comment that out in my local workspace?

**Comment by bpasero** [comment]
Yeah if you comment out that line, Ctrl+R should not do anything.

**Comment by Tyriar** [comment]
@bpasero thanks :smiley:
