### ISSUE TITLE
single line comment reconision in CSS

### ISSUE THREAD

**Issue by avinashLearner** [microsoft/vscode#75114]
Issue Type: <b>Feature Request</b>

In CSS  single line comment doesnot changes color as multiline cooment.
i.e. "/*" will turn all the code into green but "//" will not reflect any chang like that.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:18:19.664Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by egamma** [comment]
CSS doesn't support single line comments '//'
