### ISSUE TITLE
Integrated Terminal not working windows 10 1903

### ISSUE THREAD

**Issue by MalikBagwala** [microsoft/vscode#75115]
Issue Type: <b>Bug</b>

i just updated my windows to the may 2019 update ( 1903)
and I can no longer use the integrated terminal

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (2.49GB free)|
|Process Argv|C:\apps\lights-out|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.8.1
prettier-vscode|esb|1.9.0
vscode-highlight|fab|1.3.4
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.8.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
ayu|tea|0.18.0
markdown-all-in-one|yzh|2.3.1

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What happens when you try? Does it still happen on 1.36?

**Comment by MalikBagwala** [comment]
I got it to work after 1.36.  before when i used to open the integrated terminal it would always open externally

**Comment by Tyriar** [comment]
Externally is this one: https://github.com/microsoft/vscode/issues/73790
