### ISSUE TITLE
[quick fix] ⌘. twice to quickly apply the quick fix

### ISSUE THREAD

**Issue by coreh** [microsoft/vscode#7512]
Would be nice if instead of pressing `⌘.` then `Enter` to apply the quick fix, you could just press `⌘.` two times in a row. Then, pressing it again could move the cursor to the next (quick fixable) issue, so you could repeatedly fix everything by just pressing `⌘.` several times in a row.

**Comment by jrieken** [comment]
That's unfortunately not possible because once the native context menu shows the JavaScript event loop is stuck and we don't have a change to listen to key events anymore.

**Comment by coreh** [comment]
Can't we add `⌘.` as a key equivalent/shortcut to the menu item? That way the OS's own context menu event loop will respond to the keystroke?

**Comment by jrieken** [comment]
> Can't we add ⌘. as a key equivalent/shortcut to the menu item? 

Yeah, maybe... Tho, I'd go with cmd+1,2,3,4,... in that case. I also remember that there actually is new electron API that allows use to show a context menu and stay responsive. @bpasero any insight on that?

**Comment by bpasero** [comment]
@jrieken yes there is an option to run context menus async but if we adopt that we loose the [`onHide`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/contextview/electron-browser/contextmenuService.ts#L60) callback which is still being used in many places.

**Comment by justschen** [comment]
With the new code action widget, custom keybindings can be utilized to enter the top selected quickfix immediately.

``` json
[
	{
	  "key": "ctrl+k",
	  "when": "CodeActionMenuVisible",
	  "command": "focusPreviousCodeAction"
	},
	{
	  "key": "ctrl+j",
	  "when": "CodeActionMenuVisible",
	  "command": "focusNextCodeAction"
	},
	{
	  "key": "ctrl+.",
	  "when": "CodeActionMenuVisible",
	  "command": "onEnterSelectCodeAction"
	},
  ]
```

The latter half of this issue, regarding pressing again to move to the next error, is something we can take a look at!

**Comment by coreh** [comment]
🥳 Thanks!! This just made my day
