### ISSUE TITLE
Error in syntax coloring for java when calling methods in array literal

### ISSUE THREAD

**Issue by maxime915** [microsoft/vscode#75121]
(I've tested in the last version of VSCode insiders and the bug is present as well)

- VSCode Version: 1.35.0
- OS Version: 10.14.5

Steps to Reproduce:

1. write a java file and set the language mode to java
2. in any method write a array literal and call a method in the value list (e.g. Object.clone())
2. observe the syntax coloring now gone wild

Here are some exemple of the wrong coloring with the line commented (no bug) and not commented (bug active) :

<img width="687" alt="testBug_inactive" src="https://user-images.githubusercontent.com/13822908/59145504-2606b280-89e5-11e9-9b92-1b0fe3d8e675.png">
<img width="661" alt="testBug_active" src="https://user-images.githubusercontent.com/13822908/59145503-256e1c00-89e5-11e9-933b-2e4f62f8adfb.png">

NB:

* this also works in static methods and in a static initialization block but not in the assignment of a static field at declaration.
* this does not work at the declaration of the field (static or not)
* the issue only impact method declared below the method in which the line is written
* somehow writing it in a static block and right after as the declaration of a field cancels it (see below)

[EDIT: better description and better image]magic cancel : we can see that the static initialization block alter the coloring of the visibility of the next field however the next methods are not altered 
<img width="715" alt="testBug_weird_2" src="https://user-images.githubusercontent.com/13822908/59146647-13927600-89f1-11e9-93dc-fabe684a2d60.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@maxime915 can you provide some copy/pastable code that reproduces the coloring issue you're seeing?

**Comment by maxime915** [comment]
Sure !
```java
public class TestBug {

    static Object[] someTest;

    static {
        // Uncomment this to see the bug
        // someTest = new Object[] {someArgs[0].clone(), someArgs[1].clone()};
    }

    public SomeConstructor(Object[] someArgs) {

        // Uncomment this to see the bug
        // this.someListOfArg = new Object[] {someArgs[0].clone(), someArgs[1].clone()};

        // this does not make any bug
        this.someListOfArg = new Object[] {someArgs[0], someArgs[1]};

        // nor does this one
        this.someListOfArg = new Object[2];
        this.someListOfArg[0] = someArgs[0].clone();
        this.someListOfArg[1] = someArgs[1].clone();
    }

    // uncomment this one to cancel out a previous bug
    // private Object[] someListOfArg= new Object[] {someArgs[0].clone(), someArgs[1].clone()};

    public int lengthOfListOfArg() {
        return this.someListOfArg.length;
    }

    public static void test() {
        // Uncomment this to see the bug (works in static methods)
        // this.someListOfArg = new Object[] {someArgs[0].clone(), someArgs[1].clone()};
    }

    public void test() {
        // Uncomment this to see the bug (works not only in constructor)
        // this.someListOfArg = new Object[] {someArgs[0].clone(), someArgs[1].clone()};
    }

    // some generic methods to see the coloring
    public Object clone() {
        TestBug clone = null;
        try {
            clone = super.clone();
            clone.someListOfArg = (Object[]) this.someListOfArg.clone();
            for (int i = 0; i < someListOfArg.length; i++)
                clone.someListOfArg[i] = (Object) this.someListOfArg[i].clone();
        } catch( CloneNotSupportedException e) {
            e.printStackTrace();
            throw new RuntimeException("unable to clone object of type `TestBug`");
        }
        return clone;
    }

    public boolean equals(Object other) {
        return this == other;
    }
}
```

**Comment by alexr00** [comment]
Moved to the repository with the grammar.
