### ISSUE TITLE
[Feature Request] Option to ignore autoreveal on tab close

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#75120]
## Problem
Suppose `"explorer.autoreveal" feature is enabled. If I close a tab, then the next tab is selected, and the explorer jumps to that file.

This is often confusing and I need to scroll back to where I was.

Think about it: when you're working on some file, you're probably working on a set of related files in that part of the tree. Suddenly the explorer jumps to someplace completely different.

So I disable autoreveal, because it takes me out of "the zone".

## Solution
There should be a new option, e.g. `"explorer.autoReveal.revealOnClose": boolean`.

Behavior:
- Suppose that option is enabled
- Close a tab
- The next tab is selected
- BUT, the explorer doesn't jump to the file - it stays where it is (and I can open some other file from that part of the tree)
- If I click on the tab though, then the explorer will jump to it, as usual

**Comment by isidorn** [comment]
This sounds too specific for me and you are the first user requesting this.
I suggest to simply not use explorer.autoReveal.

Though leaving this open as a feature request for now.
