### ISSUE TITLE
Extension Marketplace not working correctly, when .obsolete is invisible

### ISSUE THREAD

**Issue by SPFabGerman** [microsoft/vscode#75129]
Issue Type: <b>Bug</b>

On Windows 10, VSCode's Extension Manager doesn't show you installed extensions, if the `C:\Users\<USERNAME>\.vscode\extensions\.obsolete` is invisible.
If you search for `@installed` (or similar), it will simply give you an error:
`We cannot connect to the Extension Marketplace at this time, please try again later.`
Also already installed Extensions can be "installed" again. This makes it practically impossible to manage your Extensions.
You can still search for Extensions on the Marketplace, and even search with `@category`, but you are not able to install any extensions. If you try to install an Extension (doesn't matter if it is already installed or not) it gives you the error: `Cannot read property 'local' of undefined`.
As far as I could test, it seems like all Extension are still loaded and function correctly.

This Bug happens even if all Extensions are disabled.

You can fix this bug, if you make the `.obsolete` file visible again and reload the window.

(Little side note: If you ran: `code --list-extensions` on `cmd` it prints: `EPERM: operation not permitted, open 'C:\Users\<USERNAME>\.vscode\extensions\.obsolete'`.
If I make `.obsolete` file visible again, this command works fine again.)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
`.obsolote` file is internal and messing up with it is not a good idea. Wanted to know the reason behind changing this?

**Comment by Mohammed90** [comment]
I think I have something related. I'm not sure what the OP means by `invisible` (hidden?).

The file `.obsolete` became owned by `root` on my system on accident. I opened vscode once as root, and it auto-updated an extension, which subsequently caused the extension's directory (only that particular extension) owned by `root` as well as the `.obsolete` file. From then on, I kept getting the `We cannot connect to the Extension Marketplace at this time, please try again later.` error message. Once I re-owned that file/directory to myself, everything was functional again.

**Comment by sandy081** [comment]
We improved our error messages and now the view should what exactly went wrong. Also the error `Cannot read property 'local' of undefined` while installing the extension got fixed. Please try with our latest insiders or wait for the next stable release to see these changes.
