### ISSUE TITLE
Input() function 

### ISSUE THREAD

**Issue by PseudoLabs-Deemo** [microsoft/vscode#75122]
Issue Type: <b>Bug</b>

Sorry I'm having an issue with the input() function, it seems to be giving me an invalid syntax error, yet the issue is resloved in using raw_input and I'm quite sure I'm using a python 3.6.6 interpreter.

Could you please advise 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.9.0
code-runner|for|0.9.10
theme-monokai-pro-vscode|mon|1.1.13
python|ms-|2019.5.18875
cpptools|ms-|0.23.1

(10 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
You should post Python issues in https://github.com/Microsoft/vscode-python repository.
