### ISSUE TITLE
Some refactors don't work on new javascript files

### ISSUE THREAD

**Issue by adelphes** [microsoft/vscode#75132]
- VSCode Version:1,35
- OS Version: Ubuntu 19.04 x64

Steps to Reproduce:
- Launch a new, empty instance of VSCode
- Create (but don't save) a new file (`Untitled-1`)
- Set the language mode for the file to JavaScript (to enable the Typescript/Javascript language feature extension)
- In the new file, type an arrow function with an unused parameter:
```javascript
a => 3
```

Move cursor over `a` and from the "lightbulb" code actions, pick `remove declaration from 'a'` - it works;
```javascript
() => 3
```
Now pick another code action: `add braces to arrow function` and nothing happens. Developer logs show:
![image](https://user-images.githubusercontent.com/13035517/59148068-93254280-89fb-11e9-8806-21e2823916cf.png)

Save the file (`Untitled-1.js`). Run the same code action again and it works:
```javascript
() => {
	return 3;
}
```

**Comment by adelphes** [comment]
Hi @mjbvz - if you're opting to close an issue marked as a bug, could you include a brief note as to why it's being closed so that I (and others) can understand the reason. - thanks.

**Comment by mjbvz** [comment]
Because it was fixed; see the linked change

And please test in VS in vscode insiders
