### ISSUE TITLE
"Extract to..." in Interactive Playground fails

### ISSUE THREAD

**Issue by Brandon-Gui123** [microsoft/vscode#75137]
Issue Type: <b>Bug</b>

Under the "Refactoring via Extraction" section in the Interactive Playground, clicking on the bulb and then clicking on one of the options does nothing. There are no currently opened folders or windows other than the Interactive Playground.
![visual-studio-code-interactive-playground-bug](https://user-images.githubusercontent.com/34325463/59149004-73653d00-8a42-11e9-85d8-22e9dd52a710.gif)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpfixformat|Leo|0.0.81
csharp|ms-|1.19.1

</details>

**Comment by chrmarti** [comment]
@mjbvz Anything I can do to help fix this?

**Comment by mjbvz** [comment]
I just tested on the latest build from master. We now open a new `.md` file after running the extraction. @chrmarti  Do you have any idea on fixing this? I think it's something in the core editor or playground logic.

**Comment by Brandon-Gui123** [comment]
Just for your information, I noticed that the following error showed up in the inspector (which is accessible via **Help** > **Toggle Developer Tools** > **Console (in the window that opens up)** when I tried to perform any of the options available.

Here's an image of the error in the console:
![image](https://user-images.githubusercontent.com/34325463/59356146-dd3f5880-8d5a-11e9-8432-ce4f9b0a5308.png)

**Comment by chrmarti** [comment]
@mjbvz The rename command appears to trigger the new editor:
![image](https://user-images.githubusercontent.com/9205389/60331949-0cc6a580-9996-11e9-9c6a-ff26723789a0.png)

**Comment by mjbvz** [comment]
We likely can fix this by moving the welcome experience to a notebook

**Comment by chrmarti** [comment]
@mjbvz I agree, that is a direction we should investigate.

**Comment by mjbvz** [comment]
Yes the rename seems to be the issue. @chrmarti I'm just going to disable the rename operation in walkthrough files. I don't think TS is doing anything wrong here but I also don't know that we want to invest in marking the rename command work properly for embedded editors. Notebooks seems like correct wrong term fix
