### ISSUE TITLE
"problem checker" spit out the same problem 500 times 

### ISSUE THREAD

**Issue by Tobor58** [microsoft/vscode#75131]
![Annotation 2019-06-08 093754](https://user-images.githubusercontent.com/31450111/59148066-a28f9600-89d1-11e9-8b44-fd6152935821.png)
Issue Type: <b>Bug</b>

Shift + Alt +  F
Should reformat the the document . I supposed it did but the "problem checker" spit out the same problem 500 times while doing so. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.11GB free)|
|Process Argv|--folder-uri file:///d%3A/KN2/Visual%20Studio%202019/PowerShellARNG|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.5.0

</details>

**Comment by egamma** [comment]
Please report the issue against the PowerShell extension.
