### ISSUE TITLE
Remote Jupyter [Run Cell] throwing 'command 'vscode.previewHtml' not found'

### ISSUE THREAD

**Issue by mainak555** [microsoft/vscode#75133]
- VSCode Version: 1.35.0
- OS Version: win8

Steps to Reproduce:

1. Connect to Remote Jupyter Server using Ctrl+Shift+P
2. Run Cell

Screenshot attached

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/26775546/59148104-e4e0c380-8a21-11e9-897e-2bf6d23a02d2.png)

**Comment by minkir014** [comment]
Have you tried to reinstall the extension?

**Comment by egamma** [comment]
previewHtml command has been deprecated, please report the issue against the corresponding extension.
