### ISSUE TITLE
An API to get a range of visible positions in the editor

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#7513]
It would be useful for extension developers to get a range of visible positions (or lines) in the editor.

This would be useful when the extension is dealing with the visual aspect of the VSCode since the extension does not need to update the visual on invisible area.

For example, [Guides](https://marketplace.visualstudio.com/items?itemName=spywhere.guides) needs to update its indentation guide lines but this has impact the extension performance (https://github.com/spywhere/vscode-guides/issues/6) due to a calculation on whole file which cause the lag on the VSCode. With this API, Guides can now update only visible area, reduce the necessity of update the invisible area which can improve the performance a lot.

**Comment by spywhere** [comment]
Well, seems like it is a dup of #2771, #588

**Comment by sandy081** [comment]
@spywhere Yes they are and thanks for providing the duplicates :).

Duplicates #2771
