### ISSUE TITLE
Long scrollable menus will slowly scroll up without any user action

### ISSUE THREAD

**Issue by Brandon-Gui123** [microsoft/vscode#75134]
Issue Type: <b>Bug</b>

So far, this bug has occurred on the menu that shows up in the "..." button in Source Control.
Not sure if this affects other scroll menus.

This is similar (if not, same) to this issue: https://github.com/microsoft/vscode/issues/66273
It hasn't been solved yet, however.

Here's a GIF showing this:
![visual-studio-code-scrolling-bug](https://user-images.githubusercontent.com/34325463/59148463-e6b78080-8a3b-11e9-8486-2c0eb4168d63.gif)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
@Brandon-Gui123 I currently cannot reproduce this issue on my machine. Can you provide any more detalis that might help get a repro?

E.g. Does it happen on more than one machine? Can you get it to repro on other context menus? Do you have any special scaling enabled? Do you use a special mouse?
