### ISSUE TITLE
[Feature Request]Pressing '.' or space selects the currently selected item from the intellisense dropdown list

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vscode#75143]
If you typed some parts of an expression and pressed `.` , the intellisense would stop and wouldn't complete the half typed expression according to the currently selected item in its list.  
To make it more clear, consider the following image : 
![image](https://user-images.githubusercontent.com/5382892/59028695-6fce8c00-8871-11e9-8b6d-9d1fc399cd82.png)

Here I'm halfway in typing an expression , if I press `.` it will simply write `nn.adap` while it was expected to complete the half-typed item using the currently selected item from the dropdown list! 
Here's another example : 
![image](https://user-images.githubusercontent.com/5382892/59028875-eff4f180-8871-11e9-97d3-bcac8d6b89df.png)

Pressing `.` on this should choose the currently selected item from the dropdown list, i.e. `Conv2d`.
Currently pressing the `Tab` button does this, but it would also be better to have this using `.` or `space` just like `Visual Studio`. It feels more natural. at the very least adding options that would let the end user configure these himself would be appreciated.

**Comment by egamma** [comment]
It is up to the language extension what the completion characters. For example, JavaScript/TypeScript is configured to do exactly what you are asking for. You need to report the issue against the language extension that doesn't support this behaviour.
