### ISSUE TITLE
Auto-import doesn't work with CMD+. (Quick Fix) but works with suggestions

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#75144]
- VSCode Version: 1.35.0
- OS Version: macOS

> Auto-import doesn't work with CMD+. (Quick Fix) but works with suggestions

It's really weird because if I use Quick Fix it doesn't show auto-import suggestion, but if I trigger suggestions (control + space) it shows me the auto-import suggestion.

### JavaScript file

<img width="337" alt="Screen Shot 2019-06-08 at 23 14 17" src="https://user-images.githubusercontent.com/10441177/59151876-351c4d80-8a43-11e9-96d3-29fd7814d5d3.png">
<img width="562" alt="Screen Shot 2019-06-08 at 23 14 28" src="https://user-images.githubusercontent.com/10441177/59151877-351c4d80-8a43-11e9-87b6-9dbd005d965c.png">

### TypeScript file

<img width="364" alt="Screen Shot 2019-06-08 at 23 16 27" src="https://user-images.githubusercontent.com/10441177/59151902-7876bc00-8a43-11e9-9e44-b2a6b5467f25.png">
<img width="548" alt="Screen Shot 2019-06-08 at 23 16 35" src="https://user-images.githubusercontent.com/10441177/59151903-7876bc00-8a43-11e9-81d7-791d64845c4d.png">

As you can see both works correctly with suggestions (trigger them with control + space), but if it's Quick Fix (cmd + .) behavior is different.

_Problem was with older version too (1.34.0)_

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates this

**Comment by svipas** [comment]
@mjbvz 

1. `git clone https://github.com/svipas/personal-website/`
2. Open `./src/App.jsx`
3. Remove this line `import { howOldAmI } from './utils';`
4. Test the behavior with Quick Fix and suggestions.

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json`:

![Screen Shot 2019-06-10 at 11 52 30 AM](https://user-images.githubusercontent.com/12821956/59218970-474ad880-8b76-11e9-937c-61565d231bc5.png)
![Screen Shot 2019-06-10 at 11 52 21 AM](https://user-images.githubusercontent.com/12821956/59218971-474ad880-8b76-11e9-84c1-eda1a05211e3.png)

After creating one, everything works for me on VS Code insiders

**Comment by svipas** [comment]
@mjbvz It's necessary to have `jsconfig.json` for JS projects in order to get full support from VS Code? Maybe you can share `jsconfig.json` you used in my repo to solve this? Or it's enough to have an empty one?

**Comment by mjbvz** [comment]
From a js file, run  `javaScript: Go to project configuration` and use the default config it creates. Save the `jsconfig.json` to disk at the root of your workspace and reload VS Code.

Does it work as expected after doing this?

**Comment by svipas** [comment]
@mjbvz No issue still exists... 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2016",
    "jsx": "preserve",
    "experimentalDecorators": true
  },
  "exclude": ["node_modules", "**/node_modules/*"]
}
```

I created with the command you mentioned and it doesn't work... I even tried to customize it a little bit, but no help at all.

**Comment by mjbvz** [comment]
Yes you do also need to enable `checkJs`, either globally or in that file: https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript Otherwise we will not generate an error on unknown symbols so there will be no quick fixes for the errors
