### ISSUE TITLE
Icon: Insufficient contrast on macOS dock

### ISSUE THREAD

**Issue by kbrgl** [microsoft/vscode#75148]
The new VS Code icon shipped in 1.35.0 doesn’t have enough contrast against the dock when macOS is in light mode. It’d be great if the colors could be tweaked to be brighter.

<img width="611" alt="Screen Shot 2019-06-09 at 12 21 20 PM" src="https://user-images.githubusercontent.com/13417496/59155987-cfb37580-8ab1-11e9-8f5d-cc495a85ff4e.png">

<hr>

- VSCode Version: 1.35.0
- OS Version: macOS Mojave 10.14.4

Steps to Reproduce:

1. Install and launch VS Code on macOS

Does this issue occur when all extensions are disabled?: Yes

**Comment by sam3d** [comment]
The previous logo conformed really nicely to the [Apple app design guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) and I'm sad to see it go on Mac. I can understand why this chance was made on Windows but I don't believe that the Mac icon should be changed as well.

**Comment by Divni** [comment]
+1. I like the new icon by itself but it really doesn't fit into the macOS Dock. 

![image](https://user-images.githubusercontent.com/34585078/59357456-e8619c80-8cf8-11e9-9216-b94cde46994f.png)

It looks really out of place.

**Comment by t3rminus** [comment]
As a short-term fix, you can drop the old icon into `/Visual Studio Code.app/Contents/Resources` and overwrite the new one: [Code.icns.zip](https://github.com/microsoft/vscode/files/3283514/Code.icns.zip)

But yes, I agree, the new icon is a huge step backwards. It makes me think of Office 2011 icons...

The old icon followed Apple HIG, provided a nice contrast on both light and dark docks, and was appropriately sized with the rest of the dock icon (It didn't "feel" too big).

**Comment by a-x-** [comment]
On my mac and on the mac of my collegue we have en 1px vscode icon 😂 
![Screenshot 2019-06-13 at 19 18 05](https://user-images.githubusercontent.com/6201068/59460547-0679ea80-8e28-11e9-9d64-d8f61e970732.png)

**Comment by misolori** [comment]
Thanks for the feedback! We did try to address this issue by adding a drop shadow and increasing the gradient colors. Due to the logo having transparency vs a solid shape, you may still encounter issues with similar colored backgrounds. With that said, I'm going to close this issue as `as-designed` as we're trying to keep our issue count on a manageable level.
