### ISSUE TITLE
Presence of folder with many (>10,000) files causes freezing

### ISSUE THREAD

**Issue by jeff-hykin** [microsoft/vscode#75145]
## Reproduce
- MacOS High Sierra
- Latest Stable VS Code, all extensions disabled
- Latest Insiders VS Code, all extensions disabled

1. Download this large Kaggle [dataset](https://drive.google.com/file/d/1JjA15jy42W90q5Oi-o4jK9qLklHgZses/view)
2. Unzip it, then unzip the `train1.zip` and `test.zip` 
3. Open the parent folder in VS Code `code ..`
4. Open the integrated terminal and type out half of `ls -l path/to/unzipped/train1 | wc -l`
5. Make sure to use tab completion as you're typing out the path

During the typing (before pressing enter), the UI stutters and CPU spikes 100%.
There are also other stutters related to other actions, but the terminal is the one I can produce easily and consistently.

## Notes
In the side panel Explorer:
toggling `1,000` images is handled effortlessly, and scrolling is smooth
toggling `12,500`  images in has small initial lag (expected) and then goes to being perfectly smooth after the initial opening.

If I do very narrow actions, the editor stays fast, but particular actions like typing out the directory in the terminal will cause the whole app to overwork and stutter. Git (as an alternative to the terminal) is another area that can trigger the massive slowdown.

## Why is this an issue?
I know VS Code's goal is to 'get a cursor blinking, and keep it blinking' in terms of maintaining responsiveness. I think large folders should be an "opt-in" slowdown the same way VS Code makes opening large files an opt-in slowdown.

I don't want to interact with the dataset, I just want to continue editing the code that is stored in sibling folders.

## Suggestions / Possible Solutions
I know this is way tougher to fix than large files, here's solutions I'd be okay with:
- Disabling tab-complete in folders with >1,000 items. 
- Having a timeout for terminal tab-complete suggestions so they don't continue to slow down the rest of the app
- Having a cap on the number of files shown/handled in the source control panel.

**Comment by Tyriar** [comment]
Here's the timeline I see:

<img width="1278" alt="Screen Shot 2019-07-08 at 12 25 55 PM" src="https://user-images.githubusercontent.com/2193314/60836874-90914680-a17b-11e9-8d2a-4511dd97fcc6.png">

The terminalProcess part is blocking on checking process.title which calls into this https://github.com/microsoft/node-pty/blob/32ea3e47791794a82c58c76bf83dc4d441a93108/src/unix/pty.cc#L372-L395

I think that makes sense because bash is too busy to respond, sucks that we block on it though.

Not sure what the sort part after is about but I think there's another issue tracking that already.

**Comment by Teoge** [comment]
I have similar issues. I got a folder containing more than 600k files. And when I typed the path of this folder in the integrated terminal, vscode stops responding, no matter how many times I tried. And I did not use tab-complete and typed the path letter by letter.

**Comment by Tyriar** [comment]
Tracking this in https://github.com/microsoft/node-pty/issues/356
