### ISSUE TITLE
Python Custom Module Importer

### ISSUE THREAD

**Issue by bkazour** [microsoft/vscode#75149]
Issue Type: <b>Bug</b>

When creating Custom python modules and importing them from another python file, the modules works fine. However, making changes to the module and importing them again weren't reflected in the other python file until Kernel has been restarted

Steps to Reproduce:

1. Create Custom Module
2. Import Module to a python file and run the module with no problem
3. Make Changes to the Module
4. Import the module from the python file again and check if changes take effect, which they don't
5. Restart Kernel and import the module again to see the changes taking effect

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.14
xml|Dot|2.5.0
gitlens|eam|9.8.1
php-debug|fel|1.13.0
vscode-solution-explorer|fer|0.3.4
cshtml|fir|0.1.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-mysql|for|0.4.0
auto-using|Fud|0.7.8
wordpress|hri|1.0.1
icon-fonts|idl|2.1.5
csharpextensions|jch|1.3.0
docomment|k--|0.1.7
csharpfixformat|Leo|0.0.81
vscode-html-format|moh|0.0.3
mssql|ms-|1.6.0
python|ms-|2019.5.18875
csharp|ms-|1.19.1
debugger-for-chrome|msj|4.11.3
wordpress-snippet|tun|1.1.5
vscode-icons|vsc|8.7.0
json|Zai|1.0.1
html-css-class-completion|Zig|1.19.0

</details>

**Comment by egamma** [comment]
please report the issue against the python extension.
