### ISSUE TITLE
VS Code extension bug

### ISSUE THREAD

**Issue by Googolplex-C** [microsoft/vscode#75154]
I have some problems with my VSC extension.
After installation, every time I open my VSC, the Extension part just doesn't show anything, except for a scrolling bar on the top of the window.
 
system: Xubuntu 18.04
architecture: amd64
vscode version: 1.35 / 1.33 / 1.31 (I have tried a couple of versions, but the same issue came up)

![image](https://user-images.githubusercontent.com/37791677/59160959-dcb28200-8b0e-11e9-899d-448d7ad159e1.png)

**Comment by SHAGO7932** [comment]
Beathiful

**Comment by sandy081** [comment]
By any change are you behind any proxy setting and if you are able to access Marketplace? Can you please open the dev tools and see if there are any errors?
