### ISSUE TITLE
Editor Smart Zoom

### ISSUE THREAD

**Issue by hl2guide** [microsoft/vscode#75157]
An "Editor Smart Zoom" setting would be useful, such that it would auto-set the editor zoom level based on:

1) the maximum line length (character-based) in a document
2) the width of the current Window

**Comment by egamma** [comment]
@hl2guide can you please specify the desired behaviour in more detail.

**Comment by hl2guide** [comment]
Well say that the zoom level is on a scale of 0 .... 100.

The zoom level would automatically scale to the viewport of the window.
