### ISSUE TITLE
The width of WebviewTextEditorInset is not correct

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#75163]
- VSCode Version: 1.36.0-insider (1.36.0-insider) c089daa858f34631f5f827ff8a0313bf1e2ded6d 2019-06-07T06:03:17.956Z
- OS Version: macOS High Sierra 10.13.6（17G7024）

Steps to Reproduce:

1. Disable the minimap.
2. Execute the following sample code of VS Code extension.
3. The width of `WebviewTextEditorInset` is not correct. It is overlayed by the scroll bar.

Does this issue occur when all extensions are disabled?: Yes

This may be related to #73117.

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    const disposable = vscode.commands.registerCommand('extension.helloWorld', async (args, brgs, crgs) => {
        if (!vscode.window.activeTextEditor) {
            return;
        }

        const inset = vscode.window.createWebviewTextEditorInset(
            vscode.window.activeTextEditor,
            vscode.window.activeTextEditor.selection.with({ end: vscode.window.activeTextEditor.selection.end.translate(30) }),
            // { enableScripts: true, enableCommandUris: true }
        );
        inset.onDidDispose(() => {
            console.log('WEBVIEW disposed...');
        });
        inset.webview.html = `<head><meta></head><body style="background-color: #000;"><body>`;
    });
	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}
```

![2019-06-10 7 34 33](https://user-images.githubusercontent.com/10665499/59165195-11482d00-8b53-11e9-88aa-905c4bc28420.png)

**Comment by jrieken** [comment]
That's the design of the scrollbar, it also overlays the text itself.
