### ISSUE TITLE
Failed install Windows 10 vsc 1.35.0

### ISSUE THREAD

**Issue by larrym** [microsoft/vscode#75166]
Install says it cannot complete installation after offering to update during edit session.

vscode-inno-updater-1560127695.log](https://github.com/microsoft/vscode/files/3270194/vscode-inno-updater-1560127695.log)

Tried to install from download and Explorer target says contents do not exist.

**Comment by ngi32487** [comment]
I have the same problem. The update to 1.35.0 fails and refers to the vscode-inno-updater-log...

**Comment by ngi32487** [comment]
When I retry to install the update, the following error dialog appears:
![error1](https://user-images.githubusercontent.com/39375526/59333047-de8b6980-8cf7-11e9-980f-cf94b686041a.png)

VS Code Version Info:
![vs-code-version](https://user-images.githubusercontent.com/39375526/59333166-109ccb80-8cf8-11e9-9209-554e6af13689.png)

**Comment by ngi32487** [comment]
Finally, after the third try (restart VS Code - update 2nd try failed - restart Windows - update 3rd try failed - install Windows updates - restart Windows again), the update eventually succeeded...

**Comment by joaomoreno** [comment]
@larrym Can you try to fully reinstall VS Code? Maybe use the user setup?

**Comment by larrym** [comment]
I did reinstall from  https://code.visualstudio.com/. But as I said
earlier, the shortcut created on the desktop pointed to '%windir%\Progam
Files' when in fact it was installed at
'c:\users\{username}\AppData\Local\Programs\Microsoft VS Code'. I had to
reset the icon too.
