### ISSUE TITLE
Show Git shortcut inconsistent on Mac

### ISSUE THREAD

**Issue by dotchev** [Microsoft/vscode#7516]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

Show Git command uses Ctrl-Shift while all the other Show commands use Cmd-Shift shortcuts.

* Show Explorer - Cmd-Shift-E
* Show Search - Cmd-Shift-F
* Show Git - **Ctrl**-Shift-G
* Show Debug - Cmd-Shift-D

**Comment by alexandrudima** [comment]
I think cmd+shift+g is used for find/replace to make it consistent with other mac software.

**Comment by joaomoreno** [comment]
@dotchev Unfortunately, @alexandrudima is right, it used to be that... but was taken away for consistency with other OS X applications.

You can always overwrite it in your keybindings file, so I'll close this issue.
