### ISSUE TITLE
Faster saving when on a remote system

### ISSUE THREAD

**Issue by shawnl** [microsoft/vscode#75164]
Vscode is one of the few editors that does IO on another thread, so that it is actually possible to code over ssh

HOWEVER

It is really slow, and I think this is because it is doing atomic renaming and fsync.

And you can't just point me to the ssh extension because WHERE IS THE CODE?

**Comment by egamma** [comment]
I assume you are using the VS Code Remote-SSH extension?
Can you provide more background on your setup?
