### ISSUE TITLE
Change the name of this IDE

### ISSUE THREAD

**Issue by MhAllan** [microsoft/vscode#75168]
🚨 The issue tracker is not for questions 🚨
The name is not helpful in search engine, I want to be able to search for some visual studio "code" problems like visual studio code review, code analysis, code cleanup, code snippet ... whatever has "code", but the search engine sees it as visual studio code! what a bad name for this IDE! I hope it get's a name totally different from visual studio and unique for search engines.

**Comment by roblourens** [comment]
Too late for that :)
