### ISSUE TITLE
[feature request] output view: disable auto scrolling once user scrolled back

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#75173]
Currently the Output view would start to auto-scroll when there're lots of output generated meanwhile the view height is not enough to show all the lines. It's a great feature, but when the new lines come too fast, one might need to scroll back to see what had happened earlier, however currently the output view would keep scrolling whenever there're new lines appear.

### What's Expected:
1. stop auto scrolling when the user scroll back, even if there' new lines added to the Output view.
2. resume auto scrolling once user scroll to the bottom

VSCode version: 1.35.0
OS: macOS 10.14.5

**Comment by egamma** [comment]
Autoscrolling can be controlled using the 'lock' button, pls see the attached screenshot

![image](https://user-images.githubusercontent.com/172399/59188952-26d04d80-8b79-11e9-837d-44f508c8f7d9.png)

**Comment by ryenus** [comment]
Glad to know! though not designed as I expected but it simply works. 

Thank you @egamma! BTW, may I ask if there's any chance that a pull request implementing the proposed behavior could be accepted?
