### ISSUE TITLE
Crashes and closes when moving files or deleting folder

### ISSUE THREAD

**Issue by JulianH99** [microsoft/vscode#75170]
- VSCode Version: 1.35.0
- OS Version: Manjaro 18.0.4 Illyria

Steps to Reproduce:

1. Try to move two files into a folder
2. Try to delete a folder, empty or not

Does this issue occur when all extensions are disabled?: Yes

**Comment by David-Else** [comment]
I just tried both of those things on 1.35.0 and Linux Fedora 29 and can report they work fine. For the moving I did a drag and drop using the explorer.

**Comment by JulianH99** [comment]
> 
> 
> I just tried both of those things on 1.35.0 and Linux Fedora 29 and can report they work fine. For the moving I did a drag and drop using the explorer.

Should I think it's an issue of my operating system¡

**Comment by David-Else** [comment]
@JulianH99 Probably, but @Tyriar is the expert and will find out in due course I imagine. He added it to the Backlog which means it will be looked at in the future.

For development I highly recommend Fedora, here is my setup script if you want to try it out. It installs and sets up VS Code for you along with a lot of cool extras:

https://github.com/David-Else/fedora-ultimate-setup-script

**Comment by JulianH99** [comment]
Tested on ubuntu 18.04 too, and works fine. I'm starting to think my Manjaro is the problem. Gonna give a try to fedora again soon as your advice says @David-Else

**Comment by philoez98** [comment]
I find the same issue using kubuntu 19.04. It only happens when I try to delete a file; when I do that vscode becomes irresponsive. I am using the snap version of vscode.
