### ISSUE TITLE
disable auto-remove of matching bracket

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#75175]
I'd like to disable auto-delete of matching parens or brackets. For example, if `|` represents my cursor, and I have:

```
foo(|)
```

and I press backsapce (or delete on mac), then currently we get:

```
foo|
```

but I'd like for it to do

```
foo|)
```

It keeps annoying me, and wasting my time. I'd like to turn it off, but either the option doesn't exist, or I can't find it.

**Comment by egamma** [comment]
Have you tried the set the setting `editor.autoClosingBrackets` to `never`?

**Comment by trusktr** [comment]
@egamma Yes, I have that setting set to `never`. It does prevent auto-closing brackets (just as the name suggests). But it does not prevent auto-deleting brackets.

So, with that setting on, typing `(` results in `()`. With the setting as `never`, typing `(` results in `(`. However, it has no effect on the OP, so pressing delete while the cursor is in `(|)` still deletes both brackets.

**Comment by trusktr** [comment]
![Kapture 2019-07-07 at 21 41 15](https://user-images.githubusercontent.com/297678/60783576-196a9c80-a100-11e9-86e3-6d3991acd99d.gif)
