### ISSUE TITLE
Artifacts in editor background on macOS

### ISSUE THREAD

**Issue by atomiks** [microsoft/vscode#75171]
- VSCode Version: 1.35.0 **(It started in 1.31.0)**
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. Change the current theme's `editor.background` to `#212337`
2. Notice artifacts in the background

See right side of the editor background in this screenshot (not sidebar, to the left of the sidebar the colors are darker compared to the background color behind the code).

![image](https://user-images.githubusercontent.com/20030075/58768751-4ca49380-8576-11e9-99b3-1c1638a4ed62.png)

I mentioned this already here https://github.com/microsoft/vscode/issues/68001#issuecomment-461318004

But I stayed on 1.30.2 and forgot about it. Now I've updated to the latest version and it's still not fixed. However, I'm pretty sure the Electron 4.x upgrade next month fixes this from what I tested. It's just really weird how only colors right around the HSL values of this specific background color causes the artifacts...

> Okay so weirdly enough, only colors right around the editor.background color I chose for this theme causes the artifact problem. If you change any theme's background color to this theme's exact background color, the problem occurs.

> For now, you can change editor.background to a different color. e.g. Palenight's "editor.background": "#292D3E"

> If I try to just move the color picker a few pixels from this theme's current background color, it's not enough to fix it. It's like a whole vicinity of colors around it that is buggy.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by atomiks** [comment]
Yes it's fixed, I'm guessing it has something to do with the color profile.

Is that release version out stable in early July? My color theme has this artifact problem and it can't be fixed for the current versions :s

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
