### ISSUE TITLE
remote development doesn't work well for virtual environment python interpreter

### ISSUE THREAD

**Issue by messi-yang** [microsoft/vscode#75172]
- VSCode Version: 1.35.0
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. attaching running container with vs code, activate python virtual interpreter and choose python path for the interpreter. 
2. But python language service doesn't work well for code hover hint and go to definition.
3. all default python interpreters work well(python2.7 and python3.5), but virtual environment doesn't.
just show "Code analysis is in progress..." all the time and can't finished.

Does this issue occur when all extensions are disabled?: Yes/No
Just keep three extensions, python, gitlens and visual studio intelliCode, all installed in container.

**Comment by egamma** [comment]
Please report the issue against the python extension.

**Comment by messi-yang** [comment]
python extension: ms-python.python
installed in docker container.
