### ISSUE TITLE
Add sorting feature in search across files

### ISSUE THREAD

**Issue by shakeabi** [microsoft/vscode#75178]
Feature Request:
It would be really helpful to sort search across files with a sort feature like sort based on date modified etc.,

**Comment by skprabhanjan** [comment]
@roblourens , I just gave this a try but I am not able to find a way .
I am able to get last modified time of the file but the call is async and sort is a sync function which happens sequentially [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/search/browser/searchView.ts#L503) and the sort comparator is [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/search/common/searchModel.ts#L602).
Can you please help me here ?

**Comment by roblourens** [comment]
Hey @skprabhanjan thanks for looking at this but I think this feature would take some careful UX thinking which I don't really want to do right now.
