### ISSUE TITLE
Allow quickpick to be dismissed via mouse

### ISSUE THREAD

**Issue by josephshin93** [microsoft/vscode#75174]
- VSCode Version: 1.35.0
- OS Version: OS X Yosemite (Version 10.10.5)

Steps to Reproduce:
1. Open up Visual Studio Code and open up a folder that has been initialized to be a Git repository.
2. Click on the branch checkout button at the very bottom left of the window
![vscode-checkout-btn ](https://user-images.githubusercontent.com/15806388/59172436-e8ee0d80-8b15-11e9-9ab1-ea306d11257c.png)
3. A dropdown list of branches will appear, you cannot click on any other part of the application to try to close the dropdown list. It can only be closed by hitting the esc key.
![vscode-branch-list](https://user-images.githubusercontent.com/15806388/59172441-eb506780-8b15-11e9-8dc2-954f6f882fcd.png)
If I remember correctly, I encountered this issue with the command palate dropdown as well with a previous version of Visual Studio Code. It has been fixed and I can exit the command palate dropdown now by clicking away from the dropdown. I hoped to find an issue report for the past issue as it could be helper for the developers,  unfortunately, I could not find an issue report on this topic.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
This appears to be an intentional change of behaviour that arrived in April. See #71355

**Comment by egamma** [comment]
// fyi @misolori another request for a close box

**Comment by AlexSZYDLO** [comment]
Can there be an option to disable this? I find very annoying that I have to press esc to close it...

**Comment by misolori** [comment]
This issue should account for all quickpick widgets (branch picker, recents, etc.) to be consistent. One idea is to add a dismiss button (x), but will need to be discussed with the team.

**Comment by misolori** [comment]
The original issue (branch picker not closing when clicking outside of the picker) is now fixed, see https://github.com/microsoft/vscode/issues/82797 for details. Will be closing this one as a duplicate.

**Comment by gjsjohnmurray** [comment]
I think there's still a good case for adding a "dismiss" button to quickpicks.
