### ISSUE TITLE
Add ability to open files with the OS's default application

### ISSUE THREAD

**Issue by nabeelomer** [microsoft/vscode#75188]
A context menu option can be added to the file browser that allows files to be opened in the default application for that file type. For example if the file is a PDF document, opening the context menu and click "Open with desktop" will open the file with the default PDF reader.

This can be accomplished with the [openItem() method from Electron's shell module](https://github.com/electron/electron/blob/v0.36.10/docs/api/shell.md#shellopenitemfullpath).

I am aware that this particular feature has been suggested before in #50383 and #45989 but my suggestion is not the same as that.

**Comment by egamma** [comment]
For now you can reveal the program in the finder/desktop and open the file from there.

**Comment by nabeelomer** [comment]
Yes but that's very cumbersome, it would be much easier if it can be done directly from VS code.

**Comment by hugonasciutti** [comment]
I also wanted this feature, I found an extension that does that, [Open - sandcastle.vscode-open](https://marketplace.visualstudio.com/items?itemName=sandcastle.vscode-open), [repository](https://github.com/sandcastle/vscode-open). But it would be great to have natively.

**Comment by hugonasciutti** [comment]
I just wanted to open an HTML file but always have to open the folder to open with the default application.

**Comment by PapsOu** [comment]
Is this feature is planned ? It is really annoying to open the folder and open the desired file. All the extensions in the VSCode marketplace does not work under Linux
