### ISSUE TITLE
选择编码功能不能用了

### ISSUE THREAD

**Issue by LaughingLUO** [microsoft/vscode#75189]
更新到最新版的vs code1.35后，新建一个文件，未保存之前，直接点右下角UTF-8不能选择其他编码

**Comment by zwuis** [comment]
@egamma translation:
title: **Feature "select encoding" is useless**
Update VS Code to version 1.35. Create a new file. Modify it and not save it. Click `UTF-8` in bottom right corner. It's unable to choose another encoding.
