### ISSUE TITLE
I want to turn off the template literal highlight

### ISSUE THREAD

**Issue by Imputes** [microsoft/vscode#75180]
![image](https://user-images.githubusercontent.com/12896162/59178154-c51bdd80-8b90-11e9-9a56-4367cd4ba906.png)
As you can see, I don't want the `${` and `}` characters to be highlighted in red. I like them to be white like normal characters.

**Comment by msftrncs** [comment]
This is a feature of the theme you are using.   What theme are you using? (it looks custom)  Place the cursor at the `$` and then press F1 (or ctrl-shift-p).  Look for/select the command 'Developer: Inspect TM Scopes', and then report the scope that is being applied to by the theme.

**Comment by Imputes** [comment]
> This is a feature of the theme you are using. What theme are you using? (it looks custom) Place the cursor at the `$` and then press F1 (or ctrl-shift-p). Look for/select the command 'Developer: Inspect TM Scopes', and then report the scope that is being applied to by the theme.

It is Red theme, and I have customized fonts and other colors. I want the color to be white except for the comment, the color of the other text is white, the line number is blue, and the indent guide and space are rendered in green.
According to what you said, I opened the file, but which one should I use?

**Comment by Imputes** [comment]
What I found to be changed is:
"punctuation.definition.template-expression.begin",
"punctuation.definition.template-expression.end",
"punctuation.section.embedded",
".format.placeholder"，
I copied this to setting.json to make changes, and the success became what I wanted.
![image](https://user-images.githubusercontent.com/12896162/59244618-b93f2280-8c47-11e9-96a6-78e1d958ccc3.png)

**Comment by egamma** [comment]
@msftrncs thanks providing the guidance.
