### ISSUE TITLE
Add clickable button to dismiss QuickPick

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#75186]
Clicking outside a QuickPick only dismisses it if ignoreFocusOut hasn't been set true. If it has been set true the user must reach for the keyboard and press Esc.

Consider adding an [X] button on the QuickPick so it can be dismissed using the mouse or touchscreen.

For UX stability I suggest the [X] button always shows, even if ignoreFocusOut is false.

Also do this for the workspace folder pick UI, where ignoreFocusOut is an option too.

Not sure about InputBox. An [X] button could appear ambiguous. Does it clear the content of the field, or dismiss the field entirely?

Suggestion prompted by #75174

**Comment by egamma** [comment]
//fyi @chrmarti

**Comment by misolori** [comment]
Closing this in favor of #75174
