### ISSUE TITLE
Find widget: too much space between result count and up / down arrows

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75187]
I like that we use the up / down arrow in the find widget now as discussed here https://github.com/microsoft/vscode/issues/75056
Since we have now saved on horizontal space it seems to be there is too much empty space between the result cound and the up / down arrows.
I think the arrows could go 2px or 4px to the left. Making the whole widget a bit smaller and nicer

![Screenshot 2019-06-10 at 11 04 45](https://user-images.githubusercontent.com/1926584/59185025-bcff7600-8b6f-11e9-8fb7-6bc7844e8707.png)

**Comment by misolori** [comment]
Not sure I would tweak certain icon elements to make the smaller because right now they're all the same size. I personally like that there is some breathing room and not crammed in 😄

**Comment by isidorn** [comment]
I would not change the icon elements. I would just change the right padding margin for the No Results. Currently it is 1 + 2 = 3px. I think it is too much

![Screenshot 2019-06-11 at 09 43 52](https://user-images.githubusercontent.com/1926584/59253049-b6373880-8c2d-11e9-9c8d-bb3b6edc44f3.png)

**Comment by misolori** [comment]
Ah, I see now. I can update this.
