### ISSUE TITLE
如何从 Explorer 中通过后缀名过滤文件列表？

### ISSUE THREAD

**Issue by mljuw** [microsoft/vscode#75185]
Issue Type: <b>Feature Request</b>

如何从 Explorer 中通过后缀名过滤文件列表？

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
I do not speak chineese. Please open a new issue in english with exact reproducable steps. Thank you

**Comment by mljuw** [comment]
> I do not speak chineese. Please open a new issue in english with exact reproducable steps. Thank you

Thanks Reply :-) ,            How to filter the explorer list by file suffix?

**Comment by isidorn** [comment]
Click on the explorer start typing and type ".txt" and click on the filter button in the widget
You can also set this setting `"workbench.list.keyboardNavigation": "filter"`

![filter](https://user-images.githubusercontent.com/1926584/59187354-92b0b700-8b75-11e9-97db-af08faf558ac.gif)

**Comment by mljuw** [comment]
I have been looking for a long time from the network, but not found.  thank you for your help!

**Comment by isidorn** [comment]
Welcome.
