### ISSUE TITLE
Cannot pin editor

### ISSUE THREAD

**Issue by gheorghina** [microsoft/vscode#75193]
Issue Type: <b>Bug</b>

no matter if I double click on a file, it will always show as preview - this started to happen after the may update

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.55GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.7.0
vscode-postgres|cko|1.1.10
jest-test-language-support|dpl|1.30.2
terraform-autocomplete|erd|0.0.8
vscode-jest-runner|fir|0.3.5
ginfuru-vscode-jekyll-syntax|gin|0.1.0
elixirlinter|iam|0.4.1
elixir-ls|Jak|0.2.25
vscode-elixir|mjm|1.1.0
mssql|ms-|1.6.0
csharp|ms-|1.19.1
vscode-jest|Ort|2.9.2
erlang|pgo|0.5.2
vscode-elixir-formatter|sam|0.2.0
ava|sam|0.6.0
erlang-otp|yuc|0.2.4

</details>

**Comment by egamma** [comment]
Cannot reproduce with 1.35 on OS X. Double clicking a tab pins the editor for me. Please provide more detailed steps. Ideally an animate gif.

**Comment by gheorghina** [comment]
It must have been a weird combination of settings, I reset everything I had, and now it works.
We can close this issue. Thanks!
