### ISSUE TITLE
VSCode source control with Git

### ISSUE THREAD

**Issue by bhaktibhoj** [microsoft/vscode#75191]
Though Developer does changes in single file git showing multiple files in staged changes after Git pull.

- VSCode Version:1.35.0
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Changes in any one of the file 
2. commit the changes.
3. Pull latest changes

Does this issue occur when all extensions are disabled?: Not sure

**Comment by joaomoreno** [comment]
Can you elaborate? Maybe with screenshots?

**Comment by bhaktibhoj** [comment]
I am attaching the screenshot PFA,
![image](https://user-images.githubusercontent.com/46561367/59416984-06f09200-8de4-11e9-8c97-16d7a53fc229.png)

1. User does changes in single file only. 
2. She commit the file and pull the remote changes
3. Files identies a conflicts, And multiple files in the staged section
4. So could you please let us know why multiple files( which are unchanged by her) identifies in staged section?

**Comment by joaomoreno** [comment]
When you pulled, new changes came in which have conflicts with your local changes. The conflicts occur only in certain files, those files will appear in the MERGE CHANGES section. The files which were also modified but not in a conflicting way appear in STAGED CHANGES.

https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
