### ISSUE TITLE
Support file watching on Windows < .NET Framework 4.5

### ISSUE THREAD

**Issue by kiwirob** [Microsoft/vscode#7519]
Hi,

Code recently added a dependency on .NET Framework 4.5 on Windows 7 (I believe to address issue #9). .NET Framework 4.5 is an optional update on Windows 7. However, I am using Code on my work PC and do not have admin rights, so am unable to install this. Code still seems to function largely OK (except for the automatic file update issue related to #9), but I get a repeated warning to install the .NET framework which gets old pretty fast.

Any chance of adding an option to disable this warning for those of us using Code on Windows 7 with no admin rights to update the .NET framework?

Thanks for a great product! 
- VSCode Version: 1.2
- OS Version: Windows 7 32-bit

**Comment by bpasero** [comment]
I think we should rather find a solution to have file watching supported on Windows 7.

**Comment by mjbvz** [comment]
Closing since I'm not sure this issue is still relevant. We've since switched to using [node-sentinel-file-watche](https://github.com/Axosoft/nsfw) 

Please let me know if you are still running into this problem
