### ISSUE TITLE
Minifying feature to expand to cover the html

### ISSUE THREAD

**Issue by Bahaatya** [microsoft/vscode#75194]
Hello, I would like to voice this request to you, to have a file minifier feature, not just for .css or .css files, but to be to the file itself whatever is it, especially to the .php files that include HTML templates.

In the real practices, we write full frameworks from the scratch, this is done almost in PHP (.php files) - and surely can be done in any other language - and the frameworks have html templates, static pages and so on... 

I was searching to find an extension that can minify the file itself, regardless of the extension of the files, and I found HTML-Minifier, but unfortunately it doesn't cover the case when the page includes <script> that's written in ECMA 6, so it minifies the .php files (that includes css styles and htmls) but neglects the javascript parts.

I was thinking if You can make such feature integrated in Visual Code itself, without the need to any external extensions that may or may not work, that would be great feature, and all of programmers will certainly use it, because surely any programmer whatever his skills level is, needs to minify his products to the max, as well as minify/ugify/mangle the javascripts that are written in the same php/html files,

What do you think guys?

Thanks in advance.

**Comment by roblourens** [comment]
Sorry, this feature makes more sense as an extension or external tool, not a core feature in vscode.

**Comment by Bahaatya** [comment]
How come? what if there's no available extension that could do it?!

**Comment by roblourens** [comment]
Because vscode can maintain detailed tools for every language, this is exactly what extensions are for. If it doesn't exist then somebody should make it 😁
