### ISSUE TITLE
Can no longer switch the encoding of an untitled file

### ISSUE THREAD

**Issue by LaughingLUO** [microsoft/vscode#75190]
After updating to the latest version of VS code1.35, create a new file, and before you save it, you cannot select a different encoding UTF-8 the lower-right corner of the direct point

**Comment by egamma** [comment]
Cannot reproduce given the information provided.
Please provide detailed steps with an example file so that we can reproduce your problem.

**Comment by LaughingLUO** [comment]
![image](https://user-images.githubusercontent.com/22276108/59188625-a1659100-8baa-11e9-94de-412420d5ebda.png)
