### ISSUE TITLE
Visual bug type definitio

### ISSUE THREAD

**Issue by pchodak** [microsoft/vscode#75196]
- VSCode Version: 1.34
- OS Version: Windows 10 (17134)

Steps to Reproduce:

1. Focus type definition name
example type test = {}
2. Click ctrl key during focus

Result:
Duplicated preview
![image](https://user-images.githubusercontent.com/12396676/59193971-ba107f80-8b87-11e9-96ba-d28ce5a9b4d4.png)

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by carloslahrssen** [comment]
From what I can tell, it isn't a straight duplication error(You can tell by the fact that the strings aren't exactly duplicates of each other, i.e, missing semicolon in the first part), but more about what VSCode is meant to be doing. The first part of the hover will display the type and the keyword of an expression, while hitting ctrl will expand on the selected keyword. You can see this with the following example, 
```javascript
export interface AzureResponse {
  resourceTypes?: ResourceType;
}
```
Which following your steps, will produce this
![snippet-interface](https://user-images.githubusercontent.com/13179704/59213312-65f6a280-8b69-11e9-8200-563e1395db0e.PNG)

Now what happens with hovering over type is that one shows you the declaration/expression and the other shows you the actual type assignment which for the `type` keyword is in this case all the properties declared are a part of the type itself, if that makes any sense. 

So the first part is what the editor sees when hovering over which in your case was your type declaration, and the second part was Typescript type detection.

That's what I'm gathering from all of this at least, if someone can correct me on anything I said that isn't true please let me know!

**Comment by egamma** [comment]
@carloslahrssen thanks for chiming in, you analysis is correct.
