### ISSUE TITLE
expose trigger character to signature help and completion provider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#752]
Add a `CompletionContext` and `SignatureHelpContext` which contains the character that has triggered that request: `{ ch: string }`

**Comment by jrieken** [comment]
Must not break the API - probe on arguments length

**Comment by jrieken** [comment]
Challenge is to have a nice signature that is backwards compatible. I only see something like this

```
interface CompletionItemProvider {
  providerItem: ((doc, pos, token) => CompletionItem[] | Promise<CompletionItem[]>) | ((doc, pos, context, token) => CompletionItem[] | Promise<CompletionItem[]>)
}
```

which I am not a big fan of

**Comment by jrieken** [comment]
Needs more thinking...

**Comment by jrieken** [comment]
Also, expose if it got triggered because of `24x7` intellisense or manually.

**Comment by joaomoreno** [comment]
Do it and :beer:

**Comment by jrieken** [comment]
parts of this are addressed by #2224

**Comment by jrieken** [comment]
Should be another overload of `provideCompletionItems`, like so 
```ts

interface CompletionContext {
  triggerCharacter: string;
  //...
}

provideCompletionItems(document: TextDocument, position: Position, context: CompletionContext, token: CancellationToken): ProviderResult<CompletionItem[] | CompletionList>;
```

The challenge is that there are already many completion item providers expecting 3 arguments and that we need to check on that before calling, `Function.length` is our friend

**Comment by jrieken** [comment]
We have now context information for completion request. Most people should be happy now. I am creating a new issue for context information when making signature help requests

**Comment by DustinCampbell** [comment]
awesome!

**Comment by jrieken** [comment]
@DustinCampbell Let me know if you are missing something. We have started small, just exposing the trigger character and deciding between two kinds: manual and trigger character

**Comment by DustinCampbell** [comment]
I'll let you know. However, this should make it possible for C# to offer completion in special cases after SPACE. For example:

```C#
List<int> l = new // <-- We trigger a completion list on SPACE here that contains List<int>
```
