### ISSUE TITLE
Is it possible to let previewHTML can really run HTML url?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#7520]
I want to view html project I write in angular on vscode side by side. Are there some way such as embed browser in vscode. Or extend previewHTML.

Also it would be great if we could write html page tobe an editor extension. so we could write editor for json in html form style or using canvas to make 3D editor

**Comment by alexandrudima** [comment]
@Thaina The extension API allows for providing a text document `registerTextDocumentContentProvider` and executing a command to preview that document `vscode.previewHtml`. You can then have in there arbitrary HTML that is previewed inside Code.

Please see https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample or https://github.com/Microsoft/vscode-extension-samples/tree/master/contentprovider-sample

**Comment by jrieken** [comment]
Alex is correct - if you really need to access a http(s) resource, I'd reckon to define an html page that embeds an iframe pointing to the http(s) page

**Comment by Thaina** [comment]
@alexandrudima @jrieken What I have heard is `vscode.previewHtml` is not render animation and execute javascript am I wrong? If so then how can I preview angularjs page which heavily based on js?

**Comment by jrieken** [comment]
> What I have heard is vscode.previewHtml is not render animation and execute javascript am I wrong? 

That isn't true
