### ISSUE TITLE
Filtering file names in Workspace

### ISSUE THREAD

**Issue by nunoperalta** [microsoft/vscode#75207]
Issue Type: <b>Feature Request</b>

I like very much that we can filter files by name, and whether we can choose to still show all files or just the matched files.

However, I find it a bit inconvenient that I must open a random file by clicking on the side bar, to put the focus in there so I can start typing to filter.

It would be better if there was a fixed (always visible) input field on the top of the file list where I can just click there and type. That would seem a better UI/UX for me.

In addition, if there could be another button where we could choose whether we want "Exact Expression" or not (by default, the filter doesn't apply an exact expression, so it usually shows me several irrelevant files, as long as they have all the characters through its filename), it would be very nice.

![image](https://user-images.githubusercontent.com/487079/59209701-dcb09180-8ba3-11e9-875b-251fcdea718c.png)

Thanks!

**Comment by michaeljota** [comment]
If you want to search a know file in your workspace, I would suggest to use Quick Open (`workbench.action.quickOpen` <kbd>ctrl</kbd>+<kbd>e</kbd> in windows by default):

**Comment by nunoperalta** [comment]
@michaeljota - nice tip. I think my suggestions are still valid, and not everyone (including me) are aware of all these shortcuts, or even remember that they exist when we need them :) Thank you very much.

**Comment by nunoperalta** [comment]
> The described behavior is how it is expected to work. If you disagree, please explain what is expected and what is not in more detail.

Well, this was a **Feature Request**, as I said in the first line.

Feature Requests are suggestions for new behaviors, so there's nothing to detail about what's "what is expected and what is not", and doesn't make sense that you close this with reason "as designed"...

If you are not happy with Feature Requests, then you should not allow submissions of those through the VSCode UI  (Help -> Report Issue -> This is a [Feature Request]).
