### ISSUE TITLE
Opening a file (from an extension for Salesforce) marks the file as dirty

### ISSUE THREAD

**Issue by Jay-Beeckman** [microsoft/vscode#75201]
- VSCode Version: 1.36.0-insider
- OS Version: Windows 10 (Insider)

Steps to Reproduce:

1.  Using the Prophet Debugger for SalesForce Commerce Cloud, when you go to Logs and click a log, it opens the "file" and marks it as dirty and requires you to save or cancel when closing the file.  The extension has not been updated recently, and the functionality is working fine in the stable release 1.34.0 of VS Code.  It makes going through log files super tedious.

Does this issue occur when all extensions are disabled?: NA

**Comment by Jay-Beeckman** [comment]
This is not a duplicate that I could find.  Also, the non insider version was updated this morning as well, to 1.35.0 and the log is now broken there as well, so whatever was done was in 1.35.0.  I am going to look through the commits again.

**Comment by egamma** [comment]
To track this down please start by filing an issue against the corresponding extension.

**Comment by Jay-Beeckman** [comment]
@egamma how can you say it's a problem with the extension when the extension works just fine in previous versions of VSC, and has not changed?  I would expect either clear directions about, for example, Open File Methods have been updated to require a new parameter or something, else it's a bug with something that was done here.  Provide link to the ticket that describes the new functionality change, or re-open the bug.
