### ISSUE TITLE
Can't launch VS Code. Check failed: (isolate->snapshot_blob()) == nullptr. 

### ISSUE THREAD

**Issue by BinMan86** [microsoft/vscode#75203]
- VSCode Version: 1.34
- OS Version: Windows 7 Enterprise

Steps to Reproduce:

1. Close Visual Studio Code then try to relaunch it and nothing happens, launching from Command Line gives:

> C:\Users\BMartin>code --verbose
> 
> 
> \#
> \# Fatal error in , line 0
> \# Check failed: (isolate->snapshot_blob()) == nullptr.
> \#
> \#
> \#
> \#FailureMessage Object: 000000000018F3C0

2. Only workaround I've found is to do a reinstall, and select the "Launch Visual Studio Code" option from the installer once it has completed. Even this workaround will only last until VS code is next closed, then I have to reinstall again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
>VSCode Version: 1.34

Please upgrade to the latest version 1.35. Can you still reproduce the problem?

**Comment by BinMan86** [comment]
Have upgraded to 1.35 and the problem still occurs

**Comment by nschneir** [comment]
I'm seeing this same issue with the latest VSCode (1.37). I rolled back to an earlier version and the problem went away.

**Comment by nschneir** [comment]
I'm on Windows 10 Enterprise, 64-bit

**Comment by Lajnold** [comment]
I have the same problem with 1.37.0. Rolling back to 1.36.1 solves it. The nightly insider also works.

**Comment by Lajnold** [comment]
1.37.0 started working now too. I use the portable zip version. I replace my previous installation each time I upgrade, keeping the data/ folder. After some back and forth with 1.36.1, insider, and 1.37.0, it started working. This time, I also started up the unzipped 1.37.0 before moving it to replace the old installation, and without the old data/ folder. It still works after replacing the old installation while keeping the data/ folder. I don't know which step solved it.
