### ISSUE TITLE
Search is not working for huge projects using keyword as _REPLACE_DEVELOPER_DOMAIN_

### ISSUE THREAD

**Issue by galegriaredteadev** [microsoft/vscode#75204]
Issue Type: <b>Bug</b>

Complete results are taking about 10 seconds but there is only 1 result in file... when a file is opened in edit mode the search is finding my keyword on it :(

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|61.03GB (31.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-map-preview|jum|0.4.8
Angular-BeastCode|Mik|8.0.7

</details>

**Comment by roblourens** [comment]
Please see whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results
