### ISSUE TITLE
Expose command to display the test view

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#75219]
Today users of VS Code can display the test view using the command `View: Show Test`, however extensions cannot do the same.

The Python extension would like to display the `Test View` when users have configured the extension to use testing. 
The work flow is simple:
* User opens VSC
* User configures tests (in Python extension)
* Python extension displays test explorer (we believe this is the next logical step for user).

**Comment by egamma** [comment]
@DonJayamanne if I understand you properly you want to programmatically open a view?

You should be able to do this today. There is a command for each view. You can find the corresponding command IDs in the keybindings editor.  You should then be able to do this programmatically using `vscode.commands.executeCommand(‘workbench.view.extension.test’)`.

**Comment by DonJayamanne** [comment]
Yes, that's what I'm after and thats exactly what I use to look for the commands. Couldn't find it in there:
<img width="559" alt="Screen Shot 2019-06-11 at 00 44 12" src="https://user-images.githubusercontent.com/1948812/59252999-2ddf7600-8be2-11e9-86ac-c002c6c243fb.png">

**Comment by egamma** [comment]
So then you can do what you intend and we close the issue, or is there still something missing?

**Comment by DonJayamanne** [comment]
Curious, why isn't the command Id exposed for this command.
As you can see from the screenshot, the command I'd isn't displayed!

**Comment by DonJayamanne** [comment]
> So then you can do what you intend

Yes this is what I need, but not sure why I can't see the command in vsc stable and insiders on a Mac.

**Comment by DonJayamanne** [comment]
Found the problem, when typing `Show Test` in the search box, then command ids are not displayed. However typing `View Test` displays the command ids!
Interesting.

**Comment by DonJayamanne** [comment]
@sandy081 I can file a separate issue for the search issue if required.
I'm not too concerned at this stage, even though I believe there's a problem.

**Comment by sandy081** [comment]
Can you please show the screenshot when command ids are shown and when it does not?

**Comment by DonJayamanne** [comment]
![issue](https://user-images.githubusercontent.com/1948812/59385916-3c30ad80-8d1a-11e9-94b5-a60172bfa317.gif)

**Comment by sandy081** [comment]
I see.. command ids are shown because they have matches. Otherwise by default they are not shown if labels are available. You can find the ids by hovering on the labels.

**Comment by DonJayamanne** [comment]
> command ids are shown because they have matches.

This is still a bug. Assume I'm someone else, I don't know the command id at all.
Now how do i find it.

I know the command is named `Show Test`, and I type that, but nothing appears.
How do i know that I need to type in `View Test`, when the command is explicitly named `Show Test`. I.e. i cannot find something when I don't know what it is.

**Comment by sandy081** [comment]
> Now how do i find it.

Do you mean the command id? I see the entry is shown with both phrases `View Test` and `Show Test`. Only difference is that it does not show command id. As said, command id is shown when you hover on the entry. Also why is the command id is important for a normal user?
