### ISSUE TITLE
Intellisense unusably slow

### ISSUE THREAD

**Issue by nickmkk** [microsoft/vscode#75214]
Use intellisense, observe unusable experience

There was another similar issue reported that was closed and I don't understand why?  Several people are obviously experiencing this, downgrading to the previous version is not an acceptable solution...

https://github.com/microsoft/vscode/issues/72616

![intellisense](https://user-images.githubusercontent.com/10885165/59225994-b8e74e80-8b97-11e9-91cf-d536d8ca49f2.gif)

**Comment by mjbvz** [comment]
What VS Code version, OS version, and extensions do you have enabled?

/needsMoreInfo

**Comment by nickmkk** [comment]
@mjbvz  Sorry for the delay getting back to you, here is my system info.

Version: 1.35.0 (user setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

CPUs | Intel(R) Xeon(R) CPU W3690 @ 3.47GHz (12 x 3464)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledsurface_synchronization: enabled_onvideo_decode: enabledwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 16.00GB (8.11GB free)
Process Argv |  
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
ng-template | Ang | 0.800.0
path-intellisense | chr | 1.4.2
tslint | eg2 | 1.0.43
vscode-npm-script | eg2 | 0.3.7
prettier-vscode | esb | 1.9.0
auto-close-tag | for | 0.5.6
sass-lint | gle | 1.0.5
code-beautifier | mic | 2.2.1
Angular-BeastCode | Mik | 8.0.7
material-icon-theme | PKi | 3.8.0
code-spell-checker | str | 1.7.16

**Comment by mjbvz** [comment]
Does this still happen when you disable all extensions?  Also, please share more info about your workspace or ideally some example code that demonstrates this
