### ISSUE TITLE
Process explorer icons are not centered vertically

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#75210]
![image](https://user-images.githubusercontent.com/323878/59213686-4b70f900-8b6a-11e9-956a-b166bf58460a.png)

The icons seem a little higher than they should be.

Also they are not using the new icons when I have opted in, is that expected to work? @misolori

**Comment by misolori** [comment]
@roblourens those aren't updated yet but I can add them

**Comment by RMacfarlane** [comment]
Closing since we now use the tree widget, so this doesn't repro
