### ISSUE TITLE
HTML indentation inside PHP files part 2

### ISSUE THREAD

**Issue by andremacola** [microsoft/vscode#75223]
The #34178 issue is back.

1.36.0-insider (1.36.0-insider)

Steps to Reproduce:

1. Save any file to file.php
2. type div (or any html tag) (press tab and enter)

Reproduces without extensions: Yes

What happen:
![30302501-dcdfbc74-9737-11e7-886e-750d19d409b4](https://user-images.githubusercontent.com/3408809/59234706-6bcda180-8bc4-11e9-814f-ff0a0e7afd4c.png)

Expected:
![30302500-dcdf2e30-9737-11e7-93a1-b04ff6d6bd1b](https://user-images.githubusercontent.com/3408809/59234707-6f612880-8bc4-11e9-933b-a4eecb268f65.png)

**Comment by roblourens** [comment]
Tracked in https://github.com/microsoft/vscode/issues/42782
