### ISSUE TITLE
Built-in terminal loses output

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/vscode#75229]
Issue Type: <b>Bug</b>

Built-in terminal loses output, replacing the missing text with blank lines.  I can't reproduce this on command, but it happens very often and is quite annoying.  Also affects `tsc --watch` as it loses the text that watching has begun; I end up thinking it locked up.

This issue has been ongoing through several updates of VSCode.

Compare terminal output in VSCode for a webpack build
![image](https://user-images.githubusercontent.com/4097841/59242930-9f67f600-8bdb-11e9-98eb-4515e638a81b.png)

To the same output from a direct command prompt
![image](https://user-images.githubusercontent.com/4097841/59242956-b1499900-8bdb-11e9-8e57-40a83746aea2.png)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-eslint|dba|1.9.0
csharp|ms-|1.19.1
debugger-for-chrome|msj|4.11.3
LiveServer|rit|5.6.1
shader|sle|1.1.4

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by fatcerberus** [comment]
Thanks, I guess my recent update to Win10 May 2019 (18362) enabled ConPTY in VSCode and now the built-in terminal is much less glitchy. :smiley:
