### ISSUE TITLE
File not showing up in quick picker

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#75226]
Issue Type: <b>Bug</b>

When I type `edit attendee`, VS Code correctly find the file `edit-attendee.html`:

![image](https://user-images.githubusercontent.com/490562/59240907-b0574c80-8c59-11e9-8382-b997d517d00e.png)

When I type `view attendee`, VS Code fails to find the file `view-attendee.html`:

![image](https://user-images.githubusercontent.com/490562/59240920-be0cd200-8c59-11e9-8892-e5de73eaab80.png)

Only when I'm explicit with a dash does it find the file:

![image](https://user-images.githubusercontent.com/490562/59240938-ca912a80-8c59-11e9-9f8d-4c58578df2aa.png)

Why this discrepancy?

VS Code version: Code - Insiders 1.36.0-insider (7a5bca9fafbbb23de289179be95e9c4832540c02, 2019-06-06T11:36:26.351Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.2
vscode-eslint|dba|1.9.0
file-icons|fil|1.0.17
multi-command|ryu|1.3.0
vscode-fileutils|sle|2.14.5
reopenclosedtab|uyi|1.1.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by egamma** [comment]
This issue is that `view` is a quick pick command that allows you to navigate to the Open Views (see below).

While this is confusing in this case, it is working as designed.

![image](https://user-images.githubusercontent.com/172399/59252702-ec27ed00-8c2c-11e9-8c97-6a74736ddb4e.png)

**Comment by adamreisnz** [comment]
This is quite annoying, when I'm in a file picker I expect to be able to pick files, not be bothered with other commands. Where can I disable/change the alias for these quick pick commands?

**Comment by adamreisnz** [comment]
How can something be "as designed" if it's preventing you from doing what it's supposed to do in the first place, e.g. quickly opening a file?

**Comment by adamreisnz** [comment]
Same issue with trying to find a file that starts with `task`.
