### ISSUE TITLE
Terminal Command Prompt Missing

### ISSUE THREAD

**Issue by mjohnson24** [microsoft/vscode#75228]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Start VS Code thats all
2.

Does this issue occur when all extensions are disabled?: No

Command prompt is not showing up. I cant type in the terminal, can't use it.

**Comment by thebeersmith** [comment]
Same issue here... I'm using PowerShell.
Should mention, this has been the case for a number of versions.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
