### ISSUE TITLE
new version's performance is so bad

### ISSUE THREAD

**Issue by Virczz** [microsoft/vscode#75227]
Issue Type: <b>Performance Issue</b>

1.the git was so slow. When I edit some page and use the git to find different. It's slow.
2. There is not the same for the language when I open two or more window. the first is true, and others are default English.

Ummm. bad English level.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    79	  2752	code main
    1	    68	  2260	   window (问题报告程序)
    0	    47	 13992	   shared-process
    1	   262	 29856	   window (index.vue (Working Tree) - jn-icip - Visual Studio Code)
    0	     6	 15364	     watcherService 
    0	     4	 32356	       console-window-host (Windows internal process)
    0	     2	 20008	     winpty-process
    0	     4	 23204	       C:\Windows\System32\cmd.exe
    0	     9	 28324	       console-window-host (Windows internal process)
    0	     2	 20708	     electron-crash-reporter
    0	   197	 21180	     extensionHost
    0	     4	  6440	       "C:\Users\usv\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\usv\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=21180
    0	    10	 11320	       "C:\Users\usv\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\usv\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=21180
    0	   112	 14676	       electron_node vueServerMain.js 
    0	    18	 17664	       electron_node tsserver.js 
    0	    19	 14288	         electron_node typingsInstaller.js typesMap.js 
    0	    27	 31668	     searchService
    1	   561	 30344	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.vue (Working Tree) - jn-icip - Visual Studio Code)
|    Folder (jn-icip): 730 files
|      File types: js(185) ts(134) wxss(127) json(126) wxml(126) vue(14)
|                  wxs(10) eslintignore(1) md(1) editorconfig(1)
|      Conf files: package.json(1);
```

</details>

**Comment by joaomoreno** [comment]
Sorry but I can't understand what the issue is. Can you maybe send a video recording showing what is slow?

**Comment by Virczz** [comment]
Sorry, all the features are now good. But I don't know the reason for the failure The day before yesterday.
