### ISSUE TITLE
Why not style more stuff with CSS?

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#75233]
File explorer indent size could be a simple CSS style, instead of JavaScript.

Feature request: style file explorer indent size  (and other features) with CSS (use a CSS var if you want it to come from JS), that way the look/feel of the editor is much easier to hack. This is one of the areas where Atom is strong.

**Comment by egamma** [comment]
@trusktr 

>that way the look/feel of the editor is much easier to hack

While this is true, to make this non-hacky would require that we expose the CSS styles as API. This is not something we can sign-up to.

**Comment by trusktr** [comment]
> would require that we expose the CSS styles as API. This is not something we can sign-up to.

@egamma Why not? Is because those would be like Global variables? Does the JS implementation allow more control, and less opportunity of plugins clashing? Curious to learn about this.
