### ISSUE TITLE
Integrated Terminal CopyPaste from Terminal

### ISSUE THREAD

**Issue by danielkaufmann** [Microsoft/vscode#7523]
- VSCode Version: 1.2.0
- OS Version: WIn7 64

Steps to Reproduce:

1. Start  Integrated Terminal
2. >powercfg /L (just use any command /? to get output text)
3. try copy output text in terminal to use in script.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6451
