### ISSUE TITLE
Better support for decorator in `@example` jsdoc block

### ISSUE THREAD

**Issue by wayou** [microsoft/vscode#75238]
Considering the following sample code:

```ts
/**
 * description for decorator `Foo`
 *
 * @example
 *
 * @Foo
 * public async MyController(){...}
 *
 */
function Foo(_target: any, _key: string, descriptor: PropertyDescriptor) {
// ....
}
```

We get the following result:

<img width="665" alt="with_at" src="https://user-images.githubusercontent.com/3783096/59249293-fe1e8580-8c56-11e9-992c-98bfce8fe7c7.png">

Seems VSCode does not parse the decorator correctlly within the `@example` code block of jsdoc.

and here's the result without decorator:

<img width="692" alt="without_at" src="https://user-images.githubusercontent.com/3783096/59249382-2efeba80-8c57-11e9-8227-77f5b3fef408.png">

**Comment by mjbvz** [comment]
This is consistent with also how jsdoc itself handles this case, a new @tag block always starts a new block.

Please try filing an issue/question against jsdoc upstream if you want to see this supported better: https://github.com/jsdoc/jsdoc/i
