### ISSUE TITLE
Wrong extension dependency list 

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#75231]
- VSCode Version: 1.35.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open VS Code extension panel
2. Search `Java Dependency Viewer`
3. Switch to `Dependencies` section, there are two dependencies.
![WeChat Screenshot_20190611122242](https://user-images.githubusercontent.com/6193897/59243802-58fab180-8c44-11e9-83ba-4925dd1ff13e.png)

But according to the [source code here](https://github.com/microsoft/vscode-java-dependency/blob/master/package.json#L165-L167), it should not contain the python extension.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connorshea** [comment]
This seems to be occurring for all extensions, for some reason :)

**Comment by sandy081** [comment]
@jdneo I cannot repro this. Can you please try with latest insiders https://code.visualstudio.com/insiders/ and see if you are able to repro?

**Comment by jdneo** [comment]
Update:
  - Can repro in the standard version
  - Cannot repro in the insider version

**Comment by sandy081** [comment]
Please wait for next stable release for the fix.

**Comment by ruslan-bikkinin** [comment]
@sandy081 still experience this on both stable 1.36 and 1.37 insiders
![image](https://user-images.githubusercontent.com/30265843/60895189-dbd75200-a26c-11e9-822b-91db0602ff38.png)

**Comment by sandy081** [comment]
Yes I can repro.

**Comment by maziac** [comment]
Having the same issue with my extension "maziac.z80-unit-tests.
vscode version 1.36.1

**Comment by sandy081** [comment]
Please update to latest `1.37` where the fix went in.
