### ISSUE TITLE
vscode extension - can't align text to the right in quickpick control

### ISSUE THREAD

**Issue by ShimonBenYair** [microsoft/vscode#75236]
vscode extension - can't align text to the right in quickpick control
Steps to Reproduce:

1.Use the quickpick sample : https://github.com/microsoft/vscode-extension-samples/tree/4c2ba979fc933af2330543cbab0566d1ea2a39c6/quickinput-sample

2.try to align the text of the quickpick items to the right -  I dont see any option to do it

**Comment by ShimonBenYair** [comment]
so there is no option to do it ?

**Comment by chrmarti** [comment]
No, there is no option for this at the moment. Taking this as a feature request.
