### ISSUE TITLE
Signature Helper does not highlight parameters starting with an ampersand 

### ISSUE THREAD

**Issue by glennsarti** [microsoft/vscode#75239]
- VSCode Version: 1.35.0 (system setup)
- OS Version: Windows 10 - 1809

### Expected Behaviour
When I trigger the signature helper feature, it should highlight the selected parameter.

### Actual Behaviour
When I trigger the signature helper feature, it does not highlight the parameter which starts with ampersand `&`

When the cursor is on second parameter, the second param is highlighted
![image](https://user-images.githubusercontent.com/5819622/59249788-2955a480-8c58-11e9-9797-6534070bf087.png)

However when the cursor is on the third parameter it does not highlight
![image](https://user-images.githubusercontent.com/5819622/59249980-9f5a0b80-8c58-11e9-89d8-bb2203c829d3.png)

Looking at the JSON response from the Language Server to the client you can see they are correct.

When the cursor is on the second param (`"activeParameter":1`)
``` json
{
	"jsonrpc": "2.0",
	"id": 10,
	"result": {
		"signatures": [{
			"documentation": "",
			"label": "assert_type(Type $type, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "&block"
			}]
		}, {
			"documentation": "",
			"label": "assert_type(String $type_string, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type_string"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "&block"
			}]
		}],
		"activeSignature": 0,
		"activeParameter": 1
	}
}
```

When the cursor is on the third param (`"activeParameter":2`)
``` json
{
	"jsonrpc": "2.0",
	"id": 4,
	"result": {
		"signatures": [{
			"documentation": "",
			"label": "assert_type(Type $type, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "&block"
			}]
		}, {
			"documentation": "",
			"label": "assert_type(String $type_string, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type_string"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "&block"
			}]
		}],
		"activeSignature": 0,
		"activeParameter": 2
	}
}
```

There are no errors in the Developer Tools console

### Additional Information

I modified my language server to remove the leading ampersand to see what happens the it highlights (mostly) correctly

![image](https://user-images.githubusercontent.com/5819622/59250280-6706fd00-8c59-11e9-8042-1ca7a3828e93.png)

Note - `"activeParameter": 2` and the parameter label is now `block`

```json
{
	"jsonrpc": "2.0",
	"id": 11,
	"result": {
		"signatures": [{
			"documentation": "",
			"label": "assert_type(Type $type, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "block"
			}]
		}, {
			"documentation": "",
			"label": "assert_type(String $type_string, Any $value, Optional[Callable[Type, Type]] &$block)",
			"parameters": [{
				"documentation": "",
				"label": "type_string"
			}, {
				"documentation": "",
				"label": "value"
			}, {
				"documentation": "",
				"label": "block"
			}]
		}],
		"activeSignature": 0,
		"activeParameter": 2
	}
}
```

### Steps to Reproduce

This is a little tricky to reproduce as I've found this issue while I was developing a Language Server

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
This is because the label for the parameter is `&block`, but it is displayed as `&$block` in the  signature label we use for underlining. The labels need to exactly match for the underlining of the active parameter to work

A better way to fix this is to have your language provider return a range (`[number, number]`) for `ParameterInformation.label` instead of a name: https://github.com/microsoft/vscode/blob/cae0668a0ed9fb9be106de11ab5d5725f12f9a4b/src/vs/vscode.d.ts#L3091

**Comment by glennsarti** [comment]
@mjbvz Oh of course!  Sorry, I shouldn't seen that.
