### ISSUE TITLE
Why the CompletionItem doesn't show up when I set its range?

### ISSUE THREAD

**Issue by YHaoNan** [microsoft/vscode#75237]
I'm sure the range is correct.

```typescript
provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.ProviderResult<vscode.CompletionItem[] | vscode.CompletionList> {
    const range = getWordRange(document,position);
    const currentWord = document.getText(range);

    let result:vscode.CompletionList  | undefined;
    Object.keys(RULES).forEach(regex=>{         
        let match = currentWord.match(regex);
        if(match){
            result = RULES[regex](match,range);
            return;
        }
    });
    console.log(result); // Result is correct
    return result?Promise.resolve(result):null;
}
```

This is my provideCompletionItems method,It works like Responsibility Chain.It will return when find a function can handle it.

In the last third lines,I print result to the console and the result is correct,but it doesn't show up in UI when i test the plugin.

Here is some code In the matched function from the RULES.
```typescript
//...some code
let text = optMap[match[2]]+match[1]+optMap[match[2]];
item.documentation = new vscode.MarkdownString('## 插入样式\n\n'+text);
item.detail = '样式转换';
item.insertText = text;
item.range = range;
return new vscode.CompletionList([item]);
```

The CompletionItem will show up when i delete the last second line.

This problem has been bothering me for a day!!! Sad!!!

**Comment by jrieken** [comment]
Sorry but I cannot follow. Can you share a working sample - extension code and source file in which you try this. Thanks

**Comment by YHaoNan** [comment]
> Sorry but I cannot follow. Can you share a working sample - extension code and source file in which you try this. Thanks

Ah,I see.

The VSCode API document said that The range must contain the position at which completion has been requested.

I can't understand it before.

Let's say the input is "abc.b" and it's in line 0,the keyword is '.' , in that way the range must be (0,4,0,5).
In other words,the range can only contain the text after the keyword.(I don't know wether what I say is correct)

But i wanna replace all the text, so , finally , I use the additionalTextEdits to implements that.

```typescript
item.additionalTextEdits = [TextEdit.delete(range)];
```

**Comment by jrieken** [comment]
Please share a working example. YEs, the range must include the position at which suggestions have been requested *and* the range "selects" the text which is used to filter the suggestion against

**Comment by YHaoNan** [comment]
> Please share a working example. YEs, the range must include the position at which suggestions have been requested _and_ the range "selects" the text which is used to filter the suggestion against

Oh,I'd resolved my problem yesterday.Thanks!!
This is my first time to create a VSCode extension and it's my first time to use TypeScript.xD

The full code about the AutoComplete is [here](https://github.com/YHaoNan/Markdown-X/blob/master/src/autocomplete.ts).
