### ISSUE TITLE
Devtools console error on startup

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#75245]
The following error shows up in devtools everything a folder without a  `.vscode` subfolder is opened:

![image](https://user-images.githubusercontent.com/22350/59258348-19c66380-8c38-11e9-9b6e-f67eb7e1e9ee.png)

Steps:

1. Open folder without `.vscode` folder within
2. Open any file
2. Check the devtools console

---

Comes from:

https://github.com/Microsoft/vscode/blob/1c1c33c18db5e26f6b4529e1b20c0eb3e4c4fab6/src/vs/workbench/contrib/snippets/browser/snippetsService.ts#L275

cc @bpasero

**Comment by jrieken** [comment]
@bpasero Why would the `exists` call produce such a message? Isn't this the what its return value represents?

**Comment by bpasero** [comment]
@jrieken the `IFilesystemProvider` interface only exposes `stat` as method, not `exists`. So there is no other choice than calling `stat` on a file which produces an error that we simply log to the console. Previously when the file system provider for local files was implemented using just node.js, I had `fs.exists()`, but we no longer use it.

**Comment by jrieken** [comment]
Yeah, but `stat` is spec'd to throw a `FileNotFound` exception and my expectation is that `exists` knows how to handle that (or that the provider throw that error)

**Comment by bpasero** [comment]
@jrieken I debugged this and found that it does not originate from the exists check, but rather from a call to `IFileService.watch()` even if the resources does not exist:

https://github.com/Microsoft/vscode/blob/c5bddfa5c2a6c3154e29d887297d52d34d535d7d/src/vs/workbench/contrib/snippets/browser/snippetsService.ts#L280

Can you check? I would argue printing an error in that case is OK.

**Comment by jrieken** [comment]
Hm... I need to know when the folder is being added. How do I listen for that? Should I listen on the parent and its add-events?

**Comment by bpasero** [comment]
@jrieken if this is about a folder within the workspace, you do not have to install a watcher yourself right, you can just rely on the file changes event to be sent. If the folder is not within the workspace, then actually we currently do not have any good solution other than watching on the parent too.
