### ISSUE TITLE
Opening multiple files from Windows Explorer context menu, when one of those files is already open in code.

### ISSUE THREAD

**Issue by alenas** [microsoft/vscode#75244]
Issue Type: <b>Bug</b>

Open VSCode and open "first.txt" file.
Open Windows Explorer and select multiple files, and include same "first.txt" file. Right click on selection and choose Open with VS Code.
You will get error.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.55GB free)|
|Process Argv|open_create.reg|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
@alenas what error?

**Comment by alenas** [comment]
Crap, can't reproduce easily. The error was something like "file not found or is locked". I will make a screenshot when it fails again.

**Comment by bpasero** [comment]
Please do, it sounds familar.
