### ISSUE TITLE
Sort completion items by item type

### ISSUE THREAD

**Issue by RUSshy** [microsoft/vscode#75248]
Completion items should be forted by type and not by A-Z

VSCode:
![image](https://user-images.githubusercontent.com/18348637/59260240-8bec7780-8c3b-11e9-9185-b176a0514748.png)

Rider:
![image2](https://user-images.githubusercontent.com/18348637/59127502-1b5a0800-8968-11e9-9d8a-bfa6157f24d5.png)

You can also see in Jetbrains IDEs, there is much more informations, VSCode feels like someone who doesn't know my project at all, so how can it help ???

**Comment by gjsjohnmurray** [comment]
See #74213
