### ISSUE TITLE
Store history of regexp for search and replace

### ISSUE THREAD

**Issue by pixmaster** [microsoft/vscode#75246]
Issue Type: <b>Feature Request</b>

It would be perfect to have history of regexp (and simple) in search or/and replace. I didn't find any buttons that related to it.
![image](https://user-images.githubusercontent.com/3305295/59258602-f3f18c80-8c40-11e9-89a3-37915a711893.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
You can actually use the arrow keys to navigate the history in both boxes.
