### ISSUE TITLE
Suggested variables auto completes on full stop

### ISSUE THREAD

**Issue by m-garg** [microsoft/vscode#75249]
- VSCode Version: 1.35.0
- OS Version: macOS Mojave 10.14.1 (18B75)

Steps to Reproduce:

1. Type a couple of words (for example, "we")
2. Press full stop, comma or semi-colon.

The highlighted suggestion would auto fill.

Does this issue occur when all extensions are disabled?: Yes

![ezgif-1-370c944d6d8c](https://user-images.githubusercontent.com/10848368/59260411-34f59b00-8c59-11e9-9255-8e6a495693b8.gif)

**Comment by gjsjohnmurray** [comment]
Looks like a duplicate of #70176. @m-garg if you agree please close this one.

**Comment by m-garg** [comment]
@gjsjohnmurray Thanks. It seems to be the same issue. Sorry, I couldn't find the issue before filing this one.
