### ISSUE TITLE
Updating Code when Windows shutting down

### ISSUE THREAD

**Issue by yemling** [microsoft/vscode#75247]
- VSCode Version: Latest
- OS Version: Windows 10

Steps to Reproduce:

1. When closing Code to shut down laptop, it sometimes updates the program.
2. If I don't spot it doing the update (in that little dialog box) and shut down the laptop, then when I go to use Code again it's uninstalled and I have to download and install it again.

Does this issue occur when all extensions are disabled?:  I have no idea.

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of #52855 - @yemling if you agree it is, please close this one.

**Comment by yemling** [comment]
Yes, it is a duplicate, it'd be great if it could be fixed though as it's happened several times now. Windows usually says 'this application is stopping shut down' for most apps, it needs to happen for this updater too.
