### ISSUE TITLE
Search for Files and Folders

### ISSUE THREAD

**Issue by StanNL** [microsoft/vscode#75252]
I think it would be a very nice addition if you were able to search for files and folders in the search tab (the Ctrl+Shift+F one). Instead of searching _within_ files, I'd like to be able to search _for_ file names or even file types using asterisks. It would be pretty neat if it displayed the files and folders at the top of your search results (perhaps minimizable) and only after that the results from within the files.

**Comment by roblourens** [comment]
You can use "quick open" with ctrl+p to search for files, is that what you are looking for?
