### ISSUE TITLE
High CPU usage after search in project on macOS

### ISSUE THREAD

**Issue by mikpetr** [microsoft/vscode#75255]
Issue Type: <b>Performance Issue</b>

Sarch something in the project,
then is starts to drain battery and fans always working.

It worked well in previews version.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	  1657	code main
    0	    82	  1658	   gpu-process
    0	   279	  1659	   window (ReportsEditor.html — ui-app)
    0	    82	  1665	     extensionHost
    0	   180	  1667	       electron_node tsserver.js 
    0	    49	  1683	         electron_node typingsInstaller.js typesMap.js 
    0	    66	  1670	       electron_node eslintServer.js 
    0	    98	  1681	       electron_node server.js 
    0	    98	  1700	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=1665
    0	    49	  1666	     watcherService
    0	    82	  1690	   shared-process
    2	    82	  1715	   window (Issue Reporter)
    0	     0	  1718	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ReportsEditor.html — ui-app)
|    Folder (ui-app): 1414 files
|      File types: html(453) js(449) png(156) less(152) vue(30) svg(25)
|                  json(21) map(21) css(19) ico(8)
|      Conf files: package.json(7) webpack.config.js(2) gulp.js(1);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
auto-close-tag|for|0.5.6
vetur|oct|0.21.0
code-spell-checker|str|1.7.16

</details>

**Comment by roblourens** [comment]
Can you check whether any of these tips are relevant? https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results

**Comment by mikpetr** [comment]
I just updated to 1.35.1 version. Does not hit to that issue yet. Will let you know when it appears.

**Comment by mikpetr** [comment]
Again the same situation. It starting to use CPU and drain battery after search in a project. There exists some large files, but it starts CPU usage after the search, and not stop when I stop searching.

**Comment by mikpetr** [comment]
![image](https://user-images.githubusercontent.com/5211427/59562319-4ca79780-903c-11e9-854b-da433ccbc453.png)

**Comment by mikpetr** [comment]
Code helper is starting when I start searching in a project, and then not stop and even not close when I quit from VS Code

**Comment by roblourens** [comment]
Can you check in vscode's process explorer so we can see exactly which process that actually is?

**Comment by mikpetr** [comment]
Where it is?

**Comment by roblourens** [comment]
Under the Help menu.

**Comment by mikpetr** [comment]
![image](https://user-images.githubusercontent.com/5211427/59745652-5290b900-9286-11e9-8892-1931d3f572aa.png)

**Comment by roblourens** [comment]
Ok, it looks like the eslint extension is doing a lot of work. I'm not sure what that has to do with search. If you opened a bunch of files after doing the search then maybe eslint is scanning those files. Can you give the exact steps that led to this?

**Comment by mikpetr** [comment]
Well, I am searching for some staff, and there are some built and minified files, I am opening that files and then go to others. But when I am close it it continue to run hot. Even when I am closing VS code.

**Comment by roblourens** [comment]
Ok, please file an issue on the eslint extension.  Probably it is slow to process the minified files.
