### ISSUE TITLE
Cut & paste of selected line drops newline

### ISSUE THREAD

**Issue by mcroker** [microsoft/vscode#75251]
Note - I believe this may be the same issue as #58293, which was (potentially incorrectly) closed on the basis it is working as designed & locked.

- VSCode Version: 1.35
- OS Version: MacOS Mojave 10.14

Steps to Reproduce:

1.  Select a line (with the mouse) & Ctrl-C
2. Select a different line (with the mouse) & Ctrl-V
3. The new line character is 'eaten' causing the line below to append

Note - this doesn't happen when Ctrl-X is used instead of Ctrl-C (suggesting to me that the copy buffer for a selected line needs to include the EOL character.

Video of what happens here https://youtu.be/a2uvGLrX-Zo 

Does this issue occur when all extensions are disabled?: No (although it does still happen if I launch without the disable-exensions options but without any extensions enabled).  The only extensions I had installed are vim, TSLint, XML Tools, Debugger for Chrome.

**Comment by alexandrudima** [comment]
@mcroker I cannot reproduce. Does the issue reproduce for you when disabling extensions? 

(
![Kapture 2019-07-30 at 16 50 36](https://user-images.githubusercontent.com/5047891/62139761-2edf7a80-b2ea-11e9-81b7-3b603b9431ec.gif)
