### ISSUE TITLE
Interact with files in search results

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode#75259]
Being able to interact with the files that appear in `Search` would be useful. A few examples that come to mind:

1. Rename file matched by search. Clicking the file in the search result and then pressing `F2` does not work. Right-clicking the file does not show the `Rename` command. Right-clicking the file does not show `Reveal in Side Bar` (where the file could be renamed). The only option I've found is to click one of the matches to open the file, right click the tab, select `Reveal in Side Bar` and rename the file using the `Explorer` side bar (`F2` or right-click).
2. Delete file matched by search.
3. Delete multiple files matched by search.
4. Dismiss multiple files from the search result.
5. Compare two files matched by search.

When right-clicking a file in `Search`, I think all the options that are shown when right-clicking a file in `Explorer` should be shown. Then any options added by extensions would also be available. The keyboard shortcuts `Delete` and `Ctrl+C` should probably keep their current behavior.

Also, it should be possible to select multiple files, similar to in `Explorer`.

**Comment by skprabhanjan** [comment]
@roblourens , can we take this up separately ? ( Like rename , delete etc )
I would like to work on that if that is the case. Please let me know , Thanks :)

**Comment by roblourens** [comment]
I think a "reveal in explorer" command for search results would be really useful and I would take a PR for that. But I don't want to replicate all the the other commands and functionality of the explorer.

**Comment by Stadly** [comment]
Just adding "Reveal in Explorer" goes a long way :) I've created a different feature request for allowing selecting multiple files: https://github.com/microsoft/vscode/issues/77749

**Comment by sandy081** [comment]
To be consistent the command should be called `Reveal in Side Bar`

![image](https://user-images.githubusercontent.com/10746682/62122053-7d891680-b2e2-11e9-8b84-dcfab2d099a9.png)


Also I do not understand the logic why it is at the top. Is not this after copy commands?

**Comment by skprabhanjan** [comment]
@sandy081 , The command was called "Reveal in Side Bar" but @roblourens preferred "Reveal in Explorer".
Also i can change the position and add it where ever you both suggest, Thanks :)

**Comment by roblourens** [comment]
You're already looking at the side bar, so I don't think "Reveal in side bar" makes sense. I don't really like it for the tab context menu either, I think we should be more specific.
