### ISSUE TITLE
Unknown FileSystemError when settings.json on readonly filesystem

### ISSUE THREAD

**Issue by Kloenk** [microsoft/vscode#75250]
- VSCode Version: 1.34.0
- OS Version: nixos 19.03

Steps to Reproduce:

1. put settings.json into /nix/store via homemanager (read only filesystem) and link it into /home/user
2. do something that tries to change the settings.json file
3. returns an unknown error, but the error code says that it is on a read-only filesystem => Failed to save 'settings.json': Unable to write file (Unknown (FileSystemError): Error: EROFS: read-only file system)
Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It is expected that settings file should be editable. Since it is not above error is valid.
