### ISSUE TITLE
Key binding for openToSide?

### ISSUE THREAD

**Issue by z0mt3c** [Microsoft/vscode#7526]
Is it possible to define a key binding for the openToSide-action - or is there any? :-)

![screenshot](https://cloud.githubusercontent.com/assets/1782471/15962174/8cf7029a-2f09-11e6-98e4-7cc36ce84591.png)

**Comment by alexandrudima** [comment]
In the `Ctrl+P` list, I use `Ctrl+Enter`. Otherwise I use `Ctrl+2` quite a lot.

@bpasero : Should there be a hover showing the keybindings?

**Comment by z0mt3c** [comment]
Hmm, didn't i try that? :-) works great - thanks.... 👍

**Comment by bpasero** [comment]
👍
