### ISSUE TITLE
Something happen with "Source: Update Service"

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode#75260]
- VSCode Version: 1.36.0-insider
- OS Version: MacOS Mojave 10.14.5
<img width="465" alt="Screen Shot 2019-06-11 at 3 24 03 PM" src="https://user-images.githubusercontent.com/31858171/59271768-17c2cb80-8c5d-11e9-9ff8-890da8ef769f.png">

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/73806
