### ISSUE TITLE
Another side dock

### ISSUE THREAD

**Issue by Serhioromano** [microsoft/vscode#75275]
We have a dock on the side where we show filed, search, ... That used to be ok till some time ago when I started to use VS Code on all my projects. The thing I miss most is to be able to dock another navigator to a new location. For example, I want OUTLINE to be on the right full height always show the structure of my file. I have a lot of files in a project and when I share height between project navigator and outline, I cannot use well any of those. 

The ability to drug any navigator to the right and have docks on both sides is ideal.  But at least to get OUTLINE navigator as separate column would be nice too.

**Comment by gjsjohnmurray** [comment]
See #49923 for this being discussed for Outline.
