### ISSUE TITLE
Stray processes left when closing the main window

### ISSUE THREAD

**Issue by semihalf-kardach-stanislaw** [Microsoft/vscode#7527]
- VSCode Version: 1.2.0-1465219835
- OS Version: Linux Mint 17.3 Rosa (4.4.0-22-lowlatency #40~14.04.1-Ubuntu SMP PREEMPT Fri May 13 22:47:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

Steps to Reproduce:

1. In terminal run `code`.
2. (sometimes optional) enable built-in terminal and run `ls` in it
3. Close the window
4. Result:

```
kda@toster ~ $ code
# launch terminal, do something in it and close the window
kda@toster ~/workspace/tmp $ code
kda@toster ~/workspace/tmp $ pgrep -la code
31925 /usr/share/code/code
31928 /usr/share/code/code --type=zygote --no-sandbox
31999 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=SharedProcess
32179 /usr/share/code/code ./terminalProcess
```

I've captured the strace for the `code` process with:
`strace -f -o vscode.strace.log code > vscode.stdout.log 2> vscode.stderr.log`

Result is attached.
[vscode.strace.log.zip](https://github.com/Microsoft/vscode/files/308909/vscode.strace.log.zip)

**Comment by alexandrudima** [comment]
@joaomoreno for the shared process, @Tyriar for the terminal process

**Comment by Tyriar** [comment]
Terminal process already fixed in https://github.com/Microsoft/vscode/issues/7458

**Comment by joaomoreno** [comment]
This is strange. The shared process checks for its parent. And now so does the terminal process. If that doesn't work as we think it does... both are broken.

**Comment by joaomoreno** [comment]
This should be fixed in the later insiders: https://code.visualstudio.com/insiders

@semihalf-kardach-stanislaw Let us know if otherwise.
