### ISSUE TITLE
Text pasted into rich text programs does not specify a fallback font

### ISSUE THREAD

**Issue by ryanoshea** [microsoft/vscode#75279]
Issue Type: <b>Bug</b>

When pasting text from the editor to another program, such as an email, the HTML generated to specifies only the editor font as the font-family of text elements, so if the user has specified a custom editor font that doesn't exist on most systems, recipients of the code will see it rendered in a default, non-monospaced font. In this case, pasting code from VS Code (with font set to Inconsolata) into an outlook email causes the code to be rendered in Times New Roman for recipients that don't have Inconsolata installed. 

Current paste result:

```html
<span style='font-size:10.5pt;font-family:Inconsolata;color:#F09483'>...
```

Proposed paste result:

```html
<span style='font-size:10.5pt;font-family:Inconsolata, monospace;color:#F09483'>...
```

A good solution might be to always specify a fallback font corresponding to the class of the editor font: `monospace`, `sans-serif`, or `serif`.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
Good suggestion, thanks!
