### ISSUE TITLE
Setup dialog not suppressed with /SUPPRESSMSGBOXES /VERYSILENT 

### ISSUE THREAD

**Issue by PhilLee-MSFT** [microsoft/vscode#75281]
- VSCode Version:  1.35.0
- OS Version:  Windows 10

Steps to Reproduce:

With 64-bit VS Code installed, run run VSCodeSetup-ia32-1.35.0.exe with /SUPPRESSMSGBOXES /VERYSILENT

You'll get a dialog that says "please uninstall the 64-version before attempting to install the 32-bit version.”

**Comment by piraces** [comment]
Hello. I can take this issue if you want, I have reproduced and identified the bug.
I will open a PR when ready :+1

**Comment by joaomoreno** [comment]
Verification:

1. Install 32 bit
2. Try to install 64 bit, see msg box
3. Try to install 64 bit from the command line with /VERYSILENT, msg box should not come up

**Comment by lramos15** [comment]
`VSCodeUserSetup-x64-1.36.0-insider.exe /VERYSILENT` or `start VSCodeUserSetup-x64-1.36.0-insider.exe /VERYSILENT` still displays the message box.

**Comment by piraces** [comment]
It appears that latest insider release was built using this commit:
https://github.com/microsoft/vscode/commit/b7265738444f1eee05762341b4361ee6452a4154/

Commit fixing this is was hours later:
https://github.com/microsoft/vscode/commit/90d25d083557bbf2ce9c34e0def82a971cd58653

It's possible that insiders version doesn't include the fix yet @lramos15 ?

**Comment by lramos15** [comment]
Oh yes. Normally I catch myself on this, but It's still early in the morning I guess. Thank you for pointing that out, I'll test it once insiders contains the fix.
