### ISSUE TITLE
Use activityBarBadge.foreground for the badge progress indicator

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75288]
When set to black on a dark theme the progress indicator is white:

![image](https://user-images.githubusercontent.com/2193314/59295933-afaebe00-8c39-11e9-91f9-028e411d2645.png)

![image](https://user-images.githubusercontent.com/2193314/59295947-b4737200-8c39-11e9-8698-b03cb05d78f9.png)

**Comment by usernamehw** [comment]
Related or duplicate #44604

**Comment by misolori** [comment]
@usernamehw thanks!
