### ISSUE TITLE
cannot edit in read only mood

### ISSUE THREAD

**Issue by Mehrab-Hossain** [microsoft/vscode#75280]
"After compiling a code in v
![Screenshot (2)](https://user-images.githubusercontent.com/50637969/59287650-e3b6cd00-8c93-11e9-93f1-0d4db7db79a9.png)
s code i can't write anything in the terminal,it just read the code.In the vs code settings code runner:Run in the Terminal option is enabled.Last three or four days i faces this problem."

please give me any solution

**Comment by Tyriar** [comment]
An extension is launching that terminal as it's called "Compile Run"
