### ISSUE TITLE
Open file via URL should open hosted file via http

### ISSUE THREAD

**Issue by Messulethe92** [microsoft/vscode#75282]
It would be nice to be able to specify a URL in the "vscode://file/" command, eg: 
vscode://file/https://github.com/microsoft/vscode/blob/master/README.md

In my case I have a script-editor website where I would like to send a file straight to VSCode from my front-end, so that a user doesn't have to copy-paste the code manually, or the user has to click a link to download the file. It would be nice to try the VSCode://file/URL so that I can open the script straight into VSCode. 

Furthermore, support a UNC path would also be nice, eg:
vscode://file/\\\\sharedServer\sharedFolder\README.md

Right now: 
![image](https://user-images.githubusercontent.com/36839817/59288019-19978980-8c73-11e9-9765-534bee644e82.png)

**Comment by Messulethe92** [comment]
FYI - same error for UNC path:
![image](https://user-images.githubusercontent.com/36839817/59325155-34edad80-8ce2-11e9-8261-b613e423ca85.png)

Note, also tried double escaping the UNC path, causing no errors, but also not opening the file - probably an exception happening - cannot confirm: 
vscode://file/\\\\JFOL-NB-02\Shared\File.cs

**Comment by jrieken** [comment]
This the API that your extension needs to use: https://github.com/microsoft/vscode/blob/4a3c056e9a56e45bee19cff400f4891e2fb89774/src/vs/vscode.d.ts#L6675-L6696. Find an example (git extension) [here](https://github.com/microsoft/vscode/blob/4a3c056e9a56e45bee19cff400f4891e2fb89774/extensions/git/src/protocolHandler.ts#L15)
