### ISSUE TITLE
Angular 7 Typescript doesn't work in 1.35

### ISSUE THREAD

**Issue by rcketscientist** [microsoft/vscode#75292]
- VSCode Version: 1.35
- OS Version: Win 10

Steps to Reproduce:
Open an Angular 7 (Typescript 3.2.4) project in Code 1.35.  It will be little better than a text editor as intellisense and definitions will be broken.  Tried with multiple ng7 projects.  They were all useless in 1.35 and worked fine when I rolled back to 1.34.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What TypeScript version are you using in your workspace?

**Comment by rcketscientist** [comment]
If you mean an actual Code workspace, we don't have one, just a vanilla angular project, no ts server config.  So I believe the tsc was the built-in one 3.5.1 (I think).  First time it's ever been an issue to run with the built in ts.

**Comment by rcketscientist** [comment]
One of our guys tracked it down:
https://github.com/microsoft/TypeScript/issues/31868
