### ISSUE TITLE
Quick Open 

### ISSUE THREAD

**Issue by yuliangruan** [microsoft/vscode#75294]
- VSCode Version: 1.35 both regular and insider
- OS Version: Win 10

Steps to Reproduce:

1.   Ctrl+P to pull up quick action box
2.   start typing in filename in the project
3.   expect near instant response of list of files matches as in VSCode 1.34
4.   actual behavior is shows the revolving progress bar for 2-3 seconds before showing the list

our project is about 2000 files.  

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Please check whether any of these tips are relevant: https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results

**Comment by paolo-venturi** [comment]
I tried to disable the parameters indicated in the guide (search.useIgnoreFiles, search.followSymlinks) but the problem continues to exist. In previous versions the problem did not exist.

VSCode Version: 1.35 both regular and insider
OS Version: Win 8/10

Our project is about 20000 files.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
No response from OP, closing. @paolo-venturi please open your own issue with more details
