### ISSUE TITLE
Integrated terminal (powershell) cuts input and autoexecuted incomplete command

### ISSUE THREAD

**Issue by vavalomi** [microsoft/vscode#75296]
- VSCode Version: 1.35.0
- OS Version: Window 10 10.0.18362

Steps to Reproduce:
1. paste long string into the terminal, for example $lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
2. It doesn't happen on the first run, but I am able to ultimately 'break' it if I keep just simply generating random variables and assigning log text.
3. Seems to be triggered easier if the terminal is aligned to the right and then the maximum length of the string accepted before cutting seems to depend on the width of terminal window, if I widen it more, I can fit more.
4. Once it starts breaking, the behavior can be replicated even by keyboard input, i.e. typing long text, so not happening exclusively via pasting from buffer, although seems to be triggered only this way.

Does this issue occur when all extensions are disabled?: Yes/No No

**Comment by Tyriar** [comment]
Do you see something like this?

![image](https://user-images.githubusercontent.com/2193314/60760342-eda8c300-9fe8-11e9-87f2-8a31d428dc16.png)

**Comment by vavalomi** [comment]
no, I just get the line broken into multiple commands as if there were linebreaks and then get regular syntax error messages from powershell...

**Comment by Tyriar** [comment]
@vavalomi does it happen if you change the setting terminal.integrated.windowsEnableConpty to false?

**Comment by vavalomi** [comment]
@Tyriar you are definitely onto something - I could reliably reproduce the error with the true setting but not even once with false.

**Comment by Tyriar** [comment]
Can you repro the same problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab)?

**Comment by Tyriar** [comment]
I think this is https://github.com/microsoft/vscode/issues/78967

/duplicate
