### ISSUE TITLE
VSCode + Angular X - Intellisense bug with underscore functions

### ISSUE THREAD

**Issue by ExDeaDguY** [microsoft/vscode#75297]
Hi Guys, I am using the latest version of VSCode 1.35.0 and Angular 7. I came across an odd bug. I'm pretty sure it's a bug and not a config setting.

In angular, my component folder has 3 items in it, my .html, .scss, and .ts files. When I create functions in the component ts such as:

```
public ThisIsAFunction() { }
public ThisIsAnother_Function() { }
```

Now in the html file I will create an element and try to assign a property like so:

`<button (click)="this.ThisIsAFunction()">DoFunction</button>`

The issue here is, when I start typing "this.ThisIsA" the intellisense will only display "ThisIsAFunction" in the list of available functions. Any functions named with an underscore will never show up.

Thanks.

**Comment by mjbvz** [comment]
Please file this against your angular extension

**Comment by ExDeaDguY** [comment]
> Please file this against your angular extension

Isn't the intellisense handled by vscode though? Thanks for the reply, will do.
