### ISSUE TITLE
Support for a TDD Layout

### ISSUE THREAD

**Issue by carl-menezes-aql** [microsoft/vscode#75298]
Many languages have a clear way to distinguish between test and non-test code. 

When doing TDD, I always find myself with a two vertical tab layout - one tab group with test code and the other with non-test code:

VSCode Window:

| tab group1  | tab group2|
| ------------- | ------------- |
| testcode 1| code under test 1  |
| testcode 2 | code under test 2|

When I create a new file, I usually have to move it to the correct tab group so that it fits with this layout. It would simplify the workflow considerably if VSCode placed test code (or non test code) in the correct tab group 

Note that this feature request is **not** about getting VSCode to execute any TDD specific actions, like the red-green-refactor loop. This is purely about layout of the files being worked on.

A simple, naive test would be:
* Open a collection of files with the TDD layout enabled

Expected:

* Test code is in one tab group
* Non test code is in a different tab group

Next:
* Add a new test file

Expected:
* New test file is automatically in the test tab group

I realise not all languages provide a way to distinguish between test and non test code. However, I submit that enough languages do to make it really useful. In addition to that, TDD is widely used, which would make this a good addition to VSCode as a modern code IDE.

**Comment by spartanatreyu** [comment]
Have you tried View -> Editor Layout -> Grid (2x2)?

I'm assuming this is what you're after.

**Comment by carl-menezes-aql** [comment]
No it isn't. Like I said, what's important is that VSCode knows which group a file belongs to based on the type of code that's in it.

So it's not the grid layout I'm after, but intelligent placing of opened files in the correct place within that grid, based on the code they contain.

**Comment by spartanatreyu** [comment]
Ah, I understand now.

How would vscode determine which file goes into which grid cell? Are the tests named a certain way? Does the file structure of the project specify what is a test? Is there a standard way to determine this regardless of which project you're working in? Would different test frameworks have different ways of displaying files or the same? Are there multiple workflows to consider?

Assuming the answer to this is it will be different for each developer/project, this could be a good excuse to make a plugin for vscode to learn more about its internals.

**Comment by carl-menezes-aql** [comment]
It would depend on the language. Some languages like Go and C# can detect test code. Some languages can't and still others can only if you're using a specific test framework. I would suggest the scope for this feature only includes languages that do provide this information. I'm not familiar with the language server, but I was wondering if some functionality there can be used to distinguish test code from non test code? 

In essence, if the ability to identify test code is part of the language, then it would be nice if VSCode used that information to its advantage to provide a TDD friendly layout.

**Comment by spartanatreyu** [comment]
You could try and figure out what test framework is used based on file extension and keywords inside the file but this might be really error-prone and more trouble than it is worth. Testing could vary wildly between languages + frameworks. It would probably be better to detect and recommend an extension for the user's current particular test framework.

In the grand scheme of things, the lessons learnt from the extensions could help maybe one day unifying testing across frameworks and languages into a shared spec(s) and perhaps into vscode itself.
