### ISSUE TITLE
Unable to Search for or Install Extensions Behind Proxy

### ISSUE THREAD

**Issue by sebasijan** [Microsoft/vscode#7529]
- VSCode Version: 1.2.0
- OS Version: Windows 7

Steps to Reproduce:

1. Open VSCode
2. F1
3. Type "Install"
4. Select "Extensions: Install Extension"

At this point, I see a loading bar, but it never goes away - it just loads forever. If I click into another window, it appears to stop searching and does nothing. This is quite frustrating as it means I can't really use VSCode for anything.

I am behind a proxy, and I have amended by User Properties like so : 

    // Place your settings in this file to overwrite the default settings
      {
          //-------- HTTP configuration --------

          // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
        "http.proxy": "http://my.proxy.ip.here:portnumber",

        // Whether the proxy server certificate should be verified against the list of supplied CAs.
        "http.proxyStrictSSL": false
    }

As per another similar issue which was related to proxy and extensions not installing

**Comment by joaomoreno** [comment]
Did you restart Code after modifying the settings?

**Comment by sebasijan** [comment]
Yes I restarted after each attempt. Let me know if there is anything I can post that might be helpful

**Comment by lextm** [comment]
@sebasijan you might use a tool such as Wireshark to analyze if the packets go through the proxy properly. If they do then I suspect your corporate proxy blocks the access to the necessary site for some reason.

The setting has been verified by far too many users, so I think this issue you report is more related to the network settings than VSCode itself.

**Comment by sebasijan** [comment]
@lextm Thanks for the advice Lex - WireShark seems really useful. I can't work out thought - how can I filter packets to only analyse those coming from VSCode? There are so many packets when viewing it is impossible to distinguish by eye. 

Is there perhaps an IP address which `Install Extensions` always makes a call to so that I can isolate?

Thanks again

**Comment by sebasijan** [comment]
Okay I was able to resolve this after my network manager disabled SSL Inspection on my machine. After re-enabling it the issue comes back. I tried setting 

> "http.proxyStrictSSL": true

After we re-enabled SSL (as the default was "false") but I am still unable to see extensions. Is this expected?

**Comment by joaomoreno** [comment]
Yeah, this sounds like a problem in your network.
