### ISSUE TITLE
Filter errors / warnings for current file only

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#753]
When I am viewing the *Errors and Warnings* (`COMMAND + SHIFT + M`), I should be able to filter the list for only the current file that I am viewing. Right now, it is showing the errors for all files in the currently opened folder / workspace.

In the screenshot below, I am currently viewing a file called `azuredeploy-webapps.json`, but the *Errors and Warnings* pop-up is showing me warnings for a different file called `azuredeploy.json`.

![screen shot 2015-11-27 at 9 50 44 am](https://cloud.githubusercontent.com/assets/466713/11445783/6e7d8224-94ec-11e5-8b87-887c24f7f520.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by jrieken** [comment]
@pcgeek86 You should be able to do that by typing the filename. For Jan it will event look pretty:

<img width="900" alt="screen shot 2015-12-23 at 10 17 49" src="https://cloud.githubusercontent.com/assets/1794099/11973801/70e8eb6c-a95e-11e5-9ee7-fedc7de3491d.png">

**Comment by pcgeek86** [comment]
@jrieken Awesome, thanks. Seems a little confusing that the default would be to show errors from all files, but that might just be me. :) 

Cheers,
Trevor Sullivan
