### ISSUE TITLE
default spaces always changed back to 2

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/vscode#75301]
Hi

    default spaces always changed back to 2 everytime i restart vscode. I have set the "Tab Size" to 4 and disabled "Insert Spaces".

Even i manually change to tab-4 by clicking the footer bar at the bottom. When i restart vscode, it changed back to spaces-2

thanks

**Comment by quantrpeter** [comment]
It is caused by a plugin called "EditorConfig". When i remove it, vscode back to works.

**Comment by mattgaspar** [comment]
Thanks, 
I've been struggling with this on a couple projects.  The Aurelia cli tool created a ".editorconfig" file which was overriding my VSCode settings.  I thought it was a bug in a VSCode update!  I will file a bug with Aurelia!

**Comment by quantrpeter** [comment]
Thanks @mattgaspar
