### ISSUE TITLE
DOM Manipulation properties and functions intellisense problem

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#75303]
When I write DOM properties. It was working well even after the new release it worked properly but from few hours it had a problem and that pictures will explain the problem

When I type style property it doesn't show anything

![pr](https://user-images.githubusercontent.com/42807112/59310080-92afd480-8ca5-11e9-9b2b-2579233368f0.jpeg)

**Comment by mjbvz** [comment]
`getElementsByClassName` return an `Element` (you can check this by hovering) We do not know for sure that it will return an html element with a style property.

You need to add a jsdoc cast to tell VS Code that you really do have html Elements:

```js
const elements = /** @type {HTMLCollectionOf<HTMLDivElement>} */(document.getElementsByClassName('bla'));
```
