### ISSUE TITLE
Git Switching branch cause error: permission denied

### ISSUE THREAD

**Issue by leo-117** [microsoft/vscode#75305]
Issue Type: <b>Bug</b>

step one: I work on branch A. I create new files and add to commit and push.
step 2: I switch branch to the branch B  (In this branch no exist the new files, created on branch A). In this branch i do nothing. 
step 3: back to the branch A, and then the error ocurred.

i think that when vscode try create the files againt on the branch A, the operating system cause the exception

Sorry my english is bad : /

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?
