### ISSUE TITLE
Integrated terminal does not honor PS1 properly

### ISSUE THREAD

**Issue by EricDepagne** [microsoft/vscode#75302]
- VSCode Version: 1.35.0
- OS Version: Archlinux

Steps to Reproduce:

1. Create a prompt that makes use of 24 bits colors 
2. Open a terminal (my shell is bash) and the integrated terminal.
3. run ls on the same directory.

Expected results:
Both prompt  should be identical, but they are not.
The colors themselves are slightly different (see the two images attached)
This is the aspect of the prompt in my terminal 
![shellprompt](https://user-images.githubusercontent.com/7965617/59308780-2da6af80-8ca2-11e9-94f2-1f4b51699c47.png)

This is the same prompt, as shown in the integrated terminal
![vscodeprompt](https://user-images.githubusercontent.com/7965617/59308825-49aa5100-8ca2-11e9-9f49-5183853622b4.png)

On top of that, the icons, created by [lsd](https://github.com/Peltoche/lsd/) are not shown.

Here is the PS1 variable that created that prompt:
\[\033[0;0m\]\[\e[38;2;16;122;176m\][Local]\[\e[38;2;10;221;8m\] :: \[\e[38;2;240;131;63m\]eric\[\e[38;2;10;221;8m\] :: \[\e[38;2;251;85;129m\]Portable \[\033[0;0m\]\[\e[38;2;250;194;5m\]\w\[\033[0;0m\] on branch \[\e[38;2;199;96;255m\]${GIT_BRANCH}\[\033[0;0m\] L\[\033[0;0m\]:\[\e[38;2;254;0;2m\] ✚2\[\033[0;0m\]\[\e[38;2;5;255;166m\] ⚑2\[\033[0;0m\]\[\033[0;0m\]\n\[\e[38;2;16;122;176m\]\D{%a %d/%m/%y} \[\e[38;2;10;221;8m\]:: \[\e[38;2;16;122;176m\]\t\[\e[38;2;10;221;8m\] :: \[\e[38;2;254;0;2m\]\#\[\e[38;2;128;249;173m\] → \[\033[0;0m\]

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Different colors: https://github.com/microsoft/vscode/issues/69135

The icons are configured through `terminal.integrated.fontFamily`
