### ISSUE TITLE
Warnings and Errors don't appear upon hover

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75304]
Issue Type: <b>Bug</b>

While developing in the VS Code repo the warning and errors do not appear on hover. The tooltips do appear on smaller repositories. 

Steps to reproduce
1. Create an error in the VS Code Repo
2. Hover over the the error

The developer console contains an error for Maximum call stack size exceeded with this statement repeated:
```
    at _toDispose.forEach.e (lifecycle.ts:105)
    at Set.forEach (<anonymous>)
    at a.clear (lifecycle.ts:105)
    at a.dispose (lifecycle.ts:98)
```

VS Code version: Code - Insiders 1.36.0-insider (7bc29bf67c17608b11e23a8497c8f1de5a0922cf, 2019-06-11T08:29:28.099Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
remote-containers|ms-|0.60.0
remote-ssh-edit-nightly|ms-|2019.6.15380
remote-ssh-explorer-nightly|ms-|2019.6.15380
remote-ssh-nightly|ms-|2019.6.15380
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0
polacode|pnp|0.3.2
vscode-sort-json|ric|1.13.0

</details>

**Comment by lramos15** [comment]
Upon reload hover will appear and then close instantaneously and I get the error `Grammar is in an endless loop - Grammar pushed & popped a rule without advancing`.

**Comment by mjbvz** [comment]
Can you please test this again in the latest insiders. I wasn't able to repo but fixed a potential cause of the issue

**Comment by mjbvz** [comment]
Closing as dispose loop was fixed
