### ISSUE TITLE
Running Two Versions

### ISSUE THREAD

**Issue by fadihania** [microsoft/vscode#75310]
Issue Type: <b>Bug</b>

I have already updated VS Code to latest version 1.35 but sometimes when opening workspaces or folders it randomly run some of them on 1.34.

At this moment, I have two copies of VS Code running next to each other one on 1.35 and the other on 1.34

How can I fix that?

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.88GB (9.21GB free)|
|Process Argv|D:\permagreen\PermaGreen\PermaGreen.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Uninstall both and install VS Code again.
