### ISSUE TITLE
Conflict prompts will upset the location of the original line

### ISSUE THREAD

**Issue by Imputes** [microsoft/vscode#75313]
For example:
The main branch text:
![image](https://user-images.githubusercontent.com/12896162/59326275-a3e5f900-8d18-11e9-8b74-db8e7d0df3f8.png)

The br_1 branch text:
![image](https://user-images.githubusercontent.com/12896162/59326317-c5df7b80-8d18-11e9-9ac7-cb6bbd1a3743.png)

After switching to main, execute merge command, the line number is completely messed up:
![image](https://user-images.githubusercontent.com/12896162/59326368-f45d5680-8d18-11e9-8f7f-8848b086224d.png)

It would be better if there was something like this:
![image](https://user-images.githubusercontent.com/12896162/59341476-7e69e700-8d3a-11e9-9d63-0c31a238a714.png)

**Comment by Imputes** [comment]
I found this feature, open the command panel with ```Command+ Shirft+P``` in macOS, and then input ```Merge Conflict: Compare Current Conflict```:
![image](https://user-images.githubusercontent.com/12896162/59356781-23e18280-8d5c-11e9-8ed5-9806735deda7.png)

**Comment by Tyriar** [comment]
The first view you're in is the actual file, we wouldn't want the compare thing there as you're simply viewing the file.
