### ISSUE TITLE
Outline: Object of JSON array should be sorted by position

### ISSUE THREAD

**Issue by Tobyee** [microsoft/vscode#75318]
Version: 1.36.0-insider (user setup)
Commit: f291714906cdcb02830b8cfe2485a3c23415b5fe
Date: 2019-06-12T05:19:53.054Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a json file such as following content.
``` json
{
	"nodes":[
		{ "key":0, "name":"0" },
		{ "key":1, "name":"1" },
		{ "key":2, "name":"2" },
		{ "key":3, "name":"3" },
		{ "key":4, "name":"4" },
		{ "key":5, "name":"5" },
		{ "key":6, "name":"6" },
		{ "key":7, "name":"7" },
		{ "key":8, "name":"8" },
		{ "key":9, "name":"9" },
		{ "key":10, "name":"10" },
		{ "key":11, "name":"11" }
	]
}
```
2. Take a look at the 11-th\12-th object of array nodes in OUTLINE view.

![Screen Shot](https://user-images.githubusercontent.com/1400574/59327355-d47b6200-8d1b-11e9-9d05-3dfcb21d89df.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
What sort mode are you using? What does  "Outline > ... > Sort By: " show?

**Comment by Tobyee** [comment]
@jrieken 
It's default setting, shows "Sort By: Type".
So, it's by designed while sorting by Type?
