### ISSUE TITLE
[Feature request] CompletionItem's icon can be defined by icon property.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#75311]
Since now the CompletionItem's is defined by the `kind`, I think we can also support an optional `icon: string | Uri` property that will make it more powerful.

What I want to implement is an extension that can autocomplete color by providing a color palette, and I can see what the color really is by the CompletionItem's icon. This will help developers choose the appropriate colors.

Look forward to your reply.

**Comment by jrieken** [comment]
Honestly, this is unlikely to happen because it also impact the LSP and that mean each extension needs to ship icons that match the style of the corresponding editor, Eclipse style icons, Sublime style icons etc. That's why we have common set of kinds which editor associate to icons.
