### ISSUE TITLE
When saving all, save whatever files can be immediately saved, even if some can't be

### ISSUE THREAD

**Issue by Arrow7000** [Microsoft/vscode#7531]
If I have a bunch of unsaved files open, plus one or two new ('untitled') ones and then click 'save all', it immediately throws up a dialog asking me to 'save as' the untitled files. When i don't want to save them, none of the files have been saved. 

This makes little sense; those files that can be immediately saved should be saved, and those that can't should wait for more information. The untitled files shouldn't hold up the others from being saved.

**Comment by bpasero** [comment]
Good point, that can probably be changed easily.

**Comment by Arrow7000** [comment]
Thanks for working on this! Which release will this update be in?

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/16067448/09e52488-32bd-11e6-8f13-770a925c8c38.png)
