### ISSUE TITLE
Autocompletion support for python dataclasses' __init__

### ISSUE THREAD

**Issue by aspyct** [microsoft/vscode#75319]
Autocompletion could be better for dataclasses in Python. Currently, when creating a new instance of such a class, the only parameter suggestion is `args, kwargs`.

```python3
from dataclasses import dataclass

@dataclass
class Animal:
    species: str

Animal()
```

This is the tooltip we get:
<img width="254" alt="Screen Shot 2019-06-12 at 08 20 35" src="https://user-images.githubusercontent.com/1143093/59327927-5010eb00-8ceb-11e9-9231-ed64549ae4d5.png">

It'd be nice if we could have the actual properties of the class in the right order, as well as their type.

**Comment by mjbvz** [comment]
Please file this against the python extension

**Comment by aspyct** [comment]
https://github.com/microsoft/vscode-python/issues/6007
