### ISSUE TITLE
Using VSCode and SF extension unable to perform conflict resolution

### ISSUE THREAD

**Issue by SethMagner** [microsoft/vscode#75312]
When performing a commit vscode is sending a file to a stag
![59006776-b2508400-87f1-11e9-818d-129e263b4f69](https://user-images.githubusercontent.com/28605067/59324394-c17d7900-8cac-11e9-8498-983568c397cf.png)
e changes area instead of a merges changed area not allowing for conflict resolution.

**Comment by joaomoreno** [comment]
Can you give me exact reproducible steps?
