### ISSUE TITLE
is there a way to standardize the formatting behavior in a team?

### ISSUE THREAD

**Issue by zzzgit** [microsoft/vscode#75322]
https://code.visualstudio.com/docs/languages/html#_formatting

According to this page, we can customize the formatting behavior in vs-code by modifying the `settings.json` file.

However, if we need to standardize the behavior in our team, what should we do? Is there an extension for that?

**Comment by temi007** [comment]
Not sure if it helps but vs code understand .editorconfig files 
https://editorconfig.org/

**Comment by adelphes** [comment]
Depends on what language you're coding in, but for JS/TS a really popular formatter is [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). You can commit a config file which defines the formatting rules for your team.

**Comment by Tyriar** [comment]
Editorconfig/prettier are good recommendations as they're editor agnostic 👍
