### ISSUE TITLE
VSCode Insiders completely broken after latest update

### ISSUE THREAD

**Issue by charles4221** [microsoft/vscode#75321]
Issue Type: <b>Bug</b>

The latest VSCode Insiders update (Wed 12 June, around 4:30pm AEST) has broken everything. I can't backspace or use arrow keys, I can't switch views in the Explorer, I can't open preferences or settings, I can't do anything I need to do for my job!

VS Code version: Code - Insiders 1.36.0-insider (f291714906cdcb02830b8cfe2485a3c23415b5fe, 2019-06-12T05:18:48.847Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
random-string-password-generator|bib|1.0.2
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.0
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
gitlens|eam|9.8.2
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
apacheconf-snippets|eim|1.2.0
vsc-material-theme|Equ|2.9.0
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
sass-lint|gle|1.0.5
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
docthis|joe|0.7.1
sublime-babel-vscode|jos|0.2.10
haml|kar|1.2.0
auto-comment-blocks|kev|1.0.1
vscode-liquid-snippets|kil|1.2.0
graphql-for-vscode|kum|1.13.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
php-docblocker|nei|1.8.0
language-liquid|nei|0.1.1
vscode-phpcbf|per|0.0.8
material-icon-theme|PKi|3.8.0
ruby|reb|0.23.0
sass-indented|rob|1.5.1
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.2.9
gitconfig|sid|2.0.0
open-in-browser|tec|2.0.0
hosts|tom|1.1.1
wordpress-snippet|tun|1.1.5
vscode-wakatime|Wak|2.1.2
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.1
vscode-import-cost|wix|2.12.0
wordpress-toolbox|wor|1.3.4
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
markdown-all-in-one|yzh|2.3.1

(3 theme extensions excluded)

</details>

**Comment by charles4221** [comment]
- also can't open integrated terminal (or any of the tabs that sit alongside it) - pressing `Control+~` does nothing.
- when opening a file from the Explorer side panel it shows the contents of the file in the editor but doesn't update the tabs of which files are open across the top
- can't switch between open tabs in the editor view

**Comment by charles4221** [comment]
- opening command pallette (`Cmd+shift+p`) does nothing
- go to file / go to line / go to symbol don't work

**Comment by Ovyerus** [comment]
Getting this too after updating today.

**Comment by storm1er** [comment]
Colors gone wild :/
It's OK but after some times it starts to look like unicorn poop ...
![gnome-shell-screenshot-01ID3Z](https://user-images.githubusercontent.com/9821946/59334197-3aef8880-8cfa-11e9-9b2d-f92dc08b800a.png)

![gnome-shell-screenshot-8LHP3Z](https://user-images.githubusercontent.com/9821946/59334224-4a6ed180-8cfa-11e9-885b-32990490f56a.png)

Once it happens, I can't do anything to get colors back, I have to restart vscode :(

**Comment by MrBaptastic** [comment]
Right clicking a folder in the explorer, freeze the app

**Comment by maximilian-krauss** [comment]
Got the same issues 😐 Is there a way to rollback to the previous one?

**Comment by piotrgredowski** [comment]
> Got the same issues neutral_face Is there a way to rollback to the previous one?

for Debian/Ubuntu/Mint I suggest to rollback to `1.36.0-1560242080`, for me it's working ok.
```bash
apt install code-insiders=1.36.0-1560242080
```

**Comment by SlyDen** [comment]
I could recover using `brew cask reinstall visual-studio-code-insiders` on Mac OS

**Comment by mwwski** [comment]
Happens on windows too after running the in app update.

**Comment by manrueda** [comment]
To do a manual rollback you can get the last good Insider osx build from here:

https://az764295.vo.msecnd.net/insider/c089daa858f34631f5f827ff8a0313bf1e2ded6d/VSCode-darwin-insider.zip

**Comment by batjko** [comment]
New release (same version) seems to fix the issue:
![image](https://user-images.githubusercontent.com/7287076/59387811-fc8db400-8d61-11e9-89c2-c583aefd0418.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
