### ISSUE TITLE
Integrated Terminal parsing VSCode variables

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode#75320]
Can you add feature when type in Integrated Terminal, for example: `${workspaceFolder}` and it's will move you actually to the `${workspaceFolder}` ... ? Or other work in Integrated Terminal with VSCode variables.

Currently in VSCode 1.36.0-insider on MacOS Mojave 10.14.5 it's doesn't work.

<img width="244" alt="Screen Shot 2019-06-12 at 9 22 59 AM" src="https://user-images.githubusercontent.com/31858171/59328178-666f7480-8cf4-11e9-884a-0732133004dc.png">

**Comment by Tyriar** [comment]
This is impossible, the shell (bash/zsh/etc.) is in control of this sort of thing and anything we do would be flaky at best.
