### ISSUE TITLE
Explicitly refresh active text editor from extension api.

### ISSUE THREAD

**Issue by bmingles** [microsoft/vscode#7532]
There doesn't appear to be any way to explicitly refresh the active text editor. This would be useful for extensions that modify files via external commands and need to show the latest version once said command completes.

**Comment by alexandrudima** [comment]
@bmingles Would `window.showTextDocument` help here ?

**Comment by bpasero** [comment]
There is an option for opening editors to `forceOpen` which will reload the file from disk. Assuming we do not want to make this extension API, an alternative would be to add a command for this.

/cc @jrieken

**Comment by jrieken** [comment]
@bpasero Isn't this a case for file events?

**Comment by bpasero** [comment]
@jrieken yeah though all the bugs I have on file events show me that they do not work in all cases ;-)

**Comment by bpasero** [comment]
Actually in this case what could bite is the fact that I ignore file change events on the currently edited file for a short period because otherwise I would reload the file every time you made a modification. 

@bmingles is this a possible explanation that the text content is rapidly changed after the user saved? what is the use case for the extension?

**Comment by bmingles** [comment]
I have an extension that can run arbitrary shell commands whenever a user saves a file (using vscode.workspace.onDidSaveTextDocument). I have some users of the extension that are running commands that modify the source file after save and are asking if it could update the active file after the commands run. The goal would be to explicitly refresh it in the extension after commands run and not based on change detection on the source file.

**Comment by slemireOmni** [comment]
My current version of VS code is 1.11.1 and got the same issue.

I noticed that the VS code editor do not refresh when an external program update a file (copy, save, etc). If the opened file is currently focused in the editor and change externally, it does not refresh. 

The workaround to refresh the opened and focused file in VS code is to select another opened file and get back to the edited/updated opened file.

Steps to reproduce:
-	Open a file in VS Code.
-	Open the same file in Notepass++, change it and save it.
-	Get back to VS Code.

Expected result: The change is visible in VS Code.

I found this while trying to debug a file under the node_module that is copied from another server package during the build process.

Please, give us a solution to automatically refresh opened and focused file in VS Code editor when an external program change it.

**Comment by bmingles** [comment]
@slemireOmni To clarify, it sounds like you are asking for a different feature, one that responds to a file system change or something external to vscode. The feature I am requesting here is for extension developers to be able to explicitly trigger a refresh via a vscode extension through an api of some sort.

**Comment by alekstheod** [comment]
Is it still open? Any solution to that? It is really annoying I can't use any formatting tools as vs get out of sync with the formatted files.

**Comment by bmingles** [comment]
@bpasero Has there been anything added to the extension api that would facilitate this,

**Comment by bpasero** [comment]
There is no official API yet (hence this issue is still open).

The only workaround to force refresh the active file from disk is to call our internal command `workbench.action.files.revert`, e.g. by doing `vscode.commands.executeCommand('workbench.action.files.revert')`.

**Comment by bpasero** [comment]
`workbench.action.files.revert` should work. It will force the active editor to read the contents from disk again and update the UI. It will not work for dirty files.
