### ISSUE TITLE
Not viewing suggestions - Typescript

### ISSUE THREAD

**Issue by arundev-kv** [microsoft/vscode#75328]
Issue Type: <b>Bug</b>

Showing loading instead of viewing suggestions.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.20GB free)|
|Process Argv|D:\ArunDev\Workspace\Sharja police\SPSA_Mobile|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
auto-close-tag|for|0.5.6
vscode-react-typescript|inf|1.2.1
vscode-typescript-tslint-plugin|ms-|1.1.0
vscode-react-native|msj|0.9.3
color-highlight|nau|2.3.0

</details>

**Comment by mjbvz** [comment]
Closing as there is not enough info to investigate
