### ISSUE TITLE
Open folder

### ISSUE THREAD

**Issue by emilmuller** [microsoft/vscode#75329]
When right-clicking on a file or folder, there is an "Open containing folder" option.

I frequently have to open a specific folder. In order to do this, I have to first expand the folder contents in vscode, then right-click on any of the children and select "Open containing folder". If the folder has no children, I have to right-click on it, select "Open containing folder", then find the folder in my explorer and enter it from there.

I would like to suggest that "Open containing folder" gets replaced with "Open folder", like it is in Visual Studio (not Code).

Kind regards, Emil :-)

**Comment by kousiksatish** [comment]
I would like to work on this issue. Will do initial analysis.

**Comment by isidorn** [comment]
Hi Emil,
When you right click on a file / folder in the explorer there is no "Open containing folder" as seen in my screenshot.
The action you are referring to has been added by an extension I believe.
You should use the vscode action "Reval in Finder", or "Reveal in Explorer"

If these actions are not exactly what you are looking for then please write an extension that contribues "Open folder" and does whatever you think is right. Or find one existing extension.

![Screenshot 2019-06-13 at 09 37 23](https://user-images.githubusercontent.com/1926584/59412983-ecf08880-8dbe-11e9-95aa-c82c6afcada1.png)

**Comment by emilmuller** [comment]
@isidorn 

https://github.com/microsoft/vscode/blob/9bd21e3f2b406ca2f5c4f47e45514ceb803872ac/src/vs/workbench/contrib/files/browser/fileCommands.ts

It is not part of an extension. However, it does come with a different label for different OSes it seems:

`export const REVEAL_IN_OS_LABEL = isWindows ? nls.localize('revealInWindows', "Reveal in Explorer") : isMacintosh ? nls.localize('revealInMac', "Reveal in Finder") : nls.localize('openContainer', "Open Containing Folder");`

**Comment by isidorn** [comment]
@emilmuller good point - forgot about that (I actually wrote that code). However we will not change this behavior to not upset acostumted users. If you would like a new action I still suggest to use an extension which contributes a simple action.
