### ISSUE TITLE
The Folding For Nested Brackets Is Not Done Correctly

### ISSUE THREAD

**Issue by hawston** [microsoft/vscode#75324]
Issue Type: <b>Bug</b>

We have lisp code with typical nested brackets structure, e.g.

(defun a ( b  c )
  (defun d ( e  f )
    (if (not g)
       (progn)
    )
; ** some comment ...  in lisp ";" is used for comment quote, and this cause the folding not work properly
 )
)

when I try to collapse the range of (), it does not collapse the right range with the corresponding closing bracket. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.63GB (50.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
autolispext|Aut|1.5.5

</details>

**Comment by gjsjohnmurray** [comment]
Anything smarter than indent-based folding is the responsibility of the extension that implements the language you're coding in. See [here](https://code.visualstudio.com/docs/editor/codebasics#_folding) for doc. Please raise this as an issue with the developer of the Lisp extension you are using, and close this issue here because it's not a VSCode bug.

**Comment by aeschli** [comment]
@gjsjohnmurray is correct, thanks, John, for explaining.
