### ISSUE TITLE
Blurry terminal

### ISSUE THREAD

**Issue by cossio** [microsoft/vscode#75336]
Whenever I switch off my session in Linux and return, VS code terminal looks like this:

![image](https://user-images.githubusercontent.com/10637482/59351225-32a94480-8d1e-11e9-9498-1a7e80efc73d.png)

With all text blurred. If I close and re-open the terminal it looks fine again.

**Comment by Daylien** [comment]
Could you provide some information about your system? I know this issue, but it not related to vscode in my case. I'm running Arch Linux with Gnome and a proprietary NVIDIA driver. Those pixel mash occurs when you wake up the system out of the suspension mode. But in my case you should also get this pixel mash in several application not only in vscode such as some parts of the gnome shell should become blurry. When you have a similar setup please let me know. 

A reddit user has written down a little workaround see [here](https://www.reddit.com/r/archlinux/comments/bd1vl1/gnome_nvidialts_buggy_wake_from_suspend/).

Hope this will help you.
