### ISSUE TITLE
Text stays on terminal even after clearing it

### ISSUE THREAD

**Issue by yoyo00xx** [microsoft/vscode#75335]
- VSCode Version: 1.35
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Write stuff on the terminal 
2. Clear the terminal 
3. Repeat the step from 1 one more time and the text will not go away

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rajan21march** [comment]
1. VSCode Version: 1.35

2. OS Version: Windows 10 Home Single Language

Problem:
>Write stuff on the terminal
>Clear the terminal
>But still stuffs on terminal not clear, only Cursor move from last line to First line. 
![Clear Error](https://user-images.githubusercontent.com/15049781/59379380-13d59d00-8d74-11e9-8af5-bc4f1a99c3eb.JPG)
