### ISSUE TITLE
PHP Debug not working with latest version 1.35.0

### ISSUE THREAD

**Issue by rukkykf** [microsoft/vscode#75337]
My VSCode just automatically updated itself to the latest version, 1.35.0
and now my PHPDebug extension isn't working. The debug tools are all disabled. These things were working perfectly fine before the update, I'm not sure what's causing this or how to go about this.

**Comment by weinand** [comment]
@isidorn in what situation are all debug tools disabled?

**Comment by isidorn** [comment]
@weinand this should never happen At least the stop should always be enabled.
@rukkykf can you reproduce with vscode insiders? Some reproducable steps are useful. Pictures?

**Comment by rukkykf** [comment]
the stop is enabled. it's only the step into, step over and step out tools that are disabled. And the breakpoints don't seem to be working, let me try this again.

**Comment by rukkykf** [comment]
just checked again and it's working fine, sorry about the waste of time.
