### ISSUE TITLE
Passing by a tab copies selected content in primary clipboard (Linux)

### ISSUE THREAD

**Issue by grippon** [microsoft/vscode#75345]
- VSCode Version: 1.35.0
- OS Version: Ubuntu 18

Steps to Reproduce:
Open 3 tabs.
In tab 2, write some text and select it.
In tab 3, write some text and select it.
Go to tab 1 by shortcuts (usually two Ctrl+Shift+Tab or Ctrl+PageUp) (I don't use "switch to last tab".).
Middle-click in tab 1.

Expected result : text from tab 3 is pasted
Actual result : text from tab 2 is pasted
Passing by tab 2 updated the primary clipboard with the selected text, it's a bug

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Looks like switching to tab 2 will see the selection and reapply it to the primary clipboard, ideally this should only happen at the time the selection is made.
