### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by isaac2004** [microsoft/vscode#75346]
- VSCode Version: 1.36.0 - Insider
- OS Version: Windows 1903

Steps to Reproduce:

1. Install Fresh Version
2. Try to open error list from bottom bar

![image](https://user-images.githubusercontent.com/8878502/59361826-7725e780-8d00-11e9-9b47-8766f277dc63.png)

After this, entire UI locks up

Does this issue occur when all extensions are disabled?: Yes

**Comment by OmriSama** [comment]
I'm getting this issue too after updating. I'm running VSCode latest insider off `apt` on Lubuntu 19.04 and anytime I try to type anything or make a keystroke I get this issue:

![image](https://user-images.githubusercontent.com/10534779/59369463-560bc980-8cf5-11e9-8434-2a869826abdc.png)

**Comment by OmriSama** [comment]
But also 
Duplicate of #75343
