### ISSUE TITLE
Cannot disable auto closing brackets in settings search input 

### ISSUE THREAD

**Issue by vomout** [microsoft/vscode#75349]
Issue Type: <b>Bug</b>

Setting editor.autoClosingBrackets to "never" seems to have little effect. Some closing brackets are still inserted, both in LaTeX Workshop (math mode brackets \[\], which probably should have a different setting in LaTeX Workshop), but also in the settings search box closing brackets are inserted. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (3.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
latex-workshop|Jam|7.0.2
language-julia|jul|0.11.6
change-string-case|max|1.1.1
hg|mrc|1.3.0
ayu|tea|0.18.0
markdown-all-in-one|yzh|2.3.1

(9 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@vomout I cannot reproduce. I have tried configuring `"editor.autoClosingBrackets": "never"` and typing `(` in a TypeScript file. The `)` is not inserted automatically. What precise steps would reproduce the issue?

**Comment by vomout** [comment]
Just go to the settings search box within settings (ctrl-alt-cmd-w) and type a bracket [, and see ] inserted. With auto-closing brackets set to never within the settings.

**Comment by alexandrudima** [comment]
Ok, now I understand. The settings search input box uses an editor and that one does not receive the global `editor.autoClosing...` option.

**Comment by roblourens** [comment]
Also extension viewlet search

**Comment by alexr00** [comment]
Verified that the settings search box never does auto closing brackets now.
