### ISSUE TITLE
Keyboard Events Broken

### ISSUE THREAD

**Issue by khpatel4991** [microsoft/vscode#75343]
- VSCode Version: 1.36.0-insider
- OS Version: Linux x64.4.15.0-20-generic

Steps to Reproduce:

1. Latest build of vscode-insiders doesn't detect any key events.

Does this issue occur when all extensions are disabled?: Yes
Attached is a developer console view.

![developerconsole](https://user-images.githubusercontent.com/6532483/59359212-efd67500-8cfb-11e9-8b29-f15fd202a5c1.png)

**Comment by rfoust** [comment]
Backspace (delete) key doesn't work for me at all on Mac now on the latest insiders. Dunno if that's related or not.

**Comment by jakewmeyer** [comment]
+1 on Backspace (delete) not working on Mac with latest insiders

Keybind settings are also inaccessible

**Comment by khpatel4991** [comment]
For me, on linux, none of the keys work.

**Comment by jm2242** [comment]
Also, shortcuts don't seem to be working (command+p, command+f, etc)

**Comment by OmriSama** [comment]
I'm running on latest Lubuntu and here's my traceback in case anyone was curious:

![image](https://user-images.githubusercontent.com/10534779/59369829-1a253400-8cf6-11e9-97df-6413b06b1b0d.png)

**Comment by OmriSama** [comment]
Working around by downgrading for now:

```shell
$ sudo apt install code-insiders=1.36.0-1559798873
```

**Comment by sandy081** [comment]
Can you please provide the content in your `keybindings.json` file?

**Comment by sandy081** [comment]
Steps to Repro:

- Open `keybindings.json` file
- Delete all content and save
- Reload VS Code
🐛 Keybindings do not work and above errors are seen

**Comment by sandy081** [comment]
Sorry for this. Fixed it and there will be a new insiders soon with the fix.

**Comment by sandy081** [comment]
New insiders released.

**Comment by OmriSama** [comment]
> New insiders released.

I take it probably takes some time to propagate through `aptitude`? :/

**Comment by khpatel4991** [comment]
Awesome... Thanks a bunch
