### ISSUE TITLE
Several features quit working every few minutes (format, intellisense, error updates)

### ISSUE THREAD

**Issue by Godrules500** [microsoft/vscode#75347]
I am writing an angular application and the issue I am having is while coding, eventually every thing seems to stop. I cannot hit f12 and go to variable/method, code formatting doesn't work, errors don't update and still show even if I have fixed it, tasks are no longer fired in vscode, etc. I am having to restart every few minutes.

If I hit save, angular will rebuild automatically.

There are no errors in the developer tools window and I do not see any in the output logs either.

- VSCode Version: 1.35.0
- OS Version: Windows 10 10.0.17763 Build 17763

Steps to Reproduce:
1. Start debugging Angular App in Debugger for Chrome (have not been able to try it without debugging yet)
2. After a while tslint stops, formatting code stops, intellisense doesn't work, etc.

I have disabled all except chrome debugging and tslint and still having the issue.

**Comment by roblourens** [comment]
Does this only happen when you are debugging, or does it happen when developing normally?

When stuff breaks, do you see some process using high cpu in task manager?

You can also try out our Insiders build to see whether it still happens there: https://code.visualstudio.com/insiders

**Comment by Godrules500** [comment]
Hey @roblourens just found out it also happens when developing normally and with it **not** debugging as well. 

Not really. my cpu is at 20% and memory at 72%.

**Comment by roblourens** [comment]
Most likely some extension is causing the extension host process to crash. If you start with the `--disable-extensions` flag, do you still see this issue?
