### ISSUE TITLE
$tsc-watch problemMatcher overwrites errors in Problems view when offending file is opened

### ISSUE THREAD

**Issue by erinha** [microsoft/vscode#75348]
- VSCode Version: 1.35.0 (system setup)
- OS Version: Windows_NT x64 10.0.17134
- TS Version: 3.5.1

With this tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Custom watch",
            "type": "npm",
            "script": "watch",
            "problemMatcher": {
                "owner": "typescript",
                "base": "$tsc-watch",
                "applyTo": "allDocuments",
                "source": "EG",
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": {
                        "regexp": "^\\[\\s*\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)?\\](?: Starting compilation in watch mode\\.\\.\\.| File change detected\\. Starting incremental compilation\\.\\.\\.)?"
                    },
                    "endsPattern": {
                        "regexp": "^\\[\\s*\\d{1,2}:\\d{1,2}:\\d{1,2}(?: AM| PM)?\\] (.*)Watching for file changes\\."
                    }
                },
                "fileLocation": "relative",
                "pattern": {
                    "regexp": "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "code": 5,
                    "message": 6
                }
            },
            "isBackground": true
        }
    ]
}
```

This index.ts:
```
import { echo } from "./helper";

function sayHi(): void {
    console.log("Hi");
    console.log(echo("bye"));
}

sayHi();
```

This helper.ts:
```
export function echo(): string {
    const input: string = "blah";
    return `Echoing: ${input}.`;
}
```

1. With index.ts closed, run the Custom watch task 
2. The Problems view shows the TS compiler error, notably with EG(2554) as the error code, indicating the source is from the Custom watch task problemMatcher. Click on the error to open index.ts.
3. The Problems view now shows one TS compiler error, with ts(2554), indicating the source is from the $tsc problemMatcher.
4. Closing the file (without fixing the error) clears the error from the Problems list, even though the Custom watch task has applyTo: allDocuments property. 
5. If I set the owner to be "nottypescript", then the error appears twice in the Problems view and the one generated by my Custom watch problemMatcher remains when I close the file without fixing the error.

The Problems view should not be overwritten by the $tsc problemMatcher (as in step 3). 

I want the Custom watch task behavior to overwrite the built-in TS task behavior, which is why I set the owner to be typescript so that I can have the error remain as long the error exists, whether or not the file is open. (Ideally, the typescript task would apply to all files, not just open ones in the workspace.)

I also have a reprorepo here where the issue occurs: https://github.com/erinha/reprorepo

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur with the Insiders build? Yes:
Version: 1.36.0-insider (user setup)
Commit: f291714906cdcb02830b8cfe2485a3c23415b5fe
Date: 2019-06-12T05:19:53.054Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
Feature request to merge problems with the same source and somehow know which provider "wins" when it comes to removing the problem.

**Comment by alexr00** [comment]
Can you just turn off typescript validation: `	"typescript.validate.enable": false`? 
If you don't want that for every project, you could put in the project specific settings.
