### ISSUE TITLE
Variables pane does not update after changing value via debug console

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#75359]
Issue Type: <b>Bug</b>
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
powershell|ms-|2019.5.0
vscode-docker|Pet|0.6.2
code-spell-checker|str|1.7.16

</details>

I am from the python extension team. I have investigated this issue on the extension side. The pyhton debug adapter does not get a variables request after a evaluating code via the debug console.

Repro steps:
1. Create a python file with this content:
```py
a = 1
print(a) # set breakpoint here
```
2. After hitting the breakpoint, open debug console and change the value of `a`
3. Variables panel is not updated.

![image](https://user-images.githubusercontent.com/3840081/59377501-37163300-8d07-11e9-8dc6-17a1543f866d.png)

Logs from the debug adapter
```
D00027.812: IDE --> {
                "command": "evaluate",
                "arguments": {
                    "expression": "a=5",
                    "frameId": 2,
                    "context": "repl"
                },
                "type": "request",
                "seq": 15
            }

D00027.828: (while handling {'command': 'evaluate', 'type': 'request', 'seq': 15})
            IDE <-- {
                "type": "response",
                "seq": 20,
                "request_seq": 15,
                "success": true,
                "command": "evaluate",
                "message": "",
                "body": {
                    "result": "",
                    "variablesReference": 0,
                    "presentationHint": {}
                }
            }

D00031.844: IDE --> {
                "command": "disconnect",
                "arguments": {
                    "restart": false
                },
                "type": "request",
                "seq": 16
            }
```

I have looked at the following issues:
https://github.com/microsoft/vscode/issues/2399
https://github.com/microsoft/vscode/issues/15520

we are not doing any variable caching on the debug server.

**Comment by isidorn** [comment]
Try it out in vscode insiders from Wednsdeay and let us know how it behaves for you.
Due to the node limitation specified #15520 we had to introduce some workaround in the variables view (when a variable is changed in the variables view we do not refresh the whole view).
Though this issue as described here should be fixed now.
