### ISSUE TITLE
Allow hiding the git sync status bar button but keep the branch

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75354]
Right now you can hide show them together, but not individually:

<img width="98" alt="Screen Shot 2019-06-12 at 10 02 04 AM" src="https://user-images.githubusercontent.com/2193314/59371209-39719080-8cf9-11e9-97b0-b26e48ad5f55.png">

I don't use the sync but do use the branch indicator.

/cc @bpasero

**Comment by bpasero** [comment]
@joaomoreno I was not seeing the for loop over the commands. This is easy to fix if we can come up with a combination of id/name for each command when calling `statusbarService.addEntry`. Do you have a suggestion? If I use `c.tooltip`, it would look like this:

![image](https://user-images.githubusercontent.com/900690/59373205-7e251800-8d49-11e9-97a3-f394b52a82bb.png)

However, `tooltip` is also optional and I am not sure if extensions contribute too.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/59486703-84ff7800-8e7a-11e9-842b-b5c8b5e0ba46.png)

**Comment by bpasero** [comment]
Had to revert, I have no reliable way of getting a good ID for the status entries with the current API.

**Comment by nikitavoloboev** [comment]
Is this something I can help do or there is some limitation in the API?

**Comment by usernamehw** [comment]
Workaround is:
```js
"git.enableStatusBarSync": false,
```
But it still would be great to be able to hide individual status bar entries contributed by single extension.
