### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by kameronperkins** [microsoft/vscode#75350]
Issue Type: <b>Bug</b>

VS Code seems to be stuck in an update loop. I follow the notifications to apply latest update by clicking update now, but nothing happens. I restart VS Code and the notification prompts again to update to latest version. 

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (16.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.8.2
vscode-npm-script|eg2|0.3.7
auto-close-tag|for|0.5.6
vscode-colorize|kam|0.8.10
chat|kar|0.15.4
csharp|ms-|1.19.1
Go|ms-|0.10.2
vsliveshare|ms-|1.0.379
vsliveshare-audio|ms-|0.1.50
vsliveshare-pack|ms-|0.3.2
vscode-docker|Pet|0.6.2
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.16
vscodeintellicode|Vis|1.1.6

</details>

**Comment by joaomoreno** [comment]
Can you check https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

**Comment by kameronperkins** [comment]
I ended up reinstalling vs code which seems to have resolved the issue.
