### ISSUE TITLE
ERR EMFILE: too many open file and workbench.main.js:3311 Extension Host error

### ISSUE THREAD

**Issue by devmrh** [microsoft/vscode#75352]
i have this problem since i update vscode to version 1.35 ,its about err emfile and [uncaught exception]: Error: read ECONNRESET error you can see full error in below image.

 why this happen and how can i fix this?

[https://my.pcloud.com/publink/show?code=XZju1N7ZQOPcEgCrlm0RJtQPTwC86uNgOMp7](https://my.pcloud.com/publink/show?code=XZju1N7ZQOPcEgCrlm0RJtQPTwC86uNgOMp7)

- VSCode Version: 1.35
- OS Version: Arch linux

**Comment by Tyriar** [comment]
Can you try increase your file watch limit? https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
