### ISSUE TITLE
openExternal doesn't open files with query

### ISSUE THREAD

**Issue by TobiahZ** [microsoft/vscode#75356]
I have an extension that lets you search the documentation by opening a web browser with the user's selection as a search query. I would like to add the feature to open from the web or from a local folder.

Example: Web uses `"http://some.url.com/search.html?q=SearchForThis"`, where local documentation would use `"file:///C:/Program%20Files/Folder/search.html?q=SearchForThis"`

Using `await vscode.env.openExternal(vscode.Uri.parse(s as string));` works as expected. Specifically, `vscode.Uri.parse("http://some.url.com/search.html?q=SearchForThis" as string);` is able to parse a uri that has a valid uri.query (for example, the query value is correctly `q=SearchForThis`)

**However**, `await vscode.env.openExternal(vscode.Uri.file("C:/Program Files/Folder/search.html?q=SearchForThis" as string));` does not work as expected.

The uri returned from vscode.Uri.file has `""` set for its query. Example:

```Javascript
	var uri = vscode.Uri.file("C:/Program Files/Folder/search.html?q=SearchForThis" as string);
	// uri has has query value of ""
	await vscode.env.openExternal(uri); //does not work/nothing happens
```

When I then try to run `vscode.env.openExternal(uri)`, nothing happens.

If I remove the query from the uri string, it will load the web page correctly.
Example: `await vscode.env.openExternal(vscode.Uri.file("C:/Program Files/Folder/search.html" as string));`

Even if I then modify the URI to add a query, the web page will still open the local html but will not include the `?q=SearchForThis`. Example:

```Javascript
	var uri = vscode.Uri.file("C:/Program Files/Folder/search.html" as string);
	// url is confirmed to have a query value of ""
	var new_uri = uri.with({ query: 'q=SearchForThis' });
	// new_url is confirmed to have a query value of "q=SearchForThis"
	await vscode.env.openExternal(new_uri); //Will load webpage with uri, "q=SearchForThis" will be missing
```

Version: 1.35.0 (system setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

See above.

```Javascript
	var uri = vscode.Uri.file("C:/Program Files/Folder/search.html?q=SearchForThis" as string);
	// url is confirmed to have a query value of ""
	await vscode.env.openExternal(uri); //Will not load anything/nothing happens.

	var fixed_uri = uri.with({ query: 'q=SearchForThis' }); 
	//fixed_uri has correct query value now
	await vscode.env.openExternal(uri); //Will also not load anything/nothing happens.

	var blank_uri = vscode.Uri.file("C:/Program Files/Folder/search.html" as string);
	await vscode.env.openExternal(blank_uri); //Will load local webpage in browser as expected.

	var query_uri = blank_uri.with({ query: 'q=SearchForThis' }); 
	//query_uri has correct query value now
	await vscode.env.openExternal(query_uri ); //Will load webpage with uri, however "q=SearchForThis" will be missing
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by TobiahZ** [comment]
Also, FYI, if I try to use the parse route for a local file, I have the same issues.

```Javascript
	var uri = vscode.Uri.parse("file:///C:/Program Files/Folder/search.html?q=SearchForThis" as string);
	//uri has correct query value
	await vscode.env.openExternal(uri); //WIll load webpage, however query value "?q=SearchForThis" is missing.
```

**Comment by jrieken** [comment]
Little we can do - under the hood this API is used https://electronjs.org/docs/api/shell#shellopenexternalurl-options. I suggest to forward this issue to electron and/or try this with another OS
