### ISSUE TITLE
Auto import fix inserts text when not necessary

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#75358]
Issue Type: <b>Bug</b>

1. In a ts file, use something that needs to be imported from another file.
2. See squiggly on that word, place cursor in the middle of the word.
3. Run cmd . to bring up suggestions and choose the fix to auto import it

Expected:
Import is added and text is not modified

Actual:
The text of what is being imported is inserted at the cursor position

![auto_import](https://user-images.githubusercontent.com/3672607/59377350-e30b4e80-8d06-11e9-8e50-be7a23eb53ce.gif)

VS Code version: Code - Insiders 1.36.0-insider (f291714906cdcb02830b8cfe2485a3c23415b5fe, 2019-06-12T05:18:48.847Z)
OS version: Darwin x64 18.6.0

**Comment by mjbvz** [comment]
I believe this is the same core issue as #58597/#10266. Our behavior about suggest replacements is currently not consistent across languages
