### ISSUE TITLE
Implement editor model content hashing

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7535]
Related to #7169

In order to be able to correctly restore an undo stack upon a model, we need to unequivocally know whether the file contents have changed since the undo stack was serialised. The only way is using content hashing.

Implementing content hashing could be performed in a way that improves performance overall, especially in loading a file's contents from disk.

- [x] Implement `IFileService.resolveContentAsStream`. This will let us receive chunks of the file's contents in a stream interface, instead of a big `string`.
- [x] Implement a `ModuleBuilder` which would be able to build a model given such a stream and compute its hash on the fly.

**Comment by bpasero** [comment]
Think this is done?
