### ISSUE TITLE
Can't open internal terminal

### ISSUE THREAD

**Issue by vindega** [microsoft/vscode#75360]
Issue Type: <b>Bug</b>

The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 259)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (12.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.11.3

</details>

**Comment by Tyriar** [comment]
Can you try enabling trace logging and see what it logs when you launch? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

Also can you share your settings.json file?
