### ISSUE TITLE
Find in Files: files to include ignores regexp only on subfolders

### ISSUE THREAD

**Issue by debradley** [microsoft/vscode#75364]
Issue Type: <b>Bug</b>

1. Given a root project folder, with subfolders, that contains a mixture of file types as leaves (.rb, .haml, .scss, .js, etc.) i.e. any real project
1. From Explorer View, right-click on the root project folder and select Find in Folder...
1. Enter a search term that appears in multiple file types
1. In "files to include", limit the search to a particular file type, i.e. "./myproject,*.rb"
1. See correct results
1. Change the folder to any subfolder either by manually changing "files to include" or by going back to Explorer and right-clicking a subfolder and choosing Find in Folder
1. As before, limit the search to a particular file type, i.e. "./myproject/subfolder,*.rb"
1. See that the results now ignore the file extension regexp and include results across all filetypes

I believe that this behavior began with the January update, possibly related to changes to filtering in the explorer pane?

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (3.48GB free)|
|Process Argv|-psn_0_11881300|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
erb|Cra|0.0.1
prettier-eslint-vscode|Rob|0.7.1
better-comments|aar|2.0.5
jest-snippets|and|1.7.0
react-pure-to-class-vscode|ang|1.1.8
react-food-truck|bur|1.0.2
simple-react-snippets|bur|1.2.2
vscode-exports-autocomplete|cap|0.5.4
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
rails-test-runner|dav|0.0.4
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.9.0
prettier-vscode|esb|1.9.0
code-runner|for|0.9.11
css2react|got|0.0.8
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.26
haml|kar|1.2.0
racket|kar|0.0.3
theme-karyfoundation-themes|kar|18.2.1
vscode-rubycommentdoc|mat|1.0.1
vscode-rufo|mbe|0.1.1
ruby-symbols|mig|0.1.7
ruby-rubocop|mis|0.8.1
vscode-postcss-sorting|mrm|3.0.1
python|ms-|2019.5.18875
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.3
vscode-jest|Ort|2.9.2
vscode-react-refactor|pla|1.0.4
ruby|reb|0.23.0
stylelint|shi|0.51.0
slim|sia|0.1.2
vscode-fileutils|sle|2.14.5
rails-snippets|Ven|0.4.5
vscode-icons|vsc|8.7.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.3.1

(6 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I see this also happening for `./myproject,*.rb"` which is what I expect. The comma basically gives an "or", not an "and". For what you want, you can use something like `./myproject/**/*.rb"`

**Comment by snowape** [comment]
Thanks for the investigation and clarification. This is a change in behavior that I didn’t see in any patch notes (but may have overlooked, of course).
