### ISSUE TITLE
AI / ML intellisense when patterns are recognized.

### ISSUE THREAD

**Issue by eljefe223** [microsoft/vscode#75368]
Occasionally as engineers we have tedious tasks where we repeat actions / patterns over and over again. It would be great is VS Code intellisense started to recognize a repeated action and start feeding the next step in that pattern into intellisense.

For example: In one of our projects we decided to update a file extension from a .json file to .ts file with a default export. I then would go into each index file of that directory and import  with a name and export that name  (these json files were not previously imported and exported so was not a matter of simply update the file reference). I found the intellisense to not be very good at recognizing the patterns I was repeated frequently.

Could intellisense be smarter and recommend names for imports based on repeated patterns?
Could intellisense know that you just created a new file and know that you are likely trying to import from that recently created file?
Another way to solve the problem would be a way to record actions like Photoshop allows you to do.

**Comment by mjbvz** [comment]
Checkout the intellicode extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

It is looking to do pretty much exactly what you describe. You can file feedback and suggestions [here](https://github.com/MicrosoftDocs/intellicode/issues)
