### ISSUE TITLE
Environment variables in integrated Powershell terminal are not updated when opened from "Recent Workspaces" taskbar menu

### ISSUE THREAD

**Issue by jonscheiding** [microsoft/vscode#75369]
This issue is mentioned in #47816, but I wanted to report it separately as a bug, since I don't think it's by design and it's kind of unrelated to the feature request in that issue.

The issue mentions:

> if you open your workspaces using links under Recent, you will find that even after restarting VSCode, the environment variables are not updated.

To make it clearer, here is the repro scenario:

1. Open VS Code.
2. Pin it to the taskbar.
3. Click File -> Open Folder... and choose some folder.
4. In a VS Code powershell terminal, run `Get-ChildItem Env:` and make note of the variables that appear.
5. Close VS Code (all windows).
6. Add an environment variable to the system via the Control Panel.
7. Right click on the VS Code taskbar icon and choose the folder you opened in (3) from "Recent Workspaces".
8. In a VS Code powershell terminal, run `Get-ChildItem Env:` again.

Expected behavior: the new environment variable from (6) appears in the output of (8).
Actual behavior: it doesn't.

Workarounds:

- Launch VS Code without using the "Recent Workspaces" link, and then open the folder.  This gets it to update.
- I assume that rebooting will update it, but I did not test that.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.0
ng-template|Ang|0.800.0
angulardoc-vscode|Ang|6.1.3
cform|aws|0.0.23
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.0.14
better-toml|bun|0.3.2
solargraph|cas|0.19.6
npm-intellisense|chr|1.3.0
jira-issues|crh|1.1.0
angular2-snippets|dan|1.0.21
vscode-markdownlint|Dav|0.27.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
javascript-ejs-support|Dig|0.5.0
xml|Dot|2.5.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-diff|fab|1.4.0
fontsize-shortcuts|fos|1.5.0
vscode-perl|hen|1.17.0
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
compareit|in4|0.0.2
angular2-switcher|inf|0.2.0
path-autocomplete|ion|1.13.3
vscode-nuget-package-manager|jmr|1.1.6
Angular2|joh|8.1.1
vscode-styled-components|jpo|0.0.26
vscode-styled-components-snippets|lXS|1.0.2
Kotlin|mat|1.7.0
terraform|mau|1.3.12
markdown-shortcuts|mdi|0.11.0
rainbow-csv|mec|1.1.1
sort-typescript-imports|mic|1.4.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.379
angular2-inline|nat|0.0.17
language-vscode-javascript-angular2|nwa|0.0.11
vscode-docker|Pet|0.6.2
typescript-hero|rbb|3.0.0
ruby|reb|0.23.0
java|red|0.46.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.2.9
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
twig|wha|1.0.2

</details>

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/47816

@bpasero are you aware of anything weird happen with vscode's env when you open a recent workspace from the jumplist? Is this a feature? 🤔

**Comment by bpasero** [comment]
@Tyriar I recall another discussion where this came up, not sure in which issue. I am not sure why the environment would be any different when you run from the jump list. Is this with a folder or with a VSCode workspace?

**Comment by jonscheiding** [comment]
@bpasero My scenario is with a plain folder. I haven’t confirmed whether it reproduces with a workspace.

**Comment by ngxson** [comment]
Still haven't been fixed yet

**Comment by thisisbinod** [comment]
I have a  similar issue. If I open a workspace from "Recent Workspaces" shortcut in Windows taskbar, then non of the cli applications under %APPDATA%/npm work in the integrated PS terminal. If I start VS Code and open a workspace from File menu then all of the clis in the npm folder works fine.
