### ISSUE TITLE
Update default value for terminal.integrated.inheritEnv

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75377]
Introduced in https://github.com/microsoft/vscode/issues/70248, we should switch the default to `isWindows` (or `false`) after warning users in the release notes, provided it all works as expected. In July or August probably?

**Comment by DonJayamanne** [comment]
Will test at my end and get back to you.

**Comment by DonJayamanne** [comment]
Tested at my end and works as expected.

**Comment by Tyriar** [comment]
@DonJayamanne cool, let me know if any Python users have problems with it

**Comment by Tyriar** [comment]
Maybe the default should be `!!remoteAuthority` since false in remote now means it will pull the server's env, not the ext host's.

**Comment by Tyriar** [comment]
Not changing for now, there are some issues with it.
