### ISSUE TITLE
launch.json preLaunchTask causes issues with userDataDir

### ISSUE THREAD

**Issue by Nibblesh** [microsoft/vscode#75379]
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-21-generic

Steps to Reproduce:

Using this launch.json config works

```json
{
  "version": "0.2.0",
  "configurations": [
    {
        "name": "Debug - Chrome",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceRoot}/src",
        "userDataDir": "${workspaceRoot}/.chrome-vscode-debug-profile"
    }
  ]
}
```

adding a preLaunchTask makes userDataDir ignored.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
        "name": "Debug - Chrome",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceRoot}/src",
        "userDataDir": "${workspaceRoot}/.chrome-vscode-debug-profile",
        "preLaunchTask": "npm: start"
    }
  ]
}
```

With the second configuration a new tab is launched in the currently running (default) chrome instance rather than launching a new instance with the specified userDataDir

Does this issue occur when all extensions are disabled?: Yes/No
requires using chrome debug extension

**Comment by roblourens** [comment]
I can't reproduce this, I don't think those two things are related. Is it possible that the currently running instance is just an instance of chrome running out of the user data dir from a previous run?

Also, now I recommend using `"userDataDir": true`, which is actually the default, so you don't have to keep the profile in your workspace.
