### ISSUE TITLE
Failed to Replace Carriage-return Character in Batch

### ISSUE THREAD

**Issue by eliu** [microsoft/vscode#75381]
- VSCode Version: 1.35.1
- OS Version: macOS Mojave

Steps to Reproduce:

1. Open a folder that contains more than one flat files in Windows style (CRLF)
2. SHIFT + COMMAND + H open find & replace sidebar
3. Enter '\r' and select Regex mode
4. Click replace all button, select Yes when confirm dialog opens.
5. Re-do the previous steps and you'll see there's nothing replaced or partially replaced just now

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Yes, the editor doesn't support finding `\r` because it normalizes newlines, and replace is executed by the editor. We have https://github.com/microsoft/vscode/issues/31449 for this.
