### ISSUE TITLE
VS Code Crash and delete all of my project files automaticall

### ISSUE THREAD

**Issue by fengchutadie** [microsoft/vscode#75384]
- VSCode Version: 1.34
- OS Version: windows 7

Steps to Reproduce:

1. create 'workspace' in VS Code root dir and add python projects in workspace
2. when running VS Code for several days, VS code will crash and delete all files in workspace but project dir remains
3. VS Code root hierarchy will change, it'll create new dir named '_' and many files will be removed to it.
hierarchy as below:
    1. '-'
    2. bin
    3. locales
    4. tools
    5. workspace
    6. uniss000.dat
    7. unins000.exe
    8. unins000.msg

other files have been removed to '-'.

It has happened twice with the same issue.

Does this issue occur when all extensions are disabled?: Not Sure

**Comment by Tyriar** [comment]
What extensions do you have installed?

**Comment by fengchutadie** [comment]
> What extensions do you have installed?

1. Beautify 1.5.0
2. C/C++ 0.23.1
3. Debugger for Chrome 4.11.4
4. Markdown All in one 2.4.0
5. Markdown Preview Enhanced 0.4.1
6. Python 2019.5.18875
7. Rainbow CSV 1.1.1
8. yo 0.9.3

**Comment by fengchutadie** [comment]
> What extensions do you have installed?

I get this crash again.
When I uninstall a plugin, then close VS code.
After servral seconds, VS Code restarts itself and then report error as below。
![crash error](https://user-images.githubusercontent.com/31133009/60634366-46d5f280-9e41-11e9-844f-44b13a59dd69.png)

Then all of my projects are removed, MY GOD

**Comment by fengchutadie** [comment]
It seems I open VS Code mannully when it'll restart.
But it shouldn't delete my projects.

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76567

In this case it sounds like you have put workspaces into the installation directory of VSCode. That directory should not be used as it will get deleted during updates.

//cc @joaomoreno
