### ISSUE TITLE
font rendering issue after upgrading to electron 4.x

### ISSUE THREAD

**Issue by yisiqi** [microsoft/vscode#75380]
- VSCode Version: 1.36.0 - Insiders (2019-06-12T19:40:38.592Z)
- OS Version: macOS mojave 10.14.5

The font is rendered too thin on the retina display. The previous solution didn't work. Significantly different from the stable version rendering

I thought this problem will be solved after upgrading to electron 4.x.

<img width="1185" alt="屏幕快照 2019-06-13 上午9 26 52" src="https://user-images.githubusercontent.com/1735804/59396951-70a97580-8dbd-11e9-8afb-38ac94c071a6.png">
<img width="1185" alt="屏幕快照 2019-06-13 上午9 26 55" src="https://user-images.githubusercontent.com/1735804/59396952-70a97580-8dbd-11e9-9d4e-3dd88cbdebad.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Possibly related: https://github.com/electron/electron/pull/15007

**Comment by deepak1556** [comment]
I am merging this into https://github.com/Microsoft/vscode/issues/59887 , @yisiqi can you comment on that issue with data from https://github.com/Microsoft/vscode/issues/59887#issuecomment-503277698 . Thanks!
