### ISSUE TITLE
Terminal default width breaks task problem matching

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#75385]
When the terminal is not opened, it appears to get a default width. This default width is narrower than some build output lines, which causes the lines to wrap and break problem matching.
```
data: [?25l[H[80X[80C
[80X[80C
[11:53:19 AM] Found 3 errors. Watching for file changes.[24X[24C
[80X[80C
[11:53:29 AM] File change detected. Starting incremental compilation...[9X[9C
[80X[80C
src/extension.ts:15:26 - error TS2551: Property 'comands' does not exist on type
 'typeof 'vscode''. Did you mean 'commands'?[36X[36C
[80X[80C
15  let disposable = vscode.comands.registerCommand('extension.helloWorld', () =
> {[77X[77C
                            ~~~~~~~[45X[45C
```

**Comment by Tyriar** [comment]
This situation was improved recently, the default width of 80 will be used when the terminal has not been opened, but when it has it will use the last known good width. This still has potential to break wrapped lines sometimes on Windows but I don't think we can or should do anything about that.
