### ISSUE TITLE
Terminal does not show the path suddenly

### ISSUE THREAD

**Issue by mharteens** [microsoft/vscode#75389]
Issue Type: <b>Bug</b>

Hello, I got a problem in Visual Studio Code installed in Windows 10.
The path in terminal (located in the below part) suddenly disappeared after I wrote some text (e.g. "git status", etc.). It comes again after I press new line (Enter key)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763
![2019-06-13_14h32_04](https://user-images.githubusercontent.com/12076620/59406402-073f5c00-8de9-11e9-8cf7-1875b45ade1c.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (21.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
c-cpp-compile-run|dan|0.5.0
gitlens|eam|9.8.2
vscode-solution-explorer|fer|0.3.4
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
trailing-spaces|sha|0.3.1
![2019-06-13_14h32_04](https://user-images.githubusercontent.com/12076620/59406413-18886880-8de9-11e9-9eb6-ddc32fcd1da1.png)

cmake-tools|vec|1.1.3

</details>

**Comment by TechPriest** [comment]
Can confirm. Also, prompt shows itself normally after "cls"

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
