### ISSUE TITLE
Unable to make font zoom levels persistent

### ISSUE THREAD

**Issue by sabriele** [microsoft/vscode#75397]
Hi, I currently have the following keybindings set to adjust my **font zoom levels**:

![image](https://user-images.githubusercontent.com/4678102/59412086-4670ab80-8def-11e9-9587-5f0e39d01fea.png)

At the moment, whenever I open a new file in the same window where the **font zoom levels** have been adjusted, the zoom levels are preserved; however, when I open a new window or workspace, the **font zoom levels** in the new window/workspace revert to the default value. This is unlike the behaviour of **window zoom levels** which are preserved even when you open new windows/restart VSCode. 

I believe that this may have something to do with the existence of `window.zoomLevel` in settings. Is there a corresponding setting for **font zoom levels** in settings (perhaps something like `"editor.font.zoomLevel": 2`), or is there another way I should go about to make my **font zoom levels** persistent?

Thank you!

-------

- VSCode Version: 1.35.0
- OS Version: MacOS 10.14.5 (18F203)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@sabriele The font zooming is just a temporary multiplier to `editor.fontSize` and to `editor.lineHeight`. So simply change `editor.fontSize` in your user `settings.json`... Would that work for you?

**Comment by sabriele** [comment]
@alexandrudima 🤦🏻‍♀️Oh my goodness I didn't think of that. Thanks for explaining to me how font zooming works though, I understand it now!
