### ISSUE TITLE
Cannot support Unicode or Chinese characters!

### ISSUE THREAD

**Issue by hez2010** [Microsoft/vscode#7539]
- VSCode Version:1.2.0
- OS Version: Windows 10 1511

Steps to Reproduce:

1. install C++ extension
2. create a c++ file with blankspace or Unicode or Chinese character in the filedir or filename
3. compile by using vscode command (use my own compiling batch script which will echo the filename)
4. garbled characters appear in the output panel, and cannot debug normally(cannot open source code file when meet the breakpoint)

This illustrates that VSCode can not support Unicode or Chinese character completely. Please add complete support to those character. Thank u!

![8888](https://cloud.githubusercontent.com/assets/14960345/15968264/ccee5db8-2f5d-11e6-94bd-2c9c277fd748.PNG)

compiling batch script code:
`@echo off
rem ----config----
set directory="C:\Program Files (x86)\MinGW64"
rem --------------

echo Compiling...
set "directory=%directory:"=%"

if exist "%directory%\bin\g++.exe" (
path="%directory%\bin"
cd /d "%directory%"
echo MinGW64 Directory: "%directory%"
echo g++.exe %1 -o %2 -g3
bin\g++.exe %1 -o %2 -g3
echo Complete!
exit
)

echo Please correctly config the MinGW64 Directory in Compile.bat!
`

launch.json:
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch (GDB)",
            "type": "cppdbg",
            "request": "launch",
            "launchOptionType": "Local",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "miDebuggerPath": "C:\\Program Files (x86)\\MinGW64\\bin\\gdb.exe"
        }
    ]
}
`

tasks.json:
`{
    "version": "0.1.0",
    "command": "${workspaceRoot}\\.vscode\\Compile.bat",
    "isShellCommand": true,
    "args": ["${file}","${workspaceRoot}\\a.exe"],
    "showOutput": "always"
}`

**Comment by dbaeumer** [comment]
Dups #3550.
