### ISSUE TITLE
source contral does not work any more in latest version?

### ISSUE THREAD

**Issue by zsj0613** [microsoft/vscode#75395]
Issue Type: <b>Bug</b>

version 1.36.0

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:19:34.516Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-119-generic

**Comment by henrysachs** [comment]
same here

**Comment by gjsjohnmurray** [comment]
See also #75411 which gives a more detailed description. See also [this comment from me](https://github.com/microsoft/vscode/issues/75411#issuecomment-501653472) there. @zsj0613 @henrysachs do your workspaces have the `"git.enabled": false` setting? I found that setting had mysteriously appeared in a couple of my .code-workspace files that previously worked fine with git.

**Comment by brunorzn** [comment]
same here
