### ISSUE TITLE
Option to not suggest content in comment

### ISSUE THREAD

**Issue by ZeZerT** [microsoft/vscode#75393]
Hi,

Here is my request, as an **option** for the suggestions : **allowing or not the content of comments to be suggested**.

![Screen Shot 06-13-19 at 09 07 AM](https://user-images.githubusercontent.com/10897370/59411076-c0d30880-8dba-11e9-8051-339becc2d472.PNG)

In the example given, i'd like the "abcdefgh" to not be suggested since its a comment.
One of the reason being that in this context it shadows the add() function.

Thanks in advance for considering it !

**Comment by gjsjohnmurray** [comment]
@ZeZerT what language mode is your Untitled-1 document using? See the right-hand end of the status bar for the language mode indicator and selector.

**Comment by ZeZerT** [comment]
In this exact example i set the language to c#. 
This behavior has happened with all the languages i've used in VSCode so far (lua, vba), as far as i remember.

**Comment by mjbvz** [comment]
Those are word base suggestions. They are computer from words in the current document and show up if there are no other suggestions available.

Set `"editor.wordBasedSuggestions": false` to disable them

**Comment by ZeZerT** [comment]
> Those are word base suggestions. They are computer from words in the current document and show up if there are no other suggestions available.
> 
> Set `"editor.wordBasedSuggestions": false` to disable them

Yes i get that, but i dont want to completely disable the suggestions, i just dont want suggestions from words that are in comments. 
Thats why i made this feature request.

**Comment by gjsjohnmurray** [comment]
@ZeZerT AFAIK the part of VSCode that provides word based suggestions is language agnostic, so has no notion of what is a comment and what isn't. It's the job of language servers (i.e. extensions) to understand that sort of thing and factor the knowledge in when deciding what completions to propose.

**Comment by ZeZerT** [comment]
> @ZeZerT AFAIK the part of VSCode that provides word based suggestions is language agnostic, so has no notion of what is a comment and what isn't. It's the job of language servers (i.e. extensions) to understand that sort of thing and factor the knowledge in when deciding what completions to propose.

Okay, thanks a lot for the detailed answer, i understand now that its not VSCode itself that would manage my request.

Thanks again !
