### ISSUE TITLE
Dark cursor is hard to see on dark background & text color

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#754]
I'm using Visual Studio Code 0.10.2 on Mac OS X 10.11.1 El Capitan. On my external monitor, the viewing angle sometimes makes it impossible to see the dark cursor on top of the dark Visual Studio Code background color.

Could we figure out some way to make the cursor more visible in VS Code?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by Tyriar** [comment]
There are other themes available in the command palette which feature different background colors: `cmd+shift+p` -> type `"theme"` > `enter`

**Comment by alexandrudima** [comment]
@pcgeek86 I can also only recommend a different theme. There are a lot of theme extensions already in the gallery.

**Comment by scastaldi** [comment]
in all the dark themes is difficult to see the cursor, and the other themes make you blind  :)
can we change the cursor to anything else other than black?
how about the default Visual Studio Theme? (Blue/White)

**Comment by Tyriar** [comment]
Perhaps I'm misunderstanding, but isn't this an OS X cursor issue? ([is it this one?](http://cdn.osxdaily.com/wp-content/uploads/2011/07/mac-cursor.jpg))

**Comment by alexandrudima** [comment]
Aha!

**Comment by takumif** [comment]
![screen shot 2015-12-14 at 5 55 35 pm](https://cloud.githubusercontent.com/assets/5505433/11796756/00d9eeee-a28c-11e5-9fb0-f45073a3e588.png)
![screen shot 2015-12-14 at 5 55 48 pm](https://cloud.githubusercontent.com/assets/5505433/11796764/0b6066d6-a28c-11e5-95d2-506d09c081b7.png)
Sublime inverts the color of the text cursor, which is easier to see. Maybe there should be a setting associated with themes to do this?

**Comment by alexandrudima** [comment]
@bpasero Do you know if electron supports to invert the color of the mouse cursor ?

**Comment by bpasero** [comment]
@alexandrudima not to my knowledge and in fact Atom is assigning a custom cursor when I last checked using CSS. What I dont like about that approach is that it seems impossible to put the correct size of the cursor depending on running in High DPI or not (retina).

**Comment by Tyriar** [comment]
@bpasero @alexandrudima Surely this doesn't reproduce on regular web pages with dark backgrounds on Chrome? Never heard of this being a problem as a web developer.

**Comment by bpasero** [comment]
@Tyriar I totally see it in Chrome too when using Cloud9 with a dark editor.

**Comment by elijnzaad** [comment]
I would like to support this feature request. Especially on a laptop the cursor is hard to spot when the weather conditions are slightly brighter than 'cloudy-with-rain'.

**Comment by ardan-bkennedy** [comment]
+1. This is a real problem.

**Comment by JonathanMEdwards** [comment]
+1 biggest usability problem for me

**Comment by ardan-bkennedy** [comment]
I increased the size of my cursor and it is helping for now.

**Comment by JonathanMEdwards** [comment]
Here is the fix in Atom: https://github.com/lee-dohm/white-cursor

**Comment by mbroadst** [comment]
:+1: this is highly annoying

**Comment by scastaldi** [comment]
I got the fix and I forgot to add the solution here :)
Open Control panel
Open Appearance and Personalization
Open Personalization
Finally – click Change mouse pointers. That will open this window:
mouse color scheme
Select the Scheme called – Windows Black (system scheme)

**Comment by mbroadst** [comment]
@scastaldi that seems like a windows-specific fix, I'm on osx. I think something like the above mentioned fix for atom might be a better way to go

**Comment by scastaldi** [comment]
@mbroadst I didn't have the cursor problem on my mac, but you can try: 
Choose Apple menu > System Preferences, then click Accessibility.
Click Display then drag the Cursor Size slider to the right to make it larger

You can also change the Display contrast to see if that helps, it seems MacOS removed the ability to change the mouse pointers, unless you install a another application like Mousecape

**Comment by tomasholub** [comment]
@scastaldi Thanks, it helped.
I am using VS Code from my Mac on Remote Desktop running Windows Server 2012.
There you can go to Control Panel and search for Mouse. You find Mouse Properties dialog and you can use the Pointer tab to change your mouse pointer to Windows Black.
---
BTW, when I am using VS Code directly on my Mac, the mouse pointer is somehow visible. But on MS Windows, it is (or was) much worse.

**Comment by jreadytalk** [comment]
For all of us +1's, someone [posted this request for vote on UserVoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9905172-invert-cursor-color-when-using-dark-theme).

**Comment by JVimes** [comment]
For those who are remoting into a machine, check if your remoting client has a setting like "show remote cursor pointer". That helped a lot for me (remoting from Windows into Mac using NoMachine).

**Comment by JonathanMEdwards** [comment]
This problem is so frustrating I hacked the source to fix it. See https://github.com/JonathanMEdwards/vscode

But I don't know how to package up a proper installation. I can run the dev version with the command: $HOME/Projects/vscode/.build/electron/Electron.app/Contents/MacOS/Electron /$HOME/Projects/vscode

Also note extension management seems to be disabled in this build - perhaps that is intentional in the dev build?

**Comment by mbroadst** [comment]
@JonathanMEdwards :+1: thanks!

**Comment by alexandrudima** [comment]
Thank you @JonathanMEdwards !

**Comment by agmcleod** [comment]
Was this fix put out in a release? Noticing this issue mainly on my mac screen, where as on an external monitor it's less of an issue. I tried switching between a couple default dark themes even, and the dark cursor is present.

**Comment by JonathanMEdwards** [comment]
It's out in the insider's release.
