### ISSUE TITLE
Bottom Blue bar is distracting.

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#75406]
Issue Type: <b>Feature Request</b>

Bottom Blue bar is distracting. Please change it to fit the theme.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Geobert** [comment]
It should change according to theme, I'm using a theme with another colour:
![image](https://user-images.githubusercontent.com/72570/59425981-ef5ade80-8dce-11e9-8987-b777aa488ea1.png)

**Comment by Tyriar** [comment]
Yes, just change the theme to something you like, or edit the status bar color with the `"workbench.colorCustomizations"` setting.
