### ISSUE TITLE
Autocomplete is completing in unnecessary situations

### ISSUE THREAD

**Issue by Goblinlordx** [microsoft/vscode#75408]
Issue Type: <b>Bug</b>

1. Open a new file (empty)
2. Set to javascript for type at bottom
3. Try to type "it("

The example is similar to typing an actual test in a jest test file like:
```
it("works", () => {})
```
Simply typing this example autocompletes with `instanceof(`.  This is with all extensions disabled and all my settings removed.  I have been getting autocompletes constantly like this when I am not trying to accept them and just typing normally (not even hitting enter).  This is really annoying default behavior.  I can't even work properly when it is autocompleting with completely unrelated things and adding imports that I can't even use automatically.

This did not start occurring until a recent update (not sure exactly when).
 
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Goblinlordx** [comment]
The linked issue is about autocomplete not working when pressing `tab`.  That is not what my issue is about at all.

**Comment by gjsjohnmurray** [comment]
You can disable accepting of a suggestion by commit characters by setting `"editor.acceptSuggestionOnCommitCharacter": false`

Language services get to specify what their commit characters are. For JS/TS they include `;` and `.` and `(` [(doc)](https://code.visualstudio.com/updates/v1_28#_semicolon-as-a-commit-character-for-jsts)
