### ISSUE TITLE
Text is not displayed after reset command on Integrated Terminal

### ISSUE THREAD

**Issue by fernando24164** [microsoft/vscode#75409]
- VSCode Version: 1.35.0
- OS Version:  xubuntu 16.04

Steps to Reproduce:

1. Open integrated terminal.
2. Type command reset.
3. After that, when typing on the terminal the commands are not displayed but the output behaves correctly 
 
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe related to #75021 which got fixed in 1.35.1 that just released. Please update to that and re-test.

**Comment by fernando24164** [comment]
Correct, I couldn't replicated it on 1.35.1
Thx!
