### ISSUE TITLE
Multi-caret pasting sometimes pastes the incorrect text when the number of lines being pasted matches the number of carets

### ISSUE THREAD

**Issue by liamlaverty** [microsoft/vscode#75407]
### Checked for similar reports: 
Yes, couldn't find any that match this one

### Still an issue in insiders?
yes, downloaded and ran it in the latest insiders build. The issue is there too

### Does this issue occur when all extensions are disabled?: 
Yes, ran `code --disable-extensions` and the issue is still there

### System & version details
Version: 1.35.0 (system setup)
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:17:12.481Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

### Steps to Reproduce:
Using the following text in any file:
```
p, h1,
h2,
h3 

a 

a 

a 
```

1. Copy the top 3 lines
2. Highlight the first `a` character
3. Using the `ctrl+D` command, select the other two `a` characters
4. Using `ctrl+v` command, paste the copied text into all three carets (also occurs when using the main menu's `Edit->Paste` command) 

### What I expected to see
the copied 
```
p, h1, 
h2, 
h3
``` 
in each line where the `a` characters used to be as so:
```
p, h1,
h2,
h3 

p, h1,
h2,
h3 

p, h1,
h2,
h3 
```

### What I actually saw
the `a`'s are replaced with each line of the copied code
```
p, h1,

h2,

h3 
```
![pastingbug](https://user-images.githubusercontent.com/7046713/59422409-3e514580-8dc8-11e9-8cc6-8f30ea7861b5.gif)

### More notes
The issue doesn't happen if the number of lines copied is different to the number of carets being pasted into. For example:
```
p, h1,
h2,
h3,
extra-line
```
pastes correctly as: 
```
p, h1,
h2,
h3,
extra-line 

p, h1,
h2,
h3,
extra-line 

p, h1,
h2,
h3,
extra-line
```
See example below:
![pastingbug-working](https://user-images.githubusercontent.com/7046713/59422644-9e47ec00-8dc8-11e9-9a97-f0f68bb12fd8.gif)

- The Find and Replace tools appear to work correctly in both circumstances
- The bug happens if you're pasting over text, or if you're pasting next to it
- The bug happens irrelevant of the contents of the line you're pasting into (the text can be different on all three lines). In the example below, you can multi-caret select `a-with`, then `shift + right-arrow` to the end of the line, and paste, the issue still appears

```
p, h1,
h2,
h3,

a-with-first-text

a-with-second-text

a-with-third-text
```

Let me know if I can provide any further details.

**Comment by alexandrudima** [comment]
Let's track in #80624
