### ISSUE TITLE
memery has been over occupied

### ISSUE THREAD

**Issue by Hehulk** [microsoft/vscode#75400]
i open my project of js,and memery has been over occupied,eslint and jslint is running
![image](https://user-images.githubusercontent.com/39331665/59415520-37412c00-8df6-11e9-8e79-e5985b66816c.png)
is that normal?

**Comment by Hehulk** [comment]
> /needsMoreInfo

info about project or VScode?

**Comment by mjbvz** [comment]
Please follow the linked guide when reporting issues. Your issue is missing a lot of basic info.

And [here's](https://github.com/Microsoft/vscode/wiki/Performance-Issues) how to report performance issues

Also does this happen when you disable all extensions
