### ISSUE TITLE
. not a suggest widget trigger character in typescript

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75402]
In the latest insiders `.` is not a trigger character that opens a suggest widget.
This was working yesterdays and works in stable.

Example repro, have a `hey.ts` file:
`console`
Now type `.` and notice how the suggest widget is not trigger.
This works fine in stable for me.

Adding important since regressions and breaks my flow a bit.

**Comment by jrieken** [comment]
Hm, works for me...

![Jun-13-2019 10-47-49](https://user-images.githubusercontent.com/1794099/59418104-b7e93380-8dc8-11e9-920e-a87b7ed4591b.gif)

**Comment by isidorn** [comment]
I can repro all the time. Let's see if more people complain..
@mjbvz  Also let me know if I can provide more useful info.

**Comment by gjsjohnmurray** [comment]
@isidorn I assume your `editor.suggestOnTriggerCharacters` setting hasn't somehow got flipped to `false`, right?

**Comment by isidorn** [comment]
@gjsjohnmurray nice idea, however I do not have this setting set, so I have the default value which is true.

**Comment by mjbvz** [comment]
@jrieken  I can repo this for the example code:

```
class Bar {
    public foo: number
}

const b = new Bar();

```

1. At the end of the file, type `b`
1. Then wait a moment and type `.`
1. No suggestions show up

Having trouble tracking down what is going on here but JS/TS never gets a request in this case.

**Comment by mjbvz** [comment]
Removing the `if (retrigger) {` conditional introduced in a7d510160d432dd9aa70f499b914dc7c76ef69c6 fixes this issue in my testing. @jrieken can you please take a look at what the proper fix would be

**Comment by jrieken** [comment]
Hm, this might be the same as https://github.com/microsoft/vscode/issues/75254 where we re-filter existing suggestions instead of starting a new session...

**Comment by jrieken** [comment]
I don't use accept character that's why this didin't reproduce for me... This is a regression from a7d5101 and will revert that change for now.
