### ISSUE TITLE
text line moving when saving and code not staying where I typed it. 

### ISSUE THREAD

**Issue by ismael755** [microsoft/vscode#75419]
need help fixing this. code doesn;t stay where I typed it. I noticed it when i first started the application.

**Comment by joelft** [comment]
I believe I have the same issue. If I am mistaken, I will open a separate issue.

What seems to be happening, is that when I save a file, it reverts to the state it was when I first opened it. This is only happening for one Go file in my case. The file is not opened in any other applications. It happens whether I do CTRL+S or click File>Save. 

All my other *.go files seem to be fine, and the issue appeared for me in version 1.35.1

**Comment by Tyriar** [comment]
Can you elaborate a little on the problem? Screenshots would help.

**Comment by ismael755** [comment]
![image](https://user-images.githubusercontent.com/28364860/59508962-ab72e280-8e7d-11e9-82da-c580db6f6d34.png)
This is before. You see the white typed lettering with number and time. That's how I want it.

**Comment by ismael755** [comment]
![image](https://user-images.githubusercontent.com/28364860/59509056-f55bc880-8e7d-11e9-9fc4-d5e319cff8c0.png)
And this is what it does. It did the same to my code and I redid it and the same way mind you but it didn't do it this time just any words I want to put on the website I want to stack it in the editor and when I save it, it moves from two lines to one line.

Not sure if you can help. I've check the settings to see if there is anything that I change bit didn't see anything.

**Comment by ismael755** [comment]
The version I'm on is 1.35.1

**Comment by Tyriar** [comment]
You probably have some extension that is formatting the file and/or you have format on save enabled in your settings.

**Comment by ismael755** [comment]
No none of that is on. I just downloaded this a week ago and with no settings changed or touched. Just to make sure that you said "that I have some extension or format on save is enabled" none of that is on.

**Comment by ismael755** [comment]
> 
> 
> You probably have some extension that is formatting the file and/or you have format on save enabled in your settings.

No I don't

**Comment by ismael755** [comment]
I just reinstalled the JS-CSS-HTML Formatter and typed my code and saved and it didn't move from where I typed it.

**Comment by octref** [comment]
@ismael755 You enabled "format on save" and autosave, probably.

VS Code ships with a HTML formatter (built on top of js-beautify). You can change its setting in `html.format.*`. This seems like a js-beautify bug.

**Comment by ismael755** [comment]
Ok thanks @octref
