### ISSUE TITLE
vsc file explorer do not sort alphanumeric

### ISSUE THREAD

**Issue by fenchu** [microsoft/vscode#75415]
Explorer do not sort alphanumeric. See enclosed image with both powershell and python default sorting:
![vsc_sorting](https://user-images.githubusercontent.com/11349883/59429029-220cd300-8ddf-11e9-9cb5-cf331e1c73f6.jpg)
```
VSC:   1.35.1
OS:
WindowsProductName    WindowsVersion  Os
------------------             --------------     --------------------------
Windows                          10 Enterprise      1809
```

**Comment by isidorn** [comment]
Use explorer.sortOrder setting
If that does not cover it there is alread ya feature request to give more sorting options. Find it and upvote please.
