### ISSUE TITLE
Provide terminal font ligature setting (disabled by default)

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7541]
I think...

![image](https://cloud.githubusercontent.com/assets/22350/15970061/0417147c-2f33-11e6-8623-e277b1e314df.png)

It does look a bit weird. 😕

**Comment by coreh** [comment]
Looks like my issue was fixed, then: #7268 (That one was requesting font ligatures on the terminal)

But I agree that maybe a separate setting would be nice.

**Comment by Tyriar** [comment]
@joaomoreno is this setting just inherited from the editor setting? Does it still work when turned off in editor?

**Comment by joaomoreno** [comment]
Can't answer due to #7605

**Comment by Tyriar** [comment]
Should be fixed by https://github.com/sourcelair/xterm.js/pull/138

**Comment by Tyriar** [comment]
Looking at July to pull in change from upstream and look into whether `font-variant-ligatures: none;` is better than the `font-feature-settings: "liga" 0;` being used upstream (see https://github.com/sourcelair/xterm.js/commit/4c6b99345875171c476a8e4d2f880e7372094060#commitcomment-17998829)

**Comment by joaomoreno** [comment]
The setting doesn't seem to do anything:

![image](https://cloud.githubusercontent.com/assets/22350/17207899/cf30c236-54b6-11e6-988e-153821af327c.png)

**Comment by Tyriar** [comment]
Weird...

![image](https://cloud.githubusercontent.com/assets/2193314/17223321/e31e2fe6-54b0-11e6-9697-365b20255ad7.png)

![image](https://cloud.githubusercontent.com/assets/2193314/17223335/fa27afbe-54b0-11e6-9db0-76dc89b1932b.png)

Will check on Mac.

**Comment by Tyriar** [comment]
On my Mac using hasklig with vscode at commit 531a56f772fc33ec88910328b88f4dbd7ae5df43 

<img width="428" alt="screen shot 2016-07-28 at 10 53 09 am" src="https://cloud.githubusercontent.com/assets/2193314/17223486/9f10556c-54b1-11e6-934c-7ceb68c10f20.png">

<img width="420" alt="screen shot 2016-07-28 at 10 54 31 am" src="https://cloud.githubusercontent.com/assets/2193314/17223506/b1ca6800-54b1-11e6-8522-8f9bb8ce5288.png">

**Comment by joaomoreno** [comment]
Try Fira Code, that's what I have.

**Comment by joaomoreno** [comment]
Not sure why I assigned this to myself... 😕

**Comment by joaomoreno** [comment]
I still see this. 😢 

![screen shot 2017-02-16 at 15 29 46](https://cloud.githubusercontent.com/assets/22350/23025054/d03d79e4-f45c-11e6-84fb-fdf7aa54cfbd.png)

**Comment by Tyriar** [comment]
This is what the setting toggled between:

```css
.monaco-workbench .panel.integrated-terminal {
	font-feature-settings: "liga" 0;
}

.monaco-workbench .panel.integrated-terminal.enable-ligatures {
	font-feature-settings: "liga" 1;
}
```

Can you check in dev tools if the styles look right?

**Comment by joaomoreno** [comment]
Does look good...

![image](https://cloud.githubusercontent.com/assets/22350/23061447/2adcba40-f502-11e6-9234-c9be96ae2cbd.png)

**Comment by Tyriar** [comment]
Does `font-variant-ligatures: none;` disable them? https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

**Comment by joaomoreno** [comment]
Yes, it does! 🎆
