### ISSUE TITLE
insiders latest version doesnt load git

### ISSUE THREAD

**Issue by cezarneaga** [microsoft/vscode#75411]
Issue Type: <b>Bug</b>

it says no source control providers registered. i connect to server and terminal shows that i have changes but sidebar and lines indicators do not work

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:17:56.032Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.9.0-0.bpo.2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (4.22GB free)|
|Process Argv|-psn_0_471155|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev01.in.easyname.com|
|OS|Linux x64 4.9.0-0.bpo.2-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (8 x 2194)|
|Memory (System)|15.67GB (3.53GB free)|
|VM|50%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
remote-containers|ms-|0.60.0
remote-ssh|ms-|0.42.1
remote-ssh-edit|ms-|0.42.1
remote-ssh-explorer|ms-|0.42.1
vscode-remote-extensionpack|ms-|0.15.0
vscode-todo-highlight|way|1.0.4
ReactSnippets|xab|2.3.0
vscode-intelephense-client|bme|1.0.14
turbo-console-log|Cha|1.2.23
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
language-gettext|mro|0.1.1
vs-code-toggl-extension|nat|0.2.0
fix-json|oli|0.1.2
vscode-jest|Ort|2.9.2
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.1.6
vscode-import-cost|wix|2.12.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Are you using a workspace? If yes, in the JSON of the .code-workspace file is there a `settings` section with `"git.enabled": false` in it?

**Comment by cezarneaga** [comment]
nope :)

**Comment by brunorzn** [comment]
Same problem here. Appeared today.

Version : 1.36.0-insider
OS version : Windows_NT x64

Calling "Show git output" inside vscode works great.

Also, I have the extension Git Graph which works great too (and I think it relies on git.path somehow ?)

**Comment by cdalizadeh** [comment]
I'm having the same problem.

Version: 1.36.0-insider
OS: Windows_NT x64 10

"Show git output" works fine for me too. I'm Remote-SSHing into a CentOS 7.5 machine

**Comment by cezarneaga** [comment]
pfew, i thought i effed something myself :)
i guess we need to be patient. i am sure it will get fixed.

C

**Comment by boland** [comment]
Same. Running on Mac remoting to Ubuntu. git is in the path (I can run git commands in the Terminal).

**Comment by comaniac** [comment]
Same. It was working fine and suddenly stopped working after installing the update.
- Do not see any error from the git log or GitHub extension log.
- Running git command in the Terminal (WSL) is still fine.
- I am using remote WSL.

**Comment by joaomoreno** [comment]
This is currently fixed in `master`. Should be fixed in the next Insiders release, which hasn't come out yet for Windows today.
