### ISSUE TITLE
Increasce indentation in explorer

### ISSUE THREAD

**Issue by dkrahn** [microsoft/vscode#75414]
Issue Type: <b>Feature Request</b>

It has been a few releases now, but the new, almost inexistent, indentation in folder explorer, makes it difficult to see if a file is a sibling or a child of the folder.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Try increasing your `workbench.tree.indent` setting.

**Comment by dkrahn** [comment]
Thanks!
I did not find this setting before.
Sorry for the trouble.
