### ISSUE TITLE
Breakpoint remains on breakpoints list after file is deleted

### ISSUE THREAD

**Issue by eyalroth** [microsoft/vscode#75427]
**Version:**
- VSCode Version: 1.35.0
- OS Version: Windows 10.0.17134.799

**Steps to Reproduce:**

1. Create a new code file (of any supported language).
2. Write a few lines of code.
3. Place a break-point on a line.
4. Delete the file.

**Bug:**
The break-point still appears in the break-points list. It should be automatically removed.

**Does this issue occur when all extensions are disabled?** Yes

**Comment by isidorn** [comment]
Does not reproduce for me.
What are you doing differentyl than me? Can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/

![hello](https://user-images.githubusercontent.com/1926584/59507418-48984000-8eab-11e9-9821-2189c8fc3e5a.gif)

**Comment by eyalroth** [comment]
@isidorn weirdly enough I cannot seem to reproduce it, though I'm a 100% sure it happened. I'm very sorry to bother you.

**Comment by isidorn** [comment]
@eyalroth it was probably a file event missing. So it would be an issue for our watcher.
Though let us know when you can reproduce.
