### ISSUE TITLE
Webview: make theme colors usable from a TextDocumentContentProvider

### ISSUE THREAD

**Issue by theor** [Microsoft/vscode#7542]
I think #5737 let us know if the current theme is the light or dark one - but I'd rather use directly the current theme colors. Any chance to do that ?

Thanks,

Theo

**Comment by jrieken** [comment]
@theor [This](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L121) is the smallish list of variables that you can use. Their value is derived from the current theme and changes when the theme changes.

**Comment by theor** [comment]
@jrieken thanks, I'll manage with that !
