### ISSUE TITLE
Failed to install VS Code update.

### ISSUE THREAD

**Issue by keyiis** [microsoft/vscode#75429]
- VSCode Version:1.34.0
- OS Version:win10 x64

Steps to Reproduce:

1.when  i update vscode,i get below error
![QQ截图20190613221718](https://user-images.githubusercontent.com/7766085/59440523-b4d25f80-8e29-11e9-9987-2adb1640f6b1.jpg)
**vscode-inno-updater-1560435135.log**
```
Jun 13 22:12:15.324 INFO Starting: C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Jun 13 22:12:15.328 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\Code.exe
```
2.my vscode install at `C:\Program Files\Microsoft VS Code\code.exe`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
You seem to have two versions of Code installed. Please uninstall both and install VS Code again. Thanks.
