### ISSUE TITLE
New Window shortcut opens 2(two) new windows when Webview is on active editor window

### ISSUE THREAD

**Issue by robellegate** [microsoft/vscode#75421]
Issue Type: <b>Bug</b>

1. Open anything that uses a Webview. In the below gif I used the extension [mhutchie.git-graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph), but the issue also presented itself when I had an extension's details page open, which contained a Webview
2. Press New Window keyboard shortcut

![vscode-git-graph-issue](https://user-images.githubusercontent.com/16375649/59280336-68253380-8c33-11e9-80b1-0814782276a6.gif)
Webview in the extension [mhutchie.git-graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)

![vscode-webview-issue](https://user-images.githubusercontent.com/16375649/59434733-2246a780-8dba-11e9-9c37-a1b63be232d6.gif)
Webview on the extension details page for [donjayamanne.githistory](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory)

VS Code version: Code - Insiders 1.36.0-insider (d04b5d2eb16c156e24dbf44010c315d968694bd6, 2019-06-13T05:15:24.059Z)
OS version: Linux x64 5.1.7-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 2544)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.74GB (0.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
xml|Dot|2.5.0
gitlens|eam|9.8.2
vscode-edit-csv|jan|0.0.11
git-graph|mhu|1.8.0
remote-containers|ms-|0.61.0
remote-ssh|ms-|0.42.1
remote-ssh-edit|ms-|0.42.1
remote-ssh-explorer|ms-|0.42.1
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
vscode-docker|Pet|0.6.2

</details>

**Comment by rje6459** [comment]
A big thank you to @mhutchie for helping me narrow down the issue to being in the Webview API.

**Comment by GOST-UA** [comment]
I assume that the problem is more general - I observe a similar behavior with "Toggle Internal Terminal" hotkey.

**Comment by mjbvz** [comment]
Just tested on Linux again (with both the custom titlebar and the native titlebar) but I think it's been fixed for a while

Let me know if you are still seeing this
