### ISSUE TITLE
Search cancel icon seems broken

### ISSUE THREAD

**Issue by NikilRagav** [microsoft/vscode#75436]
Issue Type: <b>Bug</b>

The Cancel icon when searching with ctrl+shift+F gives a box instead of an X (it looks like an unstyled checkbox). Once search is done, the redo icon shows correctly.

Look at the top left of the following images (the Search area)

*During search*
![image](https://user-images.githubusercontent.com/20876705/59449597-430ffc80-8dbc-11e9-8f35-2d56cf39b10d.png)

*Once search is done*
![image](https://user-images.githubusercontent.com/20876705/59449648-5a4eea00-8dbc-11e9-892e-6d967f62d4f0.png)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (44.50GB free)|
|Process Argv|C:\Users\t-niraga\Downloads\chromiumIDE.vsix|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
togglehs|bbe|0.1.2
gitlens|eam|9.8.2
chromiumide|ked|0.1.3
cpptools|ms-|0.23.1
clang-format|xav|1.9.0

</details>

**Comment by roblourens** [comment]
That's a stop button, it is supposed to look like that.
