### ISSUE TITLE
Allow ctr+click/ctrl+hover in other places

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode#75439]
allow `ctrl+click/ctrl+hover`
here
![image](https://user-images.githubusercontent.com/36124472/59453676-70db5c80-8e21-11e9-857d-988bb1829fed.png)
here
![image](https://user-images.githubusercontent.com/36124472/59453812-c7e13180-8e21-11e9-8582-38476338202d.png)
and here
![image](https://user-images.githubusercontent.com/36124472/59453862-e6472d00-8e21-11e9-94bc-f3890a373fad.png)
(where showing definition)

**Comment by mjbvz** [comment]
This is unclear to me. Please explain the expected behavior and what the current behavior is. Try to include example code (as text)

/needsMoreInfo

**Comment by SupinePandora43** [comment]
here
![59453862-e6472d00-8e21-11e9-94bc-f3890a373fad](https://user-images.githubusercontent.com/36124472/59620191-4c42f580-913d-11e9-974d-e61d105723fd.png)

**Comment by mjbvz** [comment]
Please explain what you expect

**Comment by SupinePandora43** [comment]
allow Go To Definition in (that window in screnshoot above)

**Comment by mjbvz** [comment]
Like in hovers and in IntelliSense suggestion? Try using words to explain exactly what you expect, such as:

**Repo**
1. Trigger intellisense
1. Open the suggestion details
1. Cmd click on a symbol in the top section of the hover

**expected**
It should go to the definition of the symbol

**Comment by SupinePandora43** [comment]
yes this:
> **Repo**
> 
> 1. Trigger intellisense
> 2. Open the suggestion details
> 3. Cmd click on a symbol in the top section of the hover
> 
> **expected**
> It should go to the definition of the symbol

**Comment by Yimiprod** [comment]
![image](https://user-images.githubusercontent.com/2227867/94818750-c06ede80-03fe-11eb-9a7d-634293cebceb.png)
what we have:
`cmd` doesn't show the path to the file when **require()** is inside a block
`cmd+click` doesn't follow the path when **require()** is inside a block

what is expected:
`cmd` should show the path to the file when **require()** is inside a block
`cmd+click` should follow the path when **require()** is inside a block

**Comment by mjbvz** [comment]
Merging this into https://github.com/microsoft/vscode/issues/64566
