### ISSUE TITLE
Extensions are not installing

### ISSUE THREAD

**Issue by saulius88** [microsoft/vscode#75438]
Issue Type: <b>Bug</b>

I keep getting this error:
Cannot read property 'local' of undefined

Even though I am trying to install an extension in a user-level installation of  VS Code, I am pretty sure I have access to the /.vscode/extensions directory.

Thanks

S

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.51GB (25.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
`Cannot read property 'local' of undefined` error is fixed in latest insiders
