### ISSUE TITLE
Windows terminal starts offscreen, and dropped a few lines

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#75432]
Issue Type: <b>Bug</b>

Disable all extensions.

Open the integrated terminal (after setting it to default to `cmd` rather than `powershell`).

For some reason it inserts some random lines at the top and scrolls down so you can't see the cmd intro text, version, and the current directory prompt. Scrolling up reveals that it's dropped a few lines. Entering a command as normal does execute as normal and further prompts do not have any additional empty lines injected.

![aead5d11-826f-46e8-b57d-acb9c2a9ecec](https://user-images.githubusercontent.com/8572438/59445483-c0903880-8dcd-11e9-91af-33b044901791.gif)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.04GB free)|
|Process Argv|C:\_bunker\4klick\Divisional|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
