### ISSUE TITLE
Popups immediately disappear when editor is scrolled right at all

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#75447]
Issue Type: <b>Bug</b>

Scroll right just 1px and some error popups will blink and then immediately disappear.

I disabled all extensions before reporting this, though enabling some does seem to make the problem worse it definitely exists in base VS Code.  See video:

![error_popup](https://user-images.githubusercontent.com/320562/59458861-3eedda00-8dd0-11e9-9d0f-ba388bd11814.gif)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lramos15** [comment]
Appears related to #75374
