### ISSUE TITLE
Sync button icon not corectly centered

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode#75446]
- VSCode Version: 1.35.1
- OS Version: windows 7

Steps to Reproduce:

1. press git sync button

**Comment by misolori** [comment]
This is actually a problem with the icon itself as the circles are not evenly round (it's always been like this). Symmetrical circle in the background for comparison:

![image](https://user-images.githubusercontent.com/35271042/59538202-c4938780-8ead-11e9-9c69-bfb39dd01e3a.png)

**Comment by SupinePandora43** [comment]
it's png or svg?

**Comment by misolori** [comment]
It’s an svg that gets converted to an icon font

**Comment by SupinePandora43** [comment]
@misolori may be pull request?!

**Comment by SupinePandora43** [comment]
@misolori where that icon?!

**Comment by misolori** [comment]
We use this repo that generates the icon font:

https://github.com/microsoft/vscode-octicons-font

Overrides are placed under the `src > icons` folder in that repo, then we copy over the contents of the `dist` folder into this folder:

https://github.com/microsoft/vscode/tree/master/src/vs/base/browser/ui/octiconLabel/octicons

**Comment by SupinePandora43** [comment]
@misolori to fix this, needed fix in https://github.com/primer/octicons ?!

**Comment by misolori** [comment]
You can either make the fix in the Octicons repo or place a replacement in our vscode-octicons-font repo like I mentioned above.

However, we are currently in the process of updating all of our icons (see #8017) that may happen this month or next, so I’m not sure it’s worth the effort to fix this.
