### ISSUE TITLE
Related to [exploration] "Another instance ... is running but not responding" #64091

### ISSUE THREAD

**Issue by markbridge1** [microsoft/vscode#75448]
Further info to related info that may help -

- VSCode Version: 1.35.1
- OS Version: MacOS Mojave 10.14.5

Steps to Reproduce:

1. Unzip VS Code, copy over into Applications folder (may start to make sure okay, then quit)
2. Right click to open a file (JSON) with VS Code
3. Process hangs/doesn't start
4. Force quit Code
5. See that Electron process doesn't die - even with sudo kill -9 on it

After re-start moved VS Code out of Applications folder and works fine.

Does this issue occur when all extensions are disabled?: N/A - fresh install

**Comment by bpasero** [comment]
@markbridge1 are you opening multiple files at once or just one?
