### ISSUE TITLE
Outline view does not navigate back to already-selected identifier

### ISSUE THREAD

**Issue by AlexMax** [microsoft/vscode#75444]
- VSCode Version: Version 1.35.1 (1.35.1)
- OS Version: macOS 10.14.5 (18F132)

Steps to Reproduce:

1. Open a file that covers multiple main window pages and has multiple identifiers in the outline view on the left that be selected between.
2. Select an identifier from the outline view.  The main window should navigate to the selected identifier.
3. Scroll the main window until the identifier is not in view anymore.
4. Select the _same_ identifier from the outline view again.

The expected behavior is that the identifier is navigated to again.  The actual behavior is that nothing happens, you must first select a different, random identifier (which will work) and then click the original identifier you were actually interested in.  It appears that if the identifier is already "selected" in the outline view, clicking on it a second time won't actually do anything.

Does this issue occur when all extensions are disabled?: Don't think so.  Extensions supply the outline, so it's hard to check, but I tested both C and PHP so I don't think it's a problem with any one extension.

**Comment by AlexMax** [comment]
@jrieken - I'm a little confused.  You seem to have flagged this bug as a duplicate of itself.  Is there something I'm missing here?

**Comment by jrieken** [comment]
ops - #74410
