### ISSUE TITLE
After vscode 1.35 intellisense not working javascript

### ISSUE THREAD

**Issue by jitendra1607** [microsoft/vscode#75441]
Issue Type: <b>Bug</b>

after update vscode feels slow, also no code completion and intellisense working.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
quasar-snippets|abd|0.5.0
htmltagwrap|bra|0.0.7
phpserver|bra|2.4.6
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
vscode-html-css|ecm|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
todo-tree|Gru|0.0.135
debugger-for-chrome|msj|4.11.3
vetur|oct|0.21.0
vue-beautify|pea|2.0.4
language-stylus|sys|1.11.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Please include steps to reproduce the issue

/needsMoreInfo

**Comment by jitendra1607** [comment]
I have downgraded to 1.34 and all is good, You must check system logs above and observe high RAM usages with v1.35, that may be possible reason.

**Comment by mjbvz** [comment]
Please include steps to reproduce the issue and check to see if this still happens when you disable all extensions
