### ISSUE TITLE
function definition showing only ater typing ","

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode#75440]
typed ",":
![image](https://user-images.githubusercontent.com/36124472/59454192-97e65e00-8e22-11e9-86e2-edcbb629310c.png)
not typed:
![image](https://user-images.githubusercontent.com/36124472/59454222-ac2a5b00-8e22-11e9-889c-cdb23c03eb46.png)

**Comment by mjbvz** [comment]
This is as-designed. We don't want to show parameter hints if you are just navigating through a document. They are triggered when you type part of the function or can be triggered manually with the `trigger parameter hints` command/shortcut
