### ISSUE TITLE
Workspace root should be gitignore-proof

### ISSUE THREAD

**Issue by aleclarson** [microsoft/vscode#75452]
VSCode should never mark a workspace root as ignored when applying `.gitignore` files to the tree view.

**Comment by jrieken** [comment]
Why should VSCode lie to you?

**Comment by aleclarson** [comment]
@jrieken I have a git repo nested in another git repo. The parent has the child repo in its gitignore. VSCode should detect the child's .git directory and avoid graying out the child when it's a workspace root. Does that make more sense to you?

**Comment by jrieken** [comment]
We shell out to git to know what's being ignored. In your setup git seems to ignore all of your nested git repo and if that's your setup it should be reflected that way IMO. 

We might spawning the git command for the containing repo, not the child repo but I think ultimately its git's truth that we are showing (or at least wanting to show). 

Adding @joaomoreno to clarify on which repo the git-executable runs

**Comment by aleclarson** [comment]
> We shell out to git to know what's being ignored.

Perhaps an option to prevent graying out of `.git` directories could be added. It really bothers me when I'm working in the child repo.

**Comment by joaomoreno** [comment]
> I have a git repo nested in another git repo.

This is currently not supported: https://github.com/microsoft/vscode/issues/37947

**Comment by aleclarson** [comment]
@joaomoreno As far as I can tell, yeah. The "graying out" prevents me from seeing which files have uncommitted changes.

**Comment by joaomoreno** [comment]
So, everything within the inner repo's folder is ignored? Not just the folder itself?

**Comment by aleclarson** [comment]
> So, everything within the inner repo's folder is ignored? Not just the folder itself?

Yeah, exactly! It would be okay if only the folder name was grayed out.

> Do both repos appear in the SCM view?

Nah, only the parent repo.

**Comment by aleclarson** [comment]
I whittled it down further. If you add the parent repo to the workspace **before** the child repo, the child repo will be grayed out. If you add the child repo **first**, everything is dandy.

Hope this helps!

**Comment by joaomoreno** [comment]
One last question: any specific reason why you're not using git submodules?

**Comment by aleclarson** [comment]
Because I'm tired of committing `.gitmodules` every time a submodule has new commits.

I use [meta](https://www.npmjs.com/package/meta) instead.

**Comment by joaomoreno** [comment]
Got it. I'll merge this into #37947
