### ISSUE TITLE
Internal Terminal problem

### ISSUE THREAD

**Issue by mariodaguiar** [microsoft/vscode#75453]
Issue Type: <b>Bug</b>

When I want to open the integrated terminal (ctrl + ñ) a message appears saying "The window is locked", the options it gives: return open or close; if you choose vover open reboots vscode and if you choose to close it closes vscode and exits; what is the solution, I am using extencion to translate it into spanish.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T15:16:14.389Z)
OS version: Windows_NT ia32 10.0.18362

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-languagetool|ada|3.8.0
vscode-languagetool-es|ada|3.8.0
vscode-intelephense-client|bme|1.0.14
htmltagwrap|bra|0.0.7
vscode-markdownlint|Dav|0.27.0
vscode-eslint|dba|1.9.0
css-minify|Die|0.1.11
vscode-html-css|ecm|0.2.0
php-intellisense|fel|2.3.10
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
html-tag-wrapper|hwe|0.2.3
JavaScriptSnippetsStandard|jms|1.7.2
vscode-simple-icons|Lau|1.11.7
vscode-language-pack-es|MS-|1.35.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.2
vscode-icons|vsc|8.7.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does this happen when you close all windows and launch with `code --disable-extensions`? Also can you toggle the terminal via the View menu?

**Comment by mariodaguiar** [comment]
Excuse me, I do not understand my English is very basic; when I want to do a job in sass and when I press the keys ctrl + ñ "which is for vscode in Spanish" the message window blocked appears.
This I started with this last update version 1.35.1 with the previous ones I had no problems

**Comment by Tyriar** [comment]
Probably related to windows update?

**Comment by joaomoreno** [comment]
>  the message window blocked appears.

Can you show me a screenshot?
