### ISSUE TITLE
Goto declaration not working with JS arrow functions?

### ISSUE THREAD

**Issue by accuware** [microsoft/vscode#75450]
- VSCode Version: 1.35
- OS Version: macOS mojave

Steps to Reproduce:

1. Create a "test.js".

test = () => {
    console.log("test")
}

test()

2. click on test(). Try "Goto definition"

3. Result: "No definition found". 

Should go to test.

**Comment by mjbvz** [comment]
You need to make this a proper declaration using `var` or `let` or `const`:

```js
var test = () => ...
```

Otherwise it's just a global variable which we don't know about and won't be able to properly support for intellisense

**Comment by accuware** [comment]
True. Thanks Matt

**Comment by neilyoung** [comment]
@mjbvz This approach solves the intellisense issue, but I'm having a problem to access public functions after declaring it like so from other modules. Do I have to export all?
