### ISSUE TITLE
Breakpoints are being ignored when debugging

### ISSUE THREAD

**Issue by ishraqiyun77** [microsoft/vscode#75451]
There are similar reported issues, but the solutions in those haven't been working for me

- VSCode Version: 1.35.1
- OS Version: 1803 (17134.829)

Steps to Reproduce:

1.  Just a simple JS program like the following:

```
console.log("Stop");
console.log("At");
console.log("Breakpoints");
```
2.  Add breakpoints on any, or all, of them
3.  Press F5 and it will print all lines in order instead of stopping at the breakpoints

`launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "useWSL": true,
            "name": "Launch Program",
            "program": "${file}"
        }
    ]
}
```

The breakpoints turn into hollow circles while debugging is running so not sure what that means:
![image](https://user-images.githubusercontent.com/33135849/59469227-0f979700-8de9-11e9-803d-b8cd96f1c0e4.png)

Also tested on Ubuntu 19.04 using VSCode 1.35.1. Works fine there.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by weinand** [comment]
Use of "useWSL" property is deprecated.
Please use the "Remote - WSL" extension instead.
