### ISSUE TITLE
TM Scopes have been changed, affecting themes

### ISSUE THREAD

**Issue by 76784** [microsoft/vscode#75464]
- VSCode Version: 1.35.1
- OS Version: Windows 10

Steps to Reproduce:

1. put the following in the editor: `var parser = document.createElement('a');`
2. when inspecting the TM Scopes of both `document` and `createElement()`, VS Code _used to_ scope them as members of the DOM. Something in Visual Studio Code has changed to make this no longer the case. This affects themes that have styled that based on them being from the DOM.

Does this issue occur when all extensions are disabled?: Yes - I have verified.

**Comment by mjbvz** [comment]
These scopes were intentionally removed almost 6 months. See the discussion in https://github.com/microsoft/TypeScript-TmLanguage/issues/691 for why the dom scopes are a bad idea
