### ISSUE TITLE
Hang on delete character and type `\`

### ISSUE THREAD

**Issue by Petah** [microsoft/vscode#75468]
Issue Type: <b>Performance Issue</b>

I am simply deleting 1 character (the `o`), then typing `\` and it hangs and causes "this window has stopped responding"

This is the line:
`o('testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest');`

In this function:
```
    public function getProducts()
    {
        if (!$this->_products) {
            echo ' ';
            o('testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest');
            $this->_products = iterator_to_array($this->products()->get());
        }
        return $this->_products;
    }
```

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.62GB free)|
|Process Argv|-psn_0_3941314|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   131	 26283	code main
    2	    82	 26284	   gpu-process
    0	    98	 26294	   shared-process
    0	   246	 35449	   window (Store.php — my-project (Workspace))
    0	    82	 35450	     extensionHost
    0	    49	 35456	       electron_node server.js 
    0	    49	 35460	       electron_node eslintServer.js 
    0	    82	 35491	       electron_node server.js 
    0	    49	 35451	     watcherService
    0	    98	 35499	     searchService
    3	    82	 35509	   window (Issue Reporter)
    0	     0	 35511	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Store.php — my-project (Workspace))
|    Folder (my-project-server): more than 43954 files
|      File types: php(29721) js(2399) jpg(2056) pem(980) json(952) xml(651)
|                  config(561) css(537) png(406) md(396)
|      Conf files: package.json(76) gulp.js(53) makefile(9) grunt.js(2)
|                  settings.json(1)
|    Folder (my-project-onboarding): 1421 files
|      File types: php(778) js(170) html(102) scss(82) xlf(67) png(39)
|                  json(36) md(21) yml(11) po(7)
|      Conf files: package.json(3) gulp.js(1) settings.json(1)
|    Folder (my-project-webapp): 19175 files
|      File types: png(7518) svg(3660) jpg(1838) html(1679) php(1596)
|                  json(1096) js(480) css(367) txt(236) md(83)
|      Conf files: package.json(2) makefile(2) gulp.js(1) launch.json(1)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
multi-cursor-case-preserve|Car|1.0.4
vscode-eslint|dba|1.9.0
phpmd|lin|1.2.1
vscode-typescript-tslint-plugin|ms-|1.1.0
vetur|oct|0.21.0
vscode-scss-formatter|sib|1.4.1
code-spell-checker|str|1.7.17

</details>

**Comment by Petah** [comment]
I tried disabling all my extensions as per https://github.com/Microsoft/vscode/wiki/Performance-Issues but it still occurs.

**Comment by Petah** [comment]
![image](https://user-images.githubusercontent.com/134799/59481829-1215f180-8eba-11e9-974e-db7086eca180.png)

**Comment by Petah** [comment]
Tried rolling back multiple versions an it occurs in all of them.

**Comment by Petah** [comment]
Here is `code --status` output
![image](https://user-images.githubusercontent.com/134799/59569832-402a4a00-90e3-11e9-921d-08dbddbb062b.png)

**Comment by Petah** [comment]
Profiler output:
![image](https://user-images.githubusercontent.com/134799/59569908-2d644500-90e4-11e9-97c4-a6fbfd5f7d63.png)

[Profile-20190617T094332.json.zip](https://github.com/microsoft/vscode/files/3294610/Profile-20190617T094332.json.zip)

**Comment by roblourens** [comment]
It looks like the patch from https://github.com/microsoft/vscode/issues/40279 is out of date with the PHP grammar
