### ISSUE TITLE
Git sourcecontrol

### ISSUE THREAD

**Issue by jhovanylinkin** [microsoft/vscode#75460]
We have written the needed data into your clipboard 
Issue Type: <b>Bug</b>

in the last update, working with containers, the control of code (git) is lost, but if I use git lents it works are some problem

VS Code version: Code - Insiders 1.36.0-insider (33ba72fef9099c4b58ad812585babc3fbacb9427, 2019-06-12T19:10:50.182Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container jhovanylinkin/shorestore:version1 (/nifty_wozniak)|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2676)|
|Memory (System)|1.93GB (0.13GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.61.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
vscode-docker|Pet|0.6.2
vscode-icons|vsc|8.7.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.1.0

(1 theme extensions excluded)

</details>
because it was too large to send. Please paste.

**Comment by rami3e** [comment]
i am also having a similar problem. as of the last update, remote ssh source control no longer works. it works however on a local copy of a repo. i uninstalled vscode server side and locally and it still does work.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/75411
