### ISSUE TITLE
There is no prompt code when writing a jsx file, but there are hints in previous versions.

### ISSUE THREAD

**Issue by lkrimy** [microsoft/vscode#75467]
In version 1.32.3, when I wrote the jsx file, when I typed 'this.setS', it would prompt 'this.setState'. However, after version 1.33.1, it will not be prompted.

For example, this is version 1.33.1-1.35,When I type, there are no prompts
![微信截图_20190614105308](https://user-images.githubusercontent.com/51808840/59480417-1bd82e80-8e93-11e9-9a1b-1a2848cc294a.png)

![微信截图_20190614104745](https://user-images.githubusercontent.com/51808840/59480375-f9deac00-8e92-11e9-8876-dfd4c3550c1f.png)

This is version 1.32.3, there will be a prompt
![微信截图_20190614105041](https://user-images.githubusercontent.com/51808840/59480508-6e194f80-8e93-11e9-8b1a-f4866c6df2d7.png)

![微信截图_20190614105023](https://user-images.githubusercontent.com/51808840/59480497-635eba80-8e93-11e9-9983-8aa7a00795b6.png)

**Comment by mjbvz** [comment]
Does this happen if you disable all extensions? Also can you manually trigger suggestions using ctrl+space?

/needsMoreInfo
