### ISSUE TITLE
Support filter by string or regex in Terminal window

### ISSUE THREAD

**Issue by LeonidKokhnovich** [microsoft/vscode#75474]
Hi everyone! Thanks for the great code editor!

Currently, within the Terminal window, there is no option to filter the Terminal output by a specific string or regex. In many other editors like Xcode (LLDB console) and Android Studio (Logcat), there is such a feature available. It would be great if there was support for that.

Example:
If I have a Terminal window with the following output:
```
Received payload: 2
Received message
Did receive request: 2
S#1,1
S#0,1
W b: 0
Did send message
No message received
No message received
Received payload: 2
Received message
Did receive request: 0
```
and the filter string would be "No message ", I would expect to see in the Terminal window only the following output:
```
No message received
No message received
```
As you can see, only those lines of text that contain the string entered in Filter would be displayed. The feature should also support updating the filtered Terminal output if there are more characters printed to it.

**Comment by Tyriar** [comment]
No plans to add a filter to the terminal, there is a search just like in the editor already though (ctrl/cmd+f). 
<img width="234" alt="Screen Shot 2019-06-14 at 11 46 26 AM" src="https://user-images.githubusercontent.com/2193314/59531152-15998080-8e9a-11e9-8bcb-fde747c1fce2.png">

**Comment by PEZ** [comment]
This was closed pretty quickly. 😄 Did you start with the ”collect 20 votes” after this? Maybe submit this suggestion to a test like that?

**Comment by Tyriar** [comment]
@PEZ it's not so easy to do what is being asked and would need major changes to the terminal component (xterm.js) that I'm not willing to do considering what we would be getting.
