### ISSUE TITLE
developer: not able to debug Visual Studio Code with the option 'Launch VS Code'

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode#75478]
I havea copy of the vscode master branch on my local windows machine, starting from last week, I started to have problem debugging VS Code with the option 'Launch VS Code', the main window is launched but the content is not rendering. i have no problem launching it with scripts\code.bat.

this is what I am getting:
![image](https://user-images.githubusercontent.com/13777222/59489522-41cfe580-8e37-11e9-94da-c1d56ef8b0f3.png)

from process explorer:

![image](https://user-images.githubusercontent.com/13777222/59489462-1c42dc00-8e37-11e9-9652-071644ce8074.png)

**Comment by alanrenmsft** [comment]
@weinand Hi Andre, Did you get a chance to look into the issue?

**Comment by roblourens** [comment]
So it launches with .\scripts\code.bat from the terminal? 

Is node on your system path? And not installed after vscode was launched? 

I don't do a good job of surfacing errors that come from code.bat because usually we are launching chrome.exe which produces a lot of noisy not-real-error output.

**Comment by alanrenmsft** [comment]
see my comments inline.
> So it launches with .\scripts\code.bat from the terminal?
[Alan]yes.
> 
> Is node on your system path? And not installed after vscode was launched?
[Alan]node is on the system path. version v10.15.3. It was installed a while back definitely way before vscode was launched.
> 
> I don't do a good job of surfacing errors that come from code.bat because usually we are launching chrome.exe which produces a lot of noisy not-real-error output.

**Comment by roblourens** [comment]
I think I'll just have to put out a version of this that logs stderr from the program we launch.

**Comment by alanrenmsft** [comment]
@roblourens , Thanks, that will definitely help.

**Comment by roblourens** [comment]
Please try this:

- Download this zip, rename to .vsix, install it in vscode [debugger-for-chrome-4.11.4.zip](https://github.com/microsoft/vscode/files/3308197/debugger-for-chrome-4.11.4.zip)
- Set `"trace": true` in your launch config
- Try launching again, share the log from file in the debug console

Thanks!

**Comment by ranasaria** [comment]
@alanrenmsft, @roblourens - I was not able to reproduce this issue as of the following commit on windows machine.
commit 5a5ccf7ec13f01228d4d607983e3d2efbc81fb3b

**Comment by alanrenmsft** [comment]
I am also not able to reproduce this anymore. closing for now, thanks @roblourens .
