### ISSUE TITLE
Considerable lag/system becomes unstable while trying to debug

### ISSUE THREAD

**Issue by Suhail** [microsoft/vscode#75475]
- VSCode Version: 1.35.1
- OS Version: Windows_NT x64 10.0.17763

## Problem

For some reason when I run VSCode, attempt to debug something, and set a breakpoint and merely require() this addon in NodeJS: https://github.com/wilix-team/iohook there's considerable lag, the mouse becomes jittery, and my entire computer becomes nearly unusable. 

Does this issue occur when all extensions are disabled?: yes

**Comment by weinand** [comment]
Please provide reproducible steps.

**Comment by Suhail** [comment]
Steps:
1. Make a NodeJS app
2. require this addon: https://github.com/wilix-team/iohook
3. Add a breakpoint anywhere
4. Watch the lag.

**Comment by weinand** [comment]
When looking through the other iohook issue at https://github.com/wilix-team/iohook/issues, it seems that installing iohook affects responsiveness of the underlying OS independent from VS Code. So this seems to be the expected iohook behavior. I suggest to file an issue against iohook,
