### ISSUE TITLE
autoAttach does not work in wsl

### ISSUE THREAD

**Issue by whwnow** [microsoft/vscode#75479]
- VSCode Version: 1.35.1
- OS Version: Windows10 1809 (17763.557)
- WSL Version:  Ubuntu 18.04.2 LTS

Steps to Reproduce:

1. Open the `autoAttach` option
2. Run `node --inspect-brk program.js` in the WSL terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@whwnow are you using the "Remote Development" and "Remote - WSL" extensions for this?

**Comment by whwnow** [comment]
Really sorry, it is my fault. I have not seen this document before. After using the "Remote - WSL" extensions , it runs perfectly.   Thank you for your reply. vscode great!

**Comment by weinand** [comment]
@whwnow No problem; glad that you could resolve this issue on your side.
