### ISSUE TITLE
memery has been over occupied

### ISSUE THREAD

**Issue by Hehulk** [microsoft/vscode#75485]
Issue Type: <b>Performance Issue</b>

i open my project of js,and memery has been over occupied
![image](https://user-images.githubusercontent.com/39331665/59493749-2c51ce80-8ebe-11e9-9683-0c15a0074363.png)
is that normal?

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    9	    59	  7412	code main
    0	    38	  1608	   shared-process
    1	    75	  4788	   gpu-process
    0	  2793	 11272	   window (phone.js - 全域旅游 - Visual Studio Code)
    0	     3	  3312	     watcherService 
    0	     1	  3392	       console-window-host (Windows internal process)
    0	    30	  3680	     extensionHost
    0	     8	  5560	       electron_node eslintServer.js 
    0	    14	 11900	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=3680
    0	    12	 12196	       electron_node dbaeumer.js server.js 
    0	    40	 12408	       electron_node tsserver.js 
    0	     6	 12724	         electron_node typingsInstaller.js typesMap.js 
    0	     2	 12432	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3680
    0	     1	  4148	     electron-crash-reporter
    0	     1	  8596	     winpty-process
    0	     5	 11888	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     1	 13180	       console-window-host (Windows internal process)
    0	     1	 15704	   C:\Users\admin\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-c7d83e57cd18f18026a8162d042843bda1bcf21f.exe /verysilent /update="C:\Users\admin\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-c7d83e57cd18f18026a8162d042843bda1bcf21f.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	     3	 16336	     "C:\Users\admin\AppData\Local\Temp\is-Q5LH1.tmp\CodeSetup-stable-c7d83e57cd18f18026a8162d042843bda1bcf21f.tmp" /SL5="$490B04,49638791,166912,C:\Users\admin\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-c7d83e57cd18f18026a8162d042843bda1bcf21f.exe" /verysilent /update="C:\Users\admin\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-c7d83e57cd18f18026a8162d042843bda1bcf21f.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    1	    67	 20708	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (phone.js - 全域旅游 - Visual Studio Code)
|    Folder (全域旅游): 1042 files
|      File types: html(324) css(281) png(217) js(132) json(23) gif(15) db(13)
|                  jpg(9) txt(5) rar(4)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.1.5
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
php-intellisense|fel|2.3.10
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.35.1
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
notepadplusplus-keybindings|ms-|1.0.3
vetur|oct|0.21.0
java|red|0.46.0

</details>

**Comment by Tyriar** [comment]
When in this state could you open devtools (Help > Toggle Developer Tools) then go to the memory tab, press the record button and then save and upload that recording here?
