### ISSUE TITLE
Taking too Much ram and Cpu

### ISSUE THREAD

**Issue by ajaykrishnalla** [microsoft/vscode#75484]
Issue Type: <b>Performance Issue</b>

Hi,
 Vscode taking too much ram and cpu 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.77GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   69	    53	  1296	code main
    0	   116	   572	   window (handle - Visual Studio Code)
    0	    50	  5160	     extensionHost
    0	    33	  7300	       "C:\Users\Nalla\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Nalla\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=5160
    7	   176	  7592	       php.exe c:\Users\Nalla\.vscode\extensions\felixfbecker.php-intellisense-2.3.10\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:56365 --memory-limit=4095M
    0	     4	 10132	         console-window-host (Windows internal process)
    0	    10	  5572	     electron-crash-reporter
    0	    11	  7200	     watcherService 
    0	     5	  8264	       console-window-host (Windows internal process)
    0	     4	  9184	     searchService
    0	    24	  2236	   shared-process
    0	   175	  2416	   gpu-process
    0	    67	  3012	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (handle - Visual Studio Code)
|    Folder (handle): more than 28876 files
|      File types: php(19079) js(2175) svg(1340) png(981) css(608) md(509)
|                  json(401) jpg(325) phpt(261) txt(249)
|      Conf files: package.json(19) grunt.js(12) makefile(11) gulp.js(2);
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
sublime-keybindings|ms-|4.0.0
vscode-typescript-tslint-plugin|ms-|1.1.0
laravel-blade|one|1.20.0
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by ajaykrishnalla** [comment]
i have not installed any extension still same issue

**Comment by Tyriar** [comment]
@bpasero main process at 69% CPU?

**Comment by ajaykrishnalla** [comment]
Yes

**Comment by bpasero** [comment]
@ajaykrishnalla 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
