### ISSUE TITLE
On save collapsed/folded code expands

### ISSUE THREAD

**Issue by noahsscott** [microsoft/vscode#75482]
- VSCode Version: Version 1.36.0-insider
- OS Version: Mac OS Mojave 10.14.5

When I save my html document my previously collapsed folders all expand. This occurs without any installed extensions in the latest nightly build.

Steps to Reproduce:

1. Install VSC V.1.36.0-insider on Mac OS Mojave 10.14.5
2. Create html document with some divs
3. Collapse one or many divs
4. Save
5. See that the collapsed div is now re-opened

![vsc](https://user-images.githubusercontent.com/2589149/59491567-94ea7c80-8eb9-11e9-8273-5503dddabe62.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@noahsscott  Do you have format on save enabled? 
If yes, what formatter is used?
Or any other extension that does something on save?

**Comment by noahsscott** [comment]
@aeschli No I don't have format on save enabled and when testing this have no extensions enabled.

**Comment by noahsscott** [comment]
@aeschli Apologies I just realised Codekit was running in the background when testing this. By toggling cache-bust 'off' on the html output file, the structure remains collapsed in VSC on save.
