### ISSUE TITLE
How do you see the details at intellisense?

### ISSUE THREAD

**Issue by bugtype** [microsoft/vscode#75483]
https://stackoverflow.com/questions/56590642/how-do-i-look-at-more-in-detail

https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense
I couldn't find the option that How to look at it in detail.
No matter how much I search it, it won't come out.

**Comment by gjsjohnmurray** [comment]
Do you want to see more detail about one of the Intellisense suggestions in the list? [Doc](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features) says:

> As provided by the language service, you can see quick info for each method by either pressing Ctrl+Space or clicking the info icon. The accompanying documentation for the method will now expand to the side. The expanded documentation will stay so and will update as you navigate the list. You can close this by pressing Ctrl+Space again or by clicking on the close icon.

Or is your problem that the list only shows the first N entries and you want to see more? In that case, the setting `editor.suggest.maxVisibleSuggestions` seems relevant. Its help says that there should be a scrollbar if the set limit (default 12, maximum 15) is exceeded.

If you're finding it hard to explain the problem please add screenshots.

**Comment by bugtype** [comment]
I'm sorry. I said something wrong. [Check the first link.](https://stackoverflow.com/questions/56590642/how-do-i-look-at-more-in-detail)
If there are more types, it is displayed as [...more]. I'd like to take a closer look.
<img src="https://i.stack.imgur.com/3CGym.png">

#### Second question
The description here also shows [...more] if it's longer... What do I do to get a closer look?
<img width="439" alt="Screen Shot 2019-06-15 at 12 02 54 AM" src="https://user-images.githubusercontent.com/24269591/59518636-fda91780-8f00-11e9-9d5d-9509ad6c8784.png">
