### ISSUE TITLE
Move to new file misses line breaks 

### ISSUE THREAD

**Issue by JohannesDeml** [microsoft/vscode#75493]
When using move to a new file all previously made formatting (e.g. line breaks) are lost. I like the workflow of writing a class in an already existing file and then just pushing it to a new one, but losing line breaks is quite annoying and also unexpected.

Information about Visual Studio Code version:
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

File type: .ts

Requested behaviour:
Copy all text from the class from the class beginning to the class end as is without reformatting the code (by removing line breaks).

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/27294
