### ISSUE TITLE
JavaScript no highlight for single 'var' statement for multiple lines

### ISSUE THREAD

**Issue by ProvidenceXz** [Microsoft/vscode#7549]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

```javascript 
var foo = 1, bar = 2, baz = 3;
```

In this case, foo, bar, and baz are properly highlighted. 
However, if you put bar and baz to separate lines, like:
```javascript
var foo = 1,
    bar = 2,
    baz = 3;
```
which is legit syntax, but bar and baz are not highlighted.

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/121
