### ISSUE TITLE
Cleanup async lambdas in app.ts

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#75497]
There are three instances of async lambdas in `app.ts`:

- https://github.com/microsoft/vscode/blob/96913ae480c8e056cc15d7c3a55f25be2b602efe/src/vs/code/electron-main/app.ts#L258
- https://github.com/microsoft/vscode/blob/96913ae480c8e056cc15d7c3a55f25be2b602efe/src/vs/code/electron-main/app.ts#L269
- https://github.com/microsoft/vscode/blob/96913ae480c8e056cc15d7c3a55f25be2b602efe/src/vs/code/electron-main/app.ts#L353

This would make the first two much easier to understand:

```ts
this.lifecycleService.when(LifecycleMainPhase.AfterWindowOpen).then(async () => {
			// After waking up from sleep  (after window opened)
			powerMonitor.on('resume', () => {
				if (this.windowsMainService) {
					this.windowsMainService.sendToAll('vscode:osResume', undefined);
				}
			});

			// Keyboard layout changes (after window opened)
			const nativeKeymap = await import('native-keymap');
			nativeKeymap.onDidChangeKeyboardLayout(() => {
				if (this.windowsMainService) {
					this.windowsMainService.sendToAll('vscode:keyboardLayoutChanged', false);
				}
			});
});
```

The third case is even irrelevant, the entire lambda wrapper can be removed.

**Comment by bpasero** [comment]
@joaomoreno what do you want me to change?

**Comment by bpasero** [comment]
I simplified a bit, but do not see a way to make the 3rd case any different.
