### ISSUE TITLE
scroll to end of file when back from other program

### ISSUE THREAD

**Issue by exth** [microsoft/vscode#75495]
Issue Type: <b>Bug</b>

when i use other program for a while and back to vs code, once i touch the scroll wheel of my mouse just a little bit, the editor will jump to the end of the file, but the cursor is still at origin position where the editor will go back to if i push any arrow key. 

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 5.0.7-050007-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4205)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.56GB (0.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
clojure|avl|0.10.5
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.70
paredit-revived|cos|0.1.22
vscode-markdownlint|Dav|0.27.0
githistory|don|0.4.6
ftp-sync|luk|0.3.9
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.35.1
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
Go|ms-|0.10.2
vscode-typescript-tslint-plugin|ms-|1.1.0
remote-vscode|raf|1.1.0
java|red|0.46.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
markdown-all-in-one|yzh|2.3.1
vscode-proto3|zxh|0.2.2

</details>

**Comment by alexandrudima** [comment]
Let's track in #28795
