### ISSUE TITLE
Find all References not working

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#75492]
Issue Type: <b>Bug</b>

The Find all References function isn't working as of VScode 1.35. It worked fine in 1.34.

I'm using it on typescript, and VScode has decided to use its built-in typescript engine. I haven't touched its settings. Our typescript compiles absolutely fine, so code-wise there isn't a problem. Intellisense also works perfectly, so the editor is definitely able to fetch references.

When I use Find all References on an imported function from lodash, I get only the references in the current file, and the one in `lang.d.ts`. I would expect to see references across our project instead.

When I use this function on any function imported from another file *within* our project (in other words, not an external module), it works as expected and I get to see all references in all files.

We're importing from lodash like so:
```typescript
import { isFunction } from 'lodash';
```
Which again, works absolutely fine. The fact that VScode can find the `lang.d.ts`, tells me that it knows what to search for. It just doesn't want to find references in all other files.

As for one that does work:
```typescript
import { superCoolCustomFunction } from 'superCool';
```
There, the Find all References function works perfectly.

Again, the code compiles just fine, and works as expected, so it's not like lodash cannot be found or anything.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.4.4
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
duplicate|gee|1.0.1
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
vscode-sort-json|ric|1.13.0
code-settings-sync|Sha|3.2.9
vscode-svg-previewer|vit|0.5.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Can you please share a small example project or more information about your project structure and layout? For example:

* Do you have a tsconfig? Where is it located and what are the settings in it?
* Where is the file you are working in?
* Where are other files that contain the references?

**Comment by thany** [comment]
My project structure:
```
src
\-- js
    \-- folder1
    \-- folder2
    \-- folder3
    \-- main.ts
```
The `main.ts` includes everything it needs, and each file included includes other files. All includes look like this:
```typescript
import { foo } from 'folder2/file.ts';
```
The include paths always start with `folder`, considering the above structure, no matter where the file doing the include is located. We don't do any hokey-bokey things like `../../folder/file`.

An include from a module loaded through npm, looks like so:
```
import { isElement } from 'lodash';
```
Which **compiles and works**, and VScode **can** do suggestions for isElement and other functions from lodash. I don't know how it does that. But this is the part where Find all References breaks.

I don't think including our tsconfig is going to make any difference, since VScode uses its built-in typescript engine. The one in our project is ignored, as far as I can tell, and always has been. But if you must:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src/js/",
    "checkJs": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "outDir": "./dist",
    "paths": {
      "1-polyfills/*": ["./1-polyfills/*"],
      "2-vendor/*": ["./2-vendor/*"],
      "3-utilities/*": ["./3-utilities/*"],
      "4-data/*": ["./4-data/*"],
      "5-features/*": ["./5-features/*"],
      "6-modules/*": ["./6-modules/*"],
      "7-domain/*": ["./7-domain/*"]
    }
  },
  "files": ["./src/js/main.ts"],
  "exclude": ["./node_modules"]
}
```
It sits "next to" the `src` folder, and the `node_modules`, and other project-root-kind-of files.

And again, please note that everything worked fine in VScode 1.34. So now that I've given some details, can you provide some details around what's changed in VScode around this feature? Maybe it'll clear up where this bug is coming from.

**Comment by mjbvz** [comment]
So if you open one of your typescript files and run `TypeScript: go to project configuration` in vs code, it does not open that tsconfig?

VS Code 1.35 includes a new TS version, so you can try downgrading to typescript 3.4 in your workspace by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to see if that is the root cause

**Comment by thany** [comment]
> So if you open one of your typescript files and run `TypeScript: go to project configuration` in vs code, it does not open that tsconfig?

It does. But I can make write code that the editor thinks is erroneous (like `for..of` over a `NodeListOf`) which compiles and funtions absolutely fine. So that's why I assume the editor isn't (fully?) using our tsconfig.

> VS Code 1.35 includes a new TS version (3.5), so you can try downgrading to typescript 3.4 in your workspace by following [these instructions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to see if that is the root cause

I've tried this with TS 3.4.5 and 3.3.3333, and the problem persists.

**Comment by mjbvz** [comment]
I've tried to reproduce this in a simple project but have not been able to:

![Screen Shot 2019-08-21 at 5 26 53 PM](https://user-images.githubusercontent.com/12821956/63477289-546b2a00-c439-11e9-8fc9-df43ba0a71ef.png)

To help investigate this further, can you please share small example project that demonstrates the issue.

**Comment by thany** [comment]
Maybe there's something to keep this from working that is only happening in bigger projects. Unfortunately I don't know what that might be.

If there's anything that could possibly keep this from working, I could check for that. But since the project is private, I cannot just share it here.

**Comment by mjbvz** [comment]
There are many, many reasons why this many not work as you expect. Can you create a minimal example project that captures the problem but does not have private code?

**Comment by thany** [comment]
I was afraid that might be the case. Maybe when I have the time to do so. Please understand that making a reduced test from a huge project is not easy 🤐
