### ISSUE TITLE
No Definition found when using Arrow Functions

### ISSUE THREAD

**Issue by 888iee** [microsoft/vscode#75490]
So this issue happens when you use arrow functions like the following.
`doStuff = (param) => {console.log(param);}`

When I use the regular way to define a function, it will show definition when pressing F12 on the function call.

- Version: 1.35
- OS Version: Pop!_OS 19.04 (Linux 5.0.0)
Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #75450
