### ISSUE TITLE
Running PySpark SSH Terminal

### ISSUE THREAD

**Issue by StandbyProject** [microsoft/vscode#75508]
I am trying to run PySpark code in blocks in Visual Studio Code over an SSH Terminal to a cluster. Pressing Shift+Enter opens up a traditional local Python terminal. I have tried setting key bindings to run selected lines in active terminal, however this only works if I run code one line at a time because the terminal does not know to wait for a return before sending the next highlighted line, producing an error. How can I send multiple lines of code to an ssh terminal? Any ideas?

I essentially want to be able to run python files in the same manner as I can locally on a SSH Terminal.

**Comment by Tyriar** [comment]
Please share:

- OS
- VS Code version
- List of extensions
- Your keybindings.json file
