### ISSUE TITLE
When opening another project active one should not close

### ISSUE THREAD

**Issue by coolmk09** [microsoft/vscode#75501]
Issue Type: <b>Bug</b>

1. Open a folder/project using visual studio code. 
2. Go to File -> Recent -> Select another folder/project 

Expection 
1. VS code should ask whether do you want to open in new window or open in same. If user select same window, current project will be closed
2. Should launch in seperate window

Actual
The active project gets closed when you open another folder/project. 

Thanks!
Manish Kumar

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.5.0

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
es7-react-js-snippets|dsz|2.2.1
code-runner|for|0.9.8
svn-scm|joh|1.48.0
Kotlin|mat|1.7.0
es7-react-js-snippets|rod|1.9.3
salesforcedx-vscode|sal|45.14.0
salesforcedx-vscode-apex|sal|45.14.0
salesforcedx-vscode-apex-debugger|sal|45.14.0
salesforcedx-vscode-apex-replay-debugger|sal|45.14.0
salesforcedx-vscode-core|sal|45.14.0
salesforcedx-vscode-lightning|sal|45.14.0
salesforcedx-vscode-lwc|sal|45.14.0
salesforcedx-vscode-visualforce|sal|45.14.0
sonarlint-vscode|Son|1.6.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you use File -> New Window, then use File -> Recent in the new window.

**Comment by Tyriar** [comment]
You probably want to set `"window.openFoldersInNewWindow": "on"`

**Comment by gjsjohnmurray** [comment]
@Tyriar interesting option that I hadn't previously noticed. Maybe the helptext could be improved by mentioning workspaces as well as folders, e.g. 'Controls whether folders **and workspaces** should open in a new window or replace the last active window.'
