### ISSUE TITLE
tasks command environment

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#7550]
- VSCode Version: 1.2.0
- OSX Version: 10.11.5
 
In the documentation http://code.visualstudio.com/docs/editor/tasks it seems there is no easy way to configure crosscompile environment varaibles:

 `GOOS=windows GOARCH=386 go build -o build.exe`

A new "environment" property for each task would enable easier setup for go and many other compile tools. For example to achieve the above command:

```json
{
    "version": "0.1.0",
    "command": "go",
    "isShellCommand": true,
    "showOutput": "always",
    "program": "${workspaceRoot}",
    "tasks": [
        {
            "taskName": "test",
            "args": ["-v", "-race", "-port=8080"]
        },
        {
            "taskName": "build",
            "environment": ["GOOS=windows", "GOARCH=386"],
            "args": ["-o", "build.exe"],
            "isBuildCommand": true
        }
    ]
}
```

**Comment by gertcuykens** [comment]
Just want to add that maybe in the future there could also be a request to add a task group. For example to be able to build for different environments at once. In this case there can be multiple builds with the same taskname. But I suggest to just keep it simple at first and just go with the extra "environment" property for now.

**Comment by dbaeumer** [comment]
I fold this issue with #8143. That one asked for cwd per tasks and if we do that we should for consistency also support env per tasks
