### ISSUE TITLE
Typescript fails to show any suggestions

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#75507]
Sample code:

```ts
private pendingPromiseRequests = new Map<string, IRawPromiseRequest
```

![image](https://user-images.githubusercontent.com/22350/59511742-59e74980-8eb7-11e9-9111-9434796f8870.png)

Location: https://github.com/Microsoft/vscode/blob/3fe6a332950c098557396c0dcd9ecf2dd2939fce/src/vs/base/parts/ipc/common/ipc.ts#L255

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/31909 to track this
