### ISSUE TITLE
termionalEnvironment.ts is in common, but uses process.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#75509]
See `mergeDefaultShellPathAndArgs`

**Comment by Tyriar** [comment]
No it doesn't?

<img width="927" alt="Screen Shot 2019-06-14 at 8 53 24 AM" src="https://user-images.githubusercontent.com/2193314/59521745-e37c2480-8e81-11e9-8caa-c68c6c2bbb76.png">
