### ISSUE TITLE
Add IntelliSense explain mode

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#75500]
Developing IntelliSense is not alway easy, there is many ways how suggestions are sorted and filtered and it would be nice to have some kind of explain mode. E.g. with the details/doc show debug info about

* what was compared against what, e.g `con` against `console` and what's the score
* what was the original score (based on lexo-sort, filterText)
* was there a locality bonus?
* maybe timings?
* show items that didn't match

**Comment by jrieken** [comment]
PR #76294 adds the following

* keybinding `Ctrl/Cmd+/` to toggle explain mode (kept till restart or toggled again)
* once enabled it replaces the suggest details widget with
 * the provider that added the selected suggestion
 * the score that is computed by comparing a prefix against the suggestion
 * the distance from a similar word (control by the localitybonus-setting)
 * the index derived from the sortText/label

**Comment by alexr00** [comment]
The toggle works, but I need to change which element I'm focused on to cause it to show. Steps:
- Type `con` in a typescript file.
- See the suggest widget.
- `ctrl+/`
- No change to the suggest widget.
- Arrow down to the second suggestion.
- Now the suggest widget shows the explain mode.

**Comment by usernamehw** [comment]
I don't think <kbd>Ctrl</kbd>+<kbd>/</kbd> is a great keybinding since the action `toggle comment` will be used much more often (even with `suggestVidgetVisible`). It looks like this feature will be used mostly by extension authors and they can assign the keybinding themselves.
