### ISSUE TITLE
Detect extension-less C++ files based on the shebang on the first line

### ISSUE THREAD

**Issue by hokein** [microsoft/vscode#75506]
vscode already provides this feature for some languages like python, php, but not C++, it would be nice C-family languages get supported as well. 

For example, it is a common practice to use something like [`-*- C++ -*-`](https://github.com/atom/language-c/blob/0b85c03449cf5f8947680a07bc9c1523f9b02822/grammars/c%2B%2B.cson#L21) on the first line to indicate the language (btw Atom supports this feature).

**Comment by gjsjohnmurray** [comment]
Maybe see if you can get your language extension provider to make use of the [`firstLine`](https://code.visualstudio.com/api/references/contribution-points#language-example) feature.

If you're using the Microsoft C/C++ extension, raise your request [here](https://github.com/microsoft/vscode-cpptools/issues).
