### ISSUE TITLE
VSCode GitHub

### ISSUE THREAD

**Issue by fatihcandan52** [microsoft/vscode#75510]
Issue Type: <b>Bug</b>

First of all, my first problem is, I can not change my GitHub account or I do not know how change my account in VSCode. 

Also, there is a bug in commiting in GitHub. In terminal I can change my e-mail address and username, however "git" is not make check if it is me or someone else.  So, there is doubt about identification. In short, I can show my-self as complately diffrent person even if there is no account like this in GitHub

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
> First of all, my first problem is, I can not change my GitHub account or I do not know how change my account in VSCode.

You might want to go through https://help.github.com/en/articles/set-up-git#next-steps-authenticating-with-github-from-git

> Also, there is a bug in commiting in GitHub. In terminal I can change my e-mail address and username, however "git" is not make check if it is me or someone else. So, there is doubt about identification. In short, I can show my-self as complately diffrent person even if there is no account like this in GitHub

This is how git works: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
