### ISSUE TITLE
Improve error message when trying to save a file that is locked by another program

### ISSUE THREAD

**Issue by robertbarnard** [microsoft/vscode#75518]
- VSCode Version: 1.35.1 (user setup)
- OS Version: Windows_NT x64 10.0.16299
-VSCommit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

Steps to Reproduce:

1. Open a folder containing an XML file (such as a POM) (update: that is opened by _another_ process)
2. Modify the XML file
3. Ctrl-S, or File -> Save

(Update - After filing the bug, the thought of "sharing violation" came. When I tried editing using Notepad++, sure enough, the message "Please check if this file is opened in another program." came up. I'll keep this issue here in case someone would want to address VSCode handling file locks a little more gracefully. Thank you. -Robert)

Does this issue occur when all extensions are disabled?: Yes

Also:
Removed extensions. Results are the same.
Also ran VSCode as Administrator. Result are the same.
![VSCodeErrorAsUser](https://user-images.githubusercontent.com/15946144/59523467-63fd4e00-8e9f-11e9-8ff4-13d4bc7d6f87.gif)

Error Message:
Failed to save 'pom.xml': Unable to write file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open 'c:\gitprojs\Panacea-ReleaseUtility\branch\BranchingScriptDir\Panacea-DataTools\pom.xml')

![VSCodeErrorAsAdmin](https://user-images.githubusercontent.com/15946144/59523475-6e1f4c80-8e9f-11e9-992e-3d7a02b38680.gif)
![VSCodeErrorAsUser](https://user-images.githubusercontent.com/15946144/59523498-7e372c00-8e9f-11e9-9f6e-004c9a78bad0.gif)

**Comment by vodanhbk95** [comment]
Yah. I just got it and solved it.
You just reboot your system or device that run VS and then retry to run that code.
