### ISSUE TITLE
autoAttachChildProcesses for attach type debug

### ISSUE THREAD

**Issue by gustavomassa** [microsoft/vscode#75513]
Hello,

I've been using nodejs cluster mode for a while, the autoAttachChildProcesses feature is working very well. But know that I'm migrating to docker/kubernetes, thus I need to debug the process remotely using attach, it works fine for single processes.

Currently I'm using the vscode-kubernetes extension to debug the pods, but most of my pods uses node cluster internally, resulting on master and child processes.

https://github.com/Azure/vscode-kubernetes-tools/blob/fbd9005afed7bcaa7b4b88b543928988a301c7d0/src/debug/nodejsDebugProvider.ts#L40

The code above is the debug provider for nodejs, basically we need to find check if the process has any child process, if yes, just create a debugguer for each child process too. Setting --inspec on the master process automatically adds --inpect on each child process, incrementing the port of the master process.

Master process
![image](https://user-images.githubusercontent.com/16235598/59515936-a2dad600-8e96-11e9-86da-ee3efc1db6e6.png)

Worker 1 (child process)
![image](https://user-images.githubusercontent.com/16235598/59516425-b0449000-8e97-11e9-8104-8c97486bb857.png)
![image](https://user-images.githubusercontent.com/16235598/59516018-cb62d000-8e96-11e9-88ec-40395a4e6f07.png)

I think @weinand  is the creator of autoAttachChildProcesses feature. What you think is the best solution? Modify the extension to detect child process and start multiple remote debuggers, or add the same autoAttachChildProcesses for the attach debugger?
https://github.com/microsoft/vscode/issues/40123

Thank you!

**Comment by weinand** [comment]
With VS Code's "Remote Development" extension, the "autoAttachChildProcesses" feature works transparently in containers.
