### ISSUE TITLE
[snippets] new global snippets will not work in already created workspace file

### ISSUE THREAD

**Issue by alexplusde** [microsoft/vscode#75511]
- VSCode Version: 1.35.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Create a global snippet
2. open a workspace file that has been created before step 1 and try to use that snippet.

The snippet will not be suggested, the snippets are ignored.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
Can you share the snippet that you want to use and can you share the workspace file in which you wanna use the snippet?
