### ISSUE TITLE
Can not open/save file from remote desktop of a windows server core installation

### ISSUE THREAD

**Issue by softlion** [microsoft/vscode#75515]
VsCode crashes when it tries to use the open/save dialog when it is run in a tse session of a windows server core installation.

```
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299
```

Steps to Reproduce:

1. Install vscode on a windows server code
2. Try to open a file using the file/open menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
From https://code.visualstudio.com/docs/supporting/requirements#_platforms I do not see Windows Server as a supported platform. Closing given that.
