### ISSUE TITLE
"Find in selection" changes scroll location after performing a string replace

### ISSUE THREAD

**Issue by kuhlaid** [microsoft/vscode#75512]
After using the 'replace all' option with the 'Find in selection' option toggled on, then clearing the 'Find in selection' option by toggling off, the page scrolls to a different random selection.  It would be ideal if the page position did not change.

Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by rebornix** [comment]
@kuhlaid can you share a gif or screen recording to help understand what's going on?

**Comment by kuhlaid** [comment]
The behavior seems to be if there are other occurrences of the 'find' string outside of the 'find in selection' block then toggling the 'Find in selection' option will move the page scroll to another occurrence of the 'find' string (whether you perform a replace or not).


[Replace.pptx](https://github.com/microsoft/vscode/files/3294328/Replace.pptx)

**Comment by rebornix** [comment]
The find widget always automatically researches what's in the find input box when either the document changes or the search range changes. To disallow the automatic search (and also position revealing), you can disable `editor.find.cursorMoveOnType`.
