### ISSUE TITLE
Pin/sticky search results

### ISSUE THREAD

**Issue by b3wii** [microsoft/vscode#75514]
It would be a very handy feature if you could pin search results / make search results sticky. For example align them to the bottom of the search pane. In order to quickly jump navigate between different search results. I know there are Bookmarks but this way it would be much more comfortable and and more logical.

Thanx :)

**Comment by roblourens** [comment]
Interesting idea but I don't think this is likely to happen. I see the search results as a place with transient information, and pinning or organizing search results in different ways would be at odds with that.
