### ISSUE TITLE
Inconsistent hotkey behavior for zoom

### ISSUE THREAD

**Issue by DelfCo** [microsoft/vscode#75526]
Issue Type: <b>Bug</b>

Press Ctrl + + a couple of times to zoom in. Use the plus key on your main keyboard. This isn't a listed shortcut, but it works. (The listed shortcut is Ctrl + Numpad_Add, which also works.) Now try to zoom back out using Ctrl + - where the minus key is the one on your main keyboard. It doesn't zoom out. Ctrl + Numpad_subtract is the listed shortcut, and it works.

The problem with this is that if the + on the main keyboard works to zoom in, then the - on the main keyboard *must* work to zoom out. Laptop users don't necessarily have a numpad handy. Zoom in a few times and you can't even find the menu where you can undo zooming. The editor is unusable, and everything we tried short of uninstall/reinstall doesn't fix the problem.

It's especially insidious because the notation for shortcuts is "Ctrl+key". Some naive user is going to press Ctrl and plus because of that, and end up zoomed in. Make that mistake three or four times, and the editor becomes essentially useless.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by DelfCo** [comment]
I looked at the suggested dupes, and none of them are this. 73742 might be the same problem,  but the submitter closed it. This isn't 71653 because this happened while editing a text file, not an image.

**Comment by alexandrudima** [comment]
@DelfCo What keyboard layout do you use? What does the `F1` list show next to `View: Zoom out`?

**Comment by DelfCo** [comment]
Tried to repro this right now and it's fixed in 1.36.1.
