### ISSUE TITLE
Not able to update the app 

### ISSUE THREAD

**Issue by kpapasani** [microsoft/vscode#75522]
Issue Type: <b>Bug</b>

Visual studio code is not applying the lates update 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
apex-pmd|chu|0.4.4
vscode-eslint|dba|1.8.2
prettier-vscode|esb|1.9.0
falcon|Fal|0.0.27
apex-pmd-code-scanner|moh|0.0.40
notepadplusplus-keybindings|ms-|1.0.3
vscode-xml|red|0.7.0
salesforcedx-vscode|sal|45.15.1
salesforcedx-vscode-apex|sal|45.15.1
salesforcedx-vscode-apex-debugger|sal|45.15.1
salesforcedx-vscode-apex-replay-debugger|sal|45.15.1
salesforcedx-vscode-core|sal|45.15.1
salesforcedx-vscode-lightning|sal|45.15.1
salesforcedx-vscode-lwc|sal|45.15.1
salesforcedx-vscode-visualforce|sal|45.15.1

</details>

**Comment by GuzioMG** [comment]
### Try running vs code as an admin.
Helped in my case, but your errorlog is a bit different, than my, so I'm not proposing anything.

**Comment by joaomoreno** [comment]
Are you using the user or the system setup?
