### ISSUE TITLE
Apply for Insider Program within the standard VS Code

### ISSUE THREAD

**Issue by TheLifeGamingYT** [microsoft/vscode#75520]
Hi!
A feature that I would like to see in VS Code is the ability to apply for Insider updates within the standard, stable VS Code. I think it's better because you can maintain all the extensions, preferences, etc. without re-applying them in the Insider app from the stable app.
Hope to hear from you again.
TheLifeGamingYT

**Comment by GuzioMG** [comment]
Yeah, another button under "Check for updates", saying "Check for insider build updates" would be a great idea...

**Comment by TheLifeGamingYT** [comment]
yep

**Comment by joaomoreno** [comment]
There are no plans to make this happen. Insider is a separate product altogether. Manual copy or symlinking are the suggested workarounds.
