### ISSUE TITLE
C++ Syntax Highlight incorrect

### ISSUE THREAD

**Issue by DollarAkshay** [microsoft/vscode#75529]
- VSCode Version: 1.35.1 (system setup)
- OS Version: Windows 10

Looks like the syntax highlighting is broken for C++, The green color bleeds into the rest of the line and affects even the blue keywords. This is part of the latest update. Please see the GIF image attached below.

Steps to Reproduce:
![ezgif-4-c25c99179e0b](https://user-images.githubusercontent.com/6565924/59529993-182ec100-8f00-11e9-9539-a0f5e5322d55.gif)

Does this issue occur when all extensions are disabled?:  Yes

**Comment by DollarAkshay** [comment]
@Tyriar This cannot be caused by an extension as I disabled all the extensions and this still happened.

**Comment by Tyriar** [comment]
@DollarAkshay you should install the C++ extension for proper highlighting as ours is pretty barebones.

**Comment by alexr00** [comment]
@DollarAkshay Can you provide a copy/paste-able example?

**Comment by DollarAkshay** [comment]
@alexr00 Sure 

```
#include <stdio.h>
#include <vector>

using namespace std;

class GameState {
  public:
	int a;
};

class Node {
  public:
	int a;
};

class Node *exploreTree(class GameState &game, vector<int> &searchList) {
}

class Node *expandNode(class Node *nodePtr, class GameState &game, vector<int> &searchList) {
}

int main() {
	return 0;
}
```

You can take any example that uses the `class` keyword. The `class` keyword makes the name of the class to a teal color. That teal color affects the syntax highlighting of all other things that come after it

@Tyriar I was fine with the barebones syntax highlighting but seems like the update messed it up.

**Comment by alexr00** [comment]
Thank you for the example!
We get our C++ grammar from https://github.com/jeff-hykin/cpp-textmate-grammar and it looks like they've already improved the behavior around the class keyword. I tried your example out in version 1.35.1 and saw the same behavior you did. The green bleeding into other tokens is already fixed in insiders from an update to the grammar though!

**Comment by DollarAkshay** [comment]
Thank you @alexr00
