### ISSUE TITLE
2nd vscode does not open the same workspace as already opened in first one anymore.

### ISSUE THREAD

**Issue by yosoufe** [microsoft/vscode#75528]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open a workspace in first VS code
2. Open a new window of VS code from file->New Windows or from terminal
3. Try to open the same workspace in the second VS code. It does not allow you to do that. It does not open it and it will jump to first windows.

Does this issue occur when all extensions are disabled?: Yes

VS code does not support multiple monitors and it was said that we would open the second session of VS code to work on multiple monitor. I believe I could open the same workspace on multiple sessions before and could work on multiple monitors but now with this new bug(/feature?) I cannot open the same workspace twice.

Please support mutli-monitor setups.
Thanks

**Comment by Tyriar** [comment]
This is by design currently, you can workaround it by using separate workspaces. Follow https://github.com/microsoft/vscode/issues/10121 for updates in this area.
