### ISSUE TITLE
'ext install' displaying incorrect results when there are dashes

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/vscode#7553]
- VSCode Version: 1.2.0
- OS Version: Windows 10 Pro Insider Preview (Build 14361)

Steps to Reproduce:

1. Open Visual Studio Code
2. Open your quick open bar (Ctrl+P on Windows)
3. Type in the install command for any extension with a dash in the name (i.e. `ext install code-settings-sync`)
4. Notice that the search is not displaying the correct results.

Possible Explanation:
It appears that the search term is being tokenizing as multiple words split by the dash rather than searching for the full extension name. If you search for `ext install code settings sync` you will get the same results as `ext install code-settings-sync`.

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/7327
