### ISSUE TITLE
Icon exploration doesn't apply high contrast icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75530]
<img width="358" alt="Screen Shot 2019-06-14 at 11 44 02 AM" src="https://user-images.githubusercontent.com/2193314/59530988-c0f60580-8e99-11e9-9b9d-96fad16f33b7.png">

**Comment by misolori** [comment]
This actually affected all icons as high contrast colors were not specified, fixed it now:

![image](https://user-images.githubusercontent.com/35271042/59537778-67e39d00-8eac-11e9-8e70-0807a73b8fd3.png)
