### ISSUE TITLE
Switching themes causes webview Error

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75532]
Issue Type: <b>Bug</b>

1. Toggle developer tools
2. Switch themes

Everything appears to work as normal, but the console gets flooded with `WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.` errors. 

VS Code version: Code - Insiders 1.36.0-insider (15b7c86d86319b187a5ef255c170184a8519c5af, 2019-06-14T10:36:51.530Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.96GB free)|
|Process Argv|-psn_0_2441812|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
vsc-material-theme|Equ|2.9.0
remote-containers|ms-|0.61.0
remote-ssh-edit-nightly|ms-|2019.6.19620
remote-ssh-explorer-nightly|ms-|2019.6.19620
remote-ssh-nightly|ms-|2019.6.18180
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0
polacode|pnp|0.3.2
vscode-sort-json|ric|1.13.0

</details>

**Comment by mjbvz** [comment]
I can't repo this. Which developer tools and theme are you talking about specifically?

**Comment by lramos15** [comment]
I tried repoing this again and it appears that this error is related to installing a new theme.
Here are some better repo steps:
1. Toggle developer tools
2. Switch themes (no errors)
3. Install a theme
4. Switch themes (errors even if it is one of the themes shipped with VS code)

The errors go away after a reload, but installing a theme does not tell me a reload is required.

**Comment by mjbvz** [comment]
Ok, with the extensions view open, I sometimes see

```
ERR Invalid guestInstanceId: null: Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:430:11)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/electron.asar/browser/rpc-server.js:449:34
    at EventEmitter.ipcMain.on.args (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/electron.asar/browser/rpc-server.js:278:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/electron.asar/browser/api/web-contents.js:370:21)
    at WebContents.emit (events.js:182:13)
```

Does not cause seem to cause any actual problems

**Comment by lramos15** [comment]
I get that as well sometimes, but do you not get the webview must be attached to the DOM error as well?

**Comment by jeanp413** [comment]
I can reproduce it. Steps:
1. Click on any extension to load it's Readme in an editor
2. Close that editor
3. Change theme (this triggers the webview error)
4. Repeat step 1 (this triggers the guestInstanceId error)
