### ISSUE TITLE
AppData\Roaming\Code\logs automatic cleanup?

### ISSUE THREAD

**Issue by whitecolor** [microsoft/vscode#75539]
My AppData\Roaming\Code(-insiders)\logs has multiple directories which take 2-4GB of disks space.

Maybe provide some procedure to clean up them?

**Comment by gjsjohnmurray** [comment]
Has your log level been increased [see comment here](https://github.com/microsoft/vscode/issues/75545#issuecomment-502326579)? Good question about automatic cleanup of logs.

**Comment by joaomoreno** [comment]
@whitecolor Can you find which log files exactly take up most space?

VS Code already does its own cleanup: https://github.com/Microsoft/vscode/blob/613447d6b3f458ef7fee227e3876303bf5184580/src/vs/code/electron-browser/sharedProcess/contrib/logsDataCleaner.ts#L12

**Comment by sandy081** [comment]
We retain logs of last 10 sessions, it means you should have max 10 sessions logs. Please check if you have more?

**Comment by whitecolor** [comment]
> We retain logs of last 10 sessions, it means you should have max 10 sessions logs

Probably make this configurable?

**Comment by joaomoreno** [comment]
@whitecolor 10 session should never take 2-4 GB, can you find which log files exactly take up most space?

**Comment by whitecolor** [comment]
Yeah I had `verbose` setting for all workspaces set.

**Comment by joaomoreno** [comment]
@whitecolor I see. Which log files exactly take up most space? Can you give us file names?

**Comment by whitecolor** [comment]
Were tsserver related logs.

**Comment by mjbvz** [comment]
In general, you should not run with `"typescript.tsserver.log"` on unless investigating an issue with VS Code. The logs  it produces are quite verbose and the log file can get very large.

[This upstream issue](https://github.com/microsoft/TypeScript/issues/30967) tracks comically large TS Server log files, but even under normal circumstances the tsserver log file can get quite long during a long session on a larger project
