### ISSUE TITLE
Tabs do not stay open, new file takes the tab that an open file had been in

### ISSUE THREAD

**Issue by jrobiii** [microsoft/vscode#75544]
I see the that the very thing that I'm experiencing was reported in "only show one tab,new tab will replace exist tab #51649"  
I have tried it with 1.36.0 (insider) and it still persists

Version: 1.36.0-insider (user setup)
Commit: 15b7c86d86319b187a5ef255c170184a8519c5af
Date: 2019-06-14T10:37:04.235Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open Folder with several files
2. Click on one of the files and then click on another file.  The original file is no longer in the Open Editors list and the tab of the first document is no longer open.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
This is as designed. Documentation [here](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode). @jrobiii if you agree please close this issue. If not, give more info e.g. screenshots.

**Comment by jrobiii** [comment]
I see, double clicking actually opens the window in a tab and single clicking previews.  Thanks!  I will close this ticket.
