### ISSUE TITLE
snippets not work for html

### ISSUE THREAD

**Issue by linhuang0405** [microsoft/vscode#75549]
snippets not work!i have create a snippets  for html in snippets /html.json("prefix": "aaaaaa",),now i create a new file save to demo.html and i write  "aaaaaa" in the first row , but i can not see the temple in my code!( "aaaaaa" + TAB is not work! )

**Comment by jrieken** [comment]
please share the snippet and the file in which in you try this. please share the exact position at which you try this

**Comment by linhuang0405** [comment]
> please share the snippet and the file in which in you try this. please share the exact position at which you try this

hi，i have slove by myself.this issue cause by the Extension ！Thanks your reply！
