### ISSUE TITLE
About 100 tsserver.log files each ~1-3GB log files

### ISSUE THREAD

**Issue by natew** [microsoft/vscode#75545]
- VSCode Version: Insiders (not sure which caused these)
- OS Version: Mojave

I looked through the log files roughly and they just seem to be showing lots of information about the files I've been editing.

Each of these blocks is a logfile, the selected one is 4.4GB:

![image](https://user-images.githubusercontent.com/12100/59543006-8b631380-8ebd-11e9-9f38-3bf0e2164fc9.png)

The pathnames look like:

```
Users/nw/Library/Application Support/Code - Insiders/logs/20190601T024350/exthost1/vscode.typescript-language-features/tsserver-log-feCn36/tsserver.log
```

**Comment by gjsjohnmurray** [comment]
Please use Command Palette to run `Developer: Set Log Level...` and check whether yours has been changed from `Info` which is listed as the default.

**Comment by mjbvz** [comment]
In VS Code, set `"typescript.tsserver.log": "off"`. TypeScript Server logging will slow things down quite a bit and is only useful if you are investigating a problem

These log files should also be automatically cleaned up at some point. #75539 covers that
