### ISSUE TITLE
'(' can't be correctly recognized

### ISSUE THREAD

**Issue by qwe3084614** [microsoft/vscode#75555]
Issue Type: <b>Feature Request</b>

'(' can't be correctly recognized

Extension version: 0.0.6
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by oneslash** [comment]
Could you add more information on the language and the example text.
