### ISSUE TITLE
Less features, more stability 🙏

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode#75556]
DISCLAIMER: THIS IS NOT A BUG NEITHER A FEATURE REQUEST.

Hello,

I got the impression that the development's direction is actually the opposite of the title.
I experiencing a lot of small issues. I caught myself reloading the editor too often lately, hoping this workaround helps.

I think vscode's popularity is based on that it is fast, multi-platform, lightweight, community driven (extensions) and fast (again).

Features are important but I don't think about vscode as a real competitor of *MSVS* or *Xcode*. So seeing the tons of features following a lot of issues made me thinking..

As a humble user of vscode, I am kindly asking you to allocate more time on stability please.

Anyway, it is awesome. 

Bests

PS.: I know a lot of features (built-in extensions) are in different repos. I wont post this issue every one of it. :)

**Comment by chrisdias** [comment]
Thanks for taking the time to write up an issue. Fundamentals (stability, performance, etc.) are very important to us and we prioritize these over features.  

However, finding and fixing stability/performance issues is hard without reproducible steps, so if you can isolate a problem that is most helpful. 

Oftentimes the best way to start is by disabling all of the extensions and re-enabling them one by one to see if you can isolate the problem.

Here are two docs that explain various ways to narrow down a problem as well:

https://github.com/microsoft/vscode/wiki/Performance-Issues
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

Thanks!

**Comment by matepek** [comment]
Okay, thank. I will report one when I am encounter again.

However my suggestion referred to the open issues:
There are 53 issues with label `freeze-slow-crash` and 822 with label `bug`.
