### ISSUE TITLE
Color themes not working

### ISSUE THREAD

**Issue by kmanadkat** [microsoft/vscode#75551]
- VSCode Version: 1.35.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open any html, css, cpp, python files.
2. Color themes will disappear in under 10 seconds.
3. A tiny Red icon (flames) flicks in status bar and color theme goes away.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Are you sure all extensions are disabled?
Also, can you attach a screenshot? Anything in the logs?

**Comment by aeschli** [comment]
Closing, more information is required
