### ISSUE TITLE
Delete file while editing in the tree view does not remove it from working file list

### ISSUE THREAD

**Issue by joonhwan** [Microsoft/vscode#7555]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open 'test.txt' file in directory
2. Edit and do not save
3. Delete 'test.txt' in tree view
4. create same file in the console (e.g: type nul > test.txt)
5. back to code, open it again in the tree view
6. it still show the last edited state.

**Comment by bpasero** [comment]
We have to do this so that you do not loose your unsaved work in the editor.

**Comment by joonhwan** [comment]
Ok, It is understood. But in visual studio, in such case, application will ask me to choose three options

- Discard : Discard current edited state
- Overwrite : Ignore file system change but use my edited state
- Cancel : do nothing just let it open in edited state (VS Code case)

**Comment by bpasero** [comment]
Yes, we have another issue to confirm in that case.
