### ISSUE TITLE
Allow modifying key binding for Go to Definition

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#75554]
As per documentation: https://code.visualstudio.com/docs/editor/editingevolved

In windows, there is a CTRL-click to go to definition. On mac, this appears to be CMD-click (should probably be reflected in the documentation). However, I can't seem to be able to configure this in the keyboard shortcuts.

It states F12 as an alias, but how can I change CMD-click on mac to CTRL-click?

![image](https://user-images.githubusercontent.com/490562/59547936-0b12e000-8f9b-11e9-9318-d8bf7643d469.png)

**Comment by Tyriar** [comment]
You can use `editor.multiCursorModifier` to flip the modifier of go to definition with multi cursor as a workaround. Better mouse customization is captured in https://github.com/microsoft/vscode/issues/3130

**Comment by adamreisnz** [comment]
That's helpful, thanks.
