### ISSUE TITLE
The markdown preview page sometimes has confusing lines

### ISSUE THREAD

**Issue by lognxn** [microsoft/vscode#75557]
- VSCode Version: May 2019 (version 1.35)
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1.  Code with markdown， Preview with the plugin is"Markdown Preview Enhanced".
2.  The preview page sometimes has one more confusing line.

e.g. :  
Source code in markdown:
```
C:\tmp>git checkout master
Switched to branch 'master'
C:\tmp>git status
On branch master
nothing to commit, working tree clean
```
Preview page display:
```
C:\tmp>git checkout master
Switched to branch 'master'
C:\tmp>git status
On branch master
nothing to commit, working tree clean
<p data-line="47" class="sync-line" style="margin:0;"></p>
```

**Comment by mjbvz** [comment]
Please file this against Markdown Preview Enhanced
