### ISSUE TITLE
Linux: XDG_CACHE_HOME appears in workspace 

### ISSUE THREAD

**Issue by drsooch** [microsoft/vscode#75552]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04.2

While in VSCode, occasionally a folder will appear in the workspace named `XDG_CACHE_HOME`. In this folder the Microsoft Python Language Server files appear. I did not press any buttons or shortcut keys (at least that I'm aware of) to precipitate this. 

Using `printenv` reveals my `XDG_CACHE_HOME` location to be: `XDG_CACHE_HOME=/home/user/snap/code/common/.cache`

The occurrence appears random.

Does this issue occur when all extensions are disabled?: Unknown

**Comment by autoferrit** [comment]
I started getting this today too. Although when I inspect the env it seems normal

```bash
➜ echo $XDG_CACHE_HOME
/home/shawn/.cache
```
It seems to happen when building the stubs
```bash
➜ la XDG_CACHE_HOME/Microsoft/Python\ Language\ Server/stubs.v1/
Permissions Size User  Date Modified Git Name
drwxr-xr-x     - shawn 15 Jun 15:40   -N 6Jdz2MUWOGr4bOZIEZpe3fAFOVX2QH2XXVQox93LDvI=
drwxr-xr-x     - shawn 15 Jun 15:40   -N 7C99n6DBx3TyDkTh_256g-aNza2EnMuyP24gUWgBpTY=
drwxr-xr-x     - shawn 15 Jun 15:40   -N CkOhaAcSRrnAxPPLiPLINXzzISvUoHqfUe2XpFnuIkM=
drwxr-xr-x     - shawn 15 Jun 15:40   -N DgUOPNCe5yUG1BRLIQTFkq7B2Go6gWN9a99nyAoAgt4=
drwxr-xr-x     - shawn 15 Jun 15:40   -N t5KoAFz6U1gUfcJCH_VSnv4Svx8S1w9UsncWaDgap94=
drwxr-xr-x     - shawn 15 Jun 15:40   -N ZvCkTbGIBId18gPSW6oZ8Wrre5OpFha3SOKxWNEYMsE=
```
