### ISSUE TITLE
terminal format theme and color

### ISSUE THREAD

**Issue by 1470391328** [microsoft/vscode#75566]
the theme color does not work for terminal , i can not stand the white format and black terminal

**Comment by camelCaseCo** [comment]
Can you give more context, please? What version you are using, operating system, etc.
When I try it, it seems to work fine.

**Comment by 1470391328** [comment]
最新版本的vscode， 系统是windows10 1809

**Comment by camelCaseCo** [comment]
Ok. Can you send a screenshot of the issue?
