### ISSUE TITLE
[bug] "files to include" not working

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#75572]
- VSCode Version: 1.35.1
- OS Version: macOS

Steps to Reproduce:

1. Open find tool
2. Enter a regex in "files to include", f.e. `src/*/*.*`
3. search for a term.

Does this issue occur when all extensions are disabled?: I didn't try

---

Here's a screen shot showing I'm looking for results in `src/*/*.*`, however the very first resultt is `.gitignore` which is not in the `src` folder. You can also see `package.json` is there.

<img width="355" alt="Screen Shot 2019-06-15 at 10 41 11 AM" src="https://user-images.githubusercontent.com/297678/59554583-1d205e80-8f5a-11e9-8948-e7ee5a157ba7.png">

**Comment by roblourens** [comment]
Is that file open? Files will always be searched if they are open - https://github.com/Microsoft/vscode/issues/31819

**Comment by trusktr** [comment]
@roblourens Ah, that might've been the issue. I can't recall.
