### ISSUE TITLE
There is no way to create a new folder under the root folder in the Sidebar Explorer when the root folder only contains folders

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/vscode#75571]
- VSCode Version: Latest
- OS Version: Windows 10 Latest

Steps to Reproduce:

1.  Open a folder X in the sidebar in VS Code
----- This folder X should be a folder that only contains folders as immediate children - no files as immediate children
2.  Open a file in one of the subfolders
3.  Try to create a new folder that is a child of X

It is not possible because you cannot actually select X, nor can you right-click on X.  Any time you execute the New Folder command (the one that appears on hover over X), it will create a child folder of a subfolder of X, not a new subfolder of X.

This appears to be a broken UX model as well as a bug.  The real problem is you cannot select the root folder.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/1043
