### ISSUE TITLE
Clicking urls makes browser crash

### ISSUE THREAD

**Issue by danielpetrica** [microsoft/vscode#75579]
Issue Type: <b>Bug</b>

When clicking in any link, a popup with firefox has crashed pups up. 
Happening in different places including code, terminal and error report dialog.

Also signaled over at Firefox, maybe this may be useful: [crash-stats.mozilla.org](https://crash-stats.mozilla.org/signature/?product=Firefox&signature=__memcpy_ssse3_back)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 5.0.0-16-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G (2 x 2970)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|7.32GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.5.1
gitlens|eam|9.8.2
php-intellisense|fel|2.3.10
intellij-idea-keybindings|k--|0.2.33
vscode-now|luc|0.1.0
php-namespace-resolver|Meh|1.1.8
php-docblocker|nei|1.8.0
swdc-vscode|sof|1.1.1
php-formatter|Sop|0.2.4
vscode-gitmoji-snippets|thi|3.2.0
terminal-tabs|Tyr|0.2.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Assuming this is related to snap again, fyi @flexiondotorg

**Comment by danielpetrica** [comment]
Is there anything I can do to help you solve this issue?

**Comment by oSoMoN** [comment]
This has been reported by several Ubuntu users: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1838129.

I can reliably reproduce the crash on Ubuntu 19.04 and 19.10, not on 18.04, which makes me think that it could be classic confinement playing tricks here, by exposing two ABI-incompatible versions of libpng16 (the one in the snap, and the one on the host system).

**Comment by oSoMoN** [comment]
Note that firefox installed as a deb crashes, whereas if the default browser is firefox installed as a snap, it won't crash.

**Comment by oSoMoN** [comment]
This doesn't make sense: the linked documentation says the `out-of-scope` label applies to feature requests, but this is clearly a bug, not a feature request.
Closing the bug doesn't make it go away, and it will eventually be filed again by an affected user, so this doesn't actually help alleviate the triaging work. Why not keep it open with a low priority?

**Comment by Tyriar** [comment]
@oSoMoN it's a bug in an upstream project, you should track it at https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1838129

**Comment by oSoMoN** [comment]
It's not clear to me that the problem is entirely on firefox's side. See https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1838129/comments/9.

**Comment by Tyriar** [comment]
@oSoMoN it's either a bug in Firefox, Snap or Electron. We just call an Electron API to open a link and the crash occurs. You're welcome to investigate further but we're closing this off keep our issues at a more manageable level as we cannot action this within vscode.

**Comment by joaomoreno** [comment]
@flexiondotorg I was wondering if you have any thoughts on this?

**Comment by ctaggart** [comment]
The snap packing of https://snapcraft.io/vscode is done by Snapcrafters. The bug for this is https://github.com/snapcrafters/vscode/issues/48 . I may be a good idea to liink to the snap issues from https://code.visualstudio.com/docs/setup/linux .

**Comment by ygbr** [comment]
On Ubuntu 19.10 uninstalling the "Firefox Web Browser" pre-installed deb package and installing the package named as just "Firefox" (packaged as a snap by Mozilla itself) on the Ubuntu Software store did the trick.

**Comment by nnadeau** [comment]
> On Ubuntu 19.10 uninstalling the "Firefox Web Browser" pre-installed deb package and installing the package named as just "Firefox" (packaged as a snap by Mozilla itself) on the Ubuntu Software store did the trick.

confirmed to work for me.

###### `lsb_release -a`
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

###### `code -v`
```
1.43.1
fe22a9645b44368865c0ba92e2fb881ff1afce94
x64
```

**Comment by SergeiBond** [comment]
If it helps: The same thing happens when trying to click links from within a SNAP version of Skype. Installing a .deb version of Skype fixes the problem. So, it's definitely something to do with the SNAP layer itself.
