### ISSUE TITLE
Cannot Run VSCode on MacOS Catalina

### ISSUE THREAD

**Issue by egonzal93** [microsoft/vscode#75577]
- VSCode Version: Latest download as of June 15, 2019 1.35 either one of Extended or Stable
- OS Version: MacOS
  System Version:	macOS 10.15 (19A471t) Catalina Beta
  Kernel Version:	Darwin 19.0.0

Steps to Reproduce:

1. After downloading and installing VSCode, It won't Launch from LaunchPad.
2. I tried to run VScode from BASH Terminal of MacOS.  and I get the following error:

/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code: line 10:  3195 Abort trap: 6           ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

3. I tried code --disable-extensions and I still get the same error.

**Comment by bpasero** [comment]
@egonzal93 can you try to run a bare Electron? E.g. via electron-fiddle

**Comment by johannesluedke** [comment]
@egonzal93
I had the same issue on MacOS Mojave. For me, reinstalling VS Code resolved the issue
