### ISSUE TITLE
Git clone overrides dir name

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#75574]
- VSCode Version: 1.35.1
- OS Version: macOS

Very weird issue, open a new VS Code instance and do `Git: Clone` with this repo: `https://github.com/svipas/concurrent-run/`. Instead of keeping the name `concurrent-run` it was renamed to `repository` 😄

**Comment by svipas** [comment]
Seems I cannot reproduce it anymore. It happens randomly... Or maybe because I killed all VS Code instances and relaunched it. Anyways feel free to close it if I encounter it again I will reopen.

**Comment by joaomoreno** [comment]
Reproduces if the URL has a trailing slash.

**Comment by svipas** [comment]
@joaomoreno Thanks for looking into this and I'm very happy you were able to reproduce it.
