### ISSUE TITLE
Extension: jsonValidation for another language

### ISSUE THREAD

**Issue by code1line** [Microsoft/vscode#7557]
- VSCode Version: 1.3.0
- OS Version: OSX 10.11.5

I created a second "json-language" and want to use "jsonValidation" in my extension. Is this possible?

The own "json-language" is necessary for not polluting the original JSON with too many snippets.

**Comment by aeschli** [comment]
The JSON validation is all internal and should not be referenced.
For now you have to copy the code. Eventually I can extract it to a separate node module so it can be reused.

**Comment by code1line** [comment]
Ok, I'll take a copy for the moment. Thx!
