### ISSUE TITLE
Open containing folder doesn't work

### ISSUE THREAD

**Issue by donnisnoni95** [microsoft/vscode#75588]
### Steps to Reproduce:

right click on a file
choose "open in containing folder"
nothing happens

I tried to open one of my project folders in nemo file manager by right-clicking in that folder -> Open containing folder
But after waiting, my Nemo FM is not open. hope the VSCode team can fix this.

I suggest that VS Code can provide a setting for this 

## OS Information

CPUs | Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1621)
-- | --
OS | Linux Mint Tara
Desktop Environment | LXDE
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwaresurface_synchronization: enabled_onvideo_decode: unavailable_offwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 3.78GB (0.20GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%

## VS Code Information
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic

**Comment by isidorn** [comment]
This work for me, bot on OS X and Ubuntu.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please post exact reproducable steps so we can repro on our machines and investigate. Thanks
