### ISSUE TITLE
按住鼠标左键移动输出栏  失去焦点

### ISSUE THREAD

**Issue by zctmdc** [microsoft/vscode#75587]
1.鼠标放在输出栏大小调节处，按下左键，向上拖动
2.拖动后，鼠标失去焦点，
3.释放鼠标左键。
3.靠近边缘处获得焦点，当鼠标移动过快完全失去焦点，靠近后缓慢移动，输出栏跟随鼠标移动

图片示例：https://s2.ax1x.com/2019/06/16/VT2xh9.gif

完全新装的vscode
Windows 10-1903 - 18362.175

**Comment by Tyriar** [comment]
@deepak1556 I think this is a duplicate of that electron issue?

**Comment by zctmdc** [comment]
我更换了一个主题,然后他就自己修复了?
I changed a theme, and then fixed it ?
