### ISSUE TITLE
Autocomplete box is showing weird vertical bars!

### ISSUE THREAD

**Issue by mehdico** [microsoft/vscode#75586]
- VSCode Version: 1.35.1 (updated)
- OS Version: MacOS 10.14.4 
Does this issue occur when all extensions are disabled?: Yes

This is happening in all type of files and all languages.

![Screen Shot 1398-03-26 at 10 57 50](https://user-images.githubusercontent.com/1978735/59560328-9a64d580-9025-11e9-9005-8966d83c0f1b.png)

I have no graphical issue or similar problem in any other app.
after complete remove and install from homebrew problem is gone.

**Comment by Tyriar** [comment]
Let us know if you have an issue again
