### ISSUE TITLE
Anything/extensions using execFile targetting something installed via snap (Linux packages) swallow stdout

### ISSUE THREAD

**Issue by marzolfb** [microsoft/vscode#75581]
Electron/vscode (not sure which but guessing vscode), seems to swallow stdout when executing something that was installed via snap on Linux.

- VSCode Version: 1.35.1
- OS Version: Ubuntu Linux 19.04

Steps to Reproduce:

1. Install a package via snap. It can be any package (even `sudo snap install hello-world`) but I started noticing the problem with go, so let's stick with that:

```
sudo snap install --classic go
```

And the end of that, you should have a go binary available at `/snap/bin/go` (which symlinks to `/usr/bin/snap`)

2. For comparison, [manually install a go distribution](https://golang.org/doc/install#tarball). At the end of that you should have a go binary available at `/usr/local/go/bin/go`.

3. Debug a node app (I first noticed a problem when debugging the vscode-go extension). Create an empty directory and add a new app.js file with these contents and launch a debugger:

```
var cp = require('child_process');
cp.execFile("/snap/bin/go", ['version'], {}, (err, stdout, stderr) => {
    console.log(`/snap/bin/go version: -->${stdout.trim()}<--`); 
});

cp.execFile("/usr/local/go/bin/go", ['version'], {}, (err, stdout, stderr) => {
    console.log(`/usr/local/go/bin/go version: -->${stdout.trim()}<--`);
});
```

You will see:
```
/usr/local/go/bin/go version: -->go version go1.12.6 linux/amd64<--
/snap/bin/go version: --><--
```

what you would expect to see is:
```
/usr/local/go/bin/go version: -->go version go1.12.6 linux/amd64<--
/snap/bin/go version: -->go version go1.12.6 linux/amd64<--
```

Incidentally/correspondingly, when you run `node app.js` in an integrated terminal within vscode you get the unexpected output while if you run the same command outside vscode in a terminal you get the expected output.

Does this issue occur when all extensions are disabled?: Yes

[This issue](https://github.com/nodesource/distributions/issues/663) seems identical/related but I will say I installed the exact same node version (10.15.2) and invoked the node repl in a terminal and ran this:

```
child_process.execFile('/snap/bin/go', ['version'], {}, (err, stdout, stderr) => { console.log(err, stdout, stderr); })
```
and I got back what I would expect:
```
null 'go version go1.12.6 linux/amd64\n' ''
```

So, that leads me to at least narrow it down to being a vscode/electron issue rather than a broader node issue.

**Comment by Tyriar** [comment]
FYI @flexiondotorg

**Comment by joaomoreno** [comment]
@Tyriar This doesn't appear related to VS Code running in a snap package, but to Electron spawning snap processes. Did I get that right?

**Comment by jayschwa** [comment]
@joaomoreno, I do think it's related to the VS Code in a snap. When I run VS Code from a `.deb` installation, I don't encounter the problem.

**Comment by Tyriar** [comment]
Looks like it's tracked in https://github.com/nodesource/distributions/issues/663, you might also want to report to the snapcraft team. Closing since we cannot action this on our side.
