### ISSUE TITLE
**SERIOUS, not able to select code, false text highlighting

### ISSUE THREAD

**Issue by sanjarcode** [microsoft/vscode#75580]
Issue Type: <b>Bug</b>

I just now updated my vscode from v1.34 to the latest v1.35. Actually vscode was showing the same problem on Windows7(where vscode had updated automatically), thinking this was some Windows only glitch, i switched to my other OS, i.e Ubuntu 16.04, it was running v1.34, everything worked fine. After this update, vscode in Ubuntu is behaving the exact same way.

All keywords appear in the same color(red in my case), there are no errors shown though. Can't select text, the selector(color shade) is activated only over spaces, no text is selected. Coding in C/C++.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz (2 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|5.79GB (0.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.9.11
vscode-mysql|for|0.4.0
live-html-previewer|hdg|0.3.0
python|ms-|2019.5.18875
cpptools|ms-|0.24.0-insiders
java|red|0.46.0
code-settings-sync|Sha|3.2.9
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.7.0

(2 theme extensions excluded)

</details>

**Comment by malak1an** [comment]
I'm also having the same problem after updating my Linux Manjar Deepin.

**Comment by Tyriar** [comment]
Can you provide some screenshots of the problems?

**Comment by malak1an** [comment]
When I opened the VSCode, the program asked me to reload the window, and reloading the page returned to normal.

**Comment by sanjarcode** [comment]
Screenshot of the problem.

**Comment by Tyriar** [comment]
@sanjarcode you cannot attach images via email, you need to do it on github.com

**Comment by sanjarcode** [comment]
> @sanjarcode you cannot attach images via email, you need to do it on github.com

[](url)

**Comment by sanjarcode** [comment]
> @sanjarcode you cannot attach images via email, you need to do it on github.com

[](url)

**Comment by sanjarcode** [comment]
![IMG-20190617-WA0003](https://user-images.githubusercontent.com/48156230/59612351-8d85d600-913a-11e9-903f-7d166f1b658b.jpg)
![IMG-20190617-WA0004](https://user-images.githubusercontent.com/48156230/59612352-8d85d600-913a-11e9-8008-fb08fad36761.jpg)

**Comment by Colengms** [comment]
This is an issue with enhancedColorization which was enabled by default in the latest insiders version of cpptools.  We've switched the default to disabled.

The cpptools issue is here: https://github.com/microsoft/vscode-cpptools/issues/3780 

A related VS Code issue is here: https://github.com/microsoft/vscode/issues/75642

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-cpptools/issues/3780

**Comment by sean-mcmanus** [comment]
Fixed with 0.24.0-insiders2. Set the "C_Cpp.updateChannel" setting to "Insiders" to auto-install it.
