### ISSUE TITLE
Remote-SSH: "git.path" is an 'Unknown configuration setting' in remote users settings.json

### ISSUE THREAD

**Issue by Friksel** [microsoft/vscode#75589]
When developing on a remote machine via the Remote-SSH extension vs code doesn't recognise  "git.path" is the remote settings.json: `"git.path" is an 'Unknown configuration setting` in remote users settings.json

- VSCode Version: 1.35.1
- OS Version: Windows 10 host, Ubuntu 19.4 remote (running inside VM on same computer/host)

**Steps to Reproduce:**

1. Login on the remote machine via Vs Code using Remote-SSH
2. Open Command Palette --> `Preferences: Open Remote Settings (SSH: virtualmachine)`
3. See green wave under key and message when hovering over `"git.path"` inside the `.vscode-server/data/Machine/settings.json`

**Does this issue occur when all extensions are disabled?:**
Need Microsoft SSH extensions to be enabled, so no :)

![image](https://user-images.githubusercontent.com/3089978/59562438-0a2a8e80-902d-11e9-9f84-08c09f3b2360.png)

**Additional info**
When looking in the local settings.json on a project with Remote-SSH development enabled and hovering above the `"git.path"` setting vs code does say the `"git.path"` setting can only be applied in the remote machine settings, so it's kind of strange it expects us to put this setting in the remote `settings.json`, but doesn't recognise it there when we actually do that.

![image](https://user-images.githubusercontent.com/3089978/59562503-dc921500-902d-11e9-9a4f-58e1413750e2.png)

**Comment by sandy081** [comment]
It works for me correctly. It does not show any warnings in remote settings.json.

Can you please try again with latest bits?
