### ISSUE TITLE
 Can't move the screen left and right on the touchpad

### ISSUE THREAD

**Issue by mornSea** [microsoft/vscode#75597]
Issue Type: <b>Bug</b>

1. Can't move the screen left and right on the touchpad

2.setting sync can't download sync, but on my other machine， it's  work

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3450 @ 1.10GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|5.67GB (0.96GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.11
vscode-language-pack-zh-hans|MS-|1.35.1
code-settings-sync|Sha|3.2.9

</details>

**Comment by Tyriar** [comment]
> Can't move the screen left and right on the touchpad

Can you clarify what you mean by this?

> setting sync can't download sync, but on my other machine， it's work

You will need to create an issue on the extension's repo https://github.com/shanalikhan/code-settings-sync

**Comment by mornSea** [comment]
I mean: In the VSCode, use the touchpad to slide, move to the left and right, the interface will not change, you can only move by the cursor
 (I am sure the line length exceeds the screen width)

**Comment by mornSea** [comment]
I mean: In the software, use the touchpad to slide, move to the left and right, the interface will not change, you can only move by the cursor
 (I am sure the line length exceeds the screen width)
