### ISSUE TITLE
Postfix templates

### ISSUE THREAD

**Issue by CertainLach** [microsoft/vscode#75595]
There is useful thing in IDEA/another IDE's

You can write `abc.if[TAB]`, and this expands into `if(abc) {}`

There are extensions, which implements this feature, i.e https://github.com/ipatalas/vscode-postfix-ts, but it would be awesome to see this as built-in

**Comment by jrieken** [comment]
The extension is pretty good and extensions are easy to install. Copying extension functionality into the product will give people reason to call us bloaty

**Comment by CertainLach** [comment]
@jrieken, this extension supports only one language, if something like this gets official support, it can be implemented in many language plugins (since postfix templates require language support), and anyone can easily use them as a snippets without installing plugin for every language and having templates in plugin configurations
