### ISSUE TITLE
Can't use backspace when search box is onscreen

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#75596]
- VSCode Version:1.35.1
- OS Version: Ubuntu Bionic

Steps to Reproduce:

1. Open any file and use Ctrl+S to search anything.
2. Try to use backspace with that search popup open, it doesn't works.

**Comment by rebornix** [comment]
@gurrrung do you mean deleting text in the find widget doesn't work?

**Comment by gurrrung** [comment]
@rebornix Actually, it's already fixed in new stable release. Closing issue.
