### ISSUE TITLE
Problemspanel does not refresh when rename one or more files

### ISSUE THREAD

**Issue by tb2761** [microsoft/vscode#75598]
Issue Type: <b>Bug</b>

When I rename a file, the problem area displays information such as lint errors of the old file. If you tap the error, the error message that the file does not exist is displayed. But for the new or renamed file, no info is displayed.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.41GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Tim/Git%20Projects/Deskmodder_Flutter|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-yaml-preamble|bie|0.0.4
bracket-pair-colorizer-2|Coe|0.0.28
dart-code|Dar|3.1.0
flutter|Dar|3.1.0
gitlens|eam|9.8.2
vsc-material-theme|Equ|2.9.0
vsc-material-theme-icons|equ|1.0.6
kotlin-formatter|esa|0.0.6
bloc|Fel|0.8.0
auto-close-tag|for|0.5.6
vscode-pull-request-github|Git|0.8.0
todo-tree|Gru|0.0.135
rest-client|hum|0.21.3
output-colorizer|IBM|0.1.2
XMLLanguageSupport|IBM|0.0.1
vscode-github|Kni|0.30.2
vs-color-picker|lih|1.0.0
Kotlin|mat|1.7.0
azure-account|ms-|0.8.4
awesome-flutter-snippets|Nas|2.0.2
color-highlight|nau|2.3.0
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.4.1
WebTemplateStudio-dev-nightly|WAS|0.0.1915901
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by sandy081** [comment]
Please file the issue against the extension that is generating these problems. It is responsibility of the extension to handle these cases.
