### ISSUE TITLE
Settings UI Removes Settings JSON Comments

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#75599]
**Problem**
 When adding comments above a modified setting in the settings.json file, and then modifying that same setting in the settings UI, all comments above that setting get removed. This happens with both line comments and block comments, and happens regardless of whether or not there are any line breaks after the comment.

**Sidenote**
This probably wouldn't be an issue [if the settings UI supported comments](https://github.com/microsoft/vscode/issues/68184).

**Info**
- VSCode Version: Version 1.35.1
- OS Version: macOS Mojave 10.14.4

**Reproduce**

1. Open the setting.json file and modify a setting along with a comment above the modified setting, like so:

```
// My Comment
"editor.tabCompletion": "on"
```

2. Save the settings.json file (if autosave isn't enabled)

3. Open the settings UI. Go to the setting that you modified (in this example, `editor.tabCompletion`) and set it back to the default.

4. Go back into the settings.json file. Note that any comments you added above that modified setting are now gone.

**Extensions**
Does this issue occur when all extensions are disabled?: Yes

**Insiders**
Does this issue occur on Insiders?: Yes

**Comment by roblourens** [comment]
When you set the setting to its default value, then the setting itself is just removed from the settings.json so it doesn't get cluttered with settings at their default values. When we do that, I think it's by design that we remove the comments above too. If you want to be able to mange settings at their default values and comments for settings, then you need to just use the json editor.

**Comment by jabacchetta** [comment]
@roblourens Fair enough. I might suggest adding a confirmation when a comment exists, at the very least. Otherwise users will find out about this the hard way, when they've lost months of comments without any indication (which I believe would only be recoverable if they have the Settings Sync extension installed/synced... and even then, they would need to scour through the many revisions that would likely exist by the time they noticed).
