### ISSUE TITLE
open file and press space bar

### ISSUE THREAD

**Issue by HirenSJ** [microsoft/vscode#75590]
Issue Type: <b>Bug</b>

After latest update something weird happening
open any file in visual studio code and click on space should be edit file and add space but now, it's moving cursor to next character instead of editing file.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.379
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.4
vscode-react-native|msj|0.9.3
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0
vscodeintellicode|Vis|1.1.6
vim|vsc|1.8.1

</details>

**Comment by alexandrudima** [comment]
@HirenSJ I cannot reproduce. Can you please try to disable all your extensions and also remove any customizations you might have done to `keybindings.json` ?
