### ISSUE TITLE
Comments can show/hide code

### ISSUE THREAD

**Issue by gigatesseract** [microsoft/vscode#75591]
Can there be a feature where comments can toggle visibility of code ? Say, I have a lot of classes in my code. Instead of hiding them one by one, can I have comments (maybe of a specific format)at the top of the first class and bottom of the last class that can hide all the code in between ?

I am going through pending issues still. I will close if I see if this issue already exists. Any inconvenience is regretted.
Thanks.

**Comment by aeschli** [comment]
We have the region comments.
See https://code.visualstudio.com/docs/editor/codebasics#_folding

Is that what you are looking for?

**Comment by gigatesseract** [comment]
Yes!!!!! I couldn't search it properly because I didn't know its called "folding". 
Many thanks!
