### ISSUE TITLE
[c++] Syntax highlighting gets confusing when defining a reference to an array.

### ISSUE THREAD

**Issue by LittleSaya** [Microsoft/vscode#756]
If a function's parameter is a reference to an array of constants, the data type will be recognized as a function declaration:
![1](https://cloud.githubusercontent.com/assets/16049823/11446150/20fcb222-956e-11e5-98ed-31846c9e14ec.png)

If a reference to an array of constants is defined in a block, the data type will not be highlighted:
![1](https://cloud.githubusercontent.com/assets/16049823/11449777/e2181876-95bd-11e5-86d2-36e44139cdea.PNG)

If a reference to an array (not constant) is defined in a block, the data type will be recognized as a function call:
![1](https://cloud.githubusercontent.com/assets/16049823/11449690/3100d36e-95ba-11e5-8974-11be8480d981.PNG)

Version of VS Code: 0.10.2

Color theme: Dark(Default color theme)

**Comment by LittleSaya** [comment]
Oh, the color theme I chose is Dark, Default color theme.

**Comment by alexandrudima** [comment]
@LittleSaya VSCode uses the C++ textmate definition from https://github.com/textmate/c.tmbundle . Fixing the bug there will have it fixed for all editors consuming the grammar.

**Comment by aeschli** [comment]
It would be great if you can file these against https://github.com/atom/language-c.
Once fixed there I will update our grammar.
