### ISSUE TITLE
Add a "Copy" button to the "About" window

### ISSUE THREAD

**Issue by jcollum** [microsoft/vscode#75600]
It would be very helpful if I could press a button in the About window and get the OS name, OS version and VS Code version with one click. It will help bug reporters and the dev team.

**Comment by gjsjohnmurray** [comment]
Mine already has one:
![image](https://user-images.githubusercontent.com/6726799/59591232-939d9780-90e5-11e9-853e-97883bce954a.png)

What version are you running? On what platform?

**Comment by jcollum** [comment]
OSX

**Comment by Tyriar** [comment]
I think the reason there's no copy button on macOS is because you can select the text, whereas on Windows you cannot.

**Comment by jcollum** [comment]
Please don't close a Feature Request with "as designed". I'm asking for an improvement. 

This is box on Mac: 

![image](https://user-images.githubusercontent.com/704514/59779469-29affa00-926d-11e9-9dbc-a9bdd5a308a9.png)

It has much less info than the windows version. And it doesn't have a copy button. A copy button would save the user time when reporting bugs. Also, would I know that the text is selectable when looking at it? Not really.

**Comment by Tyriar** [comment]
> A copy button would save the user time when reporting bugs.

Including this information is already handled for you by going through the issue reporter:

<img width="322" alt="Screen Shot 2019-06-19 at 11 27 06 AM" src="https://user-images.githubusercontent.com/2193314/59790683-5a039280-9285-11e9-8170-19a03dd9eb6c.png">

**Comment by jcollum** [comment]
Ah I see thanks
