### ISSUE TITLE
Enhanced quick suggestions in strings

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#75609]
With `editor.quickSuggestions`, you can set `strings` to `true` in order to have quick suggestions appear while typing inside of a string. But that only appears to suggest snippets and words (if `editor.wordBasedSuggestions` is also set to `true`).

It would be nice if all suggestion types (e.g. values) were available. The primary use case for this that I've come across is when using the names of values as labels to console messages. Rather than having to type in the full value name, I'd like to be able to auto-complete it. Currently this will only work if the value is in the file (making it appear as a word based suggestion).

**Comment by jrieken** [comment]
> But that only appears to suggest snippets and words (if editor.wordBasedSuggestions is also set to true).

There is no filter or such - the setting is purely about triggering suggest and providers (contributed by extensions) must then compute meaningful/semantic suggestions. You see words and snippets because they don't check the context but always suggest everything. Please file issues against the language/extension in question.

**Comment by jabacchetta** [comment]
@jrieken Not sure I'm understanding you correctly. This issue includes built-in language extensions (e.g. JavaScript, TypeScript) where the context is otherwise analyzed just fine.

Reproduce:

1. Add the following setting:
```json5
"editor.quickSuggestions": {
    "strings": true
  }
```

2. Inside a JavaScript/TypeScript file, type out the following:
```JavaScript
const myValue = 1;
console.log('myValue: ', myValue);
```

Notice that when typing myValue inside the string, you only get the suggestion because the type of that suggestion is a _word_.

**Comment by jrieken** [comment]
> This issue includes built-in language extensions (e.g. JavaScript, TypeScript)

Yeah, you said that only now. Thanks for clarifying. Regarding `console.log('myValue: ', myValue)` - what should TypeScript/JavaScript propose in that case? Do you expect semantic completions and iff so what would that be?

**Comment by jabacchetta** [comment]
Taking a similar example as the one above:

```javascript
const myValues = {
  one: 1,
};

console.log('myValues.one', myValues.one);
```

When string suggestions enabled, I would expect to be able to auto-complete `myValues.one` the same way that we can outside of the string.

**Comment by jrieken** [comment]
>  I would expect to be able to auto-complete myValues.one the same way that we can outside of the string.

But how would TypeScript know that? There are no semantics defined for strings and I think word based completions is the best working solution here. Should IntelliSense not show anything you type `console.log('fooValue')` even tho that word exists in the document?
