### ISSUE TITLE
cannot format css code

### ISSUE THREAD

**Issue by targboss** [microsoft/vscode#75608]
Issue Type: <b>Bug</b>

cannot format css code by clicking on ctrl+k ctrl+f like the other languages

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

**Comment by octref** [comment]
There's a wide range of CSS formatters in the market place: https://marketplace.visualstudio.com/search?term=css%20formatter&target=VSCode&category=All%20categories&sortBy=Relevance
