### ISSUE TITLE
[Feat] Add project support

### ISSUE THREAD

**Issue by Luchillo** [Microsoft/vscode#7560]
One of the nice things Sublime has over VS Code is workspaces and projects, Sublime allows to set a workspace with configs for it, as well as saving those to load the workspace later.

However the feature i want to reccomend is projects, Sublime is great in that regard since the projects are kind like the workspaces, just that they are remembered and is very easy to change between projects with a few keystrokes.

Currently VS Code doesn't have those concepts so i'm forced to open the top folder that contains all the projects i'm working / had worked on, that's a lot of folders to see, i like clean development environment so it would be a great addition to be able to set projects with just the folders or projects i need, and easily change between projects.

Lastly when i mean change between projects i don't mean like the workspaces of Sublime that we need to change by searching the workspace config file in the root of the workspace or wherever you saved it, i mean like Sublime projects that remember the last ones that were used and with a keyboard shortcut allow to see a list of those and quick change between them.

**Sumary:**
* Add support for multiple base folders in same window.
* Add support for a project manager that allows to save the previous item as a project for easy dev env restoration.
* Add an easy way to switch between projects recently used.

I think this would make VS Code even better, any thoughts about this?

**Comment by Luchillo** [comment]
Example comparison between the way Sublime shows just the selected folders:
![image](https://cloud.githubusercontent.com/assets/9698639/15986054/ff65b460-2fc3-11e6-9db2-86158bb7b86d.png)

And how VS Code forces me to open the parent folder to have multiple folders in same editor:
![image](https://cloud.githubusercontent.com/assets/9698639/15986072/44ffdc12-2fc4-11e6-9b11-a9d9d000b9b6.png)

**Comment by sandy081** [comment]
duplicates #396

**Comment by Luchillo** [comment]
@sandy081 Not quite a duplicate, maybe for the first point of this request about multiple folders, but what about the project manager and quick switch projects?

**Comment by sandy081** [comment]
@Luchillo I think #396 even though description of #396 is not talking about 
- project manager
- quick switch projects

at the end of the day all these will be under same umbrella **supporting multiple projects**

I would rather continue the discussion related to this there rather than in a separate thread. Hence closed this as a dup.

Thanks

**Comment by Luchillo** [comment]
Ok thanks.
