### ISSUE TITLE
launch.json: "${command:pickProcess}" prompts for a process to attach to *before* running pre-launch tasks

### ISSUE THREAD

**Issue by mklement0** [microsoft/vscode#75604]
As of VSCode v1.35.1, a launch configuration defined in `launch.json` that uses `"${command:pickProcess}"` as its `"processId"` value - in order to prompt for a process to attach to - does so *before* running any pre-launch tasks (`preLaunchTask` property).

* Is this by design?
* Is there a way to reverse this order?

The reason I want my prelaunch task to run _first_ is twofold:

* generally, since my prelaunch task includes building, I want the launch to be aborted if building fails.

* specifically, my prelaunch task _creates_  the process that I then want to attach to.

Taking a step back, my ideal solution would be to have the prelaunch task not only _create_ the process to attach to, but to have the launch configuration _automatically attach_ to it afterwards, but I haven't found a way to do that, given that:

*  starting the debugger from the command line isn't supported yet - though support is being considered - see #10979

* there seems to be no way to populate a launch-configuration property from an arbitrary shell command (you can only call VSCode-internal commands via `${command:...}`).

Note: I hit this limitation when trying to debug binary PowerShell modules via an external PowerShell console. I've since realized that the C# debugger _automatically_ attaches to any external process created via a `"request": "launch"` launch configuration, so launching a PowerShell console that way (with a startup command that imports the binary module) is sufficient.

**Comment by RandomGHUser** [comment]
I too am having this exact same problem.  I would expect my prelaunch task (which stops my remote process, builds and pushes my project to the remote box, then restarts the remote process) to finish executing before picking the process to attach to.

There are easy enough workarounds, but it should be able to work in a one-step process.

**Comment by weinand** [comment]
@isidorn what is the order of resolving variables and running the prelaunch task?

**Comment by isidorn** [comment]
We first resolve the varialbes and then run the `preLaunchTask`. [Code pointer](https://github.com/Microsoft/vscode/blob/3fc780dc7caf63ffd23ed1664cdfe17029f2d28d/src/vs/workbench/contrib/debug/browser/debugService.ts#L398)

**Comment by mklement0** [comment]
Understood re current design, but I think there is a _usability_ issue here:

It doesn't make sense to pick a process _first_, if the pre-launch task can fail.

I understand that variable resolution coming first is what triggers the untimely prompting, but I wonder if an exception can be made in this case: defer any `"${command:pickProcess}"` actions until _after_ the pre-launch tasks have run _successfully_.

If not all cases of untimely prompts can reliably be _inferred_ (given that there can be arbitrary extension-supplied commands such as `extension.pickNodeProcess`), perhaps an opt-in property could solve the problem.
