### ISSUE TITLE
Invisible characters still "unreadable"  in Default Dark Colour Theme

### ISSUE THREAD

**Issue by aplatypus** [microsoft/vscode#75610]
- VSCode Version: 1.35.1
- OS Version:     Ubuntu 18.10

    Version: 1.35.1
    Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
    Date: 2019-06-12T14:27:31.086Z
    Electron: 3.1.8
    Chrome: 66.0.3359.181
    Node.js: 10.2.0
    V8: 6.6.346.32
    OS: Linux x64 5.0.7-050007-generic

**Problem**:

- For a long time I thought there was no "Render Whitespace" feature at all.
  - When I used the "Render Whitespace" from the View menu 
  - I did/do not see any spaces, returns, etc.
-  Recently I really needed to be able to check on TABS and other control characters and found VS Code was not going to show me anything
   - Even though I could use `hexdump` and see non-printing characers in the file.
-  When I really really look very closely there are indeed invisible characters displayed.
    - they are so small and faint that they might as well be invisble.
    - one may not read them from a comfortable seating position
- In Dark mode I suggest these characters use a brighter colour that will stand-out and a larger font size as well as the dark background tends to bleed the edges.

Steps to Reproduce:

1.  Set DARK Theme
2.  Choose "Toggle Render Whitespace" from View menu
3.  Choose "Toggle Control Characters" from View menu
4.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Is this what you're seeing?

![image](https://user-images.githubusercontent.com/2193314/59610576-875a1000-90ce-11e9-8137-15e9de49bf9c.png)

You can change your theme or override by adding this setting:

```
  "workbench.colorCustomizations": {
    "editorWhitespace.foreground": "#ff0000"
  },
```

![image](https://user-images.githubusercontent.com/2193314/59610643-a2c51b00-90ce-11e9-92c1-a7116d03b13b.png)
