### ISSUE TITLE
csproj support?

### ISSUE THREAD

**Issue by robertleeplummerjr** [Microsoft/vscode#7561]
Some pretty fantastic, and a couple humorous events events in the Microsoft timeline, to build my case:
* November 20, 1985 - Windows 1.0 is released and changed the world
* August 24, 1995 - Windows 95 was released and changed the world
* Sometime in 1997 - Boston is born, later to be released as Visual Studio, and changed the world
* January 1999 - Simple Managed C (SMC) was started
* September 5 2000 - Balmer announces his love for this company and changed the world https://www.youtube.com/watch?v=04FOUQpnGsc
* January 2002 - SMC (now C#) v1.0 is released and changed the world
* March 6 2008 - "Developers, Developers, Developers!" https://www.youtube.com/watch?v=oioj24KQRvM and changed the world
* March 18 2014 - `Roslyn.Says("Hello World"); //and changed the world` https://github.com/dotnet/roslyn/commit/3611ed35610793e814c8aa25715aa582ec08a8b6
* November 13, 2015 - VSCode is public! https://github.com/Microsoft/vscode/commit/8f35cc4768393b25468416829e980d7550619fb1 and changed the world
* Currently - Visual Studio and VSCode are advertised together - https://www.visualstudio.com/en-us/visual-studio-homepage-vs.aspx and visual studio code is changing the world

So much went into the creation of VSCode and I admire the work that has lead up to it, but VSCode apparently has no means of running asp.net csproj projects. Rather than create a new launch.json file in order to do so, shouldn't there just be an import capability?

If the reply you are currently thinking of starts with: "Well this is open source software, scratch your own itch", does that mean that Microsoft is essentially abandoning the existing countless C# projects?  Every event in the timeline above (even the Ballmer ones) starting at 1999 and afterward involved either directly or indirectly C#, it'd be nice if we could simply import our existing projects.

After all: "developers, developers, developers"

**Comment by robertleeplummerjr** [comment]
https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/experimental-net-core-debugging-in-vs-code/

**Comment by robertleeplummerjr** [comment]
http://stackoverflow.com/questions/37062818/how-can-visual-studio-code-on-osx-import-sln-csproj-and-run

**Comment by robertleeplummerjr** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/283#issuecomment-217493910

**Comment by DustinCampbell** [comment]
@robertleeplummerjr: I definitely appreciate your passion on this particular issue. There's a lot we can do to make the C# support for VS Code even better! However, the folks working on VS Code itself aren't those who would add support for ASP.NET cspoj projects. Could we continue the conversation over on the C# extension repo?  (https://github.com/OmniSharp/omnisharp-vscode)

**Comment by dbaeumer** [comment]
@robertleeplummerjr OK for you to move the discussion over ?

**Comment by robertleeplummerjr** [comment]
Already done.  Thanks for the helpful bump.
