### ISSUE TITLE
Drastic performance degradation since upgrade

### ISSUE THREAD

**Issue by Cazaimi** [microsoft/vscode#75629]
- VSCode Version: 1.35.1
- OS Version: macOS Mojave 10.14.5 (18F132)

Steps to Reproduce:

1. VSCode slows down drastically on start up and when handling large text files.

**Comment by rebornix** [comment]
@Cazaimi sorry for reaching out late. Could you please provide more info about how to reproduce, what kind of files you are working on?

**Comment by navidalvee** [comment]
in some cases, I have seen if you have 20000 above lines in any extended files 
your vscode could lag and or some extension might need to restart several times
