### ISSUE TITLE
file select bug

### ISSUE THREAD

**Issue by landerqi** [microsoft/vscode#75624]
- VSCode Version: 1.35.0
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. select a image file, then press F2 to change its name.
2. I cannot select files in other formats during the name change process.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
> I cannot select files in other formats during the name change process.

@landerqi what do you mean here? You start to rename and click another item in the tree and rename aborts?

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
We fixed a similar bug recently.

**Comment by landerqi** [comment]
> Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> We fixed a similar bug recently.

I recorded a video to describe the problem:
https://www.bilibili.com/video/av56064370/

**Comment by isidorn** [comment]
That is using vscode stable. Please use vscode insiders.  https://code.visualstudio.com/insiders/
