### ISSUE TITLE
[BUG] Extension Host Terminated Unexpectedly - Version: 1.36.0-insider

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#75623]
VS Code Insiders edition tends to throw a splash error window that says:
"Extension Host Terminated Unexpectedly"  as shown in this screenshot.
when either installing an update for the program  or actually starting the program.
Its been happening from the last 3 recent prior updates of the Insiders Edition.
Version: 1.36.0-insider (system setup)
Commit: 11b88a3323878a98b418e4efca77e7afabd50d01
Date: 2019-06-17T05:17:47.485Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601
.
![Constant Error in VSCode Insiders Edition](https://user-images.githubusercontent.com/18384135/59593857-b1a4d100-90c0-11e9-96dd-b7c8e6bdb25f.png)

**Comment by iqmeta** [comment]
https://github.com/microsoft/vscode/issues/75267

**Comment by Tunscopi** [comment]
I'm able to repro this issue on regular and insiders version.
For me, the issue seems to be with the Microsoft C/C++ extension.

I got a fresh install of vscode (Insiders version) and started installing my extensions one after the other. Vimvscode etc. 
As soon as I installed the ms-vscode.cpptools extension, I receive a "Extension host terminated unexpectedly". Uninstalling it did nothing.

Only getting a fresh install AND making sure not to install the cpp extension allow me to use Vim and my other extensions without this error.

**Comment by iqmeta** [comment]
More problems with update:
![image](https://user-images.githubusercontent.com/7533842/59665014-666aeb00-91b2-11e9-886c-4a7bbe8968ac.png)

[2019-06-18 10:16:28.948] [main] [error] [VS Code]: render process crashed!
**Any Infos how to turn on verbose logging?** For AppData\Roaming\Code\logs\

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (5.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by iqmeta** [comment]
Gone back, no problems on this version:

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by sandy081** [comment]
All, please provide following

- What are the extensions you are running with?
- Open Developer Tools (Help -> Developer Tools) and provide us the logs you see in the console
- Open the output panel and provide us the logs of Extension host and Window
