### ISSUE TITLE
Allow baseUrl, paths, rootDirs in tsconfig files

### ISSUE THREAD

**Issue by Jonatthu** [Microsoft/vscode#7562]
The compiler works fine, but the intellisense on VS Code does not work.
Any solutions or workarounds for this? 
![image](https://cloud.githubusercontent.com/assets/3742176/15986857/e49889dc-2fc8-11e6-9ba5-9ffb901d31f8.png)

**Comment by Jonatthu** [comment]
The solution is: 

Visual Studio Code

Update .vscode/settings.json with the following:

"typescript.tsdk": "<path to your folder>/node_modules/typescript/lib"
More information is available at VSCode documentation.

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#visual-studio-code

**Comment by dbaeumer** [comment]
@Jonatthu which version of the tsc are you using. I suspect some @next version. If so using the tsdk variable is the right thing to do since VS Code in the box ships with the stable 1.8.x branch which doesn't have that feature yet.

**Comment by Jonatthu** [comment]
Yes, I already found and posted the solution thanks a lot for your help.

**Comment by dbaeumer** [comment]
Closing the issue then.

**Comment by MarkPieszak** [comment]
@Jonatthu How did you setup your tsconfig? I'm unable to get it to see the files and I have VSCode pointing at the 2.0 TS beta (tsdk).

**Comment by Jonatthu** [comment]
Open your VS Code and press f1, type workspace settings,
then type "typescript.tsdk" and the description says that you need to put a string specifying the path of the tsdk of the newer typescript that you want target, usually on root node_modules of your projects.

Greetings

**Comment by MarkPieszak** [comment]
I had that setup, I just had my tsconfig setup wrong got it now. Only annoying thing is that you have to restart vs code when you change paths in the tsconfig :(

**Comment by liviuignat** [comment]
Hi guys,

I am struggling with this for some time. It works perfect from console, but VSCode cannot still find the relative module paths. So, I don't get any autocompletion and editor help because of this. Bellow you can see a screenshot. Any help is really appreciated. 

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "baseUrl": "./src",
    "rootDir": "./src",
    "declaration": true,
    "lib": ["es7", "es2017"]
  },
  "files": [
    "src/**/**"
  ],
  "exclude": [
    "node_modules"
  ]
}

// settings.json
{
    "typescript.tsdk": "./node_modules/typescript/lib",
    "typescript.check.tscVersion": false
}
```

<img width="1107" alt="screen shot 2016-11-29 at 12 55 06" src="https://cloud.githubusercontent.com/assets/2430288/20709014/1b080bfa-b633-11e6-9dc3-80dcc1e92035.png">

**Comment by dbaeumer** [comment]
@waderyan can you have a look.

**Comment by waderyan** [comment]
@liviuignat can you open a separate issue and share a link to your workspace? 

One issue you may be having is that `files` does not support glob patterns. You'll want to use include. See the docs [here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
