### ISSUE TITLE
Freeze after some time on Linux 5.1.x

### ISSUE THREAD

**Issue by mgarstecki** [microsoft/vscode#75625]
Issue Type: <b>Bug</b>

**Reproduction:**
- Open vscode.
- Leave it in the background for some time.
- Try to switch back to vscode.

**Expected result:**
- vscode gets displayed and can be manipulated.

**Actual result:**
- the vscode window is frozen, doesn't refresh, and shows the last open app (or desktop background, ... It's the pixels that were previously shown where vscode should be displaying itself).

**Additional info:**
- I haven't identified a clear scenario that produces this: time to reproduction is random, happened with and without a system suspend... Haven't yet experienced it during active use of the app however.
- Started happening around the 5.1.x kernel updates (don't remember which one).
- Seems to impact other electron apps, see [here](https://forum.manjaro.org/t/electron-apps-crashing-randomly/81717/6)
- Currently trying with --disable-gpu to see if it's acceleration related.

VS Code version: Code - OSS 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-14T21:57:30.073Z)
OS version: Linux x64 5.1.9-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.44GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
day-night-theme-switcher|fre|0.1.2
terraform|mau|1.3.12
Go|ms-|0.10.2

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
