### ISSUE TITLE
Maximized editor group when debug step into file

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#75628]
I made a gif and sketch to help understand, sorry for poor english.
i very love how `"workbench.editor.revealIfOpen": true` allow me easy manage my workflow.
The issue is when i use a  debugger, and nav with step breakpoint.
If the step need to go inside another file inside another group editor, it seem not work, the file does not maximize automatically, i need click manually on the files.

![idN3o](https://user-images.githubusercontent.com/24865815/59601029-de60e480-90d0-11e9-976e-2aa8e8b1d688.png)
As you can see, when i click on `nextStep`, the `breakPoint` change and highlighted into the next file in editor groupe from bottom, but the editor groupe not reveal `(maximized)` automatically. 
I need manually click on the slot to maximize the groups editor.

![maximize debug](https://user-images.githubusercontent.com/24865815/59600763-22071e80-90d0-11e9-966f-e99e128bc016.gif)

Do you have something i can add in `settings.json` to allow this ?
is missing setup ?
thanks a lot guys and keep nice work.

i ask question before on stackoverflow, but it seem nobody know.
https://stackoverflow.com/questions/56620528/reveal-editor-when-debug-with-breakpoint-step

**Comment by djmisterjon** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Maximize editor group auto sizing stops working after closing the sidebar (#70083)](https://www.github.com/microsoft/vscode/issues/70083)

no is not a duplicate, i search before and ask on stackoverflow.

**Comment by isidorn** [comment]
This should be fixed in latest vscode version.
If you still see this please let us know and we will reopen this issue.
Thank you
