### ISSUE TITLE
Huge slowdown in canvas rendering on Electron 4

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75634]
I've seen it on my macbook, seems to happen randomly though and not all the time. When I saw it a frame would take 2-3 seconds to render. Using WebGL (https://github.com/xtermjs/xterm.js/pull/1790) would probably workaround the problem but I haven't verified that yet (it's getting pretty close to being able to add to VS Code as an opt-in).

When it happened to me the DOM renderer was recommended as expected, it needs 10 or so frames to render though so that can take some time.

@deepak1556 can you find the upstream issue for this you linked earlier?

**Comment by Tyriar** [comment]
Not sure if minimap is affected, drawImage seemed to be the problem and I don't think it uses that.

**Comment by deepak1556** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=872117 this was the major canvas regression bug. But the fixes were backported to 69 and is present in the version of electron we use.

**Comment by Tyriar** [comment]
Saw this today on Windows 10:

![image](https://user-images.githubusercontent.com/2193314/60118970-426b5480-9732-11e9-8b63-94de13c5f8b6.png)

![image](https://user-images.githubusercontent.com/2193314/60118982-48f9cc00-9732-11e9-8a7e-853cc22da149.png)

**Comment by bpasero** [comment]
@Tyriar 
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](hhttps://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by Tyriar** [comment]
This is tough to reproduce so let's close this, I'll reopen if I see it in Electron 6
