### ISSUE TITLE
initializing js/ts language features never completes

### ISSUE THREAD

**Issue by incompletude** [microsoft/vscode#75638]
I'm also getting the loading indicator for a few versions now. I'm working on Vue.js (Nuxt.js) project, and not using Typescript at all. The loading indicator is annoying and distracting, so I'm trying to suppress it, and I know there are several issues about the same problem, but I could not find a way to do this.

Can someone provide a way to suppress this message or point to a previous vscode version without this bug?

Thanks

**Comment by incompletude** [comment]
> /needsMoreInfo

What info is needed?

**Comment by mjbvz** [comment]
Please use the issue template and follow the guide to report issues
