### ISSUE TITLE
VSCODE has "private gallery"

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#75631]
- VSCode Version: 1.34.0
- OS Version: win10

Steps to Reproduce:
Now I am creating a lisp extension for VSCODE. And I see Visual studio can support the private gallery, now the VSCODE can support it?
https://devblogs.microsoft.com/visualstudio/create-a-private-gallery-for-self-hosted-visual-studio-extensions/

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
That's VS documentation, not VS Code
