### ISSUE TITLE
Output panel is really slow on web

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75641]
Repro:

1. Open web
2. Set log level to trace
3. Open a terminal
4. Open output panel
5. Switch to remote ext hots channel

10 seconds to show white text, 10 more seconds to show colored text.

![image](https://user-images.githubusercontent.com/2193314/59621544-67cde200-90e4-11e9-8cc1-8348895e2ea1.png)

I saw this on Windows, where the terminal environment is very large and contains heaps of `npm_*` variables.

**Comment by sandy081** [comment]
@Tyriar Are you seeing same issue when you are opening a file in editor?

**Comment by rebornix** [comment]
`[2019-06-18 09:49:08.411] [exthost] [debug] Terminal process launching on ext host` generates 10k characters in a line on my machine and when it's being opened in the editor, you can see the same hang as well. I can't trigger the same colorization in Code Insiders so not sure yet if it's because that wasm is slow.

**Comment by rebornix** [comment]
Latest master allows you to set max tokenization line length limit without reloading the workspace, which should unblock our self hosting. The next step should be looking into why onigurma-textmate performs much worse than native.

**Comment by bpasero** [comment]
Could https://github.com/microsoft/vscode/issues/76076 be related?

**Comment by bpasero** [comment]
@Tyriar do you still see this?

**Comment by Tyriar** [comment]
It's still bad, but not as bad.

![image](https://user-images.githubusercontent.com/2193314/65974416-c9128a80-e421-11e9-8d1f-81818211a9b6.png)

**Comment by bpasero** [comment]
@Tyriar with the new work from Alex, can you quickly check if this still reproduces?

**Comment by Tyriar** [comment]
So much better:

![image](https://user-images.githubusercontent.com/2193314/81937337-5d43f300-95a8-11ea-8176-a5dd95365525.png)

**Comment by bpasero** [comment]
Thanks a lot, kudos to @alexdima for this perf gain ❤️
