### ISSUE TITLE
Breadcrumbs enhancement: Pin each header to the top of the window

### ISSUE THREAD

**Issue by vexx32** [microsoft/vscode#75645]
See the GIF in this tweet: https://twitter.com/jckarter/status/1140131108564062213

Basically, a setting to be able to toggle whether all the header lines for code sections would become "pinned" to the top of the code pane as you scrolled down, and becoming automatically unpinned when you leave that section.

Bit like breadcrumbs, only a more intuitive and accessible display, I think? 

/cc @TylerLeonhardt

**Comment by jrieken** [comment]
Adding screen shot from attached gif

<img width="599" alt="Screenshot 2019-10-04 at 13 49 53" src="https://user-images.githubusercontent.com/1794099/66205519-e22f6b80-e6ad-11e9-93eb-6927e793395d.png">

**Comment by gulshan** [comment]
I think this is same as my proposal #26757

**Comment by jrieken** [comment]
Yes, it it. Thanks for helping!

**Comment by vexx32** [comment]
Time to track a new issue. Thanks fellas! 😊
