### ISSUE TITLE
Text selection highlight is not shown on decorations w/background colors

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#75642]
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

If a decoration is set and includes a background color, selection highlight is not rendered.

In the following image, text decorations (with a background value) exist on the keywords and symbols, but not the whitespace.  The entire section is selected.  Notice that the whitespace receives a selection highlight color, but the decorated text does not.

![image](https://user-images.githubusercontent.com/49173979/59624278-31479580-90eb-11e9-8560-0d8189a51a13.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-cpptools/issues/3780

**Comment by Colengms** [comment]
@Tyrair , This was duped incorrectly.  The cpptools issue should be duped to this, not vice version.  (I work on cpptools).  The issue is, generally, that if there is a background color specified on a TextEditorDecoration, no highlight selection color will be applied to it when that text is selected.  We can work around the issue in cpptools when the desired background color happens to be the same as the editor background color (so, setting a background color is unnecessary, and avoided).  But, the issue remains in the general case.  Please apply selection highlight color on TextEditorDecorations when they have a background color specified, and their text is selected.

**Comment by Colengms** [comment]
![image](https://user-images.githubusercontent.com/49173979/59874575-61916d00-9353-11e9-8ef0-a9d0a410a189.png)

**Comment by Tyriar** [comment]
@Colengms ah sorry I thought it was just a limitation of how you did semantic coloring but it I've also seen this issue in the git diff decorations:

<img width="286" alt="Screen Shot 2019-06-20 at 2 31 10 PM" src="https://user-images.githubusercontent.com/2193314/59882849-26e5ff80-9368-11e9-8f12-f9f35872550b.png">

**Comment by alexandrudima** [comment]
This is as designed. Using a color with opacity 100% will result in other things not being visible. The solution is to use a color with an opacity < 100%.

**Comment by Tyriar** [comment]
cc @joaomoreno, see the image in https://github.com/microsoft/vscode/issues/75642#issuecomment-504207975

**Comment by Colengms** [comment]
I'm almost certain this should not have been closed.  The proposed solution does not work.  Setting the (only available) "opacity" property of DecorationRenderOptions to 0.5, for example, has no effect on the visibility of the text selection highlight.  As you can see, both the selected and unselected text (w/ red background) in the example below appear the same, despite opacity 0.5 being used.

![image](https://user-images.githubusercontent.com/49173979/62484341-d63b3200-b76e-11e9-940c-e5fd860ba34c.png)

Using an alpha channel value in the background color itself does not appear to be accepted.

The opacity property would seem to only apply to the foreground color.  Setting the editor background to another color, for example, I can see that the decoration's background color is not blended with it at all.

![image](https://user-images.githubusercontent.com/49173979/62484385-ef43e300-b76e-11e9-9458-addd8cd8b76e.png)

Furthermore, even if this worked, it would not be a good design to require that anyone who sets a background color on a decoration to use (at this point ambiguous) semi-transparency in order to avoid an issue that would cause user text selection not to be apparent when selecting text within the decoration.  The text selection color should either be blended/inversed with the background color, or replace the background color, so that selection is apparent.

**Comment by alexandrudima** [comment]
I am seeing something strange. I am seeing different results running from source or running from a built version at the same commit. I am using the following to reproduce:

* `package.json`:
```js
{
    "name": "75642",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.31.0"
    },
    "activationEvents": ["*"],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    const transparentRed = vscode.window.createTextEditorDecorationType({
        backgroundColor: '#ff000033'
    });
    const red = vscode.window.createTextEditorDecorationType({
        backgroundColor: '#ff0000ff'
    });

    const decorate = function() {
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            return;
        }
        editor.setDecorations(transparentRed, [new vscode.Range(215681, 0, 215681, 6)]);
        editor.setDecorations(red, [new vscode.Range(215683, 2, 215683, 7)]);
    }
    vscode.window.onDidChangeActiveTextEditor(decorate);
    decorate();
};
```

### running from source
![image](https://user-images.githubusercontent.com/5047891/62520257-7c4d7180-b82d-11e9-9bad-30f9e28f67f8.png)
![image](https://user-images.githubusercontent.com/5047891/62520282-8ec7ab00-b82d-11e9-91d8-0b066379aae4.png)

### running from a built version
![image](https://user-images.githubusercontent.com/5047891/62520298-9be49a00-b82d-11e9-9394-6f36883c6453.png)
![image](https://user-images.githubusercontent.com/5047891/62520332-a7d05c00-b82d-11e9-8fa1-713ffb4ac3f9.png)

**Comment by alexandrudima** [comment]
Well, after debugging I can no longer reproduce this in the built version...

**Comment by alexandrudima** [comment]
Ok, now I understand this weirdness, I am running into a code cache bug. I've created https://github.com/microsoft/vscode/issues/78542 to track that.

In any case, going back to our issue. I can set an opacity and it is respected. See the above sample code:
![image](https://user-images.githubusercontent.com/5047891/62522014-182cac80-b831-11e9-97ab-f41e000469b6.png)
![image](https://user-images.githubusercontent.com/5047891/62522029-1f53ba80-b831-11e9-860a-dea97a7a3450.png)

**Comment by Colengms** [comment]
As you can see, this does not really address the issue.  Note how your background color, now that it's blending with the editor background, is no longer red.  You should be able to use a color that does not need blend with the editor background color, yet user text selection is still apparent.
