### ISSUE TITLE
Character Encoding in Terminal

### ISSUE THREAD

**Issue by mcrowson** [microsoft/vscode#75648]
![encoding_vscodium](https://user-images.githubusercontent.com/6452882/59628105-d4a9a200-910d-11e9-88e9-22bb452f42b9.png)

I cannot get special characters to show in the integrated terminal. The top half of the picture above is how the terminal should look and the bottom half is vscode's integrated terminal.

Looked at several of the locale/lang issues and none of the fixes i've tried seem to work. Here are my locale settings

![image](https://user-images.githubusercontent.com/6452882/59628207-13d7f300-910e-11e9-9f7b-f391e9473063.png)

Additionally tried `"terminal.integrated.setLocaleVariables": true`.

**Comment by Tyriar** [comment]
These issues are normally related to font config, notice you're using a different font in the terminal it works in.
