### ISSUE TITLE
missing toolbar Can not be switched on

### ISSUE THREAD

**Issue by uhi2000** [microsoft/vscode#75655]
Issue Type: <b>Bug</b>

no toolbar!!!toolbar is missing /in setting menu is disable!!!   I can not enable!!! please help!!!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.93GB (20.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
mapfile|chi|0.0.1
vscode-pull-request-github|Git|0.8.0
vscode-map-preview|jum|0.4.8
hex-fmt|ker|1.0.0
cpptools|ms-|0.24.0-insiders
arma-dev|ole|0.0.17
platformio-ide|pla|1.7.1
postal|pos|1.0.0
hoverhex|the|0.0.2
elfcode|vst|0.0.3
map-replace-js|Yuk|0.2.2
linkerscript|Zix|1.0.0

</details>

**Comment by sandy081** [comment]
@uhi2000 Which toolbar are you talking about? Can you please provide a screenshot?

**Comment by uhi2000** [comment]
the platformio toolbar....

**Comment by sandy081** [comment]
Please file issue against the platform ide extension.
