### ISSUE TITLE
# of references display modification

### ISSUE THREAD

**Issue by lgreenlee** [Microsoft/vscode#7565]
- VSCode Version: 
Version 1.2.0
Commit 809e7b30e928e0c430141b3e6abf1f63aaf55589
Date 2016-06-06T13:34:34.143Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
Linux ubuntu 4.2.0-36-generic #42-Ubuntu SMP Thu May 12 22:05:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Load or create a C# file
2. Create a new class
3. Add a method to that class
4. Add an attribute to that method

When the references are displayed they are between the attribute and the method. It would really helpful if the references display was above any attributes associated with the method, it is somewhat confusing when reading and editing with the current format.

Current:
![image](https://cloud.githubusercontent.com/assets/1766941/15987396/a1d8b44c-2ff4-11e6-9d52-8a3641dec4e4.png)

Proposed:
![image](https://cloud.githubusercontent.com/assets/1766941/15987402/22aa81c2-2ff5-11e6-8baf-55c97395c209.png)

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#429
