### ISSUE TITLE
Git commit template should be restored automatically (not only on commit)

### ISSUE THREAD

**Issue by dmstern** [microsoft/vscode#75651]
## Background
In #39048, @joaomoreno says about the command `git.restoreCommitTemplate`:

> I don't think it's a command worth putting in the command palette. Seems to be very specific for users who actively modify .gitmessage, doesn't happen often.

This might be true, but there are definitely more actions (than just `commit`) where it would make sense to read the git commit template, because if you know what you can do with this, this is so damn useful. :)

## Problem:
Personally, I use the git commit template to follow our team's git commit message and branch naming conventions, which says that the commit message and the branch you are working on have to be prefixed with the id of the corresponding Jira issue.

So I created a git hook for writing the recently used commit message into the commit template on `post-commit` and also a hook on `post-checkout` to write the current branch name (title-cased) into the commit template when I create a new branch.
:heavy_check_mark: When I commit something, the git commit template updates and the last commit message stays in the scm message box.
:negative_squared_cross_mark: But in order to get the updated content from that template after a `git checkout`, I have to invoke `git.restoreCommitTemplate`.

Temporarily [I could fix this](https://gist.github.com/dmstern/d02ea41d4b0171ff2f4661daaa3e3f86) with a macro extension and mapped the `workbench.view.scm` keyboard shortcut to my new macro, which does both (`git.restoreCommitTemplate` and `workbench.view.scm`). But (a) this works only with this shortcut, not if I click on the scm icon in the activity bar and (b) I think this behavior should be possible without an extension.

## Possible solution:
Please invoke `git.restoreCommitTemplate` every time `workbench.view.scm` is invoked or on every [`git.refresh`](https://github.com/microsoft/vscode/blob/4e7545ba8a536237387848e2b8220d2b562ae041/extensions/git/src/commands.ts#L237)

**Comment by joaomoreno** [comment]
Maybe running it on every `git.refresh. isn't too bad, but I'd definitely put that behind a setting. PR?

**Comment by joaomoreno** [comment]
@dmstern Can you try your flow on today's Insiders? Due to another issue, we now support live reloading of the template message:

![recording](https://user-images.githubusercontent.com/22350/67084047-85977a80-f19c-11e9-8481-97c3c270ca00.gif)

I believe this would help you and render https://github.com/microsoft/vscode/pull/75767 obsolete. What do you think?

**Comment by dmstern** [comment]
@joaomoreno Wow, very cool! This is even better than #75767.
I'll close my PR.

**Comment by connor4312** [comment]
@joaomoreno I'm not sure exactly the extent you mean by 'live reloading'--when I edit me message file, I need to (manually) hit refresh in the git sidebar to have it update the default commit message--it doesn't update automatically when the template it saved. If this is the intended behavior, feel free to mark this issue as `verified` 🙂

**Comment by joaomoreno** [comment]
@connor4312 Is the template file you picked _inside_ the workspace folder? If it is outside, we won't have file events hooked up to it.
