### ISSUE TITLE
Notfication pop over title doesn't look good

### ISSUE THREAD

**Issue by sb7896** [microsoft/vscode#75650]
Issue Type: <b>Bug</b>

When there are no notifiction, click the bell icon at the bottom right of the VS code window. You will see the pop over, with its tiltle bar as half shown.

![image](https://user-images.githubusercontent.com/20710705/59633957-4e23ad80-916b-11e9-87e3-4562d96d6068.png)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.95GB (0.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.2
beautify|Hoo|1.5.0
Angular1|joh|0.2.1
cpptools|ms-|0.23.1
debugger-for-chrome|msj|4.11.4
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.7.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@sb7896 does this reproduce everytime?
