### ISSUE TITLE
Fewer updates

### ISSUE THREAD

**Issue by abhimng** [microsoft/vscode#75661]
Issue Type: <b>Feature Request</b>

Can we please have fewer updates? I feel I am prompted to download and install the update almost every time I open the app. This is super annoying! 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by byyxx128** [comment]
Usually the stable only upgrades once a month with possible one to two small updates. Is this still too frequent for you? Maybe someone like you needs lower frequency.

Actually, I don't think it's the problem of the update frequency, in contrast, it's the problem of the annoying prompt. I have two ideas about this. **Just my personal opinions**:

1. Add a control of update frequency. VSCode currently can only be adjusted the `update.mode` (`none`, `manual` or `default`).
2. Silent update. VSCode currently always gives an prompt if an update is available. Why not updating silently?

Just my ideas.

**Comment by byyxx128** [comment]
Usually the stable only upgrades once a month with possible one to two small updates. Is this still too frequent for you? Maybe someone like you needs lower frequency.

Actually, I don't think it's the problem of the update frequency, in contrast, it's the problem of the annoying prompt. I have two ideas about this. **Just my personal opinions**:

1. Add a control of update frequency. VSCode currently can only be adjusted the `update.mode` (`none`, `manual` or `default`).
2. Silent update. VSCode currently always gives an prompt if an update is available. Why not updating silently? Both MS Office and Chrome are good examples.

Just my ideas.

**Comment by sandy081** [comment]
Above suggestion shall help you.
