### ISSUE TITLE
Smart "editor.find.autoFindInSelection" ?

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#75663]
Issue Type: <b>Feature Request</b>

Right now, the editor.find.autoFindInSelection and editor.find.seedSearchStringFromSelection don't work well together: a basic use case is to select a word, then Ctrl-F to find the occurrences.

The problem is that if editor.find.autoFindInSelection is true (which I really like), then the selection is the word itself. 

How about autoFindInSelection activate only if the selection is not the same as the selection used for seedSearchStringFromSelection ?

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rebornix** [comment]
Let's track it in #58111
