### ISSUE TITLE
Python Interpreter from environment not being listed when using SSHFS

### ISSUE THREAD

**Issue by petrosschilling** [microsoft/vscode#75666]
**VSCode Version:**  1.36.0-insider
**OS Version:** Mojave 10.14.4

**Overview:**
I am mapping the project from an external server using SSHFS to develop in my local machine.
The environment's interpreter doesn't show on the list for selection when trying to Select Python Interpreter.
I created a new local project and created an environment to check the issue and I was able to select the environment interpreter.
So the issue seems to only happen when working in a directory mapped using SSHFS.

**Steps to Reproduce:**
1. Mount the project directory from a remote server using SSHFS
2. Create virtual environment (venv)
<img width="292" alt="image" src="https://user-images.githubusercontent.com/5184353/59645900-a2ed1580-91b7-11e9-9a30-60d99d2ae8d7.png">

<img width="366" alt="image" src="https://user-images.githubusercontent.com/5184353/59645940-d6c83b00-91b7-11e9-9abb-7686d71d302e.png">

3. Try to select Interpreter from environment
<img width="614" alt="image" src="https://user-images.githubusercontent.com/5184353/59645911-aaacba00-91b7-11e9-843a-3acb700e1e5b.png">

**Current behavior:**
Interpreter from environment not being listed.

**Expected behavior:**
Python interpreter from environment available for selection.

*PS: I have found many issues about the interpreter selection but none of them were able to solve my problem. If I'm doing something wrong please let me know.*

**Comment by sandy081** [comment]
Please file issue against the Python extension you are using
