### ISSUE TITLE
tab and editorGroupHeader not changing background color.

### ISSUE THREAD

**Issue by mtaciano** [microsoft/vscode#75660]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04.2 (Kubuntu)

So i was noticing after the color theme that i used broke that the tab color
 also broke, so i completely removed the extensions and settings and downloaded a fresh version of vscode, and the error still occured. When i change the values of the atributes bellow to #ff0000, a strong red, the expected behaviour is to the tab change to red, but nothing changes no matter what color i choose, only the border and the foreground changes color, no change in the background color.

![Screenshot_20190617_200801](https://user-images.githubusercontent.com/40744030/59642507-9e831700-913b-11e9-91a3-5c66d900185c.png)
(with the color theme One Dark Pro)

![Screenshot_20190617_203146](https://user-images.githubusercontent.com/40744030/59643412-f66f4d00-913e-11e9-9857-c6bdd127a5a1.png)
(with default color theme)

these screenshots were of a vscode with only 1 plugin, that is the color theme, no other plugins where installed. 

Steps to Reproduce:
1. Open settings.json
2. Change atributes like tab.activeBackground or editorGroupHeader.tabsBackground to some value
3. Save and see no change

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running. Then try to reproduce the issue you see.

**Comment by mtaciano** [comment]
With this command now it works. Strange, so it is something in my data directory.

**Comment by mtaciano** [comment]
Found the issue, it was a sneaky configuration in my workspace overriding my settings, how dumb, thanks.
