### ISSUE TITLE
"Open Folder" opens base directory, not the specified directory

### ISSUE THREAD

**Issue by jastt** [Microsoft/vscode#7566]
- VSCode Version: 1.2.0
- OS Version: Ubuntu 12.04

"Open Folder" opens the base directory, not the directory navigated to. For example, attempting to open myhome/src/foofolder, vscode displays files in myhome. Not knowing how to locate and defeat the offending misconfiguration, this has rendered vscode effectively useless.

This issue began occurring after I opened two concurrent instances of vscode, whether coincidence or not is unclear. This issue appears to be sufficiently different than #2115 to warrant a new issue, since this issue began a week or so after installing and using vscode successfully.

**Comment by JimiC** [comment]
Can't reproduce on Ubuntu 16.04 LTS. `Open Folder...` works as intended. Providing reproduction steps might help.

**Comment by bpasero** [comment]
Please reopen with steps how to reproduce.
