### ISSUE TITLE
Select "All files (.)" when picking a file name with unknown extension

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#75664]
Issue Type: <b>Bug</b>

When saving a new file, the way the filename is generated is inconsistent:

1. Typing "foo" will automatically get .txt extension (so foo.txt)
2. "foo.cpp" will stay foo.cpp 
3. "foo.cu" will end up "foo.cu.txt" (should stay foo.cu)

#1 and #2 are reasonable behaviors, but #3 is not: ideally VS Code should not try to generate an extension if the new filename ends with \.(\w*) - ie. already has an extension. 

Thanks.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
code-runner|for|0.9.11
language-haskell|jus|2.6.0
cpptools|ms-|0.23.1
code-settings-sync|Sha|3.2.9
markdown-preview-enhanced|shd|0.4.1
perforce|sle|3.2.0
code-spell-checker|str|1.7.17

</details>

**Comment by isidorn** [comment]
This is a native electron thing. Not sure if we can control. Forwarding to @bpasero since this is coming from `fileDialogService`

**Comment by bpasero** [comment]
This is a windows file dialog problem. To save with an extension of choice, pick the last entry in the extension dropdown.

**Comment by tlemo** [comment]
@bpasero: Thanks for the quick response, but blaming the Windows file dialog is not exactly accurate: 

First, the underlying Win32 GetOpenFileName() is flexible enough to allow any custom behavior regarding the extensions. 

Second, the problem in this case could be simply the default: If VS Code would select the "All files (*.*)" as default filter the issue I described would not happen. I can see how .txt default may appear tempting, but I seriously doubt that most files created with VS Code are actually .txt (you should have telemetry to check this - how many people really type extension-less file names expecting a default .txt?). 

So, I hope you'll consider the suggestion to simply simply switching the default filter to "All files (*.*)".

**Comment by bpasero** [comment]
Yeah I like to treat this as feature request.

**Comment by tlemo** [comment]
Thanks @bpasero 

>  If I understand your suggestion correctly, you want to automatically select the "All Files" entry in the dropdown based on what you type as file name?

Actually, the suggestion is even simpler: just set the "All files (*.*)" as the default filter. No need to manually parse or inspect the filename.

**Comment by bpasero** [comment]
@tlemo I tried to do that programmatically but Windows refuses to show this entry first. 

Proof: input (filters) 

![image](https://user-images.githubusercontent.com/900690/59739082-c1104f80-9263-11e9-9f61-1c5ecf982f75.png)

Visual:

![image](https://user-images.githubusercontent.com/900690/59739096-c79ec700-9263-11e9-91ed-c4cc77683cc4.png)

**Comment by tlemo** [comment]
Thanks for looking into it! I'm not familiar with the code, but from a quick glance it seems that the Electron is to blame:

https://github.com/electron/electron/blob/79f0c444fd1317e397af5d889228cb911d2441e2/atom/browser/ui/file_dialog_win.cc#L204
