### ISSUE TITLE
Wrong Variable Type

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#75662]
This is my animation project and this is the js file.

![er1](https://user-images.githubusercontent.com/42807112/59645071-37cc2080-9170-11e9-90b8-d77b205ddcc2.jpeg)

and When I hover over the `mul` variable It shows a number although It's the result of multiplication of two point variables

![er2](https://user-images.githubusercontent.com/42807112/59645104-69dd8280-9170-11e9-8883-2fd56e8c07d0.jpeg)

although it shows rightly when hovering over the two other variables

![er3](https://user-images.githubusercontent.com/42807112/59645127-95606d00-9170-11e9-92a5-7426028e7c2d.jpeg)

![er4](https://user-images.githubusercontent.com/42807112/59645152-baed7680-9170-11e9-891c-b11aaa476427.jpeg)

**Comment by minkir014** [comment]
@mjbvz Can you look at this issue???

**Comment by mjbvz** [comment]
https://github.com/microsoft/TypeScript/issues/31783

**Comment by mjbvz** [comment]
Oh actually this is a different question.

But this is the correct behavior. Multiplying will always output a number in JS, even if that value is `NaN`
