### ISSUE TITLE
No auto-completion on typescript interface with classes implement

### ISSUE THREAD

**Issue by ScreamZ** [microsoft/vscode#75679]
Redirected by https://github.com/microsoft/vscode-cpptools/issues/3789

**Type: LanguageService**
**Describe the bug**
- macOS Mojave 10.14.5
- VSCODE : 1.35.1
- TS 3.5.1

**To Reproduce**

Create a file with the following : 
```ts
import { Strategy } from "passport-local";

class SSOPlugin implements Plugin {

  constructor() {}

  init() {}
}

interface Plugin {
  authenticators?: Record<string, any>;

  strategies: { [key: string]: KuzzleStrategy };
}

interface KuzzleStrategy {
  config: {
    authenticator: string;
    fields: string[];
  };
  methods: {
    afterRegister?: () => any;
    create: () => any;
    delete: () => any;
    exists: () => any;
    getById?: () => any;
    getInfo?: () => any;
    update: () => any;
    validate: () => any;
    verify: () => any;
  };
}

export = SSOPlugin;
```

In constructor or any method using `this.` and auto-completion doesn't give anything.

But if I give the wrong types, the compiler complain (also red line on IDE).

**Expected behavior**

I should get auto-completion.

**Comment by sean-mcmanus** [comment]
FYI, this bug was also filed at https://github.com/microsoft/TypeScript/issues/31956 (not sure which repo is correct).

**Comment by mjbvz** [comment]
Closing as upstream
