### ISSUE TITLE
Simple Open Folder should default to current folder (or parent)

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#75674]
Issue Type: <b>Bug</b>

Open Folder defaults to some other folder when a folder is already open. It would make sense to use the current folder as the default (or maybe its parent folder).

VS Code version: code-oss-dev 1.36.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (1.49GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-open-in-github|ziy|1.3.6
remote-containers|ms-|0.61.0

</details>

**Comment by alexr00** [comment]
@chrmarti it already should be using the parent folder. I tested with a remote container and locally, and I'm seeing the parent folder as the starting point of the picker. Were there any other steps you took to open the folder?

**Comment by chrmarti** [comment]
With a new self-hosting container it defaults to `/headless/.vscode-server-oss/data/Machine/` when the current folder is `/workspaces`. Not sure where that path comes from.

**Comment by alexr00** [comment]
This a Mac vs. Windows difference. On Mac, it is Open File or Folder, on Windows, it is two separate commands. Because it is one command on Mac, we always make the starting folder relative to the last open file. When the commands are separate on Windows, we make the Open Folder command start with a path relative to the currently open folder.

**Comment by chrmarti** [comment]
"Open Folder" is the more frequently used command on Windows and Linux (77% more often than "Open File"). It would make sense to optimize openFileFolder for the folder case by opening at the parent of the last folder. @bpasero What do you think?

**Comment by bpasero** [comment]
@chrmarti you gave some statistics but I cannot recall any user complaining about this so far, so changing this is asking for trouble maybe? And I assume this is a change that has an impact on both native and custom dialog.

**Comment by chrmarti** [comment]
I'm suggesting the change based on data and am one of the users who would benefit from it. 🤷‍♂

There will always be users complaining about change...

**Comment by bpasero** [comment]
I feel this will backfire. If I had to pick a solution for this, I would add the "Open File" and "Open Folder" as commands on macOS as well for those that want to distinguish and then we can use better default paths. These commands should probably not show up anywhere but the command palette and keybindings editor.

**Comment by chrmarti** [comment]
I suggest to make this a feature request then. As suggested by you, this could also be implemented as a setting that changes where the default folder is read from for 'open file or folder' on MacOS.
