### ISSUE TITLE
Sidebar minimap/scroll doesn't work with surface touch screen

### ISSUE THREAD

**Issue by DeXtmL** [microsoft/vscode#75672]
Issue Type: <b>Bug</b>

Touch click scrolling works, but touch drag scrolling doesn't. 
This affects both the minimap and the scrollbar

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexandrudima** [comment]
Let's track in #47771
