### ISSUE TITLE
用户登录

### ISSUE THREAD

**Issue by ixuelei** [microsoft/vscode#75670]
- VSCode Version:
- OS Version:

Steps to Reproduce:

请求：希望加一个用户登录，可以同步自己的配置。

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
1. English please.
（请讲英文，用翻译软件也可以，不然没人理你……）
2. Please check if there is already an issue reported by someone.
（以后反馈之前先看看别人是不是早就反馈过了）

duplicate https://github.com/microsoft/vscode/issues/65567

**Comment by byyxx128** [comment]
1. English please. All non-English issues will be closed directly.
（请讲英文，非英文反馈都会被直接关闭）
2. Please check if there is already covered by an existing issue before you report every time.
（以后反馈之前先看看别人是不是早就反馈过了）

duplicate https://github.com/microsoft/vscode/issues/65567

**Comment by sandy081** [comment]
Sorry for closing this, Please submit the issue in english.
