### ISSUE TITLE
taskName from tasks.json appended as a parameter when executed

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#7567]
First, I have to echo previous bugs that comment that the documentation at https://go.microsoft.com/fwlink/?LinkId=733558 is __not__ helpful in understanding the architecture of VSCode's tasks feature.   Second, I suggest that lack of reference style documentation on the schema for `tasks.json` masks design flaws, particularly when `tasks.json` contains multiple tasks.   

- VSCode Version: 1.2.0
- OS Version: Windows 10

Bug:  It seems surprising behavior that `taskName` of the individual task selected is automatically inserted as an argument when running the command.    It's best illustrated with the following `tasks.json` which attempts to use `npm run prepublish` as the build command.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "args": [],
    "showOutput": "silent",
    "tasks": [
        {
        "taskName": "build",
        "isBuildCommand": true,
        "args": ["run", "prepublish"],
        "problemMatcher": ["$tsc"]
        }
    ]
}
```

Steps to Reproduce:

1. Create a project with  `.vscode/tasks.json` set as above, and open in VSCode
2. press Ctrl+Alt+B.

Expected: I expected this to run the following command:
```
npm run prepublish
```
Observed result: the `taskName` of `build` is unexpectedly inserted as an argument in the command, resulting in the following error:
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Burt_\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "build" "run" "prepublish"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! path c:\my\ts-npm-module\run\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
...
```
Workaround: this version of `tasks.json` seems to work:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "args": ["run"],
    "showOutput": "silent",
    "tasks": [
        {
        "taskName": "prepublish",
        "isBuildCommand": true,
        "args": [],
        "problemMatcher": ["$tsc"]
        }
    ]
}
```
Related Question:  is the 'version' element of tasks.json intended to allow semantic versioning of the schema used?  Is there any version-specific documentation on these schemas?

**Comment by JimiC** [comment]
Use `"suppressTaskName": true`.

**Comment by dbaeumer** [comment]
@JimiC thanks for jumping in. It is exactly the way to address the problem. Closing.

**Comment by BurtHarris** [comment]
Yes, thanks @JimiC.   The docs are tough to approach for someone who's ramping up.   For me at least.   The examples swamp me with new concepts, grunt, gulp, jake, problem matchers, etc.   I know I read that page at least three times, but guess it was TL;DR.
