### ISSUE TITLE
Pressing Enter doesn't add Tabs or Spaces

### ISSUE THREAD

**Issue by DhirajBorana** [microsoft/vscode#75671]
# Current output
![Untitled](https://user-images.githubusercontent.com/19840056/59652338-f7d65f00-91aa-11e9-99cd-ad3d65421548.png)

# Desired output
![Untitled](https://user-images.githubusercontent.com/19840056/59652436-556aab80-91ab-11e9-942f-eac39c3fd21e.png)

**Comment by sandy081** [comment]
Please file issue against C++ extension you are using.
