### ISSUE TITLE
Task running indicator stays spinning

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#7568]
- VSCode Version: 1.2.0
- OS Version: Windows 10

Only reproduces intermittently... I will update if I can find a hard repro case...

Steps to Reproduce:

1. Open VSCode in a project directory with a `tasks.json` containing a build script
2. Press Ctrl+Alt+B

Observed: even after the script seems to have completed, the spinning indicator sometimes continues to spin indefinitely.

**Comment by JimiC** [comment]
Make sure you don't have any `"isWatching": true` in a task that should not be watchable.

**Comment by dbaeumer** [comment]
@BurtHarris can you provide your tasks.json file?

**Comment by BurtHarris** [comment]
I just got an update to 1.2.1, release notes seemed like several problems I was hitting may have been fixed.   I'll confirm but it may take a couple of days for me to get around to it.

**Comment by BurtHarris** [comment]
With Version 1.2.1, I'm getting different behavior, but still seems buggy.    Starting a fresh project, I create a tasks.json using the template for grunt.   But now when I press Ctrl+Shift+B, I get a message saying "No built task configured".

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "grunt",
    "isShellCommand": true,
    "tasks": []
}
```

**Comment by BurtHarris** [comment]
P.S. the root cause of this is that the docs at https://go.microsoft.com/fwlink/?LinkId=733558 are too complex.

**Comment by JimiC** [comment]
@BurtHarris Give it dome time to get familiarized with all the "new" tooling. I get frustrated too some times but acquiring knowledge takes time, unfortunately.

**Comment by BurtHarris** [comment]
Yes @JimiC, please recognize I'm a experienced dev (30+ years, more than half at Microsoft), and understand tool learning curve should be.   The original issue got blocked, under 1.2.1 I think there's a bug in the template **tasks.json** file generated for grunt; and bugs don't get better by giving them time.   

My comment was intended be a suggestion that documentation on the tasks.json file format shouldn't force the reader to go slogging tons of examples based tools they may not use in order to get to details on options like it currently does.   Topics like how to integrate with optional tools belong in separate topics, with hyperlinks cross-references from the file-format documentation.

**Comment by BurtHarris** [comment]
I'm going to go ahead and close the spinning indicator bug and open a new one for the template bug.

**Comment by dbaeumer** [comment]
@BurtHarris I tried to reproduce this and was able to do so in the following case:

- you have grunt installed glopally but not locally in your workspace. 

Then grunt can't execute and the tasks.json file generated contains an empty task array which is problematic. It should generate a tasks.json file with no task array. Then on the next execution you would see:

```
grunt-cli: The grunt command line interface. (v0.1.13)
Fatal error: Unable to find local grunt.
If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:
http://gruntjs.com/getting-started
```

**Comment by dbaeumer** [comment]
Created https://github.com/Microsoft/vscode/issues/7881

**Comment by BurtHarris** [comment]
Thanks.   I created #7877 with a package.json which should have installed grunt locally.   This may be a separate bug.
