### ISSUE TITLE
Mouse up event in code editor.

### ISSUE THREAD

**Issue by powerumc** [microsoft/vscode#75680]
- Version: 1.35.1(1.35.1)
- Hash: c7d83e57cd18f18026a8162d042843bda1bcf21f

I has some question about mouse event in code editor.
I developed [VSGesture](https://github.com/powerumc/vsgesture)

When I click mouse right button in code editor.
- Windows VSCode: Show context menu when **mouse up**.
- Mac VSCode: Show context menu when **mouse down**.

Why is it difference?

**Comment by sbatten** [comment]
@powerumc This is just an OS difference that we maintain. Try right clicking the desktop wallpaper on mac and windows and you should see the same difference.
