### ISSUE TITLE
Fail to install update on VSCode

### ISSUE THREAD

**Issue by Galiant** [microsoft/vscode#75685]
Fail to install updates. The error message is

> library/Caches/com.microsoft.VSCode.Shipit/update.46TeHqa/Visual%20Studio%20Code.app/ did not pass validation: code object is not signed at all

That error message is showing when I am opening a new VSCode window and after I check for updates it is like on the image below 

![Screenshot 2019-06-18 at 10 00 55](https://user-images.githubusercontent.com/14877912/59669164-a9788e80-91b1-11e9-9cb6-8205921d7d0f.png)

and it is always like that so actually never downloading updates. Last time had the same problem which I solved with reinstalling VSCode but that is not a solution for the long term.

VSCode version: Version 1.35.0 (1.35.0)
OS version: macOS Mojave version: 10.14.5

**Comment by 6simon1112** [comment]
sim 0001

**Comment by joaomoreno** [comment]
This is odd since we always sign our binaries. Can you fully uninstall VS Code and reinstall from this URL?

https://az764295.vo.msecnd.net/stable/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/VSCode-darwin-stable.zip

After installing, run it. You should get an update, does the update go through?

**Comment by Galiant** [comment]
Hi @joaomoreno any solution on this. Now I can't open VSCode at all. I tried all the solutions around with uninstalling, re-downloading and restarting my machine. Nothing helps so far. I am feeling like some newbie person who never touches PC :)

**Comment by joaomoreno** [comment]
I have no idea what is going on but something's wrong in your system. What are you using for unarchiving the download?

**Comment by Galiant** [comment]
I am using 'Archive Utility'. Yes, this happened on the working machine, but I don't think that is the reason. Unfortunately, I downloaded another IDE and install without problems. However, I am using VSCode from the beginning and I would like to continue with VSCode if is that possible.

**Comment by joaomoreno** [comment]
And I'm guessing this is fine on another machine? Do you have other people in your company with the same issue?

**Comment by Galiant** [comment]
For now, I didn't hear any issues in the office about VSCode. My team member(s) are running without any problem.

**Comment by hmhlennoxm** [comment]
@joaomoreno I'm a colleague of @Galiant and I'm having the same issue today

**Comment by Galiant** [comment]
Hi @joaomoreno we figure out that issue is on our side so I will close this one

**Comment by joaomoreno** [comment]
If you can, let us know the details, so more people can find it if they hit the issue.

**Comment by Galiant** [comment]
For me, the solution was that IT help support in my office switch to the admin account on my machine and we installed VSCode what immediately reflect that also working on my account.

My team member(who works remotely) think that this command helped him to run VSCode:

`chown -R ${whoami}:admin /Applications/Visual\ Studio\ Code.app/`
