### ISSUE TITLE
Spam in developer tools console

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75684]
Open developer tools console

A bunch of

`keybindingService.js:281 Ctrl/Cmd+Num keybindings should not be used by default in web. Offender:  000141;000130  for  editor.unfoldAllMarkerRegions`

Please only write this output in the `isWeb` case. No need to print this out for the vscode native.

![Screenshot 2019-06-18 at 11 04 03](https://user-images.githubusercontent.com/1926584/59668449-cd8b9e00-91b8-11e9-824d-12d2eaafc755.png)

**Comment by bpasero** [comment]
Oh same here...

**Comment by rebornix** [comment]
The console log is leaked as the code for web is being leaked. Now it should be fixed.
