### ISSUE TITLE
Tooltip on golang show repeated

### ISSUE THREAD

**Issue by gearintellix** [microsoft/vscode#75686]
Issue Type: <b>Bug</b>

example code:

```go
package main

type I interface {
   Print()
}

type A struct {
   Value string
}

// Print value
func (ox A) Print() {
   ...
}

type B struct {
   Value string
}

// Print value
func (ox B) Print() {
   ...
}
```

when showing tooltip `Print()` both comment showing

```
Print value
Print value  <- repeated
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.97GB free)|
|Process Argv|-psn_0_98328|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-intelephense-client|bme|1.0.14
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
vscode-projects-plus|fab|1.22.0
php-debug|fel|1.13.0
beautify|Hoo|1.5.0
docthis|joe|0.7.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
mssql|ms-|1.6.0
python|ms-|2019.5.18875
Go|ms-|0.10.2
debugger-for-chrome|msj|4.11.4
vetur|oct|0.21.0
vue-beautify|pea|2.0.4
vscode-docker|Pet|0.6.2
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please file issue against `go` extension
