### ISSUE TITLE
Code folding enhancement request

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#75688]
I find myself randomly pressing <kbd>CTRL+K</kbd>, <kbd>CTRL+1</kbd> to <kbd>CTRL+K</kbd>, <kbd>CTRL+7</kbd> and I'm always baffled by the result as it never is what I'd expect it to be.

For example, hitting <kbd>CTRL+K</kbd>, <kbd>CTRL+5</kbd> after hitting <kbd>CTRL+K</kbd>, <kbd>CTRL+5</kbd>, <kbd>CTRL+K</kbd>, <kbd>CTRL+3</kbd> doesn't revert the display to what it was when I hit <kbd>CTRL+K</kbd>, <kbd>CTRL+5</kbd> initially ...

Can we get a documentation page on code folding to see what the developers intended to happen when they implemented this functionality?

**Comment by gjsjohnmurray** [comment]
Did you see [this doc](https://code.visualstudio.com/docs/editor/codebasics#_folding)?

**Comment by SetTrend** [comment]
Yes, but folding doesn't behave as I'd expect it to (according to the docs):

![Folding not working](https://user-images.githubusercontent.com/9283914/60038596-178eeb00-96b5-11e9-9107-a1c3b6afc729.gif)

**Comment by gjsjohnmurray** [comment]
@SetTrend are you expecting the `Ctrl+K Ctrl+number` chord do do some unfolding (which you caption expanding) as well as some folding (collapsing)? I didn't see that being promised by the doc I pointed you to. But maybe I'm misunderstanding you animation.

**Comment by SetTrend** [comment]
Pardon me choosing the wrong terms. English is not my native tongue.

I interpreted the doc's sentence: "Fold Level `X` (<kbd>Ctrl+K</kbd> <kbd>Ctrl+2</kbd> for level `2`) folds all regions of level `X`" like "Fold Level `X` (<kbd>Ctrl+K</kbd> <kbd>Ctrl+2</kbd> for level `2`) folds all regions of level `X` and unfolds all regions of level `X - 1`".

I tend to believe that the current implementation doesn't quite make sense: If I accidentally went too far folding, I'd expect to be able to unfold that level easily again.

**Comment by SetTrend** [comment]
I also don't believe that it doesn't make sense to include the current block from folding.

For my use case, when I'm debugging, it's particularly the block I'm currently working within which I want to have all nested blocks folded to get an overview of that function's structure.

**Comment by SetTrend** [comment]
Visual Studio 201x offers to fold/unfold the current class member function or class.

If feel this is quite a nifty functionality when trying to delete a member function: When examining a function body and recognizing the function is redundant while the cursor is amidst the function body, you just hit <kbd>CTRL</kbd>+<kbd>M</kbd>, <kbd>CTRL</kbd>+<kbd>M</kbd> and the function folds, so it can be deleted with just three keys (<kbd>CTRL</kbd>+<kbd>M</kbd>,<kbd>CTRL</kbd>+<kbd>M</kbd>,<kbd>DEL</kbd>).

Can we have the same for Visual Studio Code?

**Comment by aeschli** [comment]
By design `Fold Level X` just fold that level. It doesn't unfold.

I'm not sure what precisely your request is.

**Comment by SetTrend** [comment]
## It's two things I'd like to suggest:
<br/>

1. **Folding should always _fold_ everything up to the specified level and _unfold_ everything below.** So if the user accidentally went too far selecting a folding level (s)he can easily revert his/her mistake by selecting another folding level.

   The current implementation is nondeterministic in its behaviour in that a folding result depends on a previous folding state. The editor state after hitting <kbd>CTRL+K</kbd>, <kbd>CTRL+2</kbd>, <kbd>CTRL+K</kbd>, <kbd>CTRL+1</kbd>, <kbd>CTRL+K</kbd>, <kbd>CTRL+2</kbd> differs from the editor state after pressing <kbd>CTRL+K</kbd>, <kbd>CTRL+2</kbd>, <kbd>CTRL+K</kbd>, <kbd>CTRL+J</kbd>, <kbd>CTRL+K</kbd>, <kbd>CTRL+2</kbd>. I suggest the behaviour to become deterministic.

   The current implementation suffers from the same logical error like this pseudo construct:

   ```
   if (items.length) { list.clear(); for (item in items) list.items.add(item); }
   ```
   (If no items are set in this example, existing items in the list will not be cleared, although they should.)

   ### So, basically, I'd like to suggest the following change:

   From:
   ```
   { foldToLevel(level); }
   ```
   To:
   ```
   { unfold(); foldToLevel(level); }
   ```
   <br/>

1. I'd furthermore like to suggest to **add the following very efficient folding commands from Microsoft Visual Studio 201x**:

   1. Fold to member declarations (<kbd>CTRL+M</kbd>, <kbd>CTRL+O</kbd>)
   1. Toggle folding for everything (<kbd>CTRL+M</kbd>, <kbd>CTRL+L</kbd>)
   1. Toggle folding to declaration for current item (<kbd>CTRL+M</kbd>, <kbd>CTRL+M</kbd>)

![Folding request](https://user-images.githubusercontent.com/9283914/61286031-4c78f400-a7c2-11e9-8304-bb3edfd8debb.gif)

   Particularly **2.iii** differs from the current implementation in Visual Studio Code, which explicitly excludes the current function from folding, whereas in Visual Studio 201x, the current function is explicitly dealt with.

**Comment by aeschli** [comment]
- Fold to member declaration is #33449 
- I added `Toggle Fold` for September (`Ctrl -K + Ctrl+L`)
- We already have Fold All and Unfold All command so I'd stick with that.

I'd rather not change the behavior of `Fold Level X`. It's what Sublime has.
