### ISSUE TITLE
Keep linting/styling/etc modules separate from project

### ISSUE THREAD

**Issue by BeyondEvil** [microsoft/vscode#75696]
I have multiple projects and use `pipenv` for them all.

They all use `tox` so that's present in the `Pipfile`:
```ini
[dev-packages]
tox = "*"
```

However, while developing I also use `black`, `flake8` etc. to deal with styling and linting and VSC adds these "automagically" to the Pipfile. Which I don't want. Because they're not relevant to the actual project.

Any linting/styling that happens outside of VSC is handled by `tox`.

So VSC should be happy if the chosen linting- and styling tools are available globally.

**Comment by sandy081** [comment]
@BeyondEvil Are you any extension that adds these styling (black, flake8)? Because AFIK VSC out of the box does not add any such styling unless there are extensions doing it.

**Comment by BeyondEvil** [comment]
@sandy081 Yes, I'm using `Python Extension for VSC` and honestly that's where I thought I had logged this issue.

Mind moving it? Thanks.

**Comment by sandy081** [comment]
Filed - https://github.com/microsoft/vscode-python/issues/6221
