### ISSUE TITLE
Command pallete automatically closes in non-file editor

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode#75694]
# System Information
Version: 1.36.0-insider (user setup)
Commit: 7f53e50cbf316dff94fbbe5406d8f352dac99a6b
Date: 2019-06-18T09:31:11.619Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT ia32 6.1.7601

issue type: bug

# Steps to reproduce:
1 open any non-file editor, like preview for markdown
2 open ("Command palette"/"Color Theme"/"File Theme") from activity bar>settings icon

**Comment by COD3BREAK3R** [comment]
What happened to the bug? Was it solved or is it in the process of being fixed?

**Comment by SupinePandora43** [comment]
@COD3BREAK3R i dont know, i'm just report bug

**Comment by chrmarti** [comment]
Something must draw focus. @bpasero I remember you mentioning this issue? /cc @sbatten

**Comment by bpasero** [comment]
Quite sure this is the webview taking focus to workaround Electron focus issues.
