### ISSUE TITLE
Outline should forget previous selection

### ISSUE THREAD

**Issue by johnmarkwayve** [microsoft/vscode#75692]
Right now, if I select an item in the outline, the editor scrolls to that item (good :+1:).

Suppose I then scroll manually to another part of the code (taking the input cursor with me). Logically, that outline entry is no longer "active", there's no real sense in which I've selected it. If I then try to click on the same entry in the outline again to return to it, nothing happens (apparently because the outline considers that item "selected" already). I have to click another outline item, then return to the one I want.

Proposed solutions:

- either have the outline "deselect" the currently selected item when the editing cursor moves off that line/out of that function/whatever;

- or simply don't persist the outline with a "selected" state at all, outline entries simply act as buttons (there's no context menu on outline entries, or anything else that seems to benefit from a specific item being memorised as "selected"

**Comment by jrieken** [comment]
How about using the 'Follow Cursor' feature?

<img width="439" alt="Screenshot 2019-06-19 at 09 47 12" src="https://user-images.githubusercontent.com/1794099/59746433-389baa00-9277-11e9-8adf-9f0fdbc6a6b6.png">

**Comment by johnmarkwayve** [comment]
@jrieken that only seems to work if my cursor moves to the specific line of another definition (e.g., the signature of a function), not if I move to anywhere else in the file (e.g., the body of a function)

**Comment by jrieken** [comment]
Understood

**Comment by jrieken** [comment]
fix via https://github.com/microsoft/vscode/issues/81323
