### ISSUE TITLE
Monaco Editor : reverse cursor is too big

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#7569]
Hover over the line numbers to see. Sample: 

![image](https://cloud.githubusercontent.com/assets/874898/15988146/6e48f3a0-3088-11e6-854d-ec5a13715758.png)

:rose:

**Comment by alexandrudima** [comment]
This is where it's defined. I wonder if this happens in vscode too and if not, why not...

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.css#L22

**Comment by basarat** [comment]
also refs https://github.com/Microsoft/vscode/issues/362 :rose:

**Comment by basarat** [comment]
I have it disabled in my code base. The official demo works fine so closing it :rose:
