### ISSUE TITLE
do not get intellisense for constructors (or overloads) in referenced dll 

### ISSUE THREAD

**Issue by mjkkirschner** [Microsoft/vscode#757]
using Version 0.10.2 (0.10.2) on mac os x 10.11- I'm using one of the unity3d integration plugins (on the unity side) and getting autocomplete/intellisense, but not on the unity engine .dll or other referenced dlls in my projects, when using constructors. I expect to see parameter info for the constructor.

If I hold control over the type I get the first overload with no way to switch to others.

if I press control+ space I get autocomplete window but nothing to do with the constructor

**Comment by aliozgur** [comment]
Same here Code 0.10.2 and osx 10.11.1 (El Capitan)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#355
