### ISSUE TITLE
VS code keeps crashing after opening

### ISSUE THREAD

**Issue by Zionknight-crypto** [microsoft/vscode#75701]
Hi,

I have downloaded VS code and every time I open it, it crashes shortly after. Every single time, sO cannot use it. I have uninstalled and reinstalled many times too.

**Comment by Zionknight-crypto** [comment]
None of those issues helped in my case.

**Comment by Zionknight-crypto** [comment]
Hi,

I have downloaded VS code and every time I open it, it crashes shortly after. Every single time, sO cannot use it. I have uninstalled and reinstalled many times too.

**Comment by sandy081** [comment]
@Zionknight-crypto Please follow this link https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and provide us the necessary information
