### ISSUE TITLE
Incorrect whitespaces rendering\wrapping

### ISSUE THREAD

**Issue by Iipal** [microsoft/vscode#75704]
- VSCode Version: 1.36.0-insider
- OS Version: MacOS Mojave 10.14.5

<img width="685" alt="Screen Shot 2019-06-18 at 5 20 48 PM" src="https://user-images.githubusercontent.com/31858171/59692965-bcf61a80-91ee-11e9-8f0f-a10d5cdc361f.png">

**Comment by alexandrudima** [comment]
@Iipal Could you please paste the text here or attach the file here, I am not 100% what I am looking at...

**Comment by Iipal** [comment]
@alexandrudima it's a lot of tabs before `i = ~0;`
```
void	foo(void)
{
	int	i;

																																																	i = ~0;
}
```

**Comment by alexandrudima** [comment]
Ok, steps to reproduce:
Have the following settings and open the above file:
```
"editor.wordWrap": "wordWrapColumn",
"editor.wordWrapColumn": 50,
"editor.rulers": [50]
```

This file + these settings causes wrapping to occur within the line leading whitespace, which confuses the indentation guides:

![image](https://user-images.githubusercontent.com/5047891/62615906-8dba7a80-b90e-11e9-8fdf-8cd2762edf96.png)

**Comment by Iipal** [comment]
@alexandrudima yeap, exactly what you says. Sorry for didn't added steps to reproduce, my fail

**Comment by alexandrudima** [comment]
Pushed a change where we now limit the rendering of indent guides to the wrapping column:

![image](https://user-images.githubusercontent.com/5047891/62623182-8b611c00-b920-11e9-96b5-2f3e8c0d0715.png)
