### ISSUE TITLE
Cycle through unsaved documents when clicking 'n Unsaved' label

### ISSUE THREAD

**Issue by maratumba** [microsoft/vscode#75708]
Cycle through unsaved files upon clicking on unsaved file number indicator in "Open Editors" title.

With too many open files, sometimes it can be difficult to figure out which ones are unsaved. This feature would alleviate the shuffling through the open files list.

Example: Upon clicking "1 Unsaved", the unsaved document should be opened in the editor. If there are more than one unsaved files, each click should take you to the next unsaved file.
![image](https://user-images.githubusercontent.com/2898911/59697787-c089a180-91ee-11e9-8966-c8162dc858f8.png)

**Comment by isidorn** [comment]
This is a fair feature request. Leaving it open and assigning to backlog since we do not currently have it on the plan.
