### ISSUE TITLE
Unsaved File Icon / Tab - Make it colored

### ISSUE THREAD

**Issue by edwardm** [microsoft/vscode#75719]
It would be nice if the "dot" icon that goes in place of the "x" icon, have some color applied to further emphasize to the user that a change has been made to the file. Perhaps make it orange or red?

OR, style the tab in such a way to show a change. For example a 1px solid top bordered, that's colored.

I find the dot not so obvious, unlike the appended asterisk in the normal Visual Studio, which has more "call-out" power to it.

![image](https://user-images.githubusercontent.com/444720/59710822-a041ee80-91be-11e9-9cc7-e7d2c0f301be.png)

**Comment by usernamehw** [comment]
```json
"workbench.editor.highlightModifiedTabs": true,
```

**Comment by edwardm** [comment]
@usernamehw oh wow, never knew that had that, cool thanks!
