### ISSUE TITLE
git bash not rendering output color

### ISSUE THREAD

**Issue by HR1991** [microsoft/vscode#75711]
Issue Type: <b>Bug</b>

Hi 
when i run git bash inside vscode by Ctrl+` all the output text are white but outside of vscode git-bash.exe work fine and render color
how to fix this problem ?

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (2.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.1.6
laravel-blade-spacer|aus|1.0.3
laravel-goto-view|cod|1.3.1
vs-phpclassgen|dam|0.1.0
goto-route-controller-laravel|erl|2.0.8
laravel-blade|one|1.20.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by HR1991** [comment]
but everything was okay suddenly this happen to my vscode

**Comment by Tyriar** [comment]
You might have tweaked the theme colors of cmd.exe/conhost outside of VS Code, other than that I don't know how this could have happened. Highly recommend moving to Windows 10.
