### ISSUE TITLE
CMD-W No Longer Closes Tabs

### ISSUE THREAD

**Issue by mikebronner** [microsoft/vscode#75710]
Issue Type: <b>Bug</b>

Open any file for editing in VSCode, CMD-W no longer closes the tab.

VS Code version: Code - Insiders 1.36.0-insider (7f53e50cbf316dff94fbbe5406d8f352dac99a6b, 2019-06-18T05:15:25.223Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.1.6
vscode-intelephense-client|bme|1.0.14
vscode-tailwindcss|bra|0.2.0
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.7
LogFileHighlighter|emi|2.5.0
file-icons|fil|1.0.17
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
phpcs|ika|1.0.5
path-autocomplete|ion|1.13.3
tailwind-sass-syntax|mac|1.1.1
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
atom-keybindings|ms-|3.0.6
vetur|oct|0.21.0
code-settings-sync|Sha|3.2.9
vscode-wakatime|Wak|2.1.2

(1 theme extensions excluded)

</details>

**Comment by mikebronner** [comment]
Those look related, but I am experiencing the issues in all tabs, not just the specific ones mentioned. This started today after updating insiders to version
```
Version 1.36.0-insider (1.36.0-insider)
7f53e50cbf316dff94fbbe5406d8f352dac99a6b
```

**Comment by mikebronner** [comment]
Work-around: I was able to restore functionality by adding the `CMD-w` key-binding to `workbench.action.closeActiveEditor`.

**Comment by mikebronner** [comment]
Also related: the window no longer closes when there are no more tabs open, when pressing `CMD-W`.

**Comment by rebornix** [comment]
@mikebronner thanks for the bug report. Fix is already in master and a new Insiders is on the way.

**Comment by andremacola** [comment]
Not only CMD + W but a bunch of other CMD + (X) commands

**Comment by mikebronner** [comment]
Keybindings seem to be restored with the latest update. Thanks for getting this fixed so quickly!

**Comment by rebornix** [comment]
@mikebronner thanks for your help and patience ;)
