### ISSUE TITLE
Cmd + n unbound in latest insiders

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#75712]
Issue Type: <b>Bug</b>

The `File: New Untitled File` command has no default keybinding on desktop insiders.

VS Code version: Code - Insiders 1.36.0-insider (7f53e50cbf316dff94fbbe5406d8f352dac99a6b, 2019-06-18T05:15:25.223Z)
OS version: Darwin x64 18.6.0

**Comment by mikebronner** [comment]
Related: #75710
Shortcuts to close editors and window are also unbound.

**Comment by rebornix** [comment]
It's already fixed in latest Insiders, @mikebronner @RMacfarlane thanks for your help.
