### ISSUE TITLE
Cannot open VSCode on Ubuntu 18.04.2

### ISSUE THREAD

**Issue by sakno** [microsoft/vscode#75714]
VSCode installed from `stable` channel is not launching after installing latest Ubuntu updates.

- VSCode Version: `c7d83e57`
- OS Version: Ubuntu 18.04.2 LTS, kernel `4.15.0-52-generic`

Log file in `~/.config/Code/logs/<timestamp>/main.log` is completely empty but created each time when I trying to launch VSCode.

The output `code --verbose` doesn't contain anything interesting:
```
(process:9273): Gtk-WARNING **: 19:21:09.916: Locale not supported by C library.
	Using the fallback 'C' locale.
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
[main 2019-06-18T16:21:10.161Z] Starting VS Code
[main 2019-06-18T16:21:10.163Z] from: /snap/code/9/usr/share/code/resources/app
[main 2019-06-18T16:21:10.163Z] args: { _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-modules': false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  nolazy: false,
  issue: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'prof-code-loading': false }
[main 2019-06-18T16:21:10.165Z] Resolving machine identifier...
[main 2019-06-18T16:21:10.165Z] Resolved machine identifier: bc5526b0964a06142d5cae0151e4b4e0540bf514a0f24721be83e09fa1d5c0dc
[main 2019-06-18T16:21:10.179Z] update#setState idle
[main 2019-06-18T16:21:10.194Z] [storage state.vscdb] open(/home/roman/.config/Code/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-06-18T16:21:10.195Z] windowsManager#open
```

`code --disable-extensions` with no luck.

VSCode Insiders is working normally.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sakno** [comment]
As I mentioned in the previous post, Insiders version is working normally. I've tested it using version `6520c22b`.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by sakno** [comment]
Unfortunately, the same story. Command line is `code --disable-extensions --user-data-dir /tmp/fresh-code/`

**Comment by Tyriar** [comment]
@bpasero maybe fixed in Electron 4?

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by sakno** [comment]
@bpasero, the last release fixes my problem, thanks!
