### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by SigmaDemon** [microsoft/vscode#75722]
Issue Type: <b>Bug</b>

It appeared when I did npm start and it should not appear because the application Compiled successfully and appeared. I checked online and the wrong message got posted along with the success message.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-install-vsix|fab|1.4.0
mssql|ms-|1.6.0
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-react-native|msj|0.9.3
vscode-docker|Pet|0.6.2

</details>

**Comment by sandy081** [comment]
I am not sure what the issue is and how it is related to VS Code. It sounds like this is related to node/npm issue. If so please file an issue against corresponding repositories.
