### ISSUE TITLE
Running a debug/build of dotnet project when root with multiple projects

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#7572]
- VSCode Version: 1.3
- OS Version: mac/windows

How does one setup vscode c# debugger to run and build projects when your workspace is root of git repo e.g.
 /
- src/
     - project1
     - project2
- test
    - testproject1
global.json

I want to be able to f5 and run which ever project i define but ever time in can't fine my project.json because it is running the build from the workspace dir, sort of like we like visual studio you set your startup project. 

Could we also define workspace dir or pull workspace dir from where the current selected omnisharp project is?

I'm pretty sure this used to just work but now its a bit messy.

Possibly I am just being completely retarted but it is a little frustrating

**Comment by JimiC** [comment]
[`launch.json`](https://code.visualstudio.com/docs/editor/debugging) has an options called `cwd` which sets the current working directory.

**Comment by dbaeumer** [comment]
@jrieken not sure if you or @isidorn @weinand

**Comment by weinand** [comment]
@dbaeumer C# and C# debugging are a separate extension. I suggest to always move this to https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by JimiC** [comment]
In VS Code you can't define the startup project for the debugger but you can set multiple configurations  that correspond to each project.

Here's an example:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/myElectronApp/scripts/main.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "compile",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "runtimeArgs": [
                "--enable-logging"
            ],
            "env": {},
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/src/myElectronApp/bin/resources/app",
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
                "runtimeArgs": []
            },
            "osx": {
                "outDir": "${workspaceRoot}/src/myElectronApp/bin/Electron.app/Contents/Resources/app"
            }
        },        
        {
            "name": "Test",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/tests/myElectronApp/scripts/main.ts",
            "stopOnEntry": false,
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "pretest",
            "externalConsole": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/tests/myElectronApp/bin"
        }
    ]
}
```

This is of course for an Electron app (Node.js) but you get the idea.

**Comment by eByte23** [comment]
Its more a problem with the c# extension as it used to work if I have multiple projects I don't want to manually have to define every project. especially when I am building the project like that is just stupid.

I should just say build and it builds my entire .net app.
But for example if I only have one project with an entry point and I say run debugger it should automatically run the project with an entry point.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#589
