### ISSUE TITLE
[UI Small bug] Error marker in problem panel is squished

### ISSUE THREAD

**Issue by V-ed** [microsoft/vscode#75721]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/16652915/59710906-fa9b7900-91d7-11e9-9f9b-c7b78ffa31d3.png)

As this screenshot and my title suggests, the error marker in the problem panel is squished, which even lead me to believe the warning was nested under the "CoreException" message. Also, the less the resolution (or VSCode's window size), the more squished this error icon looks.

By manually changing the css from `width: 16px` to `min-width: 16px`, the icon doesn't get squished anymore, which also doesn't seem to affect the other icons :
![image](https://user-images.githubusercontent.com/16652915/59711184-a5139c00-91d8-11e9-86f0-b02230948ea9.png)

I tried to find the line in the codebase to fix this, and the closest I got was finding this : https://github.com/microsoft/vscode/blob/da1061a273387a00ec1765945ed2a519d757d15d/src/vs/workbench/contrib/markers/browser/media/markers.css#L161-L163

I'll try to see if I can get a dev environment to actually compile and fix this small issue, but I tried in the past and got unsuccessfull - I'll try again in the next days.

I also downloaded the latest Insider (18 June 2019) to see if the same problem was present, which seems to also be present.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.4
project-manager|ale|10.5.2
copy-relative-path|ale|0.0.2
vscode-browser-preview|auc|0.5.9
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.28.0
vscode-quick-select|dba|0.2.8
vscode-faker|dee|1.3.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
docblocker|fly|0.4.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
gc-excelviewer|Gra|2.1.32
vscode-auto-open-markdown-preview|hnw|0.0.4
output-colorizer|IBM|0.1.2
autofilename|Jer|0.1.3
vscode-random|jre|1.6.0
vscode-github|Kni|0.30.2
expand-region|let|0.1.2
vs-color-picker|lih|1.0.0
rainbow-csv|mec|1.1.1
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
vscode-duplicate|mrm|1.2.1
powershell|ms-|2019.5.0
color-highlight|nau|2.3.0
snippet-creator|nik|0.0.5
material-icon-theme|PKi|3.8.0
view-in-browser|qin|0.0.5
java|red|0.46.0
vscode-xml|red|0.7.0
code-settings-sync|Sha|3.2.9
vscode-checkstyle|she|1.0.2
vscode-hexdump|sle|1.7.2
selectline-statusbar|tom|0.0.2
vscode-input-sequence|tom|0.2.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.7.0
vscode-todo-highlight|way|1.0.4
better-align|wwm|1.1.6
markdown-all-in-one|yzh|2.4.0

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Re - https://github.com/microsoft/vscode/issues/74534

**Comment by sandy081** [comment]
Fixed by e35ef3baffd513ce62c38d57473129a13d896760
