### ISSUE TITLE
Updating to 1.35 deleted all saved editor layouts

### ISSUE THREAD

**Issue by amloessb** [microsoft/vscode#75725]
Issue Type: <b>Bug</b>

I've just updated VS Code to 1.35, and it seems to have wiped all of my saved editor layouts (panes, open files, etc.) for all of the folders I use VS Code to work in.

Expected results:
Open files and editor layouts (e.g., panes) are retained when updating to a new version of VS Code.

Actual results:
Opening a folder (Ctrl + K, O) previously worked on in VS Code (and, indeed, with a .vscode folder already inside) shows a blank workspace, as if never opened before.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (7.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875

</details>

**Comment by bpasero** [comment]
@amloessb from which version did you update?

**Comment by amloessb** [comment]
Is there a way I can check what version I upgraded from, now that I've
already upgraded?  If not, I might be able to pull the old executable from
a backup.

Thanks.

**Comment by bpasero** [comment]
There is no real way.

**Comment by amloessb** [comment]
Unfortunately, the executable sits in Program Files, and therefore is not a
part of my backup set, so I'm not sure what version I upgraded from.

Sorry about that.

**Comment by bpasero** [comment]
Ok, since I have not heard this from other users, I am closing this. Sorry for the trouble.
