### ISSUE TITLE
Find and Replace sometimes doesn't work

### ISSUE THREAD

**Issue by saamirt** [microsoft/vscode#75723]
Issue Type: <b>Bug</b>

Using the search feature on the sidebar to search for text amongst all files in a folder will sometimes stop working. The replace all button will bring up the prompt confirming that you want to replace however many instances of the text but then nothing happens.  When it works, the instances of the text that it had previously found disappear after a replace all but when the issue occurs, those instances are still there and have not been changed. The feature works perfectly sometimes and replaces all instances but sometimes this happens.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.25GB free)|
|Process Argv|--folder-uri file:///c%3A/eclipse-workspace/Intern|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
prettier-vscode-standard|bys|0.22.1
path-intellisense|chr|1.4.2
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
prettier-vscode|esb|1.9.0
code-runner|for|0.9.11
gc-excelviewer|Gra|2.1.32
MagicPython|mag|1.1.0
rainbow-csv|mec|1.1.1
xml-format|mik|1.0.2
python|ms-|2019.5.18875
ayu|tea|0.18.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.1.7
jinja|who|0.0.8

</details>

**Comment by sandy081** [comment]
Can you give some more specific details? Can you reproduce it consistently? A sample to reproduce?

**Comment by saamirt** [comment]
I can't force it to happen as it happens inconsistently. It's a random but
frequent occurance and often a restart of vscode will fix it.

**Comment by sandy081** [comment]
Very difficult to fix it if there are no details to repro. 

Please record it if it happens next time (possibly) and provide to us. 

I am closing it for now and feel free to reopen when there is helpful info.
