### ISSUE TITLE
Break exploration icon in SVN extension

### ISSUE THREAD

**Issue by skotlex** [microsoft/vscode#75739]
- VSCode Version: 1.35.0-exploration
- OS Version: Win10 Pro

Steps to Reproduce:
* break exploration icon in SVN(https://github.com/JohnstonCode/svn-scm.git) extension
![1](https://user-images.githubusercontent.com/31692408/59738253-8c1fef00-929b-11e9-96dd-9c8daa3ba03b.png)
![2](https://user-images.githubusercontent.com/31692408/59738263-93df9380-929b-11e9-9d96-865001672f36.png)

* default icon in SVN extension
![3](https://user-images.githubusercontent.com/31692408/59738313-c5585f00-929b-11e9-895b-2396f9b1f21c.png)
![4](https://user-images.githubusercontent.com/31692408/59738314-c7222280-929b-11e9-8f05-5c0467a41b18.png)

**Comment by sandy081** [comment]
Please file an issue against the extension

**Comment by misolori** [comment]
@sandy081 FYI: if you ever see these squares, that has to do with my icon exploration (feel free to send them to me).
