### ISSUE TITLE
Weird autoformatting of es2015 import statements

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#7573]
- VSCode Version: 1.3.0-insider 2016-06-09T21:54:01.520Z
- OS Version: Mac OSX 10.11.5

Single line import statements get formatted like objects. This only happens with javascript not with typescript. Typescript seems to skip formatting of import statements.

Before saving:
```js
import {compose} from 'redux';
```

after saving:
```js
import {
    compose
} from 'redux';
```

Steps to Reproduce:

1. Create a .js file and paste `import {compose} from 'redux';`
2. Press save -> code gets formatted

**Comment by dbaeumer** [comment]
@marvinhagemeister any extension installed. VS Code doesn't offer a format on save of JS files and triggering format from the context menu in the editor doesn't format the code that way.

**Comment by JimiC** [comment]
True. I couldn't reproduce that behavior.

**Comment by marvinhagemeister** [comment]
@dbaeumer @JimiC Oh well, I fell stupid for not having thought of that! It was indeed an extension that caused this behaviour.

Thanks for your help!
