### ISSUE TITLE
vue style deep

### ISSUE THREAD

**Issue by huangxinrui** [microsoft/vscode#75734]
Issue Type: <b>Bug</b>

when use
/deep/ .select {
  color: red
}
at /deep/  tips: at-rule or selector expected

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 15.6.0

**Comment by sandy081** [comment]
I am not sure what is the issue here. If it is related to Vue specific issue please file the issue first against the Vue extension you are using.
