### ISSUE TITLE
Default formatter detection doesn't work when a default formatter is defined for multiple languages at once

### ISSUE THREAD

**Issue by lostfictions** [microsoft/vscode#75733]
VS Code allows defining per-language setting overrides in `settings.json` via the following syntax:
```js
"[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
    // any typescript-specific settings you want here...
}
```

It also supports configuring overrides for multiple languages at once by placing them all in the object key:

```js
"[javascript][javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

Unfortunately, the recently-added default formatter selection functionality doesn't seem aware of the latter, and will warn that a default formatter isn't set if it's configured via a multi-language override statement like the above. If `editor.formatOnSave` is set, the formatting will still occur correctly, but the "multiple formatters" notification will also appear:

![image](https://user-images.githubusercontent.com/567041/59729725-c0e56500-920d-11e9-8d65-ab655e18ecf6.png)

Clicking the "Configure..." action offered and selecting a formatter will add a new, redundant key below the existing definition, leaving our `settings.json` looking like this:
```js
"[javascript][javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**Expected behaviour**: VS Code should be aware of when a default formatter is configured over multiple languages at once and not display a warning or suggest adding an additional, redundant setting.

- VSCode Version: 1.35.1 and 1.36.0-insider
- OS Version: Ubuntu 16.04.1

Steps to Reproduce:

1. Install [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) from the Extensions tab

2. Add the following to your user-level `settings.json` (workspace settings probably also works, but I didn't try it):

    ```json
    "[css][scss][javascript][typescript][javascriptreact][typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
    ```

    Optionally, set `editor.formatOnSave` to `true`.

3. Create a new .js file with code that might cause Prettier to format the document. Sample:

    ```js
    function inconsistentQuotes() {
      console.log('Prettier is sure to hate one of these!');
      console.log("If not single quotes, then double quotes for sure!");
    }
    ```

4. Save the document (if `editor.formatOnSave` is enabled) or select "Format Document" from the Command Palette. A warning should appear in the notification area.

Does this issue occur when all extensions are disabled?: N/A, requires an additional formatter installed via extension to repro.

**Comment by jrieken** [comment]
> "[javascript][javascriptreact]": {

🔝 I don't think that's supported but adding @sandy081 to confirm

**Comment by sandy081** [comment]
Not Supported.

**Comment by lostfictions** [comment]
Hm, okay. So it's a bug that I'm able to define settings for multiple languages via this syntax? It seems to work for every other setting! I thought it was really handy :smile:

**Comment by jrieken** [comment]
> So it's a bug that I'm able to define settings for multiple languages via this syntax? 

🔝 @sandy081 I leave that to you... We might be able to know what languages we support

**Comment by sandy081** [comment]
@lostfictions Is this working when you override the formatter using single language?

**Comment by lostfictions** [comment]
@sandy081 yes, that's working! so if the ability to configure settings for multiple languages at once is not supported and only works accidentally, then i guess this isn't a bug. (on the other hand, i might make a feature request to officially support that functionality, because to me it's really useful!)

**Comment by sandy081** [comment]
Yeah please file a feature request or update this issue accordingly.
