### ISSUE TITLE
checkout git branch and then run in terminal bug

### ISSUE THREAD

**Issue by linlinyang** [microsoft/vscode#75744]
Issue Type: <b>Bug</b>

1、I have run my project in branch1, and run my unpack commend.It's ok;
2、Then I stop this commend,and checkout to branch2;
3、Then I run this branch's command,but it still run this branch1's project.
4、I try to close the terminal and reopen it to run, but no use.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
cssrem|cip|0.0.7
vscode-html-css|ecm|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
vetur-wepy|hu2|0.13.6
path-autocomplete|ion|1.13.3
vscode-autoprefixer|mrm|2.2.0
vscode-language-pack-zh-hans|MS-|1.35.1
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.11.4
color-highlight|nau|2.3.0
vetur|oct|0.21.0
material-icon-theme|PKi|3.8.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.7.2
scss-to-css|yut|2.1.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Are you checking git out using the git integration or the terminal? Can you show a screenshot of the problem?
