### ISSUE TITLE
Error Code Tips (red) On Scroll Bar

### ISSUE THREAD

**Issue by magician93** [microsoft/vscode#75743]
Issue Type: <b>Bug</b>

When full screen , the error code tips(red block) is can be see.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vsc-prolog|art|0.8.23
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.8.2
tslint|eg2|1.0.43
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.9.0
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.32
mysql-syntax|jak|1.3.1
vue|jcb|0.1.5
svn-scm|joh|1.54.1
vscode-styled-components|jpo|0.0.26
restructuredtext|lex|110.0.0
code-beautifier|mic|2.2.1
easy-less|mrc|1.4.5
vscode-language-pack-zh-hans|MS-|1.35.1
mssql|ms-|1.6.0
python|ms-|2019.5.18875
elmmet|nec|1.0.1
korofileheader|OBK|3.9.2
ruby|reb|0.23.0
java|red|0.46.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.2.9
trailing-spaces|sha|0.3.1
php-formatter|Sop|0.2.4
autoimport|ste|1.5.3
highlight-matching-tag|vin|0.9.2
vscode-java-dependency|vsc|0.5.0
vscode-icons|vsc|8.7.0
vscode-wakatime|Wak|2.1.2
quokka-vscode|Wal|1.0.227
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
local-history|xyz|1.7.0

</details>

**Comment by magician93** [comment]
Sorry , my mean is can't be see.

**Comment by sandy081** [comment]
Not sure what you mean, Can you please provide the screenshot of what you are not seeing?

**Comment by magician93** [comment]
Sorry ,my English is not good. But I still thank you! I have found the reason what is my display screen miss some area on right.
