### ISSUE TITLE
vscode.executeSelectionRangeProvider returns array of empty objects

### ISSUE THREAD

**Issue by sergei-dyshel** [microsoft/vscode#75746]
- VSCode Version: 1.35.1
- OS Version: Linux

By looking at the source there is a (still) undocumented command `vscode.executeSelectionRangeProvider` which is supposed to work similarly to other `execute...Provider` commands. 

When running the following code inside extension 
``` typescript
  const result = await commands.executeCommand(
      'vscode.executeSelectionRangeProvider', window.activeTextEditor!.document.uri,
      [window.activeTextEditor!.selection.active]);
  console.info(result);
```

and looking at the result in DevTools I see that the size of returned array looks valid but all objects (that are supposed to be of type `SelectionRange`) are empty.

![image](https://user-images.githubusercontent.com/6907277/59744187-a695a080-927a-11e9-9f58-775ea37d5c23.png)

It's important to note that expand/shrink commands work normally in editor so it's just *extension host* that receives empty objects. 

BTW, by looking at command's test in https://github.com/microsoft/vscode/blob/cb865f934a21830f4819bcf40b8d4b338e8bf279/src/vs/workbench/test/electron-browser/api/extHostApiCommands.test.ts#L799-L801 I see that only array size appears to be tested (which works correctly) but not array contents.

**Comment by jrieken** [comment]
Yeah, looks like this is using the wrong type...
