### ISSUE TITLE
Support vertical tabs

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#75749]
Firefox has an extension called Tree Style Tabs, which affords the user an opportunity to have vertical tabs. I think VSCode could implement something similar extremely easily in the form of a setting `window.tabLocation` which could be left, right, top, bottom. In the case of left and right we could see the tabs vertically. Vertical tabs work well on smaller screens. You can normally fit more tabs vertically than you can horizontally.

![image](https://user-images.githubusercontent.com/11936772/59746218-07ea4f00-923c-11e9-8b4b-72a6e5eb8f87.png)

**Comment by tristan957** [comment]
Is there a reason this was listed as out-of-scope?

I would like to investigate contributing a PR for this if possible. This issue probably depends on the UI being a grid. Was that implemented yet? I run 1.39.1. If I could be pointed in a direction (which files to look at), I could definitely give it my best effort. Is there a TabContainer widget somewhere?

**Comment by tristan957** [comment]
This is what I could come up with in a few minutes, just by changing a couple off CSS properties in the developer window

<img width="974" alt="image" src="https://user-images.githubusercontent.com/11936772/66765076-be6be280-ee70-11e9-8768-e554dc613ec0.png">

The scrollbar created at https://github.com/microsoft/vscode/blob/11f24f64e73504688822145ef322a82362516c8a/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L133 will also need changing. Maybe I will try out a fork and see what happens. Guidance definitely still appreciated.

**Comment by 625781186** [comment]
I think it's necessary !
Like this:
![image](https://user-images.githubusercontent.com/30521429/71318945-946b1800-24d2-11ea-95f2-56fc0ff5ea3e.png)
@tristan957 I support you!

**Comment by gjsjohnmurray** [comment]
See #85527 which needs upvoting

**Comment by santiagopuentep** [comment]
I just opened a new issue for this. In total the duplicates of this issue have 57 upvotes so this one many be accepted if we like it fast enough. Please upvote!

https://github.com/microsoft/vscode/issues/108264

**Comment by lcrocker** [comment]
Just got a new ultra-wide (32x9) monitor. Horizontal tabs are a criminal waste of precious screen real estate.

**Comment by vvxxvvxx** [comment]
the open files tabs occupy most of the space on vscode.. why the vertical tabs feature is so hard to be implemented...? I really don't understand why vscode dev team doesn't take this into their milestone?
