### ISSUE TITLE
editor.tabSize not respected when autoformatting on save

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#7574]
- VSCode Version: 1.3.0-insider
- OS Version: Mac OSX 10.11.5 2016-06-09T21:54:01.520Z

Steps to Reproduce:
```js
function main() {
  console.log("blah");
}
```
1. set `"editor.tabSize": 4` to `2` in your vscode-preferences
2. Paste the code from above
3. Press save -> code get's formatted with 4 spaces

**Comment by alexandrudima** [comment]
@marvinhagemeister The `editor.tabSize` setting is a fallback value in case detecting indentation fails (auto-detection can be controlled via `editor.detectIndentation`). What is the bottom area showing? Is the formatter respecting what is shown there?

![image](https://cloud.githubusercontent.com/assets/5047891/15999315/1bb40d24-3145-11e6-91d1-dc583b490ad0.png)

**Comment by marvinhagemeister** [comment]
@alexandrudima It was a formatting extension that applied formatting according to it's own settings. Should have checked that before making an issue...

Thanks for your help!
