### ISSUE TITLE
Cannot restart to update in disconnected remote context

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#75745]
I'm in a disconnected remote state and have an update pending:
![image](https://user-images.githubusercontent.com/172399/59743342-2ff3a580-9270-11e9-9879-b4168e2e344e.png)

When trying to restart to update nothing happens, there is no exception in the console.

**Comment by joaomoreno** [comment]
@sandy081 Related to the new commands?

**Comment by sandy081** [comment]
Not sure. Is it can be repro?

**Comment by joaomoreno** [comment]
It should yeah. Force an update by changing the commit id in product.json. Then, get an update. Then connect to SSH and close the connection somehow.

**Comment by sandy081** [comment]
Cannot repro it. I tried multiple ways and all works.

@egamma are there any other steps you might have?
