### ISSUE TITLE
Debug .net core app failed if the configurations[x].program contains space

### ISSUE THREAD

**Issue by Crazy7** [Microsoft/vscode#7575]
- VSCode Version:1.2.0
- OS Version:Windows 10

Steps to Reproduce:

1. Create a .net core project in a path contains space, such as C:\Users\XX\Documents\Visual Studio 2015\Projects\
2. Open the project in vs code, fill the lanch.json and start to debug

**Comment by JimiC** [comment]
Start debug from the debugger window. I suppose you are referring to a known issue #7291.

**Comment by isidorn** [comment]
Dup of #7291

**Comment by isidorn** [comment]
@Crazy7 works for me for debugging node applications that have a program that has whitespace in the path. 
Can you please share a screenshot of how vscode failed to start debug?

**Comment by weinand** [comment]
This issue is about .net and not node.js. I'll move it over...

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#430
