### ISSUE TITLE
HTML input/datalist fails to show dropdown in webviewPanel

### ISSUE THREAD

**Issue by BarryNolte** [microsoft/vscode#75752]
When the following text is used as the html property on a webviewPanel, the datalist control fails to drop down its list or autocomplete based on the input controls contents.
```html
<!DOCTYPE html>
<html>
<body>
    <input list="books">
    <datalist id="books">
        <select>
            <option value="Fiction">
            <option value="Non-Fiction">
        </select>
    </datalist>
</body>
</html>
```
If this html is in a file and opened by safari or edge for mac, it works as expected.  This also fails when viewed in a HTML preview pane using one of the many HTML preview extensions. 

It doesn't appear to have anything to do with the pane being wrapped with an iframe, if I wrap it with an iframe and open with a browser, it works as expected.

Expected behavior:
The drop-down arrow on the input control to actually drop and show the contents of the datalist.

**Comment by mjbvz** [comment]
This looks like an electron/chrome bug. Seems fixed in electron 6

**Comment by BarryNolte** [comment]
If I had thought to look in the electron bug database, this is all over the place.  Yup, electron bug.
