### ISSUE TITLE
Tasks set to run on folder open run twice

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/vscode#75758]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.36.0-insider (6520c22b83c0b6f168ba7de3309ffab42281e905, 2019-06-19T05:19:10.147Z)

OS version: Windows_NT x64 10.0.18908

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.05GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Kamen/Code/Stanga/Stylitics/stylitics-closet-essentials.sn77.net.git|
|Screen Reader|no|
|VM|0%|
</details>

Extensions: none

**Steps to Reproduce:**

1. Set up a project with a `tasks.json` as below (can be an empty project with nothing else)
2. From the command palette, execute `Tasks: Allow Automatic Tasks in Folder`
3. Reload project

**Expected behaviour after project restart:** each task with `"runOn": "folderOpen"` is started once.

**Actual behaviour after project restart:** each task with `"runOn": "folderOpen"` is started **twice**.

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "My Task",
			"promptOnClose": false,
			"command": "echo hello",
			"type": "shell",
			"args": [],
			"problemMatcher": [
				"$tsc"
			],
			"presentation": {
				"reveal": "always",
				"panel": "shared"
			},
			"group": "build",
			"runOptions": {
				"runOn": "folderOpen"
			}
		}
	]
}
```

Does this issue occur when all extensions are disabled?: **Yes**

I also notice high CPU usage from a `conhost.exe` process spawned from VSCode; this might or might not be related.

**Comment by NizamLZ** [comment]
Could not reproduce the issue
![tasks](https://user-images.githubusercontent.com/9017268/59772655-cf915200-92c9-11e9-9315-26f688b34e6e.gif)

**Comment by alexr00** [comment]
On the latest insiders I can reproduce it.

**Comment by alexr00** [comment]
Thank you for catching this @kamenminkov!

**Comment by kamenminkov** [comment]
@alexr00 Thanks for confirming! :)

**Comment by kamenminkov** [comment]
Seems like it's fixed in today's insider build, awesome!

**Comment by alexr00** [comment]
Thank you for verifying it too.
