### ISSUE TITLE
Problem with viewing the coding on the Internet

### ISSUE THREAD

**Issue by rishiajay** [microsoft/vscode#75769]
Issue Type: <b>Feature Request</b>

When I hit the Alt + B, it is not letting me get into the Internet. The refresh button on the page I am working on is not updating.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
Not sure which page you are talking about. Can you please provide a screenshot of what you mean?
