### ISSUE TITLE
加大Navigation中文件树图标的左右距离

### ISSUE THREAD

**Issue by Disciplining** [microsoft/vscode#75761]
- 用vocode打开一个目录或一个工作区，会有好多好多个文件.
- 父目录的图标和子目录的图标的左右距离太近，当打开很多文件时很容易看花眼.
- 希望能把左右的距离加大一些.

![Alt text](http://pic.liyanxing.top/QQ20190619182149.png)

**Comment by sandy081** [comment]
Please file the issue in english. Closing it.
