### ISSUE TITLE
Conda install of Black Formatter uses incorrect repository

### ISSUE THREAD

**Issue by AJDulk** [microsoft/vscode#75765]
Issue Type: <b>Bug</b>

1. Open a python file in a new conda environment.
2. Right click and select Format.
3. Select Black as your formatter.
4. Select to install using conda.

The command to install should use conda-forge (conda install -c conda-forge black) instead it tries to install it from the standard repositories.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 3.10.0-957.12.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3520)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|5.81GB (0.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql|for|0.4.0
python|ms-|2019.5.18875

</details>

**Comment by sandy081** [comment]
Please file the issue against the Python extension
