### ISSUE TITLE
C++ syntax highlighting and structured bindings

### ISSUE THREAD

**Issue by ebatsin** [microsoft/vscode#75766]
I have already opened this issue 2 days ago here : #75635
It was closed with no explanation so I recreate it here. It is my understanding that syntax highlighting issues are vscode jobs. If I am mistaken, could you direct me to the project handling syntax highlighting related issues ?

The syntax colorization is broken after any use of structured bindings (c++17).

- VSCode Version: 1.35.0
- OS Version: Linux x64 5.1.8-arch1-1-ARCH

Steps to Reproduce:

1. Open a new tab
2. Select c++ as the language
3. paste the following code snippet :

```c++

// The following code is not valid C++, it just shows the problem
// it seems to happen when a structured binding is assigned to a reference : 
//  `auto&` or `auto const&` or `const auto&`.

#include <tuple>
#include <vector>

std::vector<std::tuple<bool, int>> func() {
	return {{true, 2}};
}

int main() {

        // reverse these two statement and everything following the first line is broken
	auto const& tupl = condition ? func().front() : func().front();
	auto const& [first, second] = condition ? func().front() : func().front();

	/*
	 * func is not correctly colorized:
	 */
	for(auto const& [first, second] : func()) { }

	/*
	 * func is correctly colorized:
	 */
	for(auto const& tupl : func()) { }

	/*
	 * d->value is not correctly colorized (and the closing parens color is wrong too)
	 * Note: d->value pointing on an imaginary vector of tuple
	 */
	for(auto const& [first, second] : d->value) { }

	/*
	 * d->value is correctly colorized 
	 */
	for(auto const& tupl : d->value) { }

	/*
	 * first->value is not correctly colorized  (and the closing parens color is wrong too)
	 */
	if(auto const& [first, second]; first->value) { }

	/*
	 * tupl.first->value is correctly colorized 
	 */
	if(auto const& tupl; tupl.first->value) { }

	/*
	 *	Everything after the binding is not correctly colorized
	 */
	for(auto const& [first, second] = d->value; condition; ++increment) { }

	return 1;
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
A plain install of VSCode does not include C++ support, so you must have added an extension to give this. On the VSCode Activity Bar click the Extensions icon. Find the installed extension that's giving you your C++ features.  Look for the "Repository" link in its header. Click that. Go to the Issue section of its GitHub repo and open your ticket there.

**Comment by ebatsin** [comment]
A plain install of VSCode **includes** syntax hghlighting for C++...

I lost 10mn to check it...

1. I created a fresh Ubuntu 18.04 install in virtualbox. Nothing installed on it, first time I launch it
2. I installed VSCode from the "ubuntu software" app
3. I opened VSCode for the first time ever
![image](https://user-images.githubusercontent.com/9489603/59777028-23913c00-92b4-11e9-979e-0baeb34eaa83.png)
As you can see, there are no extensions enabled.

4. I open a new tab and I click in the language button in the bottom right corner of VScode :
![image](https://user-images.githubusercontent.com/9489603/59777117-520f1700-92b4-11e9-8676-16163599f304.png)

5. I click on C++ (which seems to be handled on a plain install of VSCode...)
6. I copy paste the code snippet that you can see above
![image](https://user-images.githubusercontent.com/9489603/59777196-7d920180-92b4-11e9-8f82-ff87fab11dc8.png)
7. I conclude that VSCode supports C++ syntax highligthing by default and that this syntax highlighting does not work as I explained two times before.

Now, please re-open this issue or tell me that you don't care about C++ syntax highlighting in your product, but stop with this "caused by extension"...

**Comment by gjsjohnmurray** [comment]
@ebatsin sorry I had forgotten about the builtin C/C++ Language Basics extension:
![image](https://user-images.githubusercontent.com/6726799/59782750-926f9480-92b6-11e9-83d5-8aa223dbb015.png)
Note that I'm an ordinary VSCode user just trying to help out here.  I am not a member of the development team. Nor am I a C/C++ user.

**Comment by sandy081** [comment]
@ebatsin Sorry for not looking deep into it. We support C++ syntax colouring OOB.

**Comment by ebatsin** [comment]
@aeschli, I haven't checked on the master build, but it looks like it could be fixed.

The issue has been reported here : [jeff-hykin/cpp-textmate-grammar#224](https://github.com/jeff-hykin/cpp-textmate-grammar/issues/224)

Fixed here: [https://github.com/jeff-hykin/cpp-textmate-grammar/pull/225](https://github.com/jeff-hykin/cpp-textmate-grammar/pull/225)

Merged into vscode here: [diff](https://github.com/microsoft/vscode/commit/6a7e5dbd0ea3a83b5a2488ae8e2a243effef686b#diff-6c9d8cb8e43d082572e9a66cff246d0cR4016) 8 days ago.

Since the last release is 9 days ago, it was not shipped with it but it should be in the next one (I can't check right now if this really fixes the issue).

I too should have looked deeper into it before opening this issue

**Comment by alexr00** [comment]
@ebatsin thanks for checking with the C++ grammar. I tested in insiders and the issue you show does appear to be fixed now. If you want to check, you can install insiders from [here](https://code.visualstudio.com/insiders/). It installs side by side with the stable release, so you can have both.

**Comment by ebatsin** [comment]
![image](https://user-images.githubusercontent.com/9489603/60020409-42b31380-9690-11e9-9f95-08d41df14db7.png)

I just checked. My issue is fixed in the insiders build
