### ISSUE TITLE
CMake driver died immediately after successful configure 

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#75762]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by kinglionsz** [comment]
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Impossible: CMake driver died
Impossible: CMake driver died immediately after successful configure
ed immediately after successful configure {}

Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?

"cmake.cmakePath": "cmake"

**Comment by sandy081** [comment]
Please file the issue against the corresponding extension (CMake) that is causing this.

**Comment by kinglionsz** [comment]
> [rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Impossible: CMake driver died
> Impossible: CMake driver died immediately after successful configure
> ed immediately after successful configure {}
> Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?
> "cmake.cmakePath": "cmake"

yes.

**Comment by kinglionsz** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.
> Happy Coding!

Hi,> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi, Nicolas twxs:



> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi,

> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin
I have  installed the Remote Development extension pack(vs code version 1.36.0),and use Remote-WSL,then CMake tools works very good.
build & debug, no any problems.

tks. very much.



> Please file the issue against the corresponding extension (CMake) that is causing this.

I have  installed the Remote Development extension pack(vs code version 1.36.0),and use Remote-WSL,then CMake tools works very good. build & debug, no any problems.

**Comment by kinglionsz** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.
> Happy Coding!

> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.
> Happy Coding!

Hi,> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi, Nicolas twxs:



> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin

Hi,

> Hi,
> I think this issue is for the vscode-cmake-tools (https://github.com/vector-of-bool/vscode-cmake-tools) plugin
I have  installed the Remote Development extension pack(vs code version 1.36.0),and use Remote-WSL,then CMake tools works very good.
build & debug, no any problems.

tks. very much.



> Please file the issue against the corresponding extension (CMake) that is causing this.

I have  installed the Remote Development extension pack(vs code version 1.36.0),and use Remote-WSL,then CMake tools works very good. build & debug, no any problems.

tks.
