### ISSUE TITLE
Tree guides might appear misaligned or wider when window.zoomLevel is not 0

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#75779]
Issue Type: <b>Bug</b>

I usually use VSCode with `window.zoomLevel` set to `1`. With this value tree guides sometimes look wider than for files above/below or looks shifted (mostly noticeable at zoom level `0.5`).

Doesn't look like it depends on anything except  `window.zoomLevel` (reproducible with file icons disabled)

Examples:

| `"window.zoomLevel": 1` | `"window.zoomLevel": 0.5` |
|---|---|
| ![image](https://user-images.githubusercontent.com/1312662/59774289-e6c74400-92b7-11e9-86e6-1489c6d0548c.png) | ![image](https://user-images.githubusercontent.com/1312662/59774199-b97a9600-92b7-11e9-933b-c91a6d82fc17.png) |

It is non-retina display with 1980x1080 resolution and 100% scale in Windows settings.

VS Code version: Code - Insiders 1.36.0-insider (6520c22b83c0b6f168ba7de3309ffab42281e905, 2019-06-19T05:19:10.147Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
This is definitely not related to the terminal.

And looks like @joaomoreno pushed fix https://github.com/microsoft/vscode/commit/c76027bbf4532815facae5a2df4017d57f4be51a while I was creating this issue.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/c76027bbf4532815facae5a2df4017d57f4be51a

**Comment by IllusionMH** [comment]
@joaomoreno looks like there are still cases when guides don't look crisp on deeply nested files. When viewBox "width" will have have fractional portion close to 0.5 e.g. `viewBox="0 0 105.60000419616699 26.400001049041748"`


![image](https://user-images.githubusercontent.com/1312662/59839990-39f1d300-935a-11e9-9827-d4e6bdec4f4e.png)

After manual tweaks in DOM it looks like at that at least `virtualWidth` should be rounded to integer value  (sometimes up and sometimes down 0_o) to look sharp
https://github.com/microsoft/vscode/blob/983069b176088a3b62fc19dcfd2228af9143b746/src/vs/base/browser/ui/tree/abstractTree.ts#L391

---

Side note: Is it expected that SVG with guides is 8px wider than its parent element and actually there is nothing rendered in those 8px?
![image](https://user-images.githubusercontent.com/1312662/59841185-7faf9b00-935c-11e9-9634-b4935946be98.png)
Feels like there should should be
```ts
const width = this.indent * (target.depth - 1);
```
but I will be able to play with code only in the evening.

**Comment by joaomoreno** [comment]
Let's reopen this.

**Comment by joaomoreno** [comment]
Went away from SVG :cry: and into old fashioned divs.

**Comment by IllusionMH** [comment]
@joaomoreno checked implementation with good ol' divs and it works as expected with different zoom levels and screens with different DPI 👍 

Thanks for the fix 🙇
