### ISSUE TITLE
Error when more than 999 rows using the Alt+Enter multiple cursor editor

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7577]
- VSCode Version:  1.3.0-insider
- OS Version: OS X 10.11.4

Steps to Reproduce:
1. <kbd>Cmd</kbd> + <kbd>F</kbd>
2.  <kbd>Alt</kbd> + <kbd>Enter</kbd>

cc @Inori in https://github.com/Microsoft/vscode/pull/5715
![demo](https://img.alicdn.com/tps/TB1CQDgKpXXXXaVXpXXXXXXXXXX-421-368.gif)

cc @egamma

**Comment by alexandrudima** [comment]
This has been already fixed.
