### ISSUE TITLE
Flaky test: TerminalConfigHelper getFont fontFamily

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#75772]
From: https://dev.azure.com/vscode/VSCode/_build/results?buildId=20920

1) Workbench - TerminalConfigHelper TerminalConfigHelper - getFont fontFamily:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

Skipped via https://github.com/microsoft/vscode/commit/57044c615aad6d2fe1366f8aa8b08129a8baa3f1

**Comment by Tyriar** [comment]
This is a strange error as it's not an async test... I can't reproduce it locally so I'm guessing this is just a one off failure. I'm going to split that test into 4 separate ones and will see if it happens again.
