### ISSUE TITLE
Indent guide overlaps with folder with no twistie

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#75773]
#17777

![image](https://user-images.githubusercontent.com/4033249/59771056-99f56480-92db-11e9-96e2-293c8c294bf7.png)

Repro:

- Install Ayu Icon theme: https://marketplace.visualstudio.com/items?itemName=teabyii.ayu
- Select it

Version: 1.36.0-insider
Commit: 6520c22b83c0b6f168ba7de3309ffab42281e905
Date: 2019-06-19T05:18:56.881Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0

**Comment by joaomoreno** [comment]
Great catch!

**Comment by sarahkittyy** [comment]
This was not fixed for me as of the latest VSCode Insiders build? Maybe the fix just wasn't pushed there yet?

![image](https://user-images.githubusercontent.com/31551546/59857656-5a646200-9347-11e9-8789-b1fa7a0a5233.png)

### VSCode Version:
```
1.36.0-insider
c3fe2d8acde04e579880413ae4622a1f551efdcc
x64```

**Comment by octref** [comment]
@joaomoreno Can confirm, not fixed for me either on c3fe2d8acde04e579880413ae4622a1f551efdcc:

![image](https://user-images.githubusercontent.com/4033249/59896846-bbaa3500-941c-11e9-852d-21aecd51c350.png)

**Comment by joaomoreno** [comment]
The fix is in 9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21 (today's)

**Comment by octref** [comment]
Cool, I confirm it's fixed in the latest build.

![image](https://user-images.githubusercontent.com/4033249/59907346-74806c00-943d-11e9-98a0-3fe0301427e4.png)

**Comment by dubeg** [comment]
Could we have the guide aligned leftmost to folderIcons? 
If not, because the alignment is specified statically (say, n pixels to the left), would it be doable to implement a dynamic alignment without too much trouble?
