### ISSUE TITLE
The Powershell Terminal Buffer Length Not Configurable

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/vscode#75778]
Issue Type: <b>Bug</b>

Tab Complete on long lines is apparently broken? I don't see a way to extend the buffer length of the terminal in order to correct this.

PS C:\Users\jeff0372\source\repos\rsazure-internal-buildtemplates\Microsoft.Automation\automationAccounts> New-AzureRmResourceGroupDeployment -Name testing-automationaccounts -ResourceGroupName testing-aa -TemplateFile aut
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18917

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (24 x 2660)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|36.00GB (22.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
vs-code-xml-format|fab|0.1.5
rest-client|hum|0.21.3
vscode-sprint-planner|ipa|0.2.0
diff-tool|jin|0.0.1
terraform-azure-autocomplete|las|0.0.1
terraform|mau|1.3.12
vscode-azureterraform|ms-|0.2.4
mssql|ms-|1.6.0
python|ms-|2019.5.18875
azure-account|ms-|0.8.4
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.6.0

</details>

**Comment by Tyriar** [comment]
Does this also happen in the Windows Terminal preview? https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab
