### ISSUE TITLE
broken icons in exploration build (SVN extension) (+attachments)

### ISSUE THREAD

**Issue by skotlex** [microsoft/vscode#75784]
- VSCode Version: 1.35.0-exploration
- OS Version: Win10 Pro

*issue #75739
- exploration icon set
[theme-icon-explorations.zip](https://github.com/microsoft/vscode/files/3306962/theme-icon-explorations.zip)
- SVN extension
https://github.com/JohnstonCode/svn-scm

This is the basic icon theme of the exploration build.

**Comment by misolori** [comment]
This should be fixed in tomorrow's Insiders:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/35271042/59788337-591c3200-9280-11e9-8c4a-42f2186d38cc.png">

**Comment by skotlex** [comment]
thank you :p
