### ISSUE TITLE
Update fails spectacularly on Debian.

### ISSUE THREAD

**Issue by KBassford** [microsoft/vscode#75780]
Issue Type: <b>Bug</b>

For the last week VS Code has nagged me on startup to "Download an update".  Coincidentally apt issued a major update last week (June 11) that wiped out all the user installed repos, including vscode's.  I recreated the vscode.list and installed the key for repo to get it working again, and it claims that I am currently running the latest version of VSCode.

The problem ensues if you are dumb enough to click the "Download an Update" button.  It will open my default browser (in my case, Chrome), and will immediately cause an error as it also knocks the Google Sync off-line in the browser.  This in turn causes a cascade failure of several plugins and all user settings in Chrome.  The only way I've found to recover is to completely reboot the box, logging back into Google after vscode has knocked them off-line will not fully recover (some settings come back, but not all, and none of the browser plugins/extensions are recoverable).

Note: While filling this bug report out, made the mistake of clicking the "Preview on GitHub" button, resulting in the exact same corruption of my system as noted in step 2 below!

To reproduce ...
1.    Run "sudo apt update"
      (Indicates everything is up to date, including "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main")
2.   Start Visual Studio Code
     (Within seconds of starting, a popup box appears indicating a "newer version is available", click button labled "Download", watch as all browser windows opened after the one opened by vscode are rendered useless, throwing errors and forcing you to reboot the system.)

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 4.18.0-parrot10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 2393)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.55GB (12.10GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.4.0
better-toml|bun|0.3.2
dep|car|0.1.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.5.0
tomato|duy|1.1.13
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
vscode-git-history|fab|2.0.5
gitlab-workflow|fat|2.1.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
MagicPython|mag|1.1.0
git-graph|mhu|1.8.0
vscode-docker|ms-|0.6.3
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
Go|ms-|0.11.0
go-critic|nev|0.1.0
iferrblocks|rst|1.1.1
gotimeformat|v4r|1.0.1
vscode-postfix-go|yok|0.0.12

</details>

**Comment by joaomoreno** [comment]
We've since released a Snap package, which I highly recommend switching to. It's what I use for my selfhosting setup. Comes with easy installation (`snap install code`) and background updates. Wanna try switching to that?

https://twitter.com/joaomoreno/status/1112985658002468864

**Comment by KBassford** [comment]
Really?  I gave enough information to pin down that your URL launcher is borked (pretty narrow to me).  Once you get down to that level, then it's a matter of "How you're calling that URL?"  Anything other than the equivalent of "google-chrome-stable  <insert URL here>" (for Chrome), then you run the risk of running afoul of firejail and/or the browser settings (which it appears that Chrome uses Google Sync to retrieve the settings, calling "google-chrome" vs "google-chrome-stable" appears to bypass the settings, producing similar, though not as dramatic results to those previously noted).  Your going to have to take that into account when launching the default browser from your application.

Adding another layer of abstraction (one not adopted by the community at-large no less) to running your application does not seem to be a viable solution to the problem of launching URL's.  The suggestion gives me flashbacks of running buggy programs with outdated/non-standard dependencies where one would have to render their system unusable for anything else but running their particular application.

**Comment by joaomoreno** [comment]
> I recreated the vscode.list and installed the key for repo to get it working again, and it claims that I am currently running the latest version of VSCode.

Can you explain this better?

> The problem ensues if you are dumb enough to click the "Download an Update" button. It will open my default browser (in my case, Chrome), and will immediately cause an error as it also knocks the Google Sync off-line in the browser. This in turn causes a cascade failure of several plugins and all user settings in Chrome.

Can you elaborate this? What error? Can you share a screenshot of that?

---

@Tyriar Do the apt repos not have the latest Code published? Can you verify that?

**Comment by KBassford** [comment]
> > I recreated the vscode.list and installed the key for repo to get it working again, and it claims that I am currently running the latest version of VSCode.
> 
> Can you explain this better?
```
Wed 26 Jun 2019 09:07:39 AM EDT
└──╼ $sudo apt update
[sudo] password for kbassford: 
Hit:1 https://packages.microsoft.com/repos/vscode stable InRelease
Get:2 https://deb.parrotsec.org/parrot parrot InRelease [14.6 kB]                            
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                       
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                                                         
Hit:6 http://repository.spotify.com stable InRelease                                                                               
Fetched 14.6 kB in 15s (947 B/s)                                                                                                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
┌─[kbassford@Portunus]─[~]
└──╼ $sudo apt --only-upgrade install code
Reading package lists... Done
Building dependency tree       
Reading state information... Done
code is already the newest version (1.35.0-1559611369).
The following packages were automatically installed and are no longer required:
  linux-headers-5.1.0-parrot1-3t-amd64 linux-headers-5.1.0-parrot1-3t-common linux-kbuild-5.1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
> 
> > The problem ensues if you are dumb enough to click the "Download an Update" button. It will open my default browser (in my case, Chrome), and will immediately cause an error as it also knocks the Google Sync off-line in the browser. This in turn causes a cascade failure of several plugins and all user settings in Chrome.
> 
> Can you elaborate this? What error? Can you share a screenshot of that?
![VSCode_nag](https://user-images.githubusercontent.com/31860128/60182292-12838600-97f2-11e9-8acc-973079fbf5d4.png)
I don't see what this buys you, but you asked.
> 
> > Adding another layer of abstraction (one not adopted by the community at-large no less) to running your application does not seem to be a viable solution to the problem of launching URL's.
> 
> Still, snaps are currently our suggested distribution mechanism for now. It wouldn't hurt to give it a try anyway, right? Let me know how that works for you.

Instead of battering the messenger of bad tidings (blaming them for problems inherent in your software), wouldn't it be more productive to figure out how you are launching URL's?  Installing another, non-standard, proprietary package management (with software deployment shells) ecology, not supported by my chosen OS is not a solution, it's an excuse.  (My apologies for being blunt.)

I would think the hints I gave pertaining to Firejail (which I'm guessing is blocking the URL from being opened using a non-standard method, like calling the bin directly, and which does not occur when any other program resident on my system opens a URL) would be enough to recreate the bug.

This is exasperating enough to convince me to switch to another IDE.
> 
> @Tyriar Do the apt repos not have the latest Code published? Can you verify that?

**Comment by Tyriar** [comment]
@joaomoreno 1.35.1 is definitely published as you can see in http://packages.microsoft.com/repos/vscode/pool/main/c/code/

![image](https://user-images.githubusercontent.com/2193314/60222829-a6c20d00-9833-11e9-8d07-ac230ed4bc57.png)

It also installs fine for me:

![image](https://user-images.githubusercontent.com/2193314/60222872-d2dd8e00-9833-11e9-9ce7-66a861e71690.png)

> Instead of battering the messenger of bad tidings (blaming them for problems inherent in your software)

@KBassford he simply *suggested* using the snap as a possible workaround, he certainly isn't blaming you for anything.
