### ISSUE TITLE
PHP: Accept \\wsl$\<distro>\path\to\php as php.validate.executablePath

### ISSUE THREAD

**Issue by pamtbaau** [microsoft/vscode#75788]
This request looks like [#22391 : Is it possible to use wsl bash php for php.validate.executablePath](https://github.com/microsoft/vscode/issues/22391) and the suggested workaround using a *.bat file works indeed.

Since Windows 10 build 1903 now supports accessing files in WSL using `\\wsl$\<distro>path\to\file`, it would be nice to use this reference for `php.validate.executablePath`

**Comment by roblourens** [comment]
I think that would be a linux binary that we can't run in a windows context.

See some details about developing in WSL here: https://code.visualstudio.com/docs/remote/wsl
