### ISSUE TITLE
Extension: findTextInFiles is not found in editor

### ISSUE THREAD

**Issue by wangchou** [microsoft/vscode#75786]
- VSCode Version: 1.35.1
- OS Version: 10.14.5

Steps to Reproduce:

1. create an extension and type `vscode.workspace.findTextInFiles`
 
![スクリーンショット 0001-06-20 0 20 06](https://user-images.githubusercontent.com/32716/59782895-835a0800-92f1-11e9-9406-9c301a24f7a9.jpg)

Tried this api and it works perfectly. But 
* it shows error in editor. 
* cannot trigger auto-complete in editor
* no related document in https://code.visualstudio.com/api/references/vscode-api
(the only document I found is https://code.visualstudio.com/updates/v1_26#_findtextinfiles-api)

Does this issue occur when all extensions are disabled?: Yes

**Comment by carloslahrssen** [comment]
Looks to me that it is in the proposed typescript declaration file under 
`vscode/src/vs/vscode.proposed.d.ts`, specifically [here](https://github.com/microsoft/vscode/blob/c3fe2d8acde04e579880413ae4622a1f551efdcc/src/vs/vscode.proposed.d.ts#L520)

If you're looking to use it, make sure to follow these steps located [here](https://code.visualstudio.com/api/advanced-topics/using-proposed-api)

Just make sure to enable the use of the proposed api by going to your extensions package.json and inserting 
```json
"enableProposedApi": true
```
as well as inserting the vscode.proposed.d.ts file located [https://github.com/microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts](url) into your project. 

I've duplicated this error and following the steps above fixed it for me.

**Comment by wangchou** [comment]
@carloslahrssen Thank you. Just unpublished the extension. (vsce / vscode didn't check using `proposed extension api` or not.)
