### ISSUE TITLE
Inteli-sense Stops working

### ISSUE THREAD

**Issue by mrfambo** [microsoft/vscode#75783]
Issue Type: <b>Bug</b>

Its being a pain for me from past months. I am a JS developers. All of a sudden every possible Intelisense stops working. It doesn't give me any help while i am trying to write a function name defined even in the same .js file. 

Similarly, it stops working on every react specific Intelisense e.g style={{}}, within styles intelisense stops working.

It even doesn't help me with the code errors. It stops giving me variables help in the same file, which i have declared. 

The only solution is to completely Quit the VSCode (even if you have multiple projects opened) and restart it. It seems liks a pain when after every 5 minutes you need to restart your editor.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
es7-react-js-snippets|dsz|2.3.0
vscode-great-icons|emm|2.1.47
todo-tree|Gru|0.0.135
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.13
propertylist|zho|0.0.2

</details>

**Comment by mrfambo** [comment]
Downloaded another IDE, (Not mentioning the name). It is working like a charm, but i loved VSCode.

**Comment by gjsjohnmurray** [comment]
If you run VSCode without any of your 8 extensions enabled, does the problem occur? If not, enable them one at a time and try to discover which one is causing your problem.

**Comment by mrfambo** [comment]
Let me check and get back to you shortly !!!

**Comment by mrfambo** [comment]
Hello, Thank you for waiting.

I disabled all the extensions and then started working on it again. It worked fine till i left the Mac for a moment. Mac went to sleep, when i came back and started to work intelisense is not working. Let me get through it for a couple of times to give better clue.

One more thing which i noticed previously, when i do editing on the code and switch to Browser and goes back to VSCode its intelisense stops working. Probably something is happening when VSCode is getting Idle.

**Comment by mrfambo** [comment]
It is not being effected with Mac going to sleep, i did confirm that. Something else is wrong with it. Should i clean install the VSCode again ?

**Comment by mrfambo** [comment]
UPDATE: Intelisense is working fine even if the Mac was asleep for longer period. So i am excluding it from the list of Possible reasons.
But i still can't figure out the reason. Can i know a way to observe the intelisense service if any or any logs coming into the VSCode?

**Comment by mjbvz** [comment]
Can you reliable reproduce the issue?
