### ISSUE TITLE
CLI command to get syntax highlighting of file

### ISSUE THREAD

**Issue by 0xc0** [microsoft/vscode#75789]
The HTML-formatted syntax highlighting of a file can be obtained in a window by copying the contents to the clipboard. This issue is to suggest a programmatic way of doing this via the command line. For example, running
```
code --syntax <file>
```
would print to stdout (without needing to open a window) the same HTML as would be obtained from copying the file within the editor window.

**Comment by mjbvz** [comment]
Likely not something we'd want to add to core VSCode but would be enabled by #56356
