### ISSUE TITLE
problem with pygame and vsc

### ISSUE THREAD

**Issue by udnie** [microsoft/vscode#75797]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Why is it vsc gives me errors when trying to run python code which has no
such problem in pycharm, or textwrangler???

It doesn't like import pygame as pg for example.

# ---------------------- shapes.py  --------------------
import pygame as pg
import random

from pygame.sprite import Sprite

# -------------------- some shapes ---------------------
square = [(120.0, 120.0),(600.0, 120.0),(600.0, 600.0),
            (120.0, 600.0)]

triangle = [(345.0, 100.0),(585.0, 585.0),(115.0, 585.0)]

pointer = [(453.0, 528.0),(359.0, 447.0),(266.0, 534.0),
            (322.0, 302.0),(271.0, 306.0),(360.0, 185.0),
            (442.0, 309.0),(392.0, 300.0)]

star = [(66.0, 295.0),(250.0, 419.0),(181.0, 638.0),
        (369.0, 506.0),(548.0, 640.0),(474.0, 427.0),
        (653.0, 294.0),(433.0, 296.0),(361.0, 81.0),
        (292.0, 294.0)]

cross = [(297.0, 565.0),(297.0, 421.0),(158.0, 421.0),
        (158.0, 299.0),(297.0, 299.0),(297.0, 158.0),
        (422.0, 158.0),(423.0, 301.0),(562.0, 302.0),
        (561.0, 421.0),(423.0, 421.0),(423.0, 564.0)]

awuf = [(298, 15), (327, 15), (357, 29), (385, 43), (408, 63),
        (437, 89), (458, 95), (473, 125), (480, 155), (483, 185),
        (493, 208), (489, 238), (482, 268), (470, 297), (451, 327), (464, 336),
        (447, 364), (424, 388), (397, 405), (369, 410), (339, 409), (325, 416),
        (336, 442), (342, 472), (322, 490), (293, 497), (264, 499), (235, 499),
        (206, 494), (190, 471), (188, 442), (163, 435), (143, 412), (114, 411),
        (84, 403), (69, 377), (63, 350), (43, 321), (30, 291), (26, 261), (37, 240),
        (31, 210), (29, 180), (39, 150), (54, 120), (79, 109), (107, 83), (129, 63),
        (158, 51), (184, 33), (214, 24), (244, 18), (274, 17)]

shape_list = [square,star,cross,pointer,awuf]
new_shapes = []

# -------------------- add some color -------------------
palette = ['dodgerblue', 'aquamarine',  'burlywood',
        'coral',         'cyan',        'darkseagreen',
        'deepskyblue',   'dimgray',     'lightslategray',
        'whitesmoke',    'hotpink',     'lightcoral',
        'lightgreen',    'lightsalmon', 'lightskyblue',
        'lightseagreen', 'magenta',     'tomato',
        'orangered',     'grey75',      'darkgrey' ,
        'yellow',        'darkred']

colors = []

# -------------------- screen and sprites ----------------
screen_width = 1100
screen_height = 720

number_of_sprites = 90 

# ------------------------ classes -----------------------
class Shapes(Sprite):

    def __init__(self, poly, width, height):
        super(Shapes,self).__init__()
        # randomize opacity between 100-255
        alpha = random.randrange( 20, 40) * 5

        # get the rgb part of a palette color
        r, g, b = random.choice( colors )[:3]
        color = pg.Color( r, g, b, alpha )

        # draw the polygon onto a same-size transparent surface
        self.save_image = pg.Surface((width,height), pg.SRCALPHA)

        # if zero length it's a circle
        if len( poly ) == 0:
            wuf = int( width / 2 )
            pg.draw.circle(self.save_image, color, (wuf,wuf), wuf, 0 )
        else:
            pg.draw.polygon(self.save_image, color, poly, 0)

        # rotate randomly
        rot = random.randrange(1,360 )
        self.save_image = pg.transform.rotozoom(self.save_image, rot, 1.0)

        # scale the surface size of original - make it smaller
        scale = random.randrange( 10, 45 ) / 100.0
        scale = ( int((width) * scale), int((height)* scale) )
        self.save_image = pg.transform.smoothscale( self.save_image, scale )

        self.image = self.save_image
        self.rect = self.image.get_rect()   # current boundaries
        self.vel = random.randrange(3,8)    # change it's speed
        self.direct = random.randrange(1,7) # change direction

        self.angle = 0
        self.angle_change = 8

    def update(self):
        off_screen = False
        if self.direct == 1:
            self.rect.y -= self.vel
            if self.rect.y < -random.randrange( 100, 200 ):     # is off screen
                y = random.randrange( 20, 50 )  # reset above y
                self.rect.y = y + screen_height
                self.vel = random.randrange(4,9)    # change it's speed
                off_screen = True
        else:
            self.rect.y += self.vel
            if self.rect.y > screen_height + 50:  # is off screen
                y = -random.randrange( 100, 200 ) # reset above y
                self.rect.y = y
                self.vel = random.randrange(3,8)    # change it's speed
                off_screen = True

        if off_screen == True:
            x = random.randrange(-50, screen_width)
            self.rect.x = x                     # reset x as well
#             if self.direct == 2:
#                 self.image = pg.transform.rotate(self.save_image, self.angle)
#                 self.angle += self.angle_change
#                 self.angle = self.angle % 360

class Transposed():
    # a class ito hold the updated shapes and their width/height
    def __init__(self, poly, width, height):
        self.shape = poly
        wuf = max( width, height )  # need longest side for rotations
        self.width = wuf
        self.height = wuf

#-------------------------- functions -------------------------
def set_colors(palette):
    for color, rgba in pg.color.THECOLORS.items():
        if color.find('gray') != -1 and color.find('slate') == -1:
        # if color in palette:
            colors.append(rgba)

def transpose_shapes(shapes):   # reposition polygons - save in new_shapes
    while shapes:
        poly = shapes.pop(0)
        minx, maxx, miny, maxy = get_width_height(poly)
        # tighten up x,y in the tmp
        tmp = []
        for t in poly:
            tmp.append((t[0] - minx, t[1] - miny))
        # return repositioned polygon and width/height
        tmp = Transposed( tmp, int( maxx-minx ), int( maxy-miny ) )
        new_shapes.append( tmp )
    tmp = []  # trigger for drawing a circle
    new_shapes.append( Transposed( tmp, 500, 500 ) )

def get_width_height(poly):  # get the polygon's minx, maxx, miny, maxy
    tmp = sorted(poly)
    minx, maxx = tmp[0][0]-1, tmp[-1][0]+1
    tmp = sorted(poly,key=lambda x: x[1])
    miny, maxy = tmp[0][1]-1, tmp[-1][1]+1
    return minx, maxx, miny, maxy

def init_sprites(num):
    for i in range(num):
        s = random.choice( new_shapes )
        sprite = Shapes( s.shape, s.width, s.height )
        sprite.rect.x = random.randrange(-20,screen_width)
        sprite.rect.y = random.randrange(-200,screen_height)
        sprite_list.add(sprite)

# --------------------- initialization ---------------------
pg.init()

screen = pg.display.set_mode([screen_width, screen_height])
pg.display.set_caption('python 3.7 shapes')

# set the color palette
set_colors(palette)

# list to keep track of sprites
sprite_list = pg.sprite.Group()

# reposition a shape to the upper left corner
# assuming shapes are approx. 500X500 px
transpose_shapes(shape_list)

# make a bunch of sprites
init_sprites(number_of_sprites)

clock = pg.time.Clock()
done = False

# -------------------------- begin ------------------------
while not done:

    for event in pg.event.get():  # check for exit
        if event.type == pg.QUIT or \
            (event.type == pg.KEYDOWN and \
            event.key in [pg.K_ESCAPE, pg.K_x, pg.K_q]):
            done = True

    screen.fill(pg.Color('whitesmoke'))

    sprite_list.update()         # using a Group to update and draw
    sprite_list.draw(screen)

    clock.tick(45)
    pg.display.flip()

pg.quit()

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (10.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension

**Comment by udnie** [comment]
I'm not sure if this is an answer or what?  Would you like me to upload the file using this window?
I've had this problem in the past and thought I give vsc another try after hearing Dan Taylor on a podcast.

**Comment by gjsjohnmurray** [comment]
@udnie https://github.com/Microsoft/vscode-python/issues

**Comment by udnie** [comment]
Hi,

Looks like I needed to add python extensions to make it work.
working now.



On Jun 20, 2019, at 3:20 AM, John Murray <notifications@github.com> wrote:

@udnie https://github.com/Microsoft/vscode-python/issues
