### ISSUE TITLE
Insiders Git SCM regenerates .git/index

### ISSUE THREAD

**Issue by juliancoleman** [microsoft/vscode#75796]
- VSCode Version: 1.36-insiders
- OS Version: MacOS Mojave

I'm not sure the cause of this, but I get the following Git output

```sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```

After this, if I `ls .git`, tells me that I have an `index ##` (where `##` is some number, and continues to increment) file. If I rename this file to just `index`, the moment I open a file, it will rename `index` to `index ##`, and will continue to increment. I haven't experienced this issue before today, and I have disabled all extensions, but the `Git SCM` extension still seems to be running.

This results in Git telling me that at some point, I deleted all the files in my project, but added them back in as untracked. It also keeps deleting the currently open file from disk.

![Screen Shot 2019-06-19 at 1 05 16 PM](https://user-images.githubusercontent.com/11545939/59796699-eb2d3600-9292-11e9-8f94-3b44d671212a.png)

![Screen Shot 2019-06-19 at 1 07 26 PM](https://user-images.githubusercontent.com/11545939/59796840-35161c00-9293-11e9-8201-588a4e9dd5a4.png)

![Screen Shot 2019-06-19 at 1 07 06 PM](https://user-images.githubusercontent.com/11545939/59796841-35aeb280-9293-11e9-81b3-27774ccd6b7f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I'm pretty sure VS Code isn't doing this. Do you have any Git plugins, add-ons? Does the issue reproduce when you run those commands in a terminal, without using VS Code?

**Comment by juliancoleman** [comment]
It does not happen outside of VSCode for me. I thought it had something to do with the git history, but that doesn't seem to be it. This issue seems to be only present from within VSCode, primarily when Git runs its auto-fetches (which I have disabled and oddly still fetches)

**Comment by juliancoleman** [comment]
I should also note that this happens for literally one repository. It could be an issue with the `.git` folder entirely.

**Comment by joaomoreno** [comment]
Interesting. What if you clone that repo all over again to a new folder?

**Comment by juliancoleman** [comment]
@joaomoreno the funny thing is that I have done that and the issue still persists. I am not fully convinced that it's an issue with VSCode, but it's the only environment that it happens in.

**Comment by joaomoreno** [comment]
What git version do you have installed? Try updating to the latest.
