### ISSUE TITLE
Strange colors in terminal with canvas renderer

### ISSUE THREAD

**Issue by Steffan153** [microsoft/vscode#75791]
Issue Type: <b>Bug</b>

In the integrated terminal, there's a weird bug. After typing in some commands, strange color strikes appear like the screenshot below:

![Screenshot](https://i.imgur.com/a594vkB.png)

VS Code version: Code - OSS 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-14T21:57:30.073Z)
OS version: Linux x64 4.19.52-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T9550  @ 2.66GHz (2 x 2562)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|5.79GB (0.14GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
svelte-intellisense|ard|0.5.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
vscode-svelte-snippets|fiv|0.2.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-yarn|gam|1.6.0
svelte-vscode|Jam|0.9.1
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|2.4.0
node-module-intellisense|lei|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.0
debugger-for-chrome|msj|4.11.4
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
angular-console|nrw|8.0.5
vetur|oct|0.21.0
material-icon-theme|PKi|3.8.0
code-spell-checker|str|1.7.17

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Workaround is to move off the canvas renderer:

```
"terminal.integrated.rendererType": "dom"
```

Updating your graphics drivers might also help.

**Comment by Steffan153** [comment]
Thanks, that fixed it
