### ISSUE TITLE
File explorer has strange line covering certain icon themes.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#75794]
- VSCode Version: `1.36.0-insiders`
- OS Version: `5.1.11-arch1-1-ARCH GNU/Linux`

In my side file explorer, depending on the file icon theme I use there is this line that covers certain icons. It's not breaking but it's certainly annoying. This only started happening after the most recent insiders update.

## One of the many icon themes this does affect:
Icon theme: https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.vscode-simple-icons
![image](https://user-images.githubusercontent.com/31551546/59795347-060aa500-92a9-11e9-8ceb-8dd0b39b7bea.png)

## One of the few icon themes this doesn't affect:
Icon theme: https://marketplace.visualstudio.com/items?itemName=emmanuelbeziat.vscode-great-icons
![image](https://user-images.githubusercontent.com/31551546/59795670-bd9fb700-92a9-11e9-93e1-a91e83f76124.png)

It affects many icon packs that have worked in the past, and I haven't found any way to disable these folder lines

Steps to Reproduce:
1. Open a folder / workspace.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@sarahkittyy FYI those lines come from [this new feature](https://github.com/microsoft/vscode/issues/17777#issuecomment-503127937). As @usernamehw says, the overlap is a bug that's already been reported. See if the next Insiders build solves it for you.

**Comment by sarahkittyy** [comment]
Oh, great, thank you!
