### ISSUE TITLE
Intellisense picks Auto Import rather than local variables

### ISSUE THREAD

**Issue by ahmedHusseinF** [microsoft/vscode#75798]
Whenever I type `this.` it uses Auto Import instead of getting the local variable in the class.
The Auto Import is :
import { THIS_EXPR } from '@angular/compiler/src/output/output_ast';

What is that 🤔?

- VSCode Version: 1.35.1
- OS Version: Manjaro 18.0

Steps to Reproduce:
1. Need to have @angular/cli
2. run `ng new app`
3. try to type `this.` in any .ts component

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? I can't.

Also, can you share you user settings around suggestions? There are a few settings that can effect the ordering, such as `editor.suggestSelection`

**Comment by ahmedHusseinF** [comment]
Well I figured it out, after weeks of frustration.

there was this setting, I don't know how it got in there.
```json
"editor.suggest.filteredTypes": {
    "keyword": false
}
```
