### ISSUE TITLE
Paramter hints do not reappear on ,

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#758]
* Typescript - invoke a method - paramter hints show up
* If I trigger inteli-sense to fill in the first argument parameter hints will never show up again
* I would expect parameter hints to show up again once I do a **,** (comma)

This behavior makes parameter hints not very usable for me. Before it was behaving better.

**Comment by joaomoreno** [comment]
@jrieken @dbaeumer @alexandrudima What changed?

**Comment by jrieken** [comment]
unsure, will investigate
