### ISSUE TITLE
maven not found

### ISSUE THREAD

**Issue by iamthehousedog** [microsoft/vscode#75800]
Issue Type: <b>Bug</b>

selected maven archetype quickstart adn neither mvn nor maven is recognized - why?
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights rTry the new cross-platform PowerShell https://aka.ms/pscore6
PS C:\java\demo01\demo01> cd "c:\java\demo02"
PS C:\java\demo02> cmd /c mvn archetype:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetyhttps://github.com/password_reset/AB6AXGHERXKFDGEAQVXG7GC5BLXCJA5FMVWWC2LMXJUWC3LUNBSWQ33VONSWI33HIBUG65DNMFUWYLTDN5W2KZTPOJRWLQVTOR3W6X3GMFRXI33SL53GK4TJMZUWKZGCpes"'mvn' is not recognized as an internal or external command,operable program or batch file.PS C:\java\demo02> cmd /c maven archetype:generate -DarchetypeArtifactId="maven-archtype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes"
'maven' is not recognized as an internal or external command,
operable program or batch file.
PS C:\java\demo02> 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
scala-lsp|dra|0.2.3
vscode-sbt-scala|lig|0.2.4
powershell|ms-|2019.5.0
printcode|nob|3.0.0
java|red|0.46.0
scala|sca|0.3.2
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1

</details>

**Comment by sandy081** [comment]
Please file issue against the maven extension.
