### ISSUE TITLE
move buttom bar icon to the top, and make the extra icon a stack

### ISSUE THREAD

**Issue by kita32** [microsoft/vscode#75803]
Issue Type: <b>Feature Request</b>

due to most common monitor is a width-box, the vertical space is most treasure of all.

the buttom bar is not much useful, those icon and alert should merge into left and top
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
@kita32 Not sure if I understand your request. Can you please explain in detail about your requirement. Screenshot or a gif would be helpful too.
