### ISSUE TITLE
vscode 左侧显示异常

### ISSUE THREAD

**Issue by gongyuan303** [microsoft/vscode#75805]
vscode 左侧显示异常
![微信图片_20190620093906](https://user-images.githubusercontent.com/30801250/59812120-6ea46100-933f-11e9-985e-6e38e2e1b5c8.png)
如图 左侧显示异常，这块文件名称下面还会显示内容，不知道什么原因导致的，我把所有插件已经关闭依然存在这个问题

**Comment by byyxx128** [comment]
1. English please. All non-English issues will be closed directly.
（讲英文！）
2. Please describe clearly in English without nonsense.
（不要讲“不知道什么原因导致的”这种废话，都没法给你翻译……用英语自己重新开一个 issue 说清楚）

**Comment by sandy081** [comment]
Please file issue with proper summary, description and steps to reproduce in english.
