### ISSUE TITLE
用vscode写go代码，保存总是被撤销到原来文件的样子，修改的全没了

### ISSUE THREAD

**Issue by adolphus520** [microsoft/vscode#75809]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
1. English please. All non-English issues will be closed directly.
（讲英文！）
2. Please provide detailed steps to reproduce.
（不要标题党！这样连翻译都没法给你翻译。自己开新的 Issue 用英语说）

**Comment by sandy081** [comment]
Please file the issue with summary, description and steps to reproduce in english.
