### ISSUE TITLE
Please add find file function

### ISSUE THREAD

**Issue by kenshin1215** [microsoft/vscode#75806]
Version: 1.34.0
OS: window 10

Can you add function to find the file in visual code. Now can only search keyword which is in file, but sometime I only need to edit that file.Now I have to search in the left bar.

maybe let us can only type include file(For example, if I type nothing for the keyword but type ABCDE.c for include file, then I'll find  ABCDE.c)

**Comment by roblourens** [comment]
You can use ctrl+p for this

**Comment by kenshin1215** [comment]
ok,thank you,
it solve my problem
