### ISSUE TITLE
TypeScript: Curly braces in angle brackets breaks syntax highlighting

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#7581]
- VSCode Version: 1.3.0-insider (7d56f33e508930d3727064481a7525344a227f10)
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Enter following code (from https://github.com/aspnet/JavaScriptServices/blob/master/templates/ReactReduxSpa/ClientApp/components/Counter.tsx):
```typescript
const provider = provide(
  (state: ApplicationState) => state.weatherForecasts, // Select which part of global state maps to this component
  WeatherForecastsState.actionCreators                 // Select which action creators should be exposed to this component
).withExternalProps<{ params: RouteParams }>();          // Also include a 'params' property on WeatherForecastProps
type WeatherForecastProps = typeof provider.allProps;
export default provider.connect(FetchData);
```
2. See that syntax highlighting stops working after `<{ params: RouteParams }>()`:
![image](https://cloud.githubusercontent.com/assets/594564/15991011/9fbc26d8-30a5-11e6-9472-afab8e3724ec.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#184
