### ISSUE TITLE
Autocompletion fails to input selection frequently 

### ISSUE THREAD

**Issue by tangyanhan** [microsoft/vscode#75814]
My VSCode fails to input the selected code after selecting one of the items in autocompletion list. 
E.g. With an Go object resp, I typed "resp.", then a list of methods appeared, I selected one method by pressing Enter,  made a mouse click, typed the full name of the method, and none of theses works - it simply turned back to the time when I typed "resp.", as if nothing ever happened. When this occur it's 100 percent to reproduce, and turns normal occansionaly.

Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.9-301.fc30.x86_64   (Fedora30)
Desktop: KDE5

**Comment by carloslahrssen** [comment]
Hey! I'm assuming that you're using the ms-vscode.go extension correct? This looks to me that it's more of an issue with the Go intellisense extension than it is with VSCode core itself. Could you try reproducing the same autocomplete issue with an other language extensions such as ms-python.python or ms-vscode.cpptools etc...

**Comment by tangyanhan** [comment]
@carloslahrssen Thanks for your support! 
For anyone may need it: It's probably an issue with vscode-go and I found a solution here: https://github.com/microsoft/vscode-go/issues/2575
By setting "go.useLanguageServer" to false, everything seems fine again
