### ISSUE TITLE
Icon of the CodeHelper.exe needs updating.

### ISSUE THREAD

**Issue by g-plane** [microsoft/vscode#75817]
- VSCode Version: 1.35.1
- OS Version: Windows 10

Icon of the `CodeHelper.exe` on Windows haven't been updated:

![图片](https://user-images.githubusercontent.com/17216317/59826740-75e06480-9369-11e9-8ffd-11d5a4604056.png)

Does this issue occur when all extensions are disabled?: Not related.

**Comment by g-plane** [comment]
Lack of responses and this isn't a vital issue. Closing.

**Comment by misolori** [comment]
@g-plane we're working on updating this ;)

**Comment by misolori** [comment]
thank you @joaomoreno ❤️
