### ISSUE TITLE
Terminal - New Terminal -> The terminal process command '/bin/login_script.sh -l' failed to launch (exit code: 1)

### ISSUE THREAD

**Issue by MrQ-Android** [microsoft/vscode#75813]
Issue Type: <b>Bug</b>

Terminal - New Terminal -> The terminal process command '/bin/login_script.sh -l' failed to launch (exit code: 1)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875

</details>

**Comment by Tyriar** [comment]
This means that `/bin/login_script.sh` exited with a code of 1, you should investigate that yourself as I don't know what your login script does.
