### ISSUE TITLE
VS Code takes 100% CPU

### ISSUE THREAD

**Issue by GDCPedro** [microsoft/vscode#75812]
- VSCode Version: 1.35.1
- OS Version: win10 64bit 17134.829

Steps to Reproduce:

1. Dell Inspron 14, win10 64bit
2. open VS Code

Does this issue occur when all extensions are disabled?: Yes/No
Yes. Eventhough setting "search.followSymlinks": false. And VS Code no longer gives code suggestions while coding.

**Comment by roblourens** [comment]
What steps exactly do you take before you see it using lots of CPU? Can you show what's in the process explorer (under help menu) so we can see which process it is?

**Comment by GDCPedro** [comment]
![vscodeIssue](https://user-images.githubusercontent.com/36934222/59895382-f5783d00-9416-11e9-8262-f3f2a310ba5f.png)
Or MAYBE Vue.js made this?
I just tap abc on VS code in my VUE.js project,. I figure out sth in win10 system process manager that the VS code and powerShell take a share over 50%.  But one month ago everything went well, maybe some update caused this? :) Thanks friend.

**Comment by roblourens** [comment]
Yeah looks like Vue is using a lot of CPU. If that's always the only process using lots of CPU then maybe you can find help on the Vue extension repo.
