### ISSUE TITLE
missin `]' on line 14

### ISSUE THREAD

**Issue by mycroft16** [microsoft/vscode#75820]
Issue Type: <b>Bug</b>

When launching code-insiders . from any location, the following error warning appears on the screen:
/mnt/c/Users/Alisha Morgan/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders: line 14: [: missing `]'

VS Code Insiders launches and appears to work just fine, but that warning always shows.

VS Code version: Code - Insiders 1.36.0-insider (c3fe2d8acde04e579880413ae4622a1f551efdcc, 2019-06-20T05:20:10.276Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.18GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+default/mnt/d/Projects/Code/Angular/one-equality --remote=wsl+default|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2301)|
|Memory (System)|7.87GB (1.18GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2301)|
|Memory (System)|7.87GB (1.18GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
gitkraken-glo|axo|1.1.0
vscode-typescript-tslint-plugin|ms-|1.2.0
ftp-kr|rua|1.3.16
code-spell-checker|str|1.7.17

</details>

**Comment by bpasero** [comment]
Sounds like an issue with our startup scripts to me.

**Comment by joaomoreno** [comment]
@mycroft16 Can you paste here the full contents of `/mnt/c/Users/Alisha Morgan/AppData/Local/Programs/Microsoft VS Code Insiders/bin/code-insiders`?

**Comment by mycroft16** [comment]
Whatever it was, the latest version that just installed has fixed the problem. I am no longer seeing that issue on startup.
