### ISSUE TITLE
Extra spaces inside template strings on paste

### ISSUE THREAD

**Issue by Skriptach** [microsoft/vscode#75821]
Issue Type: <b>Bug</b>

When paste piece of code containing ES6 template string VS Code add extra spces inside them. For example for this one ``this.classList.add(`prefix-${newVal}`);``

expected to be:
```
this.classList.add(`prefix-${newVal}`);
```

instead get:
```
this.classList.add(`prefix - ${ newVal }`);
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.51GB (4.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-schematics|cyr|1.23.0
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
vscode-diff|fab|1.4.0
Angular2|joh|8.1.1
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
Go|ms-|0.11.0
sublime-keybindings|ms-|4.0.0
prettier-now|rem|1.4.9
partial-diff|ryu|1.4.0
markdown-preview-enhanced|shd|0.4.1

</details>

**Comment by sandy081** [comment]
@Skriptach Looks like it is getting format on paste. You can disable that setting if wanted. `editor.formatOnPaste`.

**Comment by Skriptach** [comment]
Closed? WTF?!
@sandy081, I do want keep format. But format correctly!

**Comment by sandy081** [comment]
@Skriptach May I know which formatter you are using to format this?
Please disable all installed extensions and check if it is caused by VS Code or an external extension.

**Comment by Skriptach** [comment]
@sandy081 
I have disabled all extensions, reload VS Code and bug was reproduced

**Comment by mjbvz** [comment]
I can't repo this in a clean VS Code insiders instance with no settings. Also, please share the complete source of where you are pasting

**Comment by Skriptach** [comment]
Hi @mjbvz 
Turns out it depends on ES6 private field usage.
It reproduces if insert after line containing # char. And not if before

```javascript
class Some {
	#type = null;

	set name (newVal) {
		
		// ^ not reproduced here
		this.classList.remove(`st-${this.#type}`);

		/* could be some other code */

		
		// ^ insert here 
	}
}
```

**Comment by mjbvz** [comment]
We don't support private fields yet and can't parse files that use them properly. This is tracked by https://github.com/microsoft/TypeScript/issues/9950
