### ISSUE TITLE
sql highligher is confused by `comment ON CONSTRAINT "email is`

### ISSUE THREAD

**Issue by matjojo** [microsoft/vscode#75823]
Issue Type: <b>Bug</b>

 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
love|bsc|0.3.6
vscode-autohotkey|sle|0.2.2
lua|sum|0.9.12

</details>

Steps to Reproduce:

1. Make an sql file.
2. Insert this text: `COMMENT ON CONSTRAINT "email is unique" ON public.users
    IS 'snip';`
3. See that the first " character is ignored, and that the ending of the file is styled as if it's a comment.

I first noticed this in a way larger sql file, and this is as small as I could get the string where the issue still occurs and is visible.

Does this issue occur when all extensions are disabled?: Yes

Restarting code also does not fix this.

Image of the issue: [https://i.imgur.com/dGRragH.png](https://i.imgur.com/dGRragH.png)

When you remove is from the part of the string that should highlighted as string it get's even weirder. And the formatter seems to ignore two quote characters.

[https://i.imgur.com/JmwowhK.png](https://i.imgur.com/JmwowhK.png)

**Comment by alexr00** [comment]
Moved to owning repo.
