### ISSUE TITLE
Terminal dom renderer doesn't render `dimmed` colors

### ISSUE THREAD

**Issue by timsuchanek** [microsoft/vscode#75827]
- VSCode Version: Version 1.35.1 (1.35.1)
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open terminal in VSCode and run `npx dim-cli` - it prints `Hello World` with `World` dimmed
2. Change the "Integrated: Renderer Type" to `dom` - `World` is no longer dimmed.

## Canvas Renderer
![image](https://user-images.githubusercontent.com/1094804/59837583-c2b64200-934d-11e9-8125-49bdcfe31ba3.png)

## Dom Renderer
![image](https://user-images.githubusercontent.com/1094804/59837695-f2fde080-934d-11e9-928d-13a943e49ab3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is already done, we just need to update a css file.

To verify:

```
echo -e 'abc\x1b[2mdef'
```

**Comment by alexr00** [comment]
@Tyriar is this intended to be non-Windows only? I have verified on Ubuntu, but the dimming never works on Windows in the integrated terminal.

**Comment by Tyriar** [comment]
@alexr00 it's easier to test these on non-Windows as support can depend on the shell and the pty backend. Normally you can test these types of issues on conpty and wsl but things can still possibly go wrong (for example conpty doesn't print black background correctly).
