### ISSUE TITLE
File service: unable to move/copy same path

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75825]
1. Linux
2. Trigger rename a file in the explorer
3. Click anywhere else while the rename box is shown. Notice error in the console

`Unable to move/copy when source path is equal or parent of target path: Error: Unable to move/copy when source path is equal or parent of target path`
The issue is that the explorer calls `textFileService.move(stat.resource, targetResource)` where both resources are the same.
The fileService treats this as a no-op on OS X and Win. But throws on linux.

@bpasero What is the proper behavior, that it is always a no-op, or you always throw so I put a check in the action.

fyi @joaomoreno

**Comment by bpasero** [comment]
@isidorn wanna do this? I think it is somewhere here:

https://github.com/microsoft/vscode/blob/d813315714aad6390f59cc6a10458d19267d4001/src/vs/workbench/services/files/common/fileService.ts#L645

**Comment by isidorn** [comment]
Yeah. I will look into this. Thanks for pointer.

**Comment by isidorn** [comment]
Decided to fix this on the explorer side - felt more natural there.
I simply do not call into your service when the resources are the same
