### ISSUE TITLE
New Mac native tab resizes window

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#75830]
In current insiders when I `Cmd+Shift+N` in a maximized window with Mac native tabs enabled, the window resizes.

**Comment by bpasero** [comment]
@chrmarti couple of questions since I do not see an issue:
* are you using multiple monitors or just one
* is the new window opening as a native tab or separate window?

**Comment by chrmarti** [comment]
I use 2 monitors with VS Code confined to the primary one. The session opens as native tab on the only open VS Code window. Swing by if you want a demo. :)

**Comment by bpasero** [comment]
A regression from the workaround of https://github.com/microsoft/vscode/issues/74872

**Comment by bpasero** [comment]
The workaround for https://github.com/microsoft/vscode/issues/74872 will no longer apply when native tabs are enabled.
