### ISSUE TITLE
Can't go to parent directory in Breadcrumbs

### ISSUE THREAD

**Issue by b1zzu** [microsoft/vscode#75837]
- VSCode Version: 1.35.1
- OS Version: Fedora 30

Steps to Reproduce:

1. Open .html file in some subdirectories
2. `Focus Breadcrumbs`
3. Press left arrow a few times and it will not be possible to navigate to a parent directory or to siblings file but only inside the tree of tags of the current file.

![image](https://user-images.githubusercontent.com/7964685/59848596-d79ecf80-9365-11e9-8819-791740bdeea2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
#75564
