### ISSUE TITLE
ALT + Z malfunction

### ISSUE THREAD

**Issue by emmajiugo** [microsoft/vscode#75833]
We have written the needed data into your clipboard because it was too large to send. Please paste.Hi.
After updating the vscode to the latest version, I discover that the ALT + Z for word wrapping doesn't work again.
Please look into it.

**Comment by rebornix** [comment]
@emmajiugo could you please share more information about the platform, OS version, VS Code version, etc to help troubleshoot?

BTW, can you go to keybindings editor and search for alt + z and share the result as well?
