### ISSUE TITLE
Explorer Window Visually difficult to read

### ISSUE THREAD

**Issue by stuartsfleming** [microsoft/vscode#75838]
Issue Type: <b>Feature Request</b>

Hi.  The explorer window has several problems:
1,  The main directories should be in larger font and bold face.
2.  The tree-like structure should have larger indents.  It is almost impossible to see the difference between a main folder and the components underneath it.

Indent Indent Indent!  or at least have big icons to identify a directory vs a file

Have a nice day!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Re item 2, use the `workbench.tree.indent` setting.

You can look forward to the next release, which adds the option of indent lines. See [#17777](https://github.com/microsoft/vscode/issues/17777#issuecomment-503127937). It's already available if you install Insiders.

**Comment by sandy081** [comment]
Yes, Indentations are available in insiders build please try. https://code.visualstudio.com/insiders/

Assigning to @isidorn for your first requirement

**Comment by isidorn** [comment]
Leaving open as a feature request Assinging to backlog as we have no plans to tackle 1. in the near future.

**Comment by iheartjoo** [comment]
This issue jumped out at me immediately upon installing VS Code. A right-in-your-face UX issue. Seems worth a little investment to offer an immediate improvement in QoL.
