### ISSUE TITLE
Button to scroll to file in sidebar (like IntelliJ crosshair)

### ISSUE THREAD

**Issue by lucavallin** [microsoft/vscode#75836]
Hello, searched for open feature requests but couldn't find this one.
I'd like to have a button like the crosshair one in the IntelliJ IDE that when clicked, scrolls the sidebar to the file you have opened in the editor.
I find it very useful when you want to have an idea of where the file is, what is around it etc... especially when searching for something I am not sure about.
The breadcrumbs don't do it for me, the view is too restricted.

**Comment by roblourens** [comment]
The explorer does this by default when you open a file. You can also use the command "Reveal Active File In Sidebar"
