### ISSUE TITLE
Screen cheese with "Open file" icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#75831]
* open SCM viewlet
* hover over a change

<img width="174" alt="Screenshot 2019-06-20 at 11 36 27" src="https://user-images.githubusercontent.com/1794099/59838699-aadfbd80-934f-11e9-9eb5-13963ff1b78a.png">

**Comment by misolori** [comment]
Sorry about that, fixed the screen 🧀 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/35271042/59859934-8b866780-9332-11e9-82ba-37107ba98a56.png">
