### ISSUE TITLE
GUI stuck and beachball spinning on Mac Mojave

### ISSUE THREAD

**Issue by aquaglia** [microsoft/vscode#75832]
Mojave 10.14.5
Vs Code: 1.35

Cannot open a new instance because
"Another instance of Code is running but not responding"

Can't kill the process

aqserver:git Angelo$ ps -ef | grep "Visual Studio"
  501 33572     1   0 10:13AM ??         0:53.59 /private/var/folders/ft/rvvvs61n2tb942d3j7r3mf7r0000gn/T/AppTranslocation/4156E934-76B3-40A5-A816-DA4A37BFCA40/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4510797
  501 36239     1   0 11:51AM ??         0:01.58 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  501 36321   540   0 11:55AM ttys001    0:00.00 grep Visual Studio
aqserver:git Angelo$ kill -9 36239
aqserver:git Angelo$ kill -9 33572
aqserver:git Angelo$ ps -ef | grep "Visual Studio"
  501 33572     1   0 10:13AM ??         0:53.59 /private/var/folders/ft/rvvvs61n2tb942d3j7r3mf7r0000gn/T/AppTranslocation/4156E934-76B3-40A5-A816-DA4A37BFCA40/d/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_4510797
  501 36332   540   0 11:55AM ttys001    0:00.00 grep Visual Studio
aqserver:git Angelo$

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
