### ISSUE TITLE
High usage of computer memory

### ISSUE THREAD

**Issue by hsamfm** [microsoft/vscode#75839]

**Comment by sandy081** [comment]
Can you please provide necessary information to diagnose the issue. If it is performance related please follow this wiki https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by hsamfm** [comment]
Thank You!

**Comment by sandy081** [comment]
Can you please provide necessary information to diagnose the issue. If it is performance related please follow this wiki microsoft/vscode/wiki/Performance-Issues
