### ISSUE TITLE
Git commit message length warning for description

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#75845]
- VSCode Version: 1.35.1
- OS Version: macOS

<img width="452" alt="Screen Shot 2019-06-20 at 17 33 50" src="https://user-images.githubusercontent.com/10441177/59857461-b055fb80-9381-11e9-9358-1140d9fa34ac.png">

As you can see if I add description after commit title it should stop counting characters since I can use as much as I want, but instead, it checks it as it does with the commit title. The validation should be disabled after a new line.

**Comment by svipas** [comment]
I found the file which validates: https://github.com/microsoft/vscode/blob/997e91421e9490a11ff3b69dd285b2c175efbe46/extensions/git/src/repository.ts#L668. I can try to make a PR if needed.

**Comment by yume-chan** [comment]
The length of first commit message line is limited by `git.inputValidationSubjectLength` setting and from second line the length is limited by `git.inputValidationLength` setting.

Can't you just set `git.inputValidationSubjectLength` to 72 and `git.inputValidationLength` to a huge number so it doesn't care about what you have inputted?

**Comment by svipas** [comment]
I'm closing it because seems it's some sort of git good practice to have 50/72. Thanks, @yume-chan didn't know about these settings.
