### ISSUE TITLE
VSCode accessibility overview

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#75840]
I have gone through all our accessibility issues, and here are my findings:
* All accessibility issues are now tagged with label [`accessibility`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility) for a total of 55 issues
* To not get downgraded to score D for Microsoft accessibility the issues tagged with [`a11ymas`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aa11ymas) have to be fixed.
* Interestengly all of the `a11ymas` have no user interaction on them. None of them have a thumbs up or a comment from a user (unlike our other accessiblity issues which have lively discussions). This and my own analysis of these issues leads me to believe that they are not as important as our user created issues.
* There are around [10 actionable issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=label%3Aaccessibility+milestone%3A%22July+2019%22+is%3Aopen+), for those I have pinged the owners to provide code pointers so the author, the community or me provide PRs to fix
* There are 2 issues which are a big pain for accessibility users tagged with [`important`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+label%3Aimportant). They are both upstream, but we should put our focus on getting those fixed (by communicating with Chrome and NVDA).
* We have a total of 12 [`upstream`](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aaccessibility+label%3Aupstream+) most of them relying on Chrome
* Since we upgraded to Electron 4.0 I could close off around 5 issues which got fixed because Electron picked up a newer Chrome version. So this is another benefit of keeping up with Electron updates.
* Writing new widgets with accessibility in mind helps a lot. A good example is the new tree for which there were not that many accessibility issues - even though we use it across the workbench

@egamma @chrisdias  Could you please give me the contact of Edge / Chromium contributors that could help us with solving chrome accessibility issues. One example: https://bugs.chromium.org/p/chromium/issues/detail?id=951777

fyi @auchenberg @deepak1556 @kieferrm 

fyi @neurrone @pawelurbanski @adincebic for more potential feedback, or if I missed something in my overview

Let me know what you think. Thanks

**Comment by Neurrone** [comment]
@isidorn thanks for organizing this information. Looking at the a11ymas issues, most of them don't seem to be that critical, compared to many of the issues opened by end users, so I also feel that prioritizing the latter would be more impactful.

**Comment by pawelurbanski** [comment]
Just a quick update… Unfortunately, I cannot get through the initial Yarn package compilation. There is an issue with the postinstall.js script reported by someone on Github.
It stops me from compilation, and working on the fixes locally.

**Comment by isidorn** [comment]
This milestone we have tackled actionable accessibility issues as seen in this [query](https://github.com/microsoft/vscode/issues?q=milestone%3A%22July+2019%22+label%3Aaccessibility+is%3Aclosed)

We have also setup a meeting with the Edge team so we start discussing Chrome accessibility issues.
We can keep this overview around, but we have done what we planned for this milestone, thus removing the milestone from it.

**Comment by Neurrone** [comment]
The last big-ish issue for me on a daily basis is that NVDA disagrees with Code about what a word is, so moving by word never provides accurate feedback, tracked in #28306. Not sure if the work being done to add UIA support in Chromium would help, in this case.

**Comment by isidorn** [comment]
Planned items from this issue have been tackled. We are continuing our work on accessibility, however that is captured in other issues. Thus closing this.
