### ISSUE TITLE
Error: [js] property type declarations can only be used in a 'ts' file.

### ISSUE THREAD

**Issue by jaqmol** [Microsoft/vscode#7584]
- VSCode Version: 1.2.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Create a React component as a class, like:
`
class CommentList extends React.Component {
  render() {
    ...
  }
}
`
2. Add a static propType property, like:
`
class CommentList extends React.Component {
  static propTypes = {
    data: PropTypes.array.isRequired
  };
  render() {
    ...
  }
}
`
3. VSC underlines the static propTypes declaration as being an error with `[js] property type declarations can only be used in a 'ts' file.`. Despite there being no problem at all compiling the code with Babel.

**Comment by dbaeumer** [comment]
JS language server is maintained by the TS team. Moving...

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9121
