### ISSUE TITLE
Setting to render active line number

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#75844]
Currently, we have `editor.renderLineHighlight` which is useful if you want to show or hide the current line highlight. But there's no setting for the active line number, you need manually check the theme's `editorLineNumber.foreground` and use it in `workbench.colorCustomizations`. The new setting could be `editor.renderActiveLineNumber` or something like that.

**Comment by svipas** [comment]
I found the file where setting should be introduced, if needed I can create a PR.

https://github.com/microsoft/vscode/blob/013501950e78b9dde5c2e6ec3f2ddfb9201156b7/src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.ts

**Comment by rebornix** [comment]
@svipas are you asking for changing the color for active line number?

**Comment by svipas** [comment]
@rebornix Sorry for not being very clear. I'm asking for config to show active line number or no. Currently, we can show/hide currently active line, but there's no setting for active line number we need to do it manually by editing color scheme.

`"editor.renderLineHighlight": "none",` it would be like this setting but only for active line number since some of us want to disable highlight.

**Comment by rebornix** [comment]
if I understand correctly, you want to disable active line number highlight, right? Just to double confirm.

**Comment by svipas** [comment]
@rebornix Yes, but without editing the color scheme, instead it would be cool to have a setting like `editor.renderLineHighlight` for line highlight. If it sounds right I can create a PR.
