### ISSUE TITLE
npm scripts explorer not using current node

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#75849]
Issue Type: <b>Bug</b>

I just updated from Node 10.1.0 to 10.16.0 to be able to run Angular 8 CLI.  

When I run `npm start` in the Mac Terminal, the project works.

When I run `npm start` in the VScode Terminal, the project works.

When I click "start" in the "npm scripts" script explorer, I get the error:
```
You are running version v10.1.0 of Node.js, which is not supported by Angular CLI 8.0+.
The official Node.js version that is supported is 10.9 or greater.
```

I mean clicking this, the script explorer enabled in preferences:

<img width="419" alt="Screen Shot 2019-06-20 at 11 23 53 AM" src="https://user-images.githubusercontent.com/835148/59861046-1759bd00-934e-11e9-8b8d-7e1246bb18f7.png">

VS Code version: Code - Insiders 1.36.0-insider (c3fe2d8acde04e579880413ae4622a1f551efdcc, 2019-06-20T05:19:11.382Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
project-manager|ale|10.5.2
bracket-pair-colorizer|Coe|1.0.61
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.9.0
vsc-material-theme-icons|equ|1.0.6
prettier-vscode|esb|1.9.0
path-autocomplete|ion|1.13.3
svg|joc|0.1.5
theme-karyfoundation-themes|kar|18.2.1
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.13
vscode-scss|mrm|0.6.2
vscode-typescript-tslint-plugin|ms-|1.2.0
debugger-for-chrome|msj|4.11.4
angular2-inline|nat|0.0.17
incrementor|nms|0.1.0
angular-component-extension|oni|0.0.14
vscode-html-scss|P-d|0.0.42
vscode-versionlens|pfl|0.23.0
material-icon-theme|PKi|3.8.0
polacode|pnp|0.3.2
seti-icons|qin|0.1.3
quicktype|qui|12.0.46
code-settings-sync|Sha|3.2.9
stylelint|shi|0.51.0
vscode-scss-formatter|sib|1.4.1
rewrap|stk|1.9.1
ayu|tea|0.18.0
sort-lines|Tyr|1.8.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.4.0

(5 theme extensions excluded)

</details>

**Comment by egamma** [comment]
Does this still happen once you restarted VS Code?

The npm extension shells out to run an npm script, this means npm is run in the process environment of VS Code.

**Comment by smlombardi** [comment]
I  discovered that NVM was using 10.1.0 as default, so all new terminals went back to it.  I ran `nvm alias default 10.16.0` and restarted VSCode, works now.
