### ISSUE TITLE
URIs ending with / should not enter system

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#75847]
E.g., when opening a folder with a trailing / the recent list doesn't render properly:
![image](https://user-images.githubusercontent.com/9205389/59859306-c7461f00-937c-11e9-82c3-ab1df401d49f.png)

The simple file picker happens to pass in trailing /, but this can also be triggered through the CLI. (Also reproduced in 1.35.)

/cc @isidorn @bpasero @alexr00

**Comment by isidorn** [comment]
The workspaceContextService should "normalize" all workspace URI's that end with a `/`
@sandy081 @bpasero If this is not feasable or you think not a good idea, let me know and I can fix the display of these in the `labelService`. Though I think a better solution would be too prevent uris like these ending in our system.

**Comment by alexr00** [comment]
I made a change to remove the trailing path separator from URIs from the file picker.

**Comment by isidorn** [comment]
That should fix @chrmarti problem. But in theory this could also end in our system from the command line. So let's see what @sandy081 has to say

**Comment by bpasero** [comment]
Yes we need to sanitize. We already have [`sanitizeFilePath`](https://github.com/Microsoft/vscode/blob/6a7020dd4a11e0f33b157b3df4baeec90d85701b/src/vs/base/common/extpath.ts#L235) for exactly that purpose but I think it is probably not being used if a URI is passed in (e.g. for remote).

**Comment by sandy081** [comment]
Yes, we should sanitise and normalise the URIs that are entering the system.

**Comment by sandy081** [comment]
We already prevent such URIs (with trailing slashes) that comes through command line. Hence closing this.
