### ISSUE TITLE
vscode-node-debug assumes debug port open when --inspect-port is used for "attach to process"

### ISSUE THREAD

**Issue by philz** [microsoft/vscode#75852]
[https://github.com/microsoft/vscode-node-debug says to file issues in this repo]

If you run a node process with `node --inspect-port=1234 sleep-forever.js`, the VSCode `${command:PickProcess}` command picker suggests to connect to the process using port 1234.

![image](https://user-images.githubusercontent.com/60228/59865012-e0c77680-933c-11e9-956f-5047acf28821.png)

However, because `--inspect` wasn't specified, the port isn't opened until a `kill -USR1 <pid>` is issued, so the picker doesn't work. A workaround is to kill the process.

I suspect the issue is at https://github.com/microsoft/vscode-node-debug/blob/56dc3892885b3122385b785322b00a92d33fdded/src/node/extension/protocolDetection.ts#L233 where the regexp looking for `--inspect` is finding `--inspect-port` and assuming debugging is already "open."

In my environment, I'm trying to setup distinct, different ports for my different node processes so that multiple can be debugged simultaneously, so I'm using `--inspect-port` to facilitate that, but I don't wish to have the debugging enabled by default. (I'm starting the processes outside of VSCode at the moment.)

Note that if the node process updates `process.title` this picker fails in other interesting ways, but that's much more of an edge case.

This issue is similar to https://github.com/microsoft/vscode/issues/46664 but I think a slightly different workflow.

- VSCode Version: 1.35.1 
- OS Version: Mac OS 10.14.5 

Steps to Reproduce:

0. Install vscode-node-debug
1. Start a node process with `--inspect-port`
2. Create a debug configuration following "Attach to Process"
3. Try to attach; observe that it tries to connect using the port rather than SIGUSR1.

Does this issue occur when all extensions are disabled?: n/a

**Comment by weinand** [comment]
command line option "--inspect-port" is not yet supported.

**Comment by weinand** [comment]
Since we have a [new debugger](https://github.com/microsoft/vscode-js-debug/), please let us know if you're still running into problems, and if so open an issue on that repo.
