### ISSUE TITLE
Right Click Menu is blank

### ISSUE THREAD

**Issue by thommi1609** [microsoft/vscode#75851]
Hey.

I'm using VS Code on a virtual machine with Linux 16.04
When right clicking, the popUp menu is blank. However, all the items are still clickable.
That's why I'm thinkingthe background/foreground color is off somehow. 
When changing the color theme, the menu will appear normally on the **first** right click, but then is blank again. 
Has anyone experienced this before and might know how to fix it?

So far i tried:
1. Changing the color Theme
2. Disabling Extensions
3. Reinstalling VS Code
4. Overwriting color settings in settings.jason

- VSCode Version: 1.35
- OS Version: Ubuntu 16.04

![Version](https://user-images.githubusercontent.com/34045629/59865316-04b0a980-9389-11e9-8880-4be43d82ce8b.PNG)
![right_click_menu](https://user-images.githubusercontent.com/34045629/59865321-09755d80-9389-11e9-9e59-f4b126485e57.PNG)

**Comment by thommi1609** [comment]
Alright, i found a solution that works for me. In preferences, i set the titlebarstyle to custom.
Switching back to native i still have the issue, so i'll keep it like this for now.

Note:
English isn't my first language, and not knowing that the "right click menu" is called context menu made this harder to google.

**Comment by sbatten** [comment]
fyi @joaomoreno snap-related
