### ISSUE TITLE
Unexpected [ts] errors in JavaScript files. The errors and warnings cannot be disabled for Typescript while being preserved for Javascript.

### ISSUE THREAD

**Issue by mehas** [microsoft/vscode#75858]
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Create `babel.config.js`
2. Enter:

```
const presets = [`@babel/preset-env`, `@babel/preset-react`]

module.exports = { presets }
```

3. Observe the `m` in `module` is highlighted with a warning:

>File is a CommonJS module; it may be converted to an ES6 module.ts(80001)

Does this issue occur when all extensions are disabled?: Yes

Current user settings:

* `"tslint.enable": false`
* `"tslint.jsEnable": false`

**Workarounds:**

Setting `javascript.validate.enable` to `false` removes the Typescript validation from my file (which is not Typescript) *and all Javascript validation*. 

Setting `javascript.suggestionActions.enabled` to `false` disables suggestion actions for Typescript, *and all suggestions for Javascript* (which I want).

Is there a `TYPESCRIPT.suggestionActions.enabled` option?

How do I keep JS validation and fix the bug where VS Code is TSLint-ing files that aren't TS?

**Comment by mjbvz** [comment]
The `...` just indicates an available suggestion for a code action. Set `"javascript.suggestionActions.enabled": false` to disable these

**Comment by mehas** [comment]
@mjbvz Thanks, but I don't want to disable Javascript suggestions. I would like to disable *Typescript* suggestions. Is this possible?

**Comment by wangchou** [comment]
@mehas Typescript team don't like to fix this.
https://github.com/microsoft/TypeScript/issues/32148

**Comment by mehas** [comment]
@wangchou Both tickets were closed :(
