### ISSUE TITLE
Custom Dialogs 

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75856]
Issue Type: <b>Bug</b>

It appears that custom dialogs are on by default and unable to be turned off.
1. Edit a file 
2. Close without saving

The popup will be a custom dialog and not the native one, setting `"workbench.dialogs.customEnabled"` to false also doesn't work. 

VS Code version: Code - Insiders 1.36.0-insider (c3fe2d8acde04e579880413ae4622a1f551efdcc, 2019-06-20T05:19:11.382Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
@bpasero looks like DialogService was being double registered with browser and native versions.
