### ISSUE TITLE
Documentation: CompletionItem - editText vs insertText

### ISSUE THREAD

**Issue by thesmallbang** [microsoft/vscode#75859]
The documentation on the website  says 

https://code.visualstudio.com/api/references/vscode-api#CompletionItem.editText
https://code.visualstudio.com/api/references/vscode-api#CompletionItem.insertText

textEdit?:  depreciated - Use CompleteionItem.insertText and CompletionItem.range

Based on this information I went to look at using insertText. In VSCode when you attempt to use insertText you get some intellisense saying that insertText is "depreciated use editText instead."

Which is correct?

**Comment by jrieken** [comment]
That's not correct, `editText` doesn't exist at all. You likely meant `textEdit`. This is the docs that we have written and that the tooling shows:

* `textEdit`: https://github.com/microsoft/vscode/blob/e4ca6137b4aeae9d9e5fe719bfd117d13bcfa634/src/vs/vscode.d.ts#L3382-L3392

* `insertText`: https://github.com/microsoft/vscode/blob/e4ca6137b4aeae9d9e5fe719bfd117d13bcfa634/src/vs/vscode.d.ts#L3350-L3355

**Comment by thesmallbang** [comment]
Sorry. You are correct the incorrect depreciated comment is coming from the vscode-languageserver-types module .  I'll open this ticket there.
