### ISSUE TITLE
Large JS files cause endless Grammar Loop errors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75857]
Issue Type: <b>Bug</b>

If you open a large Javascript file, more noticeable on minified ones and have the developer console opened you get flooded with `Grammar is in an endless loop`errors. 
1. Open dev tools
2. Open a large minified file (I just chose the main.js packaged with vs code

VS Code version: Code - Insiders 1.36.0-insider (c3fe2d8acde04e579880413ae4622a1f551efdcc, 2019-06-20T05:19:11.382Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Can you please share a link the file or preferably a minimal repo? Also was this causing any issues beyond the logs?

**Comment by lramos15** [comment]
Here's a repo containing just one JS file from the VS Code packaged application for Mac. It causes tons of grammar errors when opening. I don't think it causes any issues beyond the logs and it just appears the errors happen during the loading of the large file

**Comment by mjbvz** [comment]
I'm going to close this as out of scope

I know that don't always parse minified files properly but the cost of fixing such issues is often not worth the payoff. If there's a minimal example that cause incorrect syntax highlighting in the editor, please share it
