### ISSUE TITLE
Search by data type of search term

### ISSUE THREAD

**Issue by philosophercode** [microsoft/vscode#75850]
I would like to be able to search by data type. In addition to finding a search term across project files, it would be helpful to narrow a **search by Type (e.g., 1000 vs “1000” or search for- 1000: string vs. 1000: int/number)**. The search would then filter the search by the type too and not only the term or regex.

Maybe an additional field for data Type or Class Type would be helpful.

**Comment by roblourens** [comment]
This is a popular suggestion but isn't really practical for us right now.

**Comment by philosophercode** [comment]
Thanks for reviewing.

The feature would definitely make the search/find far more efficient in my experience, and others it seems as it is a popular suggestion. It would also encourage use of typing and typescript, similarly tagging content ease the use of a platform. I would appreciate reconsideration or research of implementation.

I will look into the findContoller and see if there is an easy was to integrate the feature.

https://github.com/microsoft/vscode/blob/9bd21e3f2b406ca2f5c4f47e45514ceb803872ac/src/vs/editor/contrib/find/findController.ts
