### ISSUE TITLE
code --wait --diff doesn't exit after closing diff if the file is also opened in a non-diff view

### ISSUE THREAD

**Issue by garymm** [microsoft/vscode#75861]
Issue Type: <b>Bug</b>

I have vscode configured as my difftool with this my git config:
```
[diff]
    tool = vscode
[difftool]
	prompt = false
[difftool "vscode"]
    cmd = code --wait --diff $LOCAL $REMOTE
```

This case works correctly:

1. Start with no open files, and with an unstaged commit to a local file (e.g. foo.txt)
2. In the integrated terminal, run `git diftool foo.txt`
3. The diff shows up as a new tab
4. Close the tab
5. `git difftool foo.txt` exits

This case does not work correctly:

1. Start with foo.txt open, and with an unstaged commit to foo.txt
2. In the integrated terminal, run `git diftool foo.txt`
3. The diff shows up as a new tab
4. Close the tab that shows the diff
5. `git difftool foo.txt` does not exit
6. Close the other tab that has foo.txt
7. Now `git difftool foo.txt` exits

If it's relevant, I'm using the Remote SSH extension.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.19.20-1rodete1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (3.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: garymm1.sfo.corp.google.com|
|OS|Linux x64 4.19.20-1rodete1-amd64|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1197)|
|Memory (System)|125.89GB (6.12GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
python|ms-|2019.5.18875

</details>

**Comment by bpasero** [comment]
Yeah, this case is probably not covered well by our logic for deleting the wait marker. If someone has better ideas, code is here: https://github.com/Microsoft/vscode/blob/6a7020dd4a11e0f33b157b3df4baeec90d85701b/src/vs/workbench/electron-browser/window.ts#L478

**Comment by JacksonKearl** [comment]
Finding that the difftool call now never returns, even if the diff is the only editor opened.

**Comment by bpasero** [comment]
**Verification:** https://github.com/microsoft/vscode/issues/75861#issue-458877358
