### ISSUE TITLE
Keys sticking in VSCode

### ISSUE THREAD

**Issue by stcleezy** [microsoft/vscode#75863]
Issue Type: <b>Bug</b>

This started happening a few months ago after a year of using VSCode without issue. 

Very frequently (once every few minutes) when programming, the keyboard will stick for 3-4 seconds and repeat whatever key is being pressed at the time. This happens consistently, and only within VSCode. 

This happens regardless of language, etc. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-eslint|dba|1.9.0
vscode-docker|ms-|0.6.4
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
java|red|0.46.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-spring-initializr|vsc|0.4.5
clang-format|xav|1.9.0

</details>

**Comment by Tyriar** [comment]
Are you sure this isn't related to your keyboard or some other keyboard-related software interfering?

**Comment by stcleezy** [comment]
It looks to be resource related. VSCode taking a majority of my CPU which is pegged at 100%. I will investigate and open another ticket if appropriate once I figure out what's happening.
