### ISSUE TITLE
desired: show error if curly double quotes used instead of straight

### ISSUE THREAD

**Issue by foureyedraven** [microsoft/vscode#75867]
Issue Type: <b>Feature Request</b>

Unfortunately, copying code from Slack produces weird curly or slanted quote marks; would be nice if these reported as an error when straight quotes are required in .html files.

EG, my index.html was reffing a manifest file that it couldn't find because ref="manifest" had curly quotes (see below).

<link rel=“manifest” href=“https://storage.googleapis.com/.....” />

Thank you <3

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

**Comment by yume-chan** [comment]
According to HTML specification, curly double quotes in attributes are totally acceptable.

`ref=“manifest”` will be parsed as `ref="“manifest”"` by any standard complaint parser.

Thus I don't think is worth to implement this check in the core validator. Maybe an extension is more suitable for your specific case.

**Comment by octref** [comment]
Other than what @yume-chan said, we don't have any HTML diagnostic errors and leave that to extensions.
