### ISSUE TITLE
Unless merge when use vscode git push 

### ISSUE THREAD

**Issue by lilililee** [microsoft/vscode#75869]
- VSCode Version: 1.35.1 (user setup)
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/24242242/59892276-f6a36d00-940a-11e9-9368-58d0e16fd58c.png)
Git push

2.
![image](https://user-images.githubusercontent.com/24242242/59892304-0de25a80-940b-11e9-821b-34e6e336ccd8.png)
There have twice commit when only push once， the first merge looks like unless，it broken my commit timeline. How to resolve it？

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
I'm not sure I understand what is going on. Can you provide exact steps of what you did and what happened and what you expected to happen instead?

**Comment by lilililee** [comment]
![image](https://user-images.githubusercontent.com/24242242/60067667-1950c100-973e-11e9-9aa3-8373f3f218d9.png)

I means that i had commit only once，but the vscode git tool automatically generates a merge record. I expected that only have one commit record ,and without  automatic merge record.

**Comment by joaomoreno** [comment]
> I means that i had commit only once，but the vscode git tool automatically generates a merge record. I expected that only have one commit record ,and without automatic merge record.

Clicking `Sync` will pull and push. When pulling surely a new commit came from the server. So git created a merge commit to merge your changes with the server ones.
