### ISSUE TITLE
Add the features to display whitespace when selected.

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7586]
- VSCode Version: 1.3.0-insider
- OS Version: OS X 10.11.4

Steps to Reproduce:

Sublime text demo:

![demo](http://ww4.sinaimg.cn/mw690/534b48acgw1f4svpe2mikg208l05s1kx.gif)

* `"editor.renderWhitespace": "all"` The default display all whitespace.
* `"editor.renderWhitespace": "selection"` display whitespace when selected.

cc @outcoldman in https://github.com/Microsoft/vscode/pull/5423

**Comment by alexandrudima** [comment]
Let's track this in #3828
