### ISSUE TITLE
datalist in webview doesn't have a scroll bar

### ISSUE THREAD

**Issue by ws93** [microsoft/vscode#75864]
- VSCode Version: 1.35.1
- OS Version: Win10

Steps to Reproduce:

1. Have a webview project. For example, [vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample)
2. Add `datalist` element in html with many options
3. You will find that it doesn't have a scroll bar in the dropdown list. While the same html works good in `Firefox` or `Chrome`

VS Code Webview: 
![vscode-webview](https://user-images.githubusercontent.com/17029789/59885168-60c6fe00-9388-11e9-8f48-b4e1471d4b1e.PNG)

Firefox:
![firefox](https://user-images.githubusercontent.com/17029789/59885172-66244880-9388-11e9-9e03-5eadbb44500b.PNG)

Chrome:
![chrome](https://user-images.githubusercontent.com/17029789/59885178-6ae8fc80-9388-11e9-877a-5daf70896617.PNG)

**Comment by mjbvz** [comment]
Likely an electron bug.  Can you please test on one of our exploration builds that uses a newer electron version:

 Download them here:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by ws93** [comment]
@mjbvz The windows version Exploration doesn't work at all... 
It doesn't show any options if you type something or just click on the input bar.

Yesterday when I was try this at home using a Macbook it also didn't work, same behavior(doesn't have any options) on both normal VS Code(1.35.1) and macOS Exploration.

I think it should be an Electron bug. I cloned their [quickstart](https://github.com/electron/electron-quick-start) and added a datalist into it. It also doesn't have scroll bar. Electron version is 5.0.4.

**Comment by ws93** [comment]
Issue I submited in Electron repo: electron/electron#18925

**Comment by mjbvz** [comment]
Thank you. I'm going to close this as an upstream issue then since I do not think we can work around it on the VS Code side

**Comment by ws93** [comment]
The latest version of VS Code(1.36) uses newer version of electron which completely messes up with datalist :(

**Comment by srikar15** [comment]
exactly , even am facing the same problem
