### ISSUE TITLE
webpack aliases doesn't work in a multi-folder workspace

### ISSUE THREAD

**Issue by daizhan** [microsoft/vscode#75878]
- VSCode Version: 1.35.1
- OS Version: Win10 x64

single folder, alias works and vscode has IntelliSense 
![smart](https://user-images.githubusercontent.com/5318547/59904599-8a3e6300-9436-11e9-801e-ff488a1ecf8e.png)

but for multi-folder, it's not work and no IntelliSense 
![not-smart](https://user-images.githubusercontent.com/5318547/59904677-bc4fc500-9436-11e9-8aa6-306ffb5b4167.png)

```
# my jsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by mjbvz** [comment]
Please start by filing this issue against your vue extension
