### ISSUE TITLE
Change window font in User Settings

### ISSUE THREAD

**Issue by askareija** [microsoft/vscode#75872]
I want to change the window font, maybe in User Settings. The reason is i want to make it more like MacOS look-and-feel for windows (like toolbar fonts, sidebar fonts, etc.) It looks something like this, (i change the window font to Roboto in developer tools manually)

![ScreenShot_20190621103010](https://user-images.githubusercontent.com/21377617/59895854-610adc00-9410-11e9-9bfb-5e28b5501f5b.png)

**Comment by yume-chan** [comment]
duplicate of #519

**Comment by askareija** [comment]
oh i didn't see that, sorry.
