### ISSUE TITLE
Filtering trees on type doesnt work

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode#75871]
Using vscode exploration version, I type stuff in the explorer panel, but nothing gets filtered. Does not work in any other trees panel either.

**Comment by isidorn** [comment]
Works for me with latest vscode insiders
https://code.visualstudio.com/insiders/

Are you doing something different than me?

![tree](https://user-images.githubusercontent.com/1926584/59909478-0e312480-9410-11e9-9079-fc24248022dd.gif)

**Comment by Astrantia** [comment]
@isidorn I'm doing exactly that and I know it's not because of my mistake because it's been working sometime in past. It's been breaking haptically and then continued working randomly, now it's broken again. I'm on Windows 10 and using Exploration build. By the way exploration hasn't been updated in a while. What do I report for information?

**Comment by isidorn** [comment]
@Astrantia there will be a new insiders build soon,
As for breaking haptically, I can not really help I would need reproducable steps.

Though forwarding this to @joaomoreno as the tree owner

**Comment by joaomoreno** [comment]
Can you find a way to reliably reproduce?
