### ISSUE TITLE
 Compile run vscode to add Chinese plugin is invalid

### ISSUE THREAD

**Issue by developers-youcong** [microsoft/vscode#75876]
## Problem description
why does the packaged VsCode put into the Chinese plug-in and modify the configuration to take effect, but the compiled and run VsCode related plug-in has been put into the corresponding extension directory, but it does not take effect

## rendering
abnormal：
![image](https://user-images.githubusercontent.com/45055576/59900895-1bf4a300-942c-11e9-988c-3ab6c1961724.png)

normal:
![image](https://user-images.githubusercontent.com/45055576/59900933-3890db00-942c-11e9-91fe-f147d9c60378.png)

**Comment by sandy081** [comment]
@developers-youcong I am not sure what is the issue here. Can you please provide steps to reproduce?

**Comment by developers-youcong** [comment]
step1:
Start listening
![image](https://user-images.githubusercontent.com/45055576/59958237-cf65a200-94d5-11e9-9dda-6ee59d78a1ac.png)

step2:
Run it by >.\scripts\code.bat
![image](https://user-images.githubusercontent.com/45055576/59958284-b4dff880-94d6-11e9-9a7b-0bedd08e7d76.png)


step3:
After executing the code. Bat command, an interface will pop up
![image](https://user-images.githubusercontent.com/45055576/59958277-819d6980-94d6-11e9-8c1d-f9e8d411664d.png)

I have added the Chinese plug-in, normally, it should be like this, as shown in the picture:
![image](https://user-images.githubusercontent.com/45055576/59958315-27e96f00-94d7-11e9-8543-a9d83a2661f3.png)

In general, this is the case:

The compiled and running vscode is added to the Chinese plug-in, without translation (the configuration has been modified), while the packaged vscode has been translated (the configuration has been modified). I wonder why this is happening?

**Comment by sandy081** [comment]
Language pack extensions are not supported while running from dev.
