### ISSUE TITLE
Issue in shifting focus from Terminal tab to Editor tab

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#7587]
- VSCode Version: 1.2 (809e7b30e928e0c430141b3e6abf1f63aaf55589)
- OS Version: El Capitan

Steps to Reproduce:

1. open a editor window
2. open the terminal window
3. click on terminal windows
4. single click on editor doesn't shift focus to editor, have to double click to shift focus from terminal window. Doesn't happen with other windows like the sidebar or other editor tabs

**Comment by Tyriar** [comment]
This is fixed in master/insiders

**Comment by thewhitetulip** [comment]
When can we expect an update? :-)

**Comment by Tyriar** [comment]
@thewhitetulip it's available for preview in the insiders build, it will hit stable in v1.2.0 (early July). In the meantime you can try use keybindings to work around it <kbd>ctrl</kbd>+<kbd>\`</kbd> (toggle terminal) or <kbd>ctrl</kbd>+<kbd>1</kbd> (focus first editor)

**Comment by thewhitetulip** [comment]
@Tyriar Thank you.

I have to appreciate the efforts you guys are taking into maintaining harmony with the community. Typically open source projects are run by control freaks who don't care what the user demands are. Much less communicate promptly with the rest of us.

Also thank you for this awesome editor!

Thank you!
