### ISSUE TITLE
Extension Testing Failing on Travis

### ISSUE THREAD

**Issue by jpoon** [microsoft/vscode#75873]
- Our extension source code hasn't changed (https://github.com/VSCodeVim/Vim), but our builds on Travis have started failing.
- Local build on Windows works fine (don't have Mac/Linux to test on those OS)

The error on Travis doesn't really indicate much:

```
Current working directory: /home/travis/build/VSCodeVim/Vim
Downloading VS Code 1.35.1 into .vscode-test/vscode-1.35.1.
Downloading VS Code from: https://update.code.visualstudio.com/1.35.1/linux-x64/stable
Downloaded VS Code 1.35.1
Running extension tests: /home/travis/build/VSCodeVim/Vim/.vscode-test/vscode-1.35.1/VSCode-linux-x64/code /home/travis/build/VSCodeVim/Vim/out/test --extensionDevelopmentPath=/home/travis/build/VSCodeVim/Vim --extensionTestsPath=/home/travis/build/VSCodeVim/Vim/out/test --locale=en
Tests exited with code: 1
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```
https://travis-ci.org/VSCodeVim/Vim/builds/548501416#L279

Could this be another instance of https://github.com/microsoft/vscode/issues/70857?

**Comment by octref** [comment]
> Could this be another instance of #70857?

Nope, I ran into the same situation as you: https://travis-ci.org/vuejs/vetur/builds/536382977

For some reason VS Code doesn't launch correctly on Travis's Linux machines any more. They work fine for me on Azure DevOps, though: https://dev.azure.com/octref/vetur/_build?definitionId=1

I was just talking with @joaomoreno about this, and my guess was "Likely I need to install correct dependencies on Ubuntu, or deal with xfvb correctly." I'll fix it and let you know.

**Comment by octref** [comment]
This patch / [PR](https://github.com/vuejs/vetur/pull/1343) fixed it for me:

```patch
diff --git a/.travis.yml b/.travis.yml
index 9f57cc1..5c07a6a 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,16 +4,12 @@ os:
   - linux
 node_js: 8
 
-before_install:
-  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
-  - export PATH=$HOME/.yarn/bin:$PATH
-  - if [ $TRAVIS_OS_NAME == "linux" ]; then
-      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
-      sh -e /etc/init.d/xvfb start;
-      sleep 3;
-    fi
-
 install:
+  - |
+    if [ $TRAVIS_OS_NAME == "linux" ]; then
+      export DISPLAY=':99.0'
+      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
+    fi
   - yarn
   - cd server && yarn
   - cd ..
```

Not sure what went wrong — likely you need to start xvfb with same `$DISPLAY` as the `export` says:

I followed https://electronjs.org/docs/tutorial/testing-on-headless-ci mostly.
Upstream issue: https://github.com/electron/electron/issues/16364. This doesn't block extension test from running, but you have can't get rid of the errors as of yet.
