### ISSUE TITLE
1.35.1 sucks

### ISSUE THREAD

**Issue by xtluo-ai** [microsoft/vscode#75879]
Issue Type: <b>Performance Issue</b>

Updated to 1.35.1 ASAP, and now coding seems very slow:
1. autocomplete stuck frequently
2. suggestions also

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-51-generic

**Comment by oneslash** [comment]
Could you follow the https://github.com/microsoft/vscode/wiki/Performance-Issues and provide with more data?

**Comment by carloslahrssen** [comment]
Hey do you have any reproducible examples of what you’re talking about? It’s difficult to pinpoint the problem without them. Thanks!

**Comment by xtluo-ai** [comment]
Sorry, but I don't know how to give a reproducible example, now I have downgraded to 1.34 and everything is OK, strange. Thanks.

Some info.

## programming language

python3

## extensions installed

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-python-docstring|aza|0.0.5
c-cpp-compile-run|dan|0.5.0
vscode-markdownlint|Dav|0.28.0
vsc-material-theme|Equ|2.9.0
output-colorizer|IBM|0.1.2
python|ms-|2019.5.18875
cpptools|ms-|0.23.1

(5 theme extensions excluded)

**Comment by xtluo-ai** [comment]
My CODE stuck frequently(e.g. autocompleting) after updating to 1.5, rolling back to the previous version 1.49 didn't help. Even a `git push` command would get stuck for 2s in the terminal window, So I wonder what is installed by 1.5? What is running beside CODE may cause this problem? I tested `pycharm` IDE which seems to work smoothly.

**Comment by sandy081** [comment]
@xtluo-ai Did you try following the performance wiki and provide us necessary info as recommended there

https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by xtluo-ai** [comment]
@sandy081 Sorry, some information cannot be provided due to confidentiality. I'm closing this rare and strange issue. Thanks for your help.
