### ISSUE TITLE
[feature-request] Add icon to only show all modified files (non source control).

### ISSUE THREAD

**Issue by Kvek** [microsoft/vscode#75886]
Hi, 
It'd be pretty good if there was an icon in the activity bar that showed all the files that are modified. I know that the source control icon does this but I don't want to compare the changes. It would be easier to view the listed modified files in one place than have to navigate the entire app (sometimes a really large app) to search for changed files. Thanks.

**Comment by gjsjohnmurray** [comment]
> all the files that are modified...

@Kvek - modified relative to what? Aren't you willing to use Git as integrated with VSCode? Are you aware how the context menu from the Changes list also lets you open the file rather than the comparison?
![image](https://user-images.githubusercontent.com/6726799/59919439-54da4b00-941f-11e9-8a84-02df36268509.png)

**Comment by Kvek** [comment]
> showed all the files that are modified

I beg your pardon, I should have phrased it better. I meant the files that have been edited relative 
to their previous versions. 

> Are you aware how the context menu from the Changes list also lets you open the file rather than the comparison?

I wasn't aware of this, thanks. This is essentially what I was talking about, but instead of having having to click on 'Open file' from the context menu for each file. I was thinking of a list that just shows all the edited files (without the diffs).

**Comment by gjsjohnmurray** [comment]
I don't understand why the Changes list doesn't meet your need. All the edited files will display there with the "M" badge. Is your problem that a lot of other files list there with the "U" badge, because they are untracked, i.e. not yet under source control?

**Comment by sandy081** [comment]
@Kvek As @gjsjohnmurray mentioned the changes view shows you modified files related to your current version. Please let us know what is missing there?
