### ISSUE TITLE
saving typescript extension as css causes lots of typescript errors

### ISSUE THREAD

**Issue by bryanrasmussen** [microsoft/vscode#75880]
- VSCode Version: 1.35.1
- OS Version: Windows 7 

description/steps to reproduce - I realize the subject line sounds crazy but I think it represents a reasonable workflow.

1.  while editing a .tsx file (typescript react extension) save .tsx file as a new css file (this does not display any syntax errors with the .tsx code even though now the file is a css file.)
2. copy in the css (or write the css you want to have in the file) example css I was using from a litmus email template:
/* CLIENT-SPECIFIC STYLES */
#outlook a {
    padding: 0;
}
result is the #outlook a ends up getting a typescript error - cannot find name 'outlook' ts(2304)

what is expected - 
I get errors shown when I have TS code inside of a .css file. 
I do not get TS errors when I have css code inside of a css file. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I cannot reproduce this

![Jun-21-2019 15-12-47](https://user-images.githubusercontent.com/12821956/59953894-0f297c80-9437-11e9-93b8-b1f030529626.gif)

Are you sure that the language mode of the `.css` file is set to css and not typescript (this is shown in the lower right corner of the status bar)

**Comment by bryanrasmussen** [comment]
@mjbvz yes, you're right the language mode remains the same when I change the extension to .css (just now when I tried it) 

So if it doesn't happen to you that must mean you have some setting enabled to track the language mode by the file extension?

**Comment by mjbvz** [comment]
The language mode should be updated automatically. What is the language mode if you create  a new `.css` file?

**Comment by bryanrasmussen** [comment]
If I create a new .css file the language mode is .css.

**Comment by mjbvz** [comment]
What if you change the file mode after the rename? Does that resolve the issue?

**Comment by bryanrasmussen** [comment]
yes if I manually change the language mode after I have saved a .tsx as a
.css it takes the css mode and validates as it should.

**Comment by mjbvz** [comment]
@bpasero Any idea why the language mode would not be automatically updated when the file extension changes?

**Comment by bpasero** [comment]
@mjbvz probably a consequence of https://github.com/microsoft/vscode/issues/72632. I could maybe improve this to only take the language mode if the original one is an untitled file.

**Comment by bryanrasmussen** [comment]
@bpasero the workflow that causes it in my system is that I have a file
with extension .ts or .tsx (haven't checked on others) I save that file as
a .css - basically because I want to save it to the folder it is already in
- but it keeps the language mode that it originally was - TypeScript or
TypeScript.React, I suppose the problem will exist in anything I have. But
if no one else can replicate this?

**Comment by bpasero** [comment]
I pushed the following fix: only take over the language mode if the target model has `text/plain` as mode, otherwise do not change it assuming it is more specific.

**Comment by joaomoreno** [comment]
Verified that the language mode switches on file rename.
