### ISSUE TITLE
Support workspace settings in multi root environment

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#75888]
> `This setting cannot be applied now. It will be applied when you open this folder directly`

Still actual. related issues: #29456, #28538, #33535, #47995

For example, I have a project (master repo A: backend) with a git submodule (repo B: frontend).

Both have an independent .vscode/settings.json files.

Problem: for instance, any javascript.* settings do not work.
Both A/.vscode/settings.json and A/B/.vscode/settings.json are marked these setting-lines as not effective. See the picture

![Screenshot 2019-06-21 at 14 11 55](https://user-images.githubusercontent.com/6201068/59919157-63306300-942f-11e9-9e14-80f8691815b7.png)
**Picture**: felix is a master repo A, front is a nested repo B

- VSCode Version: 1.35.1
- OS Version: macOS mojave (10.14.5)

Steps to Reproduce:

1. Create project with a second nested .vscode/settings

VS Code w/o exts: **Yes** (e.g. javascript.referencesCodeLens.enabled works only in user/workspace/root-project settings and doesn't work, when added in nested project settings only; wait a sec when indexind will be complete)

VS Code insiders: **Yes**

----

- **Why we use submodule?:** it's simplier to have a single project for fullstack developers. but for frontend and backend developers we have a separate projects, CIs, linters, government regulations etc.
    There are three situations:
    1. Some people just use repo A (felix backend), 
    2. Some ones use repo B (front) only, 
    3. and a lot of people use A with a B as a submodule.

- **Why we prefer project-level settings over a user/workspace?:** I don't want to explain every new developer where he must take him settings and how he must apply it.

**Comment by a-x-** [comment]
it's the same currently is the vscode multiroot workspace enabled or not.

**Comment by a-x-** [comment]
files.exclude setting in nested project (repo B) is not effective too. But, sadly, vscode event does not highlight it

**Comment by sandy081** [comment]
@a-x- In a Multi root workspace we do not allow customising window settings like themes, colors etc per folder. 

Can you please provide the list of settings which you think they should be customisable at folder level in a Multiroot workspace and why?

**Comment by a-x-** [comment]
> In a Multi root workspace we do not allow customising window settings like themes, colors etc per folder.

I don't want it too

**Comment by a-x-** [comment]
e.g. javascript.referencesCodeLens.enabled
and whole javascript.* section

hm, almost everything except window, themes, etc global editor settings, I guess

**Comment by sandy081** [comment]
@mjbvz Are not javascript.* settings are resource scoped?

**Comment by mjbvz** [comment]
It's a mix. The javascript.format settings are resource scoped but `javascript.referencesCodeLens.enabled` and `javascript.format.enable` are window scoped

**Comment by sandy081** [comment]
@a-x- please mention your requirement why you need those settings (`javascript.referencesCodeLens.enabled` and others) as resource scoped.
