### ISSUE TITLE
Adding ability to insert characters in Keyboard Shortcuts 

### ISSUE THREAD

**Issue by parnell** [Microsoft/vscode#7588]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.2.0
2. OS X 10.11.2 (15C50)

Extending Keyboard Shortcuts with the ability to type letters. I think this would be useful in general as it provides more extensibilty to the shortcuts, but it also allows convenience shortcuts for many languages that are used by many programmers. 

Convenience Examples: c++ and Java, adding the semicolon to the end of a line and moving cursor to next line (this functionality is default in many editors/IDEs and is a clickable option in others like Eclipse).  Python, adding the colon to an end of a line and moving down, another example that is default in many editors/IDEs.

**Comment by alexandrudima** [comment]
Let's track this in #7390
