### ISSUE TITLE
PopClip pop-up not shown when highlighting code when using dark themes

### ISSUE THREAD

**Issue by iiKulakov** [microsoft/vscode#75892]
- VSCode Version: 1.35.1
- OS Version: Mac 10.14.6

**Describe the bug**
PopClip pop-up not shown when highlighting code when using dark themes.

**Steps to reproduce the behavior:**
1. Install popClip [https://pilotmoon.com/popclip/](https://pilotmoon.com/popclip/)
2. Activate any dark theme
2. Click on code in VSC
3. Nothing happens

<img width="202" alt="Screenshot 2019-06-21 at 07 42 41" src="https://user-images.githubusercontent.com/22544922/59923139-44fb4080-93f8-11e9-83bc-9c6cdeda1f23.png">

**Expected behavior**
Pop-up window shown with light themes

<img width="381" alt="Screenshot 2019-06-21 at 07 43 07" src="https://user-images.githubusercontent.com/22544922/59923152-517f9900-93f8-11e9-92e6-9a6e1d68b0f6.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Please file against the popClip extension
