### ISSUE TITLE
Provide Code-Levels

### ISSUE THREAD

**Issue by DerHulk** [microsoft/vscode#75894]
...to solving some Cross-Cutting Concerns (ccc) in development.

The idea to solve the problem of ccc is to create mutliplie level 
of code (code-lines) for one class/file at design time. 
These level are mixed togheter by the ide at runtime or can also viewed 
by designtime.

The system is more syntaxtic sugar of an ide feature as it is a pattern or archtecture, but
it is focused to make the readability of code better without disadvantages of performance lossing or hardreading code like in the AOP. 

This is a typcial behavior in drawing programs (for example, paint.net, Inkscape, …), to focus on one part of a picture. So why not use this for coding?

The following is a much simplified example:

![CodeLevel](https://user-images.githubusercontent.com/9537955/59929492-37b67400-9441-11e9-8668-199d1f595bc4.gif)

**Comment by innerlee** [comment]
Cool idea!

It at least can automatically create layers for variable definitions, and each indent levels.

It is cooler if each layer can adjust transparency.

**Comment by DerHulk** [comment]
Thanks :-). Yes i think this feature could be very flexible. Maybe it must implement a configuration for subset of lines on each level. Also some sort of anker-system could be required to ensure the code-mixing will work.
