### ISSUE TITLE
Support the git-client protocol address

### ISSUE THREAD

**Issue by idanpa** [microsoft/vscode#75891]
Github website offers a nice button on the clone menu - "Open in Visual Studio" which let you clone+open the repo directly on Visual Studio, it use `git-client` protocol, e.g.:

[git-client://clone?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode](git-client://clone?repo=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode)
Would open Visual Studio if the Github extension is installed.

It would be nice to have vscode supporting this protocol, from briefly looking on [extensions/git/src/protocolHandler.ts](https://github.com/microsoft/vscode/blob/master/extensions/git/src/protocolHandler.ts) it seems like it already support it and just need to register itself upon installation (?)

Together with 	`git.defaultCloneDirectory` it would be super easy (=one click) to use vscode for browsing through code from Github.
![Annotation 2019-06-21 163124](https://user-images.githubusercontent.com/17422884/59929939-202bbb00-9442-11e9-813e-037df9378320.png)

**Comment by idanpa** [comment]
Created this tampermonkey [script](https://gist.github.com/idanpa/6f7a2ea6dbe1f443c4ec483ea276a158) for the meantime, it replace git-client links to vscode links.

**Comment by MichaelParadis** [comment]
@joaomoreno would I be able to work on this?
