### ISSUE TITLE
bug message

### ISSUE THREAD

**Issue by samankiyani** [microsoft/vscode#75893]
We have written the needed data into your clipboard because it w
Issue Type: <b>Bug</b>

Samans-MacBook-Pro:MyNodeTest samankiyani$ npm install -D nodemon
Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/samankiyani/.npm/_cacache/index-v5/c9/03'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samankiyani/.npm/_logs/2019-06-21T13_42_25_153Z-debug.log
Samans-MacBook-Pro:MyNodeTest samankiyani$ 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (5.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.28.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.7
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.0
debugger-for-chrome|msj|4.11.5

</details>
as too large to send. Please paste.

**Comment by Tyriar** [comment]
You haven't installed npm right, google around for "sudo npm" of "npm permissions error", etc.
