### ISSUE TITLE
[Feature Request] Extensions: ability to detect light/dark theme

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7589]
It seems there's no way to detect the if the current theme is dark or light.

This can be a problem if the extension has complex css, like this one http://stackoverflow.com/questions/37257911/detect-light-dark-theme-programatically-in-visual-studio-code

It would be great if there was a way to determine the kind of theme applied from the extension

**Comment by rebornix** [comment]
@warpdesign we are extracting VS Code's markdown support to a separate extension and we've implemented the theme detection both in the extension and vscode side. Please keep an eye on https://github.com/Microsoft/vscode/issues/6106, once June release is out, you'll get what you want.

**Comment by jrieken** [comment]
@warpdesign The view your html is rendered in uses some css [variables](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L121) which hold values for the background and foreground colors. Would those be sufficient?

**Comment by jrieken** [comment]
With PR #7656 we will introduce these class names: `vscode-light`, `vscode-dark`, and `vscode-high-contrast`. Depending on the theme one of them is set on the document body.

**Comment by warpdesign** [comment]
@jrieken that's perfect!
:+1:

**Comment by jrieken** [comment]
We have this since merging the MD extension to master: `vscode-light`, `vscode-dark`, or `vscode-high-contrast` (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L46)

**Comment by jrieken** [comment]
- [ ] Test Plan Item created
- [ ] Key board accessible
- [ ] Screen reader accessible
- [ ] Works with the different themes, including the high contrast theme
- [ ] Telemetry events in place
- [ ] Release notes updated

**Comment by jaime-olivares** [comment]
Relying on CSS class names won't help in all use-cases. Sometimes you need to know the theme "darkness" before generating the output html (bitmap, svg, etc.).

From an extension, we are able to know almost every editor setting. Why the theme is an exception?

Isn't it better to have an enumeration with light/dark/contrast values? or even access to every theme color for a precise matching?
