### ISSUE TITLE
Git terminal is not clearing with command ctrl + l

### ISSUE THREAD

**Issue by Fagneregomes** [microsoft/vscode#75896]
- VSCode Version:  1.35.1
- OS Version: 1903

Steps to Reproduce:

1. integrate git bash to vscode.
2. execute command on the terminal and try to clean.

<!-- Launch with `code --disable-extensions` to check

![ScreenRecorderProject1 (1)](https://user-images.githubusercontent.com/11872631/59931149-bba93580-941a-11e9-9268-b5f513d1939b.gif)

**Comment by Fagneregomes** [comment]
see the error.

![ScreenRecorderProject1 (1)](https://user-images.githubusercontent.com/11872631/59931564-9ec13200-
941b-11e9-8a6b-322255276aa3.gif)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
