### ISSUE TITLE
Pressing enter on folder in filtered File Explorer

### ISSUE THREAD

**Issue by ambrt** [microsoft/vscode#75898]
When someone searches with letters in File Explorer and finds folder  but letters don't match any file inside that folder, there's no way to go to that folder (or list all files under that folder)

![feature](https://user-images.githubusercontent.com/10456131/59935450-1dcf5e00-944e-11e9-94ce-194b27440d46.gif)

Enter toggles empty list.
The suggestion is to set ctrl+enter to go to that folder standard (non filtered) File Explorer pane.

**Comment by ambrt** [comment]
The suggested issues by vscodebot seem not to be duplicate.

Just to clarify i can list  files with Quick Open (`ctrl+p >store/`) but can't do that in Explorer Pane

![feature-store3](https://user-images.githubusercontent.com/10456131/59976710-9eb26500-95c8-11e9-93d9-9d5284afef3a.gif)


Maybe if one would type slash after the string then Explorer would show files under the folder.

**Comment by isidorn** [comment]
This is a request to force the tree to show filtered out children of a visible parent.
Thus fowarding to @joaomoreno since the tree would first need to support this

**Comment by joaomoreno** [comment]
#69013
