### ISSUE TITLE
Python setup.cfg files are broken by auto-formatting

### ISSUE THREAD

**Issue by acdha** [microsoft/vscode#75902]
Issue Type: <b>Bug</b>

My Python project has a setup.cfg file. This file is detected as the “Properties” langauge.

I added a multi-line property to the file following the standard syntax:

https://github.com/LibraryOfCongress/concordia/blob/1d48009c0d10c7bf9e6a08bb23ee142d90a68abe/setup.cfg#L25-L26

If I let VSCode format that file, it removes the leading indentation which actually breaks the way tools parse this file by causing the value(s) to be seen as new property declarations.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.23
vscode-django|bat|0.19.0
better-toml|bun|0.3.2
language-prometheus|caa|0.1.2
systemd-unit-file|coo|1.0.3
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
gitlab-workflow|fat|2.1.0
shell-format|fox|6.0.1
vscode-pull-request-github|Git|0.8.0
todo-tree|Gru|0.0.135
vscode-cfn-lint|kdd|0.7.0
restructuredtext|lex|110.0.0
rainbow-csv|mec|1.1.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.6.4
python|ms-|2019.5.18875
debugger-for-chrome|msj|4.11.5
fabulous|raa|0.12.0
vscode-yaml|red|0.4.1
rust|rus|0.6.1
crates|ser|0.4.3
vscode-nginx|sha|0.6.0
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
rewrap|stk|1.9.1
vcl|tho|0.1.2
shellcheck|tim|0.6.0
sort-lines|Tyr|1.8.0
propertylist|zho|0.0.2

</details>

**Comment by sandy081** [comment]
Please file issue against the formatter that is formatting. I suspect this is from python extension.
