### ISSUE TITLE
Live share gets out of sync

### ISSUE THREAD

**Issue by cjbrunner** [microsoft/vscode#75908]
Issue Type: <b>Bug</b>

Sometimes when working with one or more people on a project, our screens can get out of sync.  He will see totally different changes to text on his screen or vice versa.  It's relatively rare (every couple days or so), but folks have to leave and rejoin to get everyone back on the same page.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
vscode-mocha-test-adapter|hbe|2.1.1
vscode-test-explorer|hbe|2.12.0
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
vsliveshare|ms-|1.0.419
vscode-react-native|msj|0.9.3
vscode-yaml|red|0.4.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the live share extension: https://github.com/MicrosoftDocs/live-share/issues?utf8=✓&q=is:issue+is:open+sort:reactions-%2B1+
