### ISSUE TITLE
Merge Conflict Git Lens missing

### ISSUE THREAD

**Issue by HaveSpacesuit** [microsoft/vscode#75901]
Issue Type: <b>Bug</b>

Ensure `Merge-conflict > Code Lens: Enabled` is chekced in the settings

Merge a git branch causing merge conflict

Open the diff tool

The current and incoming changes are highlighted correctly. The inline toolbar above them which allows to accept the current or incoming is missing.

Similar to [this issue](https://github.com/microsoft/vscode/issues/74153)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (25.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
debugger-for-chrome|msj|4.11.5
vscode-subword-navigation|ow|1.2.0
vscode-autohotkey|sle|0.2.2

</details>

**Comment by chrmarti** [comment]
Do you have Editor > Code Lens enabled as well?

**Comment by HaveSpacesuit** [comment]
I did not. Turning it on resolves the issue. Thanks!
