### ISSUE TITLE
[Feature Request] Extensions: add an API to determine the type of word of a selection

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7590]
Right now, there's no way to determine the type of word of the selection.

It would be useful if from an extension I could know that some word is a string, a regexp,.. depending on the language.

I am working on an extension that will show a visual diagram of a regex. The problem is that there is no way to know the current selected word is a string and/or regex.

**Comment by alexandrudima** [comment]
Let's track it in #7027
