### ISSUE TITLE
Breadcrumbs open-to-side with keyboard no longer working? 

### ISSUE THREAD

**Issue by andreskebe** [microsoft/vscode#75904]
- VSCode Version:  1.35.1 
- OS Version: Mac OS 10.14.5

Steps to Reproduce:

1. Select breadcrumbs
2. Select a file
3. hit alt-enter on keyboard to open the selected file to the side 
4. Nothing happens

Does this issue occur when all extensions are disabled?: Yes

When i alt (that's my modifier for open to the side, working everywhere else) click on the breadcrumbs, the file is opened to the side. However with the keyboard it is not working.

**Comment by jrieken** [comment]
It should be Cmd/Ctrl+Enter but that also seems to be defunct

**Comment by andreskebe** [comment]
Ah so it is broken after all! I was going crazy when it wasn't working, probably one of my favourite features in VS Code. Will this be fixed in the next release? 
Thanks for all your hard work!
