### ISSUE TITLE
Cmd + click on terminal link doesn't work on some computers

### ISSUE THREAD

**Issue by alexeigs** [microsoft/vscode#75906]
Scenario A:
Installed vscode on Mac Book Pro 2018 edition with Settings A (imported)

Scenario B:
Installed vscode on brand new Mac Book Pro 2019 edition with Settings A (imported)

Scenario A2: Uninstalled VSCode, installed all available mac updates, reinstalled vscode

Both in A and A2 I cannot click on any error links in the terminal `ERROR in /Users/.../...` while in B and also on the computer of some friends (but also not of all) it is working to click on the links shown and be directed to/open this file.

Any idea what could cause that issue? Something related to the terminal specifically or related to vscode? It seems like a known issue but although I read many times that it was actually fixed, apparently it is still possible to occur.

**Comment by Tyriar** [comment]
There are some lingering issues with links still, the only ones I'm aware of are sometimes link creation doesn't work and needs you to scroll up and down with the mouse wheel to refresh them, the other is multi-line links can sometimes fail. Does this help?
