### ISSUE TITLE
broken symlinks not showing in treeview

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#75907]
- VSCode Version: Version 1.35.1 (1.35.1)
- OS Version: Mac Mojav 10.14.5 (18F132)

Steps to Reproduce:

1. mkdir a; cd a
2. ln -s yay what
3. Checkout the file tree in vscode. Directory a appears to be empty.

Does this issue occur when all extensions are disabled?: Didn't check

There seems to be other issues regarding this but they are all closed with no sign it's been fixed. And I'm experiencing this issue.

**Comment by thesmiley1** [comment]
This is understandably low priority, but I think it should be dealt with at some point.  In my case it caused the appearance of a file disappearing.

I had a relative symlink, e.g.:

```
a/
  1.txt
b/
  2.txt (-> ../a/1.txt)
```

and moved the symlink to another directory level via file explorer, e.g.:

```
a/
  1.txt
b/
  c/
    2.txt (-> ../a/1.txt)
```

which caused the symlink (2.txt) to just disappear from the file explorer.

Just not showing a broken symlink is a (somewhat) benign bug, but a file disappearing from the interface is a little more concerning.

I think it would be good if there was a visual indicator in the file explorer (e.g. file name red or darker/lighter) and opening it displays a read-only buffer that explains the file is a broken symlink.
