### ISSUE TITLE
Can vscode complete normal text everywhere?

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#75913]
I'll explain that. Can vscode complete `sub` word in here??????

![all](https://user-images.githubusercontent.com/42807112/59947212-e7eda200-946c-11e9-985e-39a7c8bd5b93.jpeg)

In order to know some parameters of the `url` of my web app.

**Comment by minkir014** [comment]
Any look on this????????????????????????????????

**Comment by sandy081** [comment]
Not sure if this has to come from language or editor core. Hence assigning to both of you.

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/21611
