### ISSUE TITLE
Files not shown in sidebar and are duplicated in index

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#75919]
Issue Type: <b>Bug</b>

For whatever reason, it appears certain files in a certain project of mine are listed twice in the file index.

![image](https://user-images.githubusercontent.com/1658949/59952940-55ee9500-947e-11e9-9b41-92089d7e929b.png)

They are listed once under the path relative to the project root and once with their absolute path.

In this example, the subject file is `src/js/layout/navbar/navbar.pug`. When I open the file with the relative path, VS Code focuses the subject file in the sidebar.

![image](https://user-images.githubusercontent.com/1658949/59953016-9e0db780-947e-11e9-99a9-e7668e17d6fa.png)

However, when I open the file with the absolute file name, suddenly the entire `src` folder is empty in the sidebar.

![2019-06-21_23-46-33](https://user-images.githubusercontent.com/1658949/59953088-d7462780-947e-11e9-80ff-34eeb3f3212c.gif)

When I open a relative-path file again, the contents of the `src` folder are displayed again.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (35.81GB free)|
|Process Argv|core-live/core-live.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
generateuuid|Fir|0.0.5
vscode-mocha-test-adapter|hbe|2.1.1
vscode-test-explorer|hbe|2.12.0
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
terraform|mau|1.3.12
code-beautifier|mic|2.2.1
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
vscode-paste-image|mus|1.0.4
syncing|non|3.0.3
vscode-yaml|red|0.4.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce this with latest vscode insiders
https://code.visualstudio.com/insiders/
If yes, if you F1 > developer tools > debug console > do you see some errors there, if yes can you please share theme here?

**Comment by oliversalzburg** [comment]
> Can you reproduce this with latest vscode insiders

I can not, but I also don't know what causes this specifically. When I Ctrl+P, I don't see `navbar.pug` twice though, so I can't force the error case.

>  F1 > developer tools > debug console

That doesn't exist for me on either Stable or Insiders.

**Comment by isidorn** [comment]
If you can not reproduce with vscode insiders there is not much we can do to fix it.
Here's how you can check debug console - I am using VSCode Stable in this gif

![developerTools](https://user-images.githubusercontent.com/1926584/60079926-316d1400-972f-11e9-9a94-50919b645236.gif)

**Comment by oliversalzburg** [comment]
Oh, well, _that_ I know. What you described seemed like you want something else. Nevermind.

Just FYI, Insiders has different extensions, configuration and probably cached data. So, unless you're aware of a specific fix that has been applied, I'm not really confident in this reproduction approach.

That being said, there also was no output in the Developer Tools Console in Stable.

**Comment by oliversalzburg** [comment]
I have 1.36.0 now and this just started happening again in a different project. Developer Tools Console doesn't show anything special.

![image](https://user-images.githubusercontent.com/1658949/60835061-89d9f200-a1c2-11e9-87bc-d041b18a3669.png)

**Comment by isidorn** [comment]
For files not showing in sidebar there is already an issue. However nobody found steps thus far which makes this hard for me to fix
Here's the issue for reference https://github.com/microsoft/vscode/issues/72174
