### ISSUE TITLE
Cmd Click does not work in some cases after VScode update

### ISSUE THREAD

**Issue by dhiviyadhanasekar** [microsoft/vscode#75917]
I recently updated VS code to Version 1.35.1 (1.35.1). I command click on some objects that have been exported using `default export` in that file and it no longer take me to that file. It continues to stay where it is.

![Jun-21-2019 14-24-29](https://user-images.githubusercontent.com/6762810/59952284-71cb4a00-9430-11e9-851b-b6363169b8e6.gif)

**Comment by mjbvz** [comment]
Please share example code that demonstrates this problem

/needsMoreInfo
