### ISSUE TITLE
C/C++ Does not start debugging

### ISSUE THREAD

**Issue by TheAifam5** [microsoft/vscode#75911]
- VSCode Version: 1.35.1
- OS Version: ArchLinux

Steps to Reproduce:

Dont know how but here is the script:
```
echo $$ > /tmp/Microsoft-MIEngine-Pid-7uicda43.h0t ; cd /home/theaifam5/app ; DbgTerm=`tty` ; set -o monitor ; trap 'rm /tmp/Microsoft-MIEngine-In-mhg8vkz9.w1n /tmp/Microsoft-MIEngine-Out-gkoand7l.be7 /tmp/Microsoft-MIEngine-Pid-7uicda43.h0t /tmp/Microsoft-MIEngine-Cmd-puyben24.gos' EXIT ; read -n 1 -p \"Superuser access is required to attach to a process. Attaching as superuser can potentially harm your computer. Do you want to continue? [y/N]\" yn; if [[ ! $yn =~ ^[Yy]$ ]] ; then exit 0; fi; /usr/bin/pkexec /usr/bin/gdb --interpreter=mi --tty=$DbgTerm < /tmp/Microsoft-MIEngine-In-mhg8vkz9.w1n > /tmp/Microsoft-MIEngine-Out-gkoand7l.be7 & clear; pid=$! ; echo $pid > /tmp/Microsoft-MIEngine-Pid-7uicda43.h0t ; wait $pid; 
```

Does this issue occur when all extensions are disabled?: Yes

Just shows: “Superuser

**Comment by TheAifam5** [comment]
What's the status? Just closed without any clarification?

**Comment by weinand** [comment]
The clarification is:
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.

C/C++ is not part of VS Code but comes as a separate extension.
Please raise this issue against the C/C++ extension you are using.
