### ISSUE TITLE
Why the format will automatically remove the semicolon?

### ISSUE THREAD

**Issue by Houfeng** [Microsoft/vscode#7591]
Why the format will automatically remove the semicolon? If you don't think we should add a semicolon, can you give me a hint, why change my code?

You don't love a hat, can give me to say,  but you can't take off my hat !!

**Comment by alexandrudima** [comment]
@Houfeng What language are you formatting? Can you also provide a small sample source that can reproduce the problem?

**Comment by Houfeng** [comment]
sorry, is an extension of the resulting.
