### ISSUE TITLE
Allow configuration of terminals/commands to run at workspace startup

### ISSUE THREAD

**Issue by VIMGAS** [microsoft/vscode#75912]
# Feature Request

I'm usually involved with microservices development, therefore, I tend to have multiple services/projects that needs to be up and running locally before I can start developing anything.

It would be great if workspace configuration files could support a true/false option to determine wether or not a terminal should be spawned for a given folder of the workspace at vscode startup. Also, it would be great to be able to set a name for that terminal instance.

It would save me and perhaps other people a lot of setting up time as I have to open and rename a lot of terminal instances for my microservices workspace every time before I can do any changes to front-end or api servers.

Wrapping up:

- Add `spawnTerminalAtStartup` (or something else) configuration inside folders workspace settings to control whether it should spawn the terminal when vscode launches;
- Add `defaultTerminalName` (or something else) configuration inside folders workspace settings (this would also be applied when manually creating a new terminal for that specific workspace folder);

**Comment by Tyriar** [comment]
You can accomplish similar to this right now via extensions (https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals) or by using tasks
