### ISSUE TITLE
Quickly swap selections 

### ISSUE THREAD

**Issue by Kaos-Industries** [microsoft/vscode#75918]
I've recently started experimenting with VS Code after having been a Sublime Text 3 user for several years. One of my favourite and most-used features/key bindings of ST3 was the ability to quickly swap two selections of text with Ctrl+T.

By contrast, the closest analogue I've found to this key binding in VS Code is the ability to swap lines with Alt+X. This:

a) limits the selection to be swapped to a line, and 
b) only allows that line to be swapped with the line immediately above or below it. 

This makes swapping two selections that are further apart than a few lines very clunky, and so is not a great stand-in for the Ctrl+T behaviour in ST3. 

Is there any chance Sublime Text's Ctrl+T behaviour could be implemented into VS Code (obviously with a key binding that is free)?

**Comment by Kaos-Industries** [comment]
See here: https://techtalkdc.com/transpose-or-why-sublime-text-is-a-better-text-editor-than-visual-studio/.

**Comment by rebornix** [comment]
I'll recommend to implement this in an extension.
