### ISSUE TITLE
Glitchy (unusable) Terminal

### ISSUE THREAD

**Issue by kaitlynbrown** [microsoft/vscode#75926]
- VSCode Version: 1.35.1
- OS Version: Fedora 30

Steps to Reproduce:

1.Open the terminal
2.Try to type anything

Does this issue occur when all extensions are disabled?: Yes

The terminal is completely [unusable](https://imgbox.com/g/DDB0VtjyDE)
Though I suppose it makes for some interesting abstract art

**Comment by Tyriar** [comment]
There's probably an issue with your graphics drivers, you can turn off GPU acceleration with the setting:

```
"terminal.integrated.rendererType": "dom"
```
