### ISSUE TITLE
bad prediction on a file

### ISSUE THREAD

**Issue by gilberto389** [Microsoft/vscode#7592]
- VSCode Version:

Versión 1.3.0-insider
Confirmación 7d56f33e508930d3727064481a7525344a227f10
Fecha 2016-06-10T06:08:40.882Z
Shell 0.37.6
Representador 49.0.2623.75
Node 5.10.0

- OS Version: win 7 ultimte 64 bits

Steps to Reproduce:

1. watch video
https://youtu.be/MTObQB4tm9U

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9117
