### ISSUE TITLE
Unable to switch default terminal if WSL is disabled

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#75922]
Issue Type: <b>Bug</b>

If the WSL feature is disabled the select default terminal from the terminal drop down will not work. The developer tools will log that it cannot find `wsl.exe` because it does not exist due to the feature being disabled.

1. Make sure WSL is disabled `Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
2.  Restart your machine
3. Open VS Code
4. Switch default terminals

VS Code version: Code - Insiders 1.36.0-insider (9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21, 2019-06-21T07:52:00.716Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (2 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.98GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
remote-ssh-edit-nightly|ms-|2019.6.29700
remote-ssh-explorer-nightly|ms-|2019.6.29700
remote-ssh-nightly|ms-|2019.6.29700
vscode-icons|vsc|8.7.0

</details>

**Comment by Tyriar** [comment]
According to the WSL team when you disable WSL then wsl.exe won't exist on disk, so the stat call should fail and not show up in the shell selector dialog. Are you sure you didn't set the shell before disabling?

**Comment by Tyriar** [comment]
Ok I repro'd the problem, weird.

**Comment by aeschli** [comment]
With 'switch default terminal' you mean setting/removing `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe"`

I verified that this works as I would expect it.
Obviously when you have the wsl path configured but WSL is removed from the system, the terminal stays empty (no error message). Not sure if that's a bug or intended.

**Comment by Tyriar** [comment]
'switch default terminal' means using the select default terminal option in the dropdown (or the Select Default Terminal command)
