### ISSUE TITLE
TypeScript intellisense does not work when logging in as multiple users on Linux

### ISSUE THREAD

**Issue by asztal** [microsoft/vscode#75920]
- VSCode Version: 1.35.1
- OS Version: Ubuntu Bionic 18.04.02

Steps to Reproduce:

1. Log in as user1
2. Launch VS Code
3. You can use TypeScript intellisense
3. Log out
4. Log in as user2
5. Launch VS Code
6. You cannot use TypeScript intellisense

It tries to write to files in /tmp/vscode-typescript, but that directory is not writeable because it already exists and is owned by user1

Does this issue occur when all extensions are disabled?: Yes

Fixed by #75547

**Comment by pludov** [comment]
A quick workaround for the inpatients:

sudo chmod 1777 /tmp/vscode-typescript

**Comment by mjbvz** [comment]
Fixed by #75547
