### ISSUE TITLE
φ != ϕ, unicode operators show up as the same

### ISSUE THREAD

**Issue by basnijholt** [microsoft/vscode#75921]
Reproduce with
1. Paste these characters into a file: 
```
φ ϕ
```
2. Control + F to find, search for one of them, and both will show up.

These characters are different! I spend a long time to debug a Python program because
```
>>> python -c "print('φ' == 'ϕ')"
False
```

This was also reported here https://github.com/microsoft/vscode/issues/61275 but the issue is locked and closed.

**Comment by rebornix** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/61275
