### ISSUE TITLE
Debug failed to load: Process picker failed (your 131072x1 screen size is bogus, expect trouble)

### ISSUE THREAD

**Issue by markmail** [microsoft/vscode#75932]
Debugger failed to load when using with "attach by process ID".

I'm running VS Code connected to WSL 2 with Ubuntu 18.04.2 LTS.

I had the same code running in pure Windows environment, and debugger launched fine. I start getting this screen size is bogus error when I moved my code to WSL 2, unsure if it's WSL related or VS Code.

Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18917
*** I use the official Microsoft "Remote - WSL" extension from marketplace to connect to WSL

Steps to Reproduce:

1. Launch VS Code in Windows
2. Open code in WSL 2
3. Configure launch.json with the following
`
        {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}"
        }
`
4.  Start debugging by click the green play button.

![image](https://user-images.githubusercontent.com/51925547/59961530-a829c780-950b-11e9-9263-62879ecb2427.png)

**Comment by fabienheureux** [comment]
Fyi, I encountered the exact same issue with the same configuration. 
Did not find a way to fix it for now

**Comment by CrshOverride** [comment]
Same issue here when attempting to attach to .NET Core running in WSL 2.

<img width="275" alt="Screenshot 2019-08-02 13 19 03" src="https://user-images.githubusercontent.com/791698/62389817-d947df80-b52e-11e9-9142-c3803b692ba0.png">

**Comment by victor141516** [comment]
I'm having the same issue. As @CrshOverride said, if you hardcode the pid in the config file it will work. However this workaround is much slower than the automatic pid finding. I'd like to see a fix for this soon since it looks like a simple issue

**Comment by shrestaz** [comment]
7 months later and the issue still exists.
The workaround for me was to downgrade from WSL 2 to WSL 1.
You lose the features of WSL 2 but it at least allows to continue working.

Hoping to see some update on the issue.

**Comment by sinapis** [comment]
As a workaround, I attach via remote debugger:

In launch.json
```
{
      "type": "node",
      "request": "attach",
      "name": "Attach",
      "restart": true,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "${workspaceRoot}"
    }
```

And start node with --inspect.

This works even better with nodemon:
`nodemon --watch src -e ts --exec node --inspect .`

**Comment by Pilchie** [comment]
I'm also seeing this trying to switch what solution Omnisharp is analyzing in the C# extension when using WSLv2.

**Comment by danecreekphotography** [comment]
I hit this as well, with the same config as the original report: WSL2, code launched from inside WSL2, then trying to use the process picker to look for running node.js instances.

Workaround also worked: I can make a launch task that attaches via the specific node debugger port and it works fine.

**Comment by weinand** [comment]
This issue is basically a variant of #35798:

On some linux systems, the "/bin/ps" command tries to verify that the screen size is big enough to print anything useful. If the size is too small, the message "your 131072x1 screen size is bogus, expect trouble" gets send to stderr.

Since the "process picker" used in VS Code is using "/bin/ps" to find all node.js processes. If an error is detected on stderr, the picker shows the error and assumes that the "ps" failed.

The workaround is to detect and ignore this special "error".

**Comment by hanefi** [comment]
@weinand Can we please keep the issue open until the fix is implemented and merged?

I will not be able to use VSCode until this gets fixed, as this is a blocker for me

**Comment by weinand** [comment]
This fixed is implemented and merged. It will appear in the next Insiders (tomorrow).

**Comment by connor4312** [comment]
@hanefi can you verify whether the fix worked for you? 🙂

**Comment by JacksonKearl** [comment]
Bot isn't happy with commits in other repos... I'll work on this.
https://github.com/microsoft/vscode/issues/93814#issuecomment-608031490

In the mean time, @hanefi you can help us out by testing that things work as expected now, and if so comment `/verified` to mark this as resolved :)

**Comment by danecreekphotography** [comment]
Not the original reporter, but I just gave this a whirl with the insider's build and no longer get the error.

I launched code-insiders from inside an Ubuntu WSL2 instance then did Debug: Attach to Node Process. I was presented with a list of three node processes, all running on the Windows side. It did not show anything running in my Docker containers.

I then launched code (not insiders) from the same Ubuntu instance and tried Debug: Attach to Node Process. I got the error reported above.

So it appears fixed!

**Comment by weinand** [comment]
@danecreekphotography thanks for verifying. 
Adding "verified" label

**Comment by danecreekphotography** [comment]
Thanks! I didn't want to directly add the slash verified since I wasn't the original reporter.

**Comment by JacksonKearl** [comment]
@danecreekphotography it only works for the issue author anyways :)

**Comment by shrestaz** [comment]
The fix allowed me to completely move to WSL 2. Great work team.
_(I moved to VS Code insiders for the fix and haven't used stable since.)_
