### ISSUE TITLE
gd(go to definetion) jumped twice,  the first time is correct, but the the second time jump to uncorrect location

### ISSUE THREAD

**Issue by xxsong5** [microsoft/vscode#75934]
- VSCode Version: 1.35.1
- OS Version: windows 7

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by xxsong5** [comment]
with VscodeVim extension

**Comment by rebornix** [comment]
@xxsong5 can you reproduce this issue when running Go To Definition from the command palette?
