### ISSUE TITLE
gnome wouldn't run vscode on double click

### ISSUE THREAD

**Issue by PaulWang1905** [microsoft/vscode#75935]
- VSCode Version: 1.36.0-insider
- OS Version: archlinux x64
- kernel version: 5.1.12

Steps to Reproduce:

After double clicking on code-insiders, gnome prompts a message "There is no application installed for "shared library" file type. 
 However, VS Code successfully launches via terminal.
 I think it is caused by gcc compile option.

**Comment by Tyriar** [comment]
The AUR package is maintained by the community, I think you should follow up with them.
