### ISSUE TITLE
[Bug] Terminal

### ISSUE THREAD

**Issue by sptndc** [microsoft/vscode#75937]
When I want to open a terminal in vscode, what appears is a warning 'The window has crashed' and asks to reopen. This has never happened in the previous version, please fix this issue quickly.

![2019-06-22](https://user-images.githubusercontent.com/20803810/59963974-a02a5180-9524-11e9-8b9e-e85cfb860272.png)

- VSCode Version: 1.35.1
- OS Version: Windows 10 Pro 1903

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by Dreamurrrr** [comment]
VS Code works for me. Try uninstalling your extensions before attempting to open it again. You can do this by putting this in your File Explorer directory bar and then deleting all of the folders inside of it: `%USERPROFILE%\.vscode\extensions`

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
