### ISSUE TITLE
Hide editor context menu items

### ISSUE THREAD

**Issue by idanpa** [microsoft/vscode#75930]
After installing extensions the editor's context menu may become really bloated and hard to reach.
Extensions authors usually give the option the remove their menu items, but it would be nice to be able to remove the default ones.

I usually not using  any of the `Copy`/`Cut`/`Paste` menus, and I certainly not using the `Command Palette...` item (when I use the command palette my hands are already on the keyboard).

(This issue is similar to #3874, but for the context menu)

**Comment by pankaj-webkul** [comment]
Yes. There should be a way to hide items from context menu just like with status bar in 1.36.1.

**Comment by pankaj-webkul** [comment]
#9285

**Comment by AlbertoFabbri93** [comment]
I think a very good starting point would be being able to disable the default entries and then later implement a general interface for all of them (built-in + contributed by extensions).

**Comment by alfuken** [comment]
+1 to reopening this. This kind of functionality is pretty logical to have.

**Comment by Syul968** [comment]
+1 to reopening this. I want to arrange and add/remove context menu items in a way that makes sense for my workflow. And for tabs context menu items too.

**Comment by MartinAtSogeti** [comment]
Vivaldi browser has a pretty nice way of handling modifying of context menus and also create folders to restructure items. Like, I don't mind creating Angular bits from the context menu, but it would be fine if it was in a subfolder and not spamming 10 links in my context menu. Right now I have 34 items in the context menu and only really use 5 frequently. For me it just saves a lot of time typing things out for those that prefer that.

I'd expect something where I can create folders and separators, drag items into place and then saving it. Files and folders might be separate, perhaps even file type specific context menus. Of course resetting should be possible and adding or removing commands would be nice. But even already hiding specific items would be nice to have and make me more productive.

**Comment by yiliang114** [comment]
I also have the need to hide menus, built-in menus or other extended menus, users should be able to configure ignore not to display them.

**Comment by bigsnowballhehe** [comment]
need this

**Comment by Yuki2718** [comment]
+1 for this, over time more and more items have been added which I never use and they're annoying,

**Comment by akors** [comment]
Why is this issue closed, and why are "duplicates" of this issue closed? Context menu is simply too big.

I personally don't need much customization, but it should be clear if the context menu takes up more space than the screen height, something is not going well. It makes the context menu useless if I have to search for various functions.

@sbatten you closed issue #171906 as a duplicate of this one, but this one is already closed. Would you mind reopening this issue because it is clearly not solved.

**Comment by fa1247** [comment]
There should be a function to hide all context menus brought by an extension, or more flexible, to disable or remove certain menus as needed, just like the software RightMenuMgr on Windows.

**Comment by jackphilippi** [comment]
+1 🥴
![image](https://github.com/microsoft/vscode/assets/12421916/259681c0-de88-40e7-910d-be9e289c784f)

**Comment by gohilurvish** [comment]
While I also wants to remove Cut/Copy/Past and some other stuff from the right-click menu, the major issue was commands added by extensions.

The workaround I am using is : Delete the items added by extensions.
On mac:
1. Go to "~/.vscode/extensions" folder
2. cd to extension and open package.json file
3. Go to "contributes" -> "commands" and remove the entry which is not needed.

**Comment by Long0x0** [comment]
Thanks to @be5invis we have greasemonkey/tampermonkey for vscode: [vscode-custom-css](https://github.com/be5invis/vscode-custom-css).
> Use it at your own risk.

Here is my script to hide some context menu items:
```js
/*
Hide context menu items in vscode.
`Reload Custom CSS and JS` to apply changes.

Tricks:
  Help > Toggle Developer Tools, run `setTimeout(() => { debugger }, 3000)`
  in Console, open the context menu within 3 seconds, wait for the debugger
  to pause, then inspect items in Elements.
*/

(function () {
  console.log("Hello from custom_context_menu.js~");

  const selectors = [
    '^"Go to"', // start with "Go to"
    '"Change All Occurrences"', // exact match
    '"Share"',
    '"Share" + "_"', // sperator after "Share"
    '"_":has( + "Share")', // separator before "Share"
    '"Command Palette..."',
    '"_":has( + "Command Palette...")',
    '"Layout Controls"',
  ];

  const css_selectors = selectors
    .join(",\n")
    .replaceAll(/([*^|])?"(.+?)"/g, '[aria-label\x241="\x242"]');
  console.log(css_selectors);

  function wait_for(root) {
    const selector = ".monaco-menu-container > .monaco-scrollable-element";
    new MutationObserver((mutations) => {
      for (let mutation of mutations) {
        for (let node of mutation.addedNodes) {
          if (node.matches?.(selector)) {
            // console.log(">>", node);
            modify(node);
          }
        }
      }
    }).observe(root, { subtree: true, childList: true });
  }

  // context menu in editor
  Element.prototype._attachShadow = Element.prototype.attachShadow;
  Element.prototype.attachShadow = function () {
    const shadow = this._attachShadow({ mode: "open" });
    wait_for(shadow);
    return shadow;
  };
  // context menu in other places
  wait_for(document);

  // get mouse position
  let mouse_y = 0;
  document.addEventListener("mouseup", (e) => {
    // bug: not working in titlebar
    if (e.button === 2) {
      mouse_y = e.clientY;
      // console.log("mouse_y", mouse_y);
    }
  });

  function modify(container) {
    for (let item of container.querySelectorAll(".action-item")) {
      const label = item.querySelector(".action-label");
      const aria_label = label?.getAttribute("aria-label") || "_";
      item.setAttribute("aria-label", aria_label);
    }

    const menu = container.parentNode;
    const style = document.createElement("style");
    menu.appendChild(style);
    style.innerText = `
    .monaco-menu-container {
      ${css_selectors},
      .visible.scrollbar.vertical, .shadow {
        display: none !important;
      }
    }
    `;

    // fix context menu position
    if (menu.matches(".monaco-submenu")) {
      return;
    }
    let menu_top = parseInt(menu.style.top);
    const menu_height = menu.clientHeight;
    // console.log("menu_top", menu_top, "menu_height", menu_height);
    const titlebar_height = 40;
    const window_height = window.innerHeight;
    if (menu_top < titlebar_height && menu_height < 90) {
      mouse_y = menu_top;
    } else {
      if (mouse_y < window_height / 2) {
        menu_top = mouse_y;
        if (menu_top + menu_height > window_height) {
          menu_top = window_height - menu_height;
        }
      } else {
        menu_top = mouse_y - menu_height;
        if (menu_top < titlebar_height) {
          menu_top = titlebar_height;
        }
      }
      menu.style.top = menu_top + "px";
    }
  }
})();

```

**Comment by Delapouite** [comment]
Work is under way to clean the context menu https://github.com/microsoft/vscode/issues/225411

**Comment by BHznJNs** [comment]
@Long0x0 Thank you for your code snippet, I made an extension that used it and can partially make the contextmenu cleaner: https://github.com/BHznJNs/vscode-custom-contextmenu
