### ISSUE TITLE
Documentation for running a Cygwin shell causes build to fail

### ISSUE THREAD

**Issue by Ben-Voris** [microsoft/vscode#75945]
Following the instructions for setting "terminal.integrated.shellArgs.windows" given at https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cygwins-shell-with-the-terminal-on-windows 
causes `run build task` using Cygwin to fail with: 
```
cygpath: option requires an argument -- c
Try `cygpath --help' for more information.
```

A task window opens and shows a bash prompt. `make` runs correctly at that
prompt.

`run build task` correctly runs Cygwin make after removing 
`"terminal.integrated.shellArgs.windows"`.

[Using Cygwin Shell](https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cygwins-shell-with-the-terminal-on-windows) says:
> add the following settings to your settings.json file:
>> `"terminal.integrated.shell.windows": "C:\\Cygwin\\bin\\bash.exe",`
>> `"terminal.integrated.shellArgs.windows": ["/bin/xhere", "/bin/bash"]`

xhere takes one or two arguments: a program to start and an optional 
directory to make the cwd before starting the given program.

This problem occurs because, when executing `run build task`, VS Code 
passes three arguments: the Cygwin path name of the Windows path given in 
`"terminal.integrated.shell.windows"`, a literal `-c`, and , as one 
argument, the value of "command" and the "args" array from tasks.json. For 
example, when running all from this tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "all",
            "type": "shell",
            "command": "C:/cygwin64/bin/make.exe",
            "args": [
                "all"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}
```

arg 1: /bin/bash
arg 2: -c
arg 3: C:/cygwin64/bin/make.exe all

It appears that VS Code changes the current work directory before starting
 `"terminal.integrated.shell.windows"` which would make xhere unnecessary. If 
that is so, the fix would be to change the text of 
https://code.visualstudio.com/docs/editor/integrated-terminal#_can-i-use-cygwins-shell-with-the-terminal-on-windows 
to say that `"terminal.integrated.shellArgs.windows"` need not be set, 
along with a warning that it must not contain `-l` or `--login` as they 
reset the cwd to the user's home directory. 

```
Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299
```

Problem occurs with all extensions disabled. 

If I clear "Dev Tools Console" before `run build task`, it displays nothing
new after running `run build task`.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
remote-containers|ms-|0.59.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0-insiders
rewrap|stk|1.9.1

</details>

**Comment by Tyriar** [comment]
You're right, it looks like cygwin just works without the args stuff now. Because of this I think we should just expose it in the default shell selector now using the standard install paths instead of having the FAQ.

**Comment by Tyriar** [comment]
<img width="475" alt="Screen Shot 2019-06-27 at 8 34 03 AM" src="https://user-images.githubusercontent.com/2193314/60279711-6c4d8400-98b6-11e9-902b-aa7d1f4e8909.png">

**Comment by alexr00** [comment]
It looks like there is still some additional setup needed. I can't just change the shell to cygwin:
<img width="701" alt="cygwin" src="https://user-images.githubusercontent.com/38270282/62222937-74687a00-b3b4-11e9-844d-d17b5fd59332.png">

**Comment by Tyriar** [comment]
Removing cygwin detection for now, it looks like it needs needs args which is an area the shell detector doesn't touch yet. The old instructions don't seem to work, something must have changed in cygwin https://www.fesevur.com/2017/11/cygwin-terminal-in-vscode.html

Hoping someone in the community will put together some instructions that we can update the documentation with. I'll remove the doc entry completely for the time being.
