### ISSUE TITLE
Settings panel unusable with notebook trackpad

### ISSUE THREAD

**Issue by renevaessen** [microsoft/vscode#75942]
The settings panel is unusable on a small screen laptop without external mouse.

Why?

The only way to see all settings on a configuration-section, scrolling is required due to the small screen.

But this is only possible by dragging the very small indicator/handlebar of the vertical-scrollbar using the trackpad of the notebook.

And this is moving way to fast due to the scrollabe pagesize.

I tried clicking in the scrollable area and then use my cursor keys on the keyboard,
unfortunately this is not working..

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/66237
