### ISSUE TITLE
Allow inputs in launch task to set args array

### ISSUE THREAD

**Issue by thomasgassmann** [microsoft/vscode#75944]
As far as I know, it is currently not possible to specify the `args` property of a launch task via its input.
For example, I have the following `launch.json`:
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Terminal",
            "type": "python",
            "request": "launch",
            "pythonPath": "${workspaceRoot}/.venv/bin/python",
            "module": "mymodule",
            "stopOnEntry": true,
            "console": "integratedTerminal",
            "args": [
                "${input:args}"
            ],
            "cwd": "${workspaceFolder}"
        }
    ],
    "inputs": [
        {
            "id": "args",
            "type": "command",
            "command": "Command line args for debugging"
        }
    ]
}
```
Yet if I have a more complex CLI I want to debug, there's no way of specifying multiple arguments. I've also tried having a separate input for each argument, but that doesn't seem like a clean solution either, because the number of arguments could easily change depending on the command that's being executed.

I see two ways how this issue could be approached:

- add a new input type `promptArray`, which would allow me to directly set the `args` property
- add another property to the launch configurations, which would allow setting the `args` as a string instead of an array (e.g. something like `argsString`)

**Comment by weinand** [comment]
The "input variable" mechanism is based on string substitution in strings, e.g. `"foo ${input:args} bar"`. I do not see how the resulting string can expand into an array (e.g. "args").

But you could try the following: instead of passing the arguments via "args" you could use an input variable as part of another attribute. E.g. something like this:
```
{
            "name": "Python: Terminal",
            "type": "python",
            "request": "launch",
            "pythonPath": "${workspaceRoot}/.venv/bin/python",
            "module": "mymodule ${input:args}",
            "stopOnEntry": true,
            "console": "integratedTerminal",
            "cwd": "${workspaceFolder}"
        }
```
I've removed "args" and added the input variable to "module" attribute...
I don't know whether this makes sense but I hope you get the idea.

**Comment by thomasgassmann** [comment]
@weinand I have tried to use the input variable as part of another attribute (`module` doesn't work too in this case, because it needs to match the module name exactly).

> The "input variable" mechanism is based on string substitution in strings, e.g. "foo ${input:args} bar". I do not see how the resulting string can expand into an array (e.g. "args").

So what about the other way I mentioned in the feature request:

> add another property to the launch configurations, which would allow setting the args as a string instead of an array (e.g. something like argsString)

...or do you rather see this as an issue with the Python extension and suggest to open an issue there?

**Comment by weinand** [comment]
Yes, adding another property to the launch config can only be done via the extension. So please file the issue against the Python extension.

**Comment by petermorlion** [comment]
I'm wondering if there's a chance to reconsider this? I think it would be valuable and it's not Python (extension) specific. You could imagine a CLI application in another language (.NET, TypeScript,...) where you want to debug and let the developer pass in an array of arguments.

Something like "promptArray" could work:

- promptString: `foo bar` leads to "foo\ bar" being passed to the application, i.e. a single argument that the application would receive as `foo bar`.
- promptArray: `foo bar` leads to two argmuents being passed, i.e. `foo` and `bar`

**Comment by petermorlion** [comment]
Apparently, this isn't a popular change (see [here](https://github.com/microsoft/vscode/issues/224859)). Would a PR be acceptable, or does every PR need to be matched to an accepted issue?

**Comment by phischdev** [comment]
Which seems crazy, regarding the speedup that could be achieved with this kind of workflow while debugging.
