### ISSUE TITLE
Git source control fails for wsl 9P location

### ISSUE THREAD

**Issue by Morgy93** [microsoft/vscode#75941]
- VSCode Version: 1.35.1
- OS Version: Microsoft Windows [Version 10.0.18362.175]

Steps to Reproduce:

1. Open some `\\wsl$\{distro}` path
2. `git init`
3. Open with vscode
4. See source control failing 
![image](https://user-images.githubusercontent.com/7961978/59965416-f049e980-950d-11e9-8a3a-b4bf3d9bc42f.png)

For bigger git repos it looks funny, because it tries to do something, but then just fails.
(I'm currently unable to post a gif, because I am to slow to record ... 😒 )

Does this issue occur when all extensions are disabled?: Yes

**Comment by Morgy93** [comment]
After submitting I found out about the git output window and it seems that the git integration runs with cmd.exe in the background.
Which of course doesn't support UNC paths 😭 

Is there any known workaround to this?
Else we may just close this one. 😞

**Comment by joaomoreno** [comment]
WSL is only supported using Remote: https://code.visualstudio.com/docs/remote/wsl
