### ISSUE TITLE
code helper process takes a lot of cpu power in my mac book pro 2015 13'  

### ISSUE THREAD

**Issue by amanix007** [microsoft/vscode#75940]
Issue Type: <b>Performance Issue</b>

cwd
/
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/Library/Preferences/Logging/.plist-cache.7aOT0fn9
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
txt
/usr/lib/dyld
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/usr/share/icu/icudt62l.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
0
->0x8062b0228c667be1
1
->0x8062b0228c668091
2
->0x8062b0228c667d71
3
->0x8062b0228c6686d1
4
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
5
count=0, state=0xa
6
->0x8062b022a2801ab9
7
->0x8062b022a28037f9
8
->0x8062b022a2801279
9
->0x8062b022a28022f9
10
->0x8062b022a2802779
11
->0x8062b022a28025f9
12
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
13
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
14
count=0, state=0xa
15
->0x8062b022a28013f9
16
->0x8062b022a28011b9
17
/dev/urandom
18
/dev/null
19
->0x8062b02297675411
34
/Users/hello/Library/Application Support/Code/User/settings.json
41
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    49	 80921	code main
    8	    49	 80923	   gpu-process
    1	    49	 80933	   shared-process
   13	   492	 91535	   window (StaticComponent.jsx — page-bulb-react)
    3	   492	 91537	     extensionHost
   73	   918	 91542	       electron_node tsserver.js 
    0	    33	 91560	         electron_node typingsInstaller.js typesMap.js 
    0	     0	 91686	       electron_node server.js 
    0	     0	 91687	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=91537
    0	     0	 94879	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=91537
    0	     0	 96658	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=91537
    0	     0	 91538	     watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (StaticComponent.jsx — page-react)
|    Folder (page-bulb-react): 273 files
|      File types: png(140) jpg(27) jsx(25) scss(20) js(17) DS_Store(11)
|                  svg(10) json(6) css(5) ico(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-class-suggestions|And|1.0.7
tinypng|and|0.2.0
jsonviewer|cci|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
jsx-path-refactor|Den|0.0.1
gitlens|eam|9.8.2
vscode-todo-plus|fab|4.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
auto-run-command|gab|1.5.0
rest-client|hum|0.21.3
vscode-colorize|kam|0.8.10
scss-refactoring|luk|0.1.4
code-beautifier|mic|2.2.1
vscode-wrap-console-log|mid|1.7.2
vscode-scss|mrm|0.6.2
vscode-docker|ms-|0.6.4
python|ms-|2019.5.18875
JavaScriptSnippets|nat|0.2.0
vscode-json-editor|nic|0.2.3
vscode-extension-auto-import|Nuc|1.4.3
indent-rainbow|ode|7.4.0
code-settings-sync|Sha|3.2.9
indenticator|Sir|0.6.0
highlight-matching-tag|vin|0.9.2
vscode-icons|vsc|8.7.0
gitblame|wad|2.8.1
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
