### ISSUE TITLE
the Outline json boolean icon: make it more clear and informative

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#75943]
![telegram-cloud-photo-size-2-5219784569736244186-x](https://user-images.githubusercontent.com/6201068/59968219-f99f7a00-953e-11e9-9629-94082319fdad.jpg)

Actual checked/unchecked checkbox icon would be more clear and informative

Something like this:
e.g. `"private": true`
![image](https://user-images.githubusercontent.com/6201068/59968287-ea6cfc00-953f-11e9-812f-b83c91b39cb2.png)

**Comment by a-x-** [comment]
Current icon: [BooleanData_16x.svg](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/documentSymbols/media/BooleanData_16x.svg)

**Comment by a-x-** [comment]
I'm gonna make it

**Comment by a-x-** [comment]
UPD. Checkbox icon should be styled as disabled (in gray colors), so user will not expect it's clickable

**Comment by misolori** [comment]
@a-x- thanks for the feedback, the icon is suppose to imply the two states. The checkbox idea wouldn't work as that is known as an interactive element while these are static icons.

**Comment by a-x-** [comment]
I addressed this problem [here](https://github.com/microsoft/vscode/issues/75943#issuecomment-504698389):

> Checkbox icon should be styled as disabled (in gray colors), so user will not expect it's clickable

**Comment by misolori** [comment]
@a-x- sorry but a disabled checkbox still implies that it is interactive and won't work (also an anti-pattern).

**Comment by a-x-** [comment]
I'm not think so, disabled items are not interactive

but, okaaay...

**Comment by a-x-** [comment]
Hm, what if gray-filled square with “1” digit for “true”
and outlined square labeled with “0” digit for “false”
?
That’s might be informative and clear I hope
