### ISSUE TITLE
Triple slash reference should include extension '.d.ts' or not?

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode#7594]
`/// <reference path='../../../typings/index.d.ts' />`

or 

`/// <reference path='../../../typings/index' />`

?

Thanks!

tsc recognizes the file without .d.ts extension, but vscode's ts validation has a different behavior.
This makes a headache communication between typescript coder.

<img width="355" alt="2016-06-13 02 25 22" src="https://cloud.githubusercontent.com/assets/1777562/15998322/fa52bdb2-316f-11e6-84a8-6de7cc0316dc.png">

**Comment by dbaeumer** [comment]
Moving to the TS team since the error is generated by the tsserver. I have no idea what makes the difference between tsserver and tsc here.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9116
