### ISSUE TITLE
terminal.integrated.shellArgs.windows does not query file paths properly when using enviroment variables

### ISSUE THREAD

**Issue by Dreamurrrr** [microsoft/vscode#75948]
Note: This issue is similar to bug #65817, though it lacks details, clear examples, and talks about different environment variables in different syntaxes.
Edit: I just noticed that issue (#65817) is marked as a feature request, not a bug. I am filing a bug report.
Edit 2: This issue is similar to bug #57452, however, it is from a older version of VS Code and the issue is locked.

- VSCode Version: 1.35.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install Visual Studio Community 2017 
2. Open settings.json in Visual Studio Code
3. Insert the following code:
```
{
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k", "%ProgramFiles(x86)%\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\VsDevCmd.bat"
    ]
}
```
4. The following error will appear: `'C:\Program' is not recognized as an internal or external command, operable program or batch file.`
![lYvJ4fz1](https://user-images.githubusercontent.com/21233238/59970850-c2789b00-9535-11e9-8404-35e65abb61d2.png)
![EiAjiqAx](https://user-images.githubusercontent.com/21233238/59970871-4cc0ff00-9536-11e9-84d3-dc5eaba0883a.png)

If I replace the environment variable `%ProgramFiles(x86)%` with `C:\\Program Files (x86)\\`, then it works after pressing enter once in the terminal:
```
{
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k", "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\VsDevCmd.bat"
    ]
}
```
![aouePYbh](https://user-images.githubusercontent.com/21233238/59970861-15525280-9536-11e9-926a-87d9a82f7935.png)

I didn't test if it worked with an environment variable without a space in it.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, the issue still occurs after disabling all extensions.
Additionally, this is a fresh install of VS Code, so the likelihood of external interference is extremely low.

**Comment by Tyriar** [comment]
This is https://github.com/microsoft/vscode/issues/65817 as the syntax that would be used is `${env:VAR}` as that's the standard vscode uses for various settings.
