### ISSUE TITLE
More standard Fedora install via dnf config-manager

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#75954]
Instead of having to copy-paste this
```
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
```
it's more simpler/standard to use this
```
dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/vscode.repo
```
This requires you to create the vscode.repo somewhere.

Thanks!

Source: https://code.visualstudio.com/docs/setup/linux

**Comment by Tyriar** [comment]
I'm not sure it's time to move to exclusively use dnf as some distros might still only have yum?
