### ISSUE TITLE
Extension not reloaded & working

### ISSUE THREAD

**Issue by Jayvirrathi** [microsoft/vscode#75952]
When vscode insiders is updated then it dont work properly.
No extension are working.vscode insiders is not reloaded when any extension is added or removed.So all extension dont load.Not working Properly as extension are not loaded.

**Comment by sandy081** [comment]
Please check following and provide necessary info

- Run command `Developer: Running Extensions` and see what extensions are running
- Open Developer tools and check if there are any errors in the console
- Open Output panel and open the logs and see if there are any errors in Window, Shared Process & Extension Host Logs
