### ISSUE TITLE
no figcaption suggestion 

### ISSUE THREAD

**Issue by targboss** [microsoft/vscode#75958]
Issue Type: <b>Bug</b>

when i write the first word of any html element start with the same word except 'figcation' element like it deosn't exist !

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

**Comment by sandy081** [comment]
1. Please provide steps to reproduce the issue. 
2. Also try reproducing the issue by disabling all installed extensions
