### ISSUE TITLE
Open multiple workspace each with their own them/color/fonts

### ISSUE THREAD

**Issue by rohita77** [microsoft/vscode#75953]
Some time we need to  open multiple projects to work in parallel and cross reference code. Each project can be opened in different instance/workspace of VS Code. However, we can select different theme for different windows of VS code. This simple feature can make working with multiple projects extremely seam less

**Comment by sandy081** [comment]
@rohita77 Do you mean changing the theme in the same window based on the file opened?

**Comment by rohita77** [comment]
Having 2 different windows open with different branches/projects. If each
window has it own color/theme, developer can easily distinguish which
project / version he is using

**Comment by sandy081** [comment]
This can be done by setting the theme in workspace settings. Is not this working for you?

**Comment by rohita77** [comment]
It doesn't work. When you open two workspaces simultaneously both get the same color them

**Comment by sandy081** [comment]
Can you please show the workspace settings of both workspaces with the theme value?
