### ISSUE TITLE
Integrated Terminal couldnot display chinese character

### ISSUE THREAD

**Issue by cdyue** [Microsoft/vscode#7595]
- VSCode Version:1.2.0
- OS Version:OS X 10.11.5

Integrated Terminal couldnot display chinese character.
![111](https://cloud.githubusercontent.com/assets/7218849/15998453/0ecee5a8-3171-11e6-9942-c5120bc0707b.png)

It should be like this:
![222](https://cloud.githubusercontent.com/assets/7218849/15998556/cc0bdbd0-3171-11e6-889c-982cbf947bfb.png)

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7062
