### ISSUE TITLE
Code-Insiders - Upon selecting "Open Folder", prompt if you would like to open new window.

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode#75963]
Hello,  
Just a simple suggestion, upon selecting "Open Folder", it would be nice if it could prompt if you would like to open the folder in a new window or the same window instead of straight away attempting to open it within your currently open window.

Thanks,
-MH

**Comment by isidorn** [comment]
Thanks for the suggestion. However always prompting would be a pain. 
Thus we have settings, more about that can be foudn here
https://github.com/microsoft/vscode/issues/371
