### ISSUE TITLE
Breadcrumbs doesn't filter on type until clicking on the tree TypeFilterController

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#75969]
Steps to Reproduce:

1. Launch or reload vscode 
2. Set `"workbench.list.keyboardNavigation": "filter"`
3. Open a breadcrumb and start typing to filter the contents => contents are not filtered
4. Click two times on the tree TypeFilterController (to deactivate and activate filtering again) on the top right of the breadcrumb.
5. Contents are filtered from now on until reload of vscode.

Related to #55004

![breadcrumbsfilter](https://user-images.githubusercontent.com/25115070/60073431-14602300-96e6-11e9-9534-074e59465763.gif)

**Comment by jrieken** [comment]
I cannot reproduce with the provided steps. Please update

**Comment by jeanp413** [comment]
I can repro easily with the provided steps. I'm on ubuntu 18.04. Attached gif to the initial post.
