### ISSUE TITLE
Automatic panel position on window resize

### ISSUE THREAD

**Issue by hektormisplon** [microsoft/vscode#75960]
It would be great to have an option to be able to automatically move/hide the panel location on window resize. I like to use my panel on the right side, but when I resize my window to half the width of my screen it would be nice if the panel automatically moved to the bottom of the editor. 

(Not sure if there is already some extension available for this)

**Comment by isidorn** [comment]
There is no extension available for this, since we do not explose windows size to extensions.
Leaving open as a feature request, though I do not think we will do this since nowhere in the UX do we have automaticing hiding / closing of parts based on overall window size.

**Comment by niklasmh** [comment]
Are there any workarounds for this now? I feel like I stumble on this problem every now and then. I would only like the Panel to move to bottom when it does not make sense to have it on the side - e.g. when I change from fullscreen to split-screen.

**Comment by vaaski** [comment]
I wonder why more people aren't running into this. Depending on what I'm doing, I either use vscode maximized or split-screen with some other window next to it. When I use it maximized, I have plenty horizontal space to fit 90 columns of code and the panel side-by-side onto my screen, however when I use it in split-screen, there's practically no space at all left for the code editor, which can be solved by moving the panel to the bottom. 

I run into this very frequently, and I also investigated building an extension to solve this, which as @isidorn mentioned, is most likely impossible. One way this could maybe be done is using [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css), but I haven't had the time to look into it yet. It also seems like a pretty hacky workaround.

Is there any better way by now?
