### ISSUE TITLE
Source Controll Providers limited to 11 GIT submodules.

### ISSUE THREAD

**Issue by rutkowskimarek** [microsoft/vscode#75961]
![image](https://user-images.githubusercontent.com/17942515/59979521-4dff3400-95e9-11e9-9d53-a19ad167fb4e.png)

Issue Type: <b>Bug</b>

(I report this issues second time) **Source Control Providers display just first 11 GIT submodules** - and ignore if there is more (I have 12 git submodules in super project - yes not common scenario but I need it, and need more - I think there may be up to 32 submodules - every hardware platform is keeped in its own repo - reusable). I changed options - and it always just 11 - not cliping (I use 0 vale and manualy changed height of my window). 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.28.0
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.7
latex-workshop|Jam|7.0.2
vscode-nuget-package-manager|jmr|1.1.6
vscode-docker|ms-|0.6.4
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
debugger-for-chrome|msj|4.11.5
vscode-docker-registry-explorer|Tqr|0.1.3
vscode-icons|vsc|8.7.0

</details>

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/60080235-c6700d00-972f-11e9-8e67-9cd0291739df.png)

Setting is `git.detectSubmodulesLimit`
