### ISSUE TITLE
Feature for a back button/command when you are moving across function definitions in classes

### ISSUE THREAD

**Issue by abhyudayasrinet** [microsoft/vscode#75968]
I'm not sure if this has been requested.

A lot of times when I'm reviewing code, I'm moving across function definitions to see the flow of code and it would be easier to quickly go back as well since it's easy to go to the function definitions but I couldn't find a command to go back where I came from.

**Comment by sandy081** [comment]
Did you try following commands?

![image](https://user-images.githubusercontent.com/10746682/60027170-3e412780-969d-11e9-8885-ae1e433f5781.png)
