### ISSUE TITLE
Getting popup when I open a Dockerfile

### ISSUE THREAD

**Issue by erihanse** [microsoft/vscode#75966]
Issue Type: <b>Bug</b>

Whenever I open a Dockerfile, I'm getting
> The 'Docker' extension is recommended for this file type.

even though I have the Docker extension installed. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-52-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2728)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.12GB (14.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.2
vscode-groovy|Arg|0.0.1
vscode-django|bat|0.19.0
vagrant|bbe|0.5.0
markdown-checkbox|bie|0.1.3
npm-intellisense|chr|1.3.0
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
vscode-npm-script|eg2|0.3.7
vs-code-http-server-and-html-preview|Fli|2.2.2
vscode-pull-request-github|Git|0.8.0
gc-excelviewer|Gra|2.1.32
rest-client|hum|0.21.3
jenkins-pipeline-linter-connector|jan|1.1.7
vscode-sbt-scala|lig|0.2.4
MagicPython|mag|1.1.0
VS-code-vagrantfile|mar|0.0.7
Kotlin|mat|1.7.0
vscode-docker|ms-|0.6.4
vscode-kubernetes-tools|ms-|1.0.1
python|ms-|2019.5.18875
Go|ms-|0.11.0
debugger-for-chrome|msj|4.11.5
vscode-paste-image|mus|1.0.4
autodocstring|njp|0.3.0
vetur|oct|0.21.0
vscode-spring-boot|Piv|1.8.0
ruby|reb|0.23.0
java|red|0.46.0
vscode-yaml|red|0.4.1
python-template-snippets|Ric|1.0.0
bash-debug|rog|0.3.5
scala|sca|0.3.2
metals|sca|1.4.3
jenkinsfile-support|sec|0.1.0
vscode-hexdump|sle|1.7.2
json2yaml|tux|0.2.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5
vscode-icons|vsc|8.7.0
vim|vsc|1.8.1
vscode-ansible|vsc|0.5.2
jinja|who|0.0.8
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by chrisdias** [comment]
This is fixed in Insiders and will be rolled out in Stable this week.
