### ISSUE TITLE
Integrated Terminal  ERROR

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#7596]
- VSCode Version: 1.3.0
- OS Version: Win10 

Steps to Reproduce:

1.  Today, I updated！
2. open Integrated Terminal from menu,will show the follow error,but I can open it by  Shortcut key.

![2](https://cloud.githubusercontent.com/assets/8591065/15999306/5708e944-3177-11e6-9952-58212d851dc0.png)

the automatic update caused？

**Comment by bgse** [comment]
Seeing this as well in current insider build:

![code_terminal](https://cloud.githubusercontent.com/assets/8385202/16006249/3aff97da-316c-11e6-844f-0632118c9590.png)

**Comment by sandy081** [comment]
@Tyriar Me seeing this too. And I do not see the keyboard shortcut next to the Terminal label under views sections

**Comment by Tyriar** [comment]
@sandy081 I don't think this should be candidate, it was renamed in the insiders build. I can even change this back if it will cause too many issues.

**Comment by Tyriar** [comment]
Purpose of the rename was purely for consistency

**Comment by sandy081** [comment]
@Tyriar I was confused about the recovery build and hence marked it as a candidate.. Sorry for that.

**Comment by Tyriar** [comment]
No worries :smiley: I will probably change it back to `toggleTerminal` though. It's not worth the hassle for all the people who've rebound the keybinding.

**Comment by alexandrudima** [comment]
Verified by looking at the diff
