### ISSUE TITLE
Have contribution points for markdown extensions that are file specific

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#75965]
I'd like to add a bunch of extensions to the markdown preview (i.e. custom CSS, potentially my own plugins and a custom script), but not for the general markdown preview, but only for a custom file type. As far as I can tell, that is not possible right now? Is that something that could be added?

**Comment by mjbvz** [comment]
Can you share more information about the use case for this?

**Comment by davidanthoff** [comment]
Sure!

I maintain the [julia extension](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) and I'd like to use it there.

The scenario is that we have a custom file type with the ending `.jmd` (julia markdown). That format is a little bit like R markdown/notebooks, in that one can have julia code blocks in there, and then "weave" these docs, so that these code blocks run and the output of the code block gets inserted into the document that is generated from the jmd file.

Ideally I'd like to have a scenario where one can have the jmd file open in the text editor on the right, with the markdown preview for it on the left. And then one can run individual code cells on the left, and the preview on the right automatically inserts the output from the code runs into the preview.

I believe I could do all of this with the existing extension points in theory, but of course I a) only want that functionality for jmd files, not for generic md files, and b) I want this to _always_ happen for jmd files, so essentially I don't want other extensions to be able to add say another plugin, CSS or something like that for jmd files. And ideally I would want to reuse the markdown preview extension for this, and not copy-paste all the code in it over into our own extension. Plus, it would be nice if we didn't have to add a new command a la "Julia Markdown preview", but could just hook into the existing preview commands.

Let me know if this is unclear or you need more info!

**Comment by mjbvz** [comment]
Thanks. For your use case, you do want `.jmd` files to be treated essentially just like normal markdown files (but with these special contributions for the preview)? Essentially, does your extension set:

```json
	"files.associations": {
		"*.mjd": "markdown"
	}
```

to re-use our built-in markdown extensions features, or does it provide its own `julia markdown` language?

I ask because another way this could be implemented is exposing a `Show preview` api from the markdown extension. That would make sense if you define a separate language instead of reusing the default `markdown` one

**Comment by davidanthoff** [comment]
We define it as its own language with id `juliamarkdown`, that seemed generally safer and made it easier to for example have our language server support those files directly.

So I think your second suggestion probably makes most sense for us. For example an API a la your suggested `Show preview` that I can configure to use a certain number of markdown extensions or something like that.

**Comment by mjbvz** [comment]
Based on discussion, closing in favor of #75612
