### ISSUE TITLE
Rename symbol does not work in angular or vue templates

### ISSUE THREAD

**Issue by esteban03** [microsoft/vscode#75976]
When changing the name of a symbol with the tool to perform this operation the name is changed in all typescript files correctly. But when reviewing Angular html files or Vue the names used have not changed. This may not really be an error if not a functionality not covered for these frameworks even though it would be great to add it since completing the functionalities of these tools becomes indispensable.

- VSCode Version: 1.35.1 (1.35.1)
- OS Version: MacOs Mojave 10.14.5

Steps to Reproduce:

1. Use a project from Angular
2. Change symbol name by tool

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
We don't ship with built-in support for angular or vue. Please file this feature request against those extensions
