### ISSUE TITLE
Toggle Word Wrap

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#75970]
- vscode 1.35.1
- os Ubuntu x64 18.04

I've observed a minor issue with `Toggle Word Wrap`. It works, but the `tick` which is displayed for other 2-state items on the `View` menu (i.e. `Toggle minimap`) isn't displayed, i.e.it's unticked in either wrap or no-wrap mode.

This is relatively minor, but I suspect it also causes a slight annoyance - the `Toggle Word Wrap` state doesn't persist if I restart vscode, `Toggle Word Wrap` is always off regardless of the state it was in when I closed it.

**Comment by sbatten** [comment]
@rebornix I'd like to tackle this since every other entry uses checks now. Word wrap just needs to have a consistent state that can be used for the menubar
