### ISSUE TITLE
Visual Studio Code Crashes

### ISSUE THREAD

**Issue by angelasubi** [microsoft/vscode#75973]
when i use iterm2 run vscode will crashes!

my shell 

⫸  code .
[main 2019-06-24T03:31:57.156Z] update#setState idle
[main 2019-06-24T03:32:27.163Z] update#setState checking for updates
2019-06-24 11:32:27.168 code[77484:2922079] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/sattard/projects/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
fish: 'code .' terminated by signal SIGILL (Illegal instruction)

How can I solve this problem?

**Comment by angelasubi** [comment]
today i test in vscode
* start vscode
* when i use `⇧⌘P` and type 'shell command' to find the shell command : install 'code' in PATH.
* restart vscode,  code .  there will open vscode but now the iterm2 don't see a process (update#setData) message. 
* before i will see a error message and vscode crashes, but when i install 'code' command in PATH  iterm2 and vscode will ok

**Comment by joaomoreno** [comment]
Great. Installing code in the PATH with that command is our recommended way of getting Code in the path.
