### ISSUE TITLE
Show Navigation for Markdown in Outline

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#75974]
Issue Type: <b>Feature Request</b>

When Editing a markdown file or previewing, it would be nice to show the headings inside "Outline" on the sidebar, which when clicked on would jump to that location in the file or preview.

__This could double as a TOC index.__

VS Code version: Code - Exploration 1.35.0-exploration (1158b7573b3444493ff5ee8355ad23350d76596a, 2019-05-31T05:12:16.034Z)
OS version: Linux x64 4.15.0-52-generic

![md](https://user-images.githubusercontent.com/439226/59990598-b5c97500-9611-11e9-85c8-1edfa6efbf89.png)

**Comment by mjbvz** [comment]
@jrieken This is an interesting use case for the outline view, but I don't think our current apis would support it. The markdown preview is just a webview so is there any way to register a documentSymbolProvider for it?

**Comment by jrieken** [comment]
Everything is driven by the text editor and its models. Making this work against a higher level would be a lot of work

**Comment by zhongjiajie** [comment]
I just want to create an Issue like that. Support outline in preview could make author to check their file easier.
And some of the content have to test after render, like Markdown base blog or open source project docs. 
IMO, I think it a useful feature. If it could come true will be awesome.

**Comment by rajinder-yadav** [comment]
As I see it, the editor would just need to know it's a markdown file and really scan the file for six heading.
