### ISSUE TITLE
VSCode does not alert when extra blank space after EOF

### ISSUE THREAD

**Issue by dove-young** [microsoft/vscode#75972]
- VSCode Version: 1.35.1
- OS Version: macOS Mojave 10.14.5 

Steps to Reproduce:

1.  Create a shell script file
2. Paste a here document with extra blank space after EOF
```
!/bin/bash

cat > patch.yaml <<EOF
metadata:
  finalizers:
EOF  

echo this would never been executed. 
```
3.  Execute this script on Linux

```
bash vscode-issue.sh
vscode-issue.sh: line 9: warning: here-document at line 3 delimited by end-of-file (wanted `EOF')
```

On Emacs, `EOF  ` would be recognized and the line `echo this would never been executed. ` would be considered part of the here document.  Hens developer would notice there is type. 

But in VSCode, it is not recognized. And syntax errors leak from syntax highlight.

**Comment by dove-young** [comment]
On my Mac, the bash version is 
```
bash -version                                                                                    255
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

And on my Linux server, the bash version is 

```
bash -version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by sandy081** [comment]
@doivosev Are you using any extension in VS Code to run this script?
