### ISSUE TITLE
June 2019 Endgame

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#75985]
This is the endgame schedule for https://github.com/microsoft/vscode/issues/75103

## Schedule

* End game master: @jrieken / Zürich
* End game buddy: @rebornix / Redmond
* 06/24 Code freeze for the endgame
* 06/28 Endgame done
* 07/03 Expected release date (this may change)

> Note: The Insiders build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Monday 06/24
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) @jrieken
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Code freeze at **5pm PDT**
- [x] Ensure we have a green build on all platforms at 5pm PDT
- [x] All test items contain test meta data by **5pm PDT** and sufficiently comprehensive test descriptions by **8am CET**
- [x] Update your availability for testing here - https://vscode-tools.azurewebsites.net/
- [x] All closed feature-requests either have a verification-needed or on-testplan tag

##### Tuesday
- [x] Test plan items assigned (using https://vscode-tools.azurewebsites.net/)
  - Run the tool multiple times to balance load if test items come in later and assignments are already made
- [x] Testing
- [x] Verification for items with the `verification-needed`-label

##### Wednesday
- [x] Remind team members to assign issues that they intend to fix to the current milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22June+2019%22)
- [x] [Verification for remote](https://github.com/Microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Abug+-label%3Averified+-label%3Aon-testplan+is%3Aclosed+-label%3Aduplicate+-label%3A%2Aduplicate+-label%3Ainvalid+-label%3Aas-designed+-label%3Aerror-telemetry+milestone%3A%22June+2019%22)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] Verification for all items with the `bug`-label
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/README.md) and pass list of changed OSS usage (https://github.com/Microsoft/vscode-build-tools/blob/master/distro-tools/license/third_party_1.nn.0_diff.txt) to @isidorn for verification @jrieken 
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@octref**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [ ] node debug2 **@roblourens**
  - [x] node debugadapter node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
- [ ] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). ⚠️We are now doing release notes via **Git LFS**. Please read what this means here: https://github.com/Microsoft/vscode-docs/blob/vnext/README.md#git-lfs-setup⚠️
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [x] @chrmarti
  - [x] @dbaeumer
  - [ ] @deepak1556
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @rebornix
  - [x] @rmacfarlane
  - [ ] @roblourens
  - [ ] @sandy081
  - [ ] @sbatten
  - [x] @tyriar
  - [x] @weinand
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **@jrieken**
  - [x] vscode-node-debug **@weinand**
  - [ ] vscode-node-debug2 **@roblourens**
  - [x] vscode-debugadapter-node **@weinand**
  - [x] debug-adapter-protocol **@weinand**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [x] language-server-protocol **@dbaeumer**
  - [x] vscode-textmate **@alexandrudima**
  - [x] vscode-loader **@alexandrudima**
  - [x] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [x] vscode-docs **@gregvanl**
  - [x] vscode-css-languageservice **@aeschli**
  - [x] vscode-json-languageservice **@aeschli**
  - [x] vscode-html-languageservice **@aeschli**
  - [x] jsonc-parser **@aeschli**
  - [x] vscode-jscs **@chrisdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [x] vscode-jshint **@rmacfarlane**
  - [x] vscode-recipes @chrisdias 
  - [ ] localization **@shawndon**
  - [ ] vscode-github-issues-prs **@chrmarti**
  - [x] inno-updater **@joaomoreno**
- [ ] Review pull requests acknowledgements with `NOT MERGED - PLS REVIEW`. **@jrieken**
- [ ] Acknowledge issue trackers from the community **@chrmarti**
- [ ] Add notable fixes to the release notes **all**

##### Thursday/Friday
- When done fixing/verifying and there are changes since last build
 - [x] Trigger new insider build and publish it manually **@jrieken**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows 
  - [x] OS X 
  - [x] Linux 
- [x] Branch code to `release/<x.y>` (in vscode and vscode-distro) **@jrieken**
- [x] Bump up the version in package.json - **@jrieken**
- [x] Announce master is open for business **@jrieken**
- [ ] Polish release notes **redmond**

##### Monday - Wednesday
- [x] Polish release notes **redmond**
- [ ] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@rebornix**
- [ ] Build `Insider` from `release/<x.y>` **@rebornix**
- [ ] Manually release `Insider` **@rebornix**
- [ ] Build stable for all platforms as new candidate issues come in **@rebornix**
- [ ] Documentation updated
  - [x] @aeschli
  - [x] @alexandrudima
  - [x] @alexr00
  - [x] @bpasero
  - [ ] @chrmarti
  - [ ] @dbaeumer
  - [ ] @deepak1556
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @mjbvz
  - [x] @octref
  - [ ] @rebornix
  - [ ] @rmacfarlane
  - [ ] @roblourens
  - [ ] @sandy081
  - [ ] @sbatten
  - [ ] @tyriar
  - [x] @weinand

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Wednesday/Thursday
- [x] Build stable for all platforms **@jrieken**
- [x] Make [rpm signing request](https://github.com/Microsoft/vscode-distro/blob/master/linux-repo/README.md) **@RMacfarlane**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer 32-bit @dbaeumer 
    - [x] signed installer 64-bit @alexr00 
    - [x] signed user installer 32-bit @dbaeumer 
    - [x] signed user installer 64-bit @alexr00 
    - [x] zip 32-bit @dbaeumer 
    - [x] zip 64-bit @alexr00 
  - [x] OS X @isidorn 
  - [x] Linux @aeschli 
    - [x] deb package 64-bit
    - [x] rpm package 64-bit
    - [x] archive 64-bit
  - [x] Remote Extension Host @jrieken
- [x] Publish website **@gregvanl**
- [ ] Publish Localization language pack **@shawndon**
- [x] Publish to stable @octref 
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` (for vscode.d.ts download)  @octref 
- [x] Publish `@types/vscode@<x.y>` @octref 
- [x] Publish rpm to repository manually **@RMacfarlane**
- [x] Enable scheduled `insider` builds @octref 
- [x] Twitter announcement @chrisdias

**Comment by octref** [comment]
Shipped.
