### ISSUE TITLE
Gulp watch crashed

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7598]
I believe I checkout out to an old commit in which `monaco.d.ts` didn't exist. Can we try catch that?

![screen shot 2016-06-13 at 10 09 45](https://cloud.githubusercontent.com/assets/22350/16000840/020fa5d6-314f-11e6-912e-cfcf6fddc864.png)

**Comment by alexandrudima** [comment]
I don't think I understand. You have a `gulp watch` that you started on commit A and you want the same version of gulp watch from commit A to be able to compile arbitrary commit B from the past?

**Comment by joaomoreno** [comment]
Well, it appears to just have crashed the whole gulp at [this point](https://github.com/Microsoft/vscode/blob/master/build/monaco/api.ts#L40) when the file doesn't exist. It would be cool to just keep compilation running as usual when the file is missing... but I can live with killing gulp and launching it again. 👍
