### ISSUE TITLE
breadcrumbs in file explorer tree

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#75988]
On file explorer I usually see a lot of files in a lot of folders, So navigation is hard enough.
I have some cases which is difficult  to do in file explorer tree.
1) I need to know path to file (file is not the same as in editor view).  (it can be done by by hover mouse button over file, but it need additional movements by my hands, which is slow).
2) I need to quickly jump to for example Makefile/BUILD.gn/CMakelist.txt to parent, or grand parent directory.

I think navigation will be much simple if at the top of filetree in explorer view we can use breadcrumbs as in editor view.

As additional bonus, breadcrumbs can be editable like in windows 10 path line on file explorer. So when activate breadcrumbs line, you can type path with autocompletion hints.

**Comment by isidorn** [comment]
Leaving open as a feature request, pushing to backlog since we have no immediate plans to fix this.
fyi @jrieken
