### ISSUE TITLE
Backtick in TS comments not highlighted for //

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#75989]
![image](https://user-images.githubusercontent.com/4033249/60003317-48bcdc00-961f-11e9-8aae-e3f16abdc2d1.png)

Easily reproducible with:

```ts
/**
 * `foo`
 */
// `foo`
```

Version: 1.36.0-insider
Commit: 9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21
Date: 2019-06-21T05:18:36.348Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

**Comment by mjbvz** [comment]
We highlight markdown content in js/ts jsdoc block comments but not in normal comments
