### ISSUE TITLE
Focus search input field by keyboard

### ISSUE THREAD

**Issue by tdchien** [microsoft/vscode#75987]
Issue Type: <b>Feature Request</b>

How to focus input field by hotkey. It would be good if I could place the cursor on the input text (search keyword, file include, ...) with the keyboard. Similar to pressing Alt + a key combination underlined like window or menu bar
![image](https://user-images.githubusercontent.com/1614393/60001093-e18b4000-968f-11e9-8c31-55829e498fcb.png)
![image](https://user-images.githubusercontent.com/1614393/60001331-768e3900-9690-11e9-9728-00615cddde69.png)

Thanks

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.14393

**Comment by sandy081** [comment]
You can use following command/key binding

![image](https://user-images.githubusercontent.com/10746682/60026722-654b2980-969c-11e9-900b-e8882a2397a1.png)
