### ISSUE TITLE
Some file icons missing in Windows Explorer

### ISSUE THREAD

**Issue by BraisC** [microsoft/vscode#75993]
- VSCode Version: 1.35.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Install VS Code
2. Associate files to VS Code

Does this issue occur when all extensions are disabled?: Yes

And some icons are missing, like for example, icons for PHP or SQL files:
![Captura](https://user-images.githubusercontent.com/12214486/60005336-94e33d00-966e-11e9-8025-49028ef106e5.PNG)

**Comment by misolori** [comment]
This appears to be a Windows bug with file association (see #60716). I am on v1.35.1 and 1903 and am not able to reproduce:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/35271042/60031119-fd272400-9658-11e9-96fd-1d45c18fcac3.png">

FYI @joaomoreno not sure if you know of any workarounds/fixes
