### ISSUE TITLE
Java Extension Pack doesn't "see" the installed AdoptOpenJDK 

### ISSUE THREAD

**Issue by longtth** [microsoft/vscode#75998]
- VSCode Version: 1.35.1 
- OS Version: Microsoft Windows [Version 10.0.17134.829]

## Steps to Reproduce:

1. install Java Extension Pack  on an installed AdoptOpenJDK11 

Does this issue occur when all extensions are disabled?: N/A 

## Expected

1. Java Extension Pack auto-detect installed AdoptOpenJDK in PC 

image: 
![20190624_183148_Greenshot](https://user-images.githubusercontent.com/1010849/60008486-270b3580-96af-11e9-9d70-67f97542dc6b.jpg)

**Comment by sandy081** [comment]
Please file issue against the corresponding Java extension
