### ISSUE TITLE
Change color theme easily.

### ISSUE THREAD

**Issue by ShadyGaDa** [microsoft/vscode#75995]
Issue Type: <b>Feature Request</b>

Easily change color syntax/window theme without a long set of key shortcuts and edit manouvers.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.3.9600

**Comment by sandy081** [comment]
You can change theme using following ways

- 
![image](https://user-images.githubusercontent.com/10746682/60026464-e8b84b00-969b-11e9-93a2-ebd11955984d.png)

- 
![image](https://user-images.githubusercontent.com/10746682/60026500-f53ca380-969b-11e9-92f0-9ee8dd560a86.png)

- You can also use keyboard shortcuts

- 
![image](https://user-images.githubusercontent.com/10746682/60026556-0ab1cd80-969c-11e9-9b60-3b3fc62dbefc.png)

May I know what other easy way are you recommending?

**Comment by ShadyGaDa** [comment]
Only that after restart the theme always resets

**Comment by sandy081** [comment]
> Only that after restart the theme always resets

Can you please open your `settings.json` file and see if the theme setting is retained or not?

**Comment by ShadyGaDa** [comment]
The 'settings.json' or John Smith is a rather undefinable thing.
However 'storage.json' seems to update on close.
This issue is muddling and confusing.

**Comment by sandy081** [comment]
You can open the settings.json file from Settings editor

![image](https://user-images.githubusercontent.com/10746682/60105997-adce1a00-9764-11e9-9b3d-4ccf677fe3d9.png)


`{}` First button on the right.

Also, Can you please try to repro this by disabling all installed extensions?
