### ISSUE TITLE
Folding in comments

### ISSUE THREAD

**Issue by ShadyGaDa** [microsoft/vscode#75994]
Issue Type: <b>Feature Request</b>

There does not seem to be folding within block comments.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.3.9600

**Comment by aeschli** [comment]
Folding ranges are either provided by a language extension, or are based on indentation.
So the question is, in what language do you miss folding ranges in comments. If you use an extension for this language, we can assign this request to that language.
Please add a small code sample that shows what you would like to have.

**Comment by ShadyGaDa** [comment]
I found a discrepancy in JavaScript multi-line comments that would not fold when they should.
I guess this could be down to formatting.
I have noticed a possible addition of toggling 
/* 'proper' 
 * multi-line
*/ 
comments as a feature request.
That would be good.

**Comment by aeschli** [comment]
This looks correct to me:
![image](https://user-images.githubusercontent.com/6461412/64416968-78b14280-d098-11e9-89fd-60f3471493e5.png)
