### ISSUE TITLE
types can only be used in a .ts file Flow support

### ISSUE THREAD

**Issue by mballabaniapr** [microsoft/vscode#75996]
- VSCode Version:  1.35.1

Steps to Reproduce:

1. Open . a Flow type file

To fix this you need to disable Flow extension or disable Built in typescript extension but it will be poor use of js on this editor.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
To use Flow, install the [flow extension](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) and [follow these instructions](https://github.com/flowtype/flow-for-vscode#setup)
