### ISSUE TITLE
intellisense not showing and terminal is buggy

### ISSUE THREAD

**Issue by Alilat-imad** [microsoft/vscode#75997]
- VSCode Version: Latest stable version
- OS Version: windows 10

Recently I've noticed that the latest update that intellisense in some case not showing the adequate suggestion and i have to shut VS Code and rerun it again to get the intellisense suggestion, also when running clear in terminal, old runned command still showing.

**Comment by Tyriar** [comment]
Terminal issue: https://github.com/microsoft/vscode/issues/75141

@Alilat-imad what language?

**Comment by yoavniran** [comment]
had intellisense stop working on me 4 times in the last day and a half...

it would work fine and then it just stops and all i get is this:

![screenshot-20190627_130132](https://user-images.githubusercontent.com/1102278/60257378-ffe57b80-98db-11e9-9255-ea52ac2297d8.jpg)

restarting vscode restores it for a while but eventually it stops again.

windows 10, v: 1.35.1

path-intellisense | chr | 1.4.2
vscode-eslint | dba | 1.9.0
vscode-html-css | ecm | 0.2.0
auto-close-tag | for | 0.5.6
vscode-styled-components | jpo | 0.0.26
node-module-intellisense | lei | 1.5.0
vscode-graphql | Pri | 0.2.0
sass-indented | rob | 1.5.1
html-css-class-completion | Zig | 1.19.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, when it happens, please check the developer console for errors:

1. In VS Code, run `Developer: Toggle developer tools`
1. This should open a developer tools panel.
1. Open the console section of the developer tools and look for any errors or warnings

**Comment by mjbvz** [comment]
Closing this as more information is needed from the original poster

**Comment by yoavniran** [comment]
hey @mjbvz 

didnt have time to really dive into this but today ive been working again at home with vscode and after a few hours I do get the problem again.

here's the dev console log. 

[vscode-debug-1562234009611.log](https://github.com/microsoft/vscode/files/3358794/vscode-debug-1562234009611.log)

there were errors in it while intellisense was working. especially "TypeScript Server Error" (not coding in TS btw).

You can see towards the end it starts complaining about: "potential listener LEAK detected" 
dont know if its related...

didnt have time to investigate without extensions or with a different build.

**Comment by yoavniran** [comment]
btw, auto formatting (ex: on save)  stops working at the same time intellisense does
