### ISSUE TITLE
Bug: Right clicking in the editor triggers additional left-click action

### ISSUE THREAD

**Issue by nezorflame** [microsoft/vscode#75999]
I'm experiencing the issue which looks like #60119 which is supposed to be fixed.

Setup info from `Help - About`:

```
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.1.12-arch1-1-ARCH
```

Like the original issue, the problem exists only when the setting `"window.titleBarStyle"` is set to `"custom"`.

**Comment by sbatten** [comment]
@nezorflame can you provide a gif of your full vs code window and the behavior you are seeing?

**Comment by nezorflame** [comment]
@sbatten yup (all the actions are triggered just with a 1 right-click action)

![2019-06-25 17-52](https://user-images.githubusercontent.com/3906766/60108893-1079e280-9772-11e9-9aea-cb6d967670fa.gif)

**Comment by nezorflame** [comment]
From what I've experienced so far, it seems that right after the right-click action occurs, editor for some reason senses the left-click trigger, which makes it execute the action under the current mouse cursor position.

This is why sometimes it trigger Git compare, rename, reference search or nothing at all if I'm lucky.

**Comment by sbatten** [comment]
@joaomoreno We get these randomly all the time, I think I am just going to debounce the first click by 50ms or so

**Comment by joaomoreno** [comment]
Oh man, how is this to tricky to nail. Yeah let's do that.
