### ISSUE TITLE
Option to disable current line highlight

### ISSUE THREAD

**Issue by ThinnerSpinner** [Microsoft/vscode#760]
Whenever I place my cursor on a new line, VScode puts a border around it. Is there any way to shut the line bordering down?

**Comment by alexandrudima** [comment]
@ThinnerSpinner That is the current line highlight to help you find your cursor easily... Perhaps try another theme? Here's how it looks in Monokai:

We don't have any option to turn it off completely.

![image](https://cloud.githubusercontent.com/assets/5047891/11468716/01727eb0-9752-11e5-951f-ee5131d2faaa.png)

**Comment by mooflu** [comment]
I had a quick look. The css for current-line includes both background and a border. tmTheme files have control over the background color via lineHighlight. There appears to be no way to control the border width or color. 

Base css is in src/vs/editor/browser/widget/media/editor.css

Monokai which is based on vs-dark:

```
Monokai-tmTheme .current-line {
    background-color: rgba(62, 61, 50, 1);
}
.monaco-editor.vs-dark .current-line {
    background: none;
    border: 2px solid #282828;
    box-sizing: border-box;
}
```
Border might be important for high-contrast based themes, but maybe it can be set to none for the others.

**Comment by alexandrudima** [comment]
fyi @aeschli The border should only be shown in vs light / dark themes, not in other themes.

**Comment by aeschli** [comment]
@alexandrudima The high contrast theme no longer has a selection border.
This is how it looked in 0.10.10:
![image](https://cloud.githubusercontent.com/assets/6461412/13924099/4e2d90d0-ef83-11e5-951b-ee3b25e71a07.png)

**Comment by aeschli** [comment]
It's fine, it just doesn't show in the preview mode in the theme picker. It's because the color css only shows on focus.

**Comment by SteveTrewick** [comment]
Not sure why this is closed, there is still no option to disable line highlighting. Came to open an issue for this exact thing.

**Comment by noformnocontent** [comment]
`"editor.renderLineHighlight": "none"`, or `"editor.renderLineHighlight": "gutter"`

**Comment by allexon** [comment]
Hello, I'm using vscode a little while, really cool, now if anyone can help me with a situation. The visual code put some white borders in markup tags like [(<{.... these edges are annoying these edges, does anyone know how I do to remove them, see the image as an example
![bordas](https://cloud.githubusercontent.com/assets/1206288/23331730/830513ae-fb4a-11e6-8ec2-00f555a21e3b.jpg)

**Comment by noformnocontent** [comment]
@allexon in settings:

    "editor.matchBrackets": false

**Comment by allexon** [comment]
Obrigado, eu já consegui, antes eu tinha tentado, a opção:  "editor.matchBrackets": false, mas nesta opção o VSCODE não reconhece o nome machBrackets, agora este nome ajudou quando eu em outra dica localizar o arquivo: workbench.main.css, dentro deste arquivo eu localizei o nome math brackets, onde tinha border eu coloquei none, e funcionou!!!

**Comment by alexandrudima** [comment]
@allexon The setting `editor.matchBrackets` will be available in the next VS Code stable release (due in ~ 1 week) or is already available today on the insiders channel.

**Comment by n370** [comment]
You might be also interested in ```"editor.renderLineHighlight": "none"```.

**Comment by unjx** [comment]
Adding to what @noformnocontent and @n370 have stated, there are a few more options on how you can render the line highlight.

From settings.json:
```
// Controls how the editor should render the current line highlight, 
// possibilities are 'none', 'gutter', 'line', and 'all'.
  "editor.renderLineHighlight": "gutter",
```

**Comment by scunliffe** [comment]
The line renders (on my install) as an ugly 2px border, what is the setting to adjust the border width and style? e.g. I'd love a very pale light blue background, with a slightly darker dotted/dashed 1px border. The width is the most critical part as this should be a very subtle visual clue, not 2px wide.
