### ISSUE TITLE
Unable to force tabs for Makefile

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#76000]
So there are existing issue but that didn't help me. VSCode is always preferring spaces in my Makefile. When I click in the bottom right to use tabs and switch to another file which uses spaces and go back to the makefile, VSCode is again using spaces instead of tabs. I expect VS Code to use only tabs and not to switch back to spaces when clicking between files that have different indention types.

Settings I apply:

```json
{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.detectIndentation": true,
  "[makefile]": {
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.detectIndentation": false
  }
}
```

- VSCode Version: 1.35.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Open a Makefile
2. Change spaces to tabs
3. Open a file e.g. test.js
4. Go back to Makefile 

Does this issue occur when all extensions are disabled?: Yes

**Comment by tdjastrzebski** [comment]
I second that. I just tried to create a simple makefile using my favorite tool - VS Code.
Makefile does not run. It turns out tabs have been substituted with spaces :/
VS Code 1.36.0 on Windows 10

**Comment by louisabraham** [comment]
I'm going to go even further and say VSCode *should* automatically use tabs for makefiles as spaces break them.

**Comment by gilescope** [comment]
Hitting this on 1.41.1 / win10. Unless I set detectIndentation to false it does the wrong thing. Detect indentiaton does the wrong thing at the moment. Please get makefiles right as there's lots of them out there.

**Comment by rebornix** [comment]
@gilescope sorry for reaching out late. I'm not able to reproduce this issue currently, can you please share a sample makefile which you can reproduce this bug?

**Comment by gilescope** [comment]
Alas I don't have the makefile in question any more. It was only a little one I made up with a few targets- wasn't anything fancy. Does the autodetection check the filename? a file called  makefile is highly likely to be one, unlikely to go wrong there.

**Comment by muuvmuuv** [comment]
Resolved I guess, haven't had it till now
