### ISSUE TITLE
Cannot logout from git account.

### ISSUE THREAD

**Issue by Premitium** [Microsoft/vscode#7600]
- VSCode Version:1.2.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

After initial setup, I misspelled my git password.
Now I cannot reset it from the editors git extention.

Is there a way to re-enter my credentials from the editor?

**Comment by joaomoreno** [comment]
Code doesn't remember credentials. If you are not being asked again, there is some credential manager in your git configuration that blocks it.
