### ISSUE TITLE
Regarding add stm32 l496rgt3

### ISSUE THREAD

**Issue by vishal2494** [microsoft/vscode#76003]
Issue Type: <b>Feature Request</b>

i want interface and debug stm32 l496rgt3 so this board is not added on platformIO please add this boards or give me step how to add custom  boards on PlatformIO

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T15:16:14.389Z)
OS version: Windows_NT ia32 10.0.17763

**Comment by sandy081** [comment]
Please file issue against the corresponding PlatformIO extension
