### ISSUE TITLE
Java Maven Dependencies

### ISSUE THREAD

**Issue by DoganM95** [microsoft/vscode#76004]
Issue Type: <b>Bug</b>

vscode almost never recognizes maven dependencies. it should just import maven dependencies from  pom.xml automatically. if this already happens, then i dont understand why my imports are underlined red. 
if i hoover on a maven dependency which i imported in a .java file, it shows me the class description of that import and seems to successfully have found and imported them, but is still underlined in red.

this seems to me like a bug, if it isn't it is just extremely annoying.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.2
angulardoc-vscode|Ang|6.1.3
hsm-post-processor|Aut|3.0.0
azds|azu|1.0.120190612
vagrant|bbe|0.5.0
devhints|brp|0.5.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.28.0
vscode-instant-markdown|dba|1.4.4
gitlens|eam|9.8.2
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
javac-linter|fau|1.3.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.11
shell-format|fox|6.0.1
todo-tree|Gru|0.0.135
beautify|Hoo|1.5.0
openchrome|hua|0.0.3
rest-client|hum|0.21.3
ibm-blockchain-platform|IBM|1.0.3
r|Iku|1.1.0
r-pack|Iku|0.0.2
google-complete-me|jay|1.0.6
vscode-sshfs|Kel|1.16.2
auto-comment-blocks|kev|1.0.1
electron-debug|kod|18.11.1
javascript-test-runner|leg|1.0.0
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|1.0.0
remotefs|lix|0.0.16
sftp|lix|1.12.7
VBScript|lug|0.0.2
terraform|mau|1.3.12
xml-format|mik|1.0.2
azure-pipelines|ms-|1.152.0
azurerm-vscode-tools|msa|0.6.0
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-azureterraform|ms-|0.2.4
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.6.4
vscode-kubernetes-tools|ms-|1.0.1
mssql|ms-|1.6.0
python|ms-|2019.5.18875
vscode-ai|ms-|0.5.1
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.8
vsliveshare|ms-|1.0.419
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.5
vscode-react-native|msj|0.9.3
gradle-language|nac|0.2.3
vetur|oct|0.21.0
openhab|ope|0.5.1
javascript-test-runner|osh|1.2.1
vscode-css-peek|pra|2.2.0
java|red|0.46.0
vscode-yaml|red|0.4.1
r-lsp|REd|0.1.0
vscode-sort-json|ric|1.13.0
sql-snippets|sad|0.0.4
code-settings-sync|Sha|3.2.9
html5-boilerplate|sid|1.0.3
vba|sky|2.8.0
java-generate-setters-getters|soh|4.2.2
vba|spe|1.2.0
vba-snippets|spe|1.0.1
code-spell-checker|str|1.7.17
pdf|tom|0.5.0
vscodeintellicode|Vis|1.1.7
azure-iot-edge|vsc|1.13.0
azure-iot-toolkit|vsc|2.7.0
azure-iot-tools|vsc|0.1.0
vscode-arduino|vsc|0.2.26
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-spring-initializr|vsc|0.4.5
vscode-ansible|vsc|0.5.2
markdown-all-in-one|yzh|2.4.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please file issue against the corresponding maven extension
