### ISSUE TITLE
Pie menus for vscode.

### ISSUE THREAD

**Issue by TheRealSyler** [microsoft/vscode#76017]
**Why are pie menus great and better than normal drop down menus ?**
Mainly because you can select commands faster then with drop down menus, and once you are used to them you don`t think about them, you just think about the thing that you want to do whereas with  drop down menus you have move the mouse exactly where the item is and then also press the left mouse button and with pie menus no more clicking just move the mouse and after a threshold you have selected the item which is why they are way faster and better than drop down menus.

**How do pie menus work?** 
when they get called they appear at the mouse position and you can select elements by moving the mouse in the direction of the item that you want to select, that is the basic concept.
![vscode pie menu example](https://user-images.githubusercontent.com/46901787/60024886-e9031700-9698-11e9-81d1-1927736df395.png)

its not a hard thing to implement but you can't do with an extension at least not to my knowledge, the reason why i didn't try to do this myself is because i got stuck before i could even start to program, i will probably waist my afternoon today trying to get vscode build from my pc, it has been  a while since i tried last time maybe im lucky, anyways if anyone has the will and free time to implement this, i can tell you what to do since i already created pie menus, some of the code could just be copypasted(from know on 'copypasted' is a word because i say so).

**Comment by usernamehw** [comment]
Looks similar to #70074
