### ISSUE TITLE
Executing task only starts terminal

### ISSUE THREAD

**Issue by BobLuursema** [microsoft/vscode#76015]
Issue Type: <b>Bug</b>

When I execute any task it only starts up a shell and it doesn't run the command. This even happens when I start a fresh new workspace and execute the default hello world task.

![image](https://user-images.githubusercontent.com/25150818/60027733-477ec400-969e-11e9-9b5b-7268336730d2.png)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (26.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vscode-edit-csv|jan|0.0.11
python|ms-|2019.5.18875
powershell|ms-|2019.5.0
vetur|oct|0.21.0
vscode-spring-boot|Piv|1.8.0
java|red|0.46.0
vscode-autohotkey|sle|0.2.2
pdf|tom|0.5.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1

</details>

**Comment by alexr00** [comment]
It's because you specified the shell. When you don't specify a shell, the tasks system passes the appropriate args to the shell. Since you don't pass any args to the shell it doesn't know to try to run the command. https://stackoverflow.com/questions/515309/what-does-cmd-c-mean
