### ISSUE TITLE
Integrated Terminal Scrolls 14 lines

### ISSUE THREAD

**Issue by DanJBower** [microsoft/vscode#76014]
Scrolling in the integrated terminal jumps 14 lines. This happens on the following integrated terminals; cmd, powershell and powershell core.

This is very similar to [Scrolling via mousewheel in the terminal scrolls by a lot on Windows (~12 lines) #35111](https://github.com/Microsoft/vscode/issues/35111). However, that reports that the jump is only 12 lines and it was fixed over a year ago. It was also referenced here, [Integrated terminal scrolls too fast using mouse wheel #47376](https://github.com/microsoft/vscode/issues/47376). However, that was also closed.

I came across the `"editor.mouseWheelScrollSensitivity": 0.5` setting, but that does not appear to affect the terminal.

Apologies if I missed any information out as this is my first time posting.

VSCode Version: 1.35.1
OS Version: 1903

Steps to Reproduce:
1) Open VSCode
2) Open the integrated terminal. Make sure it is a powershell terminal.
3) Run the command `for ($i=1; $i -le 100; $i++){echo Hello;}`
4) Scroll

Does this issue occur when all extensions are disabled?: Yes

**Comment by DanJBower** [comment]
I forgot to mention this is with an external mouse. My trackpad allows line by line scrolling so it is not an issue with the trackpad.

**Comment by Tyriar** [comment]
This is the section in the terminal lib that handles the wheel event, AFAICT it's doing the right thing:

https://github.com/xtermjs/xterm.js/blob/c50a6ef41539e6be1317c602e52b490878fdfac8/src/Viewport.ts#L165-L189

**Comment by DanJBower** [comment]
Yeah I guessed that editor setting wouldn't do anything but thought it was worth a shot. Looking at the code,

    else if (ev.deltaMode === WheelEvent.DOM_DELTA_PAGE) {
        amount *= this._currentRowHeight * this._terminal.rows;
    }

It appears that it does intend to jump the whole page in the terminal. But is this normal? In a terminal such as powershell or Windows command prompt, when I scroll normally, I would not expect it to jump a whole page. Normally I would expect it to jump about three lines. Is there any way I could configure it so the scroll jumps are not as big?

**Comment by Tyriar** [comment]
@DanJBower but that's only when the mouse wheel is configured set to jump a full page:

```
ev.deltaMode === WheelEvent.DOM_DELTA_PAGE
```

https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode

**Comment by DanJBower** [comment]
@Tyriar Thanks for the response. I looked up that setting and after a google search, I found this could be changed on my computer settings. However, when I opened the settings, I discovered my mouse was set to jump 3 lines at once. Which explains why CMD and Powershell normally jump three lines for me I guess.

![Screenshot 2019-06-28 07 47 56](https://user-images.githubusercontent.com/40743213/60323274-87cd9300-9979-11e9-965a-018552d7f7ae.png)

Does this mean that the integrated terminal in VSCode should also be jumping three lines for me?

**Comment by Tyriar** [comment]
Yes VS Code's terminal should be jumping 3 lines if those are you settings

**Comment by DanJBower** [comment]
But it isn't...?

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/1805

**Comment by DanJBower** [comment]
@Tyriar Thanks for the help
