### ISSUE TITLE
TreeView becomes invisible when sibling views are expanded

### ISSUE THREAD

**Issue by ak1394** [microsoft/vscode#76013]
- VSCode Version: 1.35.1
- OS Version: MacOS Mojave 10.14.5

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi&ssr=false#overview

2. Increase zoom level twice to make fonts bigger

3. Unzip xkcd-swagger.json and open it with VS Code.

4. Switch to "API" view with activity bar.

5. Collapse all the tree views (GENERAL, PATHS, PARAMETERS and so on)

6. Start expanding the collapsed tree views starting from the top one ("GENERAL")

7. By the time the DEFINITIONS view is expanded (depending on the screen size) tree views below it become invisible and there is no indication in the UI (for example a scrollbar) that there is anything hidden below.  See expanded/collapsed screenshots below. The expanded one shows an issue where tree views below "SECURITY" one are not visible.

[xkcd.zip](https://github.com/microsoft/vscode/files/3321088/xkcd.zip)

![collapsed](https://user-images.githubusercontent.com/148276/60024388-996c1d80-968f-11e9-98fe-11b3ac5e6805.png)

![expanded](https://user-images.githubusercontent.com/148276/60024396-9cffa480-968f-11e9-9063-76f31381921f.png)

**Comment by sandy081** [comment]
@joaomoreno Seems related to split view overflow?

**Comment by joaomoreno** [comment]
#64188
