### ISSUE TITLE
Code Helper crashes MacOS

### ISSUE THREAD

**Issue by gyorgynadaban** [microsoft/vscode#76018]
Issue Type: <b>Bug</b>

Having 4-5 Visual Studio Code windows open and attempting to complete a Time Machine backup crashes MacOS 10 out of 10.

No builds were running, no scripts in any open terminals either, all Visual Studio Code windows were sitting idly.

No CPU intensive processes were running, doesn't seem to be related to overheating.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 11, 9|
|Memory (System)|32.00GB (10.60GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-groovy|Arg|0.0.1
unique-lines|bib|1.0.0
xml|Dot|2.5.0
gitlens|eam|9.8.2
filter-line|eve|1.3.2
vscode-highlight|fab|1.3.4
vscode-guid|hea|1.4.15
jenkins-pipeline-linter-connector|jan|1.1.7
jenkins-declarative-support|jmM|0.1.0
svn-scm|joh|1.54.1
terraform|mau|1.3.12
change-string-case|max|1.1.1
hg|mrc|1.3.0
vscode-azureterraform|ms-|0.2.4
vscode-docker|ms-|0.6.4
vscode-kubernetes-tools|ms-|1.0.1
python|ms-|2019.5.18875
azure-account|ms-|0.8.4
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
Go|ms-|0.11.0
powershell|ms-|2019.5.0
sublime-keybindings|ms-|4.0.0
debugger-for-chrome|msj|4.11.5
language-vscode-javascript-angular2|nwa|0.0.11
vscode-yaml|red|0.4.1
jenkinsfile-support|sec|0.1.0
markdown-preview-enhanced|shd|0.4.2
vscode-ansible|vsc|0.5.2
HCL|who|0.0.5
jinja|who|0.0.8

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
