### ISSUE TITLE
Debugger overwrites file contents saved with :w - causes lost work

### ISSUE THREAD

**Issue by ReggieMarr** [microsoft/vscode#76019]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Write code
2. save with vim extension (\:w)
3. Run the debugger with the following \: 
        {
            "name": "Python: Current File start_work",
            "type": "python",
            "request": "launch",
            "args": ['example_arg'],
            "program": "${file}",
            "console": "integratedTerminal"
        }
4. Contents of all files interacted with the debugger is overwritten.

This is incredibly frustrating. I am not sure if all files were saved and this seems to be somewhat sporadic however I can reproduce when saving and then running the debugger.

**Comment by weinand** [comment]
What do you mean by "Contents of all files interacted with the debugger is overwritten."?
Please provide detailed steps.

**Comment by ReggieMarr** [comment]
The contents of all files interacted with in the debugger will be overwritten to whatever was saved several "saves" prior to running the debugger. It seems as though something is preventing from "real" saves from occuring. Will update with more detail once I've reproduced it again tomorrow.

**Comment by ReggieMarr** [comment]
@weinand have you been able to reproduce the issue ? This seems to be pretty reproducible on my end. Simply running the python debugger with args does the trick. 
As a recap the result is that files which are referenced during a debugger session seem to get overwritten to some previous state (usually the state that the file was in when vscode was opened). It also seem to actually be saving the file after doing this as I've noticed that the timestamp changes on the file. I have also tried opening the file after saving with VI to check that it is in fact saved properly (it is) and then I have tried saving it with VI but still the debugger seems to overwrite the file back to the state it was in when vscode was opened and then save the file, thus overwriting any changes.

**Comment by weinand** [comment]
Sorry I cannot reproduce and I do not understand what the problem is.
There is no functionality in VS Code that would support what you described above:
>  "The contents of all files interacted with in the debugger will be overwritten to whatever was saved several "saves" prior to running the debugger."

I suggest that you file the issue against the Python extension. Maybe they understand your problem.

**Comment by ReggieMarr** [comment]
> Sorry I cannot reproduce and I do not understand what the problem is.
> There is no functionality in VS Code that would support what you described above:
> 
> > "The contents of all files interacted with in the debugger will be overwritten to whatever was saved several "saves" prior to running the debugger."
> 
> I suggest that you file the issue against the Python extension. Maybe they understand your problem.

Alright will do, and just to clarify the bad behaviour was that after running the debugger any file which had breakpoints in it would have its contents overwritten such that any changes made since opening the file were reverted. The file would also save during the debugging session and there was no way to get the work back unless it had been backed up/pushed to git.

**Comment by weinand** [comment]
Are you editing python files outside of VS Code?

**Comment by ReggieMarr** [comment]
> Are you editing python files outside of VS Code?
> If yes, how is this done?

No I am editing the files in vscode. I tried editing with vim and then running the debugger in vscode and the files still end up being overwritten back to whatever was the state of the file when I first opened it with vscode. I also tried debugging with pdb and found I could only reproduce the issue with vscode running the debugger using the ms-python.python extension.

**Comment by weinand** [comment]
Since this seems to be an issue with the Python extension, I suggest that you discuss it with them.

**Comment by ReggieMarr** [comment]
> Since this seems to be an issue with the Python extension, I suggest that you discuss it with them.

I've now made the bug report with the extension used and have linked this ticket for reference.

**Comment by DonJayamanne** [comment]
@weinand VS Code saves the changes made to the file before the debugger starts. I.e. its not the extension that saves changes to the file.

**Comment by ReggieMarr** [comment]
> @weinand VS Code saves the changes made to the file before the debugger starts. I.e. its not the extension that saves changes to the file.

Right but why is it that the save seems to overwrite content recently saved to the file with whatever was in the file when it was first opened by vscode ?

**Comment by weinand** [comment]
Sure, VS Code saves files before starting the debugger because without that the debugger would be run on stale data. 
But how can saving files **overwrite** the contents to some older state? This is only possible if the files were changed outside of VS Code. But @ReggieMarr said that he "is editing the files in vscode" only.
