### ISSUE TITLE
Test: Raspberry Pi remote SSH

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76022]
Refs: https://github.com/Microsoft/vscode-remote-release/issues/13

- [x] any os: @rebornix 
- [x] any os: @jrieken

Authors: @joaomoreno

Complexity: 3

1. Get a Raspberry Pi 2/3 with Raspbian installed
2. Enable SSH access on it
3. Configure SSH access to it from your host machine and use the Remote SSH extension to connect to it

**Comment by jrieken** [comment]
Works like charm! 👯‍♂

**Comment by rebornix** [comment]
Works as expected, great work!
