### ISSUE TITLE
Test API to know if you are remote

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#76028]
Refs: https://github.com/microsoft/vscode/issues/74188

- [x] any @mjbvz
- [x] any @aeschli 
- [x] any @kieferrm

Complexity: 2

The API is two pieces: `vscode.env.remoteName` and `Extension#extensionKind`. See all the details here: https://github.com/microsoft/vscode/issues/74188#issuecomment-503973407. Try to write an extension that knows
* if it runs remote or with the UI
* if a remote exists or not

**Comment by aeschli** [comment]
I added an api test for the 2 new fields

**Comment by mjbvz** [comment]
Tested from mac to ssh and dev container. New apis worked well
