### ISSUE TITLE
VS studio keeps crashing when i save a new js file

### ISSUE THREAD

**Issue by labanish** [microsoft/vscode#76036]
Issue Type: <b>Bug</b>

when i open a new file on vs on a new window, i expect it to run normaly

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
How exactly is the editor crashing? Stop responding? Application crash?

/needsMoreInfo

**Comment by labanish** [comment]
When i want to open a new project on VS code while running another session, it shuts down unexpected.  But when i check on the Task manager, i see a few instances of VScode running.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

If it still happens when you disable extensions, can you please share a step by step guide of what exactly triggers the crash. Does it happen for every project/folder you open for example?
