### ISSUE TITLE
Access to proposed APIs lost when extension disabled and then re-enabled.

### ISSUE THREAD

**Issue by dlebu** [microsoft/vscode#76035]
Issue Type: <b>Bug</b>

This issue affects LiveShare, but we believe it is an underlying VSCode issue. LiveShare is whitelisted to use proposed APIs but we seem to lose that capability in the following scenario:
1. [Host] Sign into LiveShare and start a collaboration session.
2. [Guest - open a new VSCode instance] From the command palette, join the collaboration session you just started.
3. [Guest]  Disable the LiveShare extension, then reload.
4. [Guest] Enable the LiveShare extension. (reload not needed)

Expected:
The Guest will re-join the session.

Actual:
Re-joining errors out with "Proposed APIs only available when running out of dev..."

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

</details>

**Comment by sandy081** [comment]
I can repro this with references list builtin extension.

**Comment by sandy081** [comment]
Here are simple steps to repro and verify

1. Open a file and run `Find all References` on a symbol
1. Make sure the references view opens and show the expected results
1. Go to extensions view and disable the references extensions. Type `@builtin ref` in search box to find the extension.
1. Reload the window
1. `Find all References` is not available as expected
1. Enable the extension
1. Now run `Find all References`
1. Make sure the references view opens and show the expected results
