### ISSUE TITLE
no definition found for - vsdcode 1.35.1

### ISSUE THREAD

**Issue by JubinSaniei** [microsoft/vscode#76038]
go to definition is not working anymore.
i'm coding in Angular
any help would be greatly appreciated.

here is HTML Code
`<div class="col-md-12">
     <span class="float-right cursor"><i class="fas fa-sync-alt"
          (click)="**refreshTable(model)**"></i>
      </span>
</div>`

refreshTable(model) is the function i have in my .ts file.
it used to work when i hit F12 on any function in my html file, it jumped to the source. but now its not working.

**Comment by mjbvz** [comment]
The functionality to have go to definition work between html is provided by your angular extension. Please file this issue against them

**Comment by JubinSaniei** [comment]
thanks for the advise @mjbvz . after installing Angular Language Service extention, problem solved.
