### ISSUE TITLE
Windows is hardcoded in default shell selector

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76040]

**Comment by alexr00** [comment]
I think that line 555 should be 
`					platformKey = env.os === OperatingSystem.Windows ? 'windows' : (env.os === OperatingSystem.Macintosh ? 'osx' : 'linux');
`
vs
`					platformKey = env.os === OperatingSystem.Windows ? 'windows' : (OperatingSystem.Macintosh ? 'osx' : 'linux');`

**Comment by Tyriar** [comment]
@alexr00 thanks for spotting 👍
