### ISSUE TITLE
Every day now, Insiders update crashes and botches the installation

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#76048]
Version: 1.36.0-insider (user setup)
Commit: 6a7020dd4a11e0f33b157b3df4baeec90d85701b
Date: 2019-06-24T06:46:00.488Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Have VS Code Insiders
2. "Restart to update"

During the update, it showed an error about the exe being in use and DeleteFile errored with code 32. I Already had enableBackgroundUpdates set to false.

After updating, the installation is corrupted, and gives the error below
![image](https://user-images.githubusercontent.com/461084/60057487-1496f900-96bb-11e9-9a7a-221a315c6e05.png)

Happens consistently every day I decide to click "Restart to update". Only way to fix is to download from website and reinstall. This has been going on for at least 4 weeks

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Could you maybe switch to using the System setup for a while and see if you get the same problems? https://code.visualstudio.com/docs/?dv=win64&build=insiders

**Comment by pocesar** [comment]
@joaomoreno this still happens every other day, and using Process Explorer, the SYSTEM process (ID 4) is keeping a file handle to both Code - Insiders.exe file and the bin folder

**Comment by joaomoreno** [comment]
Could you maybe switch to using the System setup for a while and see if you get the same problems? code.visualstudio.com/docs/?dv=win64&build=insiders
--

**Comment by joaomoreno** [comment]
Could you maybe switch to using the System setup for a while and see if you get the same problems? code.visualstudio.com/docs/?dv=win64&build=insiders

**Comment by pocesar** [comment]
yes, has the same problem happening. not sure what else to try

**Comment by joaomoreno** [comment]
> During the update, it showed an error about the exe being in use and DeleteFile errored with code 32. I Already had enableBackgroundUpdates set to false.

Let's make sure you do have `enableBackgroundUpdates` set to false. Then when the dialog error shows up again, take a screenshot and show me.
