### ISSUE TITLE
Inside VScode, in release notes, middle-clicking links opens broken link in browser

### ISSUE THREAD

**Issue by madacol** [microsoft/vscode#76042]
When middle clicking any of the links in the image, it opens the browser with a broken url

For example for the *remote development* link, the url is:
https://code.visualstudio.com/raw/#remote-development-preview

![image](https://user-images.githubusercontent.com/6379896/59554293-7e4e2f00-8f66-11e9-8431-bdc93ea65b61.png)

I'm Using Ubuntu 18.04

**Comment by mjbvz** [comment]
Here's where we handle clicks inside of webviews: https://github.com/microsoft/vscode/blob/355b5692ff64a3604ddad9ea4a8076f6fb9545cd/src/vs/workbench/contrib/webview/browser/pre/main.js#L148
