### ISSUE TITLE
Javascript highlighting is broken by const, conditional operator and string templates

### ISSUE THREAD

**Issue by AlbinTheander** [Microsoft/vscode#7604]
- VSCode Version: 1.2.0
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Assigning a constant value an expression with the conditional operator where the third operand is a string template will break all further syntax highlighting.  I.e:

```javascript
function foo(bar) {
    const baz = bar ? `anything` : `${bar}`;  // From here on, there is no syntax highlighting anymore.
    console.log(baz);
}
```

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/81
