### ISSUE TITLE
Test finalized DocumentLink.tooltip API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76041]
Test for #74336

- [x] Mac @bowdenk7
- [x] Linux @jrieken
- [x] Windows @stevencl

Complexity: 3

**Overview**
#74336 finalized the `DocumentLink.tooltip` property. This lets extensions customize the hover text of document links

**Testing**
Use the [ContentProviderSample](https://github.com/microsoft/vscode-extension-samples/tree/master/contentprovider-sample) and set a `tooltip` on the document links. Confirm that the tooltip is rendered as expected in the UI

Look over the api. Do you understand the property and how it should be used?

**Comment by stevencl** [comment]
I've been unable to get the sample to run properly - I don't see any references show up in the references document.

The only feedback I have about the API was that I expected a tooltip parameter on the DocumentLink constructor. I was surprised that I could only set the tooltip via the property.
