### ISSUE TITLE
Add accesibility mode only keybindings to navigate up and down rows in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76050]
For example when in accessibility mode, ctrl+up/down could navigate (focus) through rows in the terminal.

**Comment by Tyriar** [comment]
Required for this: https://github.com/xtermjs/xterm.js/pull/2294

**Comment by Tyriar** [comment]
To verify test with JAWS 2019 under Windows. ctrl+up/ctrl+down enters line navigation mode and escape exits. JAWS is going to add special rules for this, it may not be done yet but you can create the following file to fix the keybindings.

`C:\Users\<user>\AppData\Roaming\Freedom Scientific\JAWS\2019\Settings\enu\defaults.jkm`:

```
[Common Keys]
Ctrl+UpArrow=
Ctrl+DownArrow=
```

Note that accessibility must be enabled to test this, you can also define your own keybindings for the commands

```
workbench.action.terminal.navigationModeExit
workbench.action.terminal.navigationModeFocusNext
workbench.action.terminal.navigationModeFocusPrevious
```

**Comment by kieferrm** [comment]
I had to add the Common Keys section to C:\Users\<user>\AppData\Roaming\Freedom Scientific\JAWS\2019\Settings\enu\DEFAUTLS.JCF` to get this to work. Even when I told JAWS to also look for settings in `defaults.jkm` it didn't work.
