### ISSUE TITLE
Test default shell API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76051]
Test for #75091

- [x] Mac @gregvanl
- [x] Linux @lramos15
- [x] Windows

Complexity: 2

Test `vscode.env.shell` API and its documentation to make sure it works as expected.

**Comment by stevencl** [comment]
Sorry, I have been unable to test this as I just can't seem to get access to the new API.

**Comment by Tyriar** [comment]
@stevencl you need to pull in the proposed types or just cast `vscode.env` to `any`. I think to pull the proposed types you need to change the engine version in package.json to `*`, then run `npm run postinstall` and change it back.
