### ISSUE TITLE
Test Telemetry Command's extension suppot

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#76057]
Test for #76029 

- [x] Mac @rebornix
- [x] Linux @mjbvz
- [x] Windows @alexr00

Complexity: 2

1. Install an extension
2. Create a file in the extensions installed directory called `telemetry.json` copy and paste this into it: 

```json
{
  "events": {
    "E1" : {
        "E1P1" : { "classification": "SystemMetaData", "purpose": "FeatureInsight" }
      }
  }
}
```
3. Run `--telemetry`. Ensure that the event shows up under the appropriate extension in the JSON output.

**Comment by alexr00** [comment]
@lramos15 are there any other steps? I'm testing on Windows and I just get this:
```
D:\repos\Microsoft\vscode>code-insiders --telemetry
Unable to read VS Code telemetry events!

D:\repos\Microsoft\vscode>code-insiders . --telemetry
Unable to read VS Code telemetry events!
```

**Comment by lramos15** [comment]
There's no any other steps and that is just error message given when VS code fails to read either the shipped JSON or the one in the extension folder. I'll investigate this and see what's going on.

**Comment by lramos15** [comment]
@alexr00 The JSON previously provided in the test comment was not valid JSON syntax and then was failing when the function tried to parse it. I have updated the example snippet. Please try to run it again and it should work. Sorry bout that.

**Comment by rebornix** [comment]
@lramos15 I can still see the same error `Unable to read VS Code telemetry events` with latest telemetry content

```
{
  "events": {
    "E1" : {
        "E1P1" : { "classification": "SystemMetaData", "purpose": "FeatureInsight" }
      }
  }
}
```

**Comment by rebornix** [comment]
The reason that it failed on my machine is I have a symlink in the extension folder which now points to a folder no longer exits. As the file doesn't exist, https://github.com/microsoft/vscode/blob/a122c88b4e56318f778d9d2e3800395ee18ecba8/src/vs/platform/environment/node/argv.ts#L225 throws
