### ISSUE TITLE
Test terminal.integrated.inheritEnv

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76053]
Test for #75091

- [x] Mac @kieferrm
- [x] Linux over Remove-SSH @kieferrm 
- [x] Linux @rebornix

Complexity: 3

There is a new setting `terminal.integrated.inheritEnv` which when set to `false` will not use inherit window's environment, instead:

- On Linux it will get the parent of the main process and fetch its environment via procfs
- On macOS it will create a new environment taking only a few keys from the [current environment](https://github.com/microsoft/vscode/blob/8c8f79dcefde77a5df7a09c22fd85d9309706ab1/src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts#L131-L142)
- On Windows nothing (deferred in another issue)

This was added such that the integrated terminal would work more like a regular terminal and not jumble `$PATH` up by running the profile/rc scripts several times. Things to verify:

- `$SHLVL` (shell level) should be 1
- The environment in the integrated terminal should be the same as an external terminal (provided it's launched as the same login/non-login shell). Note that on macOS it may differ a little due to the approach taken, a better fix will need a native node module (https://github.com/microsoft/vscode/issues/76052).

Some more context: https://github.com/microsoft/vscode/issues/70248, https://github.com/microsoft/vscode/pull/75376,

**Comment by rebornix** [comment]
@Tyriar if I understand correctly, I should not expect the same result for `echo $PATH` when using SSH extension, right?

**Comment by kieferrm** [comment]
This works as expected locally on macOS.  Issues on Linux remote. See https://github.com/microsoft/vscode-remote-release/issues/823.

**Comment by Tyriar** [comment]
@rebornix see https://github.com/microsoft/vscode-remote-release/issues/823 for remote
