### ISSUE TITLE
Can't disable font ligatures

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7605]
When I set the editor font to one that supports ligatures, I can't seem disable them via the `editor.fontLigatures` setting. Not even after a reload.

**Comment by alexandrudima** [comment]
Yes, since we updated to the newer electron version, Chromium always shows ligatures, even without our enabling them.

**Comment by joaomoreno** [comment]
Awesome! Should we remove the setting in VS Code at least then?
