### ISSUE TITLE
Dump when format cpp code with clang-format tool.

### ISSUE THREAD

**Issue by supermanmsc** [microsoft/vscode#76066]
- VSCode Version: 1.35.1
- OS Version: windows 10 x86_64

Steps to Reproduce:

1. Add clang-format extension.
2. Use the ctrl+shift+f in a  cpp file.

Does this issue occur when all extensions are disabled?: No

Output details:

0x00007FF6F0801C4F (0x0000019762ED4980 0x0000000000000024 0x0000D8C62542F4DC 0x0000000F2378D228)
0x00007FF6F0824B42 (0x000052CD3D625D5D 0x0000000000000000 0x0000000F22C5C000 0x0000000F2378D228)
0x00007FF6F080C530 (0x0000000000000000 0x0000000F00000002 0x0000000F2378F418 0x0000000F2378DE38)
0x00007FF6F080C734 (0x0000000000000000 0x0000000000000000 0x0000000F2378F730 0x0000000000000000)
0x00007FF6F07A2D31 (0xC9366AA7F0957B9F 0x0000019720010021 0x0000019762DB0CC0 0x00000000DF0000DF)
0x00007FF6F07A18F1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF6F08E91F8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFE12B537E4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFE1529CB81 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

**Comment by sandy081** [comment]
Please file the issue against the clang-format extension.
