### ISSUE TITLE
Update to Electron 6

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76069]
This plan item is to cover the work of updating to Electron 6. We will skip Electron 5.

PR: https://github.com/microsoft/vscode/pull/75802

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by beastdestroyer** [comment]
Any predictions for when an exploration build which is up-to-date with master is released?

**Comment by bpasero** [comment]
@beastdestroyer we plan for July to release first exploration builds.

**Comment by leaxoy** [comment]
I build this branch locally， and find it resolve the thin font on external display，this looks great， so I's waiting for the exploration one.

**Comment by beastdestroyer** [comment]
@bpasero Noticed that maximise windows on Windows doesn't work - have to drag from the top and hold it there to expand it (normal Windows "gesture/shortcut")

**Comment by bpasero** [comment]
@beastdestroyer does that reproduce when you configure the window title style to native in settings? Could be a bug from our custom title.

Do you see bold in other places in the editor? Can you maybe open developer tools and see if the style is set?

**Comment by beastdestroyer** [comment]
@bpasero 
1. Setting title bar to ```native``` works fine, but the menu becomes this (I have dark mode enabled on windows 10 1903, maybe that's why?)
![image](https://user-images.githubusercontent.com/30497573/60968596-683d4f80-a315-11e9-8cc3-ea138186f1c0.png)

2. It turns out: Yes it is applying the style - it's just much more thinner so it blends in with everything else
Exploration 1.37:
![image](https://user-images.githubusercontent.com/30497573/60968722-b5b9bc80-a315-11e9-8658-767441230d49.png)
Insiders 1.37:
![image](https://user-images.githubusercontent.com/30497573/60968811-eac60f00-a315-11e9-8c06-0b84ed967e92.png)

**Comment by beastdestroyer** [comment]
@bpasero 
Also noticed when you do get the window maximised, I can't unhide my taskbar (I have auto hide on Windows turned on because I likethe extra screen real estate)

**Comment by beastdestroyer** [comment]
@bpasero @deepak1556  (Sorry if these pings bother you, idk if I should create separate issues for these or just leave them here)

Just found another bug:

1. Have an editor with the sidebar open to some width that isn't the minimum width
2. Minimise the window (don't just click off the window)
3. Then open the window back - observe the sidebar is now at minimum width

You can try by minimizing and then focusing on another window, then back and the same thing happen

**Comment by bpasero** [comment]
@beastdestroyer yeah I think at this point it would help to distill each individual issue separately and then we can add the `electron-6.0.x` label. Thanks for testing!

**Comment by beastdestroyer** [comment]
Alright done, there's like 6 issues all with [EXPLORATION] for ya :)

**Comment by NashLegend** [comment]
Any new releases ?

**Comment by cebor** [comment]
The last exploration build seems to fix the font issues from: https://github.com/Microsoft/vscode/issues/51132

**Comment by lucashtc** [comment]
Station available here [75802](https://github.com/microsoft/vscode/pull/75802)

**Comment by bpasero** [comment]
Pushed to `master` to have it in insiders on Monday.

**Comment by beastdestroyer** [comment]
@bpasero does this mean exploration won't be updated anymore until another electron update/test is needed? sad times, i love exploration :)

**Comment by bpasero** [comment]
> does this mean exploration won't be updated anymore until another electron update/test is needed? sad times, i love exploration :)

Yeah, I think we want to move forward with exploration to Electron 7 or 8 pretty soon. Deepak is on vacation right now but we will pick this up again once he is back. 

At this time it is not clear to me if we would go with E7 or E8.

**Comment by beastdestroyer** [comment]
I'd argue go for E8, you guys skipped E5 (perhaps an issue, or it was too far behind and E6 was essentially close to stable) so going for E7 may lag behind schedule? I propose going for every 2 versions because now Emajors are released very frequently

Plus you get to land exactly on E10 which is nice :)

**Comment by bpasero** [comment]
Given https://github.com/microsoft/vscode/labels/electron-blocker and this being the last day of the milestone, this moves to October.

**Comment by kanlukasz** [comment]
I hope that Electron 6 will be implemented in October. This solves many problems, including [mine](https://github.com/microsoft/vscode/issues/74047)

**Comment by svipas** [comment]
@bpasero Since all blockers are fixed, could we expect next week Insiders with Electron 6?
