### ISSUE TITLE
Xml not loading the updated content

### ISSUE THREAD

**Issue by dax13vulture** [microsoft/vscode#76075]
Issue Type: <b>Bug</b>

Hi! I wanted to load/preview a xml file and after a file change it stills shows me the "old" content:

- take a large xml and preview it in a tab
- make changes to the xml (in my case was via code)
- close and reopen the tab with the xml

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-52-generic

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.7.1
ci-snippets2|Ani|1.0.0
vscode-intelephense-client|bme|1.0.14
symfony-snippets|Cro|0.1.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-mysql|for|0.4.0
php-constructor|Meh|0.1.2
mssql|ms-|1.6.0
sqltools|mtx|0.19.5
php-docblocker|nei|1.8.0
vscode-php-getters-setters|php|1.2.3
php-ci|sma|0.2.11
duckduckgo|tai|0.0.3
makefile-creator|zen|0.0.3

</details>

**Comment by sandy081** [comment]
Are you using any extension to preview the xml?

**Comment by dax13vulture** [comment]
hi,

is the xml syntax highlighting  triggered "natively"?
That is the only thing I have for xml files.

**Comment by sandy081** [comment]
Can you please provide a screenshot to understand?
