### ISSUE TITLE
--telemetry should also be available as a normal command

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#76078]
Testing https://github.com/microsoft/vscode/issues/76056

The command should print the content directly into an editor for easier reading.

**Comment by lramos15** [comment]
After discussing with the Redmond team I don't believe I'm going to be pursuing this feature request as the command was only ever intended for the CLI to give users who were seeking information a way to acquire it and then ingest it in anyway they seem fit from the CLI.
