### ISSUE TITLE
Go constants with omitted assignment are not syntax highlighted correctly

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#76073]
- VSCode Version: 1.35.1
- OS Version: macOS 10.14.5

Steps to Reproduce:
1. Open the following `.go` file in VS Code:
```go
package foo

const (
	Value1 = iota
	Value2
	Value3
	Value4
)
```
2. `Value2`, `Value3` and `Value4` are not highlighted like `Value1`.

![image](https://user-images.githubusercontent.com/24731903/60076586-9bd28400-9730-11e9-893f-a596471c19f7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved the issue to go grammar repo.

**Comment by segevfiner** [comment]
@alexr00 The issue on the Go grammer repo was punted on since they don't seem to be interested in maintaining the Go TextMate grammer as they are migrating to a different engine for syntax highlighting in Atom.
