### ISSUE TITLE
Microsoft.EntityFrameworkCore.SQLite is not found

### ISSUE THREAD

**Issue by samova** [microsoft/vscode#76072]
- VSCode Version: 1.35.1
- OS Version: Windows_NT_x64 10.0.16299

Steps to Reproduce:

1. I tried to use VSCode to add SQLite package following the tutorials of docs.microsoft.com
https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code
2. When I tried to execute "dotnet add package Microsoft.EntityFrameworkCore.SQLite",
it showed Microsoft.EntityFrameworkCore.SQLite is not found

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Not related to VS Code. Please file the issue against the owner of the document.
