### ISSUE TITLE
Custom file dialog: text typed gets removed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76084]
![grid-tw](https://user-images.githubusercontent.com/900690/60092146-8bc59f00-9746-11e9-8de6-4c4afd2bc8c3.gif)

Setup:
* macOS
* type over "/"
* 🐛 text I type gets removed easily

**Comment by alexr00** [comment]
I think this was fixed by since I cannot reproduce anymore 9b28638e8c7e6fefb458016342563f90c28fdfd2
