### ISSUE TITLE
Some hotkeys are not keyboard layout agnostic

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#76085]
- VSCode Version: any this and previous year (I use latest **1.35.1** currently)
- OS Version: e.g. any macOS (window, I think, too; I use latest **macOS 10.14.5** currently)

Steps to Reproduce:

1. add and switch to any language keyboard layout (e.g. russian) in the system keyboard preferences
2. say, add sublime keymapping, or just `⌃+\``
![image](https://user-images.githubusercontent.com/6201068/60090449-3cce3880-974b-11e9-94a2-27c650e24e4f.png)
3. press `⌃+\`` (actually it will be `⌃+]`)

I think now, that it might be unexpected for some users... 🤔  

Also, would be good enough if we can add multiple hotkeys aliases, so your would be able to add hotkey variants in other kbd-layouts manually

**Comment by Tyriar** [comment]
@a-x- you can create as many keybindings as you want for any command, see https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/1240
