### ISSUE TITLE
Auto Save not working when the Angular App is running

### ISSUE THREAD

**Issue by rashika057** [microsoft/vscode#76083]
Issue Type: <b>Bug</b>

At the time of the Angular App running, if we want to make any change in the code. It is not taking it automatically but we need to save the file or press ctrl+S. Then only it will start compiling and provide us the updated application

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (17.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rashika057** [comment]
On going to "Select Help | Toggle Developer Tools and select the Console"

I am getting this output:

[Extension Host] debugger listening on port 54437
workbench.main.js:1406   ERR Error: Error: ENOENT: no such file or directory, stat 'c:\Users\hus8kor\Documents\my-onlineshop-app\.vscode'
﻿

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
@rashika057 I am not sure I follow the issue. Are you saying that:
* you have auto save enabled
* you start to type
* after 1s the file is still not saved to disk

Are you sure it is not saved? Or is angular app not detecting any change?
