### ISSUE TITLE
please Add the identification of functions and macros in c and c++.！

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#76086]
After the color of the function is set, the color of the macro changes accordingly.
 {
            "scope": "entity.name.function",
            "settings": {
                "name": "Functions",
                "foreground": "#ff9d6f"
            }
        },
thx

**Comment by alexr00** [comment]
If you want to see the scope of an element run the "Developer: Inspect TM Scopes" command.
The scope for macros in C++ is `entity.name.function.preprocessor`.
For example you can color just macros using:
```json
	"[Default Dark+]": {
		"textMateRules": [
			{
				"scope": "entity.name.function.preprocessor",
				"settings": {
					"foreground": "#FF0000"
				}
			}
		]
	}
```
