### ISSUE TITLE
Semicolon ends debugging argument

### ISSUE THREAD

**Issue by baadfood** [microsoft/vscode#76088]
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0 V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic

        "args": 
        [
            "Hello;World!"
        ],

Only Hello is passed to program. Semicolon isn't any special case in JSON, and even \u003b fails.

Semicolon is  a valid character to pass as a program argument.

**Comment by jeanp413** [comment]
I think this is a c++ extension bug. Also tested it with node and it works fine there, the whole string is passed as argument.
@baadfood you should create an issue there https://github.com/microsoft/vscode-cpptools
