### ISSUE TITLE
Test: downloadAndUnzipVSCode could have a constant overload 'insiders'

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76091]
Refs: #76039

`export declare function downloadAndUnzipVSCode(version?: string | 'insiders'): Promise<string>;`

**Comment by bpasero** [comment]
Same for other places where this can be done, e.g. `version` in `runTest` options.

**Comment by octref** [comment]
Tried this but I wouldn't get any `insiders` IntelliSense. For what benefit should we do this?

![image](https://user-images.githubusercontent.com/4033249/60113625-0f6f9380-9727-11e9-874a-f0aecf7f92af.png)

**Comment by bpasero** [comment]
@mjbvz I would expect a string constant to show up in the intellisense?

@octref yeah if it does not show up as help to the user, it is of not much value.

**Comment by mjbvz** [comment]
@octref Can you please share the function declaration you are using?

**Comment by octref** [comment]
@mjbvz Simple repro:

```
function downloadVSCodeArchive(version: string | 'foo') {}

downloadVSCodeArchive('|') // do completion here
```

I'm on TS 3.5.2.

**Comment by mjbvz** [comment]
Thanks. TS will reduce the type to the common `string` type in cases like that for the intellisense details / parameter hints. I believe that is the expected behavior

**Comment by octref** [comment]
@mjbvz Found upstream issue: https://github.com/microsoft/TypeScript/issues/29729

Apparently this works:

```ts
type StringLiteralUnion<T extends U, U = string> = T | (U & { });
type DownloadVersion = StringLiteralUnion<'insiders' | 'stable'>;
```

![image](https://user-images.githubusercontent.com/4033249/60206095-a9a70880-9807-11e9-89a0-b90118fa8f3f.png)

I'll add `insiders` and `stable` constants.
