### ISSUE TITLE
Understanding the variable ${env.PATH} 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#76099]
Within my workspace settings file I have terminal.integrated.evn.windows setting, there I have PATH: along with `${env.PATH}` then an appended path; therefore if I have this understood correctly, it is first searching within the windows environment variable then it is appending any paths to that but strictly within vscode ? Eliminating the need to add extra paths to the windows environment variable ?

**Comment by Tyriar** [comment]
`${env.PATH}` will use the PATH variable from the VS Code window environment variable which remains the same until you close all windows and restart. You're probably interested in https://github.com/microsoft/vscode/issues/47816
