### ISSUE TITLE
Breadcrubs keeps expanding

### ISSUE THREAD

**Issue by TheHunterDog** [microsoft/vscode#76098]
- VSCode Version: 1.35.1
- OS Version: macOS mojave 10.14.5

Steps to Reproduce:

1. Open an window with breadcrumbs enabled
2. Move the window to the edge of the screen
3. click on an breadcrumb
4. Click twice on the bar where the close minimize and fullscreen buttons are (The top bar of the editor)

Does this issue occur when all extensions are disabled?: Yes

**Comment by TheHunterDog** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Breadcrumbs' position (#58386)](https://www.github.com/microsoft/vscode/issues/58386)

this isn't the same because it's not about the position it's about duplicate's breadcrumbs

**Comment by jrieken** [comment]
Sorry, but I don't understand what's happing here? Can you try with latest Insiders (which has a fix for an issue when resizing). Can you also attach a screen capture or recording?
