### ISSUE TITLE
Test: improve console message for downloading

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76090]
Refs: https://github.com/microsoft/vscode/issues/76039

I suggest to fold the 2 first "Downloading" messages into one:

![image](https://user-images.githubusercontent.com/900690/60099121-51183280-9757-11e9-92fa-f3dea9a35f85.png)

**Comment by octref** [comment]
Decided to go with:

```
Downloading VS Code 1.35.1 from https://update.code.visualstudio.com/1.35.1/darwin/stable
Downloaded VS Code 1.35.1 into .vscode-test/vscode-1.35.1
```
