### ISSUE TITLE
Test: should we have a constant version stable?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76092]
Refs: https://github.com/microsoft/vscode/issues/76039

I see we support a constant `insiders` as version. Should we have `stable` too?

**Comment by octref** [comment]
Latest stable should be the default behavior. Adding some explicitness is fine by me.

However if we add more magical constants I'd like to make sure IntelliSense would work.

**Comment by bpasero** [comment]
Yeah, at lest for this one you could add it to the documentation.
