### ISSUE TITLE
Changing `debug.console.wordWrap` needs a restart

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#76095]
re https://github.com/microsoft/vscode/issues/72210

* change the `debug.console.wordWrap`-setting
* :bug: the editor asks for a restart

I find a restart rather weird and I don't know why we need to go full-windows-style here but I would image that resetting the output (tree) should be sufficient

**Comment by isidorn** [comment]
You are right. I was lazy here.
I can fix, assigning to June and if I do not have time this week will do in debt week.

**Comment by isidorn** [comment]
Adding bug label so we get this verified.
To verify make sure that changing `debug.console.wordWrap` does not require a vscode restart and that the setting change actually makes an effect.
