### ISSUE TITLE
Debug output isn't shown in full

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#76093]
re https://github.com/microsoft/vscode/issues/72210

* have this as `app.js`: `console.log(new Array(10000).join('Q') + 'F');`
* turn off debug wrap
* run app.js
* :bug: you don't see the whole output

<img width="1194" alt="Screenshot 2019-06-25 at 14 55 09" src="https://user-images.githubusercontent.com/1794099/60100095-4c547e00-9759-11e9-80e1-a58fa1771721.png">

**Comment by isidorn** [comment]
I wronlgy analysed this issue, and thought this is only a corner case - my mistake.
However this issue is worse and makes the word wrap not work at all. Thus assigning a candidate and to June recovery.

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/pull/76690
