### ISSUE TITLE
Touching TextEdit's are not being applied

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#761]
After moving `vscode-go` from applying full-document-replacement edits to [applying multiple targeted edits for formatting](https://github.com/Microsoft/vscode-go/pull/111), I'm seeing one odd case.

When the formatter asks to replace 4 spaces with a tab, we compute the two edits below:

```json
[
 {
  "_range": {
   "_start": {
    "_line": 3,
    "_character": 0
   },
   "_end": {
    "_line": 3,
    "_character": 4
   }
  },
  "_newText": ""
 },
 {
  "_range": {
   "_start": {
    "_line": 3,
    "_character": 4
   },
   "_end": {
    "_line": 3,
    "_character": 4
   }
  },
  "_newText": "\t"
 }
]
```

But when we return these edits, they do not get applied.  Worse, if these edits are part of a set of 20 edits, none of the edits get applied.  And worse, we get no error returned to us or reported to the user about these edits being invalid.

Is this an illegal edit, and if so why?

Is it expected that we don't get any feedback about the edits being incorrect?

/cc @newhook

**Comment by alexandrudima** [comment]
There is indeed some over protective code in the model that does not allow edits that touch each other. The code tries to protect against ambiguity.

In your specific case there is no ambiguity as to what to do:
* delete `[0->4]`
* insert `"\t"` at `4`
* this is the same as replace `[0->4]` with `"\t"`

But for example the following case is ambigous:
* insert `"A"` at `4`
* insert `"B"` at `4`
* should it insert `"AB"` or `"BA"` at `4`?

To protect against ambiguities, the model forbids any touching ranges. I agree the check is rather over protective but I would not want to remove it entirely.

@jrieken not sure where the error is going..

**Comment by lukehoban** [comment]
Thanks @alexandrudima.  For now we've successfully worked around this by collapsing the edits before returning them.  This appears to be working, but requires a lot more logic processing the edits in the extension than I'd like.

I find it odd that the edits are currently treated as being relative to the original document, vs. being a consecutive set of edits relative to the state of the document after applying all the previous edits.  The later would have ensured there are no ambiguities (and matches what would really happen if the edits were user input against a document).

But perhaps that's not an option at this stage.

Either way - would be good to get a validation error returned so we can catch this and identify places where it's failing (and to document the requirements on the `TextEdit[]`).

**Comment by alexandrudima** [comment]
@lukehoban I pushed a change that I allow now touching edits. In case of ambiguity, the order of the edits prescribes the order in which they are applied (e.g. insert 'a' at pos1, insert 'b' at pos1 => insert 'ab' at pos1)

**Comment by dbaeumer** [comment]
Verified with TS/JS formatter which creates these edits as well.
