### ISSUE TITLE
VS Code Windows Bug

### ISSUE THREAD

**Issue by weathon** [microsoft/vscode#76101]
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Use Ctrl + \` to open a terminal in VS Code, and use git bash(Or Power Shell) to run `git commit`
2. Then, the git will pop up a "vim" in the terminal, but the rendering is disordered. Just like this:
![image](https://user-images.githubusercontent.com/41298844/60103986-2d88c400-9726-11e9-9743-f3d663bacea3.png)
I didn't found this bug on Linux yet.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by weathon** [comment]
OK, thanks
