### ISSUE TITLE
"Undo Last Commit" does not prompt/confirm undo

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#76107]
- VSCode Version: 1.35.1
- OS Version: macOS 10.14

**Steps to Reproduce:**

1. Git menu, "Undo Last Commit"

No prompt before undoing, it just erases the commit from the tree.
This is astonishing behaviour - I was expecting it to revert or at least prompt / warn me before erasing the history.

#69937 is for merge commits, but this should always prompt for confirm

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
No history is lost.

- If the commit was never pushed, simply commit again from VS Code: both the changes and the commit message will be prepopulated in the view.
- If the commit was already pushed, simply reset to the server branch.

**Comment by wesinator** [comment]
But committing again creates a new commit, it doesn't restore the original
commit

**Comment by joaomoreno** [comment]
> But committing again creates a new commit, it doesn't restore the original commit

It creates a commit with the very same changes as before. Why would that not be suficient?

**Comment by wesinator** [comment]
Technically it does lose the history because the commit hash will be
different.
But I guess that's how undo (git reset) works.

It would be good to have a revert shortcut under this menu for 'softer'
undo
