### ISSUE TITLE
Ctrl+N opens recently closed files

### ISSUE THREAD

**Issue by taylorp0994** [microsoft/vscode#76100]
Issue Type: <b>Bug</b>

On multiple occasions, I've tried to use Ctrl+N to open a new file only to find that it opens recently closed files. Using the `File > New File` menu button works fine, but the hotkey does not. I checked keybindings.json to confirm that it was not bound to something else, but I don't have any custom keybindings configured.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.49GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.8.2
permute-lines|ear|0.0.10
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
vscode-docker|ms-|0.6.4
mssql|ms-|1.6.0
python|ms-|2019.5.18875
cpptools|ms-|0.23.1
powershell|ms-|2019.5.0
vetur|oct|0.21.0
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.8.0
change-case|wma|1.0.0

</details>

**Comment by sandy081** [comment]
Can you please open keybindings editor and look for the commands associated to ctrl+n keybinding?

**Comment by taylorp0994** [comment]
Currently, I have `Ctrl`+`N` bound to the command `File: New Untitled File (workbench.action.files.newUntitledFile)`. I don't remember changing this, so I assume it is the default.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by taylorp0994** [comment]
@bpasero that is good to know about running VSCode with the `--disable-extensions` flag! Oddly enough, the issue appears to have resolved itself, at least as of this morning. Perhaps my VSCode or one of its extensions installed a minor update overnight that resolved the issue? Either way, it appears to be resolved. I'll be sure to re-open with more details if I experience it again. Thanks!
