### ISSUE TITLE
One line seperation 

### ISSUE THREAD

**Issue by SergiOca87** [microsoft/vscode#76102]
- VSCode Version: 1.35.1
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

I keep having an issue where I upload files to a server via Filezilla, and when I download them back I have a white space separation on EACH line of every page which is driving me and my coworkers nuts tbh. I have tried different versions and no extensions at all and keep having the same issue.

**Comment by gjsjohnmurray** [comment]
Please clarify how Filezilla fits into the picture.

**Comment by SergiOca87** [comment]
> Please clarify how Filezilla fits into the picture.

Hmm well, it's what I use to upload files to a server, when I get the files again they are formatted, the issue has never hapenned doing something different but it is always the same server. Does not happen with other servers.

**Comment by gjsjohnmurray** [comment]
So then I'm not clear why you think it's a VSCode issue.

1. VSCode writes a file to your local disk.
2. I assume that if you close it in VSCode, then reopen it, it looks correct.
3. You use Filezilla to upload it to a server, then download it back to your local disk.
4. You open it in VSCode and it now has extra linebreaks.

So I think you need to investigate what Filezilla is doing.
