### ISSUE TITLE
Duplicate tree element ids in problems panel

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76103]
Testing https://github.com/microsoft/vscode/issues/74824 on macOS

When following the steps from that test plan item, right after

> Try changing the `"fileLocation"` in the task to `"absolute"`

... and running the task once more, you end up creating more errors on the same file, but it appears as a different file on the problems panel.

When this happens, several elements in the tree have the same ID. You can validate this by click some errors and noticing others also get focused/selected.

![image](https://user-images.githubusercontent.com/22350/60105330-6b580d80-9763-11e9-8199-b5f0ae2a61ba.png)

![image](https://user-images.githubusercontent.com/22350/60105499-b1ad6c80-9763-11e9-9701-09402b489e06.png)

**Comment by sandy081** [comment]
Will make sure that markers do not share the same id.

**Comment by sandy081** [comment]
@alexr00 I made ids of markers unique and the rest is not to generate duplicate resource entries for the same resource. I would leave that to you as I guess it is coming from tasks.

**Comment by alexr00** [comment]
Since the duplicate resources come from different tasks, we should instead clear all task markers from tasks that aren't currently running when the configuration changes.

**Comment by alexr00** [comment]
Thinking about it some more, I don't think we should just remove users task related problems without any visible reason. Instead, the best approach would be to provide a command that removes all task related problems. 

However, I don't think that would get much use. New backlog item: https://github.com/microsoft/vscode/issues/77214
