### ISSUE TITLE
Feedback Character Quantity Glitch

### ISSUE THREAD

**Issue by pridhvi-jordanhigh** [microsoft/vscode#76114]
Issue Type: <b>Bug</b>

When I opened up the feedback box (the one with the smiley face and the frowny face), picking between the two faces changes your character count. When I clicked on the smiley face it lets me type out 257 characters, but when I pick the frowny face it lets me type out 270. I think the smiley face is being counted as some characters. Either way I'm unsure if this is a glitch or not but I thought it would be necessary to bring it to your attention.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.91GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by ozyx** [comment]
seems it is intentional: https://github.com/microsoft/vscode/issues/73307#issuecomment-489468418
