### ISSUE TITLE
Select Python Interpreter with Python3 on macOS

### ISSUE THREAD

**Issue by loretoparisi** [microsoft/vscode#76112]
- VSCode Version:
1.35.1 (1.35.1)
- OS Version:
macOS 10.14.5
- Steps to Reproduce:

- Install Python3 from Homebrew.

In the status bar the app still ask to select a Python Interpreter
<img width="392" alt="Schermata 2019-06-25 alle 17 56 58" src="https://user-images.githubusercontent.com/163333/60113871-eecd2b00-9772-11e9-8d74-6117e7525d51.png">

while I have an interpreter selected already:
<img width="726" alt="Schermata 2019-06-25 alle 17 56 54" src="https://user-images.githubusercontent.com/163333/60113932-13290780-9773-11e9-8403-f60c7ddea5a5.png">

**Comment by sandy081** [comment]
Please file issue against the python extension

**Comment by loretoparisi** [comment]
Done in https://github.com/microsoft/vscode-python/issues/6357
thank you.
