### ISSUE TITLE
Can not pass debugger a boolean ENV

### ISSUE THREAD

**Issue by tmquinn** [microsoft/vscode#76116]
In launch.json, you should be able to assign a boolean property to an environment variable.

Right now they are all just strings, so `"env": { "FOO": "false" }` will be considered truthy if analyzed as `if(process.env.FOO) {...` whereas running `FOO=false node...` will not

**Comment by weinand** [comment]
Sorry, but supporting types other than strings is not possible.

The official type definition of `process.env` is this:
```ts
    export interface ProcessEnv {
        [key: string]: string | undefined;
    }
```

In addition, environment variables are an OS concept which is based on strings only.
