### ISSUE TITLE
Improve Telemetry Command Build Process

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#76113]
Follow up from #76029 about ways to improve the build process for how we ship JSON with the telemetry command.

- [x] Git clone off a specific commit
- [x] Move telemetry*.json out of the src directory and into the root.

**Comment by joaomoreno** [comment]
@lramos15 I'd feel much better if we either do this this iteration or revert the PR altogether.

**Comment by lramos15** [comment]
I'll see if I can get it fixed in time. The feature itself seems to be working, just the build needs improvements which almost feels iteration independent. I'll see what I can do 👍
