### ISSUE TITLE
Strange behaviour with undo commit.

### ISSUE THREAD

**Issue by hariprasath95** [microsoft/vscode#76115]
when i undo commit. and click commit again it doesn't ask me anything and amends to the previous commit. the same behaviour occurs with minor changes. but when i do major changes it doesn't amend and rather asks me to create a new commit. how does this work.

**Comment by joaomoreno** [comment]
When you undo a commit, the commit is undone and your working tree keeps the changes in the commit in the staging area. This is expected. There is no amend happening. Why do you say there is an amend?
