### ISSUE TITLE
Logging colours in debug console (Python)

### ISSUE THREAD

**Issue by wrussell1999** [microsoft/vscode#76111]
The Debug Console for Python shows logging in red text, but print statements in white.

An idea would be to have different colours for different logging levels, rather than all of it white. Red suggests it's important, which it may not be. Red would work better for a warning level for example.

Regardless, having all the logging output come out as red isn't great. I'd rather this was white, if no colouring was used. Or, provide a setting to change the colours.

See image for more detail:
![image](https://user-images.githubusercontent.com/34094921/60113225-38187d00-9769-11e9-901c-823384007818.png)

**Comment by isidorn** [comment]
Please file this against the python extension. https://github.com/microsoft/vscode-python
They could use ansi coloring to get more colors which we do support in vscode.

**Comment by wrussell1999** [comment]
Cheers!! Thought this was a vscode problem, rather than the extension. I have filed it against the [python extension](https://github.com/microsoft/vscode-python/issues/6324).
