### ISSUE TITLE
Support 32\64 file redirection on Windows

### ISSUE THREAD

**Issue by gerane** [Microsoft/vscode#7611]
- VSCode Version: 1.3.0-Insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Run Code as Administrator.
2. Create a new File and save it under `C:\Windows\System32\`
3. The file is actually created and saved under `C:\Windows\sysWOW64\`

Code desperately needs a 64 bit Windows client or to some how handle sysnative filesystem redirection on 64 bit Windows systems globally through the entire application.

On a 64 bit Windows OS, Code needs to redirect C:\Windows\System32\ to C:\Windows\Sysnative. Any extensions that pass Code paths will also have their paths redirected to the wrong location. In many cases, the extension passing the sysnative path might not be an option, and just expects Code to properly handle this.

In the vscode-powershell extension you can create Editor Commands written in powershell and tie your powershell scripts and modules into the Command Palette. These can be distributed inside your Modules on the PowerShell Gallery, and when the module is loaded by the powershell extension, it loads those Editor commands without any interaction from the user. When these modules interact with the extension, they might be passing paths back to code to edit, open or interact with. The powershell extension is properly running in a 64 bit context, so it is able to do it part properly.

One example of this breaking might be prompting the user with a list of PowerShell profiles to open in the editor. If the Profile doesn't exist, the extension creates it and then sends the path to Code to be opened. If an all user profile is selected, the command creates the file under `C:\Windows\System32\WindowsPowerShell\v1.0` and then passes the same path to Code to open in the editor. The problem, is code just silently does nothing. It is trying to open a file that doesn't exist at `C:\Windows\sysWOW64\WindowsPowerShell\v1.0`

There could also be potential issues when working with Program Files directories in some cases and registry values that have both 32 and 64 bit locations. Registry will be edited in the wow6432Node location instead of the normal location. So any extension or command in the editor would alter the wrong registry keys.

Also, if code handled this redirection properly, users could just set cmd.exe or powershell.exe as their terminals and get the proper 64bit terminals and avoid issues like #7095 #6684 #7266

**Comment by felixfbecker** [comment]
It's 2016, just make a 64 bit version :D

**Comment by gerane** [comment]
I think apps would have fewer issues if they just made a single 64 bit app
and ditched the 32 bit. I'd be interested to know just how many are
actually still using 32 bit OSes.

**Comment by isidorn** [comment]
We have a 64 version
