### ISSUE TITLE
Minimap search result highlight should match color used in the editor itself?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76125]
For #76030

**Repo**
1. Enable minimap
1. Search
1. Switch to a theme that highlights search results in the editor differently

**Bug**
Minimap search results are still shown in orange, even though the editor search results are highlighted in another color:

![Screen Shot 2019-06-25 at 11 26 32 AM](https://user-images.githubusercontent.com/12821956/60123478-66339800-973c-11e9-808c-868a427764fd.png)

The orange matches the gutter but for this feature it may be better to match what is shown in the editor

**Comment by RMacfarlane** [comment]
Yeah, this is a good point. I looked into using the `editor.findMatch` color, but there are some theme extensions that set this to the editor background and use only `editor.findMatchBorder` to display search results. So for parity with the editor, the minimap decorations also need to support setting a border

**Comment by RMacfarlane** [comment]
As part of https://github.com/microsoft/vscode/issues/76122, I introduced a new theme color for the decorations, `minimap.findMatchHighlight`. This defaults to the same color as the gutter, but could be changed to match the editor find color
