### ISSUE TITLE
vscode does not set current directory in the terminal if a powershell $PROFILE also sets current directory

### ISSUE THREAD

**Issue by cdmihai** [microsoft/vscode#76120]
Issue Type: <b>Feature Request</b>

Every time I open the terminal in vscode I change the directory to the directory that's opened in vscode. It would be awesome if this happened automatically.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

Later edit: It seems that vscode should have set the current directory, by my `$PROFILE` script also sets the current directory, which probably undoes what vscode sets.

**Comment by cdmihai** [comment]
#34971 and #20013 represent a much more complex problem, that of restoring an entire terminal process / state. I think this issue can stand on its own. Setting the terminal to vscode's default workspace directory does not require the deep surgery needed to capture the entire process state. It's an intermediary benefit which, according to my experience at least of having to manually set it whenever I start vscode, brings a lot of value.

**Comment by Tyriar** [comment]
> Every time I open the terminal in vscode I change the directory to the directory that's opened in vscode.

This should happen by default, what folder is it opening?

**Comment by cdmihai** [comment]
Ah, I see what's happening. My powershell `$PROFILE` script has a `Set-Location` to the directory containing all my repositories. If I comment it out and open vscode, then vscode correctly changes the current directory to the vscode workspace directory. Is there a way I can detect in my `$PROFILE` script that it's running under vscode and not set the location?

**Comment by Tyriar** [comment]
You can use `$TERM_PROGRAM` to see whether it's `vscode` or not. Other than that I think this is behaving as designed; nothing we can do if PowerShell wants to change the directory off of the cwd.
