### ISSUE TITLE
vscode-test never returns on Linux

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76126]
Stuck in this state running the helloworld-test-sample:

![image](https://user-images.githubusercontent.com/2193314/60124058-ae06ef00-973d-11e9-8349-308c679389c0.png)

**Comment by octref** [comment]
Yeah, I shouldn't have pushed the changes to samples until release I guess.

Current situation:

- Stable can only handle `function run(testsRoot: string, cb: (error: any, failures?: number) => void)`
- Insiders can handle both `function run(testsRoot: string, cb: (error: any, failures?: number) => void)` and `function run(): Promise<void>`.

So to fix this, you either need to rollback the test runner script: https://github.com/microsoft/vscode-extension-samples/commit/a200f8fce91f7be008cbdaa39da07f1ccadd657c#diff-09fc88eb54dc89a6be596a48268514ea

Or you need to download Insiders to follow Test 2's step, download Insiders locally and use it as `vscodeExecutablePath`.

**Comment by octref** [comment]
Closing as *as-designed. I'll update docs to mention that the new `run` signature is only supported from 1.36+.
