### ISSUE TITLE
add "webview" in when clause contxt

### ISSUE THREAD

**Issue by ws93** [microsoft/vscode#76127]
I'm working on an extension that has a webview to edit some local configuration(a json file). Now I would like to add an icon on `editor/title` on this webview tab. Click this icon will open the json file in editor. But I only want this icon show up on the webview's tab.

This is basically the same feature in VS Code's `Open Settings(JSON)` when we are on `Open Settings(UI)` tab.
Currently I'm trying to add `menus.editor/title` in `package.json` but I didn't find a proper `when` clause context to check if this tab is webview or something like that.

Please advise if this is a reasonable request or there is some other ways to do it.

**Comment by mjbvz** [comment]
See these questions:

https://stackoverflow.com/questions/54917748/how-do-i-contribute-a-command-to-the-vs-code-explorer-title-bar-or-command-palet/54917749#54917749

https://stackoverflow.com/questions/52142903/is-there-any-contexts-when-specified-webview-panel-is-active-in-vscode-extension/52174989#52174989

**Comment by ws93** [comment]
Thanks! It works well
