### ISSUE TITLE
Focusing editor tab does not update file-picker view for specific file(s?)

### ISSUE THREAD

**Issue by cahna** [microsoft/vscode#76135]
Issue Type: <b>Bug</b>

- VSCode: open a workspace (containing a single git repository)

- Open 3 files (split editor into vertical tab groups so all 3 files are in-view)
  - `G:\MyUICodeRepository\private\smart-campaigns\packages\smart-bundle\src\app.js`
  - `G:\MyUICodeRepository\private\smart-campaigns\packages\smart-campaigns-capi\src\with-managed-page-context.js`
  - `G:\MyUICodeRepository\private\components\packages\date-range-utilities\src\util\date-range-preset.js`
- REPEAT: click each of the 3 open editor tabs to focus the file

EXPECTED: File picker highlights the open file for all files/tabs 

DISCOVERED: `with-managed-page-context.js`, when focused, does not update the file-picker/tree view, but it works for the other 2 files

I have a screen-capture (cannot share publicly).

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (19.07GB free)|
|Process Argv|G:\AdsAppsCampaignUI.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-import-package-version|axe|0.6.1
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
JSDocTagComplete|Hoo|0.0.2
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-versionlens|pfl|0.23.0
yo|sam|0.9.3
pegjs-language|Sir|0.1.0

</details>

**Comment by bpasero** [comment]
@cahna with file picker, what do you mean? Can you attach some screenshots or screen cast?
