### ISSUE TITLE
Debugger stepping in typescript doesn't step but runs instead

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#76136]
Issue Type: <b>Bug</b>

Using the code here:
https://github.com/Microsoft/vscode-python

While debugging through code (currently I'm debugging a unit test), stepping will suddenly stop working and switch to run.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (55.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.5
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0

</details>

**Comment by rchiodo** [comment]
Essentially the same thing reported here:
https://github.com/microsoft/vscode/issues/31519

**Comment by roblourens** [comment]
Sorry for the slow response, is this still an issue?

Please give more details, like exactly where you are stepping when you see this happen.

**Comment by rchiodo** [comment]
This does occasionally happen still. Usually when debugging mocha based test files. I don't have a consistent repro though.

**Comment by roblourens** [comment]
Would appreciate if you can set `"trace": true` in your launch config, and when it happens, upload the log from the path in the debug console, with a description of what happened so I can find it in the log.

**Comment by rchiodo** [comment]
I finally have this happening again. I turned on the 'trace' flag. Here's the uploaded log:

[debugadapter.zip](https://github.com/microsoft/vscode/files/3837565/debugadapter.zip)

I was stepping over some typescript code with an await and it jumped into some random location.

**Comment by rchiodo** [comment]
Here's where it landed (in the monaco editor)

```
var EditorWorkerServiceImpl = /** @class */ (function (_super) {
    __extends(EditorWorkerServiceImpl, _super);
    function EditorWorkerServiceImpl(modelService, configurationService, logService) {
        var _this = _super.call(this) || this;
        _this._modelService = modelService;
        _this._workerManager = _this._register(new WorkerManager(_this._modelService));
        _this._logService = logService;
        // todo@joh make sure this happens only once
        _this._register(modes.LinkProviderRegistry.register('*', {
            provideLinks: function (model, token) {
                if (!canSyncModel(_this._modelService, model.uri)) {
                    return Promise.resolve({ links: [] }); // File too large
                }
                return _this._workerManager.withWorker().then(function (client) { return client.computeLinks(model.uri); }).then(function (links) { <-- Right here
                    return links && { links: links };
                });
            }
        }));
        _this._register(modes.CompletionProviderRegistry.register('*', new WordBasedCompletionItemProvider(_this._workerManager, configurationService, _this._modelService)));
        return _this;
    }
```

**Comment by rchiodo** [comment]
Here's the code I was stepping over:

```
        runMountedTest('Startup and shutdown', async (wrapper) => {
            // Stub the `stat` method to return a dummy value.
            sinon.stub(ioc.serviceContainer.get<IFileSystem>(IFileSystem), 'stat').resolves({mtime: 0} as any);

            addMockData(ioc, 'b=2\nb', 2);
            addMockData(ioc, 'c=3\nc', 3);

            const baseFile = [ {id: 'NotebookImport#0', data: {source: 'a=1\na'}},
            {id: 'NotebookImport#1', data: {source: 'b=2\nb'}},
            {id: 'NotebookImport#2', data: {source: 'c=3\nc'}} ];
            const runAllCells =  baseFile.map(cell => {
                return createFileCell(cell, cell.data);
            });
            const notebook = await ioc.get<INotebookExporter>(INotebookExporter).translateToNotebook(runAllCells, undefined);
            let editor = await openEditor(ioc, JSON.stringify(notebook)); <-- I stepped over this line

            // Run everything
            let runAllButton = findButton(wrapper, NativeEditor, 0);
            await waitForMessageResponse(ioc, () => runAllButton!.simulate('click'));
            await waitForUpdate(wrapper, NativeEditor, 15);

            // Close editor. Should still have the server up
            await closeNotebook(editor, wrapper);
            const jupyterExecution = ioc.serviceManager.get<IJupyterExecution>(IJupyterExecution);
            const editorProvider = ioc.serviceManager.get<INotebookEditorProvider>(INotebookEditorProvider);
            const server = await jupyterExecution.getServer(await editorProvider.getNotebookOptions());
            assert.ok(server, 'Server was destroyed on notebook shutdown');

            // Reopen, and rerun
            editor = await openEditor(ioc, JSON.stringify(notebook));
            runAllButton = findButton(wrapper, NativeEditor, 0);
            await waitForMessageResponse(ioc, () => runAllButton!.simulate('click'));
            await waitForUpdate(wrapper, NativeEditor, 15);
            verifyHtmlOnCell(wrapper, 'NativeCell', `1`, 0);
        },
        () => {
                // Disable the warning displayed by nodejs when there are too many listeners.
                EventEmitter.defaultMaxListeners = 15;
                return ioc;
            }
        );


```

**Comment by roblourens** [comment]
Thanks for the details. I thought you were saying that the debugger continued and didn't stop anywhere, but it just stopped in a strange place on the next step. Node is not telling us why it decided to stop there, but I assume it's related to this warning:

`Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes`

You are trying to run Monaco in Node, and then we have to load the web worker code in the main thread, and it might be pausing when the web worker code is initially loaded? But it's not telling us why it's pausing.

If you can debug this with Chrome Devtools, I think you will see the same, I don't think there's anything I can do here unfortunately.

**Comment by rchiodo** [comment]
> I thought you were saying that the debugger continued and didn't stop anywhere
Yeah sorry it did this before too. Haven't repro'd that case yet though.

Not sure if it's monaco or not. Seems to also stop elsewhere too. But maybe? Thanks for looking regardless. 

If it stops elsewhere, do you want me to capture a log for that too? Or is it stepping weirdly not something you can diagnose with a log?

**Comment by roblourens** [comment]
It might help. If you have a case that fails 100% of the time, that would help. But you could try debugging it with Chrome Devtools, and if you see the same thing, then there's probably nothing I can do.
