### ISSUE TITLE
Terminal crash

### ISSUE THREAD

**Issue by hsmyers** [microsoft/vscode#76137]
Issue Type: <b>Bug</b>

Update to the current version.  Watch the 
![2019-06-25 (2)](https://user-images.githubusercontent.com/937918/60132157-33979880-9758-11e9-96e3-2bcd5ee48129.png)
terminal crash. Followed by:
![2019-06-25 (3)](https://user-images.githubusercontent.com/937918/60132310-79546100-9758-11e9-89d9-0de3a6ca5e98.png)

VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18922

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3512)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (20.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.4
numbered-bookmarks|ale|6.2.1
markdown-imsize|amo|0.0.2
html-class-suggestions|And|1.0.7
alignment|ann|0.3.0
code-gnu-global|aus|0.2.2
coffeescript-jsdoc|bam|0.2.2
spellright|ban|3.0.38
vscode-custom-css|be5|3.0.4
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.1.4
turbo-console-log|Cha|1.2.23
vscode-astyle|chi|0.9.0
path-intellisense|chr|1.4.2
jsrefactor|cms|2.18.2
bracket-pair-colorizer-2|Coe|0.0.28
dakara-foldplus|dak|1.3.2
vscode-coffeescript-snippets|din|0.0.2
shadow-align|fsk|1.0.6
macros|ged|1.2.1
mdmath|goe|2.3.9
auto-snippet|Gru|0.0.5
todo-tree|Gru|0.0.135
vscode-journal-view|Gru|0.0.25
CppSnippets|har|0.0.14
path-autocomplete|ion|1.13.3
code-file-nav|jak|0.7.2
latex-workshop|Jam|7.0.2
reason-vscode|jar|1.6.1
markdown-extended|jeb|1.0.8
markdown-extension-pack|jeb|0.0.3
shortcut-menu-bar|jer|1.1.0
coffee-snippets|jhe|1.2.0
asciidoctor-vscode|joa|2.7.6
vscode-peacock|joh|2.4.0
vscode-insertdatestring|jsy|2.2.4
language-haskell|jus|2.6.0
perltidy-more|Kak|0.5.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-auto-timestamp|lpu|0.0.2
makefile-command-runner|mad|1.4.1
Lisp|mat|0.1.9
vscode-clang|mit|0.2.3
vscode-html-format|moh|0.0.3
vscode-cosmosdb|ms-|0.10.2
azure-account|ms-|0.8.4
cpptools|ms-|0.24.0-insiders
printcode|nob|3.0.0
indent-rainbow|ode|7.4.0
vscode-journal|paj|0.9.1
coffeescript-formatter|prp|1.0.1
text-power-tools|qcz|1.11.1
funclist|qrt|7.6.3
subtle-brackets|raf|3.0.0
datetime|rid|1.0.5
elm|sbr|0.25.0
perlcritic|sfo|1.0.2
perltidy|sfo|1.3.1
markdown-preview-enhanced|shd|0.4.2
html5-boilerplate|sid|1.0.3
indenticator|Sir|0.6.0
numbermonger|sof|0.5.0
vscode-markdown-paste-image|tel|0.12.0
vscode-input-sequence|tom|0.2.0
vscode-icons|vsc|8.8.0
change-case|wma|1.0.0
clang-format|xav|1.9.0
vscode-awesome-snippets|xin|0.2.1
coffeescript-support|yor|0.3.0
markdown-all-in-one|yzh|2.4.0
inserttimestamp|zvl|1.1.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like a wsl issue, not vscode.
