### ISSUE TITLE
Not clear how minimap decorations are being dropped after 1000

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76130]
Testing #76030

**Repo**
1. Enable minimap
1. Open VS Code src
1. Open `yarn.lock`
1. Search `version "`

**Bug**
This produces 1315 results. However it is not clear how results are being dropped from the minimap. I feel like I just see two decorations at the very top. More are highlighted as you arrow through the results

I'd expect we show the first X results in the minimap and then start dropping them

**Comment by RMacfarlane** [comment]
They use the same logic as the decorations in the overview ruler, which attempt to combine themselves in a complicated way. I'd prefer to not try to refactor this, as I don't think it's worth it
