### ISSUE TITLE
Tabs: add animations

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7613]
Explore to animate structural changes as well as DND operations.

Example: http://jsbin.com/lewamanaba/edit?html,css,js,output

**Comment by yisibl** [comment]
![Chrome tabs](https://img.alicdn.com/tps/TB1Kd6TKpXXXXa9XXXXXXXXXXXX-506-187.gif)

If the support like Chrome, always position the close button to the mouse position, it is too perfect.

**Comment by bpasero** [comment]
@yisibl chrome has it easy because each tab has the same width. this is not true for us. I have extracted https://github.com/Microsoft/vscode/issues/7646

**Comment by yisibl** [comment]
@bpasero Can we change the same width? Complete file name can be displayed when hover.

**Comment by bpasero** [comment]
@yisibl we decided to not crop the editor label in the tab. @stevencl has the background on this.

**Comment by yisibl** [comment]
@bpasero Thanks 👻

**Comment by stevencl** [comment]
We would like to optimise the design such that the file names remain glanceable for most of the time. We think that showing the file name is more important for developers than showing the name of the web page is when browsing the web.

**Comment by yisibl** [comment]
@stevencl Indeed, the use of the mouse to close the tabs in the editor frequency, there may be no shortcut key high.

**Comment by bpasero** [comment]
No plans to work on this, closing.
