### ISSUE TITLE
Snippets and auto-complete does not follow indention rules

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#76139]
Issue Type: <b>Bug</b>

Snippets and auto-complete does not follow indention rules

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Type something that uses indention rules
2. "Type" the same thing but using auto-complete or snippets

Example: 
![2019-06-25_22-52-38](https://user-images.githubusercontent.com/1727541/60132724-62376280-979c-11e9-8365-6c0a019e5305.gif)

**Comment by Hezkore** [comment]
I can't find the duplicate issue.
And will this be fixed?

**Comment by Hezkore** [comment]
@jrieken 
Where is the duplicate issue?
I'd like to follow the issue and progress.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/20112
