### ISSUE TITLE
Latest update in unusable on my system

### ISSUE THREAD

**Issue by nvanbalen** [microsoft/vscode#76134]
Issue Type: <b>Bug</b>

It is a bit difficult to to reproduce this exactly the same way, but when I try to access a member function of an object (e.g. string.c_str()) it causes my entire system to freeze up. Closest I can get to reliably reproducing it is to have Android Studio open and add a '.' after a string variable. The entire system becomes unresponsive, and after enough time I am prompted to reopen of just close the vscode window, but it never responds to clicking a button.  I have disabled intellisense which has helped simpy browsing, but it still freezes the entire system when accessing member functions. I am running ubuntu 16.04 in vmware workstation 14.1.7 build-12989993 and have given the VM 10GB of RAM.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (4 x 2801)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|9.59GB (6.80GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clang|mit|0.2.3
vscode-docker|ms-|0.6.4
python|ms-|2019.5.18875

(7 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Might be caused by the vscode-clang extension that you are using, in which case log the issue at https://github.com/mitaki28/vscode-clang/issues or try a different C extension.

**Comment by nvanbalen** [comment]
Disabling the clang extension did indeed resolve the issue, Thanks for all the help!
