### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#76131]
Issue Type: <b>Bug</b>

Since the last update of VSCode, is not possible to click on the minimap to go to the position we've clicked on.

VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
project-manager|ale|10.5.2
read-only-indicator|ale|3.0.3
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
git-extension-pack|don|0.1.3
githistory|don|0.4.6
gitlens|eam|9.8.2
remotehub|eam|0.5.0
todo-tree|Gru|0.0.135
vscode-test-explorer|hbe|2.12.1
pomodoro|lky|1.1.2
python|ms-|2019.5.18875
remote-containers|ms-|0.64.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.2
vscode-remote-extensionpack|ms-|0.15.0
resourcemonitor|mut|1.0.6
embrace|myc|1.0.0
code-settings-sync|Sha|3.3.1
vscode-icons|vsc|8.8.0
vscode-wakatime|Wak|2.1.2
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Duplicate of #75927

**Comment by RicaBenhossi** [comment]
Indeed. Is the same problem... I'm closing this issue. Thank you @gjsjohnmurray
