### ISSUE TITLE
Support multi-line decorations in the minimap

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76133]
Testing #76030

**Repo**
1. Enable minimap
1. Open a file
1. Search for `\n` with regular expressions enabled

**bug**
The entire minimap becomes orange:

![Screen Shot 2019-06-25 at 12 00 43 PM](https://user-images.githubusercontent.com/12821956/60125603-07bce880-9741-11e9-9f55-1dc5ff579731.png)

**Comment by gregvanl** [comment]
Yep, something odd with \n and regex. If you search for text with trailing \n, the minimap shows the beginning non-matching part of the line highlighted.

![image](https://user-images.githubusercontent.com/12818376/60138515-8aed3700-975f-11e9-9491-da6e33a367ef.png)

**Comment by RMacfarlane** [comment]
Nice catch! I'm not correctly handling multi-line decorations. Will defer this to next iteration, since the I think the fix will be more involved
