### ISSUE TITLE
DAP getting more SourceRequests

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode#76142]
In the C++ extension we are getting more instances of receiving a SourceRequest which we were not expecting and don't currently handle. We have put in a fix on our side to return a false `success` response to the request but I wanted to check and see if there was a change in the recent past to cause this to start happening? 

https://github.com/microsoft/vscode-cpptools/issues/3662#issuecomment-502308591

**Comment by weinand** [comment]
VS Code should only send SourceRequests for "Source" objects that it had previously received from the DA. VS Code does not "invent" Source objects by its own.

Are you just receiving more SourceRequests per time unit, or are you receiving SourceRequests for unknown Sources (i.e. sources you had never handed out)?
