### ISSUE TITLE
Enter doesnt work on delete confirmation modal

### ISSUE THREAD

**Issue by natew** [microsoft/vscode#76147]
- VSCode Version: Insiders 1.36.0
- OS Version: Mojave

Steps to Reproduce:

1. Right click file > Delete
2. Hit enter (doesn't confirm)

![image](https://user-images.githubusercontent.com/12100/60151137-7aa18000-9790-11e9-9ed1-2dfd6a8aef44.png)

Is this an experiment to do non-native modals in VSCode? If so, count my vote for 👎

**Comment by natew** [comment]
For reference, in native Mac you hit enter to confirm delete.

**Comment by sbatten** [comment]
@natew Native dialogs should be restored in the latest insiders.
