### ISSUE TITLE
System.TypeInitializationException: 

### ISSUE THREAD

**Issue by janpop2017** [microsoft/vscode#76140]
- VSCode Version: 1.36.0-insider
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Starting VSC gives the following error:

System.TypeInitializationException: Typeinitialiseringsfunktionen for 'Microsoft.Data.Sqlite.SqliteConnection' udløste en undtagelse. ---> System.Reflection.TargetInvocationException: Destinationen for en aktivering udløste en undtagelse. ---> System.DllNotFoundException: DLL'en 'e_sqlite3' kunne ikke indlæses: Det angivne modul blev ikke fundet. (Undtagelse fra HRESULT: 0x8007007E)
   ved SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   ved SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   --- Slut på staksporing af indre undtagelser ---
   ved System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   ved System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   ved System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   ved Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   ved Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- Slut på staksporing af indre undtagelser ---
   ved Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   ved SymbolCache.PersistenCacheImpl.initializeCache(String dir)
   ved FsAutoComplete.Commands.StartBackgroundService(FSharpOption`1 workspaceDir)
   ved FsAutoComplete.Lsp.Initialize@262.Invoke(Unit unitVar)
   ved Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   ved Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by janpop2017** [comment]
Enabling Ionide-fsharp causes this error.

**Comment by janpop2017** [comment]
Is this a VSC issue or a Ionide-fsharp issue
. I have reported this issue to Ionide-fsharp Github

**Comment by sandy081** [comment]
Please file issue against the extension
