### ISSUE TITLE
Github Repo - Release Notes with Releases

### ISSUE THREAD

**Issue by BloodyIron** [microsoft/vscode#76146]
Can we please get Release Notes for each Release on the Github page for this? It's just the release files, no comments on changes, etc.

Maybe? :)

**Comment by BloodyIron** [comment]
Yeah already checked, the other things were not relevant.

**Comment by egamma** [comment]
We treat the release notes as documentation and manage them in the vscode-docs repository and make them available on the VS Code Web Site https://code.visualstudio.com/updates.

Can you give an example of what you are looking for?

**Comment by BloodyIron** [comment]
Here's an example, each release links to the changes applied, and talks about functional changes as a result : https://github.com/vector-im/riot-web/releases

The point is seeing what's different from this release compared to last.

**Comment by egamma** [comment]
>each release links to the changes applied, and talks about functional changes as a result 

We cover functional changes in the release notes, we currently have no plans to change it.
During an iteration the release notes cover the closed issues and the commit history, pls see https://github.com/microsoft/vscode-docs/blob/1d60c1dacef300f73915e7bc475c5f1a412e9b36/release-notes/v1_36.md.

**Comment by BloodyIron** [comment]
Yeah that's not the point of this. This is a feature request, I'm not asking about your current "plans".

Many many many Open Source groups on GitHub and elsewhere post the release notes in the release section, and it helps a lot. It's a consistent way to present that information, and such information can be automated.

**Comment by joaomoreno** [comment]
I created the September releases and will propose to the team to have this happen every time we release. https://github.com/microsoft/vscode/releases

In any case, suggestion taken, this issue can be closed.
