### ISSUE TITLE
Azure Extension sropped working

### ISSUE THREAD

**Issue by maristhek** [microsoft/vscode#76154]
Issue Type: <b>Bug</b>

Open Node/express project in VS Code
Click on Azure symbol 
Response is : No subscriptions Found
The error is pop-up pops in an endless loop with on a small sliver of the window showing

This is on a project that is already published !!!!!!!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-wasm|dts|1.2.1
vsc-material-theme|Equ|2.9.0
vscode-azureappservice|ms-|0.15.0
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
Go|ms-|0.11.0
heroku-command|pko|0.0.8

(7 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Please file issue against the azure extension.

**Comment by maristhek** [comment]
> Please file issue against the azure extension.

Thank you for all your help !!!!!!
