### ISSUE TITLE
Git checkout panel: divider line after local, option to sort branches by remotes

### ISSUE THREAD

**Issue by ADIX7** [microsoft/vscode#76156]
Please add a divider after local branches on the checkout panel (maybe an option to turn it on/off). Something like on the command palette when you start typing there is a divider after recent commands.
An other great thing would be remote branches grouped by remotes also with dividers.

**Comment by joaomoreno** [comment]
This is currently not supported in the quick open API. @chrmarti Do you already have feature requests for this?

**Comment by chrmarti** [comment]
Reopening for tracking the Git side of this. Depends on #74967.
