### ISSUE TITLE
Use 'vscode', Congratulations, on getting a crashed computer!!!

### ISSUE THREAD

**Issue by MeetTheBest** [microsoft/vscode#76153]
![](https://ws1.sinaimg.cn/large/005zMGWfly1g4ejq4514tj30iv07tgn3.jpg) 

Every time i can only force reboot!!!

**Comment by jdz321** [comment]
dàn dìng，yǒu huà hǎo shuō ...

**Comment by sandy081** [comment]
Sorry for that. Can you please provide us information about the crash by following the wiki - https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
