### ISSUE TITLE
There is a problem with the Linux terminal

### ISSUE THREAD

**Issue by kekeqy** [microsoft/vscode#76158]
Issue Type: <b>Bug</b>

When you scroll the middle mouse button on a Linux terminal, the terminal prints strange characters like "^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A".

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-30deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3775)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.72GB (2.19GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.2.6
csharp|ms-|1.20.0
vetur|oct|0.21.0
unity-tools|Tob|1.1.1
unity-debug|Uni|2.7.2

</details>

**Comment by Tyriar** [comment]
This is sent when you're in an application that enables mouse events and doesn't handle it. What were you running at the time?

**Comment by kekeqy** [comment]
I executed a command.

rollup v1.14.2
bundles ./src/front/index.js → static/script/preview.js...
created static/script/preview.js in 2.1s

[2019-06-27 09:52:19] waiting for changes...
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A

**Comment by Tyriar** [comment]
Are you using tmux or screen?

**Comment by kekeqy** [comment]
No,I’m not.

**Comment by Tyriar** [comment]
Can you share your settings.json and also a screenshot of the terminal which also shows the dropdown?
