### ISSUE TITLE
Debug: Watch Add expression remains disabled if an expression is added while editing another expression

### ISSUE THREAD

**Issue by reappciona** [microsoft/vscode#76168]
- VSCode Version: 1.35.1
- OS Version: Windows 10 Professional 64bit

Steps to reproduce:
  1.- Create an expression in the debugger Watch section (i. e. 1 === 1)
  2.- Edit this expression and press the Add button to add another expression

Expected results:
The edited expression is saved (same as exiting the edition) and a new expression field is generated (same as clicking Add expression) ready to be edited. Adding should remain possible

Actual results:
The edited expression is saved and a new expression field is created but it's created inactive 2 slots under the last watched expression. The Add button remains disabled until Remove all expressions is clicked. Then the functionality is operative again

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for reporting this.
Now when you are editing a watch expression the + add is disabled.
