### ISSUE TITLE
Extensions stops working

### ISSUE THREAD

**Issue by khomaldi** [microsoft/vscode#76169]
Issue Type: <b>Bug</b>

All extensions stops working some times after work.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-7500 Radeon R7, 10 Compute Cores 4C+6G   (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.95GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.1.0
sftp|lix|1.12.7
python|ms-|2019.6.22090
vscode-icons|vsc|8.8.0

</details>

**Comment by sandy081** [comment]
What do you mean by extensions stop working? Is there a crash or freeze or any performance issues?

It could be that one of the extensions is causing this. Please try disabling one by one and figure out which one is causing this.

Following wikis can help you in getting some info

https://github.com/microsoft/vscode/wiki/Performance-Issues

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
