### ISSUE TITLE
VSC opens another file instead of the file I clicked on

### ISSUE THREAD

**Issue by gdfdfgd** [microsoft/vscode#76164]
I do my project on 2 computers. The first one is at the office, the second one is at my home. I began to write file react_1.html at the office, then sent it by Skype to myself. At home I opened the file, wrote some more code, saved it with the same name (react_1.html - date 25/06/2019 - 21:42) and sent it back to myself using Skype. On the next day, in the office, I download the file from the Skype (react_1.html - date 25/06/2019 - 21:42) and tried to open it in the VSC, but it opened not the current version of the file, but old version, saved somewhere in the memory of VSC. I opened it several times and it still showed me not the proper content of the file. Then I tried to rename it - and finally VSC really open the file I wanted to.
[Here is the video of the prosess](https://drive.google.com/open?id=1VdJqSgPik7lvDdnxDB6pUZFMVgH2vQOS)

**Comment by bpasero** [comment]
VSCode itself is not doing any caching. Was the file dirty maybe?
