### ISSUE TITLE
Git panel shows changes that git status doesn't

### ISSUE THREAD

**Issue by pcolmer** [microsoft/vscode#76160]
Issue Type: <b>Bug</b>

git clone https://github.com/96boards/ai.git
git status

Expected output (since I've just cloned it):

On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean

However, the git panel shows 33 modified files.

Worse is https://github.com/devicetree-org/devicetree-website.git which VSCode believes has 605 modified files!

VS Code version: Code - Insiders 1.36.0-insider (41691474e5fa22a279d49fc4b58af66bc11ce41b, 2019-06-26T05:20:29.762Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.64.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.2
vscode-remote-extensionpack|ms-|0.15.0

</details>

**Comment by joaomoreno** [comment]
I can't repro this on mac or Windows. Can you repro on another machine?

**Comment by pcolmer** [comment]
I've asked a colleague to test this and he doesn't see what I'm seeing.

What can I do/test in order to progress this? What other information can I provide?

**Comment by pcolmer** [comment]
Just in case, I was using 2.20.1.windows.1. I've upgraded to 2.22.0.windows.1 but I'm still seeing the same problem.

**Comment by joaomoreno** [comment]
Not really sure. Do you only have one git installed?

**Comment by pcolmer** [comment]
I've got "Git for Windows" installed and, from the git output that VS Code displays, that is the git executable that is being used, in that the version number displayed by VS Code matches the version of GfW that I upgraded to yesterday.

Are there any git commands I can run to try and help with this? I tried manually running the commands that VS Code is using (from the output window) but I think I'm not seeing everything that VS Code sends to git.

**Comment by joaomoreno** [comment]
> I think I'm not seeing everything that VS Code sends to git.

Code does nothing other than what's on the git output.

Not sure... never really seem this before. Which 33 files are modified?

**Comment by pcolmer** [comment]
It looks like it may be something odd either with my copy of the repository or with Git for Windows.

I was previously running "git status" under WSL and getting no errors. Now, if I run "git status" under Windows, I see the same 33 modified files that VS Code is seeing *but* I cannot clear those "changes". I can't remember whether I cloned the repo via Windows or WSL but I'll start again and see what happens.

Apologies for the noise.

**Comment by pcolmer** [comment]
Confirmed - if I clone the repo using WSL onto a Windows filing system, it messes things up somehow. I have to clone the repo using Windows.
