### ISSUE TITLE
Struct member with a name starting by a variable type is not seen as it (no color highlight for example)

### ISSUE THREAD

**Issue by LeandreBl** [microsoft/vscode#76165]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04.2

The problem does not occur when the file is tagged as a C++ file, only in C (not tried for other languages)

This occurs when --disable-extensions flag is set too

Steps to Reproduce:

1. Write any line, in a C tagged file, with the syntax of a structure usage
2. For example
```c
int main(void)
{
    im_a_struct.im_a_member = 0; /* works fine */
    im_a_struct.integer_member = 0; /* starts with a variable type "int", no color */
    im_a_struct.size_t_holder = 0; /* does not work too */
    im_a_struct.intra_thread = thread(); /* same issue, starts with "int" */
    im_a_struct.long_array = malloc(10000); /* "long" keyword */
}
```

**Comment by N-Bz** [comment]
Example of this in action:
<img width="371" alt="Capture d’écran 2019-06-26 à 11 28 42" src="https://user-images.githubusercontent.com/2073206/60169497-17066980-9807-11e9-81d8-abad81eb2bd1.png">

Screenshot taken on Version 1.35.1, macOS Mojave 10.14.5, extensions disabled.

**Comment by alexr00** [comment]
Moved to the owner of the grammar.
