### ISSUE TITLE
Diff highlights wrong lines

### ISSUE THREAD

**Issue by shikhov** [microsoft/vscode#76177]
Issue Type: <b>Bug</b>

New lines: 4 and 5. Highlighted: 6 and 7 (see screenshot)
![2019-06-26_173702](https://user-images.githubusercontent.com/9966764/60180855-66b25880-983a-11e9-8f5e-6a0624eb86e4.png)

**Comment by alexandrudima** [comment]
@shikhov The diff algorithm ignores trim whitespace by default. You can press this button to toggle that trim whitespace should not be ignored:
![image](https://user-images.githubusercontent.com/5047891/62523075-4e6b2b80-b833-11e9-82f4-91a63d1433af.png)

Ignoring trim whitespace means that lines with different indentation, but with equal content are considered equal by the diff algorithm, i.e.:
```
else
```
is equal to
```
    else
```
