### ISSUE TITLE
File/folder picker: Open in new window with Ctrl/Cmd

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#76173]
Open Recent and the Welcome page use the convention that a new window is opened when the user hold Ctrl/Cmd when clicking a file/folder / pressing Enter. (QuickOpen opens a new editor group.)

Especially for folders this is very convenient.

**Comment by alexr00** [comment]
This will need to be reconciled with how we do multi-select if we want to support it.

**Comment by chrmarti** [comment]
These might be hard to reconcile. Maybe add a setting when the second one is implemented?

**Comment by alexr00** [comment]
Discussed with @chrmarti since this would be very useful for the containers extension. Decided to add an inline action on items to open in new window.

**Comment by alexr00** [comment]
I'm not going to get to this in the next 3 days. Moving to December.
