### ISSUE TITLE
Extension Host Keeps Crashing

### ISSUE THREAD

**Issue by GingerGraham** [microsoft/vscode#76178]
Issue Type: <b>Bug</b>

1. Launch VS Code Insiders
2. Observe error notification reporting that the Extension Host has crashed
3. Click option in notification to restart Extension Host
4. Observe that the Extension host is now stable

Unable to provide further details as to what is causing the Extension Host to crash at this time, other than a possible guess that perhaps one of the extensions I have installed might be causing this?

VS Code version: Code - Insiders 1.36.0-insider (41691474e5fa22a279d49fc4b58af66bc11ce41b, 2019-06-26T05:20:29.762Z)
OS version: Windows_NT x64 10.0.18922

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.28.0
docs-article-templates|doc|0.2.5
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.9
docs-preview|doc|0.3.23
docs-yaml|doc|0.2.3
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.2
vscode-pull-request-github|Git|0.8.0
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
azure-pipelines|ms-|1.152.0
azurerm-vscode-tools|msa|0.6.0
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.6.4
vscode-language-pack-en-GB|MS-|1.36.1
mssql|ms-|1.6.0
python|ms-|2019.6.22090
remote-containers|ms-|0.64.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.3
vscode-remote-extensionpack|ms-|0.15.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
typescript-javascript-grammar|ms-|0.0.50
vscode-node-azure-pack|ms-|0.0.8
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.471
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
team|ms-|1.149.2
ruby|reb|0.23.0
java|red|0.46.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.3.1
code-spell-checker|str|1.7.17
vscodeintellicode|Vis|1.1.7
azure-iot-toolkit|vsc|2.8.0

</details>

**Comment by sandy081** [comment]
Yeah it could be due to vsliveshare-audio - https://github.com/MicrosoftDocs/live-share/issues/1916
