### ISSUE TITLE
Refresh .vscode/tags file

### ISSUE THREAD

**Issue by SiddharthPant** [microsoft/vscode#76172]
The current tags file lookup is snappy and good. But over a day when you are frantically coding, it becomes stale. For now my solution is to delete tags file and Ctrl+t search a class which creates it back. It will be good if it is a method within the Ctrl+Shift+P to refresh tags file based  on your current codebase.

**Comment by roblourens** [comment]
Are you using an extension for this? If so please file the issue on the extension.

**Comment by SiddharthPant** [comment]
@roblourens thanks. I realized this is a vscode-python extension issue. And they already have an implementation of the feature. You do Ctrl+Shift+p > "Build Workspace Symbols". So I am closing the issue now.
