### ISSUE TITLE
Intellisence feature is lost when loading outline or definition indefinitely

### ISSUE THREAD

**Issue by mmt4417** [microsoft/vscode#76179]
Issue Type: <b>Bug</b>

1) Ctrl + click a method - Sometimes this takes indefinite time and causes loss of intellisence
2) Same for loading outline.

I have to reopen the folder inorder to make everything work again. In that case point 1 and 2 works fine.

Language - Python3

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.9.0
vscode-docker|ms-|0.6.4
python|ms-|2019.3.6558

</details>

**Comment by sandy081** [comment]
Related to python extension. Please file issue against it.
