### ISSUE TITLE
Terminal: Ctrl/Cmd + Click does not trigger port forwarding

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#76175]
When Ctrl-/Cmd-clicking in a remote terminal the port forwarding that `openExternal()` is using should trigger too.

**Comment by Tyriar** [comment]
I'm not sure what this means:

> the port forwarding that openExternal() is using should trigger too.

**Comment by chrmarti** [comment]
@mjbvz has added functionality to `openExternal()` that starts port forwarding when called on the remote extension host with a localhost http/s URL, so the browser on the host machine can reach the port on the remote side.

For remote terminals the same port forwarding could be applied, so localhost http/s URLs work when Ctrl-/Cmd-clicking them to open.

**Comment by Tyriar** [comment]
@mjbvz do you have a link to the code?

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/blob/0358d08196cece5b0652cd87528b0ebc409e0d7f/src/vs/workbench/api/browser/mainThreadWindow.ts#L51

We could consider moving this logic to a higher layer in the code, such as the opener service
