### ISSUE TITLE
`ctrl + r`  opens recent instead of refreshing reload menu

### ISSUE THREAD

**Issue by kalpaj12** [microsoft/vscode#76170]
- Version: 1.35.1
- OS: Linux x64 5.0.0-19-generic

Steps to Reproduce:

1. `ctrl + shift + p` and search for reload window ( **Note:** On the right hand side, the keybinding assigned for reload window is `ctrl + r`)
2. try `ctrl + r` . this opens recent window, instead of refreshing workspace.

Video demo [here.](https://drive.google.com/open?id=13pnBZTQw0uPv9lpInH3NZZ-jpSCyOspx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
You can change the keybinding to `Reload Window` command from the keybindings editor.
