### ISSUE TITLE
format-on-type indentation places cursor in wrong position

### ISSUE THREAD

**Issue by df-adam** [Microsoft/vscode#7617]
- VSCode Version: 1.3.0-insider 51e9802304ee59dcc1d05ec15f26ec5019e28f48
- OS Version: MacOS 10.10.5 Yosemite

Steps to Reproduce:
1. install vscode
2. install legacy C# extension
3. set "editor.formatOnType": true, "editor.insertSpaces": false, in user preferences
4. Create a function with no indentation:

```
void Foo()
{
int i = 10
}
```
1. place a semicolon at the end of the variable declaration
2. observe auto-formatted code

expected:
variable declaration indents, cursor remains at the end of the line

```
void Foo()
{
    int i = 10;
               ^ cursor should be here
}
```

observed:
the indentation is performed, but the cursor is left between the 'i' and the '=' causing any additional typing to unexpectedly appear inline

```
void Foo()
{
    int i = 10;
         ^ cursor is here
}
```

**Comment by jrieken** [comment]
The cursor is set by the edit operation

**Comment by alexandrudima** [comment]
This appears to work correctly when I have tried now with the latest C# extension
