### ISSUE TITLE
Different background colors for different languages in a multi-language file

### ISSUE THREAD

**Issue by RayZ-O** [Microsoft/vscode#7618]
I want to make my multi-language files(such as PHP or ruby on rails) more readable by having different background colors for different languages .

For TextMate it's possible to set particular background color for different scope.[TextMate manual: Theme](https://manual.macromates.com/en/themes), I tried to do it on vscode but it doesn't work.

I also tried the color themes on this blog posts: [Rails TextMate Themes](http://astonj.com/wp-content/uploads/2011/04/view_vibrantink.gif). I still can't get different background colors for the two languages.

**Comment by dbaeumer** [comment]
@aeschli not sure if you or @alexandrudima

**Comment by aeschli** [comment]
Themes can set the background colors, but in VCOde we ignore these as it conflicts with other background colors (selection, mark occurrence, find replace...)
To make this work we would need to invest time in using transparency everywhere.

**Comment by aeschli** [comment]
Not planned.
