### ISSUE TITLE
Crashes with accessing Help > Release Notes

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#76183]
Issue Type: <b>Bug</b>

On my Mac, 50% chance of VSC crashing when accessing Help > Release notes menu item with the mouse.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.87GB free)|
|Process Argv|-psn_0_1651091|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
beautify|Hoo|1.5.0
remote-containers|ms-|0.59.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
Go|ms-|0.11.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Is it possible to provide any crash related logs or info to know where the crash happens? You can also follow this wiki https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by leegee** [comment]
[Code Helper_2019-06-26-101732_Lees-MacBook-Pro.crash.txt](https://github.com/microsoft/vscode/files/3333464/Code.Helper_2019-06-26-101732_Lees-MacBook-Pro.crash.txt)
[Electron_2019-06-26-154336_Lees-MacBook-Pro.crash.txt](https://github.com/microsoft/vscode/files/3333465/Electron_2019-06-26-154336_Lees-MacBook-Pro.crash.txt)
[Electron_2019-06-26-154411_Lees-MacBook-Pro.crash.txt](https://github.com/microsoft/vscode/files/3333466/Electron_2019-06-26-154411_Lees-MacBook-Pro.crash.txt)
[Electron_2019-06-26-154600_Lees-MacBook-Pro.crash.txt](https://github.com/microsoft/vscode/files/3333467/Electron_2019-06-26-154600_Lees-MacBook-Pro.crash.txt)

**Comment by leegee** [comment]
Hope that helps  — please let me know if otherwise.

**Comment by sandy081** [comment]
@deepak1556 Assigning to you as I do not see any instance of our code. Please take a look.

**Comment by deepak1556** [comment]
```
void std::__1::vector<linked_ptr<media::VTVideoDecodeAccelerator::Frame>, std::__1::allocator<linked_ptr<media::VTVideoDecodeAccelerator::Frame> > >::__push_back_slow_path<linked_ptr<media::VTVideoDecodeAccelerator::Frame> const&>(linked_ptr<media::VTVideoDecodeAccelerator::Frame> const&&&) (in Electron Framework) (vector:1578)
media::WebMClusterParser::Track::ApplyDurationEstimateIfNeeded() (in Electron Framework) (webm_cluster_parser.cc:732)
media::WebMClusterParser::~WebMClusterParser() (in Electron Framework) (webm_cluster_parser.cc:69)
af_glyph_hints_reload (in Electron Framework) (afhints.c:819)
WTF::HashTable<blink::Member<blink::CSSStyleSheet>, WTF::KeyValuePair<blink::Member<blink::CSSStyleSheet>, blink::Member<blink::InspectorStyleSheet> >, WTF::KeyValuePairKeyExtractor, WTF::MemberHash<blink::CSSStyleSheet>, WTF::HashMapValueTraits<WTF::HashTraits<blink::Member<blink::CSSStyleSheet> >, WTF::HashTraits<blink::Member<blink::InspectorStyleSheet> > >, WTF::HashTraits<blink::Member<blink::CSSStyleSheet> >, blink::HeapAllocator>::find(blink::CSSStyleSheet*) (in Electron Framework) (HashTable.h:753)
blink::MarginInfo::MarginInfo(blink::LayoutBlockFlow*, blink::LayoutUnit, blink::LayoutUnit) (in Electron Framework) (LayoutBlockFlow.h:783)
blink::LayoutBlockFlow::SetMaxMarginBeforeValues(blink::LayoutUnit, blink::LayoutUnit) (in Electron Framework) (Partitions.h:121)
blink::LayoutBoxModelObject::StyleWillChange(blink::StyleDifference, blink::ComputedStyle const&) (in Electron Framework) (ComputedStyle.h:2074)
blink::ThreadDebugger::GetEventListenersCallback(v8::FunctionCallbackInfo<v8::Value> const&) (in Electron Framework) (Vector.h:1285)
blink::LayoutBox::UnmarkOrthogonalWritingModeRoot() (in Electron Framework) (LayoutBox.cpp:5074)
```

stack trace shows its in the media layer from chromium.

**Comment by deepak1556** [comment]
@leegee I am unable to repro this crash, moving forward I would suggest the following workaround with version 1.35.1. Can you try launching code like:

```
$ code --disable-accelerated-video-decode
```

and see if the crash still exists ?

I would suggest updating code to 1.36 which should resolve this issue as well, this just a guess based on the changes that went into the media code path in chromium. If it still exists after updating I can look into it further. Thanks!

**Comment by leegee** [comment]
It's fine with 1.36 on OSX 14, thanks!
