### ISSUE TITLE
Macbook's ForceTouch dose not trigger dictionry in vscode

### ISSUE THREAD

**Issue by noisnemid** [microsoft/vscode#76182]
Issue Type: <b>Bug</b>

can't call the dictionary app by force clicking on the macbook's forcetouch track pad.

new product series of Macbook of Apple company has been shipped with a Trackpad, and it has a two-stepped force touch operation for usess. If users click the trackpad and hold the finger and push hard downward, it will trigger a advanced feature, in MACOS's 'Finder' APP it triigers a preview of a file or folder, in a browser or other normal text editors, it triggers the MacOS's native Dictionary App's quick word lookup float panel. But in VSCODE, it's not working.

it has confused me for very long a time, please help verify whether it's only my computer's problem or some sort of bug?

thnaks.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y31 CPU @ 0.90GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
json-tree-view|Cha|2.6.0
vscode-express|Com|0.0.5
vscode-eslint|dba|1.9.0
javascript-ejs-support|Dig|0.5.0
prettier-vscode|esb|1.9.0
vscode-language-pack-zh-hans|MS-|1.35.1
python|ms-|2019.6.22090
vetur|oct|0.21.0
rust|rus|0.6.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.7
vscode-preview-server|yui|1.2.1
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by sandy081** [comment]
May I know what is the dictionary app and how it can be related to VS Code?

**Comment by noisnemid** [comment]
<img width="797" alt="dictionary_app3" src="https://user-images.githubusercontent.com/16525011/60252032-274c4080-98fc-11e9-97c9-13e8c71708ec.png">
<img width="321" alt="dictionary_app" src="https://user-images.githubusercontent.com/16525011/60252036-27e4d700-98fc-11e9-806e-8ee139ab58ed.png">
<img width="684" alt="browsers" src="https://user-images.githubusercontent.com/16525011/60252038-27e4d700-98fc-11e9-8fc9-10cba4265ec1.png">
<img width="662" alt="in_bash" src="https://user-images.githubusercontent.com/16525011/60252039-287d6d80-98fc-11e9-9e3c-0a00d519bcca.png">
<img width="720" alt="in_desktop_or_finder" src="https://user-images.githubusercontent.com/16525011/60252040-29160400-98fc-11e9-95ea-023451a3d8e7.png">
<img width="579" alt="in_text_edit_of_macos" src="https://user-images.githubusercontent.com/16525011/60252041-29160400-98fc-11e9-8624-01bd65e1c420.png">
<img width="612" alt="bash" src="https://user-images.githubusercontent.com/16525011/60252044-29ae9a80-98fc-11e9-8e7e-390ae65fb618.png">
<img width="287" alt="dictionary_app_about" src="https://user-images.githubusercontent.com/16525011/60252045-29ae9a80-98fc-11e9-987a-d816476490db.png">
<img width="626" alt="in_typora" src="https://user-images.githubusercontent.com/16525011/60252048-2a473100-98fc-11e9-85a2-a4114634a0f0.png">

**Comment by sandy081** [comment]
Thanks for the info. I see now that dictionary app is not showing up in the editor with the mouse gesture you mentioned - `click the trackpad and hold the finger and push hard downward`

**Comment by noisnemid** [comment]
Hmmm, I think, maybe it's not some features of theDictionary App, and maybe it's the feature of the Finder(MacOS's GUI file manager)?
