### ISSUE TITLE
Module Javascript block has no syntax highlighting in Pug

### ISSUE THREAD

**Issue by csvn** [microsoft/vscode#76181]
Issue Type: <b>Bug</b>

The built-in Pug basic language support extension does not give any syntax highlighting for `<script type="module">` code. Regular `<script>` tags work as they should (including when `type="text/javascript"` is used). Sorry in advance if I filed this bug in the wrong project (I assume that bugs with built-in extensions belong here).

### Steps to Reproduce:

1. Open a `.pug` file with built-in Pug extension active
2. Add a `script(type="module").` block
3. Write any Javascript
4. Content is formatted as plain text

![image](https://user-images.githubusercontent.com/8770194/60187439-e128ab80-982d-11e9-973c-192fd12176b8.png)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (12.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
lit-html|bie|1.11.0
githistory|don|0.4.6
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
gitlab-workflow|fat|2.1.0
auto-rename-tag|for|0.1.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
vscode-docker|ms-|0.6.4
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.5
preview-control-characters|nes|0.0.1
java|red|0.46.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.3.1
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-icons|vsc|8.8.0
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by alexr00** [comment]
Moved to the owner of the pug grammar.
