### ISSUE TITLE
Progress indication when installing extensions

### ISSUE THREAD

**Issue by eyalroth** [microsoft/vscode#76189]
I'm not exactly sure if this is a feature request or a bug, since this has come up in the past in both #2835 and #4621 which are closed, but I'm not seeing any indication when installing extensions.

Version info:
```
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by sandy081** [comment]
@eyalroth There is an indicator on top of the extensions view and also on the side bar. You can see a moving blue bar on the top and a busy indicator on the extensions icon on the side.

**Comment by eyalroth** [comment]
@sandy081 I see now that there is an indication in the extensions view and in that view only, and there are two major problems with this:
1. This indication is extremely small and unnoticeable.
2. It is common to install an extension without the extensions view open. For example, when searching for an extension in the browser and then clicking the installation link from there (which brings up the extension page but not the extensions view).

**Comment by sandy081** [comment]
Does not that installing an extension from browser opens the extensions viewlet?

**Comment by eyalroth** [comment]
@sandy081 No, it does not, and I believe this is a good thing.

Two more things I noticed:
 1. Initiating an installation while the extensions view is loading for the first time (perhaps after a reload) will stop the indicator after the view has finished loading, even if the installation is still ongoing.
 2. The current indicator is not a progress bar, thus not really indicating anything further than what the _installing_ button on the specific extension window already does.

**Comment by sandy081** [comment]
@eyalroth Are not you seeing the busy/progress indicator on the activity bar?

![image](https://user-images.githubusercontent.com/10746682/60400759-c5e4d580-9b78-11e9-8f53-6ef45b01f876.png)

> Initiating an installation while the extensions view is loading for the first time (perhaps after a reload) will stop the indicator after the view has finished loading, even if the installation is still ongoing.

Is it possible to repro this? If so can you please provide steps with what is expected?


> The current indicator is not a progress bar, thus not really indicating anything further than what the installing button on the specific extension window already does.

It is an infinite progress bar and this is the same design we follow across the product. I would like to understand the strong reasoning behind the need for more detailed progress here.

**Comment by eyalroth** [comment]
@sandy081 

> It is an infinite progress bar and this is the same design we follow across the product. I would like to understand the strong reasoning behind the need for more detailed progress here.

Well, the same reasoning for progress bars in any installation of basically any application on any OS (mobile included), and any plugin of any application.

This is especially important when a download is involved, as some connections are slower and it might take a few seconds to download the content (and it is very helpful for the user to know that the installation is currently downloading). For instance, the most popular extension -- Python -- weighs ~16MB, which on a slow connection (5Mbps) might take awhile (30 seconds).

For some reason the download size of an extension is not available on the marketplace - not even when initiating a manual (`.vsix` file) download from the browser (the size is only apparent upon download completion).

> Is it possible to repro this? If so can you please provide steps with what is expected?

Can't say this is easy to reproduce. I'm not sure when does the extension view take a few seconds to fully load up all of its content (instead of immediately loading up everything), but when this happens, if you start an installation which will take longer than the view will take to load all of its content, then the "busy" indicator will stop after the view has finished loading all of its content instead of waiting until the installation is finished as well. Regardless, this is an esoteric (and a separate) bug.

**Comment by sandy081** [comment]
> and it is very helpful for the user to know that the installation is currently downloading

We show these details in the log here -> `Output panel -> Log (Shared)`

![image](https://user-images.githubusercontent.com/10746682/60454512-43b9e700-9c34-11e9-8ffe-e498bf059681.png)

I see your point but not all users are concerned about such details. Given that this information is shown in logs, interesting users can follow them. I am not saying logs are complete replacement for fine grained progress reporting, but it will be helpful for users who are interested in detail.

**Comment by eyalroth** [comment]
@sandy081 That's hardly something anyone would expect finding when searching for a progress indication.

I understand that this might not be the most important feature out there, but I believe it would provide a better experience for most users.

**Comment by sandy081** [comment]
Agreed, it is a nice feature to have but not sure we will do it in near future given the priorities. If there is more demand for this, we will come back to this.

**Comment by GazziFX** [comment]
Installing extension about hour already and cant see any progress
![image](https://github.com/microsoft/vscode/assets/43498426/66afbd33-1c01-419d-9ebc-47a00aaa4657)

**Comment by mempler** [comment]
@GazziFX doing the exact same thing with the exact extension. Also took an hour WITHOUT progress indicator. Such a f- pain

**Comment by hichemfantar** [comment]
showing the total download size would be very helpful to know how much data is required and how long a download would take.
