### ISSUE TITLE
VSC debugger does not map with the source .ts file when debugging mocha tests

### ISSUE THREAD

**Issue by maximedupre** [microsoft/vscode#76186]
- VSCode Version: 1.35.1
- OS Version: macOS 10.14.5

**Current behaviour:**

The debug console shows this output when running the debug task:

	spec.js:54		1) should fail
	spec.js:88		0 passing (13ms)
	base.js:319		1 failing
	base.js:332		1) should fail:

		AssertionError: expected true to equal false
		+ expected - actual

		-true
		+false
		
		at Context.<anonymous> (out/app.spec.js:5:28)

**Expected behaviour**

The debug console should display the source file instead of the compiled file. e.g. `at Context.<anonymous> (app/app.spec.ts:5:28)`

**Setup**

`.vscode/launch.json`:

	{
		"version": "0.2.0",
		"configurations": [
			{
				"type": "node",
				"request": "launch",
				"name": "Mocha Tests",
				"program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
				"args": [
					"--colors",
					"./out"
				],
				"sourceMaps": true,
				"outFiles": [
					"${workspaceFolder}/out/**/*.js"
				]
			}
		]
	}
    
`tsconfig.json`:

	{
		"compilerOptions": {
			"outDir": "out",
			"target": "ES5",
			"esModuleInterop": true,
			"resolveJsonModule": true,
			"moduleResolution": "node",
			"strict": true,
			"sourceMap": true,
			"typeRoots": [
				"app/typings",
				"node_modules/@types"
			],
			"lib": [
				"es6",
				"es7",
				"dom"
			]
		}
	}

**Comment by weinand** [comment]
Yes, we do not map paths in the program output to source.
