### ISSUE TITLE
Document link hover text shows cmd instead of ctrl on Windows

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#76180]
![image](https://user-images.githubusercontent.com/38270282/60184390-424d8080-9828-11e9-8970-d88f29928d75.png)

**Comment by rebornix** [comment]
thanks for the quick catch, regression introduced in https://github.com/microsoft/vscode/commit/be41fd02a2141ecd0a544b08f51c414a486c4474  cc @mjbvz
