### ISSUE TITLE
Relocate `--disable extension` suggestion to start of Issue form. 

### ISSUE THREAD

**Issue by droctothorpe** [microsoft/vscode#76191]
I humbly suggest moving this line to the top of the issue form:
```
<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes/No
```
I just filled out really in-depth steps to reproduce the error I was experiencing (bash completion not working), then got to that last line, and it fixed it (even after launching without the flag).

**Comment by roblourens** [comment]
I'm glad that tip helped you but I think it's relevant in a minority of cases, so I don't think it should be the very first line in the issue template.
