### ISSUE TITLE
cache variables across debug sessions

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode#76190]
Not sure how feasible this is,
but is there a way to cache the contents of variables across debug sessions?

I have a Python pipeline that takes awhile to run, and it queries AWS s3 many times in a loop, then appends the outputs to a dictionary for each iteration of the loop.

If I'm debugging later in the pipeline, it would be nice for this to not have to happen every time I restart the debugger.

**Comment by weinand** [comment]
Caching on the debugger level isn't feasible and doesn't make sense. It would be very confusing for a developer to see cached values instead of the real value coming from the runtime.

The correct approach is to make your program cache the data.
