### ISSUE TITLE
Typing "code" from Start Menu loads inconsistent/confusing experiences

### ISSUE THREAD

**Issue by kuhlenh** [Microsoft/vscode#7619]
I gave a talk at a .NET meetup the other day and one of the attendees told me he struggled to teach new developers in VS Code because when they type "code" from the Start Menu it flashes a command-line window and then loads VS Code (making them think something failed). 

It also has different behavior based on what version of Windows you have (default going to the cmd vs the app):
![image](https://cloud.githubusercontent.com/assets/1402694/16017047/fc0a4ee4-3152-11e6-9f92-e6bc796c0014.png)
![image](https://cloud.githubusercontent.com/assets/1402694/16017065/0a49a996-3153-11e6-8b93-f46749afcf37.png)

**Comment by hydranix** [comment]
could the CALL command be replaced with the START command in code.cmd?

**Comment by joaomoreno** [comment]
@hydranix: #6608

**Comment by aarondandy** [comment]
@kuhlenh Thanks for making this issue for me. It is really reassuring to see that us little people are being heard.

@hydranix I tried that on my Windows 10 machine and it totally had the desired results from the start menu and does not appear to affect the command line experience. I did some testing for the environment variables and they do appear to be copied before they are undone by `endlocal`

`start "" "%~dp0..\Code.exe" "%~dp0..\resources\\app\\out\\cli.js" %*`

@joaomoreno I was unable to replicate the issue that you linked but running that same command with my modified batch file still offered the same experience.

**Comment by joaomoreno** [comment]
As mentioned in #6608, once you switch to `start` you lose the `--wait` and `--verbose` command line flags: the command simply returns immediately.

**Comment by aarondandy** [comment]
I missed that but I understand now. Challenge accepted!

**Comment by joaomoreno** [comment]
Update from the Windows team:

> The `code.bat` shows up in the best match position 0 as a command (and not as a document). I do agree showing the VS Code app in position 0 instead will be more ideal here.

> Note that the ranking of search results is personalized, so if users select the VS Code app the first time they search using the query “code”, all subsequent searches using this query will start showing the app in the top position.

**Comment by aarondandy** [comment]
The behavior you describe does not happen on my machine or on any others I have seen. Is that new behavior in a fast ring build? If so, that will solve it in time for most users. I am on 1607 (OS Build 14393.82)

**Comment by joaomoreno** [comment]
Reply from the Windows team:

> This issue has been fixed since September 8th, the commands are no longer forced to the top.
> ![image](https://cloud.githubusercontent.com/assets/22350/18888792/20a20dfa-84fa-11e6-8bb0-0ed68177a370.png)

**Comment by Tyriar** [comment]
Marking upstream as it's a Windows problem.

**Comment by aarondandy** [comment]
I can confirm the fix on my computer as well as the computers of other people I have checked. It is in the wild now.
