### ISSUE TITLE
.eslintignore is  not working  in VS Code  May 2019 (1.35.1) on MacOS Mojave 10.14.5

### ISSUE THREAD

**Issue by IndeDude** [microsoft/vscode#76194]
Issue Type: <b>Bug</b>
create file .eslintignore in project root folder
enter the following.
`**/*.json`
save file
start up VS Code
enable eslint 
set eslint run onType
create jsconfig.json (or any json file of your preference)
and enter the following:

  ```
"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "*",
      "src/*",
      "assets/*"
    }
  }
}
```

save the file

open any javascript/jsx file
and you will see eslint report problems for jsconfig.json

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>c
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_2609789|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Moved to https://github.com/microsoft/vscode-eslint/issues/697
