### ISSUE TITLE
Test Electron 4 Webview mouse workaround

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76198]
Test for #75090

- [x] Mac @octref 
- [x] Linux @RMacfarlane 
- [x] Windows @gregvanl

Complexity: 4

**Overview**
There is an electron bug that causes mouse events to not work properly when interacting with webviews (specifically, if you click in the main editor and then mouseup in a webview, the main editor never gets a `mouseup` event). You can see this by opening a markdown preview to the side and then trying to drag the editor sash to resize it

To address this, I've added a workaround that emulates mouse events. However this workaround is not perfect and it may break more complex webview extensions. We need to see if the workaround is viable and what it potentially regresses 

**Testing**
In your assigned platform, install some popular webview extensions. For example:

* Our release notes
* Our extension pages
* gitlens
* sql
* cosmos
* Excel viewer
* Browser preview
* ...

Test the basic functionality of these extensions, specifically around clicking on things

Then test the original bug from #75090 by opening the webview next to another editor and dragging to resize

**Comment by octref** [comment]
I did release notes, ext pages, gitlens, excel, browser preview, polacode. The fix seems good to me.

**Comment by RMacfarlane** [comment]
I'm still sometimes able to reproduce the original issue of drag continuing after mouse up, not very consistently, though. I spent a long time dragging the terminal up over an extension page, quickly switching to moving the mouse downwards while releasing the button. But with the fix it's now possible to get out of that state by clicking!

I also tested release notes, gitlens, excel, browser preview, and GHPR.

**Comment by gregvanl** [comment]
Looks pretty good. Feels jumpier to me but sliding the sash like a toddler probably isn't an important scenario.
With the in-product release notes, there is brief flash when a narrow pane is rendered on the right side but it doesn't persist or get stuck in the narrow layout.
