### ISSUE TITLE
Git: Add command for git stash drop

### ISSUE THREAD

**Issue by leocb** [microsoft/vscode#76195]
Issue Type: <b>Bug</b>

When poping a stash and there are merge conflicts between the stash and current code, even after the conflict is resolved, the pop'ed stash isn't dropped from the stash list.
The only way to drop a stash in vscode, AFAIK, is by successfully merging a stash, meaning that if a stash is no longer relevant (only conflicts, never merged), it can never be dropped from within vscode, only by a terminal command.

my suggestion is: when there are conflicts, let the user choose whether to resolve the conflicts or to just drop the stash.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by joaomoreno** [comment]
> When poping a stash and there are merge conflicts between the stash and current code, even after the conflict is resolved, the pop'ed stash isn't dropped from the stash list.

This is how git works. If you run `git stash pop` and the stash can't be popped, the stash will not be dropped. We will not deviate from Git's behavior here.

If you want to drop a stash, we can add a command for that. Would you like to submit a PR for that?

**Comment by leocb** [comment]
I see, makes sense. Where should I place this stash drop feature? just in the command pallet or also in the git "more actions" (3 dots) menu?
If I manage to get some free time I will try to open a PR. But if anyone else wants to do it, please go ahead! :)

**Comment by drew212** [comment]
I have a prototype working for this, want to check a few things and I'll submit a PR.
