### ISSUE TITLE
Don't scroll to top when removing entries from recently opened

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76193]
Repro:

1. Trigger recently opened
2. Scroll down
3. Press x on one of the entries

The view will be scrolled to the top, making it much more difficult than it needs to be to clean out entries you no longer want in recently opened.

**Comment by bpasero** [comment]
Could be the picker widget behaviour, not sure. Does it have API to remove items individually?

//cc @chrmarti

**Comment by bpasero** [comment]
Yeah I cal [`lIQuickPickItemButtonContext#removeItem()`](https://github.com/Microsoft/vscode/blob/b7265738444f1eee05762341b4361ee6452a4154/src/vs/platform/quickinput/common/quickInput.ts#L249)

Leaving it up to @chrmarti if this is a bug or not.

**Comment by TylerLeonhardt** [comment]
verification steps:

* Trigger recently opened
* Scroll down
* Press x on one of the entries (not the highlighted one)

The cursor should stay put.

**Comment by lramos15** [comment]
Still seeing this

**Comment by TylerLeonhardt** [comment]
Ah... I fixed the issue on the active item persisting but not the scroll.

**Comment by TylerLeonhardt** [comment]
duping this to #109969 as we will fix this generically.
