### ISSUE TITLE
The program freezes

### ISSUE THREAD

**Issue by lucasrivoiro** [Microsoft/vscode#762]
The problem that causes the software crash continues even after the last update. But I noticed that after finishing some cases the own code, he comes back to work and I come across some error messages.

"Error from the plugin host: write EPIPE"
"Plugin host terminated unexpectedly. Please restart VSCode to recover"
"Error from the plugin host: channel closed"

If I restart the program VSCode happen again, but if I continue to use after finishing processes, can work normally, but can not open the folder from another project.

![error](https://cloud.githubusercontent.com/assets/9867694/11447088/879368ec-9527-11e5-9b29-4b4c11d94a2b.png)

**Comment by alexandrudima** [comment]
@lucasrivoiro 
* What exact version of VSCode are you using?
* Is this happening when opening a certain folder?
* Is this happening when opening a new window without a folder (`Ctrl-Shift-N`)?
* Did you install any extensions?

**Comment by bpasero** [comment]
@lucasrivoiro ping

**Comment by bpasero** [comment]
Reopen when we have more info.

**Comment by vilaskadam** [comment]
Facing the same issue. 
Just updated to the new version.
Error : Plugin host terminated unexpectedly. Please restart VSCode to recover.

- version is 0.10.6
- happens for all the folders
- The error occurs when opening a new window without a folder
- no extensions installed 

The only trigger that i can think about is, i was trying to install an extension but i am behind a proxy so cant install it. After this incident i started getting the above mentioned error.

**Comment by bpasero** [comment]
@vilaskadam does it reproduce when you run `code --disableExtensions` ?

**Comment by vilaskadam** [comment]
it still reproduces using the --disableExtensions flag

**Comment by bpasero** [comment]
@vilaskadam can you check if there is something in the extensions folder on disk? That one goes into your user home directory/.vscode/extensions? If so, can you temporarly delete the contents and then restart? If it reproduces please share those contents with us.

**Comment by vilaskadam** [comment]
my extensions folder is empty.
I tried reinstalling again still same issue.

**Comment by bpasero** [comment]
are you opening a specific folder? does it reproduce after File | Close Folder

**Comment by vilaskadam** [comment]
I have tried that too. 
The error reproduces even when i am not opening a folder. And once i close the error notification.
I can create a new file and type into it but cant really edit/delete anything.
All the menu options stop working too.

**Comment by bpasero** [comment]
@vilaskadam anything in the console (show from help | toggle developer tools)?

**Comment by vilaskadam** [comment]
Here is the console output, when I have opened a new window of editor and no files opened
---------------------------
connect ENOENT \\.\pipe\Code-6c3a8d-shared-sock: Error: connect ENOENT \\.\pipe\Code-6c3a8d-shared-sock
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:91
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:63 Plugin host terminated unexpectedly. Please restart VSCode to recover.e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:63
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67 Plugin host terminated unexpectedly. Code:  0  Signal:  null(anonymous function) @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67
index.html:24 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html:24
index.html:27 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Client.js:67:25)
    at e.log (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90:22274)
    at t.handleEvent (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:31955)
    at t.e.publicLog (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:29133)
    at t.e.flushErrorBuffer (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:27142)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:27002onError @ index.html:27
C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Client.js:67 Uncaught TypeError: Cannot convert object to primitive value
------------------------------

**Comment by bpasero** [comment]
@joaomoreno is this the shared process failing maybe?

**Comment by joaomoreno** [comment]
Maybe. But the shared process uses `cp.fork`, which shouldn't really fail like that.

**Comment by nahaiduk** [comment]
I get the same issue with the following appearing in STDOUT
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[ [Error: Error deleting the shared ipc hook.] ]

<--- Last few GCs --->

    6959 ms: Mark-sweep 1392.9 (1440.7) -> 1392.9 (1440.7) MB, 10.3 / 0 ms [last resort gc].
    6960 ms: Scavenge 1393.0 (1440.7) -> 1393.0 (1440.7) MB, 0.4 / 0 ms [allocation failure].
    6960 ms: Scavenge 1393.0 (1440.7) -> 1393.0 (1440.7) MB, 0.1 / 0 ms [allocation failure].
    6971 ms: Mark-sweep 1393.0 (1440.7) -> 1393.0 (1440.7) MB, 10.5 / 0 ms [last resort gc].
    6981 ms: Mark-sweep 1393.0 (1440.7) -> 1393.0 (1440.7) MB, 10.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x69253db45d1 <JS Object>
    1: JSONSerialize(aka JSONSerialize) [native json.js:~120] [pc=0x3b9faa9936bd] (this=0x69253d041b9 <undefined>,G=0x69253d05c59 <String[1]: 1>,j=0x1b65a5f137a1 <an Arguments with map 0x19df45809d21>,v=0x1b65a5f13759 <JS Function (SharedFunctionInfo 0x47601bbbe01)>,w=0x1b65a5f13739 <JS Array[1]>,x=0x69253d04291 <String[0]: >,y=0x69253d04291 <String[0]: >)
    2: SerializeObject(aka SerializeObj...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
ulimit is set to unlimited and the output of `free` is
```
              total        used        free      shared  buff/cache   available
Mem:       16336048     4527560     8404904      841112     3403584    10586644
Swap:       8191996     2075856     6116140
```

I also get no colour coding of the file or option to change the filetype.

This is with the zip exploded out in `~/Downloads/VSCode-linux-x64`. It still doesn't work if I run it with sudo, but if I `su` and unzip to `/root/Downloads/VSCode-linux-x64` it works. Though I do see the following in STDOUT:
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
```

**Comment by alexandrudima** [comment]
@nahaiduk Your crash looks pretty much like an OOM. Does the entire app crash for you or just the extension host or shared process? i.e. Do you see error messages similar to the ones above:

"Error from the plugin host: write EPIPE"
"Plugin host terminated unexpectedly. Please restart VSCode to recover"
"Error from the plugin host: channel closed"

After you observe this error can you please run `ps aux | grep vscode` so we can see which processes are still alive and which ones have crashed.

**Comment by bpasero** [comment]
We need more info, please comment and I can reopen.

**Comment by KirilVelichkov** [comment]
I am having a similar issue.
No matter what i open with VS Code i have a blank screen. 
![untitled](https://cloud.githubusercontent.com/assets/18174745/18272736/248c0e70-7442-11e6-94a2-df539840641c.png)


The console output shows a lot of errors.

oading "vs/workbench/workbench.main" failedt @ loader.js:136
loader.js:137 Detail:  Error: No define call received from module vs/workbench/workbench.main.
    at e._onLoad (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:20081)
    at Object.callback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:25944)
    at e.triggerCallback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:27076)
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:26882
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:30131
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)t @ loader.js:137
loader.js:139 Error: No define call received from module vs/workbench/workbench.main.
    at e._onLoad (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:20081)
    at Object.callback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:25944)
    at e.triggerCallback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:27076)
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:26882
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:30131
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)t @ loader.js:139
loader.js:141 Here are the modules that depend on it:t @ loader.js:141
loader.js:142 Array[1]t @ loader.js:142

**Comment by bpasero** [comment]
@KirilVelichkov can you completely uninstall and reinstall Code to see if it works then?

**Comment by KirilVelichkov** [comment]
@bpasero 
I have read all articles about this problem and everyone with the same issue have tried re-installing it , but that didnt fix the issue.
I have so many things already saved on the editor (extensions, snippets etc) that i really dont want to re-install it

**Comment by bpasero** [comment]
@KirilVelichkov reinstall will not tamper with your settings nor extensions, so please try.

**Comment by KirilVelichkov** [comment]
@bpasero I have it fixed thanks to @mrmlnc 

Here is what he suggested to me.

https://code.visualstudio.com/?utm_expid=101350005-27.GqBWbOBuSRqlazQC_nNSRg.0#alt-downloads

Then unzip VSCode-win32-stable.zip\resources\app\out\ directory to the C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out directory.


It worked and now i can use VS Code again!

Thanks so much @mrmlnc !

**Comment by mrmlnc** [comment]
@bpasero, this is **vscode-icons**, again.
