### ISSUE TITLE
VS Code keeps updating the same packages over and over

### ISSUE THREAD

**Issue by LorenzoDeMarco** [microsoft/vscode#76208]
Issue Type: <b>Bug</b>

1. Open VS Code
2. Install PlatformIO and C/C++ extensions from the Marketplace
3. Restart VS Code
4. After some time, the output window will show on every startup:
"Updating C/C++ dependencies..."
"Downloading package {1}..." where {1} is 'C/C++ language components (Windows)', 'ClangFormat (Windows)' and 'Visual Studio Windows Debugger'.
It does this on every startup, even if the last time it ran the updates installed successfully.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.94GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
algorithm-mnemonics-vscode|dav|1.0.3
CppSnippets|har|0.0.14
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
platformio-ide|pla|1.7.1

</details>

**Comment by mjbvz** [comment]
This is cause by one of your extensions. Please start by filing an issue against the c++ extension

**Comment by LorenzoDeMarco** [comment]
Fixed by reinstalling the above packages. :+1:
