### ISSUE TITLE
Anaconda env not correctly used

### ISSUE THREAD

**Issue by widovanheemstra** [microsoft/vscode#76204]
Issue Type: <b>Bug</b>

When activating an anaconda env for a folder, the python path is not used. As a result the default OS python is used hence all modules cannot be found. 
Previous versions of VSCode did do this correctly.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
vsc-material-theme|Equ|2.9.0
json-tools|eri|1.0.2
docker-explorer|for|0.1.6
vscode-pull-request-github|Git|0.8.0
todo-tree|Gru|0.0.135
beautify|Hoo|1.5.0
swift|Kas|0.0.3
vscode-docker|ms-|0.6.4
mssql|ms-|1.6.0
python|ms-|2019.6.22090
autodocstring|njp|0.3.0
material-icon-theme|PKi|3.8.0
java|red|0.46.0
vscode-yaml|red|0.4.1
scala|sca|0.3.3
code-settings-sync|Sha|3.3.1
html5-boilerplate|sid|1.0.3
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.8.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension repo
