### ISSUE TITLE
One test case for Range.compareRangesUsingEnds is wrong

### ISSUE THREAD

**Issue by foxtango** [microsoft/vscode#76203]
Hi

Looking around sorting of ranges (Range.compareRangesUsingEnds) I stumbled on https://github.com/microsoft/vscode/blob/17454d4e88886404af130639b979498b227a9167/src/vs/editor/test/common/core/range.test.ts#L90

The test cases in L90 and L86 are testing the same - the last one should probably be something like:

a = new Range(1, 2, 5, 1);
b = new Range(1, 1, 1, 4);
assert.ok(Range.compareRangesUsingEnds(a, b) > 0, 'a.start > b.start, a.end > b.end');

**Comment by roblourens** [comment]
I think you're right. Want to do a PR?
