### ISSUE TITLE
Integrated Terminal cannot be launched

### ISSUE THREAD

**Issue by ligtendag** [Microsoft/vscode#7620]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. View --> Views --> Integrated Terminal
2. The following error message appears
![image](https://cloud.githubusercontent.com/assets/7561933/16017129/c6871936-319e-11e6-8943-ba4b4535be93.png)

**Comment by Tyriar** [comment]
The command was renamed to `workbench.action.terminal.toggle` and will be switched back to `workbench.action.terminal.toggleTerminal` in tomorrow's build. Going to wait until there is some command deprecation method before changing it.
