### ISSUE TITLE
Snap editor edges when using four editors

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#76206]
I often work in VS Code with four editor panes open in a 2x2 grid. To get a better look at a file, I sometimes drag one of the horizontal edges. It'd be nice to be able to drag the edge back to nearly the same height as the other, and have it snap to _exactly_ line up with the other edge, making the four dividing edges meet at a single point once again.

**Comment by joaomoreno** [comment]
Have you tried just using `View > Editor Layout > Grid (2x2)`? This will lock each pair of sashes always.

**Comment by kylrth** [comment]
Oh good! Then I can do any resizing I want and just `View > Editor Layout > Grid (2x2)` to get back to equal sizes.
