### ISSUE TITLE
不能下载了

### ISSUE THREAD

**Issue by i-fengqs** [microsoft/vscode#76207]
我现在已经下载不了最新的版本了，
https://vscode-update.azurewebsites.net/latest/win32-x64-archive/stable
浏览器打不开这个

**Comment by byyxx128** [comment]
1. English please.
2. Try the link later. Everything is good for me.

**Comment by i-fengqs** [comment]
我现在已经下载不了最新的版本了，
I can't download the latest version now.
https：
//vscode-update.azurewebsites.net/latest/win32-x64-archive/stable
浏览器打不开这个
· the browser can't open this

**Comment by roblourens** [comment]
Still an issue? @octref any known update server issues?

**Comment by i-fengqs** [comment]
It can't be downloaded on the Chinese Internet

**Comment by i-fengqs** [comment]
The day before yesterday was fine

**Comment by i-fengqs** [comment]
I wonder what happened

**Comment by octref** [comment]
Does this link work for you? https://az764295.vo.msecnd.net/stable/64ce3f02d422c8c2c80455c6e711067ab7b58025/VSCode-win32-x64-1.36.0.zip
