### ISSUE TITLE
Resource labels in web have full path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#76209]
- Open a folder in the web companion
- Open a file in that folder
- All resource labels show the full absolute path:
![image](https://user-images.githubusercontent.com/323878/60206874-79606980-9809-11e9-817d-73c4f31ac6f3.png)
- They should just show the relative path inside that folder: 
![image](https://user-images.githubusercontent.com/323878/60206866-74031f00-9809-11e9-87fd-95160293dc12.png)

Don't know if related to https://github.com/microsoft/vscode/issues/76117

**Comment by isidorn** [comment]
My guess would be that the labelService does not properly compute relative labels because the `this.contextService.getWorkspaceFolder(resource)` does not return the proper results
@sandy081 what is the state of the `contextService` for the web. Is this method supported currently?

**Comment by sandy081** [comment]
Yes it is. I do not think there are any differences between web and remote.

**Comment by isidorn** [comment]
Then I will have to debug and investigate more -> assigning to July so I look into this next week.

**Comment by isidorn** [comment]
@roblourens great catch. Thanks for reporting. It should be fixed from tomorrow.
