### ISSUE TITLE
Extension suggestion for filetype, but extension is already installed/active

### ISSUE THREAD

**Issue by pulberg** [microsoft/vscode#76213]
Issue Type: <b>Bug</b>

When opening or editing a Dockerfile, vscode informs me that there is a Docker plugin available.  I already have the Docker plugin installed and active.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

![ScreenShot1](https://user-images.githubusercontent.com/11069351/60217961-36af8900-982b-11e9-83a2-80e17ff512b9.png)

![ScreenShot2](https://user-images.githubusercontent.com/11069351/60218039-5f378300-982b-11e9-8709-eb15ccd77c46.png)

![ScreenShot3](https://user-images.githubusercontent.com/11069351/60218052-65c5fa80-982b-11e9-9dc7-b6ffbea7ea95.png)

<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-snippets|adi|0.0.1
swagger-viewer|Arj|2.2.2
vscode-database|baj|2.1.5
vscode-custom-css|be5|3.0.4
vscode-linkerd|bha|0.1.4
inspec|bur|0.5.2
solargraph|cas|0.19.6
vscode-standard-format|che|0.0.12
vscode-standardjs|che|1.2.3
aws-cloudformation-yaml|Dan|0.2.2
vscode-dash|dee|2.1.0
vscode-yaml-validation|dja|0.0.1
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.7
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|2.9.0
file-icons|fil|1.0.17
cloudcode|goo|0.0.9
live-html-previewer|hdg|0.3.0
vscode-power-mode|hoo|2.2.0
jwt-decoder|igo|0.0.4
squash|ile|0.5.15
jwt|ina|1.3.0
mysql-syntax|jak|1.3.1
easy-icons|jam|0.3.1
terraform|mau|1.3.12
vscode-docker|ms-|0.6.3
duffle-vscode|ms-|0.0.5
vscode-kubernetes-tools|ms-|1.0.1
python|ms-|2019.5.18875
Go|ms-|0.11.0
powershell|ms-|2019.5.0
team|ms-|1.149.2
language-vscode-javascript-angular2|nwa|0.0.11
chef|Pen|0.7.1
vscode-spring-boot|Piv|1.7.0
material-icon-theme|PKi|3.8.0
ruby|reb|0.23.0
java|red|0.46.0
vscode-yaml|red|0.4.1
bash-debug|rog|0.3.5
bash-beautify|sha|0.1.1
ayu|tea|0.18.0
vscode-icons|vsc|8.7.0
makefile-creator|zen|0.0.3

(7 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This is because docker extension got renamed recently and the recommendations are updated. Since current stable is still pointing to old ids and hence these recommendations are shown.

There will be a new stable build next week and this will get fixed.

@chrisdias FYI

**Comment by sandy081** [comment]
Please verify that this does not happens in Insiders.

**Comment by sandy081** [comment]
Wait, I think we need a long term solution here. Even with insiders or next stable notification will not be shown only if the user has latest or extension with new name installed. If user has old extension, then the notification still appears. 

We should aim not to show the notification at all even if user has extension with old or new name installed, or user is on old or new stable or insiders. So the fix should be to include UUID in our recommendations.


@egamma @chrisdias FYI

**Comment by sandy081** [comment]
I have created a follow up issue to fix it in long run - https://github.com/microsoft/vscode/issues/76258

Closing this issue and tracking this issue to verify that recommendations are not shown when user has installed docker extension with new name.

**Comment by sandy081** [comment]
Verify that recommendation is not shown when user has installed latest docker extension with new name.
