### ISSUE TITLE
Editor does not handle large files well in Insiders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76210]
The theory is that this is a regression in Electron 4.

The first issue I saw was trying to open a 24mb json file that has a lot of very long lines, Insiders will become unresponsive but Stable can open it.

@rebornix and I then looked at typing characters into another large json file (100mb, also very long lines but different to the original) that could be opened in Insiders and Stable. Typing and joining lines took a very long time on Insiders because of Layout, see the images below.

Stable typing:

<img width="791" alt="Screen Shot 2019-06-26 at 2 42 40 PM" src="https://user-images.githubusercontent.com/2193314/60217347-5f328580-9821-11e9-86cc-22f2ef3b048b.png">

Insiders typings:

<img width="1195" alt="Screen Shot 2019-06-26 at 2 40 48 PM" src="https://user-images.githubusercontent.com/2193314/60217357-65286680-9821-11e9-9aeb-051eff131bd0.png">

Stable join lines:

<img width="410" alt="Screen Shot 2019-06-26 at 2 43 25 PM" src="https://user-images.githubusercontent.com/2193314/60217369-6c4f7480-9821-11e9-89af-8d2877b246f4.png">

Insiders join lines:

<img width="836" alt="Screen Shot 2019-06-26 at 2 43 32 PM" src="https://user-images.githubusercontent.com/2193314/60217379-71acbf00-9821-11e9-899d-d3bfc21acfa0.png">

**Comment by bpasero** [comment]
@rebornix maybe useful to debug further with `--trace` and `--trace-options` / `--trace-category-filter` if we cannot look into why `Layout` is taking such a long time (https://www.chromium.org/developers/how-tos/trace-event-profiling-tool).

We are only ever putting the selection into the text area right? So I wonder why would the size of the document have any impact on the layout of the text area?

**Comment by Tyriar** [comment]
I got the impression it was related to laying out all the spans to the right of the viewport which are included in the DOM as there would be 100000+ characters there being added to the DOM in the file I used.

**Comment by bpasero** [comment]
@Tyriar We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by deepak1556** [comment]
@Tyriar does this repro with electron 6 ?

**Comment by Tyriar** [comment]
Electron 6 seems to behave a little better, monaco really has issues with unwrapped long lines though because it puts the whole line in the DOM (@rebornix):

![image](https://user-images.githubusercontent.com/2193314/66405348-da6a1280-e99e-11e9-9ea7-358b4a6692b6.png)

Closing as I think the Electron regression is fixed in 6.
