### ISSUE TITLE
Progress/feedback when dropping large file into VS Code 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76216]
From https://github.com/microsoft/vscode-remote-release/issues/664 (but I don't think this is remote specific)

**Repo**
1. Open a folder in VS Code
1. Create a large file on your desktop
1. Drag and drop that file into VS Code

**Bug**
On remote file systems (such as in a remote workspace), it takes a moment for the file to actually be copied into the folder. However we don't show any feedback while this is happening

**Comment by isidorn** [comment]
Makes sense. However dup of https://github.com/microsoft/vscode/issues/73996 and https://github.com/microsoft/vscode/issues/75705
