### ISSUE TITLE
--install-extension does not quit properly

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#76219]
VS Code 1.35

```
code --install-extension pnp.polacode
Installing extensions...
Installing extension 'pnp.polacode' v0.3.2...
Extension 'pnp.polacode' v0.3.2 was successfully installed.

^C
```

I have to press Ctrl+C to exit the process. I think after successfully installing the extension the process should quit.

**Comment by sandy081** [comment]
@octref it exists for me. Which platform are you on?

**Comment by octref** [comment]
macOS

**Comment by octref** [comment]
Hmm, in my home computer it works fine. I'll see what went wrong with my work machine. Sorry!
