### ISSUE TITLE
F5 launch broken in Insiders - environment variables not getting passed in

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#76212]
Issue Type: <b>Bug</b>

Does *not* repro in stable 1.35.1

REPRO:

1. git clone https://github.com/microsoft/vscode-azurearmtools.git
1. cd vscode-azurearmtools
1. npm i
1. open in vscode
1. Select configuration "Launch Extension"
1. F5
!) Activating extension 'msazurermtools.azurerm-vscode-tools' failed: Cannot find module './dist/extension.bundle'.

The cause is that the environment variables from launch.json are not getting passed in to the process.  
In main.js:
  const ignoreBundle = !/^(false|0)?$/i.test(process.env.AZCODE_ARM_IGNORE_BUNDLE || '');

process.env.AZCODE_ARM_IGNORE_BUNDLE is not defined, even though it's specified in the launch.json file:

            "env": {
                "AZCODE_ARM_IGNORE_BUNDLE": "1",
                "DEBUGTELEMETRY": "1",
                "NODE_DEBUG": ""
            }

VS Code version: Code - Insiders 1.36.0-insider (41691474e5fa22a279d49fc4b58af66bc11ce41b, 2019-06-26T05:20:29.762Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.6.4
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
azure-account|ms-|0.8.4

</details>

**Comment by roblourens** [comment]
I can repro this. The debug adapter hasn't changed. vscode is doing the launching here, did something change there @isidorn?

**Comment by weinand** [comment]
This is a regression of the work I did for launching VS Code internally.

**Comment by weinand** [comment]
@StephenWeatherford it would be great if you could verify the fix in tomorrows Insiders. Thanks a lot and sorry for breaking this.

**Comment by isidorn** [comment]
This works fine for me with latest vscode insiders on macOS. Adding verified label

**Comment by StephenWeatherford** [comment]
Yep, thanks!
