### ISSUE TITLE
Duplicated folder on explorer after clicking New file/folder buttons while editing an item

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#76228]
From https://github.com/microsoft/vscode/pull/75695#issuecomment-504300068

- VSCode Version: Insiders/build from source code
- OS Version: Ubuntu 18.04 

Steps to Reproduce:

1. Open explorer view
2. Trigger rename on a file or folder item
3. Click `New file`/`New folder` buttons
4. See duplicated folder item. If I delete it the whole project folder gets deleted.

![explorerduplicatedfolder](https://user-images.githubusercontent.com/25115070/60240338-3dafb900-9876-11e9-80dd-25f763fe2f90.gif)

cc @isidorn

**Comment by isidorn** [comment]
Thanks a lot for reporting this.
