### ISSUE TITLE
C++ syntax highlighting broken after (const char *)[]

### ISSUE THREAD

**Issue by Dust1404** [microsoft/vscode#76225]
VSCode Version: 1.35.1

![1](https://user-images.githubusercontent.com/40361332/60233860-b8a7bc80-98d4-11e9-977f-82e8547bec3d.PNG)
![2](https://user-images.githubusercontent.com/40361332/60233867-bcd3da00-98d4-11e9-86da-225bae28e0c7.PNG)

Just like the picture above. C++ syntax highlighting is broken after `""[]`.

I tried it on 4 different computers, wheter on Windows or Linux, whether with or without extensions.

I think it has nothing to do with the computer, system or extensions.

**Comment by jeff-hykin** [comment]
A fix has been created, and it should show up in VS Code in one of the next updates. If you want the fix right now download the [Better Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension and it'll automatically be applied

**Comment by Dust1404** [comment]
@jeff-hykin Thanks a lot.

**Comment by alexr00** [comment]
@jeff-hykin thank you for making the fix so quickly. 

@Dust1404 I'll pull the grammar update in to VS Code next week and close this issue when I do. After that, you'll be able to get the update through insiders.

**Comment by ian-h-chamberlain** [comment]
@jeff-hykin is this a symptom of the same issue, or should I open a separate issue for this? Deeply nested `[]` access seems to cause something similar:

![broken-highlight](https://user-images.githubusercontent.com/11131775/60522039-48bf7a80-9cb6-11e9-8b23-dc72a84a4782.png)
With a comment to "fix" it:
![comment-fixed-highlight](https://user-images.githubusercontent.com/11131775/60522055-4eb55b80-9cb6-11e9-8c2f-9d067bc184e4.png)

**Comment by matter123** [comment]
@ian-h-chamberlain That is most likely a separate issue. Would you mind filing an issue at https://github.com/jeff-hykin/cpp-textmate-grammar/issues with a copy/pasteable example?

**Comment by alexr00** [comment]
Change has been pulled into VS Code and will be available in insiders soon.
