### ISSUE TITLE
Toggle between settings ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#76223]
Is it possible to switch between two different settings within either settings.json or workplace settings ?

**Comment by roblourens** [comment]
Not sure what you are talking about - switch between two settings?

**Comment by SheepDomination** [comment]
Change between two settings within either `settings.json` or `workspace` settings; with a keyboard short-cut.

**Comment by roblourens** [comment]
I need you to be more specific, what does "change between two settings" mean?

**Comment by SheepDomination** [comment]
@roblourens If I set one setting within the *settings.json* file or *workspace* settings; I want to be able to toggle between another similar setting, for example; the font used within code.

**Comment by roblourens** [comment]
We don't have any builtin functionality like that but there are extensions, for example maybe https://marketplace.visualstudio.com/items?itemName=Ho-Wan.setting-toggle does what you want.
