### ISSUE TITLE
Web: dialog button default is wrong 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76232]
Steps to Reproduce:

1. macOS undo some changes from SCM view
2. with native, I can just press enter, in web the default seems to be "Cancel"

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/77266

@sbatten I suggest you take a look how we handle dialogs in electron for specific platforms: [`massageMessageBoxOptions`](https://github.com/Microsoft/vscode/blob/3456ef3aaaf6132eada921a53e8291b928c4d530/src/vs/workbench/services/dialogs/electron-browser/dialogService.ts#L145)

There are possibly more things to consider.

**Comment by sbatten** [comment]
@bpasero From what I see in that method, there is just button reversal on non-windows and special placement of the cancel button which seems the same as the logic @lramos15 added in `rearrangeButtons`
