### ISSUE TITLE
Go to reference/implementation using Ctrl + mouse

### ISSUE THREAD

**Issue by davidluca3000** [microsoft/vscode#76238]
Issue Type: <b>Feature Request</b>

Hello,
In Eclipse there was a nice feature that when you hover the mouse over a function/variable name and you hold Ctrl key then it would be underlined and become a link, so that when you click on it would go to the implementation/reference. It would be much easier than pressing F12. 
Best regards,
David.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

**Comment by IllusionMH** [comment]
`Ctrl + Click` functionality is already implemented and works for me on Windows.

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

**Comment by roblourens** [comment]
That's correct, thanks @IllusionMH

**Comment by davidluca3000** [comment]
Then it's not working well, it doesn't find references in other files in the workspace, only in the same file.

**Comment by roblourens** [comment]
It should do exactly the same thing as pressing F12, are you saying that it works with F12 but not ctrl+click?

**Comment by davidluca3000** [comment]
Doesn't work with F12 either.

**Comment by roblourens** [comment]
Oh so you are just saying that it doesn't work at all, what language is this and are you using a language extension for it?

**Comment by davidluca3000** [comment]
I'm using it with Python extension.

**Comment by roblourens** [comment]
Ok please file an issue on the python extension's repo or see their docs

**Comment by davidluca3000** [comment]
will do, thank you.
