### ISSUE TITLE
beautify json not working

### ISSUE THREAD

**Issue by jasonChen1982** [microsoft/vscode#76236]
Issue Type: <b>Bug</b>

my json file was big (20kb), new vscode can not beautify it

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|8.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
dart-code|Dar|3.1.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
translation|dus|0.0.4
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
flow-for-vscode|flo|1.1.4
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.35.1
vetur|oct|0.21.0
java|red|0.46.0
guides|spy|0.9.3
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.12.7
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.8.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by fazlarabbi2** [comment]
Unibeautify no longer working in latest vscode 
Please solved this bug as soon as possible
