### ISSUE TITLE
Show previous search results in quick finder

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#76234]
I'm transitioning from Qt Creator to VSCode and one of the things it does better is its quick finder (Ctrl-P in VSCode, Ctrl-K in Qt Creator).

One way it is better is that if you search for a file, and open that file, then realise you got the wrong one you can just press Ctrl-K again to focus the finder and *it will show the same list as before* so you don't have to re-type your search query.

Here's are some low quality GIFs (yeay Github) of the difference.

![qt_creator_search](https://user-images.githubusercontent.com/376842/60256494-8d6ba000-98c9-11e9-949c-9568046fdd52.gif)

![vscode_search](https://user-images.githubusercontent.com/376842/60256504-92305400-98c9-11e9-9734-c19f3d834cb7.gif)

It would make sense for the previous text to be in the quick search box and to be selected so when you type it is overwritten, like in Qt Creator. But if it just shows the previous results that'd be fine too.

**Comment by skprabhanjan** [comment]
@roblourens , Can I take this up ? 
I did a bit of research in the code base and found [this](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenActions.ts#L57) is where keybinding is associated , But I need more help from you if you feel I can work on this :)

**Comment by roblourens** [comment]
Yes go for it 😁 

You probably want to start in OpenAnythingHandler. Figure out how that gets called and how it calls into OpenFileHandler and others. Then have it cache its last used query, and add a command that calls OpenAnythingHandler and tells it to use the last used query.

**Comment by skprabhanjan** [comment]
@roblourens , I tried to do this but finally ended up finding a setting that does what I was trying to do.
`workbench.quickOpen.preserveInput` => This setting will preserve the input value when typed and opens the Quick Open next time with that value populated and results similar ( Now it will show the mistakenly opened file in recently opened ).
Can you please confirm if this is good or should I need to do anything ?

I guess this is what @Timmmm had requested for ? ( Or Can be achieved using this  ? )

**Comment by roblourens** [comment]
Oh, I didn't know we had that setting. Sorry for sending you down the wrong path. Thanks!

I think that's enough to call this closed.

**Comment by Timmmm** [comment]
Those options work perfectly. Strange that it isn't enabled by default because why would you want this disabled? I made a pull request for it: #77873.
