### ISSUE TITLE
git HEAD info in tab title

### ISSUE THREAD

**Issue by coldner** [microsoft/vscode#76246]
IMHO, in tab title there should be an information about git HEAD file mode. For now, there isn't any difference between original file and HEAD file in tabs.

I suggest to add "HEAD" text in parentheses after filename just like "Working tree" text in comparision mode.

![head file](https://user-images.githubusercontent.com/35400886/60274104-c28ee700-98f7-11e9-91fa-717f2864ce2e.png)

**Comment by roblourens** [comment]
How did you open the HEAD version of the file?

**Comment by coldner** [comment]
Source Control > Right click on file

![file](https://user-images.githubusercontent.com/35400886/60286826-a3e91a00-9910-11e9-9ab6-d6f1a676a43c.png)

**Comment by BabyManisha** [comment]
can i work on this or does this already have any plans?
