### ISSUE TITLE
Reading pytlint files for languages 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#76244]
If I want visual studio code to read specific `pylint.rc` files for specific languages; must I put that in the python environment file ?

**Comment by SheepDomination** [comment]
@roblourens My original question was that of a question; what makes you say it has to do with an extension ?

**Comment by roblourens** [comment]
I am not sure what you are asking about, and I assume you are asking about some extension? VS Code doesn't read pylint.rc files by default but some extensions probably add this functionality
.

**Comment by SheepDomination** [comment]
@roblourens I probably have to move this question to the python extension.
