### ISSUE TITLE
Text in code block in markdown starting with # disappears in preview

### ISSUE THREAD

**Issue by kaushik-work** [microsoft/vscode#76249]
Issue Type: <b>Bug</b>

The following markdown code in preview is missing the line starting with #
(Screen shot attached)
![Screen Shot 2019-06-27 at 10 46 49 AM](https://user-images.githubusercontent.com/6299530/60276397-893f8280-98c9-11e9-98ad-0abeb8686a66.png)

Thanks!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_40970|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
html-preview-vscode|geo|0.2.5
latex-workshop|Jam|7.0.2
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
cpptools|ms-|0.23.1
benten-cwl|sbg|2019.5.16-alpha
rewrap|stk|1.9.1
code-spell-checker|str|1.7.17

</details>

**Comment by roblourens** [comment]
I think the text after \`\`\` is considered a syntax highlight mode selector, so it won't show up in the document. You should put it on the next line if you want it to show up in the document.

**Comment by mjbvz** [comment]
That is correct
