### ISSUE TITLE
Clink extension for Windows' standard command line not fully supported

### ISSUE THREAD

**Issue by Toreno96** [Microsoft/vscode#7624]
- VSCode Version: 1.2.0
- OS Version: Windows 7 64-bit with Polish language pack

Steps to Reproduce:
1. Install [Clink](https://mridgers.github.io/clink/).
2. Toggle integrated terminal in VSCode.
3. With "clink set option_name value" command, change esc_clears_line to 1 and use_altgr_substitute to 0.
4. Try to use Clink shortcut that require combination of alt + ctrl + _anything_, where _anything_ is a key, that combined with altgr will make a special character on your system. Instead of Clink function, in VSCode integrated terminal you'll see that special character. For me, that's for example _ć_ character, instead of _copy whole line_ function.
5. Try to use alt + h shortcut to show help of Clink. Instead, help menu of VSCode will expand.
6. Try to clear a line with the escape key. Line will be cleared, but terminal will hide.

Clink is very good expansion for Windows' standard cmd, while integrated terminal is very good expansion for VSCode - so I'm really disappointed they aren't fully compatible with each other. Hope you will do something about that.

**Comment by Toreno96** [comment]
I found another two issues, which possibly could be present on standard command prompt too:
1. When I'm trying to use combination of ctrl + left/right arrow to jump throught a whole word, instead it prints "5D" and "5C", respectively.
2. Scrolling terminal with up and down arrows with scroll lock turned on doesn't work.

**Comment by Tyriar** [comment]
@Toreno96 I played with Clink a little yesterday and filed an issue of my own https://github.com/Microsoft/vscode/issues/7630

It seems *very* broken to me currently, I would just avoid using it in vscode right now. I have a feeling it may be on the Clink end as well because most other shells (powershell, cmd, bash, zsh) don't demonstrate the issues that Clink does.

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/7345

**Comment by Tyriar** [comment]
Closing off, a lot has changed since now including the upgrade to winpty which improved Windows support a lot.
