### ISSUE TITLE
Error creating new file from contextual menu

### ISSUE THREAD

**Issue by manu-chroma** [microsoft/vscode#76254]
Issue Type: <b>Bug</b>

Sometimes when creating a file using ctrl+shift+p and then selecting "New file" option has no effect. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.01GB free)|
|Process Argv|2.cpp|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
python|ms-|2019.6.22090
cpptools|ms-|0.23.1
Go|ms-|0.11.0
pdf|tom|0.5.0
clang-format|xav|1.9.0

</details>

Chrome dev tools logging: 

![image](https://user-images.githubusercontent.com/12952080/60286464-3a2b3900-992d-11e9-9a9e-f294cf656478.png)

**Comment by isidorn** [comment]
@manu-chroma  Do you see this when being in a no folder vscode (purple status bar)?
Do you have better reproducable steps?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
