### ISSUE TITLE
Respect "editor.tabSize" in terminal

### ISSUE THREAD

**Issue by aleclarson** [microsoft/vscode#76251]
Otherwise commands like `git diff` are unreadable

**Comment by Tyriar** [comment]
Tabs are very special in the terminal, you need to get the program to use something different: https://stackoverflow.com/a/10584237/1156119

**Comment by aleclarson** [comment]
Yeah, my bad! This worked for me on macOS:
```sh
git config --global core.pager 'less -x2'
```
