### ISSUE TITLE
Reload window stays closed

### ISSUE THREAD

**Issue by jpan127** [microsoft/vscode#76255]
Issue Type: <b>Bug</b>

I used `Ctrl+Shift+P` to open up the command list, then selected reload window.  The program closed and stayed closed.

**Expected:**
Window closes, window reopens.

**Actual:**
Window closes.

VS Code version: Code - Insiders 1.36.0-insider (b7265738444f1eee05762341b4361ee6452a4154, 2019-06-27T05:16:31.292Z)
OS version: Linux x64 4.15.0-52-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|45.89GB (15.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
python|ms-|2019.6.22090
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
cpptools|ms-|0.24.0-insiders2
sublime-keybindings|ms-|4.0.3
trailing-spaces|sha|0.3.1
sort-lines|Tyr|1.8.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Maybe an issue due to installation being a snap package? 

@jpan127 does it reproduce if you try from a VSCode in zip form: https://az764295.vo.msecnd.net/insider/d50852db1af10ec100a71ad57cc3a04c8aead117/code-insider-1562564123.tar.gz

**Comment by jpan127** [comment]
Hm, it might be recent updates but it works now! Closing this but thanks anyways!
