### ISSUE TITLE
Chrome debugger: Use port forwarding to open URL when running with a remote

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#76259]
Testing https://github.com/microsoft/vscode-remote-release/issues/754

When the launch config has a `url` and the window is connected to a remote, the URL should be opened with the same smarts as `openExternal()` has on the remote side. /cc @mjbvz

**Comment by mjbvz** [comment]
What API do you need? A way to force `vscode.env.openExternal` to use port forwarding even though it is a UI extension?

**Comment by roblourens** [comment]
In this case the chrome debug adapter is running as a UI extension, but it knows the port on the remote. It looks like `asExternalUri` won't help in this case right?

**Comment by mjbvz** [comment]
@roblourens Yes that's correct; the current api would be a noop in that case. Maybe we need a way to force a uri to be resolved as if the extension were remote?

**Comment by roblourens** [comment]
I think this is supported in js-debug
