### ISSUE TITLE
Installing previous version action is not working for renamed extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#76253]
Ref https://github.com/microsoft/vscode/issues/76211
From @EricJizbaMSFT

As I side note, I tried to install the old version directly from VS Code (instead of from a vsix), but no luck.
![Screen Shot 2019-06-27 at 8 37 47 AM](https://user-images.githubusercontent.com/11282622/60279946-dc5c0a00-98b6-11e9-8d90-ad33dfe31d72.png)
![Screen Shot 2019-06-27 at 8 34 37 AM](https://user-images.githubusercontent.com/11282622/60279923-d23a0b80-98b6-11e9-8e12-3b93a8576bdb.png)
![Screen Shot 2019-06-27 at 8 34 22 AM](https://user-images.githubusercontent.com/11282622/60279919-cfd7b180-98b6-11e9-91fb-615fea859513.png)

**Comment by sandy081** [comment]
@kesane-msft It happens because the properties of old extension (with old name) are not available when querying from marketplace. Are they get deleted when extension gets renamed?

**Comment by kesane-msft** [comment]
@sandy081 yes. During the rename, we basically just change the latest version of the extension.

**Comment by sandy081** [comment]
Sorry if I am not clear -

I run the query with new name and in the query I request for all versions. 
In the result, I get all versions of the extension but only those versions with new name has properties, remaining has missing properties.

**Comment by kesane-msft** [comment]
@sandy081 - that's because we don't migrate the properties for the older versions.

**Comment by sandy081** [comment]
@kesane-msft Is it possible to also migrate the properties? We heavily rely on properties to know the metadata of the extension.

**Comment by kesane-msft** [comment]
@sandy081 fair ask. I have logged a bug on our side to make these changes.
