### ISSUE TITLE
dont auto show integrated terminal.

### ISSUE THREAD

**Issue by NikitaChizhik** [microsoft/vscode#76256]
Issue Type: <b>Feature Request</b>

Please, I dont want to see Integrated terminal panel. It always opens when I deploy source to org or use some comand in power shell. But I dont want to see Terminal panel. If I want to see it I would manually open it. Please make this avaliable to configure. I couldn't find info on how to disable auto popup of terminal every time I use it.
Many Thanks.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by Tyriar** [comment]
I think this is about the powershell extension?
