### ISSUE TITLE
Problems don't clear when closing and reopening file.

### ISSUE THREAD

**Issue by rook2pawn** [microsoft/vscode#76257]
Related issues
https://github.com/microsoft/vscode/issues/52348
https://github.com/microsoft/vscode/issues/53944
https://github.com/Microsoft/vscode/issues/52348

- VSCode Version: Version 1.35.1 (1.35.1)
- OS Version: MacOS 10.14.5 (18F203) Mojave

Steps to Reproduce:

1. Have a problem with the code.
2. Change git branches so the working directory has correct, problem-free code.
3. Problems still exist but the file is updated. Close file.
4. Reopen file, problems don't clear.

**Comment by mjbvz** [comment]
This is for JavaScript or TypeScript, correct? Can you please provide specific repo steps for this issue. Depending on how large the branch change is, it may take a moment for the problems to be updated but they should eventually be updated for all js/ts files open in VS Code
