### ISSUE TITLE
mouse menu item is automatically selected on RMB release

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#76252]
- VSCode Version: 
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-52-generic

- OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Steps to Reproduce:
1. Open VScode and do work during some time.
2. press right mouse button and immediately release it.

Does this issue occur when all extensions are disabled?: Yes

![mouse_menu](https://user-images.githubusercontent.com/801951/60280089-ead41100-990a-11e9-8915-94892b8d5948.gif)

**Comment by roblourens** [comment]
Can you explain some more about what you are seeing? I don't understand

**Comment by dibalavs** [comment]
Hi, 
Just compare behavior in vscode and in other application:

Google chrome:
1) Press RMB.
2) menu is shown
3) release mouse button
4) menu is visible, I can select required item manually.

vscode:
1) press RMB
2) menu is shown
3) release mouse button
4) menu item which is placed under  cursor will be automatically selected and menu disappeared!

In example above menu item "Cut" will be selected immediately I release RMB.

If I restart vscode, all is ok. But is reproduced after hours when I work with vscode.

In attachment example how context menu in chrome is working:
![mouse_menu_chrome](https://user-images.githubusercontent.com/801951/60321361-45aa4e80-9985-11e9-8f44-eb9939f8ba88.gif)

**Comment by roblourens** [comment]
Sorry, the gif in your original post didn't load yesterday.

**Comment by sbatten** [comment]
@dibalavs are you using `window.titleBarStyle`: `custom` or `native`

**Comment by dibalavs** [comment]
titlebarstyle is custom. 
My settings:
global:

>  "workbench.activityBar.visible": false,
    "window.titleBarStyle": "custom",
    "gitlens.codeLens.recentChange.command": "gitlens.toggleFileBlame",
    "gitlens.currentLine.enabled": false,
    "gitlens.hovers.currentLine.enabled": false,
    "gitlens.advanced.telemetry.enabled": false,
    "search.maintainFileSearchCache": true,
    "search.quickOpen.includeSymbols": true,
    "search.runInExtensionHost": true,
    "search.smartCase": true

workspace:

> "folders": [
		{
			"path": "dist"
		},
		{
			"path": "packages"
		},
		{
			"path": "config"
		},
		{
			"path": "kb"
		}
	],
	"settings": {
		"files.associations": {
            .................
		},
		"cSpell.words": [
        .............
		],
		"C_Cpp.default.includePath": [
            ............................
		],
		"C_Cpp.default.systemIncludePath": [
			.......................................
		],
		"git.ignoreLimitWarning": true,
		"editor.fontSize": 13,
		"editor.renderWhitespace": "boundary",
		"workbench.statusBar.feedback.visible": false,
		"workbench.tips.enabled": false,
		"workbench.editor.highlightModifiedTabs": true,
		"workbench.editor.revealIfOpen": true,
		"window.zoomLevel": 1,
		"search.exclude": {
			"**/.git": true
		},
		"search.maintainFileSearchCache": true,
		"search.quickOpen.includeSymbols": false,
		"search.smartCase": true,
		"telemetry.enableTelemetry": false,
		"telemetry.enableCrashReporter": false,
		"gitlens.hovers.annotations.changes": false,
		"gitlens.hovers.annotations.details": false,
		"gitlens.hovers.annotations.enabled": false,
		"gitlens.hovers.currentLine.changes": false,
		"gitlens.hovers.currentLine.details": false,
		"gitlens.hovers.currentLine.enabled": false,
		"gitlens.hovers.enabled": false,
		"gitlens.currentLine.enabled": false,
		"gitlens.codeLens.recentChange.enabled": false,
		"gitlens.codeLens.authors.enabled": false,
		"search.useReplacePreview": false,
		"workbench.editor.enablePreview": false,
		"search.runInExtensionHost": true
	}

**Comment by sbatten** [comment]
this has been addressed elsewhere
