### ISSUE TITLE
File > Open Folder makes VSC to crash

### ISSUE THREAD

**Issue by orojina** [microsoft/vscode#76261]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open VSC
2. Click File > Open Folder...
3. Dialog windows opens, then ~1 sec later VSC crashes and closes it self

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.00GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Python-autopep8|him|1.0.2
python|ms-|2019.6.22090

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
