### ISSUE TITLE
Colour scheme has been broken for a while 

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode#76265]
- VSCode Version: 1.35.1
- OS Version: NT 10.0.14393

The colour scheme has been broken for a while , I am not sure if this is already reported 

Steps to Reproduce:
1. just comment the code 
2.

Does this issue occur when all extensions are disabled?: Yes/No
![image](https://user-images.githubusercontent.com/7133450/60302029-aaaf6700-98e7-11e9-8bfd-501169e43ba6.png)

**Comment by roblourens** [comment]
Can you include the broken code as text?

**Comment by thkrishn** [comment]
```
    // class Iterator {
    // public:
    //     Iterator(Manager* manager, std::size_t index) : manager(manager), index(index) {}
    //     bool operator==(const Iterator &other) { return index == other.index; }
    //     bool operator!=(const Iterator &other) { return !(*this == other); }
    //     const Iterator &operator++() { index++; return *this; }
    //     std::shared_ptr<StoreExtent> operator*() { return manager->getNext(index); }
    // private:
    //     Manager *manager;
    //     std::size_t index;
    // };
```
Will that help?

**Comment by roblourens** [comment]
Is that the full file? I can't reproduce it.

**Comment by alexr00** [comment]
I also cannot reproduce it. If you have the whole file that would help. Does this still reproduce if you disable all extensions?

**Comment by thkrishn** [comment]
is there a way to reload all extensions ?

**Comment by alexr00** [comment]
To disable all extensions you can run with `--disable-extensions`

**Comment by Colengms** [comment]
Hi @thkrishn .  Are you perhaps using an insiders build of the C/C++ extension?  If so, if you update to the latest, does the problem persist?

**Comment by thkrishn** [comment]
@Colengms Yup VS Code insiders build,  yea I did an update I don't see the issue now
 Thank you !
