### ISSUE TITLE
Open files in window that have file already open or that have parent folder opened

### ISSUE THREAD

**Issue by vomout** [microsoft/vscode#76262]
- VSCode Version: 1.35.1
- OS Version: MacOS 10.14.5

Steps to Reproduce:

This is particularly related to LaTeX Workshop and synctex with a PDF viewer, so I will copy-paste the exact procedure from the bug filed against it at https://github.com/James-Yu/LaTeX-Workshop/issues/1465. Presumably the same error happens simply by opening two VScode windows, opening a file in one, then switching to the other window, and reopening the file from the command line (e.g., MacOS Terminal). The result is that the file is reopened in the second, wrong, window, instead of VScode switching to the already open file in the first window. (Or, if not open, opening it in the window whose workspace has the relevant directory open.)

1. Set up an external PDF viewer with LaTeX Workshop (Skim instructions: https://github.com/James-Yu/LaTeX-Workshop/issues/318#issuecomment-383610589)
2. Open two VSCode windows (possibly on two different MacOS workspaces) with different projects, different VSCode workspaces.
3. Edit a LaTeX project in one workspace/window, build it and have it opened in the external viewer.
4. Switch to the other VSCode window.
5. Return to the PDF viewer (without activating/focusing the other VSCode window, showing the source file for the document in the PDF viewer), and reverse synctex to make VSCode show a particular position of the source file.
6. Observe how the source file is reopened in the previously active wrong window (even if that window is on a different MacOS workspace).

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@vomout VSCode is not preferring a specific window when opening a file that is already opened in any other window. Can we summarise that you want to always open a file in a window that has the file already opened?

**Comment by vomout** [comment]
Yes, a file that is already open should not be reopened, rather VSCode should switch to that window.

**Comment by vomout** [comment]
I guess I'll switch back to SublimeText then. Thank you so much for nothing—as can be said to most projects open source or not. This makes VScode completely unusable for any serious LaTeX work with multiple projects in multiple windows.
