### ISSUE TITLE
You get a lot of dialogs when moving multiple TS files to another folder

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76268]
<img width="270" alt="Screen Shot 2019-06-27 at 4 28 50 PM" src="https://user-images.githubusercontent.com/2193314/60307274-c7a06600-98f8-11e9-8b7e-b8e52889591b.png">

I moved those 2 files from `renderer` to `dom` and got 3 dialogs

<img width="390" alt="Screen Shot 2019-06-27 at 4 32 09 PM" src="https://user-images.githubusercontent.com/2193314/60307366-27970c80-98f9-11e9-9ccf-916d67a4278c.png">
<img width="834" alt="Screen Shot 2019-06-27 at 4 32 15 PM" src="https://user-images.githubusercontent.com/2193314/60307369-2a91fd00-98f9-11e9-84c1-3d5b48e44b1a.png">
<img width="834" alt="Screen Shot 2019-06-27 at 4 32 18 PM" src="https://user-images.githubusercontent.com/2193314/60307371-2cf45700-98f9-11e9-921a-7005a07a3183.png">

Each additional file selected is one more dialog.

**Comment by mjbvz** [comment]
@jrieken For #43768, is the expectation that extensions de-bounce multiple file updates if they need to? 

On the TS side with the current server API, we'd need to perform the updates sequentially but could make sure we don't prompt too much

**Comment by jrieken** [comment]
Yeah, I would assume that the extension is in charge of debouncing, esp. since the file service is likely running two sequential (?) operations despite this being a single UI gesture.

**Comment by DanTup** [comment]
> Yeah, I would assume that the extension is in charge of debouncing

This feels a bit fragile to have extensions do. There was a single UI gesture so VS Code knows exactly what's moving at once - firing lots of events and then requiring extensions to collect them together seems weird - they've had to pick some amount of time to debounce for (which then becomes a trade-off between being slow and doing it badly - and execution time seems to vary hugely across VS Code users, so there's no standard good value).

**Comment by mjbvz** [comment]
This was a pain to fix. With the change though, you should now see two prompts in the case @Tyriar brought up: one from VS Code and one for the js/ts extension.

However there are still cases where js/ts can prompt multiple times for a single set of file moves, including:

* If you move a mix of js and ts files. The user can have different settings for whether to update imports in these two different file types

* If you move files between workspaces. Again, the settings for updating imports may differ between workspaces so we may have to prompt for each workspace to be safe
