### ISSUE TITLE
Pasting a file into a folder via the explorer should expand the folder

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76264]
1: Initial state:

<img width="181" alt="Screen Shot 2019-06-27 at 2 12 26 PM" src="https://user-images.githubusercontent.com/2193314/60301232-a71ae080-98e5-11e9-9cc1-2077ebe5f258.png">

2: Go to another window and copy a file.

3: Click the src directory

4: Hit ctrl+v to paste, the file is pasted but the src directory is still closed as in step 3:

<img width="163" alt="Screen Shot 2019-06-27 at 2 13 41 PM" src="https://user-images.githubusercontent.com/2193314/60301273-ca459000-98e5-11e9-9ad7-cd4ebd344ee0.png">

**Comment by isidorn** [comment]
This makes sense to me. However neither Windows Explorer nad Mac Finder expand the folder on paste. Why do you think we should do that?

**Comment by Tyriar** [comment]
@isidorn because we close the folder when it's selected and Windows Explorer doesn't.

**Comment by isidorn** [comment]
That's a fair point.

**Comment by isidorn** [comment]
@Tyriar I have pushed a change that will fix this. Try it out when we release new insiders and let mek now how it behaves. Thanks!

**Comment by Tyriar** [comment]
@isidorn tested out of sources, it only works for a single files, not multiple.

**Comment by isidorn** [comment]
Good point, pushed a fix for that. Thanks.
