### ISSUE TITLE
Add Document Types to Webview

### ISSUE THREAD

**Issue by cbreeden** [Microsoft/vscode#7626]
- VSCode Version: 1.2.0
- OS Version: Linux

When providing html to `vscode.previewHtml` the doctype is stripped [here in the webview.html](https://github.com/Microsoft/vscode/blob/aaa65451f6f2d6de290ee3cb1c8ce1f2def7a52a/src/vs/workbench/parts/html/browser/webview.html#L81).  This can prevent some styles from not working properly, such as KaTeX which can cause problems like [this here](https://github.com/Khan/KaTeX/issues/332).  I was working on a plugin that would allow me to render Markdown and KaTeX in previewHtml when I ran into this issue.

I simply wanted to replace the linked code above with

```
target.contentDocument.write('<!DOCTYPE html>' + newDocument.documentElement.innerHTML);
```

This __does__ fix the problem for me.  But I had issues following the contribution guidelines (probably another issue), and there probably is a better way to handle this.

**Comment by sandy081** [comment]
Looks like this and #7628 are same. Hence closing this as duplicates #7628

**Comment by cbreeden** [comment]
@sandy081 not quite.  #7628 was a pull request to fix this issue, which we decided to defer since #7656 would fix the issue and was almost ready for prime time.  So while this issue is still valid, it shouldn't be soon and probably can be closed.

**Comment by jrieken** [comment]
We will merge the PR very soone
