### ISSUE TITLE
Shows git diff between two files with same name, but with different case letters

### ISSUE THREAD

**Issue by akdagade** [microsoft/vscode#76263]
Issue Type: <b>Performance Issue</b>

I have two files named 'Stats.sql' and 'stats.sql' (with different content) at same location. 
The VSCode git diff detects these as same file and shows that there a re changes made.

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (Stats.sql (Working Tree) — Untitled (Workspace))
|  Window (billing_data.py — AuctionFee_Adjustment)
|    Folder (getmedata-bot): 107 files
|      File types: py(64) ini(8) yml(7) txt(6) csv(4) sh(3) sql(2)
|                  gitignore(2) xls(2) html(2)
|      Conf files:
|    Folder (AuctionFee_Adjustment): 27 files
|      File types: tsv(12) py(5) pyc(5) json(3) DS_Store(2)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.0
gc-excelviewer|Gra|2.1.32
mssql|ms-|1.6.0
python|ms-|2019.6.22090
Go|ms-|0.11.0
scala|sca|0.3.3
vscodeintellicode|Vis|1.1.7
vscode-icons|vsc|8.8.0

</details>

**Comment by joaomoreno** [comment]
Usually HFS uses case insisitivity. Do you have a case sensitive file system?

Also, what does `git status` return?
