### ISSUE TITLE
Not possible to explicitly change the foreground text color for widgets

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#76274]
It's not possible to explicitly change the foreground text color for widgets (such as the Find widget) in color themes.  **"editor.foreground"** will change it; however, it will also change the text color to ALL code in the code editor which don't have color tokens defined.
See below example where I changed the text color for  **"editor.foreground"** to white... adversely affecting color in my code:
**This:**
![Screenshot](https://user-images.githubusercontent.com/811008/60313665-d9900200-9914-11e9-9dba-8b7bc3c00488.png)

**Will cause this to happen::**
![Screenshot](https://user-images.githubusercontent.com/811008/60313280-56ba7780-9913-11e9-9350-40a057078bbe.png)

Adding **editorWidget.foreground** _(dedicated to widget foreground text color)_ will mitigate this issue.  Otherwise, themes with light colored editor backgrounds and dark widget background colors will either look like the above screenshot or the below screenshot:
![Find-Text](https://user-images.githubusercontent.com/811008/60313344-997c4f80-9913-11e9-89b2-d49adfecdced.png)

**Comment by mkanet** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> tab and editorGroupHeader not changing background color. (#75660)

This is not a duplicate issue.

**Comment by sandy081** [comment]
Verified but in find widget, `No Results` is still hardcoded to red.

**Comment by aeschli** [comment]
Not hardcoded, but the color 'errorForeground'. If there's a request for a widget specific error color, we can add it.
