### ISSUE TITLE
Can clicking open folder use non-dimmed color for indent guide?

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#76276]
- Click open a folder
- Notice that the folder you are focusing on is using the dimmed version of indent guide
- You have to select one of its children to get it to use non-dimmed color

I'd suggest that if the active tree item is a folder, its indent guide should use non-dimmed color

For example, in the below image, `syntaxes` should have the bright yellow when I'm toggling open/close the folder, and when I hover back at file explorer when `syntaxes` is the active item:

![image](https://user-images.githubusercontent.com/4033249/60317503-44950500-9924-11e9-974f-faae1337b504.png)

Expected indent guide color (show this when `syntaxes` is active item):

![image](https://user-images.githubusercontent.com/4033249/60317552-7a39ee00-9924-11e9-93fa-0f8873c19dd9.png)

**Comment by octref** [comment]
Ref #17777

**Comment by joaomoreno** [comment]
I like that.
