### ISSUE TITLE
C++ debug (C/C++ extension)

### ISSUE THREAD

**Issue by Leasder** [microsoft/vscode#76277]
Issue Type: <b>Bug</b>

I have a problem when using gdb to debug my program, VS code shows tha他information “Stopping due to fatal error: NullReferenceException: 未将对象引用设置到对象的实例。” But I can run the program.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.11
run-in-terminal|kor|0.0.1
python|ms-|2019.6.22090
cpptools|ms-|0.24.0-insiders3

</details>

**Comment by roblourens** [comment]
This sounds like an issue with the cpptools extension, please file an issue on their repo: https://github.com/Microsoft/vscode-cpptools
