### ISSUE TITLE
Improve Split View UI

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#76270]
![image](https://user-images.githubusercontent.com/4319522/60310987-2549a800-9923-11e9-87ec-e7decf3e0439.png)

Is there anyway we can improve the explorer UI. It doesn't feel all that great. For example the headings are squished together.   I'm not sure what exactly should change, but I'm also not a big fan of the animations that appear when you click a section heading like `outline` or `Open Editors`. I would also add the option to remove  the drop down icon from folder and section headers.  Maybe others can chime in.

**Comment by isidorn** [comment]
This is not the explorer UI, this is the split view UI. Thus forwarding to @joaomoreno 
@musm Though I did not actually read any suggestions in this issue. What do you suggest to be improved?

**Comment by joaomoreno** [comment]
@isidorn I think part of the user's confusion comes from the fact that the top view is locked, it can't be resized. So it is explorer related.

Anyway, adding @misolori for splitview headers ux.

**Comment by misolori** [comment]
I would love to hear more about what issues there are with the split views, @musm can you expand/elaborate? What I'm hearing so far is:

- Headings feel squished
- Collapsing a view feels unnecessary

Until we have more info, I'm not sure I would count this as a bug but rather a feature request.

**Comment by musm** [comment]
Hey, I think I accidentally pressed bug instead of feature request!  @misolori you got it. The overall UI in the splitview looks clunky.
