### ISSUE TITLE
Git extension excludes diretories which are signed in the .gitigonore. 

### ISSUE THREAD

**Issue by fang13** [microsoft/vscode#76272]
Git extension excludes diretories which are signed in the .gitigonore. 

In fact, there is another repository in the diretory, where  .gitigonore file laid.

.gitigonore is used to differ these two repositoryies.

In this situation, I don't hope that these diretories are excluded by VSCODE.

**Comment by joaomoreno** [comment]
I'm finding it hard to understand the problem. It's git that ignores everything listed in gitignore, be that files or folders.

Can you elaborate with an example?
