### ISSUE TITLE
"Source control providers" can't resize manually

### ISSUE THREAD

**Issue by martimorta** [microsoft/vscode#76289]
Issue Type: <b>Bug</b>

Hi, It would be useful and I think at some point it was possible to be able to see all source control providers in the list. Currently it only allows for 10, to see the rest it needs scrolling even though the space exists anyway.
1. Open/Create a workspace with more than 10 repositories.
2. Go to source control
3. Minimise all repository menus
4. Try to resize the top menu "Source Control Providers" manually hovering the mouse around the top border of the first git repository.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-52-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 3259)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (1.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Look at the `scm.providers.visible` setting. Helptext says if you set this to 0 you will be able to resize the view.

**Comment by martimorta** [comment]
Spot on! Thanks!
