### ISSUE TITLE
Somehow node::AtExit is not invoked

### ISSUE THREAD

**Issue by d3x0r** [microsoft/vscode#76284]
[Example Addon Module gist]( https://gist.github.com/d3x0r/a2a691daec3c4ed5c75f74f092c6bec7)

When I run a script that loads a module that registers atexit, the atexit is not invokes when the process ends when launched with VS code.

If I run the same command `node run.js` from the command line the atexit code is run.

I don't expect the script to not stop, so I don't think that this applies... https://github.com/Microsoft/vscode-node-debug/issues/1  although it looked similar.

I had put a breakpoint in the script, and as it was paused also attached visual studio and put a breakpoing in the atexit function, and it was not called, except when run from command line or visual studio (not visual code)

**Comment by connor4312** [comment]
I do not plan to fix this in js-debug.
