### ISSUE TITLE
Issues with Excel Export Reports - functions not yet external

### ISSUE THREAD

**Issue by CKL-CAalstede** [microsoft/vscode#76283]
I am having a tiny issue transfering our Reports that handle the Export to Excel into AL Language. All issues are created because certain Functions that are set to Global in C/AL Coding have not yet been made External for Extension development.

To fully achieve our conversion to AL we would need the following Functions set to External:
1. Table 370 Excel Buffer - Select Sheets Name
**[External]** SelectSheetsName(FileName : Text) : Text[250]
IF FileName = '' THEN
  ERROR(Text001);

FileManagement.BLOBImportFromServerFile(TempBlob,FileName);
TempBlob.Blob.CREATEINSTREAM(InStr);
EXIT(SelectSheetsNameStream(InStr));

2. Table 370 Excel Buffer - Update Book
**[External]** UpdateBook(FileName : Text;SheetName : Text)
UpdateBookExcel(FileName,SheetName,TRUE);

3. Codeunit 419 File Management - Upload File
**[External]** UploadFile(WindowTitle : Text[50];ClientFileName : Text) ServerFileName : Text
Filter := GetToFilterText('',ClientFileName);

IF PathHelper.GetFileNameWithoutExtension(ClientFileName) = '' THEN
  ClientFileName := '';

ServerFileName := UploadFileWithFilter(WindowTitle,ClientFileName,Filter,AllFilesFilterTxt);

**Comment by roblourens** [comment]
Sorry, I don't know what you are asking about. I assume this is regarding a vscode extension. Please file the issue on the extension's repo.
