### ISSUE TITLE
Support Include directive in Remote SSH config

### ISSUE THREAD

**Issue by kwando** [microsoft/vscode#76282]
My `.ssh/config` contains the `Include` directive which is just including another config file.

It would be super nice if those included hosts would also be shown in `connections` on the Remote-SSH tab.

**Comment by roblourens** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/65

**Comment by kwando** [comment]
Wow, and I even tried to search for a ticket. Shame on me, sorry for the noise.
