### ISSUE TITLE
format down

### ISSUE THREAD

**Issue by lujfsd** [microsoft/vscode#76292]
Issue Type: <b>Bug</b>

在保存格式化时，正个程序全部乱掉了
格式化之前
![1561725596(1)](https://user-images.githubusercontent.com/3353399/60342782-f4ca4280-99e4-11e9-852e-d47ae5fd94a6.jpg)
格式化之后
![1561725596](https://user-images.githubusercontent.com/3353399/60342784-f72c9c80-99e4-11e9-9a59-d76b04035ec6.jpg)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.4.0-17763-Microsoft
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.85GB (1.93GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.85GB (1.93GB free)|
|VM|67%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.85GB (1.93GB free)|
|VM|67%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.35.1
remote-wsl|ms-|0.38.0
code-settings-sync|Sha|3.3.1
doxdocgen|csc|0.4.3
xml|Dot|2.5.0
gitlens|eam|9.8.2
python|ms-|2019.6.22090
cpptools|ms-|0.23.1
markdown-all-in-one|yzh|2.4.0
vscode-proto3|zxh|0.3.0

</details>

**Comment by lujfsd** [comment]
That is Terminal,and mine is cpp file at formatting.
sorry for my English。

**Comment by roblourens** [comment]
VS Code doesn't include a formatter for cpp files by default, so an extension is doing the formatting. Probably the vscode-cpptools extension, please file this issue on their repo.

**Comment by lujfsd** [comment]
thanks ,i has submit issues:[#3859](https://github.com/microsoft/vscode-cpptools/issues/3859#issue-462238127) at vscode-cpptools
