### ISSUE TITLE
intellisense

### ISSUE THREAD

**Issue by ThiagoAlencar12** [microsoft/vscode#76299]
Issue Type: <b>Bug</b>

My intellisense stop runing in javascript, i dont no the cause, programming in node js, please help

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 5.0.0-19-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2999)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.66GB (1.97GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.8.0
RocketseatReactJS|roc|2.2.0
RocketseatReactNative|roc|2.2.0

(1 theme extensions excluded)

</details>

**Comment by FishOrBear** [comment]
https://github.com/microsoft/vscode/issues/70971
The big probability is that ts-server is broken. I have often encountered such problems recently.

Need restart ts server

**Comment by mjbvz** [comment]
Closing as not actionable
