### ISSUE TITLE
Error notification balloon keeps popping up endlessly

### ISSUE THREAD

**Issue by Groschenroman** [microsoft/vscode#76296]
Issue Type: <b>Bug</b>

I start VS Code from directory in shell using `code .` shortcut.
The application loads the current folder project and the notification in the lower right corner appears once and after some seconds it starts to reappear frequently without stopping.
I'll try to share a screen capture. I reloaded the window and restartet the whole app but the problem reoccurs.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.39GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular2|UVB|0.4.1
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
beautify|Hoo|1.5.0
vscode-settings-cycler|hoo|1.0.1
java-properties|ith|0.0.2
RelativePath|jak|1.4.0
svg|joc|0.1.5
Angular2|joh|8.1.1
code-beautifier|mic|2.2.1
vscode-scss|mrm|0.6.2
vscode-docker|ms-|0.6.4
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
csharp|ms-|1.20.0
debugger-for-chrome|msj|4.11.5
angular2-inline|nat|0.0.17
vetur|oct|0.21.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|1.7.1
code-settings-sync|Sha|3.3.1
stylelint|shi|0.51.0
sort-lines|Tyr|1.8.0
quokka-vscode|Wal|1.0.232
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by Groschenroman** [comment]
Screen capture of issue 
https://mega.nz/#!WIxU0Q5J!C6Gh2pgkjsL_o0t81tO8VvMoKu1Tb0_FrP5tvjndApw

**Comment by mjbvz** [comment]
Can you please re-upload the screenshot / recording to github
