### ISSUE TITLE
Can't copy text of removed change in the inline diff viewer

### ISSUE THREAD

**Issue by tunnij** [microsoft/vscode#76305]
- VSCode Version: 1.35.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Change a source controlled file by removing some lines
2. Open a diff editor in inline mode
3. Observe you can't select and copy text of the red highlighted, removed code
4. Change to side-by-side view
5. Observe you can select and copy text of the red highlighted, removed code

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/8226
