### ISSUE TITLE
terminal prompt disappears when typing a command

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#76309]
Issue Type: <b>Bug</b>

open vs code
open an integrated terminal (cmd)
![image](https://user-images.githubusercontent.com/7658657/60360190-232a2c80-99a9-11e9-95e1-4fa88c86c460.png)

start typing.
![image](https://user-images.githubusercontent.com/7658657/60360207-35a46600-99a9-11e9-97eb-7b34b43237f8.png)

actual:
the prompt text disappears.  the typed text displays properly

expected:
the prompt text does not disappear

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.00GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.20.0
vsliveshare|ms-|1.0.471

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by burtonrodman** [comment]
wow, that was fast.  Thanks!

**Comment by Tyriar** [comment]
🏎
