### ISSUE TITLE
Clink integrated terminal occasionally drops keystrokes on the UI when using backspace

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7630]
Steps to Reproduce:

1. Type a command
2. Press backspace, if you notice a character not being deleted and the cursor jumping back, run the command
3. The command ran will not be equal to the command on the UI

**Comment by Tyriar** [comment]
Another weird problem: pressing up*3 and down*3 multiple times screws up the current line.

**Comment by gerane** [comment]
I've noticed this in powershell as well.

**Comment by gerane** [comment]
Also issues with moving left or right. The visual cursor gets out of sync.

**Comment by Tyriar** [comment]
Oh Powershell too? I found Clink completely unusable because of this.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7345#event-700693361
