### ISSUE TITLE
New File

### ISSUE THREAD

**Issue by EduardoMX** [microsoft/vscode#76307]
Issue Type: <b>Bug</b>

On enter the new file button, for create a new file, its nothing happen, i reboot and nothing

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.2.0
vscode-peacock|joh|2.4.0
vsliveshare|ms-|1.0.471
vscodeintellicode|Vis|1.1.7

(8 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please explain some more. What exactly are you doing, and what do you see?

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by EduardoMX** [comment]
its a network issue, i have my files on a network drive, its disconnect for an instant, my pc reconnect, but code isnt, no warning,nothing, even on my pc a can see the network drive, but not on code, the solution its to close code,and reopened, i hope for a warning when this happen

**Comment by isidorn** [comment]
Can you reproduce with vscode inisders
