### ISSUE TITLE
Integrated terminal still occasionally freezes VSCode

### ISSUE THREAD

**Issue by FadeZhanger** [microsoft/vscode#76301]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS version: Windows_NT x64 10.0.18362

Maximizing, closing or killing the integrated terminal occasionally causes VSCode to hang completely, which can only be recovered by force quitting or waiting for the "Unresponsive window" dialog to present the option to reopen the window. This issue only seems to occur after the terminal has been running for some time.

Likely related to #72416 but this issue is still occurring in the latest insiders build.

Relevant settings:
```
"terminal.integrated.rendererType": "canvas",
"terminal.integrated.windowsEnableConpty": true,
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe",
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/76548
