### ISSUE TITLE
"editor.tokenColorCustomizations" shows different colors in different scope? 

### ISSUE THREAD

**Issue by RonnieDuck** [microsoft/vscode#76308]
See the image, after my customizing the theme color, Javascript's "const", "let", "var", "function" declaration does not change color under the class scope. Why? Is this a bug?
![image](https://user-images.githubusercontent.com/19317133/60359164-cbbca880-9a0a-11e9-967f-39fe8c296cb2.png)

![image](https://user-images.githubusercontent.com/19317133/60359204-edb62b00-9a0a-11e9-97c4-459ad34e5746.png)

**Comment by alexr00** [comment]
Can you run the "Developer: Inspect TM Scopes" command and click on the "var", "let", "const", and "function"? What scopes does the command say those have?

**Comment by RonnieDuck** [comment]
#### Which's purple color:
![image](https://user-images.githubusercontent.com/19317133/60558098-96052000-9d7a-11e9-80db-9f15b49fca0b.png)
![image](https://user-images.githubusercontent.com/19317133/60558108-9c939780-9d7a-11e9-9b47-6f99b924d488.png)
![image](https://user-images.githubusercontent.com/19317133/60558118-a1f0e200-9d7a-11e9-95f9-2651d9466229.png)
![image](https://user-images.githubusercontent.com/19317133/60558128-a7e6c300-9d7a-11e9-8d00-8343eb12067a.png)
#### Which's pink color:
![image](https://user-images.githubusercontent.com/19317133/60558165-d1075380-9d7a-11e9-88fc-feb867f3ae9f.png)
![image](https://user-images.githubusercontent.com/19317133/60558173-d5337100-9d7a-11e9-99fc-a2099f7f83f8.png)
![image](https://user-images.githubusercontent.com/19317133/60558178-d9f82500-9d7a-11e9-8289-5c600f644e83.png)
![image](https://user-images.githubusercontent.com/19317133/60558186-de244280-9d7a-11e9-9532-05e0bb7759e3.png)

@alexr00

**Comment by alexr00** [comment]
What theme are you using? If not one of the defaults, can you reproduce with a default theme? I don't see anywhere we might be using that color.

**Comment by RonnieDuck** [comment]
I use the [Snazzy Light
](https://marketplace.visualstudio.com/items?itemName=loilo.snazzy-light) theme, downloaded from [marketplace.visualstudio.com](marketplace.visualstudio.com)
And what's the meaning of "reproduce with a default theme"?

**Comment by alexr00** [comment]
The scopes listed are different, which means that any theme author can color them differently if they wish.

If you can reproduce the issue with a default theme, such as Dark+, then the color difference could be because of the theme that you have installed.

**Comment by alexr00** [comment]
It looks like the colors are different because the theme you have installed gets very specific.
The pink is coming from `meta.class storage.type` and the purple is from your customization of `storage`.

@aeschli Can you confirm that more specific wins with themes? 
```json
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": ["storage.type"],
				"settings": {
					"foreground": "#cc66ff",
					"fontStyle": "bold"
				}
			}
		]		
	}
```
This is the sample:
```javascript
var a = 1;
let b = 'sss';
const c = [];
function d() {}

class F {
    somr() {
        var w = 1;
        let x = 'sss';
        const y = {};
        function z() {}
    }
}
```

**Comment by aeschli** [comment]
Yes, the most specific match wins.

**Comment by RonnieDuck** [comment]
@alexr00 , I understand what you mean, maybe my expression was indistinct.
I change the "storage.type" scope to set bold and italic font style and it work except for colors under the class scope.
![image](https://user-images.githubusercontent.com/19317133/60694478-d7c7cf00-9f10-11e9-9cc8-34301625a298.png)
![image](https://user-images.githubusercontent.com/19317133/60694535-02198c80-9f11-11e9-9e61-5e8e09b51bd3.png)
As @aeschli  said that the most specific match wins, my customization should be the top priority, but except for colors now...🤔

**Comment by alexr00** [comment]
The theme specifies `meta.class storage.type`, which is more specific.
