### ISSUE TITLE
High CPU Consumption watcherservice node when use WSL remote project

### ISSUE THREAD

**Issue by BettoISC** [microsoft/vscode#76303]
Issue Type: <b>Performance Issue</b>

Just Opened VSCode and conected to WSL, and the process:
/root/.vscode-server-insiders/bin/[HASH]/node /root/.vscode-server-insiders/bin/[HASH]/out/bootstrap-fork --type=watcherService

![image](https://user-images.githubusercontent.com/3585089/60353567-ec93e800-998f-11e9-86e7-a3bdcfb3c1c4.png)

![image](https://user-images.githubusercontent.com/3585089/60353667-21a03a80-9990-11e9-9988-0fd62acf2507.png)

![image](https://user-images.githubusercontent.com/3585089/60353604-07665c80-9990-11e9-8370-af7efb063731.png)

VS Code version: Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|       Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2401)|
|Memory (System)|7.92GB (2.56GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    89	 10880	code-insiders main
    4	    82	   236	   gpu-process
    2	    63	  2084	   window (Issue Reporter)
    3	   241	  3388	   window (settings.json - abu-workspace (Workspace) [WSL] - Visual Studio Code - Insiders)
    0	    52	 11388	     extensionHost
    0	    32	  9292	       electron_node wslDaemon.js 
    0	     5	  3604	         C:\WINDOWS\System32\wsl.exe -d ubuntu-18.04 bash -c "'./scripts/wslServer.sh' 'fe0c3e785c22c3ed2d5caa7178488c92d62bdb08' 'insider' '.vscode-server-insiders' 'C:/Users/Beto/AppData/Local/Temp/vscode-remote-wsl/fe0c3e785c22c3ed2d5caa7178488c92d62bdb08/vscode-server-linux-x64.tar.gz'  "
    0	     5	  3420	           C:\WINDOWS\System32\lxss\wslhost.exe {e8e4b39b-de8e-4d08-bc09-92bfd170be47} 456 464 468
    0	    12	  5432	             console-window-host (Windows internal process)
    0	    11	 12124	           console-window-host (Windows internal process)
    0	    13	  9144	   electron-crash-reporter
    0	    68	 11964	   shared-process
Fetching remote diagnostics for 'wsl+ubuntu-18.04' timed out.
```

</details>
<details>
<summary>Workspace Info</summary>

```

Fetching remote diagnostics for 'wsl+ubuntu-18.04' timed out.;
```

</details>
<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.65.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.5
vscode-remote-extensionpack|ms-|0.15.0
sublime-keybindings|ms-|4.0.3
debugger-for-chrome|msj|4.11.5
odoo-snippets|mst|0.9.0
vscode-intelephense-client|bme|1.1.1
xml|Dot|2.5.0
gitlens|eam|9.8.2
php-debug|fel|1.13.0
sftp|lix|1.12.7
rainbow-csv|mec|1.1.1
formate|Mik|1.1.1
easy-less|mrc|1.4.5
python|ms-|2019.6.22090
css-auto-prefix|spo|0.1.7
wordpress-snippet|tun|1.1.5

</details>

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/864#event-2449466217

**Comment by BettoISC** [comment]
I've already read that threat, I've open this new one since that watcher config didn't work in my case.

**Comment by offero** [comment]
Seeing this issue now also.

![image](https://user-images.githubusercontent.com/4681330/60445951-53aed800-9bee-11e9-8c7d-14bef2627077.png)

![image](https://user-images.githubusercontent.com/4681330/60446041-7e009580-9bee-11e9-8770-8941777493f8.png)


Path:
C:\Users\me\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\offero\.vscode-server-insiders\bin\fe0c3
