### ISSUE TITLE
Remote-Containers Docker error "invalid mount config for type "bind"

### ISSUE THREAD

**Issue by jzngdt** [microsoft/vscode#76314]
Issue Type: <b>Bug</b>

Windows VS-Code Insider.
- Choose Remote-Containers: Open Folder in container
- Choose vscode-remote-try-python folder that was git cloned from VS-Code samples

During the setup, we receive the docker error:
 **...invalid mount config for type "bind": bind source path does not exist.**

No changes have been been to the git cloned folder vscode-try-python

I can't figure out why this same code works on MacOS and not Win10.
I've completely removed Code --uninstall the app, delete all the folders-- so nothing from a previous install was lingering.
I can run the app successfully with docker run. It just refuses to build inside Code on Windows.

(fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'Dev Container: Python Sample' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Dev Container: Python Sample' failed.
</details>Extensions: none

![vscode-remote-container-open-folder-error](https://user-images.githubusercontent.com/52288541/60363552-dac33c80-99b1-11e9-81d9-095b124724b8.JPG)

**Comment by chrmarti** [comment]
Sorry this slipped through our issue triage. Is this still a problem?
