### ISSUE TITLE
Autosuggest is missing `string` but shows `String` interface

### ISSUE THREAD

**Issue by norbertpy** [microsoft/vscode#76311]
- VSCode Version: `1.35.1`
- OS Version: `macOS Mojave 10.14.5`

Steps to Reproduce:

1. Open a `.js` file
2. Start typing `let s: string,`

Does this issue occur when all extensions are disabled?: Yes

![vscode-suggest](https://user-images.githubusercontent.com/10294525/60360993-e868ca00-9991-11e9-91c8-be1229bd6c79.gif)

As you see in the `gif`, the `.js` files are missing types in autosuggest. There is no `string`, `number`, etc and if I type `let s: string,` fast, it'll replace the `string` with `String`. There is a similar issue [Intellisence (JS) "String" replaced "string"](https://github.com/Microsoft/vscode/issues/72278) but it's locked and closed.

**Comment by mjbvz** [comment]
Why are you writing types in the js file? flow?

**Comment by norbertpy** [comment]
Yes but even if I disable all the plugins and set the `Language Mode` for current file to `typescript` it won't fix the issue.

**Comment by mjbvz** [comment]
Types are not supported in JS files. If you want JS files to be treated as typescript, try configuring `files.associations` and then restarting VS Code
