### ISSUE TITLE
Django debug stopped working after VSCode update

### ISSUE THREAD

**Issue by lzantal** [Microsoft/vscode#7631]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

After updating to the latest version of the editor Django debug stopped working. 
All breakpoints turn gray and the tooltip says "unverified breakpoint". 
Debugging runs but never hits the breakpoints.

**Comment by rebornix** [comment]
@lzantal are you using https://github.com/DonJayamanne/pythonVSCode extension for django debugging?

**Comment by weinand** [comment]
No information after 10 days -> closing.

**Comment by lzantal** [comment]
Ooops, github emails went to spam folder :( 
Yes I use that extension, latest version of VSCode fixed it 1.2.1

Thank you and sorry for not responding sooner.
