### ISSUE TITLE
Git create new branch not focused automatically with specific extension

### ISSUE THREAD

**Issue by xWiiLLz** [microsoft/vscode#76316]
Issue Type: <b>Bug</b>
I'm not sure if this issue should be submitted here since it's only happening when a third party extension (Git Graph) is focused. Please let me know if this should be addressed in Git Graph's repository issues.

1. Open the Git Graph extension
2. Navigate to the native VS Code branches list (bottom left corner)
3. Choose `Create new branch...` or `Create new branch from...` (Either with a mouse click or using keyboard arrows + Enter)
4. Input to enter branch name is not focused.

This is really annoying, since you can't use only your keyboard when using the branches menu to create new branches. You're required to manually click the branch name input before starting to type.

VS Code version: Code - Insiders 1.36.0-insider (e80dd4f217db6e230d311a87fdf4276f740f6445, 2019-06-25T05:19:01.461Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
gitstash|art|2.1.1
azds|azu|1.0.120190617
angular-schematics|cyr|1.23.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|2.4.0
git-graph|mhu|1.9.0
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.6.4
vscode-typescript-tslint-plugin|ms-|1.2.1
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.5
angular2-inline|nat|0.0.17
angular-console|nrw|8.0.5
vscode-jest|Ort|2.9.2
material-icon-theme|PKi|3.8.0
typescript-hero|rbb|3.0.0
sass-indented|rob|1.5.1
autoimport|ste|1.5.3
markdown-all-in-one|yzh|2.4.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I can repro with other webviews open. Webview stealing focus from the quick pick @mjbvz?

**Comment by mjbvz** [comment]
Looks like this has been fixed for me (potentially while fixing https://github.com/microsoft/vscode/issues/75209).

Closing this for verification in October
