### ISSUE TITLE
typescript `tsx` extension syntax highlighting problem

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [microsoft/vscode#76327]
- VSCode Version: 1.35.1 (1.35.1)
- OS Version: MacOS 10.14.5

![Screen Shot 2019-06-29 at 12 02 14 PM](https://user-images.githubusercontent.com/15520015/60378981-dc4e3c80-9a65-11e9-8ebb-10dadb6eaed2.png)

The last line `<TextSmall text={text}/>` should be highlighted with the same color as above.

If comment is removed, it works fine:

![Screen Shot 2019-06-29 at 12 02 35 PM](https://user-images.githubusercontent.com/15520015/60378982-e07a5a00-9a65-11e9-9d37-67028ab2db27.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@mjbvz please check it.

```
const Text: React.FunctionComponent<IProps> = (props) => {
  const { type, text } = props
  return (
      type === 'BIG'      ? <TextBig text={text}/>
    : type === 'BOLD'     ? <TextBold text={text}/>
    : /* type === SMALL */  <TextSmall text={text}/>
  )
}
```

```
const Text: React.FunctionComponent<IProps> = (props) => {
  const { type, text } = props
  return (
      type === 'BIG'      ? <TextBig text={text}/>
    : type === 'BOLD'     ? <TextBold text={text}/>
    : <TextSmall text={text}/>
  )
}
```

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/754 to track this upstream
