### ISSUE TITLE
Wrong matching parenthesis

### ISSUE THREAD

**Issue by yahwarang** [microsoft/vscode#76326]
Issue Type: <b>Bug</b>

Suppose we have python code like below,
```
(pa if pa == '(' else "" for pa in S)
```
when the cursor is located at the left parenthesis which is encapsulated by quotation mark , '(' , the editor shows an expected matching parenthesis, it should not point nothing, because the left parenthesis is escaped. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3789)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.86GB (52.30GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-preview|ajs|0.5.1
xml|Dot|2.5.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.11
python-coding-conventions|igr|0.0.4
r|Iku|1.1.0
MagicPython|mag|1.1.0
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
powershell|ms-|2019.5.0
gradle-language|nac|0.2.3
java|red|0.46.0
python|tht|0.2.3
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1

</details>

**Comment by roblourens** [comment]
Please file this on the Python extension repo.
