### ISSUE TITLE
Extension ordering seems off

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#7632]
- VSCode Version: 1.2.1
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Run ext install 
2. Type "python"

I expect to see the most popular python extension. Instead the order is not by download count. 

![image](https://cloud.githubusercontent.com/assets/2449568/16026225/c9229db8-3181-11e6-9a04-f0590bfcdf26.png)

Could be related to some recent changes to MP backend.

**Comment by gregvanl** [comment]
Looks like a recent regression, doesn't repro on 1.2.0

**Comment by joaomoreno** [comment]
Forwarded to marketplace team.
