### ISSUE TITLE
Indent detection detected 2 spaces file as 4 [ansible yml]

### ISSUE THREAD

**Issue by kaovilai** [microsoft/vscode#76320]
Issue Type: <b>Bug</b>

The content below (ansible yml) is to me, 2 spaces indented. but VSCode detects as 4 spaces. Allow custom one time per file text indent spaces setting.
----------------------------
```
---
# Implement your Pre Workload deployment tasks here

- name: get workers


- name: try to loop
  command: echo donothing

- fail:
    msg: 'Failed as requested from task' # not required. The customized message used for failing execution. If omitted, fail will simply bail out with a generic message.

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool

```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
java-run|cao|1.1.4
dart-code|Dar|3.2.0
flutter|Dar|3.2.0
gitlens|eam|9.8.2
json-tools|eri|1.0.2
code-eol|jef|1.0.8
cpptools|ms-|0.23.1
quicktype|qui|12.0.46
java|red|0.46.0
vscode-xml|red|0.7.0
vscode-yaml|red|0.4.1
vscode-autohotkey|sle|0.2.2
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
vscode-ansible|vsc|0.5.2

</details>

**Comment by oneslash** [comment]
Please use .editorconfig

**Comment by kaovilai** [comment]
Does that allow per file setting? Or alternative per session setting. I do not want a global setting to be 2 spaces

**Comment by oneslash** [comment]
Yes you can set per file type or use regular expression to set config. And it will work per project basis not the global

**Comment by kaovilai** [comment]
This is still an issue that should be solved without extension as it is fundamental.

If you are referring to a plug-in then I'll have to leave the issue open for now.

**Comment by oneslash** [comment]
The documentation https://editorconfig.org/ and please install extension.

Please copy paste here your config so we can see it.

I believe EditorConfig is becoming the standard for configuring editors.
