### ISSUE TITLE
Have IEditorRegistry.registerEditor take a lazy promise to an editor constructor?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76323]
For code splitting, I believe we should avoid importing the definitions of various editors—such as the `WebviewEditor` or settings editor—until they are actually needed. This  should be possible if we make `IEditorRegistry.registerEditor` take a Promise to an editor constructor instead of the constructor itself. We could us register an editor with an `import(...)` expression so that the editor code itself only needs to be loaded / processed when it needed

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/76324#issuecomment-506932019

**Comment by mjbvz** [comment]
Closing from conversation in #76324
