### ISSUE TITLE
selection of Debugger

### ISSUE THREAD

**Issue by deepanshumehtaa** [microsoft/vscode#76332]
Issue Type: <b>Bug</b>

visual studio every time ask me to select debug configuration on running my code by pressing f5
how i can select that debugger as default.
i don't know wether it is due to some extention

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.2.0
flutter|Dar|3.2.0
python|ms-|2019.6.22090

</details>

**Comment by roblourens** [comment]
You can create a launch config for your project so you won't have to select the type each time. Start by clicking the gear icon in the debug viewlet. More info: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
