### ISSUE TITLE
Enable Extension for workspace is not persisted across restarts

### ISSUE THREAD

**Issue by Leon99** [microsoft/vscode#76335]
- VSCode Version: 1.35.1
- OS Version: Win10.0.17763

Steps to Reproduce:

1. Disable an extension
2. Open a workspace (Git repo from a mapped SMB drive)
3. Enable the extension for a workspace
4. Reload window (or close/open VSCode with the same workspace)

Expected result:  the extension is enabled.

Actual result: the extension is disabled.

**Comment by sandy081** [comment]
Does it also happens for folders/workspaces on disk?

**Comment by Leon99** [comment]
Local folders are fine.

**Comment by sandy081** [comment]
@bpasero Looks like storage is not the same opening mapped drives

**Comment by bpasero** [comment]
@sandy081 local storage is persisted on the machine that VSCode is running on, independent from the workspace you open.

@Leon99 can you check if other state is persisted and restored when you open such a workspace, e.g. the list of opened editors?

**Comment by Leon99** [comment]
@bpasero no, the list of opened editors is not persisted for that workspace either.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Leon99** [comment]
Tried today's build, the same.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Leon99** [comment]
Done. Anything else I can help with?
[verbose.txt](https://github.com/microsoft/vscode/files/3372598/verbose.txt)
[console.txt](https://github.com/microsoft/vscode/files/3372599/console.txt)

**Comment by bpasero** [comment]
@Leon99 yeah weird, I can see how an attempt is made to open `c:\Users\Leon\AppData\Roaming\Code\User\workspaceStorage\0d8494725b95ecd23ec9681e3d2f677e\state.vscdb`, but I see no further output reading from that storage. Is there any way you could open a different folder from that SMB drive and see if it always reproduces? And if so, maybe send me one of those DBs for me to try to open?

**Comment by Leon99** [comment]
Opening another, non-root folder from that drive gives the same results. That state DB attached.
[state.zip](https://github.com/microsoft/vscode/files/3388644/state.zip)

**Comment by bpasero** [comment]
Thanks, it opens just fine for me on macOS at least and shows data. I cannot explain this issue, sorry.

**Comment by Leon99** [comment]
@sandy081 @bpasero what more info can I give to help with solving this?
