### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by struggle3** [microsoft/vscode#76336]
Issue Type: <b>Feature Request</b>

在终端执行npm start再次同步一下git后出现vs code异常退出

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.3.9600

**Comment by byyxx128** [comment]
1. English please.
2. It is not a feature request.
3. Please provide specific steps to reproduce.

**Comment by roblourens** [comment]
Need more info
