### ISSUE TITLE
Keep Open keyboard shortcut not working

### ISSUE THREAD

**Issue by caliniaru** [microsoft/vscode#76333]
Issue Type: <b>Bug</b>

"Ctrl + K + Enter" does not keep a file open. To replicate, open a folder with "Ctrl + K + O", then use "Ctrl + P"  to open the navigator, type a file name from the folder. Press "Ctrl + K + Enter" to keep it open, then press "Ctrl + P" to open another file. Type the name of a different file. The new file appears in the same window where the 1st file was displayed.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
powershell|ms-|2019.5.0
vscode-yaml|red|0.4.1

</details>

**Comment by bpasero** [comment]
@caliniaru I cannot reproduce:

![before](https://user-images.githubusercontent.com/900690/60381461-8f626a00-9a55-11e9-8d4f-e529c4a6b743.gif)

Is that what you see?

**Comment by caliniaru** [comment]
The problem occurs on the Windows version.

________________________________

**Comment by caliniaru** [comment]
Ah, sorry. I just saw your key combination. It is Ctrl+K, followed by Enter. I was using Ctrl+K+Enter with the Ctrl key pressed for K and Enter.
