### ISSUE TITLE
Optimized keyboard shortcuts for none US keyboards

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#76339]
Issue Type: <b>Feature Request</b>

Not all keyboards are build the same. The shortcuts however were created with a US-intl keyboard in mind. I have US-Intl keyboards everywhere exept on my laptop. 

Are there standard shortcut keyboard layouts for other keyboards? Is there a developer pushed platform to do so?

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Potentially useful info: https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexandrudima** [comment]
Let's track in #1240
