### ISSUE TITLE
Disabled breakpoint reverts the breakpoint to original location (not where it bound)

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#7633]
@isidorn @weinand 

We wanted to check what we are seeing is expected.

If a breakpoint is set on line `n`, and that breakpoint bound to line `m`, when the breakpoint is disabled (but the debug session is still running), the glyph goes back to line `n`.

![movingbreakpoint](https://cloud.githubusercontent.com/assets/637952/16027159/9e81f872-3188-11e6-8cc6-a9792f67cd78.gif)

VS doesn't behave that way: the disabled breakpoint stays on line `m` until the debugging session is stopped. When the debugging session is stopped, the breakpoint goes back to `n`.

![vsmovingbreakpoint](https://cloud.githubusercontent.com/assets/637952/16027261/5da9c4dc-3189-11e6-9c55-5ab6e0617370.gif)

Any thoughts whether it would make sense for VSCode to remember the line a breakpoint bound to and keep that information until the debugging session finishes?

**Comment by isidorn** [comment]
Yes this is designed behavior - we were inspired by the chrome debugger which behaves that way.
When the breakpoint is disabled making it jump to the original assigned position feels natural to me.

Closing as designed, but I have no strong opinion here so if @edumunoz or @weinand have strong preference I can easily be conviced to go in another direction.

**Comment by edumunoz** [comment]
Looping in @jacdavis and @delmyers in case they have a strong preference.

**Comment by jacdavis** [comment]
My only concern is the lack of unity between the VS experience and the Vscode experience as we try and unify the design and do things like support VSCode debug adapters inside Visual Studio. I suspect users are unlikely to notice this change in behavior, but if they did, it would appear as a bug in which ever product they were less familiar with.  I suspect Xamerin Studio probably has a third behavior in this case as well.
