### ISSUE TITLE
Extention is installing

### ISSUE THREAD

**Issue by SATYAM679** [microsoft/vscode#76341]
Issue Type: <b>Bug</b>

Any extension is not installing in my machine

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by roblourens** [comment]
Can you give some more details about exactly what you are seeing?
