### ISSUE TITLE
VSCode doesn't show variable value provided by debug adapter in hover if there are variable references

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#7634]
- VSCode Version: 1.2.0 stable
- OS Version: all

Steps to Reproduce:

1. Have a debug adapter that returns `variablesReference` as part of the `EvaluateResponse` on a hover.
2. The actual tip only shows information in the variables referenced, not the actual value of the main expression to evaluate.

The data tip should also show the value returned for the expression that is being evaluated during a hover.

Note the watch and the hover results:

![hoverbug](https://cloud.githubusercontent.com/assets/637952/16028425/02ef548e-3194-11e6-9325-72648bbd51b1.png)

@isidorn @weinand

**Comment by isidorn** [comment]
We have now added a title area in the complex variable hover - makes the whole thing look nicer and shows the missing value in your case. Check it out and let us know what you think

**Comment by edumunoz** [comment]
:+1: Thanks!
