### ISSUE TITLE
VSCode Freeze after moving file from folder to another one 

### ISSUE THREAD

**Issue by Blacktoviche** [microsoft/vscode#76344]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04 & Windows 10

Steps to Reproduce:

1.Move file from folder to another one a window prompt "update import for moved file 'xx'" 
2.Repeat the previous action twice or more VSCode freeze on windows, on Ubuntu VSCode and the whole system freeze 

I tried it on React and React-Native projects on both operating system 

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by mjbvz** [comment]
So this only happens when you have extensions enabled? What extensions do you have installed?

**Comment by Blacktoviche** [comment]
@mjbvz  I'm sorry but the last question was auto answered I did not answer it.
I didn't try VSCode without extensions.

**Comment by mjbvz** [comment]
Please try the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled to see if one of them is causing this issue
