### ISSUE TITLE
Reorder folder with drag and drop

### ISSUE THREAD

**Issue by hwhung0111** [microsoft/vscode#76346]
Issue Type: Feature Request

I usually add ten or twenty folders in a workspace. The order of these folders is according to the adding order. While I only use the first five folders, it's fine. But sometimes I get a new task, I need to use the first and last folders. I have to switch between the top folder and the bottom folder. It might not in the same view, I have to scroll up and down frequently. 

I want to have a feature that I can reorder folders order in 'explorer' or 'source control'. It's can be 'drag and drop' or another way.

**Comment by gjsjohnmurray** [comment]
It's pretty easy to change the order of root folders in a multiroot workspace by editing the JSON of the workspace settings.

**Comment by isidorn** [comment]
You can already drag and drop the root folders in the explorer to change their order.
Also you can open the F1 > workspace configuration file and change the order there manually.
Closing since this works already

**Comment by hwhung0111** [comment]
I know how to drag a folder to the bottom. But how to drag a folder and drop it between two folders?

**Comment by isidorn** [comment]
Are you using multi root workspace: if yes just drag and drop.
If not: then we do not support this. Checkout the feature request explorer sorting options and you might find what you want there.
