### ISSUE TITLE
process object used in browser/terminalTaskSystem

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76351]
https://github.com/microsoft/vscode/blob/7152aa5db53ece656bb8f1f4b92ecb3b18a1665e/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1378-L1387

I'm planning on copying this function to the terminal contrib for https://github.com/microsoft/vscode/pull/76349, so maybe tasks can use that?

**Comment by Tyriar** [comment]
@alexr00 FYI this now exists in terminal/node:

https://github.com/microsoft/vscode/blob/a570522203fef3ff5d9cb204125e899f7ed78bbb/src/vs/workbench/contrib/terminal/node/terminalEnvironment.ts#L82

Note that it's a little different the the method in tasks, the terminal one will ensure the path exists and return undefined if not.

**Comment by alexr00** [comment]
Since it's in node I can't use it in terminalTaskSystem. The bit of tasks code that calls `findExecutable` will never run where there isn't node. It should still be fixed though.

**Comment by Tyriar** [comment]
@alexr00 feel free to pull it into common if you need to, adding an optional env arg and passing the process deps in via findExecutable in node/terminalEnvironment.ts

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/4acba1a2dd2b84b3af789dfac33fc328b01beb23
