### ISSUE TITLE
Cannot type 'test(' without arbitrary autocomplete

### ISSUE THREAD

**Issue by cefn** [microsoft/vscode#76353]
- VSCode Version: 1.35.1
- OS Version: Linux x64 4.15.0-50-generic snap

Steps to Reproduce:

1. Try to type the following text on a new line in a .test.js file : test(
2. Have the entire line replaced with TextDecoderStream() without prompting

Does this issue occur when all extensions are disabled?: Yes

This is a duplicate of https://github.com/microsoft/vscode/issues/75408 which was closed without responding to the concern raised by the OP. 

I too am concerned this is very poor default behaviour for a source code editor and it prevents me from authoring jest test files.

The response to the original issue was to suggest users should read through all the VSCode documentation to find a setting which disables this extremely intrusive default. 

This didn't respond to the OPs issue, and my own, which is that this shouldn't be default behaviour and that if it is a new behaviour it is a regression.

**Comment by mjbvz** [comment]
This was answered in https://github.com/microsoft/vscode/issues/75408#issuecomment-501661143. That comment both explains why this is happening (commit characters) and how to disable it (`"editor.acceptSuggestionOnCommitCharacter": false`).

This behavior been the default for a long time and proves helpful in many cases, so we can't just disable it by default.
