### ISSUE TITLE
Quick suggestions shouldn't trigger when suggestion show in the meantime

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#76354]
- VSCode Version: Stable and Insiders
- OS Version: linux

Steps to Reproduce:

1. Set "quickSuggestionsDelay: 3000"
2. Trigger suggestions in a js/ts file and wait for 3s
3. Suggestions are filtered after 3s

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> Trigger suggestions in a js/ts file and wait for 3s

How do you trigger suggestions? By typing or via Ctrl+Space? In the former case, the described behaviour is expected because we cannot filter suggestions before requesting them. The latter case work well for me.

**Comment by diabolicle** [comment]
Here's what I'm doing with my preferred delay of 1s:

1. Typing console.log and getting [log, timeLog]
2. Waiting 1s and getting [log, log, timeLog] (the newest one is a snippet)

> the described behaviour is expected because we cannot filter suggestions before requesting them

Has this recently changed? I remember using a higher delay value a while ago without any issues, but now when I'm using a delay of 0.5-1s the suggestions seem to flicker as I type. It just feels really weird for this to happen because the description of the setting is

> Controls the delay in milliseconds after which quick suggestions will show up.

I interpreted this as "if the suggestions widget is not visible, it will become visible." Regardless, it doesn't seem like anyone else has run into this problem so I guess my interpretation is at fault here.

**Comment by diabolicle** [comment]
Could there be an additional setting called "quickSuggestionsRequestDelay" that controls the delay before requesting suggestions?

**Comment by jrieken** [comment]
> that controls the delay before requesting suggestions?

That's exactly how it is implemented and that's why I have a hard time understanding what your issue is... The reason for this setting is to prevent requests against language server when typing quickly.

**Comment by diabolicle** [comment]
The issue I'm facing is that if I want to increase the delay before the quick suggestion widget is visible, I have to deal with some flickering which is not a great experience. I think it would be optimal to have one setting configure the delay before the widget is visible and another for when the widget is already visible; i.e. I don't want the requests to be delayed if I've already invoked the suggestions.

The description for the current setting only references the suggestions "showing up" and not anything about language servers being queried which led to me to think this was unexpected behavior.

**Comment by diabolicle** [comment]
Actually, I'm now achieving my desired behavior by just turning off quickSuggestions. I'll close this because it was due to my misunderstanding.

**Comment by jrieken** [comment]
The rule is that the widget shows immediately when explicitly requesting suggestions, e.g pressing Ctrl+Space. It then shows often Loading... before showing a result. When suggestions are request implicit, e.g. by just typing, the widget only shows when suggestions have been computed. So, there should be no flicker. I wonder if you can create an animated gif that shows what you are seeing.

**Comment by diabolicle** [comment]
Yeah, sure. After examining the gif I don't know if I was correct in calling it "flickering", but it did seem to  appear that way when I was writing actual code.

![cast](https://user-images.githubusercontent.com/49266605/60530245-de273280-9ce7-11e9-9cd0-87dece28cfc1.gif)

**Comment by jrieken** [comment]
I see, thanks for clarifying! What happens is this: (1) Start typing, (2) quick suggest delay is started, (3) you type a `.` which triggers completions immediately, (4) the `.` completions shows `log`, (5) now the quick suggest delay is done and re-triggers completions. 

That's a bug, the quick suggestion shouldn't re-trigger when in the meantime suggestions are showing.

**Comment by diabolicle** [comment]
@jrieken Hi, sorry for bothering you, but could you reopen this again? I just tried the latest insiders and it doesn't seem like this was completely fixed. Here is what it looks like with a delay of 1s:

![cast](https://user-images.githubusercontent.com/49266605/60837355-812fee80-a1b7-11e9-98d7-ac92d052aaf4.gif)

**Comment by diabolicle** [comment]
@jrieken Sorry for bothering you, but could you reopen this again? I just tried the latest insiders and it seems like the fix might have introduced a regression. Here is what it looks like now with a delay of 1s:

![cast](https://user-images.githubusercontent.com/49266605/60842535-d3770c80-a1c3-11e9-9aeb-585d846263fa.gif)

**Comment by lramos15** [comment]
@diabolicle I'm not really seeing any change between stable and insiders can you explain what you believe the regression is
