### ISSUE TITLE
A file named flow.js will auto run.

### ISSUE THREAD

**Issue by mnxm01** [microsoft/vscode#76355]
Issue Type: <b>Bug</b>

1. Create a file named flow.js
2. Write some code in it
3. [ctrl + S] to save

The Microsoft ® Windows Based Script Host will run the code automatically.
When I open other jsfile in the same directory, the problem will repeat as well.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
iview-snippets|bos|0.2.1
vue-format|feb|0.1.6
vscode-flow-ide|gca|1.2.0
vscode-language-pack-zh-hans|MS-|1.35.1
vetur|oct|0.21.1

</details>

**Comment by Tyriar** [comment]
You have an extension called vscode-flow-ide.

**Comment by mnxm01** [comment]
thanks
