### ISSUE TITLE
VSCode doesn't save changes to file after running a process in terminal

### ISSUE THREAD

**Issue by allusernamestakenexceptthis** [microsoft/vscode#76356]
- VSCode Version: 1.35.1 (user setup)
- OS Version: windows 10x64 10.0.18362
Does this issue occur when all extensions are disabled?: Yes

issue: file changes are not saved, opening any other file no longer work, same with view extensions . all get stuck with progress indicator at the top.

Steps to Reproduce:

You'll need a 

1. directory with a lot files/folders to notice the issue, in my case a lot of folders as direct subdirectories and files inside each. but likely it's happening briefly unnoticed otherwise on normal directories .

2. python version 3.6.6 (perhaps any other version?)

1.run vscode with extensions disabled :  code --disable-extensions   (happens with extensions of course)
2.create a python script with the following code: ex. test.py

```
import os
import sys

dirs = {
	'c:\\directory_with_too_many_files\\',
}

for dir in dirs:
    print (dir)
    for root, subdirs, files in os.walk(dir):
        for filename in files:
            exit()
            
            print (filename)

```

use cmd integrated terminal to run:
python test.py

since we have exit statement it will exit immediately.  when you get back to the editor. there will be a momentarily freeze. now any changes you make won't save with ctrl+s or save from menu, for long while.  apparently vscode is waiting for file operations on the directory despite python process exited.  I'm not sure how or why. but this is happening every time.

I tried to test on c:\windows. but I didn't notice it happening. so even more files than windows folder have.

running python from external terminal e.g. cmd.exe. the issue doesn't happen.  only running python from integrated terminal produce the problem. 

I confirmed that python is not running after exit in task manager in either cases.

running with --verbose doesn't reveal anything useful. except File Watcher line doesn't appear in the verbose messages when the issue is happening.

killing vscode from task manager (as can't exit from x button) and opening the vscode again can allow save again but doing the  same steps above reproduce the issue.

**Comment by bkcsfi** [comment]
I might also have this issue, or something similar.

I run code-insiders on ubuntu 18.04.2 LTS.  I apt update && apt upgrade every single day to get the latest version. I'm currently running 1.36.0-insider

I've noticed sometime in the past 7 days that code-insiders stops saving files. I do not see a spinning indicator. Clicking 'save', CTRL-S, Save-All, etc. still shows the file as 'open editors - 1 unsaved' 
also git commit warns about unsaved code changes.

Once in this condition, I cannot exit code-insiders using file/exit or ctrl-Q, I have to use killall to stop all code-insiders related processes including vsls-agent

Looking in the dev tools console, I don't see anything  obviously wrong. It is complaining that /snap/bin/microk8s.kubectl doesn't not exist (I have this snap disabled)

Process explorer also doesn't seem to show anything fishy to me, i.e. all tasks are 0% cpu.

Similar to @allusernamestakenexceptthis I am also opening a terminal window to run docker swarm deploy commands. In the most recent 'hang', I'm editing a docker-compose.yml file.

In my case, after opening the terminal and keeping it open I can continue to save files for a while. 

Some of my code is in Python and some folders may have a python interpreter selected. I don't think this is related to Python itself though.







Version: 1.36.0-insider
Commit: b7ca272b6e041e42f9edfe48f4d559c2044cdaae
Date: 2019-07-02T12:07:21.186Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-43-generic

**Comment by Tyriar** [comment]
This sounds like it might be https://github.com/microsoft/vscode/issues/71966
