### ISSUE TITLE
I want to tell vscode call which debug type by current extension name

### ISSUE THREAD

**Issue by Carson126** [microsoft/vscode#76361]
when I editing html,css,javascript, I want to debug the current file with browser.
when I editing php, I want to debug the current file with php(xdebug).
At this time, I have to change debug configuration.
so that I want to have a way to tell vscode which debug configuration to be use by current file extension name.

**Comment by weinand** [comment]
There is at least one extension that provides this functionality: https://marketplace.visualstudio.com/items?itemName=PhillipCao.debug-current

**Comment by Carson126** [comment]
Maybe it's not clear what my words, i want to debug current file with right debugger config options.
at this time, when i debug html, i have to change options to launch firefox and when i debug python, i've change to launch python. i want vscode autochange to the right option by Current file extension. thanks i lot.
