### ISSUE TITLE
Tree: Keybinding shortcuts with Alt stopped working

### ISSUE THREAD

**Issue by yc9274** [microsoft/vscode#76369]
Issue Type: <b>Bug</b>

when i press shift+alt+r it searches for "r" in list instead of revealing it in explorer

VS Code version: Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:35.956Z)
OS version: Windows_NT x64 10.0.18895

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
What does shift+alt normally do?

**Comment by joaomoreno** [comment]
@ChangLCS @yc9274 Did this behavior change recently, or was it always like this?

**Comment by ChangLCS** [comment]
@joaomoreno  Only after updating

**Comment by joaomoreno** [comment]
Yup, found the underlying issue. This will go into a candidate release.
