### ISSUE TITLE
Signature helper wobbling when typing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76363]
VS Code version: Code - Insiders 1.36.0-insider (fe0c3e785c22c3ed2d5caa7178488c92d62bdb08, 2019-06-28T12:34:48.210Z)
OS version: Darwin x64 18.6.0

![wobble](https://user-images.githubusercontent.com/2193314/60393322-4a2b5000-9ac8-11e9-887f-8db728e64c67.gif)

**Comment by rebornix** [comment]
@Tyriar do you change the zoom level, font size, etc? I didn't reproduce this with latest insiders on macOS.

**Comment by Tyriar** [comment]
I can't repro anymore
