### ISSUE TITLE
how can I expand a specific tree view and  collapse others in a ContainerView

### ISSUE THREAD

**Issue by MrKevinLu** [microsoft/vscode#76376]
I want to expand a specific tree view and collapse others in a ContainerView by using api "vscode.commands.execute('workbench.view.xxx')".  But there seems  no way to control the display of tree views in ContainerView  but can only control whether display the ContainerView. Whether there is some method to do it?

**Comment by sandy081** [comment]
@MrKevinLu What is the use case for doing this?

**Comment by MrKevinLu** [comment]
> @MrKevinLu What is the use case for doing this?

I am writing an extension that has multiple capabilities presented in a ContainerView. Each capability is presented as a tree view. For example, a capability of creating project from templates. I will list the templates in a  tree view and I wish the interface can switch to the tree view when user clicks a button from a custom welcome page or from a context menu, and then user can select a template in the tree view to create project.  Whether there is any method to do that? I do not want to use webview to realize it.

**Comment by sandy081** [comment]
@MrKevinLu You can open a particular view using `reveal` api on tree view or calling a command `workbench.view.extension.{viewid}`.

Re collapsing other views, I think there should be a user gesture to have it or not instead of automatically doing it by the extension.
