### ISSUE TITLE
gb2312编码文本文件打开失败

### ISSUE THREAD

**Issue by kinth-bd** [microsoft/vscode#76370]
Issue Type: <b>Bug</b>

gb2312编码文件打开失败，我已经是用指定编码打开的了，在notepad++打开没有问题

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
gc-excelviewer|Gra|2.1.32
vscode-language-pack-zh-hans|MS-|1.35.1
python|ms-|2019.6.22090

</details>

**Comment by roblourens** [comment]
Please give more details about what you are trying to do. Please include the actual file if possible

**Comment by kinth-bd** [comment]
I had find what the problem is,I changed the End-of-line sequence and destroyed the file.thanks
