### ISSUE TITLE
Pug/vue syntax highlighting fails sometimes

### ISSUE THREAD

**Issue by pqvst** [microsoft/vscode#76373]
- VSCode Version: 1.35.1 (1.35.1) & 1.36.0-insider
- OS Version: macOS 10.14.5 (18F203)

### Steps to Reproduce:

A colon-prefixed attribute that is not the first attribute does not get highlighted correctly (whereas @-prefixed does). Colon-prefixed attributes are shorthand notation for Vue.js property binding.

**Important**: The bug is not *visible* in some color themes (e.g. Dark+).

![image](https://user-images.githubusercontent.com/4990657/60397866-935abe80-9b1f-11e9-9a73-0596f70b884b.png)

```pug
body
  .foo(foo="foo" bar="bar")

  .foo(foo="foo" v-bind:bar="bar")
  .foo(foo="foo" :bar="bar")
  .foo(:foo="foo" bar="bar")
  
  .foo(foo="foo" :[bar]="bar")
  .foo(:[foo]="foo" bar="bar")

  .foo(foo="foo" v-on:bar="bar")
  .foo(foo="foo" @bar="bar")
  .foo(@foo="foo" bar="bar")

  .foo(foo="foo" @[bar]="bar")
  .foo(@[foo]="foo" bar="bar")
```

(It seems github syntax highlighting has the same issue)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to grammar owner's repo: https://github.com/davidrios/pug-tmbundle/issues/32
