### ISSUE TITLE
Syntax highlight for vscode python not working in Insider release 1.36.0 

### ISSUE THREAD

**Issue by pranav08** [microsoft/vscode#76385]
- VSCode Version: Insider release 1.36.0 
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Just open any python project and file. The syntax highlighting is not working properly. I have attached the example image where the IDE has no sense of commented lines

![image](https://user-images.githubusercontent.com/1762064/60409493-a0d97c80-9be3-11e9-8b27-91458a56b899.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Can you try disabling all extensions and running again? I can't reproduce.

**Comment by pranav08** [comment]
@alexr00 There is just 2-3 extensions installed. Surprisingly the culprit is 'Python for VSCode'. Once I disabled and reloaded this VSCode after disabling this particular extension, the syntax highlight is back to normal

![image](https://user-images.githubusercontent.com/1762064/60512333-07e65680-9cf4-11e9-86da-ae8e3399d5e2.png)

Also another thing to note is, In my normal VSCode build 1.35.1, the syntax highlighting works fine with this extension. Any suggestions?

Thanks a lot for your help
