### ISSUE TITLE
Go extension not working

### ISSUE THREAD

**Issue by phungvandat** [microsoft/vscode#76388]
- VSCode Version: 1.35.1 
- OS Version: Macos 10.13.6
- Go Version: 1.12.6

I installed all packages from the suggested Go extension. But when I tried to import a package from GOPATH I was not recommend. The error .go file immediately does and not ref to the previously imported pakage. I turned off vscode and rebooted it before I ran out of errors.

**Comment by dbaeumer** [comment]
@phungvandat please file the issue here: https://github.com/microsoft/vscode-go
