### ISSUE TITLE
Allowing integrated terminal zoom by mouse scroll

### ISSUE THREAD

**Issue by geekonloose** [microsoft/vscode#76381]
This is similar to  [#72011](https://github.com/microsoft/vscode/issues/72011), but it would be very convenient to allow zoom for integrated terminals (especially for the small screen). Of course, this can be implemented only on the terminals which are supporting scroll zoom (for ex, git bash, bash etc)

**Comment by LucaSorvillo** [comment]
Please introduce this required functionality, it is absurd that every time I have to go and change the terminal font in setting...

**Comment by Tyriar** [comment]
@LucaSorvillo if it's a common thing you do, you could make a simple extension to toggle between two values. In fact there may be generic extensions that do this already.

**Comment by LucaSorvillo** [comment]
@Tyriar I would be really happy if it could be solved so easily 😊

**Comment by Tyriar** [comment]
@LucaSorvillo some other ideas that might help:

- If it's wrapped lines you can also hit alt+z to toggle "fake wrapping" where we size the terminal's width the the largest wrapped line
- The Terminal: Set Fixed Dimensions command allows you to do this but to a fixed number of columns
- You can pipe the output of a command to vscode, I think the syntax is `<cmd> | code -`
- Ctrl+shift+up in the terminal should select the output of the previous command to easily copy/paste into an editor

**Comment by LucaSorvillo** [comment]
@Tyriar Thanks again, I'm used to zooming with mouse scroll also because I use it a lot in Windows Terminal ..

**Comment by o-l-a-v** [comment]
If/ when this ever get's implemented (CTRL+scroll for zoom in the terminal), I'd like an option to link the terminal zoom level to the editor zoom level. Like PowerShell ISE does it.
