### ISSUE TITLE
Unity keeps opening new instances of Microsoft Visual Studio code

### ISSUE THREAD

**Issue by jackxuechen** [microsoft/vscode#76382]
- VSCode Version:1.35.1
- OS Version:macOS 10.14.5

Unity keeps opening new instances of Microsoft Visual Studio code.Even if the vscode is already open, each time you double-click the cs file in unity, a new vscode opens.

**Comment by dbaeumer** [comment]
@jackxuechen this sounds like a problem with a Unity extension. Which extension do you have installed?

**Comment by jackxuechen** [comment]
@dbaeumer The unity version is 2019.1.8f1

**Comment by jackxuechen** [comment]
the unity version is 2019.1.8f1

**Comment by jackxuechen** [comment]
@dbaeumer 
unity version:2019.1.8f1
VSCode Version:1.35.1
OS Version:macOS 10.14.5
Problem:
Unity keeps opening new instances of VScode.Even if the vscode is already open, each time you double-click the cs file in unity, a new vscode icon Appear in the Dock of Mac OS.

**Comment by dbaeumer** [comment]
Does this happens if you disable unity ? If no can you please file the issue against the unity extension?

**Comment by jackxuechen** [comment]
It is no problem opening cs files directly in the finder.I will feed back to unity.Thanks!
