### ISSUE TITLE
A solution about that markdown.styles with a GitHub URL is not working  

### ISSUE THREAD

**Issue by SepCode** [microsoft/vscode#76384]
A URL is under the https://raw.githubusercontent.com domain, Those don't work because GitHub responds with X-Frame-Options.

**Comment by SepCode** [comment]
If you want to use that file "https://github.com/SepCode/vscode-markdown-style/blob/master/preview/github.css", we know that "https://raw.githubusercontent.com/SepCode/vscode-markdown-style/master/preview/github.css", the URL is not working.

I have a good idea, we can use Github Pages.

Add a submodule in your repository, like this "`git submodule add https://github.com/SepCode/vscode-markdown-style.git`". And now we can use the URL "https://sepcode.github.io/vscode-markdown-style/preview/github.css" set markdown.styles.

Step:



- clone your GitHub pages "`git clone https://github.com/SepCode/SepCode.github.io.git`"
- `cd SepCode.github.io`
- `git submodule add https://github.com/SepCode/vscode-markdown-style.git`
- `git commit -am 'added vscode-markdown-style module'`
- `git push`
- setting vscode setting.json
    ```
    {
        "markdown.styles":["https://sepcode.github.io/vscode-markdown-style/preview/github.css"]
    }
    ```

**Comment by mjbvz** [comment]
Yes, for github content you must either either download the file or host it somewhere else. No plans on working around this

Also—although this all seems well intended—I must add that it is a very bad idea to tell people to use stylesheet from a resource that they do not control. Just download the css file or use an extension like [this one](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles)

**Comment by SepCode** [comment]
Yeah, the vscode-markdown-style repository is just an example, we should use ourself's CSS file, and I also know this extension. But this way is more convenient and controllable.
