### ISSUE TITLE
No markdown preview button when a file is not named ending with .md

### ISSUE THREAD

**Issue by fenying** [Microsoft/vscode#7638]
- VSCode Version: 1.2.0
- OS Version: Windows 7

Steps to Reproduce:

1. Open a file named with extension like `.txt`, only if not `.md`.
2. Switch language mode to `Markdown`.

**Now there is no `Preview` button to switch to Markdown Preview view.**

**Comment by rebornix** [comment]
I second this. Preview feature is supposed to go with the language mode instead of file extensions. BTW, I think it's also Okay to preview txt files even if it's recognized as plain text, just like what we have in Atom.
