### ISSUE TITLE
Snippets: Transforms not working with same tabstop

### ISSUE THREAD

**Issue by BrendanThompson** [microsoft/vscode#76383]
- VSCode Version: `v1.35.1`
- OS Version: macOS `10.14.5`

Steps to Reproduce:

As per the below two snippets, the first one does not work. After hitting **tabstop** 2, entering the value and tabbing out the transformation does not occur. However, if I change the second occurrence of **tabstop** 2 to 3 then it works upon tabbing from 3 -> 4

As seen in #59516 this should work, although in the reference issue its talking about an uppercase transform.

Nonworking snippet:
```
{
	"Managed Terraform Module": {
		"prefix": "tf_nanaged_module",
		"body": [
			"module \"${1|azurerm,gcp,aws|}_${2}\" {",
				"  source = \"./modules/terraform_module_repo\"",
			  
				"  provider_name = \"${1}\"",
				"  name          = \"${2/[\\_]/-/g}\"",
				"  description   = \"$4\"",
				"  core_team_id  = ${5:github_team.core.id}",
			  "}"
		],
		"description": "Create skeleton for AzureRM Module for the Managed Module repository."
	}
}
```

Working snippet:
```
{
	"Managed Terraform Module": {
		"prefix": "tf_nanaged_module",
		"body": [
			"module \"${1|azurerm,gcp,aws|}_${2}\" {",
				"  source = \"./modules/terraform_module_repo\"",
			  
				"  provider_name = \"${1}\"",
				"  name          = \"${3/[\\_]/-/g}\"",
				"  description   = \"$4\"",
				"  core_team_id  = ${5:github_team.core.id}",
			  "}"
		],
		"description": "Create skeleton for AzureRM Module for the Managed Module repository."
	}
}
```

**Comment by jrieken** [comment]
Both work for me, the first sample transforms the value of placeholder 2 (when typing at its first (!) occurrence) when moving to 3. In the second sample the value updates when move I from 3 to 4. Please update your steps. 


![Jul-01-2019 11-13-07](https://user-images.githubusercontent.com/1794099/60424773-5828c000-9bf1-11e9-85d0-783b8c86fd68.gif)

**Comment by BrendanThompson** [comment]
@jrieken hey there, sorry took me so long to get back to you! I managed to get this working on another laptop but it still doesn't work on my primary work laptop.

I am using the VSCode Remote Development stuff, could have be causing an issue?

**Comment by jrieken** [comment]
> I am using the VSCode Remote Development stuff, could have be causing an issue?

Hm, I wouldn't know why...
