### ISSUE TITLE
Add multiple work spaces with entirely different tabs

### ISSUE THREAD

**Issue by lazercaveman** [microsoft/vscode#76399]
Sometimes one has to work on to different project folders (like a backend API and a related Web-App for example). If this is, it can be annoying if tabs of separate project folders are mixed - so wouldn't it be nice to have entirely separated work spaces with entirely different tabs opened, related to the selected work space!?

Example: I have 2 project work spaces. 
Work space 1 now has 3 opened (projectTab1, ProjectTab2, ProjectTab3)
If I switch to work space 2 to Tabs of work space 1 will disappear (projectTab1, ProjectTab2, ProjectTab3), and the tabs, which are related to work space 2 will show up (like project2Tab1, Project2Tab2, etc).

If I go back to work space one I will se my opened tabs over there again (projectTab1, ProjectTab2, ProjectTab3).

**Comment by bpasero** [comment]
@lazercaveman would you say this is a "Working Sets" feature where you can switch these sets and this makes the list of tabs change? Asking because we have a duplicate I think.

**Comment by lazercaveman** [comment]
@bpasero  I mean one should have multiple working spaces, which can contain several root-folders (projects). switching related tabs by switching work spaces also comes along with that, if not is the main feature to me...

**Comment by bpasero** [comment]
@lazercaveman isn't that covered by https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by lazercaveman** [comment]
Thank you, I'll have a look at it later, maybe it is something - I'll report.

**Comment by bpasero** [comment]
Ok, closing for now.

**Comment by 1138-4EB** [comment]
> @lazercaveman would you say this is a "Working Sets" feature where you can switch these sets and this makes the list of tabs change? Asking because we have a duplicate I think.

Can you, please, provide the reference to that duplicate?
