### ISSUE TITLE
[folding] instead of  '...' show body content for short methods

### ISSUE THREAD

**Issue by procodix** [microsoft/vscode#76396]
This function will allow to toggle the code view to "compact" mode. Compact mode means that short methods will be displayed as a one-liner. It looks similar to a folded methods, but the method's body remains visible. A method is conisdered short, if it fits on one line in the current viewport, or if it is shorter than a configurable number of lines / characters.

Technically a compacted method simply replaces all line-breaks with a blank/space, while it has no focus.

The feature operates completely in memory, the underlying editied file remains unchanged. If a compacted method is focused, by clicking or moving the cursor inside its body, it transforms to its original view, so that editing looks and works as expected. The cursor simply remains at the clicked position, while the line-breaks are restored. By Clicking outside the method being edited, it returns to compact mode.

Benefit is better readability for short methods. Compared to folding, all code remains visible, and no toggles are required. Optimizes real estate use on wide screen displays. 

Example for "Normal View"
PHP:
```
public function Test($aParam)
{
    $this->Test = $aParam;
    return $this;
}
```
CSS:
```
body {
    background:#f00; 
    color:#000;
    border:1px solid #ff0000;
    font-size:1.6rem;
}

```
"Compact View":
PHP:
`public function Test($aParam) {$this->Test = $aParam; return $this;}`

CSS:
`body {background:#f00; color:#000; border:1px solid #ff0000; font-size:1.6rem;}`

**Comment by aeschli** [comment]
Nice idea!

**Comment by procodix** [comment]
it should be added, that in the case of LESS, recursion is neccessarry:
```
.test {
    background:#f00; 
    color:#0f0;
    img {
        width:100%;
        boder:1px solid #f00;
    } 
}

```
would transform to:

```
.test {background:#f00; color:#0f0;
    img {width:100%; boder:1px solid #f00;} 
}
```

Focusing ".test" class by setting the cursor on one of its attributes would leave "img" definition compacted.

**Comment by aeschli** [comment]
dup of #70794
