### ISSUE TITLE
extension shows as "Installing" until I reload the workbench

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#76400]
MacOS, Stable build

After installing the Azure Tools extension pack, the Azure Account extension shows "Installing..." until I reload the workbench.

To reproduce, make sure you don't have any Azure extensions installed and then install the "Azure Tools" extension pack.  

![image](https://user-images.githubusercontent.com/1487073/60431657-8792f900-9c00-11e9-9de3-36ba37b46d09.png)

Once all the extensions have been installed you'll see that the Azure Account extension continues to show "Installing":

![image](https://user-images.githubusercontent.com/1487073/60431604-6af6c100-9c00-11e9-97cb-67e664e38303.png)

If I reload the workbench, the AA extension then shows as Installed.

**Comment by chrisdias** [comment]
Note also that the Azure Account extension is a dependency of the other Azure extensions and is not included in the `extensionPack` section of the Azure Tools `package.json`.

**Comment by sandy081** [comment]
@chrisdias Tried couple of times but failed to repro. Is there any specific steps I shall follow?

**Comment by chrisdias** [comment]
upgraded to latest stable and it doesn't repro now :(
