### ISSUE TITLE
Toggle search Details icon update

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#76402]
@roblourens , the toggle search details button on the search layout is expanding the view and showing "Files to include" and "Files to exclude" and clicking on that again will hide the same thing ( Collapse it back ) 
If this button is doing just this then "expand and collapse icon" (The little triangle one facing downwards) will make more sense rite? 

The current icon shows three dots ( It does not open any menu on clicked )

![image](https://user-images.githubusercontent.com/17094832/60432955-2fb8ba00-9c21-11e9-8c5f-4b5908072908.png)

**Comment by roblourens** [comment]
I like the `...` better since we are already using `>` in the search viewlet, and also because it is showing and hiding a detail section entirely, not collapsing it into a smaller form.
