### ISSUE TITLE
Code scrolls instead of finding, switches to Normal instead of Copying

### ISSUE THREAD

**Issue by TimurOzsan** [microsoft/vscode#76404]
Issue Type: <b>Bug</b>

When I launch MSVSCode it won't let me edit the python script unless I switch from 
-- Normal -- 
to 
-- Insert --
the cursor turns from a block to a line.

Ctrl + F scrolls instead of finding, although the Key binding for find is Ctrl + F.

Ctrl + C returns it from Insert back to Normal.  Which means I can't copy and paste code into a report

MSVSCode version 1.35.1 (system setup)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.86GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-test-explorer|hbe|2.12.1
vscode-python-test-adapter|lit|0.3.8
MagicPython|mag|1.1.0
python|ms-|2019.6.22090
cpptools|ms-|0.23.1
python|tht|0.2.3
vim|vsc|1.8.1

</details>

**Comment by rebornix** [comment]
The behavior is contributed by the Vim extension you are using. If you are using VSCodeVim, it has options to allow you to override this behavior.
