### ISSUE TITLE
Index all files in Workspace for faster content search

### ISSUE THREAD

**Issue by Montago** [microsoft/vscode#76403]
Searching in content across 1000's of files seems VERY SLOW

eg: we have a folder with 200 customer website folders , and if i then need to search through ALL JS files or simply all js files called xx.js then search using VSCode is extremely slow. 

1st, it shouldn't take long to locate all files with a specific name
2nd it shouldn't take that long to locate all occurances of some medium long text in all of the files, eg:  "updatePreview" in all *.JS files .. 

Searches like these can take 5 minutes which seems a bit long !!

My thought is to improve it by utilizing some sort of index / db / whatever...

**Comment by roblourens** [comment]
You can see tips about search perf here: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

But it's not likely that we will change how this works in the near future.
