### ISSUE TITLE
Handle disposable result of createAndFillInActionBarActions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76419]
From #74922

The `createAndFillInActionBarActions` function returns a disposable which cleans up the returned actions. There are a few places in our code where we may not be handling the returned disposable properly. Please review these and handle the disposable result as if required. 

- [x] @joaomoreno  https://github.com/microsoft/vscode/blob/a280393c6b713edcc0d3ccffc9db5b10c6dcce01/src/vs/workbench/contrib/scm/browser/scmViewlet.ts#L118
- [x] @joaomoreno https://github.com/microsoft/vscode/blob/a280393c6b713edcc0d3ccffc9db5b10c6dcce01/src/vs/workbench/contrib/scm/browser/scmMenus.ts#L79
- [x] @isidorn https://github.com/microsoft/vscode/blob/a280393c6b713edcc0d3ccffc9db5b10c6dcce01/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L268
- [x] @joaomoreno https://github.com/microsoft/vscode/blob/a280393c6b713edcc0d3ccffc9db5b10c6dcce01/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L261

**Comment by isidorn** [comment]
@mattbierner  Thanks for pointing this out.

**Comment by joaomoreno** [comment]
Great catches!
