### ISSUE TITLE
Breadcrumbs should change based on cursor location in diff view

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#76417]
To me it seems weird that when I am in a side by side diff view that the breadcrumbs are always based on the right hand side. I would like it so that the breadcrumbs change based on my cursor and update with the respective file accordingly. I am unsure what the expected behavior would be with inline diffs however.

**Comment by jrieken** [comment]
That's to be aligned with other language features, like quick outline. Another reason is that the left hand side doesn't live on disk and most language server won't be able to provide good outline for such files.

**Comment by lramos15** [comment]
I guess this makes sense. I was using side by side view when both files lived on disk and I expected it to work because some things like peek and goto definition work. I see that you can't navigate via symbols in the menu either though so I guess it wouldn't really make sense to add breadcrumb support as that is effectively what breadcrumbs do.
