### ISSUE TITLE
Sass/Scss intellisense is broken in latest builds.

### ISSUE THREAD

**Issue by admmasters** [Microsoft/vscode#7641]
- VSCode Version: Version 1.2.0 (1.2.0) Current Insiders
- OS Version: OSX

Steps to Reproduce:

1. Open a _base.scss file
2. Start typing.

Intellisense has stopped working in css files - this seemed to occur 1-2 nightlies ago.

**Comment by aeschli** [comment]
I'm currently working on refactoring the SCSS support. It will be 100% functional again later today. Sorry and thanks for reporting the issue.
If you are todays build, first open an css file, then switch to the scss file and intellisense should work.

**Comment by admmasters** [comment]
Cool thanks for the quick reply - no problem! 👍

**Comment by admmasters** [comment]
@aeschli unfortunately - intellisense seems broken completely for css and sass files now in the latest insiders build.

**Comment by admmasters** [comment]
Don't worry - just seen your commit! 👍
