### ISSUE TITLE
Symlinking extensions into extensions dir no longer works

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76425]
Repro:

clone vscode ext samples, build terminal sample

```
ln -s $(pwd)/vscode-extensions-samples/terminal-sample ~/.vscode-oss-dev/extensions/terminal-sample
```

The extension shows up in disabled and cannot be enabled.

![image](https://user-images.githubusercontent.com/2193314/60461943-e2c2ec80-9bfc-11e9-88cd-fd22744e4a0c.png)

Copying the folder over works but this is very inconvenient compared to my previous setup.

**Comment by sandy081** [comment]
Working in insiders and stable, broken only in master. Will investigate.

**Comment by sandy081** [comment]
@bpasero [this](https://github.com/microsoft/vscode/commit/00acc08e0d7a3c1bed48a51b96eff010e84c049d) broke reading sym links in the directory

https://github.com/microsoft/vscode/blob/2c3e8a8e39d568464e4a14ab861ef2658f25612a/src/vs/base/node/pfs.ts#L482

Sym links are not read now.
