### ISSUE TITLE
Lag for file to be recognized as changed in SCM when remote

### ISSUE THREAD

**Issue by tunnij** [microsoft/vscode#76423]
Hi,

Unsure if here is right place but I've noticed when editing a file (no existing changes) then it can sometimes take a while for it to show up in the 'changes' section of SCM.

I'm using remote-ssh.

- VSCode Version: 1.35.1
- OS Version: Windows_NT x86 10.0.17763

Steps to Reproduce:

1. Check out a git project in remote ssh
2. Edit a file
3. Save the file
4. Observe that the file doesn't show up in the changes section.
5. A manual refresh makes it show up. 

Is there maybe a setting for it to check more frequently automatically? Does it need to be a polling mechanism?

**Comment by tunnij** [comment]
Note that the file explorer notices the file. I then hit save and the numbered icon on file explorer disappears. But nothing changes in the SCM view.

**Comment by joaomoreno** [comment]
How much is a while?

**Comment by tunnij** [comment]
On a small repo I have it takes about 1 second.

On a large repo I use I just timed a saved file change taking 3 minutes to
show up in scm. On second timing it took 2.5 minutes. So the lag is
repeatable.

Both using remote-ssh and both connected to the same host.

If I click the refresh button in scm manually then the changed file shows
up in about a second for the large repo.

**Comment by joaomoreno** [comment]
Can you run `Developer: Set Log Level...`, change it into `Debug`, then `Git: Show Git Output`, and then edit a couple of files. Can you show me the output?

**Comment by tunnij** [comment]
> git remote --verbose
> git show :scripts/snapshot.py
> git fetch
Warning: No xauth data; using fake authentication data for X11 forwarding.
X11 forwarding request failed on channel 0
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse jt_dev
> git rev-parse --symbolic-full-name jt_dev@{u}
> git rev-list --left-right jt_dev...refs/remotes/origin/jt_dev
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

There's no timings on these logs but between `git show :scripts/snapshot.py` and `git fetch` is the lag I observe. As soon as `git fetch` runs its instant.

**Comment by joaomoreno** [comment]
How big is scripts/snapshot.py?

**Comment by tunnij** [comment]
snapshot.py is 83 lines. I’m following the other issue where it looks to be the same thing but please let me know if there’s any more info I can give.
