### ISSUE TITLE
Git diff highlights wrong column depending on zoom level

### ISSUE THREAD

**Issue by bergwerf** [microsoft/vscode#76424]
- VSCode Version: 1.35.1
- OS Version: Debian 9.9

I tested with different fonts and ligatures enabled/disabled, but in all cases the issue persists. The git diff shows highlights where text was changed inside the line (i.e. the whole line is light red but the change is dark red). However this dark red highlight is shifted incorrectly, and changes relative to the text depending on the zoom level. The positioning at 100% zoom is also incorrect in many cases. If needed I can produce a repro, but I think it should be fairly easy to reproduce unless it depend on some platform specific font rendering/measuring thing.

**Comment by dbaeumer** [comment]
@bergwerf can you please attached a screen shot.

**Comment by bergwerf** [comment]
Here are a few cases (zoom in/out with Ctrl +/-)

![image](https://user-images.githubusercontent.com/4458965/60505177-7101a600-9cc3-11e9-9c85-176bff27592c.png)
![image](https://user-images.githubusercontent.com/4458965/60505208-8545a300-9cc3-11e9-9477-5ab20484de1c.png)
![image](https://user-images.githubusercontent.com/4458965/60505302-bc1bb900-9cc3-11e9-9f51-4a7f96fe653d.png)

**Comment by alexandrudima** [comment]
This does not reproduce for me on Ubuntu... So I'm thinking it is related to your environment / specific distro... Do you have any other details?

In the meantime you can use `"editor.disableMonospaceOptimizations": false`.

**Comment by bergwerf** [comment]
I am no longer able to reproduce this on `1.36.1` so perhaps something got fixed. If I encounter this issue in the future I will report back to this issue.
