### ISSUE TITLE
resources.relativePath needs a `ignoreCase` argument

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#76421]
If two resources have windows like paths and with non-file scheme then `resources.relativePath` is giving me wrong values.

```ts
resources.relativePath(URI.file('c:\\foo\\bar\\').with({scheme: 'vscode-userdata'}), URI.file('c:\\foo\\bar\\a1\\a2').with({scheme: 'vscode-userdata'}))
```

Expected: `a1\a2`
Actual: `../c:\foo\bar\a1\a2`

**Comment by aeschli** [comment]
I ran your example on Window and it results in `a1/a2` which is correct.

- URI.file('c:\\foo\\bar\\') only works as you expect when ran on Windows. `\` is a valid file name character on Linux/Mac, so URI.file would not try to convert '\' to '/'
- For non-file URI, the resource util uses posix path logic: Doesn't know about path roots (/C:/), nor does it treat `\` as separators.

**Comment by aeschli** [comment]
This is the sample that causes issues:
`resources.relativePath(URI.file('c:\\foo\\bar\\').with({scheme: 'vscode-userdata'}), URI.file('C:\\foo\\bar\\a1\\a2').with({scheme: 'vscode-userdata'}))`

We're missing the 'ignoreCase' argument on `resources.relativePath`
