### ISSUE TITLE
Compare merge conflict

### ISSUE THREAD

**Issue by jceval** [microsoft/vscode#76439]
When looking at and resolving merge conflicts, you are presented with the option to 'Compare Changes'
![image](https://user-images.githubusercontent.com/45887246/60472785-14e54600-9c1f-11e9-9290-c090aa04714b.png)

The resulting side-to-side split should allow you to resolve conflict by allowing you to select which side, left (current) or right (incoming) of the conflict you want to keep through the merge.

**Comment by hediet** [comment]
With the introduction of the 3 way merge editor, it is unlikely that we will implement this feature soon.
