### ISSUE TITLE
VSCode SSH Remoting with Windows target

### ISSUE THREAD

**Issue by wolfgangam** [microsoft/vscode#76436]
Visual Studio Code's new remoting feature is awesome, but I'd like to be able to remote develop on Windows from Linux. 

The docs (https://code.visualstudio.com/docs/remote/ssh) specify 'linux host' as the target for remote development, and I have been unable to successfully remote develop with Windows 10 1903 with OpenSSH server installed. 

I haven't been able to find a feature request or issue describing this feature, nor is it part of the 2019 iteration plans (https://github.com/microsoft/vscode-remote-release/issues/608). 

I'm willing to help add the functionality but will need some guidance. Thanks.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/25
