### ISSUE TITLE
window.showTextDocument type signature inconsistency

### ISSUE THREAD

**Issue by Huxpro** [microsoft/vscode#76433]
- VSCode Version: 1.35.1
- OS Version: Darwin x64 18.5.0

Steps to Reproduce: 
Minimal code:

```ts
import {  window } from 'vscode'
import {  TextDocument } from 'vscode-languageserver';

 const doc: TextDocument = TextDocument.create(
  //@ts-ignore
  editor.document.uri.with({scheme: passScheme}),
  editor.document.languageId, 1, "'')

window.showTextDocument(doc);
```

![Screen Shot 2019-07-01 at 3 17 57 PM](https://user-images.githubusercontent.com/5563315/60470011-a8187e80-9c13-11e9-87a8-8f84974ba646.png)

From here: `showTextDocument` has constructor taking `TextDocument` as first argument.

![Screen Shot 2019-07-01 at 3 18 08 PM](https://user-images.githubusercontent.com/5563315/60470013-a9e24200-9c13-11e9-8ec5-44008380784e.png)

From here: `doc` is typed with `TextDocument` and not type check with `Uri`

**Comment by jrieken** [comment]
The `TextDocument` isn't a type from the type, hence an invalid argument and TypeScript picks some overload for its error message
