### ISSUE TITLE
C++ syntax highlighter breaks with certain macro definitions

### ISSUE THREAD

**Issue by cristian64** [microsoft/vscode#76430]
- VSCode Version: 1.35.1
- OS Version: Linux (I guess also Windows)

Steps to Reproduce:

1. Open any existing C++ file in Visual Studio Code (no extension required).
2. Insert the following at some point in the document:
```
#define EXTERN_C extern "C"
```
3. Observe how, from that line on, the syntax highlighting goes bad.

![broken_syntax_highlighting](https://user-images.githubusercontent.com/1853278/60466585-f47fb080-9c4b-11e9-94fe-d8072faad34a.gif)

Does this issue occur when all extensions are disabled?: Yes.

**Comment by alexr00** [comment]
Thank you @matter123 for fixing this so quickly! I have pulled in the latest grammar and added a macro to our test file.

**Comment by cristian64** [comment]
This was quick.
