### ISSUE TITLE
VSCode Wont open on Mac

### ISSUE THREAD

**Issue by StevenMonty** [microsoft/vscode#76438]
- VSCode Version: 1.35.1 and 1.11.2
- OS Version:  OS X 10.13.6

Steps to Reproduce:

1. Download VSCode.zip
2. Unzip
3. Attempt to run

Does this issue occur when all extensions are disabled?: Yes

My terminal does not recognize the `code` command and when I try to unzip it I get the message that only 4968 of 4987 files could be unzipped. Moving the app to the Applications folder and attempting to open does not work. Below is the Apple bug report: 
```
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.35.1 (1.35.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [44373]
User ID:               501

Date/Time:             2019-06-19 18:19:29.097 -0400
OS Version:            Mac OS X 10.13.6 (17G65)
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by StevenMonty** [comment]
@bpasero I am getting the same issue. Still wont open and the same zip issue. 
<img width="337" alt="Screen Shot 2019-07-02 at 8 56 21 PM" src="https://user-images.githubusercontent.com/28907147/60555674-f610ad80-9d0b-11e9-8b60-cc30a14fd94c.png">

**Comment by bpasero** [comment]
@StevenMonty this seems to be an issue with your Securezip program?

**Comment by StevenMonty** [comment]
Wow, I feel like an idiot. Thank you for your time.
