### ISSUE TITLE
Remove suppressImplicitAnyIndexErrors

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#76442]
Although VS Code is now strict null checked, we currently set `"suppressImplicitAnyIndexErrors": true`. This setting allows using bracket accessors on values, even if the value's type does not specifically have an index access signature.

This is bad because it can easily end up hiding errors that TypeScript could have caught:

```ts
const map = new Map()
map.set('property', true);

...

if (map['property']) { // This is not an TS error but it does not do what you want!
    doImportantStuff();
} 
```

# Fix
The good news is that there are only around 240 errors total and these errors are typically not too difficult to fix. Here's the process:

1. In `./src/tsconfig.base.json`,  set `"suppressImplicitAnyIndexErrors": false`
1. Restart the compile (if using `watch`)
1. Open the file you wish to fix errors in and fix the errors:

    Potential fixes include:

    - Use a `Map` or `Set` instead of an object literal.

    - Add an index signature to the type

    - Cast to a type with an index signature (or any)

Here's the complete list of files with errors. I've assigned a few potential owners but feel free to claim others:

 - [x] `vs/base/common/console.ts`  @mjbvz 
 - [x] `vs/base/parts/storage/node/storage.ts` @mjbvz 
 - [x] `vs/code/electron-browser/issue/issueReporterMain.ts` @RMacfarlane 
 - [ ] `vs/code/electron-main/window.ts` 
 - [ ] `vs/editor/standalone/browser/standaloneLanguages.ts` @mjbvz 
 - [x] `vs/platform/configuration/common/configuration.ts` @sandy081
 - [x] `vs/platform/configuration/common/configurationModels.ts` @sandy081
 - [x] `vs/platform/configuration/common/configurationRegistry.ts`@sandy081
 - [x] `vs/platform/environment/node/environmentService.ts` @sandy081
 - [x] `vs/platform/extensionManagement/node/extensionGalleryService.ts` @sandy081
 - [ ] `vs/platform/instantiation/common/instantiationService.ts` @mjbvz
 - [x] `vs/platform/windows/electron-main/windowsService.ts` @bpasero 
 - [x] `vs/workbench/api/browser/mainThreadTreeViews.ts` @sandy081 
 - [x] `vs/workbench/api/common/extHostTreeViews.ts` @sandy081 
 - [x] `vs/workbench/browser/editor.ts` @bpasero 
 - [ ] `vs/workbench/browser/parts/editor/editorStatus.ts` @mjbvz 
 - [x] `vs/workbench/browser/parts/views/viewsViewlet.ts` @sandy081 
 - [ ] `vs/workbench/contrib/comments/browser/commentsEditorContribution.ts`
 - [x] `vs/workbench/contrib/debug/browser/rawDebugSession.ts` @isidorn 
 - [x] `vs/workbench/contrib/debug/test/node/debugger.test.ts` @isidorn 
 - [ ] `vs/workbench/contrib/experiments/electron-browser/experimentService.ts`
 - [ ] `vs/workbench/contrib/extensions/common/extensionQuery.ts` @mjbvz 
 - [x] `vs/workbench/contrib/extensions/electron-browser/extensionEditor.ts` @sandy081 
 - [x] `vs/workbench/contrib/localizations/browser/localizations.contribution.ts` @sandy081 
 - [x] `vs/workbench/contrib/preferences/browser/keybindingsEditor.ts` @sandy081 
 - [ ] `vs/workbench/contrib/preferences/browser/settingsEditor2.ts` @roblourens 
 - [ ] `vs/workbench/contrib/preferences/browser/settingsTree.ts` @roblourens 
 - [ ] `vs/workbench/contrib/preferences/electron-browser/preferencesSearch.ts` @roblourens 
 - [x] `vs/workbench/contrib/quickopen/browser/viewPickerHandler.ts` 
 - [x] `vs/workbench/contrib/tasks/common/taskConfiguration.ts` @alexr00 
 - [ ] `vs/workbench/electron-browser/window.ts` @bpasero 
 - [ ] `vs/workbench/services/extensions/common/abstractExtensionService.ts` @alexandrudima  
 - [ ] `vs/workbench/services/extensions/common/extensionsRegistry.ts` @alexandrudima 
 - [x] `vs/workbench/services/keybinding/common/keybindingEditing.ts` @sandy081
 - [x] `vs/workbench/services/workspace/electron-browser/workspaceEditingService.ts` @sandy081

**Comment by aeschli** [comment]
TypeScript seems to not understand iteration with `in`. @mjbvz What's the suggested worksaround?

interface MyObject {
   a: string;
   b: string;
}
const myObject : MyObject = { a: "val1", b: "val2 };
for (const key in myObject) {
    console.log(myObject[key])  // typescipt doesnt like this, why?
}

**Comment by aeschli** [comment]
I started to use the following workaround to be able to use `for ... in ...`
```ts
interface MyObject {
   a: string;
   b: string;
}
const myObject : MyObject = { a: "val1", b: "val2" };
for (const objectKey in myObject) {
    const key = <keyof typeof myObject> objectKey;
    console.log(myObject[key]) 
}
```

**Comment by mjbvz** [comment]
@aeschli See this comment for more info about the issue: https://github.com/microsoft/TypeScript/issues/31087#issuecomment-486175658

**Comment by mjbvz** [comment]
Only around errors left. I've updated the list and assigned some initial owners

**Comment by dbaeumer** [comment]
@mjbvz I compiled VS Code today using `yarn run gulp compile` and I receive a ton of compile errors. Looking at the list in the description not everyone seems to have the work done. Any reason why the compiler flag got already removed.

**Comment by bpasero** [comment]
@dbaeumer run `gulp mixin-server` and try again.

**Comment by dbaeumer** [comment]
Thanks.

**Comment by dbaeumer** [comment]
@bpasero can I also 'unmix' ?

**Comment by aeschli** [comment]
@dbaeumer `git clean -xdf`. Of course don't do this while you have uncommited changes.

**Comment by dbaeumer** [comment]
@aeschli Thanks
