### ISSUE TITLE
OUTPUT during debugging not showing

### ISSUE THREAD

**Issue by nmaxcom** [microsoft/vscode#76445]
- VSCode Version: 1.35.1 (1.35.1)
- OS Version: macOS 10.12

I'm trying to debug a nodeJS app called strapi. It doesn't work with my database, but that's not the point. It has to be run on a strapi folder like `strapi develop`.

This is what I see in my terminal:
![image](https://user-images.githubusercontent.com/8936090/60486583-400f7a00-9c9f-11e9-9a72-790c75ff708b.png)

When debugging in Webstorm it shows up:
![image](https://user-images.githubusercontent.com/8936090/60486918-92509b00-9c9f-11e9-907e-92b5d305698f.png)

But, using the same debug configuration (program, arguments etc.) nothing shows in VSCode:
![image](https://user-images.githubusercontent.com/8936090/60487257-e8254300-9c9f-11e9-96a6-cdcc3581d446.png)

For a debugging like this, I can't use VSCode. This is my launch config:

```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "/usr/local/lib/node_modules/strapi/bin/strapi.js",
      "cwd": "${workspaceFolder}",
      "args": ["develop"],
      "console": "internalConsole",
      "outputCapture": "std"
    }
  ]
}

```

Searching in past issues, I found someone with a similar problem that was solved by using that console and outputCapture settings. I've tried all combinations, and it doesn't work for me.

I've also tried all combinations of breaking in "All exceptions", "Uncaught exceptions"... The debug stops when a thousand other exceptions happen, but not in this error I'm trying to fix. Breakpoints also work but still, can't see the output on the console, so I'm flying blind.

Ideas?

**Comment by weinand** [comment]
@nmaxcom does it make a difference if you set `console` to `"integratedTerminal"`?

**Comment by nmaxcom** [comment]
No. Sorry, I forgot to mention I tried all three `console's`.

**Comment by mpunak** [comment]
Definitely still an issue.


The following source:
![Source Code](https://user-images.githubusercontent.com/6179773/66674564-0e03a180-ec18-11e9-8d04-80fa041ef1c8.png)

With Internal console for output capture
**launch.json**
```
"configurations": [
    {
        "type": "node",
        "request": "launch",
        "name": "logging test",
        "program": "${workspaceFolder}/test.js",
        "console": "internalConsole", //integratedTerminal,internalConsole
        "outputCapture": "std"
        
    }
```
Has the following output in Debug console after 20-30  seconds:
![debug console](https://user-images.githubusercontent.com/6179773/66674601-24116200-ec18-11e9-9f77-8d36e9779243.png)

The first output makes it, but nothing after.





Same program running under integrated terminal..
**launch.json**
```
"configurations": [
    {
        "type": "node",
        "request": "launch",
        "name": "logging test",
        "program": "${workspaceFolder}/test.js",
        "console": "integratedTerminal", //integratedTerminal,internalConsole
        "outputCapture": "std"
        
    }
```

Output:
![Integrated terminal](https://user-images.githubusercontent.com/6179773/66674646-39868c00-ec18-11e9-90e8-665755d139f6.png)


Integrated terminal works. Integrated console does not.

Some additional information... any interaction with the debug console gets stdout to flush to the console. Tabbing off of the debug console, perhaps to the terminal tab, and then tabbing back, ALSO gets the output to flush.

**Comment by weinand** [comment]
This works fine for me in VS Code 1.43.2 bot for the internal console as well as the integrated terminal:

![Uploading 2020-04-06_16-17-35 (1).gif…]()
