### ISSUE TITLE
access data file in extension

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#76446]
- VSCode Version: 3.1.8
- OS Version: win10 x64

Steps to Reproduce:
I am writing a lisp extension, and want to support the auto-complete feature. For me there are about 1000 library functions. If user inputs a char, I want to search in these library functions, and then return the "best" matches.
I want to put all the 1000 functions in a data file, and then put the data file in the extension.
Then in the "export function activate(context: vscode.ExtensionContext)" how I can access the data file? I see the current path is the vscode installation path.

1. put a data.txt file in Mockdebug sample
2. then write the codes in "export function activate(context: vscode.ExtensionContext)" like:
  	fs.readFile("../allinternals.txt", function(text){
		var func = text.split("\n");
		internalFuncs.push(func);
	});
3. Debug the extension

Result: it reports there is no path in vscode path.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@jrieken can you please help him.

**Comment by jrieken** [comment]
To read a file that's bundled with your extension you need use the `ExtensionContext#asAbsolutePath(relativePath: string)`-function. It's available on the `context` that's passed to the activate call.
