### ISSUE TITLE
The built-in terminal displays wrong colors (everything is green or red)

### ISSUE THREAD

**Issue by irudyi-carecloud** [microsoft/vscode#76449]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Open the built-in terminal 
- Execute any command that prints colored text

Actual result: all texts have the same color

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
githistory|don|0.4.6
gitlens|eam|9.8.2
xml-format|mik|1.0.2

</details>

**Comment by Tyriar** [comment]
Update to 1.35.1
