### ISSUE TITLE
Can't see conflicts on yarn.lock files

### ISSUE THREAD

**Issue by wissog** [microsoft/vscode#76443]
Issue Type: <b>Bug</b>

make conflicting changes in yarn.lock file in two different branches.
try to merge one branch to another and get a confict in yarn.lock file
see the conficting changes are not displayed.

other types of files are OK, i currently found only yarn.lock is problematic to me

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|29.1.0
beautify|Hoo|1.5.0
easy-icons|jam|0.3.1
MagicPython|mag|1.1.0
debugger-for-chrome|msj|4.11.5
html-css-class-completion|Zig|1.19.0

(15 theme extensions excluded)

</details>

**Comment by wissog** [comment]
after playing with stage and unstage it displayed the changes only in unstage mode, but NOT in stage mode.

**Comment by joaomoreno** [comment]
> see the conficting changes are not displayed.

What is displayed, then?

**Comment by wissog** [comment]
the files are displayed without the expected marked changes


*Gabi*

*"What R we living for?" :)*

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the full workbench showing that?
