### ISSUE TITLE
change default shell under vscode terminal failed

### ISSUE THREAD

**Issue by gaoyangang001** [microsoft/vscode#76444]
- VSCode Version: 1.35.1
- OS Version: macos mojava

Steps to Reproduce:

 I exec `chsh -s /bin/zsh` under vscode terminal, but it shows `chsh: no changes made` (/bin/zsh already installed in the path), and `echo $SHELL` shows the old shell (`/bin/sh`)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
https://apple.stackexchange.com/a/88296
