### ISSUE TITLE
How to not return immediately to shell when VSCode is executed from shell

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#76454]
When I open a file in VSCode form Bash by typing `code ${FilePath}` it returns immediately i.e. I can start typing next command before closing the file. 

If I do the samething with other editors like `gedit ${FileFpath}` the prompt waits for me to close the file.

I need this behavior with Vscode, as I am executing a bashscript which open a file in the middle, and the next process should occur only after the file is closed.

How can I make the bash prompt wait for me to close the file?

**Comment by dbaeumer** [comment]
`-w` or `--wait`
