### ISSUE TITLE
VScode remote jsconfig paths optoin doesn't work

### ISSUE THREAD

**Issue by nicooprat** [microsoft/vscode#76452]
- VSCode Version: Version 1.36.0-insider (1.36.0-insider)
- OS Version: Mac 10.13.6 (17G65)

Steps to Reproduce:

1. Create a `jsconfig.json` file as below
2. Open a file with an import using the `@` alias
3. Intellisense can't find imported files

![image](https://user-images.githubusercontent.com/645641/60498137-5543d300-9cb6-11e9-8d0e-aad74c7541ff.png)

My `jsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "@": ["./src"]
    },
  },
  "exclude": [
    "node_modules"
  ],
}
```

Does this issue occur when all extensions are disabled?: Yes

Couldn't find any other issue related to this here or on StackOverflow. Thanks.

**Comment by nicooprat** [comment]
Looks like it's working in the stable channel though (1.35.1). Letting you close the issue if it's OK.

**Comment by mjbvz** [comment]
That error looks like it is coming from the eslint extension. Please start by filing an issue against that extension
