### ISSUE TITLE
Horizontal scrolling occurs despite word wrap enabled with GitLens decorations

### ISSUE THREAD

**Issue by sandersaares** [microsoft/vscode#76458]
Issue Type: <b>Bug</b>

I pressed the "end" key on my keyboard and was surprised to see the viewport scroll horizontally, as I have word wrap enabled. I do not think I have changed anything in the VSCode configuration recently. Presumably this is a regression in a recent VSCode version, as I have not encountered it before (working on the same files on the same PC).

Screenshot of horizontally scrolled viewport after pressing End key on my keyboard: 

![image](https://user-images.githubusercontent.com/9914262/60505624-c8584400-9ccc-11e9-8f5a-568908382a12.png)

Expected behavior: viewport never scrolls horziontally when word wrap is enabled.

Using font Consolas, so should not be related to proportional fonts.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.65GB (17.50GB free)|
|Process Argv|--folder-uri file:///c%3A/Source/DASH-IF-IOP|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|9.8.2
plantuml|jeb|2.11.1
azure-pipelines|ms-|1.152.0
powershell|ms-|2019.5.0
vscode-yaml|red|0.4.1

</details>

**Comment by sandersaares** [comment]
Still occurs after updating to latest stable release:

```
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by duncanawoods** [comment]
I have had to abandon vscode for writing markdown because of this so really hope to see a fix soon!

**Comment by webdevnerdstuff** [comment]
Please fix this bug already. With word wrap on it should never have a horizontal scroll bar. Sometimes it works, and then you add some code, and then it's broken until you mess around with word wrap on/off again.  Sometimes just saving the document causes the horizontal scroll bar to show up. It even happens with the editor in full width with the left drawer closed. There is plenty of space in the code and it doesn't extend the full width, yet it still has the horizontal scroll bar. This is extremely annoying, especially when working on a laptop and scrolling with the track pad. 

The other ticket referenced by vscodebot is not applicable.

**Comment by alexandrudima** [comment]
I cannot easily reproduce this. Does this reproduce when using a monospace font and when disabling all extensions?

Here I am trying with this file: https://github.com/microsoft/vscode/blob/master/README.md

![Kapture 2019-08-05 at 11 16 18](https://user-images.githubusercontent.com/5047891/62453365-7c3c6b80-b772-11e9-9f28-70e9bcdbbff4.gif)

**Comment by duncanawoods** [comment]
It doesn't happen on window resize but when
* typing a long paragraph, as each line breaks the h-scroll gets borked
* pressing `end` on a long line within a paragraph that is at the page width limit

> disabling all extensions

I think it might be gitlens. If you look at @sandersaares image, gitlens adds inline text to indicate commits e.g. in the paragraph you can see light grey text saying `you a few seconds ago . uncommitted`.

You can see how that spills over the page width but isn't real text so doesn't break across lines. I think that might be causing the issue.

**Comment by duncanawoods** [comment]
I can confirm that disabling `GitLens>CurrentLine>Enabled` to turn off the blame annotation fixes the unwanted horizontal scrolling for me.

I don't know if the wrapping bug from that annotation is a VSCode or a GitLens responsibility but it had been introduced quite recently.

**Comment by alexandrudima** [comment]
Currently, text decorations such as those contributed by GitLens are not taken into account when computing wrapping points. 

The text decorations are rendered after the wrapping points have been established and then the horizontal scrollbar is expanded in order to be able to see them.

**Comment by duncanawoods** [comment]
> The text decorations are rendered after the wrapping points have been established and then the horizontal scrollbar is expanded in order to be able to see them.

That's not what is happening. The horizontal scrollbar is not increased sufficiently to read the annotation. If fact I'm not sure that the annotation needs to even cross the page width.

The amount of extra horizontal scroll created is only a single character. This doesn't make annotations visible but it does making typing infuriating because the view continuously rescrolls itself as you write each line and it the resting point is scrolled to the rhs which cuts off the start of all lines meaning you can't properly read what you are typing.

**Comment by alexdima** [comment]
Let's track in #32856
