### ISSUE TITLE
Keyboard is unresponsive withing vs code

### ISSUE THREAD

**Issue by bogdangrab** [microsoft/vscode#76453]
- VSCode Version: 1.35.1
- OS Version: Windows 10/ MacOs 10.14 - i think any OS and or version, but these two I use

Steps to Reproduce:

1. Switch from any window. I cannot reproduce it myself as it seems to show up when you least expect it. I am constantly switching windows from Chrome to VS Code and back. 

Does this issue occur when all extensions are disabled?: Yes/No
This would mean duplicate this issue across a days work to see if it still happens which is not really an option for me.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
