### ISSUE TITLE
Add bash start container command before vscode debug command

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#76457]
# System information
- OS: Ubuntu 16.04
- VSCode: v1.36.0-insders
- Singularity: 3.2.1

# Problem description
I'm currently trying to debug a python script that needs access to a python environment that is inside a singularity container. I was, therefore, wondering if there is an option to set a pre to debug command before the debug command.

*Example:*
```
singularity run --nv CONTAINER; VSCODE debug command
```

**Comment by isidorn** [comment]
VSCode does not support running debug from the command line. There is already an open feature request for that.
Thus closing this a duplicate of that issue (you can search for existing issues to find it)

**Comment by rickstaa** [comment]
@isidorn Thanks for your answer. Can you maybe link it to the existing issue? I, unfortunately, could not find it using the `debug from the command line` search stream.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/10979
