### ISSUE TITLE
HTML Syntax Broken when specifying script src extension.

### ISSUE THREAD

**Issue by carljohnesan** [microsoft/vscode#76450]
HTML syntax is broken after I specify extension in script src attribute. Nowhere else. So when I type dot in src all syntax is broken. How can I fix it?

![vscode bug  screen](https://user-images.githubusercontent.com/47556468/60494496-938dc200-9cb7-11e9-9dc8-bf37c4d92ea4.png)

**Comment by alexr00** [comment]
I can't reproduce. Does it still happen if you run without extensions?

**Comment by carljohnesan** [comment]
Oh, It seems fixed by itself
