### ISSUE TITLE
HTML autoformat - inserts a space in my string ??

### ISSUE THREAD

**Issue by goltvn** [microsoft/vscode#76459]
vscode V1.35
windows 10 latest build

Got this mysterious problem and caused me massive headache :

https://i.imgur.com/QQO4lXr.gifv

when i change focus i have autosave and format on, using the standard HTML formatter but for some odd reason it adds a space into my string like this ? why ?

**Comment by aeschli** [comment]
@goltvn Can you paste a small sample code that shows the issue?
