### ISSUE TITLE
vscode is freezing when working with Node workspace

### ISSUE THREAD

**Issue by Aravindraj92** [microsoft/vscode#76451]
Hi, I have using vs code in my ubuntu 18.04, its working good when I am editing normal files but if I add npm project to the workspace and starting to edit a file then my editor get frozen not responding for any key. this issue happens only for my node projects.

**Comment by dbaeumer** [comment]
Can you please provide the trace of `code --status`. This would help to understand what component could cause this.

**Comment by Aravindraj92** [comment]
I couldn't understand what you are asking?

**Comment by dbaeumer** [comment]
When this happens can you please open a terminal and run code --status. This will print some status information to stdout. Please attach the output here.

**Comment by Aravindraj92** [comment]
[5764:0703/112143.394685:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.

Version:          Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS Version:       Linux x64 4.15.0-45-generic
CPUs:             Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 1010)
Memory (System):  3.77GB (0.10GB free)
Load (avg):       2, 5, 4
VM:               0%
Screen Reader:    no
Process Argv:     --unity-launch
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        enabled
                  webgl2:                       enabled

CPU %	Mem MB	   PID	Process
    0	    73	  3213	code main
    0	    12	  3243	   zygote
    0	   224	  3342	     window (MobHotelDetails.js - Untitled (Workspace) - Visual Studio Code)
    0	    54	  3639	       extensionHost
    0	    42	  3676	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3639
    0	   224	  4634	         electron_node tsserver.js 
    0	    69	  4644	           electron_node typingsInstaller.js typesMap.js 
    0	    31	  3652	       watcherService
    0	    54	  3364	     shared-process
    0	    46	  3321	   gpu-process

Workspace Stats:
|  Window (MobHotelDetails.js - Untitled (Workspace) - Visual Studio Code)
|    Folder (hapus): 568 files
|      File types: js(226) png(118) css(83) jpg(59) map(16) svg(10) html(10)
|                  json(7) jpeg(7) woff(4)
|      Conf files: package.json(2)

**Comment by dbaeumer** [comment]
Actually that all looks normal. Can we clone your Node project to see whether we can reproduce it?

**Comment by Aravindraj92** [comment]
Actually, I couldn't share the project due to security reasons.

**Comment by dbaeumer** [comment]
OK. Thanks. Let me know how it goes.
