### ISSUE TITLE
Tab: explore to keep close button stable when rapidly closing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7646]
Even though we have non-equal width tabs it would be nice if you could rapidly close tabs without moving the mouse.

**Comment by yisibl** [comment]
Demo
![Chrome tabs](https://img.alicdn.com/tps/TB1Kd6TKpXXXXa9XXXXXXXXXXXX-506-187.gif)

**Comment by bpasero** [comment]
@joaomoreno I actually wonder if this is also something that should go into the tabs widget because it is closely related to animations and timings. I thought about it once and could not come up with a good solution because our tabs are not even width.

**Comment by joaomoreno** [comment]
Yeah if we keep the current tab width model, this isn't possible at all.

**Comment by bpasero** [comment]
No plans of action here.
