### ISSUE TITLE
C++ syntax highlighting broken if 'class' keyword appears in function declaration

### ISSUE THREAD

**Issue by Vultraz** [microsoft/vscode#76462]
- VSCode Version: 1.35.1
- OS Version: Windows 10 1903 64 Bit

![image](https://user-images.githubusercontent.com/3558659/60509398-8359ff00-9d18-11e9-85f2-7ef3267e084c.png)

See the image above. The trailing `const` doesn't get highlighted due to the `class` keyword in the function argument.

**Comment by Colengms** [comment]
Hi @Vultraz .  This issue appears to be with the Text Mate grammar for C/C++ in VS Code.  There is an extension, "Better C++ Syntax", which appears to address this issue.  ( @jeff-hykin )

**Comment by jeff-hykin** [comment]
If that is the whole code segment, this has been fixed upstream. If you want the changes right now install the [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension.

If the code still isn't fixed after installing the extension, then there's a bug. In that case, if you could create an issue on https://github.com/jeff-hykin/cpp-textmate-grammar/issues and include all of the code for that particular file.

**Comment by alexr00** [comment]
I've also pulled in the changes from  https://github.com/jeff-hykin/cpp-textmate-grammar twice in the last week, so if you install VS Code insiders (it installs side by side with the stable release) then you can have the fix there too sometime in the next couple days.
