### ISSUE TITLE
Allow to customise IntelliSense font

### ISSUE THREAD

**Issue by kumarharsh** [microsoft/vscode#76466]
Opened as a suggestion from this issue: https://github.com/microsoft/vscode/issues/76280#issuecomment-507587535

I'm using the Iosevka font (https://typeof.net/Iosevka/) as the editor font. The full list of editor fonts is:

```
"Iosevka SS07", "Fira Code", "Source Code Pro", 'Courier New', monospace
```

Since the font was slightly slimmer than my liking, I'd set the editor font family to be **bold**. The UI elements in VSCode are in a non-configurable font (Segoe) which inherit the Editor font weight from settings, but not the font family. This creates peculiar issues on these UI elements which use Segoe instead of the configured editor font.

Some screenshots illustrating the issue:
![image](https://user-images.githubusercontent.com/760112/60419992-3b49b800-9c04-11e9-91f1-0540fcd78312.png)

![image](https://user-images.githubusercontent.com/760112/60322625-8d3cd480-999d-11e9-823c-3bccffbe23c2.png)

My suggestion is to add another setting: `UI font weight` which applies to the UI, and the `Editor font weight` applies to code elements.

**Comment by octref** [comment]
Our last release should have made the inline code font better on Windows. I don't think we would make the font more customizable. Once you add weight people would want size as well. The suggestion details widget is part of VS Code UI and VS Code should control the font.

In your snippet completion, it wasn't a code block so it didn't use the monospace font at all.
