### ISSUE TITLE
Python Interactive Window Has No Command Line.

### ISSUE THREAD

**Issue by mmhealey1** [microsoft/vscode#76464]
Steps to Reproduce:

1. Python: show Python interactive Window
2. Window loads but no command line shows i.e. it is not interactive

![interactive_window_bug](https://user-images.githubusercontent.com/52454660/60512739-57655c00-9ccd-11e9-91ea-c5d6e38e8329.PNG)

**Comment by dbaeumer** [comment]
@mmhealey1 I think this is caused by an extensions. If so, please file it there. If you have no Python extension installed, please ping.
