### ISSUE TITLE
Focus next search result (F4) should work when there is a single result and is run again

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76475]
Repro:

1. Search vscode for "interface ITerminalChild" (or any search with a single result)
2. Press F4
3. Switch to some other file
4. Press F4, nothing happens (presumably because the item is still selected in the search viewlet)

**Comment by roblourens** [comment]
I think this was fixed with https://github.com/microsoft/vscode/issues/74142 but we can verify it separately

**Comment by Tyriar** [comment]
Doesn't work still
