### ISSUE TITLE
saving files revert/change color theme on mac 10.12.6

### ISSUE THREAD

**Issue by ipstone** [microsoft/vscode#76474]
Hello, I have a similar issue with https://github.com/microsoft/vscode/issues/71695 , that when I change the color theme, somehow vscode automatically switch back to the previous theme in the user setting for workbench color theme. 

Is this a bug with some caching issues? not sure why it always try to switch back. Right after switching color theme, if I restart vscode, the the changed color theme will stay this time, but we can not change the color theme to something else (similar as before).

Thanks

**Comment by ipstone** [comment]
This behavior can be overridden, if I also set color theme in the workbench color theme setting (user workbench color theme will be overridden by the color theme set at workbench configurations). However, the color theme setting in the user setting is still not changeable - when manually changed, it will revert back on saving or some other triggers...

**Comment by aeschli** [comment]
How exactly do you change the color theme? In the settings UI, or in settings.json, or using the `Set color theme` command?
Does the workspace settings alread define a color theme?
Some screenshots of your settings and how you make the change would help....
