### ISSUE TITLE
VSCode causes Docker Desktop to hang on startup (OSX)

### ISSUE THREAD

**Issue by gregorskii** [microsoft/vscode#76473]
EDIT: On further testing it seems this was occurring when I had a VS Code window opened to my home folder. It may have had a file open in the home directory that was somehow oddly linked to Docker?

---

- VSCode Version: 1.35.1
- OS Version: Mac OSX Mojave 10.14.5

Steps to Reproduce:

1. Open VSCode
2. Open Docker

Does this issue occur when all extensions are disabled?: Yes

Result:

Docker Desktop hangs on `Docker Desktop is starting...`

Mac OSX console reports (over and over):

```
44;58H                       \^[[44;80H\^[[08;58HThis is the option     \^[[09;58Hone adjusts to change  \^[[10;58Hthe language for the   \^[[11;58Hcurrent system         \^[[12;58H                       \^[[13;58H                       \^[[14;58H                       \^[[15;58H                       \^[[16;58H                       \^[[17;58H                       \^[[18;58H                       \^[[19;58H                       \^[[20;58H                       \^[[21;58H                       \^[[22;58H                       \^[[23;58H                       \^[[24;58H                       \^[[25;58H                       \^[[26;58H                       \^[[27;58H                       \^[[28;58H                       \^[[29;58H                       \^[[30;58H                       \^[[31;58H                       \^[[32;58H                       \^[[33;58H                       \^[[34;58H                       \^[[35;58H                       \^[[36;58H                       \^[[37;58H         <…>
```

```
This is the option one adjusts to change the language for the system <…>
```

I have also seen:

```
This selection will direct the system to continue to booting process
```

Seems like some subsystem in VSCode is trying to send commands to docker as it is booting. Likely needs to wait until it is done to send these commands. Quitting VSCode, starting docker, then reopening VSCode works.

I was debugging this issue on a brand new mac with barely anything installed, then I found this comment:

https://github.com/docker/for-mac/issues/2873#issuecomment-413969899

I have repeatedly tested it, if VS Code is on Docker will not start. Without doing anything but quitting both Docker will start when VS Code is closed.

I do not have any Docker extensions installed for VS Code.

**Comment by dbaeumer** [comment]
@chrmarti although it is not remote may be you are the best to comment.

**Comment by shamill** [comment]
Can confirm I was experiencing this EXACT SAME problem.

Brand new mac, fresh Mojave install, nothing on it except installing Visual Studio code to edit my .bashrc file.

Tried to install stable release of Docker, will not start. Edge release, will not start. Cleared all caches and application files. No luck.

Stumbled across this post, decided to close Visual Studio code, now Docker starts fine.

Thank you so much, I was banging my head against the wall for 2 days trying to debug this.

**Comment by jeffxf** [comment]
Noticing it’s only causing issues when the home directory is open in VS code is a good find.

**Comment by gregorskii** [comment]
@shamill can you confirm that was the same for you?

It is working for me now.

Mac OSX does some odd things when the home folder is open for reading.

**Comment by shamill** [comment]
@gregorskii I can confirm that. I had previously run `code ~` to open up the home directory for editing.

In fact, I just replicated the issue. With VSCode open and the `~` folder opened for editing Docker will not start. I can leave VSCode running, go to File -> Close Folder, to stop editing `~`. I am then able to start Docker successfully.

**Comment by gregorskii** [comment]
Interesting. There have been a lot of posts / comments on docker due to similar issues.

I bet lots of folks had the home folder open to debug things and it was causing the issue.

I typically open the entire home folder when making dot file config changes.

**Comment by chrmarti** [comment]
Is this still an issue with the latest versions? Not sure how the two would interact.

**Comment by icirellik** [comment]
I can reproduce this issue 100% of the time by opening VSCode from within `~/Library/Containers/com.docker.docker` folder. If I close that VSCode session Docker starts just fine.

```sh
# Exit Docker Desktop

cd ~/Library/Containers/com.docker.docker
code .

# Start Docker Desktop
```

**Comment by chrmarti** [comment]
@bpasero Maybe we're holding on to some file or folder in the working dir?

**Comment by bpasero** [comment]
@icirellik are you only starting VSCode from there or also opening the folder within VSCode?

**Comment by icirellik** [comment]
I'm opening the folder, I first ran into this issue when I was updating my local dotfiles and opened `~/` in VSCode and noticed that Docker Desktop would no longer start as long that folder was open in VSCode.

I was doing some additional testing to make sure that my extensions were not causing the issue.

Steps:

1. Exit VSCode
2. Exit Docker Desktop
3. Open home folder in VSCode: `cd ~/ && code --disable-extensions .`
4. Start Docker Desktop (sometimes will work the first time)
5. Exit Docker Desktop
6. Leaving VSCode open, start Docker Desktop again.

It always hangs on step 6. 

I haven't had much time to look into the issue. I know the docker vm lives in `~/Library/Containers/com.docker.docker/Data/vms` and contains several different sockets along with a tty that can be connected to using the following command:

```sh
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
```

It could be that VSCode is holding a file handle to one of those files preventing the vm from properly recreating them when docker is restarted.

**Comment by bpasero** [comment]
@icirellik maybe it is our file watcher holding onto something, for that we have a setting to exclude folders, e.g. if you configure:

```json
"files.watcherExclude": {
	"**/.git/objects/**": true,
	"**/.git/subtree-cache/**": true,
	"**/node_modules/**": true,
	"**/com.docker.docker/**": true
}
```

Does it still reproduce?

**Comment by icirellik** [comment]
I did some more testing and the results lead me to believe that the file globs are also misbehaving.

Path | Exclude Used | Before Opening VSCode | Start Attempt 1 | Start Attempt 2 | After VSCode Closed
-- | -- | -- | -- | -- | --
~/ | no | loads | hangs | hangs | loads
~/ | yes | loads | hangs | hangs | loads
~/Library/Containers/com.docker.docker/ | no | loads | hangs | hangs | loads
~/Library/Containers/com.docker.docker/ | yes | loads | loads | loads | loads
~/code | no | loads | loads | loads | loads

**Comment by bpasero** [comment]
@icirellik I think at this point to continue the investigation someone from Docker needs to comment why it would not start. I think us trying to diagnose Docker is not correct. I will close this issue until we heard back from them that the culprit is something VSCode does wrong and then hopefully we can investigate further.
