### ISSUE TITLE
lost of sync with git

### ISSUE THREAD

**Issue by BlueTeo91** [microsoft/vscode#76471]
Issue Type: <b>Performance Issue</b>

The project loose the sync with the git repository. To solve the problem I have to disable->restart->enable the @builtin git. The problem appears randomly

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   123	 14408	code main
    1	    61	  6668	   window (Issue Reporter)
    0	    38	 11004	   shared-process
    0	   199	 16924	   window (PHY_abstraction_SERIAL.m - esim2m - Visual Studio Code)
    0	    23	 12040	     extensionHost
    0	     4	 12820	     watcherService 
    0	     1	 12144	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (PHY_abstraction_SERIAL.m - esim2m - Visual Studio Code)
|    Folder (esim2m): 2426 files
|      File types: png(1299) mat(620) fig(155) txt(112) m(94) pdf(28) eps(13)
|                  mexw64(12) ant(12) xlsx(10)
|      Conf files:;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-formatter|Aff|2.4.12
Bookmarks|ale|10.4.4
notes|can|0.9.3
matlab|Gim|1.1.0
latex-workshop|Jam|7.0.2
matlab-snippets|sky|1.11.0
matlab-complete|sla|1.0.2
markdown-all-in-one|yzh|2.4.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> The project loose the sync with the git repository.

Can you explain what this means? Maybe screenshot? Screen recording?

**Comment by BlueTeo91** [comment]
Apparently with the last VSCode update of today (1.36.0) the problem doesn't show up anymore
