### ISSUE TITLE
Show full type in typescript type hover hint

### ISSUE THREAD

**Issue by fantapop** [microsoft/vscode#76480]
When hovering over a Union type with a lot of options, some of the types are not shown.  As far as I can tell there is no way to "view all" or "view more".  Having this functionality would be very helpful.

![Screenshot from 2019-07-02 10-54-37](https://user-images.githubusercontent.com/6658984/60536060-5c6ce000-9cba-11e9-99dd-d41fa9b9f3d7.png)

**Comment by mjbvz** [comment]
Duplicate of #64566
