### ISSUE TITLE
Wrong input box color in dark theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7648]
In light theme for input boxes we use the same background color as the one used for editor, however in dark theme that is not the case.
This becomes particularly visible when tabs are enabled as the quick open input has the same color as the empty after the tabs - looks confusing and this is the main reason why tabs visually look much better in the light theme than in the dark theme imho.

I can look into changing all the input box background colors but it is a big change and it requires UX blessing - so we can discuss it today in the ux meeting.

fyi @bpasero 

![screen shot 2016-06-14 at 11 41 58](https://cloud.githubusercontent.com/assets/1926584/16038481/65d2cff4-3225-11e6-95ef-4299dde5411b.png)

**Comment by bpasero** [comment]
+1 for making all inputs the same colour as the editor.

/cc @jrieken @alexandrudima for owners of input fields in the editor (find, rename).

**Comment by isidorn** [comment]
Assigning to @bgashler1 to experiment with colors as we have agreed on our UX meeting and if we come to a conclusion give the issue back to me to implement it across vscode.

**Comment by stevencl** [comment]
We discussed and agreed that we should look at the colours used throughout the product now that we have tabs enabled. @bgashler1 - this is something you and I should talk about.

**Comment by bgashler1** [comment]
While Steven and I collaborate on holistically evaluating our colors, iconography, etc, I think the change in this PR #8238 may dampen the problem somewhat.  You'll notice that the tab well is now the same color as the viewlet which—aside from being more hierarchically correct color-wise—has the benefit of being less confusing with the command palette's input box.

<img width="784" alt="screen shot 2016-06-27 at 9 51 13 pm" src="https://cloud.githubusercontent.com/assets/11839736/16404220/da83acec-3cb1-11e6-958b-a8ffbf0abb42.png">

I'll move this to the backlog for now and we can keep this on our radar.
