### ISSUE TITLE
Settings.json is not showing default settings after update

### ISSUE THREAD

**Issue by Devloper-King** [microsoft/vscode#76485]
- VSCode Version:Version: 1.35.1 (user setup)
- OS Version: Windows_NT ia32 6.1.7601

![Capture](https://user-images.githubusercontent.com/46634323/60550855-30e60600-9d4b-11e9-9c67-eef0c9559189.PNG)
 After update Settings.json is showing my settings not the default settings where in previous version in vscode the defualt settings were shown in the side.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/68386#issuecomment-462247156
