### ISSUE TITLE
property name posits: is underlined and clickable

### ISSUE THREAD

**Issue by tommulkins** [microsoft/vscode#76486]
Anywhere I place the characters `posits:` VSCode will make it a link.  

![image](https://user-images.githubusercontent.com/11251283/60551090-251d2400-9cf8-11e9-8e4e-305d680aef39.png)

I couldn't find a mention that `posits:` would behave in this fashion.

**Comment by dbaeumer** [comment]
@tommulkins does this happen if you disable all installed extensions. You can start code from a terminal with `--disable-extensions`

**Comment by tommulkins** [comment]
@dbaeumer It must be an extension causing that somewhere.  Thanks!  Now off to chase down which one 🤔
