### ISSUE TITLE
With "Indent Using Spaces" TAB key inserts spaces even in middle of line

### ISSUE THREAD

**Issue by Mingun** [microsoft/vscode#76499]
- VSCode Version:  1.35.1
- OS Version: Linux x64 4.4.0-151-generic

Menu **About**:
```
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.4.0-151-generic
```

Steps to Reproduce:
-------------------------
This bug already will be reported as #30692, but it was closed without eliminating problem. Error is not just configuration problem -- the editor works in defiance of expectations.

1. When I press TAB and there is no non-(spaces or tab) characters from begin of line, configured characters for intent must be inserted. This part works as expected
2. When I press TAB and there exists characters, other than space or tab between start of line and insertion point, TAB must be inserted irrespective of setup of indents -- this is not an indent!

Does this issue occur when all extensions are disabled?: **Yes**
![Tab behaviour](https://user-images.githubusercontent.com/450131/60564256-6b19cc80-9d78-11e9-8cbb-c2a7c02d669f.png)

**Comment by autinerd** [comment]
Yep, this is annoying, you have to open another editor with tabs enabled and copy the tab character from there and paste it.

**Comment by alexandrudima** [comment]
I have tried also SublimeText and when configured to indent using spaces, pressing <kbd>Tab</kbd> always inserts spaces also in that editor, so I think our behavior is reasonable and aligns with expectations set forth by other editors. IIRC I believe this is also the behavior of Visual Studio.

One possible workaround could be to bind a keybinding for inserting a tab character, e.g.:

```
{ "key": "ctrl+tab", "command": "type", "args": { "text": "\t" }, "when": "editorTextFocus" },
```

**Comment by Mingun** [comment]
Yes, just now check that in editor from 200x (SciTE), it working the same way. So you solution with new keybinding is sufficient
