### ISSUE TITLE
Manual collect garbage feature

### ISSUE THREAD

**Issue by nico-abram** [microsoft/vscode#76498]
I'm opening 3 files with about 100k lines each. These files are getting completely rewritten often. After a couple minutes of developing, vscode starts to consume huge amounts of memory. What I usually do is reload the window, but that means resetting the terminal, and the WIP open files. It'd be nice to have a way to manually collect garbage/caches (I'm assuming the issue is because vscode is keeping some kind of cache/history of changes to these 100k line files).

**Comment by dbaeumer** [comment]
@nico-abram can you provide us with a test case or GitHub repository we can clone that demos this. This sounds like a leak which shouldn't happen. 

@jrieken do we have any instructions to take a heap snapshot to see what we leak?

**Comment by nico-abram** [comment]
Sure! Here, this repo has a test case with instructions in the readme: https://github.com/nico-abram/vscode-leak-test
My use case is I'm writing an emulator, outputting the cpu status on every instruction executed, and diffing against a log from a pre-existing emulator (Keeping all three files open, mostly looking at the diff file and occasionally switching to the real logs when requiring more context)

**Comment by rebornix** [comment]
@nico-abram can you please open Developer Tools and open Memory tab to record a heap snapshot and share with us?
