### ISSUE TITLE
Bad experience when installing extension that has updates that aren't compatible with this version of vscode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#76491]
![Jul-02-2019 18-01-16](https://user-images.githubusercontent.com/323878/60555868-93131c80-9cf3-11e9-9408-a845ef968e6b.gif)

This is what you see when installing the Remote Containers extension in stable vscode 1.35. It always offers to update to 0.66, which is only compatible with 1.36, and if I click the button, I just get the prompt again and it looks broken.

**Comment by sandy081** [comment]
Can no longer repro with latest stable.

**Comment by roblourens** [comment]
Well yeah now the Containers extension's engine matches the latest stable. When they bump the engine to 1.37 or something else I would guess it would do this again.

**Comment by sandy081** [comment]
I cant repro it on latest stable when the extension's latest is not compatible. See the following video.

![Kapture 2019-07-12 at 15 07 56](https://user-images.githubusercontent.com/10746682/61130402-e2590a00-a4b6-11e9-96a4-f2d7002f9a8c.gif)

I mimicked it on latest stable by changing its version in `package.json`.

**Comment by roblourens** [comment]
I think the latest is compatible, the engine is 1.36
