### ISSUE TITLE
Find widget does not blend well when tabs enabled

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7649]
IMHO the find widget does not visually blend well when tabs are enabled
Two similar gray colors and no seperation between them does not look good to me.

Just my 2 cents so feel free to close

![screen shot 2016-06-14 at 11 52 28](https://cloud.githubusercontent.com/assets/1926584/16038735/c96b8384-3226-11e6-928a-cc8b32627301.png)

**Comment by bpasero** [comment]
I took the following color rule for the tabs container background: `rgba(128, 128, 128, 0.2)`

(this is the same as the color we use for split views header, e.g. in debug viewlet).

**Comment by isidorn** [comment]
I am not arguing against that color just not sure if there should be some spearation between the find widget and the header.

**Comment by stevencl** [comment]
Here's what it looks like using the same colour as the selection colour in the explorer:

**Comment by stevencl** [comment]
I am not sure about adding another separator if the contrasting colour works better?

**Comment by stevencl** [comment]
We discussed and agreed that we should look at the colours used throughout the product now that we have tabs enabled. @bgashler1 - this is something you and I should talk about.

**Comment by bgashler1** [comment]
Agreed.  Steven and I will be meeting next week to discuss.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8564
