### ISSUE TITLE
Salesforce retrieval through generated package.xml retrieves part of the file

### ISSUE THREAD

**Issue by cbsp101** [microsoft/vscode#76497]
On VSCode, when tried to retrieve profiles from a salesforce org, 2 issues are encountered:

Issue 1: when retrieved the profiles via sfdx Package.xml generator:Choose metadata components around 300+ lines of the file were missing from the retrieved file

Issue 2: The sequence of code lines are changed while retrieve from Salesforce sandbox

**Comment by gjsjohnmurray** [comment]
I suggest you raise this issue with the developers of the extension(s) you are using to do Salesforce development in VSCode.

**Comment by cbsp101** [comment]
Thanks John for prompt reply. Will raise it with the developers of extension. Raised https://github.com/vignaesh01/sfdx-package-generator/issues/10

**Comment by dbaeumer** [comment]
Closing the issue then. @gjsjohnmurray thanks for pointing @cbsp101 to the right location.
