### ISSUE TITLE
Way to author snippets with code

### ISSUE THREAD

**Issue by reggi** [microsoft/vscode#76501]
I'd love to be able to do something like this, and be able to generate a snippet with typescript itself.

```ts
import { uppercase } from 'lodash'
import { snippet } from 'vscode-snippet'

export const newRelation = snippet`
@ManyToOne(type => ${i => i[1]}, { nullable: false }),
@JoinColumn(),
${i => i[2]}: ${i => uppercase(i[2])}

@RelationId((${i => i[2]}: ${i => uppercase(i[2])}) => ${i => i[2]}.${i => i[1]}),
${i => i[1]}Id: number;,
`
```

I tried looking I don't think anything like this exists.

**Comment by jrieken** [comment]
This is a cool idea! However, given our current plans I don't see that happening within the near future and I would encourage you to create a standalone project for this. VS Code uses TextMate-snippets which are also used in TextMate, SublimeText, and others and your idea would apply to them as well.
