### ISSUE TITLE
[REGEX] Non fixed-length lookbehind support

### ISSUE THREAD

**Issue by jerryc05** [microsoft/vscode#76502]
I am writing a extension for language syntax highlighting, and I would like to use non fixed-length lookbehind regex like `(?<=void[ \t]+)\w+` to highlight function name, but it does not work. However, fixed-length lookbehind works. Is there any way to fix this, or any workarounds? Thx.

**Comment by dbaeumer** [comment]
@aeschli @alexandrudima since this is TextMate, any idea.

**Comment by jerryc05** [comment]
Okay one possible solution is to move `[ \t]+` out of the lookbehind block, and that worked fine.

But what if there are more modifiers like `public void funcNameToCatch()`?

**Comment by aeschli** [comment]
TextMate Grammars use Oniguruma as RegExp engine. The [spec](https://github.com/stedolan/jq/wiki/Docs-for-Oniguruma-Regular-Expressions-(RE.txt)) there says:
```
Subexp of look-behind must be fixed character length.
                     But different character length is allowed in top level
                     alternatives only.
                     ex. (?<=a|bc) is OK. (?<=aaa(?:b|cd)) is not allowed.
```
