### ISSUE TITLE
deleteFile keyboard shortcut adds the word 'Delete' to the explorer

### ISSUE THREAD

**Issue by DanielSharp01** [microsoft/vscode#76514]
Issue Type: <b>Bug</b>

So far when delete was pressed it deleted the file in the explorer, not it just adds the word Delete in capital letters to the file search,

VS Code version: Code - Insiders 1.36.0-insider (b7ca272b6e041e42f9edfe48f4d559c2044cdaae, 2019-07-02T12:07:21.186Z)
OS version: Linux x64 4.18.0-25-generic snap

**Comment by isidorn** [comment]
Can you please post a video showing this?
You can F1 > toggle screen cast mode and then record so we see what keys get pressed?

I do not have a keyboard with the delete key thus I can not test this atm

**Comment by DanielSharp01** [comment]
I do not have any custom key bindings. I'll post a video later about the issue.

**Comment by isidorn** [comment]
Thanks

**Comment by renanhangai** [comment]
It happened to me as well

Version: 1.36.0
Commit: 0f3794b3847
OS: Linux x64 4.15.0-54-generic

![Delete](https://user-images.githubusercontent.com/1877289/60622150-f82f4680-9db5-11e9-9b6b-c3ce2828fdee.gif)

**Comment by tkvw** [comment]
Same issue here

**Comment by sabariramc** [comment]
Same issue

```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-15-generic
```

**Comment by isidorn** [comment]
@joaomoreno the tree seems to be eating up the Delete key. I can not repro on win. But I can repro on Linux. This is a recent change in the past week.
It seems like something changed in the last release, since users did not hit this before.
Did we change something in how the tree handles the delete key?

Adding candidate since this is a regression.

**Comment by joaomoreno** [comment]
@jrieken Ooops.

**Comment by joaomoreno** [comment]
Yep, definitely reproducible.

Broken by https://github.com/microsoft/vscode/commit/382e1a0289a16d62be04ff9ec4a1b40f297c9637, related to https://github.com/microsoft/vscode/issues/74934

**Workaround:** use the context menu for now.

**Comment by jrieken** [comment]
We have logic to know whether a key press results in a printable character or not, e.g on most keyboard `KEY_F` prints `f`, `SHIFT+KEY_F` prints `F`, `ESC` prints nothing etc. To know if the tree should start filtering or not we run this logic and it seems broken on linux, thinking that `KEY_Delete` prints `delete`, e.g. in a text field.

**Comment by jrieken** [comment]
Talked to @alexandrudima, seems we have some utils for this: https://github.com/microsoft/vscode/blob/7980cd2697482e14a1f2ea9a8a36c064aebc180b/src/vs/base/common/scanCode.ts#L223

**Comment by Manviel** [comment]
Same issue!

**Comment by ilyarudnitsky** [comment]
Same issue!

Fix please!

**Comment by srfrnk** [comment]
Seems like this should've been fixed in 1.36.0 am I wrong?

If so - still happens to me:
```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic
```

**Comment by jurosh** [comment]
@srfrnk it was reported for `1.36.0`, so fix will likely be included in the next minor release. https://github.com/microsoft/vscode/milestone/99

**Comment by srfrnk** [comment]
@jurosh Thanks for the info.
I thought since [commit 76608](https://github.com/microsoft/vscode/pull/76608) was merged into [release 1.36](https://github.com/microsoft/vscode/tree/release/1.36) - this meant it was included in 1.36.
My bad.

**Comment by mirao** [comment]
**Workaround:** Disable the setting `workbench.list.automaticKeyboardNavigation`

**Comment by srfrnk** [comment]
> Another **workaround:** Disable the setting `workbench.list.automaticKeyboardNavigation`

Thx @mirao - that helps!

**Comment by frederikheld** [comment]
You are awesome folks! I had this issue with 1.36 only on Ubuntu, not on Windows. But both hat exactly the same settings for key bindings. It drove me nuts :-P Thank you so much for fixing and deploying it so quickly!
