### ISSUE TITLE
MacOS: Terminal integration tests are broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76515]
This is off master:

![image](https://user-images.githubusercontent.com/22350/60593254-a6c98c00-9da2-11e9-9013-ad631a110f02.png)

**Comment by Tyriar** [comment]
I can't repro the failures locally, I do see some exceptions being thrown in successful tests though which I'll fix now.

**Comment by Tyriar** [comment]
Fixed that error, queuing a build now to see if it passes as I still can't repro locally.

**Comment by Tyriar** [comment]
Looks like https://github.com/microsoft/vscode/commit/112a60d637fc7df10c0bf8b5b3a74bb9aeb6f203 fixed it, terminals were "leaking" across tests which causes race conditions in the terminal API events.

**Comment by Tyriar** [comment]
Disabling so the build succeeds, will continue investigation tomorrow.

**Comment by joaomoreno** [comment]
@Tyriar Is this still an issue?
