### ISSUE TITLE
Implement resolveTask in grunt extension

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#76518]
See gulp extension change https://github.com/microsoft/vscode/commit/b6089b1db51dbfb7b096a829261a0b3b9370d6e5

**Comment by peacemaker14** [comment]
i'm going to work on this issue

**Comment by peacemaker14** [comment]
#76731

**Comment by peacemaker14** [comment]
#76731

**Comment by alexr00** [comment]
Thank you @peacemaker14!
