### ISSUE TITLE
Option to hide/disable "Commit all ..."

### ISSUE THREAD

**Issue by ADIX7** [microsoft/vscode#76510]
It would be great if one could disable "Commit all..." options on the Version Control (I use git) tab under the "More Actions...". Something like "git.disableCommitAll".

**Comment by ADIX7** [comment]
No, dear bot, this is an other issue.

**Comment by joaomoreno** [comment]
Why?

**Comment by ADIX7** [comment]
I don't use it, I stage things before I commit, it's a safety step. But if I accidentally press Commit All instead Commit Staged I have to undo the commit. Usually it's not a hard thing to do but if it is amend... Well, good luck... Just because there is a button (3 actually) that does something I don't even need.
So in my opinion Commit All is not a safe solution. It is convenient but I prefer the safer Commit Staged option. For me Commit All is a time bomb, and I guess I'm not alone.

**Comment by joaomoreno** [comment]
Given that `Undo Commit` is there, there's an easy and safe way to undo a misclick. There's no data loss at all. Closing this.

**Comment by ADIX7** [comment]
Actually 'Undo Commit' does not restore state if one did 'Commit All (Amend)'. When you do Undo Commit after amend you just undo the rebase commit but you don't get back the commit reseted by rebase (amend). So if you are at
`A -> B ->Staged+Unstaged` and you do an amed all you get `A -> B'` while 'amend staged' would give you `A -> B' -> Unstaged`. If you do 'Undo Commit' on `A -> B` you will get `A ->B+Staged+Unstaged` but `B+Staged+Unstaged` all will be in the index ('merged'). So you have to recreate B+Staged (or B) what would be the originally wanted amended state. If a file has changed in B, Staged and Unstaged recreating these states can be frustrating.
