### ISSUE TITLE
RANDOM Graphical Glitches

### ISSUE THREAD

**Issue by vintzl** [microsoft/vscode#76513]
- VSCode Version: 1.35.1 + 1.36.0
- OS Version: Debian Stable amd64

Steps to Reproduce:

1. UNKNOWN

Does this issue occur when all extensions are disabled?: Yes/No
UNKNOWN

![Screenshot at 2019-06-27 14-48-36](https://user-images.githubusercontent.com/44751088/60586254-36f6d980-9d81-11e9-9417-1a9b1abd7456.png)

**Comment by rebornix** [comment]
@vintzl could you please provide more info about how to reproduce this issue? For example, the language you are working on, how often do you run into the issue, how did you recover from that, etc.

**Comment by vintzl** [comment]
C# is the language.
Well, after hours of work, I can see this glitches.
To recover from that, I have to restart VSCode.

**Comment by alexandrudima** [comment]
It looks like the content widgets of codelens are out of sync with the view zones

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/71745
