### ISSUE TITLE
PHP template auto indent inaccurate

### ISSUE THREAD

**Issue by TomS-** [microsoft/vscode#76517]
- VSCode Version: 1.35.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create a PHP template file with HTML and PHP used together
2. Auto indent doesn't consistently work and becomes really inaccurate

Does this issue occur when all extensions are disabled?: Yes

Example: 
https://twitter.com/Tom_Smedley/status/1144595828625018880

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/62077
