### ISSUE TITLE
Moving Lines in C# does not change indentation

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#76511]
Issue Type: <b>Bug</b>

In a C# file, using the Move Line Up/Down key combination (Option-Up arrow on Mac), moves the line, but does not change the indentation, if the line moves into another code block (if { } for example. It stays at the same level it started at.

The same command on a Typescript file cause the indentation to work as expected.

VS Code version: Code - Insiders 1.36.0-insider (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T08:01:27.575Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (4.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
ng-template|Ang|0.800.0
path-intellisense|chr|1.4.2
githistory|don|0.4.6
auto-rename-tag|for|0.1.0
Angular2|joh|8.1.1
csharp|ms-|1.20.0
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.7

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Not really the same.

**Comment by rebornix** [comment]
Our auto indentation is based on regex rules while it is not fully aware of the context/scope and it also doesn’t support different indentation formats. By that it means it's hard to make a perfect indentation rules builtin in VS Code. It would be great if language extensions can take care of that.
