### ISSUE TITLE
Implement resolveTask in jake extension

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#76519]
See gulp extension change b6089b1

**Comment by hwhung0111** [comment]
I'm willing to give it a try.

**Comment by alexr00** [comment]
Thanks @hwhung0111! It should be very similar to the change in the gulp extensions.

**Comment by hwhung0111** [comment]
@alexr00 Yes, it's very similar. I copy the different part to jake extension and make a little change to fit jake extension.
