### ISSUE TITLE
VSCode hangs on macOS; cannot be shut down

### ISSUE THREAD

**Issue by RichMorin** [microsoft/vscode#76529]
- VSCode Version: 1.35.1 
- OS Version: macOS 10.13.6 (High Sierra)

Steps to Reproduce:

This problem has only occurred once so far. I don't expect the following steps to reproduce the problem, but here is what transpired.

1. I started VSCode, opened a tree of several thousand files, and did a file search.
2. I went to some other apps, closed and re-opened the laptop, etc.
3. I came back to VSCode and got a spinning pizza of death.
4. After waiting for a few minutes, I did a cmd-opt-esc.
5. VSCode was "not responding", so I killed it.

The VSCode window should have disappeared at this point, but it did not. I finally resorted to restarting the machine.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by RichMorin** [comment]
None of the User Reports I found in the Console begin with Code, but that
may have to do with the fact that VSCode locked up and I had to kill it
and then restart the computer.  In any case, I've enclosed a report that
_might_ be related.

-r

**Comment by bpasero** [comment]
Ok closing until we have further info.
