### ISSUE TITLE
Attaching second monitor makes terminal go blurry

### ISSUE THREAD

**Issue by tehcyx** [microsoft/vscode#76523]
I've seen some issues reporting the same thing, but they all seem to have a platform specific workaround and are targeted for windows. Since I'm on mac, I'd assume a new issue would do, if not please link it.
![image](https://user-images.githubusercontent.com/917785/60597514-e9b64000-9d5f-11e9-9708-7ff75f34aabe.png)

As you might be able to tell, the above terminal content is blurry, and it only is fixed, if I resize the window (assuming to cause a new render call).

I do not know, if the problem came with me switching to zsh or with a newer version of vscode, since I regularly update when prompted.

- VSCode Version: 1.35.1
- OS Version: MacOS 10.14.5

Steps to Reproduce:

1. Open VSCode and a terminal
2. Enter some commands in Terminal
3. Plug-in second monitor

**Comment by Tyriar** [comment]
Related: https://github.com/xtermjs/xterm.js/issues/2137

**Comment by Tyriar** [comment]
Let's track upstream.
