### ISSUE TITLE
Could not establish SSH connection to remote using Remote - SSH

### ISSUE THREAD

**Issue by arglog** [microsoft/vscode#76534]
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

I failed to connect a remote machine using the Remote-SSH extension in VS Code stable. Below is the error message
```
remote-ssh@0.44.0
win32 x64
SSH Resolver called for "ssh-remote+xxxx.yyyy.zzz", attempt 1
SSH Resolver called for host: xxxx.yyyy.zzz
Setting up SSH remote "xxxx.yyyy.zzz"
Using commit id "0f3794b38477eea13fb47fbe15a42798e6129338" and quality "stable" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
Install and start server if needed
> 
> ]0;C:\WINDOWS\SYSTEM32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> flock: 
> flock: Installation already in progress...
> b38ddf8b-a292-464a-a9b3-2c14f32418f3##24##
> 99: Input/output error
> flock: 99: Input/output error
> 
"install" terminal command done
Received install output: flock: 99: Input/output error
Failed to parse remote port from server output: flock: 99: Input/output error
```

**Comment by roblourens** [comment]
What file system are you on, is it a network drive?

Can you try running the command "Uninstall VS Code Server from Host" and trying again?

**Comment by arglog** [comment]
@roblourens 
The file system is NFS4. I've tried "Uninstall VS Code Server from Host" and SSH again but have the same error. 

P.S. I was able to SSH normally using VS Code + Remote-SSH in the past few weeks but got this error since yesterday. I've tried several different local machines to connect to the same remote machine -- all have this error.

**Comment by saeedizadi** [comment]
I have the same problem since yesterday

**Comment by svenkata9** [comment]
I have the same problem since an hour - after updating the latest update

**Comment by epleone** [comment]
@roblourens 
Updated to version 1.36，I have the same problem

**Comment by saeedizadi** [comment]
That's really inconvenient that we are experiencing such an error since last week. I have been a big fan of VSCode and migrated from PyCharm to VSCode recently, but this problem is pushing me to go back to PyCharm.

**Comment by epleone** [comment]
Hi all, This is my solution:
Open CMD with Windows+R shortcut, then open the properties and uncheck the old version of the console.

**Comment by arglog** [comment]
@epleone Thanks for sharing this. But on my laptop, the old version CMD has already been unchecked before the SSH-remote issue appears.

**Comment by svenkata9** [comment]
Same here. It is already unchecked.

**Comment by DickyT** [comment]
@arglog @svenkata9 Try to `rm -rf ~/.vscode*` and reboot your container/vm/server, this works for me

**Comment by svenkata9** [comment]
Thanks. It works only on one instance (first instance). And, from next time on, we will need to repeat the same rm  -rf and reboot. Pain really!

**Comment by arglog** [comment]
@svenkata9 @DickyT For me, it even doesn't work for the first try.

@DickyT Are you also using the NFS file system?

**Comment by DickyT** [comment]
@svenkata9 Yes, for now I can also only get one instance working. One of the previous nightly build have the same problem, and they fixed it next day. Not sure what is causing this error.

**Comment by DickyT** [comment]
@arglog I am running the GUI VSCode on a Windows 10 machine, and the remote side which running `vscode-server` is a Hyper-V ubuntu VM.

**Comment by roblourens** [comment]
Looks to be the same as https://github.com/microsoft/vscode-remote-release/issues/885
