### ISSUE TITLE
Native Sierra-tabs are not working in macOS 10.12.x

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#76537]
- VSCode Version: V1.36.0 (1.36.0) and higher
- OS Version: macOS 10.12(.0-6)

Steps to Reproduce:

1. Download latest release
2. Try to use Sierra tab feature

Note: _Insiders build already does not work on Sierra_
Note 2: _This feature works only for High Sierra and Mojave_
Note 3: _Can this feature be added to without OS specific? i.e. for Windows users and/or for El Capitan users?_
Note 4: _Upgrading to Mojave isn't solution as Mojave not available to all users_

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@dalisoft are you saying that in VSCode `1.35` you could use native tabs on macOS Sierra (`10.12.x`) and now you need at least High Sierra (`10.13.x`) to use them?

**Comment by dalisoft** [comment]
@bpasero Only v1.35 worked for me (Sierra tab feature), before and last release works only in v10.13+ (old releases worked only 10.13+, i did not test latest release on 10.13+)

**Comment by bpasero** [comment]
@dalisoft that is weird, are you saying `v1.34` also did NOT support native tabs on macOS Sierra `10.12.x`? 

We did an Electron update for `1.36`, but I would be surprised if there is something that changed between `1.34` and `1.35` that could cause this.

**Comment by dalisoft** [comment]
Yes, v1.34 also did not worked. Insiders build also does not support native tabs, even it has fullscreen black space bug

**Comment by bpasero** [comment]
@dalisoft how exactly do you see that it is not working, does it partially work or not at all. Can you share your settings file?

**Comment by dalisoft** [comment]
It's not works at all

```
{
  "breadcrumbs.enabled": false,
  "extensions.autoUpdate": true,
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.editor.highlightModifiedTabs": true,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.editor.enablePreview": false,
  "workbench.settings.enableNaturalLanguageSearch": false,
  "editor.wordWrap": "bounded",
  "editor.scrollBeyondLastLine": false,
  "editor.scrollBeyondLastColumn": 0,
  "editor.renderWhitespace": "all",
  "editor.cursorBlinking": "solid",
  "editor.cursorSmoothCaretAnimation": false,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": false,
  "editor.formatOnType": false,
  "editor.minimap.enabled": false,
  "editor.minimap.renderCharacters": false,
  "editor.minimap.maxColumn": 200,
  "editor.minimap.showSlider": "always",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.fontFamily": "Monaco, Menlo, Consolas, 'Courier New', monospace",
  "editor.fontSize": 12,
  "editor.smoothScrolling": true,
  "editor.suggestSelection": "first",
  "editor.fontWeight": "100",
  "diffEditor.ignoreTrimWhitespace": false,
  "window.zoomLevel": 0,
  "window.title": "${dirty} ${activeEditorMedium}${separator}${rootName}",
  "window.nativeFullScreen": false,
  "window.nativeTabs": true,
  "javascript.validate.enable": false,
  "javascript.format.enable": false,
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "javascript.implicitProjectConfig.checkJs": true,
  "javascript.format.insertSpaceAfterSemicolonInForStatements": false,
  "javascript.suggest.autoImports": false,
  "typescript.validate.enable": false,
  "typescript.format.enable": false,
  "typescript.implementationsCodeLens.enabled": true,
  "typescript.referencesCodeLens.enabled": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "explorer.confirmDelete": false,
  "explorer.confirmDragAndDrop": false,
  "explorer.openEditors.visible": 0,
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true,
    "**/dist/**": true,
    "**/build/**": true,
    "**/.cache/**": true,
    "**/.webpack/**": true
  },
  "files.autoSave": "onWindowChange",
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.associations": {
    "*.js": "javascriptreact",
    "*.ts": "typescriptreact",
    "*.css": "postcss"
  },
  "eslint.autoFixOnSave": true,
  "eslint.runtime": "/usr/local/bin/node",
  "eslint.validate": [
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "javascript",
      "autoFix": true
    },
    {
      "language": "javascriptreact",
      "autoFix": true
    }
  ],
  "prettier.stylelintIntegration": true,
  "prettier.printWidth": 80,
  "prettier.jsxBracketSameLine": true,
  "prettier.arrowParens": "avoid",
  "prettier.eslintIntegration": true,
  "prettier.tslintIntegration": true,
  "prettier.requireConfig": false,
  "stylelint.enable": true,
  "emmet.includeLanguages": {
    "postcss": "css",
    "javascript": "javascriptreact"
  },
  "emmet.syntaxProfiles": {
    "postcss": "css"
  },
  "postcssSorting.config": {
    "order": [
      "custom-properties",
      "dollar-variables",
      "declarations",
      "at-rules",
      "rules"
    ],
    "properties-order": [
      "display",
      "position",
      "top",
      "right",
      "bottom",
      "left"
    ]
  },
  "sync.gist": "GIST_ID",
  "sync.autoUpload": false,
  "sync.autoDownload": false,
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "terminal.explorerKind": "external",
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
  // "terminal.integrated.shellArgs.windows": ["~"],
  "search.exclude": {
    "**/.cache": true,
    "**/.out": true,
    "**/build": true,
    "**/dist": true
  },
  "markdown.preview.fontFamily": "-apple-syLight BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', 'Ubuntu', 'Droid Sans', sans-serif",
  "workbench.editor.closeOnFileDelete": true,
  "workbench.colorTheme": "Oceanic Plus",
  "typescript.experimental.useSeparateSyntaxServer": true,
  "update.mode": "none",
  "update.enableWindowsBackgroundUpdates": false,
  "workbench.statusBar.feedback.visible": false
}
```

**Comment by bpasero** [comment]
@dalisoft ok I am sorry to hear that but I cannot tell why it fails for you :-(

**Comment by dalisoft** [comment]
Thanks. Lets wait for fix

**Comment by christianztamayo** [comment]
Setting for `window.nativeFullScreen` seems to have disappeared as well

**Comment by Platzii** [comment]
Having the same issue.
Running macOS Sierra (1.12.x), before VSCode 1.36.0 native window tabbing worked after update they did not anymore.

**Comment by bpasero** [comment]
Given the comment in https://github.com/microsoft/vscode/issues/77047 I think this is another Electron 4 related regression.

//cc @deepak1556

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by crabicode** [comment]
@bpasero, I have just tested macOS `code-exploration`. The issue is still present.

```
Version: 1.37.0-exploration
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:05:44.909Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Darwin x64 16.7.0
```

**Comment by Platzii** [comment]
@bpasero, I can confirm the issue still persists with the exploration build

By the way:
In order to reproduce, you must set "Prefer tabs when opening documents" to "Always" in System Preferences > Dock

<img width="690" alt="Screen Shot 2019-07-10 at 15 47 37" src="https://user-images.githubusercontent.com/7767841/60974461-692cac00-a32a-11e9-993d-e415169aa827.png">

**Comment by crabicode** [comment]
Good day everyone,

The issue has not been resolved yet. Unfortunately, it forces me to downgrade to v1.35 every time it automatically updates to v1.36.

Is there an investigation or any update?

**Comment by dalisoft** [comment]
@crabicode Hi!
1. You can disable auto-update from Settings.
2. I updated to Mojave (latest update) and performance was improved, these bugs are fixed and memory usage was reduced to **1.5** times which is huge as i'm using old macBook with 8Gb memory

**Comment by crabicode** [comment]
@dalisoft,

I was reluctant to upgrade to Mojave because vscode could not open projects in the same window. Could you confirm vscode opens projects in native tabs in Mojave?

Thank you very much!

**Comment by dalisoft** [comment]
Yes, opens in native tabs. Performance was improved, reduced CPU and memory usage. I very happy with upgrade. But, note, only 10.14 latest version is best works.

**Comment by dalisoft** [comment]
Hi everyone :)

I can confirm, last three updates also does not fix this issue on macOS Sierra (back to Sierra from Mojave :smile:)

**Comment by dalisoft** [comment]
@crabicode I update [comment](https://github.com/microsoft/vscode/issues/76537#issuecomment-519941289)
@babakks @deepak1556 Any news?

**Comment by babakks** [comment]
I'd be happy if I could help, but I'm not using macOS, nor I'm involved with the issue.

**Comment by dalisoft** [comment]
@babakks Aw, sorry. Please, really sorry.
Yes, i mean @bpasero !

**Comment by crabicode** [comment]
@dalisoft I've updated to Mojave as per your advice. vscode opens projects in native tabs for me now.

**Comment by dalisoft** [comment]
@crabicode Nice, but for my macbook Sierra works quicker than Mojave if i compare after month usage of each macOS

**Comment by bpasero** [comment]
I will close this because we do not have the resources to support this feature in older macOS versions, sorry. I suggest to update.

**Comment by bpasero** [comment]
I will reopen this as I think we should still report this to Electron. 

Is anyone here in the issue willing to distill a reproducible case against Electron so that we can report this?

**Comment by bpasero** [comment]
Anyone?

**Comment by dalisoft** [comment]
I don’t have macOS Sierra currently, issue already fixed?

**Comment by bpasero** [comment]
I think there are still people that complain that native tabs are not working with macOS 10.12. Waiting for someone with 10.12 to respond, then we can see to reproduce with a simple Electron app.

**Comment by dalisoft** [comment]
I try install Sierra and test in weekend

**Comment by bpasero** [comment]
Thanks!

It should be as easy as:
* download Electron fiddle
* pick Electron 6
* in the browser window options add: `tabbingIdentifier: "foo"`
* run it

![image](https://user-images.githubusercontent.com/900690/67304961-e99ba500-f4f4-11e9-8345-1518626d1177.png)

**Comment by dalisoft** [comment]
@bpasero 
I can confirm it is does not work

![](http://joxi.ru/Vrw6EGni7eEbWA?d=1)

---

OS Info

![](http://joxi.ru/L21Z6glcRM9vzA?d=1)

**Comment by bpasero** [comment]
@dalisoft thanks a ton for doing this ❤️ . Now as a last step, can you distill this into an issue against Electron [here](https://github.com/electron/electron/issues) and link the bug back here?

**Comment by dalisoft** [comment]
I try @bpasero now

**Comment by dalisoft** [comment]
@bpasero You can track bug at [here](https://github.com/electron/electron/issues/20703) in Electron repository

**Comment by dalisoft** [comment]
I found workaround by trying many ways to get it work in Sierra.

Required: System Preferences -> Dock -> Open document in tabs -> Only in full-screen mode.

1. Run VSCode
2. Maximize / make it Full-screen
3. Click Window -> New Tab in VSCode
4. Make revert window status to previous state (no full-screen)
5. Maximize again.
6. Enjoy working solution.

If you want open new tabs, try 3-5 steps again. 

Note: If you forgot steps 3-5, you able to use native-tabs, but top tabs bar will be empty or hidden (i don't why)

This solution tested in v1.40 and v1.39.

Hope it helps you :smile:

**Comment by aitiancai** [comment]
VSCode Version:  1.63.1
OS Version: macOS 12.1
CPU :Apple M1
already does not work

**Comment by dalisoft** [comment]
@bpasero As linked issues are closed, this can be closed too
