### ISSUE TITLE
Doc bug: no additionalLaunchArgs (actually launchArgs)

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#76531]
Docs at https://code.visualstudio.com/api/working-with-extensions/testing-extension#disabling-other-extensions-while-debugging say you can specify `additionalLaunchArgs: ['--disable-extensions']` but the property is actually just `launchArgs`.

**Comment by octref** [comment]
Thanks, queuing updates to website.

**Comment by isidorn** [comment]
@octref thanks for fixing this.
