### ISSUE TITLE
Open remote file for editing from local command line

### ISSUE THREAD

**Issue by talsaiag** [microsoft/vscode#76533]
I would like to open a remote file for editing (using ssh, specifying host_address, ssh_port, user_name, password / key) from my local computer using the command line.

Target usage:
code -h remote_host_address -p 22 -u username -i key_file.pem /path/to/file/on/remote/host:line_number

So far I have been using [vscode-sshfs extension](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) to access and edit files on different remote machines (passing those arguments via the environment variables). But there is no support for opening a specific file URI and specific line on a different FileSystemProvider (or using a different url scheme, for that matter) from the command line.
Running `code ssh_fs://path/relative/to/root` opens local file `~/ssh_fs/path/relative/to/root`.
(working on mac, if that makes any difference)

Thanks,
Tal

**Comment by dbaeumer** [comment]
@talsaiag have you tried the new VS Code remote extensions for ssh. See https://code.visualstudio.com/docs/remote/ssh

**Comment by talsaiag** [comment]
I have tried it;

I'm connecting to multiple temporary remote hosts at a time.
Setting them inside the ssh config file is burdensome.

As I mentioned, if possible, I would like to use the command line to open a remote file the same way I would if it was local:
`code -h remote_host_address -p 22 -u username -i key_file.pem /path/to/file/on/remote/host:line_number`

Maybe even use --wait in addition, and also support more than one opened paths from more than one remote host (preferable using the same vscode window).

I want to eventually be able to run `code local_path_on_remote_host` inside a remote ssh connection and get a local vscode window pointing to that file/folder on the remote instance in question - but that is way too much to ask here :)
(and I think I have a way for doing just that if I have the command line support listed above, without ever configuring the remote host prior, from any outgoing ssh connection from my local host)

**Comment by roblourens** [comment]
>  want to eventually be able to run code local_path_on_remote_host inside a remote ssh connection and get a local vscode window pointing to that file/folder on the remote instance in question

This actually works already, if you are connected to a remote already and do it in vscode's integrated terminal.

For connecting from a local terminal, https://github.com/microsoft/vscode-remote-release/issues/585
