### ISSUE TITLE
Unexpected cut and paste

### ISSUE THREAD

**Issue by vintzl** [microsoft/vscode#76539]
Say I have a block of code that I want to cut/copy and paste anywhere in the code.
1. If I cut/copy the code;
2. **then delete the blank line/all blank lines (if I did cut)** OR **delete the existing lines (if I did copy)**
3. then try to paste the code anywhere I want,

The buffer contains no more the lines of code, but a blank line…

![Peek 2019-07-03 21-56](https://user-images.githubusercontent.com/44751088/60621692-9cc57e80-9dde-11e9-94f8-778b6a12856e.gif)

I noticed this with all Visual Studio Code up to 1.36.0.
OS Version: Debian Stable amd64

**Comment by rebornix** [comment]
I can't reproduce this issue on Linux. Does everything you delete is saved to the clipboard?

**Comment by vintzl** [comment]
Yes, as you can see in the gif, the block of code is cut, then the remaining blank line is deleted.
Finally, when I want to paste the previous block of code, the clipboard return a blank line/new line…

**Comment by rebornix** [comment]
@vintzl what I mean is does it happen every time when you press delete button?

**Comment by vintzl** [comment]
what didn't you understand?

**Comment by alexandrudima** [comment]
@vintzl Does this reproduce when disabling all extensions? What about your keybindings? Did you by any chance customize `ctrl+v` or `delete`?

**Comment by vintzl** [comment]
hum… strange enough, I tried with a PHP workstation and this issues does not occur. So this is not a VSCode issue. Sorry :s

Maybe you right :s, there is a problem with keybindings. I will check shortcuts of the C# workstation.
