### ISSUE TITLE
Should Online Services Settings command be available from the Command Palette?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#76530]
- VSCode Version: 1.36.0
- OS Version: Windows

The Online Services Settings command, which brings up the Settings editor filtered by `@tag:usesOnlineServices`, is available from the File > Preferences menu and gear settings context menu but not the Command Palette.

**Comment by RMacfarlane** [comment]
I think this is used infrequently enough that it doesn't need to be in command palette, so will close this as out-of-scope
