### ISSUE TITLE
Taskbar Menu Item for Opening VSCode in Remote

### ISSUE THREAD

**Issue by navneethc** [microsoft/vscode#76535]
This is a feature request. Would it be possible to add an item to the taskbar menu to open VSCode in remote mode.  Something like *New Window [WSL]*.

![image](https://user-images.githubusercontent.com/4192839/60618532-0c923400-9df4-11e9-9cac-3836bc927528.png)

**Comment by aeschli** [comment]
Remote WSL is currently only an extension, not part of VSCode. So adding a taskbar item is difficult.

We have currenlty no plans to add this.

**Comment by navneethc** [comment]
Oh, alright. Appreciate the reply.
