### ISSUE TITLE
Fatal error when working with  codes on remote server

### ISSUE THREAD

**Issue by hamedhaghighi** [microsoft/vscode#76536]
Issue Type: <b>Bug</b>

When working with codes which are on the remote server (accessed by sftp protocol for example) if the connection gets lost the VS code will clear the file code on the server and show the alert that it cannot save the file. This bug is very dangerous since it can ruin the complete project if the programmer does not understand the error. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 3042)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|11.62GB (2.29GB free)|
|Process Argv|--unity-launch /run/user/29999/gvfs/sftp:host=172.16.146.239,user=mlcm/home/mlcm/Danial-Home/Our_branch_except_Sepehr/UTLC/RNAN/code|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
githd|hui|2.1.0
vscode-github|Kni|0.30.2
python|ms-|2019.6.22090

</details>

**Comment by dbaeumer** [comment]
@hamedhaghighi  How do you access the files using sftp. VS Code has no support for this out of the box.

**Comment by hamedhaghighi** [comment]
I connect to the server using nautilus file browser on ubuntu and then open
codes via vscode. It is like opening file using sftp

**Comment by dbaeumer** [comment]
But in this case this is transparent for VS Code since it looks like a normal file system. I don't see how we could handle this special.

**Comment by hamedhaghighi** [comment]
I dont know what you mean by transparent here. I haven't seen this issue on
other IDEs; they just alert that the IDE cannot save the file when the
connection is lost. but Vs code clear the file which is obviously a fatal
bug.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
