### ISSUE TITLE
Move Panel to the Left

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#76543]
Issue Type: <b>Feature Request</b>

Right now the Panel can only be positioned at the bottom/right. It would be useful to allow a more flexible placement. For example, Panel -> Left and Sidebar -> Right

(the latter, Sidebar -> Right is already supported)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.16299

**Comment by tlemo** [comment]
Actually, why not go all the way to the Visual Studio shell docking model, with a generic pene docking model?

**Comment by gjsjohnmurray** [comment]
Duplicate of #37877
