### ISSUE TITLE
File events: missing events when workspace path has accent on macOS

### ISSUE THREAD

**Issue by LioMasterRIE** [microsoft/vscode#76541]
- VSCode Version: 1.35.1
- OS Version: macOS Mojave

Steps to Reproduce:

1. create a path with accent : /home/test/année
2. put the GIT repo in this directory
3. Open this folder in VScode and Make a modification on a file
4. --> source control need manual update to show modificated files

need to manual refresh (looks like no file modified)
<img width="454" alt="need manual update" src="https://user-images.githubusercontent.com/38889163/60623442-f7f97000-9de2-11e9-802a-43b69fcc30a7.png">

once manual refresh done (we see the modified file)
<img width="454" alt="manual update done" src="https://user-images.githubusercontent.com/38889163/60623510-1cede300-9de3-11e9-878c-7f3ba5305233.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

I can't reproduce this on Insiders.

**Comment by LioMasterRIE** [comment]
I tried with insider release and it is the same (not working)
I tried to change the accent word (année) to a single letter (é or à) and the issue is still here
as I change the word or letter to (a or e or annee) it is working well

make a modification to a file, save the file and the source control doesn't update
if there is no accent the auto update is working well

**Comment by joaomoreno** [comment]
> make a modification to that file

Is `année` a file, or a folder?

**Comment by LioMasterRIE** [comment]
it is a folder, just like that for example
/home/année/gitFolder/file.txt

**Comment by joaomoreno** [comment]
What's your git version? `git --version`

**Comment by LioMasterRIE** [comment]
2.21.0

**Comment by LioMasterRIE** [comment]
it is now working 
I changed a setting in viscose and it makes the application to work :
- I launched vscode and I unchecked Autorefresh and then I closed vscode
- I launched vscode and I checked back Autorefresh  and closed vscode again
- Now vscode is working perfectly

<img width="485" alt="AutoRefresh" src="https://user-images.githubusercontent.com/38889163/62540622-52f60b00-b858-11e9-8fd2-f46a0fdf6d92.png">
