### ISSUE TITLE
Make it easier to tell which status item will be disabled in context menu

### ISSUE THREAD

**Issue by kbd** [microsoft/vscode#76544]
It's not clear, when you right-click on a status bar item, which item in the list will be hidden when you click "Hide". For reference, here is the current right-click UI:

![Screen Shot 2019-07-03 at 2 44 16 PM](https://user-images.githubusercontent.com/728060/60623971-5140af80-9da1-11e9-8c04-36a5ded3c88f.png)

I found myself right clicking on a status bar item and clicking "Hide", then right clicking on the status bar again to see what was now unchecked from the pop-up menu.

![Screen Shot 2019-07-03 at 2 50 13 PM](https://user-images.githubusercontent.com/728060/60624196-e5127b80-9da1-11e9-967d-d697db6d73d2.png)

"Oh, that's what extension that icon with three lines is for." I did subsequently realize that if you hover over a status bar item you get a description tooltip, but notably that doesn't match the text presented in the screenshotted right-click menu, *and* you can have multiple status bar items for one feature (hidden together with right-click, like "Source Control") so it still takes some figuring to match it up.

Suggestion: change it from simply "Hide", to "Hide: Name of Feature" (as presented in the above list). Alternate suggestion: highlight/bold the currently-right-clicked-on feature in the above list so it's clear which one you're going to hide.

**Comment by bpasero** [comment]
@kbd thanks for the feedback. We typically do not like to have 1 issue that talks about 3 different things, can you please update this issue to talk about one suggestion and create 2 more for the others? Thanks.

**Comment by kbd** [comment]
Ok, no problem, I'll split these up. Thanks!

**Comment by bpasero** [comment]
Thanks

**Comment by kbd** [comment]
Those are all edited and split up, sorry for the trouble.

**Comment by bpasero** [comment]
If we change this, we should also change it for the view/panel context menu.

//cc @sandy081 @isidorn

**Comment by isidorn** [comment]
I think this makes sense.

**Comment by bpasero** [comment]
Decided to only push this for status bar because there is often no label, while views have it.

**Comment by bpasero** [comment]
Verify: right click on a status bar item and see that "Hide" label includes the name of the status bar entry.
