### ISSUE TITLE
Large cache data folders of portable VSCode

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#76546]
- VSCode Version: 1.35 (Portable mode)
- OS Version: Windows 10

I am using portable VSCode. As mentioned in the [docs](https://code.visualstudio.com/docs/editor/portable), I need to move the `data` folder to the new version of VSCode whenever there is an update.

Then I found the `data` folder takes ~1.35G space. Among those folders, `Cache` and `CachedData` are 1.04G, which is pretty much 5 times larger than VSCode itself 😮

![Capture](https://user-images.githubusercontent.com/7588612/60627002-70acfc00-9de4-11e9-88ca-32ef4874f831.PNG)

I have tried `window.localStorage.clear()` but it didn't help.

May I ask what they are and how to clean them?

Cheers

**Comment by dbaeumer** [comment]
@yzhang-gh can you let us know how big `Cache` is and how big `CachedData` is. The first one is actually not really under our control.

**Comment by jrieken** [comment]
Not sure what's in `Cache` and not sure how large `CachedData` is for you but it's expected that we but data there, approx 50MB per version of VS Code. There is logic to make sure that we clean up data which is older then 3 months for stable and data which is older than 1 week for insiders: https://github.com/microsoft/vscode/blob/7980cd2697482e14a1f2ea9a8a36c064aebc180b/src/vs/code/electron-browser/sharedProcess/contrib/nodeCachedDataCleaner.ts#L15-L17

**Comment by bpasero** [comment]
Cache is a folder from Electron / Chromium. Nothing we control currently, but should be free to be deleted between a restart.

**Comment by yzhang-gh** [comment]
Thanks for all the reply.

The `Cache` is 324M and `CachedData` 787M

> Cache is a folder from Electron / Chromium. Nothing we control currently, but should be free to be deleted between a restart.

Got it.

---

I usually organize my working files into folders by week, e.g. `190701` for this week.
There is one globally-disabled extension is enabled at folder level in some of above folders.
Every week I rename the folder of past week, e.g. `190701` to `190701 summary text`.

I was wondering whether the cache for `190701` was still there although the folder was renamed.

**Comment by yzhang-gh** [comment]
Got a new version (v1.36.1) today and had to copy them again...

Now the `CachedData` folder is 817M 😥. Is there a safe way to delete it?

**Comment by bpasero** [comment]
@jrieken please decide if this is actionable, user seems to complain about `CachedData` folder which is from us and not from Chrome/Electron. 

![image](https://user-images.githubusercontent.com/900690/66543177-f0114080-eb34-11e9-95c2-78b91c4b3cb7.png)

**Comment by jrieken** [comment]
We keep that data around to make subsequent startup faster. As @bpasero mentioned it's not needed (and can be deleted). What you can do

* Use the `--no-cached-data` command line flag which disables cached data, e.g no new cached data will be produced
* Create a sym link for the cached data directory so that it points to a non portable directory

**Comment by jrieken** [comment]
Closing because no change on our side is planned.
