### ISSUE TITLE
Latest update BREAKS mouse forward/back buttons

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode#76547]
After latest update VS Code does not recognize system-wide mouse back/forward buttons. Before 1.36 it worked perfectly

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by inliquid** [comment]
@bpasero It's not duplicate, #71318 is referring problem on Linux OS and at insiders build, while this one is for other OSes as well and regarding a recent update on regular (GA) build.

**Comment by bpasero** [comment]
@inliquid yeah bad title, I renamed it. It's the same.
