### ISSUE TITLE
Closing a conpty terminal can hang the window

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76548]
https://github.com/microsoft/terminal/issues/1810

**Comment by Tyriar** [comment]
This is causing integration tests to fail under conpty https://github.com/microsoft/vscode/issues/75689

**Comment by Tyriar** [comment]
Console team's issue: https://github.com/microsoft/terminal/issues/1810

**Comment by Tyriar** [comment]
@alexr00 this is caused by inherit cursor position which was a fix for terminals that have already been written to before the process launches (just tasks). We have 2 options to workaround the crashes:

- Only enable the flag for ter minals that have already been written to, we don't need to pass around as I just need to know if `TerminalInstance.write` was called. There's still a chance of a crash but it should rarely happen as the most common repro is creating a bunch of terminals and killing them immediately.
- Disable the flag completely and move tasks to winpty again.

**Comment by alexr00** [comment]
Option 1. Conpty is the way of the future and I'd rather we keep finding new bugs there than seeing the same old winpty bugs.

**Comment by Tyriar** [comment]
I'm going to call this fixed in August with this workaround, while a hang likely can still occur it should be very tough to reproduce just with tasks. If people are hitting it they can avoid using the flag completely by configuring the task to not show the intro line and not reuse terminals.

**Comment by Tyriar** [comment]
I'm getting reports that this is still happening with the workaround:

- https://github.com/microsoft/vscode/issues/79303
- https://github.com/microsoft/vscode/issues/71966#issuecomment-521374053

**Comment by usernamehw** [comment]
The upstream issue https://github.com/microsoft/terminal/issues/1810#event-2585115689 was fixed. Will this be fixed in **1.39**?

**Comment by Tyriar** [comment]
@usernamehw depends on a Windows update and the fix is too complicated to backport.

**Comment by Tyriar** [comment]
Fixed upstream, closing. You may see this until updating to Windows >1903, other windows crashes tracked in https://github.com/microsoft/vscode/issues/71966#issuecomment-521374053

**Comment by csicky** [comment]
Installed the new powershell and set it as default. https://github.com/PowerShell/PowerShell/releases
Now it doesn't freeze anymore when I close it.

**Comment by Tyriar** [comment]
Not sure why I reopened this, see #71966
