### ISSUE TITLE
The Folding code feature is missing

### ISSUE THREAD

**Issue by hzb** [microsoft/vscode#76559]
Issue Type: **Bug**

I wrote nodejs in VSCodium, and here are some codes

```
.get("/a", async(ctx)=>{
    //lots of codes
})
.get("/b", async(ctx)=>{
    //lots of codes
})
.get("/c", async(ctx)=>{
    //lots of codes
})
```

And some code blocks have the folding code feature, but some don't have.  

![Screen Shot 2019-07-04 at 12 04 21](https://user-images.githubusercontent.com/535675/60639154-f5832e80-9e53-11e9-9ace-3a5de9dd0d55.png)

![Screen Shot 2019-07-04 at 12 04 32](https://user-images.githubusercontent.com/535675/60639156-f61bc500-9e53-11e9-9069-c5ef91407975.png)

VS Code version: VSCodium 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T18:19:13.191Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 3|
|Memory (System)|8.00GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.4
markdown-preview-github-styles|bie|0.1.6

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are on an old, unsupported build

**Comment by hzb** [comment]
@mjbvz No, I submitted this issue from VSCodium, and I tried on VSCode (the latest version downloaded from https://code.visualstudio.com/download), it has the same issue, I took a screen recording that might help you.

https://www.dropbox.com/s/7my4iiywm72wxpn/Screen%20Recording%20.mov?dl=0

I think you should open this issue.

**Comment by mjbvz** [comment]
Share some complete code that demonstrates this. It does not reproduce with your simple example

**Comment by hzb** [comment]
@mjbvz You can check some codes here: https://gist.github.com/hzb/11fa960f89e54b39ea41cfb807561da1

And another screen recording: https://www.dropbox.com/s/35mz56o0cse0zas/sr02.mov?dl=0

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/32328 to track root cause upstream

**Comment by hzb** [comment]
You are welcome.
