### ISSUE TITLE
User input variables in launch config are broken

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#76558]
- Add one of the special `input` to some launch config, like

```
"cwd": "${input:cwd}"
```

- Start the launch config
- Get "Cannot read property 'filter' of undefined"

From https://github.com/microsoft/vscode/blob/6a7d02f2f44446a7eda01abeb1c25122e148d264/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L231

**Comment by isidorn** [comment]
@weinand assigng to you, feel free to assign back to me if you would like me to investigate

**Comment by weinand** [comment]
I cannot reproduce.

Please note that "input" variables require a proper "input" section in the launch.json, e.g. this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Hello World",
            "cwd": "${input:cwd}",
            "runtimeExecutable": "foo"
        }
    ],
    "inputs": [
        {
            "id": "cwd",
            "type": "promptString",
            "description": "Please enter a cwd value",
            "default": "default_cwd"
        }
    ]
}
```

This works fine.

But even if the "input" section is missing like here:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Hello World",
            "cwd": "${input:cwd}",
            "runtimeExecutable": "foo"
        }
    ]
}
```
I get a proper error message:

![2019-07-04_11-15-49](https://user-images.githubusercontent.com/1898161/60654874-172ce780-9e4d-11e9-9f4b-51fb3dad87a2.png)

**Comment by weinand** [comment]
@roblourens ping?

**Comment by roblourens** [comment]
Oh I forgot about the inputs section. But when that is missing, that's when the unhelpful error message shows up.
