### ISSUE TITLE
Cannot load extensions

### ISSUE THREAD

**Issue by aj96** [microsoft/vscode#76551]
- VSCode Version: 1.36.0 Insider
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. Launch vscode
2. Click on Extensions tab

Does this issue occur when all extensions are disabled?: N/A

I tried installing vscode and vscode insider from scratch, but no matter what, I cannot load any extensions. The extensions available to me is always empty. I tried restarting my computer and the wifi, but that does not help. I realize this is similar to https://github.com/Microsoft/vscode/issues/19753 However, the issue was closed to only vscode collaborators. 

<img width="1013" alt="vscode_extension" src="https://user-images.githubusercontent.com/19962279/60630189-dc27a700-9dad-11e9-9a04-e5de7099f411.png">

**Comment by sandy081** [comment]
Do you have any proxy issues like your machine is behind some proxy and cannot connect to Marketplace?

Can you also open the developer tools and see if there are any errors in the console?

Also open Log (Shared Process) from Output panel and see if there is any info that can help us understanding the issue?

**Comment by aj96** [comment]
@sandy081  I don't know what the issue was, but when I opened vscode today, everything was working normally. So it's a non-issue now. Thank you for your timely reply. I'll close the issue now.
