### ISSUE TITLE
Enable an iterative git workflow by showing diff compared to master

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#76552]
My current situation:

- I have a branch `pine/feature` where I have made 5 edits.
- I want "changes from master" as a contextual hint as to what I have changed and what to work on next.
- I could have used GitLens' "compare branches" to compare my branch with master. But the diff that's opened is not editable.
- I could have used PR extension to open a diff view for `foo.ts`, where I can see my changes as compared to master. But I have to at least open a "draft pull request" for this to work.
- I could have done `git reset --soft HEAD~5`, where I can see the diff and edit the file at the same time, but I cannot very easily make a new commit. I would have made my previous 5 commits and the new changes into a single commit.

What I really want is the diff view in Git Viewlet I get after `git reset --soft HEAD~5`.

I don't think this feature belongs to PR extension since I find it useful outside the context of a PR as well.

I also think this is something we should add core to enhance the git experience: a nested view under Git Viewlet which shows your changes compared to master (or another specific commit).

**Comment by joaomoreno** [comment]
cc @eamodio

**Comment by octref** [comment]
I should simplify my ask: Add another tree `Changes from master` below `Changes`. Provide an action to switch default branch. When clicked, each file reveals a diff editor comparing local `foo.ts` to `foo.ts` on master branch.

![image](https://user-images.githubusercontent.com/4033249/60825511-ae9d7d80-a160-11e9-929d-1af99b061b9d.png)

**Comment by eamodio** [comment]
@octref Is this something different than the branch compare node in the GitLens Repositories view:
![image](https://user-images.githubusercontent.com/641685/60831480-ae64a880-a187-11e9-9b50-51e6543635fe.png)

**Comment by octref** [comment]
@eamodio Diff view opened there is not editable. I can't "See my changes in annotations.ts while making more changes".

**Comment by eamodio** [comment]
@octref Yeah, I thought it might be something like that -- I've been mulling over changing that node to open changes with the working file by default. This is probably the vote that tips the scale to do it.

**Comment by octref** [comment]
> open changes with the working file by default

Is there a setting to change the behavior?

**Comment by eamodio** [comment]
No, but in the next release, I'm going to add a setting to specify whether that compare node should use the current branch vs the working tree -- and if you choose the working tree (which I think I will make the default) then the compares will use the working tree

**Comment by eamodio** [comment]
@octref This is now in GitLens v9.8.3 -- let me know if it works for you

**Comment by octref** [comment]
@eamodio Thanks for the fast implementation! That's very useful, but I think it should be built in. I'd really like my Git Viewlet to show two trees:

- One showing changes since last commit
- One showing changes that deviate from master (The most common cases when working on PRs)

**Comment by octref** [comment]
Actually there's one missing feature.

- Let's say we have two branches, `master` and `feature` level
- `feature` advances 1 commit
- `master` advances 50 commits
- I want the same diff as if I open a PR from `feature` to `master` on GitHub
- Currently GitLens would show all files affected by the 1 commit (wanted) and by the 50 commits (unwanted)

**Comment by eamodio** [comment]
@octref You should be able to control that via the `..` or `...` button on that node:
![image](https://user-images.githubusercontent.com/641685/61075218-76f43700-a3e7-11e9-8431-0bf9b45503f6.png)

That will allow for switching between a two-dot (range) vs three-dot (symmetric) comparison

**Comment by joaomoreno** [comment]
Going with the GitLens recommendation.
