### ISSUE TITLE
Cannot launch v1.36.1 on OSX 10.9.5

### ISSUE THREAD

**Issue by voiceactivity** [microsoft/vscode#76557]
Just updated to the latest v1.36.1 running on MBP (OSX 10.9.5) and cannot start the VSC at all. Presented the error message that it can only run on OSX 10.10.x and above. Really?

My old MBP still in a good shape, but unfortunately, cannot be upgraded to 10.10.x
What are the OS specific features do you use for a code editor that prevents you running the older OSX versions?

I had to downgrade back to 1.35.1

**Comment by dasurid** [comment]
I also have the same problem.  I have several machines running Mavericks (OSX 10.9) which can no longer run VSCode after this update. These machines also cannot be updated to 10.10 and above.

I could not find any mention of OSX 10.9 being dropped in the release notes.

I had to downgrade to VSCode 1.35 and disable automatic updates on it.  Unplanned obsolescence?

**Comment by bpasero** [comment]
We never officially supported macOS 10.9.x, please see https://code.visualstudio.com/docs/supporting/requirements#_platforms

It is possible that the Electron update now enforces it. I am closing this issue based on our clear messaging that macOS 10.9.x is not supported.

**Comment by mcferren** [comment]
@bpasero It says 10.9+ on the download page: https://code.visualstudio.com/download This is blocking out a lot of people

**Comment by bpasero** [comment]
@mcferren oh wow, great catch, we need to fix that.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode-docs/issues/2861
