### ISSUE TITLE
Leftover console.log?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#76556]
![image](https://user-images.githubusercontent.com/323878/60638500-764e1600-9dd3-11e9-9171-e805b19cac63.png)
https://github.com/microsoft/vscode/blob/6a7d02f2f44446a7eda01abeb1c25122e148d264/extensions/git/src/commands.ts#L676

![giphy](https://user-images.githubusercontent.com/323878/60638563-a1386a00-9dd3-11e9-98ba-0b48e874bdd1.gif)

**Comment by joaomoreno** [comment]
4 months old! WHAT?!
