### ISSUE TITLE
EXPLORER keybindings don't work

### ISSUE THREAD

**Issue by ChangLCS** [microsoft/vscode#76555]
- VSCode Version: 1.36.0
- OS Version: win10

![图片](https://user-images.githubusercontent.com/18084468/60637951-0f6e4280-9e4f-11e9-9729-76560e0fc9e1.png)

Steps to Reproduce:

1.  Select a folder in EXPLORER 
2.  Shift + Alt + R
3.  Just like this
![图片](https://user-images.githubusercontent.com/18084468/60638106-a3d8a500-9e4f-11e9-97b9-dda11b2aef6d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment]
If you want to filter the tree, try `"workbench.list.keyboardNavigation": "filter"` in you settings

**Comment by joaomoreno** [comment]
Merging into #76369
