### ISSUE TITLE
Show a warning when storing workspace within installation folder

### ISSUE THREAD

**Issue by Brann4** [microsoft/vscode#76567]
While I was sitting, repairing some minor details on my website created as a proposal for the school of my campus, by simply closing the Visual Studio Code, there was an update of June 2019 (v 1.36), at the time I wanted to enter to finalize only 1 details of text size, all pages, styles, javascript, jquery and others, were removed by magic and I try to recover a project which depends on my approval of the course, thank you very much.

**Comment by dbaeumer** [comment]
@Brann4 where was the workspace folder located. The only case I can think of that something like this happens is when the data is put into VS Code's installation directory? Was this the case?

**Comment by dbaeumer** [comment]
@bpasero @joaomoreno we might want to think about warning the user if he stores data into the installation directory.
