### ISSUE TITLE
1.36 status bar right-click menu out of order

### ISSUE THREAD

**Issue by kbd** [microsoft/vscode#76564]
When right clicking on the new status bar in 1.36, the order of the items in the context menu (top->down) doesn't match the order of the items in the status bar (left->right). It would seem more intuitive if the two orders matched, and it would be easier to find the correct item to enable/disable if the order in the context menu matched what you see on-screen.

Menu I'm referring to, for reference:

![Screen Shot 2019-07-03 at 2 44 16 PM](https://user-images.githubusercontent.com/728060/60623971-5140af80-9da1-11e9-8c04-36a5ded3c88f.png)

**Comment by bpasero** [comment]
@kbd can you let me know which item does not match the order?

**Comment by kbd** [comment]
![Screen Shot 2019-07-04 at 12 56 45 AM](https://user-images.githubusercontent.com/728060/60645713-ae1a8500-9df6-11e9-8c9a-3d1a3748e49f.png)

Upon careful inspection, it looks like Problems appears fourth in the menu instead of first, and everything else is in the correct order if you ignore the fact that the Python extension has two items separate from each other.

The actual order in the status bar in the screenshot is:

* Problems
* Source Control
* Python (Extension)
* Salesforce CLI Integration (Extension) (hid work email address with context menu)
* Node debug auto-attach (sorry this is mostly hidden too)
* Coverage gutters
* Apex
* Python extension part 2 ("Run Tests")

The rest (on the right side of the status bar) are in the correct order, starting with "Editor Selection".

Probably related to #76561. I, too, have other windows with status bar items in a different order. Another window has the right click menu with the items in the correct order and the order of the first few items is:

* Source Control
* Python (Extension)
* Problems
* Salesforce CLI Integration (Extension)

the rest is the same.

**Comment by bpasero** [comment]
Yeah totally looks like a bug in the ordering, that should not happen. If you can provide steps to reproduce in https://github.com/microsoft/vscode/issues/76561 that would be good (e.g. your list of extensions).

Merging into https://github.com/microsoft/vscode/issues/76561
