### ISSUE TITLE
Persist view/panel/status view state in settings

### ISSUE THREAD

**Issue by kbd** [microsoft/vscode#76563]
Previously, the "Tweet Feedback" status bar item was hidden using the setting `workbench.statusBar.feedback.visible` in `settings.json`. In 1.36 a more general mechanism for hiding status bar items was added. After re-removing "Tweet Feedback" in this version, I was surprised that didn't update `settings.json`.

It looks like those settings are now recorded in `User/globalStorage/state.vscdb` instead. Unfortunately, that file isn't appropriate for source control. I'll have to manually click status bar items to keep or remove on each computer I use Visual Studio Code from, whereas previously that was easy to keep in source control with `settings.json` and share among all computers I use.

**Comment by bpasero** [comment]
I intentionally did not pick settings.json to store this because we also do not store other state in there (visible views, panels, order). Renaming to reflect the general desire.

**Comment by sandy081** [comment]
Yeah it is a bit weird that some are stored in setting and some does not. 

But I agree this is pretty consistent with other view state we store.

**Comment by VideoPlayerCode** [comment]
Another vote for: Yeah it's a bit weird to have this in settings.json, since no other view-states are stored in settings.
