### ISSUE TITLE
the "quick fix" feature does not work in the new version of vscode

### ISSUE THREAD

**Issue by cnyunguo** [microsoft/vscode#76566]
Issue Type: <b>Bug</b>

I am using the translation software to give you feedback. If the description is not clear, please contact: zhangbaoqi888@gmail.com;
I use dart programming, the "quick fix" feature does not work in the new version of vscode, please pay attention to this issue.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
dart-code|Dar|3.2.0
flutter|Dar|3.2.0
sftp|lix|1.12.7
ftp-sync|luk|0.3.9
vscode-language-pack-zh-hans|MS-|1.36.2
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1

</details>

**Comment by dbaeumer** [comment]
@cnyunguo this is caused by the Dart extension which is responsible for provided quick fix for Dart. Please file the issue here: https://github.com/Dart-Code/Dart-Code
