### ISSUE TITLE
default editor theme Dark+ became gray-ish after update

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode#76562]
Issue Type: <b>Performance Issue</b>

When updated to 1.36.0,  vscode default theme Dark+ became gray-ish, the color is not of high purity anymore, and it's sorta disturbing because I couldn't see the code clearly.  I know I could change to other awesome themes, but I like the default one,so ...

Any kind of help would be great.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2435)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (0.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   134	 12214	code main
    0	    32	 12218	   zygote
    0	   395	 12259	     window (device_task.cpp - workspace - Visual Studio Code)
    0	   253	 12299	       extensionHost
    0	   237	 12354	         clangd
    0	    71	 13276	         /home/newtma/.vscode/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.VSCode.CPP.Extension.linux
    0	   292	 29081	           /home/newtma/.vscode/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 13276 17
    0	   158	 29145	           /home/newtma/.vscode/extensions/ms-vscode.cpptools-0.24.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.linux 13276 18
    0	    63	 13297	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=12299
    0	    79	 12317	       watcherService
    0	    63	 12365	       searchService
    2	   103	 12333	     shared-process
    0	     0	 30570	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 30571	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    95	 30549	     window (Issue Reporter)
    0	   103	 12246	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (device_task.cpp - workspace - Visual Studio Code)
|    Folder (workspace): 5239 files
|      File types: h(1059) c(942) cpp(347) xml(304) html(267) service(196)
|                  network(147) sh(135) in(127) json(118)
|      Conf files: makefile(36) cmake(3) settings.json(2) launch.json(1)
|                  tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.7.7
TabOut|alb|0.1.6
toml|be5|0.4.0
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
c-cpp-project-generator|dan|1.1.1
vscode-markdownlint|Dav|0.28.0
xml|Dot|2.5.0
markdown-table-formatter|fcr|1.4.3
auto-close-tag|for|0.5.6
pythonsnippets|frh|1.0.2
gc-excelviewer|Gra|2.1.32
CppSnippets|har|0.0.14
vscode-test-explorer|hbe|2.12.1
Python-autopep8|him|1.0.2
vscode-elm-jump|joe|0.0.1
vsc-python-indent|Kev|1.0.0
vscode-python-test-adapter|lit|0.3.8
vscode-clangd|llv|0.0.15
rainbow-csv|mec|1.1.1
vscode-clang|mit|0.2.3
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
python-coding-tools|nil|1.0.3
guides|spy|0.9.3
python|tht|0.2.3
highlight-matching-tag|vin|0.9.2
vscode-icons|vsc|8.8.0
org-mode|vsc|1.0.0
debug|web|0.23.1
clang-format|xav|1.9.0

(1 theme extensions excluded)

**Comment by githue** [comment]
It seems VS Code has changed or unset its color profile. My colors are twice as saturated after the update, it affects all colors in the app not just the editor.

VS Code: 1.36.0
Windows 10 (Build 18362.175)

**Comment by NewtMa** [comment]
> It seems VS Code has changed or unset its color profile. My colors are twice as saturated after the update, it affects all colors in the app not just the editor.
> 
> VS Code: 1.36.0
> Windows 10 (Build 18362.175)

dunno, I have to settle for that base16 extension and I used the "Base16 Dark Monokai" theme, and at least the "red" color is of high purity, so that theme looks fine to me.

**Comment by bpasero** [comment]
@NewtMa @githue does this work if you run from the command line:

`code --force-color-profile=srgb`

?

**Comment by NewtMa** [comment]
@bpasero sorry, i don't think that worked.

**Comment by githue** [comment]
@bpasero There was no difference when forcing to sRGB.

When I force Chrome to use sRGB instead of the default, which is monitor calibrated, I also get oversaturated colors. I've included a screenshot of my color profile settings.

![color-profile](https://user-images.githubusercontent.com/7245595/60644201-b5827280-9e78-11e9-935a-c9377546a5ab.png)

**Comment by bpasero** [comment]
Any difference running `code --disable-gpu --force-color-profile=srgb`?

**Comment by NewtMa** [comment]
@bpasero sorry, still not working. "Base16 Dark Monokai" from "Base16 Theme" extension didn't change a thing, either.

**Comment by bpasero** [comment]
Ok thanks for trying.

**Comment by dons20** [comment]
My editor looks completely washed out with most of the dark themes I used prior to the update.
![image](https://user-images.githubusercontent.com/3958349/60697974-25195180-9ebb-11e9-9afb-77bcb2b3fda9.png)

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/76656
