### ISSUE TITLE
Problems in the status bar sometimes appear to the left of Source Control, sometimes to the right

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#76561]
My two VS Code windows now have different status bars when updated to 1.36.
![image](https://user-images.githubusercontent.com/8168391/60639659-1a78a100-9e56-11e9-85f6-ff5545f0c63e.png)
![image](https://user-images.githubusercontent.com/8168391/60639670-22d0dc00-9e56-11e9-918e-58b74c8137c2.png)

- VSCode Version: 1.36.0
- OS Version: Windows 10 18362.175

Steps to Reproduce:

1. Open a VS Code window. the Problems on the status bar may appear to either the left or right of the Source Control.
2. After performing some Git actions, the relative position between Problems and Source Control might change.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@infinnie can you give a list of your installed extensions?

**Comment by infinnie** [comment]
OK.
![image](https://user-images.githubusercontent.com/8168391/60656857-d9e34c80-9e82-11e9-82db-586d544a2ebc.png)

**Comment by bpasero** [comment]
@infinnie thank you very much!

PR open for recovery: https://github.com/microsoft/vscode/pull/76598

**Comment by SupinePandora43** [comment]
what's about drag&drop feature for statusbar items?!

**Comment by isidorn** [comment]
I have verified this is no longer happening thus adding a verified label.
However I have discovered this git status bar issue while verifying https://github.com/microsoft/vscode/issues/76949
