### ISSUE TITLE
jsconfig paths not working for .mjs files

### ISSUE THREAD

**Issue by ashuanindian** [microsoft/vscode#76576]
- VSCode Version: 1.35.1
- OS Version: Mac Mojave

Steps to Reproduce:

JS config file
{
    "compilerOptions": {
      "target": "es6",
      "allowSyntheticDefaultImports": false,
      "baseUrl": ".",
      "paths": {
        "config": ["./config/*"],
        "client/*": ["./src/client/*"],
        "server/*": ["./src/server/*"],
        "shared/*": ["./src/shared/*"],
        "mtpd/*": ["./mtpd/*"]
      }
    },
    "exclude": ["node_modules", "dist"]
  }

Create two files.
./src/shared/sum.mjs

export function sum(a,b) {
  return a+b;
}

./src/shared/app.mjs

import {sum} from 'shared/sum.mjs'
sum(2,3);

on click of sum ide scrolls to the import statement.
Works as expected for .js files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Mjs support is tracked upstream by https://github.com/microsoft/TypeScript/issues/27957
