### ISSUE TITLE
Linux: 1.36 tarball shipping with shared library instead of executable

### ISSUE THREAD

**Issue by budach** [microsoft/vscode#76574]
- VSCode Version: 1.36
- OS Version: Linux 64bit

I am using the Linux 64bit .tar.gz releases and the "code" file in the parent directory is now a shared library instead of an executable (according to my file manager Thunar). I am a little bit short on the details about what that means, but I am now not able to directly launch this file anymore by clicking it, I also cant launch it through the script in the bin/ folder. I went back to the 1.35.1 .tar.gz release and here the code file is an executable and I can run it just fine.

Is this intended?

**Comment by bpasero** [comment]
Here is a comparison of the file contents (left new, right old):

![image](https://user-images.githubusercontent.com/900690/60721315-ce992b00-9f2d-11e9-919d-0cd1db77cb19.png)

Can you be more more specific what you mean?

**Comment by budach** [comment]
Sure. I am talking about the file named "code", which used to be an executable, but which is now a shared library I can't run. When I made my above post yesterday I was using some unnamed Linux From Scratch distro. I just tested it again on another machine with Fedora 30 and I still can't run it, see screenshot:

![screen](https://user-images.githubusercontent.com/7905425/60722338-e625e300-9f30-11e9-9f48-55bfbb52ddc3.png)

**Comment by bpasero** [comment]
@Tyriar thoughts?

**Comment by Tyriar** [comment]
I can confirm, probably is related to the Electron update @deepak1556 

1.36.0:

<img width="480" alt="Screen Shot 2019-07-05 at 10 01 27 AM" src="https://user-images.githubusercontent.com/2193314/60736476-f081b600-9f0b-11e9-8819-00cf95764dda.png">

1.35.1:

<img width="488" alt="Screen Shot 2019-07-05 at 10 01 04 AM" src="https://user-images.githubusercontent.com/2193314/60736477-f081b600-9f0b-11e9-9908-f39f0b834382.png">

I can still execute it from the command line just fine, but running it from file managers won't work.

**Comment by joaomoreno** [comment]
I saw the same thing, yet gave it no thought. The file does have the exec bit, @budach you can run it from the command line.

**Comment by budach** [comment]
Thanks for the hint, I got it running now. No issue for me anymore.

**Comment by bpasero** [comment]
I confirmed this is a bug in Electron: https://github.com/electron/electron/issues/19162

**Comment by bpasero** [comment]
As designed: https://github.com/electron/electron/issues/15406#issuecomment-435480303
