### ISSUE TITLE
Peek definition for import {} in TypeScript

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#7657]
Imagine this code

def.ts:
```
export interface Message {
  name: string
}
```

code.ts: 
```
import {Message} from './def'
import * as def from './def'

let test1:Message
let test2:def.Message
```

When I peek definition of `Message` in `let test1:Message` i only get `import {Message} from './def'` - it would be awesome if it was smart enough to determine that i'm importing interface `Message` and give me definition of that interface. Works fine for `let test2:def.Message` case

**Comment by dbaeumer** [comment]
Moving to TS since the feature is provided there.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9177
