### ISSUE TITLE
Improving the settings.json experience

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#76575]
I'd like to resurface #43670 which I think was closed prematurely. @nojvek Made a lot of really good suggestions there for improving the `settings.json` experience which I much prefer to the settings UI.

Particularly, the ability to sort settings alphabetically by key (without having to install an extension) and smart search applied not only to the default settings pane on the left but also to the user/workspace settings on the right are essential, I think.

**Comment by sandy081** [comment]
Settings json editor is not maintained anymore. Settings UI is the editor we support for editing settings. Hence no more features will be done on old settings editor.
