### ISSUE TITLE
Support InstantiationService in extension host

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#76570]
In the VS Code frontend the `ExternalTerminalService` is registered via `registerSingleton` here:
https://github.com/microsoft/vscode/blob/7c88e07cc69633729be10d25e8408707fce48bf4/src/vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts#L389-L395

I'd like to use the same service in the backend (ext host) and I would like to share the approach how it is initialised (registered). Currently I'm doing this:
https://github.com/microsoft/vscode/blob/7c88e07cc69633729be10d25e8408707fce48bf4/src/vs/workbench/contrib/debug/node/terminals.ts#L17-L25

But I would rather like to use the `InstantiationService` and the `registerSingleton` calls for this.

**Comment by jrieken** [comment]
@weinand there is now an instantiation service in the extension host and `ExtHostDebug...` is being created with that. That should give you access to those terminal services and/or the instantiation service itself. 

https://github.com/microsoft/vscode/blob/3a47abace18bd464e12f30ebb731519384f51f77/src/vs/workbench/api/node/extHost.api.impl.ts#L126

**Comment by weinand** [comment]
@jrieken great, I'll give it a try!
