### ISSUE TITLE
not able to see how the command "yarn smoketest" is implemented and where it is referring the testscripts to execute testing on UI components

### ISSUE THREAD

**Issue by androdvlpr** [microsoft/vscode#76580]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by androdvlpr** [comment]
thanks for this, for me yarn smoketest is working. i want to use that for my vs code application. please help me how i can make use of this framework in my application. we have added extensions and want to extend this framework to do some more testings related to our vs code application.

**Comment by joaomoreno** [comment]
Check inside `test/smoke`
