### ISSUE TITLE
“Remove destructuring” changes the function signature.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#76583]
- VSCode Version: 1.36.0
- OS Version: Windows 10 18362.175

Steps to Reproduce:

1. Write code like function `f({x}, y) {}`.
2. Select Remove destructuring from “Show fixes”.
3. it is refactored to `f(y) {}`, which might cause problems because the function signature is changed.

I guess that it might be better refactored to something like `f(_, y) {}`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/32297 to track upstream
