### ISSUE TITLE
Commenting out in tsx file

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#7658]
Right now when I use `cmd+/` in tsx file in jsx part of the file:

eg. on second line of:

```
<div>
  <div>...</div>
</div>
```

then it will convert it to

```
<div>
  // <div>...</div>
</div>
```

It would be awesome if it could turn it into 

```
<div>
{/* <div>...</div> */}
</div>
```

**Comment by sandy081** [comment]
This issue was moved to Microsoft/TypeScript#9210
