### ISSUE TITLE
Window does not open when specifying --max-http-header-size in NODE_OPTIONS

### ISSUE THREAD

**Issue by sysmat** [microsoft/vscode#76585]
- VSCode Version: Version 1.36
- OS Version: Win 10 1803(OS Build 17134.829)

Steps to Reproduce:
Not even start

Does this issue occur when all extensions are disabled?: Yes/No
NO

**Comment by sysmat** [comment]
--max-http-header-size= is not allowed in NODE_OPTIONS

**Comment by bpasero** [comment]
@sysmat 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by sysmat** [comment]
@bpasero 

* my system environment variable NODE_OPTIONS hase:
`--max-http-header-size=200000`

* when running command:

```
PS C:\Users\tomaz> code --verbose
C:\Users\tomaz\AppData\Local\Programs\Microsoft VS Code\bin\..\Code.exe: --max-http-header-size= is not allowed in NODE_OPTIONS
```

editor window not open

PS: If I remove NODE_OPTIONS then editor window open and work.
But for me when developing web application with REST API is responding with jersey trace headers  and node start blocking response(is to big), but with previus VSCode version it work fine with my NODE_OPTIONS

**Comment by bpasero** [comment]
@sysmat so you say this used to work in our previous releases, e.g. 1.35?

**Comment by sysmat** [comment]
Yes, NODE_OPTIONS I have for for few months  and newer have problems with VS, but 4 days ago after upgrading this happened

Regards, Tomaž

**Comment by sysmat** [comment]
All of member in our team have the NODE_OPTIONS and after upgrading(also linux os) have this problem, after reverting to previous version of VS it works normal

**Comment by sysmat** [comment]
maybe for title: editor doesn't open

Regards, Tomaž

**Comment by sysmat** [comment]
```
PS C:\Users\tomaz> node --version
v12.6.0
```

**Comment by sysmat** [comment]
also the same problem with node 10.16.0 LTS

**Comment by bpasero** [comment]
@sysmat it looks like this option only got added in node.js 11, but Electron is still using 10:

https://nodejs.org/api/cli.html#cli_max_http_header_size_size

**Comment by sysmat** [comment]
Yes, thx  @bpasero
