### ISSUE TITLE
Add Zoom region when the user hover regions into the minimap

### ISSUE THREAD

**Issue by javierlopezdeancos** [microsoft/vscode#76586]
The minimap could show a circle region Zoom when the cursor hovers this region in minimap.

**Comment by rebornix** [comment]
@javierlopezdeancos can you help elaborate more about what's *circle region Zoom*?

**Comment by javierlopezdeancos** [comment]
Yep sure, let me do some designs and sketch about my idea

**Comment by javierlopezdeancos** [comment]
![feature](https://user-images.githubusercontent.com/1202463/61530015-2b630e00-aa23-11e9-97b6-1a0b41f6c0da.png)

**Comment by rebornix** [comment]
@javierlopezdeancos thanks ;)

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/40048
