### ISSUE TITLE
Improve markdown docu

### ISSUE THREAD

**Issue by rowild** [microsoft/vscode#76587]
Nowhere in the documentation of "Markdown edition" is mentioned how to suppress the removal of trailing whitespace, which is necessary to create a simple line break. Considering the size of the docu, it would be very, very helpful to mention it somewhere on page instead of expecting users to know by heart that there is a "files" available for that.

Please mention it somewhere, here is a suggestion:

## Removing trailing white space in markdown files only

In order to create a simple line break, markdown requires you to add two empty spaces at the and of the line. Usually, VSCode removes trailing whitespace. In order to tell VSCode to not remove trailing whitespace in markdown files ony, you can add these lines to your `settings.json`:

```
{
  "[markdown]": {
    "files.trimTrailingWhitespace": false
  }
}
```

**Comment by mjbvz** [comment]
Our markdown docs are all hosted [here](https://github.com/microsoft/vscode-docs/blob/master/docs/languages/markdown.md). Do you want to submit addition as a PR against that repo?

**Comment by rowild** [comment]
@mjbvz Thanks! PR done.
