### ISSUE TITLE
1.36 breaks autoimport and experimentalDecorators

### ISSUE THREAD

**Issue by zedryas** [microsoft/vscode#76597]
- VSCode Version: 1.36
- OS Version: OsX 10.14.5

Steps to Reproduce:

None, happens since the update

Does this issue occur when all extensions are disabled?: Yes

Hello all,

Since upgrading today, auto import is no longer working, and experimentalDecorators seems to not be recognized on tsconfig.

All of the above did work perfectly until the update. Anyone experiencing the same issues? How to resolves them ?

Thanks in advance

**Comment by Tarpsvo** [comment]
I am experiencing the same issue. `jsconfig.json` doesn't seem to have any effect on `experimentalDecorators` anymore.

**Comment by mjbvz** [comment]
Please share some example code or small example project
