### ISSUE TITLE
proper JSDocs for function signatures using destructuring

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#76592]
Currently the best official JSDoc support can do with function with destructure parameters is just infer that there is just one parameter which is an object.
This is not good enough, and it is a bit tedious to have to duplicate that line and add each extra parameter there.
It will be awesome if VSC JSDoc detects the names of the destructured properties and adds those, trying to infer the type from the default values when available.

Here is a GIF showing the current behavior:
![Screen Recording 2019-07-04 at 12 21 PM](https://user-images.githubusercontent.com/2270425/60660987-3c275780-9e59-11e9-974b-aedb4989c7ab.gif)

This is what I could expect instead

```js
/**
 * 
 * @param {Object} param0
 * @param {String} param0.region <- cursor jump to each of this
 * @param {String} param0.institution
 * @param {String} param0.type 
 */
```

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/27942
