### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by AltieriR** [microsoft/vscode#76599]
Issue Type: <b>Bug</b>

Ctrl + F - Search bar is throwing an error to special characters like (/):

E.g.: On typing .update(
"Invalid Regular Expression /.update(/: Unterminated group".

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.10586

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-css-formatter|aes|1.0.1
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|29.2.0
auto-close-tag|for|0.5.6
quokka-vscode|Wal|1.0.233

</details>

**Comment by roblourens** [comment]
This is correct, either escape it with \ or deselect the regex mode button
