### ISSUE TITLE
TAB key switches to Global scope automatically

### ISSUE THREAD

**Issue by ManojCologne** [microsoft/vscode#76593]
Issue Type: <b>Bug</b>

When using the TAB key to indent the code the functionality switches to Global scope.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (14.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.23.1

</details>

**Comment by dbaeumer** [comment]
@ManojCologne can you please provide and example of what happens and what you expect to happen.

**Comment by dbaeumer** [comment]
And does this happen with all extensions disabled (start code with `--disable-extensions` from a terminal)

**Comment by ManojCologne** [comment]
Expected behavior - TAB key should insert 2 or 4 spaces in the code edit section (depending on the indent size setting).
Observed behavior - TAB key functions at the IDE level that means pressing on TAB key the doesn't indent the code rather it highlights the "Explorer", "Search..." tabs.

**Comment by dbaeumer** [comment]
Not reproducible for me.

**Comment by rebornix** [comment]
@ManojCologne can you reproduce this issue when setting `editor.accessibilitySupport` to `off`?
