### ISSUE TITLE
Lines are cut with debug.console.wordWrap

### ISSUE THREAD

**Issue by Schnielz** [microsoft/vscode#76595]
Issue Type: <b>Bug</b>

I  was realy looking forward for the new option debug.console.wordWrap.
Unfortunatly I can not scroll to the end of the longest lines. The new scrollbar ends before the entire line is visible.

![grafik](https://user-images.githubusercontent.com/14457580/60664039-2d44a300-9e61-11e9-81a8-d559751e855d.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/76093
I plan to investigate this week. Next release should have this improved. Sorry about that!

**Comment by isidorn** [comment]
Actually I will push a fix as part of the recovery release. So this should work after we release the recovery release in 5-6 days. Thanks
