### ISSUE TITLE
Font display broken in Extensions detail view after upgrade to 1.36

### ISSUE THREAD

**Issue by stsa-bc** [microsoft/vscode#76591]
After the upgrade to 1.36 the font used in Extension detail view (and in some extensions) is a serif font, probably the chromium default one. Installing fonts-ubuntu from Debian buster fixes the issue.

Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-4-amd64

- VSCode Version: 1.36
- OS Version: Debian Stretch

Steps to Reproduce:

1. Do not have Ubuntu fonts installed
2. Upgrade to 1.36

Does this issue occur when all extensions are disabled?: Yes

**Comment by charliedua** [comment]
Tried to reproduce the issue with not having fonts-ubuntu installed

**System info**: 18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- [x] This issue is reproducable

When trying to reproduce the issue, in the extension detail page only the **font changed** and that was  completely **expected behaviour** as vscode uses the available **system fonts**, here it couldn't find that nice font we always see, but it found the other font installed on your system and used it, however nothing of sort seemed broken.

If you can, please **share more** on this issue as the **word broken is too vague**.

**Comment by stsa-bc** [comment]
Sorry, broken was clearly not the best word to choose, but then, English is not my mother tongue.
I made some screenshots that should help clarify the matter:
### Release notes with fonts ubuntu installed
![VSCode_with_fonts_ubuntu](https://user-images.githubusercontent.com/33422090/61031947-cbd08700-a3c0-11e9-941a-8fd3b962f491.png)
### Release notes without fonts ubuntu installed
![VSCode_without_fonts_ubuntu](https://user-images.githubusercontent.com/33422090/61031962-d0953b00-a3c0-11e9-9ae1-728ec06d8b8b.png)

While not exactly broken, the font displayed isn't even of the same font-family and feels very out of place. With 1.35 display was fine as a non-serif font similar to Arial would be displayed.

**Comment by charliedua** [comment]
I am pree sure [this line](https://github.com/microsoft/vscode/blob/332aaba6ded659529a7ae91e6ae0071ff1ef6ae8/src/vs/workbench/browser/media/style.css#L20) is causing the font change mentioned
```css
.linux { font-family: "Ubuntu", "Droid Sans", sans-serif; }
```
here the font `Ubuntu` and `Droid Sans` both are not available so it goes to `sans-serif` Hence the font that appears.

**Comment by hey24sheep** [comment]
Can't we add fonts as a part of the electron app, like we do on web app?

**Comment by charliedua** [comment]
Yes it is completely possible. @mjbvz your thoughts?

**Comment by hey24sheep** [comment]
Great, if we could do that. I would like to contribute, I would need some starting help though :)

**Comment by Nowaker** [comment]
Also affects Arch Linux.

![image](https://user-images.githubusercontent.com/611746/62344512-e7a4e580-b4b3-11e9-888a-0e476dbd2b73.png)

**Comment by Nowaker** [comment]
Installing `ttf-ubuntu-font-family` package on Arch Linux fixes the problem but... it changes the font **everywhere**.

![image](https://user-images.githubusercontent.com/611746/62344637-6a2da500-b4b4-11e9-8029-67709a5c6dc0.png)

I don't like Ubuntu font so I removed it.

It should be possible to set a custom font. Ideally, VS Code should use the default font of the desktop environment (e.g. KDE, Gnome).

**Comment by mjbvz** [comment]
Are you still seeing this issue in VS Code 1.47+? There's only be two upvotes on this over the past year
