### ISSUE TITLE
User data: migrate Backups, Workspaces, user state into %APPDATA%/User

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76590]
Today we have a bit of a mix in our `%APPDATA%` folder: a lot of stuff is going into the `%APPDATA%/User` folder but a few things outside are not:
* Backups
* Workspaces
* `storage.json`

I think we should do a migration step for a while to consolidate this data under the `User` folder. 

@Tyriar also happy for your input given you are the author of https://github.com/Microsoft/vscode/issues/3884

**Comment by bpasero** [comment]
I removed part of the description. Specifically we can leave the backup format as it is today where we have a folder per scheme, even though that is not really needed if we take the hash of the full resource.

**Comment by Tyriar** [comment]
Is this just cleanup or is there a bigger problem with the folders being there?

**Comment by bpasero** [comment]
@Tyriar I think it would bring us closer to a model where all of our data goes into one folder "User" and the rest is a) chrome stuff and b) some caches that can be ignored.

E.g. we could then start to think about nuking anything which is not in "User" to ensure a cleaner startup (e.g. no traces of previous chrome stuff around).

**Comment by Tyriar** [comment]
:+1: sounds good

**Comment by gudvinr** [comment]
What about extensions? Why is the extensions directory located in `~/.vscode/` rather than `%APPDATA%/User`?

**Comment by bpasero** [comment]
I think very much in the beginning we were worried that Windows would automatically roam the stuff that is inside `%APPDATA%` so we decided to not put extensions in there. I also find it a bit unfortunate that we require 2 folders on disk to store stuff.

**Comment by byyxx128** [comment]
As mentioned in #3884, the optimum location for extensions is `%LOCALAPPDATA%` rather than `%APPDATA%`.
I expect to see the transition during my lifetime. 😁
