### ISSUE TITLE
Code thinks that there is a new update when changing the system date

### ISSUE THREAD

**Issue by whyseman** [microsoft/vscode#76605]
- VSCode Version: 1.36
- OS Version: Windows 10 Version 1903 (OS Build 18362.175)

Steps to Reproduce:

1. Change your system date to a future date, say the year 2020 or 2021.
2. Start VS Code.
3. Watch the cog icon at the bottom left in VS Code. An icon that looks like a "clock" should appear on the cog. Hover over the cog and it should display a message: "Manage - New Code update available."

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Are you sure this reproduces all the time and that you really did not have an update? AFAIK, we don't check for timestamp at all when checking for updates.

**Comment by whyseman** [comment]
@joaomoreno I'm sure. Checked couple of times.
