### ISSUE TITLE
1.36 is incredibly "bright"

### ISSUE THREAD

**Issue by AngellusMortis** [microsoft/vscode#76604]
- VSCode Version: 1.36
- OS Version: Windows 10 1903 (Slow Ring Build 18362.175)

Steps to Reproduce:

1. Open VS Code

Does this issue occur when all extensions are disabled?: Yes

I tried this with both VS Code stable and my VS Code Insiders install (mostly since I had not updated the Insiders install since before 1.35).

Before:
![Code_-_Insiders_2019-07-04_09-34-17](https://user-images.githubusercontent.com/490848/60670654-358be680-9e3f-11e9-8bc4-ae7ad6e96515.png)

After:
![Code_-_Insiders_2019-07-04_09-34-29](https://user-images.githubusercontent.com/490848/60670657-36bd1380-9e3f-11e9-9538-27cd59e32096.png)

Both of these images are the same theme and everything. I also have an HDR monitor connected, but VS Code is not running on the HDR monitor. The HDR monitor makes it a _little_ better, but it still far brighter than on 1.35.

**Comment by bpasero** [comment]
@AngellusMortis any difference if you run from the command line: `code --force-color-profile=srgb`?

**Comment by AngellusMortis** [comment]
Yep, that actually fixes it.
