### ISSUE TITLE
Diff view needs more UX affordance when tabs enabled

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7661]
Enable tabs and open a diff view. Notice the following:
1. Diff view is rendered the same as a regular editor view - we should add some affordance so there is a clear difference between the two when looking at the tab header
2. There are no more top level diff view actions - this is fine as this space is now occupied by tabs - but this actions should be present in the secondary top level actions

![screen shot 2016-06-14 at 15 47 55](https://cloud.githubusercontent.com/assets/1926584/16045118/65119c5e-3247-11e6-8a10-74447f6420dd.png)

**Comment by bpasero** [comment]
@isidorn all diff actions should show up in the context menu of the tab.

I agree though that we need to add something to the label to make it clear this is a diff.

**Comment by isidorn** [comment]
Ok now I found the actions in the context menu - and I agree it makes sense that they live there. It is just me as a user I was acustomed to have those actions in the corner. And I think it will be hard for users to find these actions in their new location.

No idea how to solve this, just saying that some users might not be happy. But it is fine for now :)

**Comment by bpasero** [comment]
You get a LOT when you enable tabs, but you cannot have everything ;)

**Comment by isidorn** [comment]
Not sure if HEAD is needed:
* just occupies space
* caps lock -> unnecessery draws attention
* I think it will be obvious to users if you just show lalalal.txt <-> lalalal.txt

**Comment by bpasero** [comment]
I leave that up to @joaomoreno if he has other ideas how to represent this:

![image](https://cloud.githubusercontent.com/assets/900690/16076061/df564c8a-32f1-11e6-98c2-2bf44a127836.png)
