### ISSUE TITLE
After last update search in project is very very very very slow

### ISSUE THREAD

**Issue by mikpetr** [microsoft/vscode#76610]
Issue Type: <b>Bug</b>

After last update search in project is very very very very slow. Plase make a way to downgrade app, as in last updates every time simething breakes!

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|-psn_0_5641569|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
auto-close-tag|for|0.5.6
vetur|oct|0.21.1
code-spell-checker|str|1.7.17

</details>

**Comment by dbaeumer** [comment]
@mikpetr just to clarify: you use search in files from the side bar?

**Comment by mikpetr** [comment]
@dbaeumer yes, I am searching from side bar in the project. There are some large files but it worked instantly in previews version and now it is really slow. After clicking on "X" close button to remove item from results list I have to wait several seconds before it will be removed. The same thing in previews version was working instantly.

**Comment by roblourens** [comment]
> After clicking on "X" close button to remove item from results list I have to wait several seconds before it will be removed

Is this while the search is running or after it's finished? 

Can you check the process explorer (help menu) to see if some vscode process is using high cpu to slow this down?

**Comment by saschanaz** [comment]
My task manager shows searching from sidebar on my gecko-dev project causes Antimalware Service Executable to consume 70%+ of my Ryzen 2600X, so that may be a bottleneck.

* Search query: `optional`
* Files to include: `dom/webidl/*.webidl`

I'm on Windows 10 Insider build 18922 so the result can be different on stable version of the OS.

**Comment by nicolasbadia** [comment]
For me it looks like this issue started as soon as I started to set a regex to "files to include". In my case the search  take a few minutes to complete and eat all my CPU.
Now, even if I do not set anything to "files to include", I have the issue.
Here is the process:

`263	246	94687	             /Applications/VSCodium.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --case-sensitive --max-filesize 17179869184 --no-ignore --pcre2 --fixed-strings --no-config --no-ignore-global --json -- my_search .`

**Comment by roblourens** [comment]
Please open your own issues. Windows defender is a known issue. If you do not select the "use exclude settings" button it will search more files and be slower. No response from OP so closing
