### ISSUE TITLE
TERMINAL: kills open terminals when switching, but does not kill web server 

### ISSUE THREAD

**Issue by georgebatalinski** [microsoft/vscode#76613]
- VSCode Version: 1.36.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. File -> Open Folder 
2. Run a webserver in the integrated terminal - e.g. (ng serve)
3. Switch to another project (File -> Open Recent -> Project #2)
4. Switch back to project from STEP #1
5. Result: You get a brand new terminal and you try to run the (ng serve) 
`Port 4200 is already in use. Use '--port' to specify a different port.`

 On Windows, I have to do the following:
taskkill -f /pid 16868

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you run `ver` in cmd and paste the output?

**Comment by georgebatalinski** [comment]
Microsoft Windows [Version 10.0.15063]

**Comment by georgebatalinski** [comment]
**I checked the following:** 
1. I ran `python -m SimpleHTTPServer 8000` and if I do the above steps - its works as expected 
2. If I ran the code manually `node-pty` using the `ptyProcess.kill()` it works as expected with `ng serve`

```
var os = require('os');
var pty = require('node-pty');

var shell = os.platform() === 'win32' ? 'powershell.exe' : 'bash';

var ptyProcess = pty.spawn(shell, [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  process.stdout.write(data);
});

ptyProcess.write('ng serve\r');


setTimeout(()=>{
	ptyProcess.kill();
}, 50000);
```


Let me know your thoughts as in where the issue could be 
Thank you so much

**Comment by Tyriar** [comment]
The terminal uses a new backend system in newer Windows 10 (1903+), you should update as that version is super old.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
