### ISSUE TITLE
1.36 broke custom Tasks to run on split terminal if no terminal is active

### ISSUE THREAD

**Issue by felipe-spengler-osf** [microsoft/vscode#76611]
Hi

I have been using a custom task to group some tasks that I run daily on a split terminal. This was possible since version 1.31.1 introduced the "group" attribute on presentation.

**Update**: I usually kill any terminal before running this, and today with update 1.36 this stopped working, tasks run on dedicated terminal and VSCode shows a tooltip with "No enough space to split terminal" (which is totally nonsense as I have a 2560px display), and when I kill the terminals an error "Should never try to resolve undefined" appears and also on DevTools.

**If I already have a terminal open and run my custom Task, then it works fine as before!**

This is my tasks config:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "DW Utils Watch",
            "type": "shell",
            "command": "dw-utils watch",
            "problemMatcher": [],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": false,
                "group": "GroupA"
            }
        },
        {
            "label": "Watch-Vue",
            "type": "shell",
            "command": "gulp watch2",
            "problemMatcher": [],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": false,
                "group": "GroupA"
            }
        },
        {
            "label": "Watchers",
            "type": "shell",
            "problemMatcher": [],
            "dependsOn": [
                "DW Utils Watch",
                "Watch-Vue"
            ]
        }
    ]
}
```

- VSCode Version: 1.36.0 (user setup)
- OS: Windows_NT x64 10.0.18362

Does this issue occur when all extensions are disabled?: 
Yes

Any ideas??

Thanks

**Comment by alexr00** [comment]
@Tyriar this appears to be a timing issue. At the time that tasks gets the terminal instance, it hasn't actually been finished being created yet.

**Comment by alexr00** [comment]
The "Should never try to resolve undefined" is unrelated to the split terminal, but should also be fixed.

**Comment by alexr00** [comment]
@Tyriar it's a little hacky, but as a simple fix for the terminal splitting I can `waitForTitle` on the first terminal. It seems that be the time it has a title it also has a height and width.

**Comment by alexr00** [comment]
To verify kill all your integrated terminals then run task three:
```
        {
            "label": "one",
            "command": "sleep 11",
            "type": "shell",
            "problemMatcher": [],
            "presentation": {
                "group": "one"
            }
        },
        {
            "label": "two",
            "command": "sleep 12",
            "type": "shell",
            "problemMatcher": [],
            "presentation": {
                "group": "one"
            }
        },
        {
            "label": "three",
            "type": "shell",
            "problemMatcher": [],
            "dependsOn": [
                "one",
                "two"
            ]
        },
```
Verify that you see tasks one and two in split terminals next to each other and that there are no task related errors in the console.

**Comment by bpasero** [comment]
Verified on Linux.
