### ISSUE TITLE
Word based suggessions does not respect word separators

### ISSUE THREAD

**Issue by mainakk** [microsoft/vscode#76614]
- VSCode Version: 1.36.0
- OS Version: Windows 10 Version 19.03 (OS Build 18362.175)

Steps to Reproduce:

1. Remove '/' and '-' from editor.wordSeparators setting.
2. Edit a plain text file, words like snacks/fruits/green-apple are not shown in the suggestion list.

![word_suggestions](https://user-images.githubusercontent.com/3246658/60676218-f6d84980-9e9b-11e9-837f-e05d51c456e0.png)

This is useful for editing Scheme language files for which word definition from language is not available.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That's the design, word based suggestions honour the language specific word definition
