### ISSUE TITLE
Workbench tree first indent guide overly visible after opening a window

### ISSUE THREAD

**Issue by coderpatsy** [microsoft/vscode#76617]
- VSCode Version: 1.36.0
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Set `workbench.tree.renderIndentGuides` to `onHover` or `always`
2. Open a new workspace window

Does this issue occur when all extensions are disabled?: Yes

The first visible guide in the tree is overly visible on first load. and always shows irrespective of `onHover`.

![vscode_very_guided](https://user-images.githubusercontent.com/13140934/60679587-5fe0a280-9e45-11e9-94a8-4877b026119b.png)

When you cause it to redraw by toggling that folder or a folder above it in the list, then the guides are drawn normally and respect `onHover`.

![vscode_regular_guided](https://user-images.githubusercontent.com/13140934/60679636-8dc5e700-9e45-11e9-85fc-00f1a22fc4ad.png)

**Comment by joaomoreno** [comment]
This is as designed. The guide of the currently selected file's containing folder is highlighted. Click around other files and you'll see what I mean.
