### ISSUE TITLE
Make it easier to debug missing parentheses

### ISSUE THREAD

**Issue by 12people** [microsoft/vscode#76622]
Issue Type: <b>Feature Request</b>

When my parentheses are off while writing Dart code, it's not clear where I should add or remove them. It can be frustrating trying to debug.

(Making things worse, VSCode doesn't add parenthesis when there's already a parenthesis to the right of a cursor. It often happens that I do not notice that a parenthesis that I meant to add wasn't added because of this.)

Please make it easier to find where to put a missing parenthesis.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.0.0-20-generic snap

**Comment by dbaeumer** [comment]
Please file this request against the VS Code Dart extension here: https://github.com/Dart-Code/Dart-Code

**Comment by 12people** [comment]
Done: https://github.com/Dart-Code/Dart-Code/issues/1832

**Comment by dbaeumer** [comment]
Thanks!
