### ISSUE TITLE
Rendering glitch for tab headers custom scrollbar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7662]
Sorry I do not have repro steps but happened to me 2 times so far. Both times it happened when I switched back to vscode from some other active window.

Opening a new tab triggers a new layout which fixes the brokeness

![screen shot 2016-06-14 at 15 54 03](https://cloud.githubusercontent.com/assets/1926584/16045357/59b6a394-3248-11e6-87b9-5e5173e67fb8.png)

**Comment by bpasero** [comment]
I have seen this once I think and it is likely our custom scrollbar. When you are in this state again, lets dev tools that guy.

**Comment by bpasero** [comment]
@isidorn let me know if you still see this with todays insider build.

**Comment by isidorn** [comment]
I still see it with latest

![screen shot 2016-06-16 at 16 40 53](https://cloud.githubusercontent.com/assets/1926584/16120810/2b2858ac-33e1-11e6-80be-2c38e8955d34.png)

**Comment by bpasero** [comment]
Pushed something that maybe has an impact, please check tomorrow again in insiders.

**Comment by bpasero** [comment]
@isidorn did it happen?

**Comment by isidorn** [comment]
@bpasero not today

**Comment by bpasero** [comment]
ok, please reopen if it still happens.
