### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by nishantp63** [microsoft/vscode#76621]
Issue Type: <b>Bug</b>

sometimes  when i close the vs code ,it automatically starts to update visual studio code and could not be able to update it and delete the entire vs code from the system.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (12.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
code-runner|for|0.9.11
html-snippets|gey|0.2.3
live-html-previewer-v2|kos|0.1.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joaomoreno** [comment]
Please fully uninstall and reinstall VS Code.
