### ISSUE TITLE
Do not classify snakemake files as Python source code

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#76624]
https://github.com/microsoft/vscode/commit/3cf704d2b88a415ef931f63d2c1efbe7fe479d94 added snakemake files as Python files. Unfortunately they are not valid Python source and so they get flagged by the Python extension as syntactically invalid (i.e. Microsoft/vscode-python#6438). It's probably best to not flag them as Python source files.

**Comment by timtroendle** [comment]
It's true that Snakefiles aren't valid Python, but first this extension was working just fine for me and second, there is unfortunately no alternative at the moment. If others want to use the extension for Snakefiles like me, here's the config that you'll need:

```json
"files.associations": {
    "Snakefile": "python",
    "*.smk": "python"
}
```
