### ISSUE TITLE
Screen flashing white

### ISSUE THREAD

**Issue by fcoramos** [microsoft/vscode#76623]
Issue Type: <b>Bug</b>

Two or three white flashes in the screen happens when browsing the code or changing the focus of the active code window on a HP Spectre X360 with high resolution screen 3840x2160.

Version: 1.36.0 (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.800.0
vscode-eslint|dba|1.9.0
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
docker-explorer|for|0.1.6
terminal|for|0.0.10
vscode-mysql|for|0.4.0
crane|Hvy|0.3.8
phpcs|ika|1.0.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-docker|ms-|0.6.4
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.11.6
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.
