### ISSUE TITLE
Menus do not respect GTK theme colors

### ISSUE THREAD

**Issue by teohhanhui** [microsoft/vscode#76629]
Issue Type: <b>Bug</b>

The menus (and by extension the menu items in them) don't have the correct colors from the GTK theme. The menubar looks alright.

It's not the theme's fault as I've checked and the menus look correct in `gtk3-widget-factory`.

![Screenshot from 2019-07-04 20-52-45](https://user-images.githubusercontent.com/548843/60684396-ddd09800-9e9d-11e9-8c1c-ce9674d05843.png)
![Screenshot from 2019-07-04 20-52-58](https://user-images.githubusercontent.com/548843/60684397-ddd09800-9e9d-11e9-96d5-eb06d964830e.png)
![Screenshot from 2019-07-04 20-53-20](https://user-images.githubusercontent.com/548843/60684398-ddd09800-9e9d-11e9-9974-45a5c0428f54.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.15-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.45GB (5.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
latte|Kas|0.1.1
vscode-paste-and-indent|Rub|0.0.8
cucumberautocomplete|ale|2.14.0
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|29.2.0
vsc-material-theme-icons|equ|1.0.6
varnish-vcl|flo|0.1.3
vscode-pull-request-github|Git|0.8.0
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
restructuredtext|lex|110.0.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
vscode-yaml|red|0.4.1
vscode-qt-for-python|sea|0.3.0
gitconfig|sid|2.0.0
shellcheck|tim|0.6.0
twig|wha|1.0.2

</details>

**Comment by dbaeumer** [comment]
Looks like the native menu (not the VS Code custom one).

**Comment by bpasero** [comment]
@teohhanhui did it work good in our previous release `1.35`?

**Comment by teohhanhui** [comment]
I've tested with a previous version and it's the same.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 5.1.15-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1898)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.45GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
latte|Kas|0.1.1
vscode-paste-and-indent|Rub|0.0.8
cucumberautocomplete|ale|2.14.0
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|29.2.0
vsc-material-theme-icons|equ|1.0.6
varnish-vcl|flo|0.1.3
vscode-pull-request-github|Git|0.8.0
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
restructuredtext|lex|110.0.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
vscode-yaml|red|0.4.1
vscode-qt-for-python|sea|0.3.0
gitconfig|sid|2.0.0
shellcheck|tim|0.6.0
twig|wha|1.0.2


</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
