### ISSUE TITLE
watcherService high CPU and memory usage with recursive symbolic links

### ISSUE THREAD

**Issue by scarvalhojr** [microsoft/vscode#76626]
- VSCode Version: 1.36.0
- OS Version: MacOS Mojave 10.14.5 (18F132)

I came across this bug while trying to work on a repository containing several recursive symbolic links to parent directories.

The repo in question is https://github.com/ceph/ceph. The `qa/suites` directory contains a number of sub-directories with symbolic links pointing back to it. Opening this directory alone in VSCode is enough to send watcherService into a mad run. I suspect the relatively large number of files in this directory is part of the problem.

This issue is somewhat related to [File watcher resulting in high CPU use on Mac/Linux for large folders - Issue #3998](https://github.com/Microsoft/vscode/issues/3998).

However, the problem here is not the large number of files (which is actually relatively small in this case - 1,115 files), but the fact that the directories are also recursively linked, which appears to make `watcherService` believe there are a lot more files to watch (see below how 58,393 files are reported). Ideally `watcherService` should be able to detect circular references to avoid trying to watch too many files.

Steps to Reproduce:
1. git clone https://github.com/ceph/ceph.git
2. code ceph/qa/

Does this issue occur when all extensions are disabled?: Yes

Result:

`watcherService`'s CPU and memory consumption goes out of control for several minutes, e.g.:

```
~ > code --status
Version:          Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS Version:       Darwin x64 18.6.0
CPUs:             Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)
Memory (System):  16.00GB (0.04GB free)
Load (avg):       34, 57, 30
VM:               25%
Screen Reader:    no
Process Argv:     qa/
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     enabled
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    66	 73254	code main
    0	    33	 73291	   gpu-process
    0	    82	 73299	   window (qa)
    0	    49	 73331	     extensionHost
  205	  2425	 73332	     watcherService
    0	    33	 73333	     searchService
    0	    66	 73356	   shared-process
    0	     0	 73566	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (qa)
|    Folder (qa): more than 58393 files
|      File types: py(17108) sh(16046) yaml(15833) t(1716) c(916)
|                  gitignore(916) supp(658) DS_Store(658) ini(658)
|                  template(312)
|      Conf files: makefile(1194)
```

Workarounds:

To stop `watcherService` going mad either:
1. simply remove the link `qa/suites/.qa`
2. include `**/qa/suites/**` in `files.watcherExclude` setting

**Comment by bpasero** [comment]
@scarvalhojr would be great if you could report this to https://github.com/paulmillr/chokidar with a standalone sample. We are using that watcher after all.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
