### ISSUE TITLE
Loading C++ header hangs VSCode

### ISSUE THREAD

**Issue by WoLfulus** [microsoft/vscode#76628]
## Description

After opening a C++ header file, VSCode hangs with 100% CPU usage on main window.
The problem is happening with FBXSDK 2019 header files.

## Version

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

## Steps to Reproduce

1.  Open a header file

Take for example: 
https://github.com/komastar/DX11BASE/blob/master/DX11Base/DX11Base/FBX_SDK/2019.0/include/fbxsdk/core/math/fbxaffinematrix.h

## Extensions disabled

It does occur with extensions disabled.

## Related

I found this #74023, maybe it's related?

**Comment by dbaeumer** [comment]
@WoLfulus can you provide an example header files that shows this.

@alexr00 assigning to you since it happens with all extension disabled.

**Comment by alexr00** [comment]
I can repro with the provided example, thanks!

**Comment by alexr00** [comment]
It looks like this is fixed in master.

**Comment by WoLfulus** [comment]
Awesome! Thanks ;)
