### ISSUE TITLE
[json] confusing error message when schema can not be loaded

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#76633]
After having updated to the latest VS Code version (1.36.0) on a machine with no Internet access a few moments ago I noticed that VS Code is now regularly throwing JSON exceptions.

![image](https://user-images.githubusercontent.com/9283914/60685657-91d52180-9ea4-11e9-86bd-de364b9804ef.png)

**Comment by aeschli** [comment]
It's not really crashing, just a confusing message when a schema can not be loaded.
@SetTrend Can you confirm? Or do you really see the JSON server crash?

**Comment by octref** [comment]
Would be fixed by #76905, but we need to verify.

**Comment by aeschli** [comment]
To verify:

create a JSON:
```
{
	"$schema": "https://schema"
}
```

Verify that the error no longer mentions `'vscode/content` unexpectedly failed`

Depending on the site, the 404 errors could still be improved, but this was the minimal fix to what we had before.

**Comment by jrieken** [comment]
Seeing a ENOTFOUND error now, adding verified-label

<img width="552" alt="Screenshot 2019-07-09 at 10 39 04" src="https://user-images.githubusercontent.com/1794099/60872885-c85cc480-a235-11e9-8e90-ba9b30cff158.png">

**Comment by SetTrend** [comment]
@aeschli , @jrieken 👍

Here's another confusing error presented when no Internet connection is available:

![JSON schema could not be loaded](https://user-images.githubusercontent.com/9283914/61075542-7f199a00-a41a-11e9-9ecc-1145e52dd826.png)
