### ISSUE TITLE
Issues with debugging with Node.js since "June 2019 (version 1.36)"

### ISSUE THREAD

**Issue by Luaqs** [microsoft/vscode#76636]
VSCode (Insiders) Version: 1.36
OS Version: Windows 10 Pro (version 1903)

Steps to Reproduce:

1. Create a launch configuration, in a Node.js project, with the default "Node.js: Launch Program". I use TypeScript, so I have it run with a preLaunchTask that builds my code before it runs.
2. Run the newly generated "Launch Program" configuration, if you have a preLaunchTask then that will run and afterward the session will shut down.

This is what happens to me: https://gyazo.com/df81268eecdbd09afeebab25fa3b60ca
In the GIF I have the toolbar in the top right corner, you can see it disappear before the program has a chance to run, nor does the Debug Console output anything.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ankon** [comment]
I think I'm having the same issue: Debug sessions don't start with NodeJS. In my case I do not have a preLaunchTask, and instead use ts-node/register:
```jsonc
		{
			"type": "node",
			"request": "launch",
			"name": "restore (master)",
			"program": "${workspaceFolder}/scripts/restore.ts",
			"runtimeExecutable": "node",
			"runtimeArgs": [
				"-r", "ts-node/register",
				"--inspect-brk", "9229"
			],
			"port": 9229,
			"env": {
				"TS_NODE_FILES": "true",
				"LOG4JS_CONFIG": "${workspaceRoot}/scripts/log4js.json",
			},
			"args": [
                            // stripped
			],
			"cwd": "${workspaceFolder}",
			"smartStep": false
		},
```

I tried both with explicitly adding `--inspect-brk`/`port` and without, no change. 
I am not sure where to look for output really, everything is just "silent".

**Comment by weinand** [comment]
@Luaqs does it make a difference if you comment out the "preLaunchConfig" (after having built your project at least once manually)?

**Comment by isidorn** [comment]
I know there were some issues with tasking not being found @alexr00 would know more.

**Comment by alexr00** [comment]
It looks like @ankon is having the issue without any `prelaunchTask`. I'm not aware of any problems with any existing problems with tasks not being found. It sounds like the task is found and run, but that it is run out of order with the debug.

**Comment by weinand** [comment]
I'm not sure that @ankon 's issue is related at all.

**Comment by alexr00** [comment]
Based on the gif from @Luaqs the debug toolbar does show. I second this question:

> @Luaqs does it make a difference if you comment out the "preLaunchConfig" (after having built your project at least once manually)?

**Comment by weinand** [comment]
Debugging is broken in Insiders. We are investigating.

**Comment by Luaqs** [comment]
For me; no it does not make a difference with or without the preLaunchTask. Either way it stops before running.

**Comment by weinand** [comment]
And what version of VS Code are you using? You said Insiders above. 
Do you see that problem in Stable too?

**Comment by Luaqs** [comment]
I have not tried Stable, allow me to do that.

**Comment by Luaqs** [comment]
I am _not_ having the problem in Stable.

**Comment by weinand** [comment]
Ok. Good.
We know that debugging is broken in Insiders and we will wait with further investigation until the next Insiders...
