### ISSUE TITLE
No source control providers registered

### ISSUE THREAD

**Issue by therblack** [microsoft/vscode#76630]
Issue Type: <b>Bug</b>

When using Remote: SSH I get "No source control providers registered" in the 'Source Control' activity section

* worked until the most recent update (yesterday or so)
* works on windows
* there is an git icon that I can press to init a repo
* git works in the terminal
* gitlense works

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 3.10.0-862.14.4.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.66GB (9.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sdpsvrwm0303|
|OS|Linux x64 3.10.0-862.14.4.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (56 x 1928)|
|Memory (System)|503.62GB (167.80GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0

</details>

**Comment by therblack** [comment]
Just to confirm, I went back to the the may release and that works fine

**Comment by elvishp2006** [comment]
I got the same problem after install the last update.

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by therblack** [comment]
I had to install a previous version of code, so I can't answer exactly. However, I did do a git init by clicking the button in the source providers screen, and the git log looked normal (it either created a repo or said it was reinitializing an existing repo)

I did look at the git log and saw nothing untoward

Thanks

**Comment by oligray** [comment]
I have this issue too, when opening VS Code this morning  the source control explorer window states 'No source control providers registered'. It was working yesterday - and my git repo is still there because I am using the Terminal window to workaround the issue with git commit/ push etc. Version 1.36.0 on Ubuntu. In addition it seems to be repo specific, I can close and re-open VS with another project and it's working fine still.

**Comment by joaomoreno** [comment]
I'd like to see the full contents of `Git: Show Git Output`, please.

**Comment by oligray** [comment]
It seems to be intermittent, the Project is back to normal after a reboot. I will post the results from above when it happens again.

**Comment by joaomoreno** [comment]
OK let me know.

**Comment by therblack** [comment]
So having downgraded, I upgraded to 1.36.1 and the issue remains.  The output from the git log is:

Looking for git in: /home/pdeboe/local/bin/git
Using git 2.14.2 from /home/pdeboe/local/bin/git
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /opt/bns)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir

**Comment by DianaNites** [comment]
Same issue, and same output. Just a bunch of `git rev-parse` and an error or two.
The same commands work fine when used in the terminal, though.

**Comment by krasi-georgiev** [comment]
Same problem:

```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-17-generic
```


Here is the output of Git show

```
Looking for git in: git
Using git 2.19.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
```

**Comment by joaomoreno** [comment]
Is the repository in a symlink, or uses symlinks?

**Comment by krasi-georgiev** [comment]
nope a simple holder

**Comment by joaomoreno** [comment]
@krasi-georgiev 
Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by krasi-georgiev** [comment]
inside works fine, when is it scheduled for a release?

**Comment by krasi-georgiev** [comment]
all that said the issues is intermittent so might appear in insider as well so need to use for a while to confirm.

**Comment by joaomoreno** [comment]
Great. Let me know if they come back.

**Comment by therblack** [comment]
Things are also working for me using insiders
