### ISSUE TITLE
Symbols in URL fragment should not be encoded

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#76635]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Ctrl+Click on a link with symbols in the URL fragment (see code below).

```ts
/**
 * http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CSharpCompilationOptions.cs,20
 */
function test() {}
```

**Expected result:**
`http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CSharpCompilationOptions.cs,20`.

**Actual result:**
`http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp%2FCSharpCompilationOptions.cs%2C20`

For this particular website, the mangled link results in users viewing the index page, which makes the link completely useless. As far as I am aware, the symbols `? / : @ - . _ ~ ! $ & ' ( ) * + , ; =` are permitted in URL fragments, and don't have to be percent-encoded.

VS Code version: Code - Insiders 1.36.0-insider (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T08:00:29.662Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/76606
