### ISSUE TITLE
Reveal In Explorer and shortcut broken

### ISSUE THREAD

**Issue by rsxdalv** [microsoft/vscode#76639]
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Show current file in side explorer (CTRL + SHIFT + E for me)
2. Reveal that file in explorer (SHIFT + ALT + R for me)

What used to happen forever minus a few days ago - I open the file.
What happens now - I'm searching for files with 'r' in them.

I'll see if the issue disappears on its own, but for now I am having it in all VSCode windows I am using.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Duplicate of #76369 which will be fixed in the upcoming recovery release.

**Comment by rsxdalv** [comment]
Thank you!

**Comment by gjsjohnmurray** [comment]
@rsxdalv - happy to help. Please close this issue.
