### ISSUE TITLE
Can’t add project to workspace by drag folder

### ISSUE THREAD

**Issue by linggan100** [microsoft/vscode#76649]
Seen on windows 7
- VSCode Version: 1.36

Steps to Reproduce:

1.open code
2.drag folder to code workspace
3.error，like the image：
![image](https://user-images.githubusercontent.com/9244771/60692625-88ca6b80-9f09-11e9-8024-393b8a0a0df2.png)

**Comment by gjsjohnmurray** [comment]
If you click that button, does it show you the contents of your .code-workspace file?

**Comment by aeschli** [comment]
Unable to reproduce. Please reopen with more information.
- After step 1, is the window open on a folder or a workspace?
- If it is already a workspace, Run `Preference: Open Workspace Configuration File` ans paste what's the content of the workspace file.

**Comment by linggan100** [comment]
Maybe it's a version problem. I reinstalled another version and it's OK again. Some versions may have problems after updating, and I hope to keep an eye on it.
