### ISSUE TITLE
Explorer gets stuck when creating a new file while the watcher removes files

### ISSUE THREAD

**Issue by AWhetter** [microsoft/vscode#76644]
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 3.10.0-693.2.2.el7.x86_64

Steps to Reproduce:

1. Start a process that keeps creating and deleting a file in the workspace root. In my real world case I have a process writing to a sqlite database, and a journal file is being written and deleted as the database is written to.
2. While the process runs, attempt to create a file in the workspace root using the Explorer in VSCode (either via the icon or by right clicking and selecting "New File").
3. When the background process deletes a file it removes the placeholder for the new file as well. The explorer gets stuck in the greyed out state and you also can't try to make a new file again using the icon because it is still disabled. You can right click and make a new file that way, but you have to wait for the process to finish deleting files before you can.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is fixed in latest, please update

**Comment by AWhetter** [comment]
Apologies for the duplicate issue and thanks for the fast feedback! :smiley:
