### ISSUE TITLE
highlight the indent guide of the region starting a the cursor position

### ISSUE THREAD

**Issue by AbrahamBrookes** [microsoft/vscode#76643]
- VSCode Version: 1.36.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new .html or .php file
2. Paste some basic markup, nesting a few elements

The margin line to the left of the selected tag is offset one tab to the left. Image:
![Capture](https://user-images.githubusercontent.com/8340776/60690287-aac3ee00-9f09-11e9-9143-3f383910fc83.JPG)
as you can see I have highlighted the `<span>` tag and the matching tag is highlighted, but the tab line - the vertical margin rule to the left of the matching tags - is indicating that I have the parent `<div>` selected. This makes understanding where you are in the nested elements quite hard, and kinda defeats the purpose of that feature at all. Here's how it works in notepad++:
![Capture](https://user-images.githubusercontent.com/8340776/60690367-4f463000-9f0a-11e9-9ea7-e262178bc018.JPG)
Kinda hard to see there, but the margin rule goes red between the span tags I have highlighted, not the parent div tags

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/49342
