### ISSUE TITLE
Ctrl + tab and Ctrl + Shift + tab behaves like in Browsers with tabs enabled

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#7664]
With tabs enabled, I think it would be nice to have <kbd>Ctrl</kbd> + <kbd>tab</kbd> and <kbd>Ctrl</kbd> + <kbd>shift</kbd> + <kbd>tab</kbd> behave like the same way as in browser. 

As we switch back and forth from browser to editor, this flow would be very helpful

**Comment by bpasero** [comment]
@sandy081 Ctrl+Tab should open quick open with a MRU list of tabs. Does it not work for you?

**Comment by sandy081** [comment]
@bpasero Yah it works.. Ctrl+Tab opens Quick open and navigates to file/tab that I last opened. That makes perfect sense without tabs. But with tabs, I felt it would be more easier to navigate and use if we have similar behavior as in browsers. 

Like Ctrl + Tab goes to next visible tab and Ctrl + Shift + Tab goes to previous visible tab.

**Comment by bpasero** [comment]
You can assign the following keybinding to get this:

	```
{
		"key": "ctrl+shift+tab",
		"command": "workbench.action.previousEditor",
		"when": ""
	},
	{
		"key": "ctrl+tab",
		"command": "workbench.action.nextEditor",
		"when": ""
	}
```

**Comment by sandy081** [comment]
@bpasero Thanks for the keybindings..

My next question would be, is it possible to enable these key bindings only when tabs are enabled?

**Comment by bpasero** [comment]
I believe so, e.g. there are already keybindings that check for config:

![image](https://cloud.githubusercontent.com/assets/900690/16046521/04a9af5e-324d-11e6-98d8-b7a8204be1f4.png).

**Comment by yisibl** [comment]
This can be used as the default configuration?

**Comment by rebornix** [comment]
I'd like to have it as default, as it's already muscle memory.

If you don't like it, I will suggest make Ctrl+Page Up and Ctrl + Page Down as the default way to navigate to tabs nearby. Just like Notepad++.

**Comment by bpasero** [comment]
What is wrong about `Ctrl+Tab` as it works out of the box?

**Comment by yisibl** [comment]
There is a problem, we should limit about switching tab in separate columns(groups)?

**Comment by bpasero** [comment]
@yisibl can you clarify what you mean? Ctrl+Tab only works in the active group and the other across groups.

**Comment by yisibl** [comment]
![VSCode tabs demo](https://img.alicdn.com/tps/TB1RfMnKpXXXXXZXpXXXXXXXXXX-790-200.gif)

@bpasero I want to have an option to control only one side of the switch.

**Comment by bpasero** [comment]
@yisibl so you want to navigate in spatial order until the end of the group is reached?

**Comment by yisibl** [comment]
@bpasero Yeah, you can consider adding an option.

**Comment by bpasero** [comment]
@yisibl I suggest you open a feature request on this.

**Comment by cvax** [comment]
@yisibl Did you ever end up making a feature request for this? I am looking for the exact same thing.

**Comment by yisibl** [comment]
@cvax Nope 😢

**Comment by cvax** [comment]
@yisibl okay, I made one for us at #15225. Please thumbs up it.
