### ISSUE TITLE
Make the debug menu bar to move anywhere. wonder why this is not corrected yet, very annoying 99% of the time.

### ISSUE THREAD

**Issue by ArunEdathadan** [microsoft/vscode#76645]
Found similar issues, but all those are closed, it's super annoying. please find a way, otherwise, this is a superb platform.

![Code_dcF7q7Elf2](https://user-images.githubusercontent.com/16814342/60691625-b8b84580-9eee-11e9-825a-eb90eb484db6.png)

**Comment by gjsjohnmurray** [comment]
AFAIK this is behaving as designed. Why do you find it 'very annoying 99% of the time'?

If it's because you find it gets it the way of your tabs and breadcrumb, have you seen how the `debug.toolBarLocation` setting allows you to dock it?
