### ISSUE TITLE
icons disappear git add/stage, activity bar, and near top-right menu

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode#76652]
Issue Type: <b>Bug</b>

Icons are invisible in multiple locations. If you hover the mouse of the invisible area, the functions are still clickable and work.

This problem occurs when using Windows VS 1.36 with Remote WSL. It does not reproduce if using VS 1.36 locally. When VS with Remote WSL is launched/loading, I can see all the icons are visible on the left activity bar. But a few seconds later, some of them become invisible as listed below.

Invisible icons include:

* Icons for GitLens, TODO, Powershell, etc. are all invisible in left activity bar
* Icons in source control to the right of filenames that add/stage files
* Icons on top right for git blame, preview markdown to the side, etc.

### Failed workarounds

* Disabling all extensions (except the WSL Remote) does not fix the issue. The git add/stage icons are still invisible. Naturally, other icons are expected to not be there since the extensions were disabled
* Changing setting workbench color theme doesn't work. I tried several different themes and the icons above continued to be invisible.
* F1 reload window failed
* Restarting the vscode application failed
* No errors in the Output tab in different categories that seem to relate.

### Images of invisibility

Each of the three categories of invisible icons I hovered over the area. You can see the tooltip correctly rendered, and if I click the action will occur.

![image](https://user-images.githubusercontent.com/679350/60693607-38d4b000-9edb-11e9-8046-2f11552c046a.png)

![image](https://user-images.githubusercontent.com/679350/60693711-9f59ce00-9edb-11e9-85f3-95a7d9e7dd4d.png)

![image](https://user-images.githubusercontent.com/679350/60693905-5eae8480-9edc-11e9-88d3-b8c7b2f19efd.png)

![image](https://user-images.githubusercontent.com/679350/60694017-dd0b2680-9edc-11e9-8aeb-de823f1f6b60.png)

### Setup

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (5.66GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
vscode-markdownlint|Dav|0.28.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
todo-tree|Gru|0.0.138
rainbow-csv|mec|1.1.1
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by dbaeumer** [comment]
@aeschli starting with you since it only happens in WSL.

**Comment by diablodale** [comment]
There was an event in which I noticed this problem appear. I *was* using code-insider until yesterday (4 July 2019). Yesterday, code-insider notified of an upgrade and I accepted --> upgraded to 1.37. I quickly experienced blocking problems in code-insider related to remote and I needed to do some immediate work rather than debug code-insider.

Therefore, I switched to normal code. Normal code also had an update and I accepted --> upgraded to 1.36. I downloaded/enabled the remote extensions. And reconfigured settings to meet the needs of my remote WSL project. It was then that I noticed the missing icons.

Later in the day yesterday, I uninstalled code-insider and removed a few *insider* folders that I found as I was working on my project. I can still do work because I can click in the invisible areas. So there is a workaround and this is not work-stoppage 😉

**Comment by rfgamaral** [comment]
I'm having the same problem since I've updated to the latest version (stable). I can also confirm - at least for me - that this is only happening with Remote WSL.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/908

If you open the dev tools (Help > Toggle Dev Tools) and go the network tab to see if there are rejected calls?

**Comment by diablodale** [comment]
@aeschli , please note that the scenario of the bug you linked is limited to only the git icons. It does not include all three of this issue's scenarios of missing icons in the git areas, activity bar, and top right toolbar.

Today I am unable to reproduce the missing icons in any of the three icon locations. I tried using the same project folders that were failing in the original post. Same WSL distro Ubuntu 18.04. I did install a few more packages in it (e.g. 'jq').

* I see no errors in the network tab of dev tools.
* This original issue post was: 5 July 2019 @ 4:40 AM GMT+2  
  Windows last boot time was: 5 July 2019 @ 9:39 PM GMT+2  
  Therefore, I have rebooted Windows.
* Code's commit sha matches. Code hasn't updated.
* Comparing versions of the extensions, the extensions haven't updated. They are the same versions.
* Windows firewall logs are not enabled, so I have no historical info.

Should I move the pictures of the two missing scenarios to issue microsoft/vscode-remote-release#908?
Should I enable any other diagnostics?

**Comment by aeschli** [comment]
Thanks for getting back. The icons in the git areas, activity bar, and top right toolbar are all related in that they are icons from remote extensions.
I've seen similar things a while a go and had the feeling it is a timing issue. The network tab can help us see how early the images are requested.

**Comment by diablodale** [comment]
I reproduced it today. I will put the console log info into the linked bug
