### ISSUE TITLE
Color theme faded/less contrast

### ISSUE THREAD

**Issue by jellythewobbly** [microsoft/vscode#76656]
- VSCode Version: 1.36.0 (1.36.0)
- OS Version: OSX Mojave 10.14.5 (18F132)

Steps to Reproduce:

1. I am using the One Dark Pro Vivid color theme together with the Material Icon Theme.
2. All the colors on VS Code seem to be faded and have less contrast after the update to version 1.36.0.
3. I will like the colors to be like they were before the update.

Before the update:
<img width="139" alt="icon-before" src="https://user-images.githubusercontent.com/39648852/60696360-fed5cf00-9f17-11e9-9bc2-6cb05474067e.png">

After the update to version 1.36.0:

<img width="143" alt="icon-after" src="https://user-images.githubusercontent.com/39648852/60696365-04331980-9f18-11e9-85d4-6ccaf0bf5c33.png">

**Comment by dons20** [comment]
Having this issue as well with almost every one of my dark themes. Currently using Super One Dark as an example.
![image](https://user-images.githubusercontent.com/3958349/60697923-d53a8a80-9eba-11e9-8cd5-308d3c0f58da.png)

**Comment by sxnaprkhr** [comment]
Same VSCode appears to be faded after updating to version 1.36

**Comment by bpasero** [comment]
Any difference running `code --disable-gpu --force-color-profile=srgb`?

**Comment by jellythewobbly** [comment]
Doesn't seem to be working for me

**Comment by gjkunst** [comment]
`code --force-color-profile=srgb` works for me with version 1.36

**Comment by dons20** [comment]
@gjkunst wow thanks for that, it worked for me as well. 
![image](https://user-images.githubusercontent.com/3958349/60841481-ee378a00-a19f-11e9-85c4-2582ddc15f2a.png)

**Comment by NewtMa** [comment]
Hi, I have the same issue. Those two command lines don't work on my Ubuntu 1804 LTS. Just wondering, have you tried Base16 Dark Monokai from Base16 theme v1.4.5 by A.D.C. ? Do you think that theme color faded?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by NewtMa** [comment]
@bpasero wow, you nailed it!!!!! Thank you so much

**Comment by jellythewobbly** [comment]
Exploration version is great. Will be closing the issue, cheers.

**Comment by bpasero** [comment]
Great, let's leave this open though until we shipped Electron 6.

**Comment by Tyriar** [comment]
This is the root cause of the issue that I've been getting reports on where the terminal is darker than the rest of the editor. The terminal and minimap (canvases) are the correct colors, everything else is wrong :tada:
