### ISSUE TITLE
Improve testing experience for VSIXes when Webpack is in play

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#76659]
VS Code now supports bundling extensions, and the documentation guides extension devs towards Webpack.  https://code.visualstudio.com/api/working-with-extensions/bundling-extension  I have an extension which imports a lot of dependencies, and the biggest benefit to me is to be able to bundle my `node_modules` into a single file with my own code.

However, not all my dependencies play nicely with Webpack.  I can work around this using Webpack's `externals` option to continue loading them from `node_modules`.  The documentation recommends that I exclude `node_modules` from packaging in `.vscodeignore`, which is where I get most of my speed boost from, but then I need to add patterns _not_ to exclude the packages I externalised (and the packages _they_ depend on... which can itself be a bit laborious).  Example:

```
node_modules/**
!node_modules/cross-spawn/**
```

However, if I do this, then what I get in the debug environment (F5) does not necessarily match what I get in the packaged environment (`vsce package/publish`).  If I forget to unignore something, then it seems that the _debug_ extension will work (because it maps the source directory which includes `node_modules`) but the _packaged_ extension will fail - with no useful diagnostic as to _why_ it failed.  And the only way I've found to determine what's wrong in the package is to:

* Build the VSIX for the real extension (call it R).
* Install the VSIX for R.
* Load a folder containing the source of another (dummy) extension (call it D).
* Debug D to launch the Extension Development Host.
* In the Extension Development Host, trigger one of R's activation event.
* If activation of R fails, e.g. due to a missing external dependency, the error is dumped to the debug console where I am editing D.  I can now inspect the error and relate it back to a location in R.

Is there a more streamlined way?  Can we have a way to have the extension packaged, and its VSIX loaded into the Extension Development Host, e.g. via a debug launch configuration?

**Comment by isidorn** [comment]
Currently it is not supported to load an Extension VSIX via a debug launch configuration, though might be an open feature request. Forwarding to @weinand to decide.

**Comment by weinand** [comment]
There are no plans to support debugging an extension VSIX directly.
The reason for this is the sad state of source maps in Webpacks.

If you know a reliable way of producing a compact Webpack with truthful source maps, I'm all in for supporting this in extension debugging.
