### ISSUE TITLE
Dart 

### ISSUE THREAD

**Issue by Apogee7** [microsoft/vscode#76653]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Performance Issue</b>

Having trouble dealing with error message:
set the program value in your launch config(bin/main.dart

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (7.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   131	  1275	code main
    0	    66	  1277	   gpu-process
    0	   147	  1296	   shared-process
    0	     0	  1615	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   262	  1546	   window (Untitled-1)
    0	   131	  1548	     extensionHost
    0	    98	  1554	       /Users/kevinjones/Downloads/dart-sdk/bin/dart /Users/kevinjones/Downloads/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.2.0
    0	    98	  1607	       electron_node tsserver.js 
    0	    66	  1611	         electron_node typingsInstaller.js typesMap.js 
    0	    49	  1608	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=1548
    0	    49	  1609	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1548
    0	    98	  1610	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=1548
    0	    82	  1613	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.2.0
vsc-python-indent|Kev|1.0.0
python|ms-|2019.6.22090

</details>

**Comment by gjsjohnmurray** [comment]
For Dart assistance I think you should submit your request at https://github.com/Dart-Code/Dart-Code/issues

**Comment by dbaeumer** [comment]
@gjsjohnmurray is right. @Apogee7 please file the issue against the Dart extension.

**Comment by Apogee7** [comment]
Understood.
