### ISSUE TITLE
git infomation layout BUG

### ISSUE THREAD

**Issue by cydiacen** [microsoft/vscode#76650]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
![Xnip2019-07-05_10-02-32](https://user-images.githubusercontent.com/11609222/60693352-8cabbd00-9f0c-11e9-8701-42b17b13f27f.jpg)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
What VSCode and OS versions?

**Comment by cydiacen** [comment]
VSCode Version：1.36.0
OS Version ： macOS Mojave 10.14.5

**Comment by cydiacen** [comment]
> What VSCode and OS versions?

VSCode Version：1.36.0
OS Version ： macOS Mojave 10.14.5

**Comment by dbaeumer** [comment]
@cydiacen the git information is very likely rendered by an extension. VS Code doesn't do this out of the box. Please report the bug against the extension first.

If this happens with all extension disabled, please ping.
