### ISSUE TITLE
Distinguish which workspace folder a symbol belongs to in Ctrl-T search for symbol (Go To Symbol)

### ISSUE THREAD

**Issue by johnnytemp** [microsoft/vscode#76661]
#### When I Ctrl-T & type `Abc` (a class) to search for a symbol, it now show 3 symbols that I cannot distinguish like this :

Abc - \<namespace> - abc.php
Abc - \<namespace> - abc.php
Abc - \<namespace> - abc.php

#### This is because my workspace have 3 folders (project), and each with the same class Abc (but in different folders on disk). Could you consider adding the workspace folder hinting like this (when the workspace have multiple workspace folders) so that I can distinguish the three?  E.g.

Abc - \<namespace> - abc.php (workspace_folder_1)
Abc - \<namespace> - abc.php (workspace_folder_2)
Abc - \<namespace> - abc.php (workspace_folder_3)

Remark: I think this scenario is quite common and so fired this request.

**Comment by johnnytemp** [comment]
For your info: I'm using "PHP Intelephense" for the symbols' intellisense.

**Comment by mjbvz** [comment]
How the results are displayed is up to the extension. Please file this issue against PHP Intelephense

**Comment by bmewburn** [comment]
@mjbvz that's not entirely true. VSCode adds the filename to the result -- `abc.php` in this case. To solve this in the extension would mean to either only show the file that matches the currently active editor folder -- it's a workspace search not a folder search though -- or to hijack the `SymbolInformation.containerName` property which usually has namespace/typename info.

**Comment by bpasero** [comment]
**Verification**
Open the workspace symbol search (`Cmd+T`) and find symbols. Verify their file path appears as part of the container description label.

**Comment by johnnytemp** [comment]
Verified the file path exists and can distinguish now.
