### ISSUE TITLE
Can not open a file by dragging when filename contains '%'

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#76669]
Issue Type: <b>Bug</b>

1. Create a file named "file_f%3A_Github_script.log" in folder 'log'.
2. Open folder 'log' in VSCode.
3. Drag file "file_f%3A_Github_script.log" into edit window from left.
4. VSCode shows the filename is "file_f:_Github_lua.log" and failed to open this file.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

Wrong filename:
![image](https://user-images.githubusercontent.com/5213431/60703284-00ad8b80-9f34-11e9-8c7d-7a420f0e77d7.png)

Correct filename:
![image](https://user-images.githubusercontent.com/5213431/60703200-bf1ce080-9f33-11e9-8ec8-2ae3e08822a9.png)

**Comment by sumneko** [comment]
![VSCode bug](https://user-images.githubusercontent.com/5213431/60703552-ae209f00-9f34-11e9-961e-76054f856dad.gif)

**Comment by gjsjohnmurray** [comment]
Maybe related to #76506 which is expected to be fixed in the upcoming June recovery build.
