### ISSUE TITLE
Open file has a loading state for a long time, about 5 minutes before opening

### ISSUE THREAD

**Issue by bensonzhow** [microsoft/vscode#76666]
Issue Type: <b>Bug</b>

打开文件有很长时间的loading状态，大概5分钟左右才打开！

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-eclipse-keybindings|alp|0.10.0
swagger-viewer|Arj|2.2.2
multiline-find-and-replace|axl|0.0.1
vs-treeview|DaG|2.6.0
markdown-table-prettify|dar|2.4.0
vscode-markdownlint|Dav|0.28.0
es7-react-js-snippets|dsz|2.3.0
Vue2|duc|0.1.3
vscode-babel-coloring|dza|0.0.4
tortoise-svn|fan|0.1.1
todo-tree|Gru|0.0.138
vue-snippets|hol|0.1.11
nsis|idl|3.17.0
smarty|imp|0.3.0
svn-scm|joh|1.54.3
node-module-intellisense|lei|1.5.0
git-tree-compare|let|1.7.0
markdown-shortcuts|mdi|0.11.0
code-beautifier|mic|2.2.1
vscode-extension-auto-import|mop|1.3.3
vscode-docker|ms-|0.6.4
vscode-language-pack-zh-hans|MS-|1.36.2
mssql|ms-|1.6.0
python|ms-|2019.6.22090
cordova-tools|msj|1.8.3
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.0
vetur|oct|0.21.1
ejs-language-support|Qas|0.0.1
swaggitor|qns|0.1.1
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.8.0
full-react-snippets|wal|1.3.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.4.0
propertylist|zho|0.0.2

(2 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
Translation: 

> Open file has a loading state for a long time, about 5 minutes before opening

@bensonzhow can you please provide us with some steps on how to reproduce this. Are you seeing this with all file?
