### ISSUE TITLE
Initialising js/ts language features never completes

### ISSUE THREAD

**Issue by prianchiru** [microsoft/vscode#76667]
When i open vscode with js file then this process begins 'Initialising js/ts langualge features' and it never ends. I cant use any other vs code functionalities. I can just edit the code but even suggestions also are now shown. 

Some things i noted:

- Ts server is starting but the starting process is not getting completed. The log says ts server starting...
- Extensionhost take 100% cpu usage in vscode process explorer
- Code helper take 100% cpu usage in activity monitor.

Tried completely removing vscode and reinstalled it. Still facing same problem

Attached the logs. This is really a headache. Please help me with
<img width="1677" alt="Screenshot 2019-07-05 at 11 40 49 AM" src="https://user-images.githubusercontent.com/28918190/60701925-f8952200-9f1a-11e9-9479-752e24abc765.png">
<img width="984" alt="Screenshot 2019-07-05 at 11 51 46 AM" src="https://user-images.githubusercontent.com/28918190/60702070-693c3e80-9f1b-11e9-8b0b-41956aceb536.png">

OS: Mac mojave
VS code version: 1.36.0
<img width="1678" alt="Screenshot 2019-07-05 at 12 13 13 PM" src="https://user-images.githubusercontent.com/28918190/60703053-59722980-9f1e-11e9-9698-8968d6446582.png">

**Comment by prianchiru** [comment]
@mjbvz any updates on this?

**Comment by mjbvz** [comment]
Please follow [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) to provide information about your system setup.

Also be sure to test with all extensions disabled

**Comment by prianchiru** [comment]
[VSCODE.mov.zip](https://github.com/microsoft/vscode/files/3371473/VSCODE.mov.zip)
Disabled all extensions and still able to reproduce

**Comment by prianchiru** [comment]
System info:

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
@prianchiru Does this happen for every project you open? Can you share an example project?

**Comment by prianchiru** [comment]
@mjbvz yes it is happening for every project
