### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by kienmatu** [microsoft/vscode#76668]
TERMINAL do not wrote PS local address yet, and not focus when i open
Ex: PS C:\Users\kienm\Documents\a DEV\REACTJS\productpage>

i have to type cd then it appear

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
