### ISSUE TITLE
VSCode hangs on developer tools

### ISSUE THREAD

**Issue by himanshu-nain** [microsoft/vscode#76663]
Issue Type: <b>Performance Issue</b>

VSCode hangs whenever I toggle developer tools and execute some javascript on console. I have to manually kill all the running  code processes to get back to normal state and close code.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.13.1-041301-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz (4 x 2526)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|5.63GB (3.76GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   121	  3084	code main
    0	    35	  3088	   zygote
    0	   213	  3132	     window (Untitled-1 - Visual Studio Code)
    0	   104	  3383	       extensionHost
    0	    86	  3407	     shared-process
    0	     0	  3633	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  3634	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	    92	  3607	     window (Issue Reporter)
    0	   110	  3116	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
gitlens|eam|9.8.2
rest-client|hum|0.21.3
cpptools|ms-|0.24.0
material-icon-theme|PKi|3.8.0
java|red|0.46.0

</details>

**Comment by gjsjohnmurray** [comment]
Does it also happen if you run VSCode with all extensions disabled?

If so, please post a simple example of what you execute on the Developer Tools Console to trigger the hang.

**Comment by dbaeumer** [comment]
@bpasero Electron update?

**Comment by bpasero** [comment]
> VSCode hangs whenever I toggle developer tools

This is odd, but VSCode is not officially supporting the developer tools of chrome. I suggest you try to reproduce this in Electron and then report this to Electron https://github.com/atom/electron
