### ISSUE TITLE
(key binding) After v1.36.0, alt+1 no longer works when focusing on explorer

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#76660]
- VSCode Version: 1.36.0 or insiders
- OS Version: Win10

Steps to Reproduce:

1. Ctrl+Shift+E to focus on Explorer
2. Press Alt+1
3. Before v1.36.0, this should move focus onto the first tab, now it doesn't. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Duplicate of #76369 which will be fixed in  the upcoming recovery build.

**Comment by dbaeumer** [comment]
@gjsjohnmurray thanks a lot for doing all the duplication detection work!

Dups #76369
