### ISSUE TITLE
VSCode Windows jerks on mouseover the footer/status bar items 

### ISSUE THREAD

**Issue by flexdevguy** [microsoft/vscode#76664]
Issue Type: <b>Bug</b>

The window jerks when mouse pointer is placed on top of status bar items like language/encoding.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
vscode-npm-script|eg2|0.3.7
vscode-todo-plus|fab|4.13.0
rest-client|hum|0.21.3
azure-pipelines|ms-|1.152.0
vscode-apimanagement|ms-|0.1.1
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
azure-account|ms-|0.8.4
sublime-keybindings|ms-|4.0.3
debugger-for-chrome|msj|4.11.6
fabulous|raa|0.12.0
vscode-extjs|Sen|1.0.1
vscode-icons|vsc|8.8.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by gjsjohnmurray** [comment]
Do you also see the problem if you run VSCode with all extensions disabled?

If so, can you post an animation?

**Comment by dbaeumer** [comment]
@bpasero assigning to you due to the status line work you did.

**Comment by bpasero** [comment]
> The window jerks when mouse pointer is placed on top of status bar items like language/encoding.

@flexdevguy please explain what that means, the word does not tell me what you see. Extra points for doing screen recording.
