### ISSUE TITLE
add *.hpp.in to the file.associations in vscode out of the box

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#76662]
*.hpp.in is a very common extension for C++ file to be processed by cmake. also *.h.in. It would be nice to add it to vscode so it can highlight it in c++ out of the box.

Thank you.

**Comment by alexr00** [comment]
Pointer for starting: https://github.com/Microsoft/vscode/blob/master/extensions/cpp/package.json#L21-L22

**Comment by skprabhanjan** [comment]
@alexr00 , I will push this change :)
