### ISSUE TITLE
Remove smooth scroll CLI

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76665]
@usernamehw @mjbvz I am a bit confused about this change, isn't it that command line arguments are being passed to Chrome/Electron anyway? Why is this needed?

_Originally posted by @bpasero in https://github.com/microsoft/vscode/pull/65422#issuecomment-508529723_

**Comment by mjbvz** [comment]
@usernamehw Would you like to submit a PR that reverts the original PR?
