### ISSUE TITLE
Find & Replace UX ideas

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7667]
One idea is to reuse as much of the search UI we already have. Each entry in the search viewlet could show a preview of the replace operation and clicking on an entry could open the diff editor to actually show a before/after using the text editor.

Mockup:

![image](https://cloud.githubusercontent.com/assets/900690/16046809/04ea83de-324e-11e6-9552-73edfc7c1842.png)

**Comment by yisibl** [comment]
I think we should be unified only a one search box, when the search project, you can directly display the search results in tab, click on the search results in the right to open a new tabs.

Sublime text: 

![demo](https://img.alicdn.com/tps/TB1k4PSKpXXXXcXXpXXXXXXXXXX-1216-762.png)

**Comment by stevencl** [comment]
We discussed in the UX meeting yesterday and suggested that we want to iterate over this design as it progresses.
