### ISSUE TITLE
[Extension]Can not start GUI program with child_process in vscode command context

### ISSUE THREAD

**Issue by zengfenfei** [microsoft/vscode#76673]
- VSCode Version: 1.29.1 & the latest insiders
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Create a vscode extension and register a command with following code:
```
vscode.commands.registerCommand('rnk.inspect', () => {
    require('child_process').exec('react-devtools', (err, stdout) => {
        console.log('result', err, stdout)
    })
});
```
2. Press `F5` to debug the extension.
3. Run the command.

Expected: The **react-devtools** GUI program can be launched.

Actual result: The following error reported:
```
result Error: Command failed: react-devtools
extension.js:22
    at ChildProcess.exithandler (child_process.js:287:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12) 
```
I've tried the code as standalone node.js app and it works fine. I'm not sure if it's a bug. So I also asked [a question](https://stackoverflow.com/questions/56896340/can-not-start-gui-program-in-vscode-command-context) in stackoverflow.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
What happens if you start "react-devtools" from VS Code's integrated terminal?

**Comment by zengfenfei** [comment]
> What happens if you start "react-devtools" from VS Code's integrated terminal?

Works correctly.

**Comment by weinand** [comment]
Have you tried to specify an absolute path instead of the relative path "react-devtools"?

Since this is a problem of your extension, you'll have to debug why the exec fails...

**Comment by zengfenfei** [comment]
yes, I've tried the absolute path of 'react-devtools', the same error.

I do try to debug why the exec fails, but the the error info is so limited, and the extension code is simple enough, have no clues for further debugging. The 'react-devtool' is by facebook and it works in OS terminal and vscode's integrated terminal, so I don't think it's the problem of the command itself. And the code also works in regular node environment(the same version of node used by vscode extension). So I speculate that the root cause may be the node environment used by vscode extension is different from the regular node. Hope you guys can give some clues for further debugging of the problem.

Thanks

**Comment by weinand** [comment]
Does it work if you run your code as a standalone node.js program?
```
require('child_process').exec('react-devtools', (err, stdout) => {
        console.log('result', err, stdout)
})
```

**Comment by zengfenfei** [comment]
The code works as a standalone node.js program. 
['react-devtools'](https://www.npmjs.com/package/react-devtools) does not read any input from tty. it's a GUI program using electron. it just pop up a window like this:
<img width="817" alt="Screen Shot 2019-07-09 at 11 25 15 AM" src="https://user-images.githubusercontent.com/773310/60857220-4c19af80-a23c-11e9-9414-9d611c45795d.png">

**Comment by weinand** [comment]
Aha, 'react-devtools' is an electron app. Most likely that's the problem as VS Code is an electron app too. So your extension runs in a node.js process that is really an electron app where electron is turned off. Since this behavior is configured via environment variables, and variables are inherited via childprocess.exec, 'react-devtools' might get confused...

**Comment by zengfenfei** [comment]
Successfully launch the 'react-devtools' by setting the environment variable explicitly.
```
exec('react-devtools', {env: {...process.env, ELECTRON_RUN_AS_NODE: ''}}, (err, stdout) => {
        console.log('result', err, stdout);
    });
```

Thanks for your help!

**Comment by weinand** [comment]
Please try to remove the env variable 'ELECTRON_RUN_AS_NODE' before calling `childprocess.exec`, e.g. by using something like this:
```js
delete process.env.ELECTRON_RUN_AS_NODE;
```

A more correct would be to clone the process.env; remove the 'ELECTRON_RUN_AS_NODE' variable and then pass it on to `childprocess.exec`.
