### ISSUE TITLE
 Display Chinese garbled code on terminal   System: Mac OS Mojave 10.14.5   

### ISSUE THREAD

**Issue by G1King** [microsoft/vscode#76678]
System: Mac OS Mojave 10.14.5   

vscode V : 1.36.0 

![image](https://user-images.githubusercontent.com/21077737/60709851-f09da800-9f43-11e9-801c-e6c308a4cfe7.png)
 display Chinese garbled code on terminal  but  previous versions were normal !

**Comment by Tyriar** [comment]
What's in your settings.json file?

**Comment by G1King** [comment]
my setting.json :   {
    "fileheader.Author": "xxx",
    "fileheader.LastModifiedBy": "xx",
    "fileheader.tpl": "/*\r\n * @Author: {author} \r\n * @Date: {createTime} \r\n * @Last Modified by:   {lastModifiedBy} \r\n * @Last Modified time: {updateTime} \r\n */\r\n",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "files.autoSave": "off",
    "files.autoSaveDelay": 1000,
  "eslint.validate": [
      "javascript", 
      "javascriptreact",
       {
           "language": "html",
           "autoFix": true
       },
      {
          "language": "vue",
          "autoFix": true
      }
  ],
    "eslint.autoFixOnSave": true,
    // Enable/disable default JavaScript formatter (For Prettier)
    "javascript.format.enable": false,
    "prettier.singleQuote": true,
    // 点击保存时，根据 eslint 规则自定修复，同时集成 prettier 到 eslint 中
    "prettier.eslintIntegration": true,
    "eslint.options": {
        "plugins": [
            "html"
        ]
    },
    "emmet.includeLanguages": {
        "vue-html": "html",
        "javascript": "javascriptreact",
        "wxml": "html"
    },
    "liveServer.settings.donotVerifyTags": true,
    "liveServer.settings.donotShowInfoMsg": true,
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "workbench.sideBar.location": "left",
    "editor.quickSuggestions": true,
    "window.zoomLevel": 0,
    "explorer.confirmDelete": false,
    "liveServer.settings.host": "192.168.3.99",
    "explorer.confirmDragAndDrop": false,
    "typescript.locale": "zh-CN",
    "git.confirmSync": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "git.enableSmartCommit": true,
    "gitlens.views.repositories.files.layout": "list",
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "dart.flutterSdkPath": "/Users/Sunshinking/flutter",
    "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
    "php-cs-fixer.lastDownload": 1560128767346,
    "liveServer.settings.wait": 1000,
    "breadcrumbs.enabled": true,
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "all",
    "editor.minimap.enabled": false,
    "files.associations": {
        "*.cjson": "jsonc",
        "*.wxss": "css",
        "*.wxs": "javascript",
        "*.jsx": "javascriptreact"
    },
    "minapp-vscode.disableAutoConfig": true,
    "better-comments.highlightPlainText": true,
    "todohighlight.isEnable": true,
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "editor.fontSize": 13,
    "diffEditor.ignoreTrimWhitespace": false,
    "phpserver.ip": "192.168.3.99",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.setLocaleVariables": false,
    "terminal.external.osxExec": "terminal.app",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "workbench.colorTheme": "One Dark Pro Bold",
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorCustomizations": {
       
        "editor.background": "#1b1b1bad",
        "statusBar.background": "#0b80ee",
        "statusBar.foreground": "#fff"
    }
   
}

**Comment by Tyriar** [comment]
Does setting this to true fix it?

```
"terminal.integrated.setLocaleVariables": false
```

**Comment by G1King** [comment]
Thank you very much for solving my problem！！！
