### ISSUE TITLE
Search icon keeps in processing status when no search job

### ISSUE THREAD

**Issue by energygreek** [microsoft/vscode#76677]
Issue Type: <b>Bug</b>

Search icon on the left pane has a clock, even there is no search task. 
It may be caused by a canncelation of search.
![image](https://user-images.githubusercontent.com/25223558/60710060-673aa580-9f44-11e9-848e-66db4a353d88.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (1.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
wxml-vscode|cny|0.1.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
cpptools|ms-|0.24.0
vetur|oct|0.21.1
minapp-vscode|qiu|2.0.0
cmake|twx|0.0.17
vscode-proto3|zxh|0.3.0

</details>

**Comment by roblourens** [comment]
Do you know what steps you took for that to happen?

If you start another search does it go away?

**Comment by energygreek** [comment]
```
Do you know what steps you took for that to happen?
```
make a search then click cancel or clear after soon.
```
If you start another search does it go away?
```
yes

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders
