### ISSUE TITLE
go live option is not showing

### ISSUE THREAD

**Issue by mayureshkasar** [microsoft/vscode#76676]
Issue Type: <b>Bug</b>

go live option is not showing

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.88GB (2.88GB free)|
|Process Argv|D:\Developer\javascript\jscode\function.html|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like an extension issue, in which case please log it at https://github.com/ritwickdey/vscode-live-server/issues and close this one here.

**Comment by dbaeumer** [comment]
Agree with @gjsjohnmurray. Closing. Please report the issue with the extension you are using.
