### ISSUE TITLE
There is an unknown delay when coding.

### ISSUE THREAD

**Issue by neverwinter-sjh** [microsoft/vscode#76682]
Issue Type: <b>Bug</b>

There is an unknown delay when coding.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (15.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
vscode-great-icons|emm|2.1.47
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|1.9.0
vscode-pull-request-github|Git|0.8.0
vue-snippets|hol|0.1.11
vscode-react-typescript|inf|1.3.0
vscode-github|Kni|0.30.2
remotefs|lix|0.0.16
Angular-BeastCode|Mik|8.0.10
vscode-remote-workspace|mkl|0.42.0
vscode-language-pack-ko|MS-|1.36.2
python|ms-|2019.6.22090
debugger-for-chrome|msj|4.11.6
syncing|non|3.0.4
angular-console|nrw|8.0.6
vetur|oct|0.21.1
vscode-snippets-mobx-react|qin|1.0.5
nativescript|Tel|0.10.1

</details>

**Comment by dbaeumer** [comment]
@neverwinter-sjh can you be a little bit more specific. In which file does it happen? Dooes it happen if all extensions are disabled. Start code with `--disable-extensions`
