### ISSUE TITLE
A11y_VSCode_ProblemPanel_ScreenReader:Screen reader annoucne the error informatin twice

### ISSUE THREAD

**Issue by prasadaps** [microsoft/vscode#76685]
Environment Details:
VSCode Version : 1.36.0
OS Version : Win10
Additional Details:
MAS Violated : MAS 1.3.1

Repro Steps:
1) Open Visual studio code editor  
2) Press ctrl+shift+M
3) Type something in the editer which must be systactically wrong
4) Remove the line from editor
5) Listen the announcement of the screen reader while screen reader annoucne about error message.
 
Actual:
Screen reader announcement the information twice.

Expected:
Screen reader should annoucne the infromation about error only once.

Recommendations:
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

User Impact:
Screen reader will face difficulty to understand the information. 

MAS Reference:
MAS 1.3.1 - https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

Attachment For Reference: 
A11y_VSCode_Output panel_ScreenReader_NoAnnouncementOfStateOfButton.Mp4
Does this issue occur when all extensions are disabled?: Yes
[A11y_VSCode_ProblemPanel_ScreenReader_AnnoucnementInformatinTwice.pptx](https://github.com/microsoft/vscode/files/3361997/A11y_VSCode_ProblemPanel_ScreenReader_AnnoucnementInformatinTwice.pptx)

**Comment by isidorn** [comment]
Can not reproduce the issue. You might be using JAWS, which we do not support.
Also for errors our default accessibility experience is F8 which navigates through all errors nicely

<img width="958" alt="Screenshot 2019-07-08 at 18 17 29" src="https://user-images.githubusercontent.com/1926584/60825752-ae2ad400-a1ac-11e9-8897-cc8c47c313ee.png">
