### ISSUE TITLE
Recognition of unicode quotation marks

### ISSUE THREAD

**Issue by Sasha-Sorokin** [microsoft/vscode#76693]
Issue Type: <b>Feature Request</b>

Whenever you use <kbd>^ Ctrl</kbd>+<kbd>⌫ Backspace</kbd>, VS Code will remove the quotation marks as if it was part of word, when it shouldn't be: try paste in Chrome text `“Hello world!”`, then move cursor at the end of word “Hello,”  then press <kbd>^ Ctrl</kbd>+<kbd>⌫ Backspace</kbd>.

This is what I would consider correct behaviour — Chrome will remove “Hello,” but will leave quotation mark untouched (resulting `“| world!”`), when VS Code does the opposite — removing both word and mark.

I think this change is very useful when you are using Code to write documentation or localization files, where typography matters. Please consider that there are more than English quotation marks in Unicode, the [list on Wikipedia](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) can be handy probably.

One more good thing would be auto closing of quotation marks (when you type `«` with Compose key, it would automatically insert `»` at the end, resulting `«|»`), but this is more like extension request, so forget..

VS Code version: Code - OSS 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-28T20:38:33.371Z)
OS version: Linux x64 5.1.15-1-MANJARO

**Comment by rebornix** [comment]
Currently the word operations only honor `editor.wordSeparators`, which doesn't contain unicode quotation marks.

**Comment by alexandrudima** [comment]
@Sasha-Sorokin Just configure 
```
"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?“”",
```
i.e. add `“”` to the string and things will work as you wish.

I would not change the defaults we ship with, which are optimized from programming languages.

**Comment by Sasha-Sorokin** [comment]
Yep. Already did, thanks for telling! Clearly missed that option when was searching...
