### ISSUE TITLE
Is the icon of vs code changed again

### ISSUE THREAD

**Issue by ramgesg** [microsoft/vscode#76699]
- VSCode Version: 1.37.0-insider (user setup) (34e0ed575230b5c8168289995d59edf274539631)
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Open VS Code

![image](https://user-images.githubusercontent.com/26381563/60715860-ab757800-9f3b-11e9-83c2-812a6d73c2cc.png)

**Comment by SupinePandora43** [comment]
same issue, but my vscode after downgraded to 1.36 via "Update available!"

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/ef893f0cfe7d80bd695005cfea24d481a4722bb3
