### ISSUE TITLE
Error in Explorer Exclude

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#76692]
Issue Type: <b>Bug</b>

Getting an initial error.
![image](https://user-images.githubusercontent.com/30625381/60714331-2b3f1a80-9f1b-11e9-929d-a4840e9322a8.png)

VS Code version: Code - Insiders 1.37.0-insider (34e0ed575230b5c8168289995d59edf274539631, 2019-07-05T08:53:23.345Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|-psn_0_12147605|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.0
sort-imports|ama|6.0.1
jest-snippets|and|1.7.0
vscode-apollo|apo|1.7.4
atlascode|atl|1.4.2
vscode-custom-css|be5|3.0.4
color-info|bie|0.5.1
twigcs|cer|1.0.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-storybook|cst|0.0.5
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
vscode-pull-request-github|Git|0.8.0
sass-lint|gle|1.0.5
beautify|Hoo|1.5.0
rest-client|hum|0.21.3
output-colorizer|IBM|0.1.2
figma|ide|0.1.1
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.1
exercism|jgo|0.0.4
vscode-commitizen|Kni|0.8.2
twig-language-2|mbl|0.8.8
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
vscode-remote-extensionpack|ms-|0.15.0
references-view|ms-|0.0.27
vscode-typescript-next|ms-|3.6.20190703
debugger-for-chrome|msj|4.11.6
ts-prop-dag|nat|1.0.5
gremlins|nho|0.14.3
vscode-jest|Ort|3.0.2
vscode-versionlens|pfl|0.24.0
polacode|pnp|0.3.2
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.4.1
explorer-exclude-vscode-extension|Red|1.1.0
elastic|ria|0.13.3
code-settings-sync|Sha|3.3.1
gherkin-autocomplete|sil|1.3.3
sonarlint-vscode|Son|1.8.0
sourcegraph|sou|1.0.14
easy-snippet-maker|tar|0.0.6
vscodeintellicode|Vis|1.1.7
vscode-icons|vsc|8.8.0
snippet|vsc|0.6.0
vim|vsc|1.8.1
quokka-vscode|Wal|1.0.233
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3

(1 theme extensions excluded)

</details>

**Comment by bm-stschneider** [comment]
ok, which extension?

**Comment by Tyriar** [comment]
<img width="265" alt="Screen Shot 2019-07-08 at 7 31 50 AM" src="https://user-images.githubusercontent.com/2193314/60818426-798a2e80-a152-11e9-826d-970ab72db22e.png">

**Comment by bm-stschneider** [comment]
doh, thanks.
