### ISSUE TITLE
Override Theme on a Rule by Rule Basis

### ISSUE THREAD

**Issue by tills13** [Microsoft/vscode#7669]
- VSCode Version: 1.3.0-insider
- OS Version: OSX 10.11

This would be a "**nice to have**." In Sublime, you could apply a theme globally, and then override it piece by piece. For example, if I were to apply the Material theme, but wanted a different color for string tokens, I could override it in a "User Theme" file.

**Comment by aeschli** [comment]
We currently have no plans to support this.

**Comment by Kitanotori** [comment]
I also vote for this feature. It's possible in Atom, and makes customization much easier than having to do some copypaste & customization for a whole theme.
