### ISSUE TITLE
Can't use 'F12' goto definition for C Lanuage file.

### ISSUE THREAD

**Issue by NeoXiong** [Microsoft/vscode#767]
I want to use Visual Studio Code for C programming, after load the top folder of my project, all files has been added, but seems I can't use 'F12' or 'Ctrl + left click' to go to definition across my project files

**Comment by NeoXiong** [comment]
Does vscode support this feature? or I made some mistake?

**Comment by egamma** [comment]
VS Code currently does not support this feature and I've labeled it with the 'feature request label'.

Am 28.11.2015 um 15:59 schrieb NeoXiong <notifications@github.com<mailto:notifications@github.com>>:


Does vscode support this feature? or I made some mistake?

-

**Comment by JonLee9527** [comment]
looking forward the support for C/C++ “go to definition"

**Comment by wirecat** [comment]
@egamma @NeoXiong Isn't this implemented now? Can this be closed?

**Comment by egamma** [comment]
Closing - this is now support by the C/C++ extension.

@wirecat thanks for pointing this out.
