### ISSUE TITLE
VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#76707]
Issue Type: <b>Bug</b>

getting this issue, tried reinstalling vscode insiders a several times but doesnt help.
![image](https://user-images.githubusercontent.com/9264813/60717510-9dc1f180-9f3f-11e9-9bb1-6320059c912b.png)

VS Code version: Code - Insiders 1.37.0-insider (34e0ed575230b5c8168289995d59edf274539631, 2019-07-05T08:57:32.211Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (2.39GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
python|ms-|2019.6.22090
typescript-javascript-grammar|ms-|0.0.50
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
fabric8-analytics|red|0.0.12
vscodeintellicode|Vis|1.1.7
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
debugger-for-chrome|msj|4.11.6
scala|sca|0.3.4

</details>

**Comment by IllusionMH** [comment]
Is it reproducible without extensions?
To try this you can open Command Palette (`F1` or `Ctrl + Shift + P`) and pick `Developer: Reload Window With Extensions Disabled`

**Comment by mjbvz** [comment]
Does this happen in the latest insiders too?

/cc @joaomoreno

**Comment by sanket-bhalerao** [comment]
@mjbvz this happened for a brief time period when version 1.37 was released initially, within an hour of release the rollback to 1.36 was released (with 1.36 this issue was not reproducible).
With newer release 1.37 this issue is not reproducible.
