### ISSUE TITLE
Creating new Date from string date adds 21 seconds to result

### ISSUE THREAD

**Issue by ruslan-volkov** [microsoft/vscode#76700]
Issue Type: <b>Bug</b>

**TypeScript Version:**  3.5.2

**Search Terms:**

**Code**

Creating new dates (before or equal to 10 march 1911) from string format dates adds 21 seconds to the resulting date.

```ts

var firstDate = new Date("1900-01-01T00:00:00.000Z").toString()
// Mon Jan 01 1900 00:09:21 GMT+0009 (Central European Standard Time)

var secondDate = new Date(firstDate).toString()
// Mon Jan 01 1900 00:09:42 GMT+0009 (Central European Standard Time)

var thirdDate = new Date(secondDate).toString()
// Mon Jan 01 1900 00:10:03 GMT+0009 (Central European Standard Time)
```

**Expected behavior:**
Should return Mon Jan 01 1900 00:09:21 GMT+0009 (Central European Standard Time)

**Actual behavior:**
Adds 21 seconds every time new Date(string) is called.

Detected since vscode 1.36 (1.35 works).

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.28GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
cometeextension|ceg|0.2.3
docs-markdown|doc|0.2.9
gitlens|eam|9.8.2
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
It doesn't depend on VS Code or TS. Only on environment where you run it.
So it is either Chromium or Node.js (both was updated with new Electron version)

**Comment by dbaeumer** [comment]
@IllusionMH thanks for explaining this. I totally agree. Best is to try in native code or Chrome matching VS Code's version and then file an issue there:

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
