### ISSUE TITLE
Keybinding With terminal.close Command Doesn't Close Terminal

### ISSUE THREAD

**Issue by tills13** [Microsoft/vscode#7670]
- VSCode Version: 1.3.0 Insider
- OS Version: OSX 10.11

Steps to Reproduce:

- create keybinding with `terminal.close` action

`{ "key": "escape", "command": "workbench.action.terminal.close", "when": "editorFocus" }`

- if the terminal was originally closed, it will open. If the terminal is open, it will reload.

**Comment by Tyriar** [comment]
It's not supposed to close the terminal panel but rather the active terminal, what you're seeing is it closing the last terminal and it recreating a new one. This is the very beginning of the multiple terminals work, you can create a new terminal instance using <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\`</kbd>.

@tills13 do you think  renaming these to terminal.kill and terminal.killAll would make things clearer?

**Comment by tills13** [comment]
Maybe just differentiate between the /terminal/ and the terminal /panel/ - `workbench.action.terminal.panel.close`. Also, perhaps this should be in another "ticket" but is there a `terminalFocus` context similar to `editorFocus`? Ideally, I'd like to be able to close the terminal panel when it's focussed with the ESC key (I've tried `!editorFocus`)

**Comment by Tyriar** [comment]
@tills13 yes I think eventually there should be some `terminalFocus` that you can use in your keybindings with a `when`.
