### ISSUE TITLE
ExtensionContext.globalStoragePath not defined in NPM's vscode.d.ts

### ISSUE THREAD

**Issue by pongad** [microsoft/vscode#76704]
Apologies if I'm doing something stupid.

If I run `npm i vscode`, my `node_modules/vscode/vscode.d.ts` contains:
```
        export interface ExtensionContext {
                subscriptions: { dispose(): any }[];

                workspaceState: Memento;

                globalState: Memento;

                extensionPath: string;

                asAbsolutePath(relativePath: string): string;

                storagePath: string | undefined;

                logPath: string;
        }
```
The `globalStoragePath` member seems to be missing even though it has been a part of the API since January? I can see this on `vscode` NPM package version 1.1.35.

Of course, since the member doesn't exist,
`extContext.globalStoragePath` doesn't compile, but `(extContext as any)['globalStoragePath']` seems to work.

**Comment by jrieken** [comment]
Not sure if you on the old or new world but you should be installed `@types/vscode`, see here for more: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
