### ISSUE TITLE
TypeScript code lens treats `interface`s differently from `type`s

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#76706]
- VSCode Version:
- OS Version:

Given:

``` ts
{
    interface Foo {
        foo: number
    }
    
    type F = Foo;
    
    const foo: Foo = {
        foo: 1
    }
}

{    
    type Foo = {
        foo: number
    }
    
    type F = Foo;
    
    const foo: Foo = {
        foo: 1
    }
}
```

If we compare the behaviour of the code lens for the `interface` and `type`, they are different:

![image](https://user-images.githubusercontent.com/921609/60717329-6b9d9900-9f19-11e9-8cd5-d0ec14022e6a.png)

![image](https://user-images.githubusercontent.com/921609/60717349-72c4a700-9f19-11e9-979d-451bed67f018.png)

As a user, I want the behaviour that `interface` has to also apply to my `type`:

- Show implementation count
- Object members should show reference counts

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
First one is a won't fix; the implementations code lens only is enabled on direct interfaces. Otherwise we'll end up showing this code lens in many more locations where it is not useful.

**Comment by OliverJAsh** [comment]
Why does it make sense for interface and not type?

**Comment by mjbvz** [comment]
```ts
// Showing implements code lens here would generally not use useful
type Size = number;
```

**Comment by OliverJAsh** [comment]
Then it could be restricted to "type aliases for objects", i.e. exclude primitives? That way, it's the same as `interface`?

**Comment by jhnns** [comment]
@mjbvz it would actually be very useful if VSCode showed me all places where somone used the `Size` type. It would not be useful if VSCode showed me all occurrences of the `number` type (which is probably the only information that TypeScript gives us?)
