### ISSUE TITLE
Permanently disable extension recommendations popup for all possible extensions

### ISSUE THREAD

**Issue by jlmcdonnell** [microsoft/vscode#76715]
The extension recommendations popup is quite distracting. I don't want extension recommendations at all. I don't want to have to manually blacklist every single extension either.

I have set the following settings:
```
"extensions.ignoreRecommendations": true,
"extensions.showRecommendationsOnlyOnDemand": true,
```

I believed these would have stopped the popups but they haven't. I don't know if this is a bug, or if I have misunderstood what they're for. Either way, the whole experience for stopping this visual distraction is unintuitive.

I suggest adding an unambiguous setting that stops all extension recommendation popups.

**Comment by jlmcdonnell** [comment]
Just for further clarity, this is what I'm referring to:

<img width="519" alt="popup" src="https://user-images.githubusercontent.com/2794581/60721732-c8538080-9f26-11e9-8d42-106ad7bff32f.png">

**Comment by sandy081** [comment]
@jlmcdonnell Sorry, this is a broken in our latest stable. Following settings should allow you to control these recommendation notifications

```
"extensions.ignoreRecommendations": true,
"extensions.showRecommendationsOnlyOnDemand": true,
```

**Comment by sandy081** [comment]
To verify:

- Recommendation notifications for file type or file extensions, should not be shown when one of the above settings is set to `true`.
