### ISSUE TITLE
Use URI for backupPath

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#76719]
I introduced a new URI property called `backupWorkspaceResource` in window configuration. This is being used on the renderer.

https://github.com/microsoft/vscode/blob/2a88776f07d7d8bebca2e78491b204c6eaf45169/src/vs/platform/windows/common/windows.ts#L421-L422

Please adopt and use `backupWorkspaceResource` property also on electron main side

**Comment by bpasero** [comment]
@sandy081 I am a little bit confused by the change to introduce `backupWorkspaceResource`. You added it to `IWindowConfiguration` it seems, but the adoption on electron-main is missing, so when you access `backupWorkspaceResource` there, it will always be undefined. 

Was your intent to change `backupPath` to a resource and `backupWorkspaceResource` is just a workaround to not do this adoption in `electron-main` or is there more to it?

I think it is realistic to say that today on `electron-main` we can only deal with `file://` paths and as such using paths on `electron-main` at least seems to be OK. However why don't we add the backup location to the environment service similar to snippets home, etc, as URI?

**Comment by bpasero** [comment]
After discussion: We seem to have 4 different backup properties (some are strings, some are URIs) in environment service and window config. We should try to convert to URIs where possible and try to move some of these properties to a `IMainEnvironmentService` to not have them go into the workbench environment service.  We could possibly do this for other properties as well.

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/102918 which is the more general issue for environment service debt.
