### ISSUE TITLE
update to 1.37 it can't build & debug task/launch with cmake tools

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#76712]
Issue Type: <b>Bug</b>

版本: 1.37.0-insider (system setup)
提交: 34e0ed575230b5c8168289995d59edf274539631
日期: 2019-07-05T08:57:32.211Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18922

it's no any problems on 1.36 ,build(ctrl+shift+B) task & debug(F5) launch . 
but  on 1.37 it can't work!the same code,same configs.

if I use cmake tools build & debug , that's ok.

VS Code version: Code - Insiders 1.37.0-insider (34e0ed575230b5c8168289995d59edf274539631, 2019-07-05T08:57:32.211Z)
OS version: Windows_NT x64 10.0.18922
Remote OS version: Linux x64 4.4.0-18922-Microsoft

 @

**Comment by kinglionsz** [comment]
when I debug(F5),vs code will report:  The specified task cannot be tracked.

**Comment by weinand** [comment]
@isidorn or @alexr00 does this ring a bell?

**Comment by alexr00** [comment]
@kinglionsz what is your launch config?

**Comment by kinglionsz** [comment]
> @kinglionsz what is your launch config?

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/helloworld",
            "args": [],     
            "stopAtEntry": true,   
            "cwd": "${workspaceFolder}/bin/",
           
            "environment": [],                        

            "preLaunchTask": "build",       

            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            //remote wls下无需以下管道
            // "pipeTransport": {
            //     "debuggerPath": "/usr/bin/gdb",
            //     "pipeProgram": "${env:windir}\\system32\\bash.exe",
            //     "pipeArgs": ["-c"],
            //     "pipeCwd": ""
            // },    

            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by kinglionsz** [comment]
tasks.json:

// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format

//https://code.visualstudio.com/docs/editor/tasks#vscode

{
    "version": "2.0.0",
    //remote wls下无需以下管道shell
    // "windows": {
    //     "options": {
    //         "shell": {
    //             "executable": "c:\\windows\\System32\\bash.exe",
    //             "args": ["-c"]
    //         }
    //     }
    // },
    "tasks": [
        {
            "label": "cmake",
            "type": "shell",
            "command": "cmake",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "args": [
                "-H.",
                "-BDebug",
                "-DCMAKE_BUILD_TYPE=Debug",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=YES",
                "../"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "make",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceFolder}/build/Debug"
            },
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "build",
            "dependsOrder": "sequence",     //按顺序执行 cmake and then make
            "dependsOn": [           
                "cmake",            // first run
                "make"              // second run
            ]
        }
    ]
}

**Comment by kinglionsz** [comment]
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format

//https://code.visualstudio.com/docs/editor/tasks#vscode

{
    "version": "2.0.0",
    //remote wls下无需以下管道shell
    // "windows": {
    //     "options": {
    //         "shell": {
    //             "executable": "c:\\windows\\System32\\bash.exe",
    //             "args": ["-c"]
    //         }
    //     }
    // },
    "tasks": [
        {
            "label": "cmake",
            "type": "shell",
            "command": "cmake",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "args": [
                "-H.",
                "-BDebug",
                "-DCMAKE_BUILD_TYPE=Debug",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=YES",
                "../"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "make",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceFolder}/build/Debug"
            },
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "build",
            "dependsOrder": "sequence",     //按顺序执行 cmake and then make
            "dependsOn": [           
                "cmake",            // first run
                "make"              // second run
            ]
        }
    ]
} @

**Comment by kinglionsz** [comment]
> @kinglionsz what is your launch config? this is  tasks.json

@

// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format

//https://code.visualstudio.com/docs/editor/tasks#vscode

{
    "version": "2.0.0",
    //remote wls下无需以下管道shell
    // "windows": {
    //     "options": {
    //         "shell": {
    //             "executable": "c:\\windows\\System32\\bash.exe",
    //             "args": ["-c"]
    //         }
    //     }
    // },
    "tasks": [
        {
            "label": "cmake",
            "type": "shell",
            "command": "cmake",
            "options": {
                "cwd": "${workspaceFolder}/build"
            },
            "args": [
                "-H.",
                "-BDebug",
                "-DCMAKE_BUILD_TYPE=Debug",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=YES",
                "../"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "make",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceFolder}/build/Debug"
            },
            "args": [],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        },
        {
            "label": "build",
            "dependsOrder": "sequence",     //按顺序执行 cmake and then make
            "dependsOn": [           
                "cmake",            // first run
                "make"              // second run
            ]
        }
    ]
}

**Comment by kinglionsz** [comment]
press F5, start the task: cmake, but stay here ,everything is just "silent".
see the gif:
https://gyazo.com/75f9c279bb512968af768633d889c90b

after a few moments,vs code throws out surprises : The specified task cannot be tracked.
see the gif:
https://gyazo.com/ac20ffd6fc36fcb4b6e10e2a1b0443bd

**Comment by kinglionsz** [comment]
> @isidorn or @alexr00 does this ring a bell?

thanks .It's now ok 👌 @

**Comment by kinglionsz** [comment]
> @kinglionsz what is your launch config?

thanks .It's now ok 👌  @weinand @kinglionsz
