### ISSUE TITLE
Swining between Upgrade to 1.37 and Downgrad to 1.36

### ISSUE THREAD

**Issue by dbenarfa** [microsoft/vscode#76718]
Issue Type: <b>Bug</b>

The issue is:
VSCode requests an update to version 1.37 and a few minutes later, it requests an update (it is actually a downgrade) to version 1.36
This is happening more the 5 times to me.

VS Code version: Code - Insiders 1.36.0-insider (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T08:00:29.662Z)
OS version: Windows_NT x64 10.0.18922

**Comment by akulbe** [comment]
I can confirm this is happening here as well. This same behavior has happened on multiple machines.

**Comment by dbaeumer** [comment]
This was due to build problems we has. Should be solved now.
