### ISSUE TITLE
Ctrl+P nor Ctrl+N working with recent update to VS Code

### ISSUE THREAD

**Issue by condericson** [microsoft/vscode#76716]
- VSCode Version: 1.36.0
- OS Version: Windows 10 Version	10.0.15063 Build 15063

Since this newest patch, I'm unable to use Ctrl+P to go to a file, nor Ctrl+N to open a new tab in an already existing window.

Steps to Reproduce:

1. Open VS Code
2. Open a project with multiple files
3. Press and hold the control button, then press either p or n, then release control.
4. Nothing happens.

I looked for duplicates and could not find any. I apologize if I overlooked an open ticket. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by wilstoff** [comment]
I have a similar issue (not exact) to this with go to file.  It seems like for a large project vs code's index of files is not complete nor is updated unless you open a specific file.  I can type the exact name or path of the file, and it will return no results.  Then i can browse to that file and open it, and it shows up the next time i use Ctrl+P.  I am on 1.37.

**Comment by eduandebruijnemm** [comment]
Also experienced this issue with Go to file / Ctrl+click on class. Would be great if this issue can be resolved!

**Comment by alexandrudima** [comment]
@condericson Does VS Code receive the keybinding?


![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by condericson** [comment]
I have no idea why, but these key bindings just started working again...thanks for everyone's attention and attempts at a resolution. The only suggestion I can make to others is to confirm they're on the most recent version of VS Code.
