### ISSUE TITLE
Npm Script Explorer tries to execute the labels of a task instead of the script

### ISSUE THREAD

**Issue by daniel-schulz** [microsoft/vscode#76711]
- VSCode Version: 1.36.0, 1.36.1
- OS Version: Windows 10 Pro 1809 (build 17763.437)

Steps to Reproduce:
![2019-07-24 13_32_29-Clipboard](https://user-images.githubusercontent.com/8694700/61790540-c1c67380-ae17-11e9-98cd-151f5f089b86.png)
1. Setup any task in the package.json.
2. Create a task of type NPM with any label different form the script name.
3. Try to run that task via NPM SCRIPTS
4. It seems like VSCode is trying to execute the label instead of the script.
BTW: Executing the task in the command panel works fine:
![2019-07-05 12_51_58-package json - shiftconnector-code4 - Visual Studio Code](https://user-images.githubusercontent.com/8694700/60718420-def8d800-9f24-11e9-9b2f-f78191e98a14.png)

I've also recorded the issue see video in the zip file:
[video_vscode_npm_scipt_bug.zip](https://github.com/microsoft/vscode/files/3362417/video_vscode_npm_scipt_bug.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by daniel-schulz** [comment]
Just installed the new release.
Issue still available in 1.36.1.

**Comment by daniel-schulz** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Stop script in NPM Script Explorer (#49738)](https://www.github.com/microsoft/vscode/issues/49738)
> * [Newly created npm scripts are not picked up by the explorer (#48544)](https://www.github.com/microsoft/vscode/issues/48544)
> * [Pin task in the npm script explorer (#73786)](https://www.github.com/microsoft/vscode/issues/73786)
> * [Can't execute task inside VS Code after VS Code update (#73817)](https://www.github.com/microsoft/vscode/issues/73817)

These are no duplicates of this problem.

**Comment by daniel-schulz** [comment]
Does no one have the same problem or do I something wrong?
Is it maybe not intended to use task.json together with package.json (npm scripts)?

**Comment by egamma** [comment]
@daniel-schulz not clear what your exact scenario is, but if you just want to run a script from the package.json, then you do not need to define tasks. Can you just delete your 'tasks.json' file and try to run the scripts from the NPM Script Explorer directly.

If this doesn't do what you want, then please provide a `package.json` and `tasks.json` file so that we can easily reproduce the problem.

**Comment by daniel-schulz** [comment]
@egamma Thank you for the reply. I want to use the `tasks.json` to provide readable labels for my NPM scripts from the `package.json`.

I've attached a simple workspace with example `package.json` and  `tasks.json` files.
[npm-scripts-issue.zip](https://github.com/microsoft/vscode/files/3486419/npm-scripts-issue.zip)

**Comment by egamma** [comment]
Thanks for the repro, the issue is confirmed.

The code had a check that the script name exists in the package.json, which doesn't work when the task is defined in the tasks.json. I've removed guard.

**Comment by daniel-schulz** [comment]
Thank you very much @egamma.
