### ISSUE TITLE
Insiders Mac version pulled?

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#76714]
Was the MacOS Code Insiders latest update (v37) pulled? I was able to update at home, but an hour or so later at work there is no update available.

(A place to see the current "release" version would be helpful - with a note if an update was pulled would be a bonus)

- VSCode Version:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/13488/60720910-36ce1980-9efa-11e9-85c3-8c7d0c75dfaf.png">

- OS Version:
MacOS
Steps to Reproduce:

1. Launch Code Insiders
2. Check for updates
No Updates available.

**Comment by IllusionMH** [comment]
Yes. Same for Windows.

Looks like there were few new (severe?) issues that may be a reason to roll back buggy version.

**Comment by lramos15** [comment]
There were a few bugs in the old builds that were causing a bad user experience so we decided to roll it back until it could be fixed. A new version of insiders should be out now!
