### ISSUE TITLE
Code freezes when trying to open file with a lot of strings

### ISSUE THREAD

**Issue by fazaldegui** [microsoft/vscode#76713]
Issue Type: <b>Bug</b>

I have a source c++ file with one variable that has a lot of concatenated strings. When I try to open it Code just hangs/freezes until a message box appears to wait, retry or close.

I try with the all the extensions disabled but no luck. It freezes. In other editor such as Visual Studio or Notepad++ don't have this problem.
I try  to have all the "substrings" in just one big string but It still freezes.

Perhaps is too big for Code the value of this variable?

Thank you.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
clipboard-history|Anj|1.0.7
doxdocgen|csc|0.5.0
githistory|don|0.4.6
gitlens|eam|9.8.2
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.138
vscode-edit-csv|jan|0.0.12
plantuml|jeb|2.11.1
sftp|lix|1.12.7
vscode-language-pack-es|MS-|1.36.2
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0
vs-keybindings|ms-|0.2.0
qub-xml-vscode|qub|1.2.8
vscode-qt-for-python|sea|0.3.0
vscode-hexdump|sle|1.7.2
shell-launcher|Tyr|0.3.0
debug|web|0.23.1

</details>

[problem.zip](https://github.com/microsoft/vscode/files/3362589/problem.zip)

**Comment by r44083** [comment]
Looks like this issue is duplicate of #76710

**Comment by matter123** [comment]
@fazaldegui This should be fixed upstream with version 1.12.15 of https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax.

if you want the changes immediately, install the Better C++ Syntax extension
if you're okay with waiting a few days, you can use the VS Code Insider's release
if you're okay with waiting a while, the changes will eventually be pulled into VS Code stable

**Comment by fazaldegui** [comment]
Thank you :)
