### ISSUE TITLE
windows mouse navigation back forward is broken since recent version update.

### ISSUE THREAD

**Issue by doneykoo** [microsoft/vscode#76728]
Issue Type: <b>Bug</b>

Steps:
- on pc.
- code for a while.
- use mouse 4th and 5th button to naviate backward and forward.

Result:
It has no response.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.4
vscode-json|and|1.5.0
tslint|eg2|1.0.43
prettier-vscode|esb|1.9.0
vscode-back-forward-button|gri|0.1.2
beautify|Hoo|1.5.0
docthis|joe|0.7.1
favorites|kdc|2.4.5
cpptools|ms-|0.24.0
vscode-json-editor|nic|0.2.3
funclist|qrt|7.6.3
quicktype|qui|12.0.46
bash-beautify|sha|0.1.1
vscode-proto3|zxh|0.3.0

</details>

**Comment by gjsjohnmurray** [comment]
Duplicate of #71318 and will be fixed in upcoming June Recovery release.

**Comment by doneykoo** [comment]
> 
> 
> Duplicate of #71318 and will be fixed in upcoming June Recovery release.

that's right. Duplicate of #71318 as it was confirmed bing same issue on windows since 1.36.0 release version.
