### ISSUE TITLE
Can not find all the results when I use the global searching

### ISSUE THREAD

**Issue by cybmws** [microsoft/vscode#76720]
- VSCode Version: 1.36
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. global search the string "GOOGLE_RESOURCE"
2. I can not find it in this file:  "xx/library/xxx/xxx.js" 
( acturally, the string exists in this file )
3. When I use Sublime Text do the same thing, I can find it.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
If you haven't already done so, please review the info at https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results and see if it explains what you're seeing.

**Comment by cybmws** [comment]
It works for me. Thank you very much !

**Comment by cybmws** [comment]
> If you haven't already done so, please review the info at https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results and see if it explains what you're seeing.

It works for me. Thank you very much !
