### ISSUE TITLE
package explorer indent horrible to read

### ISSUE THREAD

**Issue by judos** [microsoft/vscode#76722]
- VSCode Version: 1.36.0
- OS Version: Win10 Pro

Steps to Reproduce:
1. Open workspace folder
2. Look at explorer on the left side

Does this issue occur when all extensions are disabled?: Yes

To give an impression what the user is looking at I marked the left-most visible pixels for each folder with a red line. As you can see subfolders and files have a different indentation. This is very confusing and gives the user difficulties to group the perceived elements. Probably also why a lot of tickets are created where users want to change indentation etc: #17777, #35447, #76276

![indent1](https://user-images.githubusercontent.com/5525810/60725285-fc37a180-9f38-11e9-9d27-ae08100082a0.PNG)

As proposal it would be good to make the arrow icon of the subfolder the same size as the other icons such that the icons actually show up at the same indentation.

**Comment by joaomoreno** [comment]
The `workbench.tree.indent` setting lets you control indentation. The `workbench.tree.renderIndentGuides` setting lets you display indent guides.

**Comment by judos** [comment]
Great but not what I asked. 
The issue is that the icons are not aligned and that makes the UI very hard to read. Even with the indent and indentGuide lines. If the icons would be correctly aligned you would probably also get less people asking about changing indent and showing indent lines always.
