### ISSUE TITLE
Automatic config the charset of opened file

### ISSUE THREAD

**Issue by miguelamello** [microsoft/vscode#76721]
Issue Type: <b>Feature Request</b>

When a file is open in editor, and the editor is set to open files as of the configured charset, it does open the file with the configured charset, however the file may have a diferent charset. Then every time wew have to change reopen the file with the correct charset. The problem is when we forget to do this, and the file content is messed up, and we save the file. Oh god... this is borring indeed.  

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.15-300.fc30.x86_64

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by miguelamello** [comment]
|files.autoGuessEncoding is not working properly.

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.18-200.fc30.x86_64
|

Miguel Angelo Mello
Mobile: +55 22 99998-3366
WhatsApp: 5522999983366
