### ISSUE TITLE
ideavimrc and vim plugin

### ISSUE THREAD

**Issue by 1170801317** [microsoft/vscode#76727]
VSCode Version : 1.36.0

I don't know what's the difference between .ideavim and .vimrc.
Many vim plugin can't be supported because of the api of vscode.
The vim mode is just a simplified version.
It should be closer to origin vim.

**Comment by dbaeumer** [comment]
@1170801317 please file the issue against the owner of the VIM extensions here: https://github.com/VSCodeVim/Vim
