### ISSUE TITLE
Outline panel display incorrectly

### ISSUE THREAD

**Issue by LongChampion** [microsoft/vscode#76724]
- VSCode Version: 1.36
- OS Version: Ubuntu 18.04.2 LTS (Linux kernel: 4.18.0-25-generic)

Steps to Reproduce:

1. Open an empty workspace
2. Right click on the side-panel, then choose New File
3. Name it TEST.cpp
4. Loot ak Outline panel, there are many line with content "{}__7"

The problem disappears when I disable ms-vscode.cpptools extension.

**Comment by LongChampion** [comment]
![image](https://user-images.githubusercontent.com/47727306/60727273-b7772f00-9f67-11e9-8551-65f485e82782.png)

**Comment by dbaeumer** [comment]
Please report the issue against the owners of the CPP extensions you are using. Very likely: https://github.com/Microsoft/vscode-cpptools
