### ISSUE TITLE
Fix icon references in code

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76739]
@misolori SVGs can't be referenced from TS, because the loader will sometimes inline them an make them unavailable in the build:

https://github.com/microsoft/vscode/blob/6dabbf2963836fb41561c6b02a098ce9acde0aa5/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L519

cc @bpasero @alexandrudima

**Comment by misolori** [comment]
The references were already in place when I made the icon updates, I only updated the SVGs. Not sure who should update the references.

**Comment by misolori** [comment]
Looks like we've had these references for the past year:

https://github.com/microsoft/vscode/blame/bc7f5a72062e807a086e179c252f00ef2a1d55e5/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L456-L457

**Comment by bpasero** [comment]
@joaomoreno @alexandrudima I think we were always at risk of having this issue and now the close icon probably increased in size and as such got inlined and we see this issue.

However, I do not think we can say that TS code cannot reference icons anymore. We use this concept throughout our code a lot: register a menu item with an icon path. [`iconLocation`](https://github.com/microsoft/vscode/blob/51da09bae22fd2ff402c9eb8f57c22498587927d/src/vs/platform/actions/common/actions.ts#L25) is actually a core part of our menu system, so I am not sure how to fix this properly?

@alexandrudima should maybe comment how the icons are inlined. Is the issue that the [`appendEditorToolItem`](https://github.com/microsoft/vscode/blob/51da09bae22fd2ff402c9eb8f57c22498587927d/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L450) is dynamic and composes the icon path with a variable and as such the inlining does not work?

**Comment by bpasero** [comment]
@misolori looks like this came in via https://github.com/microsoft/vscode-distro/commit/0bbbc43f0c3b3517e55611432f96a69c07834974

**Bottom line:** a SVG icon cannot be referenced from both a CSS file as well as a TS file. The reason for that is that we have a build-step that tries to inline smaller SVG files into the CSS and removing it from disk. In the past I think we always managed to have a copy of the icon referenced from TS and a different one (even though the same contents) from CSS.

This is not easy to spot and we should improve on our linting to prevent this from happening (e.g. show a warning if a SVG icon is both referenced from CSS as well as TS).

I am not entirely sure if we have more cases like these, but for this case I suggest to go back to having 2 distinct icons for close.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/8d1ff2484905e0819d7cc52f54351b76953d54b5

Also noticed that the dirty icon was not used. This only reproduces when tabs are disabled. I made copies of the SVG icons with `-alt` suffix to ensure they do not get inlined.
