### ISSUE TITLE
Install 'code' command in PATH when not Administrator

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#7673]
I can't install `code` command-line on my school OS X session because I'm not the Administrator of the computer I work on.

I have to trick and put the previous command-line on my .zshrc, but it does not work well (sometimes only focuses on VSCode instead of opening the requested folder), and then I have a VSCode popup asking me to remove it from my `.zshrc` and install from the editor EACH time I open a window.

It would be cool to permit to install this as a non-Administrator.

**Comment by joaomoreno** [comment]
Create a link to `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code`.

You can add the following to your `.zshrc`: `alias code="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"`

**Comment by lax96** [comment]
I face the same issue with Windows

**Comment by itoonx** [comment]
Add this command to your bash profile

`code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* ;}`
