### ISSUE TITLE
Improve documentation for debugging missing search results

### ISSUE THREAD

**Issue by fortytw2** [microsoft/vscode#76737]
On this wiki page - https://github.com/Microsoft/vscode/wiki/Search-Issues#missing-search-results nothing is mentioned about vscode happening to also read a `.ignore` file by default too, I think it'd be a great addition to that section of something to check and may help someone else in the future. 

Here's the relevant `rg` documentation on this behavior - https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering

**Comment by roblourens** [comment]
I've added this to the wiki, thanks for pointing that out.
