### ISSUE TITLE
1.36.0 with PlatformIO crashes on Debian 10

### ISSUE THREAD

**Issue by renejeanmercier** [microsoft/vscode#76734]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by elsandosgrande** [comment]
@renejeanmercier Umm, you need to actually fill the template comment in with the details of your issue so that it can be worked on You cannot simply leave the comment blank, for all intents and purposes.

**Comment by renejeanmercier** [comment]
Hi,

I wish I could help, but as soon as it opens, it crashes (freezes). I
removed it (1.36.0) and reinstalled 1.35.1-1560350270, which work like a
charm.

*PlatformIO development environment :*

[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
board_build.core = maple
upload_protocol = dfu
upload_port = /dev/ttyACM0
monitor_speed = 115200


*Here is my system :*
~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

Ask me the question that might lead you to the fix and I will try to help.

Regards,


Rene-Jean Mercier
=======================

**Comment by renejeanmercier** [comment]
Hi Sandy,

Here is the message I get.


[image: image.png]


Regards,

René-Jean Mercier
==============================================

**Comment by dbaeumer** [comment]
@renejeanmercier what happens if you start with all extensions disabled (e.g. from a terminal with ` --disable-extensions`. Does it crash. If not this is very likely a problem with the extension itself and needs to be reported there. I guess that are using native node modules which is not supported right now.

**Comment by renejeanmercier** [comment]
Hi Dirk,

Good news!

What I thought of doing is to erase .platformIO directory and let 1.36.0
detect and reinstall platformIO. It now works!

But if I do an update All  I get this message "Reconnecting" (top center)
and this message stays there forever (see picture attached) until I close
and restart vscode.

It does not prevent it from working properly though. If I restart vscode
everything is back to normal. You might want to focus on this
"Reconnecting" glitch.

[image: image.png]

Thank you for your support.

Regards,


René-Jean Mercier
==========================================

Le sam. 6 juill. 2019, à 07 h 35, Dirk Bäumer <notifications@github.com> a
écrit :

**Comment by dbaeumer** [comment]
@renejeanmercier can you pleas attach the screen shot.

@sandy081 see comment https://github.com/microsoft/vscode/issues/76734#issuecomment-508924533 for the reconnect glitch.

**Comment by renejeanmercier** [comment]
Good morning Mr. Bäumer,

Here, attached, are two screenshots of the behavior. Also attached our
previous email exchanges.

Contrary to what I thought (my previous email), the problem is still there.
The application freezes. Sometimes I can start the compilation of my
program, sometimes not, before it freezes.

I can run a few test for you, but you need to direct me to the directory
(like /usr/share/...) where the application is located and spell the
command  (and parameters) you want me to execute.

Regards,


René-Jean Mercier.

=================================================
P.S. VSCode is an EXCELLENT application !!!!! I LOVE it !!!!!!
=================================================

Le lun. 8 juill. 2019, à 03 h 56, Dirk Bäumer <notifications@github.com> a
écrit :

**Comment by sandy081** [comment]
@renejeanmercier 

I do not see any screenshots here. 

Not sure what do you mean by following

> But if I do an update All  I get this message "Reconnecting" (top center)
and this message stays there forever (see picture attached) until I close
and restart vscode.

Can you please explain what do you mean by Update All and Reconnecting?

**Comment by renejeanmercier** [comment]
Hi Sandeep,

Did you get my message with files attached (emails and screen captures), a
few minutes ago ?

To answer your question : in PlatformIO there is a function Update all (see
screen capture attached on the left side) and the "Reconnecting" message
(top center).

Regards,


Rene-Jean Mercier

**Comment by sandy081** [comment]
@renejeanmercier No I do not see any attachments or schreeshots

**Comment by renejeanmercier** [comment]
Hi Sandeep,

Well you account provider/server strips out any/all attachments.

If you have an "honnest" email provider/server, like gmail, send me an
email, and I will reply.

Regards,


René-Jean Mercier

===============================

**Comment by sandy081** [comment]
@renejeanmercier I do not think it is stripped out from my side as I am checking it directly from `github` web page. Can you please log into github and check the issue thread.

**Comment by renejeanmercier** [comment]
![Screenshot_2019-07-08_07-12-31](https://user-images.githubusercontent.com/25909231/60896501-710a2480-a234-11e9-980c-53e3948cf8ec.png)

![Screenshot_2019-07-08_07-11-46](https://user-images.githubusercontent.com/25909231/60896522-7cf5e680-a234-11e9-8ebd-53319d1330b7.png)

![Screenshot_2019-07-08_06-21-49_VSCode](https://user-images.githubusercontent.com/25909231/60896534-854e2180-a234-11e9-940f-ff5bd7d30a1a.png)

![Screenshot_2019-07-08_06-24-51_VSCode](https://user-images.githubusercontent.com/25909231/60896553-8bdc9900-a234-11e9-92c0-76e4f169e78c.png)


https://mail.google.com/mail/u/0?ui=2&ik=f8f1c64b83&attid=0.1&permmsgid=msg-a:r5499028710684902561&th=16bd1386dba32027&view=att&disp=safe&realattid=f_jxu92d2e2


https://mail.google.com/mail/u/0?ui=2&ik=f8f1c64b83&attid=0.4&permmsgid=msg-a:r5499028710684902561&th=16bd1386dba32027&view=att&disp=safe&realattid=f_jxu92d2g3

https://mail.google.com/mail/u/0?ui=2&ik=f8f1c64b83&attid=0.5&permmsgid=msg-a:r5499028710684902561&th=16bd1386dba32027&view=att&disp=safe&realattid=f_jxu92d2h4

**Comment by renejeanmercier** [comment]
Hi Sandeep,

It looks like you have to explicitly drop the files in the windows. If attached to emails, they are discarded. :-(

Please look at the files attached a minute ago.

Looking forward to helping you solve the problem.

Regards,


Rene-Jean.

**Comment by renejeanmercier** [comment]
Hi Sandeep,

The 1. 36.1 version is working fine under 
PRETTY_NAME="Debian GNU/Linux 10 (buster)" 
NAME="Debian GNU/Linux" 
VERSION_ID="10" VERSION="10 (buster)" 
VERSION_CODENAME=buster ID=debian.

Thank you to you and to the team who works hard to offer to people like me such a great development application.

Regards,


Rene-Jean
===================

**Comment by sandy081** [comment]
@renejeanmercier This functionality is from PlatformIO extension and so I request you to file the issue against the extension.

**Comment by renejeanmercier** [comment]
Hi Sandeep,

I have done it. See the PlatformIO at https://community.platformio.org/.

Again, thank you for your support.

Regards,



RJMercier
