### ISSUE TITLE
Live Server not working

### ISSUE THREAD

**Issue by manthank705** [microsoft/vscode#76746]
Issue Type: <b>Bug</b>

The LIve Server Extension by Ritvik Dev is not working on vs code. The browser just doesn't open up.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|2.4.6
bracket-pair-colorizer-2|Coe|0.0.28
prettier-vscode|esb|1.9.0
sublime-keybindings|ms-|4.0.3
material-icon-theme|PKi|3.8.0
LiveServer|rit|5.6.1
indenticator|Sir|0.6.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
See #76676. This needs to be raised in the extension's project, not here in the VSCode one.

**Comment by manthank705** [comment]
> See #76676. This needs to be raised in the extension's project, not here in the VSCode one.

I am actually new to github so i don't know much about it!

**Comment by dbaeumer** [comment]
Closing since this needs to be addressed by the extension.
