### ISSUE TITLE
json schema defined in local file configured via json.schema in user settings.json is ignored

### ISSUE THREAD

**Issue by jan-dolejsi** [microsoft/vscode#76744]
- VSCode Version: 1.36 (also not working on the insider build)
- OS Version: Win 10 64bit

I am trying to configure a json schema that is not ready for sharing publicly via the user settings.json to avoid having to configure it in every workspace on my machine. 
Same configuration works in a workspace `.vscode/settings.json` though.

Steps to Reproduce:

1. Follow instructions to [configure json schemas in user settings.json](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-user-settings)
2. But instead of pointing to a schema hosted online, point to a local file via an absolute file url
3. Json file that matches the file name pattern does _not_ get validated
4. Move the same `json.schemas` configuration to the workspace `.vscode/settings.json` and the same Json file immediately starts being validated by the schema.

Does this issue occur when all extensions are disabled?: Yes

Here is how my `json.schemas` configuration looks like:

```json
    "json.schemas": [
        {
            "fileMatch": [
                "*.myConfiguration.json"
            ],
            "url": "file:///C:/directory/myConfiguration.json"
        }
    ]
```

And I am naturally testing it on a file named `test.myConfiguration.json` to match the fileMatch pattern.

**Comment by aeschli** [comment]
I just tried this setup and it worked for me. Not sure what went wrong in your case.

![image](https://user-images.githubusercontent.com/6461412/64271246-48a15c80-cf3d-11e9-83bf-c86cf20c829f.png)

**Comment by aeschli** [comment]
A way to debug this is by looking at the json language server log.
Define `"json.trace.server": "verbose" in the settings and check the logs.
