### ISSUE TITLE
"Updating visual" instead of "Updating Visual Studio Code"

### ISSUE THREAD

**Issue by salmanmkc** [microsoft/vscode#76742]
- VSCode Version: 1.36.0 (just updated to, not sure what it was before)
- OS Version: 10.0.18362 Build 18362

Steps to Reproduce:

1. Update Visual Studio Code with notification

**Comment by joaomoreno** [comment]
This is an issue in https://github.com/microsoft/inno-updater

**Comment by potatoqualitee** [comment]
Was coming here to file the issue as well. Got it on two machines, and is like 😬 because I had to consider if I had malware.

**Comment by angusgraham** [comment]
I also have this issue. My Windows DPI setting e.g. "Change the size of text, apps, and other items" is set to 150% as I have a 4K monitor. Presumably others with this issue are also at high DPI.

**Comment by potatoqualitee** [comment]
Yes! And I increase the sizes of my fonts too 👵

**Comment by salmanmkc** [comment]
> This is an issue in https://github.com/microsoft/inno-updater

Is this solved? Can't see any issues there, yet this is still open. Do you have a link to it? Would like to try and fix it again, now that I know which repo it is in.

**Comment by Joehuu** [comment]
Fixed in https://github.com/microsoft/inno-updater/pull/13.
