### ISSUE TITLE
Ctrl + Shift + F (and View > Search) - Opening search panel is broken

### ISSUE THREAD

**Issue by Wolven531** [microsoft/vscode#76749]
Issue Type: <b>Bug</b>

1. Open VSC Insiders Edition (1.37.0-insider)
1. Hit command to open Search (Ctrl + Shift + F is default)

## Expected
Show search panel

## Observed
Notification w/ error message: "Cannot read property 'searchResult' of undefined

Afterwards, attempting to hit the shortkey again dispaly different notification w/ error message: "Cannot read property 'toggleReplace' of undefined"

### Notes
Behavior also occurs when trying to open search through the View menu item (at the top of the application window)

VS Code version: Code - Insiders 1.37.0-insider (bbfd565b1be08703831d261859955c4fd188b555, 2019-07-05T15:42:24.267Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
dotnet-test-explorer|for|0.7.1
vscode-guid|hea|1.4.15
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
vsls-whiteboard|los|0.0.8
vscode-docker|ms-|0.6.4
csharp|ms-|1.20.0
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vsliveshare-pack|ms-|0.3.2
debugger-for-chrome|msj|4.11.6

</details>

![image](https://user-images.githubusercontent.com/2125913/60743361-7e6e9880-9f2e-11e9-85d5-2040c3fa7939.png)
![image](https://user-images.githubusercontent.com/2125913/60743366-84647980-9f2e-11e9-8eae-1b1fc06e563c.png)

**Comment by gjsjohnmurray** [comment]
I can't reproduce it, testing with the save VSCode build, but mine is a user setup install rather than a system setup install. And my Windows is 10.0.16299.

Please test with all your extensions disabled, in case one of them is causing your problem.

**Comment by Wolven531** [comment]
Attempted on second laptop (also Win10, also system install) w/ all extensions disabled. Same result. See screenshots below:

![image](https://user-images.githubusercontent.com/2125913/60751703-cc5bbe80-9f77-11e9-8e49-20edb38db397.png)
![image](https://user-images.githubusercontent.com/2125913/60751704-cf56af00-9f77-11e9-92e7-7915716e3f2d.png)
![image](https://user-images.githubusercontent.com/2125913/60751706-d2519f80-9f77-11e9-8cf9-0dee318aeaef.png)
![image](https://user-images.githubusercontent.com/2125913/60751713-e09fbb80-9f77-11e9-8ed6-b806d21d57ea.png)

**Comment by Wolven531** [comment]
> /duplicate of #76701

Good catch. Thanks!
