### ISSUE TITLE
Please tag the 1.2.1 release

### ISSUE THREAD

**Issue by fusion809** [Microsoft/vscode#7674]
Hi,

Those of us building VSCode from source are being left behind when new releases come out as binaries but the corresponding source code is not tagged, so I'm here to request that the 1.2.1 release be tagged.

Thanks for your time,
Brenton

**Comment by Tyriar** [comment]
Done https://github.com/Microsoft/vscode/tree/1.2.1

I created https://github.com/Microsoft/vscode/issues/7677 to prevent this in the future.
