### ISSUE TITLE
javascript.updateImportsOnFileMove is too slow, buggy and has bad modal prompt UX

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#76748]
- VSCode Version: latest macOS  (any, e.g. 1.35.1)
- OS Version: latest (any, e.g. 10.14.5)

Steps to Reproduce:

1. enable javascript.updateImportsOnFileMove
2. rename any file

# Problems
- **buggy**: If a user fixes manually some imports or edit some files with imports that will be affected, the file's code becomes a broken mess of something awful after `updateImportsOnFileMove` had complete
- **too slow**: it takes 30+ sec on a medium project (40 000 lines / 400 files).
- **bad UX**: when blocking modal window appeares user can press space as she codes and accept 'Yes, and do it automatically in the future'. Solution: use usual for VSCode good right-bottom non-modal SnackBars. [Never Use Modals Please](https://modalzmodalzmodalz.com)! 

Does this issue occur when all extensions are disabled?: Yes

![telegram-cloud-photo-size-2-5258076337778830144-y](https://user-images.githubusercontent.com/6201068/60742493-412df900-9f76-11e9-99f3-6d1a22f3e8f9.jpg)

**Comment by mjbvz** [comment]
1. Please open specific issues with repo steps for any bugs

1. Tracked by https://github.com/microsoft/TypeScript/issues/30535

1. We intentionally use a modal to block user input. Otherwise the user could make edits that would corrupt the update of imports

**Comment by a-x-** [comment]
3. We intentionally use a modal to block user input

This is totally not work
Please use modal in cases when it appeares in a not longer than 300ms, otherwise show no-modal SnackBar

You cannot make it fast in all the situations I think, so this is should be improved

Otherwise user accept accidentally the modal by pressing <kbd>space</kbd> or <kbd>enter</kbd> as she codes
