### ISSUE TITLE
file is remove, but still show in problems

### ISSUE THREAD

**Issue by goldpicker** [microsoft/vscode#76757]
Issue Type: <b>Bug</b>

when I delete file from file explorer. except I reboot the vscode, It's still report proplems with these deleted files.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 17.6.0
Remote OS version: Linux x64 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|-psn_0_3781531|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: RemoteDevelopWithForward|
|OS|Linux x64 4.15.0-51-generic|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 1596)|
|Memory (System)|15.56GB (3.07GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
vscode-eclipse-keybindings|alp|0.10.0
code-gnu-global|aus|0.2.2
sftp-sync|blo|0.0.3
jira-issues|crh|1.1.0
FreeMarker|dco|0.0.9
xml|Dot|2.5.0
auto-close-tag|for|0.5.6
vscode-lombok|Gab|0.9.8
mysql-syntax|jak|1.3.1
plantuml|jeb|2.11.1
docthis|joe|0.7.1
sftp|lix|1.12.7
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
java|red|0.46.0
vscode-xml|red|0.7.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-jetty|Sum|0.1.11
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
html-css-class-completion|Zig|1.19.0

</details>

**Comment by dbaeumer** [comment]
@goldpicker can you provide me with a screen short showing these errors. The extension producing those is responsible for removing them.

@sandy081 are we removing them on file delete. I remember we discussed that some when.

**Comment by sandy081** [comment]
@dbaeumer We discussed but did not consider it yet.

**Comment by dbaeumer** [comment]
@sandy081 thanks

**Comment by goldpicker** [comment]
![Screen Shot 2019-07-25 at 8 10 54 PM](https://user-images.githubusercontent.com/2731456/61873585-e6eedb00-af18-11e9-999a-8d9856c8e7b8.png)

**Comment by dbaeumer** [comment]
@goldpicker those come from the Java extension. Can you please report the issue there.
