### ISSUE TITLE
Markdown preview doesn't support html self closing tags

### ISSUE THREAD

**Issue by mhofman** [Microsoft/vscode#7675]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a `.md` file with the following content:
```markdown
Hello

<a name="custom-heading"/>
# Heading

Some text
```
2. Open preview for the file
3. Observe "Heading" and "Some Text" are blue and have anchor styling.

While a self closing anchor tag isn't valid html, it's quite common to find them on Github, which seem to handle them correctly. Example: https://raw.githubusercontent.com/wiki/adam-p/markdown-here/Markdown-Cheatsheet.md

**Comment by rebornix** [comment]
@mhofman thanks for reporting this issue, it's quite interesting. Actually GitHub don't have a consistent rendering for invalid html, like in Wiki you provided, 

```
<a name="custom-heading">
# Heading
```
will be generated as 

```
<p><a name="user-content-headers"></a></p>
<h2>
<a id="user-content-headers" class="anchor" href="#headers" aria-hidden="true"></a>Headers
</h2>
```

This output makes no sense to me as I don't see any reason to have two `<a>` elements.

Moreover, if you type in the same markdown content here (github issue)

```
<a name="user-content-custom-heading">
<h1>Heading</h1>
<p>Some text</p></a>
```

See? `Some text` is included in the `a` element, just the same as we do. I'm not saying it's a correct way but the inconsistency shows that people are not clear about how to handle **invalid** HTML correctly. How can we say the output of an invalid input is valid?

But let me emphasize, we should have a clear solution for this in Visual Studio Code. Recently we are moving Markdown parser from marked.js to markdown-it, once the feature is online, let's see how to make it happen. Before that, I'd like to share a workaround with you

```
<a name="custom-heading">

# Heading
</a>

Some text
```

Tricky but works :smile:

**Comment by mhofman** [comment]
Thanks for looking into it. I also did more tests and I'm tempted to say GitHub's html handling is very lenient and it might not be worth the effort replicating it. I'm not even sure if the rewrite of the self closing anchor tag comes from the markup parser itself, or the id/name rewrite they do afterwards (prefixing all with `user-content-`).

I'd say this is working as intended in VSCode. I'll try to fix any broken tags I come by instead.

**Comment by rebornix** [comment]
@mhofman our next move for markdown is allowing you to add plugins for markdown-it. Once we have that, you can customize the id/name generation by yoir own script.
