### ISSUE TITLE
Marketplace search does not weight rating heavily enough

### ISSUE THREAD

**Issue by Almenon** [microsoft/vscode#76758]
Reposting from https://github.com/Microsoft/vscode/issues/42890:

When I search for "python" "python extended" is above my extension (arepl) despite having literally 0 reviews vs 17/17 5-star reviews. In terms of download count we are very close (176k vs. 180k) so if the reviews were taken into account I would expect AREPL to be ranked higher.

I would even go so far as to say that reviews should be more important than download count in influencing search ranking (assuming you have enough reviews to be statistically valid). As a user when I search for things I want to find the best extensions, not the most downloaded extensions, but my extension has good reviews so I am biased on that front :P

I'm not sure what algorithm is being used but there's some existing ones that may be helpful:

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html
https://stackoverflow.com/questions/1411199/what-is-a-better-way-to-sort-by-a-5-star-rating

**Comment by sandy081** [comment]
@kesane-msft Can you please respond to this?

**Comment by Almenon** [comment]
Update: I think it's the titles that are causing AREPL to be ranked lower - AREPL now has more downloads and more stars. Maybe the order of the words matters? So if "Python Extended" was "Extended python" it would be lower? I still don't think a unreviewed extension should be so high up in the search rankings.

**Comment by sandy081** [comment]
/duplicate 
https://github.com/microsoft/vscode/issues/62472
