### ISSUE TITLE
"cmd" non è riconosciuto come comando interno o esterno

### ISSUE THREAD

**Issue by MineFriend** [microsoft/vscode#76751]
Issue Type: <b>Bug</b>

ogni volta che provo a fare il debug di un file mi da questo errore " "cmd" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch."  ho provato a cambiare da  "integratedTerminal" a "externaTerminal" ma non funziona comuque anche avviando visula studio code con i permessi di amministratore non succde nulla

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|2.1.32
vscode-language-pack-it|MS-|1.36.2
python|ms-|2019.6.22090
vetur|oct|0.21.1
vscodeintellicode|Vis|1.1.7

</details>

**Comment by MineFriend** [comment]
Translate (with deepl translator): Title: "cmd' is not recognised as internal or external command

body: every time I try to debug a file gives me this error " "cmd" is not recognized as internal or external command,
an executable program or a batch file." I tried to change from "integratedTerminal" to "externaTerminal" but it does not work as well even starting visula studio code with administrator permissions does not happen anything

**Comment by isidorn** [comment]
What program / type are you debugging? Can you share your `launch.json` configuration?
