### ISSUE TITLE
File/Dir is not deleted when Del key is pressed

### ISSUE THREAD

**Issue by zyrikby** [microsoft/vscode#76750]
- VSCode Version: 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338)
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1. Select a file in Explorer
2. Press Del button or Shift+Del buttons

Current behavior: A red highlighted box with "Delete" word appears in Explorer
Expected behavior: The "delete file" dialog appears / The "delete file permanently" dialog appears

Does this issue occur when all extensions are disabled?: Yes

**Comment by Quincunx271** [comment]
I also have this issue. Some more information:

* Repros on Ubuntu 16.04. (vscode version is the same)
* Does _not_ repro on Windows 10. (vscode version is the same)
* Works when multiple files are selected as well.
* The text "Delete" appears in the filter/search location, where you can highlight files matching the filter.
* Pressing the Del button multiple times makes "DeleteDelete", where the number of repetitions of the word is how many times you pressed the button.

**Comment by lucasbasquerotto** [comment]
I'm also having this issue in Ubuntu 18.04.

```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-21-generic snap
```

**Comment by jarekb123** [comment]
I'm also having this issue on Ubuntu 19.04.
```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
```
![image](https://user-images.githubusercontent.com/15148100/60755327-6fe7b600-9fee-11e9-9347-8822bf245307.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode/issues/76514
