### ISSUE TITLE
Searches search in excluded files.

### ISSUE THREAD

**Issue by TerryFranguiadakis** [Microsoft/vscode#7676]
- VSCode Version: 1.2.1 (1.2.1)
- OS Version: osx 10.11.5 (15F34)

Steps to Reproduce:

1. Do a search with "files to exclude" set with *\.csproj
2. perform search

Result:
The search searches *\.csproj files.... 

<img width="549" alt="screen shot 2016-06-14 at 2 04 27 pm" src="https://cloud.githubusercontent.com/assets/625737/16059732/3e39d3ac-3239-11e6-9006-8b206f7b2676.png">

**Comment by sandy081** [comment]
@TerryFranguiadakis Expression you have to use in this case is `**/*.csproj`

For more info please click on the glob pattern button on the right

Thanks
