### ISSUE TITLE
TypeError: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76766]
TypeError: Cannot read property 'focus' of null
at HTMLElement.proto.focus ( VS :318:24)
/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#556:16 (focus)
/vs/workbench/contrib/extensions/electron-browser/extensionEditor.ts#486:22 (focus)
/vs/workbench/browser/parts/editor/editorGroupView.ts#748:22 (focus)
/vs/workbench/browser/parts/notifications/notificationsToasts.ts#300:40 (removeToast)
/vs/workbench/browser/parts/notifications/notificationsToasts.ts#114:16 (onDidNotificationChange)
/vs/workbench/browser/parts/notifications/notificationsToasts.ts#92:63 (call)
/vs/base/common/event.ts#558:15 (fire)
/vs/workbench/common/notifications.ts#212:34 (call)
/vs/base/common/event.ts#39:20 (call)
/vs/base/common/event.ts#558:15 (fire)
/vs/workbench/common/notifications.ts#620:19 (close)
/vs/workbench/browser/parts/notifications/notificationsCommands.ts#111:17 (apply)
/vs/platform/instantiation/common/instantiationService.ts#60:13
at Proxy._tryExecuteComm

**Comment by mjbvz** [comment]
Should have been fixed by e14492ab96f2f95229c14f988079dd4f4256eb02
