### ISSUE TITLE
Find widget hangs around after toggling `renderSideBySide`

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#76773]
Issue Type: <b>Bug</b>

```json
"diffEditor.renderSideBySide": true,
```

1. Open diff
1. Search <kbd>Ctrl</kbd>+<kbd>F</kbd> in the left split side (deleted)
1. `toggle.diff.renderSideBySide`
1. Find widget is partly visible 

Insiders 1.37.0-insider (7e03eb1a1fce3beb6ccea5f3b8f828e01940be61); Stable 1.36.0  (0f3794b38477eea13fb47fbe15a42798e6129338)
OS version: Windows_NT x64 10.0.18362

**Comment by rebornix** [comment]
@usernamehw can you help me understand *Find widget is partly visible* ? A screenshot can help.

**Comment by usernamehw** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/9638156/61434275-2d9f6c80-a93e-11e9-8b3f-fdd3cbab88ac.png)
