### ISSUE TITLE
Cannot install vsix from shell

### ISSUE THREAD

**Issue by zyrikby** [microsoft/vscode#76770]
In the [documentation](https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/) it is written that it is possible to install extension offline using command  `code <path_to_vsix>`. However, in my case instead of installing an extension from vsix, vscode opens the file.  

- VSCode Version: 1.36.0
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1. Run command `code <path_to_vsix>`

Current behavior: vscode tries to open vsix as text file
Expected behavior: vscode should install vsix file

**Comment by usernamehw** [comment]
Is this even official documentation?

|  Argument       |     Description      |
| ------------- |-------------|
| `--install-extension <ext>`  |  Install an extension. Provide the full extension name `publisher.extension` as an argument. Use `--force` argument to avoid prompts. |

https://code.visualstudio.com/docs/editor/command-line

**Comment by zyrikby** [comment]
@usernamehw this is a good point! Indeed, I did not realize that this is not official documentation. Your approach is working. So, I think the issue can be closed!
