### ISSUE TITLE
[config] `markdownDescription` is missing from autocomplete for nested properties

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#76771]
Issue Type: <b>Feature Request</b>

1. In `package.json` create nested configuration
```javascript
"configuration": {
    "properties": {
        "smth": {
            "type": "object",
            "properties": {
                "nested": {
                    "|"
                }
            }
        }
    }
}
```
2. Autocomplete only has `description` and missing `markdownDescription` (although it's working)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
Not easy to add unless we want to repeat the whole schema-schema.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/configurationExtensionPoint.ts has that schema.
PR's welcome.
