### ISSUE TITLE
Simple File Picker - Selecting a file without leading / prefills input undesirably

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#76775]
- VSCode Version: Insiders (1.37.0)
- OS Version: Linux

Steps to Reproduce:

1. Open the simple file picker
2. Clear the default path from the input
3. Wait a moment for the root files to be shown
4. Press on the down button twice
5. Notice the path in the input is prefixed by the first letter of your first selection

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@diabolicle is this the native file picker. Can you post a video showing what you are seeing?

**Comment by dbaeumer** [comment]
@alexr00 FYI

**Comment by alexr00** [comment]
Nice bug, thank you for finding!
