### ISSUE TITLE
Allow to run VSCode hidden in the background for faster opening

### ISSUE THREAD

**Issue by eddydu44** [microsoft/vscode#76778]
Issue Type: <b>Performance Issue</b>
The application is too long to open. Sometimes, i just want to open a draft page to save some part of code or anything else.
Maybe you could add an option to keep a caching process in the background in order to launch the app as fast as w10 apps ^^

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18932

**Comment by tecosaur** [comment]
Something like emacs server :smiley:
