### ISSUE TITLE
a sudden break here;

### ISSUE THREAD

**Issue by Jsoneft** [microsoft/vscode#76774]
Issue Type: <b>Bug</b>

 puts("**********************************");“***”are hidden
here once I add a "\n" like  puts("\n**********************************");
it just stopped responding
![image](https://user-images.githubusercontent.com/50447410/60756590-a5fa5980-a031-11e9-8e88-0a25317fd61a.png)
![image](https://user-images.githubusercontent.com/50447410/60756594-b27eb200-a031-11e9-96eb-886877c53caa.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
eclipse-new-java-project|mel|1.0.0
python|ms-|2019.6.22090
cpptools|ms-|0.24.0
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1

</details>

**Comment by dbaeumer** [comment]
C/C++ code.

**Comment by Jsoneft** [comment]
> C/C++ code.

yeah

**Comment by alexr00** [comment]
Opened an issue in the owning repo. I'll leave this issue open to add a test once it's fixed.

**Comment by Jsoneft** [comment]
Gota say that you guys work so efficient , PROBLEM solved instantly , 
![image](https://user-images.githubusercontent.com/50447410/60801093-f5af6100-a1a8-11e9-9350-059d493fe88b.png)

**Comment by Jsoneft** [comment]
thanks !

**Comment by alexr00** [comment]
Hmm. Not sure how it is fixed here. Regardless, I'm going to reopen this issue so that I remember to add a test for this case :)
