### ISSUE TITLE
Sidebars' settings are not persisted

### ISSUE THREAD

**Issue by a-x-** [microsoft/vscode#76779]
- VSCode Version: 1.35.1
- OS Version: 10.14.5

Steps to Reproduce:

1. setup any bar, e.g.:
    - hide git sources panel, 
    - or set outline to sort as abc (btw, no one wants to sort by type)
2. do it every week again and again ...

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
I can repro with source control providers panel. 

@joaomoreno Assigning to you as it happens only with this panel

@a-x- I cannot repro with setting outline sort type. This is retained for me

**Comment by joaomoreno** [comment]
> I can repro with source control providers panel.

Steps?

**Comment by sandy081** [comment]
![Kapture 2019-07-12 at 15 33 54](https://user-images.githubusercontent.com/10746682/61131874-898b7080-a4ba-11e9-9d37-b9c109d9a7e2.gif)

**Comment by a-x-** [comment]
> @sandy081: setting outline sort type are retained for me

that settings are disappeares less often, might be with vscode upgrading?

**Comment by sandy081** [comment]
> that settings are disappeares less often, might be with vscode upgrading?

They are stored as ui state. @bpasero any insights?

**Comment by bpasero** [comment]
@a-x- to be clear you:
* start vscode
* set outline to sort as abc
* reload window

=> that setting is gone and back to where it was?

**Comment by a-x-** [comment]
> @joaomoreno, This is purposeful on SCM, such that the user is aware of open repos.

Yeah I know, some people in some cases might be look it useful. But for us it’s useless all the time, so issue is about respect our settings :)

**Comment by a-x-** [comment]
> @bpasero 
It’s not every time like this. Looks like settings gone when vscode upgrades or in some other cases. But is caused more then 4 times for recent months

**Comment by joaomoreno** [comment]
How many repositories do you have open usually?

**Comment by a-x-** [comment]
@joaomoreno, I have 1–3 repo/projects in different vscode windows usually, mostly 2.
