### ISSUE TITLE
Terminal not working.

### ISSUE THREAD

**Issue by divijish** [microsoft/vscode#76782]
Issue Type: <b>Bug</b>

Terminal is not working properly. On opening it neither is it showing present working directory nor any command I type. It is completely blank. ![image](https://user-images.githubusercontent.com/24991204/60760604-883eeb80-a055-11e9-8932-38fcc029132a.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by zenicu** [comment]
I have this issue, plus I cannot change directories

**Comment by dankox** [comment]
For me, it just takes forever to start (around 70 seconds).... 
It looks blank for a long time and then the shell comes up.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by zenicu** [comment]
I am running on Windows 8...

**Comment by Tyriar** [comment]
The original issue is about Windows 10:

> Windows_NT x64 10.0.17763

**Comment by petval** [comment]
I also have this issue.
Microsoft Windows [Version 10.0.17763.615] (so 1809)
