### ISSUE TITLE
View > Views > Problems results in "No handler found"

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#7678]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Steps to Reproduce:

1. View > Views > Problems
2. Results in "No handler found for the command: 'workbench.action.markers.panel.toggle'

**Comment by gregvanl** [comment]
There is also no keyboard shortcut shown in the dropdown.  Should this show Ctrl+Shift+M (on Windows)?

**Comment by gregvanl** [comment]
The Problems view command also doesn't toggle like other views (ex. Output, Debug Console, Integrated Terminal).  Running the View > Views > Problems command or using the keyboard shortcut should toggle the view.

**Comment by sandy081** [comment]
@gregvanl This was broken is yesterday's build due to the change - 2f4745320864b07abedf7b6e7442cd6ddf4e36e2

Fixed yesterday - 5fd7ffd07fee48632387157e296939f45d601aa3

This is working as expected in today's build.

Thanks
