### ISSUE TITLE
Marketplace: Not able to add a second reply to a feedback thread

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#76787]
In the VS Code marketplace for extensions, the `Rating &Review` section allows extension authors to engage with the feedback they receive. We can reply to one of the reviews, but then there is provision to add another comment. 

For reference, please see the screenshot below. The `Reply` link only shows on the original unreplied comment.

<img width="1230" alt="Screen Shot 2019-07-06 at 5 28 00 PM" src="https://user-images.githubusercontent.com/16890566/60762380-69b80080-a013-11e9-8a60-fb39ca535937.png">

This is not an issue with VS Code, but since this repository is also tracking customer reported issues for the marketplace and has a label `marketplace`, I chose to create the issue here. Apologies if there is another preferred location for this feedback

**Comment by sandy081** [comment]
@kesane-msft This is an issue specific to market place and nothing to do with VS Code. Please transfer this to Maketplace.

**Comment by harishkragarwal** [comment]
It is true that for reviews in the Marketplace folks can't have a threaded conversation. However, I have seen quite a few cases where folks have appended their review/response and have had a conversation. Yes, it is not the perfect way. The Q&A capability, if enabled by the publisher, in the Marketplace allows for a threaded conversation.
