### ISSUE TITLE
Treat warning as error (.Net Core Project)

### ISSUE THREAD

**Issue by shpsyte** [microsoft/vscode#76785]
Hi, I would like to see an option that I can set a **warning as an error** in my .net core project.

Will be perfect!

Cheers

**Comment by dbaeumer** [comment]
@shpsyte please report the issue against the .Net Core extension you are using which is responisble to generate these errors.

**Comment by shpsyte** [comment]
Thank you, I've been posted.

https://github.com/dotnet/core/issues/3002
