### ISSUE TITLE
Markdown line breaks and setting `files.trimTrailingWhitespace`

### ISSUE THREAD

**Issue by c3er** [microsoft/vscode#76786]
Issue Type: <b>Bug</b>

Linebreaks in Markdown files are made with 2 trailing whitespaces at the and of a line. I use this Markdown feature sometimes. But in my VS code I have the setting `files.trimTrailingWhitespace` set to `true` and these line breaks are removed when I save a Markdown file.

Expectation: If `files.trimTrailingWhitespace` is set to `true` all trailing whitespaces are removed *except* the 2 trailing whitespaces that occur sometimes in Markdown files.

[A source for my claim about linebreaks](https://www.markdownguide.org/basic-syntax/#line-breaks)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
To disable this in markdown files, set:

```md
"[markdown]": {
    "files.trimTrailingWhitespace": false
}
```

**Comment by c3er** [comment]
@mjbvz Thanks for the workaround! Though I'd like to cleanup not necessary trailing whitespaces in Markdown files too.

I'm wondering about the "out-of-scope" tag. Is there a project where this issue could fit better? I didn't find one in [the list of related projects](https://github.com/Microsoft/vscode/wiki/Related-Projects).

**Comment by mjbvz** [comment]
We are not going to fix this in VS Code core. You can write an extension if you want customized  whitespace trimming behavior

**Comment by yannl35133** [comment]
Considering Markdown is broken by "trimTrailingWhitespace", why does the Markdown extension not set
```json
"[markdown]": {
    "files.trimTrailingWhitespace": false
}
```
in the settings itself ?
