### ISSUE TITLE
Allow us to define width of the find widget

### ISSUE THREAD

**Issue by skyhirider** [microsoft/vscode#76795]
The width of the find widget (Ctrl+F) can be changed by dragging the mouse.

Could you add a setting under Text Editor -> Find that would allow us to set the default size of the widget?

I would prefer it to start maximized (100% width) instead of having to drag it.

Or have it dynamically expand as more text is typed into it.

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/15727
