### ISSUE TITLE
Javascript (*.js) support doesn't consider namespaced xml 

### ISSUE THREAD

**Issue by KennethScott** [microsoft/vscode#76790]
- VSCode Version:  1.36.0
- OS Version:   Windows 10 v1903

Steps to Reproduce:

1.   Create a new javascript .js file and paste the following contents:

```
var soap = new Namespace('soap', 'http://schemas.xmlsoap.org/soap/envelope/');

default xml namespace = soap;

var xml = 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
   <soap:Header>
      <soap:userId>{userId}</soap:userId>         
   </soap:Header>
  </soap:Header>
  <soap:Body>
   <soap:CustomerId>{customerId}</soap:CustomerId>
  </soap:Body>
</soap:Envelope>;

```
2.  Watch the squigglies and errors thrown

I realize this is e4x AKA "ECMAScript for XML" syntax that is deprecated and no longer supported. However I also realize it is recognized fine/error free in an xml/\*.xml file.  It's only in a javascript/\*.js file that this is reported as an error.  

Thank you.

**Comment by mjbvz** [comment]
We don't offer builtin support for ECMAScript for XML and have not plans to add this. Please check if there is an extension in the marketplace that offers this

**Comment by KennethScott** [comment]
@mjbvz, sorry I should have explained my request better.  I wasn't actually requesting support for ECMAScript for XML.  I guess I was curious if the syntax checking could be adjusted to allow for namespaced xml the way it allows for non-namespaced xml.  

To better explain,  this xml (in a javascript file) produces no errors:
```
var xml2 = 
<Envelope>
  <Header>
   <Header>
      <userId>{userId}</userId>         
   </Header>
  </Header>
  <Body>
   <CustomerId>{customerId}</CustomerId>
  </Body>
</Envelope>;
```

While a namespaced equivalent like the example in my original message produces numerous errors.

Also, I have searched for alternative language server extensions that might support e4x, but I haven't had any luck.  I'm doubtful anyone cares these days as e4x is essentially a dead animal.  I was just curious if it would be simple enough to perhaps adjust a regex pattern somewhere to allow for the namespace: within the <> brackets since the non-namespaced xml seemed to be allowed.   

It's usable as-is regardless, it's just hard to ignore the large number of errors generally generated from a given script file.  Anyway, thank you for the consideration.

**Comment by mjbvz** [comment]
We ship built-in support for jsx in plain js files. Your example without the namespaces is valid jsx which is why there is no errors.

However, there are no plans to generalize our jsx support to ecmascript for xml
