### ISSUE TITLE
MacOS Dock icon is way too small

### ISSUE THREAD

**Issue by olhadanylchenko** [microsoft/vscode#76794]
![Знімок екрана  о 10 42 08](https://user-images.githubusercontent.com/39850741/60766063-32456480-a0a4-11e9-9991-fc30e0da15c3.png)

Issue Type: <b>Bug</b>

I'm not sure how to reproduce this, but the issue started after a recent update. When I open VS Code the icon in the dock is so small I can't see it without zooming in the dock.

In addition to being so small it's barely visible, clicking on the tiny icon doesn't do anything (switch application focus).

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|40, 27, 23|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by dbaeumer** [comment]
Looks like. Dups #63068
