### ISSUE TITLE
Mouse back shortcut stopped working

### ISSUE THREAD

**Issue by vincaslt** [microsoft/vscode#76797]
Version: 1.36.0 (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

After the update, shortcut on the mouse to go back/forward has stopped working.
The mouse button that is bound to "back" action used to work out of the box in the editor, now it doesn't.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by little-tomorrow** [comment]
I also found this problem, now I can only use Alt + LeftArrow to go back.

**Comment by FDIM** [comment]
Any workarounds? I can't seem to bind back/forward keys to shortcuts either. It almost seems like that these 2 buttons are now treated like clicks e.g. explorer/command window closes when you press one of these button outside of the modal

**Comment by dbaeumer** [comment]
Dups #71318
