### ISSUE TITLE
Does VS code support automatically importing components for Typescript?

### ISSUE THREAD

**Issue by bkbonner** [Microsoft/vscode#768]
Are there any plans to supports automatic imports for typescript?   I don't think this currently works even if typings files are included.

Thanks.

**Comment by dbaeumer** [comment]
@bkbonner what do you mean by 'automatic' imports. Can you please provide an example.

**Comment by bkbonner** [comment]
i.e.   If there's a package where I've included the typings.d.ts file.   i.e. Angular2

and I type a decorator like:

*@Comp*onent

If I hit ctrl+space after @Comp, I'd like it to finish the word Component, but I'd also like it to add the import to the top of the file if it exists if it's unique, or a mechanism to add the import through a hotkey of some sort.   I'm wondering if this is planned?   It seems like it might be possible with an extension, but I'm not sure.

**Comment by bkbonner** [comment]
It looks like this is a dupe of:  https://github.com/Microsoft/vscode/issues/818

**Comment by dbaeumer** [comment]
Yes duplicates #818
