### ISSUE TITLE
settings.json file changed into binary or unsupported encoding text

### ISSUE THREAD

**Issue by OmorFaruque-65** [microsoft/vscode#76804]
I have accidentally deleted my C:/users/userExample/AppData folder where vscode related information such as extension, settings.json, etc located. Now I have recovered the AppData folder using recovery software. So I also able to recover the vscode related folder that resides in the AppData folder. But now the settings.json file that I have retrieved is corrupted (see below img)-

![Untitled](https://user-images.githubusercontent.com/33119311/60770624-e2e05200-a0fe-11e9-98c8-3f910ffefdc7.png)

![Untitled1](https://user-images.githubusercontent.com/33119311/60770625-e378e880-a0fe-11e9-988e-7b151da76628.png)

My settings.json file contains important setup that speeds up my work. Is there any way to get back the original settings from this corrupted file. Here is the corrupted settings.json file -
[settings.zip](https://github.com/microsoft/vscode/files/3365825/settings.zip)
I really need the old settings.json file cause i can't remeber the old settings that i did.

**Comment by OmorFaruque-65** [comment]
Please help me out on this problem

**Comment by sandy081** [comment]
@OmorFaruque-65 Not sure if we can be helpful here, but please check out if there is a software outside to retrieve the content.
