### ISSUE TITLE
Integrated Terminal should be able to be moved

### ISSUE THREAD

**Issue by avarun42** [Microsoft/vscode#7680]
I would like to be able to move the integrated terminal to a vertical pane alongside my code, rather than below my code.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/3360 https://github.com/Microsoft/vscode/issues/7161

**Comment by maxfriedmann** [comment]
oh that would be great! +1

**Comment by isidorn** [comment]
Dup of #2806
