### ISSUE TITLE
workbench.activityBar.visible not working

### ISSUE THREAD

**Issue by JMS55** [microsoft/vscode#76803]
Issue Type: <b>Bug</b>

Pressing alt with `workbench.activityBar.visible` set to `false` still causes the custom menu bar to underline the first lettter of each entry

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.1.16-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2297)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.60GB (7.99GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-icon-theme|jtl|1.6.5
git-graph|mhu|1.10.0
rust|rus|0.6.1
tabnine-vscode|Tab|1.1.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@JMS55 I think you might mean to set `window.menuBarVisibility` to `hidden` or `window.enableMenuBarMnemonics` to `false`
