### ISSUE TITLE
PHP auto-closing HTML tags

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/vscode#76800]
When editing a plain HTML file typing `"</"` brings up closing tag suggestions popup

When the file type is "PHP" though - this does not work. It would be a great addition.

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode/issues/62077

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode/issues/62077
