### ISSUE TITLE
Can not search in Files

### ISSUE THREAD

**Issue by technificentConsulting** [microsoft/vscode#76808]
Issue Type: <b>Bug</b>

When hitting CTRL + Shift + F or accessing Find in Files I receive an error and am unable to search in files.  The search window does not display.  The same issue occurs with Replace in Files.

VS Code version: Code - Insiders 1.37.0-insider (7e03eb1a1fce3beb6ccea5f3b8f828e01940be61, 2019-07-05T18:31:56.611Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
dotnet-core-commands|mat|1.0.6
eclipse-new-java-project|mel|1.0.0
mssql|ms-|1.6.0
csharp|ms-|1.20.0
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
java|red|0.46.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
If your `search.location` setting is `panel` then this is probably a duplicate of #76708 and the workaround is to reset that setting to its default, `sidebar`

**Comment by gjsjohnmurray** [comment]
Update: `"search.location": "panel"` seems to be fixed in the latest insiders when I tested just now

Version: 1.37.0-insider (user setup)
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:37:36.104Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by technificentConsulting** [comment]
Thank  you @gjsjohnmurray.  I verified that the the workaround resolves the issue as well the latest Insiders Update.
