### ISSUE TITLE
Wrong amount of characters is being displayed with emoji

### ISSUE THREAD

**Issue by Wouterr0** [microsoft/vscode#76802]
- VSCode Version: 1.36.0
- OS Version: Windows 64 bit 10.0.18362

Steps to Reproduce:

1. Open a file containing emojis
2. Select some emojis

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/41055533/60770182-879b6900-a0d8-11e9-9b8f-b61a57d647a0.png)

**Comment by rebornix** [comment]
@Wouterr0 can you help provide the original content of the file shown in the screenshot to help reproduce?

**Comment by Wouterr0** [comment]
You can hit `win` and `.`(dot) key to get some emojis but here is the text:
```
😃1️⃣😣🙄😊🤗😑👨‍🦰👨‍🦰👩‍🦰👱‍♂️ some
text 😎😎😍
```

**Comment by rebornix** [comment]
@Wouterr0 when you say "Wrong amount of characters is being displayed", do you mean the status bar item "9 selected" or something else ?

**Comment by Wouterr0** [comment]
Yes, sorry for the duplicate.
