### ISSUE TITLE
Terminal just says starting

### ISSUE THREAD

**Issue by mycroft16** [microsoft/vscode#76810]
Issue Type: <b>Bug</b>

Upon opening the terminal tab, the dropdown to select type just asy "starting..." This never goes away. Closing and re-opening VSCode does not help.

VS Code version: Code - Insiders 1.37.0-insider (7e03eb1a1fce3beb6ccea5f3b8f828e01940be61, 2019-07-05T18:31:56.611Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.96GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/d/Projects/Code/Angular/one-equality-project --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2301)|
|Memory (System)|7.87GB (2.96GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
gitkraken-glo|axo|1.1.0
vscode-typescript-tslint-plugin|ms-|1.2.1
ftp-kr|rua|1.3.16
code-spell-checker|str|1.7.17

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
