### ISSUE TITLE
Organic search

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#76816]
### Motivation
Let's say I want to find a snippet of code in my workspace. I don't know what exact search will take me to the right file and snippet (i.e. this may involve an iterative process of doing multiple searches, previewing files, updating the search text and so on). This happens often enough that I'd like to easily switch between the text field and file preview until I get to the right file and snippet. 

### Navigation and preview from within the search text field
Ideally I could just type e.g. `Ctrl+P` / `Ctrl+N` to go up and down directly from the search results, as [we do already](https://github.com/Microsoft/vscode/issues/7876) for the Command Palette, without losing the cursor focus on the text field so that I can refine my search as needed.

### Automatic updates
Ideally I would also be able to optionally enable the **automatic** updating of results as I continue to type or edit my text. 

Is any of this supported (perhaps through extensions?). If not, do we have any of these features in the roadmap? If not, why? 

### Related issues
* [Show quick open results as preview while navigating through them ](https://github.com/microsoft/vscode/issues/8939)

### How Emacs Helm does this
In case it's useful or informative, here's this same feature in Emacs Helm (for everything actually, i.e. commands, files, buffers, etc).

![helm-projectile-find-files-1](https://user-images.githubusercontent.com/1993919/60773642-6a659b00-a0d6-11e9-8251-9e73f59fd56a.gif)

## Further context and background
The screenshot below illustrates graphically what I am looking for.

<img width="332" alt="Screen Shot 2019-07-07 at 4 29 03 PM" src="https://user-images.githubusercontent.com/1993919/60773532-dd6e1200-a0d4-11e9-8da8-d284733244b3.png">

**Comment by roblourens** [comment]
You can use cmd/ctrl+down to move focus from the search box to the result list. It sounds like you want to change the selected item in the list keeping selection in the search box, right? It's an interesting idea. Would take a PR for that.

Auto-search - would not do this, search is expensive and I don't want to spawn a potentially expensive search process on each keystroke.

**Comment by amelio-vazquez-reina** [comment]
Thanks! I can close this issue then and create one dedicated to what you said. Separately, do you know what cmd/ctr+down are tied to in terms of actual Palette commands?

**Comment by roblourens** [comment]
They are not registered for the command palette, but their command IDs are `search.focus.nextInputBox` and `search.focus.previousInputBox` if you want to customize the keyboard shortcuts.

**Comment by roblourens** [comment]
It seems like this is served by just using cmd/ctrl+down to move focus from the search box to the result list, and cmd/ctrl+shift+f to move focus back to the search box when you need to refine your query. I don't really see a huge amount of value in what I said in https://github.com/microsoft/vscode/issues/76816#issuecomment-510137134.
