### ISSUE TITLE
Adding a root level item experience

### ISSUE THREAD

**Issue by vcsjones** [Microsoft/vscode#7681]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11

Steps to Reproduce:

1. Open a Folder in VS Code that has no root files, only Folders
2. Try to create an item at the root and not inside any of the folders.

If a folder is selected, items are created as a child of it. If a file is selected, new items are created along side that file. This makes adding "root" items a bit tricky, and if your project has no files in the root, only folders, seemingly impossible.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1043
