### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by michaaa123** [microsoft/vscode#76811]
Issue Type: <b>Bug</b>

Hi I was recently working on python project where I had to use UTF-8 charapters (georgian) and when I compiled the program I saw that one letter was into another It happens everytime when I'm trying to compile program please fix it it's very annoying!

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
fontsize-shortcuts|fos|1.5.0
python|ms-|2019.6.22090
vscode-icons|vsc|8.8.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
Can you please provide a screenshot showing what you are seeing. Where do you see these mixed characters?

**Comment by michaaa123** [comment]
> Can you please provide a screenshot showing what you are seeing. Where do you see these mixed characters?
Sure so first image is from vs code and second image is from atom to see how it should be
First: ![1](https://user-images.githubusercontent.com/27835393/61225311-5d2d5980-a731-11e9-955a-3e76e2ea4b91.png)
Second: ![2](https://user-images.githubusercontent.com/27835393/61225377-7afabe80-a731-11e9-87ef-1b91b6a85d1d.png)

**Comment by dbaeumer** [comment]
@michaaa123 you see that in the editor pane. Right?

**Comment by alexandrudima** [comment]
@michaaa123 Can you please provide that text in a copy-paste friendly format?

**Comment by michaaa123** [comment]
> @michaaa123 you see that in the editor pane. Right?

No the issue is presented in the terminal after when I try to get some text on the screen for instance  in the above picture I was asking to user for input some information and when the text was presented words were mixed

**Comment by michaaa123** [comment]
> @michaaa123 Can you please provide that text in a copy-paste friendly format?

sure: ჩაწერეთ პინ კოდი რათა შეხვიდეთ:

**Comment by alexandrudima** [comment]
I could not reproduce it on macOS, it might be a Windows specific issue in the terminal:

![image](https://user-images.githubusercontent.com/5047891/62788374-07956400-bac7-11e9-8be1-e38dcd7d2dec.png)

**Comment by Tyriar** [comment]
Adding this setting might help:

```
"terminal.integrated.rendererType": "dom"
```

But I think this is mainly that the terminal doesn't support RTL languages https://github.com/xtermjs/xterm.js/issues/701
