### ISSUE TITLE
Set Language-Specific Default Template for New Files

### ISSUE THREAD

**Issue by alivefromupstairs** [microsoft/vscode#76819]
The ability to set a template/scaffold when creating new files. For example creating a New_File.html in explorer that would already have something like:
```html
<!DOCTYPE html>
<html lang="en">
<head>
   <title>${file's actual name}</title>
</head>
<body>
  
</body>
</html>
```
Much like triggering a snippet on file creation that is not bloating suggestions.

**Comment by ShadowFoxNixill** [comment]
For Java it could be something like this
```java
package $path_with_dots_instead_of_slashes

public class $filename_without_extension {
}
```
