### ISSUE TITLE
savable and remainable variable for scripting languages such as python and javascript and so on

### ISSUE THREAD

**Issue by aminabvaal** [microsoft/vscode#76814]
this is important for everyone to able to view and work with variables that are in program code after running......
most for scientific works ....
just like Matlab savable, view-able, workable and modifiable and loadable variables

**Comment by aminabvaal** [comment]
hi @weinand ...this feature is very great and very high commercial for attracting anyone to Vscode
i ask by very high attention to it and a lot regard to it.

**Comment by weinand** [comment]
Please explain the feature.

**Comment by aminabvaal** [comment]
this image must be output 

![image](https://user-images.githubusercontent.com/31241289/60774174-ad029400-a125-11e9-84b7-75943e0fd2ca.png)

**Comment by 1138-4EB** [comment]
@weinand, although it is very interesting, I think this might be out-of-scope of vscode's core, as the implementation needs to be specific to each language. From the image, I assume that @aminabvaal expects not only to save/load a set of variables, but also to have a 'real-time' view of the content. Such a feature is likely to fit as an Extension, one for each scripting language/framework.

Nonetheless, as suggested in https://www.quora.com/Is-there-a-way-to-save-the-workspace-in-python-like-one-does-in-Matlab, the best approach for Python is probably to use Jupyter. Fortunately, that's already supported: https://code.visualstudio.com/docs/python/jupyter-support

**Comment by weinand** [comment]
yes, this feature is out-of-scope for VS Code, and belongs to the individual language/debugger extensions. And yes: there is already Jupyter support.
