### ISSUE TITLE
Tabbing with highlighted code ignores tab preference

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/vscode#7682]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

![vscode-tab-repro](https://cloud.githubusercontent.com/assets/1088987/16064204/dcb1ff7c-3253-11e6-9115-e9732bd4ea5f.gif)

Settings:

```json
{
  "editor.tabSize": 2,
  "editor.wrappingColumn": 0,
  "editor.renderWhitespace": true,
  "files.trimTrailingWhitespace": true
}
```

**Comment by alexandrudima** [comment]
@blakeembrey When the selection is a single line selection the text will be replaced with a `\t`. Otherwise there would be absolutely no way to insert a Tab character anymore.

Related #8840 #4312 -- the latter one has the exact opposed view as #8840 and this issue

**Comment by blakeembrey** [comment]
@alexandrudima Understood. However, I still disagree. I don't care to insert tabs, that's why I set my preferences as spaces. Having a surprising and hacky way just to insert a tab doesn't make a lot of sense to me. I can't recall any other editor that does this.

The exact behaviour I run into this was actually trying to fix my indentation. Say you have copied something and the indent is one space off. I'd go back and highlight the space and hit tab. Great, now I have a tab character instead of the two spaces I asked for.

**Comment by blakeembrey** [comment]
@alexandrudima Actually https://github.com/Microsoft/vscode/issues/8840 is a duplicate of this issue. It says the expected behaviour is to insert spaces (not the opposite).

**Comment by HubertJFarnsworth** [comment]
@blakeembrey -- I completely agree.  I opened #8840 not knowing this one already existed.  The current behavior seems clunky and non-intuitive and allows \t characters to be inserted into a file unintentionally.  Visual Studio and Notepad++ also both seem to function as I would expect.  VSCode's behavior seems like the outlier, and IMHO incorrect.

**Comment by alexandrudima** [comment]
@blakeembrey I agree, hitting tab + indentation with spaces should not insert the tab character.
