### ISSUE TITLE
Drag the extension to split and the editor windows is black

### ISSUE THREAD

**Issue by SCUTJcfeng** [microsoft/vscode#76822]
- VSCode Version: 1.36.0
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Open a project and open a file in the project
2. Open a extension page and drag the page to the right to split into 2 window
3. Editor window go black, click theextension page on the left and the error msg shows down right, but all the other functions still work well
4. close vs code and restart, the same bug happens again

Does this issue occur when all extensions are disabled?: No(This is a extension related bug)

![微信图片_20190708095650](https://user-images.githubusercontent.com/14869384/60778479-b0b80a00-a169-11e9-8380-d0133276469d.png)

**Comment by mjbvz** [comment]
Are you still seeing this issue in the latest VS Code build? I have not been able to reproduce the problem

If you do still see the problem, can you also please test this using our electron 6 exploration builds: https://github.com/microsoft/vscode/pull/75802#issue-289924821
