### ISSUE TITLE
I can't created sfdx project

### ISSUE THREAD

**Issue by hasectic** [microsoft/vscode#76829]
Issue Type: <b>Bug</b>

command 'sfdx.force.project.create' not found

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
salesforcedx-vscode|sal|46.4.0
salesforcedx-vscode-apex|sal|46.4.0
salesforcedx-vscode-apex-debugger|sal|46.4.0
salesforcedx-vscode-apex-replay-debugger|sal|46.4.0
salesforcedx-vscode-core|sal|46.4.0
salesforcedx-vscode-lightning|sal|46.4.0
salesforcedx-vscode-lwc|sal|46.4.0
salesforcedx-vscode-visualforce|sal|46.4.0

</details>

**Comment by dbaeumer** [comment]
Please report the problem against the extension that contributes that command. Very likely one of the saleforce extensions.
