### ISSUE TITLE
Open Recent workspace opens new window

### ISSUE THREAD

**Issue by restjohn** [microsoft/vscode#76823]
Issue Type: <b>Feature Request</b>

I always expected, and I would prefer, that _File_ > _Open Recent_ > _<workspace_item>_ opens a workspace in a new window instead of replacing the current window.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by gjsjohnmurray** [comment]
Hold the Shift key down when you click on the recent workspace item.

**Comment by dbaeumer** [comment]
@gjsjohnmurray is correct. Closing
