### ISSUE TITLE
Add a contextmenu item to support copy filename to clipboard 

### ISSUE THREAD

**Issue by nodew** [microsoft/vscode#76826]
Indeed, there is an extension implements what I want, https://github.com/Jack89ita/vscode-copy-filename, but I think it's should be a default support in vscode, since we already have copying absolute path and copying relative path. If ok, I'll help with the PR.

**Comment by dbaeumer** [comment]
`Copy Path` and `Copy Relativ Path` are already in the context menu. Are they not suifficient?

**Comment by dbaeumer** [comment]
Please ping if you think more needs to be done here.

**Comment by nodew** [comment]
@dbaeumer Hmm, I write fsharp and csharp daily, in my situation, file path is not so important, because of namespace. And the filename is usually the name of my class or module name. Without the copy filename option, my workflow is `right-click -> rename -> copy -> paste`, if use `copy path` or `copy relative path`, I have to drop more useless code after paste.

Another situation is that sometimes I will use vscode and visualstudio at the same time and I usually copy the filename from vscode and search to open it in visualstudio.
