### ISSUE TITLE
Stuck in executing task building cpp with WSL

### ISSUE THREAD

**Issue by Iamnvincible** [microsoft/vscode#76820]
![Snipaste_2019-07-08_09-54-22](https://user-images.githubusercontent.com/5810474/60777720-7e58dd80-a166-11e9-97fa-cba0dd317768.png)

- Version: 1.36.0 (user setup)
- Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
- Date: 2019-07-03T13:25:46.372Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Follow the steps on the vs code doc [Using C++ and WSL in VS Code](https://code.visualstudio.com/docs/cpp/config-wsl)
2. When I finish all the instructions , I press `ctrl+shift+B` to build my cpp file
3. I can see the terminal outputs `>Executing task: g++ ...` command, and it just stuck in that line even I wait for more time.

I remember I can launch the same task in previous version of VS Code and I do not change any configuration on my computer.

Does this issue occur when all extensions are disabled?: No

**Comment by Iamnvincible** [comment]
I figure out the problem, in the `tasks.json` file
```
    "windows": {
        "options": {
            "shell": {
                "executable": "bash.exe",
                "args": [
                    "-c"
                ]
            }
        }
    }
```
The `executable` parameter should be set to `bash.exe`, while in the doc that is `c:\\windows\\sysnative\\bash.exe`.

I tried the longer `executable` path in VS Code Insider, it outputs
`The terminal shell path "c:\windows\sysnative\bash.exe" does not exist`
so I change the value to `bash.exe`, it works!
It's time to update the doc

**Comment by alexr00** [comment]
Doc updated, thank you for reporting!
