### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by spriteetirps** [microsoft/vscode#76836]
- VSCode Version:  1.36.0
- OS Version:  linux 16.04

Steps to Reproduce:

1.When I open a CPP file, I always get stuck, but when I open other CPP files, this problem does not occur.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Can you provide an example C++ file that causes this?

**Comment by alexr00** [comment]
Sounds like it might be another instance of https://github.com/microsoft/vscode/issues/76774

**Comment by spriteetirps** [comment]
> 你能提供一个导致这种情况的示例C ++文件吗？

**Comment by spriteetirps** [comment]
> Sounds like it might be another instance of #76774

I saw this writing, but I don't think my problem is caused by code. I didn't use it to run my code.
