### ISSUE TITLE
输入时感觉卡顿

### ISSUE THREAD

**Issue by zjxcv7** [microsoft/vscode#76837]
Issue Type: <b>Performance Issue</b>

当启动angular程序实时编译后感觉会卡顿，之前版本没有这个问题。

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    74	 13283	code main
    0	    33	 13284	   gpu-process
    0	   328	 13286	   window (supplierclass.service.ts — csp)
    0	   131	 13326	     extensionHost
    6	   238	 13330	       electron_node tsserver.js 
    0	    16	 13347	         electron_node typingsInstaller.js typesMap.js 
    0	    41	 13333	       electron_node server.js 
    0	    16	 13373	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=13326
    0	    25	 13597	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=13326
    0	    25	 13327	     watcherService
    0	     0	 17032	     /bin/zsh -l
    0	    33	 17185	       node /usr/local/Cellar/yarn/1.16.0/libexec/bin/yarn.js start
    0	   614	 17186	         ng serve -o
    0	   295	 17193	           /usr/local/bin/node /Users/zhaojj/Project/csp/node_modules/@ngtools/webpack/src/type_checker_worker.js 9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
    1	    66	 13328	   shared-process
    0	     0	 17403	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    74	 17399	   window (问题报告程序)
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
ng-zorro-vscode|cip|8.0.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
code-runner|for|0.9.11
terminal|for|0.0.10
Angular2|joh|8.1.1
Angular-BeastCode|Mik|8.0.10
vscode-language-pack-zh-hans|MS-|1.36.2
cpptools|ms-|0.24.0
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@zjxcv7 can you please provide a description in English with steps on how to reproduce it. Does the problem occur when all extensions are disabled (e.g. start code with ` --disable-extensions`)
