### ISSUE TITLE
WSL $PATH changed by VSCODE automatically , Breaks Anaconda

### ISSUE THREAD

**Issue by apoorvagarwal41** [microsoft/vscode#76833]
Issue Type: <b>Bug</b>

When we open bash inside vscode WSL, the $PATH  variable is automatically appended by /usr/bin:/home/username/random_id/bin, which breaks python paths even though you activate your conda env manually

Result of : echo $PATH

`/usr/bin:/home/apoorv/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/bin:/usr/bin:/home/apoorv/anaconda3/bin:/home/apoorv/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/Oracle/Java/javapath_target_2272687:/mnt/c/Program Files (x86)/RSA SecurID Token Common:/mnt/c/Program Files/RSA SecurID Token Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/1E/NomadBranch:/mnt/c/Program Files/Dell/Dell Data Protection/Encryption:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/mnt/c/Program Files/Calibre2:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/mnt/c/Users/apoorv_agarwal/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/apoorv_agarwal/AppData/Roaming/npm:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/snap/bin:/home/apoorv/.dotnet/tools:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin`

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.88GB (3.91GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|15.88GB (3.91GB free)|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
project-manager|ale|10.5.2
vscode-color|ans|0.4.5
markdown-emoji|bie|0.0.9
turbo-console-log|Cha|1.2.26
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.2.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
code-runner|for|0.9.11
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.138
rest-client|hum|0.21.3
vscode-cdnjs|Jak|0.18.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.22090
azure-account|ms-|0.8.4
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.488
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
angular-console|nrw|8.0.6
indent-rainbow|ode|7.4.0
vscode-template-literal-editor|pli|0.9.0
quicktype|qui|12.0.46
vscode-yaml|red|0.4.1
datetime|rid|1.0.5
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-fileutils|sle|2.14.5
vscode-status-bar-format-toggle|tom|1.5.0
vscodeintellicode|Vis|1.1.7
markdown-all-in-one|yzh|2.4.0
html-snippets|abu|0.2.1
flutter-snippets|ale|2.0.0
emojisense|bie|0.5.1
bracket-pair-colorizer|Coe|1.0.61
flask-snippets|cst|0.1.1
javascript-ejs-support|Dig|0.5.0
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.3.0
vsc-material-theme|Equ|29.2.0
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.11
Angular2|joh|8.1.1
vscode-peacock|joh|2.4.0
theme-karyfoundation-themes|kar|18.2.1
Angular-BeastCode|Mik|8.0.10
dotenv|mik|1.0.1
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.7
vscode-remote-extensionpack|ms-|0.15.0
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
jinjahtml|sam|0.10.5
code-settings-sync|Sha|3.3.1
vscode-nginx|sha|0.6.0
vscode-icons|vsc|8.8.0
vuetify-vscode|vue|0.2.0
JavaScriptSnippets|xab|1.7.2

(5 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
We only add `/home/apoorv/.vscode-server/bin/$commitId/bin`.
You likely have a line in a shell startup script (e.g. `.bash_profile`) that adds  `/usr/bin`.

Can you explain how this breaks your python paths?

**Comment by apoorvagarwal41** [comment]
> We only add `/home/apoorv/.vscode-server/bin/$commitId/bin`.
> You likely have a line in a shell startup script (e.g. `.bash_profile`) that adds `/usr/bin`.
> 
> Can you explain how this breaks your python paths?

as /usr/bin is added to $PATH automatically , even when my anaconda environment is activated it uses the wrong python executable to run the program , thus resulting in import errors.
Also, I check by normally launching the bash from the start menu the $PATH variable is set in the corrent manner.
`/home/apoorv/anaconda3/bin:/home/apoorv/anaconda3/condabin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/Oracle/Java/javapath_target_2272687:/mnt/c/Program Files (x86)/RSA SecurID Token Common:/mnt/c/Program Files/RSA SecurID Token Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/1E/NomadBranch:/mnt/c/Program Files/Dell/Dell Data Protection/Encryption:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/mnt/c/Program Files/Calibre2:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/mnt/c/Users/apoorv_agarwal/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/apoorv_agarwal/AppData/Roaming/npm:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/snap/bin:/home/apoorv/.dotnet/tools:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin`

The above is the result from `echo $PATH` from normal bash.

And this is the result when I echo $PATH inside vscode integrated bash shell, when opening through remote WSL

`/usr/bin:/home/apoorv/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/bin:/usr/bin:/home/apoorv/anaconda3/bin:/home/apoorv/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/Oracle/Java/javapath_target_2272687:/mnt/c/Program Files (x86)/RSA SecurID Token Common:/mnt/c/Program Files/RSA SecurID Token Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/1E/NomadBranch:/mnt/c/Program Files/Dell/Dell Data Protection/Encryption:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/mnt/c/Program Files/Calibre2:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/mnt/c/Users/apoorv_agarwal/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/apoorv_agarwal/AppData/Roaming/npm:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32:/mnt/c/Users/apoorv_agarwal/AppData/Local/Programs/Python/Python37-32/Scripts:/mnt/c/Program Files/MongoDB/Server/4.0/bin:/mnt/c/MinGW/bin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/condabin:/mnt/c/Users/apoorv_agarwal/AppData/Local/Continuum/anaconda3/Scripts:/snap/bin:/home/apoorv/.dotnet/tools:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin:/opt/mssql-tools/bin`

**Comment by aeschli** [comment]
@Tyriar Do you have an idea how the `/usr/bin` gets to the front of the PATH?
When we launch the remoteExtHost, `/home/apoorv/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/bin` is the first entry

**Comment by apoorvagarwal41** [comment]
> @Tyriar Do you have an idea how the `/usr/bin` gets to the front of the PATH?
> When we launch the remoteExtHost, `/home/apoorv/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/bin` is the first entry

Really sorry, I didn't check my ~/.bash_profile file , I was only rechecking my .bashrc again and again , somehow there was a entry there adding /usr/bin in front of the path, fixed that now everything is working well.
