### ISSUE TITLE
Clicking into editor does not properly take focus from Terminal view

### ISSUE THREAD

**Issue by neandrake** [Microsoft/vscode#7684]
- VSCode Version: 1.2.1 (fe7f407b95b7f78405846188259504b34ef72761) (note this happened on previous version as well, 1.2.0)
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. With Terminal view open, click into terminal and type some keys, verify terminal is receiving keyboard input
2. Using mouse, click into text editor
3. Type keys and see that the first keyboard input goes to terminal and the rest are lost
4. Clicking again in text editor will bring proper focus so keyboard input is directed to editor

Note: I am using the fish shell and have not tried these same steps with bash. http://fishshell.com/

Attached is a GIF where I am doing these steps. You won't be able to see that I'm typing keys after clicking to focus into editor but I am (the terminal loses its block cursor). I click twice and focus goes into editor and my typing appears.

![focus](https://cloud.githubusercontent.com/assets/1531355/16065025/9758c750-3274-11e6-9c8e-87313960a343.gif)

**Comment by Tyriar** [comment]
Fixed in master already, coming in v1.3.0.

**Comment by neandrake** [comment]
Thanks - sorry Github default Issue search is for open status only

**Comment by Tyriar** [comment]
@neandrake I'm making this the "official" issue for this bug as it was fixed before reported :stuck_out_tongue:
