### ISSUE TITLE
Can't disable auto-indent

### ISSUE THREAD

**Issue by JacobParis** [microsoft/vscode#76846]
Issue Type: <b>Bug</b>

Every time I commit a file, VS Code changes the indent before committing. 

The setting in the bottom right is `Spaces: 4` and after committing, my four space indents are all replaced with two space indents, and it still says `Spaces: 4` after the change

 I've disabled all extensions and every indent or format related setting I could find. I've deleted the project and workspace settings files in case those were overriding anything.

`settings.json`
```json
{
    "atomKeymap.promptV3Features": true,
    "editor.formatOnPaste": false,
    "files.autoSave": "onFocusChange",
    "editor.renderWhitespace": "all",
    "javascript.updateImportsOnFileMove.enabled": "never",
    "javascript.suggest.autoImports": false,
    "typescript.suggest.autoImports": false,
    "vetur.completion.autoImport": false,
    "flow.enabled": false,
    "eslint.enable": false,
    "editor.detectIndentation": false,
    "vetur.format.options.tabSize": 4,
    "editor.autoIndent": false,
    "html.format.enable": false,
    "json.format.enable": false,
    "javascript.format.enable": false,
    "javascript.format.insertSpaceAfterCommaDelimiter": false,
    "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "javascript.format.insertSpaceAfterKeywordsInControlFlowStatements": false,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false,
    "javascript.format.insertSpaceAfterSemicolonInForStatements": false,
    "javascript.format.insertSpaceBeforeAndAfterBinaryOperators": false,
    "typescript.format.enable": false,
}
```

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: disabled_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.35GB free)|
|Process Argv|-psn_0_6415902|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rebornix** [comment]
> Every time I commit a file

May I know if you are referring `commit` to `git commit`? Do you see this issue with all languages?
