### ISSUE TITLE
Mouse shortcut do not work anymore

### ISSUE THREAD

**Issue by pmattei** [microsoft/vscode#76841]
Issue Type: <b>Bug</b>

Hello

Since my Visual code updated to 1.36.0, I lost my mouse shortcut.
I am using Visual code for some ocaml project. 
The "go to definition" works fine, for example if I do Ctrl + click I will have a new popup to naviguate to the definition. 
If I go, I can go backward with Alt + LeftArrow. 
I have two buttons on the left side of my mouse that normally allows me to navigate backward and forward. (They still working fine in Chrome for example). Since the new version I can no more go backward and forward with my mouse, it is really annoying.
I did not fine any help on internet about mouse shorcut in Visual Code.
The preference Keyboard Shorcuts did not allow me to add mouse shorcut, how can I fix that?

Regards
 

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.8.2
reasonml|fre|1.0.38
latex-workshop|Jam|7.1.0
cpptools|ms-|0.24.0
helloworld-minimal-sample|vsc|0.0.1
vscode-mlfi|Nev|0.0.1

</details>

**Comment by dbaeumer** [comment]
Yes, dups #71318

**Comment by pmattei** [comment]
You are right, I did not fine this issue
I close and wait the new release :)
