### ISSUE TITLE
Emojis don't work under ConPTY

### ISSUE THREAD

**Issue by MofX** [microsoft/vscode#76842]
I am giving rust and rocket a try. Rocket uses lots of unicode icons for it's output. With WinPTY all icons are replaced by placeholders, which is kind of fine. With ConPTY some are shown, and some aren't. But the really bad thing is, that some other characters get lost.

![image](https://user-images.githubusercontent.com/1215681/60793424-fe337780-a167-11e9-93bf-9d7172237aa3.png)

The image shows two starts of the same program, to demonstrate the major problem.
In the first output the url ("http://localhost:8000") is completely printed. In the second output the last to numbers of the port are missing and also the last two letters of the word "development".

After stopping the program AND hitting enter one more time, the output of the second run is the same as the first run -> The missing characters are added in default color and boldness.

**Comment by Tyriar** [comment]
Tracking width-related issues in https://github.com/xtermjs/xterm.js/issues/1709

Conpty seems to be handling these characters differently to Linux and macOS, that still needs to be looked into to figure out the discrepancy.

**Comment by MofX** [comment]
I just want to mention, that the new windows terminal (https://github.com/Microsoft/Terminal) correctly displays the output from rocket.

**Comment by Tyriar** [comment]
Yep, that's because they only need to use conpty, whereas we use regular pty (mac/linux, where it works), conpty and winpty.

**Comment by mikegwhit** [comment]
This is my current frustration.  I don't have data to add, except that I am trying to support a library that beautifies console output for NPM packages and part of this includes dropping in a nice emoji character with the package.  This ends up breaking that effort.  How can I help?  What threads can I pull in?

![image](https://user-images.githubusercontent.com/2973130/66016166-c439ef00-e492-11e9-8e8a-b352055b3781.png)

**Comment by mikegwhit** [comment]
Bump

**Comment by rmcenlly** [comment]
In addition to the terminal behavior described in this issue, we have seen missing, flashing text content in the editor when `ThemableDecorationAttachmentRenderOptions` `contentText` is set to the same characters that don't display properly in the terminal.

Example:

```javascript
String.fromCodePoint(9731, 9733, 9842, 0x2F804)
```

**Comment by mikegwhit** [comment]
Bump

**Comment by mikegwhit** [comment]
Bump

**Comment by nijikokun** [comment]
This happens with all integrated terminals sadly. Tried Powershell, Git Bash, WSL.
