### ISSUE TITLE
${env:PATH} etc does remove last bracket

### ISSUE THREAD

**Issue by Tatsujinichi** [microsoft/vscode#76849]
- VSCode Version:
1.35.1
- OS Version:
Ubuntu 18.04
Steps to Reproduce:

1.
Open settings.json and add
```
"terminal.integrated.env.linux": {
		"PATH": "/usr/local/cuda/bin:${env:PATH:+:${env:PATH}}",
		"LD_LIBRARY_PATH": "/usr/local/cuda/lib64:${env:LD_LIBRARY_PATH:+:${env:LD_LIBRARY_PATH}}"
	},
```
2.
Open Terminal and echo either, notice there is an extra '}' left over at the end.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I don't think you're meant to nest them?

**Comment by Tatsujinichi** [comment]
If I leave off the last bracket it evaluates as you would expect when nested.  Nesting is not disallowed.
This is fine in bash.

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/77289 to disallow it
