### ISSUE TITLE
References viewlet icon is too small

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#76845]
<img width="595" alt="Screenshot 2019-07-08 at 10 25 51" src="https://user-images.githubusercontent.com/1794099/60794813-d09bfd80-a16a-11e9-8d38-45960c2a8770.png">

**Comment by johnletey** [comment]
Sorry, I have to ask @jrieken ... what theme is that?

**Comment by misolori** [comment]
@johnletey that's [GitHub Sharp Theme](https://marketplace.visualstudio.com/items?itemName=joaomoreno.github-sharp-theme) by @joaomoreno

**Comment by johnletey** [comment]
Thanks @misolori!
