### ISSUE TITLE
Quick Fix hover not working

### ISSUE THREAD

**Issue by archer3cl** [microsoft/vscode#76851]
After updating to VS Code 1.36.0 the option for quick fix when hovering does not apply the related action.
![NOACTION](https://user-images.githubusercontent.com/4583932/60730600-270b0100-9f0b-11e9-84ef-5a3a05379c42.gif)

Using the quick fix on the bulb action does.
![ACTION](https://user-images.githubusercontent.com/4583932/60730671-4a35b080-9f0b-11e9-8fe9-2b6b7b6f3700.gif)

VS Code Info
Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
Doesn't happen for JS/TS in my testing. Will try with eslint and java

**Comment by mjbvz** [comment]
Simple example for eslint. Only happens sometimes:

```js
// @ts-check
import * as React from 'react';

export default <div dangerouslySetInnerHTML={{ __html: '' }} />
```

**Comment by mjbvz** [comment]
**Repo**

1. Install eslint and create basic config file.
1. In a file:
```j
// @ts-check
import * as React from 'react';

export default <div dangerouslySetInnerHTML={{ __html: '' }} />
```
3. Wait for warning to show up on `dangerouslySetInnerHTML`.
4. Place cursor before `dangerouslySetInnerHTML` and quicky type `space`, `delete`, `ctrl+.` to trigger code actions 
5. Select one of the suppress fixes 

**Bug**
Code action not applied

**Comment by infinnie** [comment]
> I'm having the same problem after updating VSCode to 1.36. I'm going to use the bulb action meanwhile.

But it is hard for bulbs to pop up sometimes.

**Comment by Fernandomr88** [comment]
Still not working on DART/Flutter

**Comment by infinnie** [comment]
This doesn’t seem to have been fixed in the 1.36.1 update.

**Comment by Fernandomr88** [comment]
> Still not working on DART/Flutter

Already reported here https://github.com/microsoft/vscode/issues/77018

**Comment by babs232** [comment]
Below is what I am getting as error while using Quick Action:

[2019-07-11 10:38:38.078] [exthost] [warning] redhat.java - Code actions of kind 'quickfix 'requested but returned code action is of kind 'source.generate.delegateMethods'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
