### ISSUE TITLE
Tabs & makefiles

### ISSUE THREAD

**Issue by khenidak** [Microsoft/vscode#7685]
- VSCode Version:1.2.1 
- OS Version: MacOs ElCapitan

Steps to Reproduce:

1. create a makefile
2. edit the make file create a very basic build target as in
>> start file
CC=GCC
CFLAGS=-c -Wall

build:

	$(CC) $(CLFAGS) test1.c -o test
>> end file

3. running make build will fail with the infamous "missing separator" reason being VSCODE does do tab correctly. 
4. to fix: edit the file with vi or nano remove the old tabs (created by VSCode) add new ones using nano and run make again (works).

sorry didn't have file to look at char codes used by VS code.

**Comment by jhasse** [comment]
I don't think this is a bug. When you select "Indent Using Tabs" editing Makefiles works just fine.

vi and nano default to indention using tabs while VSCode uses 4 spaces by default.

**Comment by khenidak** [comment]
Thanks! - modified the settings file and all worked as expected. will close the issue.
