### ISSUE TITLE
Unusable pre-filed value after openning the Find panel

### ISSUE THREAD

**Issue by atiris** [microsoft/vscode#76857]
The pre-filled value after opening the Find panel is unusable in some cases.

- VSCode Version: 1.36.0
- Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
- Date: 2019-07-03T13:20:56.241Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Linux x64 5.1.16-200.fc29.x86_64

Does this issue occur when all extensions are disabled?: Yes

**Steps to Reproduce:**

1. Start VSCode without extensions `code --disable-extensions`, open new file and paste this code:

```text
aaa aaa aaa aaa
bbb aaa aaa bbb
aaa aaa ccc ddd
```

2. Select any `aaa` text.
3. Open Find panel `CTRL+F`.

**Bug:** The pre-filled value is `aaa` and "Find in selection" is enabled. Such a setting (to fill selected word when only this word is entire selection) makes no sense. If you mark a word, you are most likely to look for it outside the selection. Or you search for previous searched value in new selection. **Search entire selection inside entire selection makes no sense.**

_Note:_ In the case of multiline selection, the pre-fill is correct. The last search value is pre-filled, and the button "Find in selection" is marked on.

_The proposed behavior is described in https://github.com/microsoft/vscode/issues/76856 request._

**Comment by gregvanl** [comment]
Hi @atiris Does this issue still reproduce for you? I don't see "Find in selection" enabled automatically when I follow the repro steps.

**Comment by atiris** [comment]
After testing in this later version on Windows:

Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
_(I using Linux in work so I can tested now only on Windows)_

There is still a situations when Find panel after select one word is open with "Find in selection enabled".

Repro steps are identical:

- start vscode: `code --disable-extensions`
- paste text:

```txt
aaa aaa aaa aaa
bbb aaa aaa bbb
aaa aaa ccc ddd
```

- doubleclick on `ccc`
- press `CTRL+F`

Find panel is in state that you want to find `ccc` in `ccc`. If you now type aaa, result is: `No Results`. But no one will ever want such functionality. If you select one word you almost always want to find this word in entire document.

After that I turn off the "Find in selection", close Find panel, double click on `bbb`, press `CTRL+F` and Find panel is again in "Find in selection" enabled and result is "1 of 1". But to understand me, if you select something and the Find panel in your favorite editor tells you that **the marked part is in the marked part just once** 😂 - it has no informative value for me 😎

**Comment by gregvanl** [comment]
I see you have `editor.find.autoFindInSelection` set to true in your user settings so it is set when you reopen the editor Find control. Do you feel that the Find control is a too strict in following your preference?

**Comment by atiris** [comment]
Yes. ... But I had no idea that this behavior was configurable. 🙄

Nevertheless, it does not make sense to enable "Find in selection" if the selection does not contain more than one row.  
Nor does it make sense to turn off searches in a selection if multiple-line text is selected.  
Now I don't know exactly how `editor.find.autoFindInSelection` works, but I'm afraid if I can get closer to this behavior with any configuration option (only true / false).

To make the find panel behavior logical, it is sufficient to observe the principles: if the marked part contains a end of line, the search in selection as enabled will be better choice for most developers, in all other cases it will be better to search throughout the whole document. Maybe `editor.find.autoFindInSelection` can be a select with options: "yes", "no", "automatic".

**Comment by rebornix** [comment]
> Nevertheless, it does not make sense to enable "Find in selection" if the selection does not contain more than one row.

Yup, we should optimize the `editor.find.autoFindInSelection` to be richer, especially considering that currently you can search multiple line in the find widget.
