### ISSUE TITLE
Selection is changed when using Find and Replace panel

### ISSUE THREAD

**Issue by atiris** [microsoft/vscode#76859]
When using the Find and Replace panel, the Selection is changed without user intervention.

This is a bug of **high importance** (for any editor) because **you cannot trust the result of the replacement**.

For example, if you have the "misake" text in the file several times and you are trying to fix it, you cannot trust the result after using Replace, that it actually replaced all the results you requested. Because there may be a situation where the selection that the user has made does not match the one used by the Find panel (after some operations, even though the selection has not changed by user).

- VSCode Version: 1.36.0
- Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
- Date: 2019-07-03T13:20:56.241Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Linux x64 5.1.16-200.fc29.x86_64

Does this issue occur when all extensions are disabled?: Yes

**Steps to Reproduce:**

1. Start VSCode without extensions `code --disable-extensions`, open new file and paste this code:

```text
aaa aaa aaa aaa
bbb aaa aaa bbb
aaa aaa ccc ddd
```

2. Select entire second line `bbb aaa aaa bbb` including line break (the cursor should be in front of the first character of the third line).
3. Open Find panel `CTRL+F`.
4. Type `aaa`
5. Turn off "Find in selection"
6. Turn on "Find in selection"

**Bug:** Selection for replacement was changed without user intervention.

**Any use of Find Panel should not change the original selection.** The standard expectation is that the Find panel finds two occurrences of the string "aaa" (in line 2) but the active selection has changed to the first text "aaa" on line #3 if you would now start the replacement, only first occurrence of "aaa" on last line would be replaced and not what you expect (that is, all occurrences in the last selection entered by user)

_The proposed behavior is described in https://github.com/microsoft/vscode/issues/76856 request._

**Comment by rebornix** [comment]
It's arguable whether the current behavior is as expected as in the steps, we intentionally turn on and off `Find in selection`. When `Find in selection` is turned off the first time, the cursor selection is updated based on the search result of find widget: it's changed to the first `aaa` of the second line.

However when turning off `editor.find.cursorMoveOnType`, the selection will not be updated when toggling `Find in selection`.
