### ISSUE TITLE
Flashing menus

### ISSUE THREAD

**Issue by martinschayna** [microsoft/vscode#76850]
- VSCode Version:
```
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic
```
- OS Version:
```
Ubuntu 18.04.2 LTS
```

Steps to Reproduce:
1. open any pulldown or context menu by any method (Alt+letter, mouse click or right click on an icon, etc.)
2. menu is shown with a light background without items for a fraction of second, then turn to dark color with items

It's reproducible at any time, it's here in actual Code Insiders too. 

It's **a glitch only**, everything works as usual.

Does this issue occur when all extensions are disabled?: Yes

**Comment by martinschayna** [comment]
It looks like that...
![ezgif com-gif-maker](https://user-images.githubusercontent.com/1617977/60798218-0217c780-a171-11e9-8083-20ebbfd60be1.gif)

**Comment by user414** [comment]
I can confirm I also have this issue on Ubuntu 18.04.2 LTS.

**Comment by haskjold** [comment]
I can also confirm this issue on Ubuntu 18.04.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by user414** [comment]
Just tested on Ubuntu 18.04 LTS and same as before.

**Comment by bpasero** [comment]
@user414 can you just download Electron from https://github.com/electron/electron/releases and see if the menu flashes too? If so, report an issue to them?

**Comment by user414** [comment]
Tested with the latest electron, same problem. Opened issue here https://github.com/electron/electron/issues/20520

**Comment by deepak1556** [comment]
Can you check if this is still an issue with latest stable `1.50`, thanks!

**Comment by MrHaroldA** [comment]
The flashing is gone on the insiders version (1.51) on Ubuntu 20.10 beta!

**Comment by user414** [comment]
@deepak1556 Just tested the 1.51 insider version and it is not gone for me on Ubuntu 18.04.5 LTS

**Comment by madasebrof** [comment]
Not sure why this was closed, it's still an issue even with the latest releases as of November 2020!

Menus still flash on Ubuntu 20.04. Maddening!
