### ISSUE TITLE
The color of current line compared with git is not obvious

### ISSUE THREAD

**Issue by moroal** [Microsoft/vscode#7686]
- VSCode Version:1.2.1
- OS Version:windows 7

Steps to Reproduce:
1. Click git
2. View a file has been changed
3. Click next modification at up-right corner , the current line viewed is not marked with special color

**Comment by alexandrudima** [comment]
We are now rendering a plus or minus next to added or removed lines to make things clear.

**Comment by moroal** [comment]
ok , thank you!
