### ISSUE TITLE
Html syntax highlighting breaks in razor files

### ISSUE THREAD

**Issue by cduivis** [microsoft/vscode#76870]
Html syntax break inside razor (`.chtml`) files, whenever you use a `?` inside the html element, while that Html element is nested within a code context.

- VSCode Version: 1.36.0
- OS Version: Windows 10 Pro (Windows_NT x64 10.0.17134)

Steps to Reproduce:

1. Open Visual Studio
2. Open / Create `.cshtml` file
3. Place a code context block e.g. an if statement.
4. Place a question mark in an html element. e.g.:
```html
@if( true )
{
	<div>
		<a asp-action="Index" asp-controller="Register">Create new account</a> | 
		<a asp-action="Index" asp-controller="PasswordRecovery">Forgot password?</a>
	</div>
}
```
5. All syntax highlighting is broken after the `?`.

Does this issue occur when all extensions are disabled?: Yes

Extra data:
- Nesting depth does not matter
  - Probably the highlighter assumes it's the start of a short if statement

**Comment by atiris** [comment]
The error does not affect linux version 1.36.0.

After open new html file and paste this text in VSCode (started without extensions) there is nothing wrong with question mark.

![Screenshot from 2019-07-08 14-37-26](https://user-images.githubusercontent.com/10474618/60810767-1e762d00-a18e-11e9-970e-aaa85776a5d8.png)

@cduivis can you attach a screenshot?

**Comment by alexr00** [comment]
I also can't reproduce this on Windows. @cduivis, in the bottom right corner what Language Mode is set?

**Comment by cduivis** [comment]
Sorry somehow it seems that GitHub has taken an really early writing of this bug.
Neither the title nor the it's body is how I posted it, I will amend these now.

**Comment by alexr00** [comment]
Sounds like this one is not needed then.
