### ISSUE TITLE
Do not update disabled extensions

### ISSUE THREAD

**Issue by supernes** [microsoft/vscode#76879]
Today I noticed that VSCode updates and installs extensions even if they are disabled. In fact, I was reminded of a couple of extensions I no longer use by the hundreds of megabytes downloaded in the background.

Could you consider adding this as a toggle in settings or disabling this behavior altogether?

**Comment by sandy081** [comment]
I see your point. But what is the reason behind having such extension installed and disabled, instead of uninstalling it?

**Comment by supernes** [comment]
So that they don't update in the background and waste traffic on my metered connection ;)

I switch between a lot of languages and runtimes regularly. I use VSCode for C++, C#, F#, PHP, Python, JS/Flow, Processing, GLSL/HLSL, Arduino and others, but I like to keep a "working set" of supporting extensions, depending on the project I'm working on.

This comes down to the question "what does disabling extensions actually do", besides declutter the list? Initially I thought this would help with memory usage and startup time, but I don't believe that's really the case.

If there's no practical use for disabling, maybe that option should be deprecated in favor of just uninstalling them.

**Comment by sandy081** [comment]
Yes, Disabling helps you in creating a working set. But I see your point and agreed that not auto updating a disabled extension makes sense.

**Comment by ffes** [comment]
> This comes down to the question "what does disabling extensions actually do", besides declutter the list?

Know that disabled extension can also still popup a notification as well.

I'm sure the C++ extension (ms-vscode.cpptools) occasionally (not sure when exactly) asks you to enter a survey even when the extension is disabled.

**Comment by sandy081** [comment]
@ffes This should not happen. Please file a separate issue with steps to repro.

**Comment by lszomoru** [comment]
@sandy081, I will take a look at this one and follow up with a pull request.

**Comment by lszomoru** [comment]
I have not had the chance to look into this. @sandy081, is this something that we still want to pursue?

**Comment by plainerman** [comment]
@sandy081 It looks to me like you have already implemented the desired changes a few days ago?

https://github.com/microsoft/vscode/blob/5954c8366d9646958e40bb4e50357afe7f8c22d2/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L478

**Comment by sandy081** [comment]
This is not yet supported and contribution is very much appreciated. Code pointer: Auto update of extensions happen here

https://github.com/microsoft/vscode/blob/a416c1534bb9159c7ad9d88f19d70019ded16a6a/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L880-L880

**Comment by plainerman** [comment]
Thank you @sandy081. I will look into it.
I would say, we just `filter` out the disabled extensions and do not return them. Do you have something different / more elaborate in mind?

And do you happen to know an easy way to test this function (i.e. forcing an auto-update)?

**Comment by plainerman** [comment]
I was able to implement this feature and also added a configuration to let users decide on whether disabled extensions should be updated.
The PR can be found at #113155.
