### ISSUE TITLE
Razor `.cshtml` - html syntax highlighting breaks after a question mark `?` inside an html element within a code context

### ISSUE THREAD

**Issue by cduivis** [microsoft/vscode#76872]
- VSCode Version: 1.36.0
- OS Version: Windows 10 Pro (Windows_NT x64 10.0.17134)

Steps to Reproduce:

1. Open Visual Studio.
2. Open / Create an `.cshtml` file.
3. Create an code context with an e.g. an if statement.
4. Place an HTML element with a question mark in the code context e.g.:
```html
@if( true )
{
	<div>
		<a asp-action="Index" asp-controller="Register">Create new account</a> | 
		<a asp-action="Index" asp-controller="PasswordRecovery">Forgot password?</a>
	</div>
}
```
5. All code highlighting breaks after the question mark.

Does this issue occur when all extensions are disabled?: Yes

- Only breaks inside a code context (no matter of the nesting depth).
  - Probably the highlighter incorrectly assumes it's the start of a short if statement.

**Comment by alexr00** [comment]
Moved to owning repo.
