### ISSUE TITLE
Open window with same dimensions each time

### ISSUE THREAD

**Issue by SirCameron** [microsoft/vscode#76873]
Currently each time I open Code (insiders), the window opens with its own idea of size, even tho I set the size and then close the app.
It's horrible and one of the reasons I quit using Atom. 

Request:
remember the size I set and open next time with that same size.

**Comment by bpasero** [comment]
That should be how it works. Steps? Video?

**Comment by SirCameron** [comment]
I noticed the first time you open a project, it opens correctly... the second time it opens in the default size.
so if i open in terminal with:
```
code-insiders .
```
first time is correct.
And in another tab I do the same in another project, it opens incorrectly.
I don't understand why this is especially because normal VS Code (not insiders) opens correctly every time.

**Comment by bpasero** [comment]
@SirCameron we never persist window dimensions beyond the first one. Maybe you have configured `window.newWindowDimensions` in the one but not the other?

**Comment by SirCameron** [comment]
@bpasero I haven't configured ```window.newWindowDimensions``` at all. I was expecting the app to remember the last dimensions. 
I googled ```window.newWindowDimensions``` and found this issue ```https://github.com/Microsoft/vscode/issues/24227```
I set ```window.newWindowDimensions: "inherit"``` and we have life.
