### ISSUE TITLE
Can't delete files and folder using the delete key in Explorer treeview

### ISSUE THREAD

**Issue by charlesg99** [microsoft/vscode#76875]
VSCode 1.36
Tested on Ubuntu 18.04 and Arch Linux

The delete key stopped working correctly in the Explorer's treeview (since 1.36 I believe). Instead of prompting to move the file/folder to the trash, the "delete" filter appears:

![Peek 2019-07-08 09-01](https://user-images.githubusercontent.com/33044886/60812371-544fed00-a15f-11e9-87ae-68edbbc4a5ff.gif)

**Comment by isidorn** [comment]
Duplicate, fixed, will be shipped as part of the recovery release we are about to ship later this week.
