### ISSUE TITLE
"Go to File" / quick open is slow when entering the full relative path

### ISSUE THREAD

**Issue by Standard8** [microsoft/vscode#76871]
- VSCode Version: 1.36 and 1.37-insider
- OS Version: Mac 10.14.5

Steps to Reproduce:

1. Start VSCode, open a large workspace, e.g. a clone of [mozilla-central](https://hg.mozilla.org/mozilla-central/).
2. Press cmd-P, and enter a file name, let it finish (this is to allow VSCode to seed the cache).
3. Copy a filename from another app (e.g. terminal), then switch back to VSCode and press cmd-P, paste the file name using cmd-V.
  * At this stage, VSCode completes almost immediately.
4. Press enter to open it
5. Now copy a relative path from the other app, switch back, cmd-P and cmd-V.
  * Now wait about 5 - 10 (or more) seconds for the completion to appear.

Given this is a relative path, it should be able to find it just as quickly as searching for the filename.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I think I can repro this, it's probably just that a longer filter is slower, but it shouldn't be that much slower.

**Comment by roblourens** [comment]
We avoid using a cache for search when the query has a slash and the cache's query doesn't. But that shouldn't apply when the cache query is empty and contains all results.

FYI @chrmarti I think this is ok, let me know if you see something wrong.

**Comment by chrmarti** [comment]
@roblourens LGTM.
