### ISSUE TITLE
Query encoding issue in URI when using vscode.diff and custom content provider

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode#76888]
Issue Type: <b>Bug</b>

This code below is ok in a single test:
```ts
        const id = "id++hello";
        let uri = Uri.parse("customContent://path").with({
            query: querystring.stringify({id})
        });
        
        console.log(uri.toString());
        console.log(uri.query);

        const query = querystring.parse(uri.query);
        assert.equal(id, query.id);
```

```
customContent://path?id%3Did%2B%2Bhello
id=id%2B%2Bhello
    √ encodeDecoreQuery
```

But when using vscode.diff and a custom content provider (TextDocumentContentProvider), the uri in provideTextDocumentContent method is not the same, the query part has been decoded, so the value in the query are decoded twice. In my example the id that was "id++hello" has now the value "id  hello".

Something goes wrong between executeCommand("vscode.diff", leftUri, rightUri)  and TextDocumentContentProvider.provideTextDocumentContent(uri: Uri).

This is a regression it was working well before the last update.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.15063

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/76506
