### ISSUE TITLE
SCM exploration icon is bold

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#76884]
From #8017 Issue Type: <b>Bug</b>

1. Install and activate icons [Material](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)
1. `"breadcrumbs.enabled": false,`
1. Reload Window
1. Open any editor and create Error/Warning in code
1. SCM icon becomes bold

VS Code version: Code - Insiders 1.37.0-insider (d50852db1af10ec100a71ad57cc3a04c8aead117, 2019-07-08T05:37:36.104Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
Not reproducible with new version. Commit: 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904

Did you change something? I'm curious what that bug was...

**Comment by misolori** [comment]
I did update the Git icon via https://github.com/microsoft/vscode/commit/58e2a079a521b2a8743fb83bf2a5d69489c6f2d4. What was happening was the circles were not on the pixel grid so we re-drew them and placed them on-grid to avoid pixelation that would add to the weight. 

Not sure how this would've solved this issue though, if it's not reproducible then feel free to close the issue.
