### ISSUE TITLE
Key-bindings restricted to focus on custom views

### ISSUE THREAD

**Issue by chakshugoyal97** [microsoft/vscode#76881]
While it is possible to let key bindings be active only when a view in the side bar/panel is in focus like explorer, scm etc., there does not seem to be a way to limit key bindings to only when a custom tree view is in focus. For instance, something like `"activeViewLet == 'myTreeView'"` in the when clause.

**Comment by sandy081** [comment]
@chakshugoyal97 What is the use case here?

**Comment by chakshugoyal97** [comment]
For instance, I'm making an extension with multiple tree views that represent different type of data. Each tree view has some similar buttons that perform operations for their respective views. Key bindings can be associated to shift focus to each tree using `myTreeView.focus` command. Now, I would want to perform operations to only the tree in focus preferably with the same keys for consistency and simplicity.

**Comment by sandy081** [comment]
Provided a new context key `focusedView` whose value is set to the current focused view.

`"when": "focusedView == nodeDependencies"`
