### ISSUE TITLE
Extension testing migration guide does not make clear where vscode/lib/testrunner is now

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#76897]
My `tests/index.ts` file currently imports a `testRunner` from `vscode`. I am trying to use this [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) to convert to the `vscode-test` library, but I don't know where to  import that test runner from anymore. How can I do this?

Here is my current file:
```typescript
import * as testRunner from 'vscode/lib/testrunner';

testRunner.configure({
    ui: 'bdd',
    reporter: 'list',
    useColors: true
});

module.exports = testRunner;
```

**Comment by octref** [comment]
The old `vscode` module bundles mocha 4. `vscode-test` does not export a default test runner to give your more flexibility. You can replace that script with https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-runner-script, and manually install `mocha` and `glob` as dev dependencies.
