### ISSUE TITLE
Support preview images inline

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7689]
Currently only in the browser to preview the images, which is uncomfortable.So that we can't focus on the code 😭 .

This is a feature request.
Details are as follows:
1. <kbd>Cmd/Ctrl</kbd> +  `Click` or hover preview images(The UI like Chrome DevTools).
   ![Chrome demo](https://img.alicdn.com/tps/TB1gEnVKpXXXXbDXpXXXXXXXXXX-401-170.png)
2. Right click to copy the image to the clipboard.
3. Click on the width and height text can be inserted width and height to HTML or CSS.
   after:
   
   ``` html
   <img src="https://code.visualstudio.com/home-screenshot-mac-lg.png" alt="Intellisense" class="screenshot">
       <style>
         background: url(https://code.visualstudio.com/home-screenshot-mac-lg.png);
       </style>
   ```
   
   before:
   
   ``` html
   <img src="https://code.visualstudio.com/home-screenshot-mac-lg.png" alt="Intellisense" class="screenshot" width="750" height="451">
       <style>
         background: url(https://code.visualstudio.com/home-screenshot-mac-lg.png);
         width: 750px;
         height: 451px;
       </style>
   ```

**Comment by sandy081** [comment]
@yisibl I am not sure I understood the reported problem correctly, can you please let me know
- what and where is the problem and
- how to reproduce it

If it is a feature request, please provide a detailed description of where and what the feature is about.

Thanks

**Comment by yisibl** [comment]
Sorry, this is a feature request.

I mean, add a preview of the picture feature. Like Chrome DevTools.
The details are as above.

**Comment by mjbvz** [comment]
Extension can provide this functionality. Check out this one for example: https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview

Closing as extension candidate
