### ISSUE TITLE
A visual bug

### ISSUE THREAD

**Issue by vporton** [microsoft/vscode#76899]
Issue Type: <b>Bug</b>

The terminal is damaged on Ubuntu 19.04:
![Screenshot from 2019-07-08 19-54-23](https://user-images.githubusercontent.com/2900574/60828219-8f333e80-a1ba-11e9-95dc-fccb9117d196.png)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.0.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.60GB (3.47GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ada|Ent|0.88.0
csharpextensions|jch|1.3.0
lean|jro|0.14.2
csharp|ms-|1.20.0
code-d|web|0.20.2

</details>

**Comment by lramos15** [comment]
Are you running in a VM? Virtual machines often have graphic driver issues that cause this type of behavior in your settings.json try adding this `"terminal.integrated.rendererType": "dom"` as a workaround.

**Comment by vporton** [comment]
No, I don't use a VM. Should I add `"terminal.integrated.rendererType": "dom"` even despite I don't use a VM?

**Comment by lramos15** [comment]
I would give it a try to see if it fixes your issue as it might be caused by a bad graphics driver on your machine.

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-my-terminal-showing-a-multicolored-triangle-or-a-completely-black-rectangle
