### ISSUE TITLE
Allow to get a handler for the default Explorer TreeView

### ISSUE THREAD

**Issue by 1138-4EB** [microsoft/vscode#76891]
I'm trying to get a handler for the default File Explorer TreeView. The use case is to reveal (and focus) a given item programmatically, after an action is triggered in a separate Custom TreeView contributed by my own extension.

I found #30288, about how to `reveal` an item in the Custom TreeView. However, I'd like to reveal an item in the default File Explorer instead. Hence, I tried [window.createTreeView](https://code.visualstudio.com/api/references/vscode-api#window.createTreeView):

`const myhandle = vscode.window.createTreeView(viewId: 'explorer');`

But it is invalid, because it requires TreeViewOptions, which I don't want to provide/override.

I'd expect the API to provide `window.getTreeView`, so it is possible to interact with the default File Explorer view. AFAIK, currently it is only possible to add features in the expected contribution points, e.g. the context menu.

**Comment by isidorn** [comment]
This is a fair feature request, however it is not currently on the plan, thus assigning to backlog.

**Comment by 1138-4EB** [comment]
@isidorn, is there any workaround/hack I can use meanwhile?

Since it might take long until this feature is included on some plan, an alternative I have considered is to use an additional 'subtree view', where the desired file explorer subtree is shown. However, I'm afraid that it is not possible to 'reuse' all the default and custom options that are configured/defined for the File Explorer viewId. I.e., to make a (custom) copy/instance of File Explorer with a limited scope. Hence, I would need to reimplement all the features in the custom view, which sounds as a no-go.

Another approach would be to filter the content of the default File Explorer, instead of trying to reveal some subdir. Is it possible to programmatically filter the content of the File Explorer?

**Comment by isidorn** [comment]
Unfortunetly there is no workaround.
We are not exposing the Explorer via the API.

And sorry it is not possible to programmaticly filter the content in the file explorer.
It is simply not exposed and this goes with our API rules. More about our approach can be found here 
https://code.visualstudio.com/api and in some corresponding docs
