### ISSUE TITLE
Confugure Build Task hangs forever / does not open editor

### ISSUE THREAD

**Issue by tomschrot** [microsoft/vscode#76894]
Issue Type: <b>Bug</b>

Im just opening menu - Terminal/Configure Standard Build Task
Status Bar shows animated icon and "Buildaufgaben werden abgerufen..." forever.
Same with "Execute Build Task"

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-intelephense-client|bme|1.1.1
githistory|don|0.4.6
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
kotlin|fwc|0.1.13
todo-tree|Gru|0.0.138
mysql-syntax|jak|1.3.1
Kotlin|mat|1.7.0
git-graph|mhu|1.10.0
vscode-language-pack-de|MS-|1.36.2
debugger-for-chrome|msj|4.11.6
java|red|0.46.0
code-settings-sync|Sha|3.3.1
highlight-matching-tag|vin|0.9.2
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
vscode-icons|vsc|8.8.0
json|Zai|1.0.2

</details>

**Comment by alexr00** [comment]
@tomschrot does is reproduce if you disable all extensions?

**Comment by tomschrot** [comment]
@alexr00 -disabled all extensions (except German language pack) and it still hangs trying to open build configuration... :( 
There is the tasks.json file in .vscode dir that I use all the time and worked well.

**Comment by alexr00** [comment]
Can you share your tasks.json file?

**Comment by tomschrot** [comment]
@alexr00:
 I use the project on two different machines (via gdrive) and there are no problems on my main workstation! (There weren't problems on the other machine either until yesterday!)

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "kotlin build",
            "type": "shell",
            "command": "${workspaceFolder}\\kotlin\\gradlew build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceFolder}\\kotlin\\"
            },
            "presentation": {
                "echo": false,
                "reveal": "always",
                "revealProblems": "onProblem",
                "focus": true,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            }
        }
    ]
}

**Comment by alexr00** [comment]
@tomschrot that isn't valid json. The backslash in `"cwd": "${workspaceFolder}\kotlin\"` causes the last `"` to be escaped, which in turn causes an un-closed string.

**Comment by tomschrot** [comment]
Of course, you are right! It was "swallowed" by the insite editor here!
The original is (screenshot)

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "kotlin build",
            "type": "shell",
            "command": "${workspaceFolder}\\kotlin\\gradlew build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "options": {
                "cwd": "${workspaceFolder}\\kotlin\\"
            },
            "presentation": {
                "echo": false,
                "reveal": "always",
                "revealProblems": "onProblem",
                "focus": true,
                "panel": "dedicated",
                "showReuseMessage": true,
                "clear": true
            }
        }
    ]
}

**Comment by alexr00** [comment]
I still can't repro. This really looks like an extension is not returning tasks. Since you tried disabling all extensions, can you try disabling some built-in extensions (you can find them by using "@builtin" in the extensions viewlet). 
Can you try disabling:
"Npm support for VS Code"
"Grunt support for VS Code"
"TypeScript and JavaScript Language Features"
"Jake support for VS Code"
"Gulp support for VSCode"

And then see if it still happens?

**Comment by tomschrot** [comment]
Disabled.....
but no change. (See status bar)
Im wondering if there is a way to kind of reset vs code to initial state without loosing the installed extensions...?

![image](https://user-images.githubusercontent.com/1196470/60894524-28b62b00-a263-11e9-830b-000e3c772f2b.png)

**Comment by tomschrot** [comment]
Ok, got a little closer.
(De-)activating your suggested extensions one by one with restart each time an checking seems that the JS/TS Extension is the wrongdoer. By deactivating it, vs code will meditate on build tasks.
Is there a way to clear settings?

**Comment by tomschrot** [comment]
Funny: activating JS/TS immediately starts build process, even after minutes....
(but this is only true for my main workstation)

**Comment by tomschrot** [comment]
I did all of the above on my notebook and it still hangs..... :(

**Comment by alexr00** [comment]
Are you using the same repository across your notebook and main workstation?

**Comment by tomschrot** [comment]
Yes I do. I've been doing this for over a year now without any problems due to project files being local.
I solved the issue finally. Uninstalled VS Code and deleted all VSC artifacts in the windows user directory by hand. Then installed VS Code again and voila its working.
Even all extensions are there without re installing them....!? Seems that VS Code hooks its stuff deep in the system. How would I get rid of it if then?

**Comment by alexr00** [comment]
If it is fixed after a re-install and all your extensions were still there, then it could have been something in your settings file. If you see the issue start happening again please re-open the issue or create another issue and we'll keep trying to narrow it down.

**Comment by svilenmarkov** [comment]
I'm also experiencing this issue where trying to run the build task or running a specific task hangs on "Fetching build tasks...". I narrowed it down to the Gulp builtin extension and more specifically my gulpfile.js having a `watch()` at the bottom. Either disabling the extension or removing the watcher fixes the issue.

**Comment by alexr00** [comment]
@svilenmarkov can you open a new issue for that please?
