### ISSUE TITLE
Add support of relative paths for ```git.ignoredRepositories``` 

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#76892]
_Originally posted by @r44083 in https://github.com/microsoft/vscode/pull/47890#issuecomment-506282034 pulling this up into an issue rather than a comment in a merged PR_

Hi, could you please add support of relative ```git.ignoredRepositories``` path? So it could be possible to add ignored repository in the following way:
```
"git.ignoredRepositories": ["./openwrt"]
or 
"git.ignoredRepositories": ["${workspaceFolder}/openwrt"]
```
instead of
```
"git.ignoredRepositories": ["/home/username/some/absolute/path/openwrt"]
```

**Comment by mushtaqak** [comment]
@joaomoreno I am interested in fixing this issue, I will put up a PR shortly.

**Comment by abhinuvpitale** [comment]
@mushtaqak are you working on this, if not lmk, I ll take it up

**Comment by mushtaqak** [comment]
@abhinuvpitale I hadn't started on this. If you are interested then please feel free to take it up. (I smh didn't get the notification of thumb-up emoji from Jao Moreneo)

**Comment by abhinuvpitale** [comment]
let me give it a shot then

**Comment by abhinuvpitale** [comment]
@joaomoreno what would be a good place to start?

**Comment by adityakaria** [comment]
@abhinuvpitale are you still working on this? If not, I'd like to try my hand it. 
Ps: I'm new to this repository, and this seems like a good place to start.

**Comment by abhinuvpitale** [comment]
@adityakaria go for it!

**Comment by Wowol** [comment]
Hi, @adityakaria, are you still working on this? If not, I'll be glad to take it.

**Comment by joaomoreno** [comment]
**Verification:**

The chosen syntax is `"git.ignoredRepositories": ["./openwrt"]` and it means _relative from any of the workspace folders.
