### ISSUE TITLE
Snippet adds extra blank line

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#76908]
Issue Type: <b>Bug</b>

In a .vue file, trying to use a Javascript snippet (to insert a console.log statement) a blank line is entered below the statement:
![image](https://user-images.githubusercontent.com/13488/60834343-875da500-a18e-11e9-9943-fd7b1df967f4.png)

![image](https://user-images.githubusercontent.com/13488/60834352-8b89c280-a18e-11e9-94cb-d074a0fb982b.png)

VS Code version: Code - Insiders 1.37.0-insider (d50852db1af10ec100a71ad57cc3a04c8aead117, 2019-07-08T05:33:31.335Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.88GB free)|
|Process Argv|-psn_0_6776438|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
auto-close-tag|for|0.5.6
output-colorizer|IBM|0.1.2
Angular2|joh|8.1.1
azure-account|ms-|0.8.4
csharp|ms-|1.21.0-beta1
vscode-typescript-tslint-plugin|ms-|1.2.1
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.0
quicktype|qui|12.0.46
vue-vscode-snippets|sdr|1.7.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.7

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This snippet is defined to do that: https://github.com/microsoft/vscode/blob/f3569142cc702896e3569b6f3de66f41d02a613d/extensions/javascript/snippets/javascript.json#L173-L180

**Comment by jrieken** [comment]
I'd say 'as-designed' but I leave it up to @mjbvz

**Comment by jtsom** [comment]
Weird, but ok I guess. Just making sure it wasn't some weird bug.

**Comment by mjbvz** [comment]
Yes, the snippet has been this way for a while
