### ISSUE TITLE
Code Navigation Regression - "Unable to read file"

### ISSUE THREAD

**Issue by mayorbyrne** [microsoft/vscode#76907]
- VSCode Version: 1.36+
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl+Click a pub-hosted class/file
2. Error showing in lower-right popup, ex: "(Error: File not found (c:\Users\...\AppData\Roaming\Pub\Cache\hosted\httpXGGpub........."

Does this issue occur when all extensions are disabled?:  N/A

This is a regression from 1.35, in which it successfully navigated to the class/file in question. Still occurring on latest 1.37 insiders

Sorry, this one is kind of difficult to explain.

**Comment by mayorbyrne** [comment]
Here's a gif showing my issue. Note that the filepath has %encoded parameters (`http%58%47%47pub.x.com%5850004`) but the popup says it is trying to hit (`httpXGGpub.x.comX50004`) (not sure if that has anything to do with it) ![code nav error](https://user-images.githubusercontent.com/1082201/60840129-6304c700-a194-11e9-8a23-a6b558a76393.gif)

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/76506
