### ISSUE TITLE
Allow multiple instances of the File Explorer

### ISSUE THREAD

**Issue by 1138-4EB** [microsoft/vscode#76902]
Ref #74229
Ref #76302
Ref #76891

---

> [[@nicolo-ribaudo#74229]](https://github.com/microsoft/vscode/issues/74229#issuecomment-496626167)
> The file explorer should also allow duplicating the same file tree, like split editor view allows viewing different positions of the same file.

---

> [[@1138-4EB#76891]](https://github.com/microsoft/vscode/issues/76891#issuecomment-509288763)
> an alternative I have considered is to use an additional 'subtree view', where the desired file explorer subtree is shown. However, I'm afraid that it is not possible to 'reuse' all the default and custom options that are configured/defined for the File Explorer viewId. I.e., to make a (custom) copy/instance of File Explorer with a limited scope. Hence, I would need to reimplement all the features in the custom view, which sounds as a no-go.
> 
> Another approach would be to filter the content of the default File Explorer, instead of trying to reveal some subdir. Is it possible to programmatically filter the content of the File Explorer?

> [[@isidorn#76891]](https://github.com/microsoft/vscode/issues/76891#issuecomment-509291505) 
> We are not exposing the Explorer via the API.
>
> And sorry it is not possible to programmaticly filter the content in the file explorer. It is simply not exposed and this goes with our API rules.

**Comment by isidorn** [comment]
Feature request. We do not plan it for the immedaite future, thus assigning to backlog.
