### ISSUE TITLE
Terminal with Git bash

### ISSUE THREAD

**Issue by tungvn** [Microsoft/vscode#7690]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Change the key "terminal.integrated.shell.windows" with value "C:\\Program Files\\Git\\git-bash.exe" (path to git-bash.exe file, like as cmd or powershell)
2. Try ``Ctrl+` ``, gitbash show external vscode, not in terminal box. I can not type anything on terminal box (not git bash)

**Comment by mdocter** [comment]
I found that same instruction somewhere, but it should be:

 "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

**Comment by mdocter** [comment]
Duplicate of #7286.

**Comment by tungvn** [comment]
Yeah, thanks a lot!

**Comment by jamiebarrow** [comment]
As [commented](https://github.com/Microsoft/vscode/issues/10054#issuecomment-261115806) in #10054, you can also try the below configuration:

```
// settings.json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\Program Files\\Git\\bin\\bash.exe"
    ]
}
```

**Comment by aflext** [comment]
@jamiebarrow not worked for me. It seems the shell args not executed.

**Comment by aflext** [comment]
`"terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
       "E:\\Program Files\\Git\\bin\\bash.exe"
    ]`

**Comment by NicolasDragon** [comment]
for every windows 10 users with bash terminal:
  "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"

**Comment by miguelgilrosas** [comment]
Thank you.

**Comment by jonaskello** [comment]
The solution suggested by @jamiebarrow works for MSYS2 shell too. However when you exit you get to cmd and need to exit again.

**Comment by caiobep** [comment]
My way around was opening the git bash without the cmd using : 
```json
    "terminal.integrated.shell.windows": "C:\\path_to_your_git_bash",
    "terminal.integrated.shellArgs.windows": [
      "--command=usr/bin/bash.exe",
      "-l",
      "-i"
    ]
```
It works pretty well and it already loads my bash_profile!

**Comment by c3y** [comment]
@mdocter thanks but bash.exe doesn't print with colors. For example, ls command returns all the results same color. but git-bash.exe makes the directories blue.
