### ISSUE TITLE
Update Octicons to match new icon style

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#76909]
This is to track the work of updating [Octicons](https://octicons.github.com/) to match our new outline icon style (#8017). We currently use Octicons in the [Status Bar and Quick Pick items](https://code.visualstudio.com/api/references/icons-in-labels). Since we will be updating the icon style, this means that we will be replacing Octicons with our own custom icon font.

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/35271042/64648767-71f43980-d3d0-11e9-94fa-2cbd179a0313.png">

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35271042/64648435-bc28eb00-d3cf-11e9-821c-b1c6c44f7017.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/35271042/64648526-ef6b7a00-d3cf-11e9-86c8-8c962226d10b.png">

**Comment by misolori** [comment]
This is now enabled by default in `master` (will be on Insiders next week). We've introduced a new settings `workbench.octiconsUpdate.enabled` that controls the visibility of the new Octicons style. Below is a snapshot of the updates:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/35271042/63150272-aa3d6d80-c006-11e9-9773-8b8a4803c94d.png">

**Comment by johnletey** [comment]
@misolori This is amazing! Can't wait to try out these new icons!

**Comment by johnletey** [comment]
@misolori Would it be possible to also have the Figma for the new octicons?

**Comment by misolori** [comment]
@johnletey once they are finalized we will publish them as well to the same repo/Figma file. Though that might not happen until next month as we just added them and will be getting feedback/iterating on them.

**Comment by sean-mcmanus** [comment]
Before:

![image](https://user-images.githubusercontent.com/19859882/63308561-0b37a080-c2a8-11e9-9483-5189811b943a.png)

After -- not what the C/C++ extension team wants: 

![image](https://user-images.githubusercontent.com/19859882/63308565-1094eb00-c2a8-11e9-92b9-a5c73b7da8d4.png)

Expected: Can you allow extensions to still use the old style somehow for their icons? Or do you have another suggestion?

**Comment by bobbrow** [comment]
I agree with @sean-mcmanus.  The flame icon is unrecognizable at this point. Some outlines just don't work well enough to convey meaning.

**Comment by bobbrow** [comment]
Some icons got to keep their solid fills: ![image](https://user-images.githubusercontent.com/12818240/63363525-a1131000-c328-11e9-8a6c-46c6007ac99b.png) ![image](https://user-images.githubusercontent.com/12818240/63363538-a708f100-c328-11e9-8bc0-6af2af0390c3.png) ![image](https://user-images.githubusercontent.com/12818240/63363561-aff9c280-c328-11e9-9d3b-77d0f2de79f3.png)

Please keep the solid fill for the flame icon too.

**Comment by johnletey** [comment]
I'm a fan of the new GitHub logo

![Shot 2019-08-20 at 17 12 12](https://user-images.githubusercontent.com/30328854/63364538-b3636d00-c36d-11e9-9656-e30c27582e2e.jpg)

**Comment by Guema** [comment]
> @sean-mcmanus @bobbrow here's a few alternates for the flame that match our outline style, let me know if you like one over the other. I personally prefer 1 or 2.
> 
> <img alt="image" width="230" src="https://user-images.githubusercontent.com/35271042/63811725-207e8180-c8dd-11e9-8215-d44b6efe1da2.png">

The 1 is the best in my opinion.
Even if unfortunately a graphic chart can never satisfy everyone.
It's look like a flame, and it's simple.

2nd works fine, but more complex.
The line inside make it more readable in red on blue though.

3rd is simple but can create confusion as it also looks like a water drop.

model 1 has the most identifiable shape in my opinion, while 2 is more readable.
Maybe a 1 shaped with an inside shape like the 2 could do the trick ?

**Comment by Tyriar** [comment]
Flame 2 looks best to me, I thought Flame 1 was a thumbs up icon.

**Comment by misolori** [comment]
Thanks everyone for the feedback, I've update the flame icon to version 2 and it'll be updated in tomorrow's Insiders:

<img width="130" alt="image" src="https://user-images.githubusercontent.com/35271042/64380913-e43ad780-cfe6-11e9-8943-99579e74cf9a.png">
