### ISSUE TITLE
One of folders within a Workspace now shows empty and all content disappeared all of the sudden

### ISSUE THREAD

**Issue by Mari0203** [microsoft/vscode#76916]
Hello,

One of my folders named, "Coding" within my Workspace all of the sudden shows as empty.  All I did recently was to add a new working folder under this same Workspace and added terraform extension.  All other folders remain unaffected.

How can I retrieve my disappeared contents?  Is there a log file I can examine what happened? 

**VSC version: 1.36.0**
**Installed extensions:** 
- Terraform 1.3.12
- SQL Server (mssql) 1.6.0
- Prettier - Code formatter 1.9.0
- Open in Browser 2.0.0
- Liver Server 5.6.1
- ESLint 1.9.0
- Color Picker 0.4.5

**Comment by bpasero** [comment]
@Mari0203 that should never happen, do you have more details about the workspace? Where was it located?

**Comment by Mari0203** [comment]
Hi @bpasero. Not sure if I'm understanding your question correctly, but the the affected workspace is on my local machine's desktop. Just noticed this morning that now another subfolder lost all of its content as well.  I have 2 more subfolder under the same workspace that remain unaffected---yet I have not touched anything since yesterday....  Is there a log file I can examine on my own?

**Comment by bpasero** [comment]
@Mari0203 the folder is not within the installation directory of VSCode, or is it?
