### ISSUE TITLE
VSCode stable release does not recognize Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/vscode#7691]
- VSCode Version: 1.2.1
- OS Version: 10.0.1461

Steps to Reproduce:

1. Toggle Integrated Terminal
2. type bash or bash.exe
3. Be greeted by error

![yunobash](https://cloud.githubusercontent.com/assets/7173984/16068581/eeb1ddb4-3294-11e6-81b7-20ff4e4f2cbe.PNG)

**Comment by Tyriar** [comment]
This should work by adding this to your settings.json:

```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
}
```

**Comment by rogersachan** [comment]
That fix didn't work unfortunately, still doesn't recognize Bash on Ubuntu on Windows.

**Comment by Tyriar** [comment]
What happens when you add that setting and restart vscode? Can you take a screenshot?

You could also try: `C:\\Windows\\SysWOW64\\bash.exe`

And if that doesn't work, check to see that the executable is actually located there.

**Comment by rogersachan** [comment]
Those aren't working either and even if I give it a direct path it still won't work!

**Comment by Tyriar** [comment]
Can you describe what happens and post a screenshot? Also toggling developer tools via the help menu and seeing there are errors in the console would be useful.
