### ISSUE TITLE
Dirty file indicator in quick pick not using same color as in the tab.

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#76912]
![image](https://user-images.githubusercontent.com/2193314/60837868-2f1ea700-a17e-11e9-9e09-d5330cc42bb2.png)

**Comment by misolori** [comment]
Should be fixed now, had the theme icons mixed up:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/35271042/60838205-fdf2a680-a17e-11e9-909d-a6bd1b474bb8.png">
