### ISSUE TITLE
VSIX Files Adding To /tmp Each Hour VSCode is Open.

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode#76911]
Issue Type: <b>Bug</b>

- VSCode Version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:15:26.964Z)

- OS Version: Linux x64 5.1.15.a-1-hardened

Steps to Reproduce:

1. Open Visual Studio Code.
2. Monitor /tmp folder for created vsix files.

Does this issue occur when all extensions are disabled?: No

I am already aware of:
https://github.com/Microsoft/vscode/issues/53110
and
https://github.com/microsoft/vscode/issues/54925
both of which are closed with no apparent resolution after about 1 year so far.
In other words don't close this, or re-open 53110, or let me know if this issue should be posted to vscode-cpptools instead ("why" below).

Each hour that vscode is open, a vsix is downloaded and is never removed from /tmp.
I unzipped 2 of the 20+ vsix files and it looks to be related to the c/cpp extension. This is the "why" it MAY need to be posted to their repository instead of here.
Given that Archlinux mounts /tmp as tmpfs, that is taking up memory, and it adds up over hours.
I do NOT believe it's related to https://github.com/microsoft/vscode-cpptools/issues/3093 since I'm online and it has no problems installing and I have no problems when using it.
I usually only update if a changelog looks appealing to me or applicable to an issue I have.

<b>extensions.autoCheckUpdates</b> is set to "enabled".
Wouldn't this ONLY check for a version online and NOT download the updated extension?

<b>Extensions: Auto Update</b> is set to "disabled".
So it shouldn't even be downloading the extension automatically.

<b>Expectations:</b>
- A vsix would NOT be downloaded unless an install has been requested.
- A vsix would be cleaned up either:
A. After an install completes
B. When VSCode is closing
- A vsix file would go by a filename of \<extension repository name>-\<extension version>.vsix rather than what appears to be a random filename like tmp-<17 random letters/numbers>.vsix

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (4 x 2574)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.25GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Doxygen|bbe|1.0.0
arm|dan|0.3.0
xml|Dot|2.4.0
vscode-solution-explorer|fer|0.3.1
ilspy-vscode|ics|0.7.5
vscode-nuget-package-manager|jmr|1.1.6
cortex-debug|mar|0.3.0
cortex-debug-dp-stm32f1|mar|1.0.0
cortex-debug-dp-stm32f4|mar|1.0.0
mssql|ms-|1.5.0
cpptools|ms-|0.23.1
csharp|ms-|1.20.0
debugger-for-chrome|msj|4.11.3
view-in-browser|qin|0.0.5
msbuild-project-tools|tin|0.2.54
debug|web|0.23.1
riscv|zhw|0.0.4
linkerscript|Zix|1.0.0

</details>

**Comment by sandy081** [comment]
@vindicatorr VSIX files are downloaded to `/tmp` folder from Marketplace and will be deleted after installing. Fix for #53110 does this.

Can you please let us know which vsixs are those? Can you reproduce this issue by disabling all extensions? Is it possible that one of the installed extensions is doing this?

**Comment by vindicatorr** [comment]
I'll just copy/paste what I had already filled in for the bug template:

"Does this issue occur when all extensions are disabled?: No"
"I unzipped 2 of the 20+ vsix files and it looks to be related to the c/cpp extension"

I've attached one of the vsix files (had to add .zip to be uploaded here):
[tmp-3523lOiS2uBxUhQ.vsix.zip](https://github.com/microsoft/vscode/files/3374932/tmp-3523lOiS2uBxUhQ.vsix.zip)

**Comment by sandy081** [comment]
I remember there is beta feature in C++ extension that makes it to download the VSIX.

I can confirm that when VS Code installs extension from Marketplace, it downloads the VSIX into temp location and deletes it after installing.

Can you please file issue against C++ extension asking them if they are deleting the VSIX after downloading.
