### ISSUE TITLE
Newline behavior is unexpected

### ISSUE THREAD

**Issue by sriharshamadala** [microsoft/vscode#76915]
Issue Type: <b>Bug</b>

Steps :
* At the start "git diff" shows nothing.
* Changed a line and saved the file (:w)
* git diff now shows two changes - the line i changed above and a completely different line that is not even nearby (2k lines apart). The diff for the unexpected line change is like :
-    str1 ^Mstr2
+    str1
+str2
* I was able to reproduce this behavior by disabling the vim extension.
* I made the line change in notepad instead of VS code and I do not see this behavior. 

Environment :
I have the following extensions :
* Vim (vscodevim)
* WAVE
* C/C++ IntelliSense 0.24.0
* Azure Repos
* CPPLint

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-install-vsix|fab|1.4.0
vscode-nmake-tools|Mic|2.0.190607004
cpptools|ms-|0.24.0
team|ms-|1.149.2
vim|vsc|1.8.1

</details>

**Comment by alexandrudima** [comment]
@sriharshamadala I don't understand your issue. Is your issue about the vim extension, that you executed an edit with the vim extension and that the resulting text is not what you were expecting?
