### ISSUE TITLE
Stage all adds a mystery dir

### ISSUE THREAD

**Issue by chulan** [microsoft/vscode#76910]
Issue Type: <b>Bug</b>

Noticed when staging changed files, but also occurs when no modified files exist

Click 'Stage all changes' and the dir appears in staged and in changes

I'm not sure what is creating the dir, it appears to contain a duplication of the project dir

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|9.8.2
rainbow-csv|mec|1.1.1
python|ms-|2019.6.22090
powershell|ms-|2019.5.0
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
![post-stageAll](https://user-images.githubusercontent.com/419514/60835608-998d1280-a191-11e9-952c-3a2644c8d376.JPG)
![pre-stage](https://user-images.githubusercontent.com/419514/60835609-998d1280-a191-11e9-8125-5c2edb16d2be.JPG)

vscode-maven|vsc|0.17.1

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
What dir? What's its name...?
