### ISSUE TITLE
Seti file icons broken / not showing

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#76925]
This might be related to the recent changes in the seti-ui repo (cc @orta):

<img width="925" alt="image" src="https://user-images.githubusercontent.com/35271042/60857221-92c8c480-a1be-11e9-9d6e-f1068b404f01.png">

Repro:
1. Open settings.json file
2. 🐛 TypeScript icon appears (which is wrong, should be `{ }` and it's significantly larger

Version: 1.37.0-insider
Commit: 4f3262dd1bba349e5be1e415a60874662da2c038
Date: 2019-07-08T23:47:40.093Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by eamodio** [comment]
When using seti file icon theme, the icons don't render at all for me -- which just started in the latest insiders

**Comment by aeschli** [comment]
I reverted the seti update.

**Comment by aeschli** [comment]
Theme is back in the mean time.

**Comment by lramos15** [comment]
Seti icons still show the settings.json as Typescript for me

**Comment by jrieken** [comment]
<img width="809" alt="Screenshot 2019-07-31 at 10 53 40" src="https://user-images.githubusercontent.com/1794099/62198298-a57b8700-b381-11e9-9eaf-a5db23d2836b.png">

Works for me, both 1.36.1 and 1.37 show the same icon for TS files

**Comment by jrieken** [comment]
Extracted the setting.json issue into #78261
