### ISSUE TITLE
Save section order of left panel in global.

### ISSUE THREAD

**Issue by jerryzhoujw** [microsoft/vscode#76922]
It's may related to [Alternative locations for the outline view](https://github.com/Microsoft/vscode/issues/49923), Just to void disturb peoples who subscribe in that issue, so I create this one.

Instead fo to move Outline view to the right panel. 
I'd like to keep it in left. And provide **save section order of left panel to all projects**.

Currently I open a new project and change it's section order like 
`OUTLINE`, `Project..`, `DEPENC` and so on.

In this way, I can **easily view the Outline view** by just expand the always first line of left panels(fixed position). and fold it when I don't needed(still the fixed position at first line of left panels).

But the current problem is this order can only remember in each project self instead of saving to all projects. So I have to change the order every time when I download/create a new project.

**Comment by sandy081** [comment]
Verify the order of views in the side bar is persisted across all windows.

**Comment by SSJ9899TDylan** [comment]
What are you waiting for? Christmas 



Sent from myMail for iOS


Monday, 29 July 2019, 6:55 pm +1000 from notifications@github.com  <notifications@github.com>:
