### ISSUE TITLE
open new window

### ISSUE THREAD

**Issue by raptor314912** [microsoft/vscode#76928]
Issue Type: <b>Bug</b>

I've installed VSCode-win32-x64-1.36.0-insider on one PC, we have many users can remote that PC by same username at same time, if one user opened VScode, other users can't open it, and if double click VScode, it will show in other user's desktop.

VS Code version: Code - Insiders 1.36.0-insider (15b7c86d86319b187a5ef255c170184a8519c5af, 2019-06-14T10:37:04.235Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.

**Comment by Tyriar** [comment]
Use the user installer might fix your problems?

**Comment by joaomoreno** [comment]
Please try the user installer.
