### ISSUE TITLE
Toggle sidebar view shortcut

### ISSUE THREAD

**Issue by Jeffreyfan** [microsoft/vscode#76926]
Issue Type: <b>Feature Request</b>

Can CTL+SHIFT+E shortcut toggle the file explorer view?  

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
Not by default, but you can customise this.
Open keyboard shorcuts and add this

```
{
            "key": "ctrl+shift+e",
            "command": "workbench.action.toggleSidebarVisibility",
            "when": "sideBarVisible"
      }
```
