### ISSUE TITLE
extension post-install/post-update processes occur in multiple windows

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#76927]
Upon update to VS Code 1.36, (Windows 10 18932) I caught the C/C++ extension performing a post install process in each window that was open, each window reporting different errors.

VS Code should only trigger the post install process in a single window.

![image](https://user-images.githubusercontent.com/26179051/60859952-062bff80-a1da-11e9-9af9-59875b9b0286.png)

After I closed all windows one at a time and then restarted VS Code so that only one window opened, the extensions post install process successfully completed.

**Comment by sandy081** [comment]
This is specific to C++ extension. Please file issue against it.

**Comment by msftrncs** [comment]
I don't think this is specific.   What mechanism does VS Code implement to insure IT does not tell an extension to start its post install operations in multiple Windows?   There is no reason this should occur, ever, for any extension.
