### ISSUE TITLE
Highlighting does not work for Javascript on windows 10 X64

### ISSUE THREAD

**Issue by seta-namle** [microsoft/vscode#76924]
Issue Type: <b>Bug</b>

The hightlight does not work for Javascript on window 10 X64.
I tried to disable all extension and restart the VSCode but not luck.
Tried to update to latest version but got the same result.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.28GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
vscode-for-node-js-development-pack|nod|2.0.1
vscode-import-cost|wix|2.12.0

</details>

**Comment by seta-namle** [comment]
As I see, the issue comes up with theme "Dark (Visual Studio)" when I changed to monokai, the highlighting works well.

**Comment by mjbvz** [comment]
For all js files? Can you share a screenshot?

**Comment by seta-namle** [comment]
Yes, FYI
![image](https://user-images.githubusercontent.com/50015330/60934108-31544300-a2ef-11e9-94a6-2b6229120dce.png)

![hightlight02](https://user-images.githubusercontent.com/50015330/60934235-ac1d5e00-a2ef-11e9-912b-4a5c74ec5315.png)

**Comment by mjbvz** [comment]
Please explain exactly what isn't working as you expect

**Comment by seta-namle** [comment]
As you can see, it highlights only keywords. I'm not sure this is the feature of theme "Dark (visual studio)".
As I think, it should highlight other part like this:
![Screenshot from 2019-07-10 13-56-54](https://user-images.githubusercontent.com/50015330/60947427-b739b380-a31a-11e9-8e77-2457cc718886.png)

**Comment by mjbvz** [comment]
Change you theme to `dark+` (not `dark (visual studio)`)
