### ISSUE TITLE
Explorer: improved copy/paste into another folder

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#76939]
Currently, when copy-pasting into another folder, VS Code simply renames the file/folder by appending " copy".

However, I'd like VS Code to behave as follows:
When copy-pasting a file into another folder: prompt "replace/skip".
When copy-pasting a folder into another folder: prompt with 3 options:
* merge (+ prompt "replace/skip" for files with the same name)
* replace
* skip
There should also be a new setting, which allows to set the default action for copy-pasting a folder into another folder (e.g. in Windows Explorer, the default is "merge" as described above)

(note that this is similar to #64784, but the expected behavior is not quite the same (and I was unable to update the now-outdated title))

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
I have updated that title, and closing this one as a duplicate.
Thanks!
