### ISSUE TITLE
File icons are not visible after the latest insiders update

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#76932]
Issue Type: <b>Bug</b>

file icons for different files are not visible after the latest insiders update.
I am using the "seti (visual studio code) theme.
![image](https://user-images.githubusercontent.com/9264813/60863414-46bd6480-a23e-11e9-9225-74303dd757b9.png)

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (2.25GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.8
vscode-remote-extensionpack|ms-|0.15.0
debugger-for-chrome|msj|4.11.6
ng-template|Ang|0.800.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
python|ms-|2019.6.22090
typescript-javascript-grammar|ms-|0.0.50
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.56
fabric8-analytics|red|0.0.12
vscodeintellicode|Vis|1.1.7

</details>

**Comment by aeschli** [comment]
dup of #76925
