### ISSUE TITLE
Unable to access ThemableDecorationAttachmentRenderOptions when writing theme extension

### ISSUE THREAD

**Issue by jcklpe** [microsoft/vscode#76935]
- VSCode Version: 1.36
- OS Version: Windows 10

I'm trying to write a syntax hilighting and theme extension and the documentation for it is very thin. 

I can see from reading the examples that I can set the foreground and background colors under the theme tokenColors section but I don't seem to be able to access any of the [ThemableDecorationAttachmentRenderOptions](https://code.visualstudio.com/api/references/vscode-api#ThemableDecorationAttachmentRenderOptions). 

So what's up with that? The documentation describes these as "themable". Am I doing something wrong or is this feature broken? Or merely missing?

**Comment by aeschli** [comment]
Token colors are not yet available as color ids.
That's part of the request for https://github.com/microsoft/vscode/issues/32813

**Comment by aeschli** [comment]
closing as duplicate

**Comment by jcklpe** [comment]
@aeschli  Thank you, that was informative. Have a nice day!
