### ISSUE TITLE
npm install output in console is messed up

### ISSUE THREAD

**Issue by M-Zuber** [Microsoft/vscode#7693]
- VSCode Version: 1.2.1
- OS Version: Win 10 Home x64

Steps to Reproduce:

1. Open console
2. Run npm install
3. See something like this 
![image](https://cloud.githubusercontent.com/assets/4746537/16069608/68f0ce62-32d8-11e6-8a17-d470478e0ae7.png)

**Comment by sandy081** [comment]
@M-Zuber May I know for which node module you are running npm install command?
Are you using the terminal inside code?

Thanks

**Comment by M-Zuber** [comment]
The terminal is the one inside code.

I've seen output like this for any command I've run, but the example above was with `npm i -g tslint`

**Comment by sandy081** [comment]
@M-Zuber Thanks for the information

**Comment by Tyriar** [comment]
Fixed in insiders with the adoption of xterm.js

![image](https://cloud.githubusercontent.com/assets/2193314/16073888/dc76b1ee-329c-11e6-9637-0760bf0856b1.png)

**Comment by M-Zuber** [comment]
Wow!! that was a :fire: quick fix!

Thank you!!
