### ISSUE TITLE
Git status bar contribution shows status for wrong root

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#76949]
1. Multi root workspace (for example vscode and vscode-docs)
2. Click on vscode-docs file -> status bar gets nicely updated to show git status for the vscode-docs repo
3. Click back on a vscode file -> status bar does not get updated 🐛 

I can repro 100%

![git](https://user-images.githubusercontent.com/1926584/60872408-e7a72200-a234-11e9-8d61-51875894780a.gif)

**Comment by joaomoreno** [comment]
@isidorn Did this break recently?

**Comment by isidorn** [comment]
@joaomoreno I rarely use multi root workspaces so I can not say when this broke.

**Comment by joaomoreno** [comment]
No repro! :(
