### ISSUE TITLE
shortcut to hide editor's tooltip hint

### ISSUE THREAD

**Issue by glacjay** [microsoft/vscode#76948]
I've typed something, I've done reading the tooltip hint, and now I want some method to hide it, without using my mouse.

**Comment by rebornix** [comment]
what do you mean by tooltip? Does *Escape* work for you?

**Comment by glacjay** [comment]
I mean this:

![图片](https://user-images.githubusercontent.com/292719/61431650-c9da6b00-a960-11e9-8ec0-263234107885.png)

And no, escape key doesn't work for me, maybe cause I'm using vim-mode plugin :-(

**Comment by rebornix** [comment]
@glacjay You can probably configure the Vim extension or keybindings to make it work then.

**Comment by glacjay** [comment]
OK, found that shift-esc can do this too.
