### ISSUE TITLE
Code is still runing after close it

### ISSUE THREAD

**Issue by PeterMX** [Microsoft/vscode#7694]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. open code use it as normal
2. close it and you have this  _/usr/share/code/code ./terminalProcess_ still runing

I don't know if this is a problem but I guess this isn't normal!
![code](https://cloud.githubusercontent.com/assets/9899682/16069690/072c4fcc-3296-11e6-9c8e-e848a2e52586.png)

**Comment by PeterMX** [comment]
sometimes process is just _/usr/share/code/code_

**Comment by PeterMX** [comment]
"Durmiendo" means "Sleeping" in english

**Comment by joaomoreno** [comment]
Duplicate of #7527
