### ISSUE TITLE
Deleting of text after autocompletion

### ISSUE THREAD

**Issue by LaetitiaSaillard** [microsoft/vscode#76955]
Issue Type: <b>Bug</b>
<br>
The purpose of this manipulation is to write text before another text and do autocompletion. Here is how to reproduce:<br>
Write in a page in HTML mode (the bug does not reproduce on a javascript page):<br>
`<script> HelloWorld </ script>`<br>
Position the caret just before the H<br>
Write document.getEl<br>
Press enter to validate autocomplete by document.getElementById<br>
The word HelloWorld disappears.<br>
Thank you for your work and your great software!<br><br>

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           W3530  @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
vscode-highlight|fab|1.3.4
compareit|in4|0.0.2
vscode-edit-csv|jan|0.0.12
vscode-language-pack-fr|MS-|1.35.1
powershell|ms-|2019.5.0

</details>

**Comment by aeschli** [comment]
dup of #67948
