### ISSUE TITLE
It is unfriendly when hovering over the extender

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode#76951]
-Version: 1.37.0-insider (user setup)
-Commit: 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904
-Date: 2019-07-09T05:26:27.407Z
-Electron: 4.2.5
-Chrome: 69.0.3497.128
-Node.js: 10.11.0
-V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install Cosmos DB Extension--> Expand the Cosmos DB accounts.
2. Check the result.

Actual:
It is unfriendly when hovering over the extender.
![image](https://user-images.githubusercontent.com/34729092/60872652-a845f900-a267-11e9-88b9-34091a866dbc.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Do your Insiders and your non-Insiders both have the same setting for `workbench.tree.renderIndentGuides` ?

Please explain what you mean by "unfriendly".

**Comment by v-dantch** [comment]
![image](https://user-images.githubusercontent.com/34729092/60934928-9eb9a100-a2fa-11e9-83ba-494ae93b4b2d.png)

The indent guides don't show if setting "workbench.tree.renderIndentGuides" to "None".

**Comment by joaomoreno** [comment]
Closing as designed. If you don't like indent guides, disable them in the settings.
