### ISSUE TITLE
Markdown preview not offered on WSL Remote

### ISSUE THREAD

**Issue by pcolmer** [microsoft/vscode#76953]
Issue Type: <b>Bug</b>

Use the WSL Remote feature to connect to a folder in WSL. Open a Markdown file.

Expected behaviour: in the top right corner, I would expect to see the Preview button.

Actual behaviour: no Preview button is displayed.

This functionality works as expected with Docker Remote connections.

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.6.4
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.8
vscode-remote-extensionpack|ms-|0.15.0

</details>

**Comment by pcolmer** [comment]
Just to be clear ... although this would seem to be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/376, that was supposed to be fixed on May 22nd and I'm seeing the problem now.

**Comment by mjbvz** [comment]
Do any other markdown features work, such as the document outline?

**Comment by pcolmer** [comment]
> Do any other markdown features work, such as the document outline?

I believe so. I've attached a screenshot of what I'm seeing.

![image](https://user-images.githubusercontent.com/1979931/60946186-796e6800-a2e5-11e9-9a31-731f571b94f5.png)

I've also updated overnight and the problem is still there.

**Comment by mjbvz** [comment]
Can you open the preview using the command palette? What if you try clicking where the button should be? I just want to understand if the problem is that the feature doesn't work or the icon isn't rendering.

**Comment by pcolmer** [comment]
@mjbvz My apologies for not thinking of that earlier.

The icon isn't rendering. In fact, there are a two non-rendering icons:

![image](https://user-images.githubusercontent.com/1979931/61109883-eddc0f00-a47d-11e9-8c3d-5b7d8bb4853d.png)

![image](https://user-images.githubusercontent.com/1979931/61109989-2d0a6000-a47e-11e9-993b-c649b7785eb0.png)

**Comment by mjbvz** [comment]
Thanks. 

@aeschli This looks like a potential icon loading issue for WSL. Can you please take a look

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/966
