### ISSUE TITLE
Intellisense for Node not working properly

### ISSUE THREAD

**Issue by Yadugaran** [microsoft/vscode#76957]
**VSCode Version: 1.36.0
OS Version: Win 7 Professional SP1**

Hi,
i recently started taking an online course for "nodejs". As i went along with the explanations and coding i started to notice some differences in the suggestions and information intellisense was giving in the examples in the course, compared to my system. To reproduce it, here is what i did:

1. Fresh Installation of Node.js 10.16.0
2. Fresh Installation of VSCode 1.36
3. Create a javascript file ("app.js")
4. type in the following code:

```
const http = require('http'); // Suggestion for core modules takes quite a while but it's getting there eventually

http.createServer( // Here is where intellisense/suggestions are quite useless
```

Expected information like i've seen it pop up in the video-course:
`function createServer(requestListener?: (request: IncomingMessage, response: ServerResponse) => void): Server`
------> the course uses **VSCode 1.26** with **Nodejs 8.12.0** on a **Mac** (Fresh Installation)

The information i get from VSCode:
`function createServer(requestListener?: RequestListener): Server`

Does this issue occur when all extensions are disabled?: Yes. It's the same. Also takes quite a while to load the basic node core module information. (suggestions inside the require('') statement)

**Please help**

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/32493 to track upstream
