### ISSUE TITLE
Terminal: Can't resize tmux panes using mouse

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76967]
Linux

Mouse drag behavior became much different recently. I can't no longer resize tmux panes. It does work if I double click tho... so this makes me thing the change was purposeful.

I also can't figure out how to select text to copy into the clipboard any more. None of the modifier keys let me select text such that Ctrl Shift C would copy it.

It's getting hard to stick to the integrated terminal like this. :cry:

**Comment by Tyriar** [comment]
Does it work in an outside terminal? I'm struggling to get mouse support working with `set -g mouse on` on mac (tmux 2.9a)

**Comment by joaomoreno** [comment]
Yup works in iTerm 2, tmux 2.9a.

**Comment by Tyriar** [comment]
Doh, .tmux.conf, not .tmux-conf. I can repro the issue

**Comment by joaomoreno** [comment]
Thanks!!
