### ISSUE TITLE
window.nativeFullScreen no longer recognised

### ISSUE THREAD

**Issue by o8e** [microsoft/vscode#76961]
In the last few days, `window.nativeFullScreen` has suddenly stopped working and shows as an `Unknown configuration setting`.

Has this disappeared?

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_36#_engineering

**Comment by o8e** [comment]
> https://code.visualstudio.com/updates/v1_36#_engineering

Oh. Well that's shit.

That answers my Q. Cheers.
