### ISSUE TITLE
javascript highlighting: destructuring over multiple lines breaks highlighting

### ISSUE THREAD

**Issue by AdamWillden** [Microsoft/vscode#7696]
- VSCode Version: 1.3.0 insider
- OS Version: Windows 10 x64

Pictures explain this best:

 1. This is okay - destructuring on one line:

![image](https://cloud.githubusercontent.com/assets/4629144/16070788/a6b26336-32cf-11e6-9101-df6aea444b76.png)

 2. This is broken - destructuring over multiple lines:

![image](https://cloud.githubusercontent.com/assets/4629144/16070829/dc26d420-32cf-11e6-9aeb-5fe2d108f685.png)

**Comment by sandy081** [comment]
I think this is typescript code.

@dbaeumer Not sure if this has to go to Typescript guys or we own the decorations. So assigning to you.

Thanks

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#189
