### ISSUE TITLE
Find Next Selection (Ctrl+F3) behavior is inconsistent with Ctrl+D

### ISSUE THREAD

**Issue by ditek** [microsoft/vscode#76960]
In VS Code, when you select a word and then press Ctrl+D (`editor.action.addSelectionToNextFindMatch`) partial words are found:

![image](https://user-images.githubusercontent.com/10835824/60874692-b4ff2880-a238-11e9-896c-1ce38a4e7d56.png)

When the cursor is on the word without selecting it, only whole words are found:

![image](https://user-images.githubusercontent.com/10835824/60874834-eed02f00-a238-11e9-9b11-50567ad1e64b.png)

However, with Ctrl+F3 (`editor.action.nextSelectionMatchFindAction`) the behavior is always finding partial words. That is inconsistent with how Ctrl+D works and also how other editors (namely Sublime Text and Intellij) behave.

Tested on VSCode version 1.36.0.

**Comment by alexandrudima** [comment]
Well, we try to please everybody... Ctrl+D and Ctrl+K Ctrl+D are mainly targeted to folks used to multicursor (like in Sublime) and Ctrl+F3 is targeted to folks used to searching (like in VS).

* Ctrl+F3 is `editor.action.nextSelectionMatchFindAction`.
* Ctrl+D is `editor.action.addSelectionToNextFindMatch`.
* Ctrl+K Ctrl+D is `editor.action.moveSelectionToNextFindMatch`

Simply remap Ctrl+F3 to `editor.action.moveSelectionToNextFindMatch`
