### ISSUE TITLE
SFTP plugins not working as of 1.36

### ISSUE THREAD

**Issue by immortaltako** [microsoft/vscode#76969]
Any plugin that supports SFTP (I currently use Remote FS but have tried this with 3 different plugins) fails after upgrading VSC to 1.36. All three plugins throw the same error:

`Error while signing data with privateKey: error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM`

However, downgrading to 1.35 and all three SFTP plugins work again

**Comment by gjsjohnmurray** [comment]
1.36 brought Electron 4, Chrome 69 and Node.js 10.11.0, so perhaps one or more of those upgrades is relevant. In any case I think you need to raise your issue with the extension provider.
