### ISSUE TITLE
Javascript Highlight does not turns on for "*.debug.js%3fctag=190708" files, after update 1.36.0

### ISSUE THREAD

**Issue by Gennady-G** [microsoft/vscode#76968]
Greetings!

- VSCode Version: 
- OS Version: Win 2012 R2

Version: 1.36.0 (system setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

Steps to Reproduce:

1. I add file in chrome Sources -> Overrides. It saves file with ctag in name, for example 'myfile.debug.js%3fctag=190708'

![2019-07-09_150941](https://user-images.githubusercontent.com/5569346/60890358-2e643e80-a26c-11e9-8b64-d8dea4ca254a.png)
2. Try to select Language mode to javascript, and it does nothing. No highlght is turned on.

Maybe something related with: this [this issue](https://github.com/microsoft/vscode/issues/11878), but not sure

**Comment by alexr00** [comment]
Fixed in 1.36.1.

FYI @jrieken I think this was a URI thing

**Comment by Gennady-G** [comment]
Thank You!
