### ISSUE TITLE
Npm script don't show in explorer

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#76971]
Issue Type: <b>Bug</b>

Even with the right setting the script in my package.json file don't show in the npm script explorer

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:11:51.716Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.98GB (1.12GB free)|
|Process Argv|--folder-uri file:///d%3A/electron/GestionSiteRestau|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.4.4
project-manager|ale|10.5.2
vscode-custom-css|be5|3.0.4
css-compressor|bes|0.0.2
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
docs-markdown|doc|0.2.9
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.13.0
vscode-mysql|for|0.4.0
beautify|Hoo|1.5.0
ftp-simple|hum|0.7.0
typings-autoinstaller|jvi|1.2.0
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.36.2
debugger-for-chrome|msj|4.11.6
live-server-preview|neg|0.1.4
markdown-preview-enhanced|shd|0.4.3
flowmaker|spe|1.2.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

![bugNpmScripts1](https://user-images.githubusercontent.com/624802/60887062-c0138200-a253-11e9-8225-31c741e4661b.PNG)
![bugNpmScripts2](https://user-images.githubusercontent.com/624802/60887070-c3a70900-a253-11e9-9525-68753c14e90f.PNG)

**Comment by egamma** [comment]
/needsMoreInfo

Cannot reproduce given the information provided. Please verify that you have the user setting `npm.enableScriptexplorer` set to true.

**Comment by albu77** [comment]
I don't see which infos I could add:
Even with the last Vs code version
Version : 1.37.1 (system setup)
Validation : f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date : 2019-08-15T16:18:10.377Z
Électron : 4.2.7
Chrome : 69.0.3497.128
Node.js : 10.11.0
V8 : 6.9.427.31-electron.0
OS : Windows_NT ia32 6.1.7601
Extensions enabled or disables: same problem

- Setting is Ok
- Scripts are declared in package.json

Results: No scripts appear in the script Explorer
![image](https://user-images.githubusercontent.com/624802/63638012-6e984880-c683-11e9-8068-1fd3d6810b57.png)

![image](https://user-images.githubusercontent.com/624802/63637993-342eab80-c683-11e9-8690-5ae6e27859a9.png)
![image](https://user-images.githubusercontent.com/624802/63638003-54f70100-c683-11e9-8aa5-aa76fdfa0b96.png)

**Comment by albu77** [comment]
Eventually find where was coming from. Ikept my original task.json file from long time ago and was using 0.1.0 version . After stting to 2.0.0 and changing the syntax for my build command for running electron the script explorer is now working
