### ISSUE TITLE
Not asking OTP on npm publish

### ISSUE THREAD

**Issue by hemendralexium** [microsoft/vscode#76973]
Issue Type: <b>Bug</b>

I have configured two factor authentication on my npm package, on publishing npm package it was showing error. While when I published same package with terminal it asked me OTP. Please provide right configuration or check the issue if there is any.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
Angular2|joh|8.1.1
csharp|ms-|1.20.0
debugger-for-chrome|msj|4.11.6

</details>

**Comment by Tyriar** [comment]
What did you get the error in and what did you not get the error in? It's not clear?

**Comment by hemendralexium** [comment]
Sorry I also don't have any screen shot of same. Anyway now its
working fine on vscode also, now vscode is also asking OTP. It was weired
but now issue is not replecating.
