### ISSUE TITLE
improvements in explorer

### ISSUE THREAD

**Issue by SandrinSF** [microsoft/vscode#76974]
Issue Type: <b>Feature Request</b>

I saw that they updated the explorer, it was a legal change. but I still have many problems with it, I think quite confused, I think that increasing the spacing between father and son would improve enough

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-30deepin-generic

**Comment by usernamehw** [comment]
```json
"workbench.tree.indent": 20
```
