### ISSUE TITLE
A11y_VSCode_VersionControl_Keyboard_Keyboard focus is not going on the publish button

### ISSUE THREAD

**Issue by prasadaps** [microsoft/vscode#76975]
**Environment Details:**
VSCode Version : 1.36.0
OS Version : Win10
Additional Details:
MAS Violated : MAS 2.4.3

**Repro Steps:**
1.Open Visual studio code editor
2.Using F1 key navigate to the palette, type "git branch" and select "Create Branch"
3. Enter the branch name in the edit field and hit enter. Observe the change in branch name at the bottom left corner
4. Publish branch to the remote Git repository by navigating to the bottom left pane, arriving at the cloud button next to the git branch and hit ENTER
5. Observe the focus is going on the publish button.

**Actual:**
Focus is not going on the publish button which are at bottom of the application .
The same issue is observed on all the button which are present at bottom of the application 
![image](https://user-images.githubusercontent.com/51405877/60952362-bf90ef00-a318-11e9-90ae-4bb23e4ee372.png)

**Expected:**
Focus should be go on this button's

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
User Impact:
Keyboard and screen reader user will face difficulty to access this controls. 

**MAS Reference:**
MAS 2.4.3 -https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}
**Attachment For Reference:** 
[BOTTON BUTTON ARE NOT ACCESSIBLE.pptx](https://github.com/microsoft/vscode/files/3372927/BOTTON.BUTTON.ARE.NOT.ACCESSIBLE.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is by design, we do not focu sthe status bar because that would bring too many hops for the user to naviagte through our workbench.
Also none of the status bar items have unique information, that is all duplicated and is simply designed to not be accessed by tab navigation
