### ISSUE TITLE
Mouse back and forward buttons do not work with latest update

### ISSUE THREAD

**Issue by rohansekhri** [microsoft/vscode#76982]
Have a logitech M510 mouse which has side buttons that act like back and forward.

They used to work until the May update and now they do not work while navigating code. However, Alt + <- | -> still works. 

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
/duplicate of #71318 and will be fixed in upcoming recovery release

@rohansekhri  please close this one.

**Comment by rohansekhri** [comment]
Closing!!
