### ISSUE TITLE
Can't open file when path contains cyrillic and urlencode

### ISSUE THREAD

**Issue by mkpankov** [microsoft/vscode#76988]
Issue Type: <b>Bug</b>

I have a file located in Git repository at `Результаты-тестов/ISS-SDK/ISS-SDK-001%2D0.21.md`.
VS Code displays it in side bar, but when I click it, an error message appears:
```
Unable to open 'ISS-SDK-001%2D0.21.md': Unable to read file (Error: File not found (/home/mkpankov/projects/FT-Procesess.wiki/Результаты-тестов/ISS-SDK/ISS-SDK-001-0.21.md)).
```
`less` displays the file with no issues.

Repository itself is a Wiki repository cloned from Azure DevOps Server, so urlencode is not my choice.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3527)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.32GB (1.68GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
reflow-markdown|mar|2.0.0
azure-pipelines|ms-|1.152.0
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.8
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0
tcl|ras|0.1.0
vscode-yaml|red|0.4.1
rust|rus|0.6.1
crates|ser|0.4.3
rewrap|stk|1.9.1
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
clang-format|xav|1.9.0

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Not sure if some URL encode/decode issue we recently fixed (cc @jrieken)

**Comment by gjsjohnmurray** [comment]
Probably [this](https://github.com/microsoft/vscode/issues/76506#issuecomment-509682376), which upcoming recovery release will fix.
