### ISSUE TITLE
disable extensions not working for extension debugging

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#76989]
- VSCode Version: 1.37.0-Insider
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Download https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample
2. Add `--disable-extensions` to `launch.json` as described in https://code.visualstudio.com/api/working-with-extensions/testing-extension#disabling-other-extensions-while-debugging: 
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run Extension",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--disable-extensions",
        "--extensionDevelopmentPath=${workspaceFolder}"
      ]
    }
  ]
}

```

Does this issue occur when all extensions are disabled?: Yes

Additional information: 
- calling `code-insiders --disable-extensions` from the command line works as expected
- `--disable-extensions` in `launch.json` has worked in version 1.35, it stopped working in 1.36

**Comment by iansan5653** [comment]
I am seeing the same behavior. It launches Code with an editor called `--disable-extensions`, and all extensions remain enabled.

#### System Information
Version: 1.37.0-insider (user setup)
Commit: 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904
Date: 2019-07-09T05:26:27.407Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by iansan5653** [comment]
I just tried running the tests using the `vscode-test` module with `launchArgs: ["--disable-extensions"]` and that did succesfully disable the extensions, so this appears limited to just running as a debug task with `type: extensionHost`.

**Comment by Septh** [comment]
Until this is fixed, using `--disable-extensions=1` seems to do the trick:

```
  "args": [
    "--extensionDevelopmentPath=${workspaceFolder}",
    "--disable-extensions=1"
  ],
```

**Comment by weinand** [comment]
Please try and verify the fix in the next Insiders build.

**Comment by SimonSiefke** [comment]
works great, thanks!

**Comment by iansan5653** [comment]
Can also verify, thank you!
