### ISSUE TITLE
Custom html tags are red in php language

### ISSUE THREAD

**Issue by adamk33n3r** [microsoft/vscode#76997]
This was rectified for the html language in #56467 but I'd like to see this done for php as well. I work with Laravel so all of my views are in php files.

![image](https://user-images.githubusercontent.com/1350444/60901489-0c52c800-a23c-11e9-96a3-ec3151a998c9.png)

**Comment by roblourens** [comment]
Guessing that we just need to get the php html grammar to reference `text.html.derivative`

https://github.com/microsoft/vscode/commit/cfc2a2212de9ea10943af58ebd1817a5ad196463
