### ISSUE TITLE
update loop

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode#76996]
Issue Type: <b>Bug</b>

With this version 

Version: 1.37.0-insider (user setup)
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:37:36.104Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

It seems like every time I start VS code, it's offering an update.

VS Code version: Code - Insiders 1.37.0-insider (d50852db1af10ec100a71ad57cc3a04c8aead117, 2019-07-08T05:37:36.104Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Can you fully uninstall VS Code and reinstall it?

**Comment by omartin2010** [comment]
It somehow went away at some point without reinstalling.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
