### ISSUE TITLE
[typescript] Collapsed code expansion on syntax error

### ISSUE THREAD

**Issue by dkazmer** [microsoft/vscode#76990]
Please fix issue wherein all my subsequent collapsed areas suddenly expand in my large JS file just for typing `(` or `{`, as it's deemed an error for not having closed them. Then I have to waste time recollapsing them.

**Comment by mjbvz** [comment]
Can you please provide steps to reproduce this (with example code)

**Comment by dkazmer** [comment]
I'll try my best to elaborate without giving you code due to its confidential and proprietary nature.
I'm working building a very custom and flexible date picker in vanilla JS (es6+) with some dependencies - whatever - and it's gotten to 1000+ lines. So to keep visually organized I'm collapsing all my methods and functions, some of which contain template literals to inject HTML where needed. In them, if I start to write `{` or `(` (to run a function to insert dynamic data), all subsequent code is now in error because the editor is looking for their closing brackets. This causes all my subsequent collapsed code to expand. Hope that's clear.

**Comment by mjbvz** [comment]
Please provide some example code. It doesn't need to run and you can rename all the variables to something generic; it just needs to be syntactically valid and demonstrate the issue

**Comment by dkazmer** [comment]
Oy vey!
All that's needed to reproduce is 4 lines of code
```
var mytemp = `template literal`;
function mFunc(params) {
    // something here
}
```
Step 1: fold the function (via little minus icon)
Step 2: in the template literal type `${`
You will now see the function unfold. This is especially annoying in large files with many folds.

**Comment by bowdenk7** [comment]
@mjbvz removing needs more info tag as I can repro with the snippet above.

**Comment by mjbvz** [comment]
@aeschli What's the recommendation for extensions here? We provide the folding ranges based on the current document state, and if you add a `${` then the entire rest of the program will look like a template expression to us

**Comment by aeschli** [comment]
Ideally, the parser's error recovery is able to put a limit on the length of the incomplete construct.
On the UI side it helps to have autoclosing pairs. E.g. when the user types a `${` already add `}`.

**Comment by dkazmer** [comment]
Basically the equivalent to saying Nice to have, but fuck it.
I hate that bot.
