### ISSUE TITLE
Monaco API: `css` / `scss` / `less` aren't bundling anymore in monaco 

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#7699]
After building the latest run: 

```ts
monaco.languages.getLanguages().forEach(function(language) {
    console.log(language); // DEBUG
});
```
And you will not see `css` in there

/cc @alexandrudima sorry I keep mentioning you but you seem to be managing (helping us with :heart:) the monaco API singularly right now :rose:

**Comment by basarat** [comment]
Got it. Happening cause of this : https://github.com/Microsoft/vscode/blame/master/src/vs/languages/languages.main.ts#L13

/cc @aeschli :rose:

**Comment by basarat** [comment]
refs https://github.com/alm-tools/alm/pull/121

**Comment by basarat** [comment]
I've made a new release of the build automation of monaco I am using for [alm.tools](http://alm.tools) ([commit](https://github.com/basarat/monaco/commit/3552a4958c80023a487089760545fda1751260f6#diff-de2dfcc43796b9f87cb55ee95e2f8f1dR292)) which unblocks me for now. 

If you are satisfied with the fix on your end (i.e. just leaving those files in here but still commented out) feel free to close this :heart:

**Comment by aeschli** [comment]
I added them back to editor.main.ts, so they show up again in the standalone editor

**Comment by basarat** [comment]
> I added them back to editor.main.ts, so they show up again in the standalone editor

worked like a charm :rose: Thanks!
