### ISSUE TITLE
Files reverted and deleted by Git panel not in trash

### ISSUE THREAD

**Issue by waynebloss** [microsoft/vscode#76993]
- VSCode Version: 1.36.0
- OS Version: 4.19.56-1-MANJARO

Steps to Reproduce:

1. Have setting `files.enableTrash` enabled.
2. Create a new file in your workspace.
3. Use the Git panel `revert changes` icon to delete the new file.
4. File not found in trash.

Does this issue occur when all extensions are disabled?: Yes.

Why I think this is a bug:

1. The major facility for working with files, the Explorer panel, always moves files to the trash.
2. So, the user gets used to depending on the relative safety of using VSCode to deal with files.
3. Changing the behavior in another panel, even though the alert message says that the file will be "DELETED" in all caps, is very unexpected.
4. At the very least, the alert message should make this change of behavior more clear with more text IMO.

Thanks!

**Comment by joaomoreno** [comment]
The git integration only uses git commands, which do not understand the concept of a trash. As the setting indicates, `files.enableTrash`, this is only related to file actions, not Git/SCM actions.

> At the very least, the alert message should make this change of behavior more clear with more text IMO.

We can do more text, do you have any recommendations?

**Comment by waynebloss** [comment]
Thanks!

If you are not interested in making git commands follow the `files.enableTrash` setting then it would be nice to see another line appended to the original text, something like `"Please note that these files will NOT be sent to Trash."`.

However, since we know what GIT will do when we run the `revert changes` command on an untracked file, wouldn't it be really nice if VSCode just sent those files to trash for you? I am usually pretty careful about what I'm deleting but I have certainly regretted reverting changes in the past. As a matter of fact, I'd love to see VSCode send even tracked files with modifications to Trash before reverting them...

I suppose that I can do this with some sort of bash script that replaces my system `git` command but that sounds like a lot more work than what could be done from inside VSCode.

**Comment by waynebloss** [comment]
For now, since I've discovered this behavior, I think instead of reverting files, I'll try to get into the habit of using the VSCode Explorer panel to delete the files that I want to revert (to Trash) and then revert the deletions in the GIT panel. That is certainly the safest workflow.

**Comment by joaomoreno** [comment]
I think `DELETED` already implies that they won't go to trash, but they will be deleted instead. Sorry about your missing files, but I'm glad you found a workflow which works for you.

**Comment by waynebloss** [comment]
I disagree because in many, many contexts `DELETING` something means you're sending it to the trash.

By far the most used OS (Windows) labels the context menu in Explorer as `Delete`, the command that actually sends things to the recycling bin.

So, I think it's a very bad idea to not differentiate what is actually happening in this scenario because people will continue to lose files.

**Comment by joaomoreno** [comment]
Alright. We were already showing the following message when using the Discard All action:

```
This is IRREVERSIBLE!
Your current working set will be FOREVER LOST.
```

I've added the same disclaimer for the Discard action.
