### ISSUE TITLE
Simplify shell command for Linux and OS X

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#77]
Is there a shell command out of the box to launch VSCode?

Atom has `atom`
Sublime has `subl`

**Comment by egamma** [comment]
VS Code has `code`

**Comment by jchannon** [comment]
<img width="855" alt="screen shot 2015-11-18 at 18 10 14" src="https://cloud.githubusercontent.com/assets/105126/11249583/a2d2e9b6-8e1f-11e5-8ee5-3c82c1418326.png">

**Comment by lukehoban** [comment]
On OS X, you need to follow the instructions here to invoke from the command line: https://code.visualstudio.com/Docs/editor/setup.

It would be nice to have an installer on OS X that configured this automatically.

**Comment by jchannon** [comment]
Agreed. Not sure how atom and sublime do it

**Comment by egamma** [comment]
apologies, forgot that it was a manual step for me on OS X.

**Comment by Tyriar** [comment]
For `atom`, this file is renamed from atom.sh and is put in `/usr/bin/atom` and `/usr/share/atom`

https://github.com/atom/atom/blob/1ee08be508f6892a6bd2f412d03dcb70de59ebe3/atom.sh

**Comment by ZombieProtectionAgency** [comment]
For future reference Githubs issue tracker is not for support or feature suggestions. Feature suggestions already have a place over at vscodes [uservoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code) and you can ask for help on StackOverflow with the [\[vscode\] tag](https://stackoverflow.com/questions/tagged/vscode)

**Comment by jchannon** [comment]
Unlike every other OSS library?

**Comment by ZombieProtectionAgency** [comment]
No idea what you mean, I was just trying to be helpful. With VS Code going open source I figured a lot of people are going to be posting questions to the issue tracker which would be better suited for StackOverflow.

Ill delete my comment since you seem to have an issue with it.

**Comment by bpasero** [comment]
Closing, we have instructions for adding "code" to the path.

**Comment by jchannon** [comment]
Not exactly a seamless user experience is it and seeing as the other
editors provide this for you out of the box and Erik considers it a feature
I'd ask you to reopen this

**Comment by joaomoreno** [comment]
This is valid and I want to fix it.

**Comment by Tyriar** [comment]
I created https://github.com/Microsoft/vscode-docs/pull/46 in the docs to improve the script so it doesn't consume the terminal.

**Comment by 0xmohit** [comment]
It would be nice to see the binary being renamed from `Code` to `code`.

**Comment by mackenza** [comment]
it's not just a matter of putting it on the path. It needs a decent shell script so that control returns to your terminal window.

Also, as @0xmohit points out, it's called `Code` and not `code` which makes a difference

**Comment by Tyriar** [comment]
@mackenza my PR features a small script that does this, something similar should probably be included in the codebase eventually https://github.com/Microsoft/vscode-docs/pull/46 to meet user expectations

**Comment by Tyriar** [comment]
The script has been created, moving the OSX portion of this issue to https://github.com/Microsoft/vscode/issues/2859
