### ISSUE TITLE
C++: Comment block always auto-adds end symbol

### ISSUE THREAD

**Issue by andrew-r-king** [microsoft/vscode#77008]
- VSCode Version: 1.36.0
- OS Version: Windows 10 / Mac OS

Steps to Reproduce:

1. Write any c++ code inside of a .cpp/h/hpp etc file.
2. Type "/*" at the begging of of a line that has already been written
3. Notice "*/" gets automatically added afterwards, but before the code, so nothing actually gets commented out

Simple example, where "|" denotes the cursor position:
```
/*| */void mySoonToBeCommentedFunction() {}
```

"/*" shouldn't auto-add the end symbol of the comment block by default, should be setting controlled, and should be able to recognize when it's been entered at the start of a line.

Does this issue occur when all extensions are disabled?: Yes

Originally reported here:
https://github.com/microsoft/vscode-cpptools/issues/3904

They forwarded me to you folks, so I'm assuming this was added to the "C/C++ Language Basics" built-in extension without a setting to control it. Please for the love of god fix this. It's super annoying.

**Comment by andrew-r-king** [comment]
Found a temporary Workaround: 

1.Go to: (User Folder)\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions
2. Copy "cpp" to (User Folder)\.vscode\extensions
3. Rename it something like "cpp.language-basics-custom" to avoid any later confusion.
4. Open "language-configuration.json" & comment out (or remove) this line:

```
{ "open": "/*", "close": " */", "notIn": ["string", "comment"] }
```

5. Remove the trailing comma in the previous line (might not be necessary)
6. Save
7. Reload VS Code. The custom version should take precedence over the built-in version.

**Comment by andrew-r-king** [comment]
Also, of note:
Neither javascript nor typescript contains that in their language-configuration.json files, but uses that style of block comments obviously, so I think it's safe to say it should just be removed from the cpp language-configuration.json.

**Comment by alexr00** [comment]
It looks like C# and json use the `/*` as an auto closing pair, but java, javascript, php, and typescript use the `/**`. For C languages we whould use `/**` since it is more consistent.

**Comment by alexr00** [comment]
Fix will be available in next insiders if you want it ASAP. It installs side by side with stable, so you can have both: https://code.visualstudio.com/insiders/

**Comment by bobbrow** [comment]
@alexr00, the C/C++ extension already registers a custom `LanguageConfiguration`, including `onEnterRules` for `/**`.

Please don't add autoClosingPairs for comments since there is no way to disable them in vscode.  There are only settings for `autoClosingBrackets` and `autoClosingQuotes`.  I seem to recall these all being controlled by a single setting at some point, but now there are only 2 out of 3 available.
