### ISSUE TITLE
Custom views: Node decorations are on the wrong side of inline commands

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#77001]
Issue Type: <b>Bug</b>

Since the change to the new tree, nodes with decorations and inline commands cause the decorations to move to the left of the command, where previously they stayed in place on the right (like they still do in the SCM view). Also the spacing is too tight now too.

![image](https://user-images.githubusercontent.com/641685/60902339-70c25700-a23d-11e9-9870-c9ea7366dc6c.png)

//cc @alexr00 

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@eamodio thank you for doing all this great testing and filing issues!

**Comment by eamodio** [comment]
Looks good!
