### ISSUE TITLE
View Menu : UX Ideas

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#7700]
Currently we have quite number of views and view actions under Views menu and making it cumbersome. We should organize them better and effectively.

![views menu](https://cloud.githubusercontent.com/assets/10746682/16072484/64992ee6-32e1-11e6-815f-befb60246dde.png)

cc: @bpasero @gregvanl @stevencl

**Comment by sandy081** [comment]
One suggestion is to move views under main section and move other actions like toggle to secondary section.

**Comment by bpasero** [comment]
@stevencl @bgashler1 @chrisdias fyi we should make a decision. I do like the idea of moving the views and panel back to be top level and the other stuff into a sub menu.

**Comment by yisibl** [comment]
I think `Views` can be used as a top leve menu.

**Comment by bpasero** [comment]
Does not work for me if we also have a `View` menu.

**Comment by bpasero** [comment]
UX meeting decision: 

![image](https://cloud.githubusercontent.com/assets/900690/16274949/27f4a962-38a8-11e6-9237-f90aa69de97d.png)
