### ISSUE TITLE
Text added right after naming a new file disappears

### ISSUE THREAD

**Issue by yedayak** [microsoft/vscode#77005]
- VSCode Version: 1.36.0 (user setup)
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. create new file
2. open save file dialog (ctrl+s)
3. pick name and file extension (some extensions might make it easier to reproduce by a slower save process)
4. save.
5. write or paste text into file right away. the text disappears.

This works even when there is already text in the file.
The text isn't accessible by undoing or redoing. (ctrl+z/y)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by yedayak** [comment]
@bpasero I tried now, I wasn't able to reproduce it. I wonder what changed.
