### ISSUE TITLE
Comment API: actions are not hidden when contextValue changes

### ISSUE THREAD

**Issue by sbeland** [microsoft/vscode#77012]
- VSCode Version: Insiders 1.36
- OS Version: Mojave 10.14.5

Steps to Reproduce:
1. Add comment actions (comments/comment/actions) with the comment API.

2. Actions render clipped and overlapped.
<img width="1521" alt="Screen Shot 2019-07-09 at 11 49 32 AM" src="https://user-images.githubusercontent.com/3302319/60915127-e92a1780-a23f-11e9-96a2-50d9db59eec0.png">

3. Update the contextValue for a comment after the comment has been rendered, and now the comment action's "when" clause is false.

4. The comment actions are not hidden as expected. (If the "when" cause is false when the comment thread is drawn initially, then it works as expected. It also does not get fixed when I force a redraw. I've also seen flaky updating when I update a comment label).

Does this issue occur when all extensions are disabled?: N/A

**Comment by RMacfarlane** [comment]
Thanks for reporting this @sbeland! I've opened a separate issue for the rendering issue since that's independent of the update problem.

**Comment by sbeland** [comment]
Awesome! Thank you @RMacfarlane  :)

**Comment by sbeland** [comment]
@RMacfarlane I've also noticed that when I change a comment label, it doesn't force a redraw. Is there an explicit way to make it redraw?

**Comment by RMacfarlane** [comment]
After you update the property on the comment, are you also setting the comments property on the thread? I’m not sure how clear we made this in the documentation, but the mutations that actually cause redraws are

- updating the comment thread label
- updating the comment thread context value
- updating the comment thread collapsible state
- updating the comment thread comment array
- updating the comment thread range

That being said, I think there may may be a problem with the way we internally id comments. We had a previous version of the API that required specifying a `commentId` property on comments, we may still be trying to read from that in some cases. If so, then adding `commentId` on comments would be a workaround
