### ISSUE TITLE
Breadcrumbs capture backspace from editor

### ISSUE THREAD

**Issue by idreyn** [microsoft/vscode#77016]
Issue Type: <b>Bug</b>

When I have breadcrumbs enabled I cannot use the backspace key in the editor, because it is captured by the breadcrumbs as seen in the gif below. This happens whether or not I have any extensions enabled. I do not see any errors in the developer console. The suggested fix from the related issue in #28737 does not apply here.

**Screencast**

![giphy](https://user-images.githubusercontent.com/2208769/60916170-b7bf4500-a25b-11e9-8647-b45a146d6081.gif)

**Steps to reproduce**
- Enable breadcrumbs (`View > Show Breadcrumbs`)
- Open an editor and try backspacing to remove some text
- Observe that hitting backspace causes the breadcrumbs to focus, rather than deleting text.

**Expected behavior**
Pressing backspace deletes text while the editor is focused

**Observed behavior**
Pressing backspace focuses the breadcrumbs

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.79GB free)|
|Process Argv|-psn_0_376924|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.2
vsc-material-theme|Equ|29.2.0
rainbow-csv|mec|1.1.1
vscode-language-babel|mgm|0.0.22
theme-monokai-pro-vscode|mon|1.1.13
python|ms-|2019.6.22090
material-icon-theme|PKi|3.8.0
vscode-icons|vsc|8.8.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
@idreyn Can you try with 1.36.1 that we have release yesterday? Also, can you paste your keybindings.json file (F1 > Open Keyboard Shortcuts (JSON))

**Comment by idreyn** [comment]
Ah, I found the issue in `keybindings.json`!
```
{
    "key": "backspace backspace",
    "command": "breadcrumbs.focus",
    "when": "breadcrumbsPossible"
},
{
    "key": "shift+cmd+;",
    "command": "-breadcrumbs.focus",
    "when": "breadcrumbsPossible"
}
```
I'm not sure how these came to be here, but it definitely fixes the problem, thanks!
