### ISSUE TITLE
Add trailing empty new line when creating settings.json file

### ISSUE THREAD

**Issue by gemal** [microsoft/vscode#77017]
when the .vscode/settings.json files is created is should have a newline added to the end of the file to avoid this when checking in the file in github:

![2019-07-09_212412](https://user-images.githubusercontent.com/69105/60916976-20c0b000-a290-11e9-9d3a-f2b57a526555.png)

**Comment by roblourens** [comment]
It's not an error, some people like a trailing newline and some don't
