### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by HiuryBressanelli** [microsoft/vscode#77015]
Issue Type: <b>Feature Request</b>

programmers in php often need to use html within repeating loops, for example, and the functionality of allowing the editor to format the code just in the php extension leaving "out" all the html is really very frustrating, a whole team of programmers of a company do not use vscode for this reason. Please allow us to be able to format html within PHP exactly as it does netbeans, this would be a dream !!

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
We don't provide a PHP formatter out of the box, this is only provided by extensions. If you are using an extension for this, please file an issue on their repo.
