### ISSUE TITLE
[loc][Query][DevDiv] Translatability of Code

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#7701]
Hi, we have a question from our translator. Can you help please?

Source:
Please restart Code before reinstalling {0}.

File Name:
src\vs\platform\extensionManagement\node\extensionManagementService.nls.resx

Resource ID:
".resx", 0; "restartCode"

Query:
Is Code translatable?	Cristina Carrasco	6/9/2016 9:18:45 AM

**Comment by joaomoreno** [comment]
No, it's not. Should we extract it?

**Comment by mkyjakova** [comment]
Hi, thanks for your reply. I think it's fine for the moment. I let the translators know.
