### ISSUE TITLE
HTML in .php files

### ISSUE THREAD

**Issue by darckex** [microsoft/vscode#77014]
Issue Type: <b>Bug</b>

HTML in .php extension files outside the <?php block code no longer autocomplete attributes.  This used to work in v 1.35.1.

**Comment by Derjyn** [comment]
This seems like a pretty old issue, that has never been properly addressed. HTML in PHP files is nothing new or strange, so why syntax highlighting and such is unsupported is confusing. Plenty of other editors have had this for... Decades.

**Comment by kanlukasz** [comment]
What you mean by "no longer autocomplete attributes" ?

If you talk about tags, are you sure it still doesn't work? I've done the test now and it looks like it's working well

An example with a fresh installation without any custom settings:
![php1](https://user-images.githubusercontent.com/30685349/80917874-f6316d80-8d61-11ea-990a-f5f3669dbd3e.gif)


My env:
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Derjyn** [comment]
@kanlukasz - That's great! However it looks like your version is quite newer than the versions we were working with from 1 month to a year ago.

Thanks for sharing, though!

**Comment by rzhao271** [comment]
@darckex closing this issue for now as part of housekeeping, and because it seems fixed in a newer version (?). Feel free to reply if it still occurs for you on the latest version of VS Code.
