### ISSUE TITLE
Insert completion on Tab don't work

### ISSUE THREAD

**Issue by karambaq** [microsoft/vscode#77024]
- VSCode Version: 1.36.0
- OS Version: MacOS Mojave 10.14.5

In the vim I can do that:
![vim](https://user-images.githubusercontent.com/14233969/60925062-4f984f80-a2ab-11e9-9b8b-333db2f92625.gif)
But in vscode I can't,  this option is enabled: `"editor.tabCompletion": "on"`
![vscode](https://user-images.githubusercontent.com/14233969/60925112-748cc280-a2ab-11e9-81ff-b7742b1033cd.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by karambaq** [comment]
Umm, I can't find it in the existing issue

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/70532

**Comment by jrieken** [comment]
for the future, this is how you find duplicates once we have added subject-labels

![Jul-11-2019 15-20-33](https://user-images.githubusercontent.com/1794099/61054372-9c853e80-a3ef-11e9-9dad-3fcfac7e39a9.gif)

**Comment by karambaq** [comment]
@jrieken Thank you, but I think it's not the same issue, in my situation text under cursor isn't changing before I hit Enter.

**Comment by karambaq** [comment]
Any news on this?
