### ISSUE TITLE
Add single-space indent command

### ISSUE THREAD

**Issue by johndog** [microsoft/vscode#77028]
Currently it seems that a configured tab-stop is the only mechanism available for indentation.  Sometimes clean indentation requires higher precision than a tab-stop permits.  

I'd like the ability to indent by one space, regardless of tab-stop.  Here's the mechanic I'd prefer:

- If you select a whole-line block of text (i.e. one or more lines including newlines), then [Space] indents the line by one space, and [Shift]+[Space] un-indents by one space.  
- If your selection includes any partial lines, space works normally, replacing the selection with a space character.

I'm relatively certain I've used an editor that had this behavior before, but I can't remember which.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=usernamehw.indent-one-space

**Comment by johndog** [comment]
Splendid, this extension is perfect (even supporting configuration to the mechanic I prefer)
