### ISSUE TITLE
Custom views: Left padding of the tree items is large

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#77026]
Issue Type: <b>Bug</b>

Since the change to the new tree, the left padding of the root nodes is quite large:
![image](https://user-images.githubusercontent.com/641685/60928684-565b9e00-a27c-11e9-9bd9-fda4fedd20af.png)

//cc @alexr00 

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Well this is strange. I'm seeing the opposite, with 12px on the old tree and 8px on the new tree. I went back to the commit your on and saw the same 8px.

**Comment by eamodio** [comment]
Hrm, with the old I'm seeing 12px total, but with the new tree, the row is padded by 20px and then the twistie is another 8px.

![image](https://user-images.githubusercontent.com/641685/60970313-b63f5c80-a2ef-11e9-9121-d630adea77e2.png)

![image](https://user-images.githubusercontent.com/641685/60970346-c5bea580-a2ef-11e9-82a8-bcbedee44696.png)

And that is with today's insiders.

Version: 1.37.0-insider (user setup)
Commit: 360e4e4dfa989135f28edc0d6f7e42df33cddf87
Date: 2019-07-10T05:26:12.322Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by eamodio** [comment]
Somewhat related, I also noticed that `workbench.tree.indent` doesn't affect the custom trees (nor the SCM ones)

**Comment by alexr00** [comment]
Something strange is happening here. I see the `workbench.tree.indent` setting affect custom trees correctly. Can you share your user and workbench settings?

**Comment by eamodio** [comment]
Nevermind, this was my confusion -- the `workbench.tree.indent` doesn't affect the root nodes -- only children. All is fine, sorry :)

**Comment by alexr00** [comment]
Are you still seeing the extra padding to the left of the root node?

**Comment by eamodio** [comment]
Yes - the DOM/CSS looks the same in today's as yesterday's

**Comment by alexr00** [comment]
Can you share your user and workbench settings? I still can't reproduce this.

**Comment by eamodio** [comment]
@alexr00 I did more digging into this, and this only happens for views that are contributed into the `scm` sidebar -- `explorer` and custom activities are fine. I see this behavior with GitLens and GitHub PRs (but only when the views are in the `scm` sidebar)

**Comment by eamodio** [comment]
@alexr00 Do you need any more info on this?

**Comment by alexr00** [comment]
No, I can repro in the scm viewlet, thanks for tracking it to there!
