### ISSUE TITLE
Typescript IntelliSense stuck loading: Initializing JS/TS language features after auto updating to 1.36.1

### ISSUE THREAD

**Issue by canpoyrazoglu** [microsoft/vscode#77025]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Update VScode from 1.36 to 1.36.1
2. Try completing any Typescript code with Intellisense as usual.

Does this issue occur when all extensions are disabled?: No

**Comment by canpoyrazoglu** [comment]
In the logs I've noticed that Auto Rename Tag extension was halting. I've disabled Auto Rename Tag, Auto Close Tag, Auto Complete tag trio, restarted, and the problem went away.

Don't know if it's Vscode to blame or the extension though.

**Comment by mjbvz** [comment]
Please file an issue against that extension to start.

If you still see any issues with all extensions disabled, let me know
