### ISSUE TITLE
Code formatter moves to end of file

### ISSUE THREAD

**Issue by albertoalexander6537** [microsoft/vscode#77027]
Issue Type: <b>Bug</b>

Steps to reproduce: Edit an HTML document 150+ lines long. From the top or middle, select all (cmd-a). Format with cmd-k, cmd-f.

Result: The editor scrolls to the last line and leaves the bottom half of the editor window blank. Then you have to scroll up looking for where you were so you can continue working.

I think this must have something to do with needing to select the whole file contents before formatting, which loses track of the cursor. I suggest being like Eclipse, and formatting the whole file if a selection is not made.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_1745322|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|29.2.0
Angular2|joh|8.1.1
vscode-typescript-tslint-plugin|ms-|1.2.1
java|red|0.46.0
vscode-scss-formatter|sib|1.4.1
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jrieken** [comment]
Can you share the file that you have been formatting?

**Comment by albertoalexander6537** [comment]
Attached is one (zipped because github won't take html), but any html file will work, as long as there is something that needs to be formatted (e.g. one extra space somewhere.
[test.html.zip](https://github.com/microsoft/vscode/files/3377722/test.html.zip)

**Comment by jrieken** [comment]
Ah, now I get it. The thing is that you run "Select All" first. When doing that the cursor moves towards the end and formatting always reveals the active cursor. For you the easiest is to invoke format with selecting all (since cmd-k, cmd-f formats the whole while anyways)

**Comment by albertoalexander6537** [comment]
@jrieken Yes that is true, doing select all moves the cursor. Are you sure it's designed to format the whole document with cmd-k then cmd-f? For me, that does nothing. Perhaps that is the bug here?

I tried uninstalling/disabling all of my plugins to make sure none of them were messing with HTML formatting, but I get the same behavior.

**Comment by jrieken** [comment]
Sorry, you are right the cmd-k cmd-f sequence is actually "format selection". Try `shift-alt-f` - that's bound to "format document",
