### ISSUE TITLE
Bottom border doesn't show on tabs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7702]
Looking at the CSS there should be a bottom border outlining inactive tabs, this is current look:

![image](https://cloud.githubusercontent.com/assets/2193314/16073489/ebb1ece8-329a-11e6-81c5-2bcf1f949ef7.png)

Making tab element's height `36px` instead of `35px` displays it:

![image](https://cloud.githubusercontent.com/assets/2193314/16073512/0c70ed26-329b-11e6-9054-30026331e795.png)

**Comment by bpasero** [comment]
Great catch.
