### ISSUE TITLE
SQUARE ICONS on Windows, please help me to fix!

### ISSUE THREAD

**Issue by dmxt** [microsoft/vscode#77030]
Issue Type: <b>Bug</b>

Screenshot will speak it all for both enabled and disabled extension mode:
![](https://i.imgur.com/QSKeIZT.png)
![](https://i.imgur.com/0Uy8jIe.png)
<details>
<summary>Screenshots</summary>
</details>

Only icon pack that works is file-icons https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons

Aside from that, most icons appear as square, including those popular packs like material or vscode big pack.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.3
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
LogFileHighlighter|emi|2.5.0
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
file-icons|fil|1.0.17
html-slim-scss-css-class-completion|gen|1.5.17
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
svg-icons|idl|0.6.7
svg|joc|0.1.5
vscode-icon-theme|jtl|1.6.5
vscode-colorize|kam|0.8.11
git-graph|mhu|1.10.0
code-beautifier|mic|2.2.1
prettify-json|moh|0.0.3
python|ms-|2019.6.24221
svg-font-previewer|nko|1.1.5
fix-json|oli|0.1.2
material-icon-theme|PKi|3.8.0
view-in-browser|qin|0.0.5
colored-console-log|reh|1.0.7
ActiveFileInStatusBar|Ros|1.0.3
stylelint|shi|0.51.0
vscode-fileutils|sle|2.14.5
code-spell-checker|str|1.7.17
vscode-field-lights|sve|0.0.11
vscode-icon-all|tra|0.0.4
vscode-iconfont-preview|und|0.1.0
vscodeintellicode|Vis|1.1.7
vscode-icons|vsc|8.8.0
vscode-wakatime|Wak|2.1.2
file-size|zh9|0.1.3
html-css-class-completion|Zig|1.19.0

(27 theme extensions excluded)

</details>

**Comment by misolori** [comment]
@dmxt have you tried restarting the app + Windows to see if it persists? Can you also disable all extensions and try again?

**Comment by dmxt** [comment]
@misolori Yes, I restarted an app, Windows and attempted to reinstall VS Code and deleted /Code/ and /.vscode/ folders to start from scratch. I also added a [registry entry](https://code.visualstudio.com/docs/setup/windows) from official docs' however I'm on W10 machine, not W8/7 as mentioned in their official doc.

**Comment by dmxt** [comment]
@misolori 	I haven't pinpointed the cause but I also get this if status bar icon randomly started working

![](https://i.imgur.com/InS9SxZ.png)
(and icons on everywhere else, aside from status bar on bottom, became square)

It feels like a stressful lose-lose game.

**Comment by dmxt** [comment]
@misolori I found this batshit insanity "fix" that I would have to do every time I open VS Code window

https://gfycat.com/SlightWeepyAlpinegoat

**0. Ensure icon line is AFTER theme line in settings.json** otherwise status bar icons will be broken and the sidebar will be "unbroken" like some sort of invert effect
1. Delete icon line or change icon theme
2. Save
3. Restore icon line or icon theme
???
Icons are back!

This won't work if step 0 is inverted (aka icon line BEFORE theme line) with working sidebar icons - the status bar icons will remain broken no matter how many time you save settings.json, there's no way to rerender status bar but to fully restart vs code.

It was very hard to track down this part, it took me hours, this note may appear valuable for someone else.

**Comment by misolori** [comment]
@dmxt which icon theme are you setting? the default `vs-seti` or is this a separate extension?

**Comment by misolori** [comment]
@bpasero @aeschli have you either of you seen this before?

**Comment by bpasero** [comment]
No, never.

**Comment by dmxt** [comment]
@misolori `vs-seti` behave the same as other icon extension.

Only icon pack out of 20-30 icon packs I tried that works is file-icons https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons

I feel that it's an issue with SVG

**Comment by dmxt** [comment]
Anybody?

It's still not fixed. I even used `file-icons` which I thought worked in the first place, but it doesn't anymore after Windows 10 reinstall.

I have to select and set a file icon theme through `ctrl+p` every single time I cold start a VS Code to unsquare these square icons.

![image](https://user-images.githubusercontent.com/3248782/61707960-a4ab7b00-ad19-11e9-9276-756721fca05a.png)

**Any hack or trick to auto-run the script to set file icon every time I start a VS Code app?** It seems like my only solution because it seems like no one else have this issue even though I'm on freshly installed W10 and no one can solve it.

**Comment by misolori** [comment]
@dmxt sorry you're still having this issue, I tried to debug on my Windows machine w/ same OS build and same version of VS Code and can't reproduce this. We also haven't seen other reports of this so it's been hard to debug. Can you try using [Insiders](https://code.visualstudio.com/insiders/) and see if this still persists?
