### ISSUE TITLE
No response for quick fix when clicking one solution in the quick-fix dropdown menu

### ISSUE THREAD

**Issue by jenniferqyl** [microsoft/vscode#77032]
Issue Type: <b>Bug</b>

1. Find an error
2. Hover on
3. Click quick fix
4. Click on solution in quick fix dropdown menu
5. It doesn't work. But if you choose quick fix -> solution in problem tab, then it works. 

I am not sure what causes the bug. But the bug suddenly appeared since yesterday. And I think I didn't modify any configuration or add any extension yesterday.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.2
csharp|ms-|1.20.0
vscode-typescript-tslint-plugin|ms-|1.2.1
gradle-language|nac|0.2.3
java|red|0.46.0
code-spell-checker|str|1.7.17
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0

</details>

**Comment by pape2016** [comment]
I see this issue too, it happens from version 1.36.0, I upgraded to 1.36.1 just now, The issue is still there, not fixed.

**Comment by Fernandomr88** [comment]
> Issue Type: Bug
> 
> 1. Find an error
> 2. Hover on
> 3. Click quick fix
> 4. Click on solution in quick fix dropdown menu
> 5. It doesn't work. But if you choose quick fix -> solution in problem tab, then it works.
> 
> I am not sure what causes the bug. But the bug suddenly appeared since yesterday. And I think I didn't modify any configuration or add any extension yesterday.
> 
> VS Code version: Code 1.36.1 ([2213894](https://github.com/microsoft/vscode/commit/2213894ea0415ee8c85c5eea0d0ff81ecc191529), 2019-07-08T22:59:35.033Z)
> OS version: Windows_NT x64 10.0.17763
> 
> System Info
> Extensions (12)

already on https://github.com/microsoft/vscode/issues/77018
