### ISSUE TITLE
Copy tabulation

### ISSUE THREAD

**Issue by Galifray** [microsoft/vscode#77039]
Issue Type: <b>Feature Request</b>

ctrl-c ctrl-v why /t?

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.18.0-25-generic

**Comment by bpasero** [comment]
What is this request about?

**Comment by Galifray** [comment]
https://drive.google.com/file/d/1zwpU5cmQ83AfAyStdwURAzMOUb8gVyIj/view?usp=sharing
