### ISSUE TITLE
[Bug] After v1.37 vscode-exploration, the restore-down-button does not working 

### ISSUE THREAD

**Issue by ddzy** [microsoft/vscode#77037]
- VSCode Version: v1.37-exploration
- OS Version: Win10-1903

Steps to Reproduce:

**1. Click the restore-down-button** 

![vsc_issue_4](https://user-images.githubusercontent.com/33921398/60933917-f9e99480-a2f6-11e9-8a7b-355de0c8e9a6.png)

**2. The editor can not restore**

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@ddzy I am unable to reproduce this issue with the latest exploration build. Can you provide more details that might help reproduce?

/cc @deepak1556

**Comment by deepak1556** [comment]
Same as @sbatten wasn't able to repro based on the description. Can you please attach a gif/video describing the issue or clearer repro steps. Thanks!
