### ISSUE TITLE
[Bug] After v1.37 vscode-exploration, workspace layout is breaking when the window is minimized and then restored 

### ISSUE THREAD

**Issue by ddzy** [microsoft/vscode#77036]
- VSCode Version: v1.37-exploration
- OS Version: Win10-1903

Steps to Reproduce:

**1. Normal layout**

![vsc_issue_1](https://user-images.githubusercontent.com/33921398/60933239-06b8b900-a2f4-11e9-99b4-7ebb8b269c26.png)

**2. Minilize and restore**

![vsc_issue_2](https://user-images.githubusercontent.com/33921398/60933264-22bc5a80-a2f4-11e9-8dbe-6be99c512523.png)

**3. Complete step**

![vsc_issue_3](https://user-images.githubusercontent.com/33921398/60933450-dfaeb700-a2f4-11e9-9d93-9e9d6d57a30c.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I have no clue what is the issue here.
Can you please post reproducable steps?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
