### ISSUE TITLE
A11y_VSCode_SidebarBarOptions_AccessingTheExplorersidebaroptionsandCreatinga newfile_ScreenReader: Inappropriate name is announced for the “Open Editors”, “PRE.REQ” and “Outline” toolbar.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/vscode#77045]
**Environment Details:**
VSCode Version : 1.35.6 (user setup)
OS Version : Win10

**Additional Details:**
MAS Violated : MAS 1.3.1, MAS 4.1.2
ScreenReader Versions : NVDA2019.1.1, JAWS 2019

**Repro Steps:**
1.	Pre-req: Create an empty folder on desktop
2.	Open Visual studio code editor.
3.	Using "Ctrl+Shift+E" key navigate to the Explorer side view bar option.
4.	Using "Tab" key navigate to explorer side bar options.
5.	Arrive at the "Open Folder" button and hit "Enter".
6.	Select the folder created under "Pre-req".
7.	Using "Tab" key navigate to and select "New File" option using "Enter" key.
8.	Start screen reader
9.	Using "Tab" key navigate to extension side bar options. 

**Actual:**
When screen reader users navigate through the “Open Editors”, “PRE.REQ” and “Outline” toolbar inappropriate name is announced to the users which is incorrect.

**Expected:**
The “Open Editors”, “PRE.REQ” and “Outline” toolbar should be announced with the specific name and their state of either expand/collapsed accordingly.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx](https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
If the name of the controls is not announced properly to the screen reader user then they will get confused.

**MAS Reference:**
MAS 4.1.2 - [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}) 

**Attachment for Reference:**
![VSCode_SidebarBarOptions_AccessingTheExplorersidebaroptionsandCreatinga newfile_ScreenReader Inappropriate name for toolbar](https://user-images.githubusercontent.com/52036772/60942383-0faf8780-a300-11e9-9e8b-06fcc5151706.png)

**Comment by isidorn** [comment]
This works for me and also works for you (check your screen shot it nicely says Open Editors Section tool bar expanded).
We properly set the aria-expanded attribute. Thus closing as invalid
