### ISSUE TITLE
[Suggestion] About new folding-icon after v1.37-exploration

### ISSUE THREAD

**Issue by ddzy** [microsoft/vscode#77040]
## Current Feature

After updating to `v1.37 vscode-exploration`, the new icon for folding is not pretty💥.

**Here is the new icon:**

![vsc_icon_for_folding_issue_1](https://user-images.githubusercontent.com/33921398/60936260-138eda00-a2ff-11e9-8489-b9a8986a92e3.png)

![vsc_1](https://user-images.githubusercontent.com/33921398/60937625-9e71d380-a303-11e9-8608-b9528d77686a.gif)

**The old icon:**

![vsc_icon_for_folding_issue_2](https://user-images.githubusercontent.com/33921398/60936272-1b4e7e80-a2ff-11e9-983a-8390ee8ff2ed.png)

## Expected Feature

Is it possible to provide a way to use the previous icon?🚗

**Comment by misolori** [comment]
@ddzy Can you explain what it is about the old icon that you prefer over the new icon?
