### ISSUE TITLE
C/C++ conditional enum item color

### ISSUE THREAD

**Issue by pfaltynek-als** [microsoft/vscode#77046]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

#if and related preprocessing instructions are not correctly colorized inside of C/C++ enum:

enum FOO {
	ONE,
	TWO,
#if COND
	TWO_AND_HALF,
#endif
	THREE
}

#if COND
	#define TWO_AND_HALF 1
#endif

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
vscode-sqlite|ale|0.7.1
doxdocgen|csc|0.5.0
vscode-markdownlint|Dav|0.28.0
githistory|don|0.4.6
gitlens|eam|9.8.3
vscode-great-icons|emm|2.1.47
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
mono-debug|ms-|0.15.8
printcode|nob|3.0.0
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.3.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
gitflow|vec|1.2.1
wandbox-vscode|wra|2.2.3

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Moved to grammar repo.
