### ISSUE TITLE
Window: Native Tabs does not open new windows as tabs in MacOS Sierra

### ISSUE THREAD

**Issue by crabicode** [microsoft/vscode#77047]
- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: MacOS Siera 10.12.6

Env:

I have "prefer tabs when opening documents - Always" in dock panel.

Steps to Reproduce:

1. I've upgraded from May 2019 (version 1.35) to June 2019 (version 1.36)
2. I have Window: Native Tabs enabled
3. I toggle the internal terminal
4. I enter `code ./dir1`
5. I enter `code ./dir2`
6. I see two separate windows are open

Downgraded to May 2019 (version 1.35) and attempted the same scenario.
It worked as expected. I believe native tabs are broken in version 1.36.

**Comment by bpasero** [comment]
I cannot reproduce, it works for me. I see another tab opening next to the existing one.

**Comment by crabicode** [comment]
@bpasero what info do you require to investigate further? I am attaching the video.Last login: Wed Jul 10 10:27:37 on ttys001
~ » mkdir
~ » workspace
~/workspace » reprod

**Comment by crabicode** [comment]
UPD: Replaced the broken link to the video.

**Comment by crabicode** [comment]
My colleague has just tested the scenario on MacOS Mojave worked. However, on MacOS Sierra it does not.
