### ISSUE TITLE
CPU usage is high when scrolling

### ISSUE THREAD

**Issue by luoyefeisong** [microsoft/vscode#77051]
Issue Type: <b>Performance Issue</b>

Scroll the screen to reproduce

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    95	 11844	code main
    0	    13	  9692	   electron-crash-reporter
    1	    81	 12216	   gpu-process
   19	   112	 14008	   shared-process
    0	   232	 15088	   window (peer.h - sigsrv - Visual Studio Code)
    0	    11	 12292	     watcherService 
    0	    11	 10564	       console-window-host (Windows internal process)
    0	    69	 12736	     extensionHost
    0	    32	 15424	   utility
    1	    68	 15796	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (peer.h - sigsrv - Visual Studio Code)
|    Folder (sigsrv): more than 24543 files
|      File types: hpp(12264) h(11183) c(182) ipp(181) cpp(116) lib(105)
|                  obj(78) tlog(41) dll(39) mak(29)
|      Conf files: sln(5) cmake(4) settings.json(2);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
gitlens|eam|9.8.3
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
Go|ms-|0.11.4
code-settings-sync|Sha|3.3.1
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.7

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Based on the info provided above

```
CPU %	Mem MB	   PID	Process
    2	    95	 11844	code main
    0	    13	  9692	   electron-crash-reporter
    1	    81	 12216	   gpu-process
   19	   112	 14008	   shared-process
    0	   232	 15088	   window (peer.h - sigsrv - Visual Studio Code)
    0	    11	 12292	     watcherService 
    0	    11	 10564	       console-window-host (Windows internal process)
    0	    69	 12736	     extensionHost
    0	    32	 15424	   utility
    1	    68	 15796	   window (Issue Reporter)
```

The CPU usage seems reasonable. Can you please provide more info?

**Comment by luoyefeisong** [comment]
Ok, the previous information was generated by the `report issue` itself. I now manually scroll the text bar and observe the CPU occupancy of the Vs Code, which can be found at around 25%. The previous version did not have this problem.
![image](https://user-images.githubusercontent.com/13747710/61505417-56dcfd00-aa11-11e9-9b51-96d457a38fcd.png)

**Comment by rebornix** [comment]
@luoyefeisong can you please open Developer Tools and go to Performance tab and do some recording? 

* Record
* Scroll in the editor, make sure the CPU is higher than normal
* Stop recording and share the log

With the log we can dig into where the time is being used.

**Comment by luoyefeisong** [comment]
Sorry, I am not very familiar with js, here is my record
[Profile-20190722T100524.zip](https://github.com/microsoft/vscode/files/3415453/Profile-20190722T100524.zip)

**Comment by rebornix** [comment]
it seems you have long lines in the document, is it correct? 
![image](https://user-images.githubusercontent.com/876920/61668320-358a4400-ac91-11e9-9875-40c66913e4ea.png)

**Comment by luoyefeisong** [comment]
I just open a C file and it will take up such a high CPU. You can just open a C file and test it.
Like this, only one file is opened.
![image](https://user-images.githubusercontent.com/13747710/61694480-1c05fc80-ad64-11e9-9419-6529a7da1a77.png)

**Comment by Cheldon** [comment]
I'm seeing similar CPU usage/lag while scrolling C files since the last update 1.36.0+

**Comment by rebornix** [comment]
Can you please try run vs code by disabling all extensions and see if you can reproduce the same issue? `code--disable-extensions`. I'm wondering whether it's because C++ extension introduces semantic syntax highlighting.

**Comment by Cheldon** [comment]
I believe setting `"editor.occurrencesHighlight": false` fixed my performance issue. I also updated the ms-vscode.cpptools extension to 0.24.1 (July 22) and I turned that setting back the default true and I am not seeing any issues. The release notes indicate improvements to semantic colorization.

**Comment by luoyefeisong** [comment]
It is no problem for me to try my other computer. 
Turn off the problem first. Maybe there is something wrong with my computer.
