### ISSUE TITLE
Remote WSL: Server installation fails with wslpath missing

### ISSUE THREAD

**Issue by tinebp** [microsoft/vscode#77055]
- VSCode Version: 1.36.1
- OS Version: Windows 10
- Computer: Dell XPS 15 UHD 2018 model

Steps to Reproduce:
1. Install VS code on Windows 10
2. Install Remote-WSL extension
3. Select Remote-WSL: New Window

Expected:
A new window should open with WSL enabled

Actual:
WSL fails with error message. cannot find wslpath (see screenshot below)
![Screenshot (2)](https://user-images.githubusercontent.com/2282163/60947740-5b8e0c80-a2bf-11e9-863c-524858c82ea6.png)

Diagnostic:
Tried reinstalling vscode and ubuntu on the system, but still was able to reproduce the error.

**Comment by aeschli** [comment]
You are using a fairly old version of WSL that doesn't have `wslpath`.
I highly recommend you to update to the latest version (Windows 10, May 2019 Update). It also enables the Remote WSL extension to open any distro.

However, I published a new Remote WSL version (0.38.9) that works again when `wslpath` is not available.

**Comment by aeschli** [comment]
@tinebp Can you confirm that things work again?

**Comment by tinebp** [comment]
yes!
    On Tuesday, July 30, 2019, 03:33:51 AM EDT, Martin Aeschlimann <notifications@github.com> wrote:  
 
 
@tinebp Can you confirm that things work again?
