### ISSUE TITLE
Left side of Changes View not showed in actual encoding

### ISSUE THREAD

**Issue by mickeypearce** [microsoft/vscode#77069]
Left side of changes view shows file always in encoding UTF8 regardless of actual file encoding which is correctly shown on the right side.

- VSCode Version: 1.36.1
- OS Version: Windows_NT 6.1.7601

Steps to Reproduce:

1. create a file (ex. txt) with encoding other than utf-8 (ex. windows1250) with some text
2. stage file
3. add some changes to file and open changes (Git: Open changes)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/1925433/60953147-e2ada580-a2fc-11e9-93ad-32219295f6cb.png)

**Comment by joaomoreno** [comment]
#48038

**Comment by mickeypearce** [comment]
excuse me for duplicate.
