### ISSUE TITLE
EACCES when browsing extensions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7706]
From @hinogi, https://twitter.com/con_SSC/status/740876561835032576

> [...] ext install gives an error "connect EACCES 191.238.172.191:443"
> [...] I think I'm not behind a proxy, the stable works just fine

Possibly related to #5596

--

@hinogi I just want to confirm a few things:

- You have both the insider and stable releases installed in the same machine
- You can both browse and install extensions in the stable release
- You can't even browse extensions in the insider release
- Your stable installation doesn't have any proxy settings configured (both global and workspace settings).

Can you confirm all those details for me? Thanks!

Also, can you run `ping marketplace.visualstudio.com` in the command prompt?

**Comment by con-ssc** [comment]
I cannot ping marketplace.visualstudio.com I get a timeout there, I'm not sure if ICMP is active on the other side. tracert hops near the destination but cannot reach it if I look at the IP ranges.
After Hop  23   137 ms   136 ms   133 ms  ae86-0.sn2-96cb-1b.ntwk.msn.net [104.44.9.79] it does not continue.
The rest I can confirm.

**Comment by joaomoreno** [comment]
Yes, `timeout` makes sense. But it does resolve to `191.238.172.191` correct? It there anyway you could run a network analysis tool like Wireshark in both the insider and stable cases so we figure out what the difference it?

**Comment by con-ssc** [comment]
yes, it is not resolved. Anything special I should be looking for?

**Comment by con-ssc** [comment]
This is the stable version
![vscode stable ext install](https://cloud.githubusercontent.com/assets/8189808/16075747/6ad206a2-32f0-11e6-8ceb-143e7e9978ef.png)

This is the insider version
![vscode insider ext install](https://cloud.githubusercontent.com/assets/8189808/16075685/390453d2-32f0-11e6-828a-14adf4b0e6fb.png)

**Comment by con-ssc** [comment]
It looks pretty much like a certificate issue

**Comment by joaomoreno** [comment]
Since both are accessing the same URL... this is sounding more and more strange.

I apologise for asking once again, but can you just triple check that you don't have any proxy settings in your stable, especially the `http.proxyStrictSSL`? Make sure you check your workspace settings too, in case you have a workspace open.

Any chance you can export those logs, so I can open them in Wireshark and take a closer look?

**Comment by con-ssc** [comment]
I have saved the logs but I don't want to put them up here of course.
both have the same configuration
 //-------- HTTP configuration --------

    // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
    "http.proxy": "",

    // Whether the proxy server certificate should be verified against the list of supplied CAs.
    "http.proxyStrictSSL": true,

**Comment by joaomoreno** [comment]
That seems to be the default configuration. I meant the contents of both `.vscode/settings.json` contained within your workspace and the `settings.json` file that opens on the right when you open the User Settings.

Also, I assume you have no `http_proxy` and `https_proxy` environment variables set?

And another thing, can you install an extension on stable?

**Comment by con-ssc** [comment]
I don't have a .vscode/settingsjson and I don't have any env. variables for proxy, and the user settings do not contain any http entries.

**Comment by joaomoreno** [comment]
How about that last part? Can you install an extension on stable? And what version is your stable installation?

Sorry for all the questions... and thanks for the help by the way!

**Comment by con-ssc** [comment]
No problem, I have a lot extensions in stable. I have currently version 1.2.1 I can install, uninstall, update etc.

**Comment by joaomoreno** [comment]
Stranger and stranger. Insiders is practically equal to stable, with regards to the gallery.

Is some firewall blocking the Insiders build? Can you disable any firewall/antivirus temporarily and see whether that is the case?

**Comment by con-ssc** [comment]
I cannot I'm afraid. I have no access to the antivirus program or firewall if there is one.

**Comment by joaomoreno** [comment]
Alright let's try something else then. Can you download the latest insider release from here, and try there?

https://vscode-update.azurewebsites.net/latest/win32-archive/insider

This URL will download Code as an archive, instead of as a Setup executable. You can just extract and execute it from there directly.

**Comment by con-ssc** [comment]
Downloaded, extracted, same error on ext install

**Comment by joaomoreno** [comment]
How about the stable archive?

https://vscode-update.azurewebsites.net/latest/win32-archive/stable

What happens if you rename the executable from the insiders to `Code.exe` and vice versa to the stable?

**Comment by con-ssc** [comment]
stable works as intended, I can use ext install.
renaming the insider executable didn't change anything.

**Comment by con-ssc** [comment]
Totally forgot about the devTools:

workbench.main.js:115 connect EACCES 191.238.172.191:443: Error: connect EACCES 191.238.172.191:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

workbench.main.js:88 connect EACCES 191.238.172.191:443: Error: connect EACCES 191.238.172.191:443
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

**Comment by joaomoreno** [comment]
OK, so I'll try to compile it all down:

- Error is `connect EACCES`, happening on Windows
- Always happens on the insider executable
- Never happens on the stable one
- Both stable and insider builds do exactly the same when talking to the Marketplace

Googling a bit for ["connect EACCES" windows](https://www.google.ch/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22connect+eacces%22+windows) yields firewall issues:

- http://stackoverflow.com/questions/26192865/npm-install-eacces-error-on-windows
- felixge/node-mysql#858

I suggest once again to disable any firewall on the system. Also check the Windows firewall. Usually, when a new application comes along there is a firewall permission dialog that will let the user block the application from making network requests. It's possible that this dialog was dismissed thus leaving the Insiders release unable to contact the Marketplace.

**Comment by con-ssc** [comment]
Okay now it works after adding it to windows firewall exception. The stable version is not in there but works.

**Comment by joaomoreno** [comment]
cc @egamma

**Comment by con-ssc** [comment]
Hold the phones. It is not the firewall but Kaspersky Security 10. -.-

**Comment by con-ssc** [comment]
Webcontrol, Mail-Anti-Virus and IM-Anti-Virus is blocking Visual Studio Insiders

**Comment by joaomoreno** [comment]
Good to know we have a culprit.

**Comment by con-ssc** [comment]
Also, it is an invisible one, no entries in any reports of Kasperski nor in the messages telling you it blocked something.

**Comment by con-ssc** [comment]
I can narrow it further down. Kaspersky blocks https traffic for apps that it doesn't know. It doesn't report that nor gives feedback to the user, it just cuts off the connection. If you disable the supervision on port :443 the extension connection works.
