### ISSUE TITLE
[json] "Fetch Online Package Info" feature doesn't work when npm is not present

### ISSUE THREAD

**Issue by someden** [microsoft/vscode#77066]
Issue Type: <b>Bug</b>

There was some popup with information about package when hover on it in package.json file.
With 1.36 and 1.36.1 there is nothing on hover.
I suppose "Fetch Online Package Info" feature doesn't work since 1.36.
Found this bug on macOS, but it works fine on Windows.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: macOS 10.14.5

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by someden** [comment]
Maybe it's related with https://github.com/microsoft/vscode/issues/75274 and https://github.com/microsoft/vscode/commit/9bc4699da43ec929c41a0442797ba48d924d1a2b

**Comment by aeschli** [comment]
The info hover now uses `npm view`. Do you have `npm` installed?

**Comment by someden** [comment]
No, because I use docker containers

**Comment by someden** [comment]
@aeschli Is it possible to have this feature without installing `npm`?
It looks like a huge overhead to install `npm` just for a small popup inside vscode.

**Comment by martijnrondeel** [comment]
For me its broken since 1.36 too, but I do have npm and yarn installed and I'm using Ubuntu 18.04.2.

**Comment by christoph-fricke** [comment]
Same for Pop!_OS 19.04 (Ubuntu based). I have npm 6.10.0 installed as snap package.
Hovering a packages only displays "Loading..." but it never stops loading.

**Comment by cyraid** [comment]
Yup, I'm using Linux and I can't see packages like I did while I was in Windows.

**Comment by aeschli** [comment]
Now falling back to npms.io when npm is not present.

**Comment by cyraid** [comment]
Npm is present though, just through nvm on the path.
