### ISSUE TITLE
VS Code installed through snap has issues with some characters

### ISSUE THREAD

**Issue by tplive** [microsoft/vscode#77071]
- VSCode Version: 1.36 installed with Snap
- OS Version: Ubuntu 

Steps to Reproduce:

1. Install VS Code using Snap on Ubuntu
2. Run VS Code
3. Try typing the ~ or ` characters as you usually do.
4. No output.
5. Uninstall from Snap, install using "official" installation method.
6. Now these characters output as they should.

I had the same problem with the Atom editor, also solved by installing throught the supported method and not using Snap.

**Comment by joaomoreno** [comment]
@flexiondotorg Seen this before?

**Comment by joaomoreno** [comment]
@tplive Is this still an issue?
