### ISSUE TITLE
VSCode uninstalled or deleted itself

### ISSUE THREAD

**Issue by Izrab** [microsoft/vscode#77070]
- OS Version: Windows 10 Pro version 1809

Today is 10 of July, 2019, when I opened my laptop, and started to open a JSON file, I realized that VSCode is removed from my PC! I searched "Programs" directory of C drive, I could not file VSCode program files at all, all my VSCode shortcuts were corrupted.
But ٱلْـحَـمْـدُ للهِ praise to be God, after I downloaded VSCode and installed it again, when I launched the new installed VSCode, all my previous settings, configs, plugins, etc. were saved and as is.

I have no idea what what exactly happened, why VSCode deleted itself...

Steps to Reproduce:
I don't know this bug suitable in reproducible category.
 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by autinerd** [comment]
Did you maybe shut down the operating system while an update was being installed? In some occassions, when it happens between uninstalling old version and installing new version, the program is gone.

**Comment by joaomoreno** [comment]
I think @autinerd might be right. Glad to know everything's OK now.
