### ISSUE TITLE
A11y_VSCode_Keyboardshortcuts_Keyboard:While Voice over is on the Keyboard shortcut list is not accessible through keyboard.

### ISSUE THREAD

**Issue by bhagwatshelke1047** [microsoft/vscode#77074]
**Environment Details:**
VSCode Version : 1.36.1 (user setup)
OS Version : MacOS Mojave 10.14.5

**Additional Details:**
MAS Violated : MAS 2.1.1
Screen Reader Versions : Voice over

**Repro Steps:**
1.Open Visual studio code editor.
2.Naviagte to setting icon
3)Select "Keyboard shortcuts options"
4)Start voice over

**Actual:**
While Voice over is on the Keyboard shortcut list is not accessible through keyboard.

This issue is observed in Mac + Voice over

**Expected:**
While Voice over is on the Keyboard shortcut list should be accessible through keyboard.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader users will face difficulty  to access the proper information.

**MAS Reference:
MAS 2.1.1 -** https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachment for Reference:**
[A11y_VSCode_Keyboardshortcuts_Keyboard.pptx](https://github.com/microsoft/vscode/files/3376654/A11y_VSCode_Keyboardshortcuts_Keyboard.pptx)

**Comment by bhagwatshelke1047** [comment]
This issue has been logged in earlier test pass: #52175

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/52154
