### ISSUE TITLE
Font "jumps" when cursor hits the line

### ISSUE THREAD

**Issue by abyss7** [microsoft/vscode#77086]
Issue Type: <b>Bug</b>

For all files and almost always the line's size/font/whatever changes when I hit it with keyboard cursor. That's all. Video sample: https://drive.google.com/open?id=1iy0ovHB4r97ymgXcazDDgaMAbganAqfx

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.1.16-300.fc30.x86_64

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
ccls|ccl|0.1.26
gitlens|eam|9.8.3
graphql-for-vscode|kum|1.14.2
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
vscode-gn|npc|1.0.0
vscode-header-source|ryz|1.3.0
cmake|twx|0.0.17

</details>

**Comment by abyss7** [comment]
Possibly, it matters, but I invoke program as `code . --force-device-scale-factor=2`

**Comment by abyss7** [comment]
Noticed similar behavior in Chrome 75.0.3770.100 - looks like it's overall recent engine problem :(

**Comment by alexandrudima** [comment]
@abyss7 Does this reproduce when disabling all extensions?
