### ISSUE TITLE
The terminal process terminated with exit code: 259

### ISSUE THREAD

**Issue by VoilaL** [microsoft/vscode#77085]
Issue Type: <b>Bug</b>

since vscode has been running, the error 259 is always reported when the terminal being launched

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:47:15.448Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|3.89GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0

</details>

**Comment by Tyriar** [comment]
This indicates the shell process exited with that exit code. Also you're on a very old version of vscode

**Comment by VoilaL** [comment]
Thanks! Reinstalled from the official website, still failed to launch the terminal n reported error code 259😭



发自我的小米手机
在 Daniel Imms <notifications@github.com>，2019年7月10日 下午11:22写道：

This indicates the shell process exited with that exit code. Also you're on a very old version of vscode
