### ISSUE TITLE
modification acceptance

### ISSUE THREAD

**Issue by vashish1** [microsoft/vscode#77081]
Issue Type: <b>Bug</b>

whenever an error is resolved it does not work on it no changes are made and the error   remains though the error is resolved

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edit-csv|jan|0.0.12
Go|ms-|0.11.4
quicktype|qui|12.0.46

</details>

**Comment by gjsjohnmurray** [comment]
@vashish1 I assume you are talking about the Problems pane, right?

Entries here are typically created by extensions, and it is the extension's responsibility to remove the entries it makes when they no longer apply.

For more info, see discussion at #66982 and links from there.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
