### ISSUE TITLE
No color box in css

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7708]
- VSCode Version: insiders latest
- OS Version: OS X

Open any css file and try to set a bacground-color or any color - notice the nice color box is missing.
Another thing I noticed is that colors like 'red', 'blue' are now missing as suggestions.

![screen shot 2016-06-15 at 11 14 45](https://cloud.githubusercontent.com/assets/1926584/16074375/7db9b658-32ea-11e6-842a-28292b8b1644.png)

**Comment by aeschli** [comment]
The css extension was not bundled correctly, fixed now.
