### ISSUE TITLE
Explorer Outline does't work correctly with JSX anymore

### ISSUE THREAD

**Issue by behrouze** [microsoft/vscode#77080]
Issue Type: <b>Bug</b>

with JSX files, VSCode Outline section in Explorer panel, only displays Constants, no more methods names etc. before this version it was working.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-20-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3548)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.3
toggle-excluded-files|eam|1.6.0
prettier-vscode|esb|1.9.0
flow-for-vscode|flo|1.1.4
terminal|for|0.0.10
todo-tree|Gru|0.0.138
vscode-docker|ms-|0.7.0
debugger-for-chrome|msj|4.11.6
stylelint|shi|0.51.0

</details>

**Comment by mjbvz** [comment]
Please share some example code that demonstrates this issue

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
