### ISSUE TITLE
Layout error when renaming long filenames

### ISSUE THREAD

**Issue by mxdh** [microsoft/vscode#77091]
Issue Type: <b>Bug</b>

<img width="241" alt="批注 2019-07-10 190621" src="https://user-images.githubusercontent.com/20399194/60964740-a5004b00-a303-11e9-953b-27858e2581d4.png">

<img width="279" alt="批注 2019-07-10 190744" src="https://user-images.githubusercontent.com/20399194/60964746-aa5d9580-a303-11e9-8fdd-ecfdaf0d258d.png">

When I rename the long filename, the scrollbar is misplaced and the file icon is missing.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
language-gas-x86|bas|0.0.1
doxdocgen|csc|0.5.0
disasexpl|dse|0.0.5
gitlens|eam|9.8.3
vsc-material-theme|Equ|29.2.0
vsc-material-theme-icons|equ|1.0.6
todo-tree|Gru|0.0.138
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.3
vscode-kanban|mkl|1.25.0
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.36.2
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
Go|ms-|0.11.4
java|red|0.46.0
markdown-preview-enhanced|shd|0.4.3
code-spell-checker|str|1.7.17
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/71291
