### ISSUE TITLE
Regression - tasks.json - dependsOn starts only first and last task if presentation group is defined

### ISSUE THREAD

**Issue by shruda** [microsoft/vscode#77098]
DependsOn only executes the first and last task of the list if all tasks have the same presentation group.

Sample tasks.json:
https://github.com/shruda/bugreports/tree/master/vscode/77098/.vscode

VSCode shows 4 Terminals but the second, third and fourth terminal shows the output of the last task.

---
- VSCode Version: 1.36.1
- OS Version:         Version 10.0.17763.557

Steps to Reproduce:

1. Create at least 3 tasks
2. Define the same presentation group for all tasks
3. Create a tasks which dependsOn all existing tasks

Does this issue occur when all extensions are disabled?:
I can't reproduce it because the "group tasks - step 3" will not be listed in the task list if I disable all extensions.

**Comment by alexr00** [comment]
I can repro. Thanks for the clear steps/example.

**Comment by alexr00** [comment]
This issue was exposed by sync changes made to support auto detection of problem matcher file location.
