### ISSUE TITLE
Some suggestions missing in css

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7709]
- VSCode Version: insiders latest
- OS Version: OS X

Steps to Reproduce:

1. Open any css file trigger inteli-sense
2. Notice some suggestions are missing like border-bottom for instance, the picture compares current insiders (light theme) with stable release (dark theme)

![screen shot 2016-06-15 at 11 19 53](https://cloud.githubusercontent.com/assets/1926584/16074524/1efbf81e-32eb-11e6-849c-31c1c2ed8270.png)

![screen shot 2016-06-15 at 11 19 13](https://cloud.githubusercontent.com/assets/1926584/16074492/02b122ce-32eb-11e6-8784-aee1b6df5e1a.png)

**Comment by aeschli** [comment]
The css extension was not bundled correctly. Fixed now.
