### ISSUE TITLE
PowerShell Pop-up Opens in Background

### ISSUE THREAD

**Issue by NickDorak** [microsoft/vscode#77097]
Issue Type: <b>Bug</b>

Windows from PowerShell open in background. For example using "| out-gridview" or "Connect-ExchangeOnlineShell" or "(New-Object System.Windows.Forms.OpenFileDialog).showdialog()". You cannot see the dialog box open because it is hidden by VSCode.  

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:26:27.407Z)
OS version: Windows_NT x64 10.0.18932

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vscode-pull-request-github|Git|0.9.0
reg|ion|1.0.1
powershell|ms-|2019.5.0

</details>

**Comment by Tyriar** [comment]
Closing out of scope, Windows changed some API that made this the default behavior afaik.
