### ISSUE TITLE
No folder: simple file dilaog should show home directory as default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#77094]
1. Open vscode with no folder (purple status bar)
2. Have 	`"files.simpleDialog.enable": true,`
3. New untitled file, save as file
4. Notice how the simple dialog offers me the root path. This is wrong imho, you should offer the home directory, or at least something wich I choose the last time

**Comment by alexr00** [comment]
@aeschli Could we keep the Untitled URI scheme here? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textfile/common/textFileService.ts#L907

All file scheme URIs are absolute. Which means that the remote file picker would have to use a heuristic like checking for "Untitled-" in the path to tell that the user home should be used.

**Comment by aeschli** [comment]
Feel free to change. @bpasero is the expert on the untitled URIs...

**Comment by bpasero** [comment]
@alexr00 the URI only seems to be used in combination of the dialog itself (both native and custom - [here](https://github.com/Microsoft/vscode/blob/0e3c50a251229477516d056a5689b11b663ca009/src/vs/workbench/services/textfile/common/textFileService.ts#L659)), so I think we can preserve the `scheme` if you deal with the untitled case in both worlds.
