### ISSUE TITLE
Reveal Active File in Side Bar command is unreliable

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#77106]
Issue Type: <b>Bug</b>

1. Open a workspace in vscode
2. Collapse everything in the side bar
3. Open a file in the workspace via some means _other_ than clicking in the side bar
4. Issue the Reveal Active File in Side Bar command

What happens for me:

_Sometimes_ it works.  Often however it only opens up some of the folder layers "on the way to" the file, and then stops before actually revealing the file.

For example, if my file is `project1/a/b/c.ts`, it might expand `project1/a`, but not `project1/a/b` so that it can show `c.ts`

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.19.0-5-amd64

This was happening in 1.36.0, and 1.35.x too.  My memory is uncertain if it was happening before that.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.92GB (6.81GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
beautify|Hoo|1.5.0
bash-ide-vscode|mad|1.3.3
terraform|mau|1.3.12
openapi-lint|mer|1.0.3
vscode-docker|ms-|0.7.0
Go|ms-|0.11.4
debugger-for-chrome|msj|4.11.6
vscode-yaml|red|0.4.1
vscode-nginx|sha|0.6.0
html-preview-vscode|tht|0.2.5
reflow-paragraph|Tro|1.3.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@mgabeler-lee-6rs  Thanks for reporting this.
When you get this, if you F1 > developer tools > debug console > Do you see some error?

Can you try to get exact reproducable steps, we are very interested in hunting this bug down?
fyi @joaomoreno

**Comment by mgabeler-lee-6rs** [comment]
As far as exact steps, I haven't found any strong correlation for when it does vs. does not work.  But I can provide one small more behavioral observation: if it fails on the first try, if I hit the command a second time it seems to always work on the retry.

I did notice an error in the console when it just repro'd on me though:
```
  ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at X.getDataNode (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:968:904)
    at X.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:967:201)
    at Generator.next (<anonymous>)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at X.expand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:966:945)
    at e.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:5357:202)
    at Generator.next (<anonymous>)
    at r (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:35:293)
```

**Comment by mgabeler-lee-6rs** [comment]
Some more observations on the failure mode:
1. The error quoted above happens every time it fails and never when it succeeds
2. Thus far it's always getting stuck after opening the "second" layer -- i.e. given my multi-folder workspace, it opens the top level folder, and one folder below that, and then gets stuck
3. It never seems to fail on a given file if it has succeeded before on the current open of the workspace
4. I can get it to reliably fail if I collapse all the side bar folders, close the workspace, open it again, and invoke the reveal command
5. The behavior is unchanged if I launch vscode with all extensions disabled

**Comment by isidorn** [comment]
@mgabeler-lee-6rs thanks for providing more details, assignig to August to investigate then.
fyi @joaomoreno

**Comment by mgabeler-lee-6rs** [comment]
This is probably no surprise to anyone, but confirming this issue is still present unchanged in 1.37.0

**Comment by isidorn** [comment]
@mgabeler-lee-6rs thanks for great repro steps, I could finally reproduce the issue.
The problem was that [here](https://github.com/Microsoft/vscode/blob/19a5bd6123b0e032228a55fa8744f32a5c3b2521/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L525) we were expanding the tree elements in a chain.
And it looks like the tree returns from the `expand` as soon as the element is expanded and its children get fetched. However that moment seems to early to call expand for one of its children. This feels like an issue in the tree thus ping @joaomoreno 

In the meantime as a workaround I have added a `timeout` of `0` between expands that seems to fix the issue.

**Comment by mgabeler-lee-6rs** [comment]
Thanks!  I'll take a look at that build when it comes out and confirm.

**Comment by mgabeler-lee-6rs** [comment]
Installed `code-insiders` version `1.38.0-1566471633` and confirmed the fix is working, thanks!

**Comment by isidorn** [comment]
Ok, adding verified label.
Though this introduced a slight delay / jarring effect in revealing. For this milestone let's go with this approach and next milestone we can see if there is something better than the sily timeout.
fyi @bpasero
