### ISSUE TITLE
Color theme stops working on large files

### ISSUE THREAD

**Issue by klopes14** [microsoft/vscode#77105]
When I open a relatively large file, ~100k lines, with my user-created color-theme, the file is not highlighted.

Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
```json
"editor.maxTokenizationLineLength": 110000,
```

**Comment by klopes14** [comment]
Is there a limit on that setting?

**Comment by klopes14** [comment]
Also my file size is 26MB... does that make a difference?

**Comment by usernamehw** [comment]
> Is there a limit on that setting?

No idea.

> Also my file size is 26MB... does that make a difference?

What difference are we talking about?

**Comment by klopes14** [comment]
Basically raising the limit didn't fix it.... then again I set it to 1mil since I'm looking at some pretty long trace files

**Comment by usernamehw** [comment]
That's actually an unrelated setting. My mistake.

**Comment by usernamehw** [comment]
```json
"editor.largeFileOptimizations": false,
"files.maxMemoryForLargeFilesMB": 8192,
```

**Comment by klopes14** [comment]
That worked! Thanks.
