### ISSUE TITLE
Suggestion: improve TypeScript loading indicators

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#77101]
I understand VS Code has a few mechanisms for indicating that TypeScript is loading, such as the "Loading…" tooltip/hover, and in the status bar (bottom).

![image](https://user-images.githubusercontent.com/921609/60972975-33ce9100-a31f-11e9-9fce-1235fe6d9a21.png)

![image](https://user-images.githubusercontent.com/921609/60972643-92473f80-a31e-11e9-92c8-f0d3f28ed3dc.png)

However, I frequently run into situations where I know TypeScript is loading, but VS Code doesn't tell me this. When this happens, I usually just restart the TS server, because then at least I get some indication of what's going on and when it has finished.

I seem to run into these situations most often when working on a large project and switching between branches, rebasing (i.e. quickly moving between commits), and dealing with merge conflicts.

Is this already a known problem, or do you need more specific steps to reproduce? If you need examples, I can try but it's not easy to share a reduced test case, because it only really happens when you're working on a large TS project.

Would it be possible to improve the loading indicators in VS Code so it's always clear when we're waiting on TypeScript, and we don't have to resort to restarting the TS server all the time?

**Comment by mjbvz** [comment]
Can you provide specific examples where a loading indicator would be helpful. We generally show loading indicators when you try to perform an action but it takes time to return

**Comment by OliverJAsh** [comment]
I'll gather some notes over the next few days and get back to you.

One idea that would help a bit: just showing something in the status bar when TS is loading (like we do when initializing), so I don't have to keep hovering over types to know when it's finished loading.

**Comment by mjbvz** [comment]
Yes, please provide some examples.

I am not in favor of adding something to the status bar without a lot of thought. We've had a lot of non-actionable/as-designed issues reported about the `Initializing JS/TS language features...` project load indicator in the status bar
