### ISSUE TITLE
Invalid highlighting for multiple post parameters in c++ pure virtual method

### ISSUE THREAD

**Issue by tbhartman** [microsoft/vscode#77107]
Issue Type: <b>Bug</b>

Multiple post parameters on c++ methods are not highlighted correctly if the method is pure virtual.  For example, "override" below is not highlighted:

```cpp
class Base
{
  public:
    virtual void method() const = 0;
}
class Derived : public Base
{
  public:
    virtual void method() const override = 0;
}
```

Expected:
![image](https://user-images.githubusercontent.com/896331/60981584-9fefcb80-a304-11e9-8281-e54c0f1f5e3f.png)

Actual:
![image](https://user-images.githubusercontent.com/896331/60981547-8d759200-a304-11e9-8ca2-770e3b21f00c.png)

VS Code version: Code - Insiders 1.37.0-insider (360e4e4dfa989135f28edc0d6f7e42df33cddf87, 2019-07-10T05:26:12.322Z)
OS version: Windows_NT x64 10.0.16299

Extensions: none

**Comment by Colengms** [comment]
@Jeff-hykin ;)

**Comment by tbhartman** [comment]
@jeff-hykin should I open an issue and/or pull request in jeff-hykin/cpp-textmate-grammar?

**Comment by matter123** [comment]
@tbhartman You can open one, or I can when I am able to, in about 9 hours.

**Comment by tbhartman** [comment]
Created jeff-hykin/cpp-textmate-grammar#301

**Comment by alexr00** [comment]
Closing in favor of jeff-hykin/cpp-textmate-grammar#301. Thanks!
