### ISSUE TITLE
Actionbar registry should only ask contributor for action item where action came from

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7710]
It currently just asks every contributor: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actionBarRegistry.ts#L167

**Comment by bpasero** [comment]
@jrieken I am not sure how to best fix this due to the way an action bar handles action items: You set actions into an action bar and then we have action item providers that you can pass in that get called whenever the action is displayed (`getActionItem(action: IAction): IActionItem`). At that point I have no clue from which contributor the action item was coming from. It is totally disconnected.

However, quickly checking our uses of action contributors, I do not find a client that actually leverages the `getActionItem` API. So I am also easy to take it out from the contribution story unless you actually now introduce a use case for this for the extensions?

**Comment by jrieken** [comment]
Yes, I need the `getActionItem` API to get the icon in. With that I can just use the icon path(s) and don't have to generate and manage css styles for each of them (see https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/platform/actions/workbench/actionBarContributions.ts#L165). 

To solve your problem: How about wrapping action into another action that keeps a reference to the provider? Or having somewhere an identify mapping of Action -> Provider?

**Comment by jrieken** [comment]
Oh, and this became less important for me since I now use a special action of which I can switch: https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/platform/actions/workbench/actionBarContributions.ts#L85

**Comment by bpasero** [comment]
@jrieken yes I thought about doing the wrapper thing. 

Given your https://github.com/Microsoft/vscode/issues/7710#issuecomment-226402768 you will not do unnecessary work for all the other actions that float around.

**Comment by bpasero** [comment]
I think this is no longer needed.
