### ISSUE TITLE
Git Fetch doesn't present authentication prompt

### ISSUE THREAD

**Issue by satori-stan** [microsoft/vscode#77109]
Issue Type: <b>Bug</b>

1. Open a folder with a Git repo that doesn't have authentication stored
2. Perform a Git Fetch
3. HttpRequestException occurs (Authentication failed)
4. Prompt for credentials doesn't appear

Other remote operations (Pull, Push, etc.) display the credentials prompt if authentication fails.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
Yeah we purposefully disable prompts in fetch, simply because fetch happens often in the background. Would you like to constantly get prompted to authenticate as fetch runs in the background? A better solution would be for you to automate that authentication.
