### ISSUE TITLE
Should debug integrated terminal support pass the env directly to createTerminal?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#77111]
Looking at this:

https://github.com/microsoft/vscode/blob/b51019b5508096e2dbd7ae3c7ac84a3a0c22816c/src/vs/workbench/contrib/debug/node/terminals.ts#L113-L122

It looks like it would be a lot simpler to pass in `env` to `createTerminal` instead of constructing a per-shell command to set/unset them:

https://github.com/microsoft/vscode/blob/4d02d83c4183abeba42061135b0cd6a976dabab3/src/vs/vscode.d.ts#L7106-L7109

**Comment by weinand** [comment]
Debug tries to reuse a terminal if it is "free", i.e. if there are no child processes running in it.
So the terminal is created for the first "runInTerminal" and then reused (if possible).
Consequently passing env to `createTerminal` only works for the first "runInTerminal". Subsequent "runInTerminal" requests still require the current approach.

**Comment by weinand** [comment]
@Tyriar for addressing this issue I'm trying to use the `terminalService.createTerminalFromOptions` API. When filling up the "options" arguments, I can use "getDefaultShell". But why is the corresponding "_getDefaultShellArgs" private?

```ts
const options: vscode.TerminalOptions = {
	shellPath: this._terminalService.getDefaultShell(configProvider),
	shellArgs: this._terminalService._getDefaultShellArgs(configProvider),
	cwd: args.cwd,
	name: args.title || nls.localize('debug.terminal.title', "debuggee"),
	env: args.env
};
delete args.cwd;
delete args.env;
this._integratedTerminalInstance = this._terminalService.createTerminalFromOptions(options);
```

**Comment by Tyriar** [comment]
@weinand it just didn't have any consumers outside yet, whereas the default shell is exposed in the API via `env.shell`, feel free to change it to public
