### ISSUE TITLE
[Feature Request] Tabs: open new tab at the end

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#7711]
I don't know if this is planned, but when enabling tabs on Insider builds, when opening a new file, the new tab is opened next to the current active one.

How about a setting to allow the tab to always be opened at the last position ?

**Comment by sandy081** [comment]
@warpdesign  We already support this with a setting. Please refer to this item for current settings for tabs.

https://github.com/Microsoft/vscode/issues/7643
