### ISSUE TITLE
Find references: show number of children similar to search results

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#77112]
Similar to how search results show a number for their children:

![image](https://user-images.githubusercontent.com/900690/60983812-ec55fe00-a33a-11e9-9181-0d2f8fee3006.png)

Would be cool to have the same for references view:

![image](https://user-images.githubusercontent.com/900690/60983831-f7109300-a33a-11e9-9cd5-5a32c4723a5d.png)

Would probably need some API on the custom view layer.

//cc @sandy081

**Comment by jrieken** [comment]
I like but it might look noisy with the those git-decoration on the right

**Comment by bpasero** [comment]
Oh wow, I never realized that search results actually do not have decorations 🙉
