### ISSUE TITLE
Is is able to add a shortcut to toggle the items in the side bar? 

### ISSUE THREAD

**Issue by mejliu** [microsoft/vscode#77118]
Is it able to add a keybinding (or shortcut) to toggle the items of the activity bar in the side bar? Thanks. This is especially useful when the side bar is shown, but the activity bar is hidden and there are many item in the activity bar.

**Comment by charliedua** [comment]
# Understanding
From what i can understand from this is, you're looking for a **feature request** where you want a button which toggles the visibility of icons in activity bar. 
# Investigation
When the side bar is shown, the visibily of activity bar is never compromised hence both the side bar and activity bar are shown.
# Solution
This Feature however is **already implemented** and is availabe by
* Right clicking the activity bar and selecting hide Activity bar
`OR`
* By opening the Command pallet by pressing `Ctrl` + `Shift` + `P` and wrting `>activity bar` so it shows the toggle option.

# Conclusion
This Feature request is invalid and hence this issue should be closed if no further action is needed @mejliu Confirm.

**Comment by mejliu** [comment]
Hi @charliedua , thanks for your reply. Actually, when the side bar is shown, the visibility of the activity bar can be compromised. 
![image](https://user-images.githubusercontent.com/4575879/61012022-ccc6d180-a34a-11e9-8b2d-793b03a68bc0.png)

Also, when the activity bar is shown, the visibility of the side bar can also be compromised. 
![image](https://user-images.githubusercontent.com/4575879/61012055-e831dc80-a34a-11e9-8cf8-b372a1172952.png)

To save space, I usually hide the activity bar and only make the side bar visible. This is shown in the first picture. 

However, sometimes I need a quick switch between `Explorer` and `Debug` without showing the side bar. Therefore, it would be nice to have a keybinding to toggle the `Explorer`, `Debug`, `Source Control`, `Extensions` or any new added tabs in the side bar without first click `activity bar` and then choose different contents for `side bar`.

**Comment by charliedua** [comment]
I see what the problem is

You can configure a keyboard shortcut to hide the activity bar and side bar in the keyboard shortcuts menu

![Screenshot from 2019-07-11 11-36-35](https://user-images.githubusercontent.com/33629087/61015764-5967a300-a3d0-11e9-8a3a-567fd8094af3.png)

**Comment by mejliu** [comment]
@charliedua Actually, I want to toggle the items (or tabs) in the activity bar. :) This may be more clear. Sorry for the confusing.

**Comment by charliedua** [comment]
@mejliu so oyu want to put the activity bar inside the side bar so it saves you some space? 
as of now visual studio code alone can not handle this kind of the senarios. however you might find some extensions which does it for you.
