### ISSUE TITLE
Detect updates in dependencies

### ISSUE THREAD

**Issue by michaeljota** [microsoft/vscode#77115]
## Description

VS Code should be able to detect if there is a diff in a dependency declaration file and offer to install the new version. If the user accept, VS Code should temporary close any extension that needs information of the installed dependencies, remove the dependencies folder (if any) and install the updated dependency list. Then, it would reload all the closed extension. 

## Why

Some extensions depends on information inside dependencies folder (ex: `node_modules` for `typescript` types). Removing that folder while any extension it's using some of the dependencies would result in an error, either from the remove command, or from the extension itself. 

Second, it would improve productivity as you will reinstall the dependencies with one click, removing old dependencies and installing a fresh new copy.

## Example
Original `package.json`
```json
{
  "name": "example-app",
  "devDependencies": {
    "@types/node": "10.12.10",
    "typescript": "~3.4.5"
  }
}
```
Updated `package.json`
```json
{
  "name": "example-app",
  "devDependencies": {
    "@types/node": "~12.6.2",
    "typescript": "~3.5.3"
  }
}
```
Steps VS Code would made:
- Detect the diff between the original and the updated.
- Ask the user for update the package.
  - If the user refuse, don't do anything.
- Stop `typescript` extension, if it is using `@types/node` package. 
- Remove `node_modules`.
- Run `npm install`
- Start `typescript` extension, if it was stopped.

**Comment by sandy081** [comment]
This is not about `extension dependencies` and about `node dependencies`

**Comment by michaeljota** [comment]
It's not about `node dependencies`, but `project dependencies`. Not all projects use `npm` as package manager. I just put an example of how it would be with `package.json`.

**Comment by aeschli** [comment]
It's a good idea but I think this shouldn't be part of the VSCode editor, but your build tooling. Like 'tsc --watch' that watches the typescipt file and rebuilds when necessary, you want a package-json watch that runs `npm install` when it detects a change.

I believe the typescript language server already watches the @types folders for added d.ts.

**Comment by michaeljota** [comment]
I think you are focusing too much on the example. I write that because that's the most I use, but it's not the only package manager we have.

You could say it could be done with a extension, but I actually would like to disable all the extensions, or at least the ones that are keeping files from the package folder open and the ones that expect something inside the package folder. I don't think this can be properly done.

For the ts ls, the problem it's actually that. It keep watching the `@types` folder, so when I want to remove the `node_modules` folder, I can't until I close the ts ls. Most of the time, I end up closing VS Code itself, as sometimes other extensions would throw as well.
