### ISSUE TITLE
Terminal starts with command prompt and curser hidden.

### ISSUE THREAD

**Issue by rjones020** [microsoft/vscode#77113]
Issue Type: <b>Bug</b>

The command prompt does not show until user hits enter for the first time.  If you start typing i.e. "npm run build"  the command appears to be just floating in the middle of the terminal space.
Steps to reproduce:
1.  Type CRTL+`  or click the terminal tab and click new terminal.
2.  Notice the command prompt is hidden.
3.  Start typing anything.
4.  Observe the typed text shows where the command prompt should be. 
5.  Press enter.
6.  Observe the command prompt is visible as it should be.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
