### ISSUE TITLE
EACCES on temporary socket

### ISSUE THREAD

**Issue by lnicola** [Microsoft/vscode#7712]
- VSCode Version: 1.2.1 Linux x64
- OS Version: CentOS 7

Steps to Reproduce:

1. Run code

The following error appears. Notice the newline in the path.

```
Error: listen EACCES /tmp/user
/Code-333ea0.sock
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at /home/user/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:6:16982
    at new __dirname.undefined.t.Class.derive._oncancel (/home/user/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:5:11845)
    at Object.s [as serve] (/home/user/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:6:16912)
    at t (/home/user/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:10:20560)
    at x (/home/user/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:10:21566)
```
`strace` extract:
```
execve("/bin/mkdir", ["mkdir", "-p", "-m", "700", "/tmp/user"], [/* 57 vars */]) = 0
bind(58, {sa_family=AF_LOCAL, sun_path="/tmp/user\n/Code-333ea0.sock"}, 110) = -1 ENOENT (No such file or directory)
```

This seems to have regressed in `1.1`, since `1.0.0` is working for me.

This doesn't occur on my Arch machine.

**Comment by lnicola** [comment]
Update: This only seems to happen from `zsh`.

**Comment by joaomoreno** [comment]
@Tyriar any clue?

**Comment by lnicola** [comment]
Regarding the `/usr/bin/code` symlink, it seems to get created somehow. `rpm -qf /usr/bin/code` doesn't recognize it as being part of the package.

**Comment by Tyriar** [comment]
@lnicola https://github.com/Microsoft/vscode/pull/7350 should fix the /usr/bin/code issue.

@joaomoreno nothing comes to mind really... The environments are the only things that could potentially change between shells aren't they?

**Comment by lnicola** [comment]
@Tyriar I updated the environment variables to match (at least as reported by `env`), but it didn't have any effect. It's strange..

**Comment by joaomoreno** [comment]
So, in that shell what do you get with `echo $TMPDIR`?

**Comment by lnicola** [comment]
@joaomoreno it's not set

**Comment by joaomoreno** [comment]
How about `node -p 'require("os").tmpdir()'`?

**Comment by lnicola** [comment]
@joaomoreno I don't have `node` installed. Can somehow I test that with the `code` executable or do I have to install `node`?

**Comment by joaomoreno** [comment]
Sure, maybe this will work: `ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 /usr/bin/code -p 'require("os").tmpdir()'`.

**Comment by lnicola** [comment]
With `/usr/share/code/code`, both `tmpdir()` and `tmpDir()` return `/tmp`. As I mentioned above, `/usr/bin/code` works fine.

**Comment by joaomoreno** [comment]
OK, so the real problem seems to be the original lack of `/usr/bin/code`, leaving it to @Tyriar

**Comment by lnicola** [comment]
Not really, but perhaps it's my fault. I downloaded the VSCode ZIP archive, extracted it, and it failed to start. Only yesterday I noticed that running `bin/code` works. Is this the expected behavior?

**Comment by Tyriar** [comment]
@lnicola can you try the Insiders build and see if the problem still exists? https://code.visualstudio.com/insiders

**Comment by lnicola** [comment]
@Tyriar Thanks, Insiders version works. Do you happen to know the commit that fixed it?

I'll close this soon anyway.

**Comment by lnicola** [comment]
Works for me in newer Insiders builds, closing.

**Comment by Tyriar** [comment]
@lnicola https://github.com/Microsoft/vscode/pull/7350 is the PR that fixed the bin command.

**Comment by lnicola** [comment]
@Tyriar no, I meant the extra newline in the temporary path.

**Comment by Tyriar** [comment]
No idea on that one
