### ISSUE TITLE
Custom views: Expand/Collapse state is not saved after refresh

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode#77129]
Issue Type: <b>Bug</b>

Seems like there's been some new tree work? This issue repros on most of our Azure extensions and _only_ on insiders (works fine on VS Code v1.36.1). I'll use the [storage](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage) extension as an example.

Repro steps:
1. Expand several items down the tree
![Screen Shot 2019-07-10 at 12 05 22 PM](https://user-images.githubusercontent.com/11282622/60997385-8bfb9800-a30b-11e9-9953-625d8343bf44.png)
1. Right click on subscription ("erijiz test") and refresh

Expected:
Tree looks basically the same with all nodes still expanded

Actual:
Everything under subscription is collapsed
![Screen Shot 2019-07-10 at 12 05 31 PM](https://user-images.githubusercontent.com/11282622/60997428-a46bb280-a30b-11e9-9638-63f6940ed0cf.png)

VS Code version: Code - Insiders 1.37.0-insider (360e4e4dfa989135f28edc0d6f7e42df33cddf87, 2019-07-10T05:29:59.244Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
azurerm-vscode-tools|ms-|0.6.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
azure-account|ms-|0.8.4
vscode-typescript-tslint-plugin|ms-|1.2.1
sort-lines|Tyr|1.8.0

</details>

**Comment by alexr00** [comment]
This should already be fixed if you update to the latest insiders!

**Comment by EricJizbaMSFT** [comment]
No longer repros - thanks!
