### ISSUE TITLE
CPU usage of VS code helper is completely out of control

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#77125]
Issue Type: <b>Performance Issue</b>

This happens all the time, a common cause for me is re-generating numerous typescript files.  My CPU just gets pegged at 100% and my entire system becomes inoperable.  Running the 'Reload Window' command in VS code solves the issue immediately, which leads me to believe that the TS helper has an issue with changing code, not with the actual types.

TS specifically isn't the main problem though, no VSCode extension should be able to completely lock my machine, and VSCode provides no way to really inspect what's going on other than the trial and error of disabling extensions one at at time, then either living with the extension blowing up from time to time or completely disabling the extension.

See screenshot, the drop in CPU was simply me running 'Reload Window'

<img width="558" alt="Screen Shot 2019-07-10 at 11 28 44 AM" src="https://user-images.githubusercontent.com/320562/60995019-86e81a00-a306-11e9-90a5-b5fd23189394.png">

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
