### ISSUE TITLE
VSCode clearing files

### ISSUE THREAD

**Issue by dudeking** [microsoft/vscode#77124]
- VSCode Version: 1.36.1
- OS Version: Windows 10 64-bit

Hello. I have been using VSCode for some time now, and sometimes whenever I finish working with it and properly close the program, all the files I am working on are erased completely. 
For example: I am working on a file foo.bar and I see that it is, say, 10kb in size. When I close VSCode and click "Save", I see suddenly that the file is 0kb, and when I open it, its completely empty.

I don't know how to reproduce it, at all. It happens randomly and unpredictably

Extensions:

Extension | Author (truncated) | Version
-- | -- | --
code-gnu-global | aus | 0.2.2
npm-intellisense | chr | 1.3.0
vscode-markdownlint | Dav | 0.28.0
vscode-eslint | dba | 1.9.0
vscode-npm-script | eg2 | 0.3.8
auto-close-tag | for | 0.5.6
auto-rename-tag | for | 0.1.0
vscode-csharp-snippets | jor | 0.3.1
vscode-github | Kni | 0.30.2
csharpfixformat | Leo | 0.0.81
cpptools | ms- | 0.24.0
csharp | ms- | 1.20.0
powershell | ms- | 2019.5.0
bash-debug | rog | 0.3.5
cc65 | Sha | 0.0.2

Any help/suggestions?

**Comment by bpasero** [comment]
> I don't know how to reproduce it, at all.

So it only happened once?

**Comment by dudeking** [comment]
No, it happens randomly

**Comment by bpasero** [comment]
@dudeking are you connected to some remote file system or is this all local?

**Comment by dudeking** [comment]
Everything is done locally on my computer, the files I'm working on are on my USB hard drive. That could be the cause now that I'm thinking

**Comment by bpasero** [comment]
Yeah, that sounds like it could be a cause. Any chance you could try to reproduce on your local disk?

**Comment by dudeking** [comment]
I has happened several times on my local disk too

**Comment by bpasero** [comment]
@dudeking are you able today to reproduce this following these steps (on the local disk):
* open a folder in one window
* open a single file and type into it
* close the window
* confirm to save

=> is the file empty?

**Comment by dudeking** [comment]
It is not empty about 90% of the time, as I have tested before both on local and external, so that might not be the issue

**Comment by bpasero** [comment]
@dudeking so if you try these steps now 10 times, you see it happening once?

**Comment by dudeking** [comment]
On average, yes

**Comment by bpasero** [comment]
@dudeking I just tried to reproduce that, but cannot.

Do you have `files.hotExit` turned off? Because by default you should not get asked to save when you close the last window

**Comment by dudeking** [comment]
I dug deeper into my system, and realized both of my drives are corrupted in a spot, where if something is saved its erased. Its a problem on my side.
