### ISSUE TITLE
ESLint and Intellisense stops working

### ISSUE THREAD

**Issue by Samuel-Montoya** [microsoft/vscode#77126]
Issue Type: <b>Bug</b>

After a while of developing, the Intellisense stops working. It doesn't show any auto-completes, any auto-fills, any sort of tip or help after a while of usage. Not sure what could be causing this.. But when I hover over something, it just says "Loading...". But every time I restart, it works again.

Also, the formatter does nothing as well. Not too sure what's happening and why, but it occurs pretty often.

Steps:
Booting up VSCode
Coding for a while, consistently formatting and using VSCode Features
Eventually it stops working

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.0
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
gc-excelviewer|Gra|2.1.32
dotenv|mik|1.0.1
python|ms-|2019.6.24221
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.0
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
