### ISSUE TITLE
Migrate away from HockeyApp by November 16, 2019

### ISSUE THREAD

**Issue by SamB** [microsoft/vscode#77128]
[HockeyApp will be shut down](https://www.hockeyapp.net/blog/2018/11/16/thanks-hockeyapp-app-center-will-take-it-from-here.html) on (after?) November 16, 2019, so it would probably be a good idea to migrate crash reporting to a different service soon.

Theoretically, something called "App Center" is supposed to be taking over HockeyApp's responsibilities, but since the [Windows Transition Plan](https://github.com/microsoft/appcenter/blob/specs/specs/2019-04/Windows-Plan.md) indicates that they neither know of Win32 support in HockeyApp nor have any immediate plans to add any to App Center, I doubt if that's actually the best option here.

Starting from electron's [crashReporter](https://electronjs.org/docs/api/crash-reporter>) docs, and cross-referencing with [Crashpad overview design](https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md) (since Electron uses crashpad for Mac), it looks like breakpad protocol is used in all cases.

You could self-host:

* [mini-breakpad-server](https://github.com/electron/mini-breakpad-server)
* [Sentry](https://docs.sentry.io/server/) 
* [socorro](https://github.com/mozilla/socorro) if you're feeling adventurous

Or use a 3rd party hosted solution:

* [Backtrace](https://backtrace.io/electron/)
* [Sentry](https://docs.sentry.io/clients/electron)
* [BugSplat](https://www.bugsplat.com/docs/platforms/electron)

(I may have copied and pasted most of these bullets from the markdown source of https://electronjs.org/docs/api/crash-reporter.)

I guess you'd also want to rename the `hockeyApp` property in [`poduct.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/product/node/product.ts)/`product.json` to something more generic.

**Comment by deepak1556** [comment]
Appcenter is used since v1.43
