### ISSUE TITLE
html comments block emmet

### ISSUE THREAD

**Issue by DiegoDiazGato** [microsoft/vscode#77139]
Issue Type: <b>Bug</b>

When i write a html comment VSC can´t write the hint code. Thanks

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vscode-sass-format|sas|1.1.6
vscode-icons|vsc|8.8.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
@DiegoDiazGato Can you please add a small code sample?
