### ISSUE TITLE
Git: Workspace with a few submodules shows all submodules in "SOURCE CONTROL PROVIDERS"

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#77130]
Version: 1.36.0
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:20:56.241Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic

# Issue

I have repository with many submodules. When I like to work on a small subset of those submodules, I open them in a new window. But the "SOURCE CONTROL PROVIDERS" shows me all submodules, unnecessary bloating the information, which is not interesting.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
You can disable this behaviour with the setting `git.detectSubmodules`.

**Comment by anishmittal2020** [comment]
@joaomoreno What you proposed, completely hides the detection of submodules, which is not what I intended. For example if Repository `Super` has 40 Submodules (such as `Super/A`, `Super/B`, and so on), and if we open vscode by `$ code Super` then it should detect all the submodules. 

But If I want to work on only a few Submodule such as `Super/D` and `Super/E`, and I open New window with `$ code Super/D Super/E` then I was hoping that in the `SOURCE CONTROL PROVIDERS`, it could only show me git status of `Super/D` and  `Super/E`, and not of other submodules.

**Comment by joaomoreno** [comment]
I actually can't repro that. I have created a sample repo with two submodules. When I open one of them as a folder in code, neither the top level repo nor the other submodule get open in Code. Can you reproduce in a smaller sample?
