### ISSUE TITLE
CJK font

### ISSUE THREAD

**Issue by iscraft** [Microsoft/vscode#7713]
like this
![cjk_font](https://cloud.githubusercontent.com/assets/5448825/16076355/7c5fe116-3325-11e6-9ef9-dce5a8efb6c8.gif)

**Comment by be5invis** [comment]
Did you know the main font can be a list?
```
"editor.fontFamily": "Iosevka Slab, Inziu Iosevka Slab SC"
```

**Comment by iscraft** [comment]
@be5invis yes i know,but font size is only one.

**Comment by be5invis** [comment]
@iscraft CSS does not support size adjustments in font linking. Your feature cannot be implemented.

**Comment by alexandrudima** [comment]
I am sorry, but @be5invis is correct, we cannot implement this as the font fallback is handled by the browser and AFAIK there is no way to associate a different font size with each fallback option. Maybe a feature request against w3c?

**Comment by iscraft** [comment]
try the [everedit](http://everedit.net)
