### ISSUE TITLE
"Feature Request": syntax specific feature for settings & keybindings.

### ISSUE THREAD

**Issue by mejliu** [microsoft/vscode#77144]
Is it able to add syntax specific features for settings and keybindings.

For example,
For settings,  If the source file is a cpp file, we use the settings like:
```
{
"spell check": False,
"source": cpp,
}
```
If the source file is a python file, we use the settings like:
```
{
"spell check": True,
"source": python,
}
```

Similarly, for keybindings. If the source file is a cpp file, we set the keybindings like:
```
{
"key": f1,
"command": "open a help file"
"source": "cpp"  
}
```
If the source file is a cpp file, we set the keybindings like:
```
{
"key": f1,
"command": "open other stuff"
"source": "python"  
}
```

This syntax specific feature would be very extremely useful.

**Comment by sandy081** [comment]
We support language specific settings already 

https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

But why do you need language specific keybindings? 

@bpasero @alexandrudima Is not it possible if there is a context for active file language?

**Comment by mejliu** [comment]
@sandy081 In some cases, it would be nice to use the same key for different commands when opening different files. For example, F5 can be used for debugging for some files and for running for other files. The link you mentioned above is for settings. Is there a way to do this for commands? Thanks.

**Comment by sandy081** [comment]
For commands/keybindings we might have to introduce or use `context` for languages or other solution

**Comment by bpasero** [comment]
@sandy081 there is [`ResourceContextKey`](https://github.com/Microsoft/vscode/blob/5106b556bdb44fc81d74ef31d6135e9ec0889c8c/src/vs/workbench/common/resources.ts#L19) with a bunch of context values for the active file.

**Comment by alexandrudima** [comment]
@mejliu It is possible to bind a keybinding only in certain languages using `when` conditions, e.g.:

```
{ "key": "f11", "command": "-workbench.action.toggleFullScreen", "when": "editorLangId == json" },
```
