### ISSUE TITLE
Regression: Weird hang in suites when using webpack and assert

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#77146]
Issue Type: <b>Bug</b>

This did not repro in 1.35.x.  It started appearing in our nightly suites on 7/4 (see https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7470), which I believe is the day that vscode 1.36.0 came out.

Repro (using prebuilt/modified code that makes it easier to debug):
1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) git checkout saw/test-bug
4) npm i
NOTE: Do *not* build, the branch contains already-built code
5) npm test
!) Expected: passing test
Actual:  Suite hangs in the "bug" testcase in test\bug.test.ts

To debug:
6) Open vscode on the folder
7) Set configuration to "Launch Tests (webpack)"
8) Open test\bug.test.ts file
9) set breakpoint here on the Json.parse(null) line:
```ts
        test("with null text", () => {
            console.log("Test: bug: 1");
            try {
                console.log("Test: bug: 2");
                Json.parse(null); << BREAKPOINT HERE
```
10) F5
11) When you hit the breakpoint, step into the code (F11)
12) This will open up the dist/extension.bundle.js file, which is the webpacked, minimized sources
(see /*asdf assertion call is here:*/ n(!1) - the "n" is an assert.ok() call)
13) Press F11 again to step into assert.ok
14) F5
!) The code calls getErrorMessage() to determine the message for the failed assertion
Then it gets stuck in an infinite loop here:
```js
function findColumn(fd, column, code) {
  if (code.length > column + 100) {
    try {
      return parseCode(code, column);
    } catch {
      // End recursion in case no code could be parsed. The expression should
      // have been found after 2500 characters, so stop trying.
      if (code.length - column > 2500) {
        // eslint-disable-next-line no-throw-literal
        throw null;
      }
    }
  }
…
  return findColumn(fd, column, code);  <<< INFINITE LOOP
```

It has something to do with the line length of the minimized file. If I add line breaks, it no longer repros.  I can't see the source location for assert.js in the debugger. That, plus the fact that this started happening when vscode 1.36.0 came out, my theory is that vscode picked up a buggy assert.js file and is force loading it instead of the local version.  Thoughts?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.7.1
vscode-browser-preview|auc|0.5.9
azure-arm-template-helper|ed-|0.0.17
tslint|eg2|1.0.44
rest-client|hum|0.21.3
vscode-antlr4|mik|2.1.1
azure-pipelines|ms-|1.152.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
extension-manifest-editor|ms-|0.1.5
mssql|ms-|1.6.0
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.1
azurerm-vscode-tools|msa|0.6.0
arm-snippets|sam|1.4.14
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
html-preview-vscode|tht|0.2.5
arm-params-generator|wil|0.7.0

</details>

**Comment by StephenWeatherford** [comment]
The version of assert.js which is picked up at runtime starts like this:

(function (exports, require, module, process, global, Buffer) { return function (exports, require, module, process) { // Originally from narwhal.js (http://narwhaljs.org)
// Copyright (c) 2009 Thomas Robinson <280north.com>

Doesn't appear to be the Node.js version.

**Comment by roblourens** [comment]
Thanks for the steps, I tried it and it takes an extremely long time but does not hang forever

```
Test: bug: 4
BUG.test.ts:22
      ✓ with null text (387527ms)
```

I see that it is in that method but seems like it has to read the entire line into memory which just takes awhile. That looks like the real assert.js, https://github.com/nodejs/node/blob/57c70835af07485948bb3690b78adbf52d2205cd/lib/assert.js.

This might be a regression in Node's assert, you could file an issue on them. We just went up to Node 10.x in 1.36.
