### ISSUE TITLE
Feat: Show the comments for items when inspecting them.

### ISSUE THREAD

**Issue by SephReed** [microsoft/vscode#77157]
It would be really nice if the comments that lead up to a symbol were shown when inspecting its origin.

It does happen in ts if you format your comments like this:
```
/**
 * This is some comment about fn
 */
function fn() {}
```

But sometimes you're not trying to write js-docs, and you just want to put a one-line comment above a function.  eg:

```
// This is some comment about fn
function fn() {}
```

It would probably make sense to put this functionality behind a flag, so people who litter their code with old commented out code would not get it displayed as relevant information.  But, for the most part, if there's a comment before something, it's for informative reasons.

**Comment by mjbvz** [comment]
You can put doc comments on a single line:

```js
/** This is some comment about fn */
function fn() { }
```

No in favor of treating `//` comments as function documentation comments since that would effect a lot of existing code. Using`/**` makes it clear when you are commenting code vs adding a documentation comment

**Comment by SephReed** [comment]
So put it behind a flag?  Maybe people use different commenting styles?

**Comment by SephReed** [comment]
If I were you, what I would have said is this:

> Hmmm... maybe.  That would definitely cause issues with code that has commented out sections, so I think having it as a default disabled setting would be the only way to go.  I'll pass it by so and so.

Then, if I was feeling like being totally unhelpful, I could just not ever pass it by anyone, and come back later with "Sorry, unless a bunch of people request this, it's not anywhere near a priority".

I'm telling you this, because I really want you to not treat other people the way you just treated me.  Saying "no because I wouldn't use it" is basically shaming a user for doing things different than whatever you believe is normal.  Making no attempt to work with the idea for even a moment implies a relationship where I'm unworthy of your time.  It feels shitty, so (unless that's your intention) please take some time to reflect on the power which has gone to your head.

**Comment by mjbvz** [comment]
Sorry if my response came across the wrong way

However understand that we have limited resources and cannot support every feature request that comes in, even if the behavior is gated behind a flag. This isn't about personal preference: your proposal goes against widely used conventions for js code and would cause unexpected behavior in a whole lot of existing code. As we will not implement this request now or at any point in the near future, I closed it as out of scope

**Comment by SephReed** [comment]
>  "would cause unexpected behavior in a whole lot of existing code"

0% true.  You're plenty aware that only users who enabled the setting would see any difference.

> "your proposal goes against widely used conventions for js code"

There it is again.  Shaming a user for being unpopular.  What's worse, "comments before functions" is far more ubiquitous than "specific star comments before functions," dating back to the very beginning of comments, in all languages.  So not only are you using popularity as a metric of correctness, you're also incorrect about which of the two is more popular.

You should not be a gate keeper.  Your logic is not sound enough, and your tact not mature.  You have very well just passed up on a feature that would serve every single user who's ever used anything except "conventional" documentation.

In any case, I've made a script that converts from one to the other.  It's not a huge deal, just kind of thought it was lame that holding cmd while hovering over a function shows me everything but the comments above its source code.  Thanks for reminding me why I hate dealing with mega corps.

> "conventional"
