### ISSUE TITLE
VS Code uninstalled itself

### ISSUE THREAD

**Issue by DeadCatLady** [microsoft/vscode#77156]
Issue Type: <b>Bug</b>

I'm not too sure what happened. I worked on VS code this morning, and then when I booted my laptop just now, it was gone. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.0
php-intellisense|fel|2.3.10
code-runner|for|0.9.11
language-haskell|jus|2.6.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
laravel-blade|one|1.20.0
bash-beautify|sha|0.1.1

</details>

**Comment by autinerd** [comment]
Did you maybe shut down the operating system while an update was being installed? In some occasions, when it happens between uninstalling old version and installing new version, the program is gone.

**Comment by joaomoreno** [comment]
Sorry about that. Let's reinstall VS Code and let me know if it happens once again.
