### ISSUE TITLE
[problems view] align UI with other views

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#7715]
- the problem view find box is slightly higher (26px) than the find/replace box and the search box (25px)
- the view's closing X has a larger margin on the right then the editor's X

![image](https://cloud.githubusercontent.com/assets/6461412/16077183/8eecacc0-32f7-11e6-9884-1a5e3477ada4.png)

**Comment by sandy081** [comment]
- Fixed the input box height. 

- Aligned toolbar actions in the panel with those on the editor.
