### ISSUE TITLE
Auto Save isn't working anymore

### ISSUE THREAD

**Issue by kimmosh** [Microsoft/vscode#7716]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by sandy081** [comment]
@kimmosh Can you please provide which version of VS code and OS are you using and any additional info would be really great.

Thanks.

**Comment by kimmosh** [comment]
version 1.2.1. os:windows 10 bing

On Thu, Jun 16, 2016 at 9:21 AM, Sandeep Somavarapu <
notifications@github.com> wrote:

> @kimmosh <https://github.com/kimmosh> Can you please provide which
> version of VS code and OS are you using and any additional info would be
> really great.
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode/issues/7716#issuecomment-226419236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASwZaqKpf0mJOdLyzJSXKLjQzVjAVs6aks5qMQd0gaJpZM4I2PLI>
> .
>



-- 
*-moshood oshindele*

**Comment by sandy081** [comment]
@kimmosh I just checked and it is working on stable build on Windows 10

Can you please provide more information like 
- what is your set up
- what you are trying and what you noticed..

Note: We (Dev team) use Auto save as default and it is working.

Thanks

**Comment by dbaeumer** [comment]
Closing. Didn't receive a response in 10 days.
