### ISSUE TITLE
Go to the idea of defining improvements

### ISSUE THREAD

**Issue by fengzhihenxs** [microsoft/vscode#77164]
I have a nice feature when using webstrorm to develop an angular project, but this feature is not implemented in vscode.
scene:
I defined a variable a in app.component.ts, a variable a in app.component.html, and a variable a in app.component.html in webstrorm to go to the defined location. But vscode doesn't work, and shows that you can't find any definition of a.

Can it be improved?

**Comment by mjbvz** [comment]
We don't include builtin angular support. Please try installing one of the angular extensions

**Comment by fengzhihenxs** [comment]
Ok， thank you. By the way, which extension of angular can implement this function? Angular Follow Selector can't.
