### ISSUE TITLE
With VSCode 1.37 insider build spectron test cases not running the same is working with VSCode 1.36

### ISSUE THREAD

**Issue by kaushal2712** [microsoft/vscode#77166]
Issue - We have written automation tests using spectron to test "ExtendScript Debug" VSCode extension. These tests are run daily on latest insider builds with "ExtendScript Debug" VSCode extension installed. Our tests are failing since  July 4th 2019 insider builds.

- VSCode Version: 1.37 insider builds
- OS Version: OSX 10.14

Steps to Reproduce:

1. Please refer to the usage instruction of spectron at - https://www.npmjs.com/package/spectron
2.  below are the steps
-npm i mocha -D
-touch test/spec.js
-cd test
-copy spec.js contents from https://www.npmjs.com/package/spectron
-replace spec path with the electron path of VSCode insider build.
-run mocha test

**Comment by weinand** [comment]
Since the tests are your code, you will have to figure out what is failing.

**Comment by kaushal2712** [comment]
Hi,
Even the sample code available in electron official documentation https://electronjs.org/spectron is not working. Please advise.

**Comment by weinand** [comment]
How is it failing?
Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
