### ISSUE TITLE
Support moving to next/previous change in editor view, without opening inline changes view

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#7717]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.4

`workbench.action.compareEditor.nextChange` only works in 'Changes View' right now.
It would be nice to have a more general action that also works in 'Editor View'.

**Comment by vogler** [comment]
What info do you need?
I'm talking about this keyboard shortcut:
```json
{ "key": "cmd+k cmd+right",       "command": "workbench.action.compareEditor.nextChange",
                                     "when": "textCompareEditorVisible" },
```
Even if the `when`-part is removed, it only works in the compare view and doesn't in the normal editor.

**Comment by joaomoreno** [comment]
I don't fully understand how you'd expect to navigate to the next change in the editor view. It would only work if you edit a file which is currently modified? What would happen if the next change is a line deletion?

**Comment by vogler** [comment]
> It would only work if you edit a file which is currently modified?

Yes.

> What would happen if the next change is a line deletion?

Same as in the "Changes View", i.e. jump to that position.

**Comment by joaomoreno** [comment]
👍

**Comment by joaomoreno** [comment]
By the way, this would possibly make a good contribution, if you are interested in creating a PR.

**Comment by bpceee** [comment]
need this! jetbrains has it.. 
https://www.jetbrains.com/help/pycharm/2016.3/navigating-to-next-previous-change.html

**Comment by bpceee** [comment]
Hi @joaomoreno , I created a PR for this.

**Comment by joaomoreno** [comment]
Went with:

- `workbench.action.editor.previousChange`
- `workbench.action.editor.nextChange`

Default keybindings: <kbd>Alt F5</kbd> and <kbd>Shift Alt F5</kbd>.

**Comment by bpasero** [comment]
Two issues (using keybindings):
* the diff is not revaled when jumped to it (cursor moves though)
* when there is no change, I see an error: 

![image](https://user-images.githubusercontent.com/900690/36726452-1cde56f8-1bba-11e8-895f-b36ebd47b7c3.png)

**Comment by joaomoreno** [comment]
@bpasero Great catches!

**Comment by Tyriar** [comment]
Thanks @bpceee and @joaomoreno! I've wanted this for a long time 😃

**Comment by Tyriar** [comment]
@joaomoreno FYI I'm going to try get used to these keybindings to override the other one, so a setting would be more convenient personally:

```js
{ "key": "alt+f3",                "command": "workbench.action.editor.nextChange",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+f3",          "command": "workbench.action.editor.previousChange",
                                     "when": "editorTextFocus" },
```

alt+f5 is a bit awkward with one hand.

**Comment by theseyi** [comment]
Is this currently available? @Tyriar. I get `command 'workbench.action.editor.nextChange' not found`

**Comment by Tyriar** [comment]
@theseyi are you using insiders? https://code.visualstudio.com/insiders/

**Comment by theseyi** [comment]
Not currently, but will switch to that. Thanks

________________________________

**Comment by bpasero** [comment]
@joaomoreno is it intentional that these commands do not work in the diff editor?

**Comment by joaomoreno** [comment]
More like not implemented/possibly not able to.

**Comment by bpasero** [comment]
Ok, I opened https://github.com/Microsoft/vscode/issues/44904

The diff editor itself is defining commands already that allow to navigate between diffs. At one point these should maybe be aligned.
