### ISSUE TITLE
Side panels do not remember width between restarts

### ISSUE THREAD

**Issue by lllopo** [microsoft/vscode#77177]
- VSCode Version: 1.37.0 Insiders latest
- OS Version: Windows 10

Steps to Reproduce:

1. Resize one of the side panels, "Explorer" for example
2. Restart VS Code
3. Check the panel width

Expected result:
The width of the side panel should be what the user set before restart.

Result: 
The side panel width is reverted to some preset width.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@lllopo what about other state, like the list of opened editors?

**Comment by lllopo** [comment]
> @lllopo what about other state, like the list of opened editors?

Not sure If I'm getting your quastion right, but all panes - explorer, search, debug, extensions, no matter with folder open or not do not remember their state. The production version does, insiders - not.

**Comment by bpasero** [comment]
@lllopo what I meant is:
* start VSCode (insiders)
* close all editors
* open one editor (e.g. some file)
* close VSCode via the close button top right
* start VSCode (insiders)

=> is that one editor still opened?

**Comment by lllopo** [comment]
I can answer straight that it is not, because that's how I've set it up. The thing is, that my production VS Code has the exact same configuration, but it does remember the panes widths.

**Comment by bpasero** [comment]
@lllopo strange!

Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running and see if it then also happens?

**Comment by lllopo** [comment]
Oookayyy ... hm ... if I run it this way it works fine. Furthermore, even if I run it with extensions enabled (so just with --user-data-dir) it still works fine. It must be somehow the settings then, but I can see how. Here they are :

`{
    "git.ignoreMissingGitWarning": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "editor.insertSpaces": false,
    "editor.codeLens": false,
    "editor.minimap.enabled": false,
    "editor.dragAndDrop": false,
    "editor.emptySelectionClipboard": false,
    "editor.hover.delay": 3000,
    "editor.quickSuggestionsDelay": 3000,
    "editor.renderLineHighlight": "gutter",
    "editor.showUnused": false,
    "editor.formatOnType": true,
    "editor.fontSize": 15,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.startupEditor": "newUntitledFile",
    "workbench.settings.openDefaultSettings": false,
    "workbench.colorCustomizations": {
        "foreground": "#333333",
        "editor.background": "#ffffff",
        "editor.lineHighlightBackground": "#EAEAEA",
        "editorIndentGuide.background": "#f3f3f3",
        "editorIndentGuide.activeBackground": "#e0e0e0",
        "editorGutter.background": "#f9f9f9",
        "editor.selectionBackground": "#cee7ff",
        "editor.selectionHighlightBorder" : "#cee7ff",
        "editorBracketMatch.background": "#cae5ff",
        "editorBracketMatch.border": "#ffffff00",
        "activityBar.foreground": "#FFFFFFED",
        "activityBar.background": "#232A35",
        "sideBar.border": "#D5D5D5",
        "widget.shadow": "#ffffff00",
        "scrollbar.shadow": "#ffffff00",
        "focusBorder": "#00000000",
        "titleBar.activeBackground": "#fafafa",
        "titleBar.activeForeground": "#333333",
        "titleBar.inactiveBackground": "#fafafa",
        "titleBar.inactiveForeground": "#aaaaaa",
        "tab.activeBorderTop": "#0099E1",
        "tab.activeBackground": "#f9f9f9",
        "tab.inactiveForeground": "#777777",
        "statusBar.noFolderBackground": "#232A35",
        "statusBar.background": "#232A35",
        "statusBar.foreground": "#ffffff",
        "menu.selectionBackground": "#1A7DC4",
        "menu.background": "#FAFAFA",
        "menubar.selectionBackground": "#d0d0d0",
        "breadcrumb.foreground": "#555555",
        "breadcrumbPicker.background": "#f9f9f9",
        "breadcrumb.background": "#f9f9f9",
        "editorLineNumber.foreground": "#B9B9B9",
        "editorLineNumber.activeForeground": "#777777",
        "list.activeSelectionBackground": "#1A7DC4",
        "list.activeSelectionForeground": "#FFFFFF",
        "list.inactiveSelectionBackground": "#e4eef7"
    },
    "window.closeWhenEmpty": true,
    "window.restoreFullscreen": true,
    "window.restoreWindows": "none",
    "window.newWindowDimensions": "maximized",
    "window.enableMenuBarMnemonics": false,
    "files.autoGuessEncoding": true,
    "files.hotExit": "off",
    "files.associations": {
        "*.ctp": "php"
    },
    "explorer.openEditors.visible": 0,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",       
    "html.format.indentInnerHtml": true,
    "html.format.indentHandlebars": true,        
    "php.suggest.basic": false,
    "php.validate.executablePath": "D:\\Programs\\OSPanel\\modules\\php\\PHP-7.2-x64\\php.exe",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Boxy Yesterday",
    "explorer.autoReveal": false,
    "explorer.enableDragAndDrop": false,
    "local-history.saveDelay": 1,
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
    "local-history.path": "${workspaceFolder}/.vscode",
    "files.exclude": {
        "**/.history": true,
        "**/.idea": true,
        "**/.vscode": true,
        "**/nbproject": true
    },
    "breadcrumbs.enabled": true,
    "files.watcherExclude": {
        "**/.history/**": true,
        "**/.idea/**": true,
        "**/.vscode/**": true,
        "**/nbproject/**": true
    },
    "workbench.list.keyboardNavigation": "filter",
    "phpGettersSetters.redirect": false,
    "textPowerTools.insertUppercaseGuids": true,
    "auto-close-tag.SublimeText3Mode": true,
    "auto-close-tag.fullMode": true,
    "better-comments.highlightPlainText": true,
    "better-comments.tags": [
        {
            "tag": "todo",
            "color": "#1A7DC4",
            "strikethrough": false,
            "backgroundColor": "transparent"
        },
        {
            "tag": "!",
            "color": "#CC0000",
            "strikethrough": false,
            "backgroundColor": "transparent"
        }
    ],
    "editor.gotoLocation.multiple": "goto",
    "editor.maxTokenizationLineLength": 50000,
    "editor.find.addExtraSpaceOnTop": false,
    "workbench.iconExploration.enabled": true,
    "workbench.useExperimentalGridLayout": true,
    "zenMode.hideLineNumbers": false,
    "search.smartCase": true,
    "search.useGlobalIgnoreFiles": true,
    "debug.inlineValues": true,
    "debug.internalConsoleOptions": "neverOpen",
    "debug.toolBarLocation": "docked",
    "workbench.tree.indent": 19,
    "css.lint.compatibleVendorPrefixes": "warning",
    "css.lint.duplicateProperties": "warning",
    "css.lint.ieHack": "warning",
    "html.format.wrapAttributes": "preserve-aligned",
    "namespaceResolver.exclude": "**/node_modules/**, **/.history/**",
    "namespaceResolver.sortNatural": true,
    "namespaceResolver.highlightOnOpen": true,
    "references.preferredLocation": "view",
    "intelephense.files.exclude": [
        "**/.git/**",
        "**/.svn/**",
        "**/.hg/**",
        "**/CVS/**",
        "**/.DS_Store/**",
        "**/node_modules/**",
        "**/bower_components/**",
        "**/vendor/**/{Test,test,Tests,tests}/**",
        "**/.history/**",
        "**/.idea/**",
        "**/.vscode/**",
        "**/nbproject/**"
    ],
    "workbench.tree.renderIndentGuides": "none"
}`

**Comment by bpasero** [comment]
@lllopo well `"window.restoreWindows": "none"` ??

**Comment by lllopo** [comment]
Hmm ... if so, a few things then :
1. When I say I don't want my windows restored, this definitely doesn't mean I don't want my work layout restored. These are quite different things for me.
2. Having the above, isn't it reasonable to store this on application level or at workspace level at the very least.
3. Last, but the most confusing - how come that my production VS Code behaves as expected, with the very same setting ?

**Comment by bpasero** [comment]
@lllopo sorry, this is caused by another setting. Try switching to `workbench.useExperimentalGridLayout: false`

**Comment by lllopo** [comment]
@bpasero Yes, that's it !
