### ISSUE TITLE
VSCode crashes and uninstalled when updating

### ISSUE THREAD

**Issue by carl-angelo** [microsoft/vscode#77176]
Issue Type: <b>Bug</b>

when I close my VSCode app, it updates automatically then failed. Then, my VSCode was uninstalled already. After i reinstall the latest version, same thing happen again.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
es7-react-js-snippets|dsz|2.3.0
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
sass-indented|rob|1.5.1

</details>

**Comment by joaomoreno** [comment]
Do you use the system setup or the user setup?
