### ISSUE TITLE
PowerShell script gets an error in VSCode Insider preview but works fine in VSCode.

### ISSUE THREAD

**Issue by vRITHNER** [microsoft/vscode#77178]
Issue Type: <b>Bug</b>

Hi,
The same PowerShell script gets an error in VSCode Insider preview but works fine in VSCode.

I can't share my code but I reproduce the issue with other urls:

```
Clear-Host

$login_url="https://google.com"

#Login
Write-Host "Press any key after login !"
Start-Process -FilePath "${login_url}"
pause

Write-Host "--> next step"
Write-Host "--> done !"

```
In VsCode, this code works fine.
In VsCode Version: 1.37.0-insider (user setup)
Commit: 46cc0a1670b7047e610aaef1bf84f1190802e9ec
Date: 2019-07-11T05:39:42.001Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18922
-------------------------------------------------------------------------------

> Start-Process : Cannot find drive. A drive with the name 'https' does not exist.
> At D:\Mandats\Roomz\V2\src\docker-onpremise\Get_TeamCity_Binaries_Test.ps1:7 char:1
> + Start-Process -FilePath "${login_url}"
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (https:String) [Start-Process], DriveNotFoundException
> + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.StartProcessCommand       

 -----------------------------------------------------------------------------------
I get this error which happened few versions ago. Before, it was working fine.
Thanks

VS Code version: Code - Insiders 1.37.0-insider (46cc0a1670b7047e610aaef1bf84f1190802e9ec, 2019-07-11T05:39:42.001Z)
OS version: Windows_NT x64 10.0.18922

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (7.23GB free)|
|Process Argv|--folder-uri file:///d%3A/Mandats/Roomz/V2/src/docker-onpremise|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
azurenodeessentials|azu|0.2.6
phpserver|bra|2.4.6
npm-intellisense|chr|1.3.0
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.8
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
dotnet-test-explorer|for|0.7.1
rest-client|hum|0.21.3
phpcs|ika|1.0.5
diff-tool|jin|0.0.1
vscode-nuget-package-manager|jmr|1.1.6
guid|kos|0.0.1
gitignore|mic|1.0.1
dotenv|mik|1.0.1
azure-pipelines|ms-|1.152.0
azurerm-vscode-tools|msa|0.6.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.9
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.1
vetur|oct|0.21.1
nginx-formatter|ray|0.0.4
java|red|0.46.0
json-organizer|rin|0.0.4
vscode-xml-complete|rog|0.1.7
yo|sam|0.9.3
vscode-nginx|sha|0.6.0
json-schema-validator|tbe|0.1.0
python|tht|0.2.3
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.7
azure-iot-edge|vsc|1.14.0
azure-iot-toolkit|vsc|2.8.0
vscode-arduino|vsc|0.2.27
vscode-iot-device-cube|vsc|0.1.0
vscode-iot-workbench|vsc|0.3.1
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
prettify-selected-json|vth|1.0.3
WebTemplateStudio-dev-nightly|WAS|0.0.1919001
vscode-nginx|wil|0.7.1

</details>

**Comment by Tyriar** [comment]
@TylerLeonhardt thoughts?

**Comment by TylerLeonhardt** [comment]
@vRITHNER does your terminal window say “powershell.exe” or “PowerShell Integrated Console”.

I’m trying to narrow down if you’re running within the PowerShell extension or just the default terminal experience in vscode.
