### ISSUE TITLE
A11y_VSCode_ Debugging_Keyboard: Keyboard focus lost after refreshing.

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/vscode#77182]
**Environment Details:**
VSCode Version : 1.360(user setup)
OS Version : Win10

**Additional Details:**
MAS Violated : MAS 2.4.3

**Repro Steps:**
1.Open Visual studio code editor.
2.Using "Ctrl+Shift+D" key navigate to the debug side view bar option.
3.Open the launch.json file under the "Configure or Fix: launch.json"button and select "Node.js" from the drop down list
4. Add configurations to "launch.json" utilizing IntelliSense with CTRL+SPACE
5. Parse launch.json with keyboard and observe if ATs will provide stock debugging information under "configurations" properties.
6.Start debugging by pressing F5.
7.Navigate to refresh button and hit  enter key.

**Actual:**
Keyboard focus is going back to first actionable control in toolbar after refreshing. 

**Expected:**
Keyboard focus should remain on same button after refreshing.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
[https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx
](https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
Keyboard only user get confused after refreshing.

**MAS Reference:**
MAS 2.4.3 -
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9})

**Attachment for Reference:**
[VSCode_ Debugging_Keyboard focus lost after refreshing.pptx](https://github.com/microsoft/vscode/files/3380684/VSCode_.Debugging_Keyboard.focus.lost.after.refreshing.pptx)

**Comment by isidorn** [comment]
This is fine. Since the refresh is stoping a session and starting a new session. Thus the toolbar is recreated and the focus is not preserved.
Preserving focus on the debug toolbar is not that important imho in this case (why would a user want to restart a session after he just restarted it?!)
Also most users just use keyboard shortucs or command palette, and not moving focus to the floating toolbar (which is designed more for the mouse use)
