### ISSUE TITLE
property functions being flagged as invalid code in js files

### ISSUE THREAD

**Issue by jefflindholm** [Microsoft/vscode#7718]
- VSCode Version: 1.2.1
- OS Version:
windows 10
Steps to Reproduce:

1. create a js file
2. create a class file and add a property
get "[js] 'property declarations' can only be used in a .ts file." with the property code highlighted. 
I am attempting to use code to do react coding and using the property functions keep me from littering my code with myfunc = myfunc.bind(this); unless I actually need to rebind something. It is more an annoying visual thing to have a lot of code underlined than anything else, but it would seem to be something you should allow in js/jsx files.
```javascript
class MyClass {
  someFunction = () => {

  }
}
```

**Comment by sandy081** [comment]
This issue was moved to Microsoft/TypeScript#9207

**Comment by sandy081** [comment]
@jefflindholm Above issue got fixed in Typescript 2.0 which is TS Next version and VS code is currently shipped with always latest shipped Typescript which is 1.8.x. 

You can install the latest Typescript 2.0 and point VS code to it by changing the settings `typescript.tsdk`
