### ISSUE TITLE
Visual Studio Code Extensions Terminated Unexpectedly

### ISSUE THREAD

**Issue by sdc224** [microsoft/vscode#77189]
Issue Type: <b>Bug</b>

Whenever I am trying to write any html or css code, my extensions are terminated unexpectedly and I need to restart vs code again to get suggestions (intellisense)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
jsrefactor|cms|2.18.2
ini-for-vscode|Dav|0.0.4
es7-react-js-snippets|dsz|2.3.0
vscode-html-css|ecm|0.2.0
reg|ion|1.0.1
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
vsliveshare|ms-|1.0.509
vsliveshare-audio|ms-|0.1.59
vsliveshare-pack|ms-|0.3.2
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.1
java|red|0.46.0
LiveServer|rit|5.6.1
vscode-java-debug|vsc|0.20.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by lea-lp** [comment]
Same error here, unless none of my extensions are working anymore. 
I tried to disable and enable them one by one, reload several times : no changes.

VS Code Version 1.36.1 (1.36.1)
MacOS Mojave Version 10.14.1

<details>
<summary>Error details : "Extension host terminated unexpectedly" </summary>

```
Extension host terminated unexpectedly.abstractExtensionService.ts:155 
Extension host terminated unexpectedly. Code: null Signal: SIGSEGV _onExtensionHostCrashed @ abstractExtensionService.ts:155 notificationsAlerts.ts:40 
Extension host terminated unexpectedly. onDidNotificationChange @ notificationsAlerts.ts:40 vscode
```
</details>

<details>
<summary>Extensions (18)</summary>

| Author | Extension  | Version |
| ------------- | ------------- | ------------- |
bmewburn|PHP Intelephense|1.1.4
CoenraadS|Bracket Pair Colorizer 2|0.0.28
DavidAnson|Markdownlint|0.28.0
Equinusocio|Material Theme|29.2.0
esbenp|Prettier|1.9.0
felixfbecker|PHP Debug|1.13.0
felixfbecker|PHP Intellisense|2.3.10
HookyQR|Beautify|1.5.0
jnbt|Rufo|0.0.1
johnpapa|Peacock|2.4.0
ms-mssql|SQL Server (mssql)|1.6.0
ms-vsliveshare|Liveshare|1.0.509
ms-vsliveshare|Liveshare-pack|0.3.2
phproberto|PHP Getters-Setters|1.2.3
PKief|Material Icon Theme|3.8.0
rebornix|Ruby|0.24.1
sibiraj-s|Scss Formatter|1.4.1
Sophisticode|PHP Formatter| 0.2.4

</details>


Thanks !

**Comment by jeremytbrun** [comment]
Same issue.

**Comment by alexandrudima** [comment]
It's the `karigari.chat` extension. Please reach out to the extension author directly. See https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205
