### ISSUE TITLE
Update VS Code from Command Palette

### ISSUE THREAD

**Issue by gkkirilov** [microsoft/vscode#77184]
Ability to update VS Code from the command palette as I have disabled activity bar and have to reenable it to update VS Code.
Also, there is a palette option to check for extensions updates, but not for the whole app

Steps:
1. Open Command palette
2. Input `>Check for VS Code Update`
3. Update VS Code

**Comment by 2l2t** [comment]
First timer here. Could I give this one a shot?

**Comment by DiamondYuan** [comment]
I can do this work.

**Comment by Iviglious** [comment]
Hello there, I'm experienced developer and would like to contribute.

**Comment by NISHIT103** [comment]
Hello there, I am a developer and I have gone through the whole code base and I think that I can add this feature without much problem. Can I please give it a shot?

**Comment by gkkirilov** [comment]
@NISHIT103 Please do, you can check the [previous PR](https://github.com/microsoft/vscode/pull/77515)

**Comment by NISHIT103** [comment]
@gkkirilov I have implemented this feature in #82168 . Kindly review it.

**Comment by NISHIT103** [comment]
@gkkirilov I have implemented this feature in #82202. Kindly review it.

**Comment by alexr00** [comment]
Works nicely, for downloading updates, but a command doesn't show to Restart To Update.
