### ISSUE TITLE
Font not rendering correctly in WIndows 10 - MacBookPro 2017

### ISSUE THREAD

**Issue by jstoppa** [microsoft/vscode#77188]
Issue Type: <b>Bug</b>

When opening VSCode insiders, the font doesn't render correctly. This happens intermittently.
See image here:
https://jstoppa.github.io/images/vscodeissue.png
This started happening since the new change on the icons on the left hand bar.
I'm running VSCode Insiders in Windows 10 - MacBookPro 2017

VS Code version: Code - Insiders 1.37.0-insider (46cc0a1670b7047e610aaef1bf84f1190802e9ec, 2019-07-11T05:39:42.001Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.5
prettier-vscode|esb|1.9.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.14.2
mssql|ms-|1.6.0
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6

</details>

**Comment by Sovgut** [comment]
Seen the same in [Discord](https://discordapp.com/), I think this is electron bug.

**Comment by Sovgut** [comment]
I found a dependency, this happens when using an AMD video card (RX570).

When using solutions from Intel, this problem is not observed.
And yes, I use the stable version, not insider.

![image](https://user-images.githubusercontent.com/26426861/61865028-2dbde000-aedb-11e9-82b0-7a671c559fda.png)

**Comment by deepak1556** [comment]
@jstoppa how is the behavior when you launch code with `--disable-gpu` ?

**Comment by bpasero** [comment]
Ping

**Comment by Sovgut** [comment]
If no one is against, I will answer, when I started with the attribute ```--disable-gpu```, the problem disappeared.

**Comment by Sovgut** [comment]
How do I set ```--disable-gpu``` flag by default to run vscode?

**Comment by Tyriar** [comment]
@Sovgut you can't, you should upvote https://github.com/microsoft/vscode/issues/15211 if you want it

**Comment by Sovgut** [comment]
@Tyriar thank you.

**Comment by jstoppa** [comment]
@Sovgut sorry for not getting back to you before and thanks for looking at this.
I haven't had the issue for a few weeks now, I'm running VS Code insiders (setup below). I'll report back if I get the issue again and see if `--disable-gpu` solves the issue as @deepak1556 suggested

Version: 1.39.0-insider (user setup)
Commit: d157c2e941cae17acb79bf26a70bbfad732bdc83
Date: 2019-09-16T06:06:10.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by jstoppa** [comment]
This happened again today, I tried the `--disable-gpu` option but then I saw @Tyriar comments.

Bottom line is that I closed VSCode, reopened a blank project and the problem went away.

I'll try to collect more info if I manage to reproduce it again

Here are the latest details of my VSCode setup.

Thanks

VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:24:45.690Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.96GB free)|
|Process Argv|--disable-gpu|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.0
prettier-vscode|esb|2.3.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.1
mssql|ms-|1.6.0
powershell|ms-|2019.9.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
angular-console|nrw|8.1.2


</details>

**Comment by deepak1556** [comment]
Can you also try our exploration builds to see if the situation is any better ? Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by jstoppa** [comment]
Thanks @deepak1556 
What is the exploration build? does it have the same functionality as of insiders?

**Comment by jstoppa** [comment]
ok, I downloaded it now. I'll start using the exploration build too. I'm not getting the issue at the moment but I'll le you know if I do

**Comment by deepak1556** [comment]
@jstoppa thanks for confirming! exploration builds contain a more recent version of electron that will be the candidate for next insiders. The exploration update has been merged into master today https://github.com/microsoft/vscode/pull/81644, you can expect this in next insiders.
