### ISSUE TITLE
This color looks like shit. How do i edit it ?

### ISSUE THREAD

**Issue by zhishanggao** [microsoft/vscode#77180]
![image](https://user-images.githubusercontent.com/16753441/61029423-8eceb980-a3ed-11e9-9bcf-64c1076089e8.png)
version 1.36.1

**Comment by kanlukasz** [comment]
First of all, when you ask for something, be cultured. "Like shit" definitely is not what we want to read.
And secondly, the repository is not used to handle simple questions like this one.
Please use stackoverflow.com instead.

Anyway, you have to edit your theme for change this colors, or you can change your theme to another.
https://code.visualstudio.com/api/references/theme-color

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/getstarted/themes on how to change or customize a color theme. The color that is yellow in the screenshot is a git color: https://code.visualstudio.com/api/references/theme-color#git-colors

You can also file issue a request against the theme.
