### ISSUE TITLE
The VSCODE Emmet is not easy to use

### ISSUE THREAD

**Issue by shenenhua88** [microsoft/vscode#77193]
In vscode, emmet function is not very friendly,

Can't liket sublime，easy to use.

The vscode not fully support emmet, and not click "tab" to completion code. 
that is not  write code quickly.

Hope to refer emmet of sublime 3.

Hope to adopt!!!

**Comment by octref** [comment]
You can enable `"emmet.triggerExpansionOnTab"`.
