### ISSUE TITLE
Links in Typescript tooltips don't work

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#77199]
There are blue hyperlinks in the tooltips for the VS Code bindings, but clicking them doesn't seem to do anything. If they're not expected to work, should they not be links?

<img width="966" alt="Screenshot 2019-07-11 at 12 21 31 pm" src="https://user-images.githubusercontent.com/1078012/61047068-80c16e80-a3d6-11e9-80a2-1e0e06dbdda3.png">

**Comment by mjbvz** [comment]
These links are of the form `#Some-Symbol-Name` and so they definitely will not work. Support is tracked by #8223

Marking as help wanted if someone want to investigate stripping such links from the displayed content

**Comment by DiamondYuan** [comment]
> These links are of the form `#Some-Symbol-Name` and so they definitely will not work. Support is tracked by #8223
> 
> Marking as help wanted if someone want to investigate stripping such links from the displayed content

i can do this job，Do you mean remove link from comment in image？

**Comment by mjbvz** [comment]
Yes. Just render it as text

**Comment by DiamondYuan** [comment]
> Yes. Just render it as text

Sorry, I didn't find which file I should change.

**Comment by frobinsonj** [comment]
Commit 2c1c691b06ce90b9517bd3c5e5f518a130c18939 from @jrieken means that these links will now output as `file:///#fragment`.

Could add `|| href.match(/^file:\/\/\/#/)` to the below if statement to filter out these broken links but that's far from ideal. Would like to have a go at this issue but I have a feeling that a better solution would involve removing "file" as the default scheme. Any ideas on how I could tackle this?
https://github.com/microsoft/vscode/blob/fa5c6386eb7533390fac174cc1b7327321a8b986/src/vs/base/browser/markdownRenderer.ts#L101-L110

**Comment by bradennapier** [comment]
This occurs because there is a special extension that specifically provides document links for any `vscode.d.ts` files.  This is separate from the tooltip renderer which renders the markdown. 

It is pretty clear that in general `URI` fragment should provide a means for navigating to a symbol.  

`file://path/to/file.ts#Symbol.path` should basically be supported out of box.

**Comment by mjbvz** [comment]
Let's fold this into https://github.com/microsoft/TypeScript/issues/35524

Once JS/TS supports `@see` tags, then we can swap over to using proper links in the `vscode.d.ts` file
