### ISSUE TITLE
DisposableStore doesn't fail fast but obscure

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#77192]
https://github.com/microsoft/vscode/blob/e9d8aaafcb1f0a456aa95950de22b822663a00e0/src/vs/base/common/lifecycle.ts#L130-L131

🔝 That's quite mean because instead of throwing an error at the spot it disposes whatever has been given to it and therefore causes all kinds of errors later down the road. This issue is an example: https://github.com/microsoft/vscode/issues/76769 of "random" carnage due to unexpected disposal and I was lucky to spot [one](https://github.com/microsoft/vscode/issues/76769#issuecomment-509342223) occurrence of that warning.  This fix was trivial, calling `clear` instead of `dispose`, an error that often happens during this refactoring. 

So, either only warn and don't dispose or throw a real error.

**Comment by mjbvz** [comment]
Needs some thought. We may want different behavior in debug / shipped builds. For example, throwing may be ok in our local builds but will likely cause more problems for shipped builds

**Comment by jrieken** [comment]
I agree but for a start it should just stop disposing, it's much worst having some unexpected state than a leak.
