### ISSUE TITLE
VSCode crashes when running webpack with "--progress" flag

### ISSUE THREAD

**Issue by Franziskus1988** [microsoft/vscode#77197]
Issue Type: <b>Bug</b>

I have a build task that executes a npm script:
Build task:
```
{
      "type": "npm",
      "script": "build",
      "path": "src/apps/client-app/",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": false,
        "revealProblems": "onProblem",
        "clear": false
      }
    }
```

Npm script:
`webpack --config .\\webpack.config.js --progress`

If I run this task VSCode first freezes and then crashes. 

It does not crash when I have the terminal tab with the running task open. Only if e.g. Problems tab is active. 

It does not crash when I remove the "--progress" flag.

Does this issue occur when all extensions are disabled?: Yes
Does it happen in Insider build?: Yes

Just wanted to let you know. For me it's easy to just remove the progress flag for now, but maybe it's a general problem that VSCode can't handle this type of output. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (50.35GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by sandy081** [comment]
Can you please profile it and provide us the report. 

https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by Franziskus1988** [comment]
Hi. Here is the profile. Since VSCode crashes after around 30 seconds I can only profile the first few seconds otherwise the profiling is cancelled, too.

[profile.zip](https://github.com/microsoft/vscode/files/3405363/profile.zip)

**Comment by sandy081** [comment]
@Franziskus1988 Profile does not have any interesting info related to crash. 

Are there any logs or crash reports do you get? Open Dev tools and see if there are any errors in the console? Also there are logs in the Output panel.

Can you also repro it by disabling all extensions?
