### ISSUE TITLE
Failed to execute git on project folders which are not git repos

### ISSUE THREAD

**Issue by danielrob** [Microsoft/vscode#7719]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: OSX 10.11.4 (El Capitain)

My workflow is like this: 

Steps to Reproduce:
1. `$ mkdir gitcodetest && cd gitcodetest && code .`
2. Create a new file in the visual studio code window that opens up. 
3. Save it with some content.

Get: 
<img width="1048" alt="screen shot 2016-06-15 at 9 27 47 am" src="https://cloud.githubusercontent.com/assets/5865302/16081457/7a0d3ce6-32db-11e6-8410-3a28cfebdca4.png">

Workaround: 
run `git init` on the repo

By contrast this does not happen if I open a folder that is a git repo. 

This popup is a royal pain, why should I have to be using git on the repo? I'm just checking out projects which I'm not actually developing. It's seriously annoying. 

Opening the git panel results in an endless loading bar under these circumstances:
<img width="216" alt="screen shot 2016-06-15 at 9 35 04 am" src="https://cloud.githubusercontent.com/assets/5865302/16081683/8b1f1a6c-32dc-11e6-8d5a-b8d9abbfaf33.png">

Console.log: 
<img width="961" alt="screen shot 2016-06-15 at 9 38 25 am" src="https://cloud.githubusercontent.com/assets/5865302/16081780/f9650b62-32dc-11e6-9edb-e3f16f310d37.png">

**Comment by joaomoreno** [comment]
I assume you mean *without a git repository initialised* instead of *without git installed*.

Plus, from the error it looks like you do have a strange setup: `fatal: Invalid gitfile format: .git\n`. Are you sure there is no `.git` folder or file in the cwd or any of its ancestors?

**Comment by danielrob** [comment]
I had a `~/.git` _file_ for some unknown reason (it had node_modules as it's sole contents, so a .gitignore gone wrong perhaps). Removing this file resolves the issue. I had not thought at all about ancestor search paths, thank you sir!

**Comment by joaomoreno** [comment]
Thanks for confirming!
