### ISSUE TITLE
debugger hijack node-pty stdout in debug mode

### ISSUE THREAD

**Issue by webarchymeta** [microsoft/vscode#77191]
- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.18362

We have a project that uses node-pty (background) + xterm(js)  (UI) to access linux shell. The debugger works before upgrading, namely, when launching the system in the vscode debugger, the linux shell appears on a visiting browser because the data can be captured by the `data` event of the child process (launched by the node-pty) and send to the browser xterm via a websocket. 

After the upgrading, the said data output is hijacked by the debugger stdout via a pipe and appears on the console window of the debugger. The said `data` event above no longer fires ...

I am not sure this is a bug or there is additional setting to be made?

**Comment by weinand** [comment]
What do you mean by "upgrading"?

**Comment by webarchymeta** [comment]
@weinand I mean changing from an older version to the newest version at the moment (of writing the above message) ... But I am not sure which one of the older versions is the last one that works since I might had skipped a few before discovering the defect

**Comment by weinand** [comment]
Sorry, I don't understand your problem and I do not know how to reproduce this.
Please try again with the latest VS Code 1.43.2 and I will reopen the issue if the problem still occurs.
