### ISSUE TITLE
[html] Improve auto completion of html closing tags

### ISSUE THREAD

**Issue by osjn** [Microsoft/vscode#772]
For html closing tags, auto completions will show after typing `</`, can they show after typing `<` and needn't type `/`, and then the cursor is positioned between `>` and `<` after auto-completing?

**Comment by oatmealpirate** [comment]
Many editors all did this, like **Komodo Edit**.

**Comment by alexandrudima** [comment]
@aeschli Not sure if this is low hanging

**Comment by Tyriar** [comment]
@osjn do you mean to have the closing tag be a higher priority than other tag auto-completions? Enabling this:

- Type `<div>`
- Type `<`
- Press enter to auto-complete `/div>`

Related: https://github.com/Microsoft/vscode/issues/877

**Comment by osjn** [comment]
@Tyriar not mean that, just the mean of providing for auto completion, and the affect after auto completing. As below:
1. type `<div>`
2. type`<`
3. needn't press enter, it becomes `<div></div>`, and the cursor is between `>` and `<`
Resources:
`1. Komodo Edit
2. Brackets`

**Comment by formulahendry** [comment]
@osjn  This [Extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) would nearly meet with your requirement. It will automatically add closing tag when you type in the closing bracket of the opening tag.

![GIF](https://raw.githubusercontent.com/formulahendry/vscode-auto-close-tag/master/images/usage.gif)

**Comment by osjn** [comment]
@formulahendry thank you so much...

**Comment by aeschli** [comment]
Not sure when we added that, but closing proposals are shows also right after `<`.
Note they only show up if there are tags to be closed.

**Comment by aeschli** [comment]
There's a related issue: #38880
