### ISSUE TITLE
Electron 6: Bold font seems less distinguishable from normal font

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77204]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. For this, I used the "Fira Code Medium" font (it worked for me with other font too)
2. Open a file which has bold formatting: like Markdown
3. Type __bold__ and see it coloured, but the boldness is ever so little (it is verified in DevTools that the styling is being applied)
4. Compare with Insiders/Stable that their boldness is much thicker

Exploration 1.37:
![image](https://user-images.githubusercontent.com/30497573/60968722-b5b9bc80-a315-11e9-8658-767441230d49.png)
Insiders 1.37:
![image](https://user-images.githubusercontent.com/30497573/60968811-eac60f00-a315-11e9-8c06-0b84ed967e92.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I am not seeing a big difference for me. us
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by beastdestroyer** [comment]
Actually, I now seem to not notice a difference; perhaps it could be one of my markdown extensions I'm not exactly sure. Im gonna be off for a week so i can't confirm much but when I get time, I'll take a deeper dive

**Comment by bpasero** [comment]
ok let's close this one then.
