### ISSUE TITLE
Weird snippets suggested before obvious ones

### ISSUE THREAD

**Issue by Arrow7000** [Microsoft/vscode#7720]
- VSCode Version: 1.21
- OS Version: Windows 7 Professional

When editing JavaScript files in my project and I want to use the built in snippets like `for` and `console.log`, VSCode suggests a ton of snippets, but none of the ones I want. They're all random ones that I have never seen before, like `Performance` and `onbeforeupload`. I don't know where these snippets come from. 

![image](https://cloud.githubusercontent.com/assets/13225609/16081712/8f689380-3306-11e6-92e7-0b04e6415fb0.png)

To test this in isolation I actually created a new JS file on my desktop and it didn't have any of these random snippets and it did go directly to suggesting the pure JS snippets. 

![image](https://cloud.githubusercontent.com/assets/13225609/16081779/e104e8ec-3306-11e6-8128-97899dd6d8f2.png)

So I'm not sure what's happening here. Any suggestions would be appreciated. Thanks!

**Comment by jrieken** [comment]
VS Code shows snippet-suggestions as well as language suggestion in one window. The symbols like `Performance`, `onBefore` are suggestion computed by the JavaScript language service. Their actual type is shown by using a different icon. In you test case (2nd screen shot) you hit the unlucky case that the JavaScript language service doesn't work on unsaved/untitled buffers.

**Comment by jrieken** [comment]
We have an issue about mixing snippet suggestion with other suggestions: #2343. Closing this as a duplicate.

**Comment by Arrow7000** [comment]
Hi @jrieken, thanks for replying. But this is more complicated because in the 2nd screenshot the file *was* actually saved on my desktop - albeit under the name `Untitled-1.js`.

So I don't understand why for two JS files, in one I get a ton of random suggested autocompletions, and in the other I only get the core snippets.

**Comment by jrieken** [comment]
> In your test case (2nd screen shot) you hit the unlucky case that the JavaScript language service doesn't work on unsaved/untitled buffers.

Because of that

**Comment by Arrow7000** [comment]
Right I see. I was confused because it was saved and had a name, albeit the name was `Untitled-1.js`. But I just tried it with the identical file, only difference being a different filename and it does work as before. 

![image](https://cloud.githubusercontent.com/assets/13225609/16146983/c30a8554-3478-11e6-934e-f3a59ca61bb7.png)

At least it's consistent then but the primary problem still appears.
