### ISSUE TITLE
Electron 6: Sidebar width keeps resetting after minimising window and then opening it back

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77207]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362
Steps to Reproduce:

1. Have an editor with the sidebar open to some width that isn't the minimum width
2. Minimise the window (don't just click off the window)
3. Then open the window back - observe the sidebar is now at minimum width

You can try by minimizing and then focusing on another window, then back and the same thing happen

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
This no longer reproduces for me. @beastdestroyer can you try with latest?

**Comment by bpasero** [comment]
Ping @beastdestroyer

**Comment by beastdestroyer** [comment]
I believe I don't experience this issue anymore, at least the version with electron 6.0.7 as that's when I last updated this build
