### ISSUE TITLE
Code --list-extensions slow

### ISSUE THREAD

**Issue by fasmat** [microsoft/vscode#77201]
- VSCode Version: 1.35, 1.36
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Call ``code --list-extensions``
2. VSCode lists all extensions
3. VSCode takes > 30 seconds to return, even if no extensions are installed

I tried uninstalling all extensions, uninstalling VSCode (also deleting ``$HOME/.vscode`` and ``$HOME/.config/Code``) and upgrading to the newest version, the behavior persists.

Does this issue occur when all extensions are disabled?: N/A

**Comment by sandy081** [comment]
@bpasero Is there a way to profile the cli? It could be also that launching the cli might be taking time?

@fasmat Can you please check if it is taking same time in the UI? (Listing installed extensions)

**Comment by fasmat** [comment]
Hi sandy081,

listing extensions in the UI seems not to take longer than normally. At least when I click on the extensions icon I see all installed extensions without much delay.

**Comment by sandy081** [comment]
@fasmat Thanks. May I know the experience when you are launching VS Code from CLI?

**Comment by fasmat** [comment]
@sandy081 Of course. I am automating the provisioning of development environments using chef and serverspec. Recently I noticed that verifying our setups using serverspec took significantly longer than it used to and identified vscode as being the reason.

**Comment by sandy081** [comment]
@joaomoreno Assigning to you since @bpasero is not available. Looks spawning CLI is slow.

**Comment by joaomoreno** [comment]
Spawning CLI is fast. Shutting it down seems to be slow. @fasmat did I get it right that printing the extensions is instant... just that the process doesn't die immediately?

**Comment by fasmat** [comment]
@joaomoreno This is correct, it pretty much instantly prints all installed extensions (or none if none are installed) and then takes up to 30 seconds to return.

**Comment by joaomoreno** [comment]
Is the time pretty constant? If you measure it a couple times using `time`, are the numbers consistent?

**Comment by fasmat** [comment]
Not really, here are a few times I called it. It seems to be consistently a multiple of ~ 5 sec though:

```
real    0m20.876s
user    0m0.233s
sys     0m0.096s

real    0m15.805s
user    0m0.224s
sys     0m0.067s

real    0m25.257s
user    0m0.241s
sys     0m0.038s

real    0m20.806s
user    0m0.215s
sys     0m0.067s
```

**Comment by joaomoreno** [comment]
Interesting, I'm really out of ideas here...

**Comment by fasmat** [comment]
Anything I can do to dig deeper into the issue?

**Comment by sandy081** [comment]
Is it could be due to our telemetry flush while exiting?

**Comment by joaomoreno** [comment]
Interesting. @fasmat Can you edit the `product.json` file distributed with code and change `enableTelemetry` to `false` and see if that helps?

**Comment by fasmat** [comment]
That one change reduced the time from 20 - 30 seconds down to ~0.5 seconds!

**Comment by joaomoreno** [comment]
@sandy081 Have you seen this before?

**Comment by sandy081** [comment]
No. Based on the info here I suspected. Also I was in that code recently.

**Comment by joaomoreno** [comment]
@fasmat Is there anything special about your network setup that you can think of which could delay reaching out to our telemetry service?

**Comment by fasmat** [comment]
@joaomoreno hm... not that I know of, all outgoing ports are open, incoming connections are blocked (unless connected via vpn). But until a few weeks ago there wasn't any issue.

**Comment by joaomoreno** [comment]
Is it a work network, or a simple home network? Could you use Wireshark and detect that network connection to the telemetry service?

**Comment by joeywatts** [comment]
Simple workaround that doesn't involve modifying any files or settings: `--disable-telemetry` command line flag.

`code --list-extensions --disable-telemetry`

**Comment by dbaeumer** [comment]
Verified that this is reasonable fast on my machine.
