### ISSUE TITLE
Electron 6: Maximising window does not work

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77203]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open up Exploration
2. If the window isn't maximised, attempt to click on maximise button and see it is dysfunctional
3. To maximise it, drag to the top of the screen and let Windows do its thing
4. Observe that clicking the button again actually works

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce that. Does it reproduce when you run from a fresh user data directory? 
Can you try to run `code-exploration --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by beastdestroyer** [comment]
@bpasero  Can confirm this bug still exists

I've now noticed if I drag the window to any position on my screen and click it, it just centres the window and doesn't maximise...

**Comment by bpasero** [comment]
Are you using any special window manager software?

**Comment by beastdestroyer** [comment]
AFAIK No

**Comment by beastdestroyer** [comment]
I believe this issue has been fixed now, however I noticed the animation seems jumpy and weird, I'll check it out when I get the time to

**Comment by beastdestroyer** [comment]
From testing the stable electron 6 build, can say this issue is fixed :)
