### ISSUE TITLE
Debugger dont restarts

### ISSUE THREAD

**Issue by narendraingale** [microsoft/vscode#77200]
Issue Type: <b>Bug</b>

starting debugegr and aking some changes in code debugger doesnt gets restarts on clicking restarts even it dont stops need to restart visual studio code

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.11.6

</details>

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by narendraingale** [comment]
My launch.json is empty surprisingly

**Comment by weinand** [comment]
Without a launch configuration you won't be able to get automatic restart behavior. Please read https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited
