### ISSUE TITLE
Electron 6: Maximised window does not allow my taskbar to be shown

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77206]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362
This is another issue based off  #77203

Steps to Reproduce:

1. In Windows settings, set taskbar to hide in desktop mode
2. Maximise the window as detailed in  #77203
3. Attempt, by using mouse, to show the taskbar - observe nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> In Windows settings, set taskbar to hide in desktop mode

How do you do that?

**Comment by beastdestroyer** [comment]
@bpasero 
Right click taskbar > Taskbar settings and then toggle switch labelled "Automatically hide the taskbar in desktop mode"

**Comment by deepak1556** [comment]
@beastdestroyer I am unable to reproduce the issue with the following exploration build which is based on electron 6.0.0 , can you re-check and if its still an issue can you attach a video/gif sample with the repro steps. Thanks!

* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by beastdestroyer** [comment]
@deepak1556 That link seems to be v1.37 exploration (unless it is a new version  based off everything)
My current build is:
Version: 1.39.0-exploration (system setup)
Commit: a715df3459718a501686bd03414f69929bf6e9a2
Date: 2019-09-13T06:41:33.699Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

And to demonstrate the issue:
1. Go to Taskbar Settings and enable "Automatically hide the taskbar in desktop mode"
2. Open VScode if you haven't already
3. Observe the window take the whole screen like expected, but pressing maximise/minimise window doesn't work properly

EDIT I can confirm it was broken, but that was to be expected with an older version

**Comment by Raamakrishnan** [comment]
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

This issue still occurs for me. This maybe related to these bugs reported in electron:
https://github.com/electron/electron/issues/20635
https://github.com/electron/electron/issues/18310
https://github.com/electron/electron/pull/18321
https://github.com/electron/electron/issues/20635
