### ISSUE TITLE
Electron 6: Weird borders around fullscreen window

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77208]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Press f11 to go fullscreen
2. Observe these weird borders around the screen, which don't appear in other editions
3. Note, you may have to do it a couple times and focusing out fixes the issue
![image](https://user-images.githubusercontent.com/30497573/61050206-55db1880-a3de-11e9-8d7c-ebd3d17e7376.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@beastdestroyer and you do not see that with our current insiders?

**Comment by beastdestroyer** [comment]
@bpasero  Nope; I've repeated the steps a couple times and nothing happens

**Comment by beastdestroyer** [comment]
@bpasero @deepak1556 noticed that this issue still exists in the electron 6 stable update

I'll see if it works with a clean profile of exploration

**Comment by beastdestroyer** [comment]
![image](https://user-images.githubusercontent.com/30497573/62639677-ee11e200-b937-11e9-8e25-ed2fcea17cbd.png)
As you can see, the border still exists even with clean profile. Look aty the edges for these weird borders

**Comment by bpasero** [comment]
I think I cannot reproduce this on my Windows VM at least. 

@beastdestroyer can you make a screenshot when running in light theme, having a hard time to see the issue in your screenshots.

**Comment by beastdestroyer** [comment]
I remember not seeing this issue anymore with my last build with electron 6.0.7 on dark mode. I'll update and see if it's gone later today, thanks!
