### ISSUE TITLE
Electron 6: Native menu showing white font in dark mode

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#77205]
Version: 1.37.0-exploration (system setup)
Commit: 54c6f2047b7e26f9dd6f991d9831ead1f06964b2
Date: 2019-07-09T10:09:10.044Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Set titlebarstyle to ```native```
2. observe menu font is white
![image](https://user-images.githubusercontent.com/30497573/60968596-683d4f80-a315-11e9-8cc3-ea138186f1c0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Does not reproduce for me.

**Comment by beastdestroyer** [comment]
@bpasero i have enabled dark mode on windows 10.

Switching to light mode on Windows 10 1903 actually fixes it (or at least turning app mode to be light) probably cos Electron 6 detects dark mode is on so switches the menu; or it could be Windows's doing

**Comment by deepak1556** [comment]
Should be fixed with https://github.com/electron/electron/pull/19505

**Comment by bpasero** [comment]
@beastdestroyer is it better when you update to latest exploration?
