### ISSUE TITLE
When you are in the Configuration menu of an Extension and you try to access the VS Code Configuration Menu, you can not access

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode#77216]
- VSCode Version: 1.36.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Access the configuration menu of any extension.

2.Then try to directly access the VS Code configuration menu from the extension menu.This will not allow access to the VS Code menu

**Comment by sandy081** [comment]
@COD3BREAK3R What do you mean by configuration menu? Can you please provide some screenshots to see what they are?

**Comment by COD3BREAK3R** [comment]
> What do you mean by configuration menu? Can you please provide some screenshots to see what they are?

If you are on any extension which has configuration options, (for example the monokai theme) you can access it by right clicking / configure extension options, once inside the extension menu try to access the VS Code configuration and you can see that the VS Code configuration menu does not open

**Comment by sandy081** [comment]
Looks related to menus.

**Comment by COD3BREAK3R** [comment]
> Looks related to menus.

Before in VS Code 1.35 this did not happen if I remember correctly.
Also this happens with any extension, not only with Mokai or extensions of themes, you can try with any extension even if you do not have configuration options such as Spanish Language Pack and it will happen in the same way, even with extensions that do not change the appearance, for example CSS Peek which has configuration options.

**Comment by sbatten** [comment]
@COD3BREAK3R maybe I am misunderstanding. I am not sure what you mean by "access the VS configuration"

Can you provide screenshots with your steps?
