### ISSUE TITLE
Search Panel UX: Allow keyboard-only show result without moving focus

### ISSUE THREAD

**Issue by abierbaum** [Microsoft/vscode#7721]
I think the usability of the side search panel could be improved significantly by allowing one simple addition for keyboard only case.

When I want to search across the entire project to find some items of interest, if first put the search text into the search panel, then have the search run.  When then trying to go to the results to see which ones I want to take action on:

When using mouse:  
  - click on a find result to jump to that location in the file within the active panel view
  - click on file name to expand/close the finds within that file

With keyboard:
   - user can use arrows to move through the list
   - user can use spacebar to expand/close file of results
   - user can hit enter to open file to the result  (this switches focus to the file panel)

There is no way with the keyboard to show the result in the panel but not move focus.  (ie. I can't use keyboard to rapidly go through the results, opening them for context, and then moving on to next one in the list)

Suggestion: all user to press spacebar when on a search result to have the system open the search result in the file panel but *not* change focus over to the file panel.

This would keep the action consistent with using spacebar to expand/contract fille results and would allow the user to still use enter to jump into it.

**Comment by sandy081** [comment]
@bpasero Here is the request to use keyboard for same functionalities as with mouse. Similar to https://github.com/Microsoft/vscode/issues/7183

**Comment by abierbaum** [comment]
@sandy081 If you (or anyone) can point me to the source file that handles these interactions I could give a try at providing a PR with the change. Alternatively is it possible to write an extension that would override the interactions in this panel?

**Comment by sandy081** [comment]
@abierbaum Really appreciate your interest on this. We use tree navigation (similar to Search results) in multiple places like Explorer, Problems view. Behavior has to be consistent across all. 

Here are some code references:

**Comment by abierbaum** [comment]
@sandy081 Thanks for the pointers.  I took a look and realize it would take longer than I thought so I may have to delay this.  In the meantime if anyone with more experience with the code could add this change, I think many keyboard users would appreciate it.

**Comment by sandy081** [comment]
fixed by dfa1a20878aef4ab031ccccc481a014a9cf6b5b3

**Comment by abierbaum** [comment]
@sandy081 Thanks!!!
