### ISSUE TITLE
vscode can't restore if it crashed in zen mode

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode#77211]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open a folder and then go into zen-mode,
2. Kill the vscode process
3. reopen the vscode

**Comment by isidorn** [comment]
Can not reproduce.
@DFVSQY  Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by DFVSQY** [comment]
@isidorn Hi, this bug still exist, like below:
![image](https://user-images.githubusercontent.com/8075421/62181580-53893000-b386-11e9-9fa1-776013e1727b.png)
And i can't toggle off zen-mode.

**Comment by isidorn** [comment]
Just F1  > toggle zen mode
Or F1 > toggle centered editor layout
