### ISSUE TITLE
Not able to select Python interpreter

### ISSUE THREAD

**Issue by Killer-I** [microsoft/vscode#77212]
Issue Type: <b>Bug</b>

No 'Python: Select Interpreter' options showing. Followed below doc.
https://code.visualstudio.com/docs/python/environments

Not able to select environment for python.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.87GB (0.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details>Extensions: none

**Comment by deitry** [comment]
> Extensions: none 
Did you install Python extension? It contributes all Python functionality

**Comment by Killer-I** [comment]
I installed the extension and now I am getting that option.

Thank You for the quick response.

**Comment by efroim102** [comment]
@Killer-I If this resolved the issue, please close.
