### ISSUE TITLE
Ctrl + S in CSS files sends the cursor to the last line of the document and pressing Ctrl + Z focuses the view at the end of the document. You need to press Ctrl + Z like 3 times to undo changes

### ISSUE THREAD

**Issue by COD3BREAK3R** [microsoft/vscode#77217]
- VSCode Version: 1.36.1
- OS Version: Windows 10 1803

Steps to Reproduce:

1. Save changes in a CSS file by pressing Ctrl + S, this will send the cursor to the end of the document.

2. Try to undo changes by pressing Ctrl + Z and this will cause the view to be placed at the end of the document, another error is that you need to press Ctrl + Z at least 3 times to undo changes.

Note: I have tried to disable all the extensions and it happens in the same way.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
If you set `"editor.formatOnSave": false`, does it still repro?

We don't bundle any formatters for CSS though, so this is very strange. Are you sure you were running code with `code --disable-extensions`?

**Comment by COD3BREAK3R** [comment]
I have tried to disable all code formatters and disable all extensions and the error still occurs, however I will try again to confirm.

**Comment by COD3BREAK3R** [comment]
> If you set `"editor.formatOnSave": false`, does it still repro?
> 
> We don't bundle any formatters for CSS though, so this is very strange. Are you sure you were running code with `code --disable-extensions`?

I have tried to disable all code formatters and disable all extensions and the error still occurs, however I will try again to confirm.

**Comment by octref** [comment]
If you can still repro, please open a new issue with information. Thanks!
