### ISSUE TITLE
code --list-extensions by category

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#77220]
Just like I can do `@installed @category:themes` in the Extensions Search Bar, I want something like `code --list-extensions @category:themes` which will only list installed themes.

It comes handy to copy all the installed themes rather than manually entering them one by one.

Same with other categories would be cool :)

**Comment by lramos15** [comment]
@deadcoder0904 I made a PR with a simple implementation of this, it proposes that you would do `code --list-extensions --category themes` to get just your themes extensions.

**Comment by deadcoder0904** [comment]
Thanks, @lramos15 that was fast
