### ISSUE TITLE
Drag files into vscode, it should auto copying the files into folder

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#77225]
Issue Type: <b>Feature Request</b>

1. I copied  files Ctrl+C from outside, Ctrl+V into the vscode, which should be automatically saved to the appropriate directory.

2. I drag files from outside into vscode's specified directory, it should be automatically copied to the specified directory.

the function like eclipse,idea. 
![3](https://user-images.githubusercontent.com/11532015/61065278-ef81e480-a435-11e9-9ac9-0fa3f6d9c448.gif)

but vscode can not copy it 
![5](https://user-images.githubusercontent.com/11532015/61065534-746cfe00-a436-11e9-94a0-8697aa4e9b8c.gif)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexzshl** [comment]
drag file to paste is working in VSCode, but Ctrl+V not
