### ISSUE TITLE
TerminalVirtualProcess.start is called before Change TerminalVirtualProcess.setDimensions

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#77228]
- VSCode Version: Insiders 1.37

When implementating vscode.TerminalVirtualProcess, I've noticed that setDimensions is not called before start, which is necessary for enabling pseudo-console output using the Windows 10 APIs. (The dimensions are required before starting a psuedo console).

The only time setDimensions seems to be called at all is when the user resizes the terminal.

**Comment by Tyriar** [comment]
This is no longer valid and doesn't need verification as initialDimensions are now passed into start
