### ISSUE TITLE
Delete Key doesn't work as expected on File Explorer

### ISSUE THREAD

**Issue by danieldeveloper001** [microsoft/vscode#77224]
Issue Type: <b>Bug</b>

## Steps to Reproduce

1. Open a project folder on Visual Studio Code**.
2. Open the builtin file explorer.
3. Press delete on a file or folder.
4. A "delete" pattern will show up on the top right corner instead of performing the delete action.

** The scenario can be replicated either with extensions enabled or disabled.

## Environment 

Visual Studio Code 1.36.0
Operating System: Ubuntu Linux 18.04 LTS
Desktop: Gnome Shell 3.28.4

## Description

When trying to delete files on Visual Studio Code sidebar, via the File Explorer, the deletion key is understood as a "match pattern" instead of a "delete command".

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3813)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.42GB (2.44GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-ruby-test-adapter|con|0.6.0
vscode-test-explorer-status-bar|con|1.1.2
vsc-material-theme|Equ|29.2.0
dotnet-test-explorer|for|0.7.1
vscode-jasmine-test-adapter|hbe|1.5.0
vscode-mocha-test-adapter|hbe|2.1.2
vscode-test-explorer|hbe|2.12.1
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
rest-client|hum|0.21.3
vscode-python-test-adapter|lit|0.3.8
terraform|mau|1.3.12
azure-pipelines|ms-|1.152.0
azurerm-vscode-tools|msa|0.6.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-azureterraform|ms-|0.2.4
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
vscode-node-azure-pack|ms-|0.0.9
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
angular-karma-test-explorer|raa|1.0.3
vscode-jest-test-adapter|rtb|0.2.0
azure-iot-toolkit|vsc|2.8.0
vscode-icons|vsc|8.8.0

(5 theme extensions excluded)

</details>

**Comment by danieldeveloper001** [comment]
Below, an image that shows the actual behaviour when trying to delete a file.

![Screenshot from 2019-07-11 12-38-32](https://user-images.githubusercontent.com/29714040/61064812-d9920680-a3d8-11e9-829f-481b3d1a1855.png)

**Comment by danieldeveloper001** [comment]
Below, an image that shows the keybinding for the deletion key.

![Screenshot from 2019-07-11 12-41-34](https://user-images.githubusercontent.com/29714040/61065052-4c02e680-a3d9-11e9-847e-8676cae5cadb.png)

**Comment by usernamehw** [comment]
**1.36.0** => **1.36.1**

**Comment by danieldeveloper001** [comment]
@usernamehw, thanks for pointing out! It indeed resolves the issue, it didn't show up on my research! 
Closing this one! I'll leave the [issue link here](https://github.com/microsoft/vscode/issues/76514) for future readers.
