### ISSUE TITLE
Caracter encoding issue when comparing files

### ISSUE THREAD

**Issue by cderi** [microsoft/vscode#77229]
Issue Type: <b>Bug</b>

Here are the Steps to reproduce the issue:
Write an python utf-8 code file (File1.py), include some comment with accented chars (exemple:  # attaché ).
Make a copy of the file (File2.py).
Compare the 2 files.
The comment gets corrupted in the original file.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|1.1.1
python|ms-|2019.6.24221

</details>

**Comment by bpasero** [comment]
@cderi screenshot?

**Comment by cderi** [comment]
Ok - I had changed several things on my configuration to try to identify the issue and could not reproduce it anymore after I posted the issue. I think I found what the root cause was.

In settings, you need to set "Auto Guess Encoding".

Save a file that includes an accent (such as # Comment: é) in utf8.

When you reopen the file, vscode will get it wrong and will open the file in windows cp1252 (which you may not see ). So if you save the file after that it becomes corrupted.

So I am now thinking the issue was not triggered by comparing files (unless when you "compare with selected", the Auto Guess behaves differently, but Its unlikely).

The only remaining verification would be to confirm that it is normal that the file saved as utf8 is "guessed" cp1252 the next time you open it.
