### ISSUE TITLE
Extensions fails to start with VS Code

### ISSUE THREAD

**Issue by rajus0007** [microsoft/vscode#77223]
![export](https://user-images.githubusercontent.com/36203264/61062469-20efb580-a420-11e9-9607-69eb5b42b123.png)

- VSCode Version: 1.36
- OS Version: Arch Linux

Steps to Reproduce:

1.   My extensions are not loading while I start vscode. It happens all the time. If I click on "restart extension host" then extensions starts working.....
2.

Does this issue occur when all extensions are disabled?: Yes/No
No.

**Comment by omusavi** [comment]
I also repro this error, happens every time I open VS Code with 1.36 and 1.36.1. Kills all extensions and source control. Can confirm clicking Restart works. 

Are there any steps we can take to attach logs or something?

**Comment by alexandrudima** [comment]
@rajus0007 @omusavi You can look at the extension host log, that will show the extension that loads up before the crash. That is how you can track down which extension is most likely the culprit.

**Comment by omusavi** [comment]
@alexandrudima I tried to look at the extension host log but it wasn't even visible in the dropdown. there was an Extensions item but it was empty:
![image](https://user-images.githubusercontent.com/8106112/62980969-e097a480-bddc-11e9-9ded-49267b7ac7a9.png)

Is the log output to disk somewhere?

**Comment by rajus0007** [comment]
Can you please describe where we can find extension log ??

(Windows, Linux, Mac)

**Comment by alexandrudima** [comment]
`Developer: Open Logs Folder` will reveal the folder with all the logs. I'm not sure if the output channel drop-down is 100% correct and renders all the logs we have directly on disk.There we need to look for `exthost` logs.
