### ISSUE TITLE
error when stepping through read-only (inlined) contents

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7722]
I was stepping into my 'debugAdapter' node module (which has inlined source) when I got this:
 
![2016-06-15_15-50-12](https://cloud.githubusercontent.com/assets/1898161/16082378/59fee61c-3311-11e6-92d8-724e69a375ae.png)

So the removal of the string editor cache seems to have broken this.

Instead of introducing a new cache, why couldn't you interrogate Alex model? If he can produce this error, it should be possible to use that information upfront and avoid creating another string editor input with the same URI.

**Comment by isidorn** [comment]
Fixed by @bpasero via c423fe9, 9dede06
