### ISSUE TITLE
The last problem in the Problems panel for any given file seems to stick around (custom task)

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/vscode#77231]
## Issue Description ##

The last problem in the Problems panel, reported by a custom task, for a given file does not get cleared.

## Steps to Reproduce ##

I was actually testing a "fake" task that just dumps a file containing "problem" lines to the console (see https://github.com/dotnet/format/issues/247#issue-466546732).

**tasks.json**
```json
{
    "label": "format",
    "command": "cmd",
    "type": "process",
    "args": ["/c", "FOR /L %G IN (1,1,100) DO timeout /T 10 & type example.txt"],
    "isBackground": true,
    "problemMatcher": {
        "fileLocation": ["relative", "${workspaceFolder}"],
        "severity": "warning",
        "source": "dotnet format",
        "pattern": {
            "regexp": "^\\s+(.*)\\((\\d+),(\\d+)\\):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "message": 4,
        },
        "background": {
            "activeOnStart": true,
            "beginsPattern": "^Formatting code files in workspace\\s+'(.*)'\\.$",
            "endsPattern": "^Format complete\\.$"
        },
    }
}
```

### Step 1

I know it's a bit of hack, but the custom task and regexes seems to be doing the trick!

**example.txt**
```
Formatting code files in workspace 'C:\Users\anthony\example\Example.sln'.
  src\Example\Startup.cs(26,22): space between parentheses not required
  src\Example\Startup.cs(26,42): new line before open brace required
  src\Example\Controllers\ExampleController.cs(100,31): new line before open brace required
Format complete.
```

![image](https://user-images.githubusercontent.com/217842/61069128-a0a66180-a3d9-11e9-8424-df742ed2e4ac.png)

### Step 2

I removed a second problem from a file just to see that the problem clearing behavior works _at all_.

**example.txt**
```
Formatting code files in workspace 'C:\Users\anthony\example\Example.sln'.
  src\Example\Startup.cs(26,22): space between parentheses not required
  src\Example\Controllers\ExampleController.cs(100,31): new line before open brace required
Format complete.
```

![image](https://user-images.githubusercontent.com/217842/61069151-abf98d00-a3d9-11e9-8bf2-53e46af9dbdc.png)

### Step 3

But, removing _all_ of the problems (or the last problem) didn't clear out the problems for that file.

**example.txt**
```
Formatting code files in workspace 'C:\Users\anthony\example\Example.sln'.
Format complete.
```

![image](https://user-images.githubusercontent.com/217842/61069201-c03d8a00-a3d9-11e9-9198-6f1993aeb3e5.png)

## Expected Behavior ##

When the last "problem" for a file is removed, it should be cleared from the Problems panel.

## Actual Behavior ##

The last "problem" sticks around... forever?

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.20.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.20.0|
|EditorConfig|EditorConfig|0.13.0|
|powershell|ms-vscode|2019.5.0|
|prettier-vscode|esbenp|1.9.0|
|puppet-vscode|jpogran|0.18.1|
|remote-containers|ms-vscode-remote|0.66.0|
|remote-ssh|ms-vscode-remote|0.44.0|
|remote-ssh-edit|ms-vscode-remote|0.44.0|
|remote-ssh-explorer|ms-vscode-remote|0.44.0|
|remote-wsl|ms-vscode-remote|0.38.9|
|synthwave-vscode|RobbOwen|0.0.7|
|theme-panda|tinkertrain|1.3.0|
|vscode-docker|ms-azuretools|0.7.0|
|vscode-peacock|johnpapa|2.4.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.15.0|
|vscode-terminals|fabiospampinato|1.12.6|
|vsliveshare|ms-vsliveshare|1.0.509|
|vsliveshare-audio|ms-vsliveshare|0.1.59|
|vsliveshare-pack|ms-vsliveshare|0.3.2|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by AnthonyMastrean** [comment]
Hm. I just wrote a _real_ test task that runs as a background problem matcher and it _clears_ the last error from the file in the Problems panel.

```json
        {
            "label": "test",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "command": "dotnet",
            "args": ["watch", "--project", "${workspaceFolder}/SimpleNetQ.sln", "test"],
            "isBackground": true,
            "runOptions": {
                "runOn": "folderOpen"
            },
            "problemMatcher": {
                "fileLocation": ["absolute"],
                "severity": "error",
                "pattern": {
                    "regexp": "^\\s+at\\s+(?<test>.*\\.(?<method>.*?)\\(\\))\\s+in\\s+(?<path>.*):line\\s+(?<line>\\d+)\\s*$",
                    "message": 2,
                    "file": 3,
                    "line": 4
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^Starting test execution, please wait...$",
                    "endsPattern": "^Total tests:.*$"
                }
            }
        }

```

![auto-test](https://user-images.githubusercontent.com/217842/61157757-0facb480-a4c5-11e9-9b7e-15898c8e8130.gif)

Is it possibly the nature of my fake task that's causing problems?

**Comment by alexr00** [comment]
Using timeout causes the terminal to re-write things. When lines are re-written in the terminal, the task problem watcher can behave unexpectedly. As (unfortunately) designed.
