### ISSUE TITLE
Key bindings bug when multiple keyboards layouts configured in OS

### ISSUE THREAD

**Issue by mileusna** [Microsoft/vscode#7723]
- VSCode Version: 1.2.1
- OS Version: OS X El Capitan

Steps to Reproduce:
1. Press cmd+/ to comment the entire line using US keyboard layout
2. If you have multiple keyboards layouts in your OS X, it will zoom out the letters in editor (wrong shortcut), even if your current keyboard is US

By looking at keybindings.json I found this info for keyboard layout:
**_"For your current keyboard layout press ⌘+-"_**
The problem is, my **current keyboard layout** is US and VSCode mixed that shortcuts and use alternative shortcuts on US keyboard layout.

Of course, same will happen with other shortcuts as well which have alternative keys for other languages layouts.

This is the new bug, I haven't experienced this with previous versions.

**Comment by alexandrudima** [comment]
@mileusna VSCode caches the keyboard layouts it detects for as long as a window is open. Is your scenario switching between keyboard layouts while a VS Code window is open?

**Comment by mileusna** [comment]
@alexandrudima I investigated this now, it appears that bug depends which layout is set on **opening of VSCode**:

- If my lang is SR in OS X and I **open the VSCode**, when I switch to US (I usually do programming with US keyboard) it will use alternative shortcuts. Funny thing is that default, normal, shortcuts are active when your language is set to SR and alternative shortcuts are active when the EN is the language. It is up side down.

- If EN lang is set on VS Code open, everything works as it should. When I switch to SR language alternative shortcuts are active and when I switch to EN normal shortcuts are active.

Yes, I do switch sometimes inside VSCode to local language to enter some string with local characters, but I done that before, then switch back to EN for programing and easier access to [] {} etc. that was not the problem until latest release. Even now it works fine if you open VSC with EN, and even now VCS active different shortcuts depending on kb layout, but if you open VSC with other kb active, shortcuts are messed up.

**Comment by kristianmandrup** [comment]
I'm having the same problem...

**Comment by alexandrudima** [comment]
This is for now a limitation described in http://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts

![image](https://cloud.githubusercontent.com/assets/5047891/20052482/78e46266-a4d4-11e6-9f70-d00f9f84c1af.png)

**Comment by michaelbpaulson** [comment]
This same problem exists when attempting to define a custom keybinding.  If I start vscode in my specialized keyboard layout I am unable to make most keybinding shortcuts (constantly telling me its a different symbol for my layout).  To get around this, after reading this thread, I open VSCode with US keyboard, set my bindings, then switch my keyboard.  All works well with that work around.

Thought that might help for anyone attempting to set keybindings.

**Comment by eproxus** [comment]
@michaelbpaulson I'm in the same situation. I use a custom layout and even though it is selected VSCode doesn't handle the `Cmd+/` command correctly. Your "workaround" also works for me, but you are correct that it is a huge hassle.

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) detect correctly keyboard layout changes on OSX. The keybinding service refreshes its state (I have tried with launching VSCode under a German keyboard layout and then switching to US and `cmd+/` correctly toggles line comment).

**Comment by RicardoEPRodrigues** [comment]
It seems this bug also affects Linux.

I found that VSCode doesn't look at the active keyboard layout, but instead it looks at the first available layout.

In Ubuntu it's possible to change the order of the Input Sources or Layout and putting English US first fixed the shortcuts.

**Comment by alexandrudima** [comment]
@RicardoEPRodrigues you are correct, there are some limitations on Linux. You hint on the one that we detect the keyboard layout that X11 is aware of. i.e. the one `setxkbmap -query` returns. This and other limitations are documented here -- https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings -- if anyone has any experience in this area, PRs for these limitations are most welcome.
