### ISSUE TITLE
Run Least privilege on Mac OS/X

### ISSUE THREAD

**Issue by jakewatkins** [microsoft/vscode#77237]
On Mac OS/X - VSC seems to have a few issues when running in a least priviledge environment.
Updates constantly fail, installing extensions fail, trying to see what extensions are installed fails:
@installed results in:
Error while loading extensions.  EACCES: permission denied, open 'Users/jakewatkins/.vscode-insiders/extensions/.obsolete'

The account I use does not have admin rights.  I have to sudo or switch to my admin account to do admin stuff.
All of this works great in Windows (I run least priviledge there as well), but OS/X ironically seems to have trouble with this (OneDrive really doesnt like this).

**Comment by joaomoreno** [comment]
Did you ever run `sudo code`? This is NOT recommended and will cause files and folders to be created under root.

Please make sure to `chown Users/jakewatkins/.vscode-insiders/extensions/.obsolete` to your user.

Also, never run `sudo code` again.

**Comment by jakewatkins** [comment]
lolz - thanks.  
For clarity - Code was not run via Sudo.  It's other stuff that gets done with sudo.  For instance that chown had to be done via sudo.   And it worked.  Thanks for the help.
