### ISSUE TITLE
Deleting a file from the explorer sidebar removes it from the list even if the delete fails

### ISSUE THREAD

**Issue by TrevinAvery** [microsoft/vscode#77236]
Issue Type: <b>Bug</b>

1. Create a file named "test.txt"
1. Open it in Python with `f = open("test.txt", "w")`
1. Right click on the file in the explorer sidebar and click "Delete"
1. It will disappear from the explorer sidebar, but it will not be deleted
1. Now find the file in Windows Explorer and try to delete it
1. You will get a "File In Use" window that says "The action can't be completed because the file is open in Python"

When the delete fails in VSCode, the "File In Use" window should pop up with the same warning and then leave the file in the explorer sidebar until it is actually deleted.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.0
python|ms-|2019.1.0
cpptools|ms-|0.21.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/43819
