### ISSUE TITLE
The Terminate task command hangs Code

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/vscode#77230]
Issue Type: <b>Bug</b>

I have a single solution file and single project file and the following custom task.

```json
        {
            "label": "format",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "--project",
                "${workspaceFolder}/Example.sln",
                "format",
            ],
            "isBackground": true,
            "problemMatcher": []
        }
```

I can start this task with the command palette "Run task" and it chugs along fine. I can even re-run it and choose "Restart" in the little pop-up window.

However, if I use the command palette for "Terminate task" it hangs Code until this window is displayed:

```
[Window Title]
Visual Studio Code

[Main Instruction]
The window is no longer responding

[Content]
You can reopen or close the window or keep waiting.

[Reopen] [Keep Waiting] [Close]
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (17.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
vscode-terminals|fab|1.12.6
vscode-peacock|joh|2.4.0
puppet-vscode|jpo|0.18.1
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.0
remote-ssh-edit|ms-|0.44.0
remote-ssh-explorer|ms-|0.44.0
remote-wsl|ms-|0.38.9
vscode-remote-extensionpack|ms-|0.15.0
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.509
vsliveshare-audio|ms-|0.1.59
vsliveshare-pack|ms-|0.3.2

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@AnthonyMastrean can you try with this task? I can't reproduce the issue you're seeing.
```
        {
            "label": "Testing",
            "type": "process",
            "command": "powershell.exe",
            "args": ["-Command", "Start-Sleep", "20"],
            "isBackground": true,
            "problemMatcher":[]
        }
```

**Comment by AnthonyMastrean** [comment]
Your task terminates immediately and Code is responsive. And, of course, now my task terminates, too. I was testing it _all day_ yesterday and closed/opened Code multiple times! 😱

**Comment by alexr00** [comment]
Does the same hang happen if you run the same watch command in the integrated terminal without a task?

**Comment by AnthonyMastrean** [comment]
In the integrated terminal, Code is responsive and CTRL+C works fine to stop the task

```
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
watch : Shutdown requested. Press Ctrl+C again to force exit.
```

**Comment by alexr00** [comment]
This will mess up your terminals while the setting is set, but all you need to do to fix it is undo these settings. In you settings.json can you add:
```
	"terminal.integrated.shell.windows": "dotnet",
	"terminal.integrated.shellArgs.windows": [
		"watch",
		"--project",
		"${workspaceFolder}/Example.sln",
		"format",
	],
```
Then start an integrated terminal? Then, kill the terminal at the same time you'd kill the task by using the trash can icon.
