### ISSUE TITLE
[Open Editors] Unsaved label is misaligned

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77232]
Issue Type: <b>Bug</b>

![Screenshot (23)](https://user-images.githubusercontent.com/9638156/61069522-2398dd80-a415-11e9-96c4-e63efbda3ae2.png)

VS Code version: Code - Insiders 1.37.0-insider (46cc0a1670b7047e610aaef1bf84f1190802e9ec, 2019-07-11T05:39:42.001Z)
OS version: Windows_NT x64 10.0.18362

**Comment by misolori** [comment]
This is now fixed (and also centered the label):

![image](https://user-images.githubusercontent.com/35271042/61726681-e42c9400-ad26-11e9-9310-72d58fbd2bc5.png)

**Comment by isidorn** [comment]
@misolori thanks for fixing this!
