### ISSUE TITLE
Contributed tree's indent guide overlaps with icon

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#77240]
![image](https://user-images.githubusercontent.com/4033249/61074920-b0b84400-a3cd-11e9-9f79-b7d27b73a0ec.png)

Repro:

- Checkout a PR
- Click `Files`
- My file icon is [Ayu](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu)

Version: 1.37.0-insider
Commit: 46cc0a1670b7047e610aaef1bf84f1190802e9ec
Date: 2019-07-11T05:37:24.194Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by joaomoreno** [comment]
How can I get that view? I can't seem to get it in the Github Pull Request Extension.

**Comment by octref** [comment]
Oops I forgot to post a reply. Simply checkout a PR:

![image](https://user-images.githubusercontent.com/4033249/61897103-31e20180-aecb-11e9-8a79-2d0c4ca176c7.png)
