### ISSUE TITLE
Current open file changes without any action

### ISSUE THREAD

**Issue by giacomorebonato** [Microsoft/vscode#7724]
- VSCode Version: 1.3.0-insider
- OS Version: El Capitan

Steps to Reproduce:

1. Open many files in a project folder
2. Just keep working

The current file where I am writing, switches automatically to another one.

**Comment by eamodio** [comment]
Version 1.3.0-insider (1.3.0-insider)
57c833a81206c3d6bb99ba876e6cbafaf427b892

I am experiencing the same issue, but it not only changes the active file -- it closes the entire 2nd editor when it does it. This happens very randomly but VERY often.

**Comment by vlad-saling** [comment]
Same issue here.  El Capitan, Nightly Vscode 1.3.0-insider (1.3.0-insider). 
I work with 2 panes and suddenly one closes. Drives me crazy. I cannot track down precise steps. As @eamodio said: very random. Sometimes it seems to be tied to copy&paste, sometimes to cursor text select and sometimes to simple click.

**Comment by sandy081** [comment]
We fixed this issue yesterday already - d8de4d4695a8bcc4656405067f9ce046a9ee6f47

But due to the build issues, we did not have a nightly build yesterday. Builds are back today which is good news and today's nightly has the fix. Please upgrade to latest.

Sorry for inconvinience

**Comment by vlad-saling** [comment]
Thank you!

**Comment by rashnk** [comment]
i were working on ionic2 project, when i ctrl+s the page1.ts file content replaced with page1.html file, and showing full redlines below the text, i have to ctrl+z to revert,, 
vscode -version : 1.8.1
Node : 6.5.0

**Comment by rashnk** [comment]
![capture](https://cloud.githubusercontent.com/assets/12730428/22075096/a9769d74-ddd0-11e6-8fe3-da1330a58b9b.JPG)

see this screenshot, page1.ts has html content,, this happened when i save the file while it run by ionic serve
