### ISSUE TITLE
Task stopped working in version 1.36.1

### ISSUE THREAD

**Issue by paedocypris** [microsoft/vscode#77246]
Issue Type: <b>Bug</b>

This update broke my setup. I run a makefile in WSL to compile a fortran program, but after this last update the build does nothing, i.e., it does not run the makefile script.

The task that doesn't work anymore is this:
```
{
            "label": "build",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceFolder}\\progFolder"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "new",
                "showReuseMessage": true,
                "revealProblems": "onProblem"
            },
            "problemMatcher": {
                "owner": "fortran",
                "fileLocation": ["relative", "${workspaceFolder}\\progFolder"],
                "pattern": [
                    {
                        "regexp": "^([^\\s].*):(\\d+):(\\d+):$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                    },
                    {
                        "regexp": "^.*$",
                    },
                    {
                        "regexp": "^\\s+(.*)$",
                        "code": 1
                    },
                    {
                        "regexp": "^.*$",
                    },
                    {
                        "regexp": "^(.*):\\s+(.*)$",
                        "severity": 1,
                        "message": 2
                    }
                ],
                "source": "gfortran"
            }
        }
```
In this version, the output only shows the following line:
> Executing task: make <

Reverting to 1.35.1 does solve the issue. By now I have two local installations, a 1.36.1 and a 1.35.1, and will continue to work in the previous version until I have a solution.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.44GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
linter-gfortran|krv|2.1.1
cpptools|ms-|0.24.0
debug|web|0.23.1

</details>

**Comment by alexr00** [comment]
@paedocypris Can you try it with Insiders? I can reproduce it in stable, but not in insiders.

**Comment by alexr00** [comment]
I've narrowed it down. It only happens when the path for the cwd doesn't exist. There is an error in the console for it. A very simple example:
```
        {
            "label": "build",
            "type": "shell",
            "command": "make",
            "options": {
                "cwd": "${workspaceFolder}\\progFolder"
            }
        }
```
@Tyriar have there been a change in what happens when the cwd doesn't exist?

@paedocypris can you confirm that `"${workspaceFolder}\\progFolder"` is a real folder?

**Comment by Tyriar** [comment]
When the cwd doesn't exist it's mean to fail, it's just failed in different ways over time:

- At one point it started in some random directory (I think where the code exe was)
- Then it gave a generic exit code message
- Now (insiders) it will give a specific exit message that the cwd doesn't exist (https://github.com/microsoft/vscode/pull/76743)
