### ISSUE TITLE
Peek/ Go to won't work on split window

### ISSUE THREAD

**Issue by khariya** [microsoft/vscode#77248]
Issue Type: <b>Bug</b>

The Peek and Go to definition/declaration feature won't work on the split editor on the right half.
The same file on left half works fine.
I've tried selecting the option from context menu and with keyboard shortcut.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (8 x 1878)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|11.71GB (8.05GB free)|
|Process Argv|-n neuron/|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cortex-debug|mar|0.3.1
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
linkerscript|Zix|1.0.0

</details>

**Comment by jrieken** [comment]
Are you sure that you aren't confusing left and right? 
<img width="1263" alt="Screenshot 2019-07-12 at 07 43 22" src="https://user-images.githubusercontent.com/1794099/61105039-ecf4ae80-a478-11e9-97df-b1b1e631696a.png">

**Comment by khariya** [comment]
Restarting the system seems to have fixed the issue.
If I come across a similar situation again, I'll try to post the exact steps/scenario to reproduce it.
I'm sorry for the trouble!
