### ISSUE TITLE
Slowdown when Triple Clicking or Changing Windows

### ISSUE THREAD

**Issue by toddallen97** [microsoft/vscode#77243]
Issue Type: <b>Performance Issue</b>

This began in the 1.36.0 update, and is unresolved in 1.36.1.  The 1.35.x versions have all been working fine.  Once VSCode is launched the issue persists even after several minutes.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    91	  3600	code main
    0	   146	  1812	   window (Button.class.nut - imp-forked-Button - Visual Studio Code)
    0	    12	   112	     watcherService 
    0	    10	  5864	       console-window-host (Windows internal process)
    0	    63	  8700	     extensionHost
    0	    16	  6376	   electron-crash-reporter
    0	    74	  6824	   shared-process
    0	   152	  9632	   gpu-process
    0	    69	 12368	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Button.class.nut - imp-forked-Button - Visual Studio Code)
|    Folder (imp-forked-Button): 17 files
|      File types: nut(6) md(2) editorconfig(1) gitignore(1) test(1)
|                  builder(1) nut@feature-unit-test-refactor(1) 0(1)
|                  1(1) png(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by toddallen97** [comment]
Attached is a CPU profile where I click around to replicate the issue.

[CPU-20190711T144852.txt](https://github.com/microsoft/vscode/files/3383462/CPU-20190711T144852.txt)

**Comment by toddallen97** [comment]
> We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
> * Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
> * Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

The Explorer version of VSCode works great! It is snappy like the previous versions have been.

**Comment by bpasero** [comment]
@toddallen97 ok good to know, how about our insiders version, just to be sure:
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by toddallen97** [comment]
The insiders version runs the same as 1.36.1 unfortunately. Slow to change windows, triple click highlighting lines, etc.

**Comment by bpasero** [comment]
Ok, looks like a regression in Electron then. We need to wait for the Electron 6 update I think.
