### ISSUE TITLE
editor.snippetSuggestions: smart

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#77253]
### What

**Requested Functionality**

Another option (e.g. `smart`) for `editor.snippetSuggestions` that will place snippets at the top _only_ if you've typed in the _exact prefix_.

**Current Functionality**

Setting this to `top` will place snippets at the top at all times when any letter typed exists in the snippet prefix. It doesn't matter where the letters exist in the snippet, as long as the typed letters are ordered properly (you could skip letters in between, for example, and the snippets would still appear). This has the effect of placing tons of snippets at the top in certain situations. See screenshot below where tons of (dummy) snippets appear before the local variable. I would prefer that a snippet only appear at the top in this case if the snippet prefix was exactly "re". Otherwise I'd want the snippet to appear inline.

### Why

I prefer my settings as shown below. This allows you to immediately tab to autocomplete a snippet and be guaranteed that the snippet is in fact what is autocompleted. If snippet suggestions were not placed at the top, there is a good chance that the quick suggestions appear before you've had a chance to tab, and the selected suggestion could be something other than the target snippet (and that unwanted suggestion would get completed instead). There is the option to turn quick suggestions off completely, but with this feature request, you get the best of both worlds  — quick suggestions AND guaranteed snippet prefix completion.

```jsonc
{
  "editor.tabCompletion": "onlySnippets",

  // TODO: `smart` option preferred here 
  "editor.snippetSuggestions": "top",
}
```

### Screenshot
<img width="1280" alt="example" src="https://user-images.githubusercontent.com/12591890/61091221-ee858e80-a406-11e9-9305-47706f61278d.png">

**Comment by jrieken** [comment]
Well, `inline` does exactly that and matches the prefixed against the current text on the line and 'perfect' matches always rank higher (sort higher up) than other matches.

**Comment by jabacchetta** [comment]
What about in situations where there are multiple perfect matches, which will produce a different autocompletion, depending on if you tab before or after the quick suggestions appear?

**Comment by jrieken** [comment]
> What about in situations where there are multiple perfect matches

Then use tab completion with value `on` and hit tab till the desired suggestion in inserted

**Comment by jabacchetta** [comment]
While not exactly what I'm looking for, I think that's definitely easy enough. And the situation I'm now describing is probably a rare occurrence that I might have only ran into once or twice.

Going to close this out. Thanks!
