### ISSUE TITLE
No suggestion from Convert to async await for this function

### ISSUE THREAD

**Issue by jeznag** [microsoft/vscode#77258]
This function does not get a convert to async function suggestion:
```
function test(callback) {
  return user.app.models.TagList.find({
    where: { userId: this.id },
    include: "tags"
  })
    .then(list => {
      if (!list.length) {
        return [];
      }
      return Promise.all(
        list.map(l => {
          if (!l.tags || l.tags.length === 0) return Promise.resolve([]);
          else return l.tags.get();
        })
      ).then(allTags => {
        let listOfTags = allTags.map(tl => {
          return tl
            .map(t => t.name || null)
            .filter(function(n) {
              return n;
            });
        });
        let flatList = Array.prototype.concat.apply([], listOfTags);
        return flatList.filter(function(item, pos) {
          return flatList.indexOf(item) === pos;
        });
      });
    })
    .catch(callback);
}
```

Running Version 1.35.1 (1.35.1)

**Comment by mjbvz** [comment]
JavaScript or TypeScript? If you extract 

```ts
user.app.models.TagList.find({
    where: { userId: this.id },
    include: "tags"
  })
```

to a variable and hover over it, what type does it have?

**Comment by jeznag** [comment]
It's Javascript. type: any

![image](https://user-images.githubusercontent.com/1034890/61277250-26b91280-a7f5-11e9-8dcc-84839c5a2681.png)

**Comment by mjbvz** [comment]
We only suggest this refactoring if we know for sure that you are working with promises. The `any` type in the hover shows that our IntelliSense doesn't know the type you are using.

Try [configuring typings](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition) for your code or [enable type checking](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript) to identify untyped code
