### ISSUE TITLE
Remote large files cannot be dragged to local

### ISSUE THREAD

**Issue by Sundayistomorrow** [microsoft/vscode#77257]
Issue Type: <b>Feature Request</b>

Remote large files cannot be dragged to local file system(can see the drag flag, but can't download,however,small files can) , I had to use rsync command in wsl to download

(note: the remote large file size about 52M)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-957.12.2.el7.x86_64

**Comment by isidorn** [comment]
This is a chrome limitation. Nothing we can do about it.
Leaving it open as an upstream
