### ISSUE TITLE
VSCode slow in scrolling 

### ISSUE THREAD

**Issue by euclimauro** [Microsoft/vscode#7726]
- VSCode Version: 1.2.1
- OS Version: el capitan

Steps to Reproduce:
1. Slow while scrolling your source code

**Comment by alexandrudima** [comment]
@euclimauro Is this happening for you with any file content, or only a specific file? Would you mind doing a CPU profile so we can find out where time is spent. Here is me doing it:

* `F1` -> Developer: Toggle Developer Tools
* Go to `Profiles` tab
* Start a new profile
* Scroll around
* Stop the profile
* Save it and attach it here

![cpuprofile](https://cloud.githubusercontent.com/assets/5047891/16110028/0113f4f2-33ac-11e6-9886-a79b8d49c1f4.gif)

**Comment by euclimauro** [comment]
Date: Thu, 16 Jun 2016 01:22:45 -0700

**Comment by alexandrudima** [comment]
@euclimauro  Something might have went wrong, did you try to attach a CPU profile at https://github.com/Microsoft/vscode/issues/7726

**Comment by euclimauro** [comment]
[CPU-20160629T160103.cpuprofile.zip](https://github.com/Microsoft/vscode/files/339542/CPU-20160629T160103.cpuprofile.zip)

**Comment by alexandrudima** [comment]
@euclimauro Thank you! It looks like most of the time is spent in painting, before a lot of time is spent in painting, a lot of time (44ms) is spent in `deltaDecorations`, so my initial thought is that you might have a file that has a high number of decorations (probably in the multiple thousands range).

Is it possible you open a file with a lot of errors and warnings, or perhaps you have an extension installed that adds a lot of decorations to the editor?

**Comment by alexandrudima** [comment]
@euclimauro Do you have a laptop with a touchscreen?

**Comment by bpasero** [comment]
@euclimauro  we just updated Electron again, was wondering if that helps you: http://code.visualstudio.com/Download#insiders

**Comment by alexandrudima** [comment]
No answer => closing
