### ISSUE TITLE
Explorer disappears

### ISSUE THREAD

**Issue by paulgeorge92** [microsoft/vscode#77268]
Issue Type: <b>Bug</b>

When I Click any option in sidebar (ex: Search or git), the explorer disappears and need to manually enable it from view->Open view and then Explorer

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sandy081** [comment]
@paulgeorge92 I cannot reproduce it. 
- Can you please provide me steps?
- Do you see any errors in the console (Help -> Toggle Developer Tools)
- Try to reproduce it by disabling all extensions
- Can you please open VS Code on a fresh user data directory using option `--user-data-dir` from command line and see if you can still repro it
