### ISSUE TITLE
German translation in git clone -> open repo dialog is nonsense

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#77267]
Issue Type: <b>Bug</b>

1. Git clone a repo
2. look at the dialog in the bottom right corner

One of the button reads "Eröffnungskurs", which would fit for something like an entry level course at university. But not for opening the repo in the current window. The old translation (1-2 versions ago) was perfectly fine.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.87GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.5
toggle-excluded-files|eam|1.6.0
EditorConfig|Edi|0.13.0
RunOnSave|eme|0.0.18
prettier-vscode|esb|1.9.0
vscode-test-explorer|hbe|2.12.1
rest-client|hum|0.21.3
vscode-docker|ms-|0.7.0
vscode-language-pack-de|MS-|1.36.2
vscode-jest|Ort|3.0.2
project-snippets|reb|0.5.0
java|red|0.46.0
vscode-coverage-gutters|rya|2.4.0
vscode-icons|vsc|8.8.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by johnliu2016** [comment]
@lukaschal, vscode localization moved to MLCP, please take a look

**Comment by lukaschal** [comment]
@AlCalzone Please what was the previous translation ?

**Comment by AlCalzone** [comment]
I'm not sure what the old one was exactly. But IMO the only logical translation is this:
![grafik](https://user-images.githubusercontent.com/17641229/62457261-b6117000-b77a-11e9-9124-31333bf36dac.png)

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by AlCalzone** [comment]
I remember that there was once a community-driven platform for the translations. Is there any possibility now to directly propose those suggestions without making issues here?

**Comment by lukaschal** [comment]
@AlCalzone Yes see more info in a link below.

https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project
