### ISSUE TITLE
Formatter not working after VS update

### ISSUE THREAD

**Issue by rahabchung** [microsoft/vscode#77262]
Issue Type: <b>Bug</b>

after clicking ALT+SHIFT+F showing a alert said no formatter, but i have installed JS-CSS Formatter

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G630 @ 2.70GHz (2 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.91GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.4.2
vscode-html-css|ecm|0.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.2.1
vscode-yaml|red|0.4.1

</details>

**Comment by rahabchung** [comment]
Oh I found 1 thing, when I click Ctrl + S to save, the html file format automatically

**Comment by octref** [comment]
When you press Ctrl+Shift+P and use "Format Document WIth...", you should see a list of formatters. What do you see?

![image](https://user-images.githubusercontent.com/4033249/61140703-c20e5880-a480-11e9-8fb1-530218f39204.png)
