### ISSUE TITLE
TSDoc tag excluded from IntelliSense

### ISSUE THREAD

**Issue by bookmoons** [microsoft/vscode#77261]
A TSDoc tag excluded from the IntelliSense display would be useful. If type declarations are used to generate the full API docs, there may be some things (eg very lengthy descriptions or examples) you want in the docs but not cluttering the small IntelliSense box.

I think it's nice to have `@remarks` in IntelliSense as a midsize extended description.

VSCode right now lists all tags, including unrecognized custom tags. So it seems to be impossible to get docs-only tags even if you defined custom tags.

```ts
/**
 * @notATag Custom tag not in standard TSDoc.
 */
export function foo(): void;
```

![foo-cropped](https://user-images.githubusercontent.com/35854232/61099836-b5aedf00-a431-11e9-8db5-c21c403a344d.png)

Possible tags `@extended` `@extendedExample`:

```ts
/**
 * Take over the specified world.
 * 
 * @param world - The world to dominate.
 * 
 * @remarks
 * Optimizes for minimum loss of life, minimum reputation harm, and maximum deviousness.
 * Leverages all available capital and human resources without remorse.
 *
 * @extended
 * The development of this procedure began with the Sumerian kings.
 * [... long history ...]
 * 
 * @extendedExample
 * // Example of error handling based on the latest best practices
 * while (!retired) {
 *   try { takeOverWorld(earth) } catch (error) {
 *     if (error instanceof InsurrectionError) squashInsurrection()
 *     else if (error instanceof CoupError) decimateCoup()
 *     else if (error instanceof GlobalThermonuclearWarError) retire()
 *     [.. long example list .. ]
 *   }
 * }
 * 
 * @beta
 */
export function takeOverWorld(world: World): void;
```

**Comment by mjbvz** [comment]
Displaying custom tags was a feature request. We show them after the important bits of intellisense that we do parse (such as types and top level descriptions) I don't think it is worth adding a setting to hide them as it's just additional information, some of which may be useful
