### ISSUE TITLE
can't open vscode on mac  macOS10.15 Beta (19A501i)

### ISSUE THREAD

**Issue by xujipm** [microsoft/vscode#77265]
- VSCode Version:  maybe latest version , after relaunch and upgrade VScode , can't open it
- OS Version: 10.15 Beta (19A501i)

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by philsherry** [comment]
Adding further info. 

![Image 10-07-2019 at 22 31](https://user-images.githubusercontent.com/272769/61144513-f27be400-a4cc-11e9-9a40-c502adefed7d.jpeg)
