### ISSUE TITLE
Support ForwardAgent In Git Over Remote SSH Connection 

### ISSUE THREAD

**Issue by mdemoret-nv** [microsoft/vscode#77264]
Issue Type: <b>Bug</b>

VS Code's git GUI does not support `ForwardAgent` when connected to a remote machine over SSH preventing pushing and pulling code via the UI.

### Repo Steps:
1. Add `Host` item in `.ssh/config` for remote connection with necessary info. Something like:
    ```
    Host remote-host
       HostName XXX.XXX.XXX.XXX
       User ubuntu
       ForwardAgent yes
    ```
    1. Make sure to include `ForwardAgent yes`
2. On local machine, verify `ssh-add -l` returns correct key
    1. It should start similar to:
    ```
    $ ssh-add -l
    4096 SHA256:<KeyHash> <EmailAddress> (RSA)
    ```
1. Connect via ssh (outside of VS Code) to remote machine specified by `Host` in step # 1 (i.e. `ssh remote-host`)
    1. Verify forwarding has worked correctly: `ssh-add -l`
        1. It should return the same value on the remote machine as it did locally in step # 2
        2. If it returns `Error connecting to agent: No such file or directory` something is not  configured correctly
1. In VS Code, open a remote connection over SSH to the same Host in step # 3
    1. Open terminal in VS Code and run `ssh-add -l`
        1. It returns `Error connecting to agent: No such file or directory` instead of the correct public key in step # 5

### Expected Behavior:
Since connecting over SSH outside of VS Code and with VS Code use the same config file `.ssh/config`, I would expect the `ForwardAgent yes` to work in both instances. However, it does not work in VS Code.

This prevents pushing any code in the VS Code Git window while using a Remote SSH Connection. Instead I have to open a separate terminal just for `git push`

**Note:** I am not an expert on SSH so this may not be the best way to show `ForwardAgent` isnt working. However, you can always test it by connecting to a remote machine and running `git pull` both in a VS Code terminal and outside VS Code and comparing the difference. For example:

**In Ubuntu terminal (Expected behavior):**
```
username@local-machine:~$ ssh remote-host
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Jul 11 21:29:21 2019 from 10.2.165.44
ubuntu@remote-host:~$ cd /path/to/workspace
ubuntu@remote-host:/path/to/workspace$ git pull
Already up-to-date.
```
**In VS Code terminal (after using Remote SSH - Connect to Host... and selecting "remote-host"):**
```
ubuntu@remote-host:/path/to/workspace$ git pull
git@gitlab.domain.com's password:
```
This should return "Already up-to-date" instead of asking for a password.

VS Code version: Code - Insiders 1.37.0-insider (46cc0a1670b7047e610aaef1bf84f1190802e9ec, 2019-07-11T06:09:12.987Z)
OS version: Linux x64 4.15.0-51-generic
Remote OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz (12 x 2664)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|31.32GB (1.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dgx1-2|
|OS|Linux x64 4.4.0-142-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2105)|
|Memory (System)|503.81GB (16.75GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.1
remote-ssh-edit|ms-|0.44.1
remote-ssh-explorer|ms-|0.44.1
remote-wsl|ms-|0.38.9
vscode-remote-extensionpack|ms-|0.15.0
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/16
