### ISSUE TITLE
Opening git changes of large package-lock.json causes hang up for several minutes 

### ISSUE THREAD

**Issue by magnattic** [microsoft/vscode#77276]
Issue Type: <b>Bug</b>

We have our package-lock.json file (~13000 lines) in git.

Trying to open the git changes of this file in VS Code does not work properly. Instead it "hangs", making it impossible to open any other changes for up to 5 minutes. This is fairly annoying, because when I review my git changes I oftentimes click the file accidentally and the I am unable to continue my git review until it finished loading the file.

I suspect this is because of the large size of the file.

After the 5 minute delay, the changes actually open and I can continue. I haven't found any way to cancel the process after starting it accidentally.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.56GB (2.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
vscode-bazel|Baz|0.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|1.23.0
bazel-code|Dev|0.1.9
gitlens|eam|9.8.5
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
vscode-nginx-conf-hint|han|0.1.0
terraform|mau|1.3.12
Angular-BeastCode|Mik|8.0.10
vscode-scss|mrm|0.6.2
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.509
debugger-for-chrome|msj|4.11.6
angular-console|nrw|8.0.7
vscode-versionlens|pfl|0.24.0
java|red|0.46.0
stylelint|shi|0.51.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0
vscode-icons|vsc|8.8.0

</details>

**Comment by rebornix** [comment]
@magnattic when you open the file directly in the editor from file explorer, does it open smoothly? I'm wondering if the time is majorly spent in diffing.

**Comment by magnattic** [comment]
Yes, I can open it normally in the editor. Only the diff causes problems.

**Comment by joaomoreno** [comment]
Any chance you can send me the file?
