### ISSUE TITLE
Why INFO level is green by default?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77277]
![demo](https://user-images.githubusercontent.com/9638156/61124455-9bb3e180-a4af-11e9-8a1b-3664a34dcfee.png)

Now that warning colors are matching with the corresponding icon, wouldn't it make sense to change INFO decoration color (squiggly & peek & overviewRuler) to match blue info icon?

**Comment by misolori** [comment]
@usernamehw what extension are you using? I agree that we should fix this as well.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

**Comment by misolori** [comment]
This is now fixed:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/35271042/61477598-81ad4f80-a944-11e9-8b58-1e7579694718.png">

FYI @sandy081
