### ISSUE TITLE
For version 1.36.1 of vs code, the jump is very slow when you click on the method in typescript

### ISSUE THREAD

**Issue by xiaodeji** [microsoft/vscode#77271]
For version 1.36.1 of vs code, the jump is very slow when you click on the method in typescript

**Comment by charliedua** [comment]
Can you please elaborate on the issue you have, 
1. What do you mean by jump is very slow?
1. clicking on a method is very vague.

Can you please provide more evidence (Screenshots, Gifs, etc.) to support the issue.

**Comment by thatguypark** [comment]
My guess would be that @xiaodeji is talking about when you Ctrl/Cmd click the method name, and it jumps to the source code for that method.

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
