### ISSUE TITLE
VS Code won't save new files

### ISSUE THREAD

**Issue by CookieCrumbles** [microsoft/vscode#77270]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I can't save any new files since the last update.
I received a new update today but that didn't resolve it.

VS Code version: Code - Exploration 1.37.0-exploration (33fdd551e0b7a9b5254883a281ea8b384fb2cd48, 2019-07-11T14:24:04.223Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.8.3
file-icons|fil|1.0.17
code-runner|for|0.9.11
gc-excelviewer|Gra|2.1.32
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|2019.5.0
hide-gitignored|npx|1.0.1
ayu|tea|0.18.0
vscode-vtools|ven|1.0.6

</details>

**Comment by charliedua** [comment]
Can you provide any **screenshots** (before and after hitting save) and more information as to **how you're trying to save** (Keyboard shortcut, file menu, etc.)

**Comment by CookieCrumbles** [comment]
Sure,

I set up the screens for you, on the left the file i try to save, on the right the folder it should go to.
I used ctrl+s to save the file, renamed it and pressed enter. You'll see that the file does not appear on the right side of the screen and thus, did not get saved.

<blockquote class="imgur-embed-pub" lang="en" data-id="a/oS2AfPi"><a href="//imgur.com/a/oS2AfPi"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by CookieCrumbles** [comment]
I'll instantly add that via the menu file-> save or file-> save as it also does not work.

**Comment by charliedua** [comment]
There is a slight chance that when you press enter then the **cursor is actually pointed at cancel** instead of save and it cancels? can you please **confirm if that is not the issue** and **try clicking the save button**. 
Moreover I tried to reproduce the issue on linux as i don't have a windows machine handy, and the **file actually saved to the targetted folder** so it might be a **OS dependent issue**, However, my windows virtual machine will be ready _in about 2 hrs and i'll try to reproduce the issue then in a windows machine_.

**Comment by CookieCrumbles** [comment]
So, it's Monday and now it works with both pressing enter or using the mouse to click save.
I swear it did not work on Thursday or Friday. I rebooted 2 or 3 times to make sure.
This is very strange.

So i'll add the info : 
`Version: 1.37.0-exploration (user setup)
Commit: 6ffec1dc69b7c657b7f1300c1a4e3be5a75b50db
Date: 2019-07-13T07:04:49.831Z
Electron: 6.0.0-beta.12
Chrome: 76.0.3809.54
Node.js: 12.0.0
V8: 7.6.303.18-electron.0
OS: Windows_NT x64 10.0.16299`
