### ISSUE TITLE
Not able to open file with mentioned name format (Earlier it was able to open)

### ISSUE THREAD

**Issue by bhavin-vadgama** [microsoft/vscode#77278]
Issue Type: <b>Bug</b>

Name file with the following format
%XXXXXX-XXXX%XXXXXXXX-XXXX-XXX-X%XXXX%XXXXXXXX%0efe8700dbs698km0000rpdo

Error:
Unable to open '%XXXXXX-XXXX%XXXXXXXX-XXXX-XXX-X%XXXX%XXXXXXXX%0efe8700dbs698km0000rpdo': Unable to read file (Error: File not found (/home/ib051/Desktop/Project/generatedDocuments/reports_on/%XXXXXX-XXXX%XXXXXXXX-XXXX-XXX-X%XXXX%XXXXXXXXfe8700dbs698km0000rpdo)).

Tried to create from the error message it says the file is already there.
Before maybe a recent update of VSCode was able to open the file with the mentioned format. 

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2757)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|11.64GB (1.47GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.4.4
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.8.5
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
todo-tree|Gru|0.0.138
beautify|Hoo|1.5.0
rainbow-csv|mec|1.1.1
git-graph|mhu|1.10.0
python|ms-|2019.6.24221
material-icon-theme|PKi|3.8.0
swdc-vscode|sof|1.1.13
gitblame|wad|2.8.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Update to 1.36.1 and then try.
