### ISSUE TITLE
Emmet balance not working with typed components

### ISSUE THREAD

**Issue by snoosmoomrik** [microsoft/vscode#77279]
- VSCode Version: 1.36.1
- VSCode Insiders Version: 1.37.0-insider
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. create typed FunctionComponent
example:
```
import React, {FunctionComponent} from 'react'

interface IProps {
}

const SomeComponent: FunctionComponent<IProps> = (props) => (
  <ul>
    <li>item</li>
  </ul>
)
````
2. put cursor on li tag
3. run command Emmet: Balance (outward)

Current behavior: nothing happening
Expected behavior: li tag selected

Same bug with  Emmet: Balance (inward).

Without `<IProps>` everything works well.

Does this issue occur when all extensions are disabled?: Yes

**Comment by samipshah100** [comment]
same her

**Comment by medeirosjoaquim** [comment]
same here

**Comment by sahilrajput03** [comment]
Yes, its not working for me too!!!

**Comment by rzhao271** [comment]
This issue occurs because the current parser attempts to parse `<IProps>` as part of the HTML tree. Closing in favour of #99896
