### ISSUE TITLE
add ability of see the prototype of an object in debug console when debugging javascript

### ISSUE THREAD

**Issue by targboss** [microsoft/vscode#77283]
browsers developer options contain the ability to see the prototype of any object in javascript but the debug console in visual studio doesn't offer this feature so please add it

**Comment by weinand** [comment]
The VS Code debug console provides access to the prototype:

<img width="711" alt="2019-07-12_16-39-15" src="https://user-images.githubusercontent.com/1898161/61136323-b98b4180-a4c3-11e9-80e3-4a9f349f9617.png">

Do you mean something else?
