### ISSUE TITLE
terminal.integrated.env.linux doesn't work for zsh

### ISSUE THREAD

**Issue by umed** [microsoft/vscode#77280]
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2

Steps to Reproduce:

1. Set default terminal to `/bin/zsh`
2. Update `terminal.integrated.env.linux` settings to:

```json
    "terminal.integrated.env.linux": {
        "IN_VSCODE": "true"
    },
```

3. Open integrated terminal
4. Check variable:

```sh
echo $IN_VSCODE
```

Actual: output is empty. Expected: `true`

Does this issue occur when all extensions are disabled?: Yes

**Comment by umed** [comment]
When I manually disabled extensions one by one to find problematic extension I disabled them all and it is still reproducing.

**Comment by umed** [comment]
Hi @Tyriar ,

Can I try to fix this problem?

**Comment by Tyriar** [comment]
This works fine for me on Insiders:

```
"terminal.integrated.shell.linux": "/bin/zsh",
"terminal.integrated.env.linux": {
  "IN_VSCODE": "true"
},
```

Also if you are trying to get whether you're in a vscode terminal you should use the `$TERM_PROGRAM` env var which gets set automatically.
