### ISSUE TITLE
Disallow nesting in config variable resolver

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#77289]
Apparently resolving a string like `"/usr/local/cuda/bin:${env:PATH:+:${env:PATH}}"` will work but it will leave the last curly brace. We should disallow this case or throw an error, etc.

See https://github.com/microsoft/vscode/issues/76849

**Comment by mjbvz** [comment]
Still seeing some odd behavior (although this may be expected)

**Repro**
1. On MacOs
1. Set:

```
"terminal.integrated.env.osx": {
  "PATH": "${env:PATH:+:${env:PATH}}"
}
```
3. Open new terminal

**Bug**

In the terminal, see:

```
(eval):1: unrecognized modifier
/etc/zshrc:7: command not found: locale
nvm:7: command not found: tr
nvm:7: command not found: tr
matb@mb-mbp16 vscode % 
```

This does not happen if I use a setting such as `"PATH": "${env:PATH:+:abc}"`

**Comment by connor4312** [comment]
Looks like that's a side effect of 'breaking' the path. Nested variables are just no longer interpolated, it's left as:

```
(eval):1: unrecognized modifier
/etc/zshrc:7: command not found: locale
/Users/connor/.oh-my-zsh/oh-my-zsh.sh:69: command not found: rm
compdump:136: command not found: mv
detect-clipboard:33: command not found: uname
nvm:7: command not found: tr
nvm:7: command not found: tr
/Users/connor/.zshrc:119: command not found: pgrep
/Users/connor/.zshrc:123: command not found: gpg-agent
/Users/connor/.zshrc:126: command not found: direnv
➜  etcd3 echo #PATH

➜  etcd3 echo $PATH
${env:PATH:+:${env:PATH}}:/Users/copeet/.cargo/bin:./node_modules/.bin
```

**Comment by rzhao271** [comment]
@connor4312 are those side effects you listed above intended side effects of the change?
If so, I see the same thing on codespaces and we can just leave this issue verified.
Otherwise, should the issue be moved to the next milestone?

**Comment by connor4312** [comment]
Yes, it's intended that variables that have nested segments are no longer replace. Previously it would have resulted in a malformed string.
