### ISSUE TITLE
All extensions appear to fail to load

### ISSUE THREAD

**Issue by LeotomasMC** [microsoft/vscode#77286]
- VSCode Version: 1.37.0-insider
- OS Version: Windows 10 Pro Insider Version 1903 Build 18931.1000

Extensions seem to have issues loading. Not sure if its the extensions itself, or VSCode, as the extensions were working fine until VSCode updated, and the extensions did not update, and many extensions are failing to load properly.
The extensions I have seen failing to load are as follows

Extension Name - Author Version

Discord Presence - Noel 3.6.0
GitHub Issues - HookyQR 0.1.2
GitHub Pull Requests - GitHub 0.9.0
HTML Preview - Thomas Haakon Townsend 0.2.5
Indent Rainbow - oderwat 7.4.0
Python - Microsoft 2019.6.24221

This is every extension I have installed, and I find it hard to think that an extension made by MS would not work as a fault of the extension. All of them fail to load. Some extra things to note is that Discord Presence and Python are able to show that they are loading on the bottom status bar. However both of them say they are loading.

Does this issue occur when all extensions are disabled?: No, but the point is that extensions don't load.

**Comment by sandy081** [comment]
@LeotomasMC Are there any errors in the console (F1->Developer Tools) ? Also see Extension Host and Window logs in Output Panel and provide to us.

Please try disabling all extensions and enabling one by one.
