### ISSUE TITLE
Can‘t preview .rst file

### ISSUE THREAD

**Issue by heyixiaoran** [Microsoft/vscode#7728]
- VSCode Version:  1.2.1
- OS Version:Windows 10 Pro Insider Preview 14342

Steps to Reproduce:

1. Install this plugin- https://marketplace.visualstudio.com/items?itemName=tht13.rst-vscode
2. Open one .rst file
3. Ctrl + P . Input " >ext: "
4. Press enter 

Show message Faild to open

**Comment by sandy081** [comment]
@heyixiaoran This is related to extension. Please file the bug in the repository of the extension - https://github.com/Microsoft/vscode/issues/7741

Thanks
