### ISSUE TITLE
With Remote SSH, uri in the WebView Panel is escaped wrongly when requested.

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#77281]
- VSCode Version: Version: 1.37.0-insider
Commit: 8fa811108f0f0524c473020ef57b6620f6c201e1
Date: 2019-07-12T09:17:10.495Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

Name: Remote - SSH (Nightly)
Version: 2019.7.15304

- OS Version: macOS High Sierra 10.13.6 (17G7024)

Steps to Reproduce:

1. Execute the following sample code of extension with Remote - SSH (Nightly) in the remote server.
2. The request of `http://127.0.0.1:3000/?file=abc` send from webview is actually `/?file%3Dabc`. `=` is escaped wrongly.

Notice that, with Remote Containers, it works well. So, please debug with Remote SSH.

```typescript
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
  const rootUrl = vscode.Uri.file(context.extensionPath)
  const disposable = vscode.commands.registerCommand('extension.helloWorld', async (args, brgs, crgs) => {
    if (!vscode.window.activeTextEditor) {
      return;
    }
    
    const panel = vscode.window.createWebviewPanel(
      'catCoding',
      'Cat Coding',
      { preserveFocus: true, viewColumn: vscode.ViewColumn.Beside },
      { enableScripts: true, localResourceRoots: [ rootUrl ],
        portMapping : [{webviewPort: 3000, extensionHostPort: 4000}]
        }
    );
    panel.webview.html = getHtml();
  });
  context.subscriptions.push(disposable);
}

function getHtml() {
	return `
<!DOCTYPE html><html>
<img src='http://127.0.0.1:3000/?file=abc' />
`
}


// this method is called when your extension is deactivated
export function deactivate() {}
```

![スクリーンショット 2019-07-12 21 40 34](https://user-images.githubusercontent.com/10665499/61128747-bd33be00-a4ed-11e9-998c-a3606a2349e4.png)

**Comment by TheMasterOfMagic** [comment]
Influenced here.
Hope this can be fixed ASAP.

**Comment by mjbvz** [comment]
Should be fixed by https://github.com/microsoft/vscode/commit/ca2eb3be062bb5d6f15788667b523557b9f33dae
