### ISSUE TITLE
No official VSCode T-Shirts available

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode#77292]
- Version of VS Code: The Latest!
- Your operating system: Male (Size L)
- List of extensions that you have installed: Arms and Hands and Voice
- What you expected to see, versus what you actually saw: I expect to see a VSCode T-Shirt, but I see some other random T-Shirt.

**Comment by sudomann** [comment]
There are over 5k open issues. Refrain from adding to that with such?

**Comment by sudomann** [comment]
Thank you
