### ISSUE TITLE
Double-clicking sometimes selects the whole line

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#77299]
Issue Type: <b>Bug</b>

Interestingly enough, I am seeing a rather peculiar bug: sometimes when double-clicking a symbol (in a C file), the whole _line_ is selected instead of just the _word_ in question. This is annoying since it means I might copy-paste more than just the word with Ctrl-C, causing problems whan pasting it.

Tested both with and without extensions enabled; I can reproduce it even without extensions (but perhaps slightly less often).

The video below illustrates what I mean.

----

To be honest, it _could_ be a hardware problem with my mouse. I seem to get the same behavior in Firefox. (?) Any ideas on how to debug a broken potentially broken mouse? :smile: 

![double_click_bug_vscode](https://user-images.githubusercontent.com/630613/61149412-c589fa00-a4e9-11e9-88d6-8cf8071dd10e.gif)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.19.0-5-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (12 x 1271)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.80GB (5.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by perlun** [comment]
I'm very certain this is actually a hardware problem. Sorry for the noise. Feel free to wrapup with some more info before we close the issue if you like.

**Comment by charliedua** [comment]
@perlun agreed, this looks like when you try to double click your mouse actulay registers a triple click, resulting in selection of the whole line. [Hardware Problem]

**Comment by perlun** [comment]
I tested with another mouse, the problem has gone away. :see_no_evil: 

I will close this now. If you want to do something more before dismissing it, feel free to reopen. Once again, sorry for the noise; I was thinking loudly... :innocent:
