### ISSUE TITLE
Chrome Debugger once again doesn't break on breakpoints in typescript with Angular 8.1

### ISSUE THREAD

**Issue by JohnGalt1717** [microsoft/vscode#77294]
Fire up a new Angular 8.1 project.
Set a break point.

Doesn't work.

Looks like all of a sudden with latest version of angular and chrome that the pathing that used to work doesn't anymore:

Here's what used to work:
```

		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome against localhost",
			"preLaunchTask": "start",
			"url": "http://localhost:5003",
			"webRoot": "${workspaceFolder}/src",
			"userDataDir": "${workspaceRoot}/.vscode/chrome",
			"runtimeArgs": [
				"--disable-session-crashed-bubble",
				"--disable-infobars",
				"--disable-session-restore",
				"--incognito"
			],
			"sourceMapPathOverrides": {
				"webpack:///./*": "${webRoot}/*",
				"webpack:///./~/*": "${webRoot}/node_modules/*"
			}
		},
```

webpack:///./* appears to be the issue but I cannot figure out what it should be now.

**Comment by roblourens** [comment]
Can you include the output of `.scripts`?

**Comment by roblourens** [comment]
This works for me:

```
"sourceMapPathOverrides": {
          "webpack:/*": "${webRoot}/*",
          "/./*": "${webRoot}/*",
          "/src/*": "${webRoot}/*",
          "/*": "*",
          "/./~/*": "${webRoot}/node_modules/*"
}
```

So it looks like angular-cli has changed the default sourcemap setup. I have updated this in vscode-recipes. Let me know if that doesn't work for you.

**Comment by dbusacca** [comment]
For me it works.

I've also had to change
`"webRoot": "${workspaceRoot}/src/app",`
to
`"webRoot": "${workspaceRoot}",`

**Comment by JohnGalt1717** [comment]
@roblourens where do I find this output?

**Comment by JohnGalt1717** [comment]
@roblourens And yes that change worked! Thanks!

**Comment by roblourens** [comment]
@JohnGalt1717 You can type `.scripts` in the debug console to see how sourcemap paths are resolved, it can help to debug these issues in the future. Glad it works!
