### ISSUE TITLE
VSCode cannot replace in multiple files

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#773]
There's SEARCH, but where is REPLACE?

**Comment by justsml** [comment]
Is anyone working on this already? ... Maybe there is a branch being worked on? ... I'm so happy VS Code is open source  :heart:

**Comment by bkbonner** [comment]
+1

**Comment by tazejin** [comment]
If you want to search in code, you press CTRL + F and on the left you can see little drop down like icon, which will expand replace feature ... or you can press CTRL + H

**Comment by SQLEmil** [comment]
+1 - Glad to see this has made the backlog! Just had to jump back into Visual Studio to do a replace in files and was disappointed to find it missing in Code.

**Comment by hecs** [comment]
+1
Essential when refactoring.

**Comment by anibalsanchez** [comment]
+1 ... recently moved from Eclipse and it's the only missing feature

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/1690

**Comment by repositorio-ultra** [comment]
Why is it that VS code limits find/replace to 999 occurences only?

**Comment by mschipperheyn** [comment]
And why does it open ALL of the files for you to manually save :-(
