### ISSUE TITLE
small square in the error message

### ISSUE THREAD

**Issue by zhuxinyishcn** [microsoft/vscode#77307]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

![image](https://user-images.githubusercontent.com/42358759/61160379-dbd18f00-a4c4-11e9-887b-0c1981db26ae.png)

Not sure what cause that and how to fix 
Thanks

**Comment by charliedua** [comment]
This issue tracker is not for **questions** please ask it [here](https://stackoverflow.com/questions/tagged/visual-studio-code)
