### ISSUE TITLE
[json] Referencing **local** JSON schema from another local schema

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode#7730]
- VSCode Version: 1.3.0-insider
- OS Version: Mac OSX (macOS 😉) 10.11.5

Steps to Reproduce:

1. Reference one JSON schema from another. Please note that I'm **not** talking about referencing a JSON schema for a given JSON document, but schema-to-schema.
2. Observe that the validation fails because the validation treats the reference as url and tries to load schema using HTTP

Small example: imagine a `schema1.json` and `schema2.json` as well as `document1.json` and `document2.json`.

`document1.json` is associated to `schema1.json` through `json.schemas` association in `.vscode/settings.json` (this should be irrelevant), similar for `...2.json` doc/schema.

`schema1.json` has a definition called `mydef`. Using this from `document1.json` works fine.

Now I'm trying to reuse definitions from `schema1.json` in `schema2.json` so that when I validate `document2.json` everything works.

In order to do so, I make a `$ref` like so:

`"$ref": "./schema1.json#definitions/mydef"`

However, validator fails on the first opening curly brace in the file, saying the following:

```
Problems loading reference './schema1.json#definitions/mydef': Unable to load schema from './schema1.json': Unable to to connect to ./schema1.json. Error: connect ECONNREFUSED 127.0.0.1:80
```

Tried using `file://` protocol with no success (I guess file protocol is meant for absolute references which is out of the question since a developer can clone source repo anywhere on any machine). It basically says `//schema1.json not found` (when simply using `file://schema1.json#...`).

Am I missing something or is this not supported? If so, are there any workarounds?

**Comment by ddotlic** [comment]
Also, though I've originally set `id` for both schemas to HTTP URLs (that - like XML schemas - do **not** represent actual live links to documents) as recommended, since this establishes base URL for relative `$ref`s elsewhere in the file, I've also tried setting `id` to the local file URLs of the files in question, with no success.

**Comment by ddotlic** [comment]
Finally, I've also tried removing `id` from both schemas, it does not help.

**Comment by ddotlic** [comment]
I can see you've added  `feature-request` tag to this, so I guess this confirms it's not working at the moment.

We should carefully evaluate how to do this because the same two schemas will also be used outside of VS Code (deployed on the site where JSON documents validated by given schemas will be loaded) and should still work (I hope it can be done) unchanged.

**Comment by aeschli** [comment]
Delivered the change to support relative $refs, as seen [here](https://spacetelescope.github.io/understanding-json-schema/structuring.html).
Resolving the relative URL also works in the workspace, just remember to save the content as the schemas are loaded from disk.

**Comment by aeschli** [comment]
Regarding the file URL: You could also have used file URL, but file URL always need to contain the full path, e.g `file://C:/data/workspace/test/myschema.schema.json`.
With the change now you can also use relative paths, which are evaluated against the location the schema was loaded.

**Comment by ddotlic** [comment]
You have got to be kidding me 😄 Already done? Since I'm on insider, I should see this tomorrow? Y'all rule!

So how should it work? When I reference another schema, do I say "./schema..." or just "/schema..."? What if schemas are deployed and loaded through HTTP? Is there a way to have one syntax work for both local files while editing in VS and also while validating while loading through HTTP?

**Comment by ddotlic** [comment]
Forgot to say but big thanks!

**Comment by aeschli** [comment]
you can write `"$ref": "other.schema.json#/definition/blue"`, or `"./other.schema.json..."`
np, you are welcome, thanks for the detailed bug report.

**Comment by ddotlic** [comment]
@aeschli Awesome, will try as soon as next build is out 😃

**Comment by ddotlic** [comment]
@aeschli FYI, works like a charm. Y'all gonna spoil us with such a quick turnaround times 😃
