### ISSUE TITLE
Visual Studio code opens two windows on launch

### ISSUE THREAD

**Issue by stuartmuyambi** [microsoft/vscode#77302]
We have written the needed data into your clipboard because it was too 
Issue Type: <b>Bug</b>

I just updated to the latest version but every time i open vs code. Two windows open up and i have to close one and use the other one. I dont know why am getting this error. Am getting this from my latest update.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.89GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.4
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
vscode-faker|dee|1.3.0
gitlens|eam|9.8.5
react-native-react-redux|EQu|2.0.3
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|1.9.0
vscode-install-vsix|fab|1.4.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.11
Python-autopep8|him|1.0.2
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
python|ms-|2019.6.24221
vsliveshare|ms-|1.0.509
heroku-command|pko|0.0.8
vscode-css-peek|pra|3.0.2
format-html-in-php|rif|1.5.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.3.1
trailing-spaces|sha|0.3.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.7
vscode-icons|vsc|8.8.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>
large to send. Please paste.

**Comment by charliedua** [comment]
to make sure it is not an hardware problem, please try these things and if the problem still persists write here.
* Try opening through terminal instead of double clicking as the I/O device might be defective.
* Check if you have a ny scripts in settings.json which opens another vscode. (these scripts are ran right after you open vscode).

**Comment by stuartmuyambi** [comment]
Just a few days ago i update to the latest version and i have been having a minor problem with my editor. When I launch it, it automatically opens up a two windows at the same time and i have to close one and use the other one. This doesnt happen when i open up with the terminal.

**Comment by charliedua** [comment]
I am very certain it is just a **hardware issue**, as the **terminal only opens one window**, however double clicking makes it open 2 windows, there is a small chance that the **I/O device is faulty** and when you try to click on VSCode it **triple clicks** it, resulting in **2 windows** opening.

**Comment by stuartmuyambi** [comment]
You were right, there was a minor issue with my Mouse. Thank you. I really do Appreciate it.
