### ISSUE TITLE
Path delimiters in file header aren't specific to remote OS

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#77303]
- VSCode Version: 1.37.0-insider (user setup)
- VSCode commit: 46cc0a1670b7047e610aaef1bf84f1190802e9ec
- Date: 2019-07-11T05:39:42.001Z
- Local OS Version: Windows 8 (Windows_NT x64 6.3.9600)
- Remote OS Version: CentOS Linux Release 7.4.1708
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a workspace with the following structure:

```
someDirectory/
    main.cpp
main.cpp
```

2. Open both `main.cpp` and `someDirectory/main.cpp` in the same editor group, and observe that the directory disambiguation uses a backslash even though it should use a forward slash. This is sometimes (but not always) true for the hover text containing the absolute path as well.

![example](https://user-images.githubusercontent.com/5044802/61152656-a621ab80-a4ae-11e9-93ab-ae3b3297a248.png)

This is similar to #76840.

**Comment by paul-alkhimov** [comment]
This also happens when I try to "Find in folder..." The path to the folder uses wrong separators:

![image](https://user-images.githubusercontent.com/631749/61359470-a5a55e00-a87c-11e9-9845-247eadce3996.png)

**Comment by isidorn** [comment]
@paul-alkhimov that is an unrelated issue, please file a seperate one. Fyi @roblourens you should use [`getSeparator`](https://github.com/Microsoft/vscode/blob/980ad1ce090d58fdac487ad376612ae6e2f23134/src/vs/platform/label/common/label.ts#L26)

@kylrth can you reproduce this with the latest vscode insiders? Sorry for the slow response I was on vacation

**Comment by kylrth** [comment]
Can reproduce on 3802a986823977ec472fc993854e1a753037fc8f

**Comment by isidorn** [comment]
Ok, thanks, assigning to next milestone to investigate.

**Comment by isidorn** [comment]
@bpasero I belive you just fixed this via https://github.com/microsoft/vscode/commit/39e60539d6414e7e38d49cfc2cde3bf80bcb8155

Thus closing.
Please let me know @kylrth if you still see the issue with Wednesday vscode insiders 
Thanks

**Comment by bpasero** [comment]
@isidorn not convinced. My change is in a if-block that only runs in web: https://github.com/microsoft/vscode/commit/39e60539d6414e7e38d49cfc2cde3bf80bcb8155#diff-593252d90cf74418d62090c425ca6048R30

**Comment by isidorn** [comment]
@bpasero was not aware of that. Reopening

**Comment by kylrth** [comment]
Yup, can reproduce on ba69d8dcccaebbfaa94906503728eb7c3e45b9c1.

**Comment by kylrth** [comment]
I've also noticed that the tooltip with the absolute path does not use the correct delimiters for some files but not all. Regardless of whether another file with the same name is open.

**Comment by isidorn** [comment]
Now we cache the file header much less agressively.
This should be fixed via https://github.com/microsoft/vscode/commit/54c3db1285e8bc0d7dac0bf7d2b79ed35d5075f6
@kylrth let me know if you still see this. Thanks!
