### ISSUE TITLE
Shortcut to keep opened tab fixed

### ISSUE THREAD

**Issue by g0d0** [microsoft/vscode#77309]
Issue Type: <b>Feature Request</b>

Actual behavior

I can search and open a file with shortcuts, but if I keep opened the file tab unfixed - without clicking over it with the mouse -  and open another file with shortcuts too, than first opened file fades away and the last takes its place.

Desire behavior

Keep first opened file and fixed with a shortcut for open next file on another tab. For dont use the mouse.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.9.0-9-amd64

**Comment by bpasero** [comment]
The command is: `workbench.action.keepEditor`

**Comment by g0d0** [comment]
I have been imagined opening file editor and keeping it unfixed until I want, but I'm doubt about if it's usual. I'll use this settings for now, I think it can solve my "problem". Thanks @bpasero
