### ISSUE TITLE
Notification Popup Cuts Off Content

### ISSUE THREAD

**Issue by JSRobertOuimet** [microsoft/vscode#77310]
Issue Type: <b>Bug</b>

1. Click on the bell icon at the bottom right
2. If no notification is present, the popup cuts off the content

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by bpasero** [comment]
@JSRobertOuimet does that reproduce with every notification?

**Comment by JSRobertOuimet** [comment]
@bpasero I don't think it matters. Once all notifications are dismissed, the resulting popup (with the text “NO NEW NOTIFICATIONS”) is not tall enough to accomodate its content.

![screenshot](https://user-images.githubusercontent.com/9955368/61185561-d2613780-a628-11e9-89f6-f584a91c7662.png)

**Comment by bpasero** [comment]
I cannot reproduce that. Anything special about your computer?

**Comment by JSRobertOuimet** [comment]
I can't think of anything unfortunately.

**Comment by bpasero** [comment]
Can you try to run out of sources to see if it reproduces reliably? https://github.com/microsoft/vscode/wiki/How-to-Contribute
