### ISSUE TITLE
Working very slow on high performance pc

### ISSUE THREAD

**Issue by samplecoder122** [microsoft/vscode#77312]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by samplecoder122** [comment]
Issue Type: <b>Performance Issue</b>

VS code started working slow today so I get bored.
The performance of pc is very good

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    78	  8828	code main
    5	    66	  4232	   shared-process
    0	   148	  8896	   gpu-process
    0	    67	  9180	   window (Issue Reporter)
    0	    14	 14252	   electron-crash-reporter
    0	   154	 14312	   window (sellyourlot.php - admin - Visual Studio Code)
    0	    62	  4828	     extensionHost
    0	    11	 14612	     watcherService 
    0	    11	  9732	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (sellyourlot.php - admin - Visual Studio Code)
|    Folder (admin): 5486 files
|      File types: jpg(1048) php(987) png(796) js(793) gif(591) html(386)
|                  css(236) txt(140) z(84) htm(40)
|      Conf files:;
```

</details>
Extensions: none

**Comment by sov1178** [comment]
The same problem is here. After upgrading to 1.36.x version the VSCode started to suffer from different freezes from fraction of a second to 1..2s long. It can freeze when typing, when navigating with arrow keys, when scrolling (with mouse wheel, as well as touchpad, and the real hell is scrolling using UP/DOWN keys). It is very annoying...

VSCode version: 1.36.1
OS: Windows 8 x64
System: Intel i7-3517U / 10GB RAM / SSD

Tried with both integrated graphics as well as NVidia GT620M with the same result.

**Comment by sov1178** [comment]
Small update. Maybe this information will be useful. I have tried VSCode v1.37.0-insiders and it performs much better.
Full version information:
> Версия: 1.37.0-insider
Фиксация: fd5985489982fe14381dd56e6f0b29c53d5f991b
Дата: 2019-07-18T14:11:10.247Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
ОС: Windows_NT x64 6.2.9200
