### ISSUE TITLE
it always blink when opened

### ISSUE THREAD

**Issue by helloyan** [microsoft/vscode#77318]
- VSCode Version: 1.36.1
- OS Version: win10 1903

Steps to Reproduce:

1. open vscode 
2. see
3. 1.33 is ok

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by bpasero** [comment]
What does that mean?

**Comment by helloyan** [comment]
![1](https://user-images.githubusercontent.com/1699033/61184290-9658c180-a67e-11e9-97b4-5df985ce6dad.gif)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by helloyan** [comment]
bug has gone under exploration edtion

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/81644
