### ISSUE TITLE
Consider making Open dialog start from folder of current file

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode#7731]
In other Microsoft code editors (VS in particular), if I do Ctrl-O, the current folder of the open dialog is automatically set to the folder that contains the current open source file. This makes it very easy to open up matching headers or related source files without doing a search through the files pane. Please consider adding this behavior.

**Comment by bpasero** [comment]
Can you try http://code.visualstudio.com/Download#insiders if it works as you want?

**Comment by jacdavis** [comment]
Thanks for the response. I tried it out and it still uses the previously opened path. Try something like this:
1) Open up a source file. Say c:\squid\squid.cs
2) Open up another source file: c:\clam\clam.cs
3) Use back to reopen squid.cs
4) Open the file open dialog. The open folder will still be on c:\clam. 

What I was suggesting is to set the open dialog's current folder to the document that currently has focus, regardless of how we arrived at that document.

**Comment by bpasero** [comment]
@jacdavis how do you open the file dialog?

**Comment by jacdavis** [comment]
Ctrl-O

**Comment by bpasero** [comment]
Thats weird, works for me. See video:

![editors](https://cloud.githubusercontent.com/assets/900690/16127475/e3bdcf1c-33fc-11e6-8287-b135d0d779b8.gif)

**Comment by jacdavis** [comment]
Interesting. That's the behavior I want but not the behavior I'm seeing. I am running on windows 10, not on Mac though. Could it be that?

**Comment by bpasero** [comment]
@jacdavis i am on Windows 10. maybe you send a video too showing the issue. Also make sure you are on the insider release (1.3.x).

**Comment by jacdavis** [comment]
It is working now on the insiders drop after a reinstall. I think the problem is the link http://code.visualstudio.com/Download#insiders still points to the released build unless you click the little link to get the insiders, so I most likely just re-downloaded the released bits.

**Comment by jacdavis** [comment]
And yes, this looks like what I was hoping for. Thanks!

**Comment by bpasero** [comment]
@jacdavis can you explain where you clicked and got the stable bits? we should fix that.
