### ISSUE TITLE
explorer.sortOrder per folder

### ISSUE THREAD

**Issue by walter-a-jablonowski** [microsoft/vscode#77324]
Make the setting explorer.sortOrder available per folder. Currently it is just per user or workspace.

I use files OR folders with numbers in front (priorities) for project management, but only in "mngm" folder. Best would be show "mixed", while "default" would be best for src folder.

**Comment by isidorn** [comment]
This is a fair feature request, however it is not currently on the plan. Thus assigning it to the backlog.

**Comment by walter-a-jablonowski** [comment]
Thanx. I would really like 2 see that feature.
