### ISSUE TITLE
Inbuilt terminal is not working and opens up a seperate window for shell.

### ISSUE THREAD

**Issue by iyashpal** [microsoft/vscode#77320]
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. In my case when i press ```ctrl+` ``` shortcut the terminal is opening in a seperate window instead of within the vscode panel. And when I close the terminal window then in the notification I am getting this message : ```The terminal process terminated with exit code: 3221225786```

Does this issue occur when all extensions are disabled?: Yes

**Comment by SupinePandora43** [comment]
do you're edited `"terminal.integrated.shell.windows"`, `"terminal.integrated.shellArgs.windows"` or something else?!

**Comment by iyashpal** [comment]
I unchecked the **Windows Enable Conpty** and it works fine.

Thanks!
