### ISSUE TITLE
Reverse debug mode indication

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#77323]
I'm writing a debug adapter for vscode, see here:  https://github.com/maziac/z80-debug
My next step would be to offer reverse debugging possibility.
So far it's working already.
However there is a major non technical "problem" with it:
As far as I can see there is no indication being in reverse debug mode.
My debug adapter, of course, can tell the difference from the program counter and stack pointer but how to visualize this to the user. 
I.e. it is very hard to tell if you are in "normal" or in reverse debugging.

And this matters because in reverse debugging not all information is trustworthy.
I.e. I can guarantee for the registers to display accurate values but not e.g. for the whole memory.

It would help a lot if some status bar would e.g. change the color in reverse debug mode. Or maybe the whole background color would change or whatever.
I would need a strong indicator to see in what mode the debugger is.

Most probably also other debug adapters would benefit from this.

**Comment by weinand** [comment]
Feature request makes sense.
For the time being you could add some textual indication to the "Stopped" event reason, e.g. a prefix "REVERSE! ".

**Comment by Trass3r** [comment]
> Feature request makes sense.

Why did it get removed then?

**Comment by weinand** [comment]
The feature request was not "removed" but just closed because there seems to be no widespread interest for it and we have no plans to work on it.

Today most of the debug extensions that support "reverse stepping" don't have a "reverse mode" but allow reverse and forward stepping at any time. So they do not seem to have a need for a mode indicator.
