### ISSUE TITLE
Dynamically discover environment variables for a project

### ISSUE THREAD

**Issue by pior** [microsoft/vscode#77337]
One of the typical dev workflow is to have the project environment setup in the terminal.
I'm talking about environment variables, set by tools like [DirEnv](https://github.com/direnv/direnv) or [DevBuddy](https://github.com/devbuddy/devbuddy).

I always start VSCode in command line, in the project, so the VSCode language tools are working since it inherits the env-vars.

But this breaks:
- when the env-vars are changed in the terminal
- when VSCode restarts for upgrade
- for people who do not want to start VSCode in console

I was wondering if it would be possible to run the language tools with env-vars dynamically loaded from the project.

Possible implementations would be:
- reading of file with the project env-vars, like `.envvars` or the DirEnv `.envrc` at the project root path
- explore projects like https://github.com/Shopify/shadowenv

**Comment by Tyriar** [comment]
This has to do with the window environment, not the integrated terminal environment.

**Comment by joaomoreno** [comment]
#15452
