### ISSUE TITLE
constantly getting error 

### ISSUE THREAD

**Issue by raushankumar27** [Microsoft/vscode#7733]
- VSCode Version: Code - Insiders 1.3.0-insider (0dba5abc3dcc0b69c04374dee90a2726dcbbdabf, 2016-06-14T07:51:29.842Z)
- OS Version: Windows_NT ia32

Steps to Reproduce:

1.it comes randomly anytime
![screenshot 12](https://cloud.githubusercontent.com/assets/9436987/16091178/275a65f8-3350-11e6-8c9f-f78a635ef34c.png)

**Comment by sandy081** [comment]
duplicates #7597
