### ISSUE TITLE
Dont jump to beginning of lines longer than screen width

### ISSUE THREAD

**Issue by sirmspencer** [microsoft/vscode#77335]
The auto horizontal scroll is great when the line is shorter than the screen width, this brings everything back into view.  However for long lines, I cannot edit the ends because every click moves horizontal scroll to the beggining and therefore the cursor off the screen.

- VSCode Version: 1.36.1
- OS Version: Ubunutu 19.04

Steps to Reproduce:

1. Have a long line of code/text (for example a long SQL command)
2. Click on a line of code that is shorter than screen width
3. scroll to the right and click towards the end of the line that is wider than screen width
4. Window moves horizontal to beginning

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@sirmspencer I am not sure I understand the issue. Here I am following your steps but I don't see the step 4 you mention:

![Kapture 2019-08-07 at 20 39 24](https://user-images.githubusercontent.com/5047891/62648644-81a4dc00-b953-11e9-825f-1e5bbf6e6fa3.gif)

**Comment by sirmspencer** [comment]
Sorry, It was an extension. I must have had a typo when I did --disablle-extensions.  vscode seems to launch even if you add an invalid parameter.
