### ISSUE TITLE
Languages firstLine-detection quietly fails if match need more than 100 characters

### ISSUE THREAD

**Issue by PerMildner** [microsoft/vscode#77332]
- VSCode Version: Version 1.36.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Create a file with a first line that is longer that 100 characters that matches a `firstLine` regexp of some language, where the regexp wants to match something at the end of the line.
As an example the `shellscript` language [defines](https://github.com/microsoft/vscode/blob/844c7f1c94c7cadb25d46fb97f0d3d4c4b66b3cc/extensions/shellscript/package.json#L17) the `firstLine` detection with:
```
"firstLine": "^#!.*\\b(bash|zsh|sh|tcsh).*|^#\\s*-\\*-[^*]*mode:\\s*shell-script[^*]*-\\*-",
```
which wants to match a `-*-` at the end of the line.
2. Open the file and observe that the language is not detected. Shortening the first line to no more than 100 characters, closing the line and opening it again, makes the language be detected.
E.g. a file name `test-file` containing the following text:
```
# -*- mode:shell-script; some-more:1; some-more:1; some-more:1; some-more:1; some-more7890123:12; -*-
#234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
#        ^10       ^20       ^30       ^40       ^50       ^60       ^70       ^80       ^90       ^100
```
will not be detected as containing `shellscript` language. Changing the final "12" to "1" brings the length down to 100 and now it _will_ be detected as `shellscript`.

Presumably this is because of the `100` at [textEditorModel.ts](https://github.com/microsoft/vscode/blob/150730fbd7082f8bc442a0b79100a83c868e846e/src/vs/workbench/common/editor/textEditorModel.ts#L109).

For Emacs-style mode lines, like the ones `shellscript` tries to detect, contain file-specific "settings", so they can be quite long. At a minimum, the magic number 100 ought to be documented.

**Comment by rebornix** [comment]
@alexandrudima any reason why we have the limit for the first line?

**Comment by alexandrudima** [comment]
I don't think we had an actual bug about this, so we have a limit only for the sake that a limit is always a good thing... Maybe we can increase it to some other larger magic number.

**Comment by PerMildner** [comment]
Unfortunately, Emacs does not use any fixed limit (in [set-auto-mode-1](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/files.el#n3235)). It uses 3000 as a limit in a related case (looking from the end of a file).

Still, something like 1000 should be more than enough. Even the current 100 would probably suffice if the limit was clearly documented. In my use case I just made the regexp a little less precise.
