### ISSUE TITLE
Git: Failed to watch .git folder when located on mapped drive

### ISSUE THREAD

**Issue by mindlessbaby** [microsoft/vscode#77345]
After update to latest version, VS Code not recognizing git repo in workspace if located on network drive.

Please note:
- Recognized git repos correctly before update.
- Running on windows Version 1.36.1

**Comment by joaomoreno** [comment]
Can you give me exact reproducing steps?

**Comment by mindlessbaby** [comment]
Problem occurs on a "mapped drive".  That is, if git repository is located on c drive, git appears to work normally.  Also note, git lens and command line works correctly on network (only git UI in VS Code doesn't recognize the repository if located on mapped drive).

Steps to reproduce?:

1) map a network drive (if C drive all is ok!)
2) open/create repository in mapped drive
3) open with vs code 
4) observe git within vsc ui not recognizing repository.

**Comment by jaszhix** [comment]
I ran into this before on previous versions. In my case, the remote network drive is a Samba share on a Linux host, and one of the directories in the workspace was not owned by the samba user. The workaround was taking ownership on the Linux host (`sudo chown -R $USER:$USER .`). Reproduced on 1.36.1, devtools console:

```
Error: EPERM: operation not permitted, stat 'z:\path\to\redacted\path'
    at Object.t.createFileSystemProviderError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1391:836)
    at l.toFileSystemProviderError (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3406:351)
    at l.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3400:89)
    at Generator.throw (<anonymous>)
    at a (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:344)
```

**Comment by joaomoreno** [comment]
@mindlessbaby Is your scenario also related to Linux?

**Comment by mindlessbaby** [comment]
> 
> 
> @mindlessbaby Is your scenario also related to Linux?

I am unaware of issues related to Linux.  To re-iterate, previous to this release, VSC Code git worked as expected with "windows network" shared drive/path.  That is, @jaszhix appears to be describing a different scenario/issue.

**Comment by jaszhix** [comment]
> That is, @jaszhix appears to be describing a different scenario/issue.

The cause might have some variation but the end result is the same, git stops working over an SMB share.

**Comment by joaomoreno** [comment]
I could repro.

**Comment by roblourens** [comment]
I can't repro this on 1.36.1. Would be great if @mindlessbaby or @jaszhix can verify the fix in our Insiders build! https://code.visualstudio.com/insiders

**Comment by jaszhix** [comment]
I'm not able to reproduce either on 1.37.0-insider. Thanks for the quick fix.

**Comment by roblourens** [comment]
Thanks for testing!
