### ISSUE TITLE
Custom keyboard shortcuts have not worked ...

### ISSUE THREAD

**Issue by Martin00001** [microsoft/vscode#77342]
Issue Type: <b>Bug</b>

Custom keyboard shortcuts have not worked with either a find input or a replace input.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Martin00001** [comment]
Hello, I would like you to edit a behavior of the inputs as well.
When a text is selected in an editor, the text appears in the input after giving either a find or replace command.

**Comment by rebornix** [comment]
@Martin00001 what's the keyboard shortcuts / commands you are trying to use?

**Comment by Martin00001** [comment]
I assigned F9 + F9 for copying and F10 + F10 for pasting.

**Comment by rebornix** [comment]
Copy/Paste command only works when the focus is in the text area.

**Comment by Martin00001** [comment]
I thank you
