### ISSUE TITLE
Variable references in shortcuts don't work with remote container

### ISSUE THREAD

**Issue by inkytonik** [microsoft/vscode#77340]
- VSCode Version: 1.36.1 and 1.37.0-insider
- Local OS Version: Mac OS 10.14.5
- Remote OS Version: Ubuntu bionic
- Remote Extension/Connection Type: Docker

Setup the following keyboard shortcut:

    {
      "key": "ctrl+shift+t",
      "command": "workbench.action.terminal.sendSequence",
      "args": { "text": "run -v ${file}\n" }
    }    

Then open a folder in a remote container. Open a file in an editor. Invoke the shortcut. Instead of the string being sent to the terminal, I get the error:

    '${file}' can not be resolved. Please open an editor.

The problem does not occur if I open the folder locally.

**Comment by Tyriar** [comment]
This works now
