### ISSUE TITLE
Breadcrumbs command to "go up/down" a folder during navigation

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#77343]
Are there any commands in VScode to navigate "up" or "down" (*a folder*, directly) in a selection in breadcrumbs? 

<img width="659" alt="Screen Shot 2019-07-13 at 7 04 55 PM" src="https://user-images.githubusercontent.com/1993919/61177354-5bcd2700-a5a1-11e9-8cf4-742b371ea6cf.png">

**Comment by jrieken** [comment]
@joaomoreno for what the command id is but pressing ArrowLeft does the job for me

**Comment by joaomoreno** [comment]
The command is actually `list.collapse`. It will collapse a node. If already collapsed, it will select the parent. Should we implement a command to simply select the parent?

**Comment by DiamondYuan** [comment]
I can do this and have i try。

**Comment by DiamondYuan** [comment]
> The command is actually `list.collapse`. It will collapse a node. If already collapsed, it will select the parent. Should we implement a command to simply select the parent?

i make a PR but not very clear about how primary work.

**Comment by joaomoreno** [comment]
Command is `list.focusParent`, you'll be able to configure a custom key binding when it's out.
