### ISSUE TITLE
Weird fade and very light colors in VS Code

### ISSUE THREAD

**Issue by aurelien-m** [microsoft/vscode#77348]
Issue Type: <b>Bug</b>

VS Code has some weird fade and very light colors with the default theme. I tried reinstalling but it dit not work. 

Very annoying and weird and couldn't find informations online, thanks in advance for the help !

![image](https://user-images.githubusercontent.com/29719028/61181595-15230f80-a629-11e9-8f68-2d1575215ada.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
php-intellisense|fel|2.3.10
code-runner|for|0.9.11
csharpextensions|jch|1.3.0
docomment|k--|0.1.8
vscode-language-pack-fr|MS-|1.36.2
mssql|ms-|1.6.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
Csharp-ASPNETCore|rah|1.11.0
aspnet-helper|sch|0.6.4
asp-net-core-vs-code-extension-pack|tem|1.0.3

</details>

**Comment by MichelDEVde** [comment]
Same for me on my main computer but on my notebook everything looks normal. This error could be related to the 1903 Window Update I recently installed on both of my machines.

**Comment by MichelDEVde** [comment]
I found a temporary workaround which works for me. If I enable the compatibility mode and set it to Windows 8, the colors are normal again. But I don't know if this works on every machine or just on mine

**Comment by aurelien-m** [comment]
> I found a temporary workaround which works for me. If I enable the compatibility mode and set it to Windows 8, the colors are normal again. But I don't know if this works on every machine or just on mine

It also works for me, thanks ! I think its a bug from Windows 10, like you said, because I also get these strange colors when I take a screenshot on one of my monitors... But the colors are still not correct on both of my monitors (one IPS and the other not IPS) with VS Code and I didn't find any other software that does this.
