### ISSUE TITLE
Custom font not working

### ISSUE THREAD

**Issue by chenz97** [microsoft/vscode#77353]
Issue Type: <b>Bug</b>

I changed to the font Monaco, everything's going on well at the beginning. However, after I reboot the machine, I find the custom font gone. Note: using Consolas is still OK.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
matlab|Gim|1.2.0
gc-excelviewer|Gra|2.1.32
sftp|lix|1.12.7
python|ms-|2019.6.24221
code-settings-sync|Sha|3.3.1
markdown-preview-enhanced|shd|0.4.3
cmake-tools|vec|1.1.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bpasero** [comment]
@chenz97 just to confirm, you changed the editor font right?

**Comment by chenz97** [comment]
Yes. My settings.json looks like:
"editor.fontFamily": "'Monaco','Consolas'"

**Comment by louzhang** [comment]
Having the same issue, I'm on VS code version 1.36.1 and same OS version.
I'm using fira code instead.
After rebooting the custom font no longer works, current work around is to reinstall the font. 
![CodeVersion](https://user-images.githubusercontent.com/33789437/61669760-3c27b400-acaf-11e9-871b-58297ab7160d.png)
![CodeSettings](https://user-images.githubusercontent.com/33789437/61669761-3c27b400-acaf-11e9-9561-88a99b013f2b.png)

**Comment by fuyunliu** [comment]
I have the same problem, I tried to change any font,vscode has no effect.

![image](https://user-images.githubusercontent.com/13273942/62408752-2e075b00-b600-11e9-8003-cf8043799f11.png)

![image](https://user-images.githubusercontent.com/13273942/62408702-63f80f80-b5ff-11e9-9bd3-7f0b2941e6c1.png)

![image](https://user-images.githubusercontent.com/13273942/62408677-0f549480-b5ff-11e9-8c9a-57cee926e2b1.png)

**Comment by alexandrudima** [comment]
I cannot reproduce. Changing the font family works for me on both Windows and Mac.

**Comment by chenz97** [comment]
> I cannot reproduce. Changing the font family works for me on both Windows and Mac.
> Do you have those fonts installed? Do they work in other software? Have you tried other font names like "Arial"?

For me I have the font "Monaco" installed, and it works perfectly in Sublime text and Notepad++. I have also tried "Consolas", and it works well in vscode. The problem seems to be related to the custom font itself, but on another computer with the same setting, the font works well.

**Comment by alexandrudima** [comment]
@chenz97 Thank you for the extra info. The font selection is happening in Chromium (VSCode is built with Electron which is based on Chromium)... The fact that this worked until a reboot indicates to me that perhaps it is some sort of environmental problem with the OS or with the machine... I don't think there is any code change I can do in VS Code to address this...

**Comment by fuyunliu** [comment]
I am very sorry, i kown the reason --> .vscode/settings.json --> `editor.fontFamily`
