### ISSUE TITLE
Find using regular expression does not recognize chinese character

### ISSUE THREAD

**Issue by fbilo** [microsoft/vscode#77357]
Issue Type: <b>Bug</b>

1. Open a file contain Chinese characters which at the head of a line or have a space character before it;
2. Ctrl + F to open find dialog, click on the '*' button to enable regular expression, then try into the pattern string \b;

Expect:
- All Chinese characters which at the head of a line  should be selected;
- All Chinese characters which have space before it should be selected;
- An English character directly behind a Chinese character (no space or any other special character between them) should not be selected;

Actual
- All Chinese characters which at the head of a line  will not be selected;
- All Chinese characters which have space before it will not be selected
- An English character directly behind a Chinese character like the character 'L' in string "中文Linux" will be selected.

![image](https://user-images.githubusercontent.com/19651809/61185265-de311600-a689-11e9-9fce-d1e4535807d6.png)
Like in this screenshot, the cycled with yellow points are characters should be selected but not; the points with blue underline are wrong selected.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (15.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.11
vscode-nuget-package-manager|jmr|1.1.6
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
csharp|ms-|1.20.0
java|red|0.46.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0

</details>

**Comment by rebornix** [comment]
We are using JavaScript regex engine which doesn't split Chinese characters and others into segments with `\b`

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/876920/61918122-26133100-af05-11e9-9b72-176e908c7b9f.png">

**Comment by rebornix** [comment]
So is PCRE, Python and Golang regex engine.
