### ISSUE TITLE
High contrast theme has a UX issue with the cursor.

### ISSUE THREAD

**Issue by envygeeks** [microsoft/vscode#77368]
- VSCode Version: 1.35.1
- OS Version: macOS latest

Steps to Reproduce:

1. Use the high contrast theme
2. Wish yourself luck trying to figure out where the cursor *actually is* 
3. Cry a little

When using the high-contrast theme, one cannot easily determine where the cursor actually is because the box around certain stuff obscures it, and a bolded left, or right side hardly points to where the cursor actually is because the old portions weight is not enough to easily determine in a sub-second like outside of high contrast themes (actually if we were highly technical the same applies to non-high contrast as well because the cursor is often too thin)

![image](https://user-images.githubusercontent.com/99763/61187584-d1d09d00-a638-11e9-9806-62000558486a.png)

**Comment by rebornix** [comment]
Can `editor.cursorStyle` and `editor.cursorWidth` help mitigate the issue?

**Comment by envygeeks** [comment]
Phased cursors throw off my view and distract me, width might help, but if I'm honest, having it the same color as the orange line above and below to indicate the split where the cursor is would provide the best indication.

**Comment by rebornix** [comment]
@envygeeks 👍 

@misolori I'll leave it to you to choose a good color ;)

**Comment by misolori** [comment]
Here's what it would look like being the same color as our focus color:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/35271042/61469039-60903300-a933-11e9-9c12-8ec0016e23d1.png">

**Comment by misolori** [comment]
What if we updated `editorBracketMatch.border` to a different color? That at least have better contrast than white on white:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/35271042/61470396-dbf2e400-a935-11e9-8c5c-5afb400a9684.png">

**Comment by envygeeks** [comment]
@misolori indeed I was able to spot the cursor almost instantly in your second example I'm :+1: on that

**Comment by misolori** [comment]
This is now fixed and will be in the next release:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/35271042/61478704-e9fd3080-a946-11e9-973e-b3b36cd1a811.png">
