### ISSUE TITLE
Terminal never works when trying to change a theme.

### ISSUE THREAD

**Issue by paragdiwan** [Microsoft/vscode#7736]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1. Open integrated terminal from vscode
2. Now try to change a theme, Terminal then never works.

**Comment by Tyriar** [comment]
@paragdiwan this should be fixed in v1.3.0

**Comment by paragdiwan** [comment]
Thank you !
