### ISSUE TITLE
Error when upgrading or installing user June 2019 on Windows 1903

### ISSUE THREAD

**Issue by erichiller** [microsoft/vscode#77360]
- VSCode Version: June 2019 update 1
- OS Version: Windows 10 , 1903

Steps to Reproduce:

1. upgrade VSCode to June 2019 update 1

Does this issue occur when all extensions are disabled?: _this was only an upgrade, the error occurs before launching_

When upgrading from May to June VSCode releases (performed yesterday, July 13) , even the progress bar is finishing up, but before the final complete / Launch VS Code checkbox, an error pops up saying `internal error failed to expand group constant`. The only noticable result I found was that there is no start menu entry. This error only occurred when upgrading or reinstalling (which I also tried) the User install (rather than the system install). When I installed the system install, it seemed to go without error.

note: this upgrade occurred on the first launch after upgrading to Windows 1903 (from 1809).

**Comment by joaomoreno** [comment]
> When I installed the system install, it seemed to go without error.

Maybe stick to the system install for now, as it seems to work best on your system. Glad to know it works that way.
