### ISSUE TITLE
Request: Add 'Restart to Update' to command palette

### ISSUE THREAD

**Issue by Phrohdoh** [microsoft/vscode#77367]
It'd be nice if, when VSCode has an update, I could trigger the restart via the command palette instead of _having_ to click on the gear in the activity bar.

**Comment by usernamehw** [comment]
With one window opened `Reload Window` should work.

**Comment by Phrohdoh** [comment]
Issuing the `Reload Window` command (even with only a single window open) does not apply the update, at least not for me.

```
Version: 1.37.0-insider
Commit: 8fa811108f0f0524c473020ef57b6620f6c201e1
Date: 2019-07-12T09:17:10.495Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by usernamehw** [comment]
Weird, it doesn't work for me either.

**Comment by usernamehw** [comment]
Although, it feels kind of nice when updates don't interrupt you.

**Comment by Phrohdoh** [comment]
I don't consider the user explicitly running a command to update an interruption.

If VSCode were to auto-apply updates on window reload I would agree, but that isn't the request in this ticket.

**Comment by usernamehw** [comment]
Looks like a duplicate of #77184

**Comment by Phrohdoh** [comment]
Indeed it is, nice find!
