### ISSUE TITLE
Resolve resolveDebugConfiguration return values when debug type changes

### ISSUE THREAD

**Issue by awschristou** [microsoft/vscode#77365]
# Request 

As an extension developer, I'd like to be able to define a custom debug type / `DebugConfiguration`, and have `resolveDebugConfiguration` resolve to a different debug type. Currently, a custom `resolveDebugConfiguration` handler can return a `DebugConfiguration` object with a different type, but this configuration is not resolved through VS Code before it is run.

(cc: @roblourens , @weinand )

# Motivation

I'm developing an extension that allows users to develop and debug serverless applications. I'd like to provide debug support using the Debug panel of VS Code. My thought is that users would set up launch.config to reference their application's serverless manifest file. The manifest file knows the details required to run the application (code location, function handler to launch, etc), as well as whether the application is written in node, python, or c#. My extension would resolve this information from the manifest, and launch the appropriate debugger for the serverless application.

# Sample

Here is a small example of a custom debug type that passes through a different config type

In extension activate:
```
    vscode.debug.registerDebugConfigurationProvider(
        'mydebugtype',
        new MyDebugConfigProvider(),
    )
```

The declarations:
```
interface MyDebugConfig extends vscode.DebugConfiguration {
    config: vscode.DebugConfiguration
}

class MyDebugConfigProvider implements vscode.DebugConfigurationProvider {

    public async resolveDebugConfiguration(
        folder: vscode.WorkspaceFolder | undefined, 
        debugConfiguration: MyDebugConfig, 
        token?: vscode.CancellationToken
    ): Promise<vscode.DebugConfiguration | undefined> {
        return debugConfiguration.config
    }
}
```

In launch.json:
```
        {
            "type": "mydebugtype",
            "request": "launch",
            "name": "My Sample Debug",
            "config": {
                "name": "My Sample Debug",
                "type": "node",
                "request": "launch",
                "program": "${workspaceFolder}/app.js",
                "protocol": "inspector"
            }
        },
        {
            "name": "Regular Sample Debug",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/app.js",
            "protocol": "inspector"
        }
```

In this example, running `Regular Sample Debug` works as expected. `My Sample Debug` contains the same payload as `Regular Sample Debug` in the `config` property. When I run `My Sample Debug`, I would expect my configuration provider to launder the mydebugtype config into a valid node config, which looks and behaves exactly like `Regular Sample Debug` does. The actual result in Debug Console is:
```
C:\Users\<......>\node.exe --nolazy --debug-brk=61651 app.js
(node:13544) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
```

# Alternate Workarounds Considered

1 - Register my configuration provider to first-class debug types of interest (such as 'node' and/or 'python).

I tried to register `MyDebugConfigProvider` to debug type 'node'. In launch.config, I added a custom property "X" to the configuration, where I placed all of the fields of interest to `MyDebugConfigProvider`. In `resolveDebugConfiguration`, I check for the presence of "X". If it is not present, the configuration is returned without processing or modification. If "X" is present, I perform all necessary processing, and return a DebugConfiguration object of type 'node' that is configured to run the program of interest.

Pros
* It works!

Cons
* Unsure if this is a valid approach. Is it expected that several VS Code extensions would register `DebugConfigurationProvider`s against types like 'node' or 'python'?
* When the extension is active, `MyDebugConfigProvider` runs against *all* user launch configurations for those types (eg: anything with a debug type of 'node'), even if they are debugging programs that aren't relevant to this extension (eg: even if the configuration does not contain "X"). That seems invasive.
* `MyDebugConfigProvider` has to be explicitly registered against all of the different types it is supporting
  * This appears to also require duplicate declarations in the package.json contribution points for each type, in `configurationAttributes`
* When users of my extension are setting up launch configurations, they have to set the correct debug type themselves (instructing users to set the type to a single value like "mydebugtype" reduces confusion/chance of misconfiguration)

2 - Register my configuration provider to custom type ("mydebugtype"), and explicitly call `vscode.debug.startDebugging`

Given `MyDebugConfig` from earlier, I have `resolveDebugConfiguration` call `vscode.debug.startDebugging` with the payload from `MyDebugConfig.config`. `resolveDebugConfiguration` then returns `undefined`.

Pros
* It works!

Cons
* This does not seem compatible with the spirit of `resolveDebugConfiguration`. We're halting the requested debug session from starting and spinning up an alternate one instead of taking the requested session and setting it up to run
* Unsure if there are any side effects or constraints (like a timeout limit) that come with operating from within `resolveDebugConfiguration`

**Comment by daniv-msft** [comment]
I was about to report the exact same issue. 👍
This is also a blocker for my team, and we landed on the same workaround you suggested (calling startDebugging directly). However with this solution, it seems that restarting the debug session doesn't work (the debug session never restarts).

@weinand > Could you please let us know usually how long a backlog item remains in backlog before being fixed? Is there any chance that this item might be part of an incoming release?

**Comment by connor4312** [comment]
I believe we added this behavior in the last several years, sorry this issue got lost. Let us know if you have a scenario that's not covered.
