### ISSUE TITLE
Extension Host High CPU Usage

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#77362]
Issue Type: <b>Performance Issue</b>

Here some screenshots

![Image](http://joxi.ru/BA0K5qOcMonb32?d=1)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    66	  5472	code main
    0	    49	  5473	   gpu-process
    0	   156	  5475	   window (client/routes.js — revolution2)
    0	     8	  5794	     watcherService
  103	     8	  5795	     extensionHost
    0	     8	  5802	       electron_node server.js 
    0	     8	  5862	       electron_node eslintServer.js 
    0	    16	  5864	       electron_node tsserver.js 
    0	     8	  5872	         electron_node typingsInstaller.js typesMap.js 
    0	     8	  5867	       electron_node server.js 
    0	     8	  5871	       electron_node server.js 
    0	     8	  6237	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5795
    0	    41	  5797	   shared-process
    2	    66	 14087	   window (Issue Reporter)
    0	     0	 14093	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (client/routes.js — revolution2)
|    Folder (revolution2): 912 files
|      File types: js(453) css(215) html(131) png(53) xml(10) json(9) ejs(9)
|                  yml(4) yaml(3) prod(2)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
markdown-checkbox|bie|0.1.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
LogFileHighlighter|emi|2.5.0
prettier-vscode|esb|1.9.0
flow-for-vscode|flo|1.1.4
vscode-gutter-preview|kis|0.19.4
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
vscode-postcss-sorting|mrm|3.0.1
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.1
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.0
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.4.1
postcss|ric|2.0.0
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.3.1
stylelint|shi|0.51.0
mdx|sil|0.1.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.7
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
