### ISSUE TITLE
autocomplete on js files replacing "console." with "this.console." and "window." with "this.window."

### ISSUE THREAD

**Issue by sam0x17** [microsoft/vscode#77370]
Issue Type: <b>Bug</b>

In my vscode installation every time I type `console.` or `window.` within a function body (not at the root level of a .js file), it gets replaced automatically with `this.console.` or `this.window.` etc. I have attached a screenshot of the autocomplete option appearing. I have no idea how to disable this and the only recourse right now is deleting the `this.` part manually. It doesn't seem to be specific to any project.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:20:56.241Z)
OS version: Linux x64 5.0.0-20-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1599)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.35GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
crystal-lang|fau|0.3.14
haml|kar|1.2.0
material-icon-theme|PKi|3.8.0
ruby|reb|0.24.0

(1 theme extensions excluded)

</details>

before typing `.` character:
![before_typing_dot](https://user-images.githubusercontent.com/1855021/61188578-35fe5b80-a64f-11e9-9e36-22170ae7c0c3.png)

after typing `.` character:
![after_typing_dot](https://user-images.githubusercontent.com/1855021/61188577-35fe5b80-a64f-11e9-9763-2aaf73a3b0e5.png)

**Comment by sam0x17** [comment]
OS is Ubuntu Budgie 19.04

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
