### ISSUE TITLE
Incorrect title order

### ISSUE THREAD

**Issue by huahuajjh** [microsoft/vscode#77374]
Issue Type: <b>Bug</b>

The markdown OUTLINE panel show incorrect md title order, eg:

```
markdown source file:
---------------------------
## 1
## 2
## 3
---------------------------

OUTLINE panel  parsing:
------------------------
## 2
## 3
## 1
------------------------

```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz (4 x 1868)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.71GB (0.80GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Try changing the sorting method in the outline view:

<img width="579" alt="Screen Shot 2019-07-19 at 5 31 08 PM" src="https://user-images.githubusercontent.com/12821956/61571793-084c5480-aa4b-11e9-92dd-330086e50bab.png">
