### ISSUE TITLE
Output Channel misbehaves after clear when null character is appended

### ISSUE THREAD

**Issue by smcenlly** [microsoft/vscode#77377]
- VSCode Version: 1.36.1 and Insiders 1.37.0
- OS Version: Windows 10, MacOS

Steps to Reproduce:

1. Create a new output channel

```
const testChannel = window.createOutputChannel('TestChannel');
testChannel.append('');
testChannel.clear();
testChannel.append('Test\u0000');
testChannel.clear();
testChannel.append('Test\u0000');
testChannel.clear();
testChannel.append('Test\u0000');
testChannel.clear();
testChannel.append('Test');
```

**Expected value:** `Test`
**Actual value:** `t`

**Comment by sandy081** [comment]
Look like this is happening only with null characters. The logger (spdlog) we use for writing output channel is skipping null characters. Is there a reason to use these in your case?

**Comment by smcenlly** [comment]
In our case, parts of our output come from user input. In this case, one of our users happened to have a null character in a string that was included in our output, which caused the problem. In both of our extensions, we now strip null characters, so the issue no longer affects us but obviously could affect other extensions.

**Comment by sandy081** [comment]
I see. Since it is in the third party library unfortunately I do not have fix from my side. 

I will see if other extensions are facing this issue in real time.

**Comment by sandy081** [comment]
Closing this for now and will reopen if needed.
