### ISSUE TITLE
keybindings are totally broken on linux. Close tabs doesn't work, keep window open doesn't work.

### ISSUE THREAD

**Issue by cottrell** [microsoft/vscode#77371]
Is there some known issue on Linux vscode? Nothing is working any more. Can not even see obvious way to reset.

**Comment by alexandrudima** [comment]
@cottrell Can you give a specific example of what is not working for you?

**Comment by cottrell** [comment]
So I think the issue is something is locking the task queue. I have a repo with a lot of submodules as the top level project. vscode really bites on this for a while. Maybe it is just hanging.
