### ISSUE TITLE
Snippets in YAML not working

### ISSUE THREAD

**Issue by nicovigil1** [microsoft/vscode#77372]
```
    "[yaml]": {
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    }
```

in settings.json, this fixed the issue for me - I guess intellisense doesn't work on strings in VScode & sees everything in yml as a string?

**Comment by jrieken** [comment]
Yes - the default config for quick suggestion is to be disabled inside comments and strings
