### ISSUE TITLE
Need a provision to switch back to editor from terminal & vice-versa.

### ISSUE THREAD

**Issue by paragdiwan** [Microsoft/vscode#7737]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 14.04

Steps to Reproduce: 

1. Open terminal & there is no way you can switch to editor. ( Need a key-binding for this)

**Comment by Tyriar** [comment]
- <kbd>ctrl</kbd>+<kbd>\`</kbd> toggles the terminal
- <kbd>ctrl</kbd>+<kbd>1</kbd> focus first editor
- <kbd>ctrl</kbd>+<kbd>2</kbd> focus second editor
- <kbd>ctrl</kbd>+<kbd>3</kbd> focus third editor

A focus terminal command is coming in v1.3.0 which will allow you to toggle the terminal without dismissing it first.
