### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by Jfhow** [microsoft/vscode#77373]
Issue Type: <b>Bug</b>

Choose Terminal--> New Terminal
When closing terminal window, get the following error:

The terminal process terminated with exit code: 3221225786

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (9.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.4.6
vsc-material-theme|Equ|29.2.0
git-graph|mhu|1.11.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
material-icon-theme|PKi|3.8.0
code-settings-sync|Sha|3.3.1
vscode-arduino|vsc|0.2.27

(1 theme extensions excluded)

</details>

**Comment by uzibutt** [comment]
You completed a few fine points there. I did a search on the subject and found nearly all persons will go along with with your blog.<a href="https://itsmyownway.com/what-is-osteoporosis-and-how-can-it-be-prevented/">top 10 orthopedic surgeons in karachi</a>

**Comment by uzibutt** [comment]
This post is very simple to read and appreciate without leaving any details out. Great work!<a href="https://www.minds.com/uzibutt/blog/what-is-primary-and-secondary-protection-with-fr-clothing-987611548035682304">FR fabric manufacturer</a>

**Comment by handsoffred** [comment]
Problem went away after two reboots. First time after reboot, default shell was changed from bash to cmd but terminal still not operable. Changed default to bash (my preference) and after reboot bash terminal works but my custom prompt is gone.
This all happened after an auto-update to vs code version 1.37.0.
Did the update mangle some sort of configuration file?
