### ISSUE TITLE
Cannot use any input method when installed from snap

### ISSUE THREAD

**Issue by notsyncing** [microsoft/vscode#77382]
Issue Type: <b>Bug</b>

Hello, I cannot input any chinese characters with ibus in vs code snap. The input method can be switched with hot keys, but won't show up when I type anything. 

Ubuntu 19.04, kernel 5.0.0-20-generic, gnome-shell 3.32.1 on wayland, ibus 1.5.19-1ubuntu2, ibus-libpinyin 1.11.0-1ubuntu0.19.04

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-20-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 1690)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|13.68GB (3.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-docker|ms-|0.7.0
vscode-language-pack-zh-hans|MS-|1.36.2
python|ms-|2019.6.24221
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6
java|red|0.46.0
rust|rus|0.6.1
vscode-lldb|vad|1.2.3
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.0

</details>

**Comment by notsyncing** [comment]
I guess this may help: https://forum.snapcraft.io/t/compatibility-with-cjkv-input-method-frameworks/7788

**Comment by palxex** [comment]
Same with me. 
I just tried snap install Kate and verified it could receive fcitx input. So it should have nothing with snappy, just VSC snap version.
My environment is Manjaro stable, also tested both `code` in pacman(the oss version) and `visual-studio-code-bin`(official deb wrapped) in AUR could also receive fcitx input.
So the problem could be isolated to the snap version ONLY. Not sure whether relative to the '--classic'.

**Comment by Tyriar** [comment]
@palxex it was an unofficial package back then, now there's a new official one.

**Comment by critical-bug** [comment]
Same with me.
Code installed with snap can't input hiragana in commit message box. ver c47d83b2 (rev 25), ver 78a4c914 (rev 26).
My environment is Fedora 31, ibus 1.5.21, ibus-mozc 2.23.2815.182.
snap is installed according to official document https://snapcraft.io/docs/installing-snap-on-fedora .
rpm-version Code can.

**Comment by alk-sramond** [comment]
Hi, i got the same issue i cannot get rid of Ubuntu 20.04 `CTRL + Shift + e` which trigger the emoji annotation (and therefor override the vscode shortcut to open file viewer).

The shortcut was removed from the system using `ibus-setup`.
![image](https://user-images.githubusercontent.com/50571972/83110952-23084480-a0c4-11ea-90b8-1f28d5f89b5f.png)
 It work anywhere else just not in VSCode. VScode was installed using `snap`.

If you need more info or have any workaround ?

**Comment by joaomoreno** [comment]
Merging into #96041
