### ISSUE TITLE
Rust: Syntax highlighting fail when using bit ops inside type parameters

### ISSUE THREAD

**Issue by ylxdzsw** [microsoft/vscode#77380]
(originally reported [here](https://github.com/rust-lang/rls-vscode/issues/623))

Currently VSCode does not recognize bit shifting punctuations inside type parameters. Example:

```rust
fn main() {
    let a = unsafe { std::mem::uninitialized::<[u8; 1<<14]>() };
    println!("{:?}", a[0])
}
```

This file is valid and can be compiled and run by `rustc`. However, vscode does not correctly render the color after `<[u8; 1<<14]>`. This is what it currently shows:

![Screenshot from 2019-07-14 12-42-58](https://user-images.githubusercontent.com/7145046/61179449-08a4b400-a635-11e9-8760-8cd6164a1638.png)

The highlighting works if I remove the bit shift operation:

![Screenshot from 2019-07-14 12-44-24](https://user-images.githubusercontent.com/7145046/61179454-2540ec00-a635-11e9-8db3-c77a5c98f135.png)

**Comment by alexr00** [comment]
Moved to owning repo.
