### ISSUE TITLE
Mac mouse click + command cannot quickly jump to a defined method or variable

### ISSUE THREAD

**Issue by CjoyHome** [microsoft/vscode#77384]
Version 1.36.1 (1.36.1)
Vue project
Mac mouse click + command cannot quickly jump to a defined method or variable and css

**Comment by CjoyHome** [comment]
I have installed the vscode-elm-jump extension
No effect

**Comment by octref** [comment]
Please include reproducible cases and report to https://github.com/vuejs/vetur.
