### ISSUE TITLE
"File to include" in Windows is case sensitive

### ISSUE THREAD

**Issue by baget** [microsoft/vscode#77392]
Issue Type: <b>Bug</b>

"File to include" in Windows is case sensitive,
if my file is *.C  and I put *.c in "File to include" it does not find the files
but if it changed to *.C it works

VS Code version: Code - Insiders 1.37.0-insider (894056d11c7fffb261a0100fd4dcbf8cff84a8c0, 2019-07-15T05:26:27.959Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (16.40GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-sqlite|ale|0.7.1
inf|bag|0.0.2
gitlens|eam|9.8.5
windows-explorer-context-menu|ele|2.0.0
vscode-diff|fab|1.4.0
asciidecorator|hel|0.2.0
rainbow-csv|mec|1.1.1
mssql|ms-|1.6.0
python|ms-|2019.6.24221
sarif-viewer|MS-|2.14.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|2019.5.0
indent-rainbow|ode|7.4.0
quicktype|qui|12.0.46
partial-diff|ryu|1.4.0
code-spell-checker|str|1.7.17
vscode-asl|Tho|1.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.7
vscode-arduino|vsc|0.2.27
vscode-icons|vsc|8.8.0
code-d|web|0.20.2

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/10633

**Comment by dmitrivMS** [comment]
This is done.
