### ISSUE TITLE
File filter/highlight in explorer misses some files

### ISSUE THREAD

**Issue by akoeplinger** [microsoft/vscode#77391]
Issue Type: <b>Bug</b>

The file highlighter which appears when you start typing in the explorer tree view misses some files.

Repro steps:
1. Extract the attached [vscodebug.zip](https://github.com/microsoft/vscode/files/3391808/vscodebug.zip) into a new folder and open it in Code
2. Start typing `.ignore` in the explorer
3. Notice how some file extensions are highlighted, while others are not
4. It seems to be inconsistent too since e.g. more files are highlighted when you just type `.ign` instead of the full word.

Screencast:
![vscode](https://user-images.githubusercontent.com/1376924/61210028-8fbc5f80-a6fb-11e9-9d19-1780a40001af.gif)

VS Code version: Code - Insiders 1.37.0-insider (894056d11c7fffb261a0100fd4dcbf8cff84a8c0, 2019-07-15T05:24:02.940Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|--disable-extensions /Users/alexander/dev/test/vscodebug|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/74133

**Comment by akoeplinger** [comment]
@jrieken since that issue talks about autocomplete in the editor context I assume this is some shared component?

For the explorer it's more annoying since the matches also affect what's shown in the file filter (when you hover over the filter text and click the "Enable Filter on Type" icon).

I often use that filter to quickly edit all files with a certain extension and if I can't be confident it shows all the files then that feature is kinda useless. Having files longer than 54 chars is not _that_ uncommon 😄
