### ISSUE TITLE
Language Specific Variable Contributions for Snippets

### ISSUE THREAD

**Issue by chriszwickerocteris** [microsoft/vscode#77395]
Snippets currently have a limited set of variables available to them. It would be very helpful to enable language specific variables to be contributed by extensions.

As an example, we may want to introduce a variable that holds the name of the method we're expanding a snippet in or offers a choice of the method names defined in a given class / file.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/10561

**Comment by chriszwickerocteris** [comment]
I understand that of course what I'm looking for can be achieved by executing a function that can be contributed by an extension.

I do wonder, though, if it wouldn't be easier for many users to have the simple case of language specific variables (which could be offered in language specific snippets' content assist) in addition to the more advanced feature of calling arbitrary functions...

I'll be happy as long as either is implemented - and happier if both are ;-)
