### ISSUE TITLE
Automatic generation for CSS, SASS, ... classes

### ISSUE THREAD

**Issue by palpatin0** [microsoft/vscode#77398]
Hello everyone! I am a web developer and mostly work with Angular, HTML and SASS. When building layouts, you have to create a SASS/CSS class parallel to the HTML class. Would it be possible to include a function that automatically creates a class in my SASS/CSS file when creating a class in my HTML code?
It would save a lot of time in development!

**Comment by aeschli** [comment]
Automatically adding stuff is IMO to aggressive, especially as we can't know in which css file you want that rule what would be a good location in that file.

But having a smarter code assist makes IMO sense: https://github.com/microsoft/vscode/issues/28442

Closing as dup
