### ISSUE TITLE
Custom theme: line number background color or border

### ISSUE THREAD

**Issue by oryam** [Microsoft/vscode#7739]
- VSCode Version: 1.2.1
- OS Version: Win 7 x64

Steps to Reproduce:
1. Open a file
2. Show line numbers in vscode settings ("editor.lineNumbers": true)
3. Line numbers are shown with a background color same as the background color of the editor area
4. It makes confusion with indent. We do not know how well the code is indented due to the margin

Suggestion:
1. Be able to customize the background color of line number area
2. Make a thin left vertical border along the editor area

**Comment by alexandrudima** [comment]
@oryam We are aware of this problem, we will soon introduce indent guides which help things here, or otherwise I use `editor.renderWhitespace` which helps in seeing where the text begins.

**Comment by oryam** [comment]
Thank you for the tip `editor.renderWhitespace`.

**Comment by drinktee** [comment]
I have the same suggestion. I think the width of the line-numbers is a little wide and maybe a waste of space. As the pic shows.
What about /(how to)  make it thinner?
![image](https://cloud.githubusercontent.com/assets/7619792/18417287/bacdafd2-785d-11e6-9ccd-4952a65e373f.png)

**Comment by alexandrudima** [comment]
@drinktee The gap is so wide to accommodate both folding indicators and git indicators:

![image](https://cloud.githubusercontent.com/assets/5047891/18434428/5ab758ec-78ed-11e6-9833-32aab350e4c9.png)

**Comment by bpasero** [comment]
@oryam how about `"editorGutter.background"` via `workbench.colorCustomizations` in settings?

Already available from our insiders release: You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

![image](https://cloud.githubusercontent.com/assets/900690/26277744/7afeec1c-3d8e-11e7-86a1-982aa8646f33.png)

**Comment by isidorn** [comment]
If I understand correctlhy @bpasero provided a solution to this, thus closing
