### ISSUE TITLE
Search all on networked drives

### ISSUE THREAD

**Issue by vandijkstef** [microsoft/vscode#77397]
Search all in larger codebases is very slow on networked drives. Not surprised offcourse, since the access to all the files is way slower. I have several (php) projects setup on my macbook with server config etc. When at home, I like to work on my desktop and connect it through network. Both machines are fully visual and running VSCode, I'm not connecting to a non-GUI server here.

What I'd like is VSCode on the desktop to hand off search-all to the local VSCode on the laptop, then the laptop reporting the results back to the desktop, because search-all locally is pretty damn fast. 

It would probably involve opening up some sort of API/local-server on VSCode, and I totally understand if this out of scope and suits better in a plugin but I lack the knowledge to create this, though I'd be happy to help in discussion, design briefing, use cases etc either way.

**Comment by roblourens** [comment]
You are basically describing VS Code Remote 😁 https://code.visualstudio.com/docs/remote

We don't support connecting to macOS yet but will some day, and then Remote - SSH is probably what you are looking for.
