### ISSUE TITLE
file change  on win 10 isnt saved

### ISSUE THREAD

**Issue by RaabenFuchs** [microsoft/vscode#77409]
Issue Type: <b>Bug</b>
maybe related: #51689

im not sure if its somehow a win10 problem, but its somehow funny, confusing:

when i save, **win explorer dosnt update the changed date and time of the file**, although i tried it with "save as"
on other software of course it works. and by hovering the coursur over the folder, it works, too

i want to **remark:**, i lost my work on the first session using VScode because a**utosave wasnt enabled** and **by closing/shutting down VSC i wasnt asked for saving** either, thats a bit bullshitty i guess ;)

_another wish:_ how about changing the file icon of files standartly used by VSC? (if you have to mess around win stuff now)

but thx for that great app

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.28.0
8051|jun|0.1.0
nc-gcode|ML|0.13.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
platformio-ide|pla|1.7.1
vscode-yaml|red|0.4.1
vscode-arduino|vsc|0.2.27

</details>

**Comment by Tyriar** [comment]
> VScode because autosave wasnt enabled and by closing/shutting down VSC i wasnt asked for saving either

@RaabenFuchs that's because hot exit backs up all the changes and presents your unsaved files the next time the folder is opened.

**Comment by RaabenFuchs** [comment]
hmmm. that wasnt the case, too bad, i think i had the same file open in arduino IDE while migrating **...** too bad :D thanks

**Comment by bpasero** [comment]
I see no issue in VSCode that we should change given https://github.com/microsoft/vscode/issues/77409#issuecomment-511473582, closing.
