### ISSUE TITLE
new behavior of File duplication not smart(file<space>copy.ext)

### ISSUE THREAD

**Issue by makeway4pK** [microsoft/vscode#77406]
Issue Type: <b>Performance Issue</b>

The new behavior of file copy pasting (ctrl+c, ctrl+v) in the proj explorer adds whitespace to the new file name, often causing command line scripts to not work. including double quotes to the script is not always easy, and many devs(probably you as well) have a habit of eliminating whites just to avoid this clumsiness.

Older behavior was much better, if not best, file.ext -> file.1.ext
plz restore it

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>Workspace Info</summary>

```
|  Window (LightStickUI.1.ino - LightStickUI - Visual Studio Code)
|  Window (Transparent_Sprite_Demo.ino - Transparent_Sprite_Demo - Visual Studio Code)
|    Folder (Transparent_Sprite_Demo): 3 files
|      File types: json(2) ino(1)
|      Conf files:
|    Folder (LightStickUI): 6 files
|      File types: json(3) ino(2) cpp(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.24.0
vscode-arduino|vsc|0.2.27

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/76752
