### ISSUE TITLE
disable context menu animation - slow on remote desktop

### ISSUE THREAD

**Issue by jkristia** [microsoft/vscode#77400]
Issue Type: <b>Bug</b>

Is there any way to disable the context, and menu, popup / slide out animation. I work mostly on remote desktop, and with the latest upgrade I noticed a slowdown in popping up the context menu when running remote desktop.
No issues with scrolling and editing, only the popup animation is slow.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sbatten** [comment]
Is the performance improved when changing `window.titleBarStyle` to `native`?

**Comment by jkristia** [comment]
Yes - thank you. Now there is no animation and it shows instantly (but also no dark theme for the menu). This is strange, apparently I have used this 'new / custom style' all the time since I know for sure I have had the dark popup menu, but it is not until just recently I notices a delay in popping up the context menu (only on remote desktop).

Anyway, this flag removed the popup animation and it is now instant again

Thanks

**Comment by sbatten** [comment]
@jkristia thanks for testing, `custom` is the default which is why you had it set. Since there is a workaround, I will close this issue as resolved. Thanks again.
