### ISSUE TITLE
Electron 6: windows-mutex cannot be loaded

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#77417]
Looks like https://github.com/microsoft/node-windows-mutex fails to load on Windows in Electron 6. There is now a test for it that fails: https://dev.azure.com/vscode/VSCode/_build/results?buildId=22999

**Comment by deepak1556** [comment]
Fixed by https://github.com/microsoft/vscode/commit/ccbd05eed34de1fb016f14a830ceeb19b96184b2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
