### ISSUE TITLE
Terminal picker is off

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#77415]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.37.0-insider (8fa811108f0f0524c473020ef57b6620f6c201e1, 2019-07-12T09:17:10.495Z)
OS version: Darwin x64 17.7.0
Remote OS version: Linux x64 4.18.0-1024-azure

I'm connected remotely to a VM in Azure over SSH.  I noticed that my terminal picker looked like this:

![image](https://user-images.githubusercontent.com/1487073/61236184-38fb5980-a6ec-11e9-9dbb-32273966adf6.png)

And when i clicked on it, the separator was checked!

![image](https://user-images.githubusercontent.com/1487073/61236166-31d44b80-a6ec-11e9-880c-d4ddd7552f87.png)

Once I clicked on a terminal (e.g. I clicked on `bash`) the problem went away.

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv|-psn_0_12962908|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cdias-devbox|
|OS|Linux x64 4.18.0-1024-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.77GB (6.24GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
vscode-peacock|joh|2.4.0
dotenv|mik|1.0.1
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.66.0
remote-ssh-edit-nightly|ms-|2019.7.21060
remote-ssh-explorer-nightly|ms-|2019.7.21060
remote-ssh-nightly|ms-|2019.7.21060
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
cloudenv|ms-|1.0.488
cloudenv-explorer|ms-|1.0.488
cloudenv-extensions|ms-|1.0.488
debugger-for-chrome|msj|4.11.6
vscode-openapi|42C|1.8.3
vscode-azurefunctions|ms-|0.17.1
vscode-kubernetes-tools|ms-|1.0.1
azure-account|ms-|0.8.4
vscode-yaml|red|0.4.1

(2 theme extensions excluded)

</details>

**Comment by chrisdias** [comment]
looks like it happens on first connect...

![image](https://user-images.githubusercontent.com/1487073/61237075-73fe8c80-a6ee-11e9-9388-a89e58519711.png)

**Comment by Tyriar** [comment]
I repro'd this by turning on show login terminal and connecting to an ssh box.

**Comment by Tyriar** [comment]
This appears to happen because of the short-lived "install" terminal

**Comment by Tyriar** [comment]
This is merged, I'll manually verify it in tomorrow's build though.

**Comment by Tyriar** [comment]
This wasn't actually fixed

**Comment by Tyriar** [comment]
Another repro in https://github.com/microsoft/vscode/issues/78405

**Comment by Tyriar** [comment]
I think this is fixed
