### ISSUE TITLE
VSC high CPU usage on startup. 

### ISSUE THREAD

**Issue by ktajeran** [Microsoft/vscode#7741]
- VSCode Version: Currently 1.0, have also been running into this issue on 1.2 and 1.2.1
- OS Version: Windows 10 64 bit

See attachment for CPU profiling while reloading the VSC window. 
[cpu_profile.zip](https://github.com/Microsoft/vscode/files/317180/cpu_profile.zip)

Steps to Reproduce:

1. Start VSC 

Description:
Painfully slow (About 3-5 minutes) to fully start VSC. VSC will max my CPU usage on my system while starting up, after it starts up, it will dip to about 5% CPU utilization, but will jump back up to max my CPU when I am typing in an empty document.

Have tried running `code -n --disable-extensions --disable-gpu` but I am running into the same issue as well. Also tried clean installs and have reverted back to 1.0 but the issue still persists. 
System Specs:

 Operating System: Windows 10 Enterprise 64-bit (10.0, Build 10240) 
 System Manufacturer: Hewlett-Packard
 System Model: HP ZBook 15 G2
 Processor: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz, ~2.8GHz
 Memory: 16384MB RAM
 Available OS Memory: 16042MB RAM

**Comment by sandy081** [comment]
@joaomoreno Here is another performance issue which it seems claimed to happen also on 1.2.1

**Comment by joaomoreno** [comment]
Does it reproduce if you set `git.enabled` to `false` and restart?

**Comment by ktajeran** [comment]
@joaomoreno I am still experiencing the same symptoms after adding `"git.enabled" : false` to my settings.json and restarting VSC .

**Comment by joaomoreno** [comment]
Code uses multiple processes to execute. Can you try to figure out which process spikes the CPU? [Process Hacker](http://processhacker.sourceforge.net/) is a great tool for that.

**Comment by ktajeran** [comment]
@joaomoreno The process that is spiking in cpu usage is the following, let me know if additional information is required on your end:

"C:\Program Files (x86)\Microsoft VS Code\Code.exe" --type=renderer --no-sandbox --lang=en-US --app-user-model-id=Microsoft.VisualStudioCode --node-integration=true --enable-pinch --device-scale-factor=1 --enable-delegated-renderer --num-raster-threads=1 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --channel="9128.1.1948626824\1501164466" /prefetch:673131151"

**Comment by joaomoreno** [comment]
This is great news. Could you run a profile for about a minute in the `Developer Tools` of your Code window, and send me that? That'll tell us where the time is spent.

Let me know if you need help with that, I'll guide you.

**Comment by ktajeran** [comment]
@joaomoreno Will this suffice? https://github.com/Microsoft/vscode/files/317180/cpu_profile.zip

**Comment by joaomoreno** [comment]
Hm, it doesn't have much info... was the CPU spiking during that profile?

**Comment by ktajeran** [comment]
@joaomoreno Yes, that profile was taken while the CPU was spiking. 

I figured out the root cause of my issue. On my laptop there are two GPUs, an embedded one from Intel and a discrete one from Nvidia. There is a bios option called "Hybrid Graphics" mode that allows the system to dynamically use the embedded one when there are no high-demand GPU intensive programs running. Disabling this hybrid graphics mode has made VSC very responsive and fast. This seems to be something that has to do with the Electron framework possibly, I was experiencing the same slowdowns on Atom and do not have any problems with either VSA or Atom now after making this change.

**Comment by joaomoreno** [comment]
@ktajeran Great to know, thanks for the insights!

@bpasero Heard of this before?
