### ISSUE TITLE
Terminal Startup

### ISSUE THREAD

**Issue by yuri-castroo** [microsoft/vscode#77413]
Issue Type: <b>Bug</b>

Whenever I just open Visual Studio Code, the terminal would be off. It starts off completly blank. and when i want to start typing in it, the input would off to the center and nothing in front. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (25.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</su
![terminal](https://user-images.githubusercontent.com/38123393/61234576-47e00d00-a6e8-11e9-8f40-6335d02796b8.PNG)
![terminal](https://user-images.githubusercontent.com/38123393/61234591-4e6e8480-a6e8-11e9-87ee-1a6b7cac2a45.PNG)

mmary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.28.0
mustache|daw|1.1.1
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.2
code-spell-checker|str|1.7.17

</details>

**Comment by yuri-castroo** [comment]
![terminal](https://user-images.githubusercontent.com/38123393/61234616-5dedcd80-a6e8-11e9-96a1-7dc41fa2af53.PNG)

**Comment by anton-gorbikov** [comment]
I'm experiencing the same issue. 

From my side I want to add, that it looks like a rendering issue only, because despite the fact that terminal window is empty it is still fully functional. So I can type any commands and execute them, however some characters will not be rendered.

![image](https://user-images.githubusercontent.com/5469718/61785324-25e73880-ae14-11e9-9fae-5d3b1d470e46.png)

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by sergey-tihon** [comment]
> OS: Windows_NT x64 10.0.18362

@Tyriar but this is version of `Windows 10 (1903)` so probably is not enough to just wait for update.

**Comment by Tyriar** [comment]
The OP's Windows version is 10.0.17763
