### ISSUE TITLE
Cannot drag and drop files or directories

### ISSUE THREAD

**Issue by juancrescente** [microsoft/vscode#77422]
Issue Type: <b>Bug</b>

Suddenly it stopped working after update. I cannot drag and drop anyuthing (nothing happens when I do)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3491)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.84GB (18.32GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.4
nbpreviewer|jit|1.2.2
python|ms-|2019.6.24221

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest vscode insiders
https://code.visualstudio.com/insiders/

If yes please provide reproducable steps and some video demonstrating this.
Thanks

**Comment by juancrescente** [comment]
this hasn't happend anymore

**Comment by isidorn** [comment]
Thanks for letting us know.
