### ISSUE TITLE
Make cmd-1/2/3/.../9 switch tabs on macOS

### ISSUE THREAD

**Issue by nico** [microsoft/vscode#77425]
Issue Type: <b>Bug</b>

Hit cmd-1, cmd-2, ...

In Safari, Terminal.app, Chrome, ... this switches to tab 1, 2, ... (and cmd-9 switches to the last tab). In Code, the shortcut for that is ctrl-1/2/3/.../9 instead, breaking muscle memory.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by mjbvz** [comment]
These are configurable using keybindings: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by nico** [comment]
Yeah, but defaults matter.
