### ISSUE TITLE
Freezes when typing

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#77426]
The file decorations are leaking CSS at a terrible high rate.

I am just selfhosting with some modified and added files... Here's how it looks like:
![image](https://user-images.githubusercontent.com/5047891/61244459-90c8ad80-a74a-11e9-8c22-7a1252c94710.png)

Here is the profile:
![image](https://user-images.githubusercontent.com/5047891/61244290-2a438f80-a74a-11e9-8fe2-4968612028c5.png)
[CPU-20190715T214746.txt](https://github.com/microsoft/vscode/files/3393947/CPU-20190715T214746.txt)

And here is the CSS style element with thousands of rules that have leaked. Notice > 700 KB of dynamic CSS in there:
![image](https://user-images.githubusercontent.com/5047891/61244365-565f1080-a74a-11e9-8beb-6d1de10b57d6.png)

![image](https://user-images.githubusercontent.com/5047891/61244422-7989c000-a74a-11e9-9b6f-a10bae3dfdaa.png)

**Comment by alexandrudima** [comment]
weird how M appears multiple times in the CSS but never in the UI:

![image](https://user-images.githubusercontent.com/5047891/61244550-c8cff080-a74a-11e9-8dfa-e42c08912ae9.png)

**Comment by jrieken** [comment]
hm... there should be logic to clean up css rules that are unused...

**Comment by jrieken** [comment]
Very certain that this has the same cause as https://github.com/microsoft/vscode/issues/77587. It seems that deleting rules has been broken with https://github.com/microsoft/vscode/commit/5565ddd88c6350f90e1031be4ce0d6089ac73a57. I make sure that the decoration service calls `deleteRule` but that seems to only work when said rules have been created via `insertRule`. Optimistically closing as duplicate.
