### ISSUE TITLE
Intellisense dialogue for signature help is smaller then the text

### ISSUE THREAD

**Issue by Abdullah2993** [Microsoft/vscode#7742]
- VSCode Version: 1.2.1
- OS Version: Win 10 x64

intellisense dialogue is smaller then the text and isn't scrollable so you can't see the text i.e arguments and options

![Proof](http://i.imgur.com/9628D34.png)

I guess this is the right place for this issue
https://github.com/OmniSharp/omnisharp-vscode/issues/443

I'm not sure but could be a problem with calculating the height [Here](https://github.com/Microsoft/vscode/blob/8a9ddea7f979912cea99dd39369fa88e033f7d5f/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L289) when the text is wrapped

**Comment by joaomoreno** [comment]
#7488
