### ISSUE TITLE
External terminal window opens, even integrated mode is turned on

### ISSUE THREAD

**Issue by AiratShaimuhamitov** [microsoft/vscode#77424]
Issue Type: <b>Bug</b>

VSC always opens the external terminal window. In settings, I have set to integrated terminal mode, but it doesn't help. Also, I didn't find any errors in the event viewer.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.3.0
vscode-npm-script|eg2|0.3.8
vsc-material-theme|Equ|29.2.0
dotnet-test-explorer|for|0.7.1
electron-debug|kod|18.11.1
vscode-azureappservice|ms-|0.15.0
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
sublime-keybindings|ms-|4.0.3
debugger-for-chrome|msj|4.11.6
polacode|pnp|0.3.2
vscode-icons|vsc|8.8.0

</details>

**Comment by uncikmarek** [comment]
same issue, it was working until yesterday and now its not

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
