### ISSUE TITLE
Add title property to QuickPickOptions/InputBoxOptions (showQuickPick)

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#77423]
Currently, `title` can only be set when going through the more complex `createQuickPick` API. It would be great if the title could be set via `QuickPickOptions` when using the simpler `showQuickPick`.

**Comment by TylerLeonhardt** [comment]
proposal:

for quickpick
```ts
export interface QuickPickOptions {
                 // ...

		/**
		 * An optional string that represents the tile of the quick pick.
		 */
		title?: string;

                 // ...
}
```
or Input:

```ts
export interface InputBoxOptions {
                 // ...

		/**
		 * An optional string that represents the tile of the quick pick.
		 */
		title?: string;

                 // ...
}
```

This basically meshes with UI in:
https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/src/vs/base/parts/quickinput/browser/quickInput.ts#L88
and in the class itself here:
https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/src/vs/base/parts/quickinput/browser/quickInput.ts#L137

cc @eamodio

**Comment by TylerLeonhardt** [comment]
what extensions have to do now in order to get the base functionality + a title:

https://github.com/eamodio/vscode-gitlens/blob/88ac213a4ae24205f80c58d1fc78fb98e32bb89a/src/quickpicks/repositoryPicker.ts#L36

**Comment by TylerLeonhardt** [comment]
In API sync there was no pushback or additional comments. I have moved to implementation ^

**Comment by TylerLeonhardt** [comment]
I will reopen this for API finalization next week.

**Comment by TylerLeonhardt** [comment]
This was covered on [a previous test plan item](https://github.com/microsoft/vscode/issues/119526) so there's nothing else to do here besides wait for the next release of vscode types :)
