### ISSUE TITLE
Error messages in another language

### ISSUE THREAD

**Issue by credencie1** [microsoft/vscode#77420]
Issue Type: <b>Bug</b>

I don't know if this is a VSCode issue or with any extension, but when I'm trying to start debugging a React Application, I get an error message in Portuguese. My OS, Windows 10, is in Portuguese, but VSCode and Chrome are in English (I have all my programs in English because there are many translation errors).

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.5.2
vscode-color|ans|0.4.5
vscode-twig-pack|baj|1.0.0
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.8.5
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
shell-format|fox|6.0.1
crane|Hvy|0.3.8
MagicPython|mag|1.1.0
python|ms-|2019.6.24221
debugger-for-chrome|msj|4.11.6
python-docs|Muk|0.8.3
php-docblocker|nei|2.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
python|tht|0.2.3
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.1.7
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@credencie1 can you provide me with a screen shot showing where the error message is shown.
