### ISSUE TITLE
[json] Allow users to register a json validator through code similarly to how they can register one through package.json

### ISSUE THREAD

**Issue by lexrey** [microsoft/vscode#77433]
Create a function similar to registerCompletionItemProvider that can take in a json schema that provides json validation.

**Comment by aeschli** [comment]
@lexrey  Can you describe a use case?

**Comment by lexrey** [comment]
Sure. I'd like to collect telemetry on my extension and one of the things it offers is json validation. By registering my own json validator, I could then make the telemetry function calls on use of the snippets provided by the schema as well as hovers used.

**Comment by aeschli** [comment]
If what you provide is a JSON schema, then all you could measure is how many accesses there are to the schema. Only the JSON language service would know when proposals or hovers are provided.

-> It's already possible to provide schemas programmatically by registering a TextDocumentContentProvider

To know what proposals or hovers are requested, you would have to implement a hover and completion provider.

**Comment by lexrey** [comment]
Could you provide an example on how to measure the amount of accesses to the schema? It seems that recreating the functionality of the jsonValidation supplied by package.json is much more difficult than recreating the snippets provided by it.

**Comment by aeschli** [comment]
- register a TextDocumentContentProvider for a new URL schema (let's say 'fooSchema')
- in your extension associate file extensions with that schema
```    "jsonValidation": [
      {
        "fileMatch": "*.foo",
        "url": "fooSchema://schemas/schema"
      },
```
in the TextDocumentContentProvider, serve your JSON schema when requested and collect telemetry

**Comment by lexrey** [comment]
Thank you for the example. And before closing just for clarification, the association for the file extensions would be set in the contributes.jsonValidation section of package.json?

**Comment by aeschli** [comment]
Yes, correct
