### ISSUE TITLE
Warning color in explorer gets stuck when switching themes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#77432]
Issue Type: <b>Bug</b>

![ezgif com-gif-maker(44)](https://user-images.githubusercontent.com/35271042/61254890-1fbdd180-a71b-11e9-8e87-a912b46edccb.gif)

Steps to repro:
1. Open a file that has warnings
2. Switch from dark -> light theme
3. :bug: Warning error in list view does not update and is stuck on previous theme color. Reloading the window will show the correct color.

VS Code version: Code - Insiders 1.37.0-insider (894056d11c7fffb261a0100fd4dcbf8cff84a8c0, 2019-07-15T05:24:02.940Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_4777102|
|Screen Reader|no|
|VM|20%|

|Item|Value|
|---|---|
|Remote|SSH: parallels-ubuntu18|
|OS|Linux x64 4.15.0-51-generic|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (4 x 3096)|
|Memory (System)|1.94GB (0.20GB free)|
|VM|100%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-profile-switcher|aar|0.3.0
vscode-opennewinstance|chr|0.0.6
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
rest-client|hum|0.21.3
all-symbol-kinds|jri|0.0.1
graphql-for-vscode|kum|1.15.0
theme-monokai-pro-vscode|mon|1.1.13
vscode-scss|mrm|0.6.2
vscode-azureappservice|ms-|0.15.0
vscode-gatsby-snippets|nic|1.1.2
material-icon-theme|PKi|3.8.0
vscode-graphql|Pri|0.2.1
stylelint|shi|0.51.0
notification-tester|svi|2.1.2
errorlens|use|2.5.0
markdown-all-in-one|yzh|2.4.0
vscode-open-in-github|ziy|1.3.6

(5 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
same as https://github.com/microsoft/vscode/issues/77587
