### ISSUE TITLE
"Invalid regular expression: ..." validation message is missing immediately after enabling regular expression search in Search Panel

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#77435]
Issue Type: <b>Bug</b>

There is no validation message in Search panel when search term is invalid regular expression (contains unmatched `(`, `[`, etc.) right after enabling regular expression search.

Steps to reproduce:

1. Open Search panel and turn off regular expression search if one is enabled
1. Type `require(` in search field
1. Click on `Use Regular Expression`
1. Observe that search is in progress however no results visible
1. Type any letter or number to the search field
1. Correct "Invalid regular expression: ..." error message appears

Simple Find displays error immediately after enabling regular expression search.

VS Code version: Code - Insiders 1.37.0-insider (894056d11c7fffb261a0100fd4dcbf8cff84a8c0, 2019-07-15T05:26:27.959Z)
OS version: Windows_NT x64 10.0.18936

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
Good catch, search is kind of broken after this.

**Comment by IllusionMH** [comment]
Works great! 🎉
Thank you!
