### ISSUE TITLE
Visual Studio Code should verify system requirements before auto-updating

### ISSUE THREAD

**Issue by kiddailey** [microsoft/vscode#77439]
Visual Studio Code does not verify system requirements, specifically the operating system, before auto-updating.  On Mac OS, this can result in breaking working environments when auto-updating is enabled.

- VSCode Version: 1.35.1
- OS Version: Mac OS X 10.9.5

I realize that this is being reported related to an old, outdated OS version, but I maintain various operating systems and versions for testing purposes and suspect that I will encounter this issue again in the future.  I figured a bug report was a better fit than a feature request, since this issue actively broke one of my dev environments and is entirely reproducible.  It seems like the auto-updater should be at least minimally mindful of the OS version requirements before it proceeds.

**Steps to Reproduce:**

1. [Install VSCode v1.35.1](https://update.code.visualstudio.com/1.35.1/darwin/stable) on Mac OS X 10.9.5

2. From the main "Code" application menu, choose "Check for Updates..."  or, alternatively wait for the application to perform an auto-update check.
_When complete, the gear icon in the lower left of the window will indicate that you need to restart to update the software._

3. Restart VSCode to apply the update.
_VSCode version 1.36.1 (or newer) will now be installed.  The app icon will indicate that it cannot run under OX 10.9.5 and attempting to launch it will result in an error dialog being displayed that states "You can't use this version of the application with this version of OS X."_

Does this issue occur when all extensions are disabled?: Yes

**Expected Behavior:**

Do not apply the update.  Notify the user that an update is available but incompatible with the system.  Instruct how to, or automatically disable auto-updates.

**Workaround:**

[Download last-known, working version (if available) from the VSCode Update Page](https://code.visualstudio.com/updates), install and immediately disable auto-updating before the software performs the check.

**Comment by joaomoreno** [comment]
@bpasero It seems the Electron update also raised the macOS system requirements.

**Comment by bpasero** [comment]
@joaomoreno that is right, we no longer support macOS 10.9 as outlined on https://code.visualstudio.com/docs/supporting/requirements.

**Comment by joaomoreno** [comment]
Then there's not much we can do now.

For everyone that is on macOS 10.9 and already has Code installed, we can't update those versions in people's disks... they will simply get an update to something that doesn't work. This is unfortunate. @bpasero next time this happens let's try to plan for it a bit better by adding the rule in the update story.
