### ISSUE TITLE
File content is empty when a file opened in VS code

### ISSUE THREAD

**Issue by vinoth-sarsha** [microsoft/vscode#77443]
Issue Type: <b>Bug</b>

The issue is similar to the following issue. But here it is in windows:
https://github.com/microsoft/vscode/issues/25987

I have also raised an issue for the same
https://github.com/microsoft/vscode/issues/76409
A solution was provided to try with the latest insider and the issue persists. That issue is closed requesting for more info. 

So raising another issue for the same. Have also attached the console log generated from the developer tools.
[-1563200515068.log](https://github.com/microsoft/vscode/files/3395424/-1563200515068.log)

VS Code version: Code - Insiders 1.37.0-insider (894056d11c7fffb261a0100fd4dcbf8cff84a8c0, 2019-07-15T05:26:27.959Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by vinoth-sarsha** [comment]
@bpasero @mjbvz 
Hi, Can u pls help me in fixing this issue?

**Comment by bpasero** [comment]
@vinoth-sarsha what is your exact setup? are you opening a file from FTP?

**Comment by bpasero** [comment]
This likely is https://github.com/microsoft/vscode/issues/73884
