### ISSUE TITLE
"terminal.integrated.env.windows" is not working for variables which contain underscore characters.

### ISSUE THREAD

**Issue by shihaonan369** [microsoft/vscode#77440]
- VSCode Version:
1.36.1
- OS Version:
Windows 10 1903

Steps to Reproduce:
1. Set up these variables, see below.
```
{
    "terminal.integrated.env.windows": {
        "LOCALAPPDATA": "./cache",
        "TEMP": "./cache",
        "ELECTRON_BUILDER_CACHE": "./cache",
        "ELECTRONBUILDERCACHE": "./cache"
    }
}
```
2. Echo values.
- PS E:\workspace\client-electron> echo $env:LOCALAPPDATA
- ./cache
- PS E:\workspace\client-electron> echo $env:TEMP
- ./cache
- PS E:\workspace\client-electron> echo $env:ELECTRON_BUILDER_CACHE
- PS E:\workspace\client-electron> echo $env:ELECTRONBUILDERCACHE
- ./cache

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
What you're seeing is the environment being sanitized of anything that starts with `ELECTRON_`:

https://github.com/microsoft/vscode/blob/74d8f8d743e1f9fc4d118cbd9dbb646bc06a2a2d/src/vs/base/common/processes.ts#L101-L126

**Comment by Tyriar** [comment]
Thanks for the report, fixed 😃
