### ISSUE TITLE
Add UI for editing variables

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7744]
I've added a new 'setVariableRequest' and a capability 'supportsSetVariable' to the debug protocol.
If this capability is true, the VS Code debugger should provide a UI gesture to edit the value of leafs in the variable view. The request takes the reference of the variable container, the name of the variable leaf, and the value as arguments. If the request succeeds, the new value is returned and is used as the new value of the variable. In case of failure the error should be shown in the error notification and the old value remains. 

This is the UI for https://github.com/Microsoft/vscode-debugadapter-node/issues/27

**Comment by isidorn** [comment]
@weinand please notice that I started with just the context menu action with the 'Set Value' action. This action should only be enalbed for primitive values and only if the debug adapter supports set value.
We can add this behavior on double click aslo if we want in future.

Try it out and let me know what you think.

**Comment by weinand** [comment]
@isidorn works like a charm!

One issue: on success use the body.value as the new value for the variable, not the value passed as an argument.

**Comment by isidorn** [comment]
@weinand great! Pushed the fix to respect the value returned.

**Comment by weinand** [comment]
@isidorn Another issue: the error returned by `setVariableRequest` is not yet shown. For now you can show it as an error notification. In the future we could use a similar approach as in the explorer:

![2016-06-17_12-19-54](https://cloud.githubusercontent.com/assets/1898161/16147813/d2e9c81a-3485-11e6-8ff5-9d958c721c95.png)

**Comment by wesrupert** [comment]
@isidorn It looks like assigning to a variable doesn't prompt a reevaluation of any variables that depend on it. Variables can be stale after setting a variable in languages such as C# (e.g. a property in the locals window), and watch expressions can be stale in all languages since they can be arbitrary expressions dependent on the changed variable.

**Comment by isidorn** [comment]
@wesrupert true, can you please create a seperate issue for that. Thank you.
