### ISSUE TITLE
[Settings GUI] String array becomes modified even if it's not changed

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77449]
#77427

1. Have default (not modified) setting
1. Open input on one of the array items
1. Don't change the input value and hit <kbd>Enter</kbd>
1. It writes the entire array into `settings.json`

VS Code version: Code - Insiders 1.37.0-insider (8e0f348413f4f616c23a88ae30030efa85811973, 2019-07-16T05:25:39.655Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
I can't repro. Here's what I tried:

- Have below contribution:

```json
{
  "configuration": [
    {
      "title": "foo",
      "properties": {
        "bar": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": ["foo"]
        }
      }
    }
  ]
}
```

![bug](https://user-images.githubusercontent.com/4033249/62167426-11a1b080-b2d8-11e9-97e8-df7209b5a878.gif)

**Comment by usernamehw** [comment]
Well, it became modified in your case, isn't it? There's no point in writing the default value.

Compare it to the simple numeric `editor.fontSize` setting:
* Reset the value
* Focus input 
* Blur input without changing 
* The value is not written (setting still not modified), because it hasn't changed.

**Comment by octref** [comment]
Ah I see. You meant default value being `["foo"]` and merely pressing and exiting input mode shouldn't write back the setting.

**Comment by usernamehw** [comment]
Yes.
