### ISSUE TITLE
Debugging window should not change VS Code it is opened from

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#77446]
I'm the developer of the extension [vscode-sundial](https://github.com/muuvmuuv/vscode-sundial). Sundial changes the VS Code theme based on sunrise and sunset or other selected options.

My problem when testing my changes is that whenever I debug the extension by `Debug: Launch Extension` (launch.json) and I test some options (change theme based on time or location) VS Code is changing the theme on both Windows; the debugging window and the one I'm developing in. This is causing some unexpected results (flickering theme) because my debugged extension window is changing the theme and my developing window, so I can't really test or even test a blank VS Code.

What I would like to have is a flag to say that this new opened VS Code window has nothing to do with the window it is opened from and just share the settings and extensions _once_ it is loaded. 
Additionally, I would like to have a flag to disable the extensions or exclude all settings for that new VS Code window.  I think this has worked someday but with the latest update the flag `--disable-extensions` in `args` just opens a file with that name.

This would really help me to debug my extension!
Thanks in advance!

**Comment by aeschli** [comment]
If you don't want to share the user settings, add `--user-data-dir` in the launch config

```
	"configurations": [{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--user-data-dir=/tmp/foo",
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "npm: watch"
		},
```

**Comment by muuvmuuv** [comment]
Thanks @aeschli! What about that on first start the settings will be copied over and after it ignores everything else instead of a "blank" installation? And what about disable all extensions? The flag I have used is not working any more. Has it changed and where can I see those flags in the docs?

**Comment by muuvmuuv** [comment]
Okay, found the link: https://code.visualstudio.com/docs/editor/command-line but still the `--disable-extensions` does not work.

**Comment by muuvmuuv** [comment]
Okay, I had to do this `--disable-extensions=true` but this should also work without `=true`.

**Comment by muuvmuuv** [comment]
Okay I still have the flickering problem. The problem with `-user-data-dir=/tmp/sundial` is that my extension will not be installed on debugging and the extensions tab says "Error while loading extensions. connect ENOENT /tmp/sundial/1.36.1-shared.sock".

Maybe I was a little unclear what I need: on debugging it should copy all settings once (keep the host VS Code settings untouched after that) and should disable all extensions except the one I'm debugging.

This works without `-user-data-dir=/tmp/sundial` but it still edits my host VS Code settings which cause a flickering of the theme: https://imgur.com/a/N2sbSWw
