### ISSUE TITLE
css font-feature-settings autocomplete: c2sc

### ISSUE THREAD

**Issue by david-buck** [microsoft/vscode#77441]
Issue Type: <b>Bug</b>

suggests a value "c2cs" this should be "c2sc" (cap to small cap)

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 18.6.0

**Comment by octref** [comment]
Thanks a lot! I happen to find a bug that ate a lot of the descriptions for property values. Now you not only get c2sc but also many other value descriptions in IntelliSense 😉 

Diff: https://github.com/microsoft/vscode-css-languageservice/pull/164/files#diff-4a2e84241dd30c22463e9f8ea9fbd221

![image](https://user-images.githubusercontent.com/4033249/61392515-dc2aab00-a873-11e9-80d5-489159ff6f68.png)
