### ISSUE TITLE
Scrolling is slow on remote desktop. 

### ISSUE THREAD

**Issue by fijsh** [microsoft/vscode#77445]
Issue Type: <b>Bug</b>

Scrolling has always been very slow and laggy in Visual Studio Code.

My Visual Studio Enterprise editions (2015,2017,2019) are performing well and without any scroll lag.

I have tried many things that I found on the internet but none of them are fixing the slowness in VS Code.
Hope you can look into this. All my collegeas that are using VS Code have the same issue. 

We are working an a remote desktop. I suspect that has someting to do with the issue.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|32.00GB (19.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.21.3
vscode-tfs|iva|0.7.2
csharpextensions|jch|1.3.0
vscode-docker|ms-|0.7.0
vscode-logicapps|ms-|0.2.5
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
csharp|ms-|1.20.0
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.6

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by fijsh** [comment]
Thanks bpasero for your response. 
Last week I installed the latest exploration build, but unfortunately there is no difference in performance. Let me know if you need more info or if you have any more things I could try.
