### ISSUE TITLE
Pass through GPU command line flags to electron/chromium

### ISSUE THREAD

**Issue by JohannesRudolph** [microsoft/vscode#77447]
I'm running Fedora 30 on an Intel i7-8700  CPU using integrated graphics with 4k/UHD displays. Chrome/Chromium famously  doesn't want to enable GPU acceleration by default on Linux, [citing fears of buggy drivers](https://bugs.chromium.org/p/chromium/issues/detail?id=463440#c68).

I'm however happily running chromium using `--enable-gpu-rasterization --enable-native-gpu-memory-buffers` and get full GPU acceleration without any noticeable graphic glitches. I'd like to have the same for VSCode too. 

I want to have the ability to force VSCode to use GPU acceleration too, as it makes for a very big difference in responsiveness on 4k screens. Unfortunately, `code` doesn't pass the required chromium args through to electron -> chromium and I couldn't find other flags to try (i.e. there's a `--disable-gpu` flag, but not a `--force-enable-gpu` or similar).

Here's what I tried, note that GPU rasterization and native_gpu_memory_buffers is still disabled
```
10:13 $ code --enable-gpu-rasterization --enable-native-gpu-memory-buffers
10:13 $ code --status
[12966:0716/101357.767249:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS Version:       Linux x64 5.1.15-300.fc30.x86_64
CPUs:             Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 800)
Memory (System):  31.29GB (16.74GB free)
Load (avg):       2, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --enable-gpu-rasterization --enable-native-gpu-memory-buffers
GPU Status:       2d_canvas:                    enabled
                  checker_imaging:              disabled_off
                  flash_3d:                     enabled
                  flash_stage3d:                enabled
                  flash_stage3d_baseline:       enabled
                  gpu_compositing:              enabled
                  multiple_raster_threads:      enabled_on
                  native_gpu_memory_buffers:    disabled_software
                  rasterization:                disabled_software
                  surface_synchronization:      enabled_on
                  video_decode:                 unavailable_off
                  webgl:                        enabled
                  webgl2:                       enabled
```

**Comment by deepak1556** [comment]
What happens when you start code with `--gpu-sandbox-start-early`

```
$ code --enable-gpu-rasterization --enable-native-gpu-memory-buffers --gpu-sandbox-start-early
```

**Comment by JohannesRudolph** [comment]
Turns out I had something mixed up. Maybe it also changed between v1.35 to 1.36 which I think also updated electron version, but on the latest version I can use code
--ignore-gpu-blacklist --enable-gpu-rasterization --enable-native-gpu-memory-buffers and get decent acceleration. 

Documented my findings here
