### ISSUE TITLE
integrated terminal on MacOS has bug.

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#77457]
Issue Type: <b>Bug</b>

On the terminal starting, this line
```
export A_RANDOM_VARIABLE=231
```
shouldn't be executed.
But it seems to be executed quietly.
This is a bug obviously.
And I believe this bug is related to and is the cause of https://github.com/microsoft/vscode/issues/70248
@Tyriar 

<img width="978" alt="屏幕快照 2019-07-16 下午5 21 16" src="https://user-images.githubusercontent.com/10379994/61283092-2453ba00-a7ef-11e9-87af-f8c4457add60.png">

BTW, what is that extra "%" in terminal window?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

Extensions: none

**Comment by Tyriar** [comment]
Can you share your settings.json file? Also you can try enable escape sequence logging to see if the % coming from the process or not https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by ladyrick** [comment]
> Can you share your settings.json file? 

Thank you for reply.
I delete the settings.json and disable all the extensions then test it again.
The result doesn't change.
You can test it for yourself.
[zshrc.txt](https://github.com/microsoft/vscode/files/3438958/zshrc.txt)

**Comment by Tyriar** [comment]
<img width="455" alt="Screen Shot 2019-07-31 at 11 07 49 AM" src="https://user-images.githubusercontent.com/2193314/62236210-736b2480-b383-11e9-8d7e-16bd267d98a3.png">

**Comment by ladyrick** [comment]
@Tyriar Did you try this?
1. use given .zshrc file.
2. set your default shell to zsh.
3. totally quit vscode.
4. start vscode.
5. press control + ` to open the terminal.
6. see the result.

If you start zsh from shell, it works well. But if you start zsh from vscode, it works differently.

**Comment by Tyriar** [comment]
Works fine:

<img width="478" alt="Screen Shot 2019-08-10 at 7 17 22 AM" src="https://user-images.githubusercontent.com/2193314/62822909-ea03e100-bb3e-11e9-8807-ee3bae579fb5.png">

Can you try enable escape sequence logging to see if the % coming from the process or not https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by ladyrick** [comment]
> Can you try enable escape sequence logging to see if the % coming from the process or not https://github.com/Microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

Yes, it's from zsh.
