### ISSUE TITLE
[Settings GUI] String array: No indication that item is not allowed

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77456]
#77427
```json
"type": "array",
"items": {
	"type": "string",
	"enum": [
		"error",
		"warning",
		"info",
		"hint"
	]
},
```

`settings.json`:

![Screenshot (27)](https://user-images.githubusercontent.com/9638156/61282839-bb574c80-a7c4-11e9-8357-b92364c6a625.png)

`settings GUI`:

![Screenshot (28)](https://user-images.githubusercontent.com/9638156/61282852-c1e5c400-a7c4-11e9-81f1-920548053101.png)

**Comment by octref** [comment]
This functionality is not provided yet. We don't have much validation in settings editor.
