### ISSUE TITLE
[Settings GUI] String array item blinks when at the end of the list

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77452]
#77427

1. Select top list item
1. <kbd>Arrow Up</kbd>

![demo](https://user-images.githubusercontent.com/9638156/61282025-4fc0af80-a7c3-11e9-9f14-6903760a53f6.gif)

VS Code version: Code - Insiders 1.37.0-insider (8e0f348, 2019-07-16T05:25:39.655Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
@roblourens I assume this is as-designed to show some action?

**Comment by roblourens** [comment]
It doesn't seem like a big problem but it's not pretty and doesn't match other lists. It's probably an easy fix to check whether we are already at the first or last row.
