### ISSUE TITLE
[Settings GUI] String array item overlaps container border

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77451]
#77427

1. Focus list item
1. Focus its container <kbd>Shift</kbd>+<kbd>Tab</kbd>

![demo](https://user-images.githubusercontent.com/9638156/61281481-5ef32d80-a7c2-11e9-99b8-7f1c35c971cd.png)

VS Code version: Code - Insiders 1.37.0-insider (8e0f348413f4f616c23a88ae30030efa85811973, 2019-07-16T05:25:39.655Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
Added 1px padding:

![image](https://user-images.githubusercontent.com/4033249/62236801-a366f780-b384-11e9-9502-6b839f60b38f.png)
