### ISSUE TITLE
Snap in Output

### ISSUE THREAD

**Issue by easyMaxi** [microsoft/vscode#77460]
Issue Type: <b>Feature Request</b>

1. I save a python file.
2. I have the output console open and get some information from pylint.
3. I am struggling to find the beginning and ending of the "new" output versus the "old" (the save before that) at a glance.

Maybe make the output console behave like the "clear" (snap to the new output) command in terminals. 
Don't delete the old output. But hide and show it to me when I am scrolling up to it.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

**Comment by isidorn** [comment]
The extension is in charge of the output and it should format the output in a better way such that it is more distinguishable.
