### ISSUE TITLE
Back Button in Visual Code Please

### ISSUE THREAD

**Issue by tallibunny** [microsoft/vscode#77467]

**Comment by IllusionMH** [comment]
Same as <kbd>Alt + LeftArrow</kbd> (Back) and <kbd>Alt + RightArrow</kbd> (Forward) from Go menu?
And where it should be located?

**Comment by tallibunny** [comment]
Hi, yes that is what we want haha,  something like visual studios back and
forward buttons next to or above the components? But I will use this
shortcuts

Thank you
