### ISSUE TITLE
[Settings GUI] String array: Doesn't update until focus moved

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77463]
#77427

1. Focus any list item
1. Try to delete it / add new item
1. The list not updated until the focus is moved

VS Code version: Code - Insiders 1.37.0-insider (8e0f348413f4f616c23a88ae30030efa85811973, 2019-07-16T05:25:39.655Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
Good catch. Merged into #78162.
