### ISSUE TITLE
Clicking in focuses on terminal if terminal was focused when clicked out

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#7746]
- VSCode Version: 1.2
- OS Version: Windows 8.1, Ubuntu 12.0.4

Steps to Reproduce:

1. Put vs code and one other window (e.g.. Browser) side by side
2. Open a file in VS Code
3. Place cursor in Terminal
4. Click on external window
5. Click into file editting area in VS Code
6. Observe that typing will occur now in the terminal and not the clicked on file

**Comment by Tyriar** [comment]
This is already fixed in master, coming in v1.3.0
