### ISSUE TITLE
VS js editor: Ternary operator with "return"

### ISSUE THREAD

**Issue by MarinBuric** [microsoft/vscode#77469]
Issue Type: <b>Bug</b>

I tried this code:
localStorage.getItem("_ZABA popup") == popupID  ? ( return ) : ""

and VS Editor - underlines  "return" with "expression expected" 

But VS Editor doesn't have problems when i write normal IF..THEN statement:

if (localStorage.getItem("_ZABA popup") == popupID ) {
          return;
}

Marin

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by usernamehw** [comment]
/question

https://stackoverflow.com/q/35231609/5590193

**Comment by MarinBuric** [comment]
Thx..
