### ISSUE TITLE
whitespace render failed

### ISSUE THREAD

**Issue by HensonLi** [microsoft/vscode#77466]
Issue Type: <b>Bug</b>

whitespace's width is too small, and the render of whitespace seems wrong

VS Code version: Code - Insiders 1.37.0-insider (8e0f348413f4f616c23a88ae30030efa85811973, 2019-07-16T05:24:52.139Z)
OS version: Linux x64 4.15.0-55-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4002)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|11, 11, 10|
|Memory (System)|31.24GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cpptools|ms-|0.24.0
clang-format|xav|1.9.0

</details>

**Comment by kanlukasz** [comment]
Can you show us some screenshot for better understanding?
