### ISSUE TITLE
Allow intellisense while filling in snippet tabstops

### ISSUE THREAD

**Issue by third774** [microsoft/vscode#77478]
Currently it seems that suggestions do not appear when filling in tabstops of a snippet. Is this an intentional design decision? Would love for this to work!

![example of suggestions not appearing](https://media.giphy.com/media/SXfKg2D4l51nte1wEo/giphy.gif)

**Comment by jrieken** [comment]
This setting controls quick suggestions when snippets are active: `editor.suggest.snippetsPreventQuickSuggestions`
