### ISSUE TITLE
I want the automated PHP tag opener

### ISSUE THREAD

**Issue by alperendurmus** [microsoft/vscode#77470]
I want the automated PHP tag opener
![bandicam2019-07-1616-56-01-883](https://user-images.githubusercontent.com/44159011/61300802-56631d00-a7eb-11e9-979b-bb7a3c459bde.gif)

**Comment by kanlukasz** [comment]
I'm not sure I understand you well.
You can use snippets. Where the problem is?

**Comment by alperendurmus** [comment]
Hello there! 
I was showing open-source Atom text editor you to see how useful it is... 
Let try to decide which one is useful? Look at this screencast...
![bandicam2019-07-1621-11-26-930](https://user-images.githubusercontent.com/44159011/61318781-840d8d80-a80e-11e9-8f3f-83f25abeae39.gif)

**Comment by kanlukasz** [comment]
Ok, so like i said, you can simply make it with snippets
It's native function in VS Code

What are snippets?
https://code.visualstudio.com/docs/editor/userdefinedsnippets

You can create your own:
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

If you need behavior like in Atom, you have to create snippet like this:
```
"PHP Tag ": {
	"scope": "html",
	"prefix": "php",
	"body": [
		"<?php $1 ?>"
	],
},
```

**Comment by alperendurmus** [comment]
I am so so glad about this answer. Thanks.
