### ISSUE TITLE
VSCode Terminal only always defaults to python2.7 

### ISSUE THREAD

**Issue by IntelligentFunction** [microsoft/vscode#77476]
- VSCode Version: version 1.36
- OS Version: OSX Mohave

Steps to Reproduce:

1. Choose python interpreter - python3.7
2. open terminal
3. type "Python" 
python2.7 opens 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please start by filing this issue against the python extension
