### ISSUE TITLE
Extension grammer 'begin' 'end' oddities

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#77485]
So while trying to add block comments to my language extension; I found that `begin` and `end` doesn't really behave as expected.

Here's what I've written in my syntax json file:
```
"begin" : "^(?:\\s+)?(?i:rem\\b)($|\\s)",
"end" : "^(?i:end *?rem)",
"name" : "comment.block.bmx"
```
But here's what VSCode shows:
![Code_2019-07-16_23-36-43](https://user-images.githubusercontent.com/1727541/61331670-9691c200-a822-11e9-89c8-608b7b32548f.png)
Notice that once the `Rem` is tabbed; it doesn't get a match.
Even though I've specifically specified that whitespaces are okay.

As a reference, this is what regex101 shows: https://regex101.com/r/rk8rln/1
Which is the result I expected.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by matter123** [comment]
This is because you have a pattern that matches leading spaces, in particular, the begin/end rule that starts on line 11. That rule is a better match for the tab character before `Rem` because it is earlier in the grammar. Once the leading space pattern matches, the line is no longer anchored to the start and therefore the block comment pattern is never entered.

**Comment by Hezkore** [comment]
> 
> 
> This is because you have a pattern that matches leading spaces, in particular, the begin/end rule that starts on line 11. That rule is a better match for the tab character before `Rem` because it is earlier in the grammar. Once the leading space pattern matches, the line is no longer anchored to the start and therefore the block comment pattern is never entered.

Are you able to provider a better regex for this situation?

**Comment by matter123** [comment]
I would move the block comment rule above the `meta.leading-space` rules. As long as those rules are at the top, any rule the has a `^` anchor followed by whitespace will not work.

**Comment by Hezkore** [comment]
> 
> 
> I would move the block comment rule above the `meta.leading-space` rules. As long as those rules are at the top, any rule the has a `^` anchor followed by whitespace will not work.

This did the trick.
Thanks.
