### ISSUE TITLE
onDidOpenTextDocument document.getText().length is incorrectly 0

### ISSUE THREAD

**Issue by stuckinaboot** [microsoft/vscode#77486]
- VSCode Version: Version 1.36
- OS Version: Mac OS Mojave 10.14.4 (18E226)

Steps to Reproduce:
1. Create a new untitled file
2. Observe that `hit me` is printed (which is correct)
2. Add some contents to the file, such as: abcdefgh
3. Save the file by pressing command-s
4. Observe that `hit me` is printed again (which is incorrect)

Code to repro:
```
import * as vscode from 'vscode';

const myFunction = async (document: vscode.TextDocument) => {
  if (document.getText().length === 0) {
    console.error('hit me');
  }
};

export async function activate(context: vscode.ExtensionContext): Promise<void> {
  context.subscriptions.push(vscode.workspace.onDidOpenTextDocument(myFunction));
}
```

Does this issue occur when all extensions are disabled?: yes

cc @pelmers

**Comment by jrieken** [comment]
When you save a file, the `untitled`-file (not saved yet) is closed and the corresponding `file` file (file on disk) is opened.

**Comment by stuckinaboot** [comment]
@jrieken thanks for making me aware of that. However, when there are contents added to an untitled file that is subsequently then saved, and then `onDidOpenTextDocument` gets hit when the file on disk is opened, we would expect that the document passed into onDidOpenTextDocument would have `document.getText().length > 0` right?
