### ISSUE TITLE
My VSCode Quick Fix feature can't be used

### ISSUE THREAD

**Issue by Alexwsc** [microsoft/vscode#77489]
My VSCode quick fix feature cannot be used. Currently I am using VSCode to develop the flutter application, before the code error place, quick repair function has been used, do not know when, this quick repair function can not be used, click on the code red error place, no response, can only manual repair, very troublesome. Google also didn't find the answer.

**Comment by kswamy15** [comment]
I just upgraded to the June 2019 version and the Quick Fix selection to repair errors is not working.  When you have an error in the code, it is redlined.  When you right click the redlined code, shows a Quick Fix tab that comes up with many options.  One of the option would be a solution to the Fix the error (like Fix no Trailing spaces) and the others would be eslint code to ignore the error.  When you choose any of the choices, it doesn't do anything.  so the Quick Fix of VS code has stopped working in the latest update.  This is very frustrating.

**Comment by mjbvz** [comment]
Duplicate of #77018
