### ISSUE TITLE
VSCode is stuck off screen

### ISSUE THREAD

**Issue by dhruvrnaik** [microsoft/vscode#77480]
Steps to Reproduce:

Laptop connected to external monitor
Start vscode
Use normally
Leave VS code running and undock/disconnect from monitor
VScode is stuck offscreen
Attempted all these steps to fix: https://www.technipages.com/bring-off-screen-window-back-onto-screen. None of them worked
Restarted laptop
Started vscode - it is still stuck off-screen
How did I fix it:

I had to connect back to my external monitor to start using vscode again
This makes vscode unusable.

Does this issue occur when all extensions are disabled?: Yes/No

Copying from [#73534](https://github.com/microsoft/vscode/issues/73534), since I am facing exactly the same problem.

**Comment by dhruvrnaik** [comment]
Okay, I found a fix by using Alt+Space , and Maximizing the window. 
But I still think this is something that needs to be looked at.

**Comment by sdunnin** [comment]
VS Code seems to be the only app that I have significant problems with when undocking my Windows laptop. As reported above if VS Code is open or minimized on an attached monitor after undocking it will be forever lost off-screen. The only other workaround other than reconnecting to external monitor is to terminate and restart VSC from task bar or task manager.

**Comment by sbatten** [comment]
@sdunnin did you try the steps at https://github.com/microsoft/vscode/issues/73534#issuecomment-491369081

**Comment by sdunnin** [comment]
@sbatten Yes I tried the steps you noted and was able to get control of the VSC window and move it into focus. But man is that a non-intuitive sequence to have to remember. Usually you are able to move & snap off screen application windows with <Win> + <Arrow> keys which is a much simpler thing to remember. Unfortunately VSC doesn't seem to respond to those commands.
