### ISSUE TITLE
Extension tests are not running in a windows docker container

### ISSUE THREAD

**Issue by BugDiver** [microsoft/vscode#77499]
- VSCode Version: 1.36.1
- OS Version: Windows Server Core ltsc2016

Steps to Reproduce:

1. Start a windows docker container
2. Install yo, generator-code
3. Create a sample extension
4. npm install and npm test
5. The error is as following
```
Downloading VS Code 1.36.1 from https://update.code.visualstudio.com/1.36.1/win32-archive/stable
Downloaded VS Code 1.36.1 into .vscode-test/vscode-1.36.1
Exit code:   3221225781
Done

Failed to run tests
npm ERR! Test failed.  See above for more details.
```
## Note

The tests works fine when the `vscode` engine in `package.json` is `1.35.1`.

**Comment by octref** [comment]
Working for me on Windows 10 though.

```
PS C:\Users\octref\Desktop\foo> yarn test
yarn run v1.13.0
warning package.json: No license field
$ npm run compile

> foo@0.0.1 compile C:\Users\octref\Desktop\foo
> tsc -p ./

$ node ./out/test/runTest.js
Downloading VS Code 1.36.1 from https://update.code.visualstudio.com/1.36.1/win32-archive/stable
Downloaded VS Code 1.36.1 into .vscode-test/vscode-1.36.1


[main 2019-07-17T21:24:13.829Z] update#ctor - updates are disabled by user preference




  Extension Test Suite

    √ Sample test




  1 passing (10ms)


Exit code:   0
Done

Done in 92.34s.
PS C:\Users\octref\Desktop\foo>
```

Where can I find docker for Windows Server Core ltsc2016? Also this error code gave me some issues when people generally run apps in Docker:
- https://stackoverflow.com/questions/49413443/trouble-debugging-error-with-exit-code-3221225781-missing-libraries-in-windows
- https://social.msdn.microsoft.com/Forums/en-US/67425dcd-6812-4b52-81a8-f85c0e4e7d59/error-3221225781-when-running-existing-applications-in-docker?forum=windowscontainers

So I'm not sure this is a VS Code issue.

**Comment by BugDiver** [comment]
@octref Thanks for the quick reply.

The tests work perfectly fine on a windows machine for me as well. The issue is only when we try to run it in a docker container (windows)

> Where can I find Docker for Windows Server Core ltsc2016?

It can be pulled from the docker hub. `docker pull mcr.microsoft.com/windows/servercore:ltsc2016`

The weird part is all the test passes with vscode version 1.35.1 with the same setup. (I use CODE_VERSION env to set the vscode version for tests.)

Does vscode 1.36.1 require some new dep (dll's) on windows?

**Comment by octref** [comment]
There's another bug report saying 1.35.1 works fine but 1.36.0 doesn't: https://github.com/microsoft/vscode/issues/77513

So, just to recap, this setup:
- Works fine with both 1.35.1 and 1.36.1 locally
- Works fine on container with 1.36.1, but not 1.36.1

Is this correct?

Also I'm not familiar with Windows Server Core, but would it have problem launching 32-bit VS Code? Currently `vscode-test` by default downloads 32-bit archive for Windows.

**Comment by BugDiver** [comment]
> So, just to recap, this setup:
> * Works fine with both 1.35.1 and 1.36.1 locally
> * Works fine on container with 1.36.1, but not 1.36.1

Yes, just that the second point is a bit wrong
It is `Works fine on container with 1.35.1, but not 1.36.1`

> Also I'm not familiar with Windows Server Core, but would it have a problem launching 32-bit VS Code? 

I'm not sure about that but since it works with 1.35.1 I guess it can launch.

**Comment by Glavin001** [comment]
Is there a workaround for this? If I force `engines` to be `<= 1.35.1` then the extension would not be installable by newer VSCode versions? https://github.com/Unibeautify/vscode/blob/master/package.json#L67

**Comment by hunterwerlla** [comment]
Is there an update on this? We are still having this happen in Windows Docker containers: making our CI a pain.
