### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by qaisaliabbas** [microsoft/vscode#77498]
Issue Type: <b>Performance Issue</b>

I'm facing problem in Terminal, Its not opening properly. Only blank screen opening in terminal, I cann't write any command here. Please tell me solution to fix this problem.
Thanks!
Qais Ali Abbas

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
