### ISSUE TITLE
Implementing Protocol command 'Target.getBrowserContexts'

### ISSUE THREAD

**Issue by caslt** [microsoft/vscode#77491]
I met an issue when using puppeteer to connect to an existing VSCode instance.
I use these steps

1. Open a instance by code . --remote-debugging-port=9222
2. Get the WSEndPoint in http://localhost:9222/json/version
3. Connect to this VSCode instance by puppeteer.connect, with the WSEndPoint get from step 2

However, puppeteer throw an error saying command  'Target.getBrowserContexts' is not supported.

I could see it sends command and waiting for a correct response, in Launcher.js
const {browserContextIds} = await connection.send('Target.getBrowserContexts');

So I tried to fix this by https://github.com/GoogleChrome/puppeteer/pull/4720

However, as the other page mentioned https://github.com/GoogleChrome/puppeteer/issues/4283, the command should be implemented by electron apps.

So could you please support the protocol command  'Target.getBrowserContexts'

**Comment by weinand** [comment]
Please file this issue against electron.
