### ISSUE TITLE
SHELL Environment is not consistent with native Terminal

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode#77493]
- VSCode Version: 1.36.1
- OS Version: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_6

Steps to Reproduce:

1. Native Terminal: `chsh -s /bin/zsh`
2. `echo $SHELL # /bin/zsh`
3. open VSC
4. open VSC Terminal
5. `echo $SHELL # /bin/bash`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
That's what the new inheritEnv setting is meant to fix eventually, it has some issues on mac currently though.
