### ISSUE TITLE
Cancel closing the debug hover inspector if the mouse goes back over it before it disappears

### ISSUE THREAD

**Issue by charlesg99** [microsoft/vscode#77490]
The debug hover inspector window should stay visible if the mouse goes out, but comes back over it before the window disappears. In the following example, I would expect the window to stay visible:

![Peek 2019-07-16 20-24](https://user-images.githubusercontent.com/33044886/61338543-18c0bd00-a808-11e9-9fcb-06265e4a5afc.gif)

**Comment by weinand** [comment]
yes, I agree.

**Comment by itamark** [comment]
I am working on a solution for this @isidorn if it's okay!

**Comment by isidorn** [comment]
@itamark thank you for providing a PR! I will review it next week.

**Comment by isidorn** [comment]
Adding  bug so we get this verified
@itamark thanks for providing a nice PR!
