### ISSUE TITLE
Cannot find string after & in launch.json args

### ISSUE THREAD

**Issue by Juliehzl** [microsoft/vscode#77495]
- VSCode Version: 1.36.1
- OS Version: win 10

Steps to Reproduce:

1. lanuch.json args ['xxxxx&sssss&sss']

Does this issue occur when all extensions are disabled?: No

I want to pass argument "xxxxx&sssss&sss", but it looks only "xxxxx" passed and the following are ignored.

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by Juliehzl** [comment]
In configuration, the args part looks in the following way:       
  "args": [
                "storage", "copy", "--source", "..\\testfolder", "--destination", "https://storageforcli.blob.core.windows.net/recursivetest&aaaaaaa"
            ],

And finally, I got a parsed args in [
                "storage", "copy", "--source", "..\\testfolder", "--destination", "https://storageforcli.blob.core.windows.net/recursivetest"
            ]

**Comment by weinand** [comment]
If possible, please post the whole launch config. Without this I do not know what debugger you are using.
