### ISSUE TITLE
please auto-indent HTML / JavaScript code

### ISSUE THREAD

**Issue by mariusa** [Microsoft/vscode#775]
Open a .html or .js file, select all, press shitft+tab.

Expected: auto-indent everything, like a HTML beautifier

Result: all blocks, even if properly indented, are removed 1 tab. Press enough times and all lines of HTML code will start at column 0.

Maybe related: issue #677

**Comment by Tyriar** [comment]
`shift+tab` de-indents code so that's working as expected. `ctrl+shift+i` (Linux) is the shortcut for format code (`editor.action.format`) which seems to work fine on HTML and JS.

**Comment by mariusa** [comment]
Indeed, that does work! Thanks & sorry for the noise
