### ISSUE TITLE
There may need a column highlight for any code file.

### ISSUE THREAD

**Issue by Aisuko** [microsoft/vscode#77502]
Hi, thanks for your all, develop the perfect IDE.  I'm a maintainer of helm/charts and daily work is focused on .yaml file.  The template language of helm charts is really difficult to debug and the format tool difficult to told you where was the issue of the charts template. So, Is there may have a  column highlight? Just like the first picture below.

![Screen Shot 2019-07-17 at 3 05 53 PM](https://user-images.githubusercontent.com/8053949/61354291-6db21100-a8a4-11e9-8db1-631727a387d2.png)

My vscode picture below:

![Screen Shot 2019-07-17 at 3 07 12 PM](https://user-images.githubusercontent.com/8053949/61354368-9803ce80-a8a4-11e9-8721-19165d3fbc1a.png)

**Comment by alexandrudima** [comment]
@Aisuko it appears you are already using indent guides. Perhaps your theme does not provide a color for it, but you can configure on your side:

```
"workbench.colorCustomizations": {
	"editorIndentGuide.activeBackground": "#ff0000"
},
```

![image](https://user-images.githubusercontent.com/5047891/62629711-ff55f100-b92d-11e9-98cc-b3c51e85b902.png)

**Comment by Aisuko** [comment]
Thanks a lot❤️
