### ISSUE TITLE
How can the Modifier keys be changed?

### ISSUE THREAD

**Issue by gordonrust** [microsoft/vscode#77506]
I would like to use a key combination like spacebar+g  spacebar+d and not Alt+g Alt+d. 
I figure, changing the modifier key to spacebar would do it. But couldn't find any reference on how to change that. Is there a way? Essentially,  I would like to use spacebar as the leader-key as I do in my vim. Thanks

**Comment by rebornix** [comment]
Right now we don't support mapping modifiers globally in VS Code but you can use the keybindings editor to change shortcuts for commands.

**Comment by jclounge** [comment]
Just to add to this, it would be good to be able to change ALT+SHIFT+drag for column selection into simply ALT+drag, especially for macOS where most apps behave that way already, e.g. Terminal, TextEdit, and Sublime.
