### ISSUE TITLE
dart is not recognized as internal or external command

### ISSUE THREAD

**Issue by ifiroj** [microsoft/vscode#77509]
I changed some user settings in this IDE to run python programs but unfortunately my current settings does not execute any of my .dart files. I need help regarding this problem asap. I even tried to reset the settings but still IDE does not executes my flutter project .

'dart' is not recognized as an internal or external command,
operable program or batch file.
is the output of any project.

**Comment by mjbvz** [comment]
Please start by making sure the dart extension is enabled and file this issue against them
