### ISSUE TITLE
Allow changing "Peek Problem" colors

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#77507]
It seems like both `editorError.foreground` and `editorMarkerNavigationError` are changing the colour of 1. and 3.'s title and border + they override themself. Its unclear how I can change the "Peek Problem" overlay (border, background, foreground...). I would also like to know how I can change the peek view title (2.) if there is an error, I don't know where this red is coming from.

I don't know if it is a bug but the arrows (1.) are overlapping weird. I think multiple open peek views should be handled in tabs instead stacking them like it is ATM.

![Bildschirmfoto 2019-07-17 um 10 15 17](https://user-images.githubusercontent.com/11534760/61359182-29ab1600-a87c-11e9-9216-94632a63be3f.png)

**Comment by aeschli** [comment]
The peek view title has 2 colors:
```
		"peekViewTitleLabel.foreground": "#ff00F0",
		"peekViewTitle.background": "#0f00F0",
		"peekViewTitleDescription.foreground": "#FFFF00"
```
they are also used for the error marker navigation.

The error marker navigation border is `editorMarkerNavigationError.background`

![image](https://user-images.githubusercontent.com/6461412/61445429-ace86c80-a94d-11e9-9df9-d7d1b14c4c3e.png)

So this looks all fine too me.

Please file a separate issue about the overlapping arrows
