### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Summeringgod** [microsoft/vscode#77505]
Issue Type: <b>Bug</b>

[Extention Host] PHP process connected    workbench.main.js:sourcemap:240
Extention Host                                             workbench.main.js:sourcemap:3341
   Debugger atached.                                   workbench.main.js:sourcemap:3341
Extension host terminated unexpectedly.   workbench.main.js:sourcemap:3207
Code : 3221225477   Signal: null              
Extension host terminated unexpectedly.   workbench.main.js:sourcemap:2393

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.1.4
phpserver|bra|2.4.6
vscode-html-css|ecm|0.2.0
apacheconf-snippets|eim|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
extbundles-csharp|Fel|2.0.0
cshtml|fir|0.1.3
cshtml-tm|fir|1.0.0
code-runner|for|0.9.11
auto-using|Fud|0.7.9
vscode-firefox-debug|hbe|1.8.0
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.8
csharpfixformat|Leo|0.0.81
vs-color-picker|lih|1.0.0
csharp-colors|log|0.1.3
code-beautifier|mic|2.2.1
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
vscode-apache|mrm|1.2.0
csharp|ms-|1.20.0
sublime-keybindings|ms-|4.0.3
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.6
vscode-versionlens|pfl|0.24.0
stylelint|shi|0.51.0
csharp-code-snippets|Som|0.0.1
msbuild-project-tools|tin|0.2.55
highlight-matching-tag|vin|0.9.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
