### ISSUE TITLE
打开大文件失败后的无限重启。

### ISSUE THREAD

**Issue by Iamzz-cn** [microsoft/vscode#77516]
Issue Type: <b>Performance Issue</b>

我试图打开一个很大的文本文件，大概有14GB，我调整了vscode的设置 max-memory=一个大于我当前系统内存的值（我的系统有16GB，设置为40960），虽然成功的打开了文件，但是当我修改其中的内容本且尝试保存时，vscode没有任何的提示，过了一段时间，我关闭了vscode。至此之后，我使用vscode打开任何文件，他都会崩溃。

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.86GB free)|
|Process Argv|C:\Apache24\php|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    85	 15456	code main
    0	   184	  1880	   window (设置 - php - Visual Studio Code)
    0	    13	  5020	     watcherService 
    0	    11	  1388	       console-window-host (Windows internal process)
    0	    36	 13072	     searchService
    0	    62	 18032	     extensionHost
    0	    19	  2280	   electron-crash-reporter
    0	    67	  4812	   window (问题报告程序)
    2	    80	  5016	   gpu-process
    0	    31	  6444	   utility
    0	    69	 18040	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (设置 - php - Visual Studio Code)
|    Folder (php): 94 files
|      File types: dll(74) exe(5) txt(5) lib(2) cnf(1) gif(1) bat(1)
|                  ini-development(1) ini-production(1) phar(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
shell-format|fox|6.0.1
formate|Mik|1.1.1
vscode-docker|ms-|0.7.0
vscode-language-pack-zh-hans|MS-|1.36.2
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
Go|ms-|0.11.4
logstash|Ran|0.0.3
nginx-formatter|ray|0.0.4
vscode-yaml|red|0.4.1
vscode-nginx|sha|0.6.0
vscode-logstash|vsc|1.0.1
vscode-proto3|zxh|0.3.0

</details>

**Comment by zwuis** [comment]
@mjbvz translation:
title: **VS Code restarts indefinitely after failed to open a big file**
I tried opening a big text file, about 14 GB. I had modified the setting of VS Code max-memory=40960.(The memory of my system is 16 GB). I successfully opened the file, but when I modified it and tried saving it, VS Code didn't give any prompt. After a period of time, I closed VS Code. After that, whatever I open by VS Code, VS Code will crash.
