### ISSUE TITLE
tests don't run properly

### ISSUE THREAD

**Issue by cazfletch** [microsoft/vscode#77513]
I raised this issue on the vscode-test repo https://github.com/microsoft/vscode-test/issues/28

The tests don't run properly either they don't run at all or some run but then just stops. It worked fine at 1.35.1 but hasn't since version 1.36. 

You can see the issue from the linked travis builds, but this can also be reproduced locally. If you clone the repository and do an npm install. Then open vscode and debug the extension (you need to do this to do some initial setup and its the easiest way to do the initial setup). Then stop debugging and then switch the launch configuration to unit test then run the tests you will see either the tests don't run at all and debugging just stops or some tests will run and then just stop. I tried running the tests in batches on travis (running 10 test files in each batch) that ran better but you would often see some batches just not running and it would move onto the next batch.

**Comment by cazfletch** [comment]
What extra info do you need on this issue?

**Comment by octref** [comment]
I tried:

1. `git clone https://github.com/IBM-Blockchain/blockchain-vscode-extension`
2. `cd blockchain-vscode-extension`
3. Run the configuration `Node Integration Tests`
4. This window opens. Nothing is being run

![image](https://user-images.githubusercontent.com/4033249/62333908-56fde380-b47a-11e9-8eef-a48599cc740c.png)

Please do something like this for reproducing the problem. Describe **all** setups I need, **step by step in a list**.

Or, even better, fork https://github.com/microsoft/vscode-test/tree/master/sample and modify the sample to demonstrate the problem.

**Comment by cazfletch** [comment]
here are some better instructions

1. Clone the repo
2. cd `blockchain-vscode-extension/client`
3. npm install
4. open vscode
5. switch to debug tab
6. Change launch configuration drop down to be `extension`
7. press play
8. wait for the extension to be activated
9. close the launched vs code window
10. change the launch configuration drop down to be `unit test`
11. press play

This will then try and run the tests and either no tests will run or only some tests will run. It should run over 1000 tests.  

steps 5 - 9 are needed to do some setup like get the native grpc module and doing those steps are the easiest way to achieve the setup.

**Comment by octref** [comment]
Is this still an issue for you in latest version?

**Comment by cazfletch** [comment]
No in vscode 1.40 it seems to have been fixed
