### ISSUE TITLE
VSCode on WSL, Marketplace 

### ISSUE THREAD

**Issue by fpopineau** [microsoft/vscode#77510]
- VSCode Version: 1.36, 1.37
- OS Version: Windows 10, 1903, 18362.10005

Steps to Reproduce:

1. Install WSL/Ubuntu
2. Mount user directory from NTFS, aka c:\Home on /home/<username> 
3. Install VSCode on WSL by any mean (.deb, .tar.gz)
4. Marketplace is not reachable

Does this issue occur when all extensions are disabled?: Yes

Problem is that VSCode is using sockets and these sockets are not created on an NTFS mounted directory. These sockets are located by default in :
```
~/.config/Code/<vscode-version>-main.sock
~/.config/Code/<vscode-version>-shared.sock
```

An option is to run VSCode with `--user-data-dir` option to relocate the configuration directory inside the WSL filesystem.

Regards,

**Comment by aeschli** [comment]
Installing VSCode-Linux on WSL is not recommended. Instead, install VScode on windows and use the Remote-WSL extension.
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

Please reopen if I misunderstood what you are doing.
