### ISSUE TITLE
Expand Selection in JSON file selects whole file regardless of nesting depth

### ISSUE THREAD

**Issue by WORMSS** [microsoft/vscode#77514]
### Expand Selection in JSON file selects whole file regardless of nesting depth

When you have some data selected in a JSON file, I was `Expanding Selection`, and was surprised to see it select the whole file. Regardless of if you are nested n levels deep. `Expand Bracket Selection` works as expected, but that is not the command I have shortcutted. I would expect it to work like `Expand Selection` does in Javascript. Selecting Word, Sentence, Scopes, etc before selecting whole file.

```json
{
  "one": {
    "two": {
      "three": {
        "four": "value"
      }|
    }
  }
}
```
`|` denotes cursor.

Issue Type: <b>Bug</b>

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.0
ssh|chr|0.0.4
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
vscode-ts-auto-return-type|ebr|1.0.1
RunOnSave|eme|0.0.18
prettier-vscode|esb|1.9.0
todo-tree|Gru|0.0.139
json2csv|kha|0.0.1
node-module-intellisense|lei|1.5.0
camelcasenavigation|map|1.0.1
rainbow-csv|mec|1.1.1
vscode-typescript-tslint-plugin|ms-|1.2.2
node-modules-resolve|nau|1.0.2
uuid-generator|net|0.0.4
vetur|oct|0.21.1
gitconfig|sid|2.0.0
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.8.0

</details>

**Comment by KingKCodes** [comment]
I am experiencing the same issue.

**Comment by aeschli** [comment]
dup of #77194
