### ISSUE TITLE
Cursor position change event

### ISSUE THREAD

**Issue by xahon** [microsoft/vscode#77526]
I didn't find a hook like `onDidCursorPositionChange` to handle every cursor (caret) movement events

**Comment by usernamehw** [comment]
```js
vscode.window.onDidChangeTextEditorSelection
```

**Comment by xahon** [comment]
@usernamehw why selection? Vscode treats cursor position as zero-length selection?

**Comment by usernamehw** [comment]
Yes.

**Comment by xahon** [comment]
@usernamehw I think it must be reflected in documentation because it is soo unintuitive

**Comment by usernamehw** [comment]
https://github.com/microsoft/vscode-docs
