### ISSUE TITLE
C# syntax not working as expected

### ISSUE THREAD

**Issue by githubhero** [Microsoft/vscode#7752]
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

1. Download and install the onnisharp extension;
2. Just try to copy and paste some C# code;
3. Look at the source;

The code is not properly highlighted.

![csharp](https://cloud.githubusercontent.com/assets/1677287/16107131/84413f2c-339a-11e6-9962-f37d864c13b5.png)
![csharp2](https://cloud.githubusercontent.com/assets/1677287/16107143/93d54bd6-339a-11e6-942d-3afb3133ac72.png)

I don't know if this can be of any interest, but the theme is Monokai.

**Comment by sandy081** [comment]
@githubhero C# extension is owned by Omnisharp. Please file the bug here - 
https://github.com/OmniSharp/omnisharp-vscode

**Comment by githubhero** [comment]
Ok, thanks
