### ISSUE TITLE
Unable to debug VS Code - launches but displays blank window

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#77537]
Issue Type: <b>Bug</b>

I'm attempting to debug VS Code (from VS Code) but when I launch from the debug viewlet a mostly blank window pops up and nothing ever loads. 

I can launch VS Code successfully using scripts/code.bat though.

Window when launching using **Debug VS Code Main and Renderer** target :

![image](https://user-images.githubusercontent.com/28519865/61397322-814a8100-a87e-11e9-9665-5c1a4f59e2a8.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (38.49GB free)|
|Process Argv|--folder-uri file:///d%3A/src/vscode|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.5
tslint|eg2|1.0.44
Untabify|ili|0.0.2
mssql|ms-|1.6.0
csharp|ms-|1.20.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.7.17
vscodeintellicode|Vis|1.1.7

</details>

**Comment by Charles-Gagnon** [comment]
Note I'm hitting this issue even after disabling all of the extensions except for the Chrome debugger as well.

**Comment by Charles-Gagnon** [comment]
@roblourens FYI this seems to be the same issue as #75478

[vscode-chrome-debug.txt](https://github.com/microsoft/vscode/files/3403315/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
I looked into this when someone on my team saw it, and found that it is some issue with Electron 4 on Windows. I don't have a workaround, and it seems to be fixed in Electron 6 which we will upgrade to at some point.

Sorry, I don't understand the issue yet, but my only workaround is just to start vscode manually like `.\scripts\code.bat --remote-debugging-port=9222` then attach with the "Attach to VS Code" launch config.

**Comment by roblourens** [comment]
We are on Electron 6 now
