### ISSUE TITLE
Integrated terminal will not start.

### ISSUE THREAD

**Issue by akulbe** [microsoft/vscode#77534]
Issue Type: <b>Bug</b>

I am running a WSL-Remote session, and attempting to start the "Integrated Terminal" on the right pane. It says "1. Starting..." and never gets past that.

VS Code version: Code - Insiders 1.37.0-insider (112fa76c775ecb79ac2c9e9e5dba0d711d523543, 2019-07-17T05:37:41.194Z)
OS version: Windows_NT x64 10.0.18936
Remote OS version: Linux x64 4.19.43-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.55GB (41.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: WLinux|
|OS|Linux x64 4.19.43-microsoft-standard|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|61.40GB (59.90GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ansible-vault|dho|0.1.3
vscode-ansible|vsc|0.5.2
inspec|bur|0.5.2
bracket-pair-colorizer|Coe|1.0.61
vscode-peacock|joh|2.4.0
VS-code-vagrantfile|mar|0.0.7
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
code-settings-sync|Sha|3.4.0
vscode-nginx|sha|0.6.0
fish-vscode|sky|0.2.1
vscode-autohotkey|sle|0.2.2
vscode-icons|vsc|8.8.0
propertylist|zho|0.0.2

(1 theme extensions excluded)

</details>

**Comment by efroim102** [comment]
Any chance #77522 is related? If yes, try disabling legacy console.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1031, should be fixed tomorrow
