### ISSUE TITLE
[json] Expand Selection for JSON not working as intended

### ISSUE THREAD

**Issue by KingKCodes** [microsoft/vscode#77545]
I am using the Shift + Alt + RightArrow default shortcut key for expanding a selection (editor.action.smartSelect.expand). 

1. Open or create a valid JSON file.
2. Put cursor within a curly brace section and press Shift + Alt + RightArrow

Expected Results:
The containing curly brace section is selected

Actual Results:
The entire JSON is selected

**Comment by aeschli** [comment]
dup of #77194
