### ISSUE TITLE
The Copy by CTRL+C is not working 

### ISSUE THREAD

**Issue by ibrahim-fares** [microsoft/vscode#77544]
Issue Type: <b>Bug</b>

The Copying with CRTL+C is not working also it activate Insert key

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.93GB (2.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.4
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.24.0
sublime-keybindings|ms-|4.0.3
vim|vsc|1.8.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

/needsMoreInfo

**Comment by ron23** [comment]
I have the same issue. Not sure what the OP meant, but I'm getting `command 'clipboard.copy' not found` error whenever I do cmd+c.
I disabled all extensions and  issue remains.

With the insider version i'm not seeing it.

**Comment by rebornix** [comment]
Could you please follow https://github.com/microsoft/vscode/wiki/Keybinding-Issues to provide more info when you run into the issue again?

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
