### ISSUE TITLE
Setting for Search Case Sensitivity and Regex

### ISSUE THREAD

**Issue by philoserf** [microsoft/vscode#77543]
Issue Type: <b>Feature Request</b>

I would like to have two settings for search.

Case Sensitive and Regex. I would like that setting to be manageable in the `settings.json` file.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by roblourens** [comment]
You can toggle these by clicking the buttons in the search box, and they will be persisted per workspace

**Comment by philoserf** [comment]
Closed? I was seeking a global setting. Not a workstation setting.
