### ISSUE TITLE
Launch custom task as variable

### ISSUE THREAD

**Issue by giantmustache** [microsoft/vscode#77556]
I have created a task in tasks.json and I would like to have the result as a variable that I can use in my launch.json.

An example:

    // tasks.json
    {
        "label": "party",
        "type": "shell",
        "command": "echo",
        "args": [
            "party"
        ]
    }

    // launch.json
    {
        "program": "someprogram.exe"
        "args": ["${task:party}"]
    }

I cannot find an alternative that makes it possible at this point and it would give a bunch of opportunities, like passing parameters and running some processing over a certain string. What if you could do `${task:replacebackslashes|somevarwithbackslashes}`? Sometimes I just need to process a variable before using it.

**Comment by alexr00** [comment]
This can now be accomplished with commands! https://code.visualstudio.com/docs/editor/variables-reference#_command-variables

**Comment by alexr00** [comment]
I think you could even write a single command that takes a task as an argument and "commandifys" it.

**Comment by giantmustache** [comment]
Can you show me an example of how you would do this? I don't think the tasks themselves are available as commands, right?

**Comment by alexr00** [comment]
That's correct, you'd have to write a command that that does whatever processing you need. Then you can reference that command in your task.
