### ISSUE TITLE
terminal window as whole new tab  , not a subset of current 

### ISSUE THREAD

**Issue by RishiNiranjan** [microsoft/vscode#77555]
I am used to working with linux terminal , with various tabs open simultaneously . And I easily cycle through them .

And I started preferring VScode than Vim for code writing.

But with vscode ,I would like to have that feel (first statement above) of many open terminals and cycling through tabs.

In vscode , Terminal (ctrl+~) opens as subset of open window (be it right or below or expended).

I do not find any option regarding open terminal as new seperate tab  ,
SO I can have one tab open for code editing, another tab for gcc execution , another for other terminal command execution.

Feature request : various terminals open as seperate tabs , like linux terminal tabs.

**Comment by Tyriar** [comment]
ctrl+shift+` will create a new "tab", currently they're all shown in the dropdown menu though, not through actual tabs. I have the following keybindings to allow me to easily switch between them:

```json
{ "key": "ctrl+shift+j",     "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",     "command": "workbench.action.terminal.focusPrevious" },
```

/duplicate #10546
