### ISSUE TITLE
Terminal cursor style changes on blink

### ISSUE THREAD

**Issue by karolfalkiewicz** [microsoft/vscode#77559]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Open internal terminal
2. In settings set cursor style for terminal to `line`
3. Enable cursor blinking
4. Check the cursor blinking

Info: Cursor changes style to `block` on every blink.
![cursor](https://user-images.githubusercontent.com/36987335/61443564-0b135080-a94a-11e9-8fc9-41e4035cd38f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by skprabhanjan** [comment]
@Tyriar , I cannot reproduce this issue.
The cursor blinking seems to be correct when I tried this.

**Comment by karolfalkiewicz** [comment]
@skprabhanjan I use zsh shell in integrated terminal, but this shoudn't be the case. Same shell works fine in normal Terminal app. When I switched shell to bash in integrated-terminal issue still occurs. It looks like when out of focus, integrated-terminal cursor ignores selected style and renders as block.

**Comment by Tyriar** [comment]
I can't repro either, it definitely seems to be happening though. @karolfalkiewicz have you set `terminal.integrated.rendererType`?

> It looks like when out of focus, integrated-terminal cursor ignores selected style and renders as block.

https://github.com/microsoft/vscode/issues/67410

**Comment by karolfalkiewicz** [comment]
@Tyriar I checked once again. It happens only when Renderer Type is set up to `dom`. `Canvas` or `auto` works fine.

**Comment by Tyriar** [comment]
@karolfalkiewicz it's fixed in the upcoming version
