### ISSUE TITLE
test-integration scripts print difficult to read output

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#77550]
Issue Type: <b>Bug</b>

**Repo**
1. Run `./scripts/test-integration.sh`

**Bug**
See that the output for some sections is printed as:

```
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'workspaceFile' ]
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'workspaceFolders' ]
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'getWorkspaceFolder' ]
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'openTextDocument' ]
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'openTextDocument, illegal path' ]
[ '  \u001b[32m  ✓\u001b[0m\u001b[90m %s\u001b[0m',
  'openTextDocument, untitled is dirty' ]
...
```

VS Code version: Code - Insiders 1.37.0-insider (112fa76c775ecb79ac2c9e9e5dba0d711d523543, 2019-07-17T05:34:19.397Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_2667147|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by octref** [comment]
Is this on Azure Devops? It's an issue for Azure Devops's handling of console output. On Travis it looks fine.

**Comment by mjbvz** [comment]
This also happens on my local machine when you run the tests from the tests from command line

**Comment by octref** [comment]
@Tyriar FYI, any clue why this would be happening?

**Comment by Tyriar** [comment]
Maybe if mocha was updated? I see it on all platforms.

**Comment by Tyriar** [comment]
I'm guessing this is related to 4dc738593b4fa0ec6bb72d8694c867f4c362c382, I tried to fix it but I haven't used mocha reporters before.

**Comment by joaomoreno** [comment]
FYI this is my first time looking at integration tests.

@Tyriar https://github.com/microsoft/vscode/commit/4dc738593b4fa0ec6bb72d8694c867f4c362c382 affected unit tests only. And it's a 1 year old change. This broke much more recently.

The fix ended up being related to array spreads, beware of them. https://github.com/microsoft/vscode/commit/70f5805cfe6f65d2d78f023f336df4deaf4ac555

cc @bpasero

**Comment by joaomoreno** [comment]
Build looks good now: https://dev.azure.com/vscode/VSCode/_build/results?buildId=23873

**Comment by Tyriar** [comment]
@joaomoreno thanks for looking into this
