### ISSUE TITLE
A black screen appears using ‘yarn run gulp -- vscode-win32-ia32’

### ISSUE THREAD

**Issue by zhouhangzooo** [microsoft/vscode#77563]
Package 32-bit systemsThe steps are as follows:
1. input ‘yarn run gulp -- vscode-win32-ia32’ in CMD；
2. When vscode is opened, the following situation appears
![image](https://user-images.githubusercontent.com/37395573/61445985-00c07900-a981-11e9-86b6-12520377aca6.png)
I wonder how to use packaged vscode for 32-bit computers?
![image](https://user-images.githubusercontent.com/37395573/61446447-bab7e500-a981-11e9-9cbc-588e148db37d.png)

**Comment by zhouhangzooo** [comment]
1.'yarn run gulp -- vscode-win32-ia32' was successfully 
2.open Vsocde error

**Comment by snowying001** [comment]
I has the same question

**Comment by joaomoreno** [comment]
If you are going to create a 32 bit package for Windows, you must install all dependencies for 32 bits as well. Make sure you compile all `yarn` dependencies for `ia32`.
