### ISSUE TITLE
Launching VS Code via Windows Subsystem Linux should return to prompt and suppress output

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#77566]
Issue Type: <b>Bug</b>

when i run vs code in cmd windows,there wil output the vs code update log:
![Launching VS Code via Windows Subsystem Linux should return to prompt and suppress output](https://user-images.githubusercontent.com/51827261/61448441-7a5a6600-a985-11e9-8a70-7f94692e98ce.jpg)

main 2019-07-18T06:57:11.468Z] update#setState idle
[main 2019-07-18T06:57:26.263Z] Received resolved authority wsl+Ubuntu-18.04[main 2019-07-18T06:57:31.121Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.121Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.121Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.121Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.122Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.122Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.127Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.127Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.129Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-18T06:57:31.129Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-18T06:57:41.486Z] update#setState checking for updates
[main 2019-07-18T06:57:41.754Z] update#setState idle
...

i find the issue report:https://github.com/Microsoft/vscode/issues/44540
and now the issue appears again,pls check.tks.

VS Code version: Code - Insiders 1.37.0-insider (52b6e7c4f58466e5b67348fb67d359f6bc3bb7e8, 2019-07-18T05:35:22.001Z)
OS version: Windows_NT x64 10.0.18936
Remote OS version: Linux x64 4.4.0-18936-Microsoft

**Comment by kinglionsz** [comment]
> I'm a bit confused about the screenshot.
> What you show is output in the 'Output View,' correct?
> You have a WSL window open?
> Looks like the messages come from the main which fails to load some image.
> Duplicate of microsoft/vscode-remote-release#966
yes
1,run wsl.exe
2,in the wsl windows, run code-insiders
and now , vs code is opening and the wsl windows output :

ubuntu@DESKTOP-J925CM6:/mnt/c/WINDOWS/system32$ code-insiders

[main 2019-07-19T14:44:28.712Z] update#setState idle
[main 2019-07-19T14:44:42.319Z] Received resolved authority wsl+Ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.949Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.950Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:58.715Z] update#setState checking for updates
[main 2019-07-19T14:44:58.989Z] update#setState idle

while vs code closed, the wsl windows stop output.

the Issue appears after I  update vs code. it is ok  before update. 

@aeschli

**Comment by kinglionsz** [comment]
> I'm a bit confused about the screenshot.
> What you show is output in the 'Output View,' correct?
> You have a WSL window open?
> Looks like the messages come from the main which fails to load some image.
> Duplicate of microsoft/vscode-remote-release#966


**yes
1,run wsl.exe
2,in the wsl windows, run code-insiders
and now , vs code is opening and the wsl windows output :**

ubuntu@DESKTOP-J925CM6:/mnt/c/WINDOWS/system32$ code-insiders
[main 2019-07-19T14:44:28.712Z] update#setState idle
[main 2019-07-19T14:44:42.319Z] Received resolved authority wsl+Ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.947Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.948Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.949Z] Resolving authority wsl+ubuntu-18.04
[main 2019-07-19T14:44:45.950Z] Didnot find resolved authority for wsl+ubuntu-18.04
[main 2019-07-19T14:44:58.715Z] update#setState checking for updates
[main 2019-07-19T14:44:58.989Z] update#setState idle

**while vs code closed, the wsl windows stop output.
the Issue appears after I update vs code. it is ok before update.**

@aeschli

**Comment by aeschli** [comment]
It's not a dup, now I understand...

**Comment by aeschli** [comment]
Caused by the fix for https://github.com/microsoft/vscode-remote-release/issues/914.

Reverted that change.

**Comment by aeschli** [comment]
This happened only when the opened instance was the first window opened.
