### ISSUE TITLE
Ubuntu 19.04 repository is broken

### ISSUE THREAD

**Issue by bluezio** [microsoft/vscode#77562]
I am using the Ubuntu 19.04 repository in a Dockerfile. During the build, Docker Hub reports the following:

```
Get:4 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages [8391 B]
Err:4 https://packages.microsoft.com/ubuntu/19.04/prod disco/main amd64 Packages
File has unexpected size (8578 != 8391). Mirror sync in progress? [IP: 40.76.35.62 443]
Hashes of expected file:
- Filesize:8391 [weak]
- SHA512:36c04ee2c54f8b17d055ca42d47e0959705419d1232011237f1e5d9b23212631275e5c7d62294023285d141b436dd619948851cb4234db5e136d72ad9e81450d
- SHA256:c8b08b97647637ee27db4e5ff5bcca1845eac34ddd84fde32c9de6ecc95f3c03
- SHA1:b173d5500f8801b0296d2ea9d778e7b4455077fa [weak]
- MD5Sum:2ed269198b20be9459f67e77010c92ec [weak]
```

This was running fine on my laptop yesterday. Did the repository just break today?

**Comment by bluezio** [comment]
Looking at the Release and InRelease files, InRelease seems to be out of date (one day behind).

**Comment by Tyriar** [comment]
vscode is not in https://packages.microsoft.com/ubuntu/19.04/prod...?

**Comment by crnisamuraj** [comment]
Same error still happening, seems that it is repeated from time to time. What is happening with repo?
Cant you really take more caution? i think having broken repo is big issue especioally if it happens every 2 months....

Fatal error: E: https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages is not (yet) available (File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.74.252.37 443]
Hashes of expected file:
 - Filesize:66619 [weak]
 - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
 - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
 - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
 - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
)

**Comment by Tyriar** [comment]
VS Code is not in that repo, it's in https://packages.microsoft.com/repos/vscode, why are you telling us?

**Comment by crnisamuraj** [comment]
That's strange, because that's url thats appended to /etc/apt/sources.list by .deb package during install

**Comment by Tyriar** [comment]
It shouldn't be 🤔 

https://github.com/microsoft/vscode/blob/026b470f49bc27ace5b270521c837657d0794970/resources/linux/debian/postinst.template#L59-L72

**Comment by crnisamuraj** [comment]
Well, I checed my soures.list.d/vscode.list and URL to repository is 
`deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main`
but the URL in error output was wrong....
today everything is working normally without any changes made in my filesystem... so definitely it was repository problem.

**Comment by crnisamuraj** [comment]
> Looking at the Release and InRelease files, InRelease seems to be out of date (one day behind).

I think this kind of issue happened, anyway it was a temporary problem, now its solved, and update is working as it's supposed to. tnx anyway.
