### ISSUE TITLE
Save as modal on 2nd monitor with other monitor 4K

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#77560]
- VSCode Version: 1.36.1
- OS Version: Windows 10

I have 3 monitors. Laptop set to 4K, and two normal 24" with 1920x1080

I work with VSCode on the 24" but when I want to save a new file I get huge Save As modal. It doesn't happen in different programs. My laptop has scaling enabled but the other monitors have no special settings applied..

![image](https://user-images.githubusercontent.com/16131590/61444252-ef587c00-a942-11e9-8a5d-b2ad3b44b036.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by moseleyi** [comment]
Same happens with any tooltips, they're huge:

![image](https://user-images.githubusercontent.com/16131590/61463745-f72d1600-a96c-11e9-9b38-cab734caf55d.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)
