### ISSUE TITLE
Grouped multi-file select in explorer

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#77575]
Basic multi-file select in the explorer is already working. However, it'd be nice to have the ability to multi-select different groups of files that are not located directly next to each other, without having to single select files outside of the first group.

In other words, on a Mac:

- select a file
- shift+click to select another four files below that
- skip down a couple files and cmd+click another file
- shift+click to select another four files below that
- note that now all of the files starting from your first selection have been selected, rather than having two selection groups

This feature request is the default behavior of macOS (if further examples are needed). Below shows what I'd like to be able achieve directly inside VSCode, where the second large group can be selected with another single cmd+click followed by a shift+click.

<img width="1440" alt="example" src="https://user-images.githubusercontent.com/12591890/61463653-7b19da80-a93a-11e9-9bdf-710c2e4b11cd.png">

**Comment by isidorn** [comment]
I understand the request.
Currently this is only possible by using the keyboard, so please use that as a workaround. up/down keys + shift

All in all this is a feature request for the tree, thus forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
This is actually implemented... it just broke at some point.

**Comment by lramos15** [comment]
There appears to be a regression in tree multi select. If I have three folders click the first one and then shift + click the other two you will see that the selection moves rather than selecting all three folders.

**Comment by joaomoreno** [comment]
@lramos15 Can you show me a video recording? I can't reproduce, works fine over here.

**Comment by joaomoreno** [comment]
I can repro. @roblourens This is bad, fixing for July.

**Comment by joaomoreno** [comment]
@lramos15 Great catch!
