### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by tady159** [microsoft/vscode#77574]
Issue Type: <b>Bug</b>

Today I was working with a text file with fixed-width fields. Each line has 360 columns and I wanted to wrap the lines so I wouldn't have to scroll horizontally. However, between columns 198 and 201, which is close to the width of my viewport, there is a sequence of 4 spaces that refer to two distinct fields. Visual Studio Code is breaking the line after the entire sequence of spaces at column 202, even though there's still a little bit of space left in my viewport, which can reach column 216. However, there is a record which has the second field filled with data, making the sequence of spaces only 2 columns wide. Visual Studio Code still wraps the line after the last space, at column 200 this time, and this throws off the alignment of that line in comparison with the others.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz (6 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
php-intellisense|fel|2.3.10
vscode-firefox-debug|hbe|1.8.0
debugger-for-chrome|msj|4.11.6
debugger-for-edge|msj|1.0.10

</details>

**Comment by alexandrudima** [comment]
@tady159 Can you share a screenshot? Can you share the text that causes the issue? Are you perhaps using a non-monospace font?

**Comment by alexandrudima** [comment]
@tady159 Can you please share a screenshot? Or maybe the text that reproduce the problem? Are you using a monospace font?

**Comment by tady159** [comment]
@alexandrudima I'm using the default font. Since the data is confidential, I had to replace its contents with something nonsensical, but still shows the incorrect line wrapping. I've extracted two record as samples just to show the misalignment.
[file.txt](https://github.com/microsoft/vscode/files/3487611/file.txt)
![misaligned](https://user-images.githubusercontent.com/8518463/62800682-5983bd00-baba-11e9-8714-bd672a80ca34.png)

**Comment by alexandrudima** [comment]
@tady159 Thank you for following through. I can reproduce, but this is not a bug, this is just how **word wrapping** works:

Here I have reduced the repro to the relevant parts to simplify reasoning:
```
some text                 0000000000000000000    000000000000000000                    *
some text                 0000000000000000000  00000000000000000000                    *
```

Without word wrapping:
![image](https://user-images.githubusercontent.com/5047891/62851000-fb86ed80-bce4-11e9-9d96-060fb096b49f.png)

With word wrapping:
![image](https://user-images.githubusercontent.com/5047891/62851012-03df2880-bce5-11e9-9fad-2aa45053f7ac.png)

The second line contains a word which is slightly longer (by 2 characters). The first line contains 4 spaces, while the second line contains 2 spaces. The word wrapping is computed such that it tries really hard to **not break inside words**. Therefore, the misalignment of the final `*` occurs.
