### ISSUE TITLE
checkJs does not recognize properties assigned with lodash

### ISSUE THREAD

**Issue by kevinszuchet** [microsoft/vscode#77578]
- VSCode Version: 1.36.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Enable "javascript.implicitProjectConfig.checkJs"
2. Use lodash method to **assign** some properties to **this**
3. Try to use any property

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/31735779/61466135-bd99e200-a94f-11e9-89a6-c495f9db8fc0.png)

**Comment by mjbvz** [comment]
This is a limitation of our IntelliSense which is powered by JavaScript. Please file a feature request against TypeScript upstream: https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md
