### ISSUE TITLE
Error peek view triangle not correct color

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#77587]
When using the error peek view, the triangle tip does not respect the correct error color and is always yellow:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/35271042/61478157-ceddf100-a945-11e9-86eb-7b313d070672.png">

<img width="133" alt="image" src="https://user-images.githubusercontent.com/35271042/61478174-d8ffef80-a945-11e9-8855-6d759b1bdaa6.png">

**Comment by sandy081** [comment]
Looks like the rules are not getting deleted and overridden. 
`Arrow` widget deletes the old rule and adds new rule with new colours and which is not working.

@jrieken Moving this back to you.

**Comment by jrieken** [comment]
fixed by reverting https://github.com/microsoft/vscode/commit/5565ddd88c6350f90e1031be4ce0d6089ac73a57
