### ISSUE TITLE
Using the Chinese input method that comes with the system, you cannot type punctuation on the console normally.

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#77581]
Issue Type: <b>Bug</b>

I am using the input method of the Window system. When I use the Chinese input method, I want to type some punctuation marks (such as <code>"</code> ,<code> '</code>,<code>!</code>) on the terminal, and I will not immediately display the corresponding Symbol, which needs to be typed multiple times to appear.

The punctuation of my Chinese input method is in punctuation format in English.At the same time, the above phenomenon does not appear on the directly opened terminal.

**Below is the GIF image that I saved after I disabled all extensions**.

When using the Chinese input method that comes with the system:
**( I have typed the corresponding button multiple times.)**
![error_ch](https://user-images.githubusercontent.com/13393959/61470919-6e39cd00-a9b4-11e9-8311-ee1c9f3e31d0.gif)

The following is the use of English input method:

![error_en](https://user-images.githubusercontent.com/13393959/61471003-9a554e00-a9b4-11e9-897a-a0fe000b833a.gif)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by czfadmin** [comment]
@jianboy .Thank you, just like the operation in your GIF, I tried this is normal, but the problem I encountered was that when I was in Chinese input method, it would appear when I had to enter the table **dot symbol**, and it would only appear when I clicked multiple times.

**Comment by czfadmin** [comment]
There's nothing wrong with my keyboard.I just found that in the case of Chinese input method, the same situation will occur when I type Numbers.

**Comment by jianboy** [comment]
小兄弟，输入法不太会用吧。中英文完全没问题！

console本质上就是一个输入框！不存在不能输入的问题。

![7](https://user-images.githubusercontent.com/11532015/61485193-20808d00-a9d3-11e9-8f74-0c16bc89108d.gif)

**Comment by rebornix** [comment]
That's how the IME works. When you are using Chinese IME, typing quotes will not insert `"` immediately into the editor, instead it will enter composition mode.

**Comment by czfadmin** [comment]
> 小兄弟，输入法不太会用吧。中英文完全没问题！
> 
> 控制台本质上就是一个输入框！不存在不能输入的问题。
> 
> ![7](https://user-images.githubusercontent.com/11532015/61485193-20808d00-a9d3-11e9-8f74-0c16bc89108d.gif)

你那个录制案按键快捷方式是什么软件啊

**Comment by jianboy** [comment]
> > 小兄弟，输入法不太会用吧。中英文完全没问题！
> > 控制台本质上就是一个输入框！不存在不能输入的问题。
> > ![7](https://user-images.githubusercontent.com/11532015/61485193-20808d00-a9d3-11e9-8f74-0c16bc89108d.gif)
> 
> 你那个录制案按键快捷方式是什么软件啊


https://github.com/jianboy/AutoHotkey-Script

**Comment by czfadmin** [comment]
@jianboy    很不错的工具啊,多谢了;
![error_ch](https://user-images.githubusercontent.com/13393959/61502712-87b83480-aa07-11e9-8f24-b982617d4668.gif)

**Comment by LittleClown** [comment]
@czfadmin hey，我也遇到了和你一样的问题，今天无意中找到一个可行的方法（问题原因没有找到，无意中试出来的，也没有兴趣去深究，仅作分享以供参考），希望对你有帮助：

  * 在中文输入法设置中，进入 `Keys` 页面，保证里面的 `Chinese/English punctuation switch` 选中 `ctrl + .`
  * 在 `vscode` 终端下执行一次这个快捷键，同时输入一些符号；
  * 最后切换中文标点模式，即可在 `vscode` 终端顺畅输入中文标点了
