### ISSUE TITLE
yarn package cache inside the code-insiders snap dir

### ISSUE THREAD

**Issue by kinghat** [microsoft/vscode#77580]
im seeing yarn package cache inside of my code-insiders snap dir instead of using the `yarn cache dir` which is :
```
$ yarn cache dir
/home/kinghat/.cache/yarn/v4
```
for me.
![image](https://user-images.githubusercontent.com/16073360/61469066-2e3b0180-a944-11e9-90c7-5d51a7db8901.png)

from `yarn`:

> this is the code that yarn would use to determine where the cache is:
> https://github.com/yarnpkg/yarn/blob/master/src/util/user-dirs.js#L26
> maybe there is something odd about the snap environment when yarn is run that causes it to look under code-insiders/common? though it looks like it would have to think your homedir was set to that directory in order to have that happen. seems weird...
> 
> :thinking: not sure where those files would have come from then. Maybe they are part of code-insiders (since vscode is a JS/electron app). You could try deleting that cache dir and see if everything still works 

ive removed the dir and it comes back with yarn use. maybe this is normal and shouldnt be worried about? :man_shrugging:

**Comment by Tyriar** [comment]
@flexiondotorg is there a way to workaround this sort of thing so it uses the shared cache in `$HOME`? I thought classic confinement would have done this automatically?

**Comment by kinghat** [comment]
@Tyriar do you happen to know if this was fixed upstream?

**Comment by Tyriar** [comment]
@kinghat no, please report to the snapcraft team I don't believe we can action this on our end.
