### ISSUE TITLE
Release notes open in all open windows

### ISSUE THREAD

**Issue by joachim-n** [microsoft/vscode#77583]
Issue Type: <b>Bug</b>

When VS Code updates itself, the release notes appear in all open windows, and it's a pain to have to close all of them.

Suggested fix: Only open release notes in the frontmost window.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.0.0

**Comment by mjbvz** [comment]
Previously #25800
