### ISSUE TITLE
Search seems slow

### ISSUE THREAD

**Issue by philipjrosen** [microsoft/vscode#77586]
Issue Type: <b>Bug</b>

Recently I'v noticed that searching for things in our codebase (large but not huge) can be slow and can also cause the VSCode to freeze for a while. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
vscode-coffeescript-preview|dre|1.0.1
gitlens|eam|9.8.5
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
rest-client|hum|0.21.3
coffeelinter|lky|1.4.0
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
vscode-css-peek|pra|3.0.2
sass-indented|rob|1.5.1
addDocComments|ste|0.0.8
gitblame|wad|2.8.1
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by rvinzent** [comment]
I am seeing extremely slow global search as well with Mojave 10.14.5 and the same version of VScode. It's so bad that the window eventually crashes. I have a multi-root workspace with two medium-large sized projects and I am searching for text enclosed in single quotes with regex turned on.

Hope this helps the issue to be resolved quickly.

**Comment by roblourens** [comment]
Please see whether any of the tips in this wiki help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
