### ISSUE TITLE
Provide way to self-diagnose TS server re-initializing

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#77597]
I frequently run into the issue where every time I open a JS file, I'll get the "Initializing JS/TS language features" message, which eats up all my CPU for a minute or so.

The problem is, it comes and goes, and is difficult to consistently reproduce. I've opened issues, but they usually end up getting closed because of this difficulty.

Could some logging be added to tsserver.log that clarifies what the cause of the re-initialization is?

**Comment by mjbvz** [comment]
Can you share an example tsserver log? It already should have this information in it, but it may not be clearly marked

**Comment by jacobweber** [comment]
@mjbvz Yeah, but it's got stuff in it that I don't want to post publicly, and because of #75748 I'm not sure how to upload it privately anymore. Anything I can look for myself?

**Comment by mjbvz** [comment]
Followed up on #77533 

For this issue, TS server log is really not meant for anyone except the members of the vscode or TypeScript dev teams. This is who the TS server log was designed for.

The loading indicator is one of the user facing ways we expose the TS server state to end users. If you have other ideas on how we could improve this, let me know but I don't think focusing on the server log itself is the correct direction

**Comment by jacobweber** [comment]
OK. In that case, can I consider it a bug worth reporting, whenever that "Initializing" message re-appears, even if it's not consistently reproducible or it happens with extensions enabled? (Not including the first time and times when I change config settings.)

**Comment by mjbvz** [comment]
The initializing indicator is expected to show up whenever a new js/ts project is loaded. Because we unload inactive projects, it may show up multiple times per session depending on which files you open and close. But it should always go away and we in generally should not unload and reload the same project
