### ISSUE TITLE
Git status isn't updating correctly

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode#77599]
Issue Type: <b>Bug</b>

Within the last week or two, it seems like the Git integration is not working, or something is getting cached when it shouldn't.

From the terminal in VSCode, I can see nothing or a single file has changed. But from the Source Control: Git (top left) window, I see more than 5K file changes. Closing that VSCode entirely and reopening to the same project seems to fix it. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
vscode-markdownlint|Dav|0.28.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.11
docs-preview|doc|0.3.24
docs-yaml|doc|0.2.3
day-night-theme-switcher|fre|0.1.2
vscode-azurefunctions|ms-|0.17.1
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
powershell|ms-|2019.5.0
debugger-for-chrome|msj|4.11.6
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17

</details>

**Comment by joaomoreno** [comment]
Is there anything special about your workspace?

Can you reproduce this in another workspace?
