### ISSUE TITLE
UI issues with lots of git submodules

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#77590]
When a git repo has lots of git submodules in different folders outside the folder you are editing with vs code, the vs code source control tab gets crowded out with all those submodules such that you can hardly see the project you are working on.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. clone https://intelligentdevices.visualstudio.com/EMLL/_git/ELL-firmware
2. cd MXCHIP\mbed-keyword-spotter
3. code .

Does this issue occur when all extensions are disabled?: Yes

See:

![image](https://user-images.githubusercontent.com/18707114/61481839-fa64d980-a94d-11e9-8aa3-0bf55668fc66.png)

**Comment by joaomoreno** [comment]
> such that you can hardly see the project you are working on.

You can simply select each repository in the top panel and scope your work.
