### ISSUE TITLE
Opening a specific workspace also opens 'untitled' workspace

### ISSUE THREAD

**Issue by ronbos** [microsoft/vscode#77596]
Issue Type: <b>Bug</b>

1. Pin VS Code icon to taskbar
2. Right click on the VS Code Icon and select a specific workspace
3. Two VS Code windows will open, one that was clicked on, and "Untitled" workspace

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ini-for-vscode|Dav|0.0.4
json-and-jsonc|htw|1.0.1
reg|ion|1.0.1
python|ms-|2019.6.24221
vscode-ai|ms-|0.5.1
azure-account|ms-|0.8.4
cpptools|ms-|0.24.0
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
proto|pet|0.0.2

</details>

**Comment by bpasero** [comment]
This works as designed. Untitled workspaces will open until they are closed to preserve the possibly user data associated with it.
