### ISSUE TITLE
Debug Console scrolls to top after every command I run in python

### ISSUE THREAD

**Issue by eraoul** [microsoft/vscode#77598]
Issue Type: <b>Bug</b>

This is in python.  If I output a large output (such as a large dataframe), then every successive command causes the window to scroll back to the top, and I have to scroll down again to see the results. It's super annoying.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
RunOnSave|eme|0.2.0
vscode-test-explorer|hbe|2.13.0
nbpreviewer|jit|1.2.2
vscode-python-test-adapter|lit|0.3.8
linecounter|lyz|0.2.2
rainbow-csv|mec|1.1.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
team|ms-|1.149.2
vscode-yaml|red|0.4.1
vscode-coverage-gutters|rya|2.4.0
indenticator|Sir|0.6.0
vscode-counter|uct|1.2.0

</details>

**Comment by isidorn** [comment]
This should be fixed with latest vscode insiders 
https://code.visualstudio.com/insiders/

Let me know if you an still reproduce.
And if you can, please write down exact reproducable steps.
Thanks!
