### ISSUE TITLE
Better support for the functional icon(color picker, etc.)

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7759]
In VSCode, we have supported the display color icon.
But in fact, in order to better user experience, we may need to show more icons.

For the icon you can click on the pop-up layer to do some visualization of the operation, such as color picker(https://github.com/Microsoft/vscode/issues/625, https://github.com/Microsoft/vscode/issues/4329)

In this issue(https://github.com/Microsoft/vscode/issues/7757), I expect to be able to support the display angle Icon.

![Firefox DevTools](https://img.alicdn.com/tps/TB1zhUgKpXXXXX0XFXXXXXXXXXX-400-171.gif)

**In Firefox, there are more icon features.**
- CSS filter editor  
  ![](https://img.alicdn.com/tps/TB1BoY3KpXXXXXmaXXXXXXXXXXX-780-341.png)
- CSS border editor https://bugzilla.mozilla.org/show_bug.cgi?id=1272148  
  ![](https://bug1272148.bmoattachments.org/attachment.cgi?id=8755272)

**Hope VSCode can be better and better** 👻 .

**Comment by 0x4E69676874466F78** [comment]
+1
You can also make autocompletion as in dreamweaver:
https://youtu.be/fO9TR5aYt0E?t=93
