### ISSUE TITLE
php 7 support

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#776]
Wanna see php 7 support in next version.

**Comment by egamma** [comment]
What is missing for php 7 support? You can configure the linter you want to use. I assume php 7 provides the -l option?

Is it coloring?

**Comment by Spy-Seth** [comment]
It's my be the extended type hinting that PHP7 provide.

**Comment by brunnopleffken** [comment]
There's still some broken things with PHP 7, like type hinting (```function xxxx(): array {}```) and null coalescing operator, as shown below:


<img width="428" alt="screen shot 2016-03-07 at 17 31 08" src="https://cloud.githubusercontent.com/assets/3427344/13582302/69562376-e48a-11e5-9301-32d6f704b62b.png">

**Comment by zbandhan** [comment]
No MYSQLi API suggestion in intellisenxe

**Comment by niksumeiko** [comment]
+1 for [null coalescing operator](https://wiki.php.net/rfc/isset_ternary) support

**Comment by roblourens** [comment]
Is there still anything to be done here? I don't see an error for the `??` operator.

**Comment by alejosky** [comment]
+1 for null coalescing operator support
