### ISSUE TITLE
an inaccurate detect on git version

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#77607]
I've update git to 2.22.0,but the vscode still send me a warning,"you seem to have git 1.8.3.1" installed. code works best with git >=2".
![image](https://user-images.githubusercontent.com/27731323/61500656-cc8b9d80-a9fe-11e9-949a-10c79482d8a6.png)

**Comment by mjbvz** [comment]
If you run `git --version` in the integrated terminal, what version is printed?

**Comment by bonaluo** [comment]
git version 2.22.0.windows.1
![image](https://user-images.githubusercontent.com/27731323/61572633-5b69ea00-aad3-11e9-8754-56e0e8acb105.png)

**Comment by bonaluo** [comment]
When I open a new window with remote-ssh, he always reminds me that my git version is only 1.8.
![image](https://user-images.githubusercontent.com/27731323/61572655-a126b280-aad3-11e9-8e4a-b9d9fa98cbb2.png)

**Comment by joaomoreno** [comment]
If you run `git --version` in the **remote machine**, what version is printed?
