### ISSUE TITLE
VSCode find operation is too expensive for system resources

### ISSUE THREAD

**Issue by JiZimo** [microsoft/vscode#77606]
VSCode uses about 4G of memory when it looks up strings in a large file (about 60M) and causes VSCode to crash (the provided task manager view is not the time to use the most memory)
![image](https://user-images.githubusercontent.com/20215395/61500202-b977ce00-a9fc-11e9-9f5a-b0f2fcbd211b.png)
![image](https://user-images.githubusercontent.com/20215395/61500204-bda3eb80-a9fc-11e9-9c63-09f68b3a3fe3.png)

**Comment by roblourens** [comment]
Can you explain exactly what you are doing when this happens? What do you mean "looks up strings"?

**Comment by JiZimo** [comment]
@roblourens Ctrl+F My English is poor so I can't describe it very well 😢

**Comment by rebornix** [comment]
@JiZimo could you please provide the data to help troubleshoot? Like the file and query you are searching.

**Comment by JiZimo** [comment]
File:Top 100 million pi
search:341124

**Comment by rebornix** [comment]
A costly a find operation might hang the whole system which is an known issue.
