### ISSUE TITLE
VSCode hangs while starting in WSL

### ISSUE THREAD

**Issue by offero** [microsoft/vscode#77600]
This bug is while using insiders with the Remote WSL extension

- VSCode Version: 
```
+ λ code-insiders --version
1.37.0-insider
360e4e4dfa989135f28edc0d6f7e42df33cddf87
x64
```

- OS Version: Windows 10 WSL

Steps to Reproduce:

1. Run code-insiders .
2. IDE loads, status says Opening Remote but the IDE just hangs in the loading screen.

![image](https://user-images.githubusercontent.com/4681330/61490609-63167b00-a97b-11e9-8c21-7bd032d4a0f2.png)

Does this issue occur when all extensions are disabled?: Yes/No

This bug requires the remote extensions.

Log:
```
[2019-07-18 20:38:21.594] Starting VS Code Server inside WSL (Ubuntu)
[2019-07-18 20:38:21.595] Extension version: 0.38.10, Windows build: 18362. Multi distro support: enabled. WSL path support: enabled
[2019-07-18 20:38:21.999] WSL resolver response: undefined:57286

```

**Comment by aeschli** [comment]
Is there another WSL window open? Can you see if there's more in that Windows WSL terminal?

**Comment by offero** [comment]
There was another WSL window open when it happened, yes.

**Comment by aeschli** [comment]
Closing. If you see it again, please report to https://github.com/microsoft/vscode-remote-release/issues
