### ISSUE TITLE
New comments added to comment threads aren't shown

### ISSUE THREAD

**Issue by BenPryor** [microsoft/vscode#77605]
- VSCode Version: 1.37.0-insider

Repro steps:

1. Build and run the comment sample ([vscode-extension-samples/comment-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample))
2. Open a file, click in the gutter to start a comment thread, type some text, and click Create Note to add the first comment to the thread
3. With the thread still open, again enter text in the text box, and click Reply

Expected result: The second comment should be shown
Actual: The thread only shows the first comment

This can be worked around in the extension by disposing the original comment thread and creating a new one:
```typescript
function replyNote(reply: vscode.CommentReply) {
    let thread = reply.thread;
    thread.dispose();

    let newComment = new NoteComment(reply.text, vscode.CommentMode.Preview, { name: 'vscode' }, thread);
    _commentController!.createCommentThread(thread.uri, thread.range, [...thread.comments, newComment])
        .collapsibleState = vscode.CommentThreadCollapsibleState.Expanded;
}
```

**Comment by BenPryor** [comment]
Copying @rebornix and @RMacfarlane - since i see you folks have looked at other issues in this area recently.

**Comment by RMacfarlane** [comment]
Hmm, @BenPryor is this the insider’s version from today? I’m having trouble reproducing right now with that and the current version of the comment sample. Can you check the dev console (`F1` -> `Developer: Toggle Developer Tools`) to see if anything gets printed then? Otherwise my hunch would be that there is a timing issue with updating the comments.

**Comment by BenPryor** [comment]
Thanks for taking a look.

I'm on the Insiders version from 2019-07-18T14:11:10.247Z. I ran through the repro with the dev console showing, but nothing was logged.

<details>
    <summary>Full version info</summary>

Version: 1.37.0-insider (user setup)
Commit: fd5985489982fe14381dd56e6f0b29c53d5f991b
Date: 2019-07-18T14:11:10.247Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

</details>

**Comment by BenPryor** [comment]
And, I just updated to the very latest Insiders build (628bdedf671d3230fc76982fae845875a6f6c0da, 2019-07-19T10:33:04.702Z) and the issue looks like it no longer repros. Going to do a bit more testing to be sure, but looks like this may have been fixed.

**Comment by rebornix** [comment]
I pushed a fix with using correct comment id, which should fix the issue properly.
