### ISSUE TITLE
vscode.d.ts missing from vscode npm package 1.1.34 and 1.1.35

### ISSUE THREAD

**Issue by joechung-msft** [microsoft/vscode#77610]
- VSCode Version: 1.1.34, 1.1.35
- OS Version:

Steps to Reproduce:

1. Create a new folder.
2. `npm init -y` in the new folder.
3. `npm install -D @types/vscode@1.1.34` (or 1.1.35)
4. `tsc --init`
5. Create an `index.ts` file with the following code:

````ts
import * as vscode from "vscode";
````

6. `tsc` to compile.

Expected:
TypeScript should be able to find `vscode.d.ts`.

Actual:
`index.ts:1:25 - error TS2307: Cannot find module 'vscode'`

1.1.33
![image](https://user-images.githubusercontent.com/26208574/61502635-8a744480-a989-11e9-9e60-bd27a60841f3.png)

1.1.34
![image](https://user-images.githubusercontent.com/26208574/61502614-7cbebf00-a989-11e9-890b-1db7ce10da20.png)

1.1.35
![image](https://user-images.githubusercontent.com/26208574/61502650-995af700-a989-11e9-8a0f-e21ed34b92d1.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
> @types/vscode@1.1.34

This is wrong. You installed `vscode@1.1.34`. `@types/vscode` share version number with VS Code. For example, latest is `@types/vscode@1.36.0`.

**Comment by joechung-msft** [comment]
Let me get this straight.  You're saying that it is as designed that the @types/vscode package should not include the vscode.d.ts types file?

**Comment by joechung-msft** [comment]
Can we update the `vscode` package description to reflect that it no longer contains `vscode.d.ts`?

https://www.npmjs.com/package/vscode

![image](https://user-images.githubusercontent.com/26208574/61596729-21284780-abbc-11e9-8904-98d593c79d01.png)
