### ISSUE TITLE
space font size is too narrow

### ISSUE THREAD

**Issue by yan-ace62** [microsoft/vscode#77612]
- VSCode Version: 1.36
- OS Version:ubuntu18.04

Steps to Reproduce:

1. I upgraded vscode from 1.36 to 1.361, but I found that the space character font size became very small. When I indent 8 space characters, the font size equal four Latin alphabet.
2. You can see this display problem from the picture below.
![space font size](https://user-images.githubusercontent.com/38411792/61503863-db2c8180-aa0b-11e9-8b93-7c2b6e96258c.png)

Does this issue occur when all extensions are disabled?: yes

**Comment by JoyNop** [comment]
我也遇到这个问题了TUT

**Comment by yuhao-kuo** [comment]
I also encountered this problem and the terminal was out of control.

![term](https://user-images.githubusercontent.com/12791051/61527522-37fd5b80-aa4f-11e9-8015-a78f5f7ec918.png)

* os: ubuntu mate 18.04.2
* vscode version: 1.36.1 x64

**Comment by smallp** [comment]
Same issue, and downgrading to 1.35.1 does not help.

**Comment by Tyriar** [comment]
Use a monospace font in the `editor.fontFamily` setting

**Comment by yuhao-kuo** [comment]
@Tyriar, I fixed the `edit.fontfamily` settings. The font still hasn't changed.

**Comment by smallp** [comment]
@yuhao-kuo Try to add `"editor.fontFamily": "monospace"` in setting to overwrite the default setting. It works for me.

**Comment by caidwang** [comment]
@smallp It works. Thanks.

**Comment by yuhao-kuo** [comment]
@smallp I'm fix `"editor.fontFamily": "monospace"`and restart vscode it work. Thanks.
