### ISSUE TITLE
Create new file - default to LF, not CRLF

### ISSUE THREAD

**Issue by reactivize** [Microsoft/vscode#7761]
- VSCode Version: 1.3.0-insider, nightly build
- OS Version: Win10

Steps to Reproduce:

1. create a new file
2. is CRLF by default
- so I always have to change it's settings to LF, to keep all my project files consistently LF.

p.s.
Great work guys and gals!
I'm loving VSC.

**Comment by glen-84** [comment]
Add `"files.eol": "\n"` to your settings file.

**Comment by reactivize** [comment]
Works, thanks.
I was searching the settings for "LF" and "CRLF", didn't think to search for \n
