### ISSUE TITLE
Providing ${relativeFileDirname} in Variables Reference

### ISSUE THREAD

**Issue by liushiqi9** [microsoft/vscode#77616]
In Variables Reference, we currently have ${relativeFile} and ${workspaceFolder}.
A common structure of project is having a structure like ${workspaceFolder}/build64/${relativeFileDirname}/${filebasenameNoExtension} as the binary file of ${workspaceFolder}/${relativeFile}. 
Supporting ${relativeFileDirname} can make the launch.json work with this kind of structure.

**Comment by weinand** [comment]
When looking at the existing variables in https://code.visualstudio.com/docs/editor/variables-reference, I think the correct name (and associated semantics) would be `${relativeFileDirname}`.
@liushiqi9 correct?

**Comment by liushiqi9** [comment]
> When looking at the existing variables in https://code.visualstudio.com/docs/editor/variables-reference, I think the correct name (and associated semantics) would be `${relativeFileDirname}`.
> @liushiqi9 correct?

Correct, I will change the issue name and description.

**Comment by weinand** [comment]
@liushiqi9 please try in the next Insiders.

**Comment by weinand** [comment]
and this is the doc change: https://github.com/microsoft/vscode-docs/commit/4565a599624826e88b0f47bf379374be913f275d

**Comment by liushiqi9** [comment]
Don't forget to edit https://code.visualstudio.com/docs/editor/variables-reference page.  
Thanks for the help and fast response.

**Comment by weinand** [comment]
@liushiqi9 my doc change from above will change the variables-reference page when we release Stable.
