### ISSUE TITLE
If #Set-Location is set in Documents/WindowsPowerShell/profile.ps1, tasks only run in this directory.

### ISSUE THREAD

**Issue by JonathanBuchner** [microsoft/vscode#77614]
- VSCode Version: 1.36.1
- OS Version: Windows 1809

Steps to Reproduce:
1. In Documents\WindowsPowerShell create the file profile.ps1.  Add the below line and save. 
#Set-Location C:\

2. Open powershell.  The default directory should be C:\

3. Open an Electon project that has a tasks.json file in the .vscode folder.  My tasks.json looks like this:
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "npm",
            "script": "build",
            "group": "build",
            "options": {
                "cwd": "${workspaceRoot}\\"
            }
        }
    ]
}

4. Run the task

Actual: The console opens in directory C:\  and executes npm run build

Desire: Task runs in the root folder instead of the folder set in profile.ps1

Thanks,

Jonathan

**Comment by alexr00** [comment]
This is intentional. Can you add an argument for skipping the profile? Maybe:
```
			"options": {
				"shell": {
					"executable": "powershell.exe",
					"args": ["-NoProfile", "-Command"]
				}
			},
```
