### ISSUE TITLE
Setting to define import precedence based on folders/location of definition

### ISSUE THREAD

**Issue by AlexAegis** [microsoft/vscode#77623]
Even with `"editor.suggest.localityBonus": true,` (Because I think that only changes the precedence if it's in the file you are editing) when I'm trying to import something with the same name as another thing in a library, the one in the library takes precedence (in this case) because of alphabetic order.

![image](https://user-images.githubusercontent.com/16900547/61516350-16778200-aa05-11e9-9639-54d09dd88731.png)

This means that I can't use import all because it would import the wrong one.

With an option that would allow to tell vscode to prefer things in a certain folder (`src`) and everything else is behind that, this can be solved in a flexible way.

Suggestion:

(.vscode/settings.json)
```json
"editor.suggest.folderPrecedence": ['src', 'node_modules'],
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for this feature
