### ISSUE TITLE
Strange style in Terminal & Code 

### ISSUE THREAD

**Issue by 5987dogking** [microsoft/vscode#77621]
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic

Steps to Reproduce:

1.Terminal › Integrated: Letter Spacing is default value 0
My User Setting.json
{
    "window.zoomLevel": 3,
    "workbench.colorTheme": "Default High Contrast"
}

![image](https://user-images.githubusercontent.com/27723079/61513474-bcd87d00-aa2f-11e9-9fb0-9f1fff179fdd.png)

![image](https://user-images.githubusercontent.com/27723079/61513522-ebeeee80-aa2f-11e9-8cdb-dc50d2d3674c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
You're using a non-monospace font, you should set one in `terminal.integrated.fontFamily` (and `editor.fontFamily`)
