### ISSUE TITLE
Unit tests: Keybinding service NPE

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#77622]
I see this when running the unit tests with `--debug`:

```
Uncaught (in promise) TypeError: this._storageService.getBoolean is not a function
    at TestKeyboardMapperFactory.setActiveKeyMapping (keymapService.js:141)
    at _getBrowserKeyMapping.then.keyMap (keymapService.js:198)
```

No test fails, though.

**Comment by joaomoreno** [comment]
Actually I see a lot more on my Linux box:

![image](https://user-images.githubusercontent.com/22350/61881780-813e2700-aef7-11e9-849e-8c334426a4c8.png)

**Comment by rebornix** [comment]
@joaomoreno I fixed the error message so now it displays warning as expected. The warning is used to help us troubleshoot when chromium's keymap result conflicts with the keyboard event, which also means it's a bug in chromium's implementation of the keymap API.

**Comment by joaomoreno** [comment]
Makes sense... but should this really be running during our Unit Test suite?

**Comment by rebornix** [comment]
I removed the code base as currently on Linux and Windows, the error is almost everywhere. Chromium already fixed it so we can have this turned on once they ship.
