### ISSUE TITLE
Regression Bug: Feedback icon cannot be hidden

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/vscode#77629]
Issue Type: <b>Bug</b>

Regression Bug: Feedback icon cannot be hidden as implemented in https://github.com/microsoft/vscode/issues/41189

```
"workbench.statusBar.feedback.visible": false
```

The hint returns: `Unknown configuration setting`

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by usernamehw** [comment]
https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items
