### ISSUE TITLE
editor freezes with big project

### ISSUE THREAD

**Issue by itzmanish** [microsoft/vscode#77636]
- VSCode Version: 1.36.1
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Linux x64 4.9.0-9-amd64

Steps to Reproduce:

1. Load big project with 20k lines of code in some files and have more than 30 files in workspace.
2. Then open a file and start editing it. After one single word addition it freezes. On outline it seems something loading and loading.
3. I use some extension including vim and mostly for React projects.

It is very bad beacuse i am not able to complete my project beacuse of this.
I only use vscode and mine most configuration is based on vscode. So please do something.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
So this does not happen when you disable all extensions?

**Comment by itzmanish** [comment]
I can't figure out exactly which extension does it. My outline tab keep loading on a react component which i have open in editor.

**Comment by mjbvz** [comment]
But if you disable all extensions, you don't see this?

**Comment by itzmanish** [comment]
Yes

**Comment by svipas** [comment]
@itzmanish Please share all your extension list by running this in terminal: `code --list-extensions` before that make sure you run this command in VS Code command palette: `Shell Command: Install 'code' command in PATH`.

And @mjbvz is asking you if you disable all extensions by doing this in command palette: `Extensions: Disable All Installed Extensions` is an issue still exists?

**Comment by itzmanish** [comment]
> Please share all your extension list by running this in terminal: code --list-extensions

mahadev@kailash:~$ code --list-extensions
akamud.vscode-theme-onedark
austin.code-gnu-global
CoenraadS.bracket-pair-colorizer-2
cssho.vscode-svgviewer
Dart-Code.dart-code
Dart-Code.flutter
deerawan.vscode-faker
DiemasMichiels.emulate
dracula-theme.theme-dracula
dsznajder.es7-react-js-snippets
eamodio.gitlens
Equinusocio.vsc-material-theme
esbenp.prettier-vscode
formulahendry.auto-rename-tag
markskelton.one-dark-pro-italic
mikestead.dotenv
ms-vscode.cpptools
ms-vscode.Go
mtxr.sqltools
naumovs.color-highlight
oderwat.indent-rainbow
Orta.vscode-jest
pranaygp.vscode-css-peek
ritwickdey.LiveServer
Shan.code-settings-sync
shardulm94.trailing-spaces
shd101wyy.markdown-preview-enhanced
sldobri.bunker
Tyriar.lorem-ipsum
vincaslt.highlight-matching-tag
vscodevim.vim
WallabyJs.quokka-vscode
wix.vscode-import-cost
xabikos.JavaScriptSnippets
Zignd.html-css-class-completion

> And @mjbvz is asking you if you disable all extensions by doing this in command palette: Extensions: Disable All Installed Extensions (also restart VS Code after doing this) is an issue still exists?

No after opening vscode with all extensions disabled mode editor works fine. I see no issue. I think this is the problem with prettier or some other extension which try to reformat code or recognise code. However when editor freeze My cpu usages become 100% . But what i can do during freeze is i can move cursor anywhere by using arrow keys but i can't add or remove any letter.

**Comment by svipas** [comment]
@itzmanish Try to disable extension one by one to see which one causes editor freeze and then you can submit an issue :)

**Comment by itzmanish** [comment]
> Try to disable extension one by one to see which one causes editor freeze and then you can submit an issue :)

Seriously.... 
I don't think this is a good idea.
Isn't there any other workaround?

**Comment by svipas** [comment]
@itzmanish I mean you can skip for use snippets, themes, etc. disable the ones which make the most sense and I believe you will find the issue very fast :)

Also in VS Code, you can open `Developer: Show Running Extensions` and you can start a profile and then save the output and open it with Chrome :)

**Comment by itzmanish** [comment]
@svipas i think i found which extension causing the problem.
The extension is Auto rename Tag which becomes non responsive and due to this editor freezes.

> Also in VS Code, you can open Developer: Show Running Extensions and you can start a profile and then save the output and open it with Chrome :)

This worked. Thanks.
