### ISSUE TITLE
images links

### ISSUE THREAD

**Issue by id027102** [microsoft/vscode#77637]
Issue Type: <b>Bug</b>

images links only working if images directory is under current directory
samples:
directory tree
```
root--markdown
               --images(directory)
                        -- image.jpg
               -- test.md 
      -- tocheck
               -- images(directory)
                        -- image.jpg
```
In file test.md :
```
    ![image](images/image.jpg)    : work
    ![image](./images/image.jpg)  : work
    ![image](../markdown/images/image.jpg) : work
    ![image](../tocheck/images/image.jpg)  : does NOT WORK
```

Displayinfg file in firefox or epsilon on android gives NO problem, only here.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.1.18-towo.1-siduction-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-9700 RADEON R7, 10 COMPUTE CORES 4C+6G (4 x 3353)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.32GB (3.94GB free)|
|Process Argv|--unity-launch -r|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.6
vscode-markdownlint|Dav|0.28.0
code-runner|for|0.9.11
open-html-in-browser|pea|1.2.0
pdf|tom|0.5.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.4.0

</details>

**Comment by mjbvz** [comment]
For security reasons, we only allow the markdown preview to load resource from under the current workspace. Closing this as by-design
