### ISSUE TITLE
[bug] insertFinalNewline not work

### ISSUE THREAD

**Issue by pando85** [microsoft/vscode#77633]
- VSCode Version:
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64

- OS Version: Linux 4.18.20-1

Steps to Reproduce:

1. Set setting files.insertFinalNewline to True
2. Create new file, add one char and save

Does this issue occur when all extensions are disabled?: Yes

Additional info: If combined with `editor.renderFinalNewline: True` it appears to work correctly.
I tested it with `wc -l <file>`

**Comment by alexandrudima** [comment]
Well, I'm really confused at this point... and I'm not sure what to do.

@jonolo6 in #71957 expects the complete opposite of this, i.e. that an empty file saved to disk will remain an empty file, while here we want that an empty file saved to disk is saved as `\n`....

**Comment by pando85** [comment]
@alexandrudima  you are right. I think  #71957 is right; when file is empty it is better no add a new line.
I mistake with the example. I want to mean that new line is not added but I hit a special case.

I will edit `Steps to Reproduce` section because this bug is affecting all cases and empty file is the unique case it is correct.

**Comment by alexandrudima** [comment]
:+1: Thanks! Then let's track in #71957
