### ISSUE TITLE
When moving folders in javascript -  imports messed up!

### ISSUE THREAD

**Issue by lishine** [microsoft/vscode#77635]
Hi,

I am desperate about this, how do people even work like this, with this happening.
The auto-refactor of imports worked for some time since you added this feature, but It started to make these problems some time ago and I see that it is not fixed in the releases so I create this issue.

Have not found similar issue

Insiders have the same issue

VS Code version: Code - Insiders 1.37.0-insider (fd5985489982fe14381dd56e6f0b29c53d5f991b, 2019-07-18T14:11:10.247Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

Steps to Reproduce:

1. When I move any folder to anywhere, all absolute imports (even from node_modules) get added the path from the base till this folder. So I need to go and ctrl-z every file.
What actually should happen is that absolute imports should not change.
2. I have all my source in ./src. 
And jsconfig.json is in ./
```
{
	"compilerOptions": {
		"baseUrl": "./src",
		"target": "ES6"
	},
	"exclude": [
		"**/node_modules/**",
		"**/dist/**",
		"**/db/**",
		"**/.history/**",
		"**/.git/**",
		"**/not_used/**",
	]
}
```
Beneath is the folder root

Here are screenshots before and after
![image](https://user-images.githubusercontent.com/6741645/61529113-3d47af80-aa29-11e9-885a-8711c173d28e.png)
![image](https://user-images.githubusercontent.com/6741645/61529125-46d11780-aa29-11e9-81c4-4c57e98c49fb.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes, all extensions are disabled

**Comment by mjbvz** [comment]
Can you please share a small example project that demonstrates this issue

**Comment by lishine** [comment]
Thanks for taking care!
Demo repo for this issue:
https://github.com/lishine/demonstrate-vscode-issue-77635
For example, try to move  folder 'common' into folder '1'.
The problem is still reproduced in Insiders without extensions.

**Comment by lishine** [comment]
Same problem when renaming folder

**Comment by lishine** [comment]
@mjbvz 
I provided the info.
Please do something.
The auto refactor of imports is still non functional...
Is there anybody there using javascript :) ? Please support it...

**Comment by mjbvz** [comment]
It looks like the example project is not complete so it is difficult to understand what the expected behavior is supposed to be. For example `'common/utils/utils'` does not exist.

Try adding `"checkJs": true` to your `jsconfig` to make sure the imports are being resolved properly in the first place

**Comment by lishine** [comment]
Adding this to jsconfig.json solves the problem.
I appreciate your help! :)
```
"moduleResolution": "node",
```
BTW, checkJs helped to see the imports resolve problem, but otherwise it shows many typescript issues, so it cannot be enabled all time for js dev, pity.
