### ISSUE TITLE
Sometimes when I use CTRL+S to save file, the file returns  to newly-built status

### ISSUE THREAD

**Issue by fortwind** [microsoft/vscode#77632]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by fortwind** [comment]
- Version: 1.36.1 (user setup)
- Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
- Date: 2019-07-08T22:59:35.033Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.18362

It happens randomly, and, I donnot find out how to reproduce it succesfully😥. But others appear to have no such problem, there may be some problem with my computer.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by fortwind** [comment]
Sorry, it still can't be reproduced as I want.  So I guess I should close this issue. 
If there is any progress, I'll be back.
