### ISSUE TITLE
Search in File dialog cannot handle large strings

### ISSUE THREAD

**Issue by reactivize** [Microsoft/vscode#7763]
- VSCode Version: 1.3.0-insider
- OS Version: win10

Steps to Reproduce:

I accidently pasted in a big block of text into the search box,
and whole IDE froze up.
I had to kill the process and restart it.

In this case, the text I had pasted in was the 600 line settings.json file.
Should be easily reproducable.

possible solution....
Maybe put in a max-character limit on the search input box
especially since it's a single line text field.

**Comment by sandy081** [comment]
@reactivize I am not seeing this freeze even if I pasted more than 600 lines of text in Search box. Can you please let me know if it is still happening for you? 

Thanks

**Comment by sandy081** [comment]
Closing this as the requested information is not provided. Please re-open it with necessary info. Thanks.
