### ISSUE TITLE
Allow to always open file in current tab

### ISSUE THREAD

**Issue by jimbo5644535** [microsoft/vscode#77639]
I'm personally not a fan of the whole preview mode thing. 
I want my file code editor to be as stupid and predictable as possible. I turned preview mode off, now every time I open a new file through the vscode explorer it opens a new tab.

I searched through all Workbench>Editor Management Settings and there are a lot of options around where to open the new tab (first, last, after, before etc), but it doesn't seem possible to always open the file in the current tab.

I'd prefer to always open it in the current tab, if I want a new tab I'll create one and open the file afterwards. That's how I did it in vim and that's how I'd like to keep doing it :)

**Comment by bpasero** [comment]
@jimbo5644535 have you considered to just disable tabs altogether?

**Comment by jimbo5644535** [comment]
well, it's not the behaviour I'm looking for. I just don't want vscode to create new tabs for me.

**Comment by bpasero** [comment]
@jimbo5644535 so how exactly would that work? isn't that what the preview feature does for you already?

**Comment by jimbo5644535** [comment]
Preview modes opens the file in the current tab if the file has not been edited or saved yet or opened with double click.

I'd like vscode to always open the file in the current tab, even if it has been edited/saved and if I wanted a new tab I would manually open one and open the file after.

**Comment by bpasero** [comment]
@jimbo5644535 but if the file is edited and not saved, we cannot just open another file in there, can we?

**Comment by jimbo5644535** [comment]
we can, we just needed a dialogue asking if the changes should be saved or dismissed.
