### ISSUE TITLE
Side bar and SCM icons missing when using WSL remote

### ISSUE THREAD

**Issue by matt-FFFFFF** [microsoft/vscode#77649]
Issue Type: <b>Bug</b>

When using WSL remote and opening a remote folder, some sidebar icons are missing. Also, the + icon to add changed files to a staged commit is also missing.

VS Code version: Code - Insiders 1.37.0-insider (628bdedf671d3230fc76982fae845875a6f6c0da, 2019-07-19T10:33:04.702Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (6.99GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.39.0
vscode-remote-extensionpack|ms-|0.15.0
vscode-icons|vsc|8.8.0
azds|azu|1.0.120190708
bracket-pair-colorizer-2|Coe|0.0.28
terraform|mau|1.3.12
azure-pipelines|ms-|1.152.0
vscode-azurefunctions|ms-|0.17.1
vscode-azureterraform|ms-|0.2.4
vscode-logicapps|ms-|0.2.6
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
cpptools|ms-|0.24.0
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
team|ms-|1.149.2

(1 theme extensions excluded)

</details>

**Comment by matt-FFFFFF** [comment]
See screengrab:

![image](https://user-images.githubusercontent.com/16320656/61545352-33c94200-aa3f-11e9-950a-97b4e81dc256.png)

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode-remote-release/issues/966
