### ISSUE TITLE
Allow disabling of closing bracket removal when using Auto Closing Brackets

### ISSUE THREAD

**Issue by kotauskas** [microsoft/vscode#77646]
When the `Editor: Auto Closing Brackets` setting is enabled, if you type the a closing parenthesis/bracket/quote and the caret is behind one (like this: `|}`, where `|` is the caret), it's automatically removed and the cared is advanced one symbol forward (`}|`). It'd be much easier to type nested function calls, like in `SDL_LogCritical(SDL_LOG_CATEGORY_APPLICATION, "Error occured: %s", SDL_GetError())`, if the auto-removal could be disabled in Settings, because `SDL_GetError()` is usually typed out after the `SDL_LogCritical()` "body" is typed out.

**Comment by alexandrudima** [comment]
Duplicate of #37315
