### ISSUE TITLE
C++ Syntax highlighting broken

### ISSUE THREAD

**Issue by HellerCommaA** [microsoft/vscode#77641]
Issue Type: <b>Bug</b>

While working in (larger? not sure if it matters) C++ files, syntax highlighting freaks out from time to time and begins to highlight my \t characters as if they are printable characters. As well as taking a lot of time to recognize and properly highlight normal function calls and statements. Never had any issues with these sized .cpp files until this most recent update.   My coworkers' install of vscode is also doing the same thing, so I'm pretty confident it isn't extension related. We also both run different themes, it's not theme related.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 3.13.0-170-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1607 0 @ 3.00GHz (4 x 1200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|31.38GB (9.64GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
cpptools|ms-|0.24.0
printcode|nob|3.0.0
gitblame|wad|2.8.1

</details>

**Comment by matter123** [comment]
If you have the C/C++ extension it could be their enhancedColorization option introduced with version 0.24. See https://github.com/microsoft/vscode-cpptools/issues/3933 & https://github.com/microsoft/vscode-cpptools/issues/3932.

**Comment by HellerCommaA** [comment]
That was it. Closing this.
