### ISSUE TITLE
 Debugger stopped working after upgrading vscode to Version 1.2.1

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#7764]
- VSCode Version: 1.2.1
- OS Version: Fedora 23

Steps to Reproduce:

1. Write PHP code and press F5 to run PHP debugger extension
2. Error:  Debug adapter process has terminated unexpectedly
![vscode_error](https://cloud.githubusercontent.com/assets/9781577/16115844/d7c067a2-33c9-11e6-8a26-70b81704274f.png)

**Comment by sandy081** [comment]
@forethoughtde May I know are you using any extension for PHP debugging?

**Comment by forethoughtde** [comment]
I am using PHP Debug 1.9.1

**Comment by sandy081** [comment]
Thanks @forethoughtde 

I would suspect this could be a bug in the extension. Please report the same on the extension.
