### ISSUE TITLE
Restore access to folder on "removable" partition/disk

### ISSUE THREAD

**Issue by Mlocik97-issues** [microsoft/vscode#77640]
Issue Type: <b>Bug</b>

https://youtu.be/y-aghs9fN8s

Is there way, how can VS Code get access to open "DATA" partition automatically?

If not, vs code sohuld remember last opened folder, and when is avaiable, suggest to open it.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.61GB (2.81GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please post repo steps as text

**Comment by Mlocik97-issues** [comment]
HW: Computer with 2 or more internal disks.
SW: Ubuntu, VS Code

Example: Have Ubuntu and VS Code on Disk 1, by default other disks with NTFS partitions are unmounted. (Ofc, I can change it)
Partition on disk 2 will be mounted after first access. So, if I open VS Code before partition on disk 2 is mounted. VS Code will close folder in VS Code explorer. (standarly, VS Code remember which folder was last opened), when disk 2 is again mounted, I must again open folder in VS Code.

Additional info: I have setting "HotExit" off.
