### ISSUE TITLE
REQUEST - Alter "No source control providers registered" verbiage.

### ISSUE THREAD

**Issue by MalcolmAnderson** [microsoft/vscode#77642]
High Level issue: The current verbiage 
"No source control providers registered" 
can be read by the user (especially a new user) as:
"Git will not work with your current VSCode configuration until you register it, because no source control providers are currently registered in this copy of VSCode."

From 
@tornPiece
Suggestion: Please add a hint in the ui that content in the source control view is only available if your already open a folder that is under source control.
https://github.com/microsoft/vscode/issues/61522

Version: 1.37.0-insider
OS: Ubuntu, on Virtual Box, on Win10

When I first open VSCode and click the source control button I get a message implying that git is not installed.  
![image](https://user-images.githubusercontent.com/1200043/61537786-d3a9b000-a9ec-11e9-9241-e63961ce1238.png)
Please change the verbiage from "No source control providers registered" to something like:
"Current location not under version control"
'Switch to a directory view that has already had "git init" run on it'
or any other clue that Git is already installed, just not useful in the current context.

**Comment by joaomoreno** [comment]
#61491
