### ISSUE TITLE
Ctrl+Shift+T for new info for VSCode

### ISSUE THREAD

**Issue by MunirMuratovic** [microsoft/vscode#77647]
When I open after some time Code, there is some welcome tab with new data about VS Code. It after closing can't be opened, i.e. Ctrl+Shift+T does not work on those.

Make that possible to open in Reopen Closed Editor option.

**Comment by MunirMuratovic** [comment]
Here it is: https://www.youtube.com/watch?v=-Hl4TBu0vY0

After closing this type of tab, it won't open with Ctrl+Shift+T, or via File menu.

**Comment by mjbvz** [comment]
Use the Help -> Welcome command to reopen the welcome screen.

The welcome page is not an editor so the `reopen previous editor` command is not expected to work
