### ISSUE TITLE
Cannot modify 'Recent' list

### ISSUE THREAD

**Issue by wzlwit** [microsoft/vscode#77654]
I pin Vscode to the taskbar. When I try to remove a file name from 'Recent' list, it cannot be done. The 'Recent' list in unchangeable anymore.  

Briefly, the 'Recent' list has not been updated for a long time. It does not represent 'Recently Opened File'

Very annoying. Could somebody help me with that?

Thank you very much

**Comment by bpasero** [comment]
You can clear the list to start fresh: File > Open Recent > Clear Recently Opened
