### ISSUE TITLE
Deleting unsaved page doesn't close the editing window

### ISSUE THREAD

**Issue by nh1402** [Microsoft/vscode#7765]
- VSCode Version: 1.2.1
- OS Version: Linux Mint 17.3 Rosa

Steps to Reproduce:

1. Modify a file inside Visual Studio Code (don't save it)
2. Delete the file

As the title says. If you modify a file and then immediately delete it from the side bar (without saving it first), then the editing window is still there with the tag thing showing that it's been modified and unsaved, when it no longer exists.

**Comment by bpasero** [comment]
We do not delete user content to not have data loss.
