### ISSUE TITLE
Freezing on "big" search

### ISSUE THREAD

**Issue by simplyandyg** [microsoft/vscode#77650]
Issue Type: <b>Bug</b>

When searching for commonly used terms, VS Code freezes. The system then gives me the prompt for "close, restart, or wait for VS Code". Sometimes if I click "wait" then it will come back. Other times I end up having to force close it if I click "wait". This only started happening within the last couple months.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.4
path-intellisense|chr|1.4.2
vscode-new-file|dku|4.0.2
vscode-great-icons|emm|2.1.47
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.0
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.0.12
docthis|joe|0.7.1
rainbow-csv|mec|1.1.1
mssql|ms-|1.6.0
atom-keybindings|ms-|3.0.6
node-debug2|ms-|1.33.0
vsliveshare|ms-|1.0.540
vscode-react-native|msj|0.10.2
color-highlight|nau|2.3.0
vetur|oct|0.21.1
code-settings-sync|Sha|3.4.0
html-preview-vscode|tht|0.2.5
sort-lines|Tyr|1.8.0
vscode-todo-highlight|way|1.0.4

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It would be very helpful if you could get a profile of the renderer process with these steps:

- Help > Toggle developer tools
- Performance tab
- Click "Record"
- Reproduce the issue
- Click "Stop"
- "Save Profile"
- Attach it to this issue

**Comment by simplyandyg** [comment]
Profile-20190725T160805.json
<https://drive.google.com/file/d/1OS58-XVLyyBBrpZUhUfoNZ9NIhkNcU-V/view?usp=drive_web>
The attached profile contains a search where the UI did hang up a quite a
bit, but I did not get the system message asking if I would like to wait or
close the application as I have before. I have tried it a couple of times
today without success in reproducing the issue, unfortunately.


Andy

**Comment by roblourens** [comment]
Thanks, that is helpful.

Did your search contain matches in really long lines, or were the matches extremely long? Does it happen for the exact same search again?

**Comment by simplyandyg** [comment]
I went through all the results for "orderBy(". In those results, some lines were as short as 20-30 characters including tabs, but some were as long as 220 characters.

The matches were generally short like "down(" or "orderBy(". Usually, just function names.

If I do the same exact search again, right after the editor finally unfreezes, it locks up again.

Also, when I scrolled to the bottom of the list of the results, VS Code hung up there as well.

**Comment by roblourens** [comment]
Thanks. The profile shows this function taking an extremely long time: https://github.com/microsoft/vscode/blob/285b680dc1dea713d57edf78dcc0872d4b79191e/src/vs/base/common/strings.ts#L595

Is there any way you can share the repo?

Was this just a text search for `orderBy(` or was it a regex search?

**Comment by simplyandyg** [comment]
I can't share the repo, unfortunately. This was just a text search.

**Comment by simplyandyg** [comment]
I ended up noticing the freezing seemed to happen a lot when results for *.js.map were popping up. So, in my settings, I excluded those files from search. Haven't had a problem since.

**Comment by roblourens** [comment]
Yes there is actually a regression in finding matches with long lines, thanks.

**Comment by simplyandyg** [comment]
Yeah, sorry about that. I know you asked that before. I didn't put two and two together. Thanks.

**Comment by roblourens** [comment]
No problem, I didn't see it before, but I saw it when specifically searching sourcemaps, so thanks for leading me to the issue!

**Comment by roblourens** [comment]
Verification steps

- Search 'sourceroot' in the vscode codebase, with excludes turned off
- It should not hang while loading results, or while scrolling through the list
