### ISSUE TITLE
Pick up all WSL distributions in default shell selector

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#77652]
Currently we only check for wsl.exe, it would be nice if it exposed specific distros. This would also need to modify args which would be a change though.

**Comment by Tyriar** [comment]
Additionally git bash should probably use --login as in #79572

**Comment by Tyriar** [comment]
We can consider this for March as part of https://github.com/microsoft/vscode/issues/45444

**Comment by TylerLeonhardt** [comment]
marking this as verified but I saw https://github.com/microsoft/vscode/issues/119639 while verifying this issue
