### ISSUE TITLE
Integrated terminal not working

### ISSUE THREAD

**Issue by uncikmarek** [microsoft/vscode#77659]
Issue Type: <b>Bug</b>

Hi, so in past few days, I was changing my keybinding, and also unninstaling some of extensions, and out of nowhere this issue came that that is not allowing me to open a integrated terminal, if I press open integrated termimal, its panel comes up and also external (bash) terminal is oppend automatically, in the integrated the coursor is just frozen on first line without any error,  but I cant write there niether, and the external is working, I tried switching it in settings, but it still opens external

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.4
better-phpunit|cal|1.5.0
vsc-material-theme|Equ|29.2.0
php-debug|fel|1.13.0
php-cs-fixer|jun|0.1.120
snippet-creator|nik|0.0.5
laravel-blade|one|1.20.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.8.1
laravel-artisan|rya|0.0.25
vscode-fileutils|sle|2.14.5
vscode-icons|vsc|8.8.0

(2 theme extensions excluded)

</details>

**Comment by uncikmarek** [comment]
Anyone else having this issue or is it just my configuration problem or maybe som extension ?

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
