### ISSUE TITLE
"Initializing JS/TS Language Features" appears every time I open a JS file

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#77665]
Issue Type: <b>Bug</b>

On certain projects, whenever I open a JS or TS file, I get the message "Initializing JS/TS Language Features". Often this is accompanied by a CPU spike.

The attached tsserver.log file is from a session where I turned on "verbose" logging, made sure no Code Helper processes were running, and started vscode with `--disable-extensions`. I removed sensitive portions (it would be great if someone could undo #75748 and restore the ability to upload logs privately).

In this session, I opened a JS file, waited for the "initializing" message to disappear, then closed the file and opened another. I repeated this a few times. The "initializing" message reappeared three or four times.

[tsserver.log](https://github.com/microsoft/vscode/files/3412236/tsserver.log)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.5.2
vscode-intelephense-client|bme|1.1.4
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.5
vscode-npm-script|eg2|0.3.8
vscode-powertools|ego|0.45.0
php-debug|fel|1.13.0
vscode-pull-request-github|Git|0.9.1
vscode-favorites|how|1.4.0
svn-scm|joh|1.54.4
vscode-apache|mrm|1.2.0
python|ms-|2019.6.24221
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
debugger-for-chrome|msj|4.11.6
java|red|0.47.0
vscode-yaml|red|0.4.1
vscode-hexdump|sle|1.7.2
slack|soz|0.0.14
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.1
sync-rsync|vsc|0.35.0
jinja|who|0.0.8

</details>

**Comment by mjbvz** [comment]
Thanks! I pushed a potential fix based on one of the errors in your log. Please test using the next VS Code insiders build to see if this resolved the issue for you

**Comment by jacobweber** [comment]
Hi @mjbvz -- thanks for the update. However, I tried running today's Insiders build on the same project, with extensions disabled, and continued to see this behavior. I don't see any of the "Exception on executing command" messages, however.

It's time-consuming to clean up the log file for posting publicly -- is there anywhere I can email it?

```
Version: 1.37.0-insider
Commit: 81ed55af79f01e9e64c3438558d2c2233e382a5a
Date: 2019-07-22T07:13:09.762Z
```

**Comment by mjbvz** [comment]
Thanks for checking. You can email the logs to me (or a link to the logs if they are too large) at: matb at microsoft

**Comment by jacobweber** [comment]
Wait, please don't close me! I sent the logs by email.
