### ISSUE TITLE
Toggle integrated Terminal shotcut does not work 

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#7766]
- VSCode Version: 1.2.1
- OS Version: Fedora 23

Steps to Reproduce:

1. Open the VSCode
2. Press Ctrl + ` and observe the bug

It should open the integrated terminal but it does not open it.

**Comment by Tyriar** [comment]
@forethoughtde I cannot reproduce. What is your `$SHELL` set to? Also do you have anything set in your settings.json?

**Comment by gerane** [comment]
Any other applications possibly have conflicting keybinding?

**Comment by forethoughtde** [comment]
This is my setting.json file. My $SHELL set to /bin/bash

```
{
    "php.validate.executablePath": "/usr/bin/php",
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true,
        "Test/": true,
        ".idea/":true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/.git": true
    }
    
}
```

**Comment by forethoughtde** [comment]
After I changed my keybinding shortcut  to shift + t it does work but not ctrl + ` shortcut

**Comment by Tyriar** [comment]
@forethoughtde are there any errors or warnings in your the console of developer tools? (Help > Toggle Developer Tools).

**Comment by forethoughtde** [comment]
I have warnings. 
Overwriting extension <<.handlebars>> to now point to mime <<text/x-handlebars>>
workerClient.ts:366Overwriting extension <<.hbs>> to now point to mime <<text/x-handlebars>>

**Comment by Tyriar** [comment]
@forethoughtde could there be an operating system override that captures <kbd>ctrl</kbd>+<kbd>\`</kbd> before it reaches vscode?

**Comment by forethoughtde** [comment]
I do not think so

**Comment by Tyriar** [comment]
I'm out of ideas, you might want to just use a different keybinding since you can rebind it without issues. If I was to guess I think something outside of VSCode is swallowing the key event before it reaches the app. Going to close this off for now, please comment if you find out more.

**Comment by askhat** [comment]
Same issue on OS X 10.12.5. My `settings.json`:
```json
{
  "terminal.external.osxExec": "iTerm.app",
  "terminal.integrated.shell.osx": "/usr/local/bin/fish"
}
```
