### ISSUE TITLE
Containers stopped working

### ISSUE THREAD

**Issue by Karrq** [microsoft/vscode#77666]
Issue Type: <b>Bug</b>

1) Prepare dev container from Dockerfile
2) Open folder in said container

I switched to insiders yesterday to use alpine linux and it was working fine.
Today I updated and I can't launch anything.

VS Code version: Code - Insiders 1.37.0-insider (628bdedf671d3230fc76982fae845875a6f6c0da, 2019-07-19T10:33:04.702Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (15.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|10.4.4
better-toml|bun|0.3.2
jsonviewer|cci|1.2.2
calva-fmt|cos|0.0.38
clojure4vscode|cos|1.3.70
paredit-revived|cos|0.1.22
xml|Dot|2.5.0
gitlens|eam|9.8.5
EditorConfig|Edi|0.13.0
vscode-powertools|ego|0.45.0
vscode-projects-plus|fab|1.22.0
vscode-projects-plus-todo-plus|fab|1.6.10
vscode-todo-plus|fab|4.13.0
short-commands|lag|0.2.0
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
remote-containers|ms-|0.66.0
cpptools|ms-|0.24.0
vscode-typescript-tslint-plugin|ms-|1.2.2
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.8.1
rust|rus|0.6.1
text-marker|ryu|1.11.0
crates|ser|0.4.3
code-settings-sync|Sha|3.4.0
vscode-hexdump|sle|1.7.2
tabnine-vscode|Tab|1.1.0
vscode-jumpy|wma|0.3.1
vscode-hy|xuq|0.0.4
vscode-surround|yat|1.0.2
markdown-all-in-one|yzh|2.4.0

(1 theme extensions excluded)

</details>

**Comment by Karrq** [comment]
Should be labeled insiders...

**Comment by floodkoff** [comment]
![image](https://user-images.githubusercontent.com/1153804/63004596-0e332b00-be7b-11e9-8b07-bfbf351f0337.png)
Have just noticed the same happens for me. Is it the same issue?

**Comment by chrmarti** [comment]
@floodkoff Make sure you are on the latest version of the extension.

@Karrq How far does it get? Do you get a new window with a Dev Container terminal? What does that terminal show?

**Comment by floodkoff** [comment]
@chrmarti thanks, I updated Visual Studio Code & all plugins but didn't restart it.

**Comment by chrmarti** [comment]
This should have been fixed with the latest VS Code Insiders & Remote-Containers versions at the time. Let me know if this is still a problem. Closing.
