### ISSUE TITLE
Comment should use double forward slash for multiline React Props

### ISSUE THREAD

**Issue by onelz** [microsoft/vscode#77661]
Issue Type: <b>Bug</b>

using the shortcut cmd+/ to comment Multiline React Props:
```
<div
   className="bla"
   ...
```
would give me:
```
<div
   /* className="bla" */
   ...
```
instead, it should be 
```
<div
   // className="bla"
   ...
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

This works as expected for me in a simple js file:

<img width="418" alt="Screen Shot 2019-07-19 at 5 27 33 PM" src="https://user-images.githubusercontent.com/12821956/61571740-8c520c80-aa4a-11e9-989c-0e3a9ba3f899.png">

**Comment by onelz** [comment]
Sorry, you're right apparently my language was set to Javascript React (Babel) and after making several changes the babel was gone and everything works. Thanks!
