### ISSUE TITLE
Integrated Terminal slows after usage

### ISSUE THREAD

**Issue by Tylerflick** [microsoft/vscode#77660]
Issue Type: <b>Bug</b>

I am noticing the integrated terminal's input lag increasing with the current stable release. After a cold start it's fine. The lag increase happens over of a couple cycles of opening and closing it. This is happening on all of my Mac systems.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.4
vscode-apollo|apo|1.7.4
better-toml|bun|0.3.2
vscode-eslint|dba|1.9.0
vsc-material-theme|Equ|29.2.0
VS-code-vagrantfile|mar|0.0.7
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
csharp|ms-|1.21.0
Go|ms-|0.11.4
vetur|oct|0.21.1
vscode-ios-common-files|Ort|1.0.5
material-icon-theme|PKi|3.8.1
vscode-yaml|red|0.4.1
rust|rus|0.6.1
git-merger|sha|0.4.1
vscode-lldb|vad|1.2.3
code-navigation|vik|0.2.0
vscode-icons|vsc|8.8.0
vscode-proto3|zxh|0.3.0

(6 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
