### ISSUE TITLE
Typing in quick open has significant lag

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#77662]
Issue Type: <b>Bug</b>

When I type a file name into the quick open panel I frequently get severe lag and can watch characters appear one at a time. I have a rather large workspace composed of many folders and I assume the issue comes from the sheer number of files.

It looks like the text box doesn't update until the file query returns and updates the results list. For better user experience I think the text box should update immediately, even when the query is still pending. Some sort of 'spinner' may be necessary, but I don't consider it critical personally.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
This is likely https://github.com/microsoft/vscode/issues/78401. Maybe you can try the 1.38 insiders when we get it out later today or Monday.

**Comment by roblourens** [comment]
That update is out now.
