### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by cyberh0me** [microsoft/vscode#77678]
occurs on latest VS code and also latest VS code insiders
need to start code from command line like "code-insiders --force-color-profile srgb" to have a normal color window

![code](https://user-images.githubusercontent.com/39925052/61569112-208d9500-aa86-11e9-8d23-3376f90234b9.jpg)

please also see #68069

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by cyberh0me** [comment]
@bpasero cant reproduce it with the exploration build

![2019-08-05 171602](https://user-images.githubusercontent.com/39925052/62475134-ba528300-b7a4-11e9-90be-b00fae847018.jpg)

**Comment by cyberh0me** [comment]
worked with latest insider releases up to 1.39.0, with this version it appeared again !

**Comment by bpasero** [comment]
We briefly went back to Electron 4 since we are about to cut a stable release but will go back to Electron 6 soon.
