### ISSUE TITLE
Cannot search for extensions

### ISSUE THREAD

**Issue by pkail** [microsoft/vscode#77679]
Issue Type: <b>Bug</b>

I type 'Postgresql' in the search bar for extensions.  A blue line moves endlessly across the top of that section of the page, suggesting that something is loading.  But a list of extensions never loads.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:25:47.870Z)
OS version: Linux ia32 4.15.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 CPU          6600  @ 2.40GHz (2 x 1827)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.94GB (0.92GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by pkail** [comment]
I haven't tried it on the insider's build.  It works okay so far on my 64-bit machine, so it's possible it may just be an issue with the 32-bit version.   I might just give up on that, because there were also issues with extensions not loading properly.
I haven't tested it with the extensions disabled.

**Comment by sandy081** [comment]
@pkail Can you please check logs and let us know whats happening. You can find logs using `F1 > View: Open View > Log (Shared)` and `F1 > Toggle Developer Tools`
