### ISSUE TITLE
History does not saved

### ISSUE THREAD

**Issue by Skriptach** [microsoft/vscode#77674]
There are several bug reports for same issue

https://github.com/Microsoft/vscode/issues/37273
https://github.com/Microsoft/vscode/issues/43557
https://github.com/microsoft/vscode/issues/59230

All closed but still not fixed!

**Comment by mjbvz** [comment]
Is this for the terminal history?

/needsMoreInfo

**Comment by Skriptach** [comment]
@mjbvz  yes

**Comment by Tyriar** [comment]
What's your version of Windows?

**Comment by Skriptach** [comment]
Win 7 SP1 x64

**Comment by Tyriar** [comment]
Then this is https://github.com/microsoft/vscode/issues/45693 just like https://github.com/microsoft/vscode/issues/43557, Windows 10 1903+ uses the new terminal backend build by MS.

**Comment by Skriptach** [comment]
I have set "terminal.integrated.windowsEnableConpty": false. But that not fixed the issue
