### ISSUE TITLE
Default Keyboard Shortcuts file has dup key conflict

### ISSUE THREAD

**Issue by reactivize** [Microsoft/vscode#7767]
- VSCode Version: 1.3.0-insiders
- OS Version: win10

Steps to Reproduce:

The dup keys are....
{ "key": "ctrl+shift+t",          "command": "workbench.action.reopenClosedEditor" },
{ "key": "ctrl+shift+t",          "command": "launcher.terminal" },

Since launcher.terminal occurs last, the ctrl-shift-t shortcut opens the exernal terminal.
This shortcut should reopen the last closed editor window.

Proposed Solution....
remap the launcher.terminal key to default to another, nonconflicting shortcut sequence

**Comment by Tyriar** [comment]
I don't see a `launcher.terminal` in the latest insiders, are you sure this isn't a custom keybinding?

**Comment by reactivize** [comment]
Hey Tyriar, 
That's interesting
I have the latest builds, I get them every night.
I didn't modify the Default Keyboard Shortcuts file, plus it's readonly.


[Link to my screenshot image](https://s31.postimg.org/f1p5xa8nf/launcher_terminal.jpg)

**Comment by Tyriar** [comment]
@reactivize It appears to be the https://github.com/ilich/vscode-launcher extension causing the conflict.

**Comment by reactivize** [comment]
Good catch Tyriar,
I guess the take-home lesson here is that an installed extension may cause unintended behavioral changes by overriding existing IDE shortcuts.

**Comment by Tyriar** [comment]
@reactivize in the future you can run `code --disable-extensions` to help prevent this sort of confusion :)
