### ISSUE TITLE
VS Code doesn't allow me to type anything in the integrated terminal

### ISSUE THREAD

**Issue by chilupa** [microsoft/vscode#77673]
Issue Type: <b>Bug</b>

VS Code isn't allowing me to type anything in the integrated terminal after stopping the gatsby develop server. 

Steps to replicate the issue
- Run 'gatsby develop' in the terminal 
- Stop it by doing 'Ctrl + C' 
- Try to enter something or press up arrow to see if the previous commands would display. The terminal just hangs and the cursor won't blink. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 5|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
angular1-code-snippets|ale|0.0.3
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
Angular2|joh|8.1.1
sublime-babel-vscode|jos|0.2.10
tag-rename|kri|0.2.1
code-beautifier|mic|2.2.1
mssql|ms-|1.6.0
python|ms-|2019.6.24221
debugger-for-chrome|msj|4.11.6
java|red|0.47.0
sass-indented|rob|1.5.1
vscode-sass-format|sas|1.1.6
highlight-matching-tag|vin|0.9.2
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.1
ReactSnippets|xab|2.3.0

</details>

**Comment by chilupa** [comment]
This issue seems to be resolved with the latest **Version: 1.37.0** of the update that I did today.

**Comment by chilupa** [comment]
It looks like the issue is not resolved after the new update. It happens to appear again.

**Comment by Tyriar** [comment]
Can you provide a screenshot for VS Code and one when you do the same in the built-in macOS terminal?
