### ISSUE TITLE
Remove Ctrl+K + F shortcut

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#77680]
- VSCode Version: 1.36.1
- OS Version: arch linux

By default `"key": "ctrl+k f"` is bound to `workbench.action.closeFolder`. But there is a default shortcut `ctrl+k ctrl+f` which formats current line or selection. It's easy to hit wrong one and accidentally close workspace. (Usability)

**Comment by alexandrudima** [comment]
@Yanpas Just remove it by yourself. Open the keybindings editor via ctrl+k ctrl+s, find the keybinding and right click > remove keybinding
