### ISSUE TITLE
Ability to name workspace files '.code-workspace'

### ISSUE THREAD

**Issue by nayeemrmn** [microsoft/vscode#77694]
- VSCode Version: 1.36.1
- OS Version: Windows 10 1903

Steps to Reproduce:
1. Save a workspace as '.code-workspace'.
2. Try to open this workspace through either 'File > Open Workspace...' or `code path/to/.code-workspace` on a CLI.

No workspace will open, '.code-workspace' will be opened as a file in both cases.

It doesn't seem like VSCode is at all prepared for workspace files to be named like this. For example if you bring up the recents menu with Ctrl+R, the workspace name on the left is set to the part of the workspace file name before the extension. This menu would look strange if it included workspaces named as above. Some redesign would be needed if this is implemented.

**Comment by nayeem-rahman** [comment]
The reason this is needed is because I put my workspace files in 'project-name/.vscode' and I imagine many other do the same. Any name I can give to this file is therefore redundant. To illustrate this, I currently call them all 'workspace.code-workspace'.

**Comment by gjsjohnmurray** [comment]
I'm experimenting with having the workspace file named `..code-workspace` (note the double dot) and put in the `.vscode` folder. My file has the following initial content:
```
{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"window.title": "${dirty}${activeEditorShort}${separator}${folderName}${separator}${appName}"
	}
}
```

**Comment by nayeemrmn** [comment]
@gjsjohnmurray Your solution has been working great for me, thanks! It's not ideal but I can live with it.

Since this isn't going to get 20 upvotes, I won't give the bot the satisfaction 😀
