### ISSUE TITLE
default cwd of terminal

### ISSUE THREAD

**Issue by alexzshl** [microsoft/vscode#77692]
Issue Type: <b>Suggest</b>

when I try to use the relative path in my script(python), and the script is in a subfolder, it will not work. Finally, I find that's because the cwd is incorrect. VSCode using the workspacefolder as default cwd

Finally, I have to add a configuration item for launch.json manually
![](https://i.loli.net/2019/07/20/5d3314d095efa73261.png)

On this point, VSCode is very different from other editors, I think the configuration of cwd should become the default setting in launch.json

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.8.5
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|29.2.0
php-pack|fel|1.0.2
code-runner|for|0.9.11
theme-monokai-pro-vscode|mon|1.1.13
vscode-language-pack-zh-hant|MS-|1.36.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
Go|ms-|0.11.4
vsc-netease-music|non|0.0.20
material-icon-theme|PKi|3.8.1
view-in-browser|qin|0.0.5
vscode-yaml|red|0.4.1
vs-picgo|Spa|2.0.4
guides|spy|0.9.3
ayu|tea|0.18.0
highlight-matching-tag|vin|0.9.2
vscode-icons|vsc|8.8.0
livereload|zii|0.2.5

(12 theme extensions excluded)

</details>

**Comment by weinand** [comment]
VS Code doesn't know what "cwd" is.  "cwd" is contributed by individual debug extensions. Please file this issue against the debug extension you are using.
