### ISSUE TITLE
windows 1252  encoding error, can not display correct.

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#77699]
Issue Type: <b>Bug</b>

File can not display correct in vscode. **A file encoding with UTF-8, but VSCode guess it encoding with windows 1252.**  and can not display correct.

see below:

![10](https://user-images.githubusercontent.com/11532015/61582829-60c24580-ab62-11e9-87d1-e1b24f851639.gif)

this is a utf8 coding file:
![BaiduHi_2019-7-21_2-58-41](https://user-images.githubusercontent.com/11532015/61582917-86038380-ab63-11e9-87fd-50c509deb04e.png)

Notepad open the file:
![BaiduHi_2019-7-21_3-0-21](https://user-images.githubusercontent.com/11532015/61582932-bc410300-ab63-11e9-8a5c-ca1339590bce.png)

correct preview:
![BaiduHi_2019-7-21_2-55-11](https://user-images.githubusercontent.com/11532015/61582886-0ecdef80-ab63-11e9-887a-d287a4626109.png)

Setting :

![BaiduHi_2019-7-21_2-51-31](https://user-images.githubusercontent.com/11532015/61582846-76376f80-ab62-11e9-8084-10920fb5faa3.png)

this code cause the error.
```async function guessEncodingByBuffer(buffer: Buffer): Promise<string | null> {
	const jschardet = await import('jschardet');

	jschardet.Constants.MINIMUM_THRESHOLD = MINIMUM_THRESHOLD;

	const guessed = jschardet.detect(buffer);
	if (!guessed || !guessed.encoding) {
		return null;
	}

	const enc = guessed.encoding.toLowerCase();

	// Ignore encodings that cannot guess correctly
	// (http://chardet.readthedocs.io/en/latest/supported-encodings.html)
	if (0 <= IGNORE_ENCODINGS.indexOf(enc)) {
		return null;
	}

	return toIconvLiteEncoding(guessed.encoding);
}
```
**jschardet.detect(buffer);**   jschardet dependency
![BaiduHi_2019-7-22_21-56-38](https://user-images.githubusercontent.com/11532015/61638260-a2223480-accb-11e9-854c-72abacbb897f.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.36GB free)|
|Process Argv|C:\Users\liuyuqi\Desktop\AutoHotkey-Script|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.7.1

</details>

**Comment by byyxx128** [comment]
May duplicate #33720
But why is #33720 still not fixed...
