### ISSUE TITLE
one git project with two folder 

### ISSUE THREAD

**Issue by Jack126** [microsoft/vscode#77690]
- VSCode Version:1.36.1
- OS Version:mac 10.12.6

Steps to Reproduce:

1.one git project with two folder which with same files ( like folder test1 and folder test2 )
2.when you do something such git commit or push ,in folder test1 . The same name file in test2 will be commit or push too. But I just like to commit or push the file in folder test1 . so sadly

![image](https://user-images.githubusercontent.com/3423503/61578108-19b55f80-ab24-11e9-82a8-db845a34b938.png)
![image](https://user-images.githubusercontent.com/3423503/61578112-2cc82f80-ab24-11e9-85d2-18d0b5266fac.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jianboy** [comment]
This is  not a bug. you should add a file before you commit.

**Comment by Jack126** [comment]
> This is not a bug. you should add a file before you commit.

yes, I add the file 1.vue in the folder test1 and 1.vue in the folder test2 will be commit too

**Comment by joaomoreno** [comment]
They are different files. You need to add them separately.
