### ISSUE TITLE
Can't open web links from editor in Ubuntu Server 18

### ISSUE THREAD

**Issue by sfsccn** [microsoft/vscode#77698]
Clicking on web links in the editor does nothing in Ubuntu.

- VSCode Version: 1.36.1 and 1.37.0-insider
- OS Version: Ubuntu Server LTS 18.04.02 4.15.0-54-generic 64-bit (Windows version works as expected)

Steps to Reproduce:

1. Create new file myfile.txt
2. Insert "https://code.visualstudio.com/"
3. Hover over text to produce tooltip "Follow link (ctrl + click)"
4. Control-click the text (tried double clicking as well)
5. Expected: link opens in default web browser (/usr/bin/firefox)
6. Actual: nothing happens

Also, can’t open links in other places such as the extensions menu: for example, when viewing the “One Dark Pro” theme, links such as "Repository" don't open although they appear to be clickable.

Does this issue occur when all extensions are disabled?: Yes

Here's the output of `sudo update-alternatives --config x-www-browser`:

> There is only one alternative in link group x-www-browser (providing /usr/bin/x-www-browser): /usr/bin/firefox
> Nothing to configure.

**Comment by jrieken** [comment]
We delegate to electron for opening links

**Comment by deepak1556** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/77653
