### ISSUE TITLE
Tooltip on hover for "existing commands have this keybinding"

### ISSUE THREAD

**Issue by kostyabushuev** [microsoft/vscode#77696]
Hello
When you try override hotkey, you get tip, that the hotkey is existing for other commands, but you cannot see what are commands this.  You need to click on the tip and then your tab will be reopen with search result. I think that it is not comfortable

![Screenshot from 2019-05-19 08-34-57](https://user-images.githubusercontent.com/31274471/61580230-ec1ee500-ab28-11e9-91c2-7a6f82e21eae.png)

Solution:

1. Show existing commands on hover
2. Or open new tab with search result

**Comment by cnamal-msft** [comment]
Hi @sandy081, I'd like to tackle this bug. I investigated a bit both solutions suggested by kostyabushuev, and would appreciate your input:

1/ There can be a lot of information to be displayed on hover:
![DeepinScreenshot_select-area_20190728141105](https://user-images.githubusercontent.com/53378748/62006518-a625da80-b141-11e9-8461-de566bd60455.png)
I also need to test the accessibility of this text. Just looking at the DOM, the current text `{0} existing commands have this keybinding` doesn't seem (easily?) accessible to screen reader users. Maybe it works in Scan Mode, which I can't test right now on Linux. 
2/ Opening an existing tab doesn't seem to be possible in the same editor group, which makes sense :) Should I try opening in a different editor group?

An alternative could be to display the list directly in the widget, but that might be overwhelming.

**Comment by sandy081** [comment]
Opening in another editor group makes sense to me. You can use cmd/ctrl+click user gesture for this.

**Comment by cnamal-msft** [comment]
I'm not entirely sure what you meant by _"use ctrl+click user gesture"_ @sandy081. If you meant mimicking the behavior of the [go to definition](https://github.com/microsoft/vscode/blob/118e3517522060ec45ccbba606ec908cffd175a3/src/vs/editor/contrib/goToDefinition/goToDefinitionMouse.ts#L294) when doing `ctrl+alt+click` on a symbol, that's what I tried to do in my PR #78114. Let me know if you meant something different :)
