### ISSUE TITLE
VSCode unable to create file using button

### ISSUE THREAD

**Issue by jwilliams-dae** [microsoft/vscode#77693]
Issue Type: <b>Bug</b>

I have Hyper-V from Windows10Pro (AMD x64) hosting Umbuntu 18.04.02 LTS

Installed VSCode and opened my working folder.  When I select the button to add file or folder it opens either in the project and I can add a file name/type or folder name.  When I hit enter the file or folder disappear. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (1 x 3393)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|11.63GB (5.81GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/78153
