### ISSUE TITLE
provideSignatureHelp block extension ejecution

### ISSUE THREAD

**Issue by DracotMolver** [Microsoft/vscode#777]
I'm writing and extension where I use **registerCompletionItemProvider** 
```javascript
context.subscriptions.push(languages.registerCompletionItemProvider('php', new Completion(),'>'));
``` 
and I'm using **onDidSaveTextDocument**
```javascript
context.subscriptions.push(vscode.workspace.onDidSaveTextDocument((textDocument: vscode.TextDocument) => {
//...Some lines of code
}));
```
Here everything works fine. When I  seved a file, it throws me some text  and it shown using console.log(). At the same time, the Completiton works fines, showing me the some text of test. 
What I normaly do in a PHP file is a class with some methods.
```php
class Test{
 public funciton sayHello(){
   //...some code.
 }
}
$class = new Test();
$class->//Here shows me some text, thanks to registerCompletionItemProvider.
```
But when I do *$class->sayHello();* the Console debugger shows me provideSignatureHelp (ofcourse) but after this I can't keep using my code. when I write again $class->, nothing happends. So why is that?, If I'm using ">" to shows some info for completition and works fine till write a method and a provideSignatureHelp actions is triggered.

**Comment by roslanr18** [comment]
$class->sayHello();

**Comment by DracotMolver** [comment]
@roslanr18 is that a kinda of help?

**Comment by jrieken** [comment]
@DracotMolver Can you outline what your `provideCompletionItem` function looks like? 

I have understood the following steps:

* type `>`, completion is requested
* type `>` another time, no completion request happens

**Comment by DracotMolver** [comment]
@jrieken ok. This is what I have. I'm doing everything just in a single file for learning easily.
File extension.ts:
```javascript
import * as vscode from 'vscode'; 
var className, methods, importClassDefinition;
export function activate(context: vscode.ExtensionContext): void {
	console.log('Congratulations, your extension "phpclassmethods_is" is now active!'); 
	
	context.subscriptions.push(vscode.languages.registerCompletionItemProvider('php', new Completion(),'>'));
	
	context.subscriptions.push(vscode.workspace.onDidSaveTextDocument((textDocument: vscode.TextDocument) => {
			var text = textDocument.getText().toString().trim();
			className = text.match(/(class)\s([\w\d]+)/igm)[0]
							.replace(/(class)\s/,'');

			var importClassDefinition = ImportClassDefinition.getInstance();
			if(!importClassDefinition.classExists(className)){
				methods = text.match(/[\w\d]+(\().*(\))/igm);
				importClassDefinition.setClassParams(className,methods);					
			}
	}));
}
 
export class Completion implements vscode.CompletionItemProvider{
	public provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken) 
	: Promise<vscode.CompletionItem[]>{
		return new Promise((resolve, reject)=>{
			try{
			 	var completion:Array<vscode.CompletionItem> = [
					new vscode.CompletionItem('test')
				];
				
				resolve(completion);
			}catch(e){
				reject(e);
			}
		});
	}
}

export class ImportClassDefinition{
	private classes : Array<string>;
	private className : string;
	private classMethods : Array<string>;
	private static instance: ImportClassDefinition = null;
	
	constructor(){}
	
	static getInstance():ImportClassDefinition{
		if(ImportClassDefinition.instance){
			ImportClassDefinition.instance = new ImportClassDefinition();
		}
		return ImportClassDefinition.instance;
	}
	
	public setClassParams(className: string, methods:Array<string>){
		this.className = className;
		this.classMethods = methods;
		this.classes[this.className] = this.classMethods;	
	}
	
	public getClassParams(className: string) : Array<string>{
		return this.classes[className];
	}
	
	public getClassName() : string{
		return this.className;
	}
	
	public classExists(className: string){
		return undefined !== Object.keys(this.classes)[className];
	}
}
```

**Comment by jrieken** [comment]
@DracotMolver You mentioned `provideSignatureHelp` but I don't see that in your sample

**Comment by DracotMolver** [comment]
@jrieken  Sorry, Mayby there was a bad explanation by my side. I'm not using provideSignatureHelp. The provideSignatureHelp appears in the console debugger when I type "();", after that I can keep using the code.

**Comment by jrieken** [comment]
@DracotMolver I am sorry, but i still haven't understood the issue here? Can provide detailed steps or let me know if this became obsolete?

**Comment by narf** [comment]
I'm not sure if it's related but I wrote a plugin and everything is fine except that when the user is idle from vscode for some time (10-30minutes maybe) there is a message in the console "provideSignatureHelp" and then the plugin do not respond.

In "do not respond" I mean that you can't click on the status bar (well, you can but nothing happens) and all setInterval launched by the plugin have stopped (I added some console.log to debug and they are not showing)

**Comment by narf** [comment]
I'm wondering if it's because I don't dispose correctly of my all commands... Still looking for the problem.

**Comment by jrieken** [comment]
So, the `provideSignatureHelp` message came form an issue with the php language service. That also caused some unresponsiveness.
