### ISSUE TITLE
IntelliSense auto import in TypeScript stops working after extending module

### ISSUE THREAD

**Issue by pandaniell** [microsoft/vscode#77702]
IntelliSense does not suggest auto imports from external modules when extending the modules while importing local modules in a local file using declare module 'name' { }, if you manually import from the library there are no issues

**Comment by mjbvz** [comment]
Please share a code example along with steps to reproduce the issue

/neesMoreInfo

**Comment by mjbvz** [comment]
Closing as not actionable without repo steps
