### ISSUE TITLE
Option to open terminal in current working directory by default

### ISSUE THREAD

**Issue by methodbox** [microsoft/vscode#77703]
I realize this has been asked for before here:  https://github.com/Microsoft/vscode/issues/66721.
However, the provided solution sucks. It doesn't solve the problem.

The suggested extension doesn't even work.

The suggested solution is to use an extension, which is, in itself a bad solution when there is already a setting called "Terminal > Integrated: Cwd" which could be used for this **if the VS Code environment variable for the current project directory** could be provided as an argument.

The goal is simply that when I used the *default* command of Cmd + ~ or Ctrl + ~ to open an integrated terminal it by default starts in the project directory.

The suggested extension does not do this. It would require reassigning the keyboard shortcut to a command which is only accessible via the command palette. Not only is this slower, it's prone to break; I'm not even sure it's possible to make it function reliably.

My suggestion is modify the setting called "Terminal > Integrated: Cwd" to give the option of either providing a specific directory or simply checking a box to open it by default in the current project directory.

**Comment by methodbox** [comment]
To be clear this issue is in Windows, using git-bash. I don't think this is an issue on my Mac.

**Comment by Tyriar** [comment]
The cwd setting should resolve variables just like the other settings so this would work:

```
"terminal.integrated.cwd": "${fileDirname}"
```

**Comment by Tyriar** [comment]
FYI @lramos15

**Comment by lramos15** [comment]
We don't currently resolve variable references in `terminal.integrated.cwd` @Tyriar but the logic is there to do it with the executable, args, and environment I believe so it shouldn't be too much work to add it in this case. We might want to go ahead and add support for all terminal configuration references to be able to use variable references.

**Comment by methodbox** [comment]
FWIW I confirmed the desired behavior is the default on macOS.

Odd that it’s not in Windows.

**Comment by Tyriar** [comment]
@methodbox on macOS when you _split_ the cwd is inherited by the terminal it's split from, this is impossible to do on Windows. See `terminal.integrated.splitCwd`

**Comment by methodbox** [comment]
@Tyriar I’m not talking about when you split.

I’m simply talking about when you first pull up the terminal with Cmd+~.

Considering the working directory is known and the terminal can be opened with a command (in Windows) specifying which directory to open it in, I doubt it’s impossible.

**Comment by methodbox** [comment]
While I’m sure it’s a bit different doing this programmatically inside VS Code, here’s two examples: opening PowerShell and opening Git-Bash, respectively, in a specific directory.

https://stackoverflow.com/questions/14233659/open-powershell-in-a-specific-directory-from-shortcut

https://superuser.com/questions/1310814/git-open-git-bash-in-specific-directory

If it can be done with a simple command, I’m not sure what would be difficult about combining the suggestion by myself and  @lramos15 to allow this.

If an environment variable for the CWD exists already it seems it would be a matter of interpreting this along with the appropriate CLI command to open the respective terminal in the right directory.

**Comment by Tyriar** [comment]
@methodbox I believe the behavior you're describing is how it's meant to work, what directory does your shell open in? Can you show a screenshot and share your settings.json?

For me, I just set the shell to git bash and it opens in the opened directory (ie. the project dir): 

![image](https://user-images.githubusercontent.com/2193314/62002395-053f0d00-b0b8-11e9-8dac-fa0fe3ed6ce3.png)

Is that what you're expecting? What version of git bash do you have?

**Comment by Tyriar** [comment]
The fix that went in just now might not have been the fix to your issue @methodbox, my guess is you're on an old version of git bash that doesn't respect the cwd we give it. I'm interesting in getting to the bottom of your issue though.

**Comment by methodbox** [comment]
I’ll have to try it out at work tomorrow. Fortunately I’m on a Mac at home.

Unfortunately I use Windows at work ;)
