### ISSUE TITLE
reopen breadcrumb to the position where I left.

### ISSUE THREAD

**Issue by niudai** [microsoft/vscode#77709]
In a really long code file, I always use the new breadcrumb in vscode to navigate within the file like this:

![image](https://user-images.githubusercontent.com/44165182/61586566-0056f680-abaa-11e9-9d25-4b9f852970ff.png)

When I find the wanted property or function, I click the item in this list and the popup menu list would be closed.

But I reopen that breadcrumb menu, I wish it should be in the position where I left, not just the top.

You know, the reason behind the scene is locality. I always code in a little area, not whole through the file, wish the feature could be implemented in future release.

**Comment by jrieken** [comment]
Not sure that I understand. Selecting a breadcrumb item always reveals that item, that also means selecting the last item (rhs) reveals your current position. So, that should do what you are wishing for

**Comment by niudai** [comment]
I mean within a single file.
