### ISSUE TITLE
allow using icons in contributes.menus

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#77700]
atm in order to have an icon in the editor title bar area we have to first create a command and add the icon along with it [docs](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)

but what am trying to do is to add icons to an internal commands & currently am getting the command label in the title bar instead of icons :cry:

**Comment by jrieken** [comment]
Yes, that's the designed behaviour. You must define a command which assign this like human readable label, title, icons, category etc and then you define additional UI place where these commands show up

**Comment by ctf0** [comment]
> You must define a command which assign this like human readable label, title, icons, category etc 

> but what am trying to do is to add icons to an internal commands

which means that now we will have a duplicated commands & labels
