### ISSUE TITLE
Terribly Slow At Linux

### ISSUE THREAD

**Issue by mese79** [Microsoft/vscode#7770]
Hi
It is almost unusable on linux Manjaro(Arch based). after each key stroke it takes about 500-700 milliseconds to show the typed charater!
 
- VSCode:
Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Date 2016-06-14T12:54:38.105Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version: Linux 4.1.26-1-MANJARO

![shot](https://cloud.githubusercontent.com/assets/1878378/16118605/227be88e-33ed-11e6-8663-d61597dd258a.png)

**Comment by alexandrudima** [comment]
@mese79 Do you have a special setup?

Can you please profile where the CPU time is spent:
* `Help > Toggle Developer tools`
* `Profiles` tab
* `Start profiling`
* type
* `Stop profiling`
* save file and attach it here.

**Comment by mese79** [comment]
I guess this is more related to my **_intel integrated graphic card_** rather than VSCode itself.
As i said, on my laptop i have an intel onboard vga and Manjaro linux as OS. So i've figured out that i have the same problem with every application which uses chrome/chromium as an engine like google-chrome, Atom, Brackets and ... : It is very slow!! 
But on my PC with the same OS i have a pci express nvidia card and everything is fine. so i think for me it's time to buy a new laptop ;) 
Thanks for your efforts.

**Comment by alexandrudima** [comment]
@mese79 You could try launching vscode with `--disable-gpu`. That might help...

**Comment by mese79** [comment]
`--disable-gpu` did the trick! thanks.
