### ISSUE TITLE
Terminal output unrecognized words

### ISSUE THREAD

**Issue by hupo376787** [microsoft/vscode#77713]
- VSCode Version: 1.36.1
- OS Version: 18362.239

Steps to Reproduce:

1. Build https://github.com/robertodoering/harpy.git with terminal: flutter build apk --debug --flavor=free -t lib/main_pro.dart

![image](https://user-images.githubusercontent.com/14960168/61589138-82f6aa80-abd8-11e9-825b-b0d1c80b222d.png)

**Comment by Tyriar** [comment]
This sort of thing is normally related to locale not being configured correctly, searching should lead you to the answer.
