### ISSUE TITLE
Text blur

### ISSUE THREAD

**Issue by taoyouh** [Microsoft/vscode#7771]
- VSCode Version: 1.2.1
- OS Version: Windows 10 1511 (10586.318)
- OS DPI Setting: 150%

Steps to Reproduce:
1. Open VSCode
2. Type something
3. If the text is very sharp, then try zoom in or zoom out using ctrl + or ctrl -
4. The Text is now very unclear

**Comment by lediur** [comment]
This looks pretty similar to #5154 or #1896.

**Comment by bpasero** [comment]
@taoyouh we are in the process of updating to a newer electron version, I was wondering if you could give our latest a try to see if that resolves the blurriness. Just jump to our insiders build:

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by taoyouh** [comment]
Seems the insider-1.8.0 version solved the problem.

**Comment by bpasero** [comment]
Great thanks 👍

**Comment by dbaeumer** [comment]
Marking as verified based on user verification.
