### ISSUE TITLE
Unaesthetic display annotations

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#77711]
Issue Type: <b>Bug</b>

vscode can not show the javadoc beautifully
![image](https://user-images.githubusercontent.com/27731323/61587877-e4148300-abc4-11e9-8d45-d61f94d8c24a.png)
![image](https://user-images.githubusercontent.com/27731323/61587879-e840a080-abc4-11e9-8edc-6a56a5d0f21a.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|1.8.7
vscode-tomcat|ada|0.11.1
copy-relative-path|ale|0.0.2
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.8.5
vscode-npm-script|eg2|0.3.8
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-lombok|Gab|0.9.8
beautify|Hoo|1.5.0
relativepathrefactor|jak|0.9.0
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
docthis|joe|0.7.1
vscode-peacock|joh|2.4.0
intellij-idea-keybindings|k--|0.2.34
node-module-intellisense|lei|1.5.0
vscode-exec-node|mir|0.5.1
vscode-json5|mrm|1.0.0
python|ms-|2019.6.24221
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
debugger-for-chrome|msj|4.11.6
gradle-language|nac|0.2.3
vetur|oct|0.21.1
vscode-versionlens|pfl|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.9.0
vscode-manifest-yaml|Piv|1.9.0
vscode-spring-boot|Piv|1.9.0
java|red|0.47.0
vscode-xml|red|0.7.0
vscode-yaml|red|0.4.1
vscode-leetcode|she|0.15.2
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5
vscode-icons|vsc|8.8.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue and describe the expected behavior

/needsMoreInfo

**Comment by bonaluo** [comment]
Put your mouse on the class or interface.In this case i use the interface Queue(java.util.Queue).The table should have been displayed.
![image](https://user-images.githubusercontent.com/27731323/61609037-6ebdb680-ac87-11e9-9cf1-5318025974ab.png)

**Comment by mjbvz** [comment]
Please file this against your Java extension
