### ISSUE TITLE
crash down

### ISSUE THREAD

**Issue by sofu456** [microsoft/vscode#77716]
Issue Type: <b>Bug</b>

crash down by [Extension Host]% null

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.8.5
code-gnu-global|aus|0.2.2
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
cocos-debug|Chu|0.0.1
vscode-devtools-for-chrome|cod|0.0.5
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
python-extension-pack|don|1.6.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
vscode-fold|fel|1.4.3
vscode-solution-explorer|fer|0.3.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
godot-tools|gee|0.3.7
vscode-javac|geo|0.2.20
cmake-integration-vscode|go2|0.6.1
beautify|Hoo|1.5.0
dotnet-core-essentials|Kis|0.0.7
node-module-intellisense|lei|1.5.0
cmake-tools-helper|mad|0.2.1
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.36.2
python|ms-|2019.6.24221
cpptools|ms-|0.24.0
csharp|ms-|1.21.0
Go|ms-|0.11.4
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.2
vuejs-extension-pack|mub|1.1.5
gulptasks|nic|1.3.1
vetur|oct|0.21.1
java|red|0.47.0
vscode-essentials-snippets|rob|2.0.0
watch-in-chrome|sne|0.0.2
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|1.5.0
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
unity-debug|Uni|2.7.2
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.18.1
quokka-vscode|Wal|1.0.236
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.4.1

</details>

**Comment by THE-ORIGINAL-MASTER** [comment]
It is easy pay me

**Comment by THE-ORIGINAL-MASTER** [comment]
I am not fixing shit tell I have been and have signed con with all my shares on it

**Comment by THE-ORIGINAL-MASTER** [comment]
The more you fix the worse it is going to get

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
