### ISSUE TITLE
sidebar has the same color customization with command panel

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#77712]
changing side bar background will also change command panel background

- VSCode Version: 1.36.1
- OS Version: 10.14.5

Steps to Reproduce:

1.  try to change the background color of command panel.
2. You will likely put something like this in the settngs.json
```json
"workbench.colorCustomizations": {
	"sideBar.background": "#282a36",
},

```
3. that code will change the color of the sidebar as well

Does this issue occur when all extensions are disabled?: yes

**Comment by aeschli** [comment]
What is the `command panel`? See [here](https://code.visualstudio.com/docs/getstarted/userinterface) for the names of the various parts in VSCode....
Also please add a screenshot.

**Comment by craigcosmo** [comment]
`command palette` I meant.

<img width="1277" alt="Screen_Shot_2019-07-22_at_3_49_20_PM" src="https://user-images.githubusercontent.com/538657/61619132-776ab880-ac98-11e9-9eb1-afe08a920f3a.png">

**Comment by aeschli** [comment]
there's now "quickInput.background"

fixed by https://github.com/microsoft/vscode/issues/65153
