### ISSUE TITLE
Markdown bold and italics doesn't work following an indented line

### ISSUE THREAD

**Issue by margold** [microsoft/vscode#77722]
- VSCode Version: 1.36.1
- OS Version: MacOS 10.14.5
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. An indented line following an unindented line is rendered correctly.
<img width="739" alt="Screen Shot 2019-07-21 at 21 23 27" src="https://user-images.githubusercontent.com/2191414/61596636-fe1e8780-abfd-11e9-896b-5f059ba23443.png">

2. An indented line following another indented line is not rendered correctly. Note the different scopes detected in both examples.
<img width="741" alt="Screen Shot 2019-07-21 at 21 24 03" src="https://user-images.githubusercontent.com/2191414/61596637-fe1e8780-abfd-11e9-8abd-95e4a2d397a1.png">

I realize that you might be using a third-party library for parsing markdown. Happy to submit an issue/fix there if you can point me to it.

**Comment by mjbvz** [comment]
This is the correct behavior. four spaces or a tab creates a code block

**Comment by margold** [comment]
To add more info if anybody else wonders the same thing:
- Vscode uses CommonMark (FAQ entry: https://code.visualstudio.com/docs/languages/markdown#_does-vs-code-support-github-flavored-markdown, reference implementation: https://spec.commonmark.org/dingus/).
- Current CommonMark spec (v0.29) defines that a line is a code block if indentation is 4 spaces or more.
- The lists in my example were parsed as code blocks since I had indentation set to 4 spaces, and the first item in the list was indented (out of personal habit). To ensure that the list is parsed correctly, I either have to not indent the first item in the list, or if I want to stick with the habit of indenting the first item in the list, I have to set indentation to under 4 tabs.
