### ISSUE TITLE
Could not find or load main class when creating a new package

### ISSUE THREAD

**Issue by Jarvis-ZHChen** [microsoft/vscode#77729]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. create new project from maven (quick start)
2. create new package, then create a new java file with main method
3. run this main method.
it seems VSCode cannot generate .class file and folder in 'target' folder. Or should I generate these my self ? what's more weird is that .class file will be generated automatically when restarting VSCode.
![image](https://user-images.githubusercontent.com/45837977/61602846-d0712700-ac6d-11e9-95ff-b83611727497.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Please file issue against the Java extension you are using.
