### ISSUE TITLE
vscode package claims it has vscode.d.ts which it no longer does

### ISSUE THREAD

**Issue by joechung-msft** [microsoft/vscode#77723]
Update the `vscode` package description to reflect that it no longer contains `vscode.d.ts` and that extension authors should install `@types/vscode`.

https://www.npmjs.com/package/vscode

![image](https://user-images.githubusercontent.com/26208574/61596729-21284780-abbc-11e9-8904-98d593c79d01.png)

Related: #77610

**Comment by octref** [comment]
@joechung-msft It has never contained `vscode.d.ts`. In generated extension, we used to include a postinstall script that runs `node_modules/vscode/bin/install` that downloads `vscode.d.ts`.

I've already added a deprecation notice to https://github.com/microsoft/vscode-extension-vscode. I'll publish a new version.

**Comment by octref** [comment]
See 1.1.36.
