### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by sinceseason** [microsoft/vscode#77726]
- VSCode Version: 1.36.x
- OS Version: windows10 x64 home basic

Steps to Reproduce:

1.The vscode keeps crashing, i cannot open it

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please describe what you mean by crashing? Does the program never open?

/needsMoreInfo

**Comment by sinceseason** [comment]
yes. When I turn on the vscode, it craches. so that I can never open it.
Here is the gif.
![crash](https://user-images.githubusercontent.com/14029440/61678243-e0077300-ad34-11e9-9acb-a6783f235211.gif)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by sinceseason** [comment]
I didn't do anything, and the vscode could start.
