### ISSUE TITLE
"Use exclude settings" gear is unintuitive 

### ISSUE THREAD

**Issue by jcollum** [microsoft/vscode#77721]
Issue Type: <b>Feature Request</b>

https://github.com/Microsoft/vscode/issues/64561 

Totatlly agree with @natesilva here. Use a checkbox like most UX designers would use here. 

Under "Files to exclude" put a checkbox that says "Use search exclude patterns from Settings" 

A gear implies settings that I can change right there, not a toggle. I clicked that by accident and spent 5 minutes figuring out why files in my node_modules folder were coming up in search. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
I added a warning at one point that says "exclude settings are disabled", did you notice that? I have thought about making it more obvious. @misolori what do you think about making that message warning-colored with a ⚠️ icon?

**Comment by jcollum** [comment]
I just tried that gear again. 

![image](https://user-images.githubusercontent.com/704514/62013660-4d0e7480-b14a-11e9-94c9-bce473feae27.png)

When I click on that gear literally nothing happens. 

1.36.1

**Comment by skprabhanjan** [comment]
@roblourens As suggested above, a checkbox under "Files To Exclude" or next to it would be good enough rite ?
I agree this gear is confusing ( Given that nothing happens when clicked apart from the gear getting highlighted which is very hard to notice with the text box also selected ) .

**Comment by yisding** [comment]
In the latest 1.37.0 it looks like there's no way to revert the gear by clicking it. So if exclude settings are disabled for a workspace there's no way to change it back.

**Comment by jcollum** [comment]
@roblourens  this is not resolved, please re-open or create an issue with the proposed fix.

**Comment by roblourens** [comment]
Meant to close this as a duplicate of https://github.com/microsoft/vscode/issues/65317
