### ISSUE TITLE
Warnings showing up from a file with a number?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7773]
![image](https://cloud.githubusercontent.com/assets/900690/16120410/aa8bbc58-33df-11e6-8b0d-a4052b10b718.png)

This looks like a marker that is not for a file but something else?

**Comment by aeschli** [comment]
@bpasero Any reproducing steps? It's likely not the language server that made up these resources. The language server just validates what he is asked to do.

**Comment by bpasero** [comment]
No steps, I am just using this tool in selfhost.

**Comment by bpasero** [comment]
@aeschli actually found it:
* open git.contribution.css
* make a change
* open the file in diff viewer

**Comment by aeschli** [comment]
The document has URI `inmemory://model/3`.
The extension host gets a document open event on it. The language client sends it the the css extension which validates it and sends back problems.

@dbaeumer @jrieken @alexandrudima Any opinons where we should cut the flow? IMO the css language service should not make decisions on what documents to validate, it is just a service.
Maybe the extension host clients should not get document open events for diff documents. Or maybe the problem view should only show error for file resources located in the workspace.

**Comment by bpasero** [comment]
Marking important because we look silly. Can we not just in the marker service ignore markers produced for non-file non-untitled resource schemes?

**Comment by sandy081** [comment]
I do not understand one thing here.. I am getting this issue only on git.contribution.css file but not on other css files. 

Only difference I see is that git.contribution.css file has already a warning, I do not know how it matters.

Why is it so special about one file and not other files?

**Comment by dbaeumer** [comment]
I agree that we look silly here, however this is nothing the marker service should decide. It currently has special code for the counting ignoring these resources but that's a patch for the broader underlying problem described by @aeschli.

Not syncing inmemory:// resources is IMO not a good solution. I can easily think about use cases where inmemory:// resources needs to travel to the extension host and need to be validated. The open problem here remains that we need to find a 'better' name for them in the UI. May be the first line of the buffer like sublime in tabs.

In general I think we need to have a special schema for diff documents so that the system can distinguish them from inmemory. For those we can then decide to not make them 'visible' in the system as @aeschli suggests.

**Comment by alexandrudima** [comment]
I suggest that we clean up how these files are created.

fyi @joaomoreno @bpasero 
The git files IMHO should use `git-head://FILE_PATH` or `git-index://FILE_PATH` or whatever. Then, git would register itself as a document provider and the workbench would be able to open these files.

That is step number 1, that these files are actually addressable in our system. That would allow IMHO for the workbench to reopen diff editors when doing a Ctrl+R. Or to actually navigate to those files from the error list.

Step number 2 is for the css validator to register only on `file://` resources or other resources that are editable.

**Comment by jrieken** [comment]
I agree with @alexandrudima. The diff view should not use the `inmemory` scheme cos that's the default for any editor model. It's good that the css brain can work on those models. For LHS diff editor resources we should use a different scheme that everyone knows to ignore or maybe the diff editor creates a 'random' mode on the fly which only reuses tokenisation.

**Comment by bpasero** [comment]
I appreciate the ideas around introducing git URIs. The UX issue I have is that I see warnings for resources I cannot edit. Whatever we decide on doing, please do not show me warnings for resources that I cannot edit. I might be able to open them if we do all the things talked about here but I can still not fix the warnings.

I am not sure how to express myself better, sorry :)

**Comment by alexandrudima** [comment]
well, how can a language service extension recognize read-only resources. Are all the inMemory read only resources?

**Comment by dbaeumer** [comment]
@bpasero I fully agree that I don't want to see errors for read-only resource. Having a git-* schema would allow all validators to exclude those.

**Comment by bpasero** [comment]
@alexandrudima as of today you cannot edit any resource in the editor that has a different schema than `file` or `untitled`. That seems like a good start to filter...

Are we planning to allow extensions to open editors with other schemas and making those writeable? If not, we should start simple and only validate `file` and `untitled`.

Nevertheless, +1 for using domain-specific schemas if possible and not the default.

**Comment by sandy081** [comment]
Outcome of discussion is to come up with a new schema say private and do not send to extension host at all just like large files.

- Left hand side of diff-editor uses this private schema.

I think for in memory files, markers owners should be responsible for cleaning / removing the markers when the file is closed. This would 

- Let the user know if there are real problems (just like the case in Default Settings)
- Let the user not to worry about seeing them always and not able to take any immediate action

**Comment by sandy081** [comment]
I think excluding private/internal scheme file events at extension host does not look like a cleaner. As most of the users are interested to see the problems in preview / diff editors. Asking all extensions to do the clean up does not also help.

Here is another idea:
- For all internal (private, vscode) and inmemory scheme resources, let us (say IModelService) do the clean up during model dispose phase. 

I think this is cleaner and simpler solution.

**Comment by jrieken** [comment]
> For all internal (private, vscode) and inmemory scheme resources, let us (say IModelService) do the clean up during model dispose phase.

That's were we came from ;-)

I think it's OK to exclude some documents from the extension host but only if they are **readonly**, like left-hand-side diff, synthetic configurations document, etc.

**Comment by sandy081** [comment]
I tried excluding from extension host but I felt that is not the single point of place. 
- I excluded documents from all events (add, change, remove), Otherwise some extensions are able to validate.
- Excluding from all events causing some extensions to break. They are looking for document data on active editor change.

Probably we can discuss on Monday and figure out a solution.

**Comment by sandy081** [comment]
I would be also interested to know the story behind coming from cleaning up during model dispose :)

**Comment by gillez** [comment]
I still see this issue.  See the attached screengrab.  I am using VS Code v1.10.2 on OSX v10.11.6 (El Capitan)
<img width="620" alt="screen shot 2017-03-23 at 12 52 16" src="https://cloud.githubusercontent.com/assets/19570905/24248579/ecc623fa-0fc7-11e7-9caa-2291ad550176.png">

**Comment by dbaeumer** [comment]
This got fixed in the latest version of ESLint extension (1.2.8)

**Comment by gillez** [comment]
Thanks @dbaeumer, that's good news as this has been bugging me for months.  I'll upgrade ESLint and check it out.
