### ISSUE TITLE
Markdown preview problem

### ISSUE THREAD

**Issue by LiuyangRY** [microsoft/vscode#77736]
Issue Type: <b>Bug</b>

I write nearly 20 MSSQL queries and execute them in visual studio code, the results were showed in th right editor. Then I scrolled thoes data, and the data could not be showed normally.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.28.0
EditorConfig|Edi|0.13.0
vscode-nuget-package-manager|jmr|1.1.6
unity-code-snippets|kle|1.3.0
vscode-language-pack-zh-hans|MS-|1.36.2
mssql|ms-|1.6.0
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
csharp|ms-|1.21.0
Go|ms-|0.11.4
vetur|oct|0.21.1
markdown-preview-enhanced|shd|0.4.3
vscode-leetcode|she|0.15.2

</details>

**Comment by IllusionMH** [comment]
@LiuyangRY are you sure this is related to built-in markdown preview?
Extensions can create custom view so I suggest you to create issue in repo with `mssql` extension: https://github.com/Microsoft/vscode-mssql/issues

if this is one that you use
