### ISSUE TITLE
Support save a WorkspaceEdit

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#77730]
Currently there is an API `workspace.applyEdit(edit: WorkspaceEdit)`, it will be helpful to add an API to control whether to save all changes of a WorkspaceEdit.

It could be `workspace.applyEdit(edit: WorkspaceEdit, save?: boolean)` or a standalone API `workspace.saveEdit(edit: WorkspaceEdit)`.

**Comment by jrieken** [comment]
There is [`workspace.saveAll`](https://github.com/microsoft/vscode/blob/3d5cbf2538749f00e1d36907d67c25aa82ce4db1/src/vs/vscode.d.ts#L7775)
