### ISSUE TITLE
NPM Script Explorer no longer de-emphasizes pre/post scripts

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#77746]
With the old icons pre/post scripts where de-emphasized, since they are run as part of another script, see the `postInstall` and `pretest` scripts below.
 
![image](https://user-images.githubusercontent.com/172399/61623951-f4396a80-ac77-11e9-802b-05f4004f6a82.png)

Since the last icon update pre/post scripts are no longer rendered in a de-emphasized way.

![image](https://user-images.githubusercontent.com/172399/61624064-2e0a7100-ac78-11e9-97cf-1cb36b9b2881.png)

**Comment by misolori** [comment]
This should now be fixed:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/61643239-4c13a980-ac57-11e9-9626-e9228dfd4294.png">

**Comment by egamma** [comment]
@misolori looks great, thanks!
