### ISSUE TITLE
Select multiple search results entries

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode#77749]
Being able to use `Shift+Click` and `Ctrl+Click` to select multiple entries in search results would be useful.

**Selecting multiple search result entries**
1. Possible to dismiss multiple entries.
2. Possible to copy multiple entries.

**Selecting multiple search result entries within the same file**
1. When a search result is selected, pressing `Enter` selects the matched area in the file so that it can be edited. The same should happen when multiple entries within the same file are selected, so that the chosen matches can all be edited using multiple cursors.

**Selecting multiple files in search result**
1. Possible to dismiss all entries in multiple files.
2. Possible to copy all entries in multiple files.
3. Combined with https://github.com/microsoft/vscode/pull/76828, possible to reveal multiple files in Explorer. This makes it possible to for example delete multiple files or compare two files.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/47166
