### ISSUE TITLE
tsserver CPU consumption goes too high on just typing

### ISSUE THREAD

**Issue by whitecolor** [microsoft/vscode#77748]
- VSCode Version: 1.36 / insiders latest
- OS Version: windows 10

There are a lot of issues that tsserver (probably issue refers more to tsserver than vscode) consumes a lot of CPU.

Just when I type on the almost empty file, is start to consume 40%-60% cpu (In process explorer I see that it is tsserver, not some other inner processes, besides if ts server disabled/restarting not problems with performance while typing).

I understand probably my PC is not the fastest one, and tsserver analyzes file on very change, but still, maybe tsserver/vscode teams still could think how to make such scenario work quicker? 

Maybe introduce some debounce for type checking when typing or something like that.

Here is just demo on what i'm talking about. I tried on the latest insiders, and with all disabled extensions, the result is the same. Sometimes when I close all the editors and tabs it works quite ok (on small simple files).

I don't think that trace logs will help here, there is probably some quite basic and general issue with the approach of realtime type checking which shows itself on not very fast machines.

![slow-ts-vscode-ddd](https://user-images.githubusercontent.com/736697/61626419-b39d1980-ac96-11e9-8aa2-181d73005f8e.gif)

**Comment by mjbvz** [comment]
Is this causing any problems besides the cpu usage?

**Comment by whitecolor** [comment]
@mjbvz yes, external irritation and deep internal frustration

**Comment by axetroy** [comment]
same happen at my old Macbook.

Especially when the file is hundreds of lines, it can be delayed by a few seconds.

**Comment by mjbvz** [comment]
@whitecolor What specific user problems are you seeing? For example: do suggestions take too long to show up?

**Comment by whitecolor** [comment]
@mjbvz yes everything regarding code is working slower, autocomplete and type checking (error reporting).

**Comment by mjbvz** [comment]
Can you please file issues [upstream against typescript](https://github.com/microsoft/TypeScript/issues/new) for specific cases where the cpu usage seems too high on typing

Closing this as an upstream issue
