### ISSUE TITLE
Display viewlet temporarily on mouseover

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#7774]
It would be cool if viewlets displayed on a delayed mouseover (on top or in place of the currently opened viewlet), and would hide on a mouseout (showing the primary open viewlet again). When you click on the viewlet icon it would still then make that the primary opened viewlet like it does now.

So like is said in https://github.com/Microsoft/vscode/pull/7704 (future support for custom viewlets), it could be nice to have this, because I don't always want to have a viewlet open, I just want to take a "peek" for a second.

For example say there is a `Navigator` viewlet that displayed all the classes/methods/properties/etc. in the currently opened file. So, what I would do mouse over the `Navigator` icon and it would open, then say I click on `Method`, it would then navigate to the correct line where that `Method` is defined. Once I moused off of the viewlet it would then close and my `Files` viewlet would come back (or whatever one I had opened prior to the mouseover).

**Edit**

This would also be helpful when the viewlets are in a collapsed state (activated by pressing <kbd>Ctrl+B</kbd>).

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
