### ISSUE TITLE
Hover is too small when editor is too narrow

### ISSUE THREAD

**Issue by leedonhyun** [Microsoft/vscode#7775]
- VSCode Version:

Version 1.3.0-insider
Commit 9f2c1b7ddfdc631198e9b541072489af78b7cade
Date 2016-06-16T05:08:39.628Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version:
  windows 10
1. ![animation](https://cloud.githubusercontent.com/assets/8449892/16122060/ad52035c-3420-11e6-8de2-28fd63779fad.gif)
2. ![animation2](https://cloud.githubusercontent.com/assets/8449892/16122068/b16c951a-3420-11e6-9393-d27adbdab4f4.gif)

**Comment by joaomoreno** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/22350/25423434/f5bee570-2a64-11e7-94f6-636b53ff0ada.png)
