### ISSUE TITLE
Open file while preserving focus in the Explorer

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode#77750]
When clicking a file in the Explorer using the mouse, the file is opened, but focus remains in the Explorer.

When navigating the Explorer using the arrow keys, files are not opened (and it seems this behavior is not wanted https://github.com/microsoft/vscode/issues/17682). Pressing `Enter` opens the selected file and moves focus to the editor. A way to open the selected file without moving focus from the Explorer would be really useful. This would make it easy to quickly navigate the Explorer and see what files look like. I propose that pressing `Space` in the Explorer opens the selected file while preserving focus in the Explorer.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/28710
