### ISSUE TITLE
VSCode don't work when I delete files after global search

### ISSUE THREAD

**Issue by thomasyxy** [microsoft/vscode#77754]
- VSCode Version: 1.36.1
- OS Version: macOS mojave 10.14.5

Steps to Reproduce:

1. global search for a lot of files.
2. delete them in the directory.
3. I have to restart VSCode.

![image](https://user-images.githubusercontent.com/15939196/61631046-db52a880-acbb-11e9-955d-4b519c61bb5f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
How did you delete them? What does this have to do with the search exactly?

**Comment by thomasyxy** [comment]
@roblourens delete them by rm -rf ....
search result contain these files

**Comment by roblourens** [comment]
There is a bad slowdown here, we are refreshing the list once per file
