### ISSUE TITLE
Ubuntu: “unlock your keyring” on startup

### ISSUE THREAD

**Issue by elieobeid7** [microsoft/vscode#77756]
I'm using ubuntu 16.04 unity 64 bit and the latest version of VSCode. My computer suffers from “[unlock your keyring](https://askubuntu.com/questions/495957/how-to-disable-the-unlock-your-keyring-popup)” problem. I haven't fixed the problem, because all of the solutions providers either don't work or have severe security drawbacks.

The problem is that each time, right after login, if I want to use chrome or skype, I'll have to re-enter my login password, after that, I can use the software normally, the dialog is only shown once after logging in when trying to use chrome and skype, maybe firefox too.

Today I found out that VScode is asking for unlocking your keyring too, if I don't provide him that, it would be unusable, I can't type anything unless I enter the password, which is odd for an editor to ask for, it's only happening with the new version.

Unless it's caused by a plugin, the last time I installed an extension was months ago, even if that's the case, it's still a problem, it means that a single plugin can access the password manager and can render VScode unusable.

Or maybe it's caused by chromium since VScode uses electron and that uses Chromium, not sure.

**Comment by deepak1556** [comment]
@elieobeid7 can you try the exploration builds from here and see if the issue repros. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by elieobeid7** [comment]
I tried the deb file, it doesn't work.
