### ISSUE TITLE
extHostTasks.ts is using incorrect DTO and TASK in $resolveTask implementation (results in resolved tasks being ignored)

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#77757]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Write an extension that uses customExecution(s) and provides them during provideTasks. Make one of them a build task and set it as default so it is written to tasks.json.
2. Modify the task in tasks.json so it no longer matches what the extension will return from provideTasks. This ensures that resolveTask will be called.
3. Execute "configure default build task" again.

Result:
The extension's resolveTask API is called, but when the extension host attempts to create an ID in addCustomExecution (or addCustomExecution2) it fails because the extHostTask implementation of $resolveTask is not using the resolved DTO or the resolved task when calling these APIs.

**Comment by GabeDeBacker** [comment]
This was introduced by #71027

**Comment by alexr00** [comment]
This is intentional! the properties of a provided task are its ID. If the resolved tasks properties do not match the initial properties then they are not the same task.

**Comment by alexr00** [comment]
The goal here isn't to modify task definition properties of an existing task, rather it is to resolve a task that hasn't been provided. This is goodness and should be allowed.
