### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/vscode#77768]
Issue Type: <b>Bug</b>

Seems to happen randomly but pretty frequently at seemingly random times.

abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|3.0.3
spellright|ban|3.0.46
cake-vscode|cak|0.12.0
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.9.0
prettier-vscode|esb|1.9.0
scriptcsRunner|fil|0.1.0
code-runner|for|0.9.11
dotnet-test-explorer|for|0.7.1
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.0
vscode-peacock|joh|2.5.0
docomment|k--|0.1.8
chat|kar|0.15.5
terraform|mau|1.3.12
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.540
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.2
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.6.0
debugger-for-chrome|msj|4.11.6
fix-json|oli|0.1.2
vscode-manifest-yaml|Piv|1.9.0
blank-line-organizer|rin|0.1.5
terraform-doc-snippets|run|0.4.0
taskrunnercode|San|0.3.0
vscode-sass-format|sas|1.1.6
trailing-spaces|sha|0.3.1
azure-iot-toolkit|vsc|2.9.0

(1 theme extensions excluded)

</details>

**Comment by jeremytbrun** [comment]
Same issue.

**Comment by alexandrudima** [comment]
It's the `karigari.chat` extension. Please reach out to the extension author directly. See https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205
