### ISSUE TITLE
Error on git commit from terminal

### ISSUE THREAD

**Issue by juampa** [microsoft/vscode#77763]
Issue Type: <b>Bug</b>

I have configured VSCode as git editor with this configuration:

```
$ git config --global -l
core.editor=code --wait
diff.tool=default-difftool
difftool.default-difftool.cmd=code --wait --diff $LOCAL $REMOTE
```

When I try to commit changes in git I get this error:

```
$ git commit 
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/jc/p795q44101jb29m1h61jbhbm0000gn/T/AppTranslocation/7720399B-0AA6-4BB4-982E-A984FA8B9A6E/d/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: image not found
/usr/local/bin/code: line 10:  3411 Abort trap: 6           ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
error: There was a problem with the editor 'code --wait'.
Please supply the message using either -m or -F option.
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.61GB free)|
|Process Argv|-psn_0_434282|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
java|red|0.47.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by bpasero** [comment]
@juampa but normally starting VSCode from the command line works without error?

**Comment by juampa** [comment]
Yes, VSCode from shell works ok. I am trying to reproduce the error again and I can´t, it works perfect now. I will close it, but I don´t know which label must be added: invalid or not-reproducible. Thanks.
