### ISSUE TITLE
Triple-Slash directive not working

### ISSUE THREAD

**Issue by Zenoo** [microsoft/vscode#77761]
- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Reference a JS file using a Triple-Slash directive :   
`/// <reference path="../../../../node_modules/ajax-sender/AjaxSender.js" />`
2. VSCode doesn't create a shared context with the referenced file. *(Here, it should give me informations about the `AjaxSender` class, but it still shows `AjaxSender` as type `any`)*

If I understood the official doc correctly, it should create a shared context : [![jsconfig.json](https://i.imgur.com/4WvOUZ5.png)](https://code.visualstudio.com/docs/languages/jsconfig#_why-do-i-need-a-jsconfigjson-file)

If I'm mistaken, how can I reference an external JS object from another file so that code completion becomes available for this object?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share a small complex code example of what you are trying to achieve? Is `AjaxSender` supposed to be used as a global module?

**Comment by Zenoo** [comment]
I have multiple JS files imported in the same HTML page, but not as modules.
So I'd have 
```html
<script src="AjaxSender.js">
<script src="main.js">
```

So I know I have access to whatever I defined in `AjaxSender.js` inside the file `main.js`

Let's say I declared a class inside `AjaxSender.js` :

```js
class AjaxSender{
  constructor(){
    // ...
  }

  myMethod(){
    // ...
  }
}
```

And in `main.js` I have 
```js
/// <reference path="AjaxSender.js" />
```

I want VSCode to prompt me with the class `Ajaxsender` methods & properties if I start typing them.

**Comment by mjbvz** [comment]
Have you tried creating a `jsconfig.json` file?

**Comment by Zenoo** [comment]
I haven't no, the documentation I linked above tells me using a Triple-Slash directive should be enough.
Is it simply inaccurate or did I misunderstand?

What would the `jsconfig.json` look like in the example above?

**Comment by Zenoo** [comment]
@mjbvz I tried adding a `jsconfig.json` in the same folder as my JS file:

```json
{
	"include": [
		"*.js",
		"../../../../node_modules/ajax-sender/AjaxSender.js"
	]
}```

It doesn't work. I don't have access to the code completion for everything that's declared inside `AjaxSender.js`

**Comment by mjbvz** [comment]
Please share an example project. I don't understand what your project looks like and why you are using all the `../../..` stuff. Is `AjaxSender.js` under `node_modules` within the workspace you have opened?

**Comment by Zenoo** [comment]
@mjbvz I have a project that looks like this : 

```
root
∟ a
  ∟ a1
    ∟ a2
      ∟ a3
        ∟ a4
          ∟ main.js
          ∟ jsconfig.json
∟ b
∟ c
∟ node_modules
  ∟ ajax-sender
    ∟ AjaxSender.js
```

I want to get code completion for everything declared in `AjaxSender.js` when I'm in `main.js`

**Comment by mjbvz** [comment]
Our intellisense is not going to work properly with how your code is written. The problem is that you are trying to use globals from `ajax-sender` but we will always treat `ajax-sender` as an isolated module because `AjaxSender.js` uses `require` and `module.exports`

You should:

* use proper imports: either `import`, `require`
* write a [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) that specifies what your library's api looks like
