### ISSUE TITLE
[json] validation of date-time format not working

### ISSUE THREAD

**Issue by mrmydt** [microsoft/vscode#77765]
- VSCode Version: 1.36.1 (not working on 1.33.1 neither)
- OS Version: Windows 10, Mac OS 10.14.5

Steps to Reproduce:

1. Have a json-schema with type: "string" and format: "date-time"
2. Have a json file with a property that is defined in the schema as date-time and that contains a string that is definitely not a date-time (e.g. "blbabpabg")
=> Visual Studio Code doesn't show it as a validation error

Does this issue occur when all extensions are disabled?: Yes

In attachment, an example json-schema and a example json file. Note that the validation works fine with format: "email" (as shown in the example file).

[date_format_issue.zip](https://github.com/microsoft/vscode/files/3418289/date_format_issue.zip)

**Comment by harshsingla** [comment]
@mjbvz Will i can help you in solving the task as i also get the same problem and i solved it.

**Comment by alexr00** [comment]
Verified using schema:
```
{
    "type": "object",
    "properties": {
        "aaa": {
            "type": "string",
            "format": "date-time"
        }
    }, "required": ["aaa"]
}
```
and json:
```
{
    "$schema": "./jsonschema.json",
    "aaa": "4000-02-01 00:00:00"
}
```
