### ISSUE TITLE
Markdown: code preview styling needs polish

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7776]
I am comparing previous to new solution and I liked how code blocks got represented with a different background color:

Old:

![image](https://cloud.githubusercontent.com/assets/900690/16122316/e841fd8a-33e6-11e6-86e0-579676922e52.png)

New:

![image](https://cloud.githubusercontent.com/assets/900690/16122328/f01d84de-33e6-11e6-8631-51b927d83961.png)

**Comment by bpasero** [comment]
I find the old way nicer to read, more examples:

![image](https://cloud.githubusercontent.com/assets/900690/16122392/2e8e0536-33e7-11e6-84db-c07acbfe84dd.png)

**Comment by TheColorRed** [comment]
Could It also be possible for users to define an overridable stylesheet to override the defaults? For example say I want to use twitter-bootstrap for my styles...

**Comment by bpasero** [comment]
We used to have a way to configure the CSS to use for previewing but I am not sure we lost this with our new markdown extension.

**Comment by kieferrm** [comment]
Forgot to contribute the actual configuration option...  fixed in #7832.
