### ISSUE TITLE
Adjust Code Tab Size to 4 in Markdown Preview

### ISSUE THREAD

**Issue by Neonit** [microsoft/vscode#77779]
**This issue has been created for tracking purposes. I have created a PR for this feature already: https://github.com/microsoft/vscode/pull/77745**

Please set the default tab size to 4 in the Markdown preview for code blocks in Markdown documents. I consider a tab size of 4 being standard and the default of 8 being unbearable. The few people, if any, using a different tab size than 4 can use the custom markdown preview style feature, if it is going to be fixed anytime (https://github.com/microsoft/vscode/issues/77290).

**Comment by mjbvz** [comment]
Fixed by #77745
