### ISSUE TITLE
Renaming a file before saving causes contents to be lost

### ISSUE THREAD

**Issue by bhanke-msft** [microsoft/vscode#77778]
Issue Type: <b>Bug</b>

1. Create a new file, e.g. MyClass.ts
2. Write something incredible
3. Decide to rename your class
4. Rename the file to match your new class name, e.g. WorldPeaceSolver.ts
5. Watch in horror as your life's work is irretrievably lost

Example alternative behaviour:

1. Pop up a box that says something like "Would you like to save your changes first?"
2. Copy the original unsaved contents into the new file's buffer

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

**Comment by bhanke-msft** [comment]
Apologies in advance if this is a known issue / popular feature request. I did look, but was unable to find anything.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by bhanke-msft** [comment]
Ah, no it doesn't. It's a fair cop. Thanks.
I'm also having trouble reproducing the issue in VSCode now too, but the TSLint extension did update itself between runs so maybe that was involved somehow.
