### ISSUE TITLE
Bug: Emmet expansion doesn't work when parentheses are used inside text node 

### ISSUE THREAD

**Issue by devanshj** [microsoft/vscode#77776]
Already being tracked via [vscode-emmet-helper #31](https://github.com/microsoft/vscode-emmet-helper/issues/31). I thought I should also file an issue here. I also opened a [PR that fixes this](https://github.com/microsoft/vscode-emmet-helper/pull/32).

**Comment by devanshj** [comment]
Hi @octref, I think this issue is a low hanging fruit it won't take more than 5 minutes to review the PR. I would love if you could prioritise it. Thanks! :)

**Comment by jakehockey10** [comment]
What is the best way to tell when something like this is released?  This is still happening for me and I don't know if I have received the fix or not.

**Comment by devanshj** [comment]
@jakehockey10 I'm not sure what's the best way, members can tell you more... But what I suspect is once there's a `verified` label that means it's verified and available in the Insider's Build (you can actually download that for early updates) and then you can check the release date in issue labeled as ["[Current Month] Endgame"](https://github.com/microsoft/vscode/issues/81667). So release date that has this fix is tentatively 9th of October. I hope this helps!
