### ISSUE TITLE
Terminal lose log when resizing

### ISSUE THREAD

**Issue by angel-luis** [microsoft/vscode#77775]
Issue Type: <b>Bug</b>

When I resize the attached window for the Terminal, I lose some lines of the log.

I'm using Powershell, and it happens when I've a Node server opened. I haven't tested another scenarios.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
dotenv|mik|1.0.1
vscode-language-pack-es|MS-|1.36.2
colonize|vms|2.2.2

</details>

**Comment by Tyriar** [comment]
You're likely seeing a problem in conpty, could you try repro in the Windows Terminal (via Microsoft Store) and report over at https://github.com/microsoft/terminal/issues if it happens there?
