### ISSUE TITLE
Terminal doesn't work!

### ISSUE THREAD

**Issue by lnxpy** [microsoft/vscode#77771]
Hello vscode developers,

I use Windows10. I've googled a lot for this issue but I didn't get anything. I've installed python interpreter and python extension on vscode but I can't run my program and after pushing F5 button the time out error appears.

When I push (CTRL+`)، the terminal bar will appear but the cursor is the only thing that is that bar! I've changed my default shell but nothing changed. I reinstalled vscode, and when I open the terminal it appeared just for 5 seconds and then It disappeared up to now.
I didn't find my solution on any websites. please help me to solve this issue step by step.

Thanks :)

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
