### ISSUE TITLE
"scss.validate" - Docs differs from Default Settings

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#7778]
- VSCode Version: 1.3.0-insider

There are a [doc for setting "sass.validate"](https://code.visualstudio.com/docs/languages/css#_customizing-css-sass-and-less-settings) instead of "scss.validate".
Other settings appers to be wrong too.

_Default Settings_ screenshot
![Default Settings screenshot](https://gyazo.com/1275ec05d26ef2af7c242452ed301d39.png)

**Comment by aeschli** [comment]
Yes, we renamed the SCSS mode id from sass to scss. The doc will be updated when we make the stable release.

**Comment by aeschli** [comment]
Made the change on the doc repo (not visible yet)
