### ISSUE TITLE
Inconsistent behavior with compound configurations depending on both settings.json and launch.json configurations

### ISSUE THREAD

**Issue by damolina-stripe** [microsoft/vscode#77782]
- VSCode Version: 1.36.1
- OS Version: MacOS 10.14.5

**Scenario**
Extension user reported a problem with a compound configuration not working correctly with a custom extension using `vscode.debug.startDebugging`. The extension creates a command  that sets up the debugging environment (e.g. starts services) before launching a given debug configuration by name.

**Steps to Reproduce**

0. Create a new workspace (any target should do).

1. Define a configuration structure similar to this: 

_settings.json_
```
...
"launch": {
  "configurations": [
    { "name": "Config_A", ... }
  ],
  "compounds": [
     { name: "Compound", "configurations": [ "Config_A", "Config_B" ] }
  ]
}
...
```
_launch.json_
```
...
"configurations": [
  { name: "Config_B" , ...  }
]
...
```
2. From the Debug drop down, select "Compound" and run. 
**This works.**  

3. Create an extension that runs this line (a workspace must be loaded): `vscode.debug.startDebugging(vscode.workspace.workspaceFolders[0], 'Compound')` 
 **This fails** with "Configuration 'Compound' is missing in 'launch.json'".

**Questions**

1. Should step 2 (run from drop down) work? It seems to me it should not:

    - According to this page: https://code.visualstudio.com/Docs/editor/debugging, _Tip: If a workspace contains a "launch.json", the global launch configuration is ignored_.

   - According to `WorkspaceConfiguration.inspect` documentation,  local values (launch.json) should override global (settings.json). This works _strictly_ as documented. For the provided repro: `Workspace.getConfiguration('launch').get('configuration')` only returns configurations in _launch.json_ (i.e. arrays are not merged),  `Workspace.getConfiguration('launch').get('compounds')` only returns compound configurations in _settings.json_ (i.e. because _launch.json_ does not define a _compounds_ value). Using `WorkspaceConfiguration.inspect`  I can verify all configuration values exists and are overriden as intended.

2.  If Step 2 should work, how to run step 3? i.e. how to use `vscode.debug.startDebugging` to call 'compound' successfully? 

3. If step 3 should not work, neither should step 2. Correct?

**Comment by damolina-stripe** [comment]
The idea would be for `vscode.debug.startDebugging` to have behavior parity with the _Debug_  dropdown, whatever the proper behavior happens to be. Extension users see it as an extension bug when behavior is not equivalent.
Having said that, it is not a P1 bug for sure but would it be possible to update documentation to call out this difference?

**Comment by isidorn** [comment]
I agree that there should be parity. And we will aim for this.
I think updating docs makes sense and we accept PRs in our vscode-docs repository https://github.com/microsoft/vscode-docs
