### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by bravostone** [microsoft/vscode#77780]
When I started VS Code and open any folder, show that message.

**Comment by jeremytbrun** [comment]
Same issue.

**Comment by alexandrudima** [comment]
What extensions do you have installed? We have seen a lot of issues coming in for crashes caused by `karigari.chat`. See https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205 . Do you perhaps have that extension installed? Can you try to disable it?
