### ISSUE TITLE
Intellisense and auto-formatting keeps crapping out.

### ISSUE THREAD

**Issue by ericklind** [microsoft/vscode#77785]
Issue Type: <b>Bug</b>

Hi,
Not really any steps to reproduce. I'll be working away and intellisense and auto-formatting stops working. I'm using it for .js files. Not sure why...maybe some extension(s) interfering? Nonetheless, it's really frustrating. Once I restart everything works for a bit then it just stops working again.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.8
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.6
vscode-jest|Ort|3.0.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by ericklind** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

I'm using the latest updated, but not the insiders. 

I can try disabling all the extensions, but again, I can't directly reproduce it as it will work fine for hours/days then suddenly stop working.

**Comment by mjbvz** [comment]
You have a few extensions that would be active in js files. Please try using the latest insiders build and with extensions disabled to see if you still hit this issue

**Comment by tlemo** [comment]
For what is worth, I noticed the same regression with VSCode + the Microsoft C++ extension (1.36.1). 

Also, the issue manifests on both Linux and Windows.

**Comment by ericklind** [comment]
It looks like it might have been the Auto Close Tag or the Auto Rename Tag by Jun Han. I disabled those and so far I have not run into the same issue.
