### ISSUE TITLE
Initialize repositories fully in Git extension API

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#77787]
Issue Type: <b>Bug</b>

On Windows where Git it slow, I frequently see that the `repositories` property on the Git extension API is first initialized to an empty array, and then later an update event is sent with the actual repositories. When consuming this API from the GitHub Pull Requests extension, this causes the tree text to read "No GitHub repositories found" on startup before the event is fired and the tree is loaded for whatever remotes are found. It would be great if we could avoid showing this intermediate and confusing text to users by having the `repositories` property set from the beginning.

VS Code version: Code - Insiders 1.37.0-insider (81ed55af79f01e9e64c3438558d2c2233e382a5a, 2019-07-22T07:16:47.743Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
The same happens in the SCM view: `No source control providers registered`.

To do this I would have to delay the extension activation until I get (some?) repositories. I'm not too convinced I should do this, since the extension should actually activate asap.

**Comment by RMacfarlane** [comment]
When the extension is activated but scanning for repositories hasn’t finished, is the user still able to perform any actions with the extension/is the UI able to be updated to display some information at that point?

I still think it’s weird for the initial state to be incorrect as a consumer of the API, but don’t want to impact performance. Would it instead be possible to send some sort of “finished initial scanning” event so that other extensions would know when state has been fully initialized?

**Comment by joaomoreno** [comment]
Pushed the concept of an `APIState`. The Git API starts with an `'uninitialized'` state, then goes through the initial scanning and changes to an `'initialized'` state once that's done. There's also a `onDidChangeState` event.

Let me know if that's not enough. :+1:

**Comment by RMacfarlane** [comment]
Thanks Joao, this is great! ❤️ 

There's one more `await` I'd like to see added, though 😃 Right now, when scanning completes and the API state is `'initialized'`, the state for repositories has not been initialized. So trying to read `repository.remotes` gives an empty array at that point. The constructor for `Repository` calls status at the end, would it be possible to remove that and instead `await repository.status()` in the code that's creating the repository?

**Comment by joaomoreno** [comment]
I like that! Pushed: https://github.com/microsoft/vscode/commit/8213baf0769d63d6bc65db25b93fc5fb91432173
