### ISSUE TITLE
Tasks quoting options are incomplete for PowerShell

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#77786]
- VSCode Version: 1.36.1
- OS Version: Win 10 1903

Steps to Reproduce:

1.  In Tasks.JSON:
```jsonc
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo",
            "args": [
                {
                    "value": "${workspaceFolder}"
                }
            ],
            "problemMatcher": []
        }
    ]
}
```
2. Execute task on a 'workspace folder' that contains single quotes and spaces.

I am expecting to see the 'workspacefolder' as a single unbroken argument echo'd to the terminal.

VS Code appears to apply single quotes around the argument, but fails to escape the inner single quotes.

`> Executing task: echo Z:\Programming\PowerShell\`'test` $_` folder`' <`

If I used the option "quoting": "escape" then a path with a `$` fails because the `$` is not escaped.

I think the best thing would be to escape single quotes when single quoting a PowerShell argument.

It would also be nice if quote escaping could happen for expanded arguments in the "command" property, but that would take another signal, such as something like `${workspaceFolder escapeSingleQuote}`.

**Comment by msftrncs** [comment]
I also tried experimenting with using a scriptblock for the command, but VS Code fails to see it as such and quotes it, which makes the scriptblock a command name, which it cannot find.

(with "weak" quoting)
`> Executing task: & '{echo $args[0]}' "Z:\Programming\PowerShell\'test $_ folder'" <`

**Comment by msftrncs** [comment]
BTW, the tooltip seems to be wrong for the "weak" vs "strong" quote character on PowerShell.

ToolTip:
Weak - `e.g. ' under PowerShell and bash`
Strong - `e.g. " under PowerShell and bash`

Actually:
Weak - `"` for PowerShell
Strong - `'` for PowerShell

**Comment by alexr00** [comment]
' and " are consistent between powershelll and bash, so I'm leaving the tooltip as is.

Leaving open as a feature request for escaping single quotes in powershell.

**Comment by alexr00** [comment]
Changing the escaping could break many people who are used to the old behavior.
