### ISSUE TITLE
.gitcommittemplate is processed before the actual commit

### ISSUE THREAD

**Issue by riweckr** [microsoft/vscode#77798]
Issue Type: <b>Bug</b>

1. create a .gitcommittemplate e.g
    > #a comment
    > add/update/remove something
    > 
    > nice description...
2. create a new folder
3. open this folder with vscode
4. git init
5. create a file
6. go to "Source Control"

Current behavior:

The commit message is prefilled with

> add/update/remove something
> nice description...

Comments and newlines are removed.

Expected behavior:

1. Unchanged content of .gitcommittemplate is prefilled. (As git does)
2. Remove # lines after commit

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-54-generic

**Comment by joaomoreno** [comment]
Similar to https://github.com/microsoft/vscode/issues/74222#issuecomment-502022138
