### ISSUE TITLE
Can the official team provide a remote manager?

### ISSUE THREAD

**Issue by NMSAzulX** [microsoft/vscode#77791]
I am using vscode remote SSH plug-in development. 

**The steps make me feel cumbersome:** 

1. Open VSCode. 
2. Select a remote folder. 
3. Create a new window and input password twice. 

**Now, a total of two VSCode windows stay on the desktop.**   

----------

**I suggest providing a remote manager：**

1. Help install VSCode. 
2. Help VSCode install remote plug-ins. 
3. Help install the remote environment. 
4. Configure remotely according to different OS and manager the password. 
5. View the remote directory. 
6. Open the specified remote directory using VSCode without inputing password. 
7. Some management functions. 
8. Some statistical functions. 
9. As it is used locally, I don't have any good suggestions at the moment.

**Comment by roblourens** [comment]
You can try out the new setting `remote.SSH.useLocalServer` which will help with this scenario. But otherwise we recommend using ssh key auth instead of password auth.
