### ISSUE TITLE
[BUG] detecr tab size default 8 space.

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#77793]
- VSCode Version:
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.  I had set tab size is 4,

![BaiduHi_2019-7-23_11-51-59](https://user-images.githubusercontent.com/11532015/61681521-4e9dfe00-ad40-11e9-867b-21b791bfee2e.png)

2.**but I open some file, and input "Tab", it take 8 space.**

![BaiduHi_2019-7-23_11-48-28](https://user-images.githubusercontent.com/11532015/61681533-5bbaed00-ad40-11e9-8f12-ada3db58bcf2.png)

Does this issue occur when all extensions are disabled?: Yes/No
**yes**

**Comment by rebornix** [comment]
@jianboy do you have `editor.detectIndentation` turned on?

**Comment by jianboy** [comment]
> @jianboy do you have `editor.detectIndentation` turned on?

yes, of course.
![BaiduHi_2019-7-24_7-28-46](https://user-images.githubusercontent.com/11532015/61754193-bf96f180-ade4-11e9-9f63-ca70412df4d3.png)

**Comment by rebornix** [comment]
Close in favor of https://github.com/microsoft/vscode/issues/62143, which is fixed in master already.
