### ISSUE TITLE
Some of display name of config is not correct.

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#77794]
- OS Version:

Steps to Reproduce:

1. Install Azure IoT Hub Toolkit: https://github.com/microsoft/vscode-azure-iot-toolkit
2. Got to VS Code settings

Actual: 
![image](https://user-images.githubusercontent.com/1050213/61683792-76459400-ad49-11e9-9193-2d0beb868068.png)

Expected:
**D2C** and **IoT** are one word, should not be truncated

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/191807
