### ISSUE TITLE
Markdown: lost ability to provide custom CSS to use for styling?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7779]
I am missing the `markdown.styles` configuration we used to have for a user to use their own CSS for the preview. Was there a reason to not have it in our new extension?

Marking as important because this is feature loss that can be ugly for our users if they rely on it.

//cc @jrieken

**Comment by jrieken** [comment]
There is [code](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts#L203) to read them and support to [author](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L112) them...

**Comment by kieferrm** [comment]
See #8287.
