### ISSUE TITLE
Using semver used by vscode from vscode extensions ?

### ISSUE THREAD

**Issue by fforjan** [Microsoft/vscode#778]
I all, I'm currently playing with VSC extensions and create a very simple one in typescript as learning experience about managing nuget packages for project.json - nuget4code, https://github.com/fforjan/nuget4code.

At one stage, i had to reference semver package for node, but it seems it's already in use with vscode (i would have been surprised if it wasn't too).

Any idea how I can configure my extension to rely on the installed semver from Visual Studio Code and not provide my own ?

**Comment by SamVerschueren** [comment]
The packages used by VS Code are totally independent of the ones you use in your plugin. It are two separate things.

Even if it was possible, you should rely on it. What if VS Code decides to remove the package and use something like `semver-improved`? Your extension breaks... What if the next `semver` version has a breaking change which your extension can't handle? Your extension breaks... That's the whole idea of semver and package dependencies...

**Comment by fforjan** [comment]
Yo Sam ! (sorry i cannot resists ;))

That's the point on the platform. IT's the same with node dependencies ? I was thinking it was a core functionality.

It's working as it is, but I was thinking it was a core feature  ;)

**Comment by egamma** [comment]
As @SamVerschueren said, package dependencies between VS Code and extensions or between extensions are independent.

**Comment by SamVerschueren** [comment]
> Yo Sam ! (sorry i cannot resists ;))

@fforjan see what you did there :)
