### ISSUE TITLE
HTMLPart to survive restarts?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7780]
I am not sure if there is a technical reason for not implementing a `IEditorInputFactory` so that previews (e.g. markdown) survive a restart or refresh. Is it that we can only have the input when the extension is ready?

An example factory for file inputs is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.contribution.ts#L127

Today when you close and restart the markdown preview is closed. With our old markdown preview we were able to persist and restore it given the factory.

//cc @jrieken @kieferrm

**Comment by jrieken** [comment]
The problem is that the extension providing the actual content isn't necessarily active that that point. We would need to introduce an activation event ala `onDocumentRequest:markdown` which I am not super keen on.

**Comment by bpasero** [comment]
@jrieken I see, so URIs for the markdown inputs are only valid if the extension is activated. I thought all we need is to wait for extension host having started in https://github.com/Microsoft/vscode/blob/ben/dnd/src/vs/workbench/common/editor/resourceEditorInput.ts#L60 but turns out the extension would also have to be activated.

I think in general it would be cool if an extension that brings in a new URI scheme to the system would also get activated when this URI is being displayed.

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
