### ISSUE TITLE
Multiple prompts on Input variables when used by more than 1 task

### ISSUE THREAD

**Issue by demali** [microsoft/vscode#77803]
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic snap

Steps to Reproduce:

1. Create task.json with inputs variable.
2. Create more than 1 task which use the above inputs. 

Prompted multiple times for the same input variables because they were used by multiple tasks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by demali** [comment]
Attaching file tasks.json (as txt). Run the publish task and you will be prompted twice for inputs, once for mkdir and once for publish even though both of them use the same input variables.

[tasks (copy).txt](https://github.com/microsoft/vscode/files/3420932/tasks.copy.txt)

**Comment by alexr00** [comment]
I think this is fixed. Please ping if it isn't!
