### ISSUE TITLE
Find In Selection should be turned on only if multiline have been selected

### ISSUE THREAD

**Issue by namleasia** [microsoft/vscode#77805]
Enabled "Auto Find In Selection" in settings.

**Currently**:
When I select one/some words in one line, hit Ctrl+F, this words will be filled in find field automatically, and "Find in selection" also turned on automatically.

**Expected**:
- When I select one/some words in **one line**, hit Ctrl+F, this words will be filled in find field automatically, but "Find in selection" **should not be turned on**. "Find in selection" should be turned on **only if multiline** have been selected.

**Comment by jolleekin** [comment]
I suggest the VS Code team adopt the behavior of the Replace tool in WebStorm. To be specific,
- If the selected text is **an identifier**
    - fill the **Find text box** with the selected text
    - turn off **Find in selection**
- If the selected text is not **an identifier** (contains spaces, delimiters, ...)
    - clear the **Find text box**
    - turn on **Find in selection**

**Comment by rebornix** [comment]
Let's use #27083 to track this issue, the solution will be introducing a richer findInSelection option.
