### ISSUE TITLE
Renaming file in explorer not working ( large project)

### ISSUE THREAD

**Issue by laur1s** [microsoft/vscode#77801]
- VSCode Version: 1.36.0
- OS Version: Linux x64 5.1.16-1Manjaro

Steps to Reproduce:

1. Open a project with a lot of files
2. start renaming files, after some time the renaming will stop working( When I rename the file and press enter the name just stays the same)
(EDIT):
Simply reloading the Vscode window solves the problem temporary but after a while rename stops working again. 
Disabling extensions doesn't solve the problem

**Comment by laur1s** [comment]
Hey, why is this issue ignored? I also just noticed that actually when I create a file it is not displayed in the explorer bar.

**Comment by isidorn** [comment]
I was on vacation for 3 weeks, sorry for the slow response.
I will look into this next milestone
@joaomoreno this sounds like something you were hitting

**Comment by joaomoreno** [comment]
@isidorn This is what I hit: https://github.com/microsoft/vscode/issues/78153

**Comment by isidorn** [comment]
@laur1s I can not reproduce this issue. In the gif attached you can see me renaming a lot of files in the vscode repository (which has lots of files).
Let me know if you can reproduce this with latest vscode insiders https://code.visualstudio.com/insiders/

![rename](https://user-images.githubusercontent.com/1926584/62948752-42f4a300-bde5-11e9-9215-3b19b130d62a.gif)

**Comment by isidorn** [comment]
Data not provided -> closing this issue.
