### ISSUE TITLE
Tasks only: Problems panel re-opens file if a path is not normalized

### ISSUE THREAD

**Issue by csk-ableton** [microsoft/vscode#77804]
- VSCode Version: Tested with 1.36.1 and 1.37.0-insider
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Open a file `/Users/foo/dev/project/main.cpp`
2. Create a task with a problem matcher that uses absolute file locations
3. Start a task that generates an error with an unnormalized path: `/Users/foo/dev/project/output/../main.cpp:48:7: error:`
4. Click on the error in the problems pane

Expected: The cursor jumps to the position in the open editor view
Actual: A new editor is opened containing the relative part of the path. The file history contains a new entry. When using "Go to file", both file locations are offered.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
This doesn't seem fixed to me. Consider this extension:

```ts
function activate(context) {
  let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
    const diag = vscode.languages.createDiagnosticCollection();
    const uri = vscode.Uri.file(
      '/Users/pine/Code/work/vscode-extension-samples/helloworld-sample/package.json'
    );
    const uri2 = vscode.Uri.file(
      '/Users/pine/Code/work/vscode-extension-samples/helloworld-sample/../helloworld-sample/package.json'
    );
    diag.set(uri, [
      {
        message: 'wrong!'
      }
    ]);
    diag.set(uri2, [
      {
        message: 'wrong!'
      }
    ]);
  });

  context.subscriptions.push(disposable);
}
```

Here's what I see:

![image](https://user-images.githubusercontent.com/4033249/63961327-6c4c3a80-ca45-11e9-8323-4285eac75b40.png)

Other than the duplicated error messages, the editor also treat those two files as different files:

![image](https://user-images.githubusercontent.com/4033249/63961398-956ccb00-ca45-11e9-819a-8e1bc0c04a53.png)

**Comment by alexr00** [comment]
@sandy081 for diagnostics. I only fixed it for tasks. Closing again for verification with tasks.
