### ISSUE TITLE
Extensions settings are unknown until document is modified

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77800]
#33931 Issue Type: <b>Bug</b>

1. Open `settings.json`
1. All extension settings are `Unknown Configuration Setting` and dimmed out (not only disabled).

VS Code version: Code - Insiders 1.37.0-insider (e1d3dd53d17fb1529a002e4d6fb066db0a0bd385, 2019-07-23T05:23:48.960Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
Good catch.
