### ISSUE TITLE
Cursor turns into crosshair during Pytest debug session

### ISSUE THREAD

**Issue by gatopeich** [microsoft/vscode#77807]
Issue Type: <b>Bug</b>

Debug-run pytest tests, and cursor turns into crosshair.

If tests abort due to errors, the crosshair stays until I click or hit Esc several times.

Seems related to Internal Terminal issue #57141

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3786)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.31GB (9.35GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
code-runner|for|0.9.11
beautify|Hoo|1.5.0
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
sublime-keybindings|ms-|4.0.3
vscode-yaml|red|0.4.1
vscode-make|tec|1.0.2
vscodeintellicode|Vis|1.1.8

</details>

**Comment by gatopeich** [comment]
BTW I see another side effect: a file named "os.path^M" appears out of the blue in my workspace when running these pytests, and it contains a Postscript image!
```
%!PS-Adobe-3.0
%%Creator: (ImageMagick)
%%Title: (os.path
)
%%CreationDate: (2019-07-30T17:18:02+01:00)
%%BoundingBox: -0 -0 1148 1025
%%HiResBoundingBox: 0 0 1148 1025
%%DocumentData: Clean7Bit
%%LanguageLevel: 1
%%Orientation: Portrait
%%PageOrder: Ascend
%%Pages: 1
%%EndComments

%%BeginDefaults
%%EndDefaults

%%BeginProlog
%
% Display a color image.  The image is displayed in color on
% Postscript viewers or printers that support color, otherwise
% it is displayed as grayscale.
%
...```

**Comment by Tyriar** [comment]
The only thing that causes the crosshair cursor in the terminal is pressing alt, you probably got into a state somehow after pressing it but I can't seem to reproduce.
