### ISSUE TITLE
Search button gone

### ISSUE THREAD

**Issue by woto** [microsoft/vscode#77806]
- VSCode Version: 1.36.1
- OS Version: 18.04.2

Steps to Reproduce:
Unknown. After some time search button has gone. Also can't understand the reason why search panel moved down and way to move it left.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![image](https://user-images.githubusercontent.com/146704/61700005-9f175a80-ad44-11e9-8420-1c33b46efdb4.png)

![image](https://user-images.githubusercontent.com/146704/61708516-a430d580-ad55-11e9-8ea3-2cd7f1b8b4a1.png)

**Comment by roblourens** [comment]
Search can be moved between the panel and the side bar. If you want it back to the sidebar, right click it and select "Toggle search view position"

**Comment by woto** [comment]
> Search can be moved between the panel and the side bar. If you want it back to the sidebar, right click it and select "Toggle search view position"

Damn. Was clicking on a tab. Click on a content of search results helps. Thank you!
