### ISSUE TITLE
Syntax highlight bug

### ISSUE THREAD

**Issue by duskpoet** [microsoft/vscode#77808]
Issue Type: <b>Bug</b>

The following code has problems with syntax highlight following line, that has `resp.data.reduce`

```
export const createTableDataDuck = ({
    apiMetrics,
    tableColumns,
    tableDimensions,
}: TableDataDuckOptions) => {
    const togglePending = createAction<boolean>('tableData/togglePending');
    const toggleError = createAction<boolean>('tableData/toggleError');
    const setApiData = createAction<SetApiDataPayload>('tableData/setApiData');

    const initialState: TableDataState = {
        sortColumn: tableColumns[0],
        sortDirection: 'desc',
        pending: false,
        error: false,
        offset: defaultOffset,
        limit: defaultLimit,
        allIds: [],
        rowsById: {},
    };
    const reducer = createReducer<TableDataState>((on) => {
        on(togglePending, (state, pending) => ({
            ...state,
            pending,
        }));
        on(toggleError, (state, error) => ({
            ...state,
            error,
        }));
        on(setApiData, (state, { resp }) => {
            return {
                ...state,
                ...resp.data.reduce<
                    Pick<TableDataState, 'allIds' | 'rowsById'>
                >(
                    (acc, {}) => {
                        return acc;
                    },
                    {
                        allIds: [],
                        rowsById: {},
                    },
                ),
            };
        });
    }, initialState);

    function* watchFetchTableData() {
        let prevSelected: SelectData | undefined;
        let fetchTask: Task | undefined;
        while (true) {
            yield take();
            const selectedData: SelectData = yield select(
                tableReqParamsSelector,
            );
            if (prevSelected !== selectedData) {
                prevSelected = selectedData;
                fetchTask && cancel(fetchTask);
                fetchTask = yield fork(fetchTableData, selectedData);
            }
        }
    }

    function* fetchTableData(selectedData: SelectData) {
        const params = getTableRequestParams({
            ...selectedData,
            tableColumns,
            tableDimensions,
            apiMetrics,
        });
        yield put(togglePending(true));
        try {
            const data = yield callApi(getData, params);
            yield put(toggleError(false));
        } catch (ex) {
            if (!(yield cancelled())) {
                yield put(toggleError(true));
            }
        } finally {
            yield put(togglePending(false));
        }
    }

    return {
        reducer,
        saga: watchFetchTableData,
    };
};
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
clojure|avl|0.10.6
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
vscode-nginx-conf-hint|han|0.1.0
vscode-styled-components|jpo|0.0.26
debugger-for-chrome|msj|4.11.6
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.8
vim|vsc|1.8.2
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@duskpoet a screenshot can help with explaining the issue you run into.

**Comment by yndx-shri-reviewer** [comment]
<img width="907" alt="Снимок экрана 2019-07-24 в 17 30 50" src="https://user-images.githubusercontent.com/50715001/61802272-d9faba80-ae38-11e9-81cf-bc8d767d462b.png">

I also forgot to mention, that file is `.ts`.

**Comment by duskpoet** [comment]
<img width="907" alt="Снимок экрана 2019-07-24 в 17 30 50" src="https://user-images.githubusercontent.com/3032829/61802532-4bd30400-ae39-11e9-8548-9e50f282aafb.png">
I also forgot to mention, that file is `.ts`

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/784 to track upstream
