### ISSUE TITLE
`files.exclude` applies to findFiles() result when null provided as exclude argument

### ISSUE THREAD

**Issue by deitry** [microsoft/vscode#77813]
There is an extension which use [findFiles()](https://code.visualstudio.com/api/references/vscode-api#workspace.findFiles) API:
https://github.com/matepek/vscode-catch2-test-adapter/blob/474e6c3d06f7bc3706ac8ec21cdcfa8ad1b4c35b/src/FSWatcher.ts#L101

I notice that extension could not find executables inside `build/` when this folder is listed in `files.exclude` configuration: https://github.com/matepek/vscode-catch2-test-adapter/issues/113

As documentation stated, no excludes should apply when `null` is provided, so developer of extension and me consider this a bug.

Tested on VSCode Stable 1.36.1

**Comment by roblourens** [comment]
This is by design, and has always been this way, but I will update the comment on the vscode.d.ts to reflect this.

**Comment by jrieken** [comment]
> When `undefined` only default excludes will apply. When `null`, no search excludes will apply, but `files.exclude` will still apply.

@roblourens I am super confused by that and don't believe that this is by design. Wasn't https://github.com/microsoft/vscode/issues/33528 about that? Re-opening for a better clarification of the issue

**Comment by roblourens** [comment]
What I said makes no sense, I was misinterpreting a comment I made in an earlier issue. There is some bug here.

**Comment by roblourens** [comment]
This is from https://github.com/microsoft/vscode/commit/10c0126e4b69d3c0672cdb10cd8f0c987304ac4b#diff-667e490a03391a012e309e8a660ce628R539 :( I will add tests

**Comment by jrieken** [comment]
Thanks!

**Comment by deitry** [comment]
Thank you!
