### ISSUE TITLE
How do I make each row of buttons have its own value

### ISSUE THREAD

**Issue by macdawinter** [microsoft/vscode#77815]
Does anyone know what to do? I have code to show each row with its own set of buttons but every time I click one value it selects it for every row
![95B66188-FD36-49F6-9BBB-93BE95F6D1BA](https://user-images.githubusercontent.com/50878125/61715189-8b5efa80-ad2a-11e9-8e70-99226f6fb62a.jpeg)
![52BD8398-000E-4A34-929B-F3EC9345FF23](https://user-images.githubusercontent.com/50878125/61715191-8b5efa80-ad2a-11e9-81c4-15a4ce535cc8.jpeg)

**Comment by rebornix** [comment]
This issue seems not related to VS Code.
