### ISSUE TITLE
Add global setting to open terminal panel on bottom/right side

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#77818]
I can't find any global setting in VSCode to make it so terminal sticks to the right all the time by default.

Currently the default is bottom and you are forced to right click on panel and click every time:

![2019-07-23 at 14 52](https://user-images.githubusercontent.com/6391776/61717752-93825e80-ad59-11e9-8b1d-88e11b3284c3.png)

Perhaps there is a setting for this already to choose default location for terminal panel?

And if no, I would appreciate if it was added. Thank you.

**Comment by usernamehw** [comment]
```json
"workbench.panel.defaultLocation": "right",
```

**Comment by nikitavoloboev** [comment]
Thank you. I knew there should be a setting for it.
