### ISSUE TITLE
File menu - recently opened files list

### ISSUE THREAD

**Issue by Meekie** [microsoft/vscode#77814]
Issue Type: <b>Feature Request</b>

Hi,

it would be a nice to have a list of recent opened files in the file menu.
Similar to Word etc.

Thanks,
Marcel

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by rebornix** [comment]
File -> Open Recent.
