### ISSUE TITLE
Firefox crashes when I start Code

### ISSUE THREAD

**Issue by Instagit** [microsoft/vscode#77816]
**VSCode Version:**

_Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.9-050009-generic_

**OS Version:**

_Ubuntu 16.04_

**Firefox version:**

_68.0_

**Steps to Reproduce:**

1. Have Firefox running.
2. Start VS Code.
3. All tabs crash (spinning wheel) and recover after around 10-20 seconds.

**Does this issue occur when all extensions are disabled?:** Yes

I'm a bit puzzled by this one, because what does Firefox have to do with Code? But it's 100% reproducible.

The Firefox _PROFILE/crashes/events_ directory is empty and I'm looking for a way to provide more information.

**Comment by tusharsrivastava** [comment]
Hi, I've also faced the same error and was about to create a Bug Report when I found it already created.

**Comment by bpasero** [comment]
@deepak1556 ever heard this?

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by tusharsrivastava** [comment]
@bpasero I've just downloaded the exploration build DEB and tested the same. I'm afraid but the issue is still there. I'm attaching two screenshots to maybe help you in any way possible. Thank you.

![Screenshot from 2019-08-05 18-35-00](https://user-images.githubusercontent.com/8246875/62466854-fb9c6000-b7af-11e9-9d41-e10abe42f55f.png)
![Screenshot from 2019-08-05 18-35-07](https://user-images.githubusercontent.com/8246875/62466867-022ad780-b7b0-11e9-9352-d61927ff212e.png)
![Screenshot from 2019-08-05 18-35-18](https://user-images.githubusercontent.com/8246875/62466881-0a831280-b7b0-11e9-8d66-6bf8580b3b69.png)

**Comment by bpasero** [comment]
Thanks for testing :+1:

**Comment by tusharsrivastava** [comment]
@bpasero @deepak1556 Just to make sure that the issue is not with Electron, I've just installed Atom editor and tested the same, it did not happen to crash my Firefox. So, we're sure that the issue is somewhere in VSCode's source code.

**Comment by bpasero** [comment]
@tusharsrivastava that depends. Atom might be using a very different Electron version from VSCode. Are you sure Atom is using Electron 4?

**Comment by tusharsrivastava** [comment]
@bpasero I checked, Atom is using Electron 3.1.10

**Comment by bpasero** [comment]
@tusharsrivastava so would you agree this could be due to the change in Electron versions?

**Comment by tusharsrivastava** [comment]
@bpasero I'm still not sure. Seems like Electron's issue but I guess we need more information here. Also, I'm not sure if a simple "Hello World" application in Electron 4+ can reproduce this bug?

**Comment by bpasero** [comment]
@tusharsrivastava yeah give it a try

**Comment by tusharsrivastava** [comment]
@bpasero I did the testing and sure enough, the bug is in electron's version. I ran the hello world application and it surely did crashed my firefox. What should we do next?

**Comment by tusharsrivastava** [comment]
@bpasero Moreover, I've just tested by launching google chrome and interestingly the issue probably is with Chrome/Chromium as electron's using the same and my firefox crashed again.


![Screenshot from 2019-08-06 18-09-09](https://user-images.githubusercontent.com/8246875/62540626-ab87d100-b875-11e9-9362-edb5e0e21cc9.png)
![Screenshot from 2019-08-06 18-09-13](https://user-images.githubusercontent.com/8246875/62540631-ae82c180-b875-11e9-9f98-4fb3e62ad273.png)
![Screenshot from 2019-08-06 18-09-25](https://user-images.githubusercontent.com/8246875/62540641-b0e51b80-b875-11e9-8e34-50c5ca3fdc34.png)

**Comment by bpasero** [comment]
@tusharsrivastava great, I suggest to report it over at https://github.com/atom/electron

**Comment by pmoris** [comment]
I'm facing the same issue and noticed this bug was also reported on the Mozilla bug tracker:

https://bugzilla.mozilla.org/show_bug.cgi?id=1566053

**Comment by tusharsrivastava** [comment]
@pmoris I've also faced the same issue when opening Google Chrome or Chromium. I guess the issue is rooted somewhere in chrome base.
