### ISSUE TITLE
Open Editors view is not assigning truly unique ids?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7781]
I am playing around with the new markdown preview and it seems that the IDs we use in the opened editors view are not truly unique. E.g. they just seem to rely on the name of the input which can be identical for two different inputs:

![image](https://cloud.githubusercontent.com/assets/900690/16124778/be7165fe-33f0-11e6-947c-cd92db56fe57.png)

**Comment by bpasero** [comment]
In this case I was opening the preview of 2 different markdowns, both named readme.md though.

**Comment by isidorn** [comment]
I am now also using the index of the editor input in the group to generate the id - so it should be trully unique.
Unfortuently I could not repro your test case since the markdown preview throws an error when I try it in out of source built vscode.

**Comment by bpasero** [comment]
@jrieken @kieferrm I saw this too, could it be that we miss to npm install in this extension?

**Comment by jrieken** [comment]
> IDs we use in the opened editors view are not truly unique

@bpasero What is the algorithms that defines the ID? This is where we create input: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/html.contribution.ts#L35

**Comment by bpasero** [comment]
@jrieken this is about IDs for tree items. I would think that taking an inputs resource is a good ID (@isidorn you should use it if you have it together with the position of the editor in the groups).

Editor inputs do not need an ID but the idea is that an editor input gets identified by its resource e.g. to find out if an editor is already opened or not. Some editor inputs do not have a resource associated but I consider that debt to change in the future.

**Comment by jrieken** [comment]
+1 for all inputs having a resource associated. Tho, it might still be the same resource for different inputs

**Comment by bpasero** [comment]
Also, usually we do an instance of check too, so that 2 inputs can have the same associated resource but are considered different.
