### ISSUE TITLE
Terminal bug

### ISSUE THREAD

**Issue by fhtozetto** [microsoft/vscode#77812]
Issue Type: <b>Bug</b>

After the last update of windows 10, my VScode terminal no longer opens integrated, when it opens it opens an external window and when closing the following message appears: "The terminal process terminated with exit code: 3221225786"

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.3.0
code-runner|for|0.9.11
vscode-language-pack-pt-BR|MS-|1.36.2
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.8.1
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, turn off legacy console in cmd.exe properties
