### ISSUE TITLE
Highlight the outdated dependencies versions

### ISSUE THREAD

**Issue by abdonrd** [microsoft/vscode#77811]
It would be great that VSCode highlight the outdated dependencies versions in the `package.json`.

The latest version appears in the hover tooltip:

![Screenshot 2019-07-23 at 13 13 29](https://user-images.githubusercontent.com/1007051/61707885-b73ea800-ad4b-11e9-8668-70fd14a3f5d2.png)

**Comment by egamma** [comment]
This extension already does this https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens
