### ISSUE TITLE
[Minor] Run-on in copy text

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/vscode#77827]
- VSCode Version: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
- OS Version: macOS

![No results found, run a previous search again:](https://user-images.githubusercontent.com/829827/61759635-bf174000-ad7d-11e9-91a8-31a727106c59.png)

This copy is a run-on, because it's two complete sentences joined by a comma. Instead, it should be: 

> No results found. Run a previous search again:

Repro steps:

1. Load a fresh VSCode window with no extensions.
1. Create a file with the following contents:
    ```ts
    const varThatIsReferenced = 0;
    console.log(varThatIsReferenced);

    varThatDoesNotExist;
    ```
1. Right click on `varThatIsReferenced` and choose "Find All References".
1. Right click on `varThatDoesNotExist` and choose "Find All References".
1. See the grammar error in the screenshot above.

**Comment by roblourens** [comment]
Where is this from? I don't think this is even from vscode

**Comment by NickHeiner** [comment]
I'm so sorry. I should have provided more detail. I mistakenly assumed that it this would be trivial to look up in a message property or translations file. I've updated the OP.

**Comment by roblourens** [comment]
It's from code that isn't in the main repo, so I didn't know where to search.

**Comment by hwhung0111** [comment]
I would like to give it a try.

**Comment by jrieken** [comment]
fyi - sources can be found here: https://github.com/microsoft/vscode-references-view

**Comment by NickHeiner** [comment]
Yep, here's the line: https://github.com/microsoft/vscode-references-view/blob/4d22ba8ee293caf7882882281b4002da57b52f8a/src/extension.ts#L37
