### ISSUE TITLE
Scrolling feels sluggish

### ISSUE THREAD

**Issue by mishushakov** [microsoft/vscode#77823]
- VSCode Version: 
<img width="396" alt="Screenshot 2019-07-23 at 17 07 40" src="https://user-images.githubusercontent.com/10400064/61723425-68edd100-ad6c-11e9-9a6b-05f19517d5a0.png">

- OS Version:
<img width="193" alt="Screenshot 2019-07-23 at 17 08 03" src="https://user-images.githubusercontent.com/10400064/61723480-81f68200-ad6c-11e9-8b15-d2eda080b81d.png">

Steps to Reproduce:

1. Open VSCode
2. Scroll a little bit

https://drive.google.com/open?id=1f9f-S7TY29uPqwjC4-fiOIDG_Hifh-6f

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@mishushakov may you help provide following information

* is it a regression with 1.36.1?
* when did you start to see this issue?

**Comment by mishushakov** [comment]
@rebornix 
Hey,
Really difficult for me to tell, when it first occurred, because most of the time i probably didn't actually noticed that.

If i open editor and scroll with touchpad (as in the video) i start to see, that some lines appear to move faster and some slower, which feels like a parallax effect to my eyes.

It reminds me of a frame-skip feature in Nintendos :D

First time i noticed it i just thought i'm going crazy, but after a good break i see, that it is not because of that...

Here is my configuration:

```json
{
  "files.exclude": {
    "**/__pycache__": true,
    "**/.DS_Store": false,
    "**/.git": true,
    "**/.gitignore": false,
    "**/.hg": true,
    "**/.svn": true,
    "**/.yarn-integrity": true,
    "**/CVS": true,
    "**/node_modules": true,
    "**/venv": true,
    "**/yarn.lock": true
  },
  "git.enableSmartCommit": true,
  "git.confirmSync": false,
  "vetur.validation.template": false,
  "editor.minimap.enabled": false,
  "workbench.panel.location": "bottom",
  "explorer.confirmDelete": false,
  "extensions.ignoreRecommendations": true,
  "explorer.confirmDragAndDrop": false,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "material-icon-theme.activeIconPack": "none",
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "workbench.enableExperiments": false,
  "workbench.statusBar.feedback.visible": false,
  "diffEditor.renderSideBySide": false,
  "rest-client.enableTelemetry": false,
  "editor.tabCompletion": "on",
  "workbench.iconTheme": "material-icon-theme",
  "breadcrumbs.enabled": false,
  "window.zoomLevel": 1,
  "editor.multiCursorModifier": "alt",
  "workbench.colorTheme": "One Dark Pro"
}
```

Here is a list of plugins:

<img width="289" alt="Screenshot 2019-07-23 at 21 46 09" src="https://user-images.githubusercontent.com/10400064/61742399-520ea500-ad93-11e9-931d-33ecb6691bc8.png">

Here is my trackpad configuration:

<img width="780" alt="Screenshot 2019-07-23 at 21 54 45" src="https://user-images.githubusercontent.com/10400064/61742953-8e8ed080-ad94-11e9-946a-3bf508c6ca65.png">

I will try it on a difficult mac tomorrow. Let me know anything i can share with you to find the roots of the issue.

Thanks.

**Comment by rebornix** [comment]
@mishushakov is there any particular pattern when you run into the scrolling lagging? For example, what is the language of files you are working, etc.

**Comment by mishushakov** [comment]
Yeah, its pretty annoying. Just noticed, that its not only in the editor, but everywhere. I didn't do anything special. Here some more vids:

Here is a full folder of videos with the bug:
https://drive.google.com/drive/folders/1b81jQNVhbvE9Cdz6QBC8XjMiyHZncDR5?usp=sharing

**Comment by iiKulakov** [comment]
Just fixed same problem by disabling in settings.json: 
`  // "window.zoomLevel": -1,`

**Comment by mishushakov** [comment]
Hey,
noticed another artefact in markdown files:
sometimes a pink line appears and disappears

<img width="593" alt="Screenshot 2019-07-27 at 14 59 20" src="https://user-images.githubusercontent.com/10400064/61994775-41a24700-b07f-11e9-8641-e2141d834c57.png">

Thanks.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by mishushakov** [comment]
The issue still persists on 1.37.0
