### ISSUE TITLE
Weird state with editors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7782]
Another weird state with tabs but no repro. The second editor isn't showing when I try to toggle it, when I split the editor through the UI it shows up but <kbd>ctrl</kbd>+num doesn't control it.

<kbd>ctrl</kbd>+<kbd>1</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/16126254/2f7a21c2-33ac-11e6-9e6a-7ba8b07fbc6f.png)

<kbd>ctrl</kbd>+<kbd>2</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/16126272/4494127a-33ac-11e6-9b38-4cbd1fa4b90c.png)

**After hitting the split button on the UI**

![image](https://cloud.githubusercontent.com/assets/2193314/16126169/dfda31a2-33ab-11e6-84e5-0e4905bf2fa3.png)

<kbd>ctrl</kbd>+<kbd>1</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/16126193/ed831594-33ab-11e6-82a1-65fef918a199.png)

Another quirk with this is that if the right editor is focused, <kbd>ctrl</kbd>+num does nothing.

**settings.json**

```json
{
  "editor.fontFamily": "Hack",
  "editor.roundedSelection": false,
  "editor.rulers": [ 80, 100, 120 ],
  "editor.selectionClipboard": true,
  "explorer.autoReveal": false,
  "editor.renderWhitespace": true,
  "workbench.showEditorTabs": true,
  "explorer.openEditors.visible": 0,
  "workbench.quickOpenPreviews": false
}
```

**Comment by bpasero** [comment]
Note that the tabs setting is now called: `workbench.editor.showTabs`
