### ISSUE TITLE
Can not signin Azure account under coporate firewall

### ISSUE THREAD

**Issue by rqwzhou** [microsoft/vscode#77825]
Issue Type: <b>Bug</b>

The issue was reported by many users, and still has issue with latest version 1.36.   Rollback 1.31, same issue .   Worked in different ways per people's option, none of worked.  Is there anyway give us a tranparent experience on this

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.65GB (8.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Exte

**Comment by rebornix** [comment]
cc @alexr00 as Christof is out.
