### ISSUE TITLE
http proxy setting doesn't work in builtin console

### ISSUE THREAD

**Issue by go101** [microsoft/vscode#77826]
- VSCode Version: 1.36.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
We could set `HTTP_PROXY` / `HTTPS_PROXY` environment variables for the terminal based on the `http.proxy` setting, but then we would also need to consider setting these variables based on Electron's resolveProxy API.

Not sure if any of this is desirable. Assigning to you @Tyriar for consideration.

**Comment by Tyriar** [comment]
> but then we would also need to consider setting these variables based on Electron's resolveProxy API.

@chrmarti not clear what you mean here?

**Comment by chrmarti** [comment]
Electron has an API that you can ask for the proxy server given an URL. We could set `HTTP(S)_PROXY` based on the result from that for an example URL. That wouldn't always be accurate (different URLs might need different proxies), but might be sufficient in many cases.

**Comment by Tyriar** [comment]
Oh ok, the less we touch the terminal environment the better imo. If this is a problem you can configure in your `.bashrc` to set `HTTP(S)_PROXY` (only when `$TERM_PROGRAM` = `vscode` if necessary).
