### ISSUE TITLE
enable drag and drop of multiple files on Linux using remote extension

### ISSUE THREAD

**Issue by WSLUser** [microsoft/vscode#77822]
Per release doc for Remote extensions:
> You can drag a single file from the remote VS Code File Explorer to your local machine. Due to an upstream limitation, we cannot support this on Linux formultiple files.

Please remove the limitation. This will help enable the offline extension install scenario that’s needed for working remotely.

**Comment by isidorn** [comment]
This is a chrome limitation, and since VSCode is built upon chrome we can not do anything about it.
Please file this feature request against Chrome. Thanks

**Comment by WSLUser** [comment]
> This is a chrome limitation, and since VSCode is built upon chrome we can not do anything about it.
Please file this feature request against Chrome. Thanks

There is a higher likelihood of the limitation being addressed if it was filed by someone on the VSCode team than some user. You could even file it against Electron and let them push it forward to chromium.
