### ISSUE TITLE
Format Document (PHP) doesn't format heredoc/nowdoc

### ISSUE THREAD

**Issue by TheDutchCoder** [microsoft/vscode#77829]
- VSCode Version: 1.36.1
- OS Version: MacOS Mojave 10.14.5

Steps to Reproduce:

1. Open a PHP file and write some heredoc with an erroneous end to the heredoc:
```
            echo <<<JS
            var foo = 'foo';
            JS;
```
2. Format document
3. Heredoc is not formatted to a valid heredoc

Expected result:
```
            echo <<<JS
            var foo = 'foo';
JS;
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
VS Code does not include a PHP formatter out of the box, so you are using some extension
