### ISSUE TITLE
After update to latest version

### ISSUE THREAD

**Issue by MohammadFakhreddin** [microsoft/vscode#77830]
Issue Type: <b>Performance Issue</b>

My editor gets slower overtime and I have to restart it to fix the issue,It was super good before current update
Thanks for your awesome editor

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nithramus** [comment]
Same here, the problem continued even after a full cleanup (extension, reinstallation etc...)

**Comment by rebornix** [comment]
Could you please follow our wiki https://github.com/microsoft/vscode/wiki/Performance-Issues to help provide more info about the performance issue you run into?

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.

**Comment by MohammadFakhreddin** [comment]
I fixed the issue ,
You need to disable crash report and then it works very much fast. 
I found it;s issue when I disconnect and reconnect to internet and saw that speed issue got fixed,
It's because of their crash reporter
