### ISSUE TITLE
Mac version frequently freezing "The window is no longer responding"

### ISSUE THREAD

**Issue by kwadsten** [microsoft/vscode#77834]
I've been getting multiple freeze up's lately on my Mac.

It seems to happen frequently, more so when opening a file in "new window" using Comand-K, O option.

I have re-installed multiple times (including Insider release).

The test I use is to have a few files open (including a large 500K html file), then open one of the small python files in a new window.  The new window does not respond and eventually comes up with the "The Window is No Longer Responding" message, wait or close.

**Comment by kwadsten** [comment]
And it just happened again.  I was typing "theme" in the Settings window and it froze after "the"
![Screen Shot 2019-07-23 at 4 27 46 PM](https://user-images.githubusercontent.com/3610869/61745171-e57db100-ad66-11e9-91a8-be4ed2fe09f9.jpg)

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by kwadsten** [comment]
I've re-opened this issue using the Help/Report issue feature as requested.  Still happening.

**Comment by jrieken** [comment]
Please follow this guide when it happens: https://github.com/Microsoft/vscode/wiki/Performance-Issues.
