### ISSUE TITLE
Default task no longer running

### ISSUE THREAD

**Issue by michaelwestbrook** [microsoft/vscode#77838]
Issue Type: <b>Bug</b>

My default task that has worked for 1+ years is no longer working. When I hit ctrl+shift+b the choose task menu comes up but nothing happens when I select the task.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
Can you share your task?

**Comment by michaelwestbrook** [comment]
`{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "build-deploy",
      "problemMatcher": [],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}`

**Comment by alexr00** [comment]
I can't reproduce this. Does your npm script still work if you run it from the integrated terminal as `npm run build-deploy`?

**Comment by michaelwestbrook** [comment]
Yes it does. That is how I am running it now. However I am also unable to reproduce the issue on my work machine. I will try to reinstall VSCode and update here with the results.

**Comment by michaelwestbrook** [comment]
Reinstalled everything and I am still experiencing the same issue. I will try to re-install and wipe all of my extensions and other data next.

**Comment by alexr00** [comment]
Can you try disabling all extensions? I'd also like to see all of your settings.json (user and workspace).
