### ISSUE TITLE
JavaScript syntax highlighting seems to break w/ ternary operators

### ISSUE THREAD

**Issue by tylucaskelley** [Microsoft/vscode#7783]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Paste in the following JS code while using any default theme (I'm using Dark+)
2. Observe the broken syntax highlighting

```js
export function uuid() {
    const pattern = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';
    const yVals = '89ab';

    return pattern.replace(/[xy]/g, (c) => {
        const d = c === 'x' ? Math.random() * 16 | 0 : yVals[Math.random() * 4 | 0];
        return d.toString(16);
    });
}
```

Here's a screenshot: 

![screen shot 2016-06-16 at 1 43 58 pm](https://cloud.githubusercontent.com/assets/5448759/16127026/b59a0dfa-33c8-11e6-80fb-767a64aa3c57.png)

I've tested with a few of the built-in and custom themes and problems stays the same, so I assume it has something to do w/ the way VSCode handles tokenizing pieces of a line using a ternary operator

**Comment by sandy081** [comment]
@tylucaskelley it got fixed in latest build (1.3). Thanks for reporting.
