### ISSUE TITLE
[Feature Request]  Add "Right click/create new document" for the task bar.

### ISSUE THREAD

**Issue by jeffstokes72** [microsoft/vscode#77833]
I'd like a right click/create new doc added to the right click menu on the task bar. I can close docs in a variety of ways but not create a blank one..

![image](https://user-images.githubusercontent.com/9102841/61744561-9daa5a00-ad65-11e9-9105-b4adf9b36909.png)

But if I right click on the taskbar, I get a white glove..

**Comment by isidorn** [comment]
You can double click on empty space in tab area.
You can ctrl + N, to get a new doc.
Putting it in that menu is out of scope and we would not add it there since there are alterantive ways to achieve this.
