### ISSUE TITLE
the update broke vscode 1.36.1

### ISSUE THREAD

**Issue by KazievKazi** [microsoft/vscode#77832]
- VSCode Version: 1.36.1
- OS Version: 10.14.5

Перестало работать.

1) intellisense не работает...
2) Что бы не сделал обдумывает пару минут...работать не возможно
3) и это на windows10 тоже самое

**Comment by rebornix** [comment]
@KazievKazi could you please provide more info about what goes wrong?

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
