### ISSUE TITLE
Howto configure serverReadyAction debugwithchrome point to a specific config 

### ISSUE THREAD

**Issue by nileio** [microsoft/vscode#77843]
I have setup chrome debugger and specific settings for launch configurations, such as pathmappings, sourcemaps, etc.

Can I configure the feature of "serverReadyAction" having an action: "debugwithchrome" to actually launch one of my existing 'chrome' launch configurations in my launch.json rather than start its own?

I am not sure , does the feature launch a default debug configuration of chrome or can it use my configured launch configurations ? 
There is no setting to define the name of chrome debug configuration.

**Comment by weinand** [comment]
Currently it is not possible to configure the "debugWithChrome" action to use a specific launch config.

**Comment by nileio** [comment]
thanks @weinand for reply. What is the current behaviour of this feature please ?

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode/issues/109931

(this is now done)
