### ISSUE TITLE
VS Code ( with Flutter ) - How to save DEBUG CONSOLE logs to file ?

### ISSUE THREAD

**Issue by GauravPatni** [microsoft/vscode#77849]
- VSCode Version: 1.36.1
- OS Version: Windows 7

I am using VS code with flutter , 
I need a way to save "Debug Console " logs to a text file.

Thanks ,
Gaurav

**Comment by isidorn** [comment]
Context menu > copy all > paste to a file
Automatically saving in a text file is currently out of scope

**Comment by ItsCubeTime** [comment]
Is there a way of automating this?

I would like to be able to view my console output through a file in real-time to achieve .log syntax hightlighting

**Comment by AxelFlores1990** [comment]
Same here as @ItsCubeTime

Please, theres any chance to reconsider open again this?
