### ISSUE TITLE
Shortcut to change border between editor windows

### ISSUE THREAD

**Issue by sanboxrunner** [microsoft/vscode#77846]
Hello,

I try to use VSC without touching my mouse as much as possible. One issue that I can’t find a solution for (it’s not super easy to google, at least to me) is changing the size of editor tabs/windows without using the mouse. 

I am not talking the “window” of the application but each editor. 

For example, if i am looking at some code, I might type Command + \ to split the editor, then Command 2 to the go to the newly created Editor panel, then page down to scroll down until I get to the other part of the file I need. Unfortunately, if the other file is now too wide horizontally, I don’t have a solution without grabbing the mouse.

If this is not yet a feature, I have a suggestion for usability — the User types some key combhination + arrow key to “select” the border within their current window. This way, we don’t need to assign every editor window a border, we just need to check when asked. So if the user asks to grab the bottom margin, but there is no bottom margin, we can ignore that request. We don’t need to, say, label every margin like we do for Editor windows (where a user can do Command + numeral to jump between them)

Thanks so much guys! Feel free to ask if clarification is need.

**Comment by sbatten** [comment]
I think you are looking for the commands: `Increase Current View Size` and `Decrease Current View Size`. They don't have default keybindings but you may add them yourself in the keybinding editor. Additionally, there is `Maximize Editor Group` which can be used to expand the current editor to the max dimensions.

**Comment by sanboxrunner** [comment]
@sbatten Thank you! I had confused that with the Editor zoom function and had ignored it when I was looking for something like this.

Perfect!
