### ISSUE TITLE
MS Python extension won't install with VS Code in user local folder

### ISSUE THREAD

**Issue by CloudbusterOhio** [microsoft/vscode#77859]
Issue Type: <b>Bug</b>

1) Install Visual Code in C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Visual Studio Code
2) Install MS Python extension version 2019.6.24221
3) Installation fails with message "Failed to install 'ms-python.python'.

VSIXInstaller log shows the following:
23-Jul-19 13:50:16 - Searching for applicable products...
23-Jul-19 13:50:16 - Found installed product - Global Location
23-Jul-19 13:50:16 - Found installed product - Visual Studio Community 2017
23-Jul-19 13:50:16 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.24.1
python-docs|Muk|0.8.3

</details>

**Comment by sandy081** [comment]
Where do you find this VSIX Installer log?

**Comment by CloudbusterOhio** [comment]
> Where do you find this VSIX Installer log?

If I remember corretly it was in <user>\AppData\Local\Temp. But I'm unsure now and can't locate it anymore.

I managed to install the VSIX package manually in VS-code, which worked fine. The same error happens when trying to update the package, and I have to perfom the download and install manually again.

**Comment by sandy081** [comment]
Can you please provide steps to reproduce it?
