### ISSUE TITLE
SIGINT not sent when hitting Stop button in Windows (but works on MacOS)

### ISSUE THREAD

**Issue by keless** [microsoft/vscode#77855]
- VSCode Version: 1.36.1 (system setup)
- OS Version: Windows_NT x64 10.0.17.134  (Windows 10)

Steps to Reproduce:

1. create a NodeJS app with process.on('SIGINT', handler)  in app.js
2. Add a nodeJS launch program configuration in Visual Studio Code
3. Run program in Debug from Visual Studio Code (hit green arrow button)
4. Stop program from Visual Studio Code (hit red stop square button)
5. Observe: the SIGINT signal is not received/handled by the nodeJS app before exiting

Does this issue occur when all extensions are disabled?: Yes

Also happens in latest insiders build (7/24/2019)

**Comment by weinand** [comment]
@keless this is a known Windows limitation. See VS Code doc: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_stop-debugging

> "Note that on the Windows operating system, pressing Stop always forcibly kills the debuggee and its child processes."

**Comment by keless** [comment]
Is there any reason VS Code on Windows cant intercept and send its own SIGINT (or allow for user settings to specify a behavior) before killing debuggee?

**Comment by weinand** [comment]
Windows doesn't have SIGINT. Please read https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js

**Comment by keless** [comment]
Thanks for the additional info. I'm beginning to understand the difficulty of supporting that particular set on Windows (and additional reading is showing that other methods of shutdowns in windows will also immediately kill an app with no recourse, so its definitely a thing).

Ultimately my problem is allowing a Nodejs server to shutdown properly during iterative testing when hitting that red button. Is there no better feature or common practice for shutting a server down nicely from Visual Studio Code on Windows? It seems like it shouldn't _have_ to be a two step process. Sorry if I'm belaboring the issue; I appreciate your time.

**Comment by weinand** [comment]
This is not really a VS Code issue because VS Code supports the two step process generically (but that requires that the debug extension cooperates).
In case of node-debug it seems to be difficult to cooperate because there are limitations on Windows. But if I read the [article](https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js) carefully, it looks like that SIGINT works on Windows 10:
> "I'm not sure as of when, but on node 8.x and on Windows 10 the original question code simply works now."

@roblourens could that be? If yes, you could opt-into VS Code's two step sequence.

**Comment by roblourens** [comment]
I do see it working in a windows terminal, however I can't get it to work with node's `process.kill`. `process.kill(pid, 'SIGINT')` is never received by the process, maybe node is not doing the right thing on windows yet. So I don't think I can improve this.

**Comment by weinand** [comment]
For now I've labeled this "upstream bug"
