### ISSUE TITLE
Can't rename a folder when its child file is used and without any prompt

### ISSUE THREAD

**Issue by zcqno1** [microsoft/vscode#77850]
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Run an exsiting app (I run it in the WSL)
2. Try to rename an existing folder in which some files has been used by other file. Just say `testt/test.js`, `test.js` has been imported in other file. Now try renaming `testt` to `test`.
3. Then folder name recovers to the original name when exiting the rename input box. And without any prompt.
4. Stop running the app or remove the child file importing in other file. And try again, rename successfully.
5. Keep running the app. Rename an invoving file and it's ok. 

Files and folders don't have the same rename strategy. That's strange.
It had better prompt something when an involving folder fails to be renamed.

Does this issue occur when all extensions are disabled?: No

**Comment by woaibiancheng01214** [comment]
Is it solved?

**Comment by isidorn** [comment]
As fro the no prompt -> there is already an issue for this (that the prompt should be shown)
