### ISSUE TITLE
Code Completion not work after use snippets.

### ISSUE THREAD

**Issue by DiamondYuan** [microsoft/vscode#77851]
![2019-07-24 14-30-22 2019-07-24 14_31_03](https://user-images.githubusercontent.com/9692408/61770384-b0816500-ae1f-11e9-9d28-e0d2da26e992.gif)

**Comment by jrieken** [comment]
it's this setting `editor.suggest.snippetsPreventQuickSuggestions`

**Comment by DiamondYuan** [comment]
https://github.com/microsoft/vscode/issues/50776
