### ISSUE TITLE
Can we open a specific workspace using vcsode CLI ? 

### ISSUE THREAD

**Issue by ayush-kalani** [microsoft/vscode#77854]
It would be great if we can open a workspace giving the options in vscode CLI.

options:-
-w = name of the workspace

example - code . -w fs1

**Comment by PatrickHeneise** [comment]
I'm just starting to use workspaces and it would be great if `code .` would open the first workspace file in the folder that can be found. If there are multiple, the `-w` option would be great.

**Comment by bpasero** [comment]
@ayush-kalani VSCode itself is not tracking workspaces by name, but needs the full file path. I fear you need to continue to pass in the path of the workspace file.
