### ISSUE TITLE
Interface Overview in Learn area of Splash Page

### ISSUE THREAD

**Issue by WillWagnerIV** [microsoft/vscode#77858]
Issue Type: <b>Bug</b>

1. Open VS Code with no file open.
2. Click the Interface Overview in Learn
3.  Note that the arrow for Source Code Management and the shortcut point to the Search across files tab, and the Search points to the Source Code management tab.  The two are reversed.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.28.0
gitlens|eam|9.9.1
python|ms-|2019.6.24221
csharp|ms-|1.21.0

</details>

**Comment by rebornix** [comment]
@WillWagnerIV may I ask if you have re-arrange the viewlet icons?
