### ISSUE TITLE
Drag and drop from Explorer onto VS Code multiple times resulted in "associated text model is undefined" error.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#7786]
- VSCode Version: 1.2.1
- OS Version: 10586.318

Steps to Reproduce:

1. Open VS Code (only instance with `--disable-extensions`)
2. Drag a file in to VS Code to open
3. Close file
4. Remove from file list (multiple times)
5. Repeat 2-4 several times.
6. Encounter the following error:
![image](https://cloud.githubusercontent.com/assets/494055/16129352/57075c7a-33b9-11e6-9d3e-b54c0eabae4b.png)
7. From then on, unable to open that file despite it being a valid file.

Restarting VS Code fixes the problem.

(I have had difficulty reproing this issue myself -- I'm not sure how to better reproduce the issue.)

Discovered while trying to repro https://github.com/Microsoft/vscode/issues/7787

**Comment by bpasero** [comment]
@dilijev does it reproduce using our insiders build?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by dilijev** [comment]
@bpasero Thanks for pointing me to the preview release. I'll run that for a while and see if I happen to observe this again.

**Comment by bpasero** [comment]
Ok please comment if it reproduces. We can reopen then.

**Comment by dilijev** [comment]
Yes, things seem to work better now. I'll let you know if I see any further problems.
