### ISSUE TITLE
git gutter decorations not showing on ssh remote development

### ISSUE THREAD

**Issue by cezarneaga** [microsoft/vscode#77865]
- VSCode Version: 1.36.1
- OS Version: OSX 10.14.6

I do not get the gutter decorations anymore. tried in insiders and issue persists there too. works as expected on local development.

Steps to Reproduce:

1. connect to ssh remote
2. change file

Does this issue occur when all extensions are disabled?: Yes/No
cannot check this as remote development extensions are needed.

**Comment by cezarneaga** [comment]
if i check git changes and then open the file from git panel they show up again. i saw this in other issues also and believe it may be a regression.

**Comment by joaomoreno** [comment]
I can't reproduce this.

Are you using symlinks at all?

**Comment by cezarneaga** [comment]
Yes. But accessing the repo from symlink or direct causes the same result

**Comment by joaomoreno** [comment]
Is any of the repository root's parents a symlink?

**Comment by cezarneaga** [comment]
Not below the root. basically in my home folder I can access the root of the repo through a symlink eg: `cd app`or direct `cd html/user/app`

home folder on the server

```

~

  - app  

  - html/user/app

```

**Comment by cezarneaga** [comment]
seems to be ok today if i access the actual not the alias. will close for now.
