### ISSUE TITLE
Python indentation error

### ISSUE THREAD

**Issue by nanguatou9** [microsoft/vscode#77860]
Issue Type: <b>Bug</b>

There is a serious indentation error in Python on the kubuntu 19.04 system.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.2.2-050202-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1400 Quad-Core Processor (8 x 1374)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.65GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
python-extension-pack|don|1.6.0
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.36.2
python|ms-|2019.6.24221
python|tht|0.2.3
vscodeintellicode|Vis|1.1.8
jinja|who|0.0.8

</details>

**Comment by rebornix** [comment]
@nanguatou9 can you please share some screenshot / recording to help troubleshoot?

**Comment by nanguatou9** [comment]
As shown, the indented space is too small. 
![Screenshot_20190724_153532](https://user-images.githubusercontent.com/31814335/61837538-c9d5f000-aeb7-11e9-8f41-bfd3febfbbb9.png)

This problem also exists on another kubuntu19.04 computer, but Ubuntu 18.04 does not have this bug, it may be a problem with the KDE desktop environment.

**Comment by nanguatou9** [comment]
Just showing the problem code running will not give an error. A similar situation has appeared on Atom (https://atom.io/)
