### ISSUE TITLE
run debug output missing

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/vscode#77867]
Issue Type: <b>Bug</b>

{
"type": "node",
"request": "launch",
"name": "Egg Debug",
"runtimeExecutable": "npm",
"runtimeArgs": [
"run",
"debug",
],
"console": "internalConsole",
"protocol": "auto",
"port": 9229,
"autoAttachChildProcesses": true
}
Starting according to the above configuration, only part of the log can be printed, and subsequent content will no longer be output. But if "console": "integratedTerminal", all the logs will be output.
Keyword: typescript, egg, debug

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (3.84GB free)|
|Process Argv|--file-uri file:///e%3A/%E6%A1%8C%E9%9D%A2/cc-server-in_api.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.1
gist|fan|0.0.1
svn-scm|joh|1.54.4
vscode-language-pack-zh-hans|MS-|1.36.2
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsc-netease-music|non|0.0.20
polacode|pnp|0.3.2
code-settings-sync|Sha|3.4.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|8.8.0

</details>

**Comment by lengyuxuan** [comment]
npm run debug: egg-bin debug -r egg-ts-helper/register

**Comment by weinand** [comment]
Please provide more information (e.g. screenshots) about what you expect to see and what is missing.

In addition please add a `"outputCapture": "console"` or a `"outputCapture": "std"` to your launch config. Does one of those makes a difference?
