### ISSUE TITLE
Reveal in browser

### ISSUE THREAD

**Issue by evan-zubov** [microsoft/vscode#77864]
In my workflow I often do following steps:
1. Copy Relative Path
2. Go to Chrome
3. Go to dev tools
4. CMD+P to go to file
5. Paste relative path copied in step 1
6. Go to the file.

Is it possible to combine this steps into one command? I understand that not everyone needs this feature, so it probably got to be an extension or something. Thanks!

**Comment by rebornix** [comment]
I'll suggest it to implement it in an extension.
