### ISSUE TITLE
ALT+LEFT/RIGHT does not take context/focus into account while Finding

### ISSUE THREAD

**Issue by Azarlak** [microsoft/vscode#77877]
Issue Type: <b>Bug</b>

### Reproduction steps
1. Open new file.
2. Type `a{`. The corresponding `}` is automatically inserted.
3. Press **CTRL+F** to bring up the find bar.
4. Type `b`.
5. _Note that now:_
    * The `{}` pair is highlighted in the editor
    * The bottom bar displays "Ln1, Col 3"
    * The cursor is to the right of the `b` in the find box
6. Press **ALT+LEFT**.
7. _Note that now:_
    * The `a` is highlighted instead of the `{}` pair
    * The bottom bar displays "Ln1, Col 1"
    * The cursor in the find box has not moved
    * _Alternating between **ALT+RIGHT** and **ALT+LEFT** right now would have these results:_
        * Would alternate between highlighting the `a` and the `{}`
        * Would alternate between displaying "Ln1, Col 1" and "Ln1, Col 4" on the bottom bar
        * Would not affect the cursor in the find box
9. Pressing **ESCAPE** to close the find box reveals that the cursor move is permanent, as in it wasn't just _visually_ moving while finding stuff, it _actually_ moved.

### Expected behavior
The expected behavior was that pressing **ALT+LEFT/RIGHT** while focused on the find box would...
* move the cursor in the find box to the beginning or end of the search string or RegEx.
* not affect the editor's cursor position.
### Additional Information 
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0

</details>

**Comment by rebornix** [comment]
I can't reproduce this issue in latest Insiders, can you help confirm that?
