### ISSUE TITLE
Incompatible NODE_OPTIONS makes starting VSCode impossible

### ISSUE THREAD

**Issue by glatzert** [microsoft/vscode#77871]
There's a problem if you need NODE_OPTIONS environment variables, which are not yet supported by the VS included node version. If such a variable is set, starting VS Code via Start Menu will fail silently and starting it via CLI will fail with `...\Code.exe: --max-http-header-size= is not allowed in NODE_OPTIONS`

Why is the variable necessary?
Node apparently had some security issue, which made them introduce a maximum header size of 8K. 8K is rather low for environments, where cookies containing access tokens, id tokens or both are present, which makes it necessary to set another value. Especially during development of angular the variable cannot be set via any other option, currently.

Unfortunately starting code fails, when the options are not known
Workaround is to call `set NODE_OPTIONS=` before starting VS and using non-internal cmd windows for `ng serve` and such.

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Set environment variable NODE_OPTIONS=--max-http-header-size=16384
2. Start VS code

**Comment by goosy** [comment]
NODE_OPTIONS environment variables worked fine before VSCode V1.35.1
However, after VSCode V1.36.0, it will not start properly.

**Comment by bmacnaughton** [comment]
node is in the discussing unflagging --experimental-modules, i.e., making them the default. when that takes place vscode will no longer run. maybe the priority on this issue should be reconsidered?

**Comment by bmacnaughton** [comment]
this should not be an issue - when it's unflagged vscode's version of node won't see a flag so won't enable `--experimental-modules` and won't encounter the problem. this is only an issue if the editor needs to run in an environment with `--experimental-modules` enabled.
