### ISSUE TITLE
Selecting a file should set focus on file's contents

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode#77872]
Issue Type: <b>Bug</b>

1. Open a folder of files.
2. Select a file from the list.
3. Invoke keyboard shortcut to Select All (Cmd-A or Ctrl-A)

ACTUAL: All files in the explorer are selected
EXPECTED: All text in the selected and newly open file should be selected.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (9.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
mssql|ms-|1.6.0
csharp|ms-|1.21.0
debugger-for-chrome|msj|4.11.6
vscode-code-outline|pat|0.2.1
java|red|0.47.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0

</details>

**Comment by isidorn** [comment]
Disagree. Where the focus we should select that.
You can switch the focus to the editor by pressing tab, or by pressing cmd + down.

Closing as we will not change this.

**Comment by ChrisMiami** [comment]
Then you should also NOT open the file.  I COMPLETELY DISAGREE with this since OPENING THE FILE CHANGES FOCUS TO THE FILE.
