### ISSUE TITLE
Trim git clone in command palette

### ISSUE THREAD

**Issue by suit0r** [microsoft/vscode#77878]
This is a small request to accept the whole `git clone SSH` inside the command palette.

So pasting the entire string in the Git: Clone command should resolve properly (rather throwing a permissions error, like i got last time).

Thanks

**Comment by rajathans** [comment]
Can you please explain the issue and the desired behaviour a little further.

**Comment by joaomoreno** [comment]
The `Git: Clone` command shows an input box to insert the repository to clone. The user wants to be able to paste `git clone URL` instead of just `URL` and have it simply work.

**Comment by hwhung0111** [comment]
@rajathans Are you still interesting at this issue? I would like to give it a try.

**Comment by rajathans** [comment]
yes @hwhung0111 I've started working on this

**Comment by suit0r** [comment]
> The `Git: Clone` command shows an input box to insert the repository to clone. The user wants to be able to paste `git clone URL` instead of just `URL` and have it simply work.

exactly @joaomoreno .

I've been thinking about the UX part @rajathans , and I think it would be nice if the paste command returned a processed string rather than allow for the full command to be inserted.

so on paste, the command palette would show `REPO@REPO` instead of `git clone REPO@REPO`

Thanks a lot everyone

**Comment by rajathans** [comment]
Hey @hwhung0111 you can go ahead with it. I've not been getting enough time lately.
