### ISSUE TITLE
Starts downloading OneDrive files on-demand

### ISSUE THREAD

**Issue by zuboje** [microsoft/vscode#77874]
Issue Type: <b>Bug</b>

Out of nowhere VS Code started downloading my files from OneDrive. I have not even opened any file that is stored in OneDrive I just randomly received notification "Code started downloading files"... I don't want VS Code to download any files on-demand that I have not opened to work on. I am using VS Code for Mac OS.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vs-code-xml-format|fab|0.1.5
php-intellisense|fel|2.3.10
gc-excelviewer|Gra|2.1.32
ftp-simple|hum|0.7.0
eml|lei|0.3.2
saml-extension|mca|0.0.8
powershell|ms-|2019.5.0
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.2

</details>

**Comment by isidorn** [comment]
I can not reproduce this.
Please file with reproducable steps
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
