### ISSUE TITLE
Drag and drop from Explorer onto VS Code sometimes doesn't work

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#7787]
- VSCode Version: 1.2.1
- OS Version: 10586.318

Steps to Reproduce:

1. Open VS Code (only instance with --disable-extensions)
2. Drag a file in to VS Code to open
3. Notice that file didn't open and was not added to the file list
4. Try to open the file again (usually works this time)

Does not consistently repro AFAICT. Might have something to do with window focus of explorer window and VS Code?

Sometimes happens while VS Code has been open for a while and has many instances and many files, but I have also seen it happen for the very first file I tried to open in a fresh instance of VS Code (as above) with no other instances or files open.

**Comment by bpasero** [comment]
DND into Code is being revamped for our June release. Please reopen if you still see it from latest.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
