### ISSUE TITLE
Add configuration item, Enter can both wrap and select grammar suggestions

### ISSUE THREAD

**Issue by imlijq** [microsoft/vscode#77870]
Issue Type: <b>Feature Request</b>

When using vscode, I am very accustomed to using the Enter key to select grammar suggestions instead of using the Tab key, so "editor.acceptSuggestionOnEnter" I will keep the default setting to "on". But there are some cases where I press Enter to just want to wrap, instead of choosing a grammar suggestion, this is when I press Enter but I choose the first suggestion. I hope that the carriage return and the suggested function can be combined on the Enter key. I want to add a configuration item. When this configuration item is set to true, the first syntax suggestion of vscode is empty, so click Enter will change the line, if you want to choose the real grammar suggestion given, as before, press the up and down keys to switch

As shown in the figure, after the configuration item is enabled, the first item of each grammar suggestion is a null value, which is convenient for direct line breaks.

![](https://cdn.nlark.com/yuque/0/2019/png/253016/1563973444986-66727b51-d72f-4532-ad41-f617f53ed4a4.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
> the first syntax suggestion of vscode is empty,

Do I understand that right? You want the first suggestion to be nothing, e.g an empty row, which on "select" enters a new line?

**Comment by imlijq** [comment]
Yes. I want the first suggestion to be nothing, it should be an empty row, which on "select" enters a new line

**Comment by imlijq** [comment]
> > the first syntax suggestion of vscode is empty,
> 
> Do I understand that right? You want the first suggestion to be nothing, e.g an empty row, which on "select" enters a new line?

Yes
