### ISSUE TITLE
keybindings.json causes UI to freeze for several seconds

### ISSUE THREAD

**Issue by russelldavis** [microsoft/vscode#77882]
- VSCode Version: 1.36.1 (also repros on insiders build)
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:
1. From the command pallete, choose "Preferences: Open Default Keyboard Shortcuts (JSON)
2. The UI freezes for several seconds.
3. Switch to any other tab.
4. The UI freezes for several seconds again.

While the keybindings.json file is open, it will continue to freeze when switching between any two tabs.

This seems to be caused by the code that's populating errors in the Problems panel for the keybindings. It seems like a separate bug that VSCode ships with problems in the default keybindings, but regardless, any problems there shouldn't cause the UI to freeze like this.

It also happens if you have errors in the user-generated keybindings file. The more errors, the longer the UI freezes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Can you please follow https://github.com/microsoft/vscode/wiki/Performance-Issues to create a performance log for the renderer process to help us troubleshoot?

**Comment by usernamehw** [comment]
It's probably because Problems tab in Panel doesn't truncate long messages. `keybindings.json` generates very long ones and it tries to render them offscreen, which still takes a lot of memory/CPU.

 Just a guess, idk.

**Comment by russelldavis** [comment]
@rebornix attached:
[CPU-20190724T120042.cpuprofile.zip](https://github.com/microsoft/vscode/files/3428397/CPU-20190724T120042.cpuprofile.zip)

**Comment by rebornix** [comment]
It seems we try to write a good chance of content into `textarea` for screen reader.

**Comment by russelldavis** [comment]
@rebornix here's the Performance tab recording: 
[Profile-20190724T140742.json.zip](https://github.com/microsoft/vscode/files/3428761/Profile-20190724T140742.json.zip)

(Note this should be really easy to repro if you need more data.)

**Comment by rebornix** [comment]
It seems @usernamehw 's right, the Problems Panel is triggering a reflow which takes seconds and it affects the textarea as a side effect.

**Comment by usernamehw** [comment]
Doesn't look fixed.

1. `keybindings.json`
```json
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
```
2. Open Problems Panel
3. Switch editor tabs

Version: 1.37.0-insider (user setup) cf03ea3729dc37e439d724267ad29dc5840f903a

**Comment by sandy081** [comment]
Reopening to investigate

**Comment by sandy081** [comment]
@usernamehw I cant repro it. Can you please take the cpu profile and share it?

**Comment by usernamehw** [comment]
[CPU-20190730T151429.zip](https://github.com/microsoft/vscode/files/3446698/CPU-20190730T151429.zip)

**Comment by sandy081** [comment]
@rebornix Looks like it is getting blocked in textareainput

![image](https://user-images.githubusercontent.com/10746682/62131254-710fb880-b2f8-11e9-8b37-63ced99b7c2c.png)

**Comment by rebornix** [comment]
@sandy081 actually the long running `layout` can be triggered by any element trying to update itself when the Problems Panel is open with the code snippet @usernamehw posted above. For example, I open the json editor for keybindings, open the Problems Panel then, and try to scroll the Problems

![image](https://user-images.githubusercontent.com/876920/62252445-bc34d480-b3a7-11e9-8f12-20446e453f5f.png)

As you can see from above screenshot, updating the filter input box is triggering a force layout and taking around 3 seconds.

IMO we may want to trim the problem messages in the Problems Panel, otherwise it will affect the whole workbench.

**Comment by sandy081** [comment]
@rebornix @usernamehw You are right. Root cause of this issue is the length of the message. Rendering a long message is impacting the performance.

I am trimming the message to max 1000 characters.

**Comment by sandy081** [comment]
To verify

1. Open `keybindings.json` and have following content
```json
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
{"command": ""},
```
2. Open Problems Panel
3. Switch editor tabs

Make sure there is not any lag.
