### ISSUE TITLE
VSCode freezes when trying to add folder to workspace. (macOS Catalina)

### ISSUE THREAD

**Issue by Harmiox** [microsoft/vscode#77880]
**Versions:**
- VSCode Version: 1.36.1
- OS Version: macOS Catalina (10.15 Beta)

**Steps to Reproduce:**
1. Open up Visual Studio Code
2. VSCode opens up the last workspace I had open.
3. Click `File > Add Folder To Workspace`
or
4. Click `File > New Window`, then click `Open Folder...`
5. VSCode is now frozen and I have to force quit the application/process.

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by Harmiox** [comment]
I apologize as apparently this issue is due to an iCloud bug on macOS Catalina. Since disabling iCloud I've experienced no issues with VSCode.
