### ISSUE TITLE
Can't open web links

### ISSUE THREAD

**Issue by cadu-tech** [microsoft/vscode#77885]
- VSCode Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-5-amd64

- OS Version: Linux Debian 10 Buster

Steps to Reproduce:

1. Open VSCode.
2. Click in any external web link.
3. An error message is shown because the string "/root/" is concatenated to the beginning of parameter [url] for window.open() call as follow in attached image.
![Screenshot from 2019-07-24 16-01-17](https://user-images.githubusercontent.com/24251894/61821546-e1689680-ae2d-11e9-8b80-22fc12d671eb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
It seems the web view in the screenshot is contributed by the Java extension, please file an issue against them.

**Comment by cadu-tech** [comment]
Sorry, I think you don't understand. It's a generic problem, not with the extension. I'm using code --disable-extensions. 
![Screenshot from 2019-07-24 17-02-05](https://user-images.githubusercontent.com/24251894/61824777-3956cb80-ae35-11e9-8f16-2eae8d192df4.png)

**Comment by bpasero** [comment]
That seems to be a link from a webview.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

The Java welcome page works for me using VS Code 1.37 on MacOS

**Comment by cadu-tech** [comment]
Hello, @mjbvz 

I downloaded the latest code insiders build as you suggested and tested. but the problem remains.

When I go to (for instance) Help -> Join Us on Twitter
![Screenshot from 2019-08-13 22-16-10](https://user-images.githubusercontent.com/24251894/62988192-cd56fa00-be19-11e9-8a2b-0580d5c75867.png)

**Comment by wendzhue** [comment]
Do it has anything to do with super user?

**Comment by cadu-tech** [comment]
Today, I saw the problem with other apps. Some of them can open external weblinks, while others can't.

So it's not a problem specifically with VSCode.
