### ISSUE TITLE
In class bodies, "this." is replaced by the first autocomplete suggestion

### ISSUE THREAD

**Issue by sstephenson** [microsoft/vscode#77881]
Issue Type: <b>Bug</b>

1. Create a file test.js.
2. Paste the following text:
```js
class Test {
  x() {
    
  }
}
```
3. On line 3, type `this` and observe the autocomplete suggestions show symbols containing the word "this", but not the symbol `this` itself.
4. Type `.`. The text `this.` is replaced by the first autocomplete suggestion; in my case it's `globalThis.`.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.63GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
troff|ban|1.0.18
vscode-wasm|dts|1.2.1
graphviz-preview|EFa|1.3.3
open-current-file-in-new-window|ell|1.0.0
magic-racket|evz|0.3.3
center-editor-window|kai|2.1.1
auto-dark-mode|Lin|0.1.5
AWK|lug|0.0.2
rainbow-csv|mec|1.2.0
vscode-docker|ms-|0.7.0
cpptools|ms-|0.24.1
rust|rus|0.6.1
vscode-scheme|sjh|0.4.0
dot|Ste|0.0.1
propertylist|zho|0.0.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

Also, can you try setting `"editor.suggestSelection": "first"` to see if that fixes the suggestion ordering?

**Comment by mjbvz** [comment]
Also duplicate of #77370

**Comment by sstephenson** [comment]
I’m really sorry about this—I did have `editor.suggest.filteredTypes` set to `keyword`. I definitely didn’t _intentionally_ set it, though, and there doesn’t appear to be a visual editor in the settings UI for it, so I’m not sure how it happened.
