### ISSUE TITLE
HTML autocomplete lowercase is messing with text color

### ISSUE THREAD

**Issue by Ares9323** [microsoft/vscode#77889]
**VSCode Screenshot with all extensions disabled**

<img src="https://image.prntscr.com/image/Kty4jrtUTui2vFExen5Ayg.jpeg" alt="Screenshot" style="float: left; margin-right: 10px;" />
<img src="https://image.prntscr.com/image/CrsxEABhR-KzKNW1jNHfDg.jpeg" alt="Screenshot" style="float: left; margin-right: 10px;" />

**Steps to Reproduce:**

1. Type anything inside a div like onClick, onMouseOver, etc.
2. If you use the autocomplete function everything will be written in lowercase causing the system not to recognize the function and applying a different color

If the correct form is lowercase i will use it, but in some documentations is written with uppercase letters

**System Info**
- VSCode Version: 1.37.0 Insider (Latest)
- OS Version: Windows 10 Pro Build 1903 (Latest)
- Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
I don't know if there's a recommendation but we follow how mdn does it: all-lowercase
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers

Moving issue to the HTML textmate grammar to answer why the tokens are different.
https://github.com/textmate/html.tmbundle/issues/104
