### ISSUE TITLE
Git: show staged changes even if there are none

### ISSUE THREAD

**Issue by awmottaz** [microsoft/vscode#77888]
Currently, the Git SCM panel will show "Changes: 0" if there are no changed files in the project:

![Screenshot from 2019-07-24 15-47-10](https://user-images.githubusercontent.com/17735385/61827557-723d7300-ae2a-11e9-970d-2237a3194f5b.png)

I would like to see a similar heading "Staged Changes: 0" if no changes have been staged yet. This would be a good reminder for me to stage changes before committing them instead of enabling auto-staging when trying to commit without any staged changes.

**Comment by joaomoreno** [comment]
The setting ID is `git.alwaysShowStagedChangesResourceGroup`
