### ISSUE TITLE
Request: VS Code Help>About text should be selectable or auto-copy to clipboard useful info for filing an issue.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#7788]
- VSCode Version: 1.2.1
- OS Version: 10586.318

Steps to Reproduce:

1. Want to file a bug.
2. Click on the "Report Issues" link.
3. Realize I need to open `winver` to get the OS version, and VS Code Help>About to get the VS Code version -- and this dialog does not have selectable text so I need to transcribe the info, and I end up only transcribing the Version 1.2.1 because everything else is too difficult.

Request: VS Code Help>About text should be selectable or auto-copy to clipboard useful info for filing an issue.

Bonus: Also detect the OS version number and build string so that info can be copied into a bug as well.

This would make opening issues with the most useful data way easier -- win-win for VS Code devs and for users filing bugs!

**Comment by Tyriar** [comment]
This is OS specific, I know WIndows you can't but Linux you can select the text. Related: https://github.com/Microsoft/vscode/issues/3362

@dilijev also in v1.3.0 you will be able to use Help > Report Issues to automatically fill this info in for you :smiley:

**Comment by coreh** [comment]
On OS X it is selectable as well.

**Comment by sandy081** [comment]
@dilijev IMO Help > Report Issues functionality will definitely overcome this problem. I am closing this issue in favor of using this new functionality. 

Please use #3362 for any suggestions on help dialog.

Thanks

**Comment by dilijev** [comment]
@sandy081 Thanks, that's definitely an improvement. Although the value populated for OS seems very non-specific. I end up still transcribing from winver.

**Comment by Tyriar** [comment]
@dilijev apparently it is [as easy as running `os.release()`](http://stackoverflow.com/a/14989382/1156119) to get this. I didn't realize, I'll add this now, thanks :smiley:

**Comment by dilijev** [comment]
@Tyriar Thanks! It now works the way I'd expect as of version Insiders 1.3.0-insider (06d108b4a0aa6c031e7c1e61a463c069809d6019
