### ISSUE TITLE
#68627 is occurring again

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/vscode#77895]
Issue Type: <b>Bug</b>

I'm seeing the same symptoms that were originally reported in #68627. I would just comment on that issue, but it's locked now. :smile:

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv|-psn_0_13073527|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
auto-rename-tag|for|0.1.0
change-case|wma|1.0.0

</details>

**Comment by isidorn** [comment]
Can you please provide reproducable steps?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If you F1 > developer tools > do you see some errors in the debug console

**Comment by isidorn** [comment]
Actually dup of https://github.com/microsoft/vscode/issues/77106
Please comment there

**Comment by NickHeiner** [comment]
Thanks. Sorry that I didn't have repro steps.
