### ISSUE TITLE
List content in markdown should not be styled

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7789]
![image](https://cloud.githubusercontent.com/assets/2193314/16129556/fd739e2a-33b9-11e6-85c4-ddd6d9b51b90.png)

The text after the `*` should be white and links should be styled as links.

Note that removing the markup scope from all elements fixes the issue, it does remove heading coloring though which is also important:

![image](https://cloud.githubusercontent.com/assets/2193314/16129691/a86c6c62-33ba-11e6-81d9-82d9590829dd.png)

**Comment by mjbvz** [comment]
The original problem seems to have been fixed:

![screen shot 2016-09-20 at 5 51 22 pm](https://cloud.githubusercontent.com/assets/12821956/18693972/e2fbbae0-7f5a-11e6-97b1-51d537181cb5.png)

However, we still don't consistently colorize the link elements within the list (note how the text for 'link' is red, but inside the list, the link text is white.) I've opened #12344 to track this.
