### ISSUE TITLE
vscode 1.36 crashes when opentext socks client is installed

### ISSUE THREAD

**Issue by sazeez** [microsoft/vscode#77897]
- VSCode Version: 1.36
- OS Version: Windows 10

Steps to Reproduce:

1. Install VSCode v1.36.0 (June 2019) User/System version
2. Install OpenText SOCKS client version 14.0. No need to enable socks profile.
3. Launch VSCode from either command line or Start Menu
4. Close VSCode
5. Launch VSCode again, the application fails to launch.
6. All open applications in Windows become unresponsive, Chrome, Firefox, windows explorer etc.. The only way out is rebooting the whole machine. 
7. Uninstall OpenText SOCK client, and VSCode starts to work again.

Installing prior version of VSCode v 1.34.0 doesn't have this issue. I am having to install v1.34 and disable auto-update to stay stable.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by sazeez** [comment]
Tried Windows [Exploration build win system](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe) and having the same issue. After closing vscode windows hangs. 

No issue with [vscode 1.35](https://update.code.visualstudio.com/1.35.1/win32-x64-user/stable) either, the issue starts with 1.36

**Comment by bpasero** [comment]
@sazeez can you try if just starting Electron itself fails already? https://github.com/atom/electron

**Comment by bpasero** [comment]
Also: Can you run from the command line `code --verbose` to see for error output.

**Comment by sazeez** [comment]
No issues with base Electron.

Attached are the verbose outputs from the exploration build and 1.35.1
[vscode-expl-verbose.log](https://github.com/microsoft/vscode/files/3478474/vscode-expl-verbose.log)
[vscode-1351-verbose.log](https://github.com/microsoft/vscode/files/3478476/vscode-1351-verbose.log)

Also noting that the issue only starts occurring after closing vscode, all ok while vscode is running.

**Comment by bpasero** [comment]
@sazeez the log of the first start seems ok, I wanted to see the log of the second start that fails.

**Comment by sazeez** [comment]
I don't see any log updates when vscode is launched again when it crashes, it seems the process is hung immediately after its closed. On further investigation I found this issue only occurs on company PC, its most definitely some admin policies interfering with vscode and socks client.

**Comment by sazeez** [comment]
Installing Windows 1903 May 2019 update seems to have fixed this issue.
