### ISSUE TITLE
Output channel content highlighting stops working after clearing its contents

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/vscode#77899]
Version: 1.37.0-insider
Commit: 36e08fed41272d1ff0d73d9b3a540b0a052ecef4
Date: 2019-07-24T19:56:39.504Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.0.0

Output channel output highlighting stops working after clearing its contents:

```js
const outputChannel = window.createOutputChannel('Quokka');
outputChannel.append('this will be highlighted');
...
outputChannel.clear();
outputChannel.append('this will not be highlighted');
```

If it is important, our extension is using a language + grammar to highlight the output:

```
  "contributes": {
    ...
    "languages": [
      {
        "id": "wallaby-output",
        "mimetypes": [
          "text/x-code-output"
        ]
      }
    ],
    "grammars": [
      {
        "language": "wallaby-output",
        "scopeName": "wallaby.output",
        "path": "./wallaby-output.tmLanguage"
      }
    ]
  },
```

Steps to Reproduce:

1. Install [Quokka extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode&ssr=false#overview).
2. Run `>Quokka New JavaScript File` command from Command Palette.
3. Observe output channel content highlighted.
4. Type anything in the created JS file.
5. Observe output channel losing highlighting.

![vid](https://user-images.githubusercontent.com/979966/61836612-55557e00-aec4-11e9-9219-1dc46477db9f.gif)

The same steps work as expected (with content highlighted) in the Version 1.36.1 (1.36.1).

There are some errors reported in Dev Tools that may be related:

<img width="1769" alt="Screen Shot 2019-07-25 at 1 54 33 pm" src="https://user-images.githubusercontent.com/979966/61844751-e12ad280-aee3-11e9-95f8-2fd7db6398a1.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Fixed via #77740
