### ISSUE TITLE
Using vscode unit tests environment on travis build system.

### ISSUE THREAD

**Issue by fforjan** [Microsoft/vscode#779]
I all, I'm currently playing with VSC extensions and create a very simple one in typescript as learning experience about managing nuget packages for project.json - nuget4code, https://github.com/fforjan/nuget4code.

When learning, I'm always trying to do a full slice, including unit testing and build environment.
As I'm using GitHub, I've also link it to the Travis build system.
My npm test action  is currently configure compile only, so I can catch build error which could have been missed on my computer (more likely none ;))

I got some unit tests working on my computer, they are really unit tests, I don't trigger any UI actions or other things, but they are doing *import * as vscode from "vscode"*, use some vscode.Uri and thus require a vscode environment setup to run.

Do you have any idea how to configure Travis to be able to run unit tests ?

**Comment by alexandrudima** [comment]
I think I heard @dbaeumer and @bpasero discussing about how a Travis CI should look like for extensions.

**Comment by akamud** [comment]
:+1: same question

**Comment by bpasero** [comment]
Planned for next release and we make sure its documented!

**Comment by bpasero** [comment]
Documented here: https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines

**Comment by fforjan** [comment]
Already used pre3 last week and it's working fine ;) 
(i.e. the documentation was online before the package being finally release, this is why I've used pre3...)

**Comment by bpasero** [comment]
Great :)
