### ISSUE TITLE
Editor width changes when toggling sidebar, breaking auto-expand of focused editor functionality.

### ISSUE THREAD

**Issue by Imisnew2** [microsoft/vscode#77901]
- VSCode Version:
```
Version: 1.37.0-insider
Commit: 36e08fed41272d1ff0d73d9b3a540b0a052ecef4
Date: 2019-07-24T19:56:39.504Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0
```
- OS Version:
```
$ uname -v
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64
```

Steps to Reproduce:

![VSCode Editor Resizing](https://user-images.githubusercontent.com/1633556/60932707-32d73880-a2fa-11e9-9f8d-777df1830e43.gif)

1. Open VS Code and close all editors.
2. Close/Hide the sidebar.
3. Create two side-by-side editor panes.
4. Resize the editor panes so that one is as small as it can be / the other is as big as it can be.
4a. Sanity-check that when you enter focus in an editor pane that it auto-maximizes the pane.
5. Open/Reveal the sidebar.
6. Focus on an editor pane that is not currently in focus. It will auto-maximize the pane. This step is required to cause the bug in step 8 to manifest.
7. Close/Hide the sidebar.
8. Focus on an editor pane that is not currently in focus; it does not auto-maximize anymore, as the editor panes are no longer the minimum/maximum relative size.

Does this issue occur when all extensions are disabled?: Yes

This is basically a clone of #77034, as it was closed as a duplicate without any rationale. I've searched but I cannot find a duplicate of this issue. Yes, there are *similar* issues, such as #51614 and its many duplicates, but nothing currently tracking *this particular issue* as far as I can tell.

**Comment by bpasero** [comment]
@Imisnew2 do you still see this when you configure `"workbench.useExperimentalGridLayout": true`

**Comment by Imisnew2** [comment]
@bpasero Unfortunately, reproduces even with `"workbench.useExperimentalGridLayout": true`. Just to make certain, I downloaded the latest code-insiders update and tried again; it still reproduces.

1.37.0-insider
5e08ee01b7daee99cdda2456f19d77e715fb8762
