### ISSUE TITLE
[Suggestion] Add option for longest-common-prefix based double tab completion

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/vscode#77907]
This is a feature that most Unix shells supports, what it does it basically allows you to press TAB to get a list of suggestions then press tab again to insert just the maximal prefix of the options seen.

For example this is a typical flow:

<details>
<summary>Typical flow</summary>

Given this list of auto suggestions:

```
one
two
two-bar
three-baz
three-buz
```

A flow in the double-tab longest common prefix scheme could would look like:

<kbd>t</kbd>

```
t
```

On pressing tab once a list of options is shown but the input is not changed.

<kbd>TAB</kbd>

```
t
  - two
  - two-bar
  - three-baz
  - three-buz
```

<kbd>h</kbd>

```
th
```

<kbd>TAB</kbd>

```
th
  - three-baz
  - three-qux
```

Because all entries have the same common prefix the second tab in a row will place the longest-common-prefix in.

<kbd>TAB</kbd>

```
three-
```

<kbd>TAB</kbd>

```
three-
  - three-baz
  - three-qux
```

<kbd>q</kbd>

```
three-q
```

Only a single match left so it's auto completed now.

<kbd>TAB</kbd>

```
three-qux
```

</details>

In ZSH this can be configured through two independent settings:
  - `nomenucomplete` which disables <kbd>TAB</kbd> from automatically inserting the first item.
  -  `noautocomplete` which disables autocomplete on the first tab press if there's multiple options and just displays the list of options instead

Whether or not adding both options makes sense in VSCode I'm not sure, but it'd be quite nice to be able to use the same tab-completion flow in both VSCode and in shells.

**Comment by Tyriar** [comment]
This is normally a shell-level feature, does it not work when you configure the terminal to use zsh?

```
"terminal.integrated.shell.linux": "/bin/zsh"
```

**Comment by Jamesernator** [comment]
I don’t mean I want the feature in the integrated terminal, that works already.

I am suggesting adding the behaviour to suggestions in the edtor.

**Comment by Jamesernator** [comment]
What issue is this a duplicate of? I couldn't find one and I would like to track it.
