### ISSUE TITLE
When debugging an extension, closing the extension dev host exception-breaks with EPIPE

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#77909]
Issue Type: <b>Bug</b>

I maintain a VS Code extension. Recently I have started to experience the following behaviour:

* I run the extension under the debugger and the Extension Development Host runs.  I activate my extension.
* I close the Extension Development Host.
* VS Code triggers a debug break in an internal VS Code function called `afterWriteDispatched`.  It displays an exception popup and the code location where the exception occurred.  The error is `write EPIPE`.  None of my code appears to be on the stack at this time.
* After a few seconds, the debug toolbar and exception popup disappear.  The internal file remains open.

Although this seems harmless, it's a bit annoying, and it does make me anxious that there's something I'm doing wrong.  This never used to happen but I'm not sure whether it started due to changes in my extension or changes in VS Code; it now happens more often than not.  Other extensions I maintain do not seem to be hitting this problem so I can well believe it's an extension problem but the error message doesn't give me any clue where to look!

The operating system is Windows and the extension source code is at https://github.com/Azure/vscode-kubernetes-tools/

Here's a screenshot of the error (sorry, it doesn't stay around long enough for me to copy as text):

![image](https://user-images.githubusercontent.com/865538/61844991-99ad4200-aef5-11e9-974a-abe455316ddd.png)

And a screenshot with the full file path:

![image](https://user-images.githubusercontent.com/865538/61845043-c82b1d00-aef5-11e9-92ac-e2363d5a0112.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18912

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (33.24GB free)|
|Process Argv|--folder-uri file:///d%3A/GitHub/vscode-kubernetes-tools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
vscode-pull-request-github|Git|0.9.1
terraform|mau|1.3.12
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
Go|ms-|0.11.4
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
java|red|0.47.0
vscode-yaml|red|0.4.1

</details>

**Comment by weinand** [comment]
What breakpoint settings are you using?

![2019-07-25_10-34-58](https://user-images.githubusercontent.com/1898161/61859190-f2fe7c80-aec7-11e9-8da2-18cf47d79c4b.png)

**Comment by itowlson** [comment]
@weinand `Uncaught Exceptions` is ticked.  The other two are unticked.

**Comment by itowlson** [comment]
@weinand Kia ora, I see this was tagged as `needs more info`.  What more information do you need?  I'm working on webpacking my extension and this is now biting me every time, so it would be great to know if there is anything we can do about it.  Thanks!

**Comment by weinand** [comment]
This problem should be fixed in recent builds.
Please try latest Insiders.
