### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#77913]
Issue Type: <b>Bug</b>

The terminal pane isn't working. All I get is a blinking cursor. I've selected cmd as the default shell. Adding a new terminal doesn't help, nor does restarting/reloading vscode. This issue also happens with all extensions disabled. The real command prompt works fine.

![image](https://user-images.githubusercontent.com/152227/61854709-f4777700-aebe-11e9-8f0d-714328b972ef.png)

(The cursor looks like that probably just because the window was inactive while taking this capture)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (23.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.4.4
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
file-icons|fil|1.0.17
duplicate|gee|1.0.1
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|0.7.0
vscode-versionlens|pfl|0.24.0
vscode-template-literal-editor|pli|0.9.0
vscode-sort-json|ric|1.14.0
code-settings-sync|Sha|3.4.1
vscode-svg-previewer|vit|0.5.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json file and also try out the Insiders build as improvements have been made in this area recently https://code.visualstudio.com/insiders/

**Comment by thany** [comment]
Funny thing is I can't reproduce it anymore. I'm not aware that anything at all got updated in the mean time.

Literally the only difference is that now I also have an external monitor attached with power, and when I reported the bug, I hadn't and was on battery power. But in either case I'm using VScode on my laptop screen, so I don't think it should matter.

So I guess maybe freeze this issue for now.

**Comment by thany** [comment]
Just got it again. Apparently it wasn't dependent on my physical location, but on the repo that I opened.
Works better in the Insiders build, but it's not quite there yet:
![Capture](https://user-images.githubusercontent.com/152227/62297422-7cd2ba80-b471-11e9-8083-f8159da2b105.PNG)

Only when I hit Enter, I get a usable prompt 🤔

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
