### ISSUE TITLE
/usr/bin/code not linked when doing rpm upgrade

### ISSUE THREAD

**Issue by guoxiao** [Microsoft/vscode#7791]
- VSCode Version: 1.2.1
- OS Version: Fedora

## Steps to Reproduce:

1. Install an old version (for example 1.1) of code
2. run `dnf install https://az764295.vo.msecnd.net/stable/fe7f407b95b7f78405846188259504b34ef72761/vscode-x86_64.rpm`
3. `/usr/bin/code` is not created.

## Details
The problem is that /usr/bin/code is not a part of the rpm.
`/usr/bin/code` is created in postinstall script as:
```
# Symlink bin command to /usr/bin
sudo rm -f /usr/bin/code
sudo ln -s /usr/share/code/bin/code /usr/bin/code
```
In the `postuninstall` script, `/usr/bin/code` is removed.

In first installation of `code`, only `postinstall` script is executed. So it works well.
However, when doing an upgrade, `postinstall` and `postuninstall` script are both executed. So `/usr/bin/code` is removed.

## Possible solutions
* make `/usr/bin/code` as part of the rpm package. (my recommendation)

Or

* check the argument of `postinstall`. Only remove `/usr/bin/code` when the argument is 1.
( see explanations on `Install/Erase-time Scripts` part of http://www.rpm.org/max-rpm/s1-rpm-inside-scripts.html )

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/5840, fixed in v1.3.0 and current insiders build.
