### ISSUE TITLE
Package.json error on workspaces object

### ISSUE THREAD

**Issue by zifahm** [microsoft/vscode#77912]
- VSCode Version: 1.36.1
- OS Version: Linux64 4.15.0-55-generic

Steps to Reproduce:

1. add in "workspaces":{"nohoist":["somepackage"] } in package.json
![croppedpackagejsonerror](https://user-images.githubusercontent.com/3761062/61854123-10891180-aedb-11e9-98bd-c25c13c45c1b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
As the error message said, `workspaces` needs to be an array while you write an object, is this expected?

**Comment by fabricioferreira** [comment]
According to a [post](https://yarnpkg.com/blog/2018/02/15/nohoist/) on yarn blog, the new workspaces configuration format should be as below:

`// flow type definition:
export type WorkspacesConfig = {
  packages?: Array<string>,
  nohoist?: Array<string>,
};`

**Comment by rebornix** [comment]
@fabricioferreira thanks, then we should update it.

**Comment by zifahm** [comment]
Yup workspaces takes an array as well as an object as well.

**Comment by aeschli** [comment]
The `package.json` schema is loaded from http://schemastore.org/json/
Please file a bug (or even PR) at https://github.com/schemastore/schemastore/issues

**Comment by zifahm** [comment]
Thanks will PR and file an issue as well

**Comment by zifahm** [comment]
filed a PR https://github.com/SchemaStore/schemastore/pull/756

**Comment by aeschli** [comment]
Thanks!
