### ISSUE TITLE
Language support for Javascript/Typescript

### ISSUE THREAD

**Issue by joguarino** [microsoft/vscode#77917]
Issue Type: <b>Bug</b>

Everytime I open a JS or TS file in VSCode, I always have this error:

"
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
_onExtensionHostCrashed	@	abstractExtensionService.ts:155
"

The result is that all the functionalities regarding JS/TS aren't working, such as, for example, the structure of the script, or the intellisense, neither the add-ons (for example, "Bracket Pair Colorizer", which is the signal the file was not properly recognized).

Sometimes the problem disappears simply restarting the extention host, as notified by VSCode, but often it isn't enough, and I have to restart VSCode.

A few times it happened that the problem came out more and more even during the work, not only at the first opening of the file, but it has been too rare to be considered recurrent.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.29GB free)|
|Process Argv|C:\Users\g.guarino\source\repos\Node\filemanager|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.4.4
angular-schule-extension-pack|ang|0.4.6
ng-template|Ang|0.801.1
angulardoc-vscode|Ang|6.1.3
swagger-viewer|Arj|2.2.2
vscode-intelephense-client|bme|1.1.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
vscode-nupkg|eri|1.0.1
php-intellisense|fel|2.3.10
cshtml|fir|0.1.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|2.1.32
vscode-firefox-debug|hbe|1.8.0
minify|Hoo|0.4.3
XMLLanguageSupport|IBM|0.0.1
mysql-syntax|jak|1.3.1
latex-workshop|Jam|7.2.0
plantuml|jeb|2.11.2
Angular1|joh|0.2.1
vscode-peacock|joh|2.5.0
classic-asp-html|jtj|0.1.1
chat|kar|0.15.5
angular1-code-snippets-johnpapastyle|lpe|0.1.0
openapi-lint|mer|1.0.3
vscode-remote-workspace|mkl|0.42.0
binary-viewer|mom|0.0.1
vscode-docker|ms-|0.7.0
vscode-language-pack-it|MS-|1.37.0
mssql|ms-|1.6.0
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.581
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.2
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.6
debugger-for-edge|msj|1.0.10
reload|nat|0.0.6
angular-console|nrw|8.0.10
vscode-auto-scroll|pej|1.0.3
material-icon-theme|PKi|3.8.1
java|red|0.47.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.4.1
gitconfig|sid|2.0.0
html-preview-vscode|tht|0.2.5
msbuild-project-tools|tin|0.2.55
highlight-matching-tag|vin|0.9.3
vscodeintellicode|Vis|1.1.8
vscode-icons|vsc|8.8.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
