### ISSUE TITLE
pytest tests are not properly displayed if test name contains upper letters

### ISSUE THREAD

**Issue by Galileo-Galilei** [microsoft/vscode#77916]
Hello, 

I've encountered a little bug recently in the "Tests" tab. I am not 100% sure that the bug is related to vscode or to the python extension. 

**_Environment:_**
- VSCode Version: 1.34.0
- OS Version: Windows_NT x64 6.1.7601
- Python extension version : 2019.6.24221
-  settings.json : 
```
{
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true
}

```
**_Bug :_**
When a test file contains an upper letter, it is not displayed properly in the test tab. After running if passed or failed, it is displayed with a "grey question mark".

Steps to Reproduce:

1. Create an empty project (note : use a conda environment where pytest is installed)
2. Create a "tests" folder
2.1 Create a ```test_working.py``` file
```
 import pytest

def test_this_one_works():
    assert 1==1
```
2.2 Create a ```test_NotWorking.py``` file with the same code
```
 import pytest

def test_this_one_works():
    assert 1==1
```

3. In the ```Test``` tab of vscode, run ```Discover Tests```
If everything ran properly, you should see the following architecture : 
-(?) tests
    - (?) test_notworking.py **(with lower case!!!)**
        - (?) test_this_one_does_not_work
    -  (?) test_working.py
         - (?) test_this_one_works

4. In the ```Test``` tab of vscode, run ```Run All Tests```.
Now I have :
-(green tick ok) tests
    - (?) test_notworking.py **<- BUG  - EXPECTED BEHAVIOUR : should have a green tick and have name in upper case**
        - (?) test_this_one_does_not_work **<- BUG - EXPECTED BEHAVIOUR : should have a green tick and have name in upper case**
    - (green tick ok) test_working.py (with lower case!!!)
        - (green tick ok) test_this_one_works

**_Remarks_** : 
- the tests seem to be ran whatever is displayed (the bug only concerns the user interface) : indeed in the bottom line (where my python version and my environment are shown), I see an icon "two tests passed".
- when i run ```pytest tests``` in the command line, everything is fine. 

**_Conclusion_** : 
This bugs is not critical at all since it only concerns te UI, but in my old projects I can't see the tests in the UI (while it used to work perfectly fine few weeks ago). I definitely do not want to change the names of the scripts (the tests scripts are a mirror of the scripts names of my project). 

Any hope this would be easy to fix?

Many thanks for reading and any further help !
Galileo

**Comment by weinand** [comment]
Please provide a screenshot that shows the problem.

**Comment by Galileo-Galilei** [comment]
Hello @weinand, 

many thanks for the fast answer. You can see two red boxes in pictures below : at the bottom of my IDE, two tests are marked as passed, but there is no green tick near the "test_NotWorking.py", and its name has been converted into lower case.

![example_img](https://user-images.githubusercontent.com/29451317/61859707-ee869380-aec8-11e9-9f60-76dc1aaa7ed5.png)

I'm at your disposal to provide as many additional information as needed.

**Comment by weinand** [comment]
This is an issue with the test extension you are using. Please file the issue in their repository.
