### ISSUE TITLE
Integrated terminal breaks with Powershell

### ISSUE THREAD

**Issue by byt3pool** [microsoft/vscode#77910]
Issue Type: <b>Bug</b>

Since I updated Windows 10 to version 1809 I discover following behaviour when opening the integrated terminal (PowerShell):

**Opening terminal**
![vscode_start](https://user-images.githubusercontent.com/966427/61847515-3e566200-aeab-11e9-92cf-4dadf1b68ffd.PNG)

**Typing/execute command**
![vscode_typing](https://user-images.githubusercontent.com/966427/61847533-50380500-aeab-11e9-8349-6574182bda10.PNG)

As said before it all started after installing Windows 10 1809-Update. At this time I had a bunch of extensions (mostly listed below) such as [Shell launcher](https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher) and a PS1 script for my PowerShell-profile which sets a few aliases and defines some functions. All worked as expected. Unfortunately after the update things with the integrated powershell terminal got worse (see screenshots above).

I already reinstalled VSCode completely anew (even deleted every cached settings-folder etc.) without said Shell launcher extension and removed the PS1 script but I still get a huge whitespace when opening the terminal and the pink background as soon as I start typing.

----

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.1
clipboard-history|Anj|1.0.7
swagger-viewer|Arj|2.2.2
erb|Cra|0.0.1
FreeMarker|dco|0.0.9
fileheadercomment|doi|0.0.3
plantuml|jeb|2.11.2
vscode-docker|ms-|0.7.0
remote-wsl|ms-|0.38.10
java|red|0.47.0
vscode-xml|red|0.8.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
