### ISSUE TITLE
VS Code restarts indefinitely after failed to open a big file

### ISSUE THREAD

**Issue by Iamzz-cn** [microsoft/vscode#77919]
I tried opening a big text file, about 14 GB. I had modified the setting of VS Code max-memory=40960.(The memory of my system is 16 GB). I successfully opened the file, but when I modified it and tried saving it, VS Code didn't give any prompt. After a period of time, I closed VS Code. After that, whatever I open by VS Code, VS Code will crash.

**Comment by rebornix** [comment]
As the file opening is fine, assign to @bpasero first as it might be related to file saving or hot reload.

**Comment by bpasero** [comment]
@Iamzz-cn did you recover meanwhile?
