### ISSUE TITLE
Conditionally reachable code is not properly type-checked

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#77921]
Issue Type: <b>Bug</b>

Given the following JS code:

```js
/** @param {Element} target */
yay( target ) {
	if( target instanceof HTMLElement ) {
		target.style.width = "0px";
	}
}

/** @param {Element} target */
nay( target ) {
	if( target instanceof HTMLElement === false ) {
		return;
	}
	target.style.width = "0px";
}
```

In `nay`, VS Code will complain that `style` does not exist on `Element`, while it correctly understands the situation in `yay` and does not complain.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (34.74GB free)|
|Process Argv|core-data-access/core-data-access.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal-formatter|ale|2.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
generateuuid|Fir|0.0.5
shell-format|fox|6.0.1
vscode-mocha-test-adapter|hbe|2.1.2
vscode-test-explorer|hbe|2.14.0
JSDocTagComplete|Hoo|0.0.2
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
terraform|mau|1.3.12
code-beautifier|mic|2.2.1
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
vscode-paste-image|mus|1.0.4
syncing|non|3.0.5
vscode-yaml|red|0.4.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/32819 to track upstream
