### ISSUE TITLE
Workbench grid: panel renders according to wrong position

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#77922]
1. Disable workbench grid
2. Place sidebar on the left and panel on the right
3. Enable workbench grid

Notice:

- The panel will appear in the bottom
- The panel will be rendered as if it is on the side: there will be a 1px border on the left side and nothing on the top

**Comment by joaomoreno** [comment]
Easier steps:

1. Open a New Window
2. Move panel to the right
3. Close window
4. Open a New Window
5. Toggle show panel

Panel will be on the right but rendered as if its on the bottom.

We gotta remove the legacy sources of truth for view locations.

**Comment by sbatten** [comment]
@joaomoreno this source of truth should already be fixed and I cannot repro. Can you still in latest?

**Comment by SSJ9899TDylan** [comment]
Who knows!
Sent by Dylan Taylor

**Comment by joaomoreno** [comment]
Nope, the last steps still reproduce.

**Comment by joaomoreno** [comment]
Things like these should not exist in the grid world:

- https://github.com/microsoft/vscode/blob/f515c229c98f8362adc88f67138afb5367f8a25c/src/vs/workbench/browser/layout.ts#L147-L148
- https://github.com/microsoft/vscode/blob/f515c229c98f8362adc88f67138afb5367f8a25c/src/vs/workbench/browser/layout.ts#L132

They should all come from the Grid serialization.

**Comment by sbatten** [comment]
@joaomoreno right now panel position is a workspace specific item while the grid is global, we need to throw out the grids POV if it doesn't work with what's stored. Now I am doing that with the last commit but ideally I'd be able to move the panel and sidebar into the right place before layout. Is that possible?

**Comment by joaomoreno** [comment]
Ohh I hadn't realised that. Sucks. Well, you have to restore the grid and then run through the `Move Panel to the Right` action inner workings.

**Comment by sbatten** [comment]
Verification Steps:
1. Set `restoreWindows` to `none`
2. Follow @joaomoreno steps
