### ISSUE TITLE
Annoying GitHub commit

### ISSUE THREAD

**Issue by yogesh-aggarwal** [microsoft/vscode#77927]
- VSCode Version: 1.36.1
- OS Version: Linux (Ubuntu 19.04)

**Steps to Reproduce:**

1. Make your default code editor (commit editor) of git to "code".
2. Turn ON autosave on vscode.
3) Try to commit, it will autosave that file and blank commit get passed.

**In my opinion, it should ignore the "COMMIT_EDITMSG" file.**

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@yogesh-aggarwal I am using this setup all the time and see no issues, even with auto save enabled. The commit should only happen when you close the editor. Could it be some mis-configuration on your end given this is the first time I hear about it?

//cc @joaomoreno

**Comment by yogesh-aggarwal** [comment]
> @yogesh-aggarwal I am using this setup all the time and see no issues, even with auto save enabled. The commit should only happen when you close the editor. Could it be some mis-configuration on your end given this is the first time I hear about it?
> 
> //cc @joaomoreno

Yes you are right, on windows, I also have no problems but on Ubunutu 19.04 LTS it has appeared the first time annoying. Are you on Linux (Ubuntu).
