### ISSUE TITLE
Underline of hyperlinks in editor randomly flashes on and off

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#77928]
This happens really intermittently, but I've seen it many times over the last month or so. Sometimes I open a file, and I see hyperlinks in comments where the underline is flashing on and off. It "randomly" stops on its own too.

(my recording is bad because I converted it to GIF - it's flashing about twice the rate seen here.. slightly slower than the cursor/caret flash - though definitely not in sync with it).

![Untitled](https://user-images.githubusercontent.com/1078012/61873154-239ce100-aedd-11e9-87ab-9bb27e5ef85d.gif)

Is there anything I can do to capture more information when it happens?

(I don't have any extensions besides my own and MS-created ones, I'm certain this is not caused by any extension).

**Comment by rebornix** [comment]
Could you please help confirm if it's a dup #48321  of by following steps in https://github.com/microsoft/vscode/issues/48321#issuecomment-383602537 ?

**Comment by DanTup** [comment]
I'm OOO for a bit now, but I'll have a go when I'm back.

**Comment by DanTup** [comment]
Sorry for the delay - I haven't seen this recently, but I'll try to do some more debugging if I do see it again.

**Comment by alexandrudima** [comment]
Let's track in #76642
