### ISSUE TITLE
Typing "string;" sometimes inserts "strings;"

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#77926]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.37.0-insider (36e08fed41272d1ff0d73d9b3a540b0a052ecef4, 2019-07-24T19:58:35.647Z)
OS version: Windows_NT ia32 10.0.17763

- type `string;` very quickly. (ask @octref to type if you cannot repro :) )
- embrace the rage of seeing `strings;` typed

![intellisense](https://user-images.githubusercontent.com/5047891/61869379-c7858d00-aedb-11e9-8017-4dfc1989a443.gif)

If you type `string;` slowly, then this does not reproduce... :/

fyi @jrieken

**Comment by jrieken** [comment]
It's the design behaviour because `strings` is the top match and since `editor.acceptSuggestionOnCommitCharacter` is set to `true` by default. I think the discussion should be if this is a good default

<img width="1428" alt="Screenshot 2019-07-25 at 13 00 19" src="https://user-images.githubusercontent.com/1794099/61869551-2b0fba80-aedc-11e9-945d-21e0ee9394c4.png">

**Comment by alexandrudima** [comment]
Kind of fishy is that `string` does not appear in that list...

**Comment by YoniChechik** [comment]
> It's the design behaviour because `strings` is the top match and since `editor.acceptSuggestionOnCommitCharacter` is set to `true` by default. I think the discussion should be if this is a good default
> 
> <img alt="Screenshot 2019-07-25 at 13 00 19" width="1428" src="https://user-images.githubusercontent.com/1794099/61869551-2b0fba80-aedc-11e9-945d-21e0ee9394c4.png">

In my opinion it's a **bad** default! happens as well in python when typing:
`import numpy as np`
and the result is annoyingly:
`import numpy as numpy`

**Comment by mjbvz** [comment]
@octref @alexandrudima Can you please share which project/file you are working in (and what TS version you have enabled). I can't repo

**Comment by alexandrudima** [comment]
@mjbvz As I mentioned, reproducing has to do with typing speed, you need to be very fast. The gif is from self-host in VS Code and the status bar shows TypeScript 3.5.2  -- https://github.com/microsoft/vscode/blob/6157007341589c334ce771cbbe453c18142c7bce/src/vs/editor/common/controller/cursorTypeOperations.ts#L942

At the time I recorded the gif it reproduced 50% of the time. I have been working in VS Code at that time for > 5 hrs without killing the TS server. I have found it easier to reproduce if TS is "stressed" with errors... This somehow makes it easier for me to reproduce even with a fresh self-hosting environemnt e.g.
![image](https://user-images.githubusercontent.com/5047891/61907499-e6ad0a80-af2d-11e9-9023-364f62cf9d19.png)

---

@jrieken After a lot of attempts, now it reproduces 20% of the time even if I type the accepting character ; slowly and only after a **flash** is observable in the suggest list. I am not pressing arrow down nor moving the mouse or anything like that, `string` is typed in the editor, `string` is selected in the suggest list, yet `strings` is inserted (the second choice) when I press `;`... Notice the weird flicker in rendering over `strings`. Only when the flicker appears does the insertion go bad:

![wth](https://user-images.githubusercontent.com/5047891/61908610-59b78080-af30-11e9-9702-2d0544d6620e.gif)

**Comment by jrieken** [comment]
Debugged this with @alexandrudima and it turns out that the suggest widget isn't always cancelling details requests and subsequently splicing the wrong elements, e.g. `strings` occurs as suggestion 1 and 2. That causes flicker but doesn't explain the commit character behaviour...

**Comment by jrieken** [comment]
@alexandrudima please report back if this still happen for you
