### ISSUE TITLE
go to file not ignore gitignore configuration

### ISSUE THREAD

**Issue by qljiong** [microsoft/vscode#77920]
Issue Type: <b>Bug</b>

go to file that does not ignore gitignore Configuration 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
insertnumbers|Asu|0.9.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
sql-formatter|cym|1.0.2
todo-tree|Gru|0.0.139
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.37.0
csharp|ms-|1.21.0
vs-keybindings|ms-|0.2.0
code-settings-sync|Sha|3.4.1
vscodeintellicode|Vis|1.1.8
join-lines|wma|0.2.2

</details>

**Comment by roblourens** [comment]
I need more details
