### ISSUE TITLE
Add config for split editor pane's initial state as empty

### ISSUE THREAD

**Issue by eriknelson** [microsoft/vscode#77929]
This was closed as a duplicate, but the linked issue is not exactly the feature that the OP had requested: https://github.com/Microsoft/vscode/issues/30168

The above issue allows for keeping editor groups open when empty, but the requested feature was that the **initial state in a new pane should be empty**. This is the default behavior in vim. I'm not suggesting this should be the default behavior, but a configurable option would be greatly appreciated; the current behavior is hugely annoying.

Is this already possible, or is there some kind of workaround that can be done to achieve it?

**Comment by bpasero** [comment]
@eriknelson what about this command:

![image](https://user-images.githubusercontent.com/900690/62458779-1524b400-b77e-11e9-8fb4-fd0d83d5b3bb.png)


?
