### ISSUE TITLE
Microsoft keyboard macros ignored in VS Code only

### ISSUE THREAD

**Issue by hulapluto** [microsoft/vscode#77939]
- VSCode Version: 1.31.1 (work-locked to this version)
- OS Version: Windows 10

Steps to Reproduce:

1. Launch vs code
2. Try to use a keyboard macro.
3. Fail. Very Frustrate. Search Web. Very more Frustrate. nada nada nada.

Using microsoft natural ergonomic keyboard 4000 and Intellitype macros to remap the home, search, email buttons to ctrl+c, ctrl+v, ctrl+a, respectively. Vs code is now ignoring these and just launching the default mappings. They work in every other program.

Tried deleting and remapping the macros, no change.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hulapluto** [comment]
I should add if I try to add the home, search or email buttons in the keybindings json file vs code just comes back with "unknown"

**Comment by rebornix** [comment]
@hulapluto does it work properly in Chrome? Can you please share the result when pressing those keys in the input box in https://w3c.github.io/uievents/tools/key-event-viewer.html ?

**Comment by hulapluto** [comment]
![vscodeCTRLc](https://user-images.githubusercontent.com/39414674/62049944-edf64180-b1d5-11e9-9cd7-91c796b199f1.JPG)
![vscodeCTRLv](https://user-images.githubusercontent.com/39414674/62049945-edf64180-b1d5-11e9-85ed-e0bedbdd74d9.JPG)

Yes, it works properly in all programs except for vscode. Thank you!

**Comment by rebornix** [comment]
@hulapluto you can try setting `"keyboard.dispatch": "keyCode"` to workaround this issue.

**Comment by hulapluto** [comment]
Could you elaborate on this? I am not sure where I am supposed to set this... I tried to search on your answer but I am not using linux.

**Comment by hulapluto** [comment]
I did try adding to the settings.json file, restarted, but no change. 

The key bindings field showed this: 
code: , keyCode: 172, key: BrowserHome => UI: unknown, user settings: unknown, dispatch: null

**Comment by RLHSI** [comment]
I can second this not working and I can try things if anyone wants me to.

I currently have the browser back/forward buttons below the spacebar on my Microsoft Ergonomic Keyboard 4000 set to media prev/next, and it works in every application but VSCode.  Nothing shows up in the W3 Key Event Viewer because they aren't truly input keys, they're just macro buttons that you can program to do whatever you want.

`"keyboard.dispatch": "keyCode"` isn't a valid setting in the `settings.json` file.

**Comment by RLHSI** [comment]
Update:

These buttons macros DO work when I'm not running VSCode as Administrator in Windows.  @hulapluto are you running VSCode as Administrator?
