### ISSUE TITLE
Settings scroll up or down

### ISSUE THREAD

**Issue by marcel0liveira** [microsoft/vscode#77931]
Hi, I'm a developer of new technologies, I'm using to learn node.js, 
and when navigating settings, I'm having difficulty scrolling down and up
scroll bar, not the mouse wheel, path (File > Preferences> Settings) or 
("Ctrl" + ",") any menu, if I pull the scroll it goes too far down or up too much, 
it is difficult to navigate without using the mouse wheel.
My theme is the dark, if help
Thank you.

**Comment by roblourens** [comment]
Yes, tracking this in https://github.com/microsoft/vscode/issues/66237
