### ISSUE TITLE
file remove, but still report error on this file

### ISSUE THREAD

**Issue by goldpicker** [microsoft/vscode#77930]
Issue Type: Bug

when I delete file from file explorer. except I reboot the vscode, It's still report proplems with these deleted files.

VS Code version: Code 1.36.0 (0f3794b, 2019-07-03T13:09:31.507Z)
OS version: Darwin x64 17.6.0
Remote OS version: Linux x64 4.15.0-51-generic

System Info
Item	Value
CPUs	Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: enabled
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	3, 3, 3
Memory (System)	16.00GB (0.32GB free)
Process Argv	-psn_0_3781531
Screen Reader	no
VM	0%
Item	Value
Remote	SSH: RemoteDevelopWithForward
OS	Linux x64 4.15.0-51-generic
CPUs	Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 1596)
Memory (System)	15.56GB (3.07GB free)
VM	0%
Extensions (34)
Extension	Author (truncated)	Version
vscode-tomcat	ada	0.11.1
vscode-eclipse-keybindings	alp	0.10.0
code-gnu-global	aus	0.2.2
sftp-sync	blo	0.0.3
jira-issues	crh	1.1.0
FreeMarker	dco	0.0.9
xml	Dot	2.5.0
auto-close-tag	for	0.5.6
vscode-lombok	Gab	0.9.8
mysql-syntax	jak	1.3.1
plantuml	jeb	2.11.1
docthis	joe	0.7.1
sftp	lix	1.12.7
vscode-JS-CSS-HTML-formatter	lon	0.2.3
remote-containers	ms-	0.66.0
remote-ssh	ms-	0.44.0
remote-ssh-edit	ms-	0.44.0
remote-ssh-explorer	ms-	0.44.0
remote-wsl	ms-	0.38.7
vscode-remote-extensionpack	ms-	0.15.0
cpptools	ms-	0.24.0
csharp	ms-	1.20.0
java	red	0.46.0
vscode-xml	red	0.7.0
LiveServer	rit	5.6.1
sass-indented	rob	1.5.1
vscode-jetty	Sum	0.1.11
vscodeintellicode	Vis	1.1.7
vscode-java-debug	vsc	0.20.0
vscode-java-dependency	vsc	0.5.1
vscode-java-pack	vsc	0.7.1
vscode-java-test	vsc	0.18.1
vscode-maven	vsc	0.17.1
html-css-class-completion	Zig	1.19.0

![Screen Shot 2019-07-25 at 8 10 54 PM](https://user-images.githubusercontent.com/2731456/61873826-73999900-af19-11e9-8466-968f440c5090.png)

**Comment by sandy081** [comment]
Please file issue against the extension generating these errors
