### ISSUE TITLE
Python Extension remote jupyter fails behind corporate proxy: "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by cslovell** [microsoft/vscode#77934]
Windows 10 enterprise edition. On an ordinary network connection, connecting to remote jupyter notebook server works perfectly. 

However, a particular corporate network connection uses Cisco's web security appliance to inspect traffic, providing a corporate certificate that is signed by an un-trusted authority (the corporate entity). This has been added to the system's trusted root certificate authorities by the system administrator. 

When I connect to this network, generally things work. However I cannot connect to the remote jupyter notebook and it throws the following error:

```
Executing code failed : Error: Failed to connect to remote Jupyter notebook.
Check that the Jupyter Server URI setting has a valid running server specified.
https://jupyter.example.com/user/example/
TypeError: request to https://jupyter.example.com/user/example/api/contents/?123456 failed, reason: unable to get local issuer certificate

Source: Python (extension)
```

I believe this has to do with the python extension not using the system's trusted root certificate authorities but I'm not sure. Any ideas for a work around?

**Comment by DonJayamanne** [comment]
@chrmarti Please fee free to move this to the Python Extension repo. https://github.com/microsoft/vscode-python

**Comment by chrmarti** [comment]
Can't move it for some reason. Is this a connection from a CLI or through Node.js in the extension?
