### ISSUE TITLE
Minus character not appearing

### ISSUE THREAD

**Issue by dmzobel** [microsoft/vscode#77932]
- VSCode Version: 1.36.1
- OS Version: 10.14.4

Steps to Reproduce:

1. Open a new file. As far as I can tell, the file type does not matter (I've tried with Plain Text, JSON, JavaScript, Python, and SQL files).
2. Try to type a `-` key. For me, nothing happens (i.e. no characters are produced), even when I'm trying to comment out SQL lines or subtract integers in JS or Python.
3. However, the `_` character works fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Could you please follow our wiki https://github.com/microsoft/vscode/wiki/Keybinding-Issues to help provide more info?

**Comment by dmzobel** [comment]
Figured this out, there was a weird keybinding attached to my `-` key. Thanks
