### ISSUE TITLE
Intellisense breaks if not suppying null for optional parameters

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#7793]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

**proto.js**
```js
module.exports = MyClass;

function MyClass() {
  this.prop = null;
}

/**
 * @param  {any} required
 * @param  {any} [notRequired]
 * @returns {MyClass}
 */
MyClass.prototype.optionalParam = function(required, notRequired) {
  this.prop = required;

  if (notRequired)
    this.prop += notRequired;

  return this;
};

MyClass.prototype.secondMethod = function(param) {
  return 'Hello';
};
```

**index.js**
```js
const proto = require('./proto');

let pInst = new proto();

//pInst.optionalParam('hello')
//pInst.optionalParam('hello', null)
```

Uncomment the second line and hit `.` after it. You'll get the proper Intellisense.

![properintelli](https://cloud.githubusercontent.com/assets/286972/16132534/892b1778-33e1-11e6-818f-49634b9bcf4b.PNG)

Uncomment the first line and hit `.`.

![badintelli](https://cloud.githubusercontent.com/assets/286972/16132549/95f32ebe-33e1-11e6-867b-faa119ec859e.PNG)

The Intellisense is broken if you don't supply something for the parameter, even though it is clearly recognized as optional.

![optional](https://cloud.githubusercontent.com/assets/286972/16132596/d53376b0-33e1-11e6-9132-a46693dbe6ce.PNG)

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#9228
