### ISSUE TITLE
Emmet Wrap Abbreviation Keeps Crashing

### ISSUE THREAD

**Issue by suit0r** [microsoft/vscode#77948]
After about 5 wrap abbreviation shortcuts, the command palette comes up but the command won't trigger.

**Comment by octref** [comment]
Please include exact steps for reproducing the problem.

**Comment by suit0r** [comment]
@octref i noticed this mostly happens with url strings

1. paste content from ms word
2. highlight the url string to wrap with `<a>` tags
3. sometimes the command palette doesn't accept input
3.1. enter a different element (like `div`) and it won't respond
4. sometimes the functionality returns (i think after using a different emmet command or autocomplete)
5. check dev tools, and and the native emmet extension shows high cpu usage
6. restart vscode
7. take an unnecessarily long break

**Comment by octref** [comment]
How large/long is your document?

**Comment by suit0r** [comment]
Really small. Thing is I am saving them as html snippets to paste into an LMS later, so the files are not fully structured documents (no head, body tags or doctype)

**Comment by octref** [comment]
![gif](https://user-images.githubusercontent.com/4033249/62076642-0af23b00-b1fd-11e9-98a4-3c1df8d8a7b7.gif)

I can't really repro. Anything you are doing different?

**Comment by suit0r** [comment]
It mostly broke when wrapping with a tags and adding attributes. 

I will try to record when I start working on these again, but is there a stack trace or something I can generate?

**Comment by octref** [comment]
Yes, if it crashed, you can give me everything you see in Help -> Toggle Developer Tools. Thanks!

**Comment by suit0r** [comment]
ok it crashed again.

some more details. there are multiple folders in the root, and a lot of the file names are duplicated per folder, so i got week1/t2.html, week2/t2.html etc, and i move through files rather quickly.

also, i have some apps in the background, like ms teams, chrome and brave, and some music or video.

here's the dev tools console log.
![emmet-crash](https://user-images.githubusercontent.com/14353433/62137204-90d0bd80-b2b3-11e9-8be2-ce81fa3b4c26.JPG)

**Comment by octref** [comment]
@suit0r Do you mind attaching the cpuprofile (zip it and drag & drop to GitHub comment)?

**Comment by suit0r** [comment]
@octref I will next time I hit the crash

**Comment by octref** [comment]
Feel free to reopen and attach the error / profile.
