### ISSUE TITLE
[SCM] commands attach to wrong Resource after reopen source control tab.

### ISSUE THREAD

**Issue by rusnasonov** [microsoft/vscode#77940]
- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: macos mojave 10.14.5

I working on extension which use SCM API, for example I look to git extension from microsoft/vscode repo.

Extension create three ResourceGroup, and attach command (with + icon) to one of them Resource items. When first time open SCM tab command bind correctly. But when close tab and open again, commad bind to Resource items from another ResourceGroup.

1. Clone repo https://github.com/rusnasonov/scmtest.
2. Run extension.
3. Open any workspace.
4. Open SCM tab. Items in `Changes` group has command, items from `Stage Changes` without command.
5. Close SCM tab and open again. Now some items from `Stage Changes` has commands.

Does this issue occur when all extensions are disabled?: Yes

![Kapture 2019-07-25 at 23 13 01](https://user-images.githubusercontent.com/4026379/61890802-79e83f00-af32-11e9-9b33-8fc2e8c89964.gif)

**Comment by joaomoreno** [comment]
Great catch!
