### ISSUE TITLE
autocorrecting to this.this.

### ISSUE THREAD

**Issue by kross-italk** [microsoft/vscode#77943]
- VSCode Version: 1.36.1
- OS Version: Windows 10

Steps to Reproduce:

1. In a javascript file type console.log(
2. Autocorrects to console.this.log( 

Similarly, this.whatever is autocorrecting to this.this.whatever 
I am using the setting acceptSuggestionOnCommitCharacter: false to prevent this behavior after searching online. This has stopped working as well. This is new behavior in the last 2 weeks or less. I haven't installed an extension or modified config in over 4 months. 
Tried to reproduce in plain JS file and was unable to. Appears to be inside an es6 class. 

Does this issue occur when all extensions are disabled?: Yes
[settings.json.txt](https://github.com/microsoft/vscode/files/3432524/settings.json.txt)

![this this autocorrect](https://user-images.githubusercontent.com/50964932/61892995-63ff5d80-aee3-11e9-916a-e715593bc1f1.gif)

**Comment by mjbvz** [comment]
I can't repo this in VS Code 1.37

Does this happen consistently in every js file in every workspace?  Can you share the rest of the file  from the example?
