### ISSUE TITLE
Alignment Issue of Error Message while clicking on Peek Problem

### ISSUE THREAD

**Issue by shauryaverma4296** [microsoft/vscode#77941]
Issue Type: <b>Bug</b>

HI,

I just saw the alignment issue. When there is a left pannel open and you click on "Peek Problem" to an error you'll see the dialouge box. But then when you hide the left pannel there is an alignment issue and also the cross button of the Peek Problem dialouge also diappear.

Please look into the issue.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 2708)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.60GB (0.35GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
elm-ls-vscode|elm|0.4.1
prettier-vscode|esb|1.9.0
smarty|imp|0.3.0
jackfranklin-elm|jac|0.23.0
Angular-BeastCode|Mik|8.0.10
vscode-elixir|mjm|1.1.0
vscode-elixir-formatter|sam|0.2.0
gitblame|wad|2.8.1
html-css-class-completion|Zig|1.19.0

</details>

**Comment by rebornix** [comment]
@shauryaverma4296 could you please share a screenshot to help troubleshoot?

**Comment by shauryaverma4296** [comment]
Here is the screenshot 
![image](https://user-images.githubusercontent.com/13284683/61992000-fb94b580-b075-11e9-94d1-4c12cf43cb1a.png)

**Comment by shauryaverma4296** [comment]
![image](https://user-images.githubusercontent.com/13284683/61992591-166b2800-b07e-11e9-940c-3bb1ed1b485e.png)

**Comment by jrieken** [comment]
You reported this against 1.32.3, please try to reproduce this with a recent version of code. Latest stable is 1.36.1
