### ISSUE TITLE
When FindText Dialog is Visible (ON) the syntax code parsing not working

### ISSUE THREAD

**Issue by IcedLife** [microsoft/vscode#77952]
1. Ctrl+F to try to find a text,
2. Leave the findText box on and open a new language file like C++ file
Expected: Text show up with syntax color and at previous opened location
Actual: Text all white and does not become colored after 5 mins and it starts at head of the file

**Comment by rebornix** [comment]
@IcedLife does this only happen with C++ file? Does it reproduce if you disable all extensions by running `code --disable-extensions`?

**Comment by IcedLife** [comment]
It didn't happen to other files for me yet. Only C++ so far, Also I am using SFTP extension and , so prior from me opening the file, the SFTP updated the local file from remote. I don't know if that contributes anything. 

I tested it again, The search box didn't seems to be the factor, but I do notice that Intellisense is on (fire on bottom left corner) while it is searching.

**Comment by rebornix** [comment]
@IcedLife do you have any C++ extension installed? If so, could you please disable it and then try to reproduce this issue? The find widget should not interfere the colorization of the code.

**Comment by IcedLife** [comment]
you right the findBox is not the factor.  I got this again when I have a lot of (15+) c++ files opened 4 of them with 1000+ lines.  So far, I don't have a reliable way to reproduce it. sorry.

**Comment by IcedLife** [comment]
If you are fine, I can close the issues, it seems it mostly just slow to parses and hangs.

**Comment by matter123** [comment]
@IcedLife does the issue still exist if you disable the setting `C_Cpp: Enhanced Colorization`?

**Comment by IcedLife** [comment]
I disabled it, but that may take a while to find out, I don't have a good way to reproduce it.

**Comment by IcedLife** [comment]
No it still happens. So my set up is I uses a linux remote box and local vscode to have a SFTP to transfer remote file over automatically. Whenever I switch branches, the SFTP extension will update the files. But recently, I am experiencing that when I open new files after switch branches, the syntax color is just not working.  I have to change language mode to re trigger for some reason.

**Comment by IcedLife** [comment]
It just takes too long for Parser to parse the files it seems.  At least, after like 10 mins, and I reopened the file it is syntax-colored
