### ISSUE TITLE
Errors in Problems panel for tsconfig.json don't appear and resolve properly

### ISSUE THREAD

**Issue by russelldavis** [microsoft/vscode#77950]
- VSCode Version: 1.36.1 (also happens in latest Insiders build)
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

*Part 1:*
a) Create a new typescript project. (Run `tsc --init` and create a simple `foo.ts` file.)
b) Open the project in VS Code.
c) Open `tsconfig.json` (without opening `foo.ts`)
d) Add this line at the top, above "compilerOptions":
```
"include": "src/**/*",
```
e) Notice that nothing appears in the Problems panel.
f) Open foo.ts
g) **An error now appears in the Problems panel for tsconfig.json. It should have appeared after step 'd'.**

*Part 2:*
a) Continuing from above, fix the error by putting the value in an array, like this:
```
"include": ["src/**/*"],
```
b) **The error should be removed from the Problems panel, but it remains.**

*Part 3:*
a) Try to update the Problems panel by restarting the TS server. You can't, because **the "TypeScript: Restart TS Server" command doesn't appear in the Command Palette when tsconfig.json is the active file**.
b) If you switch to foo.ts, you can run the Restart TS Server command, and the Problems panel finally gets updated properly. But step 3a should have been possible.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
1 has the same root cause as https://github.com/microsoft/TypeScript/issues/30623

2 is https://github.com/microsoft/TypeScript/issues/30674

Can you please open a separate issue for 3
