### ISSUE TITLE
suggest: move the "don't show again" message from gear to primary button

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#77957]
For important recommendations, we put the "Don't show again" action behind the gear. 

![image](https://user-images.githubusercontent.com/1487073/61907532-85ac1500-aee2-11e9-8a4c-97338c015ac5.png)

Suggest to move this option to a primary button, so that it is more obvious to users.

**Comment by sandy081** [comment]
It's common practice to keep this button as secondary for all our notifications. What is the reason why this button has to be primary?

**Comment by chrisdias** [comment]
ya i am pulling back on this suggestion.
