### ISSUE TITLE
Mac lock/unlock multiple windows cursors flashing

### ISSUE THREAD

**Issue by danieladams456** [microsoft/vscode#77956]
- VSCode Version: 1.37.0-insider
- OS Version: Mac OS 10.14.5

Steps to Reproduce:
1. Two windows of VS Code open (generally I have two on separate monitors, but also works with two visible and no external monitors attached)
2. Lock Mac
3. Unlock Mac
4. All VS Code windows have the keyboard cursor flashing.  It's not a huge deal, but a bit distracting seeing something move out of the corner of your eye on the other monitor.

Does this issue occur when all extensions are disabled?
Yes

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by danieladams456** [comment]
@bpasero you hit it on the head!  Issue solved on macOS with that experimental build.
