### ISSUE TITLE
problemMatcher is not working in 'Terminal' but the problem is clickable in 'Problems' view

### ISSUE THREAD

**Issue by yury-s** [microsoft/vscode#77955]
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2 LTS

Jump to code via Ctrl+click worked at some point but stopped working at some point.

Steps to Reproduce:
1. Configure custom build task:

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "build WebKit release",
            "command": "Tools/Scripts/build-webkit",
            "args": [
                "--gtk"
            ],
            "options": {
                "cwd": "/home/yurys/WebKit"
            },
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": [
                    "relative",
                    "/home/yurys/WebKit/Tools/Scripts"
                ]
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

2. Run the build task with an error in the source code:

The error line in the terminal is not linkified:
![terminal](https://user-images.githubusercontent.com/9798949/61900470-8d63bd80-aed2-11e9-8665-59d584015fdc.png)

The same error in the problems view, clicking on the problem will reveal correct line in an editor:
![problems](https://user-images.githubusercontent.com/9798949/61900515-a5d3d800-aed2-11e9-9a6e-85ed5362e431.png)

Does this issue occur when all extensions are disabled?: Yes
I've managed to reproduce it with extensions disabled but I had to change the problem matcher definition to not reference $gcc:

```json
            "problemMatcher":{
                "source": "c++ compiler",
                "owner": "external",
                "fileLocation": [
                  "relative",
                  "/home/yurys/WebKit/Tools/Scripts"
                ],
                "pattern": {
                  "regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
                  "file": 1,
                  "line": 2,
                  "column": 3,
                  "severity": 4,
                  "message": 5
                }
            },
```

**Comment by alexr00** [comment]
@yury-s if you run your webkit build in the terminal (not from the task) with the exact same parameters as you run it with the task does the same thing happen?

@Tyriar, I don't believe we do anything special to get the file clickable in the terminal with tasks.

**Comment by yury-s** [comment]
@alexr00 if I run the build script in the terminal, the error is not linkified. Moreover, it will not show up in the problems view either (not sure it is expected to):

![build-from-terminal](https://user-images.githubusercontent.com/9798949/62065721-75e34800-b1e4-11e9-82d0-d6014071eae5.png)

**Comment by Tyriar** [comment]
Oh I thought it was related to problem matchers.

The terminal resolves links against the terminal cwd which is `/home/yurys/WebKit`, the build-webkit script is printing errors relative to the script's location, not the cwd of the terminal. The terminal is checking if `/home/yurys/WebKit/../../Source/..` exist and it doesn't. This is working as intended.

**Comment by yury-s** [comment]
I see, than you, changing the task config to the following fixed the issue:
```json
            "command": "./build-webkit",
            "options": {
                "cwd": "/home/yurys/WebKit/Tools/Scripts"
            },
```

It is very confusing though that the terminal uses `problemMatcher` definition but overrides `problemMatcher.fileLocation` with `options.cwd`. I expected that `problemMatcher` definition would be self-contained and not depend on the view where it is used.

**Comment by alexr00** [comment]
The terminal doesn't actually use the `problemMatcher`, it is just the task that uses that for creating problems in the problems panel. The terminal independently creates links out of paths that exist.

**Comment by yury-s** [comment]
@alexr00 thanks for explaining, that makes sense now. I assumed that the terminal was using `problemMacher` definition because it would jump to exact location of an error in the source files, apparently default linkifier is smart enough to recognize `<source>:<line>:<col>` outputs.

**Comment by Tyriar** [comment]
The terminal links are powered by this block of regexs 🙂 

https://github.com/microsoft/vscode/blob/183deef5f43d77dc0c13e8accc41f5dff492a434/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L39-L46
