### ISSUE TITLE
Markdown preview still opens links to local files in Editor

### ISSUE THREAD

**Issue by LMKTech** [microsoft/vscode#77963]
Markdown > Preview: Open Markdown Links = inPreview

Expected behaviour: [https://code.visualstudio.com/updates/v1_28#_markdown-preview-now-opens-links-to-local-files-in-the-preview](https://code.visualstudio.com/updates/v1_28#_markdown-preview-now-opens-links-to-local-files-in-the-preview)

Looking at the example GIF in the above link, when clicking on a link to a local file, it does actually navigate to the desired location in Preview, but it also opens the <file>.md in a new Editor tab.

Seems an issue with the Markdown > Preview: Open Markdown Links setting?

Also if linking to a #label within a separate local file, the link works in Preview, but not when Open Preview to the Side is active.

Both still open the md file in Editor also.

**Comment by tarheels100** [comment]
I have the same issue.  I've attached some Markdown code that reproduces the issue.

[LinkTest.zip](https://github.com/microsoft/vscode/files/3636694/LinkTest.zip)
