### ISSUE TITLE
Add a setting to control preview behaviour when splitting an editor

### ISSUE THREAD

**Issue by tscontenna** [microsoft/vscode#77968]
VSCode Version: 1.36.1

When setting true for workbench.editor.enablePreviewFromQuickOpen,
continuous Quick-Open ( Ctrl+P ) means "opening file and close current file IF NOT EDITED".

When I use Quick-Open after splitting editor (Ctrl+\ ), the shown file is not closed.
This behavior is confusing.
And I have to close file (with Ctrl+W) twice to remove the side editor.
I think it is better the new editor by split to be treated as a preview,  regardless of editing state of its source.

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

Does it help?

**Comment by tscontenna** [comment]
Thank you for a reply.

But the article does not help me.

Regardless of the "workbench.editorenablePreview" value,  new editor region by split is not marked as "Preview".

**Comment by bpasero** [comment]
@tscontenna I see, you want an editor that opens "to the side" to preserve its preview state? We intentionally not mark an editor opened to the side as preview editor because of the explicit intent to open it to the side.

**Comment by tscontenna** [comment]
> @tscontenna I see, you want an editor that opens "to the side" to preserve its preview state? We intentionally not mark an editor opened to the side as preview editor because of the explicit intent to open it to the side.

OK. 
I often use the side editor as a Browser, to refer some code contains function definition etc.
The "Preview" concept is difficult.  There is no sign or highlight before open/close the editor. 
So "explicit" or not is not clear for us. 

BTW , I found other way to split and mark preview.
- Launch VSCode app and open a file.
- Press Ctrl+P
- Type filename
- Select file then press Ctrl+Enter Key
Then new editor opens to the side and it becomes Preview.

Could you make the UI more clear to realize the editor is "Preview" or not ?

**Comment by bpasero** [comment]
I think this requires a new setting.

**Comment by tscontenna** [comment]
> I think this requires a new setting.

Thanks, I see.
I understand your suggestion.

I often replace a preview tab with other view by mistake.
But clarifying the "Preview" state is another issue.
Please make separated ticket if possible.
