### ISSUE TITLE
Cursor slip random when select a string via mouse

### ISSUE THREAD

**Issue by dove-young** [microsoft/vscode#77966]
- VSCode Version:   1.36.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. For example, I got a function call in my code.
```
some_func_call(Cursor slip random when select a string via mouse)
```
2. I select the string `slip random when` by mouse, and I want to paste a string `not slip any more while`  then the cursor might slip and I will get a result like 
```
some_func_call(Cursor snot slip any more while select a string via mouse)
```
or 
```
some_func_call(Cursor not slip any more whilen select a string via mouse)
```

Notice the redundant `s` or redundant `n` in these examples. That's very bad because it cause program crash and very hard to notice. 

Actually I do select strings very very carefully because of this problem, but I still keep slip into this problem when coding in VSCode. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
I can't reproduce this issue locally, please help provide more info like recordings/gif or how to reproduce.

**Comment by dove-young** [comment]
Here is my screen shots.

You can find the 1st and 2nd selection go well but in the 3rd selection, the cursor slips and the letter `l` slips from selection. 

And if you check the screen shot carefully you can find that I finish each selection very carefully. Otherwise it would be something like the 2nd selection, it slips and included the suffix `.` 

![VSCode-cursor-select-1](https://user-images.githubusercontent.com/606882/62436142-4cd92f00-b771-11e9-9e6a-706574105514.gif)
