### ISSUE TITLE
Add follow link to terminal link hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#77964]
See https://github.com/microsoft/vscode/issues/69719#issuecomment-513898860

Related https://github.com/microsoft/vscode/issues/73035

**Comment by CTimmerman** [comment]
From #73035:
> This feature is already implemented in the DEBUG CONSOLE panel.

Navigating to `/home/cees/code/test/server.js:20` via de debug console only works for me when using both hands, one holding Ctrl.

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-1059-oem snap

**Comment by jmbockhorst** [comment]
@Tyriar To be able to hover over the widget so it can be clicked, we need to not hide it up if the mouse is over it. Currently, the `leaveCallback` doesn't pass any MouseEvent back, so there's no way to check. Is there a better solution? Or does `leaveCallback` in xterm need to be updated to pass back a MouseEvent?

**Comment by Tyriar** [comment]
@jmbockhorst we have some freedom here as the widget is owned by VS Code. Maybe the widget could listen for mousemove while it exists and we only hide it on leaveCallback if a mousemove event hasn't happened on the tooltip element?

**Comment by jmbockhorst** [comment]
@Tyriar I tried doing something like this, but the leaveCallback is fired before a mousemove or mouseenter is fired for the widget.

**Comment by Tyriar** [comment]
@jmbockhorst you could add a small timeout after leaveCallback before closing the widget.
