### ISSUE TITLE
can't paste

### ISSUE THREAD

**Issue by menshen** [microsoft/vscode#77970]
Issue Type: <b>Bug</b>

can't paste

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v6 @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
vim|vsc|1.8.2

</details>

**Comment by rebornix** [comment]
@menshen could you please provide more info about how to reproduce this issue? A recording/gif can help a lot.

**Comment by scole66** [comment]
This has happened to me as well.
Ctrl-V as "paste" no longer pastes any text. Right-button menu item "paste" no longer has any function.

I can select text and drag it with the cursor, but keyboard-only techniques fail.

(And: does seem to be paste. Ctrl-X to "cut" still works fine.)

**Comment by scole66** [comment]
And this morning it works again. :/

**Comment by rebornix** [comment]
@scole66 do you ever run into the issue again?

**Comment by scole66** [comment]
No, it never happened again. It pissed me off for a few days, so I came here to the issues page, and then without me even noticing the point when it changed, things started working again.

"without noticing" means that cut-n-paste is such a normal thing for me that I was just using it before I even realized that the fact it was working was a change. ☹️ Kinda means I don't have much useful info to share.

**Comment by rebornix** [comment]
Close as lack of enough information to help troubleshoot. We can reopen whenever we have good reproduce steps.
