### ISSUE TITLE
Typing performance is laggy for long sentence with hyperlinks

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#7797]
- VSCode Version:1.2.1
- OS Version:Window 10

This seems very odd. 

Steps to Reproduce:

1. Create an empty file (just blah.txt) and paste in the follow Markdown sentence:
```
For debugging other languages and runtimes (including [PHP](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug), [Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby), [Go](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go), [C#](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp), [Python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) and many others), please look for `Debuggers` [extensions](/docs/editor/extension-gallery.md) in our [VS Code Marketplace](https://marketplace.visualstudio.com/vscode/Debuggers) extension.
```
2. Now type words anywhere in the sentence.  The typing performance is laggy and ackward.
Typing elsewhere in the file feels responsive.

**Comment by gregvanl** [comment]
Keyboard navigation is also slow in the sentence.

**Comment by alexandrudima** [comment]
@gregvanl I am not seeing this slowness. Can you please profile and attach the CPU profile trace. Here I am doing it:

* F1 > Developer tools
* Profile tab
* Start profiling
* Do the typing or whatever causes slowness
* Stop profiling
* Save the cpu profile

It would be preferable if you could do this in a dev environment such that the function names are not all garbled, but I would take it anyways :). Anything to help me repro.

![wzf9w4xpbz](https://cloud.githubusercontent.com/assets/5047891/16144526/d6bc5528-3473-11e6-9e7c-72b830bcf1a0.gif)

**Comment by alexandrudima** [comment]
@gregvanl Do you have a laptop with a touchscreen?

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
