### ISSUE TITLE
Not able to see tsc build task

### ISSUE THREAD

**Issue by chanduDendukuri** [microsoft/vscode#77973]
- VSCode Version:
- OS Version:

I tried to fix using https://github.com/microsoft/vscode/issues/74756  but it doesnt work for me..
Steps to Reproduce:

1. Till couple of days back , am able to build TSC files with out any issues ,, but all of sudden am not able to see tsc build tasks or watch tasks by clicking on cntl + shift + B

2. I followed couple of steps in the forms by replacing forward slashes with 2 backward slashes but there is no luck.. and it is creating another task in the tasks.js file.

```
    {
        // See https://go.microsoft.com/fwlink/?LinkId=733558 
        // for the documentation about the tasks.json format
        "version": "2.0.0",
        "tasks": [
            {
                "type": "typescript",
                "tsconfig": "node_modules\\protractor\\tsconfig.json",
                "group": {
                    "kind": "build",
                    "isDefault": true
                    
                }
            },
            {
                "type": "gulp",
                "task": "amrdemo",
                "group": "build"
            },
            {
                "type": "gulp",
                "task": "JShint",
                "problemMatcher": []
            },
            {
                "type": "npm",
                "script": "install",
                "problemMatcher": []
            },
            {
                "type": "npm",
                "script": "test",
                "problemMatcher": []
            },
            {
                "type": "typescript",
                "tsconfig": "node_modules/protractor/tsconfig.json",
                "problemMatcher": [
                    "$tsc"
                ]
            }
        ]
    }
```

Kindly help me out on this..

I tried restarting my machine..
i tired uninstalling and installing vsCode.. 
but no luck

**Comment by chanduDendukuri** [comment]
while trying to build above one... it throws 
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "type": "typescript",
    "tsconfig": "node_modules\\protractor\\tsconfig.json",
    "problemMatcher": [
        "$tsc"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.

**Comment by mjbvz** [comment]
Using the latest VS Code build, can you try changing to use forward slash paths in the task instead of backslash ones
