### ISSUE TITLE
Terminal: Pasting text into Terminal  appears garbled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#77976]
On today's Linux Insiders (d471d1c7f918ff567e71026671896f17f388a784):

1. Copy `hello`
2. Paste it into the Terminal with <kbd>Ctrl V</kbd>

![image](https://user-images.githubusercontent.com/22350/61937873-1a208100-af90-11e9-81ab-dd9f4ac8eb7a.png)

Pasting it with right click, `Paste`, works. Pasting it with <kbd>Ctrl Shift V</kbd> works too.

**Comment by Tyriar** [comment]
@joaomoreno this was probably caused by https://github.com/microsoft/vscode/issues/77975? I can't repro but ctrl+v was never meant to paste in Linux unless you've tweaked your keybindings.

**Comment by Tyriar** [comment]
If you're interested what the 200 is, it's encoding "bracketed paste mode" which applications can turn on so they know what text is typed and what is pasted.
