### ISSUE TITLE
Want a 'current debug line' button on debugging.

### ISSUE THREAD

**Issue by cangyin** [microsoft/vscode#77971]
Issue Type: <b>Feature Request</b>

The basic debug buttons provided are helpful, but I still want a "Current line" added to them. Because some times when I jumped in and out of functions, I loses debug focus.
Best regards!

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.14393

**Comment by isidorn** [comment]
There is a context menu action in the editor: Run to Cursor
And for some debug adapters like C# "Jump to Cursor"

You can also find these commands in the command palette
