### ISSUE TITLE
Terminal doesn't catch Ctrl-B any more

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#77975]
On today's Linux Insiders (d471d1c7f918ff567e71026671896f17f388a784):

1. Focus terminal
2. Press <kbd>Ctrl B</kbd>

The sidepanel hides/shows.

This broke sometime this week, so it could be related to grid work @sbatten. Assigning @Tyriar as well just in case.

**Comment by joaomoreno** [comment]
Weird, I can't repro off `master` in dev.

**Comment by joaomoreno** [comment]
I also can't repro dev out of d471d1c7f918ff567e71026671896f17f388a784, which is latest insiders.

**Comment by joaomoreno** [comment]
Doesn't repro on today's Insiders: 6d82826e990407364d5c829b73602a19ecdf7d00

Turns out I didn't actually have the latest.

**Comment by Tyriar** [comment]
I caused this by trying to fix an a11y issue, fixed yesterday https://github.com/microsoft/vscode/issues/77945
