### ISSUE TITLE
VS Code should not hijack svg OS file association

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7798]
Steps to Reproduce:

1. Install vscode on OS X
2. Double click an .svg file in finder, vscode opens the file, not a browser/viewer.

**Comment by joaomoreno** [comment]
AFAIK Code just lets OS X know that it *can* edit SVG files, that is all. Right, @weinand?

**Comment by weinand** [comment]
Yes, we are registering VS Code as a editor for SVG files, but how VS Code has become the default editor for SVG is unclear to me.

You can change the default here:
![2016-06-17_10-26-22](https://cloud.githubusercontent.com/assets/1898161/16144872/088adf78-3476-11e6-9b69-ffc7d957337b.png)

**Comment by Tyriar** [comment]
This is on my relatively new macbook, I have Chrome and Code Insiders installed, I was expecting to view the image not the code when I opened it.

**Comment by weinand** [comment]
@Tyriar then you'll have to make Chrome the default viewer for *.svg
