### ISSUE TITLE
CANNOT open code on Ubuntu 16.04

### ISSUE THREAD

**Issue by Xuguanglin** [microsoft/vscode#77981]
- VSCode Version: 1.36.1-1562627527
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1. I install the vscode from the *.deb, but code cannot open, whether from the terminal or the start menu, even the `code --verbose` shows nothing

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Assigned to @bpasero since there are couples of launching issues since 1.36.

**Comment by Xuguanglin** [comment]
> Assigned to @bpasero since there are couples of launching issues since 1.36.

But I tried v1.35, v1.33, v1.30 and even v1.27, no one works.
