### ISSUE TITLE
Adding jar to vscode debug extension

### ISSUE THREAD

**Issue by BelidePruthvi** [microsoft/vscode#77982]
I have posted this question at https://stackoverflow.com/questions/57056473/adding-jar-to-vscode-debug-extension but there was no reply there , so I am posting the question here

We are having a runnable jar for the DAP(Debugger Adapater Protocol) of ABL language and we are planning to add a vscode extension for that ABL DAP.
we couldn't find how to add the jar anywhere so our work is blocked. 
Could you provide us some documentation or give us an idea about how to do it?

**Comment by weinand** [comment]
There are basically two approaches for making VS Code run your *.jar:
- **declarative**:
In the `package.json` of your extension, you can register your executable as part of the `debuggers` extension point. Here is the doc: https://code.visualstudio.com/api/extension-guides/debugger-extension#anatomy-of-the-package.json-of-a-debugger-extension. <BR>
And here is an example from the node.js debugger.
Basically the following attributes are available:
  ```json
    "runtime": "node",
    "runtimeArgs": [ "--arguments_passed_to_runtime" ],
    "program": "./dist/dap.js",
    "args": [ "--arguments_passed_to_program" ],
  ```
  The resulting command that VS Code will call is this:
  ```
    node "--arguments_passed_to_runtime" ./dist/dap.js --arguments_passed_to_program
  ```
  You do not have to make a distinction between runtime and program. You can use either "runtime" or "program" and leave out the other.

- non-declarative:
Alternatively you can use extension code to "calculate" the command that VS Code should execute when launching your Debug Adapter. See this API: https://github.com/microsoft/vscode/blob/4c3769071459718f89bd48fa3b6e806c83cf3336/src/vs/vscode.d.ts#L8797-L8816
Based on this API the following snippet shows how you could create a DebugAdapterDescriptor for your abl debugger:
  ```ts
  // this method is called when your extension is activated
  // your extension is activated the very first time the command is executed
  export function activate(context: ExtensionContext) {

    vscode.debug.registerDebugAdapterDescriptorFactory('abl', {
		createDebugAdapterDescriptor(session: DebugSession, executable: DebugAdapterExecutable | undefined): ProviderResult<DebugAdapterDescriptor> {
            return new vscode.DebugAdapterExecutable(
                "/usr/bin/java",
                [
                    join(context.extensionPath, "bin", "abl.jar")
                ],
                {
                    "cwd": "some current working directory path",
                    "env": {
                        "key": "value"
                    }
                }
            );
        }
    });
  }
  ```
