### ISSUE TITLE
Overwrite top menu bar shortcuts

### ISSUE THREAD

**Issue by gkkirilov** [microsoft/vscode#77987]
Currently, Alt+<letter> opens the top menu bar, for example, Alt+D opens the debug menu.

Would like to be able to remap Alt+<letter> to something more useful than opening the menu bar.

**Comment by sbatten** [comment]
Use `window.customMenuBarAltFocus` and `window.enableMenuBarMnemonics` and configure Alt keybindings to your hearts content.

**Comment by gkkirilov** [comment]
@sbatten Is there a way to stop the toggling of the menu entirely?
