### ISSUE TITLE
comment thread context value affects other threads too

### ISSUE THREAD

**Issue by BenPryor** [microsoft/vscode#77994]
Repro steps:
  1. Build and run the comment sample ([https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample))
  2. Open a file
  3. Add a first comment thread to the file (click in the comment gutter, enter some text, and click Create Note)
  4. Add a second comment thread to the file
  5. Go to the first comment thread, enter some text in the reply area, and click Start Draft

Now both comment threads will show the Finish Draft thread context action.

This is not expected - only the first comment thread has the `'draft'` contextValue, but both are getting the mywiki.finishDraft context command that has `"when": "commentThread == draft"`.

VSCode version:
  * Version: 1.37.0-insider (user setup)
  * Commit: d4b3a7a22fe01ce6af85f9c59943ad54d6f6f205
  * Date: 2019-07-25T16:23:12.371Z

CC @rebornix and @RMacfarlane

**Comment by rebornix** [comment]
A really good catch, we created the `commentThread` key on the parent context key service by mistake, that's why it's being leaked.

**Comment by BenPryor** [comment]
Thanks for the very quick fix!
