### ISSUE TITLE
Symbol & Text may fuzz and unclear

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#7799]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Version 1511

Steps to Reproduce:
1. Set language as PHP, type code like screenshot
2. First line pad with 8 space, next line pad with 9 space at start

![vscode](https://cloud.githubusercontent.com/assets/4962408/16138762/67afd4b6-3473-11e6-860d-7d03814828b9.png)

Look at two '|' symbol, they are same symbol, i have copy them into node console and compare , result is true.

**Comment by sandy081** [comment]
@ArianeLu Can you please provide complete lines?

**Comment by ArianeLu** [comment]
![vscode](https://cloud.githubusercontent.com/assets/4962408/16144457/a923544a-34a5-11e6-83fc-a58962339493.png)

@sandy081 Look, no need complete lines, the code in picture have same issue

**Comment by aeschli** [comment]
This is about the editor rendering being fuzzy on line 2

**Comment by alexandrudima** [comment]
I can reproduce:

![image](https://cloud.githubusercontent.com/assets/5047891/17508903/9df9e84a-5e17-11e6-82af-dc65d8e432b4.png)

But I think this is the sub-pixel antialising implementation of Chromium

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
