### ISSUE TITLE
File > Save As moves cursor to beginning of file

### ISSUE THREAD

**Issue by wregimbal** [microsoft/vscode#77996]
Issue Type: <b>Bug</b>

When performing a Save As, the cursor is moved to the very beginning of the file.  It would be preferable to keep the cursor position, especially if making separate changes to 1 line across all the newly created files.  This can be distracting for long lines.  I have tried disabling all extensions.  Bookmarks also will not work.  It would seem that Save As creates a new file and the bookmarks are lost.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
bracket-pair-colorizer-2|Coe|0.0.28
atom-icons|emr|1.0.2
vsc-material-theme|Equ|29.2.0
abaqus|JP|1.0.0
vscode-simple-icons|Lau|1.11.9
python|ms-|2019.6.24221
atom-keybindings|ms-|3.0.6
material-icon-theme|PKi|3.8.1
vscode-fileutils|sle|2.14.5
vscode-icons|vsc|8.8.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Good catch, looks like this broke a while ago.
