### ISSUE TITLE
Update issue: Setup files are corrupted

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#780]
hey guys. i am running on windows 10 pro v-1511 and code v-10.1 it's not updating automatically but it shows a pop-up, i click update now it closes the editor, i have tried to wait for 10 min it didn't work when i launched the code it was the same, what should i do ?  maybe it is because my windows is not activated ? i clean installed and lost my key.

**Comment by oatmealpirate** [comment]
Go to http://code.visualstudio.com to download VSCodeSetup.exe and install.

**Comment by Johnaka** [comment]
>oatmealpirate. oh man thank you you're my hero you've made my day!

**Comment by joaomoreno** [comment]
Seems fixed.

**Comment by Johnaka** [comment]
>joaomoreno it never works for me to be sarcastic !

**Comment by joaomoreno** [comment]
@Johnaka, is it fixed?

**Comment by Johnaka** [comment]
>joaomoreno nope if i could fix that i wouldn't be here

**Comment by joaomoreno** [comment]
Is it constantly happening then? I mean the cycle of

1. Code reports there is an update.
2. You press Update Now
3. Editor closes.
4. Nothing happens.
5. You launch Code.
6. Code reports there is an update...

**Comment by Johnaka** [comment]
>joaomoreno yep, it works perfectly, i could download and install but i don't wanna do it over and over.

**Comment by oatmealpirate** [comment]
this question you said happened during 0.10.2 updating, my two computer all met, but my cycle is
1. Code reports there is an update.
2. You press Update Now.
3. Editor closes.
4. A error report tell you the installer is not comlete.
5. You launch Code.
6. Code reports there is an update...
At last I had to go to visit http://code.visualstudio.com to download `VSCodeSetup.exe` and installed.

**Comment by Johnaka** [comment]
now it shows downloading update.... but nothing happens i have waited for 25 minutes with my 236kbs speed. it didn't update

**Comment by Johnaka** [comment]
![untitledjhjh](https://cloud.githubusercontent.com/assets/11838212/11525164/a2380a58-98f2-11e5-8664-b56ec51e0ecd.jpg)

this happened !

**Comment by Johnaka** [comment]
why can't you make it like google chrome ? i have never had troubles updating chrome. i actually never go there if it's updated or not. i am sure it will

**Comment by joaomoreno** [comment]
Aha, an error! Good, we can do something about that.

**Comment by Johnaka** [comment]
thank you. can it be because of my internet speed ? it waves from 12 to 236 kbps ?

**Comment by hville** [comment]
I am having the same issue, that only started yesterday (15 December) well after the 10.3 update.
* `vscode` prompts that an update is available
* When trying to update I get the the error prompt `The setup files are corrupted`
* Re-installing a new `vscode version 10.3` did not resolve the problem

**Comment by Johnaka** [comment]
oh i love you people. now that someone else has that issue i guess they will fix it

**Comment by Johnaka** [comment]
i think i know what causes that issue, it is internet. because i have the same thing happening when i download an app with my chrome browser, when internet bumps it gives me an error, and i start over.

**Comment by Johnaka** [comment]
also 'ext install' is not working

**Comment by Johnaka** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11838212/12003385/230f6826-ab3e-11e5-8583-2ac0ddfc4609.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/11838212/12003386/2314ebfc-ab3e-11e5-9b22-9356a74007ff.jpg)

**Comment by Johnaka** [comment]
downloaded and installed v-10.05
noticed that in v-10.05 no highlighting
some time later new version has arrived 
tried to update it told me
(Error) The setup files are corrupted. Please obtain a new copy of the program.
╫

**Comment by imsedim** [comment]
Happened to me when VS code tried to update to version 1.1 from version 1.0

**Comment by duncanhunter** [comment]
Also happened to me when VS code tried to update to version 1.1 from version 1.0

**Comment by Johnaka** [comment]
switched to Atom by github perfect my life is PERFECT now

**Comment by imsedim** [comment]
Well I switched **from** Atom and have nowhere to go now.

**Comment by Johnaka** [comment]
when it comes to golang atom turns out to be better than vscode, vscode best for  typescript

**Comment by Hardboiled-frog** [comment]
always happens to me, I've never been able to update automatically, ofc, if you upgrade manually it works just fine(I'm on 8.1 x64)
thanks

**Comment by jangajack** [comment]
I have the same issue with this update. It's easy to fix by re-downloading the installer, but still it would be better to have a button to re-download the update, or for VSCode to detect failed installs and re-download the update automatically.

**Comment by rebornix** [comment]
+1 here. 

Working from Costa now and VS Code starts to download newest version automatically. But unfortunately the file downloaded was somewhat corrupted. The first idea came into my mind was opening VS Code and triggered the check for update button again, but unfortunately I had to download the bits only from site.

**Comment by dbaeumer** [comment]
Verified by code review.

**Comment by smuuf** [comment]
It still happens to me with versions `1.5.2` -> `1.5.3` - on Windows 7.

And it was happening even with `1.5.1` -> `1.5.2`, which I resolved by manually downloading and installing the "pure" setup package. And now it's still happening again.

**Comment by fabrulana** [comment]
Same issue here. Happened after a really bad internet connection. The download probably failed whereas VS Code assumed it downloaded correctly and keeps trying to install the failed download. Had to reinstall VS Code manually.

**Comment by joaomoreno** [comment]
@fabrulana Is this Windows?

**Comment by mikeyjk** [comment]
I'm experiencing this on a system where I have not previously installed Code.
Win 10, 64 bit.
Re-downloading the installer doesn't change the outcome unfortunately.
Neither does running it is administrator.

**Comment by joaomoreno** [comment]
@mikeyjk Did you download it straight from https://code.visualstudio.com ? Can you give me the size and SHA1 of the Setup.exe you downloaded?

**Comment by mikeyjk** [comment]
@joaomoreno thank you for your response! You were so prompt I missed it :).

I am now able to get past this issue, however the application is launching 'off screen', and no amount of win 10 tricks seems to be working (snap right, snap left, winkey + all arrows, right click + move).

Completely separate issue now, though.

**Comment by fabrulana** [comment]
@joaomoreno Sorry yes it was windows - also missed your comment like mikeyjk above.

@mikeyjk Use Alt+Space and then press 'm' key ... then move window with arrow keys.
