### ISSUE TITLE
Test:  editor.renderWhitespace "selection" option

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#78002]
Test for https://github.com/microsoft/vscode/issues/1477

- [x] Windows @bowdenk7
- [x] macOS @roblourens
- [x] Linux @aeschli

Complexity: 2

The `editor.renderWhitespace` setting has a new option, “selection”, that renders whitespace only for selected text. Test that this behaves as expected on single and multicursor selections.

**Comment by andremacola** [comment]
Nice. Looks like it's working.

**Comment by IllusionMH** [comment]
Small clarification:
Is it expected that there are no whitespace characters in search matches but they are visible in current match?
![image](https://user-images.githubusercontent.com/1312662/62047469-3bdd6a80-b213-11e9-93ff-e2b1db601c71.png)

**Comment by roblourens** [comment]
I think that is expected @IllusionMH because those are not "editor selections", just a highlighted range
