### ISSUE TITLE
Emmet: Support to wrap with abbreviation

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#7800]

**Comment by yisibl** [comment]
Demo and doc: http://docs.emmet.io/actions/wrap-with-abbreviation/

**Comment by egamma** [comment]
@yisible thanks 🌷 . Looks like we had the same plan and do some work on this over the weekend 😄. I'm about to checkin some of these features. I'll ping when done. Pls review and then I suggest we join forces.

**Comment by egamma** [comment]
@yisibl the changes are committed please verify them in the insiders build.

**Comment by yisibl** [comment]
@egamma  We should support real time preview, is so cool 👻 
![](https://img.alicdn.com/tps/TB1Vj..KpXXXXbnaXXXXXXXXXXX-360-235.gif)

**Comment by jonathanphz** [comment]
What's the command to do this? Cntrl + W doesn't seem to work.

**Comment by morcegon** [comment]
Please! This is so helpful!
