### ISSUE TITLE
Special characters in .env variables not correctly escaped

### ISSUE THREAD

**Issue by alsteven** [microsoft/vscode#78014]
Essentially the same as issue #50302, seems like you missed escaping a character.
 
- VSCode Version: 1.36.1
- OS Version: Windows 10

Steps to Reproduce:
1. Set up any python project
2. Create a .env file with BUG=HELLO>LOOKAFILE
3. Start debugging 

The ">" character is not correctly escaped and will cause a file that begins with "LOOKAFILE" to be created in the current directory.

**Comment by alsteven** [comment]
I should point out that because you are escaping the escape character (^), I can't even easily work around this, since my attempt to escape ">" by using "^>" gets turned into "^^>"

These are the characters you need to escape:
<, >, |, &, ^

Reference: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1

**Comment by alsteven** [comment]
This fix indeed didn't go far enough:
https://github.com/microsoft/vscode/commit/2ff1c7de9376f9dfc09cf1da61dc88a0bc28a6c6

Someone just needs to change line 277 of src/vs/workbench/parts/debug/node/terminals.ts please.

Need to add escaping for three additional chars:  |, < and >

**Comment by sksaifuddin** [comment]
I found the issue. Working on it, will create a PR soon
