### ISSUE TITLE
Emmet HTML: wrapping multiple lines with output.format (formerly tag_nl) set to false

### ISSUE THREAD

**Issue by lucasengel** [microsoft/vscode#78015]
Emmet should expand multi-line abbr keeping lines as-is even with setting `"tag_nl": false`

Steps to Reproduce:
1. Open the following HTML:
```
one
two
```
2. Select text
3. Run `Emmet: Wrap individual Lines with Abbreviation`
4. ul>li*

Expected:
```
<ul>
  <li>one</li>
  <li>two</li>
</ul>
```

Actual:
```
<ul><li>one</li><li>two</li></ul>
```

**Comment by octref** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/4033249/62333090-e1dcdf00-b476-11e9-8c55-c08d33414141.png)

Any emmet setting you have?

**Comment by lucasengel** [comment]
@octref yes, as per the title, I have tag_nl set to true:
```
"emmet.syntaxProfiles": {
        "html": {
            "tag_nl": false            
        }
    }
```

My understanding of this flag is that it should prevent single-line wraps from creating new lines.

Instead of this:
![Screen Recording 2019-08-01 at 7 32 31 pm](https://user-images.githubusercontent.com/1020229/62334053-1317d800-b494-11e9-86c4-f614c009f881.gif)

Getting this:
![Screen Recording 2019-08-01 at 7 35 21 pm](https://user-images.githubusercontent.com/1020229/62334052-1317d800-b494-11e9-8f1d-28acba1fcc81.gif)

I guess my bug report is due to the inconsistency. One multi-lines the extra-lines are not created while on single lines they are.
![Screen Recording 2019-08-01 at 7 44 36 pm](https://user-images.githubusercontent.com/1020229/62334289-224b5580-b495-11e9-93b1-171fd77dd02c.gif)

**Comment by lucasengel** [comment]
Let's start over.

With this set on your settings:
```
{
  "emmet.syntaxProfiles": {
    "html": {
        "tag_nl": false            
    }
  }
}
```

Try wrapping the following with a  `ul`:
```
<li>one</li>
<li>two></li>
```

Instead of getting:
```
<ul>
  <li>one</li>
  <li>two></li>
</ul>
```
You get everything in one line:
```<ul><li>one</li><li>two></li></ul>```

**Comment by rzhao271** [comment]
Marking this as an upstream issue because it still happens on the latest Emmet.

**Comment by rzhao271** [comment]
@sergeche I labelled this as upstream, but I can remove that label if the following is intended behaviour:

Should wrapping `['one', 'two']` with `ul>li*` and `{ "output.format": false }` result in `<ul>\n\t<li>one</li>\n\t<li>two</li>\n</ul>`? Currently, it just collapses everything into a single line.

**Comment by sergeche** [comment]
Yes, `format: false` should always produce output on single line. The purpose of this option is to produce proper output for string literal, for example

**Comment by lucasengel** [comment]
@sergeche so your answer is actually 'No', right?

What would be the appropriate option to have the output as @rzhao271 referred to (note the `\n`s and `\t`s)?

**Comment by sergeche** [comment]
The answer is "no". I'm curious what's the reason to disable formatting and expect formatted output?

**Comment by lucasengel** [comment]
As I was trying to replicate the original issue on VSC 1.51.0-insider I noticed that it is now solved.

I'm closing this issue for now.
