### ISSUE TITLE
Maintain cursor position relative to viewport on page-up and page-down

### ISSUE THREAD

**Issue by russelldavis** [microsoft/vscode#78013]
This is the same issue as #17686 and #22796, but those are locked from additional comments. I wanted to add a couple things:

- I created an extension that implements the change: https://marketplace.visualstudio.com/items?itemName=russelldavis.better-pageup-pagedown.
- The implementation is dead-simple, it's just a `scrollPage{Up/Down}` followed by a `cursorPage{Up/Down}`.
- With this extension as a workaround, there might be less of a need to add this as an opt-in config to VSCode. However, I think it would be valuable for VSCode to change its *default behavior* to this.
  - As mentioned in the other issues, this would be consistent with the default behavior in Visual Studio, Sublime Text, Jetbrains IDEs, and others. 
  - It would be an easy change to make.
  - I'd be happy to submit a PR if it would be accepted.

cc @alexandrudima @DaanDeMeyer @darekrusin @kobalicek (from the other issues)

**Comment by darekrusin** [comment]
Ah... yes! Now it's finally working as it's supposed to :) Thanks so much, Russel.

**Comment by russelldavis** [comment]
@alexandrudima I'm just looking for a yes/no/maybe on whether a PR for this would be accepted, then I'll close this issue.

**Comment by alexandrudima** [comment]
PR welcome

**Comment by russelldavis** [comment]
👍, PR forthcoming.
