### ISSUE TITLE
Menu shifted, not in the right place

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#78010]
Hi

You broke the menus on Insiders :smile: 

![vscode-bug2](https://user-images.githubusercontent.com/15984272/61975675-115c9900-afea-11e9-8968-95f3803a093b.png)

Less offset with the left bar collapsed

![vscode-bug3](https://user-images.githubusercontent.com/15984272/61975762-4e289000-afea-11e9-990e-2dba0dcaa3c3.png)

VS Code version: Code - Insiders 1.37.0-insider (6d82826e990407364d5c829b73602a19ecdf7d00, 2019-07-26T05:28:07.472Z)
OS version: Linux x64 4.15.0-54-generic

**Comment by sbatten** [comment]
This happened when switch between native and custom title bar I believe. I've added code to reset the layout if this is detected but it shouldn't happen again as I've fixed what I believe was the root cause as well.
