### ISSUE TITLE
Abort on running script on intregrated terminal does not respond.

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#7801]
- VSCode Version: 1.2.1
- OS Version: Fedora 23

Steps to Reproduce:

1. Open a VSCode 
2. Run a PHP script which runs forever
3. Try to kill the running PHP script by Ctrl+C. 

What is happening?
It does not abort the running script.

**Comment by sandy081** [comment]
@Tyriar Not sure if it is related/duplicate of #7740

**Comment by forethoughtde** [comment]
It is about integrated terminal. The other one is external terminal.

**Comment by Tyriar** [comment]
This is a duplicate of https://github.com/Microsoft/vscode/issues/7554, it is somewhat fixed but still needs https://github.com/sourcelair/xterm.js/issues/134 to be looked at for better performance.
