### ISSUE TITLE
Options menu for extensions in the activity bar

### ISSUE THREAD

**Issue by llkiriell** [microsoft/vscode#78011]
Currently, when you click on the activity bar (anywhere, even above an extension), the menu that appears is:

![](https://images2.imgbox.com/29/15/74ZkT6iX_o.jpg)

However, I propose that a menu of options (uninstall extension, reload, disable, properties or settings, etc.) be added for extensions that are in the bar. Having a menu on each extension of the activity bar would save time by having to go to the extensions list and uninstall an extension or disable it:

![](https://images2.imgbox.com/ea/2a/lY1whjg7_o.jpg)

**Comment by sandy081** [comment]
Not a big fan of this especially because we do not do this anywhere where extensions contribute icons.
