### ISSUE TITLE
Change of behavior with closing parenthesis

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#78012]
The behavior of closing character elision appears to have changed with today's update to VS Code. Also as of today, the closing character now appears dimmed. The elision works as expected when the closing character is dimmed, but not when I've moved away from the line and moved back.

It would appear that the previous behavior was desired (https://github.com/microsoft/vscode/issues/55707). The only related commit I could see from today was 141617c5b5793b2f7313e8295581afdf88480014.

## Version information

- Version: 1.37.0-insider (user setup)
- Commit: 6d82826e990407364d5c829b73602a19ecdf7d00
- Date: 2019-07-26T05:37:26.606Z
OS: Windows_NT x64 6.3.9600 (Windows 8)

## Steps to Reproduce

1. Type an open parenthesis (`'('`) and observe that the closing parenthesis is added after the cursor, colored dimly: 

![ugg](https://user-images.githubusercontent.com/5044802/61977833-25d26e80-afb5-11e9-87a7-59ff5b83653c.png)

2. Click away from the current cursor location. Observe that the closing parenthesis is no longer dimmed:

![ugg2](https://user-images.githubusercontent.com/5044802/61977966-7ea20700-afb5-11e9-85b4-68fe5ccd1107.png)

3. Type a closing parenthesis (`')'`) and observe the unexpected character:

![ugg3](https://user-images.githubusercontent.com/5044802/61977986-882b6f00-afb5-11e9-9a2d-a19c4bd98b90.png)

Does this issue occur when all extensions are disabled?: untested

**Comment by kylrth** [comment]
The dimming behavior and this character elision bug appear to have been removed at or before 3802a986823977ec472fc993854e1a753037fc8f. If no one disagrees in the next few days I'll close this.

**Comment by alexandrudima** [comment]
These changes were done for #37315 . I have removed the dimming in the meantime. But, there is still a difference:

**VS Code will now overtype `)` only if the specific `)` was automatically inserted by the editor, it will not overtype other `)` characters ...** The same is true for all other auto-closing character pairs...

@kylrth Please try it out and let me know if this is disturbing. I can add an option to get the old behavior (where overtyping would work on any character, even those which were not inserted by the editor), but I would try to avoid adding yet another option... as the current behavior should be intuitive and hopefully pleasant to use.

**Comment by kylrth** [comment]
I'll have to change my habit of using the closing character as a way to move to the end of the line. :) All good.
