### ISSUE TITLE
more commands for different functions

### ISSUE THREAD

**Issue by SteinTheRuler** [microsoft/vscode#78023]
Expose a command for every supported command. I can call outline.focus, but not outline.hide (even though you can right-click and select hide). You can also collapse in Outline panel, which is not supported as command. More toggle commands for panels.

**Comment by sandy081** [comment]
@SteinTheRuler What is the usecase to hide outline view (or any other view) programmatically?

**Comment by SteinTheRuler** [comment]
It makes using the software more fluid if it can show/hide panel's using the keyboard instead of the cursor. What I'm thinking about is that everything you can do with the mouse, you should be able to do with the keyboard, or at least expose the methods and offer more options to extensions.

**Comment by sandy081** [comment]
I do not think its a good idea to have a command per view. Instead there can be a single command that takes view id as argument.

**Comment by SteinTheRuler** [comment]
yeah, sounds smart. for example, the Outline panel only has the command focus, but no command for hiding. maybe more toggle-style could be nice.
