### ISSUE TITLE
Move config to XDG_CONFIG_HOME in Linux

### ISSUE THREAD

**Issue by MycroftHolmes1989** [microsoft/vscode#78026]
Kindly change the current convention of putting the configurations in `~/.vscode` to `~/.config/vscode`. In other words, use the `XDG_CONFIG_HOME`. Putting the config files in home directory goes against the norms prescribed by the FOSS community. For more info, please check [this](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) or [this](https://wiki.archlinux.org/index.php/XDG_Base_Directory).

- VSCode Version: 1.36.1
- OS Version: Fedora/Ubuntu (Any Linux Distro will do)

Steps to Reproduce:

Installation of VSCode creates a directory containing the so-called dotfiles, which are the config files as well as the extensions used by VSCode. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by ayekat** [comment]
Uhm… https://github.com/Microsoft/vscode/issues/3884?
