### ISSUE TITLE
clipboard paste error

### ISSUE THREAD

**Issue by frozenzj** [microsoft/vscode#78025]
Issue Type: <b>Bug</b>

when I  copy my code to the clipboard,and then paste them into the ipython(open with integrated shell),the line break symbol turn into "^["
paste result:
```
In[1]:import os
  ...:^[
  ...:import datetime
```  
except:
```
In[1]:import os
  ...:import datetime
```  
VS Code version: Code - Insiders 1.37.0-insider (6d82826e990407364d5c829b73602a19ecdf7d00, 2019-07-26T05:37:26.606Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
vagrant|bbe|0.5.0
vscode-ipaddress|Com|1.0.0
python-extension-pack|don|1.6.0
gitlens|eam|9.9.1
vsc-python-indent|Kev|1.2.0
MagicPython|mag|1.1.0
VS-code-vagrantfile|mar|0.0.7
vscode-language-pack-zh-hans|MS-|1.37.0
mssql|ms-|1.6.0
python|ms-|2019.6.24221
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
resourcemonitor|mut|1.0.6
LiveServer|rit|5.6.1
ayu|tea|0.18.0
python|tht|0.2.3
vscodeintellicode|Vis|1.1.8
vscode-icons|vsc|8.8.0
jinja|who|0.0.8

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
