### ISSUE TITLE
auto import same file more than once

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#78036]
```
import {
  readJSON,
  writeKVBlockHeader,
  writeJSONVarint,
  writeJSONName,
  BIN_KV_SERIALIZE_TYPE_STRING,
} from '../../../p2p/protocol/json';
...
import {
  readJSONVarint,
  BIN_KV_SERIALIZE_TYPE_STRING,
} from '../../../p2p/protocol/json';
```

when select the prompted optioins `BIN_KV_SERIALIZE_TYPE_STRING`, it can be imported more than once.

**Comment by mjbvz** [comment]
Please provide a compete, minimal code example and steps to reproduce

/needsMoreInfo

**Comment by calidion** [comment]
@mjbvz 

1. create more than one exports in a file
2. import one first, then import another.

**Comment by mjbvz** [comment]
Please provide a compete, minimal code example
