### ISSUE TITLE
js - collapse for es6 class instance

### ISSUE THREAD

**Issue by ramtinabadi** [microsoft/vscode#78035]
While initializing a class in es6, if the class has a `{}` or function as an arguement in the constructor, we can collapse the code. such as :
![Screenshot 2019-07-27 at 3 46 43 PM](https://user-images.githubusercontent.com/17789994/61993197-db6cf280-b085-11e9-9881-024c85ea8d00.png)
But if the class takes only variables or expresions as arguments, there is no collapse option. For example:
![Screenshot 2019-07-27 at 3 50 14 PM](https://user-images.githubusercontent.com/17789994/61993223-3ef72000-b086-11e9-8b12-ea15ec3bb830.png)
It would be very useful if we could collapse the variable itself.

**Comment by mjbvz** [comment]
Intelligent code folding for JavaScript and TypeScript is powered by TypeScript project. Please file a feature request against them: https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md
