### ISSUE TITLE
[Shell Scripts] Wrong Syntax Highlighting

### ISSUE THREAD

**Issue by IceWreck** [microsoft/vscode#78034]
- VSCode Version: 1.36
- OS Version: Fedora 30

Steps to Reproduce:

1. Open a bash script. (.sh file) 
2. Write some code and then type `#` in the same line. Example : 
```
sudo dnf remove -y \
krdc \
kmail \
kgpg \
krusader \ # the old kde twinstyle file manager
kruler
```
3. Everything after `#` is greyed out and vscode thinks that its a comment, misleading the user

This is wrong, as bash does not consider everything after `#` as a comment and running the script can lead to disastrous results as it would remove the file package, which is somehow a dependency for essential packages and removing it can break the system.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to owning repo.
