### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ChendrayanV** [Microsoft/vscode#7803]
- VSCode Version: 1.3.0 Insider 
- OS Version: Windows 10 

using module is not supported
Toggle Output option is missing in view menu

**Comment by sandy081** [comment]
@ChendrayanV Output menu option is moved under View->Views section. We are discussing to get this back to main section.

May I know what do you mean by using module is not supported?

Thanks

**Comment by ChendrayanV** [comment]
Thanks - It will be good if we have it in main section. Using Module is for PowerShell Extension -  I will post it over there!
