### ISSUE TITLE
wish search bar regexp include more advanced features

### ISSUE THREAD

**Issue by pangjunpeng** [microsoft/vscode#78031]
Today I want to change all the **snake_case** variables in the code to **camelCase**
The online search method says you can use `_([a-z])`，then replace `\U$1`，
But the result are in unexpect

then i download the notepad++，it's replace is so excellent
it solved my needs

i really like vscode，so i wish increase search regexp features, 
English is not good, please forgive me
thanks

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/12185

**Comment by pangjunpeng** [comment]
thanks
