### ISSUE TITLE
Clear Simple Mac Shortcuts

### ISSUE THREAD

**Issue by dbnex14** [microsoft/vscode#78044]
Can you provide proper information about shortcuts for Mac please.  It is annoying to see this desinforming shortcuts showing on Mac machines for VS Code.

For example, F5 - start debugging is what menu shows in VSC but F5 actually starts Voice Over, not debugging.  I know Mac does not respect F keys but then make simple one-hand shortcuts and show them in VSCode for Mac.

I also know I can override Mac to follow F keys but that disables Mac functionality, i.e Volume Up or Volume Down needs to be used with Fn+F11/Fn+F12 which what most people dont want to fudge with.

Considering the maturity and popularity of VSC, I'd say it is time to finally address this annoyance with VSC.

**Comment by rebornix** [comment]
> F5 - start debugging is what menu shows in VSC but F5 actually starts Voice Over, not debugging

it seems it's bind to cmd+f5

<img width="780" alt="image" src="https://user-images.githubusercontent.com/876920/62022284-67634500-b180-11e9-96f1-a470a9db1f39.png">

**Comment by dbnex14** [comment]
> > F5 - start debugging is what menu shows in VSC but F5 actually starts Voice Over, not debugging
> 
> it seems it's bind to cmd+f5
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/876920/62022284-67634500-b180-11e9-96f1-a470a9db1f39.png">

Read before you reply with stupid comment and ask for more info please.
you can clearly open your own VSC on your mac and show this screenshot instead of that and figure out of that what the problem is, cant you???

<img width="1029" alt="Screen Shot 2019-08-02 at 18 56 22" src="https://user-images.githubusercontent.com/8755679/62405830-6acb4780-b557-11e9-8302-9e100f30cbfa.png">

**Comment by rebornix** [comment]
@dbnex14 what I'm trying to figure out is checking what's the default keybinding for Open Voice Over in your system. If it's set to F5, then it will definitely override VS Code's keybindings. By default, on macOS, turning on Voice Over is Cmd+F5 and it doesn't conflict with F5 from VS Code.

I don't doubt that F5 is assigned to Start Debugging on your machine but to figure out why this happens, we need to know why it triggers Voice Over, and if it's done by the OS.
