### ISSUE TITLE
External powershell opening instead of integrated terminal

### ISSUE THREAD

**Issue by mscientist18** [microsoft/vscode#78040]
- VSCode Version: 1.36.1
- OS Version: Windows 10 version 18362.364

Steps to Reproduce:

1.open terminal using ctrl+`
2.integrated terminal opens and halts then external powershell opens, if i close external powershell it displays "The terminal process terminated with exit code: 3221225786".

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
