### ISSUE TITLE
The shortcut key of adjust the Terminal size.

### ISSUE THREAD

**Issue by unihon** [microsoft/vscode#78057]
`workbench.action.increaseViewSize` and `workbench.action.decreaseViewSize` can adjust the size of **View editor**.  
But **Terminal panel**  can only adjust the size by `workbench.action.toggleMaximizedPanel`.

I look forward to enhancing the ability to adjust the size of the terminal.

**Comment by unihon** [comment]
Is there a function of fold\unfold the all panel header of side bar?

**Comment by Tyriar** [comment]
There are terminal-specific commands to resize it: 
![image](https://user-images.githubusercontent.com/2193314/62082438-9f629a80-b209-11e9-9f21-b7ae6d0c1b73.png)

**Comment by unihon** [comment]
This is not what I want to express.
Look at the picture below.

![show](https://user-images.githubusercontent.com/42078581/62099843-f4fa7e00-b2c1-11e9-86e0-c842ff70aeae.png)

**Comment by unihon** [comment]
This is not what I want to express.
Look at the picture below.

![show](https://user-images.githubusercontent.com/42078581/62100512-95ea3880-b2c4-11e9-9524-93be87344767.png)

Can achieve this purpose by `workbench.action.increaseViewSize` and `workbench.action.decreaseViewSize`, but that just can adjust the size of  **current view editor**.
And when focus on termianl, It will can't adjust the size between **view editor** and **terminal**.

**Comment by Tyriar** [comment]
@unihon in insiders (and the upcoming version of vscode) will resize the panel when using resize up/down

**Comment by unihon** [comment]
@Tyriar  Good!
