### ISSUE TITLE
the debug function can't work well

### ISSUE THREAD

**Issue by leewwe** [microsoft/vscode#78056]
Issue Type: <b>Bug</b>

When I want to "#include" something, it didn't work.
I have added the right include path and files, but the program don't use it when compile the source code.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2835)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.55GB (4.87GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
matlab-formatter|Aff|2.4.12
code-gnu-global|aus|0.2.2
language-gas-x86|bas|0.0.1
vscode-language-pack-zh-hans|MS-|1.37.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
vscode-leetcode|she|0.15.2
vscode-icons|vsc|8.8.0
HCL|who|0.0.5

</details>

**Comment by rebornix** [comment]
@leewwe please file issue against the c++ extension you are using to start investigation.
