### ISSUE TITLE
Add shortcut command for show type/signature

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7805]
I want to show the type/signature of an identifier, like when hovering over an identifier, but instead by pressing a keyboard shortcut. Is this possible?

**Comment by tht13** [comment]
Is `ctrl+k ctrl+i` what you're looking for? I'm on the insiders build so it could be a new shortcut.

**Comment by OliverJAsh** [comment]
Exactly, thanks! Do you know the name of the command?

**Comment by tht13** [comment]
`editor.action.showHover`

**Comment by dbaeumer** [comment]
@OliverJAsh OK to close ?

**Comment by OliverJAsh** [comment]
Yup thanks

**Comment by dbaeumer** [comment]
Closing.
