### ISSUE TITLE
Incorrect cursor position

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#78058]
Issue Type: <b>Bug</b>

When editing in VS Code, the cursor position is often incorrectly shifted to the right. For example, in the screenshots below, it first shows the visual location of the cursor, while in the second the location of the typed character ("x") is one character to the left of the cursor location.

![Screenshot 2019-07-28 at 11 01 03 AM](https://user-images.githubusercontent.com/81476/62009672-8d103000-b127-11e9-91c9-e8a9edd05b1e.png)

![Screenshot 2019-07-28 at 11 01 19 AM](https://user-images.githubusercontent.com/81476/62009670-87b2e580-b127-11e9-8889-e5c48a1a20d4.png)

It appears to be a partial shift, as is seen in the screenshot below, where the cursor appears in the middle of the letter.

![image](https://user-images.githubusercontent.com/81476/62009699-de202400-b127-11e9-8c7b-616d22ce9162.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.19.34-04457-g5b63d4390e96
Remote OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|4.84GB (3.43GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: pytorch-gpu.us-west1-b.model-development|
|OS|Linux x64 4.9.0-9-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (4 x 2200)|
|Memory (System)|14.69GB (9.09GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.13
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@fonnesbeck have you ever zoom the editor or workbench?

**Comment by fonnesbeck** [comment]
Yes, this is at zoom level 1. Is that the issue?

**Comment by alexandrudima** [comment]
@fonnesbeck What linux distribution are you using? Does this reproduce with the default settings and when disabling all extensions ? Did you touch in any way our CSS?

You can workaround by setting `editor.disableMonospaceOptimizations`, but I would like to understand what is causing it and to reproduce...

**Comment by fonnesbeck** [comment]
This is Debian (Slim). I did not touch any CSS, and I do not have many extensions. The next time it occurs, I will try disabling them (it does not appear to be occurring right now).

**Comment by alexandrudima** [comment]
Let's track in #77817
