### ISSUE TITLE
PyCharm-like go-to definition/definition look up.

### ISSUE THREAD

**Issue by AndrewVailcross** [microsoft/vscode#78053]
Will there ever be a decent PyCharm-like go to definition/documentation/reference feature?

Seriosly, it seems the kind of feature that should be there by default, but even with some extentons VS code doesn't show definitions of simple core components, such as "import" and "while", not to mention modules from outside libraries. 

You've done a great job at creating lightweight and elegant-looking IDE, but why there must be so much _**f*ckery**_ to set this thing work with definitions, autocompletions and interpreters?
It seems only logical hat every IDE must have a feature to look up for the use of modules and snippets of code, as well as be able to autocomplete typing.

Without it process of work really gets frustrating.

https://www.jetbrains.com/help/pycharm/viewing-reference-information.html

**Comment by rebornix** [comment]
We do support code navigation https://code.visualstudio.com/docs/editor/editingevolved

**Comment by SSJ9899TDylan** [comment]
Yeet



Sent from myMail for iOS


Monday, 29 July 2019, 2:36 pm +1000 from notifications@github.com  <notifications@github.com>:
