### ISSUE TITLE
Comment background 

### ISSUE THREAD

**Issue by metrocoding** [microsoft/vscode#78054]
there is a feature that i like in **visual studio** and i can't find it in **vs-code**.

- Defining background color for comments.<br>

>  just like below black background with green text color.<br>

![Annotation 2019-07-28 134310](https://user-images.githubusercontent.com/46874334/62004708-ba67d880-b13d-11e9-9bb2-35e2353d9be1.jpg)

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/3429
