### ISSUE TITLE
Test webview.toWebviewResource api proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#78050]
Test for #76489

- [x] Windows @deepak1556
- [x] Linux @rebornix 
- [x] Mac @sandy081

Complexity: 4

**Overview**
There are two new proposed properties on the `Webview` object:

- `webview.toWebviewResource(resource)` — Converts `resource` from a file resource uri to a uri that can be used in webviews to load local content

- `webview.cspSource` —  Content security policy root for local resources. 

Test using these two apis to load local resources inside the webview in both desktop and web versions of vs code. You can use the webview sample as a starting point: https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample

**Comment by sandy081** [comment]
@mjbvz Looks like these APIs need some internal knowledge about web views and how they are implemented in web. 

I am sorry that I do not understand how to use these APIs and test. It would be great if you can provide some sample and how to use it and why it is needed.

**Comment by rebornix** [comment]
This is how I test this feature

* Clone https://github.com/microsoft/vscode-extension-samples/tree/rebornix/78050/webview-sample 
* Open the folder and start debugging in local VS Code and debug, run Cat Coding command
* Open the folder and start debugging in web , run Cat Coding command

In both cases, you should be able to see the gif. The code change I made is in https://github.com/microsoft/vscode-extension-samples/commit/833f574ff9d42e8ef88bd12836842a533610bc04 , without `toWebviewResource` and `cspSource` , the gif resource won't load properly.

**Comment by sandy081** [comment]
@deepak1556 I forgot to see the platform I was assigned and tested in Mac. Can you please test this in Windows?
