### ISSUE TITLE
所有插件经常突然失效，需要重启软件才行

### ISSUE THREAD

**Issue by hjhwel** [microsoft/vscode#78069]
Issue Type: <b>Performance Issue</b>

使用一段时间后，就会有几率出现，

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	  9584	code main
    1	    60	  4024	   window (问题报告程序)
    0	     9	  7312	   electron-crash-reporter
    0	    60	 11676	   shared-process
    0	   309	 12572	   window (casedetail.wxml - hjhTest - Visual Studio Code [管理员])
   13	   129	  7048	     extensionHost
    0	    21	  2684	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=7048
    0	   122	 16188	       electron_node tsserver.js 
    0	    23	   228	         electron_node typingsInstaller.js typesMap.js 
    0	    18	 16252	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=7048
    0	    34	 11136	     searchService
    0	    11	 12808	     watcherService 
    0	     4	 15056	       console-window-host (Windows internal process)
    0	   175	 15132	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (casedetail.wxml - hjhTest - Visual Studio Code [管理员])
|    Folder (hjhTest): 725 files
|      File types: wxss(186) js(167) json(156) wxml(143) png(58) gitignore(4)
|                  xml(4) jpg(3) ts(2) http(1)
|      Conf files: jsconfig.json(2) settings.json(2);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.6.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.9.1
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-browser-sync|jas|1.3.1
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.37.0
korofileheader|OBK|3.9.4
open-html-in-browser|pea|1.2.0
minapp-vscode|qiu|2.1.1
css-auto-prefix|spo|0.1.7

</details>

**Comment by Xianbei233** [comment]
same issue, after coding on vscode for a while, all extension will lose effect and need to relauch the vscode

**Comment by hjhwel** [comment]
我更新了自己电脑的内存条，从8G升级到了16g,已经没有这个问题了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 先辈 <notifications@github.com>
发送时间: Monday, August 19, 2019 2:53:42 PM
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: 扬眉剑出鞘 <hjhlovewel@outlook.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode] 所有插件经常突然失效，需要重启软件才行 (#78069)


same issue, after coding on vscode for a while, all extension will lose effect and need to relauch the vscode

―

**Comment by Xianbei233** [comment]
@hjhwel 可我已经是16g了，难不成这个问题是内存不足引起的？

**Comment by hjhwel** [comment]
也有可能是插件冲突了，把一些插件重装下试试，我是直接重装了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 先辈 <notifications@github.com>
发送时间: Monday, August 19, 2019 3:02:40 PM
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: 扬眉剑出鞘 <hjhlovewel@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/vscode] 所有插件经常突然失效，需要重启软件才行 (#78069)


@hjhwel<https://github.com/hjhwel> 可我已经是16g了，难不成这个问题是内存不足引起的？

―
