### ISSUE TITLE
[TypeScript]: Need to (F12/Goto definition) twice on destructured imports to get to actual definition

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#7806]
- VSCode Version: 1.2.1
- OS Version: Windows 8.1 x64

Steps to Reproduce:

1. Import a module member using destructuring syntax
2. F12 / Goto definition on the destructured import symbol

The first F12 takes you to the destructuring expression. The second F12 then takes you to the actual definition

See attached gif for an example

![destructured_import](https://cloud.githubusercontent.com/assets/563860/16146848/8e0726d2-34c3-11e6-9ea2-c2f5b4c8e9c9.gif)

Possibly also related is that tooltips on destructured import symbols show the import statement instead of its definition

![destructured_import_tip](https://cloud.githubusercontent.com/assets/563860/16146886/c002207e-34c3-11e6-88f0-c3c2685cfc30.png)

Compare with non-destructured version

![nondestructured_import_tip](https://cloud.githubusercontent.com/assets/563860/16146921/e35c5c6a-34c3-11e6-8fed-ab17b31b3c09.png)

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9278
