### ISSUE TITLE
multiple extensions scheme(extension profiles) 🌈

### ISSUE THREAD

**Issue by xianghongai** [microsoft/vscode#78065]
Like Firefox, `firefox -p`, we can configure multiple extensions scheme.

disable, enable, disable, enable... not elegant~

![l](https://user-images.githubusercontent.com/2075006/62017825-b8a81e80-b1ea-11e9-8099-23e26cb1423a.png)

**Comment by sandy081** [comment]
@xianghongai I do not understand what you are asking for. Can you please elaborate on multiple schemes?

**Comment by xianghongai** [comment]
Like keymaps and Color Theme,
Extensions can support multiple different environments, such as web development, java development, .md document editing..., 
different environments, different extensions;

**Comment by sandy081** [comment]
I see are you talking about extension profiles?

**Comment by xianghongai** [comment]
![yes](https://user-images.githubusercontent.com/2075006/62380934-eab7d880-b57c-11e9-9972-7db6eb51906f.gif)
