### ISSUE TITLE
[Extensions View] `@id` is missing from input autocomplete

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#78062]

**Comment by jrieken** [comment]
@sandy081 verified, but sorting is questionable...

<img width="247" alt="Screenshot 2019-07-30 at 15 37 53" src="https://user-images.githubusercontent.com/1794099/62133962-005ca200-b2e0-11e9-90f7-e7c5b064bd85.png">

**Comment by sandy081** [comment]
Fixed sorting. Please check in latest build

![image](https://user-images.githubusercontent.com/10746682/62149664-e2139800-b319-11e9-8c13-b3f95eef2bc9.png)
