### ISSUE TITLE
An unwanted linebreak after opening integrated terminal with fishshell

### ISSUE THREAD

**Issue by lonr** [microsoft/vscode#78064]
- VSCode Version: 1.36.1
- OS Version: Linux  5.1.19-300 Fedora 30
- fish, version 3.0.2

Steps to Reproduce:

1. set fish as the default shell
2. open integrated terminal

There is a blank line ahead of fish's prompt.(with a down-left arrow rendered)   
Then if I split the terminal, the new(right) one is normal.
Other shells seem to be fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lonr** [comment]
![image](https://user-images.githubusercontent.com/4436034/62176609-c7bad800-b374-11e9-81bd-9a7e1d5599b8.png)

**Comment by Tyriar** [comment]
In the first terminal can you select all, copy and then paste in an editor to see what the content is? I suspect fish is printing spaces or something at the end of the first line which get reflowed when resized, in which case this would be as designed.

**Comment by lonr** [comment]
This issue also happens in Tilix(a terminial emu), don't bother.
