### ISSUE TITLE
Resizing the editor

### ISSUE THREAD

**Issue by Brandolfdesigns** [microsoft/vscode#78074]
Hello, 

While resizing the editor bar between the 2 groups it either gets stuck on resizing to the left without clicking on it, like whenever the mouse is moved, and it doesnt resize to the right. Need to double click on it so it goes back to the center, and also having hard time for it to stop while resizing it

**Comment by joaomoreno** [comment]
Can you show me what you mean with a screen recording?

**Comment by Brandolfdesigns** [comment]
Hello, This is a video link ( youtube ) https://youtu.be/HGHWe2F7sZs of the issue.

Note: I wasn't clicking while moving the mouse left to right. until you can see the cursor changes this is when i was clicking.

**Comment by joaomoreno** [comment]
@mjbvz This is the webview event stealing issue. I thought this was fixed? Maybe only on insiders?

**Comment by Brandolfdesigns** [comment]
Thank you so much, it has been fixed <3

**Comment by Brandolfdesigns** [comment]
Hello, the issue was back today same problem. Any updates?

**Comment by mjbvz** [comment]
Are you sure this reproduces in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
