### ISSUE TITLE
Conditional Tasks

### ISSUE THREAD

**Issue by joelmagner** [microsoft/vscode#78075]
Feature request: Conditional Tasks.

Scenario

### Run _"Build Company SW"_ Task 
>    Microsoft
       Apple
       Oracle

If I pick **Microsoft** - a list with:
>    VS Code
      VS
      Windows

Should appear.

If I pick **Apple** - a list with:
>    iOS
       Os X

should appear.

If I pick **Oracle** - a list with:
>    Java

should appear.

Now imagine that I can't do all of this from one task...

What I'll end up with (when having many customers) is a list that is so long that is virtually impossible to see any other tasks and hard its hard to filter through. 
This is just for building. Other common tasks for companies that use VS Code are:  
* run unittest for customer
* run analyze for customer
* run lint for customer
* upload to customer server 
* etc...

So imagine trying to use tasks to filter through all of these... (Rel: ["Recently Used" Option For Sublevel Tasks](https://github.com/microsoft/vscode/issues/78422)

If this feature request was implemented, you could nest all of these into **one** task, or **one** per usecase i.e. one for builds, one for lint and so on. That would mean that I'd have a clean interface for one customer. Especially if I build the SW for that customer often, then its just ctrl+shift+b -> enter -> enter.

As it is now, its a long list with over 100 tasks (build, lint etc for each customer) - this really destroys the purpose of tasks IMO - it is faster to just type out the arguments in the terminal rather than looking through a long list with 100 entries trying to find what you are looking for.

- Run "Build Customer SW" Task 
- - Choose "Microsoft"
-  - - Choose between "VS Code", "VS", "Windows" 

I then can pass these args to the script: `.\myBuildScript.ext Microsoft VS Code`

The problem is that as of now: another customer (or selection) may not have the same options (VS Code, VS, Windows), which is why this fails. **DependsOn** doesn't work for this scenario. 

Please implement!

A more complete example (GUI-isch):

```
     "inputs"        "Options"
------------------------------------------------------------
Run Build Customer SW Task.
     - Customer1   
                 - [v954, 
                    v952]

     - Customer2   
                 - [v300,
                    v301, 
                    v302]

     - Customer3   
                 - [v102, 
                    v103]
```

Tasks.json example to show current limitations

```
"tasks": [
    {
      "label": "Build Customer",
      "type": "shell",
      "command": ".\\AutoBuild.bat",
      "options": {
        "shell": {
          "executable": "powershell.exe"
        },
        "cwd": "${workspaceFolder}",
      },
      "isBackground": false,
      "args": [
        "${input:customerName}",
        "${input:buildWhat}"
      ], 
      "group": "build",
      "problemMatcher": []
    }
],
  "inputs": [
    {
      "type": "pickString",
      "id":"customerName",
      "options": [
        "customer1",
        "customer2",
        "customer3"
      ],
      "description": "📦 Select Customer...",
      "default": "customer1"
    },
    {
      "type": "pickString",
      "id":"buildWhat",
      "description": "🗳 Select SW version",
      "options": [
        "v102", //there is no way to show these options conditionally based on what customer I chose
        "v103"
      ],
      "default": ""
    },
  ]```

**Comment by alexr00** [comment]
Could you use the [command input type](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) to accomplish this? 
Once you want conditional actions in your task you start to drift out of realm of tasks and into commands.

**Comment by joelmagner** [comment]
Using **command input type** will not work for this. 
Lets take an even more generic example:

### Run _"Build Company SW"_ Task
>    Microsoft
       Apple
       Oracle

If I pick **Microsoft** - a list with:
>    VS Code
      VS
      Windows

Should appear.

If I pick **Apple** - a list with:
>    iOS
       Os X

should appear.

If I pick **Oracle** - a list with:
>    Java

should appear.

Now imagine that i can't do all of this from one task...

What i'll end up with (when having over 100 customers) is a list that is so long that is virtually impossible to see any other task and hard to filter throughs. This is just for building. Other common tasks for companies that use VS Code are:  
* run unittest for customer
* run analyze for customer
* run lint for customer
* upload to customer server 
* etc...

If this feature request was implemented, you could nest all of these into **one** task, or **one** per usecase i.e. one for builds, one for lint and so on...
Otherwise as it is now, its a long list with over 100 tasks - this really destroys the purpose of tasks IMO - it is faster to just type out the arguments in the terminal rather than looking through a long list with 100 entries trying to find what you are looking for.

**Comment by yeggles** [comment]
I had tried to use nested inputs to do this very thing but it doesn't appear to work.  I also tried to create inputs as tasks hoping that I could avoid the task showing up in the "Run Task..." menu but it didn't work either.  :(

Example tasks.json:
{
	"version": "2.0.0",
	"tasks":
	[
		{
			"label": "Start",
			"command": "${input:Start ${input:App Options}}",
			"type": "process",
			"dependsOn":
			[
				"${input:Initialize Terminal}"
			],
			"group": "test"
		}
	]
	"inputs":
	[
		{
			"id": "App Options",
			"description": "Select which app to start",
			"type": "pickString",
			"options":
			[
				"App 1",
				"App 2"
			]
		},
		{
			"id": "Start App 1",
			"type": "command",
			"command": "./bin/app 1 <app 1 flags>"
		},
		{
			"id": "Start App 2",
			"type": "command",
			"command": "./bin/app 1 <app 2 flags>"
		},
		{
			"id": "Initialize Terminal",
			"type": "command",
			"command": "export SOME_VARIABLE='some/path'"
		}
	]
}

**Comment by yeggles** [comment]
Something like this could be useful if implementing nesting is out of the picture:

`			"id": "App Options",
			"description": "Select which app to start",
			"type": "pickCase",
			"options":
			[
				"App 1": "./bin/app 1 <app 1 flags>",
				"App 2": "./bin/app 1 <app 2 flags>"
			]`

**Comment by alexr00** [comment]
When you have a lot of conditions like this you should consider using a command instead of a task. If you want to still tie into the task system, you can write a command (lets call it productChooser.taskArgs) that returns a string (ex. it returns "Microsoft Windows") then you can run it in a task:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"command": "runProductAction.bat ${input:chooseProduct}",
			"label": "Run analyze for customer",
			"problemMatcher": []
		}
	],
	"inputs": [
		{
			"id": "chooseProduct",
			"type": "command",
			"command": "productChooser.taskArgs"
		}
	]
}
```

**Comment by yeggles** [comment]
My VSCode doesn't recognize "command": "productChooser.taskArgs"

**Comment by joelmagner** [comment]
> When you have a lot of conditions like this you should consider using a command instead of a task. Tasks should not take the place of a scripting language :) If you want to still tie into the task system, you can write a command (lets call it productChooser.taskArgs) that returns a string (ex. it returns "Microsoft Windows") then you can run it in a task:
> 
> ```
> {
> 	"version": "2.0.0",
> 	"tasks": [
> 		{
> 			"type": "shell",
> 			"command": "runProductAction.bat ${input:chooseProduct}",
> 			"label": "Run analyze for customer",
> 			"problemMatcher": []
> 		}
> 	],
> 	"inputs": [
> 		{
> 			"id": "chooseProduct",
> 			"type": "command",
> 			"command": "productChooser.taskArgs"
> 		}
> 	]
> }
> ```

Can you please provide a working example? I'm afraid I don't grasp the gist of it.

**Comment by alexr00** [comment]
I am suggesting that you write a new command, then use that command in your task. There is an example you can see here using debug configurations (you need to scroll down a bit): https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
