### ISSUE TITLE
Debug hover respect editor.wordSeparators setting

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#78073]
- VSCode Version: 1.36.1
- OS Version: win10

Steps to Reproduce:
I am write a common LISP dialectic language addin for VSCODE,  and find that the editor.wordSeparators setting can't work for hover on a symbol when debugging. In LISP language the variable name can contains * ? - and so on.

1. add setting "editor.wordSeparators": "&#^()[]|;'\".",
2. launch the mock debug
3. open a MD file which contains a word \*test\*
4. when debugger is stopped at breakpoints, hover mouse on the word \*test\*
5. In the runtime "evaluate" call back the input expression is "test" instead of "\*test\*"

Does this issue occur when all extensions are disabled?: Yes

**Comment by whlkw** [comment]
@isidorn Could you help on this issue?

**Comment by isidorn** [comment]
This is currently not implemented.
I am leaving it open as a feature request, and assigning to backlog since it is not on our current plan.

**Comment by whlkw** [comment]
Thanks for your conformation!

**Comment by msweeney1999** [comment]
Please fix this issue.   The hover should respect the editor.wordSeparators  setting.
