### ISSUE TITLE
Set variable should show an error in a nice way

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7807]
From @weinand 

<img width="662" alt="screen shot 2016-06-17 at 12 34 51" src="https://cloud.githubusercontent.com/assets/1926584/16148143/ed2d3f7a-3487-11e6-9677-a7a591be27fe.png">

**Comment by isidorn** [comment]
@weinand please tune the error message coming from the adapter so it nicely fits in the error box - looks decent thus far though

**Comment by weinand** [comment]
@isidorn I've tuned the error message to be short.

One issue which the variables view shares with the explorer: if the error box is open the view can be scrolled with the mouse wheel which detaches the error box from the item being edited.

**Comment by isidorn** [comment]
@weinand I think we are good for that if no user noticed the issue in the explorer for the last 2 years :)
