### ISSUE TITLE
Markdown HR (---, ***, or ___) in hover is not rendered correctly

### ISSUE THREAD

**Issue by Benjamin-Lee** [microsoft/vscode#78071]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14.5

 
Steps to Reproduce:

1. Create a Python docstring with:

```
def foo(bar):
    """
    One line goes here

    ***
    Warning:

    This is a bad idea!
    ***

    Some more content goes here.
    """
```
2. Hover over it.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/13618205/62026825-15371980-b1aa-11e9-915f-78c6c1a65e3e.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Does Markdown generally work in that scenario? Eg. does `Hello *World*` make it bold?

**Comment by Benjamin-Lee** [comment]
Yes, sorry for not making that clear.

**Comment by joaomoreno** [comment]
This seems to work fine for TypeScript:

<img width="963" alt="Screenshot 2019-07-29 at 17 23 17" src="https://user-images.githubusercontent.com/22350/62060539-9da6d000-b225-11e9-8220-3ce2794ffd6e.png">

Is this maybe a Python extension issue?
