### ISSUE TITLE
Window has crashed

### ISSUE THREAD

**Issue by ruslan-makeev** [microsoft/vscode#78079]
WIndow has crashed keeps poping in as soon as i touch any file. Have to shut the editor. Nothing helps. Had normal version of VSC code before for a month with no issues. Than suddenly that error occured. Reinstalled the VSC with no luck. Tried the insiders version... worked for a week only. Same error. Had to swith to Atom to keep coding. Please help, I love VSC.

**Comment by xorscode** [comment]
I'm having the same issue.  Used VS code for 3 years same project, no issues.  Suddenly every time I try to open the console, "The window has crashed" error message.

**Comment by deepak1556** [comment]
@ruslan-makeev @xorscode can you test with the latest exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 and see if its any better ? Thanks!

**Comment by xorscode** [comment]
Quick update, @deepak1556 

Removing 32 bit VS Code and installing 64 bit VS Code has fixed the problem.
