### ISSUE TITLE
PHP syntax highlighting issue with here strings

### ISSUE THREAD

**Issue by smx-smx** [microsoft/vscode#78078]
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/1978844/62037132-7d5e1d80-b1f3-11e9-8220-362c73a1d669.png)

![image](https://user-images.githubusercontent.com/1978844/62037190-9b2b8280-b1f3-11e9-8113-7a0dda7fbfda.png)

Does this issue occur when all extensions are disabled?: Yes

If EOS; is placed at the beginning of the line (without spacing), syntax highlighting works as expected.
However this is not required and the PHP code shown in the first picture is valid.

**Comment by alexr00** [comment]
This is an issue with the php grammar from https://github.com/atom/language-php.

**Comment by smx-smx** [comment]
Fixed upstream and working in VSCode, closing

![screenshot](https://user-images.githubusercontent.com/1978844/64653128-ef966480-d425-11e9-8998-a3e62ee2c06b.png)

https://github.com/atom/language-php/commit/0efbd42e73b52347f95ac5f00c9f288ed4958832

**Comment by alexr00** [comment]
Thanks for verifying!
