### ISSUE TITLE
 Smart select doesn't consistently stops before and after quotes

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#78084]
- VSCode Version: 1.36.1
- OS Version: Windows 10

Smart select doesn't consistently stops before and after quotes.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
