### ISSUE TITLE
Cursor become fat and blinking

### ISSUE THREAD

**Issue by OsmanDhaqane** [microsoft/vscode#78083]
Issue Type: <b>Performance Issue</b>

I can't write code unless I hit the insert key, and again if i try to use short cuts like ctrl + c or x the cursor goes back to the same problem. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (25.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    96	  8708	code main
    0	   170	  1888	   window (script.js - starter - Visual Studio Code)
    0	   166	  2920	     extensionHost
    0	    31	   744	       electron_node eslintServer.js 
    0	    88	  5128	       electron_node tsserver.js 
    0	    59	 19320	         electron_node typingsInstaller.js typesMap.js 
    0	    74	 12184	       "C:\Users\roobl.000\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\roobl.000\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=2920
    0	    48	 19076	       electron_node server.js 
    0	    36	  7660	     searchService
    0	    11	 20072	     watcherService 
    0	    11	 20112	       console-window-host (Windows internal process)
    0	    81	  2228	   gpu-process
    0	    72	  3904	   shared-process
    0	    13	 13080	   electron-crash-reporter
    1	    69	 18692	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (script.js - starter - Visual Studio Code)
|    Folder (starter): 3 files
|      File types: html(1) js(1) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-development|aal|0.0.2
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-javascript-snippet-pack|aka|0.1.5
vscode-standardjs-snippets|cap|0.8.5
npm-intellisense|chr|1.3.0
vscode-css-modules|cli|0.2.3
vscode-javascript-snippets|cod|1.0.0
bracket-pair-colorizer|Coe|1.0.61
crossplatform-startup|cro|0.0.1
vscode-markdownlint|Dav|0.29.0
vscode-eslint|dba|1.9.0
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
mithril-emmet|Fal|0.7.1
auto-rename-tag|for|0.1.0
vscode-atom-javascript-snippet|glu|0.2.1
beautify|Hoo|1.5.0
html-tag-wrapper|hwe|0.2.3
vscode-language-babel|mgm|0.0.23
code-beautifier|mic|2.3.3
mssql|ms-|1.6.0
anaconda-extension-pack|ms-|1.0.1
atom-keybindings|ms-|3.0.6
js-atom-grammar|ms-|0.1.14
debugger-for-chrome|msj|4.11.6
JavaScriptSnippets|nat|0.2.0
elmmet|nec|1.0.1
prettier-standard-vscode|num|0.5.0
prettier-vscode-with-tabs|pas|1.1.0
vscode-yaml|red|0.4.1
LiveServer|rit|5.6.1
nativeemmet|Sau|0.0.8
vscode-javascript-booster|sbu|0.11.0
hyper-javascript-snippets|t7y|2.1.0
vscode-jss-snippets|vis|0.2.2
vscodeintellicode|Vis|1.1.8
vim|vsc|1.9.0
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by OsmanDhaqane** [comment]
[index.html - starter - Visual Studio Code 2019-07-29 13-21-57.zip](https://github.com/microsoft/vscode/files/3441792/index.html.-.starter.-.Visual.Studio.Code.2019-07-29.13-21-57.zip)

**Comment by IllusionMH** [comment]
Is is reproducible without extensions (especially Vim)?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by OsmanDhaqane** [comment]
Thank you I removed the Vim extension, and everything works properly now.
