### ISSUE TITLE
Preview jumps to top when scrolling

### ISSUE THREAD

**Issue by volker-wd** [microsoft/vscode#78089]
- VSCode Version: 1.31.0
- OS Version: Win 10

Steps to Reproduce:

1. Open (or create) a "long" adoc file (500+ lines).
2. Insert three include directives (include::filename.adoc[]) at different locations in the file.
3. Save the file.
4. Open the preview.
5. Keep the mouse in the "file" section (not in the preview).
6. Scroll from top to bottom (using the mouse wheel).

> Preview scrolls accordingly but suddenly it jumps back to the top.

Does this issue occur when all extensions are disabled?: Don't know

**Comment by mjbvz** [comment]
What is an `adoc` file? Is this for markdown?

**Comment by volker-wd** [comment]
Hi mjbvz, thanks for replying. 
Yes ASCIIDOC (which is a markup language just as markdown) uses the file extension adoc. I'm using VSC to write documentation.

**Comment by mjbvz** [comment]
File this against the asciidoc extension
