### ISSUE TITLE
Changing workspaces qucikly shows the activity bar margin

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#78088]
1. Have the activity bar hidden via user setting
	`"workbench.activityBar.visible": false`
2. Change workspace -> notice the activity bar quickly showing (without any icons) before appearing again

It was not behaving like this 2 weeks ago when I went on vacation. Thus I think this is a regression.

![activity](https://user-images.githubusercontent.com/1926584/62048044-26b10d80-b20c-11e9-8114-da7011707968.gif)

**Comment by usernamehw** [comment]
Looks like another grid problem
```json
"workbench.useExperimentalGridLayout": false,
```
