### ISSUE TITLE
"Add all missing members option" is not working

### ISSUE THREAD

**Issue by nshenoy06** [microsoft/vscode#78080]
Issue Type: <b>Bug</b>

When you right click on a variable /xpath it displays an option saying "Add all missing members" which is not working currently

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
Is this maybe an issue with a specific extension?
