### ISSUE TITLE
Running/configuring tasks hangs when gulpfile has a top level watch()

### ISSUE THREAD

**Issue by svilenmarkov** [microsoft/vscode#78082]
Issue Type: <b>Bug</b>

### Steps to reproduce:
* Create a new directory and have it open in vscode
* Have gulp available either globally or locally (`npm install --save-dev gulp`)
* Create a gulpfile.js with the following contents: 
```
const { watch } = require('gulp');

watch("*.*", () => {});
```

* Close and re-open vscode
* Try executing any of the task-related commands, for example: **Configure Default Build Task** / **Run Build Task** / **Run Task**

### Result
The commands hang on "Fetching build tasks..."

### Culprit
The built-in Gulp support extension. Disabling it fixes the issue. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
Node version: 10.6.0
Gulp version: 4.0.2
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.83GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.5
php-docblocker|nei|2.0.1

(2 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
To find gulp tasks we run `gulp.cmd` --tasks-simple. This is what hangs. We should detect that finding gulp tasks is too slow and offer to add the `"gulp.autoDetect": "off",` setting.

**Comment by alexr00** [comment]
I decided to tackle this in core instead of in the gulp extension. As a result, it can't suggest the specific gulp auto detect setting. However, the notification says that the extension may have a setting and offers the global tasks auto detection setting.

**Comment by alexr00** [comment]
Test plan item: https://github.com/microsoft/vscode/issues/83437
