### ISSUE TITLE
VSCodeQuickStart

### ISSUE THREAD

**Issue by sunnyvats** [microsoft/vscode#78090]
Issue Type: <b>Feature Request</b>

why i am not able to delete the folder in which i am storing the project?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by joaomoreno** [comment]
Can you be more specific? What folder are you exactly trying to delete?

**Comment by sunnyvats** [comment]
Thanks for the concern.
Actually when i am creating a folder for my vscode project and later if i
want to delete the folder in which i have stored my project then i am not
able to delete it.

**Comment by joaomoreno** [comment]
What happens when you try to delete? Please try to be more specific. A screenshot always helps.

**Comment by sunnyvats** [comment]
Actually there was a space at the end of the folder's name and i try to
delete the folder but it won't allowing me to delete it when i tried to
rename it then it was saying folder does not exist but i was able to see
the folder but the content inside the folder were delete as i tried to
delete the folder. Sorry but i can not share the screenshot because i
formatted the drive to delete that folder.

**Comment by joaomoreno** [comment]
Can you still reproduce the issue?

**Comment by sunnyvats** [comment]
yes, i will update you once i will reproduce.

**Comment by joaomoreno** [comment]
Kk let me know.
