### ISSUE TITLE
Cannot start up as root although I specify an alternate user data directory with the --user-data-dir in Ubuntu docker container

### ISSUE THREAD

**Issue by alexsmartens** [microsoft/vscode#78099]
- VSCode Version: 1.36.1-1562627527 (insiders 1.37.0-1564378337)
- OS Version: Ubuntu 18.04 in Docker container

Steps to Reproduce:

1. `code .` produces the following error: 
` You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument. `
2. `code . --user-data-dir="." ` does nothing 

Notes:

* Does this issue occur when all extensions are disabled?: **Yes**;
* **insiders** build has **the same** behaviour;
* similar issue suggestions (#7243, #52732) **did not help**

**Comment by joaomoreno** [comment]
Does _does nothing_ mean it never returns... or it returns immediately? If you add `--verbose`, is there an error?

**Comment by alexsmartens** [comment]
Here is what I see after running `code . --user-data-dir="." --verbose`:

 [41952:0730/131625.898665:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory                                                                                                                                         [41980:0730/131625.932839:ERROR:gl_surface_glx.cc(429)] GLX 1.3 or later is required.                                                                [41980:0730/131625.932879:ERROR:gl_initializer_x11.cc(157)] GLSurfaceGLX::InitializeOneOff failed.                                                   [41980:0730/131625.940820:ERROR:viz_main_impl.cc(236)] Exiting GPU process due to errors during initialization                                       
[main 2019-07-30T13:16:26.053Z] Starting VS Code                                                                                                     
[main 2019-07-30T13:16:26.054Z] from: /usr/share/code/resources/app                                                                                  
[main 2019-07-30T13:16:26.054Z] args: { _: [ '/desktop' ],                                                                                             diff: false,                                                                                                                                         
add: false,                                                                                                                                         
goto: false,                                                                                                                                        
 'new-window': false,                                                                                                                                 
'reuse-window': false,                                                                                                                               
wait: false,                                                                                                                                         
version: false,                                                                                                                                      
help: false,                                                                                                                                         
'list-extensions': false,                                                                                                                            
'show-versions': false,                                                                                                                              
verbose: true,                                                                                                                                       
status: false,                                                                                                                                      
 'prof-startup': false,                                                                                                                              
'disable-extensions': false,                                                                                                                        
'disable-gpu': false,                                                                                                                                logExtensionHostCommunication: false,                                                                                                                'skip-getting-started': false,                                                                                                                       
'skip-release-notes': false,                                                                                                                         
'sticky-quickopen': false,                                                                                                                           
'disable-restore-windows': false,                                                                                                                    'disable-telemetry': false,                                                                                                                          
'disable-updates': false,                                                                                                                            
'disable-crash-reporter': false,                                                                                                                     
'skip-add-to-recently-opened': false,                                                                                                                'unity-launch': false,                                                                                                                              
'open-url': false,                                                                                                                                   
nolazy: false,                                                                                                                                      
issue: false,                                                                                                                                        
'file-write': false,                                                                                                                                 
'file-chmod': false,                                                                                                                                 
'driver-verbose': false,                                                                                                                             
force: false,                                                                                                                                        
'prof-code-loading': false,                                                                                                                          
'user-data-dir': '.' }                                                                                                                             
[main 2019-07-30T13:16:26.056Z] Resolving machine identifier...                                                                                      
[main 2019-07-30T13:16:26.056Z] Resolved machine identifier: 7996181d-5c89-4324-b33f-b482bd7df2ed                                                    
[main 2019-07-30T13:16:26.075Z] update#setState idle                                                                                                 
[main 2019-07-30T13:16:26.078Z] [storage state.vscdb] open(/desktop/User/globalStorage/state.vscdb, retryOnBusy: true)                               
[main 2019-07-30T13:16:26.079Z] lifecycle (main): phase changed (value: 2)                                                                           
[main 2019-07-30T13:16:26.080Z] windowsManager#open                                                                                                  
[41952:0730/131626.129046:ERROR:browser_main_parts.cc(137)] X IO error received (X server probably went away)

**Comment by alexsmartens** [comment]
Just a clarification note, I'm able to run Firefox, PyCharm and everything else that I need.

**Comment by joaomoreno** [comment]
Does the `/desktop/User` path exist in your system?

**Comment by alexsmartens** [comment]
Yes, it does. `/desktop/User` contains `globalStorage` and `workspaceStorage`, both directories are empty

**Comment by joaomoreno** [comment]
Got it. I think your issue is this: 

```
[41952:0730/131626.129046:ERROR:browser_main_parts.cc(137)] X IO error received (X server probably went away)    
```

Do you have an X server in the container?

**Comment by alexsmartens** [comment]
No, I don't have X server in the container.
X server is only installed on my actual Windows machine

**Comment by joaomoreno** [comment]
So... how do you want to launch Code?

**Comment by alexsmartens** [comment]
I run X on my Win machine, set up `DISPLAY` variable in the container and run whatever I need to run

**Comment by joaomoreno** [comment]
Can you run vanilla Electron that way?
