### ISSUE TITLE
Support MSYS2 style of file path (example: /d/Project/xxx.c)

### ISSUE THREAD

**Issue by yetangye** [microsoft/vscode#78097]
I built a C project under MSYS2 use gcc and make, When I tried to debug the built .exe file, VS Code launched the terminal successfully, but inner VS Code, the error below showed:
Can not open “main.c”: Unable to read file (Error: File not found (\d\Projects\foo\main.c))

The debug configuration in launch.json is 

> {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/main.exe",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\usr\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }

Terminal settings in settings.json is:
> {
    "terminal.integrated.shell.windows": "C:\\Users\\tangye\\sirzone\\msys64\\msys2_shell.cmd",
    //"terminal.integrated.shellArgs.windows": ["-defterm", "-mingw64", "-no-start", "-here"]
    "terminal.integrated.shellArgs.windows": ["--login", "-i"],
    "terminal.integrated.env.windows":
    {
        //"MSYSTEM": "MINGW64",
        "MSYSTEM": "MSYS2",
        "CHERE_INVOKING":"1"
    }
}

So I think maybe VS Code should support MSYS2 file path style directly.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/34026
