### ISSUE TITLE
Test DiagnosticTag#Deprecated

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78096]
Refs: https://github.com/microsoft/vscode/issues/56694

- [x] any @sbatten
- [x] any @egamma

Complexity: 3

There is new API to mark a decoration as representing something deprecated. In addition to the normal rendering, the editor shows a strikeout. That that

* the API can be used without enabling proposed API
* the API is proper and documented
* the editor shows a strikeout

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`

**Comment by sbatten** [comment]
API works fine, filed issues as feedback but they can easily be closed as designed.
