### ISSUE TITLE
Finalize onDidExecuteCommand-API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78091]
Remaining work is listed here: https://github.com/microsoft/vscode/issues/1431#issuecomment-514627618. Also, finalise the API

**Comment by jrieken** [comment]
During the API sync concerns about this API have been raised. The following issues have come up:

* commands are at the heart of almost everything and there is potential to wreck the extension host when doing something every time a command is run
* command arguments aren't API, esp. internal objects (like the explorer model) will leak into the extension host setting expectations that we cannot satisfy

/cc @kieferrm 

An alternative to having the `onDidExecuteCommand`-api would be to allow/accept PRs that extend the core of VS Code. Feature requests that would need this API

* marco recording (run commands in sequence) @hedgerh
* keybindings tutor (teach keybinding when a command was run)

**Comment by jrieken** [comment]
I have pushed 21de711cdf that removes the proposed API - as explained in my previous comment. This wasn't an easy decision but there were too many doubts around the usefulness of this API, the performance impact, and accidental leakage of arguments. 

However, the *internal* API is there and we are open to accept features like the "keybindings teacher" or "macro recording" as a core contribution to VS Code.

**Comment by hedgerh** [comment]
No worries.  Thank you for all your help.  I may take a crack at it sometime if I have some time.  Cheers.

**Comment by moshfeu** [comment]
Maybe instead of invoking it for **each** events, a plugin could register to specific events so the callback will be fired only in specific events (PubSub?)

**Comment by ifSchleifenSindAuchSchleifen** [comment]
I have found a method that allows you to add eventListeners/onExecution logic to commands.
As vs code does not allow you to alter existing commands, we have find a workaround. So this guide can be used for any command altering in vs code.

VS code allows you to register an already existing command, and will use the last registration. (This could conflict with other extensions doing the same!)

## Easy guide

We register an existing command, and on execution we follow a `unregister - execute - register` logic. The registered command calls the original command, and so we don't fall into a recursive loop we have to follow this logic.
