### ISSUE TITLE
Drag the selected contents

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#7809]
- VSCode Version: Code1.3.0-insider
- OS Version: Win10
Steps to Reproduce:

1. As the title！

**Comment by dbaeumer** [comment]
@ZCShou which view are you talking about. The explorer, editor, ...

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
