### ISSUE TITLE
Undo Functionality

### ISSUE THREAD

**Issue by DennyScott** [Microsoft/vscode#781]
What is VSCode using for Undo commands? I've searched the source code, but never found anything triggering it specifically. I found a text model interface with undo/redo methods, but nothing more then that.

Is VSCode just relying on the native browsers support for undo? I ask, because I'm building a plugin, that requires calling undo, but can't find a way to call it through vscode. I could build my own stack for something like that, but seems redundant, when it should rely on the same system vscode does.

Cheers.

**Comment by SamVerschueren** [comment]
You can execute every command like this

```js
commands.executeCommand('undo');
```

Search for the available commands in `Code > Preferences > Keyboard Shortcuts`

**Comment by DennyScott** [comment]
Thanks Sam!
