### ISSUE TITLE
Control + Alt eats input without doing anything

### ISSUE THREAD

**Issue by sanboxrunner** [microsoft/vscode#78105]
- VSCode Version: 1.36.1
- OS Version: Windows 10

Steps to Reproduce:

1. Type CONTROL - ALT
2. "Alt" access keys no longer work and any keyboard combo which uses CONTROL+ALT+* no longer work.

Does this issue occur when all extensions are disabled?: Yes

Asked a friend to repro on a different computer from mine (who knows what system setting could be messing with it) and he succesfully reprod.

I would like Control+Alt+* commands to be possible, mostly because I do control+alt+left/right to navigate between tabs on my Mac and would like to have parity on my PC.

Thank you!

**Comment by alexandrudima** [comment]
@sanboxrunner Does VS Code receive the keybinding?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by sanboxrunner** [comment]
Yes, it records the input in the keybindings pane, but then it does not react to that input when trying to use it elsewhere. There is so "when' clause in this keybinding

**Comment by alexandrudima** [comment]
@sanboxrunner Let's pick one specific keybinding. I'm assuming VS Code receives "ctrl+alt+right". Please double check that in the keybindings input.

Can you please comment everything else and add precisely the following to your `keybindings.json`:
```
{ "key": "ctrl+alt+right", "command": "actions.find" }
```

Does pressing ctrl+alt+right result in the find widget showing up?

**Comment by sanboxrunner** [comment]
Success! Yes!

These are the raw keybindings I have for my desired output:

```
    {
        "key": "ctrl+alt+left",
        "command": "workbench.action.focusPreviousGroup"
    },
    {
        "key": "ctrl+alt+left",
        "command": "-workbench.action.moveEditorToPreviousGroup"
    },
    {
        "key": "ctrl+alt+right",
        "command": "workbench.action.focusNextGroup"
    }
```
Control alt + left/right still does not work, even though the widget *does* work!

**Comment by alexandrudima** [comment]
@sanboxrunner This works for me in `keybindings.json`:

```
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "ctrl+alt+left",
    "command": "workbench.action.focusPreviousGroup"
  },
  {
    "key": "ctrl+alt+right",
    "command": "workbench.action.focusNextGroup"
  }
]
```

When I press `ctrl+alt+left` the focus moves to the group to the left and when I press `ctrl+alt+right` the focus moves to the group to the right:

![focus](https://user-images.githubusercontent.com/5047891/62939073-b17b3600-bdd0-11e9-8269-b26341a1abd2.gif)
