### ISSUE TITLE
Unable to connect to extension marketplace behind proxy

### ISSUE THREAD

**Issue by vnikk** [microsoft/vscode#78103]
Hi. This is a continuation of https://github.com/Microsoft/vscode/issues/68843
I couldn't reopen that issue so I created a new one. I didn't test insiders build yet, but 1.36.1 doesn't let me connect the same way. It works on 1.35.

- VSCode Version: 1.36.1
- OS Version: OSX 10.14.5

**Comment by joaomoreno** [comment]
Can you test Insiders?

**Comment by vnikk** [comment]
@joaomoreno Insiders doesn't work either.
