### ISSUE TITLE
Newly opened panel is small

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78109]
Related:

- https://github.com/microsoft/vscode/issues/77884
- https://github.com/microsoft/vscode/issues/77954

When doing Cmd+Shift+N, panel is much smaller than it used to be:

Insiders:

![image](https://user-images.githubusercontent.com/4033249/62065712-6a901c80-b1e4-11e9-9f17-24f9446088b2.png)

Stable:

![image](https://user-images.githubusercontent.com/4033249/62065718-7380ee00-b1e4-11e9-912d-358008b3cff2.png)

Also, now in Stable I can do:

- Open one window
- Open panel
- Resize the panel
- Open a new window
- The new window inherits the same panel height

![old](https://user-images.githubusercontent.com/4033249/62065895-d1add100-b1e4-11e9-8917-8513838f8133.gif)

Now the panel is resized to a smaller default height.

**Comment by sbatten** [comment]
Issue is believed to be fixed, if you are restoring from a previously serialized grid with a small panel, just resize it and it should go away. Re-open if you see it any other case.
