### ISSUE TITLE
open terminal view (ctrl-j) after exiting the previous session with exit command, will fail

### ISSUE THREAD

**Issue by tikotal** [Microsoft/vscode#7810]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open terminal using ctrl-'
2. in the terminal enter "exit" and press enter
![image](https://cloud.githubusercontent.com/assets/1773701/16151124/eca46c06-34a3-11e6-8793-07e6da7a5cfb.png)

3. the terminal view will close itself
4. now toggle back to terminal view using ctrl-j
5. ERROR: an empty terminal view is shown
![image](https://cloud.githubusercontent.com/assets/1773701/16151140/094d18e4-34a4-11e6-8033-abfcec8e928a.png)

workaround:
1. now click on the closing 'x' button
2. re-open using ctrl-j
3.  result: terminal is now shown

seems like closing the terminal using exit will not trigger and cause the handler to reinitialize a command line. I guess this was done because you wanted to be efficient when switching to other views (output, debug etc.)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

If not, could you open developer tools (via help menu) and check for errors in the console?
