### ISSUE TITLE
Old extension never removed

### ISSUE THREAD

**Issue by tebeco** [microsoft/vscode#78107]
Issue Type: <b>Bug</b>

##### Extension
* Uninstalling extensions keeps file on disk 
* Update or Auto Update, keeps on version on disk (kinda worse, this is why dotnet core changed to "Upgrade in place")
![image](https://user-images.githubusercontent.com/2266487/62064842-07c37300-b22e-11e9-85a8-37eb80945168.png)

#### Why ?
This is critical when you try to cleanup corrupted file, and it's never deleted from disk.
Just took me 3-4 Reload / uninstall / install of `VsCode` to remember that there is potentially a bug here
When an extension is bugged or "corrupted" it's almost impossible to know if "uninstalling" it will have an effect or not (just had the issue with `vs-icons`)

#### Workaround (or not)
I don't expect much `VsCode` user to
* Uninstall extension
* Close all `VsCode` instanences
* manually go in `C:\Users\USER_NAME\.vscode-insiders\extensions`
* find the actual extension id (almost never match the name)
* Delete tons of `js`/`node_modules` "like" files

Did i missed a settings in `VsCode` so that users don't have to "guess and do" that ?

Keeping file on disk makes sense for "Disable" ... but please, let the "Uninstall" actually delete file.
I think it's been the second times i'm hit with "corrupted" extension because of this

VS Code version: Code - Insiders 1.37.0-insider (3802a986823977ec472fc993854e1a753037fc8f, 2019-07-29T05:30:35.768Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alarco-l** [comment]
Same here:

<img width="1481" alt="Screenshot 2019-07-30 at 08 59 18" src="https://user-images.githubusercontent.com/7009064/62107882-e5bb0680-b2a8-11e9-91dd-670358c30153.png">

VS Code version: 1.31.1
OS Version: macOS Mojave V10.14.6

**Comment by sandy081** [comment]
@tebeco @alarco-l We remove old extensions on restart of VS Code. Can you please restart and check if they are gone?

**Comment by tebeco** [comment]
Since i had 4 different version of `vs-liveshase` on my screenshot with respective date :
01/24/19 - 05/13/19 - 05/16/19 - 07/26/19

I restarted VsCode serveral times, updated it (then reload it) and also rebooted the computer.

Also it does not fix the issue that "Uninstalling extension" should absolutly delete the files on disk. Especially for the specified scenario :
* `VsCode` Insider updated 
* Reload window
* Vs-Icons updated
* Reload window
* `VsCode` tells me that the extensions is corrupted
* Uninstall / reinstall the extension, can still show corrupted extension since the same version is already on disk

I do understand old version could be kept until next restart/reload.
Can you ensure me that "uninstall" properly clean `~/.vscode-insiders/extensions/name_here`

**Comment by alarco-l** [comment]
@sandy081 
Indeed  extensions are gone after restart.

**Comment by sandy081** [comment]
Can you please restart VS Code with log level trace. You can do this by launching from command line use option `--verbose`. 

Then open logs using `F1 > View: Open View > Log (Shared)`. Please check logs to see if they are getting deleted or not.

**Comment by tebeco** [comment]
hummmm,

I created the issue after the issue of extensions being corrupted / could not work ^^.
So i already manually deleted duplicated the extensions (after multiple full stop / reload)

I was too focus on making `VsCode` properly load extensions ... i totally forgot about capturing the log to be honnest :s

**Comment by sandy081** [comment]
Is it possible to capture the logs next time you see it and provide it to us?

**Comment by tebeco** [comment]
yes of course ;) it seems obvious now ^^ i completely forgot about that.

i was too focused on managing to load the IDE.
i think i raised an similar issue few week/month ago but for a full uninstall ...
at that time there was no cleanup (it's probably still not cleaning up by default now)

that's probably why i wipe out the extension on disk.
i would love to see proper cleanup on uninstall in order to be sure there are no more artifact left on disk when user try to uninstall vscode or in this scenario extension per extension

**Comment by sandy081** [comment]
Yeah we do not remove extensions when uninstalling VS Code. Not sure if it is intended or not. May be we can ask users to remove or not. @joaomoreno FYI.

Regarding removing after uninstalling an extension, it will be much safer if we do it after restart as we are sure no extension host or process is running with that extension.

**Comment by tebeco** [comment]
> Yeah we do not remove extensions when uninstalling VS Code. Not sure if it is intended or not. May be we can ask users to remove or not

Having the choice would be great yes.
Especially when you got extension with "post install" like Omnisharp, and you are not sure the "post-install" went well to the end (like a network issue or in the extension has a cache issue/bug)

A frequent pattern is usually 
* "Unistall == Remove everything on the disk". As the default this should always be explicit for the end-user
* The uninstall wizard has one or more checkbox to keeps things on disk


> Regarding removing after uninstalling an extension, it will be much safer if we do it after restart as we are sure no extension host or process is running with that extension
I totally understand that point
@sandy081 can you confirm me if "Reload Windows" would do the clean up, or it needs a full close of all instances of VsCode ?


Should i keep this issue open for the "Uninstall" process, as this is titled after extension delete,
I trully beleive changing the default + having checkboxes in the wizard would helps a lots user trying to clean up their devbox.
It's kinda the sems issue with `AppData` or `Regedit` not being cleaned up by various software and at the end you have to run tools to spot them 🗡
Everybody remember (still use) `CCleaner` (or other tools)

For example on this current dev box it would keep ~1.1 GB
![image](https://user-images.githubusercontent.com/2266487/62192308-a8707a80-b375-11e9-9c67-82f7d73f31d6.png)

**Comment by alarco-l** [comment]
I wasn’t aware of that, thanks for the enlightenment.

I agree with @tebeco having the choice of removing all extensions or not when uninstalling would be really great.

**Comment by sandy081** [comment]
> can you confirm me if "Reload Windows" would do the clean up, or it needs a full close of all instances of VsCode ?

In Windows and Linux, it needs closing of all instances of VS Code and in Mac, it needs quit and restart.

Regarding removing extensions on VS Code uninstall I will wait for @joaomoreno 's suggestion

**Comment by joaomoreno** [comment]
@sandy081  https://github.com/microsoft/vscode/issues/66837

**Comment by tebeco** [comment]
@joaomoreno 
Thx for the link i was looking for it ^^
Since i was pretty angry at that time :s

I feel bad reading this now ... i appoligize for that :s

Can you confirm me if i understand this properly ...
It has been implemented using the CLI and then was also shipped to the Uninstall Wizard ?

**Comment by tebeco** [comment]
@sandy081 
> In Windows and Linux, it needs closing of all instances of VS Code and in Mac, it needs quit and restart.

The reload done automatically by the "Update" should be enought ?
Does the `reload` button from the Extension panel is ok ?
So `F1 > Reload Window` is not enought if i understand this correctly ?

**Comment by tebeco** [comment]
(Also i guess i can close this issue ?)

I probably stumbled a bug in `insider` build regardng the extensions like `liveshare` that were still on disk, but this is probably fixed by now ?

**Comment by sandy081** [comment]
> The reload done automatically by the "Update" should be enought ? 

If you mean updating VS Code then it is enough as it restarts VS Code.

> Does the reload button from the Extension panel is ok ?
So F1 > Reload Window is not enought if i understand this correctly ?

Not enough as they just reload the instance.

Thanks and closing this issue.

**Comment by tebeco** [comment]
Thx a lot for the clarification, will be carefull next time
