### ISSUE TITLE
How to make snippet transform from snakecase to camelcase 

### ISSUE THREAD

**Issue by jascodes** [microsoft/vscode#78110]

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by jonschlinkert** [comment]
This probably isn't a vscode issue. Might be a regex support question better suited for stackoverflow.

**Comment by jrieken** [comment]
A sample of what has been tried is needed here

**Comment by jascodes** [comment]
Hey guys,

I finally got around and implemented it.
`${any_snake_case_text/((^[a-z])|_([a-z]))/${2:/upcase}${3:/upcase}/g}`

**Output**
```
AnySnakeCaseText
```
