### ISSUE TITLE
Test button toggle state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78115]
Test for https://github.com/microsoft/vscode/issues/36439

- [x] anyOS @bowdenk7
- [x] anyOS @sana-ajani

Complexity: 1

**Overview**
We've introduced a new color token, `inputOption.activeBackground`, that allows you to style the button toggle state and have added this to our button toggles. Verify that you can style this via `workbench.colorCustomizations` and that the button state is updated when toggled. Also ensure that when tabbing via keyboard that you can clearly tell when a button toggle is in focus vs being active.

Button toggles appear in:
- Search find input
- Files exclude
- Find widget (editor and terminal)

**Comment by sana-ajani** [comment]
Works on Windows 👍

**Comment by bowdenk7** [comment]
Works on Mac 👍
