### ISSUE TITLE
Find In Files: 'Match Whole Word' doesn't work with Russian text

### ISSUE THREAD

**Issue by fantaclaus** [microsoft/vscode#78116]
Issue Type: <b>Bug</b>

1. open folder with files
2. open Find In Files panel
3. enter any Russian word or a few letters to search, check "Match Whole Word" option on and press ENTER

_What I see:_ 
A list is filled with lines. The search text is highlighted regardless of being a whole word or a part of a word.

_What I expect to see:_
A list that is filled with only lines where the searched text is a whole word.

**NOTE**
This option **does work** for Find in document.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:58:59.274Z)
OS version: Windows_NT ia32 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.01GB free)|
|Process Argv|D:\!ProjectsGit\!KmPhoto\KmPhoto\KmPhotoWebAdmin|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-icons|jam|0.3.1
classic-asp-html|jtj|0.1.1
python|ms-|2019.6.24221
seti-icons|qin|0.1.3

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/27280

**Comment by fantaclaus** [comment]
@roblourens, are you sure this is a duplicate? 

#27280 describes the search inside a document, but this issue is about Search In Files.

I specifically noted that this option **does work** for Find in document.

**Comment by roblourens** [comment]
That is about search. The user in that issue was trying find before it was implemented there.
