### ISSUE TITLE
Test new product icons

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78113]
Test for https://github.com/microsoft/vscode/issues/8017

- [x] Windows @rebornix
- [x] macOS @chrisdias
- [x] Linux @joaomoreno

Complexity: 2

**Overview**
We've updated all of our product icons to use our new outline style:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/35271042/62069541-60bee700-b1ed-11e9-8359-c6b8d13a0412.png">

Please go through each area of the product and verify that thew new icons appear properly, and that there are no old icons remaining. Please ensure that you disable extensions (`--disable-extensions`) when running this as other extensions haven't updated their icons yet and can be confusing when testing this. Note that Octicons are not covered in this and those appear in the Status bar and Quick pick. Please cover the following the areas:
- Activity bar
- Explorer
- Search
- SCM
- Debug
- Extensions
- Panels
- Notifications
- Settings
- Keyboard Shortcuts
- Running Extensions

**Comment by joaomoreno** [comment]
Love it! :clap:

**Comment by rebornix** [comment]
❤️

**Comment by chrisdias** [comment]
🌈🦄

**Comment by johnletey** [comment]
@misolori Just wondering, is the screenshot you attached in the first comment of a **public** figma file? The reason why I'm asking is because I'm still working hard on https://github.com/eamodio/vscode-gitlens/issues/784, and occasionally take some of the new vscode icons ... but it's a pain having to search through the tons of files on GitHub to find an SVG file

**Comment by misolori** [comment]
@johnletey no that is not a public Figma file. We're currently discussing the best way to help extension authors update their icons. Let me get back to you on the recommended options.

**Comment by WebGhan** [comment]
The new icon is ugly
