### ISSUE TITLE
"Merge All Windows" command no longer works on Mac OSX after update

### ISSUE THREAD

**Issue by nojvek** [microsoft/vscode#78112]
- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: Mac Sierra 10.12.6

Steps to Reproduce:

1. code somefolder
2. code someotherfolder
3. cmd+p and run "merge all windows".

Windows don't merge. 

Does this issue occur when all extensions are disabled?: Yes/No

Yes

-- 

I can manually drag the two windows to merge them, but the my keyboard shortcut cmd+k+m is broken since the command doesn't work.

**Comment by joaomoreno** [comment]
This seems to work for me on Insiders, can you try?
