### ISSUE TITLE
Setting variable values

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7812]
Tests https://github.com/Microsoft/vscode/issues/7744:

- [x] any platform - @sandy081 

During a debugging session it is now possible to change a value of any primitive variable (leafs in the variable tree). Currently this is only supported in node-debug. The accepted syntax is the same as for watch expressions and the REPL.  

Verify:
* you can use the context menu / double click to change the value of any primitive variable; this includes object properties and individual array entries, 
* changing it to some invalid value clearly shows the error
* try to be creative and break it

**Comment by sandy081** [comment]
Tested. Tried to break it but can't :). Looks good.

**Comment by isidorn** [comment]
Great - thanks! Then we can close this issue
