### ISSUE TITLE
Form Feed isn't rendered on a new line in editor

### ISSUE THREAD

**Issue by martijnhoekstra** [microsoft/vscode#78124]
Issue Type: <b>Bug</b>

Open a file containing a form feed character. The character isn't rendered.

Expected: Rendered as one or two new lines.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
gitlens|eam|9.9.1
eml|lei|0.3.2
mssql|ms-|1.6.0
csharp|ms-|1.21.0
java|red|0.47.0
scala|sca|0.3.4
metals|sca|1.5.2
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by alexandrudima** [comment]
View > Render Control Characters:

```js
const fs = require('fs');
fs.writeFileSync('test.txt', 'a file\fa second line');
```

![image](https://user-images.githubusercontent.com/5047891/62715396-b9b62880-ba00-11e9-8562-b018c2597f94.png)

**Comment by martijnhoekstra** [comment]
@alexandrudima does that mean not rendering anything for form feed is the intended behaviour (when render control characters is not turned on)? Could that be changed/revisited?

**Comment by alexandrudima** [comment]
When render control characters is off, the font decides what to render for form feed. When render control characters is on, we substitute the form feed character with another character which renders `FF`. We do that [here](https://github.com/microsoft/vscode/blob/63fe017c5a4af7db96b78d7bd9ccc762ece02816/src/vs/editor/common/viewLayout/viewLineRenderer.ts#L883-L886)

I don't know, perhaps other editors render control characters by default?

**Comment by martijnhoekstra** [comment]
VSCode also renders the control characters \t and \n regardless of font used. I expected something similar.

The git bash terminal also honour \f

It's hard to explain, I included a screenshot of what I mean:

![Likethis](https://user-images.githubusercontent.com/882449/63352232-03880280-c361-11e9-9e61-820d8c591426.png)
