### ISSUE TITLE
Test "Extension Terminal" proposed API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78123]
Test for #70978

- [x] Mac @lramos15
- [x] Linux @aeschli
- [x] Windows @alexr00

Complexity: 5

The `TerminalRenderer` API has been deprecated in favor of the new extension terminal/pseudoterminal API. The new API allows an extension to be the backend for a terminal instead of a process. Search vscode.proposed.d.ts for `ExtensionTerminalOptions` for full details and examples.

To test, create an extension that utilizes the API and make sure all methods are working as expected. Also make sure the docs in vscode.proposed.d.ts are good, the examples there are a good place to start the extension with.

**Comment by lramos15** [comment]
It was unclear to me that the terminal dimensions have a min of 2 based on the docs.

**Comment by lramos15** [comment]
@aeschli I saw that you unassigned yourself, but didn't check the box so I assumed you completed testing and checked the Linux box. Feel free to uncheck and reopen the issue if that's not the case :+1:
