### ISSUE TITLE
Remote SSH to the machine fails 

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode#78126]
- VSCode Version: 1.36.1
- OS Version: W10 1603

Steps to Reproduce:
Using remote ssh -- I receive this error when I try to connect to a machine, I am able to connect to the machine from cmd terminal or using vs code , but fails to connect from code-insiders 

 
```
"install" terminal command done
Received install output: f5f7e0f4-98ad-4e74-ac6d-dafkaf033##28##
Server status check failed - waiting and retrying 5
```

**Comment by tkoelpin** [comment]
Hi @thkrishn, 
I am also a user like you.

I remembered that I had also problems with the SSH connections. I answered the question by myself via the following questions:

- Do you have internet connection on your remote host? 
- Do you use a proxy connection?
- Did you checked the SSH config for the SSH-Daemon (`sshd_config`) on your remote host?
- Did you compared the SSH Daemon config with your local SSH config? Sometimes a setting is required or missed.

Kind regards
tkoelpin

**Comment by thkrishn** [comment]
Do you have internet connection on your remote host? Yes 

Do you use a proxy connection? No

Did you checked the SSH config for the SSH-Daemon (sshd_config) on your remote host?
Did you compared the SSH Daemon config with your local SSH config? Sometimes a setting is required or missed.
please provide details about what should be present 

I am able to  ssh into  `machine1.domain` , access the internet, also connect via code-insiders (sorry i typed in opposite info in the question)

But fails a remote host connection from VS code (vs-code is my primary) the config files are the same on both machines

**Comment by thkrishn** [comment]
So one thing I observed in the `machine.domain:/tmp` there are `*.sock`  files
Once I just removed those files I was able to connect from both vscode and code-insiders

I am not sure if this is the fix but that helped

**Comment by roblourens** [comment]
I am not sure what those files are from. I would need the full log to understand what happened. Please let me know if this happens again.

**Comment by thkrishn** [comment]
The have names like 
```vscode-ipc-41d09272-286d-4259-888e-e0cd79cf5041.sock  
vscode-ipc-cefbe2db-6e22-4e47-8743-40276b4d7abb.soc ```

**Comment by thkrishn** [comment]
This is happening again, after rebooting the machine I am not able to connect from VS code 
 But I am able to login from an ssh connection 

```
Install and start server if needed
> 
> ssh: Could not resolve hostname machine: Name or service not
>  known
> The process tried to write to a nonexistent pipe.
> 
"install" terminal command done
Received install output: The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe
------
```

**Comment by roblourens** [comment]
`Could not resolve hostname machine: Name or service not known` this sounds like a configuration error, it can't find a machine named `machine` on your network.

**Comment by thkrishn** [comment]
It was working fine and after the update getting this error 
```
[20:43:13.146] > Found existing installation at /home/thkrishn/.vscode-server-insiders/bin/3
> 66e1b275cf01e2d50e96083dede553de608b078...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 37444 with wget
> failed: Connection refused.
> 4d1e635f-cf74-44f9-bd01-980097f43130##28##
```

**Comment by roblourens** [comment]
Could you try running the command "Uninstall vscode server from host" and try again? Seems there is a problem connecting to the currently running server...

**Comment by thkrishn** [comment]
how/where  do I run that command

**Comment by roblourens** [comment]
The command palette (ctrl+shift+P)

**Comment by thkrishn** [comment]
Still doesn't work but different error :
```
[22:26:50.157] > 
> *
> 
> 
[22:26:50.220] > Server did not start successfully. Full server log >>>
> 
[22:26:50.249] > <<< End of server log
> 
[22:26:50.668] "install" terminal command done
[22:26:50.668] Install terminal quit with output: <<< End of server log
[22:26:50.668] Received install output: <<< End of server log
[22:26:50.669] Failed to parse remote port from server output: <<< End of server log
[22:26:50.670] 
[22:26:50.671] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[22:26:50.671] ------
```

**Comment by roblourens** [comment]
There is definitely something wrong with running the server on your remote. Can you share the full log? And do you see the server running? `ps ax | grep <commit hash>`

**Comment by thkrishn** [comment]
When I grepped for `4454769affdb83e84721305835b300e94`

```
thkris+  13330  0.0  0.0   4500   784 ?        S    Aug22   0:00 sh /home/thkrishn/.vscode-server-insiders/bin/4454769affdb83e84721305835b300e943ca0d61/server.sh --enable-remote-auto-shutdown --port=0
thkris+  13338  0.0  0.1 883992 48464 ?        Sl   Aug22   0:01 /home/thkrishn/.vscode-server-insiders/bin/4454769affdb83e84721305835b300e943ca0d61/node /home/thkrishn/.vscode-server-insiders/bin/4454769affdb83e84721305835b300e943ca0d61/out/vs/server/main.js --enable-remote-auto-shutdown --port=0
thkris+  21486  0.0  0.0  16028  2448 pts/3    S+   10:50   0:00 grep --color=auto 454769affdb83e84721305835b300e943ca0d
```

**Comment by thkrishn** [comment]
Is it a problem if multiple instances of vscode/code-insiders try to connect to the same host?

**Comment by thkrishn** [comment]
code-insiders just updated to the below version ..Now I am able to SSH

![image](https://user-images.githubusercontent.com/7133450/63614898-f6555880-c598-11e9-9667-3ca073bc1b3d.png)
