### ISSUE TITLE
"Your First Extension" fails with PowerShell profile

### ISSUE THREAD

**Issue by garyericson** [microsoft/vscode#78129]
- VSCode Version: 1.36.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Configure PowerShell as the default shell.
2. Step through [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) up to "Then, inside the editor, press F5...".
3. Press F5 - a message is displayed, "The terminal process terminated with exit code: 1", but everything continues running.
4. In the Extension Development Host, run "Hello World".

Result: Two errors are displayed instead of "Hello World":

- command 'extension.helloWorld' not found
- Activating extension 'undefined_publisher.helloworld' failed: Cannot find module 'c:\Users\garye\helloworld\out\extension.js'

Does this issue occur when all extensions are disabled?: Yes

Workaround: Configure cmd as the default shell, or configure PowerShell to run with the "-noprofile" option.

I have a lot of things in my PowerShell profile, so I'm assuming something in there is conflicting with something, but I don't know what. I can continue just fine using one of the workarounds.

**Comment by octref** [comment]
What happens if you try to open a powershell terminal (F1 -> Open New Terminal) and run `npm run watch`?

**Comment by garyericson** [comment]
I assume you mean running powershell while in the helloworld folder. I get the following messages and then it just sits there. I'm not sure how or when to close it.

[9:41:46 AM] Starting compilation in watch mode...

[9:41:48 AM] Found 0 errors. Watching for file changes.

**Comment by octref** [comment]
@alexr00 I see this error message: `The terminal process command 'C:\Windows\System32\wsl.exe-e npm run watch' failed to launch (exit code: 1)`

Notice the connecting `wsl.exe-e`. I suspect that's the cause.

**Comment by alexr00** [comment]
@octref are you sure you were using powershell? I'm not sure how you could have gotten wsl.exe if it's powershell.

@garyericson How did you configure powershell to be the default shell? Can you share your settings.json?

**Comment by octref** [comment]
@alexr00 Hmm, today I tried it again and it seems to be working. Did I have to restart VS Code for task to pick up the changed default shell?

**Comment by garyericson** [comment]
@alexr00 - I'm not a VS Code wizard, but I set PowerShell to the default shell by going to File -> Preferences -> Settings, finding "Terminal > External: Windows Exec" and pasted in this: "%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe".

**Comment by garyericson** [comment]
Where can I find settings.json, and how would you like me to share it?

**Comment by octref** [comment]
@garyericson F1 (Or Ctrl+Shift+P) + "Preferences: Open Settings (JSON)"

When you run the "launch extension" command, it would launch the build task in a new terminal. You can find it like this:

![image](https://user-images.githubusercontent.com/4033249/62332178-544bc000-b473-11e9-9791-a9fbfc89d1b5.png)

**Comment by octref** [comment]
Let me know when you can provide more information.

**Comment by garyericson** [comment]
@octref - My workaround is to run PowerShell without executing my profile. That works fine for what I need, so I'm fine with closing this.

**Comment by Tyriar** [comment]
@garyericson there is a new setting `terminal.integrated.automationShell.windows` coming which allows you to set the shell and ignore the shellArgs of your normal terminal, this might be useful for you? https://github.com/microsoft/vscode/issues/78497
