### ISSUE TITLE
Add a user setting to disable loading of workspace settings

### ISSUE THREAD

**Issue by jmillikin-stripe** [microsoft/vscode#78134]
Workspace settings override user settings, which can cause a fairly unpleasant experience if the repository owner's preferences for VSCode behavior are significantly different from the current users'. I would like a way to configure my VSCode installation such that it will obey my own user configuration, but will not load `${WORKSPACE}/.vscode/settings.json`.

**Comment by sandy081** [comment]
@jmillikin-stripe This looks completely opposite of why workspace settings are used. Do you want a way to override workspace settings? Is not it possible to change them in the workspace settings file?

**Comment by jmillikin-stripe** [comment]
I understand that workspace settings are intended for settings that are reasonable for all users. Unfortunately, there are some repositories whose owners encode more personal preferences into the `.vscode/settings.json`. I strongly prefer my editor's behavior to be consistent between workspaces, just as way web browsers don't change e.g. key bindings between websites, so I would like a way to completely prevent workspace settings from affecting my editor.

Ideally this would be a user preference `useWorkspaceSettings` or something like that, which I could toggle off.

**Comment by sandy081** [comment]
But that means you might miss workspace settings which makes sense like `insertSpaces` etc. So, what you want is to override workspace settings without changing them in workspace settings?

**Comment by jmillikin-stripe** [comment]
I'd prefer the ability to completely ignore workspace settings.

**Comment by SSJ9899TDylan** [comment]
Oh really?



Sent from myMail for iOS


Wednesday, 31 July 2019, 5:56 pm +1000 from notifications@github.com  <notifications@github.com>:

**Comment by sandy081** [comment]
Hmm I see. Sorry, I do not think we would like to provide that feature to completely ignore workspace settings. As this not a highly requested feature and we do not have plans to implement this I am closing this as out of scope
