### ISSUE TITLE
utf-8下“交易页面”识别为Window 1252

### ISSUE THREAD

**Issue by zcp5935** [microsoft/vscode#78139]
Issue Type: <b>Bug</b>

确切地说，不知道算不算是bug。
utf-8下保存的“交易页面”这4个字，被vsCode的autoGuessEncoding猜测为Window 1252编码。
其他情况：
1.后面有其他字符时会被识别为utf-8字符集
2.前面为数字时识别为Window 1252，前面为中文时被识别为utf-8

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.21.1

</details>

**Comment by joaomoreno** [comment]
@octref @rebornix Some translation help here, please.

**Comment by yume-chan** [comment]
@joaomoreno translation:

> ## Some content in utf-8 is incorrectly detected as windows-1252
>
> With `files.autoGuessEncoding` on, a file containing exactly four Chinese characters "交易页面" will be incorrectly detected as windows-1252 encoding by Code.
>
> Some other notes:
> 1. If any other characters are appended, Code can correctly detect the file as utf-8.
> 2. When the file starts with numbers, it will be windows-1252. When it starts with Chinese characters, it will be utf-8

---

My tests show that Code might not be able to detect encoding for "交易页面" and uses `files.encoding` instead.

**Comment by zcp5935** [comment]
But my `files.encoding ` is `uft-8`。
I create an .html file with `utf-8` encoding,when i add comments like
`<!-- 交易页面 -->`,
next i open this file,the .html's encoding become `windows-1252`

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
