### ISSUE TITLE
Powershell integrated terminal PSReadline keyboard commands

### ISSUE THREAD

**Issue by Js-Brecht** [microsoft/vscode#78132]
There seems to be some issue with the integrated powershell reading certain control keys; for example, I use CTRL+BACKSPACE frequently to erase the last word (`backward-kill-word` in bash readline).  It works fine in my system powershell, but in vscode integrated terminal, it just prints the control key to output: 

```pwsh
PS C:\> ^W^W^W
```

It's been like this since I started using vscode more than a year ago, but I've just ignored it until now.  Not sure if it's an issue with PSReadline, the vscode emulator, or my configuration.

- VSCode Version: 1.36.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Changing the edit mode to emacs should fix this, I think pwsh latest does this automatically for vscode now.

```
Set-PSReadLineOption -EditMode Emacs
```
