### ISSUE TITLE
inspect API is not working on workbench.colorCustomizations 's sub properties

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#78135]
RE: VS Code API for inspect from this page https://code.visualstudio.com/api/references/vscode-api

How can the inspect API operate on a 4 part setting like workbench.colorCustomizations.panel.background ?

![image](https://user-images.githubusercontent.com/1202528/62091989-8544ae80-b241-11e9-8d55-f771a0e2438c.png)

When *global user settings.json* has the following 👇

```json
    "workbench.colorCustomizations": {
        "panel.background": "#212121"
    }
```

TypeScript code
```typescript
  const section = 'workbench.colorCustomizations';
  const setting = 'panel.background';
  const config1 = vscode.workspace.getConfiguration(section).inspect(setting);
  const config2 = vscode.workspace.getConfiguration().inspect(`${section}.${setting}`);
```

Neither config1 nor config2 above inspects the panel.background from the section listed. This inspect API works great when it looks for a single level, but perhaps since this is 4 parts (three dots) it has a problem? or maybe there is another syntax for this?

**Comment by sandy081** [comment]
`inspect` api takes only the registered configuration keys. Looks like you are trying to inspect the values which is not valid.

**Comment by johnpapa** [comment]
Is there a way to know which of these values came from user settings or global settings?

Scenario:

I get a set of these and I need to remove some and add some back, then write them to workspace settings. The problem I I don;t want to touch the ones in global settings. This is for the Peacock extension.

Otherwise I can write a set to workspace , but this overwrites whatever they had and they may lose some things they wanted. Or I can get the merged set, and then write to workspace - but this takes settings from global and duplicates them to the workspace, which isnt god either.

**Comment by sandy081** [comment]
You can do it by inspecting the setting and compare the values.

**Comment by johnpapa** [comment]
Thanks, but I think I need to provide more context. 

** global user settings.json**
```
 "workbench.colorCustomizations": {
     // the user manually set this 👇
     "panel.background": "#212121"
    }
```

** workspace settings.json**
```
 "workbench.colorCustomizations": {
     // the user manually set this 👇
    "panel.foreground": "#ffffff",

     // peacock set these 👇
    "activityBar.background": "#174a8e",
    "activityBar.foreground": "#e7e7e7",
    "activityBar.inactiveForeground": "#e7e7e799",
    "activityBarBadge.background": "#e03f84",
    "activityBarBadge.foreground": "#e7e7e7",
    "statusBar.background": "#103362",
    "statusBarItem.hoverBackground": "#174a8e",
    "statusBar.foreground": "#e7e7e7",        
    }
```

A user of Peacock decides they want a new color. I now need to write all of the "activityBar" and "statusBar" colors to the workspace. if I grab all colors and go through them one by one, I get the merged set of global and workspace. Then I can go thru them and overwrite the peacock colors. But when I go to write them, I would be writing the global one to the workspace. I think you are saying I have no way of knowing that `     "panel.background": "#212121"` came from global.

If I just overwrite the workspace colors, the user will lose their color `"panel.foreground": "#ffffff",`.

Do you see the dilemma?

**Comment by sandy081** [comment]
You can call inspect on `workbench.colorCustomizations` and you get 
`global` and `workspace` values. From that you can infer `panel.background` value is coming from global settings.

**Comment by johnpapa** [comment]
Thanks for the tip. Here is what I did, in case anyone else is curious

```typescript
export interface ISettingsIndexer {
  [key: string]: any;
}

export function getColorCustomizationConfigFromWorkspace() {
  const inspect = workspace.getConfiguration().inspect('workbench.colorCustomizations);

  if (!inspect) {
    return {};
  }

  if (typeof inspect.workspaceValue !== 'object') {
    return {};
  }

  const colorCustomizations: ISettingsIndexer = inspect.workspaceValue as ISettingsIndexer;

  return colorCustomizations;
}
```
