### ISSUE TITLE
wsl.exe as default terminal crashes

### ISSUE THREAD

**Issue by deryb** [microsoft/vscode#78136]
Issue Type: <b>Bug</b>

`The terminal process command 'C:\WINDOWS\System32\wsl.exe -l' failed to launch (exit code: 4294967295)`

To reproduce:
- I've installed ubuntu & WSL. A bit cryptic / messy when many other tools installed before (cygwin, git bash etc)
- in VSC, set wsl.exe as default terminal
- open terminal window

details:
wsl.exe > details > file version:   10.0.17763.615

Feel free to ask any other info, I'd like to get WSL running along nicely. Coming from a Mac & Ubuntu & Java background, I'd like to get back at coding on my Windows dev machine with node.js, so many things to re-learn, be gentle ;-)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.4.0
prettier-vscode|esb|1.9.0
terminal|for|0.0.10
vscode-mysql|for|0.4.0
graphql-for-vscode|kum|1.15.0
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.23
debugger-for-chrome|msj|4.11.6
LiveServer|rit|5.6.1
vscode-fileutils|sle|2.14.5
open-in-browser|tec|2.0.0
quokka-vscode|Wal|1.0.238

</details>

**Comment by Tyriar** [comment]
Do you have `"terminal.integrated.shellArgs.windows": ["-l"]` in your settings?
