### ISSUE TITLE
Bad extensions rankings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7813]
The current extension ranking is bad, here are a couple of examples:
Due to this finding the correct extension right now is extermely difficult.

![screen shot 2016-06-17 at 16 10 12](https://cloud.githubusercontent.com/assets/1926584/16153294/ff140d2c-34a5-11e6-8750-e0bcbb0df622.png)

![screen shot 2016-06-17 at 16 10 47](https://cloud.githubusercontent.com/assets/1926584/16153317/18b0fa2e-34a6-11e6-9eca-7ff8ae20c542.png)

![screen shot 2016-06-17 at 16 11 24](https://cloud.githubusercontent.com/assets/1926584/16153328/2e727180-34a6-11e6-8d93-1deae0f2f05d.png)

![screen shot 2016-06-17 at 16 12 28](https://cloud.githubusercontent.com/assets/1926584/16153365/50fe83ce-34a6-11e6-910a-afbabf29adb6.png)

**Comment by joaomoreno** [comment]
Forwarded to Marketplace team.

**Comment by joaomoreno** [comment]
Closing as Marketplace owns the issue.
