### ISSUE TITLE
change the open Recent shortcut to not trigger when in terminal.

### ISSUE THREAD

**Issue by sanderma** [microsoft/vscode#78144]
When you press `ctrl-r` the open recent window opens. For people who use the reverse search functionality in terminals (bash, powershell etc) this is really annoying.

It is easily solved by changing the when clause to `!terminalFocus`
Is it a good idea to set this as default?

**Comment by Tyriar** [comment]
Have you customized your keybindings and settings? The default behavior shouldn't do this. Also what version of vscode are you on? If it's insiders we had a regression that could have caused this recently but is fixed already.

**Comment by sanderma** [comment]
Ah nice, that was it then. I am indeed using insiders.
I did change the keybinding, to not trigger when in terminal, but if it's not going to go to the normal vscode, this is a non-issue.
Thanks for the update!
