### ISSUE TITLE
Configure task action should reveal the newly added task and position the cursor there

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#78147]
Testing https://github.com/microsoft/vscode/issues/78102

At the following step

> This will open tasks.json and add that task to it. Set some extra properties on the task, such as a presentation property.

tasks.json file is opened and task is added. But it did not reveal the added task and I was wondering where and what task got added.

It would be good if the newly added task is revealed and the cursor is positioned there

**Comment by weinand** [comment]
Verified that the added task is selected and that the caret is placed at the end of the selection.
