### ISSUE TITLE
[js] syntax highlighting: Regular expressions are hard to read

### ISSUE THREAD

**Issue by tylucaskelley** [Microsoft/vscode#7814]
- VSCode Version: 1.2.1
- OS Version: 10.11.5

Steps to Reproduce:
1. Write a RegExp literal
2. Note the lack of any highlighting to distinguish different elements of the regular expression

![screen shot 2016-06-17 at 10 14 44 am](https://cloud.githubusercontent.com/assets/5448759/16153445/596e6862-3474-11e6-85e1-d0327a91cb2f.png)

I prefer the way Atom handles this:

![screen shot 2016-06-17 at 10 16 03 am](https://cloud.githubusercontent.com/assets/5448759/16153496/8f736066-3474-11e6-8e97-12def017eccb.png)

**Comment by nsgundy** [comment]
Agree, this would help a lot reading / writing RegEx. I currently digest / compose the more complex examples with an external tool to make my life easier.

**Comment by Earl-Brown** [comment]
I like this idea, too - but I would recommend it be in an extension

**Comment by mjbvz** [comment]
Try out vscode 1.7. We picked up a new grammar from the TypeScript team that adds syntax coloring for regular expression literals:

![screen shot 2016-11-18 at 2 23 19 pm](https://cloud.githubusercontent.com/assets/12821956/20448794/868394fe-ad9a-11e6-905d-ed9b5af303c4.png)

Please let me know if something still looks off or if you have any ideas on how this could be improved.  Thanks.

**Comment by tylucaskelley** [comment]
looks great!
