### ISSUE TITLE
Collapse folder from anywhere inside the Folder

### ISSUE THREAD

**Issue by dineshsm** [microsoft/vscode#78142]
let's say am inside a folder and that has 100+ files and when I need to navigate to another folder I Should use the scroll bar (Which is not convenient) or scroll all the way to the top.

When right Clicked **Collapse Parent Folder** option will be more helpful

**Comment by joaomoreno** [comment]
You can press <kbd>Left Arrow</kbd> twice. Does that help?

**Comment by dineshsm** [comment]
Thanks for the response it really helps.
