### ISSUE TITLE
Font rendering on Windows uses wrong DPI(?)

### ISSUE THREAD

**Issue by james-schend-iii** [microsoft/vscode#78141]
- VSCode Version: 1.36.1
- OS Version: Windows 10

Steps to Reproduce:

1. In Settings, change the font size to 14
2. Compare font rendered in VS Code to font rendered in a known-good application like Microsoft Word (see attached image)

Does this issue occur when all extensions are disabled?: Yes

Comments:

If you set font size 14 in settings, VS Code ends up rendering a font that looks similar to 12.5. If you set the size to 16.5, you get something that resembles size 14 in all other applications. My guess is that VS Code is incorrectly sizing its fonts assuming a DPI of 72. The DPI of Windows is 96, so this results in wrong font sizes.

I searched related issues and couldn't find this issue reported before, although I could have missed it because many of the font issues have generic titles.

![unknown](https://user-images.githubusercontent.com/53459265/62098353-cd160680-b23e-11e9-99e9-c1d3101cf8ba.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by FernandoC92** [comment]
I'm testing this build of windows is very better for UI and fonts render! When will update?
