### ISSUE TITLE
Inconsistant workbench.action.openSnippets

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#78146]
- VSCode Version: `1.36.1`
- OS Version: `Windows 10`

Snippets list opened with `workbench.action.openSnippets` does not always show all snippets. Sometimes only folder snippets are shown, not global ones. When I restart VSCode all snippets are back in the list. I couldn't figure out what causes this fluctuation. 

Steps to Reproduce:
1. launch command `workbench.action.openSnippets`

Does this issue occur when all extensions are disabled?: `Yes`

**Comment by jrieken** [comment]
> I couldn't figure out what causes this fluctuation.

Ok, please update this issue once you know
