### ISSUE TITLE
Braces inserted by typescript.suggest.completeFunctionCalls can't be over-typed

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#78151]
Testing #78118

Issue Type: <b>Bug</b>

Steps:

1. Enable `typescript.suggest.completeFunctionCalls`
2. Auto-complete some function, e.g., `alert`. It will become `alert()` and the cursor is between the brace pair.
3. Type `)`.

Expected:

The `)` inserted by auto-completion is getting over-typed, as 1.36.1 does.

Actual:

It does not.

VS Code version: Code - Insiders 1.37.0-insider (3802a986823977ec472fc993854e1a753037fc8f, 2019-07-29T05:30:35.768Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by misolori** [comment]
I'm also seeing this but only within a function (see below after typing `console.log()` and adding a parenthesis):

![overtyping](https://user-images.githubusercontent.com/35271042/62149950-b78df480-b2b1-11e9-8883-7db4376a9f4d.gif)

**Comment by alexandrudima** [comment]
Let's track in #78975
