### ISSUE TITLE
I want to code to call Terminal:Rename

### ISSUE THREAD

**Issue by 851201344** [microsoft/vscode#78152]
![image](https://user-images.githubusercontent.com/40556460/62113614-7ca6b380-b2e7-11e9-9c4a-fac6cb5b5875.png)

Is there any way I can code to call Terminal:Rename ?

![image](https://user-images.githubusercontent.com/40556460/62113750-b677ba00-b2e7-11e9-8206-dd09030a977e.png)
 
I know that way

But I want to know how to call it in code

Nodejs   or  NPM   or  CMD command

Thanks !!!

**Comment by IllusionMH** [comment]
/question

VSCode displays name of active process in that terminal. So you should look for a way to set name of active process for your OS and used terminal

**Comment by 851201344** [comment]
do you have any suggestions ?

I want to know which folder teminal is currently in

like this 

![image](https://user-images.githubusercontent.com/40556460/62178115-3d757280-b37a-11e9-985b-1bfa45cf76a8.png)

Or other ways

@IllusionMH

**Comment by Tyriar** [comment]
The command name is `workbench.action.terminal.rename` which you can call from an extension or add a keybinding for.
