### ISSUE TITLE
Search exclude regression

### ISSUE THREAD

**Issue by caub** [microsoft/vscode#78158]
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic

Steps to Reproduce:

1. Search in file (Ctrl+Shift+f)
2. Results are found in .git or node_modules although they're excluded from searches

Does this issue occur when all extensions are disabled?: Yes

This issue exist since a few weeks, and didn't happen before

![2019-07-30-122803_1615x885_scrot](https://user-images.githubusercontent.com/3134574/62122382-d5fdeb00-b2c5-11e9-94cc-c2bbfe385719.png)

**Comment by caub** [comment]
Oh I just noticed the "exclude settings and ignored files are disabled", how to enable it like before?

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/62124261-76f2a300-b2d2-11e9-9413-82322ea4e4f5.png)
You should click on "Toggle Search Details" (three dots) and then on "Use Exclude Settings and Ignore Files" (button in Exclude field)

**Comment by caub** [comment]
Wow, thanks, it's really not obvious it's a toggle button
