### ISSUE TITLE
Split view sizes not preserved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#78156]
1. Make the outline view in the exlporer the maximum size
2. Reload -> the outline size is not preserved

I can repro this for all split views. Also in web.
I can not reproduce with stable -> regression, assigning to July.

![splitView](https://user-images.githubusercontent.com/1926584/62120942-e6609680-b2c2-11e9-93a9-0d0438c3a3c0.gif)

**Comment by sandy081** [comment]
Good catch
