### ISSUE TITLE
VSCode crashes when closing large SQL file

### ISSUE THREAD

**Issue by kyokawasaki** [microsoft/vscode#78150]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open very large SQL file.
2. Edit something on the file.
3. Try to close the file without saving.
4. VSCode hangs a bit and crashes.

I was only able to close the file before it loaded when I opened VSCode after it crashed.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.1.5
laravel-blade|cjh|1.1.2
gitignore|cod|0.6.0
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
beautify|Hoo|1.5.0
python|ms-|2019.6.24221
snippet-creator|nik|0.0.5
vetur|oct|0.21.1
advanced-new-file|pat|1.2.0
vscodeintellicode|Vis|1.1.8
colonize|vms|2.2.2
vscode-icons|vsc|9.1.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@Tyriar I suppose auto hot exit tries to save the file onto disk but crashed?

**Comment by Tyriar** [comment]
@rebornix see https://github.com/microsoft/vscode/blob/a996f2a9a56ece1db8bddf0737ba7714b73d7e3c/src/vs/workbench/services/backup/common/backupFileService.ts#L248

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by kyokawasaki** [comment]
@bpasero Here is the log I got after running the diagnostic tool.

[Code__PID__19232__Date__11_07_2019__Time_04_45_28PM__587__Log.txt](https://github.com/microsoft/vscode/files/3818443/Code__PID__19232__Date__11_07_2019__Time_04_45_28PM__587__Log.txt)
