### ISSUE TITLE
Full width bottom panel

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78155]
re #78137

I don't know how that happened, but I have proof that it happened...

<img width="1585" alt="Screenshot 2019-07-30 at 11 46 08" src="https://user-images.githubusercontent.com/1794099/62119365-acda5c00-b2bf-11e9-8c37-0967596e2c0f.png">

**Comment by IllusionMH** [comment]
👍 Would be awesome to have this layout as feature after some tuning!
No more trashing of terminal text during panel resize.

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/42149

**Comment by sbatten** [comment]
this issue should be close as the new system is more robust and this should not happen accidentally. As for the feature request, we will track separately

**Comment by bpasero** [comment]
I also saw it btw when I played around, are we sure this does not happen anymore?

**Comment by sbatten** [comment]
You saw it in master this week?

**Comment by bpasero** [comment]
@sbatten well I saw it very early this week, but not with your latest changes.

**Comment by jrieken** [comment]
Adding verified since I haven't seen this anymore
