### ISSUE TITLE
Enable `strictPropertyInitialization`

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#78168]
We have enabled `strictNullChecks`, but the TS compiler doesn't catch the following:
```ts
class A {
  prop: number;
  constructor() {
    // forgot to assign to prop, so it will be undefined...
  }
}
```

Possible fixes:
```ts
class A {
  prop: number;
  constructor() {
    this.prop = 5; // Assign the property in the ctor
  }
}
```

```ts
class A {
  prop!: number; // use exclamation mark to suppress the error
  constructor() {
    this._init();
  }
  private _init() {
    this.prop = 5;
  }
}
```

---

In order to get errors for such cases, we need to add `"strictPropertyInitialization": true` to our `tsconfig.json`.

@microsoft/vscode it would be nice if we could tackle some of these errors during debt week.

**[edit 11.11]**: There are 8 errors left:

- [ ] `vs/base/browser/ui/tree/asyncDataTree.ts` @joaomoreno 
- [ ] `src/vs/workbench/api/common/extHostTypes.ts` @jrieken 
- [ ] `src/vs/workbench/api/common/extHostWebview.ts` @mjbvz

**Comment by isidorn** [comment]
Adding it to next milestone so it shows up in my issue query for debt week.
If we do not tackle it completely we can always move it to the next one afterwards.

**Comment by joaomoreno** [comment]
Went through a bunch of these.

**Comment by bpasero** [comment]
I am seeing quite a bit of these in the code:

`StrictNullOverride Nulling out ok in dispose`

I think that is not a good pattern and we should never do that, because disposing something is no guarantee that the code is not used anymore. This is causing NPEs left and right still.

**Comment by jrieken** [comment]
Yeah, I never understood why "nulling" during dispose is helpful? Is this a defence when items referenced by one leak?

**Comment by bpasero** [comment]
Since many of these seem to originate from @joaomoreno , let's wait when he returns.

**Comment by joaomoreno** [comment]
These are all from the old days, when we were all doing that. It doesn't make any sense. When strict null came in, these lines should've just been deleted.

**Comment by bpasero** [comment]
Assigning a few more pepole:
* @RMacfarlane comments
* @chrmarti quick input, walkthrough
* @aeschli theme service
* @joaomoreno scm, tree
* @sbatten menubar / title
* @jrieken exthostXYZ
* @mjbvz webview
* @alexandrudima parameter hints, editor options

I know maybe you are not the original author, but we need more help to get this down to 0. Sandy is out in October and I got some biggies to look at.

**Comment by weinand** [comment]
Added @weinand for debug

**Comment by jrieken** [comment]
- [ ] `extHostTypes`, Task @alexr00 
- [ ] `extHostDebug`, @isidorn @weinand 
- [ ] `extHostQuickOpen` @chrmarti 
- [ ] `extHostWebview` @mjbvz

**Comment by bpasero** [comment]
:tophat:

**Comment by bpasero** [comment]
Getting there:

![image](https://user-images.githubusercontent.com/900690/68032246-96c4a900-fcbd-11e9-9f36-147b3829f26c.png)

@chrmarti if you do yours I can maybe look into Sandeeps.

**Comment by chrmarti** [comment]
@bpasero Done. 👍

**Comment by bpasero** [comment]
Looks like Sandy is back :)

**Comment by sandy081** [comment]
Yes, I am back and on to this 😄

**Comment by sandy081** [comment]
✅

**Comment by bpasero** [comment]
Remaining:
![image](https://user-images.githubusercontent.com/900690/68596061-e1eb7280-049a-11ea-9a84-9152d9b93558.png)

@mjbvz d.ts & webview
@joaomoreno async tree
@jrieken extHostTypes (call hierarchy related it seems)

**Comment by mjbvz** [comment]
Fixed `extHostWebview` again. Down to four errors in three files:

- `viewsViewlet.ts`
- `asyncDataTree.ts
- `extHostTypes.ts`

**Comment by sandy081** [comment]
Ping @alexr00 for `viewsViewlet.ts`

**Comment by bpasero** [comment]
I went ahead and resolved those so that we do not have to play the catch up game all the time 👍
