### ISSUE TITLE
Auto updater do not remove old version from old location

### ISSUE THREAD

**Issue by daoluong** [microsoft/vscode#78163]
- VSCode Version: 1.33.0 and 1.36.1
- OS Version: windows 10 1903

Steps to Reproduce:

1. 1.33 installed in 'C:\Program Files'  dunno why it not removed
2. 1.36.1 installed in %AppData%\Local\Programs
3. json associated with 1.33
4. xml associated with 1.36
5. open 2 files and 1.33 and 1.36 open together with release note (anytime)

6. I removed 1.33 and any thing back to normal. 
7. Just wanna let you know that this issue exist 

Does this issue occur when all extensions are disabled?: Yes/No
what

**Comment by joaomoreno** [comment]
Thanks. Please make sure to only have one Code installed: either the system one (in Program Files) or the user one (in AppData).
