### ISSUE TITLE
there is no change but it says there is change (github)

### ISSUE THREAD

**Issue by canbax** [microsoft/vscode#78169]
Issue Type: <b>Bug</b>

When write a file the same as before and when there are warnings/problems

![image](https://user-images.githubusercontent.com/8426741/62128497-419f8280-b2dd-11e9-8514-ed3e3120482c.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.1
cypher-query-language|jak|1.0.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
vscode-yaml|red|0.4.1

</details>

**Comment by IllusionMH** [comment]
Looks like there might be changes in whitespace. Do you see any difference if you toggle "Show Trim Whitespace" using this icon?
![image](https://user-images.githubusercontent.com/1312662/62141609-8afbcc00-b2f5-11e9-8d20-6018c38e21fd.png)

Also you should see diff if you run `git diff` for uncommited & unstaged changes, `git diff --cached` for staged changes, or `git show <commit id>` if you already commited this file.

**Comment by canbax** [comment]
when I run `git diff` on the file it gives 
`warning: LF will be replaced by CRLF in src/styles.css.
The file will have its original line endings in your working directory`
probably line endings are changing
