### ISSUE TITLE
Items are inserted delayed

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#78162]
Testing #77427

Please see the attached recording

![array-setting](https://user-images.githubusercontent.com/172399/62124256-0f385a00-b2ca-11e9-9fdf-ad48a72194da.gif)

Notice how 'bb' is only shown after adding 'ccc'

**Comment by octref** [comment]
Good catch. The "fast update" only applied when list DOM element is in focus but not when list item is in focus.
