### ISSUE TITLE
Cannot remove the first entry

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#78160]
Testing #77427

Edit the TypeScript > TS Server > Plugin Path setting

1. Add 'aaa'
2. Add 'bbb'
3. Delete 'bbb' by hovering over 'bbb' and press 'x' 
4. Delete 'aaa'

-> You cannot delete the item, 'x' has no effect.

**Comment by octref** [comment]
Good catch, 0 index was converted to false.
