### ISSUE TITLE
Add a link to the settings description from the default settings.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#7816]
In the header:
![image](https://cloud.githubusercontent.com/assets/172399/16153696/b94f5844-34a7-11e6-8994-0c86c6923993.png)

add:

See http://go.microsoft.com/fwlink/?LinkId=808995 for the most commonly used settings.

@seanmcbreen pls chime in with regards to words.

**Comment by aeschli** [comment]
added the links, polished all labels,
