### ISSUE TITLE
Screen cheese when opening editor in small window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78165]
re https://github.com/microsoft/vscode/issues/78137

* use custom title
* make window as small as it allows it to be
* open a file (using quick pick)
* :bug: the title and status bar are bust (half back, half grey)

<img width="204" alt="Screenshot 2019-07-30 at 14 09 09" src="https://user-images.githubusercontent.com/1794099/62127954-a8b83980-b2d3-11e9-8de8-bf15e6df45fb.png">

**Comment by sbatten** [comment]
/cc joaomoreno 

also moving to september

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/78167 as they share the same fix

**Comment by bpasero** [comment]
I would expect:

![image](https://user-images.githubusercontent.com/900690/65965929-adc67000-e45f-11e9-8737-d2e06134362d.png)

I get:

![image](https://user-images.githubusercontent.com/900690/65965946-b6b74180-e45f-11e9-96d3-5523a04f2227.png)

**Comment by joaomoreno** [comment]
@misolori Adding you since it was likely broken by https://github.com/microsoft/vscode/issues/81573

**Comment by joaomoreno** [comment]
Also, after spending hours around these issues, I am now in favor of just having minimum size restrictions for the window, instead of making these unrealistic scenarios work. Toughts, @bpasero @misolori @sbatten ?

**Comment by sbatten** [comment]
@joaomoreno you know I'm in favor. Though we still have to be considerate of zoom levels

**Comment by joaomoreno** [comment]
Moving to October then.

**Comment by sbatten** [comment]
Our previous min size was 200 by 120. I've been playing with 600 by 600 which is still fairly small but keeps this issue from happening. Do we think this size is too big or realistic?

**Comment by joaomoreno** [comment]
LGTM
