### ISSUE TITLE
Screen cheese when toggling side bar with small window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78167]
re https://github.com/microsoft/vscode/issues/78137

Maybe the same as https://github.com/microsoft/vscode/issues/78165

* "normal" window size
* make side bar wide (~70% of the window width)
* hide sidebar (cmd+b)
* make window as small as possible
* show side bar
* :bug: massive screen cheese

<img width="205" alt="Screenshot 2019-07-30 at 14 12 54" src="https://user-images.githubusercontent.com/1794099/62128270-56c3e380-b2d4-11e9-901a-e7216a3c25be.png">

**Comment by sbatten** [comment]
@joaomoreno this is clearly not a reasonable window size, but we are a bit better with the old layout. In the old layout we kind of enforce the titlebar and status bar to be present and let the others go below minimum, but should we set a minimum window width and height that is the sum of all minimums?

**Comment by sbatten** [comment]
one thing I will say is that even though the screen goes crazy at that size, resizing the window to something reasonable always makes thanks work again

**Comment by joaomoreno** [comment]
Linux looks good: 
![image](https://user-images.githubusercontent.com/22350/62759626-2d4c4a00-ba82-11e9-9cb7-55814d129fa2.png)

**Comment by joaomoreno** [comment]
Nevermind, see something now:

![image](https://user-images.githubusercontent.com/22350/62759736-78fef380-ba82-11e9-8aaa-d4b1e0d348dc.png)

**Comment by joaomoreno** [comment]
> but should we set a minimum window width and height that is the sum of all minimums

We could do that, but we can also fix the overflowing rules that seem to be occurring here.

**Comment by joaomoreno** [comment]
Pushed something. @jrieken Can you give it a try again? I don't have access to macOS right now.

**Comment by jrieken** [comment]
Check, will test with next insiders since I don't know how to run with custom title bars in dev

**Comment by sbatten** [comment]
fyi @joaomoreno, had to revert your change as it breaks the menubar

**Comment by joaomoreno** [comment]
@sbatten More details? Steps?

**Comment by sbatten** [comment]
breakage was https://github.com/microsoft/vscode/issues/78768

**Comment by joaomoreno** [comment]
Got it. Here's a better fix: https://github.com/microsoft/vscode/commit/b6a4220a98cdf874df3feaa16f73559fe708c3b8

**Comment by jrieken** [comment]
<img width="376" alt="Screenshot 2019-08-27 at 16 22 25" src="https://user-images.githubusercontent.com/1794099/63779457-dd291080-c8e6-11e9-9833-019ea9dba778.png">

**Comment by jrieken** [comment]
Different, but still massive screen cheese

**Comment by joaomoreno** [comment]
Looks like the status bar is wrapping. Not good!

**Comment by joaomoreno** [comment]
Saw it on @jrieken's machine. Suggested fix: all parts and split-view-view instances should be `overflow: hidden`. Let's push that next week and have a month of coverage on that.

**Comment by joaomoreno** [comment]
@jrieken Pushed the `position: absolute` change we experimented with as well as an absolute position of splitview views which will help as well. There are still cases in which `scrollTop` and `scrollLeft` will be automatically messed around by the browser and the layout will look strange but not as broken as in the previous screenshots. Permanently fixing that would involve touching `scrollTop` and `scrollLeft` which would bring back those forced reflows from https://github.com/microsoft/vscode/issues/77856

**Comment by sbatten** [comment]
fyi @joaomoreno removed the same css overflow hidden value as last time given this breaks the custom menubar

**Comment by joaomoreno** [comment]
OK, sorry again @sbatten... @jrieken give it a try, if it's good enough let's leave as is. Else, we gotta tackle the menubar, since `overflow: hidden` does make sense in splitview views.
