### ISSUE TITLE
Toggling a find button does not re-evaluate the search

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#78170]
Testing #78108

Hava a folder with two files `aa.txt`, `aaa.txt`. 

- execute dir
- search for 'aa'
-> it matches 'aaa.txt'
- now change the find toggle to `Match whole word`

I would have expected that the find is re-evaluated and `aa.txt` is matched same as in the editor.

![image](https://user-images.githubusercontent.com/172399/62129112-309f4300-b2d6-11e9-82fb-f8165012333f.png)

**Comment by lramos15** [comment]
@Tyriar this isn't a feature even in the way the old search went, but we might want to align at least the functionality of the find widget with that of the editor, since the buttons look the same.

**Comment by ATheCoder** [comment]
@Tyriar can you please review my Pull Request (https://github.com/microsoft/vscode/pull/78327) for this?
