### ISSUE TITLE
Invoking 'tasks.fetchTask()' with a type filter fetches all tasks

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#78179]
The Npm Scripts Explorer calls `tasks.fetchTask({ type: 'npm' })`. This call will also fetch the tasks of type `gulp` which is expensive. The function should only fetch the tasks from the TaskProvider given as argument.

**added**
The current implementation has some unpleasant side effects. For example, open the NPM Scripts Explorer in the VS Code workspace. The script explorer fetches the npm tasks, but since the implementation fetches all tasks it will also fetch the gulp tasks. This not only makes the NPM Script explorer's population slow, it also shows an error from the gulp task provider, when opening the NPM Scripts explorer. This is highly unexpected. Even more so since the error message doesn't provide any hint about what went wrong. Clicking the link from the notification result in the output below

![image](https://user-images.githubusercontent.com/172399/62163042-d45e1280-b319-11e9-935b-5e0ecc51eef3.png)

![image](https://user-images.githubusercontent.com/172399/62163184-243cd980-b31a-11e9-8ec7-ea6e4153ec48.png)

**Comment by egamma** [comment]
@alexr00 I've should added some more information about the consequences of the current implementation. I've added more information to the description (see **added** above).

**Comment by alexr00** [comment]
This ended up being a nice simple change 😊
