### ISSUE TITLE
Panel should remember sizing before toggling editor area

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78175]
Testing https://github.com/microsoft/vscode/issues/78137

1. Open a folder
2. Close all editors
3. Close the panel
3. Run the Toggle Editor Area command
4. The panel takes over ✔
5. Open a file by clicking in the explorer.
6. See that the panel ends up a weird size:
<img width="1920" alt="panel" src="https://user-images.githubusercontent.com/38270282/62130452-537f2680-b2d9-11e9-920a-a854d63cfd7b.png">

**Comment by alexr00** [comment]
I'm still seeing this in bffbe2ea304a6a4cff23388703b0963f1dadec36

**Comment by sbatten** [comment]
I deleted a line that was definitely necessary for this to work ><
