### ISSUE TITLE
Grid state not correctly restored on restart

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78173]
Testing https://github.com/microsoft/vscode/issues/78137

Starting state that I made:
<img width="1920" alt="one" src="https://user-images.githubusercontent.com/38270282/62130004-53caf200-b2d8-11e9-8d5d-d7b8f6ee8054.png">
Then I moved one of the sashes:
<img width="1920" alt="two" src="https://user-images.githubusercontent.com/38270282/62130016-5e858700-b2d8-11e9-9f77-aa3be363bf8b.png">
Then I restarted:
<img width="1920" alt="three" src="https://user-images.githubusercontent.com/38270282/62130030-67765880-b2d8-11e9-8916-890bf107695b.png">

You can see that the sash position didn't save.

**Comment by sbatten** [comment]
@bpasero where does the editor grid stuff get saved, not sure why it wouldn't be properly saved in grid layout

**Comment by bpasero** [comment]
@sbatten it gets stored into the memento of the editor part:

https://github.com/microsoft/vscode/blob/8ebfa686ec8eafb4b25c7ee37a90bd21b59583dd/src/vs/workbench/browser/parts/editor/editorPart.ts#L939

**Comment by beastdestroyer** [comment]
I have been seeing this issue from time to time especially in the exploration electron 6 builds: my sidebar width still resets on starting up vscode

**Comment by bpasero** [comment]
@beastdestroyer and what is your setting for `workbench.useExperimentalGridLayout`?

**Comment by beastdestroyer** [comment]
@bpasero  It has always been on since introduced as a setting
![image](https://user-images.githubusercontent.com/30497573/62776993-0868ce80-baa4-11e9-9dd9-144fd1a2c632.png)

**Comment by bpasero** [comment]
I would wait for a more recent exploration build where a couple of changes went in specifically around serialization.

**Comment by sbatten** [comment]
@joaomoreno we can discuss this in our deep dive tomorrow as this results from the many layout calls happening during initial layout propagating down to the nested grid which gets a lot of different sizes ruining its serialized layout.

**Comment by joaomoreno** [comment]
Only happens for vertical sashes of the editor grid.
