### ISSUE TITLE
Error: Data tree node not found: [object Object] 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78185]
https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=9f557384-6b49-bd8a-4e01-3c103fc5da27

```
Error: Data tree node not found: [object Object]
/vs/base/browser/ui/tree/objectTree.ts#18:0 (delegate)
/vs/base/browser/ui/tree/objectTree.ts#26:2
/vs/workbench/contrib/extensions/browser/extensionsActions.ts#1820:30
at Generator.next ()
/vs/base/common/errors.ts#184:9
```

**Comment by sandy081** [comment]
Above call stack is not correct as it is not matching with the code.

**Comment by jrieken** [comment]
Sorry, the tools apparently deminifys wrongly. Simply use the minified version then. That said these errors occur at the rate of millions, not reason to ignore them.

**Comment by sandy081** [comment]
Agreed no reason to ignore them. But it would be great if you provide me the proper stack.

**Comment by jrieken** [comment]
Did you click the link?

**Comment by sandy081** [comment]
I did but I could not find the minified version

**Comment by sandy081** [comment]
/duplicate

But I think this is a dup of https://github.com/microsoft/vscode/issues/73469

**Comment by jrieken** [comment]
<img width="733" alt="Screenshot 2019-07-31 at 10 38 04" src="https://user-images.githubusercontent.com/1794099/62197127-9693d500-b37f-11e9-9961-7ed9bd3767b1.png">


That's (yellow) what I look at. Turns out the page is even more broken and despite saying 1.37 in the header the version is actually 1.36.1

**Comment by jrieken** [comment]
Tho, this shoud/could be the same with yesterdays insiders https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=0a4ae8ee-254f-fabc-9c94-748bd1cb99d2

**Comment by jrieken** [comment]
This is the explorer. I guess nothing new for @isidorn

**Comment by isidorn** [comment]
Yeah we already have issues for this https://github.com/microsoft/vscode/issues/73469
