### ISSUE TITLE
Pseudoterminal: Unclear what dimensions are

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#78180]
Testing #78123

```
const writeEmitter = new vscode.EventEmitter<string>();
		const dimensionsEmitter = new vscode.EventEmitter<vscode.TerminalDimensions>();
		let columns = 20;
		const pty: vscode.Pseudoterminal = {
			onDidWrite: writeEmitter.event,
			onDidOverrideDimensions: dimensionsEmitter.event,
			open: () => {
				dimensionsEmitter.fire({
					columns: columns,
					rows: 10
				});
			},
			handleInput: data => {
				if (data === '1') {
					columns+=10;
					dimensionsEmitter.fire({
						columns: columns,
						rows: 10
					});
				}
				writeEmitter.fire(data === '\r' ? '\r\n' : data);
			},
			setDimensions: dim => {
				console.log('setDimensions invoked: ' + JSON.stringify(dim));
			}
		};
		vscode.window.createTerminal({ name: 'Local echo', pty });
	});
```
Unclear to me what the relationship of `setDimensions` and `onDidOverrideDimensions` is.
Both use the type `TerminalDimensions`.

setDimensions is only called when the window is resized and seems to give you Panel deimensions  {"columns":148,"rows":10}

onDidOverrideDimensions seems to be about the inner text dimension

Looks like different names would help to understand

**Comment by Tyriar** [comment]
@aeschli any suggestions? "dimensions" refer to the outer panel dimensions, "override dimensions" let pty's override the panel dimensions to something smaller

**Comment by Tyriar** [comment]
I made some doc improvements to better clarify, still open to changes in the name if you have better ideas.
