### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by vajarov** [microsoft/vscode#78196]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. start a fresh instance of VS Code
2. In about 15 seconds, I get "extension host terminated unexpectedly". 

workaround: restarting the extensions host seems to make the problem go away.

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:15:22.972Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.801.1
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.9.1
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|2.5.2
chat|kar|0.15.5
vscode-azureappservice|ms-|0.15.0
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.614
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.2
debugger-for-chrome|msj|4.11.6
angular2-inline|nat|0.0.17
angular-console|nrw|8.0.10
material-icon-theme|PKi|3.8.1
typescript-hero|rbb|3.0.0
code-settings-sync|Sha|3.4.1
vscode-icons|vsc|9.1.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Does this problem reproduce with `code --disable-extensions`?

**Comment by jeremytbrun** [comment]
Also have this issue.

Running <pre>code --disable-extensions</pre> does not reproduce the issue for me.

**Comment by joaomoreno** [comment]
@jeremytbrun Then selectively disable extensions until you figure out which is the culprit.

**Comment by alexandrudima** [comment]
It's the `karigari.chat` extension. Please reach out to the extension author directly. See https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205
