### ISSUE TITLE
--list-extensions --category themes shows non-themes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78193]
Testing https://github.com/microsoft/vscode/issues/78106

When running `code-insiders --list-extensions --category themes`, I see a few extensions show up in the list that are not themes (highlighted):

![image](https://user-images.githubusercontent.com/35271042/62141417-6544d780-b2a1-11e9-8fcb-302e73d842f2.png)

**Comment by lramos15** [comment]
There's not much I can do here as GraphQL and Profile Switcher are both classified as themes in the marketplace even searching the market place for `@category:themes` will display them.
