### ISSUE TITLE
Reuse launchBrowser window tab

### ISSUE THREAD

**Issue by steveoh** [microsoft/vscode#78197]
It is really nice that we can F5 debug and launch our web applications. A nice improvement would be to reuse the window if you debug more than once. Currently, a new duplicate tab will be created every time you launch.

The only current solution that I know of is a little silly and involves having two almost duplicate launch tasks, one to open the window and one to skip doing that. I still have to remember to refresh the tab when the building is complete.

Other tools like react will reuse the same tab and refresh the content. This is a really nice developer feature and a productivity boost.

Can we add this functionality?

moved from https://github.com/OmniSharp/omnisharp-vscode/issues/3152

**Comment by isidorn** [comment]
This is due to the [`serverReadyAction`](https://github.com/Microsoft/vscode/blob/9c10972a11492288878a34584b692a137173d43a/extensions/debug-server-ready/src/extension.ts#L23), thus assigning to @weinand

**Comment by SSJ9899TDylan** [comment]
Lol


Sent from myMail for iOS


Wednesday, 31 July 2019, 7:34 pm +1000 from notifications@github.com  <notifications@github.com>:

**Comment by weinand** [comment]
This functionality relies on VS Code's ["openExternal" API.](https://github.com/microsoft/vscode/blob/28520b821089572888df26056d40ac53841f9531/src/vs/vscode.d.ts#L6181).

We would need some optional parameter (e.g. a window/tab name) to specify that the URL should be opened in an existing window/tab if possible.

@jrieken does this make sense? should I create a feature request?

**Comment by jrieken** [comment]
> @jrieken does this make sense? should I create a feature request?

I am afraid that we cannot do that. We use [`shell#openExternal`](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options) which doesn't support this

**Comment by weinand** [comment]
Missing upsteam API.
