### ISSUE TITLE
API to control the visibility of files in the File Explorer

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#78195]
As far as I can tell, there is no way for an extension to hide a file from the file explorer tree without modifying the workspace settings. I'd like to see a simple API for this.

**Comment by iansan5653** [comment]
Maybe it could be an extension of the proposed decoration provider API? Although it's not strictly a decoration, that could be implemented with minimal impact. A simple option on `DecorationData` like `visible: boolean` would be easy.

**Comment by isidorn** [comment]
@iansan5653 this is currently not possible using our API.
The explorer is not open in such a way to the API, extensions can only contribute FileSystemProviders, they can not customise what is shown in the local files.

I can leave this open as a feature request, even though we have no immediate plans to tackle this.

In the meantime you can write an extensions which add a context menu action "Hide" and which would just modify the workspace settings to actually hide the item.

**Comment by iansan5653** [comment]
Alright, thanks for the response. The reason I requested this was #38878, as it's not possible to implement that feature without an API like this.
