### ISSUE TITLE
Terminal Window does not parse line number for IAR compiler errors

### ISSUE THREAD

**Issue by rcsmith00** [microsoft/vscode#78205]
Issue Type: <b>Bug</b>

Using an IAR cross-compiler, if you click on the error, VS Code always navigates to line 1 of the file instead of the line with the error.  Here is some example syntax:

      myFunction();
                 ^
"C:\repos\file.c",80  Error[Pe165]:
          too few arguments in function call

      pVar = Var;
           ^
"C:\repos\file.c",81  Error[Pe513]:
          a value of type "uint32_t" cannot be assigned to an entity of type
          "uint32_t *"

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/commit/183deef5f43d77dc0c13e8accc41f5dff492a434
