### ISSUE TITLE
Preserve case behaves unexpectedly, taking caps from both source and replace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78204]
#78133

For this:

![image](https://user-images.githubusercontent.com/2193314/62153009-88c74c80-b2b8-11e9-8096-e097da9daca0.png)

The case of only the first capital from the search result is retained, not the second

![image](https://user-images.githubusercontent.com/2193314/62153022-8fee5a80-b2b8-11e9-9167-4046a4919660.png)

---

For this:

![image](https://user-images.githubusercontent.com/2193314/62153120-c4faad00-b2b8-11e9-9fb1-88e72064a8c0.png)

The case of the first capital from the search result is retained, not the second. The cap in the replace term is retained, but not the lowercase first letter

![image](https://user-images.githubusercontent.com/2193314/62153160-d348c900-b2b8-11e9-8ae2-0e9008f68844.png)

---

Maybe this isn't supported yet as per https://github.com/microsoft/vscode/issues/78133, it would be very confusing to people trying to use an incomplete feature though.

**Comment by Tyriar** [comment]
If this is not how you're meant to use the feature, should we disable the preserve case toggle if there are caps in the replace term?

**Comment by rebornix** [comment]
@Tyriar good suggestion, we should disable the option if the pattern is not supported yet.

**Comment by guidobouman** [comment]
Wait, how does this work exactly? In the examples I see multiple letters being capitalised in the final result. But when using a CamelCase word, this does not work in my source code? The first letter of the word is maintained, but any later capital in the same word is not preserved. Yet, for all-caps words it does seem to work?

<img width="468" alt="Screenshot 2019-09-10 at 14 09 44" src="https://user-images.githubusercontent.com/147413/64615782-7c680080-d3db-11e9-8573-60b1223877e8.png">
