### ISSUE TITLE
when i do alt-sht-f to format code it adds a semicolon to places with a starting parentheses and a starting curly bracket!! 

### ISSUE THREAD

**Issue by shpleef** [Microsoft/vscode#7820]
- VSCode Version:
- OS Version:

Steps to Reproduce:
![screen shot 2016-06-17 at 17 21 59](https://cloud.githubusercontent.com/assets/16339855/16155497/0a6efac4-34b0-11e6-89ca-899de54e44bc.png)

1. vscode 1.20
2. MacOsX El Captain

**Comment by tills13** [comment]
Fill out the OS version/vscode version as well - it really helps the devs out.

**Comment by dbaeumer** [comment]
Moving to the TS team which own the formatter.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9277
