### ISSUE TITLE
Support for Skype chat

### ISSUE THREAD

**Issue by hectormartin42** [microsoft/vscode#78209]
I will be great to have integrted skype chat on it

**Comment by hornta** [comment]
Disagree. Seems uneccessary. This is an IDE.

**Comment by lramos15** [comment]
There are various extensions which integrate chats from various platforms into VS Code. I would recommending taking a look at those and trying to write something similar for Skype.

**Comment by riazXrazor** [comment]
https://marketplace.visualstudio.com/items?itemName=riazxrazor.vscode-skype
I built a small extension for it @hectormartin42
