### ISSUE TITLE
Overtyping not working on html attributes via autocomplete

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78201]
Testing https://github.com/microsoft/vscode/issues/78118

**Steps to reproduce**
1. Open an HTML file
2. Create a `div` and use autocomplete for any attributes (ex: `class` or `id`)
3. :bug: When using autocomplete, typing a closing `"` will not overtype

Also noticed that when not using autocomplete and manually typing the attributes that it works (example below shows this when I add an `id`)

![Screen Recording 2019-07-30 at 10 38 29 AM 2019-07-30 10_40_04](https://user-images.githubusercontent.com/35271042/62152014-751ae680-b2b6-11e9-9646-cc847cba4d99.gif)

**Comment by sana-ajani** [comment]
Overtyping also works for me in this case (on Windows machine)

**Comment by sana-ajani** [comment]
I also see this on Windows! (overtyping doesn't work when autocomplete is used, but does when manually typing)

**Comment by alexandrudima** [comment]
Let's track in #78975
