### ISSUE TITLE
Peek Definition popup is displayed below visible area 

### ISSUE THREAD

**Issue by russelldavis** [microsoft/vscode#78202]
- VSCode Version: 1.36.1 (also repros on insider's build)
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:
1. Add the following code to a javascript file, following the instructions in the comments:
```js
function foo() {};


// Add enough blank lines here (or resize the window) so foo() is at the bottom of the editor


foo(); // This must be the last line. Don't add a newline here.
```
2. Place the cursor on `foo` on the last line.
3. Run the Peek Definition action.
4. The Peek Definition popup will show below the current line, outside of the visible area of the editor.
5. If there is an empty line at the bottom of the file, the problem goes away (the popup shows above the line like it should).

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> outside of the visible area of the editor.

Can you attach a screen shot of that? Can you also try with 1.37.0 insiders?

**Comment by russelldavis** [comment]
@jrieken yep, it happens on 1.37.0 insiders as well. Here's a screenshot (due to the bug, you have to scroll down to actually see more than the very top of the popup):


<img width="648" alt="Screen Shot 2019-07-31 at 8 52 02 AM" src="https://user-images.githubusercontent.com/551404/62227527-f0d96980-b370-11e9-82b9-2d0665a9d151.png">

**Comment by jrieken** [comment]
Thanks for clarifying

**Comment by jrieken** [comment]
This is due to a lack of editor API. We cannot reveal a view zone and our current workaround is to reveal the N+1 line - which doesn't exists in case you are on the last line...
