### ISSUE TITLE
Focus is lost when dismissing modal dialog in custom tree commands

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78208]
Testing #78101

- Install GitLens
- Navigate with keyboard to "Compare master (working) with..."
- Enter, Reveals quick open picker
- ESC to cancel
- Focus is lost

![bug](https://user-images.githubusercontent.com/4033249/62157062-2aeb3280-b2c1-11e9-8d51-46b760713936.gif)

Compare this with Git tree:

![good](https://user-images.githubusercontent.com/4033249/62157110-46563d80-b2c1-11e9-85bf-0bee0c57949f.gif)

**Comment by alexr00** [comment]
Also occurs in the old custom tree. Moving to August.

**Comment by eamodio** [comment]
@octref As long as https://github.com/microsoft/vscode/issues/78310 gets fixed, I've put some changes into GitLens to resolve this. Although it would be nice if focus was automatically restored to where it came from after the quickpick closed.

**Comment by alexr00** [comment]
@chrmarti this seems to be a more general problem with all quick picks. When you open a quick pick, focus isn't returned to the last focused item when is is exited.
