### ISSUE TITLE
Dark and Dark+ Theme Opacity

### ISSUE THREAD

**Issue by jordychetty** [microsoft/vscode#78215]
# Issue
Using **MacOS Mojave (v 10.14.6)**, when I change my display profile to anything other than the default, the opacity increases drastically on the Dark and Dark+ colour themes. The main editor window and explorer are predominantly affected.

## Steps to reproduce
- Change colour profile on MacOS. System Preferences > Displays > Colour, then choose a non-default profile (ACES CG Linear, for example).
- Choose Dark/Dark+ colour profile in VS Code.

## Expected results

A standard dark-mode themed application, with all panels consistently coloured.

## Actual results

Inconsistently coloured panels, primarily affecting the main workflow areas (editor window and explorer)

**Comment by misolori** [comment]
I don't believe this is a VS Code problem as it is a color profile issue. When I change my color profile from the default to ACES CG Linear (for example) this affects all applications windows, especially when on dark mode and using dark applications (Finder, Spotify, etc.)

If the default themes don't work well for you you can browse through[ other themes](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Downloads) or [create your own](https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme). Let us know if there is anything else we can help you with.
