### ISSUE TITLE
Emmet wrap empty lines

### ISSUE THREAD

**Issue by ksk-waqs** [microsoft/vscode#78219]
- VSCode Version: 1.36.1 (user setup)
- OS Version: Windows 10 Home x64

Steps to Reproduce:

![emmet-wrap-empty-lines](https://user-images.githubusercontent.com/3883054/62165197-93202f80-b326-11e9-9ddd-aa263586480a.gif)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by amang034** [comment]
I am interested to work on it, picking it up
