### ISSUE TITLE
Highlight disappears from items in Search 

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/vscode#78217]
Issue Type: <b>Bug</b>

This is kind of difficult to explain so bear with me. When you're performing a search in VS Code, and you select an item, that item is highlighted from the list in the left pane. However, as soon as you click the file open, and make a change, the highlighting on the left pane disappears. When trying to make bulk updates to a number of files, this is really frustrating because it's difficult to keep track of which file you just changed (since the highlighting disappears). 

The expected behavior is that any item open via search is highlighted perpetually until another item is selected from the search menu. This will make it much easier to figure out which file you haven't yet changed when performing bulk updates. 

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (17.22GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
vscode-markdownlint|Dav|0.29.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.12
docs-preview|doc|0.3.24
docs-yaml|doc|0.2.3
powershell|ms-|2019.5.0
vscode-yaml|red|0.4.1
code-spell-checker|str|1.7.17

</details>

**Comment by MashaMSFT** [comment]
i have a video example of this but i'd like to post it somewhere privately.. please feel free to contact me directly for further explanation :)

**Comment by roblourens** [comment]
I assume this is https://github.com/microsoft/vscode/issues/20467, let me know if you think it's different

**Comment by MashaMSFT** [comment]
i don't think so, i am not re-searching anything, i am just going down the list of items in my search pane. can you please provide me away to share this video with you, or maybe i can share my screen or something? thanks!

**Comment by roblourens** [comment]
That bug just involves doing a search, selecting a result, then editing that file. That sounds like what you are describing, but you can email your video to the address in my profile if you would like me to check!

**Comment by MashaMSFT** [comment]
so yes, that part is similar, but this part does not apply to what i'm doing:

now, edit the file (that contains the 2nd search result) so the line in that file no longer matches the search criteria.
notice how the 2nd search result disappears from the search results pane, and NO results are hilighted.
hit F4 again.
BUG: the first search result is hilighted.

emailing :)

**Comment by roblourens** [comment]
Yes, this is the same as the other one. It should really be fixed. Thanks for reporting!
