### ISSUE TITLE
Directories created under Linux don't show in VSC explorer on Windows

### ISSUE THREAD

**Issue by DeanRoddey** [microsoft/vscode#78216]
So I have a large C++ development environment repository ( https://github.com/DeanRoddey/CIDLib) which is highly portable and I'm working on the Linux platform driver for it. I created a sub-directory on the Linux side. When I git pull those changes down to the Windows side, the Linux created sub-directory doesn't show up in VSC's explorer.

I've checked the permissions of the directory and contained files and they are identical to the Win32 files. My local Windows account shows up as the owner of both. The directory is there from Window's point of view. If I try to get VSC to create a new sub-directory with that name it complains that the directory is already there. So it's not like it can't see it. But for some reason the explorer won't show it.

If I do a find in folder from the parent (build tool folder) for something that should be found in one of those Linux platform files, they are not found by the search.

Any ideas why that would be?

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:58:59.274Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT ia32 10.0.17763

**Comment by DeanRoddey** [comment]
Oh, man. Way too many details, way too few brain cells. I'd put the Linux directory into VSC's "Files: Exclude" list at some point for some reason. Presumably to avoid the Intellisense stuff scanning it and finding lots and lots 'errors' because so much of that code is not valid for Windows. And by default search has the 'Use Ignore Files' option checked so of course they wouldn't be found in a search.

Sorry about that. Not sure if there's a good solution there. Maybe the ability to exclude some directories from scanning, but keeping them visible or something.

**Comment by aeschli** [comment]
Does maybe the C++ extension have a way to configure which folders are included/excluded? That would probably be the better approach.

For any issues / feature requests with the C++extension, please use https://github.com/Microsoft/vscode-cpptools
