### ISSUE TITLE
Recent items not showing in taskbar list

### ISSUE THREAD

**Issue by hornta** [microsoft/vscode#78210]
- VSCode Version:
- OS Version:
![image](https://user-images.githubusercontent.com/4553604/62157516-a672d100-b30d-11e9-8284-7b1df75ff647.png)

Steps to Reproduce:

1. Open any folder
![image](https://user-images.githubusercontent.com/4553604/62157766-36b11600-b30e-11e9-953e-14cfd0197152.png)

2. Restart vscode, that folder is not in the recent list in the taskbar
![image](https://user-images.githubusercontent.com/4553604/62157847-5e07e300-b30e-11e9-8513-6613de3f153d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by hornta** [comment]
Same behaviour unfortunately.

**Comment by bpasero** [comment]
I cannot reproduce and have no idea why it does not work for you, sorry.

![image](https://user-images.githubusercontent.com/900690/62466958-ebc25300-b792-11e9-9bf8-3c668ccd5b95.png)

Maybe some Windows setting has any impact.

**Comment by hornta** [comment]
Is that workspace folders? I've only tried with the regular "Open Folder..." menu alternative

**Comment by bpasero** [comment]
@hornta no, these are normal folders I open with File > Open Folder.

**Comment by hornta** [comment]
But in your list you have the folders listed under "Recent Workspaces". In that case shouldn't it be listed under "Recent folders" or something like that?

**Comment by bpasero** [comment]
@hornta we actually decided to explicitly distinguish workspaces (that is single folders and/or code workspace files) from individual files so that they are not being mixed. As such, they both appear under the same category.

If you open a file (File > Open File), do entries then show up?

**Comment by hornta** [comment]
I've found the problem which is a Windows setting.

This was marked OFF for me. 
![image](https://user-images.githubusercontent.com/4553604/62468223-d69af380-b795-11e9-9242-fa2da1d97342.png)
