### ISSUE TITLE
Add promptPath as user input type for launch configs

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#78214]
Currently, a user input that is a path has to be declared as "promptString". Since VS Code has a path selector built-in, it would be great if this was exposed as new type, e.g. "promptPath".

**Comment by alexr00** [comment]
This would be pretty easy to do if you wrote an extension.

**Comment by letmaik** [comment]
Can you provide some more detail? Which contribution point is that?

**Comment by alexr00** [comment]
You could write an extension that contributes a new command `pickFile` that uses VS Code API to show the file picker. Example of an extension that contributes a command https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample
Then you could run that command from a task similar to https://code.visualstudio.com/docs/editor/variables-reference#_command-variables

**Comment by alexr00** [comment]
Also duplicate of https://github.com/microsoft/vscode/issues/71461, where after thinking about it some more I'm wondering if there's a simple way we could support this...
