### ISSUE TITLE
VS Code incessantly invokes an OpenSSH dialog

### ISSUE THREAD

**Issue by MIchaelMainer** [Microsoft/vscode#7821]
- VSCode Version:1.0.0
- OS Version: 10.0.10586

I'm using the git bash terminal on Windows 10 to work with repos. When I use a repo where I used SSH to connect to the remote repo, I get an OpenSSH dialog that requests my passphrase with 'Enter passphrase for key /c/..id_rsa'. The dialog gives me an OK and Cancel button. I press either one, the dialog goes away. It seems to pop up about every 5 to 10 minutes or so. It is driving me nuts.

Steps to Reproduce:

1. Clone a repo in the git bash shell using SSH.
2. From the terminal, open the current repo directory with `code . &`
3. Within a few seconds, the OpenSSH dialog opens up. 
4. I can press OK or Cancel, the dialog goes away. It will pop up again.

**Comment by OneOfOne** [comment]
Not really a solution, but `"git.autofetch": false` in your `settings.json` might help.

**Comment by MIchaelMainer** [comment]
@OneOfOne Thank you! That removed the annoying dialog prompt scenario.

**Comment by joaomoreno** [comment]
Disabling auto fetch or setting up a credential manager solves it.

**Comment by MIchaelMainer** [comment]
Thank you @joaomoreno ... As of today, disabling auto fetch appears to be the only option when using SSH.
https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/25

**Comment by danwulff** [comment]
I know this was closed awhile ago, but I thought I'd chime in that this same thing was occurring for me.
 
Following the top answer here worked for me: http://stackoverflow.com/questions/10032461/git-keeps-asking-me-for-my-ssh-key-passphrase

In git bash:
> eval $(ssh-agent)
> ssh-add

VSCode: 1.12.1
Win 10 Pro: 14393.1198
