### ISSUE TITLE
PowerShell not applying syntax highlighting color to methods

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#78212]
One of the first things I noticed when switching from Sublime Text 3 to VSCode for PowerShell code is VSCode doesn't change the syntax highlighting color for methods.  In Sublime Text 3 and PowerShell IDE, methods use a separate color.  VSCode method color is the same color as variables.  Below, both editors are using the same TextMate color scheme:

**Sublime Text 3:**
![Sub](https://user-images.githubusercontent.com/811008/62158400-270cdf80-b2c4-11e9-89c4-7a772183744f.png)

**VSCode:**
![VSCode](https://user-images.githubusercontent.com/811008/62158420-34c26500-b2c4-11e9-8d5d-b301107a2236.png)

I am hoping someone with more experience in VSCode might have a temporary workaround in **settings.json** until there's an official fix for this.  Wishful thinking.. but something like: below:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "method.definition.variable.powershell",
                "settings": {
                    "foreground": "#005757"
                }
            },
        ]
    }
```

- VSCode Version:  1.36.1 (user setup)
- OS Version:  (Windows 10 64bit)

Steps to Reproduce:

1.  Open PowerShell code that has PowerShell methods

**Comment by alexr00** [comment]
You can use the "Developer: Inspect TM scope" to get the correct scope for your setting:
<img width="388" alt="textmatescope" src="https://user-images.githubusercontent.com/38270282/62204939-8f27f800-b38e-11e9-8e25-ab0108996114.png">

You could also make your own theme that does colors the way you want.

**Comment by alexr00** [comment]
I'll fix it for the default themes.

**Comment by mkanet** [comment]
Thank you for the tip to use **"Developer: Inspect TM scope"**.  This was extremely helpful.
