### ISSUE TITLE
Deprecated Tag shows now indication in the Problems panel

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#78226]
Testing #78096

Diagnostics tags as deprecated don't show any indication in the Problems panel. Maybe they should?

**Comment by jrieken** [comment]
Adding @sandy081 for ideas but I believe we should not. We haven't done anything special for `DiagnosticTag.Unnecessary` something for which the editor has special rendering. So, unless we have a good idea or some inspiration from other tools I'd say to leave it.

**Comment by sandy081** [comment]
I agree. Hence I did not adopted it in problems view.
