### ISSUE TITLE
VS Code won't open with Linux Kernel 5.2.4

### ISSUE THREAD

**Issue by plsloan** [microsoft/vscode#78229]
- VSCode Version: 2213894e (from Ubuntu store)
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Run "code" in the command line
2. Output is...

/snap/code/11/electron-launch: line 28: /snap/code/11/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: No such file or directory
/snap/code/11/usr/share/code/bin/code: line 44: /snap/code/11/usr/share/code/bin/../code: No such file or directory

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you try downloading the Linux zip and see whether that runs?

http://update.code.visualstudio.com/latest/linux-x64/stable

**Comment by hmnd** [comment]
@joaomoreno this happened to me with the snap as well. The tarball runs fine.

**Comment by plsloan** [comment]
I just reverted back to Linux 5.1.21, but I would like to able to update when my programs will run. Perhaps this isn't a Code issue. Spotify, Code, and Telegram all would not start.

**Comment by zhenjieliang** [comment]
I am using manjaro and my kernel is 5.2.4-1-MANJARO.
my vscode installed from https://www.archlinux.org/packages/community/x86_64/code/

no problem at all. smooth as usual.

**Comment by joaomoreno** [comment]
> Spotify, Code, and Telegram all would not start.

Then it's snap related.
