### ISSUE TITLE
Grid Layout snapped terminal reverts to min size

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#78228]
Issue Type: <b>Bug</b>

1. Snap terminal away at the bottom of vs code
2. Reveal it again

The terminal will be the minimum size possible.

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by sbatten** [comment]
From slack:
> If you snap something, the cached size is always the minimum. It should be the where the sash starts dragging. I attempted to separate visibility and cached sizing so that you could have a cached size separate from your current size since dragging causes several layouts but I ran into a propagation issue with splitview and gridnodes.
