### ISSUE TITLE
Deprecated Tag strikethrough renders strangely multicolored

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#78225]
Testing #78096

When a strikethrough renders over some text it can change opacity and color multiple times depending on the underlying tokens. This makes the strikethrough look bad IMO. It should be one solid color and above the underlying text.

When two diagnostics overlap, it can be even worse:
![image](https://user-images.githubusercontent.com/6561887/62169939-955e9b80-b2de-11e9-9c1a-7f631f562c3e.png)

**Comment by jrieken** [comment]
Yeah, I agree but I am unsure if that can be achieved. We use text decorations and I believe that always picks up the foreground color. Tho, I believe in real world this will be less funky as language brains are likely only striking out single tokens/words not multiple tokens/statements. 

@alexandrudima Do you have an idea how we draw the strikeout different? Some special decoration?

**Comment by jrieken** [comment]
Turns out that `text-decoration-color` exists: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color
