### ISSUE TITLE
Distance based import suggestions for typescript

### ISSUE THREAD

**Issue by SephReed** [microsoft/vscode#78227]
The ordering of these two imports is illogical:

`import { ISpansJSON } from 'MultipleChoiceQuestion/src/MultiChoiceQue';`
![Screen Shot 2019-07-30 at 5 36 50 PM](https://user-images.githubusercontent.com/14002040/62170342-b16b3880-b2f0-11e9-9236-016616e3ad85.png)

`import { ISpansJSON } from '../ISpansJSON';`
![Screen Shot 2019-07-30 at 5 36 57 PM](https://user-images.githubusercontent.com/14002040/62170350-b62fec80-b2f0-11e9-925b-c6dd86400054.png)

I think it would be much more user friendly if the hierarchy for imports went:
1. Nearest by path
2. Ts > Js

I am often getting issues with auto-import going for dist instead of src too.

**Comment by SephReed** [comment]
Another nice priority would be importing from already existing paths, rather than new ones.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
