### ISSUE TITLE
Iframe webvviews capture keybindings

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#78224]
Issue Type: <b>Bug</b>

Testing #77132
On windows using iframe based webviews.

I'm unable to open the command palette because the iframe captures the keybindings. 

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Windows

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by mjbvz** [comment]
This should have been fixed by 201a9c8e4146b7ad00db36c843ecf7550fbef6bb
