### ISSUE TITLE
Settings UI: When "Add Item" out of view port, have to click 2x

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#78237]
testing #77427

When editor is zoomed in, pressing the "Add Item" button scrolls the settings to the top and it does not go into edit mode.

Steps to repro:

1. zoom in vscode  a few times
2. open settings ui and search for `skipshell`.  this setting has a very long description, so you can't see the "Add Item" button, like this:

![image](https://user-images.githubusercontent.com/1487073/62174698-baa7d580-b2ef-11e9-81aa-e64a34d5e6dd.png)

3. Scroll down and click on the "Add Item" button

![image](https://user-images.githubusercontent.com/1487073/62174715-cb584b80-b2ef-11e9-8eba-46dd367913d9.png)

Result: Settings scroll back to the top

![image](https://user-images.githubusercontent.com/1487073/62174736-d9a66780-b2ef-11e9-8540-da33f03265ef.png)

And if you scroll down again, you can see that the "Add Item" button is still there, I have to click it again to get the input field.

![image](https://user-images.githubusercontent.com/1487073/62174776-f2168200-b2ef-11e9-8571-c68634a90f42.png)

If i click the "Add Item" button again, it then goes into edit mode

![image](https://user-images.githubusercontent.com/1487073/62174797-022e6180-b2f0-11e9-9883-383275658ced.png)

You can "reset" this by toggling to `json` view

**Comment by chrisdias** [comment]
This happens with more than just "Add Item".  If I click on the text box or "Cancel" etc it will scroll back up as well.

**Comment by octref** [comment]
@roblourens Seems to be a setting tree issue. First time clicking the add button doesn't get the event.

**Comment by roblourens** [comment]
@joaomoreno I don't think there isany way to query the height of an element, would it make sense for the tree to expose that? I only care about it after the element has been rendered. I am also not against just looking at the DOM.

Note to self, this is from https://github.com/microsoft/vscode/blob/2afeba767c4f01eeab94dbc3facf8a74bdc32044/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L627, the point is to fully reveal the setting when navigating with the keyboard, but I should not do that if the setting is taller than the current viewport.

**Comment by joaomoreno** [comment]
Yeah we can definitely expose it. I'm wondering though if `reveal` should be smarter and do the better thing here: do not touch the scrollTop if the element is already revealed in this way. What do you think?

**Comment by roblourens** [comment]
That makes sense. I can also imagine someone wanting `reveal` to always reveal the top of the element regardless of where the bottom is. I don't think there's a real use case for that right now but `reveal` could take a parameter to switch.

**Comment by joaomoreno** [comment]
`reveal` does have a `relativeTop` which allows you to specify if you want the item aligned to the top (0) or bottom (1). When the element's height is larger than the viewport, `relativeTop` could still mean:

- `0`: align it to the top
- `1`: align it to the bottom
- `undefined`: just make it visible; if already visible, do nothing

**Comment by roblourens** [comment]
That makes sense, if "already visible" means "completely visible"

**Comment by joaomoreno** [comment]
Yeah you're right, thanks for removing the ambiguity there. 👍  Let's do it.

**Comment by roblourens** [comment]
@joaomoreno please take a look at https://github.com/microsoft/vscode/commit/dfaff021a84c91e687c53ddfcd454a2a94f36ed3, it's pretty simple
