### ISSUE TITLE
Expose command for "Switch to Inline View"

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#7823]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.4

The "..."-menu in the "Changes View" offers "Stage Selected Lines" and "Switch to Inline View"/"Switch to Side by Side View", which are (sadly) not listed in the API.
Also, a command for staging the current hunk would be nice.

**Comment by dbaeumer** [comment]
@joaomoreno adding you for the "staging current hunk" request.

**Comment by joaomoreno** [comment]
These two commands are easy to add, wanna give it a try with a PR?

**Comment by dbaeumer** [comment]
@jrieken I assigned you because of the API request: 

The "..."-menu in the "Changes View" offers "Stage Selected Lines" and "Switch to Inline View"/"Switch to Side by Side View", which are (sadly) not listed in the API.

**Comment by rebornix** [comment]
Anyone wants to add a new command to the diff view menu bar can take a look at https://github.com/Microsoft/vscode/pull/6896 , it's as simple as that.

**Comment by vogler** [comment]
Some other things I noticed:
- there's no "Unstage Selected Lines" for staged changes
- "Stage Selected Lines" always uses the right side of the diff for selection, which makes deletions hard to handle: selecting the line before the hunk, stages the whole hunk, i.e., selecting single lines isn't possible. Also, selecting one change on the right, then another change on the left, I would expect the most recently selected line to be staged. Why wasn't this command moved into the context menu? Would make much more sense IMO.

**Comment by rebornix** [comment]
@vogler Try Insider build and you will see the "Unstage" feature.

**Comment by joaomoreno** [comment]
@vogler You've caught it all. 😄 There's quite a bit of work to be done there.

**Comment by ice-blaze** [comment]
@joaomoreno Is this issue still up to date with the latest version of march 1.11 ?

**Comment by joaomoreno** [comment]
The `Switch to Side by Side View` command is still not exposed. We should get to that.

**Comment by bpasero** [comment]
Exists as `toggle.diff.editorMode`

**Comment by vogler** [comment]
For anyone getting here before the next release, my workaround was
~~~
    {
        "key": "cmd+m cmd+d",
        "command": "git.openChange",
        "when": "!textCompareEditorVisible"
    },
    {
        "key": "cmd+m cmd+d",
        "command": "git.openFile",
        "when": "textCompareEditorVisible"
    },
~~~
