### ISSUE TITLE
Grid: Can hide editor and terminal when sidebar is on the right

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#78230]
Issue Type: <b>Bug</b>

If the sidebar and panel are both toggled to the right then when you drag the sidebar out  it can become large enough to cause the terminal and editor to both hide.

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by joaomoreno** [comment]
Can't repro on latest.

**Comment by sbatten** [comment]
requires 2 drags for me but still repros

**Comment by joaomoreno** [comment]
@sbatten Maybe a video/exact steps?

**Comment by sbatten** [comment]
1. Put panel on the right
2. Put sidebar on the right 
3. Use sash to hide editor, release mouse
4. Use sash to hide panel
5. You now have a window sized sidebar

**Comment by joaomoreno** [comment]
This is what I see after step 4:

![image](https://user-images.githubusercontent.com/22350/62867811-74ea0480-bd14-11e9-9f9a-7649242ea916.png)

When I the panel hides, the editor shows. Looks good to me.

**Comment by joaomoreno** [comment]
Strange behavior, yes, but not incorrect:

![Peek 2019-08-12 15-21](https://user-images.githubusercontent.com/22350/62868001-ecb82f00-bd14-11e9-9d38-2ad7026c6513.gif)

**Comment by sbatten** [comment]
@joaomoreno I now see this too in master, something done since 4 days ago has fixed the issue, This behavior is reasonable enough imo as it doesn't let you break the UI anymore.
