### ISSUE TITLE
--list-extensions "installed" category filter doesn't work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78234]
#78106

![image](https://user-images.githubusercontent.com/2193314/62174313-546e8300-b2ee-11e9-8bd3-743f09d2e20a.png)

Should just show everything?

**Comment by lramos15** [comment]
Installed is not a valid category if you do `code-insiders --list-extensions --category` without specifying a category it will list out all the valid categories. I also have pushed a change which should be in todays insiders to tell you if you specify a valid category. Valid categories are the ones that you can search with in the extension viewless when doing `@category:`.
