### ISSUE TITLE
Overtyping doesn't factor in escape characters

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#78231]
Testing https://github.com/microsoft/vscode/issues/78118 

Version: 1.37.0-insider (commit: cf03ea3729dc37e439d724267ad29dc5840f903a)
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Escape character (backslash) triggers overtype. Expected behavior should be that \' would be within the original autoinserted ' '.

![escape overtype](https://user-images.githubusercontent.com/9721254/62173979-fbeab600-b2ec-11e9-9857-f4a6b11057d5.gif)

**Comment by alexandrudima** [comment]
Duplicate of #53357
