### ISSUE TITLE
Add a "Toggle Word Wrap" button to the Output window

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#78245]
Visual Studio's Output window has a "Toggle Word Wrap" button, but VS Code has word wrapping always (?) enabled. For certain scenarious like the pending "C/C++ References" output it is desirable for word wrapping to be disabled for the results to be more easily read. There is a "View: Toggle Word Wrap" command, but it applies to the active document only (and not the Output panel, even if it's active).

And/or if the OutputChannel interface could add a toggleWordWrap capability, that would allow extensions to set an appropriate default for their particular Output channel.

This seems like a pretty basic feature that other Output channel providers would want, but I couldn't find an existing feature request on this.

**Comment by ol-bones** [comment]
https://github.com/microsoft/vscode/issues/21468

This describes the same issue and led adding a config option but it doesn't seem to work or the feature request was misunderstood?

**Comment by sean-mcmanus** [comment]
@ol-bones Thanks a lot -- I can use that [Log] setting as a workaround; however, the result is still not ideal because it will apply to all Output windows and our extension would prefer to isolate the behavior to a specific one. (And a button in the UI would make it easier to discover than a hidden setting that isn't even auto completed that most users won't be able to discover).

**Comment by panchalkalpesh** [comment]
Currently, one workaround is to set:
```
"[Log]": {
    "editor.wordWrap": "on" // "off", "bounded", "wordWrapColumn"
},
```

**Comment by sean-mcmanus** [comment]
@panchalkalpesh Yes, that is the same workaround I was describing (which our C/C++ extension uses), but it applies to all the output panes, and we'd prefer to isolate the change to a particular output pane (e.g. "C/C++" or "C/C++ References" and not "Git", etc.).

**Comment by panchalkalpesh** [comment]
@sean-mcmanus that's a nice to have feature.

**Comment by KayvanShah1** [comment]
For log files, I had the word wrap button visible & after a few moments it just disappeared

**Comment by bobbrow** [comment]
It looks like the 'editor.wordWrap' setting no longer works for [Log].  Was it removed intentionally?

**Comment by bobbrow** [comment]
Ah, it's working for me now.  It looks like it requires a Reload Window after it is set.

**Comment by sandy081** [comment]
`View: Word Wrap` command is now also supported for Output Channels.
