### ISSUE TITLE
String Array Settings: Cannot empty field

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#78240]
Testing https://github.com/microsoft/vscode/issues/77427

If I clear out the input field and press "Save", the edit is thrown away.  I would expect that either an empty string is inserted into the array or the item is removed.

To repro:

* add a new string array setting `foo`, press "OK" to commit it
* now click on the pencil to edit the item `foo`.  clear out all of the characters so the input field is empty, click on "OK" to save

Result: `foo` is reverted back into the input field.

Expect: Either the element is deleted or an empty string is persisted to the array. I don't know exactly which I prefer.

**Comment by octref** [comment]
Good catch. I'll go with "removing item".
