### ISSUE TITLE
GridLayout for empty workspace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#78244]
Issue Type: <b>Bug</b>

When opening an empty workspace on a SSH box using Remote-SSH, we programmatically reveal the explorer as well as the terminal. When doing so, the sidebar as well as the panel are too narrow.

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1018-azure
Remote OS version: Linux x64 4.18.0-1018-azure

**Comment by sbatten** [comment]
resolved elsewhere
