### ISSUE TITLE
Freeze when collecting search result

### ISSUE THREAD

**Issue by Amadeea** [microsoft/vscode#78248]
Issue Type: <b>Bug</b>

Using find in files feature, type "iris" on the search input. 
Hit Enter
And vs code will freeze (cannot do anything including profiling)
I think it is not about too much search result. The search result is few but it keep freezing. 
For other keywords are fine (even with more larger search result). Not yet find another keyword which will cause the freeze.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
php-intellisense|fel|2.3.10
theme-monokai-pro-vscode|mon|1.1.13
vscode-docker|ms-|0.7.0
Go|ms-|0.11.4
material-icon-theme|PKi|3.8.1
html5-boilerplate|sid|1.0.3
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Can you try this in Insiders? I might have fixed this already. If not, can you share this repo?
https://code.visualstudio.com/insiders

**Comment by NPrada** [comment]
I am having the same issue when searching for "rightBar", it either freezes when I search for the word or when I click on one of the results
VS Code version: Code 1.36.1
OS version: MacOS Mojave 10.14.5

**Comment by NPrada** [comment]
Seems to be fixed for vscode insiders

**Comment by warpdesign** [comment]
I am having the same problem from time to time with VSCode 1.37.0 on macOS Mojave. It doesn't happen all the time.

**Comment by roblourens** [comment]
I will close this, anyone still having problems please open a new issue.

The only real known issue here is with matches in very long lines.
