### ISSUE TITLE
When resizing tab width smaller, Find window truncated.

### ISSUE THREAD

**Issue by leedonhyun** [Microsoft/vscode#7824]
- VSCode Version:

Version 1.3.0-insider
Commit 93e65224d7598017bfa0b188a0d82b66a2ee9698
Date 2016-06-17T05:08:31.587Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version:
  windows 10
1. 

![animation3](https://cloud.githubusercontent.com/assets/8449892/16156842/fc588aea-34f0-11e6-983b-90f451df9921.gif)
1.

**Comment by alexandrudima** [comment]
This has been fixed, the find widget resizes when there is not enough space.
