### ISSUE TITLE
Items list does not refresh correctly

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#78242]
While testing https://github.com/microsoft/vscode/issues/77427

Issue Type: <b>Bug</b>

1) Start with `code-insiders --user-data-dir ./<something new>`
2) Open the Settings editor
3) Filter the Settings editor to “commands to skip”
4) `Add Item` for  “Commands to Skip Shell”
5) Paste `aaaa aaaaa aaaaa aaaaa aaaa aaaaa aaaaa aaaaa aaaa aaaaa` as value and press “OK”
6) Repeat steps 4 and 5 
-> new value does not show up; you first have to change selection

![wrong-edit-mode](https://user-images.githubusercontent.com/4674940/62175155-50903000-b2f1-11e9-8f7a-4b95c1a23982.gif)

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:10:53.695Z)
OS version: Darwin x64 18.6.0

**Comment by octref** [comment]
This is already fixed in yesterday's insiders as part of #78162.
