### ISSUE TITLE
exePath variable doesn't resolve as integrated terminal variable

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#78246]
- VSCode Version: 1.37.0 Insiders
- OS Version: macOS

Found will testing https://github.com/microsoft/vscode/issues/78122

Steps to Reproduce:

Try to set

```json
 "terminal.integrated.cwd": "${exePath}"
```

No new terminal is created and you see "The terminal shell CWD "${exePath}" does not exist.

**Comment by Tyriar** [comment]
execPath gets resolved

**Comment by gregvanl** [comment]
Oops
