### ISSUE TITLE
F11 (step into) when debugging sometimes triggers the Full Screen command

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#78251]
Issue Type: <b>Bug</b>

I've only noticed this fairly recently, but when debugging sometimes pressing `F11` results in the full screen command rather than step into.

It seems like this was also noted here: https://github.com/microsoft/vscode/issues/70932#issuecomment-475813664

/cc @isidorn 

VS Code version: Code - Insiders 1.37.0-insider (d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c, 2019-07-31T05:24:41.973Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
It could have happened that you were debugging and not being stopped.
In that case the Step Into is disabled and Full Screen takes over F11.
I have changed this such that now F11 is never Full Screen while you are debugging.

Try it out and let me know how it works for you from tomorrow's insiders.
Thanks

**Comment by eamodio** [comment]
@isidorn The change looks good -- thank you!

**Comment by sandy081** [comment]
What are the steps to verify?

**Comment by eamodio** [comment]
I did the following:
1. Ensure that F11 toggles full screen mode outside of a debug session
1. Ensure that F11 steps into when paused in a debug session
1. Ensure that F11 does nothing when running in a debug session

**Comment by isidorn** [comment]
@eamodio thanks for verifying!
