### ISSUE TITLE
Add test or general spinning status to status bar

### ISSUE THREAD

**Issue by zenozen** [microsoft/vscode#78254]
My usecase is I have a TS project, and besides having VSCode checking my code using tsserver, I also ran **`tsc --watch`** on the side to instantly emit code.

I was having issues with compilation speed of tsc, and the thing is, after changing my code and as soon as tsserver finishes type checking the code, I want to run it (the emitted JS) right away, but cannot since TSC hasn't finished built yet. 

It takes about 3-4 seconds to finish the incremental compilation. So I have to constantly switch between the `Problems` panel and `Terminal` to make sure TSC finishes the build.

The idea is having the `problemMatcher` config to include status matching as well, for example, 
- as soon as `File change detected. Starting incremental compilation...` shows up in the build task's output, we know TSC is building
- after error/success message shows up, we know it's finished. This can be reflected on the status bar, so that I don't have to switch to terminal panel to make sure TSC is done.

I asked on forum and get back the answer of no such extension/thing exists yet to solve the specific problem. Also I imagine this would benefit other languages/environments as well, for example, 
- webserver restart after changing the code 
  * this applies to all environments as long as there's anchor texts, and the good thing is, it's totally customizable
- Continuous unit test run
- Scala's continuous build with sbt

Just to name a few. I can see this being useful for many users as well.

**Comment by alexr00** [comment]
We already show this in the status bar when building: 

<img width="103" alt="building" src="https://user-images.githubusercontent.com/38270282/62204071-bbdb1000-b38c-11e9-9e73-3ad5fd9f00c5.png">

Does that accomplish what you want?

**Comment by zenozen** [comment]
No it doesn't. I'm using `tsc --watch`. While tsc watch is running, this `Building` badge is always showing and spinning, despite of the status of tsc.

If the build task is set to run manually (tsc without watch), then the current building badge probably works.

**Comment by alexr00** [comment]
That sounds like it could be a bug with our typescript task detection then. Building should only show while it's building in this case. Can you share your task?

**Comment by zenozen** [comment]
For sure. Thanks for replying.

I was using a custom npm command, which copies a bunch of stuff and then start `tsc --watch`, but I tried changing to what the [doc](`https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks`) says, here is what it looks:

![image](https://user-images.githubusercontent.com/292364/62393856-41db9000-b520-11e9-9e9d-0b2fb3d7f494.png)
![image](https://user-images.githubusercontent.com/292364/62393889-67689980-b520-11e9-850f-1407bc8c875d.png)

Anything I might be doing wrong?

The text version if that makes things easier:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Build",
      "command": "tsc",
      "args": ["-p", "tsconfig.json", "--watch"],
      "problemMatcher": ["$tsc-watch"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "reveal": "always",
        "focus": false,
        "panel": "dedicated"
      }
    }
  ]
}
```

**Comment by alexr00** [comment]
I can repro with that. Thank you!

**Comment by alexr00** [comment]
I'm looking into what's going on with the task you have, but until I fix it, is it possible for you to use:
```
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"option": "watch",
			"problemMatcher": [
				"$tsc-watch"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"presentation": {
				"reveal": "always",
				"focus": false,
				"panel": "dedicated"
			}
		}
```
?

**Comment by alexr00** [comment]
I should have noticed this earlier. It is a problem with your task. When you use a watching problem matcher, you need to include `"isBackground": true` in your task.

**Comment by zenozen** [comment]
@alexr00 Thanks for replying!

However, I tried `isBackground: true`, doesn't seem to work for me (`Building` badge still spinning)

![image](https://user-images.githubusercontent.com/292364/62481962-c1f43680-b768-11e9-8a33-b59d717409e2.png)

Anything I might be doing wrong?

**Comment by alexr00** [comment]
Task I used:
```
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"option": "watch",
			"problemMatcher": ["$tsc-watch"],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"isBackground": true,
			"presentation": {
				"reveal": "always",
				"focus": false,
				"panel": "dedicated"
			},
		}
```
The Building... showed and hid correctly. Did you by chance forget to reload after running one of the bad tasks?

**Comment by zenozen** [comment]
@alexr00 Thanks for following up!

I might've know where the issue is. I pulled a Windows VM and tried your config with the same project, it DOES work.

However, on my macOS, the building badge is always spinning. So this seems to be an OS issue.

**Comment by alexr00** [comment]
Maybe it is a language issue and the regex isn't matching the characters in the timestamp? What language do you use on your mac and what language on Windows?

**Comment by zenozen** [comment]
@alexr00 They're both English. So it doesn't seem a language issue

**Comment by alexr00** [comment]
The timestamp on the terminal here is not 100% english: https://github.com/microsoft/vscode/issues/78254#issuecomment-518317920
Where are those non-english characters coming from?

**Comment by zenozen** [comment]
@alexr00 Ooooh. Right, yeah, that's the problem. Sorry about that. When I tried on my friends English machine, `isBackground` is not there.

Thanks for helping me debug this.

It might be helpful for the default regex to handle such cases, since the anchor text is really the message after the timestamp, not the timestamp itself.

Also One Q before I close this one, is it possible to add a custom badge to the status bar, for non-build task? I think it would be really useful, like restarting webservers, monitoring background processes. If you think that makes sense, I'll update the task description for that.

**Comment by zenozen** [comment]
Actually, just did some experiment. 

It seems that as long as I have `"group": "build"` in my webserver task with correct patterns, the `Building...` badge will be spinning. It's already very nice, even though both task would show "Building..." which is sort hard to tell which one is running.

Tried group setting to `test` showing no spinning icon. I guess one thing we could do is to have a `Testing...` spinning to differentiate build and test task.
