### ISSUE TITLE
Code hint is invalid on mac

### ISSUE THREAD

**Issue by Przeblysk** [microsoft/vscode#78253]
- VSCode Version: 1.36.1 
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. create a react project with creat-react-app
2.Try to enter a life cycle function

Does this issue occur when all extensions are disabled?: Yes
### Mac
![image](https://user-images.githubusercontent.com/18001272/62189034-99eb8880-b3a0-11e9-975c-e959c3e12d48.png)

### Windows
![image](https://user-images.githubusercontent.com/18001272/62189012-89d3a900-b3a0-11e9-954c-beb0ceb46b72.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by mjbvz** [comment]
Also share the code as text, not just a screenshot
