### ISSUE TITLE
softwareupdate_notify_agent

### ISSUE THREAD

**Issue by marcbourlon** [microsoft/vscode#78256]
Issue Type: <b>Performance Issue</b>

Hi all,
My Code process is taking a lot of CPU. If I quit Code, then CodeHelper keeps taking this same amount of CPU. I had notice prior to this time that it seemed related to updates, and indeed, when I ps aux | grep the pid as requested in the long performance thread, I saw this line, attached to my Code Helper PID:
/System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdate_notify_agent
CodeHelper process is stuck at 99.9% (of one core?), and if I launch Code, it's even worse. I killed Code Helper, but it comes back as strong as before, and I don't get any notification regarding an update to apply...

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 6, 4|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    98	  3279	code main
    8	    49	  3280	   gpu-process
    5	   246	  3282	   window (ClientFinder.cmp — 2) ABSA Onboarding VSC)
    3	   229	  3288	     extensionHost
  103	   147	  3291	       electron_node server.js 
    0	    66	  3292	       electron_node server.js 
    0	   131	  3294	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=3288
   76	   131	  3298	       electron_node server.js 
    0	    49	  3305	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3288
    0	    98	  3317	       electron_node visualforceServer.js 
  238	   180	  3328	       /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java -cp /Users/marcbourlon/.vscode/extensions/salesforce.salesforcedx-vscode-apex-46.7.0/out/apex-jorje-lsp.jar -Ddebug.internal.errors=true -Ddebug.semantic.errors=false apex.jorje.lsp.ApexLanguageServerLauncher
    0	    49	  3289	     watcherService
    0	    49	  3299	     searchService
    2	    82	  3290	   shared-process
    0	     0	  3371	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    5	    82	  3356	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ClientFinder.cmp — 2) ABSA Onboarding VSC)
|    Folder (2) ABSA Onboarding VSC): 328 files
|      File types: xml(107) json(73) js(30) cls(17) png(14) cmp(12) design(12)
|                  css(9) svg(8) ts(7)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.4.3
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
beautify|Hoo|1.5.0
python|ms-|2019.6.24221
mq4|ner|1.0.4
vscode-yaml|red|0.4.1
salesforcedx-vscode|sal|46.7.0
salesforcedx-vscode-apex|sal|46.7.0
salesforcedx-vscode-apex-debugger|sal|46.7.0
salesforcedx-vscode-apex-replay-debugger|sal|46.7.0
salesforcedx-vscode-core|sal|46.7.0
salesforcedx-vscode-lightning|sal|46.7.0
salesforcedx-vscode-lwc|sal|46.7.0
salesforcedx-vscode-visualforce|sal|46.7.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by joaomoreno** [comment]
If you run with `code --verbose` is there any interesting output when you hit the issue?

Does the issue reproduce often?

**Comment by marcbourlon** [comment]
Hi joaomonero, thanks for the quick reply! Actually, I forced quit Code, and the Helper, waited for a bit, restarted, it went fine. However yes, it happens relatively frequently that Code starts taking up CPU, but not to that extent.

**Comment by joaomoreno** [comment]
When it happens, try to correlate with what you're doing: what actions you've executed, what files you have open, what extensions you are using etc.
