### ISSUE TITLE
Edge: Web view sample is not working with http and local resource

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#78258]
Testing https://github.com/microsoft/vscode/issues/78050

Cat coding web view sample is not loading the gif with http or local file resource.

![image](https://user-images.githubusercontent.com/10746682/62194692-044bfb00-b398-11e9-889d-6de4c11e3675.png)

**Comment by mjbvz** [comment]
What edge version / os did you test this on? 

With  77.0.235.5  on MacOS, I see the image loading but the script sometimes does not execute. Always seems to work in normal Chrome (76.0.3809.100)

**Comment by sandy081** [comment]
Yeah chrome was working. Its on MacOS and edge Version 77.0.235.5 (Official build) Dev(64-bit)

**Comment by mjbvz** [comment]
@sandy081 You still see the images not loading as well? This could potentially be https://bugs.chromium.org/p/chromium/issues/detail?id=978325
