### ISSUE TITLE
Keyboard shortcuts randomly stop working

### ISSUE THREAD

**Issue by Gooseman** [microsoft/vscode#78257]
Issue Type: <b>Bug</b>

The problem is random, so there are no steps to reproduce the problem.

I still regularly have problems with shortcuts I've created that include use of Alt and a vowel.  For instance, I use Ctrl + Alt + e to move to the end of the current line.  Most of the time this results in the character é rather than the execution of the shortcut.  This has gotten much much worse since my work machine was switched to Windows 10 from Windows 7.  So far there are no Windows settings I can find that might affect this, not to mention that there's no change in my Windows setup between when it works as expected and when it doesn't.  I have VSCode open most of the time and without shutting it down and reopening it it'll just occasionally switch back and forth between executing the shortcut and inserting the character.

Until today I was just accepting this as an insurmountable bug in the VS Code software (since it doesn't happen in any other software which uses Alt and a vowel in a shortcut).  However, now other shortcuts have decided to stop working.  The one I noticed (I haven't the time to test every possible shortcut) is Ctrl + Alt + Arrow.  This is supposed to do column select, but now it does nothing.  Alt is simply turning on the accelerators in the app menu.

Why is it that VS Code is unable to interact consistently with a keyboard?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.4.4
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
code-runner|for|0.9.11
vscode-lombok|Gab|0.9.8
beautify|Hoo|1.5.0
cs-syntax-visualizer|itn|0.0.2
csharpextensions|jch|1.3.0
vscode-sbt-scala|lig|0.2.4
prettify-json|moh|0.0.3
mssql|ms-|1.6.0
python|ms-|2019.6.24221
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
vscode-jest|Ort|3.0.2
java|red|0.47.0
scala|sca|0.3.4
html5-boilerplate|sid|1.0.3
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by alexandrudima** [comment]
Ctrl+Alt+letter combinations are often interpreted on Windows machines as AltGr+letter. See https://en.wikipedia.org/wiki/AltGr_key#Control_+_Alt_as_a_substitute

This can be improved if switching to a keyboard layout like Standard US English which produces no accented characters even with AltGr.

As for the Ctrl + Alt + arrow, I think you have installed new software on the machine (very likely a certain Intel Display driver) which steals the ctrl + alt + arrow key combinations (very likely to rotate the screen).

I also notice you are using a high number of extensions (and extensions can customize built-in keybindings). Did you try to reproduce the ctrl + alt + arrow issue with disabling all extensions first?

**Comment by Gooseman** [comment]
Yes, I know the tired old excuse that it's somehow my fault.  Unfortunately since the information I gave shows that it's certainly not related to changing keyboard layouts - it's not like I'm sitting at my machine and changing my keyboard layout regularly - it's pretty weird that that's been used in the attempt to blame me.

As for the "I think you've installed..."  notion, unless I'm randomly installing and uninstalling my video drivers, I'd have to say that's not even clutching at straws.  And perhaps I'd have said something like "and now the screen rotates instead of selecting a column" instead of, you know, pointing out that it's doing nothing other than activating the accelerators in the menu.

For the extensions, how exactly would the keyboard interaction be changing randomly?  Are there extension authors who're creating their extensions to randomly capture and release keybindings?  Since that's what you're claiming is the case, perhaps there ought to be a hint to extension authors to capture keybindings or not capture them, but not randomly capture and release?

Unfortunately, since I'm not sitting here randomly switching keyboard layouts and installing/uninstalling drivers or extensions, it seems that this is still just an insurmountable VS Code bug.

**Comment by alexandrudima** [comment]
@Gooseman Do these shortcuts work in any other software on your machine? In other words, do these shortcuts reach applications installed on your machine?

What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by Gooseman** [comment]
As far as I remember, when I've tried that previously the recorded key strokes always changed to the accented character when the shortcut wasn't working and stayed as the individual keys when the shortcut was working.

v1.37.0 has installed and the problem has disappeared for now - I've had a few days without the problem returning.  This has happened previously - the problem occurs most of the time with intermittent periods of the key strokes working as set, followed by an update installing and the problem going away for a while - so I expect it'll return again with a future update.  When it starts happening again I'll check what keys are recorded.
