### ISSUE TITLE
call stack view too narrow

### ISSUE THREAD

**Issue by christianparpart** [microsoft/vscode#78255]
I am developing mainly in native and C++, and my call stacks aren't near as readable as one could get in plain GDB. This is what it looks like:

![image](https://user-images.githubusercontent.com/56763/62189523-7b20ce00-b36f-11e9-8f6d-8c3716a1d82d.png)

And this is what it looks like me trying to get more visibility:

![image](https://user-images.githubusercontent.com/56763/62189546-896eea00-b36f-11e9-927f-2b9d2953b1d7.png)

Neither of the two vscode views actually are useful. Either I can see the editor window OR I can see the call stack somewhat proper.

What I now wish for is the ability (just like in Visual Studio, or, CGDB, ...., to have the call stack view not squeezed into the left panel, but optionally in the lower panel, just like where the (terminal|error|output|...)-panels are.

**Comment by isidorn** [comment]
Somewhat similar to https://github.com/microsoft/vscode/issues/49923
We need a more flexible grid workbench layout (another issues exists for that).
Thus closing as a duplicate
