### ISSUE TITLE
Tabs Not Showing in Insiders Build (June 17th Build)

### ISSUE THREAD

**Issue by tills13** [Microsoft/vscode#7826]
- VSCode Version: 1.3.0
- OS Version: OSX 10.11

Steps to Reproduce:

1. enable tabs using `"workbench.showEditorTabs": true`
2. open more than one context
3. the contexts should open in separate tabs, but open in the traditional "stack" instead.

**Comment by bpasero** [comment]
Setting name changed to `workbench.editor.showTabs`

**Comment by andreipaz** [comment]
Thanks @bpasero. Now I can breathe :)

**Comment by tills13** [comment]
@bpasero this brings up a good point about "release notes" for insider builds. It's not always evident from looking at recently closed tickets what has changed.

**Comment by bpasero** [comment]
@tills13 https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/June_2016.md

**Comment by tills13** [comment]
Perfect. Thanks.
