### ISSUE TITLE
Seti uses TS-icon for jsonc-language

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78261]
Seti icons still show the settings.json as Typescript for me

_Originally posted by @lramos15 in https://github.com/microsoft/vscode/issues/76925#issuecomment-516629147_

**Comment by jrieken** [comment]
@aeschli I pushed a fix but I didn't go the way through PR et al. I think you want to follow up next milestone

**Comment by misolori** [comment]
FYI @orta

**Comment by orta** [comment]
Cool, yeah, this might be from the import script? It's not in the [seti-ui repo anywhere](https://github.com/jesseweed/seti-ui/search?q=jsonc&unscoped_q=jsonc)

**Comment by misolori** [comment]
Yea, it looks like it was added [when we updated seti-ui](https://github.com/microsoft/vscode/commit/0d4f1bca5325a3358a5ef0a7e4910544018228aa#diff-d7e663ee7d187cd918f11e8ac668a41fR1611). I believe @aeschli will look into it, just wanted to give you a heads up.

**Comment by orta** [comment]
<£
