### ISSUE TITLE
IntelliSense is broken for absolute import paths: "No definition found"

### ISSUE THREAD

**Issue by z-ax** [microsoft/vscode#78268]
Go to Definition doesn't work as expected, can't navigate to JS/JSX module definition via F12, can't auto-complete **absolute** import paths (relative works just fine).

Well, I think this feature was working weeks ago, but was broken with recent updates (not speaking for myself only, our whole team is facing the same issue and I'm pretty surprised there's no new issue on it yet).

- VSCode Version: 1.36.1 (1.36.1)
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Create a JS project (for example, via CRA) with JS sources in `./src`
2. Create `jsconfig.json` with proper `compilerOptions` (`baseUrl` should lead to `./src`), all according to your [docs](https://code.visualstudio.com/docs/languages/jsconfig)
3. Create couple React components (`*.js` files, it's set to process as `JavaScript React`)
4. Try to auto-complete import path starting from some dir inside `./src`, or go to definition of the successfully imported one
5. Tried re-launching VS Code, didn't help

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you please share a small example project that demonstrates this

**Comment by z-ax** [comment]
Alright, will add later a simple example: it's actually couple steps to reproduce as I described (create app with CRA, add couple files and try importing with absolute paths).
Also, issue is only valid for `jsconfig`. With `tsconfig` and latest VSCode (1.37.0) everything seems to work as expected now.

**Comment by z-ax** [comment]
Here are some really simple steps:

```
npx create-react-app vscode-test-app
code ./vscode-test-app
```

Add file `src/Test/TestComp.js`:

```
const TestComp = () => null

export default TestComp
```

Now:
1. Try to import in in `src/App.js` as `import TestComp from 'Test/TestComp'` (auto-complete didn't work for me)
2. When it's added somewhere like `<TestComp />` try to go to definition (it navigates to the `import` statement, but no further)

**Comment by z-ax** [comment]
Seems like it works now with the recent VSCode (1.37.0). I checked my test app with steps above and it works just fine. Closing the ticket, thanks.
