### ISSUE TITLE
Suggest widget explain mode requires repaint before it shows the explain.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78275]
The toggle works, but I need to change which element I'm focused on to cause it to show. Steps:
- Type `con` in a typescript file.
- See the suggest widget.
- `ctrl+/`
- No change to the suggest widget.
- Arrow down to the second suggestion.
- Now the suggest widget shows the explain mode.

Found testing https://github.com/microsoft/vscode/issues/75500

**Comment by jrieken** [comment]
yeah, kind of "by lazy design"

**Comment by YisraelV** [comment]
I'm working on this.
