### ISSUE TITLE
Add un-wanted space at the end of the line

### ISSUE THREAD

**Issue by yenerorerGW** [microsoft/vscode#78277]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

VSCode is adding a space by itself at the end of the live automatically. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|11.92GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.1
vscode-line-endings|jha|0.2.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-scss|mrm|0.6.2
csharp|ms-|1.21.0
debugger-for-chrome|msj|4.11.6
java|red|0.47.0
aspnet-helper|sch|0.6.4
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
local-history|xyz|1.7.0

</details>

**Comment by IllusionMH** [comment]
How do you see them? Screenshot would be helpful.
Does it happen with extensions disabled (e.g. `vscode-line-endings` intentionally displays line ending characters, but they shoud differ from spaces which displayed as dots)?
Is `"editor.trimAutoWhitespace": true` enabled?

/needsMoreInfo

_(I know that I'm not in whitelist for bot commands, but may be some day :) )_
