### ISSUE TITLE
Reduce mouse movement effort for changing editor encoding by improving GUI

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#78279]
Currently, it's a huge, time wasting effort to change file encoding:

![ReduceMouseMovements-encoding](https://user-images.githubusercontent.com/9283914/62225674-3588f300-b3b9-11e9-83d9-1ab68ae1191a.gif)

I suggest to improve usability by having the list of encoding schemes pop up not at the top but at the _bottom_ of Visual Studio Code, right above the Encoding status text in the blue bar.

**Comment by joaomoreno** [comment]
Try:

1. <kbd>F1</kbd>
2. <kbd>encoding</kbd>
3. <kbd>Enter</kbd>

Zero mouse movement!

**Comment by SetTrend** [comment]
Thanks for the hint.

From a usability (UX) point of view I tend to consider the <kbd>F1</kbd> approach a "hidden feature", though. One certainly cannot expect users to walk around with a number of cheat sheets for each and every program they use. Any command that's not available by menu, toolbar buttons or tool tips should be considered not available.
