### ISSUE TITLE
Prevent goto definition when trying to copy 

### ISSUE THREAD

**Issue by jbeaudoin11** [Microsoft/vscode#7827]
Hi !

I posted in the closed issue #189 but nobody replied after 4 days..
So I create a new one so I can get some help with that.

I wanna know if it's possible to disable the goToDefinition bind to Ctrl + Click ?
This is so annoying ! Every time I copy/paste I end up to somewhere else in the code...
Since I'm not using the goToDefinition, I wanna disable it.

Tried to overwrite the key bind like someone said on my [stackoverflow ](http://stackoverflow.com/questions/37683703/how-to-disable-ctrl-click-in-vs-code/37692728?noredirect=1#comment62907898_37692728) post : 
```
{ "key": "ctrl+[mouse button]",   "command": "cursorWordLeft",
                                         "when": "editorTextFocus" }
```
But it didn't work...
I need some help please !

**Comment by tills13** [comment]
try `{ "key": "ctrl+[mouse button]",   "command": "-cursorWordLeft" }`

**Comment by jbeaudoin11** [comment]
Still doesn't work

**Comment by dbaeumer** [comment]
@alexandrudima not sure if you or @jrieken with his new menu support.

**Comment by jbeaudoin11** [comment]
How long is going to take to this feature be done ?
At least a month ? more ? Will it be done ?

**Comment by bpasero** [comment]
@jbeaudoin11 can you give me more details how you are still able to reproduce this issue?

**Comment by bpasero** [comment]
Pushed a change to stop the goto definition procedure if you change the cursor position while having Ctrl-key down. This should handle the case where you start to drag over the word to select the portion to copy.

**Comment by jbeaudoin11** [comment]
@bpasero Alright ! can't wait to next update ! :)

**Comment by bpasero** [comment]
It should be available tomorrow already from our insider builds, but I need to do some more testing on Windows and Linux that I did not break this feature entirely.

**Comment by jbeaudoin11** [comment]
@bpasero Installed the insider builds and it's looking so much better now god you're my hero <3

**Comment by isidorn** [comment]
Verified by user adding verified tag

**Comment by jbeaudoin11** [comment]
@bpasero What about ctrl + db click (for selection) + c/v

**Comment by bpasero** [comment]
Uh double click is tricky and I see the issue. Is it as annoying as this issue was?

**Comment by jbeaudoin11** [comment]
@bpasero i didn't test it a lot for now. But as i know its  probably not as annoying as the other one !

From what i have seen its working very good at the moment.

**Comment by bpasero** [comment]
OK good, I am not sure how to fix the double click thing...

**Comment by jbeaudoin11** [comment]
@bpasero I just updated to new insiders version it doesn't work anymore ! :'(

**Comment by jbeaudoin11** [comment]
@bpasero Doesn't work in html files. When i try it on a file link it just pop me the file.

**Comment by bpasero** [comment]
@jbeaudoin11 yes, my solution has nothing to do with links in the editor, I suggest you open a separate issue for that.

**Comment by alexdima** [comment]
ctrl+click does not select a word in VS Code. Currently, only double click does word selection. #3130 tracks that mouse bindings can be customized.
