### ISSUE TITLE
Sync: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#78288]
I am behind a web proxy/firewall.  I don't have any issues syncing changes to my github repos or downloading and installing extension within VSCode..  However, this particular extension produces the below error when downloading settings.

**Sync: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console**

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?
