### ISSUE TITLE
How do I debug vscode itself?

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#7828]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: OSX 10.11.5

Having an issue loading another jsonschema via `$rel`, trying to figure out what domain it's sending the request to (not going to localhost I expected). I'd like to turn on vscode debugging to see what vscode is requesting.

**Comment by Sequoia** [comment]
Installed for local development but now I can't install the chrome debug extension-- there's no "`ext install`" option in the version I run with `./scripts/code.sh`

![jsonschema-vscode](https://cloud.githubusercontent.com/assets/317498/16161410/593ad1ce-349b-11e6-8397-f2187969161d.gif)

**Comment by isidorn** [comment]
As you figured out you need the chrome debug extension to debug vscode itself. Just launch 
`scripts/code.sh --remote-debugging-port=9222` and attach to the port from the "real vscode" that has the chrome debug extension installed.

If for some reason you still need extensions in your `./scripts/code.sh` you can just install them to your "real vscode" and copy them over from vscode_app/resources/app/extensions/ to home/.vscode-oss-dev/extensions
