### ISSUE TITLE
[IntelliSense explain mode] Not sure if it has value to show in Extensions View / Settings GUI

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#78284]
#75500

1. Toggle Explain Mode in editor
1. Extensions View trigger autocomplete

![Screenshot (36)](https://user-images.githubusercontent.com/9638156/62232513-1ac17900-b3cf-11e9-85ba-f914e508c574.png)

![Screenshot (37)](https://user-images.githubusercontent.com/9638156/62232521-1e550000-b3cf-11e9-83d8-692ffd764b1d.png)

**Comment by joaomoreno** [comment]
What is Explain Mode?

How do you _go somewhere else_?

**Comment by usernamehw** [comment]
There is a link to issue at the very top

**Comment by jrieken** [comment]
While those suggestions aren't from extensions it's still the same feature, explaining how suggestions happen. This is a debug feature and when enabled, folks should know what it means and how to turn if off again
