### ISSUE TITLE
Open in New Window, with shortcut

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode#78286]
Issue Type: <b>Feature Request</b>

The most frequent operations I perform with the File menu are:

1) New Window
2) Open...

Wouldn't it be just so grand if there were a single menu item called **"Open in New Window"** with a keyboard shortcut of, say, `Cmd-Shift-o`?  OMG, that would just be so incredibly convenient!!  Add cool points if there's also a new setting that says "**Start filesystem navigation in folder: _______** ", (which I'd set to `~/Developer/src/` since that's the **root** of all my problems).

Thanks for considering it.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.7.0

**Comment by bpasero** [comment]
@ChrisMiami there is:

![image](https://user-images.githubusercontent.com/900690/62465990-8a00e980-b790-11e9-8665-e0b792c04b92.png)

Works when the file is actively opened.

**Comment by ChrisMiami** [comment]
Not sure what "more info" is needed?  The response "Open Active File In New Window" is inappropriate because the point is to open a new file, not an already-open file.
