### ISSUE TITLE
Terminal Scrolls search even if find result is visible

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#78281]
Issue Type: <b>Bug</b>

If you are moving through search results via enter or shift+enter the terminal will scroll the terminal even if the search result is in view resulting in some jitter. See https://user-images.githubusercontent.com/4544166/62226436-15344680-b36f-11e9-84cf-ce448c9c9c45.gif

Upstream: https://github.com/xtermjs/xterm.js/issues/2352
VS Code version: Code - Insiders 1.37.0-insider (d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c, 2019-07-31T05:21:45.449Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by Tyriar** [comment]
Upstream issue is xtermjs/xterm.js#2352 if anyone wants to help out with PRs

**Comment by lramos15** [comment]
I'm going to try to get a PR out this weekend once I set my machine up to compile VS Code

**Comment by lramos15** [comment]
Upstream PR created, awaiting merge and update of VS Code's xterm and then this should be fixed. (Only 1 week late :) )
