### ISSUE TITLE
CSS Element tree not shown

### ISSUE THREAD

**Issue by InKiev** [microsoft/vscode#78285]
Issue Type: <b>Bug</b>

1. Open a CSS/SCSS file
2. Hover over a nested definition
3. Element tree is not being displayed.

VS Code version: Code - Insiders 1.37.0-insider (d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c, 2019-07-31T05:24:41.973Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (21.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.801.1
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-todo-plus|fab|4.13.0
code-runner|for|0.9.11
python|ms-|2019.6.24221
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6
vscode-scss-formatter|sib|1.4.1
vscode-icons|vsc|9.1.0

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@octref do you know where this comes from?
Insiders:
<img width="220" alt="insidersscss" src="https://user-images.githubusercontent.com/38270282/62367848-0eeac980-b52b-11e9-9315-565f7159f9b5.png">

Stable:
<img width="210" alt="stablescss" src="https://user-images.githubusercontent.com/38270282/62367849-0eeac980-b52b-11e9-930f-6474a74f34dd.png">

**Comment by octref** [comment]
@InKiev Please attach full source code, and show where you are doing the hover.

**Comment by InKiev** [comment]
I can do that, but, I don't think is necessary @alexr00 just added an example above showing the issue.

**Comment by alexr00** [comment]
```
$padding: 6px;

nav {
  ul {
    margin: 0;
    padding: $padding;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: $padding 12px;
    text-decoration: none;
  }
}
```

**Comment by itamark** [comment]
I can repro - but can't tell where the element tree comes from (just like @alexr00) - anyone know?

**Comment by itamark** [comment]
I'd like to take this. I can prob figure out where it comes from.

**Comment by octref** [comment]
@itamark Sorry we have an upcoming release and this has to be fixed as early as possible. I suggest looking for these labels:
https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

Thanks for offering to help though!

**Comment by itamark** [comment]
Okay no worries @octref thanks!
