### ISSUE TITLE
Re-open #43670 -- "When editing settings, add new items alphabetically sorted and fix find experience"

### ISSUE THREAD

**Issue by sarpik** [microsoft/vscode#78298]
#43670 suggests improving the `settings.json` experience.

[A comment](
https://github.com/microsoft/vscode/issues/43670#issuecomment-420841680), after which the issue was closed, states that
> Now that we have the settings UI, we aren't investing much in the JSON editor

but c'mon people! Most of us, programmer folks, highly prefer the `settings.json` file over the GUI -- 

* not all settings are supported in the GUI with links to edit the setting in settings.json file;

* the .json file is synced with [settings sync extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync);

* I and many more folks prefer the `.json` file over the GUI

* <...> name your own use case!

IMO, there're too many use cases for the `settings.json` file to just throw it out of the maintainability scope and call it a day.
Same with other configuration files, such as `keybindings.json` and `global.code-snippets`!

See also #76575

Please consider supporting them config files! `settings.json` would be a great start. I'd love helping out and contributing to the #43670 issue.

Thank you.
Sincerely,
Kipras.

**Comment by roblourens** [comment]
To be clear, we will never get rid of settings.json or the other json configuration files. But we are not going to build complicated UI on top of the json editor like the old split editor view. Discussion about the split editor is here: https://github.com/microsoft/vscode/issues/68386

**Comment by sarpik** [comment]
Nooo that's not what I'm concerned about! I'm fine with the UI editor. I wanted to bring attention to #43670 - sorting config options by keys to make the config less messy.
@roblourens

**Comment by roblourens** [comment]
I understand - we used to have a split json editor with extra UI features on top of it, and now that is deprecated. We still have the json editor as a simple text editor and I don't plan to add things like #43670 to it

**Comment by sarpik** [comment]
Understandable. Is there any way I could attempt to implement #43670?

**Comment by roblourens** [comment]
An extension would be the right place for that sort of feature.

**Comment by sarpik** [comment]
After your explanations I agree. Will see what I can do. Thanks Rob:)
