### ISSUE TITLE
Show Color with Hex Colors in strings

### ISSUE THREAD

**Issue by isaac2004** [microsoft/vscode#78290]
The new [Windows Terminal](https://github.com/microsoft/terminal) uses hex colors to specify profile colors which is controlled by a json file. Here is an example

```json
"background" : "#0C0C0C",
"black" : "#0C0C0C",
"blue" : "#0037DA",
"brightBlack" : "#767676",
"brightBlue" : "#3B78FF",
```

When I open this file in VS Code, it would be great if the hex value of the color had the actual color next to it, similar to other file types, for instance css files

![image](https://user-images.githubusercontent.com/8878502/62235839-c81a9980-b39b-11e9-86ac-3a0439d17b2d.png)

**Comment by alexr00** [comment]
This should be done in an extension by [`provideDocumentColors`](https://code.visualstudio.com/api/references/vscode-api#DocumentColorProvider)

**Comment by isaac2004** [comment]
FYI, an extension does this,
[colorize](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize)
