### ISSUE TITLE
Simple file dialog auto complete doesn't kick in until the third character when the path starts with a .

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78293]
Found while verifying https://github.com/microsoft/vscode/issues/76426

<img width="149" alt="Screen Shot 2019-07-31 at 11 30 35 AM" src="https://user-images.githubusercontent.com/2193314/62237876-a82cab00-b386-11e9-9a79-8c3aa5f14331.png">
<img width="138" alt="Screen Shot 2019-07-31 at 11 30 39 AM" src="https://user-images.githubusercontent.com/2193314/62237879-a9f66e80-b386-11e9-83c4-cc8b67c57cfc.png">

Also folders that don't start with a `.` don't start auto completing until the second character?

**Comment by Tyriar** [comment]
Consider for July

**Comment by itamark** [comment]
@Tyriar I can't repro this. What OS is this on?

**Comment by Tyriar** [comment]
@itamark Windows 10 using Remote - SSH extension into an Ubuntu VM.

**Comment by alexr00** [comment]
I could repro something similar. I intend to fix in August.
