### ISSUE TITLE
Ctrl + P does not work on latest vscode

### ISSUE THREAD

**Issue by anusm14** [microsoft/vscode#78296]
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
Steps to Reproduce:

1.Open Vscode
2.ctrl + P shortcut stopped working. Works if you from menu - Go-> go to file
3. checked keyboard shortcute, recording does not capture "ctrl + p" .

Does this issue occur when all extensions are disabled?: Yes
Disabling extension did not help.

**Comment by alexandrudima** [comment]
> recording does not capture "ctrl + p" .

This means that VS Code does not receive the keybinding from the OS. Are you able to use this keybinding in other applications? Have you recently installed some software on your machine that would capture Ctrl+P globally?

Unfortunately, this is not an issue with VS Code and there is nothing we can do on our side if we don't receive the keybinding...
