### ISSUE TITLE
Terminal and main window hang when scrolling on top of output.

### ISSUE THREAD

**Issue by dno89** [microsoft/vscode#78300]
- VSCode Version: 1.37.0-insider 3802a986823977ec472fc993854e1a753037fc8f x64 .

- OS Version: Ubuntu 18.04 bionic.

Steps to Reproduce:

1. `bazel build //...` in the integrated terminal on my large project.
2. Scroll to the first line while compiling of even after compilation.

Does this issue occur when all extensions are disabled?: Yes

Hi, I have frequent main window and terminal hangs when I compile my project from the integrated terminal.
This happens even after the compilation is done: scrolling to the top of the output freezes everything for few seconds.
Strange thing, if the terminal has other random output in it, it doesn't happen.
I saw there are a bunch of closed issues about this, but I'm not sure it's 100% the same.
I tried starting `code` with other options, including `--enable-accelerated-2d-canvas --enable-gpu-rasterization --ignore-gpu-blacklist --enable-native-gpu-memory-buffers` or `--disable-gpu`, tried both `dom` and `canvas` for the integrated terminal, but the result is the same.

**Comment by Tyriar** [comment]
Please try reproduce the issue in [xterm.js]'s demo https://github.com/xtermjs/xterm.js
