### ISSUE TITLE
File Get Blank

### ISSUE THREAD

**Issue by zem2464** [microsoft/vscode#78309]
- VSCode Version: 1.36
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1.Open GIT Conflict  file. 
2.Solve it and save. Full file get blank

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
@zem2464 since you reported that the issue does not occur when all extensions are disabled I suggest you re-enable extensions one at a time (or half of them at a time) to discover which extension is causing your problem.

**Comment by joaomoreno** [comment]
@zem2464 Can you reproduce with `code --disable-extensions`?

**Comment by krunal9421** [comment]
@joaomoreno getting the same issue reported by @zem2464  after reproduce with code --disable-extensions.

**Comment by joaomoreno** [comment]
@krunal9421 Can you share a screen recording?
