### ISSUE TITLE
There are some problem with termial's dropdown menu！Chinese text display incomplete!

### ISSUE THREAD

**Issue by YugeCse** [microsoft/vscode#78305]
![TIM截图20190801091217](https://user-images.githubusercontent.com/8111495/62258335-8db50900-b43c-11e9-9325-61b94e1bb711.png)

**Comment by YugeCse** [comment]
终端显示区域的右侧下拉菜单中的中文显示不全问题.

**Comment by Tyriar** [comment]
Related to custom select. fyi @cleidigh

**Comment by YugeCse** [comment]
> Related to custom select. fyi @cleidigh 
Thanks!

**Comment by cleidigh** [comment]
@YugeCse 
@Tyriar 
@isidorn 
I just reopened so I could comment.
I don't have enough information to understand this.  Should it be more investigated?

**Comment by Tyriar** [comment]
@cleidigh CJK characters are getting the bottom cut off (eg. terminal rename "中文"). @YugeCse what OS/version/distro are you on and what version of VS Code?

I can't repro on Windows 10:

![image](https://user-images.githubusercontent.com/2193314/62314811-c5c24900-b448-11e9-8f52-7c8633b1c18a.png)

**Comment by isidorn** [comment]
Assigning to you @cleidigh 
If you decide to fix this I am open to review a PR.

**Comment by rzhao271** [comment]
I don't think this issue occurs anymore.
I'm unable to repro on Windows 11 on the latest Insiders.
