### ISSUE TITLE
CLI processes do not terminate on exit on MacOS Darwin

### ISSUE THREAD

**Issue by aaayushsingh** [microsoft/vscode#78308]
I checked out issues #18385 #24962 #62040 with #62040 mentioning that the issue is gone after October update. I am still able to reproduce this issue with other processes. (The node process is the only process that gets terminated)

- VS Code version: Code 1.36.1 (2213894, 2019-07-08T22:56:38.504Z)
- OS version: Darwin x64 18.6.0

Steps to Reproduce:

1. open integrated terminal
2. run any process like `redis-server` or `mongod`
3. close vscode
4. try running `redis-server` or `mongod` or same process in terminal, it'll say port already in use. check running processes, process is running

Does this issue occur when all extensions are disabled?: Yes

**Comment by aaayushsingh** [comment]
@Tyriar if no one is working on this, I'd like to, if you can point me in the right direction.

**Comment by Tyriar** [comment]
@aaayushsingh I'm pretty stumped as to why this would only happen. It needs verification that it's not actually a problem with redis-server/mongod first.

This is where terminal processes/ptys are teared down: https://github.com/microsoft/vscode/blob/e0762af258c0b20320ed03f3871a41967acc4421/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L168-L197

And this is the lib that manages the ptys https://github.com/microsoft/node-pty

**Comment by aaayushsingh** [comment]
@Tyriar They do not terminate with regular terminal either. Just checked
