### ISSUE TITLE
Sort Lines Ascending / Descending sorts differently on comments than on code.

### ISSUE THREAD

**Issue by gmattie** [microsoft/vscode#78304]
- VSCode Version:  1.36.1
- OS Version:  Windows 10

Steps to Reproduce:

1.  Copy paste this code in to VSCode:

```
/**
 * @description Properties of type {string} consist of:
 * 
 * <ul>
 *     <li> USER_DATE </li>
 *     <li> USER_ADMIN </li>
 *     <li> USER_PASSWORD </li>
 *     <li> USER </li>
 *     <li> USER_EMAIL </li>
 *     <li> USER_TOKEN </li>
 *     <li> USER_NAME </li>
 * </ul>
 * 
 * @public
 * @constant
 * 
 */
const Model = {

    USER_DATE: "date",
    USER_ADMIN: "admin",
    USER: "user",
    USER_EMAIL: "email",
    USER_PASSWORD: "password",
    USER_NAME: "name",
    USER_TOKEN: "token",
};
```
2. Select / highlight both the list elements in the documentation and the object entries in the Model constant:

![Capture](https://user-images.githubusercontent.com/933921/62255868-1eec9700-b3cd-11e9-9db2-cdbbe671370a.PNG)

3.  Open the Command Palette (F1 or Ctrl + Shift + P).

4.  Type "sort" to filter the commands and select "Sort Lines Ascending" (or descending).

5.  Notice the ascended (or descended) sorting is different in the documentation than in the code.  Specifically, `<li> USER </li>` appears first in the documentation but `USER: "user"` appears last in the code:

```
/**
 * @description Properties of type {string} consist of:
 * 
 * <ul>
 *     <li> USER </li>
 *     <li> USER_ADMIN </li>
 *     <li> USER_DATE </li>
 *     <li> USER_EMAIL </li>
 *     <li> USER_NAME </li>
 *     <li> USER_PASSWORD </li>
 *     <li> USER_TOKEN </li>
 * </ul>
 * 
 * @public
 * @constant
 * 
 */
const Model = {

    USER_ADMIN: "admin",
    USER_DATE: "date",
    USER_EMAIL: "email",
    USER_NAME: "name",
    USER_PASSWORD: "password",
    USER_TOKEN: "token",
    USER: "user",
};
```

Does this issue occur when all extensions are disabled?:  Yes

**Comment by alexandrudima** [comment]
Yes, this makes sense because in the first list, the space character follows the words, so ` ` (space) will be compared with `_`, while in the second example `:` will be compared with `_` and it looks like the order is:  ` ` (space) < `_` < `:`
