### ISSUE TITLE
Unresolvable variables should resolve to empty string

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#78307]
While testing #78122 on Linux.

I used the following:
`shell.sh`
```
#!/usr/bin/env bash
node rudi.js $*
```

rudi.js
```
process.argv.forEach(function (val, index, array) {
    console.log(index + ': ' + val);
  });
setTimeout(function() {}, 3000);
```

settings.json
```
{
"terminal.integrated.shell.linux": "${workspaceFolder}/shell.sh",
"terminal.integrated.shellArgs.linux": ["${workspaceFolder}", "${workspaceFolderBasename}", "${file}", "${relativeFile}", "${fileBasename}", "${fileBasenameNoExtension}", "${fileDirname}", "${fileExtname}", "${cwd}", "${lineNumber}", "${selectedText}", "${execPath}"]
}
```

When opening a terminal I expect to see output with the unresolvable variables having the empty string as value. Instead, when there is no selection, internal errors are thrown and the terminal hangs. Same, when having the settings.json file open, see #78247).

**Comment by Tyriar** [comment]
I don't think they should be the empty string but that's more of a question for the configuration resolver so we act generally @isidorn 

I do notice though that we only catch the resolve error and continue on for the cwd.

**Comment by isidorn** [comment]
Previously we were resolving them to an empty string but that proved confusing because those errors where harder to catch. So we decided against it
fyi @weinand @alexr00
