### ISSUE TITLE
extension keybinding fail.

### ISSUE THREAD

**Issue by Gubith** [microsoft/vscode#78306]
{ "key": "alt+d", "command": "multiCommand.myMain" },
{ "key": "alt+d", "command": "Macros.commentDown"	},

macros, macrocommander, mult-command

These fail now. 
Every time I work with Code, I have to work ON Code.
The settings for the extensions are fine, but the keybindings are fail.

I'm looking for a better tool, Code is junk.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.2.9200

**Comment by joaomoreno** [comment]
> These fail now.

What do you mean?
