### ISSUE TITLE
Terminal: search context isn't focused on successive toggles with Ctrl+F

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#78301]
When testing https://github.com/microsoft/vscode/issues/78108

Local OS: macOS/windows/linux

**Stable**:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/964386/62252590-251c4c80-b3a8-11e9-9e4f-98a4916f8db0.gif)

**Insiders**:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/964386/62252670-60b71680-b3a8-11e9-9f87-5865645c979c.gif)

**Comment by lramos15** [comment]
Good catch. Looks like the subsequent ctrl+f's try to give focus back to the editor's find widget and will open it even though the terminal find widget is already open. You just don't see that in this case because there is no file open in this case

**Comment by lramos15** [comment]
@Tyriar this is a regression even before #77958 as reverting my changes doesn't fix the problem.
