### ISSUE TITLE
Right-click shows black rectangle instead of context menus #74751

### ISSUE THREAD

**Issue by singh-arulraj** [microsoft/vscode#78315]
VSCode Version: 1.36.1
OS Version: Ubuntu 16.04 LTS Running on Virtual Box(Version 6.0.10 r132072 (Qt5.6.2)).

**Steps to Reproduce:**
1. In virtual Box, enable Virtual Screen 2. (View -> Virtual Screen 2-> Enable)
2. Open any file (I open .c/.cpp)
3. Do right click on a function or a type name

**Observation**: 
1. A black context menu pops up Nothing is visible.
2. As soon as virtual Screen 2 is disabled, the context menu is populated correctly.

**Other Information.**
Version: 1.36.1
Commit: 2213894
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic

![image](https://user-images.githubusercontent.com/42382649/62277675-46db0980-b464-11e9-978c-a5763b4dd8cd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
@singh-arulraj can you try the following builds which is based on Electron 6, to see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

If the issue still appears, can you also run them with `--dsiable-gpu` command line flag.

**Comment by ferodco** [comment]
> @singh-arulraj can you try the following builds which is based on Electron 6, to see if the issue appears there. Thanks!
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
> * Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
> * Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
> 
> If the issue still appears, can you also run them with `--dsiable-gpu` command line flag.

Same issue here (Ubuntu 18.04.03 LTS on VirtualBox 6.0.12 r133076 (Qt5.6.2):

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-31-generic


--disable-gpu works for me. Thanks.

**Comment by bpasero** [comment]
@singh-arulraj 
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.
