### ISSUE TITLE
Add predefined variable ${fileDirBasename}

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#78316]
Hello, I have some dotnet solutions opened as my root workspace.

For example:

${workspaceFolder}:
/home/username/dotnet-solution1

${file}:
/home/username/dotnet-solution1/project1/Program.cs
/home/username/dotnet-solution1/project2/Program.cs
/home/username/dotnet-solution1/project3/Program.cs
/home/username/dotnet-solution1/project4/Program.cs

When I open Program.cs or other cs file, I want press F5 to debug the corresponding project.

So I need this ${fileDirBasename} variable.

this is my expected lanunch config:

```
{
    "name": "Launch current project",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${fileDirname}/bin/Debug/netcoreapp2.0/${fileDirBasename}.dll",
    "args": [],
    "cwd": "${fileDirname}",
    "stopAtEntry": false,
    "console": "internalConsole"
}
```

my expected build task:

```json
{
    "label": "build",
    "command": "dotnet",
    "type": "process",
    "args": [
        "build",
        "${fileDirname}/${fileDirBasename}.csproj",
        "/property:GenerateFullPaths=true",
        "/consoleloggerparameters:NoSummary"
    ],
    "problemMatcher": "$msCompile"
}
```

**Comment by isidorn** [comment]
There might be already a feature request for this, unfortunetly I can not find it.
Leaving it open as a feature request for now and assigning to @alexr00

**Comment by rioj7** [comment]
for this project directory structure what is this variable different than `${relativeFileDirname}`?

**Comment by kzhui125** [comment]
@rioj7 

consider this example:

/home/username/dotnet-solution1/dir1/project1/Program.cs

${relativeFileDirname} will be dir1/project1, I won't get "${fileDirname}/${fileDirBasename}.csproj" using ${relativeFileDirname}

**Comment by rioj7** [comment]
@kzhui125  I have added this variable to the extension [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable) v0.7.0.

In case you have a project structure
```
/home/username/dotnet-solution1/dir1/project1/Program.cs
/home/username/dotnet-solution1/dir1/project1/subdir1/tool.cs
```
And if your current file is `tool.cs` the launch or build will go bad.

Then you should use `extension.commandvariable.file.fileAsKey`
```json
{
  "version": "2.0.0",
  "tasks": [
    {
        "label": "build",
        "command": "dotnet",
        "type": "process",
        "args": [
            "build",
            "${input:chooseFileBasename}/${input:chooseFileBasename}.csproj",
            "/property:GenerateFullPaths=true",
            "/consoleloggerparameters:NoSummary"
        ],
        "problemMatcher": "$msCompile"
    }
  ],
  "inputs": [
    {
      "id": "chooseFileBasename",
      "type": "command",
      "command": "extension.commandvariable.file.fileAsKey",
      "args": {
        "/project1/": "project1",
        "/project2/": "project2"
      }
    }
  ]
}
```
You need to make the key as specific as needed.

**Comment by alexr00** [comment]
Could you do `${fileDirname}/${relativeFileDirname}/${fileBasenameNoExtension}.csproj`?

**Comment by kzhui125** [comment]
@rioj7 thanks, I will have a try.

@alexr00 


for example:
/Users/test/Documents/dotnet-solution1 opened as ${workspaceFolder}:
/Users/zm/Documents/dotnet-solution1/dir1/project1/Program.cs opend as ${file}

my expected launch.json:

/Users/test/Documents/dotnet-solution1/dir1/project1/bin/Debug/netcoreapp2.0/project1.dll

my expected tasks.json:

/Users/test/Documents/dotnet-solution1/dir1/project1/project1.csproj

${fileDirname} will be /Users/test/Documents/dotnet-solution1/dir1/project1
${relativeFileDirname} will be dir1/project1
${fileBasenameNoExtension}.csproj will be Program.csproj

so ${fileDirname}/${relativeFileDirname}/${fileBasenameNoExtension}.csproj will be:

/Users/test/Documents/dotnet-solution1/dir1/project1/dir1/project1/Program.csproj

It's not as expected.

**Comment by alexr00** [comment]
`${workspaceFolder}/${relativeFileDirname}/${fileBasenameNoExtension}.csproj`?

**Comment by kzhui125** [comment]
@alexr00 

`${fileBasenameNoExtension}.csproj` will be `Program.csproj`

But `project1.csproj` is expected

**Comment by alexr00** [comment]
Ok. The feature request here is for a variable the resolves to the second to last segment of the current file's path.

**Comment by alexr00** [comment]
The new variable is fileDirnameBasename

**Comment by alexr00** [comment]
\closedWith 551db7ec94f02a4bdc8999092cf8bef642b3992d

**Comment by aeschli** [comment]
Verified with
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo",
            "args": ["${fileDirnameBasename}"],
            "problemMatcher": []
        }
    ]
}
```
