### ISSUE TITLE
TreeView.reveal doesn't seem to be working anymore

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#78310]
Issue Type: <b>Bug</b>

Calling `Treeview.reveal` with any options -- select, focus, expand, doesn't seem to have any effect.

To repo:
1. Install GitLens
1. Open the GitLens _Compare_ view
1. Click on the _Compare References..._ action or click on the _Compare <branch, tag, or ref> with <branch, tag, or ref>_
1. Pick any two things to compare
1. 🐛 _Comparing <x> to <y>_ node is not selected or expanded -- if you go back to stable it will be

You can also see this with auto-reveal of repositories in the _Repositories_ view too (though you have to have more than 1 repo open, and as you switch the active editor, it will select & expand the associated repo)

/cc @alexr00 

VS Code version: Code - Insiders 1.37.0-insider (d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c, 2019-07-31T05:24:41.973Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.49GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Eric/code/vscode-gitlens|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
Also fixed by https://github.com/microsoft/vscode/commit/e2501299e9f6f4312579c43127a3f885d703a5a3

**Comment by eamodio** [comment]
Thanks! Built from source and tried it out with the latest GitLens and it all looks good!
