### ISSUE TITLE
Git not working

### ISSUE THREAD

**Issue by vivekp123** [microsoft/vscode#78311]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
/needsmoreinfo

@vivekp123 it seems you missed the instruction that the Report Issue dialog gave (see above) about pasting clipboard contents. We need more information than 'Git not working' before we stand any change of being able to help you.

**Comment by pvskrishna** [comment]
#79031

**Comment by pvskrishna** [comment]
#79031
