### ISSUE TITLE
jsonschema $ref not loading relative URL

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#7831]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: OSX 10.11.5 

Steps to Reproduce:

## Setup
Serve the following from `localhost:8090`

### test-parent.json
```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "id": "http://localhost:8090/test-parent.json",
  "properties": {
    "external" : {
      "$ref" : "external.json"
    }
  }
}
```

### external.json
```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "id": "http://localhost:8090/external.json",
  "properties": {
    "foo" : {
      "type" : "string",
      "description": "A String"
    }
  }
}
```

## Include from another project

Create `instance.json` in a separate project:
```
{
  "$schema" : "http://localhost:8090/test-parent.json"
}

# Expected
Now get prompts for `external` & `external.foo` properties a la https://code.visualstudio.com/Docs/languages/json#_json-schemas-settings

# Actual
```html
Problems loading reference 'external.json': Unable to load schema from 'external.json': <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
Cmd + click to follow link
```

**Comment by Sequoia** [comment]
Cannot reproduce running vscode via local `./scripts/vscode.sh` debug install 😦

**Comment by aeschli** [comment]
I made a fix for this with #7730. The $ref is resolved against the actual location of the file ('file:///...), the id is not considered.
I'm closing tis assuming you just verified this with what on HEAD. If not, please reopen.

**Comment by gdimauro** [comment]
Hi, I tried with vscode insiders downloaded this morning, but I obtain the following error message:
Unable to parse content from '/schemas/all-schema.json': [object, Object]. (1,1)

**Comment by Sequoia** [comment]
Does it work from relative local file addresses? I was serving schemas from a local server during development...

**Comment by aeschli** [comment]
Can you file a new issue so I can look at this?

**Comment by gdimauro** [comment]
Hi, you can find it here:

[https://github.com/Microsoft/vscode/issues/8757](url)

I can send you also the complete solution if you prefer or need.

Thanks in advance,
Giuseppe
