### ISSUE TITLE
cursor not enable in terminal

### ISSUE THREAD

**Issue by pandiyarajanmca** [microsoft/vscode#78317]
Terminal cursor not working vscode. i tried with gitbase, powerShell and cmd promp. windows 10 64bit OS.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
