### ISSUE TITLE
search history feature.

### ISSUE THREAD

**Issue by Rainzhouzzz** [microsoft/vscode#78314]
Issue Type: <b>Feature Request</b>

I think most of us need a search history feature.I hope developers can add this feature in future.Think you.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Per https://github.com/microsoft/vscode/issues/73642#issuecomment-491925951, try using the up/down arrow keys.

**Comment by joaomoreno** [comment]
:arrow_up:

**Comment by jmc5113** [comment]
This is cool, but very hard for a user to discover (hence why I'm looking on here). Maybe a drop down when you click on the search box would help. I think it would also be nice to have a few search results shown in the search pane.
![image](https://user-images.githubusercontent.com/24373928/64204975-bd946980-ce4b-11e9-8d36-5275f1c4945d.png)
