### ISSUE TITLE
Renaming a file before saving it discards all its content

### ISSUE THREAD

**Issue by eugenmihailescu** [microsoft/vscode#78318]
Issue Type: <b>Bug</b>

Create somewhere in the source tree a file called README.ms.
Start typing `something`, don't save and don't close the editor either.
Go to VSCode Explorer and rename README.ms to README.md

That `something` disapears entirely and there is no way to get it back. I don't know if this is `by-design` or just a bug, at least I've learned my lesson :)

VS Code version: Code - Insiders 1.37.0-insider (92da68a71cfb60bd3b9b0d7fbfb2a7e1fff9dbaf, 2019-08-01T05:28:20.516Z)
OS version: Linux x64 5.2.2-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 1556)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|13.66GB (5.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
folder-source-actions|bie|0.2.0
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.29.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.4.0
gitlens|eam|9.9.2
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
sass-lint|gle|1.0.5
todo-tree|Gru|0.0.139
jbockle-format-files|jbo|3.0.0
docthis|joe|0.7.1
sublime-babel-vscode|jos|0.2.10
graphql-for-vscode|kum|1.15.0
debugger-for-chrome|msj|4.11.6
material-icon-theme|PKi|3.8.1
sass-indented|rob|1.5.1
vscode-sass-format|sas|1.1.6
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like #77778. On that one the person raising the issue found it wasn't reproducible when running with all extensions disabled. Please do the same and see what you find.

**Comment by isidorn** [comment]
@eugenmihailescu thanks for the nice steps. And this is definetently not by design.
I just tried this and I can not reproduce on my macOS and on my Linux.
@eugenmihailescu can you reproduce if you disable all your extensions?

**Comment by eugenmihailescu** [comment]
With all extensions disabled it cannot be reproduced. So I guess some of these extensions returns a `false` instead of a `true` somewhere. However, since I have ca. 20 different extensions enabled, I don't think I am able to make 20! different permutations just to find which permutation causes this issue.

So the quick fix is to use the lesson learned earlier until somehow the issue solves by itself. Sometimes they appear from nowhere, and nowhere they go.

As @gjsjohnmurray said , it sounds like #77778.

**Comment by beastdestroyer** [comment]
You don't even need to permutate through all of them, start vscode with all extensions disabled and then one-by-one just toggle each on separately and see if your issue exists. 

I would highly doubt multiple extensions are causing your problem (in which case feel free to get out the combinations)
