### ISSUE TITLE
VS Code Ubuntu 16.04. After connecting ftp files open empty

### ISSUE THREAD

**Issue by CardinaLiv** [microsoft/vscode#78320]
After updating VS Code An incomprehensible error has occurred. When connecting to the sftp server, VS Code files adequately open, however, when opening files after connecting to the ftp server, the files open empty. Rolled back VS Code to version 1.33.1 works correctly. Someone in the know how to fix this problem on new versions of Ubuntu 16.04

**Comment by joaomoreno** [comment]
> An incomprehensible error has occurred

What error? Do you have a screenshot?

**Comment by CardinaLiv** [comment]
I connect to the server through PCmanFM / FileZilla on VS Code 1.36.1 https://prnt.sc/ondz7j and on VS Code 1.33.1 https://prnt.sc/ondzv8 with a similar connection to the sftp server, both versions open the file correctly

**Comment by CardinaLiv** [comment]
Climbing over the network, this problem arose not only I also came across a similar problem for a user with the linux mint operating system

**Comment by bpasero** [comment]
@CardinaLiv to clarify: you open an entire folder in VSCode that is backed by FTP? And files open empty? If that is true can you somwhow give me a detailed explanation how to set this up on my Ubuntu to reproduce? Thanks!

**Comment by CardinaLiv** [comment]
Miogu suggest teamviewer to demonstrate the problem

**Comment by CardinaLiv** [comment]
@bpasero and on the settings of Ubuntu 16.04 PCmanFM / FileZilla as a ftp connection manager. VS Code version 1.33.1 as it works. To check on new versions, I just update VS Code through the Ubuntu update manager, if it doesn’t work, I roll back to version 1.33.1

**Comment by bpasero** [comment]
@CardinaLiv 

> and on the settings of Ubuntu 16.04 PCmanFM / FileZilla 

Any further information how that setup works, I would really like to set this up myself to debug this issue.

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/73884
