### ISSUE TITLE
Auto import: dependencies listed in package.json should be prioritized

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/vscode#78322]
**Background**

When I'm importing a dependency, I never want to import an implicit dependency (one that is not listed in my local `package.json`). [See how that works.](https://i.imgur.com/zA9JxWx.gif)

**Motivation**

Quoting TSLint and ESLint documentation, respectively:

> Disallows importing transient dependencies and modules installed above your package’s root directory.

> This helps prevent accidentally depending on a module that is present in node_modules as a result of being installed further down your dependency tree, but is not listed as an explicit dependency of your project.

**Existing solutions**

Both TSLint and ESlint offer rules and plugins to prevent importing implicit dependencies, but instead of importing one and immediately deleting it, it would make sense to exclude implicit dependencies from the list of suggestions so they don't get imported in the first place.

- https://palantir.github.io/tslint/rules/no-implicit-dependencies/
- https://github.com/lennym/eslint-plugin-implicit-dependencies

**Proposed solution**

Add a configuration option.

TSLint and ESLint allow their rules to be configurable in a way that allows for importing from:

- `devDependencies`
- `optionalDependencies`
- `peerDependencies`

So the configuration could look like that:

```json
{
  "typescript.preferences.importFrom": {
    "dependencies": true,
    "peerDependencies": true,
    "devDependencies": false,
    "optionalDependencies": false,
  } 
}
```

However, it should be also possible to allow importing from aliased paths. If a project uses a mapping from `./src/` to `'src'`, then `'src'` must not be treated as an implicit dependency.

In that case, it might be easier to reverse the situation and _disallow_ directories as opposed to whitelisting them.

```json
{
  "typescript.preferences.excludeFromAutoImport": {
    "dependencies": false,
    "peerDependencies": false,
    "devDependencies": true,
    "optionalDependencies": true,
  } 
}
```

**Comment by OliverJAsh** [comment]
Potentially related: https://github.com/microsoft/TypeScript/issues/31199

**Comment by IllusionMH** [comment]
It will be partially fixed with: https://github.com/microsoft/TypeScript/pull/32517 which will remove anything that is not added in `package.json` (there won't be any transitive dependencies in suggestions).
However more control after that will be great!

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
