### ISSUE TITLE
Allow easy accepting/rejecting changes from both versions on save conflict

### ISSUE THREAD

**Issue by ezk84** [microsoft/vscode#78325]
This is the same as #47250 which is closed and locked, but I will try to explain in more detail.

Normally when there is an SCM merge conflict I can do a side by side comparison, can navigate conflicts one by one and can choose which version to keep (or to keep both) by using commands or buttons on the UI in addition to manual editing.

However, when there is a save conflict (the file I am trying to save has been modified elsewhere since I opened it) I get an error. I can then click "Compare" and get a side-by-side comparison. I can navigate differences with the arrows on top of the editor but crucially *I have to manually copy and paste wanted changes from the on-disk version onto the VS Code version* if I want to keep them.  There are buttons that allow *accepting my changes* and *discarding my changes*, which are both all-or-nothing operations; there is no easy way to merge a bit of both. 

Instead, it would be nice to have buttons/commands that allow accepting changes one at a time, from either source in the same way as a merge conflict.

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by ichtestemalwieder** [comment]
Hello, 
I have the same problem. I am new to VSC and VSC is so unbelievably great! I love it. But what I can not understand at all, that this absolutely basic feature is not present! 

What we want is a  <= and => Icon on each changed line that allows me to copy the changes to the other side/document, which actually  means "accept the change" or "discard the change"  
Please see example mock below with the blue icons below.  

![image](https://user-images.githubusercontent.com/54768881/66542109-e4704a80-eb31-11e9-8750-f8372426c822.png)

@joaomoreno : Please note. As you added the git-merge Flag/Label. What ezk84 and I mean is  not only for git merges but for general file merges!

You can have a look at the open source software "Win Merge" which has a great interface for doing that kind of merges. https://winmerge.org/?lang=en

Thanks very much.

**Comment by joaomoreno** [comment]
@bpasero This is about non-scm save conflicts.
