### ISSUE TITLE
Build task fails when Live Share is disabled

### ISSUE THREAD

**Issue by infixint943** [microsoft/vscode#78323]
Issue Type: <b>Bug</b>

Build task(using keybinding `ctrl+shift+b`) doesn't work if live share is disabled or uninstalled. No build task takes place, and no error message is given on why it failed. However, enabling live share seems to fix the problem.
Note that this problem occurs while trying to build cpp files. I have not tested this on other files.

This question has been migrated from the vscode-cpptools repo. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.20.17-042017-generic

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.24.1

(1 theme extensions excluded)

</details>

**Comment by infixint943** [comment]
Seems like even test task fails. Even running build task(or test task) from the command pallete produces similar results.

**Comment by alexr00** [comment]
Can you share your build task?

**Comment by infixint943** [comment]
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "g++-8 build active file",
            "command": "g++-8",
            "args": [
                "-g",
                "${relativeFile}"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Run",
            "type": "shell",
            "command": "${workspaceFolder}/a.out",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "focus": true,
                "echo": false,
                "showReuseMessage": false,
                "panel": "dedicated"
            }
        }
    ]
}
```

**Comment by alexr00** [comment]
Nothing looks concerning there. Can you share your settings.json? I'm wondering if you have some setting that is causing you task to need live share.

**Comment by infixint943** [comment]
```
{
    "window.menuBarVisibility": "toggle",
    "C_Cpp.updateChannel": "Insiders",
    "workbench.statusBar.visible": false,
    "explorer.confirmDelete": false,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.intelliSenseCacheSize": 0,
    "editor.minimap.enabled": false,
    "files.exclude": {
        ".vscode": true,
        "*.code-workspace": true
    },
    "workbench.activityBar.visible": true,
    "terminal.integrated.rightClickBehavior": "copyPaste",
    "debug.internalConsoleOptions": "neverOpen",
    "terminal.external.linuxExec": "gnome-terminal",
    "workbench.editor.tabCloseButton": "left",
    "breadcrumbs.enabled": false,
    "files.watcherExclude": {
        "*.code-workspace": true
    },
    "extensions.showRecommendationsOnlyOnDemand": true,
    "workbench.colorTheme": "Shades of Purple",
    "editor.fontFamily": "monospace",
    "editor.fontLigatures": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.drawBoldTextInBrightColors": false,
    "debug.showInStatusBar": "never"
}
```

**Comment by alexr00** [comment]
If you open the dev tools (Developer: Toggle Developer Tools) is there anything in the console after you hit this issue?

**Comment by infixint943** [comment]
When live share is disabled, after trying to run build task(`ctrl+shift+b`) and test task(`ctrl+shift+t`). Note that no message is displayed on running build or test task. All the message's occur after reloading vscode, after disabling live share.
![Screenshot from 2019-08-02 18-33-23](https://user-images.githubusercontent.com/45997896/62372299-c1835200-b554-11e9-9f16-3b5e342ca3ac.png)

The below screenshot is after re-enabling live share. The warnings and error occur right after enabling live share.
![Screenshot from 2019-08-02 18-33-38](https://user-images.githubusercontent.com/45997896/62372405-0c9d6500-b555-11e9-91f5-f6361922e468.png)

**Comment by alexr00** [comment]
Are the settings you shared user or workspace settings? Can you share which ever one you haven't shared yet?

**Comment by alexr00** [comment]
Can you also share your keybindings.json?

**Comment by infixint943** [comment]
How do check which is what?

**Comment by infixint943** [comment]
```
[
    {
        "key": "ctrl+shift+t",
        "command": "workbench.action.tasks.test"
    }
]
```

**Comment by infixint943** [comment]
settings.json
```
{
    "window.menuBarVisibility": "toggle",
    "C_Cpp.updateChannel": "Insiders",
    "workbench.statusBar.visible": false,
    "explorer.confirmDelete": false,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.intelliSenseCacheSize": 0,
    "editor.minimap.enabled": false,
    "files.exclude": {
        ".vscode": true,
        "*.code-workspace": true
    },
    "workbench.activityBar.visible": true,
    "terminal.integrated.rightClickBehavior": "copyPaste",
    "debug.internalConsoleOptions": "neverOpen",
    "terminal.external.linuxExec": "gnome-terminal",
    "workbench.editor.tabCloseButton": "left",
    "breadcrumbs.enabled": false,
    "files.watcherExclude": {
        "*.code-workspace": true
    },
    "extensions.showRecommendationsOnlyOnDemand": true,
    "workbench.colorTheme": "Shades of Purple",
    "editor.fontFamily": "monospace",
    "editor.fontLigatures": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.drawBoldTextInBrightColors": false,
    "debug.showInStatusBar": "never"
}
```

**Comment by infixint943** [comment]
*.code-workspace
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"files.associations": {
			"iostream": "cpp"
		},
		"debug.internalConsoleOptions": "neverOpen"
	}
}
```

**Comment by infixint943** [comment]
Are you able to replicate the issue?

**Comment by alexr00** [comment]
I am not able to reproduce the issue. Can you run the build task by opening the command palette and running the build task from there?

**Comment by infixint943** [comment]
> Can you run the build task by opening the command palette and running the build task from there?

No. Build task doesn't work using any method.

**Comment by infixint943** [comment]
I'm running on ubuntu 18.04, if that helps.
Steps to reproduce:
- Install cpp-tools (microsoft extension)
- Set-up build task
- Install Live Share
- Reload VSCode
- Disable Live Share
- Try running the build task now.

**Comment by alexr00** [comment]
On ubuntu I can reproduce that the _keybinding_ vanishes which is a problem. But I'm not seeing it ever come back. Running the build task from the command palette still works.

**Comment by alexr00** [comment]
Can you try running the task using Run Task instead of Run Build Task?

**Comment by infixint943** [comment]
Nope. I'm having no luck using any method.
Is there any way to delete VSCode along with all files it would have created?
I'll try a complete reinstall and check.

**Comment by infixint943** [comment]
I did a complete reinstall, deleting ~/.configs/Code, ~/.vscode and ~/.vscode-cpptools. Then I reinstalled cpp-tools and now build task works fine without live share.

**Comment by infixint943** [comment]
I've installed Live Share, and build and test task works when live share is disabled. Thanks for all your help!
