### ISSUE TITLE
Jenkins pipeline linter connector

### ISSUE THREAD

**Issue by vinith03** [microsoft/vscode#78329]
Issue Type: <b>Bug</b>

I couldn't find any jenkins pipelin linter extension in the dropdown(task, git, extensions,  ...) which is available in the output window. Is it possible to view? or Do i have to do anything further?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.4.0-157-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.69GB (1.22GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
jenkins-pipeline-linter-connector|jan|1.1.7

</details>

**Comment by joaomoreno** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vsts.services-jenkins
