### ISSUE TITLE
Expanding an object when it is the bottom of the scroll view should scroll with the expand

### ISSUE THREAD

**Issue by orta** [microsoft/vscode#78336]
If I'm debugging and at the bottom of my current scroll view:

![Screen Shot 2019-08-01 at 1 03 28 PM](https://user-images.githubusercontent.com/49038/62312711-e8f6f380-b45c-11e9-9d56-7876aa280ecd.png)

Clicking on `NodeObject` would ideally trigger a scroll down with it:
![Screen Shot 2019-08-01 at 1 04 46 PM](https://user-images.githubusercontent.com/49038/62312752-0035e100-b45d-11e9-8c31-4606e44dfa71.png)

**Comment by joaomoreno** [comment]
@isidorn I'm not convinced this should be a feature of the tree as it will cause friction. Feel free to do this at the repl level if you think it's a fair request.

**Comment by isidorn** [comment]
This is a fair feautre request. And yes we can do it on the REPL.
Assigning to next milestone to look how feasable it is. Thanks

**Comment by isidorn** [comment]
I looked into this and there are two minor challanges
1. The `onDidChangeCollapseState` event from the tree comes a bit too early, as soon as the user expanded, not when the children got  resolved. So we have to react to this event with a timeout, which is a bit hacky
2. Idealy we would not scroll all the way down, but still keep the expanded object visible while showing as much children as possible. This requires some math with the `tree.scrollTop`

I will not add this feature request. However here's a code pointer in case someone is intrerested in providing a nice PR
https://github.com/Microsoft/vscode/blob/079aef1ec5549171717decf30a9cb3e5b8aeee18/src/vs/workbench/contrib/debug/browser/repl.ts#L414

And here's an example of the `scrollTop` math which should be modified for this particular use case https://github.com/Microsoft/vscode/blob/079aef1ec5549171717decf30a9cb3e5b8aeee18/src/vs/workbench/contrib/debug/browser/repl.ts#L83
