### ISSUE TITLE
Panel will be small if using multiwindow

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#78338]
From slack:
> If you deserialize a view that is both hidden and has a cached view size and then immediately close the window without resizing. The resulting grid will have that view serialized without any cached view size. The repro for this on Windows is as follows.
• Set Restore WIndows to one
• Open a folder, set the terminal to a size above minimum,  close the window.
• Open a window (should be the same folder as before due to setting)
• Ctrl+Shift+N a new window
• Close the first window
• Close the second window
• Open a new window (should be empty workspace)
• In the same window open recent > the folder from above
• Bug => Panel is visible but minimum size

**Comment by joaomoreno** [comment]
Easier steps:

1. Resize panel to X
2. Hide panel
3. Reload
4. Reload
5. Show panel

Panel doesn't take X height.
