### ISSUE TITLE
Settings UI does not add array settings correctly

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#78339]
Issue Type: <b>Bug</b>

1. Have GHPR extension installed
2. Try to add a remote via the settings UI
3. It will fail because the settings.json does not have the setting in it yet. 
4. Add  `"githubPullRequests.remotes": []` to your settings.json 
5. Add a remote via the settings UI, it will succeed

VS Code version: Code - Insiders 1.37.0-insider (92da68a71cfb60bd3b9b0d7fbfb2a7e1fff9dbaf, 2019-08-01T05:33:41.496Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by octref** [comment]
https://github.com/microsoft/vscode-pull-request-github/blob/1496ba06870d887ab7a4ea1ea12ea3992f10c45c/package.json#L72-L79

That's because that setting has type array and default `null`. Although I asked @rebornix to change it I handled this case as well.

To verify:

- In an extension like https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample
- Contribute a setting like so:

  ```json
        "githubPullRequests.remotes": {
          "type": "array",
          "default": null,
          "items": {
            "type": "string"
          },
          "markdownDescription": "List of remotes to fetch pull requests from. If no remotes are specified, will default to `upstream` or `origin` if these remotes are present, or all valid GitHub remotes."
        }
  ```

- Make sure you can add new key to it in the Settings UI from unset setting state

**Comment by Tyriar** [comment]
@rebornix shouldn't the default be something like `["origin", "upstream"]` instead of `null`?

**Comment by octref** [comment]
@Tyriar That's up for @rebornix to decide. I also agree it should at least contain `origin`.

**Comment by rebornix** [comment]
Thanks, I think it should be `["origin", "upstream"]`.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode-pull-request-github/issues/1289
