### ISSUE TITLE
Box-drawing characters not monospaced

### ISSUE THREAD

**Issue by rslemos** [microsoft/vscode#78342]
Issue Type: <b>Bug</b>

Some (if not all) box-drawing characters are not correctly aligned. Also there seems to be a space between lines of text. Here some examples:

(tree building)
╮  ╭
╰┬─╯
 │  
 ├╴╶
 ╰╴ 

(table building)
╔═╤╗
║ │║
╠═╪╣
╚═╧╝

I'm using Consolas typeface.

VS Code version: Code - Insiders 1.37.0-insider (cf03ea3729dc37e439d724267ad29dc5840f903a, 2019-07-30T07:15:22.972Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (3.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.9.2
graphviz-markdown-preview|gee|0.0.8
vscode-firefox-debug|hbe|1.8.1
vscode-graphviz|joa|0.0.5
vscode-antlr4|mik|2.1.1
mssql|ms-|1.6.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.6
java|red|0.47.0
vscode-xml|red|0.8.0
mdx|sil|0.1.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
vscode-icons|vsc|9.2.0

</details>

**Comment by joaomoreno** [comment]
Screenshot?

**Comment by rslemos** [comment]
![image](https://user-images.githubusercontent.com/954487/62394872-e8d22300-b544-11e9-9bae-14a51eeac30a.png)

"Rectangular" selection of 10 lines x 8 columns.
All those lines align neatly if truly monospaced.

**Comment by rslemos** [comment]
Using https://opentype.js.org/font-inspector.html and https://opentype.js.org/glyph-inspector.html I just found that Consolas font does not define a glyph for U+256D to U+2570 (rounded corners), U+2574 and U+2576 (half horizontal lines left and right).

So vscode draws those graphics using another font.

**Comment by rslemos** [comment]
"Source Code Pro" is a better font for this. Thanks.
