### ISSUE TITLE
Open files in new window more intelligently

### ISSUE THREAD

**Issue by Zarel** [microsoft/vscode#78341]
VS Code's "Open Files In New Window" feature has three options:

- on: always in new window
- off: file's folder-window if available, otherwise last active window
- default: "off" for opening with commandline, "on" for opening with a GUI

None of these options actually seem all that great to me, and they all make it kind of annoying to open files with Finder.

My preferred behavior would be:

File's folder-window if available, otherwise last active window without an open folder if available, otherwise new window.

In other words, say I'm working on a project in `~/Projects/foo`. I have one VS Code window open, set to the project folder. If I double-click `~/Projects/bar/README.md` and `~/Projects/bar/LICENSE`, I want them to open as tabs in window 2.

Currently, there's no way to do that. "on" will create two new windows (which takes lots of effort to merge into one: drag the second window away, drag the second window's tab into the first window, gesture Mission Control, select the second window, close it), and "off" will open both files in my project window.

My current workaround is to set my default text editor to Sublime (set to open new files in tabs), and then open projects in VS Code. But I'd prefer to use VS Code for all my text editing.

**Comment by OneMoreSecond** [comment]
I feel this feature is exactly what I want. Usually I want to open ad-hoc files in a dedicated window and "last active window without an open folder" will be suitable.
