### ISSUE TITLE
Issues with source control example extension

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78340]
- Clone and run the extension
- Run "Open JS Fiddle"
- Pick "demo"
- Pick some folder
- That folder is added to the workspace with some `.jsfiddle` file but nothing else happens, there is no source control provider in the source control viewlet
- Run "Refresh JS Fiddle status"
- Get `command 'extension.source-control.refresh' not found`

When I run "Open JS Fiddle" I see writeFile in `saveConfiguration` calling its error callback with `null` even though it seemed to write the file successfully. Then the debug session terminates and it seems that the EH is hung or crashed.

**Comment by joaomoreno** [comment]
cc @jan-dolejsi

**Comment by jan-dolejsi** [comment]
Thanks. I will have a look. What is your operating system?

**Comment by jan-dolejsi** [comment]
I reviewed and re-tested the workspace folder management and found several issues that could cause the behavior you are describing. I believe there was a race condition happening between the async file writing and VS Code reloading the extension upon workspace folder addition. 

I have cleaned up the async file system operations and made the sample more robust.

Could you please test this PR?
https://github.com/microsoft/vscode-extension-samples/pull/202

**Comment by roblourens** [comment]
Works for me! I did not review the code changes in depth though.
