### ISSUE TITLE
disable/enable extension for specific language

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#78349]
Hello

This can be a useful option - disable or enable a specific extension for a specific language.
It could be identify by extension id

Maybe something like:
![obraz](https://user-images.githubusercontent.com/30685349/62323688-20d75880-b4a8-11e9-8773-dbe81d45df2e.png)

**Comment by sandy081** [comment]
What do you mean by disabling or enabling an extension per language?

**Comment by kanlukasz** [comment]
For example, I'm using a plugin like `Highlight Matching Tag`. I want to use it for XML files, but I do not want to use it in HTML files at the same time

The next example is that I use the `Prettier` plugin. I would like it to function only in JS files.

These are two examples that immediately came to my mind, but I think there are more cases where it could be useful

**Comment by kanlukasz** [comment]
A little similar ticket: #40239
Not the same but similar

**Comment by sandy081** [comment]
I do not think it is possible by disabling the extension. Because we can disable an extension completely but not only for some files.
