### ISSUE TITLE
Terminal output is corrupted

### ISSUE THREAD

**Issue by dannypike** [microsoft/vscode#78344]
Issue Type: <b>Bug</b>

Since the most recent update (1.36.1 according to the Help|About box), the output in the Terminal is getting messed up when I scroll up and down using the mouse-wheel and/or scroll bars.

It appears as though VSCode suddenly decides to wrap the lines too early and fails to clear the remaining part of each line, which continues to display the previous contents resulting in gibberish. I've turned off [word wrap](http://prntscr.com/on4dqv) but, at the moment, it's decided to wrap each line at 112 characters.

If I shrink and expand the main window to force it to repaint the terminal, the line length gets shorter and shorter; here's it with only [10 characters per line on all but the final line](http://prntscr.com/on4f17).

I only noticed this behaviour in the most recent upgrade, but I may have changed other settings in the meantime.

**Comment by Tyriar** [comment]
Platform and vscode version, also a screenshot would help

**Comment by dannypike** [comment]
Thanks for the speedy reply.

My question stated the VSCode version in the first sentence and gave a couple of links to screenshots showing the terminal window output, and the word-wrap settings.

Is there some other version information that I should have given?

What other screenshot(s) do you need?

**Comment by Tyriar** [comment]
@dannypike oh, by the way you can inline images by dragging them into the comment box.

**Comment by Tyriar** [comment]
Can you show a screenshot showing the panel title and terminal dropdown as well? FYI that setting only applies to the debug console, not the terminal.

**Comment by dannypike** [comment]
Here's a sequence where I make the VSCode window almost full screen (not maximised):

![1_large](https://user-images.githubusercontent.com/18309713/62392204-c5b46d00-b55e-11e9-95b6-0cde0f39b5f1.jpg)

then made it narrow so that VSCode wraps the text:

![2_shrinkToWrap](https://user-images.githubusercontent.com/18309713/62392254-e4b2ff00-b55e-11e9-9b66-b2123ea52f95.jpg)

then wide again:

![3_expandToLarge](https://user-images.githubusercontent.com/18309713/62392270-f399b180-b55e-11e9-97d3-1663d0c2e235.jpg)

and, finally, I scrolled up using the scroll bar (though I see the same effect with the mousewheel):

![4_scrollUpAFewLines](https://user-images.githubusercontent.com/18309713/62392300-0613eb00-b55f-11e9-9871-b5a907dee796.jpg)

This was all done quite slowly and steadily, i.e. taking a second or two just to allow things to react to events. The effect is very similar to a partial-paint issue except for the fact that I can select the corrupted text and copy-paste it into a separate text editor to show that it is not just a display artefact, the terminal does really think that this the output that it should be displaying.

**Comment by Tyriar** [comment]
Looks like this is happening due to either winpty (Windows 10 <= 1809)or conpty (Windows 10 >= 1903), they hold a copy of the buffer and handle all the resizing and redrawing of the terminal which can cause weird quirks like this.

**Comment by dannypike** [comment]
I don't know what conpty or winpty are, or who to ask to get them fixed. Do you?

**Comment by Tyriar** [comment]
They emulate how unix terminal work, if you can reproduce this using [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot%3Aoverviewtab) you can start a conversation over there https://github.com/microsoft/terminal

**Comment by dannypike** [comment]
thanks, I'll see what I can find out

**Comment by dannypike** [comment]
Unfortunately, I can't seem to run Windows Terminal; it says that it is installed but I cannot find any way to start it (doesn't appear on the  Start menu.

Apparently, it requires a Insider version of Windows (>= 18362) and I am only on build 17763.652, as I am not on the Insider program.

Is there anything else that you think I could try to get this sorted out? Can I install a different terminal in VSCode?

**Comment by Tyriar** [comment]
If you're on build number 17763 then you have to be using winpty which is deprecated at this point. You should update to Windows 1903 to move to the new system that way the console team can action bugs if you find them.

**Comment by dannypike** [comment]
OK.

I need to be using the same Windows version as my customers, so that's not an option for me. Is there a reason why you have already deprecated something that is still in the "mainline" version of Windows?

**Comment by Tyriar** [comment]
Because it's an upstream package that we don't maintain, in order to solve this problem we now depend on the conpty API provided by the Windows team.

**Comment by dannypike** [comment]
It's a pity but I guess I'll just have to go back to using Command Prompt + Node for debugging.

Thanks a lot for the explanation.
