### ISSUE TITLE
VSCode reliably crashing on Fedora 30

### ISSUE THREAD

**Issue by DrBluefall** [microsoft/vscode#78347]
Attempting to run VSC at all leads to an immediate crash. I've had this reliably happen with both the Stable and Insiders builds of VSC. Running `code --verbose` results in the following output: https://pastebin.com/xvVEV45V

In both tests, I had a clean install of VSC on version 1.36.1, on Fedora 30.

**Comment by deepak1556** [comment]
@DrBluefall  can you try the following builds which is based on Electron 6, to see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
