### ISSUE TITLE
Integrated terminal handles some ansi escapes incorrectly

### ISSUE THREAD

**Issue by allight** [microsoft/vscode#78355]
Issue Type: <b>Bug</b>

1) in gnome-terminal or xterm run the following program

```
while true; do echo abc; echo def; echo hij; echo '\x1b[0;10r\x1b[11;0Habc hijk\x1b[K\ndef hij\x1b[K\x1b[10;0H'; sleep 1; done
```

2) Observe the terminal.

3) run the same program in the vscode terminal (with the height being at least 13 rows.

Expected:
Idential output

Result:
the line 'abc hijk' is missing.

This test case is extracted from the behavior of soong when used to build AOSP.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.19.37-5rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (72 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|24, 32, 30|
|Memory (System)|187.62GB (30.46GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
togglehs|bbe|0.1.2
smali|cra|1.0.1
vsc-material-theme|Equ|29.2.0
todo-tree|Gru|0.0.139
better-cpp-syntax|jef|1.12.21
vscode-clangd|llv|0.0.15
cpptools|ms-|0.24.1
material-icon-theme|PKi|3.8.1
java|red|0.46.0
vscode-header-source|ryz|1.3.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.4.3
code-spell-checker|str|1.7.17
vscode-icons|vsc|9.2.0
vim|vsc|1.9.0
gitblame|wad|3.0.0
vscode-todo-highlight|way|1.0.4
clang-format|xav|1.9.0
markdown-all-in-one|yzh|2.4.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
@jerch another edge case related to scroll top/bottom?

**Comment by jerch** [comment]
Already PRed: https://github.com/xtermjs/xterm.js/pull/2355
