### ISSUE TITLE
Comment thread button actions appear twice

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78356]
- Run the comment thread sample
- Create a note
- Click "Edit" on the note
- See the Cancel and Save buttons twice

![image](https://user-images.githubusercontent.com/323878/62333332-f372b680-b477-11e9-97e0-56f659a9b9f3.png)

**Comment by ATheCoder** [comment]
What is the "comment thread sample" ?

**Comment by roblourens** [comment]
This sample extension https://github.com/microsoft/vscode-extension-samples/tree/master/comment-sample
