### ISSUE TITLE
Source control window with submodules - no bulk hide

### ISSUE THREAD

**Issue by darobs** [microsoft/vscode#78359]
Issue Type: <b>Feature Request</b>

I have a project with a C library in it.  The C library has git submodules.  Those submodules have submodules.  All in all, I have 20 or so submodules, and I really only care about the top one, because I'm not working on the C library.

When I bring up the source control sidebar, I have all 20 displayed.  I don't care about the other 19, so I want to hide them.  So far, the fastest way to hide them is to select each one, right-click and select "hide" from the menu.  I'd love it if there way a faster way to do this.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by darobs** [comment]
A good example:  https://github.com/Azure/azure-iot-sdk-c

**Comment by joaomoreno** [comment]
The first view of SCM shows a list of all open repositories. You can use this as a visibility toggle as well. If you click one repo there, only that repo will become visible. It supports multiple selection as well. Let me know if that works for you.

**Comment by darobs** [comment]
Thank you - that did work.
