### ISSUE TITLE
Using for as a prefix for snippets, does not allow comments to be included

### ISSUE THREAD

**Issue by blachawk** [Microsoft/vscode#7835]
- VSCode Version:1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. create a javascript snippet with the prefix for.
2. try to add a comment to the snippet, along with the javascript code.
3.processing the snippet does not allow comments to be shown, until you change the prefix name to something else.
4.more on my initial fiinding can be seen here - http://stackoverflow.com/questions/37889412/visual-studio-code-how-to-include-comments-in-a-new-javascript-snippets

**Comment by aeschli** [comment]
I tried your snippet from http://stackoverflow.com/questions/37889412/visual-studio-code-how-to-include-comments-in-a-new-javascript-snippets
and it seems to work.
![image](https://cloud.githubusercontent.com/assets/6461412/16957822/4f8e0c48-4dde-11e6-817d-a517286fa57e.png)

Can it be that you accidentally picked the built-in for snippet? It also has name 'for' and has the same content as yours except the comment.
![image](https://cloud.githubusercontent.com/assets/6461412/16957883/8f15a434-4dde-11e6-85f1-d8c60d418117.png)
