### ISSUE TITLE
Support fontStyle "strikethrough" about theme

### ISSUE THREAD

**Issue by stakiran** [microsoft/vscode#78358]
Feature Request.

## Request
Currently v1.36.1, supported fontStyles in theme customization are `bold`, `italic` and `underline`.

But I want to use `strikethrough` too. like this:

```json
		{
			"name": "FinishedTaks",
			"scope": [
				"task.fiinshed"
			],
			"settings": {
				"foreground": "#ffff00",
				"fontStyle" : "strikethrough"
			}
		}
```

## FYI
VSCode sources:

-  [src/vs/editor/common/modes/supports/tokenization.ts#L63](https://github.com/microsoft/vscode/blob/013501950e78b9dde5c2e6ec3f2ddfb9201156b7/src/vs/editor/common/modes/supports/tokenization.ts#L63)
- [src/vs/editor/common/modes.ts#L70](https://github.com/microsoft/vscode/blob/aba87f135229c17c4624341b7a2499dcedafcb87/src/vs/editor/common/modes.ts#L70)

TextMate source:

- [Frameworks/theme/src/theme.cc#L76](https://github.com/textmate/textmate/blob/b17253ae035978964ae3d137a847554d211caff7/Frameworks/theme/src/theme.cc#L76)

TextMate supports strikethrough.

**Comment by pumpkinlink** [comment]
this would be perfect for semantic syntax highlighting in regards to deprecated methods
