### ISSUE TITLE
Float window below console tab

### ISSUE THREAD

**Issue by schneiderbruno** [microsoft/vscode#78353]
Hello everybody,

I suggest create one function to enable resize window to below, while there is already more than one window open.

Thx, VSC is wonderfull!!

![Sem título](https://user-images.githubusercontent.com/8595383/62331103-44db6f80-b491-11e9-8e9f-730086312b60.png)

**Comment by joaomoreno** [comment]
Unfortunately that is not possible. But you can always split down first and then split horizontally.
