### ISSUE TITLE
Notification popup is non-responsive to any mouse input

### ISSUE THREAD

**Issue by chris-findlay** [microsoft/vscode#78360]
Issue Type: <b>Bug</b>

I happened to open a .gql file and got the (expected) popup about going to find a plugin for this type of file, but it didn't respond to the mouse at all, other than if I clicked the background of it, it got focus, allowing me to tab to the button and invoke it with the keyboard.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
tt-processor|ais|0.8.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.2
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
terraform|mau|1.3.12
rainbow-csv|mec|1.2.0
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
vscode-coverage-gutters|rya|2.4.0
code-clip-ring|Sir|0.4.0
vscode-todo-highlight|way|1.0.4
t4-support|zbe|0.4.3

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that popup?
