### ISSUE TITLE
why my font width so strange?

### ISSUE THREAD

**Issue by salamander-mh** [microsoft/vscode#78361]
![image](https://user-images.githubusercontent.com/16663435/62339661-61b68800-b50f-11e9-8119-839a864f5479.png)

- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:
it happened when I upgrade the vscode, I don't know how to reproduce.
1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by kanlukasz** [comment]
1. Did you try check it on Insider version?
2. Did you try check it on portable stable release?

---

> Does this issue occur when all extensions are disabled?: No

- So, maybe this is because any extension?

**Comment by Tyriar** [comment]
Because you're using non-monospace font, change your editor.fontFamily to a monospace one.

**Comment by salamander-mh** [comment]
@Tyriar  I know I have to change the **workspace** font family.
