### ISSUE TITLE
Terminal "clear" command bug

### ISSUE THREAD

**Issue by gokayokutucu** [microsoft/vscode#78369]
"clear" command just hides the cleaned rows. It does not clean the terminal screen really.

**Comment by Tyriar** [comment]
Platform and vscode version?

**Comment by gokayokutucu** [comment]
MacOS Mojave and Version 1.36.1

**Comment by Tyriar** [comment]
Are you running the `clear` command in the terminal or are you running the VS Code `Terminal: Clear` command?

**Comment by gokayokutucu** [comment]
I am running the command on vs code integrated terminal.

**Comment by formulahendry** [comment]
Meet with the same issue. Seems like a regression staring from v1.36
![terminal-clear](https://user-images.githubusercontent.com/1050213/62844699-a1daef00-bcf5-11e9-898d-9145c7c93ae2.gif)

**Comment by Tyriar** [comment]
@formulahendry that's not a regression https://github.com/microsoft/vscode/issues/75141
