### ISSUE TITLE
Command+click and alt+click shortcuts are switched

### ISSUE THREAD

**Issue by jooleeanh** [microsoft/vscode#78368]
Normally in my workspace:
- cmd-click: goes to declaration
- alt-click: creates a new cursor
For some reason, these two commands got switched yesterday (2019/08/01).
All the other shortcuts with commands and alts still work as expected.
Yes, I've made sure I'm pressing the right button 😁 

- VSCode Version: 1.36.1
- OS Version: Mac OS 10.14.5

Steps to Reproduce: 
1. Pressing cmd and hovering over a method does nothing (should make it look like a hyperlink and show a preview of the declaration)
2. Pressing cmd+click creates a new cursor
3. Pressing alt and hover over a method changes the method name style to a hyperlink and shows a preview of the declaration (should not do anything)
4. Pressing alt+click goes to declaration.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I can't reproduce this. If you open Settings and search for `multi cursor modifier`, what's that setting's value?
