### ISSUE TITLE
Overwrite default behaviour to display unsupported files anyway

### ISSUE THREAD

**Issue by timfayz** [microsoft/vscode#78363]
When I'm trying from the sidebar to open the files either binary or unsupported I get the following:

> The file is not displayed because it is either binary or uses an unsupported text encoding. Do you want open it anyway?

![image](https://user-images.githubusercontent.com/6209197/62350916-d805bb00-b50c-11e9-9922-8609bcee91ad.png)

That's good but could we override it somehow through the settings? For example, it happens all the time when I click on pdf files. But when I further click _open it anyway_ it kicks me a nice preview. So constantly clicking that button becomes really annoying one day.

**Comment by mik3y64** [comment]
+1. I have similar issues. Currently, I click this button more than 20 times per day. Having to click the button every single time really break my workflow. Please support it and allow users to overwrite the default behaviour. Thank you.
