### ISSUE TITLE
The code process does not killed when debug restarted

### ISSUE THREAD

**Issue by avtrifanov** [microsoft/vscode#78365]
Issue Type: <b>Bug</b>

I'm using python and pytest for testing and found the follwing issue.
When I'm start a debugging of test the vscode spawns a new process with following agruments: `/usr/share/code/code -e delete process.env.ELECTRON_RUN_AS_NODE;require(process.argv[1])`

This process is spawned by process:
`/usr/share/code/code --nolazy --inspect=25125 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost`

### Expected behavior
Code kills the unnecessary process when debugger is restarted.

### Actual behavior
Code doesn't kill the unnecessary process when debugger is restarted. Also the new one process is spawned.

### Steps to reproduse
Make a pytest test for function
Discover tests in vscode menu
Add breakpoint to test function
Run debugging of a test
Restart debugging when it stops at breakpoint

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.1.12-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3690)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.51GB (3.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.6.24221
csharp|ms-|1.21.0

</details>

**Comment by isidorn** [comment]
Can not reproduce with the node debugger.
This is up to the python debugger, please file it against their extension here https://github.com/microsoft/vscode-python
