### ISSUE TITLE
Visual Studio Code can't open file on gvfs ftp network

### ISSUE THREAD

**Issue by dnutiu** [microsoft/vscode#78364]
Issue Type: <b>Bug</b>

I'm currently using Ubuntu linux 16.04  and using the built in `Files` program I've connected to an ftp host. It seems like I can't use visual studio code to open files from that host, I tried to drag the file manually into code but the contents of the file are not displayed. 

The path of the file I want to open is: run/user/1000/gvfs/ftp:host=0.0.0.0/public/...

To connect to the FTP, I've opened the `Files` program and clicked `File -> Connect to Server...` 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 3154)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.53GB (1.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.7.0

</details>

**Comment by dnutiu** [comment]
Hello, 

When I use the `File->Open Folder`, I don't see the FTP folder in the right-side menu so I go navigate manually to the path `/run/user/1000/gvfs/` and open any sub-folder of `ftp:host=0.0.0.0`. 


VSCode loads filenames from the directory and displays them in the tree but when I click any of the files the contents will be blank.

Please note that I've used the `Files` program from Ubuntu & Gnome in order to mount the FTP under the path: `/run/user/1000/gvfs/ftp:host=0.0.0.0`. I didn't use VSCode to connect to the FTP directly.

```
tmpfs                         1628260      156   1628104   1% /run/user/1000
```
Here's a screenshot of the issue: 
![Image](https://i.imgur.com/wQkY92w.png)

Opening the file with gedit shows it's contents.

**Comment by bpasero** [comment]
@dnutiu awesome, thanks so much. I know what this is. Merging into https://github.com/microsoft/vscode/issues/73884
