### ISSUE TITLE
cannot copy/paste text and drag/drop file on VMware MacOS VsCode

### ISSUE THREAD

**Issue by panda919** [microsoft/vscode#78373]
I am using VScode final version on MAcOs mojave on VMpalyer 15 and host is win10.
But, after use VScode in 20 mins from MAcOS startup, suddenly copy/paste text (between windows10 and MacOS vmware's VScode ) doesn't work.
Even, Drag/Drop file Between win10 and Vm MacOS.
But, Once i restarted MacOS(without reinstall VMware tool), then it working well 10 mins
and after 10 mins, also copy/paste doesn't work.
I hope kindly help.

**Comment by joaomoreno** [comment]
Can you reproduce with another text editor, like Notepad?>

**Comment by panda919** [comment]
If I use another textEditor, I didn't got this error.
Only I get this issue on VScode.
Since I am using VScode mainly, current state is not good for me really

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by panda919** [comment]
I got same issue with your new MACos version.

**Comment by panda919** [comment]
Hey.
Actually, Now I am thinking I will never use VScode at all from now.
Current situation is very bad.
Only i can copy/paste in 10 mins after MacOS VMware.

**Comment by deepak1556** [comment]
@panda919 can you update your exploration build to the latest and see if the issue still persists. Thanks!

**Comment by panda919** [comment]
Thanks.
But I got same error yet on your new version!

**Comment by deepak1556** [comment]
Just to confirm the repro steps, this happens on MacOS mojave running inside VM on a windows host ? 

Can you run with `code <file> --enable-logging` and attach the logs you see when the copy/paste stops working ?

**Comment by panda919** [comment]
this happens on MacOS mojave running inside VM on a windows host.
and how to  run with code <file> --enable-logging?

**Comment by bpasero** [comment]
You pass it on the command line!
