### ISSUE TITLE
Custom tree not updating in specific case

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78371]
See context here: https://github.com/microsoft/vscode/issues/77000#issuecomment-517487512

**Comment by alexr00** [comment]
To verify, use gitlens and click on the item referenced in https://github.com/microsoft/vscode/issues/77000#issuecomment-517487512

**Comment by eamodio** [comment]
Thanks! I built from source and tried it out with the latest GitLens and it all looks good!
