### ISSUE TITLE
Research bar

### ISSUE THREAD

**Issue by 123456987789** [microsoft/vscode#78374]
Issue Type: <b>Feature Request</b>

I hope you can add a research bar on top of  the folder content, so I can search the file I want easily !

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by IllusionMH** [comment]
At this point there are 2 options to quickly find file:
1. <kbd>Ctrl + P</kbd> that will show quick open where you can type name of a file and pick it from the list.
2. If you have folder with file open: just start typing in Explorer view to highlight all matches and use <kbd>ArrowUp/ArrowDown</kbd> to navigate matches.

If these function doesn't fit your need could you specify more details of your proposal?

**Comment by 123456987789** [comment]
Exactly what I want ! Thank you very much !


On 8/2/2019 17:45，Andrii Dieiev<notifications@github.com> wrote：

At this point there are 2 options to quickly find file:

Ctrl + P that will show quick open where you can type name of a file and pick it from the list.
If you have folder with file open: just start typing in Explorer view to highlight all matches and use ArrowUp/ArrowDown to navigate matches.

If these function doesn't fit your need could you specify more details of your proposal?
