### ISSUE TITLE
New extension to open file relative to current directory

### ISSUE THREAD

**Issue by gpaul** [microsoft/vscode#78375]
I had the same issue as in https://github.com/Microsoft/vscode/issues/53279 and wrote a little extension to fix it: `quickOpenRelative`. 

See https://marketplace.visualstudio.com/items?itemName=gpaul.quickOpenRelative

The extension provides a single command `quickOpenRelative.quickOpenRelative` that opens the quick launch panel with the current directory path filled in, which is equivalent to trying to open a file in the current directory. I've bound my default `ctrl+p` to this command.

I would prefer to add this as a comment on that issue, but that conversation is locked. To the admins: please consider mentioning this extension on that issue and closing this one.

This is a public service accouncement, my good deed for the day.

**Comment by joaomoreno** [comment]
Thanks a lot @gpaul, I've added a comment there.
