### ISSUE TITLE
Auto fix on save

### ISSUE THREAD

**Issue by nxz91** [microsoft/vscode#78386]
Issue Type: <b>Bug</b>

"Auto fix on save" is not working, it tells "There is no formatter for javascript installed" – 5 minutes before it was working. I can somehow make it work for a few minutes and then it stops working again.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.3
vscode-eslint|dba|1.9.0
prettier-vscode|esb|1.9.0
json-escaper|jos|1.1.0
rainbow-csv|mec|1.2.0
vscode-docker|ms-|0.7.0
convert-css-in-js|pau|1.1.3
java|red|0.46.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
gitblame|wad|3.0.0

</details>

**Comment by ATheCoder** [comment]
Can you provide more information please?

**Comment by IllusionMH** [comment]
I see that you have `prettier-vscode` installed. If there are few extensions that can apply auto-formatting to file VS Code forces you to pick one to avoid conflicts.

What happens when you try to format code manually (using <kbd>F1</kbd> and `Format Document`)? I guess that you will see dropdown with choice.

**Comment by jrieken** [comment]
no actionable information
