### ISSUE TITLE
German localization misses Extensions viewlet title

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78383]
The Extensions viewlet title should be `Erweiterungen` and it seems that it has changed to `Extensions`. Not sure if this was a purposeful decision from the localization team.

Commented out the smoke test assertion for now: https://github.com/microsoft/vscode/commit/709a07d51919d3266ca71699c6ddfb2d3547c0e1

**Comment by dbaeumer** [comment]
I think it is more likely that code got shuffled around and this needs a new LP from the translation team which should come with when we release 1.37. Let's see if this fixes it.

**Comment by dbaeumer** [comment]
Actually, there is no a mix of Extensions and Erweiterung in the UI even embedded in German sentences. So it doesn't look like a LP issue.

<img width="600" alt="capture" src="https://user-images.githubusercontent.com/1931590/62545704-7faf2000-b862-11e9-891d-a85d75b5f694.png">

@danyeh can you please make sure this gets consistent, either using Erweiterungen or Extensions. But the current form is unhappy.

**Comment by lukaschal** [comment]
Strings localized correctly in a MLCP and json file.

https://github.com/madcoder2k17/visualstudio-code/blob/master/i18n/deu/src/vs/workbench/parts/extensions/browser/extensionsActions.i18n.json

"showOutdatedExtensions": "Veraltete Erweiterungen anzeigen",
"showPopularExtensions": "Beliebte Erweiterungen anzeigen",
"showRecommendedExtensions": "Empfohlene Erweiterungen anzeigen",
"showWorkspaceRecommendedExtensions": "Für den Arbeitsbereich empfohlene Erweiterungen anzeigen",
"showRecommendedKeymapExtensions": "Empfohlene Tastenzuordnungen anzeigen",

**Comment by barnabasn** [comment]
The strings are fixed in the freshly published language pack (1.38.1):
![image](https://user-images.githubusercontent.com/38212935/63871081-7de90000-c9bb-11e9-8cb7-20e4125ddc85.png)
Please close this issue if you are satisfied with the fix.
