### ISSUE TITLE
Integration test failure: Terminal sendText after createTerminal should not throw 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#78381]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=53474

![Screenshot 2019-08-02 at 15 04 50](https://user-images.githubusercontent.com/1926584/62372111-e5d03600-b536-11e9-9d9e-d36d12c307a6.png)

**Comment by Tyriar** [comment]
I expect the terminal tests to be much better after https://github.com/microsoft/vscode/commit/dc6b475be75999e78233f9f6951ef66f18f768ea
