### ISSUE TITLE
Twistie on a tree node doesn't get shown when the node is rerendered and child count toggles to/from 0

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78388]
Reported here: https://github.com/microsoft/vscode/issues/77000#issuecomment-517456842

Nice example: https://github.com/eamodio/vscode-simple

**Comment by joaomoreno** [comment]
Sorry @alexr00, didn't get the chance to get this done, pushing it out to September.

**Comment by joaomoreno** [comment]
Note to self: remember to revert https://github.com/microsoft/vscode/commit/dcdc7f0f8c2f02694f6b1b76aeeaeee35ce53a7f
