### ISSUE TITLE
Formating code is not working

### ISSUE THREAD

**Issue by nikhiljanshali** [Microsoft/vscode#7838]
- VSCode Version: 1.2.1
- OS Version:  10.0.10240

After updating last version i have an issue of basic intellisense and formatting code.

**Comment by dbaeumer** [comment]
@nikhiljanshali in which language. And can you provide sample code that demonstrate the behavior you are seeing.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
