### ISSUE TITLE
Disabled extension shows notification

### ISSUE THREAD

**Issue by ffes** [microsoft/vscode#78380]
As suggested by @sandy081 in https://github.com/microsoft/vscode/issues/76879#issuecomment-517223382:

A disabled extension can show a notification.

- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install the C++ extension (ms-vscode.cpptools)
2. Disable the extension globally
3. Restart vscode
4. See the question to take the survey appear

I can not easily reproduce these steps anymore. I clicked the "Take Short Survey" button to ensure it really was the C++ extension that shows ask the question. And now the notification doesn't seem to re-appear. I guess they store that somewhere. When it still was shown I think it was shown only once a day, but I am not sure. Maybe the team https://github.com/Microsoft/vscode-cpptools can help you with these questions.

![disabled-extension-shows-notification](https://user-images.githubusercontent.com/3225656/62371027-064ac100-b534-11e9-8f99-8c7f7966c701.png)

**Comment by sandy081** [comment]
Can you please check if the extension is running by opening `Show Running Extensions`?

**Comment by ffes** [comment]
@sandy081 At the moment it doesn't show up in as a running extension when I open a project where the extension is disabled.

But as I said in my original post, I don't see the notification anymore, maybe because I started the survey once, instead of closing the notification with `x`.

**Comment by sandy081** [comment]
Can you please click on the settings gear icon and see from which extension this notification is coming from? If the extension is disabled no notification should come from this extension. So do following

- Disable the extension
- Check if notification is shown
- If shown check from which extension it is coming from.
