### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by completedigital** [microsoft/vscode#78387]
Issue Type: <b>Performance Issue</b>

There's a few seconds lag when typing new lines of code.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   115	  4122	code main
    8	    49	  4123	   gpu-process
   52	    49	  4134	   shared-process
    0	     0	 96207	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   688	 62360	   window (style.css — icc)
    0	   131	 62361	     extensionHost
    0	   688	 62367	       electron_node server.js 
    0	   164	 62390	       php /Users/bentoms/.vscode/extensions/felixfbecker.php-intellisense-2.3.10/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:51568 --memory-limit=4095M
    0	   442	 62407	       electron_node server.js 
    0	    49	 62498	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=62361
    0	     0	 62701	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=62361
    0	    66	 63748	       electron_node tsserver.js 
    0	     0	 63753	         electron_node typingsInstaller.js typesMap.js 
    0	    16	 63749	       electron_node tslintServer.js 
    0	     0	 63882	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=62361
    0	     0	 64097	       electron_node server.js 
    0	    16	 62362	     watcherService
    0	     0	 62493	     /bin/bash -l
    0	    82	 96203	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css — icc)
|    Folder (icc): 2049 files
|      File types: php(919) js(482) css(253) png(139) gif(66) mo(34) po(34)
|                  jpg(25) json(17) txt(13)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
subtitles-editor|pep|1.0.4
vscode-css-peek|pra|3.0.2
code-spell-checker|str|1.7.17
lorem-ipsum|Tyr|1.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible without extensions?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Not related, but TSLint extension that you use is deprecated in favor of [ms-vscode.vscode-typescript-tslint-plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)

**Comment by completedigital** [comment]
The problem goes away with extensions disabled.
I turned them back on one by one and it seems it was the Beautify extension
causing the lag.

Thanks for the note about TSLint.
