### ISSUE TITLE
Work around for twistie on a tree node doesn't get shown when the node is rerendered and child count toggles to/from 0

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78389]
Custom tree view work around for https://github.com/microsoft/vscode/issues/78388

**Comment by alexr00** [comment]
@eamodio FYI, this should address the twistie not show/hiding that you were seeing.

**Comment by eamodio** [comment]
Great, thanks! Built from source and tried it out with the latest GitLens and it all looks good!
