### ISSUE TITLE
Installing an extension with dependencies installs old versions of the dependencies

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#78391]
I've seen this a few times when publishing new versions... it's probably something that fixes itself in time, but it feels a bit like a bug so I thought it was worth raising. Here's what I did:

- Published version v3.3.0 of the Dart extension
- Published version v3.3.0 of the Flutter extension (this depends on the Dart extension)
- Uninstalled both extensions from VS Code and restarted
- Installed the Flutter extension - which showed as v3.3.0 - however it installed v3.2.1 of Dart

I figured that maybe the Dart one just took longer to go through, so I ran "Check for extension updates" and it found v3.3.0 of Dart an updated it. So then I tried:

- Uninstalling both extensions again
- Searching for Dart in the marketplace - it shows v3.3.0
- Search for Flutter - also shows v3.3.0
- Install Flutter
- Once again, it installed Dart v3.2.1

I suspect something is cached and it'll fix itself soon, but I'm not sure what - my client has already seen (and installed) v3.3.0 of Dart, so I'm not sure why installed Flutter would somehow bring with it an old version.

**Comment by sandy081** [comment]
Did you try installing Dart extension separately and what version is being installed?

**Comment by DanTup** [comment]
It's been a while, but I'm certain I did install Dart and it got v3.3.0, then I uninstalled it and installed Flutter and it gave me old Dart (v3.2.1). I didn't mention it in the bullets above, but I did write "my client has already seen (and installed) v3.3.0" so I'm sure I'm not misremembering.

As expected, it's working fine today - so I suspect it's only a temporary issue after publishing, but since these always publish together it can be quite confusing to users.

**Comment by sandy081** [comment]
Looks like a caching issue on Marketplace then.

**Comment by DanTup** [comment]
Is there somewhere it can be reported?

**Comment by sandy081** [comment]
@@kesane-msft can you please let @DanTup know where to report marketplace related issues?

**Comment by kesane-msft** [comment]
@DanTup you can reach us at VSMarketplace@microsoft.com to report any Marketplace related issues. Sorry for the delay in the reply, I was out sick. I will also take a look into the issue you have reported.

**Comment by DanTup** [comment]
@kesane-msft great, thanks! Let me know if you need any more info (though I can't easily re-test without publishing real extensions - maybe you have some test environment where you can try it out).
