### ISSUE TITLE
Default value for VSCODE_NLS_CONFIG.locale ?

### ISSUE THREAD

**Issue by shanalikhan** [microsoft/vscode#78392]
1. If the OS is non-english ( e.g Chinese )
2. user choose to install vscode in english- No `locale.json`

What would be the value of `process.env.VSCODE_NLS_CONFIG.locale` ?
If the value is non-english, what would you guys suggest to extension authors to either read from `locale.json` directly.

**Comment by shanalikhan** [comment]
@dbaeumer suggestions...

**Comment by dbaeumer** [comment]
Extension authers should use `vscode-nls` and `vscode-nls-dev` which handles this. An extension should never read the `VSCODE_NLS_CONFIG` by itself since it structure is not API and might change in the future.
