### ISSUE TITLE
change in task.json not reflecting in "select the build task prompt"

### ISSUE THREAD

**Issue by stdLn** [microsoft/vscode#78396]
I tried adding a new task and changing existing task label but build task prompt showing the same old list. I restarted vs code, my laptop, reinstalling vscode and clearing extension. None is working. 
Event tried in a different folders.

**Comment by alexr00** [comment]
Can you share your tasks.json?

**Comment by stdLn** [comment]
Following is my task.json code. Though I added 'dd' at the label, It's not reflecting. 
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "g++.exe dd build active file",
            "command": "C:\\MinGW\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\MinGW\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ]
        }
    ]
}`
See here:
![Screenshot (16)](https://user-images.githubusercontent.com/13703633/62452903-b114e680-b7a3-11e9-9bea-59683b4851a7.png)

I can see those option after deleting my task.json . is there any global task.json ?

**Comment by alexr00** [comment]
You need to have `"group": "build"` in your task. There is no global tasks.json, those tasks come from extensions. I assume that you created your task by using the Configure Task command in the command palette? I will update that command to include the group in the tasks.json.
