### ISSUE TITLE
Implement case preservation in search as well

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78397]
In https://github.com/microsoft/vscode/issues/9798 we implemented some support for preserving the match case while doing a find/replace. We need the same feature in search.

**Comment by skprabhanjan** [comment]
@roblourens , Can I work on this ?

**Comment by roblourens** [comment]
Yes that would be great @skprabhanjan! I want the same button that supports the same "preserve case" logic, but when using search in the side bar. Here is basically what you need to do:

The original PR is here: https://github.com/microsoft/vscode/pull/60311

- Add the same button to the replace input that the find widget got
- Add plumbing for a "preserve case" option that goes along with the "is regex" and "whole word" and other options
- We compute the replace string for search here: https://github.com/microsoft/vscode/blob/ca2eb3be062bb5d6f15788667b523557b9f33dae/src/vs/workbench/contrib/search/common/searchModel.ts#L99 and we need to take the "preserve case" option into consideration here too. So we need to use this same code: https://github.com/microsoft/vscode/blob/ca2eb3be062bb5d6f15788667b523557b9f33dae/src/vs/editor/contrib/find/replacePattern.ts#L55-L64 ideally copying it into a shared file so that find and search will use the same preserve case logic.

Should be relatively straightforward, let me know if that doesn't make sense.

**Comment by deitry** [comment]
Case preservation is a great feature.
Just to be clear: would it work with `editor.action.addSelectionToNextFindMatch` / `addSelectionToPreviousFindMatch`? I use this actions a lot through keybindings and hope this feature will be supported there too.
