### ISSUE TITLE
[html] entities are not highlighted in HTML mode

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#784]
HTML entities/named character references are not highlighted correctly in HTML mode.

![html_entity](https://cloud.githubusercontent.com/assets/2193314/11454769/e87a3074-95ee-11e5-9c83-afc0b38eb77c.png)
- [List of XML and HTML character entity references](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)
- [HTML5 named character references](http://www.w3.org/TR/html5/syntax.html#named-character-references)

**Comment by alexandrudima** [comment]
@aeschli I think for HTML we still use the hand-written tokenizer.

**Comment by Tyriar** [comment]
@alexandrudima [This](https://github.com/Microsoft/vscode/blob/master/src/vs/languages/html/common/html.ts#L98)? Are there plans to move away from that?

**Comment by alexandrudima** [comment]
@Tyriar Yep, that's the current one out of the box for HTML. 

Yes, we want to move all the code in `src/vs/languages` into extensions. HTML is one of the last ones we can move, after we move out CSS and JavaScript into extensions and perhaps consume them again as library code in the HTML one (the reason being intellisense in embedded CSS/JavaScript).

**Comment by Tyriar** [comment]
@alexandrudima Thanks for the clarification, my interest mainly stems from looking into SVG support (https://github.com/Microsoft/vscode/issues/728). It was a little puzzling why language implementations were implementing in two spots. Should this be tracked in an issue? I'd love to help out.

**Comment by aeschli** [comment]
I created #820 for XML

**Comment by aeschli** [comment]
This got fixed in the meantime. The html textmate grammar that we use also highlights entities.
