### ISSUE TITLE
Scroll sluggish on ChromeOS

### ISSUE THREAD

**Issue by ViRb3** [microsoft/vscode#78403]
## Laptop:
* Acer Chromebook 14 (CB3-431)

## Specs:
* Intel Celeron N3160
* 4GB RAM
* Linux 3.18 kernel

## Tested environments:
* [Crostini](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md)
* [Crouton](https://github.com/dnschneid/crouton)
* Replaced ChromeOS with Ubuntu ([GalliumOS](https://galliumos.org/))
* [code-server](https://github.com/cdr/code-server) hosted via Crouton, interface rendered by ChromeOS browser

True, this machine is not powerful. However, running [Theia IDE](https://github.com/theia-ide/theia) hosted on the same machine feels ultra smooth in the same workflow and projects. Is this an issue of GPU acceleration or optimization that VSCode is lacking?

**Comment by joaomoreno** [comment]
ChromeOS is not an officially supported platform.
