### ISSUE TITLE
Yup, I am experiencing the same thing still in version 1.36.1

### ISSUE THREAD

**Issue by ghaith6558** [microsoft/vscode#78409]
Yup, I am experiencing the same thing still in version 1.36.1

_Originally posted by @sts24 in https://github.com/microsoft/vscode-css-languageservice/issues/152#issuecomment-517778554_

**Comment by kanlukasz** [comment]
Please, don't create another the same ticket if already exist.
Instead put thumb up in there or type more information
We need to respect the time of the VSCode programmers team
