### ISSUE TITLE
Settings lose focus while editing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78404]
- Type in an input box setting, like Font Family
- Wait a couple seconds
- Focus is lost

From https://github.com/microsoft/vscode/commit/ce15ecb0d50cab9f0ca6ef443b145a144f428634

**Comment by octref** [comment]
I used the wrong check. `setting-item-list` is parent of `setting-item-content`:

![image](https://user-images.githubusercontent.com/4033249/62397042-90415c80-b529-11e9-9b29-56afd6de9c8b.png)

**Comment by octref** [comment]
Verifier: Verify both this bug and https://github.com/microsoft/vscode/issues/78162 are fixed.
