### ISSUE TITLE
Allow debug adapters prioritize suggestions via breaking alphabetic sorting

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#78408]
Suggestions returned by the debug adapter are currently sorted by label then by type. This prevents debug adapters from suggesting their own completion order. For example, for JavaScript objects, useless `__defineGetter__` suggestions are shown at the very top:

<img width="516" alt="Screen Shot 2019-08-02 at 2 05 04 PM" src="https://user-images.githubusercontent.com/883973/62398785-8bcb7280-b52e-11e9-8f95-713d1d511ebf.png">

Begin able to control the order allows adapters listing properties as they wish, for example by prototype, hence pushing the object's properties to the very bottom.

<img width="195" alt="Screen Shot 2019-08-02 at 1 59 48 PM" src="https://user-images.githubusercontent.com/883973/62398831-b7e6f380-b52e-11e9-9c68-1179f459940a.png">

**Comment by pavelfeldman** [comment]
I experimented with addressing it and the simplest way I found was prepending zero-width space to the suggestions in order to push them lower the stack. VS Code shows these suggestions, but does not quite like applying them out of the box. With a single line change to `isWhitespaceAtPos` that starts treating \u200B as a space makes it happy.

That might sound hacky, but formally it looks Ok and allows not introducing any additional completions settings and/or DAP capabilities. I'm happy to submit a PR if you find the approach reasonable.

**Comment by weinand** [comment]
@isidorn We can take the  "hacky" fix for now, but we should start addressing this in a better way, which might involve extending the DAP.

**Comment by isidorn** [comment]
@pavelfeldman agree with your point that putting the useless properties at the end is the right thing to do.
@weinand as for extending the DAP I think the right apporach would be to go with [`sortText`](https://github.com/Microsoft/vscode/blob/9afa70a7415ea8614ca74b0869fc3a64cfcd477b/src/vs/vscode.d.ts#L3334) which we already expose in `vscode.d.ts`.

As for the hacky solution we can also go down that route, however for changes at [`isWhitespaceAtPos`](https://github.com/Microsoft/vscode/blob/9afa70a7415ea8614ca74b0869fc3a64cfcd477b/src/vs/base/common/filters.ts#L480) we need @jrieken approval since that would change all fuzzy scoring used by the suggest widget.
Thus I would lean towards extending the DAP.

**Comment by weinand** [comment]
Ok, I've created a DAP feature request for adding a "sortText" to the "CompletionItem" type.

**Comment by jrieken** [comment]
>  With a single line change to isWhitespaceAtPos that starts treating \u200B as a space makes it happy.

Generally that's a fair change - the list of whitespace characters in definitely  not complete. Anyways, the proper way to tackle this is @weinand's `sortText` extension.

**Comment by pavelfeldman** [comment]
Any solution works for me. DAP `sourText` extension sounds great. It requires more changes in VS Code itself - it seemed fairly opinionated in how it wanted to alphabetically sort items, but overall sounds like a great addition!

**Comment by weinand** [comment]
@isidorn 
I've added an optional "sortText" attribute to the "CompletionItem" type.
Please implement sorting completion items based on this.

**Comment by isidorn** [comment]
Debug console now supports the `sortText`.
Try it out from Wednesday vscode insiders and let me know how it behaves.

**Comment by weinand** [comment]
I've added sample code for completions to mock-debug and verified that sorting completion items work.

**Comment by isidorn** [comment]
Adding verified label per @weinand comments. And seems to work for Pavel as well.
