### ISSUE TITLE
Go to definition/declaration and Problems window does not work well with symlinks

### ISSUE THREAD

**Issue by dfsbbl** [microsoft/vscode#78415]
Issue Type: <b>Bug</b>

1. Set `workbench.editor.revealIfOpen` to be true.
1. Put some sources files with dependencies (e.g. cpp files with related headers) and problems detectable by VS Code into a symlink folder (or a folder inside a symlink folder).
1. Use VS Code to open the symlink folder.
1. Open a source file and its dependent header files using the Explorer sidebar.
1. Perform "Go to Definition" or "Go to Declaration" to variables or functions in the cpp file or use the reveal file feature in the Problems window.

**Actual results:**
- "Go to Definition" and "Go to Declaration" for names defined inside the cpp file will open the preview of the cpp file again in the active editor group using its absolute path, shown in screenshot 2.
- "Go to Definition" and "Go to Declaration" for names defined in the dependent header files will open the preview of the header file again in the active editor group using its absolute path, shown in screenshot 1.
- The reveal file feature of the Problems window has similar behavior to the previous two.
- (unrelated problem) The cpp file newly opened with absolute path has a different syntax highlighting from the original file opened with symlink path. See screenshot 2 and 3 for comparison.

**Expected results:**
- The `revealIfOpen` option should respect symlink and VS Code should reveal the already opened files instead of open the files again using absolute path.
- The syntax highlighting of sources files should be stable and consistent.

Disabling extensions doesn't solve the problem.

Screenshots:

![screenshot1](https://user-images.githubusercontent.com/34668597/62406102-f802b080-b5d8-11e9-919b-eba3259c62aa.png)

![screenshot2](https://user-images.githubusercontent.com/34668597/62406104-005aeb80-b5d9-11e9-85ef-0cac30778319.png)

![screenshot3](https://user-images.githubusercontent.com/34668597/62406106-051f9f80-b5d9-11e9-893a-c9b80c9216c6.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3456)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (9.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.24.1
rewrap|stk|1.9.1
vim|vsc|1.9.0
explicit-folding|zok|0.3.2

(1 theme extensions excluded)

</details>

**Comment by dfsbbl** [comment]
**Update:** the error squiggling feature doesn't work, either. It seems that problems with symbolic links are general problems of vs code. I've found **two related closed issues** about this problem: #18837 and #59245. It seems that previously vs code will dereference a symbolic link folder when opening it, so these problems do not occur, but now it doesn't dereference symbolic links (which is a good thing to me), and this introduces some new problems.

Screenshots about error squiggling:
![image](https://user-images.githubusercontent.com/34668597/62433384-ccadcc00-b766-11e9-97de-49211e780b87.png)
![image](https://user-images.githubusercontent.com/34668597/62433407-e5b67d00-b766-11e9-9e11-1fe776c50a92.png)

**Comment by dfsbbl** [comment]
(Sorry, I'm new to github, and I do not have a good title to summarize the problem... It would be great if someone can help to give this issue a better title.)

**Comment by sandy081** [comment]
These problems are generated by the corresponding c++ extension. Please file issue against it.
