### ISSUE TITLE
vs code icon is not displayed in the taskbar

### ISSUE THREAD

**Issue by hameesha** [microsoft/vscode#78419]
this was happened when i was uninstalled vs code first time and reinstall it 
after that vs code icon is not displayed in the taskbar and i try to
reinstall vs code for severel times but it didn't work out.help me to fix this
![Screenshot (8)_LI](https://user-images.githubusercontent.com/45784711/62409047-5fc3f600-b5ef-11e9-8ad4-790a7bc66265.jpg)

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?
