### ISSUE TITLE
how to debugg js file without need configure launch.json

### ISSUE THREAD

**Issue by zengyunchun** [microsoft/vscode#78418]
how to debugg js file without need configure launch.json
 
i just want to quick debugger file in node enviroment, but when change file to debugger every time ,i must change launch.json file, it's too tedious, can you help me

**Comment by IllusionMH** [comment]
/question

It is better to ask this question on StackOverflow.

If you want just run `node` command for file you are editing you should use
https://stackoverflow.com/questions/38419779/debugging-current-file-in-vs-code

If your app entry point is different from file you are editing, than you have to specify that file name in `launch.json`

**Comment by isidorn** [comment]
@IllusionMH thanks a lot for answering! Really appreciate it.
