### ISSUE TITLE
change java icon to the java cup icon.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#78421]
Issue Type: <b>Feature Request</b>

change java icon to the java cup icon.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sanket-bhalerao** [comment]
this issue is not caused by any extension.
i checked this by installing fresh vscode stable version and no extension.
![java icon](https://user-images.githubusercontent.com/9264813/62822558-d7bb8e80-bba2-11e9-98fb-b5d9844ece6b.png)

**Comment by joaomoreno** [comment]
That Java icon comes from the Seti file icon theme extension, which we bundle. You are free to install other file icon themes.
