### ISSUE TITLE
Effective way of commenting out one-liners.

### ISSUE THREAD

**Issue by damiantoczek** [microsoft/vscode#78429]
Shortcut: `Ctrl + C + K` and `Ctrl + C + U`
I really hate this way of commenting out my code, yes there is also something like `Alt+LShift+A` but this doesn't feel better.
Before someone starts trash talking, I like VSCode, stable, smooth and really fast. But I really like the `Ctrl+Shift+/` shortcut from AtomEditor.
I can use it on a single line or select multiple lines and then use the same shortcut to uncomment everything again or select one line and uncomment just this one line.

I'm one of those guys who use also a mouse to navigate thru my code, not pro quite yet :p
I would be thankful if this idea could be implemented into VScode or for some tips on how to make better use of VScode and get a better working flow?

**Comment by IllusionMH** [comment]
Not sure what you want to achieve. Do you want to toggle comment state for one line or several?
VS Code has <kbd>Ctrl + /</kbd> to **toggle** single line comment. It also works works when you select multiple lines.

You can check list of common shortcuts in [Keyboard Shortcuts Reference](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference)

In any case you you can use <kbd>F1</kbd> and `>Preferences: Open Keyboard Shortcuts` to configure any shortcuts. Or use <kbd>F1</kbd> and `>Preferences: Keymaps` to install keymap from your favorite editor.
