### ISSUE TITLE
Hyperlinks don't open when System's default browser is Firefox

### ISSUE THREAD

**Issue by navjotjsingh** [microsoft/vscode#78427]
- VSCode Version: 1.36.1
- OS Version: Windows 10 v 1903 (OS Build 18362.239)

(Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362)

Steps to Reproduce:

1. Open any page which has HTML links (Even Welcome Page works)
2. Click on any link (like the Github repository page link on Welcome)
3. It won't open. Doesn't launch Firefox.

I have tried by keeping other browsers as System default - Edge, Chrome, Vivaldi. Links opened in them just fine. Its just when I keep Firefox as my default browser, links refuse to launch.

I have tried the latest Insiders build and it has the same problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Doesn't this seem like a Firefox issue?
