### ISSUE TITLE
regular error

### ISSUE THREAD

**Issue by PlaneV** [microsoft/vscode#78428]
Issue Type: <b>Bug</b>

Hi! I'm using a regular expression to find something from a html files, and it writed in big5, but I can find nothing, the same regular in Notepad++ working fine.
I dont know what the problom is.

----------------------------------
the regular:
`<font FACE=(.+?) LANG=(.+?)>([\s\S]*?)</font>`

----------------------------------
the part of html files:
```
      <p>
          <font FACE="細明體" LANG="ZH-TW">&nbsp;&nbsp;&nbsp;&nbsp;
            </font>
  <font size="3">
    <font LANG="ZH-TW">人的身體分兩大循環系統</font> [1]<font LANG="ZH-TW">血液循環系統</font>
    [2]<font LANG="ZH-TW">水道系統，為何須要此二系統呢？因為有水，再有營養互相配合，這是任何生物賴以為生的必要條件，人類如此，動植物亦如此，舉凡地球上所有生物，包含</font>virus<font
      LANG="ZH-TW">與</font>cancer<font LANG="ZH-TW">，</font>tumor<font LANG="ZH-TW">
      都須要此二者，缺一不可。人體的這二大系統主導著生命的延續，東方醫學是巨視醫學，它看整體，直接面對病人，並聆聽病人的陳述，体內發出的訊息，經由病人口述的感覺，包括肉體上疼痛，精神上的變化等，從而細察出病源所在，直接與病人面對面，這是最直接，最近距離的接觸。西方醫學是微視醫學，它藉由儀器，
    </font>X<font LANG="ZH-TW">
      光片，驗血報告等資料，進而診斷病人，是間接的，較遠距離的，西醫被訓練起來解讀照片及驗血報告，往往忽略病人的感覺與存在，對病人視而不見，因此只能得到片斷的資料，絕大多數的病都不知因何而來。</font>
  </font>
  <font FACE="細明體" LANG="ZH-TW">
    </p>
  </font>

  <p>
    <font size="3">
      <font FACE="細明體" LANG="ZH-TW">&nbsp;&nbsp;&nbsp;&nbsp;
      </font>
      <font LANG="ZH-TW">
        東方醫學認為，一個人水道系統的正常與血液循環系統的正常，則癌症不生，癌並非毒，它的由來，只是体內某一部份堆積了一些陳舊的營養，加上水的協助給予了局部組織，不正確的訊息，誤導了正常生長的過程，形成不正常畸形的發展，這就是腫瘤，癌症之源。它生長在不同的地方，就被賦不同的病名，由於儀器的進步，偵測出它在何處，看起來好像貢獻很多，實際上，不但無助，反而更壞，怎麼說呢？第一︰宣告病人在某部位得到癌症之時，病人早已嚇到，自此惡夢開始，終身難過直到死時，完全失去了生活的品質，也死的更快，因此宣告了又怎麼樣呢？第二︰許多醫生一再提醒大眾及早檢查，可以治好，可以預防，試問如果它們是對的，為何有一大堆人死於癌症呢？第三︰西醫給病人的治療，如開刀、化療等，即使正常人都會死亡，更何況病人呢？肯定死的更快。
      </font>
    </font>
  </p>
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-zh|ada|3.8.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-language-pack-zh-hans|MS-|1.37.3
python|ms-|2019.6.24221
cpptools|ms-|0.24.1

</details>

**Comment by roblourens** [comment]
Have you set the `files.encoding` setting?

**Comment by PlaneV** [comment]
it's set to utf8

**Comment by roblourens** [comment]
We can only search one encoding at a time, so you will have to set it for "big5" to search those files
