### ISSUE TITLE
Add an option to enable whether to override the vscode shortcut when the focus is on the terminal

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#78423]
Issue Type: <b>Feature Request</b>

Add an option to enable whether to override the vscode shortcut when the focus is on the terminal.

When I enter a command on the terminal, if I want to execute some shortcut commands, what I want is not to enter characters on the terminal.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
Check out the `terminal.integrated.commandsToSkipShell` setting
