### ISSUE TITLE
[Bot] Support helping bot with assigning

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#78432]
Example:

```
/assign Tyriar
```

**Comment by roblourens** [comment]
Does this work for me?

/assign roblourens

**Comment by roblourens** [comment]
Does it need /unassign? 🤔

**Comment by JacksonKearl** [comment]
> Does it need /unassign? 🤔

Probably helpful, especially as bot will soon be auto-assigning people.

**Comment by JacksonKearl** [comment]
#96600
