### ISSUE TITLE
Scrolling editor with a bunch of emoji is extremely slow

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78434]
Maybe you know this already but I can't find an issue

- Open this file from a Google CTF: [emoji.txt](https://github.com/microsoft/vscode/files/3464139/emoji.txt)
- Scrolling in vscode is extremely laggy
- Profile: 
[Profile-20190803T103727.json.txt](https://github.com/microsoft/vscode/files/3464141/Profile-20190803T103727.json.txt)

**Comment by rebornix** [comment]
@roblourens it seems you have quite a few decorations to render in the viewport, may I know what are they?

**Comment by rebornix** [comment]
The perf log I have 

![image](https://user-images.githubusercontent.com/876920/62485184-ddfbd600-b770-11e9-888b-ea2fe9154427.png)


The one posted by you

![image](https://user-images.githubusercontent.com/876920/62485199-ee13b580-b770-11e9-91d5-74a7c8fee4a4.png)

**Comment by roblourens** [comment]
No extensions here except gitlens?

**Comment by roblourens** [comment]
Extensions disabled (this does not say anything about decorations though)

![image](https://user-images.githubusercontent.com/323878/62485646-1f40b580-b772-11e9-8877-9f21a160019b.png)

**Comment by roblourens** [comment]
I think the problem is with these number emojis: 9️⃣ 8️⃣ 4️⃣ 2️⃣ 6️⃣ 

Also I have to press the arrow keys multiple times to get over them, where the others work as expected.

**Comment by rebornix** [comment]
@roblourens may I know the font family you are using in the editor? The font used in the editor contributes a lot to the rendering lag.

**Comment by roblourens** [comment]
Default

**Comment by bpasero** [comment]
@roblourens 
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by roblourens** [comment]
Oh this is completely perfect in the explroation build! I should have tried that already 😅 thanks!
