### ISSUE TITLE
"Find All References" does NOT find all references

### ISSUE THREAD

**Issue by SHxKM** [microsoft/vscode#78433]
It's actually quite dangerous to rely on "Find All References" when refactoring code since it doesn't really return all references. I think this feature should be turned off until it's fixed because it's currently straight up misleading.

- **VSCode Version:** 1.36.1
- **OS Version:** macOS 10.14.5

**Steps to Reproduce:**

1. ctrl-click a (python) function, say `perform_job()` to open the contextual menu
2. Hit "Find All References"
3. You will get X results
4. Now run a separate query "Search in Files" query for `perform_job`
5. You will often get more results

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by SHxKM** [comment]
An extension..?

**Comment by gjsjohnmurray** [comment]
The built-in Python Language Basics (vscode.python)

See https://github.com/microsoft/vscode/issues/71773#issuecomment-480246825
