### ISSUE TITLE
[Terminal] Support Fast Scrolling

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#78431]
Issue Type: <b>Feature Request</b>

Editor supports increased scrolling speed while holding <kbd>Alt</kbd> key. It allows to scroll 1000 lines in 2 mouse wheel turns. 
```json
"editor.fastScrollSensitivity": 5,
```

It works in `Editor` and all `Tree`s. Is it possible to have it working for terminal?

**Comment by Tyriar** [comment]
@joaomoreno @bpasero @alexandrudima should this setting be under the `workbench` namespace instead of `editor`?

**Comment by raufabr** [comment]
I would like to have a go at this. Is that ok?

**Comment by joaomoreno** [comment]
I didn't even know about this feature before. This should definitely be a workbench thing, since it's read by the `ScrollableElement`. cc @alexandrudima

**Comment by alexandrudima** [comment]
I think `editor.fastScrollSensitivity` only works in the editor. It is there to be right next to its older buddy `editor.mouseWheelScrollSensitivity`. We can rename them, but we need a migration story for those that are already using them + an adoption story for all areas in our workbench (like trees & terminals)

**Comment by Tyriar** [comment]
@raufabr most of the work for the terminal is in the upstream project, which someone else might already be working on https://github.com/xtermjs/xterm.js/issues/2363. If it's still available in a week you can probably give it a shot though.

**Comment by Tyriar** [comment]
At one point @bpasero set up a deprecation component for settings that would show warnings but I think it got removed. It would be good to have something that allows aliasing settings that work as if the other setting is present but shows a warning about the new key.

**Comment by Tyriar** [comment]
Moved the namespace moving discussion over to https://github.com/microsoft/vscode/issues/78626, I'll go ahead and accept PRs for this and just use the editor setting if it's not done by then.
