### ISSUE TITLE
Immersive Mode

### ISSUE THREAD

**Issue by qtisan** [microsoft/vscode#78430]
Issue Type: <b>Feature Request</b>

I am eager for a Immersive Mode, that it can expand window to fullscreen, and then when I am typing on Mac OS, with the Immersive Mode, it will move vscode to a new desktop fullfill with code what immersed me.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by antoniogamiz** [comment]
Have you seen Zen Mode?

**Comment by qtisan** [comment]
@antoniogamiz thanks dude, i get it.
