### ISSUE TITLE
Overlay Comments

### ISSUE THREAD

**Issue by mukeshbadgujar** [microsoft/vscode#78435]
Can you add here a special comment section , because while creating comment in different languages it is hard , so for all languages you have to put a overlay comment opetion that have to write comment  for eg. as i write comment in htlm,css etc it is hard.

means : in s/w just like adobe premier pro the video overlay option. same as in coding at the time of different languages we have to keep in mind for every language comment syntax, the HTML syntax is really very hart to type a comment so "simply use //" as a comment as overlay in html code , i think it imagination i cant write it perfectly but try to understand it......... for more indormation call me >> Mukesh Badgujar : 9156563098

**Comment by IllusionMH** [comment]
Could you please show any mock up of your idea so it will be clear for developers what you want to achieve?
