### ISSUE TITLE
Java Hightlight doesn't work when there are many Expections to catch

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#78445]
Issue Type: <b>Bug</b>

```java
try {
            constructor = c.getConstructor(int.class, int.class);
            Object newInstance = constructor.newInstance(3, 4);
            Method method = c.getMethod("add", int.class, int.class);
            Object result = method.invoke(newInstance, 2, 6);
            System.out.println(result);
        } catch (NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException
                | IllegalArgumentException | InvocationTargetException e) {
            e.printStackTrace();
        }
```

the expections in `catch`'s parens isn't highlighted except last one.

i don't know whether the bug is caused by VSCode or the Java Language Extension.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|3.0.3
bracket-pair-colorizer|Coe|1.0.61
vscode-clock|Com|0.0.1
gitlens|eam|9.9.2
vscode-great-icons|emm|2.1.47
todo-tree|Gru|0.0.139
beautify|Hoo|1.5.0
calculator|lix|0.1.1
python|ms-|2019.6.24221
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
cpptools|ms-|0.24.1
sqltools|mtx|0.19.7
material-icon-theme|PKi|3.8.1
java|red|0.47.0
vscode-xml|red|0.8.0
LiveServer|rit|5.6.1
vscode-markdown-paste-image|tel|0.12.0
linenote|tkr|1.2.1
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by JoeyRxy** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

@joaomoreno 
When I uninstall all `Java` extensions,there're still problems!How could the extensions cause this problem?

**Comment by alexr00** [comment]
Moved to owning repo https://github.com/atom/language-java/issues/205
