### ISSUE TITLE
Don't show "Do you want to upload ...." and "overwrite" messages

### ISSUE THREAD

**Issue by isnaasharimam** [microsoft/vscode#78448]
Issue Type: <b>Feature Request</b>

KWrite for linux has feature that when I open file from remote server by KWrite and edit it, then press save, it saves the file on remote server without showing prompt for "Do you want to upload" and "File already exists on server, overwrite". This is very good features and speeds up coding.

I request this feature for visual studio code.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-22-generic

**Comment by IllusionMH** [comment]
Are you using extensions for this or how do you upload files remotely?

If you use extension - it most likely that this request should be in extension repo.

**Comment by isnaasharimam** [comment]
No, KWrtie do this as default without extension. I want to this feature be as core feature of visual studio code. I cannot trust extensions.

**Comment by IllusionMH** [comment]
Could you provide more details about that you take to get that prompt for "Do you want to upload" and screenshot? I haven't found this string in this repo code, so it looks like this isn't from VS Code itself.

Also VS Code core is kept slim, so some specific functionality that not necessary for all cases should be added with extensions.

Also you you are working with remote hosts you should check family of Remote extensions. See [VS Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) for details.

**Comment by isnaasharimam** [comment]
[https://pasteboard.co/IryiRUv.png](url) See this picture please. I guess this is functionality of "Linux kde neon" but the KWrite uses some arguments when saving files that bypass this stages.
I can't trust extensions and further more in the extensions we should put server credentials.

**Comment by bpasero** [comment]
Since this dialog does not seem to originate from VSCode, I do not see how to prevent it.

**Comment by isnaasharimam** [comment]
I think the method of saving file, cause the dialogs. 
See how the KWrite saves file and do like it. It's big feature, and speeds up coding.
