### ISSUE TITLE
Find and replace in file and folder names

### ISSUE THREAD

**Issue by thomas-darling** [microsoft/vscode#78449]
I'd love to see a feature, that let me **search and replace in file and folder _names_** - not their content, but the names themselves.

I often find myself copying existing files or folders, renaming them, and then making some modifications - essentially using something I already have as a template for something new.
If that something is a folder, it can be quite tedious to rename all the files - being able to just search and replace in the names would be a huge time saver.

There's of course a little bit of complexity to this, as it could result in duplicate file names. However, if such a situation is detected, it could be easily handled - a couple of suggestions:

1. Block the whole rename operation, and let me know it's because names would collide - ideally with a list of the files for which collisions would occur, and an option to continue by handling those according to 2. This would be ideal, as it means I'd know about any collisions.

2. Append incremental postfixes, similar to what happens when a file is copied - this is simple, but also a bit more risky, as I might not realize that collisions occurred.

**Comment by roblourens** [comment]
Might be a good feature for an extension
