### ISSUE TITLE
When refreshing/ opening window of workspace workbench.colorCustomizations setting is gone

### ISSUE THREAD

**Issue by YamenSharaf** [microsoft/vscode#78444]
Issue Type: <b>Bug</b>

1. Have a workspace consisting of two projects
2. Have `workbench.colorCustomizations` present in your workspace settings config file
3. Reload VSCode window

Expected: Workspace settings retain its color configurations.

Actual: Color configurations are gone from the JSON file and no longer applied

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (4.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
jest-snippets|and|1.7.0
react-pure-to-class-vscode|ang|1.1.8
vue-jsdoc|bej|0.0.2
vscode-tailwindcss|bra|0.2.0
turbo-console-log|Cha|1.2.26
npm-intellisense|chr|1.3.0
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
vscode-quick-select|dba|0.2.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|9.9.2
vscode-element-helper|Ele|0.5.6
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
terminal|for|0.0.10
vscode-pull-request-github|Git|0.9.2
vscode-peacock|joh|3.0.1
vscode-styled-components|jpo|0.0.26
chat|kar|0.16.0
graphql-for-vscode|kum|1.15.0
vscode-wrap-console-log|mid|1.7.2
vsliveshare|ms-|1.0.614
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.2
debugger-for-chrome|msj|4.11.7
vetur|oct|0.21.1
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.7.1
code-settings-sync|Sha|3.4.1
addDocComments|ste|0.0.8
code-spell-checker|str|1.7.17
vscode-npm-scripts|tra|0.2.1
es-quotes|vil|0.2.6
highlight-matching-tag|vin|0.9.3
vuetify-vscode|vue|0.2.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

(8 theme extensions excluded)

</details>

**Comment by YamenSharaf** [comment]
So I figured out this is not happening because of a refresh. The settings file for the workspace has this setting `workbench.colorCustomizations`  removed on every start of VSCode.

**Comment by MFueg** [comment]
Same here

**Comment by sandy081** [comment]
Can you try to reproduce this by disabling all extensions?

**Comment by MFueg** [comment]
I investigated a little more.
In my case it was the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock&wt.mc_id=vscodepeacock-github-jopapa)-Extension.

See [this issue](https://github.com/johnpapa/vscode-peacock/issues/262).
It is already closed - I had to update my user settings.
