### ISSUE TITLE
What about folding the comments 

### ISSUE THREAD

**Issue by cangyin** [microsoft/vscode#78451]
Issue Type: <b>Feature Request</b>

For many times when I read code from others, there is commented code scattering everywhere, which is deprecated due to code rewrites or may be other reasons.  Would there be the feature in VsCode that folds up the commented blocks?

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-23-generic

**Comment by gjsjohnmurray** [comment]
@cangyin Have you tried the `Fold All Block Comments` command?

![image](https://user-images.githubusercontent.com/6726799/62448377-9456bf80-b75f-11e9-8fdb-1d9b9fea58d4.png)

Result:
![image](https://user-images.githubusercontent.com/6726799/62448435-b81a0580-b75f-11e9-872e-7e24515f95a7.png)

And if you'd like a context menu item to trigger this from, try this little extension I created:

[The Folding Stuff](https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff)

**Comment by aeschli** [comment]
@cangyin See the comment above. Is that good enough for your use case?
