### ISSUE TITLE
VSCode prompting for git  Credentials (macOS)

### ISSUE THREAD

**Issue by qcha0s** [microsoft/vscode#78454]
This just started happening yesterday. - Somewhere between GitHub and VSCode, VSCode has decided to request login credentials repeatedly. (VERY ANNOYING). 

This is happening on multiple systems and for multiple accounts. I'm not the only one on my team experiencing this issue. 

I don't know what you changed in GitHub or VSCode, but please change it back 

- VSCode Version: 1.36.1 
- OS Version: 10.14.6

Steps to Reproduce:

1. Clone repo 
2. Make changes and commit / push in VSCode 

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by IllusionMH** [comment]
Does it happen when you perform actions with Git (pull/push) or just appear "randomly"?
Do you have `"git.autofetch": true` in your Workspace (especially if you have shared `.vscode` folder for project) or User settings?

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the prompt?

**Comment by qcha0s** [comment]
It's corrected itself again (I haven't had to re-enter a login since posting this)
