### ISSUE TITLE
Inconsistent search results in settings editor

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#78455]
Searching for a setting ID will sometimes produce a single result, and other times multiple results. The issue appears to be that **search results while editing the search input are different from search results that come from fresh/cleared input**.

This issue is a bit trivial, since the results still yield the target settings. It's just that they aren't consistent results. The only reason why I noticed this myself is that I'm creating a VSCode course and I wanted to mention that exact matches could be achieved by searching for a setting ID. But then I noticed that this wasn't always the case.

**Steps to Reproduce:**

1. Open the settings UI editor.
2. Search for "editor fontSize" (noting the _multiple_ results).
3. Back track with cursor (but do NOT delete).
4. Add the dot, changing input to "editor.fontSize" (noting the _multiple_ results).
5. Clear input with escape key.
6. Search for "editor.fontSize" (note the _single_ result).

**Environment:**

- VSCode Version: 1.37.0-insider
- OS Version: macOS 10.14.4
- Occurs when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Oh this is an interesting bug, thanks
