### ISSUE TITLE
VSCode seems not setup file type associations to `.ts` files correctly. Explorer still think they are MPEG-TS video

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode#78459]
- VSCode Version: 1.36
- OS Version: Windows 10, Build 18362.267

Steps to Reproduce:

1. Install VSCode
2. Make sure enabled file type association
3. Open any folder containing many TS files in Explorer

Does this issue occur when all extensions are disabled?: Yes

Expected Results:

Explorer should not treat these TS files as MPEG-TS video.

Actual Results:

Explorer still think they are videos.
![image](https://user-images.githubusercontent.com/240091/62430115-a4718f00-b6cc-11e9-9cec-37a93c16ff90.png)

**Comment by joaomoreno** [comment]
This is because your system settings are giving preference to MPEG-TS. Just right click and change the file association for all .ts files.
