### ISSUE TITLE
Terminal Keeps Scrambling Up.

### ISSUE THREAD

**Issue by Emyboy** [microsoft/vscode#78458]
I'm working on a node backend project, and few minutes after running my server, the terminal stops reloading my server each time i make a change,  then when i try stopping the server with CTRL + C, the terminal dies.

**Comment by Tyriar** [comment]
@Emyboy can you define what terminal stops and terminal dies means? Screenshots might be helpful.

**Comment by nearwood** [comment]
I have a similar if not the same issue. After running either git bash or power shell (possibly others) for a while, the text disappears:

![vscode-garbled-terminal](https://user-images.githubusercontent.com/1929778/62959053-863b1b80-bdbd-11e9-847c-7e431a045e9f.png)

Text is still there it's just either the wrong color or not rendering correctly. The processes remaining running and I can blindly type in new commands. On the right side of that split terminal is running `git status` after it goes blank. Some of the text appears.

**Comment by Emyboy** [comment]
> I have a similar if not the same issue. After running either git bash or power shell (possibly others) for a while, the text disappears:
> 
> ![vscode-garbled-terminal](https://user-images.githubusercontent.com/1929778/62959053-863b1b80-bdbd-11e9-847c-7e431a045e9f.png)
> 
> Text is still there it's just either the wrong color or not rendering correctly. The processes remaining running and I can blindly type in new commands. On the right side of that split terminal is running `git status` after it goes blank. Some of the text appears.

This is exactly what I was talking about.

**Comment by Emyboy** [comment]
sorry for the late reply.

**Comment by nearwood** [comment]
The processes I spawned from the terminal still work, though. Or, I can wipe these and create a new terminal and that resets it.

**Comment by Tyriar** [comment]
/duplicate https://github.com/Microsoft/vscode/issues/69665

See https://github.com/Microsoft/vscode/issues/69665#issuecomment-519194905 for workarounds
