### ISSUE TITLE
Language-specific setting results in settings editor search

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#78457]
**Expected Behavior**

`wordWrap`, `[markdown]`, and `[]` should produce language-specific results in the UI editor. In other words, the `[markdown]` setting ID should appear, with the "Edit in settings.json" link.

**Actual Behavior**

Searching for language-specific settings is inconsistent.

In Insiders, it looks like the only way to get language-specific settings to appear in the settings UI editor is to search for a specific setting that is included for that language (e.g. search for `wordWrap` and `[markdown]` shows up). You can't search for `[markdown]` in the UI editor for example. But you _can_ in the JSON editor (with split mode enabled).

In Stable, the results are similar, with one notable exception: you can _also_ search for `[]` in the JSON editor (with split mode enabled) to get all language-specific settings to appear.

**Steps to Reproduce:**

1. Open the settings UI editor
2. Search for `[markdown]` (note that there aren't any results)
3. Open the settings JSON editor (with split mode enabled)
4. Search for `[markdown]` (note the target result appears)

**Environment:**

VSCode Version: 1.37.0-insider
OS Version: macOS 10.14.4
Occurs when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Yes this is not really supported in the GUI, got https://github.com/microsoft/vscode/issues/58995 and https://github.com/microsoft/vscode/issues/74195 for this
