### ISSUE TITLE
Support NODE_OPTIONS detection for node debugger auto attach

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/vscode#78460]
I'm not currently sure of the mechanism used to detect node processes but I have found auto attach does not work with `NODE_OPTIONS="--inspect-brk" ` rather than `node --inspect-brk`.

I would like to request adding this as it's helpful for when running scripts through intermediate scripts (e.g. `package.json` scripts or shell scripts).

There does seem to be a way to read the environment variables of a process for all platforms so this should be viable:
- [Windows](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.startinfo?view=netframework-4.8)
- [MacOS](https://apple.stackexchange.com/questions/140327/how-can-i-inspect-the-environment-variables-of-a-running-process)
- [Linux](https://serverfault.com/questions/66363/environment-variables-of-a-running-process-on-unix)

**Comment by weinand** [comment]
Yes, it is possible to read the "NODE_OPTIONS" environment variable, but it is impossible to know which of the running node.js processes are actually seeing (and obeying) the environment variable.

VS Code's auto attach feature scans running node.js process for their command line arguments in order to find the ones that are in debugging mode.

If node.js processes don't have a "--inspect-brk" command line argument (because they are using the env variable), VS Code cannot find node.js processes in debug mode.

Supporting NODE_OPTIONS for auto attach would require a completely different approach for finding node.js processes in debug mode.

**Comment by Jamesernator** [comment]
How do you find node processes? Can't you just do something akin to:

```js
function getEnvNodeOptions(processId: number): string | undefined {
  // Use platform specific mechanism
}

for (const { processId, commandString } of findNodeProcesses()) {
  const envOptions = parseArguments(getEnvNodeOptions(processId));
  if (parseArguments(commandString)['--inspect-brk'] // Presumably this is what's done already
  || envOptions['inspect-brk']) {
    // Add node process to list of processes
  }
}
```

**Comment by weinand** [comment]
@Jamesernator your code nicely shows the problem: as soon as there is a "NODE_OPTIONS='inspect-brk'" set as an environment variable, **all** node processes are added to the list of processes, independent from whether they are actually using the env var or not. This will make VS Code try to connect to every node process (even the ones used by VS Code internally), which will fail eventually.

**Comment by Jamesernator** [comment]
I don't know if Windows has a different definition of environment variable but in Unix systems environment variables are process scoped to the process and won't affect other ones.

e.g. `NODE_OPTIONS="--inspect-brk" node` will only set `NODE_OPTIONS` for that specific process it doesn't propagate to all processes on the system.

As an example you might use `NODE_OPTIONS="--inspect-brk=0" yarn some-package-script` to run the debugger on something in `package.json`'s scripts field.

But this still only applies `--inspect-brk` to Node processes started by `yarn` not to every process on the machine.

**Comment by weinand** [comment]
@Jamesernator on all OSes environment variables are inherited from parent to child processes. If you set a env var in a shell, all (direct and indirect) processes started from that shell will inherited the env variable.

**Comment by Jamesernator** [comment]
No `getEnvNodeOptions()` does not care about env variables in the current process.

e.g. Consider this CLI interaction:

```bash
$ code .
$ NODE_OPTIONS="--inspect" node
```

VSCode does not have `NODE_OPTIONS` passed to it, only the `node` process in the second line does.

`getEnvNodeOptions()` does not care whatsoever about the current process's env variables, it uses OS mechanisms such as `/proc/` on Linux or `ps` on `mac` to read env variables of arbitrary processes.

For example run this in in a linux shell:

```
FOO=bar node -e 'setTimeout(() => {}, 2**31 /* Keep process alive */)'
```

From another unrelated shell that does not have `FOO=` set, just do `cat /proc/<PID>/environ` where `<PID>` is the process id of the above process.

You will find `cat /proc/<PID>/environ` has a line for `FOO=bar` even though the current shell has no reference to that env variable.

A similar solution for Mac and Windows are listed in my original comment.

**Comment by weinand** [comment]
BTW, in your example
```
NODE_OPTIONS="--inspect-brk" yarn some-package-script
```
you are in fact passing the env var only to the "yarn" program, so after that has run, the env var is not know to the shell or any other program started from it.

But this approach has the opposite problem: VS Code has no way to access the env var because it is not in control when the shell passes the env var to yarn. So there is no way to implement the "getEnvNodeOptions" from your pseudo code above.

**Comment by weinand** [comment]
Reading env variables from a non child process is only possible on linux, which has the /proc filessystem. It is not possible on macOS and Windows.

**Comment by weinand** [comment]
Please feel free to submit a PR with your suggested fix. You can find the auto attach code here: https://github.com/microsoft/vscode-node-debug/blob/master/src/node/extension/autoAttach.ts

**Comment by Jamesernator** [comment]
MacOS works (as linked) via `ps -E` which lists the initial environment variables a process started with (which is sufficient for this use case).

Looks like the windows solution linked does not actually get all environment variables just some global ones. I'll investigate getting this solution: https://stackoverflow.com/a/1203011/4295105 into a Node C++ plugin in the weekend.

**Comment by Jamesernator** [comment]
I'm going to open a ticket on node in the meantime to see if we can get `node` to set the process title when using `--inspect-brk` so that it is discoverable.

**Comment by weinand** [comment]
Please try to avoid native node modules since they are a major pain to maintain for all platforms and versions of electron/node.

**Comment by weinand** [comment]
BTW, "--inspect-brk=0" will not work either, because we are not currently scraping the output of node.js for finding the random debug port. VS Code node debug only supports "--inspect-brk" (and assumes a well known port") or an explicit port , e.g. "--inspect-brk=12345".

**Comment by Jamesernator** [comment]
The issue I created on Node would allow `--inspect-brk=0` by allowing setting the process title to whatever e.g. `node --inspect-title="node vscode-inspect:%port% --inspect-brk=0`.

In fact this could even work now if you set the port ahead of time e.g. `DEBUG_PORT=9292 node --title="node vscode-inspect:$DEBUG_PORT" --inspect-brk="$DEBUG_PORT"`. It would not be hard to create a PR to detect that.
