### ISSUE TITLE
cannot copy/paste text in table

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode#78467]
I am using vscode running on my windows system. After I run my sql code and I will get a table. Previously it works well(a couple of weeks before). However, when I copy it and try to paste on notepad today, I end up with nothing. Could you help? Thanks

**Comment by gjsjohnmurray** [comment]
Where are you running your SQL code? In a Terminal panel in VSCode?

@zesluo Maybe add a screenshot to this issue. On Windows it's easy enough to run Snipping Tool, grab a region of your screen, copy to clipboard, then paste it directly into the GitHub input field when you add a comment.

Also worth giving us your version info. Help\About will copy this to your clipboard.

If you're using an extension to run your SQL code, tell us which extension.

**Comment by zesluo** [comment]
Thanks for your reply! The version of VScode is 1.36.1. I 'm using spark & Hive tools . When I use ctrl+c, ctrl+v, I get nothing on the notepad. However, if I right click and use "copy" command, it can work

![image](https://user-images.githubusercontent.com/46309533/62452636-3055ea80-b7a3-11e9-81cf-0aebe79edf42.png)

**Comment by joaomoreno** [comment]
Not sure if this is supported today @mjbvz
