### ISSUE TITLE
Markdown Preview scroll remains same after clicking on some other link

### ISSUE THREAD

**Issue by ankitpriyarup** [microsoft/vscode#78465]
Issue Video:
https://youtu.be/PtYy8V2AUhs

- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:
1. Create a long markdown file (such that you have to scroll to bottom) in the bottom add a link to some other markdown file.
2. Now simply preview your first md file and click on the link. The scroll bar position remains the same, I tried using [Link] (othermarkdown.md) as well as [Link] (othermarkdown.md#) but it didn't worked. Infact for some reason if I use #some-valid-heading as link it works but it doesn't work for headers in other files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hypercubestart** [comment]
@mjbvz  I am interested in fixing this issue. What would be the expected behavior of the scroll bar position be?

**Comment by ankitpriyarup** [comment]
#79416 Should solve this. Thanks!

**Comment by txava** [comment]
This https://github.com/microsoft/vscode/pull/79450 fixes the problem and respects the section/fragment of the link by scrolling to it if available.
