### ISSUE TITLE
Cursor slip random when select a string via mouse 

### ISSUE THREAD

**Issue by dove-young** [microsoft/vscode#78463]
- VSCode Version:   1.36.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. For example, I got a function call in my code.
```
some_func_call(Cursor slip random when select a string via mouse)
```
2. I select the string `slip random when` by mouse, and I want to paste a string `not slip any more while`  then the cursor might slip and I will get a result like 
```
some_func_call(Cursor snot slip any more while select a string via mouse)
```
or 
```
some_func_call(Cursor not slip any more whilen select a string via mouse)
```

Notice the redundant `s` or redundant `n` in these examples. That's very bad because it cause program crash and very hard to notice. 

Actually I do select strings very very carefully because of this problem, but I still keep slip into this problem when coding in VSCode. 

Does this issue occur when all extensions are disabled?: Yes

Here is my screen shots.

You can find the 1st and 2nd selection go well but in the 3rd selection, the cursor slips and the letter `l` slips from selection. 

And if you check the screen shot carefully you can find that I finish each selection very carefully. Otherwise it would be something like the 2nd selection, it slips and included the suffix `.` 

![VSCode-cursor-select-1](https://user-images.githubusercontent.com/606882/62436142-4cd92f00-b771-11e9-9e6a-706574105514.gif)

**Comment by dove-young** [comment]
It seems like the mouse drag/move action tends to be too sensitive. 

Issue https://github.com/microsoft/vscode/issues/78464 seems like to be cause by similar reason. mouse drag/move action tends to be too sensitive.

**Comment by alexandrudima** [comment]
@dove-young The editor works by taking the position which is closest. So if you click in the first half of a character, the cursor will go to the left of the character, and if you click in the second half of a character, the cursor will go to the right of the character.

![Kapture 2019-08-05 at 11 08 34](https://user-images.githubusercontent.com/5047891/62452900-64181c80-b771-11e9-89ae-b9d1d33603cb.gif)

Is this unexpected?

**Comment by dove-young** [comment]
@alexandrudima you know the problem is it makes the behavior not predictable. 

Unpredictable is dangers in programming.  1st, it leads to errors, as what I demonstrated above. 2nd and the even worse side is unpredictable behavior would lead to errors that you don't mean, and you don't have any sense that it would be a typo which made this error.  Many dynamic programming language do not have capacity to indicate error source like this.

**Comment by alexandrudima** [comment]
@dove-young 

I think this behavior is predictable and aligned with other software.

### Edge Dev (based on Chromium):
![78463](https://user-images.githubusercontent.com/5047891/63347625-c4a17f00-c357-11e9-98c7-d1005ef80267.gif)

### Firefox
![78463-2](https://user-images.githubusercontent.com/5047891/63347640-d08d4100-c357-11e9-8e75-fd69c66c280d.gif)

### Microsoft Word
![78463-3](https://user-images.githubusercontent.com/5047891/63347674-e6026b00-c357-11e9-94d1-fbfbcf7f5aef.gif)

We are trying to be consistent with other software and not thus predictable.
