### ISSUE TITLE
Grid: store state using onWillSaveState event

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78479]
I noticed that in `layout.ts` we are using `lifecycleService.onBeforeShutdown` to save state into the storage service. This is not the right event though, rather use `storageService.onWillSaveState`. This event might fire more often than just on shutdown and thus allows to preserve state even in situations such as crashes (or for the web - where we cannot have long running operations on shutdown). 

Even better would be to save state in the grid as soon as it changes, but I am not sure how expensive that is.

//cc @joaomoreno

**Comment by bpasero** [comment]
@sbatten Joao just informed me that we will probably go back to the state we already have (e.g. sidebar location and size) and put that into the grid when creating it. As such my understanding is that we will not need to store the serialized grid in the future and can probably remove that code.

**Comment by bpasero** [comment]
I went ahead and pushed https://github.com/microsoft/vscode/commit/da3b599b789697b3813f36fac8f3ec55510f86e2 because the way this was working it was also causing to show a confirmation dialog each time in the web you want to close the tab because a promise was returned which we do not support in the web.

**Comment by sbatten** [comment]
we will still need to store some things that need to be pulled from the grid state like sizing and restore sizing, so thanks for the change

**Comment by bpasero** [comment]
Ok, feel free to close then, since I pushed.
