### ISSUE TITLE
Allow custom object types in JSDoc

### ISSUE THREAD

**Issue by GRIM2D** [Microsoft/vscode#7847]
I'm using "vanilla" javascript for development. If I write custom object type in JSDoc, it appears as `any` or `void` . It will be more helpful, if one can type custom types.

- VSCode Version: 1.1.1 (1.1.1)
- OS Version: OSX (10.11.4)

Steps to Reproduce:

1. 
```javascript
/**
 * @param document {Object}
 * @returns {Object}
 */
function addDocument(document) {
	
}
```
![screen shot 2016-06-18 at 3 07 53 pm](https://cloud.githubusercontent.com/assets/6705445/16170266/b3f9bf6e-3566-11e6-9661-3868cf13210d.png)

2. 
```javascript
/**
 * @param document {ProductProjection}
 * @returns {ObjectId}
 */
function addDocument(document) {
	
}
```
![screen shot 2016-06-18 at 3 07 15 pm](https://cloud.githubusercontent.com/assets/6705445/16170276/d1ce4d16-3566-11e6-9d6e-2d9ca559aa68.png)

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9276
