### ISSUE TITLE
Add  "format as" command for files without proper file extension

### ISSUE THREAD

**Issue by YisraelV** [microsoft/vscode#78473]
I often open json files which don't have json extension. I would like to be able to use the "format document" command even though the file doesn't have an extension.

**Implementaion**: I suggest that the "format as" command opens a quickpick which allows to specify the file extension.

 **Use case 1**: editing file that doesn't have the proper extension. For example: Chrome saves some settings in "local data" file, which is a valid json but doesn't have json extension.

**Use case 2**: formatting data without saving it on disk. Often I want to paste json data, edit it, and then copy it again. I don't want to have to create a file for it. I would like to just click "new file", in my current work space, paste the text, edit, copy, and close the file without saving. 

I'm willing to try a pull request if this feature is approved.

**Comment by jrieken** [comment]
You can run `F1 > Change Language Mode > JSON` which will make code interpret that file as JSON, supporting not just formatting but also validation, outline, etc etc. That's the order in which things must happen because we don't know upfront if there is a formatter for that language available.

**Comment by jrieken** [comment]
Forwarding to @bpasero to consider allowing `files.associations` work on more than just file endings

**Comment by YisraelV** [comment]
@jrieken that's sufficient for me. Thank you.
