### ISSUE TITLE
Highlight 'active' terminal

### ISSUE THREAD

**Issue by iainmstott** [microsoft/vscode#78488]
Split terminal is amazing, perfect for me (and others) working simultaneously on different data sets.

I program in R and with Ctrl + Enter I'm able to send code to the 'active' terminal (the last one clicked on). It's not possible at the moment to see which one that is, so without being careful you can run code in the wrong one. 

It would be cool to be able to highlight which terminal is 'active, e.g. with a discreet box around it.

**Comment by Tyriar** [comment]
This might have to wait for https://github.com/microsoft/vscode/issues/10546 to be able to differentiate them, I don't think we should differentiate the look much from the editor and tabs would let us show the active one when not focused.

**Comment by Tyriar** [comment]
This sort of thing would only come after the editor gets the same feature.
