### ISSUE TITLE
Grid: sashes lost in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78481]
Noticed while verifying https://github.com/microsoft/vscode/issues/67210

Steps:
* make sidebar as large as possible
* open a couple of editors side by side

=> :bug: I see now cursor over the borders of the editors where the sashes are and thus cannot resize anything. 

I would expect that I can still make an editor larger even in this state.

![image](https://user-images.githubusercontent.com/900690/62451829-477ae500-b76f-11e9-9619-0f84d467bf09.png)

**Comment by joaomoreno** [comment]
Fooled me there! They are separate grids. ;)

**Comment by bpasero** [comment]
:tropical_drink:
