### ISSUE TITLE
Mark file or folder with color

### ISSUE THREAD

**Issue by Leopold5** [microsoft/vscode#78484]
In the explorer tab, it will be nice if i could mark some specific file or folder to be always highlighted with the color of my choice so that i could find the file i use often faster.

In the file right-click menu, add additional button - "mark" ---> opens color-picker.
After color is applied the file always has a colored bg. 
The bg looks the same as current selected file bg, but with custom color:
![1](https://user-images.githubusercontent.com/15216174/62453199-2071e280-b772-11e9-8a9f-b92699f25cee.png)
If the marked file is selected, the bg should still contain mark color somehow (increased brightness?), but current behavior can also be left without changes - it is not so critical.

And thanks! VSCode is awesome!

**Comment by isidorn** [comment]
Extensions can add context menu actions to the explorer. So that would be step 1.
And I believe that extensions can also add decorations (like Git is doing making things orange).
So putting those two together could produce what you are looking for via an extension.
