### ISSUE TITLE
Diff of UTF-16 LE coded files corrupted

### ISSUE THREAD

**Issue by modbw** [microsoft/vscode#78482]
Issue Type: <b>Bug</b>

If a UTF-16 LE encoded is changed in a GIT repo the diff is corrupted 

![image](https://user-images.githubusercontent.com/4498104/62451784-33cf7e80-b76f-11e9-9dc5-03ed1e80b69b.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-157-generic

**Comment by joaomoreno** [comment]
#48038
