### ISSUE TITLE
VScode detects incorrect Character Set of file.

### ISSUE THREAD

**Issue by dharam-live** [microsoft/vscode#78494]
Issue Type: <b>Bug</b>

VScode detects the incorrect character set of a file. The file used is encoded in Windows 1252 but this is interpreted as UTF-8.

Expected result is that when opening a file encoded in a certain character set, VScode detects the correct character set of the file. In this case it should display Windows 1252 in the status bar and not UTF-8.

Steps to reproduce:
1. open a file encoded in Windows 1252 not from VScode and generated outside of VScode.
2. open the file in VScode check the character set in the bottom right of the status bar.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.99GB free)|
|Process Argv|C:\Users\dharam.pankhania\Downloads\knapp ansi issue\New folder\V605MWLE04567308020PRODUCTREDPRAIRIE20190726214000_fromarchive.CSV|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vscode-edit-csv|jan|0.1.2
mssql|ms-|1.6.0
azurecli|ms-|0.4.6
csharp|ms-|1.21.0
notepadplusplus-keybindings|ms-|1.0.3
vscode-xml|red|0.8.0
vscode-hexdump|sle|1.7.2
vscode-detect-charset|yel|0.0.1

</details>

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
