### ISSUE TITLE
editor.fontFamily is not being respected on Linux

### ISSUE THREAD

**Issue by jeng1220** [microsoft/vscode#78493]
- VSCode Version: 
```
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
```
- OS Version:
```
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic
```
Steps to Reproduce:

1. upgrade Ubuntu 16.04 to Ubuntu 18.04
2. reinstall vscode 
```bash
sudo apt-get purge code -y
rm -rf .vscode .vscode-cpptools .config/Code
sudo apt install ./code_1.36.1-1562627527_amd64.deb
```

Does this issue occur when all extensions are disabled?: Yes

This is a snapshot:
![incorrect](https://user-images.githubusercontent.com/5894445/62857725-ec2a9300-bd2a-11e9-83bc-db706be53b93.png)

Before I upgraded Ubuntu, pixel width of whitespace is correct, like this:
![correct](https://user-images.githubusercontent.com/5894445/62857736-f0ef4700-bd2a-11e9-86d1-13097616ec09.png)

Could anyone help please?

**Comment by Tyriar** [comment]
You're using a non-monospace font, what's in your settings.json?

**Comment by jeng1220** [comment]
Thanks for reply.
I haven't changed any setting yet.
The font is:
```
'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'
```

**Comment by jeng1220** [comment]
checking installed font,  my system did have **Droid Sans Fallback** font
```bash
$ fc-list | grep "droid"
/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
```

**Comment by alexandrudima** [comment]
@jeng1220 Could you please install some free font like Hack and then try to choose it via `"editor.fontFamily": "Hack"`?

I believe that Ubuntu stopped shipping / tweaked some fonts in Ubuntu 18, and I'm not 100% sure how upgrading from Ubuntu 16 to 18 differs from a fresh Ubuntu 18...

**Comment by jeng1220** [comment]
@alexandrudima ,
Thanks for reply but it didn't work.
I used following command to install Hack font
```bash
$ sudo apt-get install fonts-hack-ttf
```
Checking font:
```bash
$ fc-list | grep hack
/usr/share/fonts/truetype/hack/Hack-Regular.ttf: Hack:style=Regular
/usr/share/fonts/truetype/hack/Hack-Bold.ttf: Hack:style=Bold
/usr/share/fonts/truetype/hack/Hack-BoldItalic.ttf: Hack:style=Bold Italic
/usr/share/fonts/truetype/hack/Hack-Italic.ttf: Hack:style=Italic
```
Then I tried 
```
"editor.fontFamily": "Hack"
```
and also tried
```
"editor.fontFamily": "hack"
```
but it didn't work

**Comment by alexandrudima** [comment]
@jeng1220 Could you please try to open the following in Chromium:
https://jsfiddle.net/x40jt5g6/

This is how it renders for me (I also have Hack installed):
![image](https://user-images.githubusercontent.com/5047891/62855741-532c5580-bcf3-11e9-922e-e504c97d824d.png)

Could you please post a screenshot of how it is rendered? How is it rendered in Firefox?

**Comment by jeng1220** [comment]
The results rendered by Chromium and Firefox are very similar.
And results are normal.
![render](https://user-images.githubusercontent.com/5894445/62857377-0dd74a80-bd2a-11e9-8705-742e04c22def.png)

**Comment by alexandrudima** [comment]
Now I'm a bit confused myself... Is your `settings.json` file valid? Can you change other settings successfully? How about the integrated terminal font? Does changing `"terminal.integrated.fontFamily": "Hack"` do anything?

**Comment by jeng1220** [comment]
I just updated vscode to v1.37, then I checked terminal font.
This is what I saw at first:
![original](https://user-images.githubusercontent.com/5894445/62911714-ee86fe80-bdb7-11e9-861b-0da8511c250b.png)
Then I saw a warning showed up:
![warning](https://user-images.githubusercontent.com/5894445/62911736-0199ce80-bdb8-11e9-8380-ee1590d30c1d.png)
so I tried to use `monospace`, then it worked:
![monospace](https://user-images.githubusercontent.com/5894445/62911823-4e7da500-bdb8-11e9-9486-3a2396ad494e.png)

I also try `Hack` and now it works too, but the installed font `Droid Sans Fallback` still cannot be taken effect (like what I saw at first). To me, it seems that problem was solved but vscode may still has potential issue. @alexandrudima  do you want to check anything? Otherwise I will close this issue.

**Comment by alexandrudima** [comment]
Font selection itself is done by Chromium... I cannot say what could be wrong with the Droid Sans Fallback and why Chromium doesn't find it... But I'm happy you're now in a working state.
