### ISSUE TITLE
Brackets are drawn in the insider version

### ISSUE THREAD

**Issue by coaperator** [microsoft/vscode#78492]
Brackets are drawn in the insider version of VS CODE to fold the code instead of +/-. how to get back into place +/-
**change it** 
![image](https://user-images.githubusercontent.com/6645911/62460463-bca7e380-b78a-11e9-8720-3eccd2687a0a.png)
on this
![image](https://user-images.githubusercontent.com/6645911/62460532-ecef8200-b78a-11e9-8be2-58f4b9434e3a.png)

**Comment by IllusionMH** [comment]
This works as intended and was implemented as part of iconography update #8017 .

These icons (basically collapse, expand) are now unified and used across the app (fold/unfold, Explorer, custom trees etc.)

Not sure if these can be changed as part of theme.

**Comment by kanlukasz** [comment]
Icons are redesigned and now everything is consistent
This was the goal that was achieved.

You don't have `+/-` but you have `>/v` instead which is readable too

![obraz](https://user-images.githubusercontent.com/30685349/62466084-bfa5d280-b790-11e9-9653-48749e0d18db.png)

I do not think that VS Team will change that.
If you get a lot of 👍 here, maybe they'll think about it again, but honestly, I do not think so

**Comment by coaperator** [comment]
Nightmare pointers!
Informativeness is zero, because parentheses usually indicate a place, a string. They do not carry information about the blockiness of the code, while +/- precisely indicate the blockiness of the code, that it can be minimized / expanded.

The three most important visual things for me in the editor are:
- hearth backlight
- code folding +/- (this is a generally accepted standard for editors)
- brackets on one line with the code minimized (this is a generally accepted standard for editors)

If the update is accepted and the normal icons (+ and -) are not left - for me this editor is dead.

And what were the hopes.

**Comment by octref** [comment]
I have to say I also think while hovering, the icon should change to the down chevron to indicate that the action will "expand":

![image](https://user-images.githubusercontent.com/4033249/62480805-ab98ab80-b765-11e9-9020-8ba18b66bc0d.png)

Plus sign was a good indication of the action of expanding.

**Comment by misolori** [comment]
We already have an issue tracking this https://github.com/microsoft/vscode/issues/78024
