### ISSUE TITLE
Incorrect TypeScript types

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#78495]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14

I have the following snippet of code:

```typescript
interface jQuery {
  [index: number]: Element | undefined,
  get ( index: number ): Element | undefined;
}

class jQuery {}

jQuery.prototype.get = function ( this: jQuery, index: number ) {

  const element = this[index];

  return element;

};
```

As you can see the variable named `element` should be of type `Element | undefined`, as that's the type I'm using in the index signature.

Sure enough that's what I'm seeing in TS's [playground](https://www.typescriptlang.org/play/#code/FASwdgLgpgTgZgQwMZQAQCsCKBXWBPVAb2FVQG1wATKADwC5UxsBbAI1gF0GBRAGymZRIqAD6psYanHBRKAGhKoA5lAioAFKiq0GTNrFQBKHv0HCxEqTMoBuYAF9gwJLwQBnNxhz4ij4FlwYPAA6AAcYAHsIKLxQqGCVNQBeVDgJJAgQCLANVAgACxA3BgD8OS1JHUYWdhgjIidFJGy3NShTIWS8wrcKSpoOO0UYVWwYHPaBTqH7OyA):

<img width="977" alt="Screen Shot 2019-08-05 at 14 12 59" src="https://user-images.githubusercontent.com/1812093/62464015-cb42ca80-b78b-11e9-954c-510b2642ae4c.png">

But VSCode instead is reporting that `element` is of type `Element`, which is incorrect:

<img width="559" alt="Screen Shot 2019-08-05 at 14 12 38" src="https://user-images.githubusercontent.com/1812093/62464047-deee3100-b78b-11e9-860b-1708b5d31be1.png">

As you can see in boh the playground and vscode I'm using TS v3.5.1. Switching to v3.5.2 didn't fix it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have `strictNullChecks` enabled for project in VSCode?

**Comment by fabiospampinato** [comment]
That seems to be the issue, disabling it in the playground make it behave like vscode, thanks!
