### ISSUE TITLE
Right click should offer remote variants of "Open with Code"

### ISSUE THREAD

**Issue by stellirin** [microsoft/vscode#78491]
We have fully embraced remote WSL and remote containers. We have a have a large number of projects set up for this. We would save a lot of time if we had the option to launch a folder directly into WSL or a container, especially those of us who do a lot of context switching.

Right now the flow for WSL is:
* Right-click > 'Open with Code'
* Wait for VS Code to open
* F1 > Type 'remote' 
* Choose 'Remote-WSL: Reopen folder in WSL'
* Wait for VS Code to reopen

A more efficient workflow would be:
* Right-click > 'Open with Code in WSL'
* Wait for VS Code to open

(An option for Remote-SSH should also be there, but we haven't used that yet)

**Comment by aeschli** [comment]
The problem is that 'Open with Code' is set up by the VSCode installer, but remote WSL is only an extension. What you request would mean to bundle WSL with VSCode.

**Comment by stellirin** [comment]
So I can appreciate this is difficult because the WSL functionality is an extension. However I'm curious _why_ this functionality should remain an extension. For me and my colleagues this is a 'killer' feature that improved our workflows immensely.

We feel that it _should_ be bundled as a feature of VSCode on Windows by default to allow deeper integration with the OS as suggested.

If you have time to briefly state the reasoning for not bundling this by default, we might be a bit less grumpy 🙃

Thanks!

**Comment by ddouglas** [comment]
@stellirin I googled this today and found #79208, which led me here. Using that issue and this one, I was able to put the following shortcut together. 

```
code --folder-uri=vscode-remote://ssh-remote+7b22686f73744e616d65223a224f54534c6f63616c227d/var/www/chatter/ui
```

1. Have the code extension installed
2. Open a fresh VS Code window and immediately connect to your target host
3. Open VSCode output console, switch to remote filter in the dropdown
4. Look for a line like what I underlined in my screenshot below.
![Code_sXHobhj5RJ](https://user-images.githubusercontent.com/48367195/71451355-b6b69d00-2741-11ea-9d6c-e5ff50c40f12.png)
5. Replace the hash in the command above with yours and `voila!`

Not sure how feasible this actually is, but it works for me.

On Windows 10, when I double click the shortcut a cmd window open for about 3 seconds and then closes and VSCode launches and connects to my Local VM.

Also, @aeschli a possible alternative to 'Open with Code' is still 'Open with Code' but search for some sort of configuration file, probably .remote or something and inside of there are details outlining the SSH Host and Directory to connect to on the remote. After that, you can treat the connection attempt as if they already had VSCode open.

**Comment by aeschli** [comment]
`Open with Code in WSL` has been added a few weeks back in the Remote -WSL extension. Please check it out.
