### ISSUE TITLE
Account Sync

### ISSUE THREAD

**Issue by LuizKrlz** [microsoft/vscode#78490]
Issue Type: <b>Feature Request</b>

It would be interesting if I had a way to log into account and sync my extensions and settings. Same as Google Chrome that syncs forward your email.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-20-generic

**Comment by IllusionMH** [comment]
In meantime you can use great extension for this: [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)
