### ISSUE TITLE
String interpolation confounds text coloring

### ISSUE THREAD

**Issue by BRS999** [Microsoft/vscode#7849]
- VSCode Version: 1.2.1
- OS Version:  OSX 10.11.5

Background: I was playing around with some new C# features when I noticed the text coloration became wonky in VSCode.

Steps to Reproduce:

1. Add this line of code to a blank cs file `public void Print() => WriteLine($"Your name is {FirstName} and {LastName}");`
2. Add this line of code after it `public void sqrt() => WriteLine(Sqrt(3 * 3 + 4 + 4));`
3. Observe the wonky text coloring.

See screenshot
<img width="727" alt="screen shot 2016-06-18 at 8 37 53 am" src="https://cloud.githubusercontent.com/assets/6516437/16170902/f7852818-352f-11e6-9e60-eb8024c2f141.png">

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#588
