### ISSUE TITLE
AWS Lambda function integration

### ISSUE THREAD

**Issue by ranjit009** [microsoft/vscode#78499]
Ability to connect to aws, using aws credentials.
Which allows users to run lambda functions locally. Just like sublime text which already has an plugin to do this.

**Comment by IllusionMH** [comment]
Custom integrations are most likely should be addressed with extensions (similar to plusing for Sublime)
Have you tried to search for extensions? and check AWS docs?
Looks like it already exists https://aws.amazon.com/visualstudiocode/

/question
