### ISSUE TITLE
Integrated terminal: execvp(3): failed. No such file or directory

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#7850]
- VSCode Version: 1.2.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Start VSCode
2. Command Palette: Toggle Integrated Terminal

Terminal panel shows for a second with `execvp(3): failed. No such file or directory` and then closes.

It used to work in the past, not sure what happened that it stopped. Redownloaded VSCode but still the same problem

**Comment by wallverb** [comment]
This problem does not happen if i start `code` from terminal. It only happens when I start it from Finder/Spotlight.

**Comment by wallverb** [comment]
Ok, found the problem, not sure why it happens though:

When I start VSCode from Finder then User Settings have this:

`"terminal.integrated.shell.osx": "/bin/zsh\nCOM_GOOGLE_CHROME_FRAMEWORK_SERVICE_PROCESS/USERS/GOD/LIBRARY/APPLICATION_SUPPORT/GOOGLE/CHROME_SOCKET=/private/tmp/com.apple.launchd.dMvrDCzGvG/ServiceProcessSocket",`

but when i start `code` from Terminal then it is:

`"terminal.integrated.shell.osx": "/bin/zsh"`

I fixed this issue by overriding this value with `"terminal.integrated.shell.osx": "/bin/zsh"` in my settings and then it works. Not sure why that `COM_GOOLGE_*` stuff gets added there

**Comment by Tyriar** [comment]
Can you try this out in the insiders build to see if that fixes your problem? Otherwise it's an issue with our environment parsing code.

**Comment by wallverb** [comment]
Insiders build seems not to have this problem. Although it does have problem with scrolling of terminal as described in here: #7817
