### ISSUE TITLE
Web: hot-exit can turn files empty if leaving the page while backups are made

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78500]
I would like to understand how files can turn empty that are being backed up while the user leaves the editor. We should investigate to add some safety measures to prevent this from happening if possible.

**Comment by isidorn** [comment]
Great. Let me know if I can help.

**Comment by bpasero** [comment]
Given all the stuff in https://github.com/microsoft/vscode/issues/73884 I wonder if https://github.com/microsoft/vscode/commit/c223ba6f80b66b1bad90dbd7b8f5079d8ef372e8 fixed this.

**Comment by isidorn** [comment]
I can still reproduce this with latest from master.
It took me 5 attempts to reproduce.

**Comment by bpasero** [comment]
This is what happens:
- a backup file was being created
- the workbench went down before any contents could get written to (a write is always a truncate(0) first, which explains why the file ends up being empty)
- the workbench starts up and finds the backup (even though empty)
- the workbench happily thinks the file was made empty by the user before shutdown and shows an empty editor that is dirty
- at this point the user could easily restore the original file by closing the editor and reopening it or simply picking File > Revert File

I pushed a fix to throw an error when we restore a backup that is missing our meta data: Every backup's first line is a string of meta data (e.g. file name) that must be there to ensure the backup is not corrupt. Since the backup file is empty, the meta marker cannot be found.

The visible effect of this is that we fallback to opening the file normally and discarding the malformed backup. 

//cc @Tyriar

**Comment by isidorn** [comment]
Sounds good. I can no longer reproduce -> thus adding verified label.
Thanks for fixing this.
