### ISSUE TITLE
Stable version release notes in insider build.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#78506]
Issue Type: <b>Feature Request</b>

Is it possible to have stable version release notes in insiders version as well?

proposed:
Help Menu:
-> Release Notes(points to insiders)
-> Stable Release Notes( points to stable version release notes)

I know i can always find the release/features on the github release, however it never hurts to have it handy :)

VS Code version: Code - Insiders 1.37.0-insider (4a03f7e7eff2560d2e53c029321870514d19a2aa, 2019-08-05T09:34:10.366Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-54-generic

**Comment by gregvanl** [comment]
Hi @sanket-bhalerao Thank you for the suggestion but I think this would confuse some users. We want to show the release notes in-product that match the release that the user is currently running. This can get especially problematic if a user is running an early version of Stable or Insiders.
If you are not running Stable (to read the Stable release notes), you can always read the latest Stable and previous release notes on the VS Code website at https://code.visualstudio.com/updates.
