### ISSUE TITLE
Allow to minimize editor groups to 0 size

### ISSUE THREAD

**Issue by MaliusArth** [microsoft/vscode#78519]
Currently, there is a minimum size for editor groups, it would be great to minimize them entirely, so they are only visible in the "open editors" explorer sidebar. (also not focus them when debugging)

**Comment by sbatten** [comment]
> also not focus them when debugging

@MaliusArth what do you mean by this?

**Comment by joaomoreno** [comment]
@MaliusArth Can you show me a screenshot of the area you mean by "editor groups"?

**Comment by MaliusArth** [comment]
![vscode-minimize-tab-groups](https://user-images.githubusercontent.com/1645005/62615586-d7569580-b90d-11e9-85eb-a3e01cc49f86.png)
i have tab groups as focus groups like all config stuff in 1 tab group because i have a big multi workspace project and don't want to search for the right config and i don't want configs to open in between other files, just in a separate tab group.
I also use this to separate external code bases from my own but have them open for quick reference.
