### ISSUE TITLE
Sidebar: Search width independent of Explorer width

### ISSUE THREAD

**Issue by garyskiba** [microsoft/vscode#78512]
There are currently two states of the Explorer: open and closed.  All other sections are opened to the width of the Sidebar.  Resizing the sidebar width affects all sections.

I use Search in Files a LOT.  However, I constantly find myself resizing the sidebar width to provide more readable results.  I then have resize again when I no longer need the additional space (e.g., use the explorer).  Seems a bit clunky.

Request:
1. A separate persisted property for the sidebar width of each section (e.g. Search).  When opening that section, the width of the sidebar would be automatically adjusted.  
2. A setting for each Sidebar section that would have it either use a common width (based on the Explorer) or make it independent of the others.  This would default to "common".
3. (optional) A Sidebar setting for either forcing a common width or allowing it to be controlled by the section (from 2. above).

**Comment by gjsjohnmurray** [comment]
@garyskiba have you tried setting `search.location` to move Search to the panel area instead of it being constrained by the sidebar width?

**Comment by sbatten** [comment]
I second @gjsjohnmurray response. This sounds very complex from a UX perspective when I believe search in panel is intended for your use case.

**Comment by garyskiba** [comment]
I know about that option, but prefer the sidebar.

And this is not just about search, but any plugin on the sidebar.

As for UX complexity, one additional setting is not very complex.  Nothing changes unless the user selects "allow independent width", and then all VSC has to do is keep track of them separately and use the appropriate one (sideBar.width = user.independentWidths ? plugin.width : default.width; // psuedo-code).
