### ISSUE TITLE
Is JavaScript IntelliSense forever gone?

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#7851]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Build 14342.rs1_release

Steps to Reproduce:

1. Set language mode to JavaScript.
2. Type something.   

Only keywords will be popped up.

Update: it was my fault but I wish that JS IntelliSense were added to JavaScript files outside a folder.

**Comment by decker67** [comment]
Maybe they want you to use TypeScript ;-(

**Comment by dbaeumer** [comment]
@infinnie what exactly do you mean with outside the folder. Outside the workspace you have open or is the file an untitled file (doesn't exist on disk). The second one is currently not working the first one should. 

@decker67 out goal is to have good JS and TS support :-)

**Comment by infinnie** [comment]
@dbaeumer the 2nd one.

**Comment by dbaeumer** [comment]
Then it is a dup of https://github.com/Microsoft/TypeScript/issues/4526 which needs to be fixed in the TS support we use.
