### ISSUE TITLE
Debugging iframe inside of webview not working

### ISSUE THREAD

**Issue by hsiwkin** [microsoft/vscode#78515]
Console.logs from the inside of the iframe in the webview are not printed. Also it isn't possible to debug source file from the iframe.

- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2 LTS

Steps to Reproduce:
1. Clone the repo with the example: https://github.com/hsiwkin/vsc-bug-example
2. Start the server containing page we want to show in the iframe located in webview: `npm run start:server`
3. Press `F5` to compile and run the extension
4. Run the Hello World command from the Command Palette (Ctrl+Shift+P) in the new window
5. Open Webview Developer Tools console
6. Reload Webviews
7. Notice that instead of 2 console logs (from the webview and the iframe) two errors are printed, each of which saying: `VM93 main.js:10 [Violation] Avoid using document.write().`

Does this issue occur when all extensions are disabled?: Yes (all but the tested one)

**Comment by mjbvz** [comment]
Your html is invalid. Iframes cannot be selfclosing. Change it to `<iframe ...></iframe>`
