### ISSUE TITLE
workbench.action.toggleMaximizedPanel should fill entire view when experimentalGridLayout is enabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78516]

**Comment by Tyriar** [comment]
Current:

<img width="685" alt="Screen Shot 2019-08-05 at 9 32 49 AM" src="https://user-images.githubusercontent.com/2193314/62480200-0e894300-b764-11e9-9e1c-e5f2b09e261c.png">

Desired:

<img width="670" alt="Screen Shot 2019-08-05 at 9 32 55 AM" src="https://user-images.githubusercontent.com/2193314/62480208-147f2400-b764-11e9-8484-f65c2012bba0.png">

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/42149

**Comment by isidorn** [comment]
@sbatten it would be great if we could tackle that feature with the new grid layout.
