### ISSUE TITLE
Visual Code 1.35+ doesn't detect the '$or' operator like the valid operator of SEQUELIZE TYPESCRIPT

### ISSUE THREAD

**Issue by RobertoGlez** [microsoft/vscode#78523]
Visual Code doesn't detect operator '$or' on version 1.35, I thought it was Sequelize Typescript but only crash in version 1.35 or higher, in version 1.34 I don't have any problem with implementation this operator 

- VSCode Version: 1.35+
- OS Version: Windows 10

![Captura de pantalla (124)](https://user-images.githubusercontent.com/20331406/62482287-629f2200-b77a-11e9-8f2f-1fe79c5c0c3a.png)
![Captura de pantalla (125)](https://user-images.githubusercontent.com/20331406/62482289-629f2200-b77a-11e9-9bba-1a5fa797dc28.png)

**Comment by IllusionMH** [comment]
VSCode 1.35 and 1.36 ships with be TS version of TypeScript - 3.5. Which at least has breaking change that improve soundness of indexed types.

Do you use built-in version of TS or from your `node_modules`?

**Comment by RobertoGlez** [comment]
I use a built-in version of TS for my project, only compile all js on a dist folder and run with a node here, I don't use any node dependency for handler typescript

**Comment by IllusionMH** [comment]
Then I think it is difference in object behaviors in TS. You can verify it by installing concrete version of TS (`3.4.x` or `3.5.x`) and adding `typescript.tsdk` that points to your cuctom TS install.
See details here: [Using a TypeScript Nightly Build Within Visual Studio Code](https://mariusschulz.com/blog/using-a-typescript-nightly-build-within-visual-studio-code) (can't find good example in docs)

If you won't see error with TS 3.4 but will see it with TS 3.5 - it might be releated to https://github.com/microsoft/TypeScript/pull/30769
Then it is better to create issue in library repo to see if they support TS 3.5, or (less likely) you should create issue in TS repo.

**Comment by octref** [comment]
Please create an issue in TS repo. You can also follow @IllusionMH's advice to stay on 3.4.
