### ISSUE TITLE
VSCode Freeze when working with big json

### ISSUE THREAD

**Issue by gorydev** [microsoft/vscode#78524]
Issue Type: <b>Bug</b>

Hello I have a 40mb JSON with 1.400.000 lines file and when I try to open it in Code the editor freezes and becomes really slow there's times when I need to restart the editor because the functions like git tracking or autocomplete stops working because of the json file also I keep getting the message: Extension host terminated unexpectedly. and 2 optiones restart extension host and open developer tools

in working on a MacBook Pro 13" 2017
MacOS Mojave

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
gc-excelviewer|Gra|2.1.32
vscode-styled-components|jpo|0.0.26
vscode-colorize|kam|0.8.11
git-graph|mhu|1.12.1
vscode-docker|ms-|0.7.0
sqltools|mtx|0.19.7
material-icon-theme|PKi|3.8.1
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.3
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please try disabling all extensions to see if it's caused by extension.
Also please provide info as requested here: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by aeschli** [comment]
Also, please disable breadcrumbs and the outline view to see if this makes a difference.
