### ISSUE TITLE
 C# snippet with macro recorder variables

### ISSUE THREAD

**Issue by fabiodocit123** [microsoft/vscode#78520]
Please i need something like that (im not developer but this question will help much people).

Macro recorder support c# snippets. (i dont know what snippets is )

I need mirror clipboard 2 variables in the start of program and the variable of snippet mirror that clipboard value with paste option in ... 
I try put the flow . 

User > You need write your email and password > clipboard variable 1 and clipboard variable 2 C#snippet can stash this variable ? 
after hit some "tab" buttons on keyboard paste or mirror this variable with new snippet code is possible ?
Im using jibit macro recorder to try to this.

edit: Other thing i think can do to stash this snippets in macro binds... clipboard 1 (when press ctrl+D 
paste snippet 1) when press ctrl+E paste snippet 2. 
In macro i can do that... but i dont know to develop that snippets variables.

**Comment by octref** [comment]
Please open issue for C# extension.

**Comment by fabiodocit123** [comment]
where i can put this .. microsoft/vscode extension ? because this is like a question about put variables on snippet interacting with clipboard

**Comment by octref** [comment]
You can find more information on snippets here: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by fabiodocit123** [comment]
thank you very much for the help guys.. im going for this user defined session ^>^
