### ISSUE TITLE
"Go to definition" on symbol with multiple definitions does not navigate to the first item, and the first item can't be opened

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78521]
Previously was https://github.com/microsoft/vscode/issues/69613

- F12 on `onDidSelection` at https://github.com/microsoft/vscode/blob/6e498530cc95080ab907d5048b712ce5e8972425/src/vs/platform/list/browser/listService.ts#L703
- It's impossible to navigate to the first result

**Comment by roblourens** [comment]
This is from https://github.com/microsoft/vscode/issues/78174 @alexr00 but that change seems correct, I think we should fix https://github.com/microsoft/vscode/blob/6e498530cc95080ab907d5048b712ce5e8972425/src/vs/editor/contrib/referenceSearch/referencesWidget.ts#L385, I think it is just assuming that browserEvent will be undefined when triggered by the keyboard. We can change this for pass for any KeyboardEvent too.

**Comment by jrieken** [comment]
Thanks @roblourens
