### ISSUE TITLE
HEX editing to insert ASCII Characters

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#78535]
I want to add a character from the extended ASCII characters to the `settings.json` file.  Unfortunately my keyboard does not have a numeric keypad; therefore, I was hoping I could edit the `setting.json` file in a HEX editor to replace the character I want with one of the extended ASCII characters.  Although the `settings.json` file does not recognize changes to the HEX value of the document ?

**Comment by roblourens** [comment]
settings.json is just a normal json file. You can edit it however you want. It's not really clear what you mean by 

> Although the settings.json file does not recognize changes to the HEX value of the document ?

I would need more details to help

**Comment by SheepDomination** [comment]
@roblourens I loaded the settings.json file in a hex editor and where I wanted an extended ASCII character, for example `ALT+178` I replace the character; whatever character that may be from a standard keyboard, with the hex code of an extended ASCII character, for example `ALT+178`.  

I then saved the file as a settings.json file in the hex editor, upon loading the settings.json file; I was hoping to see the character from the extended ASCII character list (`ALT+178`), unfortunately that wasn't the case.  Therefore, it appears as though you cannot edit a json file in a hex editor and have the changes reflect ?

**Comment by roblourens** [comment]
You need to set the file encoding to an encoding that includes that character.

**Comment by SheepDomination** [comment]
> You need to set the file encoding to an encoding that includes that character.

It's `UTF-8`; you can try it yourself. If you have a keyboard with a physical numeric keypad, type `ALT+178` in notepad, you'll get the, what is described on [this](https://coding.tools/ascii-table) page as the *Graphic character, high density dotted*.  

Setting the encoding to `UTF+8` doesn't cause the *Graphic character, high density dotted* character to appear within the `settings.json` file; even if I edit the `setting.json` file in a hex editor and change a `.` to the hex value for the *Graphic character, high density dotted* it does not show up as the *high density dotted* character within the `setting.json` file.

**Comment by roblourens** [comment]
It's not utf-8. I think you want cp437 or windows 1252.

**Comment by SheepDomination** [comment]
cp437 shows the correct extended character ASCII character, only when it's a text file; a json file shows this character, �. And windows1252 doesn't work in both cases.

**Comment by roblourens** [comment]
It works for me. The file extension doesn't matter.

**Comment by SheepDomination** [comment]
@roblourens Are you entering the ASCII code on a physical keypad with a numeric keypad for the `settings.json` file, or did you try to edit the hex value in a hex editor to create the character in the `setting.json` file ? All the while making sure the encoding in vscode was *cp437*.

If it's the latter, as in you edited the `settings.json` file in a hex editor; what hex value did you use ?

**Comment by roblourens** [comment]
It doesn't matter how you enter it. I echoed that exact byte into a file. vscode is capable of displaying that byte as a character if you set it up correctly.

**Comment by SheepDomination** [comment]
I create a `^` character in the *settings.json* file.  Then I open the *settings.json* file in a hex editor enter the correct hex code for what is the `^` character.  I open the *settings.json* file in vscode, change the encoding to `cp437` and the character which I changed in the hex editor is not displayed.  

What could be wrong, it all seems correct.
