### ISSUE TITLE
Extensions Stucked Installing Status

### ISSUE THREAD

**Issue by MrX456** [microsoft/vscode#78534]
Issue Type: <b>Bug</b>

Some extensions are stucked in installation and can´t install new Extensions

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-html-css|ecm|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-javac|geo|0.2.18
python|ms-|2019.3.6558
csharp|ms-|1.20.0
java|red|0.46.0
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.1.7
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
vscode-icons|vsc|8.8.0

</details>

**Comment by octref** [comment]
What are the "some extensions"?

**Comment by octref** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release. 

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.
