### ISSUE TITLE
DEBUG CONSOLE has no color

### ISSUE THREAD

**Issue by SCUTJcfeng** [microsoft/vscode#78538]
![vscode_color_issue](https://user-images.githubusercontent.com/14869384/62508842-ac9c0c80-b83b-11e9-8b74-226ceb4b6968.png)
Here is my spring boot application debug conosle, is there a way to colorize it?
Anyone help?

**Comment by isidorn** [comment]
Yeah the debug extension could control this. We support ansii character colorisation.
Anyways please file this agains the debug estension you are using. Thanks!
