### ISSUE TITLE
Shell Command `code` fail if specific python version with pyenv is not installed

### ISSUE THREAD

**Issue by hiroga-cc** [microsoft/vscode#78530]
- VSCode Version:1.36.1 
- OS Version:macOS 10.14.6

Steps to Reproduce:

1. install and setup pyenv 
2. install specific version of python. like `pyenv install 3.7.4`
3. set local python. like `pynev local 3.7.4`
4. unisntall specific version. like `pyenv uninstall 3.7.4`

How to fix:
in /usr/local/bin/code
`function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }`
↓
`function realpath() { usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }`

Related Issue:
https://github.com/microsoft/vscode/issues/3790

**Comment by octref** [comment]
https://github.com/microsoft/vscode/issues/46123
https://github.com/microsoft/vscode/pull/56943

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/pull/74082#issuecomment-498258126
