### ISSUE TITLE
Install extensions from Marketplace in China

### ISSUE THREAD

**Issue by iloveyo123u1** [Microsoft/vscode#7853]
- VSCode Version:1.2.1
- win Version:10 64x

Steps to Reproduce:

 connect ETIMEDOUT 191.238.172.191:443

i'm try 10 times， install python Extensions

**Comment by dbaeumer** [comment]
Might be a proxy issue.

**Comment by joaomoreno** [comment]
@iloveyo123u1 Did you configure your [proxy settings](https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support)?

**Comment by iloveyo123u1** [comment]
my pc install https://github.com/getlantern/lantern  ,i 'm not configure proxy seetings, i fix it,but still have the occasional problem

**Comment by iloveyo123u1** [comment]
thanks @dbaeumer  @joaomoreno

**Comment by rebornix** [comment]
@joaomoreno Do we have marketplace guy on GitHub? We've seen a lot of issues complaining the extension installation failure/slowness from China. Do they have any monitoring or reports for it? We may need some enhancement for marketplace like what people do for Windows or VS.

**Comment by joaomoreno** [comment]
I'll make sure they get the feedback.

**Comment by joaomoreno** [comment]
@iloveyo123u1 Do you get the error when browsing for extensions or installing an extension?

**Comment by iloveyo123u1** [comment]
https://en.wikipedia.org/wiki/Great_Firewall

**Comment by joaomoreno** [comment]
Feedback has been sent to Marketplace team. They have improved download speeds significantly.
