### ISSUE TITLE
VSCode high CPU when browse Native-base StyleProvider and React-native 0.60.4

### ISSUE THREAD

**Issue by grean** [microsoft/vscode#78548]
Hi,
I post this specific ReactNative/Native-base weird behavior here because maybe it's a parse/eslint/jsx/etc... problem with all this big stuff.
Already posted here : https://github.com/GeekyAnts/NativeBase/issues/2849#issue-476933146

I've isolated a weird behavior in my workflow.
I'm using :
Win10 pro, Version : 1903, build : 18362.239
vscode 1.36.1
RN 0.60.4
Native-base 2.13.4 with theme ejected and up to date
As soon as i open the file that containing the styleProvider component and modify it, intellisence goes very slow on all the other files.
When i look at my process explorer, it looks like this screenshot above and it never improve before i restart VScode even if i close the problematic file.
![Task Manager](https://user-images.githubusercontent.com/170967/62528180-b4a87c00-b83c-11e9-9d55-8aaa0c78d11b.png)
Here a simple exemple that has the problem :
```
import React, { Component } from 'react';
import { Root, StyleProvider } from 'native-base';
import getTheme from '../native-base-theme/components';
import platform from '../native-base-theme/variables/platform';
import Main from './Main';
export default class App extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <Root>
        <StyleProvider style={getTheme(platform)}>
          <Main />
        </StyleProvider>
      </Root>
    );
  }
```
A workaround is to isolate this piece of code and never open it to keep vscode stable.
I've no error or warning due to lint/flows/etc..
It worked nice before my migration to RN 0.60.4 from RN 0.59.9

**Comment by grean** [comment]
This issue is still present even with the last release of VScode 1.37.0
Also, an other person get the intellisence type script problem here : https://github.com/GeekyAnts/NativeBase/issues/2864

**Comment by mjbvz** [comment]
Can you please share a small, complete example project that demonstrates this issue

/needsMoreInfo

**Comment by grean** [comment]
Thanks for replying.
You have to get a React native project : https://facebook.github.io/react-native/docs/getting-started.html from React native CLI quick start part (you don't need to setup an emulator device, just a react native project, the goal is to get a project with node_modules)
Once you get it, go inside your new project, and install Native-base with : yarn add native-base
then eject the theme folder with this command : node node_modules/native-base/ejectTheme.js (source https://docs.nativebase.io/Customize.html#theaming-nb-headref) the goal is to get a file that is causing the issue. Now you have a new folder named : native-base-theme
Go inside and open this file for exemple : native-base-theme\variables\platform.js
after a few second, you can see that a 10 or 15% CPU load is appeared and never go down even if you close this file.

![Task Manager](https://user-images.githubusercontent.com/170967/62928250-7b31bc80-bdb8-11e9-91b8-fe939b51b716.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
