### ISSUE TITLE
macOS Catalina: no more python preinstalled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78543]
As far as I have learned, macOS Catalina will not have Python installed. We seem to be relying on it at least from our startup script.

**Comment by pellstrike** [comment]
> As far as I have learned, macOS Catalina will not have Python installed.

Is this really true? From what I've observe macOS Catalina still comes with python 2.

**Comment by bpasero** [comment]
@pellstrike oh, totally true! It only seems to be deprecated and will be removed in macOS 10.16: https://www.macobserver.com/analysis/macos-catalina-deprecates-unix-scripting-languages/
