### ISSUE TITLE
Extension code cache does not get invalidated

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#78542]
Distilled from https://github.com/microsoft/vscode/issues/75642#issuecomment-518547141

Create an extension at e.g. `c:\Users\alex\.vscode-insiders\extensions>`

* `package.json`:
```js
{
    "name": "75642",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.31.0"
    },
    "activationEvents": ["*"],
    "main": "index.js"
}
```

* `index.js`:
```js
const vscode = require('vscode');

exports.activate = function() {
    const transparentRed = vscode.window.createTextEditorDecorationType({
        backgroundColor: '#ff000088'
    });
    const red = vscode.window.createTextEditorDecorationType({
        backgroundColor: '#ff0000ff'
    });

    const decorate = function() {
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            return;
        }
        editor.setDecorations(transparentRed, [new vscode.Range(215681, 0, 215681, 6)]);
        editor.setDecorations(red, [new vscode.Range(215683, 2, 215683, 7)]);
    }
    vscode.window.onDidChangeActiveTextEditor(decorate);
    decorate();
};
```

* Run a new insiders window and open a file with 215681 lines or tweak the numbers:
![image](https://user-images.githubusercontent.com/5047891/62521545-2b8b4800-b830-11e9-81ef-7483e78a4ad6.png)

Observe (via the inspector) the opacity for the first decoration is 0.533 which is 136/255 (drive by the 88 opacity).

Wait for a while and observe the cache data file:
![image](https://user-images.githubusercontent.com/5047891/62521709-77d68800-b830-11e9-9ceb-dfcce9400490.png)

![image](https://user-images.githubusercontent.com/5047891/62521739-845ae080-b830-11e9-8e79-1e089656f693.png)

* Open `index.js` in another VSCode window and change the opacity in the first color from 88 to 33

* Reload the second window
* Observe the color does not change because the cached data is not invalidated.

**Comment by jrieken** [comment]
The caching relies on file names changing (commit hash for our sources, version ids for extension sources). When files change without changing their path we rely on v8 rejecting the data. This case seems to trigger none of the bail out mechanisms: file path doesn't change, v8 doesn't reject...

**Comment by jrieken** [comment]
Now, a hash is used verify the cached data still matches the sources. Tho, this happens after the fact and *only* on the console.
