### ISSUE TITLE
highlight error when using Ctrl+T to search workspace symbols

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode#78547]
highlight error when using Ctrl+T to search workspace symbols and capture is attached. I think it highlight string 'ss' instead of 's...s'.

![20190806-170014(eSpace)](https://user-images.githubusercontent.com/39362073/62526849-a40ffa00-b86c-11e9-8ec3-41e65315cb41.png)

In addtion, I want to ask a question: Is there any way to control workspace symbols order ? I found that results aren't ordered by providerWorkspaceSymbols return-results order. I don't know how to order the results in vscode source code.

![捕ddd获](https://user-images.githubusercontent.com/39362073/62528176-fce09200-b86e-11e9-8cc6-6d8ba1c28104.PNG)

VsCode maybe show results : '2','3','1'

**Comment by IllusionMH** [comment]
VS Code uses fuzzy search that basically looks for characters in proper order and doesn't require exact substring match.
This is same as in Explorer highlights, quick open, Command palette.

I think there should be issue that asks for "exact" match.

**Comment by Lennon925** [comment]
> VS Code uses fuzzy search that basically looks for characters in proper order and doesn't require exact substring match.
> This is same as in Explorer highlights, quick open, Command palette.
> 
> So it basically highlights first two `s` characters in string, not substring `ss` in name. You'll see all strings that has 2 `s` in symbol name, and may not contain `ss` substring.
> 
> I think there should be issue that asks for "exact" match.

Are there any ways to control the results order?

**Comment by bpasero** [comment]
Yes this works as designed.

As for questions, please use: https://stackoverflow.com/questions/tagged/visual-studio-code
