### ISSUE TITLE
 javascript.validate.enable for certain folders

### ISSUE THREAD

**Issue by MrEfrem** [microsoft/vscode#78549]
Currently I have many projects in a one workspace. Some projects use Typescript JSDoc comments other use Flow. When I edit any files in Flow projects the JS linter shows many errors, therefore I should disable it. But if I will disable the JS linter then the Typescript JSDoc validation  doesn't work anymore.
Would be the best way to be able to disable/enable `javascript.validate.enable` setting in projects.

**Comment by octref** [comment]
https://code.visualstudio.com/docs/editor/multi-root-workspaces
https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings

**Comment by MrEfrem** [comment]
@octref there is no answer how can I set `javascript.validate.enable` per folders in a workspace.

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/62561640-727b3c80-b834-11e9-9036-d6cc1af31775.png)

**Comment by MrEfrem** [comment]
@octref oh yes, thanks.

**Comment by MrEfrem** [comment]
@octref only it doesn't work.
I've created folder `.vscode` in one subfolder of my workspace and I've put there `.code-workspace` file:
```
{
  "folders": [
    {
      "path": "../"
    }
  ],
  "settings": {
    "javascript.validate.enable": true
  }
}
```
But it hasn't any effect. I tried to change the folder path, I tried without the folder path. Also I even tried create the `settings.json` with content `{ "javascript.validate.enable": true }` but then the editor showed  warning me that it will be applied only when I will open this folder directly (i.e. not in my workspace).

**Comment by octref** [comment]
I think you are looking for `"javascript.implicitProjectConfig.checkJs": true`.

**Comment by MrEfrem** [comment]
@octref no, I don’t use checkJs because I have tsconfig.json in those root folders where I want Typescript check JS files. And some root folders have Flow types therefore there Typescript shouldn’t work.

**Comment by octref** [comment]
`"javascript.validate.enable": true` only enables syntactical checks. This works for me in a multi-root folder.

![err](https://user-images.githubusercontent.com/4033249/62654253-3cad8500-b914-11e9-927e-4a5b2db562f6.gif)

**Comment by MrEfrem** [comment]
@octref you show me how you change it for whole `workspace`. Though I told you about certain folders in one `workspace`. I can't set this setting at the folder level in one `workspace`. My workspace contains many `Github` repos. Some repos use Flow types other use Typescript in JSDoc comments. That type checking in `VSCode` works for `JSDocs` comments I need this setting to turn on. But because I can't turn on this setting only for certain repos in my workspace other repos which use Flow types shown with errors on Flow types annotations (because `VSCode` doesn't support Flow without separate extension). Therefore now I when edit files in a Typescript project I enable this setting but when I edit files in a Flow types project I disable it. Only it is very not comfortable because I often have are open files from both types of projects.

**Comment by octref** [comment]
I don't know why this setting is `window` scoped, meaning it can only be set in user/workspace/remote settings but not folders. Giving to @mjbvz.
