### ISSUE TITLE
soft keyboard pops up every time I click between windows

### ISSUE THREAD

**Issue by brhels** [microsoft/vscode#78551]
Issue Type: <b>Bug</b>

When I either tab between fields or click into Visual Studio Code from another application, the soft keyboard (touch keyboard, whatever its called) pops up. This started in the past month or so.

I run Windows 10 Enterprise on a touchscreen laptop.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
rest-client|hum|0.22.0
vscode-docker|ms-|0.7.0
sqltools|mtx|0.19.7
vscode-yaml|red|0.4.1

</details>

**Comment by IllusionMH** [comment]
Looks like duplicate of #76560

Which was fixed in VS Code Insiders: https://code.visualstudio.com/insiders/
Could you check that it was fixed in your case?

**Comment by brhels** [comment]
Yes the 1.37 Insiders build does not exhibit this problem. 

Sorry for the duplicate issue.
