### ISSUE TITLE
follow link issue

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#7855]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10 14366.rs1_release

Steps to Reproduce:
1. download https://github.com/ms-iot/samples/blob/develop/IotCoreService/README.md
2. open this file
3. the file contains an url at Line 24
4. set mouse cursor over url or try to open the url (ctrl +)

the last char ')' should not be part of the url...

**Comment by alexandrudima** [comment]
Nice catch! We don't count matching parens in link detection

The text is:
```
7. At this point, ServiceMain has been called.  There is no functionality presently in ServiceMain, but you can consult the [MSDN documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687414(v=vs.85).aspx) to add functionality as desired!

```

**Comment by alexandrudima** [comment]
Perhaps this can be fixed without counting brackets...
