### ISSUE TITLE
rg full cpu use

### ISSUE THREAD

**Issue by wanzhao0** [microsoft/vscode#78552]
Issue Type: <b>Performance Issue</b>

rg full cpu use

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   239	 31312	code main
    1	   261	 14352	   gpu-process
    0	    14	 21324	   electron-crash-reporter
    0	    85	 23016	   window (进程管理器)
    0	   350	 24952	   window (\defaultSettings.json ↔ \defaultSettings.json - vue-learn - Visual Studio Code [管理员])
    0	    67	 15040	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 33904	       C:\WINDOWS\system32\cmd.exe /c ""D:\nodejs\npm.cmd" run serve"
    0	    35	  2776	         "D:\nodejs\\node.exe"  "D:\nodejs\\node_modules\npm\bin\npm-cli.js" run serve
    0	     4	 27820	           C:\WINDOWS\system32\cmd.exe /d /s /c vue-cli-service serve
    0	   260	 15600	             node   "E:\��ҵ��\vue\������-vue\������Ŀ\3.��Ŀʵսday1\code\vue-learn\vue-learn\node_modules\.bin\\..\_@vue_cli-service@3.10.0@@vue\cli-service\bin\vue-cli-service.js" serve
    0	     6	 19548	     console-window-host (Windows internal process)
    0	   218	 20252	     extensionHost
    0	   228	 17912	       electron_node tsserver.js 
    0	    62	 24584	         electron_node typingsInstaller.js typesMap.js 
    0	   153	 18968	       electron_node vueServerMain.js 
    0	    51	 29648	       electron_node server.js 
    0	    48	 32124	       electron_node server.js 
    0	    41	 32344	       "D:\Microsoft VS Code\Code.exe" "d:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20252
    0	    46	 20960	     searchService
    0	    14	 22952	     watcherService 
    0	    12	  8748	       console-window-host (Windows internal process)
    0	    80	 31160	   shared-process
    1	    60	 31496	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (\defaultSettings.json ↔ \defaultSettings.json - vue-learn - Visual Studio Code [管理员])
|    Folder (vue-learn): 42 files
|      File types: vue(10) js(8) html(4) json(3) css(3) png(2) ico(1) log(1)
|                  lock(1) browserslistrc(1)
|      Conf files: package.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.29.0
javascript-vue|Dig|0.1.3
vscode-html-css|ecm|0.2.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-gutter-preview|kis|0.21.0
vscode-language-pack-zh-hans|MS-|1.37.3
vscode-typescript-tslint-plugin|ms-|1.2.2
vuejs-extension-pack|mub|1.1.5
vetur|oct|0.21.1
vuehelper|oys|0.1.0
vue-beautify|pea|2.0.4
vscode-css-peek|pra|3.0.2
vscode-essentials-snippets|rob|2.0.0
vue-vscode-snippets|sdr|1.7.1
vue-helper|she|2.1.10
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.3
vscode-icons|vsc|9.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by roblourens** [comment]
Need more details about exactly what you are doing, and what you see
