### ISSUE TITLE
Remote-SSH : Server download failed

### ISSUE THREAD

**Issue by tianlanli** [microsoft/vscode#78556]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by tianlanli** [comment]
wget: unable to resolve host address ‘vscode.cdn.azure.cn’

**Comment by roblourens** [comment]
Are you using a proxy or custom DNS configuration?

**Comment by tianlanli** [comment]
NO，I  know the resason ，thankyou , I have fixed this problem by downloading the vscode-server-linux-x64.tar.gz manually

**Comment by roblourens** [comment]
Ok, what was the reason?

**Comment by tianlanli** [comment]
my server can't connet the google
