### ISSUE TITLE
Cannot tab from a pdf file

### ISSUE THREAD

**Issue by TrustLak** [microsoft/vscode#78554]
Issue Type: <b>Bug</b>

After tabbing into a PDF file from some other file, I cannot tab back again. (Using ctrl+tab)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|7.3.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.1

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Do you mean you tabbed into another application and cannot tab back?

**Comment by TrustLak** [comment]
I mean tab within vscode (using control+Tab).  I'll see how to capture a gif and I'll post it.

**Comment by octref** [comment]
I see, you should probably open issue for https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop. I don't think they handle your shortcut in the PDF view (Webview).
