### ISSUE TITLE
[folding] shift+click should only fold inner ranges

### ISSUE THREAD

**Issue by mmahmoudian** [microsoft/vscode#78557]
In other IDEs like Rstudio Shift+click on the arrows near the line number folds the fold-able sub parts of that part.

![Peek 2019-08-06 14-34](https://user-images.githubusercontent.com/390889/62536920-e4b14880-b857-11e9-81bc-20b0756b089b.gif)

This is very handy since it only folds everything within the scope of a specific region and can help user to have a better view on the sub-parts.

**Comment by aeschli** [comment]
In VSCode, Shift + Click recursively folds the range and all contained ranges.

So for what you want you can press `Shift + Click` and `Click`

**Comment by mmahmoudian** [comment]
@aeschli your "solution" to address this works and I appreciate the suggestion and also title modification, but I think you also agree that it is very un-intuitive since achieving something should not be through doing something (recursive folding: <kbd>SHIFT</kbd>+<kbd>Click</kbd>) first and undoing something else (normal unfolding: <kbd>Click</kbd>).

I would also like to raise a point here:
recursive folding is very useless since you are folding the top level as well and you are not seeing the inner ranges to know if they are folded or not. This makes it also confusing since one cannot know if something is previously normally folded or recursively (there is no icon difference but the editor have memorized it internally!).

The _best_ solution would be <kbd>SHIFT</kbd>+<kbd>Click</kbd>:
- "fold inner ranges" if the current range is unfolded
- "open the range with inner ranges folded" if the current range is folded

This way the user don't get any surprises when unfolding a range and can control if the inner ranges should be folded or unfolded while unfolding a range.

**Comment by GustavoASC** [comment]
@aeschli do you guys of VSCode Team agree with @mmahmoudian suggestion?
Because if you agree, I can try to contribute making a pull request with this change.

It looks like a simple change at /vs/editor/contrib/folding/folding.ts file where `foldingModel.toggleCollapseState()` method is invoked.

**Comment by GustavoASC** [comment]
@mmahmoudian
I would like to point this part out:
> "open the range with inner ranges folded" if the current range is folded

I think you meant: _"open the range with inner ranges **unfolded**" if the current range is folded._
Because RStudio has this second behavior when current range is folded.

Anyway, I made these changes on my local VSCode fork and I think it's really nice. This way we have simpler control over inner ranges.

**Comment by mmahmoudian** [comment]
@GustavoASC Thanks for putting some effort into this and ultimately #86626.

Regarding your last comment, I'm a bit lost. What I was/am after is to force inner ranges ("child nodes" if we think about it as XML-like hierarchy) folded while the user is at the outer range (parent node). The logic/rationale I have is simple: codes tend to be large and typically segmented by inner ranges. The programmer would usually want to navigate through the code and understand it's structure, so it is necessary to start from abstract view (inner ranges folded) and get the general gist of what the current range is doing and then start expanding the inner ranges one by one to explore them if needed. Needless to say that a good code is well commented and has an organized structure.

I hope my brief explanation above has clarified my point.

**Comment by aeschli** [comment]
Ok, let's give this a try. I hope this doesn't break other users. We can still add an other modifier key.

**Comment by aeschli** [comment]
I made the following improvement:
- when doing shift+click and all children are already folded (or there are no children), then the current region is also folded
![shift-click-on-fold](https://user-images.githubusercontent.com/6461412/71267138-30b5e300-234a-11ea-87a3-421e826b3d1f.gif)

That way shift+click always does something and you can loop the states.

Let me know what you think.

**Comment by GustavoASC** [comment]
@aeschli Good idea!! I liked it.
