### ISSUE TITLE
vscode incorrectly states comments aren't allowed in Windows Terminal profiles.json 

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#78559]
Windows 10.0.18362.0, vscode 1.36.1, Terminal Preview 3.

vscode when editing it's own config (which allows comments in JSON)

![image](https://user-images.githubusercontent.com/172594/62541915-a49b9700-b852-11e9-9450-e11d359a80e2.png)

vscode when editing Windows Terminal profiles.json (which [allows comments in JSON](https://github.com/microsoft/terminal/issues/2292#issuecomment-518660740) )

![image](https://user-images.githubusercontent.com/172594/62541842-846bd800-b852-11e9-9c85-420e85bdcfaf.png)

vscode should not complain about the comments, when they are allowed (using whatever mechanism it uses to allow them in vscode's configs)

**Comment by octref** [comment]
You can use `files.associations` to make the file JSONC type instead of JSON.

**Comment by alexr00** [comment]
To verify, open a json file named `profiles.json` and confirm that the grammar allows comments.
