### ISSUE TITLE
Organize Imports Doesn't Respect "Groups"

### ISSUE THREAD

**Issue by chriszwickerocteris** [microsoft/vscode#78553]
Versions:

- VSCode Version: 1.37.0-Insider
- OS Version:Darwin x64 18.6.0

Description:

* When using "Organize Imports", import "groups" are ignored. Instead, each group should be treated individually, retaining import grouping.
* Comments separating groups are removed if the import following the comment is removed (it seems as if comments were assumed to be associated with the following import - that may be how some / many people work, but others use lines with only a comment as a "section title" and would add comments behind the code related to. Maybe this should be a setting?)

Steps to Reproduce:

1. In a TS source with a few imports, create 2+ groups of imports (separating them by an empty line)
2. Add a comment on the line above an unused import (add one if there is none)
3. Run "Organize Imports"

Does this issue occur when all extensions are disabled?: Yes

**Comment by chriszwickerocteris** [comment]
@mjbvz I'm afraid I don't quite understand, isn't the functionality (as it is) part of the core? And if it is, can it easily be changed by an extension (if so, would you know of an example of an extension doing a similar thing)? And if not, are you suggesting reimplementing the functionality?

Thanks!

**Comment by j** [comment]
I ran into this issue today as well.

I want to `import 'reflect-metadata'`; before anything else but it's sorting it by default causing compile errors.

How can I force specific imports to stay in place?  Grouped imports makes sense here.
