### ISSUE TITLE
Html recognition

### ISSUE THREAD

**Issue by SanthoshReddy97** [microsoft/vscode#78568]
Issue Type: <b>Bug</b>

Files with .html extension is not recognized by visual studio code instead it is  identifying as .htm 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.19.0
code-runner|for|0.9.12
ts-compile-on-save|liu|0.0.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
sublime-keybindings|ms-|4.0.3
vscode-typescript-dev|Ort|0.0.1
vscode-yaml|red|0.4.1
jinja|who|0.0.8

</details>

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/62558624-4c529e00-b82e-11e9-8ad2-74f88d36041e.png)
