### ISSUE TITLE
Pressing Tab breaks things

### ISSUE THREAD

**Issue by nic-hartley** [microsoft/vscode#78561]
Issue Type: <b>Bug</b>

1. Open a new Visual Studio Code window, not in any workspace.
2. Press Ctrl+N to open a new pane.
3. Press Tab.

Expected behavior: A tab (or equivalent spaces) is inserted.

Actual behavior: Does nothing, and then it refuses to take input until I click the text area again.

I think the text area is losing focus, but I'm not sure. Either way, sounds like someone needs to rework the pre-release test plan...

The same thing occurs with terminals, and in every other text area I try typing in.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows 10

**Comment by nic-hartley** [comment]
Okay, follow-up: This has suddenly vanished. It persisted across a reboot; then, I closed a window and opened another and it was gone. It appeared right after I got the update, so I assumed it was that, but... apparently not. Maybe a partially-applied update, or something? I have no idea, and I can no longer repro this, but I'll leave it for someone working on this to close -- maybe this'll help somehow.

**Comment by gjsjohnmurray** [comment]
@nic-hartley I am unable to reproduce this. My version info:

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

For your step 1 please launch VSCode as follows:

`code --disable-extensions`

Do you still get the problem? If not, the finger points at one or more of your extensions.

**Comment by TimCollins** [comment]
@nic-hartley Could you have accidentally hit `CTRL+M` (Toggle Tab Key Moves Focus) along with `CTRL+N`? I occasionally do that and I only realise once the prompt appears in the status bar.

**Comment by nic-hartley** [comment]
@TimCollins I disabled that shortcut after the first time I toggled it by accident, actually by miskeying Ctrl+N, so... not likely.

**Comment by octref** [comment]
Open new issue if you find repro again.
