### ISSUE TITLE
Too wide @media hover highlighting?

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#78567]
- VSCode Version: 1.36.1
- OS Version: Win10 1903

Steps to Reproduce:

1. Create css file
2. Try put cursor on `@media`
3. When we place the cursor on `div`, only` div` is highlighted, whereas when we place the cursor on `@media`, the entire range is highlighted. Is it intentional?

Example:

![99](https://user-images.githubusercontent.com/30685349/62555651-9e69e280-b873-11e9-8784-3a5017162700.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Yes that's intentional.
