### ISSUE TITLE
Blurry Terminal Console 

### ISSUE THREAD

**Issue by evanshoshan** [microsoft/vscode#78565]
Issue Type: <b>Bug</b>

I am experiencing an issue where the terminal window in VS Code will randomly get blurry as if it is being rendered in a low resolution. The issue is fixed by terminating the conosle and re-openining.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|-psn_0_217141|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.6.0
teacode-vsc-helper|App|1.2.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.4.6
gitlens|eam|9.9.3
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
comment-anchors|Exo|1.6.1
nasc-touchbar|fel|1.12.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
open-in-browser|igo|1.0.2
vscode-map-preview|jum|0.4.8
vs-color-picker|lih|1.0.0
auto-save|mcr|1.0.3
git-graph|mhu|1.12.1
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
python|ms-|2019.6.24221
csharp|ms-|1.21.0
vsliveshare|ms-|1.0.614
gradle-language|nac|0.2.3
code-spell-checker|str|1.7.17
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.2.0
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you provide a screenshot?
