### ISSUE TITLE
Debugger + NodeJS + Error Stack + SourceMaps (TypeScript)

### ISSUE THREAD

**Issue by normalser** [microsoft/vscode#7856]
It would be awesome if debugger would use source maps when outputting stack for an Error. 

Right now it will output:

```
[Error]
   {
     stack: 'TypeError: Cannot read property \'config\' of null\n 
   at null.<anonymous> (..../build/handlers/test.js:57:50) ....
```

and you can click that file name to jump to file (but it jumps to built js file - not source typescript file)

ideally if it showed: 

```
     stack: 'TypeError: Cannot read property \'config\' of null\n 
   at null.<anonymous> (..../src/handlers/test.ts:68:46) ....

```

and you could click it to go to the TypeScript source file and proper location.

Thanks

**Comment by weinand** [comment]
This feature would live in a specific debug adapter (because VS Code knows nothing about source maps).
