### ISSUE TITLE
Inconsistent tree item padding to the left

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78579]
Version: 1.37.0-insider
Commit: 5e08ee01b7daee99cdda2456f19d77e715fb8762
Date: 2019-08-05T21:16:01.319Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

---

File explorer tree:

![image](https://user-images.githubusercontent.com/4033249/62563180-4f05c100-b837-11e9-937b-f0044aae612a.png)

File explorer tree with Seti Icon theme (no folder icon):

![image](https://user-images.githubusercontent.com/4033249/62563938-c9831080-b838-11e9-8da8-608daf5bb7fb.png)

PR tree:

![image](https://user-images.githubusercontent.com/4033249/62563164-490fe000-b837-11e9-9c64-c860f7d50acc.png)

**Comment by alexr00** [comment]
@octref can you show more of the tree? We alignment differently when a node with children does and does not have an icon, so it's hard to see what's going on here.

**Comment by octref** [comment]
Sure. First picture has 3 pixels between the guide and icon. Second and third only 1 pixel.

What I think is the correct spacing:

![image](https://user-images.githubusercontent.com/4033249/62631733-0b1dc500-b8e6-11e9-9417-96a093eb37a5.png)

Change to Seti Icon theme, the spacing is very narrow:

![image](https://user-images.githubusercontent.com/4033249/62631933-71a2e300-b8e6-11e9-94db-6def1c36faf7.png)

GitHub PR extension, check out a branch. The indent guide for `azure-pipelines.yml` in the bottom tree is too narrow:

![image](https://user-images.githubusercontent.com/4033249/62632051-a878f900-b8e6-11e9-8f0d-2d025ebfddd9.png)

(https://github.com/microsoft/vscode/commit/9a2744250ca26b3fd694f44a9e00352de53280c5 for #77240 should be 5px padding, imo)

**Comment by alexr00** [comment]
@isidorn for file explorer. I don't think anything changed here, but with the guide it does look narrow.

I think the custom tree view is consistent with the file explorer with the narrow space between the guide and the icon. If the file explorer changes then I will change the custom tree to match so we can be consistent.

**Comment by isidorn** [comment]
There was some witchcraft to make this work with all the icon themes done by @aeschli and @joaomoreno 
Thus changing it for a couple of pixels might break some icon theme thus I am not keen on tackling this.

**Comment by octref** [comment]
Will give it a try with @joaomoreno when I'm done with all other items this month.

**Comment by octref** [comment]
Something changed and this is no longer an issue:

![image](https://user-images.githubusercontent.com/4033249/72882749-6bbd8480-3d03-11ea-821d-51b604cfed9d.png)
