### ISSUE TITLE
Can not install any extension

### ISSUE THREAD

**Issue by Spasley** [microsoft/vscode#78570]
Issue Type: <b>Bug</b>

I am not behind a proxy or VPN
Dev tools console does not show any errors
In network tab all requests are 200 OK
I see an extensions but when I click "Install" I just start watching blue bar rolling left to right

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by octref** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release.

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.

**Comment by Spasley** [comment]
@octref I can access the image. Anyway I tried to set DNS server to 1.1.1.1, but extensions still does not load

**Comment by Spasley** [comment]
@sandy081 Output of F1 -> View: Open View -> Log (Shared):
```
[2019-08-11 22:42:28.990] [sharedprocess] [info] main {"machineId":"79d3c06183f5054f009de3a68cc702780af58b865bf4aa5af03cdfb4942313ea"}
[2019-08-11 22:42:31.670] [sharedprocess] [info] Installing extension: ms-python.python
[2019-08-11 22:43:08.999] [sharedprocess] [info] Starting to clean up unused language packs.
[2019-08-11 22:44:27.411] [sharedprocess] [info] Installing extension: ms-vscode.cpptools
```
Nothing happens then.

VS Code by link https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe seems the same version (letest) what I try to use. I did quick look but did not find previous release

**Comment by Spasley** [comment]
@sandy081  Update here, I found that version 1.37 is available. There in the logs I see
```
[2019-08-11 22:52:05.076] [sharedprocess] [info] main {"machineId":"79d3c06183f5054f009de3a68cc702780af58b865bf4aa5af03cdfb4942313ea"}
[2019-08-11 22:52:07.897] [sharedprocess] [info] Installing extension: ms-python.python
[2019-08-11 22:52:08.754] [sharedprocess] [error] Failed to install extension: ms-python.python Unable to write file (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, mkdir 'c:\temp;C:')
```
C:\temp exists. May be the issue is that somewhere in the settings I set lowercased 'c' as path?

**Comment by sandy081** [comment]
@Spasley Please update your temp folder location to `c:\temp`. You cannot have multiple values for it.

**Comment by Spasley** [comment]
@sandy081 yesterday when I found 1.37 version of VS Code I did search over preferences by strings 'c:\temp', 'c:\temp;C:', 'temp', 'temporary' but did not find where it is set. Where can I change this path?

**Comment by sandy081** [comment]
Its an environment variable in your windows box. Please look for changing temp location in windows.
