### ISSUE TITLE
[js] highlight break

### ISSUE THREAD

**Issue by biaocy** [Microsoft/vscode#7858]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce(disable extension):

![image](https://cloud.githubusercontent.com/assets/7885426/16175072/699206a2-3615-11e6-846c-cbdf73dd6d77.png)

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/167
