### ISSUE TITLE
Allow to set tab size based on file type

### ISSUE THREAD

**Issue by HappyTreesDev** [microsoft/vscode#78593]
Often I am working between js files and css files and I would like to have my js files have a tab width of 4 spaces while my css files have a tab size of 2 spaces. As it sits, this is not possible to set and I have to either detect the tab size when switching to a different file or just deal with it. the detect tab size when looking at files side by side does not work and I have to retrigger the check every time.

**Comment by ArturoDent** [comment]
See https://stackoverflow.com/questions/34247939/how-to-set-per-filetype-tab-size .  This doesn't work for you?
