### ISSUE TITLE
emmet not working

### ISSUE THREAD

**Issue by calrunion** [microsoft/vscode#78592]
Issue Type: <b>Bug</b>

the subject says it all

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.39GB (24.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
Angular-BeastCode|Mik|8.0.10
vscode-jsp|pth|0.0.2
vscode-nginx|sha|0.6.0
vscode-scss-formatter|sib|1.4.1
vscode-icons|vsc|9.2.0

</details>

**Comment by kanlukasz** [comment]
1. In what type of file you tested it?
2. Does this issue occur when all extensions are disabled?
3. Did you tried reproduce this with Vscode Insider version?

**Comment by calrunion** [comment]
Whoops, this extension was actually causing the issue.Thx
[image: image.png]

**Comment by kanlukasz** [comment]
Ok, please close the issue if you think it is solved. Thanks

**Comment by calrunion** [comment]
Closing this issue. Java Server Pages (JSP) was causing emmet to not work as if writing HTML.
