### ISSUE TITLE
IntelliSense for language settings in settings.json

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#78591]
It'd be useful to have IntelliSense for all language IDs when adding language-specific settings manually (as opposed to only showing IDs for those settings that already exist).

In other words, all language IDS that show up when using the `Preferences: Configure Language Specific Settings` command should also show up when manually adding those settings.

Notice in the screenshot that `typescript` is not available from the IntelliSense list, for example.

Language setting related issues: #58995 and #74195

<img width="1280" alt="example" src="https://user-images.githubusercontent.com/12591890/62569379-25a75e00-b854-11e9-9055-60a3c620709d.png">

**Comment by usernamehw** [comment]
Possible duplicate of #48317
