### ISSUE TITLE
code shell command hangs in WSL 2

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#78596]
- VSCode Version: 1.36.1
- OS Version: Windows 10 Insiders (18950)

Steps to Reproduce:

Note: requires Windows Insiders.

1. Enable WSL 2 (`$ wsl --set-version Ubuntu-18.04 2`)
2. Attempt to launch VS Code from the shell using `$ 

**Expected:**

VS Code opens the current directory.

**Actual:**

The shell command is unresponsive and never launches.

Does this issue occur when all extensions are disabled?: Yes

**Comment by nicoabie** [comment]
Are you launching it from /mnt/c folder?

**Comment by fiveisprime** [comment]
No. I'm working in directly within Linux so the path is `\\wsl$\Ubuntu-18.04\home\fiveisprime\src\`

I just tried opening a directory in `/mnt/c` and it also hangs.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/77898
