### ISSUE TITLE
Failing test: Disk File Service move - directory - across providers (ubuffered - buffered)

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78602]
I've skipped this test on Linux, as it has failed a build: https://github.com/microsoft/vscode/commit/074e1bb82ffd3ffa54fceff75786ad9ab94107db

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=53792

**Comment by bpasero** [comment]
Added retry support for file based tests.
