### ISSUE TITLE
Saving a fs.watch()'d rapidly empties source file, but only in VSCode?

### ISSUE THREAD

**Issue by renotoaster** [microsoft/vscode#78601]
- VSCode Version: 1.36.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Create 2 files, `index.js` and `source.txt`
2. Edit them like so:
```javascript
// Index.js 
const fs = require('fs')
const sourcePath = './source.txt'
const targetPath = 'target.txt'

fs.watch(sourcePath, (e) => {
  fs.copyFile(sourcePath, targetPath, (err) => {
    console.log('error?', err)
  })
})

// source.txt
foobarbaz // any content will do
```
3. Start `node index.js`
4. Edit `source.txt` and verify `target.txt` is created
5. Rapidly save (~5 times per second, or as fast as you can) `source.txt` (no need to edit in between)
6. After 2-5 saves `source.txt` is cleared of all content, and `Failed to save 'source.txt': Unable to write file (Unknown (FileSystemError): Error: EBUSY: resource busy or locked,` appear in VSCode (and sometimes in the above started node process log)

Does this issue occur when all extensions are disabled?: Yes

In essence the copy operation should be done by the node process, so it's unclear why VSCode has trouble with reading/editing the file when other editors do not.

My guess is that VSCode cannot read the source file, clears the editor, and resaving is somehow impossible, as trying to keep saving the file keeps resulting in the same error.
This doesn't happen with another editor, for example with notepad. Replicated on colleague's PC (same OS).

Even though the issue would seemingly lie in the started node process, this only manifests in VSCode (at least on Windows), and hence I'm filing this issue.

**Comment by bpasero** [comment]
@renotoaster this error is not coming from VSCode but from node.js so I would suggest you try to reproduce with a standalone node.js sample. E.g. add code that simulates the writing that VSCode does.

Btw I think it is a known issue that watching on Windows locks file resources. At least for folders that is true.

**Comment by renotoaster** [comment]
I did, with the notepad version. I'm not sure how to simulate "how VSCode writes it" to get enough understanding if there's something VSCode can do to mitigate this (it can't really override the OS behaviour).

I acknowledged beforehand that this might not be something VSCode can affect even if it manifests in it (as it's the node process that does the actual (b)locking), so do close/keep this open at your discression.

**Comment by bpasero** [comment]
@renotoaster you can start with `fs.writeFile` to fill the file. Or `fs.createReadStream(source).pipe(fs.createWriteStream(target))`.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
