### ISSUE TITLE
workbench.startupEditor cannot be applied in workspace settings

### ISSUE THREAD

**Issue by jsondoo** [microsoft/vscode#78604]
Trying to override user settings for `workbench.startupEditor` through workspace settings gives a warning saying "This setting can be applied only in application user settings". 

From the docs: https://code.visualstudio.com/docs/getstarted/settings, it mentions that 
> Workspace settings override user settings.

Is there a reason this setting does not follow that rule? Is there a way to get around this? It would be a nice addition to be able to customize what opens up at the start up such as README based on workspaces settings.

**Comment by bpasero** [comment]
Yes, we do not want to allow a specific workspace to override this setting and force opening its readme when you use VSCode.
