### ISSUE TITLE
Word Wrap/Horizontal scroll on Debug Screen

### ISSUE THREAD

**Issue by rougiain** [microsoft/vscode#78608]
Issue Type: <b>Bug</b>

When debugging, the name of a variable or watch expression can exceed the width of the watch or variable sections, making it hard to see values at a glance.

Options to fix:
* limit column width of variable/watch expression so value shows.
* word wrap the expression/name  
* Horizontal scroll bar

![image](https://user-images.githubusercontent.com/19661735/62608004-509abc00-b8ff-11e9-9aea-6ba4620e804a.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|-psn_0_200753|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.4.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
extbundles-csharp|Fel|2.0.0
auto-using|Fud|0.7.9
todo-tree|Gru|0.0.139
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.8
csharpfixformat|Leo|0.0.83
code-bitbucket-pipelines|luk|0.4.2
vscode-docker|ms-|0.7.0
csharp|ms-|1.21.0
css-grid-snippets|oha|0.0.5
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.4.1
html5-boilerplate|sid|1.0.3
msbuild-project-tools|tin|0.2.55
vscode-icons|vsc|9.2.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Set this setting:
`"workbench.list.horizontalScrolling": true`
