### ISSUE TITLE
"scm.diffDecorations" does not work in workspace.

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/vscode#78603]
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18 LTS

Steps to Reproduce:
add 
{
   "scm.diffDecorations", "none"    
}

to settings.json of a workspace.

Observed:
The setting does not work in workspace. The setting only works in global setting.

Expected:
The setting work in workspace.

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9527KGG** [comment]
Thanks. Do you know when/which version will have the fix?

**Comment by joaomoreno** [comment]
The August release should come in a month from now, or tomorrow on [Insiders](https://code.visualstudio.com/insiders)?
