### ISSUE TITLE
Format On Save not triggered when switching tabs and Auto Save set to onFocusChange

### ISSUE THREAD

**Issue by fabb** [microsoft/vscode#78605]
- VSCode Version: 1.36.1 
- OS Version: macOS 10.14.6 (18G87)

Steps to Reproduce:

1. In settings, activate "Format On Save", and set "Auto Save" to "onFocusChange"
2. Install the Prettier extension (esbenp.prettier-vscode)
3. Open 2 editors, and in one (js/ts file) make some changes that are not pretty formatted
4. Switch editor tabs with Ctrl+Tab

Expected outcome: the file is formatted with prettier and saved.

Actual outcome: the file is saved as-is.

Does this issue occur when all extensions are disabled?: No because I do code formatting with Prettier.

**Comment by jrieken** [comment]
Hm, that's actually my self host setup and I see formatting happening when saving. Does this reproduce with the default formatter? E.g disable prettier-vscode, check that formatting works when trigger manually, and then try the format-on-save flow

**Comment by fabb** [comment]
I could not reproduce it with the default formatter.

With the prettier formatter, it seems to be a race condition. When I switch tabs VERY quickly with Ctrl+Tab it often does not format. See 3rd time in the gif:

![ezgif-1-471894e090a0](https://user-images.githubusercontent.com/153960/62758347-6e425f80-ba7e-11e9-9ee8-7823a0ac80a8.gif)

**Comment by jrieken** [comment]
Is there anything in the log (F1 > Show Logs> Window) or the dev console (F1 > Developer Tools > Console)?

**Comment by fabb** [comment]
No output in the window log. I don't have the Developer Tools > Console, but if you mean the Debug Console or the Terminal, nothing in both either. And nothing in the Prettier output log.

Funny in the demo project: Currently I can only reproduce it very rarely (but still), even under high cpu. This was different when I made the video above. But in my big real project, it's always reproducible, even with very low cpu load. I also tried deleting the `.git` folder of my big project, just in case the built in git plugin causes issues, but no changes.

**Comment by jrieken** [comment]
>  I don't have the Developer Tools > Console,

You do

<img width="1222" alt="Screenshot 2019-08-22 at 11 59 54" src="https://user-images.githubusercontent.com/1794099/63505766-65b54480-c4d4-11e9-946b-07daa629e205.png">

**Comment by fabb** [comment]
Ah interesting. But no, no output there at all either.

**Comment by jrieken** [comment]
Well, there is nothing I can do here. It's likely an extension issue (see https://github.com/microsoft/vscode/issues/78605#issuecomment-519794854) so please follow up with the extension author
