### ISSUE TITLE
search using regex matches unmatched lines

### ISSUE THREAD

**Issue by MaysonChen** [microsoft/vscode#78607]
- VSCode Version:1.36.1
- OS Version:win10

Steps to Reproduce:

1.search something in the target folder
2.try to use `type [a-z][a-zA-Z]+` to match lines like `type response`, but `type Cookie` matches,too

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You need to set the case sensitive flag for the search to be case sensitive, did you do that?
