### ISSUE TITLE
Line ending resets to CRLF

### ISSUE THREAD

**Issue by Rafi993** [microsoft/vscode#78600]
Issue Type: <b>Bug</b>

I do use VScode in a repo both in Linux and Windows I did change line ending to LF in windows both on settings and on the file while editing it. But if I make some changes in Linux and push it to git and pull it back it in Windows VScode opens up the file as CRLF again.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
Likely due to your git settings, not VS Code?
https://help.github.com/en/articles/configuring-git-to-handle-line-endings
https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings
