### ISSUE TITLE
Outline empty using --goto

### ISSUE THREAD

**Issue by Totoditoto** [microsoft/vscode#78612]
When opening certain files with code --goto, the Outline pane is empty saying "No symbols found in document". Outline is populated when opening same files without --goto.

Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
