### ISSUE TITLE
make a default shortcut to "debug evaluate"

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/vscode#78613]
in python extension:
we have def shortcuts to run selected lines in terminal & in interactive mode, but no shortcut for "debug evaluate".
This shortcut is really helpful when debugging python data science scripts. In PyCharm the def shortcut for this is alt+shift+e (but maybe it can be done easier...)

**referenced** from [here](https://github.com/microsoft/vscode-python/issues/6675)

**Comment by isidorn** [comment]
You can just add a shortcut to debug evaluate.
This command is not that common to deserver a default shortcut imho.
Also if the python extension decides to change this they can add a default shortcut through their extension. I will also reply on the issue in the python extension.
