### ISSUE TITLE
Sub-folder not showing in explorer view when using "Open folder..."

### ISSUE THREAD

**Issue by tjansson** [microsoft/vscode#78618]
Issue Type: <b>Bug</b>

When opening a folder to use as my workspace, certain sub-folders are not shown in the explorer.

This is the folder structure shown in the "Open Folder" dialog:
![bilde](https://user-images.githubusercontent.com/209188/62620467-b09e5c00-b919-11e9-82be-d590198a4d61.png)
Note the presence of a CVS folder.

This is the explorer view once the folder has been opened:
![bilde](https://user-images.githubusercontent.com/209188/62620498-c14ed200-b919-11e9-80de-b81405ad89f1.png)
Note that the CVS folder is now missing.

---

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.38GB (17.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.46
theme-verdandi|be5|1.10.1
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-simpler-icons|dav|1.6.5
ini-for-vscode|Dav|0.0.4
gitlens|eam|9.9.3
vscode-great-icons|emm|2.1.47
file-icons|fil|1.0.17
code-runner|for|0.9.12
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
nsis|idl|3.17.0
easy-icons|jam|0.3.1
vscode-simple-icons|Lau|1.11.9
theme-monokai-pro-vscode|mon|1.1.13
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
powershell|ms-|2019.5.0
color-highlight|nau|2.3.0
markdown-preview-enhanced|shd|0.4.3
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.17
ayu|tea|0.18.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.2.0
city-lights-icon-vsc|Yum|1.1.3
vscode-proto3|zxh|0.3.0

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Could you check if your User or Workspace settings have `CVS` in `"files.exclude"`?

I think it is ignored by default
![image](https://user-images.githubusercontent.com/1312662/62624825-9de15280-b92c-11e9-9338-e44889d35011.png)

**Comment by tjansson** [comment]
That solved my issue, so not a bug then. I was not aware of this setting, and how it affected the explorer view. My bad. Anyway, thanks for your help!
