### ISSUE TITLE
Pin debugger to one editor group

### ISSUE THREAD

**Issue by MaliusArth** [microsoft/vscode#78615]
I have a couple tabs in separate tab groups with the file pointers at certain lines of the files or scrolled to certain lines. When I step wise debug through the code the focus jumps from tab group to tab group and jumps to different lines in those files messing up the view of multiple files related to my task. I would like to have one dedicated tab group for the debugger to do its thing without messing up my workspace.

**Comment by isidorn** [comment]
Well if you have 
`	"workbench.editor.enablePreview": true`
All the new files that get opened through debugging will get opened in preview tabs, and they should not mess up with your layout.
If you have an exact example where debugger opens a file where it should not let us know and we can try to improve that.

Having debugger related files open in one editor group I can leave open as a feature request, though we have no plans to tackle this currently thus assigning to backlog.

**Comment by MaliusArth** [comment]
previews only open for files which are not already opened (closed files), when the files are already opened they get reused by debuggers
