### ISSUE TITLE
Please provide Code Conflict error during Deploy code

### ISSUE THREAD

**Issue by shahpathik81** [microsoft/vscode#78617]
Issue Type: <b>Feature Request</b>

Hello,

I am a salesforce Developer. From last 3 years i used Mavensmate and sublime text for salesforce project editor purpose. But now mavens no more longer support to Mavensmate. So i try to user frieldly with VS Code. But now i got Big Problem faced during Implementation that VS can not show Code Conflict error throw. It shows and compare with Highlight of server copy and change copy.
If some changes in server copy code then VS code Deploy that code without throw any error. That is Big Problem to any salesforce developer that changes that code.
Please add this functionality in VS Code.

Please Contact me on Below Mention Email Id:
shahpathik81@gmail.com
pathik.shah@softwebsolutions.com

Contact - +91 9033427787

Thanks:
Pathik Shah

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.14393

**Comment by gjsjohnmurray** [comment]
@shahpathik81 I guess that what you call "Deploy code" may be a feature of a Salesforce-specific VSCode extension you are using. In that case you need to log this issue with the extension provider.
