### ISSUE TITLE
Terminal: shift dragging causes lots of console errors

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78614]
On Linux (maybe tmux only?)

1. Open Terminal
2. Reload workbench
3. Shift click and drag in the terminal

This doesn't repro if I *first* click into the terminal and *then* shift click&drag.

![image](https://user-images.githubusercontent.com/22350/62614664-2996b700-b90c-11e9-90ce-54a264ac51a2.png)

**Comment by Tyriar** [comment]
This appears to only happen if you have not made any selection yet, so it's not that big of a deal. Fixing in August.
