### ISSUE TITLE
VS code crashing(Window has crashed)

### ISSUE THREAD

**Issue by Autumnwinter** [microsoft/vscode#78616]
Issue Type: <b>Bug</b>

This happens only when opening java file.
Try to open any java file from the java project it crashes every time

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|1.0.120190715
docs-yaml|doc|0.2.3
docker-explorer|for|0.1.6
shell-format|fox|6.1.1
vscode-javac|geo|0.2.21
cloudcode|goo|0.0.11
azure-pipelines|ms-|1.155.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.29288
vscode-ai|ms-|0.5.1
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
team|ms-|1.149.2
java|red|0.47.0
vscode-yaml|red|0.4.1
java-checkstyle|tho|1.1.1
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-debugger-azds|vsc|0.2.2
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by octref** [comment]
Can you start by opening issues for the Java extension? Thanks.
