### ISSUE TITLE
Move editor.fastScrollSensitivity and editor.mouseWheelScrollSensitivity into workbench namespace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78626]
This came out of the discussion in https://github.com/microsoft/vscode/issues/78431

We have these editor namespace settings that should live in workbench as `fastScrollSensitivity` already works in the tree and I want to add it to the terminal. We need to figure out a migration story as part of this. Maybe we should introduce setting aliasing with warnings to give us a way to move these and future settings around?

**Comment by bpasero** [comment]
I do not know what exactly the outcome should be but I think this sounds like a feature request and I will assign you to make a PR which either @sandy081 or me can review 👍

**Comment by Tyriar** [comment]
I'm not planning to work on this, seems more like UX or debt item to fix up the namespaces imo. The terminal will just be using `editor.fastScrollSensitivity` in the meantime just like it falls back on `editor.fontFamily`.

**Comment by bpasero** [comment]
I think that is OK given that most people refer to VSCode as being an "editor".
