### ISSUE TITLE
vs code fails to install extensions

### ISSUE THREAD

**Issue by shico24** [microsoft/vscode#78620]
vs code fails to install or download extensions

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo - please see https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions for guidance about how to do this.

**Comment by octref** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release. Here is  windows user installer (Let me know which platform are you on will provide the corresponding VS Code installer)

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.
