### ISSUE TITLE
No auto-suggest for React components' props interface

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#7862]
- VSCode Version: 1.3.0-insider
- OS Version: macOS 10.11.5
- TypeScript versions: 1.8.10 and 1.9.0-dev

Steps to Reproduce:

1. Declare an interface to define a React component's props.
2. There's no suggestion for the interface while declaring the component's `props` generic.
3. The interface name *is* available for auto-complete inside the component body itself and works as expected.
4. A similarly declared interface for the state *is* suggested.

![image](https://cloud.githubusercontent.com/assets/390540/16175849/ef14c4e6-3619-11e6-82ff-7a1be9530b2d.png)

![image](https://cloud.githubusercontent.com/assets/390540/16175855/0f474fa4-361a-11e6-927e-e72813d67162.png)

**Comment by dbaeumer** [comment]
Moving to TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9275
