### ISSUE TITLE
Problem with Conda

### ISSUE THREAD

**Issue by RMeli** [microsoft/vscode#78623]
When I open a new VSCode window and then open a new terminal, the following commands work as expected:
```
$ conda activate testenv
$ python --version
Python 3.6.8 :: Anaconda, Inc.
```
Then, I open a Python file (`.py`) and select the correct Python environment in VSCode (`Python 3.6.8 64-bit ('testenv': conda)`). If I now open a new terminal, the following problem occurs:
```
source /biggin/b195/lina3015/miniconda3/bin/activate
conda activate gsoc                                                                                                                                                
$ source /biggin/b195/lina3015/miniconda3/bin/activate
activate does not accept more than one argument:
['is_csh', '=', '123']
```
And the `conda` environment is stuck to the one loaded by default in my `.zshrc` (and not the one correctly selected via VSCode). Even more concerning, the following (which was working on the first terminal) does not work anymore:
```
$ conda activate testenv
$ python --version
Python 3.7.1
```
i.e. the Python interpreter remains stuck to the one 

I saw that many `conda`-related issues have been closed recently, but this one persists.

- VSCode Version: 1.37.0-insider
- OS Version: Ubuntu 18
- Shell: ZSH
- Conda: 4.7.5

Steps to Reproduce:

1. Open the terminal in a new VSCode window
2. Open a Python file and load the correct Python extension (from a `conda` environment)
3. Open a new terminal

The following error appears on the freshly open terminal:
```
activate does not accept more than one argument:
['is_csh', '=', '123']
```

Does this issue occur when all extensions are disabled? The Python for VSCode extension is required in order to activate the Python environment.

**Comment by octref** [comment]
Please report to here: https://github.com/Microsoft/vscode-python
