### ISSUE TITLE
Indention error

### ISSUE THREAD

**Issue by mythio** [microsoft/vscode#78628]
- VSCode Version: 1.36.1
- OS Version: Deepin 15.11

Steps to Reproduce:

1. Open a cpp file
2. Set the tab width to 4 spaces
3. Press `ctrl+shift+i` to indent the code
4. The indentation is set to 2 automatically

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Report to https://github.com/microsoft/vscode-cpptools.
