### ISSUE TITLE
remote ssh's terminal in mac cant support Chinese

### ISSUE THREAD

**Issue by Handsomer** [microsoft/vscode#78621]
Issue Type: <b>Bug</b>

1、 can edit Chinese language in my Mac.
2、 also can do in my google machine(by ssh connect in mac terminal)
3、 but In VS code's remote terminal cant do this : can edit English cant edit Chinese. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.3.0
Remote OS version: Linux x64 4.15.0-1033-gcp

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: google_machine|
|OS|Linux x64 4.15.0-1033-gcp|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (1 x 2200)|
|Memory (System)|3.61GB (0.79GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.37.3
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
code-gnu-global|aus|0.2.2
json-tools|eri|1.0.2
python|ms-|2019.8.29288
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.24.1
team|ms-|1.149.2

</details>

**Comment by roblourens** [comment]
Can you explain exactly what the problem is? Why can't you edit chinese?

**Comment by Handsomer** [comment]
scenes to be used:
When I open the vscode in the macbook pro, use the remote ssh plugin to connect to the remote server, open the C++ project, and use git to submit the code in the terminal below the vscode.
I need to use this command: git commit -m "here is Chinese", the Chinese part does not display properly
![8月-08-2019 13-25-36](https://user-images.githubusercontent.com/10918610/62677217-2a991880-b9e0-11e9-9f9d-1be5f1acc61b.gif)

**Comment by Tyriar** [comment]
Can you run `echo $LANG` in a local vscode terminal and a remote vscode terminal and paste in the result?

Also Can you share your settings.json file?

**Comment by evedark1** [comment]
I also have the same bug on windows 10. I use the git bash and git ssh.
My settings.json have set this:
```
"terminal.integrated.shell.windows": "D:\\tools\\Git\\bin\\bash.exe",
"remote.SSH.path": "D:\\tools\\Git\\usr\\bin\\ssh.exe",
```
LANG in local terminal and remote terminal is "zh_CN.UTF-8"

I have try to use windows openssl, bug have the same question.
