### ISSUE TITLE
Snippets in Debug Console

### ISSUE THREAD

**Issue by Venipa** [microsoft/vscode#78622]
Issue Type: <b>Bug</b>

![Image](https://i.mavis.moe/f/RCmKz03Lj5/code-2019-08-07-15-01-48.png)

Once i press `ctrl + space` snippets are displaying in the debug console.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18941

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (89)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
Bookmarks|ale|10.4.4
ng-template|Ang|0.801.1
angulardoc-vscode|Ang|6.1.3
vscode-mjml|att|1.6.0
vscode-custom-css|be5|3.0.4
vscode-icontheme-nomo-dark|be5|1.3.6
google-translate-ext|ben|1.3.1
vscode-intelephense-client|bme|1.1.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular2-snippets|dan|1.0.21
vscode-markdownlint|Dav|0.29.0
jshint|dba|0.10.21
githistory|don|0.4.6
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.0
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
windows-explorer-context-menu|ele|2.0.0
spfx-debug|eli|0.0.3
spfx-essentials|eli|5.0.0
spfx-snippets|eli|1.7.1
vscode-spfx-localization|eli|1.2.2
vscode-spfx-remove-components|eli|1.0.0
vscode-spfx-task-runner|eli|1.2.4
vsc-material-theme|Equ|29.2.0
prettier-vscode|esb|1.9.0
auto-using|Fud|0.7.9
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
vscode-test-explorer|hbe|2.14.1
discord-vscode|icr|3.8.1
vscode-gnupg-tool|JHe|1.2.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.0.1
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.8
auto-comment-blocks|kev|1.0.1
csharpfixformat|Leo|0.0.83
vscode-csproj|luc|0.7.0
json-to-ts|Mar|1.5.5
csharpextensions|mav|1.3.0
Angular-BeastCode|Mik|8.0.10
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.13
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
python|ms-|2019.8.29288
remote-containers|ms-|0.66.0
remote-ssh|ms-|0.44.2
remote-ssh-edit|ms-|0.44.2
remote-ssh-explorer|ms-|0.44.2
remote-wsl|ms-|0.38.10
vscode-remote-extensionpack|ms-|0.15.0
azure-account|ms-|0.8.4
csharp|ms-|1.21.0
powershell-preview|ms-|2019.5.0
vscode-typescript-next|ms-|3.6.20190806
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.614
debugger-for-chrome|msj|4.11.7
vscode-react-native|msj|0.10.2
resourcemonitor|mut|1.0.6
angular2-inline|nat|0.0.17
angular-console|nrw|8.0.10
vetur|oct|0.21.1
vscode-jest|Ort|3.0.2
material-icon-theme|PKi|3.8.1
quicktype|qui|12.0.46
vscode-yaml|red|0.4.1
rencore-tenant-wide-spfx-extension-deployment|Ren|1.0.2
vscode-spfx-deploy-package|Ren|1.1.0
vscode-spfx-script-check|Ren|1.1.0
vscode-jest-test-adapter|rtb|0.2.0
svg-preview|Sim|2.5.7
spgo|Sit|1.4.3
vscode-taskexplorer|spm|1.19.3
code-spell-checker|str|1.7.17
code-spell-checker-german|str|0.1.2
ayu|tea|0.18.0
msbuild-project-tools|tin|0.2.55
vscodeintellicode|Vis|1.1.8
vscode-nginx|wil|0.7.1
html-css-class-completion|Zig|1.19.0

(23 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
The contents of the debug console suggesstions are coming from the debug extension.
Thus please file this against the debug extension you are using.
For example the issue you are showing is not present in node debugging.
