### ISSUE TITLE
Terminal: resets history when Toggle Maximized Panel

### ISSUE THREAD

**Issue by JasonDickens** [microsoft/vscode#78634]
Issue Type: <b>Bug</b>

Using Powershell as terminal:
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
"powershell.integratedConsole.showOnStartup": false,

1. Shrink terminal down to only displaying seven lines of text.
2. Change directory to a path that has many folders
3. Type dir
4. Scroll in the terminal and verify there is a long history.
5. Click Maximize Panel Size, or use keyboard shortcut to Toggle Maximized Panel
6. Observe you are no longer able to scroll up to view the console history.

Expected behavior: Console "top" is not reset and all output can be viewed
Actual behavior: Console history is lost.

This used to work correctly several versions ago and console history was preserved when the console was toggled. I use this by keeping my build watchers running in a small window at the bottom while I code and a hotkey to toggle the console maximize when I need to see the results of the watchers. Normally, I only need to see 3-4 lines when the watchers succeed, then when there's an error, I can toggle the maximize and scroll back to see the results. With this bug, my workflow is hindered greatly as I have to keep a separate console open and alt-tab over and over to see the results.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
![vscodeBug](https://user-images.githubusercontent.com/12192719/62632609-9ba8d500-b8e7-11e9-94d7-a33926267a90.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (41.13GB free)|
|Process Argv|C:\g\PowerBIClients2\src|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
gitlens|eam|9.9.3
pbi-vscode-tools|Mic|0.0.14

</details>

**Comment by Tyriar** [comment]
Looks like this is an issue with windows mode in xterm.js, we should not try to push the rows down when in windows mode like we do on *nix because conpty will redraw the screen and it always has overscroll. The edge case when the buffer is full might need to behave differently though.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/xtermjs/xterm.js/issues/2459
