### ISSUE TITLE
Need a way to force-refresh Quick Open index

### ISSUE THREAD

**Issue by lunelson** [microsoft/vscode#78632]
In a workspace with multiple folders, after I recently moved a folder on disk, removed it from the workspace and re-added it from a new location, Quick Open is "polluted" with paths from the old folder whenever I type the name of a file. 

I would like to have a command to simply rebuild the Quick Open index completely.

**Comment by chrmarti** [comment]
The index is rebuilt each time you use Quick Open, you see the old index while the new one is being built.

You likely see the file history. Does the `File: Clear Recently Opened` command help?

**Comment by lunelson** [comment]
Thanks, I never tried that command, only the ones with "Refresh" in the name; but I suspect it's the wrong tack. None of the files I'm seeing in `Quick Open` ever showed up in `Open Recent`. I can't verify at the moment if it helped the original problem because those results have slowly started to disappear; but it has had the unfortunate side-effect of wiping out my recent folders and workspaces. 

I guess another way of putting this question is "is there a way to restrict Quick Open results to only contain files which are in the current folder / workspace"? Or in fact "why would files show up in Quick Open which are not part of the current workspace or folder?"

**Comment by chrmarti** [comment]
If you still had editors open of the already deleted files, those files would still show up. Closing all editors would fix that.

**Comment by lunelson** [comment]
No that wasn't it, it was a single workspace, with no other windows open. I can't reproduce right now, perhaps in the meantime the file list was purged on its own. I'll reopen this at some point if I can isolate the behaviour...🤷🏻‍♂️
