### ISSUE TITLE
Python REPL history doesn't work when running via 'py' command in a virtualenv

### ISSUE THREAD

**Issue by michaelkolber** [microsoft/vscode#78639]
Issue Type: <b>Bug</b>

**Steps to Reproduce:**

1. Create a new virtualenv
2. Activate the virtualenv
3. Start the Python REPL using `py`
4. Type a few commands
5. Hit the up/down keys. It does not show previous history.

**Details:**

- This does not happen when you launch via `python`.
- This does not happen when the virtualenv is deactivated.
- This does not happen when using a normal Powershell or Command Prompt window.

**Does this issue occur when all extensions are disabled?:** Yes

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31245 @ 3.30GHz (8 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
gitlens|eam|9.9.3
pyright|ms-|1.0.52
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
vscodeintellicode|Vis|1.1.8

</details>

**Comment by Tyriar** [comment]
The fact that this doesn't happen when you run `python` says to me it's an issue with `py`, the command history is also maintained by the application, it's nothing to do with vscode.

**Comment by michaelkolber** [comment]
@Tyriar The `py` launcher works fine in all other consoles, including PS, CMD, and emulators such as ConEmu. It also works fine when running on Linux via Windows Subsystem for Linux. Furthermore, hitting the up/down keys clears whatever is written in the console, which is not standard behavior under any build? Is it possible that vscode is sending an incorrect signal to the shell?

If not, do you have any information I can give when filing an issue with `py` or `venv` other than "It does not work specifically with vscode"?

**Comment by Tyriar** [comment]
Some things you could try:

- Update Windows to 1903, that will move you to the new/supported backend conpty
- After updating, checking if you can repro it under [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701)
