### ISSUE TITLE
Windows file explorer of project not getting refreshed

### ISSUE THREAD

**Issue by imsushil** [microsoft/vscode#78636]
Issue Type: <b>Bug</b>

Hello,

Whatever changes I'm making in the files of my project in visual studio code, it is not reflecting in the windows file explorer of the same project. 

The modified dates of the files in my project in the file explorer is still showing the last date and time when I had cloned the project.
Can you please look into this issue? 

Thanks.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.801.1
vscode-color|ans|0.4.5
angular-schematics|cyr|1.23.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.0.1
rainbow-csv|mec|1.2.0
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.2.2
material-icon-theme|PKi|3.8.1
angular-template-formatter|str|0.1.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@imsushil this does not sound like an issue with VSCode but the windows explorer not showing up to date information?
