### ISSUE TITLE
Add a decoration render option to extend to edge of window but keep range

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#78640]
In

https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions

there is already a flag `isWholeLine` which extends the range across the full width of the window. It would be nice to have another similar option, which extends a multi-line range to the end of the window, but does not extend the start of the range to the beginning of the line, or the end of the range to the end of the line - just the intermediate lines.

e.g.

Current behaviour:
```
........{......................
...............................
........}......................
```
```
........{.............}........
```

Desired behaviour:
```
        {......................
...............................
........}
```
```
        {.............}
```

**Comment by alexandrudima** [comment]
@Gruntfuggly You can use 3 decorations on your side to simulate this.

**Comment by Gruntfuggly** [comment]
True. Would still be a nice option though if anybody is making changes in that area. :smile:
