### ISSUE TITLE
Unable to create breakpoints by clicking next to the line number

### ISSUE THREAD

**Issue by jens1o** [microsoft/vscode#78645]
Issue Type: <b>Bug</b>

1. Open a file in the editor (e.g. an JavaScript file)
2. Try clicking next to the line.
3. :bug: You cannot add a breakpoint add the line, there is no area to click on. Adding a breakpoint via `Debug: Inline Breakpoint` works and it gets hit.

Is this a removed feature I missed to read in the release notes?
![image](https://user-images.githubusercontent.com/11234139/62640622-46e67800-b942-11e9-9a00-c10595692178.png)
(next to it there is the file explorer)

VS Code version: Code - OSS 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-22T07:38:21.043Z)
OS version: Linux x64 5.2.6-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3050)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.31GB (16.81GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
autoit|Dam|0.2.3
gitlens|eam|9.9.3
php-intellisense|fel|2.3.10
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
latex-workshop|Jam|7.3.0
vscode-phpfmt|kok|1.0.30
ra-lsp|mat|0.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
idl|myt|0.3.1
php-docblocker|nei|2.0.1
vetur|oct|0.21.1
polacode|pnp|0.3.2
java|red|0.47.0
code-settings-sync|Sha|3.4.1
vscode-lldb|vad|1.3.0
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-icons|vsc|9.2.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Looks like you have `editor.glyphMargin` disabled in your User or Workspace settings.

**Comment by jens1o** [comment]
Ah, I was expecting that it will reappear as soon as there is something to be shown. Thanks and sorry for the useless error report. :/
