### ISSUE TITLE
Link preview text on hover are inconsistent

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#78647]
Our link preview text on hover are inconsistent across various views, we should work to make all of them consistent.

## Terminal
<img width="350" alt="image" src="https://user-images.githubusercontent.com/35271042/62640657-ed0c9080-b8f6-11e9-8e05-e51a86eda80c.png">

## Markdown
<img width="558" alt="image" src="https://user-images.githubusercontent.com/35271042/62640826-42e13880-b8f7-11e9-9b9d-822fa860d58e.png">

## Webviews
<img width="614" alt="image" src="https://user-images.githubusercontent.com/35271042/62640973-8b98f180-b8f7-11e9-9ec8-fcddff180479.png">

**Comment by octref** [comment]
Related: #78125

**Comment by rebornix** [comment]
Related https://github.com/microsoft/vscode/issues/77964

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/pull/83175 was merged which fixes the terminal hover position, created https://github.com/microsoft/vscode/issues/83293 so we can verify it in endgame.

**Comment by misolori** [comment]
This looks like it got fixed:

![image](https://user-images.githubusercontent.com/35271042/98304887-af713a00-1f75-11eb-8281-dfbc74094202.png)

![image](https://user-images.githubusercontent.com/35271042/98304899-b730de80-1f75-11eb-8e75-5525bd67081b.png)

![image](https://user-images.githubusercontent.com/35271042/98304934-c44dcd80-1f75-11eb-8e80-e74efe4338ee.png)
