### ISSUE TITLE
Missing padding for "no quick fixes available"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#78657]
![image](https://user-images.githubusercontent.com/323878/62661195-3378e400-b925-11e9-9c81-79fb06663d6c.png)

Feels like it needs left padding

**Comment by misolori** [comment]
Fixed

<img width="252" alt="image" src="https://user-images.githubusercontent.com/35271042/62663231-8f466b80-b92b-11e9-9878-6267e0ee2442.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/35271042/62663242-94a3b600-b92b-11e9-9ba4-d21773ef9a2b.png">


<img width="356" alt="image" src="https://user-images.githubusercontent.com/35271042/62663220-85bd0380-b92b-11e9-84f9-0584c272654f.png">
