### ISSUE TITLE
Sluggish Behavior in the Text Editor

### ISSUE THREAD

**Issue by StarTether** [microsoft/vscode#78654]
Issue Type: <b>Performance Issue</b>

I am working in a large codebase. I am turning on a TSLint Rule (no-floating-promises) and going through each file one-by-one and fixing it manually. I am doing this by pasting in some text (`trackBackgroundTask(` followed by a `)` a few lines later to wrap the offending code). As I do this pasting, the whole UX becomes unresponsive for a second or up to three. The first time I paste within a file it is responsive for a moment but then not responsive for a couple seconds while it is likely analyzing the file for other errors and TSLint warnings; I say "likely" because the UX becomes interactive again at the same time that highlighting in the file is updated. This unresponsiveness gets in the way because I often know where I want my cursor to go but I cannot place it there until the UX is responsive. It would be much better if I could always navigate freely and that file analysis always happened in the background in a non-clocking fashion.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.18GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    94	 33300	code main
    0	    64	 13644	   window (Issue Reporter)
    0	   936	 16964	   window (● UserAddNewBladeV2.ts - UX - Visual Studio Code)
    0	   294	  6828	     extensionHost
    0	     3	 13648	       cmd /s /c "C:\Users\rarthur\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe -s c:\git\AD\IAM\IbizaExt\UX\src\Extension.sln --hostPID 6828 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\rarthur\.vscode\extensions\ms-vscode.csharp-1.21.0\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4"
    0	     5	 12876	         console-window-host (Windows internal process)
    0	    75	 27404	         C:\Users\rarthur\.vscode\extensions\ms-vscode.csharp-1.21.0\.omnisharp\1.34.0\OmniSharp.exe  -s c:\git\AD\IAM\IbizaExt\UX\src\Extension.sln --hostPID 6828 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin C:\Users\rarthur\.vscode\extensions\ms-vscode.csharp-1.21.0\.razor\OmniSharpPlugin\Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    59	 15808	       electron_node server.js 
    0	  1197	 17136	       electron_node tsserver.js 
    0	    20	 22680	         electron_node typingsInstaller.js typesMap.js 
    0	    21	 30316	       "C:\Users\rarthur\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\rarthur\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=6828
    0	     7	  8004	     console-window-host (Windows internal process)
    0	    41	 16936	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    15	 26604	     watcherService 
    0	     5	 22776	       console-window-host (Windows internal process)
    0	    41	 28220	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 36976	     console-window-host (Windows internal process)
   22	    72	 17296	   shared-process
    0	    12	 28656	   electron-crash-reporter
    0	    98	 34856	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● UserAddNewBladeV2.ts - UX - Visual Studio Code)
|    Folder (UX): 18047 files
|      File types: ts(5611) js(2666) map(2543) html(2148) dll(1304) lss(873)
|                  xml(661) lcl(646) json(416) svg(108)
|      Conf files: csproj(3) tslint.json(2) tsconfig.json(2) sln(1) gulp.js(1)
|                  package.json(1);
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.29.0
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.8
jsonnet|hep|0.1.0
vscode-edge-devtools|ms-|1.0.2
csharp|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
debugger-for-edge|msj|1.0.10
stylelint|shi|0.51.0
vscode-icons|vsc|9.2.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by StarTether** [comment]
No, it does not. But it also doe snot repro if I enable the TSLint 1.2.2 extension (which is likely the offending extension).

**Comment by mjbvz** [comment]
Thanks for checking.

Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to try tracking down which specific extension is causing this and please file an issue against them
