### ISSUE TITLE
Missing "flip cursor about selection" command

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#78653]
On the latest Insiders, but also on 1.36.1:

I could swear that in the past there has been a command for inverting the location of the cursor about a selection. But, searching the command palette and keyboard shortcuts for both "cursor" and "selection" turns up nothing. 

To be clear, I mean going from:
```
Hello <World>|
```
where inside brackets is selected and the pipe is the cursor, to:
```
Hello |<World>
```

Has this been removed or am I remembering something that never existed? If its still around, I think adding "cursor" or "selection" to the action name would really help with discoverability.

**Comment by rebornix** [comment]
@JacksonKearl could you share what's the last version you remember shipped with this command? Is it possible that is contributed by an extension?

**Comment by JacksonKearl** [comment]
Hm, if you don't remember it either I might be wrong about it existing earlier. Using this for now: `mlewand.vscode-selection-flip`.
