### ISSUE TITLE
No autocomplete for native JavaScript methods inside function

### ISSUE THREAD

**Issue by morshedx** [microsoft/vscode#78668]
- VSCode Version: 1.36.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Type `str.tol` outside the function - you will get `toLowerCase()` autocomplete suggestion.

![Screenshot_13](https://user-images.githubusercontent.com/10260796/62669217-a54a3f80-b9b0-11e9-844a-48e7d0871f35.png)

2. Type `str.tol` inside the function - you will get no `toLowerCase()` autocomplete suggestion.

![Screenshot_14](https://user-images.githubusercontent.com/10260796/62669247-c743c200-b9b0-11e9-8489-3cdeab401cb0.png)

This looks like an issue, I hope this will be fixed in the next release.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
You have no types defined for your function. Currently it accepts parameter of any type.

```js
/**
 * @param {string} str
 */
function getString(str) {

}
```

**Comment by morshedx** [comment]
> You have no types defined for your function. Currently it accepts parameter of any type.
> 
> ```js
> let str = 'hello';// <= `str` is `string` type
> 
> function getString(str) {// `str` is `any` type
> 
> }
> ```
> 
> You can either define types for the function parameter:
> 
> ```js
> /**
>  * @param {string} str
>  */
> function getString(str) {
> 
> }
> ```
> 
> Or you can remove function parameter declaration:
> 
> ```js
> let str = 'hello';
> function getString() {
> 	
> }
> ```

Why I've to declare function parameter type to get autocomplete?

Or if i remove the parameter from the function, then how can i get parameter value?

 It's kinda weird.
