### ISSUE TITLE
Cannot open multiple file tabs

### ISSUE THREAD

**Issue by 1245678** [microsoft/vscode#78669]
Issue Type: <b>Feature Request</b>

I want to open multiple file tabs in the same time, but it is always override open file.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
