### ISSUE TITLE
Strange Welcome Page Name

### ISSUE THREAD

**Issue by KsRyY** [microsoft/vscode#78664]
- VSCode Version: 1.37.0-insider
- OS Version: Windows 10 Insider Preview Build 18950

Steps to Reproduce:

1. Just Launch VSCode, the name of the welcome page shows the full resource path and its name in the `open editors` is `vs_code_welcome_page`.

![image](https://user-images.githubusercontent.com/25174488/62668260-da10c380-b9bd-11e9-80af-9d053cff8e73.png)

Does this issue occur when all extensions are disabled?: No, but I don't think this problem is caused by extensions.

**Comment by gjsjohnmurray** [comment]
@KsRyY why do you think this isn't caused by extensions?

If you enable your extensions one at a time can you identify the point where the problem occurs?

**Comment by KsRyY** [comment]
Weird. It recovered after a restart. No modification on anything.
![image](https://user-images.githubusercontent.com/25174488/62744012-4bf91380-ba77-11e9-9f73-ddcef13f2ea2.png)
Think it just a coincident.
