### ISSUE TITLE
Debug API: Inform extensions when Debug Session paused

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#78663]
I have been working for quite some time now on my [Debug Visualizer](https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer) extension that visualizes values while debugging. I find it very helpful when working with TypeScript ASTs:

![](https://raw.githubusercontent.com/hediet/vscode-debug-visualizer/master/docs/demo.gif)

To do that, I had to fork node-debug2 and [send the `paused` event as custom event together with the current frame id](https://github.com/hediet/vscode-node-debug2/commit/a2a43db0b5926d81d02136482031f4229537d7bd#diff-d03a74f75ec189cbc7dd3d2e105fc9c9R998).
Without manually patching the node debug adapter, the extension could neither visualize local variables as it doesn't know the current frame id nor could it update the visualization when the next breakpoint is hit as there is no event for that that can be consumed by extensions.
I used the [`evaluation` request](https://github.com/microsoft/vscode/issues/42989) to evaluate the given expression.

It would be great if VS Code could provide an event `onExecutionStateChanged` with a signature similar to this:
```ts
vscode.debug.onExecutionStateChanged: Event<DebugSessionExecutionStateChangedEvent>;

type DebugSessionExecutionStateChangedEvent = {
   newState: "running" | "stopped";
} | {
   newState: "paused"
   newFrameId: number;
}
```
Such an event would enable extensions like mine that could highly improve the debugging experience!

**Comment by hediet** [comment]
@weinand are you open for PRs on this one? Forwarding existing API's shouldn't be a technical issue though (so I guess the PR would be easy), but rather a deliberate design choice (which is why I guess a PR would likely be declined).

To be honest, I thought the debug visualizer (and this issue) would get a lot more traction, as I thought the visualizer could be really useful. At least it has been really useful to me every single time I worked with the TypeScript AST.

**Comment by weinand** [comment]
@hediet sorry for my late reply, but I was on vacation.
We will look into your request soon.

**Comment by hediet** [comment]
Thanks ;) 
Also, it would be cool if this state updates the current frame id when the user selects a non-active stack frame from the stack frame list of VS Codes UI. This way, one can visualize values of parent frames without stepping out.

**Comment by hediet** [comment]
Have you had a look yet? ;) Is there anything I can do?

**Comment by hediet** [comment]
By luck I found the method `debug.registerDebugAdapterTrackerFactory`, which allows to react on arbitrary messages from the debug adapter, including the `stopped` event. This basically allows extensions to access the debug adapter the same way VS Code does.

Being able to get the currently selected stack frame in the debug pane would still be nice, but that's another ticket.
