### ISSUE TITLE
debug console should support program input

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#78675]
Original feature request is: https://github.com/microsoft/vscode/issues/57571
But making `integratedTerminal` default for java debugger has a blocking issue on Windows.
 
Windows's default [code page](https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers) is not 65001(UTF-8), e.g. 437 for United States. This causes that all kinds of terminals (cmd, powershell, mingw, etc.) unable to display Unicode chars well. See: https://github.com/microsoft/vscode-java-debug/issues/622

A workaround for the display issue is: run `chcp` first before the command.  e.g. `chcp 65001 && <path-to-java-binary> -cp XXXX HelloWorld`. But it's also blocked by DAP and VSCode.

According to [DAP's RunInTerminal spec](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal), it's supposed to run only one single command. 
```ts
  /**
   * List of arguments. The first argument is the command to run.
   */
  args: string[];
```

I've tried to use `cmd /c "chcp 65001 && <path-to-java-binary>"` as a workaround, but it was also blocked by the below:
* `cmd /c` is not robust in all windows terminals. e.g. it does not work well in Git Bash for Windows, see related issue in [StackOverflow](https://stackoverflow.com/questions/21357813/bash-in-git-for-windows-weirdness-when-running-a-command-with-cmd-exe-c-with-a)
* In this case, <path-to-java-binary> is not well interpreted by vscode if there's any whitespace in the path.

My suggest is, whether it's possible to support also program input in DebugConsole, REPL also works because we can input in the above textbox, just like:
<img width="615" alt="Screen Shot 2019-08-08 at 12 58 58 PM" src="https://user-images.githubusercontent.com/2351748/62676147-57e3c780-b9dc-11e9-8682-4012cc69c88d.png">

**Comment by isidorn** [comment]
As for the input from the program I believe this is an old request. However I can leave it open for now.
As for a potential workaround for your RunInTerminal I am assigning this one also to @weinand (who might know the previous debug console input feature requests)

**Comment by weinand** [comment]
Run the debug target in the integrated terminal when your program reads input.
Only with the integrated terminal we are able to provide faithful tty/terminal input behavior.
