### ISSUE TITLE
Grid: when editor area is hidden, clicking on the file that is already opened does nothing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78678]
Steps to Reproduce:

1. open a file
2. move the panel large enough so that the editor area snaps away
3. click on the same file in the explorer again

=> 🐛 the editor is not revealed

I think we need to make sure that the editor area reveals on any action, even if the editor is already opened.

**Comment by joaomoreno** [comment]
@bpasero I think this is on purpose. The editor reveals if you double click or press Enter after the first click. First click would only change selection, but since selection is already that file, nothing happens.

**Comment by bpasero** [comment]
Ack. We still should add something to the menu though to bring back editor area.
