### ISSUE TITLE
[feature request] sftp protocol support

### ISSUE THREAD

**Issue by vinhjaxt** [microsoft/vscode#78673]
Yes, I've searched this issue to prevent duplication.
I am using "Connect to Server" feature on Linux to edit a file on my server over sftp.
However, vscode not work over this protocol. When i open a file with vscode, it'll execute command like `code sftp://root@xxx.xxx.xxx.xxx/root/my_file.js`
Then, vscode show up with blank page. So i think this protocol not supported yet.
Thank you.

**Comment by jrieken** [comment]
see https://marketplace.visualstudio.com/search?term=sftp&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by vinhjaxt** [comment]
> see https://marketplace.visualstudio.com/search?term=sftp&target=VSCode&category=All%20categories&sortBy=Relevance

It's not about extension, what I request is the command: `code sftp://root@xxx.xxx.xxx.xxx/root/my_file.js` just works.
