### ISSUE TITLE
Disable Outline panel

### ISSUE THREAD

**Issue by piecioshka** [microsoft/vscode#78676]
Issue Type: <b>Feature Request</b>

Hi there!

When editor start on the left side we have sidebar with:
- Code
- Outline

I never use Outline panel, so I woule like to disable that panel throught settings.json.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

**Comment by gjsjohnmurray** [comment]
@piecioshka Did you discover that the context menu on the Outline panel header allows you to hide the panel?

**Comment by piecioshka** [comment]
@gjsjohnmurray yes, I discovered. Is there any option to set into settings.json to disable after a fresh installation of VSC? During my workshops, I would like to send to student my config and they just will have configured whole editor.

**Comment by sandy081** [comment]
No, it is a state and not a setting.

**Comment by karbassi** [comment]
@sandy081 Can we propose it to be a setting?

As @piecioshka stated, many of us educators (instructors, workshop runners, etc.) share an initial settings.json with our students to get them all in the same place. Having to have them do extra steps to hide the Outline panel is an unnecessary step.
