### ISSUE TITLE
Intergrated terminal is pop out

### ISSUE THREAD

**Issue by onecentlin** [microsoft/vscode#78670]
Issue Type: <b>Bug</b>

I have already disabled all extensions. When I click `Terminal`, it is not embeded in VSCode but pop out. I also try to re-install VSCode again, but the issue still remain.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Possible duplicate of #73790

**Comment by onecentlin** [comment]
Settings:
Search `conpty` and disable `Terminal › Integrated: Windows Enable Conpty`

![20190809_002](https://user-images.githubusercontent.com/7122270/62748394-0c3c2700-ba8b-11e9-8662-5ca83cd668e0.png)
