### ISSUE TITLE
CANNOT CREATE FOLDER OR FILE FROM THE PANEL - SOLUTION

### ISSUE THREAD

**Issue by peter1492** [microsoft/vscode#78677]
$sudo chmod -R 777 <project_dir_name>. 

This gives the access to the workspace to create files and folder

**Comment by octref** [comment]
Please see our [issue reporting guideline](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests).
