### ISSUE TITLE
Launch VS Code launch config no longer connects to the launched instance

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78684]
When I run the Launch VS Code launch config the OSS version of VS Code launches, but the Insiders instance that I ran the launch from always times out. Same with the Attach to VS Code config.

**Comment by weinand** [comment]
@alexr00 you are using the "Launch VS Code" debug config, correct?
This works fine for me on macOS...

Could it be that there is some stale process already running on the debug port 5870?
In this case VS Code picks another debug port but VS Code still tries to connect on port 5870 (which will time out after 10 secs).

Just verify on the debug console that the debugger is in fact listening on port 5870.
Here is what I see on macOS:

![2019-08-08_11-34-35](https://user-images.githubusercontent.com/1898161/62692221-8cea1d00-b9d0-11e9-86ea-310ca5f29bd7.png)

**Comment by alexr00** [comment]
There is nothing in the debug console. I looked through the processes and killed the one listening on port 5870, but it still didn't work. So I rebooted.

Of course it now works so there must have been something stale somewhere. Thank you!
