### ISSUE TITLE
Launch remote from cli

### ISSUE THREAD

**Issue by DataTables** [microsoft/vscode#78688]
The `code` cli has:

```
  --folder-uri <uri>                Opens a window with given folder uri(s)
  --file-uri <uri>                  Opens a window with given file uri(s)
```

I'd like to propose a feature request to add support to these (or perhaps a new option) for opening VS Code with a remote folder - for example:

```
code-insiders --folder-url vagrant@192.168.234.234:/home/vagrant/
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/656
