### ISSUE TITLE
Folder contents

### ISSUE THREAD

**Issue by avinashsinghdhillon** [microsoft/vscode#78689]
Issue Type: <b>Bug</b>

Folder contents of my "client" folder are not showing up. I can however see them when I open the folder in the file explorer.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.05GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|1.9.0
vscode-npm-script|eg2|0.3.8
node-module-intellisense|lei|1.5.0
python|ms-|2019.8.29288
csharp|ms-|1.21.0
team|ms-|1.149.2
open-in-browser|tec|2.0.0

</details>

**Comment by avinashsinghdhillon** [comment]
![image](https://user-images.githubusercontent.com/47045062/62689468-7cb24d80-b990-11e9-9f9e-121d854d9425.png)

**Comment by gjsjohnmurray** [comment]
What does your `files.exclude` setting look like?

**Comment by avinashsinghdhillon** [comment]
![image](https://user-images.githubusercontent.com/47045062/62693960-11b94480-b999-11e9-94f6-14ac09d0e856.png)

**Comment by avinashsinghdhillon** [comment]
![image](https://user-images.githubusercontent.com/47045062/62694002-239ae780-b999-11e9-98bf-25fd21d1ca6e.png)

**Comment by avinashsinghdhillon** [comment]
I think the issue has something to do with merging git branches. I aborted my merge and the folder contents are visible now.
