### ISSUE TITLE
An error occurred while calling python mscvrt module to retrieve characters from a vscode terminal (windows10 1903)

### ISSUE THREAD

**Issue by SummerGGift** [microsoft/vscode#78682]
Today I updated Windows to 1903 and found that a python program I had written earlier ran incorrectly.
The brief test code is as follows:

```
import msvcrt
ch1 = msvcrt.getch()
ch2 = msvcrt.getch()
print(ch1)
print(ch2)
```

When I run the above code in native powershell, press ← key when collecting characters, and it will print `b'\xe0' B 'K'`, and the same code running in the vscode terminal returns `b'\x00' b'K'`.
This problem didn't appear in the last version of Windows, and I wondered what to do about it.

- VSCode Version: 1.36.1
- OS Version: windows 10 1903

Steps to Reproduce:

1. Run this code on the powershell terminal of vscode using Python3
2. press ← key，record print information
3. Run this code directly from your powershell on Windows using Python3
4. press ← key，record print information
5. Look at different outputs

Does this issue occur when all extensions are disabled?: No

Thank you for your attention.

**Comment by Tyriar** [comment]
Does the same occur if you use the Windows Terminal? I'm guessing this is related to the difference between keys going through conpty and the console api.

**Comment by SummerGGift** [comment]
This only happens when vscode calls the powershell terminal, not in a native Windows terminal.

@Tyriar

**Comment by SummerGGift** [comment]
This error occurred after Windows was upgraded to 1903, and was not present in the last Windows version 18xx.

**Comment by Tyriar** [comment]
@SummerGGift I think you're talking about conhost when you say windows terminal, I'm talking about this https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab

**Comment by SummerGGift** [comment]
@Tyriar 
I encountered the same problem when I tested the Windows Terminal (Preview) you said.
The code above returns the value '\x00' but not '\xe0'.
What seems to be the trouble now? 

Thank you.

**Comment by SummerGGift** [comment]
Does VScode call the terminal you're talking about? Should I go to the Windows Terminal to submit the issue?

**Comment by SummerGGift** [comment]
I have tested powershell with 6.x and 7.x, and they all work without vscode terminal calls.

Once it is called and run under vscode, the error I proposed will occur, so I think the problem is still on the vscode terminal.

**Comment by Tyriar** [comment]
We share the backend that Windows Terminal uses. You can create an issue over on that repo https://github.com/microsoft/terminal, but one probably already exists. I'm certain the team know of the problem and it might just be a design limitation.

> I have tested powershell with 6.x and 7.x, and they all work without vscode terminal calls.
>
> Once it is called and run under vscode, the error I proposed will occur, so I think the problem is still on the vscode terminal.

I'm confused now, so it doesn't reproduce in Windows Terminal using pwsh?

**Comment by SummerGGift** [comment]
When Windows was upgraded to 1903, whatever version of powershell it was, I got the error on [terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab) .

I wonder why this problem didn't exist with the last version of Windows (18.xx).

@Tyriar

**Comment by SummerGGift** [comment]
I had created an issue on the terminal repo : https://github.com/microsoft/terminal/issues/2397.

**Comment by Tyriar** [comment]
Tracked upstream
