### ISSUE TITLE
1.36.1 (user setup)-No symbols found in document'main.c'

### ISSUE THREAD

**Issue by lihaolongc** [microsoft/vscode#78685]
Issue Type: <b>Bug</b>

Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.76GB free)|
|Process Argv|D:\work_space\led\code\Color_led_grayscale|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
project-manager|ale|10.6.0
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.29.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|29.2.0
vscode-highlight|fab|1.3.4
beautify|Hoo|1.5.0
sublime-babel-vscode|jos|0.2.10
theme-monokai-pro-vscode|mon|1.1.13
vscode-language-pack-zh-hans|MS-|1.37.3
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
team|ms-|1.149.2
korofileheader|OBK|3.9.4
material-icon-theme|PKi|3.8.1
vscode-css-peek|pra|3.0.2
highlight-words|rsb|0.1.4
tabnine-vscode|Tab|1.3.0
ayu|tea|0.18.0
todo-list|Tza|1.4.0
code-navigation|vik|0.2.0
vscode-icons|vsc|9.2.0
vscode-todo-highlight|way|1.0.4
pyqt-integration|zho|0.2.0

(8 theme extensions excluded)
![QQ截图20190808161409](https://user-images.githubusercontent.com/49756541/62686927-4d372b80-b9f8-11e9-84c0-2d5215a8385a.png)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo - please see https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions for advice about how to write a good bug report

**Comment by lihaolongc** [comment]
> 
> 
> /needsMoreInfo - please see https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions for advice about how to write a good bug report

Thank you ,I will learn that.

**Comment by octref** [comment]
Please report to https://github.com/microsoft/vscode-cpptools
