### ISSUE TITLE
中文出现乱码了

### ISSUE THREAD

**Issue by lxp521125** [Microsoft/vscode#7868]
- VSCode Version:1.2.1
- OS Version: win7 x64

命令行 不能正常显示中文

**Comment by xiaopai** [comment]
VSCode Version 1.2.1
OS Version OSX 10.10.5

In terminal  the Chinese characters were garbled

**Comment by bingzheyuan** [comment]
This should be the same with #7036.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7062
