### ISSUE TITLE
cb function in vscode.workspace.onDidCloseTextDocument() is delayed

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#78694]
Hi

- VSCode Version: 1.36.1 (user setup)
- OS Version: Windows_NT x64

In my extension, I am opening a local file(which is saved one) using vscode.workspace.openTextDocument() and showing it in the text editor using vscode.window.showTextDocument() Till here every thing works fine.

Now I am listening to an event called vscode.workspace.onDidCloseTextDocument() the CB function is executed after some time like more than 5 minutes.

https://github.com/microsoft/vscode/issues/30820 This is also related to my issue but it was closed as reproduce steps are not give.

Steps to Reproduce:
extPath = path.resolve( process.env.USERPROFILE, ".vscode", "extensions","foldername","ddl.txt")
1. Open the file using  vscode.workspace.openTextDocument(vscode.Uri.file(extPath))
2. show the file using   vscode.window.showTextDocument()
3. Now listening to vscode.window.onDidCloseTextDocument()

---3rd callback function will take more time to execute. (Even if you put only Console.log in that )

Does this issue occur when all extensions are disabled?: Yes

Thanks,
Akhil

**Comment by hediet** [comment]
Can you paste the code of the entire `extension.ts` so we can directly try to reproduce it?

**Comment by akhilravuri1** [comment]
Hi @hediet 

please open this link https://github.com/akhilravuri1/treeworld In this you have all the required files.

Thanks,
Akhil

**Comment by jrieken** [comment]
>  the CB function is executed after some time like more than 5 minutes.

Yes, that's the design behaviour as the editor decides when to actually close the document/file. To observe editors changing, you need to listen to the `onDidChangeVisibleTextEditors`-event

**Comment by akhilravuri1** [comment]
Hi @jrieken 
onDidChangeVisibletextEditor will call the cb function while opening and closing the file but I want to call it only at closing so I have to use onDidClosetextDocument().
Thanks,
Akhil

**Comment by jrieken** [comment]
> onDidChangeVisibletextEditor will call the cb function while opening and closing the file but I want to call it only at closing 

When the event fires, just check with `window.visibleTextEditors` if a certain document is still showing

**Comment by akhilravuri1** [comment]
Hi @jrieken 
vscode.window.activeTextEditor.document.fileName gives "c:\Users\rakhil\.vscode\extensions\DevOps\dll.txt"

But when I do process.env.USERPROFILE it gives me "C:\Users\rakhil" here c  is small and capital.
So it doesn't match.

**Comment by jrieken** [comment]
use `document.uri`, not fileName, and make sure to compare it again `vscode.Uri.file(<somePath>)`

**Comment by akhilravuri1** [comment]
Hi @jrieken 
See the log:-
THIS IS URI.file

Object:-
$mid:1
path:"/C:/Users/rakhil/.vscode/extensions/DevOps/dll.txt"
scheme:"file"

THIS IS document.uri

Object:-
$mid:1
fsPath:"c:\Users\rakhil\.vscode\extensions\DevOps\dll.txt"
_sep:1
external:"file:///c%3A/Users/rakhil/.vscode/extensions/DevOps/dll.txt"
path:"/c:/Users/rakhil/.vscode/extensions/DevOps/dll.txt"
scheme:"file"

both have different path values(small c and captial C).

**Comment by jrieken** [comment]
> both have different path values(small c and captial C).

Yes, that's OK. There is no spec about the casing of the drive letter, it can c or C. Use `vscode.Uri.toString` (maybe `fsPath` in case you are sure it's a file-url) to compare. Those values are normalised

**Comment by akhilravuri1** [comment]
Hi @jrieken 
sorry for the trouble.
I tried all the possible ways. It's not working.
And one more thing is activetexteditor CB function is called in an increment way. Like when I open the file for the first time it is called only once after the second call it is called twice. 

Thanks,
Akhil
