### ISSUE TITLE
c/c++ features request. pointer and function list.

### ISSUE THREAD

**Issue by xsjqqq123** [Microsoft/vscode#7869]
- VSCode Version:1.2.1
- OS Version:win 7

Steps to Reproduce:

1. I develop c++ app using this soft. I had installed most the c++ plugins,the operator "." work well when show functions list, but the operator "->" don't show any tips. 
2. can this soft show a "function list" like source insight? when a click a func name ,can jump it fast?

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscppsamples#76
