### ISSUE TITLE
chinese support 

### ISSUE THREAD

**Issue by diveDylan** [microsoft/vscode#78691]

**Comment by Handsomer** [comment]
i have see same problem[https://github.com/microsoft/vscode/issues/78621](url)

**Comment by Handsomer** [comment]
i have see same problem[Chinese support in remote ssh ](https://github.com/microsoft/vscode/issues/78621)

**Comment by diveDylan** [comment]
> i have see same problem[Chinese support in remote ssh ](https://github.com/microsoft/vscode/issues/78621)

chinese extension document😄
