### ISSUE TITLE
some error cant find the solution

### ISSUE THREAD

**Issue by ullas1313** [microsoft/vscode#78692]
Issue Type: <b>Feature Request</b>

I am a student and I was doing the practical some error occur
when i opened the terminal for excuting the code for two number addition, subtraction, multiplication and division.
i entered the path file for example d:/mycode>gcc practical3.c for exe its showing some error like this mention bellow
put file a.exe: Permission denied
collect2.exe: error: ld returned 1 exit status

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
/question

@ullas1313 how is this a Feature Request? Please use other Internet resources to get answers for questions like this. If you think the question is VS Code-specific maybe use [StackOverflow and the visual-studio-code tag](https://stackoverflow.com/questions/tagged/visual-studio-code).
