### ISSUE TITLE
"Copy to Clipboard' not working 

### ISSUE THREAD

**Issue by KVGarg** [microsoft/vscode#78707]
Sorry, for not following the Issue Template as the template was not according to my issue that I want to file. As, I wasn't able to find the repository for https://marketplace.visualstudio.com.
Visiting any `extension` webpage on marketplace website, there is an option `copy to clipboard` that copies the `execution command` that installs the extension to VSCode. That option isn't working. Can we have a fix for that? Or I would like to solve it, if allowed!
For example, https://marketplace.visualstudio.com/items?itemName=danwahlin.angular2-snippets

**Comment by sandy081** [comment]
Seems issue on Marketplace website @kesane-msft FYI

**Comment by kesane-msft** [comment]
Thanks @KVGarg for reporting. I have created a bug on the Marketplace backlog. Till we roll out the fix, would suggest you to manually copy paste the command. Sorry for the trouble.
