### ISSUE TITLE
Slow completions with TS/JS language server

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode#78706]
- VSCode Version: 1.36.1
- OS Version: Windows 10 (1903)

Steps to Reproduce:

1. Open a medium size angular project with with around 18K lines of typescript code
2. The initialization of the language server takes around 2 mins.
3. Now open a typescript file and try to invoke code completions. That's takes around 10-20 secs to get the completion list. The second invocation is fast.
4. Now open another typescript file and invoke code completions. That's takes around 10-20 secs again.

Does this issue occur when all extensions are disabled?: No
This happens when the `angular.ng-template` extension is active.

**Comment by mjbvz** [comment]
As you noted, this only happens when `angular.ng-template` is active. Please file an issue against them
