### ISSUE TITLE
Scroll Problem in "Peek Problem"

### ISSUE THREAD

**Issue by shauryaverma4296** [microsoft/vscode#78703]
Issue Type: <b>Bug</b>

On generating an error.
Click on Peek Problem.
Long error messages cut off and scroll just won't work
![image](https://user-images.githubusercontent.com/13284683/62704512-3c42e600-ba09-11e9-9a68-cdf9dc9cf726.png)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3388)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.61GB (4.98GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-add-brackets|ali|0.9.0
vscode-hex-pm-intellisense|ben|0.2.1
elm-ls-vscode|elm|0.4.2
vscode-elixir-snippets|flo|0.0.30
smarty|imp|0.3.0
elixir-ls|Jak|0.2.25
vscode-elm-jump|joe|0.0.1
elixir-language-support|max|0.3.0
elm-markup-vscode|mdg|0.1.4
vscode-elixir|mjm|1.1.0
elixir-formatter|sar|1.3.0
elm|sbr|0.25.0
gitblame|wad|3.0.1

</details>

**Comment by sandy081** [comment]
Can you please provide steps to repro?
