### ISSUE TITLE
Incorrect PHP syntax highlighting after writing PHP in <style> tag

### ISSUE THREAD

**Issue by hdodov** [microsoft/vscode#78704]
- VSCode Version:
- OS Version:
![image](https://user-images.githubusercontent.com/5570098/62755070-2cfc8080-ba7b-11e9-92ee-408330f8fec4.png)

Steps to Reproduce:

1. Create a PHP file
2. Add the following:

```
<body>
    <style>
        <?php foreach ($words as $word) : ?>
            .word-<?= $word->id() ?> {
                top: <?= $word->y() ?>%;
                left: <?= $word->x() ?>%;
                font-size: <?= $word->size() ?>em;
            }
        <?php endforeach ?>
    </style>
    <div>
        <span>Hello world!</span>
        <?php foreach ($item as $items) : ?>
            <?= $item->bar() ?>
        <?php endforeach ?>
    </div>
</body>
```

Does this issue occur when all extensions are disabled?: **Yes**

![image](https://user-images.githubusercontent.com/5570098/62705843-efeeaa80-b9f6-11e9-8b54-dbae9d162111.png)

---

**Edit:** Adding `/` after the last PHP tag resets the highlighting for some reason and everything after it is alright:

```
<?php endforeach ?>/
```
![image](https://user-images.githubusercontent.com/5570098/62708495-37c40080-b9fc-11e9-8d17-5997ad584e71.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/33519
