### ISSUE TITLE
explorer.autoReveal causes double stat call when Explorer is refreshed

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#78710]
Issue Type: <b>Bug</b>

1. Fetch fsprovider-sample from https://github.com/microsoft/vscode-extension-samples
2. Check that your `explorer.autoReveal` is true.
3. Set a logpoint on the return statement of the stat function in fileSystemProvider.ts, making it log the following message:
  `stat {uri.path}`
4. Start debugging the 'Launch Extension' debug configuration
5. When the Extension Development Host (EDH) window appears, use its Command Palette as follows:
- MemFS: Setup Workspace
-  MemFS: Create Files
6. Expand the workspace root.
7. Open one of the files, e.g. file.txt
8. In your main VSCode window (orange status line), clear the Debug Console pane.
9. In the EDH (blue status line), use the Command Palette to run `File: Refresh Explorer` or click the Refresh Explorer button on the workspace titlebar.
10. On the Debug Console of the main window observe that the logpoint writes `stat /` twice.
11. Set your `explorer.autoReveal` to false.
12. Repeat the `File: Refresh Explorer` and observe only one `stat /`

The duplicated stat call is a problem in situations where this is expensive (e.g. a large number of files on a remote filesystem on a slow connection).

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

Also observed in 1.37-insider.

**Comment by isidorn** [comment]
@gjsjohnmurray would you be interested in providing a PR to tackle this. It looks like it might be something similar to the `select` issue you already created a PR for?

**Comment by gjsjohnmurray** [comment]
@isidorn yes I will have a go at a PR, as this issue is in a similar area to #79047

**Comment by isidorn** [comment]
@gjsjohnmurray great, thanks!
