### ISSUE TITLE
Python has no TextMate scope for variables

### ISSUE THREAD

**Issue by Mooninaut** [microsoft/vscode#78711]
Issue Type: <b>Bug</b>

There is no TextMate (TM) scope for ordinary variables in Python. In order to style ordinary Python variables, it is necessary to set the entire `source.python` scope to the desired color and font style, and then select every `.python` scope individually to change the color and font style back.

The problem still exists with all extensions disabled.

Example using Developer: Inspect TM Scopes
![image](https://user-images.githubusercontent.com/1463364/62717420-dd15af00-b9d1-11e9-9b28-b12d7399ab45.png)

Example theme workaround:

    {
      "scope": "source.python",
      "settings": {
        "foreground": "#76aae0"
      }
    },
    {
      "scope": [
        "keyword.operator.arithmetic.python",
        "keyword.operator.assignment.python",
        "keyword.operator.comparison.python",
        "punctuation.definition.arguments.begin.python",
        "punctuation.definition.arguments.end.python",
        "punctuation.definition.dict.begin.python",
        "punctuation.definition.dict.end.python",
        "punctuation.definition.list.begin.python",
        "punctuation.definition.list.end.python",
        "punctuation.section.function.lambda.begin.python",
        "punctuation.separator.annotation.result.python",
        "punctuation.separator.arguments.python",
        "punctuation.separator.colon.python",
        "punctuation.separator.element.python",
        "punctuation.separator.period.python"
      ],
      "settings": {
        "foreground": "#dadada",
      }
    },
    {
      "scope": [
        "meta.function-call.generic.python",
        "support.function.builtin.python"
      ],
      "settings": {
        "foreground": "#ff8000",
      }
    }

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment]
This is a neat idea, but it is beyond what can be done with textmate. An exploration of how this could be down outside of textmate is here: https://github.com/microsoft/vscode/issues/77140
