### ISSUE TITLE
MarkupContent: Link not rendered when space exists on line start

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78717]
Use below `MarkupContent` to return hover and completion in [LSP sample](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample):

```ts
const markupContent: MarkupContent =  {
	kind: 'markdown',
	value: `
   	[I'm an inline-style link](https://www.google.com)`
};
```

![image](https://user-images.githubusercontent.com/4033249/62721687-93bd6380-b9c1-11e9-9e08-93e42f51bd75.png)

![image](https://user-images.githubusercontent.com/4033249/62721702-9ae47180-b9c1-11e9-885b-335385cc0bec.png)

**Comment by jrieken** [comment]
We use 'marked' for this... Not sure if this is by design or a bug

**Comment by octref** [comment]
After reading CommonMarks spec I realized 4 spaces => code block, so it's correct to render it as code blocks in hover.

And as for completion...It's a matter of wrapping. I just needed to scroll down...

![image](https://user-images.githubusercontent.com/4033249/65066501-4fff3780-d939-11e9-8897-b8d21e60f1cc.png)
