### ISSUE TITLE
Source Control views are not remembered properly w/ multi-root

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#78724]
Issue Type: <b>Bug</b>

In 1.37, the chosen views on the Source Control sidebar aren't remembered anymore. I have a multi-root workspace with 7 repos. If I have each repo the views on and restart code it only restores 2 of them. And it always shows the _Source Control Providers_ view regardless of me turning it off.

I tested this in 1.36 and other than the _Source Control Providers_ view from always re-appearing everything else worked as expected.

/cc @joaomoreno 

VS Code version: Code - Insiders 1.37.0-insider (5e08ee01b7daee99cdda2456f19d77e715fb8762, 2019-08-05T21:18:05.921Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.56GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Eric/code/vscode-gitlens|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
@eamodio Do you see the same behavior with any other view container? E.g. debug?

**Comment by eamodio** [comment]
Not that I can see -- and the Source Control sidebar seems to remember custom view just fine. Its only the views per repo and the _Source Control Providers_ view

**Comment by joaomoreno** [comment]
What I see in 1.36:

- Regardless of what repos you pick, on reload VS Code will always add the first repo to the visible set
- The Source Control Providers view always shows, regardless of user choice

What I see in 1.37:

- Regardless of what repos you pick, on reload VS Code will always show the first repository and the *first* repo of the picked set
- The Source Control Providers view always shows, regardless of user choice

Do you confirm?

This is so weird and definitely not as I last left it. :cry:

**Comment by joaomoreno** [comment]
Not really sure what broken here. I'll refactor this a bit and try to get it into a better shape. Removing the candidate label tho, since it's not really critical.

**Comment by eamodio** [comment]
@joaomoreno looks good now -- thank you!

**Comment by joaomoreno** [comment]
I think I found what broke this in the first place: https://github.com/microsoft/vscode/issues/77088

I now have two more issues related to that:
- https://github.com/microsoft/vscode/issues/79037
- https://github.com/microsoft/vscode/issues/80043

**Comment by eamodio** [comment]
@joaomoreno This bug seems to be back -- and sometimes worse than before.

I have a workspace that has 7 repos in it and I have some GitLens views and GitHub PRs on the SCM sidebar. When I open the workspace (to the SCM or switch right away at launch), I seem to get a somewhat random ordering (and visibility) of the views. The GitLens & GitHub PRs views are always there (though they move around), but sometimes they also get duplicated. While the repo views move around and sometimes become hidden.

In the screenshot below, you can see the following issues:
- The Source Control Providers view is checked in the menu but isn't visible at all (and should have been)
- The GitHub PRs view is duplicated (I've seen the same thing happen with GitLens views -- but only seems to happen if they are expanded -- the GitHub PRs view seems to always expand itself 😠)
- Only 2 repos are visible when all 7 should have been

![image](https://user-images.githubusercontent.com/641685/67706606-75974c00-f98f-11e9-8677-23b17010f597.png)

This behavior changes each time a reload too

**Comment by joaomoreno** [comment]
There is no easy fix here.

**Comment by eamodio** [comment]
@joaomoreno I don't know if the behavior has gotten even worse, but working in mutli-root workspaces especially with the GitHub PRs extensions (because it basically requires the use of the _Source Control Providers_ view) is really painful compare to stable. Using the SCP view, causes views to re-order (jump around), sometimes won't hide certain views, and they are hidden according to the context menu and if you "unhide" them from the menu there will be 2 views open for the same repo, and it seems if that happens, sometimes resizing views breaks (no drag handles).

**Comment by joaomoreno** [comment]
Show me in a screen sharing session.

**Comment by joaomoreno** [comment]
This has now changed so much, it no longer applies.
