### ISSUE TITLE
Last 2 weeks get Loading...and no intellisense

### ISSUE THREAD

**Issue by dl-husky73** [microsoft/vscode#78721]
- VSCode Version:  1.37.0 insider (used 1.36, added insider)
- OS Version:  Win 10, v1903, OS Build 18362.267

Steps to Reproduce:

1.  Open VS Code with React Native Folder (150-200 small to medium files).  Intellisense operates normally for 5-15 seconds and then cpu spikes and never works again.  Always shows Loading... with no outcome.  Worked fine until week or two ago.   I am new (few months coding) but have been using vs code since beginning so feel comfortable and love it until this.  
2.  I have typical react native extensions.  After reading github issues/online, I have gone to insiders and disabled all extensions.  Same issue.   
3. I upgraded RN to 60.4 and many of subsequent packages.  Happened about same time.  
4. Did a clean install of project into another folder/workspace in React Native.  
5. I have the tsserver log on verbose.  I have included. I see some issues but honestly I have tried to fix and can't figure out...

Does this issue occur when all extensions are disabled?: Yes
[tsserver.log](https://github.com/microsoft/vscode/files/3483098/tsserver.log)

**Comment by IllusionMH** [comment]
I can't see any `completionInfo` events here which should provide list of all possible completions.
Could you get `tsserver.log` after attempt to trigger Intellisense?
Please note that log contains full file names and completion info should show a lot of variables/functions etc. names.

Do you see anything suspicious in DevTools (**Help > Toggle Developer Tools**)?

**Comment by dl-husky73** [comment]
Thanks for follow-up.  Yes, I did get the tsserver.log updated and I do see the intellisense plugin.   I have attached a 2nd log for review.  What I see is no error, it just has the blue line going back and forth like it is doing something but never resolves.


Toggle Tools – I see this error:

/C:/Users/CopperMine/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3349
[EQuimper.react-native-react-redux]: Unknown language in `contributes.react-native-react-redux.language`. Provided value: jsx
_logMessageInConsole @ /C:/Users/CopperMine/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3349
/C:/Users/CopperMine/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3501
[Extension Host] debugger listening on port 29355
/C:/Users/CopperMine/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:242
[Extension Host]
(node:15416) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Thanks,
David

**Comment by mjbvz** [comment]
@dl-husky73 Unfortunately I don't see anything that stands out in the logs. 

Can you please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to see if that fixes the issue. If you still see the problem, please try share a small example project that demonstrates this issue
