### ISSUE TITLE
`cursorPageUp` + `cursorPageDown`

### ISSUE THREAD

**Issue by buggymcbugfix** [microsoft/vscode#78725]
We have `scrollPageUp` + `scrollPageDown` actions, but they don't move the cursor. In most cases I want the cursor to move and not just the view to scroll. I therefore propose `cursorPageUp` + `cursorPageDown`.

**Comment by rebornix** [comment]
We do have these two command ;)

**Comment by buggymcbugfix** [comment]
D'oh. Thanks!
