### ISSUE TITLE
Deleted file keeps showing up on editor tab

### ISSUE THREAD

**Issue by hanzo2001** [microsoft/vscode#78723]
Issue Type: <b>Bug</b>

I usually keep a lot of Untitled-NN tabs open with code snippets which are always there when I reopen the editor. Some time ago I deleted a large project and probably one of the files was open in an editor. Regardless, all the other tabs disappear if I manually close them, however, this deleted file always turns up the next day.
I tried to save the file to see if I could get rid of it some other way but an error pops out:

    Unable to write file (NoPermissions (FileSystemError): Error:
    EACCESS: permission denied, mkdir '/node_modules')

How can I get rid of this file once-and-for-all? It always shows up empty with the unsaved marker next to the name on every restart

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.4.0-151-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.54GB (6.87GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
sql-formatter|cym|1.0.2
vscode-markdownlint|Dav|0.29.0
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
beautify|Hoo|1.5.0
kubernetes-snippets|ipe|0.1.9
ldif|jta|0.2.0
xml-format|mik|1.0.2
vscode-docker|ms-|0.7.0
cpptools|ms-|0.24.1
java|red|0.47.0
vscodeintellicode|Vis|1.1.8
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by bpasero** [comment]
@hanzo2001 if it shows up dirty, it seems like we try to restore a backup on that file. Can you check if there is any content in `%APPDATA%/Code/Backups`? If you delete that it should be fine. But make sure to backup that folder if you have other dirty files.
