### ISSUE TITLE
VS Code does not load files with previous changes when OS recovers from read only mode.

### ISSUE THREAD

**Issue by mcarpenterjr** [microsoft/vscode#78720]
- VSCode Version: Insiders 1.37
- OS Version: Linux Mint 19

Just had a strange occurrence and this might not be a bug, I'm just looking for a better understanding of what might have taken place. 
Our intern's Linux machine's file system, at some point in the past 36 hours, became corrupted and went into read-only mode. The files he was working from were a network mount with a symlink of the mount to a directory in their home folder. VSCode never indicated it was having trouble autosaving, and nothing indicated there were save issues either. Once we realized the OS was read-only we shut down VSCode, without closing any of the open files, shut the machine down and then ran FSCK to fix the file system issues. Once the machine booted back into the OS we then reopened VSCode, which opened all the appropriate files that were previously open. However, when we were looking at them they all seemed to lack changes that were previously saved. We then closed the files and then reopened them to see the most current versions of them.
My question is, in the case stated above why did VSCode start with these older files? Is there some level of caching going on? Without knowing what really happens when VSCode starts with previously open files, I'm speculating that VSCode isn't asking for the version on disk it is loading from a cache, which in some cases is fine I guess, but at a failure point like this could cause users to lose work if they are not careful. Again without knowing what is exactly happening at launch this is all pure speculation, would like to know the thoughts on this of the community and developers.

Steps to Reproduce:

1. Have linux FS fault and go into read only mode
2. Close VSCode with files that contain recent changes.
3. FSCK linux OS Drive.
4. Reopen VSCode allowing it to load previously open files.
5. See that recent changes are not present.
6. Close files and reopen. See previously made changes are present.

Does this issue occur when all extensions are disabled?: Unsure

**Comment by bpasero** [comment]
@mcarpenterjr there is no caching done at all in VSCode. The only exception is, if any of the file has changes by the user, we restore these changes from a cache location. But you would see this by the fact that these files are dirty. Where they dirty?

**Comment by mcarpenterjr** [comment]
> > Steps to Reproduce:
> 
> Have linux FS fault and go into read only mode
> 
> I would not say that is a recipe for reproduction...
I haven't the slightest idea how the device got into read-only and I have no idea how to trigger that again. :man_shrugging: 

Files were not dirty.

Before running FSCK and Restarting, everything was current.
After the reboot, VSCode opened with the previous files, and they were short some lines and edits that were previously made and committed to the project's repo. 

Just found it odd that VScode started like that.
