### ISSUE TITLE
Seed "Find in files" from regular "find" input when focused (like VSPro)

### ISSUE THREAD

**Issue by gmathis** [microsoft/vscode#78733]
A common workflow for me when a "find" operation in the current file doesn't turn up any results is to then search for the same term across all files.
This is trivial in VSPro, where hitting [Ctrl]-[Shift]-[F] at this point brings up "Find in files" with the same search terms as the "Find" dialog.

VSCode has an unfortunate behavior here that I thought was a bug for a long time.
When pressing [Ctrl]-[Shift]-[F] after a failed local find, the "Find in files" input is seeded with a truncated version of the search terms.
What's actually happening is that "Find in files" is being seeded not with the current "find" query, but with the selected text from the current document, which, since the find failed, represents only the longest matching prefix of the actual search terms.

While seeding "find in files" from the current document selection is desirable when focus is in the document, it would be much more useful, when focus is in the "find" popup, to seed "find in files" from the full search terms there instead.

Thanks for a great tool!

**Comment by roblourens** [comment]
@rebornix is it possible for me to query the text in the active editor's find widget, and whether it is focused? Without cheating and looking at `document.activeElement`.

**Comment by rebornix** [comment]
Didn't see the notification before. @roblourens we can archive that without `document.activeElement`

* Read from context key `findInputFocused` to check if it's focused or not.
* If you can get active text editor, then you can resolve the find controller bind to it by `let controller = CommonFindController.get(editor);`, with which you can get the state of the query, replacement and options.

**Comment by roblourens** [comment]
Oh interesting, thanks

**Comment by RMacfarlane** [comment]
Is this scenario supposed to work?

1. Select some text in an editor and Cmd+F to bring up find widget
2. Select other text in editor
3. Refocus the find widget
4. Cmd+Shift+F to open global search

The global search isn't populated with anything, I was expecting it to take the text from the find widget

**Comment by roblourens** [comment]
That works for me, do you have any search settings set?

**Comment by roblourens** [comment]
Oh in your scenario, if you didn't select the text in the find widget in step 3, it won't copy text to the search viewlet unless you have `"search.seedWithNearestWord": true`

**Comment by RMacfarlane** [comment]
Ah, yeah, that was it! I didn't have the text selected or `"search.seedWithNearestWord": true`, thanks.
