### ISSUE TITLE
UNC Path autocompletion removes one leading slash, preventing further completions

### ISSUE THREAD

**Issue by SydneyhSmith** [microsoft/vscode#78738]
- VSCode Version: 1.36
- OS Version: Windows

We had an issue opened in the [PowerShell VScode extension repo](https://github.com/PowerShell/vscode-powershell/issues/2116) and after investigation, it looks like the issue could be occurring in VSCode. 

Steps to Reproduce:

Open a PowerShell file in vscode, attempting to complete a path to a directory on a UNC path, the leading slash keeps being removed by the completion.

`'\\server\share\somefolder\'`

Expected Behaviour
`'\\server\share\somefolder\AdditionalFolder\'`

Actual Behaviour
`'\server\share\somefolder\AdditionalFolder\'`

Based on the logs, it appears that the PowerShell extension is properly handling the the slashes, so it looks like the issue could be occurring in vscode. 

```
2019-08-06 22:39:14.306 [VERBOSE] tid:22 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Response 'textDocument/completion' with id 50
    
    {
      "jsonrpc": "2.0",
      "id": "50",
      "result": [
        {
          "label": "Carl",
          "kind": 19,
          "detail": null,
          "documentation": null,
          "sortText": "0001Carl",
          "filterText": "'\\\\svr-2015-01\\User Documents\\Carl'",
          "insertText": "'\\\\svr-2015-01\\User Documents\\Carl$0'",
          "insertTextFormat": 2,
          "range": null,
          "commitCharacters": null,
          "textEdit": {
            "range": {
              "start": {
                "line": 889,
                "character": 0
              },
              "end": {
                "line": 889,
                "character": 35
              }
            },
            "newText": "'\\\\svr-2015-01\\User Documents\\Carl$0'"
          },
          "additionalTextEdits": null,
          "command": null,
          "data": null
        }
      ]
    }

2019-08-06 22:39:14.309 [VERBOSE] tid:22 in 'ReadMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageReader.cs: line 138
    Received Request 'completionItem/resolve' with id 51
    
    {
      "jsonrpc": "2.0",
      "id": 51,
      "method": "completionItem/resolve",
      "params": {
        "label": "Carl",
        "filterText": "'\\\\svr-2015-01\\User Documents\\Carl'",
        "insertTextFormat": 2,
        "textEdit": {
          "newText": "'\\\\svr-2015-01\\User Documents\\Carl$0'",
          "range": {
            "start": {
              "line": 889,
              "character": 0
            },
            "end": {
              "line": 889,
              "character": 35
            }
          }
        },
        "kind": 19,
        "sortText": "0001Carl",
        "data": null
      }
    }

2019-08-06 22:39:14.309 [VERBOSE] tid:22 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Response 'completionItem/resolve' with id 51
    
    {
      "jsonrpc": "2.0",
      "id": "51",
      "result": {
        "label": "Carl",
        "kind": 19,
        "detail": null,
        "documentation": null,
        "sortText": "0001Carl",
        "filterText": "'\\\\svr-2015-01\\User Documents\\Carl'",
        "insertText": null,
        "insertTextFormat": 2,
        "range": null,
        "commitCharacters": null,
        "textEdit": {
          "range": {
            "start": {
              "line": 889,
              "character": 0
            },
            "end": {
              "line": 889,
              "character": 35
            }
          },
          "newText": "'\\\\svr-2015-01\\User Documents\\Carl$0'"
        },
        "additionalTextEdits": null,
        "command": null,
        "data": null
      }
    }
```

**Comment by TylerLeonhardt** [comment]
This was closed by accident.

> Based on the logs, it appears that the PowerShell extension is properly handling the the slashes, so it looks like the issue could be occurring in vscode.

**Comment by TylerLeonhardt** [comment]
@octref

**Comment by octref** [comment]
There's no path completion for powershell files built-in in VS Code, are there?

**Comment by msftrncs** [comment]
@octref,

> There's no path completion for powershell files built-in in VS Code, are there?

It does not appear so.  If the PowerShell extension is disabled, then no completions are offered around or near the path string.

Of a specific note, this is only seeming to occur when the path is quoted (single or double doesn't seem to matter).  Also of special interest is the `$0` character used in the completion to move the cursor to be in front of the final quote so that more completions (more folders) can be requested without the user needing to back-step.

**Comment by TylerLeonhardt** [comment]
@octref that's correct - the completions are provided by the PowerShell extension. However, the logs from the PowerShell extension claim that the message being sent to vscode is correct:

```
2019-08-06 22:39:14.306 [VERBOSE] tid:22 in 'WriteMessageAsync' C:\PowerShellEditorServices\src\PowerShellEditorServices.Protocol\MessageProtocol\MessageWriter.cs: line 88
    Writing Response 'textDocument/completion' with id 50
    
    {
      "jsonrpc": "2.0",
      "id": "50",
      "result": [
        {
          "label": "Carl",
          "kind": 19,
          "detail": null,
          "documentation": null,
          "sortText": "0001Carl",
          "filterText": "'\\\\svr-2015-01\\User Documents\\Carl'",
          "insertText": "'\\\\svr-2015-01\\User Documents\\Carl$0'",
          "insertTextFormat": 2,
          "range": null,
          "commitCharacters": null,
          "textEdit": {
            "range": {
              "start": {
                "line": 889,
                "character": 0
              },
              "end": {
                "line": 889,
                "character": 35
              }
            },
            "newText": "'\\\\svr-2015-01\\User Documents\\Carl$0'"
          },
          "additionalTextEdits": null,
          "command": null,
          "data": null
        }
      ]
    }
```

The important part is `"insertText": "'\\\\svr-2015-01\\User Documents\\Carl$0'",`

Even though the PowerShell extension sends this to vscode, vscode replaces the first slash for some reason.

So yes, this happens with the PowerShell extension, but it is sending the correct data to vscode - it seems that this would be a vscode bug

**Comment by octref** [comment]
Looping in @jrieken, I'm not very familiar with path handling and UNC.

**Comment by jrieken** [comment]
@TylerLeonhardt Please provide a repo extension using`vscode.d.ts`-types

**Comment by TylerLeonhardt** [comment]
@jrieken not sure why I didn't get a notification for this but here is the repro with snippets:

```
"repro": {
        "prefix":"repro",
        "body":[
            "'\\\\svr-2015-01\\User Documents\\Carl$0'"
        ]
    }
```

gives me:

`'\svr-2015-01\User Documents\Carl'`

also here's the popup:

![image](https://user-images.githubusercontent.com/2644648/64275641-f17a9800-cefa-11e9-98ff-edb05e07a473.png)

**Comment by jrieken** [comment]
Sorry, this isn't a bug it's just complicated so that I also keep forgetting how this goes. It seems like we need better tooling... So, the rules of backslash in TextMate is that backslash escapes `$`, `}`, and `\` itself. So, `\\foo` results in `\foo` just like `\foo`. Go get two slashes, type three. That must be combined with JSON needing to escape a `\` with another `\` which leads to `'\\\\\\svr-2015-01\\User Documents\\Carl$0'`

**Comment by TylerLeonhardt** [comment]
Wow. That's really rough. So how come only two slashes gets me one slash?

I would expect 3 slashes to get me one slash which would then mean 6 slashes for 2 and so on

**Comment by jrieken** [comment]
Don't shoot the messenger - I didn't invent this, I only mimic what Textmate does.. The things is that the backslash is insert when it does escape anything: `\\\foo` -> first backslash escapes second (and hence disappears) and third doesn't escape anything and is printed

**Comment by TylerLeonhardt** [comment]
```
"'\\\\\\\\svr-2015-01\\\\User Documents\\\\Carl$0'"
```

This seems to work:

per single backslash:
`\` - JSON escape it
`\` - TextMate escape the single backslash you want
`\` - JSON escape it
`\` - the single backslash you want

since I wanted 2 backslashes, I needed 8 in my snippet.

**Comment by TylerLeonhardt** [comment]
6 also seems to work like you said... but I think that might be a bug/edge case... because 3 slashes (to get 1 slash) isn't valid JSON.

**Comment by TylerLeonhardt** [comment]
by using multiples of 4, it's easy to write logic in language servers that says:
```
path = "\svr-2015-01\User Documents\User Documents"

// for TextMate
path = escapeSlashes(path)

// for JSON
path = escapeSlashes(path)
```

**Comment by TylerLeonhardt** [comment]
btw, dropping all this here for anyone else who hits this issue.

**Comment by msftrncs** [comment]
Any idea/explination why this only affects when the completion includes quote characters?

**Comment by TylerLeonhardt** [comment]
@jrieken this means that any other client of the LSP must handle these TextMate constructs. Is this documented somewhere?

**Comment by TylerLeonhardt** [comment]
I'm afraid to make this change and break our other editors

**Comment by TylerLeonhardt** [comment]
@msftrncs my guess is that it's because of the `$0` not the quotes. The `$0` says "hey I'm a template" go tell Textmate to do the heavy lifting where without the `$0` it's treated as just a plain string.

Just a guess though

**Comment by msftrncs** [comment]
ahh, of course, because now its a template string, it gets processed according to template processing rules, but that means that the `\` escaping rules will only apply in that situation then, and so not as simple as just always multiplying all the `\`.  I'm pretty sure this behavior didn't start until the change to move the cursor behind the quote in the completions of file paths, but I hadn't used completions of UNC paths in a while.

**Comment by TylerLeonhardt** [comment]
exactly. I'm happy to make that change as long at it's doc'd somewhere.
