### ISSUE TITLE
Localizaton of jsonValidation schema

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#78737]
We are using contributes.jsonValidation to provide a schema for our own json settings file.  VS Code displays description from the schema when hovering on keys in our settings file.

There doesn't appear to be a way to localize those descriptions in the schema, or a way to vary the schema path in package.json based on the current language.

If there is a way to accomplish this, let me know.  Otherwise, I'd like to suggest VS Code add support for localization of schema json files either using a similar approach as package.json (package.nls.json), or allow a separate uri to be provided per supported language within the jsonValidation node in package.json.

Related discussion on localization of schema files: https://github.com/json-schema-org/json-schema-spec/issues/53

**Comment by aeschli** [comment]
You could consider using dynamically created schemas as described here: https://github.com/microsoft/vscode/issues/77433#issuecomment-512726599
The text document provider would let you load the schema of the current language.

**Comment by Colengms** [comment]
Thanks for the pointer.  This approach works.  :)
