### ISSUE TITLE
Vertical lines appear in file browser

### ISSUE THREAD

**Issue by dcolakchile** [microsoft/vscode#78730]
Issue Type: <b>Bug</b>

**How to turn off vertical lines in file explorer?!**

Why do you guys keep adding stuff wherever you see free space?!?!

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.5.0

<img width="271" alt="Screen Shot 2019-08-08 at 17 03 35" src="https://user-images.githubusercontent.com/44586609/62737725-7b1f6e80-b9fe-11e9-9272-f4c6bd24ac34.png">

**Comment by usernamehw** [comment]
/question

https://code.visualstudio.com/updates/v1_36#_tree-indent-guides
