### ISSUE TITLE
How to get back to the old icon set?

### ISSUE THREAD

**Issue by tranvannhat** [microsoft/vscode#78748]
How to get back to the old icon set? 

Can you choose the option between old and new icon sets?

**Comment by WebGhan** [comment]
The new icon is ugly.

**Comment by GaryChangCN** [comment]
Too ugly!!!!!!!!!

**Comment by tranvannhat** [comment]
Let us choose between old and new icon sets!!!!

**Comment by kuangyanit** [comment]
Version 1.36.1 download url:

- mac: https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCode-darwin-stable.zip

- win64
https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-x64-1.36.1.exe

- win32
https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-ia32-1.36.1.exe

In fact, download url is regular. Just like:

- mac:
https://vscode.cdn.azure.cn/stable/[commitId]/VSCode-darwin-stable.zip

- win64
https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-x64-[version].exe

- win32
https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-ia32-[version].exe

You can get the [commitId] and [version] by git tags.

**Comment by tranvannhat** [comment]
> Version 1.36.1 download url:
> 
> * mac: https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCode-darwin-stable.zip
> * win64
>   https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-x64-1.36.1.exe
> * win32
>   https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-ia32-1.36.1.exe
> 
> In fact, download url is regular. Just like:
> 
> * mac:
>   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCode-darwin-stable.zip](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCode-darwin-stable.zip)
> * win64
>   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-x64-[version].exe](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCodeSetup-x64-%5Bversion%5D.exe)
> * win32
>   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-ia32-[version].exe](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCodeSetup-ia32-%5Bversion%5D.exe)
> 
> You can get the [commitId] and [version] by git tags.

I still want other updates, except the icon package

**Comment by kuangyanit** [comment]
> > Version 1.36.1 download url:
> > 
> > * mac: https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCode-darwin-stable.zip
> > * win64
> >   https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-x64-1.36.1.exe
> > * win32
> >   https://vscode.cdn.azure.cn/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeSetup-ia32-1.36.1.exe
> > 
> > In fact, download url is regular. Just like:
> > 
> > * mac:
> >   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCode-darwin-stable.zip](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCode-darwin-stable.zip)
> > * win64
> >   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-x64-[version].exe](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCodeSetup-x64-%5Bversion%5D.exe)
> > * win32
> >   [https://vscode.cdn.azure.cn/stable/[commitId]/VSCodeSetup-ia32-[version].exe](https://vscode.cdn.azure.cn/stable/%5BcommitId%5D/VSCodeSetup-ia32-%5Bversion%5D.exe)
> > 
> > You can get the [commitId] and [version] by git tags.
> 
> I still want other updates, except the icon package

There's nothing I can do about it :(

**Comment by tjx666** [comment]
new icon for the folded code  block is too ugly.

**Comment by natis** [comment]
Revert back to 1.36.1, in settings change Update: Mode to none. My biggest gripe with VS Code has been how updates feel more intrusive than Sublime. I just finally committed myself to VS Code full time from Sublime, but not 100% sure that was the right move.
