### ISSUE TITLE
WorkspaceFolders can't be changed while testing

### ISSUE THREAD

**Issue by manuth** [microsoft/vscode#78740]
## Info
- VSCode Version: 1.37.0
- OS Version: Windows 10 Build 1903

## Steps to Reproduce:
1. Create an extension using vscode-generator-code
2. In a test-file open up a workspace-folder using vscode.workspace.updateWorkspaceFolders

Does this issue occur when all extensions are disabled?: Yes

Feel free to clone my repo https://github.com/manuth/MarkdownConverter/ and checkout the `testrunner-issue` to reproduce the error.

## Expected Behavior
The workspace-folders should be changed.

## Actual Behavior
An error-message occurs in the extension developement host:
```
Extension 'Markdown Converter' failed to update workspace folders: {1}
```

**Comment by bpasero** [comment]
@manuth please try to distill an isolated minimal test case to reproduce via the yo generator for me to run

**Comment by manuth** [comment]
Alright - there you go: https://github.com/manuth/TestExtension
Thanks for the rapid answer! 😄

**Comment by manuth** [comment]
I also verified that when updating workspace-folders from a command via `vscode.commands.executeCommand` causes said issue, too.

* Manually changing the opened folder (which is what I was trying to reach using `updateWorkspaceFolder` in the first place) via `File => Open Folder` is working just fine
* Manually adding a folder to the workspace does not work
* Manually adding a folder to the workspace after opening a folder (`File => Open Folder`) works but stops the debugger

In my test-scenario I try to verify whether my settings are handled correctly in File/Folder/Workspace-mode so opening a folder, closing a folder and opening a workspace are important key-functions to me.

**Comment by bpasero** [comment]
@manuth adding a folder to an otherwise empty workspace or changing the first folder in that workspace currently requires us to restart the extension host. So it is currently not possible to test this, is that what you see?

**Comment by manuth** [comment]
I'm not sure about that.
As manually opening a folder in the extension development host ( `File => Open Folder`) is working without breaking the debugger I don't guess that the fact that the extension host needs to be restarted should cause any trouble.

Sadly I do not know how to debug the extension host itself.

To me it looks like this piece of code is getting triggered:
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostWorkspace.ts#L284-L292

**Comment by bpasero** [comment]
@aeschli looks like this is coming from you via this change:

https://github.com/microsoft/vscode/commit/eee10d2c7f79e05526e555c9a39d57d835d5a40d

But yeah, we currently do not support to test a workspace folder change because we require the extension host to restart in that case.

**Comment by manuth** [comment]
@bpasero should I open up a feature request or is this noted already?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/69335

**Comment by manuth** [comment]
@bpasero do I understand correctly that after this change you still won't be able to change the currently opened folder in vscode but only to manipulate the currently opened vscode-workspace?
