### ISSUE TITLE
Can't install dependencies with npm >= 3.9

### ISSUE THREAD

**Issue by csvn** [Microsoft/vscode#7874]
I was thinking of making a pull request, and tried checking out and building the vscode source, but I get the error `MSVSProject' object has no attribute 'iteritems'` when I try to run `scripts\npm install`. 

![image](https://cloud.githubusercontent.com/assets/8770194/16179512/4f48970e-3668-11e6-905b-fa96240cb9d0.png)

I followed the instructions [How to run from Source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source), and tried out the instructions [Compiling native addon modules](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules) when that didn't work. I can get e.g. bson and node-sass to install and compile native code via node-gyp without issues.

![image](https://cloud.githubusercontent.com/assets/8770194/16179521/a5e12310-3668-11e6-8bf0-7d8c84a1f447.png)

I can't seem to figure out what's causing this issue. Any help is greatly appreciated.

System info:
Windows 10
npm@3.9.6
node@6.2.2
git 2.9.0.windows.1

**Comment by joaomoreno** [comment]
The error occurs in `fsevents`, which is an optional dependency. It is expected to fail in Windows, you can continue as if the error didn't occur.

**Comment by csvn** [comment]
Yes, `fsevents` is optional and should fail, but npm should not exit with error code 1 because of it, preventing further installs or postinstall hook from running.

I figured out the cause of this though, I tried this on another machine where `install` worked. When I updated npm it stopped working. The latest working npm version seems to be 3.8.9. npm@^3.9.0 seems to cause the `install` to fail.

I haven't figured out what change causes this, but it might be good to have a heads up in the "Development workflow" section, until this is sorted out.

**Comment by lurdan** [comment]
Also, it should be fixed because npm stopped at the fsevents so following modules won't be set up.
(I've been required to do so manually, npm install vscode-languageclient, vscode-languageserver, jsonc-parser, ...etc)

**Comment by joaomoreno** [comment]
Oh. It always returned error code 0. `3.9.0` might've changed it, it's worthwhile to look into.

**Comment by joaomoreno** [comment]
npm/npm#12698

**Comment by joaomoreno** [comment]
Meanwhile: use `npm < 3.9`.

**Comment by ramya-rao-a** [comment]
I have a Windows 10 machine with VS 2015. If I use  `npm < 3.9`, `node-gyp` [fails](https://github.com/nodejs/node-gyp/issues/972) while installing `onigurama` module. 
What I ended up doing was to remove `fsevents` from npm-shrinwrap.json and get the latest npm. Install then runs without any errors. Even then I had to install `native-keymap` manually.

**Comment by ramya-rao-a** [comment]
@joaomoreno Below is the part of the `npm install` log that fails while installing onigurama module.
Using latest npm solves this for me. This might be specific to VS 2015. 
```
> oniguruma@6.0.1 install C:\...\vscode\node_modules\oniguruma
> node-gyp rebuild


C:\...\vscode\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\ramyar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  regcomp.c
  regenc.c
  regerror.c
  regexec.c
  regext.c
  reggnu.c
  regparse.c
  regposerr.c
  regposix.c
  regsyntax.c
  regtrav.c
  regversion.c
  st.c
  ascii.c
  big5.c
  cp1251.c
  euc_jp.c
  euc_kr.c
  euc_tw.c
  gb18030.c
  iso8859_1.c
  iso8859_2.c
  iso8859_3.c
  iso8859_4.c
  iso8859_5.c
  iso8859_6.c
  iso8859_7.c
  iso8859_8.c
  iso8859_9.c
  iso8859_10.c
  iso8859_11.c
  iso8859_13.c
  iso8859_14.c
  iso8859_15.c
  iso8859_16.c
  koi8.c
  koi8_r.c
  mktable.c
  sjis.c
  unicode.c
  utf16_be.c
  utf16_le.c
  utf32_be.c
  utf32_le.c
  utf8.c
  win_delay_load_hook.c
C:\Users\ramyar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\...\vscode\node_modules\oniguruma\build\oniguruma.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ramyar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ramyar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...\vscode\node_modules\oniguruma
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ramyar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@6.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\...\vscode\npm-debug.log

```

**Comment by Tyriar** [comment]
@joaomoreno installed VS 2015 with Windows 10 SDK and C++ tools, installed Python 2.7, added it to PATH and had a PYTHON environment variable set too. Nothing was obvious to me, I've only successfully set up vscode dev on Windows once though.

**Comment by joaomoreno** [comment]
nodejs/node-gyp#972

**Comment by Tyriar** [comment]
@ramya-rao-a did you end up getting around this issue? I'm running into it on my Windows 10 laptop and `npm@next` is not as option since it's v3.10.

**Comment by ramya-rao-a** [comment]
@Tyriar Did you remove `fsevents` from npm-shrinwrap.json ?

**Comment by Tyriar** [comment]
@ramya-rao-a nope. If that is the fix, any idea why this happens on some Windows 10 machines and not others?

**Comment by ramya-rao-a** [comment]
@Tyriar What are your errors around? The `onigurama` or `fsevents`?

**Comment by Tyriar** [comment]
@ramya-rao-a `__pfnDliNotifyHook2` error on `oniguruma`

**Comment by JustinPealing** [comment]
I've been having this issue but fixed it by using npm 2

```
npm install npm@2 -g
```

**Comment by Tyriar** [comment]
@JustinPealing you may run into other issues with npm 2. They may only be during the packaging steps though so development might be fine.

**Comment by Tyriar** [comment]
Instructions to fix this were added to https://github.com/Microsoft/vscode/wiki/How-to-Contribute#installing-prerequisites by @bpasero, closing this off.
