### ISSUE TITLE
Render whitespace in selection inappropriate appearance with underline.

### ISSUE THREAD

**Issue by purocean** [microsoft/vscode#78746]
- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/7115690/62749899-ca15e400-ba90-11e9-9a00-8830f058e0d1.png)

```
"editor.fontFamily": "Consolas, 'Courier New', monospace, 'Microsoft YaHei UI'"
```

Does this issue occur when all extensions are disabled?: No

**Comment by alexandrudima** [comment]
@purocean How did you get the underscore to show up? Are you using a specific theme?

**Comment by purocean** [comment]
@alexandrudima 

https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
