### ISSUE TITLE
I couldn't install any extention

### ISSUE THREAD

**Issue by Fesho** [microsoft/vscode#78741]
Issue Type: <b>Bug</b>

Hello,
i couldn't install any extention it gives me this message for example
Failed to install 'jundat95.react-native-snippet'.
I tried to download manuallt also failed .This happened all of sudden .

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by donnisnoni95** [comment]
1. Try to backup your extensions first.. go to `C:/Users/{YourUsername}/.vscode/extensions`, after backup, delete the `.vscode` folder or `extensions` folder.
2. Re-installing `vscode` again.
3. After installing `vscode`, copy back your extensions back to `C:/Users/{YourUsername}/.vscode/extensions`.

Thank you..

**Comment by abdolrhman** [comment]
still not working ... ! :///////

**Comment by octref** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release - 

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.
