### ISSUE TITLE
New icons make it very difficult to distinguish intellisense from autocomplete suggestions

### ISSUE THREAD

**Issue by luisrudge** [microsoft/vscode#78744]
Issue Type: <b>Bug</b>

With the new icons, it's pretty hard to distinguish between *actual* intellisense items and autocomplete suggestions :( They used to have different colors, now it's all the same color, same font etc.

![image](https://user-images.githubusercontent.com/941075/62748347-b6399600-ba2e-11e9-9a22-adcdae03066f.png)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ActiveFileInStatusBar|Ros|1.0.3
cypress-snippets|and|1.2.0
vscode-custom-css|be5|3.0.4
vscode-styled-jsx|bla|1.5.0
vscode-tailwindcss|bra|0.2.0
vscode-exports-autocomplete|cap|0.5.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
vscode-pull-request-github|Git|0.9.2
vscode-styled-components|jpo|0.0.26
terraform|mau|1.3.12
vscode-docker|ms-|0.7.0
csharp|ms-|1.21.0
node-debug2|ms-|1.33.0
code-settings-sync|Sha|3.4.1
language-stylus|sys|1.11.0
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|9.2.0
vscode-import-cost|wix|2.12.0
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0

(1 theme extensions excluded)

</details>

**Comment by jiankafei** [comment]
The new icon is ugly.

**Comment by tranvannhat** [comment]
How to get back to the old icon set?

**Comment by WebGhan** [comment]
> The new icon is ugly.

I agree

**Comment by donnisnoni95** [comment]
@tranvannhat install the previous release...

**Comment by donnisnoni95** [comment]
@luisrudge I think that's not a bug..

**Comment by alexamy** [comment]
It would be very nice to have an option to switch old icons back.

**Comment by misolori** [comment]
@LuisBosquez as I mentioned on Twitter, property and text icons in intellisense have always been the same color so that has not changed. 

Using your React example, here's a comparison of the two:

|Before|After|
|---|---|
|<img width="329" alt="image" src="https://user-images.githubusercontent.com/35271042/62795674-1ad70e00-ba8c-11e9-8861-669464d6820a.png">|<img width="382" alt="image" src="https://user-images.githubusercontent.com/35271042/62795908-aa7cbc80-ba8c-11e9-82d2-403bf8305411.png">|

And the rest of the IntelliSense icons still use color:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/35271042/62795803-65588a80-ba8c-11e9-8547-5b05a576194f.png">

If you do encounter any other specific issue please create a new one and I'll take a look.

**Comment by luisrudge** [comment]
@misolori sorry, missed your tweet. The colors haven't changed, but now the distinction between a component pro and a regular autocomplete suggestion is not that great. Although the color wasn't different (my bad), they did have a clear difference: one is 'filled and the other is outlined. You can barely tell the difference between a react component pro and a suggestion

**Comment by DeltaRazero** [comment]
If only icon themes would allow for intellisense icons too..
