### ISSUE TITLE
Dragging and dropping a file into a WSL terminal will use the incorrect '\' separator

### ISSUE THREAD

**Issue by alphagocc** [microsoft/vscode#78751]
- VSCode Version: 1.37.0
- OS Version: 10.0.18632

Steps to Reproduce:

Drag a file to the WSL Shell

File path separator is '\\' not '/'

![image](https://user-images.githubusercontent.com/28982331/62751950-2defdb00-ba98-11e9-8146-72f09e2164ca.png)

Does this issue occur when all extensions are disabled?: Yes
（But in fact I have to enable Remote WSL extensions

**Comment by Tyriar** [comment]
Note to self: For files dragged in via OS they should be resolved in window, dragged in via file explorer should be resolved in ext host. One complication here is for WSL where we need to run wslpath for files dragged from explorer, this might need better WSL terminal detection and marking terminal instances with additional information.

**Comment by eamodio** [comment]
For verification:

Setup: Windows 10

1) Open a PowerShell terminal 
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Open a PowerShell Core terminal
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Open a Command Prompt terminal
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Open a Git Bash terminal 
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `/`
1) Open a WSL terminal 
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `/`, and that the path is translated into a WSL path (e.g. `/mnt/*`)

---

1) Open a PowerShell or Command Prompt terminal
1) Run powershell.exe
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Run pwsh.exe (PowerShell Core)
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Run cmd.exe
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `\`
1) Run bash.exe (from Git)
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `/`
1) Run wsl.exe
1) Ensure that when dragging a file from the desktop or from the vscode explorer the path has the correct slashes `/`, and that the path is translated into a WSL path (e.g. `/mnt/*`)

**Comment by alexr00** [comment]
When I start with a powershell integrated terminal, then run git bash.exe, dragging a file from the desktop into the terminal produces the wrong slashes. From VS Code file explorer it's ok. When the integrated terminal starts as git bash it's also ok.

**Comment by alexr00** [comment]
Finally, when I start with a powershell integrated terminal, then run wsl.exe, dragging a file from the VS Code explorer doesn't produce a path. Dragging a file from the desktop produce a Windows path.

**Comment by eamodio** [comment]
@alexr00 are you on WSL1? Also what version of Windows?

**Comment by alexr00** [comment]
Yes, I"m on WSL 1. Windows version 1901, build 18363.418

**Comment by CM000n** [comment]
I also have this behavior. When I drag and drop a file from a WSL filelist into the WSL bash, VS code creates a path specification that uses "\" instead of "/".

It cannot find the folder/file under the path thus generated by VS Code:
![6574567456nt](https://user-images.githubusercontent.com/7945681/122344289-eca79c80-cf46-11eb-8965-e8cee3758e53.PNG)

If I manually replace the "\" with "/" in the path specification, it no longer has any problems finding the file:
![6574567435345456nt](https://user-images.githubusercontent.com/7945681/122344759-6c356b80-cf47-11eb-8638-5b30b02bbdd9.PNG)


I use Ubuntu-20.04 as WSL 2 and VS Code 1.57.0

**Comment by melink14** [comment]
I also noticed the reverse being true, clicking file names in the WSL terminal will trigger a search with all the slashes reversed. Might be unrelated but including in case it's a clue to the larger problem.

**Comment by CM000n** [comment]
Are there any news on this?
For me, unfortunately, this is one of the most annoying behaviors when developping with VSCode under a WSL
