### ISSUE TITLE
Alt to select multiple line cannot keep selection on right clicking

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#78757]
When using alt+selection to select arbitrary lines of code. I can't use right click to open context menu for these selection. The selection just suddenly disappeared when right click. Other kind of selection are not

![image](https://user-images.githubusercontent.com/1042507/62754827-aa37ed80-ba9b-11e9-8281-82e96931ea95.png)

I don't know if it's a bug or intentional but I think it should be allowed. Or it is not possible?

**Comment by rebornix** [comment]
@sbatten any idea?

**Comment by sbatten** [comment]
@rebornix does multi-selection disappear on focus lost?

**Comment by sbatten** [comment]
@rebornix no clue actually, this reproduces with both native and custom

**Comment by Thaina** [comment]
It seem like this was fix in some recent version (maybe it was fixed for Format on Selection feature of v1.49)
