### ISSUE TITLE
New product icons is disgusting

### ISSUE THREAD

**Issue by WebGhan** [microsoft/vscode#78752]

**Comment by SashaAstanin** [comment]
What was wrong with old icons? Old icons look better imho.

**Comment by donnisnoni95** [comment]
i prefer new icons... it looks simple and modern... the old icons is so bold... anyone agree with me ??

**Comment by SailorMax** [comment]
i prefer old icons... it looks good... the new icons is so thin... anyone agree with me ??

**Comment by dcastil** [comment]
I also prefer the old icons. The new icons have so thin strokes that it takes longer to understand what it represents. Generally I believe that thin strokes in icons and text lead to a worse user experience. I also want to mention that I work with a 4k monitor which probably makes the icons look even thinner.

**Comment by gdh1995** [comment]
I don't like the new icons at the left sidebar, for me their curves are uncomfortable and too slim to read.

**Comment by fasterthan** [comment]
I agree 100%. These new icons look gross. Feature creep is setting in...

**Comment by misolori** [comment]
If you have any comments about the new product icons please comment on #8017, otherwise create a new issue for specific problems.
