### ISSUE TITLE
I wonder why there is no similar hide title bar layout in Linux based OS like Windows VS Code. [Solved]

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/vscode#78755]
A few months ago I created a 'feature request' to make Vs code to hide Title Bar the way Chrome & Firefox let users hide the title bar. 
I thought when we feature request something, it allows to all 'machine' which contain OS. Maybe I was wrong. This is not a good thing though. Prioritizing Windows's Vs code even when it's their own product.

Please give the option to hide title bar the same way Chrome, Firefox & VS code in Windows give for Linux based operating systems.
![Screenshot from 2019-08-09 10-05-09](https://user-images.githubusercontent.com/32763112/62753888-3858a780-ba8d-11e9-8b32-38e1e79a750e.png)

**Comment by PranavBhattarai** [comment]
Choosing custom title bar style did the trick for me, it merges menu bar and title bar into one, although the look is not very neat, it saves at least some screen space.
Try it. It's nice.

Go to File>Preference>Settings and in user settings write "window.titleBarStyle": "custom",

_I am on Ubuntu 19.04_

**Comment by garyng** [comment]
Please **close** this issue if you considered your problem solved; else please remove the `[Solved]` from the title - it's confusing.

**Comment by PranavBhattarai** [comment]
> Please **close** this issue if you considered your problem solved; else please remove the `[Solved]` from the title - it's confusing.

I wanted to close. But got confused how. Now I see where is close option.
