### ISSUE TITLE
open two panels in vscode

### ISSUE THREAD

**Issue by MarshmellowAlone** [microsoft/vscode#78750]
Good morning colleagues, I have a problem and that is when I try to open two panels in the browser the editor hangs. I tried to open one with a js file and in the other I opened the information of an extension, but the editor gives me the following error message.

"Unable to open 'Extension: JavaScript Snippets': Cannot read property 'focus' of null".

After this the editor crashes and does not allow writing to the code file that I opened, even the content of the file does not appear simply the editor is blocked and does not allow anything, I have to restart to use it.

Please could you solve it because I don't know if it is an error but this happens to me, and if it were only in my case, you could help me find the solution.

I say goodbye and I appreciate the improvements that make such a wonderful editor. A greeting :)

**Comment by sandy081** [comment]
@MarshmellowAlone Can you please provide steps to repro?

> I try to open two panels in the browser 
Do you mean in VS Code ?
