### ISSUE TITLE
Hope to add a function list structure tree

### ISSUE THREAD

**Issue by caish00** [microsoft/vscode#78765]
By adding the structure tree of function list, we can quickly understand document structure, function list and locate it conveniently and quickly.
![TIM截图20190809144930](https://user-images.githubusercontent.com/22131400/62759808-f5aac580-bab4-11e9-9cac-052809944295.jpg)

**Comment by jrieken** [comment]
That exists, we call it "Outline" and it lives in the explorer area

<img width="384" alt="Screenshot 2019-08-09 at 10 26 54" src="https://user-images.githubusercontent.com/1794099/62765341-3b08cc00-ba90-11e9-8655-20b3dad50559.png">

**Comment by jrieken** [comment]
If you don't see it, enable it by right clicking the explorer title and selecting outline

<img width="386" alt="Screenshot 2019-08-09 at 10 28 03" src="https://user-images.githubusercontent.com/1794099/62765416-5ffd3f00-ba90-11e9-9f25-70edac429b2b.png">
