### ISSUE TITLE
Grid: custom menu totally broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78768]
Steps to Reproduce:

1. enable custom title on Linux
2. enable grid layout
3. try to use menu

=> :bug: menu seems to open above the window

**Comment by sbatten** [comment]
fixed by e8c6bfcec7029c83a2dfa691c72cd2e77a932745

**Comment by joaomoreno** [comment]
Fix: https://github.com/microsoft/vscode/commit/b6a4220a98cdf874df3feaa16f73559fe708c3b8
