### ISSUE TITLE
No file events for ignored folders

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78763]
1. Open a repo which has `node_modules` in `.gitignore`
2. Run `mkdir node_modules` or `rmdir node_modules` in the terminal

The file explorer never updates when that folder is created or deleted. It works for other folder names.

**Comment by bpasero** [comment]
@joaomoreno is this coming from the watcher exclude setting maybe? Can you check:

```
"files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
}
```

**Comment by joaomoreno** [comment]
Yeah that seems to be the default setting.
