### ISSUE TITLE
product icons from theme extensions

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#78766]
Can you add support product icons from theme extensions?
Your latest experiment with product icons will raise another wave of dissatisfied (#78752).
But restore old icons we do not have the opportunity :/

thank you.

**Comment by octref** [comment]
Marking as duplicate of #78752 then.

**Comment by SailorMax** [comment]
@octref How feature suggestion can be duplicate of decision complaint?

**Comment by misolori** [comment]
@SailorMax see https://github.com/microsoft/vscode/issues/26130 for theming product icons
