### ISSUE TITLE
Uncaught Error: Blocked remote.getCurrentWindow()

### ISSUE THREAD

**Issue by flipp3d** [microsoft/vscode#78764]
version: 1.37.0
提交: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
date: 2019-08-08T01:22:37.660Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

when nodeRequire('electron').remote.getCurrentWindow(),unable to get current window.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@flipp3d how are you calling this code at all?

**Comment by flipp3d** [comment]
> @flipp3d how are you calling this code at all?

console printing

**Comment by flipp3d** [comment]
> @flipp3d how are you calling this code at all?
vscode developer tools,

**Comment by Jinkeycode** [comment]
remote.getCurrentWindow() can be used on vscode 1.36 with Custom CSS and JS，but it is blocked on 1.37，why

**Comment by phatpt8** [comment]
Is there any alternatives to `remote.getCurrentWindow()`? Also why now it marks as as-designed? Can you share a design doc?
