### ISSUE TITLE
New arrow icon cannot be shown completely

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#78761]
![image](https://user-images.githubusercontent.com/32427260/62756571-d018be80-baaa-11e9-927c-58c4388d2ec7.png)

For this, I zoomed the VS Code with <kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>-</kbd>. In the following 4 situations, the second one and third one's arrow icons are broken. 

### zoom level 1
![image](https://user-images.githubusercontent.com/32427260/62756644-238b0c80-baab-11e9-8708-7ef72d1c8246.png)

### zoom level 2
![image](https://user-images.githubusercontent.com/32427260/62756621-1110d300-baab-11e9-82c7-a0216ce7887e.png)

### zoom level 3
![image](https://user-images.githubusercontent.com/32427260/62756607-05bda780-baab-11e9-84f7-e3acb3f505f3.png)

### zoom level 4
![image](https://user-images.githubusercontent.com/32427260/62756614-0b1af200-baab-11e9-97fe-5fa475dc961f.png)

The old triangle works fine but now was replaced by an arrow, which is broken in some situations. Hope it can be fixed in later versions.

- VSCode Version: 1.37.0
- OS Version: deepin 15.11

Steps to Reproduce:

1. Upgrade VS Code to 1.37.0 version
2. Found that the arrow icon is broken

Does this issue occur when all extensions are disabled?: Yes

**Comment by donnisnoni95** [comment]
I have the same issue... 

- VSCode Version: 1.37.0
- OS Version: Linux Mint 19.1 Cinnamon

Steps to Reproduce:

Upgrade VS Code to 1.37.0 version
Found that the arrow icon is broken
Does this issue occur when all extensions are disabled?: Yes

**Comment by lolimay** [comment]
![image](https://user-images.githubusercontent.com/32427260/62757982-9d24f980-baaf-11e9-85dd-e550c6a6b175.png)

The interesting part is that the first arrow icon is always fine. So I think it may not the icon issue but the padding or margin problem?

**Comment by misolori** [comment]
@lolimay do you see this at different zoom levels (which ones) or does this happen all of the time?

I'm also seeing some weirdness when I zoom in (1)and only on the chevron following the file name, but it's not being cut off (I'm on a Mac). I'll test this on Linux to see how it differs.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/35271042/62795080-b9fb0600-ba8a-11e9-845f-a0111908b4b3.png">

**Comment by lolimay** [comment]
> zoom levels

Hi @misolori! I tested 4 zoom levels. And my results have been pasted [above](https://github.com/microsoft/vscode/issues/78761#issue-478807912). As you can see, the first zooms level and fourth zoom level are good. The arrow in the second and third zoom level is broken.

**Comment by lolimay** [comment]
Hi @misolori! I just tested it on my surface pro6 (windows 10). The arrow icon is pretty good with all zoom level. Hope this info could be helpful.

![breadcrumbs_on_surface_pro6](https://user-images.githubusercontent.com/32427260/62796699-6d580f00-bb0c-11e9-84c9-f7a72d3be798.gif)

**Comment by misolori** [comment]
@lolimay very helpful, thank you!

**Comment by andreskebe** [comment]
I am on OS 10.14.5, and I can confirm that with **zoom level 1** none of the arrow icons in the breadcrumbs are fully visible: 
![Screen Shot 2019-08-12 at 3 09 35 PM](https://user-images.githubusercontent.com/16766540/62891284-4fa8c680-bd13-11e9-9d24-84156d55f86d.png)

**Comment by jrieken** [comment]
/needsMoreInfo

I cannot reproduce on MacOS with 1.40 insiders. Can others still repro this?

**Comment by misolori** [comment]
I'm not able to reproduce this anymore using Insiders 1.40 (I'm also on Catalina).
