### ISSUE TITLE
Integrated terminal's cursor becomes normal style

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#78762]
- VSCode Version: 1.37.0
- OS Version: deepin 15.11

Steps to Reproduce:

1. Upgrade VS Code to 1.37.0
2. Found that cursor becomes the normal style when in the integrated terminal

![image](https://user-images.githubusercontent.com/32427260/62757167-f4759a80-baac-11e9-8ccf-e12c62cafb9d.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/32427260/62757229-2f77ce00-baad-11e9-8733-866301e8ce8d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2370
