### ISSUE TITLE
Flickering when resizing of the VSCode window

### ISSUE THREAD

**Issue by terradek** [microsoft/vscode#78778]
Issue Type: <b>Bug</b>

1. Grab any of the corners
2. Resize the window (especially top-bottom, bottom-top)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.0.0-23-generic
Ubuntu 19.04

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.9.3
tslint|eg2|1.0.44
vscode-docker|ms-|0.7.0
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
typescript-javascript-grammar|ms-|0.0.52
vscode-statusbar-json-path|ric|1.4.0
vscode-javascript-booster|sbu|0.11.0
vscodeintellicode|Vis|1.1.9
vscode-js-console-utils|wht|0.7.0

</details>

**Comment by bpasero** [comment]
@terradek can you record this somehow?

**Comment by terradek** [comment]
@bpasero 
PFA
[flickering.zip](https://github.com/microsoft/vscode/files/3488779/flickering.zip)

**Comment by bpasero** [comment]
Does it get any better with setting `"window.titleBarStyle": "custom"` ?

**Comment by terradek** [comment]
@bpasero  It gets worse with this setting
[flickering_title_bar_native-cuscton-2019-08-10_21.28.20.zip](https://github.com/microsoft/vscode/files/3489196/flickering_title_bar_native-cuscton-2019-08-10_21.28.20.zip)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by terradek** [comment]
@bpasero  IMO a bit better
[flickering_title_bar_code_exploration-2019-08-12_11.43.07.zip](https://github.com/microsoft/vscode/files/3491543/flickering_title_bar_code_exploration-2019-08-12_11.43.07.zip)

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/81644
