### ISSUE TITLE
Warning icon is clipped in Extensions panel

### ISSUE THREAD

**Issue by drawcard** [microsoft/vscode#78777]
The warning icon is clipped if the Extensions panel is narrowed:

![image](https://user-images.githubusercontent.com/1435638/62769830-f2c1cc00-bad8-11e9-906b-46460777730b.png)

![image](https://user-images.githubusercontent.com/1435638/62769839-f6ede980-bad8-11e9-9b4b-bb0be3a85daf.png)

- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Open VS Code (latest July update)
2. Go to Extensions panel

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
Fixed

<img width="300" alt="image" src="https://user-images.githubusercontent.com/35271042/62855807-7a832280-bcf3-11e9-9939-a988b9770426.png">

**Comment by misolori** [comment]
Verification steps:
- Open dev tools (`Developer: Toggle Developer Tools`)
- Settings > More > Network conditions
- Set `Network throttling` to `Offline`
- Search for an extensions and make viewlet width narrow
