### ISSUE TITLE
compressed autocompletion box

### ISSUE THREAD

**Issue by KKegel** [microsoft/vscode#78776]
- VSCode Version: 1.37.0
- OS Version: Windows 10 Home (latest update)

Device: Razer Blade 15 2018 Advanced Model
Nvidia GTX 1070 MaxQ Graphics
15 inch UHD Touch Display

As shown in the screenshot, all autocompletion boxes are compressed, so that they are unusable. Clicking inside such a small box works, but of course, no useful selection can be done.

The issue occures both on UHD and FHD resolution on my device. I tried starting VSCode with the GTX 1070 or the included Intel graphics with no difference.

 ![screenshot](https://i.ibb.co/TMY6jHR/screenshot-error.png)

If I setup a Ubuntu KDE Plasma VBox with enabled hardware support and scale it to FHD or UHD resolution, VSCode works just fine inside.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
cc @bpasero @deepak1556

**Comment by octref** [comment]
@joaomoreno Did you ping Ben and Deepak thinking it's a Chrome issue? I haven't seen anything issue like this and don't know where to start.

**Comment by joaomoreno** [comment]
I'd start by trying to repro. If unable to, we gotta reach out to @KKegel and try to debug it live on his machine.

**Comment by KKegel** [comment]
That should be possible on my side.

**Comment by octref** [comment]
Doesn't repro for me. @deepak1556 Do you mind giving it a try?

**Comment by jrieken** [comment]
Let's close this as (1) we weren't able to reproduce and (2) we have redone the layouting of the suggest widget this milestone
