### ISSUE TITLE
Don't provide useless suggestions

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#78779]
- VSCode Version: 1.36.1
- OS Version: 10.14.6

Steps to Reproduce:

1. Open TS file
2. Enter the following, replacing `<CURSOR>` with your cursor
   ``` ts
   const fn1 = (param: string) => {}

   const fn2 = ({ param }: {
     param: <CURSOR>
   })
   ```
3. Type `string`

Expected: no suggestions should appear

Actual: `string` suggestion appears, even though `string` has already been typed and there are no other suggestions. The suggestion here provides no value?

![image](https://user-images.githubusercontent.com/921609/62772203-cc7b3c80-ba96-11e9-965b-9e831106944b.png)

This is annoying because now I have to accept/reject the suggestion before I can continue, e.g. to enter a new line I have to press enter twice.

Does this issue occur when all extensions are disabled?: Yes

**Comment by shiftgeist** [comment]
:thinking: @OliverJAsh has a point.

**Comment by jrieken** [comment]
Setting: `editor.wordBasedSuggestions`

**Comment by OliverJAsh** [comment]
@jrieken I don't see why I should have to disable word based suggestions. They are useful in many cases, just not in this case.

**Comment by usernamehw** [comment]
> Setting: `editor.wordBasedSuggestions`

That is not the case. The issue is that already typed single match should not bother the user.

**Comment by jrieken** [comment]
> The issue is that already typed single 100% match should not bother the user.

Well, the use `editor.acceptSuggestionOnEnter: smart`

**Comment by OliverJAsh** [comment]
The suggestion is still shown, which it doesn't need to be, but that's less of an issue. Thanks @jrieken
