### ISSUE TITLE
on mbp2017 using macos10.14, vscode 1.37 just look like an app that is not supported for retina

### ISSUE THREAD

**Issue by scris** [microsoft/vscode#78772]
Issue Type: <b>Bug</b>

I've just updated from an version months ago to v1.37, and I found everything as if vscode is not supporting retina. 
I'm using mac book pro 2017, so clearly, it must support high dpi.
Not knowing what was damaged.
Reinstall without removing data don't work.

Screen Shot：
<img width="1440" alt="Screen Shot 2019-08-09 at 17 22 55" src="https://user-images.githubusercontent.com/23412857/62768849-5bee1300-baca-11e9-9f37-7660e59b29a9.png">
You will find that Finder is clearer than vscode. This problem does not occur using a previous version of vscode.

Thanks a lot for reading this!

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.29.0
githistory|don|0.4.6
vscode-npm-script|eg2|0.3.8
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vetur|oct|0.21.1
smile-theme|one|1.2.0
material-icon-theme|PKi|3.8.1
vs-picgo|Spa|2.0.4
element-ui-snippets|SS|0.3.5
vscodeintellicode|Vis|1.1.9

(5 theme extensions excluded)

</details>

**Comment by scris** [comment]
ouch.
I have found that if the vscode is out of /Applications, it displays correctly.
But once I move it to the /Applications, it looks blurry.
The same works with v1.36.1

**Comment by scris** [comment]
can anyone know why? thanks a lot!

**Comment by scris** [comment]
anyone here 
I dont know why

**Comment by bpasero** [comment]
Sorry, I do not know. But seems like you resolved this.
