### ISSUE TITLE
Code not recognizing git repos when they are more than one level deep

### ISSUE THREAD

**Issue by bjg2** [microsoft/vscode#78775]
- VSCode Version: 1.37.0
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

Open folder with repos one level deep:
![image](https://user-images.githubusercontent.com/6639273/62769108-a35bab80-ba98-11e9-84c3-fba21cb4d1dc.png)
Git works as expected:
![image](https://user-images.githubusercontent.com/6639273/62769132-ad7daa00-ba98-11e9-9a6c-78aa1827a697.png)
Open folder with repos two level deep (just openned a parent of the folder above):
![image](https://user-images.githubusercontent.com/6639273/62769043-80c99280-ba98-11e9-8894-b9eb5e5e634b.png)
Source control does not recognize git repos:
![image](https://user-images.githubusercontent.com/6639273/62769072-92ab3580-ba98-11e9-988c-ee52e6be299a.png)

This seems to be a new issue, since it worked as expected few days ago... And this is a significant issue for me, sometimes I have even more than two levels of repos, I have to open workspace and add individual folders to workspace to make it work, it takes my time.... I even deleted all my code and tried again, then deleted vscode and all its settings and installing again, nothing helped...

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
> This seems to be a new issue, since it worked as expected few days ago...

I don't think this ever worked.

The repositories might appear once you open a file within them, but Code will only check one directory level down. That's the current implementation. Finding them further down would be too expensive.

For exact situations like this, https://github.com/microsoft/vscode/issues/56504 was implemented: there's a `git.scanRepositories` setting which you can add to your workspace settings with a list of paths to check.

**Comment by bjg2** [comment]
I don't know why or how, but it did work for me until few days ago. Maybe they did appear when I openned a file within them, but now that doesn't happen as well.

![image](https://user-images.githubusercontent.com/6639273/62872769-75879880-bd1e-11e9-855f-b67211e6101d.png)

![image](https://user-images.githubusercontent.com/6639273/62872786-7ddfd380-bd1e-11e9-897c-11ba4f8ab89f.png)

git.scanRepositories would help a bit, but still I would need to enumerate each possible path... For my usecase it would be best to expose the level of depth git is ready to traverse as a setting (defaulted to 1), so I could change it to a bigger value...

**Comment by joaomoreno** [comment]
> Maybe they did appear when I openned a file within them, but now that doesn't happen as well.

Oh, that should work. Are you using symlinks at all in your workspace, or any of its parent folders?

**Comment by bjg2** [comment]
No, no symlinks nowhere...

Now that I try it explicitly it does work the way you say it, and I don't know if it worked any different before. The thing that confused me in the example above was the fact that when I open a file from the first repo it doesn't show repo name in the git, so I was confused  on whether it worked...

Repos:
![image](https://user-images.githubusercontent.com/6639273/62926582-19bc1e80-bdb5-11e9-8d2c-b5dabdb9b540.png)

Git before first file opened:
![image](https://user-images.githubusercontent.com/6639273/62926666-3b1d0a80-bdb5-11e9-8deb-c8ac489ccc6e.png)

Git after first file opened (from any repo):
![image](https://user-images.githubusercontent.com/6639273/62926691-496b2680-bdb5-11e9-8975-fea512e65608.png)

Git after second file opened (from another repo):
![image](https://user-images.githubusercontent.com/6639273/62926720-5851d900-bdb5-11e9-9a70-bf4010516fef.png)

That's good enough for me I guess, I will touch a file from each repo. :) Thanks!
