### ISSUE TITLE
Is it possible to diff block of codes ?

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#78770]
There could be a copied block of code, or just coincidentally look alike, that should refactored into one function

Normally I would create a tmp files and copy those to diff them to see the difference that should be made parameter for it

But I wish there could be some way to just select a code block in two places (could be same file). Then call the command to open diff editor that compare only those two block. And I also wish that it could be edited to those lines of code directly

I'm not sure it possible with the feature we have today. Is it possible by extension in any kind of approach? Or it require to add more extension API first? Or we should not have this feature?

**Comment by IllusionMH** [comment]
Have you tried extension for this task?
Looks like [Partial Diff](https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff) should be good candidate.

**Comment by Thaina** [comment]
@IllusionMH Thank you for suggestion but it not a reflecting on the source though. It just copied diff. Changing the source does not change the diff nor vice versa

**Comment by Thaina** [comment]
@rebornix I was made this not only to propose feature, but for asking that is it possible by any approach. Because I try to look in the extension API and got hesitate. I am not sure it actually possible for vscode API right now

Could you please guide me a bit, which API should I looked for aside from command `vscode.diff`. Because it taken in URL but it not seem like we could specified a range in the URL
