### ISSUE TITLE
Regression: ES6 & TypeScript "go to definition" jumps to import

### ISSUE THREAD

**Issue by jahewson** [Microsoft/vscode#7878]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

I the past week (or two?) the "go to definition" feature for ES6 and TypeScript has changed from jumping to the original definition to jumping to the import at the top of the current file. That's the old broken behaviour which was reported in #263 (and despite that issue being open still, was actually fixed and has worked nicely for several months).

"Peek definition" also suffers from the same problem.

I've opened this as a new issue to report it as regression and not as a feature request 😄

**Comment by dbaeumer** [comment]
This is actually a problem in the tsserver. Moving to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9274
