### ISSUE TITLE
command 'editor.emmet.action.wrapWithAbbreviation' not found

### ISSUE THREAD

**Issue by alexeigs** [microsoft/vscode#78785]
Just started to happen after updating my VSCode to the latest version 1.36.1

Any idea what causes this error and how to fix it?

**Comment by octref** [comment]
Does any other emmet feature work? If you search for `@builtin emmet`, what do you see?

![image](https://user-images.githubusercontent.com/4033249/62793326-32ab9380-ba86-11e9-91ed-6ecc7432156d.png)
