### ISSUE TITLE
VSCode update fails : The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by crowne** [microsoft/vscode#78780]
I finally managed to get my upgrade to work, I'm now on version 1.37.0, I didn't check the version before the upgrade.
I'm logging this bug in the hope that there may be a future solution to the problem encountered.

I tried several times to perform the VS Code upgrade and I would reach the step where it requires a restart but then after a while it would fail with an error saying that the file is being used by another process (log file pasted below).
I was certain that I had no other VSCode instances running, I checked this on the process explorer.
Eventually after the 4th or 5th time, while waiting for the restart to complete or timeout I decided to try closing my WhatsApp window, as I know that this is also an Electron based app.
And Eureka! that solved the issue the upgrade finally finished successfully.
So it seems like there is some kind of shared dependency between Electron apps which prevents the upgrade from completing.

Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Last failure log file:
Aug 09 11:59:00.016 INFO Starting: C:\Users\Neil\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Aug 09 11:59:00.018 INFO Checking for running Code.exe processes... (attempt 1)
Aug 09 11:59:00.028 INFO Code.exe is running, wait a bit
Aug 09 11:59:00.529 INFO Checking for running Code.exe processes... (attempt 2)
Aug 09 11:59:00.540 INFO Code.exe is not running
Aug 09 11:59:00.540 INFO Checking for possible conflicting running processes... (attempt 1)
Aug 09 11:59:00.551 INFO Inno Updater v0.8.0
Aug 09 11:59:00.551 INFO Starting update, silent = false
Aug 09 11:59:00.581 INFO do_update: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
Aug 09 11:59:00.581 INFO move_update: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
Aug 09 11:59:00.581 INFO Reading directory: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code"
Aug 09 11:59:00.582 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\chrome_100_percent.pak" (attempt 1)
Aug 09 11:59:00.582 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\chrome_200_percent.pak" (attempt 1)
Aug 09 11:59:00.582 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 1)
Aug 09 11:59:00.633 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 2)
Aug 09 11:59:00.834 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 3)
Aug 09 11:59:01.285 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 4)
Aug 09 11:59:02.085 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 5)
Aug 09 11:59:03.336 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 6)
Aug 09 11:59:05.137 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 7)
Aug 09 11:59:07.587 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 8)
Aug 09 11:59:10.788 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 9)
Aug 09 11:59:14.839 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 10)
Aug 09 11:59:19.840 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 11)
Aug 09 11:59:25.891 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 12)
Aug 09 11:59:33.092 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 13)
Aug 09 11:59:41.542 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 14)
Aug 09 11:59:51.343 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 15)
Aug 09 12:00:02.594 INFO Get file handle: "C:\\Users\\Neil\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" (attempt 16)
Aug 09 12:00:08.685 ERRO Failed to create file handle: The process cannot access the file because it is being used by another process.

**Comment by Cirieno** [comment]
I've reported this previously, months ago, and the issue was ignored.

The solution I have found is to use the "install update later" option in the notification pop-up, then when you close VSCode the update is performed and you can open the new version (nearly) immediately.

**Comment by gavinr** [comment]
I got this too. Now after I restart, VS Code does not seem to exist
![image](https://user-images.githubusercontent.com/209355/62780609-b3b15d80-ba7b-11e9-946f-9420578e675a.png)
