### ISSUE TITLE
Add logpoint validation

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#78789]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Run Node debugger
2. Add a logpoint somewhere for an invalid expression, e.g. for an invalid identifier: `{iDoNotExist}`

Expected:
- There is some validation/feedback in the logpoint UI to show that this is an invalid expression/identifier, just like it would if you used this expression in the file itself:
   ![image](https://user-images.githubusercontent.com/921609/62774910-1fa4bd80-ba9e-11e9-9c1c-edec236558ee.png)
- The logpoint fails loudly.

Actual:
- There is no validation/feedback in the logpoint UI to show that this is an invalid expression/identifier.
- The logpoint silently fails.

![image](https://user-images.githubusercontent.com/921609/62774881-0c91ed80-ba9e-11e9-9ee5-51c9d7e6a39c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is a fair feature request, however it is not curretnly on our plan thus assigning to the backlog.
