### ISSUE TITLE
Cannot install any extension

### ISSUE THREAD

**Issue by BeemenSameh** [microsoft/vscode#78783]
- VSCode Version: 1.37.0 (user setup)
- OS Version: win 10 1903

Steps to Reproduce:

1.the search of extension work fine
2.if open or download any extension, will failed

Does this issue occur when all extensions are disabled? yes
![image](https://user-images.githubusercontent.com/41084077/62773784-5b8e5180-baa3-11e9-8563-e22fec715a39.png)

**Comment by octref** [comment]
Help -> Toggle Developer Tools, any errors there?

**Comment by BeemenSameh** [comment]
yes
![image](https://user-images.githubusercontent.com/41084077/62805564-abdfd080-baf0-11e9-8801-901a183bc085.png)

**Comment by abdolrhman** [comment]
same !!!!!!!

**Comment by octref** [comment]
@BeemenSameh Would be helpful if you can select and copy-paste those errors here. Thanks.

**Comment by BeemenSameh** [comment]
```
/C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1450 ERR An unknown error occurred. Please consult the log for more details.

/C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5329 Error
extensionsWorkbenchService.install.then.t @ /C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5329

/C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2478 Failed to install 'donjayamanne.python-extension-pack'.
onDidNotificationChange @ /C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2478

/C:/Users/beman/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1450   ERR An unknown error occurred. Please consult the log for more details.
```

**Comment by roblourens** [comment]
Are you connecting with a proxy?

**Comment by abdolrhman** [comment]
I have same error, i dont use proxy, 
i noticed that the one who posted this error from same country,

maybe the DNS, the internet service provider problem ??

**Comment by BeemenSameh** [comment]
@roblourens 
no, i don't use proxy
all thing is alright even browser or when i search on extensions in vs code but if i want download any one, it will appear to me the error message "failed to install <package>"

**Comment by octref** [comment]
@BeemenSameh. From your screenshot, are you trying to access this image? Can you check the "failed to load resource" url and put it here?

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

When you open it in browser, or run the below curl command, what happens?

```bash
curl https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default > python.png
```

**Comment by BeemenSameh** [comment]
@octref 
thanks for help
finally i solve the problem. when you told me "DNS", i try to put a "DNS" in router rather than "blank" and it is work
thanks 😊

**Comment by abdolrhman** [comment]
@BeemenSameh  i said DNS :(

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release - 

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.

**Comment by sandy081** [comment]
Duplicates

https://github.com/microsoft/vscode/issues/78874
https://github.com/microsoft/vscode/issues/78872
https://github.com/microsoft/vscode/issues/78739
