### ISSUE TITLE
Terminal selection for line with promt works incorrectly

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [microsoft/vscode#78787]
- VSCode Version:1.37.0
- OS Version: Kubuntu 18.04

Steps to Reproduce:

1. Open new terminal.
2. **Type a lot of 'Enter' while terminal scrollbar will appear**(Without scrollbar issue is not reproducible).
3. Type text `test a` **(Don't type Enter you need save this text in the line with prompt)**
4. Try to select 'test' with help of mouse.

Expected behavior: Word `test` should be selected
Actual behavior: Selected all text from word 'test' to the end of the line.

**Comment by Tyriar** [comment]
I can't reproduce, are you double clicking test? A gif/video showing the issue would be useful.
