### ISSUE TITLE
quickSuggestions stop working when triggerCharacters from another completion provider contain a-z since 1.37.0

### ISSUE THREAD

**Issue by felixhao28** [microsoft/vscode#78781]
I am not sure if this undocumented change in 1.37.0 (comparing to 1.36.1) is intended, but it surely causes some issues.

Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Write an extension which contributes a completion item provider.
2. Add a-z character to triggerCharacters.
3. Run vscode with that extension. Now the default completion provider will not trigger on key type. (Still triggers on ctrl+space).

Does this issue occur when all extensions are disabled?: No

Example extension code:

```ts
import * as vscode from "vscode";

export async function activate(context: vscode.ExtensionContext) {
    const jsprovider = {
        async provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, completionContext: vscode.CompletionContext): Promise<vscode.CompletionItem[] | vscode.CompletionList> {
            return null;
        },
        resolveCompletionItem(): vscode.ProviderResult<vscode.CompletionItem> {
            return null;
        },
    };
    const triggerCharacters = [".", "/", "@", "<", "=", "_", "$", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
    context.subscriptions.push(vscode.languages.registerCompletionItemProvider({ language: "javascript", scheme: "file" }, jsprovider, ...triggerCharacters));
}
```

Completions marked by a yellow star are provided by a third-party plugin. Please notice how completion results changed before and after a-z characters in triggerCharacters are removed.

![vscodebug](https://user-images.githubusercontent.com/2417391/62773057-c48dbd80-bad3-11e9-9274-7c8648d069de.gif)

**Comment by jrieken** [comment]
Maybe related to https://github.com/microsoft/vscode/issues/76354 (which is a good bug fix). Generally, I would describe the behaviour as correct because trigger characters only target certain providers (those that contribute said characters) but the design is clearly for non-word characters like `.` or `>`, e.g. trigger member completion, and not for all characters (that's what quick suggest is for)

**Comment by jrieken** [comment]
@felixhao28 What's the reason for adding trigger characters a-z?

**Comment by felixhao28** [comment]
So if I understand it correctly, every completion provider will be triggered on characters a-z because quick suggest (unless turned off in the settings). Trigger characters are simply additional characters that triggers the completion other than a-z. By design, trigger characters should not overlap with quick suggest triggers (a-z).

If so, adding a-z to trigger characters was a mistake.

**Comment by jrieken** [comment]
> So if I understand it correctly, every completion provider will be triggered on characters a-z because quick suggest (unless turned off in the settings).

Yes, whenever a "word" is typed (the languages defines what a word is, but generally it's a-z), suggestions are triggered. Additional trigger characters are for scenarios like member completions, e.g `console.` should trigger suggestions to `console.log`, `console.warn` etc

**Comment by jrieken** [comment]
I pushed an additional jsdoc comment to clarify trigger character and how to use them.
