### ISSUE TITLE
could you write extensions for  bootstrap v4 ?

### ISSUE THREAD

**Issue by iloveyo123u1** [Microsoft/vscode#7879]
http://v4-alpha.getbootstrap.com/

**Comment by marvinhagemeister** [comment]
Just curious: what kind of features would that extension have?

**Comment by dbaeumer** [comment]
Chris, assigning to you as this is more a produce decision.

**Comment by chrisdias** [comment]
Hi @iloveyo123u1 -

I'm sorry, I am not sure what the request is here :)  

There are [snippets for bootstrap](https://marketplace.visualstudio.com/search?term=bootstrap&target=VSCode&sortBy=Relevance) in the market that might be useful, please try them out.  

If you are interested in creating an extension for bootstrap, we've got [great documentation](http://code.visualstudio.com/docs/extensions/overview) that will quickly get you started, so give it a try and let us know how it goes!

Chris

**Comment by iloveyo123u1** [comment]
thank you very much ,dear @dbaeumer and  @chrisdias
