### ISSUE TITLE
Wrong behavior in VIM mode when one file shown in two windows

### ISSUE THREAD

**Issue by haccel** [microsoft/vscode#78791]
Issue Type: <b>Bug</b>

When one file opened in two windows ( in one edit page) VIM commands work not correctly.. cursor jumps on random lines and any other issues.
May it is not neseccary open one file in two windows..may be it could be different files.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.93GB free)|
|Process Argv|--folder-uri file:///z%3A/clinic_melsy|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
Please file against the Vim extension you are using.
