### ISSUE TITLE
No info in outline

### ISSUE THREAD

**Issue by jimk66** [microsoft/vscode#78796]
Issue Type: <b>Bug</b>

In version 1.37.0, outline shows "No symbols found in document" no matter what file or language I'm working in. 

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by haobohuiying** [comment]
I hava the similar issue. "No Symbol found " shows  when pressing ctrl+p+@ in all files of C language.
cobiSymbolOutline and inner outline of vs hava the same phenomenon.

**Comment by haobohuiying** [comment]
the issues has been solved by updating the dependences of c/c++ extension;
