### ISSUE TITLE
Activity bar badge is less readable

### ISSUE THREAD

**Issue by rchard2scout** [microsoft/vscode#78794]
The number shown on the activity bar badges (number of unsaved files, number of uncommitted files) has changed in VSCode 1.37. It's now smaller, less readable, and more ugly. This is caused by [this commit](https://github.com/microsoft/vscode/commit/db0b3fde0ee19f80f71005fe56b4af7eb0e0d5c8) by @misolori.

New badge in 1.37.0:
![new icon font](https://user-images.githubusercontent.com/4447610/62777904-2be54680-baaf-11e9-8789-43def66fccb6.png)

Old badge in 1.36.1:
![old icon font](https://user-images.githubusercontent.com/4447610/62777906-2c7ddd00-baaf-11e9-937e-f8f1ba22d695.png)

System information:
Ubuntu 19.04 Disco Dingo, running in VMWare Workstation Player.

**Comment by misolori** [comment]
Thanks for feedback. As you can see, this was intentional as the previous size was too large in relation to the icons in the activity bar. In trying to keep our issue count on a manageable level, I'm going to close this issue as `as-designed`.
