### ISSUE TITLE
JS files unusable while init JS/TS lang features

### ISSUE THREAD

**Issue by vandijkstef** [microsoft/vscode#78795]
Issue Type: <b>Performance Issue</b>

While JS/TS lang features are initialising, JS files are unusable when the file had collapsed code sections; You cannot un-collapse them. Even when the + sign appears, it doesn't work. Also unfolding using the command pallete is unresponsive

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:58:59.274Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3110)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (8.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    72	 15232	code main
    0	    83	  4540	   gpu-process
    0	    87	  4608	   shared-process
    0	    58	 11384	   window (Issue Reporter)
    0	   109	 12368	   window (Untitled-1 - Visual Studio Code)
    0	   129	 19192	     extensionHost
    0	    13	 21596	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
project-manager|ale|10.6.0
html-class-suggestions|And|1.0.7
vscode-intelephense-client|bme|1.1.5
htmltagwrap|bra|0.0.7
phpserver|bra|2.4.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.29.0
vscode-eslint|dba|1.9.0
javascript-ejs-support|Dig|0.5.0
vscode-npm-script|eg2|0.3.8
vsc-material-theme|Equ|29.2.0
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
vscode-power-mode|hoo|2.2.0
vscode-random|jre|1.6.0
presentationmode|jsp|1.1.5
format-indent|Kas|1.3.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
color-highlight|nau|2.3.0
node-modules-resolve|nau|1.0.2
ejs-language-support|Qas|0.0.1
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
todotasks|san|0.5.0
vscode-table-formatter|shu|1.2.1
open-in-browser|tec|2.0.0
wordpress-snippet|tun|1.1.5
vscode-icons|vsc|9.2.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by vandijkstef** [comment]
Unfolding DOES work before the JS/TS init has started

**Comment by gjsjohnmurray** [comment]
See #73041 for an explanation.

**Comment by octref** [comment]
You need to wait for initialization to finish for language features to work. Before it initializes it's the default (indentation-based) folding working.

**Comment by vandijkstef** [comment]
I don't care for language features. There is already a fold set (from memory or smth?) which I cannot unfold.

Im not talking about an enhancement that is failing, but a feature blocking another feature to read my full file. Folding practically is a timebomb now.

Is there a flag to disable re-applying folding on opening?

**Comment by octref** [comment]
OK, I agree while loading TS server it shouldn't stop any regions from unfolding.

**Comment by aeschli** [comment]
![folding](https://user-images.githubusercontent.com/6461412/63325410-572b2980-c32a-11e9-9235-468dcc7289b4.gif)
