### ISSUE TITLE
Preserve search options / Allow default search options to be configured

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#78793]
When I search in VS Code, via for example `ctrl+d`, `ctrl+f`, I get this tiny menu with options like case-sensitive, regex, etc. I'd really like those options to stay the way I like them. But there are two problems with that:

1. **VS Code forgets**  
Not sure if it's after a certain amount of time, app reloads, project switching, or what causes VS Code to forget my choices, but annoyingly often when I press for example `ctrl+d`, the options are back to their application defaults: all `off`.

2. **There's no way to configure the default**  
Only search option I find is something called `Smart Case`, which I'm not interested in. I find no way to configure the default search options to be what I want.

Any chance of getting some settings where I can configure my preferred search options in my `settings.json`? And then initiate with those instead of everything `off` as it does now when I start a new search?

If I can configure the defaults I don't mind VS Code forgetting (would actually be preferred). But if that's not a possibility, an alternative would be that VS Code just always used my last options, instead of forgetting them as it does now. In other words, I'd like one of those solutions, but not both. 😛

---

**VSCode Version:** `1.36.1`
**OS Version:** `Windows_NT x64 10.0.17134`

**Steps to Reproduce:**

1. Press `ctrl+f`
2. Change the search options
3. ...
4. Repeat 1 and check if they're the same

**Comment by octref** [comment]
Btw are you aware up/down error goes to prev/next search?

**Comment by Svish** [comment]
@octref I was aware of the arrow buttons, but not the shortcut key. Useful to know about, but not really what I'm looking for here. I don't want my previous search. I want to do a new search, but with my preferred search _options_.
