### ISSUE TITLE
some keys dose not work in vsc

### ISSUE THREAD

**Issue by yuhaozyx** [Microsoft/vscode#788]
Some keys  like 'h,v,/' dose't work  when i  coded in vsc and try press them,but it's look good outside vsc, so i have to restart vsc to resume it.who can help me to resolve this issues?
On the other hand,i can't switch my system input method  when i  built a new file and typed the file name.The first issues will only happen once in a while.

**Comment by tailgo** [comment]
what is your system and system input method?

**Comment by alexandrudima** [comment]
@yuhaozyx Any more info will be appreciated. OS, input method, maybe even steps?

**Comment by yuhaozyx** [comment]
Thank you very much, but I feel it doesn't matter with vsc,I also encountered such a situation in other software.I guess it may be the result of software conflict, I can't accurately say what specific steps, because it occurred randomly,everything back to normal after the restart.The second issues due to 'shift' key can't work sometimes,so they are the same issues.
os:win 10 pro , 64bit
