### ISSUE TITLE
NPM scripts explorer does not respect files.exclude

### ISSUE THREAD

**Issue by ingdanko** [microsoft/vscode#78803]
Issue Type: <b>Bug</b>

Steps to replicate:
1. Duplicate your npm project folder.
2. Put the duplicated folder into the original folder (you can also rename it for clarity)
3. Open the original folder in VSCode
4. Npm scripts shows both of the package.json (correctly)
5. Create a settings.json:
{
  "files.exclude": {
    "[name of the duplicated folder]": true
  }
}
6. Both package.json still shows in NPM scripts (incorrectly)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.49GB free)|
|Process Argv|D:\User\_Projects\nodeJS\excel|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|1.9.0
vscode-hasher|dee|1.0.1
javascript-ejs-support|Dig|0.5.0
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.8
apacheconf-snippets|eim|1.2.0
vscode-todo-plus|fab|4.13.2
code-runner|for|0.9.12
discord-vscode|icr|3.8.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.8
google-fonts|lio|0.0.1
xml-format|mik|1.0.2
HTMLHint|mka|0.6.0
python|ms-|2019.8.29288
csharp|ms-|1.21.0
debugger-for-chrome|msj|4.11.7
vscode-css-peek|pra|3.0.2
addlocalnetreferences|Raf|0.4.8
LiveServer|rit|5.6.1
esdoc-mdn|sam|0.8.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.4.3
addDocComments|ste|0.0.8
pdf|tom|0.5.0
unity-debug|Uni|2.7.2
highlight-matching-tag|vin|0.9.3
vscode-icons|vsc|9.2.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by egamma** [comment]
The npm script explorer provides a separate setting to exclude files `npm.exclude`.
