### ISSUE TITLE
Unable to use autocomplete (IntelliSense)

### ISSUE THREAD

**Issue by Chevallm** [microsoft/vscode#78801]
Hi,

In this computer I can't use autocomplete.

VS Code version: 1.37.0
Windows_NT x64 6.1.7601
Extentions:

- Angular Essentials 0.6.3

1. Open a .js file
2. Type `document.`
3. Presse `control+space`
4. :bug: Nothing comes except alphabetical words and basic snippets

I except to have some methods like `document.getElementById()`, ...

![image](https://user-images.githubusercontent.com/14332255/62781791-04937700-bab9-11e9-9e48-abc41b3a102e.png)

![image](https://user-images.githubusercontent.com/14332255/62782604-e464b780-baba-11e9-8f47-08b6b8f5a240.png)
)

**Comment by IllusionMH** [comment]
Looks like VS Code tries to find TSServer in a wrong place.

Do you have `typescript.tsdk` in your User or Workspace settings?

**Comment by Chevallm** [comment]
No I don't have any `typescript.tskd` in those folders.

**Comment by IllusionMH** [comment]
Can you check your environment variables `TEMP` and `TMP` in VSCode dev tool and in your System Properties? 

In VS Code you can use **Help > Toggle Developer Tools** and then
`process.env.TEMP` and `process.env.TMP`.

If they contain anything except `C:\Users\<username>\AppData\Local\Temp` it should be removed.

**Comment by Chevallm** [comment]
Gonna check it Monday. Device is at work.

**Comment by Chevallm** [comment]
Hello, my TEMP env var is set to `"C:\Users\mcpichon\AppData\Local\Temp;C:\Users\mcpichon\.nvm\"` in VS code, not anymore in my system. How can I modify my TEMP var in VS code ?

**Comment by Chevallm** [comment]
I can now enjoy autocompletion ! Thanks !
That was the fact that **process.env.TEMP** is my **USER ENV VAR** was set to anything but **C:/Users/<username>/AppData/Local/Temp**
