### ISSUE TITLE
Signature help should be triggered by characters in completion snippets

### ISSUE THREAD

**Issue by georgewfraser** [microsoft/vscode#78806]
This has come up a couple times before:

#13072
#31290

And has been discussed in the language server protocol repo:

https://github.com/microsoft/language-server-protocol/issues/274

When implementing a language server using the language server protocol, it's common to complete parens and place the cursor between them, for example: `println($0)`. However, this creates a problem: the `(` in the snippet doesn't trigger signature help, even though `(` is a signature-help trigger-character.

As a workaround, you can provide `editor.action.triggerParameterHints` as the completion-item command, as discussed in #31290. But this is not a great solution, because `editor.action.triggerParameterHints` isn't part of the language-server-protocol.

The proper solution would be for VSCode to treat signature-help trigger-characters the same, whether they are being typed by the user, or being inserted as part of a snippet.

**Comment by jrieken** [comment]
> But this is not a great solution, because editor.action.triggerParameterHints isn't part of the language-server-protocol.

Adding @dbaeumer - Let's make this a LSP problem first ;-) 

> The proper solution would be for VSCode to treat signature-help trigger-characters the same, whether they are being typed by the user, or being inserted as part of a snippet.

Not sure about that - the occurrence of such characters in a completions doesn't always mean that signature help is needed and it might lead to false signature help showings. I think  the explicit command is pretty specific but, yeah I agree that this is VS Code specific

**Comment by dbaeumer** [comment]
I agree with @jrieken that this can be solved in LSP without any further action in VS Code. In LSP we would need to add a information to a completion item whether it should trigger signature help after insertion. If specified the VS Code implementation could trigger the corresponding action.

I will close the issue since VS Code has everything to support this in LSP.
