### ISSUE TITLE
Git SCM issue ...

### ISSUE THREAD

**Issue by hemantwithu** [microsoft/vscode#78809]
![git-SCM-issue](https://user-images.githubusercontent.com/40213657/62789576-3398f100-ba97-11e9-82b4-8a8b1478e0f5.PNG)
Issue Type: <b>Bug</b>

This issue has been occured multiple times showing a message "No source control providers registered" under source control. Though I can do the few git operation using command line but the basic featues on the files couldn't be done using command line such as file revision history and compare files. 

I would really appreciate your help on this fix .

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Maybe info in https://github.com/microsoft/vscode/issues/61491#issuecomment-440681068 can help you?

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show you?

**Comment by matmel** [comment]
Hi there, I have the same problem as @hemantwithu. My laptop is on windows but connect via remote-ssh to a linux server. When I open a directory which contains a git repository, I have the `No source control providers registered` message.

The output of `Git: Show Git Output` is an error popup which says `command 'Git.showOuput' not found`

![image](https://user-images.githubusercontent.com/6333189/62878265-bf5c8880-bcf6-11e9-9cc5-c5c885d957af.png)

I have not the same problem with the insider version. As you can see the regular vscode is updated to the very new July release 1.37.0.

Other issues I am experiencing are regular disconnection from ssh and my python extension that won't start either. All those issues came at the same time as my git problem.

**Comment by joaomoreno** [comment]
It seems your extension host isn't running at all. Can you run `Developer: Toggle Developer Tools` and check whether there are errors in the console?

**Comment by matmel** [comment]
@joaomoreno Thanks for getting back at me. Here is the ouput of the developer tools console:
```
Extension Host
extensionHost.ts:202 Debugger attached.
remoteAgentConnection.ts:345 A permanent connection error occurred
(anonymous) @ remoteAgentConnection.ts:345
remoteAgentConnection.ts:346 Error: Connection error: Unknown reconnection token.
    at f (remoteAgentConnection.ts:443)
    at i.onControlMessage.o (remoteAgentConnection.ts:177)
    at d.fire (event.ts:572)
    at a (ipc.net.ts:421)
    at e (ipc.net.ts:428)
    at d.fire (event.ts:572)
    at S._receiveMessage (ipc.net.ts:718)
    at _socketDisposables.push._socketReader.onMessage.e (ipc.net.ts:670)
    at d.fire (event.ts:572)
    at g.acceptChunk (ipc.net.ts:236)
    at _register._socket.onData.e (ipc.net.ts:197)
    at Socket.t (ipc.net.ts:28)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at TCP.onStreamRead (internal/stream_base_commons.js:94)
(anonymous) @ remoteAgentConnection.ts:346
abstractExtensionService.ts:154 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:154
extensionHost.ts:201 Extension Host
extensionHost.ts:202 Waiting for the debugger to disconnect...
```

I am not sure but I may have corrupted somehow the remote host vscode server configuration when I changed my default git version by sourcing automatically CentOS software collection [sclo-git25](https://www.softwarecollections.org/en/scls/sclo/sclo-git25/). In other words, before the automatic sourcing I had:

```
[user@host] $ which git
/usr/bin/git
[user@host] $ git --version
git version 1.8.3.1
```

and now:
```
[user@host] $ which git
/opt/rh/sclo-git25/root/usr/bin/git
[user@host] $ git --version
git version 2.5.5
```

**Comment by matmel** [comment]
FWIW, I deleted `~/.vscode-server` on the remote host, and after re-installing all extensions it works again.
