### ISSUE TITLE
Reveal in Explorer should say Reveal in Finder for search results

### ISSUE THREAD

**Issue by ErikHumphrey** [microsoft/vscode#78800]
![image](https://user-images.githubusercontent.com/1473776/62781373-db0d2800-ba85-11e9-8cb1-007e126be9e3.png)

I don't have a Mac handy right now, but I noticed in a screenshot in [the update notes](https://code.visualstudio.com/updates/v1_37) that macOS displays "Reveal in Explorer" in search results. Code suggests that it may not say "Reveal in Finder" on macOS.

https://github.com/microsoft/vscode/blob/71b7c73bb98130a2bdfca7c8f1ecd4180a95f49d/src/vs/workbench/contrib/search/browser/search.contribution.ts#L335-L338

See also [fileActions.contribution.ts](https://github.com/microsoft/vscode/blob/079aef1ec5549171717decf30a9cb3e5b8aeee18/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts), [fileCommands.ts](https://github.com/microsoft/vscode/blob/079aef1ec5549171717decf30a9cb3e5b8aeee18/src/vs/workbench/contrib/files/browser/fileCommands.ts).

If you're not experiencing this issue on macOS, or it's resolved on Insiders, please close this issue.

@skprabhanjan

**Comment by isidorn** [comment]
This action is actually revealing it in the vscode Explorer. Thus we choose that name such that the users would not be confused that we would actually open the Mac FInder.
I am closing this as designed.
@roblourens feel free to reopen if you want.

**Comment by ErikHumphrey** [comment]
Oops! In hindsight, I suppose the "revealInSideBar" l10n identifier shows that it is for that Explorer.

I guess "Reveal in Side Bar" wasn't used (like [with open files](https://user-images.githubusercontent.com/1473776/62792579-97beb380-ba9d-11e9-8b48-282eb639231b.png)) because Search is already in the Side Bar?

**Comment by isidorn** [comment]
I leave that up to @roblourens 
Though I personally like the current name.

**Comment by roblourens** [comment]
Yeah, that view is called the Explorer everywhere in UI.
