### ISSUE TITLE
Multiple cursor backspace affect only one line when using snippets

### ISSUE THREAD

**Issue by Cyber0ni** [microsoft/vscode#78812]
- VSCode Version: 1.37.0
- OS Version: Windows 10

When I try to delete chars with backspace in same placeholders backspace affect only first one and also delete next chars (" =" in this example).
![Alt Text](https://i.imgur.com/jVr8XHv.gif)

This is the snippet that I use 
```json
"For loop": {
	"prefix": "for",
	"body": [
		"for(${1:int} ${2:i} = ${3:0}; ${2:i} < ${4:count}; ${2:i}++) {",
		"\t${0:/*code*/}",
		"}" 
	],
}
```

**Comment by jrieken** [comment]
![Aug-10-2019 09-52-20](https://user-images.githubusercontent.com/1794099/62819370-99977e00-bb54-11e9-8577-558be769c1f8.gif)

🔝 doesn't reproduce for me

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by Cyber0ni** [comment]
Yes, it seems to be **Vim** extension bug. Thank you, **_jrieken_** and sorry for the false alarm.
