### ISSUE TITLE
Format Selection maxes out at 999 lines

### ISSUE THREAD

**Issue by dimmyr** [microsoft/vscode#78811]
Issue Type: <b>Bug</b>

Format Selection and Format Document options max out at 999 lines of code. I tried it with a JSON file. 

![image](https://user-images.githubusercontent.com/8550213/62791119-24fc0b00-ba92-11e9-81a8-c77ef3911fc7.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
regions-with-colors|arg|1.0.3
mssql|ms-|1.6.0
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|2019.5.0

</details>

**Comment by octref** [comment]
I can successfully format JSON files longer than 1000 lines. It doesn't seem you can share your JSON file. Can you find a reproducible case?
