### ISSUE TITLE
Error on save version 1.37.0

### ISSUE THREAD

**Issue by marceloroberto** [microsoft/vscode#78818]
- VSCode Version: **Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)**
- OS Version: **Windows_NT x64 10.0.10586**

Steps to Reproduce:

1. Open Folder;
2. Select and open file;
3. Edit file;
4. Save (With Menu or CTRL+S)
5. Not save the file and freeze VSCode

Does this issue occur when all extensions are disabled?:  **Yes**

**Comment by octref** [comment]
Does this happen in 1.36.0? If not, is there anything specific about the file/folder?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
