### ISSUE TITLE
Tasks executed with TaskScope.Global fail due to missing workspace in VSCode 1.37

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#78817]
- VSCode Version: 1.37.0
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Create a new extension using `yo code`.
2. Add the following to the activate function in the generated code:

```
const task = new vscode.Task({type: 'echo'}, vscode.TaskScope.Global, 'echo', 'globaltask', new vscode.ShellExecution('echo 321'));
vscode.tasks.executeTask(task);
```

3. Run the extension and activate it using the 'Hello World' command. 

Expected behavior: The shell command is run.

Current behavior:

An error appears stating: 'Must have workspace folderglobaltask: echo'.

In the Log (Window) output the following stack trace occurs:

[2019-08-09 10:06:44.898] [renderer4] [error] Must have workspace folderglobaltask: echo: Error: Must have workspace folderglobaltask: echo
    at x.executeCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3288:38)
    at e.command.Promise.all.then.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3286:528)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment]
This is by design. We don't currently support Global tasks.

**Comment by ashgti** [comment]
Does that mean the documentation is out of date? 

I don't see any mentions of the TaskScope.Global not working for task executions. 

Should https://github.com/microsoft/vscode/blob/2b40fd525c193396bfa0ab2cc79963adfe56dff2/src/vs/vscode.d.ts#L5248 exclude TaskScope.Global?

**Comment by kcaze** [comment]
Global tasks used to work on previous versions of VS Code though; it seems like they no longer work due to https://github.com/microsoft/vscode/commit/7705bbd564412e3f31272c3f69573e770b88733e ?

In that diff it seems like a workspace folder argument was added for the terminal name but couldn't that remain optional in order to support Global tasks?

cc @Jma353

**Comment by alexr00** [comment]
@kcaze can you point me to a version where global tasks worked? The "Must have workspace folder" error would have happened even before 
 https://github.com/microsoft/vscode/commit/7705bbd564412e3f31272c3f69573e770b88733e since the workspace folder was still checked.  If this is a regression I want to fix it though.

**Comment by kcaze** [comment]
@alexr00, I just confirmed that this worked on `bdb640354a1404d0bf2226292ac452e8aa23df2d` which is the commit right before `7705bbd`.

The workspace folder is not checked if `cwd` is passed into `ShellExecution` which allows the task to execute successfully. Attached is a minimal repro example of an extension that uses `TaskScope.Global`.

[global-tasks.zip](https://github.com/microsoft/vscode/files/3571597/global-tasks.zip)

**Comment by alexr00** [comment]
@kcaze thanks for making sure I noticed this. I've restored the behavior that existed before with global tasks.

**Comment by kcaze** [comment]
@alexr00, thanks for the fast response and fix!

By the way, are there any issues for discussing the tasks API design and behavior more generally? I see that there's a Task2 in the proposed API but can't find a sort of "master issue" discussing it.

**Comment by alexr00** [comment]
The current issue for the proposed task API is https://github.com/microsoft/vscode/issues/80375 
If you have any feedback on the new task execution type please do add it there!

**Comment by roblourens** [comment]
When I run the original steps, I get `'${workspaceFolder}' can not be resolved. Please open a folder.`

**Comment by alexr00** [comment]
To verify, open a folder or workspace then follow the original steps.
