### ISSUE TITLE
"Stash All Changes" icon does not have refreshed icon

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode#78814]
Issue Type: <b>Bug</b>

The July 2019 update of VS Code introduces a new icon set across the editor, and they look really nice. One place that's missing a new icon, though, is the "Stash All Changes" button in the source control pane. The "Stash Changes" icon right next to it has a new icon, so it would only make sense that "Stash All Changes" has one as well.

![Screen Shot 2019-08-09 at 10 55 50 AM](https://user-images.githubusercontent.com/6618434/62792405-d603a500-ba94-11e9-96ee-b7e083fed780.png)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
project-manager|ale|10.6.0
sort-imports|ama|6.0.2
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.9.3
prettier-vscode|esb|1.9.0
rest-client|hum|0.22.0
elixir-ls|Jak|0.2.25
apex|Joh|1.0.4
debugger-for-chrome|msj|4.11.7
partial-diff|ryu|1.4.0
elm|sbr|0.25.0
code-settings-sync|Sha|3.4.1
rewrap|stk|1.9.1
enumerator|swi|0.0.6
selectline-statusbar|tom|0.0.2
sort-lines|Tyr|1.8.0
vscode-svg-previewer|vit|0.5.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
This one comes from GitLens extension. They have plan to update icon to match new VSCode icons.

See
https://github.com/microsoft/vscode/issues/8017#issuecomment-504295222
https://github.com/microsoft/vscode/issues/8017#issuecomment-504300145

**Comment by misolori** [comment]
Thanks @IllusionMH, this is from GitLens, see https://github.com/eamodio/vscode-gitlens/pull/811 and https://github.com/eamodio/vscode-gitlens/issues/784
