### ISSUE TITLE
Emmet/expansion stops working

### ISSUE THREAD

**Issue by cdCorey** [microsoft/vscode#78826]
Issue Type: <b>Bug</b>

When pressing tab, Emmet should expand and other code should auto-complete. This has worked fine for the last couple years. Recently, this has started to randomly stop working during the day. If I close and restart VS Code, it will work again... for awhile. Sometimes for a few hours, sometimes only for a few minutes.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (2.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.1
vscode-caniuse|aka|0.5.3
Bookmarks|ale|10.4.4
project-manager|ale|10.6.0
atlascode|atl|1.4.3
simple-react-snippets|bur|1.2.2
path-intellisense|chr|1.4.2
woocommerce|cla|1.1.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.3
apacheconf-snippets|eim|1.2.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
svg|joc|0.1.6
sftp|lix|1.12.7
vscode-apache|mrm|1.2.0
vscode-json5|mrm|1.0.0
vscode-scss|mrm|0.6.2
vscode-docker|ms-|0.7.0
php-docblocker|nei|2.0.1
vscode-code-outline|pat|0.2.1
vscode-css-peek|pra|3.0.2
text-power-tools|qcz|1.11.1
htmlescape-vscode-extension|ray|0.0.6
vscode-yaml|red|0.4.1
format-html-in-php|rif|1.5.3
stylelint|shi|0.51.0
vscode-gulp|tan|0.0.4
wordpress-snippet|tun|1.1.5
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Some extensions might be slow and blocking other extension from functioning. Please follow https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions and try to file a new issue. Thanks.
