### ISSUE TITLE
alt+click in terminal resets scroll position and prevents click-on-link

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode#78828]
- VSCode Version: 1.37.0 (system setup)
- OS Version: Win 7 (Windows_NT x64 6.1.7601)

Steps to Reproduce:

1. (optional) set `"editor.multiCursorModifier": "ctrlCmd"` so that links are clickable via `alt`
2. open terminal → hold `enter` until the buffer is large enough for the terminal to be scrollable → scroll up
3. `alt+click` anywhere

**result:** scrolls to the bottom of the terminal. If you `alt+click` on a link, the file doesn't open (note: if you click while the terminal is scrolled to the bottom, it works).

- Does this issue occur when all extensions are disabled?: **Yes**
- Is this fixed in insiders?: **No**

Terminal settings:

![image](https://user-images.githubusercontent.com/5153846/62804449-a2089e00-baed-11e9-839a-a6fdc75dd1d9.png)

**Comment by maxshelley** [comment]
I can replicate this behaviour, VS Code Version: 1.37.0, macOS 10.14.6 (18G87).

> If you alt+click on a link, the file doesn't open (note: if you click while the terminal is scrolled to the bottom, it works).

This is how I found the issue, links in my test results would only work when terminal was scrolled to the bottom.

Happy to help provide more debugging info or anything else that can be useful here.

**Comment by maielo** [comment]
+1 I have exactly same issue as @dwelle

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/2381

**Comment by dwelle** [comment]
While the `alt+click` on link has been fixed, the scroll-to-bottom still happens. This is a problem when you mis-click a link (happens a lot to me) -- it scrolls you down and you need to scroll back up to try and click again, which is a pain when working with long stack traces.

Can we maybe re-open this, or should I create a new issue?

**Comment by Tyriar** [comment]
@dwelle created https://github.com/microsoft/vscode/issues/80496, https://github.com/xtermjs/xterm.js/issues/2401
