### ISSUE TITLE
tslint.json should be jsonc

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78821]
<img width="432" alt="Screen Shot 2019-08-09 at 11 10 12 AM" src="https://user-images.githubusercontent.com/2193314/62799667-465ef600-ba96-11e9-85e1-630d22ed2007.png">

https://palantir.github.io/tslint/usage/configuration/

> tslint.json configuration files may have JavaScript-style // single-line and /* multi-line */ comments in them (even though this is technically invalid JSON). If this confuses your syntax highlighter, you may want to switch it to JavaScript format.

**Comment by aeschli** [comment]
I also sugest we revert. TSLint is soon replaced by eslint anyways.
