### ISSUE TITLE
Pressing <Tab> key adds tab to incorrect editor pane

### ISSUE THREAD

**Issue by fluffynuts** [Microsoft/vscode#7882]
- VSCode Version: 1.3.0-insider, commit f8bb4ade94ba5c9401419d3ec1e12fbe8719e0c1
- OS Version: Windows 10

Steps to Reproduce:

1. open two panes side-by-side
2. press tab in right-hand side (for example); notice that cursor doesn't move. Press tab a lot -- notice that left-hand pane starts scrolling horizontally. Focus left pane with ctrl-1 and see a large number of tabs appended to the current line there.

**Comment by bpasero** [comment]
@egamma I can reproduce, might it be https://github.com/Microsoft/vscode/commit/f8bb4ade94ba5c9401419d3ec1e12fbe8719e0c1 ?

**Comment by Vishal-Isharani** [comment]
in my case it doesn't work in the single panel

**Comment by jnath** [comment]
same for me it doesn't work in the single panel too

**Comment by pocesar** [comment]
oh wow, this one is a real blocker for me, it can really break code and builds when working with 2 panes

**Comment by bpasero** [comment]
We are looking into the issue. Until then please use our stable release.
