### ISSUE TITLE
Intelli-sense crashing application

### ISSUE THREAD

**Issue by twpeele** [microsoft/vscode#78822]
Intelli-sense code completion crashes teh application. Just pick a selection suggested parameter or function from the list and hit enter. Then just sit back and wait for windows to come along to close the frozen app. :( It was such a good tool too... I guess I'll have to find something else.

**Comment by David-Else** [comment]
Use `help:report issue` and supply system details for a proper bug report.

**Comment by isidorn** [comment]
No details provided, thus closing the issue
