### ISSUE TITLE
Debug point goes few steps above

### ISSUE THREAD

**Issue by bharathhs2290** [microsoft/vscode#78827]
Issue Type: <b>Bug</b>

after reching the second debug point the debugger reaches the first debug point again which was already passed

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.15GB free)|
|Process Argv|E:\changiappserver09_08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
project-manager|ale|10.6.0
clipboard-history|Anj|1.0.7
javascript-ejs-support|Dig|0.5.0
prettier-vscode|esb|1.9.0
beautify|Hoo|1.5.0
vscode-wrap-console-log|mid|1.7.2
remote-wsl|ms-|0.39.2
cpptools|ms-|0.24.1
vetur|oct|0.21.1
platformio-ide|pla|1.8.1
ejs-language-support|Qas|0.0.1
partial-diff|ryu|1.4.0
open-in-browser|tec|2.0.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by isidorn** [comment]
What program are you debugging?
Are you using some extension for this?
Do you have exact reproducable steps?
