### ISSUE TITLE
Extension - Allow TreeView inline buttons to always be visible

### ISSUE THREAD

**Issue by tetchel** [microsoft/vscode#78829]
I would like it to be possible for `inline` command buttons to always be visible, ie show up even when the corresponding TreeItem is not hovered or selected.

I'm not sure how this would be be implemented, perhaps a different `group` in the `view/item/context` object (`inline-persistent` instead of `inline`? I know that sucks). Or it could be an option on the TreeItem object itself.

**Comment by sandy081** [comment]
I do not think we would do this as it will cause inconsistency. We do the same in other internal views too.

**Comment by tetchel** [comment]
The inconsistency (which I would call flexibility) is the whole point, but I can respect that decision.
