### ISSUE TITLE
Used variable not highlighted in JavaScript

### ISSUE THREAD

**Issue by Hoto-Cocoa** [microsoft/vscode#78835]
- VSCode Version: 1.36.1 / 1.37.0-insider
- OS Version: Windows 10 Pro Version 1903, Build 18362.239

Steps to Reproduce:

Write code like this. Declare variable in function, and call that variable by any method like set variable value, except by pass to function argument.
![image](https://user-images.githubusercontent.com/21969938/62810310-79f25c80-bb38-11e9-9922-94005993dd58.png)

This is incorrect. `variable` in forEach function meaning `variable` that located at outside of forEach function.
![image](https://user-images.githubusercontent.com/21969938/62810409-d6ee1280-bb38-11e9-8200-79d67f735df4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The dimming is correct. `variable` is never actually used for anything, the code updates the value but never does anything with it
