### ISSUE TITLE
Extension API to focus comments panel

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#78838]
Is there an extension API or builtin command that would let an extension focus the comments thread at the bottom pane?

It could be similar to the `reveal` method on Output Channels.

**Comment by jrieken** [comment]
Pretty sure there is command for that. @sandy081, @isidorn can you help?

**Comment by isidorn** [comment]
Yes, you can use `workbench.action.focusCommentsPanel` command.

**Comment by pelmers** [comment]
Thanks! Somehow I didn't find it
