### ISSUE TITLE
Organize Imports CLI command

### ISSUE THREAD

**Issue by ccorcos** [microsoft/vscode#78839]
Organize imports is a nice editor feature, but if we start using it as an organization, we'll need to enforce that everyone is using it. Thus we need to be able to run this command on all files in our CI, otherwise people will fall out of sync. Also people using other editors won't be able to be on the same page.

**Comment by mjbvz** [comment]
This feature is powered by TypeScript. Please [file a feature request against them](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by ccorcos** [comment]
Here you go: https://github.com/microsoft/TypeScript/issues/32818
