### ISSUE TITLE
Folding icon so ugly and indiscernible in 1.37

### ISSUE THREAD

**Issue by Cicin411** [microsoft/vscode#78848]
let's constrasting them first
![image](https://user-images.githubusercontent.com/19829978/62817147-5e04b000-bb64-11e9-92e9-a40f739539f8.png)

then we could see: 
1.37 ">﹀"  folding icons are so ugly and  **can't easily be discerned** from the file names **because they are so similar with the English alphabets.**
Maybe 1.36 icons also aren't so good but they're better than the 1.37 version.

**Comment by shanyujie** [comment]
<img width="98" alt="屏幕快照 2019-08-10 下午12 34 19" src="https://user-images.githubusercontent.com/22969676/62817548-64e2f100-bb6b-11e9-8f45-7e20e3acf88c.png">
the icon is so ugly,please go back to the icon for the old version.

**Comment by misolori** [comment]
@Cicin411 Hi, can you please clarify:
> can't easily be discerned from the file names because they are so similar with the English alphabets.

I am not seeing this icon to be similar with other characters, can you show me an example where they look similar? And please try to provide better feedback than "folding icons are so ugly" as this is hard to be actionable. Thanks!

**Comment by Cicin411** [comment]
> @Cicin411 Hi, can you please clarify:
> 
> > can't easily be discerned from the file names because they are so similar with the English alphabets.
> 
> I am not seeing this icon to be similar with other characters, can you show me an example where they look similar? And please try to provide better feedback than "folding icons are so ugly" as this is hard to be actionable. Thanks!

Sorry maybe I didn't describe it precisely and exaggerate it.

In v1.36 or before, the folding icons are just icons , they can easily be discerned from the files name tree-list, maybe one reason is that **the filled-triangle icons are totally different** from the English alphabets, and they can easily be spotted at one glance. 

In v1.37 the >﹀icons  are a little **a little bit like** the alphabet-charactors. Icons are constituted with short-lines, just as th alphabet-charactors with lines, as the intent guiding line. **Too many line elements make dazzling and ugly.** 
When the files name tree-list is very long , I can't easily discern them very well in v1.37 as in v1.36 , even if the intent pixels set wider.  

**So could the folding icons back to v1.36 and a little bit bigger ?** Maybe 1.36 icons are too small to select and need to be a little bit bigger.
Of course, not like th folding icons, other icons in v1.37 are so graceful.

**Comment by misolori** [comment]
I see what you mean now, if you'd liked the previous version on the folding icon please upvote #78024. The `>` chevron is a standard icon used across all Microsoft products, which is one of the reasons why we decided to update this icon. I'll close this so that we can consolidate the feedback into that other issue. Thanks for the feedback!

**Comment by nhdoublek** [comment]
I definitely prefer the +/- icons for folding as opposed to the chevron.  Also, the rest of the new icons are difficult to dicern given they are like 1 pixel line width outlines.  I don't have a problem with using the outline style icons, but I think they should be at least 2 pixel width lines so older people who's eyes are not so great can discern them better.
