### ISSUE TITLE
I can't install or see any extensions !! 

### ISSUE THREAD

**Issue by HoSheiMa** [microsoft/vscode#78843]
tell me Failed to install and can't see any photo or logo of extensions or install it 
after update a new version

**Comment by gjsjohnmurray** [comment]
Maybe you have a DNS issue. See #78783

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release. Here is  windows user installer (Let me know which platform are you on will provide the corresponding VS Code installer)

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.

**Comment by sandy081** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by HoSheiMa** [comment]
i'm using Ubuntu 18.4 and after last update a seen this issue

**Comment by sandy081** [comment]
Please follow above comments to provide us logs and check if it is a DNS issue?

**Comment by HoSheiMa** [comment]
I think this problem appear because vscode using a http not https because our cantray block a http urls
