### ISSUE TITLE
Build failure when using applicationinsights-web package

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#78840]
With https://github.com/microsoft/vscode/commit/803e140a230c85f0329154d1f2fdbb971082d1df, I removed the a script tag for loading the applicationinsights-web package and instead switched to using an npm package for it. To get this to work, I had to alias the name of the package in `workbench.js`.

```
'applicationinsights-web': `${window.location.origin}/node_modules/@microsoft/applicationinsights-web/dist/applicationinsights-web.js`
```
The package is namespaced under `@microsoft` and has its own typings, but I found that compilation would fail with "Module not found" if explicit typings weren't provided in the typings folder for it. (And from the comments in the xterm typings, this seems to be from a limitation in the gulp-tsb library?). Having the typings in a subfolder (i.e. in an `@microsoft` folder) would also not work, so I changed the name to remove the namespace.

Build worked fine locally, but then failed for the `optimize-vscode-reh-web` task with a module not found error for `applicationinsights-web`:
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=54106

We either need to be able to handle namespaced packages in the loader, or have some way of specifying an alias for the gulp task

cc @jrieken

**Comment by jrieken** [comment]
> The package is namespaced under @microsoft and has its own typings, but I found that compilation would fail with "Module not found" if explicit typings weren't provided in the typings folder for it.

Yeah, that's on purpose. For performance reasons we tell TS (via gulp-tsb) not to look up files but use what's streamed to it instead. That's why we have the `typings` folder. Doesn't it work when you copy the d.ts-file into that folder?

**Comment by RMacfarlane** [comment]
Yep, it does! 😄 I had the wrong module name in my declaration in the typings file 🙄
