### ISSUE TITLE
Terminal is not working

### ISSUE THREAD

**Issue by umesh2645** [microsoft/vscode#78853]
Issue Type: <b>Bug</b>

Terminal is not opening,Getting error on developer console:
[uncaught exception]: Error: connect ENOENT \\.\pipe\winpty-conin-58588-1-1d54f42c116cca0-2d74dce15300bb98529931bec0b96fcf
onUnexpectedError @ bootstrap-window.js:212
(anonymous) @ bootstrap-window.js:54
emit @ events.js:182
window.onerror @ C:\Users\umeshgupta\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\renderer\init.js:147
n.globals.onerror @ errorTelemetry.ts:20
bootstrap-window.js:215 Error: connect ENOENT \\.\pipe\winpty-conin-58588-1-1d54f42c116cca0-2d74dce15300bb98529931bec0b96fcf
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113)
onUnexpectedError @ bootstrap-window.js:215
(anonymous) @ bootstrap-window.js:54
emit @ events.js:182
window.onerror @ C:\Users\umeshgupta\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\renderer\init.js:147
n.globals.onerror @ errorTelemetry.ts:20
events.js:167 Uncaught Error: connect ENOENT \\.\pipe\winpty-conin-58588-1-1d54f42c116cca0-2d74dce15300bb98529931bec0b96fcf
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113)
exceptionWithHostPort @ internal/errors.js:354
afterConnect @ net.js:1113
bootstrap-window.js:212 [uncaught exception]: Error: connect ENOENT \\.\pipe\winpty-conout-58588-2-1d54f42c116f3b7-041cd06c5a56cb7be5b31f79a5426ee1
onUnexpectedError @ bootstrap-window.js:212
(anonymous) @ bootstrap-window.js:54
emit @ events.js:182
window.onerror @ C:\Users\umeshgupta\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\renderer\init.js:147
n.globals.onerror @ errorTelemetry.ts:20
bootstrap-window.js:215 Error: connect ENOENT \\.\pipe\winpty-conout-58588-2-1d54f42c116f3b7-041cd06c5a56cb7be5b31f79a5426ee1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113)
onUnexpectedError @ bootstrap-window.js:215
(anonymous) @ bootstrap-window.js:54
emit @ events.js:182
window.onerror @ C:\Users\umeshgupta\AppData\Local\Programs\Microsoft VS Code\resources\electron.asar\renderer\init.js:147
n.globals.onerror @ errorTelemetry.ts:20
events.js:167 Uncaught Error: connect ENOENT \\.\pipe\winpty-conout-58588-2-1d54f42c116f3b7-041cd06c5a56cb7be5b31f79a5426ee1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
vscode-docker|ms-|0.7.0
vetur|oct|0.22.0

</details>

**Comment by Tyriar** [comment]
Do you have anti-virus software installed?

**Comment by umesh2645** [comment]
Yes it is my office laptop.

**Comment by Tyriar** [comment]
You will need to get winpty.dll and winpty-agent.exe inside the VS Code install directory whitelisted in your anti-virus.
