### ISSUE TITLE
New notification icons are not very readable

### ISSUE THREAD

**Issue by krupenja** [microsoft/vscode#78857]
- VSCode Version: 1.37
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Generate some notifications.

Does this issue occur when all extensions are disabled?: Yes

Result:

The new notifications icons are so thin that they are barely readable, see '!' and 'i' on the screenshot (on Macbook Pro 13'' Retina display). This is especially problematic if you have less than perfect vision.

![image](https://user-images.githubusercontent.com/26354715/62820348-a5426f00-bb6b-11e9-80fd-9059806cb3bd.png)

Compare e.g. to these icons on Github: the borders are thin but the exclamation mark is bolder and a lot more readable.

![image](https://user-images.githubusercontent.com/26354715/62820365-04a07f00-bb6c-11e9-92d4-9a8563e3f653.png)

**Comment by krupenja** [comment]
Note that the error notification icon (red, X inside O) looks a lot better in my opinion:
![image](https://user-images.githubusercontent.com/26354715/63026911-a7326800-beb4-11e9-8336-5fbd42533aab.png)

**Comment by misolori** [comment]
I think we can bump the size of the icon (16px => 18px) and slightly increase the size of the `!` inside:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/35271042/66334317-af73b600-e8ed-11e9-9aaf-65be690f7561.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/35271042/66335348-bbf90e00-e8ef-11e9-945d-49be5b04d70c.png">


@bpasero thoughts?

**Comment by bpasero** [comment]
@misolori everywhere or only in notifications?

**Comment by misolori** [comment]
@bpasero only in the notifications panel. In the screenshot above you can see the comparison between the two.

**Comment by bpasero** [comment]
@misolori I can check it out on a branch to give more feedback
