### ISSUE TITLE
Diff tool will not identify tabs additions if there is any real code change

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#7885]
- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10

Steps to Reproduce:
1. Put some tabs before code like below
   ![image](https://cloud.githubusercontent.com/assets/876920/16189801/c9257c76-370e-11e6-849a-a02d7ad31015.png)
2. Add some real code change
   ![image](https://cloud.githubusercontent.com/assets/876920/16189818/dd58dd0a-370e-11e6-86f2-9e34ecaae5d1.png)

With this tiny bug, you might check in additional tabs/control characters (this happens a lot when your editor has auto-format turned on) blindly and people might don't love you any more :cry:

**Comment by alexandrudima** [comment]
Let's track in #18353
