### ISSUE TITLE
code insiders helper process is at 100% CPU

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#78864]
No specific actions reproduce it. i  But this has never happened until yesterday. Perhaps it was the latest insider? It actually caused my iMac Pro's fans to turn on for the first time ever, which is what clued me into it.

![image](https://user-images.githubusercontent.com/1202528/62822571-5c7ebc00-bb53-11e9-8513-722d676b040d.png)

Issue Type: <b>Performance Issue</b>

VS Code version: Code - Insiders 1.37.0-insider (5e08ee01b7daee99cdda2456f19d77e715fb8762, 2019-08-05T21:16:01.319Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   10	   131	 21298	code-insiders main
    4	    98	 21299	   gpu-process
    6	   197	 21449	   shared-process
    0	     0	 25770	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   11	   328	 21978	   window (villains.vue — vue-getting-started)
    3	   197	 21979	     extensionHost
    0	    98	 21985	       electron_node eslintServer.js 
    0	    33	 21986	       electron_node server.js 
    0	   262	 21987	       electron_node vueServerMain.js 
    0	    33	 22070	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=21979
    0	   131	 25688	       electron_node server.js 
    0	    33	 21980	     watcherService
    0	     0	 22270	     zsh -l
   41	    66	 25768	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (villains.vue — vue-getting-started)
|    Folder (vue-getting-started): 465 files
|      File types: js(131) vue(109) json(71) scss(60) html(17) ico(16)
|                  browserslistrc(15) png(15) DS_Store(10) env(6)
|      Conf files: settings.json(16) package.json(15) launch.json(15);
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.801.1
vscode-browser-preview|auc|0.5.9
spellright|ban|3.0.46
vscode-markdownlint|Dav|0.29.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
vscode-pull-request-github|Git|0.9.2
angular-essentials|joh|0.6.3
Angular1|joh|0.2.1
Angular2|joh|8.1.1
helloworld-sample-statusbar|joh|0.0.1
read-time|joh|0.2.0
vscode-peacock|joh|3.0.1
dotenv|mik|1.0.1
azure-pipelines|ms-|1.155.0
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.657
debugger-for-chrome|msj|4.11.7
angular2-inline|nat|0.0.17
angular-console|nrw|8.0.10
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.1
vue-vscode-snippets|sdr|1.7.1
code-settings-sync|Sha|3.4.1
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by octref** [comment]
Please report to https://github.com/vuejs/vetur. Would be great if you can attach a profile: https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md.
