### ISSUE TITLE
Tmux and integrated terminal

### ISSUE THREAD

**Issue by chadrien** [Microsoft/vscode#7886]
- VSCode Version: 1.2.1 (fe7f407b95b7f78405846188259504b34ef72761)
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open the terminal window (<code>cmd+`</code>)
2. Open a new tmux session (`tmux new`)
3. Close the terminal window (<code>cmd+`</code>)
4. Open the terminal window (<code>cmd+`</code>)

When using tmux in terminal window everything works fine, but as soon as you close the window and reopen it the rendering is broken. If you hit `ctrl+d` several times to close the terminal in the and you have a `Cannot set property innerHTML of undefined` error and end up having to `reload window` for the terminal to be working again.

![vscode-tmux-terminal](https://cloud.githubusercontent.com/assets/1788218/16190203/68737e9e-36de-11e6-9dd3-0208e32de7a1.gif)

You can't see it obviously but in this gif, when I reopen the terminal window I did another `ls`.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by chadrien** [comment]
Correct, it's been fixed in insider version.

Thanks

**Comment by Tyriar** [comment]
Awesome, thanks for confirming :smiley:
