### ISSUE TITLE
Replace the java file icon with the old java cup icon

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#78865]
Issue Type: <b>Feature Request</b>

change java icon to the java cup icon.
issue is not caused by any extension, i have rechecked it by installing new version of stable vscode.
also tried it with insiders installation by disabling all the extensions

recreating this issue as https://github.com/microsoft/vscode/issues/78421 is closed and i am not able to reopen it.

VS Code version: Code - Insiders 1.37.0-insider (0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b, 2019-08-02T21:22:13.578Z)
OS version: Windows_NT x64 10.0.17134

![java icon](https://user-images.githubusercontent.com/9264813/62822610-97104500-bba3-11e9-9023-bea287c9d3c0.png)

**Comment by sanket-bhalerao** [comment]
related issue https://github.com/microsoft/vscode/issues/78421

**Comment by sanket-bhalerao** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [change java icon to the java cup icon. (#78421)](https://www.github.com/microsoft/vscode/issues/78421)
> 
>     * [VS code crashing(Window has crashed) (#78616)](https://www.github.com/microsoft/vscode/issues/78616)
> 
>     * [[java] Syntax highlighting for SQL on Java Strings (#49052)](https://www.github.com/microsoft/vscode/issues/49052)
> 
>     * [Add Java to "Tools and Languages" section of the welcome page (#47169)](https://www.github.com/microsoft/vscode/issues/47169)

duplicate, but the issue is still there and i am not able to reopen https://github.com/microsoft/vscode/issues/78421

**Comment by misolori** [comment]
We use [seti-ui](https://github.com/jesseweed/seti-ui/) as our default file icons so please file an issue with that extension.
