### ISSUE TITLE
Wrong Autocomplete

### ISSUE THREAD

**Issue by ShiaForced** [microsoft/vscode#78863]
After closing style value in style attribute with semicolon, autocomplete, which is Emmet, starts to behave strangely and suggests me style properties inside a tag instead of normal tags. For instance, when I try to type h1 tag inside header tag, it suggests me to use height property instead and that's the only option.

**Comment by octref** [comment]
Can you post a gif or the code to illustrate the problem?

**Comment by isidorn** [comment]
No details provided thus closing the issue
