### ISSUE TITLE
Icon readabilty regression

### ISSUE THREAD

**Issue by qt1** [microsoft/vscode#78875]
Issue Type: <b>Bug</b>

The new icons are very hard to work with with light theme.

E.g. the debug/stop is hardly visible.
Slowing work and annoying.

Is there a simple way to revert the version ?
(using apt) ?

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 4.15.0-55-generic

**Comment by misolori** [comment]
The only way to revert is to download a previous version. If you have any additional comments please leave them on #8017. Thanks!

**Comment by qt1** [comment]
Thanks for your answer @misolori 

Unfortunately the refereed thread  related to design and consistency.

This is not a problem of taste. not is it beautiful enough or is it modern or cool.

The new icons are significantly **less visible** A big problem for people with less-then-perfect eyesight.

A show stopper for me. I how have one system with bad icons and a couple more with a "this is not the last version" icon on.

Since I do not expect designers admit a failure I guess the option left is to wait till someone will publish an extension with alternative icons.

**Comment by misolori** [comment]
@qt1 just as an FYI: all of our icons are the same that are used in [Microsoft's iconography](https://docs.microsoft.com/en-us/windows/uwp/design/style/icons) (also known as the Microsoft Design Language).

**Comment by qt1** [comment]
@gjsjohnmurray here is the visual studio icon:

![image](https://user-images.githubusercontent.com/7355327/62890608-7d5e3180-bd4c-11e9-92cc-118667fca365.png)

This new "lighter than a pixel" look is just less functional and it is harder on the eyes.
IMHO This is a working tool, not some fancy design contest. First priority is to make it functional and convenient.

**Comment by qt1** [comment]
@misolori I have lookd at the Microsoft's iconography link.

There is nothing there saying icons should be invisible.
When debugging there is **A Lot** of information going on, sometimes from 3 different screens.
The last thing you want to do is to waste time looking for a run or stop or step icons.

You can definitely treat this as an accessibility issue!

Thanks

**Comment by misolori** [comment]
> There is nothing there saying icons should be invisible.

I don't think I follow, can you please elaborate?

**Comment by qt1** [comment]
@misolori 

I think that there are two major goals for icons:
1. Functionality - user should be able to use them at a glance: find, understand, distinguish
2. Graphic appeal - contribute to the brand and sales (for new users)

I am already using the product so sales is not the issue.

However, I am not that young and my eyesight is less sharp then what is used to be.
For me an icon that I need to spend time finding on a cluttered screen and then I need to stare at in order to to decipher it is not a good icon..

The new icons are significantly harder to see and to distinguish. This makes them less visible and less usable. 

Making all icons almost the same, and making them blend with the background may be considered by some to be of good graphical taste however this completely defies the basic purpose of icons and make them less usable.

I hope this clarifies
