### ISSUE TITLE
Extensions don't install

### ISSUE THREAD

**Issue by akilany** [microsoft/vscode#78872]
When i try to install a new extension, it does not install. The app Suggests me to download it manually instead.
p.s. the "details" on every extension doesn't appear either.
![Capture](https://user-images.githubusercontent.com/48571369/62823837-1a2a9e80-bb96-11e9-89d0-c50d588c4bba.PNG)

**Comment by gjsjohnmurray** [comment]
Maybe you have a DNS issue. See #78783

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release. Here is  windows user installer (Let me know which platform are you on will provide the corresponding VS Code installer)

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.

**Comment by sandy081** [comment]
#78783 seems to be a DNS issue.

Can you try to access this image? https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by akilany** [comment]
@sandy081 
i can't access the image. I think the problem with the new update if i install the previous version, it may work.
also i don't know how to change my DNS

**Comment by akilany** [comment]
@sandy081 
[2019-08-12 03:17:08.134] [sharedprocess] [info] main {"machineId":"4ebaadf030bca2851724866d442450c15184f60359164ff3f1f4e5a30fc28fe3"}
[2019-08-12 03:17:10.187] [sharedprocess] [info] Installing extension: visualstudioexptteam.vscodeintellicode
[2019-08-12 03:17:11.196] [sharedprocess] [error] Failed to install extension: visualstudioexptteam.vscodeintellicode 
[2019-08-12 03:17:48.148] [sharedprocess] [info] Starting to clean up unused language packs.

**Comment by akilany** [comment]
@sandy081 @gjsjohnmurray 
thank you it was a DNS issue. I changed my DNS settings and it worked.
