### ISSUE TITLE
Show Fixes: not giving right option when TDD (expected)

### ISSUE THREAD

**Issue by georgebatalinski** [microsoft/vscode#78871]
- VSCode Version: 1.37.0-insider
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. write `expect(x).ToEqual(expected)`
2. where the intention of `expected` is to create a new variable 
3. Show fixes - gives the wrong option (says correct spelling)
4. Expected option would be `Declare variable`

![screenshot](https://i.postimg.cc/QtcYjS4L/vs-code-spell-error.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a complete code example as text

**Comment by georgebatalinski** [comment]
@mjbvz this is all i have in the file 

```
import { getElectivesGrades } from './carousel';

describe('getElectivesGrades', ()=> {
  it('should get', ()=> {
    expect(getElectivesGrades([]).toEqual([9]);
  });

});

```

**Comment by mjbvz** [comment]
Please share a complete code example, including the contents of `carousel` and a list of the packages you have in your package.json
