### ISSUE TITLE
please help i cant install anything on vscode

### ISSUE THREAD

**Issue by Mrjoker00200** [microsoft/vscode#78874]
Issue Type: <b>Bug</b>

so now i reinstalled my vscode after i reinstalled my windows,
i was okay before downloaded python and many extensions, but no when i search for extensions i can't even see the thumbnail or any info about it and when i click install it gives me an "Failed to install 'ms-vsts.python.'"
please help i need that app to work as soon as possible.
thanks.
![Capture](https://user-images.githubusercontent.com/33162573/62825984-1896b180-bb69-11e9-9716-c713508a1958.PNG)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by akilany** [comment]
I have the same problem

**Comment by Mrjoker00200** [comment]
I tried manually and it installed

**Comment by gjsjohnmurray** [comment]
Maybe you have a DNS issue. See #78783

**Comment by Mrjoker00200** [comment]
@gjsjohnmurray
Thanks bro the issue was really the DNS

**Comment by sandy081** [comment]
If you are able to repro it, can you please try with previous release. 

https://az764295.vo.msecnd.net/stable/2213894ea0415ee8c85c5eea0d0ff81ecc191529/VSCodeUserSetup-x64-1.36.1.exe

Would like to understand what caused this change.
