### ISSUE TITLE
GL ERROR

### ISSUE THREAD

**Issue by thespy7** [microsoft/vscode#78878]
Issue Type: <b>Bug</b>

1) Fesh install of VS Code
2) Start of VS Code
3) Blank window (or just a transparent window) of VS Code
4) Nothing appears, the only way to close that process is via the task manager.

If I start it through a CMD Terminal, same result but the output of the terminal
give this error :

`GL ERROR :GL_INVALID_OPERATION : glSetDrawRectangleCHROMIUM: failed on surface`

I also found a workaround by starting VS Code with the extra parameters : 
`Code.exe --disable-gpu --disable-gpu-compositing`

All graphics Drivers are up to date.
HW my laptop :

- Intel HD Graphics 3000
- NVIDIA Quadro 2000M

Thank you

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.88GB (26.21GB free)|
|Process Argv|--disable-gpu --disable-gpu-compositing|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by thespy7** [comment]
1) I uninstalled the previous version of VS Code (I didn't removed manually the remaining files/entries

2) I pickup your version :
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

3) Install process went fine.
4) And at the first launch, it worked (no extra parameters were needed)!

Is that version a night build or beta?
But thank you for the support !


VS Code version: Code - Exploration 1.37.0-exploration (960208fdf9aa06e6892aa14c9c84ddd607fbeb2f, 2019-07-31T07:00:13.817Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (26.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none
