### ISSUE TITLE
Show Fixes icon is blue for no good reason

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#78870]
Issue Type: <b>Bug</b>

See screenshot, why is the show fixes suddenly blue here and yellow everywhere else? I assume it is because it is ghosted as unused, but that should not make the icon blue?

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.1.18-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz (8 x 3482)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.17GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.46
markdown-preview-github-styles|bie|0.1.6
vscode-dash|dee|2.2.0
prettier-vscode|esb|1.9.0
shell-format|fox|6.1.1
vsliveshare|ms-|1.0.657
debugger-for-chrome|msj|4.11.7
LiveServer|rit|5.6.1
shellcheck|tim|0.8.1
quokka-vscode|Wal|1.0.240

</details>

![show-fixes-blue](https://user-images.githubusercontent.com/12832280/62823065-82708480-bb84-11e9-8273-49edaebfc61e.png)

**Comment by misolori** [comment]
This icon is is actually [preferred code actions](https://code.visualstudio.com/updates/v1_32#_auto-fix-and-preferred-code-actions):
<img width="466" alt="image" src="https://user-images.githubusercontent.com/35271042/62823444-b11b3a80-bb45-11e9-8db8-04c3529854d2.png">

And these are quick fixes:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/35271042/62823486-0c4d2d00-bb46-11e9-996b-6f626b25dd93.png">

Let us know if you have any other issues.
