### ISSUE TITLE
after type in `git commit -` my terminal crashed

### ISSUE THREAD

**Issue by KsRyY** [microsoft/vscode#78886]
- VSCode Version: 1.37.0-insider
- OS Version: Ubuntu WSL Remote on Windows_NT x64 10.0.18956

Steps to Reproduce:

1. Open a command window.
2. Change into a git directory.
3. Type in `git commit -` (No matter how, like type in `g-` and type `it commit ` between them)
4. The terminal will crash. The editor is fine.

Does this issue occur when all extensions are disabled?: Yes(I disabled everything except `Remote:WSL` because this happens in a WSL window)

**Comment by KsRyY** [comment]
***Note: This will happen in other terminal window. I may need to open an issue in Microsoft/WSL repository. If you want, close this issue(because I don't know if I could close it here)***

**Comment by KsRyY** [comment]
Spotted problem.

**Comment by KsRyY** [comment]
Possibly a set of dotfile causes this problem. The maintainers may close this issue.

**Comment by summarek** [comment]
@KsRyY How did you fix it? i have same issue.

**Comment by rafaelnogueira1** [comment]
Hi guys, i'm having the same problem here, what was the fix for it?

**Comment by mufeez-amjad** [comment]
Also having the same issue.

**Comment by Tyriar** [comment]
FYI @craigloewen-msft

**Comment by craigloewen-msft** [comment]
This seems to be related to an issue when running `zsh`. 

We also have an issue on the WSL Github repo: https://github.com/microsoft/WSL/issues/4430

And there's one on the Terminal repo too: https://github.com/microsoft/terminal/issues/2518

You can follow those issues as well for more updates! :)
