### ISSUE TITLE
Snippet cannot escape closing bracket inside conditional insertion variable replacement

### ISSUE THREAD

**Issue by adamvictorclever** [microsoft/vscode#78883]
Issue Type: <b>Bug</b>

I'm essentially trying to conditionally include a line in a snippet if the TM_DIRECTORY variable matches something. A simplified version of what I'm trying to do looks like this: `${TM_DIRECTORY/(.+)/${1:+import { hello } from world}/}`, where if TM_DIRECTORY matches a pattern (in this case anything) it inserts the line `import { hello } from world`. 

However, I cannot seem to escape the closing bracket of `hello }`. I've tried using various numbers of backslashes in front of it, and none seem to work. I've put the various results I'm seeing below:

`${TM_DIRECTORY/(.+)/${1:+import { hello \} from world}/}` results in `import { hello  from world`
`${TM_DIRECTORY/(.+)/${1:+import { hello \\} from world}/}` results in `import { hello \ from world}`
`${TM_DIRECTORY/(.+)/${1:+import { hello \\\} from world}/}` results in `import { hello \ from world`
`${TM_DIRECTORY/(.+)/${1:+import { hello \\\\} from world}/}` results in `import { hello \\ from world}`

This feels like a bug to me, but I'd appreciate any guidance!

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_569483|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Good find - the `}` after `hello` isn't checked for being escaped by the `\`
