### ISSUE TITLE
Oddity with moving lines with alt

### ISSUE THREAD

**Issue by Inaruslynx** [microsoft/vscode#78880]
Issue Type: <b>Bug</b>

This is in Python. When I grab lines of code with no tab in front and then drag from one end of code to the other end I noticed a bug. As the line passes tabbed sections, the selected section of code gets indented. But as it passes out of of the indented section it does not remove indents. So at the bottom, the code will be indented to whatever max indent was in the code above. Also, it indents everything else as it passes.

I didn't see any recommended bugs similar to this so maybe it was just added in the last build. Which makes sense because this has never been an issue before. It's possible something just added interferes with one of my extensions. But none of my extensions should be affecting formatting.

Here's an example:

Before:

```python
import json
import os

rootpath = os.path.dirname(os.path.abspath(__file__))
location = rootpath + "\\Blocked.json"
data = {} # The line I am going to move
data['ip-address'] = []
data['ip-address'].append({
    "address": "0.0.0.0",
    "date": "forever"
})

data = json.dumps(data).encode('utf-8')

with open(location, 'wb') as outfile:
    outfile.write(data)
```

After:

```python
import json
import os

rootpath = os.path.dirname(os.path.abspath(__file__))
location = rootpath + "\\Blocked.json"
data['ip-address'] = []
data['ip-address'].append({
    "address": "0.0.0.0",
    "date": "forever"
    })
    
    data = json.dumps(data).encode('utf-8')
    
    with open(location, 'wb') as outfile:
        outfile.write(data)
        data = {} # Here it is at the bottom
```
Another example:
```python
import json
import os

rootpath = os.path.dirname(os.path.abspath(__file__))
location = rootpath + "\\Blocked.json"
data['ip-address'] = []
data['ip-address'].append({
    "address": "0.0.0.0",
    "date": "forever"
    })
    
    data = json.dumps(data).encode('utf-8')
    
    data = {} # should have not been indented here
with open(location, 'wb') as outfile:
    outfile.write(data)
```

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.4.4
project-manager|ale|10.6.0
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
c-cpp-compile-run|dan|0.5.0
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
gitlens|eam|9.9.3
vscode-great-icons|emm|2.1.47
retroassembler|Eng|1.1.0
vsc-material-theme|Equ|29.2.0
code-runner|for|0.9.12
CppSnippets|har|0.0.14
path-autocomplete|ion|1.13.3
vscode-edit-csv|jan|0.1.2
better-cpp-syntax|jef|1.13.1
vscode-peacock|joh|3.0.1
chat|kar|0.17.1
rainbow-csv|mec|1.2.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.8.29288
cpptools|ms-|0.24.1
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.657
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.3
veriloghdl|msh|1.0.3
awesome-flutter-snippets|Nas|2.0.2
material-icon-theme|PKi|3.8.1
tsimporter|pmn|2.0.1
polacode|pnp|0.3.2
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.4.1
vscode-spotify|shy|3.1.0
vscode-smoothtype|spi|1.2.0
code-spell-checker|str|1.7.17
pdf|tom|0.5.0
vscodeintellicode|Vis|1.1.9
vscode-arduino|vsc|0.2.27
vscode-icons|vsc|9.2.0
debug|web|0.23.1

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Similar to #78788 but that one doesn't mention indenting everything that isd passed over. 

@Inaruslynx please test with your extensions disabled to see if any of yours are causing this.

**Comment by Inaruslynx** [comment]
This appears to be related to an extension. Of which I could not say. I guess I'll just live with it. Hopefully whichever extension it is will figure it out and fix it.
