### ISSUE TITLE
List of Virtual environment path in top panel overlapping with one-another.

### ISSUE THREAD

**Issue by babul7154** [microsoft/vscode#78887]
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
In top panel ,list of virtual environment path is not properly read.Please resolve this issue.
![IMG_20190811_102905](https://user-images.githubusercontent.com/46845524/62830003-c8c8f080-bc23-11e9-8bfe-8f954c8255eb.jpg)

**Comment by roblourens** [comment]
Sorry I don't understand what this list is, please tell me how you got it to show up.

**Comment by babul7154** [comment]
hello sir,
Just click at the bottom panel of vs code and you will know the issue.For better understanding please see the attachments.you can't properly read the virtual environment location.
![Capture2](https://user-images.githubusercontent.com/46845524/62859498-e75de300-bd1a-11e9-8302-9d8399f15ffe.PNG)
![Capture3](https://user-images.githubusercontent.com/46845524/62859511-f3e23b80-bd1a-11e9-9a7e-df0f2a411390.PNG)

**Comment by roblourens** [comment]
I can't reproduce it but your paths are longer, do you recognize it @bpasero?

![image](https://user-images.githubusercontent.com/323878/62898455-5da61980-bd0a-11e9-88eb-5a848aca10e2.png)

**Comment by babul7154** [comment]
I am using Pipenv for virtual environment and its path for my pipenv is at C:\Users\My World\.virtualenvs.

**Comment by bpasero** [comment]
Sounds like a quickpick or list issue to me.

**Comment by babul7154** [comment]
I have found same issue when try to configure python Framework.Please see the attachments.
![1](https://user-images.githubusercontent.com/46845524/62938061-de891200-bdeb-11e9-8ae1-b5a0f23561dc.jpg)
![2](https://user-images.githubusercontent.com/46845524/62938062-de891200-bdeb-11e9-9ef7-f1149f9fd95b.jpg)
![3](https://user-images.githubusercontent.com/46845524/62938064-df21a880-bdeb-11e9-95f1-3ca7ec856d38.PNG)

**Comment by babul7154** [comment]
I think this problem is caused by 'shades of purple theme(I was using this). I switch back to default color theme and the issue has gone.
![13](https://user-images.githubusercontent.com/46845524/63118538-afc19600-bfbb-11e9-9d25-905de68397a7.PNG)
you can clearly see no list issue.

**Comment by chrmarti** [comment]
Fixed as #84062
