### ISSUE TITLE
点击x按钮关闭标签页后的标签宽度变化增加缓冲时间

### ISSUE THREAD

**Issue by sakurawarskula** [microsoft/vscode#78895]
当我想快速关闭多个标签时（并不是关闭其他！因为有个别想保留！），我会用鼠标连续点击标签上的X关闭按钮，但是每关闭一个标签页时长度就会改变，导致每次都要重新移动鼠标到新标签的X按钮位置，能否像monoDev一样关闭标签时有一个缓冲时间改变剩余标签的长度？

**Comment by rxliuli** [comment]
The type of tab closure strategy for browsers, but I don't know how difficult it is to implement. . .

The specific effect is

1. When the browser is not the last tab, the length will not be recalculated
2. Until the last tab is closed, or the mouse is moved outside the tab bar

or chinese

浏览器那种类型的标签页关闭策略啊，不过不知道实现难度大不大。。。

具体效果是

1. 关闭浏览器不是最后一个标签页时，长度不会重新计算
2. 直到关闭最后一个标签页，或者鼠标移动到标签栏之外

**Comment by galikeoy** [comment]
> The type of tab closure strategy for browsers, but I don't know how difficult it is to implement. . .
> 
> The specific effect is
> 
> 1. When the browser is not the last tab, the length will not be recalculated
> 2. Until the last tab is closed, or the mouse is moved outside the tab bar
> 
> or chinese
> 
> 浏览器那种类型的标签页关闭策略啊，不过不知道实现难度大不大。。。
> 
> 具体效果是
> 
> 1. 关闭浏览器不是最后一个标签页时，长度不会重新计算
> 2. 直到关闭最后一个标签页，或者鼠标移动到标签栏之外
> 
> ![2019-08-11-20](https://user-images.githubusercontent.com/24560368/62834051-b9749200-bc79-11e9-9c50-b2c0f0669332.gif)

这个效果不错。。
