### ISSUE TITLE
Inconsistent selection

### ISSUE THREAD

**Issue by cloewen8** [microsoft/vscode#78891]
Issue Type: <b>Bug</b>

It is not consistent, so I can not reliably reproduce this problem.

After updating today, I started noticing strange selection behavior. When doubling clicking to select a word, it occasionally selects the entire file, nothing at all, the entire line, or it selects the word as intended.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18912

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4350 Quad-Core Processor             (4 x 4551)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.29GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Colton/Documents/GitHub/Invading-Martians|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.39.2
vsliveshare|ms-|1.0.657
shader|sle|1.1.4
lua|sum|0.11.5

</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

Are you able to reproduce the issue after disabling all your extensions?

**Comment by cloewen8** [comment]
In Lua.

Disabling all extensions seemed to help, but did not stop the problem.

**Comment by cloewen8** [comment]
I recently noticed that this behavior also occurs in Visual Studio 2019.

**Comment by cloewen8** [comment]
This issue seems to be getting worse, even showing up in Windows Explorer, so I'm guessing this may be a hardware related issue with my mouse. I'll reopen this issue if I can link it back to VSCode.
