### ISSUE TITLE
Get all problems (errors, warnings, etc.) using VSCode extensions API - 2

### ISSUE THREAD

**Issue by anurbol** [microsoft/vscode#78899]
I am sorry, I am basically duplicating this issue: https://github.com/Microsoft/vscode/issues/30075 because I didn't understand, what is the outcome of that issue? 

How can I get all problems in the workspace? I couldn't find anything related in the proposed api: https://raw.githubusercontent.com/microsoft/vscode/master/src/vs/vscode.proposed.d.ts (is the link correct?).

**Comment by usernamehw** [comment]
```ts
const diagnostics = vscode.languages.getDiagnostics();
```

**Comment by anurbol** [comment]
A big Thank You, @usernamehw! Now I can see that in the API :smiley: :man_facepalming:
