### ISSUE TITLE
Double click on empty header area should open a new tab

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7889]
We need some action to easily open a new tab via mouse. Chrome has that small square and sublime has double click on empty area to open a new tab.

Since I might not like rendering the extra square, I vote for double click on empty header area opens a new tab - same as sublime.

**Comment by isidorn** [comment]
Same as cmd + N - new untitled-1

**Comment by bpasero** [comment]
UX meeting topic I guess.
