### ISSUE TITLE
[json] JSON Schema wrong path encoding

### ISSUE THREAD

**Issue by jseanxu** [Microsoft/vscode#789]
In a JSON file, when specifying the schema file, the path of the schema file shows something like this
![image](https://cloud.githubusercontent.com/assets/6741017/11456509/8b779c7a-9640-11e5-9cd6-6922014944b7.png)

See the colon after the drive letter is not correctly encoded.

**Comment by alexandrudima** [comment]
@aeschli Perhaps use URI.fsPath in error messages

**Comment by aeschli** [comment]
fix delivered

**Comment by dbaeumer** [comment]
@aeschli can you please provide steps to verify.

**Comment by aeschli** [comment]
There are two ways to associate a schema.
1. Add a `$schema` property top level in your json file
2. configure the `json.schema` setting

At both places you can add a relative path (`./foo`), representing a workspace path.
Verify that when you give a path to a non-existant resource, the error marker makes sense.

**Comment by dbaeumer** [comment]
@aeschli thanks.
