### ISSUE TITLE
"files.defaultLanguage" should use current language 

### ISSUE THREAD

**Issue by etiennejcharles** [microsoft/vscode#78903]
VSCode Version: 1.37.0

- OS Version: Sierra 10.13.6
- Wanted behavior:

**Scenario**: 
**Given** I set `"files.defaultLanguage": "current"` (doesn't exist)
**Given** I let's say work in a `javascript` file. 
**When** I create new file via `Ctrl+N`
**Then** I Expect to have a new file new file as `javascript`, not plain text. 

**Scenario**: 
**Given** I set `"files.defaultLanguage": "current"` (doesn't exist)
**Given** I let's say work in a `plain-text` file. 
**When** I create new file via `Ctrl+N`
**Then** I expect to have a new file new file as `plain-text`

Reproduces without extensions: **Yes**

Wondering if I was the only one wanting something like that ?

**Comment by gjsjohnmurray** [comment]
See also #27796

**Comment by sanjeev444456** [comment]
I would love to work on this

**Comment by IgorPodlawski** [comment]
@sanjeev444456 are you still working on it? Because I have an idea how it could be made and I would like to handle it in couple next days (maybe even tommorow).

**Comment by sanjeev444456** [comment]
@IgorPodlawski no, i am not working on it, you can work on it

**Comment by jzyrobert** [comment]
Is there a way to get the language mode of the current active fileEditorInput?
It seems there is `preferredMode` but not the current set mode like `untitledTextEditorInput` has

**Comment by bpasero** [comment]
There is now `"files.defaultLanguage": "active-editor"` which can be used to inherit the language mode of the currently active editor. In case a diff editor is opened, the right-hand-side mode will be taken.

**Comment by etiennejcharles** [comment]
Totally awesome! thanks @bpasero for the hard work on VScode buddy ;)
