### ISSUE TITLE
Does not automatically complete in if()

### ISSUE THREAD

**Issue by creanme** [microsoft/vscode#78904]
tested on vscode insiders, it also has this bug.

- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.  Define a variable
2.  Write just the variable in if brackets, No completion

![2333](https://user-images.githubusercontent.com/11664505/62835198-e5970f80-bc87-11e9-8ef2-241b5d9dd09c.gif)

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by jrieken** [comment]
It's this setting `editor.suggest.snippetsPreventQuickSuggestions`
