### ISSUE TITLE
Tab context menu actions to open a new tab

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7890]
1. Context menu on a tab header
2. Only actions to close, I would expect some actions to open a new tab (new, open) - similar to sublime and chrome

**Comment by bpasero** [comment]
I am not convinced this adds a lot of value...

**Comment by isidorn** [comment]
I think we need some mouse gesture to quickly open a new tab. If you do not like this then I would push more for #7889

I also think the context menu might benefit from this - currently it is just a bunch of close actions. A new and a seperator might actually improve the visuals while making it consistent with what other editors are doing.

**Comment by bpasero** [comment]
@isidorn not true, if you open the context menu on a diff editor, there is a lot more entries. We put all editor actions into the context menu as well.

**Comment by isidorn** [comment]
@bpasero yeah I know, but for the most common case it is just a bunch of close actions as far as I see it

**Comment by bpasero** [comment]
UX meeting topic I guess.

**Comment by bpasero** [comment]
We decided to start with double click besides a tab to open a new untitled first.
