### ISSUE TITLE
Font with color tables (COLR/CPAL) disables syntax highlighting

### ISSUE THREAD

**Issue by jenskutilek** [microsoft/vscode#78901]
- VSCode Version: 1.37.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Install [Release 0.39 of the Sudo font](https://github.com/jenskutilek/sudo-font/tree/v0.39)
2. Set VSCode to use the Sudo font
3. Syntax highlighting will not be applied to any file.

See https://github.com/jenskutilek/sudo-font/issues/11. I have tracked it down to the fact that the font contains some color glyphs in a COLR/CPAL font table.

The color glyphs are just some rarely used characters (U+2591, U+2592, U+2593), and normal text should not be affected by this.

I would expect that color should be applied normally to any glyphs that do not have a special colorized version of the glyph contained in the color tables.

**Comment by alexandrudima** [comment]
@jenskutilek VS Code is built on Electron, which is built on Chromium. The font in the editor is rendered using Chromium's font rendering. So I wonder if what you are seeing reproduces in Chromium. You could try to change the following fiddle to use your font:

https://jsfiddle.net/3e5nu4r8/

If that reproduces in Chrome/Chromium, then please reach out directly to the Chromium folks at https://bugs.chromium.org/p/chromium/issues/list , as they will know about how font rendering works.

**Comment by jenskutilek** [comment]
It is indeed the same in Chromium, and there is an open issue already: https://bugs.chromium.org/p/chromium/issues/detail?id=944093
