### ISSUE TITLE
file explorer doesn't show anything in large git repo's

### ISSUE THREAD

**Issue by MuhsinFatih** [microsoft/vscode#78910]
- VSCode Version: 1.37 (July update)
- OS Version: MacOS Mojave 10.14.6 (18G87)

Steps to Reproduce:

1. open a large git repo in vscode

Result: Explorer will not display anything, but files are accessible (i.e.: I can open files with quickopen, edit them as usual)

Does this issue occur when all extensions are disabled?: Yes

I also installed the insiders version today (Version: 1.37.0-insider), seems to be the same version, and issue still occurs there.
I rolled back to 1.36.1, and it works as expected in this version

**Comment by bpasero** [comment]
@MuhsinFatih is that on a remote network drive? Are you having dangling symbolic links within? Does it reproduce with our Exploration builds that use a newer node.js version?

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by MuhsinFatih** [comment]
Yes, sorry for not mentioning those. It's actually exactly like that: a remote folder with dangling symlinks. I'm using sshfs, so although they are in fact not dangling symlinks, since I don't have access to their realpath's locally, to vscode they are dangling.
I don't know about exploration builds, I'll check that when I get the chance
