### ISSUE TITLE
Can I make Ctrl-left arrow and Ctrl-right arrow symmetric?

### ISSUE THREAD

**Issue by dannypike** [microsoft/vscode#78912]
Issue Type: <b>Bug</b>

If I type ctrl-right arrow followed immediately by ctrl-left-arrow, the caret does not end up in the same place. This is unexpected for me, as it differs from every other text editor that I use.

Is there a way that I can make VSCode behave "symmetrically" in the way that it skips forwards and backwards across word boundaries?

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.21GB free)|
|Process Argv|--folder-uri file:///d%3A/work/gml/serenity/0.2/src|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.8
vscode-mocha-test-adapter|hbe|2.1.2
vscode-test-explorer|hbe|2.14.1
vs-color-picker|lih|1.0.0
cpptools|ms-|0.24.1
debugger-for-chrome|msj|4.11.7
psi-header|psi|1.7.4
markdown-preview-enhanced|shd|0.4.3

</details>

**Comment by rebornix** [comment]
Can you name a few editors which don't work the same way as VS Code? If the cursor is in the middle of a word, `ctrl+left` then `ctrl+right` will not go back to previous position, which is the right behavior. You can see the same behavior in a normal `textarea`, Visual Studio, Notepad, etc.

**Comment by dannypike** [comment]
Many thanks for your reply. Perhaps, I've not explained the problem very well, so here's a single step-by-step example that I hope will help you see what I mean:

1. On a blank line, enter:
```func(arg)```
2. Put the caret before the word ```func``` and hit ```ctrl-right``` twice. Then hit ```ctrl-left``` twice.

In VSCode, the caret finishes at the '(' whereas, in every other editor that I use (Visual Studio, Textpad, Notepad, Office), it finishes back where it started, i.e. at the 'f'. So, VSCode does not treat ```ctrl-left``` as a true "inverse operator" for ```ctrl-right```, whereas all the other editors that I use regularly do.

The same applies to the converse operation:

3. Put the caret before the ')' and hit ```ctrl-left``` twice, then ```ctrl-right``` twice.

In VSCode, unlike other editors, you end up after the ')' instead of before it.

I find this inconsistency to be rather distracting, as I have to check repeatedly where VSCode is choosing to move the caret as I move through a document.

I hope that helps. :)

Dan

**Comment by Spongman** [comment]
> Can you name a few editors which don't work the same way as VS Code? 

Visual Studio.

Seriously, there needs to be an option for fixing this.

**Comment by Spongman** [comment]
ok, it looks like there _is_ an option for this:

```
    {
        "key": "ctrl+shift+right",
        "command": "-cursorWordEndRightSelect",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+right",
        "command": "-cursorWordEndRight",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+right",
        "command": "-cursorWordAccessibilityRight",
        "when": "accessibilityModeEnabled && textInputFocus"
    },
    {
        "key": "ctrl+shift+right",
        "command": "-cursorWordAccessibilityRightSelect",
        "when": "accessibilityModeEnabled && textInputFocus"
    },
    {
        "key": "ctrl+right",
        "command": "cursorWordStartRight"
    },
    {
        "key": "ctrl+shift+right",
        "command": "cursorWordStartRightSelect"
    }
```
