### ISSUE TITLE
I hope to increase the maximum editor function.

### ISSUE THREAD

**Issue by rxliuli** [microsoft/vscode#78919]
The largest editor now only hides the sidebar, but the terminal at the bottom is not hidden, which actually requires 3 shortcuts to maximize the entire editor. So, can you enhance this feature:

- Hide Terminal while maximizing editor
- Maximize the editor state and press the shortcut again to restore all previous sidebars

> Attachment: I found that some of the opposite functions in VSCode are divided into two shortcut keys. Is this intentional? For example: **jump/view to function definition <=> jump/view function definition**

Effect chart reference

![2019-08-12-09](https://user-images.githubusercontent.com/24560368/62842183-dee9b600-bce2-11e9-96a8-34bba173521f.gif)

**Comment by isidorn** [comment]
What command are you triggering in vscode?
Can you attach a gif showing the issue in vscode? You are using webstorm there (whic is another product by another company)?

**Comment by rxliuli** [comment]
> What command are you triggering in vscode?
> Can you attach a gif showing the issue in vscode? You are using webstorm there (whic is another product by another company)?

The command that is triggered is: `workbench.action.maximizeEditor`, but the Terminal is not hidden. The reason for using the WebStorm Gif diagram is that the final effect of the command should be like that.

Rendering in VSCode

![2019-08-12-16](https://user-images.githubusercontent.com/24560368/62853396-cb5c4080-bd1e-11e9-80a0-808bba853411.gif)

**Comment by isidorn** [comment]
This sounds like a feature request for the maximize editor command.
And it makes some sense to me.
Forwarding to @bpasero since he introduced this command
