### ISSUE TITLE
Issues Installing on Mac

### ISSUE THREAD

**Issue by mattferg78** [microsoft/vscode#78918]
- VSCode Version: 1.37
- OS Version: macOS Catalina 10.15 Beta

When trying to install VSCode I am getting a message advising that 'Visual Studio Code can't be opened because Apple cannot check it for malicious software.

Steps to Reproduce:

1. Download latest version of VSCode
2. Double click on VS Code App to load

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
> 'Visual Studio Code can't be opened because Apple cannot check it for malicious software.

Can you show me a screenshot?

**Comment by mattferg78** [comment]
<img width="416" alt="Screen Shot 2019-08-12 at 9 12 32 pm" src="https://user-images.githubusercontent.com/53998444/62867515-02921800-bd46-11e9-811c-127f2316610c.png">

This is the link where I downloaded it from:
https://code.visualstudio.com/updates/v1_37

**Comment by joaomoreno** [comment]
Ah this is Catalina. #74782

**Comment by mattferg78** [comment]
Yes it is.
