### ISSUE TITLE
Shortcuts for switching to the nth view in activity bar or panel

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#78911]
Today we can use Alt+1 to switch to the first file in the current editor and Alt+2 to switch to the second one. Is it possible to add shortcuts/commands to enable similar behavior for switching views in activity bar or panel?

E.g. press Ctrl+Shift+1 to switch to the first view in activity bar (file explore if you never reordered). Press Alt+Shift+1 to switch to the first view in panel (problem panel).

**Comment by ArturoDent** [comment]
Do you mean like

```
`{
  "key": "ctrl+alt+1",
  "command": "workbench.explorer.fileView.focus"
},
{
  "key": "ctrl+alt+2",
  "command": "scm.mainPanel.focus"
},`
```
etc.

**Comment by isidorn** [comment]
Yes you could do as @ArturoDent suggest
You can also use the two following commands

![Screenshot 2019-08-12 at 14 49 39](https://user-images.githubusercontent.com/1926584/62866157-70235180-bd10-11e9-8622-b4419c81c492.png)

**Comment by sunliangqin** [comment]
Thanks for the suggestion! This is exactly how I workaround this issue.

The problem here is I have to update the key bindings whenever I reorder views or install/uninstall extensions with a custom view in explorer. It would be great if we can have a a series of workbench.action.focusSideBarViewAtIndexN/workbench.action.focusPanelViewAtIndexN commands to serve this purpose. @ArturoDent @isidorn what do you think?

**Comment by isidorn** [comment]
That feels a bit out of scope imho.
With the current funcitonality you can focus the next / previous and the exact one. However you can not do "focus 5th". I think we can live with this limitation.
