### ISSUE TITLE
Webview not handing CustomEvent

### ISSUE THREAD

**Issue by brunoNetId** [microsoft/vscode#78915]
- VSCode Version: 1.37.0
- OS Version: macOS 10.14.5

Quick summary:
I'm trying to work on an extension to design diagrams to generate code. The libraries I'm using are triggering CustomEvent events on mouse events, but VSCode seems to be willing to treat them as MouseEvent, and hence breaking the execution.

Steps to Reproduce:

1. Find included a project to reproduce the problem:
   (based on the vs-extension sample 'cat-coding')
   [reproducible.tar.gz] . 
   (https://github.com/microsoft/vscode/files/3490468/reproducible.tar.gz)
2. Open the project in VSCode
3. Start debugging
4. Launch the command "Cat Coding: start cat coding session"
    <img width="255" alt="command" src="https://user-images.githubusercontent.com/14263485/62839880-378c6500-bc89-11e9-8bef-1ed3d045587a.png">
5. Click on the button displayed in the Webview:
     <img width="337" alt="click-button" src="https://user-images.githubusercontent.com/14263485/62839898-7d492d80-bc89-11e9-9334-1ce986ce6592.png">
6. The following error should be thrown and displayed in the console:
     <img width="1076" alt="console-error" src="https://user-images.githubusercontent.com/14263485/62839900-8934ef80-bc89-11e9-92fd-e6402dfb7646.png">

Thanks in advance.

**Comment by mjbvz** [comment]
Prs welcome. Here's the relevant code: https://github.com/microsoft/vscode/blob/02702327c1fea8b6c6425b84adb004c41cb84769/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L377

**Comment by mjbvz** [comment]
Fixed by #79523
