### ISSUE TITLE
terminal sessions persist after quitting vs code

### ISSUE THREAD

**Issue by meowlz** [microsoft/vscode#78913]
Issue Type: <b>Bug</b>

Apparently this issue still persists :( I am on a mac with newest updates.
https://github.com/Microsoft/vscode/issues/45535
I have to reboot my computer or find the processes and quit them to restart my server after quitting VS code once.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
I haven't seen any other reports of this and haven't been able to reproduce. The way you're launching the server be detaching the process meaning killing the terminal wouldn't kill it?
