### ISSUE TITLE
Allow Go to symbol in the highlighted Go to file after (#) is detected

### ISSUE THREAD

**Issue by Cmacu** [microsoft/vscode#78920]
This is based on one of the features of GoTo Anything in Sublime Text. Here is a sample video demonstrating how it works:
https://youtu.be/48f3N0hCaBU?t=109

From the available VSCode features Go to Symbol in Workspace feels so close to it and still doesn't cover some very useful scenarios. For example:

- When there are many classes that have the same symbol/function name, pre-filtering the file helps to jump to the exact definition instead of navigating within the list

- When the file name is known, but the exact symbol/function name is unclear. Fuzzy searching it should be fast and easy

- It's also useful for quick preview of the available symbols/functions in a given file

These are just a few that come to mind quickly and I am sure that there are other use cases.

**Comment by jrieken** [comment]
fyi @chrmarti - this would need support from the quick pick infrastructure - that's yet to be rewritten

**Comment by Cmacu** [comment]
An extension utilizing the existing api to enable this feature:
https://marketplace.visualstudio.com/items?itemName=Cmacu.gotoanything
