### ISSUE TITLE
VS Code : Sign In Request

### ISSUE THREAD

**Issue by nativekar** [microsoft/vscode#78923]
Hi, 

Can you allow for there to be an option to sign in to VS Code? This helps with accessing the app across multiple devices and quite simply - to not have to download all extensions, set/reset preferences every time VS Code is accessed from a different device? 

Perhaps linking VS Code to the MS Account that was used to sign into the device might be a start?

Edit: I've found out that there is a way to sync my settings using an extension, but I'd greatly prefer just signing into VS Code to using an extension that uploads my settings to GitHub.

**Comment by donnisnoni95** [comment]
Have a look at this extensions. I think it does exactly what you're searching for: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
Would be nice to have something like this built-in though.

**Comment by gjsjohnmurray** [comment]
I suggest you track #78869

**Comment by donnisnoni95** [comment]
@gjsjohnmurray Thats better

**Comment by nativekar** [comment]
@donnisnoni95  - thank you for the suggestion, mate, but I was looking for something built into VS rather than having to rely on an extension.

**Comment by nativekar** [comment]
@gjsjohnmurray  - thank you for your suggestion. Much appreciated.

**Comment by isidorn** [comment]
Closing as duplicate of #78869
Since this should be covered by that. Thanks
fyi @misolori @sandy081
