### ISSUE TITLE
proxy settings

### ISSUE THREAD

**Issue by chrisrapson** [microsoft/vscode#78924]
- VSCode Version: 1.36.1
- OS Version: Ubuntu 18.04.2

Steps to Reproduce:

1. Start VS Code from the launcher, or from the terminal as `code`.
2. Try any combination of settings for `http.proxy` and `http.proxyStrictSSL`
3. Test https connections with `curl -I https://www.github.com` (or by trying to install any pip package, or by trying to install an extension)

https connections only succeed if I launch  the program from the terminal with `code --proxy-server=http://company-proxy.com:1234/`

Does this issue occur when all extensions are disabled?: Yes/No
No. Extensions installed are:

- Anaconda Extension Pack 1.0.1
- Python 2019.8.29288
- YAML 0.4.1

Edit: I should add that I have read through [#22214](https://github.com/microsoft/vscode/issues/22214), [#5596](https://github.com/microsoft/vscode/issues/5596), [#69](https://github.com/microsoft/vscode/issues/69). They may be duplicates, but the suggestions there haven't worked for me.

**Comment by chrmarti** [comment]
Which connections are you looking at? Do you have your proxy configured in the OS? (Using Network Manager on Ubuntu I think.)

**Comment by chrisrapson** [comment]
It seems to be only https connections (port 443) which are a problem. Within the terminal on vscode, I can run the following (I terminate the second command by ctrl-C after it stalls):

```
$ curl -I http://www.github.com
HTTP/1.1 301 Moved Permanently
Date: Tue, 13 Aug 2019 21:18:56 GMT
Content-Length: 0
Location: https://www.github.com/
X-Cache: MISS from aotea
Via: 1.1 aotea (squid/3.5.27)
Connection: keep-alive

$ curl -I https://www.github.com
^C
```

Yes, I have my proxy installed in the OS. My browser is configured to "Use system proxy settings".

**Comment by chrmarti** [comment]
Does it work with Chromium?

**Comment by chrisrapson** [comment]
Yes, https in chromium works fine. In the preferences menu, the proxy settings button takes me straight to the system settings.

**Comment by chrmarti** [comment]
@deepak1556 Do you have an idea why Electron would not pick up the proxy setting from the OS the same way Chromium does?

**Comment by chrmarti** [comment]
@chrisrapson Which parts of the VS Code UI do not work due to this? The extensions viewlet? The Git integration? Some extension?

**Comment by deepak1556** [comment]
@chrmarti Electron by default will respect system proxy settings unless its forced to respect other proxy settings using `--proxy-server`, `--proxy-pac-url` or using apis like `session.setProxy`.

@chrisrapson can you please attach the logs generated under the following testing conditions, to narrow down the issue.

**Test I: No proxy configurations are set via VSCode, making sure system settings are respected**

* Configure proxy on your system.
* Launch code from terminal with `code <folder> --log-net-log=test_log_1.json`
* Make sure no proxy settings are present in VSCode settings
* Perform the operations that you expect to work normally and close the editor.
* Find the file `test_log_1.json` and attach it here.

**Test II: Proxy configurations are set via VSCode**

* Remove proxy configuration from your system.
* Launch code from terminal with `code <folder> --log-net-log=test_log_2.json`
* Set `http.proxy` via VSCode settings
* Perform the operations that you expect to work normally
* Remove proxy settings and close the editor.
* Find the file `test_log_2.json` and attach it here.

**Test III: Proxy configurations are set via chromium switches**

*--proxy-server*

* Remove proxy configuration from your system.
* Launch code from terminal with `code <folder> --log-net-log=test_log_3.json --proxy-server=<proxy_url>`
* Make sure no proxy settings are present in VSCode settings
* Perform the operations that you expect to work normally and close the editor.
* Find the file `test_log_3.json` and attach it here.

*--proxy-auto-detect*

* Configure proxy into your system.
* Launch code from terminal with `code <folder> --log-net-log=test_log_4.json --proxy-auto-detect`
* Make sure no proxy settings are present in VSCode settings
* Perform the operations that you expect to work normally and close the editor.
* Find the file `test_log_4.json` and attach it here.


Also it would be helpful if you can answer @chrmarti [comment](https://github.com/microsoft/vscode/issues/78924#issuecomment-521583261) with clearer repro steps as to which parts of editor don't work, even a video demo would be good. Thanks!

**Comment by chrisrapson** [comment]
@chrmarti The extensions viewlet seems to work fine. If I start typing in the search box, it updates the list of extensions.

I did notice one strange thing, probably unrelated, but you never know. I'm getting popup notifications including this one:
![Screenshot from 2019-08-16 11-26-41](https://user-images.githubusercontent.com/4982550/63133319-c9dd9180-c018-11e9-81fa-89bcb31389bb.png)
When I search for pylint in the extensions viewlet, it says "No extensions found." Intellisense and linting actually seems to be working with just the standard Microsoft python extension. (`go to definition` doesn't work, but I think that's a separate issue.) When I do click on the button to install pylint from the notification, it stalls out because of the network connection.

Git seems to work fine. It detects my local changes, and can pull and push.

The anaconda and python extensions seem to work fine. As I said, I'm having no problems with code highlighting or running python. (I don't actually know where the YAML extension came from. I don't recall installing it, and I've never knowingly worked with YAML.)

I'll run Deepak's tests now and reply in a separate message

**Comment by chrisrapson** [comment]
@deepak1556 I ran those tests, but I don't think they'll be very enlightening. I was able to create https connections on every single one of those configurations! I can upload the log files if you want, but I don't think they'll be helpful.

It turns out that the problem _only_ occurs when I start code

- from the gnome launcher
- by clicking the .desktop file
- running it from the Alt-F2 menu

I checked the Exec command in `/usr/share/applications/code.desktop`, and even if I run `/usr/share/code/code --unity-launch` from the terminal, https still works. I compared the output from `ps -ef | grep code`, and they are identical when running from the terminal and from the launcher (except for pids and some tokens). What else could change between launching by mouseclick and launching from the terminal?

**Comment by chrmarti** [comment]
Do you have the `http_proxy` environment variable set when you're in the terminal? If so, where do you set it? Are you using bash or zsh or some other shell?

**Comment by chrisrapson** [comment]
@chrmarti yes, the `http_proxy` environment variable is set in my bash terminal. I set it through the graphical gnome settings menu. I was unable to find where that setting takes effect. It is not in any of:

- `~/.bashrc`
- `~/.profile`
- `~/.bash_profile`
- `/etc/profile` (or `/etc/profile.d/*`)
- `/etc/bash.bashrc`
- `/etc/environment`
- `/etc/apt/apt.conf`

**Comment by chrmarti** [comment]
We extract the environment variables from a temporary login shell, so you could add that variable to `~/.bash_profile`. Does that make it work?

**Comment by chrisrapson** [comment]
@chrmarti yes, now launching code from the gnome launcher has the correct http_proxy environment variables. I didn't have a `.bash_profile` before, so now it is just two lines, setting the http_proxy and https_provy environment variables.

Setting `"terminal.integrated.shellArgs.osx": [ "-l" ]` in my settings didn't work.

This seems more like a workaround than an ideal solution. I'm torn on whether it's an ubuntu issue, for hiding the proxy settings somewhere obscure, or a vscode issue, since other programs seem to manage. It seems like a similar issue to [#20265](https://github.com/Microsoft/vscode/issues/20265), [#22831](https://github.com/microsoft/vscode/issues/22831) and several other issues that those two link to.

By the way, apparently the canonical way to get proxy settings in gnome is:
```
gsettings get org.gnome.system.proxy.http host
gsettings get org.gnome.system.proxy.http port
```
and similar for https. You can request authentication info in place of host/port too.

**Comment by chrmarti** [comment]
@chrisrapson Out of curiosity: Which connection did not work and started working after adding the `.bash_profile`? (Did I miss that?)

We should pick up the same proxy as the extension viewlet is using for all other connections. If you want to track this down further, you can comment out the variables in the `.bash_profile` and set the log level to `trace` (`F1` > `Set Log Level...`) and then reload the window (`F1` > `Reload Window`). The `Extension Host` channel in the `Output` panel then shows you which proxy is being used and why, search for lines containing `ProxyResolver` (`Ctrl+F` works) and post these here.

**Comment by chrisrapson** [comment]
@chrmarti All https connections didn't work previously (curl, pip, installing extensions...). Now they do.

I tried to follow those instructions to look into it more closely, but I'm not seeing anything at all when I choose "Extensions" in the drop-down menu of the Output panel. (I see a long list of commands when I choose "Git" instead, so I assume that the Output panel is working properly.)

**Comment by chrmarti** [comment]
Oh, so it's really only about the environment variable and CLI tools. That makes sense and setting the environment variable is indeed the only way to fix this for most CLIs (short of configuring the CLIs individually). Thanks for the feedback.

We could think about setting the environment variables ourselves based on what we get from Electron. The problem here is that the Electron API can return different proxies for each URL, so this would only work well in simple setups where everything must go through the same proxy and there is no way for us to tell if we are in that simple case. So for now, setting the environment variable yourself is the way to go. I'll close this issue with that.

What we learned: Some terminals add environment variables in addition to those in the shell startup scripts.
