### ISSUE TITLE
File Open dialog is too tall on a 768 pixel height screen

### ISSUE THREAD

**Issue by ajrh1** [microsoft/vscode#78925]
Lenovo X220 laptop has 768 pixel high screen, and the File Open dialog window appears taller than that, so the top and bottom of the dialog are not visible.

Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-5-amd64

**Comment by isidorn** [comment]
Please file this against the electron repository here https://github.com/electron/electron
Thanks
