### ISSUE TITLE
installing extensions

### ISSUE THREAD

**Issue by Geekboy14** [microsoft/vscode#78928]
Issue Type: <b>Bug</b>

i cant install any extension or load extension page (i dont use proxy) 
my os linux ubuntu and i tried on win 7 & 8 &10 enterprise and more than 6 linux distros and on my second laptop also i have the same problem  even when updating to v1.37

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-22-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz (4 x 1240)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|1.81GB (0.07GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
There have been several similar reports that  came down to DNS. For example #78872

**Comment by sandy081** [comment]
Try to install the extension and please provide us the logs from the following locations

`F1 -> View: Open View -> Log (Shared)`
`F1 -> View: Open View -> Log (Window)`

Also open Developer tools and see if there are any errors in the console

**Comment by sandy081** [comment]
Please try to access this image? 

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by Geekboy14** [comment]
frist of all thanks alot it was the dns problem and i changed it  thanks
alot
