### ISSUE TITLE
VS cut down the file content but it actually has the content more than it shows

### ISSUE THREAD

**Issue by hrhitesh** [microsoft/vscode#78926]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by hrhitesh** [comment]
No, it's not duplicate issues.
![vs](https://user-images.githubusercontent.com/10917307/62845685-be702a80-bce7-11e9-941e-0fb7c3f23c42.png)

**Comment by bpasero** [comment]
@hrhitesh is this about the editor scrolling down even though there is no content below?

**Comment by hrhitesh** [comment]
I have a content of more than 100 lines but it shows only a few of them from the start

**Comment by bpasero** [comment]
@hrhitesh can you attach the file here?

**Comment by hrhitesh** [comment]
Yes, I m attaching two screenshots with it first which has issues to display content in VS and second which has full content.

[index.zip](https://github.com/microsoft/vscode/files/3491607/index.zip)
![space-with-content](https://user-images.githubusercontent.com/10917307/62854614-782dc200-bd0d-11e9-848b-3c2f132d6426.png)
![space-issues](https://user-images.githubusercontent.com/10917307/62854615-78c65880-bd0d-11e9-8450-fe5dfe897066.png)

**Comment by bpasero** [comment]
@hrhitesh what version of VSCode is that you are running with?

And in your example, can you not scroll down to reveal more content?

**Comment by hrhitesh** [comment]
1. VSCode version details:
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic

2. I can scroll down but it does not show me the content after few lines.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by hrhitesh** [comment]
Sure, I will try and let you know if everything is OK as it's randomly basis.

**Comment by bpasero** [comment]
Thanks
