### ISSUE TITLE
$TM_CURRENT_LINE should replace the whole line - not duplicate it

### ISSUE THREAD

**Issue by altimmons** [microsoft/vscode#78927]
I know this is a duplicate.  
But the last dev that saw it said it wasn't really something people wanted and locked it- closing any useful debate. 

I know there is an overwhelming number of issues here, but this feature I really miss from jetbrains, et. al. 

https://github.com/microsoft/vscode/issues/69797

Clearly he's (or she) never discovered the wonders of postfix commands.

The current behavior of $TM_CURRENT_LINE will in every case duplicate part of that line.  Any snippet you write- 

     THIS IS MY LINE

leaves the line completely in place- you can't alter it, but then you can add some other text after it.  Like this-

    THIS IS MY LINE <opt before> THIS IS MY LINE (poss. modified) <opt after>

I can't for the life of me think of a use case for this.  If you trigger it as a prefix- then the line is blank- and thus the variable $TM_CURRENT_LINE is also null!, as a postfix, (or anywhere other than at the beginning- you get this- with the trigger being `.out`

![image](https://user-images.githubusercontent.com/15314341/62845537-c9e73580-bc96-11e9-8afb-afc4ef8656ea.png)

If someone can show me a single use case for $TM_CURRENT_LINE as is- I will cede the point.  But I don't think it can be used.

**Comment by altimmons** [comment]
Here is another example where it makes no sense- using the official documentation.--

Here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets

![image](https://user-images.githubusercontent.com/15314341/62845819-32371680-bc99-11e9-90c8-7f2194d9a500.png)

So, according to the example.  If I type 

     "My  text".out 

We would expect it to be replaced with 

    "My text"

because we have scanned up to the `.` and truncated from there, leaving the "base file name in the example." 

Using this: 
![image](https://user-images.githubusercontent.com/15314341/62845850-7aeecf80-bc99-11e9-95a6-8024131b75e9.png)

(The example from the site) The output remains:

![image](https://user-images.githubusercontent.com/15314341/62845858-93f78080-bc99-11e9-97b0-2a8bba8f9aea.png)


So, while it does successfully truncate the line... it leaves the line duplicated.  Making it entirely useless.

**Comment by altimmons** [comment]
Sorry, Given this input...
![image](https://user-images.githubusercontent.com/15314341/62845883-d3be6800-bc99-11e9-9a93-e023b4ebddf3.png)

**Comment by jrieken** [comment]
Our reference TextMate-snippet-implementation is TextMate itself and unless I am missing something it's working as defined (defined by me observing its behaviour)

![Aug-12-2019 10-43-54](https://user-images.githubusercontent.com/1794099/62853941-29246480-bcee-11e9-8c66-8a5fdab6290b.gif)

**Comment by ArturoDent** [comment]
I don't necessarily disagree that `$TM_CURRENT_LINE` is one of the least useful of the built-in variables but you can do some things with it if you trigger it differently.

```
{
    "key": "alt+=",
    "command": "editor.action.insertSnippet",
    "args": {
      "name": "useCurrentLine"
    }
  },
```
```
"useCurrentLine": {
    "prefix": "nil",
    "body": [
      "\nconsole.log(${TM_CURRENT_LINE/(const|let|var) ([^\\s;]*);*?\\s*?.*/$2/g});"
    ],
    "description": "use TM_CURRENT_LINE"
  },
```

Now if you trigger the snippet at the end of your line of code, it will be able to use all or part of that line of code (dependent on your regex-fu) in subsequent lines of the snippet and not modify that initial line.

So the example above takes:

`const myVar = 12; `

and adds `console.log(myVar); ` on the next line.

A simplistic example but you get the idea.  If you trigger it with the `insertSnippet` command you can capture whatever part of that `TM_CURRENT_LINE` and use it on whichever following lines you wish and do that multiple times in the same snippet.

**Comment by altimmons** [comment]
Thats an intersting idea.
And perhaps this is infact the correct implementation of Textmate's syntax.

But the core of the question remains, Post-fix editing is the number 1 reason I like JetBrains products.

It seems to flow in the order in which I, and many others think,'

If the behaviour is to replace the line: eg

    ${LINE}
    .trigger
     <?-STRING>{${Line}+RegEx}<?-STRING>

in other cases., then it would be super useful here.  IntelliJ has hundreds of postfix commands.  Mostly any time you wrap something in another function.  Its a but like the pipe function in R.  
 
      Method1(x) %>% Method2 %>% Method3 %>% Method4 -> store

rather than

      Method4(Method3(Method2(Method1(x))))

The first is the order the thoughts come out of your head, and the latter is the syntax of nearly every language- including R natively.

With Postfix I can go

     x.m1.m2.m3.m4
    
Which replaces to the above nested syntax as I select each.

**Comment by jrieken** [comment]
Yeah, post fix editing is a cool concept but it isn't Textmate snippets. I am pretty sure we have all APIs in place that would allow a 3rd party to implement, check the `CompletionItemProvider`-api
