### ISSUE TITLE
Inconsistent setting value when moving setting editor between editor groups

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#78931]
Steps to reproduce:
1. Split editor in two or more groups
2. Open settings editor
3. Move settings editor between all the groups without changing any value
4. Change some value and move settings editor to another group

![settingseditorvalue](https://user-images.githubusercontent.com/25115070/62851514-f5284f80-bcab-11e9-9657-74df4e897a80.gif)

**Comment by roblourens** [comment]
Good catch. Slightly more specific steps for verification:

- Open a text editor, split it
- Open the settings editor on one side
- Drag it to the other side
- Click the font size input to focus it
- Drag back to original side
- Change the font size
- Drag to other side
- The font size is focused and doesn't show the value change that you just made
