### ISSUE TITLE
Git missing from Extension

### ISSUE THREAD

**Issue by ms2008** [microsoft/vscode#78938]
- VSCode Version: 1.37.0
- OS Version: windows10 1809 x64

![vscode](https://user-images.githubusercontent.com/3797918/62856680-2fcfcd80-bd28-11e9-8361-1037d3cc5d30.png)

**Comment by ms2008** [comment]
I have tried add this to `setting.json`:

```
"git.enabled": true,
"git.path": "C:\\Program Files\\Git\bin\\git.exe",
```

Unfortunately, that would not work

**Comment by IllusionMH** [comment]
Do you see any exceptions in console if you open **Help > Toggle Developer Tools**?
Is it in Remote window (Remote-WSL/SSH etc extension) ?

**Comment by ms2008** [comment]
If I recall correctly, it first happen in Remote window. After that, normal window broken too.

**Developer Tools** have only a warning:

```
(node:12184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

I have did a reinstall(*user setup version*), but no luck

**Comment by joaomoreno** [comment]
@ms2008 Can you show me your full settings?

**Comment by ms2008** [comment]
Oops, it was disabled. When I re-enable it, it works. That probably was my fault.

Sorry for the inconvenience and thanks anyway!

**Comment by ms2008** [comment]
We can close this now :)
