### ISSUE TITLE
Debug console does not detect file path

### ISSUE THREAD

**Issue by htnghia** [microsoft/vscode#78939]
In DEBUG CONSOLE, there are some path to file. I cannot click (or cmd + click) on a path to go to file. 
Output example:
 Should return empty if does not have win:
     TypeError: Cannot match against 'undefined' or 'null'.
      at Object.getAllWins (path/to/file/service.js:9:21)
      at Context.<anonymous> (path/to/file/service.js:40:41)
      at next (native)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)

My debug configurations are:
`{
      "name": "mocha",
      "type": "node",
      "request": "launch",
      "internalConsoleOptions": "openOnSessionStart",
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "stopOnEntry": false,
      "args": [
        "--no-timeouts",
        "--colors",
        "-r",
        "test/init.js",
        "/path/to/test/test.js"
      ],
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": null
    },`

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/27713
