### ISSUE TITLE
code completion dont work correctly

### ISSUE THREAD

**Issue by zareshahi** [microsoft/vscode#78932]
after last update angular code completion become crazy and dont show used variables or imported modules as well and only show code complition of other plugins (such as Angular Language Service) 
but this bug is for first try to show and after press Esc and then Ctrl + Space it is work correct
![Screenshot_20190812_123608](https://user-images.githubusercontent.com/7747315/62852142-cf2b9b00-bcfd-11e9-8832-f59cb8ac6654.png)

**Comment by octref** [comment]
Please fill issue to Angular extension. If you can repro the issue in one version of VS Code but not the latest version, feel free to reopen.
