### ISSUE TITLE
当终端字体大小比较大时终端显示有问题//terminal renders wrong when terminal.integrated.fontSize is bigger number

### ISSUE THREAD

**Issue by bysdxt** [microsoft/vscode#78936]
Issue Type: <b>Bug</b>

终端字体大小设得比较大时（例如 26），打开终端会显示有问题，光标位置不对等等。
比较小时（例如 16) 不会有问题

![1](https://user-images.githubusercontent.com/13766766/62855326-8b985780-bd24-11e9-94dd-23cd169979ad.png)

![2](https://user-images.githubusercontent.com/13766766/62855339-93f09280-bd24-11e9-9d1f-c43191f6edf8.png)

![3](https://user-images.githubusercontent.com/13766766/62855356-9c48cd80-bd24-11e9-8ba4-9575e7b6fb86.png)

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (22.12GB free)|
|Process Argv|Z:\TEMP|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
pascal-formatter|ale|2.2.0
clipboard-history|Anj|1.0.7
vscode-glsllint|CAD|0.0.5
npm-intellisense|chr|1.3.0
xml|Dot|2.5.0
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
vscode-nginx-conf-hint|han|0.1.0
beautify|Hoo|1.5.0
Lua-Nginx-Snippets|jie|0.0.4
ecdc|mit|1.3.0
vscode-language-pack-zh-hans|MS-|1.37.5
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
vscode-nginx|sha|0.6.0
shader|sle|1.1.4
vscode-hexdump|sle|1.7.2

</details>

**Comment by byyxx128** [comment]
It seems the known bug of Windows 10 version 1809.
#57803
Please upgrade and try 1903.

**Comment by bysdxt** [comment]
> It seems the known bug of Windows 10 version 1809.
> #57803
> Please upgrade and try 1903.
> (下次标题和描述都要全英文，否则会被直接close）

ok
