### ISSUE TITLE
The name of the file after copying

### ISSUE THREAD

**Issue by wangwangxingao** [microsoft/vscode#78935]
Issue Type: <b>Feature Request</b>

Now 
2019.md  [ctrl+c ctrl+v]  =>  2019 copy.md
Can it be made
2019.md  [ctrl+c ctrl+v]  =>  2020.md

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 6.3.9600

**Comment by IllusionMH** [comment]
/duplicate of #76752

See last comment in thread

**Comment by isidorn** [comment]
@IllusionMH thanks for all the help! Really appreciate it!
