### ISSUE TITLE
tweet feedback button - make it hideable

### ISSUE THREAD

**Issue by guidorice** [Microsoft/vscode#7893]
- VSCode Version: 1.2.1
- OS Version: OS X 10.9.5

I do not use Twitter, and so don't want to see the Tweet Feedback icon/smiley all the time. Add a setting to hide this, please.

**Comment by eklavyamirani** [comment]
While I love this feature, I think I can help with this one. :)

If we can agree on a behavior, I can land a PR for this. @bpasero What do you think?

**Comment by bpasero** [comment]
I am not sure this scales (e.g. having an option for each and every thing in the status bar?). I would rather want to be able to e.g. right click on something in the status bar to hide it (like a Chrome extension) and then another way to bring things back to the status bar. This needs UX prep work too.

**Comment by eklavyamirani** [comment]
I know what you're saying. I like the way most browsers handle this, a drag and drop based toolbar. It works really well, and gives a way to personalize the status bar.

I'd really like to help with this. :)

**Comment by smlombardi** [comment]
go to `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css`

find `.monaco-shell .statusbar-item>.dropdown.send-feedback{display:inline-block}`

and change it to `display:none`

you'll likely need to do this after every update.  Caveat:  worked for me, but I take no responsibility for it breaking anything important.

**Comment by svnv** [comment]
It looks like the file has been moved. I edited this file (same change as above) to remove the icon: `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.css`

**Comment by intheloop** [comment]
+1 Make it go away!

**Comment by olhapi** [comment]
+1
pls, make an option to remove that annoying icon
tweaking editor's css is not an option

**Comment by netsgnut** [comment]
Would agree that we need an option for that.

Alternatively, is it possible that the Tweet Feedback button to be implemented as an extension instead? It kinda reminds me of Atom's metrics plugin, which is activated by default but can be removed.

**Comment by joanisc** [comment]
+1
pls, make an option to remove that annoying icon
tweaking editor's css is not an option

**Comment by yuhr** [comment]
+1
Also it should be possible to send feedback on the command palette by default.

**Comment by kmoe** [comment]
Fix on (Arch) Linux is the same as [above](https://github.com/Microsoft/vscode/issues/7893#issuecomment-250941381): the file is located at `/opt/visual-studio-code/resources/app/out/vs/workbench/electron-browser/workbench.main.css`.

Has anyone looked into making an extension that can fix this? Perhaps something like this to inject custom CSS? https://github.com/be5invis/vscode-custom-css

**Comment by leonadler** [comment]
On arch, installing an update reverts the css file. Having a setting (preferably) or an extension (okay-ish) would be better than manually editing on every release.

**Comment by kmoe** [comment]
@leonadler well I guess the idiomatic Arch solution to that is to stick the following in `/usr/share/libalpm/hooks/visual-studio-code.hook` to tweak the file after each package update:

```
[Trigger]
Operation = Install
Operation = Upgrade
Type = File
Target = opt/visual-studio-code/resources/app/out/vs/workbench/electron-browser/workbench.main.css

[Action]
Description = Removing smiles...
Exec = /bin/bash -c 'read -r f; sed -i 's/\.send-feedback{display:inline-block}/\.send-feedback{display:none}/' $f;' 
When = PostTransaction
NeedsTargets
```

(This is a joke. Works for me though.)

**Comment by raymeibaum** [comment]
+1

**Comment by ShayBox** [comment]
+1

**Comment by Vrox** [comment]
+1

**Comment by ShiftyAxel** [comment]
+1
I neither want nor need social media integration in my code editor.

**Comment by li-xinyang** [comment]
+1

**Comment by chriscarpenter12** [comment]
I don't mind a way to provide feedback, but put it under the Help menu or something where you would expect to see something like this. It distracts me every time I look in the status bar for something... Sure we could edit the applications css file, but should we really have to?

**Comment by xiguaxigua** [comment]
+1

**Comment by bodenlos** [comment]
+1

**Comment by leonadler** [comment]
Please use the "thumbs up" reaction on the issue itself to show your interest in it being resolved. If you write a "+1" comment, 22 people get a useless notification. (This goes for all GitHub projects, by the way.)

Thanks.

**Comment by joschabach** [comment]
@bpasero There is no one assigned to this now. I don't think that it makes sense to wait until someone rewrites large parts of the workbench UI. A lot of us OCD nerds are super annoyed by having a face staring at them that does not serve the user but only the marketing department. Do you really think that a grinning button to tweet about my text editor ought to be the most reachable and prominent permanent feature of the UI?

**Comment by joschabach** [comment]
<img width="276" alt="no twitter button" src="https://user-images.githubusercontent.com/920081/30497748-fcc8a036-9a21-11e7-876f-7d178d4fe389.png">

Screenshots in the release notes suggest that there might be an undocumented way of turning off the twitter smiley button (and that the VSCode devs are as annoyed as the users by it). Could you please let us in on the secret? Patching the CSS with every update is not a good solution.

**Comment by herrbischoff** [comment]
Looking at it from a product design angle, there is absolutely zero reason for that smiley face to be where it is. It is distracting, it serves no function and given the target audience it at best annoys. It's probably a political decision, which is a shame because VSCode is an impressive product. It is the only Electron application I use because it doesn't feel like a web app and the only editor that was able to lure me away from Vim/Neovim for any extended period of time. Extensible code editors need to be customizable. Since hiding the element is a simple matter of adjusting the CSS, it should be a preference setting.

**Comment by joschabach** [comment]
@herrbischoff I think you are right. Given all the thought and taste that went into designing the interface of VSCode, and reflecting on the needs and sensibilities of an audience of people that design software and user interfaces themselves, the smiley tweet feedback button sticks out like a sore thumb, and perhaps not just by accident. Everything about this UI element seems to be the decision of someone higher up in the corporate food chain with the power to overrule and vandalize the work of their hapless underlings. A hidden warning to engineers against working at MS?

**Comment by jwigley** [comment]
Whilst the standard O365 suite apps (Excel, Word etc) all have a smiley face with a form, somehow Microsoft Teams got away with feedback light bulb which links to https://microsoftteams.uservoice.com. No twitter required. 
![screen shot 2017-09-18 at 1 49 35 pm](https://user-images.githubusercontent.com/7350464/30528688-b8a91846-9c78-11e7-8da1-df724bb19bbc.png)

**Comment by kmoe** [comment]
I have updated the pacman hook in https://github.com/Microsoft/vscode/issues/7893#issuecomment-314497354 to reflect the current location of the CSS file so Arch users can automatically fix their editors. I am pleased to announce that this hook file is now in the Extended Support phase (Service Pack 2), meaning that I will occasionally check that the fix is still working and update it if I feel like it.

Regarding @joschabach's comments, perhaps what the smiley face really represents is a product-driven commitment to expanded consumer choice. For example, it made me aware of a product niche of editors without smiley faces, so I have now properly switched to [spacemacs](https://github.com/syl20bnr/spacemacs).

**Comment by jessejanderson** [comment]
In addition to being able to hide the Feedback icon, why not settings to optionally hide any/all sections? I personally have no use for knowing that `Spaces: 2` and that my line endings are `LF` because those are the same for all of my projects.

Some simple toggle settings like these would be really nice:
```
"workbench.statusBar.showEndOfLineSequence": true,
"workbench.statusBar.showFeedbackSmiley": false,
"workbench.statusBar.showIndentation": true,
```

**Comment by herrbischoff** [comment]
Just throwing this one-liner in here to get rid of it on macOS with a current path:

```bash
sed -i '' 's/\.send-feedback{display:inline-block}/\.send-feedback{display:none}/' /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css
```

**Comment by pzelnip** [comment]
^^ When I made that change & restarted the icon was gone, but then shortly after I got "Warn: Your Code installation appears to be corrupt. Please reinstall." :(

**Comment by herrbischoff** [comment]
@pzelnip: It's a one-time warning and does not hurt anything.

**Comment by joschabach** [comment]
VSCode updates frequently, and would have to be sanitized every time, which is not a good option. Is it feasible to fix it with a small extension (that could also customize the statusbar)?

**Comment by Tyriar** [comment]
A pattern we've been using lately is to allow hiding of components via the context menu, it would probably make sense to be consistent in the status bar:

<img width="616" alt="screen shot 2017-10-25 at 10 49 15 am" src="https://user-images.githubusercontent.com/2193314/32014199-41cb2c84-b972-11e7-83cb-56378596a984.png">
<img width="194" alt="screen shot 2017-10-25 at 10 49 21 am" src="https://user-images.githubusercontent.com/2193314/32014200-439af940-b972-11e7-8c46-9f668b4de357.png">

(Copied this over from https://github.com/Microsoft/vscode/issues/3544)

**Comment by verpixelt** [comment]
May I ask what's the status on this?

**Comment by bpasero** [comment]
A new setting `workbench.statusBar.feedback.visible` was added to support this. This can also quickly be configured from a new checkbox in the feedback form itself:

![image](https://user-images.githubusercontent.com/900690/34614600-4ea5fd5a-f232-11e7-8e68-10f7e75a4072.png)

**Comment by joschabach** [comment]
Yay, thanks!On Jan 5, 2018, at 16:07, Benjamin Pasero <notifications@github.com> wrote:A new setting workbench.statusBar.feedback.visible was added to support this. This can also quickly be configured from a new checkbox in the feedback form itself:—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zhaomiing** [comment]
but the placeholder width is still there, can we guys remove that too?

**Comment by bpasero** [comment]
Not for me:

![image](https://user-images.githubusercontent.com/900690/35957576-85212f38-0c9c-11e8-8a47-e9b0921e5d64.png)

Maybe try a restart, it should be fine.

**Comment by zhaomiing** [comment]
thanks, problem solved after disable the [quokka extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
