### ISSUE TITLE
Cursor is off 1 position to the right

### ISSUE THREAD

**Issue by jongmana** [microsoft/vscode#78941]
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.34-04457-g5b63d4390e96
I'm using ChromeOS on a acer spin13 chromebook

Steps to Reproduce:

1. Open a file to edit in VSC and then open page in the chrome browser
2. Ctrl-tab to VSC
3. type something and the letters you type will not appear under the cursor but one at the character before the cursor.
  

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Let's track in #77817 . It looks related to using ChromeOS . Workaround is `"editor.disableMonospaceOptimizations": true`
