### ISSUE TITLE
[php] syntax highlighting issue with strings

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#7894]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:
1. See images

![invalid highlight](https://cloud.githubusercontent.com/assets/1571806/16201220/27e58a6e-36d6-11e6-8b86-2238ccca5a0d.PNG)
```php
<?php
class h {
    function test(
        string $string,
        int $flags = ENT_COMPAT | ENT_HTML401,
        string $encoding = 'ini_get("defaul_charset")',
        bool $double_encode = true): string {
        }
    )
}
```
![invalid highlight 2](https://cloud.githubusercontent.com/assets/1571806/16201298/69a80076-36d6-11e6-91f8-93038c7619e0.PNG)

**Comment by aeschli** [comment]
This issue was moved to atom/language-php#186
