### ISSUE TITLE
^[ symbol when pasting code into ipython console

### ISSUE THREAD

**Issue by dbrakenhoff** [microsoft/vscode#78942]
Issue Type: <b>Bug</b>

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

When I copy multiple lines of code from the editor and paste it into an IPython console in Visual Studio Code, a `^[` is added between each line of code. Copy-pasting two lines of Python code will reproduce the problem. See the screenshot below. When I paste into an IPython console I started through command prompt, I see a `^M` (carriage return?) after every line of code, but in that case the code can still be run. 

Steps to Reproduce:
1. Select multiple lines and copy (ctrl + c)
2. Place cursor in an internal IPython console
3. Paste the selection (ctrl + v)

Expected behaviour:
The lines are copied in a way that allows the code to be run after pressing Enter.

Actual behaviour:
^[ is added between each selected line.

![image](https://user-images.githubusercontent.com/6552225/62858379-7a3a5580-bcfa-11e9-8b68-62d9dadf2edd.png)

**Comment by giveshot** [comment]
got the same problem after updating my vs code today.
tried reinstall all extensions but did't work

**Comment by dbrakenhoff** [comment]
This issue also occurs when all extensions are disabled. Also this only happens in the IPython console in VSCode, not external IPython consoles...

**Comment by dbrakenhoff** [comment]
This issue is [unrelated](https://github.com/microsoft/vscode-python/issues/6935#issue-479711848) to the Python extension. Can it be reopened?
