### ISSUE TITLE
Connection got disposed.

### ISSUE THREAD

**Issue by pramit-marattha** [microsoft/vscode#78943]
Error Message: Connection got disposed.
Product: Visual Studio Code
Version: 1.37.0 
Electron: 4.2.7
Node.js: 10.11.0
OS: Windows_NT x64 10.0.17763
Language: en

![image](https://user-images.githubusercontent.com/37651620/62859408-c4343300-bd1c-11e9-9f24-45d6c44652ac.png)

**Comment by shottei** [comment]
Can you please add more info? like what connection got disposed?
