### ISSUE TITLE
C++ code color highlight fails to recognize #endif directives in certain case

### ISSUE THREAD

**Issue by AkatsukiT** [microsoft/vscode#78947]
- VSCode Version:1.37.0
- OS Version: Windows 10 Pro 1803

Steps to Reproduce:
If there are two comments after the lines of code which are above the "#endif ",
then "#endif" will not be properly recognized as directive.

```
#if 0 // comment 1
	function( );	//comment 2
#endif
```

![image](https://user-images.githubusercontent.com/41064866/62863471-d6759780-bd43-11e9-848a-8cb154289845.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by AkatsukiT** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [syntax highlighting on #ifdef   (#72100)](https://www.github.com/microsoft/vscode/issues/72100)
It's a different issue.

**Comment by alexr00** [comment]
Already fixed in insiders!
