### ISSUE TITLE
Import statement Intellisense problem and suggestions for the imported

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#78958]
Import statement intellisense doesn't work for some cases like this

![First](https://user-images.githubusercontent.com/42807112/62871558-fabd7e00-bd1b-11e9-83a0-cd6f4558c243.gif)

This must complete `@sapper/app.mjs` as it is a module related to the directory
this is my directory

![Screenshot (3)](https://user-images.githubusercontent.com/42807112/62871663-2fc9d080-bd1c-11e9-94d8-4bb7b3d27847.png)

But I found an extension that does that trick see when enabling it the matter works

![Second](https://user-images.githubusercontent.com/42807112/62872149-22f9ac80-bd1d-11e9-8813-4cf098fe3ed6.gif)

But the problem is that the imported module doesn't have intellisense see here

![Third](https://user-images.githubusercontent.com/42807112/62872410-b337f180-bd1d-11e9-9a8e-9b3dcf3d1853.gif)

This should have completed `sapper.start` and other methods like `sapper.goto` They are exported from that file

![Screenshot (4)](https://user-images.githubusercontent.com/42807112/62872555-0ad65d00-bd1e-11e9-9b56-991779a81622.png)

So, what to do here? Am I missing something or configuration?

**Comment by mjbvz** [comment]
Please share steps to reproduce this issue (possible with a small example project) 

/needsMoreInfo

**Comment by minkir014** [comment]
First I am on node 10.16.0 and the latest vs code version
### Reproduce Steps:
1.  run command `npx degit sveltejs/sapper-template#rollup Starter` to generate the project.
2.  open the project in vs code and the `client.js` in the `src` folder and erase everything in it
3.  try what happens in the `gif` pictures above

Side Note:
The extension I mentioned in my above comment is here https://marketplace.visualstudio.com/items?itemName=leizongmin.node-module-intellisense

**Comment by minkir014** [comment]
Have you ran into a problem about creating sapper project???

**Comment by minkir014** [comment]
@mjbvz Is there any news about the issue??

**Comment by minkir014** [comment]
Hey. Why have this issue been forgotten? Is there anyone can help???

**Comment by mjbvz** [comment]
If you want support for individual problems, try asking  on stackoverflow. This is likely a config issue with your project 

I'll look into it but it isnt a priority

**Comment by leegee** [comment]
This is currently the only open issue that references '.mjs' -- is there anyway to get MJS files treated as JS files? `.mjs` is now often a required extension for ES modules (strangely, not `.mes`...)

**Comment by mjbvz** [comment]
@leegee https://github.com/microsoft/TypeScript/issues/27957

**Comment by mjbvz** [comment]
This is a configuration issue.

`'@sapper'` is not an import that our IntelliSense can understand by default. You can confirm this by [enabling semantic checking](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript) in the js file.

At starting point, create a [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) and configure [`paths `](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases) so that VS Code can resolve `@sapper` to the correct location
