### ISSUE TITLE
JS getContext("2d") intellisense issue

### ISSUE THREAD

**Issue by hkgmahwa** [microsoft/vscode#78959]
Issue Type: <b>Bug</b>

VS Code provides no intellisense for getContext("2d") and all its methods in Javascript.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         530  @ 2.93GHz (4 x 2926)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
python|ms-|2019.8.29288
cpptools|ms-|0.24.1

</details>

**Comment by IllusionMH** [comment]
Could you provide code that causes an error?

Do you see error `Object is possibly 'null'.` if you hover over `ctx.` (or how you named result of `canvas.getContext('2d')`)?
![image](https://user-images.githubusercontent.com/1312662/62876721-45e08c80-bd2e-11e9-8653-c5eee3215217.png)

This method returns `CanvasRenderingContext2D | null` but you can get suggestions if you narrow it to `CanvasRenderingContext2D`.

http://www.typescriptlang.org/play/index.html#code/CYUwxgNghgTiAEA3W8xQHbIM4C54AkAVAWQBkBhDbAUQhAFsR0AXAbgCh2wB7dLZ1MwAe8ALyoqULADoA5iGblezEEOYAKAOQAmYJoCUreAHpjgkQEss8AAaVMUgEpNQMC+llKWq5toAi8AA+8OgArhAQNpwWAGbw6gCEYML68ADe7PBZ8MwAFjDcAO7wmgBy3KjKPvBQyBbQAEZ0mhwAvpzJQtImZoXcMADW1rkgcPAN4FChWAid8FYhRbb22M7oru6eVWr+UUA
