### ISSUE TITLE
intermittent freezing

### ISSUE THREAD

**Issue by builder7777** [microsoft/vscode#78951]
Issue Type: <b>Bug</b>

The VS Code started freezing periodically after the last update.
If i switch to different application, then switch back to VS Code, it hangs for about 10-20 seconds, then works normally. If I open a new file, it hangs for 10-20s then works again. Same happens if I open a list of files in the current project. This happens every 2-5 minutes, it's basically unusable.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.0.6
insertnumbers|Asu|0.9.1
vscode-django|bat|0.19.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
json-tools|eri|1.0.2
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
diff-tool|jin|0.0.1
MagicPython|mag|1.1.0
xml-format|mik|1.0.2
vscode-docker|ms-|0.7.0
python|ms-|2019.8.29288
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
vsliveshare|ms-|1.0.657
vuejs-extension-pack|mub|1.1.5
autodocstring|njp|0.3.0
vetur|oct|0.21.1
nginx-formatter|ray|0.0.4
vscode-essentials-snippets|rob|2.0.0
vscode-paste-and-indent|Rub|0.0.8
code-settings-sync|Sha|3.4.1
vscode-nginx|sha|0.6.0
vscode-fileutils|sle|2.14.5
vscode-hexdump|sle|1.7.2
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|1.5.0
highlight-matching-tag|vin|0.9.3
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.2.0
vuetify-vscode|vue|0.2.0
jinja|who|0.0.8
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
