### ISSUE TITLE
OnDidCloseTextDocument fired in an increment way.

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#78952]
- VSCode Version:1.37.0
- OS Version:WINDOWS_NT

Steps to Reproduce:

1. open a file using vscode.workspace.openTextDocument
2. using vscode.window.showTextDocument show the text document.
3.  write a cb function(with console.log) in vscode.workspace.onDidCloseTextDocument 

see that the log is printed in an incremented way. (1st call --1log, 2nd call --2logs and ....)

Does this issue occur when all extensions are disabled?: Yes

**Comment by akhilravuri1** [comment]
Hi,
I have one more issue with  OnDidCloseTextDocument()
My issue is related to this https://github.com/microsoft/vscode/issues/30820 .

I have created an extension and this works fine when I use F5 to activate the extension.
But I have created a vsix file and installed it using that, then the call back function inside the OnDidCloseTextDocument() is not called.

code:-
```
vscode.workspace.openTextDocument(vscode.Uri.file(path_file))
            .then( value => {
            vscode.window.showTextDocument(value)
            .then(value1 => {
                vscode.workspace.onDidCloseTextDocument(function(){
                    console.log(value.isClosed)
                        })
                })
           })
```
Is there anything I have done wrong?

**Comment by bpasero** [comment]
@akhilravuri1 you say the way the output is displayed is incremental or what?

**Comment by akhilravuri1** [comment]
Yes! the output is displayed in an incremental way for my 1st message.

**Comment by bpasero** [comment]
@akhilravuri1 can you provide a full sample extension (from hello world generated) with steps to reproduce exactly?

**Comment by akhilravuri1** [comment]
Ok..give me some time I will create it and I will give you the git link.
Thanks.

**Comment by bpasero** [comment]
Thanks

**Comment by akhilravuri1** [comment]
Hi @bpasero 

You can clone the code from this https://github.com/akhilravuri1/hellovscode

You can see the log "close call" will be displayed in an incremental way.

And If you create a vsix file and then the callback function is not at all called.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @bpasero 
If you need more information please let me know.

Thanks,
Akhil

**Comment by bpasero** [comment]
@akhilravuri1 but each time the "Hello World" command is invoked you are registering another `vscode.workspace.onDidCloseTextDocument` listener, so it is expected that it fires more than once, no?

**Comment by akhilravuri1** [comment]
Is there any way to register the command only once.

**Comment by bpasero** [comment]
@akhilravuri1 yes, just move it out of the command invocation and below the activate() method of the extension. That one is only called once.

**Comment by akhilravuri1** [comment]
I have one more issue that is a callback function is not getting activated in the vsix file Is there anything that I did wrong? In the above code.

**Comment by akhilravuri1** [comment]
Hi @bpasero 
Before posting here I have done googling for several hours and posted in forums and slack but I couldn't get the answer.
can you please help me with this.

The call function of onDidCloseTextDocument() is not working through vsix file can you please help where I made the mistake. I was unable to debug as logs are not getting printed through vsix installation.

```
vscode.commands.registerTextEditorCommand('extension.closeEditor', (value) => {
        vscode.workspace.onDidCloseTextDocument(function(){
              if (value.document.getText()){
              const pickListItems = [];
              const option1 = {
                  label: "Yes",
                  description: "To Apply the changes",
              };
              const option2 = {
                  label: "No",
                  description: "Don't Apply the changes",
              };
              pickListItems.push(option1,option2)
              vscode.window.showQuickPick(pickListItems,{
                  ignoreFocusOut: true,
                  placeHolder: "Do you want to Apply the changes",
              }).then(SOME CODE)
     })
vscode.workspace.openTextDocument(vscode.Uri.file(path_file1))
            .then( value => {
            vscode.window.showTextDocument(value)
            .then(value1 => {
                console.log("This is value1",value1);
                vscode.commands.executeCommand('extension.closeEditor');
         })
  })
```
After closing the file the show pick is popped up If the installation is done using vsix file.


Thanks,
Akhil

**Comment by bpasero** [comment]
@akhilravuri1 see this PR (https://github.com/akhilravuri1/hellovscode/pull/1) I made for how I think you can make sure the listener will only be installed once. It seems to work for me.

**Comment by akhilravuri1** [comment]
Hi @bpasero 

Thanks for the fix It really helped me but it works fine when I start debugging with the code but If I create a vsix package and install it does not work.

Thanks,
Akhil

**Comment by bpasero** [comment]
I am sorry but I cannot offer more help now. I suggest you try to get help through our other channels (e.g. https://stackoverflow.com/questions/tagged/visual-studio-code).

**Comment by akhilravuri1** [comment]
Thanks, I DO THANK YOU for your help.
But, I have tried asking questions in all the forums and googled about this is for a day I was unable to find any solution. 
 If you have any solution or related links can you please share that with me. I am really frustrated with this. :(

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @bpasero 
Sorry to bother you again. But there is something wrong. When you pushed the code to active() onDidCloseTextEditor was called only once which is cool. But when I try to get the text of that document It is not working. It is comparing with git. It is designed like that or there is an error.

```
Congratulations, your extension "hellovscode" is now active!
THIS IS PATH_FILE c:\Users\rakhil\VSCode_DevOps\hellovscode\ddl1.txt
close call c:\Users\rakhil\VSCode_DevOps\hellovscode\ddl1.txt.git
THIS IS getText() 
```
since ddl.txt is in the git it is showing some data so I renamed the file to ddl1.txt which is not there in the git. Then it is unable to get the data.

Thanks,
Akhil
