### ISSUE TITLE
Emmet Abbreviation with cursor locations results in multicursor when expanded with star operator

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#78960]
Version: 1.37.0-insider
Commit: 5e08ee01b7daee99cdda2456f19d77e715fb8762
Date: 2019-08-05T21:25:08.801Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-30deepin-generic

Steps to Reproduce:

1. Add custom Emmet Snippet.JSON in Project Folder:

```
{
  "html": {
    "snippets": {
      "test": "title{${1|Hello,World|}}+id{${2|1,2|}}"
    }
  }
}
```
2. Open new HTML File and try to complete 'test' Emmet Snippet e.g. test*4
3. Try to Tab through all Choice Selectors

It does not work, because if I choose one Option on the first Selector all my 4 elements get this Option, but i want to choose each individually

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Reproduced -- it ends up with multicursor behaviour.

**Comment by rzhao271** [comment]
Actually, @alexanderniebuhr I think because you put the {1} and {2} there that it hardcodes those values, and so you end up with multi-cursor. I haven't looked too far into writing snippets with cursor locations yet, but I'm wondering if there's a way to do it without hardcoding those values in?
