### ISSUE TITLE
VSCode keep scroll from another windows

### ISSUE THREAD

**Issue by IAmKapuze** [microsoft/vscode#78964]
Issue Type: <b>Bug</b>

OS: Ubuntu 18.04
VSCode keep scroll from another windows, opened on top of VSCode, when VSCode in fullscreen mode.
Steps for reproduce:
1. Open VSCode on fullscreen
2. Open another window on top of VSCode
3. Scroll in top window
4. Maximize VSCode window
5. Scroll in VSCode window

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3636)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (1.07GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.4
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|0.5.0
CppSnippets|har|0.0.14
vscode-clang|mit|0.2.3
python|ms-|2019.8.29288
cpptools|ms-|0.25.0-insiders
reloaded-cpp|rel|0.1.9

</details>

**Comment by deepak1556** [comment]
@IAmKapuze can you test this with our exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821. Thanks!
