### ISSUE TITLE
Windows: F1 should open some kind of help and not command pallette

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#7896]
- VSCode Version: 1.2.1
- OS Version: Windows 10

My keyboard has the word **Help** stamped right on the **F1** key's legend.   As a long-term Windows and Visual Studio user, I expect **F1** to mean Help!   Preferably context-sensitive help that focuses on what I'm focused on (DWIM.)  So for example, when I'm editing README.md, I sort of hope that F1 to produce a Markdown cheat sheet.

While I appreciate the command pallet that F1 currently invokes in VSCode, it can be invoked by other means (e.g. **Ctrl+Shift+P**), and some interesting expectations seem to have come from mapping F1 to the command pallet.   #7269.  

I couldn't agree more that an F key shortcut is justified, perhaps **F4** would be a better mapping for displaying the command pallet given the traditional Windows UI guidelines.   **F4** has long been used in contexts such as a combo-box to display a list of alternatives.   See [Guidelines for Keyboard User Interface Design](https://msdn.microsoft.com/en-us/library/ms971323.aspx).   Also try, for example, pressing **F4** in the windows explorer, internet explorer, etc.

**Comment by bpasero** [comment]
You are free to rebind any keybinding we picked.

**Comment by BurtHarris** [comment]
Yes, of course.   The point is that the choice you picked is confusing and goes against the longstanding Windows UI guidelines.   Your changed title sort of misses that.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
