### ISSUE TITLE
Parentheses swallowing does not work when parentheses are inserted by autocomplete

### ISSUE THREAD

**Issue by TheRealCodeCube** [microsoft/vscode#78975]
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.7-100.fc29.x86_64

Steps to Reproduce:

1. Create a new Java file.
2. Write a basic main function.
3. Inside the main function, start typing 'main' and use autocomplete to expand it to `main(args)`.
4. Type in an argument, then type in a closing parenthesis.
5. Instead of the expected behavior of swallowing the last parenthesis, an extra parenthesis will be inserted.

Does this issue occur when all extensions are disabled?: No, because the default autocomplete does not understand function calls without the use of an extension, and therefore does not insert any parentheses. See ~~above~~ following comment about the Javascript extension.

The incorrect behavior is exhibited with any extension that provides autocomplete which inserts parentheses when autocompleting a function call. For example, I also tested this bug on Rust and Javascript code, using their respective extensions. The bug shows up with Rust but not with Javascript, because the latter requires the user to type the parentheses themselves, which correctly trigger parenthesis swallowing.

Behavior in Java:
![output](https://user-images.githubusercontent.com/9629610/62887007-32630080-bcf1-11e9-8b93-cf1f2288adf0.gif)
(Same problem with Rust.)

Behavior in Javascript:
![output(1)](https://user-images.githubusercontent.com/9629610/62887228-b61ced00-bcf1-11e9-8f99-98950eccc11c.gif)
(This behavior is also displayed when extensions are disabled, as the basic autocomplete does not insert parentheses, similar to the Javascript autocomplete.)

**Comment by fwcd** [comment]
Same thing with Kotlin:

![screencast](https://user-images.githubusercontent.com/30873659/63128007-32465780-bfb4-11e9-9986-626242837bbb.gif)

**Comment by jkyeung** [comment]
This also happens with *some* quotes in Python. String literals with a prefix character (Unicode, bytes, formatting, raw) have an automatically generated close quote, but that quote is not swallowed. (Sorry, I don't know how to make those little animated snippets.) This is even though I have **not** moved the cursor *at all*:

    f|  # vertical bar character marks the cursor

    f"|"  # after typing one quote

    f"foo|"  # after typing 'f', 'o', and 'o'

    f"foo"|"  # after typing another quote

**Comment by alexandrudima** [comment]
@jkyeung I've extracted this case to a separate issue at #79430
