### ISSUE TITLE
Tree view doesn't programatically collapse Tree items

### ISSUE THREAD

**Issue by MasterUgoZapad** [microsoft/vscode#78970]
I'm developing custom VSCode extension and i want to have an option to quickly collapse some expanded tree view items. 
For this purposes I've tried to trigger `onDidChangeTreeData` event and recreate TreeItem with desired collapsible state, but it din't have effect.

There is a pretty similar issue https://github.com/Microsoft/vscode/issues/44746 , but solution mentioned in there is only suitable for expanding tree items (I tried to call `reveal` with `expand: false` option, and it didn't work also).

Also `Collapse all` button is not suitable for my needs. 

I'm on Version 1.37.0

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/92176
