### ISSUE TITLE
Ignore specific folders code analysis (or at least report errors from them).

### ISSUE THREAD

**Issue by cyraid** [microsoft/vscode#78977]
I think this was discussed in a different issue https://github.com/microsoft/vscode/issues/78291
But I have a project that has different libraries, each with their own coding style.. They do not have .editorconfig files associated with them (nor does multiple .editorconfig files even work with VSCode currently). It'd be nice to ignore errors (without seeing the badge count either) from these folders so I don't have to see 100+ errors, and none of them from my project. :)

Edit: My project is a C# unity project that has a few other open source projects inside the folders.

**Comment by mjbvz** [comment]
Please file this as a feature request against the c# extension
