### ISSUE TITLE
Install Extension fails: does not properly install node_modules into extension folder

### ISSUE THREAD

**Issue by celador** [Microsoft/vscode#7897]
- VSCode Version:
1.3.0
- OS Version:
Mac OS 10.11.5

Steps to Reproduce:

1. Install extension ForceCode
2. Open in Visual Studio Code - Insiders Build v. 1.3.0 while not debugging.
3. Attempt to activate extension with compile
4. Get the error 'No handler found for the command ...' An extension might be missing an activation event.

Notes:  Extension works properly when `npm install` is run in the extension directory.  When it's packaged or published and installed in the client, not all dependencies get installed, leading to "missing module" showing up in the developer console.  I've added about 30 low level dependencies, and it currently works on one of my macs and not the other, they are the same versions and OSs

**Comment by celador** [comment]
Looking through the Developer Tools with the extension open, I'm getting lots of "Cannot find module ..." errors.  

I am using node 6.2.1 and npm 3.9.3

**Comment by celador** [comment]
Which versions of NPM and Node are recommended to be used for development?  It seems that I have the correct Node modules in my node_modules folder, but they are not registering for Code

**Comment by celador** [comment]
@alexandrudima I opened up the extension and ran `npm install` in the extension folder, and the extension works properly now.

**Comment by rebornix** [comment]
Here is the thing, currently vscode will not do anything after the extension bits are uploaded to the marketplace or after installing the extension to local disk, so when you publish the extension and the node_modules you referenced in the code are not included in the extension bits, they will not show in users' machine. 

A proper solution is use `.vscodeignore` to handle file inclusion/exclusion, eg, https://github.com/rubyide/vscode-ruby/blob/master/.vscodeignore

**Comment by celador** [comment]
@rebornix I had a .vscodeignore file  I copied the one you linked and removed a few lines from mine, then tried to publish again, but with the same results.  The package works on one machine, but not the other.  I don't understand why some packages would install, but not others, but then when I run `npm install` in the extension folder, it installs all the packages it needs.  

I'm currently going through and bumping the version and installing package by package all the low-level packages like `glob`, `faye-websocket`, `hawk`, etc... basically dependencies of my dependencies are not getting installed.

**Comment by rebornix** [comment]
Repro on my machine, only part of the npm packages are downloaded, seems not all dependencies are included into the final extension vsix. @joaomoreno any ideas?

**Comment by joaomoreno** [comment]
This issue was moved to Microsoft/vscode-vsce#100
