### ISSUE TITLE
[scss] support passing arguments to content blocks in mixins

### ISSUE THREAD

**Issue by yringler** [microsoft/vscode#78974]
Issue Type: <b>Bug</b>

As of [Dart Sass 1.15.0](https://github.com/sass/dart-sass/releases/tag/1.15.0), sass supports [passing arguments to content blocks in mixins](https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks).

For example, 
```
@mixin rtl($ltr-dir) {
	.dir_ltr & {
		@content($ltr-dir);
	}
}

@include rtl("left") using ($dir) {
	margin-#{$dir}: 10px;
}
```

Is valid, but vscode scss lint reports errors, notably "scss(css-semicolonexpected)" after the @content and the using keyword

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.801.1
transformer|dak|1.6.0
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
gitlens|eam|9.9.3
vscode-ember|emb|0.2.0
vs-code-xml-format|fab|0.1.5
sass-lint|gle|1.0.5
angular2-switcher|inf|0.2.0
Angular2|joh|8.1.1
openapi-lint|mer|1.0.3
csharp|ms-|1.21.0
Go|ms-|0.11.4
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
vscode-json-editor|nic|0.2.3
vetur|oct|0.22.0
openapi-designer|phi|0.3.0
vscode-yaml|red|0.4.1
copy-path-linux|sai|1.1.2
code-spell-checker|str|1.7.17
nativescript|Tel|0.10.1
vscodeintellicode|Vis|1.1.9
nativescript-ng2-snippets|www|2.0.1

</details>

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/commit/94db8300992dd9d4a00eed0ebe93bee5c0148cc7
