### ISSUE TITLE
Markdown preview no longer shows images

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#7898]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Steps to Reproduce:

1. Open a vscode-docs topic with an image (/docs/editor/codebasics.md)
2. Use Markdown preview

No image is shown, only link name.
```
![VS Code Layout](images/codebasics/layout.png)
```
![VS Code Layout](images/codebasics/layout.png)

**Comment by gregvanl** [comment]
Looks like it can not resolve the relative paths.  It will work if the path is relative to the workspace but not relative to the Markdown file location.

**Comment by rebornix** [comment]
@gregvanl works as charm on my Mac with latest Insider build, I'll give it another try once I have my Windows. 

BTW, you may want to close the preview pane and trigger the preview again, or reload the window then preview once more, then if the image is shown correctly, I'll say it can be some file detecting issue. People are running into similar issue in other cases.

**Comment by rebornix** [comment]
Finally the root cause came back to my mind. After switching the markdown preview to extension, we start to use web view instead of a single iframe to show the generated html for better security, but webview has no idea what those relative URIs mean. We have a fix for bookmarks in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.html#L77 and we should have a similar workaround for relative image links.

**Comment by rebornix** [comment]
@jrieken may have valid reasons when designing this baseUrl setting, let's wait and see his input.

**Comment by Platzer** [comment]
## Setup:
- Version 1.3.0-insider
- Commit 62f0272219dc72fda5246d330640e6af52a10cd0
- Date 2016-06-20T22:45:16.666Z
- OS Version:Windows 7

## Tests:
1. :+1: Absolute path without whitespace and slash (`/`) as delimiter  
  `![](C:/workspace/markdown/screenshots/pic.jpg)`
1. :-1: Absolute path with whitespace and slash (`/`) as delimiter  
  `![](C:/workspace/markdown/screenshots/pic one.jpg)`
1. :-1: Absolute path without whitespace and backslash (`\`) as delimiter  
  `![](C:\workspace\markdown\screenshots\pic.jpg)`
1. :-1: Absolute path with whitespace and backslash (`\`) as delimiter  
  `![](C:\workspace\markdown\screenshots\pic one.jpg)`
1. :+1: Path relative to workspace without whitespace and slash (`/`) as delimiter  
  `![](markdown/screenshots/pic.jpg)`
1. :-1: Path relative to workspace with whitespace and slash (`/`) as delimiter  
  `![](markdown/screenshots/pic one.jpg)`
1. :+1: Path relative to workspace without whitespace and backslash (`\`) as delimiter  
  `![](markdown\screenshots\pic.jpg)`
1. :-1: Path relative to workspace with whitespace and backslash (`\`) as delimiter  
  `![](markdown\screenshots\pic one.jpg)`
1. :-1: Path relative to markdown without whitespace and slash (`/`) as delimiter  
  `![](screenshots/pic.jpg)`
1. :-1: Path relative to markdown with whitespace and slash (`/`) as delimiter  
  `![](screenshots/pic one.jpg)`
1. :-1: Path relative to markdown without whitespace and backslash (`\`) as delimiter  
  `![](screenshots\pic.jpg)`
1. :-1: Path relative to markdown with whitespace and backslash (`\`) as delimiter  
  `![](screenshots\pic one.jpg)`

**Comment by jrieken** [comment]
The problem is that we encode the window drive letter `file:///d%3A/` vs `file:///d:/`

**Comment by jrieken** [comment]
Pushed a change that should fix this - tho not yet verified...

**Comment by Platzer** [comment]
# Setup:
- Version 1.4.0-insider
- Commit 9c4890399293ee5c87c4f7bfb5405d120ea650c6
- Date 2016-07-18T05:06:59.781Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0
- OS Version:Windows 7

Path with whitespace are not working on windows. Checkout test repo https://github.com/Platzer/TestVscode-7898.
