### ISSUE TITLE
Not able to install any extension from the extensions marketplace

### ISSUE THREAD

**Issue by ahmedalnouby132** [microsoft/vscode#78987]
- VSCode Version: 1.37.0
- OS Version: Win10 x64

Steps to Reproduce:

1.Launch VS Code.
2.Press CTRL+SHIFT+X to and choose a popular Extension like Python.
3.Try to download it.

Result:
no photo for the Extension logo and no README available.
and failed to install it.
![2019-08-12 (3)](https://user-images.githubusercontent.com/42790189/62896701-de3c3880-bd51-11e9-89b2-934717f93a82.png)
using the developer tool to debug what happens when I install Extension, I found this:
![2019-08-12 (5)](https://user-images.githubusercontent.com/42790189/62899101-5e18d180-bd57-11e9-8c43-9fb2fa6b8c74.png)

Expected:
To see a logo and description for the Extension, and install normally.

**Comment by gjsjohnmurray** [comment]
See #78783 for info about how others have tracked this down to a DNS issue.

**Comment by ahmedalnouby132** [comment]
@gjsjohnmurray  thanks man
