### ISSUE TITLE
Command Palette background color incorrectly uses Sidebar background color

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#78989]
There are VSCode theme coloring issues caused by Command Palette using the Sidebar's background color instead of its own background color.  For example, VSCode themes that use a dark sidebar background color that also have "light" uiTheme (for contrast).  This scenrio will cause some text to be unreadible in the Command Palette like below screenshot.

Anyway, there isn't any good reason to have the Command Palette share the Sidebar's background color.

![vscode](https://user-images.githubusercontent.com/811008/62899766-56343f80-bd0d-11e9-8fd9-02e4896c7dec.png)

**Comment by mkanet** [comment]
This seems to be a duplicate issue to [#77712](https://github.com/microsoft/vscode/issues/77712).  However, #77712 looks like it's been ignored/overlooked due to it having an incorrect title.  That issue has been stuck in **needs more info** state for over 22 days because of this.

**Comment by ArturoDent** [comment]
Command Palette backgroundColor:

`"quickInput.background": "#b61c1c",`

**Comment by mkanet** [comment]
Thanks ArturoDent!  I think that's so odd that it works like that.  I'm just glad that I have that setting available to me!  I'm going to close this case.
