### ISSUE TITLE
Remove bug adding a closing parenthesis/bracket/etc. when it is typed and next character is that type of parenthesis/bracket/etc.

### ISSUE THREAD

**Issue by adrianme213** [microsoft/vscode#78988]
Issue Type: <b>Bug</b>

Prior to the latest update, I could open a new pair of parentheses, type inside, and then hit the closing parenthesis when I was finished and I would "jump over" the closing parenthesis. With this update, I add another closing bracket instead.

Steps to recreate:
1) In editor, create a function.
2) Type a parameter inside the function parentheses
3) Type a closing parenthesis

At this point, two closing parentheses should exist whereas before this last update this did not happen.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.2.0

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.4.0
gitlens|eam|9.9.3
beautify|Hoo|1.5.0
atom-keybindings|ms-|3.0.6

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Can you reproduce this with all your extensions disabled? There was a change in this area in 1.37, trying to make VS Code do a better job. I guess it's possible one of your extensions is interacting badly with that change.

**Comment by adrianme213** [comment]
Hi @gjsjohnmurray - I disabled all extensions and the error was still reproduced.

**Comment by gjsjohnmurray** [comment]
@adrianme213 can you post a screen recording? Even better if you first issue the `Developer: Toggle Screencast Mode` command so it shows your exact keystrokes.

**Comment by gjsjohnmurray** [comment]
Also see #78902, of which this may be a duplicate.

**Comment by alexandrudima** [comment]
@adrianme213

What programming language are you using? Here I am trying what you describe in JavaScript and the closing `)` gets overtyped for me.

![auto-closing-3](https://user-images.githubusercontent.com/5047891/62929144-255e1400-bdba-11e9-97f4-5825df32b154.gif)

As @gjsjohnmurray mentions, we have made some changes to the overtyping in 1.38 (mainly to make the editor overtype only those characters inserted automatically and not others) and I would like to find out if you are hitting some corner case or if you would simply want the old behavior.

**Comment by adrianme213** [comment]
@alexandrudima @gjsjohnmurray 
Using JavaScript as well. I referenced the other issue and the problems I'm having are related to @alexandrudima's two examples - when you leave the (...) area. If my memory is right, I believe this used to work in the past even when leaving the (...) area.

![overtypedAfterExitingParentheses](https://user-images.githubusercontent.com/31184163/62958178-07d57e00-bdab-11e9-8476-c7d94c38c425.gif)

**Comment by adrianme213** [comment]
@alexandrudima @gjsjohnmurray 
Using JavaScript as well. I referenced the other issue and the problems I'm having are related to @alexandrudima's two examples - when you leave the (...) area. If my memory is right, I believe this used to work in the past even when leaving the (...) area.

![overtypedAfterExitParens](https://user-images.githubusercontent.com/31184163/62958734-31db7000-bdac-11e9-86eb-5f833964ac12.gif)

**Comment by gjsjohnmurray** [comment]
@adrianme213 thanks for the recording. AFAIK what you're seeing is the expected new 1.37 behaviour. It fixes the issue described by the OP of #37315.

Other than muscle memory, any reason why you type the closing paren after inserting the third parameter?

**Comment by adrianme213** [comment]
@gjsjohnmurray - thanks for the update and the reference. I identify with the [#37315](https://github.com/microsoft/vscode/issues/37315) people vocalizing about muscle memory and speed, but understand the new behavior and why it makes sense given autoclosing bracket inserts. Thank you again.
