### ISSUE TITLE
Right alt key does not work in terminal

### ISSUE THREAD

**Issue by hladik-dan** [Microsoft/vscode#7899]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Pro (Build 1511)

Right Alt key does not work in integrated terminal. Ctrl + Alt works fine.

Steps to Reproduce: 

1. Set Czech QWERTZ keyboard layout in Windows
2. Toggle integrated terminal in VSCode
2. Right Alt + Q (should produce \\)

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7061
