### ISSUE TITLE
folder empty and the folder check grayed out

### ISSUE THREAD

**Issue by liqisuccess** [microsoft/vscode#78993]
The project folder shows empty from the left explorer sidebar, and if I right click on it, it shows the Folders option checked and grayed out as in the following image
![image](https://user-images.githubusercontent.com/22110635/62906289-eaf56800-bd22-11e9-9e3a-6d313b909877.png)

**Comment by gjsjohnmurray** [comment]
In Explorer view the Folders section is always shown. It cannot be turned off.

It is empty until you open a folder.
