### ISSUE TITLE
any extenion faield

### ISSUE THREAD

**Issue by elshmakh** [microsoft/vscode#79003]
Issue Type: <b>Bug</b>

i donot install any extension from market place

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
See #78783 for info about how others have tracked this down to a DNS issue.
