### ISSUE TITLE
Change tags are too close to fold Tags

### ISSUE THREAD

**Issue by lky5230** [microsoft/vscode#79001]
![微信截图_20190813095426](https://user-images.githubusercontent.com/21300963/62909844-d2cc2a00-bdb0-11e9-932c-eea700e03e99.png)

**Comment by joaomoreno** [comment]
Yeah... this isn't customisable for now, unfortunately. Since there's a couple workarounds (zoom, keybindings), I'll just close this as won't fix. Sorry!
