### ISSUE TITLE
Inconsistent spacing between breadcrumbs navigation and its dropdown

### ISSUE THREAD

**Issue by huyenltnguyen** [microsoft/vscode#79005]
- VSCode Version: 1.37.0
- OS Version: macOS Mojave 10.14.6

**Steps to Reproduce:**
1. Open any file
2. Check the spacing between icon and text in the breadcrumbs navigation, and compare with its dropdown

**Does this issue occur when all extensions are disabled?**
Yes

**Screenshot**

<img width="254" alt="Screen Shot 2019-08-13 at 11 14 48 AM" src="https://user-images.githubusercontent.com/25715018/62915076-42481680-bdbd-11e9-91ed-e129a6767df6.png">

**Comment by mbelsky** [comment]
Hey,
I'm working on that issue.

**Comment by jrieken** [comment]
👏 thanks to @mbelsky
