### ISSUE TITLE
Clean up recently opened items

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#79019]
Issue Type: <b>Feature Request</b>

There's a command in VS Code to _clear_ recently opened items, but I wish there was a way to _clean_ it. I.e. remove references to files and folders/projects that no longer exists, but keep the rest.

It's for example annoying to still see folders I opened several weeks ago, that no longer exists on my disk. I think VS Code should clean this up automatically, but if not, there would at least be great with command I could run to do it.

**VS Code version:** Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
**OS version:** Windows_NT x64 10.0.17134

**Comment by pramit-marattha** [comment]
Hit `ctrl + shift +p`
Type `Remove from history`
`Hit enter `
clean it up

**Comment by Svish** [comment]
@pramit-marattha Um...
1. That only seem to cover _files_
2. Doing that for _every_ file and project that no longer exists would be very finicky and annoying
3. This was not a question...

**Comment by usernamehw** [comment]
Possible duplicate of #49056
