### ISSUE TITLE
Default character set encoding in replace dialog

### ISSUE THREAD

**Issue by fidomax** [microsoft/vscode#79012]
Search and replace in files dialog ignore "workspace" default encoding settings. It uses "user" default encoding settings.

**Comment by roblourens** [comment]
Can you explain exactly what you are seeing? I don't understand.

**Comment by fidomax** [comment]
Preferences->Settings->Text Editor->Files->Encoding
In User settings I set 'utf8'.
In Workspace settings I set 'windows1251'.
Now I can properly open files from workspace with this Cyrillic charset.
But when I use 'Replace' in files (Ctrl+Shift+F) file, this tool open, replace and save files using utf8 encoding (from User settings)

**Comment by sandy081** [comment]
Replace uses `IBulkEditorService`. @jrieken Does this ignores the file encoding from workspace while replacing?

**Comment by jrieken** [comment]
No clue. It uses our standard [`createModelReference`](https://github.com/microsoft/vscode/blob/6f998109d8ff8ba2bef074eea1b5986a9443316e/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L184)-function which open a `Uri` to a model, no mentioned of encodings and such. Next stop @bpasero

**Comment by bpasero** [comment]
> Does this ignores the file encoding from workspace while replacing?

Wait, search/replace operates on models right? And they are always in UTF-8, no matter how the encoding is configured. But then you trigger a save of the model and yes - that goes through the same path as the user saving a file.

**Comment by sandy081** [comment]
@bpasero ok. So does that mean is this expected or if not where is the issue?

**Comment by bpasero** [comment]
@sandy081 I would say unexpected, depending on how the search service runs the replace operation. If the search service replaces using raw file service without looking at the encoding, then I would think this is expected, though arguably a bug in behaviour.  Can you try to reproduce?

**Comment by sandy081** [comment]
@fidomax I tried following steps and cannot repro

- Created a sample file with following text
`АБВГДЕЅ abcdef`
- Set file encoding to `utf8` in user settings and `windows1251` in workspace settings
- Did Search and Replace in this file and did not see any change in encoding of the file.

May I know how did you come to know that file encoding has changed?
