### ISSUE TITLE
Could not establish to remote after updating win10 to 10.0.18362

### ISSUE THREAD

**Issue by pcshih** [microsoft/vscode#79013]
- VSCode-insider Version: 1.38.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18362
- Remote - SSH: 0.45.4

Steps to Reproduce:

1.  clicking the Connect to Host in New Window button(before update to win10 10.0.18362, it will open new window and connect well)
2. get the issues below
it will pop up a cmd(did not pop before updating win10)
![cmd](https://user-images.githubusercontent.com/48461528/62922399-dfb34280-bddd-11e9-88fa-3ca1d00a3171.PNG)
![vscode output](https://user-images.githubusercontent.com/48461528/62922415-e641ba00-bddd-11e9-890b-90f689f71e68.PNG)

Thank you very much.

![error window](https://user-images.githubusercontent.com/48461528/62928325-ebf1cc80-bdea-11e9-87a9-5427b6c9afbc.PNG)

**Comment by roblourens** [comment]
What happens if you run an ssh command in a normal command prompt?

What happens if you set `"remote.SSH.showLoginTerminal": true`?

**Comment by pcshih** [comment]
> What happens if you run an ssh command in a normal command prompt?
> 
> What happens if you set `"remote.SSH.showLoginTerminal": true`?

(1) It can login as usual. I use public key.
![ssh](https://user-images.githubusercontent.com/48461528/62987236-58afaa00-be71-11e9-9ba0-6e0378a381e7.PNG)

(2) The same problem as first post...
![showLoginTerminal](https://user-images.githubusercontent.com/48461528/62987244-5fd6b800-be71-11e9-94b6-0d7a1d04f8f9.PNG)

**Comment by roblourens** [comment]
When you use that setting, does anything show up in the terminal? I don't understand why it's launching a new terminal.

**Comment by pcshih** [comment]
@roblourens 
No, it does not show anything in the terminal.
I don't understand either...(it does not launch a new command prompt before updating w10)

**Comment by roblourens** [comment]
Any idea @Tyriar?

**Comment by Tyriar** [comment]
Turn off legacy console mode in cmd.exe's properties

See https://github.com/microsoft/vscode/issues/73790
