### ISSUE TITLE
Please update the problems windows as the build is ongoing

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode#79016]
The 'problems' outputpane is now only updated at the end of a build, and the output windows is not 'clickable'.

This means that if I see a warning occur, I have to start searching manually for the corresponding line of code, instead of just clicking on it to navigate to the offending line.

Alternatively, I could wait until the end of the build, go to the problems windows, navigate from there, fix the problem, only to re-start the build.

Proposal: update the problems window 'live' as the build is ongoing instead of at the end.

**Comment by sandy081** [comment]
What build do you mean? Is it a build ran by extension or task?

**Comment by janwilmans** [comment]
I think its the cmake-extension doing the building in this case, but does that matter ? couldn't filenames that occur in the output window be clickable? or would that be another extension?

**Comment by sandy081** [comment]
Yes, I would think so, because its the extension that has to generate the problems. 

Files in output panel should be clickable given that they are valid links. Please file an issue against cmake-extension.
