### ISSUE TITLE
Debug option appearing in Japanese

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#79021]
Issue Type: <b>Bug</b>

getting debug tab option appearing in japnese

VS Code version: Code - Insiders 1.38.0-insider (ffa22b268f451b5211abbe2d2a47e6b753b55b1a, 2019-08-13T07:27:53.993Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (2.11GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.67.4
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.3
vscode-remote-extensionpack|ms-|0.16.0
debugger-for-chrome|msj|4.11.7
ng-template|Ang|0.801.1
jshint|dba|0.10.21
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
python|ms-|2019.8.29288
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.657
vsliveshare-audio|ms-|0.1.60
fabric8-analytics|red|0.0.12
vscodeintellicode|Vis|1.1.9

</details>

![vscode](https://user-images.githubusercontent.com/9264813/62929359-f787c800-bdd7-11e9-986e-22ee6af5be92.png)

**Comment by isidorn** [comment]
@sanket-bhalerao What exact debugger are you using? Can you please include a picture?
@weinand you mentioned some breakage of nls for node debug? However I doubt you broke it such that everything is japnesse?

**Comment by sanket-bhalerao** [comment]
Its chrome debugger.
Can you specify if this is what you arr looking for? Or please mention what else is needed

**Comment by isidorn** [comment]
@roblourens can provide more details.
@sanket-bhalerao so everything in vscode is in english, just the strings coming from the debugger are japanesse? And you never configured anything related to japanese?

**Comment by sanket-bhalerao** [comment]
@isidorn everything else is in English. the debug messages are in Japanese.
I am making an assumption that it's Japanese. I know its not English for sure.
![vscode japanese debug](https://user-images.githubusercontent.com/9264813/63408394-916cf780-c40c-11e9-8896-467a3a96f72c.png)

**Comment by isidorn** [comment]
This message is not from the debug adapter but from vscode. Unassigning @roblourens and assinging to @dbaeumer to comment how parts of vscode can be in a different language

**Comment by dbaeumer** [comment]
Two possible reasons:

- the LP is somehow broken (it contains the Japanese strings).

Or

- an extension having its own file based translations (not a LP)
- the OS is Japanese
- and the VS COde language is not set to English.

Without steps however this is very hard to tell.

@isidorn where is the strings defined?

**Comment by isidorn** [comment]
@sanket-bhalerao can you please share your `launch.json`?
Thanks

**Comment by sanket-bhalerao** [comment]
@isidorn launch.json is the default config for chrome. launch and attach.
nothing else.

**Comment by weinand** [comment]
@sanket-bhalerao and which of the two launch configs results in the error?

Can you reproduce the problem when disabling all but the Chrome extension ('debugger-for-chrome')?

**Comment by isidorn** [comment]
@roblourens can you check if there are some misplaced japenesse strings in the english translation file in the Chrome extension (you can search for `10000` as that seems to be a part of the message)?

**Comment by roblourens** [comment]
It's not due to a misplaced string. I see that string in the jpn loc bundle and nowhere else.
