### ISSUE TITLE
Grid: enabling grid after running without grid buts sidebar width very large

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79020]
Steps to Reproduce:

1. run from a fresh user data dir without grid layout enabled (e.g. using stable)
2. run over same user data dir out of master

=> 🐛 the sidebar width is half the window width

![image](https://user-images.githubusercontent.com/900690/62928194-5a696700-bdb8-11e9-8b4e-612b5ba20d12.png)

I think to offer a smooth transition, we need to find a way to migrate the sizes for the old layout to the grid layout.

**Comment by sbatten** [comment]
To verify:
1) Start with a clean install from 1.37 insiders.
 [Windows (User)](https://az764295.vo.msecnd.net/insider/5e08ee01b7daee99cdda2456f19d77e715fb8762/VSCodeUserSetup-x64-1.37.0-insider.exe)
 [macOS](https://az764295.vo.msecnd.net/insider/5e08ee01b7daee99cdda2456f19d77e715fb8762/VSCode-darwin-insider.zip)
[Linux (deb)](https://az764295.vo.msecnd.net/insider/5e08ee01b7daee99cdda2456f19d77e715fb8762/code-insiders_1.37.0-1565040850_amd64.deb)

2) Before the update triggers, open a folder.
3) Set the panel and sidebar to some unique sizes, this will populate the old keys.
4) Restart to allow the update to occur. Verify that when the workspace opens, the workbench parts are sized the same.
