### ISSUE TITLE
Cannot bind focusNext, focusPrevious terminal actions

### ISSUE THREAD

**Issue by mnowotnik** [microsoft/vscode#79023]
- VSCode Version: 1.37
- OS Version: Linux Mint 19 Tara

Steps to Reproduce:

1.  Add to keybindings.json :
```
[
 { "key": "ctrl+shift+j", "command": "workbench.action.terminal.focusNext" },
  { "key": "ctrl+shift+k", "command": "workbench.action.terminal.focusPrevious" },
]
```
2. Open integrated vscode terminal
3. Split terminal
4. Try to use defined keybindings to move to next or previous terminal pane

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Split terminals use `workbench.action.terminal.focusNextPane` and `workbench.action.terminal.focusPreviousPane`, focusNext and focusPrevious move between items in the dropdown.
