### ISSUE TITLE
Starting with HDR on makes editor washed out

### ISSUE THREAD

**Issue by SamMurphy** [microsoft/vscode#79022]
Issue Type: <b>Bug</b>

Noticed on the latest update, if I start VS Code with HDR turned on in display settings on my second monitor. The application appears washed out (very white) turning HDR off and restarting the application fixes this issue.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-rust|kal|0.4.2
remote-wsl|ms-|0.39.2
cpptools|ms-|0.24.1
shader|sle|1.1.4

</details>

**Comment by gjsjohnmurray** [comment]
What version were you on before you went to 1.37?

https://github.com/microsoft/vscode/issues/65816#issuecomment-509701858 is from someone who saw a similar-sounding issue appear in 1.36.

Further down that thread is a suggestion to try the Exploration build.

**Comment by SamMurphy** [comment]
Tested the exploration build, and it works correctly in HDR.

Issue looks the same as #76604 from the screenshots.
