### ISSUE TITLE
Focus and scroll issues with built-in terminal window

### ISSUE THREAD

**Issue by martypdx** [Microsoft/vscode#7902]
- VSCode Version: 1.2.1
- OS Version: OSX 10.11.4

Steps to Reproduce:

Focus issue:

1. Open the terminal window
2. Run a command
3. Click or select some text in the window above
4. Try and type, it doesn't do anything
5. Click or select a second time and the text will respond as expected

Scroll issue

1. Have enough output in the terminal window that causes it to scroll
2. Scroll to the top of that terminal window
3. Try and and scroll down, it's locked up.
4. hit up or down arrows and focus will jump back to input and scroll will work again

**Comment by Tyriar** [comment]
Both are already fixed in v1.3.0, you can try it out in the [insiders build](https://code.visualstudio.com/insiders).

**Comment by isidorn** [comment]
Focus issue works fine, scroll issue - I have hit a related issue which I have caputred in https://github.com/Microsoft/vscode/issues/11439
