### ISSUE TITLE
Holding Ctrl+PgUp/PgDown stalls the window

### ISSUE THREAD

**Issue by Ardeshir81** [microsoft/vscode#79028]
Issue Type: <b>Bug</b>

Using Ctrl+PgUp/PgDown moves my active tab to right/left.
But when I hold (instead of just press) Ctrl+PgUp/PgDown, window stalls, and after a few seconds, it unfreezes.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.0.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 2441)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.75GB (2.27GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
svn-scm|joh|1.54.4
camelcasenavigation|map|1.0.1
python|ms-|2019.8.29288
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.24.1
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
vscode-extjs|Sen|1.0.1
vscode-scss-formatter|sib|1.4.1
vscode-icons|vsc|9.2.0

</details>

**Comment by bpasero** [comment]
Well, that will invoke the action possibly hundreds of times depending on how fast key events are delivered. I am sure you can reproduce issues like this with a lot of applications that support keyboard input. What is your suggestion here?

**Comment by Ardeshir81** [comment]
@bpasero 
as the issue is closed, I believe it is not necessary anymore for discussion.
But I would suggest a little (configurable) debounce is necessary. I'd suggest 100ms.

But as you mentioned, lots of programs may have this issue, and if any have, I would raise an issue there too :)

But I disagree. For example WebStorm does not have this issue. If I hold down `Alt + Right/Left Arrow` in WebStorm (or probably any JetBrains product) it does repeatedly traverses my tabs without freezing (probably a debounce is used). (on the same machine)

Or another example:
I remember I used to hold down `Ctrl + T` in Google Chrome and it repeatedly opened new tabs. It eventually used to freeze though, but in newer versions of Google Chrome, If I hold down `Ctrl + T` only one tab will be opened and other events would be ignored.

(I still like the debounce approach more)

Thanks though :+1: 

P.S.
I read through the issue, that, this issue is marked as a duplicate of, and to be honest, there were some advanced stuff :)
And I couldn't really find out how is my issue related :)
just a thought to share :+1:
