### ISSUE TITLE
Grid: SCM input box does not extend its height for the placeholder text

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79029]
When the input box is empty, there's a placeholder text. The inputbox should grow in size when the placeholder text wraps.

![image](https://user-images.githubusercontent.com/900690/62933741-2fd0db80-bdc3-11e9-940a-87b36d92944a.png)

**Comment by sbatten** [comment]
no difference between grid and legacy layout for me

**Comment by joaomoreno** [comment]
The placeholder text doesn't wrap. If you write text in it, it does wrap.
