### ISSUE TITLE
Git interface needs improvements (rebase, commit msg, git add -p)

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#79027]
When working on open-source projects that are based around creating patches, it is often necessary to carefully split changes into multiple commits, edit a commit in series, or do other stuff that requires working closely with git. VSCode does not provide nearly enough interface around Git to fit into that use case.

First of all, there needs to be an editor around interactive rebase, merging conflicting changes, rewording/melding/dropping commits in a series etc. For setting up the rebase, it is already possible to set a system editor for Git, but this is not a good solution when using VSCode to edit a remote codebase (with Remote SSH extension). There is also currently no interface to do rebase with good (non manual) handling of merge conflicts. [This](https://github.com/microsoft/vscode/issues/31153) seems to be going in the right direction, but i'd like to stress the importance of having good tooling around Git - power users such as myself rely on lots of more advanced features of git in our day-to-day work.

Similarly, commit message handling is inadequate. Many open source projects (such as one i'm working on) require lots of detail in the commit message - detailed (and well-formatted) description of the change signoffs, acks, fix tags, etc., and VSCode doesn't help matters here by only providing a single-line editing interface.

It's possible to create commit messages with current interface (including multiline ones), but it suffers from the following problems:

- it's tucked away in some corner, instead of being front and center in a proper editor
- amending commit loses multi-line information and forces the commit to be single-line, at least on my setup (Remote SSH extension)
- there aren't any visual guides on line length and no feedback on how the commit message will actually look like when committed

Getting a proper textual editing of commit message would go a long way (again - possible to set up VSCode as an editor, but not an option over SSH).

Finally, adding interface around `git add -p` and friends would be great as well. (there was a discussion about this, but it is locked now)

It is already possible to stage separate hunks (albeit the feature is not easily discoverable - this should be fixed), but this is not all there is to it for `git add -p`. For the open source projects i'm involved with, i have to routinely stage multiple changes and (more importantly) editing them (see `e` shortcut for `git add -p`).

The good thing about editing before staging is that it doesn't modify files in the workspace - just what is going to be staged. This is crucial for things like splitting changes into multiple commits and creating stubs in place of actual code (for the purposes of adding real code in later commits). There is currently no interface in VSCode Git integration to do this either.

Having all of this would go a long way towards stopping me from relying on manual git interaction and finally switch to VSCode to do everything :)

**Comment by joaomoreno** [comment]
> File a single issue per problem and feature request.

> * Do not enumerate multiple bugs or feature requests in the same issue.
> * Do not add your issue as a comment to an existing issue unless it's for the identical input. Many issues look similar, but have different causes.

https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

---

Thanks for the report. But a large issue like this is unlikely to ever be closed. Try to narrow down the features you'd like to see fixed, then search for them in our issue database and upvote if exiting or create a new issue otherwise.
