### ISSUE TITLE
Very high battery consumption on Mac

### ISSUE THREAD

**Issue by pravesh-curefit** [microsoft/vscode#79026]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.37.0
2. macOS 10.14.6

Does this issue occur when all extensions are disabled?: Yes

Seeing very high battery consumption at times. Don't notice any other change in behaviour when this happens.
<img width="446" alt="Screenshot 2019-08-13 at 2 51 18 PM" src="https://user-images.githubusercontent.com/33955423/62932201-526fee00-bddd-11e9-9e2f-69a9b8ad2225.png">

**Comment by pchodak** [comment]
After update I got ~10% more usage of CPU on windows 10.

**Comment by deepak1556** [comment]
@pravesh-curefit @pchodak can you try our exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 and see if its any better. Thanks!
