### ISSUE TITLE
Breakpoints are not hit in Launch Extension

### ISSUE THREAD

**Issue by Swapnil2107** [microsoft/vscode#79030]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Put breakpoints in flow
2.Launch extension

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Using 1.37 with https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample I am able to set a breakpoint at line 10 of src/extension.ts and execution stops here after I launch the Run Extension debug config and invoke the `Hello World` command in the Extension Development Host window that appears.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks a lot for your help I really appreciate it

**Comment by isidorn** [comment]
Data not provided -> closing this issue.
