### ISSUE TITLE
SCM: Repositories panel doesn't show on new workspaces with multiple repositories

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#79037]
Caused by fix of https://github.com/microsoft/vscode/issues/78724

**Comment by joaomoreno** [comment]
@sandy081 This is impossible for me to fix at the SCM Viewlet layer without having a tri-result for `isVisible()`: `true | false | undefined`, in which `undefined` means that the user did not yet explicitly made the view visible/invisible.

Pushing a workaround for now.

**Comment by joaomoreno** [comment]
Verification:

1. Open new Window
2. Add a folder with a git repo
2. Add another folder with a git repo
3. The SCM Providers view should show up

**Comment by sandy081** [comment]
Not sure why it is. Will catch up with you directly.

**Comment by RMacfarlane** [comment]
I still see this in the most recent insiders

**Comment by bpasero** [comment]
@joaomoreno this works for me when I start with an empty workspace, then add one folder after the other. However in this case it does not work:
* start empty
* instead of opening a folder, open just a file from a repo with git
* do this again for a file in another git repo

=> both repos show up but the repositories view does not.

**Comment by joaomoreno** [comment]
@bpasero Yup, I knew that wouldn't work. I can't fix that unless @sandy081 gives me info about whether a view is `visible | invisible | undefined`, in which `undefined` means the user never explicitly chose a visibility state.

**Comment by joaomoreno** [comment]
@sandy081 has a good suggestion: make the main panel be conditionally visible based on a `when` context instead of programmatically.

**Comment by joaomoreno** [comment]
@sandy081 That was an awesome suggestion, many thanks! Everything is simplified and seems to work much better. :pray:
