### ISSUE TITLE
Text in tables in the marketplace is bigger than normal

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#79036]
I use a markdown table to show the settings for my extension in the marketplace. For some reason the text in the table is rendered larger than the normal text.

**Comment by sandy081** [comment]
Is it in Marketplace or in VS Code?

**Comment by Gruntfuggly** [comment]
In the marketplace - vscode renders it fine in the markdown preview.
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree (configuration section).

I realise the marketplace is probably not really controlled by this project, but I don't know where else to raise the issue?

**Comment by Gruntfuggly** [comment]
Actually - it looks like it is only Chrome based browsers?

**Comment by sandy081** [comment]
Its an issue with Marketplace and nothing can be done in VS Code. Mentioning @kesane-msft from Marketplace team.

**Comment by kesane-msft** [comment]
Thanks @Gruntfuggly for reporting the issue. I am from the Marketplace team. I have created a bug tracking this issue at our end.
