### ISSUE TITLE
Option to invert terminal search direction

### ISSUE THREAD

**Issue by SpectralKH** [microsoft/vscode#79039]
In VSCode 1.37, searching in the terminal was changed so that pressing enter searches backwards in the terminal. I could not find an option to change it back, or a way to override it using keyboard shortcuts, so here's a feature request for it.

**Comment by Tyriar** [comment]
@rebornix did you say you were going to add commands for these?

**Comment by rebornix** [comment]
yes, I was thinking about adding following things to allow users to decide what keybindings to use

* context keys for find input box
* commands for navigating through history in the input box 

It may come together with https://github.com/microsoft/vscode/issues/15727 and if the solution is simple, I'll make it generic.

**Comment by rebornix** [comment]
One thing I'm not sure about yet is whether we should have dedicated context keys for editor find, terminal find and Webviews, or we should only have a generic one and uses can use other context keys like `editorFocus` to differentiate active components.

**Comment by Tyriar** [comment]
@rebornix the terminal already has separate context keys and it's default behavior needs to be inverted.

**Comment by rebornix** [comment]
Fixed in master. With next Insiders, you should be able to revert the keybindings by adding following into your keybindings.json

```
{
        "key": "shift+enter",
        "command": "workbench.action.terminal.findPrevious",
        "when": "terminalFindWidgetFocused"
    },
    {
        "key": "enter",
        "command": "-workbench.action.terminal.findPrevious",
        "when": "terminalFindWidgetFocused"
    },
    {
        "key": "enter",
        "command": "workbench.action.terminal.findNext",
        "when": "terminalFindWidgetFocused"
    },
    {
        "key": "shift+enter",
        "command": "-workbench.action.terminal.findNext",
        "when": "terminalFindWidgetFocused"
    }
```

**Comment by Tyriar** [comment]
@rebornix enter and shift+enter doesn't seem to work in the terminal find widget anymore?

**Comment by rebornix** [comment]
![shift-enter](https://user-images.githubusercontent.com/876920/63479092-81233f80-c441-11e9-9576-f732ffc65cea.gif)

Above gif is recored in latest master, are you testing against that?

**Comment by rebornix** [comment]
Good catch actually, the keybinding was added on Windows and Linux.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/commit/08d59c432609ae9306eb3889815977e93bb548de

**Comment by Tyriar** [comment]
We should verify these keybindings on all platforms just in case.
