### ISSUE TITLE
User settings.json can't be formatted in v1.37

### ISSUE THREAD

**Issue by wenfangcn** [microsoft/vscode#79038]
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. add ` "workbench.settings.editor": "json", "workbench.settings.useSplitJSON": true` to User settings.json
2. indent a line in settings.json
3. use prettier to format settings.json
4. vscode warns in the status bar
![image](https://user-images.githubusercontent.com/28700378/62947930-fffef380-be15-11e9-89bc-347ba4efe46f.png)

It's not the case in v1.36.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I am not fixing issues with the deprecated split JSON editor. The extension authors might look into it though.

**Comment by wenfangcn** [comment]
Actually, it seems having nothing to do with the split JSON editor. I tried to use the UI editor and click the Open Settings(JSON) at the top right corner, do some indentations and format it using prettier, and it still warns me:
![image](https://user-images.githubusercontent.com/28700378/62984841-46307300-be67-11e9-8058-b61d70e300e0.png)
Other JSON files are formatted normally as before, only the settings.json is not.

**Comment by roblourens** [comment]
Is it because you have comments in it which makes it not well-formed JSON?

**Comment by wenfangcn** [comment]
@roblourens No, it doesn't have any comments, although the language mode shows "JSON with comments".  Other jsonc files can be formatted as normal. Again, _formatting is only not working if I open settings.json through vscode settings commands._

**Comment by bryanjhv** [comment]
Could anyone please reopen this? Maybe someone who knows how to read and understand issues.

Just to be clear:
- It's **not** about split editor.
- It happens **only** with user **settings.json**.
- It's **not** specific to **Prettier** (tested others).
- It happens with **any** JSON-capable **formatter**.
- It **started** happening on VSCode **1.37.0** (remains in 1.37.1).

It's known that Microsoft software tends to contain regression bugs.
Also it's know that Microsoft employees don't know how to read/test something simple.

**Comment by roblourens** [comment]
I still can't reproduce it, trying different formatters. Maybe someone can share their settings file that can't be formatted. But I think an extension author who can repro it could investigate faster than I can.

**Comment by bryanjhv** [comment]
It's strange that after upgrading to `esbenp.prettier-vscode@2.2.1` and deleting the `~/.config/Code` folder (keeping `User` folder) fixed it and now works without a warning. I also tested with `HookyQR.beautify` before and it didn't work, but after clearing the profile folder it worked as it was on `1.36.1`.

Maybe there was some big changes in `1.37.0+` that made then fail without deleting the folders.

**Comment by uloco** [comment]
Funny thing is, that you can format the file normally if you open it directly and not via `open file` and not with `open settings` (<kbd>command</kbd>+<kbd>;</kbd> on mac)

**Comment by roblourens** [comment]
So you can no longer reproduce it @bryanjhv?

@uloco can you share your settings file and what extensions you are using?

**Comment by uloco** [comment]
It is really as easy as opening insiders or latest code version and installing only prettier and adding the default formatter to settings.json. 
Like described here https://github.com/prettier/prettier-vscode/issues/911

**Comment by roblourens** [comment]
Still not seeing it.

![Aug-29-2019 14-42-15](https://user-images.githubusercontent.com/323878/63978459-3d48bf80-ca6b-11e9-88ca-37cac07775ef.gif)

Same results going to the settings GUI and clicking the "open settings (json)" button.

**Comment by bryanjhv** [comment]
@roblourens no, it doesn't happen anymore.

At this point it's hard to tell what did really happen, because when I updated from 1.36.1 to 1.37.0 and 1.37.1 there was no update for Prettier extension, but whithout that update the problem manifested itself when upgraded to 1.37.0. Then, recently there have been a lot of updates to that extension, so maybe it's the extension or the IDE. The only thing I know as of now is that even after updating the extension, the problem remained and only went away after I cleared my `~/.config/Code` dir (and restored my saved settings).

**Comment by bryanjhv** [comment]
I have new findings. The "solution" to my problem (or the reason why it didn't reproduce in my other tests) was to close all folders.

In short: (for me) **formatting `settings.json` doesn't work if a folder is open.**

**Comment by roblourens** [comment]
Ok that's a good hint. Now I can repro but it still seems like a prettier issue. Prettier is not registered for this file type. It seems like it might have something to do with the fact that the settings file is not in a workspace, or that it doesn't have a local prettier installed next to it. They will have to investigate.

**Comment by bryanjhv** [comment]
I don't think it's a Prettier issue because it works with `jsonc` files normally (also if you try with `HookyQR.beautify` which also supports `jsonc`, the same thing happens). Curious thing is that, if you try with the same plugin versions and VSCode `1.36.1` or `1.36.0` it works as expected, so it's likely not a plugin issue but something that was introduced in `1.37.0`. Also, as others have pointed out, it works normally if you open the files via `File > Open file` so it's clear it's not a plugin issue.

**Comment by roblourens** [comment]
I didn't realize there is a `vscode-userdata` scheme for some files, and the formatter is not registered for that, @sandy081?

**Comment by sandy081** [comment]
User data configuration files are using `vscode-userdata` scheme from 1.37.0 but it is still using `jsonc` language. Can prettier extension use language instead of scheme for document selector and formatting?

**Comment by roblourens** [comment]
It uses language + scheme for the `untitled` and `file` schemes. I don't know why that's needed.

**Comment by maxathanja** [comment]
I've just encountered this issue, and it still persists in VSCode `1.38`.

**Comment by sandy081** [comment]
It would be great if `prettier` extension supports it. So please file an issue against `prettier` extension.

**Comment by uloco** [comment]
I already did. See here: https://github.com/prettier/prettier-vscode/issues/911

**Comment by Ivajkin** [comment]
Which folder is open?
