### ISSUE TITLE
python.pythonpath not worked in workspace config

### ISSUE THREAD

**Issue by ExiaHan** [microsoft/vscode#79049]
Issue Type: <b>Bug</b>

I have set python path below, but it didn't work both in remote ssh and my local machine when I open terminal or run my project.. It works well in the previous version.
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"python.pythonPath": "/home/exiahan/.virtualenvs/beagle/bin/python"
	}
}

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.2.6-arch1-1-ARCH
Remote OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 3320)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|15.58GB (0.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: nj-todd-han-03|
|OS|Linux x64 4.15.0-54-generic|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 1596)|
|Memory (System)|15.55GB (3.14GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
dart-code|Dar|3.3.0
code-runner|for|0.9.12
markdown-toc|jof|1.4.0
mdhelper|jos|0.0.11
vscode-emacs-friendly|lfs|0.9.0
vscode-clang|mit|0.2.3
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
Go|ms-|0.11.4
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
vscode-auto-open-markdown-preview|hnw|0.0.4
Kotlin|mat|1.7.0
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
fyi @roblourens @sandy081
