### ISSUE TITLE
tab title is cut off a bit

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#79041]
- VSCode Version: 1.37.0
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Open a `index.html` file with single click (so that title text is in italics)

Does this issue occur when all extensions are disabled?: Yes

![cut-off title](https://user-images.githubusercontent.com/23744935/62949136-f198e380-bde5-11e9-8378-c79e557f9307.png)
The `l` of `index.html` is cut off a bit.

**Comment by bpasero** [comment]
@SimonSiefke what are your tab related settings? looks like you configured tabs to shrink?

**Comment by SimonSiefke** [comment]
Yes, its only happening with:

```json
{
	"workbench.editor.tabSizing": "shrink"
}
```

**Comment by bpasero** [comment]
@SimonSiefke and tab close button off too?

**Comment by SimonSiefke** [comment]
It happens regardless of whether `workbench.editor.tabCloseButton` is `"left"`, `"right"` or `"off"`.
