### ISSUE TITLE
High contrast theme focused item inconsistency in tasks menu when selecting via keyboard

### ISSUE THREAD

**Issue by jimmyff** [microsoft/vscode#79042]
When selecting a task to run (using the keyboard) it does not provide the orange border on the focused item in the list as it should. The only way I know which item I am focused on it the small cog on the right hand side. This makes selecting an items quite difficult. See screenshot of the issue below:

![Screenshot 2019-08-13 at 15 14 57](https://user-images.githubusercontent.com/298850/62949047-6b789f00-bddd-11e9-9ba7-9ee0ce7d4db5.png)
(Note: I'm not sure why the tasks with name 'Core: tests' is highlighted in a solid white line. This is not the focused item)

This is the expected behaviour (orange borders indicate focus):
![Screenshot 2019-08-13 at 15 18 40](https://user-images.githubusercontent.com/298850/62949190-a7136900-bddd-11e9-8d47-b18f64ae388c.png)

**Comment by chrmarti** [comment]
Which version of Code is this?

**Comment by jimmyff** [comment]
Version 1.36.0

**Comment by chrmarti** [comment]
Please try 1.37.0, that has a fix for this.

**Comment by jimmyff** [comment]
Yep, this is fixed in 1.37 thanks
