### ISSUE TITLE
Allow rendering whitespace in the search/replace fields

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode#79046]
Currently whitespace is simply invisible in the search/replace boxes, even if the `editor.renderWhitespace` is turned on. This routinely results in issues e.g. replacing text with whitespace rather than an empty string, or inability to locate a pattern because it includes whitespace at the end, or tabs rather than spaces, etc.

It would be nice to be able to make whitespace visible in find an replace fields, in a way similar to what's shown in the main editor when `editor.renderWhitespace` is on. That would avoid the problems described above.

**Comment by roblourens** [comment]
Not really simple because these are simple input elements but editor features in those would be nice.
