### ISSUE TITLE
Allow configuring language explicitly

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#7905]
- VSCode Version: 1.2.1 (1.2.1)
- OS Version: Mac OS X 10.11.5 (15F34)

Steps to Reproduce:

1. Set Mac OS X to e.g. German locale
2. Start VS Code
3. VS Code is now localized in German, including configuration files

I'd like an option to control localization myself. I like my OS in German, but would strongly prefer to keep all developer tools (like VS Code) in English.

**Comment by dbaeumer** [comment]
F1 > Configure Language.

Put en into that file. This makes VS Code run in an English locale even if your OS is German.

**Comment by mprobst** [comment]
Thanks @dbaeumer. FYI, I looked for this in the regular User Settings (`Cmd-,`) and the `Code > Preferences` menu. Maybe this setting should be exposed somewhere in the UI, so it's a bit more findable?

**Comment by dbaeumer** [comment]
We do have a issue requesting this.
