### ISSUE TITLE
Terminal Freezes

### ISSUE THREAD

**Issue by joelgrodriguez** [microsoft/vscode#79051]
`
Issue Type: <b>Bug</b>

I am running the lates VSCode on PopOS Linux / 2015 MacMini

Everytime I kill a process in the integrated terminal... the terminal freezes and I have to hit the Trash icon and re open. 

I have uninstalled and installed VSCode but it keeps happening. 

It does not happen when I use Hyper or iTerm. Only in the VSCode integrated terminal. 

Still using it but its annoying and wanted to let you know. 

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.0.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 3043)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.67GB (1.34GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.6.0
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.4.0
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
styled-components-snippets|jon|0.4.0
vscode-styled-components|jpo|0.0.26
vscode-gatsby-snippets|nic|1.1.2
html-to-jsx|ria|0.0.1
LiveServer|rit|5.6.1
vscode-todo-highlight|way|1.0.4
city-lights-icon-vsc|Yum|1.1.3
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>
`

**Comment by Tyriar** [comment]
What are you doing to "kill a process"?

**Comment by joelgrodriguez** [comment]
Ctrl + C

**Comment by joelgrodriguez** [comment]
When I try to type in again after pressing Ctrl+ C nothing happens. However if I hit the enter button a bunch of times it will respond after a 10-20 second delay. Perhaps its something on my end? It was working fine when I was using VSCode on my MiniMac (same computer).

**Comment by Tyriar** [comment]
I haven't been able to reproduce this, does this happen every time you ctrl+c or only with certain applications?
