### ISSUE TITLE
Window no longer responding when developing VS Code

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79054]
![image](https://user-images.githubusercontent.com/4033249/62958161-fdb37f80-bdaa-11e9-8376-2da53bb8e49a.png)

Repro:

- Develop on VS Code
- Run "Launch VS Code + Attach to Main Process" compound config
- Hit a breakpoint
- After 30 seconds, this popup shows

**Comment by roblourens** [comment]
Where is the breakpoint, which process?

Can you set `"trace": true` and include the log?

**Comment by roblourens** [comment]
Do you see the same with chrome devtools?
