### ISSUE TITLE
Terminal window highlighting Angular chunking outputs

### ISSUE THREAD

**Issue by alexagranov7** [microsoft/vscode#79057]
- VSCode Version: 1.37.0
- OS Version: Windows 10 1703 Enterprise

Steps to Reproduce:

1. Build Angular application

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/28403336/62960254-250c4b80-bdaf-11e9-95cf-e5030b5954a5.png)

This wasn't happening before I updated to 1.37.

**Comment by alexagranov7** [comment]
Not a duplicate, this is happening only with 1.37. Once the Angular chunks are highlighted the rest of the terminal output continues being highlighted as well.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by alexagranov7** [comment]
For now I fixed my issue by overriding the workbench terminal colors to get exactly the right scheme.
