### ISSUE TITLE
Folding should only be expanded by double-clicking the end

### ISSUE THREAD

**Issue by larryw3i** [microsoft/vscode#79055]
Folding should only be expanded by double-clicking the end, 😭 I often expand it when I click inadvertently       

<img src='https://raw.githubusercontent.com/larryw3i/tomato/master/Screenshot%20from%202019-08-14%2000-08-06.webp'/>

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/53886
