### ISSUE TITLE
 Integrated terminal showing few item

### ISSUE THREAD

**Issue by babul7154** [microsoft/vscode#79069]
Issue Type: <b>Bug</b>

when I type pip list in Integrated terminal to view my installed  python  packages it give output of all my installed packages(everything fine) ,but when I resize the terminal by stretching  the border it show only few Items(only show few installed python packages).And In some case it didn't show last command.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
project-manager|ale|10.6.0
vscode-sqlite|ale|0.8.0
aws-toolkit-vscode|ama|1.0.0
spellright|ban|3.0.46
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|1.9.0
vscode-optimize-images|fab|1.1.0
code-runner|for|0.9.12
vscode-simple-icons|Lau|1.11.9
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.8.29288
vscode-typescript-tslint-plugin|ms-|1.2.2
material-icon-theme|PKi|3.8.1
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.4.1
html5-boilerplate|sid|1.0.3
code-spell-checker|str|1.7.17
ayu|tea|0.18.0
vscode-djaneiro|the|1.4.2
vscodeintellicode|Vis|1.1.9
jinja|who|0.0.8

(6 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).
