### ISSUE TITLE
After moving a file in VS Code using Remote Containers the file is inaccessible everywhere

### ISSUE THREAD

**Issue by alec-joy** [microsoft/vscode#79060]
I have to admit this one is really confusing me. I am using VS Code's remote containers extensions attaching to an already running instance of [Laradock](https://github.com/laradock/laradock). Today I tried to use the File Explorer menu in VS Code to move a file into a sub directory of the same folder. The file move operation appeared to be successful, and the file is listed in the correct folder, but when I open it the file appears empty and I cannot save changes. 

I have also tried opening this file in other text editors (Sublime Text and Notepad) and even sshing into the running container and using Vi. In all cases the behaviour remains the same, I can see the file, it is listed as 10 KB in size so I know there is something in there, but when I try to open the file it's empty and cannot be saved. 

The file permissions for the file are the same as other files in the directory which do not have this issue and are as follows

Edit: after restarting the container the file is just outright gone

-rwxr-xr-x 1 root root 9571 Aug 13 16:58 FileICannotOpen.Vue
-rwxr-xr-x 1 root root 2730 Aug 13 17:06 FileICanOpen.vue

chown, chmod, and all other file operations fail with a "no such file or directory" error. 

As you can see above, the only difference in the files appears to be the extension being capitalized after being moved.  This happened when the file was moved and I believe this to be the source of the problem but I can't seem to do anything to correct it. 

- VSCode Version: 1.37.0
- OS Version: Windows 10.0.18362

Steps to Reproduce:

1. Attach VS code to a running container
2. Move a file to a new directory created in VS Code
3. Attempt to open the file
4. File opens, but is empty and changes cannot be saved
5. Attempt to open the file in another text editor
6. ssh into the container, us ls -l to see the file is there and owned by the root user
7. attempt to open the file in vi as root, file still empty. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alec-joy** [comment]
As an update, when I restarted the containers the file was no longer there at all and is just completely gone. I tried replicating this behavour with another, much less important, file and was not able to. I tried having the file open at the time of the move operation (as I had with the other file) and it made no difference. Appears to be a one off.

**Comment by chrmarti** [comment]
Could be related to the filesystem being backed by the Windows filesystem. Which version of Docker are you using?

**Comment by alec-joy** [comment]
Docker Desktop 2.0.0.3
Docker Engine 18.09.2
Docker Compose 1.23.2
Machine 0.16.1

Using "linux containers" as well, though obviously they're still installed on an NTFS formatted drive.

**Comment by bpasero** [comment]
Probably what you said in https://github.com/microsoft/vscode/issues/79060#issuecomment-521541406

**Comment by chrmarti** [comment]
@alec-joy I'll close this issue for now. Please write down the exact steps you took if this happens again and try to repeat these steps to understand if it always happens or only sometimes and let us know. Thanks!
