### ISSUE TITLE
Python syntax highlighter

### ISSUE THREAD

**Issue by cyficowley** [microsoft/vscode#79066]
Issue Type: <b>Bug</b>

having a hashtag questionmark in a string breaks the rest of that line's syntax highlighting

ex:  matches = re.search("(#?(19|20)\d{2}-\d+)",input_str)

everything after the #? is highlighted blue even after the string ends

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.52GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
aws-toolkit-vscode|ama|1.0.0
path-intellisense|chr|1.4.2
apex-pmd|chu|0.4.4
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.1
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
beautify|Hoo|1.5.0
rainbow-csv|mec|1.2.0
python|ms-|2019.8.29288
remote-ssh|ms-|0.45.4
remote-ssh-edit|ms-|0.45.4
remote-ssh-explorer|ms-|0.45.4
sublime-keybindings|ms-|4.0.3
debugger-for-chrome|msj|4.11.7
java|red|0.47.0
vscode-xml|red|0.8.0
salesforcedx-vscode|sal|46.9.0
salesforcedx-vscode-apex|sal|46.9.0
salesforcedx-vscode-apex-debugger|sal|46.9.0
salesforcedx-vscode-apex-replay-debugger|sal|46.9.0
salesforcedx-vscode-core|sal|46.9.0
salesforcedx-vscode-lightning|sal|46.9.0
salesforcedx-vscode-lwc|sal|46.9.0
salesforcedx-vscode-visualforce|sal|46.9.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1

</details>

**Comment by alexr00** [comment]
Does it repro if you disable all extensions?

**Comment by cyficowley** [comment]
Sorry, It is actually an extension issue.  I'll go put the issue in the right place.
