### ISSUE TITLE
Return of the swipeToNavigate setting

### ISSUE THREAD

**Issue by mmakarios** [microsoft/vscode#79078]
Apparently the swipe event has been fixed in Electron: https://github.com/electron/electron/pull/19319

Can we have this setting again? It was really useful.

Related: https://github.com/microsoft/vscode/issues/57629.

**Comment by alexey-kozlenkov** [comment]
I haven't even noticed when this has broken up (still thinks that on my old mac it's still working), however I noticed on my new machine that I can't enable it.
I'd vote up for having this feature back ❤️

**Comment by bpasero** [comment]
I would accept a solution for this feature that detects the swipe using standard DOM APIs. If someone has ideas for a solution that is not a hack, happy to look at it.

**Comment by walterogrady** [comment]
Would adding simple nav buttons to the main ui be a reliable backup option? They already exist, just in an inconvenient location. Obviously swipe is nicer, but despite swipe support all browsers kept their nav buttons so it's still industry best practice.
