### ISSUE TITLE
No way to apply four slashes //// using shortcut

### ISSUE THREAD

**Issue by wooramy** [Microsoft/vscode#7907]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.3

Description:
I use four slashes //// to differentiate commented out code from actual comments but vscode inserts a space between two slashes // // if I apply line comment twice.

Steps to Reproduce:
1. Set focus on a line in the editor
2. Press cmd+k, cmd+c to comment out the code with //
3. Press cmd+k, cmd+c again

(Expected)
//// var foo;

(Actual)
// // var foo;

(Related link)
On four slashes usage
http://stylecop.soyuz5.com/SA1626.html

Thanks for consideration!

**Comment by mjbvz** [comment]
This is by design for the line comment command. Instead, please try creating a snippet with four slashes instead. You can even setup a keybinding for this: https://stackoverflow.com/a/43001161/306149
