### ISSUE TITLE
Getting error (exit code: 0) when going to Terminal or running a task

### ISSUE THREAD

**Issue by carl0lasat** [microsoft/vscode#79075]
![Terminal error](https://user-images.githubusercontent.com/54086290/62985281-7c301180-bdeb-11e9-8bf8-851edda35344.jpg)
- VSCode Version: 1.37
- OS Version: Windows 10

Steps to Reproduce:

1. Go to View.
2. Click on Terminal
or
1. Run a specific test using a task.

Result:
Error below is displayed.  Terminal window does not open.

"The terminal process terminated with exit code: {0}"

**Comment by alexr00** [comment]
@carl0lasat can you share your settings.json?

**Comment by jaondayko** [comment]
So recently I have had 3 different people deal with this issue, the resolution was to make sure windows is on version 1903. It seems to update VSCode to latest does break it and if you are not on 1903 it will not work, but the moment they updated to 1903 it worked fine.

**Comment by carl0lasat** [comment]
This is a weird issue and I only started getting this after I updated my VSCode to version 1.37.

@alexr00 not sure if you want the whole settings, but I only got all settings I could find around Terminal.

"terminal.explorerKind": "integrated"
"terminal.external.linuxExec": "xterm"
"terminal.external.osxExec": "Terminal.app"
"terminal.external.windowsExec": "C:\\WINDOWS\\System32\\cmd.exe"
"terminal.integrated.commandsToSkipShell": []
"terminal.integrated.confirmOnExit": false
"terminal.integrated.copyOnSelection": false
"terminal.integrated.cursorBlinking": false
"terminal.integrated.cursorStyle": "block"
"terminal.integrated.cwd": ""
"terminal.integrated.drawBoldTextInBrightColors": true
"terminal.integrated.enableBell": false
"terminal.integrated.env.linux": {}
"terminal.integrated.env.osx": {}
"terminal.integrated.env.windows": {}
"terminal.integrated.experimentalRefreshOnResume": false
"terminal.integrated.fontFamily": ""
"terminal.integrated.fontSize": 14
"terminal.integrated.fontWeight": "normal"
"terminal.integrated.fontWeightBold": "bold"
"terminal.integrated.inheritEnv": true
"terminal.integrated.letterSpacing": 0
"terminal.integrated.lineHeight": 1
"terminal.integrated.macOptionClickForcesSelection": false
"terminal.integrated.macOptionIsMeta": false
"terminal.integrated.rendererType": "auto"
"terminal.integrated.rightClickBehavior": "copyPaste"
"terminal.integrated.scrollback": 1000
"terminal.integrated.setLocaleVariables": true
"terminal.integrated.shell.linux": null
"terminal.integrated.shell.osx": null
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"
"terminal.integrated.shellArgs.linux": []
"terminal.integrated.shellArgs.osx": [
  "-l"
]
"terminal.integrated.shellArgs.windows": []
"terminal.integrated.showExitAlert": true
"terminal.integrated.splitCwd": "inherited"
"terminal.integrated.windowsEnableConpty": true

**Comment by carl0lasat** [comment]
@jaondayko my windows version is 1809 which was updated June 2019.  Thanks for the advise.  I'll try to update my windows version today.

**Comment by Tyriar** [comment]
Might be related to https://github.com/microsoft/vscode/issues/78898?

The message itself is confusing as {0} should be replaced, it's replaced with exitCode and it's within an `if (exitCode)` block:

https://github.com/microsoft/vscode/blob/994e1315c09a6d92e57adf8cb9d386f5b30b4b3f/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1055

**Comment by carl0lasat** [comment]
Update:

I found out that issue is affecting multiple resources across our company that use VSCode and Eclipse.  They concluded it was related to the recent updates but connected to something else.  Maybe @jaondayko was right about the windows version.  This issue has already been brought up to our IT department.  

Thanks for your responses.  I'll keep you posted.

**Comment by Tyriar** [comment]
@carl0lasat oh it affects Eclipse as well?

**Comment by carl0lasat** [comment]
@Tyriar apparently yes, at least across our company.

**Comment by StephanLeschke** [comment]
I had the same issue with my installation.  
Inreasing the log level revealed the following message:  

> Error launching WinPTY agent: ConnectNamedPipe failed: windows error 232

It turned out to be caused by my anti virus software.  
Bitdefender blocked the call to winpty.exe, which is necessary to interact with the console.  
After creating an exception rule for winpty.exe as mentioned here:  
[https://github.com/microsoft/vscode-docs/commit/3e791b025d00242eecc8f46e98d9444b498f5353](url)  
everything worked fine again.

**Comment by alexr00** [comment]
@Tyriar We tested on an 1803 Windows VM with the settings from above copied in with both insiders and stable. The terminal worked fine with both. I didn't get a chance to test on 1809.

**Comment by jaondayko** [comment]
> It turned out to be caused by my anti-virus software.
> Bitdefender blocked the call to winpty.exe, which is necessary to interact with the console.

I also am using BitDefender at our company, however, our issue was resolved as soon as anyone would update to 1903 as opposed to being on 1809.

**Comment by StephanLeschke** [comment]
As I understood under 1903 conpty is used instead of winpty.  
I don't know why this should not be blocked by BitDefender, but this could explain the difference.

**Comment by MarcusGV** [comment]
> I had the same issue with my installation.
> Inreasing the log level revealed the following message:
> 
> > Error launching WinPTY agent: ConnectNamedPipe failed: windows error 232
> 
> It turned out to be caused by my anti virus software.
> Bitdefender blocked the call to winpty.exe, which is necessary to interact with the console.
> After creating an exception rule for winpty.exe as mentioned here:
> [https://github.com/microsoft/vscode-docs/commit/3e791b025d00242eecc8f46e98d9444b498f5353](url)
> everything worked fine again.

I Have the same issue, but that link is not working :(

**Comment by StephanLeschke** [comment]
Sorry, I made a mistake creating the link.  
I updated my previous comment and tested the link.  
Now it should work.

**Comment by Tyriar** [comment]
OK this definitely looks like anti-virus software preventing winpty from doing its thing. The reason conpty wouldn't be affected is because it's built into Windows.

**Comment by MarcusGV** [comment]
Thanks a lot! you where right, was the bitdefener antivirus, I just except the file and now its working again
