### ISSUE TITLE
Getting default task and setting definition

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#79076]
Is there a way to get the current default task set in `tasks.json`?
Otherwise I'd like to suggest such a feature.
And it would be super useful if you could set the definition of tasks as well from inside the extension.

Example of both suggestions:
```
vscode.tasks.fetchTasks().then(tasks => {
	tasks.forEach(task => {
		if (task.default) task.definition.Set( 'source', 'some source file' )
	})
})
```

**Comment by alexr00** [comment]
There is no concept of a default task. If you want to set a task definition you should write a [task provider](https://code.visualstudio.com/api/extension-guides/task-provider).

**Comment by Hezkore** [comment]
@alexr00 
Maybe I was unclear.
This is not a question nor me wanting help.
I have already written a task provider.
And there certainly is a concept of a "default task".
![Code_2019-08-14_17-07-01](https://user-images.githubusercontent.com/1727541/63032393-05ac1600-beb6-11e9-923a-6c98e15ce6fe.png)
The user can set the default task which adds:
```
"group": {
	"kind": "build",
	"isDefault": true
} 
``` to `tasks.json` for the task selected.
What I'm asking for is a way in the extension API to retrieve the task currently set as `"isDefault": true`.
There is also no way of changing data in `tasks.json` from within the extension API.
Which is why I'm asking for that feature as well.

For example: Let's say the user wants to right click an open task and "lock the build file", which would set "source" in `tasks.json` to the file selected by the user.
This is currently not possible.

**Comment by alexr00** [comment]
You can write to tasks.json using https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4065

There is a default build and test task, which can be two separate tasks. Using `fetchTasks` you can inspect the tasks and see which ones are marked as build and test, but not the default. I created an API feature request to get the default: https://github.com/microsoft/vscode/issues/79188

**Comment by Hezkore** [comment]
Sorry for being persistent; but I believe that would write to settings.json, not tasks.json.
