### ISSUE TITLE
clang-format settings not available when using the SSH extension

### ISSUE THREAD

**Issue by daravi** [microsoft/vscode#79070]
- VSCode Version: 1.38.0
- OS Version: CentOS 7

Steps to Reproduce:

1. Open VSCode Insiders >> Settings >> search for clang >>> you will see the appropriate settings
2. Open a remote connection using the Remote-SSH extension
3. Open Settings >>> search for clang >>> the clang format settings are missing

Does this issue occur when all extensions are disabled? Yes (except the Remote SSH extention that cannot be disabled when connected to a remote)

**Comment by roblourens** [comment]
Do you have that extension installed on the remote or just locally?

**Comment by daravi** [comment]
Sorry but I am not sure what you mean. As I understand the Remote-SSH extention has a server component installed on the remote and a client component locally. If you are referring to clang format it is VSCode itself not an extention.

**Comment by roblourens** [comment]
vscode does not have anything for clang builtin. I assume you are using the C++ extension or another extension and in that case you need to open the extensions viewlet and install that extension on the remote.
