### ISSUE TITLE
Add git Setting: Toggle Commit Message Window

### ISSUE THREAD

**Issue by danyadsmith** [microsoft/vscode#79074]
There are several settings available related to git commit messages, such as:

* `git.inputValidation`
* `git.InputValidationLength`
* `git.InputValidationSubjectLength`

I don't like to use the Commit message window provided in the Source Control pane in the Activity Bar. I have a `.gitmessage` configured and prefer to use command line/Vim for my commit messages.

Please add a **boolean** setting for the source control panel:

* `git.showCommitWindow`

This setting would allow those of us who prefer to use an editor for commit messages to set this to `false` by default.

Also, the following command would be helpful in the Command Palette:

* `git.toggleCommitWindow` 

It would allow users to toggle the visibility of the commit window.

**Comment by joaomoreno** [comment]
We currently have API for this, so it should be pretty straightforward to implement.

**Comment by flurmbo** [comment]
Hi @joaomoreno @danyadsmith, I was thinking of working on this. Just to clarify, the `git.showCommitWindow` setting should simply hide the commit message input (where it says "Message (Ctrl+Enter to commit on 'master')" in the image below)?

![commitwindow](https://user-images.githubusercontent.com/35127144/66080873-8e494900-e52c-11e9-9ad8-4b66fea68f9e.png)

**Comment by joaomoreno** [comment]
Yeah, I would call it `showCommitInput` instead, though.
