### ISSUE TITLE
Opaque solid colour on context menus for VSCode Light & Light+ theme. 

### ISSUE THREAD

**Issue by 0msLaw** [microsoft/vscode#79081]
- VSCode Version: 1.37
- OS Version: Win10 1903

Steps to Reproduce:

1. Simply apply "Light (Visual Studio)" or "Light+(default light) theme and hover mouse pointer over context or drop down menus

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/48370987/62989029-0d00fe80-be79-11e9-874c-96f9d046f7b7.png)

**Comment by misolori** [comment]
@0msLaw I'm not seeing this reproduce on my Windows machine running 1.37: 

![image](https://user-images.githubusercontent.com/35271042/63007036-32453b00-be80-11e9-8543-b3ae3279f0ca.png)


Can you try looking through your `settings.json` to see if you've created any `workbench.colorCustomizations`?

**Comment by 0msLaw** [comment]
@misolori yep, I had some custom settings. Removed it and its working! My mistake! Thank you!
