### ISSUE TITLE
Multiple-Integrated-Terminal discoverability/usability issues

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#7908]
- VSCode Version: Code - Insiders 1.3.0-insider (62f0272219dc72fda5246d330640e6af52a10cd0, 2016-06-20T22:45:16.666Z)
- OS Version: Windows_NT ia32 - Windows 10 14342.1000 (Insider)

Hitting the hotkey (Ctrl+Shift+\`) again seems to refresh the Integrated Terminal window and the content of the already opened window disappears. I figured that this opened a fresh terminal -- but because there is no UI element that indicates how many terminals are open or which terminal I am on, I assumed it just replaced the old terminal and there was no way back.

The plus button apparently functions the same way, but initially I had no idea what it would do. Clicking it caused the terminal to reset but I wasn't sure why until I hovered over the button to read the pop-up text. 

Considering that there is no UI concept of tabs, multiple terminals, or ordering of the same, the back and forward buttons are similarly hard to reason about. They also apparently cycle around but since I have no idea how many terminals I have open without 

A "minus" button does not say to me that it would "close" a terminal. Not sure what I was expecting it to do. I understand there would be an overlap with the X for close (X already closes the pane).

It was not clear to me whether pressing the X (hover text: "Close") would close all terminals or just close "hide" the Terminal pane. The text should probably be changed to something like "Hide Integrated Terminal" to line up better with the text for Ctrl+\` in the command palette:

![image](https://cloud.githubusercontent.com/assets/494055/16216563/8ff9a2da-3720-11e6-833a-72bba619fd8d.png)

I know the hotkey Ctrl+\` is there, but does it make sense for Ctrl+Shift+\` it to open a fresh terminal when there is already a terminal open? Maybe it should pop open the Terminal pane first and not open a fresh terminal?

**Comment by Tyriar** [comment]
It will soon have a dropdown just like the output pane and the left and right buttons will go away (the commands will remain though). See https://github.com/Microsoft/vscode/issues/7732 for a discussion on the long term solution which probably won't make it in for June.
