### ISSUE TITLE
Code folding won't expand

### ISSUE THREAD

**Issue by Skatterbrainz** [microsoft/vscode#79086]
Issue Type: <b>Bug</b>

Since latest update, when working in larger powershell files (3000+ lines) it seems that some folded blocks won't expand when clicked or using the hotkey combination.  I have to close and re-open the file.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18936

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.1
xml|Dot|2.5.0
rainbow-csv|mec|1.2.0
powershell|ms-|2019.5.0
team|ms-|1.149.2
code-settings-sync|Sha|3.4.1
markdown-preview-enhanced|shd|0.4.3
vscode-icons|vsc|9.2.0

</details>

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/76596

Sample code would be great
