### ISSUE TITLE
Emmet: support all the features

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7909]
Now we only support:

* Expand Abbreviation
* Wrap with Abbreviation
* Remove Tag
* Update Tag

@egamma Are you planning to support [other features](https://github.com/emmetio/emmet/blob/master/lib/action/main.js#L75-L95)? I can submit a PR.

**Comment by rebornix** [comment]
I'm willing to see the PR :+1:

**Comment by mrmlnc** [comment]
Right now I'm working on adding support for settings and profiles.

**Comment by yisibl** [comment]
@mrmlnc Waiting for your PR.

**Comment by mrmlnc** [comment]
@yisibl, Well, I tried #7926

**Comment by egamma** [comment]
I've merged and tweaked the PR. More PRs :heart:

**Comment by mrmlnc** [comment]
Support for all Emmet action in the process development.

**Comment by mrmlnc** [comment]
Mini task, to keep you informed:

- [ ] Expand Abbreviation
- [ ] Balance
- [ ] Go to Matching Pair
- [ ] Wrap with Abbreviation
- [ ] Go to Edit Point
- [ ] Select Item
- [ ] Toggle Comment
- [ ] Split/Join Tag
- [ ] Remove Tag
- [ ] Merge Lines
- [ ] Update Image Size
- [ ] Evaluate Math Expression
- [ ] Increment/Decrement Number
- [ ] Reflect CSS Value
- [ ] Encode/Decode Image to data:URL

**Comment by egamma** [comment]
Closing this issue, the PR with all the features has been merged into master.
