### ISSUE TITLE
UI rendering is blocked when searching for files

### ISSUE THREAD

**Issue by lc-soft** [microsoft/vscode#79093]
- VSCode Version:1.37.0
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Open a project folder, this folder needs to have many large files larger than 1MB, for example: bundle.min.js, bundle.js.map
    ![2019-08-14 14-25-41 的屏幕截图](https://user-images.githubusercontent.com/1730073/62998891-70058c00-be9f-11e9-89e1-908abd699350.png)
1. Search files
1. Waiting search results
1. Scroll editor, or edit file.
1. The UI response will be very slow and sometimes it will not respond until the system pops up a dialog box to let me decide whether to close or continue to wait.
    ![Peek 2019-08-14 14-17](https://user-images.githubusercontent.com/1730073/62998533-6a5b7680-be9e-11e9-82ec-01c2f68be47a.gif)

Does this issue occur when all extensions are disabled?: 

No

**Comment by roblourens** [comment]
This issue with long lines in search results should be fixed in the Insiders build.

If there are multiple matches on the same very long line, then you may still see it.
