### ISSUE TITLE
Get error: "rejected promise not handled within 1 second" when calling showQuickPick()

### ISSUE THREAD

**Issue by tianhao-ni** [microsoft/vscode#79097]
We are calling Api "showQuickPick()" in our extension "tizentv 1.0.2", after install extension "tizentv 1.0.2", this extension always failed at showQuickPick(), with error:"rejected promise not handled within 1 second".

After disable and enable this extension, this problem is not reproduced.

This problem only occurs with version September 2018 (version 1.28) and later. Versions before this date are working fine.

**Comment by chrmarti** [comment]
This could be an error being thrown inside the extension's code. Please add logging (`.then(undefined, console.error)`) to the extension code and post the logged error here:
```ts
    vscode.window.showQuickPick(choices, options).then(function (choice) {
        ...
    }).then(undefined, console.error);
```
