### ISSUE TITLE
Unable to debug Default Angular application created using template from VS 2019

### ISSUE THREAD

**Issue by amithegde** [microsoft/vscode#79095]
Created an angular application using VS 2019 (Ver 16.3.0 Preview 2.0) using the default template. I could debug it through VS 2019.  Then I opened the ClientApp directory on VS Code and using integrated terminal, started the application by calling `ng serve --o` which loads the application in browser. Then I created a `launch.json` to debug against chrome with URL as `http://localhost:4200`. When I try to debug, it starts browser but the browser window shows up as crashed.  Address bar shows `about:blank`. And after a while VS Code shows an error message dialog:

[Window Title]
Visual Studio Code

[Content]
Cannot connect to runtime process, timeout after 10000 ms - (reason: Got a response from the target app, but no target pages found).

[Open launch.json] [Cancel]

On the VS Code it looks like debug started as the debug controls show up. I do have `Debugger for Chrome` extension installed.

**Comment by amithegde** [comment]
Validated by creating one more project. Can debug from VS 2019, `ng serve --o` works. But can't debug from VS Code. Here is the text from launch.json

    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}"
        }
    ]

**Comment by roblourens** [comment]
> When I try to debug, it starts browser but the browser window shows up as crashed

Do you say that just because it is blank or because it actually shows an error message? This is weird because we use the same code to launch chrome in both products.

**Comment by amithegde** [comment]
Debugging from VS Code:
![debug](https://user-images.githubusercontent.com/816051/63233470-2ab9c500-c1e5-11e9-9962-111cec93e6d8.png)

ng serve:
![ng-serve](https://user-images.githubusercontent.com/816051/63233485-41f8b280-c1e5-11e9-853a-c49fad41216c.png)

**Comment by amithegde** [comment]
While ng serve is running, I can start debugging from VS Code and then it hits breakpoint. Is that the recommended way? I believe when debugging is started from VS Code, it should start up HTTP server as well.

**Comment by amithegde** [comment]
I could repro the problem. It happens when VS Code is started with administrator privileges:

![image](https://user-images.githubusercontent.com/816051/63304531-34e8cb80-c298-11e9-94e0-b263c5be3fcf.png)

If VS Code is not started with administrator privileges, when `ng serve` is running, I am able to start debugging on VS Code.

So, two requests:
- Make VS Code call `ng serve` when debugging session starts, if `ng serve` is not running. Since I am coming from VS which starts debugging session when I hit debug button on VS, I feel this will provide seamless experience.
- Make VS Code debugger work fine when it's started with administrator privileges

**Comment by roblourens** [comment]
You can set this up using the preLaunchTask in your debug config. See this page and the "tasks" docs for details: https://code.visualstudio.com/Docs/editor/debugging.

The second, I discourage people from using vscode as administrator. I am not sure what issue you are seeing exactly, it should work fine as administrator. But I don't really support that use case.

**Comment by roblourens** [comment]
It's possible that Chrome just doesn't want to run as administrator, since the problem seems to be with Chrome.
