### ISSUE TITLE
can't use '\' in key bindings (no keyboard layout issue)

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode#791]
This is different to keyboard layout issues. It appears that this key isn't bindable by design. But we need it to solve some keyboard layout issues in the Vim extension. :)

More details:

https://code.visualstudio.com/docs/customization/keybindings (See "the following keys are accepted")
https://github.com/VSCodeVim/Vim/issues/49

**Comment by alexandrudima** [comment]
@guillermooo Tried the following and it worked for me on Windows / Standard US keyboard layout:

```json
{
	"key": "\\",
	"command": "actions.find",
	"when": "editorTextFocus"
}
```

What OS are you on?

**Comment by guillermooo** [comment]
It wouldn't work, neither with en-US nor with es-ES. I'll retry in case I missed something.

**Comment by alexandrudima** [comment]
@guillermooo on win10, after switching kb layout to es-ES, I can trigger the above rule with the key that produces this character (`º`).

**Comment by guillermooo** [comment]
Haven't tried yet, but then the docs should probably be updated to reflect that `\\` is a bindable key?

**Comment by alexandrudima** [comment]
well, the key that is bound is `VK_OEM_5` (https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85)). It is the key that when pressed produces a `keydown` event with the `keyCode = 220` under Chromium. On the US standard layout it is physically labeled as `\|`.

We do keybinding dispatching during the browser `keydown` event. It has to be done during `keydown` because browsers mostly do not generate `keypress` events if no characters are produced (e.g. `ctrl+enter` will generate a `keydown` and a `keyup` but not a `keypress`). The `keydown` event unfortunately has the nasty characteristic that it doesn't give any hint as to what the physicial key label would be.

In this case, to add a rule for it in `keybindings.json`, we must use `\\` because this is JSON and JSON gives a special meaning to `\` in strings. The following would be illegal JSON:

```json
{
    "key": "\",
    "command": "actions.find",
    "when": "editorTextFocus"
}
```

**Comment by guillermooo** [comment]
> In this case, to add a rule for it in keybindings.json, we must use \\ because this is JSON and JSON gives a special meaning to \ in strings. The following would be illegal JSON:

Yup, I get that. My point is that from the current docs it isn't clear that `\` is bindable at all. So for completeness, it may be beneficial to add `\` to the list of accepted keys. I just wrote `\\` earlier becaue I though the GitHub MD parser would be thrown off. But I don't know if I'm making any sense!

**Comment by alexandrudima** [comment]
@guillermooo Thank you for being patient with me :+1:  

Pushed Microsoft/vscode-docs@184dd52 to add `\` to the list. We publish to the website often, should be picked up at https://code.visualstudio.com/Docs soon.

**Comment by guillermooo** [comment]
@alexandrudima I'm able to produce `\` with `AltGr + º` using a Spanish Spain QWERTY layout. However, using a Spanish Spain QWERTY layout, I cannot capture key codes produced by keys that produce "standard" key codes (`\`, etc.) in the US QWERTY layout.

For example, `0xe7` (`ç`) in Spanish Spain QWERTY is for me `0x5c` (`\`) when switching to US QWERTY (the same physical key). So my question is, can VSC now, or is it planned for the future, to make a key code like `0xe7` bindable? My understanding of the problem is superficial, but I guess the answer is negative. If so, could VSC let extensions process key codes instead of characters?

Another surprising thing, is that the `0x3c` (`<`) key in Spanish Spain QWERTY is `0x5c` (`\`) for US QWERTY (different physical key to usual `\` in US QWERTY). So, effectively, I cannot capture `<` in Spanish Spain QWERTY, because for US QWERTY it's a redundant key code. This will make it very hard to make the Vim extension usable for non-US layouts. Sublime, for example, does capture the correct key code and character here. I believe you mentioned in a different post that this problem is a limitation of Electron. It'd be really limiting if VSC could not solve this issue.

The main lesson here is that dealing with international keyboards is very tricky and confusing; I hope I have not made any mistakes in my explanation, but keep in mind that this topic is quite alien to me, so I may be missing something obvious.

**Comment by guillermooo** [comment]
@alexandrudima I should have started here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267(v=vs.85).aspx

So need to answer to this. Also, I see better support for Vim emu is a VSC Team target for Dec.
