### ISSUE TITLE
Java variable-highlight goes wrong

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#79108]
Issue Type: <b>Bug</b>

```java
int x = 0, y = 0;
```
you will find the `y` doesn't be recognized as a variable.

When I use `TM scope inspector` to find what `y`'s kind is,it tells me `y` is a `meta.method.body.java` instead of `variable`(but `x` is `variable`).

I have try another computer with insider-version,bug shows,too.

I test this in `c++` and there's no problem.

and I have disabled my Java extensions.

can't believe VSCode could make this mistake.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.0
xml|Dot|2.5.0
gitlens|eam|9.9.3
todo-tree|Gru|0.0.141
cpptools|ms-|0.25.0-insiders
material-icon-theme|PKi|3.8.1
vscode-css-peek|pra|3.0.2
java|red|0.47.0
vscode-markdown-paste-image|tel|0.12.0
linenote|tkr|1.2.1
vscodeintellicode|Vis|1.1.9
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by JoeyRxy** [comment]
And then I find when you type this:
```java
int x = 0, y = 0;
int z = x + y;
```
the `x` and `y` at second line isn't recognized as `variable` either.

while in `c++`,everything is fine.

I didn't know whether it's a **bug** or just Java's feature.but in other editors or ides there's

**Comment by JoeyRxy** [comment]
Today I find more:
![bugs](https://github.com/JoeyRxy/tmp/blob/master/Snipaste_2019-08-15_13-36-53.png)
![bugs](https://github.com/JoeyRxy/tmp/blob/master/Snipaste_2019-08-15_13-37-33.png)
the array `BIT` has different color in different place.

**Comment by alexr00** [comment]
We get our grammars from other projects. Moved the issue to owning repo: https://github.com/atom/language-java/issues/202

**Comment by JoeyRxy** [comment]
@alexr00 But they don't want to fix the bug,so?

**Comment by JoeyRxy** [comment]
@alexr00 https://github.com/atom/language-java/issues/202#issuecomment-524430424
