### ISSUE TITLE
Task is already active dialog requires mouse interaction

### ISSUE THREAD

**Issue by jimmyff** [microsoft/vscode#79107]
Version 1.36.0

When running a task that is already running, vs code displays a dialog (see screenshot below). As this dialog does not have focus there is no way to interact with it without using a mouse.  This dialog could take focus when created which would allow easy interaction for keyboard users. 
![Screenshot 2019-08-14 at 11 55 09](https://user-images.githubusercontent.com/298850/63016129-bef4f680-be8a-11e9-9f1e-fa7a97f87cb0.png)

Alternatively this dialog could be replaced with a select menu like when choosing who to scan task output:
![Screenshot 2019-08-14 at 11 58 31](https://user-images.githubusercontent.com/298850/63016217-fcf21a80-be8a-11e9-9d54-381d096efe28.png)

**Comment by alexr00** [comment]
@bpasero is there a way to make notifications take focus?

**Comment by bpasero** [comment]
@alexr00 no, intentionally not. If you must get the users attention, use a modal dialog which has focus.

As for keyboard accessibility, there are tons of commands to focus the notification.

**Comment by alexr00** [comment]
@jimmyff when you encounter this notification, do you usually want to use one of the buttons on it?

When I see this notification, usually I want to do nothing. I had forgotten that I already had the task running.

**Comment by jimmyff** [comment]
@alexr00 fair enough, my specific use-case is when I'm serving firebase cloud functions locally and I want to re-run the serve task as I've updated the build. The majority of other tasks in this project follow the same format as yours and only require to be running, not re-run. 

Thanks for the notification focus commands @bpasero - didn't realise these existed.

Will close this as it seems that there is already keyboard solution for my edge case.
