### ISSUE TITLE
Submodules with different names shown as the same (source control providers)

### ISSUE THREAD

**Issue by TrueMatoriv** [microsoft/vscode#79101]
Issue Type: <b>Bug</b>

The integration with git submodules is great!  

But i have this problem: in the "SOURCE CONTROL PROVIDERS" section is impossible to differentiate between two submodules if the final part of the path (folder name) is the same.

for example, with this configuration in .gitmodules: 

[submodule "foundation-bo"]
	path = backoffice/foundation
	url = https://*****************************
[submodule "foundation-mp"]
	path = portafoglio/foundation
	url = https://*****************************

vscode in the "SOURCE CONTROL PROVIDERS" section show two submodules with the same name "foundation" (folder name) Instead of "foundation-bo" and "foundation-mp", which I think is the correct behavior (am i wrong?) 

![vscode-submodules-dname](https://user-images.githubusercontent.com/6492411/63003129-d5de1d80-be77-11e9-8862-e77f59e816ad.png)

making difficult to understand on which repo you are working on.

thanks! 
Nicolò. 

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
prettier-vscode|esb|1.9.0
gc-excelviewer|Gra|2.1.32
vscode-firefox-debug|hbe|1.8.2
Ionide-fsharp|Ion|4.0.6
rainbow-csv|mec|1.2.0
mssql|ms-|1.6.0
csharp|ms-|1.21.0
vetur|oct|0.22.1
quicktype|qui|12.0.46
csharp2ts|raf|0.0.22

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/43951
