### ISSUE TITLE
VScode cause samba server CPU usage high

### ISSUE THREAD

**Issue by XuthCelestica** [microsoft/vscode#79106]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

I found when I open a samba remote folder to view code, the samba server's CPU usage became very high(70% of 48 codes server). Maybe it's a bug.
And I had met this issue before, but when I upgrade a newer vscode, it disappear.
But after I upgrade the vscode v1.37.0 today, this issue happened again. 
And I tried to install different vscode version(1.33.1/1.34/1.35/1.36/1.37) but nothing help.
So I want to know why vscode cause samba server cpu usage so high.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

- What platform are you running VSCode on?
- When you were previously able to access the same remote folder with VSCode, what version were you running?
- Approximately how many files does the remote folder contain?

**Comment by XuthCelestica** [comment]
> /needsMoreInfo
> 
> * What platform are you running VSCode on?
> * When you were previously able to access the same remote folder with VSCode, what version were you running?
> * Approximately how many files does the remote folder contain?

I use vscode on win-10 and I forget the version not cause samba server cpu usage high.
And I use vscode to view a opensource embedded linux project, so there are many files folders and files the remote folder contains.

**Comment by XuthCelestica** [comment]
> > /needsMoreInfo
> > 
> > * What platform are you running VSCode on?
> > * When you were previously able to access the same remote folder with VSCode, what version were you running?
> > * Approximately how many files does the remote folder contain?
> 
> I use vscode on win-10 and I forget the version not cause samba server cpu usage high.
> And I use vscode to view a opensource embedded linux project, so there are many files folders and files the remote folder contains.

One more thing mays be helpful. When I am using vscode code before, the network usage of my win10 is low (no more than 100k/s). But now when I open vscode to view remote folder, it occupy 1MB/s continuously. But if I close vscode, the samba server cpu usage will be low in a short time.

**Comment by gjsjohnmurray** [comment]
Too bad you don't know what version you were running before you upgraded to 1.37.0 today. Seeing that you tried older versions back as far as 1.33.1 and still had the problem, I assume you were previously using something earlier than 1.33.1.

What language(s) is your project coding in? Maybe there's more file-scanning being done in the language server(s) in 1.37 than before.

Have you noticed slower performance on your Windows 10 client machine?

Maybe review https://github.com/Microsoft/vscode/wiki/Performance-Issues and submit info here.

**Comment by gjsjohnmurray** [comment]
Another idea is to run the `Reload Window With Extensions Disabled` command and see if this makes a difference. If it does, try enbling your extensions one by one until you find which one is causing  the high network traffic.

**Comment by XuthCelestica** [comment]
> Another idea is to run the `Reload Window With Extensions Disabled` command and see if this makes a difference. If it does, try enabling your extensions one by one until you find which one is causing the high network traffic.

Today, I tried to kill subprocess those occupy large bandwidth(such as rg.exe) of vscode, and found samba server cpu usage became very low. 
And I found that the vscode takes a few of senconds and then display content of the folder when I expand them with the old vscode version, but now with the vscode 1.37.0, it seems like vscode dumps the files of remote server, when I expand folders, it shows the files immediately.
Maybe the difference could help you.
Now when I use vscode 1.37.0 to view remote folders, I kill the subprocesses and the samba server cpu usage won't become high again.

**Comment by XuthCelestica** [comment]
> > Another idea is to run the `Reload Window With Extensions Disabled` command and see if this makes a difference. If it does, try enabling your extensions one by one until you find which one is causing the high network traffic.
> 
> Today, I tried to kill subprocess those occupy large bandwidth(such as rg.exe) of vscode, and found samba server cpu usage became very low.
> And I found that the vscode takes a few of senconds and then display content of the folder when I expand them with the old vscode version, but now with the vscode 1.37.0, it seems like vscode dumps the files of remote server, when I expand folders, it shows the files immediately.
> Maybe the difference could help you.
> Now when I use vscode 1.37.0 to view remote folders, I kill the subprocesses and the samba server cpu usage won't become high again.

I tried you suggestions but they could not solve my problem. 
When I open a remote folder has a few of files, samba server cpu usage won't become high. I think maybe it's because my remote project has too many files(three different kernel version of linux src and some other code).
Thanks for your help.

**Comment by XuthCelestica** [comment]
Now I am going to close the issue and use vscode with the workaround way.
Sorry for that I could not deep in this problem because I have to focus on my work.
