### ISSUE TITLE
Question on Build and Run From Source instructions: Node version

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#7910]
The wiki [instructions](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) say that I'll need Node.JS, at least version 5.10.   For unrelated reasons, I'm reluctant to install anything later than the latest [LTS](https://github.com/nodejs/LTS#lts_schedule) release (v4.4.5) on the default PATH on my dev system.   

Is v5.10 still the best release for working on vscode?   Any reason not use the 'Current' v6.6.2?

Is it possible to setup and use a side-by-side version of Node.js for the purpose of contributing to vscode on the same machine where latest LTS-compatible tools are built?     Any recommended approach would be helpful?

TIA

**Comment by joaomoreno** [comment]
- https://github.com/creationix/nvm
- https://github.com/coreybutler/nvm-windows

**Comment by BurtHarris** [comment]
Thank you, looks perfect.

**Comment by joaomoreno** [comment]
Yeah. Some Code dependencies are shared between Code and the dev tools. Some of them are binaries, compiled against Code's node version. If you have the same node version as your dev tools, you will benefit from better performance when running `gulp watch`.
