### ISSUE TITLE
Markdown Highlighting: Uppercase and Unknown Tags

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode#79119]
**Note:** This has been copied to microsoft/vscode-markdown-tm-grammar#49 as per https://github.com/microsoft/vscode/issues/79119#issuecomment-52127

The Markdown syntax highlighting grammar doesn't recognize valid uppercase HTML tags or unknown tags (such as web components):

![Screen Shot 2019-08-14 at 15 57 10](https://user-images.githubusercontent.com/1935696/63026993-6e8e9080-beac-11e9-8605-47b9aea6902e.png)

Compare that with the HTML grammar highlighting, which would be the preferable output:

![Screen Shot 2019-08-14 at 16 02 35](https://user-images.githubusercontent.com/1935696/63027367-202dc180-bead-11e9-9ab9-2693f7385b48.png)

---

Background: In @silvenon's [MDX extension](https://github.com/silvenon/vscode-mdx), I would like React component highlighting to work properly inline (see silvenon/vscode-mdx#9).

While this wouldn't get us all of the way there, it would at least be a step in the right direction (and would also benefit normal Markdown users).

---

Potentially related (HTML Textmate Grammar fix for custom HTML tags):

https://github.com/textmate/html.tmbundle/issues/92
https://github.com/microsoft/vscode/commit/cfc2a2212de9ea10943af58ebd1817a5ad196463

**Comment by iansan5653** [comment]
This may belong in https://github.com/microsoft/vscode-markdown-tm-grammar

**Comment by karlhorky** [comment]
@iansan5653 Thanks! I've copied it to microsoft/vscode-markdown-tm-grammar#49. Will close whichever one is invalid.

**Comment by mjbvz** [comment]
Closing as upstream
