### ISSUE TITLE
Disabled Extension Gets Enabled Upon Extension Update

### ISSUE THREAD

**Issue by maa3x** [microsoft/vscode#79116]
Issue Type: <b>Bug</b>

This happens only for two extensions:
- Live Share and it's dependents (chat, audio, etc.)
- Remote Development and it's dependents (SSH, ...)

When I update this two, they get enabled and I have to disable them manually.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
markdown-toc|Ala|1.5.6
laravel-extra-intellisense|ami|0.2.0
laravel-blade-spacer|aus|1.0.3
laravel-docs|aus|1.4.1
vscode-intelephense-client|bme|1.1.6
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
gitignore|cod|0.6.0
laravel-goto-view|cod|1.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.1
jshint|dba|0.10.21
vscode-eslint|dba|1.9.0
vscode-faker|dee|1.3.0
xml|Dot|2.5.0
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
LogFileHighlighter|emi|2.5.0
vscode-todo-plus|fab|4.14.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.3
svg|joc|0.1.6
docthis|joe|0.7.1
vscode-peacock|joh|3.1.0
php-cs-fixer|jun|0.1.120
rainbow-csv|mec|1.2.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
theme-monokai-pro-vscode|mon|1.1.13
vscode-apache|mrm|1.2.0
vscode-attrs-sorter|mrm|2.1.0
vscode-scss|mrm|0.6.2
vscode-typescript-tslint-plugin|ms-|1.2.2
php-docblocker|nei|2.0.1
es6-css-minify|olb|3.0.1
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.8.1
vscode-css-peek|pra|3.0.2
vscode-yaml|red|0.4.1
vscode-sort-json|ric|1.14.0
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.25
trailing-spaces|sha|0.3.1
stylelint|shi|0.51.0
vscode-fileutils|sle|2.14.5
vscode-laravel-assist|tia|0.1.7
sort-lines|Tyr|1.8.0
highlight-matching-tag|vin|0.9.3
vscodeintellicode|Vis|1.1.9
snippet|vsc|0.7.0
vscode-wakatime|Wak|2.2.0
quokka-vscode|Wal|1.0.240
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
plsql-language|xyz|1.8.2
linecount|yyc|0.1.7
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Steps to Verify:

- Install Remote SSH extension pack
- Disable all Remote SSH extensions
- Install old version of each Remote SSH extension using the action `Install Another Version...` in the gear icon
- You will see an update action on each extension
- Update all Remote SSH extensions
- Verify that they are not enabled.
