### ISSUE TITLE
Terminal lines appears to have margin

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#7911]
When pressing F7, the list of previous commands appears to have margin:
![term](https://cloud.githubusercontent.com/assets/1297882/16219781/0e56f534-3789-11e6-9008-ebbd3abf6e74.gif)

Here's the Windows command prompt:
![console](https://cloud.githubusercontent.com/assets/1297882/16219783/11ad070a-3789-11e6-8893-91f24bae7cbe.gif)

1.3.0-insider
Win10

**Comment by Tyriar** [comment]
This was introduced by customizable line height, it makes selections look a bit wonky too.

**Comment by coreh** [comment]
Wow! Out of curiosity, how do you open that menu? Is that a new Windows 10 feature?

**Comment by csholmq** [comment]
Nothing in latest insiders. Did it miss the train?

**Comment by Tyriar** [comment]
It's fixed but it's sitting on a branch, will likely be merged tomorrow for the next Insiders.

**Comment by csholmq** [comment]
Oh, ok. Just wanted to know in order to verify the fix.

**Comment by Tyriar** [comment]
@csholmq great :smiley:

**Comment by csholmq** [comment]
Confirmed! :D

**Comment by isidorn** [comment]
Verified by user - thanks!
