### ISSUE TITLE
New tap called 'hidden' in file explorer tab

### ISSUE THREAD

**Issue by yousefelgoharyx** [microsoft/vscode#79112]
sometimes there's some folders we don't wanna see in the file explorer such as node_modules and another folders that we rarely use so if there was a tab called 'hidden' which contains some folders that we don't or rarely use that'd be easier and less confusing for human eye xD therefore it improves the ux, and oh of course it'd be nice if we can access it anytime xD so maybe its name should be rarely used explorer ^^

**Comment by IllusionMH** [comment]
At this time you can use `files.exclude` to hide folders/files that aren't necessary in your workspace.

To show that files you can change json key to `files.exclude1` (make it invalid), all files will become visible. Also you can use [Toggle Excluded Files](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) to easily show/hide excluded files.
