### ISSUE TITLE
Debug console scrolls near top after each evaluated line after printing long array in debug console (close reference to #70331 - still can reproduce bug)

### ISSUE THREAD

**Issue by Ougagagoubu** [microsoft/vscode#79114]
Hello all,

first issue report, so please forgive me my mistakes.

This is a further bug report to the issue in https://github.com/Microsoft/vscode/issues/70331 , which seems, atleast for me, not entirely be fixed. (i could not comment to the issue, that's why i needed to open a new issue). I'm using latest VSCode Version, see VSCode details further below.

### Expected behaviour
Debug Console window behaves normally

### Actual behaviour
Debug console scrolls to top after each evaluated line, while showing a long array in debug window

### Steps to Reproduce:

1. create bug.py file
2. write these lines
`import numpy as np` 
`array = np.array(np.arange(1000))` 
`print(1)`
3. set a breakpoint at line 5 `print(1)`
4. start debug until breakpoint
5. switch to debug console window and type 
`array` into command line to show the array
6. follow along with a `print(1)` statement in the debug console and the window will jump to top
7. This behaviour repeats, as long as some parts of the array are shown in the debug console - when the array "disappears" behind the ribbon, the console stops jumping (for me this takes like 6 `print` statements, depending on the size of your debug console)

- VSCode Version:
Version: 1.37.0 (system setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/77837
