### ISSUE TITLE
vscode.workspace.onDidClosetextDocument() not working after creating vsix package.

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#79110]
- VSCode Version:1.37.0
- OS Version:Windows_NT

the callback function of vscode.workspace.onDidCloseTextDocument() is working at development, but it is not working after packaging to vsix.

I have done googling for several hours and posted in forums, slack but I couldn't get the answer.
can you please help me with this. 

code:-
```
vscode.commands.registerTextEditorCommand('extension.closeEditor', (value) => {
        vscode.workspace.onDidCloseTextDocument(function(){
              if (value.document.getText()){
              const pickListItems = [];
              const option1 = {
                  label: "Yes",
                  description: "To Apply the changes",
              };
              const option2 = {
                  label: "No",
                  description: "Don't Apply the changes",
              };
              pickListItems.push(option1,option2)
              vscode.window.showQuickPick(pickListItems,{
                  ignoreFocusOut: true,
                  placeHolder: "Do you want to Apply the changes",
              }).then(SOME CODE)
     })
vscode.workspace.openTextDocument(vscode.Uri.file(path_file1))
            .then( value => {
            vscode.window.showTextDocument(value)
            .then(value1 => {
                console.log("This is value1",value1);
                vscode.commands.executeCommand('extension.closeEditor');
         })
  })
```
Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi 

I have raised a request in StackOverflow(https://stackoverflow.com/questions/57498434/callback-function-of-vscode-workspace-ondidclosetextdocument-is-working-at-devel) and the persons who tried this are also facing the same issue.
Is this a bug?

Thanks,
Akhil

**Comment by sandy081** [comment]
@isidorn If I am not wrong, User is complaining about the command `vscode.workspace.onDidCloseTextDocument()` and not about extension management. 

Please assign it to the corresponding owner

**Comment by akhilravuri1** [comment]
Hi,
If you want to clone the code and check it use this repo https://github.com/akhilravuri1/hellovscode.
Please create a vsix file and check this. With normal code, it works fine.
