### ISSUE TITLE
Proxy error - corporate proxy + extensions as of 1.37

### ISSUE THREAD

**Issue by willstocks-tech** [microsoft/vscode#79115]
- VSCode Version: 1.37
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Install Synthwave theme
2. Install Custom CSS and JS extension
3. Add the following to settings.json:
```js
  "vscode_custom_css.imports": [
    "https://raw.githubusercontent.com/robb0wen/synthwave-vscode/master/synthwave84.css",
    "https://raw.githubusercontent.com/willstocks-tech/synthwave-glow-plus-bracket-glow/master/brackets.css"
  ],
```
4. Reload CSS/JS and restart VSCode
5. Notice that none of the CSS is applied at all
6. Check network waterfall and notice that no requests were made out to resources
6. Download the exact same files and reference them locally instead
7. Notice they work perfectly and requests to resources are made

I use the "Custom CSS and JS" extension to apply the Glow effect to Synthwave '84. This had been working fine up until Monday, when I updated to VSCode 1.37.

Now I see the following error:
`[exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function`

And none of the external stylesheets load.

This laptop sits behind a corporate proxy, that is configured in windows `http_proxy` and `https_proxy` environmental variables.

I originally logged this via https://github.com/be5invis/vscode-custom-css/issues/89 but I assume this might actually be a Code issue, not so much a plugin issue?

Does this issue occur when all extensions are disabled?: tbc

**Comment by IllusionMH** [comment]
Extension that you've mentioned uses custom npm package to perform network requests
https://github.com/be5invis/vscode-custom-css/blob/master/src/extension.js#L6

And that package has long standing issue with env variables https://github.com/driverdan/node-XMLHttpRequest/issues/149

Most likely extension should be switched correct implementation.

**Comment by willstocks-tech** [comment]
Thanks @IllusionMH - I will re-raise it with them now!
