### ISSUE TITLE
Backspacing doesn't work in Markdown until extensions activate

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#79120]
Version: 1.38.0-insider (user setup)
Commit: ffa22b268f451b5211abbe2d2a47e6b753b55b1a
Date: 2019-08-13T07:27:53.993Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Open a markdown file in a new window
2. Type something - this works
3. Try to backspace something before extensions activate - nothing happens

Does this issue occur when all extensions are disabled?: No

I'd post a list of my extensions but I don't see an easy way to do that - is there a way to generate an extensions report? I have 34 of them so I'd rather not type them manually unless I have to.

**Comment by IllusionMH** [comment]
> I'd post a list of my extensions but I don't see an easy way to do that - is there a way to generate an extensions report? I have 34 of them so I'd rather not type them manually unless I have to.

You can report issues using **Help > Report Issue** that will provide list of extension and other system details (when you click submit it will navigate to Github with prepopulated issue report) or you can use `code --list-extensions` (or `code-insiders --list-extensions`).

> Does this issue occur when all extensions are disabled?: No

If it works correctly when all extensions are disabled you should enable them one-by-one to narrow it to single extension (or few of them).

/needsMoreInfo
