### ISSUE TITLE
tasks.executeTask should execute any task a provider can handle (through resolveTask)

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#79127]
Now that resolveTask is called on an task provider (see issue #53691), a task should be allowed to created and executed by an extension as long as the task provider can resolve the task.

Our scenario is as follows:
We have a set of "pre-canned" build tasks that our task-provider can return. Those pre-canned build tasks only execute builds one directory at a time.

However, our extension needs to have other UI entry points for build, such as right-click menus commands on a tree-view to invoke a build (as well as a few others). In those scenarios the number of directories to build would be more than a single directory.

It seems like it should be possible for the right-click menu commands to be able to create a task, with the proper type, and properties and call tasks.executeTask and have the task system call resolveTask to verify that the task provider can handle it. If it can, then the task should be executed.

This would also enable other extensions to potentially execute tasks from other providers which could be beneifical beyond our scenarios.

NOTE: This seems like it could be slightly related to #23144.

**Comment by GabeDeBacker** [comment]
@alexr00  - Turns out the only thing that was preventing this from working was a bug in the original implementation for a scenario that I had not tried until now.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/0e56130bdf2a4cb3f79f9ec4a52e480b4937149f
