### ISSUE TITLE
When debug session has just one thread, render this thread inline with the session itself

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79121]

**Comment by isidorn** [comment]
To verify have a simple node program to debug.
Start debugging it and hit a breakpoint.
Create a new launch config which also debugs another simple node program.
Start debugging it and hit a breakpoint.

Verify that in the call stack view you can see both debug sessions and their call stack. However the threads are not shown.

**Comment by pavelfeldman** [comment]
Happy to see this moving along. A couple of comments from my side:

- Don't render expansion control when there are no children!
    All my sessions have single thread and as a result, they are all expandable, but due to inlining, they are all empty upon expansion. 

- When there is only one top-level session, inline its children.
    As seen on the screenshot below, my launch configuration corresponds to a single 'root' session. Rendering that group "Web page 2" does not seem to be necessary.

- When the web page navigates between the URLs, its thread name changes. I'd be great to either allow session to be renamed or to render the thread name in the tree instead. I can force thread rename via removing and re-adding it back today.

![threads](https://user-images.githubusercontent.com/883973/63370329-cd358d80-c336-11e9-8e8c-57a5d5b04fe4.png)

**Comment by pavelfeldman** [comment]
One more:

- As I'm typing in console of a particular session, should a new session be created, it becomes active and steals the console from under me.

**Comment by pavelfeldman** [comment]
Another one:
- When my session has a child session and a thread, I still expect to see my only thread inlined. I.e. in my case `session === thread`. This does not seem to be the case today, session `blank` has a thread `localhost5002` and a child session `sw.js`:

![threads2](https://user-images.githubusercontent.com/883973/63392503-cffea580-c36b-11e9-9e19-cbb683d3c0ec.png)

At the same time, my expectations are:
- `localhost:5002` (session and thread)
  - `sw.js` (session and thread)
- `serve.js [51030]` (session and thread)

**Comment by isidorn** [comment]
@pavelfeldman thanks a lot for the great feedback. We usually prefer seperate new issues, but let's continue the discussion here and we can open new issues.

1. Expansion control when there are no children: currently we do this everywhere across VS Code (Explorer, Variables view, Watch Expression). If we were to change this we would have to fetch children even before the element gets expanded, just to know if he has any children or not. What we currently do is that the thread should not be shown as expandble if it is not stopped [here](https://github.com/Microsoft/vscode/blob/7621355f7e0c560dc30ad0c04f62d30bc1659b61/src/vs/workbench/contrib/debug/browser/callStackView.ts#L593). So the question for me is why the `Thread` in the model is marked as stopped when it is clearly running. I would need repro steps to investigate more here. 
2. This makes sense, I have just tackled this via 72803aaeee Previously we would always show the session if we were once in a mulit session view (and you go back to one session). Though always saving space makes sense and I like this change. Please note that in the debug toolbar we will still show the dropdown such that the user is aware that there were multiple sessions in the past and that he is left with just one.
3. This should already be possible. Similar issue #18244. Please try to send a [`ThreadEvent`](https://github.com/Microsoft/vscode/blob/72803aaeee7a80838f373de7854b6e5723e798e6/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L147) and as a `reason` set `new`. VSCode will ask you for all the threads and you just return with the updated names. And we should handle it nicely [here](https://github.com/Microsoft/vscode/blob/72803aaeee7a80838f373de7854b6e5723e798e6/src/vs/workbench/contrib/debug/browser/debugSession.ts#L617). Maybe we shuold just add a `reason` `"update"` just to make this more clear in the DAP @weinand 
4. Similar issue here https://github.com/microsoft/vscode/issues/77836 Let's continue the discussion there
5. This makes sense. I have just tackled this via b8ec1d7733

Thanks again for the feedback.

fyi @weinand

**Comment by isidorn** [comment]
4. Upon further investigation I have pushed 38aa476610 which should tackle this issue in your case. We were auto focusing the newly created session even if it was not stopped which was wrong. So I changed that, we no longer switch focus when a new session is created. However our approach remains that if a breakpoint is hit we will automatically focus on the coresponding session. Please try it out and let me know how it behaves. I would be interested to hear your feedback on our auto focus behavior when there are multiple threads / sessions. Thanks

**Comment by weinand** [comment]
I've verified that this works as discussed with two instances of a simple long-running node program:
```
setInterval(() => {
	console.log("tick");
}, 1000);
```

@isidorn What I find a bit surprising is the following:

If there are no breakpoints set, starting one debug session does not show anything in the CALLSTACK view. This is only mildly surprising because VS Code always behaved like this for single-threaded programs.

Starting the second debug session results in two sessions:
![2019-08-28_16-53-52](https://user-images.githubusercontent.com/1898161/63867013-6f4b1a80-c9b4-11e9-9b12-7b2351b9830f.png)

Terminating the second session makes both items disappear which gives the wrong impression that both sessions have terminated. It would be more intuitive if we would not optimise in the n-> 1 transition and continue to show a single session. This is a strategy that we are already using in other places.

**Comment by isidorn** [comment]
@weinand agree that that one is a bit of a bad corner case and that users might think that both sessions are gone.
We can go back to the previous behavior (not optimising the n->1 transition).

We could also introduce a new heuristic instead: if a session is running (has no threads) show it in the call stack view always. That way we would also tackle the first surprising scenario.

@weinand @pavelfeldman let me know what you think and which approach you prefer.

**Comment by pavelfeldman** [comment]
No strong preference here. I would still optimize for n -> 1 and see if there is any confusion / incoming bug reports.

My thinking here is that empty CALL STACK is not alarming since that's what most users saw when working with a single session / single thread anyways.
