### ISSUE TITLE
Remote SSH not working as of v1.37.0 (release) and 1.38.0-insider

### ISSUE THREAD

**Issue by rudycazabon** [microsoft/vscode#79123]
Up until Monday 8/12 the Remote-SSH extensions for both 1.37.0 and 1.38.0-insider worked.

After that date, it does not work.  I have tried Remote-ssh on release and nightly on both builds to troubleshoot and cannot pinpoint what change took place since that date that no longer allows the extension to work properly.

Please advise if additional information is required on my part.

Version: 1.38.0-insider (user setup)
Commit: ba69d8dcccaebbfaa94906503728eb7c3e45b9c1
Date: 2019-08-14T07:18:43.039Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. log on to remote machine and ensure that no previous vscode-insiders node servers are running
2. clear out by executing 'rm -rf ~/.vscode-insiders' directory
3. Launch VSCode Insiders 1.38.0 on Windows 10.0.17763
4. Install Remote-SSH (nightly)
5. Select remote server to log into
6. Examine remote logs for errors (none found)
7. Examine local VSCode terminal output and it reads as follows (my server IP hidden)

[15:14:33.013] remote-ssh-nightly@2019.8.19620
[15:14:33.013] win32 x64
[15:14:33.015] SSH Resolver called for "ssh-remote+<remote machine>", attempt 1
[15:14:33.015] SSH Resolver called for host: <remote machine>
[15:14:33.015] Setting up SSH remote "<remote machine>"
[15:14:33.041] Using commit id "ba69d8dcccaebbfaa94906503728eb7c3e45b9c1" and quality "insider" for server
[15:14:33.045] Testing ssh with ssh -V
[15:14:33.263] ssh exited with code: 0
[15:14:33.263] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[15:14:33.264] Running script with connection command: ssh -o ClearAllForwardings=true holmes.jf.intel.com bash
[15:14:33.266] Install and start server if needed
[15:14:33.674] > 
[15:14:33.675] Got some output, clearing connection timeout
[15:14:33.719] > The system cannot find the path specified.
[15:14:35.229] "install" terminal command done
[15:14:35.229] Install terminal quit with output: The system cannot find the path specified.
[15:14:35.230] Received install output: The system cannot find the path specified.
[15:14:35.230] Failed to parse remote port from server output: The system cannot find the path specified.
[15:14:35.230] 
[15:14:35.230] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":1,"retries":1}}
[15:14:35.230] ------

**Comment by roblourens** [comment]
What happens if you run `ssh -o ClearAllForwardings=true holmes.jf.intel.com` in a normal terminal?

What if you don't use the nightly version of the ssh extension?

**Comment by rudycazabon** [comment]
Greetings Rob - 

Thank you for your reply.

1. In a separate terminal (WSL, for example) if I execute `ssh -o ClearAllForwardings=true <my remote machine>` it enables me to log in without a hitch, no reported errors.

2. Per your request, if I use the standard/release extension (not nightly) for both 1.37 (release) and 1.38.0-insiders I am not able to get the VSCode Remote SSH to punch thru.  I get the same error as I reported initially.

Are there add'l troubleshooting steps that you recommend I should try out? I'm game to try anything at this point since this workflow worked wonderfully up until a few days ago.

Kind Regards,
Rudy Cazabon

**Comment by roblourens** [comment]
But what about a standard windows command prompt? We are not using wsl here.

Sorry about this issue, I just have no idea what 

> The system cannot find the path specified.

is referring to.

Have you installed any windows updates?

We are actually writing a script to your tmp folder and piping it into the ssh command. Maybe you don't have write access to your tmp directory? Have you tried rebooting?

**Comment by rudycazabon** [comment]
Hi Rob - 

1. I ran `ssh -o ClearAllForwardings=true holmes.jf.intel.com` from both Windows cmd prompt and Powershell ... no issues.

2. No Windows updates.  However, I uninstalled and revved my local version of Anaconda python.  I can't imagine what linkages might exist Anaconda and VSCode

3. I'm a little dense - by "writing a script in my tmp folder and piping it into the ssh command" ... I presume that you are referring to my server's /tmp dir or to my local client C:\temp directory?

4. Yeah, I've rebooted my server - no change in behavior

5. Is there anyway to get a trace/log of the actions that both the local/client Remote-ssh extension is doing?  The text in the terminal window just zooms by.

Kind Regards,
Rudy Cazabon

**Comment by roblourens** [comment]
3. I am referring to your local tmp dir. The path to that file is not logged but it should be something like ` C:\Users\username\AppData\Local\Temp\vscode-linux-multi-line-command...`

All the text in the terminal should end up in the logfile that you posted, which doesn't show much terminal text. What else are you seeing?

**Comment by rudycazabon** [comment]
Greetings Rob,

I finally narrowed down the issue.  Tho' I have not taken in Windows 10 updates, my OpenSSH (C:\Windows\System32\OpenSSH) bins are NOT playing nice with VSCode.

As a temporary measure I am using the SSH bins from Cygwin64 and these are enabling my local VSCode Insiders v1.38.0-insider (user setup) and the Remote-SSH (nightly) to work correctly.

I ask that you please consult your GMail as I attempted to contact you through there as I have other matters to discuss with you.

Regards,
rudy.cazabon@intel.com

**Comment by roblourens** [comment]
> As a temporary measure I am using the SSH bins from Cygwin64 and these are enabling my local VSCode Insiders v1.38.0-insider (user setup) and the Remote-SSH (nightly) to work correctly.

Great! I have no idea what the issue with OpenSSH would be but please update me if you learn anything else.
