### ISSUE TITLE
Big Error

### ISSUE THREAD

**Issue by wllfoxe13** [Microsoft/vscode#7912]
- VSCode Version:1.2.1
- OS Version:Win10-10586
Steps to Reproduce:
SQLite :https://www.sqlite.org/download.html
SQLite Soure Code  sqlite3.c Error.....

**Comment by wllfoxe13** [comment]
Big File Error...

**Comment by dbaeumer** [comment]
@wllfoxe13 what exactly causes a Big File Error. Can you please provide additional steps.

**Comment by xenopeg** [comment]
I'm assuming that by "Big File Error" it was something related to the size of the "sqlite3.c" from SQLite's source code.

I tried opening it and indeed VSCode crashed soon after while highlighting the code.

**Comment by dbaeumer** [comment]
@xenopeg @wllfoxe13 do you have any C/C++ extensions installed.

**Comment by xenopeg** [comment]
No extensions installed, using the Insiders build.

**Comment by dbaeumer** [comment]
Them marking as important since we shouldn't crash.

**Comment by alexandrudima** [comment]
With vscode-textmate@2.0.1 on the first 10k lines of sqllite3.c

BEFORE:
![image](https://cloud.githubusercontent.com/assets/5047891/16515250/3178550e-3f71-11e6-9b85-3c11a7c58963.png)

AFTER:
![image](https://cloud.githubusercontent.com/assets/5047891/16515263/487b5f3a-3f71-11e6-9a35-4e75635ef303.png)

[AFTER-Heap-20160701T094643.zip](https://github.com/Microsoft/vscode/files/343038/AFTER-Heap-20160701T094643.zip)
[BEFORE-Heap-20160701T094538.zip](https://github.com/Microsoft/vscode/files/343039/BEFORE-Heap-20160701T094538.zip)

**Comment by alexandrudima** [comment]
Ok, with vscode-textmate@2.0.1 we don't crash when opening sqlit3.c:

![image](https://cloud.githubusercontent.com/assets/5047891/16517687/24859330-3f7f-11e6-98cc-078f06721e82.png)

I will create a separate issue to investigate why the C grammar pushes states and does not pop them for this file.
