### ISSUE TITLE
Folder in workspace not showing files underneath it

### ISSUE THREAD

**Issue by penguin2839** [microsoft/vscode#79134]
Issue Type: <b>Bug</b>

When using a workspace I have a folder that doens't show files underneath it when I expand the folder. The files exist on the file system and i can manually open the file using file->open file. 

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vmlxrndckt02|
|OS|Linux x64 3.10.0-957.10.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (2 x 2593)|
|Memory (System)|3.84GB (0.23GB free)|
|VM|100%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
python|ms-|2019.8.30787

</details>

**Comment by gjsjohnmurray** [comment]
My guess is, you have a `files.exclude` setting that's making those files be hidden in Explorer.

**Comment by gjsjohnmurray** [comment]
See https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code

**Comment by penguin2839** [comment]
I don’t appear to have a files.exclude setting applied.

**Comment by gjsjohnmurray** [comment]
So maybe #78743 which will be fixed in the upcoming 1.37.1 recovery release.
