### ISSUE TITLE
c# arrays are not highlighted

### ISSUE THREAD

**Issue by AllanDouglas** [microsoft/vscode#79135]
after the latest update
highlights don't work to array when it've [SerializeField] 
![image](https://user-images.githubusercontent.com/16799200/63044231-25d2d980-bea4-11e9-839e-961364b75547.png)

**Comment by alexr00** [comment]
Can you disable all extensions and try? I can't repro in 1.37.0

```C#
public class Test
{
    [SerializeField] private GameObject finalObjectPrefab;
    [SerializeField] private ShapeRecipe[] shapes;

    private void Fine()
    {
        int x = 0;
    }
}
```
<img width="396" alt="csharp" src="https://user-images.githubusercontent.com/38270282/63085380-af8ab180-bf4d-11e9-80a3-44b75895abb6.png">

**Comment by AllanDouglas** [comment]
oH, it is so obvious.
tks :D
Is all ok now, sorry about that.
