### ISSUE TITLE
Pressing tab in a PHP file inserts an XML tag

### ISSUE THREAD

**Issue by nevadascout** [Microsoft/vscode#7913]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. Type a variable in a PHP file
2. Put your cursor at the end of the variable
3. Press tab

![php-tab-xml](https://cloud.githubusercontent.com/assets/377089/16222036/ee598760-378d-11e6-818b-353950e960e1.PNG)

**Comment by mrqtsfr** [comment]
Same in:

VSCode Version: 1.2.1
OS Version: Windows 10

**Comment by dbaeumer** [comment]
@aeschli do you know of anything special we are doing here?

**Comment by aeschli** [comment]
It's emmet.

**Comment by mrmlnc** [comment]
@egamma,

Maybe do as plugin for Sublime Text?

> `disable_tab_abbreviations_for_scopes` — a comma-separated list of syntax scopes where Tab key handler should be disabled. For example, if you want disable handler inside strings of programming languages and HAML syntax, your setting will look like this:
> ```
> "disable_tab_abbreviations_for_scopes": "text.haml, string"
> ```

https://github.com/sergeche/emmet-sublime#tab-key-handler

**Comment by mjbvz** [comment]
Yes, this is emmet (same problem as #13578). To disable this behavior, add the following setting:

```json
"emmet.excludeLanguages": ["php"]
```

**Comment by mjbvz** [comment]
Looks like php is still acting up. The above approach works for `'markdown'` and other emmet enabled languages but after adding `"php"` to `emmet.excludeLanguages `, I'm still seeing this behavior

**Comment by ramya-rao-a** [comment]
_From @zackote_

1. Open file with syntax set to php.
2. Type `php`, and press `Tab` to expand with Emmet

Expanding the string `php` with Emmet produces `<php></php>` instead of the far more helpful `<?php ?>`. I believe Sublime, Atom, etc. all address this and the `<?php ?>` expansion occurs.

**Comment by mrmlnc** [comment]
Well, confirm. `emmet.excludeLanguages` does not work any more 😢

**Comment by ramya-rao-a** [comment]
@mrmlnc You mentioned here https://github.com/Microsoft/vscode/issues/12325#issuecomment-248398440 that emmet should work for PHP in VS Code now. 
Did you mean that xml expansion works in php files or php expansions should work in php files?

**Comment by mrmlnc** [comment]
I mean, that when I point out `php` in `emmet.excludeLanguages` Emmet continues to work in php.

![2016-11-17_01-43-48](https://cloud.githubusercontent.com/assets/7034281/20368935/585c4e42-ac67-11e6-9a94-673f923f9f68.gif)

But if I point out `html` Emmet doest now work:

![2016-11-17_01-44-48](https://cloud.githubusercontent.com/assets/7034281/20368948/70ac429a-ac67-11e6-825c-d75171682595.gif)

Something broke. I'll take a look today or tomorrow.

**Comment by ramya-rao-a** [comment]
@mjbvz just found that the exclusion works if you are inside the <?php ?> block.

**Comment by ramya-rao-a** [comment]
@mrmlnc At the moment `php` is not one of the supported modes for emmet correct?

As in I cannot expect  `this>Form>data.Encode` to expand to `$this->Form->data['Encore']`

**Comment by mjbvz** [comment]
Yes, I did actually test this before closing this the other day :) but forgot that adding `"php"` to excluded languages only disables emmet inside of `<?php?>` blocks, and not within the whole file:

![nov-16-2016 14-49-11](https://cloud.githubusercontent.com/assets/12821956/20369059/d7dcc72a-ac0b-11e6-9b83-f1749fbb69a1.gif)


Closing this again

**Comment by mrmlnc** [comment]
> just found that the exclusion works if you are inside the <?php ?> block.

Yes, you right. I think that sooner VS Code defined region differently.

**Comment by mrmlnc** [comment]
> At the moment php is not one of the supported modes for emmet correct?

My apologies again. Now VS Code determines scopes of languages a little differently.

> As in I cannot expect `this>Form>data.Encode` to expand to `$this->Form->data['Encore']`

As far as I know, Emmet does not work with PHP. Because Emmet has no code for this (https://github.com/emmetio/emmet/search?utf8=%E2%9C%93&q=php) 😄.

**Comment by ramya-rao-a** [comment]
Thanks @mrmlnc
