### ISSUE TITLE
User input isn't cleared from the terminal before running debugger causing issues

### ISSUE THREAD

**Issue by Anapo14** [microsoft/vscode#79136]
- VSCode Version: Any version
- OS Version: Windows 

When I run a python file by debugging the first time, even if I accidentally type something into the terminal and run the file again, I'd expect the terminal to clear my input and run the debugger without problems.

Steps to Reproduce:

1. Create any tester python project.
2. write some code. 
3. Run the code using the debugger. (select a default debug configuration).
4. Now, write something into the terminal in which the code was executed.
5. run the code via the debugger again.

Here's what happens: 
![image](https://user-images.githubusercontent.com/10341823/62975350-08800b80-bdcf-11e9-8d74-40cc91eb7bd2.png)

Filed an issue on the python extension [here](https://github.com/microsoft/vscode-python/issues/6958), but they closed it and said that vs code controls the terminal.

**Comment by isidorn** [comment]
I have commented on the issue in the python repository
