### ISSUE TITLE
status bar goes blank if text field is too long

### ISSUE THREAD

**Issue by thomaspugliese** [microsoft/vscode#79140]
Issue Type: <b>Bug</b>

If an extension puts text in a status bar field that is too long, the entire status bar goes blank.  Ideally, the text should either be truncated or there should be some way to communcate to the extension the size of the field so that it can decide what to do with the text.

Related issue for git-blame extension:

https://github.com/Sertion/vscode-gitblame/issues/60

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_225335|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|0.5.0
gitlens|eam|9.9.3
vscode-sshfs|Kel|1.16.3
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.24.1
tcl|sle|0.2.0
gitblame|wad|3.0.1

</details>

**Comment by bpasero** [comment]
Yeah, we have no good overflow solution. 

/duplicate https://github.com/microsoft/vscode/issues/6651
