### ISSUE TITLE
Caching/prefetching remote webview vscode-resources

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#79147]
We have some fairly large javascript bundles (~10-20 MB with sourcemaps added) which we include in some of our webviews. These views run remotely because they communicate with remote extensions (which perform things like file search and version control).

However currently initial load takes a very noticeable amount of time when opening the webview. I traced code to find it's all spent on a remote filesystem read operation.

Request:
I'd like for workspace extension to be able to either:

1) (ideal) declare resources that should be pre-fetched when running remotely, so initial javascript load is instant
2) have a mechanism to cache vscode-resources so they don't need to be re-downloaded on each open (e.g. by setting `?cache=true` on the URI)

Here's an example patch that does a very simple caching and makes resource reloading much faster (option 2 above):
```
diff --git a/src/vs/workbench/contrib/webview/common/resourceLoader.ts b/src/vs/workbench/contrib/webview/common/resourceLoader.ts
index ea33db2e26..74a905be71 100644
--- a/src/vs/workbench/contrib/webview/common/resourceLoader.ts
+++ b/src/vs/workbench/contrib/webview/common/resourceLoader.ts
@@ -7,7 +7,7 @@ import { VSBuffer } from 'vs/base/common/buffer';
 import { sep } from 'vs/base/common/path';
 import { startsWith, endsWith } from 'vs/base/common/strings';
 import { URI } from 'vs/base/common/uri';
-import { IFileService } from 'vs/platform/files/common/files';
+import { IFileService, IFileContent } from 'vs/platform/files/common/files';
 import { REMOTE_HOST_SCHEME } from 'vs/platform/remote/common/remoteHosts';
 import { getWebviewContentMimeType } from 'vs/workbench/contrib/webview/common/mimeTypes';
 
@@ -25,14 +25,20 @@ const AccessDenied = new class { readonly type = 'access-denied'; };
 
 type LocalResourceResponse = Success | typeof Failed | typeof AccessDenied;
 
+const cache: Map<string, Promise<IFileContent>> = new Map();
+
 async function resolveContent(
 	fileService: IFileService,
 	resource: URI,
 	mime: string
 ): Promise<LocalResourceResponse> {
 	try {
-		const contents = await fileService.readFile(resource);
-		return new Success(contents.value, mime);
+		let contentsPromise = cache.get(resource.toString());
+		if (contentsPromise === undefined) {
+			contentsPromise = fileService.readFile(resource);
+			cache.set(resource.toString(), contentsPromise);
+		}
+		return new Success((await contentsPromise).value, mime);
 	} catch (err) {
 		console.log(err);
 		return Failed;

```

**Comment by pelmers** [comment]
Another idea I want to bring up for discussion (cc @mostafaeweda, @kcaze) that more closely matches our use case and is even more ideal than option 1 above:

Because we know in advance that the required Javascript code already exists on our users' client, ideally we could present a `vscode-local-resource` or similar scheme that could define a client-side absolute path (therefore skipping file download altogether).

**Comment by mjbvz** [comment]
This is a reasonable request but requires careful thought. 

The first proposal is more in the right direction. We don't want to introduce further dependencies on custom protocols any anything electron specific as they will not work on the web. It'd also be nice if we could internally make use of existing http mechanisms like etags here

**Comment by solomatov** [comment]
@mjbvz I would be happy to work on this. How do you think should I start? Do you have any suggestions?

**Comment by solomatov** [comment]
@mjbvz I've taken a look at how it all works. Here's my thoughts:
- FS API is already has support for etags. Can I just use it, or is there any more work have to be done?
- It's not a good idea to store a number of cached files in memory, so I will need to store them somewhere on the disk. Will sqlite work for this (you already have deps for it).

If I implement this the way described, will you accept it? If not, could please tell me what need to be changed?

**Comment by mjbvz** [comment]
As a first step, I think we should target supporting caching in a single webview session. The markdown preview is a good example use case: it creates a webview and then updates the webview's html whenever the user modifies the markdown file.

Here's what that could look like:

1. The first time we need to load a resource, we always load it fully. 
1. Once it is loaded, we ensure the request is cached using standard http/browser stuff
1. After this, subsequent requests for the same resource should attach an `etag`. Our implementation of the resource loading should check this `etag` again file system to know if we need to reload the resource or not.
1. In the majority of cases, the resource should not have changed, so we should not need to reload it and the client can use its cached version

In the future, we can worry about caching resources across different webview sessions. This would likely using a service worker (we already use service workers for loading resources on web versions of VS Code and wish to switch to using one on desktop too)

**Comment by solomatov** [comment]
Created a PR. 


P.S. I don't like that I had to create a global variable for cache, but there's no other place to put it.

**Comment by solomatov** [comment]
@mjbvz So, it seems that my commit didn't do what you wanted. Could you please suggest what should be changed? Should I create a service worker for this?

**Comment by solomatov** [comment]
@mjbvz I see what you mean. There's a service worker for each webview, and we should use it for caching. Will think about it and create a new PR.

**Comment by solomatov** [comment]
@mjbvz I found your blog post which is very useful https://blog.mattbierner.com/vscode-webview-web-learnings/

**Comment by mjbvz** [comment]
So after looking over this, I'm not sure we can get normal web caching to work on the current versions of VS Code. The issue is that we use electron's [`registerBufferProtocol`](https://electronjs.org/docs/api/protocol) function to implement the loading of local resources, but as far as I can tell there is no way to actually set the headers on the response.

On web, we instead use a service worker to load local content. #83188 tracks switching desktop VS Code to use them as well but there are a few upstream electron blockers for this. However I think it's worth targeting the fix to the service worker based approach since that is where we want to move longer term.

**Comment by solomatov** [comment]
@mjbvz So what do you think should we do? What do you think adding caching to the service worker, and adding a temporary solution like in the PR? 

Also, do I understand correctly that service workers aren't currently working in the electron? (My impression is that in the blog post you mention that service workers are used everywhere).

**Comment by mjbvz** [comment]
No, service workers on only used on the web at the moment.

For your PR:

* Change to target caching for service workers since that is the approach we want to use long term.
* (possibly) Update your existing PR to cache resources for each webview, not globally. This would be a temporary fix until service workers are used everywhere

**Comment by solomatov** [comment]
@mjbvz 
- If we talk about local cache for webview, will we be able to get cached versions if the webview is opened and closed again?
- Will it be ok if I created 2 PRs (I wanted to learn about service workers, and I will be happy to create a PR for them)

Also, about PRs, is there a way to debug service workers in Electron? I see them in the web version in the Chrome dev tools, but I haven't managed to invoke them in vs.code.

**Comment by solomatov** [comment]
@mjbvz So, another place where I can put caching is in webviewProtocol.ts. But a new closure is created for each instance of the webview, even if it's the same kind of webview, so caching would be much less useful here for us.

What do you think? Should I put it into another place?

**Comment by mjbvz** [comment]
That sounds good. I explicitly do not want VS Code to maintain a global resource cache itself. I understand this is not what the original request is asking for but we don't want to get into the business of caching things as it is complicated

**Comment by solomatov** [comment]
@mjbvz From the debugger I see that this thing is called again for every new webview created (I opened png images). So, this won't work. Do you know any other way to do the same?

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/pull/115360 uses etags to cache loading of resources on disk that have not changed. No plans to support preloading resources right now
