### ISSUE TITLE
Duplicated code/strings for registerConfiguration

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#79144]
Issue Type: <b>Bug</b>

In the vscode code base, regex search for:
```
registerConfiguration\(\{[\s\n]+'id': 'workbench'
```

**Bug**
Notice that there are multiple places where we have copy/pasted:

```ts
registry.registerConfiguration({
	'id': 'workbench',
	'order': 7,
	'title': localize('workbenchConfigurationTitle', "Workbench"),
	'type': 'object',
...
```

If possible, we should avoid duplicating the `order` and `title` for these contributions.

VS Code version: Code - Insiders 1.38.0-insider (ba69d8dcccaebbfaa94906503728eb7c3e45b9c1, 2019-08-14T07:16:06.583Z)
OS version: Darwin x64 18.6.0

**Comment by sandy081** [comment]
Corresponding area owners should defined id and title for reuse.

**Comment by mjbvz** [comment]
Perhaps another option would be to spit the api so that callers only need to know the id of the section they are registering config for:

```ts
registry.registerConfigurationSection({
	'id': 'workbench',
	'order': 7,
	'title': localize('workbenchConfigurationTitle', "Workbench"),
});

registry.registerConfiguration('workbench', { ...properties })
```

**Comment by sandy081** [comment]
I am sorry that I have no plans to do this. PR would be always welcome here.
