### ISSUE TITLE
Extension update/install bug(Needs to be downloaded manually)

### ISSUE THREAD

**Issue by ParrotStone** [microsoft/vscode#79145]
The way to generate the bug is to try to install a new extension or update an existing one. The update/install will fail and would suggest to download the extension manually. The extension started to appear since the last update of (July 2019). Expected result is to update/install normally without the need to download the extension manually.
   
![Screenshot from 2019-08-14 23-54-54](https://user-images.githubusercontent.com/50120710/63059176-fd240180-beee-11e9-88ab-0da139e7f493.png)

**Comment by gjsjohnmurray** [comment]
Are you willing to install the [Insiders build of VSCode](https://code.visualstudio.com/insiders/) alongside your current version? If yes, can you add extensions to it?

**Comment by ParrotStone** [comment]
No. I'm not. I'm sorry what's the difference between the Insiders build and normal one.

**Comment by gjsjohnmurray** [comment]
It gives you early access to fixes that will come in the next release. You can run it alongside the standard release, no problem.

**Comment by ParrotStone** [comment]
When will the next release come out?

**Comment by gjsjohnmurray** [comment]
Target is early September. See #78844

**Comment by gjsjohnmurray** [comment]
See #78783 for info about how others have tracked this problem down to a DNS issue.

/duplicate
