### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by tritonlmk** [microsoft/vscode#79148]
software running very slow, switching between tags(different files) can take for seconds.

**Comment by 5201314999** [comment]
I have the same experiance,when I switch to use other application and then go back to vscode，the interface  take seconds to response ,By the way，I use the window，my version is 1.37.0 ,and I open 10 projects。

**Comment by 5201314999** [comment]
It makes the bad experience

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please read https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by 5201314999** [comment]
now I only open 3 projects and it is very fast
