### ISSUE TITLE
The light theme still black (the left panel)

### ISSUE THREAD

**Issue by netroby** [microsoft/vscode#79158]
I set the vscode theme to light. but the left panel still black.
![QQ截图20190815134527](https://user-images.githubusercontent.com/278153/63075156-42821680-bf63-11e9-9941-63018674ef3c.png)

**Comment by YangHanlin** [comment]
The left panel is black because it is designed that way. If you'd like to see a white left panel, you can try another light theme from the marketplace.

**Comment by gjsjohnmurray** [comment]
> The left panel is black because it is designed that way. If you'd like to see a white left panel, you can try another light theme from the marketplace.

Or try Quiet Light which seems to be a built-in one.
