### ISSUE TITLE
empty folder shows in explorer when some link in the folder fail

### ISSUE THREAD

**Issue by kjkszpj** [microsoft/vscode#79159]
We have written the needed data into your clipboard because it was too large to send. Please paste.

i have a folder name abc, which contain 2 file name A & B

A is a wrong soft link to another file
B is a normal file

and then abc show empty in the explorer,(unexpected, abc have B, but not show in explorer)
when i delete the wrong link, abc appear as a non empty folder

expected: abc show as non empty all the time, no matter the link fail or not

**Comment by gjsjohnmurray** [comment]
Probably #78743 which is fixed in the imminent July Recovery release
