### ISSUE TITLE
Crash/not responding after Filesearch in big Project

### ISSUE THREAD

**Issue by hummervee** [Microsoft/vscode#7915]
Every Time I use the file search (F1 -> enter Filename) the Editor starts lagging and stop responding a while later (maybe half an hour, sometimes longer) and forces me to restart after "not responding"-message.

- VSCode Version: 1.2.1 
- OS Version: Win10 
- current Project: ~148.000 Files,  ~25.000 Folders

Steps to Reproduce:

1. "Open Folder" of big Project
2. Search for files and open them (F1)
3. after a longer Time (upwards of 15min) window stops responding

**Comment by bpasero** [comment]
@hummervee you say you use F1 but this is the command palette. Can you share screenshots what you do?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by hummervee** [comment]
Hi, sry I overlooked your question.

"@hummervee <https://github.com/hummervee> you say you use F1 but this 
is the command palette. Can you share screenshots what you do?"

Yes I use the command palette, to look for filenames due to the size of 
the Project. For this I delete the ">"-sign and start typing the filename.

Hope this helps.


Am 28.06.2016 um 16:43 schrieb Benjamin Pasero:

**Comment by hummervee** [comment]
To clarify, the editor not only gets really slow, it completely stops responding, meaning I get an errormessage saying the window is not responding (vs-code message, not windows message) and need to restart. Your workaround might fix this, but it doesnt take away the fact that a long time after I used the search, the editor seems to be indexing a huge amount of files to the point it stops responding.

**Comment by hummervee** [comment]
Hey,

My friends just have been talking about that stuff all day long, you may like it too. More info here  <http://tyspitigu.barceloscoffeecompany.com/e2sihwd>

Hugs, Electronic Sports League

**Comment by hummervee** [comment]
Hello,

It is amazing what one can invent! You're gonna love it, I swear! Read more  here  <http://favor.istevenicholl.com/e2ldzbde>

Yours truly, Electronic Sports League

**Comment by hummervee** [comment]
Hey friend, 

I just wanted  to tell you about a beautiful place I've visited recently, I met a lot  of amazing people there. please  read more about  it here <http://resource.bloodskin.com/e5jcxye>

Jan B.

767

**Comment by hummervee** [comment]
Hey! 

It  is amazing what one can invent! You're gonna love it, I swear! Read more here <http://riziquizi.beckylane.com/e5oxahmh>

Diablo III

**Comment by hummervee** [comment]
Hello friend, 

I've suddenly came  sccross that information and thought it may  be useful for you, read more  here please <http://gethonacro.cyrussoftware.com/e2illwkl>


RuneScape

**Comment by hummervee** [comment]
Hey, 

I've seen something really awesom recently and wanted to share this info with you. Here, take a look  <http://connect.victorconsultingsystems.com/e6me/0>

Warm regards, RuneScape
