### ISSUE TITLE
forward ports: click Forward, no input show.

### ISSUE THREAD

**Issue by simpleLin** [microsoft/vscode#79151]
Issue Type: <b>Bug</b>

click Forward, no input show.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.159.218.226|
|OS|Linux x64 4.15.0-20-generic|
|CPUs|Westmere E56xx/L56xx/X56xx (Nehalem-C) (8 x 2497)|
|Memory (System)|15.66GB (8.99GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.37.5
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
debugger-for-chrome|msj|4.11.7
vscode-icons|vsc|9.2.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-jest-runner|fir|0.3.11
vscode-typescript-tslint-plugin|ms-|1.2.2
gulptasks|nic|1.3.1
vscode-jest|Ort|3.0.2
remote-vscode|raf|1.1.0

</details>

**Comment by isidorn** [comment]
Please provide more information liek reproducable steps. With the current description we can not do anything.
