### ISSUE TITLE
toggle block comment cursor place

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode#79156]
- VSCode Version: 1.37.0
- OS Version: Ubuntu 1804 LTS

Steps to Reproduce:
**It's not exactly a bug**
When using key shortcuts `toggle comment block` which is `Shift + Alt + A` on Windows platform, 

I get `/* | */` with the cursor "|" in the middle of it, and when I want to type comment blocks like 
```
/**
  *
  *
  *
  */
```
I'll have to press `Backspace` key , then type `*` and press `Enter` key to get the comment block.

---------------

but if we put the cursor "|" just after `/*`, like `/*|  */`, I don't have to press `Backspace` key, I would just type `*` and press `Enter`, and voila, the comment block.

--------------------

All in all, it's just about the whitespace and convenience. 
So, what I'm asking is whether we could place the cursor "|" just after the `/*` like `/*|  */` so that I don't have to press `Backspace` key to get a comment block?

**Comment by NewtMa** [comment]
@gjsjohnmurray sorry for the delay, just updated.

**Comment by gjsjohnmurray** [comment]
@NewtMa can you add a screen recording to show what you mean? Or a sequence of annotated screenshots?

/confirmationPending

**Comment by NewtMa** [comment]
@gjsjohnmurray I just updated the description with detailed steps.

**Comment by gjsjohnmurray** [comment]
@NewtMa thanks for clarifying what you want. But if this gets changed, when someone wants to write an actual comment they will now have to type an extra space character so it doesn't start right next to the * ?

**Comment by IllusionMH** [comment]
@NewtMa if you want to quickly get JSDoc comment you can actually type `/**|` and it will convert it to `/**| */`  (`|` is cursor position). If you then press <kbd>Enter</kbd> it will create params list for you if it is before the function.
![image](https://user-images.githubusercontent.com/1312662/63158199-65730000-c021-11e9-8faa-3defdbaabd77.png)
