### ISSUE TITLE
Do not close open editors when add folder to workspace

### ISSUE THREAD

**Issue by Mingun** [microsoft/vscode#79167]
When you have some open files and/or some unsaved buffers in VS Code and you try to add some folder to projects area for quick access to files, VS Code try close all opened files/buffers, that is unnecessary.

At least must be option to keep files open

**Comment by isidorn** [comment]
I can not reproduce this.
When I add a new fodler to the workspace the open editors list is preserved.
Please let me know what you are doing differentely and if you can reproduce it with vscode insiders https://code.visualstudio.com/insiders/

![hello](https://user-images.githubusercontent.com/1926584/63088519-72c2b880-bf55-11e9-8a1a-6285936bb995.gif)

**Comment by Mingun** [comment]
Try when you do not have any folder open

**Comment by isidorn** [comment]
Yeah that is designed behavior which we will not change.
Our ux state is preserved per workspace, and when you move from no folder to folder the whole ux state is not preserved not only open editors.
Closing as designed.

**Comment by Mingun** [comment]
I do not see the reasons why this behavior should be expected. You showed that in the presence already though any open folder the state is not reset. Why it is reset when opening the first folder? Than transition `0->1` open folders differs from `n->(n+1)` open folders? I opened the editor for the first time, opened a lot of files and I want to see them in the file system, and you suggest me to close everything and to begin with the beginning. It is possible to implement at least the setup changing this behavior?

**Comment by isidorn** [comment]
@bpasero do we have some issue how the ux state is not preserved when going from 0->1? So the user can upvote it and comment there.

**Comment by bpasero** [comment]
This is a bit inconsistent, when you drop a folder onto the explorer we could maybe ask what to do.

**Comment by bpasero** [comment]
@Mingun can you please give a step by step explanation how you add a folder to the empty window?

**Comment by Mingun** [comment]
First I have VS Code with some files (and some temporary unsaved buffers, that contains information, that I do not wont to save, but right now I need it, but in this screenshot such buffers is missed, because this is just illustrate):
![1  VS Code without folders](https://user-images.githubusercontent.com/450131/63121934-13998e00-bfbf-11e9-8fae-4ab9d6abcdf3.png)
After then I open folder and all my opened files is closed, and unsaved buffers discarded:
![2  After open folder](https://user-images.githubusercontent.com/450131/63121935-14322480-bfbf-11e9-8a62-8f0d45a5e1d7.png)

I want to keep them opened.

**Comment by bpasero** [comment]
@Mingun got it. To prevent the window from reloading you could use our multi-root workspace feature and do File > Add Folder to Workspace. https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by Mingun** [comment]
Thanks, @bpasero, that what I need. How about add button with this action under button "Open Folder" (and add tooltips explaining, what each button do)?
