### ISSUE TITLE
files.eol == LF breaks settings on latest insiders build

### ISSUE THREAD

**Issue by studoot** [microsoft/vscode#79164]
Issue Type: <b>Bug</b>

The following setting appears to break settings for vscode-insiders, 15th August 2019, yielding an error popup with the message "Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again."

```json
  "files.eol": "\n"
```

This worked as expected (the settings loaded, saved and were used by vscode-insiders) prior to today, and is the setting written by the VSCode settings panel when 'LF' is selected in for line endings.

VS Code version: Code - Insiders 1.38.0-insider (44a48f75d64333b8e33a1fe4f57f6a60553b1e6b, 2019-08-15T05:25:12.451Z)
OS version: Windows_NT x64 10.0.18956

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
insertnumbers|Asu|0.9.1
spellright|ban|3.0.46
language-gas-x86|bas|0.0.1
markdown-preview-github-styles|bie|0.1.6
head-file-guard|bjr|0.0.2
better-toml|bun|0.3.2
cmake-format|che|0.4.2
transformer|dak|1.6.0
arm|dan|0.5.0
vscode-dash|dee|2.2.0
githistory|don|0.4.6
gitlens|eam|9.9.3
permute-lines|ear|0.0.10
EditorConfig|Edi|0.13.0
ada|Ent|0.88.0
shell-format|fox|6.1.1
bettercomment|Gru|0.0.8
beautify|Hoo|1.5.0
vscode-wsl-workspacefolder|lfu|1.1.2
calculator|lix|0.1.1
vscode-antlr4|mik|2.1.1
python|ms-|2019.8.30787
remote-containers|ms-|0.67.4
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.3
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.25.0-insiders
Go|ms-|0.11.4
powershell|ms-|2019.5.0
material-icon-theme|PKi|3.8.1
text-power-tools|qcz|1.11.1
rust|rus|0.6.1
partial-diff|ryu|1.4.0
crates|ser|0.4.3
code-settings-sync|Sha|3.4.1
rewrap|stk|1.9.1
code-spell-checker|str|1.7.17
shellcheck|tim|0.8.1
pdf|tom|0.5.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
stylish-haskell|vig|0.0.10
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by studoot** [comment]
Addendum: it's not as simple as files.eol == LF - removing some comments seems to make code happy, removing some other settings does it... I've attached my (zipped) settings, anyway.

[settings.zip](https://github.com/microsoft/vscode/files/3504635/settings.zip)

**Comment by JiangJie** [comment]
#79162
