### ISSUE TITLE
Error: Invalid guestInstanceId: null 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79165]
This is our second highest crash according to error telemetry:

```
Error: Invalid guestInstanceId: null
at Object.getGuestForWebContents ( Studio :430:11)
at Studio :449:34
at EventEmitter.ipcMain.on.args ( Studio :278:21)
at EventEmitter.emit (events.js
at WebContents. ( Studio :370:21)
at WebContents.emit (events.js
```

https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=3c3c607b-2dd3-f1f6-02b1-33a1c84e0871

**Comment by mjbvz** [comment]
Looks like these are all in 1.36?

![Screen Shot 2019-08-15 at 10 03 30 AM](https://user-images.githubusercontent.com/12821956/63112086-26bb4800-bf44-11e9-9beb-dc12af5654bb.png)

Based on the call stack, I'm also not 100% sure if this is webview or not

**Comment by bpasero** [comment]
I have seen this issue a lot of times over many past versions but it could well be an Electron issue.

**Comment by mjbvz** [comment]
Closing this as potentially fixed. I quickly looked through the current error telemetry and did not see it occurring in more recent builds

**Comment by deepak1556** [comment]
We have a potential repro for this error now https://github.com/microsoft/vscode/issues/80296, will try to isolate the electron issue.
