### ISSUE TITLE
TypeError: Cannot read property 'style' of null 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79166]
```
TypeError: Cannot read property 'style' of null
/vs/base/browser/ui/sash/sash.ts#353:11 (layout)
/vs/editor/contrib/zoneWidget/zoneWidget.ts#281:19 (_onViewZoneHeight)
/vs/editor/contrib/zoneWidget/zoneWidget.ts#403:29 (_onComputedHeight)
/vs/editor/contrib/zoneWidget/zoneWidget.ts#79:7 (onComputedHeight)
/vs/editor/browser/viewParts/viewZones/viewZones.ts#290:9 (_safeCallOnComputedHeight)
/vs/editor/browser/viewParts/viewZones/viewZones.ts#78:9 (_recomputeWhitespacesProps)
/vs/editor/browser/viewParts/viewZones/viewZones.ts#102:26 (onLineMappingChanged)
/vs/editor/common/viewModel/viewEventHandler.ts#133:14 (handleEvents)
/vs/editor/common/view/viewEventDispatcher.ts#88:21 (_doConsumeQueue)
/vs/editor/common/view/viewEventDispatcher.ts#71:9 (func)
/vs/editor/browser/view/viewImpl.ts#580:9 (safeInvokeNoArg)
/vs/editor/browser/view/viewImpl.ts#357:12
at i.eventDispatcher.O.ViewEventDispatcher.e [as _eventHandlerGateKeeper] (out/vs/workbench/workbench.ma
```

https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=6bd2c005-6bb5-6695-ea28-90153d25a6ba

**Comment by bpasero** [comment]
It looks like [`_onViewZoneHeight`](https://github.com/Microsoft/vscode/blame/master/src/vs/editor/contrib/zoneWidget/zoneWidget.ts#L273) is actually being called even though the view zone is already disposed (and thus the sash). 

There is a `ViewZoneDelegate` which does not seem to be disposable but still has a event like interface. Looks fishy.

**Comment by alexandrudima** [comment]
`ZoneWidget` first disposes the sash via some newly introduced `DisposableStore` which is shared with child classes... and only later removes the view zone from the editor.

It is possible that one of the disposables in the `DisposableStore` uses editor API which results in the line mapping being changed which will invoke the view zone callback if the view zone is not removed.
