### ISSUE TITLE
vscode-insider 1.38.0-insider can not load setting.json, but my setting.json file is not error

### ISSUE THREAD

**Issue by SanJin-hx** [microsoft/vscode#79162]
`
Version: 1.38.0-insider (user setup)
Commit: 44a48f75d64333b8e33a1fe4f57f6a60553b1e6b
Date: 2019-08-15T05:25:12.451Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
`
![image](https://user-images.githubusercontent.com/26178326/63077940-87f71180-bf6c-11e9-8e6c-e03864c035ce.png)
![image](https://user-images.githubusercontent.com/26178326/63077944-8d545c00-bf6c-11e9-9433-b5948ca07a75.png)
![image](https://user-images.githubusercontent.com/26178326/63077950-8f1e1f80-bf6c-11e9-90af-23de699b49e5.png)
![image](https://user-images.githubusercontent.com/26178326/63077952-91807980-bf6c-11e9-931a-d0638cc75ad2.png)

**Comment by YangHanlin** [comment]
I have come across the same error, and due to this error the color theme of VS Code has been restored to default (`Dark+`) and cannot be switched to any other color theme.

**Comment by SanJin-hx** [comment]
> I have come across the same error, and due to this error the color theme of VS Code has been restored to default (`Dark+`) and cannot be switched to any other color theme.
and All settings don't seem to work

**Comment by edwin-egalite** [comment]
I am having the same issue after upgrading to 1.38-insider (commit 44a48f75d64333b8e33a1fe4f57f6a60553b1e6b), settings are reverted to default.

**Comment by YangHanlin** [comment]
> 
> 
> > I have come across the same error, and due to this error the color theme of VS Code has been restored to default (`Dark+`) and cannot be switched to any other color theme.
> > and All settings don't seem to work

That's true - all settings don't seem to work.

**Comment by JiangJie** [comment]
`setting.json` with backslash `\` will cause the error.
Such as settings `"editor.wordSeparators": "~!@#%^&*()=+[{]}\\|;:'\",.<>/?"` `"files.eol": "\n"` `"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"`.

**Comment by SanJin-hx** [comment]
> `setting.json` with backslash `\` will cause the error.
> Such as settings `"editor.wordSeparators": "~!@#%^&*()=+[{]}\\|;:'\",.<>/?"` `"files.eol": "\n"` `"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"`.

you are right , but how can i setting git path?

**Comment by SanJin-hx** [comment]
> `setting.json` with backslash `\` will cause the error.
> Such as settings `"editor.wordSeparators": "~!@#%^&*()=+[{]}\\|;:'\",.<>/?"` `"files.eol": "\n"` `"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"`.

and No such problem before, Appeared after the update

**Comment by JiangJie** [comment]
Only waiting for Microsoft to fix it.

**Comment by SanJin-hx** [comment]
> Only waiting for Microsoft to fix it.

Yes _(:_」∠)_

**Comment by edwin-egalite** [comment]
Move any setting with with backslash \ to the bottom of the setting file would restore many custom setting for now.

**Comment by JiangJie** [comment]
> Move any setting with with backslash \ to the bottom of the setting file would restore many custom setting for now.

You are right.
You can continue to modify the settings.json file by json format, but can not by ui.

**Comment by gjsjohnmurray** [comment]
Looks like that Insiders version (2019-08-15T05:25:12.451Z) may have been bad. At least, when I checked just now for an update to mine it didn't offer me anything.

Version: 1.38.0-insider (user setup)
Commit: ba69d8dcccaebbfaa94906503728eb7c3e45b9c1
Date: 2019-08-14T07:18:43.039Z

**Comment by JiangJie** [comment]
> Looks like that Insiders version (2019-08-15T05:25:12.451Z) may have been bad. At least, when I checked just now for an update to mine it didn't offer me anything.
> 
> Version: 1.38.0-insider (user setup)
> Commit: [ba69d8d](https://github.com/microsoft/vscode/commit/ba69d8dcccaebbfaa94906503728eb7c3e45b9c1)
> Date: 2019-08-14T07:18:43.039Z

You could try this commit [`44a48f75`](https://github.com/microsoft/vscode/tree/44a48f75d64333b8e33a1fe4f57f6a60553b1e6b).

**Comment by edwin-egalite** [comment]
It's fixed in latest insider 8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b.

**Comment by gjsjohnmurray** [comment]
@SanJin-hx after you have updated and verified please close this.

**Comment by SanJin-hx** [comment]
> @SanJin-hx after you have updated and verified please close this.

ok, thank you
