### ISSUE TITLE
cannot open terminal

### ISSUE THREAD

**Issue by RA1NN1AR** [microsoft/vscode#79161]
Issue Type: <b>Bug</b>

The terminal closed when I create it.
btw the nofication shows : ❌ The terminal shell path "C:\" is a directory

VS Code version: Code - Insiders 1.38.0-insider (44a48f75d64333b8e33a1fe4f57f6a60553b1e6b, 2019-08-15T05:25:12.451Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8300 Eight-Core Processor            (8 x 4214)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.37.5
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0

</details>

**Comment by gjsjohnmurray** [comment]
That version of Insider was bad. A new one has replaced it. Please update and report back here whether you still get the problem or not.

**Comment by WellspringCS** [comment]
In VSCode (not Insiders) I am seeing this error in a dialog box when hitting F5 to compile in Ubuntu:

The preLaunchTask 'build' terminated with exit code -2.

In the terminal window itself, this error is reported:

The terminal shell path "dotnet" is a directory

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic
