### ISSUE TITLE
cannot use placeholder such as {{file}} in gulpfile

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7916]
- VSCode Version:1.2.1
- OS Version:arch linux

Steps to Reproduce:

1. write a gulpfile
2. write a task specificly designed to be run within vscode containing {{file}} such as run current file
3. open tasks and run that task from vscode
4. it fails

**Comment by dbaeumer** [comment]
Can you provide the tasks.json file you are using.

**Comment by NikosEfthias** [comment]
my tasks are resolved from my gulpfile.js automatically by vscode

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/Cth0okF.png) here is the tasks json generated by vscode

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/qAOp3uT.png) and here is the gulpfile

**Comment by dbaeumer** [comment]
I am not a gulp expert but to my knowledge gulp doesn't replace {{file}} with a real file name. How would gulp know which file to take.

However, what you can do is to use ${file} inside the tasks.json to pass the current open file to gulp. See https://code.visualstudio.com/docs/editor/tasks#_variable-substitution for examples and which variables are available.

**Comment by NikosEfthias** [comment]
ah i just mixed ${filed} with {{file}} so anyway ${file} isnt working

**Comment by dbaeumer** [comment]
You need to put the ${file} in the tasks.json file as an arg to your gulp tasks.

**Comment by NikosEfthias** [comment]
and inside gulp i should get the process argv then i guess right ?

**Comment by NikosEfthias** [comment]
@dbaeumer  it doesnt work the file is passed to gulp not not to my script so gulp ties to run it as a task so thats not an option and vscode fails about gulp tasks

**Comment by NikosEfthias** [comment]
i figured out i could use `--env` but its still a trick i thought if i run gulp through vscode it would auto replace all those special variables inside gulpfile

**Comment by dbaeumer** [comment]
@NikosEfthias no we don't. We only spawn gulp as a separate process.
