### ISSUE TITLE
Whitespace Issues with prompt, on VSCode's integrated terminal

### ISSUE THREAD

**Issue by pradyunsg** [microsoft/vscode#79175]
Issue Type: Bug
Component: Integrated Terminal

---

A picture's worth a 1000 words, so here are 2 pictures. :)

VS Code Integrated Terminal:

<img width="1362" alt="Screenshot 2019-08-15 at 4 16 41 PM" src="https://user-images.githubusercontent.com/3275593/63078989-2ccb1c00-bf78-11e9-8e43-2c7eab173b6a.png">

MacOS's Terminal:

<img width="1216" alt="Screenshot 2019-08-15 at 4 07 37 PM" src="https://user-images.githubusercontent.com/3275593/63078569-e1643e00-bf76-11e9-9aef-773e70ef7618.png">

The main difference is when there's an RPROMPT, VS Code's Integrated Terminal does not seem to properly render/add the space that's at the end of the PS1. Both are using the same zsh executable, with the same "Iosevka Nerd Font".

<details>
<summary>Copy Pasted Text, from these sessions</summary>

VS Code:
```
     echo "this is good" && show
this is good
PS1 = b'%{\x1b[35;1H%}%{\x1b[38;5;255m%}%{\x1b[48;5;26m%}%{\x1b[38;5;255m%}  \xef\x80\x95  %{\x1b[38;5;26m%}%{\x1b[48;5;76m%}\xee\x82\xb0%{\x1b[38;5;228m%}%{\x1b[48;5;76m%}%{\x1b[39;49m%}%{\x1b[38;5;76m%}\xee\x82\xb0%{\x1b[39;49m%} '
RPROMPT = b''
     sleep 1                    
    echo "this is bad" && show                                                                                                                                                         1.018 
this is bad
PS1 = b'%{\x1b[35;1H%}%{\x1b[38;5;255m%}%{\x1b[48;5;26m%}%{\x1b[38;5;255m%}  \xef\x80\x95  %{\x1b[38;5;26m%}%{\x1b[48;5;76m%}\xee\x82\xb0%{\x1b[38;5;228m%}%{\x1b[48;5;76m%}%{\x1b[39;49m%}%{\x1b[38;5;76m%}\xee\x82\xb0%{\x1b[39;49m%} '
RPROMPT = b'%{\x1b[38;5;167m%}\xee\x82\xb2%{\x1b[38;5;255m%}%{\x1b[48;5;167m%} 1.018 %{\x1b[39;49m%}'
     which show                 
show: aliased to python3 -c "print('PS1 =', '${PS1}'.encode('utf-8')); print('RPROMPT =', '${RPROMPT}'.encode('utf-8'))"
```

MacOS Terminal:
```
     echo "this is good" && show
this is good
PS1 = b'%{\x1b[25;1H%}%{\x1b[38;5;255m%}%{\x1b[48;5;26m%}%{\x1b[38;5;255m%}  \xef\x80\x95  %{\x1b[38;5;26m%}%{\x1b[48;5;76m%}\xee\x82\xb0%{\x1b[38;5;228m%}%{\x1b[48;5;76m%}%{\x1b[39;49m%}%{\x1b[38;5;76m%}\xee\x82\xb0%{\x1b[39;49m%} '
RPROMPT = b''
     sleep 1                    
     echo "this is good" && show                                                                                                                                 1.015 
this is good
PS1 = b'%{\x1b[25;1H%}%{\x1b[38;5;255m%}%{\x1b[48;5;26m%}%{\x1b[38;5;255m%}  \xef\x80\x95  %{\x1b[38;5;26m%}%{\x1b[48;5;76m%}\xee\x82\xb0%{\x1b[38;5;228m%}%{\x1b[48;5;76m%}%{\x1b[39;49m%}%{\x1b[38;5;76m%}\xee\x82\xb0%{\x1b[39;49m%} '
RPROMPT = b'%{\x1b[38;5;167m%}\xee\x82\xb2%{\x1b[38;5;255m%}%{\x1b[48;5;167m%} 1.015 %{\x1b[39;49m%}'
     which show                 
show: aliased to python3 -c "print('PS1 =', '${PS1}'.encode('utf-8')); print('RPROMPT =', '${RPROMPT}'.encode('utf-8'))"
```

</details>

---

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.6.0
Extensions: none

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|-psn_0_602259|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
The issue is the emoji, tracked in https://github.com/xtermjs/xterm.js/issues/1709

**Comment by pradyunsg** [comment]
That character is not an emoji. Removing it from the prompt, the issue occurs:

<img width="952" alt="Screenshot 2019-08-19 at 6 26 50 PM" src="https://user-images.githubusercontent.com/3275593/63258586-ec88d800-c2ae-11e9-9b27-49b4c693d789.png">

This was working before the July update and that issue is a lot older than that.

**Comment by pradyunsg** [comment]
(for folks following via email, I added more information to the comment above)

**Comment by Tyriar** [comment]
@pradyunsg the problem isn't restricted to just emoji but other ambiguous width unicode characters as well.

**Comment by pradyunsg** [comment]
*nods* That makes sense.

Would it be possible for you to look into/provide pointers to what change might have affected this, between the June and July releases? I am more than willing to volunteer my time to help resolve this issue.

I can confirm that June release works well for me -- I've downgraded for now.

**Comment by Tyriar** [comment]
It's a pretty involved issue that will probably eventually be tackled by @jerch, lots of history you can read on xtermjs/xterm.js#1709 and linked issues/prs.
