### ISSUE TITLE
Statusbar or top row cut off with Mac native tabs

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#79176]
Issue Type: <b>Bug</b>

The first Mac native tab has its top row cut off:

![image](https://user-images.githubusercontent.com/9205389/63079652-400dc580-bf3f-11e9-96f8-b0c3dd402cb3.png)

The second one has the statusbar below the visible window:

![image](https://user-images.githubusercontent.com/9205389/63079689-5e73c100-bf3f-11e9-948c-50555c553999.png)

Resizing the window is a workaround.

VS Code version: Code - Insiders 1.38.0-insider (44a48f75d64333b8e33a1fe4f57f6a60553b1e6b, 2019-08-15T05:23:00.986Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 11, 10|
|Memory (System)|16.00GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
ghlink|dt|1.1.0
remotehub|eam|0.5.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
git-project-manager|fel|1.7.1
rest-client|hum|0.22.0
solidity|Jua|0.0.58
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.1
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.67.4
remote-ssh-edit-nightly|ms-|2019.8.19620
remote-ssh-explorer-nightly|ms-|2019.8.19622
remote-ssh-nightly|ms-|2019.8.19620
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
github-issues-prs|ms-|0.9.1
debugger-for-chrome|msj|4.11.7
vetur|oct|0.22.1
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.4.1
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.12.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.1.9

</details>

**Comment by bpasero** [comment]
@chrmarti does this reproduce when you disable grid layout?

**Comment by chrmarti** [comment]
Yes, it's the same with grid layout disabled.

**Comment by bpasero** [comment]
@chrmarti I cannot reproduce, attach your settings.

**Comment by bpasero** [comment]
I cannot reproduce using Electron 4.2.7

**Comment by bpasero** [comment]
![grid-tw](https://user-images.githubusercontent.com/900690/63094380-7e6baa80-bf68-11e9-81d1-7874a7f32f23.gif)

**Comment by deepak1556** [comment]
Fix is up at https://github.com/electron/electron/pull/19878 , should be available with next electron release.

**Comment by alexandrudima** [comment]
we will take the new build and @bpasero will push it via a PR.
