### ISSUE TITLE
"Stage Selected Ranges" displayed as "%command.stageselectedranges%"

### ISSUE THREAD

**Issue by lafe** [microsoft/vscode#79174]
Issue Type: <b>Bug</b>

1. Change a file under source control
2. Go to "Source Control" view and select the changed file
3. In the "diff view" select the change and open the context menu
4. The menu item "Stage Selected Ranges" is displayed as "%command.stageselectedranges%":
![image](https://user-images.githubusercontent.com/4070008/63078930-5b77d100-bf3d-11e9-9b9d-7f447d4756b6.png)

VS Code version: Code - Insiders 1.38.0-insider (44a48f75d64333b8e33a1fe4f57f6a60553b1e6b, 2019-08-15T05:25:12.451Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Possibly a bad Insiders release. Looks to me like the one you've got is no longer available. At least, mine says there's nothing newer than 2019-08-14T07:18:43.039Z

**Comment by lafe** [comment]
I concur - the VS Code team also opened some issues based on telemetry and #79173 even mentions the property `resource`. So might be related to that (or one of the other type errors).

**Comment by gjsjohnmurray** [comment]
New Insider release just came out, and fixes this.

Version: 1.38.0-insider (user setup)
Commit: 8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b
Date: 2019-08-15T07:37:38.653Z

**Comment by gjsjohnmurray** [comment]
@lafe Assuming you verify this after updating please close the issue.

**Comment by lafe** [comment]
It's fixed for me (#79178 as well)
