### ISSUE TITLE
TypeError: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79172]
```
TypeError: Cannot read property 'uri' of null
/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#520:177 (_actionCallback)
/vs/base/common/actions.ts#179:15 (run)
/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#397:17 (onWorkspaceFoldersChanged)
/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#313:76 (call)
/vs/base/common/event.ts#572:15 (fire)
/vs/workbench/services/configuration/browser/configurationService.ts#561:40
```

https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=ff9993b8-a9e2-e4d0-7ff1-db88a9940938

**Comment by roblourens** [comment]
@sandy081 I'm not following this code.

https://github.com/microsoft/vscode/blob/aa02f856bfce711dd2aa83309b97de0cf2b5722f/src/vs/workbench/contrib/preferences/browser/preferencesWidgets.ts#L394-L396

I think this is checking whether to update the folders button after folders change, so should it be 

```
if ((oldFolder && !this._folder)
    || (!oldFolder && this._folder)
    || (oldFolder && this._folder && (oldFolder as IWorkspaceFolder).uri.toString() !== (this._folder as IWorkspaceFolder).uri.toString())) {
```

and then change updateTarget to accept null? Or am I misunderstanding?

**Comment by sandy081** [comment]
Yes, it should check if folders are not same.

**Comment by roblourens** [comment]
Real bug to verify - 

- Open "multiroot" workspace with one folder
- Open the settings editor and select folder settings for that folder
- Remove that folder from the workspace
- The settings editor should switch to user settings
