### ISSUE TITLE
Consider adding isDefault to TaskGroup 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#79188]
Currently users of `fetchTask` can see the task group, but not if it is a default for that group.

**Comment by alexr00** [comment]
Old:
```
	export class TaskGroup {
		static Clean: TaskGroup;
		static Build: TaskGroup;
		static Rebuild: TaskGroup;
		static Test: TaskGroup;
		private constructor(id: string, label: string);
	}
```
Proposed:
```
	export class TaskGroup2 {
		static Clean: TaskGroup2;
		static Build: TaskGroup2;
		static Rebuild: TaskGroup2;
		static Test: TaskGroup2;
		readonly isDefault?: boolean; // new value
		readonly id: string; // value no explicitly exposed
		private constructor(id: string, label: string);
	}
``

**Comment by heatherjsun** [comment]
@alexr00 Is this feature still being planned for?

**Comment by alexr00** [comment]
@heatherjsun it's in the backlog, which means its something we'd like to do, but there's no timeline for when it might happen.

**Comment by alexr00** [comment]
@heatherjsun since you've communicated offline that you'd like to make a PR for this, here are some pointers:

- New API should be added to the file vscode.proposed.d.ts. Once I have a PR from you I'll take the new API to our API discussion and we'll make sure that we think it's a good addition and is consistent with our existing API. I expect this change to be pretty straight forward and shouldn't require much discussion. 
- https://github.com/microsoft/vscode/commit/d090429855e20c53798c6f4cbd3bb098d0ea7c23 has some of the changes required, but also has some unneeded changes. I recommend looking at the changes in extHost.api.impl.ts, extHostTask.ts, extHostTypes.ts, and tasks.ts to get started. But the basic idea is that extensions run in the extension host, so any data we get from extensions (in this case task group) needs to transferred to the main VS Code renderer process where the rest of the task runner lives. Then, when an extension asks for tasks, we need to make sure the task group is properly passed back to the extension host.

If you have any further questions please let me know and I'll provided more details!
