### ISSUE TITLE
 Tree element not found: [object Object]

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#79180]
Issue Id: <b>3f5e6ebf-d995-9bdc-b96e-c2ceff9ecbd9</b><br /><br />*Versions* <br />- 1.38.0-insider (8/13/2019 7:19:46)<br />*Stack* <br />Error: Tree element not found: [object Object]<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#274:9 (getElementLocation)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/browser/ui/tree/objectTreeModel.ts#L274:9 (getElementLocation))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#216:24 (isCollapsed)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/browser/ui/tree/objectTreeModel.ts#L216:24 (isCollapsed))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1412:20 (isCollapsed)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/browser/ui/tree/abstractTree.ts#L1412:20 (isCollapsed))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#565:18 (revealMarkersForCurrentActiveEditor)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L565:18 (revealMarkersForCurrentActiveEditor))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#558:8 (autoReveal)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L558:8 (autoReveal))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#463:7 (onActiveEditorChanged)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L463:7 (onActiveEditorChanged))<br />[/vs/workbench/contrib/markers/browser/markersPanel.ts#418:9 (call)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L418:9 (call))<br />[/vs/base/common/event.ts#574:18 (fire)](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/common/event.ts#L574:18 (fire))<br />[/vs/base/common/event.ts#158:15](https://github.com/microsoft/vscode/blob/ffa22b268f451b5211abbe2d2a47e6b753b55b1a/src/vs/base/common/event.ts#L158:15)<br />

**Comment by sbatten** [comment]
@bpasero created while testing

**Comment by isidorn** [comment]
This is from the markersPanel, thus forwarding to @sandy081

**Comment by sandy081** [comment]
/duplicate

#71126
