### ISSUE TITLE
Do not expand session tree node when selecting it

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79184]
When dealing with multiple debug sessions and/or threads, it is not helpful that selecting a session or a thread always expands the subtree. This quickly results in clutter and prevents the debug session tree from staying compact.

**Comment by isidorn** [comment]
Agree with this.
I have now changed the CallStackView that it bheaves like the outline view.
That clicking on the Thread and Session does not expand them. But they require an explicit click on the twistie. Elements can aslo be expanded via keyboard.

We should mention this in the release notes as some users might be surprised by the change (which I believe is good overall).

**Comment by pavelfeldman** [comment]
Looks great!
