### ISSUE TITLE
problemMatcher vs zero-based column values

### ISSUE THREAD

**Issue by db4** [microsoft/vscode#7918]
- VSCode Version: 1.2.1
- OS Version: Windows 10

I'm trying to parse error messages of OCaml compiler like this:

```
File "test.ml", line 1, characters 0-1:
Error: Syntax error
```

with a a following problemMatcher:

```
"problemMatcher": {
    "owner": "ocaml",
    "fileLocation": ["relative", "${fileDirname}"],
    "pattern": [
        {
            "regexp": "^File \"(.*)\", line (\\d+), characters (\\d+)-(\\d+):$",
            "file": 1,
            "line": 2,
            "column": 3,
            "endColumn": 4
        },
        {
            "regexp": "^(Warning|Error):\\s+(.*)$",
            "severity": 1
            "message": 2
        }
    ]
}
```

Column range of error (characters 0-1) is zero-based while VS Code expects that column numbers starts from one; so I have an error marker in VS Code shifted one position to left

Is it possible to add additional problemMatcher property to correctly handle this case?

**Comment by bobzhang** [comment]
any plan on this issue? thanks

**Comment by dbaeumer** [comment]
Not for the November/December release.
