### ISSUE TITLE
Node predefined variables needed

### ISSUE THREAD

**Issue by extmchristensen** [microsoft/vscode#79183]
Just like ${workspaceFolder} is useful in configuration files, it would also be highly useful to be able to refer to various aspects of the node and node-gyp installation such as suggested variables like ${nodeVersion} and ${nodeInstallationPath} and "${nodeGypDataPath}"

For example, this could be used to setup c++ header locations in a portable way when developing node napi modules. It would also be useful to setup debugging etc.

"configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/cpp/**",
                "${nodeGypDataPath}/${nodeVersion}/include/node"
            ],

**Comment by isidorn** [comment]
Feels like out of scope to me. But assinging to @alexr00

**Comment by alexr00** [comment]
Agree with out of scope. I suggest that you add those as environment variables and use them.
