### ISSUE TITLE
Make it possible to remove "Ln 100, Col 10, (2003903 selected)" info from statusbar

### ISSUE THREAD

**Issue by tino** [microsoft/vscode#79186]
After reading https://github.com/Microsoft/vscode/issues/45726, https://github.com/Microsoft/vscode/issues/932, https://github.com/Microsoft/vscode/issues/15344 and https://github.com/microsoft/vscode/pull/17955 on to deal with showing the amount of selected lines in the status bar, I'd like to request the option to hide or replace the current information. 

Given "the consensus of the team is that the space in the status bar is limited" (@alexandrudima) and the information displayed currently is not important enough to a lot of users (as shown by multiple issues raised with plenty of comments for a very tiny feature in the statusbar) I think it makes sense to be able to replace this completely with information that is truly useful to the user. 

A setting that you can pass a formatting string that receives a variety of counts would be all that is needed!

**Comment by gjsjohnmurray** [comment]
Context menu of the status bar allows you to do this. Deselect 'Editor Selection'
