### ISSUE TITLE
Unable to install Remote - SSH with no indication of what's wrong

### ISSUE THREAD

**Issue by yitzikc** [microsoft/vscode#79193]
Issue Type: <b>Bug</b>

I'm trying to install the Remote-SSH extension, and I get indication that it failed, with the suggestion I should download it manually and then install the VSIX file. The download is successdfully carried out by Safari, and I see the files ms-vscode-remote.remote-ssh-0.45.5.vsix and  ms-vscode-remote.remote-ssh-edit-0.45.5.vsix in the Downloads directory. When I subsequently click "Install from VSIX" and select either one of them, nothing happens. There's no indication of an installation in progress or successful.

VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.1.5
vscode-postgres|cko|1.1.11
vscode-markdownlint|Dav|0.27.0
vscode-eslint|dba|1.8.1
xml|Dot|2.5.0
shell-format|fox|6.1.1
rest-client|hum|0.22.0
ftp-simple|hum|0.7.0
configure-c-compiling|ivo|0.2.1
node-module-intellisense|lei|1.5.0
terraform|mau|1.3.12
vscode-clang|mit|0.2.3
vscode-docker|ms-|0.6.4
python|ms-|2019.1.0
cpptools|ms-|0.24.1
vscode-yaml|red|0.3.0
bash-beautify|sha|0.1.1
vscode-make|tec|1.0.2
vscode-apielements|vnc|0.6.7
vscode-ansible|vsc|0.5.2
vscode-proto3|zxh|0.3.0

</details>

**Comment by yitzikc** [comment]
Unable to install extension 'ms-vscode-remote.remote-ssh-0.45.5' as it is not compatible with VS Code '1.30.0'.

**Comment by gjsjohnmurray** [comment]
Start by updating your VS Code. I'm pretty sure 1.30 is too old to support those extensions.

**Comment by yitzikc** [comment]
Yes, updating solved the problem. My VS-Code hadn't updated in a while due to https://github.com/Microsoft/vscode/issues/27928 . Once I resolved that everything was fine.
