### ISSUE TITLE
Keyboard override

### ISSUE THREAD

**Issue by sdfcprog** [microsoft/vscode#79194]
Issue Type: <b>Bug</b>

When I am debugging .Net Core C# code, if I select the function keys F10 or F11 to step thru my code, Dells F10 or F11 function executes and does not execute Visual Code F10 or F11 functionality. I am using a Dell XPS  laptop.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
vscode-eslint|dba|1.9.0
apex|Joh|1.0.4
csharp|ms-|1.21.0
salesforcedx-vscode|sal|46.9.0
salesforcedx-vscode-apex|sal|46.9.0
salesforcedx-vscode-apex-debugger|sal|46.9.0
salesforcedx-vscode-apex-replay-debugger|sal|46.9.0
salesforcedx-vscode-core|sal|46.9.0
salesforcedx-vscode-lightning|sal|46.9.0
salesforcedx-vscode-lwc|sal|46.9.0
salesforcedx-vscode-visualforce|sal|46.9.0

</details>

**Comment by gjsjohnmurray** [comment]
Look for the BIOS setting and change it.

![image](https://user-images.githubusercontent.com/6726799/63090049-e5319980-bf51-11e9-89da-096f7b6ea18b.png)

/question
