### ISSUE TITLE
Monaco: Plans for publishing to Bower?

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/vscode#7919]
With Monaco now a separate project that can be used in sites with NPM, is there any plans to be able to fetch & install Monaco using Bower?

**Comment by alexandrudima** [comment]
I am unsure what that involves, I've personally never used Bower, but I'll look into it.

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#138

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
