### ISSUE TITLE
"Reveal in Explorer" for Breadcrumbs

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#79199]
Hello,

My another suggestion is add option `Reveal in Explorer` in Breadcrumbs.
I often would like to open any folder from breadcrumbs in Windows explorer

**Below is an example of what I mean:**
1. Mouse `right click` on one of the directories that I want to open
![obraz](https://user-images.githubusercontent.com/30685349/63091312-42334c80-bf5e-11e9-8028-6a070825cf1e.png)
2. I supposed to see something like:
![obraz](https://user-images.githubusercontent.com/30685349/63091395-7eff4380-bf5e-11e9-86e4-ba3b2afb4619.png)

**Comment by gjsjohnmurray** [comment]
Similar to #67711
