### ISSUE TITLE
Can't swip the screen in vscode,but can swip outside 

### ISSUE THREAD

**Issue by Kerinlin** [microsoft/vscode#79203]
Issue Type: <b>Bug</b>

I don't know how to reproduce the bug,but when i open the bug report dialog, it works again. 

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
vscode-npm-dependency|how|1.2.2
vscode-language-pack-zh-hans|MS-|1.37.5
vetur|oct|0.22.1
vue-vscode-snippets|sdr|1.7.1
vue-docs|tit|1.0.2

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you please provide some reproducable steps?
What is the exact issue here?
