### ISSUE TITLE
HTML format issue with style block

### ISSUE THREAD

**Issue by DennisJohnsen** [microsoft/vscode#79207]
- VSCode Version: 1.37.0
- OS Version: macOS 10.14.2

When im trying to format my HTML documents i'm having some issues with `<style>` blocks.

Correct (expected):
```html
        <style type="text/css">
            [data-component="{{ $.index }}"] .c-hero__content-wrapper:before {
                background-color: {{ . | safeCSS }};
            }
        </style>
```

Incorrect (current): 
```html
<style type="text/css">
    [data-component="{{ $.index }}"] .c-hero__content-wrapper:before {
        background-color: {
                {
                . | safeCSS
            }
        }

        ;
    }

</style>
```

I suspect it might be due to the go template syntax in the style block, but i would still expect the formatter to _kind of_ ignore `{}` symbols between `:` and `;`

Hope im making this issue the right place.

**Comment by octref** [comment]
HTML formatter uses js-beautify. Just verified this is the same output from js-beautify

```bash
 Code > js-beautify foo.html
        <style type="text/css">
            [data-component="{{ $.index }}"] .c-hero__content-wrapper:before {
                background-color: {
                        {
                        . | safeCSS
                    }
                }

                ;
            }
        </style>%                                                                                                                                              Code >
```

Please report to https://github.com/beautify-web/js-beautify.

**Comment by DennisJohnsen** [comment]
Are you sure? I used the built in html language as formatter.

**Comment by octref** [comment]
https://github.com/microsoft/vscode-html-languageservice/blob/master/src/services/htmlFormatter.ts#L8
