### ISSUE TITLE
Soften VS Code remote security policy to allow Spectron framework to attach to VS Code

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode#79204]
- VSCode Version: 1.37.0
- OS Version: macOS 10.14, Windows 1903, Ubuntu 18

Hello.
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension. In our extension we are using automated UI tests to validate the extension debug scenarios. For UI interaction with VS Code we are using Spectron framework to connect to the VS Code Electron API via ChromeDriver.
Since 1.37.0 version VS Code [has made security policy more strict](https://github.com/microsoft/vscode/commit/be083391803ae7f78242af45b63ee500a4396615#diff-fc6683f92061646324644f2cd92304cf). By this policy any remote calls of VS Code Electron API built-in modules are prohibited. For example the following call are required for Spectron, but it is failing with such error:
```
     unknown error: Blocked remote.getBuiltin('screen')
  Error: An unknown server-side error occurred while processing the command.
      at execute(<Function>, "nodeRequire") - .\node_modules\spectron\lib\api.js:72:26
```
Is it possible to soften `remote` filtering policy as described [here](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#16-filter-the-remote-module) so Spectron would be able to attach to VS Code to perform automated UI tests?

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@SounD120 to be clear, you would only want to weaken it when VSCode is started from the command line to run extension tests? In theory we could think about allowing that IFF Code is only running for tests. This would however limit the ability to run the tests otherwise, e.g. from within Code.

**Comment by SounD120** [comment]
@bpasero Yes, I think special CLI argument that will disable some security checks for VS Code test runs will suit for our case.

**Comment by bpasero** [comment]
@SounD120 I would probably not want to introduce a new argument because it may be abused in other cases but rather tie this only to tests run from CLI.

**Comment by SounD120** [comment]
@bpasero What do you mean by tests run from CLI? How VS Code will understand that it is being ran just for tests without special arguments?

**Comment by bpasero** [comment]
@SounD120 what is the exact setup, how are the tests running?

I wonder if alternatively we could detect that Spectron is attached to VSCode and then relax the rules. Because that is after all the thing that is broken. If you can find out if there is any environment variable set or any other way to find out with Electron APIs, we can make it conditional based on that.

**Comment by SounD120** [comment]
@bpasero We are using the [VS Code old approach](https://github.com/microsoft/vscode/tree/1.22.1/test/smoke) to run VS Code smoke tests through Mocha with Spectron. We run Mocha, then we prepare environment - we download an archive with VS Code, prepare a startup arguments, and then we run VS Code via Spectron [start function](https://github.com/microsoft/vscode/blob/950b8b0d37a9b7061b6f0d291837ccc4015f5ecd/test/smoke/src/spectron/application.ts#L232).  With respect to environment variables I found [such lines](https://github.com/electron-userland/spectron/blob/404b5abc7f3e0b0fb348ecd3343804c0909fc6df/lib/chrome-driver.js#L89-L101) in Spectron code, but for some reason this patch is only applies on Windows. Can we use some special environment variable like `SPECTRON_TESTS=true` to disable the part of VS Code security filters?

**Comment by bpasero** [comment]
@SounD120 have you thought about using our new approach? I can think of making this change if the `--driver` argument is passed.

Since I can not devote time for this, I am setting the help wanted label if someone wants to investigate a solution.

**Comment by SounD120** [comment]
@bpasero You mean `--driver` VS Code start up argument or environment variable?

**Comment by bpasero** [comment]
@SounD120 we moved away from Spectron to implement our own automated UI testing framework. We run it through `--driver`. Maybe you could get a long with that. Our tests live in `test/smoke`.

**Comment by nsharma1989** [comment]
Hi Is there any solutions to this yet.. Any alternatives for the same. Thanks

**Comment by rodney-wilson** [comment]
Hello. Are there any solutions or workarounds identified for this issue?

**Comment by ALS024** [comment]
Is https://github.com/microsoft/vscode/tree/master/test/smoke an alternative to Spectron?
