### ISSUE TITLE
Allow local shortcut to open remote workspace/folder

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#79208]
Since the introduction of [VS Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) I've moved all my workflow to work in WSL or via Remote SSH (spoiler: It's awesome!).

[Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) allow you to create a file e.g. like `VS Code projects.code-workspace` which is a way to launch the entire multi-root workspace.

It would be awesome if the schema for this file was augmented to provide a way to put such a file on the desktop in Windows, but double-clicking it would open the workspace in WSL. (or in a remote SSH or in a container maybe even).

**Comment by aeschli** [comment]
Workspace files are already supported in remote, but we currently require the workspace file to be on the remote file system. 

Once you created it there and opened it from there, you can use the recent entry list to re-open it.

If a clickable shortcut is what you absolutely needs, then try to create a shortcut with this command line:

`code-insiders --file-uri=vscode-remote://wsl+Ubuntu/home/user/foo.code-workspace`.

Agree that this is quite advanced and we currently try to hide the URI from the user. But you can find it in the `storage.json`

**Comment by thernstig** [comment]
@aeschli I was aware of these ways to launch it, I just thought maybe the request would make this simpler for user. At the same time, I'm not sure it would be a highly requested feature. I am actually fine with closing this, at least then future users who search for this will find your answer.

**Comment by aeschli** [comment]
Yes, lets see if there are other use cases and requests. It's a feature request on the backlog.

**Comment by aeschli** [comment]
dup of #78491

**Comment by thernstig** [comment]
@aeschli Not sure it is a dup, but similar. His is about context menu, this is about having an icon for a code-workspace file.

**Comment by aeschli** [comment]
Yes, got it. Having a 'Open in WSL' on a file would also help you.
Unfortunately neither requests are easy to implement due to the fact that we don't want to bake the WSL support into VSCode, but keep it as an extension.
