### ISSUE TITLE
File manager is non responsive after opening a folder and slow startup

### ISSUE THREAD

**Issue by monajafi** [microsoft/vscode#79202]
Issue Type: <b>Performance Issue</b>

After opening a folder every click on every button takes some seconds to take action. this happened after upgrading to vesion 1.37. 
The VSCode startup is also slowed

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	   131	 55480	code main
    1	    66	 55585	   gpu-process
    0	   197	 55587	   window (Extension: vscode-icons)
    0	    82	 55711	     extensionHost
    0	   180	 58754	       /usr/local/Cellar/dart/2.4.1/libexec/bin/dart /usr/local/Cellar/dart/2.4.1/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.3.0
    0	    98	 55604	   shared-process
    0	     0	 60427	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   377	 58860	   window (undefined)
    1	    82	 60219	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
vscode-pydev|fab|0.1.5
code-runner|for|0.9.13
swift|Kas|0.0.3
vscode-gist|ken|3.0.3
Kotlin|mat|1.7.0
python|ms-|2019.8.30787
open-in-browser|tec|2.0.0
pygame-snippets|tus|0.0.1

</details>

**Comment by monajafi** [comment]
I noticed that every non native mac app running slower

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for guidance on what to collect.
