### ISSUE TITLE
Use Windows Terminal as the built-in Terminal if it's installed

### ISSUE THREAD

**Issue by WSLUser** [microsoft/vscode#79211]
If [Windows Terminal](https://github.com/microsoft/terminal) is installed, I'd like to have the option to use it for my built-in terminal within VSCode. This would still default to the shell specified in `settings.json`.

**Comment by Tyriar** [comment]
Good idea, but this should probably wait until it's v1.

**Comment by Tyriar** [comment]
Closing for now, we can reconsider when Windows Terminal is v1
