### ISSUE TITLE
Debug console doesn't scroll to bottom

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#79213]
Hi,

I'll do my best to explain, this is hard.

I am developing an extension. When I press <kbd>F5</kbd> to run it, the debug console appears, but it is not scrolled to the bottom, instead it focuses at about the middle of the scrollbar. So I have to grab my mouse, select the scrollbar, drag it down, then focus back to my extension.

This only reproduces when the debug console panel is moved to right.

This reproduces with extensions disabled. But, in order to reproduce, there must be a lot of text that appears in the debug console. When my host has extensions disabled, and I press F5, the "child" VS Code window has its extension enabled (which is normal), and those extensions spit out a lot of text (this allows me to reproduce the annoying problem). The extension named `Python` is particularly verbose, when a python file is already opened when running the child.

There are similar issues that are closed. I found none open.

I have this problem when debugging an extension, but this probably applies to whatever debugging session one launches.

Steps to Reproduce:

1. Launch debugging session with F5
2. Debug console appears
2a. Its panel must have already been moved to right beforehand 
3. Debuggee spits out a lot of text
3a. You might want to try with an extension as a debuggee with Python extension enabled and a python file open
4. Watch as the debug console "scroll grasp" is at the middle of the scrollbar.
5. As the debuggee continues to spit out text, the debug console scrolls a little but down, but no that much, it's weird
6. Grab the scroll bar and drag it to the bottom. Watch as there is another bug that makes the mouse be dissociated from the scroll "grasp". I'll report it someday
7. Once you're at the bottom, the debug console auto-scrolls normally.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.38.0-insider (8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b, 2019-08-15T07:35:56.910Z)
OS version: Linux x64 4.15.0-55-generic

**Comment by sguillia** [comment]
This is not the same as #74095 because my problem reproduces also when the debug console is clear. Consider Step 0 = reload window.

**Comment by isidorn** [comment]
Sounds like a duplicate of 
https://github.com/microsoft/vscode/issues/77837

**Comment by sguillia** [comment]
@isidorn Maybe. My problem differs because when I have the panel moved to the bottom, I cannot reproduce even with multiple lines wrapping around. But it can be the same root problem.
