### ISSUE TITLE
Column Selection by mouse should begin where the mouse click starts

### ISSUE THREAD

**Issue by StingyJack** [microsoft/vscode#79214]
In other editors like VS, i can hold down the Alt key, then left click the mouse at the place where I want to start the column selection, and begin dragging immediately to make the selection. 

In VSC, I am required to place the cursor first then Shift+Alt, left click, drag. 

This difference in starting the operation led me to thinking that either VSC was missing the feature despite documentation stating otherwise, or that the feature was bugged or otherwise unusable.

**Comment by alexandrudima** [comment]
@StingyJack You can configure `"editor.multiCursorModifier": "ctrlCmd"` and then the `alt` key toggles between normal selection and column selection.

Regardless of the above setting, you can also use the middle mouse button to do column selection.

**Comment by StingyJack** [comment]
@alexandrudima -  I'm not talking about the difference between Alt vs Shift + Alt. I think i was pretty clear stating it was how the operation was started, not the hotkeys used.

**Comment by alexandrudima** [comment]
> In other editors like VS, i can hold down the Alt key, then left click the mouse at the place where I want to start the column selection, and begin dragging immediately to make the selection.

Use `"editor.multiCursorModifier": "ctrlCmd"`
