### ISSUE TITLE
Should ipc.ts leverage VSBuffer?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79212]
Just stumbled upon this code in `ipc.ts` which lives in `common`:

https://github.com/microsoft/vscode/blob/5d4a2514c9db09909bc06b34033a4f0117c1ba72/src/vs/base/parts/ipc/common/ipc.ts#L193

I wonder if this code could benefit from `VSBuffer`?

**Comment by alexandrudima** [comment]
@bpasero it does leverage VSBuffer, but that code has the following two constraints:
1. It must run in a browser
2. It is used in untyped ways by all kind of code in the workbench.

I had something similar for the extension host, but for the extension host I could look at the `extHost.protocol` and remove one-by-one the places where a `Buffer` was being sent transparently as arguments/return values. We need to do something similar to all the code that uses ipc in the workbench and then the transparent transport of `Buffer` can be removed from this file.

**Comment by joaomoreno** [comment]
I don't know what to do here.
