### ISSUE TITLE
Vue CLI project - @ absolute path

### ISSUE THREAD

**Issue by Mikilll94** [microsoft/vscode#79219]
- VSCode Version: 1.37.0
- OS Version:

Intellisense in VS Code is not working with absolute paths in projects created with Vue CLI.

Steps to Reproduce:

1. Create a new project using Vue CLI
2. Type in any javascript file or <script> section

`
import HelloWorld from '@/something/something'
`

3. After typing, '@/' Intellisense should prompt us with all available files and directories based on the path. Unfortunately, it is not working at all for absolute paths.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
VScode does not support vue out of the box. Please file this against your Vue extension
