### ISSUE TITLE
Custom tree right click broken

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79224]
Expected (Stable):

![image](https://user-images.githubusercontent.com/4033249/63106550-ea81ea80-bf37-11e9-844a-642e0b0e7023.png)

Bug (Insiders):

![image](https://user-images.githubusercontent.com/4033249/63106568-f40b5280-bf37-11e9-9d2b-339fc4b4e9f1.png)

Version: 1.38.0-insider
Commit: 8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b
Date: 2019-08-15T07:34:22.748Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by IllusionMH** [comment]
Strange.
This works fine for me on Windows with GitHub Pull Request Nightly Build (2019.8.19623) on the same VS Code Insiders build.

![image](https://user-images.githubusercontent.com/1312662/63111535-90fcd880-bf96-11e9-8cbf-11bd8672291c.png)

VS Code version: Code - Insiders 1.38.0-insider (8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b, 2019-08-15T07:37:38.653Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
I'm on 0.10.0 on GH PR extension. Also wondering if it's only on macOS as it might be related to native context menus.

**Comment by IllusionMH** [comment]
Now it feels like OS specific. Works as expected with `0.10.0` on Windows  for me.

![image](https://user-images.githubusercontent.com/1312662/63120150-63ba2580-bfaa-11e9-8022-3c1e5e0827e0.png)

VS Code version: Code - Insiders 1.38.0-insider (8985ff7c9d38bd2ce7d1e6b58e40d27c5bbdb67b, 2019-08-15T07:37:38.653Z)
OS version: Windows_NT x64 10.0.18956

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.10.0

**Comment by octref** [comment]
Bringing this to your attention @alexr00, as it affects all custom tree's right click:

![image](https://user-images.githubusercontent.com/4033249/63362773-3e6d4480-c327-11e9-906b-69455eaaa594.png)

**Comment by alexr00** [comment]
Tested on Windows and it works there. Looks like it could be mac specific then. @sbatten are native context menus under your purview?

**Comment by sbatten** [comment]
@alexr00 yes, but using native context menus on windows doesn't seem to reproduce the issue.

**Comment by sbatten** [comment]
This is caused by the Sass extension contributing actions to the menu without filtering to their view in the when clause. I think it is strange that an extension can accidentally bleed everywhere as I would expect by default that my command only shows up in my view.

**Comment by alexr00** [comment]
Thank you for investigating!
