### ISSUE TITLE
Debug  step over or stepInto not work correctly

### ISSUE THREAD

**Issue by mcaisw** [microsoft/vscode#79220]
Issue Type: <b>Bug</b>

when I debug my code ,press stepover or stepInto not work correctly,Just like I clicked on to the continue.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|/Users/mengchi/mergeaircraft -g /Users/mengchi/mergeaircraft/Assets/Scripts/Tmp/GridManager.cs:1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.21.0
unity-debug|Uni|2.7.2

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language do you use? (I suppose it is C#)
Does it happen with any code that you debug in that language or only specific code?
Do you have options like step over library code or other exclusions enabled?

**Comment by mcaisw** [comment]
Thank you for your kind reply.I don't know the problem right now, but after I restart my computer, everything is fine.

**Comment by mcaisw** [comment]
> /needsMoreInfo
> 
> What language do you use? (I suppose it is C#)
> Does it happen with any code that you debug in that language or only specific code?
> Do you have options like step over library code or other exclusions enabled?

Thank you for your kind reply.I don't know the problem right now, but after I restart my computer, everything is fine.
