### ISSUE TITLE
Format Document on XML Alters CDATA Section

### ISSUE THREAD

**Issue by michaelbunney** [microsoft/vscode#79233]
Issue Type: <b>Bug</b>

STEPS:
1. Open an XML file that includes CDATA sections that contain HTML, such as <p> paragraphs.
2. Right-click and choose Format Document.

RESULTS:
VSC reformats contents of CDATA sections, removing indentation on many lines.

EXPECTED:
Contents of CDATA sections to be treated as literal data, not as XML markup to be reformatted.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362

**Comment by michaelbunney** [comment]
What action is required of me?  I don’t see any way to respond whether it is a duplicate.  (It is not.)

Mike

**Comment by alexr00** [comment]
@jrieken this sounds like a format document issue.
