### ISSUE TITLE
CustomExecution proposed API needs a more explicit way to signal completion

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#79235]
## This is an issue with proposed APIs

- VSCode Version: latest master
- OS Version: Mac OS Mojave

cc @Tyriar and @aeschli since I see you've been active on this API

### Current Situation
Currently, when writing new tasks with `CustomExecution`, they are expected to create a `PseudoTerminal` and pass it back the tasks API. The only way for these tasks to signal that they are completed, is to fire their own `closeEmitter`. See example below from `vscode.proposed.d.ts`:

```ts
const writeEmitter = new vscode.EventEmitter<string>();
const closeEmitter = new vscode.EventEmitter<vscode.TerminalDimensions>();
const pty: vscode.Pseudoterminal = {
  onDidWrite: writeEmitter.event,
  onDidClose: closeEmitter.event,
  open: () => writeEmitter.fire('Press y to exit successfully'),
  close: () => {}
  handleInput: data => {
    if (data !== 'y') {
      vscode.window.showInformationMessage('Something went wrong');
    }
    closeEmitter.fire();
  }
};
vscode.window.createTerminal({ name: 'Exit example', pty });
```

### Problem
The fact that VSCode internal APIs will listen to the `PseudoTerminal.onDidClose` event to signal task completion is problematic, because it happens after the actual execution is complete, therefore, extension authors must leave the `closeEmitter` undisposed until VSCode listeners are called.

`PseudoTerminal.onDidClose` might make sense for a `PseudoTerminal`, but from a tasks API viewpoint, I suggest providing another way to signal task completion. For example, another argument to `CustomExecution`.

**Comment by Tyriar** [comment]
> extension authors must leave the closeEmitter undisposed until VSCode listeners are called.

Not sure I understand? The listeners should be called immediately?

**Comment by OmarTawfik** [comment]
Debugging through the main process event loop, I see that the callbacks are executed immediately. Thanks for confirming.
I'll look into my extension to see what is preventing the callback.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/79643
