### ISSUE TITLE
Remove usage of TSLint where possible.

### ISSUE THREAD

**Issue by joelday** [microsoft/vscode#79230]
1. TSLint is deprecated.
2. There is a moral obligation to do so given Palantir's contracts with the United States Immigration and Customs Enforcement agency (ICE).

In my personal opinion, continued usage of tslint indirectly violates the spirit of the Microsoft Open Source Code of Conduct.

Thank you!

**Comment by mjbvz** [comment]
We will migrate to eslint once it is worth the effort and we have a good technical reason to so
