### ISSUE TITLE
⌥↑ doesn't work in integrated terminal

### ISSUE THREAD

**Issue by lgarron** [microsoft/vscode#79237]
Issue Type: <b>Bug</b>

- VSCode Version: 1.37.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Install `fish` shell: https://fishshell.com/
2. Open the integrated terminal in VSCode into `fish`.
3. Type ⌥↑ (option-up)

Expected: Fish goes through tokens in its history
Observed: The code `[1;5A` is typed into the shell.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lgarron** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [An unwanted linebreak after opening integrated terminal with fishshell (#78064)](https://www.github.com/microsoft/vscode/issues/78064)

't' isn't, as far as I can tell!

**Comment by Tyriar** [comment]
I think you're after `terminal.integrated.macOptionIsMeta`?

**Comment by lgarron** [comment]
> I think you're after `terminal.integrated.macOptionIsMeta`?

Unfortunately, that doesn't seem to make a difference. 😔
