### ISSUE TITLE
User Snippets doesn't work

### ISSUE THREAD

**Issue by kiwatchi1991** [microsoft/vscode#79249]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.The snippet registered with php.json does not move in "" of the img tag
2.The snippet has key "ph" and body "<?php ?>"
3.It works fine outside the tag
4.All plug-ins are uninstalled

![テラテイル用](https://user-images.githubusercontent.com/51079797/63129149-c682df80-bff1-11e9-805d-c9c046f66c59.gif)

<img width="364" alt="スクリーンショット 2019-08-16 6 56 06" src="https://user-images.githubusercontent.com/51079797/63129604-f7174900-bff2-11e9-9ff3-d4e52ccfa8ee.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That's the design - "suggestions as you type" are only enabled when typing at word-ends. You need to trigger suggestion manually otherwise, e.g. press Ctrl+Space
