### ISSUE TITLE
Allow extensions control dimensions for existing terminals

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#79246]
Live Share has a feature where when a user starts a collaboration session as a host, all existing terminals are automatically shared. When other guests join, they'll see these shared terminals. 

The problem is that guests' UI dimensions are different from the host, and such shared  terminals may not render correctly there.

Live Share already solves this for `Pseudoterminal` that users can create via Live Share viewlet. Live Share uses `onDidOverrideDimensions` and `setDimensions` on `Pseudoterminal`. It needs VSCode support for regular `Terminal` objects.

Existing terminals has read-only `dimensions` property on `Terminal` objects which we can use to get current terminal dimensions (maximum ones I assume), but nothing that we can use to change the dimensions, and no event that would tell us when UI changes and max dimensions change.

So the feature request is to expose `onDidOverrideDimensions` and `setDimensions` equivalent on `Terminal` objects that would allow to:
1. Override current terminal dimensions
2. Get current max dimensions as allowed by UI
3. Know when max dimensions change (say when users resize UI).

cc @lostintangent, @Tyriar

**Comment by Tyriar** [comment]
@IlyaBiryukov I remember chatting with you about this in the past, has this just never worked properly for Live Share?

**Comment by IlyaBiryukov** [comment]
@Tyriar it works for pseudoterminal-backed terminals that Live Share creates on its own. Pre-existing terminals, those that users create without Live Share, don't have means to change dimensions (the property is read-only) and there is no event to know when the max dimensions have changed due to UI changes. I don't think it ever worked for them.

**Comment by Tyriar** [comment]
> there is no event to know when the max dimensions have changed due to UI changes

@IlyaBiryukov there is an event for this, the dimensions just can't be changed by extensions yet:

https://github.com/microsoft/vscode/blob/94c6893cad0fd68032905b0a622822951c96c873/src/vs/vscode.proposed.d.ts#L824-L829

**Comment by Tyriar** [comment]
Proposal:

```ts
export interface Terminal {
	/**
	 * The current dimensions of the terminal. This will be `undefined` immediately after the
	 * terminal is created as the dimensions are not known until shortly after the terminal is
	 * created.
	 */
	readonly dimensions: ITerminalDimensions | undefined;

	// actualDimensions?
	// overrideDimensions?
	overriddenDimensions: ITerminalDimensions | undefined;
}

export namespace window {
	/**
	 * An event which fires when the [dimensions](#Terminal.dimensions) of the terminal change.
	 */
	export const onDidChangeTerminalDimensions: Event<TerminalDimensionsChangeEvent>;
}
```

This uses similar language to the `Pseudoterminal` API where "dimensions" are the container dimensions and "override dimensions" are the actual terminal dimensions.
