### ISSUE TITLE
Cannot download extensions

### ISSUE THREAD

**Issue by engnaruto** [microsoft/vscode#79245]
Issue Type: <b>Bug</b>

When I click on an extension I won't be downloaded and VS Code says "Failed to install ... " and suggests to download it manually.

And when I download the extension manually and install it, it is installed normally.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2523)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.57GB (1.05GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
gitlens|eam|9.9.3
prettier-vscode|esb|1.9.0
code-runner|for|0.9.13
vscode-docker|ms-|0.7.0
debugger-for-chrome|msj|4.11.7
java|red|0.47.0
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.2
vscode-maven|vsc|0.18.1

</details>

**Comment by engnaruto** [comment]
This is the logs:

`[2019-08-15 22:43:04.348] [sharedprocess] [info] main {"machineId":"269d6f9a552f76bc2f8ff35bf03b3c63c85c883329f240d44e6e3075467f2fab"}

[2019-08-15 22:43:11.836] [sharedprocess] [info] Installing extension: ms-python.python
[2019-08-15 22:43:12.096] [sharedprocess] [info] Installing extension: vscjava.vscode-java-test
[2019-08-15 22:43:13.627] [sharedprocess] [error] Failed to install extension: ms-python.python 
[2019-08-15 22:43:14.593] [sharedprocess] [error] Failed to install extension: vscjava.vscode-java-test 
[2019-08-15 22:43:44.368] [sharedprocess] [info] Starting to clean up unused language packs.
[2019-08-15 22:56:27.937] [sharedprocess] [info] Installing extension: ms-python.python
[2019-08-15 22:56:29.337] [sharedprocess] [error] Failed to install extension: ms-python.python `

**Comment by gjsjohnmurray** [comment]
/duplicate See #78783 for info about how others have tracked this down to a DNS issue
