### ISSUE TITLE
Saving of a new file is causing didOpen and didChange -- causing duplicate text

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#79252]
- VSCode Version: 1.37.1
- OS Version: Windows (probably others)

Steps to Reproduce:

1. I used the C/C++ extension, but it should repro with other extensions that use the vscode-languageclient.
2. Do the repro steps in bug https://github.com/microsoft/vscode-cpptools/issues/4091 , which create a new file, set to C++, paste some code, save the file.

Bug: Our C/C++ gets sent a didOpen with the document text, but then we get sent a duplicate didChange with the file contents, causing our language server document to have duplicate text.

This seems like a VS Code bug, but let us know if where somehow using the APIs incorrectly or if there is some workaround you recommend we do.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Two things that you need to be aware of

* when change the language of a document a `onDidClose` and `onDidOpen` sequence is triggered, see [here](https://github.com/microsoft/vscode/blob/29be8d6125183f7e58d16bcb6f06ee3edd91397a/src/vs/vscode.d.ts#L7857-L7858)
* when saving an `untitled` document it is being closed and a new one, using the `file` scheme is created.

**Comment by bobbrow** [comment]
What @sean-mcmanus is trying to say is that we are receiving what seems to be incorrect LSP messages:

First we get a textDocument/didOpen with the full contents of the file in the "text" property
```
{
    "jsonrpc": "2.0",
    "method": "textDocument/didOpen",
    "params": {
        "textDocument": {
            "uri": "file:///d%3A/test/customer4091/1.cpp",
            "languageId": "cpp",
            "version": 2,
            "text": "void\r\nfoo()\r\n;"
        }
    }
}
```
Then we get a textDocument/didChange with the full contents of the file inserted at position 0,0
```
{
    "jsonrpc": "2.0",
    "method": "textDocument/didChange",
    "params": {
        "textDocument": {
            "uri": "file:///d%3A/test/customer4091/1.cpp",
            "version": 2
        },
        "contentChanges": [
            {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 0
                    }
                },
                "rangeLength": 0,
                "text": "void\r\nfoo()\r\n;"
            }
        ]
    }
}
```
But now that I am pasting this, I see that the version of the TextDocument did not change and maybe we can use this to ignore the didChange message.

**Comment by sean-mcmanus** [comment]
@bobbrow Yeah, we can check the version to fix this, but the LSP spec seems to suggest the version is supposed to get incremented after a change, but the behavior of didChange is that the version is incremented before: "A TextDocumentEdit describes all the changes on a version Si and after they are applied move the document to version Si+1", but the didSave that occurs afterwards still has the 2 version. I guess the spec is just worded incorrectly?

**Comment by sean-mcmanus** [comment]
@jrieken Yeah, I just fixed it by ignoring didChange messages if the version is less than or equal to the last seen version from didOpen/didChange. Let us know if that is not the correct fix.

**Comment by jrieken** [comment]
Re-opening and assigning to @dbaeumer for comment

**Comment by dbaeumer** [comment]
Here is what I see with a JS document:

```
[Trace - 11:24:43 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1",
        "languageId": "javascript",
        "version": 1,
        "text": ""
    }
}
[Trace - 11:26:02 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1",
        "version": 2
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": "console.log();"
        }
    ]
}
[Trace - 11:26:48 AM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/dirkb/Projects/mseng/VSCode/Playgrounds/linters/lib/1.js",
        "languageId": "javascript",
        "version": 1,
        "text": ""
    }
}


[Trace - 11:26:48 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/dirkb/Projects/mseng/VSCode/Playgrounds/linters/lib/1.js",
        "version": 2
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": "console.log();"
        }
    ]
}
[Trace - 11:26:48 AM] Sending notification 'textDocument/didClose'.
Params: {
    "textDocument": {
        "uri": "untitled:Untitled-1"
    }
}
```

Which is actually correct (note that the original open has an empty content). I also debugged the VS Code extension API and the API does send an open with an empty content and then the change and then a save.

@bobbrow I know you are doing a lot of tricks in your middleware. Are you sure this is nothing you cause?

**Comment by bobbrow** [comment]
Looking at my middleware code, I don't see anything that modifies the content of the TextDocument, but I do see that the version of the TextDocument changes while I am still processing the didOpen event if I insert logging at the beginning and end of the logic:

begin didOpen: d:\test\customer4091\2.cpp - version: 1
end didOpen: d:\test\customer4091\2.cpp - version: 2

Is `vscode-languageserver-node` equipped to work with middleare that does async work?  Our callback for didOpen queues async tasks as part of its execution.  It looks like the callback for didOpen doesn't currently return a promise since we're managing stuff in our own queue.  It seems that the TextDocument object passed to us in didOpen is a reference, not a copy based on the logging I'm seeing.  We could probably fix this by taking a copy of the TextDocument in our tasks if async is not supported here.  Should we be doing this, or should `vscode-languageserver-node` be giving us const inputs?

**Comment by dbaeumer** [comment]
@bobbrow this is something you need to do since I can't make the VS Code API consts. You can't queue stuff in the middleware and process it later since the VS Code API only guarantees data consistency during the life time of one callback. What happens in your example is that when you receive the open event the text document will have a empty content but when you process it you have already the change in there that VS Code is applying. 

If you need to do tricky things you need to capture the state by yourself and send the LSP notifications / requests by yourself.

**Comment by dbaeumer** [comment]
Just to clarify: the same would happen with an extension only using VS Code API. If you would react to an open event and then keep the event and process it later the text document wouldn't have the state of the open event. Text Documents are not value objects.

**Comment by bobbrow** [comment]
Thanks for confirming.  We'll stash a copy of the object.
