### ISSUE TITLE
`<dir>/` on new file creates new directory

### ISSUE THREAD

**Issue by t-eckert** [microsoft/vscode#79259]
## Context

I love the feature in VS Code where `explorer.newFile` can be used to create files in directories:

1. `explorer.newFile`
2. Type `src/main.ts`
3. File `main.ts` is created in a new directory called `src`.

I would enjoy this feature being expanded to include the creation of empty directories. 

## Proposed Behavior

1. `explorer.newFile`
2. Type `src/`
3. An empty directory called `src` is created.

## Current Behavior

1. `explorer.newFile`
2. Type `src/`
3. Error toast! 

``` text
Unable to write file (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/path/to/src/')
```

I assume this is caused because the process first checks if the dir exists before creating the file.

## Concerns

I have `explorer.newFile` mapped to `command` + `n`. This generalizes the idea of the command to be "new `x`" in my mind. The actual name of the command "newFile" doesn't map to the idea of creating a new directory. An alternative to this could be to add a command `explorer.newFileOrDirectory` which exhibits the behavior described.

**Comment by isidorn** [comment]
There is `exploerr.newFolder` please use that as a workaround.
Leaving this open as a feature request.
