### ISSUE TITLE
Allow postMessage to support blobs

### ISSUE THREAD

**Issue by ikeough** [microsoft/vscode#79257]
The setup is as follows: We have a a web view extension to which we post messages. We would like to read a file in the workspace and send that file's data to the extension using the `WebView.postMessage(...)` API. 

Unfortunately, all attempts to post a message that is not a string have resulted in the receiver getting nothing. If I convert the file data to base64 I can send it successfully. The files we are using are on the order of 10mb. Not huge, but not super quick to convert to base64 and then back to a Blob on the receiving end.

One excellent solution would be to support [Transferable Objects](https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast).  I suspect that the `WebView.postMessage` API is doing something to disallow this, perhaps for security reasons, but it'd be really useful.

Thanks!

**Comment by mjbvz** [comment]
Note that extensions are run in an entirely different context from webviews (and potentially on completely different machines) so we cannot support transferable objects. Maybe `ArrayBuffer` but probably not `Blob` (which is web specific)

**Comment by ikeough** [comment]
That makes sense. ArrayBuffers then? :)

**Comment by RandomFractals** [comment]
I ran into this issue too while adding Apache Arrow data support to my Data Preview 🈸 extension. 

It took some hours of digging as well to figure out that Blobs and Transferable Objects can't be posted to webview html part. @mjbvz would be nice if this was documented somewhere in webview ext. development guides or examples.

@ikeough I ended up using TypedArray to trasfer that binary data to web view. 

Feel free to pick code snippets for that binary data setup from my ext:

https://github.com/RandomFractals/vscode-data-preview/blob/master/src/data.preview.ts#L531

https://github.com/RandomFractals/vscode-data-preview/blob/master/templates/data.view.html#L187

**Comment by ikeough** [comment]
This is really useful. Thanks @RandomFractals!

**Comment by mjbvz** [comment]
Based on the discussion, I've documented what postMessage supports in b9eeccc. I do not think actually allowing posting of blobs (or other dom types) will be possible due to how VS Code's extensions are run

Adding to August and marking as verified for updating documentation
