### ISSUE TITLE
My .vue file no longer highlighted

### ISSUE THREAD

**Issue by miaoihan** [microsoft/vscode#79265]
After updating the latest version, my Vetur plug doesn't seem to work anymore

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.3.0

**Comment by gjsjohnmurray** [comment]
The extension's repo has [this FAQ section](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#no-syntax-highlighting--no-language-features-working) by @octref. Maybe it can help you.

**Comment by octref** [comment]
Likely because VS Code messed up the upgrading extension process and installation is complete. Try the link by @gjsjohnmurray above. Thanks!
