### ISSUE TITLE
Expose GUI settings editor to other files/APIs

### ISSUE THREAD

**Issue by nickmccurdy** [microsoft/vscode#79263]
The settings GUI is very useful to help users discover functionality and configure the editor with less technical knowledge, but I think this could apply to most JSON configuration files edited in VSCode, and not just its own settings. If APIs were provided that allowed extensions to use the settings GUI for other JSON files (or possibly even dynamic adapters), this GUI editor functionality could be provided in many more situations.

## API design
I'm new to extension development, but based on my limited understanding, here are some ideas of how this could look for extension developers:

### Static files
`contributions.fileConfiguration` file in `package.json` that's similar to `contributions.configuration` but mapping to custom JSON files rather than VSCode configuration files.

### Dynamic adapter API
Can be used to open a custom settings panel with objects in the format of `contributions.configuration` and provide either a JS object or WorkspaceConfiguration instance  for in-memory usage or custom serialization (for example, configuration file formats other than JSON).

### Internal usage
VSCode could potentially include its own optional GUIs for common configuration files or try to infer what types/values are allowed in certain configuration fields from existing JSON schema definitions (for example, converting a boolean field to a checkbox, or a string field to an input/textarea).

## Example use cases
- Letting users understand the structure of a configuration file proactively, rather than having to fix JSON schema invalidations
- Text fields for common metadata in package.json files, similar to what `npm/yarn init` already generate except as a GUI
- Toggling boolean `compilerOptions` in `tsconfig.json`
- Showing all possible values for an enum-like field, such as `compilerOptions.target`
- Replicating Code Sandbox's GUI editor for Prettier's configuration file ([screenshot](https://imgur.com/a/SOCWxQg))

**Comment by roblourens** [comment]
The settings editor is quite specific to our settings, it doesn't handle arbitrary json shapes. There are even a large number of settings that it doesn't handle. I don't plan to provide an arbitrary json editor but this has come up before so I can leave it open for now.

**Comment by nickmccurdy** [comment]
Do you think it would be feasible to abstract the settings editor UI and the settings it generates, so the settings serialization can be refactored to use it while other code could use it for JSON generation? As far as arbitrary JSON goes, I'm thinking it would work similarly to the existing settings editor UI, where the portion of the file with the matching property is highlighted for manual editing. If the file isn't JSON, there could be a fallback API/event to handle unknown data type editing, perhaps with a custom UI or file location provided by the extension.

I understand this API/feature may not be necessary for VSCode internally, but I'd like to develop extensions with it, and I'd like to try implementing it if it's not too complex.

**Comment by roblourens** [comment]
I don't think a feature like that really fits in vscode's core right now, but you might be interested in our webview extension api: https://code.visualstudio.com/api/extension-guides/webview

**Comment by nickmccurdy** [comment]
Thanks for the information. Does the implementation of the settings editor UI use webviews, or does it rely on internals that would need to be reimplemented for this to work in an extension?

**Comment by roblourens** [comment]
Yeah it relies on internals and couldn't be ported to an extension easily.

**Comment by nickmccurdy** [comment]
If this isn't going to be supported in VSCode internally, I can close the issue and potentially reimplement something similar in an extension.
