### ISSUE TITLE
Cannot type Vietnamese chacracters on file markdown

### ISSUE THREAD

**Issue by nmhillusion** [microsoft/vscode#79270]
Issue Type: <b>Bug</b>

* Visual Studio Code version: 1.37.1
* OS: Window 10. Version	10.0.16299 Build 16299

Steps:
1. open VS Code
2. create file demo.md
3. Input "# Chủ đề 1". 
4. See characters: "# Chu de 1"

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
prettier-vscode|esb|1.9.0
beautify|Hoo|1.5.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.6.2
python|ms-|2019.8.30787
cpptools|ms-|0.24.1
oracle-plsql|myc|1.0.3
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by rebornix** [comment]
@nmhillusion do you see the same issue while typing Vietnamese in other files with different languages?

**Comment by nmhillusion** [comment]
> @nmhillusion do you see the same issue while typing Vietnamese in other files with different languages?

No, I tried typing Vietnamese in `C` file, `HTML` file and `Javascript` file, but it works correctly.

**Comment by rebornix** [comment]
that's weird, there should be no difference between writing in a markdown file or other languages. Do you have preview open when writing in the markdown file?

**Comment by nmhillusion** [comment]
I also recorded a video about what things I do, please take time to watch it: [Link video](https://1drv.ms/v/s!Aq4gvH3LzuOqhH9n-ZfAsYw_jpNo)

**Comment by tienlocnguyen** [comment]
Do you use Markdown All in One extension? I have same problem with it

**Comment by nmhillusion** [comment]
@tienlocnguyen You right. I tried to uninstall it and now I can type Vietnamese normally. Thank you!
