### ISSUE TITLE
Vs code Open file Explorer Can't automatically track file location. 

### ISSUE THREAD

**Issue by AtlantisDe** [microsoft/vscode#79272]
### 
```c#
Vs code Open file Explorer Can't automatically track file location. 
This feature is normal in previous versions. 
After updating this version, it won't work.

Occasionally, occasionally
```

### Like this
![avatar](https://i.ibb.co/GsC1P4Z/location.png)

### open two workspaces and all extensions are disabled

I don't know why? I opened, two processes, open different folders, 
such as opening a file at the same time,
 one working folder can be located to the file location, 
another working folder, can not locate the file location

#### this workspace  can    automatically track file location

![avatar](https://i.ibb.co/X5GCVVV/1.png)
![avatar](https://i.ibb.co/Pw6qXBL/2.png)

I don't know why? I opened, two processes, open different folders, 

### version info
```c#
版本: 1.37.1 (user setup)
提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
日期: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo are you talking about the behaviour controlled by the autoReveal setting?

What version did you upgrade from and notice the change? 

Does the problem also happen when you run with all extensions disabled?

**Comment by AtlantisDe** [comment]
@gjsjohnmurray thanks .i don't know how to do.now

**Comment by gjsjohnmurray** [comment]
@AtlantisDe it looks like you tried to paste images into your original post, but the links don't work for me.

Does the `explorer.autoReveal` setting exist in the workspace-level settings file .vscode/settings.json for either of your workspaces?

**Comment by AtlantisDe** [comment]
@gjsjohnmurray 
I am sure that it is a folder, and occasionally it will not work properly. I am now all replaced, the  workspace open.
