### ISSUE TITLE
New Octicons don't have enough contrast

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#79278]
Related #76909

## Old
![image](https://user-images.githubusercontent.com/900690/63147493-a279cb00-bffe-11e9-9956-7b5a7038b789.png)

## New
![image](https://user-images.githubusercontent.com/900690/63147499-a86fac00-bffe-11e9-8221-f4e8624e610a.png)

## Bold
![image](https://user-images.githubusercontent.com/900690/63147536-bde4d600-bffe-11e9-8689-20e4607a59aa.png)

This feedback is not around the shape of the icon but the fact that our current octicons all have a solid background applied which puts a very nice contrast on top of the status bar. With the new transparent icons we are loosing this contrast. They almost look like the reverse icon of what we have today (e.g. now transparent where we used to have white background).

_Originally posted by @bpasero in https://github.com/microsoft/vscode/pull/79234#issuecomment-521899520_

**Comment by strafbier** [comment]
I think when they were implemented they were designed and tested on high-dpi screens. 
For more "traditional" setups like 24" 1080p, they look blurry because they get antialiased to transparency.
![Screenshot from 2019-08-16 08-58-45](https://user-images.githubusercontent.com/3565347/63149444-76614880-c004-11e9-9abf-fa76cd308ce0.png)

**Comment by misolori** [comment]
@strafbier this issue is about Octicons in the status bar and quick pick, not the activity bar.

[See this comment](https://github.com/microsoft/vscode/issues/8017#issuecomment-502809582) about why they appear blurry.

**Comment by ErikHumphrey** [comment]
The solid icons would be fine if they had the same positioning/height/spacing as New and Bold, rather than appearing as off-center or not taking up enough of the space on the status bar.

**Comment by sstaub** [comment]
The new icons are horrible designed and not helpful for perception.

**Comment by misolori** [comment]
@sstaub can you elaborate? Are you referring to our new icons everywhere or just the Octicons?

**Comment by sstaub** [comment]
Both, the icons on the sidebar also on the statusbar (insider version).
The buttons and symbols on statusbar and sidebar were better before, because they had a better contrast.
Maybe we can choose between old and new design in settings.

**Comment by misolori** [comment]
Thanks everyone for the feedback. In trying to keep our issue count on a manageable level, I'm going to close this issue as a duplicate of https://github.com/microsoft/vscode/issues/79130 since that will solve this issue. Please upvote the issue there.
