### ISSUE TITLE
Shortcut Key to Full Restart VS Code

### ISSUE THREAD

**Issue by CyberSharky94** [microsoft/vscode#79271]
![vs_code_restart_issue_160819](https://user-images.githubusercontent.com/7389582/63144156-28f4d380-c024-11e9-8478-4c023c347e9b.png)
Issue Type: <b>Feature Request</b>

Hi!
I'm requesting for a feature to Full Restart Visual Studio Code on Windows.

The issue here is when PHP version has been changed and all PATH variable has been updated, Terminal inside VS Code won't take effect until full restart of the application.

I need to close the VS Code. And start it again. Then the changes on the PATH environment variable will take effect.

Thank you. Regards. 😊

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
Just assign a shortcut to the following action `workbench.action.reloadWindow`
