### ISSUE TITLE
Setting "terminal.integrated.cwd": "${fileDirname}" makes fallback to workspace not working

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode#79281]
- VSCode Version:
```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
- OS Version: `Microsoft Windows [Version 10.0.18362.295]`

Steps to Reproduce:

1. Follow "Variables resolved in settings" guide (from release notes) and set: `"terminal.integrated.cwd": "${fileDirname}"`
2. Press `CTRL+N` (New File)
3. Press `CTRL+<backtick>` (`View: Toggle Integrated Terminal`)
4. Observer error: `The terminal shell CWD "${fileDirname}" does not exist`

Expected behaviour:

If the path does not exist, fallback to default `${workspaceFolder}` / `${workspaceRoot}` location?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Good idea 😄
