### ISSUE TITLE
onDidCloseTextDocument  document.getText()  returns empty string for a saved file.

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#79287]
- VSCode Version:1.37.0
- OS Version:WINDOWS_NT

Steps to Reproduce:
(please change the extension.txt to extension.js type).
1. Copy the extension.js and ddl.txt file attached in the comment.
2. place it in the HelloWorld extension
3. start debugging and select Hello world from the palette.
4. close the file and see the console you will see that document.getText() returned nothing.

[ddl.txt](https://github.com/microsoft/vscode/files/3508597/ddl.txt)
[extension.txt](https://github.com/microsoft/vscode/files/3508598/extension.txt)

Thanks,
Akhil

**Comment by jrieken** [comment]
Works for me... Not sure what you are seeing but simply logging the text content *without* printing`document.uri` is most likely misleading you.

**Comment by akhilravuri1** [comment]
Hi @jrieken 
Are you able to see the data of ddl.txt file in the console?
Thanks,
Akhil.
