### ISSUE TITLE
Performance degradation in a few minutes

### ISSUE THREAD

**Issue by juniordiscart** [Microsoft/vscode#7928]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open (relatively) large C# Unity project (±420 scripts)
2. Work for about 10-15 mins

Hi
Since update 1.2 (still persists in v1.2.1) Visual Studio Code started having performance degradation after a few minutes of working. The Intellisense is fluent and rapid in the first few minutes (< 1second for suggestion) but gradually takes more time to process information (> 60 seconds for suggestion).
I use the legacy C# plugin to work with a Unity project. The most up-to-date C# extension is not installed. I tried various suggestions I found here (i.e. disabling Git, excluding certain folders), but the issue keeps creeping in. I currently quickly kill VSCode and start the project back up to have a fluent intellisense for a few minutes.

Any help or light that can be shed on the matter?

Thank you.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#590
