### ISSUE TITLE
Using -1 to go to the last line of a file.

### ISSUE THREAD

**Issue by EricDepagne** [microsoft/vscode#79286]
Ctrl+g allows us to jump to any line in the editor.
If I want to go the the last line of the file, I must enter the line number of this line, which means looking at the dialog box to know what it is.
It would be convenient if we could use negative indices to jump to lines starting from the bottom of the file (-1 being the last one, -2 the one before, aso).

**Comment by hanq08** [comment]
I'd like to work on this. Let me know if it's ok. thanks @alexandrudima

**Comment by SneakyFish5** [comment]
I've got a commit here that works on my local build, if you want to test it and let me know any feedback it'd be much appreciated before I go ahead and open a PR.

https://github.com/SneakyFish5/vscode/commit/5f0ef6837ba00850cf13b2f19428416cf0956ef2

**Comment by hanq08** [comment]
@SneakyFish5 looks good. similar to what i've implemented :thumbsup:

**Comment by SneakyFish5** [comment]
Thanks @hanq08, I'll go ahead and open the PR then :)

**Comment by EricDepagne** [comment]
Wow, thanks a lot guys for such a quick implementation!
