### ISSUE TITLE
VS Code does not update, but offers download instead

### ISSUE THREAD

**Issue by Tim-Veestraeten** [microsoft/vscode#79283]
![image](https://user-images.githubusercontent.com/33923948/63149746-46ff0b80-c005-11e9-8bf6-acbffdebb6b5.png)
Instead of offering "restart to update", VS code links to a zip file: https://az764295.vo.msecnd.net/stable/f06011ac164ae4dc8e753a3fe7f9549844d15e35/VSCode-win32-x64-1.37.1.zip, which is opened in de default browser. I've been having this issue for months now and i have been manually downloading the installers for the newer versions and running those.

- VSCode Version: 1.37.0 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open vs code
2. Let it check for updates

My update setting are the default: 
"update.enableWindowsBackgroundUpdates": true
"update.mode": "default"
"update.showReleaseNotes": true

I never had this issue with the insiders build, which is an user setup too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you fully uninstall VS Code and reinstall it?
