### ISSUE TITLE
`editorOverviewRuler.bracketMatchForeground` not hot reloaded

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#79288]
Issue Type: <b>Bug</b>
```json
"workbench.colorCustomizations": {
    "editorOverviewRuler.bracketMatchForeground": "#0011ff",
}
```

VS Code version: Code - Insiders 1.38.0-insider (c23cacdc97b54e6056400599dad329cabc7facfb, 2019-08-16T06:35:26.375Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
Works again. No idea.

**Comment by ArturoDent** [comment]
Actually in my testing this is one of the "few" `colorCustomizations` that seems to require a **reload** to take effect. 

 Is that expected behaviour?  Something different about the `overviewRuler`?
