### ISSUE TITLE
Fill selected text into file open panel(ctrl+p) similar to search panel(ctrl+f)

### ISSUE THREAD

**Issue by rajatkantinandi** [microsoft/vscode#79292]
Currently when we select a text & press ctrl+f it fills the search panel with that text & we can easily search for the text, which is really nice.

But when we press ctrl+p while some text is selected, it does not fill the text in the file open panel. So in order to search for a file with the filename available in some part of the source code we need to copy the text & press ctrl+p & then paste it before searching.

It would be nice to have the selected text already available in the file search panel similar to text search(ctrl+f).

That would make our life much easier I guess.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=colch.quick-open-prefill-selection

**Comment by rajatkantinandi** [comment]
@usernamehw 
Cool..
Thanks for the info..
I guess vscode should have it by default or maybe an option in setting to turn on this behaviour.

**Comment by usernamehw** [comment]
It was already discussed. The general rule is: What can be done from an extension - should be so.
