### ISSUE TITLE
Can't set custom web browser

### ISSUE THREAD

**Issue by hubitor** [microsoft/vscode#79290]
I use Waterfox as default system browser. I don't want that VSC uses this browser for opening windows, I would like that VSC uses another browser such as Brave or Vivaldi instead. I tried to set Chrome since it was already in the dropdown menu with this setting: "liveServer.settings.CustomBrowser": "chrome"
but it doesn't work. VSC keeps opening the windows in Waterfox.

I tried with this setting:
"liveServer.settings.AdvanceCustomBrowserCmdLine": "/usr/bin/google-chrome-stable"
but it doesn't work either.

- VSCode Version: 1.37.0
- OS Version:  Linux x64 5.1.16-arch1-1-ARCH

Steps to Reproduce:
For example:
1. Create an Express App
2. Add an URL like this:
```
app.listen(3000, "0.0.0.0", function() {
  console.log(
    "Navigate to http://localhost:3000/index.html"
  );
});
```
3. Press Ctrl -C to open the link.

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Please open issue for the livereload extension. For the links in VS Code, we can only open in your system's default browser. When you are on Linux, read your distro's doc for how to change default browser.
