### ISSUE TITLE
Can't change folder name in wsl

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/vscode#79297]
I am coding in wsl environment. I can't change folder name.

**Comment by lengthmin** [comment]
https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace

if you're using WSL1, this link can solve the problem.

**Comment by aeschli** [comment]
Thanks @lengthmin, yes, that the way to go.
