### ISSUE TITLE
TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by ArtemHarchishin** [microsoft/vscode#79299]
While trying to configure and run a PyTest, I struck across the following error.

_TypeError: Cannot read property '$' of undefined_

While it seems the test case ran nicely, however, the final output has a specific error message as shown above.

Create a test suite in python (I choose pytest)
Run Python: Discover Tests and choose test directory appropriately and then run them.
Scroll down to output message at the bottom and notice the error
See error message which says TypeError: Cannot read property '$' of undefined
Expected behavior
Notice the error message which says TypeError: Cannot read property '$' of undefined

**Comment by Angel0726** [comment]
I've the same problem，do you have resolved it?

**Comment by Angel0726** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!
I've the same problem，do you have resolved it?How can I resolve the problem？

**Comment by willijk** [comment]
@Angel0726 Have you solved the problem yet? I encounter the same issue but I still new to `pytest` and I don't know how to fix it. I really don't know which extension causes the issue.

**Comment by Angel0726** [comment]
> @Angel0726 Have you solved the problem yet? I encounter the same issue but I still new to `pytest` and I don't know how to fix it. I really don't know which extension causes the issue.

I have not solved this problem yet. but I find the pytest is working with the command 
/usr/bin/env python3 -m pytest "test_in_fc.py". so I use the code Runner with #!/usr/bin/env python3 -m pytest in the head of the file
![image](https://user-images.githubusercontent.com/32816780/65564472-9bd85f00-df7f-11e9-8bb4-151051242242.png)
![image](https://user-images.githubusercontent.com/32816780/65564496-adba0200-df7f-11e9-8a62-f2c4db86f172.png)
