### ISSUE TITLE
Environment variables are not passed to tasks in 1.37

### ISSUE THREAD

**Issue by deitry** [microsoft/vscode#79291]
- VSCode Version: 1.37.1
- OS Version: Kubuntu 18.04

Steps to Reproduce:

0. (VS Code launched via link in application launcher panel or through system hotkey, i.e. not as `code .` in terminal)
1. Add task 
```json
{
    "label": "format all",
    "command": "yapf",
    "args": [
        ".", "-i", "-vv", "--recursive",
    ],
    "problemMatcher": []
},
```
2. Run task. Expected success, got `The terminal shell path "yapf" does not exist` instead. I didn't test it on 1.37.0, but in 1.36.1 it works fine. `yapf` executable located in `~/.local/bin/yapf`.

Task run correctly if I run Code as `code .` in Guake/ZSH since it gets correct environment.
Also task runs correctly if I extract command to `./script`:
```bash
#!/bin/bash
yapf . -i -vv --recursive
```
and launch it as shell task:
```json
{
    "label": "format all 2",
    "type": "shell",
    "command": [
          "./script"
    ],
    "problemMatcher": [],
},
```

I guess this is somehow connected to issue discussed in https://github.com/microsoft/vscode/issues/78898 

---
Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
If you run `yapf . -i -vv --recursive` in the integrated terminal directly does it have your environment?

**Comment by deitry** [comment]
Yes, it works as expected if launched in the integrated terminal.

**Comment by jwhitmarsh** [comment]
Can confirm, I've been confused by this all morning and just realised this is the issue. My simple test case is to create a global env var $VAR = 1

And a task:
```json
    {
      "label": "test",
      "type": "shell",
      "command": "/bin/echo $VAR"
    },
```

Which prints nothing. But running `echo $VAR` in the integrated terminal prints 1.

**Comment by Tyriar** [comment]
Where is `~/.local/bin/` added to the environment?

**Comment by deitry** [comment]
It's in the `.zshrc`.
Also i have these in User Settings:
```json
"terminal.integrated.shell.linux": "/bin/zsh",
"terminal.integrated.shellArgs.linux": ["-i"],
```

**Comment by Tyriar** [comment]
@alexr00 the `["-i"]` might be thee problem? This seems related to that issue where bashrc wasn't being sources in tasks?

If this is the root cause of the problem you should move your setup into your profile file, not rc file and/or source your rc file from your profile. The profile is meant to set up the environment, the rc file is meant to run in interactive shell sessions which tasks isn't (isn't anymore?).

**Comment by alexr00** [comment]
Tasks never ran interactive. It has always run with the `-c` argument (ex. `/bin/zsh -c /bin/echo $VAR`) which with bash means that the session isn't interactive and isn't logon (no rc and no profile). 

The `-i` should cause it to be interactive and source the rc file. Maybe there is some bug where that `-i` isn't making it in anymore. @deitry can you try add this into your task:
```
			"linux": {
				"args": ["-c", "-i"]
			},
```

**Comment by alexr00** [comment]
@deitry were you using the snap package?

**Comment by deitry** [comment]
@alexr00 
No, I don't use snap packages.

On issue: this configuration works for me right now (1.38.1 Stable):
```json
// settings.json
"terminal.integrated.shellArgs.linux": ["-i"],

// tasks.json
{
    "label": "yapf",
    "command": "yapf",
    "type": "shell",
    "args": [
        ".", "-i", "-vv", "--recursive"
    ],
    "problemMatcher": []
}
```

> Tasks never ran interactive

If it wasn't supposed to be that way, I guess current behavior is fine and the fact that my first task worked well was the real issue.

**Comment by alexr00** [comment]
There is some code that tries to capture the environment for VS Code, and I know there have been issues with that in the past. There are many root causes for it (one being the snap issue). Most likely something changed and this code stopped working for you.
