### ISSUE TITLE
 Search all files in specified folder for mac

### ISSUE THREAD

**Issue by masahirokjp** [microsoft/vscode#79309]
Issue Type: <b>Feature Request</b>

In the Windows version, you can search all the files in the folder specified in the file explorer, but since it is not possible in the Mac version, please add a function.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
This works just fine on the mac
![Screenshot 2019-08-16 at 17 21 31](https://user-images.githubusercontent.com/1926584/63178427-505e9700-c04a-11e9-8dbb-01bc77e49d17.png)

**Comment by masahirokjp** [comment]
Check in all languages. Not displayed in Japanese version.
Do not close all versions without checking them.

**Comment by masahirokjp** [comment]
> This works just fine on the mac
> ![Screenshot 2019-08-16 at 17 21 31](https://user-images.githubusercontent.com/1926584/63178427-505e9700-c04a-11e9-8dbb-01bc77e49d17.png)
Check in all languages. Not displayed in Japanese version.
Do not close all versions without checking them.

**Comment by isidorn** [comment]
@masahirokjp this is unrelated to the language used.
Please try using vscode insiders https://code.visualstudio.com/insiders/
