### ISSUE TITLE
Debug Console window doesn't get focused when debugging a TypeScript project

### ISSUE THREAD

**Issue by tedstoychev** [microsoft/vscode#79307]
### Steps to reproduce

- Open [this example project][1] in Visual Studio Code.
- Open [src/index.ts][2].
- Select 'Debug > Start Debugging (F5)'

The first time we debug the project we'll get the expected behavior:

- The 'Terminal' window will get focused.
- The build task will get executed in the 'Terminal' window.
- After the build task finishes the 'Debug Console' window will get focused.

However every next time we debug the project we'll get this behavior:

- The 'Terminal' window will get focused.
- The build task will get executed in the 'Terminal' window.
- The 'Terminal' window will stay focused even after the build task finishes.

[1]: https://github.com/tedstoychev/159781593781
[2]: https://github.com/tedstoychev/159781593781/blob/master/src/index.ts

Does this issue occur when all extensions are disabled?: Yes

- VSCode Version: 1.37.1
- OS Version: Windows 10 (Build 18362)

**Comment by isidorn** [comment]
Change this option `"debug.internalConsoleOptions": "openOnSessionStart"``
That should help with your issue. If you still see the issue please let me know and we can reopen this. Thanks
