### ISSUE TITLE
指定フォルダ内の全ファイルの検索

### ISSUE THREAD

**Issue by masahirokjp** [microsoft/vscode#79302]
Issue Type: <b>Feature Request</b>

WIndows版ではファイルエクスプローラーで指定したフォルダ内のファイルをすべて検索することが出来るが、Mac版では出来ないため、機能追加してほしい。

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
Please file this issue in english
