### ISSUE TITLE
Enhance vscode to return electron version using command prompt

### ISSUE THREAD

**Issue by bimalkjha** [microsoft/vscode#79305]
Currently, using `code --version` command, we can know the version of vscode.
Also, using Help->About, option in vscode, we can know version of node.js and electron used by the vscode. It would be good to get all information of Help->About, using a single command.
It will help other vscode extension to know the electron version using which it need to be compiled to work with vscode. 
Currently, process.versions.electron gives the version only in vscode console. I want this info from Windows or linux command prompt. Thanks.

**Comment by akhilravuri1** [comment]
Hi @deepak1556 

This issue was labeled as out of scope.
Sorry, may I know why?
We are just asking you to add one more parameter like code --electron or code --electron_version.

Thanks
Akhil
