### ISSUE TITLE
Code gets committed although the pre-commit hook fails

### ISSUE THREAD

**Issue by pedrotainha** [microsoft/vscode#79300]
- VSCode Version: 1.37.1
- OS Version: UBUNTU 18.04.3 LTS

Steps to Reproduce:

1. Add husky pre-commit (to run lint for example)
2. commit message in the left side panel and pre-commit isn't executed

NOTE: using the command line to commit trigger the pre-commit hook and fail as expected

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Works fine for our vscode repository. Just clone it and see for yourself.
Check out how we set it up.

**Comment by joaomoreno** [comment]
> pre-commit isn't executed

You can see in `Git: Show Git Output` the exact git commands and the git version we're using, so you can find out more by running those commands by hand.

**Comment by joaomoreno** [comment]
@pedrotainha Are you using NVM? And are you using VS Code as a snap package?
