### ISSUE TITLE
Allow attaching/detaching from the debug targets

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79314]
This request asks for a lightweight way of attaching/detaching the debugger UI to/from a debug target (in contrast to a heavyweight launch/attach that starts and ends a debug session).

If the debugger UI is detached (in the lightweight way), the debug session will continue to run and the debugger is still in control and can terminate the debuggee, but the debugger will not stop on breakpoints or exceptions because no debugging takes place.

In theory this could be implemented by means of DAP's "attach" and "disconnect" request: a DA is started and attaches to the debug target via the attach request. "Lightweight" detaching disconnects from the debug target via the disconnect request, but the debug adapter continues to run.

@pavelfeldman does this correctly reflect the intent of your item?

**Comment by weinand** [comment]
@connor4312 @roblourens is this feature something you would consume/support in js-debug anytime soon?

**Comment by connor4312** [comment]
While this seems fairly easy to support in js-debug, I'm not sure I really see the use case for this. Were there concrete scenarios we had in mind around it?

**Comment by weinand** [comment]
Pavel brought this up when we discussed the PWA demo:
you can have a long-running debug session (from a VS Code perspective), but a specific target is not affected by debugging at all, as long you are not attached to it (no breakpoints are hit etc.).
Then, when something interesting happens, you can easily attach and gain full control over the target.
Currently, you have to terminate a debug session and start a new (which potentially takes down child processes etc.)

**Comment by connor4312** [comment]
I see. That would work well with the "debugger terminal" that js-debug has. We'll need to put some thought into how the user experience works in the editor, but I'd be willing to support it in js-debug.
