### ISSUE TITLE
Provide a lightweight shell selector without changing default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79313]
I built the https://github.com/Tyriar/vscode-shell-launcher extension which allows the user to create profiles to launch, this is particularly useful on Windows where the user is much more likely to use multiple shells. We have a similar feature in with the default shell selector:

<img width="225" alt="Screen Shot 2019-08-16 at 7 02 34 AM" src="https://user-images.githubusercontent.com/2193314/63173027-da2f4580-bff3-11e9-82e6-5b792bef9474.png">

The issue is that it changes the default setting. It can also only change the shell, not shell args currently which makes supporting multiple WSL distro not possible (https://github.com/microsoft/vscode/issues/77652).

We should add a feature similar to Windows Terminal where current shells are detected and it also enables users to setup their own profiles including shell args.

**Comment by gregvanl** [comment]
Doc feedback verbatim 8/6/2019: "How do I have both an integrated powershell and integrated command prompt and maybe others open at same time?  It only lets me start up a terminal based on the default? So would I just have to change the default all the time? What am I missing?"
