### ISSUE TITLE
today's update for ver 1.38 disable Cmake Extension!

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#79310]
Issue Type: <b>Bug</b>

the following version is ok with cmake extension,but update to today's version ,vs code disabled the cmake extension ,so I can't build code with the cmake-tool.
pls check,tks.

Version: 1.38.0-insider (user setup)
Commit: de320052255d136673fc5eee358f6e2551d6573e
Date: 2019-08-12T07:28:58.576Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18956

VS Code version: Code - Insiders 1.38.0-insider (de320052255d136673fc5eee358f6e2551d6573e, 2019-08-12T07:28:58.576Z)
OS version: Windows_NT x64 10.0.18956
Remote OS version: Linux x64 4.4.0-18956-Microsoft

### **the following new version with the issue :**

Version: 1.38.0-insider (user setup)
Commit: 1c6e25b
Date: 2019-08-16T09:47:47.248Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18956

VS Code version: Code - Insiders 1.38.0-insider (1c6e25b, 2019-08-16T09:47:47.248Z)
OS version: Windows_NT x64 10.0.18956
Remote OS version: Linux x64 4.4.0-18956-Microsoft

**Comment by sandy081** [comment]
@kinglionsz What do you mean by disabling cmake extension? Have you seen it in extensions view? Please provide more information.

**Comment by kinglionsz** [comment]
> @kinglionsz What do you mean by disabling cmake extension? Have you seen it in extensions view? Please provide more information.

I have installed the CMake Tools extension and use cmake build the code.But updated to VS Code version: Code - Insiders 1.38.0-insider (1c6e25b, 2019-08-16T09:47:47.248Z) , the CMake Tools extension seems to be disabled ,so I can't use cmake-tools to build the code.Why?

### **about the issue pls see the screen snip:**

<img width="764" alt="cmake extension disabled-0" src="https://user-images.githubusercontent.com/51827261/63205317-3fa73300-c0d5-11e9-8b8f-742de3b3dce4.png">


### **and cmake tools is ok should be the following  👍**

<img width="829" alt="cmake extension disabled" src="https://user-images.githubusercontent.com/51827261/63205340-a0cf0680-c0d5-11e9-9052-27d07aeb466f.png">
<img width="764" alt="cmake extension disabled-1" src="https://user-images.githubusercontent.com/51827261/63205341-a0cf0680-c0d5-11e9-8389-f1b273843b05.png">

**Comment by nhorlock** [comment]
I can confirm this bug.
As of the last nightly (16th Aug) Cmake Tools no longer activates. The extension shows as installed correctly but there is not a single log line from the extension in any log file. the CMake icon on the left hand toolbar is no longer there, ctrl-shift-p followed by ANY CMake tools command will yield a cmake.<command> not found error. The infor bar that ought to show the build type etc is not active. 

I completely wiped the remote killed all processes and restarted the install and it still fails. Switching back to the latest vscode stable shows that the extension works with the same workspaces.

The breakage only occurs on remote sessions. using cmake tools on a local windows repo works fine. 
My remote machine is running ubuntu 18.04 as per the OP.

`Version: 1.38.0-insider (user setup)
Commit: 1c6e25b87e05a8429c986c59431be77467af9449
Date: 2019-08-16T09:47:47.248Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134`

One observation that may be related but it is not clear why it might be so; the C/C++ extension has an insiders preview version 0.25, this gets installed on the local. It then prompts to install remotely and installs a 0.24 version. It is (slightly) plausible I guess that the version mismatch leads to this

![image](https://user-images.githubusercontent.com/2581250/63217998-59ce2900-c148-11e9-9172-ce6b08743ddd.png)

![image](https://user-images.githubusercontent.com/2581250/63218000-6ce0f900-c148-11e9-8918-a616088dd6fc.png)

**Comment by nhorlock** [comment]
This appears to be fixed in the 19th August nightly

Version: 1.38.0-insider (user setup)
Commit: c8d44e24dd250d416475a10efe64e35c9e2c65b3
Date: 2019-08-19T12:53:53.607Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

@kinglionsz it appears to be fixed for me now. You might want to check if it is fixed for you too.

**Comment by kinglionsz** [comment]
> This appears to be fixed in the 19th August nightly
> 
> Version: 1.38.0-insider (user setup)
> Commit: [c8d44e2](https://github.com/microsoft/vscode/commit/c8d44e24dd250d416475a10efe64e35c9e2c65b3)
> Date: 2019-08-19T12:53:53.607Z
> Electron: 4.2.9
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134
> 
> @kinglionsz it appears to be fixed for me now. You might want to check if it is fixed for you too.

Thank you very much  @nhorlock @sandy081 [c8d44e2] fixed now for me.

**Comment by sandy081** [comment]
Ok, it could have been broken by some intermediate changes. Thanks for update.
