### ISSUE TITLE
(Nightly) Lose ability to open side panel after opening an extension from the new extensions panel

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#7931]
- VSCode Version: `Version 1.3.0-insider (1.3.0-insider)` 06d108b4a0aa6c031e7c1e61a463c069809d6019
- OS Version: `OS X El Capitan 10.11.5`

Steps to Reproduce:

1. Open the extension panel and click on one of the extensions
2. Click on the extension button (on the panel) again to hide the panel (or the shortcut key)
3. (BUG) If you try to click on the extension button yet again to reopen the panel it will open but badly (too narrow and can't be resized)
4. The more you do, the more things start going wrong after this point -- editors go missing, panels can go missing, etc

On the bright side the new extension panel looks great and will be great! :)

**Comment by eamodio** [comment]
This seems fixed by https://github.com/Microsoft/vscode/commit/5474147bb83618975409dad7d8aa96151d7d1ea1

**Comment by joaomoreno** [comment]
Thanks for the issue and the encouragement! 😄
