### ISSUE TITLE
TypeScript setting to control adding space to empty braces

### ISSUE THREAD

**Issue by HaveSpacesuit** [microsoft/vscode#79318]
Issue Type: <b>Feature Request</b>

We have the typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces setting. It would be nice to customize if we want a space added to empty braces or not.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/28678
