### ISSUE TITLE
JS auto import not working: not showing workspace symbols

### ISSUE THREAD

**Issue by Domiii** [microsoft/vscode#79312]
## Problem

I cannot get any symbols to show up in the suggestion menu that are clearly defined inside the workspace  (see screenshots below).

## My environment

I checked out latest insider to reproduce:

> Version: 1.38.0-insider
> Commit: 1c6e25b87e05a8429c986c59431be77467af9449
> Date: 2019-08-16T09:45:29.036Z
> Electron: 4.2.9
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Darwin x64 18.6.0

My workspace and user settings are both empty, using default settings.

## Steps to Reproduce

1. Open workspace
1. Start typing the name of a symbol present inside the workspace (like `EmptyA`, short for `EmptyArray`) - Nothing there! - Screenshot:
![image](https://user-images.githubusercontent.com/282899/63171072-5fa30c00-c06d-11e9-88af-ccee20aa2a77.png)
   * (note that it does suggest built-ins)
1. Make sure, `EmptyArray` actually exists in workspace: 
![image](https://user-images.githubusercontent.com/282899/63172118-88c49c00-c06f-11e9-808f-3b0d3f3ed2f0.png)

## Does this issue occur when all extensions are disabled?

Yes (I ran without extensions; it said extensions were temporarily disabled on start; and problem still there)

**Comment by Domiii** [comment]
A few more notes:

* When renaming something in one file (using `F2`), does not change it when imported in another
* Problem exists in all of my workspaces
* All of this worked just fine until (probably?) a month ago.

**Comment by mjbvz** [comment]
Can you please share a small example project so I can how the code is structured?

Also, do you have a [jsconfig](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson)?

**Comment by Domiii** [comment]
1. Adding a `jsconfig.json` in my `src` folder fixed it o_X
1. At the same time, if I create a new project, things work fine without a `jsconfig.json`.

Thank you so much! At least it's working now!


I have not narrowed down what actually causes the problem (as it can work with and without `jsconfig.json` in difference scenarios), so I'm rather interested:

Any idea why? Is there something I did wrong? In what circumstances do I need a `jsconfig.json`?
