### ISSUE TITLE
Dragging VS Code across two screens with different resolutions fails

### ISSUE THREAD

**Issue by chucklepie** [microsoft/vscode#79311]
- VSCode Version: 1.36.1
- OS Version: Windows 8

I have two screens:
1. 1920x1080
2. 1600x1200

First, note, this fault has only started happening so was probably introduced in the last few updates (unless I really have not dragged across screens for a while!)

When I open up code on one window then drag to the other, it keeps the same size area but then either loses content or adds black space to fill the resolution gap, depending on which direction. 

That probably didn't make much sense, here are some screenshots to explain:

1. I open up vs code on a 1920x1080 screen ok:
![image](https://user-images.githubusercontent.com/12863685/63171422-762c7180-c033-11e9-81a5-344513d748c5.png)

2. I drag it across to the 1600x1200 page and this happens (it truncates the window chopping off the right and bottom):
![image](https://user-images.githubusercontent.com/12863685/63171464-893f4180-c033-11e9-971c-6c155e4160a1.png)

3. I open up vs code on 1600x1200 screen ok:
![image](https://user-images.githubusercontent.com/12863685/63171522-a8d66a00-c033-11e9-881e-10df45e3cf19.png)

4. I drag it across to the 1920x1080 page and I get this (the black is part of the vs code application and the mouse is offset):
![image](https://user-images.githubusercontent.com/12863685/63171585-be4b9400-c033-11e9-8703-673f100f2360.png)

Notes: 
1. On item 4, everything is offset so if I place my mouse halfway into the black area it starts highlighting the min/max/close buttons
2. If I maximise the window, then it all goes back to normal and works

**Comment by deepak1556** [comment]
@chucklepie can you test this with our exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 , thanks!

**Comment by chucklepie** [comment]
So, instead of fixing bugs and testing, you simply say 'why not try the latest dev build and see if it works', then close the case hoping the bug count numbers go down?

**Comment by chucklepie** [comment]
Ok, downloading now. Hope it doesn't break my existing version ;)

**Comment by chucklepie** [comment]
Hello, it works, you can see it visibly resizing the window as you move between screens (presuming it's not an extension issue). When will this be merged into stable release?

btw, thanks, and sorry for being terse :)

**Comment by deepak1556** [comment]
Thanks for testing! you can expect this in insiders within the next 2/3 releases, after which it will get into stable.

**Comment by chucklepie** [comment]
Can this be re-opened, since the version before last it has started happening again, refer to my post and screenshots.

**Comment by deepak1556** [comment]
@chucklepie did you test with the latest insiders release ? https://code.visualstudio.com/insiders/ ,  the fix has only landed there.
