### ISSUE TITLE
VSCode window is resized weird after remote desktop connection

### ISSUE THREAD

**Issue by mbentley00** [microsoft/vscode#79316]
I always have VSCode maximized on my Windows 10 desktop machine. I sometimes reomte into this machine without using VSCode on a laptop with a different resolution. When I log back into my desktop (not through a remote session), the VSCode windows end up extending across two monitors rather than being maximized on one window. No other apps (including regular Visual Studio) have this problem.

**Comment by deepak1556** [comment]
@mbentley00 can you test this with our exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 ? Thanks!
