### ISSUE TITLE
Suggested changes to `workbench.list.keyboardNavigation: simple`

### ISSUE THREAD

**Issue by forrcaho** [microsoft/vscode#79320]
Keyboard navigation of the directory tree works _almost_ the way i want it to with the setting `workbench.list.keyboardNavigation: simple`. There are two things I'd like to change though, either in the behavior of this setting, or as a new setting, or in an extension.

1. I want to always navigate according to the directory tree, regardless of what subdirectories are open. If I collapse the tree before I do keyboard navigation, I always get the behavior I want: I type in the prefix of a subdirectory, open it, type the prefix of the subdirectory under that, etc. This is similar to using the tab key to expand a path on the bash command line. However, if any directories are open in the tree, simple keyboard navigation will jump to the next match that's visible lower in the expanded tree view, regardless of where it is in the directory structure. I don't like this. I like to keep the directories open that I happen to be working in, but I think about locating files in terms of the directory structure. The tree view is transient and I don't want to have to think about what directories happen to be open in the tree at any given time when I'm trying to navigate to a file.

2. When I navigate to a subdirectory that's below the window with keyboard navigation, it scrolls up so that subdirectory is the last visible line in the window. When I then open it, I can't see any of its subdirectories or files; they're all below the window. When I'm using keyboard navigation, I want to be able to see files and directories under a directory I've opened with a right-arrow. Maybe "scroll up when opening a directory" could be a separate setting? I'm not sure whether I'd want it to apply to mouse navigation, though.

**Comment by joaomoreno** [comment]
1. What if you were able to type something like `f/b/vc` to navigate to `foo/bar/vscode` instead? We could use the forward slash as way to navigate in a descending fashion. I know @isidorn thought about this before.

2. Yeah I get the point, yet I'm not so sure it would work out in practice. macOS Finder doesn't, for example. Just select a folder near the end of the viewport and expand it: its children don't get revealed. I think it would be a strange experience. What would happen if it would reveal a **lot** of descendants? What's the expected outcome? Feel free to experiment with making a PR for this and seeing how it behaves. We could potentially put that behind a setting.

**Comment by forrcaho** [comment]
1. I really like the idea of using `/` to descend into subdirectories. The one question I have is, what would the behavior be when a subdirectory prefix is still ambiguous? Perhaps the initial `/` can select and expand the first matching subdirectory, and if that's not the right one, tab will collapse that directory and advance to the next matching subdirectory, expanding it. That's just off the top of my head, so it might not be the best idea, but I think there should be _some_ way to continue keyboard navigation when this happens.

2. I think that perhaps the automatic scrolling of the viewport could be limited to keyboard navigation; I agree it could be disconcerting to have something jump to an unpredictable location when you've just clicked on it with the mouse. I can certainly try to get this working: any hints about where to start looking in the code would be a great help!

**Comment by brightest-dazes** [comment]
Sounds like a great idea everything else in this world is abbreviated.

**Comment by joaomoreno** [comment]
1. I would make it work without automatically expanding/collapsing anything, for now. Just scrolling and focusing the best match. Ambiguity just means multiple items would be possible to navigate to using the arrow keys.

2. You wanna start somewhere around here: https://github.com/microsoft/vscode/blob/1cba911717c27aac7c693cafe0a97e81906c1e41/src/vs/base/browser/ui/tree/abstractTree.ts#L535
