### ISSUE TITLE
CMD + Shift + P to open Command Palette Is Not Working on Mac

### ISSUE THREAD

**Issue by fylzero** [microsoft/vscode#79322]
- VSCode Version: 1.37.1
- OS Version: Mac OS Mojave 10.14.6

Steps to Reproduce:

1. Open VS Code
2. Hold CMD + Shift + P
3. Nothing happens, no command palette.

Does this issue occur when all extensions are disabled?: Yes

Extensions Used:
  Name: DotENV
    Id: mikestead.dotenv
    Version: 1.0.1
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv

  Name: GitLens — Git supercharged
    Id: eamodio.gitlens
    Version: 9.9.3
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

  Name: Image preview
    Id: kisstkondoros.vscode-gutter-preview
    Version: 0.22.2
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview

  Name: Laravel Artisan
    Id: ryannaddy.laravel-artisan
    Version: 0.0.25
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ryannaddy.laravel-artisan

  Name: Laravel Blade Snippets
    Id: onecentlin.laravel-blade
    Version: 1.20.0
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade

  Name: Material Icon Theme
    Id: pkief.material-icon-theme
    Version: 3.8.1
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

  Name: Monokai Pro
    Id: monokai.theme-monokai-pro-vscode
    Version: 1.1.13
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=monokai.theme-monokai-pro-vscode

  Name: PHP Intelephense
    Id: bmewburn.vscode-intelephense-client
    Version: 1.1.6
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

 Name: PHP Namespace Resolver
    Id: mehedidracula.php-namespace-resolver
    Version: 1.1.8
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=MehediDracula.php-namespace-resolver

  Name: Prettier - Code formatter
    Id: esbenp.prettier-vscode
    Version: 1.9.0
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

  Name: Version Lens
    Id: pflannery.vscode-versionlens
    Version: 0.24.0
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens

  Name: Vetur
    Id: octref.vetur
    Version: 0.22.2
    VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=octref.vetur

I had manually disabled all extensions.  Reloaded.  Didn't fix it.
I deleted VS Code and re-installed.  Didn't fix it.
I did a deep clean of VS Code, removed all folders, app, settings.  Reinstalled VS Code and all my extensions.  It started working again for about half a day.
I just tried closing it out and restarted via command line with `code --disable-extensions`.  Still broken.

I use CMD + Shift + P all the time, this is killing me.  Please help!  =)

**Comment by gjsjohnmurray** [comment]
I suggest you use the guidance [here](https://code.visualstudio.com/updates/v1_28#_record-and-search-keyboard-shortcuts) to check what VSCode sees when you press that combination, and what command it is bound to.

**Comment by fylzero** [comment]
@gjsjohnmurray Already tried this.  When I hit CMD, it comes up, Shift comes up, P does not show up.  The P key is working, CMD + P works.  Shift key is definitely working.  It's really weird.

I should also mention this is happening on two of my machines.  Both my personal laptop AND work computer are doing this, or should I say not doing this.  =T

**Comment by fylzero** [comment]
Figured out what it was.  I started using a to do list program called TickTick.  It was stealing the keybinding.  *facepalm*
