### ISSUE TITLE
Debug console replaces newlines with spaces

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#79321]
Issue Type: <b>Bug</b>

Message text sent to the debug console that includes newlines has them replaced with spaces.

For example, `console.log(JSON.stringify({a:1,b:2,c:3}, null, 2))` emits:
```
undefined
{ "a": 1, "b": 2, "c": 3 }
```
Instead of e.g.:
```
undefined
{
  "a": 1,
  "b": 2,
  "c": 3
}
```

Or even more trivially, `console.log("a\nb")` emits
```
undefined
a b
```

Unpleasant workaround: `bigStringWithNewLines.split('\n')` and then expand out the array object in the console.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.19.0-5-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2883)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|30.92GB (6.24GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.1
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
beautify|Hoo|1.5.0
bash-ide-vscode|mad|1.3.3
terraform|mau|1.3.12
openapi-lint|mer|1.0.3
vscode-docker|ms-|0.7.0
Go|ms-|0.11.4
debugger-for-chrome|msj|4.11.7
vscode-yaml|red|0.4.1
vscode-nginx|sha|0.6.0
html-preview-vscode|tht|0.2.5
reflow-paragraph|Tro|1.3.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
The log message is coming from the debug adapter, thus forwarding to @roblourens to first check if this is done on purpose

**Comment by roblourens** [comment]
Works for me? What version of node?

![image](https://user-images.githubusercontent.com/323878/63284449-7497bf00-c268-11e9-9804-74bb1e6cc310.png)

**Comment by mgabeler-lee-6rs** [comment]
node 10.15.3 here, via nodenv.

**Comment by roblourens** [comment]
I get the same with that version. Can you set `"trace": true` and try again, and upload the log from the path in the debug console?

**Comment by mgabeler-lee-6rs** [comment]
Stray observations that may be helpful for investigating:
1. This happens with `"outputCapture": "std"` in the launch file too, for plain text emitted from the app.  Not that it folds everything into a single newline, but things that came in a single `process.stdout.write` seem to be folded onto a single line.
2. If I copy the text to the clipboard and paste it in an editor window or some other app, the newlines are all there
3. This produces the expected two lines of output: `setTimeout(() => {process.stdout.write('a\n'); setTimeout(() => process.stdout.write('b\n'), 0);}, 0)` ... after hitting "Go" again in the debugger, anyways
4. The behavior continues for me with both options for `outputCapture`, including with all extensions disabled
5. Bisect of release versions:
    * Was working up to 1.35.1
    * Broke weirdly in 1.36.0 -- it prints just the first line, e.g. printing `'a\nb'` only reports `a` to the console
    * Current behavior began in 1.36.1

That last bit hopefully provides a tight window to figure out where this went wrong?

**Comment by mgabeler-lee-6rs** [comment]
Diffing 1.36.0 to 1.36.1 this line stands out:
https://github.com/microsoft/vscode/compare/1.36.0...1.36.1#diff-56bac19a33f70ab9e3dc7d2818b55405R380

Which was put in via #76690 to fix #76093

Looking at what that's about ... if I re-enable `debug.console.wordWrap` in my local settings, then I do get the newlines in the debug output ... but I also get long line wrapping which I don't want.

**Comment by mgabeler-lee-6rs** [comment]
> Can you set "trace": true and try again, and upload the log from the path in the debug console

Set that where?

**Comment by roblourens** [comment]
Good analysis, if I disable console wordwrap, I see the same.

**Comment by isidorn** [comment]
Yes, the issue here is that if the wordWrap is disabled, we do not break on word [here](https://github.com/Microsoft/vscode/blob/b05051e549f96298de33f6263003e77e5fd95a5a/src/vs/workbench/contrib/debug/browser/media/repl.css#L21)
If we were to change this we would also have to fine tune the height computation [here](https://github.com/Microsoft/vscode/blob/b05051e549f96298de33f6263003e77e5fd95a5a/src/vs/workbench/contrib/debug/browser/repl.ts#L750)

PR to tackle this is welcome.

**Comment by jameslh** [comment]
This seems like it might be a crucial issue, or possibly part of another issue with debug wordwrap. For example, running the following code without wordwrap: 
`for(let i = 0; i < 10; i++) console.log(i);`
Produces a different output each time it is run:
> 0
> 1
> 2 3
> 4 5 6
> 7 8 9

Or:
> 0
> 1
> 2 3 4 5 6 7
> 8 9

Or:
> 0
> 1
> 2 3 4 5
> 6 7 8 9

The debug output without wordwrap is not correct or consistent which makes the feature unusable.

**Comment by roblourens** [comment]
@isidorn it seems like a pretty bad bug, if you want people to use `"debug.console.wordWrap": false`

**Comment by isidorn** [comment]
Yeah, agree, let's reopen
