### ISSUE TITLE
Some icons appear as solid shapes

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#79326]
Version: 1.38.0-insider (user setup)
Commit: 1c6e25b87e05a8429c986c59431be77467af9449
Date: 2019-08-16T09:47:47.248Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.15063

![image](https://user-images.githubusercontent.com/2294248/63186247-f64dd980-c029-11e9-8cc1-668027c30450.png)
The errors icon in the status bar should be displaying as a circle outline with an 'x' in it. Instead it's a solid circle. The warnings icon looks fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Some others too, like `'$(search)'` or tweet+notification icons.

**Comment by iansan5653** [comment]
Confirmed - my tweet + notification icons:

![image](https://user-images.githubusercontent.com/2294248/63188579-b8ec4a80-c02f-11e9-8a52-c074f9a9ed74.png)

**Comment by misolori** [comment]
Yes, these are a rendering bug on Windows/Linux and will be fixed by tomorrow's insiders.

**Comment by RA1NN1AR** [comment]
+1

**Comment by iansan5653** [comment]
Verified, thanks.
