### ISSUE TITLE
Close panel 'x' button should be a minimize button '_'

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7932]
It's particularly confusing with the terminal panel, a `x` is ambiguous whether it will kill the terminal process when really this is purely a minimize button `_` for all panels.

**Comment by coreh** [comment]
Would be really nice if it was on the left side on OS X, as well.

**Comment by Tyriar** [comment]
@coreh I doubt that would happen as it would need to be applied globally or be inconsistent (working files, find, tabs, etc.). Lots of work in design/maintaining 2 behaviors for little payoff imo. In general we tend to go for consistency across platforms, adopting some platform-specific behaviors where it's easy and makes sense.

**Comment by coreh** [comment]
Makes sense. Y'all are moving so fast with the features and improvements that it's easy to forget the resources are actually finite.

Maybe someday 🙃

**Comment by bgashler1** [comment]
I would also add that we animate it closed into to the status bar.  This will serve two purposes:
1) Helps users understand that we are not terminating processes; we're just hiding the view
2) Helps users discover that they can drag this back out at any time from he status bar.

**Comment by bpasero** [comment]
There is a competing issue from our PM ;) https://github.com/Microsoft/vscode/issues/9638
