### ISSUE TITLE
'Add Selection To Next Find Match' ignores 'editor.wordSeparators' setting

### ISSUE THREAD

**Issue by pedzed** [microsoft/vscode#79323]
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-55-generic snap

**Steps to Reproduce:**
1. Double click a word preceded by a dollar (e.g. `$myVariable`).
2. **Expect:** `myVariable` to be selected with the default `editor.wordSeparators` setting.
3. Use the keyboard shortcut of 'Add Selection To Next Find Match' on the same word to do the same thing.
4. **Expect:** `myVariable` to be selected with the default `editor.wordSeparators` setting.

The first test passes. The second does not. `editor.wordSeparators` seems to be ignored for the 'Add Selection To Next Find Match' feature.

Default `editor.wordSeperators` for reference:
```json
"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
```

_Removing the dollar character results in having `$myVariable` selected rather than `myVariable` on a double click (which is as expected). The same should apply to 'Add Selection To Next Find Match'.._

Slightly related: https://github.com/Microsoft/vscode/issues/19483

**Comment by alexandrudima** [comment]
Let's track in #15774
