### ISSUE TITLE
Slow intellisense 1.37.1 and unstable UI

### ISSUE THREAD

**Issue by oswee** [microsoft/vscode#79328]
Recently noticed that VS Code becomes more and more unstable.
It appears to crash and exit on, terminals loose font color (output and selection are in the same color as background - so invisible), few times noticed it freezing completely.. but all those are not so critical.
Most critical issue is intellisense which takes like at least 2 seconds to show up.
Reload, Reboot, Update or plugin disable does not help.
So i fired up Vim setup and was amazed about near to the speed of light autocomplete.

Is there known issues in this context and it is worth to wait for next update or this is expected behavior due to massive amount of features implemented in electron? Like natural product degradation?

I am not an Vim expert jet, so... would like to know, should invest to learn it completely, or i just need to wait for some VS Code update?

- VSCode Version: 1.37.1
- OS Version: Fedora 30 (Workstation Edition)

Steps to Reproduce:

1.Disable all plugins `code --disable-extensions`
2.Enable only single `ms-vscode.go` extension.

Does this issue occur when all extensions are disabled?: Yes

**Comment by David-Else** [comment]
You would probably love this: https://github.com/neoclide/coc.nvim

**Comment by deepak1556** [comment]
@oswee can you try our exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 and check if the intellisense issue still persists. Thanks!
