### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by fatemi** [microsoft/vscode#79332]
Issue Type: <b>Bug</b>

I have personalized color settings. After each update the folder is removed from "resources/app/extensions"  and I have to copy it back. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edit-csv|jan|0.1.2
python|ms-|2019.8.30787

</details>

**Comment by usernamehw** [comment]
You should try not to modify vscode source.

Color customizations can be changed from `settings.json`
```js
"workbench.colorCustomizations": {
    // ...
},
"editor.tokenColorCustomizations": {
    // ...
},
```
