### ISSUE TITLE
Running VSCode through a VPN

### ISSUE THREAD

**Issue by YashasviMantha** [microsoft/vscode#79333]
I really like to run VSCode on a remote server which cannot be accessed through the regular internet. I have to stay connected to the intra-network to access the same. But this was fixed through a VPN that I run on OpenVPN. But this tunnels my whole network flow through the VPN when I want just the VSCode traffic to get tunneled. It would really be great if VSCode could tunnel its traffic through a OpenVPN configuration file hence not disturbing other traffic(like web browsers).

Thanks

**Comment by BlenderDude** [comment]
This seems like something you should configure in OpenVPN and would be a huge undertaking to integrate into VSCode. If you add these lines to your OpenVPN config, you should be able to route only the specific subnet you want through your VPN, and everything else is left untouched.

```
route-nopull 
route 10.0.0.0 255.255.255.0
```

First IP is the subnet you want to have pushed through the VPN and the second is subnet mask which controls how much of the subnet you want to use. `255.255.255.255` is a single IP, while `255.255.0.0` is `10.0.0.0` to `10.0.255.254`

**Comment by YashasviMantha** [comment]
Nicee!! I did poke around some third party softwares but never found this way. I don't seem to understand what I should be doing, bit I can figure this out since you have me a direction. Really appreciate it.

**Comment by BlenderDude** [comment]
No problem, simply put, find out the IP address of the server and then add this to your config.
```
route-nopull 
route [The server ip address goes here] 255.255.255.255
```

Then only your server's IP address will be using the VPN, everything goes through the internet as normal. If you think this solves the issues, don't forget to go ahead and close it!

**Comment by YashasviMantha** [comment]
Damn!! I can't believe the solution was this simple!! It totally worked!! Thank You so much!! But would you mind telling me about 255.255.255.255 IP? What is it? Is it something only VSCode uses?

**Comment by BlenderDude** [comment]
Sure! It actually has nothing to do with VSCode, or even OpenVPN for that matter. It's called the Subnet Mask. Without dropping a full blown explanation of networking, its basically describing how many IP addresses should be directed toward the VPN. For example, the subnet mask I gave you `255.255.255.255` makes it such that there is only 1 IP address is routed through the VPN. If you were to change the numbers of that subnet mask to something else, say `255.255.255.0`, it would then route not only your servers IP address, but other IP addresses around it. If your server's IP address was `10.0.0.54` and you wanted to apply the range with the mask `255.255.255.0` you would actually pick up everything from `10.0.0.1` to `10.0.0.254`.  You can actually see the subnet mask delivered in a different way. If I were to say `10.0.0.0/24` (CIDR notation), it would represent the same subnet as the mask `255.255.255.0`.

**Comment by YashasviMantha** [comment]
So we are basically restricting the IP address routing the VPN to just one? In that case, how can we assure that that "one" IP will only belong to VSCode. After some poking, I also noticed that I am able to access the remote server through CMD too. How does OpenVPN know that "one" IP to allow. How do I know if traffic from my chrome browser is not getting routed through the VPN?

**Comment by BlenderDude** [comment]
I think you might be using the wrong wording here. Do you have a remote server that requires the VPN to be accessed, or do you want all of VSCodes traffic to use the VPN and no other application? If its the latter, I can direct you [here](https://qasimk.io/2018/single-application-vpn/) but get ready cause it's not simple. If your server is running on a specific public IP, no other traffic is going to use that IP because its unique to your server.

**Comment by YashasviMantha** [comment]
Okay, So the lab I work at offers a high computation server. But to access that server we need to stay connected to the labs' network or at least the campus's network. So to access the server from outside(for example my home network), the college has a OpenVPN setup which can be used to access the network from outside. But when I use the college's network many of the sites are restricted(For ovbious reasons). So when I am at home I want to access the server hence connecting to the VPN setup when then restricts me to many sites.

But mainly I access the remote server through VSCode itself. If I could just run VSCode(and CMD if possible) through a VPN and all other traffic(Like Chrome) through my home wifi I could be accessing  the remote server and the sites I need at the same time.

**Comment by BlenderDude** [comment]
The first comment I left, if supplied with the up address of the server and added to the openvpn config file, will do just as you say. All traffic directed toward the lab computer will be on the VPN and all other traffic will not.
