### ISSUE TITLE
Highlighting for string type in generic

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#7933]
![image](https://cloud.githubusercontent.com/assets/3254987/16241929/e1d73e26-37a4-11e6-8410-035636c629c3.png)

Likely a TypeScript issue, but filed here as a start.
Using `typescript@1.9.0-dev20160614-1.0`

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#192
