### ISSUE TITLE
[html] Add support for `html.format.wrap_attributes_indent_size`

### ISSUE THREAD

**Issue by drstonebraker** [microsoft/vscode#79334]
js-beautify has a config field for wrap_attributes_indent_size that doesn't appear to be supported in vscode.

it seems it was added at one point and then removed?:
https://github.com/microsoft/vscode/commit/9d3307317ef1541aec4ae00ecc3604c7d1173000

**Comment by aeschli** [comment]
I had it in once, but when I tested it, it didn't seem to have any effect.
Maybe that has changed in the meantime.
