### ISSUE TITLE
cannot scope colorDecorators setting to PostCSS (at least)

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#79338]
Install an extension that provides support for PostCSS, I tried the following:

https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss
https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS

Turn off or on colorDecorators for just `PostCSS` in `settings.json` and turn off minimap:

``` json
    "[PostCSS]": {
        "editor.colorDecorators": true,
        "editor.minimap.enabled": false,

    },
```

Result: Settings are not applied to `PostCSS` file type:

![image](https://user-images.githubusercontent.com/1487073/63197845-c30d4980-c02d-11e9-982a-053a844cc2fe.png)

**Comment by usernamehw** [comment]
`languageId` is lowercase:

```json
"[postcss]": {
	"editor.minimap.enabled": false
}
```

![Screenshot (49)](https://user-images.githubusercontent.com/9638156/63198130-6daf5780-c082-11e9-976f-eb2857ce6a88.png)

**Comment by chrisdias** [comment]
ha! you would think i would know :)

`colorDecorators` doesn't work though, will change title.

**Comment by chrisdias** [comment]
Scoping this down to `colorDecorators`:

![image](https://user-images.githubusercontent.com/1487073/63199451-be975f80-c032-11e9-9e6f-c6b378e371e1.png)

**Comment by usernamehw** [comment]
Do they work without language-scope? I think the extension must provide something to get them working, so this is not a settings problem.

**Comment by alexandrudima** [comment]
@chrisdias I cannot reproduce, I've tried with `css`, but the logic is the same regardless of actual language... I can try with postcss if you really want me to, but please try again, maybe something got fixed in the meantime...:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66076179-86ee6380-e55d-11e9-97fb-ab9341cb6135.gif)

**Comment by chrisdias** [comment]
it looks to me like the extension needs to do something, per @usernamehw's comment above. When I associate `.css` files to `postcss` the color decorators go away there too.
