### ISSUE TITLE
In local / global search, 'Match Case/Word/Regex' toggles no longer distinguishable

### ISSUE THREAD

**Issue by pgobin** [microsoft/vscode#79342]
Issue Type: <b>Bug</b>

Theme: Kay Dark
Window Zoom Level: -2
Other: Full Brightness / Night Shift (Mac)

Before the recent icon update, the toggles were bright outlines. Now they're solid. I had 'Match Case' on while searching and was blocked for a few minutes before I realized the issue. Now I have to strain and get really close to the screen to see what is currently selected.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|-psn_0_2474588|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.5.0
vsc-material-theme|Equ|30.0.0
vscode-statusbar-debugger|fab|2.0.6
rainbow-csv|mec|1.2.0
dotenv|mik|1.0.1
python|ms-|2019.8.30787
indent-rainbow|ode|7.4.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.4.3

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See #8017 and particularly https://github.com/microsoft/vscode/issues/8017#issuecomment-521653495 for links to related issues.

**Comment by pgobin** [comment]
**Note:** This is a non-issue as `inputOption.activeBorder` corrects for that described above.
