### ISSUE TITLE
Linux  freezes when using the VSCode

### ISSUE THREAD

**Issue by rodrigoestevao** [microsoft/vscode#79343]
Guys, I notice that, every single time that I'm using the Visual Studio code on my Linux machine, it just freezes the whole system, not even the mouse I was able to access. This problem have been happening frequently and I took a time to figure it out that was happening just when I was using the VS code or when I left the VS Code opened.  I went into internet and I found lot of people complaining about the same problem

**Comment by WellspringCS** [comment]
I've noticed that happens when I run out of memory, so keep an eye on your resources would be my suggestion. Did I mention I'm ordering a laptop with more memory? :)

**Comment by rodrigoestevao** [comment]
I have 16GB  of memory and I was not running anything together, just the chrome and a jupyter with just one notebook opened :-(
    On Saturday, August 17, 2019, 12:10:23 AM GMT-3, Brian Wells <notifications@github.com> wrote:  
 
 
I've noticed that happens when I run out of memory, so keep an eye on your resources would be my suggestion. Did I mention I'm ordering a laptop with more memory? :)

**Comment by WellspringCS** [comment]
I have 16 gig too, and Chrome/Docker/VSCode eat away at it, especially over a period of days if I don't reboot. Not saying this has to be your problem, but that's been my experience, and when it runs out of swap drive and ram... you can't even move your mouse hardly.

**Comment by rodrigoestevao** [comment]
I kept the htop running and the average memory consume was 5 GB. I will keep a track on it

Thank you Brian
    On Saturday, August 17, 2019, 12:19:50 AM GMT-3, Brian Wells <notifications@github.com> wrote:  
 
 
I have 16 gig too, and Chrome/Docker/VSCode eat away at it, especially over a period of days if I don't reboot. Not saying this has to be your problem, but that's been my experience, and when it runs out of swap drive and ram... you can't even move your mouse hardly.

**Comment by isidorn** [comment]
Please follow this guide to report more details
https://github.com/microsoft/vscode/wiki/Performance-Issues

Thanks

**Comment by rodrigoestevao** [comment]
Thank you,
I will do that
Cheers
    On Monday, August 19, 2019, 05:23:12 AM GMT-3, Isidor Nikolic <notifications@github.com> wrote:  
 
 
Please follow this guide to report more details
https://github.com/microsoft/vscode/wiki/Performance-Issues

Thanks

**Comment by isidorn** [comment]
Thanks!
