### ISSUE TITLE
outline not in a tree view

### ISSUE THREAD

**Issue by cnjsdfcy** [microsoft/vscode#79344]
In a windows-to-linux remote development scenario, the outline are not showing a tree-like view both when opening python and C++ codes. For example:
![image](https://user-images.githubusercontent.com/5670527/63205835-f1962d80-c0dc-11e9-9450-1b6df0e01f34.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please post info about your VSCode version and the extensions you are using. The Issue Reporter dialog is one way of gathering this in a format ready to post here.

Does the issue only occur on remote development?

**Comment by cnjsdfcy** [comment]
It turns out to be an unimplemented [cpptools‘ feature](https://github.com/microsoft/vscode-cpptools/issues/4124). Closing this issue.
