### ISSUE TITLE
Some files are missing in the File Explorer

### ISSUE THREAD

**Issue by karevn** [microsoft/vscode#79349]
- VSCode Version: 1.37.1
- OS Version: MacOS 10.15.6

Steps to Reproduce:
I can't tell the specific steps for now, but I see it after a sequence similar to this one:
1. Open some project with Git repository.
2. Move, add, or rename some file (may be, move it into an another project subdir).
3. Switch to an another branch
4. See one of the files moved missing in that branch (even though does exist there).

I'll try to put together a more definite set of steps to reproduce in the meantime.

**Comment by isidorn** [comment]
I can not reproduce. Can you reproduce with vscode insiders?
https://code.visualstudio.com/insiders/
Also nice steps would be great. Thanks
