### ISSUE TITLE
Help webview extensions add a Content Security Policy

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#79340]
Many webview extensions do not currently set a [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). All webviews (even very simple ones) should set a content security policy. This is not a immediate security problem but a content security policy helps to limit the potential impact of content injections and is generally a good measure for defense in depth. 

I've put together this initial list of extensions that create webviews that seem not to have a content security policy (there may be false positives). If you are feeling like a security hero, **consider helping these extensions out by submitting a PR that adds a restrictive content security policy to their webviews**. [Here's our documentation to help you get started](https://code.visualstudio.com/api/extension-guides/webview#content-security-policy).

Let me know if an extension has been fixed or was incorrectly flagged

---

**Key**

- ❗️- Confirmed and issue opened
- ✔️ - Fixed
- ❓ - Can't confirm in current code in github master? 
- Blank - Unconfirmed

**Extensions**

- ❗️ vscjava.vscode-java-pack - https://github.com/microsoft/vscode-java-pack/issues/171
- ✔️ Shan.code-settings-sync - https://github.com/shanalikhan/code-settings-sync/issues/1010
- ❗️ shengchen.vscode-leetcode - https://github.com/jdneo/vscode-leetcode/issues/393
- ✔️ tomoki1207.pdf - https://github.com/tomoki1207/vscode-pdfviewer/issues/45
- humao.rest-client
- eamodio.gitlens
- platformio.platformio-ide
- ✔️ ms-python.python - https://github.com/microsoft/vscode-python/issues/7007
- ✔️James-Yu.latex-workshop
- shd101wyy.markdown-preview-enhanced
- ✔️ ms-mssql.mssql - https://github.com/microsoft/vscode-mssql/pull/1282/files#diff-8306d266d9ca46a40054bd378cc68948R5
- alefragnani.Bookmarks
- auchenberg.vscode-browser-preview
- streetsidesoftware.code-spell-checker
- donjayamanne.githistory
- anonimitoraf.handlebars-preview-with-function-support
- ❗️ ms-kubernetes-tools.vscode-kubernetes-tools - https://github.com/Azure/vscode-kubernetes-tools/issues/600
- alefragnani.project-manager
- almenon.arepl
- johnstoncode.svn-scm
- nkokhelox.svg-font-previewer
- mtxr.sqltools
- TOTVS.tds-vscode
- nrwl.angular-console
- jebbs.plantuml
- ❓ Microsoft.vscode-nmake-tools
- karigari.chat
- GrapeCity.gc-excelviewer
- nondanee.vsc-netease-music
- tht13.html-preview-vscode
- particle.particle-vscode-core
- scalameta.metals
- kdcro101.vscode-redis
- jock.svg
- formulahendry.ycy
- ❓ms-vscode.cpptools
- attilabuti.vscode-mjml
- AzBlockchain.azure-blockchain
- ✔️ ms-edgedevtools.vscode-edge-devtools - https://github.com/microsoft/vscode-edge-devtools/issues/91
- ms-vsliveshare.vsliveshare
- kruemelkatze.vscode-dashboard
- vsciot-vscode.azure-iot-tools
- JaimeOlivares.yuml
- vsciot-vscode.vscode-arduino
- alexcvzz.vscode-sqlite
- Equinusocio.vsc-material-theme
- bajdzis.vscode-database
- pomber.git-file-history
- alios.alios-studio
- Arjun.swagger-viewer
- Ionide.experimental-fsharp
- EFanZh.graphviz-preview
- ❗️ ms-ossdata.vscode-postgresql - https://github.com/microsoft/vscode-postgresql/issues/56
- dongli.python-preview
- Acrolinx.vscode-sidebar
- alefragnani.jenkins-status
- axosoft.gitkraken-glo
- jithurjacob.nbpreviewer
- vsciot-vscode.azure-iot-toolkit
- vsciot-vscode.vscode-iot-workbench
- WASTeamAccount.WebTemplateStudio-dev-nightly
- joaompinto.asciidoctor-vscode
- ego-digital.vscode-powertools
- Orta.vscode-jest
- ✔️ tht13.rst-vscode
- amazonwebservices.aws-toolkit-vscode
- ✔️ Ionide.Ionide-fsharp - https://github.com/ionide/ionide-vscode-fsharp/issues/1199
- yokawasa.jwt-debugger
- janisdd.vscode-edit-csv
- vitaliymaz.vscode-svg-previewer
- mrkanister.idef1xer
- Kelvin.vscode-sshfs

**Comment by ParkourKarthik** [comment]
I'll pick this up. Will start with sync settings extension.

**Comment by utsavm9** [comment]
Sorry I realized late that I cannot edit the list until I am assigned. I worked on vitaliymaz.vscode-svg-previewer. It did have a CSP, which was not the minimum so maybe it was a false positive or maybe not.

**Comment by utsavm9** [comment]
I believe `janisdd.vscode-edit-csv` is a false positive as [CSP exists in the extension](https://github.com/utsavm9/vscode-edit-csv/blob/6aef7007a1073f2f7b2a98cf91be83b010f949a1/src/getHtml.ts#L477). Is it here because it has `unsafe-inline` for its scripts and style?

**Comment by rchiodo** [comment]
We've just added a csp to the python extension, but we're still getting the warning? Does it have to be strict in order to not get the warning?

Here's our current CSP:

```<meta http-equiv="Content-Security-Policy" content="default-src 'unsafe-inline' 'unsafe-eval' vscode-resource: data: https: http:;">```

**Comment by TantumErgo** [comment]
What file or files is the CSP usually included in?

So if you click on any of the repos with confirmed and open issues and take a look at the project files, what files should usually contain a CSP? All HTML files?

**Comment by mjbvz** [comment]
@jblievremont Can you share a link to an example extension

**Comment by jblievremont** [comment]
@mjbvz see SonarSource/sonarlint-vscode#53

**Comment by abist** [comment]
Hi, I'm from the `ms-mssql.mssql` team. We added a CSP to our webview [here](https://github.com/microsoft/vscode-mssql/pull/1282/files#diff-8306d266d9ca46a40054bd378cc68948R5). Is there anything more we need to do?

**Comment by mjbvz** [comment]
@abist Looks good. Thanks

**Comment by tamuratak** [comment]
✔️James-Yu.latex-workshop James-Yu/LaTeX-Workshop/pull/1676

**Comment by mike-lischke** [comment]
mike-lischke.vscode-antlr4 uses webviews too and while working on adding CSPs to them I stumbled across a problem: I get the missing CSP warning even though I have added a CSP. The generated code is:

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8"/>
    
            <meta http-equiv="Content-Security-Policy" content="default-src 'self';
            script-src vscode-resource: 'self' 'unsafe-inline' 'unsafe-eval' https:;
            style-src vscode-resource: 'self' 'unsafe-inline';
            img-src vscode-resource: 'self' "/>
        
            <link rel="stylesheet" type="text/css" href="vscode-resource://file///Volumes/Extern/Work/projects/vscode-antlr4/misc/light.css">
<link rel="stylesheet" type="text/css" href="vscode-resource://file///Volumes/Extern/Work/projects/vscode-antlr4/misc/dark.css">
            <base target="_blank" />
        
</head>
```

Why's that not accepted?

**Comment by mjbvz** [comment]
@mike-lischke I just tried that html in a webview with VSCode 1.41.0-insider (Commit: 0d728c31ebdf03869d2687d9be0b017667c9ff37) but could not reproduce the issue. Can you please share an example extension?

**Comment by mike-lischke** [comment]
@mjbvz I assumed that `mike-lischke.vscode-antlr4` would give you a hint, but the current release has no CSP at all. The original [code is at Github](https://github.com/mike-lischke/vscode-antlr4). It should run out of the box. For the effect to see you have to open an ANTLR4 grammar file. There are a few in the `tests/background` folder (.g4). Once you opened it right click on a rule to show the context menu in the editor pane. 

<img width="450" alt="Bildschirmfoto 2019-11-13 um 09 14 08" src="https://user-images.githubusercontent.com/2398704/68744934-f4c68a00-05f5-11ea-95e5-aeb239164b51.png">

Select the Railroad diagram, which will show a webview. This one does *not* bring up the warning. Then try `Show ATN Graph for Rule`. That also opens a webview, but this time the warning `mike-lischke.vscode-antlr4 created a webview without a content security policy: https://aka.ms/vscode-webview-missing-csp` comes up in the debug console. This is particularly odd because both views share the same backend, with the same CSP code. Note also that the CSP code seems to be ok, since all graphics and CSS is used as expected.

**Comment by mjbvz** [comment]
@mike-lischke I can't repo this in VS Code insiders. 

Are you 100% sure your webview html always has a content security policy. For example, this line looks suspicious: https://github.com/mike-lischke/vscode-antlr4/blob/b6b065c09494e947259617661ab9f1bcb6c2a148/src/frontend/ATNGraphProvider.ts#L41

**Comment by mike-lischke** [comment]
Many thanks for looking into that @mjbvz.  Unfortunately this function is not the culprit here. It definitely needs a change to include a CSP, but it is not called when you have a grammar rule selected (which is the case in this example).

I tried to debug further to see where the missing csp message is generated, but that went to nowhere (I found the place where it is printed, but not the location where vscode determines if this message is needed). My (vague) assumption is that something in the generated HTML code is keeping vscode to think the csp is still missing (even though it is there).

**Comment by seongwon-kang** [comment]
`Orta.vscode-jest` is a test tool. and they uses webview to see html snapshot.
they escapes all html tag, and encloses with `<pre>` tag. it seems false positive.

**Comment by mjbvz** [comment]
@seongwon-kang Can you link the the code that does this? All html used in webviews (even html that properly escapes its content) should have a content security policy

**Comment by seongwon-kang** [comment]
@mjbvz [](https://gist.github.com/seongwon-kang/28e910d3e6a68d28f6ced0a21c17c56b) will add csp tag dynamically, but I doubt this csp is correctly configured.

**Comment by seongwon-kang** [comment]
![image](https://user-images.githubusercontent.com/56567660/75326668-61704680-58be-11ea-8faf-18c18542deab.png)

@mjbvz it seems vscode already attach CSP metatag when webview renders to workbench. is any other path to see webview?

**Comment by mjbvz** [comment]
Closing this since we've done work on the VS Code side to make these errors more obvious to extension authors.
