### ISSUE TITLE
search multi

### ISSUE THREAD

**Issue by deskenazi** [microsoft/vscode#79354]

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo - please review https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests and post more details here.

**Comment by deskenazi** [comment]
This was created by mistake when I typed in the issue creation box, saw a good suggestion, and pressed enter. Closing.
