### ISSUE TITLE
Collapse comment code

### ISSUE THREAD

**Issue by fqdawang** [microsoft/vscode#79355]
A long line of comment code does not fold.  
It takes up a lot of space. 
It affects the efficiency of writing code

**Comment by fqdawang** [comment]
I can't.  I can't fold up the code, either single-line comments or multi-line comments

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

- What language are you coding in?
- How long does the line have to be to cause the problem?
- Can you post screenshots?
- What version of VSCode?
- Does the problem reproduce when you run with all extensions disabled?

**Comment by fqdawang** [comment]
I have been using vs code for nearly half a year.

The version I'm using now is 1.37.1.

The language is js.

I don't think it's an extension problem.

I made a paragraph of video, hoping to make my question clear



------------------ 原始邮件 ------------------
发件人: "John Murray"<notifications@github.com>;
发送时间: 2019年8月17日(星期六) 晚上9:34
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "福球大王"<1311470667@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Collapse comment code (#79355)




/needsMoreInfo
  
What language are you coding in?
 
How long does the line have to be to cause the problem?
 
Can you post screenshots?
 
What version of VSCode?
 
Does the problem reproduce when you run with all extensions disabled?

**Comment by gjsjohnmurray** [comment]
@fqdawang I don't see any link to a video.

**Comment by fqdawang** [comment]
I am sorry that I sent video via email. I sent video to noti***** ions@github.com. I hope you can receive it




------------------ 原始邮件 ------------------
发件人: "John Murray"<notifications@github.com>;
发送时间: 2019年8月17日(星期六) 晚上10:02
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "福球大王"<1311470667@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/vscode] Collapse comment code (#79355)




@fqdawang I don't see any link to a video.
