### ISSUE TITLE
some korean translation is missing

### ISSUE THREAD

**Issue by funnycom** [microsoft/vscode#79351]
After installed Korean Language Pack extension, 
some strings in Source Control that translated to Korean in previous version  are not translated in this version. 
![InkedInkedvs-4_LI](https://user-images.githubusercontent.com/5915404/63208292-3fc32500-c10d-11e9-9be4-47c72c2c2979.jpg)
![InkedInkedvs-1_LI](https://user-images.githubusercontent.com/5915404/63208293-43ef4280-c10d-11e9-8c47-607ba0843cba.jpg)

- VSCode Version: 
- OS Version:
버전: 1.37.1 (user setup)
커밋: f06011ac164ae4dc8e753a3fe7f9549844d15e35
날짜: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by johnliu2016** [comment]
Hello @dbaeumer, we cannot locate this exact 'Modified' string that is not in translated form in vscode resources, could it be from Git resources instead?

**Comment by dbaeumer** [comment]
@joaomoreno can you comment on whether this is externalized.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/blob/de320052255d136673fc5eee358f6e2551d6573e/extensions/git/src/repository.ts#L113

**Comment by dbaeumer** [comment]
Could have been moved and therefore needs to be updated. @weeteckt can you ckeck if the strings shows up in a latest export from master.

**Comment by weeteckt** [comment]
@dbaeumer

Looks like I was not able to find "CHANGES" and "Message (press Ctrl..." from the latest export.
I can find "Modified" in the latest master but we need to know this is the exact string used in that specific UI area.

**Comment by janbaltus** [comment]
We can locate this string in August 1 for example vscode\extensions\git\src\repository.ts 

		this._sourceControl.inputBox.placeholder = localize('commitMessage', "Message (press {0} to commit)");

but not anymore in latest master branch

**Comment by dbaeumer** [comment]
@weeteckt @joaomoreno can comment on whether this is the right string. There is also the possibility to add a comment to a `nls.localize` call to annotate strings to make it more clear were it is used.

**Comment by danyeh** [comment]
Thank you for your feedback!
Checked on 1.51. All fixed.
