### ISSUE TITLE
VsCode Internal Terminal Does Not Line-Break When The Text is Long

### ISSUE THREAD

**Issue by gokayokutucu** [microsoft/vscode#79358]
- VSCode Version: 1.37.0
- OS Version: MacOS Mojave 10.14.6

Root username floats to left when a long row is printed. It may remove new line(/n/r) and push the line up.

![NewLine](https://user-images.githubusercontent.com/10991334/63212750-c4b03d80-c111-11e9-9eb2-5398906123b5.png)

**Comment by Tyriar** [comment]
Can you give repro steps?

**Comment by gokayokutucu** [comment]
When printing long texts in the terminal, the text begins directly next to the new row (e.g. root name). However, if the window is resized while such text is shown, the text detaches from the root name, and drops down to the line below.

You can see the screenshot of the related issue on above. In this sample; I have a console app and it just prints out a long texts.

**Comment by Tyriar** [comment]
Please provide the text you're pasting and also what your $PS1 variable is set to.

**Comment by Tyriar** [comment]
Can you try repro in [xterm.js](https://github.com/xtermjs/xterm.js)' demo and report there if you see it? Also make sure you try in different terminals as that might be the expected behavior?
