### ISSUE TITLE
Git autorefresh lose efficacy on remote-ssh mode.

### ISSUE THREAD

**Issue by tobefuturer** [microsoft/vscode#79356]
After saving file, the SCM view show nothing until click the refresh button manually. Only has problem on remote-ssh mode, git auto refresh is normal when opening local project.

I have set "git.autorefresh : true " in my settings.json.  

Do I need to modify any other settings or install any Extension?

Installed Extension : Remote Development

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by gjsjohnmurray** [comment]
/duplicate

- https://github.com/microsoft/vscode-remote-release/issues/570
- https://github.com/microsoft/vscode-remote-release/issues/700
- https://github.com/microsoft/vscode-remote-release/issues/1094
- #76423
