### ISSUE TITLE
warning on lack of calling super()

### ISSUE THREAD

**Issue by zzzgit** [microsoft/vscode#79350]
In a child class, maybe I will forget to call `super()` in its constructor.
Can you add a code lint warn for it?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo - Which linter extension are you using?

**Comment by zzzgit** [comment]
> Which linter extension a

None. I am just using the built-in functionalies.

**Comment by mjbvz** [comment]
What language is this for?

**Comment by zzzgit** [comment]
> What language is this for?
.js

**Comment by IllusionMH** [comment]
VS Code (and TypeScript) will report errors
`error TS2377: Constructors for derived classes must contain a 'super' call.`
and
`error TS17009: 'super' must be called before accessing 'this' in the constructor of a derived class.`

If you enable checks for JS files:
1) With `//@ts-check` comment at the start of the file
2) With `"checkJS": true` in [`jsconfig.json`](https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options)

![image](https://user-images.githubusercontent.com/1312662/63256767-f4ca1e80-c280-11e9-9486-655cf1730084.png)

**Comment by mjbvz** [comment]
@IllusionMH's answer is correct. To get this error in js files, you must enable type checking
