### ISSUE TITLE
VS Code slowed down and uninstalled itself.

### ISSUE THREAD

**Issue by JonasDev99** [microsoft/vscode#79364]
I was working on a project when suddenly, VS Code got so slow, I couldn't do anything anymore. I closed the program and wanted to restart it but it had uninstalled itself and Windows asked me whether I want to remove the shortcut or not.
At first, I thought it was my antivirus (I use Windows Defender) but then I checked the threat history and I never had any threats. 

OS: Windows 10
I think It was the latest VS Code version but not sure about that.

I have no Idea how to reproduce this issue yet as it occurred only once so far.

This bug is not so bad as I reinstalled VS Code and it opened the project where I left off.

**Comment by gjsjohnmurray** [comment]
Maybe similar to https://github.com/microsoft/vscode/issues/77156#issuecomment-510321678

**Comment by angelhdz** [comment]
This is a Windows 10 issue. Happened to me with Atom, so I switched from Atom to VSCode. And then VSCode uninstalled itself. Then, VLC Media Player uninstalled itself. And other programs.

It's Windows 10 Forced Updates that messes everything up.

**Comment by SneakyFish5** [comment]
This happened to me as well although I left my computer on with vscode open for a few hours and when it came back if said the exact same thing about shortcuts and stuff. I reinstalled and everything was alright including my settings which is good but I'm not sure what caused it to happen.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
