### ISSUE TITLE
VS Code transparent folder icon

### ISSUE THREAD

**Issue by Hulkstance** [microsoft/vscode#79365]
I just updated VS Code to its latest version and I'm disappointed to see that you made the folder icons transparent (using _Minimal_ style). I can barely distinguish files from folders. Bring it back or at least create a new extension for the old style icons. Right now I can't use it because it's messy when I have multiple angular modules and components inside it. I just want white filled folder icons. I checked many of the icon style extensions but none of them had same style for all files and solid folder icon.

https://i.imgur.com/SWKR5nN.png

```
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by gjsjohnmurray** [comment]
/duplicate

See #8017 and particularly #8017 (comment) for links to related issues.
