### ISSUE TITLE
sidebar explorer view to be compact

### ISSUE THREAD

**Issue by srijib** [microsoft/vscode#79360]
I am a diehard fan or notepad++ so may be i am biased, but I would like the file explorer view to se something like notepad++ check the images

want comments from other users about the aesthetic of notedpad++ file explorer, it looks clean, while v code looks clumsy

![vcc](https://user-images.githubusercontent.com/7030187/63214066-4e233800-c131-11e9-80d2-220e6df8afc1.PNG)
![notepad](https://user-images.githubusercontent.com/7030187/63214067-54191900-c131-11e9-8e5f-859417a91d80.PNG)

**Comment by ArturoDent** [comment]
See https://stackoverflow.com/questions/55310734/how-to-add-more-indentation-in-a-file-tree-structure-it-has-a-little-bit-inden/55315106#55315106 for some help in this area.
