### ISSUE TITLE
调试功能不支持中文路径

### ISSUE THREAD

**Issue by yunxu1019** [microsoft/vscode#79367]
- VSCode Version: 1.37.1(system setup)
- OS Version:Windows_NT x64 10.0.18362

Steps to Reproduce:

1. 在launch.json中添加调试脚本，runtimeExecutable指定一个npm全局安装的应用，此安装路径包含中文
2.运行此脚本，出现中文乱码，无法找到文件的错误
![image](https://user-images.githubusercontent.com/15274374/63216662-349ee200-c16b-11e9-8f72-113f36e06504.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please file in english, we do not speak chinese
