### ISSUE TITLE
VSCode doesn't run the Node.js program

### ISSUE THREAD

**Issue by szokekaroly** [Microsoft/vscode#7936]
- VSCode Version:1.2.1
- OS Version:Fedora 24 Linux, x86_64, kernel 4.5.7

Steps to Reproduce:

1. Open Node.js project
2. Press F5, run the program
3. Appear the info message: Please set up the launch configuration file for your application.
4. I have got a correct launch.json file, but the info message appear again, and the JavaScript program doesn't run
5. Workround: go to the debug mode, then click the green start debugging button or press F5 button, the program is begin to run

**Comment by isidorn** [comment]
This should be fixed in the latest insiders and will the fix will be available in the june release of vscode

**Comment by szokekaroly** [comment]
Thank you very much! I love it to develope javascript applications.
