### ISSUE TITLE
[Feature request] Add the possibility to define variables in launch.json

### ISSUE THREAD

**Issue by MaliusArth** [microsoft/vscode#79369]
In the C++ plugin, you can define environment variables in the c_cpp_properties.json like so:

```
{
"env" : {
        "systemIncludePaths": [
            "/usr/include",
            "/usr/include/c++/5.4.0",
            "/usr/include/c++/5.4.0/backward",
            "/usr/include/x86_64-linux-gnu",
            "/usr/include/x86_64-linux-gnu/c++/5.4.0",
            "/usr/lib/gcc/x86_64-linux-gnu/5/include",
            "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
            "/usr/local/include",
            "/usr/local/lib/clang/6.0.1/include"
        ]
}
// ...
}
```

They can then be used in the settings like this: `${env:systemIncludePaths}` or `${systemIncludePaths}`
I would like to be able to do this in launch.json as well to define program paths.
It would be great if this was possible in all .json settings files, actually, and to top it off, if env vars would work across settings files.

**Comment by angelhdz** [comment]
I requested this before, don't remember when exactly.

We need to be able to store colors in variables when creating themes and in every configuration file.

**Comment by isidorn** [comment]
fyi @weinand @alexr00

**Comment by weinand** [comment]
@MaliusArth I do not really understand what you are asking for.

Currently VS Code supports the following:
- in "launch.json" and "task.json" you can refer to environment variables in strings via the `${env:ENV-VARIABLE}` syntax.
- some debug extensions support to set environment variables, e.g. node-debug supports this syntax:
   ```
   "env": {
       "FOO": "xyz",
       "BAR: "123"
   }
   ```

Please clarify.

**Comment by MaliusArth** [comment]
I don't want to have to define "env" again and again in every launch task configuration.
I want an "env" to be on the same level as "version" and "configurations", just like "inputs" are as well in launch.json.
You could name it "vars" to disambiguate it from the env vars passed to debuggers if that poses a problem. Alternatively, you could extend the "inputs" by suppressing the user input popup when there is only one single option for a given input var anyway,
At the end of the day, all I want, is to be able to define variables inside a settings json file and use those vars across the entire file.
e.g:

```
{
  "version": "X.X.X",
  "env": {
    "someProgramsPath": "path/to/some/programs"
  },
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug (node)",
      "program": "${someProgramsPath}/program_A_.exe",
      "cwd": "${workspaceFolder}",
      //...
    },
    {
      "type": "pdb",
      "request": "launch",
      "name": "Debug (pdb)",
      "program": "${someProgramsPath}/program_B_.exe",
      "cwd": "${workspaceFolder}",
      //...
    },
  ]
}
```

**Comment by MaliusArth** [comment]
using `${someProgramsPath}` I get the following error in the debug console:
`Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object.`
using `${env:someProgramsPath}` a message box pops up with the following message:
`launch: program "\program_A_.exe" does not exist`
with the variable resolved to nothing

**Comment by weinand** [comment]
Yes, we should disambiguate OS-level environment variables (`${env:XXX}`) and the VS Code-only variables you are asking for (which do not yet exist).

But there is something close: in task.json and launch.json you can refer to "settings" via the  `${config:XXX}` syntax, so you can have a workspace setting:
```
{
	"someProgramsPath": "/some/path"
}
```

and use it like this:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${config:someProgramsPath}"
		}
	]
}
```

**Comment by MaliusArth** [comment]
Ah yes, this does indeed work.
So my feature request would be to be able to define such configs in the files that use them directly as well.

**Comment by angelhdz** [comment]
> Yes, we should disambiguate OS-level environment variables (`${env:XXX}`) and the VS Code-only variables you are asking for (which do not yet exist).
> 
> But there is something close: in task.json and launch.json you can refer to "settings" via the `${config:XXX}` syntax, so you can have a workspace setting:
> 
> ```
> {
> 	"someProgramsPath": "/some/path"
> }
> ```
> 
> and use it like this:
> 
> ```
> {
> 	"version": "0.2.0",
> 	"configurations": [
> 		{
> 			"type": "node",
> 			"request": "launch",
> 			"name": "Launch Program",
> 			"program": "${config:someProgramsPath}"
> 		}
> 	]
> }
> ```

What about Themes? Can we define variables in the tasks or launch *.json files to store colors that we can use in the themes.json?

**Comment by weinand** [comment]
@angelhdz I do not see how theme colors are related to tasks or launch *.json.

**Comment by angelhdz** [comment]
> @angelhdz I do not see how theme colors are related to tasks or launch *.json.

It was a question and you answered it, thanks. So we'll have to wait for Custom Variables in configuration and theme files, feature to be added.
