### ISSUE TITLE
Adding/Updating json schema programmatically  from third party plugin

### ISSUE THREAD

**Issue by ramank775** [microsoft/vscode#79363]
I am looking for a plugin API where a custom plugin can update contributes specially jsonValidation schema programmatically. Currently a plugin can add a schema in package.json file.

I am developing a plugin where user able to create json schema definition within the workspace or reference any existing schema as definition and can perform validation against the schema generated by the plugin.

Note: I have explore existing json language server, but it only has support for file based or remote schema.

**Comment by aeschli** [comment]
This comment describes how you can register a schema with dynamic content:
https://github.com/microsoft/vscode/issues/77433#issuecomment-512726599

**Comment by ramank775** [comment]
@aeschli  Thanks for the update

**Comment by ramank775** [comment]
@aeschli can you help with clearing schema cache when dynamic schema change?

**Comment by aeschli** [comment]
The `TextDocumentContentProvider` that you provide has a `onDidChange` event. You must fire this event when the document with your schema changes. The JSON language server will then clear it's cache and reload the schema.

**Comment by ramank775** [comment]
@aeschli onDidChange event do not clear the schema, i have tried this approach.

The Reason why JSON language server not clearing  the schema is the following code
`let handleContentChange = (uri: Uri) => {
			if (uri.scheme === 'vscode' && uri.authority === 'schemas') {
				client.sendNotification(SchemaContentChangeNotification.type, uri.toString());
			}
};`
This is in JSON language server client code [here](https://github.com/microsoft/vscode/blob/b8ec1d77339d61f4331c74b7bfc273fd0128bb44/extensions/json-language-features/client/src/jsonMain.ts#L167), which check if the content change has schema `vscode`.
which prevents the resetSchema function being executed on the server.

**Comment by aeschli** [comment]
@ramank775 Good catch!

**Comment by ramank775** [comment]
@aeschli  Thanks. 👍
