### ISSUE TITLE
php code syntax highlighting

### ISSUE THREAD

**Issue by osben** [microsoft/vscode#79370]
Issue Type: <b>Bug</b>

screen https://prnt.sc/ou0hly

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (22.48GB free)|
|Process Argv|E:\gitlab\web-wizard\watch-family.ru\simpla\DeliveryAdmin.php|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
gitlens|eam|9.9.3
vsc-material-theme|Equ|30.0.0
php-intellisense|fel|2.3.10
smarty|imp|0.3.0
vscode-jetbrains-keybindings|isu|0.1.9
mysql-syntax|jak|1.3.1
remote-wsl|ms-|0.39.2
material-icon-theme|PKi|3.8.1
vscode-icons|vsc|9.2.0

</details>

**Comment by alexr00** [comment]
Can you try disabling all extensions and see if the problem still happens?
If the issue still occurs, can you add a copy/pasteable example please?
