### ISSUE TITLE
intellisense doesnt work on osx

### ISSUE THREAD

**Issue by yas666** [Microsoft/vscode#7937]
- VSCode Version: latest
- OS Version: OSX El capitan

Steps to Reproduce:

1. download visual studio code on osx
2. download and install unity
3. use ext install to install legacy c# tools
4. try and access unity engine api.
5. type transform in void start or a similar function
6. use dot notation to access methods and find that you cannot get the list.

**Comment by dbaeumer** [comment]
@jrieken assigning to you since he installs the legacy tools.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#591
