### ISSUE TITLE
linux 下自带终端黑屏

### ISSUE THREAD

**Issue by CapZhang** [microsoft/vscode#79375]
> 版本: 1.36.1
> 提交: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
> 日期: 2019-07-08T22:55:08.091Z
> Electron: 4.2.5
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Linux x64 4.15.0-29-generic

以上是我的系统信息，在使用的过程中总是出现vscode中自带的终端工具黑屏，需要重启vscode才能够正常加载
不知道是否跟我更换了终端字体有关
![图片](https://user-images.githubusercontent.com/19522615/63219607-f1169900-c1a7-11e9-82a8-4c76c48d0698.png)
![图片](https://user-images.githubusercontent.com/19522615/63219611-05f32c80-c1a8-11e9-9d1f-e3ecdeebbb52.png)

以下是可能有用的ubuntu系统的错误报告
![图片](https://user-images.githubusercontent.com/19522615/63219620-55d1f380-c1a8-11e9-99b4-48efcb06b132.png)
![图片](https://user-images.githubusercontent.com/19522615/63219634-b5c89a00-c1a8-11e9-92da-cc66c029fab4.png)

**Comment by CapZhang** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [EXPLORER keybindings don't work (#76555)](https://www.github.com/microsoft/vscode/issues/76555)

这是什么意思。。。给出的和我提出的缺陷并没有关系

**Comment by wjp2013** [comment]
@CapZhang 提交和回复 issue 要用英文的。

以我初中水平的阅读理解来说，上面的回复翻译为：感谢您提交此次问题报告。请首先检查该问题是否已经被先有的提问所覆盖，例如：
* EXPLORER keybindings don't work (#76555)

并不是说它的回复就是你期望的答案。

英文差的话，可以用 Google 翻译。

**Comment by CapZhang** [comment]
> @CapZhang 提交和回复 issue 要用英文的。
> 
> 以我初中水平的阅读理解来说，上面的回复翻译为：感谢您提交此次问题报告。请首先检查该问题是否已经被先有的提问所覆盖，例如：
> 
>     * EXPLORER keybindings don't work (#76555)
> 
> 
> 并不是说它的回复就是你期望的答案，因为它只是个自动回复的机器人。
> 
> 英文差的话，可以用 Google 翻译。

很少用github。。。我知道他啥意思，但是不知道他接下来会怎么处理，谢谢回复，哈哈哈

**Comment by isidorn** [comment]
Please file this issue in English, we do not speak Chineese.
