### ISSUE TITLE
gulpfile icon not used for gulpfile.js

### ISSUE THREAD

**Issue by DanielRuf** [microsoft/vscode#79372]
Files with the filename `gulpfile.js` do not get the correct icon (which should be the red gulp icon).

- VSCode Version: 1.37.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file `gulpfile`
2. Rename it to `gulpfile.js`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by aeschli** [comment]
That's as defined by seti-ui.
https://github.com/jesseweed/seti-ui/blob/85a222708824c6f19bbecbec71633d2c97077dad/styles/components/icons/mapping.less#L514

You can file an issue or make a PR there
