### ISSUE TITLE
Can't use snippet in markdown file

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#79384]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I create a snippet file named markdown.json and define a snippet in it,but i can't use it in .md files.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|1.8.8
vscode-tomcat|ada|0.11.1
copy-relative-path|ale|0.0.2
vscode-color|ans|0.4.5
color-info|bie|0.5.1
emojisense|bie|0.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.1
vscode-eslint|dba|1.9.0
vscode-faker|dee|1.3.0
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.8
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-lombok|Gab|0.9.8
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-power-mode|hoo|2.2.0
icon-fonts|idl|2.1.5
relativepathrefactor|jak|0.9.0
latex-workshop|Jam|7.3.0
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
docthis|joe|0.7.1
vscode-peacock|joh|3.1.0
mdhelper|jos|0.0.11
intellij-idea-keybindings|k--|0.2.34
node-module-intellisense|lei|1.5.0
vscode-exec-node|mir|0.5.1
vscode-json5|mrm|1.0.0
vscode-language-pack-zh-hans|MS-|1.37.5
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
debugger-for-chrome|msj|4.11.7
sqltools|mtx|0.20.2
gradle-language|nac|0.2.3
vetur|oct|0.22.2
vscode-versionlens|pfl|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.10.0
vscode-manifest-yaml|Piv|1.10.0
vscode-spring-boot|Piv|1.10.0
vscode-css-peek|pra|3.0.2
java|red|0.47.0
vscode-xml|red|0.8.0
vscode-yaml|red|0.4.1
vscode-checkstyle|she|1.1.0
vscode-leetcode|she|0.15.2
html5-boilerplate|sid|1.0.3
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
latex-utilities|tec|0.1.0
pdf|tom|0.5.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.2.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.240
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
markdown-pdf|yza|1.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
How are you trying to insert the snippet?

**Comment by bonaluo** [comment]
print prefix

**Comment by mjbvz** [comment]
What does that mean? Explain step by step how to reproduce the issue

**Comment by bonaluo** [comment]
I had found the solution:
`
    "[markdown]": {
        "editor.quickSuggestions": {
            "strings": true
        }
    },
`
