### ISSUE TITLE
my vxcode can't be upgraded

### ISSUE THREAD

**Issue by meiyouqing** [microsoft/vscode#79385]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:42:49.304Z)
- OS Version: Darwin x64 18.2.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-extension-auto-import|NuclleaR|1.4.3|
|vscode-styled-jsx|blanu|0.2.3|
|cpptools|ms-vscode|0.10.2|
|python|tht13|0.2.3|

---

Steps to Reproduce:

1.After i launched VSCode,it says 'a new version is ready, would you restart now?'
2.Then i restart it, and the step 1 repeat again

**Comment by joaomoreno** [comment]
Can you fully uninstall it, then download it again, copy it to Applications and retry later?
