### ISSUE TITLE
[javascript] enum keyword from typescript being interpreted in javascript files

### ISSUE THREAD

**Issue by baybal** [microsoft/vscode#79382]
- VSCode Version: 1.36
- OS Version: 5.1

Steps to Reproduce:

1. make a JS file
2. write `const enum = 'lalala'`
3. `enum` constant name will be highlighted as syntax error

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is correct. `enum` is a reserved keyword in JS
