### ISSUE TITLE
Remove Linked Repos After They Were Unlink

### ISSUE THREAD

**Issue by zavr-1** [microsoft/vscode#79396]
- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: macos 10.14

Steps to Reproduce:

1. link a package
2. open a file from that package. git view will show the repo as linked
3. unlink package
4. git keeps showing the linked repo 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
> link a package

What does this mean?

**Comment by zavr-1** [comment]
@joaomoreno that's when you do `yarn link` on node.js packages

**Comment by joaomoreno** [comment]
Alright, merging this into #5970
