### ISSUE TITLE
@notoriousFF high CPU use after some time

### ISSUE THREAD

**Issue by notoriousFF** [Microsoft/vscode#7939]
- VSCode Version: 1.2.1
- OS Version: 10.11.5

Steps to Reproduce:

1. Two monitors;
2. VSCode open in one of them full screen;
3. After some hours the computer slows down and after checking Activity Monitor I get these:
4. With VSCode Opened: https://gyazo.com/450ede25910e78895f60983ac7edd260
5. After Closing VSCode: https://gyazo.com/55d576e7d75363dbe77c813e4dd286e7

**Comment by dbaeumer** [comment]
@notoriousFF could you provide me with the command line of the ElectronHelper executable. This would help understanding what is causing this.

@bpasero does this ring a bell?

**Comment by notoriousFF** [comment]
The "ElectronHelper" only show up when VSCode does this. I will post here once it happens again.

**Comment by bpasero** [comment]
@notoriousFF ping any update?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
