### ISSUE TITLE
Extend features of Code snippets

### ISSUE THREAD

**Issue by BjoernRave** [microsoft/vscode#79399]
First off I am using Typescript most of the time.

Code snippets are already great and I use them alot, they can accelerate your work by so much if used right.

However I see more potential in them:

I would love to have the ability to add an import to the top of my page, depending if it's already there. So you would define an import seperately and vscode checks, if it's there and if not adds it.

Also, not sure if it's the right place,but:

When I use a code snippet which has gaps to be filled it's always in this weird mode, where I don't get autocomplete and it's super annoying

If I am already on it, it would also be awesome to somehow define "areas" in your code, to autojump to when using a codesnippet or shortcut:

For example I am using React with Styled-Component and when I want to create a new styled component I go into my Jsx, replace the "html-tag" with my component name, then go to the part where I have my styled components and define it there.

 It would be great if I could replace my "HTML-tag" with my styled-component name, press a shortcut, which automatically generates a styled-component underneath the last styled component.

I would even be okay, if I need to have some comments inside my code, to create these seperations, like:

```
import React from 'react'
import gql from 'graphql-tag'

const GET_DATA = gql`
...
`

//Graphql Queries (seperator, so vscode knows where to put the next one)

const Foo = styled.button``

//styled-components 

const Component = () => (<Foo/>)
```

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/77478#issuecomment-513716905 for an answer to one of the things you raised.

**Comment by BjoernRave** [comment]
@gjsjohnmurray thanks for that, didn't know that :)

**Comment by jrieken** [comment]
please file separate issues for separate things. thanks
