### ISSUE TITLE
Using sortText and textEdit simultaneously when providing completion suggestions in a language server does not work

### ISSUE THREAD

**Issue by OliverSchmitt** [microsoft/vscode#79393]
- VSCode Version: 1.36
- OS Version: Manjaro

When implementing a Language Server that supports the Language Server Protocol VS Code does not behave according to the specification in a certain case. The case includes using the textEdit and sortText simultaneously while providing a list of CompletionItems for the completion request. In this case the sortText property is ignored.

Examples for the problem using the [VS Code completion](https://github.com/microsoft/vscode-extension-samples) and the [pygls](https://pypi.org/project/pygls/) language server framework for python can be found in this [issue](https://github.com/microsoft/language-server-protocol/issues/785) against the Language Server Protocol. This seems to be an issue effecting different language server implementations as well as different language clients.

**Comment by dbaeumer** [comment]
@OliverSchmitt can you provide a test case (best based on the completion item sample) that demos this using pure VS Code extension API

**Comment by OliverSchmitt** [comment]
Yes, I can. I actually already did that in [this](https://github.com/openlawlibrary/pygls/issues/75#issuecomment-507652251) issue.

**Comment by jrieken** [comment]
Seems to work just fine. What is your issue? Can you add steps, expected and actual behaviour?

<img width="382" alt="Screenshot 2019-08-21 at 12 04 00" src="https://user-images.githubusercontent.com/1794099/63423043-c62c7f00-c40b-11e9-92a5-00af514c6636.png">

**Comment by OliverSchmitt** [comment]
You triggered the completion by pressing `ctrl+space`, right? It does work for me if I do that as well.
I am starting to think the issue might be the trigger kind because I noticed different behavior depending on how the completion is triggered.

a) Steps:
1. Pressing `ctrl+space`

Result:
![Screenshot from 2019-08-21 13-14-55](https://user-images.githubusercontent.com/23654754/63427791-4526b500-c416-11e9-880a-a219e6925dd0.png)

b) Steps:
1. Typing `L`

Result:
![Screenshot from 2019-08-21 13-20-51](https://user-images.githubusercontent.com/23654754/63427918-8e770480-c416-11e9-9c0f-b778a742cc6e.png)

c) Steps:
1. Typing `La`

Result:
![Screenshot from 2019-08-21 13-22-04](https://user-images.githubusercontent.com/23654754/63427974-b2d2e100-c416-11e9-81f3-e3f8e15439b8.png)

d) Steps:
1. Pressing `ctrl+space`
2. Typing `La`

Result:
![Screenshot from 2019-08-21 13-23-13](https://user-images.githubusercontent.com/23654754/63428037-db5adb00-c416-11e9-9304-02bcbbfeff95.png)

If I test the same cases with the `insertText` instead of the `textEdit` property of the `CompletionItem` case b) and c) have the same results as case d), also with the prefix highlighting.

**Comment by jrieken** [comment]
This is because the completion using the `textEdit` always uses the current position as range. The range is the "text selection" that is to be replaced and therefore it also defines what prefix is used for filtering/sorting. If there is no prefix (no text selection, range is cursor position) then there is nothing to compare against with. When not having a prefix, the default is the current word. When showing suggestions, press `Cmd/Ctrl+/` so get a explainer.
