### ISSUE TITLE
Selected text is not copied to find panel with CTRL+F

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#79391]
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Select a text and press CTRL+F to open find panel

Actual Result:
Text not changed in find panel

Expected Result:
Selected text should be filled in find panel like in notepad and all other editors.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@Daijobou can you please provide recordings/gif to help troubleshoot as I can't reproduce it.

**Comment by Daijobou** [comment]
All extensions are disabled. I only double click on text and press ctrl+f to open find panel. 

![vscode_find](https://user-images.githubusercontent.com/260343/63500879-f9821300-c4ca-11e9-99c0-8e3f0ad4310c.gif)

Here the same with notepad, vscode working before last update so too. This changed with version 1.37.1.
![notepad_find](https://user-images.githubusercontent.com/260343/63501182-82994a00-c4cb-11e9-9656-fd47626fa956.gif)

**Comment by Daijobou** [comment]
Issue is in version 1.38 too.

**Comment by Daijobou** [comment]
bug still exists in

Version: 1.39.1 (system setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Datum: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

**Comment by Daijobou** [comment]
editor.find.seedSearchStringFromSelection was disabled... after enabled is working fine again. I never disbaled this option -.-
