### ISSUE TITLE
Confusing open file tab highlight color.

### ISSUE THREAD

**Issue by unix-based-system** [microsoft/vscode#79392]
Issue Type: <b>Feature Request</b>

Would it be possible to change the highlight color of the active file in the top bar? The current viewed file is a dark color (same as the editor background) and the un-opened files are highlighted. The result is confusion on which file is opened. I tested this on a few people and they all thought that the highlighted tab was the opened file.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@unix-based-system have you checked our theme colors? Can you mockup a screen what you want to change and check if this is not already possible?

**Comment by unix-based-system** [comment]
![Capture](https://user-images.githubusercontent.com/54240100/63287992-e9e0af80-c2bb-11e9-8967-3787d4c6e0bd.PNG)

Hello bpasero, no I've not yet checked the theme colors.
But the tab color seems off design wise. The highlighted (non active) tab visually attracts more attention (even though the font is slightly darker / faded). I tested this on a few people and many of them thought the highlighted tab was the active one. My suggestion is to switch the highlight color with the actual active tab.

Thanks, Pim

**Comment by bpasero** [comment]
Got it. There is plenty of themes you can use and colors can also be customized via settings. Please try that.

**Comment by unix-based-system** [comment]
Ok, thanks

I guess it is a preference indeed and maybe it is a subjective perception.
I am new to Visual Studio Code so I will check theme colors.

Again Thanks.
