### ISSUE TITLE
The duplication of HTML TAG with ctrl + d comes very important sometimes.

### ISSUE THREAD

**Issue by zbandhan** [Microsoft/vscode#794]

**Comment by alexandrudima** [comment]
@zbandhan Not sure what you mean. Can you please describe the feature you want in more detail. What do you mean by duplication of HTML TAG ?

**Comment by zbandhan** [comment]
@alexandrudima  if I need more than one same HTML element,  I'll type only the first one and then press ctrl + d on keyboard to duplicate that element as many times as needed.
for example:
I write once li element in vsc
<li></li>
but I need that same element five times. Now wanna do it with ctrl + d shortcut not to copy paste nor type five times.
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>

**Comment by alexandrudima** [comment]
@zbandhan. Here are two ways to do what you describe:

### Option 1
 * open a html file
 * type `li*5`
 * press `tab`
 * [this is Emmet kicking in](http://docs.emmet.io/abbreviations/syntax/)

### Option 2
 * open a html file
 * type `<li></li>`
 * run `editor.action.copyLinesDownAction` (I think under Windows bound by default to `shift+alt+down`)
