### ISSUE TITLE
Some command names not showing in keyboard shortcuts editor

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#79404]
**Explanation:**

From my understanding, when in the Keyboard Shortcuts UI editor:

- the command column defaults to showing the command name (when one is available for the command id)
- command IDs are differentiated by a lighter font weight in the commands column
- command names indicate that a command ID can be executed in the command palette

There isn't any documentation on this, however, so maybe I'm wrong. Assuming I'm right, though, it looks like some command names are not showing as they should.

**Steps to Reproduce:**

1. Open command palette and search for the `View: Close Editor` command, noting that it exists.
2. Open the keyboard shortcuts UI editor and search for `View: Close Editor`. Note that the _command name does not appear_.
3. Clear the search input and search for `workbench.action.closeActiveEditor`. Note that the command ID appears, and it is the command ID that is executed by the `View: Close Editor` command name. To prove this, change the keybinding for this command ID and then search for the `View: Close Editor` command name in the palette once more, noting that the keybinding shown to the right of that command name in the palette is now changed as well.

**More Information:**

I've run into a [similar situation with the `Insert Snippet` command](https://stackoverflow.com/questions/56821217/vscode-keybindings-commands-vs-command-ids), which seems to indicate that there's more going on with command names than I'm aware of. But again, I haven't been able to find any additional information on this.

**Environment:**

- VSCode Version: 1.37.1
- OS Version: macOS Mojave 10.14.4
- Does this issue occur when all extensions are disabled? Yes

**Comment by jabacchetta** [comment]
@sandy081 Same appears to be happening for `editor.action.showSnippets`, which is the command executed by the `Insert Snippet` command. `Insert Snippet` command name is not showing up above the command ID. This command name should maybe be renamed to `Show Snippets` as well? Because there's also a separate `insertSnippet` command ID.

**Comment by sandy081** [comment]
Good catch @jabacchetta. Filed a separate issue https://github.com/microsoft/vscode/issues/80197 to track it.
