### ISSUE TITLE
Pasting from editor to integrated terminal fails with line continuation

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#79401]
Issue Type: <b>Bug</b>

If I start creating a new Powershell script and enter
```
    Get-Process `
        -Name code

```
using line continuation and indentation on the continued line,  then copy and paste that into the integrated terminal, the command fails.  

![image](https://user-images.githubusercontent.com/12263288/63229348-76f90b00-c1cd-11e9-90cd-10cb1a354022.png)
(It also fails if the continued line is *not* indented)

If, at the same time, I open a PowerShell window and paste in the same clipboard contents, the command works as expected:

![image](https://user-images.githubusercontent.com/12263288/63229371-92641600-c1cd-11e9-97bf-34b17cc6ca34.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|9.9.3
code-runner|for|0.9.14
gc-excelviewer|Gra|2.1.32
mssql|ms-|1.6.0
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
partial-diff|ryu|1.4.0
vscode-hexdump|sle|1.7.2

</details>

**Comment by Tyriar** [comment]
Works for me in pwsh and powershell.exe:

![image](https://user-images.githubusercontent.com/2193314/63305927-95c6d280-c29d-11e9-85a2-9f3e35a997c5.png)

Probably an issue with the PS extension.
