### ISSUE TITLE
Terminal issue

### ISSUE THREAD

**Issue by weathon** [microsoft/vscode#79408]
Same as #76101
But this time it happened on Linux.

**Comment by Tyriar** [comment]
@weathon you'll need to be more descriptive and give a repro, the issue you linked is related to the system on Windows that emulates how terminals work on Linux, it is definitely not related to that. Please also provide os/vscode version and your settings file.

**Comment by weathon** [comment]
I cannot find this bug in my VSCode anymore, maybe it is already be fixed?
