### ISSUE TITLE
Crashing code helper 100% CPU on mac 

### ISSUE THREAD

**Issue by entobarn** [microsoft/vscode#79405]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

VScode is crashing frequently. Reliably replicates when I do a search in all files.

No plugins enabled. Occurs on versions 1.36 and 1.37. 

Issue is somewhat resolved in version 1.35. 

code --status (from spike) below:

[44505:0819/084627.226967:WARNING:dns_config_service_posix.cc(181)] dns_config has unhandled options!
Version:          Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS Version:       Darwin x64 17.7.0
CPUs:             Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)
Memory (System):  24.00GB (9.02GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     enabled
                  oop_rasterization:             unavailable_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 unavailable_off
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    3	   123	 39995	code main
    0	    49	 39996	   gpu-process
    3	   123	 40421	   shared-process
    1	     0	 44508	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    98	 43749	   window (Issue Reporter)
   73	   614	 44319	   window (Welcome — onboarding)
    0	    74	 44340	     extensionHost
    0	    49	 44341	     watcherService
    0	   541	 44431	     searchService

Workspace Stats:
|  Window (Welcome — onboarding)
|    Folder (onboarding): 1695 files
|      File types: js(947) svg(234) css(212) md(79) png(59) html(34) jpg(27)
|                  hbs(21) json(9) map(8)
|      Conf files: package.json(3) webpack.config.js(2)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (9.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   123	 39995	code main
    0	    49	 39996	   gpu-process
    0	   123	 40421	   shared-process
    0	     0	 44935	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   246	 44895	   window (Welcome)
    0	    74	 44908	     extensionHost
    0	    98	 44932	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by roblourens** [comment]
Can you tell me what you did right before getting that status? It doesn't show a search running, it just shows the renderer process very busy.

If you are able to before the window crashes, it would be helpful if you can get a recording from the Performance tool in chrome devtools for the window (Help > Toggle Developer Tools)

**Comment by nerdomancer** [comment]
For me it happens when I do a solution wide search and click on one of the results to see the related file.

**Comment by roblourens** [comment]
Closing, I can reopen if you have more info @entobarn. @nerdomancer please open a new issue with as many details as possible.
