### ISSUE TITLE
Support Jerkyl sass support

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79406]
Jekyll's Sass integration is described in full here: https://jekyllrb.com/docs/assets/

Basically, any `<file>.scss` file is compiled to `<file>.css` if it contains frontmatter at the top:

```css
---
---

body {
  background-color: red;
}
```

![image](https://user-images.githubusercontent.com/2193314/63231744-27b6d880-c1d5-11e9-8e30-1844d39e9ae2.png)

Additionally you can import from `_sass/_<file>` which don't need any special frontmatter to work.

---

You can use files.exclude to ignore it, but that hides the file from the user when it shouldn't be:

```
{
    "files.exclude": {
        "css/style.scss": true
    }
}
```

---

https://github.com/microsoft/vscode/issues/47354 is asking for a way to easily hide errors, I think what I'd like is that plus the setting as described in https://github.com/Microsoft/vscode/issues/52011 to ignore files from problems only.

I don't think it's possible to disable this using the `scss.lint.*` settings

**Comment by Tyriar** [comment]
In `css/main.scss` (this could be anywhere)

```
@import "something"
```

**Comment by octref** [comment]
I agree with https://github.com/jekyll/jekyll/issues/3408#issuecomment-118425400

Supporting arbitrary syntax extensions that's not in the language standard doesn't seem productive to me. It's a Jekyll problem for not going with standard scss.

**Comment by Tyriar** [comment]
@octref I agree, but I also think I should be able to ignore problems in certain files since these can happen for several reasons. While the Jekyll syntax isn't the best, it's seems pretty nice not to worry about setting up sass compilation at all.

**Comment by aeschli** [comment]
I think that has to come from an extension.
- extension defines a new language jerkyl-scss
- extension implements a new language server based on our css language service.

See https://code.visualstudio.com/api/language-extensions/embedded-languages
