### ISSUE TITLE
Trackpad Scrolling crashes

### ISSUE THREAD

**Issue by mhornbacher** [microsoft/vscode#79403]
Complex to reproduce but randomly the trackpad will no longer scroll. This is solved by a reload of Visual Studio code.

VSCode version: 1.37.1
Windows Version: 10 Pro, 1903
Hardware: Lenovo X1 Carbon 5th Generation

**Comment by mhornbacher** [comment]
It seems to happen when dealing with very large files and diffs.

**Comment by deepak1556** [comment]
Can you try our exploration builds which has improvements for trackpad scrolling https://github.com/microsoft/vscode/pull/75802#issue-289924821 and see if the hang still occurs. Thanks!
