### ISSUE TITLE
VSCode v1.37 crash on start with powershell .net framework exception

### ISSUE THREAD

**Issue by deping** [microsoft/vscode#79410]
- VSCode Version: 1.37
- OS Version: Windows 10 64 企业版

Steps to Reproduce:

1. just start up VSCode, it will crash

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deping** [comment]
v1.36 has this problem, too.

I downgrade it to v1.36, and when I open powershell terminal, it crash.
When I switch default terminal to cmd, it is alright. It doesn't crash before today.

**Comment by gjsjohnmurray** [comment]
The thread at #56810 looks like it gives some pointers on how to investigate this kind of issue.

**Comment by deping** [comment]
![image](https://user-images.githubusercontent.com/11288446/63241735-5b523b00-c287-11e9-89d9-44d5245ef882.png)

Before I close the above debuging dialog, I copied the error message from terminal window(some text are chinese characters):

PS F:\SteelStruct>
未经处理的异常:  System.TypeInitializationException: “Microsoft.PowerShell.PSConsoleReadLine”的类型初始值设定项引发异常。 ---> System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指
示其他内存已损坏。
   在 Microsoft.CSharp.RuntimeBinder.Semantics.SYMTBL.InsertChildNoGrow(Symbol child)
   在 Microsoft.CSharp.RuntimeBinder.Semantics.SymFactoryBase.newBasicSym(SYMKIND kind, Name name, ParentSymbol parent)
   在 Microsoft.CSharp.RuntimeBinder.Semantics.BSYMMGR.GetNsAid(NamespaceSymbol ns, KAID aid)
   在 Microsoft.CSharp.RuntimeBinder.Semantics.GlobalSymbolContext..ctor(NameManager namemgr)
   在 Microsoft.CSharp.RuntimeBinder.Semantics.LangCompiler..ctor(CController pCtrl, NameManager pNameMgr)
   在 Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Reset()
   在 Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetInstance()
   在 Microsoft.CSharp.RuntimeBinder.CSharpUnaryOperationBinder..ctor(ExpressionType operation, Boolean isChecked, Type callingContext, IEnumerable`1 argumentInfo)
   在 Microsoft.CSharp.RuntimeBinder.Binder.UnaryOperation(CSharpBinderFlags flags, ExpressionType operation, Type context, IEnumerable`1 argumentInfo)
   在 Microsoft.PowerShell.PSConsoleReadLine..ctor()
   在 Microsoft.PowerShell.PSConsoleReadLine..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
   在 CallSite.Target(Closure , CallSite , Type , Object , Object )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   在 System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   在 System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   在 System.Management.Automation.DlrScriptCommandProcessor.Complete()
   在 System.Management.Automation.CommandProcessorBase.DoComplete()
   在 System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   在 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   在 System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   在 System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   在 System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by deping** [comment]
It has nothing to do with VSCode.
When I run powershell in ConEmu, it crashes the same.
So I close the issue.
