### ISSUE TITLE
vscode should not force me to click a charactor sooo carefully that I am not clicking on the right hard of a charactor

### ISSUE THREAD

**Issue by dove-young** [microsoft/vscode#79414]
- VSCode Version:   1.36.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

The inspire of this issue comes from https://github.com/microsoft/vscode/issues/78463.  You can find details and even a animation demonstration there. 

The problem is not fixed over there. But sine someone was explaining the internal mechanism at that issue, there are some new problem raised.  

> The editor works by taking the position which is closest. So if you click in the first half of a character, the cursor will go to the left of the character, and if you click in the second half of a character, the cursor will go to the right of the character.
>Is this unexpected?

When I click on a single character, according on that explanation, I HAVE TO , I HAVE TO be soooooooooo carefully to most accurately clicking on the exactly LEFT half of a single character, but do my best to control my mouse cursor to NOT slip to a tiny fraction of as millimeter to MISTAKENLY slip across  the middle line ( and it is not even exist right there), to just make a single selection on a string.

If, this IS expected, can you tell me an option ? Can you tell me an option which could make the editor forget this behavior and just select this character no matter I am clicking on the LEFT half or RIGHT half of this charactor? As what it dose all over the world, except VSCode ? 

Thank you.

**Comment by alexandrudima** [comment]
Let's continue discussion in the original issue at https://github.com/microsoft/vscode/issues/78463#issuecomment-522994250
