### ISSUE TITLE
Disabled Auto Detected Tasks Should Have An Option Not To Show This Automatically

### ISSUE THREAD

**Issue by joshuadabejero** [microsoft/vscode#79417]
### Request: Option Not To Show This Automatically

I am using WSL so I can't run directly in there. Tho It's okay if I can't, but I think there should have a settings not to show this to the explorer automatically as it shrink the explorer view.

![image](https://user-images.githubusercontent.com/29270980/63237046-f0970480-c272-11e9-8ba1-b332aea79ad2.png)

**Comment by egamma** [comment]
This is an intended change https://code.visualstudio.com/updates/v1_37#_npm-scripts-explorer-visible-by-default.

>I am using WSL so I can't run directly in there. 

You should use the WSL remote extension than you can runs scripts also in WSL, pls see
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
