### ISSUE TITLE
Sometimes some functions will fail and need to be restarted.

### ISSUE THREAD

**Issue by zhengxdlol** [microsoft/vscode#79412]
Some functions will fail after running for a period of time. For example, drop-down and zoom code intelligently prompts TAB key space not to

**Comment by isidorn** [comment]
Please provide exact reproducable steps. From your descirpitoin I have no clue what you are refering to.
Thanks

**Comment by hwassinger** [comment]
I have not been able to recreate at will however basic's are 
1. create a function in VS Code using powershell extension
2. Call that function later in script

Here's my named function : function Man_Port {
Heres result when I call itMan_Port : The term 'Man_Port' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At Z:\VSCODE\Data\Promote_apps.ps1:55 char:1
+ Man_Port
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Man_Port:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
