### ISSUE TITLE
Search list of words and need result in report/tabular form

### ISSUE THREAD

**Issue by yasarshaikh** [microsoft/vscode#79418]
As of now, VS Code supports single word search for given file/all files. However need to have a **set of words** searches(e.g. need to check if set of fields referred in current code base) **in entire code base/directory**. 

Sample response will be like:

|Sr.No. | Word | File Name |
| 01 |  Sample word | CodeName1.js |
| 02 |  word | CodeName1.js |
| 03 |  Sample word | CodeNameNumber.js |

**Comment by roblourens** [comment]
It's not exactly clear what you are asking for. If you just want to check whether a file matches query1 or query2, you can write a regex for that. If you want anything more complex, an extension could do this.
