### ISSUE TITLE
Debugging hangs for a powershell script containing git commands.

### ISSUE THREAD

**Issue by lawrencebr** [Microsoft/vscode#7941]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a script with "git clone" in it, my script is below:

`Write-Host "Start Git Test";

$result = git clone <git repo> "$PSScriptRoot\test.git" 2>&1;

Write-Host "Finished Git Command";
Write-Host $result;`

please note that the <git repo> I am attempting to clone is a local bare repository on my hard drive, so no credentials are needed.
2. Debug the script
3. At this point, for me, the script hangs, the only way I can get it to finish is to pause it, wait a minute, then it will go to the next line, and I can either step through or continue to the end.  I have attached the error displayed on the console in the developer's tools.

If I run the same script from powershell it does not hang, but completes fine.

**Comment by dbaeumer** [comment]
This issue was moved to PowerShell/vscode-powershell#214
