### ISSUE TITLE
Add a command to show the value of variables WITHOUT the pain of creating a task. 

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#79413]
Something fast and simple to type in the command palette.

**Comment by gjsjohnmurray** [comment]
Variables in what context? If debugging, doesn't the REPL feature meet your needs?

**Comment by danielmrussell** [comment]
Something I can type into the command palette to get at the value of expressions like ${workspaceFolder} that are used in settings, etc.

The suggested way according to this page: https://code.visualstudio.com/docs/editor/variables-reference

seems very complicated and a PITA, especially for someone new to VSCode like me and wishing to learn. My first instincts were "I can evaluate the variables to see what they contain form the command palette." And it seems I cannot?

Instead I'm supposed to do this bit of craziness:

> One easy way to check a variable's runtime value is to create a VS Code task to output the variable value to the console. For example, to see the resolved value for ${workspaceFolder}, you can create and run (Terminal > Run Task) the following simple 'echo' task in tasks.json:
> 
> {
>     "version": "2.0.0",
>     "tasks": [
>         {
>             "label": "echo",
>             "type": "shell",
>             "command": "echo ${workspaceFolder}"
>         }
>     ]
> }

when really, I feel we should be able to just type "eval ${workspaceFolder} at the command palette.

**Comment by isidorn** [comment]
Feels like this should be done easily by an extension and is a good extension candidate. Thus adding the extension-candidate label.
fyi @alexr00
