### ISSUE TITLE
Add WORKSPACE_FOLDER variable to code snippets

### ISSUE THREAD

**Issue by svdHero** [microsoft/vscode#79428]
Code snippets are great. However, as described in https://code.visualstudio.com/docs/editor/userdefinedsnippets, there's only a build-in variable called `WORKSPACE_NAME` which yields `The name of the opened workspace or folder`, but no variable which yields the full path of the folder opened in VS Code.

Please add another variable called `WORKSPACE_FOLDER` to code snippets, which yields `the path of the folder opened in VS Code`, like the variable of the same name that one can use in `launch.json`and `task.json`, compare https://code.visualstudio.com/docs/editor/variables-reference.

**Comment by hwhung0111** [comment]
I can give it a try.
