### ISSUE TITLE
Enable FileSystemWatcher to watch virtual file systems

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode#79421]
When we implement a virtual file system, the API spec dictates that we need to implement a watch functionality. We have one in progress [here](https://github.com/microsoft/vscode-azurestorage/blob/master/src/azureStorageExplorer/blobContainers/BlobContainerFS.ts) in the azure-storage extension. Thanks @monalgarg! 
Setting up a FileSystemWatcher does not keep track of URI's related to the virtual file paths. [Details in this StackOverflow post](https://stackoverflow.com/questions/57531440/implementing-watch-on-a-virtual-file-system-vscode-filesystemwatcher-does-not). 

One alternative I see is having a side-process that frequently polls the virtual file system for changes, and emits them on VSCode. We noticed that VSCode does a lot of `stat` calls to the File system (in building the file tree for the explorer), so us implementing this watch seems like there would be : 
1. repeated logic/code across multiple explorer providers.
2. Inefficient, since VSCode's stat calls would return information that can be used here (for e.g., create and delete events on files and folders). Us making the similar calls again can be rate-limited by the service serving up the virtual files/folders.

Can my blocker be side-stepped by another approach? 
If not, 
Is there a way to make it easy to have a FileSystemWatcher watch virtual URI's without a lot of repeatable scaffolding?

**Comment by bpasero** [comment]
@PrashanthCorp I do not understand the blocking issue implementing the `watch()` method for your file system provider?

But it seems to me you are asking for a different way of reporting file change events by switching to a polling based approach? That sounds very inefficient to me, and how would it work exactly? Should we stat each file that is opened?

**Comment by PrashanthCorp** [comment]
I was wondering if there's a way to either make `vscode.FileSystemWatcher` work with virtual file URI's (since `fs.watch` will not). Else, if you have pointers on implementing our own watcher for our virtual FileSystemProvider, that would be great too. 

I agree that polling would be pretty inefficient, so I'm looking to see if there are alternatives.

**Comment by bpasero** [comment]
@PrashanthCorp to clarify, you are implementing watch functionality for your custom file system provider and you say `vscode.FileSystemWatcher` does not work even though you do that? That would be a pretty serious bug on our end.
