### ISSUE TITLE
Bad global variable access

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79429]
We have 2 files that make use of global property `name` which will be undefined. 

@isidorn https://github.com/microsoft/vscode/blob/582b187f88ef40c354d37ee792b621be3fc03a91/src/vs/workbench/contrib/files/browser/views/emptyView.ts#L62

@sandy081 `extensionTipsService`: look for `extensionId: name` (4 places)

**Comment by isidorn** [comment]
@bpasero thanks for catching this, I have fixed it in the emptyView, thus unassigning myself
