### ISSUE TITLE
An option to disable current line highlight.

### ISSUE THREAD

**Issue by achshar** [Microsoft/vscode#7942]
- VSCode Version: 1.2.1
- OS Version: Win 10

There should be an option to disable current line highlight. Sublime has it. I find it quite distracting. 

There are other closed issues on this with no real explanation why.

![Current line highlighting](https://cloud.githubusercontent.com/assets/3441158/16246080/51d80bb6-3821-11e6-81f2-78829d4570c3.png)

**Comment by Emeryao** [comment]
+1
 visual studio also has an option for this
