### ISSUE TITLE
for-in loops over arrays should be avoided

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79432]
There is a new TSLint rule to detect `for-in` use for arrays that I think would make sense to enable. We have only few violations.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in and keep in mind that `for-in` may inherit properties from `Object`.

@alexr00 @dbaeumer https://github.com/microsoft/vscode/blob/582b187f88ef40c354d37ee792b621be3fc03a91/src/vs/workbench/contrib/tasks/common/tasks.ts#L988

https://github.com/microsoft/vscode/blob/582b187f88ef40c354d37ee792b621be3fc03a91/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L342

**Comment by alexandrudima** [comment]
:+1: Yeah, not written by me, but I will fix the ones in monarch.

**Comment by alexandrudima** [comment]
Done in monarch.

**Comment by bpasero** [comment]
@alexr00 there seems to be a PR addressing this https://github.com/microsoft/vscode/pull/79551

**Comment by alexr00** [comment]
Fixed in tasks.
