### ISSUE TITLE
Update minifier for core code

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#79433]
We have seen two instances of a bug in uglify-es (#79044, #74321) that appears to be fixed in the latest version of the minifier. Updating to that caused some issues and the project seems to be abandoned atm (1.5 years old release), so I didn't invest additional time.

We need to look into updating to an actively maintained minifier supporting ES6.

/cc @joaomoreno @bpasero

**Comment by bpasero** [comment]
I am adding you @chrmarti because you did this update already and have learned what the consequences where (I think with some language definitions) that you should share here.

I personally feel we should jump to a minifier that is active and maintained, so there is a bit of research required here. So far I heard of (not necessarely active anymore): `uglify-es`, `uglify-js` and `terser`.

**Comment by joaomoreno** [comment]
Jumping out of this since my engineering plate is as full as my actual plate at a Brazilian BBQ.

**Comment by chrmarti** [comment]
Might make sense to use Terser like we do for extensions. That way we would get consistent behavior for all our code.

Article comparing minifiers: https://blog.logrocket.com/uglify-vs-babel-minify-vs-terser-a-mini-battle-royale/.

**Comment by bpasero** [comment]
@chrmarti I have a branch up for using Terser: https://github.com/microsoft/vscode/compare/ben/terser

To workaround the issue we noticed when you tried to go with latest `ugilify-es` I had to set the compress option `hoist_funs: true` which is the same what our current version is doing. I do not fully understand why there is the bug when not using it.

Maybe you can verify that your minification issue is resolved with terser.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/80201

**Comment by bpasero** [comment]
I am running a build with the new minifier and with restoring `await import` (https://github.com/microsoft/vscode/commit/89f679422a8a23480994990af82ada878f176ca8) to see if we can use this pattern now.
