### ISSUE TITLE
lost all markdown codes after restart windows

### ISSUE THREAD

**Issue by saintube** [microsoft/vscode#79435]
Issue Type: <b>Bug</b>

I've written a markdown file for about 200 lines of notes. Then I checkout my Windows Update and press "Ctrl S" before restarting my surface pro 5. But I still lost all my codes when re-opening this file.

VS Code version: Code - Insiders 1.38.0-insider (4fa08902f7845050a948d3d74e3b836276fa613a, 2019-08-19T05:39:53.031Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (4.19GB free)|
|Process Argv|D:\Homework\软件所\nfs\WORK\模拟器调研.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.1
code-runner|for|0.9.14
vscode-docker|ms-|0.7.0
vscode-language-pack-zh-hans|MS-|1.37.5
python|ms-|2019.8.30787
remote-containers|ms-|0.67.4
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.3
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
Go|ms-|0.11.4
typescript-javascript-grammar|ms-|0.0.52
ruby|reb|0.24.2
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
markdown-pdf|yza|1.2.0

</details>

**Comment by Tyriar** [comment]
ctrl+s didn't work?

**Comment by saintube** [comment]
It should work because I've seen the saved mark at the tab bar.  
Actually, I'm not sure whether the data loss was caused by VS Code Insider or Win10 Update. I met the same situation again this morning, when I pressed ctrl+s and restarted OS to update. Luckily I have a backup this time.

**Comment by bpasero** [comment]
@saintube to be clear, you:
* make changes to a file
* you save it (Ctrl+S)
* you leave VSCode open
* you do a restart because of Windows updates (actually Windows restarts for you)

=> the file is empty?

**Comment by saintube** [comment]
@bpasero 
Almost so. I think I've close VSCode before restarting OS. And the next time I opened VSCode, I found an empty Markdown file with only a filename saved.

**Comment by bpasero** [comment]
Does it reproduce if you close VSCode and restart it?

**Comment by saintube** [comment]
@bpasero 
No, it doesn't.

**Comment by bpasero** [comment]
@saintube does it reproduce if you make changes to a file, save it and then restart the OS instead of letting windows update do it?

**Comment by saintube** [comment]
@bpasero I tried it just before but the loss doesn't reproduce either.

**Comment by bpasero** [comment]
Ok I cannot really explain what the difference is...

**Comment by saintube** [comment]
Fine. Thanks anyway.
