### ISSUE TITLE
Overtyping quote in f"" no longer works for Python

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#79430]
Extracted from https://github.com/microsoft/vscode/issues/78975#issuecomment-522320888

---

This also happens with *some* quotes in Python. String literals with a prefix character (Unicode, bytes, formatting, raw) have an automatically generated close quote, but that quote is not swallowed. (Sorry, I don't know how to make those little animated snippets.) This is even though I have **not** moved the cursor *at all*:

    f|  # vertical bar character marks the cursor

    f"|"  # after typing one quote

    f"foo|"  # after typing 'f', 'o', and 'o'

    f"foo"|"  # after typing another quote

**Comment by jkyeung** [comment]
Thanks for creating the new issue. Just to be clear, even though the subject line mentions f-strings, it also applies to the other prefixed string literals in Python: `b"`, `r"`, and `u"`, as well as the single-quote (`'` instead of `"`) variants of all the above.

**Comment by jkyeung** [comment]
So far it looks like it's working in the Insiders build, thanks!
