### ISSUE TITLE
openssh-askpass keeps poping up

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#7944]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04

I am not sure what is causing this, but whenever I one of my projects I keep getting this popup. It locks up everything so I couldn't do a print screen. Anyways No matter what I do, it keeps opening. If I Press `Cancel` or `Ok` it goes away then pop back up a few minutes later. If I try entering a password, or `Yes`/`No` into the input box it still comes back a few minutes later.

![openssh](https://cloud.githubusercontent.com/assets/1571806/16251796/b74e3778-37ee-11e6-847f-c28a08e49176.jpg)

**Comment by dbaeumer** [comment]
Very likely caused by git.

**Comment by joaomoreno** [comment]
You can disable auto fetching with `"git.autofetch": false` in your settings.

**Comment by Christilut** [comment]
I had this too, it kept trying to add a new host to `.ssh/known_hosts` but my permissions were set to 500 on that file. Change the permissions to to 600 with `chmod 600 ~/.ssh/known_hosts` and it should be able to add the new host.
