### ISSUE TITLE
Graphic Glitch - underline links

### ISSUE THREAD

**Issue by Mlocik97-issues** [microsoft/vscode#79448]
- VSCode Version: 1.37.1
- OS Version: Ubuntu 18.04.3 LTS

![Snímka obrazovky z 2019-08-19 16-21-38](https://user-images.githubusercontent.com/31345346/63273181-cc9ce880-c29d-11e9-8c37-e55c93f209c8.png)

**Comment by aeschli** [comment]
How did you end up in that state?
All works for me if I paste 
```
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular-route.min.js"></script>
</head>
</html>
```

**Comment by Mlocik97-issues** [comment]
I pasted in in HTML file, then switched to another file, and then back.

**Comment by aeschli** [comment]
Looks like an editor refresh issue. Switching back and forth editors I also see that links are only partially rendered.

**Comment by alexandrudima** [comment]
related - #76642 , #48321

**Comment by alexandrudima** [comment]
Let's track in #76642 or #48321 . 

I could reproduce wierdness around `text-decoration: underline` in Chrome Canary and I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1012248

**Comment by alexandrudima** [comment]
Let's track in #76642 or #48321
