### ISSUE TITLE
Markdown preview just isn't there anymore

### ISSUE THREAD

**Issue by rummelsworth** [microsoft/vscode#79449]
Issue Type: <b>Bug</b>

1. Open a new text file in VS Code.
2. Enter some Markdown, e.g.
```
# foo

- bar
- baz
```
3. Press `Ctrl+K, V`. Nothing happens, except for the status bar message "The key combination (Ctrl+K, V) is not a command." But it is, according to [the docs](https://code.visualstudio.com/Docs/languages/markdown).
4. Press `Ctrl+Shift+V`. Nothing happens, at all.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.49GB free)|
|Process Argv|. --disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by rummelsworth** [comment]
Sorry for the noise... The language has to be set to markdown. It (obviously) defaults to plain text. Setting it to markdown allows it to work fine.

**Comment by reparke** [comment]
I'm actually having the same issue. I do have the language correctly set to markdown. However, this is the behavior


1. Open a new text file in VS Code.
2. Enter some Markdown, e.g.
```
# foo
- bar
- baz
```
3. Press `Ctrl+K, V`. Nothing happens, except for the status bar message "The key combination (Ctrl+K, V) is not a command." 
4. Press `Ctrl+Shift+V` and it pastes whatever I have on the clipboard
