### ISSUE TITLE
New window does not open

### ISSUE THREAD

**Issue by caelwithcats** [microsoft/vscode#79442]
New window will not open in VSCode. Same problem in the insiders version

## System infomation
- VSCode Version: v1.37.1 | Insiders - v1.38
- OS Version: Windows 10 with the 19h1 update (Build 18362.295)

## Steps to Reproduce:

1. Right click on the Visual Studio code icon in the Taskbar/Start menu
2. Then left click on New Window

works when all extensions are disabled but not when enabled

**Comment by bpasero** [comment]
@caelwithcats is that true?

> works when all extensions are disabled but not when enabled

**Comment by caelwithcats** [comment]
yes, in my case

**Comment by bpasero** [comment]
@caelwithcats I cannot imagine how that is related to disabling extensions, how do you do that when using the "New Window" command?

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by caelwithcats** [comment]
@bpasero You can open the menu by right clicking on the icon or holding and dragging up. The same problem occurs when you use the Visual Studio code insider. For some reason when I disable all the extensions the new window command works. 
![newwindowvscodeinsiders](https://user-images.githubusercontent.com/53895123/63414777-de1df600-c43f-11e9-9754-30de427089a7.png)

**Comment by bpasero** [comment]
> For some reason when I disable all the extensions the new window command works.

Can you identify which extension causes this? I find it rather unlikely it has an impact.

**Comment by caelwithcats** [comment]
@bpasero You were right, because disabling extensions does not seem to take effect any more.

**Comment by bpasero** [comment]
I cannot reproduce, so I cannot tell what this is.
