### ISSUE TITLE
VSCode-win32-x64-1.37.1 slow startup on Windows 7

### ISSUE THREAD

**Issue by anupamgangrade** [microsoft/vscode#79441]
[Uploading prof-5a7c.main.cpuprofile.txt…]()
[Uploading prof-5a7c.renderer.cpuprofile.txt…]()

1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-5a7c.extHost.cpuprofile.txt`
-`prof-5a7c.main.cpuprofile.txt`
-`prof-5a7c.renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@anupamgangrade files aren't uploaded
