### ISSUE TITLE
Show merge commit as "1" in the source control status bar

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#79443]
<img width="396" alt="Screenshot 2019-08-19 at 13 48 35" src="https://user-images.githubusercontent.com/101152/63263245-580b7f00-c288-11e9-8f3c-24d1f253186a.png">

After doing `git merge master` in my feature branch, it would be nice to see "1" here instead of "77".

Note that I understand that technically, the remote cannot reach 77 commits from my `303-nextjs-debugging` branch, but "1" is how humans think about it, and also aligned with how GitHub shows it (if before the merge commit the branch had X commits, with the merge commit, it has X+1).

_(Search terms: status bar, sync icon, version control, source control, Git.)_

**Comment by joaomoreno** [comment]
We currently get the 77 number by running `rev-list --left-right`. What alternative command (or additional flags to that one) would you suggest to execute instead?

**Comment by borekb** [comment]
Maybe `--first-parent`? [From Git docs](https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---first-parent):

> **--first-parent**
> Follow only the first parent commit upon seeing a merge commit. This option can give a better overview when viewing the evolution of a particular topic branch, because merges into a topic branch tend to be only about adjusting to updated upstream from time to time, and this option allows you to ignore the individual commits brought in to your history by such a merge.

**Comment by joaomoreno** [comment]
Give it a try in a couple examples, see whether it works.
