### ISSUE TITLE
Brand new top of line imac can't handle integrated terminal

### ISSUE THREAD

**Issue by Noitidart** [microsoft/vscode#79445]
- VSCode Version:
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

- OS Version: macOS 10.14.6

Steps to Reproduce:

I don't have exact repro steps, it happens randomly.

1. But a brand new imac (top of line)
2. Use VScode, I opened a 4th terminal and did an npm i

Does this issue occur when all extensions are disabled?: Yes/No

I'm not sure, still trying to reproduce. I just wanted to call out I got a brand new comuter, and it still can't handle VScode, how is this possible?

"The standard renderer for the integrated terminal appears to be slow"

<img width="581" alt="image" src="https://user-images.githubusercontent.com/6372489/63265434-78b0e600-c242-11e9-89dd-ccd1f92745e4.png">

**Comment by Tyriar** [comment]
Pressing yes should be fine, it's an Electron issue with canvases.
