### ISSUE TITLE
Test: Markdown extension 

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#7945]
Test plan for #6106

- [x] Windows - @bpasero 
- [x] OS X - @sandy081 
- [x] Linux - @aeschli 

 
Verify
- syntax highlighting in markdown source in all built-in themes
- working markdown preview in all built-in themes
- "open preview" file explorer context menu contribution
- "Show preview", "Open Preview to the Side", "Show source" editor action bar contributions
- keybindings for open/toggle preview
- test custom styles (see #6688)
- test custom styles paths including '#' (see #3613)

**Comment by bpasero** [comment]
@kieferrm there are some issues with the coloring in markdown sources. I stopped filing issues because I am also not sure if our repository is the right place for them.
