### ISSUE TITLE
Render whitespace characters not monospaced when italicized

### ISSUE THREAD

**Issue by tomocafe** [microsoft/vscode#79458]
Issue Type: <b>Bug</b>

I'm using Roboto Mono as my editor font. I have all 8 styles installed (e.g. Regular, Italic, ...)

In my theme, C++ comments are italicized.

I turned on the new `"editor.renderWhitespace": "selection"` setting and find that when selecting a line with comments (italicized text), the character used for space is not the same width as a normal space. This has the rather jarring effect of moving the text around while selecting.

Is this an issue with the font? What is the specific character used to denote space with "render whitespace"?

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

**Comment by tomocafe** [comment]
![screen-capture](https://user-images.githubusercontent.com/20233563/63285480-b1fd4c00-c26a-11e9-9448-bb3f4f7b6a09.gif)

Sorry for awful quality... hopefully this can give an idea what I'm talking about.

**Comment by RMacfarlane** [comment]
Thanks for reporting this @tomocafe, I'm able to reproduce the issue! The specific character for whitespaces is `&middot`, but we should be specifying a width.

**Comment by alexandrudima** [comment]
@RMacfarlane I would change the code to define a width on the spans only when necessary (when we find that the font is not monospace)

**Comment by alexdima** [comment]
@tomocafe I believe this has been fixed in the latest Insiders. Can you please verify?
