### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by simnon** [microsoft/vscode#79457]
Issue Type: <b>Performance Issue</b>

When editing a simple Plain text document Visual Studio Code keeps stalling. Cant interact with app for like 4-5seconds. Happens all the time. 

I open up a folder with a bunch of plain text files. All relatively small, no log files or large data dumps. I click on a file, click on a paragraph and it freezes. Works fine for a bit then click somewhere else and it freezes again. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (3.37GB free)|
|Process Argv|-psn_0_3670912|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    82	 76390	code main
    3	    16	 76392	   gpu-process
    9	    33	 76426	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (week34.txt — manager)
|  Window (client)
|    Folder (manager): 37 files
|      File types: txt(23) pptx(5) DS_Store(2) code-workspace(2) pdf(2) doc(2)
|                  pages(1)
|      Conf files:
|    Folder (client): more than 24823 files
|      File types: png(7638) h(6225) json(2617) pcm(1998) swift(1790) m(1161)
|                  timestamp(825) plist(281) mobileprovision(181)
|                  bcsymbolmap(134)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.11.2
language-plantuml|qho|0.0.3
pretty-json|sup|0.0.3

</details>

**Comment by RMacfarlane** [comment]
Hey @simnon, thanks for reporting this. When you see this issue again, can you try opening the Process Explorer as described [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu) and see if there's a process using a high amount of CPU?
