### ISSUE TITLE
Green TSLint

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79454]
After enabling and pushing some more TSLint rules, we should try to get to 0 warnings to make it possible to make our build fail when there are any TSLint warnings.

To run: `gulp tslint`

So far we have:
* for-in-loops: https://github.com/microsoft/vscode/issues/79432
* DOM in Common
  * https://github.com/microsoft/vscode/issues/79426
  * https://github.com/microsoft/vscode/issues/79425

**Comment by sandy081** [comment]
Fixed in files I own.

**Comment by bpasero** [comment]
There is still https://github.com/microsoft/vscode/issues/79425 and https://github.com/microsoft/vscode/issues/79210 but we can track that independently.
