### ISSUE TITLE
electron-browser/openerService.ts isn't needed

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#79453]
Commit ba69d8dcccaebbfaa94906503728eb7c3e45b9c1 adds another opener service so that it can take a dependency onto the `IWindowService`. That's not needed as the *base* opener service allows to register handler, see: https://github.com/microsoft/vscode/blob/c8d44e24dd250d416475a10efe64e35c9e2c65b3/src/vs/platform/opener/common/opener.ts#L23

Yet another opener service adds unnecessary code/bloat

**Comment by jrieken** [comment]
Oh, `open` vs `openExternal` not nice but understood. I think it should still use the opener-logic tho

**Comment by bpasero** [comment]
@jrieken to be clear: instead of having a separate service, we allow to register an opener that takes care of the `openExternal` thingy for electron?

**Comment by jrieken** [comment]
Yeah, well actually two issues 

* Generally, I think one opener service is better than two, esp since the former allows contributions. 
* Tho I think it's weird that `IOpenerService` has `open` and `openExternal` esp. since the implementation of `open` calls `openExternal`. As a consumer, how would I know what to call? Should consumers look at schemes first? Should `openExternal` maybe be internal and be used as fallback in case we cannot open something with the registered openers?

**Comment by bpasero** [comment]
@jrieken yeah I can see to get the count to 2.

We can think about merging `open` and `openExternal` but for now I would prefer to preserve our existing behaviour as much as possible. After all, `open` is doing things different from `openExternal`, so we cannot just merge them both into one unless we would introduce an option (which is similar to having 2 methods).
