### ISSUE TITLE
An interface anomaly occurs when adjusting the sidebar

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#79451]
Issue Type: <b>Bug</b>
An interface anomaly occurs when adjusting the sidebar
The settings icon appears above the sidebar.
As you adjust quickly, you'll see this setting icon above the sidebar.
![批注 2019-08-19 230259](https://user-images.githubusercontent.com/13393959/63276285-a72bd100-c2d5-11e9-97af-257f9fccfb21.jpg)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
go-outliner|766|0.1.20
better-comments|aar|2.0.5
toml|be5|0.4.0
path-intellisense|chr|1.4.2
dart-code|Dar|3.3.0
flutter|Dar|3.3.0
java-decompiler|dgi|0.0.2
docs-yaml|doc|0.2.3
gitlens|eam|9.9.3
prettier-vscode|esb|1.9.0
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.1
kotlin|fwc|0.2.8
fsharp-language-server|geo|0.1.26
vscode-pull-request-github|Git|0.10.0
rust-test-lens|hde|0.1.2
rest-client|hum|0.22.0
output-colorizer|IBM|0.1.2
comment-translate|int|1.4.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|4.0.6
Ionide-Paket|Ion|1.12.0
mechanic|Ion|0.0.19
solidity|Jua|0.0.58
MagicPython|mag|1.1.0
dotnet-core-commands|mat|1.0.6
vscode-apimanagement|ms-|0.1.1
vscode-language-pack-zh-hans|MS-|1.37.5
vscode-kubernetes-tools|ms-|1.0.2
mssql|ms-|1.6.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
azure-account|ms-|0.8.4
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
github-issues-prs|ms-|0.9.1
Go|ms-|0.11.4
powershell|ms-|2019.5.0
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-next|ms-|3.7.20190817
resourcemonitor|mut|1.0.6
gradle-language|nac|0.2.3
gotestexplorer|pre|0.1.10
Csharp-ASPNETCore|rah|1.11.0
java|red|0.47.0
vscode-xml|red|0.8.0
vscode-yaml|red|0.4.1
rust|rus|0.6.1
crates|ser|0.4.3
vscode-lldb|vad|1.3.0
vscodeintellicode|Vis|1.1.9
azure-iot-toolkit|vsc|2.10.0
vscode-iot-device-cube|vsc|0.1.1
vscode-java-debug|vsc|0.20.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
vscode-icons|vsc|9.2.0
debug|web|0.23.1

(2 theme extensions excluded)

</details>

**Comment by czfadmin** [comment]
![error_edge_2](https://user-images.githubusercontent.com/13393959/63276918-f1fa1880-c2d6-11e9-8b93-4321cba9bef8.gif)

**Comment by RMacfarlane** [comment]
@czfadmin Do you have the `workbench.useExperimentalGridLayout` set to `true`?

**Comment by czfadmin** [comment]
Yes, I have set the   `WorkBench.UserPerimentArGridLayout` to true，
When I set this setting to False is that this bug disappears。

**Comment by sbatten** [comment]
i can repro thanks

**Comment by sbatten** [comment]
i can no longer repro, there were some sash changes that may have been the root cause for this, please verify

**Comment by czfadmin** [comment]
@sbatten . What you said is really correct.Although I still have this problem when I quickly adjust the sidebar, I will turn this option off, it will not affect my normal use. Thank you for your work.

**Comment by bpasero** [comment]
@czfadmin can you reproduce this with our latest insider build still? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by czfadmin** [comment]
@bpasero ,Yes, I am using the latest internal version, I confirmed it again, this problem will still appear, this time it is more obvious than the last time.
![error_edge_3](https://user-images.githubusercontent.com/13393959/64015222-a9ecb880-cb56-11e9-9b81-9ad271f54810.gif)
![error_edge_2](https://user-images.githubusercontent.com/13393959/64015230-ace7a900-cb56-11e9-96eb-aacc1819ded1.gif)
![批注 2019-08-30 184034](https://user-images.githubusercontent.com/13393959/64015234-afe29980-cb56-11e9-8d85-2be1b92e9bfd.jpg)

Will this in the first picture be the effect you want, when the user adjusts the sidebar to a certain size, it will appear?

Ok, I will uninstall it again and re-install it to see if it will happen again.

**Comment by czfadmin** [comment]
I did not reproduce this issue again on the preview version released today.
