### ISSUE TITLE
Code action key-bind shows "No code actions available" when "kind" is more than just "refactor"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#79455]
Given a keybinding like this:

```js
{
	"key": "cmd+. w",
	"command":  "editor.action.codeAction",
	"args": {
			"kind": "refactor"
	},
	"when": "editorLangId == 'dart'"
}
```

When I press `Cmd+.`, `w` I see a list of refactors as expected:

<img width="398" alt="Screenshot 2019-08-19 at 4 27 42 pm" src="https://user-images.githubusercontent.com/1078012/63277983-4b922100-c29e-11e9-9ced-133e014d6af4.png">

However if I change the kind to "refactor.flutter" then I get an error that there are none:

<img width="303" alt="Screenshot 2019-08-19 at 4 28 38 pm" src="https://user-images.githubusercontent.com/1078012/63278038-6b294980-c29e-11e9-96e1-94d6b0f20536.png">

However the `kind`s of the refactors all start with `refactor.flutter.`:

<img width="768" alt="Screenshot 2019-08-19 at 4 29 45 pm" src="https://user-images.githubusercontent.com/1078012/63278111-92801680-c29e-11e9-9ffe-facb488327cc.png">

This was reported by @marko at https://github.com/Dart-Code/Dart-Code/issues/1931 who says it used to work, so this may be a regression. There are no errors in dev tools console.

cc @mjbvz

**Comment by mjbvz** [comment]
The following keybinding works fine for me:

```
	{
		"key": "shift+ctrl+e",
		"command": "editor.action.codeAction",
		"args": {
			"kind": "refactor.extract",
			"preferred": true
		}
	},
```

Does flutter do any sort of filtering based on the requested kind?

**Comment by DanTup** [comment]
Oooh, good catch :(

I have this:

```
if (context && context.only && !context.only.contains(CodeActionKind.Refactor))
	return undefined;
```

The `.contains()` here is checking the requested types explicitly asks for Refactor, but doesn't consider asking for a subset :( The logging in my screenshot above seems to be from the call when the cursor was moved, not when the keybind was invoked.

Thanks!
