### ISSUE TITLE
Window offset and causes caret inaccurate

### ISSUE THREAD

**Issue by whiterkim** [microsoft/vscode#79466]
Issue Type: <b>Bug</b>

1. Maximize the VS Code window.
2. Minimize the window.
3. Bring the window back by clicking the icon in taskbar.
Observe the left up corner of the window.

Expect: The first pixel of the window should align the first pixel of the monitor.
Actual: The first pixel is a few pixels offset to the right down corner (at coordinate around 5, 5).

This causes the bottom edge and the right edge a few pixels clipped and more importantly, the mouse caret still thinks you are at the correct coordinate and the offset makes you caret inaccurate.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18953

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (5.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-idl|kur|0.1.2
vscode-nmake-tools|Mic|2.0.190801001
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
team|ms-|1.149.2
trailing-spaces|sha|0.3.1
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.8.0

</details>

![ss](https://user-images.githubusercontent.com/11396021/63290884-4077ca80-c277-11e9-8acb-39d66049b223.png)

**Comment by deepak1556** [comment]
Can you try our latest exploration builds https://github.com/microsoft/vscode/pull/75802#issue-289924821 and see if the issue still persists. Thanks!

**Comment by whiterkim** [comment]
Got an update of Win10 (from 10.0.18953 to 10.0.18977). And for some reason the issues disappeared.
The Electron version is still 4.2.10. So this actually not caused by electron version.
But anyway it is not happened any more without reinstall VS Code.

Full VS Code version:
Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
**Electron: 4.2.10**
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18977
