### ISSUE TITLE
shortcuts such as ctrl-n ctrl-w stop working

### ISSUE THREAD

**Issue by cottrell** [microsoft/vscode#79468]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Open vscode, works for a few seconds but then stops. I *think * it might be to do with the warning of all the .git submodules (I have 21 in my workspace). I can not find the git pluging to disable it yet.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.37GB (20.31GB free)|
|Process Argv|--open-url|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
graphviz-preview|EFa|1.3.3
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
vim|vsc|1.0.4

</details>

**Comment by cottrell** [comment]
Ok, I'm not 100% but the feeling is vscode works until the very first window popup (in the bottom right). Then shortcuts mostly fail. The alerts could be busted.

**Comment by cottrell** [comment]
And for ref I've disabled most extensions (including git and slowly added them back in).

**Comment by cottrell** [comment]
Another observation is that it appears to happen when *either* vim extension OR git extension is enabled. Both are enough to trigger this behaviour.

**Comment by cottrell** [comment]
Weirdly, opening developer tools (in the help) and <clicking> into it then hitting ctrl-w seems to allow the close signal to propagate.

**Comment by RMacfarlane** [comment]
@cottrell Thanks for the info! This might be the same as https://github.com/microsoft/vscode/issues/72088. When the issue repros, can you also see if we receive the key combination, as shown here https://github.com/microsoft/vscode/issues/72088#issuecomment-489580451? Is there anything special about your keyboard configuration?

**Comment by cottrell** [comment]
I don't think anything special. Just standard PC keyboard (North American layout) and on Ubuntu. I don't have any remappings configured. 

I am not at that computer now but I remember that I would see ctrl + N or something like that appear on the main window at the bottom.

**Comment by alexandrudima** [comment]
@cottrell 
Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by cottrell** [comment]
I see vim has some ctrl-w something 

TaskQueue: Error running task. Failed to handle key=<C-w>. Cannot read property 'selections' of undefined.


![image](https://user-images.githubusercontent.com/223276/64065092-19b77d80-cc01-11e9-8541-e205c880b0e4.png)


But I was seeing this problem even after disabling vim I think (see above thread)

**Comment by alexandrudima** [comment]
There is a keybinding coming in from the vim extension. It works only on certain conditions such as `editorTextFocus` and `vim.active` and `vim.use<C-w>`. I think the first two always are true when installing vim and being focused in a text editor.

The last context key, `vim.use<C-w>`, must be dynamic and based on when that one is true, vim will "steal" Ctrl+W. I suggest that maybe you can contact the vim extension directly or consult their documentation as to what Ctrl+W does.

If you don't want vim to ever "steal" your Ctrl+W keybinding, simply right click on that line and choose Remove Keybinding.

**Comment by cottrell** [comment]
But what I don't understand is why ALL the shortcuts are interfering like this ONLY on linux. I use vscode and vim extension on mac and there is no issue. Same ctrl+n, w, etc shortcuts. Likely vim extension busted is some bad way.
