### ISSUE TITLE
"Toggle VSCode Developer Tools" and "Developer: Inspect Context Keys" don't have access to Interactive Window/Jupyter's UI

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#79463]
With "Developer: Inspect Context Keys" I'm able to focus on any CSS elements without any issues... **except** for UI elements inside Jupyter Notebooks.  Also, "Toggle VSCode Developer Tools" doesn't have access to these elements either.
I'm guessing this limitation might be because Jupyter uses a separate CSS from the rest of VSCode's UI.
Anyway, it would be great if "Developer: Inspect Context Keys" and "Toggle VSCode Developer Tools" didn't discriminate against Jupyter.
Is there a workaround for this?  BTW:  Where is the location of the CSS file for Jupyter on Windows OS?

**Comment by RMacfarlane** [comment]
@mkanet I believe Jupyter Notebooks is using a webview, instead of "Toggle VSCode Developer Tools", can you try `Developer: Open Webview Developer Tools`?

Since it's a webview, I think it's expected that you can't inspect context keys inside of it. Can you describe what information you're trying to get from using `Developer: Inspect Context Keys`?

**Comment by mkanet** [comment]
@RMacfarlane  Thanks for the quick reply.  `Developer: Open Webview Developer Tools` still doesn't identify any of the elements within the Jupyter's iframe; such as the icons.

**Comment by RMacfarlane** [comment]
@mkanet What extension are you using that adds Jupyter Notebooke support?

**Comment by mkanet** [comment]
@RMacfarlane, I'm using Jupyter Notebook directly within VSCode; without any other extensions related to it.  I want to explore the possibility of make a custom CSS for it the same way I've done with extensions like [be5invis/vscode-custom-css](https://github.com/be5invis/vscode-custom-css).  I'd like the ability to use custom icons for Jupyter within VSCode that better matches my VSCode themes.

**Comment by RMacfarlane** [comment]
@mkanet What steps did you take to show the Jupyter Notebook within VSCode? Is it like this:
![Screen Shot 2019-08-19 at 4 35 55 PM](https://user-images.githubusercontent.com/3672607/63306453-716bf580-c29f-11e9-856b-b982b5701dd7.png)
where it's from the Python extension?

**Comment by mkanet** [comment]
@RMacfarlane, the only way I know how to start Jupyter in Jupyter is opening a python file. then selecting, "Python:  Run the current file in Python Interactive Window.
While I have your attention, I'm hoping you might be able to answer a related question:

I'm using an unorthodox VSCode theme where the sidebar and panel are both using DARK backgrounds **while** the editor (and Interactive Window) use a LIGHT background (see below screenshot).  In a case like this, the base UI theme is either going to be compatible with the sidebar and panel backgrounds OR be compatible with the editor and Interactive window, not both.

I'd like to know if there's any way at all to explicitly tell Jupyter to use VSCode's "light" base UI theme and respective icons even though I'm using a "dark" base UI theme (specified in package.json as vs-dark).   That way, the icons in Jupyter will visible.  

If I try to change the base UI theme to be light (in packge.json), icons in Jypyter will be visible, but then icons in the sidebar and panel won't be visible.

It would be great if you (or someone else here) know how to tell the Interactive Window to explicitly use the "light" base UI theme regardless of what's specified in package.json.

![VSCode](https://user-images.githubusercontent.com/811008/63312164-763ba400-c2b5-11e9-825c-9520b2cd1f07.png)

**Comment by mkanet** [comment]
I've already spent a great deal of time on this; and, searching everywhere on Google.  Hopefully someone with more experience than me can shed some light on this and hopefully answer my question in the above post.

**Comment by RMacfarlane** [comment]
@mkanet To my knowledge, there's no way of explicitly specifying this. The rendering of the Jupyter Notebook is controlled by the Python extension, not VSCode. If you use the webview developer tools and look at the root element of the webview, you'll see that there are a bunch of css variables that have been set by VSCode for all of the theme colors. I haven't looked into the extension code, but I except that it's using the theme color for the editor foreground, and is checking whether the theme is light or dark to determine which set of icons to use. (Could search for something like var(--vscode-editor-foreground) to find the css setting the colors in the webview)

**Comment by mkanet** [comment]
@RMacfarlane thank you so much for shedding some light on this.  Based on your last comment, I'm going to close this issue and open a [new issue](https://github.com/microsoft/vscode-python/issues/7050) for Python on Github.  I'm going to see if they can either offer a workaround or add a setting to allow overriding the base UI theme for Jupyter.
