### ISSUE TITLE
If the renderer runs out of memory, the terminal display crashes

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#79462]
Issue Type: <b>Bug</b>

It continues to run, but there's no display which makes it useless.

1. Do something memory intensive -- your physical memory should be full and you should be heavily SWAP-ing

2. Do something to get the renderer to redraw or reinitialize (eg, start a remote desktop session at a different resolution)

3. Crashed terminal display!

![image](https://user-images.githubusercontent.com/165937/63288391-6f8b3d80-c271-11e9-98b3-76a3b68cd557.png)

(note the underlying task continues to run, just the display is gone)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
sqlformatter|bre|0.0.7
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
excel-to-markdown-table|csh|1.1.0
vscode-svgviewer|css|2.0.0
vbscript|Dar|1.0.4
empty-indent|Dmi|0.2.0
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.0
EditorConfig|Edi|0.13.0
LogFileHighlighter|emi|2.5.0
indent-switcher|eph|1.2.1
vsc-material-theme|Equ|30.0.0
terraform-autocomplete|erd|0.0.8
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
vscode-mysql|for|0.4.0
mdmath|goe|2.3.9
gc-excelviewer|Gra|2.1.32
live-html-previewer|hdg|0.3.0
r|Iku|1.1.1
mysql-syntax|jak|1.3.1
cypher-query-language|jak|1.0.2
latex-workshop|Jam|8.0.3
nbpreviewer|jit|1.2.2
language-julia|jul|0.12.1
php-cs-fixer|jun|0.1.120
indentation-level-movement|kai|1.2.1
stata-enhanced|kyl|1.6.1
vscode-emacs-friendly|lfs|0.9.0
terraform|mau|1.3.12
rainbow-csv|mec|1.2.0
code-beautifier|mic|2.3.3
vscode-apache|mrm|1.2.0
vscode-less|mrm|0.6.3
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
cpptools|ms-|0.24.1
csharp|ms-|1.21.0
powershell|ms-|2019.5.0
team|ms-|1.149.2
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
r-lsp|REd|0.1.0
terraform-doc-snippets|run|0.4.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.1
stylelint|shi|0.51.0
vscode-autohotkey|sle|0.2.2
vba-snippets|spe|1.0.1
code-spell-checker|str|1.7.18
tabnine-vscode|Tab|1.3.0
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
latex-support|tor|3.0.1
vscodeintellicode|Vis|1.1.9
markdown-pdf|yza|1.2.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Similar to https://github.com/Microsoft/vscode/issues/69665, the plan is to fix this eventually with https://github.com/xtermjs/xterm.js/issues/2253
