### ISSUE TITLE
Icons keep changing on refresh with wrong icon per file type

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode#79469]
Version: 1.38.0-insider (user setup)
Commit: c8d44e24dd250d416475a10efe64e35c9e2c65b3
Date: 2019-08-19T12:53:53.607Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18963

Steps to Reproduce:

1. install any file icon theme
2. open a project, refresh the file tree

![icons](https://user-images.githubusercontent.com/13103165/63295994-ba8b6c00-c2d6-11e9-8dab-9c0da0bb7a21.gif)

**Comment by isidorn** [comment]
I can not reproduce this with the built-in seti icon theme?
What icon theme are you using? What theme are you using? Can you reproduce if you disable all extensions and use built-in themes?

**Comment by frankintrahouse** [comment]
I have the same issue on the latest insiders build
It seems to be confused no matter what Icon Theme you select, and if you disable the Explorer Decoration: Badges, they still show for some files.

Here are some screenshots:
![Selection_215](https://user-images.githubusercontent.com/29704925/63339600-8b601380-c345-11e9-95ca-a3ab2ae493cc.png)
![Selection_216](https://user-images.githubusercontent.com/29704925/63339609-8f8c3100-c345-11e9-8a89-41ad1eea3bff.png)
![Selection_217](https://user-images.githubusercontent.com/29704925/63339616-9155f480-c345-11e9-9599-d809369a12c7.png)
![Selection_218](https://user-images.githubusercontent.com/29704925/63339622-931fb800-c345-11e9-9d97-eeea13ad395c.png)

**Comment by isidorn** [comment]
I also see some icon funkiness with wrong indent. Forwarding to @bpasero since I believe he touched this area.
fyi @aeschli
