### ISSUE TITLE
Native title bar context menu for Gear button always triggered when you click the right half of the icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79476]
It always appears in this location, so we the first item activates immediately on click:

![image](https://user-images.githubusercontent.com/2193314/63305862-4da7b000-c29d-11e9-9d9b-02c6dbca1ada.png)

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:53.607Z)
OS version: Windows_NT x64 10.0.18956
Remote OS version: Linux x64 4.15.0-55-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (44.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.15.0-55-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (4 x 3491)|
|Memory (System)|10.79GB (0.86GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
EditorConfig|Edi|0.13.0
vscode-pull-request-github-insiders|Git|2019.8.19623
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.67.4
remote-ssh-edit-nightly|ms-|2019.8.26820
remote-ssh-explorer-nightly|ms-|2019.8.26820
remote-ssh-nightly|ms-|2019.8.26820
remote-wsl|ms-|0.39.3
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
vscode-terminal-api-example|vsc|0.0.1
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
fixed this in separate clean up
