### ISSUE TITLE
Create file under cursor

### ISSUE THREAD

**Issue by alexwijoyo** [microsoft/vscode#79479]
Hi,
Can I request a feature similar to Open file under cursor? But it creates file instead of opening it. Another option is to add functionality to Open file under cursor. If vscode can't find the file under cursor it will offer to create the file. 
Thanks.

**Comment by alexwijoyo** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Scroll/Reveal when there are multiple cursors (#6995)](https://www.github.com/microsoft/vscode/issues/6995)

Hi, 
It's not the same issue. Thanks

**Comment by RMacfarlane** [comment]
@alexwijoyo Do you mean under the cursor in the file explorer?
