### ISSUE TITLE
cannot copy/paste text and drag/drop file on VMware MacOS VsCode with win 10 hosting

### ISSUE THREAD

**Issue by panda919** [microsoft/vscode#79471]
I am using VScode final version on MAcOs mojave on VMpalyer 15 and host is win10.
But, after use VScode in 20 mins from MAcOS startup, suddenly copy/paste text (between windows10 and MacOS vmware's VScode ) doesn't work.
Even, Drag/Drop file Between win10 and Vm MacOS.
But, Once i restarted MacOS(without reinstall VMware tool), then it working well 10 mins
and after 10 mins, also copy/paste doesn't work.
I hope kindly help.

**Comment by panda919** [comment]
I didn't get solution for above issue.

**Comment by RMacfarlane** [comment]
Hey @panda919, since there is already an open issue for this, I'm going to close this as a duplicate. This helps us keep track of issues. Please continue discussion in the existing issue instead. Thank you!
