### ISSUE TITLE
DND is broken when using Linux VMs (parallels)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7948]
DND of tabs and editors is broken/works bad on Linux.

**Comment by bpasero** [comment]
DND is really quite broken on Linux...

**Comment by bpasero** [comment]
@Tyriar are you using a VM like parallels? I see this only in Parallels 10.

**Comment by Tyriar** [comment]
@bpasero this was on my laptop that dual boots Ubuntu and Windows.

**Comment by bpasero** [comment]
@Tyriar does it reproduce on Windows too for you or only Linux?

**Comment by bpasero** [comment]
@aeschli do you see this as well in your Linux distro? do you have a machine that runs Linux without parallels?

**Comment by aeschli** [comment]
I only have Linux in Parallels 9. DnD looks ok to me.

**Comment by bpasero** [comment]
Looks like an upstream issue then.

**Comment by bpasero** [comment]
Works a lot better for me with Parallels 11, please update.
