### ISSUE TITLE
Visual Studio Code keeps compiling even if I do not save changes

### ISSUE THREAD

**Issue by itzvarman** [microsoft/vscode#79484]
Issue Type: <b>Bug</b>

I'm using vsc for angular 7 project. After starting project `ng serve` VSC starts compiling again and again even I don't have any single change. It's  irritating while working

Please solve this issue. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
angular2-snippets|dan|1.0.21
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
icon-fonts|idl|2.1.5
Angular2|joh|8.1.1
Angular-BeastCode|Mik|8.0.10
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
bitbucket-pull-requests|Ram|0.3.9
autoimport|ste|1.5.3
move-ts|str|1.11.5
vscode-icons|vsc|9.2.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch VSC with all extensions disabled? Or if that's not feasible, then with only the minimal essential set?

**Comment by itzvarman** [comment]
@gjsjohnmurray It's happening sometimes only. I disabled all plugins, Feel now it's fine. Any idea to find which plugin causes?

**Comment by IllusionMH** [comment]
Enabling that one-by-one and see if issue is reproducible.
Probably it make sense to start with extensions that provide formatting or other file changes automatically.
