### ISSUE TITLE
Redesign of a vertical scroll bar

### ISSUE THREAD

**Issue by hd321kbps** [microsoft/vscode#79485]
I propose to redesign the vertical scroll bar.
To reduce width, add volume and shadows.
Liked the option of Sublime Text.
![sublime-1](https://user-images.githubusercontent.com/9886849/63319278-31018b80-c322-11e9-9cc7-7b6a3016ec7b.jpg)

**Comment by RMacfarlane** [comment]
Not an exact duplicate, but there is an existing issue requesting scroll bar ui updates:
https://github.com/microsoft/vscode/issues/65352

Let's keep the conversation in that issue
