### ISSUE TITLE
In new versions, the `import` automation always fails in JS ES6+.

### ISSUE THREAD

**Issue by junlas** [microsoft/vscode#79486]
In new versions, the `import` automation always fails in JS ES6+. but the previous old versions is ok.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide exact steps that lead to a problem?
Does it happen if you trigger suggestion, that wait enough time to see details for suggestion and only then applying it? In this case it might be related to #73311

**Comment by junlas** [comment]
thank you for your response, now I'm using version 1.37.1, and the bug seems to have gone away again in the last two days, but I can be sure that it has been present in several previous versions, every time I create a new ES6 JS file, it always appears when I write code in it.

**Comment by junlas** [comment]
Hello, I'm back, this bug (JS auto import not work) appears again in the latest version 1.37.1, it is sometimes good and sometimes not clear. For example, here, I create a new ES6 JS file `InnerSectionAudio. Js`, I want to use it in another JS file, the bug appears, it always not automatically import this file.

<img width="1226" alt="err" src="https://user-images.githubusercontent.com/1894359/63647527-0ade5000-c755-11e9-9a42-fb0017bd985a.png">

**Comment by junlas** [comment]
> How are your imports managed? Have you created a jsconfig?

I don't know how to understand `imports managed` you mentioned. Isn't that what vscode comes with all the time? 

But I'm sure I have a jsconfig file.

BTW, when I have an `import` exception, I close all the tabs, and sometimes it works again.

<img width="736" alt="project" src="https://user-images.githubusercontent.com/1894359/63783648-f4382480-c91f-11e9-9033-ca3a8b641c67.png">

**Comment by junlas** [comment]
sorry, I can't share this project with you, but the chance of this bug reappearing is much lower in the current version 1.37.1.

I haven't tried to disable all extensions. I'm going to give it a try, and I'm going to give you a demo project to test some time.

I guess there are a few possible directions that might lead to reproducing this bug:
1. move a folder containing js files in the file system, and then go back to vscode to create a new ES6 js file, which may cause this bug;

2. open more than two vscode projects at the same time, and then create a new es6 js file, which may cause this bug;
<img width="329" alt="p0" src="https://user-images.githubusercontent.com/1894359/63841278-1a5bd400-c9b5-11e9-96fe-df3ddf2c87c2.png">

**Comment by mjbvz** [comment]
Closing this as it is not actionable without additional information.

Please try using [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled. Then if you still see the issue, share some additional information about your project type so we can investigate
