### ISSUE TITLE
1.37.1 Update not working.

### ISSUE THREAD

**Issue by joshya28** [microsoft/vscode#79482]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by joshya28** [comment]
Issue Type: <b>Bug</b>

VS code is asking me to install the latest version each time I open the editor. It keeps appearing even after installing the latest version(1.37.1).

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.1.6
php-autocomplete|bsc|0.4.2
jshint|dba|0.10.21
vscode-eslint|dba|1.9.0
vscode-html-css|ecm|0.2.0
mithril-emmet|Fal|0.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
add-to-globals|Min|1.0.1
mssql|ms-|1.6.0
team|ms-|1.149.2
java|red|0.47.0
phpcs|she|1.0.7
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
html-css-class-completion|Zig|1.19.0


</details>

**Comment by joaomoreno** [comment]
Can you fully uninstall and reinstall VS Code? Thank you.
