### ISSUE TITLE
autoAttachChildProcesses attaching to external threads

### ISSUE THREAD

**Issue by Azerothian** [microsoft/vscode#79483]
- VSCode Version: 1.38.0-insider
- OS Version: Ubuntu 18.04.3 LTS
- Dev Runtime: NodeJs v10.16.3

Steps to Reproduce:

1. configure two nodejs cluster based applications with multiple child threads and open them in two seperate instances of vscode.
2. create a launch debug profile configured with "autoAttachChildProcesses": true for both projects.
3. start both debug sessions sequentially
4. you will find that the first debug session will have attached to the second debug session child threads and also breakpoints that are set in one session are being hit in the alternate session.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@Azerothian how and where do you launch the nodejs cluster based applications?

**Comment by Azerothian** [comment]
two seperate vscode instances, using the vscode debugger

i have created a recording of the what i am seeing - https://imgur.com/a/Npo0edB

also here is my launch settings.
```
{
    "name": "Launch Node Debug",
    "type": "node",
    "request": "launch",
    "restart": false,
    "stopOnEntry": false,
    "args": ["build/start.js"],
    "cwd": "${workspaceRoot}",
    "console": "integratedTerminal",
    "sourceMaps": true,
    "outFiles": ["${workspaceRoot}/build/**/*.js"],
    "protocol": "inspector",
    "envFile": "${workspaceFolder}/.env",
	  "autoAttachChildProcesses": true,
    "windows": {
      "useWSL": false  
    },
    "skipFiles": [
      "<node_internals>/**/*.js"
    ]
  }
```

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/) that handles debugging children in a more relaible way. Please let us know if you're still running into problems, and if so open an issue on that repo.
