### ISSUE TITLE
System Blue Screen After return focus to VSCode window

### ISSUE THREAD

**Issue by gaodingpan** [microsoft/vscode#79481]
- VSCode Version: 1.37.1
- OS Version: Windows 10.0.18362

Steps to Reproduce: This issue happens occasionally

1. open WSL remote development.
2. Change focus to other applications such as chrome.
3. After sometime ,when you return focus to the VSCode, system break down and shows Blue Screen with message "Kernel Security Check Failure"

Does this issue occur when all extensions are disabled?: No

**Comment by RMacfarlane** [comment]
@deepak1556 Do you have any ideas about what would cause this, or what other info we could collect?

**Comment by gaodingpan** [comment]
Not really, but I think it might have to do with Symantec firewall and WSL being scanned too frequently when we try to compile/read files from WSL to windows. Actually, after updating windows' most up-to-date patch, the frequency of that has dropped to a neglegible rate.
