### ISSUE TITLE
File Content Miss-Match Issue

### ISSUE THREAD

**Issue by 1207dedun** [microsoft/vscode#79489]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

->While Opening Files with same name.  There is only one difference is that One File name starts with Small latter and Other one start with Capital Letters, then last opended file content will automatically copied into previous one file.
-> Assumed Both Files are at same path

For Example.
       File1 => 'Costing.pm'
       File2 => 'costing.pm'

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post version and platform information from Help\About or similar.
