### ISSUE TITLE
Project directory cannot be expanded

### ISSUE THREAD

**Issue by wyd2015** [microsoft/vscode#79480]
在同时管理多个项目的情况下，某些不经常展开的项目会出现无法展开的情况
![微信截图_20190820111132](https://user-images.githubusercontent.com/15035523/63314756-4cc55b80-c33b-11e9-8ce6-7ffca31a4770.png)

**Comment by RMacfarlane** [comment]
> In the case of managing multiple projects at the same time, some projects that are not frequently launched may fail to expand.

Just to confirm, the folder `yq_patrol_web` is not empty? Can you press `F1` and run `Developer: Toggle Developer Tools` and see if anything is printed in the console when this happens?

**Comment by wyd2015** [comment]
> > In the case of managing multiple projects at the same time, some projects that are not frequently launched may fail to expand.
> 
> Just to confirm, the folder `yq_patrol_web` is not empty? Can you press `F1` and run `Developer: Toggle Developer Tools` and see if anything is printed in the console when this happens?

the project `yq_patrol_web` is not empty. I tried to run `Developer: Toggle Developer Tools`, that is only a empty `div` tag. but when I remove this project and add it again, it expands well. This situation is sporadic...

**Comment by wyd2015** [comment]
> > In the case of managing multiple projects at the same time, some projects that are not frequently launched may fail to expand.
> 
> Just to confirm, the folder `yq_patrol_web` is not empty? Can you press `F1` and run `Developer: Toggle Developer Tools` and see if anything is printed in the console when this happens?

I know what happend. I removed that project folder to another path. if vscode can give me a tip about this, i would not push an issue any more. Thank you
