### ISSUE TITLE
"Ctrl + Space" does not work on Mac for intellisense

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode#79488]
Issue Type: <b>Bug</b>

"Ctrl + Space" does not work on Mac, could you help to share any solutions or share any more info?

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:51:23.899Z)
OS version: Darwin x64 17.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|-psn_0_266305|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.15.1-alpha
vscode-azurestorage|ms-|0.7.1
azure-account|ms-|0.8.4
azurerm-vscode-tools|msa|0.6.1-alphalangserv

</details>

**Comment by gjsjohnmurray** [comment]
Does Command(⌘)+Space work? If so, perhaps you have configured your Mac to swap the Control and Command keys. This is done in System Preferences, Keyboard, Modifier Keys...

**Comment by RMacfarlane** [comment]
Thanks @v-dantch, this looks like a regression in insiders.

**Comment by jrieken** [comment]
Works for me. 


re https://github.com/microsoft/vscode/issues/79488#issuecomment-523184542

@RMacfarlane Does that mean you can reproduce?

**Comment by RMacfarlane** [comment]
Oh, actually nevermind. What I had been doing was typing the beginning of something like "const" and waiting for suggestions to show up, pressing esc, and then trying to retrigger suggestions. Nothing shows up. But the same thing happens on stable.

**Comment by jrieken** [comment]
Ok. thanks for clarifying @v-dantch please provide repo steps, please try without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by v-dantch** [comment]
Thanks for you help. I tried again and this issue also reproduces. Please get the details from below:
Steps to Reproduce:
1. Disable all installed extensions.
2. Open a json file.
3. Try to add a function like below:
![image](https://user-images.githubusercontent.com/34729092/63586164-4e10b580-c5d3-11e9-83a7-0dbd78df0644.png)

Expect:
Display all matched functions.

Actual:
Nothing displays after pressing "Command + Space" on Mac.

**Comment by jrieken** [comment]
> Nothing displays after pressing "Command + Space" on Mac.

So, it is `Command` or `Ctrl` you are pressing?

**Comment by v-dantch** [comment]
"Command + Ctrl" on Mac.

**Comment by jrieken** [comment]
> "Command + Ctrl" on Mac.

sure about that?

**Comment by v-dantch** [comment]
Sorry for typo, it's "Command + Space" on Mac which we tried.

**Comment by jrieken** [comment]
The keybinding is not (and has never been) `Command+Space` (since that's bound by macOS Spotlight) but it is `Ctrl+Space` on all platforms.
