### ISSUE TITLE
Reopen and Unlock #50122

### ISSUE THREAD

**Issue by NickLarsenNZ** [microsoft/vscode#79494]
I realise: 🚨 The issue tracker is not for questions 🚨

But can someone please reopen https://github.com/Microsoft/vscode/issues/50122? A bot closed it, there is further input, and I'd like to be able to comment on that thread once it's unlocked again.

**Comment by RMacfarlane** [comment]
@NickLarsenNZ I reopened the issue. Also, it might be worth giving our exploration builds a try - these use a much newer version of our UI framework (Electron version 6.0.x). Let us know if you still see the problem there.

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by Tyriar** [comment]
I closed the old issue, please open a new one if you want us to look into it as that is very out of date. Additionally #50122 is likely some environment configuration issue which are very hard for us to diagnose/fix and probably needs investigation on your side.
