### ISSUE TITLE
Javascript Regex Lookbehind not working

### ISSUE THREAD

**Issue by msilberg** [microsoft/vscode#79495]
Issue Type: <b>Bug</b>

Unfortunately Vscode does not suppport Regex with neither negative nor positive lookbehinds (e.g. (?<=\.) ). It always marks it as incorrect.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 5.0.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2934)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (3.98GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
According to #70156 these aren't supported in PCRE2, which is what VSCode uses.

**Comment by IllusionMH** [comment]
@msilberg if you perform Find (in current file) than JS RegExp engine is used and it supports non-fixed length lookbehind.
However Find in Files uses ripgrep and its engine supports only fixed length lookbehind expression.

Adding better error message and hiding incorrect notification is tracked in #79109

/duplicate #79109
