### ISSUE TITLE
File > Close Editor with no open file, closes VS Code (crash?)

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#7949]
- VSCode Version:1.2.1-stable, 1.3.0-insiders
- OS Version:Windows 10

Steps to Reproduce:

1.Open a file 
2. File > Close Editor   - this closes the file
3. File > Close Editor   - this exits VS Code (same as File > Close Window)

Not sure if this is crash or just a regular exit.

**Comment by bpasero** [comment]
Yeah as designed. Last close closes the window. Has been like that from day 1.

**Comment by devrelm** [comment]
While this is as designed, I'm often frustrated when I hit cmd+w one time too many and close vscode altogether.

#15028 is a long-standing feature request that isn't really as succinct as this but that is at least still open, so I'll continue discussion there.
