### ISSUE TITLE
Linux: watcher can produce ENOSPC when too many handles open

### ISSUE THREAD

**Issue by srinath29** [Microsoft/vscode#7950]
- VSCode Version: 1.2
- OS Version: CentOS 7 running on VMPlayer 12

The error which I am getting is 

```
[srinath@osboxes ~]$ code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Error: watch /home/srinath/.config/Code/User ENOSPC
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1323:19)
    at Object.fs.watch (fs.js:1351:11)
    at r.e.registerWatchers (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:16692)
    at r.e (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:15951)
    at new r (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:8:19184)
    at v (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:15395)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:7:23640)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:7:24615)
    at t._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:7:23801)
```

I think while exiting suddenly (Because of sudden OS shutdown) it is unable to close some files or something.

```
```

**Comment by srinath29** [comment]
It got solved when followed this [SO](http://stackoverflow.com/a/17437601/2869667)

**Comment by dbaeumer** [comment]
@bpasero looks like a problem with the file system watcher under Linux.

**Comment by srinath29** [comment]
Yeah

**Comment by byroniac** [comment]
I'm about ready to give up on Visual Studio Code on Linux because of this. I run Insiders and keep it up to date on Ubuntu 16.04 and Windows 10 (both 64-bit). The only temporary fix I have found is to log out and log back in again. But what's weird is that, even after I do this, sometimes it will stop working. So I do the logout/login thing again.

**Comment by ifrantar** [comment]
We were having a similar issue on Mint and found [here](https://webpack.github.io/docs/troubleshooting.html) about the following command:

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

It solved the problem for us...

**Comment by pauldotknopf** [comment]
I'd like to add that I am experiencing this issue as well. My ```max_user_watches``` is set to ```524288```. My project does indeed have a very large directory (temp build stuff). I have excluded them in ```settings.json```.

```json
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "build/tmp/**/*": true,
        "build/downloads": true,
        "build/sstate-cache": true,
        "build/cache": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "build/tmp/**/*": true,
        "build/downloads": true,
        "build/sstate-cache": true,
        "build/cache": true
    }
}
```

I don't get an error in vscode, I get an error when running my build commands (openembedded bitbake). When I close vscode, the build commands continue normally.

I know other developers hate to hear this, but Atom works great with this directory. I can open all the files (excluding temp build dirs) and run my build commands, without issue.

There are very few remaining files, so I have to imagine that inotify handles are still being created for the hidden directories declared in ```settings.json```.

**Comment by joaomoreno** [comment]
I hit this by just opening Code pointing to our own sources. It's a pretty rough experience. I wonder if we can trap this better, and provide the user some guidance towards bumping up the system open file limit.

**Comment by bpasero** [comment]
I pushed changes to detect this case now (both for chokidar and nsfw):

![image](https://user-images.githubusercontent.com/900690/36036441-2a5e89e6-0dba-11e8-8412-8409ecf79e9e.png)

The link goes to: https://code.visualstudio.com/docs/setup/linux#_error-enospc

**Comment by bpasero** [comment]
**Verify**: for SINGLE folder and MULTI folder (different watchers used!).

Make sure your `fs.inotify.max_user_watches` is set to default (see https://code.visualstudio.com/docs/setup/linux#_error-enospc) and open the vscode workspace. You should get the warning and the console should not be spammed with errors.
