### ISSUE TITLE
defaultValue is not respected for nested configuration settings

### ISSUE THREAD

**Issue by jakopo87** [microsoft/vscode#79505]
- VSCode Version: 1.38.1-insiders / 1.37.0 (stable)
- OS Version: Windows 10 x64 18362.295

Steps to Reproduce:

1. Clone [this](https://github.com/jakopo87/vscode-nested-configuration-example)
2. Start debug.
3. Observe that the default value for `helloworld.test_package` is the same provided by `package.json` while `helloworld_nested.test_package` is undefined.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@jakopo87 You can only define defaults for top settings and not for nested.

**Comment by jakopo87** [comment]
@sandy081 It does work when you edit manually into the settings, and this is what confused me.
![vscode](https://user-images.githubusercontent.com/410331/63686643-b0033200-c802-11e9-82bc-c9ba15829dd4.gif)
However if this is the intended behavior it's fine, but I think it should mentioned in the docs at least.

**Comment by sandy081** [comment]
It is a feature of JSON language server and hence you see it while editing the JSON file.
