### ISSUE TITLE
Time span between two breakpoints

### ISSUE THREAD

**Issue by tredition** [microsoft/vscode#79504]
It would be very helpful if I could see the time span in milliseconds since the last breakpoint while I'm debugging (similar like in Visual Studio 2017).

Preferred steps:
I have two breakpoints in my code and I start debugging.
- Debugger stops at first breakpoint and shows the time in milliseconds since starting the application.
- F5 > Debugger stops at second breakpoint and shows the time since continuing from the first breakpoint.

**Comment by weinand** [comment]
@isidorn please investigate what VS does and how we could do something similar.

**Comment by isidorn** [comment]
This is a fair feature request. However it is not on our immediate plan, thus assigning to the backlog.
We could show something on hover if we decide to do this. As I would not make it very prominent.
I can look into VS (I currently do not have it installed). @tredition feel free to provide screenshots with an example.

**Comment by tredition** [comment]
> This is a fair feature request. However it is not on our immediate plan, thus assigning to the backlog.
> We could show something on hover if we decide to do this. As I would not make it very prominent.
> I can look into VS (I currently do not have it installed). @tredition feel free to provide screenshots with an example.

![TimeSpan](https://user-images.githubusercontent.com/50625823/63435872-f6821680-c427-11e9-8f07-da070b00856c.png)

See this example from VS2017 (red box). This is the time span between the two breakpoints. An "on hover" solution would be also okay.

**Comment by zmp2000** [comment]
This would help a lot to track performance of application and detecting problems!

**Comment by aurelien-m** [comment]
I agree! Would be really cool to have this :innocent:

**Comment by renefb** [comment]
This feature would be awesome! Pls VSCode team, think about it.

**Comment by inkandvijay** [comment]
would be a great feature to have. please include this feature,
