### ISSUE TITLE
No warning about deleting modified files in a Git workflow

### ISSUE THREAD

**Issue by jonbp** [microsoft/vscode#79500]
- VSCode Version: 1.37.1
- OS Version: macOS Mojave / Darwin x64 18.7.0

Steps to Reproduce:

1. In a Git workflow, make changes to an already committed file
2. Close the file then delete the modified file in explorer, VS Code will not throw a warning about deleting the modified file with uncommitted changes.
3. Changes made to the file are then lost

It could be the case that this is default functionality but it seems odd to me that VS Code wouldn't throw a confirmation about the detrimental effects this could have.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jonbp** [comment]
Apologies, think this i my fault. I have this in my `settings.json`

```json
"explorer.confirmDelete": false
```

I'll leave this open in case there is anything further to add but for now I'll change this back to true.

**Comment by joaomoreno** [comment]
Additionally, the file is place in the trash bin.
