### ISSUE TITLE
Sass import reference not working for .sass extension

### ISSUE THREAD

**Issue by soullivaneuh** [microsoft/vscode#79507]
- VSCode Version: 1.36.1
- OS Version: Linux 4.19

Steps to Reproduce:

1. Install bulma npm package on your local project folder
2. Create a `.scss` file witht the following:
```scss
@import "../node_modules/bulma/bulma";
```
3. Click on the import link: You will have an error trying to open a `.scss` file. But the file is bulma.**sass**.

And I suppose auto-completion from libraries files won't work either.

**Comment by octref** [comment]
There's no support for sass. VS Code's sass support only support scss. You can try one of the extensions: https://marketplace.visualstudio.com/search?term=sass&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by mkhy19** [comment]
Any solution for this issue?
