### ISSUE TITLE
Electron 6: Mocha JUnit Reporter hangs unit tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79514]
Disabled via https://github.com/microsoft/vscode/pull/75802/files#diff-bbf941f6bb5cf5154abf5ed7f515fde2R12 in `test/electron/index.js` because it turned out this was hanging the test from finishing.

//cc @joaomoreno

**Comment by joaomoreno** [comment]
We want this, since it's what gives us semantic test results in devops.

**Comment by bpasero** [comment]
@joaomoreno understood, does it require the mocha junit reporter as only reporter or do you know if it supports another one?

**Comment by joaomoreno** [comment]
It's the only one I tried, there might be others.

**Comment by MikeGJennings** [comment]
I'm seeing this as well.

**Comment by bpasero** [comment]
I think we now run with this for all tests given @lszomoru work, closing.
