### ISSUE TITLE
Images do not show updated when changed on disk

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#7951]
**New description @bpasero**
Depends on https://github.com/electron/electron/issues/6275

**Old**

- VSCode Version: 1.2.1-1.3.0 latest
- OS Version: windows(test) most likely all

1- Steps to Reproduce:

1. Open a folder with 5 or so large images in vscode
2. click between them quickly
3. vscode crashes

2- Steps to Reproduce:

1. Open a project in vscode
2. Enable tabs
3. Open some large files quickly and switch between them

**Comment by eByte23** [comment]
Will add further details later e.g. memory usage, dumps etc.. /cc @bpasero (If you want to track)

**Comment by bpasero** [comment]
@eByte23 how large are those images? can you attach the files you use?

**Comment by eByte23** [comment]
@bpasero I can't provide the images as the are client images probably copyrighted also.

But here are the sizes and types
![image](https://cloud.githubusercontent.com/assets/8544875/16256008/1a190ed4-3892-11e6-8271-b66e8a1cb53c.png)

**Comment by bpasero** [comment]
Thanks. And the files you open are all of the same file type and similar size?

**Comment by eByte23** [comment]
Just varying of all those types, it was happening switch between the biggest file in the list to others very quickly

**Comment by bpasero** [comment]
Since this has been like that since day one, and my proposed solution using a webview is rather large, I am moving this to July to investigate further.

**Comment by bpasero** [comment]
I pushed a workaround for now to not add a random number to the image URL when showing the image. This has the benefit of keeping the memory pressure low because we avoid loading the same image over and over. It has the downside that the image will not show any changes if it has been updated. I plan to add an explicit refresh action to the image viewer so that you can still force it to repaint.

**Comment by bpasero** [comment]
Marking as upstream due to https://github.com/electron/electron/issues/6275

**Comment by jaime-olivares** [comment]
In *gulp* there is a `watch` functionality for sensing changes in the source code for a given folder/glob (usually for recompiling). Can we use the same technique for updating the cached images?

**Comment by bpasero** [comment]
Verify: images changed outside are reloading in VS Code (both for when the image is active in a tab as well as if inactive and you make it active).

**Comment by sdemurjian** [comment]
this is still happening to me
