### ISSUE TITLE
Hang on rendering markup or markdown

### ISSUE THREAD

**Issue by adamstortz** [microsoft/vscode#79515]
Issue Type: <b>Bug</b>

Scenario 1: viewing extension information
1. Open Extensions View
2. Select any extension
3. The extension details page hangs indefinitely

Scenario 2: viewing markdown preview
1. Open a markdown file
2. Click 'Open Preview to the Side'
3. Preview tab hangs indefinitely

Scenario 3: launch liveshare session
1. Open Live Share View
2. Click 'Start collaboration session...'
3. Live Share Intro page hangs indefinitely

Things I have tried:
1. Updated to latest version
2. Disabling all extensions and reseting to factory settings
3. Completely removing vscode and all related files from my machine and reinstalling
4. Same steps in latest 'Insiders' build
    - Version: 1.38.0-insider
    - Commit: c8d44e24dd250d416475a10efe64e35c9e2c65b3
5. Opened Developer Tools and watch console - unfortunately there is no new output before it hangs

I have another MacBook Pro that doesn't have the same problem.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.9.0
vscode-peacock|joh|3.1.1
chat|kar|0.21.0
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
vsliveshare|ms-|1.0.721
vsliveshare-audio|ms-|0.1.64
vsliveshare-pack|ms-|0.3.3
debugger-for-chrome|msj|4.11.7
vscode-seedling-icon-theme|ras|0.4.0
vscode-yaml|red|0.4.1

</details>

**Comment by mjbvz** [comment]
Are you on a corporate proxy that could be blocking web requests?

**Comment by adamstortz** [comment]
@mjbvz Yes, I am

**Comment by mjbvz** [comment]
Does disabling it help?

**Comment by adamstortz** [comment]
No, it doesn't

**Comment by mjbvz** [comment]
Please provide more detail about your setup

**Comment by adamstortz** [comment]
I am not sure what detail would be helpful.  As stated in my original post, I have completely removed VS Code and all related files from my machine and reinstalled it.  Meaning I have an essentially vanilla install of VS code.

In [hang.log](https://github.com/microsoft/vscode/files/3525498/hang.log), I ran vscode with these switches:
`code --disable-extensions --verbose`

I manually inserted a line in the console (line 161) before previewing a markdown file.
The lines that follow (162-170) are the only output shown before it hangs.

**Comment by mjbvz** [comment]
Ok, try the following:

1. In VS Code, run the `Open Developer tools command`
1. This should open a chrome dev tools instance
1. Navigate to the network tab
1. Clear the existing requests
1. Now click on an extension in the extensions view to load its details

When I do this, I see:

![Screen Shot 2019-08-21 at 11 31 35 AM](https://user-images.githubusercontent.com/12821956/63458293-69c76080-c407-11e9-86ed-dab72f6b80da.png)

In your case, I suspect you will either see the requests not returning 200s or the content returned in the requests being invalid

**Comment by adamstortz** [comment]
This is what I see, note that the Manifest has a status 200 but time is 'Pending'.
So it looks like the request is getting a response, but vscode is crashing mid-stream:
<img width="791" alt="Screen Shot 2019-08-21 at 1 41 00 PM" src="https://user-images.githubusercontent.com/5168605/63459011-6e951000-c419-11e9-8603-0ca2668c7665.png">

**Comment by mjbvz** [comment]
Please share the details of the pending request

**Comment by adamstortz** [comment]
I don't know how to do that, because the entire app crashes.  Including the developer tools.

However, I tested it again and this time all the requests were completed.  So, I don't think it is network or content related.  I have tried many different extensions and also Markdown files.  and all have the same behavior.
<img width="2039" alt="Screen Shot 2019-08-21 at 2 02 45 PM" src="https://user-images.githubusercontent.com/5168605/63460635-7e622380-c41c-11e9-9795-cad701220600.png">

**Comment by annoying258** [comment]
>     2. Disabling all extensions

including the ones that come bundled with vs code and can't be removed? They are enabled by default in a vanilla install.


>  another MacBook Pro that doesn't have the same problem.

is it the exactly the same model with same hardware specs and same MacOS version? if it is, this might be a hardware issue. also, just check that it is not the 13-inch(non touchbar) one that need the battery replaced.

**Comment by adamstortz** [comment]
> including the ones that come bundled with vs code and can't be removed? They are enabled by default in a vanilla install.

I have run with `--disable-extensions`, will that do the disable the bundled extension?

> is it the exactly the same model with same hardware specs and same MacOS version? if it is, this might be a hardware issue. also, just check that it is not the 13-inch(non touchbar) one that need the battery replaced.

No, they are different versions of the same model (meaning one is a newer hardware revision than the other), running the same version/build of the OS and VSCode

> does using another extension for markdown previews help, say https://github.com/yzhang-gh/vscode-markdown/ ?

No, I do not have any extensions installed for markdown.

**Comment by mjbvz** [comment]
I'm closing this as we are not able to investigate this without being able to repo. It also does not look like anyone else is seeing this
