### ISSUE TITLE
Add an API for extensions to resolve variables in launch.json during resolveDebugConfiguration()

### ISSUE THREAD

**Issue by kejxu** [microsoft/vscode#79518]
our debugger extension is going to parse a configuration and propagate the debug requests to language-specific debugger extensions (`vscode-python`, `vscode-cpptools`). 

for example, for the following configuration
```json
{
    "name": "debug",
    "type": "newtype",
    "request": "launch",
    "target": "${file}"
},
```
the target `${file}` points to an XML file that contains the actual launch requests. We need to actually parse that file and generate debug requests to the other debuggers.

Since we need access to `vscode.debug.startDebugging()`, this needs to take place inside `vscode.DebugConfigurationProvider.resolveDebugConfiguration()` (not the debug adapter). For this reason, we need an API to resolve VS Code variables manually (inside the extension's context).

**Comment by rossimonique** [comment]
[__](`_**### url**_`)

**Comment by rossimonique** [comment]
[StartHere.pdf](https://github.com/microsoft/vscode/files/3660025/StartHere.pdf)
[emailSample1.pdf](https://github.com/microsoft/vscode/files/3660034/emailSample1.pdf)

**Comment by weinand** [comment]
We've introduced a new hook `resolveDebugConfigurationWithSubstitutedVariables" that receives the debug configuration with all variables resolved. See #87450.

**Comment by kejxu** [comment]
@seanyen
