### ISSUE TITLE
Syntax highlighter for INI files is flawed or at least incompatible with Python's idea of an INI

### ISSUE THREAD

**Issue by assarbad** [microsoft/vscode#79517]
Load an INI file that contains something like:

```
[DEFAULT]
option = value1; value2
```

... into VSCode and you will see that everything starting with a semi-colon will end up being colored as a comment.

I understand that a leading `;` causes a line to be a comment, but at least in terms of Python's idea of an INI file (see the [`configparser`](https://docs.python.org/3/library/configparser.html) module) [the documentation states](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure):

> Configuration files may include comments, prefixed by specific characters (`#` and `;` by default). Comments may appear on their own on an otherwise empty line, possibly indented.

On Wikipedia [we learn](https://en.wikipedia.org/w/index.php?title=INI_file&oldid=903631271#Comments):

> Semicolons (;) at the beginning of the line indicate a comment. Comment lines are ignored.
> 
>     ; comment text

... and further down:

> In some implementations, a comment may begin anywhere on a line, including on the same line after properties or section declarations. In others, including the WinAPI function `GetPrivateProfileString`, comments must occur on lines by themselves.

... suggesting that commonly comments must occur on lines by themselves, but that some implementations deviate from it.

So I suppose it would be desirable to make this behavior at the very least configurable.

Thank you and best regards,

Oliver

PS: I ran into this because I wrote a script in which lists are semi-colon separated ...

**Comment by alexr00** [comment]
This is already configurable; you can install an extension that provides a grammar then choose that grammar using the Change Language Mode command in that file.
