### ISSUE TITLE
Cursor runs ahead of the text that is being typed

### ISSUE THREAD

**Issue by panta82** [microsoft/vscode#79511]
Issue Type: <b>Bug</b>

Open a new blank file and paste this:
```
## Level 1

starthere
```
Then start typing after "starthere", in the same line. On my system, the cursor runs ahead of the text being typed.

See the gif:

![vscode_wtf](https://user-images.githubusercontent.com/4291324/63352951-45fe0f00-c362-11e9-8c01-a9acfd3210b8.gif)

Tried it on fresh install of the latest insider's edition, without extensions.

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:09.586Z)
OS version: Linux x64 4.9.0-9-amd64, XFCE on Debian 9.9

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (0.28GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexandrudima** [comment]
@panta82 Are you using any form of zoom? Or a high DPI monitor? Is the cursor drawn correctly when setting `"editor.disableMonospaceOptimizations": true` ?

**Comment by alexandrudima** [comment]
related - #77817

**Comment by panta82** [comment]
@alexandrudima I am not using zoom, I was able to repro it on stock insiders edition, without any additional settings.

It's a 2K monitor. I can't repro the issue on my home HD monitor, so that might be it.

I will post more info tomorrow, when I get back to work, where the monitor is.

**Comment by panta82** [comment]
I just remembered I was supposed to post more info here  :).

`"editor.disableMonospaceOptimizations": true` seems to solve the issue, but VSCode freezes after about a minute of playing around with this setting, and has to be killed by the system. 

My feeling is that some miscalculation happens after typing for awhile. With `disableMonospaceOptimizations`, the editor freezes. Without, the incorrect character measurement is introduced, which exhibits like shown above.

My display settings are on the screenshot.

![image](https://user-images.githubusercontent.com/4291324/63932120-d1f4f280-ca56-11e9-8f9b-a7cefcbb408a.png)

The bug is reproducible on either monitor.

**Comment by panta82** [comment]
Some more experimenting.

- It seems it doesn't matter which character I type.

- Everything seems fine at first, I can type multiple lines of characters without issues. But then I click around a bit, play with selection and then it happens. Afterwards, I can type anywhere, and characters will be incorrectly measured.

- If I open a new tab, and start typing, everything is fine in that tab (so the incorrect measurement is tied to a tab)

- I said above that `disableMonospaceOptimizations` causes editor to freeze. But now I managed to make it freeze without this setting at all, just by holding a single character for a while. Not sure if this is a separate issue or related.

**Comment by panta82** [comment]
I've installed version 1.28.2, which is the one my colleague uses successfully on a similar system. Both the freezing and misaligned cursor disappeared.

So the problem was introduced within the last 1 year.

**Comment by JacksonKearl** [comment]
@alexdima Given we're not likely to get a response within the next few hours, do you know any way to verify?

**Comment by alexdima** [comment]
I haven't been able to reproduce this myself, so the change was optimistic to begin with. Since nothing is broken, adding `verified`.

**Comment by panta82** [comment]
I just VNC-d to work computer and tested it. I was able to repro it again on the old stable version, and couldn't repro it on the latest insiders. So it seems to be fixed! :+1:
