### ISSUE TITLE
Progress Bart to notifications

### ISSUE THREAD

**Issue by LCostaN** [microsoft/vscode#79512]
I'm new, so I might have missed a previous issue about this. If so, forgive me.

So, I'd like to request a working progress bar for notifications on progress.
I have to restart virtual devices all the time and sometimes it gets stuck and never finishes the process, which surprisingly is not really that bothersome. What's a real bother is not knowing if it's actually stuck or not.

So I'd like to request for an option to see the actual progress when notifications show a process.

**Comment by RMacfarlane** [comment]
@LCostaN There is an existing API for extensions and VSCode to provide progress updates to notifications:

https://github.com/microsoft/vscode/blob/c5dc9d16be5cbd18b4a1bc44941ef8a1b16cf983/src/vs/vscode.d.ts#L6783

This depends the creator of the notification adopting the API - if the notification is coming from an extension, please file an issue on it. Thanks!
