### ISSUE TITLE
VSCode Can't find G++ in WSL2 

### ISSUE THREAD

**Issue by M-G-ARC** [microsoft/vscode#79527]
Issue Type: <b>Bug</b>

Getting the following message with C/C++ Configurations: Cannot find: C:\Users\matt\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\usr/bin/g++

However on WSL2:
                                                                                                                                     
matt@DESKTOP:/mnt/c/Users/matt$ which g++       
/usr/bin/g++

I've tried this on insiders and non-insiders VSCode, although am on Windows insider fast ring.

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:53.607Z)
OS version: Windows_NT x64 10.0.18963

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
project-manager|ale|10.6.0
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.30.1
gitlens|eam|9.9.3
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.141
python|ms-|2019.8.30787
remote-ssh-edit-nightly|ms-|2019.8.28260
remote-ssh-explorer-nightly|ms-|2019.8.28260
remote-ssh-nightly|ms-|2019.8.28260
remote-wsl|ms-|0.39.3
cpptools|ms-|0.25.0-insiders2
sublime-keybindings|ms-|4.0.3
veriloghdl|msh|1.0.3
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.4.1

</details>

**Comment by RMacfarlane** [comment]
@M-G-ARC Can you please reopen this issue on the C++ extension?
