### ISSUE TITLE
New pattern to Preserve Case ( hyphen separated variables)

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#79525]
A new pattern can we added to the preserve case ( the hyphen separated variables )
ALL upper Case and ALL Lower Case will work here and Title case will only replace the first character and not the first char after hyphen
The third example explained here https://github.com/microsoft/vscode/issues/9798#issuecomment-300153266

`Foo-Bar` replaced with `newfoo-newbar` with case preserved will be `Newfoo-newbar` and I would like to see that changed to `Newfoo-Newbar`
 ( Now that the replacing logic is generic to both search side and find side , It should work at both places )

FYI : @roblourens , @rebornix

**Comment by skprabhanjan** [comment]
Closed via #79528

**Comment by ArturoDent** [comment]
Is it intended that the cases of 

`foo_Bar`    on replace becomes  `blim_blam` should be  `blim_Balm`
`foo-Bar`    on replace becomes `blim-blam` should be `blim-Blam`

be preserved?  It does not appear that they are.  I don't know whether they are considered to be test cases.

Version: 1.39.0-insider (user setup)
Commit: de03947834d0bcf55093b97c292b76faa75cdebc
Date: 2019-09-23T08:25:10.478Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18985

**Comment by skprabhanjan** [comment]
@ArturoDent , Your point is valid and there is no implementation for the use case you mentioned.( Only `Foo-Bar` or `Foo_Bar` works currently)
If @roblourens gives a thumbs up for this , I will get it done :) 
Thanks for this !
