### ISSUE TITLE
Open Recent: Add one more button for "Add to workspace"

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79526]
![image](https://user-images.githubusercontent.com/4033249/63368381-a07f7700-c332-11e9-8a12-c630191dc67f.png)

Currently we only show a `x` for clearing input. I don't want to use system folder picker. Would be great if there's a button to add that folder to current workspace.

**Comment by misolori** [comment]
Not sure I think this is the best place for adding a folder to a workspace nor would I expect to add it from here as your intention is to switch folders/workspaces. We would also need to add it to the Welcome screen since this is a continuation of that. I'll bring it up at the next UX sync.

**Comment by octref** [comment]
Updated proposal: make an "Add recent folder to workspace" command that would show recent folders.
