### ISSUE TITLE
syntax highlighting wrong!

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#79520]
Issue Type: <b>Bug</b>

in the following C++ code:
```c++
int main(int argc, char* argv[])
{
    myFile myInput = myFile(argv[1]);
    myFile myOuput = myFile(argv[2]);
}
```

variable "myInput" is in cyan, but "myOuput" is in white. How could it be?

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:09.586Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (4.21GB free)|
|Process Argv|dio_extend_gather.cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.24.1

</details>

**Comment by sweettyler** [comment]
![screenshot](https://user-images.githubusercontent.com/49961658/63362725-ebe85400-c337-11e9-8195-8312ff296861.png)

**Comment by sweettyler** [comment]
same problem even with the latest ms-vscode.cpptools version 0.25.0-insiders2.

**Comment by alexr00** [comment]
The issue doesn't reproduce if you disable the C++ extension. Please file the issue on the C++ extension.
