### ISSUE TITLE
Python can not resolve import module time

### ISSUE THREAD

**Issue by Gr3Kidd3r** [microsoft/vscode#79522]
Issue Type: <b>Bug</b>

I start the VS code and start using it,
I put my machine to sleep (VS code is running),
I wake it up,
The python file can not resolve `import time`!

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 1938)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|11.62GB (1.17GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
enki-vscode-theme|enk|0.5.0
vsc-material-theme|Equ|30.0.0
python|ms-|2019.8.30787
gradle-language|nac|0.2.3
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1

(4 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Hey @Gr3Kidd3r, can you please reopen this issue on the python extension? https://github.com/Microsoft/vscode-python/issues
