### ISSUE TITLE
File Icons in Exporer occasionally incorrect

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#79535]
Issue Type: <b>Bug</b>

I believe this started with a recent insiders, but not sure. Cant repro on stable.

The icons assigned to files will occasionally no match the file's type. This also happens with directories being mis-identified as files. This happens with the default file icon packs, as well as external ones. 

The icon sometimes changes as files come in and out of view in the Explorer. (perhaps some virtualized list widget cache is being invalidated incorrectly?)

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:51:23.899Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.10.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
flow-for-vscode|flo|1.3.0
vscode-pull-request-github|Git|0.10.0
vscode-selection-flip|mle|0.1.1
python|ms-|2019.8.30787
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.721
debugger-for-chrome|msj|4.11.7
subtle-brackets|raf|3.0.0
colored-console-log|reh|1.0.7
code-settings-sync|Sha|3.4.1
mdx|sil|0.1.0
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.7.18
ayu|tea|0.18.0
polacode-fork|Tox|0.5.1
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
https://1drv.ms/u/s!Asa14RL-VZGjaqy25qyzhDr5CqA

**Comment by RMacfarlane** [comment]
Possibly a dup of https://github.com/microsoft/vscode/issues/79469

**Comment by isidorn** [comment]
Yeah this is a duplicate. Once we have a new insiders version you can let us know if you still see this and we can reopen.
