### ISSUE TITLE
Cntrl Alt Click on compile error does not work in specific circumstances

### ISSUE THREAD

**Issue by gilcolgate** [microsoft/vscode#79534]
Issue Type: <b>Bug</b>

Started happening only in the most recent version. You can control-alt click to go to errors in the source, but only sometimes. You cannot go to errors in the source if your terminal window has been scrolled up.

1) Compiile a C program in the integrated terminal.  
2) Get more than one page of errors
3)  Scroll up in your terminal to see an error that has gone off screen
4) Control Alt Click on the error. It will not work. Instead the terminal will scroll to show the last line.

What should happen:  In step 4 it should bring your cursor to the error in the file on the appropriate line and not scroll the terminal.

Note that if your window is showing the end , the control alt click will work. It will only fail when the window is scrolled.

Note I have several terminal tabs open, that might matter, I will check that too

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 4.15.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|31.37GB (8.40GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bazel-code|Dev|0.1.9
vscode-bazel|Baz|0.2.0
githistory|don|0.4.6
gitlens|eam|9.9.3
vscode-map-preview|jum|0.4.8
jumpprotobuf|ldc|0.0.3
rainbow-csv|mec|1.2.0
vscode-language-babel|mgm|0.0.23
vscode-mesh-viewer|mic|0.0.10
cpptools|ms-|0.25.0-insiders2
vscode-epics|nsd|0.0.8
java|red|0.47.0
vscode-yaml|red|0.4.1
blank-line-organizer|rin|0.1.5
trailing-spaces|sha|0.3.1
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
change-case|wma|1.0.0
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details>

**Comment by gilcolgate** [comment]
Note, it doesn't matter if you have one terminal or more. I checked that.

**Comment by Tyriar** [comment]
Update to 1.37.1

**Comment by gilcolgate** [comment]
1.37 fixed it thank you
