### ISSUE TITLE
Getting message "Linter flake8 is not installed," but it is

### ISSUE THREAD

**Issue by Steve-Z** [microsoft/vscode#79533]
Using VScode for MacOS 1.37.1. Intermittently getting notification message that flake8 is not installed but it is. Started with the last update I think. I contacted @code on Twitter who suggested I add this as a new issue.
![Notification 2019-08-20 at 9 40 04 AM](https://user-images.githubusercontent.com/31359112/63382394-40072e80-c360-11e9-85bf-b568f6d5c114.png)
![flake8 is installed 2019-08-20 at 9 42 04 AM](https://user-images.githubusercontent.com/31359112/63382400-43021f00-c360-11e9-9c89-6bb179e166bf.png)

**Comment by mjbvz** [comment]
Please file this issue against the python extension
