### ISSUE TITLE
Find Widget not adding space on top (`addExtraSpaceOnTop` setting) after first use.

### ISSUE THREAD

**Issue by GriceTurrble** [microsoft/vscode#79531]
- VSCode Version: 1.37.1
- OS Version: Windows 7 Enterprise (*I know, I know...*)

Steps to Reproduce:

1. Open a new editor window.
1. Add text to the first 3 lines of the editor, no more than 35 characters per line (short enough that the text does not touch the Find Widget box when it is opened).
1. Press **Ctrl-F** to open the Find Widget.
    * Initially, the `addExtraSpaceOnTop` setting should work as intended: scroll up to find extra space at the top of the file.
1. *Close* the Find Widget (either the **X** button in the UI or press the **Esc** key)
1. Press **Ctrl-F** again to open the Find Widget.
    * This time, no extra space will be added to the top of the file.
    * **This appears to be the failure point**: all steps below are tests to try to trigger it again, all of which appear to fail. From this point forward, the Find Widget seems "locked" and will not add extra space to the top of the editor window again.
1. Add more text to the first line in the editor, so that the line now falls under the Find Widget box. No new space is added to the top of the file to accommodate.
    * Closing and opening the Find Widget after this point will still not add extra space to the top of the editor.
    * Navigating to a different open editor will also not work.
    * Opening a new editor and typing a long line before opening Find Widget will still not work (no extra space added to top of editor).

The only way to make the setting work again is to reload the window, either using command "Developer: Reload Window" or closing the program.

---

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by GriceTurrble** [comment]
Adjusted title. Reproduction steps are the same, but it appears that no matter the line length used, the second time the Find Widget is opened, it will not add space to the top of the editor.

**Comment by rebornix** [comment]
It's already fixed in latest Insiders, thanks for your report!
