### ISSUE TITLE
Debugger Seetting variable in variables panel isnt working

### ISSUE THREAD

**Issue by xBiohazardx** [microsoft/vscode#79537]
Hello there,

I am trying to use VS-Code as an IDE to develop for my Blue Pill (STM32F103C8T6) development board. I already got "Make" working. I can flash it with the st-link tool and the program works fine.
I can also debug with the cortex debug extension (https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug).

And here is where my question kicks in. When the program is pausing at a breakpoint I can see all the local, global and static variables. If I double-click on one of them I can edit the value, but as soon as I hit Enter the edit panel vanishes and the value of the variable does not change.

I can change the value of the variable via the debug console, but i would like to do it over the gui.

Thank you for your help.   

- VSCode Version: 1.37.1
- OS Version: Windows 10 Version: 1903

**Comment by weinand** [comment]
Please file issue against cortex debug extension.
