### ISSUE TITLE
Code Helper uses lots of CPU when Integrated Terminal is open and have many NFS paths printed in the terminal 

### ISSUE THREAD

**Issue by yuqian90** [microsoft/vscode#79547]
My local macbook has many NFS drives mounted. Most of these NFS servers are in remote locations that are slow to access. Whenever I use the Integrated Terminal in vscode, Code Helper process uses a lot of CPU. vscode often hangs when I tried to open or save modified files. When this happens, dtruss shows that Code Helper is trying to stat64 many links in NFS directories. 

Since this slowness often happens when Integrated Terminal is open and the terminal has output that contains paths in NFS directories, I suspect it has something to do with Integrated Terminal trying to generate clickable links.

I'm filing this as a Bug report because it's odd to me Code Helper is using so much resources trying to do stat64 calls on paths printed in the terminal. It can also be a feature request because one way to solve this is to add a `"terminal.links": false` settings so that user can turn off this feature. 

- VSCode Version: 1.37.1
f06011ac164ae4dc8e753a3fe7f9549844d15e35
x64

- OS Version:
macOS Mojave Version 10.14.6 (18G87)
Steps to Reproduce:
1. Mount many NFS drives on the local machine
2. Monitor the system calls of Code Helper process with dtruss
```
$ sudo dtruss -f -n 'Code Helper'
```
3. Open vscode Integrated Terminal and print many paths in the terminal

Observe the CPU usage in Activity Monitor. Code Helper uses a lot of CPU. Also observe the number of stat64 calls in the dtruss output. Code Helper is doing a lot of such stat64 calls or lstat64 calls to all those NFS paths printed.

Does this issue occur when all extensions are disabled?: Yes

```
$ code --status
[67736:0821/121020.122219:WARNING:dns_config_service_posix.cc(181)] dns_config has unhandled options!
Version:          Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS Version:       Darwin x64 18.7.0
CPUs:             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
Memory (System):  32.00GB (0.20GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     enabled
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0      131   67129  code main
    0      164   67131     gpu-process
    0      328   67133     window (Settings — blah)
    0        0   67139       /bin/bash -l
    0        0   67288         tmux a -t bottom -d
    0      131   67142       extensionHost
    0      131   67191         /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python completion.py
    0       33   67196           /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python 3.7.4
    0       33   67586           /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python 3.7.4
    0       66   67143       watcherService
    0        0   67215       /bin/bash -l
    0        0   67218         /usr/local/Cellar/mosh/1.3.2_6/bin/mosh-client -# blah21 | 10.21.21.21 60013
    0       98   67157     shared-process
    0        0   67741       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (Settings — blah)
|    Folder (blah): 5169 files
|      File types: py(2201) pyc(1240) png(402) csv(123) ui(105) tmpl(92)
|                  conf(74) pl(69) txt(62) today(40)
|      Conf files: settings.json(1)

```

**Comment by gjsjohnmurray** [comment]
@Tyriar maybe the resolve call at https://github.com/microsoft/vscode/blob/5bf573ab9940725c09f5645766fb20406648d846/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L337
