### ISSUE TITLE
Context menu key in explorer doesn't show context menu

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79544]
Issue Type: <b>Bug</b>

Repro:

1. Click a file in the explorer
2. Press context menu key, notice the context menu shadow appears immediately then goes away, focus moves to somewhere else in the explorer

Might be needed:

```
"window.titleBarStyle": "native"
```

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:53.607Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3401)|
|Memory (System)|15.94GB (10.32GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
vscode-typescript-tslint-plugin|ms-|1.2.2
remote-ssh-edit-nightly|ms-|2019.8.28260
remote-ssh-explorer-nightly|ms-|2019.8.28260
remote-ssh-nightly|ms-|2019.8.28260
remote-wsl|ms-|0.39.3
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Noticeable only with `"window.titleBarStyle": "native"` and only in Explorer, Open editors, and Extensions lists (Enabled/Disabled).
Works fine in custom views (e.g. GitHub Pull Request)

**Comment by sbatten** [comment]
shift+f10 still works everywhere regardless, not sure what's special about file explorer's view.

**Comment by IllusionMH** [comment]
It "works" in Insiders builds (haven't checked since August).

Now context menu stays and can be uses with keyboard to select action, but it's triggered on item that is in the center of Explorer (vertical and horizontal).

**Comment by IllusionMH** [comment]
How this can be out of scope if with new behavior (triggers from the center of the list) it's possible to delete wrong file or folder?

**Comment by IllusionMH** [comment]
Forgot that this issue is about `"window.titleBarStyle": "native"`.
Created separate issue for `"window.titleBarStyle": "custom"` #109870 because context menu is shown but for wrong file/folder and it's easy to perform destructive action on wrong item.
