### ISSUE TITLE
Tree element not found error when creating nested folders in single root workspace

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#79540]
From https://github.com/microsoft/vscode/issues/78153#issuecomment-522271070

Steps to Reproduce:

1. Open single folder in vscode containing just one folder `FolderA`
2. Select  `FolderA`, create child folder `f`
3. Click New Folder Action and cancel
4. Click New Folder Action again, type `a/s/d` and accept
5. Click New Folder Action and cancel
6. Click New Folder Action again, type `q/w/e` and accept

![bugtreeexpandsinglefolder](https://user-images.githubusercontent.com/25115070/63221187-0913fb80-c15b-11e9-8ec0-c4d7b2f754c6.gif)

**Comment by isidorn** [comment]
Great catch and a wonderful fix, thanks a lot!
