### ISSUE TITLE
Anonymous tabs opening

### ISSUE THREAD

**Issue by sjhsoundar** [microsoft/vscode#79549]
Everytime I opened a file from ftp like winscp or filezilla 3 tabs is opening by default. Visual, Studio, Code these are the tabs with empty content. I disabled all extensions still getting the same. I am using windows 10 pc. Only in this pc I am getting these kind of problem.
![Screenshot (4)](https://user-images.githubusercontent.com/51694075/63408160-068bfd00-c40c-11e9-8696-03dd3a853e4a.png)

**Comment by gjsjohnmurray** [comment]
I guess a problem with config on that PC means the command that launches the VSCode executable (on Windows, code.exe) has specified three arguments on its command line:

`code.exe Visual Studio Code`
