### ISSUE TITLE
Hidden status bar still visible as a shadow

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79556]
1. Have the status bar hidden
2. Notice how the "shadow" of the status bar is still seen at the bottom of the sidebar

This is a regression in the previous couple of days, so I think it might be due to the new layout.
fyi @bpasero

![Screenshot 2019-08-21 at 10 37 38](https://user-images.githubusercontent.com/1926584/63416522-d8082500-c3ff-11e9-8273-7e6fbaaa66ee.png)

**Comment by sbatten** [comment]
I think this is a dupe. https://github.com/microsoft/vscode/issues/79280
I cannot repro on the latest, please try. If you can still reproduce, please reopen with additional steps.

**Comment by isidorn** [comment]
Yeah, looks better with latest. Thanks
