### ISSUE TITLE
Extensions viewlet: add some in-progress hint for update

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#7955]
- VSCode Version: 1.3.0-insider
- OS Version: Mac OSX

Steps to Reproduce:

1. Have an extension out of date
2. Navigate to Extension Viewlet, it shows a update button, click it. 

Expected: The update button switches to a install-in-progress image similar to what we have in command palette.
Actual: Nothing happens. We don't know whether it's updating or not.

**Comment by rebornix** [comment]
When we install new extensions in Extension Viewlet, the install button will be greyed out after clicking it. This can be another option.

**Comment by joaomoreno** [comment]
Thanks for the issue! Closing as duplicate of #7969
