### ISSUE TITLE
Python Extension is disabled

### ISSUE THREAD

**Issue by vincentthong** [microsoft/vscode#79555]
Issue Type: <b>Bug</b>

Suddenly the python extension is disabled. There is no option to turn it ON.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (17.59GB free)|
|Process Argv|D:\_project\VSCodeWorkSpace\SandBoxPLAST.code-workspace|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
python|ms-|2019.6.24221
cpptools|ms-|0.24.1
python|tht|0.2.3

</details>

**Comment by gjsjohnmurray** [comment]
@vincentthong any reason you are still on 1.32.3 and haven't upgraded to the current release, 1.37.1?
