### ISSUE TITLE
R colourising glitch with c() in function args

### ISSUE THREAD

**Issue by Hong-Revo** [microsoft/vscode#79559]
- VSCode Version: 1.37.1 (system)
- OS Version: Windows 10 Pro 1903

(Originally posted at [MikhailArkhipov/vscode-r/#25](https://github.com/MikhailArkhipov/vscode-r/issues/25) and [textmate/r.tmbundle#13](https://github.com/textmate/r.tmbundle/issues/13))

There seems to be a (rather specific) bug in how character vectors are coloured. When you have `c("a", "b", ...)` as a default function argument, the strings except for the first one are not treated as text:

![image](https://user-images.githubusercontent.com/11328890/63419106-8be0d300-c447-11e9-943c-9ccc12e542cf.png)

It only appears to happen when the `c` function is used; you can see that `list` doesn't have this problem. Similarly, if you have a character vector anywhere other than as a default function arg, it's coloured correctly.

Steps to reproduce

1. Type `f <- function(a=c("a", "b", "c")) {}` in an R editing window.
2. Note the colour of the strings.

As far as I can tell, this bug has actually been around for a few versions of VSCode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thanks for filing! Moved to the grammar's repo: https://github.com/Ikuyadeu/vscode-R/issues/120
