### ISSUE TITLE
Stale errors in Problems panel

### ISSUE THREAD

**Issue by tYYGH** [microsoft/vscode#79554]
- VSCode Version: 
- OS Version:

```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

Steps to Reproduce:

1. Work on a project with issues
2. Fix the issues
3 Issues still present in the Problems panel, even for files that were moved or deleted.

Does this issue occur when all extensions are disabled?: Yes/No

Hard to say because the problem is not systematic, and I have not yet identified the root cause.

Simply reloading the window (`[Ctrl]`+`[Shift]`+`P` >`Developer: Reload Window`), keeping the extensions, is enough to refresh (=flush, since there are no errors left) the Problems panel.

If I create new errors (I remove a dependency from `pom.xml` for my Java project), they are not sticky: when I restore a proper `pom.xml`, with all needed dependencies, the errors disappear.

I’ll give more information if I notice something relevant.

**Comment by gjsjohnmurray** [comment]
@tYYGH I think it is the responsibility of the extension to housekeep the Problem entries it created. See https://github.com/microsoft/vscode/issues/23010#issuecomment-288755175 for example.

Judging by what you wrote, you're coding in Java. Which extension(s) are you using?

**Comment by tYYGH** [comment]
Hi @gjsjohnmurray,
The list of extensions is rather long: Asciidoc, Bash IDE, Docker, EditorConfig for VS Code, French - Code Spell Checker, Git Graph, gitflow, GitLens - Git supercharged, Insert Unicode, Java Extension Pack, Liquibase Snippets, Maven for Java, NPM-Scripts, Spring Boot Extension Pack, Spring Boot Tools, SQLTools, tl;dr pages, Tomcat for Java, XML, + automatic dependencies.

**Comment by RMacfarlane** [comment]
@tYYGH My guess is that this is from this extension https://marketplace.visualstudio.com/items?itemName=redhat.java since it's the one you have installed as part of the Java Extension Pack that gives Java language support. Can you try disabling the Java Extension Pack to see if that's the extension that's contributing the problems, and if not, selectively disable until you do find the extension? Please reopen this issue on the extension.
