### ISSUE TITLE
Add bookmarks at symbols, not over line numbers

### ISSUE THREAD

**Issue by code4bones** [microsoft/vscode#79560]
Add a bookmark linked to specific symbol, like a link, becourse setting bookmark on line # after several changes on code, doesnt't point to initial line #

**Comment by gjsjohnmurray** [comment]
/causedByExtension AFAIK VSCode has no built-in support for bookmarks, so you must be using an extension. Please report your problem to the extension author.

**Comment by code4bones** [comment]
thanks
