### ISSUE TITLE
Automate exploration builds nightly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79569]
We are very close, however as it turns out the nightly exploration build seems to not run, unless a commit changes on the Electron branch. 

We probably need to automatically merge `master` somehow.

//cc @joaomoreno

**Comment by bpasero** [comment]
Done 🚀

**Comment by jtsom** [comment]
MacOS Exploration build not up to date ( Insiders dated 09-02-2019 )
<img width="414" alt="image" src="https://user-images.githubusercontent.com/13488/64171981-f4ee2080-ce21-11e9-81b2-dd7e4bbb41b5.png">

**Comment by bpasero** [comment]
Yeah, there is a test failure, reported as https://github.com/microsoft/vscode/issues/80251. Until we have that fixed, there will be no exploration builds. In other words, we only release green builds.

**Comment by jtsom** [comment]
Is there someplace to check to see if build are failing, when there is no update? (because no update today).

**Comment by bpasero** [comment]
Currently not. We are close to merging the exploration work to insiders though.
