### ISSUE TITLE
Cannot read property 'id' of undefined (shell.ts:411)

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#7956]
- VSCode Version:
![2016-06-22_09h43_45](https://cloud.githubusercontent.com/assets/3082812/16256902/d2031132-385d-11e6-8841-525a5f805a0b.png)

- OS Version: win 7

Steps to Reproduce:

1.

![2016-06-22_09h44_31](https://cloud.githubusercontent.com/assets/3082812/16256921/eea419f8-385d-11e6-93da-9505fed02aa0.png)

2.

![image](https://cloud.githubusercontent.com/assets/3082812/16256955/0ef9ff9c-385e-11e6-8881-5ab24fd492f4.png)

3.

![image](https://cloud.githubusercontent.com/assets/3082812/16256991/5b91c5ba-385e-11e6-9c2f-415af49090dc.png)

**Comment by dbaeumer** [comment]
@joaomoreno assigning to you since the new extension management code has properites metadata and id

**Comment by joaomoreno** [comment]
@IgorNovozhilov What is inside your extensions folder? Do you have any extensions installed at all?

**Comment by IgorNovozhilov** [comment]
this: https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint
and `npm install -g jshint` https://github.com/Microsoft/vscode-jshint/blob/7bbb7eaef8a5e862a8865e3234b229df8c0e500c/jshint-server/src/server.ts#L408

**Comment by IgorNovozhilov** [comment]
and it: https://marketplace.visualstudio.com/items?itemName=naumovs.theme-oceanicnext

**Comment by joaomoreno** [comment]
Any change you could zip up the entire folder and send me?

Do you get these errors right on Code startup?

**Comment by IgorNovozhilov** [comment]
Errors occur when opening the extension manager.
I reinstalled jshint. And updated the Code to version from 23.06.16.
After that, the error is not repeated.
![2016-06-23_08h29_07](https://cloud.githubusercontent.com/assets/3082812/16292711/b1e295a2-391c-11e6-884d-ebf3a3cf31cf.png)

**Comment by joaomoreno** [comment]
Thanks for the update.
