### ISSUE TITLE
Icon Accessability issue

### ISSUE THREAD

**Issue by qt1** [microsoft/vscode#79568]
The Problem:
Icons has been recently downgraded to a less accessible set of icons.

More details can be found in this discussion: #8017 

The new icons are less visible (by design) due to: smaller size, thinner, lack of color, lack of contrast, lack of visual divergence, outlined instead of filled, less definition (due to pixel interpolation)

In some situations this causes higher visual strain, eye fatigue and thus impairs accessibility.

From the  discussion in #8017 it is evident that this is related to company/barnding decision that has nothing to do with user comfort.

The long term product should be tested to keep same or better level of accessibility.

Possible solutions:

1. Add a **bold-icons** option so that icons can be displayed in a bold version
2. Add way to use the old set of icons or another, more visible, set of icons (or icon font)
3. Detach the icons to an addon and allow user control on the version

**Comment by nijikokun** [comment]
I've actually downgraded because of this, I **much prefer** the **filled in** icons. I don't know how long I'll have to wait to see filled in icons again...

**Comment by misolori** [comment]
@qt1 thanks for the feedback, your list of proposed solutions is covered under #79130 so I will be closing this as a duplicate.
