### ISSUE TITLE
Editor Blank Screen

### ISSUE THREAD

**Issue by einstein6012** [microsoft/vscode#79561]
Issue Type: <b>Bug</b>

Right Click on File Explorer -> Open in visual studio code insiders

Screen shows cutoff of vscode explorer but the remaining part of the screen is blank and does not show any editor

VS Code version: Code - Insiders 1.38.0-insider (c8d44e24dd250d416475a10efe64e35c9e2c65b3, 2019-08-19T12:53:53.607Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.75GB free)|
|Process Argv|C:\Users\mercu\OneDrive\Documents\Computer Programming 2\Assesments\Practical 3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-great-icons|emm|2.1.47
latex-workshop|Jam|8.0.4
python|ms-|2019.9.29519-dev
remote-wsl|ms-|0.39.3
octave|toa|0.0.3

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Tried with the same insiders build, but works on my machine™ (no mater if I already have VS Code open for other folder or all instances closed, if I open this folder first time or opened it earlier)

Could you please provide screenshot with a problem? Do you need to close all VS Code windows to reproduce this problem?
Do you have same problem if you disable all extensions?
Do you see any errors in DevTools?
/needsMoreInfo

**Comment by einstein6012** [comment]
It fixed itself with the latest update
