### ISSUE TITLE
waiting for the debugger to disconnect...

### ISSUE THREAD

**Issue by SambhavS004** [microsoft/vscode#79570]
Issue Type: <b>Bug</b>

Hello,

I am getting this error suddenly while debugging the JS/NodeJs code in VSCode in Nodejs environment. Though I cannot replicate this issue but certainly can say that it frequent and uncertain in nature. 
I am just running a file and suddenly get's this error. Tried restarting the system, VSCode, Stop Debugging options etc. Nothing worked!!
Node version is 9.8.0

Thanks
Sambhav

VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|14.93GB (7.93GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vue-peek|dar|1.0.2
vscode-eslint|dba|1.4.12
vscode-npm-source|dku|1.0.0
vscode-npm-script|eg2|0.3.7
prettier-vscode|esb|1.9.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
vscode-codemetrics|kis|1.19.1
node-module-intellisense|lei|1.5.0
vscode-azurefunctions|ms-|0.13.1
python|ms-|2018.7.1
azure-account|ms-|0.4.3
Go|ms-|0.11.4
vsliveshare|ms-|1.0.721
vsliveshare-audio|ms-|0.1.64
debugger-for-chrome|msj|4.11.7
vuejs-extension-pack|mub|1.1.2
vscode-for-node-js-development-pack|nod|1.4.0
vetur|oct|0.12.6
vscode-jest|Ort|3.0.2
vscode-docker|Pet|0.4.0
code-settings-sync|Sha|3.1.2
vscode-status-bar-format-toggle|tom|1.5.0
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by IllusionMH** [comment]
Do you mean "waiting for the debugger to disconnect..." in console?

AFAIK it's not an error, but indication of the fact that execution of Node program is finished (end of code or uncaught exception), but debug session is still active (because you haven't pressed Stop)

You can see same behavior if you use Chrome DevTools to debug node app:
```
node --inspect-brk script.js
```
and release breakpoint.

If you don't hit breakpoints - you should check if you have proper config in `launch.json`

/needsMoreInfo
