### ISSUE TITLE
Vscode error in Nativescript project

### ISSUE THREAD

**Issue by erjdriver** [microsoft/vscode#79576]
I'm using Nativescript and when a css file is opened with the following line

`background-image: url('res://hotels');`

I get the following error in vscode

`Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
    at /Users/mini/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:737585
 `

The `res` scheme is valid in Nativescript projects.

- VSCode Version:
- OS Version:

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
I don't see this anymore. Can you still reproduce?
