### ISSUE TITLE
Japanese GUI font-family

### ISSUE THREAD

**Issue by harujii** [microsoft/vscode#79579]
I suggest about Japanese GUI font-family. (not editor font family)

Current vscode specified "Meiryo" in Japanese font-family, but normally Windows 10 using "Yu Gothic UI" as Japanese system font.
We should add Yu Gothic UI to vscode font-family because Yu Gothic UI has a better character width and rendering than Meiryo.

#### Current (workbench.main.css)
```
.windows:lang(ja) {
    font-family: Segoe WPC, Segoe UI, Meiryo, sans-serif
}
```

#### Suggestion (workbench.main.css)
```
.windows:lang(ja) {
    font-family: Segoe WPC, Segoe UI, Yu Gothic UI, Meiryo, sans-serif
}
```

**Comment by dbaeumer** [comment]
@bpasero I think this is something set in the workbench.

**Comment by bpasero** [comment]
@harujii wanna do a PR for this change

**Comment by harujii** [comment]
@bpasero I Created PR #79735
