### ISSUE TITLE
Provide rich debugger support for pandas DataFrame

### ISSUE THREAD

**Issue by apryor6** [microsoft/vscode#79575]
I build lots of Flask APIs that internally use pandas DataFrames, and almost daily I find myself jumping into the debugger; however, there is not a particularly good way to inspect the contents of DataFrame. Ideally there would be a way to, perhaps, double-click or hover on a DataFrame variable and have a popup that shows the first few rows spreadsheet-style

The Spyder IDE has something like [what I describe](https://stackoverflow.com/questions/32438504/spyder-dataframe-editor-format)

Currently, I find I am limited to either:
- Calling `print(df.head())` from the debugger console. This is pretty clunky
- Writing the DataFrame to a file and re-importing into a Jupyter notebook, iPython, etc. This method introduces a class of problems in addition to the time inconvenience
- Inspecting the variable from the debugger Watch menu, but for an object as complex as a DataFrame this doesn't work as well. There is an implicitly structured context to a DataFrame that is not fully captured here.

I've felt for some time that this would be a great feature, but honestly I assumed there would be a large number of other data scientists sharing the same request and that it would magically appear. This is me conceding that point and doing what I should have already and making the request.

**Comment by ravishan16** [comment]
This is fantastic
