### ISSUE TITLE
PROBLEMS window showing '\' (backslash) while Remote Development

### ISSUE THREAD

**Issue by azenapow** [microsoft/vscode#79578]
I develop Linux application in Windows VSCode by Remote Development extension.

Some days ago, problems window showing backslash and does not work. (file opening)
File name does not show to me. only showing backslash.

![vscode_file_location_backslash](https://user-images.githubusercontent.com/16533954/63446675-9914b680-c475-11e9-961d-785de3c4e1f0.png)

![vscode_file_location_error](https://user-images.githubusercontent.com/16533954/63446691-9d40d400-c475-11e9-873a-88c681825d34.png)

It's no problems in VSCode stable version and no problem in previous insider versions.

Version: 1.38.0-insider (user setup)
Commit: ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8
Date: 2019-08-21T13:26:22.457Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "G++ COMPILER",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-lmysqlclient",
                "-pthread",
                "-Wreturn-type",
                "-Winline",
                "-Wunreachable-code",
                "-Wswitch-enum",
                "-Wfloat-equal",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "presentation": {
                "clear": true
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: No
Can't disable because I have to use gcc in Windows 10.

**Comment by aeschli** [comment]
The problemMatcher should run on the extension host so that the correct normalize is used. But the fix looks fine to me and I was able to verify.

**Comment by alexr00** [comment]
Opened an issue so I don't forget about it. https://github.com/microsoft/vscode-remote-release/issues/1331
