### ISSUE TITLE
bash.exe / zsh.exe on Windows should  `--login` arg defaultly.

### ISSUE THREAD

**Issue by Suyun514** [microsoft/vscode#79572]
- VSCode Version: 1.37.1
- OS Version: Windows 10 Pro 18362.295

Steps to Reproduce:

1. Change the default shell to Git Bash (`bash.exe`)
2. It seems that `--login` arg was not used. Because `/etc/profile` was not loaded.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Related https://github.com/microsoft/vscode/issues/77652

**Comment by Tyriar** [comment]
Closing this in favor of https://github.com/microsoft/vscode/issues/45444 and #77652
