### ISSUE TITLE
Quick Fix: Prepending unused TypeScript variables with underscore doesn't rename JSDoc @param

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#79574]
I'm not sure if this is a Visual Studio Code issue. I'm not even sure if the current behaviour may be by intention and correctly interpreted by JSDoc parsers:

Nonetheless, when Quick Fix solves the TypeScript linter warning: "unused function parameter" by prepending a parameter name with an underscore, it doesn't rename the corresponding JSDoc `parameter` reference accordingly:

![VS Code Underscore Rename Issue 1](https://user-images.githubusercontent.com/9283914/63437416-ce47e700-c42a-11e9-8118-fc98ce1bb8a0.png)
![VS Code Underscore Rename Issue 2](https://user-images.githubusercontent.com/9283914/63437422-cf791400-c42a-11e9-829d-c7cd0548a69f.png)

I suppose, it should, though.
<hr/>

- VSCode/OS Version:

```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.16299
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Can you please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new) that includes a small example

Closing as upstream
