### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by Shankar-Joshi** [microsoft/vscode#79573]
Whenever I try to run app from VS code, the app freezes after launching. However, when I try to run the same app from android studio, it runs smoothly. I love working on VS code but I have no idea why this is happening. Please help.

**Comment by RMacfarlane** [comment]
@Shankar-Joshi Can you provide some more information? What version of VSCode are you using, and what OS? What is the type of the app and what steps are you taking to run it? Are you able to share the code to it? Are you using any extensions?
