### ISSUE TITLE
CTRL click on other file named the same as already opened opens already opened file again

### ISSUE THREAD

**Issue by johi** [microsoft/vscode#79587]
I have a vue project with files src/api/goals.js (already opened) and src/store/modules/goals.js. Now when I CTRL and click on the second it opens the first in a split screen, not what I expected ;-) Of course the expected result is, that the other one, that  I clicked on is opened in the split.

**Comment by RMacfarlane** [comment]
Hey @johi, what version of VSCode are you seeing this on? Are you clicking on an import statement within a file, or a file in the sidebar, or somewhere else?

**Comment by johi** [comment]
Hey @RMacfarlane, I click on a file in the sidebar. Version is 1.37.1 :-)

**Comment by bpasero** [comment]
I cannot reproduce, but maybe this is an issue with the Explorer and selection/focus.

@johi please explain with a step by step description how to reproduce. assume we have no clue what you are doing.
