### ISSUE TITLE
Allow settings UI TOC to be resized

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#79581]
The TOC in settings is rather narrow, and frequently truncates extension names. This feels especially unnecessary when using a wider display.
![Screen Shot 2019-08-21 at 9 11 34 AM](https://user-images.githubusercontent.com/1166263/63448853-b9039600-c3f3-11e9-9333-446b8dbaa86e.png)

This is not only triggered by extension names, but also affects built-in settings in non-English languages:
![Screen Shot 2019-08-21 at 9 14 16 AM](https://user-images.githubusercontent.com/1166263/63449045-20b9e100-c3f4-11e9-92a3-07d1a52d9a99.png)

Ideas:
- Change the balance between the TOC and Settings Pane to give TOC more room
- Increase the max-width and allow both TOC and Settings Pane to grow proportionally.
- ...?

**Comment by gjsjohnmurray** [comment]
@dalongi  a probably-simple workaround might be to add the full name of the category as a hover tip for the truncated text.

**Comment by roblourens** [comment]
I don't really want to make things wider by default right now but a fancier UI would let you resize the TOC to your preference. I will add a tooltip now, should have had that already.

**Comment by dalongi** [comment]
@roblourens: Would additionally adding the resize UI be nontrivial? I'm not familiar with the UX framework being used, but could look into sending a PR if it's not too bad or there is an example to look at.

For changing the width: do you know how wide people typically have these panes? (Is it full window or partial due to having multiple editors?) When I have it open as the only window, I find it's easier to read the right-side setting descriptions when I shrink the window (~60-80 char per line instead of ~135 at max width)

**Comment by roblourens** [comment]
Yeah it would be nontrivial. I would think that people usually use this full-window but I don't have a good sense of the average window width.

**Comment by SiddhanthUnnithan** [comment]
+1 to this. Our team has two extensions "Azure Machine Learning" and "Azure Machine Learning - Remote" that show up in the TOC as:

![image](https://user-images.githubusercontent.com/6413608/113930928-be6b4b00-97a6-11eb-8355-d786447159c1.png)

Users have to click through each of those options to get to the right extension. We purposely added "Remote" as a suffix so that both the main and remote extensions would be grouped together, as the list is sorted alphabetically today.

Would it be possible for users to expand the column width so they can see the full extension name?

**Comment by dandavison** [comment]
When using a wider window size, I think it would make sense to use the plentiful horizontal space rather than truncate:

<table><tr><td><img width=800px src="https://user-images.githubusercontent.com/52205/134010474-c8b6650b-df62-4d13-8525-0c57c1edfb14.png" alt="image" /></td></tr></table>
