### ISSUE TITLE
Debugger: do not render expansion control on debug session when there are no children

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#79582]
Forked from https://github.com/microsoft/vscode/issues/79121.

As seen in the screenshot, session is expandable, yet has no children. Probably due to the elements' being identified as session, not thread.

![threads](https://user-images.githubusercontent.com/883973/63370329-cd358d80-c336-11e9-8e8c-57a5d5b04fe4.png)

@isidorn

**Comment by isidorn** [comment]
@pavelfeldman yes, good point. The issue was that the element is a session, and for sessions we were always rendering the expando. Now we are more strict and this case should work fine.
Try it out and let me know if it is good now.
