### ISSUE TITLE
Show CSS deprecated property with CompletionItem#deprecated

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79584]
Ref API: https://github.com/microsoft/vscode/issues/50972

![image](https://user-images.githubusercontent.com/4033249/63449562-34b21280-c3f5-11e9-8884-09b7e60f073e.png)

**Comment by octref** [comment]
@jrieken I have a [branch](https://github.com/microsoft/vscode-css-languageservice/tree/pine/deprecated) in CSS LS that does this. Will wait for the proposal in #23927 to finalize.

**Comment by jrieken** [comment]
:clap: looking already good. I agree that the UX needs some more tweaking. Maybe we can make dim deprecated items a little or change the style of strikeout

**Comment by dbaeumer** [comment]
@octref currently not: reason being is that in LSP land I only adapt API if it is release in a stable build. I am not depending on insider build version in the LSP library. So more official support has to wait until beginning of September.

**Comment by aeschli** [comment]
verified in
Version: 1.38.0-insider
Commit: eeab6fc371fcbfead7a1bd887c28f7efb28e5fcb
Date: 2019-08-28T05:34:09.557Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

**Comment by lazylazyllama** [comment]
It would be cool if we could also have this feature in the editor and not only in auto-complete.

So that "grid-gap" gets a yellow underline as a warning and maybe also a "quick fix" action?
