### ISSUE TITLE
Snippets are too slow

### ISSUE THREAD

**Issue by DominicTobias** [microsoft/vscode#79590]
- VSCode Version: all versions
- OS Version: all OS (tested Mac and Windows)

Steps to Reproduce:

1. Try a snippet
2. Observe it's very slow, you have to visibly wait even for longer shortcuts such as "log" unless you're a really slow typer

Note here how I have to wait until a menu comes up otherwise the shortcut is ignored:

![shortcuts](https://user-images.githubusercontent.com/760314/63453948-afa11a80-c441-11e9-8d61-f46cc0d689bd.gif)

This was instant on Sublime and has been bugging me for a long time, thanks!

Does this issue occur when all extensions are disabled?: yes

**Comment by jrieken** [comment]
Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by DominicTobias** [comment]
Thanks @jrieken, you're right it's the fault of an extension. I'll narrow down which one.

**Comment by DominicTobias** [comment]
Edit: weirdly just disabling and enabling the plugins (one by one as I was testing) fixed the issue
