### ISSUE TITLE
"Zap-to-char" or "delete to char" function/extension?

### ISSUE THREAD

**Issue by alanhoyle** [microsoft/vscode#79595]
Emacs and vi have similar features that let you delete everything up until a specific character.  Emacs has "zap-to-char" and vi has "dt".  They behave slightly differently, but either would be very useful.  

Imagine, for example, you have the following string, and the cursor is where the "|" is:

    Hello |death, goodbye cruel world!

In emacs, if you hit "meta-z" and then hit "l" it would delete everything between the cursor, and the first "l" character (inclusive), so the result would be this:  

    Hello | world!

in vi, if you were in command mode, you could type "dtw" which would mean "delete" "to" and then the character "w" which would stay.  

    Hello |death, goodbye cruel world!
    Hello |world!

My request is for something that mimics one of these behaviors.  

I.e. something like "alt-shift-z" then "w" to zap to the next "w" character.

**Comment by brightest-dazes** [comment]
Please don't do that God loves you

**Comment by alanhoyle** [comment]
I'm trying to delete the bad things more efficiently!  ;-)
