### ISSUE TITLE
in serverReadyAction, apply uriFormat regardless of whether 'pattern' matches a port or not

### ISSUE THREAD

**Issue by thomasrea0113** [microsoft/vscode#79596]
- VS Code Version: 1.37.1
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Create a Django (v 1.10 in my case) app
2. Debug using the VS Code python extension

First of all, this issue should be independent of my specific application. Below is the output of django runserver using the python debug plugin:

> cd /var/www/html/jtk/koyo-webapp ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /var/www/.virtualenvs/jtk-koyo-webapp/bin/python /home/reat/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 1753 /var/www/html/jtk/koyo-webapp/manage.py runserver localhost:9002 --noreload 
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> August 21, 2019 - 14:56:21
> Django version 1.10.4, using settings 'core.settings.local'
> Starting development server at http://localhost:9002/
> Quit the server with CONTROL-C.

Now I have the following launch config, which works as expected:

```
        {
            "name": "Django: runserver",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "localhost:9002",
                "--noreload"
            ],
            "django": true,
            "preLaunchTask": "supervisord",
            "serverReadyAction": {
                "action": "debugWithChrome",
                "pattern": "https?:\\/\\/\\S+:([0-9]+)\\/?\\nQuit the server with CONTROL-C\\.",
                "uriFormat": "http://localhost:%s/labs/1/forms/new/"
            }
        }
```

But if I try to do the following, chrome will simply launch to the first match in the 'pattern' regex, ignoring the uriFormat:

```
        {
            "name": "Django: runserver",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "args": [
                "runserver",
                "localhost:9002",
                "--noreload"
            ],
            "django": true,
            "preLaunchTask": "supervisord",
            //http://localhost:9002/labs/1/forms/new/
            "serverReadyAction": {
                "action": "debugWithChrome",
                "pattern": "(https?:\\/\\/\\S+:[0-9]+)\\/?\\nQuit the server with CONTROL-C\\.",
                "uriFormat": "%s/labs/1/forms/new/"
            }
        }
```

From this, I've gathered than uriFormat is ONLY used when the pattern matches a port, which is problematic when I change the binding host. This may be an intended feature, but it seems ridiculous to me that is it restricted in this manner.

**Comment by weinand** [comment]
Yes, the `uriFormat` is only used if the pattern matching captures only a port number. 
If the pattern matching captures anything else than a port number, it is used literally (without applying the `uriFormat`).

**Comment by TylerMizuyabu** [comment]
[The commit](https://github.com/microsoft/vscode/commit/f20785db318ebc6a931108c5c504028a75f8d581) that that was supposed to fix this seems  to have broken the uriFormat functionality. Unless it was intended to not allow a user to specify a uriFormat like ` "http://localhost:%s/swagger"`

It always uses the string constant `"http://localhost:%s"`. So when I try to pass in a format like `"http://localhost:%s/swagger"` it will instead open a tab to `http://localhost:<port-number>`.

**Comment by weinand** [comment]
@TylerMizuyabu I cannot reproduce the problem you are seeing in the latest Insiders:

<img width="835" alt="2019-10-03_08-57-16" src="https://user-images.githubusercontent.com/1898161/66105519-f4c97800-e5bb-11e9-94f7-6bcaacccf499.png">

Please provide detailed steps.

**Comment by TylerMizuyabu** [comment]
@weinand I created a .net core server and added swagger to it. Then made the following c# launch configuration
```json
"name": ".NET Core Launch (web)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/bin/Debug/netcoreapp2.2/Mock.Server.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "^\\s*Now listening on:\\s+(https?://\\S+)",
        "uriFormat": "http://localhost:%s/swagger"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
      }
    }
```
When I click on the start debugging button in my debug tab it builds and starts the server properly but instead of opening the new tab to `http://localhost:5000/swagger` it opens the tab to `http://localhost:5000`

This is the information for the vscode I am running this on
```
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by weinand** [comment]
@TylerMizuyabu your pattern `(https?://\\S+)` does not capture a port number but a full uri starting with "http". I do not see how this match result string could result in a valid uri if it is substituted  in the "http://localhost:%s/swagger" format string.
Make sure that the "pattern" captures only a port number.

**Comment by TylerMizuyabu** [comment]
@weinand I'll take note of that and update my pattern to just grab the port. 

That being said, it's not the solution to the problem with "uriFormat". The problem is that even if the "pattern" matches against something , the matched string doesn't seem to be used. So lets say it does match to the entire uri. I would expect it to then attempt to open a new tab with the uri `http://localhost:http://localhost:5000/swagger` (similar to what is shown in the example you posted above) . But instead it attempts to open a new tab to the uri `http://localhost:5000`. I achieved this behavior even after modifying my "serverReadyAction" to match the example you posted earlier (just without the commented out patterns).

```json
"serverReadyAction": {
        "action": "openExternally",
        "uriFormat": "http://localhost:%s/swagger"
}
```

**Comment by alexandrudima** [comment]
I have verified the OP reported issue works via the steps in https://github.com/microsoft/vscode-remote-release/issues/1115#issuecomment-538947067
