### ISSUE TITLE
Search Details is always expanded after launch despite collapsing it previously

### ISSUE THREAD

**Issue by renatoc8** [microsoft/vscode#79594]
- VSCode Version: 1.37.1 (system setup)
- OS Version: Windows_NT x64 10.0.18362 (Windows 10)

Steps to Reproduce:

1. Open the Search dialog by clicking on the magnifying glass or pressing Ctrl+Shift+F.
2. Press the Toggle Search Details button to collapse/hide the Search Details section.
3. Restart VSCode, and open the Search dialog again (the Search Details section will be expanded again despite being collapsed/hidden on the previous session).

Does this issue occur when all extensions are disabled?: Yes

Description:
When you open VSCode and open the Search dialog on the left of the window, all other search settings (such as the previous search term, whether Match Case or Match Whole Word were toggled on or off, and whether the Toggle Replace section expanded or not) will persist from your previous session. However, the Search Details section is always expanded after launching VSCode, even though I had collapsed it in a previous session.

![image](https://user-images.githubusercontent.com/2717549/63457066-1a803080-c405-11e9-9c21-aa913b916b5e.png)

**Comment by roblourens** [comment]
I swear I have seen this too but I can't reproduce it, and nothing has changed recently. Especially weird that you point out that other things are persisted properly. Do your steps reproduce it 100% of the time?

**Comment by renatoc8** [comment]
Ah, that makes sense. Is the "use excludes" setting turned on by default? It seems like it should be, but I'm not sure.

I don't recall switching that setting off on purpose, what's the default value?

**Comment by roblourens** [comment]
It should be on by default. I have had other people say that it seems to have gotten switched off on accident. That's why I try to make it obvious (like by keeping the details open) that it is off although I could probably do more.
