### ISSUE TITLE
Syntax Colorization for C/C++ standard library files has disappeared

### ISSUE THREAD

**Issue by NDelt** [microsoft/vscode#79591]
- VSCode Version: 1.37,1
- OS Version: 18362.295

Steps to Reproduce:

![Honeycam 2019-08-20 01-20-02](https://user-images.githubusercontent.com/46282492/63454360-a8036500-c485-11e9-8a0e-5a15b9f4a36f.gif)

- Compiler: Visual Studio 2019

Does this issue occur when all extensions are disabled?:
- If all extensions are disabled, `Go to definition` feature doesn't work.(Ctrl+click)

**Comment by RMacfarlane** [comment]
@NDelt How large is the standard library file you opened? We disable syntax highlighting for performance reasons if the file is larger than 20MB or if it has more than 300K lines

**Comment by NDelt** [comment]
@RMacfarlane I also tested with `<iostream>`, which has 60 lines of source code. The issue is same.

**Comment by alexr00** [comment]
I cannot reproduce in 1.37.1 or in insiders 1.38.0. My repro steps:
1. Have the C++ extension installed so I can go to definition in C++
2. Open I file that has `#include <iostream>`
3. `Go to definition` on iostream.
4. iostream is opened, and has correct C++ syntax highlighting.

@NDelt can you try disabling all other extensions? Can you also try running the `Change Language Mode` command and seeing what the configured language is for that file?

**Comment by NDelt** [comment]
@alexr00
1. Disabling all other extensions
2. Change language mode to C++
Both solutions don't change anything. Issue is same.

**Comment by alexr00** [comment]
@NDelt does the issue still occur if you disable the C++ extension?
