### ISSUE TITLE
CSS Language Server fails if client doesn't set `dataPaths` in InitializationOptions

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/vscode#79599]
- VSCode Version: 1.37.1
- OS Version: Fedora 30

I'm extracting the CSS Language Server for usage in 3rd party IDE (Eclipse IDE).
I noticed that if I start the CSS-LS without passing a `dataPaths` element to initialization, the LS will fail because of `TypeError: Cannot read property 'map' of undefined`.
One of the important lines in the stack trace is https://github.com/microsoft/vscode/blob/master/extensions/css-language-features/server/src/cssServerMain.ts#L107 .

**Comment by mickaelistria** [comment]
Submitted PR https://github.com/microsoft/vscode/pull/79600 for this issue.

**Comment by octref** [comment]
Fixed by #79600.

**Comment by mjbvz** [comment]
Verified in master by removing the dataPaths `initializationOptions`
