### ISSUE TITLE
Removing vscode python survey prompt

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#79592]
Python extension now has it's own survey prompt, so we would like to remove this. I've been trying to find the file where the survey is implemented, so I can submit a PR to remove it. Can you please point me to the implementation?

**Comment by sana-ajani** [comment]
Hi Karthik, we currently prompt users for this Python NPS survey: https://www.research.net/r/G7ZBPW7

I can replace this survey with another one or totally remove it. Btw, what is the new survey you are pointing to or what is the new criteria for showing it?

**Comment by karrtikr** [comment]
Hi Sana. We've already implemented the prompt as stated in the issue https://github.com/microsoft/vscode-python/issues/6752. 

We are randomly sampling 5% users making sure the same user is not prompted in 12 weeks again. Users sampled will be seeing the survey after 1 hour.

I am working on https://github.com/microsoft/vscode-python/issues/6957 right now, where I need to remove VSCode prompt.

![image](https://user-images.githubusercontent.com/13199757/63471629-858d2f80-c424-11e9-9a1c-63f25908a65a.png)

**Comment by sana-ajani** [comment]
Completed.
