### ISSUE TITLE
Having multiple files selected in Explorer and hitting enter only opens first selected file

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#79593]
Selecting multiple files in VS Code Explorer panel, having setting `"workbench.list.openMode"` set to `"doubleClick"` only opens the first of the selected files when hitting the <kbd>ENTER</kbd> key.
![VS Code multiple selection issue](https://user-images.githubusercontent.com/9283914/63456738-e2eaa600-c44f-11e9-87ba-212a5debfa15.png)

However, _all_ selected files are supposed to open in the current editor group.

- VSCode/OS Version:

```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Datum: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.14393
```

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/42573
