### ISSUE TITLE
Java Installer not detecting JDK 12.0.2

### ISSUE THREAD

**Issue by tamimmirza** [microsoft/vscode#79597]
- VSCode Version: 1.37.1
- OS Version: Windows 10 (1809)

Steps to Reproduce:

1. Run the installer and you get the following message:

![Annotation 2019-08-22 002244](https://user-images.githubusercontent.com/35456031/63461851-0410be00-c473-11e9-84d1-d92cc502d277.jpg)

Does this issue occur when all extensions are disabled?: No

**Comment by tamimmirza** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [how can replace extensions default jdk (#79260)](https://www.github.com/microsoft/vscode/issues/79260)

Sadly, the referenced issue is not near similar to what I have as I have not installed any Java extensions for VS Code prior to running the Java Installer. I only installed JDK 12.0.2 (64-bit) and tried to run the installer and got the above problem.

**Comment by mjbvz** [comment]
Please file this against the java extension
