### ISSUE TITLE
[ts] TypeScript function names are no longer colourised

### ISSUE THREAD

**Issue by xlexi** [Microsoft/vscode#796]
Since the new textmate based colourisation, function names are no longer colourised for TypeScript. This is clearly not intended as the same code that will be colourised in JavaScript will not be colourised in TypeScript.

**Comment by ucnc** [comment]
It will colorized in all themes except "Light"

**Comment by ucnc** [comment]
It will colorize in all themes except "Light"

**Comment by aeschli** [comment]
@xlexi  Can you give more information, maybe a screenshot.
What color theme are you using?
Do you mean function declarations or references?

**Comment by ucnc** [comment]
Try "Light" theme, it's only theme that not colorizing function names (including C#).

**Comment by xlexi** [comment]
Appologies, I meant the function name in function calls. Here is an example showing setTimeout using the default "Dark" theme in TypeScript (Left) and JavaScript (Right)
![screenshot](http://i.imgur.com/vQJO749.png)

**Comment by aeschli** [comment]
Fixed function calls in in light and dark themes.
Note that they are now black resp. white as they used to be. The color was not intended. The light and dark theme only use a reduced number of colors and themes.
