### ISSUE TITLE
Include path not passed to clang compiler

### ISSUE THREAD

**Issue by robinbudd** [microsoft/vscode#79606]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by RMacfarlane** [comment]
/needsMoreInfo Please include what version of VSCode you're using, and steps to reproduce the problem

**Comment by robinbudd** [comment]
VSCode Version: 1.37.1
    OS Version: macOS 10.14.6

Steps to Reproduce:
Configure VSC to use clang++ compiler on MacOS
Include a header file from a different directory from the project, and not one of the standard c++ paths
Add the path to the directory to "includePath" in c_cpp_properties.json
Confirm that VS Code knows how to find the include file by right-clicking the "include <filename>" statement and selecting "peek". It shows the include file contents.
Now try to build the file. Get "<filename.h> not found". Looking at the clang++ command line that vscode uses to compile the file, there is no include path passed in:
clang++ -std=c++17 -stdlib=libc++ ParseCC.cpp -o ParseCC.out --debug
So clang++ doesn't find the file. Seems like VSCode should construct the compile command with the include path.

Does this issue occur when all extensions are disabled?: It relies on the clang++ extension, so this is a silly question.

**Comment by RMacfarlane** [comment]
Thanks @robinbudd for the info! Since this behavior is from the c++ extension, can you please reopen the issue on that extension instead of VSCode? I believe here: https://github.com/Microsoft/vscode-cpptools/issues

**Comment by robinbudd** [comment]
Thanks RM will do
