### ISSUE TITLE
With tabs enabled, cannot view the active tab's file path without using mouse

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7960]
It seems this is very cumbersome to do:

- Copy path to active file command and paste somewhere
- Open in file viewer and look at the OS explorer

**Comment by bpasero** [comment]
@Tyriar how do ST, VS, Sublime solve this?

**Comment by Tyriar** [comment]
Not sure, haven't used them in quite a while.

**Comment by bpasero** [comment]
They show a hover on the tab, same as we do.

**Comment by Tyriar** [comment]
Is this something we can improve upon? Atom puts it in the status bar for example.

**Comment by wmertens** [comment]
As a corollary to this problem, if the file in the tab is `index.js(x)`, the tab should have the name of the parent directory, since `index` has almost no information.

**Comment by Treri** [comment]
Sublime will only show file path in tabs if we opened two files have the same file name.
Sublime added file path after the file name like below

![image](https://cloud.githubusercontent.com/assets/2631733/17428795/a75193d6-5b1d-11e6-9c24-23a80038b742.png)

**Comment by wmertens** [comment]
IMHO, the path can always be shown for `index.*` files, and the path can go
first, with the index on a second line or smaller, so that there is more
path visible in narrow tab heads…

**Comment by monkeysecurity** [comment]
PyCharm mirrors Sublime's functionality

![screenshot 2016-08-09 10 07 47](https://cloud.githubusercontent.com/assets/8009126/17525782/29c120e0-5e19-11e6-922f-a7d3e054b2cc.png)

**Comment by wmertens** [comment]
Maybe this can be generalized to show more of the path for all tabs that
have the same title. I really like having the path in front, it's the most
important piece of information.
