### ISSUE TITLE
plantuml does not show up in preview in md file

### ISSUE THREAD

**Issue by nwadhera** [microsoft/vscode#79602]
Issue Type: <b>Bug</b>

1. Install plantuml extension
2. write markdown with plantuml
3. Preview works
4. Next day does not work 

tried 
restart
reload
uninstall/reinstall extension

plantuml install on the system works with alt d to show preview

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.11.2
markdown-pdf|yza|1.2.0

</details>

**Comment by RMacfarlane** [comment]
@nwadhera Do you remember if you updated VSCode between when the extension worked and did not work?

**Comment by nwadhera** [comment]
Yes I think there was an update pending.

How can I revert that?

Thanks

**Comment by mjbvz** [comment]
Please file this issue against the plantuml extension
