### ISSUE TITLE
New window with no selected panel item

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#79605]
I keep getting a panel open with no selected tab:

![image](https://user-images.githubusercontent.com/323878/63476502-f9840380-c435-11e9-8e4c-36da21603c11.png)

I can't figure out why this is happening, it must be related to which panel I had focused the last time the window was open. But I have seen it many times in the past couple days. Is this related to grid stuff and how can I get more info?

**Comment by sbatten** [comment]
@roblourens anything in dev console? can you try testing with grid layout disabled for a bit if it reproes very consistently

**Comment by roblourens** [comment]
I'm pretty sure there were no errors anywhere. It doesn't repro that consistently but I can disable grid layout to see whether it shows up.
