### ISSUE TITLE
Issue running tests in linux build environment due to libdbus

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#79603]
1. Copy the Dockerfile and xvfb.init files for the linux build agent to the root of local copy of VSCode
2. Run the `Reopen folder in container` command on VSCode and select the option to use the existing Dockerfile
3. Install node with `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -` and then `apt-get install -y nodejs`
4. Install yarn with
```
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```
5. Clean and rebuild with `yarn` and `yarn run compile`
6. Try to run tests with `./scripts/test.sh`

The following is output:
```
root@b0d539dc25f0:/workspaces/vscode# ./scripts/test.sh 
.build/electron/code-oss: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by .build/electron/code-oss)
/workspaces/vscode/.build/electron/code-oss: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /workspaces/vscode/.build/electron/code-oss)
```

**Comment by RMacfarlane** [comment]
Hmm, actually, I'm wondering if there's some other issue I'm running into. I'm now looking at the build logs for linux, and they also print the error about `libdbus`, but then somehow continue

**Comment by deepak1556** [comment]
@RMacfarlane you can ignore the `libdbus` warning, its a long standing issue for the package shipped , check https://bugs.chromium.org/p/chromium/issues/detail?id=783468 for more context. As for the application not launching

Have you set ` export DISPLAY=:10` ? Since xvfb uses that display port from the config.

**Comment by deepak1556** [comment]
@bpasero I tried

```
diff --git a/test/electron/renderer.html b/test/electron/renderer.html
index a2d4bcc..a153cce 100644
--- a/test/electron/renderer.html
+++ b/test/electron/renderer.html
@@ -11,22 +11,11 @@
        <script src="../../node_modules/mocha/mocha.js"></script>
 
        <script>
-
-               // !!! DO NOT CHANGE !!!
-               // Our unit tests may run in environments without
-               // display (e.g. from builds) and tests may by
-               // accident bring up native dialogs or even open
-               // windows. This we cannot allow as it may crash
-               // the test run.
-               // !!! DO NOT CHANGE !!!
-               window.open = function () {return null;};
-               window.alert = function () {}
-               window.confirm = function () {}
-
                mocha.setup({
                        ui: 'tdd',
                        timeout: 5000
                });
+               window.open('https://google.com')
                require('./renderer');
        </script>
 </body>
```

but didn't see the crash, can you share the repro case ?

**Comment by bpasero** [comment]
@deepak1556 try with this commit: `df0dd2edc279af12fdf6140bb4362231fa8dc8a3`

**Comment by deepak1556** [comment]
Don't remember what crash we were trying to solve here, thoughts ?

Closing the issue based on @RMacfarlane original post which has been answered.
