### ISSUE TITLE
Cannot Connect To The Extentions marketplace 

### ISSUE THREAD

**Issue by hosbied** [microsoft/vscode#79604]
Issue Type: <b>Bug</b>

Hello,vscode team
i couldn't install any extention or access to marketplace .
And it  gives me this  message **<"we cannot connect to the extentions marketplace at this time , please try again later.">**

_This happened  after new update._

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

Extensions: none

**Comment by sandy081** [comment]
Can you please check if you are able to access marketplace? Also do you have any proxy settings?

Can you please open the network tab in developer tools and see if there are any errors accessing marketplace?

**Comment by hosbied** [comment]
No i can't access to marketplace , i stopped all proxy settings in my pc .
The Problem Still work .

**Comment by sandy081** [comment]
Do you have any DNS issues?

Can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/
