### ISSUE TITLE
Leaving Zen Mode disables line number 

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#79608]
- VSCode Version: 
1.38.0-insider
ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8
x64
- OS Version:
Microsoft Windows [Version 10.0.18956.1000]

### Steps to Reproduce:
1. Open VSCode and check that you can see line numbers in the gutter.
2. Enter Zen Mode (using keyboard shortcut)
3. Leave Zen Mode (using keyboard shortcut)

Lines numbers are no longer visible.

**Comment by MJ-Mohith** [comment]
I have opened up the PR with the issue and the fix evidence.
https://github.com/microsoft/vscode/pull/79622

**Comment by isidorn** [comment]
@bruno-brant good catch, thanks for reporting this and for using insiders.
You can try out VS Code insiders from Friday and let us know if this is now fixed for you. Thanks

**Comment by bruno-brant** [comment]
@isidorn seems fixed! I'm really glad to help!

**Comment by isidorn** [comment]
Great, adding verified label
