### ISSUE TITLE
Cannot use DejaVu Sans Mono in recent vscode update

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#79613]
```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
OS: Mac 10.14.6 (18G87)
```

I do not know why. It gives a popup saying that a monospaced font must be used for terminal and uses a very poor monospaced font instead. That found I selected is monospaced and should work.

**Comment by Tyriar** [comment]
Can you link to where you downloaded the font so I can try repro?

**Comment by graph** [comment]
Sorry my bad. I didn't have it installed. Some editors I use such as LibreOffice seam to have dejavu sans mono available even though it's not installed globally so I thought I had it installed.
