### ISSUE TITLE
importing python modules doesn't work

### ISSUE THREAD

**Issue by tcarroll2** [microsoft/vscode#79612]
Issue Type: <b>Bug</b>

1 - I use pip3 from the terminal console within VSC to install a python library
2 - I type import <library name> into the python file

Visual Studio Code fails to recognize it.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
python|ms-|2019.8.30787

</details>

**Comment by RMacfarlane** [comment]
@tcarroll2 Please report this on the python extension: https://github.com/Microsoft/vscode-python
