### ISSUE TITLE
vscode server for armhf linux not available after update

### ISSUE THREAD

**Issue by tjohnsonhvac** [microsoft/vscode#79610]
Issue Type: <b>Bug</b>

After the update today, I went to remote connect to armhf device. remote locks up on the wget command. I did some snooping in the .vscode-server-insider dir to get the hash dir name and tar name. I tried to manualy download from update site, but it shows not available. Are the server files not updated at the same time as the desktop version?

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.62GB (1.55GB free)|
|Process Argv|--open-url -- vscode:extension/Shan.code-settings-sync|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.5
remote-ssh-edit|ms-|0.45.5
remote-ssh-explorer|ms-|0.45.5
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.25.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.2.0

</details>

**Comment by RMacfarlane** [comment]
They should be updated at the same time. This is for VSCode insiders on commit ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8?

**Comment by tjohnsonhvac** [comment]
from the terminal:
```
root@localhost's password:
Running remote connection script
Acquiring lock on /root/.vscode-server-insiders/bin/ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8/vscode-remote-lock.ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8
Installing to /root/.vscode-server-insiders/bin/ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8...
Downloading with wget
```

![image](https://user-images.githubusercontent.com/36667609/63516588-38a86800-c4bb-11e9-87bc-e8e774bd84ac.png)

This is what it tries to download:
![image](https://user-images.githubusercontent.com/36667609/63516678-6db4ba80-c4bb-11e9-9a11-1eb115c728c0.png)

I tried navigating to:
https://update.code.visualstudio.com/commit:ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8/vscode-server-linux-armhf/insider
based on the file names it created while trying to download.

It just says "not found"

**Comment by tjohnsonhvac** [comment]
Issue fixed with latest insider update. Thank you.
