### ISSUE TITLE
weex new project 无反应

### ISSUE THREAD

**Issue by shanDeNaBianHaiDeNaBian** [microsoft/vscode#79617]
Issue Type: <b>Bug</b>

weex new project，无响应

Extension version: 0.1.7
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using any extensions for this purpose? Most likely you should report this problem in extension repo: https://github.com/weex-cli/vscode-weex
