### ISSUE TITLE
Windows Error Install Message: "The System Cannot Find The File Specified"

### ISSUE THREAD

**Issue by XxLJcool25xX** [microsoft/vscode#79611]
Issue Type: Error Installation
- VSCode Version: User Installer 64 bit & 32 bit 
- OS Version: Windows 7

Steps to Reproduce:
1. Must Be On Windows 7
2. Go To: https://code.visualstudio.com/insiders/ > User Installer > 64 Bit Or 32 Bit
![Capture1](https://user-images.githubusercontent.com/54383469/63479982-0b20d780-c445-11e9-994e-c54437fb85ab.PNG)

Does this issue occur when all extensions are disabled?: No (Unknown)\
So Idk What To Do.

**Comment by joaomoreno** [comment]
Not sure what that means. Please use the ZIP release as a workaround.
