### ISSUE TITLE
Stopping due to Debug session failure: fatal error: NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by gummoni** [microsoft/vscode#79619]
Issue Type: <b>Bug</b>

push F5

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
githistory|don|0.4.6
gitlens|eam|9.9.3
git-project-manager|fel|1.7.1
cortex-debug|mar|0.3.1
vscode-clang|mit|0.2.3
vscode-language-pack-ja|MS-|1.37.5
remote-wsl|ms-|0.39.2
cpptools|ms-|0.25.0
csharp|ms-|1.21.0
quicktype|qui|12.0.46
debug|web|0.23.1
linkerscript|Zix|1.0.0

</details>

**Comment by gummoni** [comment]
This problem is extensions C/C++ IntelliSense, debugging, and code browsing. version 0.25.0.
There is no problem in version 0.24.1.

**Comment by RMacfarlane** [comment]
Hi @gummoni, since this a problem with the C++ extension, can you please reopen this issue there? https://github.com/Microsoft/vscode-cpptools
