### ISSUE TITLE
search in folders explorer is difficult to discover

### ISSUE THREAD

**Issue by Mah3** [microsoft/vscode#79626]
It would be very helpful if we could see search box to search or filter folders explorer (similar like in Visual Studio [ctrl+;] ).

![image2](https://user-images.githubusercontent.com/18313590/63499950-98117280-c4d1-11e9-940a-de8ada25c0e4.png)

**Comment by IllusionMH** [comment]
@Mah3 you can just start typing while Explorer is in focus. This will enable highlight mode and you would be able to quickly navigate between items with matches. Also it supports filtering so you'll see only highlighted items.

One limitation - you have to have folders expanded to highlight/filter their content.

https://code.visualstudio.com/updates/v1_31#_new-tree-widget

**Comment by Mah3** [comment]
> @Mah3 you can just start typing while Explorer is in focus. This will enable highlight mode and you would be able to quickly navigate between items with matches. Also it supports filtering so you'll see only highlighted items.
> 
> One limitation - you have to have folders expanded to highlight/filter their content (improving this is tracked in #66971).
> 
> https://code.visualstudio.com/updates/v1_31#_new-tree-widget

It is nice feature , I didn't know, and I think it is very difficult to discover as @RMacfarlane changed my issue title **(many thanks by the way)**, and also I couldn't use copy paste , I think visual studio user experience in this feature is much great.

**Comment by joaomoreno** [comment]
It's a good idea for discoverability but also takes up more space. I think it's fine for now, if more people complain about not knowing how to filter, we'll rethink the design.
