### ISSUE TITLE
Can not configure file association in remote windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [microsoft/vscode#79628]
Issue Type: <b>Bug</b>

1. Open a project in WSL
2. Create a file that ends with `.cjs`
3. Click on Editor Language ("Plain Text")
4. Select "Configure File Association for '.cjs'..."
5. You will get the following error message:

> [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character

Seen both in vscode 1.36.1 and vscode-insider 1.37.0-insiders.

**Remote - WSL** Extension version: 0.39.0
VS Code version: Code - Insiders 1.37.0-insider (628bdedf671d3230fc76982fae845875a6f6c0da, 2019-07-19T10:33:04.702Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.42GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/dotnet/projects/utils --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2301)|
|Memory (System)|3.92GB (0.42GB free)|
|VM|0%|
</details>

**Comment by aeschli** [comment]
The problem is from
https://github.com/microsoft/vscode/blob/4655b60a448adfb0b827070008108d0ee2afc078/src/vs/workbench/browser/parts/editor/editorStatus.ts#L993

@bpasero I'd suggest to pass in the URI as-is to `getModeIdByFilepathOrFirstLine`, or create a new file-URI (`Uri.file(base)`) for probing.

**Comment by bpasero** [comment]
Open for grab.

**Comment by aeschli** [comment]
I'm happy to make the change. 
I'd suggest to pass in the URI as-is to getModeIdByFilepathOrFirstLine, or create a new file-URI (Uri.file(base)) for probing.

@bpasero   What do you prefer?

**Comment by bpasero** [comment]
@aeschli we cannot regress https://github.com/microsoft/vscode/issues/69334 though. There are URIs in our system that are potentially very large (inline data uris from Git) and we had freezes when those URIs would be send down to our pattern matcher.

**Comment by Wqrld** [comment]
Has the latest commit been pushed into vscode yet? I still have this issue with VS Code version: Code 1.37.1 (f06011a, 2019-08-15T16:17:55.855Z)

**Comment by aeschli** [comment]
I verified that the fix is in 1.38.0-insider (user setup)
Commit: e77b008fb04222192a608906ff603bd72943d779
Date: 2019-08-30T10:15:17.547Z


@Wqrld It will be in stable as soon as 1.38.0 is published.
