### ISSUE TITLE
Can a command support multiple shortcuts?

### ISSUE THREAD

**Issue by GanZhiXiong** [microsoft/vscode#79629]
Android Stuido supports multiple shortcuts for one command.
The nice thing about this is that I can use the default shortcuts when I want to, and I can use custom shortcuts.
And you can easily know that I have modified this shortcut key.

If vscode is not supported now, will it be supported in the future?
**Looking forward to your reply! Thanks!**

**Comment by IllusionMH** [comment]
/question

Yes, you can specify any number of shortcuts in `keybindings.json`.
You can open using <kbd>Ctrl+Shift+P</kbd>(or <kbd>F1</kbd>) and paste `>Preferences: Open Keyboard Shortcuts (JSON)`

![image](https://user-images.githubusercontent.com/1312662/63503637-8b444d00-c4d8-11e9-860d-fc2cbe7435d4.png)
