### ISSUE TITLE
Clear button not visible enough 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7962]
The current extensions input clear has some flaws:
1. Too far away from input
2. Looks disabled
3. Too small
4. Mouse does not transform to click while hovering over it
5. No hover information
6. Looks out of style compared to our other input buttons (find, search)

Due to this reasons this button can easily get ignored 

![screen shot 2016-06-22 at 09 35 10](https://cloud.githubusercontent.com/assets/1926584/16258129/a544f18e-385c-11e6-84d9-be968c3636dc.png)

**Comment by isidorn** [comment]
Also looks horrible on linux

![screen shot 2016-06-22 at 10 50 35](https://cloud.githubusercontent.com/assets/1926584/16260325/3802200a-3867-11e6-9a01-7aeedc7ef409.png)

**Comment by joaomoreno** [comment]
#7946
