### ISSUE TITLE
workbench.action.focusLeftGroup does not focus the left side

### ISSUE THREAD

**Issue by joelazar** [microsoft/vscode#79634]
- VSCode Version: 1.37
- OS Version: Windows 10 1809

I've recently opened an [issue](https://github.com/VSCodeVim/Vim/issues/3979) for VSCodeVim because on diff mode I couldn't switch side when I focused the right side of the window. @J-Fields figured out that it might be an upstream issue as workbench.action.focusLeftGroup does not focus the left side while workbench.action.focusRightGroup focuses the right side.

Could you please look into this issue?

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@joelazar Editor groups are explained [here](https://code.visualstudio.com/docs/getstarted/userinterface#_editor-groups). When I have two groups side by side, and a file open in each, I don't have any problem using Ctrl+K Ctrl+LeftArrow to switch focus from the one on the right to the one on the left. I'm testing with 1.37.1 on Windows.

I don't think the diff view spreads itself across two views. Try splitting right, then opening a diff. Then see what those commands do.

/confirmationPending

**Comment by gjsjohnmurray** [comment]
#22412 asked for a command to switch between the two diff panes. It was marked as a dup of #16707.

/duplicate
