### ISSUE TITLE
Terminal input formatting wrong

### ISSUE THREAD

**Issue by bchrisb** [microsoft/vscode#79636]
When opening a new terminal (Terminal > New Terminal), the start of the input is shifted well below the command path i.e:

```
Microsoft Windows [Version 10.0.17763.652]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\cbarnett>


                                input starts here
```

VS Code version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

![2019-08-22 13_25_35-Welcome - Visual Studio Code](https://user-images.githubusercontent.com/8687762/63514985-b2ebe300-c4e1-11e9-8f7b-3c7e1ba6b067.png)

**Comment by RMacfarlane** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by bchrisb** [comment]
@RMacfarlane I updated to Windows 10 (1903) and can confirm this is fixed. Thanks!
