### ISSUE TITLE
VS Code fails to open from file explorers address bar

### ISSUE THREAD

**Issue by tpvin** [microsoft/vscode#79638]
Issue Type: <b>Bug</b>

VS Code fails to open from windows file explorer address bar (when writing "code" + enter). Instead it prompts an "Open with..." dialog. When chosing Visual Studio Code, it opens a sh script named code within 
C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\bin

This used to work previously.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Can you record a screen recording to show me what you mean?

**Comment by tpvin** [comment]
Hi,

I failed to record explorer actions with built in windows 10 recorder.
Here is a poor quality mobile phone recording.
As soon as I hit enter after typing "code" in the address bar of file
explorer, I expect VS code to open up, not the program selector.
After selecting Visual Studio Code, it opens up displaying a .sh script.




Den fre 30 aug. 2019 kl 14:10 skrev João Moreno <notifications@github.com>:

**Comment by sbatten** [comment]
@joaomoreno 

Type code in the file explorer, it should open the `cat` folder
![image](https://user-images.githubusercontent.com/6561887/64043683-e3eb9980-cb19-11e9-966b-8524d3fbc401.png)

**Comment by joaomoreno** [comment]
@sbatten Would you happen to know how to achieve this?

**Comment by tpvin** [comment]
I have to do a correction to my error description.
I wrote : "This used to work previously"
Previously starting VS code from file explorer it did open VS code, but it didn't open the file explorer path as "open folder" which I hoped to.

The current version is worse in the sense that it opens the program "Open with" dialog.

**Comment by joaomoreno** [comment]
In the Open with dialog, if you pick Code and choose "always use Code", does it fix it?

**Comment by joaomoreno** [comment]
This sounds more like an issue with Windows than Code.

**Comment by tpvin** [comment]
Don't have the "always use Code" option in the "Open with.." dialog that pops up. Running the latest Windows 10 (1903).

**Comment by tpvin** [comment]
If I run cmd or powershell from file explorer it works. they opens up with current directory set to where file explorer pointed to.

**Comment by sbatten** [comment]
@joaomoreno no, idk how this is hooked up normally, maybe someone from the terminal team is familiar with this functionality?

@Tyriar can you cc someone from there if you don't know?

**Comment by Tyriar** [comment]
This is happening because it's seeing `code` the sh script in the bin directory which takes precedence over code.cmd, you can run the Windows CLI by entering `code.cmd .`. It will open an annoying conhost window, that is happening because it's a script that needs to be run inside a shell.

cmd/powershell work because only the exe is on the path, you could achieve what you're after by adding the folder containing code.exe to your Path and running code.exe in explorer, however you might the exe will need to be low priorities otherwise you might not be able to run the CLI in your terminal.

**Comment by tpvin** [comment]
I can understand why you close this issue. 
Still, from a user perspective, I think it is annoying to type code.cmd.
Also as a windows user I expect VS code to open the the path with "open folder" like cmd.exe and powershell.exe does. If it does not, I see no reason to type code.cmd in the file explorers address bar.

**Comment by Tyriar** [comment]
The reason is because code needs to be on the path in order to enable git bash/cygwin support. Typing in an exe/script into the explorer address bar is used significantly less than that.
