### ISSUE TITLE
1.37.1 snippet variables don't works anymore

### ISSUE THREAD

**Issue by ottopic** [microsoft/vscode#79630]
Updating from 1.36.1 to 1.37.1 my snippet variable {CLIPBOARD} is replaced with empty text

`

 "customprintr": {

		"prefix": "customprintr",
	 	"body": [
			"\t    echo '<pre style=\"text-align:left\">';",
			"\t    \\$printMe = ${CLIPBOARD};",
			"\t    echo '</pre>';",
			"\t    die;",
			"\t"
	 	],
	 	"description": "Insert custom print_r"
	},
	"br": {
		"prefix": "br",
		"body": ["<br />"]
	}
`

**Comment by ottopic** [comment]
Looking better my script I notice that I'm using macro to insert the snippet. Is it possibile that editor.action.clipboardCopyAction is not working?

`
"macros": {

        "printr": [
            "editor.action.smartSelect.grow",
            "editor.action.clipboardCopyAction",
            "editor.action.insertLineAfter",
            {
             "command": "editor.action.insertSnippet",
                "args": {
                    "name": "customprintr",
                    "langId": "php",
                }
           },
           "editor.action.insertLineAfter",
           "editor.action.clipboardCopyAction",
        ]
    }, 
`

**Comment by RMacfarlane** [comment]
@sbatten I remember you made changes that made some part of the clipboard async, was that last milestone and would it impact executing `editor.action.clipboardCopyAction`?

**Comment by sbatten** [comment]
yes /cc @jrieken

**Comment by jrieken** [comment]
🤷‍♂ no clue, the `editor.action.clipboardCopyAction` is from the editor. I have tested snippets and they seem to work.

>  I notice that I'm using macro to insert the snippet

@ottopic What is macro? Is that an extension you are using?

**Comment by ottopic** [comment]
Yes it is, is very used [extension](https://github.com/geddski/macros) to execute commands.
I use this one because I think is not possibile do the same think only using snippet functionality.

**Comment by jrieken** [comment]
Ok, please forward this issue to the extension that. The extension is using `vscode.commands.executeCommand` which returns a promise but that extension isn't awaiting those promises, see https://github.com/geddski/macros/blob/master/extension.js#L34. Reading from the clipboard is now async and mostly like a command is started before the previous command is done.
