### ISSUE TITLE
The status bar on the bottom cannot show!

### ISSUE THREAD

**Issue by yuchenzhen** [microsoft/vscode#79646]
The status bar on the bottom change into a white bar with no content shows on the screen.

**Comment by RMacfarlane** [comment]
Hi @yuchenzhen, can you include some more information to help figure out the problem? What version of VSCode are you using, and what operating system? Where you doing anything before the status bar changed color? Can you try disabling extensions and seeing if the problem persists?

**Comment by yuchenzhen** [comment]
<img width="1438" alt="WeChatWorkScreenshot_066f99fc-c932-49b5-b36e-8a01316d7faa" src="https://user-images.githubusercontent.com/16936490/63564283-1126cd80-c597-11e9-9e1a-9d887317361d.png">

On the bottom you can see the status bar blocked by the white long bar which only shows up when i use vscode.   The white long bar cannot type any word on it.

**Comment by bpasero** [comment]
@yuchenzhen 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
