### ISSUE TITLE
Follow link activates with Cmd and mouse over instead of click

### ISSUE THREAD

**Issue by braun1928** [microsoft/vscode#79644]
Issue Type: <b>Bug</b>

The link opens when I'm holding Command and hover it with the mouse, instead of clicking it; sometimes it's not the link I want to click, but go over it with the mouse pointer, and end up opening a page I didn't want.
I'm using vscode mainly for terraform, I don't know if it's a default behaviour or an issue with the extension.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|1.4.3
githistory|don|0.4.6
terraform-autocomplete|erd|0.0.8
jenkins-declarative-support|jmM|0.1.0
terraform|mau|1.3.12
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.2
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
Go|ms-|0.11.4
debugger-for-chrome|msj|4.11.7
go-doc|msy|0.1.1
ruby|reb|0.24.2
java|red|0.47.0
vscode-xml|red|0.8.0
vscode-yaml|red|0.5.1
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.1
gitblame|wad|3.0.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it happen if you disable all extensions?
Where do you hover over links: editors, markdown preview, terminal, or other specific place?

Checked on Windows in editors, markdown preview, extension details, and terminal and it doesn't happen here.

**Comment by braun1928** [comment]
Definitely something wrong with the terraform extension. Opened a golang source, wrote a URL in the terminal and in the editor, all cases the click was needed. I'll raise a ticket there. Thanks!
