### ISSUE TITLE
VS Code freezes during syntax coloring

### ISSUE THREAD

**Issue by swbrenneis** [microsoft/vscode#79640]
- VSCode Version: 1.37.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Open a Java file with a very long string constant.
2. VS Code window freezes when it starts syntax coloring.

The entire window is frozen, so the process explorer can't be used. Task manager says that VS code is using 25% CPU. This is repeatable.

Java files without a long string constant open as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@swbrenneis Can you provide a code sample that results in this problem?

**Comment by swbrenneis** [comment]
I cannot provide the original files since they contain extremely sensitive information. I will work up a similar file and try to reproduce it.

**Comment by swbrenneis** [comment]
Sorry for the delay. Other work got in the way. This file reproduces the problem repeatably.

[MyTest.zip](https://github.com/microsoft/vscode/files/3555915/MyTest.zip)

**Comment by rebornix** [comment]
I can reproduce this issue with file above and latest Java grammar in master but there is no issue with a simple java grammar https://github.com/microsoft/vscode-textmate/blob/master/test-cases/first-mate/fixtures/java.json

**Comment by alexr00** [comment]
Moved to the owning repo.
