### ISSUE TITLE
Install button in extension header too small

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7964]
The install button in the extensions header is the same size as the install button in the list - that is nice for consistency but:
1. there is too much empty space in the header
2. this is the most important action a user can take

Due to these reasons I believe the install button should be larger in the extensions header
Same for the uninstall button for the installed extensions header

![screen shot 2016-06-22 at 09 38 05](https://cloud.githubusercontent.com/assets/1926584/16258226/185a7ae0-385d-11e6-9042-031d66d822dd.png)

**Comment by joaomoreno** [comment]
YES!

**Comment by joaomoreno** [comment]
Do it in `extensionsEditor.css`.
