### ISSUE TITLE
Uninstall button color blends too much in extensions header background

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7965]
The uninstall button needs a clearer distinction from the extensions header background. Currently it blends too much and the user can easily ignore this button.
I like how it looks in the list, and I think it should have consistent color with the one in the header but I believe we can find a color which will work for both places.

Maybe increasing the size as suggested in #7964 might fix this issue

![screen shot 2016-06-22 at 09 41 54](https://cloud.githubusercontent.com/assets/1926584/16258313/973a20b8-385d-11e6-941b-a7150dbd90fb.png)

**Comment by joaomoreno** [comment]
Yeah I think #7964 will fix it
