### ISSUE TITLE
Test: Automation shell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#79657]
Test for #78497

- [x] Linux @weinand 
- [x] macOS @RMacfarlane 
- [x] Windows @joaomoreno 

Complexity: 3

The new settings `terminal.integrated.automation.shell.<platform>` was introduced which when set will override the shell used by tasks and debug with whatever is specified. This will also cause shellArgs to get ignored.

To verify make sure it does as advertised for regular terminals (not touch), tasks and debug.

**Comment by weinand** [comment]
It seems the correct name of the setting is `terminal.integrated.automationShell.<platform>`.
