### ISSUE TITLE
Insiders crashing because file is not opened before sending commands operating on that open file

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/vscode#79650]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Issue transfer from microsoft/TypeScript#32827

From the server log the command `getApplicableRefactors` is called before opening the file.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by whitecolor** [comment]
I disabled all the extensions (left only some important to me and ui related), and it seems to work ok for a couple of days.
