### ISSUE TITLE
Unable to find definition from index file while on the same folder

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#79659]
Issue Type: <b>Bug</b>

VSCode is not able to navigate to the definition from an index file to a file that is on the same folder.
Here is a little but simple example:
index.js

```js
import Conversation from './Conversation.component';

export default Conversation;
```

Folder structure

```
Conversation
 \_ index.js
 |_ Conversation.component.jsx
```

When you try to go to the definition of the only import on the index file it just goes to the index itself.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
auto-add-brackets|ali|0.10.0
Handlebars|and|0.4.1
jest-snippets|and|1.7.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-devtools-for-chrome|cod|0.0.5
danielo-node-snippets|dan|1.8.1
danielo-vsc-tools|dan|1.0.1
vscode-eslint|dba|1.9.1
jest-test-language-support|dpl|1.30.2
es7-react-js-snippets|dsz|2.4.3
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vimL|fal|0.0.3
auto-rename-tag|for|0.1.0
lintlens|ghm|2.4.0
vscode-pull-request-github|Git|0.10.0
githd|hui|2.1.0
vscode-peacock|joh|3.1.4
styled-components-snippets|jon|0.4.0
open-in-vim|jon|0.5.0
vscode-styled-components|jpo|0.0.26
expand-region|let|0.1.2
vscode-wrap-console-log|mid|1.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|0.7.0
debugger-for-chrome|msj|4.11.7
color-highlight|nau|2.3.0
incrementor|nms|0.1.0
indent-rainbow|ode|7.4.0
advanced-new-file|pat|1.2.0
vscode-quick-spec|rau|0.1.0
vscode-yaml|red|0.5.1
partial-diff|ryu|1.4.0
vscode-javascript-booster|sbu|0.11.0
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.2
addDocComments|ste|0.0.8
code-spell-checker|str|1.7.18
control-snippets|svi|1.3.0
json-schema-validator|tbe|0.1.0
highlight-matching-tag|vin|0.9.3
template-strings|vit|0.0.5
vscode-icons|vsc|9.2.0
vscode-wakatime|Wak|2.2.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
disable-eslint-rule|Woo|0.0.2
vscode-open-in-github|ziy|1.3.6
es6-string-javascript|zjc|1.0.1

</details>

**Comment by mjbvz** [comment]
Where exactly are you running `go to definition`?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by danielo515** [comment]
I'm running it on any place of the codebase, same result.
I am not running the insiders build, but I cant try with all the extensions disabled to see if that makes a difference.
If it does, I may try to provide a small reproduction repo

**Comment by danielo515** [comment]
It still happens with extensions disabled.
However, I tried to create a small reproduction and it works fine on my example. Is there any way I can debug how this happens in some repos? Some console output explaining the steps tried to find the definition that failed?

**Comment by mjbvz** [comment]
Did you have a change to test using the insiders build? 

You generally cannot debug this type of issue on your own. The best option is for you to provide a small example project so we can debug it, or you could try sending us detailed logs. Are either of those possible?

**Comment by danielo515** [comment]
As I said I tried to create a small reproduction without success, it only happens on my big project. So I think the best option will be to use the insiders build and provide detailed logs. How can I fetch such logs? What should they include?

**Comment by mjbvz** [comment]
To collect the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code with a ts file open, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by danielo515** [comment]
Sorry for the late response.
It is still happening, but on a different fashion. Instead of redirecting you again to the same index file it simple does nothing.

I have the (huge) log. I'm not worried about paths, but I don't want to expose src if there is any.
Is there a way that I can send it to you?

**Comment by danielo515** [comment]
Well, I can always remove it later.

[tsserver.log](https://github.com/microsoft/vscode/files/3718084/tsserver.log)

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

Do you still see the issue in that case?
