### ISSUE TITLE
Typescript no syntax highlighting on hover popover

### ISSUE THREAD

**Issue by FadeZhanger** [microsoft/vscode#79653]
Issue Type: <b>Bug</b>

Hovering a property/function/type/class displays a popover with detailed information. The code in the popover should have its syntax highlighted, but it is not:
![image](https://user-images.githubusercontent.com/30360288/63529925-8f21a080-c4d3-11e9-99d1-082b14e35e9c.png)

---

With Code 1.37.1, this is working as intended:
![image](https://user-images.githubusercontent.com/30360288/63530432-7665ba80-c4d4-11e9-82f1-65f0b7e31ce5.png)

---
VS Code version: Code - Insiders 1.38.0-insider (ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8, 2019-08-21T13:26:22.457Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.83GB free)|
|Process Argv|--disable-extensions --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by Gama11** [comment]
@gjsjohnmurray Not sure about that, he said in 1.37 it's working as intended (meaning it regressed between 1.37 and 1.38-insider). My issue in #78946 is broken in 1.37 but worked in earlier releases.

**Comment by gjsjohnmurray** [comment]
@FadeZhanger does this still happen for you on the latest 1.38-insider?
