### ISSUE TITLE
assign three quotes string to variable, VS code add strange characters on both mac and linux

### ISSUE THREAD

**Issue by RenNY123** [microsoft/vscode#79664]
Issue Type: <b>Bug</b>

assign a long string to a variable in python with tree quotes """ 
when you run it with shift enter on mac or linux, it addes strange characters. 
below is quote to test:

test = """
with dba_agg AS (
SELECT af.*, apps.ap_subm, ap_count, ap_return_leases, ap_fraud
, acct_subm, acct_count, acct_return_leases, ddd
-- , tna
FROM ap_first af
LEFT JOIN apps_ag apps ON af.test_name = apps.test_name
LEFT JOIN accts_ag accts ON accts.test_name = apps.test_name AND accts.acct_subm = apps.ap_subm
)
,dba_agg AS (
SELECT af.*, apps.ap_subm, ap_count, ap_return_leases, ap_fraud
, acct_subm, acct_count, acct_return_leases, ddd
-- , tna
FROM ap_first af
LEFT JOIN apps_ag apps ON af.test_name = apps.test_name
LEFT JOIN accts_ag accts ON accts.test_name = apps.test_name AND accts.acct_subm = apps.ap_subm
)
,dba_agg AS (
SELECT af.*, apps.ap_subm, ap_count, ap_return_leases, ap_fraud
, acct_subm, acct_count, acct_return_leases, ddd
-- , tna
FROM ap_first af
LEFT JOIN apps_ag apps ON af.test_name = apps.test_name
LEFT JOIN accts_ag accts ON accts.test_name = apps.test_name AND accts.acct_subm = apps.ap_subm
)
,dba_agg AS (
SELECT af.*, apps.ap_subm, ap_count, ap_return_leases, ap_fraud
, acct_subm, acct_count, acct_return_leases, ddd
-- , tna
FROM ap_first af
LEFT JOIN apps_ag apps ON af.test_name = apps.test_name
LEFT JOIN accts_ag accts ON accts.test_name = apps.test_name AND accts.acct_subm = apps.ap_subm
)
, dba_agg AS (
SELECT af.*, apps.ap_subm, ap_count, ap_return_leases, ap_fraud
, acct_subm, acct_count, acct_return_leases, ddd
-- , tna
FROM ap_first af
LEFT JOIN apps_ag apps ON af.test_name = apps.test_name
LEFT JOIN accts_ag accts ON accts.test_name = apps.test_name AND accts.acct_subm = apps.ap_subm
)

SELECT * FROM dba_agg
"""
![Screen Shot 2019-08-22 at 1 12 26 PM](https://user-images.githubusercontent.com/12498852/63542859-a9ad4700-c4de-11e9-97d0-e301af09ed32.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_565386|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
angular-schematics|cyr|1.23.0
vscode-simpler-icons|dav|1.6.5
angular-extension-pack|dog|7.2.0
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
Python-autopep8|him|1.0.2
beautify|Hoo|1.5.0
angular2-switcher|inf|0.2.0
docthis|joe|0.7.1
Angular2|joh|8.1.1
refactorix|kri|0.3.6
json-to-ts|Mar|1.5.5
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
sublime-keybindings|ms-|4.0.3
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.2
quicktype|qui|12.0.46
move-ts|str|1.11.5
ayu|tea|0.18.0
vscode-status-bar-format-toggle|tom|1.5.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@RenNY123 I haven't been able to reproduce this problem yet, can you see if it also happens after you have hit F1 and run the command `Developer: Reload Window With Extensions Disabled`? Do you see the string printed normally in a terminal outside of VSCode?

**Comment by Tyriar** [comment]
Can you try in the insiders build? I can't reproduce your first screenshot, also what do you mean ddd\n is added, you have that in the original string? If you can refine your repro so it's a little smaller it would be easier to repro/diagnose.

**Comment by RenNY123** [comment]
hi, Tyriar  

thanks for your reply. 
I tried insiders build, without any extension and a clean install of python and still have the same issue. 

I do not have "ddd\n" in my test string it's added when I try to run it in VS Code terminal. (you can find them in the terminal in the screen shot)

I tried to run the code in VS Code Python Interactive, it's perfectly fine also.
so my temporary solution is to run everything in the interactive. 

I also tried my colleagues' ubuntu machine on a Lenovo Thinkpad, similar issue happened. (just to make sure it's not my settings)  but different characters were added/produced.
