### ISSUE TITLE
Extension configuration order

### ISSUE THREAD

**Issue by idleberg** [microsoft/vscode#79666]
If I'm not mistaken, older versions of VSCode displayed configuration settings in the order they were specified in `package.json`. This is no longer the case and probably related to the switch to a visual config editor.

However, ordering configuration settings alphabetically does not always make sense. I prefer grouping related properties and to logically guide a user through them.

**Example:**

```json
"configuration": {
  ...
  "properties": {
    "nsis.pathToMakensis": {
      "type": "string",
      "default": null,
      "description": "Specify the path to makensis"
    },
    "nsis.compilerArguments": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [],
      "description": "Specify custom compiler arguments"
    },
    "nsis.alwaysOpenBuildTask": {
      "type": "boolean",
      "default": true,
      "description": "Specify whether to open the newly created build task"
    }
  }
}
```

These options are now displayed in the following order:

1. Always Open Build Task
2. Compiler Arguments
3. Path To Makensis

Specifying `pathToMakensis` is the most important setting in this example. Since the `compilerArguments` setting depends on a path to be specified, it would make more sense to have it after the `pathToMakensis` setting. Also in this example, there is the `alwaysOpenBuildTask` setting, which is a setting most people won't care about. Being less important, it makes no sense to have it displayed first.

Configuration settings for the Atom editor have a very similar format to that of VSCode. They allow specifying the `order` in which the settings appear.

**Example:**

```json
"configuration": {
  ...
  "properties": {
    "nsis.pathToMakensis": {
      "type": "string",
      "default": null,
      "description": "Specify the path to makensis",
      "order": 1
    },
    "nsis.compilerArguments": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [],
      "description": "Specify custom compiler arguments",
      "order": 2
    },
    "nsis.alwaysOpenBuildTask": {
      "type": "boolean",
      "default": true,
      "description": "Specify whether to open the newly created build task",
      "order": 3
    }
  }
}
```

It would be useful, if VSCode had the same to specify the order!

**Comment by rzhao271** [comment]
There are now `order` fields for individual settings. Also, if your configuration is in the form of an array of objects (such as https://github.com/microsoft/vscode/blob/main/extensions/css-language-features/package.json#L36), then those array elements also have `order` fields that we respect in the Settings editor table of contents.

Ref https://github.com/microsoft/vscode/issues/133483
