### ISSUE TITLE
TaskProvider.resolveTask getting called at extension startup.

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#79661]
Issue Type: <b>Bug</b>

By the docs, it seems like the TaskProvider should be able to handle the users creating custom tasks, which would depend on the task only getting resolved when the task is requested to be ran. However, this does not seem to be the case, and the task gets resolved immediately.

1. Create a custom task provider (it can be very basic)
2. Create a task of the provided type
3. resolveTask gets called immediatly, and not when the task is actually called.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (6.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
`resolveTask` gets called when tasks are enumerated, not when they are run. If you have automatic tasks enabled in the folder that you are opening, then task enumeration will happen shortly after you open the folder.
