### ISSUE TITLE
Option to not automatically resize all panes when splitting a pane

### ISSUE THREAD

**Issue by zbjornson** [microsoft/vscode#79665]
Right now when you split a pane, all panes are resized so they have equal width:

![resize-panes](https://user-images.githubusercontent.com/469365/63544644-81bbe480-c4da-11e9-8b68-70b501d79ad5.gif)

Personally I'd much rather it preserve the existing widths, and only split the width of the pane that I split. An option for this would be nice.

(Annoyance being that I have two or three columns already; when I click split, I now have to re-resize three or four columns to put them back where I had them.)

**Comment by zbjornson** [comment]
None of those appear to be dupes. I also went through every open and closed issue for "split".

**Comment by bpasero** [comment]
Changing that or offering a setting would result in the following experience:

![Peek 2019-10-10 11-53](https://user-images.githubusercontent.com/900690/66558852-9c165400-eb54-11e9-8a27-1a07548aa102.gif)

Is that clever?

**Comment by zbjornson** [comment]
@bpasero I like that. 😍 I think it'd be nice if that mode did the same (no auto-resize) when closing a tab also -- did you happen to do that?

**Comment by bpasero** [comment]
Ok we can add a setting. If someone wants to provide a minimal PR.

**Comment by dhairyanadapara** [comment]
@bpasero I would like to take up this issue. Will try to raise a PR for this soon.

**Comment by dhairyanadapara** [comment]
@bpasero I have raised PR but tests are failing can you review the PR and guide me fix tests. Thanks :)

**Comment by bpasero** [comment]
**Verification**: Try the new `workbench.editor.splitSizing` works as advertised.
