### ISSUE TITLE
TaskProvider.resolveTask not responding to adding ShellExecution

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#79662]
Issue Type: <b>Bug</b>

1. Create a custom task provider (it can be very basic)
2. Create a task of the provided type.
3. In resolveTask, add the following code.

```
    public resolveTask(task: vscode.Task, _?: vscode.CancellationToken | undefined): vscode.ProviderResult<vscode.Task> {
        task.execution = new vscode.ShellExecution('echo Hello!');
        return task;
}
```

By the documentation, and what it seems like the task does, this should work. However I get a task error, saying the task was not provided.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (6.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
The task is incomplete. See example: https://github.com/microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/rakeTaskProvider.ts#L29
