### ISSUE TITLE
Error when trying to install extensions

### ISSUE THREAD

**Issue by Hassan-Azzam** [microsoft/vscode#79669]
I can't install any extension i don't know why.
every time i try to install new one i get this error
"Failed to install extension-name, Download Manually"
and even when i do download the extension manually it gives me the same error.

also all the extensions icons are not loading which means the editor can't reach the vs code servers to get the extensions and the icons.

but i have no idea how to fix it.
in the console when i open the extensions tab i get a list of errors for failing to fetch the icons and also the network tab i get an error when i try to install extensions,
i have screenshot for all that down below.
![1](https://user-images.githubusercontent.com/42672551/63556853-a2ba1f00-c546-11e9-99ea-5ea0012ae302.PNG)
![2](https://user-images.githubusercontent.com/42672551/63556854-a2ba1f00-c546-11e9-9652-d7074e1d9969.PNG)
![3](https://user-images.githubusercontent.com/42672551/63556856-a2ba1f00-c546-11e9-81b7-dc04f61a665c.PNG)
![4](https://user-images.githubusercontent.com/42672551/63556857-a352b580-c546-11e9-9614-7cfcbc5e3cd8.PNG)
![5](https://user-images.githubusercontent.com/42672551/63556858-a352b580-c546-11e9-83de-06749493ff79.PNG)
![6](https://user-images.githubusercontent.com/42672551/63556859-a352b580-c546-11e9-896d-5b4db7459e04.PNG)

**Comment by sandy081** [comment]
Related to #78783 seems to be a DNS issue.

Can you try to access this image? ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to 1.1.1.1 as suggested here? 1.1.1.1/dns

**Comment by AhmedHalim96** [comment]
Thanks It's a DNS Problem once I changed it everything went well!

**Comment by Hassan-Azzam** [comment]
all the solutions seems to be the same but i tried all noting is working i don't know what's wrong it was working perfectly before.
