### ISSUE TITLE
Import changes to TextMate YAML syntax highlighting to fix string literals

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#79667]
On VSCode 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35), string literals in YAML aren't treated completely as strings. I opened microsoft/vscode#54219 a while back but was closed waiting for TextMate to fix this. Based on textmate/yaml.tmbundle#26 it seems that has happened. Can you do an import/conversion and test this?

**Comment by alexr00** [comment]
From the other bug:

> This is already fixed in TextMate (tested in version 2.0-rc.23). Github uses https://github.com/atom/language-yaml/blob/master/grammars/yaml.cson which also works. I don't know if VSCode supports the CSON format but it should be trivially convertible to VSCode-compatible JSON.

Looks like we need to think about changing to another grammar.

**Comment by heaths** [comment]
Perhaps, but my understanding is that the .tm files from TextMate are converted to JSON. GH is using a different format, sure, but doesn't necessarily indicate you have to use that.

**Comment by alexr00** [comment]
I tested out https://github.com/atom/language-yaml/blob/master/grammars/yaml.cson  and the syntax highlighting we get from that is inferior. 
<img width="604" alt="alternateYaml" src="https://user-images.githubusercontent.com/38270282/64109093-e569cb80-cd7e-11e9-85a7-012e9f5b25e8.png">

We have the latest yaml grammar from textmate/yaml.tmbundle already, so it looks like there is still a need for a fix there for https://github.com/textmate/yaml.tmbundle/issues/26

**Comment by heaths** [comment]
Please take a look at the comment here: https://github.com/textmate/yaml.tmbundle/issues/26#issuecomment-523367703

Seems this is already fixed in TextMate. I wasn't suggesting to use CSON.

**Comment by alexr00** [comment]
We already have the latest from textmate/yaml.tmbundle
