### ISSUE TITLE
Error while loading extensions if start vscode from desktop entry

### ISSUE THREAD

**Issue by qtcwt** [microsoft/vscode#79671]
- VSCode Version: 1.37.1
- OS Version: Manjaro 18.0.4

VSCode cannot install extension. It returns an error like 
`error while loading extensions. connect ENOENT /run/user/1000/vscode-a6e6e4fe-1.37.1-shared.sock`
In `/run/user/1000`, there's only `vscode-bf9f08ec-1.37.1-shared.sock` created when VSCode is started from desktop entry.

However, if vscode is started from the terminal via command `code`, there's no problem at all. A correct `vscode-a6e6e4fe-1.37.1-shared.sock` will be created in the directory and extensions can be installed.

Below is the desktop entry I use:

[Desktop Entry]
Exec=/opt/visual-studio-code/code %f
Icon=visual-studio-code
Terminal=false
Type=Application
Name=Visual Studio Code
Comment=Editar for building and debugging modern web and cloud applications
Categories=Development;WebDevelopment;IDE;Utility;TextEditor;
MimeType=text/plain;inode/directory;
StartupNotify=true
StartupWMClass=code

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
In VS Code, open the DevTools and run `getLazyEnv().then(e => console.log(e))`. Compare the environments from both execution options and see what is different.

**Comment by qtcwt** [comment]
Fixed by reinstalling it from Snap Store. It was installed from [here](https://aur.archlinux.org/packages/visual-studio-code-bin/) which might configure things incorrectly.
