### ISSUE TITLE
Keyboard shortcuts/settings context menu consistency

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#79670]
In the settings UI editor, right clicking on a setting to open the context menu will give two options: `Copy Setting ID` and `Copy Setting as JSON`.

For consistency, it seems like it'd make sense to name those options similarly in the Keyboard Shortcuts UI editor when right clicking on a keyboard rule, changing `Copy` to `Copy Command as JSON` and changing `Copy Command` to `Copy Command ID`.

**Comment by jabacchetta** [comment]
Related: #79747 and #79783

**Comment by sandy081** [comment]
I would just change `Copy Command` to `Copy Command ID`. `Copy` commands copies the complete entry as JSON. I do not think `Copy as JSON` looks good and `Copy` is  intuitive enough.
