### ISSUE TITLE
Browser is Not supported WebStock for Live Reloading

### ISSUE THREAD

**Issue by Snyeswa** [microsoft/vscode#79678]
Issue Type: <b>Bug</b>

'Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.46GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|3.8.1
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details>

**Comment by garyng** [comment]
An extension issue. Check https://github.com/ritwickdey/vscode-live-server.

The solution is obvious: update your browser.

**Comment by Snyeswa** [comment]
Thanks for the help and I will follow the link to solve the issue. My browser is actually up to date and I'm still getting the same error.
Google Chrome is up to date
Version 76.0.3809.100 (Official Build) (64-bit)
