### ISSUE TITLE
Copy code from vscode to ex Word shows $nbsp instead of space.

### ISSUE THREAD

**Issue by PsPsam** [microsoft/vscode#79677]
Issue Description
Copying code from Insider build 1.38.0 to Word will show &nbsp instead of blankspace. The format of the document is PowerShell.

This doesn't happen in the stable version

![image](https://user-images.githubusercontent.com/20344934/63568571-eed08800-c575-11e9-91d9-936ac2a73b1a.png)

- VSCode Version: 1.38.0-Insider user
- OS Version: Windows 10

Steps to Reproduce:

1. Open a PowerShell file
2. Copy the code
3. Paste the code in word

Does this issue occur when all extensions are disabled?: Yes

**Comment by BobSeu** [comment]
I'm running into this issue as well.  In my case it was a log file copying text to Outlook.  Stable 1.37 doesn't have that, but Insiders does.

**Comment by alexandrudima** [comment]
I cannot reproduce on macOS

**Comment by alexandrudima** [comment]
I can reproduce on Windows. @rebornox introduced via https://github.com/microsoft/vscode/commit/948d3446f35bda09991c6aecfc695e45f2d55280
