### ISSUE TITLE
How to get integral output?

### ISSUE THREAD

**Issue by wtus** [microsoft/vscode#79672]
i am trying to print a json string

![](https://ae01.alicdn.com/kf/H0596dce6ae2a4a8a91d0b583274e5d29i.png)

how do i get complete json without newline

**Comment by garyng** [comment]
A simple google search gave me this: https://stackoverflow.com/questions/25590667/class-structure-to-formatted-json-in-dart

Use [`JsonEncoder.withIndent`](https://api.dartlang.org/stable/2.4.1/dart-convert/JsonEncoder/JsonEncoder.withIndent.html).
