### ISSUE TITLE
All @tag:usesOnlineServices settings are disable (enabled for some) but vs code is still trying to connect to Internet

### ISSUE THREAD

**Issue by bobsort** [microsoft/vscode#79685]
Issue Type: <b>Bug</b>

All updates and online services are disabled based on settings specified here 

https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting

But VSCode is still trying to connect to Internet
Connection attempts are to 
224.0.0.252 (llmnr)
8.8.8.8 (dns) 

I have disabled DNS service from services.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (4.62GB free)|
|Process Argv|--user-data-dir D:\VSCode\Settings|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by RMacfarlane** [comment]
@sandy081 It looks like the extension gallery service is making a POST at startup

**Comment by sandy081** [comment]
@RMacfarlane What POST requests are you talking about?
