### ISSUE TITLE
Trackpad three fingers wipe gesture does not work any more

### ISSUE THREAD

**Issue by masq6r** [microsoft/vscode#79688]
After upgrading to 1.37, my VSCode doesn't respond to my three fingers wipe gesture (left wipe to last edit location). It used to work prior to 1.37. I'm running VSCode in Windows 10, with the latest Windows 10 version 1903 (18362.295).

**Comment by deepak1556** [comment]
@masq6r can you try our exploration builds and see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCodeUserSetup-x64-1.37.0-exploration.exe)
