### ISSUE TITLE
cursorColumnSelectLeft, cursorColumnSelectRight

### ISSUE THREAD

**Issue by niuniuliu** [microsoft/vscode#79687]
Issue Type: <b>Bug</b>

cursorColumnSelectLeft and cursorColumnSelectRight do not work.

text editor mode - 

Try to make the selection lines enter the multi-line editing (aka column mode edit)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:18:10.377Z)
OS version: Windows_NT ia32 10.0.17763

**Comment by alexandrudima** [comment]
@niuniuliu How do you mean that these commands do not work? They work for me:
![column-selection-X](https://user-images.githubusercontent.com/5047891/63781445-0d25e300-c8ea-11e9-9759-7e9a19d86bca.gif)

**Comment by niuniuliu** [comment]
> @niuniuliu How do you mean that these commands do not work? They work for me:
> ![column-selection-X](https://user-images.githubusercontent.com/5047891/63781445-0d25e300-c8ea-11e9-9759-7e9a19d86bca.gif)

@alexandrudima Roll back to 1.37, the issue was fixed. It's should be a regression issue of the new build. 

I mean use the keyboard hotkey to do column edit.
The default Keybinding is Ctrl+Shift+Alt+LeftArrow/RightArrow.

**Comment by niuniuliu** [comment]
I'm not going to re-open this issue. I used 1.37.0. It's perfect. Disabled VSCode auto-update already.
