### ISSUE TITLE
file is bin, can't open as text

### ISSUE THREAD

**Issue by chenxuuu** [microsoft/vscode#79682]
Issue Type: <b>Bug</b>

in chinese :文件似乎是二进制文件，无法作为文档打开

when I open a txt file, I can't change its encoding, vscode show this 

![图片](https://user-images.githubusercontent.com/10357394/63570885-23ae0080-c5b1-11e9-8815-a643e35775b6.png)
![图片](https://user-images.githubusercontent.com/10357394/63570898-2f012c00-c5b1-11e9-8076-3fe64cbeaed8.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.65GB free)|
|Process Argv|D:\OneDrive\同步文件夹\luat_desktop\logi log good startup(1).txt|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
blamer-vs|bea|0.5.0
love|bsc|0.3.6
vscode-markdownlint|Dav|0.30.1
xml|Dot|2.5.0
gitlens|eam|9.9.3
diff-tool|jin|0.0.1
svn-scm|joh|1.54.4
luacoderassist|liw|2.3.3
vscode-language-pack-zh-hans|MS-|1.37.5
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
csharp|ms-|1.21.1
vsliveshare|ms-|1.0.721
indent-rainbow|ode|7.4.0
code-settings-sync|Sha|3.4.2
vscode-hexdump|sle|1.7.2

</details>

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by chenxuuu** [comment]
@bpasero no, it's a bug
you can try any file, start with some 0x00 bytes, after those are really text
when you open it, vscode will mind you this file is bin file, you need to click and open it:
![图片](https://user-images.githubusercontent.com/10357394/63785201-83463c00-c922-11e9-9933-00d090e8924f.png)
then you can't change this file's encoding:
![2019-08-27_23-30-30](https://user-images.githubusercontent.com/10357394/63785396-e0da8880-c922-11e9-827e-64a0d588cd81.gif)

**Comment by chenxuuu** [comment]
I'll make a new issue
