### ISSUE TITLE
No references codelens for default typescript export 

### ISSUE THREAD

**Issue by LeopoldLerch** [microsoft/vscode#79686]
Hi
Somowhow I do not get the references to show up if I use a arrow function like this (as for a React Hook)

![image](https://user-images.githubusercontent.com/28888039/63573694-47a81c80-c586-11e9-8acc-217e1db4fe61.png)

As you can see in the image left above, if I peek for references VSCode does find them. If I do the same using the "old" "function" declaration, it works. I managed CodeLens to show up in the first place (I had to add "Function" to the Codelens-Scope), however, the references are still missing.

References in CodeLens are working fine as long inside classes and interfaces. 

Any Ideas?
Regards
Leo

**Comment by LeopoldLerch** [comment]
Seems to have something to do with the way "default" and "export" works.

declaring it with a const and without default it works:

![image](https://user-images.githubusercontent.com/28888039/63591361-de88cf00-c5ae-11e9-86aa-dee818f10e02.png)


however, I cannot export it as default while maintaining the references. I can reexport the const as default again, but as soon as I remove the export from the const-declaration itself, the references get lost. Only way currently is to export it both as default (as I need it) AND non-default (or the reference annotation disappears).

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/34601 to track root cause of this upstream
