### ISSUE TITLE
Closing developer tools causes vscode to crash and close

### ISSUE THREAD

**Issue by shanDeNaBianHaiDeNaBian** [microsoft/vscode#79691]
Issue Type: <b>Bug</b>

Open developer tools, close it again, open it again, close it quickly, and vscode crashes and closes it.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.37.5
vetur|oct|0.22.2
java|red|0.47.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-weex|wee|0.0.12
weex-debugger|wee|0.0.15
weex-doctor|wee|0.1.15
weex-lang|wee|0.0.14
weex-new-project|wee|0.1.7
weex-run|wee|0.0.11

</details>

**Comment by deepak1556** [comment]
@shanDeNaBianHaiDeNaBian can you try our exploration builds and see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCodeUserSetup-x64-1.37.0-exploration.exe)
