### ISSUE TITLE
Status bar foreground not changing

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#79699]
- VSCode Version: 1.37.1
- OS Version: Windows 10

Every time I install VSCode from scratch I pull my settings from Github Gist, which works fine. One setting, however, never gets applied and that is

`"statusBar.background" : "#ffffff"`

It happens every time and usually I end up restarting the vscode, trying to remove the setting and add it again.

**Comment by usernamehw** [comment]
Maybe you have 0 folders opened. In that case `"statusBar.noFolderBackground"` is used.

**Comment by moseleyi** [comment]
Oh wow.. that's new :D Thank you!
