### ISSUE TITLE
Parameter hints text can flow out of widget

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79690]
![image](https://user-images.githubusercontent.com/900690/63577925-b8076b80-c58f-11e9-8b41-42031451b5ac.png)

**Comment by jrieken** [comment]
<img width="989" alt="Screenshot 2019-08-23 at 10 41 24" src="https://user-images.githubusercontent.com/1794099/63579352-bee3ad80-c592-11e9-9f84-42185d6a6063.png">

**Comment by bpasero** [comment]
We need to look into this as E6 will land Monday.

**Comment by mjbvz** [comment]
Should be fixed now:

<img width="1041" alt="Screen Shot 2019-09-14 at 9 17 52 AM" src="https://user-images.githubusercontent.com/12821956/64910932-91d97500-d6d0-11e9-8f23-04275c518927.png">

**Comment by mjbvz** [comment]
For verification, since we reverted the electron update please test this on web using the latest Chrome
