### ISSUE TITLE
 Data tree node not found: [object Object]

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#79693]
Issue Id: <b>bade89ac-ace4-53d0-084c-b05ea342ce1b</b><br /><br />*Versions* <br />- 1.37.1<br />*Stack* <br />Error: Data tree node not found: [object Object]<br />[/vs/base/browser/ui/tree/asyncDataTree.ts#637:9 (getDataNode)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/browser/ui/tree/asyncDataTree.ts#L637:9 (getDataNode))<br />[/vs/base/browser/ui/tree/asyncDataTree.ts#490:20 (updateWidth)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/browser/ui/tree/asyncDataTree.ts#L490:20 (updateWidth))<br />[/vs/workbench/contrib/files/browser/views/explorerView.ts#272:56 (updateWidth)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L272:56 (updateWidth))<br />[/vs/workbench/contrib/files/browser/views/explorerViewer.ts#170:9 (call)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L170:9 (call))<br />[/vs/base/common/event.ts#572:15 (fire)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/common/event.ts#L572:15 (fire))<br />[/vs/workbench/browser/labels.ts#491:20 (render)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/browser/labels.ts#L491:20 (render))<br />[/vs/workbench/browser/labels.ts#303:8 (notifyFileDecorationsChanges)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/browser/labels.ts#L303:8 (notifyFileDecorationsChanges))<br />[/vs/workbench/browser/labels.ts#139:108](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/browser/labels.ts#L139:108)<br />    at Array.forEach (<anonymous>)<br />[/vs/workbench/browser/labels.ts#139:83 (call)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/workbench/browser/labels.ts#L139:83 (call))<br />[/vs/base/common/event.ts#88:116 (call)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/common/event.ts#L88:116 (call))<br />[/vs/base/common/event.ts#572:15 (fire)](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/common/event.ts#L572:15 (fire))<br />[/vs/base/common/event.ts#158:15](https://github.com/microsoft/vscode/blob/f06011ac164ae4dc8e753a3fe7f9549844d15e35/src/vs/base/common/event.ts#L158:15)<br />

**Comment by bpasero** [comment]
Note that this originates from `updateWidth` call.

**Comment by isidorn** [comment]
I simply now swallow the error since if the element is no longer there it's width does not need to updated. Yeah it is a bit sloppy since I am not actually sure when this happens in practice.
