### ISSUE TITLE
Clone editor into an existing group

### ISSUE THREAD

**Issue by vojtechkral** [microsoft/vscode#79707]
I would like to be able to "clone" an existing open file from one group to another.
That is, I'm editing a file and at some point I would like to have a look at some other section of the same file simultaneously side-by-side.

Basically the same thing as split, but without creating a new group. Also the same thing as move but without closing the editor in the original group.

I believe this was asked in #46758 but got closed as duplicate of #41289. I don't think it is really a duplicate of #41289 - that's a different thing, they want a file open multiple times _in the same group_.

Today, I work around this by sequence of two commands:

1. Split the current file
2. Move the new editor from the new group into the other pre-existing group

That basically does what I'd like to do, but it would be great if this could be done with one keyboard shortcut.

Thank you!

**Comment by plwalsh** [comment]
@bpasero Any chance this issue could be reopened/reevaluated? I have the exact same use case as the OP, and perform the exact same sequence of steps as a workaround. I couldn't find any other open issues describing this problem/request. And I agree with the OP that the original issue #46758 was not actually asking the same thing as #41289, for which it was closed as a duplicate of.

**Comment by iwifigame** [comment]
Try this.
```
    {
        "key": "ctrl+alt+shift+left",
        "command": "runCommands",
        "args": {
            "commands": [
                "workbench.action.splitEditorLeft",
                "workbench.action.moveEditorToLeftGroup",
            ]
        },
    },
    {
        "key": "ctrl+alt+shift+right",
        "command": "runCommands",
        "args": {
            "commands": [
                "workbench.action.splitEditorRight",
                "workbench.action.moveEditorToRightGroup",
            ]
        },
    },
```
