### ISSUE TITLE
Privacy: Telemetry user preferences being ignored for new workspaces/folders.

### ISSUE THREAD

**Issue by about-code** [microsoft/vscode#79703]
- VSCode Version: VSCode-OSS v1.36.0 built from commit 0f3794b38477eea13fb47fbe15a42798e6129338 *(HEAD -> 1.36.0, tag: 1.36.0)*
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open User preferences 
1. Disable all @usesOnlineServices and telemetry
1. Close VSCode
1. Open VSCode
1. Open Folder... on a new empty folder
1. Open Workspace preferences 
1. Find out: Some online services such as Telemetry and Experiments and NPM fetching are enabled again ... and will be enabled again for each (new) *Open Folder...* or *New workspace* without a `.vscode/settings.json`

Does this issue occur when all extensions are disabled?: Yes

**As a user if I *do not* want to send telemetry and *do not* want to use online services I *do* want this globally as a user!** I *do not* want to have this silently enabled again when starting a new project, opening a new folder or workspace without *workspace settings*.

Such behavior

1.  ...[violates the official Microsoft privacy statement](https://privacy.microsoft.com/en-us/privacystatement) which states
   
   > *When we process personal data about you, we do so with your consent* [[Microsoft](https://privacy.microsoft.com/en-us/privacystatement)]

2. ...is contrary to the official documentation on disabling telemetry as given under [code.visualstudio.com](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting).

3. ...is contrary to the information given by Microsoft developer @joaomoreno in the past (https://github.com/microsoft/vscode/issues/47513#issuecomment-380516308) where he stated

> Telemetry is opt out. Once opt out, it is always off though, regardless of whether you get an update.

For the moment I treat this as a bug and *strongly* suggest to

Either: 
- **do not** make those settings workspace-specific

OR
- **do** initialize new folders/workspaces with global user settings

*On the left: User settings. On the right: workspace settings as they appear with a newly opened (empty) folder. Workspace default options marked with "Modified in: User" (right) do in fact not reflect user settings (and have *not* been enabled manually for a fake screenshot, of course)*

![user_settings_ignored](https://user-images.githubusercontent.com/6525873/63589688-13deee00-c5aa-11e9-9e6b-8edb3d9500f4.png)

**Comment by RMacfarlane** [comment]
@about-code I believe that user settings you have set are still being respected, but that the workspace settings UI is confusing in this case. If you use `F1` -> `Developer: Set Log Level`, another channel will be added to the `Output` panel called `Log (Telemetry)`, which can be used to see all telemetry events recorded by VSCode.

Workspace settings should only override user settings if they have been explicitly set. So since you have changed these in user settings but have not touched workspace settings, they should continue to be applied. The "Modified in" tag appears next to a setting when it is being overwritten from another scope. You would also see this tag if you changed something in workspace settings, and then set the same setting in user settings.

@roblourens I'm wondering if changing the wording of the tag would help clarify this. "Modified in: x" makes it clear that the setting is also configured somewhere else, but at least to me, doesn't immediately suggest that the setting in x is taking precedence. Is my understanding of when it shows up correct?

**Comment by RMacfarlane** [comment]
Oh, actually I guess "Modified in" does actually just indicate that it's been changed somewhere else, not precedence. Would it be possible to render something in addition to "Modified in" indicating which value is being read from?

**Comment by about-code** [comment]
> I believe that user settings you have set are still being respected, but that the workspace settings UI is confusing in this case. If you use F1 -> Developer: Set Log Level, another channel will be added to the Output panel called Log (Telemetry), which can be used to see all telemetry events recorded by VSCode.

Thank you for that hint. From what I see in the log window there were no obvious telemetry events in the short period I was watching and interacting a bit with vscode. But I am still not convinced whether it's just a UI only thing. I may explain how I actually come to check those workspace settings again after a while: 

I ran vscode in some kind of a "paranoid mode", that is, with a system group I have forbidden to access internet. After I closed VSCode I saw a VSCode process left stuck, probably since it couldn't finish without internet access. The process had a shell child process with an `npm install command` obviously trying to update some typings from npm.

What bothers me is this `--enableTelemetry` option in its command line. Not sure whether it means *collecting telemetry* or just enabling a feature which respects telemetry settings, though. But I wouldn't expect such a command line and child process given my user preferences. I could also see a tsserver.js process running with `--enableTelemetry` before closing the window. *Then* I checked those workspace settings and saw that they were enabled despite my user settings.

```
    1 13926 13322 13322 ?           -1 Sl    1000   0:00 REDACTED/VSCode-linux-x64/code-oss REDACTED/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation REDACTED.cache/typescript/3.5 --enableTelemetry --typesMapLocation REDACTED/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
13926 13935 13322 13322 ?           -1 S     1000   0:00  \_ /bin/sh -c npm install --ignore-scripts types-registry@latest
13935 13936 13322 13322 ?           -1 Sl    1000   0:01      \_ npm
```

**Comment by RMacfarlane** [comment]
Got it, thanks for the additional context.

This looks like the command typescript uses to get typings, it can also be disabled using the "Typescript: Disable Automatic Type Acquisition" setting. (Looking at your screenshot of user settings, to be completely offline, you would also want to check "Extensions: Show Recommendations Only On Demand" setting). @mattbierner do you know any more about this process and what `--enableTelemetry` would mean there?

**Comment by roblourens** [comment]
The settings GUI doesn't represent the real settings model precisely. It's hard to tell the user what setting is being applied right now when you consider multiple folder settings, language-specific overrides, etc. In cases like this I just try to point the user at what is happening, but the real source of truth is in the json files. Sorry for the confusion!

**Comment by roblourens** [comment]
That TS process should be respecting the vscode telemetry setting because it processes telemetry the same way that other extensions do. But maybe it would be good to not add that flag to the process unless telemetry is enabled to avoid confusion.

**Comment by mjbvz** [comment]
The enableTelemetry flag tells the tsserver to send telemetry events back to the vscode process which then can upload it or not based on the actually telemetry user setting. The tsserver does not upload anything on its own. 

The typing install process uses npm. The process itself also does not any collect telemetry on its own but talks to an online service (your npm repository) which may

**Comment by mjbvz** [comment]
@roblourens Is there an actual bug here or can we close the issue?

**Comment by roblourens** [comment]
I think it would be good to not add the `--enableTelemetry` flag when the setting for telemetry is disabled, if possible.

**Comment by mjbvz** [comment]
Ok, we also use the TypeScript telemetry events to do stuff that is not uploaded (such as getting the real running ts version instead of guessing at it). The flag's name could have been clearer but it would be annoying to change the name now without a good reason to do so

I'm closing this since it sounds like the issues were: initially unclear ux and a misunderstanding of what the ts extension is doing related to telemetry/npm

**Comment by about-code** [comment]
> I'm closing this since it sounds like the issues were: initially unclear ux and a misunderstanding of what the ts extension is doing related to telemetry/npm

@mjbvz I can accept to stop the discussion about the telemetry and privacy matter. But this might be just a special case of the issue I think. What added to the confusion is the following: I have disabled *all* options for *@usesOnlineServices* including e.g. the option 

> ***Npm**: Fetch online package info*.  

When all those options are disabled I really expect *no* attempts to connect to an online service. But this means, there shouldn't be this `npm install` command being launched in the background upon initializing typescript tooling (no matter if there's a telemetry command line option or not).

**Comment by about-code** [comment]
@RMacfarlane

You're right: **TypeScripts** *Automatic Type Acquisition** option is enabled. So then it seems the solution to the issue is to add this to *@usesOnlineServices*.

**Comment by about-code** [comment]
@RMacfarlane is right. I did not check the options *Disabling Automatic Type Acquisition* and *Recommendations on Demand* which have to be enabled to become offline - contrary to all the others. Well: very unfortunate UX but also my fault of not reading carefully enough - have to admit that. Sorry to have bothered everyone with this.
