### ISSUE TITLE
Regression with fenced markdown blocks and injection grammars

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#79705]
Like the TypeScript extension, the Haxe extension [injects](https://github.com/vshaxe/vshaxe/blob/master/package.json#L927-L955) its grammar into markdown code blocks, and then also injects the markdown grammar into its own doc comments. This allows syntax highlighting like this:

![](https://i.imgur.com/BnyNzed.png)

This screenshot is from VSCode 1.34 after which point something seems to have broken / changed. Starting with VSCode 1.35, the `@param` after the code block is no longer highlighted (even though there were no changes in any of the grammars involved):

![](https://i.imgur.com/WjwhomK.png)

Evidently, it doesn't consider the fenced markdown block closed:

![](https://i.imgur.com/J5WOVUf.png)

---

Source for easy copy-paste:

```haxe
class Main {
	/**
		```haxe
		trace("Test");
		```
		@param foo bar
	**/
	static function main() {}
}
```

**Comment by mjbvz** [comment]
VS Code does not include a haxe grammar so please file this against the haxe extension. Even if our markdown grammar change in some way, that extension need to investigate the issue

**Comment by Gama11** [comment]
I'm one of the maintainers of the Haxe extension. ;) Anyway, I take it you want some isolated sample project to reproduce?

**Comment by mjbvz** [comment]
Yes, you need to debug this. If a fix to the markdown grammar is required, please submit a pr

**Comment by Gama11** [comment]
I managed to identify the breaking commit by building VSCode from source and running `git bisect`:

>https://github.com/microsoft/vscode/commit/f0ba210ef93504af548442b7428dc25ebab91e2e - _Add support for vscode-textmate in the browser_

This seems to be a fairly big refactor in / around vscode-textmate and unrelated to the markdown grammar, so not sure where to go from here (cc @alexandrudima).

**Comment by alexandrudima** [comment]
@Gama11 `vscode-textmate@4.2.1` did contain quite a number of changes. I wonder if https://github.com/microsoft/vscode-textmate/pull/88 is the root cause for the change in behaviour here...

Would it be possible for you to extract a standalone example that we could debug for `vscode-textmate`? Given the similarities, I wonder why TS did not get broken by `vscode-textmate@4.2.1` in the same way as Haxe ?

**Comment by Gama11** [comment]
@alexandrudima Yeah, good question what the difference between TS and Haxe is here. I'll work on making a small sample extension.

@matter123 Yeah, this seems to be about vscode-textmate 4.0.1 -> 4.1.1.

**Comment by alexandrudima** [comment]
Oh, ok, I misread the version numbers. Do you happen to use `\G` ? `vscode-textmate` had some bugs around that which were fixed around that time-frame...

**Comment by alexandrudima** [comment]
Here are the nitty-gritty details -- https://github.com/microsoft/vscode-textmate/pull/85

**Comment by Gama11** [comment]
Here's an isolated example: https://github.com/Gama11/vscode-issue-79705

It still involves three grammars:

- the language grammar itself
- a grammar to inject it into markdown code blocks based on this official example, though I see there's since been a few changes to it: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
- a grammar to inject markdown into doc comments of the language, based on https://github.com/microsoft/vscode/blob/master/extensions/typescript-basics/syntaxes/jsdoc.injection.tmLanguage.json

While isolating it, I came across something interesting. If the closing triple backticks are right at the start of the line, they still manage to close the fenced markdown code block:

Not working:

![](https://i.imgur.com/FLHHApy.png)

Working:

![](https://i.imgur.com/wh4FoTu.png)

It would seem logical that [this regex](https://github.com/Gama11/vscode-issue-79705/blob/3361904a97a5b49b6baf3d49151e1cec39565fbd/haxe-markdown.tmLanguage.json#L11 ) is responsible:

```json
"end": "(^|\\G)(?=\\s*[`~]{3,}\\s*$)"
```

I've played around with it a bit, but I feel like I don't understand `\G` / the changes to it well enough to figure out why it no longer works.
