### ISSUE TITLE
Scrollbar out of style for extension descriptions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7970]
1. Open an extension description
2. Notice the native scrollbar which looks out of style since we do not use it anywhere else in VSCode
3. I would expect our regular scroll bar which we use everywhere else (also for markdown preview)

![screen shot 2016-06-22 at 09 50 23](https://cloud.githubusercontent.com/assets/1926584/16258599/db95e750-385e-11e6-8971-08852af7e468.png)

**Comment by joaomoreno** [comment]
You are like an eagle 🐦

**Comment by isidorn** [comment]
Also looks horrible on linux + the other scroll bar should get hidden

![screen shot 2016-06-22 at 10 51 37](https://cloud.githubusercontent.com/assets/1926584/16260356/5c267274-3867-11e6-887b-971ea31db3d4.png)
