### ISSUE TITLE
Support Function overloading in JSDoc comments

### ISSUE THREAD

**Issue by nveenjain** [microsoft/vscode#79702]
I was trying to write an overloaded function using JSDoc, but VSCode only shows the first variation that i wrote only.

```js
  /**
   * @function
   * @name set
   * @param {Object} key to set in update
   * @return {Number} representing the ID
   *
   */ /**
   *
   * @function
   * @name set
   * @param {String} key to set name in the Query
   * @return {String} Showing the name
```
The suggestion shown in Intellisense is key as an object...
Expected behavior is that vscode shows 2 option/variations for the function set, similar to what is shown when we use declare statement twice for any function in TypeScript.

I would love to work on this issue, if someone can guide me.

**Comment by mjbvz** [comment]
VSCode's javascript intellisense is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
