### ISSUE TITLE
Vscode always asks for which formatter to use when I've set a default formatter for that language

### ISSUE THREAD

**Issue by maple3142** [microsoft/vscode#79706]
Issue Type: <b>Bug</b>

Demonstration video: https://streamable.com/zvkn4

I've set prettier as the default formatter for javascript language, but it always me which formatter to use when I select "format".

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-checkbox|bie|0.1.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
vsc-travis-ci-status|fel|1.1.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
terminal|for|0.0.10
vscode-yarn|gam|1.6.0
webpack-snippets|gog|0.0.4
vue-snippets|hol|0.1.11
minify|Hoo|0.4.3
rest-client|hum|0.22.0
vscode-cheerio|jas|1.1.0
webpack|jer|2.1.3
nearley|kar|1.0.3
vscode-fix-checksums|leh|1.1.0
g-translate|map|0.0.2
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.13
vscode-attrs-sorter|mrm|2.1.0
vscode-jade-snippets|mrm|1.0.1
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
cpptools|ms-|0.25.0
debugger-for-chrome|msj|4.11.7
vetur|oct|0.22.2
material-icon-theme|PKi|3.8.1
polacode|pnp|0.3.2
vscode-graphql|Pri|0.2.1
ejs-language-support|Qas|0.0.1
quicktype|qui|12.0.46
vscode-yaml|red|0.5.1
LiveServer|rit|5.6.1
background|sha|1.1.20
code-settings-sync|Sha|3.4.2
gitconfig|sid|2.0.0
language-stylus|sys|1.11.0
nativescript-xml-snippets|tsv|1.0.7
ws-rainmeter|wil|0.2.7
markdown-all-in-one|yzh|2.4.2
swig|zhu|0.0.5
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by RMacfarlane** [comment]
Hi @maple3142, there are actually two different commands for format document - `Format Document` and `Format Document With...`. The second one will always ask you to choose a formatter, the first one will use whatever is configured as the default formatter. Now that you've set the default, you can use `Format Document` to avoid being asked which formatter to use. Sorry for the confusion!
