### ISSUE TITLE
Toggle comment shortcut does not work

### ISSUE THREAD

**Issue by maks-ym** [microsoft/vscode#79708]
Issue Type: <b>Bug</b>

"Ctrl+/" does not work but 'toggle block comment' works fine.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic snap

**Comment by RMacfarlane** [comment]
@maks-ym I'm having trouble reproducing this, can you double check your keybindings to see if anything is conflicting with it? `F1` -> `Preferences: Open Keyboard Shortcuts` -> search for `"ctrl+/"`
