### ISSUE TITLE
Drag and Drop feature on editor not functioning as expected.

### ISSUE THREAD

**Issue by vixson** [microsoft/vscode#79701]
Issue Type: <b>Bug</b>

When dragging a code on the editor it refuses to drop on the desired position of the cursor.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.1
npm-intellisense|chr|1.3.0
line-counter|dol|0.5.2
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.8
vsc-material-theme|Equ|30.0.0
git-project-manager|fel|1.7.1
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
vscode-angular2-emmet|jak|2.0.3
docthis|joe|0.7.1
font-awesome-codes-html|med|0.0.7
Angular-BeastCode|Mik|8.0.10
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
linesinfostatusbar|pet|0.0.3
material-icon-theme|PKi|3.8.1
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.2
vsfire|tob|1.4.1
errorlens|use|2.7.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by RMacfarlane** [comment]
@vixson Can you explain a little more what you are doing? Where are you dragging the code/file from, and where are you dragging the code to? Did this work in previous versions of VSCode?

**Comment by vixson** [comment]
It seems the error was coming from an extension [*Error lens*](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens), [**Issue 26**](https://github.com/usernamehw/vscode-error-lens/issues/26).
