### ISSUE TITLE
User setting overrides Workspace's (search.followSymlinks)

### ISSUE THREAD

**Issue by gatopeich** [microsoft/vscode#79711]
Issue Type: <b>Bug</b>

I had disabled "search.followSymlinks" in User settings, and enabled it in Workspace settings.
The User setting overrides the Workspace's...

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3687)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.31GB (1.95GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
code-runner|for|0.9.14
beautify|Hoo|1.5.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
sublime-keybindings|ms-|4.0.3
vscode-yaml|red|0.5.1
vscode-make|tec|1.0.2
vscodeintellicode|Vis|1.1.9

</details>

**Comment by RMacfarlane** [comment]
@gatopeich Did you modify your workspace settings at all, or is it simply the default value? If the workspace setting isn't explicitly set, the user setting will still take precedence.
