### ISSUE TITLE
Allow empty search with value in "files to include" to generate search results of all files with a name/pattern

### ISSUE THREAD

**Issue by patridge** [microsoft/vscode#79716]
If I'm working through a bunch of identical or similarly named files, I would love to be able to search for them and see them in the search result list as I work through them. It would be great be able to submit an empty search when I have provided a **files to include** value/pattern (as well as maybe a value in **files to exclude**.

This is similar to the [request to match filenames in search results](https://github.com/microsoft/vscode/issues/56757), but a different desired execution. As others mentioned there, quick open is not a good equivalent to the Search mechanism when that search system is the workflow you are trying to use. You would need to take a screenshot or be able to export those quick open results to another file to be able to reference them repeatedly and work through the list.

## Sample use case

For example, I am doing a bulk review of a bunch of index.yml files in a large project. I'm not looking for anything specific to actual use as a search term. I just need to open them all and scan them, making any changes as I go. If I could do that in the search panel, I could remove search results as I review them (like a to-do list).

**Comment by roblourens** [comment]
This is an interesting idea. I can't decide whether it would be expected behavior or not. You could get this behavior by doing a search for a regex like `(.|\n)*`.

**Comment by skprabhanjan** [comment]
@roblourens , Can I take this up ?
