### ISSUE TITLE
Custom Emmet php snippets does not work inside php code or in php island within html file.

### ISSUE THREAD

**Issue by romanzmykulova** [microsoft/vscode#79710]
Custom php snippets does not work inside php code or in php island within html file.

- VSCode Version: 1.37.1
- OS Version: Windows 10

Steps to Reproduce:

1. Add custom php snippets
```
{
  "html" {
    "snippets": {
        "php": "<?php ${1} ?>"
    },
  "php": {
    "snippets": {
        "php": "?> ${1} <?php"
    }
  }
}
```

2. start new php or html file and type `php` and tab, it will output rightly `<?php ?>`, but then inside that created php island if you type again "php + tab", you will end up with `<?php <?php ?> ?>`, but it should be `<?php ?> <?php ?>`

**Comment by roblourens** [comment]
> Add custom php snippets


How are you doing that exactly? The file you posted doesn't seem to match the format of a normal global snippet file, so I'm not sure where you are putting it. But if I set up snippets then I can't reproduce this.

Also I would only expect this to work in a php file, not an html file.
