### ISSUE TITLE
Hangs while scrolling

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#79715]
Issue Type: <b>Bug</b>

While scrolling through any file the scrolling randomly stops and then resumes. The activity monitor shows Code Helper CPU increased, often above 20 %, and then drops back. 
 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-generate-getter-setter|DSK|0.5.0
vscode-surround|Swo|1.0.1
html-snippets|abu|0.2.1
Bookmarks|ale|10.5.0
vscode-multi-line-tricks|big|0.0.3
vscode-raml|blz|3.0.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
quick-html-previewer|dai|1.0.0
mustache|daw|1.1.1
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|9.9.3
remotehub|eam|0.5.0
restore-editors|eam|0.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
vscode-nupkg|eri|1.0.1
json-tools|eri|1.0.2
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|1.8.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
macros|ged|1.2.1
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
typelens|kis|1.9.1
csharpfixformat|Leo|0.0.84
git-tree-compare|let|1.7.0
dotnet-core-commands|mat|1.0.6
git-graph|mhu|1.13.0
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
cpptools|ms-|0.25.0
csharp|ms-|1.21.1
Go|ms-|0.11.4
sublime-keybindings|ms-|4.0.3
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
debugger-for-ios-web|msj|0.1.2
chai-snippets|nwh|0.1.0
vetur|oct|0.22.2
vscode-code-outline|pat|0.2.1
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.8.1
vscode-css-peek|pra|3.0.2
typescript-hero|rbb|3.0.0
git-merger|sha|0.4.1
es6-mocha-snippets|spo|0.2.2
autoimport|ste|1.5.3
msbuild-project-tools|tin|0.2.55
pdf|tom|0.5.0
gitblame|wad|3.0.1
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by dfdumaresq** [comment]
Code Helper is spiking.
![image](https://user-images.githubusercontent.com/20051/63607736-129cc980-c588-11e9-9fa1-61ceccb11828.png)

![image](https://user-images.githubusercontent.com/20051/63607792-2fd19800-c588-11e9-9892-10fd27093b57.png)

![image](https://user-images.githubusercontent.com/20051/63607807-3a8c2d00-c588-11e9-8c39-11192d261ea5.png)

**Comment by RMacfarlane** [comment]
@dfdumaresq Can you open the process explorer (`F1` -> `Developer: Open Process Explorer`) and see which process is spiking when this happens?

**Comment by dfdumaresq** [comment]
Hi @RMacfarlane - I've since deleted some old dotnet sdks and it seems to have cleared up the issue.
