### ISSUE TITLE
Clicking on a markdown preview does not set focus on editor

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7971]
1. Open markdown preview of a file
2. Click somewhere else so your editor loses focus
3. Click somewhere in the markdown preview - notice how the editor does not gain focus. If you click on its tab header the editor nicely gains focus
4. Clicking on the editor should always give it focus

This is now more visible since we show extensions description using a markdown preview.
fyi @joaomoreno

**Comment by bpasero** [comment]
@isidorn please file markdown issues against @kieferrm

**Comment by kieferrm** [comment]
I can not reproduce the issue any longer.
