### ISSUE TITLE
Add setting to hide sync icon on Source Control Status Bar

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#79714]
This icon:

![2019-08-23 at 16 51](https://user-images.githubusercontent.com/6391776/63605636-44cd1c00-c5c6-11e9-8131-83c192b07858.png)

I don't ever press on the activity bar and thus only want it to show visual information.

Can you please add a setting to hide this `sync` icon?

Thank you.

**Comment by IllusionMH** [comment]
Currently it is part of "Source control" status bar element. If you don't care about branch name you can just right-click on it and pick "Hide".

**Comment by nikitavoloboev** [comment]
I do care about the branch name. That's the issue. The sync icon is part of the branch name.
