### ISSUE TITLE
Node debugger fails with the error message "Cannot find debug adapter for type 'node'"

### ISSUE THREAD

**Issue by azlochevsky** [microsoft/vscode#79726]
Node debugger fails with the error message "Cannot find debug adapter for type 'node'".
The VSCode Version:

Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
@azlochevsky Please make sure that both the "Node Debug" and "Node Debug (legacy)" extensions are enabled:

<img width="554" alt="2019-08-26_01-04-06" src="https://user-images.githubusercontent.com/1898161/63657093-8106a500-c79d-11e9-8768-113c3f718cc6.png">
