### ISSUE TITLE
Zoom levels are not only changed by 1 but also rounded to integer

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#79723]
I know the request for finer zoom increments/decrements has been done in the past. This is a completely different issue and I consider it to be a bug report, not a feature request.

If the user sets a "home" zoom level that is not an integer (which is a reasonable use case since many things in the GUI are not easily resizable and since integer increments are a coarse 20%) it should be preserved as a comfortable setting to return to. I would say typical usage of zoom level is to stay in your preferred size except for some temporary zoom-in and out again. Currently this use case is broken, instead you have to edit your config file by hand each time, which is unacceptable.

There is this old closed issue requesting exactly the opposite but go figure why, there is no rationale there: https://github.com/microsoft/vscode/issues/15877

- VSCode Version: 1.37.1
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Set  `"window.zoomLevel": 0.4`
2. Press `Ctrl-+`: you get 1, not 1.4.
3. Press `Ctrl--`: you get 0, not 0.4.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
I actually wrote smth for this:

https://marketplace.visualstudio.com/items?itemName=usernamehw.run-commands-view

```json
{
	"key": "ctrl+=",
	"command": "run-commands-view.incrementSetting",
	"args": {
		"setting": "window.zoomLevel",
		"value": 0.5
	}
},
{
	"key": "ctrl+-",
	"command": "run-commands-view.decrementSetting",
	"args": {
		"setting": "window.zoomLevel",
		"value": 0.5
	}
},
```

**Comment by memeplex** [comment]
Hi @usernamehw that's great, I will give it a try.

Anyway, I think it's a more sensible default behavior to honor the base zoom level. For users that start at 0 (the default) the behavior would be the same than it's now. For users that deliberately change the zoom level in their settings, it's hard for me to figure out a reason why they would want the sequence `C-+` `C--` to truncate zoom to 0 instead of behaving like an "identity". It's not only cumbersome to reset their "home zoom" each time, but also counterintuitive that `C-+` and `C--` aren't inverses of each other. Besides, it's weird that, for example, a first jump up from 0.5 to 1 is just half the second jump up from 1 to 2.
