### ISSUE TITLE
Test: String-of-Array error messages

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79722]
Refs: #77459

- [x] anyOS @bpasero
- [x] anyOS @alexandrudima

Complexity: 1

Description: We now show error message for invalid string-of-array settings in the Settings GUI. For example, for this contributed setting:

```json
"type": "array",
"maxItems": 4,
"minItems": 1,
"items": {
	"type": "string",
	"enum": [
		"error",
		"warning",
		"info",
		"hint"
	]
}
```

We would show such warning when you have invalid values:

![image](https://user-images.githubusercontent.com/4033249/63620499-4555ba80-c5a6-11e9-98c5-7d3e3025ed4c.png)

Please test by creating an extension that contributes a setting, and then use the GUI settings editor to configure it. Specify one or multiple of such constraints:

- `minItems`
- `maxItems`
- `item.enum`
- `item.pattern`

Then input invalid values. Test that the error message widget works fine and the error messages make sense to you.

You can find more about these JSON schema keys here: https://json-schema.org/latest/json-schema-validation.html.

**Comment by alexandrudima** [comment]
@octref If the steps include creating an extension, then the complexity cannot be 1. An item with complexity 1 should at most consist of clicking (maybe not even touching the keyboard).

**Comment by bpasero** [comment]
@octref should an enum with multiple same values result in just one error message?

E.g. 

```json
"enum": [
  "error",
  "error"
]
```

Shows:
![image](https://user-images.githubusercontent.com/900690/63774248-25dbcc00-c8dd-11e9-88ff-028baff3d79b.png)
