### ISSUE TITLE
Git: Allow programmatic focusing of repository 

### ISSUE THREAD

**Issue by jhechtf** [microsoft/vscode#79720]
For workspaces with multiple repositories, would it be possible to show a specific repository when opening the SCM panel? As of right now the only whatever repository is set as the first repository shows up, and in all my searching I have not found a way to show a specific one.

For example, if a repository is setup as 

```
main
- front-end
- back-end
- database
``` 

if I run `executeCommand('workbench.view.scm')` it will show the SCM pane for main. 

## Possible solutions
On the Repository object, perhaps adding a `focusInScmPane()` method? Otherwise, a parameter for the workbench view command?

Apologies if this already exists, but I scoured through code and couldn't find anything.

**Comment by joaomoreno** [comment]
Feel free to submit a PR. Maybe the best would be to expose an ID (or similar) on the Repository object and then add that a parameter to the workbench view command.

**Comment by jhechtf** [comment]
I would love to, I only ask if you could give me some direction on where the code for that command is located at? That was my first idea, I just couldn't find the source of that command.

**Comment by joaomoreno** [comment]
Sorry @jhechtf, closing this as out of scope.

**Comment by jhechtf** [comment]
I'd be happy to do it and set a merge request, I just cannot find where the given command is located.
