### ISSUE TITLE
Various octicons are incorrect

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/vscode#79725]
Issue Type: <b>Bug</b>

A number of the octicons are incorrect in the insiders build.

person-filled: ![image](https://user-images.githubusercontent.com/4324725/63627198-56f58d00-c5bb-11e9-9456-14bac8a97a38.png)

organization-filled: 
![image](https://user-images.githubusercontent.com/4324725/63627222-6f65a780-c5bb-11e9-9d9a-d131f6522322.png)

Not sure if these are the only ones.

VS Code version: Code - Insiders 1.38.0-insider (0f73473c08055054f317c1c94502f7f39fdbb164, 2019-08-23T05:39:22.818Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (36.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Since this has a bug label, removing verification-needed which is only for features.
WHile I am here what are the steps to verify? Where do we actually use those icons?

**Comment by isidorn** [comment]
Hmm I get this. WHich I think are just updated icons -> verified

![Screenshot 2019-08-27 at 18 08 25](https://user-images.githubusercontent.com/1926584/63788393-b0302a00-c8f5-11e9-9fca-1e1cbb80e46f.png)

**Comment by isidorn** [comment]
Yeah with that setting I get good icons 
![Screenshot 2019-08-28 at 10 45 45](https://user-images.githubusercontent.com/1926584/63840249-08603e00-c981-11e9-97c3-05de4ad0bc53.png)
