### ISSUE TITLE
Install the extension marketplace story needs update

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7973]
1. Most of the extensions currently have a description on how to install that extension (by opening quick open and pasting some commands) - example: https://marketplace.visualstudio.com/items?itemName=mousetraps.quicksnippet#review-details
2. Due to the introduction of the extension viewlet all those install descriptions become depracted

So we should somehow notify the extension writers that this description needs to change.

Also it would be cool if the user could just click on a link in that description and vscode would automatically start downloading that extension.

**Comment by joaomoreno** [comment]
I will keep the `ext install foo` and redirect the user to the viewlet for now.

**Comment by gerane** [comment]
I don't see why you don't have both. I still want to be able to install and search extensions via command palette, but would sometimes like to use the other view.
