### ISSUE TITLE
platform-specific configuration does not support object-type arg in tasks.json

### ISSUE THREAD

**Issue by alexzshl** [microsoft/vscode#79738]
Issue Type: <b>Bug</b>

I am not sure if this is a problem

platform-specific configuration does not support object-type arg in tasks.json

**error**
![](https://i.loli.net/2019/08/24/MLvsmEDNf7hQFoV.png)

**tasks.json template**

```json
{
    "tasks": [
        {
            "type": "shell",
            "label": "test",
            "command": "echo",
            "args": [
                "arg1",
                {
                    "value": "arg2",
                    "quoting": "escape"
                }
            ],
            "windows": {
                "command": "move",
                "args": [
                    "file",
                    {
                        "value": "dest",
                        "quoting": "escape"
                    }
                ]
            },
            "options": {
                "statusbar": "show"
            },
            "group": "test"
        }
    ],
    "version": "2.0.0"
}
```

In addition, the api - "vscode.tasks.fetchTasks()" returned the correct result 
![](https://i.loli.net/2019/08/24/VWuNkYTCKtxU7JH.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.11.3
bat-snippets|bat|0.2.0
watch-run|bou|0.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.1
gitlens|eam|9.9.3
vsc-material-theme|Equ|30.0.0
awesome-vjass-support|Fak|0.0.92
php-pack|fel|1.0.2
code-runner|for|0.9.14
triggertaskonsave|Gru|0.2.9
vscode-peacock|joh|3.1.4
quicktask|lky|3.5.4
MagicPython|mag|1.1.0
theme-monokai-pro-vscode|mon|1.1.13
vscode-language-pack-zh-hant|MS-|1.37.5
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
cpptools|ms-|0.25.0
Go|ms-|0.11.4
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
gulptasks|nic|1.3.1
material-icon-theme|PKi|3.8.1
view-in-browser|qin|0.0.5
java|red|0.47.0
vscode-yaml|red|0.5.1
vs-picgo|Spa|2.0.4
guides|spy|0.9.3
lua|sum|0.11.5
vscode-gulp|tan|0.0.4
ayu|tea|0.18.0
pdf|tom|0.5.0
highlight-matching-tag|vin|0.9.3
vscode-java-debug|vsc|0.20.0
markdown-all-in-one|yzh|2.4.2
livereload|zii|0.2.5

(12 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Looks like a problem with the schema.
