### ISSUE TITLE
Strange characters appear when copying variables

### ISSUE THREAD

**Issue by JINxo-geek** [microsoft/vscode#79732]
- VSCode Version: 1.37.1
- OS Version:MacOS 10.14.6 

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/26448864/63631142-f49d9a80-c655-11e9-9ddd-f34c83990e58.png)
![image](https://user-images.githubusercontent.com/26448864/63631152-0da64b80-c656-11e9-8ebb-6f38c8230cd0.png)
![image](https://user-images.githubusercontent.com/26448864/63631158-1d259480-c656-11e9-9c3e-4b1074aeb3b9.png)

All of a sudden special characters appear in a variable name and are not visible in VSCode。

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@JINxo-geek Can you please provide repro steps?
