### ISSUE TITLE
Can not jump to member's definition

### ISSUE THREAD

**Issue by huanhexiao** [microsoft/vscode#79737]
I use vscode on Ubuntu18.04
i can jump to memeber's definition only as code is just opened,  it's not working after some while

**Comment by RMacfarlane** [comment]
@huanhexiao What version of vscode are you using? What language are you programming with?

**Comment by huanhexiao** [comment]
my code is the latest version, 1.37.1
i use C++

**Comment by huanhexiao** [comment]
> @huanhexiao What version of vscode are you using? What language are you programming with?

my code is the latest version, 1.37.1
i use C++

**Comment by huanhexiao** [comment]
i think it's an issue about the OS, i tested it on Ubuntu 16.04, everything is Ok
