### ISSUE TITLE
Preview of any thing is not working

### ISSUE THREAD

**Issue by kr-pankaj** [microsoft/vscode#79746]
**When i am pressing ctrl + shift + p it is showing the list in that list when i am choosing ionic preview and html preview no one is working .. no one is showing the preview of the code. in the previous version it was working but now it is not working.**

**Comment by RMacfarlane** [comment]
@kr-pankaj What extensions do you have installed/which extensions add the "ionic preview" and "html preview" commands?

**Comment by kr-pankaj** [comment]
Thanks for replying. As for ionic preview i have installed Ionic Preview
and for html, Live HTML Previewer.
Please find the screenshot attached below for your reference.

*Thanks & Regards*
*Chandrakant*
