### ISSUE TITLE
Keyboard shortcuts editor context menu option name change

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#79747]
When in the keyboard shortcuts UI editor, if you right click on a rule to bring up the context menu, you get options for modifying both the keybinding and the "when" context clause.

"Change Keybinding" and "Change When Expression" are appropriately named.

But it seems like the options that affect _both_ the keybinding _and_ the "when" clause should be renamed. Possibly changing "Remove Keybinding" to "Remove Rule" and changing "Reset Keybinding" to "Reset Rule".

**Comment by sandy081** [comment]
I see your point but I think current names are intuitive and good enough. So I am sorry that the change will not be considered.
