### ISSUE TITLE
Revisit label service usages for memoizing results

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79742]
I think recently we changed `FileEditorInput` to no longer cache the result of name and description but to always compute it when needed. It seems the label service has become quite complex with regards to finding the correct formatter. 

My assumption is that a label will only change if more formatters get registered, so can we maybe restore the cached labels and flush them when formatters change? This could even become a utility thing that everyone can adopt that wants this kind of caching.

The rationale here is that with many editors open, there can be a lot of calls to this service and I worry we do a bit too much each time because we do not trust the previous result.

**Comment by isidorn** [comment]
Yes, we changed the FileEditorInput to not cache the results.
Droping the cache on new formatters makes sense. Assigning to next milestone and debt week to investigate then.

**Comment by bpasero** [comment]
Thanks!
