### ISSUE TITLE
Support '.jsonc' file extension for files inside '.vscode'

### ISSUE THREAD

**Issue by kripod** [microsoft/vscode#79744]
Currently, parsers struggle to read JSON comments when coming across the '.json' extension. Using the '.jsonc' extension implies that the given file is allowed to have comments, e.g.:

```
.vscode/extensions.json -> .vscode/extensions.jsonc
.vscode/settings.json -> .vscode/settings.jsonc
```

As a temporary workaround, a `.gitattributes` file like below could be used to signal GitHub's parser that files inside the '.vscode' directory use JSONC syntax:

```gitattributes
.vscode/*.json linguist-language=jsonc
```

**Comment by joaomoreno** [comment]
Closing this down. If this is useful, just create a PR for it and ping me in it.
