### ISSUE TITLE
Key binding error or docs... or operator...?

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#7974]
I'm getting the below message when using the key binding you can see in the same screenshot.

I took the 'command' from the docs at https://code.visualstudio.com/Docs/customization/keybindings

In this Insiders build, 'ctrl+shift+m` is mapped to `workbench.actions.view.problems`, and that does work, but is different action to the above. Has the above feature been withdrawn and replaced?

[image](https://cloud.githubusercontent.com/assets/512816/16259411/7d5d361a-385a-11e6-9f77-fd353c7883fe.png)

![image](https://cloud.githubusercontent.com/assets/512816/16259404/6b2aea8c-385a-11e6-8b21-898596bf9774.png)

**Comment by dbaeumer** [comment]
@sandy081 we should open the error list now. Right.

**Comment by sandy081** [comment]
@dbaeumer Yes Ctrl+Shift+M opens problems view. But, I changed the command id to ``workbench.actions.view.problems.`` I think, I should either revert/support the old command ``workbench.action.showErrorsWarnings``

**Comment by leegee** [comment]
FWIW, `workbench.action.showErrorsWarnings` is handy both for its limited scope, and that it is easy to close. (If `workbench.actions.view.problems` could easily be toggled that'd be great -- reaching for the mouse is such a stretch)

**Comment by sandy081** [comment]
@leegee There is a keyboard shortcut to toggle display of views in bottom bar - Ctrl + J (Just like Ctrl + B for toggling side bar views)

We are in the discussion of making views behavior consistent across. Side bar views and bottom bar views - See #7540

**Comment by leegee** [comment]
Thanks for the tip! I missed that one because I simply had to map CTRL+J to
'join lines' :-)
