### ISSUE TITLE
Cursur and Line feed

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#79749]
Issue Type: <b>Bug</b>

I press alt to use cursor edit multi lines, but it has two conditions. When the window's width is not wide enough (actually it does not change the line)it will be the picture one . I expect the pciture two.

![actual](https://user-images.githubusercontent.com/27731323/63641980-19dbe880-c6ea-11e9-948f-95e11c934df0.png)

picture one

![should](https://user-images.githubusercontent.com/27731323/63641982-22342380-c6ea-11e9-86b4-ad9812a340b9.png)
picture two

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.2.0
emojisense|bie|0.5.1
vscode-markdownlint|Dav|0.30.1
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.9.3
javac-linter|fau|1.3.1
vscode-lombok|Gab|0.9.8
java-properties|ith|0.0.2
docthis|joe|0.7.1
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
sqltools|mtx|0.20.2
aixcoder|nnt|0.1.12
vscode-spring-boot|Piv|1.10.0
java|red|0.47.0
vscode-xml|red|0.8.0
vscode-checkstyle|she|1.1.0
open-in-browser|tec|2.0.0
vscode-java-debug|vsc|0.20.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.2.0
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by alexandrudima** [comment]
Let's track in #26393
