### ISSUE TITLE
[question]: Can HTML previews fetch/XHR content from virtual document URIs?

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#7975]
I was very delighted to find out that HTML previews could run JavaScript, which is the whole reason my vscode-map-preview extension (https://github.com/jumpinjackie/vscode-map-preview) exists.

One of the questions I have, is that the HTML preview I generate with the extension is not so much content, but a combination of an interactive viewer "container" into the actual content that is also embedded into the same preview HTML.

One of the small annoyances is that I have to sanitize the document content for any unruly characters before embedding into the preview HTML so that the content doesn't break out of the ES6 template string that I have defined in the preview HTML script block for this content.

What would be nicer and cleaner for me is if instead of embedding the document content into the preview HTML, is if I could define a 2 virtual documents (with their own URI schemes):

 1. For the viewer "container" HTML 
 2. For the actual document content

Then HTML preview I generate from the 1st virtual document can fetch/XHR the content from, allowing for the graceful ability to handle failures in setting up the preview. Currently any failures in previewing content are mostly silent, and I would have to physically dump the preview HTML content out to a separate file in my extension code and open that up in Chrome to see what's wrong with it. 

Is this possible to make fetch/XHR inside a HTML preview work with virtual documents in vscode?

**Comment by jrieken** [comment]
No, that's currently not possible and I wouldn't know how to do that... The implementation uses loads the document in an iframe that runs out of process. 

What you can do (and other do that) is starting a server on local host which serves the actual document content.
