### ISSUE TITLE
Increase width of vertical scroll bar on integrated terminal

### ISSUE THREAD

**Issue by amithegde** [microsoft/vscode#79751]
It takes 3 seconds to get hold of vertical scroll bar on integrated terminal since it's too tiny as of now. Provide a way to make it larger. (similar to this: https://github.com/microsoft/vscode/issues/47888)

**Comment by Tyriar** [comment]
No plans to do this specific to terminal, it should be a workbench-level setting which is tracked in https://github.com/microsoft/vscode/issues/47888
