### ISSUE TITLE
Closing tag is not memorized anymore

### ISSUE THREAD

**Issue by Rc85** [microsoft/vscode#79755]
- VSCode Version: 1.37.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create a list by typing `[`. It should automatically create a closing tag of `]`.
2. Type some value in it, resulting in `['test', 'test']`.
3. Set your cursor somewhere else and then set it back just after the last `'test'`.
4: Type `]` and it will add another `]`, resulting in `['test', 'test']]`.

Details:

This happened right after I upgraded to 1.37.1. Prior to this version, if I type a closing bracket next to a closing bracket, it would recognize that there is a closing bracket and overwrite it with the same typed closing bracket.

**Comment by usernamehw** [comment]
#37315
