### ISSUE TITLE
Add feature to duplicate file or folder

### ISSUE THREAD

**Issue by shobhitchittora** [microsoft/vscode#79757]
Ability to duplicate multiple files and folders in the explorer would be such a delight. Inspired by other editors and mac itself, I'd like to take some votes and re-consideration on this.

<img width="269" alt="Screenshot 2019-08-25 at 1 57 28 PM" src="https://user-images.githubusercontent.com/4711855/63647542-66521300-c740-11e9-9644-d9a890399374.png">

PS: I think this could help on other platforms too. Though I'm not sure how this would pan out in windows or linux environments.

As this feature is being referenced by a lot of people and I'd like to know 

Some exiting issues on the same - 

#9345,  #58527, #38002, ...

**Comment by shobhitchittora** [comment]
Got a little ahead of myself and tried a crude implementation.

**Comment by jeanp413** [comment]
Just in case, in https://github.com/microsoft/vscode/issues/9345#issuecomment-234368464 is mentioned that there's an extension that already do this
https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate
