### ISSUE TITLE
Wrong separator in path when debugging c++

### ISSUE THREAD

**Issue by Green-Soybean** [microsoft/vscode#79756]
- VSCode Version: 1.37.1
- OS Version: Windows 10
- Mingw-w64 Version: 6.0.0

Steps to Reproduce:

1. VS code, C++ extension and Mingw-w64 are successfully installed.
2. Create a "hello world" C++ program in VS code and press F5 to debug.
3. ERROR INFO 
"Unable to start debugging. Unexpected GDB output from command "-environment-cd C:\\\\Users\\\\UserName\\\\Desktop\\\\test". C:\\\\Users\\\\UserName\\\\Desktop\\\\test: No such fire or directory."

I guess it is because the VS code passes the workspace directory with wrong separator to Windows Command, "\\\\" and "/" are both supported by VS code, but "\\\\" is not supported by Windows Command, I have also tried to modify the .json files, but it did not work. 

I don't know how to solve the problem, so I'd like to ask for help.

**Comment by brightest-dazes** [comment]
Me too

**Comment by dbaeumer** [comment]
@Green-Soybean can you please file the issue here https://github.com/Microsoft/vscode-cpptools against the vscode cpp extension.
