### ISSUE TITLE
Double click on editor tab to hide other editor groups

### ISSUE THREAD

**Issue by ratiw** [microsoft/vscode#79760]
Sometimes, when open many editor windows (or even editor group) on a notebook computer where screen real estate is very limited, to compare codes or other things, it would be really great if we can double-click on the editor tab at the top to temporary expand the editor to cover the entire window of VS Code for easier editing. And when press ESC key, it is going back to the previous layout.

Please note that this is not the same as the available Zen mode as Zen mode will still keep showing the editor group.

**Comment by isidorn** [comment]
When you say editor group, you actually mean the title area of the editor - where you can see the editor tabs, right?
So you would basically like Zen Mode to hide the title area if I understood this correctly?

**Comment by ratiw** [comment]
No, that's not what I mean. Let's see these screen shots and imagine that we are working on a 13" or 14" inch laptop. 

![image](https://user-images.githubusercontent.com/807017/63730455-8810de80-c895-11e9-8c86-b25deed20f6f.png)

Since the screen is quite small, everything will looks tiny unless we use Ctrl+plus to increase font size and everything will blow up like this.

![image](https://user-images.githubusercontent.com/807017/63730619-3a48a600-c896-11e9-9865-4b5c54577cfe.png)

In the above, picture you'll see 2 editor groups. In Zen mode, it just removes other things except all the editors, but it is still showing those 2 editor groups.

In my case, I would like to temporary switch a single editor tab to a full window by double-click on its editor tab (where it shows the file name) to work on it, so I can see everything more and clearer. Then when I'm finish I can just double-click on its tab again (or press ESC) to go back to the same arrangement and continue working on what I was doing previously.

![image](https://user-images.githubusercontent.com/807017/63731289-19358480-c899-11e9-99c6-9c34b02a019d.png)

![image](https://user-images.githubusercontent.com/807017/63731360-5732a880-c899-11e9-8ed0-ff18472a9c8a.png)

![image](https://user-images.githubusercontent.com/807017/63731430-a7aa0600-c899-11e9-8dd6-a1313346ea62.png)

**Comment by ratiw** [comment]
It seems that what I really like to have is a command to "temporarily hide other editor group". 
Sorry, if this has caused any confusion.

**Comment by isidorn** [comment]
Understood.
This is a fair feature request which we currently do not have on the plan, thus keeping it open and assigning to the backlog.

**Comment by ratiw** [comment]
Well, a bit disappointed to see this one goes as I really think it would be really help people who is working on a small screen laptop. However, that's understandable. Thanks for the shot, though.

**Comment by KarenJohnstone** [comment]
Hi @ratiw 
Maybe vote for it here?
https://github.com/microsoft/vscode/issues/16927
