### ISSUE TITLE
After clicking on "Kill Terminal", the entire interface stops responding

### ISSUE THREAD

**Issue by alengYuan** [microsoft/vscode#79761]
- VSCode Version: 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Run terminal (ctrl+`), this will run a script to initialize the environment of "Cmder". The following code is part of my "settings.json".
    ```json
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\Users\\yuana\\AppData\\Local\\cmder\\vendor\\init.bat"
    ],
    ```
2. Run "npm run build" or other command.
3. Click on "Kill Terminal" button.
4. The entire interface has a probability to stop responding.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
@alengYuan See https://github.com/microsoft/vscode/issues/71966#issuecomment-522848243
