### ISSUE TITLE
Find: [Files] [text in Project]

### ISSUE THREAD

**Issue by Zireael** [microsoft/vscode#79767]
Hi,

Would it be possible to add more [Find] options to VSCode?
For example, `[Find File]`, `[Find in Project]`. At the very least I'd be grateful for being able to Find a file (filter maybe?) in File Tree pane and 

Atom (sorry for comparing apples to oranges) has a separate menu dedicated purely to finding things in your project.

Current `Find` capabilities for VSCode are very limited. I had a look at an extension but no luck either.

Few visuals of what I'm longing for:

Find menu

![image](https://user-images.githubusercontent.com/3856578/63651637-b89a3080-c74e-11e9-889d-dec02fd7b503.png)

Search in project

![image](https://user-images.githubusercontent.com/3856578/63651699-876e3000-c74f-11e9-87d0-15862feef384.png)

Thank you in advance for considering my suggestion.

**Comment by Zireael** [comment]
Apologies, I've located the  [`Find in Project`] functionality:

![image](https://user-images.githubusercontent.com/3856578/63815303-03bd6a80-c92c-11e9-94ea-781ec4882238.png)

Missing [`Find File`], but I can just use Search in Explorer.exe or such.

Feel free to close the issue if it provides you no value for your roadmap.

**Comment by roblourens** [comment]
ctrl+p will open "quick open" to search by file name/path. You might be interested in https://code.visualstudio.com/docs/
