### ISSUE TITLE
Switch between format code extensions

### ISSUE THREAD

**Issue by ahmedju** [microsoft/vscode#79762]
How to change default format code??
i have many extensions for format code and I want to switch between other extensions format, How can I do it??

**Comment by CodingCreate101** [comment]
@ahmedju 
Try this: Open VS Code and `Ctrl + ,` then search for `editor.defaultFormatter` setting.

Choose which one you'd like to use in the drop-down.

-----

Alternatively, you can copy that setting to `Settings.json` and keep other formatters listed.

Example:
```
"[javascript]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
        // "editor.defaultFormatter": "esbenp.prettier-vscode 1"
		// "editor.defaultFormatter": "esbenp.prettier-vscode 2"
		// "editor.defaultFormatter": "esbenp.prettier-vscode 3"
		// "editor.defaultFormatter": "esbenp.prettier-vscode 4"
		// "editor.defaultFormatter": "esbenp.prettier-vscode 5"
    },
```

Uncomment whichever you would like to use and so on.

See any of that works out for you.

**Comment by RMacfarlane** [comment]
@ahmedju Another way in addition to everything @CodingCreate101 listed is to use the `Format Document With...` command, which will always ask which formatter you want to use
