### ISSUE TITLE
VS Code setting scss.lint.unknownAtRule isn't recognized but applies css.lint.unknownAtRule logic

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#79768]
VS Code setting scss.lint.unknownAtRule isn't recognized nor part of the defaultSettings.json but applies css.lint.unknownAtRule logic.

VSCode Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Video explaining the issue: https://youtu.be/7ubqkAU7QkE

Steps to Reproduce:

1. Copy "scss.lint.unknownAtRules": "warning" to your setting.json file
2. Write a valid @rule in SCSS like @at-rule.
3. VS Code doesn't recognize this SCSS @at-rule, but seems to recognize all other CSS @rules.

Wouldn't it make sense to have an scss.lint.unknownAtRules in the settings.json file or am I missing something?

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
Added one for scss and one for less.
