### ISSUE TITLE
Spaces display anomalies

### ISSUE THREAD

**Issue by lamborghini1993** [microsoft/vscode#79778]
- VSCode Version: 1.37.1
- OS Version: Ubuntu 18.04.3 LTS

![2019-08-26 10-28-58 的屏幕截图](https://user-images.githubusercontent.com/18731213/63661265-5f80da00-c7ec-11e9-8ae7-f910cb211049.png)
Spaces and characters are displayed in an overlapping manner. 
The above picture is for overlapping display problems. 
For example, the last line is: input 4 spaces + one letter 4. 
Result 4 shows that after the first space, the cursor is at 4, and the right arrow moves the cursor to the next line (indicating that the cursor points to the last bit)
This problem occurs with all text files.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@lamborghini1993 Sorry, I don't understand the problem. What is it you expect to see?

**Comment by lamborghini1993** [comment]
> @lamborghini1993 Sorry, I don't understand the problem. What is it you expect to see?

Sorry, there is no description, here is a new description:
Spaces and characters are displayed in an overlapping manner. The above picture is for overlapping display problems. For example, the last line is: input 4 spaces + one letter 4. Result 4 shows that after the first space, the cursor is at 4, and the right arrow moves the cursor to the next line (indicating that the cursor points to the last bit)

**Comment by RMacfarlane** [comment]
@lamborghini1993 Sorry for the delay in replying. I'm still having trouble reproducing this issue. Can you confirm that if you run the command "Developer: Reload With Extensions Disabled", you still see this problem? Have you seen this since you installed VSCode, or did it only recently start happening?
