### ISSUE TITLE
Issue with debugger not referencing javascript closure variables

### ISSUE THREAD

**Issue by nitinsh99** [microsoft/vscode#79774]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open following code in vscode

```
const util = require('./util');
const decorator = (request) => {
    return {};
}
const init = () => {
    return decorator;
};
const closure = init();
closure();

```
2. Put a breakpoin in Line 3
3. Run using vscode node debugger
4. When breakpiont hits, try to point the variable `util` in debug console

Does this issue occur when all extensions are disabled?: Yes

Note:
I am experiencing an issue in the vscode debugger, where it's not showing variables inside closure unless they are referenced.. Please see below screenshots

in first case, I reference a variable (called util) inside closure. When the breakpoint hit, we can see it's defined in the scope( see left side)
In second case, when I don't reference it ( don't do console log for util) then variable doesn't show up in the closure and if I try to print it inside debug console, i get reference error..

**Working scenario**

<img width="1226" alt="working" src="https://user-images.githubusercontent.com/1389212/63656727-e0889480-c74c-11e9-9b2f-b19a8c89890e.png">

**Not Working scenario**

<img width="1304" alt="not_working" src="https://user-images.githubusercontent.com/1389212/63656733-f26a3780-c74c-11e9-92ff-12c438207316.png">

**Comment by weinand** [comment]
@nitinsh99 the observed behavior is the expected behavior. If a variable is not used, it is garbage collected or optimised away.
Chrome Dev tools show the same behavior:

![2019-08-26_14-10-07](https://user-images.githubusercontent.com/1898161/63689828-53584500-c80b-11e9-98c5-a523214c5a88.png)
