### ISSUE TITLE
Need to attach process and start the Debug from outside application just in one click

### ISSUE THREAD

**Issue by ArchanaGurav** [microsoft/vscode#79788]
Issue Type: <b>Feature Request</b>

We are supporting the vs code for python scripts editing and debugging for our users. We have alredy supported the editing and debigging the script, but we are facinng one blocker i.e. we need to start the debigging as soon as user selects debug button from our application we expect that we start the debug session and stop at the first line of the script. Is there any option in VS code to strat the debug from outside application. Instead of pressing F5 or green button in debug profile.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

**Comment by weinand** [comment]
You can use the `vscode.debug.startDebugging` API:
https://github.com/microsoft/vscode/blob/9f49056ec7ece19d69507dfe956fb3aae8fc355c/src/vs/vscode.d.ts#L9082-L9093
