### ISSUE TITLE
Chinese characters are garbled, setting utf-8 is also garbled

### ISSUE THREAD

**Issue by d1y** [microsoft/vscode#79785]
- VSCode Version: 1.37.1
- OS Version: Darwin x64 19.0.0

Steps to Reproduce:

1.When I opened the file, many of the Chinese characters were garbled. I found that its character encoding was automatically changed to ISO 8859-2. When I manually set utf-8 to it, I still can't display 

![](https://i.loli.net/2019/08/26/tJ6pVEFZrhfDqgP.png)

The garbled part is Simplified Chinese

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@RMacfarlane please assign encoding issues to @bpasero

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
