### ISSUE TITLE
Open Editors: unable to open file in a specific group if opened in other group and setting workbench.editor.revealIfOpen

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79784]
Steps to Reproduce:

1. open the same file in 2 groups
2. configure `workbench.editor.revealIfOpen: true`
3. try to click on the file in the one group and in the other

=> 🐛 it is not possible to open each, only one

//cc @isidorn

**Comment by isidorn** [comment]
@bpasero thanks for fixing this.
