### ISSUE TITLE
A Unifying Extension of all Settings Files (Requiring minimum work) which Simultaneously provides dramatically better Control over Extensions

### ISSUE THREAD

**Issue by altimmons** [microsoft/vscode#79796]
This is a duplicate of my own.  I have put tons of thought into how to best manage the mess and chaos I always feel using VS Code for all my projects.

This means I need it configured for like 10 different languages.  And each perfect config conflicts with others.  Its very difficult, and VS Code does a very poor job of allowing Granular control over extensions and providing different contexts.  Some of these are missing implementations or incomplete implementations, and other are frank errors.

#79790 dealt with the bugs that make it harder.

This will deal with the incomplete implementation, but the major information will not be duplicated here.  Please see the referenced thread above.  Its a bit long, but read it and I think you will agree that with a few minor tweaks, things could be dramatically better.

Most the issues here, and most the bugs all have to do with a singular issue.  The biggest asset of VSCode is also its biggest downside- its extensibility.  And yet managing those extensions are a true pain in the ass.

Now if you are a guy that writes only Python.  Each day and every day, and never anything else, you will have no idea why this matters.

If you are a graduate student (for the 2nd time) like me, and flail helplessly around a new language each week, then it will make much more sense.

Switching VSC from my Markdown Notes, to My Python Project to my Java Project is very very difficult.

The workspaces totally have the Typescript proj 1 -> TS Proj 2 -> Typescript Proj 22 -> and on some crazy friday, maybe some Javascript- people handled.

But when configs vary from proj to proj, and you are like me always trying new extensions, things often rapidly become a mess.

I propose 3 things.  I describe them in more detail at the link, and more generally here.

1.) A Mechanism for "Profiles" which are complementary to Workspaces and Folders.  One Deals with the location, the other the context.
2) a Unified Settings Paradigm. Taking *.Code-workspaces to the logical conclusion.  
- A typical project may have at most- **Settings**, **Tasks**, **Launch**, **Extensions** (_very very poorly implemented in code-workspaces only right now- its essentially broken._ **Keybindings** and **Paths**)  

Settings can be further subdivided, - something like this:

>...1-Settings
>......Editor Config
>.........Landuage Specific Settomgs
>......Workspace Config
> .........-(themes)
> ............-Workspace Configuration/ Overrides
>............-TextMate, tokenization Configs/overides 
>... 2-Extensions
>......- Include
>......- Exclude
> ......-(Recommend)
> ......-(Dont Recommend(?)) <I presume someone finds this useful>
> ... 3-Keybindings
>... 4-Snippets
>... 5-Launch Config
> ...6- Tasks
>... ?- Others I forgot, or future extensiability.

We already have a hierarchy of declarations- Global.  Workspaces. and Folder- with corresponding precedence.  We already have one folder that can contain several of the types.

The Unified aspect is that there is a root node- the default settings paradigm.
Then underneath that are all the user global settings.

Just like now.  The difference is that any settings.json file will be able to carry any of the 6 types above.  Like a Super dot code workspace. 

3-  These settings files can be passed in whenever with the use of an `includes` statement- which is necessarily named.  Each of these includes can be referenced and enabled or disabled in the command processor.  

>Snap-in Settings
->  returns a list of the declared includes at the 'leaves' of the settings tree. 

You can also snap-out settngs as well.

This is hard to describe, please see my explicit example at the link above.  

These can correspond to whatever organizational strategy the user wants.- from a per Language basis, to includes that snap in and out specific extensions, all the way to some distal includes that allow toggling individual settings, via command processor.

`"includes" : { } ` is like old school programming `GoTo` - its like the code exists at its declaration point.  The only thing is a handler keeps track of which are enabled and which aren't.

This is entirely equivalent to going to the settings file and commenting out a few lines.-- but it also allows every user to essentially design listlessly powerful macro like 'tasks; that can do nearly anything you can do by hand in code.  It can toggle settings.  Unload extnsions and change the theme and linter, to switch you into python mode.

Settings instead of a hierarchy becomes a tree (though, only one-_ish_ path to the ground may be active at a given time)  See my example.

I will try and illustrate a bit.

Each of the 6 base types can be in any settings.json file.
like if you took each and appended them to each other.  They stay separate - in their own JSON brace.,  Nothing at all special about that.

> Global
>    |
>    |---Java - a java Config which itself has 2 includes
>    |       |
>    |       |-EditorCustomizations 
>    |       |-SpringBoot - settings for a spring boot build and the related extensions it depends on
>    |       |       |
>    |       |       |-- Project A settings
>    |       |       |-- Project B settings
>    |       |       |         |
>    |       |       |         |-RevA-Overwrites some of the earlier configuration with new settings
>    |       |       |         
>   \       \       \
>   \       \       \
>   |---Python
>   |        |--Proj Config
>  |---WSL Config
>  |         | -->explicitly overrides (Windows based) paths in Java Proj B for WSL.

So
My state tree would be : Global +Java  +SpringBoot  +ProjB +WSL

The ones that arent enabled don't exist.  But a single command can toggle it.

Each branch is either On/Off at a given time.  Which controls the 'context' based settings in effect at a given time.  Rather than making this sorta poorly location dependent like they are now.  

Location and context are only sort of related, since the settings define the context- with the exception of the Paths supertype (Folder Roots).  It makes much more sense to make the settings tied to a context rather than a location.

Right now, each time I start a new Java Project, I have to replicate in my settings from an old folder to the new one.  My context is the same though.  Still doing Java.  So above

4. This leads to the 4th minor change- control over the enablement and disablement of extensions via a `settings.json` file. Like `Root.code-workspace:extensions` only it works and isnt broken and suck.

These 4 small changes will make the most extensible IDE out there much much more extensible, easier to control, easier to understand, and more flexible.  

Anyway- thoughts on this?

**Comment by sandy081** [comment]
/duplicate

There are duplicates for all these issues.
