### ISSUE TITLE
Editors: group not activated with workbench.editor.revealIfOpen: true

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79798]
Steps to Reproduce:

1. configure `workbench.editor.revealIfOpen: true`
2. open multiple editor groups
3. open some editors in one group and others in the other group
4. focus the first editor group
5. click on a file in the other group via explorer that is currently active in that other group

=> 🐛 there is no visual indicator that something happened because we do not activate that other group

A fix would be to always ensure we activate a group of the editor we want to open. The only one exception is when opening an editor to the side. For historic reasons we do not activate the editor group in that case if `preserveFocus: true`.

//cc @eamodio since you complained about this in https://github.com/microsoft/vscode/issues/24717 it seems, but only limited to search. You should see this issue in all kinds of cases where we open an editor and I think this new behaviour is better, let me know otherwise.

**Comment by eamodio** [comment]
@bpasero Looks good -- thanks!
