### ISSUE TITLE
Native input box out of style from the rest of vscode

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7979]
In the extensions viewlet we use a native input box.
1. It looks out of style compared to rest of vscode
2. It looks very bad on linux

![screen shot 2016-06-22 at 10 49 07](https://cloud.githubusercontent.com/assets/1926584/16260290/11634c30-3867-11e6-817a-4656f0ba1af6.png)

**Comment by joaomoreno** [comment]
#7946
