### ISSUE TITLE
patternPos isn't working correctly 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#79815]
Run fuzzyScore with `:p` against `prop`, using pattern pos 1. the result is `pro^p`, not `^prop`

**Comment by octref** [comment]
@jrieken Any verification steps, or just through code review?

**Comment by jrieken** [comment]
There is a unit test, so some confidence, but you can verify using quick outline, with the `@:` prefix, e.g have a class with method `prop` and search for `@:p`
