### ISSUE TITLE
Terminal output messes up after VScode window resizing

### ISSUE THREAD

**Issue by PrateekArya** [microsoft/vscode#79816]
Issue Type: <b>Bug</b>

1. Print something on terminal. I have configured my VSCode to use Anaconda's python terminal. 
2. Resize VSCode window (I did by dragging the title bar from maximized position).
3. Resize the VSCode window to maximized.
4. Voila the text in the terminal is messed up! See attached screenshots for reference.

VS Code version: Code - Insiders 1.38.0-insider (ada79d72be36ecbfed6f88bb16edcc5cc3f5c2a8, 2019-08-21T13:26:22.457Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|don|1.1.5
gitlab-workflow|fat|2.1.1
code-runner|for|0.9.14
latex-workshop|Jam|8.0.7
nbpreviewer|jit|1.2.2
r|Mik|0.0.6
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.3

</details>

![Before resizing](https://user-images.githubusercontent.com/1255663/63700847-092f8d80-c824-11e9-8eec-c646728df104.PNG)
![After resizing](https://user-images.githubusercontent.com/1255663/63700849-092f8d80-c824-11e9-9010-cd849175ad0c.PNG)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
