### ISSUE TITLE
Accessibility: tabbing in a warning popup should cycle within the popup instead of moving focus to background menus.

### ISSUE THREAD

**Issue by Benjin** [microsoft/vscode#79826]
**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: `78a42e1`
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Steps to Reproduce:**
Open VS Code Settings, execute any functionality that produces a confirmation toast.
Press Tab to move throughout the controls in the toast.

**Expectation:**
Continuing to press Tab will repeat focus with just the controls in the toast.

**Reality:**
Focus shifts to the File menu in the background of the app.

**Impact:** Accessibility

![image](https://user-images.githubusercontent.com/1609827/63716858-d2de1800-c7fb-11e9-9b79-0a8dfab5876b.png)

**Comment by isidorn** [comment]
Disagree. Tab always moves focus around the whole workbench which is expected. Just check out what other apps are doing like Chrome or Visual Studio. Tab should never lock you in some area. That way a user would be "trapped" and could not navigate outside of it.

If you want a dialog which steals focus the extension should use a modal dialog and not a toast which is designed to not be blocking.

fyi @bpasero

**Comment by isidorn** [comment]
Thanks. Closing this as designed then.
