### ISSUE TITLE
Open random file by program being debugged in VSCode not opening

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode#79822]
Issue Type: <b>Bug</b>

I'm debugging a C++ app using VSCode. Now this app tries to open a file in my default text editor ( via shell etc. on Windows), which happens to be VSCode as well. This open operation fails.
In process explorer I see a vscode process for a microsecond, but it just disappears.

e.g. Process tree:
- vscode
-- app.exe
--- vscode foo.txt (dies)

If I just run this
-- app.exe
--- vscode foo.txt (works)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.30GB free)|
|Process Argv|--folder-uri file:///c%3A/Altair/software/HstFbCurie-01_TR-LAP965|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.39.2
cpptools|ms-|0.25.0
hyperworks|sle|0.1.0
optistruct|sle|0.1.0
radioss|sle|0.1.0
tcl|sle|0.2.0
templex|sle|0.1.1
vscode-icons|vsc|9.3.0

</details>

**Comment by weinand** [comment]
@sleutho what does the error handling of your app say when opening a file with VS Code fails?

**Comment by weinand** [comment]
The name of the CLI executable is "code", not "VSCode.exe".
