### ISSUE TITLE
Errors in console while browsing extension descriptions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7982]
1. Open extensions viewlet
2. Open multiple extension descritpion
3. After some time notice errors in console
4. Everything works fine though but I would expect the console to stay clean

![screen shot 2016-06-22 at 11 21 04](https://cloud.githubusercontent.com/assets/1926584/16261356/83d04580-386b-11e6-8ac3-ffcd68cc1ce0.png)

**Comment by joaomoreno** [comment]
Can you check whether those files exist in disk at all?

**Comment by isidorn** [comment]
Well they do not extist anymore because I have deleted all my extensions. Let me try to get better steps for this...

**Comment by isidorn** [comment]
Ok here are the steps:
1. Install extension
2. Uninstall that extension -> it is still present in list -> click on it -> notice error in console

**Comment by joaomoreno** [comment]
Can't do anything to prevent this really, since the fetch is an XHR and Chromium just shows it in the console.

Will close as designed.
