### ISSUE TITLE
Toggle menu view does not work

### ISSUE THREAD

**Issue by tcantalice** [microsoft/vscode#79820]
Issue Type: <b>Bug</b>

I can not hide the menu.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD C-60 APU with Radeon(tm) HD Graphics (2 x 860)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 5, 4|
|Memory (System)|3.46GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-markdownlint|Dav|0.30.1
vscode-eslint|dba|1.9.1
code-runner|for|0.9.14
python|ms-|2019.8.30787
sublime-keybindings|ms-|4.0.3
java|red|0.47.0
vscode-yaml|red|0.5.1
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-icons|vsc|9.3.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
@tcantalice what do you mean by "Toggle menu view"?
