### ISSUE TITLE
The string is recognized as a comment

### ISSUE THREAD

**Issue by awwlife** [microsoft/vscode#79821]
The following section of code is perceived as the beginning of an endless comment, I hope for a quick solution to the problem.

SECTION:
`$header = array(  'Content-Type: application/json',
                                                'Content-Length: ' . strlen($this->_postFields),
                                                'Referer: ' . $this->_referer,
                                                'X-Requested-With: XMLHttpRequest',
                                                "Accept: application/json, text/javascript, */*; q=0.01" ), $include = true)`

**Comment by awwlife** [comment]
Are you kidding me? Last line contains '*/*'

**Comment by awwlife** [comment]
OH..... Are you kidding me? 
![image](https://user-images.githubusercontent.com/54188033/63708323-c29a5d00-c83c-11e9-8d51-717ee7c6af8c.png)

**Comment by awwlife** [comment]
Whatever quotation marks(single and none) this section is placed in, vscode still takes it as the beginning of a comment.

**Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-25-generic**

**Comment by weinand** [comment]
@awwlife What language is this?

**Comment by awwlife** [comment]
PHP
