### ISSUE TITLE
Test: Webview.asWebviewUri 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#79836]
Test for #79242

- [x] Linux @chrmarti
- [x] Mac @bpasero
- [x] Windows @alexr00

Complexity: 4

**Overview**
This iteration, we finalized two apis on the `Webview` object:

- `webview.asWebviewUri(resource)` — Converts `resource` from a file resource uri to a uri that can be used in webviews to load local content

- `webview.cspSource` —  Content security policy root for local resources. 

Test using these two apis to load local resources inside the webview in both desktop and web versions of vs code. You can use the webview sample as a starting point: https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample

**Comment by alexr00** [comment]
Test in desktop and in web.

**Comment by bpasero** [comment]
I forgot to check the platform and did macOS. Seems to work fine after a little bit of hiccup understanding it.

**Comment by chrmarti** [comment]
@mjbvz I can't get it to work on Linux with an image. The URL is `vscode-resource:/home/chrmarti/Downloads/coding.gif` and the CSP is `content="default-src 'none'; img-src vscode-resource: https:; [...]`. The webview dev tools show an `net::ERR_ACCESS_DENIED` for the coding.gif. 🤔

**Comment by chrmarti** [comment]
Figured it out: The file needs to be in the extension's folder it seems - which makes sense. Maybe the API could throw or log a warning if that is not the case. Will open an issue.
