### ISSUE TITLE
Cannot create keyboard shortcut "cmd + `"

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#79832]
Steps to Reproduce:

1. Command Palette > "Preferences: Open Keyboard Shortcuts" 
2. Search for "Integrated Terminal"
3. Edit "View: Toggle Integrated Terminal" keybinding
4. Try to type "cmd + `"

Expected: it allows me to create a "cmd + `" keybinding
Actual: It ignores the "`" character, only showing "cmd"

NOTE: 
- Repros for any keybinding, not just Integrated Terminal
- Does not repro for similar combinations "Shift + `" or "cmd + 1"
- I can manually edit the JSON file to add "cmd + `" shortcut and it works correctly.

```
// Place your key bindings in this file to override the defaults
[
  {
    "key": "cmd+`",
    "command": "workbench.action.terminal.toggleTerminal"
  },
  {
    "key": "ctrl+`",
    "command": "-workbench.action.terminal.toggleTerminal"
  }
]
```

**Comment by alexandrudima** [comment]
@dalongi On mac, `` cmd + ` `` is typically reserved to loop through windows of an application. Have you removed that keybinding from the OS ?

**Comment by alexandrudima** [comment]
@dalongi I wonder if it is not the other way around. When there is a single VS Code window opened, the OS allows an app to handle `` cmd + ` ``.

Are you now in a good state?

**Comment by dalongi** [comment]
Yes, the workaround is sufficient for me.
