### ISSUE TITLE
Duplicate definition of searchQuery module

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7983]
Saw this in the console:

`Duplicate definition of module 'vs/workbench/parts/search/common/searchQuery'`

**Comment by sandy081** [comment]
@joaomoreno I do not see any such logs in the console. 

But, when I searched for this module in code, I do not see any indication of duplicates. 
But, I saw some commented lines in workbench.main.ts 

```
// require.config({
// 	ignoreDuplicateModules: [
// 		'vs/workbench/parts/search/common/searchModel',
// 		'vs/workbench/parts/search/common/searchQuery'
// 	]
// });
```

I do not know if it is somehow related.

**Comment by bpasero** [comment]
@sandy081 yes, I think @alexandrudima did this and it is related
