### ISSUE TITLE
VSCode running `git show` constantly

### ISSUE THREAD

**Issue by wfraser** [microsoft/vscode#79830]
- VSCode Version: Version: 1.37.1 / Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
- OS Version: macOS 10.14.6 
- Does this issue occur when all extensions are disabled?: Yes

After a recent update (not sure how long ago; I haven't used VSCode for a few weeks), I find that after using the editor for a few seconds, performance starts to get really bad (scrolling lag, etc.) and CPU usage gets very high.

I checked and VSCode is running a lot of git processes. The version control icon on the left sidebar has a stopwatch on it. I turned on `Show Git Output`, and I can see VSCode running `git show` over and over again for the files I have open. The more files I have open, the more commands it tries to run, over and over again.

~Also weird is the argument to `git show` is the full path (workspace relative) with a colon character prefixed to it. This isn't a valid path, and so presumably git has to search the history to see if it ever was a valid path. I'm working on a repo with an extremely long (10+ year, 500K+ commits) history, so this takes it a while.~ edit: just kidding, apparently `git show :path` *is* valid. Still doesn't explain why it's doing it every other second.

Here's a sample snippet of a few seconds from the git output window:
```
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git status -z -u
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git symbolic-ref --short HEAD
> git rev-parse my-current-branch
> git rev-parse --symbolic-full-name my-current-branch@{u}
fatal: no upstream configured for branch 'my-current-branch'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
> git status -z -u
> git show :[redacted]/file1.rs
> git show :[redacted]/file2.rs
```

**Comment by joaomoreno** [comment]
How slow is a `git show` command exactly?
