### ISSUE TITLE
Hover obscures previous code

### ISSUE THREAD

**Issue by AlexLeung** [Microsoft/vscode#7984]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce: 
1. write function name followed by open paren `(` character

When typing in the parameters to a function, I want to see the code I just wrote, but the automatic Parameter Hinting pop-up box often covers up the previous lines, sometimes hiding up to the previous 4 lines of code! This can be especially annoying when the parameters I am typing span multiple lines.
To fix this problem I have been adding the following custom CSS style to the VSCode Developer Tools:
`.editor-widget:hover { opacity: .15; }` 
However, it would be nice if there was a way that I could disable the Parameter Hinting so I don't have to press `ESC` each time I am typing parameters and want to get rid of the hinting box. A different fix to this problem would be if the parameter hinting was out of the way, by being below the current line of code for example.

**Comment by dbaeumer** [comment]
May be @joaomoreno as well.

**Comment by joaomoreno** [comment]
There is a setting to disable it altogether: `editor.parameterHints`. It's not ideal but does address the issue.

We can also make it that if you hold a key, eg <kbd>Shift</kbd>, we'd just fade both parameter hints and intellisense away and bring them back once the key is released.

**Comment by AlexLeung** [comment]
The <kbd>Shift</kbd> solution could work, but might that cause people to accidentally disable the parameter hinting if they are just trying to capitalize something?

**Comment by joaomoreno** [comment]
We'd simply fade it, not hide it. We can also introduce a `500ms` delay on that, would help in reducing flickering.

**Comment by AlexLeung** [comment]
Could the box remained faded as I type in more parameters? One of the biggest annoyances about the way the parameter hinting currently works is that when I get rid of it by pressing <kbd>Esc</kbd> then move on to the next parameter by pressing <kbd>,</kbd>,  the box then reappears, meaning that if I am calling a function with some 5+ parameters I need to press <kbd>Esc</kbd> 5 times.

**Comment by joaomoreno** [comment]
When would it fade back in?

**Comment by AlexLeung** [comment]
By pressing a button to fade it back in. So for example if <kbd>Shift</kbd> is the key for this, holding down left shift could fade it out indefinitely, and holding down right shift could fade it back in indefinitely. Alternatively, a different key such as <kbd>Alt</kbd> could be used for this as well.

**Comment by oheard** [comment]
This is especially problematic when using extensions that hijack the Esc key (the up and coming vim plugin for instance), where there is no way to hide the pop-up without resorting to the mouse.

Just adding my 2p.

**Comment by joaomoreno** [comment]
Thanks for the insights, @oheard. That is bad, if true. 👍

**Comment by bobmagicii** [comment]
opacity won't be enough and just be as annoying. it needs to be repositioned.

**Comment by jaredly** [comment]
I would much rather it be offset horizontally by, for example, 300px, or stuck to the right of the editor. Also, I'd like it to stay in one place, vertically, ideally with the bottom of the box flush with the top of the line of the function call.
Because now it is just about unusable.

**Comment by bobmagicii** [comment]
hell for that matter, in response to @jaredly, we can pretend its a system tray notification and cram it into a corner of the window always that could be a nice optional choice.

maybe they can provide a json option that is just like "give us a object that looks like css" do wtf you want with it.

**Comment by offero** [comment]
It would also be nice to have some transparency for it. I would also prefer to be able to exit out of it somehow, which I can't seem to figure out how to do.

**Comment by AlexLeung** [comment]
@offero Try pressing the escape key

**Comment by offero** [comment]
@AlexLeung I did, but it didn't work. It was probably the vim plugin interfering.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
