### ISSUE TITLE
Hover / Suggest inconsistency: Plaintext Linkifying

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79841]
Split from #78718:

### Plaintext Linkifying

```ts
const markupContent: MarkupContent =  {
	kind: 'plaintext',
	value: 'https://code.visualstudio.com'
};
```

![image](https://user-images.githubusercontent.com/4033249/62720345-b5691b80-b9be-11e9-9fa9-4b4c935663ec.png)

**Comment by octref** [comment]
I think this should be done together with consideration for #79840. If for that we switch completion item details to use `MarkdownString.appendText`, this will be auto-fixed.

**Comment by octref** [comment]
@jrieken Do you think we should linkify the links in plaintext by doing that in `appendText`?

**Comment by jrieken** [comment]
This works when using the correct type: `vscode.MarkdownString`. The type above (its name) doesn't exist, the structure (ignoring the name) is verbatim/code blocks
