### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Renkon117** [microsoft/vscode#79852]
I am trying to update my VS code version, but it is not working well right now. I think the reason is that I moved the whole program from my D drive to C drive. At the time, something went wrong I assume. The error code suggest that the program error might come from VS code exe file. Is there any way to correct this error?? please help

**Comment by Nakxion** [comment]
nope it's not local #79854

**Comment by weinand** [comment]
Please provide more detailed information. What error code are you seeing?

I suggest that you remove VS Code in both locations and then make a fresh install (no update).

**Comment by Renkon117** [comment]
Hello, the issue was fixed by just uninstalling and reinstall the app !! thank you so mucj !!
