### ISSUE TITLE
Two remote icons (There is no visible distinction in the icons)

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#79855]
Issue Type: <b>Bug</b>

with the latest update VSCode insiders shows 2 remote icons.
1. Targets(Containers)
2. Connections

Although the viewlet on the icon click are different, there is no visible distinction in the icons.
I tried to reload the window as well as restarting VSCode insiders, however both icons are still visible.

![remote2](https://user-images.githubusercontent.com/9264813/63744792-0da88480-c8be-11e9-9d52-2d7cb7bc2723.png)
![remote1](https://user-images.githubusercontent.com/9264813/63744795-0e411b00-c8be-11e9-9111-b1471be0b2c3.png)

VS Code version: Code - Insiders 1.38.0-insider (185308c0dd317d73fe4c19dea347582dee9650de, 2019-08-26T09:46:11.283Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-58-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (4.21GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.69.0
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.3
vscode-remote-extensionpack|ms-|0.16.0
debugger-for-chrome|msj|4.11.7
ng-template|Ang|0.802.2
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
vscode-azureappservice|ms-|0.15.0
python|ms-|2019.8.30787
azure-account|ms-|0.8.4
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.721
vsliveshare-audio|ms-|0.1.64
fabric8-analytics|red|0.0.12
vscodeintellicode|Vis|1.1.9
WebTemplateStudio-dev-nightly|WAS|0.0.1922901

</details>

**Comment by sanket-bhalerao** [comment]
the problems panel icon is (i think) incorrect.
![problems panel icon](https://user-images.githubusercontent.com/9264813/63768426-cc2fcd80-c8ed-11e9-9862-a8ec622328a7.png)

**Comment by roblourens** [comment]
@rebornix is correct and the problems panel icon has been fixed
