### ISSUE TITLE
use jsconfig.json to workspace not work

### ISSUE THREAD

**Issue by Hideer** [microsoft/vscode#79851]
- VSCode Version: 1.37.1
- OS Version: Mos 10.14.6

Steps to Reproduce:

my jsconfig.json configuration：
```
{
  "compilerOptions": {
    "target": "ES6",
    "jsx": "react",
    "experimentalDecorators": true,
    "baseUrl": "./",
    "paths": {
      "@/*": [
        "src/*"
      ],
    }
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ]
}
```
when i use single folder project no problem
but when i use workspaceRoot not work

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

I tried using a jsconfig.json to include all js files like I've seen suggested but it did not work.

**Comment by mjbvz** [comment]
What doesn't work in the workspace case? Please share a small example project that demonstrates the problem and describe what is going wrong
