### ISSUE TITLE
Find in files: Collapse button is disabled

### ISSUE THREAD

**Issue by der-dirk** [microsoft/vscode#79856]
Issue Type: <b>Bug</b>

To reproduce:
- Open "Find in Files"
- Search for anything

Observed: The collapse buton is disabled
Expected: The collapse buton is enabled

Collapsing all find results via command works: Ctrl+Shift+P -> "Search: Collapse All"

---
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
Doxygen|bbe|1.0.0
unique-lines|bib|1.0.0
xml|Dot|2.5.0
json-tools|eri|1.0.2
todo-tree|Gru|0.0.142
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
csharp|ms-|1.21.1
powershell|ms-|2019.5.0
equalize|myc|1.2.0
material-icon-theme|PKi|3.8.1
vscode-header-source|ryz|1.3.0
trailing-spaces|sha|0.3.1
perforce|sle|3.2.0
vscode-hexdump|sle|1.7.2
dot|Ste|0.0.1
graphviz-interactive-preview|tin|0.0.4
clang-format|xav|1.9.0
cursor-align|yo1|1.0.4
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by weinand** [comment]
@der-dirk what do you mean by "collapse buton"? I only see a "Collapse All" button:

![2019-08-27_10-58-13](https://user-images.githubusercontent.com/1898161/63756995-9ec92c80-c8b9-11e9-8bd6-d2e235eee853.png)

For me the "Collapse All" button is enabled.

Can you reproduce the problem when disabling all extensions?

**Comment by der-dirk** [comment]
Hi, I tried several times in different ways but was not able to reproduce it. As I'm not at all sure about its circumstances I close the bug for now and re-open if it ever occurs again.
