### ISSUE TITLE
Shortcut for select in popup checklist

### ISSUE THREAD

**Issue by niudai** [microsoft/vscode#79853]
What's the shortcut for check in the items in the image below?

![image](https://user-images.githubusercontent.com/44165182/63743695-ac89ac80-c8cf-11e9-845a-f3017c7fa90d.png)

I can only left-click them to select, and I find no short cut for selecting in checkbox.
I use `enter` to select but this just close the popup list.

**Comment by weinand** [comment]
Usually checkboxes can be toggled with the "space" key.
