### ISSUE TITLE
Source control providers height flex

### ISSUE THREAD

**Issue by asegoviaTarin** [microsoft/vscode#79858]
When I have many submodules I can't make higer the source controll providers panel. In 1.32.3 VSCode version this is posible. In this version I can customize height panel in order to avoid vertical scroll panel

- VSCode Version: 1.37.1
- OS Version: Linux 18.04

Steps to Reproduce:

1. Open source control tab
2. Try to expand source controll providers when you have more than 10 submodules in order to avoid vertical scroll bar. You can't change the panel's height
![Selección_041](https://user-images.githubusercontent.com/31535202/63750421-b8647700-c8ad-11e9-81c1-f384eff85499.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by stillsweetK** [comment]
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by joaomoreno** [comment]
Change `scm.providers.visible` to `0`.
