### ISSUE TITLE
activeViewlet is broken?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#79862]
I have a command which should be enabled only when the explorer is active:
```
{
   "command": "test.explorer.visible",
   "title": "Test Explorer Visible",
   "when": "activeViewlet == 'workbench.view.explorer'"
}
```

But it is enabled always, regardless whether another view is visible, the explorer view is hidden and so on. Do I use it properly?

It is on the latest VS Code, did not try in insider.

**Comment by isidorn** [comment]
This works just fine for me in latest vscode insiders.
Please try it there and let us know if you can still reproduce this.
If yes, then please try to write a custom keybinding for a bulitin vscode command that uses the activeViewlet context and verify if the context is really is broken.

**Comment by akosyakov** [comment]
sorry for a noise, it is my fault, i had to customize `menus` contribution point, `command` does not have `when` property
