### ISSUE TITLE
Uninstalling an extension only removes latest version of that extension

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7986]
Not sure if this is expected.
1. Manually change the version of an extension you have installed
2. Start vscode - get offered an update to that extension -> update it
3. Now uninstall that extension
4. Restart vscode -> notice the extension is still in the list and an update is offered

The issue is that the uninstall only removed the latest version of my extension. I would expect that all versions of my extension get removed.

**Comment by joaomoreno** [comment]
Expected.
