### ISSUE TITLE
Smart select default proposals overwrite result from provider

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#79865]
It's in JSON mode, set the cursor before `Bar"` and invoke `Expand Selection`

```json
{
  "line1": "FooBar"
}
```

Result: `Bar"` is selected
Expected: `FooBar` or 'Bar'

- The JSON language service returns [ `FooBar`, `"FooBar"`, `"line1": "FooBar"`, ...]
- The built-in (word based) smart selection uses the JSON word rule which includes `"` in a word/token, and thus comes up with `Bar"` 
- `FooBar` is ignored. IMO the built-in (word based) smart selection results should only be used if they don't intersect with the provider results.

I know the JSON word regex is controversial, but the proposals from provider should never loose against the default proposals.

**Comment by jrieken** [comment]
The design is to first expand within the word (along typical separators) and since JSON defines `"` as word character this happens
