### ISSUE TITLE
VS Code ignores debug.console.wordWrap

### ISSUE THREAD

**Issue by retifrav** [microsoft/vscode#79878]
I think, this is a continuation of #72210

- VS Code version: 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35)
- OS version: Mac OS 10.14.6 (18G95) and Windows 10.0.18362.295

Steps to reproduce:

1. Open the OUTPUT panel;
2. Perform any operation that outputs long lines;
3. Change `debug.console.wordWrap` to the opposite value (`true`/`false`);
4. Perform any operation that outputs long lines;
5. Notice that wrap behavior doesn't change.

Does this issue occur when all extensions are disabled? Yes

More to that, it behaves differently between Mac OS and Windows. On Windows the lines _are not wrapped_ with both `debug.console.wordWrap` set to `true` or `false`. And on Mac OS it's the other way around: the lines _are always wrapped_ with both `debug.console.wordWrap` set to `true` or `false`.

Tried it it with VS Code Insiders (1.38.0-insider, 8cd00a7935eabef4aad0b0130b1d46daca0a47aa) on Windows - the lines _are always wrapped_ with both `debug.console.wordWrap` set to `true` or `false`.

**Comment by isidorn** [comment]
`debug.console.wordWrap` is not applie to the `OUTPUT` panel. It is only applied to the DEBUG CONSOLE panel.

If you are seeing this in the DEBUG CONSOLE can you please provide a screenshot, and a short reproducable program that prints some lines which do not get wrapped.

On macOS for the `debug.console.wordWrap` nicely controls this behavior, thus I cannot reproduce your issue.

You can see the gif attached where this feature nicely works for me. Let me knkow what you are doing differently

![wrap](https://user-images.githubusercontent.com/1926584/63768231-f7a3bf80-c8cf-11e9-9098-e7b51acd7dbf.gif)

**Comment by retifrav** [comment]
Then it was silly of me to assume that `debug.console.wordWrap` controls wrapping in the whole panel. But is there a setting that controls the wrapping in the OUTPUT?

My problem is that OUTPUT panel does not wrap lines anymore, but it was wrapping the lines before, and I think that it stopped doing so somewhere around the time when `debug.console.wordWrap` option was introduced, although I don't know if that is really the reason.

Should I create a new issue then and close this one as invalid?

**Comment by isidorn** [comment]
Yes, please create a new issue, as it has nothing to do with the debug.console.wordWrap option.
Yes menion when word wrapping was working in the OUTPUT and when it stopped working. ANd provide a reproducable sample

**Comment by retifrav** [comment]
If anything, I found how to control the wrapping in the OUTPUT panel:

``` json
"[Log]": {
    "editor.wordWrap": "on"
}
```

Which cannot be set/found via regular settings view, so one have to edit `settings.json` manually.

I don't know how did it work for me before as I did not have this setting, but indeed, it has nothing to do with `debug.console.wordWrap`, sorry for the confusion.
