### ISSUE TITLE
C# Syntax Highlight: Null Propagation Operator

### ISSUE THREAD

**Issue by wwdenis** [microsoft/vscode#79872]
- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

![CSHARP_HIGHLIGHT](https://user-images.githubusercontent.com/21691662/63760049-e7cfaf80-c8be-11e9-98c8-1e853e7075ac.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to the owning repo https://github.com/dotnet/csharp-tmLanguage/issues/163
