### ISSUE TITLE
When a command is missing, an error should be shown

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#79875]
Testing #79819

Tweak the extension at https://github.com/microsoft/vscode-extension-samples/blob/7b4d139f4b42e6c13fb022f1c8dad5f8179d5ce0/tree-view-sample/

* in `src/testView.ts`, add a `contextValue` to TestView tree items:
![image](https://user-images.githubusercontent.com/5047891/63760629-f5396980-c8bf-11e9-848e-27cc5378d1f2.png)

* in `package.json`, add a new command contribution:
![image](https://user-images.githubusercontent.com/5047891/63760750-3467ba80-c8c0-11e9-8b94-7bb9a82fd4d9.png)

* in `package.json`, render the command in the TestView tree items:
![image](https://user-images.githubusercontent.com/5047891/63760820-53664c80-c8c0-11e9-8922-178cc09bf7f7.png)

The new command should be rendered in the tree items:
![image](https://user-images.githubusercontent.com/5047891/63760914-81e42780-c8c0-11e9-93ef-04591b711544.png)

Clicking the command does not do anything because no command is registered, but it should show an error message. It appears that the custom tree view is swallowing errors generated by `ICommandService.executeCommand`.

**Comment by alexr00** [comment]
Moving to September since this behavior was in the old custom tree view too.
