### ISSUE TITLE
WSL shell issue (again?)

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vscode#79876]
The issue with WSL has been reported before: #67855 & #70307 but probably has not been completely resolved. Simple (tasks.json) task:
```
"type": "shell",
"command": "echo hello",
"problemMatcher": [],
```
fails with error:
```
/bin/bash: - : invalid option
The terminal process terminated with exit code: 1
```
WSL is the default terminal, settings.json contains: `"terminal.integrated.shell.windows": "wsl.exe"`
WSL Extension installed and active.
Windows 10.0.17134, VsCode 1.37.1, Ubuntu 18.04.2 installed from MS Store

**Comment by alexr00** [comment]
@tdjastrzebski I can't reproduce. Can you share the rest of your settings and your tasks file?
I used Ubuntu, installed from the store.
I set wsl.exe to be the shell.
My task:
```
{
			"type": "shell",
			"label": "TEST",
			"command": "echo hello",
			"problemMatcher": []
		}
```

**Comment by tdjastrzebski** [comment]
I will investigate further and will get back with more info.

**Comment by alexr00** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
