### ISSUE TITLE
the setting with terminal doesn't work 

### ISSUE THREAD

**Issue by haizhuling** [microsoft/vscode#79873]
- VSCode Version: 1.37.1
- OS Version: win10 1903 

i set the terminal is  integrated,but it always open terminal with new windows ,just like this, what i can do to repair it .
![1](https://user-images.githubusercontent.com/23161247/63760613-38accb80-c8f2-11e9-858a-629f2549c8b3.gif)
![Snipaste_2019-08-26_09-45-29](https://user-images.githubusercontent.com/23161247/63760668-5417d680-c8f2-11e9-94bd-25c181b7e81c.png)

Does this issue occur when all extensions are disabled?: No
i disable recent extension when this thing occur, but it doesn't work

**Comment by haizhuling** [comment]
no like it ,i want open a integrated terminal ,but vscode open a external terminal. terminal can normal work，the setting also is integrated。

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
