### ISSUE TITLE
Log files gets huge

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#79882]
re https://github.com/microsoft/vscode-internalbacklog/issues/774

* open output channel and see messages about missing linkComputer-file (see https://github.com/microsoft/vscode/issues/79874)
* wait for 15 minutes
* the log files grows unbounded (base CPU load is getting high)

<img width="972" alt="Screenshot 2019-08-27 at 12 08 53" src="https://user-images.githubusercontent.com/1794099/63762644-79412080-c8c3-11e9-969d-f7ccb1afa6eb.png">

**Comment by sandy081** [comment]
Need support for recurring logs.

**Comment by sandy081** [comment]
Now web log files reccur at 5MB and there will be 5 recurring files.

**Comment by sandy081** [comment]
To verify, run it from sources and tweak the max file size variable here - https://github.com/microsoft/vscode/blob/7c4afcf/src/vs/platform/log/common/fileLogService.ts#L13
