### ISSUE TITLE
Icon missing for data breakpoints

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79885]
Testing #79799 

Data breakpoints don't show an icon in the BREAKPOINTS view:

![2019-08-27_12-33-28](https://user-images.githubusercontent.com/1898161/63764345-e609ea00-c8c6-11e9-8955-f6562f0cd255.png)

**Comment by isidorn** [comment]
@misolori and me were thinking if we should go with the standard red circle. Or be more creative and use something new like a red hexagon.
If we do not find something nice, I will just go with the red circle for this week.

@weinand let me know if you have some ideas.

**Comment by weinand** [comment]
I'm fine with everything that looks different than the shapes already in use.
E.g. a dodecahedron or any other Platonic solid works fine for me...

**Comment by weinand** [comment]
the "Platonic solids" was a joke... no 3D necessary.
I like Data 2

**Comment by isidorn** [comment]
Data 2 was what I imagined. And yes I really like it.
Since the other remind me of batman (I don't know why), the sun and the moon.

@misolori I will update the code and you can just push the icons to `src/vs/workbench/contrib/debug/browser/media/`
We need `breakpoint-data.svg`, `breakpoint-data-disabled.svg` and `breakpoint-data-unverified.svg`

**Comment by isidorn** [comment]
@misolori I have pushed the changes on the vscode side via 79923 
We just need the three .svg files

**Comment by isidorn** [comment]
Fancy!

**Comment by weinand** [comment]
Verified that data breakpoint got an icon.

However, the visual difference between the new icon and the icon of source breakpoints is almost invisible:

![2019-08-29_12-57-34](https://user-images.githubusercontent.com/1898161/63934975-d0c6c400-ca5c-11e9-9ed1-439f46bc4b48.png)

**Comment by isidorn** [comment]
An issue with the square icon is that it looks like the stop sign.
I like this one but it needs to be thiner, so it looks less rounded.
