### ISSUE TITLE
Installing the extension via command line does not update extension viewlet 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7988]
1. Have an extension installed
2. Open the extension viewlet
3. Uninstall that extension from the command line
4. Go back to vscode - the extension still apears as installed and you can click uninstall
5. The extension now gets installed - even though I clicked uninstall

Perfectly the viewlet would update as soon as you use the command line. If that is not possible I would at least not expect that clicking on uninstall installs the extension again

**Comment by joaomoreno** [comment]
Tricky.

**Comment by joaomoreno** [comment]
Won't fix.
