### ISSUE TITLE
Improve name of "Set Data Breakpoint" action

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79884]
testing #79799 

The name of the context menu action "Set Data Breakpoint" is not very intuitive. Users not familiar with this concept will have a hard time understanding what this means.

VS uses this wording:
![2019-08-27_12-25-38](https://user-images.githubusercontent.com/1898161/63763979-1a30db00-c8c6-11e9-951b-b92cfb2c60f7.png)

I suggest to use something similar.

**Comment by isidorn** [comment]
I like `Break When Value Changes`.
And yes I agree that `Data Breakpoint` can be a misterious concept to the user.
