### ISSUE TITLE
Custom Data schema descriptions polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#79887]
Testing #79843 

These properties have no description

![image](https://user-images.githubusercontent.com/172399/63764119-68de7500-c8c6-11e9-9544-fa09f38c5357.png)

Suggest to make a pass over the descriptions and use full sentences that end with a '.' Suggest to mimic these descriptions http://json.schemastore.org/package.

![image](https://user-images.githubusercontent.com/172399/63765301-05097b80-c8c9-11e9-862b-7a80241f4590.png)

Suggest to change: 'Only workspace folder setting will be read' to 'Only workspace folder settings are considered.'

**Comment by octref** [comment]
Sample updated.
