### ISSUE TITLE
Multiple open to the side brings layout in a broken state

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79897]
Refs: https://github.com/microsoft/vscode/issues/79845

1. Have a smaller vscode window
2. Open explorer and start clicking on the `Open to the Side` context menu command
3. Every editor is opened in a new group reducing the available horizontal space
4. When there is no more space the explorer is no longer visible and the layout is in a broken state since I can no longer click on any of the Sashes to resize :bug:

Notice on the gif that I am trying to find the sashes but am not able

![openToTheSide](https://user-images.githubusercontent.com/1926584/63767123-063ca780-c8cd-11e9-8442-ab0ca19b103e.gif)

**Comment by isidorn** [comment]
Note that I can more easily getting into the sashes are broken state by having more than 3 groups side by side. Somehow the sashes are always off then. Adding label bug.

**Comment by octref** [comment]
Sashes now don't show, that's good, but I still want what terminal split does:

![image](https://user-images.githubusercontent.com/4033249/63975685-6ade3a80-ca64-11e9-8edc-f9b81ff66905.png)

**Comment by sbatten** [comment]
@octref what makes this tricky today is that the editor can increase its size beyond the currently allotted space and should expand, but agreed that this would be an improvement.
