### ISSUE TITLE
persisted data breakpoints are not reapplied

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79895]
Testing #79799 

- create a data breakpoint and verify that it works
- stop debug session
- start debug session
- try to hit data breakpoint again

Observe: breakpoint is not hit

When debugging this I noticed that mock-debug's `setDataBreakpointsRequest` is not called at all.

(And yes, mock-debug by default returns a "canPersist" value of true).

**Comment by isidorn** [comment]
Assigning to August to investigate furhter.

**Comment by isidorn** [comment]
@weinand Great catches wrt data breakpoints. Thanks a lot for nicely testing.
