### ISSUE TITLE
If two editors opened one above other, centered layout not working.

### ISSUE THREAD

**Issue by Shapovalov-Dmitry** [microsoft/vscode#79890]
Issue Type: <b>Bug</b>

Open one editor, then open one more and place horizontally one above the other. The centered layout seems not to be working.

VS Code version: Code - Insiders 1.38.0-insider (8cd00a7935eabef4aad0b0130b1d46daca0a47aa, 2019-08-27T06:12:19.868Z)
OS version: Linux x64 5.0.0-25-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz (8 x 1413)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.71GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Yes. The centered editor layout is disabled if there is more than one editor group opened due to limited space.
However this does not make sense if the editor groups are horizontall.

Assigning to me to look into.

**Comment by isidorn** [comment]
Please use this settings as a workaround `"workbench.editor.centeredLayoutAutoResize": false`
The centered editor layout does not look at the orientation of the groups, but simply if there is 2 or more in order to auto resize or not. And I would like to keep this simple.
