### ISSUE TITLE
Grid layout: hidding editor area should be done group by group

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79899]
Refs: https://github.com/microsoft/vscode/issues/79845

When we resize the sidebar or the panel on the side, and there is not enough space we decide to hide the editor area. This is a great feature and I like it.

However if in the editor area there are two groups side by side, it would be very nice that we firs thide one group, and only later the other.
Since currently we just hide the complete editor area. Which is not nice, since sometimes there is more than enough space for one group to still be shown.
Due to the current approach the whole thing feels a bit jarring and not smooth.

![snap](https://user-images.githubusercontent.com/1926584/63767696-a0e9b600-c8ce-11e9-8a1d-779ecc49d9c6.gif)

**Comment by joaomoreno** [comment]
Yeah nice to have, yet unlikely unless we place editors the same grid as the workbench.

**Comment by isidorn** [comment]
Agree that the editors should be the last to snap. We are a code editor after all and the editor part should have priority

**Comment by sbatten** [comment]
with toggle panel maximized being effectively the same as hiding the editor, I could be convinced that snapping is not necessary on the editor since you have a mouse action in the panel available to do this.

**Comment by joaomoreno** [comment]
> I could be convinced 

Then, I cast my spell: _João attempts to convince SteVen_.

**Comment by sbatten** [comment]
Hmmm what's your charisma stat? rolled a d20 and got a 4 :p

**Comment by isidorn** [comment]
18, that makes it 8 in total. He has some diplomacy skill points to add on top of that.

**Comment by joaomoreno** [comment]
Listen to @isidorn, he last held my character sheet.
