### ISSUE TITLE
marketplace download count unrealistically high

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#79894]
I think there is a bug with the download count in the marketplace. Two days ago I updated my extension [Svg Preview](https://marketplace.visualstudio.com/items?itemName=SimonSiefke.svg-preview) which had ca. 3.000 Installs and ca. 20.000 Downloads. Now it shows that there are ca. 3.000 Installs and ca. 2.500.000 Downloads.

![screenshot of extension in vscode marketplace](https://user-images.githubusercontent.com/23744935/63765767-0b4c2780-c8ca-11e9-8622-94900cc9a083.png)

I am guessing that there is a bug with the download count because it seems unrealistically high and the install count has only increased between 0 and 300.

**Comment by SimonSiefke** [comment]
Seems like my extension just got removed from the marketplace :(

**Comment by chrisdias** [comment]
@SimonSiefke sorry about this. we received an abuse report for this and through a multi-timezone miscommunication we unpublished the extension prior to contacting you (we take abuse seriously). We are investigating what is going on with the download counts and will republish/fix it ASAP, assuming everything looks ok.

**Comment by chrisdias** [comment]
We've finished up our investigation and reset the download count to 20k.  Extension is in an unpublished state, please go ahead and publish again.
