### ISSUE TITLE
Reload should preserve maximized panel

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79891]
Refs: #79845

1. Maximize the panel
2. Reload
3. Panel is not maximized 🐛 

Marking as a feature request since we never had this feature since panel could never be full height.
The ugly part about this flow is that we forget the previous size of the panel before the user maximized it (so he can not go back with a click)

**Comment by isidorn** [comment]
Also instread of reload you can toggle panel visibility via `ctrl/cmd + j`. That should aslo preserve the maximized panel

**Comment by isidorn** [comment]
Agree that the panel in a not almost maximized state never makes sense since the user looses the previous unmaximized state.

However I would still prefer that the panel remains maximized. Since the user can always click on the editor in the explorer / open editors view / quick pick and to get out of this mode. And you handle it already very nicely. So I am not worried about user being stuck at all.

Though I would love to hear the opinion from @tyriar since he is very passionate about this

**Comment by sbatten** [comment]
@isidorn I see your points. I went store the editor state and use it on launch but because of other eventing, the editor area gets restored anyway. I need to look more deeply to get the right fix for this. In the interim, I have pushed a fix that stores the editor visibility and uses that to set the panel back to its pre-maximized state.

**Comment by isidorn** [comment]
@sbatten thanks. That's fair. I do not think this is urgent for August. We can always look into it next milestone when we have more time.

**Comment by Tyriar** [comment]
> Though I would love to hear the opinion from @Tyriar since he is very passionate about this

I think the main users this would help right now are those that want to use a window as a dedicated terminal window which isn't me. However, it would be very useful when we get into the business of restoring terminals across sessions if they are the same size. Even better if the panel is correctly positioned right from the beginning before the terminal starts up.

**Comment by k-lepa** [comment]
> Also instread of reload you can toggle panel visibility via `ctrl/cmd + j`. That should aslo preserve the maximized panel

It doesn't preserve the original panel's size😔
![fullscreen-bug](https://user-images.githubusercontent.com/960814/64975204-1be33280-d8b7-11e9-8413-2d4a7c1fc967.gif)

This bug is very annoying because I use the shortcut `cmd-j` very often.
