### ISSUE TITLE
Link protection prompts for github.com although it is in trusted domain

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#79898]
Issue Type: <b>Bug</b>
Testing: https://github.com/microsoft/vscode/issues/79465
Open release notes
Click August Iteration Plan link (https://github.com/microsoft/vscode/issues/78844)
Get prompted if i want to open this external website
Click 'Configure Trusted Domains'
See that https://github.com is already checked
Expected: When clicking the August Iteration Plan link, the link should just open since it is marked as trusted

VS Code version: Code - Insiders 1.38.0-insider (8cd00a7935eabef4aad0b0130b1d46daca0a47aa, 2019-08-27T06:13:54.903Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.34GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.17.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.69.0
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.4
vscode-remote-extensionpack|ms-|0.16.0
azure-account|ms-|0.8.4
test-search-rg|rob|0.0.3

</details>

**Comment by stevencl** [comment]
The issue is that it wasn't obvious when the configure trusted domains widget came up that the user has to press OK. On first launch there should be a prompt to tell the user to click ok to accept the defaults. Or by default nothing should be checked which would make it more obvious that the user can check the ones that they want to trust and then click OK.

**Comment by octref** [comment]
Merged to #80489.
