### ISSUE TITLE
Link protection UI inconsistency

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#79900]
Issue Type: <b>Bug</b>
Testing: https://github.com/microsoft/vscode/issues/79465
See the following:
![image](https://user-images.githubusercontent.com/1704059/63767697-40ef1180-c8c6-11e9-82b4-6a0ecf00abc5.png)

I click the Open all links without prompt option, but can also unselect some of the links. Now I don't know what state I am in. Will all links open without a prompt, including the ones I unselected? Or will all links except for the ones I unselected open?

What I expected was that the open all links option would toggle the checked state of all links in the list.

VS Code version: Code - Insiders 1.38.0-insider (8cd00a7935eabef4aad0b0130b1d46daca0a47aa, 2019-08-27T06:13:54.903Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.77GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.17.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.69.0
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.4
vscode-remote-extensionpack|ms-|0.16.0
azure-account|ms-|0.8.4
test-search-rg|rob|0.0.3

</details>

**Comment by stevencl** [comment]
I don't agree. In the mockup above, if I click on a link to marketplace.visualstudio.com it is ambiguous if I will be prompted or not. The entry is not checked suggesting that I will be prompted, but open all links without prompt is selected, suggesting that I won't be prompted. Which one takes precedence? How do I know that?

**Comment by stevencl** [comment]
@misolorio - what do you think?

**Comment by misolori** [comment]
I would treat the "Open All Links" as the same as a "Select All" and select every item in the list. It is very ambiguous if you have some unselected and then "Open all links" is selected. Another option would be to disable the rest of the items when "Open all links" is checked, because that is what will trump all other selections and you want to be clear to the user what this will do especially when others are unselected.

**Comment by octref** [comment]
OK, I can try to make the quick input hide all items below the separator.

**Comment by octref** [comment]
This would involve a lot of change as we should use a completely different API to achieve this, so pushing out to next milestone.

**Comment by octref** [comment]
See See https://github.com/microsoft/vscode/issues/80595#issuecomment-531607624
