### ISSUE TITLE
Terminal Setting does not run programs in environment path

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#79907]
I included a path in my workspace setting `terminal.integrated.env.windows` hoping strictly when opening the integrated terminal, I can run any program which is in this path within my `terminal.integrated.env.windows` setting. Unfortunately any program in the path which I added, does not run within the terminal strictly in vscode ?

**Comment by SheepDomination** [comment]
This is not directly the problem I have, I hope someone can help as to why; when setting a path within either settings.json or workspacesettings.json for the terminal.integrated.env.windows. No programs in the path set run, when within strictly only the integrated terminal ?

**Comment by Tyriar** [comment]
Please don't create duplicates https://github.com/microsoft/vscode/issues/80261
