### ISSUE TITLE
Jupyter Notebook Integration PKI Support

### ISSUE THREAD

**Issue by umdstu** [microsoft/vscode#79917]
Using the built-in Jupyter Notebook support, it's impossible to connect to a server URI (from VSCode) which requires a user certificate. If I am understaning the commits for #6003 correctly, it appears to solve the opposite problem, by not rejecting unsigned certs the Jupyter server passes. However, it does not appear as though there is a configuration option to configure certs (cert/key/ca) and pass credentials (something lik e`withCredentials: True` pehaps?) so the server can even be accessed. Being able to pass a certificate authority file as well might alleviate the issue around #6003 as well.

Thoughts?

**Comment by weinand** [comment]
#6003 has no commits and is not related to the issue. You are referring to a different repository, right?
