### ISSUE TITLE
Mouse cursor doesn't disappear when typing

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#79915]
- VSCode Version: 
```
1.38.0-insider
185308c0dd317d73fe4c19dea347582dee9650de
x64
```
- OS Version:
Microsoft Windows [Version 10.0.18956.1000]

Steps to Reproduce:

1. Open VS Code
2. Create a new file 
3. Start typing 

Does this issue occur when all extensions are disabled?: Yes

Expected Behavior:
- Mouse cursor should disappear upon typing

Actual behavior:
- Mouse cursor is still visible after typing

Comments:
- I think this is related to Chromium (electron) because I see the same behavior on Google Chrome.
- It may be by design, but it's annoying. Most text editors hide the cursor when typing (for instance, good ol' _notepad_) in order to avoid the cursor covering text.
- If it's a Chrome design choice, I think it should be reviewed on VSCode, the reason being that Chrome is designed for consuming information, whereas VSCode is designed for the production of information.

**Comment by alexandrudima** [comment]
@bruno-brant I think by default Notepad does not hide the cursor when typing:

![typing-notepad](https://user-images.githubusercontent.com/5047891/63782128-35faa800-c8eb-11e9-88a8-8fce1280287d.gif)

**Comment by alexandrudima** [comment]
Oh, interesting. 

The mouse cursor hides automatically when typing in VS Code on the mac, I wonder if there's something special we would need to do on Windows.

**Comment by Gruntfuggly** [comment]
I wrote an extension to try and do something like this:
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.banish-pointer
Not sure it works very well though, but you could try it...

**Comment by alexandrudima** [comment]
VS Code is based on Electron, which is based on Chromium. This is an upstream issue in Chromium which was previously reported here -- https://bugs.chromium.org/p/chromium/issues/detail?id=254430
