### ISSUE TITLE
Small groups like to get bigger

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#79916]
Testing https://github.com/microsoft/vscode/issues/79845
I made some of my groups small, and then when I clicked on them they snapped larger. My mouse is a bit flickery in the gif, but you can see that the groups suddenly get larger.

![smallGroups](https://user-images.githubusercontent.com/38270282/63774133-e0b79a00-c8dc-11e9-9d67-ee65f617e603.gif)

**Comment by bpasero** [comment]
@alexr00 this is expected behavior actually if the editor group is at minimum size it will maximize once getting activated again. Is that it?

**Comment by alexr00** [comment]
Yes, that is it. I turned off the grid view and then it didn't happen anymore so I thought it was a bug.

**Comment by bpasero** [comment]
@alexr00 this should happen independent from having the grid enabled or not because the editors are always put inside a second grid. Can you clarify the difference you have seen?

**Comment by alexr00** [comment]
I saw a "minimized" editor not maximize when I clicked on it. However, I cannot reproduce now. I will re-open if it happens again.
