### ISSUE TITLE
a copy after a cut, even when no text is selected, overwrites clipboard with whitespace.

### ISSUE THREAD

**Issue by cfurst** [microsoft/vscode#79928]
Issue Type: <b>Bug</b>

1) select some text
2) press cmd-x (I've only seen this with keyboard shortcuts, with mouse commands, YMMV).
3) position cursor where you want to paste and press cmd-c (notice 'c' and not 'v').
4) press cmd-v and you should get whitespace pasted instead of your original text.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
xml|Dot|2.5.0
gitlens|eam|9.9.3
prettier-vscode|esb|2.2.2
code-runner|for|0.9.14
vscode-javac|geo|0.2.24
rest-client|hum|0.22.0
code-groovy|mar|0.1.2
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.11.7
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.10.0
vscode-manifest-yaml|Piv|1.10.0
vscode-spring-boot|Piv|1.10.0
vscode-graphql|Pri|0.2.1
java|red|0.47.0
vscode-yaml|red|0.5.1
vscode-java-debug|vsc|0.21.0
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-todo-highlight|way|1.0.4

</details>

**Comment by usernamehw** [comment]
There's an option to prevent copying without selection:

```js
"editor.emptySelectionClipboard": false,
```
