### ISSUE TITLE
Electron 6: debugging extension quits immediately

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#79929]
Testing #79731

* Open https://github.com/Microsoft/vscode-pull-request-github in Exploration on Ubuntu
* `yarn` and `yarn run watch`
* F5
* Extension debugging instance starts successfully and then quits immediately

No error at all in Debug Console.

**Comment by bpasero** [comment]
Adding @weinand @isidorn to investigate too.

**Comment by deepak1556** [comment]
Just to update this happens on all platforms, I tested on windows, macOS and linux.

**Comment by weinand** [comment]
When Electron is run as node (via the `ELECTRON_RUN_AS_NODE` flag), it immediately crashes when passing the `--inspect-brk` flag:
![2019-09-02_16-12-36](https://user-images.githubusercontent.com/1898161/64120440-7e5b0f80-cd9c-11e9-800e-6ef2e4f06540.png)

Passing a `--inspect` flag instead works fine.

**Comment by bpasero** [comment]
I wonder if this is a regression from https://github.com/electron/electron/issues/19316 or similar.

**Comment by deepak1556** [comment]
Fix at https://github.com/electron/electron/pull/20098 , should be available with next release.

**Comment by weinand** [comment]
Extension debugging works fine with Electron 6.
