### ISSUE TITLE
Regex-based replacing doesn't work properly when replacing in files.

### ISSUE THREAD

**Issue by arielbeje** [microsoft/vscode#79924]
- VSCode Version: 1.38.0-insider
- OS Version: Windows 10 Enterprise 1903 x64 (OS Build 18362.295)

Steps to Reproduce:
1. Make a directory with a file (or multiple files) containing text that matches the regex `^((\d{2}:?){2})\.(\d{3}) --> ((\d{2}:?){2})\.(\d{3})\n`
2. Open the directory with VSCode
3. Search for the aforementioned regex and try to replace with the string `00:$1,$3 --> 00:$4,$6\n`
4. Replaces will show the preview with `$x` instead of the replacement, and will show the same after replacing

Does this issue occur when all extensions are disabled?: Yes

Notes: 
- This exact find/replace works on single files.

### Example
File:
```
00:11.123 --> 00:14.245
Example
```
Result with `replace in files`:
```
00:$1,$3 --> 00:$4,$6
Example
```
Result with regular `replace` and same parameters:
```
00:00:11,123 --> 00:00:14,245
Example
```

NOT a duplicate of #21494

**Comment by JanMergan** [comment]
Two days ago it was still working. Yesterday I had an update and now I have the same problem.
I have to change all CaptionML into Caption property which is a huge job without regex.
![afbeelding](https://user-images.githubusercontent.com/54975815/64407534-d63b9400-d084-11e9-8bfd-33a447a49acd.png)

Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
OS: Windows_NT x64 10.0.14393

**Comment by eXigiouS** [comment]
Thanks for pointing me in the right direction JanMergan, I went and installed the June 2019 version instead, and on this version it works properly.
https://code.visualstudio.com/updates/v1_36

Version: 1.36.1 (user setup)
Date: 2019-07-08T22:59:35.033Z
OS: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
Looks like it works now, this was fixed in another issue.
