### ISSUE TITLE
Insert final newline moves cursor

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#79927]
Steps to Reproduce:

1. Set `Files: Insert Final Newline` to `true`.
2. Input some words in a ts file.
3. View the competion items in competion hover.
4. VSCode inserts the final newline and close the competion hover.
5. Frustrated.

![关闭completion](https://user-images.githubusercontent.com/5213431/63786960-97d80380-c925-11e9-8ff0-2328cedadf90.gif)

**Comment by jrieken** [comment]
> VSCode inserts the final newline and close the competion hover.

Sorry, I don't understand what's happening here. Do you accept a completion? How/why does the widget close? Are pressing any key? Can you reproduce without extensions? What version of VS Code is this?

**Comment by sumneko** [comment]
> > VSCode inserts the final newline and close the competion hover.
> 
> Sorry, I don't understand what's happening here. Do you accept a completion? How/why does the widget close? Are pressing any key? Can you reproduce without extensions? What version of VS Code is this?

1. I did not accept any completion.
2. The widget closed by VSCode due to inserting final newline.
3. Dose not press any key except down arrow (This key has nothing to do with the problem.).
4. This can be reproduced without any extensions.
5. VSCode version:
```
版本: 1.37.1 (user setup)
提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
日期: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by jrieken** [comment]
> This can be reproduced without any extensions.

Sorry, no. I cannot reproduce. Please follow these steps to really disable extensions. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by sumneko** [comment]
> > This can be reproduced without any extensions.
> 
> Sorry, no. I cannot reproduce. Please follow these steps to really disable extensions. Select 'Extensions View > ... > Disable all Installed Extensions', reload, and try again. Thanks.
> 
> <img alt="screen shot 2018-05-09 at 08 45 10" width="577" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

Only reproduced when editing the last line, I forgot to mention this key point. It's my mistake.

**Comment by sumneko** [comment]
![final newline](https://user-images.githubusercontent.com/5213431/63837552-41fb6e00-c9ae-11e9-8629-7abcbcbe2268.gif)

**Comment by sumneko** [comment]
I did a further test, to reproduce this, the following conditions must be met simultaneously:
1. Set `Files: Insert Final Newline` to `true`.
2. Set `Files: Auto Save` to `afterDelay`.
3. Input on the last line.

**Comment by jrieken** [comment]
Thanks. I can reproduce now.

**Comment by jrieken** [comment]
Ok, full steps

* enable final newline insertions
* enable auto save
* type and trigger suggest on the very last line
* wait a little
* :bug: suggest widget closes

The debugger state below shows what's happening. The insert final newline logic kicks in (while suggest is active) and ends up moving the cursor position (from line 42 to line 43). Because the cursor moves suggest cancels and hides the widget.

<img width="1339" alt="Screenshot 2019-08-28 at 10 25 28" src="https://user-images.githubusercontent.com/1794099/63838817-5de71b80-c97e-11e9-9c54-2be0c8a18bb7.png">

**Comment by bpasero** [comment]
@alexandrudima need your advice here, in the end I [call](https://github.com/microsoft/vscode/blob/4acd9c37cd0b346538c99a2a5c2b68fdb0822b7d/src/vs/workbench/api/browser/mainThreadSaveParticipant.ts#L133):

```ts
model.pushEditOperations(prevSelection, [EditOperation.insert(new Position(lineCount, model.getLineMaxColumn(lineCount)), model.getEOL())], edits => prevSelection)
```

I think this is not just about inserting a final new line but any edit operation can potentially close suggest.

**Comment by jrieken** [comment]
> Btw for me the cursor does not move, but suggest still closes.

Maybe that's an intermediate cursor state?

**Comment by alexandrudima** [comment]
@bpasero I think because the edits are done directly on the model, the cursor of the current editor can only adjust to the edit. It would be better if the edits would be done through the current editor. i.e. `ICodeEditor.executeEdits`

**Comment by bpasero** [comment]
I pushed  both a fix in `cursor.ts` with Alex and adopted the `ICodeEditor.executeEdits`. I stayed away from using it for other places where we use the model edit.
