### ISSUE TITLE
can't change encode with text files

### ISSUE THREAD

**Issue by chenxuuu** [microsoft/vscode#79926]
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. make a new file, start with some 0x00 bytes, after those are really text
2. open it, vscode will mind you this file is bin file, you need to click and open it:
![图片](https://user-images.githubusercontent.com/10357394/63785201-83463c00-c922-11e9-9933-00d090e8924f.png)
3. then you can't change this file's encoding:
![2019-08-27_23-30-30](https://user-images.githubusercontent.com/10357394/63785396-e0da8880-c922-11e9-827e-64a0d588cd81.gif)

I only changed two bytes
![图片](https://user-images.githubusercontent.com/10357394/63785929-bb01b380-c923-11e9-9afa-638ff3cfe6c8.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
blamer-vs|bea|0.5.0
love|bsc|0.3.6
vscode-markdownlint|Dav|0.30.1
xml|Dot|2.5.0
gitlens|eam|9.9.3
diff-tool|jin|0.0.1
svn-scm|joh|1.54.4
luacoderassist|liw|2.3.3
vscode-language-pack-zh-hans|MS-|1.37.5
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
csharp|ms-|1.21.1
vsliveshare|ms-|1.0.721
indent-rainbow|ode|7.4.0
code-settings-sync|Sha|3.4.2
vscode-hexdump|sle|1.7.2

</details>

**Comment by bpasero** [comment]
@chenxuuu what encoding is that that uses 0x00 bytes? We use that to detect binary files. If you need to use these bytes, set a UTF16 LE or BE BOM.

**Comment by chenxuuu** [comment]
@bpasero 
problem is, in old version, I can change those files' encoding, but I can't do this in new version
my serial port logs may start with any data, include 0x00 or 0x40-0xff

**Comment by bpasero** [comment]
Great catch, I pushed a fix for that.
