### ISSUE TITLE
Signature help binding?

### ISSUE THREAD

**Issue by chadrien** [Microsoft/vscode#7992]
- VSCode Version: Version 1.3.0-insider (1.3.0-insider) – d808ba31a697998f36c9c2cbdfc5f8d8e8b16ca2
- OS Version: 10.11.5 (15F34)

Is there a way to trigger/bind a keyboard shortcut to open the signature help window?
For now when it's closed I can't find any way to reopen it, apart from cheap hacks like removing the arguments already written or adding a coma after an argument.

**Comment by jrieken** [comment]
It's `ctrl+shift+space`

**Comment by chadrien** [comment]
As you can see from this gif, `ctrl+shift+space` does not work for me :/

![signature help](https://cloud.githubusercontent.com/assets/1788218/16305313/8d6b9740-3959-11e6-84f8-35d422496a94.gif)

Can't find `ctrl+shift+space` either in the default keyboard shortcuts.
Anyway if a keyboard shortcut should exist, could you provide me the corresponding command? At least I would be able to add the shortcut my self :)

**Comment by jrieken** [comment]
This is the default config (actually I was wrong it's `cmd` on mac`)

```
{ "key": "shift+cmd+space",       "command": "editor.action.triggerParameterHints",
                                     "when": "editorTextFocus" }`
```
