### ISSUE TITLE
Git: clone should list recent folders/repos

### ISSUE THREAD

**Issue by macxcool** [microsoft/vscode#79925]
When using Git: clone from the Command Palette, the repo URL box should give access to recent folders/repos as you type.

Also, Instead of just using the name of the repo (folder name) it should optionally prompt for a folder name to clone into.

**Comment by joaomoreno** [comment]
> When using Git: clone from the Command Palette, the repo URL box should give access to recent folders/repos as you type.

I don't think this makes much sense for the average user. How often do you actually clone the same URL? 99% of the times you're cloning a URL you never cloned before.

**Comment by macxcool** [comment]
I do, regularly, clone the same repo over and over. We use it as a template for software installation scripts.
As for the folder name. For my use-case, every time we clone the template repo we want to use a unique folder name. Right now if we create the folder first and point to it, it just creates the template folder inside that which is not what we want.
Maybe these two things (or even one of them) could be a configuration option? That would be kind of awesome.
Or is there a way for me to customize my own 'wizard' to use instead of the default 'git clone' command?

**Comment by joaomoreno** [comment]
> Or is there a way for me to customize my own 'wizard' to use instead of the default 'git clone' command?

Absolutely, you can write an extension which creates an interface better suited for your workflow, here's how to get started: https://code.visualstudio.com/api
