### ISSUE TITLE
cursorSurroundingLines causes text to be selected when clicking near the region

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#79934]
Testing #79834

![gif](https://user-images.githubusercontent.com/35271042/63796172-60803d00-c8ba-11e9-8b6e-283a4d6b601d.gif)

Steps:
1. Set `editor.cursorSurroundingLines` to something like 7
2. Attempt to click on the last line that is in view in the editor (ensure there are more lines below)
3. :bug: Clicking will select the region of text and scroll to the point

**Comment by rebornix** [comment]
I pushed a change to ignore single mouse/touchpad clicking in the *surrounding* area as it will trigger a scroll and then lead to selection. Let's see how it works once we ship Stable and have a Insiders build from master.
