### ISSUE TITLE
Add option to cursorSurroundingLines to ignore clicks

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#79935]
Testing #79834

It would be great if there was an option in `editor.cursorSurroundingLines` to ignore clicks and only act on scrolling via the keyboard. I like this feature but don't want this to apply to mouse clicks.

**Comment by daletman** [comment]
Please also add the option for a scroll delay when clicking. Currently, when I click the editor does scroll instanly even before I can release the click and so I select my code.

**Comment by myfonj** [comment]
#79934 was fixed for simple click, but the same issue prevails for case user intends to **select** text in area affected by `editor.cursorSurroundingLines` using mouse: as soon as single letter becomes selected, this selection is pushed out of the border area, text rolls under pressed mouse cursor what continues to select more etc.. what is hardly ever the intended behavior for strictly horizontal mouse selection that does not leave editor area:

![surroundUnIntededSelection](https://user-images.githubusercontent.com/1761395/67399031-e7485200-f5ab-11e9-8a5a-b0688bc00a99.gif)

I guess it was overlooked in #79934, but if there was proposed option to exclude mouse actions from  cursorSurroundingLines interventions it would be viable workaround.

**Comment by rebornix** [comment]
thanks, I agree that having ways to opt out for mouse has great value.

**Comment by rebornix** [comment]
By default it won't do any scroll off when triggered from mouse.
