### ISSUE TITLE
Please add the ability to comment out code from the right click menu

### ISSUE THREAD

**Issue by PsychoticCob** [microsoft/vscode#79938]
Issue Type: <b>Feature Request</b>

I would like the ability to select multiple lines of code and right click and select a menu item that would alow me to comment out the selected section of code.  If the code was commented out the menu item would change so I could uncomment out the selected code

Using Extension: PowerShell
 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 17.7.0

**Comment by gjsjohnmurray** [comment]
There already seems to be an extension for this, though I haven't tried it myself.

henryclayton.context-menu-toggle-comments

**Comment by gjsjohnmurray** [comment]
And ebicochineal.add-contextmenu-toggle-comment looks like it might meet your need.
