### ISSUE TITLE
Error: Model is disposed! on trying to complete a suggestion

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#79949]
Issue Type: <b>Bug</b>

Opened the file and immediately went to add the final component of the path (previously exported from `index`), and it wouldn't let me click or tab it. Other autocompletes worked, but that one consistently didn't. After restarting maybe 10 times, reproduced in like 3 of them.

![image](https://user-images.githubusercontent.com/8586769/63811832-620f2c80-c8dd-11e9-9b75-8a0dd52a45bf.png)

VS Code version: Code - Insiders 1.38.0-insider (8cd00a7935eabef4aad0b0130b1d46daca0a47aa, 2019-08-27T06:10:29.182Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (3.78GB free)|
|Process Argv|-psn_0_8640573|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

**Comment by sandy081** [comment]
Any steps to verify?

**Comment by jrieken** [comment]
Sorry, no steps but I can explain the stack trace and the code change

**Comment by sandy081** [comment]
Looked at code and understood the change. Verified by code review.
