### ISSUE TITLE
terminal 中文显示有误

### ISSUE THREAD

**Issue by zhaoleis** [Microsoft/vscode#7994]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
![image](https://cloud.githubusercontent.com/assets/10767337/16263591/be6942a0-38a7-11e6-9ac0-120dceebca0c.png)

**Comment by Emeryao** [comment]
insider 版本已经改好了 等着release就行了
另外 个人感觉title写中文不太好吧 毕竟都是老外

**Comment by Emeryao** [comment]
I think it's better to use English for issues Xiongdi

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7062
