### ISSUE TITLE
Code not showing up

### ISSUE THREAD

**Issue by godzilla1but1small** [microsoft/vscode#79941]
I need to open a folder to make some edits on my code, but when I open the folder in Visual Studio 2019 none of the files show up, it's just a gray screen and I can't do anything other than run the code. Here's some pictures:

https://gyazo.com/f681ce7a84d958f6ed10221fb800a76c

https://gyazo.com/b7382dfcbb9a4d9e881cc3c1fda2b8d8

I can open each individual file, but I have around 10 of them so I need to open them all at the same time.
 i dont know how to delete this but i figured it out

**Comment by weinand** [comment]
This repository is for "Visual Studio **Code**" not for "Visual Studio".
