### ISSUE TITLE
Make a potion to choice the view,when launch VSCode.

### ISSUE THREAD

**Issue by Ircon** [microsoft/vscode#79959]
When I submit the new issue, I already read some docments. But I don't sure if I miss somthing.My English is poor, maybe somthing is worry in this context. I will try to keep it correct.

Now, VSCode has the remote function. But sometime, the reamote hosts are not open. But when we lauch VSCode, VSCode open the last workspace by default.

If the last workspace is in a remote host and it does not work, we need to close it  and open other work spaces.

So,I think we can set a option to choose the work space which we want or just a blank space and a welcome view.

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/editor/command-line for details of the optional arguments you can use when launching VSCode.

Perhaps you want `code -n`

**Comment by Ircon** [comment]
Thank you very much!!!!!
