### ISSUE TITLE
Make prelaunch prompt for option when used with a group

### ISSUE THREAD

**Issue by luchong12** [microsoft/vscode#79952]
I've setup 3 different build tasks that are interchangeable and put them in a group `build`. I don't want any of them to be default, but I do want to run (any) one of them at prelaunch. I haven't found a way to get vscode to prompt for the task to use at prelaunch. I was thinking something like:

`prelaunch: "build"`

where `"build"` is the name of the group instead of the name of a task, to make vscode prompt to choose one of them (pretty much like `Task: Run Build Task` but at prelaunch).

**Comment by alexr00** [comment]
With 1.39 we now support `${defaultBuildTask}`! If you don't have a default build task or if you have multiple default build tasks then it shows you a quick pick to choose which one.
