### ISSUE TITLE
Popup info windows don't have a scrollbar

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#79953]
Issue Type: <b>Bug</b>

When a popup intellisense window is shown, it does not have a scrollbar - if the text is large, it takes up the whole window. Screen picture included below

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/13488/63814479-fe95f680-c8fe-11e9-95fd-0bbaf5593aa3.png">

(Compare latest Insiders (non Exploration):

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/13488/63814507-1c635b80-c8ff-11e9-84cd-2da801a52dce.png">

VS Code version: Code - Exploration 1.38.0-exploration (15bc1af92f1f2f087c741b9d2636fee31a12682b, 2019-08-27T06:41:22.709Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (7.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.900.0-next.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
Angular2|joh|8.1.1
json-to-ts|Mar|1.5.5
csharp|ms-|1.21.1
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.8.1
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@jtsom Can you try to reproduce on our insiders build? Or is it only happening on exploration build.

@bpasero Is it a known issue in exploration?
