### ISSUE TITLE
Couldn't get multi-select to work with FileExplorer sample

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#79958]
- VSCode Version: 1.38 Insiders
- OS Version: Windows 10

Found while testing https://github.com/microsoft/vscode/issues/79819

Turn on canSelectMany: true in sample FileExplorer.

![image](https://user-images.githubusercontent.com/12818376/63818982-567d2f00-c8f8-11e9-8963-0b2da60679ef.png)

Open the File Explorer custom view and click on blank space below tree to get the cursor into the view without opening a view. Cursor down to highlight a file. Try to shift+cursor down to multiselect but just moves highlight.

What is weird is that I thought it was working earlier in the day but no longer.

**Comment by alexr00** [comment]
@gregvanl is is possible you didn't have https://github.com/microsoft/vscode/commit/98574d61ca1763323baaafe2ab49839964b7e93d ?
With that fix, I can't reproduce the issue you saw.
