### ISSUE TITLE
The error and warning list increments with the same items after every typing. 

### ISSUE THREAD

**Issue by heshuimu** [Microsoft/vscode#7996]
- VSCode Version: 1.2.1
- OS Version: macOS Sierra 10.12 Beta(16A201w)

Steps to Reproduce:

I was using VS Code with **Legacy OmniSharp** to develop Unity projects. There is a plugin I used has a wrapper script used a namespace that Unity somehow did not expose (although the code compiles since the namespace does exist), which shows as an error. There are also several warnings due to unnecessary using directives.Whenever I stop typing the error/warning counter would go up and it would be several duplicated entries for one error/warning. 

1. Open a Unity project and set up to use VS Code with [dotBunny/VSCode](https://github.com/dotBunny/VSCode).
2. Create a new script and write something so that it makes an error or a warning.
3. Create another script, and while writing things in it, watch the error/warning counters go up whenever OmniSharp does the check. Reveling the list will show duplicated error/waring items.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#593

**Comment by heshuimu** [comment]
Hi, I am just commenting to give feed back on what I found later on. 
I used C# plugin (not the legacy version) on a Windows 10 computer with VS Code 1.3 installed. This issue also occurred when I write C# code in it. The C# plugin did not solve this issue for OS X either.
