### ISSUE TITLE
Throw or log warning when file is not in extension folder

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#79967]
Testing #79836

At least with images it seems that only those inside the extension's folder can be loaded, others fail to load with an error. That makes sense for security, can we add a warning or throw in the `Webview.asWebviewUri` API when that is not the case?

**Comment by chrmarti** [comment]
Also: Throw when the parameter is not a `file:` URI. /cc @bpasero

**Comment by mjbvz** [comment]
Wrong issue closed in commit

**Comment by mjbvz** [comment]
After thinking about this more, I don't think we want extra checks in `asWebviewUri`. It should be valid to call `asWebviewUri` on a resource that comes from a custom file system provider (a non `file:` uri)
