### ISSUE TITLE
Display focus border for buttons & panels only when you press Tab || Add focused input field border in theme options

### ISSUE THREAD

**Issue by I0F** [microsoft/vscode#79968]
Hi,

So I don't know if I'm the only one, but I find the focus border that's being displayed on focused buttons and panels - when you click on them with the mouse - annoying.
But I don't mind the focus border for input fields.

With the current theme options, you can either hide this border completely or have it showing on everything that's in focus.

I would like the app to behave more like other web apps when it comes down to focus borders.
For example, on web pages in Chrome if you click on any other object except for input field, they don't show focus border. But when you list through them with Tab they do. 
I would like that for VSCode too.

OR add another theme parameter focusInputBorder, so I can make focusBorder transparent, but still have the active input border which I like.

Example of what I mean:
![example](https://user-images.githubusercontent.com/18104031/63835167-29239600-c977-11e9-95ab-8e50f7c82592.jpg)

**Comment by bpasero** [comment]
We will not change this for accessibility reasons but you are free to change this color. I for example configure it as:

```json
"workbench.colorCustomizations": {
    "focusBorder": "#f3f3f3"
}
```

**Comment by I0F** [comment]
Ok, so idk if I made myself clear enough.
I want the focus border around the text fields, but not around the buttons and panels.

So can you by any chance add another parameter lets say focusInputBorder, which (if set) will override focusBorder only for input fields.
That way I can set focusBorder to transparent, and prevent it showing on buttons & panels; 
and set focusInputBorder to blue and have it showing on active input fields.

Thanks!
