### ISSUE TITLE
Clipped error icon in keybindings (JSON) editor

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#79966]
![image](https://user-images.githubusercontent.com/172399/63830571-c3caa780-c96c-11e9-97dc-73fb4f08ed09.png)

**Comment by sandy081** [comment]
We validate the `keybindings.json` content and showing errors, agreed that we should use diagnostics instead. @alexandrudima FYI.

**Comment by alexandrudima** [comment]
@misolori There are other cases like this one:

![image](https://user-images.githubusercontent.com/5047891/63919423-05c41e00-ca3f-11e9-913a-1d15ebffd496.png)

It is used here as a way to tell you that WYSInotWYG (!WYSIWYG):
![image](https://user-images.githubusercontent.com/5047891/63919485-212f2900-ca3f-11e9-9b1f-80afc60e50e0.png)

**Comment by misolori** [comment]
@alexandrudima in those cases can we also surface an info/blue squiggle? I think that would help bring more visibility to it.
