### ISSUE TITLE
Code block collapse optimzation

### ISSUE THREAD

**Issue by qinxiaoxian** [microsoft/vscode#79973]
Issue Type: <b>Feature Request</b>

Code block collapse optimzation suggest:

Current appearance:
![image](https://user-images.githubusercontent.com/20558478/63842440-26489580-c9b7-11e9-9df1-724da4bd31d3.png)

Expected appearance:
![image](https://user-images.githubusercontent.com/20558478/63842511-4a0bdb80-c9b7-11e9-9ae3-1dbbc8ee44e2.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/3352
