### ISSUE TITLE
Remote: extension installed but still grayed out and do not show tooltip why they are greyed out

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#79979]
- in a local window, install an extension as VSIX
- open a reopen window (e.g. WSL: Debian). Click on 'Install in WSL: Debian'
- Reload.
The extension seems to be installed but is still grayed out

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/63847851-eec5f300-c98e-11e9-873e-619e4fd9eeb4.png)

**Comment by sandy081** [comment]
@aeschli This is expected. Extensions is greyed out because it is enabled in remote server.

**Comment by aeschli** [comment]
Oh, I din't look at the second section which shows the extensions installed on Debian.

Maybe some extra information why it is grayed out would help. Or maybe filter it from the local view.

**Comment by sandy081** [comment]
Information is available on hover. 

> Or maybe filter it from the local view.

This will confuses the user why the extension is not there in local server.

**Comment by aeschli** [comment]
I don't get a hover (Windows 10, 1903)
