### ISSUE TITLE
Live Share extension automatically enabled after update

### ISSUE THREAD

**Issue by TareqNet** [microsoft/vscode#79972]
- VSCode Version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
- OS version: Darwin x64 18.7.0 (macOS 10.14.6)
- Live Share Extension version: 1.0.721

Hello

I installed Live Share extension on VS Code on macOS.
I disabled this extension. But it automatically enabled each time after updating the extension.

I reported an issue on Live Share issues: [this link](https://github.com/MicrosoftDocs/live-share/issues/2714#issuecomment-525519704), but one of the developers' team closed the issue with this message:
> Hey @TareqNet, we don't have control over whether Live Share is enabled or disabled in VS Code. You can file a bug with VS Code if you want to follow up: https://github.com/microsoft/vscode

**Comment by sandy081** [comment]
@TareqNet Cant reproduce it. I have old version of live share extension and disabled it. I do not see it is enabled after update.

How are you updating the extension?

**Comment by TareqNet** [comment]
It's updating automatically when there is a new version. This issue happened about 5 times.
Every few days I notice it's enabled, or I notice when there is new auto-update is installing then after requires restart vs code the extension enabled automatically.

**Comment by sandy081** [comment]
Is it happening only with this extension or you see this with other extensions?

**Comment by TareqNet** [comment]
Yes only with this extension

**Comment by sandy081** [comment]
Can you please try to reproduce this with different user data directory and extensions directory. You can do this by starting vscode from cli as follows

`code --user-data-dir <user-data-dir-path> --extensions-dir <extensions-dir-path>`
