### ISSUE TITLE
"Open a remote window" dropdown menu truncating menu items

### ISSUE THREAD

**Issue by caleb** [microsoft/vscode#79974]
The menu that pops up when clicking "Open a remote window" has the last one or two letters truncated with ellipses.

![Screenshot from 2019-08-27 10-35-18](https://user-images.githubusercontent.com/4692/63781274-82c48b80-c8b7-11e9-9b86-4d45ee02ed74.png)

- VSCode Version: 1.38.0-insider and 1.37.1
- Local OS Version: Arch Linux 5.2.9, GNOME 3.32.2
- Remote OS Version: N/A
- Remote Extension/Connection Type: N/A

Steps to Reproduce:

1. Click the "Open a remote window" button in the lower left hand corner of the VS Code window

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by TylerLeonhardt** [comment]
@caleb 👋  hi I'm the new owner of quick-pick. This issue is pretty old so I wanna ask... Are you still seeing this?

**Comment by caleb** [comment]
Unfortunately I do not use Linux as my desktop anymore and don’t have that install to test it out.

**Comment by TylerLeonhardt** [comment]
No problem! Considering no one else has commented in this and no one has given it a +1 I'm going to close this. If you do end up going back to this setup and still see this, don't hesitate to reach out again!
