### ISSUE TITLE
Custom trees: multi select context should send array only if user clicked inside selection

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79981]
Refs: #79819

1. Have some custom tree with a command
2. Select 5 elements
3. Trigger an inline command on the 6th element which is not part of the selection

We still pass the selected 5 elements to the extension.

We should only pass the seelction if the command is exectued in the context of the selection (user clicked inside the selection).

Note that the vscode explorer already behaves like this and we should aim to be consistent.

Also native os tree behave like this: checkout mac finder and probably windows explorer.

**Comment by alexr00** [comment]
These were good bugs, thank you!
