### ISSUE TITLE
Custom trees: primary element should be a part of the array in the context

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#79982]
Refs: #79819

Have some custom tree with a command
Select 5 elements. Trigger an inline command on one of those 5 elements. We will pass
object and array of 4 elements.

The first element is fine, but the array should contain all the elements including the primary one. That way the extensions who support multi select could just focus on the second argument and ignore the first not having to do array concatination.

Note that the vscode explorer already behaves like this and we should aim to be consistent.

**Comment by RMacfarlane** [comment]
I'm not seeing anything passed as a second argument on the latest insiders.

I'm using the github pull request extension and I added the "canSelectMany" argument to the options to create tree, and modified an existing command on a node to have two arguments. The first argument is the tree element as before, but the second is undefined.

**Comment by RMacfarlane** [comment]
Nevermind, there was something funky going on with the liveshare extension that I can no longer reproduce that was impacting my extension debugging.
