### ISSUE TITLE
No code assist for extension setting

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#79984]
Verifying https://github.com/microsoft/vscode/issues/73985

- Have an extension that contributes a machine-overridable setting

e.g. `testFoo.test-machine-overridable` from [ext-machinescope-test-0.0.3.vsix.zip](https://github.com/microsoft/vscode/files/3550381/ext-machinescope-test-0.0.3.vsix.zip)

- open user and workspace settings in the settings editor.
- Code assist after 'testFoo'. No proposals for `testFoo.test-machine-overridable`

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/commit/fefdc17dcd4614727eff2e88f133688f93ab7212
