### ISSUE TITLE
 'machine-overridable' can be set and read in user settings

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#79983]
Verifying https://github.com/microsoft/vscode/issues/73985

- Create a machine-overridable settings

e.g. 'testFoo.test-machine-overridable' from [ext-machinescope-test-0.0.4.vsix.zip](https://github.com/microsoft/vscode/files/3550453/ext-machinescope-test-0.0.4.vsix.zip)

- in a normal (non-remote window) set it in user and workspace settings
   -> no errors (as expected)
- open the folder in a remote window
   -> no errors (expect error in user settings)

The UI only offers the setting in machine and workspace, but the editor schema seems to be lacking the schema.

- clear workspace setting and run`Test Foo Setting` command. You can see that the value is read from the user settings.

**Comment by aeschli** [comment]
[ext-machinescope-test-0.0.3.vsix.zip](https://github.com/microsoft/vscode/files/3550381/ext-machinescope-test-0.0.3.vsix.zip)

**Comment by sandy081** [comment]
Good catch @aeschli. There is a bug that if the setting is already overridden in user settings, it is being read because defaults are getting registered lately. It needs reprocessing after defaults are registered.

**Comment by sandy081** [comment]
Also fixed the schemas to show the suggestions correctly.
