### ISSUE TITLE
Files being opened and unsaved, after replace all

### ISSUE THREAD

**Issue by prathyusha191491** [microsoft/vscode#79991]
1. search some content globally in the project or specify some folder,
2. enter replace content and click on replace all. 
3. but in changed files like bitbucket updates, showing all the changes 

it's showing all the files which are modified using replace, staying opened and unsaved. 

Please resolve this soon.

**Comment by weinand** [comment]
Do you have "auto save" enabled?

**Comment by weinand** [comment]
no response. Closing.
