### ISSUE TITLE
Message Error: localhost:4200 application not found

### ISSUE THREAD

**Issue by JorgelGtzGtz** [microsoft/vscode#79994]
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. I try run the command ng serve -o for run the angular project but sent the message box " localhost:4200 application not found" but I can't close the message

![ErrorVisualStudioCode](https://user-images.githubusercontent.com/37045031/63865465-7d724a00-c966-11e9-861b-fd4b8ff57d91.PNG)

**Comment by weinand** [comment]
How is this related to VS Code?
In your single step from above you are not referring to anything related to VS Code.

**Comment by weinand** [comment]
no reply. closing.
