### ISSUE TITLE
Type script syntax highlighting error

### ISSUE THREAD

**Issue by oaabhilash** [Microsoft/vscode#7999]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1.  Create a type script file with the following content
```javascript
 export class sampleClass  {
        public equipmentTypeList: string[] = ["FAX", "OFFICE PHONE"];
        public pbxEquipmentType = "FAX";
        public spliceRightStripName = "TE"; 
        public cablePairStatusValues: any[] =  
            [       
                { statusText: "Assigned" },
                { statusText: "Faulty" }, 
                { statusText: "Not in Use" },
            ];
        public cablePairStatusValueForAssigned = "Assigned";
        public cablePairStatusValueForFaulty = "Faulty";
        public phoneCircuitType = "Phone";
 }
```
2. The syntax highlighting after line 8 of the code above is not correct.
Tested for following themes
Default (Dark)
Visual studio Dark and
Visual Studio light
![syntaxhighlightpreview](https://cloud.githubusercontent.com/assets/10986887/16266253/dea44e58-3851-11e6-9b50-cb4963197352.PNG)

Note: if the opening square bracket on line 7 is moved to line 6 then the syntax highlighting is OK.

**Comment by Emeryao** [comment]
```typescript
export class sampleClass  {
        public equipmentTypeList: string[] = ["FAX", "OFFICE PHONE"];
        public pbxEquipmentType = "FAX";
        public spliceRightStripName = "TE"; 
        public cablePairStatusValues: any[] = new Array<any>(  
            [       
                { statusText: "Assigned" },
                { statusText: "Faulty" }, 
                { statusText: "Not in Use" }
            ]);

        public cablePairStatusValueForAssigned = "Assigned";
        public cablePairStatusValueForFaulty = "Faulty";
        public phoneCircuitType = "Phone";
 }
```

these code work fine on my vs code:1.3.0-insiders

**Comment by oaabhilash** [comment]
I just checked the typescript handbook 
https://www.typescriptlang.org/docs/handbook/basic-types.html
It looks like the way I initialized is allowed and it does compile with tsc.
![capture](https://cloud.githubusercontent.com/assets/10986887/16266710/3da0911c-3854-11e6-9ca1-84c07ff20e27.PNG)

**Comment by Emeryao** [comment]
@oaabhilash 
I think the local variable announcing by `let` is a little different with the proerty/field of a class.
JUST my own opinion. :laughing:

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#197
