### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by SpectralKH** [microsoft/vscode#79995]
VSCode already supports SCSS, but not indented Sass, which is pretty weird. The only difference between the two is that Sass is indent based instead of using curly braces and semicolons. Because of that, it doesn't sound like a huge undertaking to support it, at least to me.

There are some closed issues requesting Sass support already, concluding that support for Sass should come from extensions. It sounds like it wasn't taken into account how similar SCSS and Sass are.

**Comment by weinand** [comment]
We defer to extensions to provide this support, please see https://marketplace.visualstudio.com/search?term=sass&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by SpectralKH** [comment]
@weinand I'm aware of that. If you didn't, could you please read the whole issue and explain why this decision is made? Am I wrong in that it would be easy to implement on top of the existing support for SCSS?

**Comment by weinand** [comment]
If it is easy to implement, you are invited to submit a PR.

**Comment by SpectralKH** [comment]
@weinand Thanks for responding. I tried looking into it, and it turns out there's an open issue about Sass support in the vscode-css-languageservice repo.
