### ISSUE TITLE
ターミナルの文字について

### ISSUE THREAD

**Issue by WhiteGuineePig** [microsoft/vscode#79998]
Issue Type: Bug or My Mistake

ターミナルに表示される文字が全て2バイト文字の様になっていて困っています。正確には全ての文字の間に半角スペースが挿入されています。
![やっほい0](https://user-images.githubusercontent.com/54632880/63871256-890d5180-c9f6-11e9-8f61-7cc982b8eda2.PNG)
![やっほい](https://user-images.githubusercontent.com/54632880/63871257-89a5e800-c9f6-11e9-89aa-931702de87f1.PNG)

様々な拡張機能を導入した後に気付いた為、いつからその様になっていたのか私は知ることが出来ませんでした。アドバイスなどございましたら教えて下さいませんでしょうか。どうぞよろしくお願いたします。

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|1.4.2
regex|chr|0.2.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
autoit|Dam|0.2.3
githistory|don|0.4.6
gitlens|eam|9.9.3
prettier-vscode|esb|2.2.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-rename-tag|for|0.1.0
vscode-pull-request-github|Git|0.10.0
rest-client|hum|0.22.0
output-colorizer|IBM|0.1.2
format-indent|Kas|1.2.3
HTMLHint|mka|0.6.0
vscode-language-pack-ja|MS-|1.37.5
python|ms-|2019.8.30787
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
evilinspector|sai|1.0.4
whitespace|san|0.0.5
japanese-word-handler|sgr|1.2.0
code-settings-sync|Sha|3.4.2
trailing-spaces|sha|0.3.1
guides|spy|0.9.3
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.3.0
vscode-ansible|vsc|0.5.2

(2 theme extensions excluded)

</details>

**Comment by ypresto** [comment]
@WhiteGuineePig Welcome to GitHub! :tada:
使い方等の質問はGitHubではなくStackOverflow（や日本でならTeratail）に投稿することが望ましいです。今回のケースはフォントの設定の都合にも見えますので、設定ファイル内にフォントを指定するような項目が書かれていないか確認すると良いと思います。
