### ISSUE TITLE
Persist search results in workspace when closing/re-opening

### ISSUE THREAD

**Issue by kuzi-moto** [microsoft/vscode#79996]
I have tried to look around, and can't seem to find any other requests for this. What I'd like is for VS Code to save the global search results in a workspace after closing. So that when you re-open it will present you with the same results, and at the same position you were previously.

My use-case for this:
I'm currently working on a project to review all of the translatable strings in a web application for grammar, capitalization, etc. I search VS Code for a function, and it returns a little over 3,000 results. As I look through all the items I can dismiss them, and remove from the search results. If I close VS Code, it will remove all the results, and I'll have to start over, or remember at which file I left off at. Or I suppose I can just make sure I don't close out and restart my computer until I finish.

I can't simply export the results, because there's a lot of other code in there and syntax highlighting is useful, plus I often need to know the context of where the string occurs which may be on the previous line to the result.

This is a single most extreme example, but there are also lots of other times where I'd like to just be able to continue where I left off.

**Comment by skprabhanjan** [comment]
@roblourens , Is this something I can take up ? 
Please help me if you think yes :)

**Comment by roblourens** [comment]
I don't want to do this now. A naive approach could use quite a lot of space. I'd rather keep it open for feedback or 👍s.

**Comment by roblourens** [comment]
This will hopefully be solved by being able to get search results in a text format in the editor, where you will be able to save them and still navigate after restoring them.
