### ISSUE TITLE
Open in Terminal in folders Error is back in VScode v.1.37.1

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/vscode#79993]
Got this error after updating my vscode.

https://github.com/microsoft/vscode/issues/77174
https://github.com/microsoft/vscode/issues/77179

**Comment by Tyriar** [comment]
Does the CWD exist? I can't give advice if you don't show the error.

**Comment by virtualdvid** [comment]
Yeah the folder exists and is exactly the same issues I mentioned. I have been working on my project for 6 months now with the same config for debugging. I solved it downgrading one version as people suggested on those issues and it's working as usual after that but I had to disable the vscode auto-updates sadly.

**Comment by Tyriar** [comment]
Please show the error, when did you downgrade? Did you try on 1.38?

**Comment by virtualdvid** [comment]
I updated it last week after I started this issue. I just updated to v1.38 and got:

`The terminal shell CWD "my_folder" does not exist`

Here my launch.json file:

```python
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd": "my_folder",
            "env": {
                "DJANGO_SECRET_KEY":"***"
            },
            // "args": ["test_db"]
        }
    ]
}
```
works in v1.36

**Comment by Tyriar** [comment]
Since it's related to python debugging please report to the python extension first https://github.com/microsoft/vscode-python
