### ISSUE TITLE
Windows setup file version

### ISSUE THREAD

**Issue by mojtabakaviani** [Microsoft/vscode#80]
windows setup not have a file version and when hover cursor 0.0.0.0 shown. please set setup file version

**Comment by Leclex** [comment]
Perhaps the best practice is to add version information into the name of setup, e.g. `VScode-0.10.2.exe`.

**Comment by alexandrudima** [comment]
:white_check_mark: 

![image](https://cloud.githubusercontent.com/assets/5047891/11812615/398987a2-a33d-11e5-852a-50c6499649be.png)
