### ISSUE TITLE
Git Commit Ctrl+Enter Does Not Work

### ISSUE THREAD

**Issue by YuriySamorodov** [Microsoft/vscode#800]
Hello,

Git Commit will not work with Ctrl+Enter hotkey.
OS: Windows 7 SP1
VSO: 0.010.2

Regards,
Yuriy

**Comment by joaomoreno** [comment]
Are you sure you

1. Have changes to commit, and
2. Typed a commit message?

**Comment by YuriySamorodov** [comment]
Hello,
That's the thing. There were changes there. However I did not put in any messages just because I did not want to. Should I add messages every time I commit?
Thank you!

**Comment by joaomoreno** [comment]
Yes, you really should. :+1:
