### ISSUE TITLE
When opening extension URI, URL should be URI, and URI should be shown in full

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#80002]
Transferred from internal repo, when testing the `vscode.env.createAppUri` [API](https://github.com/microsoft/vscode/blob/20e24e879acc220cbb9b365001b5d1427824edaf/src/vs/vscode.proposed.d.ts#L1216)

![image](https://user-images.githubusercontent.com/4033249/63798196-7859c000-c8be-11e9-83e2-45d39fc150bc.png)

These are URI not URL. I'm also wondering why we are showing the ... when we have enough space to display the full URI.

**Comment by joaomoreno** [comment]
The cropping is hard since we need to accommodate for all the different dialogs we have: web, mac, win, linux. We simply have to pick a number. We currently crop at 40 characters.
