### ISSUE TITLE
Regular breakpoints don't have a title tooltip

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#80003]
Testing #79799

All of the other breakpoints have this title, we should also add them to regular breakpoints (including data). With the new data breakpoint icon it will also help tell the user what this icon means:

![gif](https://user-images.githubusercontent.com/35271042/63875104-9800ef00-c977-11e9-8c2d-27e3e890e994.gif)

**Comment by isidorn** [comment]
Makes sense, on regular breakpoint we will just say "Breakpoint".
Assigning to September to tackle in debt week

**Comment by isidorn** [comment]
@misolori I have polished the hover message in the breakpoints view.
Check it out and let me know what you think about it. Thanks

**Comment by misolori** [comment]
Verified that this works!

**Comment by isidorn** [comment]
@misolori thanks!
