### ISSUE TITLE
There aren't any git commands

### ISSUE THREAD

**Issue by kabua** [microsoft/vscode#80009]
- VSCode Version: 1.37.1
- OS Version: Win x64 10.0.17134

Steps to Reproduce:

1. Install git for windows
2. Install vscode
3. within the terminal window, type: where git
   which (in my case returns): c:\Program Files\Git\cmd\git.exe
4. click `F1`, type `git`.
   Result: `No commands matching`

I've also tried creating the following workspace:
```
{
	"folders": [
		{
			"path": "."
		}
    ],
    "settings": {
        "git.enabled": true,
        "git.path": "C:/Program Files/Git/cmd/git.exe"
    }
}
```
Still nothing. It is as if vsCode never installed the git extension during the installation process.

**Comment by kabua** [comment]
Nope this is different issue, I've read through all of these. 

On a different machine, with the following specs:
vscode version: 1.37.1
OS: windows x64 6.3.9600

I can see the `GIT` options if I look under `Settings > Extensions` and if I click `F1`  and type `git` I see lots of commands. Exactly what I expect to see.
But on my development machine I don't see the `GIT` extension or the commands. It appears that the extension is physically missing or not being loaded for some reason.
I've uninstalled and reinstalled a few times and rebooted my machine but nothing has worked so far.

**Comment by kabua** [comment]
I've also noticed that my shell selector only reports `cmd`. It is missing `PowerShell`, `git` and `bash`. Perhaps these issues are related.

**Comment by Tyriar** [comment]
> I've also noticed that my shell selector only reports cmd. It is missing PowerShell, git and bash. Perhaps these issues are related.

There are some hardcoded paths which detect these paths.

> which (in my case returns): c:\Program Files\Git\cmd\git.exe

Is the cmd path on your `Path` env var?
