### ISSUE TITLE
Call Stack pane thread folding auto-opens after being folded during debug

### ISSUE THREAD

**Issue by berdon** [microsoft/vscode#80004]
Issue Type: <b>Bug</b>

Folding a project thread-tree in the "Call Stack" pane in a multi-project debug situation immediately reopens the callstack 9/10 times. It's nearly impossible to use.

VS Code version: Code - Insiders 1.38.0-insider (0f73473c08055054f317c1c94502f7f39fdbb164, 2019-08-23T05:36:33.571Z)
OS version: Darwin x64 18.6.0

**Comment by isidorn** [comment]
I can not reproduce this. Can you please provide some simple repository for which I can reproduce this? Some steps would also be useful.
Can you provide a video showing the problem.

Thanks

**Comment by isidorn** [comment]
Ok. Looking at the code I understand that this could be happening and I agree that we should improve this.

I suggest the following strategy:
* Only expand a thread or a session if the breakpoint gets hit
* If a new thread appears (or gets removed) do not expand a session

fyi @weinand 

@berdon  Let me know what you think. And it would be great if you try vscode insiders just so we are sure it also reproduces there (since I changes some of the auto focus behavior last week). 
https://code.visualstudio.com/insiders/

**Comment by berdon** [comment]
@isidorn Yeah, I use the insiders build. I'm reasonably confident I updated monday or so.

I think your suggestion on how expansion should behave is reasonable. There's likely three types of situations here:

- Users with few threads / or a single process
- Users with many threads and one process
- Users with many threads and a multiple process

Those with few threads / single process won't care because they only see a single expanded list. 

The case with many threads and one process probably care if their scroll position changes out from under them depending on thread activity. *This* might be a reason to only change scroll position if a breakpoint is hit.

Those with many threads and many processes...probably rarely care about anything in that pane except using it to switch between focused process for logs and viewing call stack history. This might be better served by splitting the call stack history into a different panel though.

**Comment by isidorn** [comment]
@berdon I have pushed a potential fix for this to vscode insiders.
Can you try it out from Monday and let me know if this behaves better.
If it is still bad let me know and I can investigate further, though a nice reproducable step would really help.

**Comment by isidorn** [comment]
Thanks, adding verified label.
If you have more feedback please create a new issue.
