### ISSUE TITLE
Cover Tabs to Spaces is not working.

### ISSUE THREAD

**Issue by A87P** [microsoft/vscode#80005]
Issue Type: <b>Bug</b>

Cover Tabs to Spaces and back Spaces  to Tabs is not working in the latest vscode.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by weinand** [comment]
@A87P I cannot reproduce this problem.
Please provide reproducible steps.

**Comment by weinand** [comment]
no response. Closing.

**Comment by A87P** [comment]
I cannot reproduce it after the latest update to the VSCode.
