### ISSUE TITLE
Inactive window controls on Mac are hard to see on light themes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#80007]
This seems like a bug where something changed, dark themes are fine but the light themes makes the controls hard to see:

## Dark
<img width="373" alt="image" src="https://user-images.githubusercontent.com/35271042/63879686-101fe280-c981-11e9-8126-bda8e06a33d0.png">

## Light
<img width="356" alt="image" src="https://user-images.githubusercontent.com/35271042/63879695-13b36980-c981-11e9-8f62-778c2a5cf0e7.png">

## Others
<img width="261" alt="image" src="https://user-images.githubusercontent.com/35271042/63879820-51b08d80-c981-11e9-8602-c4a7a1f90143.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/35271042/63879859-68ef7b00-c981-11e9-9340-e94266954baf.png">

**Comment by bpasero** [comment]
@misolori looks OK to me:

![image](https://user-images.githubusercontent.com/900690/63913316-115c1880-ca30-11e9-98bc-7a4e89cbbf76.png)

Did you configure a color for the inactive title?

**Comment by misolori** [comment]
This repros on stable and I think this is happening when you are on dark mode in the OS and your VS Code theme is set to light. See here as I toggle the OS theme (notice how Finder updates):

![gif](https://user-images.githubusercontent.com/35271042/64440806-81e2e500-d081-11e9-9e09-d88ac10e8c10.gif)

It appears that this expected behavior but it's a problem because we don't update the title bar based on the OS title bar. Up to you if you want to re-open.
