### ISSUE TITLE
Smarter comments

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#80000]
Issue Type: <b>Feature Request</b>

When pressing Ctrl+K+C to comment a selection that starts after the first character on a given line, I think it should make a /* block comment */ instead of a line comment.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexandrudima** [comment]
But Ctrl+k Ctrl+c is bound to Line Comment. Simply use Shift+Alt+A to add a block comment.
