### ISSUE TITLE
workbench.action.terminal.moveToLineStart not working for zsh shell

### ISSUE THREAD

**Issue by sunknudsen** [microsoft/vscode#80018]
<img width="441" alt="Screen Shot 2019-08-28 at 6 00 20 PM" src="https://user-images.githubusercontent.com/2117655/63895667-c2759b00-c9bd-11e9-9521-affa4709fe0d.png">

- VSCode Version: Version 1.36.1 (1.36.1)
- OS Version: Version 10.14.6 (18G87)

Steps to Reproduce:

1. Start Visual Studio Code using application icon.
2. Configure zsh as default shell (`"terminal.integrated.shell.osx": "/bin/zsh"`)
3. Type `example` (or any other word) in terminal and hit <kbd>cmd</kbd>+<kbd>left</kbd>

Does this issue occur when all extensions are disabled?: No

The strangest thing is that the bug doesn’t occur when starting Visual Studio Code using `code` (with all extension enabled).

**Comment by Tyriar** [comment]
Your shells seems to want something different, you can send arbitrary text to your shell via the vscode keybinding system by following this: https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding

This is essentially how the moveToLineStart command works, it's just built in.
