### ISSUE TITLE
Issue disabling all extensions

### ISSUE THREAD

**Issue by sahil48** [microsoft/vscode#80011]
- VSCode Version: 1.37.1 (user setup)
- OS Version: Windows_NT x64 10.0.17134

Expected Behavior: When I click "Disable All Installed Extensions", I expect all installed extensions to be disabled. If unexpectedly, an extension cannot be disabled, I expect the remaining extensions to be disabled.

Actual behavior: Visual Studio Code reports a conflict, and does not disable remaining extensions

![image](https://user-images.githubusercontent.com/6100774/63893779-0ca84d80-c9b9-11e9-9b2a-b5b9b060ceae.png)

Steps to Reproduce:

1. Install Node Debug and Node Debug (legacy).
2. Attempt to disable all extensions.

**Comment by sahil48** [comment]
Based on what I read in the attached issue, I think this is a distinct issue.

**Comment by sandy081** [comment]
> Install Node Debug and Node Debug (legacy).

@sahil48 How did you install node debug and node debug (legacy)?

**Comment by sahil48** [comment]
Most likely by installing the Node.js Extension Pack or React Extension Pack some time back. What I suspect is that when an extension pack gets installed and some extensions depend on other extensions, the disable all extensions command gets stuck.

**Comment by sandy081** [comment]
@sahil48 I do not think installing these packs installs node debug extensions as they are built in. So I am wondering how did they become installed extensions. Can you please open the installed extensions folder using command `Open Extensions Folder` and see if node debug extensions are there. If so, delete them and try disabling again.

**Comment by sahil48** [comment]
Sure. I'll try it this weekend.

**Comment by sandy081** [comment]
👍

**Comment by sahil48** [comment]
So I have node-debug in the folder.

![image](https://user-images.githubusercontent.com/6100774/64348757-be500b80-cfc3-11e9-8a98-9046b1fdaf87.png)

However, some other extensions may depend on it (one react package, I think) What will happen to these extensions when I restart visual studio code.

**Comment by ifiokjr** [comment]
@sandy081 just so you know deleting the folder `ms-vscode.node-debug*` worked for me.

I can now disable all extensions as intended.

**Comment by sahil48** [comment]
Deleting this folder did the trick. It seems I am not the only one who ended up with ms-vscode.node-debug* folder, and that might be worth investigating. @ifiokjr, do you know how you ended up with that folder?

As the issue has been resolved for me, I am marking this issue as closed.
