### ISSUE TITLE
Ctrl+A Ctrl+C copies highlighted text

### ISSUE THREAD

**Issue by codingyourlife** [microsoft/vscode#80012]
I just copied a json file's content to Google Sheets and it copies the blue highlighting of Ctrl+A too. I'm pretty sure I did this before and this wasn't always the case.

Steps to reproduce:
- Write Code
- Ctrl+A
- Ctrl+C
- Paste Code e.g. in Google Sheets
-> blue highlighting of code will also be copied

<img width="220" alt="Screenshot 2019-08-28 at 23 25 56" src="https://user-images.githubusercontent.com/10122382/63893855-83f6d500-c9eb-11e9-87b2-633618927e17.png">

**Comment by alexandrudima** [comment]
VS Code writes two times the text to the clipboard, once as plaintext and once as HTML. Each application where you paste can choose what format to read from the clipboard. Most likely, Google Sheets has been updated to now paste the HTML variant stored in the clipboard.

The only exception from above is if you copy from a plain text file. In that case VS Code only writes to the plaintext clipboard.

**Comment by rebornix** [comment]
@codingyourlife are you using light theme in VS Code? IMO the blue highlight is from the background color of the editor. As Alex mentioned above, we will copy both plaintext and html to the clipboard. To disable this feature, you can set `editor.copyWithSyntaxHighlighting` to `false`.

**Comment by codingyourlife** [comment]
I was surprised that this wasn't easily reproduced so I tried it on a plain new google doc and there it worked. I thought maybe the formatting was set before pasting and that truly was the case.
Sorry for the wrong alert. All fine it seems :)

Aanyone having the same issue just check your hightlighting color before pasting
