### ISSUE TITLE
VSCode debugger not attaching when process started by task

### ISSUE THREAD

**Issue by mvittiglio** [microsoft/vscode#80019]
- VSCode Version: 1.37.1
- OS Version: Win 10 10.0.18965

Steps to Reproduce:

1. Start debugging with prelaunch task starting node application
2. Node fails to attach
3. This does not happen if we start the application through the embedded terminal.
4. Video showing this behavior can be found here: https://www.youtube.com/watch?v=iEsZBq1_CcM

Does this issue occur when all extensions are disabled?: Yes/No
Cannot run without WSL extension

**Comment by mvittiglio** [comment]
Here's the output from the log (when failing) btw: 
```
[22:27:07.029 UTC] Getting browser and debug protocol version via http://0.0.0.0:9229/json/version
[22:27:07.029 UTC] Discovering targets via http://0.0.0.0:9229/json/list
[22:27:07.031 UTC] HTTP GET failed: Error: connect ECONNREFUSED 0.0.0.0:9229
[22:27:07.032 UTC] There was an error connecting to http://0.0.0.0:9229/json/version : connect ECONNREFUSED 0.0.0.0:9229
```
It's worth mentioning that I could use curl in a second terminal and was able to get data from those endpoints.

**Comment by weinand** [comment]
How does your prelaunch task and your "attach" launch config look like?

**Comment by mvittiglio** [comment]
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
       {    
        "type": "node",
        "request": "attach",
        "name": "Docker development debug",
        "protocol": "inspector",
        "port": 9229,
        "address": "0.0.0.0",
        "sourceMaps": true,
        "localRoot": "${workspaceFolder}",
        "timeout": 20000,
        "stopOnEntry": false,
        "remoteRoot": "/home/app/",
        "outFiles" : [ "${workspaceRoot}/dist/**/*.js" ],
        "preLaunchTask": "docker-run",
      }
  ]
}
```

tasks.json
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "docker-run",
      "type": "shell",
      "command": "npm",
      "args": [
        "run",
        "debug:run"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "presentation": {
        "echo": true,
        "reveal": "always",
      }
    }
  ]
}
```
package.json
```
{
  "name": "es6_docker",
  "version": "1.0.0",
  "description": "Testing ES6 + Docker debugging in VSCode.",
  "main": "src/app.js",
  "scripts": {
    "docker": "npm run docker:build && npm run docker:run",
    "docker:build": "docker build . -t mike/node-debug-test",
    "docker:run": "docker run --rm -v $(pwd)/src:/home/app/src -p 9229:9229 mike/node-debug-test",
    "debug": "npm run debug:cleanup && npm run debug:build && npm run debug:run",
    "debug:cleanup": "rm -rf dist/*",
    "debug:build": "BABEL_ENV=debug babel src --out-dir dist",
    "debug:run": "node --inspect=0.0.0.0:9229 dist/app.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/node": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "nodemon": "^1.19.1"
  },
  "dependencies": {
    "core-js": "^3.2.1",
    "lodash": "^4.17.15",
    "regenerator-runtime": "^0.13.3"
  }
}

```

**Comment by mvittiglio** [comment]
Here's a fuller output from logs when failing: https://pastebin.com/zvpWKnG5

**Comment by mvittiglio** [comment]
Might as well leave the source in here as well... :-)

--app.js--
```
let main = async (maxCounter, sleepTimeMs) => {
  let counter = 0;
  while (counter < maxCounter) {
    counter += 1;
    counter -= 1;
    console.log(`Hello for the ${counter++ + 1} time`);
    await sleep(sleepTimeMs);
  }
}

let sleep = async (sleepTimeMs) => {
  return new Promise((resolve) => { setTimeout(resolve, sleepTimeMs) });
}

main(100, 1000);
```

**Comment by mvittiglio** [comment]
Just wanted to update that I've updated to NodeJS v12.9.1 and the problem persists.

**Comment by mvittiglio** [comment]
Hey folks, just wanted to check in to see if there's anything else I can do with regards to troubleshooting this behavior.

**Comment by jbracer19** [comment]
I’m here for you as well, please just ask

[cid:574F8F21-D2D8-4048-989D-C73DB1993C67]
FYi ios shows notification on the edit


John Ballou

On Oct 14, 2019, at 12:06 PM, Michael Vittiglio <notifications@github.com> wrote:

﻿

Hey folks, just wanted to check in to see if there's anything else I can do with regards to troubleshooting this behavior.

**Comment by weinand** [comment]
@mvittiglio I'm back from vacation...

**Comment by connor4312** [comment]
Thanks for the video, that's very helpful. Because there's no matcher to tell us when the container is running, we try to connect immediately, and I'm guessing the connection logic in the debugger gets stuck when the container isn't already open. I suspect you would get the same behavior if you hit F5 without a prelaunch script immediately before starting the container.

However in the intervening time since this issue was created, we have a new debugger with reconnection logic that may be more durable than the last one. Can you let us know if you still hit this on the latest VS Code 1.50 or newer?

**Comment by mvittiglio** [comment]
@connor4312 Thanks for reaching out. Unfortunately, I've since moved onto other projects and can't say for certain if this is still an issue. I can't find the repo any longer either which is also unfortunate. However, I've been able to remote debug with other projects into Docker images so I think it's safe to say that this is no longer a cause for concern.

**Comment by connor4312** [comment]
Sounds good. If you run into it again, give us a shout :)
