### ISSUE TITLE
Find widget UI incorrect behavior when focused from a new tab

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#80015]
When Testing https://github.com/microsoft/vscode/issues/79831

- VSCode Version: 1.38.0-insider
- Commit: eeab6fc371fcbfead7a1bd887c28f7efb28e5fcb
- Date: 2019-08-28T05:38:02.398Z
- OS Version: All

Steps to Reproduce:

1. Open find widget with replace
2. Type some content and resize the widget
3. Open a new tab, ex: open settings UI
4. Focus back to the original tab and see the issue with widget

Attaching a video demo: https://streamable.com/ni1te

Also tested with latest exploration builds and the same issue is present, might not be related to the new feature.

**Comment by rebornix** [comment]
No longer reproducible in latest, thanks.
