### ISSUE TITLE
Request for option to disable all installed extensions in the current workspace.

### ISSUE THREAD

**Issue by sahil48** [microsoft/vscode#80013]
Please add an option in the extensions drop-down to disable all installed extensions in the current workspace only.

![image](https://user-images.githubusercontent.com/6100774/63893979-7f192d80-c9b9-11e9-93a6-6a93ed7ef07e.png)

**Comment by sandy081** [comment]
It exists in the command pallette

![image](https://user-images.githubusercontent.com/10746682/63921809-c3511000-ca43-11e9-8855-6c45ee9b83b4.png)

**Comment by sahil48** [comment]
Okay. I didn't see that option. Thanks!
