### ISSUE TITLE
paste some files into work folder

### ISSUE THREAD

**Issue by yunpheng** [microsoft/vscode#80025]
Issue Type: <b>Feature Request</b>

dear:
    I want to use a function that paste some files into work in folder from other  folder  copy files,thank you.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

**Comment by weinand** [comment]
I don't understand what you mean.

**Comment by yunpheng** [comment]
I mean is that copy some files from somewhere else and paste them into a folder in my vs code working directory,thank you.发自我的华为手机-------- 原始邮件 --------主题：Re: [microsoft/vscode] paste some files into work folder (#80025)发件人：Andre Weinand 收件人：microsoft/vscode 抄送：yunpheng ,Author I don't understand what you mean.
