### ISSUE TITLE
vscode.javascript syntax highlighting for require()

### ISSUE THREAD

**Issue by Zireael** [microsoft/vscode#80022]
Hi,
This is a request to add TextMate grammar syntax rule for require() used in JavaScript files. The function in broad terms could be considered similar to `import`.

Currently `require()` gets marked like so:

![image](https://user-images.githubusercontent.com/3856578/63899354-7d209000-c9f4-11e9-9c79-3786cd161423.png)

It should be available as `keyword.control.require.js` similar to `keyword.control.import.js`

![image](https://user-images.githubusercontent.com/3856578/63899277-2fa42300-c9f4-11e9-9351-5544a8905205.png)

The desired outcome is that (in screenshot below) the require could be coloured as violet (control keyword) instead of yellow (function).
![image](https://user-images.githubusercontent.com/3856578/63899491-fae49b80-c9f4-11e9-9db6-90dbd439f1a0.png)

I am not proposing a breaking change of removing recognising require() as a function, but to add a new TextMate descriptor rule for it as `keyword.control.require.js` for JavaScript and `keyword.control.require.ts` for TypeScript so that it can be specifically targeted by theme colouring syntax by anyone desiring to do so. 

Thank you in advance!

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript-TmLanguage/issues/769
