### ISSUE TITLE
Breadcrumbs outline should collapse element if the corresponding range is folded

### ISSUE THREAD

**Issue by christopherkang** [microsoft/vscode#80020]
After folding a JSON file, the overview bar (underneath the tabs) should reflect the fold. Similarly, if the JSON file has been unfolded, the bar should reflect this.

E.g:
The menu displayed below should collapse when the overall JSON has folded.

<img width="478" alt="Screen Shot 2019-08-28 at 3 36 48 PM" src="https://user-images.githubusercontent.com/42285636/63897356-b2ec5700-c9a9-11e9-8d82-98b843dc64aa.png">

**Comment by aeschli** [comment]
I assume you are referring to the breadcrumps tree.

**Comment by jrieken** [comment]
Folding regions and outline aren't the same thing and while there might be some overlap in some cases there is no guarantee.

**Comment by christopherkang** [comment]
@jrieken What do you mean? Are you saying that the text itself may not be the same as the outline representing it?

**Comment by jrieken** [comment]
No, I am saying that folding regions (e.g collapse/expand triangles next to your text) aren't the same as outline items. 

⬇️ folding regions
<img width="790" alt="Screenshot 2019-08-30 at 09 53 37" src="https://user-images.githubusercontent.com/1794099/64003250-2908cf00-cb0c-11e9-9049-b8c9d620ae46.png">

⬇️ outline items
<img width="540" alt="Screenshot 2019-08-30 at 09 54 11" src="https://user-images.githubusercontent.com/1794099/64003251-2908cf00-cb0c-11e9-896c-f8ccacb2c941.png">

**Comment by christopherkang** [comment]
Got it. So, I think there are two cases:

- The breadcrumbs outline **does** match the folding regions, in which case folding in either should fold the other
- The outline **doesn't** match the regions - maybe we only fold the uppermost level where the headers match?
