### ISSUE TITLE
OpenAPI relative $ref String is not a URI

### ISSUE THREAD

**Issue by grantcarthew** [microsoft/vscode#80029]
Issue Type: <b>Bug</b>

When creating an OpenAPI yaml file the $ref key is reporting the following lint error:

String is not a URI: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "./json-schemas/request/sign-in.json", query: "", fragment: ""}

Here is the line in the OpenAPI yaml file that is causing the error:

`$ref: './json-schemas/request/sign-in.json'`

As far as I can tell, this is a valid $ref path as described here: https://swagger.io/docs/specification/using-ref/

The VSCode URI parser (https://github.com/microsoft/vscode-uri) uses `URI.file` to define the scheme. This is not possible in a yaml file as far as I know.

This doesn't stop the OpenAPI file from being useful. It is just annoying.

Thanks.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (9.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|1.8.10
swagger-viewer|Arj|2.2.2
azds|azu|1.0.120190809
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.30.1
mustache|daw|1.1.1
gitlens|eam|9.9.3
todo-tree|Gru|0.0.143
rest-client|hum|0.22.0
docthis|joe|0.7.1
terraform|mau|1.4.0
openapi-lint|mer|1.0.3
dotenv|mik|1.0.1
azure-pipelines|ms-|1.155.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.3
mssql|ms-|1.6.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
powershell|ms-|2019.5.0
vscode-node-azure-pack|ms-|0.0.9
azurerm-vscode-tools|msa|0.6.0
vetur|oct|0.22.2
vscode-yaml|red|0.5.1
azure-iot-toolkit|vsc|2.10.0
vscode-icons|vsc|9.3.0
vim|vsc|1.10.0

</details>

**Comment by grantcarthew** [comment]
To clarify, this is for a relative path. I know it is possible to use `file://` to define the schema however that would require the full file path.

**Comment by jrieken** [comment]
No clue what you are trying to do or how you are constructing uris (code sample!, steps!) but "yes" we do not support relative uris. There is usually a base-uri to which a relative path needs to be interpreted, like the uri of a document.

**Comment by elierotenberg** [comment]
I'm having similar issues. Here is a minimal example:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: My API
paths:
  /ack:
    get:
      responses:
        '200':
          description: Ack
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ack"
components:
  schemas:
    Ack:
      type: object
      properties:
        ok:
          type: boolean      
```

This definition however works with the regular API tools without error, but VSCode still throws a validation error:
```
String is not a URI: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: "/components/schemas/Ack"}
```

**Comment by jrieken** [comment]
So, that means you are just using an extension, right? You aren't the author of that extension?

**Comment by elierotenberg** [comment]
You're right. Disabling the YAML extension removes the warning. This issue belongs in the extension repo, sorry for the nuisance! For reference, a [similar issue has been submitted there](
https://github.com/redhat-developer/vscode-yaml/issues/218).

**Comment by jrieken** [comment]
Thanks for clarifying

**Comment by grantcarthew** [comment]
Hi guys,

I sincerely apologise. There was no indication in the error that it was an extension that was raising the issue.

I should have tried disabling related extensions first. I was under the impression error messages stated the package that was raising the issue.

Thanks for your hard work.

**Comment by adriengibrat** [comment]
seems related to https://github.com/redhat-developer/vscode-yaml/issues/218 (fixed ;))
