### ISSUE TITLE
gray attributes in launch.json are confusing

### ISSUE THREAD

**Issue by smcpeak** [microsoft/vscode#80026]
Related issues: #13353, #13979, #37459.
VSCode version: 1.37.1
OS Version: Windows 10 x64
Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a file called "launch.json" and populate it as described at https://code.visualstudio.com/docs/cpp/config-mingw#_configure-debug-settings
2. Observe that attributes "version", "configurations", "type", and "request" are rendered in a gray color.
3. Become confused about what this means.

Screenshot:

![gray-attributes](https://user-images.githubusercontent.com/2909643/63901778-e683ad00-c9ba-11e9-9924-6cbdd9482486.png)

I understand from #13979 that this is considered intended behavior.  It is nevertheless confusing:

* The use of gray color to signify something is "less important" is unconventional.
* There is no way in the app to discover this novel convention.  Hovering does not show anything interesting.  Even the TextMate scope inspector shows nothing unusual.
* Elsewhere (both in VSCode and other applications), differently colored or styled attributes often indicate that something is an error, potentially leading the user on a wild goose chase to discover the problem (which is how I ended up here).

Hover:

![hover](https://user-images.githubusercontent.com/2909643/63902092-8130bb80-c9bc-11e9-987d-b73901bce538.png)

TextMate scope inspector:

![tm-inspector](https://user-images.githubusercontent.com/2909643/63902102-8f7ed780-c9bc-11e9-8e51-21f04c053033.png)

The impact of this confusion is magnified by the fact that every user who follows the [VSCode C++ configuration tutorial](https://code.visualstudio.com/docs/cpp/config-mingw) will see it, and the screenshot in that tutorial does *not* show the gray attributes, further reinforcing the user's likely hypothesis that they have made a mistake.

This is what the tutorial looks like:

![should-look-like](https://user-images.githubusercontent.com/2909643/63902233-4f6c2480-c9bd-11e9-9522-af34661373e7.png)

I have read through the discussion in #13353.  My summary is that there was disagreement about whether these attributes even *are* "less important", and agreement that the use of gray color to signify that is likely to be confusing.  But, at least within the discussion there, these concerns were not resolved.

In my opinion, the gray color fails to ameliorate the problems #13353 was filed to address, and certainly leads to confusion, so ought to simply be removed.

As a tangential suggestion, the attribute hover text might be a good place to explain caveats regarding understanding or modifying those fields.

**Comment by isidorn** [comment]
@smcpeak  Thanks for sharing your feedback. 

I am also not a big fan of the gray in the `launch.json`.
The C++ configuration tutorial can easily be updated to reflect the grey color. So that issue can be easily fixed.
Some other ideas as you mention are that we keep the gray and provide a more precise hover message.
Or we could remove the grayness alltogether.

I am open for suggestions.
@weinand let me know what you think

**Comment by isidorn** [comment]
@roblourens what are your feelings about the grey attributes in launch.json?

**Comment by roblourens** [comment]
I don't feel like it improves readability a ton for me. But I don't feel strongly about it either way.

**Comment by mattacosta** [comment]
I remember that when it first came out, my initial reaction was to delete those lines, only to find out that it broke my launch configuration. I expected grey properties to act like today's unused parameters, in that it was inferred and/or unused and could therefore be deleted safely.

**Comment by weinand** [comment]
I was never a fan of the gray attributes in launch.json and we should eliminate them.

**Comment by isidorn** [comment]
To verify: open a launch.json and make sure nothing is decorated in gray
