### ISSUE TITLE
Outline view is blank with 1.38.0-insiders when SymbolInformation is returned instead of DocumentSymbol

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#80023]
- VSCode Version: 1.38.0-insiders
- OS Version: Windows

Steps to Reproduce:

1. Use the C/C++ extension or some other extension that returns SymbolInformation instead of DocumentSymbol.
2. View the Outline.

Bug: The Outline view is blank. ERR Cannot read property 'indexOf` of undefined error is shown. The bug doesn't repro with VS Code non-insiders. Our internal build that returns DocumentSymbol instead of SymbolInformation does not repro the bug (TypeScript also uses DocumentSymbol).

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Good catch! Pushed fix for next insiders build

**Comment by jrieken** [comment]
Thanks @mjbvz

**Comment by sandy081** [comment]
Can you please provide a sample C++ code to verify this?

**Comment by mjbvz** [comment]
I verified it with

```c++
int main(int argc, char const *argv[])
{
    return 0;
}
```
