### ISSUE TITLE
unable to open URL from VSCode

### ISSUE THREAD

**Issue by bulwynkl** [microsoft/vscode#80024]
Issue Type: <b>Bug</b>

Install VSCode via snap on ubuntu 19.04, select a URL from any documentation.  Attempts to open the URL by spawning a new external default browser window, which fails.  Checked with Firefox and Chrome (by changing default browser at OS level).

if I uninstall code via snap and reinstall via *.deb download, it works just fine, new tab opens in existing browser.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2981)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.66GB (2.82GB free)|
|Process Argv|--verbose|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.0
aws-toolkit-vscode|ama|1.0.0
vscode-django|bat|0.19.0
vscode-intelephense-client|bme|1.2.2
phpserver|bra|2.4.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-sql-beautify|cla|0.0.10
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
phpcs|ika|1.0.5
vscode-phpfmt|kok|1.0.30
MagicPython|mag|1.1.0
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
debugger-for-chrome|msj|4.11.7
sqltools|mtx|0.20.2
docker-compose|p1c|0.3.5
vscode-jupyterfs|sam|0.0.4
vscode-sql-beautify|sen|0.0.4
json-template|sto|0.3.1
nextflow-aws-docker-training-pack|tee|0.0.1
vscodeintellicode|Vis|1.1.9
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/75579
