### ISSUE TITLE
Markdown preview editor cannot split to right

### ISSUE THREAD

**Issue by kntmr** [microsoft/vscode#80038]
Steps:
1. Create a markdown file
1. Open preview (`Ctrl+Shift+V`)
1. Move mouse cursor on split button

"Split Editor Down" is shown by default. I tried that with Shift key, but it does not switch to "Split Editor Right".

![image](https://user-images.githubusercontent.com/1657438/63921664-30819700-ca7e-11e9-9664-97728323bfc0.png)

VSCode Version: 1.37.1
OS Version: Windows 10
All plugins related to markdown are disabled.

**Comment by mjbvz** [comment]
This happens when a webview is focused. Marking as help-wanted. Webview is likely capturing the modifier key press. Relevant webview code is here: https://github.com/microsoft/vscode/blob/78879b6a8116e5ecee3f95809ac49fb1ab0bb206/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L223

**Comment by lifez** [comment]
Seem like it already work?

**Comment by davidreis97** [comment]
Hi, I'd like to have a go at this one. After testing and looking into the code, the approach that seems most logical to me at the moment is to create a fake `KeyboardEvent` targeting the `document.body`. Similar to what's already being done here for keyboard events which target the Webview itself (e.g. copying text via Ctrl+C from the markdown preview):

https://github.com/microsoft/vscode/blob/78879b6a8116e5ecee3f95809ac49fb1ab0bb206/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L164-L170

I've tested this fix and it works, however I'm having trouble deciding which events should be recreated and sent to the window. Should I send all the `keydown` and `keyup` events to the `document.body` (seems a bit excessive), or should I send just the ones that correspond to the alternative key that is reportedly broken (i.e. the "Alt" key for macOS and the "Shift" key for Windows/Linux)?

**Comment by mjbvz** [comment]
This seems to be working as expected for me. I tested on windows using shift and on macOS using ctrl 

Note that the preview itself will not get split but you still should see a new empty editor group created in the correct location
