### ISSUE TITLE
Persist all UI state within the workspace file

### ISSUE THREAD

**Issue by N7K4** [microsoft/vscode#80032]
I work a lot with vscode. The tool is amazing!

Often I work with **different** windows / sessions. To switch between **different tasks** (devops, websites, md-files).

At the moment (vscode 1.37.1) the last session will be restored when I open a new vscode session, that is fine. Session means in that case, open files and Explorer.

I was thinking that "workspaces" can help me to handle different sessions, but that was wrong. Workspace is more for "**folders**" and "**extensions**" but NOT for files.

I found also "Allow "files" field in .code-workspace file #45177 

My **Feature Request** would be:
1) Can a workspace save open files (maybe including the view). So it would be possible to open a workspace and continue working with the open files from last session.
2) Can a workspace handle files on root, like `README.md` or `.gitignore`. Otherwith I have to add "." (as root) to the workspace and not specific folders.

**Comment by bpasero** [comment]
@N7K4 every opened file is associated with a workspace, can you provide steps where this does not work?

**Comment by N7K4** [comment]
On the local machine you are right. But when I use a workspace file under source control or I want to share it with a team member (on a different machine) all files are not listed.
