### ISSUE TITLE
Layout on minimize/maximize window

### ISSUE THREAD

**Issue by pashtet04** [microsoft/vscode#80037]
Issue Type: <b>Bug</b>

Minimize/maximize window resets/reloads my grid layout in VS Code -- very annoying =(

VS Code version: Code - Exploration 1.38.0-exploration (15bc1af92f1f2f087c741b9d2636fee31a12682b, 2019-08-27T06:42:09.318Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.7.0
gitlab-ci-validator|cst|1.0.0
gitlens|eam|9.9.3
json-tools|eri|1.0.2
gitlab-workflow|fat|2.1.1
docker-linter|hen|0.5.0
smarty|imp|0.3.0
kubernetes-snippets|ipe|0.1.9
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.3
mssql|ms-|1.6.0
vscode-postgresql|ms-|0.2.0
python|ms-|2019.8.30787
vscode-yaml|red|0.5.1
plsql-language|xyz|1.8.2

</details>

**Comment by pashtet04** [comment]
![vscode-after-maximize](https://user-images.githubusercontent.com/8694425/63918726-ec72a000-ca45-11e9-8eaf-bcff826447dd.png)
![vscode-my-layout](https://user-images.githubusercontent.com/8694425/63918727-ec72a000-ca45-11e9-858f-7e285ed2efd6.png)

**Comment by pashtet04** [comment]
--disable-extensions
same behaviour

**Comment by sbatten** [comment]
@pashtet04 I cannot repro the behavior. Can you provide explicit steps and be sure you are on the latest?
