### ISSUE TITLE
点击键盘A，一直提示等待下一步快捷键操作

### ISSUE THREAD

**Issue by KGDeveloper** [microsoft/vscode#80033]
Issue Type: <b>Feature Request</b>

点击键盘A，一直提示等待下一步快捷键操作

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.2.0

**Comment by zcmgyu** [comment]
English please
