### ISSUE TITLE
Cannot read file error after uninstalling extension

### ISSUE THREAD

**Issue by water42** [Microsoft/vscode#8004]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1. Install JSHint extension
2. Uninstall JSHint extension

Error message:
Cannot read file C:/Users/Me/.vscode/extensions/dbaeumer.jshint-0.10.12/package.json: ENOENT: no such file or directory, open 'C:\Users\Me\.vscode\extensions\dbaeumer.jshint-0.10.12\package.json'.

After I uninstalled JSHint I now receive this error every time I open vscode, even after restarting.

**Comment by bialix** [comment]
Different extension, the same situation.

**Comment by joaomoreno** [comment]
What is inside `C:/Users/Me/.vscode/extensions`? Can you show me a screenshot of the error?

**Comment by bialix** [comment]
I had 2 extensions: just Python, and MagicPython. I've unistalled first extension. Now the content of the folder you asked:

C:\Users\bialix\.vscode\extensions>dir /b
magicstack.MagicPython-0.5.11

And after I did the command above I no longer get the error message, so I'm unable to make screenshot.

It was a window in the bottom of main editor view with the message from first topic of this issue.

**Comment by bialix** [comment]
Just reproduced again (install/unistall). Icon of the extensions at the bottom left had red dot and tooltip said "Extensions (1 issue)". Clicking on this icon opened window with title "Output" and the text as quoted above. And folder with extensions had no corresponding directory.
![vscode-issue8004](https://cloud.githubusercontent.com/assets/82971/16304291/64e4fd44-395d-11e6-8b8d-21a89c62ebf4.png)

**Comment by water42** [comment]
No longer receiving the issue anymore, but what @bialix just posted was the same error

**Comment by bialix** [comment]
Yes, it seems it can cure itself, so I guess it's related to hard disk cache or something like that.

**Comment by joaomoreno** [comment]
Yes, the errors should eventually go away. It's a part of the install/uninstall procedure.

Closing the issue.
