### ISSUE TITLE
Debug console outputs overlapping lines of text 

### ISSUE THREAD

**Issue by adotg** [microsoft/vscode#80040]
- VSCode Version: 1.37.1
- OS Version:  Darwin x64 18.6.0

**Detailed Version Implementation:**
ersion: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

Debug output console shows overlapping lines while evaluating an expression in debug mode. Refer the following image
<img width="1623" alt="Screenshot 2019-08-29 at 2 29 11 PM" src="https://user-images.githubusercontent.com/7579500/63926526-9fa0c080-ca69-11e9-9dea-dad6ce6a828a.png">

Launch configuration
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "internalConsoleOptions": "openOnSessionStart"
    },
  ]
}
```

Extesion in used:
Vim
Node Debug

Steps to Reproduce:

1. Debug an application
2. Switch to Debug Console panel
3. Try evaluating an expression. The output is not readable and the lines overlaps 

Does this issue occur when all extensions are disabled?: NA

**Comment by isidorn** [comment]
I can not reproduce this.
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please provide a repo which we can clone and reproduce this issue? So we can investigate more.

**Comment by adotg** [comment]
> I can not reproduce this.

Here is something which can help. I was doing trial and error changing the settings after I posted the issue.
Adding the following two lines in `settings.json` (~/Library/Application\ Support/Code/User/settings.json in macos) creates the problem
```
"debug.console.fontSize": 13,
"debug.console.lineHeight": 1.25,
```

If I remove those two lines the behaviour is as expected.

I have attached the whole file for your reference.
[settings.json.zip](https://github.com/microsoft/vscode/files/3555006/settings.json.zip)

If this does not help you replicate the issue, I will try to follow the step you mentioned in the preceding comment (this might take some time because of my current working situation).

**Comment by isidorn** [comment]
This is expected behavior, if you set a small line height in the debug console everything will get broken.
Please just fix the lineHeight on your machine. By default it is automatically infered s oit is best to just not touch it.
Closing as designed
