### ISSUE TITLE
Scroll Issue in Top Menu

### ISSUE THREAD

**Issue by hamzawaleed0102** [microsoft/vscode#80047]
If you enlarge the VSCode interface, then a scrollbar will appear in top menu items(View,Debug).

I found a problem with that scrollbar, if you try to scroll it to the end it scrolls back automatically in an abnormal way.

Have a look at the attached GIF for better understanding.

![vscodeScrollBug](https://user-images.githubusercontent.com/43571677/63936329-fe216b00-ca78-11e9-8ad7-e8ffb07b157c.gif)

Steps to Reproduce:

1. Enlarge interface by pressing Ctrl **+** + Button until a scrollbar appears in toolbar items(View, Debug).
2.  Select **View** from toolbar and try to scroll to the end. It will scroll backward after touching the end.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@hamzawaleed0102 thanks for reporting, I fixed this issue several months ago when not zoomed in, but apparently missed this case.

**Comment by ceefour** [comment]
I have this bug too:
https://youtu.be/6x62BATeMdQ

VSCode 1.38.0

Related to https://github.com/microsoft/vscode/issues/66273#issuecomment-453228068
