### ISSUE TITLE
Git: branches no longer sorted by commit date

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80045]
Steps to Reproduce:

1. have a couple of branches
2. click on the branch picker

=> :bug: the branches are no longer sorted by commit date

This works fine in stable, so seems like a regression.

INSIDERS
![image](https://user-images.githubusercontent.com/900690/63930649-09ae6b00-ca54-11e9-8677-09b8664891c4.png)

STABLE
![image](https://user-images.githubusercontent.com/900690/63930636-02875d00-ca54-11e9-8788-71bfb8235874.png)

(my git version is `2.23.0`)

**Comment by joaomoreno** [comment]
Stable:

```
git for-each-ref --format %(refname) %(objectname) --sort -committerdate
```

Insiders:

```
> git for-each-ref --format %(refname) %(objectname) --sort committerdate
```

Yup, there's a `-` missing.
