### ISSUE TITLE
Git: clicking untracked file now opens diff editor?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80044]
Steps to Reproduce:

1. add a new file
2. click it from the changes view

=> :bug: it opens a diff editor instead of just the file?

![image](https://user-images.githubusercontent.com/900690/63930529-cfdd6480-ca53-11e9-8c64-584f28714cf4.png)

This seems to be a regression.

**Comment by joaomoreno** [comment]
This is purposeful, since you can now stage ranges in untracked files! https://github.com/microsoft/vscode/pull/78562

**Comment by bpasero** [comment]
Not sure, I always have a keybinding for doing this and I would guess it could just work via that from the editor.

**Comment by webmasterMeyers** [comment]
I prefer the old behaviour of just opening the new file.  Is there an option to set this behaviour?
