### ISSUE TITLE
VSCode Git not using global config settings when committing

### ISSUE THREAD

**Issue by Nowhk** [microsoft/vscode#80059]
I have the same problem listen here: https://github.com/Microsoft/vscode/issues/67736 (which was closed using a "workaround").

Can you please help me to fix it?

Using `git commit -m "test"` from the terminal, set the correct user.name and email (on global settings); doing it from VSCode IDE interface not: it takes some other values from a different account I had in the past.

What's wrong?

**Comment by maherkhalil07** [comment]
Using -m will force git not to use vscode
You have to configure git to use vscode and then commit using command
Git commit

**Comment by Nowhk** [comment]
@maherkhalil07 what do you mean "You have to configure git to use vscode"?
I want to use VSCode IDE to make commits, without using the terminal.

But I don't see where/how/when those user.name/email are stored in VSCode.
`$GIT_AUTHOR_NAME` and `$GIT_AUTHOR_EMAIL` are empty.

**Comment by joaomoreno** [comment]
#67736 was not closed with a workaround. The user fixed something in their system which stopped the issue from occurring.

Can you reproduce in other repositories? 
Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

**Comment by Nowhk** [comment]
@joaomoreno yes he did: "It does, but taking your comment earlier about the git environment variables i decided to add those keys to my user environment". He just put the env var and fix the problem. That what I mean with workaround :)

Yes, in all repositories I have it happens.
Yes, it does the same on the latest insider version (downloaded and tried right now).

**Comment by joaomoreno** [comment]
Is the same git executable being used in VS Code and in the terminal?

**Comment by Nowhk** [comment]
Here's my settings:

```
"terminal.integrated.shell.windows": "C:/msys64/usr/bin/bash.exe", 
    "terminal.integrated.shellArgs.windows": [
        "-i"
    ],
    "terminal.integrated.env.windows": {
        "MSYSTEM": "MINGW64",
        "PATH": "/mingw64/bin:/usr/local/bin:/usr/bin:/bin:${env:windir}/System32:${env:windir}:${env:PATH}"
    }
```

Not sure which git terminal VS Code is using. How can I check it?

**Comment by joaomoreno** [comment]
Run `Git: Show Git Output`. It'll be at the top of the log.

**Comment by Nowhk** [comment]
It show to me the log, yes. At the top I see: Using git 2.8.1.windows.1 from C:\Program Files\Git\cmd\git.exe

Than?

**Comment by joaomoreno** [comment]
Oh I see you are using mingw git, so it's picking up mingw's global config. You need to configure the Windows Git.

**Comment by Nowhk** [comment]
@joaomoreno `git config --global -e` still show the correct user/mail. Not the ones which will be set using VSCode IDE :(

**Comment by joaomoreno** [comment]
mingw is a different environment than Windows.

**Comment by Nowhk** [comment]
@joaomoreno yes, but if I set on settings the mingw terminal, I bet VS Code will use it. How can I say to VSCode "use mingw" env?

In fact, once I do`git commit -m "test"` from terminal (which use mingw), from that moment, VSCode IDE start to work :O

**Comment by joaomoreno** [comment]
> How can I say to VSCode "use mingw" env?

VS Code only supports Git for Windows.

**Comment by Nowhk** [comment]
@joaomoreno I see. So why, after.execute that command from the vscode terminal, automatically switch to "that" git engine?
