### ISSUE TITLE
Where is extensions.confirmedUriHandlerExtensionIds stored?

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#80054]
Issue Type: <b>Bug</b>

This issue is about the following setting:

> **extensions.confirmedUriHandlerExtensionIds**
>
> When an extension is listed here, a confirmation prompt will not be shown when that extension handles a URI.

1. I clicked on an URL handler that targets an extension `vscode-insiders://vscode.git/...`
2. VS Code showed the URL handler pop-up "Allow an extension to open this URL?"
3. I clicked on "Don't ask again for this extension"
4. I clicked Open

Now when I try again, as expected, VS Code doesn't ask me if I want to allow the extension to catch the URL handler event.

The setting `extensions.confirmedUriHandlerExtensionIds` is supposed to contain the ID of the extension I've just allowed, but I can't find in my user settings nor in the workspace settings.

The only place where there's a match (found with `grep`on my homedir) is in some binary cache files.

Where is `extensions.confirmedUriHandlerExtensionIds` stored? Aren't all settings supposed to be stored in settings.json?

VS Code version: Code - Insiders 1.38.0-insider (8cd00a7935eabef4aad0b0130b1d46daca0a47aa, 2019-08-27T06:12:19.868Z)
OS version: Linux x64 4.15.0-58-generic

**Comment by joaomoreno** [comment]
Actually the "remember" feature gets stored in Storage (non user visible) while the setting is used for preemptive confirmations. Now that you mention it, though, everything should just be in settings...

**Comment by bpasero** [comment]
Reopening. Thing is persisted in storage again.

**Comment by joaomoreno** [comment]
Closing as won't fix, since this is a security concern. Extensions have access to APIs which let them programmatically change the user's settings, so they could potentially allow themselves to skip the dialog without user interaction.

**Comment by sguillia** [comment]
Can I disallow an extension to open an URL when I've already allowed it?

**Comment by joaomoreno** [comment]
Great question. We should probably have some sort of UI to clean that up. Created this: https://github.com/microsoft/vscode/issues/82085
