### ISSUE TITLE
Debugger cannot resolve a "${file}" variable reference to a large file (250MB) passed as an argument

### ISSUE THREAD

**Issue by melhior61** [microsoft/vscode#80056]
- VSCode Version: 1.36.1
- OS Version: Windows 7

Hello everybody,

I am currently trying to debug an application simulating large measurement files (250MB) passed as arguments.

My debugging configuration that I use for this is following:
```js
{
            "name": "Debug SIM -c -meas -b -s -1",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/tools/sim/sim.exe",            
            "windows": {    
                "args": [
                    "-c", // continous mode
                    "-m", // measurement-based                           
                    "${file}",    // choose a measurement to be simulated 
                    "-b", // blind mode
                    "-s", // silent mode                                                                                   
                ]
            },            
            "stopAtEntry": true,            
            "cwd": "${workspaceFolder}",   
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "${workspaceFolder}/tools/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
```

The steps I take and the feedback I get:
1. I click on one of the measurements that I have;
2. VS-Code tries to open it in the editor and reports: "The file is not displayed in the editor because it is too large (249.26MB)";
3. I press F5 to start a debugging session and pass the measurement file (as ${file}) to the debugger;
4. The VS-Code reports: "${file} can not be resolved. Please open an editor".

As I think, the reason is that the large measurement file is kind of not "completely" opened in the editor (I mean, opened and displayed), but only opened without being displayed, what seems to be a problem for the debugger or debugging adapter. 

It seems not to be able to reference a file, which is not opened and displayed.

At the same time, the following simulation tasks works perfectly (no problems with referencing):
```js
 {
            "label": "run SIM any_meas -i -m -v -b -s ",
            "type": "shell",
            "windows": {
                "command": "${workspaceFolder}//tools//sim//sim.exe",
                "args": [
                    "-i",
                    "-m",
                    "${file}",
                    "-v",
                    "-b",
                    "-s",
                ]
            },            
            "group": "none",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": []  // Never scan the task output
        },
```

The value of the "--max-memory" is much larger than 300MB and the latest Insiders-build has the same problem:(

Thank you in advance!!!

**Comment by weinand** [comment]
The `${file}` variable expands to the path of the file open in the active editor when you press F5.
If there is no editor open an error dialog show the message "${file} can not be resolved. Please open an editor".
What does the editor contain after the "too large" error has occurred?  Please provide screenshot?

**Comment by melhior61** [comment]
Hello Weinand,

thank you very much for you help!!!

that's how the editor looks like after I click on the measurement file (0000_00000000_000000_222_4933_example.bla) and press F5:
![image](https://user-images.githubusercontent.com/5587238/63953955-97a14a80-ca82-11e9-8021-76e2bbbb0a37.png)

Thank you in advance!

**Comment by weinand** [comment]
The problem is that in the extension host `editorService.activeEditor()` returns undefined when the editor has a size problem. See:
https://github.com/microsoft/vscode/blob/20dd80d91a76cbe80fb1d1979c3a9f02d94ba161/src/vs/workbench/api/node/extHostDebugService.ts#L970-L979

Since there is a visible editor, I think `activeEditor` shouldn't return undefined.

**Comment by jrieken** [comment]
That's the design, editors showing files that are too large simply don't exist for extensions.

**Comment by melhior61** [comment]
Hello Gentlemen,

first of all, thank you very much for such a fast reaction on my request and for your help!!!

I only have one more question, by your permission: 
since the described behavior (the non-existance of the editors showing files that are too large) is due to the design and is not a bug, should I address the issue as a separate "feature-request" in the "C/C++"-repository or would you recommend a different way for it? As I see, it would be a nice-to-have thing:)

Thank you in advance!

**Comment by jrieken** [comment]
This might be partially covered by https://github.com/microsoft/vscode/issues/15178 but it's very unlikely that we will expose huge files to extensions.

**Comment by weinand** [comment]
@melhior61 the C/C++ extension cannot work around the issue because the code that checks for the active editor runs before they get in control. 

I'll put the issue on our (the debug teams's) backlog. Maybe I can find a way to pass more information (about the defunct editor) to the extension host.

**Comment by melhior61** [comment]
Once again, thank you very much!

I have also noticed a similar problem with binary files (or the files using unsupported text encoding), like, for example, XLSX-files.

I use the "Data Preview"-Extension for previewing xlsx-files. The extension does not see a file to open, if it is not displayed.
Here I try to open an xlsx-file in the editor and execute the extension's commando to preview the file:
![image](https://user-images.githubusercontent.com/5587238/64020878-fc1be280-cb32-11e9-9da8-a20417b57eb6.png)

As you see, the extension asks to open the file, so it possibly does not see the file.

If I press "Do you want to open at anyway", the file gets displayed in a binary unreadable format:
![image](https://user-images.githubusercontent.com/5587238/64021349-05f21580-cb34-11e9-8b01-b69a2b908a04.png)

 If I try to execute the same extension's commando to preview the file, it directly works:
![image](https://user-images.githubusercontent.com/5587238/64021408-2c17b580-cb34-11e9-96d3-a65a7e509458.png)


Thank you very much!

**Comment by melhior61** [comment]
Good morning everybody,

please, do not understand the current comment as an attempt to hurry up your debug team!
It is definitely not for this purpose here. 

However, if it could help to promote the present issue in the debug team backlog, it would be already very nice, since we still have quite a demand to git it fixed:)

Great thanks to everybody helping us in advance!!!

**Comment by hackwaly** [comment]
I have the same problem here. To provide a convenient way to debug ocaml bytecode. I implemented a custom editor for `.bc` file. But it doesn't work still. So I provide a context menu as a workaround.

![image](https://user-images.githubusercontent.com/540298/105192399-0351ef00-5b73-11eb-8a0a-0954f3a1bad6.png)
![image](https://user-images.githubusercontent.com/540298/105192756-4f049880-5b73-11eb-9664-283729fa9d5a.png)

**Comment by weinand** [comment]
no action planned.
