### ISSUE TITLE
Quick open matcher weights

### ISSUE THREAD

**Issue by Eugeny** [microsoft/vscode#80057]
Issue Type: <b>Bug</b>

It appears that the quick open matcher doesn't prioritize whole word matches at all. Here's me literally typing in an almost every word of a file's path in, only to find it on third place.

![image](https://user-images.githubusercontent.com/161476/63953003-c9b1ad00-ca80-11e9-92cc-8c0d09bab809.png)

Contrary to #56182, the files above haven't been opened recently

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 19.0.0

**Comment by bpasero** [comment]
The reason for this matching is actually https://github.com/microsoft/vscode/issues/25925: we prefer 100% matches inside the filename over matches that are scattered in filename+folders
