### ISSUE TITLE
On windows File->Open does not support posix paths

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vscode#80058]
Issue Type: <b>Bug</b>

vscode is unable to use "/" as a path separator on windows. When I open a file using File->Open "c:/temp/myfile.txt" I get an error. But from the integrated terminal `code c:/temp/myfile.txt` works just fine.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (0.82GB free)|
|Process Argv|C:\Users\e27290\projects\squadx-new\squadx.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.5.0
project-manager|ale|10.7.0
clipboard-history|Anj|1.0.7
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.1
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.15
docs-preview|doc|0.3.28
docs-yaml|doc|0.2.3
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.9.3
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
matlab|Gim|1.2.0
vscode-peacock|joh|3.1.5
restructuredtext|lex|114.0.0
cmake-tools-helper|mad|0.2.1
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
remote-containers|ms-|0.67.3
remote-ssh|ms-|0.45.6
remote-ssh-edit|ms-|0.45.6
remote-ssh-explorer|ms-|0.45.6
remote-wsl|ms-|0.39.2
vscode-remote-extensionpack|ms-|0.16.0
cpptools|ms-|0.25.0
powershell|ms-|2019.5.0
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.752
printcode|nob|3.0.0
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.9.0
vscode-yaml|red|0.5.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.2
vscode-table-formatter|shu|1.2.1
vscode-fileutils|sle|2.14.9
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
code-spell-checker|str|1.7.18
python|tht|0.2.3
cmake|twx|0.0.17
vscode-terminal-here|Tyr|0.2.4
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.3.0
jinja|who|0.0.8
clang-format|xav|1.9.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This sounds like a Windows upstream issue to me.

@pwm1234 what is the error?

**Comment by pwm1234** [comment]
Yes, you are most likely using stock windows widgets for this. When I use File->Open and enter c:/temp/foo.txt I get an error dialog with contents

````
[Window Title]
Open File

[Content]
c:/temp/foo.txt
The file name is not valid.
````

But `c:/temp/foo.txt` is a perfectly valid name, even on windows, and it works when I use `code c:/temp/foo.txt`. So I would like for it to work from File->Open. (Of course, I understand if this is too much trouble--I just think it would be nice to have.)

**Comment by bpasero** [comment]
@pwm1234 can you attach a screenshot of the error?

**Comment by pwm1234** [comment]
![Clipboard Image](https://user-images.githubusercontent.com/1510112/63998109-5df63100-cace-11e9-8255-b6f95c7a342d.jpg)

**Comment by bpasero** [comment]
This seems to originate from Windows / Electron upstream, not our code.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
