### ISSUE TITLE
.mjs file format break string template

### ISSUE THREAD

**Issue by cjbd** [microsoft/vscode#80052]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

hello, 

for below code:
```js
console.log(`Today : ${todaysDate}`);
```
when using format tool, it changes to
```js
console.log(`Today : $ { todaysDate }`);
```
which breaks string template

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (2.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
python|ms-|2019.8.30787
cpptools|ms-|0.25.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
clang-format|xav|1.9.0

</details>

**Comment by weinand** [comment]
@cjbd what format tool are you using?

**Comment by cjbd** [comment]
@weinand, i'm using `clang format`, ts/js format works

**Comment by weinand** [comment]
Please file an issue against the "clang format" extension
