### ISSUE TITLE
Failed CLI extension installation results in exit code 0

### ISSUE THREAD

**Issue by kroppt** [microsoft/vscode#80065]
Issue Type: <b>Bug</b>

When an extension fails to install via the command line, the exit code should not indicate success.

```powershell
> echo "" > test.vsix
> codium --install-extension .\test.vsix
Installing extensions...
Corrupt ZIP: end of central directory record signature not found
Failed Installing Extensions: .\test.vsix
> echo $lastexitcode
0
```

0 indicates that the operation was successful, even though it was not.

VS Code version: VSCodium 1.37.1 (9afbbd903b7b481aa127d4d8d68626397e6a5135, 2019-08-16T10:21:32.989Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.57GB free)|
|Process Argv|--snip--|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
githistory|don|0.4.6
gitlens|eam|9.9.3
--snip--
innosetup|idl|1.2.0
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vim|vsc|1.10.0

</details>

**Comment by skprabhanjan** [comment]
@sandy081 , I can take a look at this.
Some code pointers would be helpful :)

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/code/node/cliProcessMain.ts#L83

**Comment by sandy081** [comment]
@kroppt looks you are using `codium` which is a different product. It could have been built on top of vs code. Please file issue there.

**Comment by kroppt** [comment]
```powershell
> echo "" > test.vsix
> code --install-extension .\test.vsix
Installing extensions...
Corrupt ZIP: end of central directory record signature not found
Failed Installing Extensions: .\test.vsix
> echo $lastexitcode
0
```
I'm guessing you did not test as I described. Please try yourself.

**Comment by sandy081** [comment]
I can see the exit code

![image](https://user-images.githubusercontent.com/10746682/66191663-265f4380-e68f-11e9-9162-ee9878aea6bd.png)

**Comment by kroppt** [comment]
I just tested it on the latest Insiders build of Visual Studio Code, and I am getting the same result, error code 0 on failure. Maybe the `code-cli.sh` you are using is wrapping the output of `code`. Or perhaps different errors give different error codes on failure?
