### ISSUE TITLE
Visual Studio Code Opens To Many Processes(Instances) Of Itself

### ISSUE THREAD

**Issue by vkrilakis** [Microsoft/vscode#8006]
- VSCode Version:1.2.1
- OS Version:Windows 7

Steps to Reproduce:

1. Open VS Code
2. Look at your taskmgr for Code.exe it is open at least nine times

**Comment by Tyriar** [comment]
This is a consequence of both how vscode was designed and the fact that it's build on Chromium/Electron. The number of processes should not really matter from an end user perspective, it's the amount of work each process does and the communication between them that are important. Some more info here https://github.com/Microsoft/vscode/issues/5856#issuecomment-216274544
