### ISSUE TITLE
File operations should be executed in a queue

### ISSUE THREAD

**Issue by nathanpeck** [microsoft/vscode#80060]
Issue Type: <b>Bug</b>

If you copy a large folder (around 100-200 MB) on the sidebar the copy operation may still be in progress but further file operations on the copy are not forbidden while this copy operation continues silently in the background. This can result in errors. I run into this frequently when copying a folder and then attempting to rename the automatically named copy into a specific name. The copy operation only partially succeeds with missing files because the destination folder changes while the copy operation is in progress.

An error pops up that says "File to paste was deleted or moved meanwhile"

I would suggest either blocking or queueing file operations until the copy is completed. Ideally there should also be some visual feedback or state (progress bar, status message, etc) in the sidebar indicating that the duplicated folder is still in the process of being copied.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.0.0
vscode-eslint|dba|1.9.1
error-gutters|Igo|1.0.1
vscode-docker|ms-|0.7.0
vetur|oct|0.22.2
errorlens|Phi|1.1.3
vscode-graphql|Pri|0.2.1
velocity|sod|0.2.0

</details>

**Comment by isidorn** [comment]
As for the visual feedback of the progress this issue should cover that https://github.com/microsoft/vscode/issues/73996

As for queying the long running operations, renaming this issue so this one can cover that.
Leaving this open as a feature request and assigning to the backlog since we do not have immediate plans to fix this.
Also might be a bit hard to do since some operations can be done in parallel and some can not, so it might be hard to distuinguish.
