### ISSUE TITLE
"Building..." message not removed (compiling in watch mode, using Workspace TSC).

### ISSUE THREAD

**Issue by Eketol** [microsoft/vscode#80066]
I'm using the TypeScript Compiler from the Workspace (not the global one), in a shared project.

When compiling in watch mode, after it finishes compiling the first time, the "Building..." message is never removed.

![image](https://user-images.githubusercontent.com/1121725/63966512-5d8c7480-ca93-11e9-8388-5d583de44735.png)

The "Building..." message should be removed every time it finishes compiling in watch mode.

The message works fine if I use the Global TypeScript Compiler (to compile in watch mode) or if I don't use watch mode at all.

Maybe the way I use the Workspace TSC is wrong? This is the content of my tasks.json containing both tasks, using Workspace and Global TSC:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Debug (workspace tsc)",
			"type": "shell",
			"command": "node",
			"args": [
                "${workspaceFolder}\\node_modules\\typescript\\bin\\tsc",
                "-p",
                "tsconfig_debug.json",
				"--watch"
			],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "clear": true
            },
            "problemMatcher": [
                "$tsc-watch"
            ],
        },
        {
            "label": "Debug (global tsc)",
            "type": "typescript",
            "tsconfig": "tsconfig_debug.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": "build",
            "presentation": {
                "clear": true
            }
        }
    ]
}
```
Tested on: Windows 10 with VSCode 1.37.1 and VSCode Insiders 1.38.0.

Does this issue occur when all extensions are disabled?: Yes

Related issues: #60396 and #50943.

**Comment by alexr00** [comment]
You need to set `"isBackground": true,`

**Comment by Eketol** [comment]
Works like a charm! Thanks very much!
