### ISSUE TITLE
"Replace" keyboard shortcut doesn't work on Mac

### ISSUE THREAD

**Issue by cadin** [microsoft/vscode#80067]
Issue Type: <b>Bug</b>

On Mac, invoking the Replace keyboard shortcut instead maximizes the window to fill the screen. I suppose I could change the Replace shortcut, but I would rather change (or remove) the maximize window shortcut. I don't see a setting for this anywhere.

Steps to reproduce:
On a Mac, open a file and invoke the Replace keyboard shortcut (cmd-opt-f).

Result:
The VS Code app window is expanded to fill the screen.

Expected result:
The Find & Replace UI should appear.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
prettier-vscode|esb|2.2.2
vscode-styled-components|jpo|0.0.26
vscode-framerx-code-snippets|pix|0.0.70

(2 theme extensions excluded)

</details>

**Comment by weinand** [comment]
@cadin for me "cmd-opt-f" works just fine on macOS and opens the Find & Replace UI.

**Comment by cadin** [comment]
Dang, you're right. A system restart fixed it for me. Thanks!

**Comment by weinand** [comment]
No problem, great that you could fix the issue.
