### ISSUE TITLE
Open contained folder in a new VSCode window

### ISSUE THREAD

**Issue by TommasoPieroncini** [microsoft/vscode#80064]
Issue Type: <b>Feature Request</b>

I wish I could right click on one of the linked folder names in my file hierarchy that shows at the top of an opened file and open it in a new VS code window.

Use case:
I searched for something within a large parent folder, I found a file within a child/grandchild folder that contains what i'm looking for, and I want to scope my following searches to that child/grandchild folder -> I right click on the linked folder name an open in a new window

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
Please try https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance
