### ISSUE TITLE
Add a setting scope for workspace only settings

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#80073]
For html/css.customData settings, they are usually only useful in the context of specific folder/workspace they are at. See https://github.com/microsoft/vscode/issues/79911#issuecomment-526072878.

Currently it's impossible to declare a setting as workspace only, so user cannot configure it in user settings.

**Comment by sandy081** [comment]
@octref Can you please describe why a user does not want to customise this for all worksapces?

**Comment by octref** [comment]
Initially I felt this is like a "global variable". If you set user level setting it could affect you negatively.

For example, you can set up custom data so `<foo>` HTML tag and `foo` CSS property always show up in auto completion, but they wouldn't work unless you have the preprocessor (postcss, webcomponent libraries, etc) to compile them down to normal HTML/CSS. As the preprocessors are usually coupled with workspace dependencies, I thought it's a good idea to not allow user level setting.

But @aeschli disagrees here: https://github.com/microsoft/vscode/issues/79911#issuecomment-526496221. So maybe we should allow it nevertheless.
