### ISSUE TITLE
Translation Errors in VS Code Settings when 'French Language Pack for VS Code' is installed

### ISSUE THREAD

**Issue by djdakta** [microsoft/vscode#80076]
- VS Code Version: 1.37.1
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128

- OS Version: macOS Mojave 10.14.6 (18G95)

Steps to Reproduce:

(In order to see this issue, the 'French Language Pack for Visual Studio Code' must be installed.)
- Open VS Code
- Click on 'Code' (macOS version) => 'Preferences' => 'Settings'
- The settings are now open in the right pane of the screen.
- Go to 'Gestion de l'éditeur' under 'Banc d'essai' and you'll see this:

<img width="1038" alt="Capture d’écran 2019-08-15 à 02 23 56" src="https://user-images.githubusercontent.com/6761835/63978608-01d3e280-cab7-11e9-826b-beaf3698723e.png">

In the block 'Reveal if Open':
(second line) '...groupe éditeur actuellement active.' => must be 'actif'

In the block 'Show Tabs'
Contrôle si les ouverts éditeurs... => must be: Contrôle si les éditeurs ouverts ...

If I knew where to find this in the VS Code repo but... 
If someone can tell me where to find this in it, it would be very nice and I would be able to correct it myself.

That's it for now.

**Comment by djdakta** [comment]
I found other tanslation errors.

<img width="784" alt="Capture d’écran 2019-08-15 à 02 26 37" src="https://user-images.githubusercontent.com/6761835/63984961-be38a300-cacd-11e9-9dee-3d9439ccce25.png">

Close When Empty => Contrôle si la fermeture le dernier editeur... => must be: Contrôle si la fermeture du dernier...

**Comment by djdakta** [comment]
I found more errors and I think I'll find some more if I took the time to 'scan' everything. :-) :-(
I'll wait until I get a reply with where I can find the files I need to change in the repo so I would be an even better contributor instead of creating/adding more bugs.
Thanks for your reply allready.

**Comment by janbaltus** [comment]
Hi we will review your translation changes.
@djdakta  translation can be found here https://github.com/Microsoft/vscode-loc/

**Comment by lukaschal** [comment]
All suggestions implemented.
