### ISSUE TITLE
the letter 'ñ' cannot be written in the vscode terminal

### ISSUE THREAD

**Issue by maravento** [microsoft/vscode#80072]
I write in the terminal 'manana', but I can't write 'mañana', it doesn't allow it. If I try to insert the letter 'ñ' in the word 'manana' it is not allowed either.
manana
![manana](https://user-images.githubusercontent.com/14880802/63973359-3f614d00-ca70-11e9-917c-f058bdb017cd.png)
mañana
![mañana](https://user-images.githubusercontent.com/14880802/63973360-3ff9e380-ca70-11e9-899b-043b0919e70d.png)

**Comment by maravento** [comment]
It is not in a text. it's in the terminal

**Comment by Tyriar** [comment]
What platform? If you're on Windows what shell is that?

**Comment by maravento** [comment]
ubuntu 18.04.3 x64

**Comment by Tyriar** [comment]
I can't reproduce, it's likely an environment config issue. I recommend looking into the setLocaleVariables setting and your $LANG env var

**Comment by maravento** [comment]
i found the answer here https://github.com/Microsoft/vscode/issues/35550#issuecomment-354304353

**Comment by Tyriar** [comment]
@maravento can you share the good `$LANG` value (with setLocaleVariables: false) and the bad one (where it's not set)?

**Comment by maravento** [comment]
local: echo echo $LANG
es_CO.UTF-8

**Comment by Tyriar** [comment]
@maravento is that the one that's working? If so what's the value when it's not working?

**Comment by maravento** [comment]
In Ubuntu 18.04.x x 64 LTS, with locales es_CO.UTF-8:

When check the box `terminal.integrated.setLocaleVariables` And I press 'ñ' on the terminal, the out is 'arg 1'
![Captura de pantalla -2019-09-09 14-33-04](https://user-images.githubusercontent.com/14880802/64560915-1ada6000-d30f-11e9-8330-2e553a34db14.png)
When uncheck the box `terminal.integrated.setLocaleVariables` And I press 'ñ or Ñ' on the terminal, the out is 'ñÑ'
![2](https://user-images.githubusercontent.com/14880802/64561157-a9e77800-d30f-11e9-9e01-20498e378617.png)

**Comment by Tyriar** [comment]
Verify that `terminal.integrated.detectLocale` works on Linux or macOS as described in its setting description. `echo $LANG` in the terminal to verify the values, its eventual value depends on:

- The value of the setting
- What `$LANG` is set in Code's enironment
- The display language of VS Code (change using Configure Display Language command)

**Comment by maravento** [comment]
Why do you close the ticket if the problem is still there, without solution?

**Comment by maravento** [comment]
@Tyriar Ok. Thanks
