### ISSUE TITLE
Holding alt to put multiple cursors with full screen and hidden menu also pops down the menu

### ISSUE THREAD

**Issue by achshar** [Microsoft/vscode#8007]
- VSCode Version: 1.2.1
- OS Version: Win 10

Steps to Reproduce:

1. Put the editor in full screen mode.
2. Hide the menu from view > toggle menu bar.
3. Hold alt key and put in one or more cursors in the editor.
4. Release the alt key. The cursors work fine but the menu pops up as well.

It would be nice if code can not show the menu on alt press if one or more cursors were placed on the screen while the key was down. Since the menu only pops up on keyup, I reckon this should be possible. I use this pattern a lot and it's very distracting to have the menu pop up and move the entire window one step down.

**Comment by dbaeumer** [comment]
Not sure if this is a workbench or editor issue

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10224
