### ISSUE TITLE
Node packages routing to Microsoft folder in AppData and not node_modules folder in project

### ISSUE THREAD

**Issue by duncankmckinnon** [microsoft/vscode#80078]
Issue Type: <b>Bug</b>

For some reason, the environment is storing and linking to node packages stored in User/{username}/AppData/Local/Microsoft/TypeScript instead of the packages in /{project}/node_modules.  This has been the source of problems with testing packages like supertest, nock and sinon.   If I delete the TypeScript folder, things work again, but eventually the folder gets re-created and the definitions get sourced to it again.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.7.0

</details>

**Comment by weinand** [comment]
@duncankmckinnon you said "the environment is storing and linking". What do you mean by this?
Please provide reproducible steps.

**Comment by mjbvz** [comment]
Closing as more info is needed
