### ISSUE TITLE
launch options: optional shortkeys for different modes

### ISSUE THREAD

**Issue by n8crwlr** [microsoft/vscode#80070]
In `launch.json` or `settings.json` i have

```json
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "debug",
                "request": "launch",
                "type": "dart",
                "flutterMode": "debug"
            },
            {
                "name": "release",
                "request": "launch",
                "type": "dart",
                "flutterMode": "release"
            },
            {
                "name": "profile",
                "request": "launch",
                "type": "dart",
                "flutterMode": "profile"
            }
        ]
    },
```

a i have to start very often in another mode. So i would like to have shortkeys defined (which will be with highest priority in keyboard-shortcuts), like the following:

```json
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "debug",
                "request": "launch",
                "type": "dart",
                "flutterMode": "debug",
                "shortkey": "F5" *
            },
            {
                "name": "release",
                "request": "launch",
                "type": "dart",
                "flutterMode": "release",
                "shortkey": "F6" *
            },
            {
                "name": "profile",
                "request": "launch",
                "type": "dart",
                "flutterMode": "profile",
                "shortkey": "F7" *
            }
        ]
    },
```

`* optional`

**Comment by n8crwlr** [comment]
Not sure,

i found `"debug.showInStatusBar": "always"` which works good, too 👍 

My intention was to not switch to debug in sidebar all the time where i just have to run apps on my phone. Now i can click at statusbar and then choose the mode - which is good enough.

Feel free to close this request

**Comment by n8crwlr** [comment]
`"debug.showInStatusBar": "always"` seems not to work after closing the folder and opening a new project. Now it`s gone again, but is set to `"debug.showInStatusBar": "always"` as written.

![image](https://user-images.githubusercontent.com/54250425/63980814-000d1d80-cabd-11e9-8095-d4e169e2b417.png)

**Comment by n8crwlr** [comment]
`"debug.showInStatusBar": "always"` _does not_ work as espected to me - sometimes it is shown, sometimes not. Whats that state? There are differences in openening closing projects / vs code.

![image](https://user-images.githubusercontent.com/54250425/63982445-c3442500-cac2-11e9-8f5b-90513751f70c.png)

![image](https://user-images.githubusercontent.com/54250425/63982467-e7076b00-cac2-11e9-8871-bd84cd230ad4.png)

So, maybe it's not optimal as suggested

**Comment by isidorn** [comment]
The first request to launch a specific launch configuration can be done via an extension and we do not want this behavior in the core vscode. The extension can contribute a command, assign any keybinding to it, read the content of the launch.json and launch a new debug seassion using [this api](https://github.com/Microsoft/vscode/blob/3b439a8c493f94fa66b44a2a54d1889a9e8120cb/src/vs/vscode.d.ts#L9093)

As for the statusBar visibility.
`"debug.showInStatusBar": "always"`  always show the status bar entry for me.
If that is not he case for you please file a new issue with exact reproducable steps so we can investigate more and fix this. Thanks

**Comment by isidorn** [comment]
As the bot would say

We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!
