### ISSUE TITLE
does not restore the files i have opened before closing it

### ISSUE THREAD

**Issue by ww-gustavomuniz** [microsoft/vscode#80085]
Issue Type: <b>Bug</b>

When opening visual studio code it does not restore the files i have opened before closing it

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.5.0

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please give step-by-step details of exactly what you are doing, what you are seeing, and what you expected. Screenshots may be useful, and can usually be copied to clipboard then pasted directly into your update.

**Comment by weinand** [comment]
@ww-gustavomuniz did you configure the `"window.restoreWindows"` setting?
