### ISSUE TITLE
Buttons are cropped on the files save confirmation dialog while quitting VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8008]
- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:

1. I have a large number of dirty files (around 255). Of course I am using Search and Replace :)
2. Close VS Code
3. I get following dialog where buttons are cropped

![Cropped actions](https://cloud.githubusercontent.com/assets/10746682/16271474/7789b534-389a-11e6-935a-80cfa3f73535.png)

**Comment by bpasero** [comment]
@sandy081 I am now doing this:

![image](https://cloud.githubusercontent.com/assets/900690/16373260/a41b5638-3c51-11e6-8281-55c265eb442a.png)
