### ISSUE TITLE
copy expanded launch.json command 

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#80088]
Provide an easy way to copy the current launch.json command to clipboard so I could paste in terminal to run the desired launch without starting the debugging and show that top panel.

**Comment by weinand** [comment]
A launch configuration cannot be executed in a terminal directly. A debug extension must transform this into something executable first.

But you can run launch configuration *without debugging* with the "Start without Debugging" action (Cntl+F5).

**Comment by xgdgsc** [comment]
Thanks. I find the floating debug toolbox annoying, is there a way to make it dock somewhere?

**Comment by xgdgsc** [comment]
I thought vscode generates command line from this configuration, so it might be possible I could get this final commands and save them elsewhere.

**Comment by weinand** [comment]
Debug extensions generate the command line from the launch configurations (because only they know and understand the specific attributes of a launch config).

Try to set the setting `"debug.toolBarLocation"` to `"docked"`.

**Comment by xgdgsc** [comment]
Thanks.
