### ISSUE TITLE
Not highlighting when peeking function's comments/documentation

### ISSUE THREAD

**Issue by madacol** [microsoft/vscode#80082]
Issue Type: <b>Bug</b>

- Open new file with javascript syntax
- Paste this:
```js
/** yadayada
 * @param {number} var    **This highliting doesn't work**
 * @param {string} var2   But**This works!**
*/
const documented_function = () => {}

documented_function();
```
- Hover the function to peek it's comments
![Screenshot from 2019-08-29 18-08-28](https://user-images.githubusercontent.com/6379896/63982442-12209900-ca88-11e9-8849-b6f45f6319b1.png)
**Note**: The highlighting error happens in the peek mini-window, not in the editor

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.53GB (0.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|57%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/33386 to track upstream
