### ISSUE TITLE
Cannot install extensions to visual studio code insiders

### ISSUE THREAD

**Issue by maherkhalil07** [microsoft/vscode#80084]
Cannot install extensions to visual studio code insiders
it asks for manual download 

code-insiders_1.38.0-1567087590_amd64
os ubuntu

- VSCode Version:code-insiders_1.38.0-1567087590_amd64
- OS Version: ubuntu

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/34385#issuecomment-521286975 etc for  advice about resolving by using different DNS servers
