### ISSUE TITLE
Explorer: should not require a timeout(0) after expanding

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80098]
Ever since this change I feel the tree has gotten slower in reacting to my file changes to reveal it.

https://github.com/microsoft/vscode/blob/83f257472ac3aad3d67c7b3a7c4c66f94fd73d26/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L526

**Comment by joaomoreno** [comment]
As I mentioned in the original issue (link missing), I'd like @isidorn to reproduce this such that we fix it in the tree level.

**Comment by isidorn** [comment]
Yeah. Let's look at this on Monday. I can repro on the tree level.

**Comment by joaomoreno** [comment]
Repro:

1. Open two folders in multiworkspace: `vscode` and `vscode-docs`
2. Disable `explorer.autoReveal`
3. Recursively collapse all folders in explorer
4. Open `asyncDataTree.ts`
5. Reload
6. Run `File: Reveal Active File in Side Bar`

I was able to write a test which catches this. Now for the fix...
