### ISSUE TITLE
Scope tree errors per user

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#80097]
@bpasero 

> This is still our number 1 crash.

We need to change the message

```
Data tree node not found
```

Into:

```
[Explorer] Data tree node not found
[Problems panel] Data tree node not found
...
```

From https://github.com/microsoft/vscode/issues/79182#issuecomment-521561824

**Comment by isidorn** [comment]
Yeah, this would be great!

**Comment by joaomoreno** [comment]
That was a MASSIVE commit.

**Comment by isidorn** [comment]
Touched half the world
