### ISSUE TITLE
I can not install extensions anymore - No Proxy 

### ISSUE THREAD

**Issue by MMajd** [microsoft/vscode#80092]
I can not install any extension any more through extension gallery 
No proxy used 

OS: Ubuntu 18.04
VSCode Version: July 2019 1.37

Here's an image to what happen when i try to install any extension 
![image](https://user-images.githubusercontent.com/11295576/63993713-20a39a80-caf2-11e9-8af0-ee63fc8bcfdc.png)

Here's an image to network tab
![image](https://user-images.githubusercontent.com/11295576/63993832-91e34d80-caf2-11e9-9038-4f352cdde8ae.png)

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/34385#issuecomment-521286975
