### ISSUE TITLE
Some keybingings are shown on different keyboard layout

### ISSUE THREAD

**Issue by w7rus** [microsoft/vscode#80094]
Issue Type: <b>Bug</b>

Having a US Windows 10 system. Additionally install russian language pack.
Some keybindings in tutorial and interface overview using russian letters instead of english ones.
Examples:
https://i.imgur.com/Ludg8Jh.jpg
https://i.imgur.com/RPBnKNE.jpg

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
Lua|key|0.0.9
vscode-icons|vsc|9.3.0

</details>

**Comment by techiedesu** [comment]
Same.
![image](https://user-images.githubusercontent.com/21150432/63997563-0df88800-cb29-11e9-9f97-9cfe567a9e38.png)

**Comment by alexandrudima** [comment]
I could not reproduce. I have installed the following:
![image](https://user-images.githubusercontent.com/5047891/64478919-00d63b80-d1b0-11e9-86dd-65e266159419.png)

And I chose it in the input language picker:
![image](https://user-images.githubusercontent.com/5047891/64478930-2cf1bc80-d1b0-11e9-9c1e-3c3ca42ec225.png)

And here is how that welcome page looks for me:
![image](https://user-images.githubusercontent.com/5047891/64478937-4a268b00-d1b0-11e9-98d2-c248f390d697.png)

**Comment by techiedesu** [comment]
@alexandrudima I tried to find steps to reproduce:

1. Open VSCode
2. Change keyboard language to russian
3. Click "Interface Overview"

**Comment by alexandrudima** [comment]
I could reproduce now, I'm not sure what was different, I might have had keybindings customizations by accident when I last tried.

![image](https://user-images.githubusercontent.com/5047891/64646230-f10c6080-d416-11e9-998c-855dfd80b30a.png)

But this does not look like a bug to me:

When I use the on screen keyboard, it appears that the key left of `1` is labeled with `ё` and when I press `Ctrl + ё` I get the integrated terminal. So the keybinding is displayed correctly in the welcome guide, pressing `Ctrl + ё` toggles the integrated terminal:

![russian](https://user-images.githubusercontent.com/5047891/64646409-582a1500-d417-11e9-8aeb-93c87cf8c755.gif)

**Comment by techiedesu** [comment]
We cannot understand why other hotkeys use latin letters. It is not consistent.

**Comment by alexandrudima** [comment]
That is a good point. We have special case code for all the keys A - Z [here](https://github.com/microsoft/vscode/blob/bd2d2a61c1f3ae253eb7c1b60506161a1ce2d70e/src/vs/workbench/services/keybinding/common/windowsKeyboardMapper.ts#L319-L350) but that only covers A-Z...

**Comment by alexandrudima** [comment]
I will tweak this, but just to clarify, my change will impact more than the label for Backquote under the Russian keyboard layout:

```
BracketLeft   х -> [
BracketRight  ъ -> ]
Semicolon     ж -> ;
Quote         э -> '
Backquote     ё -> `
Comma         б -> ,
Period        ю -> .
Slash         . -> /
```
