### ISSUE TITLE
"debug.showInStatusBar": "always" does not work

### ISSUE THREAD

**Issue by n8crwlr** [microsoft/vscode#80105]
I want to have **debug** show in _statusbar_ permanently, but `"debug.showInStatusBar": "always"` is differently ignored.

To reproduce i will just give an _npm project structure_ - in real, i have this with _flutter projects_.

### VS Code
```bash
A:\apps>code --version
1.37.1
f06011ac164ae4dc8e753a3fe7f9549844d15e35
x64
```

`settings.json`:
```json
{
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "debug",
                "request": "launch",
                "type": "dart",
                "flutterMode": "debug"
            },
            {
                "name": "release",
                "request": "launch",
                "type": "dart",
                "flutterMode": "release"
            },
            {
                "name": "profile",
                "request": "launch",
                "type": "dart",
                "flutterMode": "profile"
            }
        ]
    },
    "debug.showInStatusBar": "always",
    "debug.showSubSessionsInToolBar": true
}
```

### Setup
```bash
A:\apps>mkdir z1
A:\apps>mkdir z2

A:\apps\z1>npm init
... <enter> to the end
Is this OK? (yes)

A:\apps\z2>npm init
... <enter> to the end
Is this OK? (yes)
```

### opening `z1` and `z2` first time:

![image](https://user-images.githubusercontent.com/54250425/64014055-7d6a7980-cb21-11e9-80a9-e5283a02dfb6.png)

![image](https://user-images.githubusercontent.com/54250425/64014112-a4c14680-cb21-11e9-92c5-feb883a9c409.png)

### opening `z1` again:

![image](https://user-images.githubusercontent.com/54250425/64014225-e81bb500-cb21-11e9-93d8-73a941704f2b.png)

### debugging first time in `z1`:

![image](https://user-images.githubusercontent.com/54250425/64014274-084b7400-cb22-11e9-84d7-072849f1432e.png)

### reopening `z2`, than `z1` again:

![image](https://user-images.githubusercontent.com/54250425/64014363-33ce5e80-cb22-11e9-8be4-18c3c88d1a2d.png)

![image](https://user-images.githubusercontent.com/54250425/64014407-4fd20000-cb22-11e9-8db7-e0a9a9d1a5f7.png)

## Conclusion

**As you can see, "debug" is only `"debug.showInStatusBar"` after first debugging session has run.**

I would like to have it always there, as the setting _speeks_ "always".

(initial issue is https://github.com/microsoft/vscode/issues/80070#issuecomment-526395022)

**Comment by isidorn** [comment]
Do you maybe also have this set in user settings? 
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by n8crwlr** [comment]
Sorry, since changing the settings-structure itself to the new UI longer time ago i do not know where to find what. So, this settings file i have is: `C:\Users\n8\AppData\Roaming\Code\User\settings.json`.

After installing insiders and setting `"debug.showInStatusBar": "always"` same issue:

![image](https://user-images.githubusercontent.com/54250425/64025706-997c1400-cb3d-11e9-85c0-a1733636ee38.png)

But, i have to copy my launch options, so next first open another new project `y2`:

![image](https://user-images.githubusercontent.com/54250425/64026187-874ea580-cb3e-11e9-87a5-7231d132aab5.png)

**Still no success, even in `y1` nor `y2` with launch options**

I have forgotten to install flutter / dart package for my launch config, but same issue in third new project `y3`:

![image](https://user-images.githubusercontent.com/54250425/64026558-4c00a680-cb3f-11e9-9ca5-c426c4142077.png)

**And again, after first started debug-session, closing and reopening `y3`:**

Now it's available:

![image](https://user-images.githubusercontent.com/54250425/64026804-c7625800-cb3f-11e9-991c-b60ca156c8cc.png)

**Comment by n8crwlr** [comment]
Just to prevent some misunderstanding: the **debug** in statusline is available _with the first run_ of the debugger-session. I _must not_ close the project and reopen it. But, my problem is, it should be always available as soon the option is set to `always`.

**Comment by isidorn** [comment]
@n8crwlr how about if you `F1 > Open Workspace Settings` and put the setting there? Does it still not work?

**Comment by n8crwlr** [comment]
@isidorn 

no, same as before (Code and Insiders)

![image](https://user-images.githubusercontent.com/54250425/64129450-5aa7c180-cdbc-11e9-9370-4d6af6d7fc0e.png)

Both Apps are reloaded, too.

**Comment by isidorn** [comment]
What happens if you have your launch configurations in a `launch.json` file, and not in your user settings?

**Comment by n8crwlr** [comment]
I have deleted `C:\Users\Ben\AppData\Roaming\Code - Insiders`, so nothing in there.

`launch.json` and workspace-settings are set. Nothing else in there.

I have also tried `"debug.showInStatusBar": "always"` in user-settings.

![image](https://user-images.githubusercontent.com/54250425/64131621-1ae7d680-cdca-11e9-92b1-0166379e2e56.png)

The only setting i must have for `"debug.showInStatusBar": "always"` is `"debug.showInStatusBar": "always"`, correct?

**Comment by isidorn** [comment]
Thanks for trying it out. Yes, only that setting is need. I still can not reproduce this.
The only thing we can do is if you debug on your machine, so
F1 > developer tools > Source > put a breakpoints [here](https://github.com/Microsoft/vscode/blob/a5a8a28953e4efe0e05b1410ed1fc90e1ce92d77/src/vs/workbench/contrib/debug/browser/debugStatus.ts#L31)
Reload the window and try to figre out why it is not shown in the status bar

**Comment by n8crwlr** [comment]
Hmm, i will post some images:

![image](https://user-images.githubusercontent.com/54250425/64199728-3830a980-ce8b-11e9-910b-d87f3ef857bb.png)

![image](https://user-images.githubusercontent.com/54250425/64199760-4ed70080-ce8b-11e9-89e3-58198288f564.png)

![image](https://user-images.githubusercontent.com/54250425/64199784-61513a00-ce8b-11e9-97e4-3fcfb7dd8d48.png)

```bash
ReferenceError: IDebugConfiguration is not defined
at eval (eval at o (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2644:716), <anonymous>:1:1)
at o (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2644:716)
at new c (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2644:831)
at d._createInstance (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1430:671)
at d.createInstance (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1430:92)
at n (file:///C:/Users/n8/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2504:539)
```

![image](https://user-images.githubusercontent.com/54250425/64200131-226fb400-ce8c-11e9-8f9c-183478454d9b.png)

![image](https://user-images.githubusercontent.com/54250425/64200166-33202a00-ce8c-11e9-9a68-7d44dfcc2a08.png)

**Comment by isidorn** [comment]
Just step over that line, do some real debugging and investigation. Pictures will not help here.

**Comment by n8crwlr** [comment]
Ok, i have absolutely to time to think about that. Thanks for the quidiance
