### ISSUE TITLE
TS formatting rules changed from 3.5.2 to 3.6.2

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#80118]
I had to commit https://github.com/microsoft/vscode/commit/defb2320c11feb3002bedd0bb715cc90f4f0215a with `--no-verify` because the following errors were popping up in hygiene:

```
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/browser/parts/views/customView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/debug/browser/breakpointsView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/debug/browser/callStackView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/debug/browser/debugHover.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/debug/browser/variablesView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/files/browser/views/explorerView.ts
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/files/browser/views/openEditorsView.ts
```

`Format Document` doesn't seem to do anything on those documents.

**Comment by joaomoreno** [comment]
Yup. Formatting it with 3.5.2 (workspace) instead of 3.6.2 (built-in) actually solves it.

**Comment by bpasero** [comment]
That is always my trick and I think this only happens if we diverge.

**Comment by joaomoreno** [comment]
@mjbvz Wanna update our workspace TS version?

**Comment by joaomoreno** [comment]
And should we have a tool to reformat all our sources, such that we run it whenever we update TS?

**Comment by mjbvz** [comment]
Yes was a formatting fix by the TS team. If you run into this issue, right now make sure you are using the workspace version of TS. The TS 3.6 update may take some extra time this iteration.

I think we can run `tsfmt` on our code once we do update to TS 3.6
