### ISSUE TITLE
TypeScript intellisense extract code not working

### ISSUE THREAD

**Issue by Arlen22** [microsoft/vscode#80110]
After the latest update, VS Code will sometimes not show the lightbulb icon to extract method to enclosing scope and related actions. I don't know why this is and I can't figure out what made it happen, but I can't fix it either, so it's not like I'm having trouble getting it to happen. I just started code with extensions disabled and it is still that way. But last night I got it to work one time. 

And now it suddenly started working again. Without any changes, except me typing that last paragraph. Is there some kind of time delay? Or does it not work with certain selections?

I was trying to select a function call and if I select the semicolon after it the lightbulb does not show up, but if I don't include the semicolon it shows up. The function call was part of a let statement `let myvar = [functionCall(args);]` with the square brackets indicating the selection. 

However, it also happened when I selected a block of code containing a return statement, but if I did not include the return statement the lightbulb showed up. 

Select a while statement block the lightbulb did not show up. The while statement contained the offending return statement I just mentioned. 

- Version: 1.37.1
- Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
- Date: 2019-08-15T16:16:34.800Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Select a block of code
2. Fail to see lightbulb icon in normal location

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share example code and simple steps to reproduce the problem

**Comment by Arlen22** [comment]
Here's an example of the semicolon problem. Select the function body except for the semicolon in the return statement and you should not see the lightbulb icon. Same with selecting the entire `if(conflict.length) ... ;` statement with and without the semicolon being selected. 

```typescript
function test (settingsObj: { tree: {} | string }, routeKeys: string[]) {
  if (typeof settingsObj.tree === "object") {
    let keys: string[] = [];
    settingsObj.tree
    let conflict = keys.filter(k => routeKeys.indexOf(k) > -1);
    if (conflict.length) console.log(
      "The following tree items are reserved for use by TiddlyServer: %s",
      conflict.map(e => '"' + e + '"').join(', ')
    );
  }
  //remove the https settings and return them separately
  return { settings: settingsObj };

}
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/33325 to track this upstream
