### ISSUE TITLE
Electron: investigate to reduce the binary size

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80119]
The E6 update comes with another jump in binary size. We should really try to reduce our binary size and remove unneeded things.

Diff:
![image](https://user-images.githubusercontent.com/900690/64033813-98eb7980-cb4d-11e9-9542-637efb8ea3e7.png)

Build Chart (notice the jump when we went with E4):
![image](https://user-images.githubusercontent.com/900690/64033834-a274e180-cb4d-11e9-9f5a-252c0081ea57.png)

**Comment by bpasero** [comment]
I see another 10MB increase for Linux and about 1-2 MB increase on other platforms. Not good :|

**Comment by deepak1556** [comment]
> I see another 10MB increase for Linux 

@bpasero its because chromium ships additional swiftshader shared library for vulkan backend with this release `libvk_swiftshader.so`. To be fair this backend is experimental, we could disable it and avoid shipping the library but I am not sure if its worth the effort.

**Comment by deepak1556** [comment]
Closing as not actionable since runtime versions have changed.
