### ISSUE TITLE
First term of a condition is wrong when changed via the debugger

### ISSUE THREAD

**Issue by xavier-deryckere** [microsoft/vscode#80111]
> let yesOrNo = false;
> let cond = yesOrNo || false; // put a breakpoint here, change yesOrNo to true
> console.log(`${yesOrNo} || false -> ${cond}`);

When just running this piece of code, cond is false, as expected.
If you stop on the second line, change the value of yesOrNo to true and continue, you get ... false again, which is wrong.
- This happens only with the first term of the expression
    let cond = a || b || c => can change b or c, no problem, the result is ok
- This happens only if the first term has been declared just one line above.
If you insert an instruction between the declaration and the condition, no problem.

With Visual Studio Code 1.37.1 (and previous)

**Comment by weinand** [comment]
What debugger is this?

**Comment by xavier-deryckere** [comment]
Visual Studio Code itself.
We noticed this with typescript but a simple .js does the same.

**Comment by weinand** [comment]
This is node.js behavior. Most likely you will see the same behavior with Chrome DevTools.

**Comment by weinand** [comment]
no response. Closing.

**Comment by xavier-deryckere** [comment]
I was in a training and did not monitor this issue.
I changed the value with the debug console.
- Put the code in a file
- Open the file in VS Code
- Put a breakpoint (F9) on the 'let cond' line
- Run (F5 - add a 'node' section in launch.json)
- in the debug console, enter "yesOrNo = true"
- execute current instruction (F10)
- check the value of "cond", it is false, while true was expected

**Comment by roblourens** [comment]
This is an interesting bug! However, I see the same behavior in chrome devtools and I don't think there's anything I can do to improve this.

I suspect that when the breakpoint is hit, the first term in that expression has already been evaluated. The v8 debugger is full of interesting little quirks like this. Feel free to file an issue upstream: https://bugs.chromium.org/p/chromium/issues/list
