### ISSUE TITLE
Search all files and search in a file have different behavior

### ISSUE THREAD

**Issue by hwhung0111** [microsoft/vscode#80117]
- VSCode Version: 1.38.0-insider (e77b008fb04222192a608906ff603bd72943d779)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open vscode source code folder
2. search whole folder with `(PROG|TEST)` and click `Match Case`, `Match Whole Word` and `Use Regular Expression`
3. the results include LATEST, CGPROGRAM, PROG_OUTPUT...
4. if use `(PROG|TEST)` to search in a single file, the result will not include LATEST, CGPROGRAM, PROG_OUTPUT and only show PROG or TEST.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Thanks for filing, but this is a hard problem: https://github.com/microsoft/vscode/issues/23785

And also have https://github.com/microsoft/vscode/issues/27280 to improve it
