### ISSUE TITLE
Multiple cursor paste  breaks when trying to replace more than 2 occurrences

### ISSUE THREAD

**Issue by yury-s** [microsoft/vscode#80128]
Issue Type: <b>Bug</b>

In the following source file

``` js
class Foo {
  /**
   * @param {string} expression
   * @return {!Promise<!Array<!Puppeteer.ElementHandle>>}
   */
  async $x(expression) {
    const context = await this.executionContext();
    return context.$x(expression);
  }

  /**
   * @param {string} selector
   * @param {Function|string} pageFunction
   * @param {!Array<*>} args
   * @return {!Promise<(!Object|undefined)>}
   */
  async $eval(selector, pageFunction, ...args) {
    return this._mainWorld.$eval(selector, pageFunction, ...args);
  }

  /**
   * @param {string} selector
   * @param {Function|string} pageFunction
   * @param {!Array<*>} args
   * @return {!Promise<(!Object|undefined)>}
   */
  async $$eval(selector, pageFunction, ...args) {
    return this._mainWorld.$$eval(selector, pageFunction, ...args);
  }

  /**
   * @param {string} selector
   * @return {!Promise<!Array<!Puppeteer.ElementHandle>>}
   */
  async $$(selector) {
    return this._mainWorld.$$(selector);
  }
}
```
 I'm trying to replace 3 occurrences of 
``` js
{
    return this._mainWorld.
```
with
``` js
{
    const context = await this.executionContext();
    return context.
```
using multi edit feature (Ctrl+D). It works fine if I select only first 2 entries but does weird thing when selecting all 3.

See [screencast](https://youtu.be/Q_1vtT-4BSQ) with reproduction steps.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (56 x 1000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|125.61GB (60.50GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yury-s** [comment]
The same video in a better quality: 
[repro.zip](https://github.com/microsoft/vscode/files/3561079/repro.zip)

**Comment by alexandrudima** [comment]
Let's track in #80624
