### ISSUE TITLE
Tab key when indenting with spaces does not insert correct number of spaces

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode#80129]
Issue Type: <b>Bug</b>

Related to #2798.

Suppose I have a line of Python in a space-indented file like this:

```python
    do_something()
```

I want to wrap it in a conditional, so I add a line above it:

```python
    if condition:
    do_something()
```

Now I need to indent the body of the conditional, so I click somewhere in the whitespace to the left of that line, and press Tab:

```python
    if condition:
     do_something()
```

It only inserts one space, awkwardly leaving the line with 5 space indentation when the file is set to use 4 spaces per tab.

Why? Because it only looks at the column position of the cursor when deciding how many spaces to insert, and not the total number of contiguous space characters there are.

This is almost certainly *never* what a programmer wants.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_167977|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rgov** [comment]
@weinand I do not believe that this is caused by an extension. I disabled all extensions (`code --disable-extensions`) and tried again and the issue reproduces. Does the issue not reproduce for you?

**Comment by egamma** [comment]
@rgov the indentation behaviour is language specific and needs to be provided by a language extension. In this case it is the python extension. Therefore pls report the issue against the Python extension.
