### ISSUE TITLE
Snippets - Apply multiple transforms

### ISSUE THREAD

**Issue by dgp1130** [microsoft/vscode#80126]
I would like to apply multiple regex transformations in series, and I don't see any good way of doing that.

The use case where I encountered this was generating a test scaffold for custom elements. My project uses a convention where all custom elements are defined in their own files, where the file name matches the custom element name using underscores instead of dashes. Tests have the same name followed by `_test`. So this looks like:

Custom element: `<my-element></my-element>`
Source: `my_element.ts`
Test: `my_element_test.ts`

I would like to use a snippet to generate a starting Jasmine test file, so it looks something like:

```typescript
describe('<my-element>', () => {
  // ...
});
```

This involves transforming the test file name into the the custom element syntax. I don't see a solid way of doing this, the closest I have is a nested transformation like so:

```
describe('<${TM_FILENAME/(.*)_test\\.ts/${1/_/-/g}/}>', () => {
  // ...
});
```

However this interprets the `$1` as an argument to be supplied by the user, not the first capture group of the regex. Alternative possibilities involve defining a custom variable with the result of the first regex (`my_element`), and then applying a transformation on that to get the final result (`my-element`). However, defining custom variables also isn't supported. I'm open to whatever means of accomplishing this, I'd just like to see *some* mechanism for applying multiple transformations.

Googling around, I'm unable to find any specific solution to run multiple regular expressions in series on an input. Tricks like `/uppercase` or `/pascalcase` can workaround this problem, but only in very specific circumstances and don't help for my case here (ironically, some kind of `/skewercase` is exactly what I need here, but this issue is more broad than that).

The [snippet grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) only seems to allow transforms in variables or tabstops, which seems very limiting. If there's any way we could work the grammar to apply arbitrary input into it, that could also solve this particular problem and would probably be the most general fashion.

**Comment by ArturoDent** [comment]
Try this:
`"describe('<${TM_FILENAME/^([^_]+)_?([^_]*)?_?([^_]*)?_?([^_]*)?_test\\.ts/$1${2:+-}$2${3:+-}$3${4:+-}$4/g}>', () => {"`

all in one line of course.  **Not** the most elegant but works for 1-4 cases like:

 ```
 element_test.ts
 my_element_test.ts
 my_element_extra1_test.ts
 my_element_extra1_extra2_test.ts
```

**Comment by dgp1130** [comment]
This issue is not "I don't know how to do X", rather this issue is "I believe it is impossible to do X and am requesting a feature to support it". If this is actually possible, then let me know and we can close this issue. @ArturoDent's solution can be a reasonable workaround for some use cases, but can only support a hard-coded number of underscores, which is a pretty limiting constraint.

The [snippet grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) only allows transformations of variables or tabstops, neither of which can accept arbitrary input. That leads me to believe that certain transformations are simply impossible. I'd like to see this as a future feature to the snippets system to provide more flexibility to users.
