### ISSUE TITLE
Markdown: use shared TSConfig for "target"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80121]
I do not really understand why the markdown extension sets its own target for tsconfig: https://github.com/microsoft/vscode/blob/f91ed14/extensions/markdown-language-features/preview-src/tsconfig.json#L5

It should use the shared one like everyone else.

**Comment by mjbvz** [comment]
That tsconfig is for the markdown webview content, not the extension, but there's probably no harm in extended the base tsconfig
