### ISSUE TITLE
Duplication of file search results

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#80123]
Issue Type: <b>Bug</b>

1. All extensions disabled, empty settings file, no working changes
2. Use file search

![Screen Shot 2019-08-30 at 10 13 17 AM](https://user-images.githubusercontent.com/3672607/64039384-599e3800-cb0f-11e9-8aa5-3c357e2b79f7.png)

The `pullRequestNode.ts` file appears 4 times, some other results are duplicated, others appear only once.

VS Code version: Code - Insiders 1.38.0-insider (20dd80d91a76cbe80fb1d1979c3a9f02d94ba161, 2019-08-29T14:02:52.867Z)
OS version: Darwin x64 18.7.0

**Comment by roblourens** [comment]
Seems that these entries were left over from the PR extension which used to set a `path` on URIs but doesn't anymore
