### ISSUE TITLE
Ctrl+Shift+M doesn't toggle Problems panel

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8012]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

Steps to Reproduce:

1. On Windows, Ctrl+Shift+M displays the Problems panel.
2. Pressing Ctrl+Shift+M a second time does not close the panel

All other panels (Output, Debug Console and Integrated Terminal) toggle visibility with their keyboard shortcuts.  We should be consistent.  Problems shouldn't be the only panel that requires another keyboard shortcut to toggle visibility (Toggel Panel Ctrl+J).

**Comment by sandy081** [comment]
@gregvanl This is an ongoing discussion in #7540. Hence closing this and request to continue the discussion there.

**Comment by gregvanl** [comment]
Last comment in #7540 indicates that the Problems panel should behave the same as the other panels. Reopening since Ctrl+Shift+M still does not toggle visibility like other panels (Output, Debug Console, Terminal).

**Comment by sandy081** [comment]
On the latest insiders build, on windows, I see Ctrl + Shift + M is toggling the visibility.

@gregvanl Can you please check again and reopen if it is not.
