### ISSUE TITLE
Save not working (MAC)

### ISSUE THREAD

**Issue by andrewsipe** [microsoft/vscode#80120]
Workspace: desktop folder + HTML File
Changes are not saving via shortcut (Command + S), or any of the menu saving options (Save, Save As, Save All).

I can create new files, copy & paste content and they will save, but only once. Any subsequent changes to the file will not save.

I have attempted to download and reinstall VSCode, but there were no apparent changes. I have not added any new extensions in the past 24 hours. In fact, saving was functional yesterday, but has not been functional today.

OS: macOS Mojave 10.14.6
VSCode: Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by weinand** [comment]
@andrewsipe please try whether rebooting your macOS helps...

**Comment by andrewsipe** [comment]
I had not attempted the tried and true "Have you tried turning it off and on again?" method. facepalm.gif

Shutting the machine down and then restarting it, worked. 

Not sure what had conspired between the previous session and the session that caused my distress, but this solved things. Thank you.
