### ISSUE TITLE
if I provide two $0 in snippest, I want to auto select the text between its when I tab the finally tab key.

### ISSUE THREAD

**Issue by CharlieCheng2014** [microsoft/vscode#80139]
if provide two $0 in snippest, I want to auto select the text between its.

**Comment by davalapar** [comment]
Provide more context, please?

**Comment by jrieken** [comment]
The `$0` tabstop is the final tab stop (as defined by TextMate) and there is little chance that we change that. What is your use-case exactly?

**Comment by CharlieCheng2014** [comment]
for example , when i type two $0 below in snippest:


	"...": {
		"prefix": "...",
		"body": [
			"$0",
            "blablabla.....",
			"$0",
		],
		"description": "......"
	}

when i do finally tap, i want auto select the text between two $0, like blablabla.....,

my use case is :

when i type a function in cpp, i want auto generate the function decalration below my function.
when i type the finally tap, i want just use Command+X to cut the function decalration and put it somewhere i want.

void function()
{
    ....
}

`$0`void function();`$0`

**Comment by jrieken** [comment]
Yeah, that's not how snippets work (and it's not use defining how they work). What you can do, is to use a non-final placeholder, like `${1:blalalalala}`, which select a portion of text.
