### ISSUE TITLE
Ctrl+T does not list exported variables

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#8013]
Ctrl+T the project wide symbols listing can't find exported globals e.g.

```
export let globalStyles = {};
```

It's visible in file wide symbols listing Ctrl+Shift+O, but not in the project wide symbol listing Ctrl+T.

**Comment by dbaeumer** [comment]
@Ciantic do you have a tsconfig.json / jsconfig.json file ? If so how does it look like and is the file exporting the globalStyles part of the project

**Comment by Ciantic** [comment]
@dbaeumer here is gist you can clone: https://gist.github.com/Ciantic/50140f189abf3e83260e6aba7cedc5ce

Clone that, open the folder in VS Code insiders, open the "openthis.ts", hit Ctrl+T and start typing "globalStyles", nothing is found. But it finds "Something" just fine.

**Comment by dbaeumer** [comment]
This gets filtered in the UI. We should remove that filtering code.

**Comment by bpasero** [comment]
@dbaeumer @jrieken -1 on this change, for me Cmd+P and Cmd+T are now quite unusable because for example all imports are showing up as results:

![image](https://cloud.githubusercontent.com/assets/900690/16369623/3c256f22-3c39-11e6-8fa1-09929bfc1259.png)

At the very minimum, please restore how Cmd+P was working (use the filter only when the symbol handler is being used from the `openAnythingHandler.ts`.

**Comment by jrieken** [comment]
Not filtering in the UI is still the right thing to do. Leaving it up to @dbaeumer to teach TypeScript to exclude some items

**Comment by dbaeumer** [comment]
IMO the last 'component' that should do any filtering is the language server / service. The service is asked to provide all workspace symbols the service should exactly return that.

In the example @bpasero shows most of the errors are properties on interfaces. So I think we need different ways to show/ filter that view: by type (only classes, ....) and by scope (top level, nested).

This requires work in the UI and in the API. What do you think?

**Comment by jrieken** [comment]
@dbaeumer I actually think that its imports like `import * as errors from '...'` and in that case I would argue the usefulness

👍 for addition grouping - as in quick outline. The information should be available since both provider return arrays of `SymbolInformation`

**Comment by Ciantic** [comment]
I also get stuff that I have imported e.g. I use globalStyles a lot, and it lists these as symbols:

`import globalStyles from "../GlobalStyles";`

I think import lines (which are not re-exports) should not be listed in the symbols listing.

**Comment by dbaeumer** [comment]
@bpasero and I discussed it an neither filtering in the UI nor filtering in the model is the right solution. So we decided to have Ctrl+T list all workspace symbol and Ctrl+P only the global once. We will therefore add the container name to the symbol and check if this allows for proper filtering. I opened  https://github.com/Microsoft/vscode/issues/8502 to track the UI changes.

**Comment by dbaeumer** [comment]
@bpasero The container name is already part of the SymbolInformation. Will close this one now and see how the UI behaves after addressing #8502

**Comment by bpasero** [comment]
@dbaeumer sorry, but the imports are showing up without containerName so they still appear in CtrlCmd+P.
