### ISSUE TITLE
Progressively slower VSCode with newer versions

### ISSUE THREAD

**Issue by KeyC0de** [microsoft/vscode#80148]
Just giving feedback on the program. I didn't know where else to put it.

Visual Studio Code is getting progressively slower with the newer updates to favor "looks".

I had 1.26.1 version for a long time. I recently upgraded to 1.37.1 and noticed it required x3 to open, double the time to open terminal, less responsiveness overall slowdown. And for what, better looking interface? I don't like it. The most important issue though for me was the significantly lagging terminal window, which I constantly use. I thought it was an extension causing it, but no I couldn't find the culprit. So now I'm back to 1.26.1 and I'm not changing for the foreseeable future. I'd much rather have a fast program than a cool-looking program.

I didn't notice this issue just with 1.37.1 but with a couple of other previous versions I installed along the way (I don't remember version ids). I have a powerful PC RTX 2080, i7 3770, 16GB Ram Windows 8.1 AMD64 perfectly maintained. There can be no reasons for slowdown on my part.

**Comment by jrieken** [comment]
I don't the that's a general observation. The chart below is the time is takes to restore a window with an editor and a terminal. There is a repeating monthly pattern and an overall downwards trend.

<img width="1061" alt="Screenshot 2019-09-02 at 10 32 52" src="https://user-images.githubusercontent.com/1794099/64100955-07f2e900-cd6d-11e9-9bd0-6897558422a0.png">

> noticed it required x3 to open, double the time to open terminal, less responsiveness overall slowdown. And for what, better looking interface? I don't like it

Show me the numbers! This guide tells you how: https://github.com/microsoft/vscode/wiki/Performance-Issues
