### ISSUE TITLE
I want snippest macro CLIPBOARD can provide more than one history clipboard.

### ISSUE THREAD

**Issue by CharlieCheng2014** [microsoft/vscode#80140]
I want snippest macro CLIPBOARD can provide more than one history clipboard.

**Comment by jrieken** [comment]
/needsMoreInfo

Don't understand what you mean. Please clarify and include a sample

**Comment by CharlieCheng2014** [comment]
for example , when i use CLIPBOARD  with a number 2 in snippest:


	"...": {
		"prefix": "...",
		"body": [
            "blablabla.....",
            ${CLIPBOARD} // the recently clipboard history text.
            ${CLIPBOARD:2} // the second recently clipboard  history text.
            "blablabla.....",
		],
		"description": "......"
	}

i want it auto replace by my second clipboard history text.

**Comment by jrieken** [comment]
This is a cool idea but too far out. There is no support in browser/electron APIs to retrieve N-1 items from the clipboard and it's very unlikely that we implement this (and won't ever be able to get this correct) in the next 3-6 months
