### ISSUE TITLE
VSCode holds *.asar file locked though I've even did not open it in editor, which leads to "The process cannot access the file because it is being used by another process."

### ISSUE THREAD

**Issue by ivictbor** [microsoft/vscode#80146]
- VSCode Version: 1.37.1 
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open sources of app app which includes *.asar resources with electron-builder
2. Run `npm run build` 
3. build fails `win-unpacked\resources\app.asar: The process cannot access the file because it is being used by another process.`
4. Process explorer shows that is holder by vscode

![image](https://user-images.githubusercontent.com/1838656/64060660-d812dc80-cbd8-11e9-999d-5da2aecb80bd.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes, tried `code --disable-extensions`, Open Folder.

**Comment by ivictbor** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/62518#issue-377059000 , but that one was not fixed

**Comment by bpasero** [comment]
@ivictbor in that screenshot, what is the full command line of the Code process that locks the asar file? Trying to understand which of our processes this is.

**Comment by ivictbor** [comment]
@bpasero thanks for reply, here how it looks, though it has no `code --disable-extensions`, maybe reason in that fact I used file -> open recent and it restarted vscode with extensions again

![image](https://user-images.githubusercontent.com/1838656/64104222-83a86200-cd7c-11e9-8364-fca5fdc9db04.png)

**Comment by bpasero** [comment]
@dbaeumer looking at it this seems to be a language server. Didn't you recently push a change there to disable asar support?

**Comment by dbaeumer** [comment]
This got fixed in the LSP libraries lately. I think it got introduced when @alexandrudima added asar support to the extension host and removed the env when starting it. Commit is https://github.com/microsoft/vscode-languageserver-node/commit/1e7962e4b6484c66e784af1c9fc343a630872db0

**Comment by octref** [comment]
@dbaeumer Is there a new version I can adopt?

**Comment by dbaeumer** [comment]
No, will come out this week.
