### ISSUE TITLE
Terminal I want to add a new add control of optional command type to the upper right corner of the window next to the add sider

### ISSUE THREAD

**Issue by microestc** [microsoft/vscode#80141]
Terminal to the default command to add a new terminal window, my default setting is PWSH, for example, when I want to add a new terminal using CMD. exe, I have to reset the select the default shell and then click on add, these operations to a large extent is not very convenient, so that I want is to Windows terminal perview, the add button sider add an optional drop-down button that I can choose the command type I want and click to create the command mode I want, one step in place.
thanks.

**Comment by microestc** [comment]
I know what you're talking about, by setting the default shell, but why not do it ina better way, a one-step solution like Windows terminal

**Comment by Tyriar** [comment]
@microestc that's what https://github.com/microsoft/vscode/issues/79313 is all about

**Comment by microestc** [comment]
ok.i see.  the shell launcher is enable to easily launch multiple shell

**Comment by microestc** [comment]
but,I prefer to add a shortcut command in the terminal window interface. If I am using shell launcher extension and shortcut keys, why don't I use the method of select default shell to add different shells, which is not as complicated as the shortcut key

**Comment by microestc** [comment]
ok, I'm just making a suggestion, and if it doesn't have much value, you can ignore it.
thanks

**Comment by Tyriar** [comment]
@microestc I'm pretty sure you're asking for exactly what #79313 will be.
