### ISSUE TITLE
Heavy CPU Usage 

### ISSUE THREAD

**Issue by Mamatha9591** [microsoft/vscode#80144]
Issue Type: <b>Bug</b>

CPU usage is so high and even all by sudden it crash's pc perfomance.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|2.2.2

</details>

**Comment by Mamatha9591** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [High CPU usage (#74992)](https://www.github.com/microsoft/vscode/issues/74992)
> * [High CPU usage in ubuntu16.04 (#26702)](https://www.github.com/microsoft/vscode/issues/26702)
> * [CPU usage is high when scrolling (#77051)](https://www.github.com/microsoft/vscode/issues/77051)

i have checked issues but that doesn't worked out.

**Comment by weinand** [comment]
/needsMoreInfo

Please follow the steps in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by weinand** [comment]
And please follow the steps in https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
