### ISSUE TITLE
Module typing don't get picked up before I open it in editor manually.

### ISSUE THREAD

**Issue by amit-gshe** [microsoft/vscode#80147]
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Clone the [sample project](https://github.com/amit-gshe/ts-auto-import-test).
2. `npm install`
3. Open the index.ts, and the Intellisense won't get typings picked up.
4. Find the index.d.ts from the node_modules and open it in another tab.
5. Back to the index.ts and the auto import get working.

Does this issue occur when all extensions are disabled?: Yes

![issue](https://user-images.githubusercontent.com/7383028/64061784-c699f680-cc11-11e9-8c89-0d2254735b19.gif)

**Comment by mjbvz** [comment]
This is a configuration issue. VS Code will not automatically try loading all globals from node modules as this would be very noisy

As a first step, try creating a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson)
