### ISSUE TITLE
Start vscode too slowly

### ISSUE THREAD

**Issue by wisheen** [microsoft/vscode#80142]
Issue Type: <b>Performance Issue</b>

I use vscode develop java and nodejs,  nodejs project has many files，when start vscode， java language server search nodejs project，Can I set a blanklist to tell java language server not checking?

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
You can disable the Java extension for workspaces that don't use Java.

**Comment by weinand** [comment]
Please file issue against Java extension
