### ISSUE TITLE
VSCode1.37.1  win 10 os  auto save problem 

### ISSUE THREAD

**Issue by Abdulali97** [microsoft/vscode#80152]
- VSCode Version: 1.37.1
- OS Version: windows 10 64x 1903

 I faced this problem when I enable autosave
 it's directly moving the pointer to end of the page
 and I see the color boxes when writing
and ican't use undo etc...
 see the video to  more understand 

https://youtu.be/PA0Qhvcc2KE

Does this issue occur when all extensions are disabled?:   >>>Yes<<<

**Comment by weinand** [comment]
Please start VS Code from a command prompt with "--disable-extensions" option.
Does the problem still occur?

**Comment by Abdulali97** [comment]
no, it's work without problem 👍👍

**Comment by Abdulali97** [comment]
hey 
I found the extensions that made the problem  
https://ibb.co/m92RqJ7

**Comment by weinand** [comment]
Great, then please file a bug against that extension!
