### ISSUE TITLE
ECONNREFUSED - lsp-multi-server-sample

### ISSUE THREAD

**Issue by Dollmminode** [microsoft/vscode#80156]
OS: macOS Mojave
Node Version: 10.16.3
code version: 1.37.1

I wanted to test the lsp-multi-server-sample from the vscode-extension-samples. I can build it without problems, but running any of the "attach to Server" commands will lead to:

"Cannot connect to the runtime process, timeout after 10000ms - (reason: Cannot connect to the target: connect ECONNREFUSED localhost:port)"

I did not change any of the files. And before building it I ran "npm install". 

Do you have any idea where the problem might be?

**Comment by weinand** [comment]
@dbaeumer after starting the client and opening a plain text file I can successfully attach to "Server 6011" but not to the other servers.
What is the expected behavior?
The Readme doesn't mention anything related to multiple servers.

**Comment by dbaeumer** [comment]
The server is started by counting up the port. The first server gets 6011, the second 6012, ... Code is `let debugOptions = { execArgv: ["--nolazy", `--inspect=${6011 + clients.size}`] };`

Unfortunately the example has a lucnh config that tries to connect to 6010. I will delete that one. @weinand it is OK for me to close.

**Comment by weinand** [comment]
@dbaeumer thanks for the clarification. 
Assigned issue to you.

**Comment by dbaeumer** [comment]
Closing the issue. I removed the broken launch config.
