### ISSUE TITLE
Poor Markdown list syntax highlighting

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8015]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 10

Steps to Reproduce:

1. Create a simple Markdown file with a list:
```Markdown
# Hello World
Here is a list:
* item 1
* item 2
```
2. Notice that the text "item 1", "item 2" is blue like the list asterisk.  It should be colored like text.

This is a regression from 1.2.1-stable.

**Comment by gregvanl** [comment]
![markdownlisthighlighing](https://cloud.githubusercontent.com/assets/12818376/16278406/bb915a7c-386b-11e6-8e50-ef0aa4d6cf03.png)

**Comment by gregvanl** [comment]
Indented text also has this issue:
```
> Hello
```

**Comment by kieferrm** [comment]
Changes were made to the dark theme and the dark+ theme. The dark theme only colors the lists bullet `*` and the quote indicator `>` while dark+ colors the complete list and the complete quote.

**Comment by gerane** [comment]
Every other theme is still broken
