### ISSUE TITLE
Vscode unauthorized compiling the code unde win10 os

### ISSUE THREAD

**Issue by Telazone** [microsoft/vscode#80151]
- VSCode Version: 1.37.1
- OS Version: win10

Steps to Reproduce:

1. I'm currently using vscode under win10 os running my angular 8 project. When I use the angular cli command ng serve --open to start the project, at the first like half an hour or one hour, it runs normally, but after that, the vscode will automatically compile the code without any changes saving. Sometimes it will run only once or twice, will take like around 10 sec, but sometimes, it get insane, it will compile the code like 7 times, and every time it will take a really long time like around 10 sec.
2. I tried to find some root cause or solution on google, but not helping. Do you have any idea on how to solve this? Thanks in advance.
Following is several snapshots when it automatically compile the code unauthorized:

**_Snapshot 1:_**
Date: 2019-08-31T12:37:37.946Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 12327ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 68% building 565/576 modules 11 active ...create-account\create-account.component.scssi ｢wdm｣: wait until bundle finished: /profile-em/24/resume

Date: 2019-08-31T12:38:09.009Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 29213ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /polyfills.js
i ｢wdm｣: wait until bundle finished: /styles.js

Date: 2019-08-31T12:38:14.497Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 5085ms
i ｢wdm｣: Compiled successfully.

**_Snapshot 2:_**
Date: 2019-08-31T12:33:16.407Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 11348ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /profile-em/24/resume

Date: 2019-08-31T12:33:28.507Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 11498ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /polyfills.js
i ｢wdm｣: wait until bundle finished: /styles.js
i ｢wdm｣: wait until bundle finished: /vendor.js
i ｢wdm｣: wait until bundle finished: /main.js

Date: 2019-08-31T12:33:38.244Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 9239ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js.map
i ｢wdm｣: wait until bundle finished: /polyfills.js.map
i ｢wdm｣: wait until bundle finished: /scripts.js
i ｢wdm｣: wait until bundle finished: /styles.js.map
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /vendor.js.map
i ｢wdm｣: wait until bundle finished: /main.js.map

Date: 2019-08-31T12:33:48.079Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 8827ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /assets/fonts/REX_icons.ttf?mffa75
i ｢wdm｣: wait until bundle finished: /assets/fonts/Linotype-ITC-Charter-Com-Black-Italic.ttf
i ｢wdm｣: wait until bundle finished: /assets/fonts/glyphicons-halflings-regular.woff2
i ｢wdm｣: wait until bundle finished: /assets/images/pwc-logo.png
i ｢wdm｣: wait until bundle finished: /assets/images/Notification_Icon_Bell.png
i ｢wdm｣: wait until bundle finished: /assets/images/photos/default.png

Date: 2019-08-31T12:34:08.586Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 19545ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /profile-em/24/resume
i ｢wdm｣: wait until bundle finished: /assets/i18n/en.json
i ｢wdm｣: wait until bundle finished: /scripts.js.map
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /app-routes-home-home-module.js

Date: 2019-08-31T12:34:17.381Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 8148ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /assets/i18n/en.json
i ｢wdm｣: wait until bundle finished: /runtime.js
i ｢wdm｣: wait until bundle finished: /polyfills.js
i ｢wdm｣: wait until bundle finished: /styles.js
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /vendor.js
i ｢wdm｣: wait until bundle finished: /main.js

Date: 2019-08-31T12:34:31.304Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 13302ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js.map
i ｢wdm｣: wait until bundle finished: /scripts.js
i ｢wdm｣: wait until bundle finished: /polyfills.js.map
i ｢wdm｣: wait until bundle finished: /styles.js.map
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /main.js.map
i ｢wdm｣: wait until bundle finished: /vendor.js.map

Date: 2019-08-31T12:34:37.792Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 5986ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-08-31T12:35:25.485Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 7138ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /profile-em/24/resume

Date: 2019-08-31T12:35:33.725Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 7794ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js
i ｢wdm｣: wait until bundle finished: /polyfills.js
i ｢wdm｣: wait until bundle finished: /styles.js
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /vendor.js
i ｢wdm｣: wait until bundle finished: /main.js

Date: 2019-08-31T12:35:41.982Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 7815ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: wait until bundle finished: /runtime.js.map
i ｢wdm｣: wait until bundle finished: /polyfills.js.map
i ｢wdm｣: wait until bundle finished: /scripts.js
i ｢wdm｣: wait until bundle finished: /styles.js.map
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /vendor.js.map
i ｢wdm｣: wait until bundle finished: /main.js.map

Date: 2019-08-31T12:35:49.144Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 6470ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-08-31T12:35:58.023Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 8211ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 95% emitting CopyPlugini ｢wdm｣: wait until bundle finished: /main.js.map

Date: 2019-08-31T12:36:26.231Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 8046ms
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

Date: 2019-08-31T12:36:45.065Z - Hash: fa144bd4f6e3525c72e3
40 unchanged chunks

Time: 18284ms
i ｢wdm｣: Compiled successfully.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
The compiling is sone in `ng serve` which is not part of VS Code.
