### ISSUE TITLE
Option to go to files filter when tabbing from the find search bar

### ISSUE THREAD

**Issue by Charuru** [microsoft/vscode#80159]
When I'm using find in file and after I finish typing the search query I typically want to filter by file type. If I press tab it automatically goes to match case, match whole words and regex options first, and only on the 4th tab ends up in files to include. Any way to make it go straight to files to include on the first tab?

Similar to #8225 but I'm just asking for an option.

**Comment by roblourens** [comment]
We can't change the tab order but you can use the ctrl/cmd+up/down bindings to easily switch between input boxes.
