### ISSUE TITLE
Squiggly red lines

### ISSUE THREAD

**Issue by JasonMG747** [microsoft/vscode#80164]
Issue Type: <b>Performance Issue</b>

I have squiggly red lines under all my code, even in areas where there is no code written. I have no extensions installed. Cannot fix it!

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
Please provide a screenshot
