### ISSUE TITLE
Cannot use variables in .code-workspace files

### ISSUE THREAD

**Issue by slavdok** [microsoft/vscode#80168]
- VSCode Version: 1.37.1
- OS Version: Windows 10 (10.0.18362)

Does this issue occur when all extensions are disabled?: Yes

I am trying to make my `.code-workspace` file agnostic of the PC on which I open it. I wanted to use `%USERPROFILE%\.ssh` that should resolve to `C:\Users\myusername\.ssh`, but it doesn't work. 
VSCode says `%USERPROFILE%\.ssh - Can not resolve workspace folder`

I tried using `${env:USERPROFILE}` as described [here ](https://code.visualstudio.com/docs/editor/variables-reference)
I tried lower case, tried upper case.
I tried escaping `\%`
I tried other variable names that would have a single value (rather than path), like `${env:USERNAME}`

Nothing seems to work

**Comment by weinand** [comment]
Variables are just not supported in workspace files.

**Comment by slavdok** [comment]
> Variables are just not supported in workspace files.

Is there a way to change this to a feature request then?
