### ISSUE TITLE
Context menu keyboard shortcut rendered strangely

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80160]
![image](https://user-images.githubusercontent.com/323878/64069094-7d3cad80-cbf7-11e9-8e9c-ac7e66f53804.png)

This is cmd+shift+1. If you hover the "replace" icon on the row, it's rendered as I would expect with 3 symbols. Technically this isn't wrong but...

**Comment by rebornix** [comment]
IMO it's how macOS context menu works as what we pass to`accelerator` is `shift+cmd+1`

https://github.com/microsoft/vscode/blob/730f47da21d26733734b9d3d1d361638379d9404/src/vs/workbench/services/contextmenu/electron-browser/contextmenuService.ts#L161-L162
