### ISSUE TITLE
Desktop veiwing options.

### ISSUE THREAD

**Issue by cirobruno** [microsoft/vscode#80166]
Issue Type: <b>Feature Request</b>

Dear sirs
Unfortunatelly, I've got quite hard difficulties for seeing. In VS Code I haven't found any way to change desktop colors and font size. That's turning it almost impossible to read. I need to open magnifying window all the time.
Please, let me choose background color and font size, not only for code editing. I simply can't see what to do!
Thank you.
Regards,
Ciro.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 17.7.0

**Comment by isidorn** [comment]
Hi Ciro,

You can try-out a couple of things:
1. View > Appeareance > Zoom In / Out
2. Change the following settings 	`"editor.fontSize"`
3. F1 > Prefererences: Color Theme and you can choose the theme which suits you best.

Cheers
