### ISSUE TITLE
Improve search keyboard navigation

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#80175]
I'm trying to achieve smooth, keyboard-only, navigation and editing, of search results, in the following scenario:

1. Search for something
1. Use keyboard shortcuts to navigate through the search results items
1. Press `enter` to start editing one of the search results
1. Make an edit in the file
1. Press shortcut to go back to the search result list and navigate through search results, until you find another file to edit
1. Repeat from step 3

Here is an example of what it looks like, as long as you don't make edits to the files:

![2019-09-01 13 57 00](https://user-images.githubusercontent.com/208149/64076104-93fb0700-ccc0-11e9-983c-b4a5c4fb0711.gif)

This flow works fine as long as long as you don't edit the files. If that happens, sometimes the search result item is removed from the list of results, or it just loses focus, which means that when focusing back on the list of search results, using a keyboard shortcut, the position in the list is lost. Like this:

![2019-09-01 14 00 02](https://user-images.githubusercontent.com/208149/64076127-010e9c80-ccc1-11e9-85a5-8f0ebfc6f2d6.gif)

I'm not sure what is the best way to fix this, but perhaps:
When focus is set back on the list, but the previously selected item has been removed, focus is set on the entire list, like happens currently. However when restarting up/down navigation, navigation should start from the item above or below the previously selected (now removed) item, instead of starting from the top of the list.

This kind of flow is one of the things I still miss, coming from Sublime Text.

------------ 

```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by roblourens** [comment]
Yeah, this is https://github.com/microsoft/vscode/issues/20467

**Comment by franciscolourenco** [comment]
Searched but didn't find, thanks.
