### ISSUE TITLE
Cannot import modules

### ISSUE THREAD

**Issue by pyuser00** [microsoft/vscode#80176]
I get the following error in VScode no matter which interpreter I select:

"Exception has occurred: ImportError
DLL load failed: The specified module could not be found."

Code runs fine in Anaconda/Spyder and consoles, just not VScode. I have the question out for over a week on StackOverflow and no one can answer, so I think it is a bug and not a question.

**Comment by pyuser00** [comment]
VScode v1.37.1 with Anaconda v3.7.3. From VScode, I open the folder containing the source and I have a entry in the settings.json to point to an additional path  like "env": {"PYTHONPATH": "C:\\Users\\..."},

**Comment by weinand** [comment]
@pyuser00 You've seen this?
https://stackoverflow.com/questions/43351596/activating-anaconda-environment-in-vscode

If you have troubles with this please ask on stackoverflow and/or file issues against the Python extension. VS Code by itself does not have Python built-in, so filing Python related issues here doesn't result in helpful answers.

**Comment by pyuser00** [comment]
That did not help... this is just too hard for someone that wants to write basic python scripts. Other environments see various python installs and just link to them without all these extensions and .json edits, so staying with the Python paradigm, I'd prefer to keep it simple.

**Comment by weinand** [comment]
And VS Code's Python tutorial didn't help either?
https://code.visualstudio.com/docs/python/python-tutorial

**Comment by pyuser00** [comment]
No. Others are suggesting modifying my PATH to point to Anaconda, but that does not work either. I have 4 different machines with VScode installed and only 2 of them link to Python correctly. The configurations appear identical to me except for the settings.json points to a different path. Working Anaconda points to either "C:\Anaconda\..." or have a blank settings.json while non-working installs point to a localized directory "%LOCALAPPDATA%\Continuum\anaconda3\..." .

**Comment by weinand** [comment]
Great that your were able to find the problem. Thanks.
