### ISSUE TITLE
serverReadyAction debugWithEdge (chromium) missing

### ISSUE THREAD

**Issue by damianog** [microsoft/vscode#80177]
I tried the new serverReadyAction to start debugging a "dotnet core + angular SPA" but with the parameter "action": "openExternally" I did not find a way to debug angular typesctipt's code till I used these settings:

"action": "debugWithChrome",
"webRoot": "${workspaceFolder}/ClientApp"

![image](https://user-images.githubusercontent.com/2786682/64078085-e47d5f00-ccd6-11e9-9d19-221231ab4b53.png)

and I need to install Chrome again.

Please add full support to debug with Edge Chromium

**Comment by weinand** [comment]
The action `"openExternally"` uses whatever browser is installed as the default browser.

**Comment by damianog** [comment]
I know but as I told, with "openExtermally" typescript debugging do not intercept beackpoints, only dotnet, am I missing any other parameter?  

![image](https://user-images.githubusercontent.com/2786682/64169727-b15ddb80-ce4e-11e9-96ff-be96f04664e1.png)

as you see webRoot is marked as not allowed

**Comment by weinand** [comment]
Yes, "openExtermally" does not start a debug session.
It was not clear from your initial comment whether you wanted to debug in the browser or only open the browser.

**Comment by aimengda** [comment]
any update on this request?
