### ISSUE TITLE
SASS/SCSS helping particle support

### ISSUE THREAD

**Issue by LiquidSolid** [microsoft/vscode#80172]
I don't see color helpers in *.sass/*.scss files, i don't see any helpers (colors, hints) for sass/css style parts in Vue single-file components:

![image](https://user-images.githubusercontent.com/43530070/64074674-2eeee380-ccb7-11e9-9558-e01c6c008ef6.png)
![image](https://user-images.githubusercontent.com/43530070/64074737-f1d72100-ccb7-11e9-93cb-62cd85e30f51.png)
![image](https://user-images.githubusercontent.com/43530070/64074723-ceac7180-ccb7-11e9-9b1d-cb1e543294e2.png)

Sorry for my bad english and bad feature description, but i think that you will understand me. Thanks.

**Comment by annoying258** [comment]
what is a color helper?

**Comment by LiquidSolid** [comment]
![image](https://user-images.githubusercontent.com/43530070/64076123-3c14ce00-ccc9-11e9-8266-7662aa2a53f6.png)

**Comment by weinand** [comment]
Are you using a Vue extension for VS Code when editing a "Vue single-file components"?

**Comment by LiquidSolid** [comment]
Yep
![image](https://user-images.githubusercontent.com/43530070/64077665-290af980-ccdb-11e9-85f4-8f1d0d9dfe2b.png)

**Comment by LiquidSolid** [comment]
Sorry, but it not fully caused by extension. Note, that color helper not working in individual *.sass files which not related to Vue.

**Comment by weinand** [comment]
VS Code does not support *.sass out of the box.

**Comment by LiquidSolid** [comment]
OK, thank you.

**Comment by annoying258** [comment]
from https://github.com/microsoft/vscode/issues/80172#issuecomment-526912955

so that's what its called. I always wonder why its present at all, I don't use it much, I like https://htmlcolorcodes.com/

----

> VS Code does not support *.sass out of the box.

is it the same for .scss files? or any other file extension that qualifies as a sass file?
Also, this may need correction https://code.visualstudio.com/docs/languages/css
