### ISSUE TITLE
cursor position incorrect

### ISSUE THREAD

**Issue by NanerLee** [microsoft/vscode#80170]
- VSCode Version: 1.37.1
- OS Version: ubuntu lts 18.04.3

Steps to Reproduce:

>  Set  `"editor.renderWhitespace": "all"` for watching easily

1.  open a  new file
2.  press `space` key
![1](https://user-images.githubusercontent.com/16791509/64072310-ee936380-ccbe-11e9-9897-70f2c3625489.png)
3.  press `space` key
![2](https://user-images.githubusercontent.com/16791509/64072311-f2bf8100-ccbe-11e9-8db6-0a77e3f8cbd4.png)
4.  press `space` key
![3](https://user-images.githubusercontent.com/16791509/64072408-42527c80-ccc0-11e9-86d5-274ab6ee400f.png)
5.  press `space` key
![4](https://user-images.githubusercontent.com/16791509/64072313-01a63380-ccbf-11e9-9677-60160df393f3.png)

we can find the cursor position is incorrect

More info:
1. I has three PCs, their are all ubuntu 18.04.3, but only one is normal.
2. The bug may be not about vscode version. I tried some old version , the bug is still.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Workaround: `"editor.disableMonospaceOptimizations": true`

**Comment by NanerLee** [comment]
@alexandrudima it doesn't work. And vscode tell me it is `Unknown configuration setting`
![2019-09-08 11-26-45 的屏幕截图](https://user-images.githubusercontent.com/16791509/64482871-2b65da00-d22c-11e9-8084-0d8990d50943.png)

**Comment by Talden** [comment]
Can confirm the same bug on VS Code: 1.37.1 (from Microsofts repo) with Debian Stretch.

Sometimes the editor starts fine, sometimes not. But even successful starts can fail calculating metrics (maybe a font loading race).

**Comment by kaseiwang** [comment]
> Workaround: `"editor.disableMonospaceOptimizations": true`

works on code(1.38.0-1) from archlinux/[community], thanks!

**Comment by Talden** [comment]
> > Workaround: `"editor.disableMonospaceOptimizations": true`
> 
> works on code(1.38.0-1) from archlinux/[community], thanks!

Is it expected that the setting is reported as "Unknown Configuration Setting"? This is the case for this version (which isn't impacted by the defect):

> Version: 1.38.0 (user setup)
> Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
> Date: 2019-09-03T21:49:13.459Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

**Comment by alexandrudima** [comment]
Yes, currently this setting is for troubleshooting only, so it is normal for `"editor.disableMonospaceOptimizations"` to be unknown. In a perfect world the monospace optimizations should work and we wouldn't need this setting to turn it off. That's why I marked this as a bug as something is definitely no longer working...

**Comment by Rock718** [comment]
Change vscode default fonts maybe useful.See #80210

**Comment by NanerLee** [comment]
@Rock718  Thanks a lot, I change the default fonts to `Noto Mono`, it works!. And 
  `editor.disableMonospaceOptimizations` is not necessary
