### ISSUE TITLE
symbol java visual studio code

### ISSUE THREAD

**Issue by Rypleyx** [microsoft/vscode#80171]
Good morning 

I have followed the visual studio code installation, and even several times, deleting configuration folders. but even so I get this error message and also when I create a java file, the java symbol does not appear, I use Windows10 and I have installed JDK with the JAVA_HOME and path environment variables, I need help, 

visual studio
[https://ibb.co/NtQfk31](url)
environment
[https://ibb.co/SvWZC1r](url)
file java
[https://ibb.co/cQfnH0w](url)

**thanks.**

**Comment by weinand** [comment]
Do you have the Java extension installed?

**Comment by Rypleyx** [comment]
Yes

**Comment by weinand** [comment]
What java extension is this? Please provide the exact name.

**Comment by Rypleyx** [comment]
I think it's some kind of problem but I don't know which one might have something to do with "language support for java (TM) by Red Hat, I don't know ...
I attached you captures:
[https://ibb.co/D1BqXmP](url)
[https://ibb.co/nMR1m1L](url)

**Comment by weinand** [comment]
@Rypleyx Please file the issue here: https://github.com/redhat-developer/vscode-java/issues

**Comment by weinand** [comment]
@Rypleyx FYI: you can paste images (*.jpg, *.gif) directly into github. There is no need to store them outside. All your "https://ibb.co/*" links from above don't work for me because they are blocked by github/Microsoft.

**Comment by Rypleyx** [comment]
weinand thank you, https://github.com/Rypleyx/images/blob/master/README.md

**Comment by weinand** [comment]
@Rypleyx I meant: you can paste the images into these comments like this:

![64102867-1d6a1200-cd71-11e9-8f01-0797f48f054e](https://user-images.githubusercontent.com/1898161/64118673-65505f80-cd98-11e9-9a40-5a99b1fe9f2f.png)

There is no need to create a repository for your images.

Did you actually create your original issue in the [Java repository](https://github.com/redhat-developer/vscode-java/issues)?

**Comment by Rypleyx** [comment]
yes https://github.com/redhat-developer/vscode-java/issues/1049
