### ISSUE TITLE
COMMAND

### ISSUE THREAD

**Issue by shaw12** [microsoft/vscode#80173]
Issue Type: <b>Bug</b>

when i write html commands and after press enter i am not gettimg the commamnd with closing.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by annoying258** [comment]
do you mean that you are not getting the command with closing tags?

**Comment by shaw12** [comment]
In Vscode , for eg: if you write "div"/"html"/ other command then hit enter
.... Then you'll get ... Like this:<Div></div>.

But I am getting this type tags from hitting enter .

**Comment by weinand** [comment]
Sorry, but I don't understand what you mean.

**Comment by annoying258** [comment]
> if you write "div"/"html"/ other command then hit enter .... Then you'll get ... Like this:<Div></div>

got it. you can call it `html tag completion`, or `tag completion` or whatever you like. so now i know what's `expected to happen`. 

> getting this type tags

what type tags? any examples? my guess is you're getting something like
```
<div>

<div>
```
instead of `<div>
<\div>` when you press Enter.

---

side note, you can use markdown to format comments and include code. it makes it easy to paste and copy code, screenshots. here are some links if you are interested
https://guides.github.com/features/mastering-markdown/

**Comment by shaw12** [comment]
For example:When I press enter after entering- div, I get div only

instead of <div> <\div>

**Comment by annoying258** [comment]
I understood that part, but got  confused by this line.

>But I am getting this type tags from hitting enter .

Try disabling all installed extensions in vscode and see if it works.

---

these pages has a visual for how its supposed to work.
https://code.visualstudio.com/docs/editor/emmet
https://docs.emmet.io/

 emmet syntax
https://docs.emmet.io/abbreviations/syntax/

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/languages/html#_intellisense on what code completion features we support. It always needs a `<` first, then can complete the element name, then attribute names and value. When closing the tag with `>` you will get the closing tag.

Then there's another feature called Emmet for fast HTML generation. As @annoying258 writes (thanks!), https://code.visualstudio.com/docs/editor/emmet documents that.

If this is not working as advertised, please create a bug with a small code sample, maybe a screenshot and a description of what you see and what expected result.

Thanks a lot!
