### ISSUE TITLE
Code Folding on comments for 'this' class functions in JavaScript not working

### ISSUE THREAD

**Issue by doublehelix** [microsoft/vscode#80186]
VSCode Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

The following JavaScript code will allow folding of both the function _and_ the function comment...
```javascript
function MyClass() {
    /**
     * This is the description of this private function.
     *
     * @param {string} param1 The first parameter.
     * @returns
     */
    function myPrivateFunction(param1) {
        // do something
    }
}
```

The following code allows folding of the function, but _not_ the associated function comment...
```javascript
function MyClass() {
    /**
     * This is the description of this public class function.
     * This block comment WILL NOT fold.
     *
     * @param {string} param1 The first parameter.
     * @returns
     */
    this.publicClassFunction = function(param1) {
        // do something
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

screenshot:
![code-folding-examples](https://user-images.githubusercontent.com/355130/64090290-ca528800-cd8d-11e9-9245-89f08535ae57.jpg)

edit:
Var functions work ok: Var functions allow folding of function comments above them: `var privateVarFunction = function(param1) {...}` 

Function comments above _any_ object function definition won't fold: (e.g. in angular)
```
 /**
     * This is the description of this public class function for an AngularJS Scope.
     * This block comment WILL NOT fold.
     *
     * @param {string} param1 The first parameter.
     * @returns
     */
    $scope.publicClassFunction = function(param1) {
        // do something
    }
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new)
