### ISSUE TITLE
A restored Webview not using the original options and blocks scripts

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#80185]
# Problem
A webview which has scripts inside is running fine when it's presented with this option:
```json
{
    enableScripts: true
}

```
When it's restored, all the scripts are blocked and I'm getting this message from the console:
```
[Embedded Page] Blocked script execution in 'data:text/html;charset=utf-8,...' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

# Expected Behavior
The original options to create the webview panel should also be persisted and used while restoring the same view.

**Comment by mjbvz** [comment]
Duplicate of #78203

Already fixed in insiders
