### ISSUE TITLE
Integrated terminal open separate from main app window, (cmd, powershell, bash)

### ISSUE THREAD

**Issue by tsukasa696** [microsoft/vscode#80180]
![terminal_vscode](https://user-images.githubusercontent.com/27456027/64080650-e1926680-ccf6-11e9-8f5b-9db69d937529.jpg)

- VSCode Version: 
Version: 1.37.1 (system setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

- OS Version: Windows 10 Pro, version 1903, build 18362.295

Steps to Reproduce:

1. Open integrated terminal

Does this issue occur when all extensions are disabled?: Yes

This start to happen today, the last time i use was on Friday Vs Code was working perfectly, i start the vs code with all the ext disabled and was the same, i will appreciate any help

**Comment by weinand** [comment]
@tsukasa696 did you change the `terminal.explorerKind` setting to `external`?

**Comment by tsukasa696** [comment]
Hi @weinand ! My settings.json has being the same as when i install and mod to use different cmd

```
"shellLauncher.shells.windows": [{
            "shell": "C:\\Windows\\System32\\cmd.exe",
            "label": "cmd"
        },
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        },
        {
            "shell": "D:\\Program Files\\Git\\bin\\bash.exe",
            "label": "Git bash"
        },
        {
            "shell": "D:\\Program Files\\cmder\\cmder.exe",
            "Label": "Cmder"
        }
    ],
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
```
the last update i did to that file was on September/October last year no new changes, and was working really fine

**Comment by weinand** [comment]
All those settings you mentioned above are irrelevant to the problem you are seeing. Please change "terminal.explorerKind" and see whether that makes a difference.

**Comment by cnscorpions** [comment]
same issue with tsukasa696, but not work for me to change "terminal.explorerKind" setting

Launch VS Code
Type Ctrl + `
Expected: View Terminal
Actual: Open Windows powershell, not integrated terminal

version: 1.37.1 (system setup)
OS: Windows_NT x64 10.0.18362

**Comment by tsukasa696** [comment]
> All those settings you mentioned above are irrelevant to the problem you are seeing. Please change "terminal.explorerKind" and see whether that makes a difference.

i try your recommendation and still the same issue, i clean the settings.json and was the same result so i rollback

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
