### ISSUE TITLE
Quick "Invert condition" option

### ISSUE THREAD

**Issue by BeSpunky** [microsoft/vscode#80188]
Hi,

It would be awesome if VS Code would allow quick inversions of logical statements.
Example 1:
```
if (x == y)
    /// Do A
else
    /// Do B
```
Quick invert and it would become:
```
if (x != y)
   /// Do B
else
   /// Do A
```

Example 2:
`x > y ? A() : B()`

Quick invert:
`x <= y ? B() : A()`

Cheers 🥂

**Comment by weinand** [comment]
For what language?

**Comment by BeSpunky** [comment]
Well, the main ones for me would be JavaScript and TypeScript.
