### ISSUE TITLE
Add chords to "show same keybindings"

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#80181]
Currently, to find conflicts caused by a chord, you need to search for the first sequence, without any quotes. This works, but since the search is global across all four columns of information for each keyboard rule, it brings up a variety of commands that you're not interested in. Additionally, it's probably not an obvious way to find conflicts for most VSCode users.

I wonder if "Show Same Keybindings" should not only show the exact same keybindings, but also any keybindings where the first sequence of a chord matches. Alternatively, there could be a second option added to the context menu that does this.

**Comment by sandy081** [comment]
I like the idea of having separate entry/mechanism to look for keybindings containing keys.

**Comment by jabacchetta** [comment]
@sandy081 Similarly, when editing a keybinding through the keybinding edit widget, when it warns you with "x existing commands have this keybinding", it should probably also warn you if that keybinding is not a chord, but it appears in an existing chord sequence, which again, has the potential for conflicts.

With the two options being that those chord conflicts are either added to the existing warning count, or an additional warning is added with its own count.

**Comment by trylaarsdam** [comment]
Definitely. Some sort of mode (or at least an obvious switch) to search for first strokes in a chord would be amazing.

**Comment by heartacker** [comment]
great
