### ISSUE TITLE
Regression - Webview gets restored only when setState is executed

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode#80184]
This was originally tracked by #50752 and was supposed to be fixed by https://github.com/microsoft/vscode/commit/6e81adc78f03e587fdcd1846e0fb534977edc052

But this is still happening. I have to work around it by calling setState({}) to get the view restored. Here's the VS Code version I'm using.

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by akaroml** [comment]
Yes it's still reproducible in the insider build:

Version: 1.38.0-insider
Commit: 5ab84ce18fe7dee304325952f2849264dd4a48c1
Date: 2019-09-02T07:48:28.922Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
![out](https://user-images.githubusercontent.com/16755094/64223425-9058c180-cf06-11e9-9242-c9b63683138b.gif)
