### ISSUE TITLE
Goto Definition not working in Ruby 

### ISSUE THREAD

**Issue by klueless-io** [microsoft/vscode#80198]
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
Steps to Reproduce:

1. Right click on any method or class in ruby file
2. Click Go to Definition

No definition found for "method_or_class_name"

Does this issue occur when all extensions are disabled?: Yes/No

Yes, still occurs

**Comment by weinand** [comment]
Ruby is not built-into VS Code, so VS Code cannot address any Ruby related issues.
