### ISSUE TITLE
`editor.action.showSnippets` command does not has label

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#80197]
From @jabacchetta

Similar:

Same appears to be happening for editor.action.showSnippets, which is the command executed by the Insert Snippet command. Insert Snippet command name is not showing up above the command ID. This command name should maybe be renamed to Show Snippets as well? Because there's also a separate insertSnippet command ID.

editor.action.insertSnippet command ID is not showing in the search. Looks like there are actually three different commands being named/mixed up?

**Comment by sandy081** [comment]
`editor.action.showSnippets` does not has any label provided and hence only command id is shown in keybindings editor. @jrieken FYI


`editor.action.insertSnippet` command is not showing in the keybindings editor because the editor does not show commands with arguments.

Leaving this issue for `editor.action.showSnippets` command label.

**Comment by jrieken** [comment]
`editor.action.showSnippets` is only there for compatibility reasons, the new command is `showSnippets` (which has a label et al). What is this about?

**Comment by sandy081** [comment]
There are two parts in this request.

1. User complained that when typing `editor.action.showSnippets` in Keybindings editor, there is no label for it. - This issue is for tracking this.

2. `editor.action.insertSnippet` is not shown in keybindings editor which I respond saying that Keybindings editor does not show commands with arguments. There is a separate feature request for this.

**Comment by jrieken** [comment]
Ok - closing then. We cannot add a label to `showSnippets` because we don't want it in the UX (and since there is no way to redefine a keybindings-editor label)

**Comment by jabacchetta** [comment]
@jrieken There is already a label for `editor.action.showSnippets`, it just isn't showing in the keyboard shortcuts editor from my understanding. Open the command palette and execute the `Insert Snippet` command, which "shows snippets".

**Comment by jabacchetta** [comment]
@jrieken @sandy081 Think I'm still confused. Is `showSnippets` supposed to appear in the search? 

The primary problem for me was that I was able to open the command palette and use the following command name to show a list of snippets: `Insert Snippet`.

However, let's say you want to add a keybinding to that command name. You go into the keyboard shortcuts editor and you search for that exact command name, `Insert Snippet`, which I would assume would show up. That command name does NOT show up. What does show up is a different command ID, `insertSnippet`, that belongs to a different command.

To assign a keybinding to the command that's associated with the `Insert Snippet` command name in the command palette, you have to assign the keybinding to the `editor.action.showSnippets` command ID.

**Comment by sandy081** [comment]
@jabacchetta Command is not shown because of this - https://github.com/microsoft/vscode/issues/80214
