### ISSUE TITLE
Ctrl+` no longer working on Windows 10

### ISSUE THREAD

**Issue by ImedAdel** [microsoft/vscode#80199]
Issue Type: <b>Bug</b>

1. Launch VS Code
2. Type Ctrl + ` (grave accent)

Expected: View Terminal
Actual: Open Windows start menu

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.94GB free)|
|Process Argv|C:\Users\Faten\Dev\themed-ocde|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ImedAdel** [comment]
Nope.

**Comment by cnscorpions** [comment]
Launch VS Code
Type Ctrl + `
Expected: View Terminal
Actual: Open Windows powershell, not integrated terminal

version: 1.37.1 (system setup)
OS: Windows_NT x64 10.0.18362

**Comment by ImedAdel** [comment]
The issue solved itself somehow.
