### ISSUE TITLE
Show search progress

### ISSUE THREAD

**Issue by SebastianZ** [microsoft/vscode#80193]
Issue Type: <b>Feature Request</b>

When searching there should be some progress indicator, i.e. there should be an info about how many of the files the search already checked in comparison to the total number of files.

This could be absolute numbers and/or a percentage value of files searched vs. how many to search in total.

Sebastian

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
This would be nice to have, unfortunately we can't get this information from ripgrep, and collecting it would slow down the search.
