### ISSUE TITLE
Feature Request: Hide workbench view via keyboard shortcut

### ISSUE THREAD

**Issue by andradei** [Microsoft/vscode#8020]
- VSCode Version: 1.2.1
- OS Version: OS X El Capital

Steps to Reproduce:

1. <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>E</kbd> - Shows Explorer view
2. <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>E</kbd> - Pressing it again doesn't hide it

Same behavior for all workbench views.

I'd like to request the feature of hiding workbench views with either a unique shortcut or with the shortcut of the active view (making <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>E</kbd> a __toggle__ Explorer rather than _show_ Explorer).

This behavior already exists with a mouse click (it toggles the workbench view visibility). Having keyboard shortcut support would be fantastic.

Thank you for the amazing editor.

**Comment by bpasero** [comment]
View > Toggle Sidebar
