### ISSUE TITLE
Column selection broken

### ISSUE THREAD

**Issue by SmasherHell** [microsoft/vscode#80204]
### Step to reproduce:

1. Clic anywhere in a document
2. Hold shift and center-clic on the line above
=> the cursor has just moved, no column selection

I don't know if it is the "new" behavior to have to hold shift and center-clic 2 times (one on the begining of the selection, second at the end). It is sluggish on windows, it is a total crap on linux as center-clic is "Paste"

### System Info :

CPUs | Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.88GB (1.03GB free)

### Modules enabled:

Extension | Author (truncated) | Version
-- | -- | --
vscode-openapi | 42C | 1.8.12
vscode-base64 | ada | 0.1.0
swagger-viewer | Arj | 2.2.2
markdown-mermaid | bie | 1.2.0
vscode-standard-format | che | 0.0.12
transformer | dak | 1.6.0
jsonpath-extract | dav | 1.1.0
xml | Dot | 2.5.0
json-tools | eri | 1.0.2
vscode-diff | fab | 1.4.0
markdown-table-formatter | fcr | 1.4.3
sepaswitch | Fut | 1.0.2
graphviz-markdown-preview | gee | 0.0.8
gc-excelviewer | Gra | 2.1.32
markdown-table-formatter | jos | 0.3.0
rainbow-csv | mec | 1.3.1
prettify-json | moh | 0.0.3
mssql | ms- | 1.6.0
printcode | nob | 3.0.0
vscode-yaml | red | 0.5.2
vscode-statusbar-json-path | ric | 1.4.0
markdown-preview-enhanced | shd | 0.4.3
vscode-json-path | wei | 2.2.7
markdown-all-in-one | yzh | 2.4.2

**Comment by weinand** [comment]
Does this problem reproduce if you disable all extensions?
