### ISSUE TITLE
VSCode Window is topmost

### ISSUE THREAD

**Issue by dschiller** [microsoft/vscode#80200]
- VSCode Version: 1.37.1 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode in a Folder ( Rightclick, Open with Code )
2. Work a while with the Project
3. Switching between Windows and VSCode Editor
4. After a while VSCode Editor Window stays on top and don't let Windows behind get visible
5. Restart VSCode
6. Now it's working OK but after a while it happens again then one need to restart VScode again
7. If you work a day you need to restart VSCode approx 20 Times for this Issue

Does this issue occur when all extensions are disabled?: Not checked

**Comment by weinand** [comment]
Please check whether the issue occurs when all extensions are disabled. Without that information we won't start investigating the issue.

**Comment by dschiller** [comment]
WIth all extensions disabled it seems not to happen.
