### ISSUE TITLE
Snap package fails Store validation checks

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#80205]
@jhenstridge says in https://forum.snapcraft.io/t/new-store-automated-review-rule-is-incorrect/12963/12:

> Interestingly, it looks like Snapcraft isn’t properly sanitising the desktop file it puts in your snap. Here’s what the desktop file included in your snap looks like:
> 
> ```
> [Desktop Entry]
> Name=Visual Studio Code - Insiders
> Comment=Code Editing. Redefined.
> GenericName=Text Editor
> Exec=code-insiders %U
> Icon=${SNAP}/usr/share/pixmaps/com.visualstudio.code.insiders.png
> Type=Application
> StartupNotify=false
> StartupWMClass=Code - Insiders
> Categories=Utility;TextEditor;Development;IDE;
> MimeType=text/plain;inode/directory;
> Actions=new-empty-window;
> Keywords=vscode;
> 
> [Desktop Action new-empty-window]
> Name=New Empty Window
> Exec=/usr/share/code-insiders/code-insiders --new-window %F
> Icon=/usr/share/pixmaps/com.visualstudio.code.insiders.png
> ```
>
> Note that the `Icon` line for the `new-empty-window` action is not `${SNAP}/` relative, and that the `Exec` line also points outside of the snap. The version installed by snapd ends up looking like:
> 
> ```
> ...
> [Desktop Action new-empty-window]
> Name=New Empty Window
> Icon=/usr/share/pixmaps/com.visualstudio.code.insiders.png
> ```
> 
> … and when PR https://github.com/snapcore/snapd/pull/6767 1 is merged, that problematic `Icon` line will be removed too. Some of this could be considered a Snapcraft bug (since it is usually the one adding the ${SNAP}/ prefix to the Icon line), but the handling of the Exec line might be your responsibility.

**Comment by joaomoreno** [comment]
We should fix that `Exec` and `Icon` entries accordingly.

**Comment by joaomoreno** [comment]
I believe the Snapcraft's team analysis is outdated, our `code-insiders.desktop` file doesn't look like that. I've replied to them in https://forum.snapcraft.io/t/new-store-automated-review-rule-is-incorrect/12963/16?u=joaomoreno

**Comment by jhenstridge** [comment]
As mentioned on the forum, the desktop file that matters is `$SNAP/meta/gui/code-insiders.desktop`, rather than `$SNAP/usr/share/applications/code-insiders.desktop`.

This will generally be a version of the file you specified via `desktop:` in your `snapcraft.yaml` with some munging by Snapcraft (unless you manually stage something to `meta/gui`).

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/pull/80585

@alexandrudima Let's see tomorrow morning if Insiders publishes successfully to the Snap Store. If so, I would recommend cherry picking this for the August recovery release.

**Comment by joaomoreno** [comment]
@alexandrudima Actually, on second thought, let's not put this on the recovery release and simply manually approve the build as we did with the August release. This option feels less risky.
