### ISSUE TITLE
Provide document.encoding get/set property for extensions

### ISSUE THREAD

**Issue by DifficultNick** [microsoft/vscode#80215]
It would be nice to have something like `vscode.window.activeTextEditor.encoding` to get (or even set) current encoding (which's displayed in the bottom bar).

**Comment by weinand** [comment]
You can execute the `workbench.action.editor.changeEncoding` command (like any other command) via VS Code's extension API `vscode.commands.executeCommand(...)`.

**Comment by DifficultNick** [comment]
Yes, that's a half of a thing, thank you!
But at first It would be better to know if current encoding need to be changed. For example to solve task #36230 manualy.
