### ISSUE TITLE
Unable to open oversized text file

### ISSUE THREAD

**Issue by Everyb0dyLies** [microsoft/vscode#80212]
Issue Type: <b>Bug</b>

When I open a csv file above 1G, I get the following error: "invalid string length"

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (26.11GB free)|
|Process Argv|C:\Users\Ming\Downloads\3-3 --max-memory=16384|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vsc-material-theme|Equ|30.0.0
gc-excelviewer|Gra|2.1.32
ftp-sync|luk|0.3.9
MagicPython|mag|1.1.0
vscode-language-pack-zh-hans|MS-|1.37.5
mssql|ms-|1.6.0
python|ms-|2019.8.30787
cpptools|ms-|0.25.1
sublime-keybindings|ms-|4.0.3
material-icon-theme|PKi|3.9.0
code-settings-sync|Sha|3.4.2

(3 theme extensions excluded)

</details>

**Comment by Everyb0dyLies** [comment]
![image](https://user-images.githubusercontent.com/5823347/64112839-22ec4a00-cdbb-11e9-9c01-9b161d9c38a6.png)

I opened this file a few months ago, it seems that a previous version did not have this problem.

**Comment by weinand** [comment]
How do you open the file?
Does the same problem occur if you have all extensions disabled?
