### ISSUE TITLE
Reopen Closed Editor opens window always into upper splitscreen

### ISSUE THREAD

**Issue by FlixDerPartyBus** [microsoft/vscode#80216]
Hi, 
to reproduce the Issue, open three or more files in splitscreen view (1 at the top and 2 at the bottom). Now close on of the bottom ones. After that press CTRL + SHIFT + T. 
In my opinion the file should open where i closed it, but it opens in the upper one.
Thanks in Advance

**Comment by isidorn** [comment]
Disagree. Ctrl + Shift + T opens in the active group.
I believe you can open it in a new group if you hold cmd when pressing on a file name. 
This feels like as designed behavior to me, however leaving up to @bpasero to decide.
