### ISSUE TITLE
Indentation in kali-linux does not display properly

### ISSUE THREAD

**Issue by Rock718** [microsoft/vscode#80210]
Issue Type: <b>Bug</b>

When I set the text to be indented to 4 spaces and the open blank characters are visible, the display of whitespace characters in vscode is not normal. The cursor will stay in the second space (this is also true when the tab is indented), and multiple indentations will cause whitespace characters to overlap. Opening this file in another editor will display normal, indicating that the vscode display is abnormal. By browsing the information on the Internet, I found that ubuntu18.04 also has this problem.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.19.0-kali5-amd64
![image](https://user-images.githubusercontent.com/20013732/64111327-fe8e6e80-cdb6-11e9-86f9-d51a13ba2719.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2501)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (4.91GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
vscode-language-pack-zh-hans|MS-|1.37.5
python|ms-|2019.8.30787

</details>

**Comment by NanerLee** [comment]
it is the same as my issue #80170

Do you have some temporary solutions ?

**Comment by Rock718** [comment]
I haven't found solution yet.

**Comment by alexandrudima** [comment]
Workaround: `"editor.disableMonospaceOptimizations": true`

**Comment by Rock718** [comment]
As @NanerLee said in #80170,`"editor.disableMonospaceOptimizations": true` doesn't work. I don't know where the problem is. Is it related to the gnome desktop, or is it related to linux fonts?

**Comment by alexandrudima** [comment]
@Rock718 Have you tried with a different font family?

**Comment by Rock718** [comment]
I open `gnome-font-viewer` in gnome-terminal,select a font "Bitstream Vera Sans Mono",
![2019-09-10_22-47](https://user-images.githubusercontent.com/20013732/64624303-0d130080-d41d-11e9-9026-c891a6c5eee5.png)
use it as the default font for vscode,then eyerything is ok.
![2019-09-10_22-39](https://user-images.githubusercontent.com/20013732/64623676-f4eeb180-d41b-11e9-8c8b-f77ba5528549.png)
or edit in setting.json
![2019-09-10_22-39_1](https://user-images.githubusercontent.com/20013732/64623753-19e32480-d41c-11e9-958f-98c73c6e40e8.png)
the result is:
![2019-09-10_22-43](https://user-images.githubusercontent.com/20013732/64623946-747c8080-d41c-11e9-9959-57b1c42c06eb.png)
Maybe there are other fonts are feasible,I just tried this.

**Comment by Rock718** [comment]
Thank you for your reminder @alexandrudima.
