### ISSUE TITLE
Window freezes when scrolling

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#80213]
* todays insiders (5ab84ce18fe7dee304325952f2849264dd4a48c1)
* open the attached file tsc.out.txt
* scroll up/down and the editor freezes for a few seconds

[tsc.out.txt](https://github.com/microsoft/vscode/files/3565989/tsc.out.txt)
[CPU-20190902T141431.cpuprofile.txt](https://github.com/microsoft/vscode/files/3565991/CPU-20190902T141431.cpuprofile.txt)

**Comment by jrieken** [comment]
hm... closed all other files and now it does repro anymore 

bad chart vs. good chart

<img width="1047" alt="Screenshot 2019-09-02 at 14 17 27" src="https://user-images.githubusercontent.com/1794099/64114115-77c49c00-cd8c-11e9-80a6-fe2aa20f8794.png">

<img width="976" alt="Screenshot 2019-09-02 at 14 17 30" src="https://user-images.githubusercontent.com/1794099/64114116-77c49c00-cd8c-11e9-9441-df510a267f3c.png">

**Comment by alexandrudima** [comment]
The CPU profile is not indicative... there is a lot of time spent in (program), which indicates native node modules...but I don't know what is causing this.
