### ISSUE TITLE
Unable to watch for files error in an empty workspace

### ISSUE THREAD

**Issue by amiramix** [microsoft/vscode#80211]
Issue Type: <b>Bug</b>

I have disabled watcher in user settings /home/user/.config/Code/User:

    "files.watcherExclude": {
      "**": true
    }

When opening VCode with an existing workspace the error isn't shown. However, when opening a new VCode window the error is shown straight away:

Unable to watch for file changes in this large workspace.

When the watcher is disabled VCode should not attempt to watch any files and this error should not be shown.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.1.21-1-MANJARO snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4269)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|62.90GB (55.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
language-gettext|mro|0.1.1
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
debugger-for-chrome|msj|4.11.7

</details>

**Comment by amiramix** [comment]
The problem seems to be related to opening a second VCode window without closing the first workspace, i.e. when working with two workspaces at the same time. It doesn't matter which workspace I open first, the error is only shown when opening a second window regardless if a workspace is loaded in that second window or not.

**Comment by Everyb0dyLies** [comment]
![image](https://user-images.githubusercontent.com/5823347/64112695-bd985900-cdba-11e9-874e-842e2ac96675.png)

**Comment by Everyb0dyLies** [comment]
> The problem seems to be related to opening a second VCode window without closing the first workspace, i.e. when working with two workspaces at the same time. It doesn't matter which workspace I open first, the error is only shown when opening a second window regardless if a workspace is loaded in that second window or not.

But I only opened a window

**Comment by bpasero** [comment]
@amiramix 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by amiramix** [comment]
@bpasero Thanks for your quick response. I installed the insider version from the snap store and just tried it. It seems that this version doesn't have this problem, i.e. I don't see the error when opening a new window or project as I could in the normal version.

For now I would consider this as resolved but I will continue testing the insider version and comment here in case I can see the problem again.
