### ISSUE TITLE
Tab size is not picked up by editor

### ISSUE THREAD

**Issue by MikaelUmaN** [microsoft/vscode#80229]
Issue Type: <b>Bug</b>

Create a project using `dotnet new fake`.

Edit the build.fsx file.

The file is indented by 2 spaces rather than 4 as I have configured.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (53.01GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexandrudima** [comment]
@MikaelUmaN Indentation is controlled by 3 settings:

```js
// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be automatically 
// detected when a file is opened based on the file contents.
"editor.detectIndentation": true,

// The number of spaces a tab is equal to. This setting is overridden based on the 
// file contents when `editor.detectIndentation` is on.
"editor.tabSize": 4,

// Insert spaces when pressing `Tab`. This setting is overridden based on the 
// file contents when `editor.detectIndentation` is on.
"editor.insertSpaces": true,
```

Have you disabled indentation detection based on file contents with `"editor.detectIndentation": false` ?

**Comment by MikaelUmaN** [comment]
Thanks. I removed the "editor.detectIndentation".
