### ISSUE TITLE
`Configure Tasks... > Create tasks.json file from template` not shown consistantly

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/vscode#80221]
Issue Type: <b>Bug</b>

Repro:
> install fresh vscode 1.37
> clone git@github.com:webrtc-uwp/webrtc-uwp-sdk.git
> Open folder in vscode
> In vscode: Terminal > Configure Tasks... => Create tasks.json file from template (is shown)
> Create workspace in root folder of repository
> In vscode: Terminal > Configure Tasks... ___!=>___ Create tasks.json file from template (is not shown)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.21GB free)|
|Process Argv|C:\Projects\webrtc-uwp-sdk|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.25.1

</details>

**Comment by alexr00** [comment]
To verify, open a _workspace_ (not a folder) that doesn't have a tasks.json. Verify that going to Terminal > Configure Tasks shows a quick pick that includes an option to create a tasks.json.

**Comment by Holo-Viktor** [comment]
I've renamed the tasks.json to tasks.json1, there is still the .vscode folder containing c_cpp_properties.json and launch.json -> no option to create tasks.json.

**Comment by alexr00** [comment]
@Holo-Viktor thanks for checking, but since this is for the September 2019 milestone it is still only available in the Insiders build (version 1.39)

**Comment by Holo-Viktor** [comment]
oh i see, thanks
