### ISSUE TITLE
1.37.1 integrated terminal keyboard input repeat delay has increased from 1.36.1

### ISSUE THREAD

**Issue by henrik-jensen** [microsoft/vscode#80228]
- VSCode Version: 1.37.1
- OS Version: Microsoft Windows [Version 10.0.18362.295]

Steps to Reproduce:

1. Install fresh portable zip versions of 1.36.1 and 1.37.1 with `data` dir in install root
2. Set Repeat delay/rate to Short/Fast as in illustration:
![image](https://user-images.githubusercontent.com/9413242/64130925-9eeb8f80-cdc5-11e9-8eaf-c7ea16e841b2.png)
3. Start New terminal in both versions.
4. Press and hold a key, say 'a', and notice the delay of the repeated 'a's in 1.37.1 vs. 1.36.1.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
/duplicate https://github.com/xtermjs/xterm.js/issues/469#issuecomment-299740272

**Comment by henrik-jensen** [comment]
> /duplicate [xtermjs/xterm.js#469 (comment)](https://github.com/xtermjs/xterm.js/issues/469#issuecomment-299740272)

This is a duplicate of adding emoji to the terminal, seriously?!!!
Anyway is emojis really more important than a responsive input?

**Comment by Tyriar** [comment]
The root cause is that the terminal listens to keydown, not input, the same reason emoji IMEs don't work.

**Comment by henrik-jensen** [comment]
> The root cause is that the terminal listens to keydown, not input, the same reason emoji IMEs don't work.

Fair enough. But why the "regression" in delay from 1.36.1, or put in another way,- can't we wait to incorporate those newer versions of xterm.js until these problems are fixed? ( as the delay problem was not present in 1.36.1)?

**Comment by Tyriar** [comment]
Both 1.38 and 1.36 have the same delay for me when I tweak that setting on Windows so I'm not sure why it's differing for you. It might be that the terminal is laggier because of an Electron update or something, does it still happen if you change terminal.integrated.rendererType to "dom"?

**Comment by henrik-jensen** [comment]
Yes,- both dom, canvas and auto gives the delay. It's like the keys are sticky but then suddenly catches up and fires all the keys pressed. (This is 1.37.1 vs 1.36.1. I see there's an 1.38 update. I'll try that and report back)

**Comment by henrik-jensen** [comment]
At first I thought 1.38 had fixed the problem, but then I started a cmd shell from the ps prompt and the stickiness, returned, also when exiting the cmd prompt to return to the PS prompt. This behavior is also present in 1.37.1 but not in 1.36.1.

**Comment by henrik-jensen** [comment]
It seems especially noticeable when a subshell (cmd and wsl) has been started and stays when finished.
