### ISSUE TITLE
Accessibility word navigation does not handle punctuation well

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#80223]
From @neurrone

Enter the following line in a file:

```
a, b
```

I expect the following sequence to be heard when pressing ctrl+right from the start of the line:

```
a,
b
```

Instead, it speaks this:

```
a,
blank
```

If the line is modified to `a, /b`, the first ctrl+right causes an announcement of `a, /` which is also wrong.

**Comment by isidorn** [comment]
@Neurrone I am having some issue with NVDA and VSCode (both insiders and stable) on Windows. When I navigate words the words do not get read out by NVDA. Did NVDA change something that this needs to be enabled? When I navigate using up / down to change lines everything is read out correctly.
I am using NVDA 2019.2.1 and it is always in this "Pending Update" state. What version are you using?
Thanks for the help.

**Comment by isidorn** [comment]
ping @Neurrone for my question

**Comment by Neurrone** [comment]
@isidorn sorry for the late reply. There's a bunch of big refactoring going on in NVDA beyond 2019.1. I'm on the latest alpha version and can't reproduce this issue with the latest VS Code as well.

**Comment by isidorn** [comment]
@Neurrone thanks for letting me know. Let's close this for now and we can reopen in the future if you encounter it again.

**Comment by Neurrone** [comment]
@isidorn Sorry, I meant that I didn't have trouble with most word navigation, but the test case that I put above can still reproduce the issue.

**Comment by isidorn** [comment]
Ok, so let's reopen for now. And you can provide more feedback once you use the new NVDA more. Thanks

**Comment by Neurrone** [comment]
The issue should still be reproduceable with the version of NVDA you tested it with, 2019.2.1

**Comment by Neurrone** [comment]
CC-ing @derekriemer and @RobGallo

@isidorn I'm now able to semi-reliably reproduce moving up and down lines as well as by word not reading what it should. I'm not sure if this is caused by changes in Vs Code and/or NVDA, and seems to happen more often if my CPU is busy doing something else in the background.

**Comment by isidorn** [comment]
@Neurrone we did not really change anything with regards to the navigation logic. We only updated to the newest Electron, which in theory could affect this.

Also note that there is a PR open which is trying to tackle this https://github.com/microsoft/vscode/pull/83450
Maybe we can continue the discussion there. Thanks

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/90578
