### ISSUE TITLE
When typing letters in an input field, letters are being inserted at the begining of the string instead of at the end

### ISSUE THREAD

**Issue by yizongk** [microsoft/vscode#80222]
- VSCode Version: Insider 1.38
- OS Version: Window10 Version 10.0.18362 Build 18362

Steps to Reproduce:

1. Install Web Template Studio and Visual Studio IntelliCode (I am not sure if these two extension are required for this bug to appear, but it is the only two things I have installed on VSCode after a fresh VSCode installation)
2. Press ctrl+shift+P
3. Type in 'Web Template Studio' and click on 'Web Template Studio: Launch'
4. Once the it launches, under Project Names there is a input box
5. Type something in, like "hello" or something. Notice how the character are inserted at the end of the string as you type, which should be the normal behavior.
6. Now use your cursor, and highlight the string from right to left, dragging pass your current window in focus.
7. Release your left click to end highlighting, and type something in, you will see that the characters you are typing in, are now inserted at the beginning of the string.

Note: This bug only occurs if you drag highlight pass your window of focus. If you drag highlight within your window focus, the bug doesn't happen.

https://imgur.com/a/nDYYqJJ  --> This is a video of step 4 to 7
Notice how the first 2 times I have highlighted, it is pass the window of focus, and the bug will happen. The 3rd time, I have highlighted within the window of focus, and the bug did not occurred. 4th time is highlight pass window of focus, and bug occured again. 5th time highlighting is within window of focus, and bug did not occurred.

Does this issue occur when all extensions are disabled?: Yes/No

No, don't know how to reproduce with extensions disabled, because I can't find any input boxes to test this on.

**Comment by weinand** [comment]
The input boxes are inside a Web View and as such out of the control of VS Code.
Please file this issue against  Web Template Studio.

**Comment by yizongk** [comment]
I see, thank you for letting me know!
