### ISSUE TITLE
Other sort orders for extensions

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#8022]
- VSCode Version: Insiders 1.3
- OS Version: OS X

Steps to Reproduce:

1. Search for JavaScript

The results are sorted by relevance.  But we used to sort by download as the default.  We should default to download and provide an other (relevance, etc)

Sean

**Comment by joaomoreno** [comment]
It is now possible to sort any query by nothing (relevance), install count and ratings. The sort order is also customisable.

- `python`
- `python @sort:installs`
- `python @sort:installs-asc`
- `@sort:installs`
- `@sort:ratings`
