### ISSUE TITLE
Visual Studio Code Mac Crash v1.37.1

### ISSUE THREAD

**Issue by kylelovespi** [microsoft/vscode#80235]
Issue Type: <b>Bug</b>

I am experiencing reoccurring crashes while editing markdown files in VS Code. It happens most frequently when I am switching taps in the editor. It's not possible to reproduce and happens unexpectedly. It has happened across the last several releases of VS Code. I thought it was a bug that would be fixed, but the issue remains unresolved. This issue occurs even with all extensions disabled. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-table-prettify|dar|2.4.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by khaled212** [comment]
I'm have the same issue, I've tried to reinstall it thinking it would work but its still happening.

**Comment by kylelovespi** [comment]
I will give it a test. Since it's not something I can reproduce, I'll need to use the editor for a while to know one way or the other. It does still exist as an issue on v1.38, which crashed almost instantly on load.

**Comment by kylelovespi** [comment]
Hi @mjbvz - Yes, it still happens in the VS Code - Insiders build. Today I got a beachball on my Mac when I went to install the markdownlint extension (no other extensions previously installed or running at the time).

**Comment by mjbvz** [comment]
When exactly did it crash? When you opened the extension's page in VS Code or when the extension itself was installed?

**Comment by kylelovespi** [comment]
Hi @mjbvz - It crashed at the moment I clicked the green "Install" button under the recommended section of apps. 

![image](https://user-images.githubusercontent.com/13473272/64627895-6f88e400-d3be-11e9-86ef-a5586f648390.png)

**Comment by mjbvz** [comment]
Can you also quickly try clicking on one of the extension to view its detail page. I want to understand if opening the extension's readme page causes the crash or if the install itself does

**Comment by kylelovespi** [comment]
The readmes open no problem. It seems like sometimes it can be triggered from similar actions though, such as switching to a preview of a markdown file.

**Comment by mjbvz** [comment]
This sounds similar to #80535

Let me know if you still see it in the next insiders build (which should be coming out within the next day)
