### ISSUE TITLE
Workspace Settings do not override User Settings

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#80243]
- VSCode Version: 1.37.1
- OS Version: Win 8.1

The extension [Select By](https://github.com/rioj7/select-by) uses an object setting to be able to group multiple settings together. I have defined the setting `selectby.regexes` in the User Settings and in the Workspace Settings. I am unable to get the Workspace Settings.

I get the Workspace Settings if I remove/rename the entry in the User Settings.

I have tried specifying a scope (`resource`) or not. (The [documentation](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) does not specify what the default scope is, or is there a fifth null scope)

I have tried possible alternatives for the call to
```javascript
vscode.workspace.getConfiguration('selectby').get('regexes');
vscode.workspace.getConfiguration('selectby', null).get('regexes');
vscode.workspace.getConfiguration('selectby', vscode.workspace.workspaceFolders[0].uri).get('regexes');
``` 
Sometimes I get a warning
```
Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'selectby.regexes', provide the URI of a resource or 'null' for any resource.
```

How do I need to call `vscode.workspace.getConfiguration` to get the Workspace Settings.

Steps to Reproduce:

1. Install the extension Select By
2. Define the User Setting
```
    "selectby.regexes": {
      "regex1": {
        "flags": "i",
        "backward": "%% section",
        "forward": "%% section",
        "forwardInclude": true,
        "backwardInclude": true
      }
    }
```
3. Create a test folder and open it in VSC
4. Define the Workspace Setting
```
  "selectby.regexes": {
    "regex1": {
      "flags": "i",
      "forward": "%% section",
      "forwardInclude": true
    }
  }
```
5. create a text file with the content
```
start VSC
%% section
write a program
%% section
debug the code
%% section
run the program
%% section
get a drink
```
6. put the cursor in the middle of line 5 ("debug....")
7. Execute the command "Select text range based on regex 1"
8. the new selection includes also the previous `%% section` text and the beginning of the line
9. rename the User Setting to `"selectby.Xregexes"`
10. Execute the command again and now the selection starts at the cursor position.

**Comment by rioj7** [comment]
@weinand I am developing this extension and I have a problem with the vscode API. It does not behave as described or the documentation is not clear.

It is not working for **object** configuration/setting.

For testing I added the following 2 configurations to `package.json`
```
        "selectby.someBool": {
          "type": "boolean",
          "default": false,
          "description": "Testing bool"
        },
        "selectby.someNumber": {
          "type": "number",
          "default": 20,
          "description": "Testing number"
        }
```
and in the extension I add an info message to show there values when you call a command
```
    let somebool = vscode.workspace.getConfiguration('selectby').get('someBool');
    let somenumber = vscode.workspace.getConfiguration('selectby').get('someNumber');
    vscode.window.showInformationMessage("SomeBool: "+somebool.toString()+"  SomeNumber: "+somenumber.toString());
```
The Boolean and the Number behave as expected: the Workspace Setting **overrides** the User Setting.
But this does not work for the Object (`"type": "object"`) configuration/setting.

**Comment by sandy081** [comment]
@rioj7 Can you provide me the sample for `object` type configuration and what is not working?

**Comment by rioj7** [comment]
@sandy081 A sample of the object I want to use is a simple JSON object as shown in the original question. (`"selectby.regexes": { .... }`)

What is not working is the fact that a workspace version of the settings object does **not** override the user settings version. If I use bool or number it works.

**Comment by rioj7** [comment]
Looking at another extension I found you can describe the schema of the allowed object.

I have added this to the `package.json` and set a `scope` but it makes no difference except entering the object gets help.

```json
        "selectby.regexes": {
          "type": "object",
          "scope": "resource",
          "description": "Object with parameters for the different regexes",
          "default": {},
          "patternProperties": {
            "^regex[1-5]$": {
              "type": "object",
              "properties": {
                "flags": {
                  "type": "string",
                  "description": "string with the regex flags \"i\" and/or \"m\" (default: \"\")"
                 },
                 "backward": {
                  "type": "string",
                  "description": "(Optional) regular expression to search from the selection start (or cursor) to the start of the file"
                },
                "forward": {
                  "type": "string",
                  "description": "(Optional) regular expression to search for from the selection end (or cursor) to the end of the file"
                },
                "backwardInclude": {
                  "type": "boolean",
                  "description": "(Optional) should the matched backward search text be part of the selection (default: true)"
                },
                "forwardInclude": {
                  "type": "boolean",
                  "description": "(Optional) should the matched **forward** search text be part of the selection (default: true)"
                },
                "copyToClipboard": {
                  "type": "boolean",
                  "description": "(Optional) copy the selection to the clipboard (default: false)"
                },
                "showSelection": {
                  "type": "boolean",
                  "description": "(Optional) modify the selection to include the new searched positions. Useful if `copyToClipboard` is true. (default: true)"
                }
              },
              "dependencies": {
                "backwardInclude": ["backward"],
                "forwardInclude": ["forward"]
              }
            }
          },
          "additionalProperties": false
        },
```

**Comment by rioj7** [comment]
@sandy081  The sample is the 10 steps I explained in the original issue. The source code of the extension I'm building can be found on github.

The Workspace Setting does not replace the User Setting for Object configuration items.

It works for numbers and booleans.

**Comment by sandy081** [comment]
@rioj7 I understand that the sample in the description and it is for numbers and booleans which is an happy case.

I am requesting you to provide a code sample for object configuration items.

**Comment by sandy081** [comment]
Object values are not replaced completely, Instead they are merged while overriding. For eg:

- User value
```json
{
 "a" : "value1"
"b": "value2"
}
```

- Workspace value
```json
{
"b": "value3"
"c": "value4"
}
```

Effective value is as follows
```json
{
"a": "value1"
"b": "value3"
"c": "value4"
}
```

**Comment by rioj7** [comment]
@sandy081 Is this behaviour described somewhere?

This is strange.
If I have setup a working setting for some Workspace and I later define a User setting version effecting different properties the extension will now work different for my Workspace. I now need to add all the properties defined in the User setting with there default values.

Is this merging done on 1 level or on all levels of properties? (shallow-merge or deep-merge)

User
```
{
 "a" : "value1"
 "b" : {
    "c" : "value3"
  }
}
```
 Workspace
```
{
 "a" : "value2"
 "b" : {
    "d" : "value4"
  }
}
```
What will be the value of `b.c` in the Workspace?

**Comment by sandy081** [comment]
>  Is this behaviour described somewhere?

Unfortunately not. Filed an issue in our docs https://github.com/microsoft/vscode-docs/issues/3113

Its always deep merge.
