### ISSUE TITLE
Executing the use of references and variables in typescript removes placeholder parameter variables in functions

### ISSUE THREAD

**Issue by yangdan8** [microsoft/vscode#80242]
- VSCode Version:
1.37.1
- OS Version:
win10

Steps to Reproduce:
1.typescript execution removes references and variables used
2. The placeholder parameter variable in the function will be deleted
 For example:

// Before:
function fn(a:string,b:number){
return b;
}

// After:
function fn(b:number){
return b;
}

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by weinand** [comment]
What do you mean by "typescript execution"?

**Comment by IllusionMH** [comment]
Looks like duplicate of https://github.com/microsoft/TypeScript/issues/32196

**Comment by yangdan8** [comment]
The same problem as #32196
