### ISSUE TITLE
Are there shortcuts like Android Studio's for selecting code blocks or methods?

### ISSUE THREAD

**Issue by GanZhiXiong** [microsoft/vscode#80249]
Android Studio can quickly select code with option+up
As shown in the following image GIF

![11 (1)](https://user-images.githubusercontent.com/27394631/64150818-9e053d00-ce5b-11e9-8fe1-c182ee725181.gif)

**Comment by weinand** [comment]
VS Code has "Expand Selection" and "Shrink Selection" commands.
