### ISSUE TITLE
Extensions Commands Missing/Confusion from Marketplace

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#8024]
- VSCode Version: Insiders 1.3
- OS Version: OS X (all)

Steps to Reproduce:

1. Marketplace has guidelines for installing i.e. type ext inst...
2. In the marketplace copy the link and guidance to install i.e.
Cmd+P and paste
3. commands are missing so does nothing - need to add them back 

See this page:
![image](https://cloud.githubusercontent.com/assets/1051190/16284664/231b1faa-3887-11e6-986e-49e9774156d3.png)

**Comment by joaomoreno** [comment]
Not forgotten! #8023
