### ISSUE TITLE
VS Code & code snippets batch export

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode#80247]
# VS Code & code snippets batch export

> feature wanted

![image](https://user-images.githubusercontent.com/7291672/64147497-069bec00-ce53-11e9-9e02-834b31d465e8.png)

**Comment by xgqfrms** [comment]
# situation

1. If I want to change the computer, I have to manually export these code snippets one by one, 

This is a waste of my time.

**Comment by jrieken** [comment]
They are stored as files, either inside your workspace or inside `<user_data_dir>/snippets`. From there, copy paste them. No need for an export command.

**Comment by jrieken** [comment]
Well, on a second thought. I somebody wants to work on it, go for it

**Comment by xgqfrms** [comment]
# solutions

https://marketplace.visualstudio.com/items?itemName=rebornix.project-snippets

**Comment by xgqfrms** [comment]
# vs code snippets folder?

https://code.visualstudio.com/docs/editor/userdefinedsnippets

https://code.visualstudio.com/api/language-extensions/snippet-guide

**Comment by xgqfrms** [comment]
@jrieken I think this issue shouldn't be closed.

**Comment by xgqfrms** [comment]
> They are stored as files, either inside your workspace or inside `<user_data_dir>/snippets`. From there, copy paste them. No need for an export command.

with path or folder, can you provide me a demo path with screen shortccut, I can't find that.
