### ISSUE TITLE
Show branch name in placeholder for all git commit commands

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#80250]
There's a new feature that shows branch name is SCM View input:

<img width="409" alt="branch-name" src="https://user-images.githubusercontent.com/9638156/64151811-db55d480-ce33-11e9-99e9-9378b7fb7d66.png">

But other git commit commands do not include it:

![Screenshot (74)](https://user-images.githubusercontent.com/9638156/64151886-fde7ed80-ce33-11e9-8755-5e390e1ed13e.png)

Such as:

```
git.commit
git.commitAll
...
```

**Comment by weinand** [comment]
The current branch name is shown in the status bar:

<img width="320" alt="2019-09-03_09-20-28" src="https://user-images.githubusercontent.com/1898161/64152070-1d7b1800-ce2c-11e9-88b7-00e96fd30c18.png">

**Comment by usernamehw** [comment]
The original issue was specifically to see the branch name **close** to the input, (so that you don't have to look at different places, or when status bar / branch indicator is hidden).

**Comment by joaomoreno** [comment]
@usernamehw Care to submit a PR?

**Comment by usernamehw** [comment]
I can try.
