### ISSUE TITLE
TypeScript Syntax Highlighting works incorrectly with non-English identifiers

### ISSUE THREAD

**Issue by fantaclaus** [Microsoft/vscode#8025]
- VSCode Version: 1.2.1
- OS Version: Win 7 Pro

create a `file.ts` with code:

```
let item = "value1";
let элемент = "value2";
```
In VSCode you'll see it this way:

![image](https://cloud.githubusercontent.com/assets/7231941/16284980/894737aa-38dc-11e6-8001-398d4730168d.png)

The identifier `item` has blue color, but `элемент` is white. In the first line the string value is brown, but in the second line the coloring is corrupted completely.

The same happens with everithing: function names, class names, class member names etc. For example:

```
function Main_Функция(s: string)
{
}

function Функция_Main(s: string)
{
}
```

This code looks like this:

![image](https://cloud.githubusercontent.com/assets/7231941/16285331/30c65fe6-38de-11e6-9b54-ddccf61ac500.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#193
