### ISSUE TITLE
markdown code chunk  don't  highlight in curly braces after tab

### ISSUE THREAD

**Issue by WillDawnlll** [microsoft/vscode#80259]
- VSCode Version:1.37.1

- OS Version:windows10 18362.295

Steps to Reproduce:

1.open markdown document use vs code 
2.write a code chunk with curly braces( every line begin with tab )
3.the code don't be highlight in curly braces
4.write a new line under forward curly braces line, write ` ``` `
5.next line got highlight ,but more down line still no highlight
6.for every no hightlight line , add a new line  with ` ``` ` befor no highlight line ,the code will be highlight 

![1](https://user-images.githubusercontent.com/28567110/64172722-36b1b200-ce88-11e9-8df7-c7c0bb32e37d.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Also, please share the text of the code along with screenshots

**Comment by WillDawnlll** [comment]
> 
> 
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
> 
> Also, please share the text of the code along with screenshots

thank u, this bug's code detail is unimportant, it appear when write in markdown code block curly braces

**Comment by WillDawnlll** [comment]
...find a closed issue .but yesterday i dont notice it, sorry and thank your
help
