### ISSUE TITLE
Deploy neccessary files for SSH-Remoting via SCP

### ISSUE THREAD

**Issue by eviscares** [microsoft/vscode#80253]
At the moment the binaries to enable ssh-remoting are downloaded to the host via a wget command, which works well in theory, but does not work well for hosts which can not access the internet.

I therefore propose to download the neccessary files via wget on the machine initiating the connection, and then deploy them to the target machine using scp.

**Comment by roblourens** [comment]
Please try installing the ssh nightly build (uninstall stable first) then set this setting: `"remote.SSH.allowLocalServerDownload": true`. It does exactly what you ask for.
