### ISSUE TITLE
Debug with arguments without launch.json

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#80267]
VSCode already supports debugging with arguments via launch.sjon, however this is geared towards spending a lot of time debugging one particular configuration. This is very inflexible for script or tool debugging scenarios, where there is frequently a need to quick test various different command-line parameters, and adding them all into launch.json is cumbersome.

There is already an extension that allows [running debug with parameters](https://marketplace.visualstudio.com/items?itemName=bpisler.vscode-debug-arg), however it only allows for one parameter, and doesn't split them up like shell does. It would be good to have this supported natively in VSCode.

**Comment by weinand** [comment]
@natolyburakov please provide more details what you are envisioning here. 
And please see https://github.com/Microsoft/vscode/issues/10979.

**Comment by anatolyburakov** [comment]
@weinand #10979 is not exactly what i'm looking for. even setting suboptimal usability aside (manually entering debug commands), running VSCode from command-line would work locally, but not when using Remote SSH extension. Maybe it would be better if i described a scenario in which this would be useful.

Imagine i'm writing a Python tool. It has a few command-line parameters, all of which trigger wildly different paths, and are very adjustable. For example:
```
./tool.py -a
./tool.py -b 10
./tool.py -b 20 -c 30
./tool.py -a -b 20 -c 30
```
now, imagine that i have to cycle through all of these quickly, and ensure all of the combinations etc. work. i may just use these once, and never again, so there's no point in adding them to launch.json - it'd take me longer to do that than to run the tool from the command-line with necessary arguments, and my launch.json would be bloated with all of the permutations of all the arguments that i've ever debugged with, which is not ideal as well.

what i'm envisioning is kind of what the [above quoted extension](https://marketplace.visualstudio.com/items?itemName=bpisler.vscode-debug-arg) does, only supporting multiple parameters, not just one. as in, run debug, prompt for command-line parameters (or reuse previous parameters), and launch the program with desired parameters.

**Comment by weinand** [comment]
@anatolyburakov so why not filing a feature request against the above quoted extension, or submitting a PR with the changes?

**Comment by anatolyburakov** [comment]
> or submitting a PR with the changes
not everyone is proficient in all things JavaScript

> so why not filing a feature request against the above quoted extension
i believe the problem was that VSCode doesn't allow supplying multiple arguments that way, and i don't really know how to formulate this in terms of "what needs to be done to make this happen". besides, i think such an obvious feature shouldn't require extensions.
