### ISSUE TITLE
Open file with `arrow up`/`arrow down` in Explorer

### ISSUE THREAD

**Issue by gerardolima** [microsoft/vscode#80266]
When in Explorer, open the selected file on `up arrow`/`down arrow`.

This issue is similar to #55816 and some context can be read in that thread. All the following users were intervenients on that issue and might also be interested to contribute to this conversation: @isidorn, @RMacfarlane, @barelabs, @justinlevi, @MiLeung, @krisnye.

**Comment by gerardolima** [comment]
As @krisnye wrote on #55816:
> When using the up and down arrow keys in the file explorer panel to navigate between files it would be good for the file you have selected to be opened in Preview mode.

**Comment by gerardolima** [comment]
As I wrote on  #55816::
> having the files previewed on arrow-up/arrow-down would be consistent with the default existing behavior of previewing the contents on mouse-click, and would improve user experience while browsing the codebase.

**Comment by isidorn** [comment]
Thanks for opening this feature request.
Currently we do not have plans to tackle this thus assigning to the backlog, however we might revisit this in the future. Thanks!

**Comment by gerardolima** [comment]
hey @isidorn, no problem, but then I don't get the suggestion to create this issue if it was to be discarded ... anyway, thank you for your time; cheers

**Comment by Japanuspus** [comment]
Would really like to see this feature. If you want a quick demo of the UX, you can try Sublime Text 3 which implements preview as suggested.
Completely agree with @gerardolima that this is super nice for exploring a new codebase, especially on an OS that does not have quick-view directly in the filesystem explorer.

**Comment by macintacos** [comment]
For those that came here, here's the solution I came up with (my solution uses `j`/`k` but just replace with `up`/`down` and I'm sure you'll get the same thing). Would just like to share since I was surprised there wasn't something like this already.

1. Download [the multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
2. Set up the following command in your `settings.json` (`multiCommand.navigateExplorerDownAndPreviewFile`/`multiCommand.navigateExplorerUpAndPreviewFile` can be whatever you want):

  ```
  "multiCommand.commands": [
    {
      "command": "multiCommand.navigateExplorerDownAndPreviewFile",
      "sequence": ["list.focusDown", "filesExplorer.openFilePreserveFocus"]
    },
    {
      "command": "multiCommand.navigateExplorerUpAndPreviewFile",
      "sequence": ["list.focusUp", "filesExplorer.openFilePreserveFocus"]
    }
  ]
  ```
3. Then set the following in `keybindings.json`:

  ```
  {
    "key": "j",
    "command": "multiCommand.navigateExplorerDownAndPreviewFile",
    "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
  },
  {
    "key": "k",
    "command": "multiCommand.navigateExplorerUpAndPreviewFile",
    "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
  }
  ```

I just have `l` set up to run `list.select` to _actually_ open the file if I want to edit it, but you could set it up with `right` if you want to keep an arrowkeys-focused workflow.

**Comment by parreirat** [comment]
> For those that came here, here's the solution I came up with (my solution uses `j`/`k` but just replace with `up`/`down` and I'm sure you'll get the same thing). Would just like to share since I was surprised there wasn't something like this already.
> 
> 1. Download [the multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
> 2. Set up the following command in your `settings.json` (`multiCommand.navigateExplorerDownAndPreviewFile`/`multiCommand.navigateExplorerUpAndPreviewFile` can be whatever you want):
> 
> ```
> "multiCommand.commands": [
>   {
>     "command": "multiCommand.navigateExplorerDownAndPreviewFile",
>     "sequence": ["list.focusDown", "filesExplorer.openFilePreserveFocus"]
>   },
>   {
>     "command": "multiCommand.navigateExplorerUpAndPreviewFile",
>     "sequence": ["list.focusUp", "filesExplorer.openFilePreserveFocus"]
>   }
> ]
> ```
> 
> 1. Then set the following in `keybindings.json`:
> 
> ```
> {
>   "key": "j",
>   "command": "multiCommand.navigateExplorerDownAndPreviewFile",
>   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> },
> {
>   "key": "k",
>   "command": "multiCommand.navigateExplorerUpAndPreviewFile",
>   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> }
> ```
> 
> I just have `l` set up to run `list.select` to _actually_ open the file if I want to edit it, but you could set it up with `right` if you want to keep an arrowkeys-focused workflow.

You da man. I just wanted to say this, after spending ~4h getting all my stuff set up to try VSCode for Ruby after ~6 years of just using SublimeText.
Thanks!

**Comment by manoharreddyporeddy** [comment]
@macintacos @parreirat 

"Manual Execution" part given at https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command
is working

However when i put keyboard focus on explorer, and press k/l nothing happens except that the key pressed is shown on right top of explorer view

how to unblock on this issue? help appreciated!

**Comment by manoharreddyporeddy** [comment]
Ok I solved it

using `double-down` arrow key & `double-up` arrow key

that is
Press `up` & `up` 2 times
Press `down` & `down` 2 times

In other words
single keys are not working
also I like to use down and up arrow - so this is best option for me.

thanks @macintacos  for original solution

    [
      {
        "key": "down down",
        "command": "multiCommand.navigateExplorerDownAndPreviewFile",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
      },
      {
        "key": "up up",
        "command": "multiCommand.navigateExplorerUpAndPreviewFile",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
      }
    ]

**Comment by macintacos** [comment]
@manoharreddyporeddy I'm not exactly sure what you ran into, as my above solution (with single-letter key shortcuts) works fine, and has worked since I mentioned it. Glad you solved whatever issue you were having though.

**Comment by manoharreddyporeddy** [comment]
@macintacos 

- Single `letter` keys din't work
- Single `down` & `up` arrows worked.

I have many extensions installed, that may be the issue for above.

**Comment by nithinpm09** [comment]
> For those that came here, here's the solution I came up with (my solution uses `j`/`k` but just replace with `up`/`down` and I'm sure you'll get the same thing). Would just like to share since I was surprised there wasn't something like this already.
> 
> 1. Download [the multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
> 2. Set up the following command in your `settings.json` (`multiCommand.navigateExplorerDownAndPreviewFile`/`multiCommand.navigateExplorerUpAndPreviewFile` can be whatever you want):
> 
> ```
> "multiCommand.commands": [
>   {
>     "command": "multiCommand.navigateExplorerDownAndPreviewFile",
>     "sequence": ["list.focusDown", "filesExplorer.openFilePreserveFocus"]
>   },
>   {
>     "command": "multiCommand.navigateExplorerUpAndPreviewFile",
>     "sequence": ["list.focusUp", "filesExplorer.openFilePreserveFocus"]
>   }
> ]
> ```
> 
> 3. Then set the following in `keybindings.json`:
> 
> ```
> {
>   "key": "j",
>   "command": "multiCommand.navigateExplorerDownAndPreviewFile",
>   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> },
> {
>   "key": "k",
>   "command": "multiCommand.navigateExplorerUpAndPreviewFile",
>   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> }
> ```
> 
> I just have `l` set up to run `list.select` to _actually_ open the file if I want to edit it, but you could set it up with `right` if you want to keep an arrowkeys-focused workflow.

thanks a lot.

**Comment by nithinpm09** [comment]
> > For those that came here, here's the solution I came up with (my solution uses `j`/`k` but just replace with `up`/`down` and I'm sure you'll get the same thing). Would just like to share since I was surprised there wasn't something like this already.
> > 
> > 1. Download [the multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
> > 2. Set up the following command in your `settings.json` (`multiCommand.navigateExplorerDownAndPreviewFile`/`multiCommand.navigateExplorerUpAndPreviewFile` can be whatever you want):
> > 
> > ```
> > "multiCommand.commands": [
> >   {
> >     "command": "multiCommand.navigateExplorerDownAndPreviewFile",
> >     "sequence": ["list.focusDown", "filesExplorer.openFilePreserveFocus"]
> >   },
> >   {
> >     "command": "multiCommand.navigateExplorerUpAndPreviewFile",
> >     "sequence": ["list.focusUp", "filesExplorer.openFilePreserveFocus"]
> >   }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Then set the following in `keybindings.json`:
> > 
> > ```
> > {
> >   "key": "j",
> >   "command": "multiCommand.navigateExplorerDownAndPreviewFile",
> >   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> > },
> > {
> >   "key": "k",
> >   "command": "multiCommand.navigateExplorerUpAndPreviewFile",
> >   "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just have `l` set up to run `list.select` to _actually_ open the file if I want to edit it, but you could set it up with `right` if you want to keep an arrowkeys-focused workflow.
> 
> thanks a lot. Is there a more generic command to "filesExplorer.openFilePreserveFocus" so that I can use the same logic for source control panel too. "list.selectAndPreserveFocus" seems to toggle folders on navigation which is a bit annoying. Thanks again for you help.

the best I could find was this work around, where we try to expand all (file or folder). It works, but not clean.
    "key": "down",
    "command": "extension.multiCommand.execute",
    "args": {
      "interval": 10,
      "sequence": [
        "list.focusDown",
        "list.selectAndPreserveFocus",
        "list.expand"
      ]
    },
    "when": "sideBarFocus && activeViewlet == 'workbench.view.scm'"

**Comment by icetbr** [comment]
Here is my solution, adjusted to work with any list kind of view, including the **File Explorer** and the **Outline** view. I use an old extension [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros), but it does the same. I just started using this, so far no problems. I don't like the `expand` folders,  so this suits me.

keybindings.json
```json
{ "key": "down", "command": "macros.downAndOpen", "when": "listFocus" },
{ "key": "up", "command": "macros.upAndOpen", "when": "listFocus" },
```
settings.json
```json
"macros": {
    "downAndOpen": [ "list.focusDown", "list.selectAndPreserveFocus" ],
    "upAndOpen": [ "list.focusUp", "list.selectAndPreserveFocus" ]
},
```

**Comment by mahiki** [comment]
Solution by @icetbr works great! Except the folders expand/collapse kind of weirdly so I'm using the `&& !explorerResourceIsFolder` in the `"when":` condition. I like to arrow left/right to close/descend into folders.

Also a strange effect: if a folder has only one file in it, there is no `up/down` to trigger the preview, so you have to press `space` to get the file to open in preview.

Overall this is very close to the Sublime Text behavior I used when browsing through the codebase.

**Comment by MuhsinFatih** [comment]
@mahiki I tried the same thing, but I think it checks for the resource when you click up or down, not after, so it's actually checking not the file/folder that you're navigating to, but the file/folder that you're focused before navigating up or down. It's a weird behavior. I wish I could add that if statement to the macro itself so that it checks for the resource **after**

**Comment by charygao** [comment]
> ```json
> "macros": {
>     "downAndOpen": [ "list.focusDown", "list.selectAndPreserveFocus" ],
>     "upAndOpen": [ "list.focusUp", "list.selectAndPreserveFocus" ]
> },
> ```
    "macros.list": {
       "downAndOpen": [ "list.focusDown", "list.selectAndPreserveFocus" ],
        "upAndOpen": [ "list.focusUp", "list.selectAndPreserveFocus" ],
    },
