### ISSUE TITLE
Terminal Paths not working ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#80261]
Terminal Integrated environment for Windows does not work. I've set PATHS for this setting and when in the integrated terminal, I cannot access any program in the PATHS when in the integrated terminal ?

**Comment by weinand** [comment]
I do not really know what you mean by "PATHS" but the macOS/linux environment variable is called "PATH" and on Windows it is "Path"

**Comment by SheepDomination** [comment]
When I set a PATH within my workspace setting in the setting `terminal.integrated.env.windows`; and I call a program which is in a PATH **only** within the integrated terminal, correct me if I'm wrong, but shouldn't that program start when I'm in the integrated terminal ?

**Comment by weinand** [comment]
I'm not sure, since the correct name of the env variable on Windows is "Path" and not "PATH". But I'm a macOS user and cannot really speak for Windows...

**Comment by SheepDomination** [comment]
It's PATH, although does it mimic what you can do with Windows System environment variables ? Hopefully a Windows user can answer, because this is not working.

**Comment by Tyriar** [comment]
Try echoing the environment variables and see what they equal to make sure they're getting set correctly. Everything is working fine here on Windows, it's likely an environment/config issue on your end.

**Comment by SheepDomination** [comment]
@Tyriar When echoing the PATH instead of getting the PATH for VSCode, which should be the PATH set in the setting `terminal.integrated.env.windows`; I'm getting the result of the system PATH ?

**Comment by Tyriar** [comment]
@SheepDomination please share your full settings.json file

**Comment by SheepDomination** [comment]
This is my *workspace* settings; unless `terminal.integrated.env.windows` paths must be put within the *settings.json* file; if so please do not close this issue immediately as I would like to verify all is working. 

There are PATHS in this *workspace* settings which have executable which should grant access to any program regardless what path I'm in the terminal, although that doesn't work ? 

```
{
	"folders": [
		{
			"path": "C:\\Custom Program Settings\\Projects.Code"
		}
	],
	"settings": {
		"workbench.statusBar.visible": false,
		"python.envFile":"${workspaceFolder}/.env",
		"python.linting.pylintEnabled": true,
		"editor.fontFamily": "Fira Code",
		"editor.fontLigatures": true,
		"python.jediEnabled": false,
		"python.autoComplete.extraPaths": ["C:\\Program Files\\Side Effects Software\\Houdini 17.5.293\\houdini\\python2.7libs"],
		"python.autoComplete.addBrackets": true,

		"terminal.integrated.env.windows": {
			"PYTHONPATH" : "C:\\Program Files\\Side Effects Software\\Houdini 17.5.293\\houdini\\python2.7libs",
			"PATH": "${env:PATH};C:\\Program Files\\Side Effects Software\\Houdini 17.5.293\\bin;${workspaceFolder}",
			"PRMAN": "C:\\Program Files\\Pixar\\RenderManProServer-22.1\\bin",
			"RMANTREE": "C:\\Program Files\\Pixar\\RenderManProServer-22.1\\"



			
			
		}
	}
}
```

**Comment by Tyriar** [comment]
How are you opening the terminal? Can you show a screenshot of the terminal including the dropdown box?

**Comment by SheepDomination** [comment]
I'm opening the terminal with `CTRL+~`

![terminalview](https://user-images.githubusercontent.com/6827459/64460761-4966f980-d0c9-11e9-8985-dd35c02050c0.png)

**Comment by Tyriar** [comment]
The following works for me on Windows:

```
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
  "terminal.integrated.env.windows": {
    "Path": "${env:Path};test"
  }
```

**Comment by SheepDomination** [comment]
@Tyriar 

The `terminal.integrated.shell.windows` setting must be set in either the *workspace.json* file or the *settings.json* file, correct ?  

Although there is a variable set for the `terminal.integrated.env.windows` which points to a path on my computer within in my *workspace* setting; identical to how you would set a system environment variable, but regardless where I am in the path on my computer, in other words, no matter what directory I'm in, like when setting a system environment variable I'm unable to access the program regardless what path I'm in strictly within visual studio code terminal ? 

It's not working identical to that when setting a system environment variable, as I assume it can be setup to behave identical too, eliminating the need to pollute your system environment variable. In other words, no matter what variable is set for `terminal.integrated.env.windows` it behaves the same way as if you set a system environment variable in Windows, so then why can't I access the programs in any of the paths set in this setting regardless what directory I'm in when within the integrated terminal ?

**Comment by Tyriar** [comment]
> Although there is a variable set for the terminal.integrated.env.windows which points to a path on my computer within in my workspace setting

There is a security feature that gives you a popup on whether you allow the *workspace* to modify your terminal, you probably saw/dismissed a notification asking you this. You can allow your workspace by using this command:

<img width="388" alt="Screen Shot 2019-09-13 at 9 56 52 AM" src="https://user-images.githubusercontent.com/2193314/64880346-d7346e80-d60c-11e9-8e4d-a389e1cb7724.png">

**Comment by SheepDomination** [comment]
@Tyriar 
I found what the problem is, hopefully the answer is directly behind it.  

When adding a path to the System Environment variable in Windows, regardless what path I'm in whether in a regular command prompt or terminal in visual studio code; I can access any program within the path which was placed in the System Environment variable with one exception.  The environment variable `${env:PATH}` must be appended to the `PATH` variable in the `terminal.integrated.env.windows` setting.

Is it possible to get the exact same behavior in vscode without appending the variable `${env.PATH}` ? 

I thought that by having the `PATH` variable with the value being the directory within the `terminal.integrated.env.windows` without the variable `${env.PATH}` I could type the program name strictly within terminal in vscode in any path and it would work; although that is not the case even with *Terminal: Manage Workspace Shell Permissions: Enabled*.
