### ISSUE TITLE
VS Code doesn't allow drag and drop files from the File Explorer (MacOs)

### ISSUE THREAD

**Issue by baxgas** [microsoft/vscode#80262]
I want to drag-and-drop files from VSCode window (File Explorer view) to my FTP program (Cyberduck) on MacOS High Sierra, but somehow it doesn't work.

Any idea why, is it a feature or just some settings? (I have all the drag-and-drop settings ticked in the Settings)

![image](https://user-images.githubusercontent.com/36408851/64176375-a2325a00-ce5d-11e9-9461-6c123becf47e.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/164
