### ISSUE TITLE
Outline displays "No Symbols found in document" when using filepath in Markdown file

### ISSUE THREAD

**Issue by bharney0** [microsoft/vscode#80277]
- VSCode Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Create Markdown file with the following content
```
# Outline

Hello world

## Outline Secondary

[!INCLUDE [include-file]()]
```
2. Notice outline is working.
![image](https://user-images.githubusercontent.com/51799435/64196801-7c935980-ce39-11e9-91c9-eb010819aa14.png)
3. Now add file path to last row for include statement
![image](https://user-images.githubusercontent.com/51799435/64196751-671e2f80-ce39-11e9-903a-aa3fbadda792.png)
4. When the file path has been added. The outline stops working. I expected that when using an include statement outline should still show the normal outline output.

Does this issue occur when all extensions are disabled?: Yes
Problem still exists in VSCode Insiders

**Comment by mjbvz** [comment]
I can't repo this

![Screen Shot 2019-09-09 at 10 23 45 AM](https://user-images.githubusercontent.com/12821956/64552367-fa4cde80-d2eb-11e9-8bfe-c6ce81a2cd40.png)

Are you sure you tested on VS Code 1.39 insiders with all extensions disabled?

**Comment by bharney0** [comment]
@mjbvz It seems to work on VS Code 1.39 Insiders. Thanks for looking into it.
