### ISSUE TITLE
Git commit is slow. 

### ISSUE THREAD

**Issue by pr3tori4n** [microsoft/vscode#80279]
It takes around 3-5 seconds to finish the commit. One consequence of this, other than being annoying, is I've added a file, committed, and while the commit is processing I've added another file intended to be a separate commit, but the second add finishes before the first commit, and VSCode commits both files with the same commit message. Can be undone but it's a headache and it's evidence of just how long each commit is taking.

- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:
Using the source control sidebar...
1. add a file that's been modified
2. commit that file with a message

Does this issue occur when all extensions are disabled?: Yes

Notes:
Haven't tested with insider.

**Comment by joaomoreno** [comment]
What about in the Command Prompt? What about inside VS Code's Terminal?

**Comment by pr3tori4n** [comment]
The online terminal (using bash on Windows) works fine. It's only slow when using the UI in the sidebar.

**Comment by joaomoreno** [comment]
What git version do you have installed?

**Comment by pr3tori4n** [comment]
git version 2.21.0.windows.1

**Comment by joaomoreno** [comment]
Are any other operations in VS Code, related to Git, slow? Staging, reverting, etc?

**Comment by DrakeLambert** [comment]
@joaomoreno I have had this same issue. Staging, diffing, and reverting are all slower. @pr3tori4n any updates on your part?

**Comment by RandomShaper** [comment]
For me, general slow Git operations happens too, in big projects (hundreds of files).

What has helped for me has been disabling auto-save completely and saving manually (prior, I had auto-save on focus change).
