### ISSUE TITLE
File not synching between duplicate workspaces

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#80275]
@momori790 commented on [Thu Aug 29 2019](https://github.com/microsoft/vscode-python/issues/7149)

## Environment data

- VS Code version: 1.37.1
- Extension version (available under the Extensions sidebar): Python: 2019.8.30787
- OS and version: Mac OS Mojave 10.14.5
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.3 Anaconda
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/a
- Relevant/affected Python packages and their versions: N/a
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): N/a

## Expected behaviour

file changes to be reflected between different windows of duplicate workspaces

## Actual behaviour

files changes are not reflected

## Steps to reproduce:
1. Open a folder and create two files: `func.py` and `test.py`

2. in `func.py`, add the lines:
```python
    #%%
    def run_test():
        return 'a' 
```
3. in `test.py`, add the lines:
```python
    #%%
    from func import run_test
    run_test()
```
4. save both files, and open new workspace by `Duplicate Workspace in new Window` command.  

5. in the first window, open `func.py` and in the second window, open `test.py`

6.  Run the cell in `test.py` by `cmd+shift` (in Mac OS) to get the expected output `a`.

7. Change the content of `func.py` in the first window to `return 'b'`. Save the file.

8.  When step 6 is repeated, I expect the output to be `b` but  I still get `a`.  

---

@gramster commented on [Fri Aug 30 2019](https://github.com/microsoft/vscode-python/issues/7149#issuecomment-526747228)

Thanks for reporting this. This seems like Visual Studio Code issue rather than a Python-specific issue but we will take a look.

---

@momori790 commented on [Fri Aug 30 2019](https://github.com/microsoft/vscode-python/issues/7149#issuecomment-526761699)

Thanks @gramster.  Would you recommend I cross-post it in Visual Studio Code also?

**Comment by momori790** [comment]
Hi @sbatten, was wondering if you had a chance to look at this.  Thanks for your time

**Comment by sbatten** [comment]
@karrtikr I tried to reproduce this and noticed that the issue as described does not require the second window. That being said, it appears this is by design and you need to run the command `Restart IPython Kernel` to refresh the imported function.
