### ISSUE TITLE
[bash] Variable is not highlighted in heredoc

### ISSUE THREAD

**Issue by Ash258** [microsoft/vscode#80270]
Issue Type: <b>Bug</b>

```bash
#!/bin/bash
variable='whatever'
cat << END
<prtg>
	<result>
		<Channel>Memory usage</Channel>
		<Value>$variable</Value>
	</result>
</prtg>
echo "$variable"
END
```

Variable substitution is supported inside heredoc and variables should be highlighted as in normal string.

![image](https://user-images.githubusercontent.com/13260377/64189738-2cd28380-ce75-11e9-84c7-8c2ae0918d93.png)

![image](https://user-images.githubusercontent.com/13260377/64189631-f1d05000-ce74-11e9-8097-be76e9db044c.png)

Bat output for comparison:

![image](https://user-images.githubusercontent.com/13260377/64198350-5ea11580-ce88-11e9-8c97-01dab25aa9b8.png)

VS Code version: Code - Insiders 1.38.0-insider (0f73473c08055054f317c1c94502f7f39fdbb164, 2019-08-23T05:39:22.818Z)
OS version: Windows_NT x64 10.0.18362
Bash version: 4.4.23(1)-release

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
Moved to the owning repo: https://github.com/atom/language-shellscript/issues/151
