### ISSUE TITLE
IntelliSense based on type inference not working in node_modules?

### ISSUE THREAD

**Issue by guidorice** [Microsoft/vscode#8027]
- VSCode Version: 1.2.1
- OS Version: OS X 10.9.5

According to the vscode docs, 

> IntelliSense based on type inference  .... ES3-style classes, specified using a constructor function and assignments to the prototype property. CommonJS-style module patterns, specified as property assignments on the exports object, or assignments to the module.exports property.

It seems in my experiments, the intellisense does not work in the case of commonjs modules being loaded from node_modules.

Steps to Reproduce:

* mkdir vscode-test
* cd vscode-test/
* code .
* create jsconfig.json

```
{
    "compilerOptions": {
        "target": "ES6"
    }
}

```
According to the docs,  this jsconfig.json file is implicitly saying that the JS project context should be all files beneath the vscode-test directory.

* create test.js

```
var lodash = require('lodash');
console.log(lodash);
```

* npm install lodash 
* vscode `cmd-> reload javascript project`
* `node test.js`  to confirm the module is being loaded
* hover over var lodash in test.js, and see it has no type inference and no intellisense.

lodash is perhaps not the best example, because there are definite typings available for lodash, and it would be more expedient to just do like:` typings install lodash `-- problem solved. However there are lots of other javascript modules that don't have typings. For example:

`npm install tnt.tree` (tnt.tree part of the biojs suite of modules). This is the one where I first noticed this problem.

Also realize in practice, one normally add node_modules to the exclude list in jsconfig.json. In summary there seems to be no way to get the type inference and intellisense working on (selected) js libraries installed via npm into node_modules.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9323

**Comment by dbaeumer** [comment]
Moving to the TS team.
