### ISSUE TITLE
Open readme.md on "Add folder to workspace..."

### ISSUE THREAD

**Issue by robertlugg** [microsoft/vscode#80282]
I don't believe this is a duplicate.

For just a bit of flash, when I add a folder to the workspace, and if the folder has a readme.md file, open that file.  It's sort of like a title page for the folder.

I'm sure this needs to be on a settings switch.

**Comment by robertlugg** [comment]
It is not a duplicate of #77350

**Comment by isidorn** [comment]
This can be done via an extension. It should simply listen to [`onDidChangeWorkspaceFolders`](https://github.com/Microsoft/vscode/blob/166ad253efbd77f88ae44834ef878ab0b6092cbd/src/vs/vscode.d.ts#L7709) and when a new workspace gets added it should simply open a readme.md file.
