### ISSUE TITLE
Change application icon to indicate notifications are present

### ISSUE THREAD

**Issue by SteveBenz** [microsoft/vscode#80286]
For the duration of the presence of a notification on the VSCode screen, VSCode's icon should be changed to indicate that the notification exists.  (Like a mail reader's icon changes in the task bar when you have e-mail.)

In issue #80285 , I also suggest that notifications that happen while VSCode is not in focused should not disappear until 15 seconds after VSCode comes into focus.

The point of this is to enable VSCode extensions that monitor for events outside of VSCode - e.g. a pull request or a work item being assigned to the user, or somebody pushing code to the branch that the user is working on.

**Comment by angelhdz** [comment]
Add this at the start of this issue's title:  **[FEATURE REQUEST]**

Cheers!

**Comment by SteveBenz** [comment]
@bpasero - we might be committed enough to this idea to contribute the code ourselves.  If we did that, would you be receptive to it?

**Comment by bpasero** [comment]
Thanks for the offer, but currently not. We appreciate help for issues marked as "[help wanted](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)" or "[good first issue](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+)". 

Note that meanwhile, I pushed a change that notifications will remain visible when the window has no focus, even from extensions.
