### ISSUE TITLE
Extensions can potentially block autocompletion from other extensions

### ISSUE THREAD

**Issue by pavelvlasov** [microsoft/vscode#80295]
TabNine VSCode plugin suppresses suggestions from other extensions. It's described in

https://github.com/zxqfl/tabnine-vscode/issues/6
https://github.com/zxqfl/tabnine-vscode/issues/20

The root cause is described in the comment https://github.com/zxqfl/tabnine-vscode/issues/6#issuecomment-437712095

My feeling that it should be fixed inside VSCode, rather than in the plugin to prevent this behavior for other extensions as well.

- VSCode Version: all versions
- OS Version: all versions

Steps to Reproduce:

1. Install [TabNine extension](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode)
2. Suggestions from other extensions stop working

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
> My feeling that it should be fixed inside VSCode,

Do you also know how? When an extension errors then we don't prevent completions, but when extensions never return a result we do (after what timeout should we stop). Then for trigger characters it gets more tricky. There is a pretty clear note in the docs: https://github.com/microsoft/vscode/blob/bd79c20ac85d44a42d28defb6aa280d5e9ab066b/src/vs/vscode.d.ts#L8167-L8170. Only triggering providers when their character is being hit still seems correct to me and I think disabling certain characters is fair. Remains the question if a trigger that's also a word character should re-trigger suggest?

**Comment by pavelvlasov** [comment]
@jrieken thanks for getting back.
I'm not pretty sure what happens in this particular case.
I still would expect completions from other extensions to show up, even if trigger characters are defined as the whole alphabet. It also would be pretty hard to draw the line on what characters should be whitelisted.

Are you aware of what is the root cause of the problem?

**Comment by jrieken** [comment]
> Are you aware of what is the root cause of the problem?

Yes, I tried to explain that here: https://github.com/microsoft/vscode/issues/80295#issuecomment-528232991.

**Comment by pavelvlasov** [comment]
@jrieken I don't think I have enough context about the problem. Do you have somebody in mind who can be pulled into a discussion?
