### ISSUE TITLE
[Feature Request] snippet support RANDOM

### ISSUE THREAD

**Issue by seognil** [microsoft/vscode#80297]
[use case]  
`console.log('#45dlk5', $1)`  
generate a simple random string as a quick debug flag

[feature request]  
add a $RANDOM varible to snippet  
or support JS expression as ES6 did  
e.g. ``  `${Math.random().toString(36).slice(-6)}` => '45dlk5'  ``

**Comment by skprabhanjan** [comment]
@jrieken , I can take this up but need some starter and code pointers for this :) 
I just need some more understanding as we can do something like this
console.log(`${Math.random().toString(36).slice(-6)}`,$1);

**Comment by moki298** [comment]
Is this still open? Can I take this?

**Comment by jrieken** [comment]
Go for it. Code pointer: https://github.com/microsoft/vscode/blob/0fc92f222f9b7007240583c090d5c2c748d91938/src/vs/editor/contrib/snippet/snippetVariables.ts#L230

**Comment by alk4do** [comment]
### 

> _****_
