### ISSUE TITLE
On change branch alert about uncommited files

### ISSUE THREAD

**Issue by Kempriol** [microsoft/vscode#80298]
Issue Type: <b>Bug</b>

If I change a file in branch Develope and switch to another branch (Feature/new) - VSCode don't alert me about uncommited changes and I can commit it in another branch, i think It's wrong

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Can you provide details steps on how I can reproduce this?

**Comment by Kempriol** [comment]
Ex:
1) Develop branch. Make change in test.html file and save them
2) Change branch to Master and commit/push
3) Now test.html in Develop will be lost changes - I'll think it's strange

**Comment by joaomoreno** [comment]
That's how git works. This is not a bug.
