### ISSUE TITLE
Closing parenthesis keeps repeating

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode#80294]
Issue Type: <b>Bug</b>

1. Type a `(`. Watch it auto close.
2. Type a `)`. The cursor skips over the existing `)`.
3. Move cursor back in between the parentheses.
4. Type a `)` again. The `)` gets repeated.

I'm sure the behaviour on previous vscode versions was to always skip over the existing parenthesis. I've tried with `editor.autoClosingBrackets` `languageDefined` and `always`. This is in typescript but I see it in other languages too.

![closing_parenthesis](https://user-images.githubusercontent.com/5885195/64218019-415d5d00-cf03-11e9-9574-3865596ced9f.gif)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.2
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
vsc-material-theme|Equ|30.0.0
vscode-docker|ms-|0.7.0
csharp|ms-|1.21.1
ayu|tea|0.18.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate of #78833. Behaviour changed in 1.37. A config option in 1.38 allows you to reinstate previous behaviour.
