### ISSUE TITLE
Snap store says licence is "Proprietary"

### ISSUE THREAD

**Issue by trampster** [microsoft/vscode#80291]
The [snap store](https://snapcraft.io/code) says the licence for vscode is "Proprietary" but it's actually MIT.

**Comment by stfuzz** [comment]
I think it is not the OSS version of VS Code as it uses proprietary telemetry services by Microsoft as you can read in the description.

See https://www.vscodium.com/ for good explanation and binaries licensed under MIT:
> Microsoft’s vscode source code is open source (MIT-licensed), but the the product available for download (Visual Studio Code) is licensed under [this not-FLOSS license](https://code.visualstudio.com/license) and contains telemetry/tracking.

**Comment by stfuzz** [comment]
You can find vscodium in the snap store here: https://snapcraft.io/vscodium
I think you can close this issue

**Comment by trampster** [comment]
Oh I see, the 'almost' opensource Microsoft strategy.

**Comment by stfuzz** [comment]
> 
> 
> Oh I see, the 'almost' opensource Microsoft strategy.

Indeed 😄
