### ISSUE TITLE
TypeScript auto-complete only shows JSDoc for first function overload

### ISSUE THREAD

**Issue by ericyhwang** [microsoft/vscode#80292]
Issue Type: <b>Bug</b>

**Steps:**

1. Paste this into a TypeScript file:

```typescript
/** 5-arg overload */
function add(a: number, b: number, c: number, d: number, e: number): number;
function add(a: number, b: number, c: number, d: number): number;
/** 3-arg overload */
function add(a: number, b: number, c: number): number;
function add(a: number, b: number): number;
function add(...numbers: number[]) {
  let total = 0;
  for (const num of numbers) {
    total += num;
  }
  return total;
}
add(1, 2, 3, 4);
```

2. Start typing `add(` at the bottom to bring up auto-complete, then hit the Down arrow to go to the second overload.

**Expected:** The auto-complete for the second overload shows docs from the doc-comment, same as it did the first overload.

**Actual:** The auto-complete for the second overload does not show docs.

**Additional note:** If you hover over the fully completed `add(1, 2, 3, 4);`, which is an overload without a doc-comment, it mostly works, showing a merged version "5-arg overload 3-arg overload". This behavior is totally OK for functions where there's one single doc-block above all overloads, it's just a bit odd in the case where you document 2+ overloads but not all of them.

VS Code version: Code - Insiders 1.38.0-insider (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T23:11:54.533Z)
OS version: Darwin x64 18.7.0

Extensions: none

**Comment by ericyhwang** [comment]
I did a bit more searching of issues, and I noticed a lot of VS Code issues were re-filed upstream on TypeScript.

So I did some searching there and found two relevant issues:
* https://github.com/microsoft/TypeScript/issues/27981
* https://github.com/microsoft/TypeScript/issues/30181

For the second issue, it looks like there's a PR open: https://github.com/microsoft/TypeScript/pull/30253

I'm not sure if the vscode project's policy is to leave issues open until TypeScript fixes are merged, so I'll leave it up to a maintainer to decide whether to close this one or not.

**Comment by mjbvz** [comment]
Closing as upstream
