### ISSUE TITLE
Update check reports no updates available when unable to access internet

### ISSUE THREAD

**Issue by knoxyca** [Microsoft/vscode#8029]
- VSCode Version: 1.1.1 (and: insider 1.3.0)
- OS Version: Windows 10 Enterprise 1511 OS Build 10586.318

Steps to Reproduce:

1. Open Visual Studio Code with no network connection
2. Select Help > Check for updates
3. Receive message: "There are no updates currently available."

**Comment by joaomoreno** [comment]
They will be available once network connection is available.

**Comment by knoxyca** [comment]
It also reports all is well when there is a "next generation" firewall doing deep packet inspection on the https connections. This prevents updates from happening automatically within some corporate environments.

**Comment by joaomoreno** [comment]
Did you configure your proxy settings in the `http.proxy` configuration setting?

**Comment by knoxyca** [comment]
There is no proxy to configure. The firewall sits as the default gateway and decrypts the https traffic and resigns it with its certificate (that is issued by our domains CA that is trusted by all domain computers). It appears that vscode is either either ignoring the results because it doesn't trust the cert, or the firewall is blocking the check. I don't believe it's the firewall as the logs indicate nothing is blocked. Where does vscode look for updates?

**Comment by joaomoreno** [comment]
`vscode-update.azurewebsites.net` is the domain.

**Comment by knoxyca** [comment]
That's probably why we haven't whitelisted it. I'll try setting: http.proxyStrictSSL first, then ask our networking team to whitelist the domain. Will report back.

**Comment by joaomoreno** [comment]
Thanks!

**Comment by knoxyca** [comment]
Looks like I already had "http.proxyStrictSSL": false in my user configuration. However, as soon as vscode-update.azurewebsites.net is whitelisted in the firewall both insider build and production build prompted me to install updates.
