### ISSUE TITLE
dart command is not recognized suddenly

### ISSUE THREAD

**Issue by amitanubha** [microsoft/vscode#80299]
Create a flutter project and sismpy try to run and it says error dart is not recognized as internal or external command though all PATH settings are correct.

**Comment by amitanubha** [comment]
nope it is not resolved or covered

**Comment by sbatten** [comment]
@amitanubha if you type dart in the integrated terminal, does this resolve to a valid command?

**Comment by DanTup** [comment]
I think this issue has been resolved -> https://github.com/Dart-Code/Dart-Code/issues/1966.
