### ISSUE TITLE
Smoketest remote: Multiroot test fails with no search results

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#80304]
Ubuntu 18.04 LTS

- `yarn smoketest --remote --build /home/aeschli/vscode/1.38.0-insider-3db7e09f3b/VSCode-linux-x64/

Multi root test fails, no search result found

![image](https://user-images.githubusercontent.com/6461412/64238197-3d7b0c00-cefe-11e9-9f4b-18cf644fea53.png)

Same when running against source or on Windows.

Typing a space in the quick input box shows the result, so it looks like a timing issue.

**Comment by roblourens** [comment]
Is there a way for the test to wait until the window is connected before triggering the search?

**Comment by roblourens** [comment]
@aeschli I am now looking at the text of the status bar item to tell whether the window is actually connected. Let me know if that's not ok.

**Comment by roblourens** [comment]
We could also add a class/id to that item.
