### ISSUE TITLE
In search panel "files to include", "*.ts" doesn't search all ts files, but "**/*.ts".

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#8030]
- VSCode Version:1.2.1
- OS Version:windows 8.1

In this version of vscode, search "\*.ts" not search all the ts files in project, I need type "\*\*/\*.ts".
I believe in the previous version , I can use "\*.ts".

**Comment by fantacytyx** [comment]
If I remember correctly, since the first edition is such.

**Comment by heroboy** [comment]
I test it in 
```
Version 1.3.0-insider
Commit 2481a7dad82f8e8d105c5329b4b6f20e15e9b27c
Date 2016-06-08T02:08:12.105Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
It can use "*.ts"

**Comment by sandy081** [comment]
@heroboy I see this is working in latest insiders - de66522e06d74752d48d92e934dcd026050355ba

Can you please check again and let me know.

Thanks.

**Comment by heroboy** [comment]
@sandy081 
```
Version 1.3.0-insider
Commit de66522e06d74752d48d92e934dcd026050355ba
Date 2016-06-24T05:07:35.941Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
This can use "*.ts". I think all insider verions has fixed this issue.

**Comment by sandy081** [comment]
Thanks for confirming. Closing this.

**Comment by sandy081** [comment]
@heroboy It works for me on latest insiders and stable build. 

![screen shot 2016-07-08 at 10 38 33 am](https://cloud.githubusercontent.com/assets/10746682/16681976/32414482-44f8-11e6-8f20-0edfc5671413.png)

Can you please check your search criteria if you have additional expressions than expected.

Thanks

**Comment by heroboy** [comment]
@sandy081,
Sorry, I checked it again,and found that I checked the "use glob patterns".
I just supposed the icon was used to show the glob patterns help tip.
Sorry again, my fault.
