### ISSUE TITLE
The warning about deleting file under version control is too strong / unnecessary

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#80309]
When I'm about to delete a file **that is version-controlled** in my project, I get this warning:

> Are you sure you want to permanently delete 'some-file.txt'? This action is irreversible!

<img width="429" alt="Screenshot 2019-09-04 at 11 31 54" src="https://user-images.githubusercontent.com/101152/64243647-fabe3180-cf07-11e9-9fad-5fa008ccbffb.png">

I think it is too strong – in fact, it's technically wrong (the action _is_ reversible).

I'm not sure if the UX is intentionally so cautious or if this is a VSCode bug where it doesn't detect correctly that a file is version-controlled. Or maybe it doesn't take VCS into account at all?

---

**UPDATE**: after some discussion below, this issue is a feature request about taking VCS into account when deciding whether to display the prompt or not.

**Comment by isidorn** [comment]
We have some novice users that easily delete their files. Due to that we are a bit too cautios with all delete dialogs. 
And yes we do not take VCS into account at all.

Though leaving this open as a feature request for now.

**Comment by borekb** [comment]
Thanks, I am aware of issues like https://github.com/microsoft/vscode/issues/32405 or https://github.com/microsoft/vscode/issues/32459 😄.

By the way, does `explorer.confirmDelete` influence whether I see this dialog or not? I had it set to `false` for a very long time and don't remember seeing this dialog before July 2019 version of VSCode – has something changed recently?

**Comment by isidorn** [comment]
@borekb that sounds like a bug. If `explorer.confirmDelete` is set to false, we shuold never ask.

I can not reproduce the behavior you are saying. Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes do you have something special about your workspace?

**Comment by borekb** [comment]
Insiders behaves the same.

I found out why I'm seeing the prompt now and don't remember seeing it in the past: it's because a few weeks ago, I added `"files.enableTrash": false` to my settings and **this combination leads to a prompt**:

```json
{
  "files.enableTrash": false,
  "explorer.confirmDelete": false
}
```

That's probably expected (although a gray area, IMO; I'm more on your side with "If `explorer.confirmDelete` is set to false, VSCode should never ask").

So as you said, this issue is really a feature request to take VCS into account.

**Comment by isidorn** [comment]
Makes sense. Let's leave this open for now to gather more user feedback.
Though I feel like these two options are unrelated, and if the confirm delete is false it should never ask no matter if you have trash scm or whatnot.

**Comment by borekb** [comment]
Do you think it's worth creating a separate issue about the `confirmDelete` and `enableTrash` interaction? I thought I'd ask first because VSCode has enough open issues already 😄.

**Comment by isidorn** [comment]
I think just this one is fine for now. Thanks

**Comment by james-innes** [comment]
This has become quite annoying now when trying to use code server tunnelling on a linux VM for development. One expects the synced user settings for `confirmDelete : false` to be respected. There may be a technical rationale but the fundamental UX doesn't feel right.

**Comment by jackallard** [comment]
I saw this message and continued thinking it would keep my local files, although I now can't find them. If you say it's reversible and too strict, please can I know how indeed to reverse it. Note that my files were not previously stored on a git repository as that's what I was trying to do (but encountered various VSC/git issues. Thanks :)

**Comment by muhammadyaqoobmuet** [comment]
how do i recover that files after delete😢

**Comment by jackallard** [comment]
> how do i recover that files after delete😢

Hi, im not sure if it's helpful for you but I recovered my files by using vsc's own file recovery fail safe (it's been a while I can't remember the name) but it's a window within vsc that shows all your previously saved files (even if they've been deleted/removed). Other than that, check the recycle bin (although I appreciate git works differently to locally-stored files.

**Comment by muhammadyaqoobmuet** [comment]
I tried a lot, but I could not figure it out. It was my 30 days of consistent hard work learning JavaScript, and I am starting all over again

**Comment by XuebinZhaoZXB** [comment]
> I tried a lot, but I could not figure it out. It was my 30 days of consistent hard work learning JavaScript, and I am starting all over again

I accidentally did a similar thing today. Do you have any solutions for this?
I got something that uses vscode local history to recover some files: https://bobbyhadz.com/blog/view-vscode-local-history#finding-and-restoring-files-that-youve-already-deleted
