### ISSUE TITLE
Keyboard shortcuts for "Dvorak, right-handed" keyboard layout are mapped to "Dvorak" keyboard layout

### ISSUE THREAD

**Issue by ghanique** [microsoft/vscode#80301]
Issue Type: <b>Bug</b>

Problem situation
===
I recently broke my left arm. In order to be able to type reasonably fast I selected the "Dvorak, right-handed" keyboard layout.

I use VS Code on Fedora 30.

Problem description
===

Test 1 (OK)
---

### Setup
When editing a file press the physical key that is marked with ",".

### Expected
The character "v" appears, because the with the "Dvorak, right-handed" keyboard layout the comma key is mapped to the letter "v".

### Actual
The character "v" appears.

Test 2 (Fail)
---

### Setup
When editing a file select some text, with the mouse right-click the selected text and select "Copy".
Press Ctrl and the physical key that is marked with ",".

### Expected
The copied text is pasted, because the with the "Dvorak, right-handed" keyboard layout the comma key is mapped to the letter "v" and Ctrl-V triggers the Paste command.

### Actual
The file that you were editing is closed, because the with the **"Dvorak"** keyboard layout the comma key is mapped to the letter "w" and Ctrl-W triggers the Close Window command.

### Cause
For handling shortcuts VS Code incorrectly assumes that the "Dvorak" keyboard layout is used, possibly because "Dvorak, right-handed" starts with "Dvorak".

### Result
It is nearly impossible to use keyboard shortcuts in VS Code when using the "Dvorak, right-handed" keyboard layout.

Thx for looking into this issue!

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.2.9-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1657)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.55GB (0.58GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ghanique** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [[Linux] Keyboard shortcuts do not update when keyboard mappings change for system (#55381)](https://www.github.com/microsoft/vscode/issues/55381)

This is a different issue.

**Comment by rebornix** [comment]
I didn't reproduce this issue on macOS so likely a linux specific issue.

**Comment by rebornix** [comment]
@ghanique could you please run "Developer: Inspect Key Mapping (JSON)" from command palette and provide the data to help troubleshoot?
