### ISSUE TITLE
unable to open same directory in new window from shell

### ISSUE THREAD

**Issue by merveillevaneck** [microsoft/vscode#80314]
- VSCode Version: 1.37.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. open a non-empty project (current working dir) using the code command eg 'code . ' (it opens normally in a new window)
2. try opening the same directory again, while the first window is still open, with the -n option eg 'code -n . ' (should open a new window but jumps focus back to the first instance)

Does this issue occur when all extensions are disabled?: Yes

**Comment by merveillevaneck** [comment]
additionally, when two windows happen to be open and one attempts to open a project directory in window B that is already open in window A, then focus will change instead of simply opening the same directory in two separate windows of the editor.

**Comment by sbatten** [comment]
@merveillevaneck There is a command `Duplicate workspace in new window` that solves this issue.

@bpasero for additional info.
