### ISSUE TITLE
Close all folders and subfolders on a single click

### ISSUE THREAD

**Issue by whyseman** [microsoft/vscode#80313]
It would be nice if there was a button or a command that would close all opened folders and subfolders in a workspace. I have multiple **large projects** and sometimes I want to **close all of the folders and subfolders** that were opened during the development in a single click. Because right now, I have to close every single subfolder in the tree in order to close all of the subfolders and folders.

Example:
- You have opened multiple folders and subfolders in your workspace during the development. And now you want to close them all at once so that no folder or subfolder is opened. Like you just started a new project with multiple folders and subfolders and none of them were opened previously.
- You have a button or a command that will close all of the opened folders and subfolders.

### Before
![Before](https://user-images.githubusercontent.com/12301022/64249361-c7819f80-cf13-11e9-8b38-3ee8e0bd467b.png)

### After
![After](https://user-images.githubusercontent.com/12301022/64249375-cea8ad80-cf13-11e9-8d5f-84e0ae49f0e1.png)

**Comment by sbatten** [comment]
is "After" what you are trying to achieve? if so I think you want this button,

![image](https://user-images.githubusercontent.com/6561887/64277872-3d7c0b80-cf00-11e9-88a3-0c7c5247a388.png)

**Comment by whyseman** [comment]
OMG yes! I had no idea that there is already a button for my issue! Thanks!
