### ISSUE TITLE
Add command deprecation

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8031]
Instead of just changing command names, we should slowly phase them out and presenting warnings if the old ones are being relied upon and direct users to the new commands. Adjusting to https://github.com/Microsoft/vscode/issues/6605#issue-156087140 may be easier that way, not totally destroying any custom keybindings and informing the user in a visible way of the change without the need to read the release notes.

This would also allow any clean up of command names to be done with a smaller impact to the end user.

**Comment by bpasero** [comment]
Actually maybe we could register all the old command ids and just show a message to the user telling him the new identifier of this command!

**Comment by Tyriar** [comment]
Great! Something like that is what I had in mind :+1:

**Comment by bpasero** [comment]
@Tyriar assigning to you for verification.

**Comment by Tyriar** [comment]
Thanks for putting this together!
