### ISSUE TITLE
Setting contrastActiveBorder in themes breaks "Select Interpreter" panel

### ISSUE THREAD

**Issue by sleighsoft** [microsoft/vscode#80316]
See https://github.com/microsoft/vscode-python/issues/7140

**Comment by sbatten** [comment]
after looking, there might be an issue with theming in the command palette?

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode/issues/78887

**Comment by chrmarti** [comment]
Fixed as #84062
