### ISSUE TITLE
Go to definition + Right-Click-Menu

### ISSUE THREAD

**Issue by St3fa11** [microsoft/vscode#80318]
Issue Type: <b>Bug</b>

I cannot use the F12 command -> Go to definition
-> nothing happens

Also there aren't any right-click menu entries like "got to definition"; "peek definition"; "got to declaration"  and so on anymore

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (25.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
code-runner|for|0.9.14
theme-monokai-pro-vscode|mon|1.1.14
csharp|ms-|1.21.1
sublime-keybindings|ms-|4.0.3
team|ms-|1.149.2
material-icon-theme|PKi|3.9.0
go-to-method|tri|0.1.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Can you provide more details? At least what language are you using? Do you use extension that should provide this functionality for language (there is built-in support for JS/TS, but other might need an extension)?

**Comment by St3fa11** [comment]
> 
> 
> /needsMoreInfo
> 
> Can you provide more details? At least what language are you using? Do you use extension that should provide this functionality for language (there is built-in support for JS/TS, but other might need an extension)?

Hello IllusionMH,

i program in C and use the C/C++ for Visual Studio Code extension from Microsoft.
I also check the topics from bot above. But I found no help to solve my issue.

**Comment by sbatten** [comment]
@St3fa11 looking at the extensions listed in your bug report, I don't see the C++ extension installed

**Comment by St3fa11** [comment]
> @St3fa11 looking at the extensions listed in your bug report, I don't see the C++ extension installed

Thanks for the attention to this point.
Somehow the extension was deinstalled. After installing it again the editor works as before.

How is this possible? I didn't deinstalled it, because I need it for my daily work.
This is very weird. That's why I also didn't check my extensions and ask for help.

Lead the automatic update function in VSCode to this?

Big thanks for the help.

**Comment by sbatten** [comment]
@St3fa11 I am not sure what could have caused the extension to be uninstalled after updating, but without a repro, it will be very hard to discover. 

cc @joaomoreno and @sandy081 for awareness, but without additional reports, I don't think we will have any action.
