### ISSUE TITLE
Feature Request: Allow file rename when not open in folder

### ISSUE THREAD

**Issue by j-Curioso** [microsoft/vscode#80321]
To start, first time opening a feature request on Github. I did look through existing issues/requests, and also through VS Code itself, but did not find anything for this specifically. Happy to be corrected and pointed in the right direction.

It would be appreciated if there was a way to rename an open file when the file's folder is not open. Often through out the day I will be working in many different locations, and won't always have the folder open, but occasionally need to rename a file. No problem to close it, rename it in explorer, and reopen, but this seems like something that could be easily added to the editor.

Thanks for listening, been really impressed with this product since its release.

**Comment by j-Curioso** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [renaming file in explorer not working (#75643)](https://www.github.com/microsoft/vscode/issues/75643)

Pretty cool bot. Unfortunately the linked issue is not a duplicate. Their issue appears to be with renaming not working when the file is open in an opened folder.

My request would be to rename a file when the file is not already opened in a folder.

**Comment by isidorn** [comment]
This could be implemented by an extension.
The extension should simply contribute the command "Rename File" in the command palette. And then the user can rename the file without opening the file explorer.
