### ISSUE TITLE
vscode doesn't recognize javascript inside html file

### ISSUE THREAD

**Issue by ederluca** [microsoft/vscode#80322]
Good Morning
One question I am using vscode in php development and I really liked the tool, but I came across a problem and could not get around it:

When I am inside a javascript document and type for example document. The properties I can use appear.

But when I am in a <script> tag in an html file and type for example document. Nothing appears to me as I do to enable this feature?

Linux Mint 19 64-bit Operating System
Vscode Version: 1.37

**Comment by octref** [comment]
Are you sure it's a HTML file? This should work out of the box.
![Screen Shot 2019-09-04 at 10 35 34 AM](https://user-images.githubusercontent.com/4033249/64277663-c0e92d00-ceff-11e9-8df9-20d0dc7f7134.png)

It's probably your PHP extension interfering. Try disable it.

**Comment by ederluca** [comment]
Actually it was a mistake on my part the file is a php file I did the test as you mentioned and actually the html file inside the <script> tag works but when the file is php it only works if I go to the program footer and change it to javascript then he recognizes

**Comment by ederluca** [comment]
Actually it was a mistake on my part the file is a php file I did the test as you mentioned and actually the html file inside the <script> tag works but when the file is php it only works if I go to the program footer and change it to javascript then he recognizes

**Comment by ederluca** [comment]
Actually it was a mistake on my part the file is a php file I did the test as you mentioned and actually the html file inside the <script> tag works but when the file is php it only works if I go to the program footer and change it to javascript then he recognizes

Any idea?

**Comment by octref** [comment]
Please open issue for the PHP extension you are using.
