### ISSUE TITLE
editor format configure

### ISSUE THREAD

**Issue by beliefgp** [Microsoft/vscode#8032]
- VSCode Version: 1.2.1
- OS Version: OSX

const a = require('a');
const bb = require('b');
const ccc = require('c');

use editor format, i want to

const a&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=  require('a');
const bb&nbsp;&nbsp;&nbsp;&nbsp;=  require('b');
const ccc&nbsp;&nbsp;=  require('c');

Can configure it?

**Comment by fantacytyx** [comment]
you can use the extension ‘Align’

**Comment by dbaeumer** [comment]
@beliefgp this is currently not support. If you need this, please file an feature request here https://github.com/Microsoft/TypeScript which provides JS and TS formatting for VS Code.
