### ISSUE TITLE
Uninstall extension button text incomplete

### ISSUE THREAD

**Issue by fantacytyx** [Microsoft/vscode#8033]
- VSCode Version: 1.3.0-insiders 2016-06-23T05:07:59.360Z
- OS Version: window 10

Steps to Reproduce:

1. open extension manage,choose one
2. Uninstall extension button text incomplete

![image](https://cloud.githubusercontent.com/assets/8966236/16293407/41040106-394c-11e6-911f-c1d00ecd54c7.png)

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/8034

**Comment by joaomoreno** [comment]
Thanks, @rebornix
