### ISSUE TITLE
Gap in right side of window

### ISSUE THREAD

**Issue by PogromistDev** [microsoft/vscode#80336]
- VSCode Version: 1.38.0
- OS Version: Windows 10 (1803)

Steps to Reproduce:
1. Hide Activity Bar
2. Move Side Bar to right side
3. Play with hiding/showing Side Bar

![vscode](https://user-images.githubusercontent.com/12221569/64291753-f894bb00-cf79-11e9-8391-b120986d5f02.PNG)

**Comment by sbatten** [comment]
@PogromistDev when this happens, does it "stick" or is it temporary while toggling the sidebar?

**Comment by sbatten** [comment]
nevermind, I can reproduce. the bugginess is dependent on the viewlet being shown. Explorer is indeed the worst. SCM doesn't seem to have the issue. Extensions viewlet is "temporary". Investigating...

**Comment by PogromistDev** [comment]
@sbatten it's like it shifts whole vscode interface to the right.

**Comment by sbatten** [comment]
fixed by https://github.com/microsoft/vscode/commit/2da473b000eb514669722f833498e872c46c446f
