### ISSUE TITLE
Reset trusted domains list for link protection

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#80333]
Issue Type: <b>Feature Request</b>

Please allow us to delete trusted domains for link protection.

Selecting a domain and hitting Backspace and Delete don't do anything.

Even better would be to have an option to reset the list of links.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

**Comment by octref** [comment]
If you run `Configure Trusted Domains`, you can toggle off domains to delete them. Does that not work for you?

**Comment by garyking** [comment]
Okay thanks, that does indeed work. I thought it would just be a simple toggle.

Where it this data located? It would be nice to have it as an array in the VSC `settings.json`, like most of the other permanent settings.

**Comment by octref** [comment]
@garyking For security purposes, we decided to not put it in `settings.json`, which is writable by any extensions.

**Comment by garyking** [comment]
Is there any way to reset the list, other than doing it manually?

**Comment by octref** [comment]
Double click the upper left checkbox should unselect all — or do you want reset instead of clear?

**Comment by garyking** [comment]
I would like an option to reset the list, so that if I added a bunch of custom URLs, then resetting the list would remove my custom URLs, and re-add any of the default URLs that I removed, if any.

**Comment by octref** [comment]
See https://github.com/microsoft/vscode/issues/80595#issuecomment-531607624
