### ISSUE TITLE
Change visible ranges

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#80332]
I see `visibleRanges: Range[]` as property. I'd like if I can change this value programatically.

**Comment by usernamehw** [comment]
You can use `cursorMove` or `editorScroll` or `revealLine`

https://code.visualstudio.com/api/references/commands

**Comment by selfrefactor** [comment]
Thank you so much. That might solve it for me.

**Comment by rebornix** [comment]
Solutions proposed above already.
