### ISSUE TITLE
Quickopen history is missing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80334]
- Open a file
- Open quick open, that file should be at the top of "Recently opened", but it isn't

**Comment by rynjwssl** [comment]
I noticed the same behavior today after updating. Went through my settings and `Search > Quick Open > Include History` is enabled. This is my primary method for navigating through multiple files.

**Comment by roblourens** [comment]
Found a fix to get it into the next insiders. @bpasero please look at 3ba84a8c070b1abcdcb6ca64f2dd6dfd48709078

**Comment by bpasero** [comment]
@roblourens thanks, I am not sure what I was thinking there, this strict property work is already causing bugs. I will probably revert that change altogether because it seems quite risky to me to always work on a different history object...

**Comment by rynjwssl** [comment]
Looks like the latest update fixed it. Thanks for addressing this so quickly!
