### ISSUE TITLE
Provide a filter for changes (staged or unstaged) in Git viewlet

### ISSUE THREAD

**Issue by c5inco** [microsoft/vscode#80346]
I think it would be cool to provide a way to quickly filter changes in the Git viewlet to make it easier to stage/unstage/undo specific changes.

I know there are ways to add and remove with patterns and filters on command line, but sometimes I run into situations where there are lots of changes and using patterns isn't always super helpful or intuitive to sift through everything.  I'd prefer a simple UI to do this instead.

**Comment by c5inco** [comment]
Thoughts @misolori?

**Comment by misolori** [comment]
Can you give an example/scenario where this would be helpful and what you'd expect to see/do?

**Comment by joaomoreno** [comment]
Absolutely @c5inco! This is https://github.com/microsoft/vscode/issues/30199. We now support automatic filtering in the tree... but the SCM view still uses the list only. Once we move to the tree there we'll get it for free.

**Comment by c5inco** [comment]
🙏 🙏

**Comment by c5inco** [comment]
Today's life with Git and icon scripting 😆 

![image](https://user-images.githubusercontent.com/1253402/64465945-ea52b600-d0c3-11e9-85bc-7a0dd792eefe.png)

**Comment by c5inco** [comment]
Just wanted to say - THANK YOU GUYS!! The new Git viewlet changes are awesome, and I didn't realize there was a toggle to filter or just highlight with the tree searching. Super cool!

**Comment by joaomoreno** [comment]
Just come snowboarding and we'll call it even.

**Comment by c5inco** [comment]
Hmm perhaps we should plan this for Feb or March next year!
