### ISSUE TITLE
Don't warn about committing before saving files if they aren't in the commit

### ISSUE THREAD

**Issue by cwoodcox** [microsoft/vscode#80349]
Currently, Code will warn you when you commit and you have unsaved files open. This is sometimes helpful, but if I haven't added the file to the commit, it's kind of useless.

It would be nice if it first checked to see if the unsaved file appears as modified (meaning it has already been saved at least once, and appears in the list of changes in the source control panel) and whether or not those changes are staged for commit. This way, if there is an unsaved file that is unrelated to my current commit, and I likely didn't miss adding the unsaved changes to the index, I probably did this intentionally.

This would preserve desired behavior, where I forgot to save the file and therefore forgot to add it to the commit, or where I did add it to the index, but not all of the changes, since it isn't saved.

**Comment by joaomoreno** [comment]
Just set `git.promptToSaveFilesBeforeCommit` to `staged`.
