### ISSUE TITLE
no git diff on wsl

### ISSUE THREAD

**Issue by sirber** [microsoft/vscode#80342]
Issue Type: <b>Bug</b>

add a remote wsl folder
modify a file
in the git view, click on a modified file
in the main window, see no diffs

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (7.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|       Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2901)|
|Memory (System)|15.82GB (7.73GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.39.5
vscode-todo-highlight|way|1.0.4
vscode-intelephense-client|bme|1.2.3
todo-tree|Gru|0.0.143
twig-language-2|mbl|0.8.10
ignore-gitignore|stu|1.0.1

</details>

**Comment by sirber** [comment]
doesn't seem to always be the case...

**Comment by joaomoreno** [comment]
OK, can you reproduce?
