### ISSUE TITLE
statusbar border no longer appears [statusbar.border]

### ISSUE THREAD

**Issue by wavebeem** [microsoft/vscode#80344]
Issue Type: <b>Bug</b>

The theme variable `statusbar.border` now no longer causes my statusbar to have a border. I am using my own theme "Uno Due Tre" and it disappeared as soon as I upgraded to VSCode 1.38.0.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

![image](https://user-images.githubusercontent.com/176815/64300215-e04c7e00-cf30-11e9-96d5-663f6e229174.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|-psn_0_4310044|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
vscode-icon-theme|jtl|1.6.5
vscode-simple-icons|Lau|1.11.10
python|ms-|2019.9.34474
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
Go|ms-|0.11.4
sublime-keybindings|ms-|4.0.3
vscode-sort-json|ric|1.14.0
trailing-spaces|sha|0.3.1
rewrap|stk|1.9.1
notification-tester|svi|2.1.3

(1 theme extensions excluded)

</details>

**Comment by meindra** [comment]
happened to me as well (VSCode 1.38, Windows 10)
<img width="426" alt="Screenshot_15" src="https://user-images.githubusercontent.com/6771960/64308069-4b926080-cfc2-11e9-910e-02a41209fb23.png">
