### ISSUE TITLE
MDN Links on html tags not working in .vue files

### ISSUE THREAD

**Issue by phiter** [microsoft/vscode#80348]
- VSCode Version: 1.38
- OS Version: Windows 10

Steps to Reproduce:

1. Open a .vue file
2. Make a html tag, like `<span>`
3. Hover the tag

The MDN links work if I'm in a HTML file, as follows:

![image](https://user-images.githubusercontent.com/12252332/64303006-65995800-cf5c-11e9-81e1-614d899394a8.png)

But when inside a .vue file, I get only the description, but not the links and tag name

![image](https://user-images.githubusercontent.com/12252332/64303036-8f527f00-cf5c-11e9-864f-54c8398a546e.png)

**Comment by octref** [comment]
Please open an issue for https://github.com/vuejs/vetur. Thanks!
