### ISSUE TITLE
IntelliSense inconsistent in JSON

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#80347]
**Problem**

IntelliSense suggestions are not appearing when they should be while in JSON files. It looks like maybe #30811 is related, but there doesn't appear to be a resolution. This does not appear to be a problem in other editors (e.g. WebStorm), so I'm assuming it can be improved.

**Reproduce**

1. Open `keybindings.json` file
2. Click the "Define Keybinding" button, press key combination and press enter.
3. In first tabstop, begin typing "editor". At this point, IntelliSense suggestions should begin showing. They don't. You need to manually trigger suggestions, or do something that will cause them to appear (e.g. delete the quotes around the property value and then retype the quotes). 

Note that the above steps are just one example. The same issue can be observed in other JSON files (e.g. `package.json`).

**Environment**

- Does this issue occur when all extensions are disabled?: Yes
- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6

**Comment by jrieken** [comment]
It's this setting `"editor.suggest.snippetsPreventQuickSuggestions"`

**Comment by jabacchetta** [comment]
@jrieken Actually, I gave a bad example. Normally, you're right, that setting would prevent suggestions. But in this case, the bug still stands, even with that setting disabled.

This is an issue in all JSON files, regardless of whether or not you're actively in a snippet.

**Comment by jrieken** [comment]
Yeah, that's mostly #30811 or actually the fact the JSON defines words to include quotes, so for JSON a word is `"foo"` and not `foo`. That, combined with the fact that typing `"` auto 'closes' to `"|"` always puts you into this unlucky position. 

fyi @aeschli

**Comment by jabacchetta** [comment]
It looks like WebStorm handles IntelliSense in JSON fine. Not sure what they're doing and whether or not there are any tradeoffs, but might be worth looking into.

@jrieken Should this be reopened until a conclusion is made, so that this issue isn't brought up again?
