### ISSUE TITLE
Extansion uninstall button bottom cut off

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#8034]
- VSCode Version: 1.3.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Click on the extensions button on the sidebar
2. Check the uninstall button (or see attached screenshot)
![untitled-1](https://cloud.githubusercontent.com/assets/5485902/16293875/c37ade38-3925-11e6-9833-9979d023eaea.jpg)

**Comment by joaomoreno** [comment]
#7995

**Comment by joaomoreno** [comment]
Actually, no.

**Comment by isidorn** [comment]
@joaomoreno hmm at the same time we looked into this issue - I pushed a font-size 16px which I prefer over the small button - feel free to revert that

**Comment by lllopo** [comment]
Nope, no luck with last update - font is smaller, but the button stil cut off. I think you should restore the font size and batting and reduce the margin of the '.actions' div (at least it work for me, when I tweak it through the developper tools).

![untitled-1](https://cloud.githubusercontent.com/assets/5485902/16330342/32372950-39f1-11e6-85bf-b276cf80dcb7.jpg)

Worth mentionning my display is scaled to 125%, but I don't think this affects the end result in any way. 
Btw., another issue is that rest of the interface is looking well with the 125% dpi scaling, but the status bar remains really tiny and incredibly hard to use (tiny click targets :-)). I'm tweaking the CSS to make it usable, but it is annouying to put my chnages after each update.

**Comment by lllopo** [comment]
My CSS that solves it, is font 14px on the button, vertical padding of 2px on the button, 10px margin on the '.actions' and '.description' DIVs ... looks ok to me.

**Comment by joaomoreno** [comment]
Thanks for the ping @lllopo.
