### ISSUE TITLE
Source Control panel cannot scroll when git modules is filled in the whole panel

### ISSUE THREAD

**Issue by dcalsky** [microsoft/vscode#80355]
- VSCode Version: 1.38.0
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Create a project including a sort of git submodules (> 5)
2. Open Source Control of Vscode, and then scroll it, you will found you cannot see the last few git modules except hide the top ones.

Does this issue occur when all extensions are disabled?: No

Before Hiding Auth git module:
![image](https://user-images.githubusercontent.com/9463958/64309966-f01b9f00-cfd0-11e9-8425-6ba1611f93d2.png)

After Hiding Auth git module, Feedhub git module appears:
![image](https://user-images.githubusercontent.com/9463958/64309988-f9a50700-cfd0-11e9-808f-9095155df615.png)

**Comment by joaomoreno** [comment]
Right click in the Source Control title, and make the Source Control Providers view visible. Then, you can use selection in that view to control which repositories are visible.

As a general splitview issue: https://github.com/microsoft/vscode/issues/64188
