### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by DearSekhar** [microsoft/vscode#80356]
Issue Type: <b>Bug</b>

Tooltip size is very small when I palce cursoron different items in my Angular project. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by DearSekhar** [comment]
Hi,Once I change laptop screen resolution from "3840*2160 (Recommended)" to 1920*1080, I am able to see tooltip normally. 
Thanks, Chandra Sekhar 

    On Thursday, September 12, 2019, 02:17:36 PM CDT, Sandeep Somavarapu <notifications@github.com> wrote:  
 
 
@DearSekhar Can you please provide the screenshot of the tooltip?

**Comment by sandy081** [comment]
Looks like Electron rendering issue.
