### ISSUE TITLE
Please Update Snap 

### ISSUE THREAD

**Issue by jeanluc243** [microsoft/vscode#80357]
on snap the are only the old version 1.37

i can't update my vscode version 
![DeepinScreenshot_select-area_20190904224135](https://user-images.githubusercontent.com/25481431/64312018-9b632e80-cfa6-11e9-9d00-80e9c590068c.png)

**Comment by bjon** [comment]
@jeanluc243 This is the official snap repo: https://snapcraft.io/code.
But that also still at 1.37.1

**Comment by joaomoreno** [comment]
As @bjon said, the official snap is https://snapcraft.io/code

1.38 is already released
