### ISSUE TITLE
Render mathematical notation in quick documentation

### ISSUE THREAD

**Issue by mtrp12** [microsoft/vscode#80359]
![image](https://user-images.githubusercontent.com/6695345/64313062-f6b01380-cfdc-11e9-854e-50c068d9da7f.png)

Hi, it would be nice to have mathematical notations declared in many different documents to be rendered in quick documentation or show hover feature. Thank you.

**Comment by mjbvz** [comment]
This is out of scope for core vscode. Extensions can convert mathematical notation to images which can be rendered in markdown documentation
