### ISSUE TITLE
Better shortcuts for expand/shrink selection

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#80354]
Expand/shrink selection when aware of the code structure is a very useful shortcut. Unfortunately, on OSX, it's Ctrl+Shift+Cmd+Left/Right. It's very long, it's hard to press, and hard to remember.

It would be nice if it would be shorter by default. For example,  Ctrl+Shift+Left/Right might be a much better option. Ideally it would be something short like Alt+Up/Down but it's already occupied.

P.S. I understand that I can set my own shortcuts. But there's a lot of value in a common keymap.

**Comment by jrieken** [comment]
Yeah, I am not a fan of the existing keybindings either. It's just a high density of existing keybindings and therefore hard to find alternatives. So, if you find a new set I am happily accepting a PR here.

**Comment by skprabhanjan** [comment]
@solomatov , do you want to submit a PR or can I take this up ?
Also update what would be the replacement set if you want me to send a PR for this :) 
IMHO :  **Ctrl+Shift+UpArrow/DownArrow** is best ( there is no default shortcut for this I guess )

**Comment by solomatov** [comment]
@jrieken Ok. I will. I will keep the old shortcut for a while since people with a better muscle memory than mine might got used to it :-)

**Comment by solomatov** [comment]
I created a PR: https://github.com/microsoft/vscode/pull/80491

I choose Ctrl+Shift+Left/Right since on other platforms Left/Right is used.

**Comment by jrieken** [comment]
👏 @solomatov
