### ISSUE TITLE
support  destructuring parameter @param tag in tsdoc

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/vscode#80368]
tsdoc rule:

https://github.com/microsoft/tsdoc/issues/186

example:

```ts
/**
 *
 * @param bar - the bar parameter
 * @param a - the first parameter
 * @param b - the second parameter
 * @param c - the third parameter
 * @returns the return value
 */
function foo(bar: string, {
  a,
  b,
  c
}:{
  a: string,
  b: number,
  c: string
}) {

  return bar + a;
}
```

![image](https://user-images.githubusercontent.com/8111351/64322482-3c78d600-cff5-11e9-96f0-1c4118bfb05d.png)
![image](https://user-images.githubusercontent.com/8111351/64322628-85308f00-cff5-11e9-83f5-cba6d8269b9c.png)

**Comment by xiaoxiangmoe** [comment]
@mjbvz

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new)
