### ISSUE TITLE
Hiding the maximized panel distorts the normal size

### ISSUE THREAD

**Issue by Mahmoudian-B** [microsoft/vscode#80366]
Reproduction steps:
1. Open any panel (Terminal, Problems, ...)
2. Restore the panel and set a desired height
3. Maximize the panel
4. Hide the panel
5. Show the panel
6. Restore the panel -> the initially set height in step 2 is not preserved.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2010 @ 2.80GHz (2 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|        Intel(R) Pentium(R) CPU G2010 @ 2.80GHz (2 x 2800)|
|Memory (System)|7.94GB (3.08GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-wsl|ms-|0.39.5
laravel5-snippets|one|1.7.0
vscode-icons|vsc|9.3.0
vscode-todo-highlight|way|1.0.4
project-manager|ale|10.7.0
vscode-intelephense-client|bme|1.2.3
laravel-goto-view|cod|1.3.2
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-test-explorer|hbe|2.14.5
python|ms-|2019.9.34474
vsliveshare|ms-|1.0.766
team|ms-|1.149.2
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
vscode-phpunit|rec|2.0.72
laravel-artisan|rya|0.0.25
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by arzyu** [comment]
I have the same problem. 

Steps to reproduce:

1. `>View: Close Panel`
2. `>View: Toggle Maximized Panel`
3. `>View: Toggle Panel`
4. `>View: Toggle Panel`

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
