### ISSUE TITLE
Peek Definition + ENTER doesn' go to definition anymore

### ISSUE THREAD

**Issue by 0ldF0x** [microsoft/vscode#80362]
Issue Type: <b>Bug</b>

How do you go to definition from peek definition window?
Before the 1.38.0 update you simply pressed enter in "peek definition" (ALT+12) and it jumped to definition. After the update this doesn't work anymore?

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
python|ms-|2019.9.34474
text-marker|ryu|1.11.0
plsql-language|xyz|1.8.2

</details>

**Comment by jrieken** [comment]
@bpasero @joaomoreno Did anything change in the tree or the workbrench tree? It seems that the item that got initially focus cannot be selected with `Enter` anymore

**Comment by joaomoreno** [comment]
The item already is both focused and selected, so pressing Enter won't fire a selection change event since the selection doesn't change. I copied the same `if` statement which is located 10 lines above. Right now both events are being listened to, I believe for your use case we can simply drop the selection change and simply listen to the open event.

**Comment by jrieken** [comment]
Hm, the weird thing is that it works in 1.37

**Comment by joaomoreno** [comment]
Yeah that's pretty weird. 🤔

**Comment by chapeupreto** [comment]
Yeah! I can confirm it doesn't work after latest updates:

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by k4113h** [comment]
Until the fix is available, pressing Shift + down arrow instead of Enter can be used as workaround.

**Comment by jrieken** [comment]
> Until the fix is available, pressing Shift + down arrow instead of Enter can be used as workaround.

Must better: there is VS Code Insider (https://code.visualstudio.com/insiders/) which updated daily and which has fix for this since 29 days
