### ISSUE TITLE
Inconsistency between newline of search between file and workspace

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#80361]
Latest version 1.38 introduce ability to add new line into search. Which is really great. But it also introduce `ctrl+enter` that was differ from workspace search that use `shift+enter`

I would like to voice that we should use the same everywhere. And so we should use `ctrl+enter` to add newline in workspace search too from the next version. We should also discourage usage of `shift+enter` for new line in some way (such as popup notice about deprecation) then remove it in some future version

**Comment by roblourens** [comment]
ctrl+enter is currently used for "replace" on windows but we need to find a way forward to unify these.

**Comment by Thaina** [comment]
Maybe opposite that we should use `shift+enter` everywhere. But then we need to find new key to select previous search

Maybe `ctrl+arrow` ?

**Comment by roblourens** [comment]
I don't think we should replace `shift+enter` in the find widget. And I'm not sure that there's really an issue with ctrl+enter in search anyway. Just need a little investigation.

**Comment by Thaina** [comment]
@roblourens I actually wish we could use `shift+enter` for newline in find widget. Because it was consistent with majority of app that need to make newline (such as chat app) so it more familiar

I just know that people may already adapt to current behaviour of our `shift+enter` so at first I suggest `ctrl+enter`
