### ISSUE TITLE
Unexpected space when formatting code

### ISSUE THREAD

**Issue by imWildCat** [Microsoft/vscode#8037]
- VSCode Version:Version 1.2.1 (1.2.1) fe7f407b95b7f78405846188259504b34ef72761
- OS Version: OS X 10.11.5 (15F34)

Steps to Reproduce:

1. A react native project with code like the gif
2. Format code

Gif:
![2016-06-23 16_55_40](https://cloud.githubusercontent.com/assets/2396817/16297410/55267d0a-3963-11e6-9d32-066fcde6b530.gif)

**Comment by aeschli** [comment]
Issue with the TypeScript formatter.
Reproduced with the following snippet:
```jsx
render() {
  return (
    <Scene>
      <Scene key="me" component={PageWrapper(HomePage)} title="me" />
    </Scene>
  );
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#9823
