### ISSUE TITLE
result of python list deug is differnet from running

### ISSUE THREAD

**Issue by xuweichn** [microsoft/vscode#80373]
code:
x = ['foo', 'card', 'bar', 'aaaa', 'abab']

x.sort(key=lambda a: len(list(a)))
print(x)

previously, code was:
x = ['foo', 'card', 'bar', 'aaaa', 'abab']

x.sort(key=lambda a: len(set(list(a))))
print(x)

debug output: ['aaaa', 'abab', 'bar', 'card', 'foo']

running result: ['foo', 'bar', 'card', 'aaaa', 'abab']

environment: miniconda 3.6 + python 3.6.5

**Comment by roblourens** [comment]
This seems like an issue with your program or your python configuration. Maybe the debugger is using a different version of python than in your environment?

If you think it's an issue with the debugger, please file an issue on the vscode-python extension.
