### ISSUE TITLE
LoadedScriptsView: id of item should not depend on label

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#80379]
When a session's `name` get changed the Loaded Scripts View looses selection / expansion state for that session.
The reason for this is that we compute the tree id of the session element based on the label [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/loadedScriptsView.ts#L114)

We should not use the `label` when computing ids, but we should use some internal id instead (or the id of the underlying `DebugSession` element in this case)

fyi @dgozman

**Comment by isidorn** [comment]
Also on session change `name` we shuold not do all this magic [here](https://github.com/Microsoft/vscode/blob/d0898d57d4ba950cece5aad11eb06f9ce1bb4f0a/src/vs/workbench/contrib/debug/browser/loadedScriptsView.ts#L480)
I think a simple `tree.rerender` should be enough (on top when we change the ID computation to no longer depend on `label`)

**Comment by weinand** [comment]
The `ID` of session nodes is now based on the session ID instead of the session label.
