### ISSUE TITLE
C++ std::unique_ptr is not evaluated during debugging

### ISSUE THREAD

**Issue by HoppeMateusz** [microsoft/vscode#80377]
- VSCode Version:
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-25-generic

- OS Version:
Ubuntu 18.04

Steps to Reproduce:

1. program with std::unique_ptr<> with custom class template parameter
2. start debugging program
3. break at unique_ptr variable in code
4. watch variable, move mouse over variable in text editor
5. only "{...}  get(): 0x5555590a5a70 " is diplayed, no memebres visible

**Comment by sbatten** [comment]
this issue should be reported on the extension you are using for C++ development

**Comment by HoppeMateusz** [comment]
Ok, thanks for guidance
