### ISSUE TITLE
File > Open Recent > More... doesn't work if there is no window open

### ISSUE THREAD

**Issue by joachim-n** [microsoft/vscode#80378]
- VSCode Version: 1.38.0
- OS Version: MacOS 10.14

Steps to Reproduce:

1. close all windows
2. Go to File > Open Recent > More... to open a project that's not in the most recent list

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@joachim-n yes, you are right, this command requires a window to be open, we should probably just disable it when no windows are open

**Comment by joachim-n** [comment]
It is disabled when there are no windows open -- sorry, I wasn't clear enough. My point is that if there are no windows open, you can't use it.

**Comment by sbatten** [comment]
@joachim-n oh, i see, then this is the intended behavior as we have now window to show the UX for this command. We could open a new window and show the picker, but this isn't really any better than opening an empty window yourself
