### ISSUE TITLE
Remote (ssh) offline installation support

### ISSUE THREAD

**Issue by VitaliKaiser** [microsoft/vscode#80388]
When connecting to a remote computer with the remote extension, the remote machine needs to be prepared first. Unfortunately, this machine also needs internet in order to download the vscode remote server.
But if the machine has no access to the internet, you cant connect to it. My proposal is to transfer the necessary files for the vscode remote server via ssh from the host.

The same goes for extensions: At the moment I can not install a extension on a docker container which has no internet connection. But it should be possible to get the installation files from the host.

Best,
Vitali

**Comment by VitaliKaiser** [comment]
As far as I can judge none of them are directly correlated.

**Comment by roblourens** [comment]
This is supported, please try enabling the `remote.SSH.allowLocalServerDownload` setting.
