### ISSUE TITLE
SCM placeholder is soo long that input widget wraps

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#80386]
I would not expect that the input box wrap when it shows a placeholder, only when I type something

<img width="403" alt="Screenshot 2019-09-05 at 12 24 26" src="https://user-images.githubusercontent.com/1794099/64334111-2b6d9c00-cfd8-11e9-9a4e-f9ddc64ebb84.png">

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/79029

OK you guys discuss, let me know who wins.

**Comment by bpasero** [comment]
I don't mind that we do not wrap, however this:

![image](https://user-images.githubusercontent.com/900690/64337731-3c221000-cfe0-11e9-8101-c92faa71be8e.png)

Looks broken. If we do not wrap then we should really not wrap and show 1 line with "..." in that input field.
