### ISSUE TITLE
Bug On Nodejs 

### ISSUE THREAD

**Issue by GaneshKoirala** [microsoft/vscode#80384]
Issue Type: <b>Bug</b>

not showing nodejs codes autocomplete like require and nodejs modules after recent updates just a min

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.88GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.9.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@GaneshKoirala can you provide simple repro steps that worked in the previous release?

**Comment by GaneshKoirala** [comment]
![Screenshot (72)](https://user-images.githubusercontent.com/42663919/64369622-73bea580-d03c-11e9-923d-916aaa58207e.png)

in new update it doesn't show this require autocomplete and also not showing core node modules inside require("")

**Comment by sbatten** [comment]
I tried reproing the issue from 1.35 => 1.38 and it seems to be broken in 1.37.1 as well

**Comment by roblourens** [comment]
Yeah I agree that it was already broken in 1.37

**Comment by mjbvz** [comment]
@GaneshKoirala What type of project are you working in? Do you have a `package.json` for example?

Please describe your project and provide some basic steps to reproduce the issue
