### ISSUE TITLE
Edit Menu --> Toggle Line Comment wrong shortcut key info.

### ISSUE THREAD

**Issue by MajhiRockzZ** [microsoft/vscode#80387]
Issue Type: <b>Bug</b>

## But give "Ctrl + Shift + /" for both Toggle Line/Block Comment.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
prettier-vscode|esb|2.2.2
vscode-azureappservice|ms-|0.15.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34474
remote-wsl|ms-|0.39.5
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
sublime-keybindings|ms-|4.0.3
vsliveshare|ms-|1.0.766
debugger-for-chrome|msj|4.11.7
java|red|0.48.0
vscode-yaml|red|0.5.2
LiveServer|rit|5.6.1
mdx|sil|0.1.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-icons|vsc|9.3.0
quokka-vscode|Wal|1.0.240
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@MajhiRockzZ I am not understanding the issue you are reporting. Could you clarify, possibly with screen shots?
