### ISSUE TITLE
vscodecandothat.com -- Wrong link

### ISSUE THREAD

**Issue by h-h-h-h** [microsoft/vscode#80385]
From the YouTube channel https://vscodecandothat.com/ links to, it seems this page is directly associated with you. And since there's no other means of contact, I'll post it here:

On https://vscodecandothat.com/, the "Learn More" link under "Force Collapsible Regions" is wrong; it's the same as the one under "Refactor Promises to Async/Await". It's all at the top of the page.

**Comment by sbatten** [comment]
This isn't really the right place to report this issue, but pinging @burkeholland
