### ISSUE TITLE
Preserve Case checkbox doesn't respect inputOption.activeBackground

### ISSUE THREAD

**Issue by knopp** [microsoft/vscode#80389]
Happens in both 1.38.0 and current insiders (7edc8f786e065edbc9540f1e19ebd9220b9e0cf9)

Tested with 

```json5
"workbench.colorCustomizations": {
   "inputOption.activeBackground": "#ff0000"
}
```

It should have bright red background in checked state instead of gray.

<img width="306" alt="Screen Shot 2019-09-05 at 13 02 18" src="https://user-images.githubusercontent.com/96958/64336499-6a522080-cfdd-11e9-89d1-73c0e9f61adc.png">

**Comment by sbatten** [comment]
@knopp, I am unable to reproduce, this works for me.
