### ISSUE TITLE
issue with tcl langage

### ISSUE THREAD

**Issue by Pascal3100** [microsoft/vscode#80395]
Issue Type: <b>Bug</b>

Hi all,

i have a problem when coding in tcl langage since 2 versions ago.
When typing the following commands:
        set item [regsub -all {\$. *} $item ""]
        set item [regsub -all { *$} $item ""]
        set item [string map {"#_" "" " " "_"} $item]
all the following code is interpreted as comment.
I've changed the tcl extension but the problem still there so i think the problem is from VS code.

Thanks a lot!

Pascal

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
gc-excelviewer|Gra|2.1.32
compareit|in4|0.0.2
abaqus|JP|1.0.0
nastran|mar|0.1.4
mssql|ms-|1.6.0
python|ms-|2019.9.34474
powershell|ms-|2019.5.0
tcl|ras|0.1.0
hyperworks|sle|0.1.0
templex|sle|0.1.1

</details>

**Comment by sbatten** [comment]
@Pascal3100 have you already reported this issue against the extension you are using? I understand that you have changed extensions, but it will be simpler if the developer of the extension who is familiar with the language can determine the root cause and if it is indeed a VS Code issue, we can get that context.
