### ISSUE TITLE
${workspaceFolder} broken in "default" of task inputs

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#80398]
- VSCode Version: 1.38.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add a `promptString` input with a default of `"default": "${workspaceFolder}/foo`. The resolved value will be `/foo`.

This did work in the past but I haven't tested it in a while.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
We don't support resolving variables in input values.

**Comment by letmaik** [comment]
Why not? That's super useful.

**Comment by alexr00** [comment]
To avoid recursion and because we just haven't done it yet for simple variables https://github.com/microsoft/vscode/issues/64358
