### ISSUE TITLE
Using env varibales in tasks.json

### ISSUE THREAD

**Issue by rohitkotak** [microsoft/vscode#80399]
- VSCode Version: 1.34.0
- OS Version: windows 10

**Steps to Reproduce:**

1. Create new task in tasks.json
2. Use environment variable(having installation path stored) in command of that task

I created new vscode task in tasks.json where I want to execute one exe file from command. So I created on environment variable(i.e. MY_PATH) to store the path of that exe.

**Below is the command of the vscode task which I am using:**
"command": "${env:MY_PATH}\MyApp.exe ${file}"

MY_PATH points to the directory of the installed application in C:\Program Files\MyApp\

**Below is the error message:**
C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\MyApp\MyApp.exe ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Which seems to me that there is a space which is creating the issue.

Please help me to solve this out.

**Comment by ArturoDent** [comment]
Does putting single ticks around the variable fix it?

Like `"'${env:MY_PATH}'\MyApp.exe ${file}"`

**Comment by alexr00** [comment]
Or, does 
```
"command": "${env:MY_PATH}\MyApp.exe",
"args": ["${file}"]
```
work? Since you have a space between MyApp.exe and ${file}, we won't know the right way to escape your command.

**Comment by rohitkotak** [comment]
This worked: **'${env:CPPCHECK_ROOT}\\MyApp.exe'**

Thank you.
