### ISSUE TITLE
Copy and paste doesn't work properly in Debug Console

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/vscode#8039]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Pro 1511, Node 5.10

### Steps to Reproduce:

1. Create an app with a large output to the console, e.g. crash report, console.dump etc.
2. Try to copy and paste 10 + lines of output on a small screen

### The Issue
I am using an M'soft surface, so the small screen makes the debug window is small. 

1. Using `shift + up` to select multiple lines rolls over into the code screen rather than scrolling the console. 

2. If I select a line and then manually scroll up through many lines while holding shift and then click the new line (10 or so lines higher - they don;t all fit on the screen) however, scrolling up and down shows them highlighted, copy and paste only shows the last 4 lines (presumably the only ones that were visible at one go).

**Comment by isidorn** [comment]
Dup of #2163
