### ISSUE TITLE
Error with TypeScript

### ISSUE THREAD

**Issue by normanfeltz** [microsoft/vscode#80400]
Hi,

After the update this morning, a error appeared on my project :
![2019-09-05_14-17-47](https://user-images.githubusercontent.com/1359159/64341216-2a446b00-cfe8-11e9-81bd-27b1fbfa45b1.png)

I'm in TypeScript 3.6.2

Cordialy

Norman F.

Technical Info:
Version : 1.38.0 (user setup)
Validation : 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date : 2019-09-03T21:49:13.459Z
Électron : 4.2.10
Chrome : 69.0.3497.128
Node.js : 10.11.0
V8 : 6.9.427.31-electron.0
OS : Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
This looks like a typescript issue. Please file it upstream
