### ISSUE TITLE
Split terminals not showing

### ISSUE THREAD

**Issue by jcserracampos** [microsoft/vscode#80404]
Issue Type: <b>Bug</b>

When splitting terminal the pair terminals (2, 4, 6, etc.) are not showing.
The even terminals are not being created with same width too.

VS Code version: Code - Insiders 1.39.0-insider (7edc8f786e065edbc9540f1e19ebd9220b9e0cf9, 2019-09-05T05:39:44.768Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
prettier-vscode|esb|2.2.2
auto-close-tag|for|0.5.6
gitlab-mr|jas|1.4.2
vscode-peacock|joh|3.1.5
sublime-babel-vscode|jos|0.2.10
solidity|Jua|0.0.58
dotenv|mik|1.0.1
vscode-elixir|mjm|1.1.0
vscode-azureappservice|ms-|0.15.0
vscode-azurestorage|ms-|0.7.1
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34474
azure-account|ms-|0.8.4
csharp|ms-|1.21.1
Go|ms-|0.11.4
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.9.0
polacode|pnp|0.3.2
ruby|reb|0.25.3
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.2
trailing-spaces|sha|0.3.1
slim|sia|0.1.2
mdx|sil|0.1.0
html-preview-vscode|tht|0.2.5
vscode-wakatime|Wak|2.2.0
vscode-todo-highlight|way|1.0.4
vscode-mdx-preview|xyc|0.2.1
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by hugovisk** [comment]
+ 1

**Comment by octref** [comment]
Split terminal not showing at all:

![image](https://user-images.githubusercontent.com/4033249/64369552-746e2200-cfd1-11e9-926a-1cff1aa2b716.png)

If I split twice, it's like this:

![image](https://user-images.githubusercontent.com/4033249/64369586-8a7be280-cfd1-11e9-9dca-ab3c757afa39.png)

**Comment by Tyriar** [comment]
@sbatten @joaomoreno some change happened probably in the split view yesterday that caused this, any ideas/pointers?

**Comment by eamodio** [comment]
@Tyriar from looking at the DOM, the split panel is there, its just positioned too far to the right.

Here is the code that is changing the `left` prop: https://github.com/Microsoft/vscode/blob/fb85e286d3c267a37ff708f371425deeb1bc1b59/src/vs/base/browser/ui/splitview/splitview.ts#L149-L156

**Comment by sbatten** [comment]
@Tyriar 

This appears to be caused by this change https://github.com/microsoft/vscode/commit/fb85e286d3c267a37ff708f371425deeb1bc1b59 by @joaomoreno 

Since terminal hardcodes the the position at https://github.com/microsoft/vscode/blob/aadad21f90f3cb71ac6e83baf3dfd5bf8b9c1625/src/vs/workbench/contrib/terminal/browser/media/terminal.css#L74-L78

it is breaking the positioning.

Removing this seems to fix the issue. I have verified that the viewport and scrollbar remain correctly positioned

![image](https://user-images.githubusercontent.com/6561887/64390882-6e8d3680-cffb-11e9-9b99-fe774d5a791c.png)

**Comment by joaomoreno** [comment]
Good catch. Yeah, I now layout the split views in absolute terms (instead of relying on the browser to stack them up). We should stay away from customising CSS on parent containers (`.split-view-view`). Even that `border-box` would make sense to just move to every `split-view-view`.
