### ISSUE TITLE
JavaScript: Incorrect highlighting of regular expressions due to unescaped slash

### ISSUE THREAD

**Issue by FremyCompany** [microsoft/vscode#80405]
Issue Type: <b>Bug</b>

The javascript syntax highlighter of visual studio code doesn't work properly one regular expressions that contain a close slash inside a parenthesis block.

```javascript
let flag = /(///)/.test(string) ? (
    'has_doc_comment' : 'has_no_doc_comment'
)
```

The syntax error is correct, but impossible to understand due to incorrect highlighting. Compare here below Visual Studio's highlighting vs a proper javascript parser highlighting:

> ![image](https://user-images.githubusercontent.com/364405/64348349-531f2d00-cff5-11e9-8229-961bf3289ccd.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

**Comment by FremyCompany** [comment]
Ahahaha, the github syntax hightlighter does't do any better :rofl:

**Comment by sbatten** [comment]
@FremyCompany that is not a valid JS regex, the `/` inside parens need to be escaped with `\`.

```js
/(\/\/\/)/g.test(string)
```

**Comment by FremyCompany** [comment]
@sbatten This is the point exactly. The `/` closes the regular expression, so after the first `/` everything should be syntax-highlighted as code, not as still part of the regular expression.

Compare how a correct syntax highlighter colors this snippt (everything after the first slash is rendered as a comment) versus how visual studio code does it, where you don't get any indication that the slash closed the regular expression.

By the way, here's is a valid code that is still highlighted incorrectly:

```javascript
try { let throws_at_runtime = /(/ } catch (ex) { console.log('PASS') }
```

![image](https://user-images.githubusercontent.com/364405/64428708-b1f7ab80-d0b4-11e9-9104-45ae402a5039.png)

Please reopen this issue.

**Comment by sbatten** [comment]
will re-open and allow @alexr00 to triage

**Comment by alexr00** [comment]
Moved to https://github.com/microsoft/TypeScript-TmLanguage/issues/771
