### ISSUE TITLE
DialogService: three butons and a checkbox

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#80403]
Currently the `dialogService` only allows me to have a checkbox if I do a `confirm`. Due to that I can only have two buttons and a checkbox.
It is not possible to have multiple buttons and a checkbox. I would expect this to be possible if the `confirm` would accept multiple buttons, or if the `show` would support the checkbox.

fyi @bpasero

**Comment by bpasero** [comment]
Caution though, the `show` signature currently does not give any indication if the checkbox was clicked by the user or not, so it would need to provide this info.

**Comment by isidorn** [comment]
@bpasero agree fully. We would need to change the return value

Also fyi I need this for https://github.com/microsoft/vscode/issues/68084
@sbatten If you do not have time to add this, let me know if you are ok with me adding this APi to the `dialogService`.

**Comment by sbatten** [comment]
I'm okay with this change. As for being careful, when updating references, the progress service will need special attention to make sure we don't break reconnection

**Comment by isidorn** [comment]
@sbatten what do you prefer that I do:
1. change the `confirm` API to allow multiple buttons
2. change the `show` to allow checkboxes and to return a richer result?

**Comment by sbatten** [comment]
@isidorn my opinion is that show is intended for a more complete experience and confirm is for fairly boolean response. I think that show can be expanded to fit that.

**Comment by isidorn** [comment]
Will be verified as part of #68084, thus adding verified label.
