### ISSUE TITLE
Indentation agnostic multi-line search

### ISSUE THREAD

**Issue by LautaroLorenz** [microsoft/vscode#80407]
Issue Type: <b>Feature Request</b>

multiline search not working with tabs on .html file, for example:
with the next code:
```
<ion-toolbar>
</ion-toolbar>
<div>
  <ion-toolbar>
  </ion-toolbar>
</div>
```
if find:
```
<ion-toolbar>
</ion-toolbar>
```
only match with the first apparition of 
```
<ion-toolbar>
</ion-toolbar>
```
but not find it inside de div
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kieferrm** [comment]
Multi-line search is not agnostic to the indentation level of your code. In order to achieve what you're looking for you currently need to use regex search.
