### ISSUE TITLE
show variable type on hover

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8040]
This feature request asks for adding the UI for this debug protocol extension: https://github.com/Microsoft/vscode-debugadapter-node/issues/32

If the optional 'type' attribute is available for a variable, the type should be shown when hovering over the name part of a variable.

**Comment by TitaneBoy** [comment]
Hi everyone. I was wondering if there would be a way to have this functionnality (i.e Having the type definition on mouse over ) but not in debug. For example, I am writting a function which has parameters with some types. But when I want to see the type definition (which comes from other files) of a variable (like parameters), I can't see it.. I just see the type name, not its definition.

Thank you for your answer...

**Comment by weinand** [comment]
@TitaneBoy VS Code already supports what you are asking for. In the following screenshot I am hovering over the logger.setup method and the hover shows the method parameters:

![2017-04-24_17-25-06](https://cloud.githubusercontent.com/assets/1898161/25344690/2b96b3b0-2913-11e7-8dc0-8903d1918558.png)

But this informations is only available if you are using a language extension that supports this (in my example it is coming from VS Code's built-in TypeScript extension).

**Comment by TitaneBoy** [comment]
Well...I know that we can have the function definition...I think I didn't ask the right question..

Suppose I have this instruction: 

```
interface ITypeInterface {
   firstVariable: string;
   secondVariable: number;
   thirdVariable: {id: number; description: string};
}

let myVariable: ITypeInterface = undefined;
```

If I want to see the definition of "ITypeInterface " with the mouse over on the "ITypeInterface" name, how can I do ? If the ITypeInterface is defined somewhere else in another file, I had to "Crl + Click" on the type name to get its definition. But by doing that, I will switch my file view and my context at the same time. Is there a way to see the type definition (and not only the name) by mousing over the type name ?

Thank you

**Comment by TitaneBoy** [comment]
Just to be sure: I'm using typescript language in my context and let's assume that import of the First_file.ts is done correctly in the "Second_File.ts"

**Comment by weinand** [comment]
Showing the full type definition on hover doesn't make a lot of sense because the hover size is fairly limited. You would only be able to see the first couple of lines in the hover.
But try to use the "Peek Definition" action (alt-F12): it shows the full type definition without swithcing files:

![2017-04-24_17-53-00](https://cloud.githubusercontent.com/assets/1898161/25346072/e422b444-2916-11e7-8830-5a72db2dfcd5.png)

**Comment by TitaneBoy** [comment]
@weinand : Perfect...This is what I was looking for...Thank you again for your fast answer and your great support...:-)
