### ISSUE TITLE
Should not process click events when in the background

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode#80408]
Issue Type: <b>Bug</b>

On macOS, typical behavior is for a mouse click on a background window to give focus to that window, without triggering the action of the button underneath the cursor.

For example, open two windows in Safari to a page full of links like Reddit, and notice how when you click back and forth between the windows, you can't accidentally hit any of the links.

This behavior is occasionally overridden, such as with the iTunes playback controls, but there should be a good reason to do so.

Visual Studio Code does not obey this convention and clicks intended to give focus can hit many "active" areas of the window, including the tab switcher, explorer, minimap, scrollbar — all things that are likely to be peeking out behind another window, and thus areas the user will click on to give focus.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
Settings: `window.clickThroughInactive: false`

**Comment by rgov** [comment]
Thanks. Please consider making it the default on platforms where it is expected.
