### ISSUE TITLE
Hover tooltips only appear when VS Code window is unfocused

### ISSUE THREAD

**Issue by mylesdawborn** [microsoft/vscode#80416]
Issue Type: <b>Bug</b>

1. Open project and hover over code. 

When VS Code is focused, hovering over code does not show tooltips, however when the window is unfocused, and I hover over the code, the tooltip will display. When clicking the unfocused VS Code window, the tooltip proceeds to disappear until I repeat the process.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
dart-code|Dar|3.4.1
flutter|Dar|3.4.1
bloc|Fel|0.11.1
awesome-flutter-snippets|Nas|2.0.2
material-icon-theme|PKi|3.9.0

</details>

**Comment by mylesdawborn** [comment]
Hovering over code with VS focused = no tooltip.
![Screenshot (4)](https://user-images.githubusercontent.com/33122420/64359826-6dfb9c80-d009-11e9-852b-27d64042fec4.png)

Hovering over code with VS unfocused = tooltip shows.
![Screenshot (5)](https://user-images.githubusercontent.com/33122420/64359859-810e6c80-d009-11e9-9c13-c7550b2c8c46.png)

**Comment by mylesdawborn** [comment]
Updated VS Code still doesn't fix issue.

**Comment by alexandrudima** [comment]
@mylesdawborn I cannot reproduce. Have you tried disabling all extensions? 

Do other hovers, like these tooltips work for you?
![image](https://user-images.githubusercontent.com/5047891/64868345-6d818800-d63f-11e9-8131-6435a15f01fe.png)

**Comment by mylesdawborn** [comment]
@alexandrudima no, those tooltips don't show up either.

I have tried with a clean, no extension install as well. Same result.

**Comment by alexandrudima** [comment]
@mylesdawborn Thank you for following up, but unfortunately I still cannot reproduce... Could you perhaps try opening https://microsoft.github.io/monaco-editor/ in Chrome or in the new Edge (based on Chromium)? Do you get hover tooltips there?

**Comment by mylesdawborn** [comment]
@alexandrudima thanks for the response. I'm not sure why, but it seems to be working. I did remove and install gpu drivers over the weekend which could have fixed it. There was a new Flutter/Dart update as well.
