### ISSUE TITLE
ESC in search box doesn't work

### ISSUE THREAD

**Issue by markho10** [Microsoft/vscode#8041]
- VSCode Version: 1.3.0-insider, Commit 5eaf9f05038b0a9818ebff510e1aafe07ac1ae68
- OS Version: Windows 10 Enterprise Build 10586

Steps to Reproduce:

1. Ctrl + Shift + F opens the search box on left side
2. "Press Enter to Search, ESC to Cancel" field is focused.
3. Pressing ESC doesn't do anything.

**Comment by sandy081** [comment]
@markho10 The way it works from beginning is as follows:

Escape will only cancel the current search request. For eg: Type some text and press enter to search . It starts getting the results. You can see the progress bar on the top. If you want to cancel the request then Press Esc.
