### ISSUE TITLE
Terminal up arrow

### ISSUE THREAD

**Issue by paamonim** [microsoft/vscode#80413]
Issue Type: <b>Bug</b>

Until recently when I was in terminal and pressed arrow up, it would automaticaly insert my last typed command in the terminal.
Now, up arrow doesn't do anything, just an annoying sound.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
bracket-pair-colorizer-2|Coe|0.0.28
remote-wsl|ms-|0.39.5
ruby|reb|0.25.3
highlight-matching-tag|vin|0.9.5
simple-ruby-erb|vor|0.2.1

</details>

**Comment by Tyriar** [comment]
The annoying sound is probably the bell, which is what the shell is telling the terminal to do. This must be an environment issue with your shell setup because that's what's reacting to the up arrow and telling the terminal to sound the bell.
