### ISSUE TITLE
Opening multiple files at once

### ISSUE THREAD

**Issue by AishwaryaPatankar** [microsoft/vscode#80418]
Issue Type: <b>Bug</b>

(In a Macbook) Command + P to open a file. Don't make any changes on it. Command + P aggain to open another file. That file replaces the original opened file. 

When I open a file, I can't open another file in a nother tab without making changes to my current file. What if I just want to look at two files at a time?

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
rails-test-runner|dav|0.0.4
gitlens|eam|9.9.1
beautify|Hoo|1.5.0
vscode-rufo|jnb|0.0.1
vscode-peacock|joh|2.4.0
chat|kar|0.21.1
vscode-docker|ms-|0.7.0
vsliveshare|ms-|1.0.766
vsliveshare-audio|ms-|0.1.64
vsliveshare-pack|ms-|0.3.3
ruby|reb|0.25.3
gitblame|wad|3.0.1

</details>

**Comment by sbatten** [comment]
@AishwaryaPatankar this setting controls that behavior. by default new editors are opened as preview: `workbench.editor.enablePreviewFromQuickOpen`

Alternately, `Cmd+K, Enter` will convert a preview tab to a pinned tab
