### ISSUE TITLE
Hash (and everything after) in .gitmessage is missing in "Source Control" pre-filled message

### ISSUE THREAD

**Issue by rlebosse** [microsoft/vscode#80415]
- VSCode Version: 1.38.0
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Write `message #issue` in file `~/.gitmessage`

![Sélection_027](https://user-images.githubusercontent.com/2794137/64358454-c9785b00-d006-11e9-8e5a-df8585efd1ee.png)

2. Open VSCode in a project that is linked to git
3. Open "Source Control" section
4. The pre-filled message is only "message " (the hash and everything after is missing)

![Sélection_026](https://user-images.githubusercontent.com/2794137/64358467-cda47880-d006-11e9-885b-f5bb0f6b9283.png)

Does this issue occur when all extensions are disabled?: **Yes**

The whole message was displayed correctly in the previous VSCode version.

![Sélection_028](https://user-images.githubusercontent.com/2794137/64359110-fda04b80-d007-11e9-91c7-ab6e1d72f06b.png)

**Comment by joaomoreno** [comment]
Broken by https://github.com/microsoft/vscode/pull/71710
