### ISSUE TITLE
Project references are not picked up (1)

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#80423]
- VSCode Version: 1.38.0
- OS Version: 10.14.6
- TypeScript version: tested with both 3.5.2 and 3.6.2

Steps to Reproduce:

`./tsconfig-src.json`:

``` json
{
    "compilerOptions": {
        "composite": true,
        "declarationMap": true,
        "outDir": "./target/",
        "baseUrl": "./src/"
    },
    "include": ["./src/**/*"]
}
```

`./tsconfig.json`:

``` json
{
    "references": [{ "path": "./tsconfig-src.json" }],
    "files": []
}
```

`./src/main.ts`:

``` ts
import { foo } from 'helpers/functions';

foo;
```

`./src/helpers/functions.ts`:

``` ts
export const foo = 1;
```

When I run `tsc --build`, it builds with no errors.

When I navigate to a TS file in VS Code, e.g. `./src/main.ts`, I get errors: `Cannot find module 'helpers/functions'`

![image](https://user-images.githubusercontent.com/921609/64363850-82d83000-d009-11e9-873c-84caa79c9542.png)

I expected this to work because VS Code would find the `./tsconfig.json` in the parent/root directory, and this references `./tsconfig-src.json` (the TS project which includes the file I'm looking at: `./src/main.ts`).

Repo including the above test case: https://github.com/OliverJAsh/unsplash-ts-project-references

I understand I could workaround this by moving `./tsconfig-src.json` into the `./src/` folder at `./src/tsconfig.json`, but I believe that shouldn't be necessary.

What's more, in my real world application the `./tsconfig-src.json` includes files in multiple root folders (`./src/`, `./client/`, `./server/`), not just `./src/`, so this workaround wouldn't help in that case. For an example, see https://github.com/OliverJAsh/unsplash-ts-project-references/tree/bad-workaround.

Does this issue occur when all extensions are disabled?: Yes

Potentially related:
- https://github.com/microsoft/vscode/issues/12463
- https://github.com/microsoft/vscode/issues/80423
- https://github.com/microsoft/TypeScript/issues/20185
- https://github.com/microsoft/TypeScript/issues/30823
- https://github.com/microsoft/TypeScript/pull/28261
- https://github.com/microsoft/TypeScript/pull/32028

**Comment by andrewbranch** [comment]
@OliverJAsh did you run a `tsc -b` first? At the moment, declaration files need to be written to disk in order for TS Server to know about symbols from referenced projects. (Changing that is in-progress, targeted for 3.7.)

**Comment by OliverJAsh** [comment]
I did all of those things, unfortunately to no avail. I even checked the TS server log to see if I could spot anything particularly odd, also to no avail.

**Comment by andrewbranch** [comment]
@OliverJAsh hold on, `helpers/functions` refers to something inside `node_modules` (or a path mapping, of which you have none in the sample you posted). I think you meant to use a relative path, unless I missed an important piece somewhere?

**Comment by OliverJAsh** [comment]
`baseUrl` is what holds it together here. It works if you don't use project references. Same example but without project references: https://github.com/OliverJAsh/unsplash-ts-project-references/tree/no-project-references

**Comment by OliverJAsh** [comment]
The more I play with project references, the more it seems like they simply don't work with VS Code. Here's a similar but separate issue I just filed: https://github.com/microsoft/vscode/issues/80438.

**Comment by mjbvz** [comment]
@OliverJAsh In your example, `src/main` is not part of any project known to VS Code (just run `TypeScript: Go to project configuration` with the file open to check this) It is only part of the `tsconfig-src.json` project, which VS Code does not load automatically. We currently only load projects in files called `tsconfig.json`

In `tsconfig.json`, if I change `files` to `"files": ["src/main.ts"]` then everything seems to work

<img width="1056" alt="Screen Shot 2019-09-09 at 10 49 26 AM" src="https://user-images.githubusercontent.com/12821956/64554078-83b1e000-d2ef-11e9-8541-b5aa185b0bbb.png">

Closing this as a configuration question

**Comment by OliverJAsh** [comment]
> It is only part of the `tsconfig-src.json` project, which VS Code does not load automatically

Correct, but `tsconfig.json` _references_ `tsconfig-src.json`. So if VS Code discovers `tsconfig.json`, why does not it pick up the referenced project? I thought this was the whole point of TS project references.

**Comment by mjbvz** [comment]
Good point. I was having trouble understanding what the intention was in the example.

This looks like another case of https://github.com/microsoft/TypeScript/issues/30823 then. If you don't think this is the case, please open a new issue against TypeScript
