### ISSUE TITLE
Clicking on input field in Settings scrolls off view

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#80421]
Issue Type: <b>Bug</b>

![gif](https://user-images.githubusercontent.com/35271042/64361085-b2167f00-cfc0-11e9-9589-ded000561e73.gif)

Repro:
1. Toggle the bottom panel
2. Open Settings UI
4. Scroll to a long setting description like Windows Title
5. Focus on the settings search input first, then attempt to click on input
6. 🐛 View scrolls off and input is never selected

I think the Settings UI scrolls to the start of the setting container, but as a user I would expect this to scroll to the input field if clicked.

VS Code version: Code - Insiders 1.39.0-insider (7edc8f786e065edbc9540f1e19ebd9220b9e0cf9, 2019-09-05T05:39:44.768Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_1720740|
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
vscode-pull-request-github-insiders|Git|2019.9.5222
todo-tree|Gru|0.0.143
vscode-colorize|kam|0.8.12
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34474
remote-containers|ms-|0.74.0
remote-ssh-edit-nightly|ms-|2019.9.6660
remote-ssh-explorer-nightly|ms-|2019.9.6660
remote-ssh-nightly|ms-|2019.9.6660
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
vscode-typescript-tslint-plugin|ms-|1.2.2
cloudenv|ms-|1.0.768
cloudenv-explorer|ms-|1.0.768
cloudenv-extensions|ms-|1.0.768
rescuetime|Res|1.0.1
code-settings-sync|Sha|3.4.2
errorlens|use|2.7.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I think the same as https://github.com/microsoft/vscode/issues/78237
