### ISSUE TITLE
Cannot find name 'TerminalDimensions'.

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode#80428]
Our extension build is failing with the following:

vscode.proposed.d.ts:717:24 - error TS2304: Cannot find name 'TerminalDimensions'.

717     readonly dimensions: TerminalDimensions;
                             ~~~~~~~~~~~~~~~~~~

vscode.proposed.d.ts:751:24 - error TS2304: Cannot find name 'TerminalDimensions'.

751     readonly dimensions: TerminalDimensions | undefined;
                             ~~~~~~~~~~~~~~~~~~

vscode.proposed.d.ts:852:53 - error TS2304: Cannot find name 'Pseudoterminal'.

852     constructor(callback: (thisArg?: any) => Thenable<Pseudoterminal>);
                                                          ~~~~~~~~~~~~~~

vscode.proposed.d.ts:859:41 - error TS2304: Cannot find name 'Pseudoterminal'.

I noticed those APIs were moved into vscode.d.ts in afe912070e91fb5d33a66182788c934a933c19c8 but I don't see an update available at https://www.npmjs.com/package/vscode. When will the update be published? Are there workarounds in the mean time? This build break is currently blocking our check-ins.

Thanks!

**Comment by Tyriar** [comment]
@octref do you know how I'm meant to workaround this? `TerminalDimensions` moved to stable in master, but proposed still depends on it? Can/should it be redefined in vscode.proposed.d.ts as well until October just to workaround this?

**Comment by octref** [comment]
> Can/should it be redefined in vscode.proposed.d.ts as well until October just to workaround this?

I think so. New APIs in master branch isn't visible to anyone (unless you are pulling it manually with `npx vscode-dts master`).

**Comment by Tyriar** [comment]
@sherryyshi you can see an explanation of what's going on here: https://github.com/microsoft/vscode-extension-samples/pull/212#discussion_r321520238

**Comment by sherryyshi** [comment]
After implementing the suggested mitigation steps, we get the following output when running tests:
```

Could not identify extension for 'vscode' require call from <project-root>\out\test\fileReporter.js. These are the extension path mappings:
        <%userprofile%>\.vscode\extensions\microsoft.devinsights-2019.8.23-1 -> Microsoft.devinsights
        <%userprofile%>\.vscode\extensions\microsoft.vscode-nmake-tools-2.0.190830005 -> Microsoft.vscode-nmake-tools
        <%userprofile%>\.vscode\extensions\ms-vscode.cpptools-0.25.1 -> ms-vscode.cpptools
....
```
