### ISSUE TITLE
Terminal does not appear

### ISSUE THREAD

**Issue by donaukinder** [microsoft/vscode#80420]
- VSCode Version:1.38.0
- OS Version: Mac OS Sierra 10.12

1. After installing vscode the terminal does not appear at all, before I had installed version 1.37 I saw it was this way and upgraded to version 1.38.0 and the bug persists. Can you help me ?
[VSCODE - PRINT](https://imgur.com/a/cVrcwMk)

**Comment by Tyriar** [comment]
Does zooming in and out help (ctrl++, ctrl+-)? Or setting this: `"terminal.integrated.rendererType":  "dom"`

**Comment by donaukinder** [comment]
I tried zoom ++ and zoom -- but it's still the same, where can I put this setting? => "terminal.integrated.rendererType": "dom"

**Comment by Tyriar** [comment]
cmd+, to open settings, there is then a file icon with an arrow in the top-right that brings you to the json file where you can paste that.

**Comment by donaukinder** [comment]
It worked, thank you very much!
