### ISSUE TITLE
Recently unsaved files do not show after restart of VS Code

### ISSUE THREAD

**Issue by miluke** [microsoft/vscode#80425]
Issue Type: <b>Bug</b>

VS Code  now always starts up with the Welcome Screen and does not show previously saven & unsaved files anymore. It works for a moment when I just re-install the latest version, but soon after the behavior changes again.
To reproduce:
Open CS Code
Create any new file, don't save it!
Close VS Code
Recopen VS Code.
Observed behavior is that VS code just shows the welcome screen, but NOT the unsaved file you opend in the session before.

Expected behavior is that VS Code shows all files from all sessions regardless is they where saved or not. In addition I would expect code not to show the welcome screen anymore once it was closed.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (25.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.46
vscode-markdownlint|Dav|0.30.2
gitlens|eam|9.9.3
gc-excelviewer|Gra|2.1.32
remote-wsl|ms-|0.39.5
Go|ms-|0.11.4
powershell|ms-|2019.5.0
sqltools|mtx|0.20.3
markdown-preview-enhanced|shd|0.4.3
vscode-autohotkey|sle|0.2.2
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by bpasero** [comment]
@miluke yeah the expected behavior is to reopen all dirty files and I just tried it with Code stable and cannot reproduce. 

Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.
