### ISSUE TITLE
RFE - Provide ability to expose/share settings form settings.json to the launch.json

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#8042]
Please could you provide the ability to expose (share) settings from the settings.json file to the launch.json file, using the dollar notation.

settings.json:
```json
"python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3"
```
launch.json:
```json
"pythonPath": "${settings.python.pythonPath}",
```

**Comment by isidorn** [comment]
Fixed by @DonJayamanne via PR #8784
