### ISSUE TITLE
Can't select adjacent strings as multiple selection

### ISSUE THREAD

**Issue by anseki** [Microsoft/vscode#8043]
- VSCode Version: 1.2.1
- OS Version: Windows 8/10

In multiple selection, when two or more selections adjoin, those are combined to single selection. Or, can't select those.

Case 1: With `foo foofoo bar foo bar`, I want to do something to `foo`.
![01](https://cloud.githubusercontent.com/assets/4763469/16299439/40354f90-3975-11e6-89da-d4c40c419469.gif)
1. I selected first `foo`.
2. I pressed `Ctrl+D` three times.
3. Then, It seems that four `foo`s were selected.
4. I pressed `x` key.

I expected `x xx bar x bar`, but result was `x x bar x bar`.
`foofoo` was selected as single selection.

Case 2: With `foofoo bar foo bar`, I want to do something to `foo`.
![02](https://cloud.githubusercontent.com/assets/4763469/16299444/487f21b2-3975-11e6-9511-e62cb217341f.gif)
1. I selected first `foo`.
2. I pressed `Ctrl+D`.
3. Then, only `foofoo` was selected, and another `foo` was not selected.

A string in "Find" text box was changed to `foofoo` when second `foo` was selected.

Case 3: I tried to select `foo` and `foo` as two selection by using mouse with `Alt` key.
![03](https://cloud.githubusercontent.com/assets/4763469/16299447/4ee3d0e8-3975-11e6-9dc8-ed3e2bc0628c.gif)

Those became single selection when those became adjacent strings.

**Comment by stewartadam** [comment]
Any ETA for resolution on this?

**Comment by alexandrudima** [comment]
This has been fixed with the fix for #6661
