### ISSUE TITLE
VScode hangs while debugging c++

### ISSUE THREAD

**Issue by nkgautam94** [microsoft/vscode#80436]
Issue Type: <b>Bug</b>

while debugging, in some cases breakpoints keep getting hang. Even after I stop debugging and close VScode, there is still a "lldb-mi" named process running which I have to manually kill using terminal

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.7.7
vscode-bazel|Baz|0.2.0
python|ms-|2019.9.34474
cpptools|ms-|0.25.1

</details>

**Comment by roblourens** [comment]
Please file this on the repo for the c++ extension and include more details.
