### ISSUE TITLE
Project references are not picked up (2)

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#80438]
- VSCode Version: 1.38.0
- OS Version: 10.14.6
- TypeScript version: tested with both 3.5.2 and 3.6.2

Steps to Reproduce:

`./tsconfig.json`:

```json
{
    "references": [
        { "path": "./src/tsconfig.json" },
        { "path": "./shared/tsconfig.json" }
    ],
    "files": []
}
```

`./shared/tsconfig.json`:

```json
{
    "compilerOptions": {
        "composite": true,
        "declarationMap": true,
        "outDir": "../target-shared/"
    }
}
```

`./shared/main.ts`:

```ts
export const foo = 1;
```

`./src/tsconfig.json`:

```json
{
    "compilerOptions": {
        "composite": true,
        "declarationMap": true,
        "outDir": "../target-src/"
    },
    "references": [
        { "path": "../shared/tsconfig.json" }
    ]
}
```

`./src/main.ts`:

```ts
import { foo } from "../shared/main";

foo;
```

1. Run `tsc --build` (observe no errors)
2. Open VS Code
3. Navigate immediately to `./shared/main.ts`
4. Find references for `foo`

Repo including the above test case: https://github.com/OliverJAsh/unsplash-ts-project-references/tree/orthogonal-folders

Expected: reference in `./src/main.ts` appears
Actual: reference in `./src/main.ts` does not appear

Also, renaming `foo` in `./shared/main.ts` does not propagate the change into `./src/main.ts`.

If I'm careful enough to navigate to `./src/main.ts` first, and then open `./shared/main.ts` afterwards, VS Code is aware that `foo` is used in both files. However, I don't believe this should be necessary.

When I open `./shared/main.ts`, I assume VS Code is stopping at `./shared/tsconfig.json` and looking no further. If it looked one level higher, it would find `./tsconfig.json`, which references `./src/tsconfig.json`, which in turn references `./shared/tsconfig.json`.

Does this issue occur when all extensions are disabled?: Yes

Potentially related:
- https://github.com/microsoft/vscode/issues/12463
- https://github.com/microsoft/vscode/issues/80423
- https://github.com/microsoft/TypeScript/issues/20185
- https://github.com/microsoft/TypeScript/issues/30823
- https://github.com/microsoft/TypeScript/pull/28261
- https://github.com/microsoft/TypeScript/pull/32028

**Comment by mjbvz** [comment]
This is an upstream TypeScript issue. I believe that https://github.com/microsoft/TypeScript/issues/30823 may track this problem. If you don't feel that covers your case, please open a new issue against TypeScript
