### ISSUE TITLE
int. terminal custom profile loading has broken after the few last updates(loads standard profile instead of custom)

### ISSUE THREAD

**Issue by KV34** [microsoft/vscode#80434]
Bug allways appears after a first launch of python script in debug mode.
I have custom terminal profile settings.
When I open integrated terminal in vscode it uses this custom profile.
But after I’ve run python script in debug mode once the terminal will use profile from ~/

In my settings.json I have the following settings:

    "terminal.integrated.shellArgs.osx": [
        "--rcfile", "/Volumes/DISK/projs/TechStuff/settings/profile"
    ],
    "terminal.integrated.env.osx": {"HISTFILE":"/dev/null"},
    "terminal.integrated.setLocaleVariables": false,

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:
1. Set custom intergated terminal profile settings. (maybe restart)
2. Open int. terminal, check  env. variables.
3. Run any python script in debug mode.
4. Check  env. variables. 

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
So step 2 was as you expected and step 4 was not as you expected?

**Comment by alkalinin** [comment]
I have the same issue is the two latest releases. Before it works. 

#### 1. I have configuration to launch python by {Ctrl + F5} in the integrated terminal, my launch.json:
```JavaScript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

#### 2. My integrated terminal is configured to use custom variables
```JavaScript
	"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
	"terminal.integrated.shellArgs.windows": [
		"/K",
		"C:\\Dev\\ConsoleZ\\vars-python-3.7.bat"
	],
```

#### 3. This custom terminal load the custom settings

![image](https://user-images.githubusercontent.com/1408589/64434324-9abebb00-d0c0-11e9-8033-81fbfe6fed1f.png)

#### 4. However, the python debug console does not use custom settings

![image](https://user-images.githubusercontent.com/1408589/64434427-d063a400-d0c0-11e9-91f2-e2ab12f47cc6.png)

Only default 'cmd' is used

**Comment by KV34** [comment]
> So step 2 was as you expected and step 4 was not as you expected?

yes, at step 2 it returned vars from my custom profile 
and at step 4 - from standard

**Comment by Tyriar** [comment]
This is related to the python extension https://github.com/microsoft/vscode-python

**Comment by DonJayamanne** [comment]
@tyriar not sure how this is an issue with the extension.
The extension doesn't control loading of profiles or executing any shell scripts, I always thought this was vscode (terminal). Please could you elaborate on this further?

**Comment by Tyriar** [comment]
@DonJayamanne it works in the regular terminal but not Python Debug Console. Can you link to where the terminal env is setup in the extension?
