### ISSUE TITLE
Invisible Characaters

### ISSUE THREAD

**Issue by asifiqbal** [microsoft/vscode#80443]
It is putting **M-BM-**  on my space and squashing it

When I type for example `set log-collector-exporter` on my yaml file it prints as `setlog-collector-export`. `cat -v file` shows it is writing `setM-BM- log-collector-exporter`. I wrote same code in with VIM and no problem.

This is severely hurting my coding with ansible expect module. I use that a lot.

**Comment by alexandrudima** [comment]
@asifiqbal I cannot reproduce. Does this reproduce when disabling all extensions?

**Comment by alexandrudima** [comment]
@bfelbo have you tried disabling all extensions?
