### ISSUE TITLE
vscode can not become foreground window after hit a breakpoint

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#80441]
- VSCode Version: 1.37.0
- OS Version: win10

Steps to Reproduce:
I am developing a vscode extension, and in windows I see that after hit the breakpoint, the vscode can not become the current foreground windows, and only flashes on the windows status bar. 
![vscode focus issue 2](https://user-images.githubusercontent.com/2315155/64394607-9034ff00-d089-11e9-81d9-b53a2350ee31.gif)

The repro steps:
1. Create a python file and paste the follow codes:
```python
import tkinter as tk
from tkinter import messagebox

root= tk.Tk() # create window

canvas1 = tk.Canvas(root, width = 1200, height = 1200)
canvas1.pack()

def ExitApplication():
    MsgBox = tk.messagebox.askquestion ('Exit Application','Are you sure you want to exit the application',icon = 'warning')
    if MsgBox == 'yes':
       root.destroy()
    else:
        tk.messagebox.showinfo('Return','You will now return to the application screen')
        
button1 = tk.Button (root, text='Exit Application',command=ExitApplication)
canvas1.create_window(150, 150, window=button1)
  
root.mainloop()
```
2. add breakpoints on line 6 and 10
3. debug this python file
4. Click the button "Exit application"

Result: vscode got the breakpoint hit, but it doesn't become the foreground window.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this.
Make sure that you did not change the value of the setting `debug.focusWindowOnBreak` 
Also can you F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/dd7daae7de1d229280400ab9ddc20973fb3178bb/src/vs/workbench/contrib/debug/browser/debugSession.ts#L724) and investigate why the window does not get focused. It also might that the electron is not respecting our focus call.
