### ISSUE TITLE
vscode Not completely sinicized

### ISSUE THREAD

**Issue by lbzli** [microsoft/vscode#80449]
Issue Type: <b>Bug</b>

The Sinicization of my old version of vscode is complete. It includes a preview prompt similar to markdown (sinicization prompt), and a sinicized version of GIT management menu.
When I updated vscode on the night of 2009/09/05, the Sinicization of vscode was no longer complete.
I tried to go back to the old version, but it didn't work.
By the way, I also updated the Windows system that night. I don't know if that's the reason. If so, can I solve this problem?
I am a student with poor English proficiency. I like vscode very much. Part of the reason is that the Chinese culture is very good. Of course, there are other perfect performances of vscode.
So I don't think this problem should appear in this perfect product. I hope you can fix it.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2397)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.83GB free)|
|Process Argv|C:\Users\Administrator\Desktop\vue-cms|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
vue-snippets|hol|0.1.11
vs-docblock|jer|0.5.6
vscode-language-pack-zh-hans|MS-|1.38.2
vetur|oct|0.22.2
material-icon-theme|PKi|3.9.0
view-in-browser|qin|0.0.5
LiveServer|rit|5.6.1
js-jsx-snippets|sky|0.8.0
addDocComments|ste|0.0.8
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by sbatten** [comment]
@lbzli I am sorry if I am misunderstanding your issue, but it sounds to me like you are talking about localization for the chinese language pack in VS Code for the latest update. If this is true, please file your issue at https://github.com/Microsoft/vscode-loc
