### ISSUE TITLE
cmd flashing when editing code

### ISSUE THREAD

**Issue by Markpajr** [microsoft/vscode#80440]
Issue Type: <b>Bug</b>

Whenever I type something into an active file, the cmd prompt flashes on my screen. I don't know how this can be reproduced, but the steps for me to create the error:
1. Open any file
2. Type anything, even one character
3. Watch the files in the explorer that I'm editing change color briefly, then a cmd prompt appear and disappear on screen twice. 
Title of the command window is C:\\Users\Owners\Anaconda3\Scripts\conda.exe. Not sure if this is related.

Setup: Coding primarily python, installed via Anaconda
Latest version of VScode (August update). This did not happen before I updated.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.7.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
gitlens|eam|9.9.3
file-icons|fil|1.0.19
kite|kit|0.96.0
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34474
atom-keybindings|ms-|3.0.6
csharp|ms-|1.21.1
team|ms-|1.149.2
material-icon-theme|PKi|3.9.0
vscode-yaml|red|0.5.2
code-settings-sync|Sha|3.4.2
vscode-spotify|shy|3.1.0
vscode-icons|vsc|9.3.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
First try disabling extensions that look like they might be related to the rogue window. Can you still repro the problem? If not, report it as an issue with the offending extension.

**Comment by sbatten** [comment]
agree with @gjsjohnmurray 
/needsMoreInfo

**Comment by Markpajr** [comment]
Alright, I've proceeded to disable every extension and reload VScode. The problem continues, when I type anything at all into a file the command terminal flashes on the screen twice roughly 2 seconds after I stop typing. Doesn't seem to be an extension issue.

**Comment by sbatten** [comment]
if you open an untitled file (Ctrl+N) and modify its contents without saving the file, does the issue reproduce?

**Comment by Markpajr** [comment]
Yes, I tried with both new files and current files. Weirdly enough though, I've been away for the weekend and came back today and it seems to be fixed, though I haven't changed a single thing or restarted. I'd say this can be closed because without knowing exactly what was causing it or being able to continue reproducing it, I don't know where else this could go unless the problem returns.

**Comment by BingSlient** [comment]
Me too, can't find a solution...

**Comment by BingSlient** [comment]
In my case, only when I edit python file and save it, the cmd window flashes. I did try to disable every extensions but didn't work. 
<img width="958" alt="2019-09-09 (3)" src="https://user-images.githubusercontent.com/16046928/64522197-107a8f00-d32c-11e9-9403-ae61d4da1fa9.png">

**Comment by Markpajr** [comment]
@BingSlient  That was the exact window I was getting. And it could be happening on save, I have autosave enabled and do the majority of my work in python files. But, it just stopped happening to me, I don't have a solution because I didn't change anything I was doing.

**Comment by BingSlient** [comment]
@Markpajr I even reinstalled VS code, still didn't work. Now I have to disable autosave to avoid the annoying windows, seems that's the only workaround for me, or I have to stop using Anaconda with vscode.

**Comment by md2perpe** [comment]
I'm having the same problem. A cmd window flashes twice when I press <kbd>CTRL</kbd><kbd>S</kbd> in a **python file** (but not in any other type of file as far as I have seen).

It appears also in VS Code Insider (commit 0f1bd7721b793ed8b7805ba621061ce5a1f5c263).

**Comment by sbatten** [comment]
Can everyone try editing the files in the files in an external application when this reproduces? E.g. open the same file you are editing in Code in Notepad instead and make changes and save. My suspicion is some kind of file watcher installed by Anaconda.

**Comment by Markpajr** [comment]
Issue is back for me, and I can confirm on my end editing the file in notepad then saving causes the same window to appear. It appears twice in vscode, just once when I save the notepad file. Assuming this is an anaconda specific issue then if it's the same case for others.

**Comment by md2perpe** [comment]
@sbatten. You're right. I closed VS Code and opened a python file in Notepad. When saving the file the cmd windows still flash. So I assume that this issue can be closed.

**Comment by md2perpe** [comment]
It seems to be an issue with [Kite](https://kite.com/). When I quit Kite, the issue stops. When I start Kite, the issue starts again.

**Comment by Markpajr** [comment]
@md2perpe Interesting, I didn't think of kite, exiting the kite copilot program causes the issue to stop for me as well. It just started recently though, I don't believe Kite recently updated? Either way, seems the issue isn't directly VSCode related, so we can close this.

**Comment by md2perpe** [comment]
It might be that the last update of VSCode affected something that Kite calls. I've sent a message to the Kite developers and referred them to this issue.

**Comment by its-dhung** [comment]
Thanks for bringing this to our attention. We have a fix for this that should get released soon.

**Comment by its-dhung** [comment]
This has been fixed in the 20190910 release. Thanks again for helping us fix this!
