### ISSUE TITLE
absolutely not self explaining

### ISSUE THREAD

**Issue by serg1964** [microsoft/vscode#80446]
🚨 The issue tracker is not for questions 🚨

Hello,

IMHO, from the very beginning of using this product we've got the issue without reading Doc. We;'re firmly beehive that any (Ieditor,IDE) should be self explained. In your case -  for instance, lets go to the "File"  menu and click "New Few" -- what type of file should be opened  - "Java", "Python" ,""JavaScript or etc."  or something else ? Even the first step it looks pretty confusing. IMHO, this approuch looks wrong, 

Thanks,

**Comment by sbatten** [comment]
VS Code is not language specific and can be used as an editor for many types of files. Please see our documentation https://code.visualstudio.com/docs for help with getting started.
