### ISSUE TITLE
ts文件不能使用name作变量名

### ISSUE THREAD

**Issue by YSHIDM** [microsoft/vscode#80450]
- VSCode Version: 1.38
- OS Version: win10 1803

Steps to Reproduce:

1. 新建ts文件（或未保存文件设置为ts语言模式）
2. 使用 const 或 let 定义变量 name
```
const name:string = 'tom'
```
提示 'name' was also declared here.
3. 疑似原因
VS code 安装目录：Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts 中19515行已经定义了name
```
declare const name: never;
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jiangyuqiao** [comment]
https://stackoverflow.com/questions/43586243/why-is-a-global-name-variable-declared-in-typescript-and-can-i-avoid-using-it

**Comment by sbatten** [comment]
please see @jiangyuqiao 's comment
