### ISSUE TITLE
Syntax highlight issue in .tsx files using generics

### ISSUE THREAD

**Issue by mbilling** [Microsoft/vscode#8045]
- VSCode Version: Code - Insiders 1.3.0-insider (5eaf9f05038b0a9818ebff510e1aafe07ac1ae68, 2016-06-23T05:07:59.360Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Create new .tsx file
2. Paste following

```
let a = Array<number>();   // Highlight ok here

interface egGenericsInArray {
   a: Array<number>;   // Highlight fails here with generics
}
let s = "anything fails here...";

```

![vscode sh bug](https://cloud.githubusercontent.com/assets/973790/16300008/c51b01c4-393d-11e6-8c18-0321744f5d7c.PNG)

Syntax highlight breaks after Array<number>

**Comment by kunnix** [comment]
Temporary workaround: adding spaces around brackets.

Syntax highlight broken with .tsx files in Visual Studio Code 1.3.0-insider:

```typescript
interface test {
  a: Array<number>,
  b: string
};
```

Temporary workaround:

```typescript
interface test {
  a: Array< number >,
  b: string
};
```

**Comment by mbilling** [comment]
One can even just make a single space
 :)
```
interface test {
  a: Array< number>,
  b: string
};
```

Thanks for the workaround!

**Comment by prencher** [comment]
This is wrecking all kinds of havoc on our code base highlighting in the 1.3.0 release. Can a fix please be prioritized?

**Comment by joaomoreno** [comment]
@aeschli @dbaeumer Forward this to TypeScript if that's the case.

**Comment by psulek** [comment]
@mbilling Even when space within Array is workaround it is not suitable for project with 200+ ts files where at least half of them has Array<T>. So weird that this issue was reported 15 days ago and was not fixed into final release of 1.3.

**Comment by aeschli** [comment]
I reverted tsx to the version we had in 1.2. ts and js still have the changes for https://github.com/Microsoft/TypeScript-TmLanguage/pull/19 which seems to work well.

**Comment by mcaballeropinto** [comment]
Awesome! 

How can I get the version that contains the patch? When will it be shipped?

Thanks!

**Comment by mbilling** [comment]
Install insiders version of vscode. Latest update from this morning includes the patch
https://code.visualstudio.com/insiders

**Comment by psulek** [comment]
@mbilling Do you release "fix" release as public for this same as was for 1.2.1 version? I think its breaking critical bug to be able to use public 1.3 release without this fix!

**Comment by mbilling** [comment]
Agree. I'm just not in the release chain. I only raised the issue.
I guess someone is on it - or i hope :-)

**Comment by aeschli** [comment]
We will have a release with the fix in the coming days.

**Comment by ianks** [comment]
@aeschli I am still having this issue. I think we should re-open it:

![img](https://s3-us-west-1.amazonaws.com/adhawk-random-public/vscode-syntax-tsx.png)

### Version info:

```
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
Date 2016-09-12T13:22:54.636Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

**Comment by joaomoreno** [comment]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/22350/18578330/a929cd66-7bef-11e6-88dd-5a6d3343ec04.png)

1.6.0-insider
0619ede1e469ed23fbb214eaa0377625a402ca87

Seems to be fixed in latest.

**Comment by Meowtimer** [comment]
<img width="644" alt="screen shot 2016-09-25 at 4 42 01 pm" src="https://cloud.githubusercontent.com/assets/322565/18815957/04d8b694-833f-11e6-8445-c26deb866290.png">

<img width="658" alt="screen shot 2016-09-25 at 4 41 40 pm" src="https://cloud.githubusercontent.com/assets/322565/18815958/0506acde-833f-11e6-8fd5-2c778a4fe4c8.png">

**Comment by joaomoreno** [comment]
ping @aeschli

**Comment by jwulf** [comment]
Broken for me in a .tsx file. 

```
Version 1.9.0-insider (1.9.0-insider)

f2379e882b415e2c503a723776c4431a40d7c1aa

2017-01-02T07:03:01.993Z
```

![screen shot 2017-01-02 at 10 41 35 pm](https://cloud.githubusercontent.com/assets/406975/21589699/46f84284-d140-11e6-8dc9-438da121c2f3.png)
![screen shot 2017-01-02 at 10 41 41 pm](https://cloud.githubusercontent.com/assets/406975/21589700/487030cc-d140-11e6-8807-385cdbd873f6.png)

**Comment by jwulf** [comment]
*Removing* the space between the component and the angle bracket works around it!

<img width="757" alt="screen shot 2017-01-03 at 10 09 12 am" src="https://cloud.githubusercontent.com/assets/406975/21597844/ba4921e8-d19c-11e6-92fa-8c7c8f649389.png">
