### ISSUE TITLE
How to on folding ( hide/show code sections )

### ISSUE THREAD

**Issue by ihor-c** [microsoft/vscode#80459]
In vsCode disapear folding arrow
![Annotation 2019-09-06 104943](https://user-images.githubusercontent.com/33926674/64410608-10606200-d094-11e9-866d-9c6a400d6d43.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What version and on what platform? Give us the info from the `Help: About` command.

Does the problem also occur when all extensions are disabled? Try the 'Developer: Reload Window With Extensions Disabled` command.
