### ISSUE TITLE
Search for `#` never completes

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#80455]
1. Open search in our `vscode` repo
2. Set `files to include` to `./extensions/git/src`
3. Search for `#`

It never seems to complete.

![image](https://user-images.githubusercontent.com/22350/64409148-9b3b5f80-d088-11e9-8468-c9573d43ce2e.png)

**Comment by roblourens** [comment]
From 250c58e66d4f79c86d85e9c6a03b5e432faf43b3, thanks
