### ISSUE TITLE
VSCode does not surface errors resulting from SetDataBreakpoints requests.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#80452]
- VSCode Version: 1.38
- OS Version: Ubuntu 18.04

At the moment, VSCode seems to assume that a successful return from `DataBreakpointInfoRequest` automatically means that setting a data breakpoint on that variable will succeed.   It ignores the `verified` flag returned in `SetDataBreakpointsResponse`, nor does it show the attached `message`.   

This is very unfortunate, because in native code, there is a multitude of reasons why data breakpoint creation may fail, and it isn't really possible to predict the outcome in advance.   
  
Would be nice to have some way of surfacing failures in `SetDataBreakpoints`  to the user.

**Comment by isidorn** [comment]
Please try it out with VSCode insiders tomorrow and let us know how it behaves.
Thanks!

**Comment by vadimcn** [comment]
Confirmed working in 2019-09-23 insider build.

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label.
