### ISSUE TITLE
Split terminal doesnt work properly after the recent update.

### ISSUE THREAD

**Issue by manoj398** [microsoft/vscode#80453]
- VSCode Version: 1.39.0.insider
![image](https://user-images.githubusercontent.com/11410788/64405718-80bfb100-d09d-11e9-89f6-b15803a2ea3d.png)
- OS Version: Win 10 Pro, 1903, OS Build : 18362.10014

Steps to Reproduce:

1. Use Split Terminal button / Ctrl + Shift + S
2. On clicking once. Two terminal windows should be present. But the other terminal window gets opened but not visible.

**Comment by gjsjohnmurray** [comment]
Is this #80404 ? Does it still reproduce in today's Insider?

**Comment by jcserracampos** [comment]
@gjsjohnmurray It was fixed today.
@manoj398 is not using the last insiders build.

**Comment by manoj398** [comment]
> Is this #80404 ? Does it still reproduce in today's Insider?

Yes it is the same issue. Sorry for posting without checking.
