### ISSUE TITLE
Disk Memory is 100% used VSCode

### ISSUE THREAD

**Issue by Sanjaypb10** [microsoft/vscode#80454]
100% disk usage problem. Looking at the numbers in the task manager. August 2019 release of Visual Studio Code.  Version 1.38

![Disk](https://user-images.githubusercontent.com/47351958/64406390-4f47e500-d09f-11e9-898e-0fe28f5ded62.jpg)

**Comment by sbatten** [comment]
@Sanjaypb10 Can you elaborate on the workload you are running from VS Code. Also, does this usage remain or is it temporary?

/needsMoreInfo
