### ISSUE TITLE
Python interpreter

### ISSUE THREAD

**Issue by SylwekGr** [microsoft/vscode#80458]
Issue Type: <b>Feature Request</b>

Hi all
I have installed two python versions: Python 2.7 & Python 3.7 and use both of them in my programming. In every py script file I add shebang line in the begging (#! C:\Python27\python.exe or #! C:\Python37\python.exe). Is there is an possibility for VSC to set/save Python interpreter for single file, not for entire instance?. It is annoying for me, when I got an errors, after changing python version, and other py files are written in second python.

![Untitled](https://user-images.githubusercontent.com/54976524/64408995-531c3d00-d088-11e9-9aef-d01b3dd5516b.png)
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

**Comment by SylwekGr** [comment]
My VSC works OK on listed issues: 
I can change python interpreter
Perfectly recognize opened py files
I can run them in the terminal
In my work I have loots of opened py files written in both python versions. If I set python interpreter to version 2.7 then errors show for all files written in Py-3.7and vice versa.
It well be nice to set python interpreter per file, not for all opened files.

**Comment by sbatten** [comment]
This feature request is suited for the python extension you are using. Assuming you are using this [Python Extension](https://github.com/Microsoft/vscode-python), please file your issue there.
