### ISSUE TITLE
fetchTasks blocked when using in extensions in vscode 1.38.0

### ISSUE THREAD

**Issue by checkin001** [microsoft/vscode#80465]
I developed a vscode debug extension using vscode.debug.registerDebugAdapterDescriptorFactory , everything works fine until vscode updated to 1.38.0.
When start debug button is clicked, loading progress does not stop, and when click on stop debug button, it has no response too.
The process stucked in await vscode.tasks.fetchTasks, and there‘s no onrejected callback.
`        const buildTasks = await vscode.tasks.fetchTasks({
            type: 'build'
        })`
This task is registered in extension's package.json in "contributes": 

`		"taskDefinitions": [
			{
				"type": "build",
				"required": [],
				"properties": {
					"config": {
						"type": "string",
						"description": "Configuration",
						"default": "develop"
					}
				}
			}
		]`

- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6

**Comment by alexr00** [comment]
@checkin001 do you have an example I can try this with? Where is `fetchTasks` being called from?

**Comment by checkin001** [comment]
> @checkin001 do you have an example I can try this with? Where is `fetchTasks` being called from?

I did find a workaround to fix this. fetchTasks is called in extension.js .Originally, I use this code to fetch buildTask:
`const buildTasks = await vscode.tasks.fetchTasks({
 type: 'build'})
const buildTask = buildTasks.shift()`

when I change it to code below, it works fine
`const buildTasks = await vscode.tasks.fetchTasks()
        const buildTask = buildTasks.find((t) => {
          return t.name === 'Build' && t.source === 'Workspace'
        })`
