### ISSUE TITLE
Can't persist word wrap on linux

### ISSUE THREAD

**Issue by newtonmunene99** [microsoft/vscode#80460]
When I toggle word wrap in VS Code it's in effect for a few seconds then toggles itself off.I've never experienced this on windows

- VSCode Version: 1.38.0
- OS Version: Zorin OS 15 / Linux x64 5.0.0-27-generic

Steps to Reproduce:

1. Toggle word wrap from view/toggle word wrap or in settings
2. Scroll document.

Does this issue occur when all extensions are disabled?: No, seems not

**Comment by alexandrudima** [comment]
@newtonmunene99 I cannot reproduce. Does this reproduce when disabling all extensions?
