### ISSUE TITLE
When vscode gets focus, input method is reset default state

### ISSUE THREAD

**Issue by bluesiboy** [microsoft/vscode#80462]
Issue Type: <b>Bug</b>

vscode is an English input state, and when you switch to vscode again, you become Chinese input state.
Because my input method defaults to Chinese input status.

im sure open [ use different input method for each app window] 
system version: windows 10 20h, 1903, 18970.1005

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18970

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexandrudima** [comment]
@bluesiboy VS Code simply respects what the OS configuration is:

Please be aware that Windows 10 allows to configure that each app window has a different input method, and I think you are describing this exact behavior: 

![image](https://user-images.githubusercontent.com/5047891/64593239-07320680-d3ae-11e9-8199-d9dab81db3d5.png)
