### ISSUE TITLE
Auto-import imports paths relative to baseUrl

### ISSUE THREAD

**Issue by artyshan** [microsoft/vscode#80468]
Issue Type: <b>Bug</b>

**Steps to Reproduce:**
1. create TypeScript project with `baseUrl` included in `tsconfig.json`
2. type something from another ES6 module to trigger auto-importer

**Expected results:** Auto-importer imports the module by the path relative to current module

**Actual results:** Auto-importer imports the module by the path relative to `baseUrl`

**Reproduces without extensions:** Yes

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
Angular-BeastCode|Mik|8.0.10
vscode-less|mrm|0.6.3
gitpatch|par|0.2.1
expand-selection-to-scope|vit|0.2.0
gitblame|wad|3.0.1

</details>

**Comment by mjbvz** [comment]
Please share your full `tsconfig`

Also, did you try setting `"typescript.preferences.importModuleSpecifier": "relative"`?

/needMoreInfo
