### ISSUE TITLE
Avoid parsing program args in rawDebugSession

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#80461]
The code in https://github.com/microsoft/vscode/blob/fe44d14e71ad3d0dc357bee26c9b5085651cd492/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L573
tries to convert the VSCode program args to a `ParsedArgs` object.

This code should rather be done on the main side where we have  https://github.com/microsoft/vscode/blob/fe44d14e71ad3d0dc357bee26c9b5085651cd492/src/vs/platform/environment/node/argv.ts#L112

To correctly parse the arguments, meta-info about the argument types is needed. We use `minimist` so it would be the easiest to just do it in main. 

-> change `openExtensionDevelopmentHostWindow` to take program args (string[]) instead of ProgramArgs

**Comment by weinand** [comment]
Actually, in `rawDebugSession.ts` we are not parsing program args in the same way as minimist would do in main. 

In `rawDebugSession.ts` we are receiving the arguments from the node-debug2 debug adapter in a special format that allows the uri rewriting to do its work. 

The marshalling takes place in [node-debug2](https://github.com/microsoft/vscode-node-debug2/blob/965054f347a8f4ea4a690f82083e9ad8f708633e/src/nodeDebugAdapter.ts#L243-L294) and the unmarshalling in [VS Code](https://github.com/microsoft/vscode/blob/fe44d14e71ad3d0dc357bee26c9b5085651cd492/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L567-L622).

**Comment by weinand** [comment]
I've created a fix in this branch:
https://github.com/microsoft/vscode/tree/aweinand/remove_parsedArgs

Please give it a try. It should not break any form of extension debugging (local, remote, Web UI).

**Comment by isidorn** [comment]
@weinand thanks. I have created PR https://github.com/microsoft/vscode/pull/81307
I will try it out and if it works nicely I will merge it in.

**Comment by isidorn** [comment]
As commented in the PR
"There are conflicts with the master branch since Ben moved a lot of code around. And I see no rush to do this before endgame since this is debt."
Thus moving to October.
