### ISSUE TITLE
Enable "Auto guess encoding" by default

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#80479]
This is a rather minor one, yet it may solve quite a lot of confusion (I myself believed this option was enabled by default until I found myself having saved a file with a false encoding).

Auto guess encoding should be enabled by default, like other text editors do, too.

**Comment by bpasero** [comment]
I would stay away from doing that as the quality of the guess is not good enough.

**Comment by SetTrend** [comment]
Why should it be worse than not guessing at all - and be wrong anyway?

From my perspective, The guessing workflow may be rather easy:

```typscript
const text: string = ...;
let encoder: Encoding;

const encoding: string =
  (encoder = new Encoding("utf8")).IsValid(text)
    ? "utf-8" + (encoder.hasBOM ? " with BOM" : "")
    : (encoder = new Encoding("utf16")).IsValid(text)
      ? "utf-16" + (encoder.hasBOM ? " with BOM" : "")
      : (encoder = new Encoding("utf32")).IsValid(text)
        ? "utf-32" + (encoder.hasBOM ? " with BOM" : "")
        : WorkspaceOrUserSetting.DefaultEncoding;
```
