### ISSUE TITLE
translate to new locale

### ISSUE THREAD

**Issue by tienhv** [Microsoft/vscode#8047]
Hi, I want to contribute to a new locale "Vietnamese", what should I do? Thank you

**Comment by dbaeumer** [comment]
@tienhv this is currently not possible.

**Comment by coreh** [comment]
A translation/localization API (so that extensions could install support for new locales) would be really neat.

**Comment by dbaeumer** [comment]
@coreh this is actually possible. See the two node modules vscode-nls and vscode-nls-dev. And may be vscode-node-debug and an example on how to use them.

**Comment by dbaeumer** [comment]
We move our translations to Transifex which can be used to translate to different locales.
