### ISSUE TITLE
Add a "Save" menu item to open editor tabs

### ISSUE THREAD

**Issue by johndaintree** [microsoft/vscode#80470]
Visual Studio has a "Save file" item on the context menu of the tab of open editors. I miss this in code. Having to move back to the File menu is a bit of a pain.

**Comment by isidorn** [comment]
It already exists in the OPEN EDITORS view 
![Screenshot 2019-09-09 at 10 19 39](https://user-images.githubusercontent.com/1926584/64514698-6d098a00-d2eb-11e9-846d-0af94debd631.png)

I believe you want it in the Tab area of the editor, thus forwarding to @bpasero so he can decide
