### ISSUE TITLE
extension host consumes a lot of memory

### ISSUE THREAD

**Issue by vvavrychuk** [microsoft/vscode#80476]
Issue Type: <b>Performance Issue</b>

No clear steps to reproduce.

If this can be a problem of a particular extension then how can I find out what extension is a problematic one.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-60-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|31.30GB (3.29GB free)|
|Process Argv|../../../|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   160	 10854	code main
    0	     0	 10858	   zygote
    0	    32	 10967	     shared-process
    0	     0	 25339	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    64	 25313	     window (Issue Reporter)
   28	   705	 28442	     window (Android.txt - Android - Visual Studio Code)
    0	  9935	 28465	       extensionHost
    0	     0	 28523	         electron_node server.js 
    0	     0	 28918	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=28465
    0	     0	 28466	       watcherService
    0	    32	 10897	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (glmark2 - Visual Studio Code)
|  Window (2019_09.txt - note - Visual Studio Code)
|  Window (Android.txt - Android - Visual Studio Code)
|    Folder (Android): 17 files
|      File types: txt(9) gitignore(1) html(1) pdf(1) code-workspace(1)
|                  json(1) png(1) docx(1)
|      Conf files: makefile(1) settings.json(1)
|    Folder (note): 323 files
|      File types: txt(300) html(7) pdf(4) dat(3) json(2) editorconfig(1)
|                  htm(1) png(1) md(1) c(1)
|      Conf files: settings.json(2) makefile(1)
|    Folder (glmark2): 2404 files
|      File types: d(509) o(504) c(286) h(214) asm(124) cpp(110) png(102)
|                  py(80) frag(78) vert(70)
|      Conf files: makefile(2);
```

</details>
<details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
QML|bbe|1.0.0
vscode-opennewinstance|chr|0.0.6
systemd-unit-file|coo|1.0.4
tslint|eg2|1.0.44
bitbake|Eug|1.1.2
local-history|gay|0.0.3
latex-workshop|Jam|8.1.0
open-folder-in-new-instance|jma|0.0.1
haml|kar|1.3.0
pasteurl|kuk|0.4.3
restructuredtext|lex|114.0.0
gnuplot|mam|1.0.4
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34474
cpptools|ms-|0.25.1
Go|ms-|0.11.4
veriloghdl|msh|1.0.3
devicetree|plo|0.1.1
tcl|ras|0.1.0
ruby|reb|0.25.3
java|red|0.48.0
vscode-open|san|0.1.0
fish-vscode|sky|0.2.1
vscode-asciidoc|sta|0.0.3
code-spell-checker|str|1.7.18
cython|tcw|0.1.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-open-in-application|fab|1.0.5
gitblame|wad|3.0.1
markdown-pdf|yza|1.2.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
Please see guidance here: https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by vvavrychuk** [comment]
@sbatten I saw it but I did not found there answer to my question: 'how can I find out what extension is a problematic one'?

**Comment by sbatten** [comment]
@vvavrychuk first, try to reproduce the issue with extensions disabled. 

>If you cannot reproduce the issue when all extensions are disabled, then can you narrow down the extension by selectively disabling extensions? You can disable extensions in the Extensions Viewlet and restart/reload.

I would focus on extensions that are likely to cause such an issue first like ones that are providing language features.
