### ISSUE TITLE
VSCode not abiding to settings.json (TypeScript still validating)

### ISSUE THREAD

**Issue by basickarl** [microsoft/vscode#80473]
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.10.0-32-generic

Steps to Reproduce:
index.js:
```
function Something() {
    this.something = function() {
        const some; // 'some' is declared but its value is never read.ts(6133)
    }
    const else; // Variable declaration expected.ts(1134)
};
const hello; // No TS error here
```
.vscode/settings.json:
```
{
    "typescript.format.enable": false,
    "typescript.validate.enable": false
}
```
Restart VSCode. Put the mouse over the variables in the file.

Does this issue occur when all extensions are disabled?: Yes

This is not the only issue I've seen with VSCodes TypeScript intellisense, on another project where I actually use TypeScript the intellisense does not detect updates to the `tsconfig.json` file nor changes I do to the code at times. I must restart VSCode to fix those issues. Seems like the quality of VSCode is starting to slip unfortunately now. :/

**Comment by sbatten** [comment]
@basickarl you are modifying a js file, I think you are looking for `javascript.validate.enable`
