### ISSUE TITLE
Failing to undo/Redo changes

### ISSUE THREAD

**Issue by edwin254** [microsoft/vscode#80475]
Issue Type: <b>Bug</b>

The last detail just added some code tcopy pasted it into anothe file, but when I try to undo it on the original file it doesn;t take effect.
Its happened a couple of times so far.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|1.0.120190617
vscode-markdownlint|Dav|0.30.2
githistory|don|0.4.6
gitlens|eam|9.9.1
prettier-vscode|esb|2.2.2
git-project-manager|fel|1.7.1
code-runner|for|0.9.10
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.7.0
vscode-kubernetes-tools|ms-|1.0.4
python|ms-|2019.6.24221
vetur|oct|0.22.2
vscode-yaml|red|0.5.2
LiveServer|rit|5.6.1
rust|rus|0.6.2
vue-vscode-snippets|sdr|1.8.0
rust-grammar|sib|0.1.0
code-spell-checker|str|1.7.17
gitflow|vec|1.2.1
vscode-icons|vsc|9.3.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@edwin254 Can you please provide clear steps? I cannot reproduce what you describe, undo works fine for me.
