### ISSUE TITLE
Add option to scale VS Code icons

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#80474]
The new Visual Studio Code icon set takes too much space, particularly on lower scale resolution screens. There's hardly space left for the code editor panel when Explorer and Terminal are open.

Hence, I'd like to propose to add a new setting to VS Code, providing the user with an option to scale down all VS Code icons (i.e. CSS `zoom` property) and another setting to scale down padding between icons.

**Comment by misolori** [comment]
@SetTrend can you post a screenshot as an example where it's taking up too much space? The icons are the exact same dimensions as the previous ones.

**Comment by SetTrend** [comment]
Gee, you are right, @misolori. It seems to have been an optical illusion.

Please pardon the inconvenience of this issue.
