### ISSUE TITLE
File compares hidden in recently opened

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#8048]
- VSCode Version: 1.2.1
- OS Version: WIN 10 x64

Steps to Reproduce:

1. Mark two files to compare

If you compare two files, the compare view doesn't show on the working files or anywhere but Ctrl+Tab.
It would be great to have those also visible somewhere when there are compare views open.
Maybe in another section above working files

**Comment by bpasero** [comment]
@con-ssc they do in the newly introduced "Opened Editors" view. you can try from our insiders build: http://code.visualstudio.com/Download#insiders

**Comment by con-ssc** [comment]
okay nice, sadly the Insiders Build Extension Functionality gets blocked by KES 10 :( So I cannot really use the Insiders build. The Stable one works btw. It's a known issue.

**Comment by bpasero** [comment]
@con-ssc KES 10?

**Comment by con-ssc** [comment]
Oh sorry for not explaining the acronym "Kaspersky Endpoint Security 10"
