### ISSUE TITLE
Workspace configs cannot be seperated between WSL-Remote and Windows

### ISSUE THREAD

**Issue by validatedev** [microsoft/vscode#80482]
- VSCode Version: 1.38.0
- OS Version: Windows 10 18362.329 1903

I have a WSL-Remote install with Pengwin distro that includes Python 3.7.3 Vanilla and in Windows 10 I have Anaconda Python 3.7.3. Trying the open .py files with both of them but when I try to switch with "Remote-WSL: Reopen Folder" in WSL (or doesn't matter how I open the .py files) the VSCode always gives the "No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging." error. Why is the error is WSL and Windows uses the same workspace settings (the settings.json contains "python.pythonPath" variable ) and when the environment changes, VSCode cannot read the path of the Python and gives the error. Because of that, the workspace config files should be seperated between Windows and WSL.
Steps to Reproduce:

1.Open any .py file
2.Try to switch between Windows and WSL using WSL-Remote

Does this issue occur when all extensions are disabled?: No because there isn't any instance of WSL without WSL-Remote

**Comment by aeschli** [comment]
What pythonPath do you have in the workspace settings? I assume it's a windows path, but not a WSL path.
For remote we now have the remote settings, I recommend you to define it there. It's stored on the remote 'machine' (WSL VM in this case). For local it should go into the user settings (until we add the machine settings also for local).
Workspace settings is not a good place for paths and only work if you do not share the workspace amongst machines and/or users.

**Comment by validatedev** [comment]
> What pythonPath do you have in the workspace settings? I assume it's a windows path, but not a WSL path.
> For remote we now have the remote settings, I recommend you to define it there. It's stored on the remote 'machine' (WSL VM in this case). For local it should go into the user settings (until we add the machine settings also for local).
> Workspace settings is not a good place for paths and only work if you do not share the workspace amongst machines and/or users.

The problem is, no matter what I define the path of the python on WSL-Remote settings or User settings, VSCode priorities the workspace settings first and even I delete the path on workspace settings, VSCode doesn't see my user and remote settings for the python path. It gives the same "No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging." error everytime.

**Comment by validatedev** [comment]
Oh my bad, misconfigured the settings. It works without any problem right now. Thanks for the clarification.
