### ISSUE TITLE
Defaults to using own Typescript version when one is specified in workspace settings (minor/first-time-only)

### ISSUE THREAD

**Issue by LolliDepp** [microsoft/vscode#80486]
Issue Type: <b>Bug</b>

Before updating to the latest version, VS Code was using the workspace version of typescript without having to do anything more than to specify a path in workspace settings. After the update, it defaults to its own TS version.

- [Optional] Create a new project, specify a path for `typescript.tsdk` in workspace settings
- Open a project with a valid path for `typescript.tsdk` in workspace settings
- VS Code runs own Typescript version instead of workspace version
- [Optional] point to another location for workspace's typescript
- [Optional] restart VS code
- [Optional] VS code still runs own version

Clicking on the version selector and choosing workspace will cause it to change successfully.
Restarting the application seems to remember this change, as once the workspace version has been selected, it will always be using the correct version even after restarting.

The issue is minor as once the selection has been made, it will be remembered.
Still, this caused a bit of an initial headache as I never had to go manually pick which version to use in the past

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
auto-close-tag|for|0.5.6
powershell|ms-|2019.5.0
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
vetur|oct|0.22.2
vscode-jest|Ort|3.0.2
tsimporter|pmn|2.0.1
stylelint|shi|0.51.0
slack|soz|0.0.14
vscode-icons|vsc|9.3.0

</details>

**Comment by mjbvz** [comment]
Having to select to use the workspace version the first time is by-design. We cannot automatically execute code (such as a typescript server) in a workspace without some sort of user action

Let me know if you can repo your selected version being lost. Maybe you changed the path of the workspace? Closing since it sounds like the issue went away though
