### ISSUE TITLE
Link protection ux is confusing

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#80489]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/35271042/64439671-5fe86300-d07f-11e9-9477-791ea9d496ed.png">

When clicking on "Configure Trusted Domains" you are sent to the picker which shows domain that you just clicked on in the list and checked:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/35271042/64439853-bce41900-d07f-11e9-9e8f-11485c7b9ec9.png">

This leaves you in a very confused state because it is now checked. So the natural thinking is since it's checked, why did it ask me to open the link? So I cancel the quickpick, click the link again and I get the same message. After inspecting it further, it appears that the "Configure Trusted Domains" actually adds the entry and you have to click on "Ok" to apply it. This is extremely confusing as the user has no idea this was added, this list is always treated as a static list.

Additionally, looking back on our notes from the last ux sync, I thought we all agreed the actions would be: Trust Once, Trust Always, Cancel. And the "Configure" part was going to be a setting? It appears like this isn't reflected at all.

**Comment by octref** [comment]
That came out of discussion at https://github.com/microsoft/vscode/issues/78125#issuecomment-521689062

> So the natural thinking is since it's checked, why did it ask me to open the link?

Would it make sense to make the message a bit different so it stands out? For example, everything below the separator -> already trusted domains. Top two options are:

- Open all links without prompt
- Trust new domain https://dev.azure.com and open link (and remove the faded details)

**Comment by misolori** [comment]
I don't think the message would improve the UX. Something that could help/improve is to have an action to add a domain when results are empty:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/35271042/64462981-2df2f300-d0b7-11e9-9c0b-b1fea873002b.png">

To me, "Configure Trusted Domains" does not equal "Add this domain" so we either should update the button text to indicate it's also adding, and then I'd auto-fill the input field to indicate that it's adding.

**Comment by octref** [comment]
See See https://github.com/microsoft/vscode/issues/80595#issuecomment-531607624
