### ISSUE TITLE
whitespace displayed in vscode is half as wide as other characters

### ISSUE THREAD

**Issue by Hexa4C** [microsoft/vscode#80481]
whitespace characters in my vscode is only half as wide as other characters. 
For example, 
![2019-09-06 20-55-39 的屏幕截图](https://user-images.githubusercontent.com/20607227/64429548-da010200-d0e8-11e9-8a62-363f5e2e49bc.png)
this is a part of a python script. There are six whitespace characters in the front of the second line. But as you can see, they are only as wide as three other characters.
I have tried disabling all the extensions, removing all my user settings, and updating my vscode. But nothing changed.
I think my issue is probably the same as that in https://github.com/Microsoft/vscode/issues/42090 .But this issued is closed and the solution doesn't work for me.

- VSCode Version: 1.38.0 
- OS Version:Ubuntu 18.04.2 LTS

PS:This problem occured few months ago, and only in my computer of the above OS version. it didn't happen in my computer with win10.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
It looks like you are not using a monospace font for your editor. Please verify that `editor.fontFamily` is set to a monospace font that is available on your OS.
