### ISSUE TITLE
Stash before Pull not working

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#80488]
Issue Type: <b>Bug</b>

I turned on "Git: Auto Stash" to stash any changes before pulling and restore them after a successful pull.  Now, when I have changes and choose "pull", I get an error:  "Git: usage: git stash list [ <options> ]".  There is a button to "Open Git Log", which shows:

> git stash push -u
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear

So it looks like my version of git (on Linux) does not know about "stash push" as an option.  I believe calling "git stash" will do the push (i.e., without the "push" parameter, or may take the "save" option for that instead if you need the "-u").

I'm running Code on Windows 10, but remotely developing on a Linux box running Ubuntu 16.4.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.08GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2Bandy-linux/home/gpudb/gpudb-dev-7.0/gpudb-core/gaiadb-cluster/Endpoint/.code-workspace.code-workspace|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: andy-linux|
|OS|Linux x64 4.15.0-58-generic|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 900)|
|Memory (System)|62.86GB (1.91GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-cudacpp|kri|0.1.1
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
vs-keybindings|ms-|0.2.0
code-gnu-global|aus|0.2.2
githistory|don|0.4.6
mssql|ms-|1.6.0
cpptools|ms-|0.25.1
java|red|0.48.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
gitblame|wad|3.0.1

</details>

**Comment by andyj513** [comment]
git --version reports: "git version 2.7.4"

**Comment by joaomoreno** [comment]
Please update to a newer git. :+1:

**Comment by andyj513** [comment]
> sudo apt upgrade git
> git is already the newest version (1:2.7.4-0ubuntu1.6).

**Comment by joaomoreno** [comment]
You can manually install a more recent version of Git in your Linux system.
