### ISSUE TITLE
change color theme messes up terminal fonts

### ISSUE THREAD

**Issue by jasonbronson** [microsoft/vscode#80485]
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. open terminal, change color theme and then back
2. terminal gets crazy on the font sizes

Does this issue occur when all extensions are disabled?: Yes

https://gyazo.com/2fd25e7148233e2efff400a82bb4c53f

resizing the window does fix it.

**Comment by Tyriar** [comment]
I can't repro here, can you share your settings.json file?
