### ISSUE TITLE
Load Remote-Container Error: Failed to connect to the remote extension host server (Error: n.window.createTerminalRenderer is not a function)

### ISSUE THREAD

**Issue by cat-hz** [microsoft/vscode#80490]
- VSCode Version: 1.38
- OS Version: windows 10
- Docker Desktop Version: 2.1.0.2(37877)

Steps to Reproduce:

1.Shift+Ctrl+P -> Remote-Container: Open Folder in Container
2.Select "Ununti 18.04...“

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Please update to the latest remote containers extension
