### ISSUE TITLE
Problem viewing auto-generated, updated jsconfig file via Problems panel

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#8049]
Using today's Insiders' build (details below), I clicked the green lightbulb in the bottom right, and created a jsconfig.json file, which you can see exposed via `cat` in the screenshot.

When I did a `CTRL+SHIFT+M` to list problems, I see that file is a problem, so I clicked on the link in the problem report pane, and see nothing, as in the screenshot.

![image](https://cloud.githubusercontent.com/assets/512816/16302780/f3655622-3944-11e6-8b40-3820dbc472a2.png)

![image](https://cloud.githubusercontent.com/assets/512816/16302794/048fcf36-3945-11e6-9bc4-26b090a71bfb.png)

**Comment by leegee** [comment]
Removing the trailing comma doesn't help.

**Comment by jrieken** [comment]
@aeschli Looks like a sticky error on the file

**Comment by aeschli** [comment]
@dbaeumer The JSON language service just validates the documents given by the language client.
It currently does not remove the makers when the document is closed. Dirk, let me know if that's what is expected from the language service.

**Comment by dbaeumer** [comment]
@aeschli I think that is the only solution that works consistently. If a service generates a marker then the service is responsible for removing it. If a linter stops validating closed files, then he removes it. But the linter could also decide to keep on validating and listening to file events to decide if a revalidation is necessary. What I could add to the language server protocol is to auto remove on close. But that must be an option which is false by default.

**Comment by aeschli** [comment]
The JSON mode now removes all markers when a document is closed
