### ISSUE TITLE
ascx comment closing tags have weird behavior

### ISSUE THREAD

**Issue by prolixus314** [microsoft/vscode#80493]
Issue Type: <b>Bug</b>

When using ascx comments , if the closing tag (normally -->) has three dashes instead of two (--->), VSCode makes all of the code after the closing tag green (colored as if it were a comment). This is not desired behavior, as only the content inbetween the `<!--` and `-->` (including any extra dashes) should appear as a comment.
To duplicate in VSCode:
1. open an existing ascx file that has code in it or create a new .ascx file and put some random nested divs in the file
2. In a line above a div tag, add a comment such as `<!-- This is a comment. -->`. Notice that all the code below the comment is colored normally.
3. Add an extra dash to the closing comment tag: ---> (should now be 
```<!-- This is a comment. --->```
) . Notice that the code below the comment is colored as if it were part of the comment. Also notice that the first two dashes in the closing tag are red/colored differently.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alexr00** [comment]
https://www.w3.org/TR/REC-xml/#sec-comments
