### ISSUE TITLE
Diff language does not highlight .diff or .patch files

### ISSUE THREAD

**Issue by deftdawg** [microsoft/vscode#80494]
Issue Type: <b>Bug</b>

I've tried to view files in either diff or diff -u format, neither highlight within the VSCode editor window, despite the language being correctly detected as 'Diff' in the status bar.  

The same diff files highlight correctly on VSCode 1.37.1 on Linux.

Sample file...
```diff
--- test.txt	2019-07-23 17:01:19.756927500 -0400
+++ test2.txt	2019-09-06 11:46:36.164507800 -0400
@@ -25,7 +25,6 @@
 
 
 
-
 a1b 2b3
 b2n 3l1
 G2B 3W1
```

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (5.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.4
ssh|chr|0.0.4
excel-to-markdown-table|csh|1.1.0
vscode-markdownlint|Dav|0.30.2
graphviz-markdown-preview|gee|0.0.8
ldif|jta|0.2.0
vscode-sshfs|Kel|1.16.3
oradew-vscode|mp|0.3.11
vscode-oracle-format|mp|0.1.5
vscode-docker|ms-|0.7.0
mssql|ms-|1.6.0
python|ms-|2019.9.34474
sqltools|mtx|0.20.3
oracle-plsql|myc|1.0.3
open-html-in-browser|pea|1.2.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.10.0
vscode-manifest-yaml|Piv|1.10.0
vscode-spring-boot|Piv|1.10.0
java|red|0.48.0
markdown-preview-enhanced|shd|0.4.3
shellcheck|tim|0.8.1
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@deftdawg do you still see the issue if you disable all extensions?

**Comment by alexr00** [comment]
Yep, it's probably worth filing an issue with the extension that causes the problem.
