### ISSUE TITLE
Warn on Save when auto-formatting fails

### ISSUE THREAD

**Issue by dutzi** [microsoft/vscode#80504]
When saving a file with `editor.formatOnSave` settings on it would be great if VSCode would issue a warning (A dialog modal asking if I'm sure I want to save this file) when formatting fails.

Otherwise the file would be saved, webpack/tsc would start processing the faulty file, I would have to fix the issue, re-save it and wait for webpack/tsc to finish processing the faulty file. 

This could save previous time when dealing with a large repository.

**Comment by jrieken** [comment]
Why is a non formatted file faulty? Formatting is all about inserting/removing whitespace and shouldn't impact compilation.

**Comment by dutzi** [comment]
Prettier fails when the file has syntax errors. Your second point is correct, but inserting/removing in a large repo, with Webpack source-maps enabled takes a bit of time (10sec per build)

This use-case might be too specific and it might very be that we're the only ones affected by it, I'm just throwing it out here.

**Comment by jrieken** [comment]
> Prettier fails when the file has syntax errors.

Yeah, that might be but then formatting isn't the issue but syntax errors are. That should already be reported in the editor (squiggles at el) and after saving the compiler should also tell you about those errors. It seems that the real issue is that you aren't happy with the compile speed in your project.

**Comment by dutzi** [comment]
Lol. You're probably correct. I'll try fixing that :)
