### ISSUE TITLE
The vscode often appears "Window Fault"

### ISSUE THREAD

**Issue by yangyankang** [microsoft/vscode#80509]
- VSCode Version: 1.37.1
- OS Version: win10

Steps to Reproduce:

1. when i open my projects in three windows, after a while one of windows will get this error

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@yangyankang is the window crashing? If so, can you take a look at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

If not, can you provide more info about what you are seeing? Perhaps with a screenshot?

**Comment by yangyankang** [comment]
![image](https://user-images.githubusercontent.com/26170482/64684586-f4a3f400-d4b7-11e9-9604-574436870bea.png)

**Comment by yangyankang** [comment]
This is the problem that i have .I have tried the tool you tell me ,but i cant find the file with the *.dmp suffix ,Now the interface of the sofaware is as follows 
![image](https://user-images.githubusercontent.com/26170482/64685038-cffc4c00-d4b8-11e9-9517-0c4be75df7c1.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
