### ISSUE TITLE
Can't update extension automatically or manually or install any new extension

### ISSUE THREAD

**Issue by AhmedMalekX** [microsoft/vscode#80508]
- VSCode Version: 1.38.0
- OS Version: windows 10 version 1809

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post details of what happens. Screenshots can usually be pasted directly. Also, did the problem only start happening after the 1.38 update?

**Comment by AhmedMalekX** [comment]
The Screenshots and yes this problem happened after the update to 1.38

![P1](https://user-images.githubusercontent.com/48364228/64472808-453bea00-d164-11e9-91b1-f6faa83df07a.JPG)
![P2](https://user-images.githubusercontent.com/48364228/64472809-453bea00-d164-11e9-87b1-13fdb759b68b.JPG)

**Comment by AhmedMalekX** [comment]
So Is there any solution for this problem?

**Comment by medo00001** [comment]
any help i have same issue

**Comment by AhmedMalekX** [comment]
@gjsjohnmurray Do you know any solution for this problem?

**Comment by gjsjohnmurray** [comment]
Maybe using a different DNS server will help. See https://github.com/microsoft/vscode/issues/34385#issuecomment-521286975 for a previous case where it did.

**Comment by AhmedMalekX** [comment]
The Problem solved thanks.
