### ISSUE TITLE
Terminal is not working as expected when connected to monitor

### ISSUE THREAD

**Issue by Suryalolla** [microsoft/vscode#80507]
When I start commands in the terminal, everything blackout in the terminal section. It works fine when I run commands directly on my Mac.

It is also not following my .bash_profile rules.
![Screen Shot 2019-09-07 at 12 40 40 AM](https://user-images.githubusercontent.com/26420251/64469890-2871c900-d108-11e9-964c-d87563c6ee4b.png)

**Comment by Tyriar** [comment]
Emoji mess with cursor position in some environments (tracking in https://github.com/xtermjs/xterm.js/issues/1059)

As for everything blacking out, sounds like you're seeing an issue with the canvas renderer, you can turn this off with this setting:

```
"terminal.integrated.rendererType": "dom"
```
