### ISSUE TITLE
Problem with JavaScript 

### ISSUE THREAD

**Issue by shrihanDev** [microsoft/vscode#80505]
<b>Hello!</b>

<p>When I type following lines in VSCode 
JavaScript..</p>
<code>
const input = document.getElementById('#input');
<br />
console.log(input.value);
</code>
<p>.. I get an error saying that value attribute not found in type Element</p>
<p>But when I open it in browser, everything is fine</p>
Please suggest me!

**Comment by austincummings** [comment]
This is because `document.getElementById` returns an `HTMLElement` which does not have a value attribute. The type you are likely expecting `input` to be is an `HTMLInputElement`. To fix this you can either do a type-assertion like this:
```ts
const input = document.getElementById('#input') as HTMLInputElement
```

Or by using a type-guard to make sure `getElementById` is returning the right element type before using it.

```ts
const input = document.getElementById('#input'); 
if (input instanceof HTMLInputElement) {
    console.log(input.value);
}
```

**Comment by embeddedt** [comment]
It's happening because TypeScript (what VSCode uses internally for suggestions) is unable to infer that the return value of `getElementById` is an input element.

However, I don't think that's supposed to trigger an error in JavaScript.

**Comment by shrihanDev** [comment]
But it raises an error that states:
Property "value" n9lot found in type Element
...In file 'test.js'

**Comment by embeddedt** [comment]
> But it raises an error

Yes. That would be the expected behavior (in TypeScript). `getElementById` always returns a generic `Element`. Only the `HTMLInputElement` type has the `value` property.

What confuses me is why it happens in JavaScript as well.
