### ISSUE TITLE
Add workbench.action.openPanel command

### ISSUE THREAD

**Issue by ksweetie** [microsoft/vscode#80503]
`workbench.action.togglePanel` already exists for toggling the integrated terminal. Having a keybinding that _always_ opens the terminal would be useful for macros. For example, a macro with two commands:

1. Open terminal
2. Run command

Currently, you can only toggle the terminal, so depending on if it's open or not, it might first close the terminal and then run the command.

**Comment by ArturoDent** [comment]
`workbench.action.terminal.focus` will open the terminal if it is closed, and not toggle it if already open.  Should work for you.

**Comment by ksweetie** [comment]
@ArturoDent That works perfectly. Thank you so much!

Closing this issue.
