### ISSUE TITLE
Overly aggressive auto-complete makes it impossible to type in certain things

### ISSUE THREAD

**Issue by mobileben** [microsoft/vscode#80500]
- VSCode Version: 1.36.1
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. This is using Typescript. Have an imported namespace called Types.
2. Type in a class from Types in the file. For example, in my case, I am typing "Types.Color"
3. Notice that you cannot type in Types, it changes it to ArrayBufferTypes once you type in T Y P E S .
4. When you type in the period, it converts it to ArrayBufferTypes

**Comment by mobileben** [comment]
Here is another example. 

Trying to type

```
export class AnchorableArea implements Area, Anchorable
```

In actuality, when I type

```
export class AnchorableArea implements Area,
```

The ',' triggers it to auto complete to `AnchorableArea`.

Not sure if it matters, but I am using the VIM plugin.

Auto complete becomes very difficult to use with the types of bad replacements it always does. 

And slight aside, VIM seems very buggy too.

**Comment by sbatten** [comment]
@mobileben check out `editor.acceptSuggestionOnCommitCharacter`, disabling this should allow you to only explicitly accept suggestions. Please re-open if I have not solved the issue.

**Comment by mobileben** [comment]
I'll mess around with this some more. Of course it tends to also the reduce speed. My first test ride with this off has some slowness for completion.

If you take my last example, Once the `r` in `Area` has been types, `AnchorableArea` should either be off the list or low on the list for completion order.

What you are seeing in both my cases is that autocomplete is prioritizing potential replacements for items which I would not expect to get listed. I get the need for alphabetizing things. But I would tend to think a "smart" auto-completer does this.

I just tried in Xcode. And that is exactly what it does. If I type in `String`, it starts with possible string matches. But `NSString` is on the list, it is after the best matches. In fact, there seems to be a weighted completion sequence (which is easier for them to do since they probably know frequency of their SDK better than others).

So in Xcode, typing in `String` yields:

```
StringPtr
StringHandle
NSString
NSStringEncoding
CFStringRef
CGPDFString
CGPDFStringRef
ConstStringPtr
```

VSCode does some sorting, but the algorithm is odd. It ignores casing and makes in general what I would call very bad ordered options (hence why it appears overly aggressive).

Oh, I just also noticed perhaps one of the items causing this. It doesn't seem to include `interfaces` in the list.

If I created a `class Areas`, it will list that first. But my `interface Area` doesn't show up. Likewise, it also seems `enums` and `const` variables in a `ts` file don't also show up.

**Comment by sbatten** [comment]
/cc @mjbvz 

@mobileben thanks for all of the feedback. there are a decent amount of points here that I would recommend creating a separate issue for them. We tend to stick to a single problem, single issue for tracking reasons. I've cc'd @mjbvz so he's aware of the points.

**Comment by mobileben** [comment]
Thanks!

Okay I will do so a bit later this evening. There also appears to be some other issues which I'll report separately. For example, the documentation states: 

> For example, in JavaScript, the semi-colon (;) can be a commit character...

But other characters like `.` and `,` also do this. It also doesn't look like you can adjust that commit character.
