### ISSUE TITLE
A different approach to display tabs on multiple rows

### ISSUE THREAD

**Issue by rmkl** [microsoft/vscode#80510]
I'd like to offer a different approach to multi-row tabs that is more flexible and aims to prevent tabs from 'jumping' whenever a tab is closed or added somewhere in the middle of a row.

This may be related to the following issues that are all about UX improvements in handling of tabs:
https://github.com/Microsoft/vscode/issues/32836
https://github.com/microsoft/vscode/issues/64690
https://github.com/microsoft/vscode/issues/15048
https://github.com/microsoft/vscode/issues/7987

The solution presented uses VS Code as an example but it can be adapted to other programs where the user wants to have more control over how tabs are organized when they open a lot of them (e.g. IDE's, Excel, browsers etc).

Let's introduce the concept of 'shelves'. Think of a shelf as a row which is not linked to any other rows.

The editor starts with one shelf that behaves the same as the current single row of tabs. It follows the user's preference for 'Tab sizing: fit || shrink', scrolling kicks in when there are too many tabs to display, and the user can reorder tabs by dragging them around.

As the user adds more tabs they have two options to organize them:
- Right-click a tab and select 'Move to new shelf from here': the selected tab and all tabs to the right of it are moved onto a new shelf below the current one.
- Add a new empty shelf below the current one: the user can drag tabs onto the new shelf from any other shelves.

The difference with earlier proposed multi-row implementations is that the shelves are independent from one another. Opening or closing tabs on a shelf never affects the ordering of the tabs on any of the shelves above or below it. By default tabs are added following the same rule as always: to the right of the currently active tab. Closing a tab will never pull in tabs from the shelf below it. This limits the 'jumping' of tabs to back and forth on a single shelf, exactly as it is now with a single row.

Each shelf can be scrolled independently. This does mean that shelves need to be of a certain minimum height to make it easy for the user to scroll the intended shelf.

The behavior of shelves when resizing the VS Code window, i.e. drastically shrinking it, follows current behavior of the row of tabs and results in having to scroll tabs.

With shelves the user is free to keep adding tabs to a single shelf and choose to scroll them, or add more shelves to prevent having to scroll.
Shelves also facilitate organizing tabs logically, using a different shelf for each flow that the user is working on.
If a file is used in two or more flows it could be opened on multiple shelves. Navigation within the file would be separate for each shelf similar to when the user opens the same file in two split editors.

Working with shelves should be quick:
- Add a new shelf below the current one in a single click.
- Close a shelf in a single click.
- Drag shelves to reorder them.
- Right-click a file or a folder in the explorer window and select 'Open on new shelf'. If a folder contains other folders these would each open on their own shelf as well.
- Shelves are shown as collaps/expand dividers in the 'Open editors' window.

I think shelves could satisfy the demand for multi-row tabs without disturbing the people who are happy to just keep scrolling their tabs. Thoughts or feedback?

Note: if anyone has the skills to visualize this in an animation, please do!

**Comment by BFGriffith** [comment]
I wish you would reconsider closing this as out of scope, as I think the functionality suggested by @rmkl would be a better optional way to handle file tabs than is currently available in VS Code (while preserving the current functionality for those who like and prefer it), as well as potentially even a better approach than Visual Studio professional (which can quickly become cluttered with many pinned tabs wrapping on multiple rows) as well as better than more directly competing code-editors like Sublime or Atom (both of which I have used, but my current team and projects have me gravitating toward and learning VS Code).
Horizontal scroll is generally bad — but, on the other extreme, I know many VS Code users who find the default "preview" setting as well as only a single row of tabs by default very limiting and frustrating UX. For example, with the proposed enhancement, a front-end developer working on several related Angular or React components could have a "shelf" for HTML markup component files, a shelf for stylesheets, and a shelf for Typescript files — OR a "shelf" for each component (such as a component, its child, and its grandchild (each with a row of tabs for its HTML, stylesheet, and Typescript files including related Services or Directives); this would be an outstanding GUI/UX improvement for VS Code!

**Comment by BukeBeyond** [comment]
I like it!
