### ISSUE TITLE
Git: Disable status bar sync setting doesn't work

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#80515]
1.
```js
"git.enableStatusBarSync": false,
```
2. Reload Window
3. 🐛 Sync entry is shown again

Version: 1.39.0-insider (user setup) Commit: 9414b7e75bdbef887c76cb603e542db2b86b99b7
OS: Windows_NT x64 10.0.18362

**Comment by nikitavoloboev** [comment]
Can confirm it happens on macOS with VSCode version 1.38.0
