### ISSUE TITLE
Need a simple way to navigate to interface implementation in TypeScript

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#80518]
I'd like to have an action which allows me to see all implementations of a particular method from an interface.

The same applies to overrides of a method in a class.

**Comment by mjbvz** [comment]
Do you try using `Go to implementation`? 

/needsMoreInfo

**Comment by solomatov** [comment]
>Do you try using Go to implementation?
Yes, but it doesn't work everywhere.
<img width="500" alt="Screen Shot 2019-09-09 at 9 59 45 AM" src="https://user-images.githubusercontent.com/1268556/64550846-9d9bf480-d2e8-11e9-9671-7f20366263e7.png">

**Comment by solomatov** [comment]
Also, there's another use case. You want to see overrides of a particular implemented method and it isn't covered well.

**Comment by mjbvz** [comment]
Are you trying to use the context menu or running the `Go to implementation` command from the command palette? Also, please include the issue template information the bot mentioned (os version, vscode version, and extensions)

**Comment by solomatov** [comment]
Here's the OS info:

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by solomatov** [comment]
@mjbvz Go to implementation really worked. I am really surprised, I missed this feature so much in vs.code :-) 

Do you mind if I create a PR to include go to implementation into the menu to make it more discoverable as well as creating a shortcut for it? (I am thinking about Ctrl+Shift+F12 on Mac and Alt+Shift+F12 on other platforms)

**Comment by mjbvz** [comment]
I believe that we actually use to have it in the menu but removed it since we didn't want to make the context menu too long. Adding it as a configuration option falls under #9285
