### ISSUE TITLE
[go] Colors of names, types of declarations inconsistent

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode#80523]
<img width="169" alt="Screen Shot 2019-09-04 at 11 07 52 AM" src="https://user-images.githubusercontent.com/63830/64279589-42db5500-cf04-11e9-8767-8ab044e3d7b1.png">

For var declarations, names are blue and types are white, whereas for const declarations, names are white and types are blue.

For type declarations without parentheses, the names are green and the types are white, whereas for type declarations with parentheses, both the names and types are white.

I'm guessing that for both var and const declarations, the names should be white and types blue?

I'm guessing that for type declarations, the names should be white and the types should be blue, except for built-in types like `int`, which should be green?

Originally reported at https://github.com/microsoft/vscode-go/issues/2733.

---

- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6 (18G87)

Steps to Reproduce:

1. Enter this in a .go file:

```go
type Foo X

type (
	Bar X
)

var x Foo = 123
const y Bar = 123

var (
	x Foo = 123
)

const (
	y Bar = 123
)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to the grammar repo: https://github.com/atom/language-go/issues/176

**Comment by willfaught** [comment]
@alexr00 That atom ticket was closed:

https://github.com/atom/language-go/issues/176#issuecomment-531023673

Apparently, atom switched from atom/language-go to their own grammar system called Treesitter, so they’re not going to fix the issue, which Treesitter has already fixed.

So I guess this should remain open? Is vscode going to fork all of atom’s old language repos?

**Comment by alexr00** [comment]
If there is a better maintained textmate grammar for go I can look into moving to a different grammar.

**Comment by willfaught** [comment]
I don't think it's maintained at all anymore, based on that issue's comment and resolution. What's vscode's plan for fixing grammar problems going forward?
