### ISSUE TITLE
h5

### ISSUE THREAD

**Issue by 35404987** [microsoft/vscode#80526]
Issue Type: <b>Bug</b>

when start debug the console alert "Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost/fav" ,because no  
installed favicon.ico ,could set "<link rel='shortcut icon' href='#' />"in head ,or add favicon.ico in the root directory and set "<link rel='shortcut icon' href='favicon.ico' />"in head  to solve the problem

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.84GB (4.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
jquerysnippets|don|0.0.1
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-zh-hans|MS-|1.37.5
debugger-for-chrome|msj|4.11.7
code-spell-checker|str|1.7.18
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.3.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
I assume you are debugging with a browser. They always request the favicon for a site when you visit it.
