### ISSUE TITLE
Renaming a symbol used as a default argument in a destructured object function argument incorrectly applies property renaming

### ISSUE THREAD

**Issue by benjaminblack** [microsoft/vscode#80521]
- VSCode Version: 1.38.0
- OS Version: Debian 11 (Bullseye)

Steps to Reproduce:

1. Define a function that accepts an object parameter, and destructure that object parameter in the function declaration. Give a default value to a property of the destructured object, assigning to it a symbol that is declared in an outer scope. E.g.,

```
const FOO = true;
function f({ v = FOO }) { ... }
```

2. Use symbol renaming to rename the outer symbol `FOO` to something else, like `BAR`. 

VSCode seems to be confused by the combination of object destructuring with default valuesand attempt to rename the default value symbol, e.g.:

```
const BAR = 1; // FOO renamed to BAR using VSCode Symbol Renaming
function f({ v = FOO: BAR }) { ... } // bad behavior
```
Correct behavior would be to simply rename the default value symbol, not try to apply destructured object property renaming after the default value assignment.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/33518 to track upstream
