### ISSUE TITLE
"Preserve case in Search and Replace" Icon Overlapping With Text

### ISSUE THREAD

**Issue by shawnrivers** [microsoft/vscode#80525]
## What is this issue?

In the search view, when the text in the input area is more than one line, there is a chance for the **Preserve case in Search and Replace** icon to overlap with the text.

![image](https://user-images.githubusercontent.com/23146992/64482681-aed5fa00-d231-11e9-9020-b4ebbddc557a.png)

## OS Info
- VSCode Version: 1.38.0
- OS Version: macOS 10.14.6

## Steps to Reproduce

1. Press `shift + command/control + F` to open the search view.
2. Toggle replace.
3. In the replace input area, type in some random text more than one line.

## Does this issue occur when all extensions are disabled?
Yes

## Does this issue occur in the latest insider?
Yes

**Comment by roblourens** [comment]
FYI @skprabhanjan

**Comment by roblourens** [comment]
The button shouldn't move, the text should wrap around the button the same way it does for the inset buttons in the search box.

**Comment by skprabhanjan** [comment]
Hi @roblourens  , Ya this is what I have tried but I am having trouble with css.
Firstly , I cant find the css that is applied for the search box to check how it is working properly.
I tried adding `white-space: normal` , Also tried `word-wrap and word-break` css properties but no luck.
Can you please help me here to get this fixed ?

**Comment by roblourens** [comment]
We just add padding-right to the input box somewhere, equivalent to the width of the buttons. Not sure where exactly, let me know if you can't find it.
