### ISSUE TITLE
Allow Icon Uri to refer to microsoft/vscode-icons

### ISSUE THREAD

**Issue by HaaLeo** [microsoft/vscode#80531]
# Description
As an extension developer I want to use the **latest** [microsoft/vscode-icons](https://github.com/microsoft/vscode-icons) in my extension without copying the svg files as resources. I want to be able to do something like: 
```typescript
import * as vscode from 'vscode';

const myButton: vscode.QuickInputButton = {
    iconPath: {
        dark: vscode.Uri.parse('https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/edit.svg'),
        light: vscode.Uri.parse('https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/edit.svg')
    },
    tooltip: 'Insert Result'
}
```

# Proposal
Allow the usage of `https://raw.githubusercontent.com/microsoft/vscode-icons/...` URIs

# Related Issues

* #66069
* #31466

**Comment by misolori** [comment]
I think #31466 will handle this. I don't think we want to link to any external URLs as that will easily break w/ connection issues. Instead we'd likely provide a way to use it similar to Octicons via `$(icon-name)`. Will close this in favor of #31466.

Also, this work will rely on #78889 so keep an eye on that.
