### ISSUE TITLE
Segfault when dragging webview to the right

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#80535]
Hi

I found a way to make VS Code crash. I was able to reproduce it several times on my side.

Here are the steps to reproduce. You can find [a video](https://github.com/sguillia/bug-repro/raw/master/vscode-repro.avi) of them. The video is two minutes long, I suggest reading the steps to reproduce while watching. I'm sorry you need to download it, github does not allow video upload. My mouse is not shown in the video.

The working folder is `completions-sample` from [your extensions samples](https://github.com/microsoft/vscode-extension-samples). Perhaps it doesn't change anything which folder you choose but this is how I reproduce on my side. This only reproduces with extension development, you need to be able to launch a VS Code guest in a debugging session.

- At 00:03, open Code insiders.
- At 00:09, start a debugging session (Press F5 or click on Run Extension)
- At 00:16, open the marketplace panel.
- At 00:19, type "java" and select the "Language Support for Java(TM) by Red Hat" extension.
- At 00:21, open a new Untitled editor, so you can later have two editor groups.
- At 00:22, drag and drop the extension webview (I guess it's called like that) to the right of your screen. Easier with window maximized but not mandatory.
- At 00:23, the Developer Tools open (??). I suppose this is a bug.
- At 00:24, see as there are a lot of errors in the console. I suppose this is a bug.
- At 00:28, close the Developer Tools. Watch as it spontaneously re-opens, and it will forever do until you close VS Code.
- Between 00:32 and 1:20, I am struggling to reproduce. Sometimes it crashes immediatly, sometimes you need to close the developer tools for two minutes in order to reproduce. You can skip until 01:20.
- At 01:25, I got it. Both VS Code instances, host and guest, completely freeze for a few seconds.
- At 01:33, VS Code crashes. I had `sudo dmesg -w` running in a terminal. It shows that code-insiders had a segfault. Forget about the high temperature messages, not sure if it's VS Code  who's causing this :-)

When I try to reproduce (drag-n-drop) in a single VS Code instance, without debuggee, then the editor group disappears. There is no segfault, but is still disappears. You can also find errors in the developer console in that case.

Happy debugging

Note: I will remove the video when this issue will be closed.

Reproduces with extensions disabled.

VS Code version: Code - Insiders 1.39.0-insider (9414b7e75bdbef887c76cb603e542db2b86b99b7, 2019-09-06T05:27:32.236Z)
OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.64GB (1.37GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Thank you for the detailed write up.

Based on the console errors, this looks like it could also be related to #80296. I'll investigate for VS Code 1.39
