### ISSUE TITLE
Don't automatically fetch when there are no remotes available

### ISSUE THREAD

**Issue by mattkefford** [Microsoft/vscode#8053]
Continually giving message "fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched." when I am working on files in a local git repo. There is no remote repo and in any case I can't find a way to interact with git apart from committing changes + a message. I don't even know what branch I'm working on so still have to revert to git shell. 
- VSCode Version: 1.2.1
- OS Version: Windows 7 SP1

Steps to Reproduce:
1. Open a folder that contains a git repo
2. Toggle git output

![image](https://cloud.githubusercontent.com/assets/15934099/16305349/513d7e44-3951-11e6-9a4b-bf4a19799f4f.png)

**Comment by joaomoreno** [comment]
We can skip automatic fetching if there are no remotes.

Your current branch is `version-1_3`... it says right there in the bottom left corner, in the status bar.
