### ISSUE TITLE
snippets  prefix support utf-8

### ISSUE THREAD

**Issue by lbgws2** [microsoft/vscode#80532]
Snippet is a very useful programming tool. 
The problem is that I am a Chinese. Can the prefix support non-English alphabet search, such as Chinese. which is very helpful for people who are not native speakers of English

**Comment by jrieken** [comment]
The prefix can be anything but "suggestions as you type" are only triggered when typing a word character. What that is defines the corresponding language. For non word prefixes suggestion must be triggered manually, using ctrl+space

<img width="505" alt="Screenshot 2019-09-10 at 09 54 16" src="https://user-images.githubusercontent.com/1794099/64594831-0b135800-d3b1-11e9-8603-038c81537fc7.png">

**Comment by lbgws2** [comment]
> The prefix can be anything but "suggestions as you type" are only triggered when typing a word character. What that is defines the corresponding language. For non word prefixes suggestion must be triggered manually, using ctrl+space
> 
> <img alt="Screenshot 2019-09-10 at 09 54 16" width="505" src="https://user-images.githubusercontent.com/1794099/64594831-0b135800-d3b1-11e9-8603-038c81537fc7.png">

Thanks for Reply.
I created the test snippet in my.code--snippets.

"HelloWorld": {
    "prefix": "测试",
    "body": "hello,world"
}

It does not work.

"HelloWorld": {
    "prefix": "test",
    "body": "hello,world"
}

it works well.

**Comment by jrieken** [comment]
<img width="377" alt="Screenshot 2019-09-13 at 18 10 32" src="https://user-images.githubusercontent.com/1794099/64877458-c9550c80-d651-11e9-8366-78b8cb0be0c2.png">


It works but you must press Ctrl+Space to get suggestion as `测` isn't a word character and auto suggestions only work on words characters

**Comment by lbgws2** [comment]
> It works but you must press Ctrl+Space to get suggestions - `测` likely isn't a word character in your programming language and auto suggestions only works on word characters

I press Ctrl+Space but not work,Maybe the problem is my IME.
My operating system is win10 x64,and Ctrl+Space Used to switch input methods.
I tried to change the system's input method switch key to Other,but it's not work.
is that a way to change the keys of get suggestions?

Thanks again.
