### ISSUE TITLE
Setting default language to python3 wont work

### ISSUE THREAD

**Issue by Mittugoud** [microsoft/vscode#80545]
Issue Type: <b>Bug</b>

It is disgusting with the new interface.
Even after creating a virtual environment to Python3 the terminal still takes python as the default language.

Even installed code-runner and set the default language as python3 (python3.7.4). Yet it didn't fix issue!!

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:51:09.716Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz (4 x 1436)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|5.71GB (2.44GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.14
python|ms-|2019.9.34911
material-icon-theme|PKi|3.9.0
java|red|0.48.0

(4 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@Mittugoud I don't quite follow the issue. Can you provide a set of steps that can be used to reproduce your issue and what you expect to occur?

/needsMoreInfo
