### ISSUE TITLE
Expand/collapse html & code

### ISSUE THREAD

**Issue by Vallentin79** [microsoft/vscode#80547]
The function of collapsing and expanding, stops working in bigger projects.

This is really time consuming, when you have to close vs code and open it again 20 times a day, because the function stops working. And therefore cant reach your code before vs code is restartet.

**Comment by aeschli** [comment]
What do you mean by 'stops working'? In what type of files does it stop working? How big are the files?
If you have reproducible steps that would be great.

**Comment by Vallentin79** [comment]
It stops working in both HTML files and Typescript files.

![vscode error](https://user-images.githubusercontent.com/46589697/64609811-09a45880-d3ce-11e9-9904-d466a5e47df1.png)
