### ISSUE TITLE
Enable to write to files that need user elevation 

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#8054]
- VSCode Version:1.2.1
- OS Version:arch linux

Steps to Reproduce:
1. open a file owned by another user  root in our case (/etc/somefile)
2. make changes and try to save
3. nothing happens

in atom editor this situation was handled by prompting password if teh current user is in sudoers file
is it possible to make a similar action for such cases .
It would be really extremely useful feature

**Comment by coreh** [comment]
Also doesn't work on OS X:

![screen shot 2016-08-22 at 22 49 48](https://cloud.githubusercontent.com/assets/418473/17877648/39e68274-68bb-11e6-89d1-94b2a730d712.png)

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
