### ISSUE TITLE
new file input name disappear when scrolling

### ISSUE THREAD

**Issue by shaodahong** [microsoft/vscode#80549]
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

![002](https://user-images.githubusercontent.com/14831261/64514875-1f5a4500-d31e-11e9-84ac-ae5350830716.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
Yeah, the actual issue is that the input box should be closed when it is no longer in the view. And this #79383 shuold tackle that.

**Comment by isidorn** [comment]
Fixed since I meged the PR.
