### ISSUE TITLE
The view function lacks image information, such as image size information.

### ISSUE THREAD

**Issue by liuyc123** [microsoft/vscode#80543]
Issue Type: <b>Feature Request</b>

When making WEB web pages, we need to use image preview, not only to view pictures, but also to look at the information of pictures, such as size. Otherwise, this function seems to be useless, that is, to look at pictures.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
I don't understand what you are asking for. Please provide an example of what you are trying to do and what is not working as expected

**Comment by liuyc123** [comment]
![图片](https://user-images.githubusercontent.com/28505081/64950529-2b11b280-d8ae-11e9-9d16-1cc494b6e1ff.png)
How to view the size of a picture in Visual Studio Code, such as 300*300
example
![图片](https://user-images.githubusercontent.com/28505081/64950685-90fe3a00-d8ae-11e9-8507-e3c2a86914d8.png)

**Comment by mjbvz** [comment]
Size information is shown in the status bar:

![Uploading Screen Shot 2019-09-16 at 10.51.37 AM.png…]()

See the 383x383 in the lower right corner

**Comment by liuyc123** [comment]
My God, thank you very much.
