### ISSUE TITLE
Disable centered layout when opening settings.json

### ISSUE THREAD

**Issue by Vxider** [microsoft/vscode#80542]
vscode uses two column layout when opening settings.json. It would be perfect if vscode can automatically exit centered layout  when  settings.json is opened.
![image](https://user-images.githubusercontent.com/6134315/64498788-bc9a8680-d2e8-11e9-9e54-76c77b7d7d61.png)

**Comment by isidorn** [comment]
This is a fair feature request. However Centered layout currently only looks at the number of groups open, not what is the context of groups.
Thus leaving this open, and assigning to Backlog since we have no immediate plans to tackle this.
