### ISSUE TITLE
Working tree ident guides misaligned

### ISSUE THREAD

**Issue by petrosschilling** [microsoft/vscode#80546]
VSCode Version: 1.39.0-insider

If you zoom in the image below you will notice the line is one pixel off to the left.
Not a big deal. But I can't stop to notice and it is distracting me.

<img width="48" alt="Screen Shot 2019-09-09 at 3 55 55 pm" src="https://user-images.githubusercontent.com/5184353/64506544-46fbde00-d31b-11e9-8652-ee295da2c15f.png">

If you guys could fix it would be great!

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/78579
