### ISSUE TITLE
Can't install any VSCode extensions for some reason.

### ISSUE THREAD

**Issue by atiyahio** [microsoft/vscode#80541]
![image](https://user-images.githubusercontent.com/47905558/64496547-4ffe9800-d2a6-11e9-8db7-c341cf87c7ef.png)

I keep getting errors every time I try to install any extension to VSCode.

**Comment by gjsjohnmurray** [comment]
What version? What platform? Did this start happening when 1.38 released? Maybe https://github.com/microsoft/vscode/issues/80508#issuecomment-529225586 is relevant. What country are you in? Does your Internet access go through a proxy? Any security software that might block DNS resolution by an app, particularly one whose executable maybe changed recently?

**Comment by atiyahio** [comment]
@gjsjohnmurray hey there! it turned out to indeed be a dns issue, I changed it and it works fine now, thanks. :)
