### ISSUE TITLE
the window has crashed

### ISSUE THREAD

**Issue by Rajshukl125** [microsoft/vscode#80540]
i was working on a html & css project advanced sass actually i switched back to cmd and browser and also save and cut and paste several times ........i thinks this was happen to that i also explore in google to solve but i m not enough pro to understand what to do ... pls help me on fixing it

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post your version info and step by step instructions for how to reproduce. Maybe paste screenshots too. Also test with all extensions disabled.
