### ISSUE TITLE
Multiple node processes on start-up

### ISSUE THREAD

**Issue by iamsalman20** [microsoft/vscode#80548]
When I start VS Code, multiple node processes start in the background which render my cpu usage very high. Those processes get killed if I close the application. If I manually kill those processes with cmd line, VS Code stops responding.
I am using Ubuntu 16.04 64-bit and I have tried uninstalling and installing the latest version of VS Code (does not help). 

Here is the outcome of cmd "ps aux|grep node":

salman   10723  9.2  7.6 1201824 310216 ?      Sl   10:17   0:33 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --service-pipe-token=4073016219813694401 --lang=en-US --app-path=/usr/share/code/resources/app --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.38.0 Chrome/69.0.3497.128 Electron/4.2.10 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=4073016219813694401 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
salman   10941  1.0  2.5 736800 102160 ?       Sl   10:17   0:03 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --disable-gpu-compositing --service-pipe-token=16610551674269398061 --lang=en-US --app-path=/usr/share/code/resources/app --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.38.0 Chrome/69.0.3497.128 Electron/4.2.10 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#1e1e1e --disable-blink-features=Auxclick --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=16610551674269398061 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
salman   11008  0.1  2.6 656476 105956 ?       Sl   10:18   0:00 /usr/share/code/code /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --syntaxOnly --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/34140610d20f8278e1c2/tscancellation-cde5b61d250fdeb57d69.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
salman   11009  6.0 11.7 1040884 473612 ?      Sl   10:18   0:21 /usr/share/code/code /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/34140610d20f8278e1c2/tscancellation-79fe2d287472776bdc79.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
salman   11069  1.2  3.1 685004 125456 ?       Sl   10:18   0:04 /usr/share/code/code /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/salman/.cache/typescript/3.6 --enableTelemetry --typesMapLocation /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
salman   11146  5.1  2.5 719732 102480 ?       Sl   10:21   0:07 /usr/share/code/code --type=renderer --disable-color-correct-rendering --no-sandbox --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --disable-gpu-compositing --service-pipe-token=15713780491077300088 --lang=en-US --app-path=/usr/share/code/resources/app --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.38.0 Chrome/69.0.3497.128 Electron/4.2.10 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#252526 --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=15713780491077300088 --renderer-client-id=8 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
salman   11175  0.0  0.0  15752  1028 pts/4    S+   10:23   0:00 grep --color=auto node

**Comment by sbatten** [comment]
@iamsalman20 these processes are part of VS code and should not be killed. As for the high CPU usage, the above duplicate seems like it might be a good match. In the future, you can also use the `Process Explorer` in VS Code (Cmd+P > Process Explorer) to look at CPU usage for processes belonging to VS Code.
