### ISSUE TITLE
Debug action buttons hidden

### ISSUE THREAD

**Issue by PowerMogli** [microsoft/vscode#80557]
After last update of insider (user setup-version) I cant see the action buttons (pause, continue, stop, etc.) when debugging.

![image](https://user-images.githubusercontent.com/5623081/64529317-e664a500-d30a-11e9-9036-249e2f7222ee.png)

**Comment by davystrong** [comment]
Having this same issue today. The buttons still work if you know where to click, but no icons.

**Comment by gmarino2048** [comment]
Also seeing this issue on the Mac build today.

**Comment by vainamov** [comment]
Same issue in VS Code version: Code - Insiders 1.39.0-insider (0f1bd7721b793ed8b7805ba621061ce5a1f5c263, 2019-09-09T05:28:53.427Z)
OS version: Windows_NT x64 10.0.18362
