### ISSUE TITLE
Show only install counts

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#80551]
From Marketplace team:

In few days from marketplace we are going to remove “downloads”(install + updateCount) which shows in details page, extension tile and publisher extension lists and replacing with “installs” to have consistent behavior with all types extensions( VS Ide, VS Code and Azure Devops) and making sort by installs depends on only “install statistic” value.

We need to make reaction work in VS Code client side to have consistent behavior with marketplace portal. Currently in VS Code we show (install + updateCount) as install count, Can you please make change in VS Code side to show (install) as install count?

This change required to have right behavior of sort by install count.

**Comment by usernamehw** [comment]
Would there be any way of getting that number (Downloads)? Now extension authors can approximately estimate number of active users by looking at download number after the update.

**Comment by sandy081** [comment]
I do not think download count will be available. 

Install count will give you number of active users.

**Comment by usernamehw** [comment]
Does it account for the users who deleted the extension?

**Comment by sandy081** [comment]
@kesane-msft Does the install count gets updated when user uninstalls the extension?

**Comment by kesane-msft** [comment]
@sandy081 - no we don't update the install counts on uninstallation of an extension.

**Comment by sandy081** [comment]
@kesane-msft Are there plans to consider uninstalls in install count. I think this information will give us active installs and will be useful to know before installing.

**Comment by kesane-msft** [comment]
@sandy081 - No plans currently to add that support.
