### ISSUE TITLE
Git VCS provider does not recognize repository unless `worktree` option is set

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#80550]
Issue Type: <b>Bug</b>

For some reason, on my work system VS Code does not recognize Git repositories unless I set the `worktree` option in config.
I can't even see why it does that, as it simply shows "no source control providers registered".
At the same time, typing git commands in the integrated terminal works just fine.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E6850  @ 3.00GHz (2 x 3060)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.00GB (2.03GB free)|
|Process Argv|--folder-uri file:///\<private>|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
php-debug|fel|1.13.0
sqltools|mtx|0.20.3
editorconfiggenerator|nep|0.2.1
shell-launcher|Tyr|0.3.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by joaomoreno** [comment]
What do you specifically set in the config?

Also, can you show me the output of `Git: Show Git Output` when the bug happens?

**Comment by AnrDaemon** [comment]
```
Looking for git in: C:\Cygwin64\usr\local\bin\git.sh
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: C:\Program Files (x86)\Git\cmd\git.exe
Looking for git in: C:\Program Files\Git\cmd\git.exe
Looking for git in: D:\Profiles\anrdaemon\AppData\Local\Programs\Git\cmd\git.exe
Looking for git in: C:\Cygwin64\bin\git.exe
Using git 2.21.0 from C:\Cygwin64\bin\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git rev-parse --show-toplevel
> git rev-parse --git-dir
```

`C:\Cygwin64\usr\local\bin\git.sh` is set in git.path, exists and is actually executable.
```
[C:\]$ set PATHEXT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.SH;.PHP;.BTM

[C:\]$ ASSOC .sh
.sh=unixshell.script

[C:\]$ FTYPE unixshell.script
unixshell.script="C:\Program Files\JPSoft\TCC-RT\TCC.EXE" /B /C "C:\Cygwin64\bin\cygwrap.btm" "%1" %*
```

But VS Code for some reason ignoring it.

**Comment by joaomoreno** [comment]
VS Code only supports the official [Git for Windows](https://git-scm.com) release. If you want to use cygwin, you are on your own, unfortunately. Let me know if this still happens with Git for Windows.
