### ISSUE TITLE
'code -n' doesn't make a new window

### ISSUE THREAD

**Issue by ChrisJefferson** [microsoft/vscode#80554]
I'm suprised I can't find this issue already, but I did search and couldn't see it (sorry if I missed it)

- VSCode Version: 1.37.1
- OS Version: Ubuntu 19.04

Steps to Reproduce:

1. Run in a terminal: `code .; sleep 5; code -n .` (the sleep is just to check this isn't a race condition. Notice that a second window isn't opened.

Does this issue occur when all extensions are disabled?: Yes

Related, this effects `-w`, which will wait until the already opened window is closed.

**Comment by bpasero** [comment]
You cannot open the same folder in multiple windows currently, see https://github.com/microsoft/vscode/issues/2686
