### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by RobertIndie** [microsoft/vscode#80556]
- VSCode Version:1.37.1
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:
Just sometimes appear.
![WTBA5TYB5TE XZWNM@_~5~W](https://user-images.githubusercontent.com/16974619/64527184-db743980-d337-11e9-8aad-19c7a403fbf4.png)
![BT(K~YCW`G R`UY8WY`AGIM](https://user-images.githubusercontent.com/16974619/64527189-de6f2a00-d337-11e9-9da7-d2793dc7bdea.png)

**Comment by deepak1556** [comment]
@RobertIndie does this issue still appears for you with latest insiders ?
