### ISSUE TITLE
Wrong cursor position and terminal width (Linux, ZSH)

### ISSUE THREAD

**Issue by Cerberooo** [microsoft/vscode#80552]
VSCode Version: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.71-1-lts
ZSH: 5.7.1

![terminal_bug](https://user-images.githubusercontent.com/16780924/64516668-26b62a00-d2ef-11e9-8c87-a5d6949d241a.png)

Steps to Reproduce:

1. Install ZSH with Powerline
```
powerline-daemon -q
. /usr/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh
```
2. Open terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Please try repro in the upstream [xterm.js](https://github.com/xtermjs/xterm.js) project and report there if it happens.
