### ISSUE TITLE
Replace - Cannot read 'toUpperCase' property of undefined 

### ISSUE THREAD

**Issue by MehdiSaffar** [microsoft/vscode#80553]
**- VSCode Version:** 1.37.1
**- OS Version:** Linux x64 5.1.14-050114-generic

Steps to Reproduce:

1. Add a search term (make sure it actually exists in the current document)
2. Keep the replace term empty
3. Check the match case box
4. Press Ctrl-Alt-T
5. Get the error 

![image](https://user-images.githubusercontent.com/13124263/64517171-7a794100-d2f8-11e9-98c6-e1a11c152da8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
What does `ctrl-alt-T` do here? I don't think I have that keybinding.

**Comment by MehdiSaffar** [comment]
I think I meant Ctrl+Alt+Enter, the shortcut for replacing all. I am not
sure if it is the correct shortcut (I don't have access to my laptop right
now), but it is not specific to it. I am guessing replace or replace all
will trigger the same bug.

**Comment by roblourens** [comment]
I can't reproduce it. It would help if you can try it again and get the full error stack from the developer tools (Help > Toggle Developer Tools)
