### ISSUE TITLE
Go to definition doesn't work properly when there are multiple definitions

### ISSUE THREAD

**Issue by saimageshvar** [microsoft/vscode#80555]
- VSCode Version: 1.38.0
- OS Version: ubuntu 16.04 LTS
I am using ruby extension to have intellisense and go to defintions
When there are multiple definitions for a method, while clicking on go to definition and choosing the file from the mini popup that appears, it doesn't work if I choose the definition in the same file. It works fine if I choose definitions given in other files.

Does this issue occur when all extensions are disabled?: Can't reproduce since go to definition works on ruby extension

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/80362
