### ISSUE TITLE
debug bar icons are not visible - insiders version

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#80563]
Issue Type: <b>Bug</b>

run the debugger

![image](https://user-images.githubusercontent.com/1202528/64534858-3da34f00-d2e4-11e9-9308-5535a4684ecb.png)

VS Code version: Code - Insiders 1.39.0-insider (0f1bd7721b793ed8b7805ba621061ce5a1f5c263, 2019-09-09T05:26:48.181Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (0.37GB free)|
|Process Argv|-psn_0_2880191|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
vscode-browser-preview|auc|0.5.9
spellright|ban|3.0.46
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
vscode-pull-request-github|Git|0.10.0
angular-essentials|joh|0.6.3
Angular1|joh|0.2.1
Angular2|joh|8.1.1
helloworld-sample-statusbar|joh|0.0.1
read-time|joh|0.2.0
vscode-peacock|joh|3.1.5
dotenv|mik|1.0.1
azure-pipelines|ms-|1.157.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.75.0
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.766
debugger-for-chrome|msj|4.11.7
angular2-inline|nat|0.0.17
angular-console|nrw|8.1.1
vetur|oct|0.22.2
material-icon-theme|PKi|3.9.0
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.2
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
We are working on a fix and will trigger a rebuild of Insiders...

**Comment by johnpapa** [comment]
thank you
