### ISSUE TITLE
VSCode updater doesn't reference home directory properly on Windows

### ISSUE THREAD

**Issue by demortes** [microsoft/vscode#80568]
Recently I had to shuffle things around, and I set my windows "home" directory or %USERPROFILE% to a different name than my user account (domain set up at work).

The updater seems to install to the old first.last rather than first_last (notice the _ vs .).

I looked through the registry and I couldn't find where to update it. I had moved the directory after installing vscode, and modified the profile to reference the new directory (it was first.last.DOMAIN at that time, so I was attempting to remove at least the DOMAIN from it). I didn't find where it was referencing the old user profile directory. I've removed and reinstalled VSCode as well.

The solution is one of two ways, if not both. 
1. The updater should always reference %USERPROFILE%, which refers to the right directory, or %TEMP% which is %USERPROFILE%/AppData/Local/Temp.
2. Installer should write to the registry new values if changed. (I think we should stop using the registry period, IMO).

FYI: I've tried both the user setup and the system setup files.

**Comment by joaomoreno** [comment]
The installer should keep whatever you give it at installation... so have you tried uninstalling Code and reinstalling it?

**Comment by demortes** [comment]
Yes. I've reinstalled entirely. That it I've used the Uninstaller and reinstalled from a new installer. I've installed originally with the user setup. Moved the profile. That's when issues started then I've uninstalled and reinstalled with user and system setups.

**Comment by joaomoreno** [comment]
And now, after reinstalling after the move, it's good?

**Comment by demortes** [comment]
Sorry I was unclear, no it is not good. The installers never rectified the problem.

The solution I employed, due to multiple issues with my profile, is that I logged into a local administrator account, deleted the original user account, deleted the home directory within c:\users\ and then recreated the profile.

The problem is solved, but the bug still exists I believe.

**Comment by joaomoreno** [comment]
Got it. The Windows installer is prime for innovation. I'll close this issue for now.
