### ISSUE TITLE
JS Intellisense shows (x:Number) after context.log in function

### ISSUE THREAD

**Issue by adrianhall** [microsoft/vscode#80565]
Issue Type: <b>Bug</b>

Install azure functions extension.
Create a new JS function.
In the module.exports function, type `context.log(`

Note that the intellisense shows x:Number - this is the logging code, so it should show the message:String as the next argument.  

VS Code version: Code - Insiders 1.39.0-insider (9414b7e75bdbef887c76cb603e542db2b86b99b7, 2019-09-06T05:25:21.167Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
auto-close-tag|for|0.5.6
vscode-azurefunctions|ms-|0.18.1
azure-account|ms-|0.8.4
vsliveshare|ms-|1.0.766
vscode-react-native|msj|0.11.0
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I can't reproduce this function in the current insiders with all extensions disabled. Repo steps:

1. Create new js function using az functions extension. Http trigger
1. `npm install`
1. Open `index.js`
1. Type `console.log(`

![Screen Shot 2019-09-23 at 11 01 00 AM](https://user-images.githubusercontent.com/12821956/65450239-90572d80-ddf1-11e9-9dd3-e5acc2bf945f.png)

What file is opened if you run go to definition on `log` in `console.log`?

**Comment by mjbvz** [comment]
For repo, note you need `context.log` not `console.log` as originally listed in the repo steps. I've corrected the original repo steps.

`context` is `any`. Bug is that `.log(` should not show any signature help in this case. The fix for the user is to add proper typings for `context` (the az function extension should probably generate these)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/33565 to track root cause upstream
