### ISSUE TITLE
can't move a file using a command

### ISSUE THREAD

**Issue by joachim-n** [microsoft/vscode#80562]
Issue Type: <b>Bug</b>

I can move a file to a different folder by dragging it in the tree.

But in my current case, the tree is too long for me to see both the file I want to move and its desired new location.

So I looked for some sort of command that would let me enter the new path for the file. There doesn't seem to be one. Rename only lets me rename the filename, not the path.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.6.0

**Comment by isidorn** [comment]
Extensions can contribute commands to the Command Palette and to the explorer context menu.
Thus an extension can easily do this imho.
