### ISSUE TITLE
new！！！！search exclude settings doesn't work normal in some projects but other projects works normal

### ISSUE THREAD

**Issue by Adolf-L** [microsoft/vscode#80569]
- VSCode Version:
Version: 1.37.1

Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

- OS Version: 10.15 Beta (19A536g)

I have two Js projects. One is works normal as you can see. another project isn't works normal. I do a testing with disabled all the extension it still can't works. I don't know why? what should I do to fix this problem?

<img width="1449" alt="1" src="https://user-images.githubusercontent.com/10137107/64543280-8516f300-d357-11e9-84d0-536fc53d99bf.png">

<img width="1049" alt="2" src="https://user-images.githubusercontent.com/10137107/64543319-965fff80-d357-11e9-819e-a42fc9706d73.png">

**Comment by roblourens** [comment]
See the message "exclude settings are disabled"? You need to click that gear button in the "files to exclude" box to enable that setting
