### ISSUE TITLE
Debugger is very slow

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode#80561]
Debugger is very slow on opening in the latest VS Code insiders , actually it takes me 15 seconds to open the Chrome .

In the Vs code 1.38.0 it works well but in the latest Insiders edition it's so slow.

**Comment by isidorn** [comment]
Can you reproduce if you disable all extensions?
Can you share some reproducable steps? With the current description we can not do anything.

**Comment by goxr3plus** [comment]
I am have a React project which i run using npm start. Then i start the debugger and it takes 15 seconds to open the Chrome Window .

VS Code insiders : 

![image](https://user-images.githubusercontent.com/20374208/64703133-8873c100-d4b4-11e9-9c51-e2b7ba86acd3.png)

**Comment by isidorn** [comment]
If the debugger starts, but Chrome loads slowly this seems to be either the issue with your Chrome, or with the Chrome extensoin.
Can you please provide a video showing this?

**Comment by goxr3plus** [comment]
yes :)

**Comment by goxr3plus** [comment]
I just updated to latest vs code insiders : 

![image](https://user-images.githubusercontent.com/20374208/64704368-da1d4b00-d4b6-11e9-8439-5f525a0ec570.png)

And it seems to work correctly again .
