### ISSUE TITLE
should be able to immediately hit enter on go to definition peek view to go to definition

### ISSUE THREAD

**Issue by dontsave** [microsoft/vscode#80571]
This behavior changed since the most recent vscode update at least on OS X. Previously if selecting `go to definition` on a reference that has a type definition and a further definition, vscode would bring up a peek view with the further definition selected, you could then press `enter` to immediately go to that definition.

Now, hitting `enter` does nothing. You should be able to immediately hit `enter` to view the selected definition.

**Comment by geovanisouza92** [comment]
I have the same issue on Ubuntu, the up/down arrows for navigation doesn't work either.
