### ISSUE TITLE
search function doesnt find nested (7 folders deep) file

### ISSUE THREAD

**Issue by imanpeeman** [microsoft/vscode#80575]
Issue Type: <b>Bug</b>

The search function isn't able to find classes 9 folders deep. this scenario applies when building a react native mobile app with node_modules attached.  
e.g.: create RN project with ReactNativePjSip and search for PjSipService. There is a file, and a class (Java) with that name in the module. how ever it's not found. 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-react-native|msj|0.11.0
java|red|0.48.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2

</details>

**Comment by roblourens** [comment]
Sounds like you are probably hitting a path size limit in windows, does that sound likely? Or the folder is just excluded by your project: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by imanpeeman** [comment]
Thanks for the sesponse. I wasn't aware that VS code is looking at the gitignore, but when disabling 'exclude settings and ignore files' the files are not found. the weird thing is that quickopen is able to find a file deed hidden in the folder structure. e.g. 'call.java' which is 10 folders deep is found by quickopen and not by the search function. 

for now i'm helped by disable the exclude function and using the quickopen function

**Comment by roblourens** [comment]
What is the full path to the file that is missing? If it's extremely long then you might just be hitting a path length limit in windows/ripgrep.
