### ISSUE TITLE
Font stylistic set support

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#80577]
Issue Type: <b>Feature Request</b>

In the new version [2.0 of Fira Code](https://github.com/tonsky/FiraCode), there are some[ stylistic options ](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets)that can be set (e.g. old-style figures).  In Sublime Text there's a simple json key you can add to its settings file to enable the ones you want.

In VSCode, you have to use an extension which modifies the "custom css".  This seems hacky and needs to be enabled after every update.

I'd rather be able to do this with a settings key like Sublime Text.

VS Code version: Code - Insiders 1.39.0-insider (0f1bd7721b793ed8b7805ba621061ce5a1f5c263, 2019-09-09T05:26:48.181Z)
OS version: Darwin x64 18.7.0

**Comment by alexandrudima** [comment]
Implemented via https://github.com/microsoft/vscode/commit/ab0eb6de2d5fb4563385d98f302f78caa1767efd (https://github.com/microsoft/vscode/issues/82153) and it already shipped in Insiders.

e.g.
```
"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"
```

or

```
    "editor.fontFamily": "Fira Code"    
    "editor.fontLigatures": true,
    "[cpp]": {
        "editor.fontLigatures": "'ss06', 'ss19'",
    },
    "[javascript]": {
        "editor.fontLigatures": "'ss06'",
    }, 
```

**Comment by arrowtype** [comment]
Hey @alexandrudima, awesome work on this – it makes my code font project so much nicer to use in VS Code, and is yet another reason I'm really happy to be using VS Code as my go-to editor. :) Thank you!
