### ISSUE TITLE
Incorrect string overload chosen for function in TypeScript

### ISSUE THREAD

**Issue by Grafu** [microsoft/vscode#80570]
- VSCode Version: 1.38.0
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

1. Doing ctrl + space to select a possible string value. Navigating onto the value, but the overload does not update.
![image](https://user-images.githubusercontent.com/11540828/64543597-2be69980-d32e-11e9-977d-18f4163f5ebd.png)

2. Selecting the value and hitting enter. The value fills the string but the overload is still incorrect.
![image](https://user-images.githubusercontent.com/11540828/64543721-63eddc80-d32e-11e9-975d-f142ec6fd0bb.png)

Declarations:
![image](https://user-images.githubusercontent.com/11540828/64543825-8ed83080-d32e-11e9-9d1e-c3779c64951f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a code example for this (as text, not screenshots)

**Comment by Grafu** [comment]
```
declare function addEventHandler(event: "onPlayerJoin", player: Player, callback: () => void): boolean;
declare function addEventHandler(event: "onPlayerQuit", player: Player, callback: (quitType: string, reason: string, responsibleElement: Element) => void): boolean;

addEventHandler(
```

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/33328 to track upstream
