### ISSUE TITLE
Can no longer resize the split editor when editing settings.json

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#80583]
Issue Type: <b>Bug</b>

I believe this just started, but I can no longer resize the split editor via the middle bar. Diff editor still works, and it works fine in stable as well.

VS Code version: Code - Insiders 1.39.0-insider (a39d2de39dd5038a1a696800ac9af6dc32a31eab, 2019-09-09T17:00:17.505Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.31GB free)|
|Process Argv|--file-uri file:///c%3A/Users/Eric/code/codestream/all.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
@eamodio Not sure which editor you mean... what steps are you doing to get to that UI?

**Comment by eamodio** [comment]
From the command palette, _Preferences: Open Settings (JSON)_

![image](https://user-images.githubusercontent.com/641685/65221624-61f0ef80-da8b-11e9-8cfe-fc193ca2df51.png)

**Comment by eamodio** [comment]
@joaomoreno does that provide what you need?

**Comment by joaomoreno** [comment]
For some reason I no longer can open that view... it always opens a regular editor, not that old settings editor.

**Comment by roblourens** [comment]
@joaomoreno now you have to set `"workbench.settings.useSplitJSON": true`. I can reproduce but haven't changed it, @sandy081?

**Comment by joaomoreno** [comment]
Aha! Couldn't find the name of that setting...

**Comment by joaomoreno** [comment]
Since I investigated it I ended up just pushing a fix for it. @sandy081 https://github.com/microsoft/vscode/pull/81308 Not sure why it broke tho.
