### ISSUE TITLE
Code from Run Box

### ISSUE THREAD

**Issue by mwdz519** [microsoft/vscode#80584]
- VSCode Version:1.38.0
- OS Version: Windows 10 1903

When I run "code" into the run box, it leaves opens a cmd windows, followed by VSCode. But cmd terminal remains open. Must manually close

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
'code' is a console app, intended to be ran from the command line. That's why there's a console opened.

Better run the VSCode application which you find in the start menu.
(`Visual Studio Code`)
