### ISSUE TITLE
Errors and Warnings in the status bar show negative count

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#8058]
- VSCode Version: Insiders
- OS Version: OSX

I am not sure how I got into this state, I was checking out to Master branch from my feature branch. After check out I see this weird state in the status bar.

![errors and warnings](https://cloud.githubusercontent.com/assets/10746682/16306560/68ed3266-395e-11e6-8f0b-1fe660f4689e.png)

**Comment by dbaeumer** [comment]
Without steps hard to fix. If we remove the workaround code that filters resources this might be gone anyways.

**Comment by mihailstefanov** [comment]
I have same from some time, even in latest version 1.3.1, using Typescript

**Comment by dbaeumer** [comment]
@mihailstefanov do you have any steps?

**Comment by stephanjust** [comment]
Currently facing the same issue. While I can't provide any steps to reproduce it, maybe some things I noticed might help.

1) The value is not random but a fixed offset. For me it was -15. This means that adding or removing errors to the code updates the value properly. Adding ```a a a a a a a a``` to a random line therefore resulted in 0 errors (7 times '; expected', 8 times 'cannot find name 'a''). Funnily enough while messing around I managed to increase this offset to -16, but was unable to change it any further.

2) I think it started after changing a private member to public while still being referenced in another class. Afterwards the reference in the other class randomly claimed that the member is still private, but fixed itself within seconds. The error sort of "flickered" on and off.

Restarting VSCode fixed everything.

**Comment by dbaeumer** [comment]
What kind of error was it [js], [ts], [eslint], ...

**Comment by mihailstefanov** [comment]
It is more editor connected.

Regards
Mihail

On Aug 8, 2016, at 1:15 PM, Dirk B?umer <notifications@github.com<mailto:notifications@github.com>> wrote:


What kind of error was it [js], [ts], [eslint], ...

-

**Comment by stephanjust** [comment]
> What kind of error was it [js], [ts], [eslint], ...

Sorry, these were [ts] errors.

**Comment by dbaeumer** [comment]
@stephanjust thanks.

**Comment by stephanjust** [comment]
@dbaeumer I have to correct myself: these errors have no "type" at all. I actually thought that they were [ts] errors based on the context, but as I have this happen at the moment I can see that this is not the case.

While I still have no repro steps to start the entire issue, once it's running I can control it. These errors go away when switching the tab to the file showing the errors, and if not, definitely when changing the content of the file (adding a whitespace is enough). Here are two example screenshots showing the change.

![error1](https://cloud.githubusercontent.com/assets/8887403/17510127/e6bcf102-5e1d-11e6-82ff-b220aed85e00.jpg)
![error2](https://cloud.githubusercontent.com/assets/8887403/17510128/e6c03a56-5e1d-11e6-8823-e9992a330739.jpg)

**Comment by mjbvz** [comment]
Closing this as out of date. If you still see this issue, please let us know
