### ISSUE TITLE
Add a setting for disabling link protection

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#80592]
It looks like the fancy new feature asking me if I really really meant to click a link doesn't have a setting to disable it (inside my `settings.json`). I really don't want to have to deal with disabling this manually on every machine I end up using.

**Comment by octref** [comment]
Extensions can write to your settings, so we don't want to allow configuring this in settings. You can run the new command "Toggle Link Protection for Trusted Domains".

**Comment by akbyrd** [comment]
I don't want this "feature".

**Comment by octref** [comment]
There's a legal requirement for Microsoft software for linking to websites that Microsoft has no control on.

**Comment by akbyrd** [comment]
Fine, but give me control over my own experience. I don't want or need this feature and now it's something I have to fuss with on every single install. Which ends up being relatively frequent on work machines.

**Comment by octref** [comment]
Yeah, unfortunately you would have to do it at least once on each machine. But the requirement is MS product has to acquire explicit user consent before it can direct users to other domains it has no control of.

**Comment by akbyrd** [comment]
Unfortunate, yes. I started using VS Code because it didn't get in my way and I was able to stay in the zone and productive longer than with, say, Visual Studio. However, it's steadily creeping up in little annoyances that add up to an unpleasant experience and this is right at home in the list. This is, however, the most direct and egregious example as it is literally a company decision to _get in the users way_ and stop them from doing their work. Yes, it's small, but these things matter.

I understand this has next to zero percent chance of changing and I'm talking into the void.

**Comment by kbd** [comment]
> Yeah, unfortunately you would have to do it at least once on each machine.

Would it be possible to expose this as a command-line option? This way I could include a call to (eg.):

```$ code --disable-link-protection```

as part of my automated system setup so I don't need to change this setting on every machine.

Or could extensions still call the command-line option to get around this?

**Comment by octref** [comment]
> code --disable-link-protection

I don't think that's a good addition. However our upcoming setting sync work should include syncing this hidden setting.

**Comment by kbd** [comment]
> However our upcoming setting sync work should include syncing this hidden setting.

I didn't know there is work ongoing on official settings sync. Would you mind linking the issue for settings sync so I can read about it?

The current settings sync extension is less-than-ideal, so I check my `keybindings.json`, `settings.json`, and `global.code-snippets` into source control. Will it be possible to sync just "system" settings that are uncontrollable through `settings.json` (I'd prefer to maintain my current source control setup) or will it be all-or-nothing? Thanks.

**Comment by octref** [comment]
@kbd https://github.com/microsoft/vscode/issues/78869 and https://github.com/microsoft/vscode/issues/78966. You can always find latest work in the pinned Iteration Plan:

![image](https://user-images.githubusercontent.com/4033249/66156925-85618180-e5d7-11e9-8b31-201522617a43.png)
