### ISSUE TITLE
C project creation/compiling

### ISSUE THREAD

**Issue by ualaci** [microsoft/vscode#80594]
I wish there was a simple extension that would modify either task.json so that you could compile complete projects in c, or some tool that facilitates the process of creating and compiling processes with library files and header files so far. There is or is absurdly difficult to find these tools and use.

**Comment by aeschli** [comment]
Such functionality would have to come from an extension.

**Comment by aeschli** [comment]
I suggest to ask the question on stackoverflow if there are aready some extensions or tools that scaffold a project with build task for you.

E.g. for node projects 'yo' is a tool that sets up projects for you.
