### ISSUE TITLE
Bug: go forward/go back in wrong editor pane

### ISSUE THREAD

**Issue by rycfung** [microsoft/vscode#80599]
Re: https://github.com/microsoft/vscode/issues/80343

The issue is closed as duplicate, but doesn't mention which issue it duplicates. As far as I can see from searching past issue, I don't find a duplicate.

If it is indeed a duplicate, please indicate the issue #.

**Comment by bpasero** [comment]
Seriously? https://github.com/microsoft/vscode/issues/9526
