### ISSUE TITLE
Show Fixes off screen

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#80597]
Issue Type: <b>Bug</b>

I think this is a vscode issue, I'm using Latex-Workshop (extension) with cspell (extension) to write documentation. If I mispell a word it's underlined, and the "Show Fixes" lightbuld is displayed in the left margin. However unless word-wrap is on if the current line is longer than the viewport width then "Show Fixes" appears off-screen.

This wouldn't be as much of an issue if "Toggle Word Wrap" remembered it's last setting 

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-60-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4363)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.33GB (14.61GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.11
vscode-markdownlint|Dav|0.30.2
gitlens|eam|9.9.3
flatbuffers|gab|0.1.0
vscode-pull-request-github|Git|0.10.0
pgsql-html|hub|0.0.7
rest-client|hum|0.22.0
latex-workshop|Jam|8.1.0
vscode-cudacpp|kri|0.1.1
restructuredtext|lex|114.0.0
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.7.0
python|ms-|2019.8.30787
cpptools|ms-|0.25.1
code-spell-checker|str|1.7.18
latex-utilities|tec|0.2.2
cmake|twx|0.0.17
vscode-lldb|vad|1.3.0
vscode-icons|vsc|9.3.0
debug|web|0.23.1

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> then "Show Fixes" appears off-screen

What does that mean? Do you have a screen shot for that?

**Comment by david-waterworth** [comment]
"Show Fixes" is the light bulb icon as per the image below, associated with the spelling error

![image](https://user-images.githubusercontent.com/5028974/64748321-0f787600-d555-11e9-9774-177c7de0d726.png)

If I scroll the view port horizontally it's no longer displayed.

![image](https://user-images.githubusercontent.com/5028974/64748363-39ca3380-d555-11e9-8b66-298af469e95c.png)

I'm assuming it's from vscode but it could be from cspell or latex-workshop?
