### ISSUE TITLE
Current line highlight not cleared after continuing debug

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80593]
- Debug vscode renderer process with vscode
- Click pause to pause somewhere
- Click continue
- The yellow line hightlight is still present

![image](https://user-images.githubusercontent.com/323878/64570025-1bc1c080-d314-11e9-93f9-e8f2d9317855.png)

**Comment by isidorn** [comment]
Thanks for reporting.
I was being overly smart trying to remove some code which is needed.
