### ISSUE TITLE
Tab key switches to control IDE

### ISSUE THREAD

**Issue by cray77** [microsoft/vscode#80603]
Issue Type: <b>Bug</b>

This has happened a few times since the August 2019 Update. It appears to happen for me when I stop the debugger in the middle of a debugging session.

At that point the TAB key no longer adds whitespace in any editor windows, but instead switches window focus within the visual studio code IDE.

I see an issue #76593 that was closed that looks related but I did not see a resolutions for that one.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
json-to-ts|Mar|1.5.5
better-comments|aar|2.0.5
Bookmarks|ale|10.5.0
Handlebars|and|0.4.1
azuretoolsforvscode|bra|2.0.2
regex|chr|0.2.0
gitignore|cod|0.6.0
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
cshtml-tm|fir|1.0.0
todo-tree|Gru|0.0.145
vscode-guid|hea|1.4.18
rest-client|hum|0.22.0
jmespath-vscode|jam|0.0.3
vscode-peacock|joh|3.1.5
swift|Kas|0.1.0
vscode-regexp-preivew|le0|0.0.3
sftp|lix|1.12.8
vscode-mocha-sidebar|mat|0.22.2
rainbow-csv|mec|1.3.1
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
mssql|ms-|1.6.0
python|ms-|2019.9.34911
azure-account|ms-|0.8.4
csharp|ms-|1.21.1
Go|ms-|0.11.4
azurerm-vscode-tools|msa|0.6.0
debugger-for-chrome|msj|4.11.7
vscode-foundation6-snippets|nat|0.0.1
vetur|oct|0.22.2
vscode-json-transform|oct|0.1.2
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|1.4.2
vscode-hexdump|sle|1.7.2
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.3.0
vscode-wakatime|Wak|2.2.0
vscode-preview-server|yui|1.3.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Just set `"editor.accessibilitySupport": "off"`. If you can still reproduce this after setting this let us know and we can reopen
For some reason Electron detects that you are using a screen reader.

**Comment by cray77** [comment]
Great thank you, i'll give it a shot.
