### ISSUE TITLE
"Content on disk is newer..." error prevent to save file change

### ISSUE THREAD

**Issue by FuQingYun** [microsoft/vscode#80605]
- VSCode Version: 1.38.0
- OS Version: 10.0.18362.329

Steps to Reproduce:

1. Use VS Code
2. Observe warning that VS Code did not save the file because content on disk was newer

I think it related with a recent code conflict merge by hand, after resolve code confilct and push them to git server, then I found that I cannot save change in vs code anymore.

there have 2 machine I used for develop:

machine 1 change code and push
machine 2 pull code and change then push
machine 1 pull and found code conflicts, then I resolve them by code change and push code
machine 2 pull code and change one file then push
machine 1 pull code and found that vs code cannot save file change any more

it must be a git module related bug, because I can still do save in other project.

Does this issue occur when all extensions are disabled?: Yes

![捕获](https://user-images.githubusercontent.com/40174468/64577949-87f20200-d3b0-11e9-9c0e-13467e47f6bf.PNG)

**Comment by joaomoreno** [comment]
This is a prevention feature. You haven't saved the changes in `ut1_main.go` before you pulled so Code is helping you in not losing those unsaved changes.
