### ISSUE TITLE
Auto-completion suggestions ordering needs improvement

### ISSUE THREAD

**Issue by mobileben** [microsoft/vscode#80608]
- VSCode Version: VSCode Version: 1.36.1
- OS Version: OS Version: OSX 10.14.6

Steps to Reproduce:

1. This is using Typescript. I am using the Vim plugin, but I don't think it matters.
2. Create a class called `interface Area`.
3. Start to attempt to type in `export class AnchorableArea implements Area, Anchorable`

What one will notice is that when you get the `... implements Area,`, the `,` triggers auto-complete. However, the auto-complete with the highest recommendation is `AnchorableArea`.

This should not happen for a couple of reasons.

1. I'm actually entering in the class (it's recommending a circular reference. It's illegal Typescript anyways, but just sayin')
2. Once I entered the `r` in `Area`, `AnchorableArea` should have been lowered as a suggestion.

In general, auto-complete suggestions are not very good. For example, in Xcode typing in `String` yields the following (listed in order):

```
StringPtr
StringHandle
NSString
NSStringEncoding
CFStringRef
CGPDFString
CGPDFStringRef
ConstStringPtr
```

This happens to be an Obj-C file. You'll notice that they recommend things by alphabetically matching and frequency of use. While `NSString` would in actuality be "more popular", Xcode knows that `String` is the priority. 

Note I reported this in #80500, which is now closed, but it was recommended I open individual tickets.

**Comment by mjbvz** [comment]
Here's what I see:

<img width="1197" alt="Screen Shot 2019-09-19 at 6 43 31 PM" src="https://user-images.githubusercontent.com/12821956/65292743-6827b000-db0d-11e9-9a42-851743482572.png">

When you trigger suggestions after `Area` in `implements Area`, bring up the details and enter explainer mode with `cmd` + `/` so we see why your order may be different: 

<img width="808" alt="Screen Shot 2019-09-19 at 6 45 04 PM" src="https://user-images.githubusercontent.com/12821956/65292809-b177ff80-db0d-11e9-82c3-e879ea1de3fd.png">

**Comment by mjbvz** [comment]
Closing as more information is needed

A lot of factors can influence completion sort order. Take a look at the suggestion settings to configure the behavior, such as `editor.suggestSelection`
