### ISSUE TITLE
New file naming prompt 1px missing

### ISSUE THREAD

**Issue by edk24** [microsoft/vscode#80602]
![bug](https://edk24.com/demo/bug.png)      
ahahahah  left  1px .......

https://edk24.com/demo/bug.png

**Comment by isidorn** [comment]
I can not reproduce this.
What OS are you using? Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

Here's what I see
![Screenshot 2019-09-11 at 11 02 38](https://user-images.githubusercontent.com/1926584/64683516-affe6580-d483-11e9-9096-3ed6ff34efd4.png)

**Comment by edk24** [comment]
> I can not reproduce this.
> What OS are you using? Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> 
> Here's what I see
> ![Screenshot 2019-09-11 at 11 02 38](https://user-images.githubusercontent.com/1926584/64683516-affe6580-d483-11e9-9096-3ed6ff34efd4.png)

version 1.38.0
OS: deepin 15.11

Thank you, the problem is not big.  :)

**Comment by isidorn** [comment]
I am sorry but I also can not reproduce this on Ubuntu.
Deepin we do not officialy test, thus we have no plans on fixig this. Sorry

![Screenshot 2019-09-11 at 12 02 08](https://user-images.githubusercontent.com/1926584/64688146-096a9280-d48c-11e9-849a-eb883667c004.png)
