### ISSUE TITLE
When using Typescript, auto-complete ignores interfaces, enums, and file scoped const

### ISSUE THREAD

**Issue by mobileben** [microsoft/vscode#80609]
- VSCode Version: VSCode Version: 1.36.1
- OS Version: OS Version: OSX 10.14.6

This is related to #80608. And it is very well possible they are linked together or the same. However, I can't go through every case right now where auto-complete does the wrong thing as it is so frequent in my case. You are more or less talking 85% it seems wrong. I'd say within 5 minutes of coding, it happens at the very least once a minute. Yes, that bad.

Steps to Reproduce:

1. Create an `interface` with a name that is part of another class or known keyword in Javascript.
2. Try and use the interface name. You'll find that it will not show up in the auto complete list.

The same issue exists with `enum` and scoped `const`/`let`/`var`. For the latter, almost every IDE I've used that supports auto-complete is able to auto-complete on variables.

Note I reported this in #80500, which is now closed, but it was recommended I open individual tickets.

**Comment by mjbvz** [comment]
Can you please share some example code

Also, make sure you are on the latest VS Code (1.38)
