### ISSUE TITLE
Comma and period trigger auto-complete accept

### ISSUE THREAD

**Issue by mobileben** [microsoft/vscode#80610]
- VSCode Version: 1.36.1
- OS Version: OSX 10.14.6
Steps to Reproduce:

1. Type in a word that will trigger auto-complete suggestions
2. Type in a `,` or `.`.
3. See that it triggers an accept on auto-complete.

This causes a lot of false completions. In particular if typing in the `.` or an `enum` or `.` for accessing an object property or function. Documentation in `Settings` for `editor.acceptSuggestionOnCommitCharacter` indicates:

> For example, in JavaScript, the semi-colon (;) can be a commit character...

Whilst true, it doesn't indicate `.` and `,` do the same. 

Using those two characters, in particular, make auto-complete not very useful due to all the improper replacements. Note also even hitting ESC to make it undo (or accept what is typed) still triggers auto complete.

Additionally, this should be overridable.
 
Note I reported this in #80500, which is now closed, but it was recommended I open individual tickets.

**Comment by mjbvz** [comment]
This is by design.

The specific commit characters depends on a couple of factors:

* The language (or rather the extension providing the language's support)
* The current completion item (for example, `.` may be a commit character for normal suggestions but not for path suggestions)

This means we cannot list out the entire set of commit characters in the setting description

**Comment by mobileben** [comment]
@mjbvz Okay understood. However why are `.` and `,` commit characters? They really seem like poor choices. I can understand `TAB`, `space`, and even `;`. 

Both `.` and `,` are part of the flow of typing. 

For example, if I want to type in `Types.Value`, but it auto-completes `Types` to something else (in my case it replaces it to `AutoBufferTypes`, it essentially handcuffs a user from effective usage of the tool.

Likewise, in Typescript, one can `implements` on several interfaces. So typing in `implements interface1, interface2` where `interface1` has some auto-complete suggestion ... the `,` forces the replacement.

keystroke-wise I'm then forced to either try and hit `ESC` .... which always doesn't work in my case because I'm using Vim and `ESC` takes me to the Normal mode. As soon as I go back to Insert mode and try and put in the `.` it auto-completes. Alternatively I could use `space` but then it means typing in something like 

`t` `y` `p` `e` `e` `space` `backspace` `.`

Is it possible then to only accept TAB or ENTER and ignore other special "commit characters"?

As a reference. Xcode upon a character like `.` understand it is used as a delimiter for things like enum, objects, etc. I would imagine Typescript/JS should too.

Sigh, I guess it's just me although I can't see how others are no affected by this. Or if they just live with it. It really makes auto-complete very difficult to tame and hence lowers dev productivity. I suppose it's getting close to the time to abandon the "VSCode" experiment and move on to something like WebStorm or go back to Sublime.

This is more than likely exacerbated by it not being able to use `interface`, `enum` and scoped variables in auto-suggestion, since it is I believe the leading culprit in causing incorrect matching.
