### ISSUE TITLE
 Invalid index -1

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#80615]
Issue Id: <b>f24d0573-5d5e-873e-e438-719d1e0d5cc2</b><br /><br />*Versions* <br />- 1.38.0-insider (9/3/2019 11:14:03 PM)<br />-  5ab84ce18fe7dee304325952f2849264dd4a48c1<br />-  dcc01858d3f75696568eb751238d01b30a1e7d33<br />-  190a29c9f8cb60859adaad497f316ceed717b3c2<br />*Stack* <br />Error: Invalid index -1<br />[/vs/base/browser/ui/list/listWidget.ts#1369:10 (setFocus)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/browser/ui/list/listWidget.ts#L1369:10 (setFocus))<br />[/vs/workbench/contrib/files/browser/views/openEditorsView.ts#384:13 (focusActiveEditor)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L384:13 (focusActiveEditor))<br />[/vs/workbench/contrib/files/browser/views/openEditorsView.ts#140:11 (call)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L140:11 (call))<br />[/vs/base/common/event.ts#572:15 (fire)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/common/event.ts#L572:15 (fire))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#1147:26 (doCloseActiveEditor)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1147:26 (doCloseActiveEditor))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#1317:8 (doCloseEditors)](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1317:8 (doCloseEditors))<br />[/vs/workbench/browser/parts/editor/editorGroupView.ts#1270:7](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1270:7)<br />    at Generator.next (<anonymous>)<br />[/vs/base/common/errors.ts#199:0](https://github.com/microsoft/vscode/blob/3db7e09f3b61f915d03bbfa58e258d6eee843f35/src/vs/base/common/errors.ts#L199:0)<br />

**Comment by joaomoreno** [comment]
@aeschli The stack trace says OpenEditors.
