### ISSUE TITLE
Menus should be shown on top of quick picks menus

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#80611]
Issue Type: <b>Bug</b>

If quick pick menus aren't set to close when focus is lost, any menus opened show up behind the quick pick. IMO the menus should be shown on top of quick pick.

![image](https://user-images.githubusercontent.com/641685/64584887-987c8b00-d364-11e9-9fb8-eb5057e94a05.png)

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
This is even a bit worse if you open a context menu from inside the quickpick
![image](https://user-images.githubusercontent.com/641685/70569387-dc4f7e00-1b67-11ea-983c-fc070e4c005d.png)

**Comment by sbatten** [comment]
fixed by f149dbbedf99267b175bd6c4abae2341102aa408
