### ISSUE TITLE
change missed by gulp-tsb

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80629]
Steps:
```sh
git checkout 51334d5bd9d52c2ad47b2c78c143683544a00933
yarn run gulp watch-client
# wait for gulp to finish and in another terminal, run
git checkout 0b3ae7e0898ac4afd39d2463c39ced7c847341e6
```

When trying to launch `scripts\code.bat`:
```
$ scripts\code.bat
[11:11:54] Syncronizing built-in extensions...
[11:11:54] You can manage built-in extensions with the --builtin flag
[11:11:54] [marketplace] ms-vscode.node-debug@1.38.4 ✔︎
[11:11:54] [marketplace] ms-vscode.node-debug2@1.33.0 ✔︎
[11:11:54] [marketplace] ms-vscode.references-view@0.0.30 ✔︎

 { [Error: ENOENT: no such file or directory, open 'C:\Alex\src\vscode\out\vs\platform\url\common\urlIpc.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Alex\\src\\vscode\\out\\vs\\platform\\url\\common\\urlIpc.js',
  phase: 'loading',
  moduleId: 'vs/platform/url/common/urlIpc',
  neededBy: [ 'vs/code/electron-main/app' ] }
```

Verbose gulp output:
[gulp-log.txt](https://github.com/microsoft/vscode/files/3594803/gulp-log.txt)

**Comment by jrieken** [comment]
```
[11:26:56] Starting compilation...
FILE /Users/jrieken/Code/vscode/src/vs/platform/url/node/urlIpc.ts true 0
FILE /Users/jrieken/Code/vscode/src/vs/platform/url/common/urlIpc.ts true 3156
FILE /Users/jrieken/Code/vscode/src/vs/workbench/services/url/electron-browser/urlService.ts true 2199
FILE /Users/jrieken/Code/vscode/src/vs/code/electron-main/app.ts true 29455
compile NOW
```

Adding some in line log when files are being piped into tsb. The problem is that deleted files are piped as *empty*, not as files without content. The contract is that `File.content` shouldn't be defined (to allow to differentiate between empty and deleted files). Not sure when that changed...

**Comment by jrieken** [comment]
gulp-tsb source reference: https://github.com/jrieken/gulp-tsb/blob/6fe856e1098c55895d19cf53976d3c0aca80e552/src/builder.ts#L63-L67

**Comment by alexandrudima** [comment]
@jrieken deleted files come as empty content files since a long long time

**Comment by alexandrudima** [comment]
See https://github.com/microsoft/vscode/blame/master/build/lib/watch/index.js#L8

**Comment by jrieken** [comment]
The check for falsy-ness was written 4 years ago, it must never have worked then. We never checked for an empty buffer
