### ISSUE TITLE
Add option for multi cursor "distributed" paste

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80624]
When having multi line text in the clipboard and pasting, VS Code will check if the clipboard text line count matches the cursor count, and if it does, it will "distribute" each line to a cursor.

- Copy the following text to the clipboard:
```
Line 1
Line 2
Line 3
```
- Create 3 cursors (to match the line count)
- Paste

![80624](https://user-images.githubusercontent.com/5047891/64595865-1c5d6400-d3b3-11e9-8dd3-fed34f0e17ab.gif)

---

Add an option to disable this "distributed" paste:
![80624-2](https://user-images.githubusercontent.com/5047891/64596046-7ceca100-d3b3-11e9-9ca6-e20c41ea26d8.gif)

**Comment by alexandrudima** [comment]
The options is called `editor.multiCursorPaste` and can have the value `spread` or `full`. `spread` is the default to maintain compatibility with the current behavior.

![image](https://user-images.githubusercontent.com/5047891/64598087-6cd6c080-d3b7-11e9-8f97-789e0e172477.png)

**Comment by rshakerov** [comment]
Hi, seem like spread in Multi Curso Paste does not work any more as of 1.39.2.
Any option behaves like full. Could you please check it?

**Comment by alexandrudima** [comment]
@rshakerov Can you please open a new issue with precise steps? I have checked and IMHO the spread behaves fine.

**Comment by randre70** [comment]
@rshakerov Did you solve your issue? @alexandrudima I have the same issue: multiCursorPaste "spread" is not working in 1.39.2 (Windows).

**Comment by alexandrudima** [comment]
@randre70 Please open a new issue with precise steps.

**Comment by rshakerov** [comment]
> @rshakerov Did you solve your issue? @alexandrudima I have the same issue: multiCursorPaste "spread" is not working in 1.39.2 (Windows).

Yes, after restarting VS Code it came back to normal.
