### ISSUE TITLE
Debugging relay todo example es6 code using Attach does not work correctly

### ISSUE THREAD

**Issue by bennyticklez** [Microsoft/vscode#8062]
- VSCode Version: 1.3.0
- OS Version: 10.10.5
- Node Version: 5.10.0

Using the "todo" example from https://github.com/facebook/relay/

I have set up Vscode to debug the server database.js file by using the Attach method. 

Steps to Reproduce:
1. Run "npm start" which runs the following line:
   npm run update-schema && babel-node --debug ./server.js
2. Attach via the Debug and refresh the webpage  

Here is the launch.json settings:
<img width="536" alt="screen shot 2016-06-23 at 16 23 44" src="https://cloud.githubusercontent.com/assets/9270069/16310575/fa1d44aa-3964-11e6-8bcf-e3b689eafe34.png">

Here is the .babelrc settings:
<img width="612" alt="screen shot 2016-06-23 at 16 23 16" src="https://cloud.githubusercontent.com/assets/9270069/16310591/0bfa2f44-3965-11e6-9334-26a8a4cd720a.png">

The debugger only stops inside the database.js file if I add a "debugger;" tag. It never lands on any of the breakpoints. It also stops many lines down from the debugger tag.

It is meant to stop here:

<img width="803" alt="screen shot 2016-06-23 at 16 24 57" src="https://cloud.githubusercontent.com/assets/9270069/16310637/3db02d36-3965-11e6-99a5-3a5fd9a03410.png">

But ends up stopping here:

<img width="802" alt="screen shot 2016-06-23 at 17 08 31" src="https://cloud.githubusercontent.com/assets/9270069/16310731/a06ee69c-3965-11e6-8db9-658c49839157.png">

I'm sure this is a problem related to es6 transpiling because I created a es5 file (databasees5.js) with a single function in it that is called from database.js.
If I add breakpoints inside this file it stops on the breakpoints in exactly the right place.

<img width="478" alt="screen shot 2016-06-23 at 17 10 30" src="https://cloud.githubusercontent.com/assets/9270069/16310685/6d5dc084-3965-11e6-9a9d-641c693f8138.png">

**Comment by weinand** [comment]
@bennyticklez sorry, but I cannot get your setup to run. The steps from above are incomplete and I do not want to type in the testxt from the .babelrc sceenshot.

I noticed on the launch.json screenshot that you have set "sourceMaps" to true but "outDir" is not pointing to the root of the generated code. Please add that and see whether this makes a difference.

**Comment by bennyticklez** [comment]
Thank you for getting back to me. I generated the .js and map.js files into a /lib directory. Now when I run the Attach I get trace information with successful mapping. It does not stop on the breakpoints though.

![sourcemap](https://cloud.githubusercontent.com/assets/9270069/16339595/6f47e09e-3a1b-11e6-8a89-3901a6dde822.jpg)

**Comment by weinand** [comment]
This issue is very old and should no longer be an issue.
