### ISSUE TITLE
Opening function definition will not go to already open file if file in split panel.

### ISSUE THREAD

**Issue by stefnas** [microsoft/vscode#80625]
I have VS Code 1.38.0.

I'm programming in C and I like working with files open side by side. Let's say I have a file "A" open on the left side and a file "B" open on the right side. If there is a function call in file A that is defined in file B, if I right-click on the function call and select "Go to Definition", a new tab with the file B will open on the left side and now I have file B open twice. What i want instead is for the already open file B to just go to the definition of the function. Is there any setting to enable that?

This behavior actually works when you have one panel only and multiple tabs but doesn't work if you have both left and right panel open.

**Comment by jrieken** [comment]
Yeah, that's `workbench.editor.revealIfOpen`
