### ISSUE TITLE
Breakpoint remains after hovering

### ISSUE THREAD

**Issue by Syopic** [microsoft/vscode#80628]
In code input mode, hover over the area to set the breakpoints, but do not set. A pale red circle lights up. Then move the mouse cursor to the side. After a few tries, the circle remains - thus frustrating the user.
![image](https://media.giphy.com/media/J5pKmze6lGFAUuZtvb/giphy.gif)

**Comment by isidorn** [comment]
There seems to be some corner case which we are not covering when showing the breakpoint hover.
We are open to a PR which fixes this.
Code pointer https://github.com/Microsoft/vscode/blob/dd7daae7de1d229280400ab9ddc20973fb3178bb/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L238

No plans to tackle this mysels, thus assigning to Backlog.
