### ISSUE TITLE
jsconfig excluded files not excluded from import suggestions

### ISSUE THREAD

**Issue by Undistraction** [microsoft/vscode#80636]
Issue Type: <b>Bug</b>

With the following jsconfig: 
```
{
  "compilerOptions": {
    "target": "es6",
  },
  "exclude": [
    "/packages/components/es/components/buttons/Button/Button.js",
  ]
}
```
I would expect `Button.js` to be excluded from the project and excluded import suggestions, however it still appears as one of the suggested imports. The same is true if I exclude `**/es/*` which is what I tried before using an explicit path.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 9, 8|
|Memory (System)|32.00GB (0.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal-tabs|Tyr|0.2.0
html-snippets|abu|0.2.1
project-manager|ale|10.7.0
folder-source-actions|bie|0.2.0
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
fileheadercomment|doi|0.0.3
githistory|don|0.4.6
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|2.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
search-node-modules|jas|1.3.0
svg|joc|0.1.6
docthis|joe|0.7.1
vscode-peacock|joh|3.1.5
vscode-styled-components|jpo|0.0.26
vscode-gutter-preview|kis|0.22.3
graphql-for-vscode|kum|1.15.1
node-module-intellisense|lei|1.5.0
vscode-apache|mrm|1.2.0
debugger-for-chrome|msj|4.11.7
material-icon-theme|PKi|3.9.0
ruby|reb|0.25.3
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.2
stylelint|shi|0.51.0
rewrap|stk|1.9.1
code-spell-checker|str|1.7.18
vscode-icons|vsc|9.3.0
vscode-js-import|wan|0.15.5
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue/feature request upstream](https://github.com/microsoft/TypeScript/issues/new)
