### ISSUE TITLE
Extract to type alias not working

### ISSUE THREAD

**Issue by B3zo0** [microsoft/vscode#80635]
Issue Type: <b>Bug</b>

Extract type to alias code fix is not working in latest insider.

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:25:22.729Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>Error Stack</summary>

> ERR <semantic> TypeScript Server Error (3.6.2)
> Debug Failure. False expression: Token end is child end
> Error: Debug Failure. False expression: Token end is child end
>     at processChildNode (tsserver.js:113552:34)
>     at tsserver.js:113499:21
>     at visitNode (tsserver.js:17018:24)
>     at Object.forEachChild (tsserver.js:17096:21)
>     at processNode (tsserver.js:113498:20)
>     at processChildNode (tsserver.js:113558:21)
>     at processChildNodes (tsserver.js:113609:48)
>     at tsserver.js:113501:21
>     at visitNodes (tsserver.js:17023:24)
>     at Object.forEachChild (tsserver.js:17158:24)
>     at processNode (tsserver.js:113498:20)
>     at processChildNode (tsserver.js:113558:21)
>     at tsserver.js:113499:21
>     at visitNode (tsserver.js:17018:24)
>     at Object.forEachChild (tsserver.js:17341:21)
>     at processNode (tsserver.js:113498:20)
>     at formatSpanWorker (tsserver.js:113313:17)
>     at tsserver.js:113277:140
>     at Object.getFormattingScanner (tsserver.js:112070:23)
>     at Object.formatNodeGivenIndentation (tsserver.js:113277:31)
>     at getFormattedTextOfNode (tsserver.js:115313:45)
>     at format (tsserver.js:115291:52)
>     at computeNewText (tsserver.js:115294:23)
>     at tsserver.js:115264:89
>     at Array.map (<anonymous>)
>     at tsserver.js:115263:50
>     at Array.map (<anonymous>)
>     at Object.getTextChangesFromChanges (tsserver.js:115249:86)
>     at ChangeTracker.getChanges (tsserver.js:115219:45)
>     at Function.ChangeTracker.with (tsserver.js:114754:32)
>     at Object.getEditsForAction (tsserver.js:122779:62)
>     at Object.getEditsForRefactor (tsserver.js:115829:41)
>     at Proxy.getEditsForRefactor (tsserver.js:126029:32)
>     at IOSession.Session.getEditsForRefactor (tsserver.js:134940:59)
>     at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133793:61)
>     at tsserver.js:135178:88
>     at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
>     at IOSession.Session.executeCommand (tsserver.js:135178:33)
>     at IOSession.Session.onMessage (tsserver.js:135201:35)
>     at Interface.<anonymous> (tsserver.js:136516:27)
>     at Interface.emit (events.js:182:13)
>     at Interface._onLine (readline.js:290:10)
>     at Interface._normalWrite (readline.js:433:12)
>     at Socket.ondata (readline.js:149:10)
>     at Socket.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at Socket.Readable.push (_stream_readable.js:219:10)
>     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.6.2)
> Debug Failure. False expression: Token end is child end
> Error: Debug Failure. False expression: Token end is child end
>     at processChildNode (tsserver.js:113552:34)
>     at tsserver.js:113499:21
>     at visitNode (tsserver.js:17018:24)
>     at Object.forEachChild (tsserver.js:17096:21)
>     at processNode (tsserver.js:113498:20)
>     at processChildNode (tsserver.js:113558:21)
>     at processChildNodes (tsserver.js:113609:48)
>     at tsserver.js:113501:21
>     at visitNodes (tsserver.js:17023:24)
>     at Object.forEachChild (tsserver.js:17158:24)
>     at processNode (tsserver.js:113498:20)
>     at processChildNode (tsserver.js:113558:21)
>     at tsserver.js:113499:21
>     at visitNode (tsserver.js:17018:24)
>     at Object.forEachChild (tsserver.js:17341:21)
>     at processNode (tsserver.js:113498:20)
>     at formatSpanWorker (tsserver.js:113313:17)
>     at tsserver.js:113277:140
>     at Object.getFormattingScanner (tsserver.js:112070:23)
>     at Object.formatNodeGivenIndentation (tsserver.js:113277:31)
>     at getFormattedTextOfNode (tsserver.js:115313:45)
>     at format (tsserver.js:115291:52)
>     at computeNewText (tsserver.js:115294:23)
>     at tsserver.js:115264:89
>     at Array.map (<anonymous>)
>     at tsserver.js:115263:50
>     at Array.map (<anonymous>)
>     at Object.getTextChangesFromChanges (tsserver.js:115249:86)
>     at ChangeTracker.getChanges (tsserver.js:115219:45)
>     at Function.ChangeTracker.with (tsserver.js:114754:32)
>     at Object.getEditsForAction (tsserver.js:122779:62)
>     at Object.getEditsForRefactor (tsserver.js:115829:41)
>     at Proxy.getEditsForRefactor (tsserver.js:126029:32)
>     at IOSession.Session.getEditsForRefactor (tsserver.js:134940:59)
>     at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133793:61)
>     at tsserver.js:135178:88
>     at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
>     at IOSession.Session.executeCommand (tsserver.js:135178:33)
>     at IOSession.Session.onMessage (tsserver.js:135201:35)
>     at Interface.<anonymous> (tsserver.js:136516:27)
>     at Interface.emit (events.js:182:13)
>     at Interface._onLine (readline.js:290:10)
>     at Interface._normalWrite (readline.js:433:12)
>     at Socket.ondata (readline.js:149:10)
>     at Socket.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at Socket.Readable.push (_stream_readable.js:219:10)
>     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> 	at Function.create (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:63463)
> 	at h.dispatchResponse (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:56618)
> 	at h.dispatchMessage (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:55516)
> 	at _reader.onData.e (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:54992)
> 	at l.fire (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/out/vs/server/remoteExtensionHostProcess.js:49:984)
> 	at t.Reader.onLengthData (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:61683)
> 	at Socket.e.on.e (/home/bezoo/.vscode-server-insiders/bin/55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5/extensions/typescript-language-features/dist/extension.js:53:61331)
> 	at Socket.emit (events.js:182:13)
> 	at addChunk (_stream_readable.js:283:12)
> 	at readableAddChunk (_stream_readable.js:264:11)
> 	at Socket.Readable.push (_stream_readable.js:219:10)
> 	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|Memory (System)|31.94GB (7.84GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.4.3
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.75.0
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
debugger-for-chrome|msj|4.11.7
code-settings-sync|Sha|3.4.2
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
shell-format|fox|6.1.1
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.26
csharp|ms-|1.21.2
vsliveshare|ms-|1.0.766
vscode-versionlens|pfl|0.24.0
vscode-react-refactor|pla|1.0.5
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Share example code and repo steps

/needsMoreInfo

**Comment by B3zo0** [comment]
Hi Matt,

This is the example code that is not working. I'm trying to extract the prop types from the generic parameter by selecting the curly braces and then `CTRL + .` _Extract to type alias_
It is still a problem in latest vscode insider however I now see an error notification on the right side. Which I think is better than silently failing.

```tsx
export const UploadDialog: React.FunctionComponent<{
  dialogProps: DialogProps
  content: GenericContent
}> = props => {
  return null
}
```

Thanks for your hard work. ✌🏻

**Comment by mjbvz** [comment]
Thanks. I confirmed this is broken when using TS 3.6.2 (the builtin TS version for VS Code 1.38) but it seems to work when using typescript@next

You can upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Closing as fixed upstream. We'll pick up TS 3.7 once the final version ships
