### ISSUE TITLE
Source Control Git: VSCode lets you create a branch with a # in the name which makes it undeletable [Linux]

### ISSUE THREAD

**Issue by HelplessEskimo** [microsoft/vscode#80637]
when using source control I can create a git branch with a # prefix on the name, this means that the branch cannot be deleted using the command line and cannot be deleted from the remote repo at all.

testing this is simple. use code to create a new branch, put a hash at the start of the name, then try and delete it using the command line. 

I have only the python support extension installed.

using version 1.38.0

**Comment by joaomoreno** [comment]
This is fine. I've just created a `#hello` branch using the `Git: Create Branch` command and deleted it using the `Git: Delete Branch` command. If you want to delete it from the command line you have to escape the character according to whatever escape rules your shell uses. Usually it's:

```
$ git branch -d \#foo
Deleted branch #foo (was 70e59e3).
```
