### ISSUE TITLE
codetree symbol disappears when zooming

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#8063]
- VSCode Version: Code - Insiders 1.3.0-insider (16676b2d1418313e949007ce98c95ca4e1cb28d9, 2016-06-21T17:35:01.730Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
jsx file..
![image](https://cloud.githubusercontent.com/assets/5635709/16311869/772ce04c-3972-11e6-8719-dcba53d28ea0.png)

1. Ctrl+ +

![image](https://cloud.githubusercontent.com/assets/5635709/16311838/631c8670-3972-11e6-9769-bc4d9ab7f18e.png)

**Comment by aeschli** [comment]
https://github.com/Microsoft/monaco-editor/issues/22 thinks that the z-index is the problem.

@joaomoreno You were involved in that change...

**Comment by joaomoreno** [comment]
We can simply revert ff9bf52. Should we?

**Comment by aeschli** [comment]
Just removing the z-index seems to fix the issue. Do you know why it is there?

**Comment by joaomoreno** [comment]
No idea...

**Comment by joaomoreno** [comment]
Thanks for looking into the issue, @aeschli !
