### ISSUE TITLE
Extension Host terminates

### ISSUE THREAD

**Issue by johnbirt** [microsoft/vscode#80647]
Issue Type: <b>Bug</b>

After last update on insider cycle yesterday Extension Host terminates and in particular Live Server and SCSS Live Compiler both fail.

This particular update seems very flaky. All other insider updates have never given any trouble at all.

Even toggling Dev Tools caused a crash.

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:23:19.252Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (3.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|17%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-class-suggestions|And|1.0.7
vscode-color|ans|0.4.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|30.0.0
html-slim-scss-css-class-completion|gen|1.5.20
gc-excelviewer|Gra|2.1.32
minify|Hoo|0.4.3
vscode-esformatter|how|1.6.0
code-beautifier|mic|2.3.3
vscode-html-format|moh|0.0.3
debugger-for-chrome|msj|4.11.7
printcode|nob|3.0.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
html-validate-vscode|Tob|0.2.0
vscode-icons|vsc|9.3.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
Can you see the same without any extensions?
Any steps to follow? What type of file do you open?

**Comment by johnbirt** [comment]
Thanks for reply.
I have not used the insider ring version I have on the iMac but have been using a Windows version via Parallels without issue and also another Windows version on a laptop all without issue.

I pinned it down to Live server and SCCSLive compiler. I removed them and re-installed and still had issue. Uninstalled and still problem so went and worked on the Windows version.

There have been 2 updates to this versionwhich may have improved matters. When I have time I will uninstall completely and install afresh.

September 2019 (version 1.39)
Insiders Release

I have used it for a short time just now and not had the long wait for extensions to load and then disappearance and stopping of extensions.

Just very small SCSS, JS vanilla and very short HTML pieces - nothing very testing.

Will report back if further issues but seems OK at moment following updates.

Thanks for the follow up.

Regards

John B


On 11 Sep 2019, at 08:45, Martin Aeschlimann <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you see the same without any extensions?
Any steps to follow? What type of file do you open?

**Comment by aeschli** [comment]
Thanks, please reopen if you see this again and have steps on how we can reproduce.
