### ISSUE TITLE
Re-enable usage of contributed schemes in markdown

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#80643]
This is the continuation of https://github.com/microsoft/vscode/issues/80352 so that we allow links in markdown to all schemes that VS Code supports. This requires a way to feed supported schemes into the markdown rendering layer

**Comment by mjbvz** [comment]
Links to files that come from a custom file system provider (such as `[a](msteams://a)`) still work after this change. We don't support loading images from custom file system schemes but I'm not sure if this capability was actually being use I had not seen this issue reported by an extension authors yet

Closing as wont fix for now. We can revisit if someone runs into the problem with an extension
