### ISSUE TITLE
Create test for this method

### ISSUE THREAD

**Issue by ivaylopivanov** [Microsoft/vscode#8064]
I'm not sure if this is the right place to ask or if there is existing solution for that, but after few hours of googling I was not able to find it. I'm searching for a functionality or extension which will allows me to right click on a method name and create instantly a test for this method. If there is no such solution at the moment, do you plan to add it in the future?

**Comment by dbaeumer** [comment]
Which programming language are you using.

**Comment by ivaylopivanov** [comment]
C++ / Go / Typescript / Javascript

**Comment by dbaeumer** [comment]
Can you please file corresponding requests for C++ & Go in their repositories.

**Comment by mjbvz** [comment]
This is outside the scope of VSCode, but such functionality could be implemented as an extension.
