### ISSUE TITLE
doesn't highlight comment in C++ member initializer lists

### ISSUE THREAD

**Issue by hokein** [microsoft/vscode#80644]
- VSCode Version: 1.37.0
- OS Version: Linux

Steps to Reproduce:

Open test.cpp:
```cpp
struct Foo {
  Foo();
  int a;
  int b;
  int c;
};
Foo::Foo()
    : a(1),
      //     b(2),
      c(3) {}
```

See screenshot:

![image](https://user-images.githubusercontent.com/2557445/64616586-25fbc180-d3dd-11e9-99f1-c1ee78146fea.png)

comment on line 12 is not highlighted.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thanks @matter123 for coping this over to https://github.com/jeff-hykin/cpp-textmate-grammar/issues/389

Leaving open to verify after the grammar changes is pulled in.

**Comment by alexr00** [comment]
Grammar update to `1.14.6` and test added for this case!
