### ISSUE TITLE
Don't cut word-by-word in git commit message input placeholder text

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#80655]
Because the branch name is too long I'm seeing this:
![image](https://user-images.githubusercontent.com/530988/64630838-d5d92b00-d3ed-11e9-947f-d38606c609f7.png)

It should instead show as much as possible and (if easy) show ellipsis at the end.

**Comment by joaomoreno** [comment]
What version do you have installed? This should be fixed by now. Here's the latest on `master`:

![image](https://user-images.githubusercontent.com/22350/64846207-4f4e6480-d60c-11e9-88d7-29de0bbbe453.png)

**Comment by letmaik** [comment]
@joaomoreno You're right, fixed in Insiders. Thanks!
