### ISSUE TITLE
Settings (JSON) icon is missing on Insiders

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#80654]
Issue Type: <b>Bug</b>

Something weird is happening with the icon, from last Friday's build (https://github.com/Microsoft/vscode/commit/9414b7e75bdbef887c76cb603e542db2b86b99b7) it was there, and on Monday it was gone:

![image](https://user-images.githubusercontent.com/35271042/64630418-eb2c6600-d3a9-11e9-9ef5-4112c5a1f613.png)

But when I run from source it's there:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/35271042/64630462-05664400-d3aa-11e9-94e8-954e7d36481a.png">

cc @bpasero @isidorn in case either of you knows what's been happening with icons missing

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:23:19.252Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.34.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
vscode-open-in-github|fab|1.2.1
nightswitch-lite|gha|2.2.2
vscode-pull-request-github-insiders|Git|2019.9.13862
todo-tree|Gru|0.0.147
vscode-colorize|kam|0.8.12
vscode-azureappservice|ms-|0.15.0
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34911
remote-containers|ms-|0.75.0
remote-ssh-edit-nightly|ms-|2019.9.13860
remote-ssh-explorer-nightly|ms-|2019.9.13860
remote-ssh-nightly|ms-|2019.9.13860
azure-account|ms-|0.8.4
vscode-typescript-tslint-plugin|ms-|1.2.2
cloudenv|ms-|1.0.768
cloudenv-explorer|ms-|1.0.768
cloudenv-extensions|ms-|1.0.768
rescuetime|Res|1.0.1
code-settings-sync|Sha|3.4.2
errorlens|use|2.7.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Maybe this adoption of loading icons from AMD @isidorn @alexandrudima ?

**Comment by alexandrudima** [comment]
Yeah, looks like an oversight. I am looking into it...

**Comment by isidorn** [comment]
@alexandrudima  Thanks for fixing this
