### ISSUE TITLE
Local Folder and VS Code Folder Not Communicating

### ISSUE THREAD

**Issue by clocknane** [microsoft/vscode#80659]
Hi,

I am having an issue where VS code and the local folder on my local laptop is different than what VS code shows upon me going to File > Open Folder and choosing that folder. I have compared the code line by line with multiple HTML and CSS docs, and they are identical, yet when I open Live server within VS code, my html files display correctly (links work, css works, javascript works etc.), however, if I just go to my local folder within Windows Explorer and pull up the website on my local directory, it loads the pages without the CSS. I have deleted the folder after making a backup and replaced the html, css, js files one by one, but the issue persist. Can someone shed some light on this? Is this a bug or what am I missing?

Running Windows 10 v. 1809
Drivers: Updated to Latest drivers for Chipset, GPU, Audio, BIOS, USB, docks etc. 
VS Code version: 1.38
Extensions Installed: Live Server Only

**Comment by liushuaimaya** [comment]
I had the same problem, have to  restart vscode everytime.

**Comment by aeschli** [comment]
Sounds like a Live Server issue?
Please file against https://github.com/ritwickdey/vscode-live-server/issues
