### ISSUE TITLE
Markdown: Find widget arrows look disabled

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#80656]
Issue Type: <b>Bug</b>

1. Open markdown preview
1. <kbd>Ctrl</kbd>+<kbd>F</kbd> Search for existing term
1. There are matches but the arrows look faded

![Screenshot (75)](https://user-images.githubusercontent.com/9638156/64633023-04153580-d403-11e9-9c69-042535c092e2.png)

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:25:22.729Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
It blinks now on every typed character (when you type text that is a match).

**Comment by Tyriar** [comment]
We should fix the blinking that @usernamehw called out

**Comment by mjbvz** [comment]
fix is too dangerous for this iteration. Moving to October

**Comment by usernamehw** [comment]
I think it works now.
