### ISSUE TITLE
wordBasedSuggestions: false doesn't work in Markdown files

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#8065]
- VSCode Version:1.2.1
- OS Version:Windows 10

Steps to Reproduce:

1. Set "editor.wordBasedSuggestions": false
2. Place the cursor in a Markdown document (no text highlighted)
3. Ctrl+space yields full word list and not just available md snippets

**Comment by jrieken** [comment]
We have moved markdown into an extension which fixes this
