### ISSUE TITLE
folder creates  automatically inside the recently working folder 

### ISSUE THREAD

**Issue by bunnysworld** [microsoft/vscode#80651]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post details of how to reproduce this. Screenshots are useful. Also post version info from About.

**Comment by bunnysworld** [comment]
> /needsMoreInfo please post details of how to reproduce this. Screenshots are useful. Also post version info from About.
