### ISSUE TITLE
Regex Search and Replace All capture groups don't work when regex includes newline

### ISSUE THREAD

**Issue by jdmoody** [microsoft/vscode#80667]
Issue Type: <b>Bug</b>

1. Create a new file with the following:
```
foo
bar baz
```

2. Open the Search tab and add the following search (ensure "Use Regular Expression" is enabled):
```
foo\n(bar) baz
```

3. Open the replace dropdown and use the following replace:
```
$1 baz
```

4. Run "Replace All"

Expected: File text is replaced with `bar baz`
Actual: File text is replaced with `$1 baz`

What's odd is that this only happens for the actual Search tab. If I do the exact same search and replace inline for the file, it replaces the capture group correctly.

Also, the Search tab replaces capture groups properly when there's no newline. This bug only happens when the match contains a newline.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

Extensions: none

**Comment by mrstandu33** [comment]
This issue could be referenced in #9010.

When we look a this bug ($1 isn't referrencing group, just used as string "$1") we find #9010, it's a pain to find this #80667 issue.

Btw, glad you fixed it, you rocks guys ! 💪
