### ISSUE TITLE
Git complains 

### ISSUE THREAD

**Issue by Brandon-Huang** [microsoft/vscode#80662]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

when do git changes, like revert or commit, if vs code open, it complains for rename from .git/index.lock to .git/index failed

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2701)|
|Memory (System)|15.85GB (6.03GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
terraform|mau|1.4.0
vetur|oct|0.22.2
vscode-open|san|0.1.0
stylelint|shi|0.51.0
gitblame|wad|3.0.1
classic-asp-html|jtj|0.1.1
intellij-idea-keybindings|k--|0.2.34
vscode-docker|ms-|0.7.0
remote-wsl|ms-|0.39.5
debugger-for-chrome|msj|4.11.7

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the complaint?

**Comment by Brandon-Huang** [comment]
To reproduce this, I need to open a folder with vscode and wsl, and it has to be a git folder.
than I open it out side of the WSL, let's say windows git, and try to commit or push it. it will complain a lock. also, if I go back to WSL then, WSL will complain the lock as well. 

Then I have to close vscode window and allow the lock to be lift. Then, I can do all git action later.

screenshot attached

![tempsnip](https://user-images.githubusercontent.com/3480392/64988505-34405680-d891-11e9-9224-c3661fa5eb0b.png)

**Comment by joaomoreno** [comment]
Are you using VS Code Remote WSL?

**Comment by Brandon-Huang** [comment]
yes

From Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by joaomoreno** [comment]
Is your repository inside WSL or outside?

**Comment by Brandon-Huang** [comment]
Cloned from outside, develop in side, commit out side, triggers the issue, then no matter inside or outside, both locked and can’t commit or push.

From Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by joaomoreno** [comment]
Can you re-clone the repository from inside?

**Comment by Brandon-Huang** [comment]
It's the same.

**Comment by joaomoreno** [comment]
I can't reproduce this. If you initialize the repo from within WSL, then everything works with VS Code Remote WSL. Can you show me a video reproducing the issue, with a brand new repository?

**Comment by Brandon-Huang** [comment]
It's pretty difficult for me to record screen from my company.
