### ISSUE TITLE
warnings in file default settings

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#8066]
- VSCode Version: 

![2016-06-23 20 25 40](https://cloud.githubusercontent.com/assets/3082812/16313206/dbb1f10c-3980-11e6-9961-b833d517dcfe.png)
- OS Version:

![2016-06-23 20 28 00](https://cloud.githubusercontent.com/assets/3082812/16313256/10c6921c-3981-11e6-8b6b-c7865aa3e7de.png)

### Steps to Reproduce 1:

1. open user settings

2. open the list of warnings

![2016-06-23 20 29 56](https://cloud.githubusercontent.com/assets/3082812/16313308/52a6f366-3981-11e6-8ce1-9134ec7a8032.png)

**properties**
   "jshint.config": null,
   "jshint.excludePath": null,
   "markdown.styles": null,

### Steps to Reproduce 2:

1. after "Steps to Reproduce 1" close all open workspace

2. click to "warning message"

![2016-06-23 20 33 18](https://cloud.githubusercontent.com/assets/3082812/16313424/d010d1dc-3981-11e6-91f8-b34abfd6b242.png)

**Comment by dbaeumer** [comment]
@aeschli not sure if this is you.

**Comment by aeschli** [comment]
@kieferrm These are issues in with the markdown resp the jsLint settings schema:
If `null` is a valid value for a setting, the settings schema needs to list 'null' as in the 'type' as well.
See property "type" in the example below
e.g.
```json
"markdown.styles": {
	"type": ["array", "null"],
	"default" : null,
	"description": "A list of URLs or local paths to CSS style sheets to use from the markdown preview."
}
```
