### ISSUE TITLE
Save Jupyter Notebook (Python VS Code)

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode#80665]
For the upcoming Native Jupyter experience release in the Python extension for VS Code, we are using a webview instead of an editor. We would like the ability to intercept the File menu save to trigger a save of the webview Jupyter notebook, such that when a user presses FIle->Save, it should save the Jupyter notebook file.

Also, currently CTRL + S works only when the webview has focus, It doesn't save when it does not have focus.

Relevant Issues:
https://github.com/microsoft/vscode-python/issues/7238
https://github.com/microsoft/vscode-python/issues/7258
https://github.com/microsoft/vscode/issues/76863

**Comment by mjbvz** [comment]
Duplicate of #77131
