### ISSUE TITLE
property "processor" is not allowed in eslintrc.json

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#80660]
- VSCode Version: 1.38.0
- OS Version:1903 18362.329

Steps to Reproduce:

1. edit a .eslintrc to include override, with processor entry

![image](https://user-images.githubusercontent.com/618922/64640723-7d605880-d402-11e9-9c62-0ca186efd556.png)

I guess a schema is wrong

https://eslint.org/docs/user-guide/configuring#specifying-processor

yes

**Comment by aeschli** [comment]
It very likly comes from this schema: http://json.schemastore.org/eslintrc

You need to file the issue there.

**Comment by stalkerg** [comment]
I created the issue on schema tracker. 
PS Another one svelte3 user.

**Comment by SteveALee** [comment]
@stalkerg Thank you. For some reason I did not get the email notification for @aeschli's comment.
