### ISSUE TITLE
Repeated definition found when attaching to module.exports

### ISSUE THREAD

**Issue by conradkoh** [microsoft/vscode#80678]
- VSCode Version: 1.38.0
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Create a new file with the following code
```
module.exports.test = async () => {
    return 123;
}

module.exports.test();
```
2. Cmd + Click on the usage of function
3. Panel shows up with 2 definitions, although the references to the definitions are for the same file at the same line

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Thanks for the example. Opened https://github.com/microsoft/TypeScript/issues/33520 to track this upstream
