### ISSUE TITLE
JSON schema file doesn't provide intellisense until the initial save of a .json file

### ISSUE THREAD

**Issue by jgoshi** [Microsoft/vscode#8067]
- VSCode Version: 1.2.1
- VSCode C++ extension Version: 0.7.0
- OS Version: Windows 10 Enterprise

NOTE: You need the C++ extension version 0.7.0 or later because we introduced the c_cpp_properties.json schema file.

Steps to Reproduce:

1. Open any folder containing a .cpp file with unresolved header files.
2. Click on the lightbulb for an unresolved header and select the "Add include path to settings"
3. The c_cpp_properties.json file opens, but no intellisense is available. After I save once, intellisense begins to work.

**Comment by aeschli** [comment]
Works for me in the latest
![image](https://cloud.githubusercontent.com/assets/6461412/16990467/6558233c-4e98-11e6-9cfd-1f572a6ccc24.png)

Can you still see this?

**Comment by jgoshi** [comment]
Works for me after I save the file. But on the first attempt (when you click on the lightbulb and it brings up the json file) before you save it, there is no intellisense. I'm still seeing this on version 1.3.1.

**Comment by aeschli** [comment]
Can you try on the insiders build? https://code.visualstudio.com/insiders
I just tried again and I see hovers and code completions as shown on the screenshot.

**Comment by jgoshi** [comment]
This still doesn't work for me on insiders. It only starts working after my initial save.

**Comment by aeschli** [comment]
What about the hovers? Do you have any special settings?

**Comment by jgoshi** [comment]
Hovers do no work. And I didn’t change any settings.
