### ISSUE TITLE
Workspace shell permissions are not remembered in multi-root workspaces

### ISSUE THREAD

**Issue by LAK132** [microsoft/vscode#80674]
My workflow requires the use of cygwin in particular workspaces, so I have my *workspace settings* set up to default to cygwin for the integrated terminal. The "Do you allow this workspace to modify your terminal shell?" comes up *every single time* I open this workspace, which is absolutely painful (requires using the mouse) when I *always* allow it. 

![image](https://user-images.githubusercontent.com/1386467/64657849-593d5f80-d474-11e9-9afe-7b25605e6b42.png)

This wouldn't be such an issue if it just showed up the first time I opened vscode, but it also shows up every time I duplicate the workspace as well (which I do regularly).

![image](https://user-images.githubusercontent.com/1386467/64657956-cd780300-d474-11e9-9783-9e929e2f13a4.png)

Is it possible to get an option to "Remember for this workspace", or at least to not ask every time I duplicate a workspace if I had already allowed/disallowed?

**Comment by w9jds** [comment]
I'd be interested in grabbing this issue. Any specific place I should start looking?

**Comment by Tyriar** [comment]
Currently it's stored against the workspace:

https://github.com/microsoft/vscode/blob/afa911d942f60aff56a65be989eb8c74d9cc56a5/src/vs/workbench/contrib/terminal/browser/terminalConfigHelper.ts#L181-L188

Should probably be storing the folder against the user scope.

**Comment by w9jds** [comment]
So the storage scope only allows `GLOBAL` and `WORKSPACE`. Wouldn't we want to modify the duplicate action to properly duplicate the storage too, as it only copies settings currently:
https://github.com/microsoft/vscode/blob/afa911d942f60aff56a65be989eb8c74d9cc56a5/src/vs/workbench/electron-browser/actions/workspaceActions.ts#L44

**Comment by Tyriar** [comment]
Yeah global is what we actually want. Not sure what you mean with the duplicate action, my thinking was changing the key to something that would be unique for a folder like `${IS_WORKSPACE_SHELL_ALLOWED_STORAGE_KEY}_${folderUri.toString()}`

**Comment by w9jds** [comment]
If we make it global and locked to a specific folder wouldn't that just make it permanent for that folder regardless of what workspace the user is in? 

So the original issue was that this happens when duplicating workspaces. Since the notification comes up when duplicating a workspace, and the action doesn't actually duplicate that workspace's storage too, shouldn't we just copy the storage for this value when the workspace is duplicated?

**Comment by Tyriar** [comment]
@w9jds but the problem is a little more general than that, duplicating the workspace is one way to get into this state, creating a new window and adding the folder as a workspace folder would also trigger this. The shell "workspace" permissions was added to ensure users trusted that particular _folder_ to modify those settings, I would argue that the fact that the particular folder is in a different workspace doesn't matter, the user has already trusted the folder.

**Comment by Tyriar** [comment]
The naming kind of sucks with this thinking, "Manager Folder Shell Permissions" would be more correct if we go with this model.

**Comment by w9jds** [comment]
I can see that, I'll go ahead and see if I can get this working properly then based on folder instead of workspace.

**Comment by emilyoon** [comment]
@w9jds are you still working on this? If not, @jhuree and I would like to take on this issue. Let us know if you have made any progress on this!

**Comment by w9jds** [comment]
@emilyoon sorry I got distracted, I didn't find a good way to reliably get the folder URI, so if you would like to grab this and finish it. Go for it!

**Comment by jhuree** [comment]
@w9jds Sounds good, thanks for the quick reply. We'll work on this!

**Comment by Vane11ope** [comment]
If the issue still exists (and probably it still does by checking the code) and no one is working on it, could I give it a shot?

**Comment by krokyk** [comment]
Maybe it's already covered/connected with #88406 ?

**Comment by Aetherbase** [comment]
@Vane11ope Are you working on it currently?

**Comment by jgugu** [comment]
I'm going to take a shot at this for Grace Hopper's Open Source Day!

**Comment by jgugu** [comment]
@isidorn Could you provide a code pointer to an existing function / maybe a code example of getting the folderUri? (referencing this comment https://github.com/microsoft/vscode/issues/80674#issuecomment-540845624) Thanks!

**Comment by isidorn** [comment]
@jgugu Daniel already provided quite a nice code pointer in his comment above
https://github.com/microsoft/vscode/issues/80674#issuecomment-540672806
I think that is a good starting point

**Comment by isidorn** [comment]
Best would be to use the WorskapceContextService for getting the Uri of the folders
Code pointer
https://github.com/microsoft/vscode/blob/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4/src/vs/platform/workspace/common/workspace.ts#L16

We get services via dependency injection - the @ notation
Example https://github.com/microsoft/vscode/blob/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4/src/vs/workbench/contrib/terminal/browser/terminalConfigHelper.ts#L49

**Comment by Tyriar** [comment]
We've removed workspace shell permissions in main due to the upcoming workspace trust feature. This is no longer needed

**Comment by nunoperalta** [comment]
> We've removed workspace shell permissions in main due to the upcoming workspace trust feature. This is no longer needed

@Tyriar - In the comment in https://github.com/microsoft/vscode/issues/103415#issuecomment-668130384 , you suggested this "workspace shell permissions" as a fix for the `terminal.integrated.env.windows` not working.

I have:

```
		"terminal.integrated.env.windows": {
			"COMPOSE_DOCKER_CLI_BUILD": "0",
			"DOCKER_BUILDKIT": "0"
		},
```

And the terminal (PowerShell) isn't getting those envs:

```
PS > echo $env:DOCKER_BUILDKIT
PS > echo $env:COMPOSE_INTERACTIVE_NO_CLI
PS > [Environment]::GetEnvironmentVariable("COMPOSE_INTERACTIVE_NO_CLI")
PS > [Environment]::GetEnvironmentVariable("DOCKER_BUILDKIT")  
```

If the workaround no longer exists, what can I do?

Thank you.

**Comment by Tyriar** [comment]
In the current insiders this is now driven by the new trusted workspaces feature.
