### ISSUE TITLE
智能提示出错

### ISSUE THREAD

**Issue by ChamHuang** [microsoft/vscode#80676]
Issue Type: <b>Performance Issue</b>

智能提示总是显示正在加载中，加载不出来

Googl translate: 
Smart prompts always show that they are loading, not loading

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   120	 19144	code main
    2	    67	  7708	   shared-process
    0	   220	  7812	   window (createWord.vue - 无标题 (工作区) - Visual Studio Code [管理员])
    0	    45	  7460	     watcherService
    0	    41	 17320	     searchService
    0	   196	 20552	     extensionHost
    0	    52	  6968	       electron_node eslintServer.js 
    0	   143	 21428	       electron_node vueServerMain.js 
    0	    67	 10560	   window (问题报告程序)
    0	   139	 14080	   gpu-process
    0	    13	 15824	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (createWord.vue - 无标题 (工作区) - Visual Studio Code [管理员])
|    Folder (FrontEnd): 1170 files
|      File types: svn-base(501) vue(100) js(87) svg(64) gif(21) scss(9)
|                  css(8) xml(7) woff(5) ttf(4)
|      Conf files: package.json(1)
|    Folder (testFontEnd): 429 files
|      File types: vue(100) js(87) svg(64) gif(21) scss(9) css(8) woff(5)
|                  png(4) ttf(4) md(3)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
px2rem|art|0.0.3
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.3
react-native-react-redux|EQu|2.0.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vue-snippets|hol|0.1.11
vscode-react-typescript|inf|1.3.1
path-autocomplete|ion|1.13.3
formate|Mik|1.1.3
easy-less|mrc|1.4.5
vscode-language-pack-zh-hans|MS-|1.38.3
vetur|oct|0.22.2
open-in-browser|tec|2.0.0
react-redux-es6-snippets|tim|2.1.0
vscode-icons|vsc|9.3.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0

</details>

**Comment by aeschli** [comment]
Please add a code sample and reproducble steps, if possible add some screenshots.
