### ISSUE TITLE
node_module folders don't update

### ISSUE THREAD

**Issue by liushuaimaya** [microsoft/vscode#80675]
Issue Type: <b>Bug</b>

folder/file don't update in the file tree when add new file in mac finder,(so does npm install module files).

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
vscode-eslint|dba|1.9.1
prettier-vscode|esb|2.2.2
docthis|joe|0.7.1
HTMLHint|mka|0.6.0
python|ms-|2019.9.34911
debugger-for-chrome|msj|4.11.7
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The node_module folder is ignored from file watching. See the setting `files.watcherExclude` for other folders that are ignored by default.

I tested that the a file 'foo.txt' shows up when added in the mac finder.

Please add more detailed information. File name, file location....
