### ISSUE TITLE
Git 'rename' tree decoration is missing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80671]
- Open a folder tracked in git
- Rename a file
- Stage the delete/untracked file
- Missing `R`

![image](https://user-images.githubusercontent.com/323878/64655125-23e73200-d3e0-11e9-88cd-bf23430e331b.png)

**Comment by joaomoreno** [comment]
cc @jrieken just in case there has been some changes here.

**Comment by jrieken** [comment]
should be defined here: https://github.com/microsoft/vscode/blob/f6df256c60892c0b31f70a5a872c5d9a1559d126/extensions/git/src/repository.ts#L174-L175

**Comment by joaomoreno** [comment]
Not sure how this was working before and what broke it, but I've fixed it. :man_shrugging:
