### ISSUE TITLE
Icon for new built-in "Image Preview" Extension

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80677]
As part of our custom editor work (#77131), I've moved our image preview into a built-in extension. This extension needs a simple icon

**Comment by misolori** [comment]
Would our generic "preview" icon work here?
<img width="242" alt="image" src="https://user-images.githubusercontent.com/35271042/64990427-a78f9b80-d884-11e9-9836-d8d55c08cd3e.png">

Or do you think one with a picture inside would be better suited?
<img width="211" alt="image" src="https://user-images.githubusercontent.com/35271042/64990673-1cfb6c00-d885-11e9-98cb-28d7a33b0d6f.png">

**Comment by mjbvz** [comment]
Either works for me. It's going to be pretty hidden in the UI so it doesn't need to be anything fancy

**Comment by misolori** [comment]
In that case let's go with the generic one, you can re-use the icons from the Markdown extension:

https://github.com/microsoft/vscode/blob/master/extensions/markdown-language-features/media/preview-dark.svg

https://github.com/microsoft/vscode/blob/master/extensions/markdown-language-features/media/preview-light.svg

**Comment by bpasero** [comment]
Fyi there is a few more built in extensions without icon:

![image](https://user-images.githubusercontent.com/900690/65964559-84a4e000-e45d-11e9-93ef-f22ad934974e.png)

![image](https://user-images.githubusercontent.com/900690/65964567-88d0fd80-e45d-11e9-9617-44ac71c9221b.png)

**Comment by misolori** [comment]
@bpasero created #81760 to track that
