### ISSUE TITLE
Is there any other way to get “files.associations” in VS Code?

### ISSUE THREAD

**Issue by antonioOrtiz** [microsoft/vscode#80670]
- VSCode Version: Version 1.33.1 (1.33.1)
- OS Version: macOS Mojave

Steps to Reproduce:

1. Have `"files.associations" { 
   "*.js": "javascriptreact",
  },`  set in `settings.json`
2. Enable  the [ExpressJS 4 snippets](https://github.com/gurayyarar/expressjs4-snippets), [ExpressJS](https://github.com/amandeepmittal/expressjs-vscode), [Node-snippets](https://github.com/softchris/node-snippets) extensions.

Does this issue occur when all extensions are disabled?: 

No, because it appears that's the problem; When this is set...

```
"files.associations": { // breaks node, express auto complete
   "*.js": "javascriptreact",
  },

```

in `settings.json` it breaks these extensions:
[ExpressJS 4 snippets](https://github.com/gurayyarar/expressjs4-snippets), [ExpressJS](https://github.com/amandeepmittal/expressjs-vscode), [Node-snippets](https://github.com/softchris/node-snippets)

**Comment by jrieken** [comment]
What is the issue/wish/question here?

**Comment by jrieken** [comment]
Only the extension author can make that call, e.g. extensions target 'javascript' not another language and you basically made the language disappear by that. I think the behaviour is fair and while javascript vs javascriptreact is borderline similar they are different languages and not all tools that understand javascript can understand javascriptreact.
