### ISSUE TITLE
Let me cancel a Find in Files operation

### ISSUE THREAD

**Issue by eedwards-sk** [microsoft/vscode#80672]
Node Projects with a `node_modules` directory are often so massively huge with files and folders that if you accidentally do a "Find in Files" search that includes it, the entire application hangs while it overloads itself doing a massive search.

I would like to be able to press the escape key or similar to immediately cancel a search-in-progress. There needs to be some kind of UI responsiveness during a search to allow it to be cancelled.

Currently, I have to force-quit the application, or wait 10+ minutes for the search to complete.

**Comment by gjsjohnmurray** [comment]
Does this button not work for you?

![image](https://user-images.githubusercontent.com/6726799/64657509-b660f300-d42b-11e9-8bff-52aeef94f168.png)

**Comment by eedwards-sk** [comment]
That button does not appear during a search on my version of vscode.

```
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by roblourens** [comment]
It should appear after a few seconds. The escape key also works.

> the entire application hangs while it overloads itself doing a massive search.

If the program is actually unresponsive then it probably won't show up. Is that what you see?

**Comment by eedwards-sk** [comment]
You're correct it took a couple seconds to appear.

<img width="570" alt="Screen Shot 2019-09-18 at 2 12 51 PM" src="https://user-images.githubusercontent.com/34585329/65178559-a1352700-da1e-11e9-8c23-1f1ad7d5dc48.png">

Unfortunately, escape nor clicking it still does not work, as per my original issue -- the UI is not responsive.

**Comment by eedwards-sk** [comment]
actually I can confirm it doesn't always show up

after closing the entire application (the only way to get it to close once hung), I re-opened it and performed a new search, and it hung even before the cancel button appeared

when it hangs, the search progress bar stops moving, as well

<img width="470" alt="Screen Shot 2019-09-18 at 2 17 23 PM" src="https://user-images.githubusercontent.com/34585329/65178801-2caeb800-da1f-11e9-81d7-0dce7dbf5529.png">

**Comment by roblourens** [comment]
Most likely, your search is returning a result in an extremely long line and hanging when we try to send the results back. If it ever resumes after hanging, I wonder if you can get a profile of the renderer process during the hang? You could do this by opening the developer tools (Help > Toggle developer tools), open the Performance tab: 
![image](https://user-images.githubusercontent.com/323878/65289728-c0a48080-db00-11e9-9cf0-4fbae52cd33a.png)
Start recording, start the search, then stop recording after it is not hanging any more.

It would probably just show that we spend a lot of time sending a large IPC message but it might show something else interesting.
