### ISSUE TITLE
[json] hover in JSON documents hides '*'

### ISSUE THREAD

**Issue by jgoshi** [Microsoft/vscode#8068]
- VSCode Version: 1.2.1
- VSCode C++ extension Version: 0.7.0
- OS Version: Windows 10 Enterprise

NOTE: You need the C++ extension version 0.7.0 or later because we introduced the c_cpp_properties.json schema file.

Steps to Reproduce:

1. Open any folder containing a .cpp file with unresolved header files.
2. Click on the lightbulb for an unresolved header and select the "Add include path to settings"
3.The c_cpp_properties.json file opens. Save once so intellisense works (see issue 8067 for more details).
4. Hovering to see a description over "includePath" the '*' character is not visible. But if you start typing "includePath" the intellisense shows the '*' character. See the two attached screenshots for more info.
![image1](https://cloud.githubusercontent.com/assets/19478941/16315443/06268208-391e-11e6-88b8-f7eb12e4b956.png)
![image2](https://cloud.githubusercontent.com/assets/19478941/16315442/0623315c-391e-11e6-88b8-7a27fb880d55.png)

**Comment by jgoshi** [comment]
![image1](https://cloud.githubusercontent.com/assets/19478941/17008220/04271472-4e8b-11e6-82b6-685ecfc19c43.png)
I still see this issue with version 1.3.1 (see attached image for details on the version).

**Comment by aeschli** [comment]
You need the latest insider build (1.4.0-insider): https://code.visualstudio.com/insiders

**Comment by jgoshi** [comment]
This works on the latest insider build. These are the daily builds so it will appear in the next official vscode release as well?
