### ISSUE TITLE
The api workspace.applyEdit failed for some case of mixing resourceChange and textEdit

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#80688]
Below is my reproducing script.
- Create an empty `file1` and `file2` in your workspace root, and open it in VS Code.
- Run `extension.helloWorld`, it failed with errors. The second insert failed.
But if commenting the operation to rename file2, it succeeds. It looks like adding a different resource change between two inserts, applying the second insert will fail. 

```typescript
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
	let disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		let files = await vscode.workspace.findFiles("file*");
		if (!files || files.length < 2) {
			vscode.window.showErrorMessage("Cannot find the test files.");
			return;
		}

		const file1 = files[0];
		const file2 = files[1];
		let we = new vscode.WorkspaceEdit();
		we.insert(file1, new vscode.Position(0, 0), "import1;");

		const file2Name = path.basename(file2.fsPath);
		const file2NewUri = vscode.Uri.parse(file2.toString().replace(file2Name, `new/${file2Name}`));
		we.renameFile(file2, file2NewUri);

		we.insert(file1, new vscode.Position(0, 0), "import2;");
		await vscode.workspace.applyEdit(we);

		const document = await vscode.workspace.openTextDocument(file1);
		const expected = "import1;import2;";
		if (document.getText() !== expected) {
			vscode.window.showErrorMessage(`Failed. Expected: '${expected}', Actual: '${document.getText()}'`);
		}
	});

	context.subscriptions.push(disposable);
}
```

**Comment by jrieken** [comment]
> it failed with errors. The second insert failed.

Not sure what you mean with that. I have added a unit test with you sample and it passed. Tho, it passes after fixing the expected value: `import1;import2;` should be `import2;import1;` because the edit is setup like this: (1) at offset 0 insert "import1;" and then (2) at offset 0 insert "import2;". That makes "import2;import1;". 

Is there anything else? What's changing, failing, not failing when skipping the rename?

**Comment by testforstephen** [comment]
- When i executed the script above, what i observed is `import1;` and `rename file2` was applied, but `import2;` was not applied. (My VS Code is 1.38.0)
- When i executed the following operation, the file1 becomes `import1;import2;`, not `import2;import1;`
```typescript
    let we = new vscode.WorkspaceEdit();
    we.insert(file1, new vscode.Position(0, 0), "import1;");
    we.insert(file1, new vscode.Position(0, 0), "import2;");
    await vscode.workspace.applyEdit(we);
```

Besides, here is the api documentation. It looks like `import1;import2;` should be the expected result.
> If multiple textual inserts are made at the same position, these strings appear in the resulting text in the order the 'inserts' were made.

**Comment by jrieken** [comment]
Thanks, I can now reproduce. What happening is that we process all changes in order but we group sequenced of text edits and file create/rename/delete edits. So, in the first case we have `[[text], [file], [text]]` and the second there is `[[text,text]`. The latter seems to applied different to what's expected.

**Comment by jrieken** [comment]
This "fix" here is to update the docs. Already today, it says that changes are applied in the order that have been provided and what isn't clear is that the multiple text edits at the same position aren't grouped together.
