### ISSUE TITLE
Sort in 'OPEN EDITORS' on left sidebar

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/vscode#80681]
Section 'OPEN EDITORS' on left sidebar can't sort by name. I feel difficult find opened file

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/27286

**Comment by SimplyInk** [comment]
When I have no folder opened in VS Code, if I drag a number of files into VS Code, OPEN EDITORS does not sort alphabetically.

![image](https://user-images.githubusercontent.com/12554237/66457164-484b3280-eaa2-11e9-8577-5dc103ee1d83.png)

But if I open a folder with the files, OPEN EDITORS gets sorted alphabetically.

![image](https://user-images.githubusercontent.com/12554237/66457792-ba704700-eaa3-11e9-86e0-a7c68e9dd9a1.png)
