### ISSUE TITLE
auto script on startup for vscode

### ISSUE THREAD

**Issue by dtvn** [microsoft/vscode#80686]
I have a hugo theme repo. Every times I start vscode, I have to copy the theme repo to a tester dir and run `hugo server` to test. It was ok for a first few times, but now I kinda sick of it. I wish I can write a script tell vscode that every time I open a project, vscode will do what I expect it do.

So I'm looking for an auto script on startup. This `auto.script` should be kept under `.vscode` dir in order to commit. It will be similar with some auto build script like gulp but much simpler because I only expect it could open terminal and executes some pre build script of mine.

**Comment by aeschli** [comment]
You could write an extension that does that. It needs to activate on '*' and then look for the init task.
