### ISSUE TITLE
Markdown refresh preview command resets scroll position

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80680]
Issue Type: <b>Bug</b>

**repo**
1. Open a long markdown preview
1. Scroll down part way on the page
1. Be focused on preview
1. Run the `markdown refresh preview` command

**Bug**
Scroll position is reset to top

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:23:19.252Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.73GB free)|
|Process Argv|-psn_0_1016056|
|Screen Reader|no|
|VM|20%|
</details>

**Comment by gjsjohnmurray** [comment]
See also #63690

**Comment by Tyriar** [comment]
Still happens.

Version: 1.39.0-insider
Commit: a655c0836de8b8e06f4d56fa4e581b0ced53f56f
Date: 2019-10-03T05:32:23.012Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
@Tyriar I tried with both side by side and single preview and I can't repo. Can you share your steps

**Comment by Tyriar** [comment]
@mjbvz steps are exactly as stated above, happens in both full preview and on side.

![Kapture 2019-10-03 at 11 41 41](https://user-images.githubusercontent.com/2193314/66154633-cd31da00-e5d2-11e9-82d9-0013421f9ebf.gif)

Command in gif is:

<img width="232" alt="Screen Shot 2019-10-03 at 11 42 06 AM" src="https://user-images.githubusercontent.com/2193314/66154672-dcb12300-e5d2-11e9-8c53-2b964d095bd8.png">

**Comment by mjbvz** [comment]
Do you have one of the scroll sync settings turned off? It looks like the text file is not scrolled along with the preview

**Comment by mjbvz** [comment]
Yes `markdown.preview.scrollEditorWithPreview: false` is what causes this
