### ISSUE TITLE
experimentalDecorators Typescript warning always present

### ISSUE THREAD

**Issue by giacomorebonato** [Microsoft/vscode#8069]
- VSCode Version: 1.3.0-insider
- OS Version: El Capitan

Steps to Reproduce:

1. Create a Typescript project
2. Use decorators (I am using [Mobx](https://mobxjs.github.io/mobx/best/syntax.html))  

I keep seeing the warning:  
```
[ts] Experimental suport for decorators is a feature that is subject to chang in a future release. Set the 'experimentalDecoratos' option to remove this warning.
``` 
Where should I set this option? Because my tsconfig.json should be right  
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": false,
    "isolatedModules": false,
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noLib": false,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "./dist/"
  },
  "exclude": [
    "client",
    "node_modules",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}
```

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9335

**Comment by Martin-Wegner** [comment]
I still have the same problem with this tsconfig.json:
https://raw.githubusercontent.com/AngularClass/angular2-webpack-starter/master/tsconfig.json

**Comment by giacomorebonato** [comment]
Try to remove the path property in the tsconfig

**Comment by Martin-Wegner** [comment]
I tried everything (e.g. removed the path property) but nothing helped. The only config that worked is the previous one: https://raw.githubusercontent.com/AngularClass/angular2-webpack-starter/888795d1c20c157d023ee2b9dcc503be11913019/tsconfig.json

**Comment by Martin-Wegner** [comment]
https://github.com/AngularClass/angular2-webpack-starter/issues/781#issuecomment-232788165

**Comment by dbaeumer** [comment]
@Martin-Wegner please make sure your comments are raised here https://github.com/Microsoft/TypeScript/issues/9335 as well since VS Code itself can't fix this.

**Comment by Ihatetomatoes** [comment]
I had a similar issue and this fixed it for me:

[How to remove experimentalDecorators warning in VSCode](https://ihatetomatoes.net/how-to-remove-experimentaldecorators-warning-in-vscode/)

**Comment by 7elven** [comment]
@Ihatetomatoes my vscode fixed

**Comment by cdibbs** [comment]
Removing the `files` property within `tsconfig.json` seemed to fix it for me after @Ihatetomatoes post didn't, but I was less than scientific about it.

In case it helps anyone else, prior to removing the `files` property, I had also removed an old, auto-generated `.vscode/tasks.json` after noticing other projects didn't have that file, and I updated my global typescript to 2.1.5, and set my workspace to use that.

**Comment by Hosar** [comment]
@Ihatetomatoes  solution works for me.

**Comment by anhtuank7c** [comment]
@Ihatetomatoes Thank you.
It's work.

**Comment by nubunto** [comment]
@Ihatetomatoes works for me, but I had to restart it
thanks!

**Comment by ConAntonakos** [comment]
@Ihatetomatoes Worked for me as well. Is there a way to add this to VS Code's settings rather than needing to generate a `tsconfig.json` file per project?

**Comment by Ihatetomatoes** [comment]
@ConAntonakos, I don't think it can be included in the `.vscode` settings.

**Comment by alekspetrov** [comment]
+1

**Comment by jgillich** [comment]
@dbaeumer This issue also applies to pure JS projects, I think it should be reopened. Adding a `tsconfig.json` just to get rid of the error cannot be the proper solution.

**Comment by dbaeumer** [comment]
@mjbvz can you please follow up.

**Comment by mjbvz** [comment]
If you have a `tsconfig.json` or `jsconfig.json` and are still seeing a warning about `experimentalDecorators` not being supported, most likely you working with files outside of the project. That explains why removing the `files` config option fixes the problem.

To check if this is indeed the case, open the file with the warning and run the `Go to Project Configuration` command. This will jump to the `jsconfig` or `tsconfig` that the file belongs to, or alert you if the file is not part of any project

We are also tracking a feature request that would allow enabling experimentalDecorators using a vscode setting: #14985

**Comment by harmon25** [comment]
Was having the issue in a JS project.
The following VS Code workspace `settings.js` resolved it - would work for both [ts] and [js] projects
```json
{
    "typescript.validate.enable": false,
    "javascript.validate.enable": false
}
```

**Comment by SuEric** [comment]
@mjbvz Just adding: Remember to do Reload Window command. Worked for me, thanks!

**Comment by Gatix** [comment]
@harmon25's solution worked.

I'm validating my code with eslint anyway so I guess disabling this should be fine.

**Comment by daniel-filipe-lobo** [comment]
In my case the Build Action for the tsconfig.json was "None", once I've changed it to "Content" it worked.

![image](https://user-images.githubusercontent.com/5391648/27876989-f3376010-61b0-11e7-9414-dab62d8a779d.png)

**Comment by kobenauf** [comment]
Adding this comment in case it helps anyone.  I was having this same problem, and the steps above didn't help.  My problem is I had assumed tsconfig.json should go in .vscode, but it should actually go in the project root folder.  Once I moved it there it the decorator warning went away without even restarting the IDE.
