### ISSUE TITLE
Cmd+F changes selection text in find/replace dialog but not in global search text field

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#80693]
Hi @roblourens , Not sure if this is an issue or this should work like how it is currently working but this is what I found.

Highlighting a text and pressing cmd+f will open the find/replace dialog with that text auto populated , Highlighting a new text and pressing cmd+f will replace the find/replace dialog text and does a new search. ( This is great )

Similarly when you have highlighted a text ( either you have pressed cmd + f to open find/replace dialog or not ) and then go ahead and open the global search , The text is auto populated to what was highlighted or what is currently in the find/replace dialog.
But now if I **change the selection** and highlight a new text and press cmd+f , the find/replace dialog text changes but the text inside **global search field is still the same and does not update**,
Maybe there is no need to trigger a global search when this happens but the search field value can be at least updated to reflect the same in find/replace dialog.

Added a small clip for better understanding :) 
https://drive.google.com/open?id=1n5C14Xbiolx-tEMF1ztooMJX8oSS4xB7

**Comment by roblourens** [comment]
Yeah this is correct. If you press cmd+shift+f, then it will update in the search box.
