### ISSUE TITLE
Update of VS Code started from VS Code fails

### ISSUE THREAD

**Issue by StefanPavlik** [microsoft/vscode#80690]
Issue Type: <b>Bug</b>

Prerequisities: 
VS Code installed per machine (not per user).
VS Code runnig as normal user (non elevated admin).

Steps to reproduce:
VS Code shows popup that new update is available.
After clicking on 'Update Now' the update starts but it fails because the installer is started with same privileges as VS Code (not elevated admin).
Following error is displayed to user:
![VS_update_not_elevated_admin](https://user-images.githubusercontent.com/54433467/64673230-de714600-d46d-11e9-8d63-f257aad5c438.png)

Solution:
The installer can be started using ShellExecute API with lpOperation parameter set to 'runas'. This way the elevation prompt of installer gets displayed.

Workaround:
Start VS Code 'as administrator'. Update started from elevated application will succeed.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.94GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|8.0.2
pascal-formatter|ale|2.2.0
vscode-jasmine-test-adapter|hbe|1.6.1
vscode-test-explorer|hbe|2.14.5
innosetup|idl|1.2.0
python|ms-|2019.9.34911
vscode-formatall|rat|0.0.2

</details>

**Comment by joaomoreno** [comment]
> VS Code installed per machine (not per user).

Please use the [System Installer](https://code.visualstudio.com/docs/?dv=win64) if you wan to install VS Code per machine, not the User installer (as it's indicated in the screenshot).

**Comment by StefanPavlik** [comment]
Thanks for explaining, but...
My problem is caused (most likely) by some old (user) version of VS Code which was installed to 'Program Files'. It means that that it is not able to update itself.

BTW: What is the reason for two installers (user and system)?
