### ISSUE TITLE
[json] large file with no extension causes "extension host terminated unexpectedly" 

### ISSUE THREAD

**Issue by luciferz2012** [microsoft/vscode#80691]
Issue Type: <b>Bug</b>

if i open a 10MB json file with no extension, the extension host costs more than 2GB memory and then terminated.

if i rename the file as txt, no crash happens.

[test.zip](https://github.com/microsoft/vscode/files/3599334/test.zip)

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:25:22.729Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (8.49GB free)|
|Process Argv|C:\Users\Z\.cODES\bim-optimizer\core-optimizer|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode/commit/223076ac5437993de001efe884f8060c88b20095

**Comment by aeschli** [comment]
To verify:
- verify that huge JSON documents don't crash
- you get a notification that some provider result are limited in size (color infos, color symbols, folding)
