### ISSUE TITLE
Crash on windows 7

### ISSUE THREAD

**Issue by perfectdeveloper53** [microsoft/vscode#80699]
Issue Type: <b>Bug</b>

Hi. 
After I close VS code or when I try to update VS code, it shows alert and crash down.
Currently I am using windows 7.
With these problems, I can not update VS code properly.

Please resolve it to help me. Thanks

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please disable your extensions and try again. If it still crashes, post a screenshot here. It's usually possible to paste one into the GitHub textfield direct from your clipboard.
