### ISSUE TITLE
Avoid semver dependency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80698]
Today we depend on `semver` (and `semver-umd` for web). 

I suggest to connect with @alexandrudima who already wrote a parser and try to use that one for our requirements, which only seems to be to find out if a version is greater or not.

Refs: https://github.com/microsoft/vscode/blob/dd7daae7de1d229280400ab9ddc20973fb3178bb/src/vs/platform/extensions/common/extensionValidator.ts#L37

**Comment by sandy081** [comment]
@bpasero I see `marked.js` has `cgmanifest.json` and `marker.license.txt`, may I know shall I have to follow the same format? And is there any other place where I need to register `semver` thingy so that its license is read by our OSS tool?

**Comment by bpasero** [comment]
My understanding is that this is sufficient. Copying what `marked.js` does seems legit to me for the semver needs.

**Comment by alexdima** [comment]
@sandy081 Please see https://github.com/microsoft/vscode-build-tools/tree/master/distro-tools#types-of-3rd-party-oss-dependencies Please LMK if that documentation is complete or needs more info.

**Comment by sandy081** [comment]
Inlined `semver`.

@alexdima Above doc makes sense. Just one confirmation - Added [cgmanifest.json](https://github.com/microsoft/vscode/blob/88144f6/src/vs/base/common/semver/cgmanifest.json). I am assuming the `vscode-build-tools` scans the files and picks this automatically or shall I have to register it anywhere ?

**Comment by alexdima** [comment]
@sandy081 :+1: The file will be picked up because of its name. There is no need to inline the license. It looks like the repo has a top level LICENSE file ("licenseDetail") and that should work automatically.

**Comment by sandy081** [comment]
Thanks. Removed `semver.license.txt` and deleted `licenseDetail` from `cgmanifest.json`.
