### ISSUE TITLE
Cmd+\ (backslash) not registered on macOS

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#80697]
This is probably the same issue as #66434 which has been auto-closed due to lack of information so I'm opening this fresh one. cc @synthecypher @sandy081

In my case, I'm trying to invoke the **Go to Bracket** command which is `Cmd+Shift+\`:

![Screenshot 2019-09-11 at 10 37 08](https://user-images.githubusercontent.com/101152/64681507-239e7380-d480-11e9-9b26-56e8f616eedb.png)

When I press just `Shift+\`, that is registered fine by VSCode:

![Screenshot 2019-09-11 at 10 31 13](https://user-images.githubusercontent.com/101152/64681572-3e70e800-d480-11e9-80f7-badfdfaf6d00.png)

However, when I try `Cmd+\`, that doesn't work:

![Screenshot 2019-09-11 at 10 28 15](https://user-images.githubusercontent.com/101152/64681598-4e88c780-d480-11e9-9502-a8f38316067c.png)

This is what the OS keyboard viewer sees at that point:

![Screenshot 2019-09-11 at 10 50 17](https://user-images.githubusercontent.com/101152/64682635-171b1a80-d482-11e9-915d-f32577883e54.png)

I see this in both VSCode stable (1.38.0) and Insiders (1.39.0-insider).

**Comment by alexandrudima** [comment]
@borekb 
What keyboard layout do you have configured? 
What physical keyboard do you use? (ISO or ANSI)?
![image](https://user-images.githubusercontent.com/5047891/64849251-46ad5c80-d613-11e9-892c-239ae5a0a127.png)

**Comment by borekb** [comment]
@alexandrudima ISO. The screenshot from the OP is a realistic view on how my keyboard looks like:

> This is what the OS keyboard viewer sees at that point:
>
> ![Screenshot 2019-09-11 at 10 50 17](https://user-images.githubusercontent.com/101152/64682635-171b1a80-d482-11e9-915d-f32577883e54.png)

**Comment by borekb** [comment]
Oh, I see the problem now. This "U.S. - PC" is my modified keyboard layout via [Ukelele](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ukelele) because I wanted to move backtick and backslash to their "normal" locations in the PC world:

<img width="647" alt="Screenshot 2019-09-13 at 11 02 50" src="https://user-images.githubusercontent.com/101152/64850640-0dc2b700-d616-11e9-9793-0d53bed06dc8.png">

<img width="647" alt="Screenshot 2019-09-13 at 11 01 46" src="https://user-images.githubusercontent.com/101152/64850574-ecfa6180-d615-11e9-8452-260ab6906e48.png">

As a result, I now have two backslashes on my "U.S. - PC" keyboard which might be related.

When I use the `\` key right **next to Enter** on the right, it works:

![Screenshot 2019-09-13 at 11 08 25](https://user-images.githubusercontent.com/101152/64851053-ee785980-d616-11e9-9b66-abc8bcf0ae76.png)

I didn't even realize that there's this duplicate backslash there, will try other apps that use `\` for shortcuts if they work correctly...

**Comment by borekb** [comment]
Ok, so tried in Google Sheets where `Cmd+\` should clear formatting.

- My `\` next to Enter works. ✅ 
- My `\` next to left Shift doesn't work. 🚫 

So it's an issue with my keyboard, not with VSCode, sorry for the report.

**Comment by alexandrudima** [comment]
:+1: Thank you for following up
