### ISSUE TITLE
VS Code crashing on restart after opening large file once with —max-memory=12288

### ISSUE THREAD

**Issue by DanGardnerr** [microsoft/vscode#80701]
- VSCode Version: 1.38
- OS Version: Win 10 (1809) 17763.678

Steps to Reproduce:

1. Open a large file 10GB (original opened using `--max-memory=12288mb`). Observe that VS Code works fine handling the large file
2. Close VS code (note VS code options were previously set to hot close and restore on close)
3. Opening any VS Code window, either normally or through the context menu will cause the old large file to be loaded on open
4. At this point vs code will crash on opening within ~10 seconds. It will be functional within these 10 seconds but manual trying to close the window, file or editor will not have any effect. (Unfortunately I didn't take a screenshot of the error window but the dialog options were 'restart' which would reopen and perform perform steps 3. Onward again or just close the application)
5. Attempting to change hot reload setting or restore previous state options during the functioning 10 seconds before crash take no effect on restart

![image](https://user-images.githubusercontent.com/7859942/64691488-a88e8a80-d48a-11e9-969d-8bb3285e3a9f.png)

Does this issue occur when all extensions are disabled?: No

The solution is to start VS Code through the command line with the `--max-memory=12288mb` argument and to manually close the document to prevent attempting to hot reload. 

I'll attach the seetting.json. Note that I've commented the settings that I added as part of step 5, these weren't present originally.

```
{
    "workbench.colorTheme": "Visual Studio Light",
    "editor.renderWhitespace": "all",
    // "window.restoreWindows": "none",
    // "files.hotExit": "off"
}
```

**Comment by aeschli** [comment]
What type of file is it? JSON, HTML...?

**Comment by DanGardnerr** [comment]
> What type of file is it? JSON, HTML...?

It's a `.yalv` log file. To all extents and purposes just a large text file, I don't believe VS Code applies any tokenization or formatting to these types of file.

**Comment by alexandrudima** [comment]
@bpasero @Tyriar 
Maybe we could do a `fs.stat` and detect that a file >1GB is being restored and perhaps we could prompt users if they really want to restore? Or maybe an option to "Restart in safe mode"?

**Comment by bpasero** [comment]
@DanGardnerr just to be clear, you instructed VSCode to do this:

> Open a large file 10GB (original opened using --max-memory=12288mb). Observe that VS Code works fine handling the large file

Or did we do this somehow and lost the CLI argument?

**Comment by DanGardnerr** [comment]
@bpasero I ran the command `code —max-memory=12288` the first time when I was intentionally trying to open the file. After that I was just opening VS Code in my normal way

**Comment by bpasero** [comment]
Ok got it.

**Comment by bpasero** [comment]
Moving to @rebornix as owner of this feature. We originally did not allow to open such large files, I am not sure why no error is raised in this case.

**Comment by rebornix** [comment]
> Or maybe an option to "Restart in safe mode"?

This one is appealing to me. We have see quite a couple of similar issues where either hot exit restore and editor restore stops users from opening vs code.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/70433

Unassigning myself as it seems to be related to renderer OOM, not hot exit.

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/167719
