### ISSUE TITLE
Editor: Word Wrap doesn't work

### ISSUE THREAD

**Issue by zangief2000** [microsoft/vscode#80708]
Issue Type: <b>Bug</b>

Editor: Word Wrap is set to off by default but all files are still word wrapped upon opening. I tried changing it to on then back off, as well as adding "editor.wordWrap": "off" to settings.json, but neither one worked.

How do I fix this? I don't want to keep on pressing Alt+Z every time I open a new file. Thanks.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Are you opening a workspace? Is it possible that `"editor.wordWrap": "on"` is set at the workspace level?

**Comment by zangief2000** [comment]
It is possible. How do I change that on a workspace level?

**Comment by gjsjohnmurray** [comment]
Settings screen has tabs:
![image](https://user-images.githubusercontent.com/6726799/64703654-cc5eca00-d4a4-11e9-98b0-2eeb7560e9b2.png)

The thing that is underlined is the one you're making the settings for.

**Comment by zangief2000** [comment]
Both seem to have "Editor: Word Wrap" set to "off".

**Comment by alexandrudima** [comment]
@zangief2000 
- Does this reproduce when disabling all extensions? 
- Does this reproduce when you comment out your `settings.json`?
- Does this reproduce in any folder or only in certain folders?
- Does this reproduce with a specific file type or with any file types, including `.txt` files?
