### ISSUE TITLE
Light menu bar when selected Breeze Dark in Kubuntu

### ISSUE THREAD

**Issue by vnikolai** [microsoft/vscode#80709]
Issue Type: <b>Bug</b>

While selecting Beeze Dark color scheme in Kubuntu window title bar changes properly from light to dark but menu bar stays light.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:51:09.716Z)
OS version: Linux x64 5.0.0-27-generic

**Comment by deepak1556** [comment]
@vnikolai can you try our exploration builds and see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/a715df3459718a501686bd03414f69929bf6e9a2/VSCodeUserSetup-x64-1.37.0-exploration.exe)
