### ISSUE TITLE
Make snippet selection case sensitive

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#8070]
- VSCode Version: 1.2.1
- OS Version: Wind10

I just added latex snippets to the [julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) extension. These snippets essentially map things like `\eta` onto `η`. This is very hand for scientific code.

One problem is that we will have snippets like `\eta` and `\Eta`, where the lower case will translate to the lower case greek letter and the upper case version to the upper case greek letter. But the snippet filtering right now is not case sensitive: when I enter `\Eta`, it will select `\eta` as the default and show `\Eta` as the second item in the list.

I think the best solution here would be this:
1. if there is a case-sensitive match, select that by default
2. If not, select a case-insensitive match as the default

**Comment by davidanthoff** [comment]
This seems fixed, so I'm closing this issue.

**Comment by joaomoreno** [comment]
Thanks for checking!
