### ISSUE TITLE
[themes] monokai Dimmed theme issue

### ISSUE THREAD

**Issue by ironman96** [microsoft/vscode#80704]
Issue Type: <b>Bug</b>

during inline styling (HTML) the color of the inverted commas are different 
eg. style="float: right;"
attaching screenshot below

![image](https://user-images.githubusercontent.com/52822565/64691901-6af12800-d4b1-11e9-8054-a9cf61adbb72.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6500B APU with Radeon(tm) HD Graphics    (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.20GB (2.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
python|ms-|2019.9.34911
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
jinja|who|0.0.8

</details>

**Comment by aeschli** [comment]
I don't see that in the Default Dark Theme:

![image](https://user-images.githubusercontent.com/6461412/64713025-7bf36680-d4bc-11e9-841a-c4a77df0e3c3.png)

What is your theme?

**Comment by ironman96** [comment]
> I don't see that in the Default Dark Theme:
> 
> ![image](https://user-images.githubusercontent.com/6461412/64713025-7bf36680-d4bc-11e9-841a-c4a77df0e3c3.png)
> 
> What is your theme?

"Monocai Dimmed"

**Comment by keshav-bohr** [comment]
`{
	"name": "String Embedded Source",
	"scope": "string source",
	"settings": {
		"fontStyle": "",
		"foreground": "#D08442"
	}
}`

This code from `extensions/theme-monokai-dimmed/themes/dimmed-monokai-color-theme.json` file is causing this issue. But not able to figure out why is it happening only for style keyword?

Also, did not find any usage of `string source`. We can just replace the foreground colour if that works for further usage?

@aeschli Please let me know
