### ISSUE TITLE
React TSX files with component properties marked with @ts-ignore generate unexpected errors

### ISSUE THREAD

**Issue by lamontadams** [microsoft/vscode#80715]
Issue Type: <b>Bug</b>

Prior to v 1.38, it was possible to mark individual React component property lines with `@ts-ignore` to work around typing issues with 3rd-party components. This seems to be broken in 1.38. See screenshots for current behavior. 

This doesn't appear to be a problem with typescript itself as the source files in question compile correctly, this is just a problem with TSX files loaded into the editor.

Steps to Reproduce:
1. Create a TSX file that imports a React component which exposes multiple typed props values.
2. Add rendering code for the imported component to the TSX file, with one prop value per line
3. Specify an invalid value for one of the props
4. Add `// @ts-ignore` above the invalid value
(See screenshots)

![image](https://user-images.githubusercontent.com/1198083/64703017-9f48f200-d479-11e9-9d9c-453ebf0bfd52.png)

![image](https://user-images.githubusercontent.com/1198083/64703043-ab34b400-d479-11e9-89f0-b9232aebe7cd.png)

Issue occurs with all extensions disabled, persists after file is edited, closed and re-opened, and is new to v1.38. Applying `@ts-ignore` to the entire component works as expected. Applying `@ts-nocheck` to the entire file works as expected. `tsc` itself works as expected with `@ts-ignore` applied to props on individual lines.

Expected behavior:  prop lines marked with `@ts-ignore` should not generate errors.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:51:09.716Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor (16 x 1703)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|31.43GB (13.78GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lamontadams** [comment]
Reverted to 1.37 and the issue went away, so it's definitely new with 1.38.

**Comment by mjbvz** [comment]
Does the TS code compile without any errors? What tsc version are you using for this?

**Comment by lamontadams** [comment]
Yes the code compiles with no errors via tsc. tsc version is 3.5.2

**Comment by mjbvz** [comment]
What about with TS 3.6.2? (which vscode is using by default in the workspace)

**Comment by lamontadams** [comment]
Ah. I can reproduce this with tsc version 3.6.2 so that's something. Still seems incorrect behavior.

Is the tsc version in use internally by vscode communicated anywhere? I don't see it on Help > About which is where all the other version information is listed.

**Comment by mjbvz** [comment]
Yes, see https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions for how to change your workspace TS versions. Instead of downgrading to VS Code 1.37, you should be able to switch your workspace back to using TS 3.5.2 to workaround this issue

Since you also see this error with tsc, please file an issue upstream against TypeScript: https://github.com/microsoft/TypeScript/issues/new/choose
