### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed

### ISSUE THREAD

**Issue by farruqjon** [microsoft/vscode#80716]
issue after upgrading flutter today (09/11/2019). i created new project and copied working example of DefaultTabController. but still issue exists. 
E/flutter ( 5068): #16     main 
package:todo_sqlite/main.dart:5
E/flutter ( 5068): #17     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)
E/flutter ( 5068): #18     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter ( 5068): #19     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter ( 5068): #20     _runZoned  (dart:async/zone.dart:1516:10)
E/flutter ( 5068): #21     runZoned  (dart:async/zone.dart:1500:12)
E/flutter ( 5068): #22     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)
E/flutter ( 5068): #23     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 5068): #24     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 5068):

**Comment by aeschli** [comment]
Can you file it against the Dart/Flutter extension?

**Comment by farruqjon** [comment]
sure)))
