### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hygens** [Microsoft/vscode#8071]
- VSCode Version: 1.2
- OS Version: Linux Mint 17.3(Ubuntu Based 14.04.04)

Steps to Reproduce:
1. Install all plugins for Haskell and haskell-platform 7.6.3-10.
2. Create one simple file. Ex.: 
-- File add.hs
myNot False = True
myNot True = False
sumList (x:xs) = x + sumList xs
sumList [] = 0
3. Configure informations for file in launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ghc",
            "name": "ghci debug viewer Phoityne",
            "request": "launch",
            "internalConsoleOptions": "openOnSessionStart",
            "workspace": "${workspaceRoot}",
            "startup": "${workspaceRoot}/HaskellLearning/src/learning/add.hs",
            "logFile": "${workspaceRoot}/.vscode/phoityne.log",
            "logLevel": "WARNING",
            "ghciPrompt": "H>>= ",
            "ghciCmd": "cabal ghci --test --no-load --no-build"
        }
    ]
}
4. Entry on Debug view and execute.
5. Error: 
phoityne-vscode.exe is not found. Run `stack install phoityne-vscode`, and put it to PATH environment.

Detail I have installed cabal not stack and exists other error that starting vscode says:
Couldn't start ghc-mod process Error: Command failed: ghc-mod version.

**Comment by dbaeumer** [comment]
@Hygens please file the issue against the owner of the Haskell extension. There is nothing we can do in VS Code to address this.

**Comment by Hygens** [comment]
Okay. Sorry for my mistake open issue here.
