### ISSUE TITLE
Help popup font size: title ok but content too big

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#80724]
I've reported https://github.com/microsoft/vscode-python/issues/7208 to vscode-python tracker but they said it should be moved upstream.

- VSCode Version: 1.38
- OS Version: Ubuntu 19.04

Steps to Reproduce:

See link above.

image
![image](https://user-images.githubusercontent.com/6461412/64765632-c4eefd80-d544-11e9-8a52-6551a7791924.png)

Environment data
VS Code version: 1.37.1
Extension version: 2019.9.34474
OS and version: Ubuntu 19.04

Expected behaviour
Docstring font size more closely matches editor font size.

Actual behaviour
Docstring font is way too big.

**Comment by joaomoreno** [comment]
@aeschli Please assign hover, suggest and parameter hints to @octref

**Comment by octref** [comment]
This is already very small font size. Currently we don't allow you to customize that font yet. You can track #519.

**Comment by memeplex** [comment]
@octref this is not a request to customize the font, it's a bug report because the font is (not to sound harsh but yet) ridiculously big for a help tooltip. So I don't think it should be closed as a dup of #519.

**Comment by octref** [comment]
@memeplex The top part is rendered using your editor font. The bottom part is not the same font.

If I make it smaller I'm sure some other people would complain it's not readable. That's why I think setting is necessary.

**Comment by memeplex** [comment]
I see your point and I have to say that I've a slightly incremented zoom level (`"window.zoomLevel": 0.4,`), yet you can see that everything in the GUI (without taking into account the editor and terminal fonts, which are independently controlled) is smaller than the contents of the help popup. I still believe that it's set too large at the point of inconsistency wrt the rest of the GUI.
