### ISSUE TITLE
Folding and folding shortcuts not working on VSC 1.38.0

### ISSUE THREAD

**Issue by ls-chloe-schoreisz** [microsoft/vscode#80728]
- VSCode Version: : 1.38.0
- OS Version: mac Mojave 10.14.3

Steps to Reproduce:

1. Open VSC
2. Open a file with functions or class(.js, .ts, ..)
3. Fold some functions
![Screen Shot 2019-09-11 at 12 10 25 PM](https://user-images.githubusercontent.com/39059255/64714764-2c497680-d48d-11e9-83be-6f7931f43acc.png)

4. Navigate to another file
5. Come back to this file
6. The folding is not available, and the folding shortcuts do not work either
![Screen Shot 2019-09-11 at 12 11 04 PM](https://user-images.githubusercontent.com/39059255/64714803-3f5c4680-d48d-11e9-9c7f-50a7edad8714.png)

_Workaround:_ Reload the page 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
I'm not able to reproduce. If you have a code sample, or even a sample project (e.g. on github) that would be great.
Maybe you can also`"typescript.tsserver.trace": "messages"` in the settings and open the output view on the `typescript` tab to verify that on step 5, you get a trace message `Response received: getOutliningSpans...`
