### ISSUE TITLE
Can't modify hosts file in Windows 10 with "Retry as admin"

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/vscode#80721]
I'm having the same issue as #56894. This worked prior to updating VSCode to the latest version. I know that, since I need to modify the hosts file frequently to make WSL2 and local domains working.

Steps to reproduce:

1. Open VSCode (not in Administrator mode)
2. Open File `c:\Windows\System32\drivers\etc\hosts`
3. Make changes and save
4. Pop-up showing `Failed to save 'hosts': Insufficient permissions. Select 'Retry as Admin' to retry as administrator.`
5. Click on "Retry as admin"
6. Pop-Up error showing
```
Failed to save 'hosts': Command failed: "C:\Users\add\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --file-write "C:\Users\add\AppData\Local\Temp\code-elevated-vwdmrp" "c:\Windows\System32\drivers\etc\hosts" Error using --file-write: EPERM: operation not permitted, open 'c:\Windows\System32\drivers\etc\hosts'

```

System
```
Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18975
```

**Comment by MPowerData** [comment]
I have exact the same issue on 2 windows 10 laptops. Even running it as Administrator does not work.

Notepad++ does work.

**Comment by bpasero** [comment]
I am closing this as I do not know what is going wrong, sorry.
