### ISSUE TITLE
editor.renderFinalNewline: false has no effect, still shows empty line

### ISSUE THREAD

**Issue by vogler** [microsoft/vscode#80725]
Issue Type: <b>Bug</b>

~~~json
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  "files.trimTrailingWhitespace": true,
  "editor.renderFinalNewline": false, // seems to have no effect?
  "editor.wordWrap": "on",
~~~

![image](https://user-images.githubusercontent.com/493741/64712522-ab55a380-d4bb-11e9-905d-2433ed4632f2.png)
`git diff` output as it should be:
![image](https://user-images.githubusercontent.com/493741/64712596-ca543580-d4bb-11e9-9fe7-7457f4d196fc.png)

To  check a possible conflict with `insertFinalNewline`, I removed the visible empty line and got:
![image](https://user-images.githubusercontent.com/493741/64712915-523a3f80-d4bc-11e9-9c97-1c3fe264d984.png)
Note the dreaded 'No newline at end of file' which is not POSIX conform and makes diffs ugly (especially when also using vim).

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_1892814|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
haskero|Van|1.3.1
Bookmarks|ale|10.5.0
spellright|ban|3.0.46
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.9
vscode-great-icons|emm|2.1.47
reasonml|fre|1.0.38
macros|ged|1.2.1
ocaml-debugger|hac|0.1.2
latex-workshop|Jam|8.1.0
hoogle-vscode|jca|0.0.7
dune|mae|0.0.5
Lisp|mat|0.1.9
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34911
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
vscode-code-outline|pat|0.2.1
platformio-ide|pla|1.8.3
gi|rub|0.2.11
vscode-gtm|s3r|0.2.0
linter-xo|sam|2.3.2
code-settings-sync|Sha|3.4.2
vscoq|sie|0.2.7
stylish-haskell|vig|0.0.10
vscode-icons|vsc|9.3.0
vim|vsc|1.10.2
vscode-wakatime|Wak|2.2.0
quokka-vscode|Wal|1.0.243
better-align|wwm|1.1.6

(4 theme extensions excluded)

</details>

**Comment by vogler** [comment]
Related: #1027, #70344

**Comment by alexandrudima** [comment]
@vogler I cannot reproduce this. I am generating a file with the following script:

```js
require('fs').writeFileSync(`test.txt`, `Line1\nLine2\n`);
```

and then I open the file:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/64864984-97837c00-d638-11e9-9d3a-91bb7a05ccd4.gif)

**Comment by vogler** [comment]
Ok, very strange, it only happens in `settings.json`. For other files I get the same behavior as you.

Ideally, one shouldn't be able to put the cursor in the final newline (`Gdd` deletes the last line in vim, here it's a no-op; `Go` should append a line, here it appends an empty line and then opens a line).

**Comment by vogler** [comment]
It's a problem with word wrap:
![vscode](https://user-images.githubusercontent.com/493741/64908447-c82ee880-d700-11e9-97c6-9b0e5ac2cb89.gif)
