### ISSUE TITLE
UI and UX overhaul

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#8073]
The VS Code UI and UX has evolved to a point where we need to take a holistic and top down view on the experience and look for improvements and inconsistencies. We should define our principles and design language and use that to evolve the product.

In particular, we need to focus on 
- iconography #8017
- panels #7161
- colours #7649, #7648
- commanding #1136

**Comment by bgashler1** [comment]
We also should touch on **typography** tune-ups
https://twitter.com/brunnopleffken/status/752902520683593728

**Comment by bgashler1** [comment]
### Workbench
#1135 Notifications
#12377 Inline title bar, Mac
#8655 Status bar commanding (Git sync confusing)
#9853 search canceling and progress feedback

### Window managment
#2806 Panel position configurable

### Editor
#2352 Focus indication for editors

### Colors/accessibility
#12826 Peek UI contrast
#6065 Light theme text hard to read

**Comment by bgashler1** [comment]
We also should do some exploration on how the workbench could enable more advanced needs like SQL database exploration.

**Comment by dilijev** [comment]
If I may humbly submit an additional item for discussion: https://github.com/Microsoft/vscode/issues/12543 Improve horizontal screen real-estate

**Comment by Stanzilla** [comment]
statusbar, too?

**Comment by RoyTinker** [comment]
May I ask for https://github.com/Microsoft/vscode/issues/10121 to be considered? I think it's a top priority for a lot of developers who work on multiple monitors...

**Comment by jackjwilliams** [comment]
Agree with @roytinker, I feel like it's the big elephant in the room that no VSCode team member has responded or commented on (or maybe I missed it, I do a lot of GitHub browsing on my phone).

If it's not doable, at least let everybody know.

Thanks!
