### ISSUE TITLE
Broken product build: Storage Error in Publish Step

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80730]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=57756&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=88cf806a-7ffd-5251-d3d5-a4aa73b1ef42&l=26

**Comment by joaomoreno** [comment]
>  statusCode: 500,

Never seen this. But if storage is returning 500, this is hardly something we can fix. I would simply resubmit the build. If it happens often, we should probably look into updating our client library.
