### ISSUE TITLE
Long TS errors can't be read in the problems panel

### ISSUE THREAD

**Issue by AndrewMorsillo** [microsoft/vscode#80737]
- VSCode Version: 1.38.0
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Create a TS error that results in a very long message
2. Attempt to read the error message in the problems panel

The long problem message is cut off with ellipsis. The only way to read the message is to go to the location and hover over the problem to view the full output in a popup. There is no way to read the problem in the problems panel which given the generally long nature of TS error messages makes the problem panel mostly useless except for showing that a problem exists. Perhaps there should be an option to wrap error output or a scrollbar to see the rest of it.

Does this issue occur when all extensions are disabled?: Yes

![Screen Shot 2019-09-11 at 2 12 35 PM](https://user-images.githubusercontent.com/858965/64723285-3de74a00-d49e-11e9-8474-9b9b53f28a88.png)

**Comment by sandy081** [comment]
its not so often to get into this. and horizontal scroll bars is not a good option by default.
