### ISSUE TITLE
Press BracketLeft to find in explorer and shows Dead

### ISSUE THREAD

**Issue by MarcelloVSilva** [microsoft/vscode#80741]
- VSCode Version: 1.38.0
- OS Version: Linux x64 4.15.0-29deepin-generic

Steps to Reproduce:

1. Put focus on explorer section
2. Type BracketLeft, key code 219

![dead](https://user-images.githubusercontent.com/6786382/64727470-4c8a2d00-d4af-11e9-8a6b-91dc5c1603fa.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kevinunger** [comment]
Cannot reproduce

- VSCode Version: 1.38.0
- OS Version: macOS 10.14.6 (18G95)

**Comment by aganglada** [comment]
Cannot reproduce either

- VSCode Version: 1.39.0
- OS Version: macOS 10.14.2

**Comment by joaomoreno** [comment]
@MarcelloVSilva Do you maybe have a special keyboard layout?

**Comment by MarcelloVSilva** [comment]
No, i have a Dell Inspiron 14 5480 and i use his keyboard, i check again and the error stills here. Not just for BracketLeft, but shows the same error when i press `Quote`. I tested with external keyboard and i have same results.

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-29deepin-generic
```
Keys:
![WhatsApp Image 2019-09-23 at 20 33 59](https://user-images.githubusercontent.com/6786382/65470418-83fac100-de41-11e9-8598-c477a76b0502.jpeg)

**Comment by kevinunger** [comment]
Ok, I can reproduce it now on MacOS & Windows with english and german layout, but BracketLeft works. 
What kind of keyboard layout do you use @MarcelloVSilva, Portuguese layout?
Maybe this is related: [Issue](https://github.com/atom/keyboard-layout/issues/36)

When pressing a modifier key, the key event listener returns 'DEAD', this is normal, but should not be printed to the user. The modifier key is applied. So when I press ' ^ ' then ' a',  it shows ' â '. vscode should check the return value of the key event listener and filter out 'DEAD'.
Modifier keys that result in 'DEAD' :
-  ^
-   ` 
-   ´

**Comment by HanielBarros** [comment]
I'm using portuguese layout keyboard as well.

- ^
- ´  
-  ` 
- ~ 

All of these keys prints `Dead`

**Comment by IBRAHIM-HAMZA** [comment]
I'm using portuguese layout keyboard as well.

- ^

- ´

**Comment by frobinsonj** [comment]
@joaomoreno I'd be interested in taking a look at this if that's okay.

I've found https://github.com/microsoft/vscode/blob/385bf0f0e80a473e862dc27d4aa8127e926c2f13/src/vs/base/browser/ui/tree/abstractTree.ts#L692-L702

The obvious fix here is to amend L699 to include a check for dead keys, however, this seems a bit hacky. Is there somewhere else that this could be handled?
```ts
private onEventOrInput(e: MouseEvent | StandardKeyboardEvent | string): void {
	if (typeof e === 'string') {
		this.onInput(e);
	} else if (e instanceof MouseEvent || e.keyCode === KeyCode.Escape || (e.keyCode === KeyCode.Backspace && (isMacintosh ? e.altKey : e.ctrlKey))) {
		this.onInput('');
	} else if (e.keyCode === KeyCode.Backspace) {
		this.onInput(this.pattern.length === 0 ? '' : this.pattern.substr(0, this.pattern.length - 1));
	} else if (e.browserEvent.key !== 'Dead') {
		this.onInput(this.pattern + e.browserEvent.key);
	}
}
```

**Comment by joaomoreno** [comment]
@frobinsonj I think the best we can do is exactly what you've done with `!== 'Dead'`. Feel free to submit a PR!
