### ISSUE TITLE
User set editorAssociations not show in openWith

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80744]
Issue Type: <b>Bug</b>

**Repo**
1. Set

```
    "workbench.experimental.editorAssociations": [
        {
            "filenamePattern": "*.md",
            "viewType": "imagePreview.previewEditor",
        }
    ],
```
1. In explorer, right click on a md file and go to `Open with`

**Bug**
Preview editor is not listed in list of editors

VS Code version: Code - Insiders 1.39.0-insider (211fa02efe8c041fd7baa8ec3dce199d5185aa44, 2019-09-11T06:12:03.831Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_2556528|
|Screen Reader|no|
|VM|20%|
</details>

**Comment by RMacfarlane** [comment]
@mjbvz I'm not seeing an `Open with` option in the explorer context menu, has this been changed?
