### ISSUE TITLE
When I move window to side, part of it shows up on another monitor

### ISSUE THREAD

**Issue by jychoudh** [microsoft/vscode#80747]
Issue Type: <b>Bug</b>

When I move VS Code window to right side by pressing Windows + RightArrow key, a part of the window shows up on my second monitor (which is on my right), a little bit of title bar of the window is also cut and a little bit of bottom part of window hides behind start menu bar.

This might be helpful - my main monitor has 3440x1440 resolution and the secondary monitor has 1920x1080 resolution.

I have uploaded the screenshot [here](https://imgur.com/a/G4IASVk). You can see that VS Code has covered part of Command Prompt window in the right monitor (You cannot see the drive letter in the command prompt).

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-pipelines|ms-|1.157.2
vscode-docker|ms-|0.7.0
python|ms-|2019.9.34911
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
java|red|0.48.0
bash-beautify|sha|0.1.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2

</details>

**Comment by jychoudh** [comment]
If I use `native` instead of `custom` for `window.titleBarStyle`, the issue does not reproduce.

**Comment by sbatten** [comment]
@deepak1556 we've seen issues like this before where frameless windows in electron overflow the monitor just slightly in maximized or snapped states. 

@jychoudh Can you try with our insiders build? This may be fixed in a newer version of electron.

https://code.visualstudio.com/insiders/

**Comment by jychoudh** [comment]
I tried insiders build. Same issue occurs.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
