### ISSUE TITLE
[php] 'use' statement breaks coloring

### ISSUE THREAD

**Issue by louwill** [Microsoft/vscode#8074]
Running VSCode 1.2.1 on Windows 7 with Dark+ (Default).  When a PHP using statement exists, HTML tags are not themed correctly.  See two attachments: the first with the using statement commented; the second with the using statement not commented.  This appears to have broken in a recent release.

![image](https://cloud.githubusercontent.com/assets/1969592/16320586/8e027694-3966-11e6-9dbc-746d55f6d825.png)

![image](https://cloud.githubusercontent.com/assets/1969592/16320597/983c1b42-3966-11e6-8028-67f5640e3364.png)

**Comment by roblourens** [comment]
(Late response, but) this is actually a result of not using a semicolon after the use statement. It happens to PHP without html as well:

![image](https://user-images.githubusercontent.com/323878/30009050-16c35022-90da-11e7-930d-1a0f33cea69d.png)

![image](https://user-images.githubusercontent.com/323878/30009054-21458b78-90da-11e7-9b83-d1e23f8de2af.png)

**Comment by zessx** [comment]
This is not totally fixed, the issue subsists with in-class "improved" use statements.

This works well:
```
class FooClass 
{
  use BarTrait;

  public function __construct() {};
}
```


But not this:
```
class FooClass 
{
  use BarTrait {
    barFunction as private;
  };

  public function __construct() {};
}
```

**Comment by roblourens** [comment]
There was nothing fixed here, I just pointed out that the case was missing a semicolon. I'm not aware of any remaining issue. Your case looks correct to me:

![image](https://user-images.githubusercontent.com/323878/31188319-60e25b9a-a8e9-11e7-9c29-5d3aeb2ead8f.png)

Please open another issue if there's a problem.
