### ISSUE TITLE
VSCode API to get recommended extensions

### ISSUE THREAD

**Issue by Priya91** [microsoft/vscode#80750]
Is there an api or command to get the list of recommended extensions? The workbench.extensions.action.showRecommendedExtensions command shows the recommended extensions in the Extensions panel. 

Can this logic be exposed: https://github.com/microsoft/vscode/blob/dedf0de944fae56f0bf748913cbc1b2cc24987d2/src/vs/workbench/contrib/extensions/browser/extensionTipsService.ts

**Comment by sandy081** [comment]
What is the use case for this requirement?
