### ISSUE TITLE
Cannot Change Font

### ISSUE THREAD

**Issue by 8thHalfHour** [microsoft/vscode#80752]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Change the font family list in User Settings to 'Fira Code' and save settings.

Expected Result:
The font within the code editor window changes to the new font.

Actual Result:
VS Code substitutes what looks like Times New Roman instead of the new font.

What I've Done to Troubleshoot:
I've replaced the original setting for Font Family to "Consolas, 'Courier New', monospace" and everything returns to normal. I then tried 'Deja Vu Sans Code' with the same problem, then Inconsolata, all with the same results. It is not until I replace the setting with the original values that font is no longer displayed as some sort of default serif font.

FYI: All of these fonts are 100% correctly installed on my system. I can access them without issue in Microsoft Office, Photoshop, and Notepad++.

VS Code version: Code - Insiders 1.39.0-insider (211fa02efe8c041fd7baa8ec3dce199d5185aa44, 2019-09-11T06:18:37.576Z)
OS version: Windows_NT x64 10.0.18945

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|2.2.2
remote-containers|ms-|0.75.0
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
html5-boilerplate|sid|1.0.3

</details>

**Comment by 8thHalfHour** [comment]
This issue is not duplicated in any of those that are mentioned. I had looked into other possible duplicate scenarios, but those all seem to have been resolved by not overwriting settings in workspace and user or something else along those lines. To the best of my knowledge, this issue does not seem to have been addressed here yet.

**Comment by alexandrudima** [comment]
@8thHalfHour Can you share your `settings.json`? Have you restarted VS Code since you installed the font? Can you post a screenshot of how the font looks like?
