### ISSUE TITLE
Code does not prompt for restart when installing a .vsix file.

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#8075]
- VSCode Version:
```
Version 1.3.0-insider
Commit 5eaf9f05038b0a9818ebff510e1aafe07ac1ae68
Date 2016-06-23T05:07:59.360Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```
- OS Version:
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.10586 Build 10586
```

Steps to Reproduce:

1. From new extension UI, search for any extension and install

Expected Behavior:
Code installs extension and prompts for restart.

Actual Behavior:
Code installs extension and does not prompt for restart.

**Comment by isidorn** [comment]
Now the extension nicely shows that it is disabled when the user clicks enable the user is prompted for a restart - I like this experience so please check it out and let us know what you think.

![enableextension](https://cloud.githubusercontent.com/assets/1926584/16376084/e55db606-3c5e-11e6-8f55-9783b847d6b6.gif)

**Comment by chuckries** [comment]
@isidorn thanks! I had not seen this in the build I was working with, but I have seen it in a more recent build.

**Comment by isidorn** [comment]
Verified by user -> adding tag

**Comment by chuckries** [comment]
When installing an extension with the 'File -> Open -> .vsix file' workflow, there is no prompt for a restart, nor does the 'Enable' button appear in the Extensions viewlet. Please reopen this issue.

**Comment by chuckries** [comment]
![vsix](https://cloud.githubusercontent.com/assets/6598594/16507001/4255064c-3edb-11e6-824d-3d4d2ee99da4.gif)

**Comment by isidorn** [comment]
Reopening issue - this flow is not the main scenario how users would use the viewlet -> removing important, july
