### ISSUE TITLE
Missing error details from test

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80757]
- Have extension test code that throws an error at the top level (outside of a test)
- Run the test, the error message shows up in the console, but the full stack is nowhere to be seen
- Be confused and spend awhile hunting for the source

This is sort of the opposite of https://github.com/microsoft/vscode/issues/76096 but we can probably satisfy both.

**Comment by octref** [comment]
This is doable by changing test running script:
- Currently, when the test finishes with failure or when the test fails to run, the test script throws error, which is handled in Ext Host by `err.toString`
- The test writer can print the error in the case when test fails to run

**Comment by octref** [comment]
Verifier:
- Create a statement to `throw Error('something')` outside the `test` function callback: https://github.com/microsoft/vscode-extension-samples/blob/ba9a56e68277b6ba0ae3ee4593b6a864ba158b1f/helloworld-test-sample/src/test/suite/extension.test.ts#L11-L14
- Run the extension test from either CLI (`npm run test`) or debug viewlet. See error with full stack trace.
