### ISSUE TITLE
Find all references peek goes away when opening in different file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80754]
- Trigger peek find all refs
- Navigate to a reference in the same file, press enter
- It navigates there and peek stays open
- Navigate to a reference in a different file, press enter
- It navigates there and peek closes

I'm not sure what the behavior is supposed to be. It looks like in previous versions, peek would always stay open or always close. It seems like it should be consistent and either of those would be preferable, but is there a bug here?

**Comment by jrieken** [comment]
This seems to be a regression from https://github.com/microsoft/vscode/issues/80362. I am removing the selection change listener as suggested by @joaomoreno in https://github.com/microsoft/vscode/issues/80362#issuecomment-528247865
