### ISSUE TITLE
STDIN file extension support

### ISSUE THREAD

**Issue by scabana** [microsoft/vscode#80759]
Allow doing something like: ```more some.yml | code --file-extension yml -```. 

This would allow having the right editor kind right away instead of having a .txt file and having to rename it (or which ever other gesture to get the right editor).

Willing to contribute if idea is accepted.

**Comment by aeschli** [comment]
To read from stdin, append `-`
`ps aux | grep code | code-insiders -` or `echo Hello World | code-insiders.exe -`

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/84079
