### ISSUE TITLE
Do not set --wait when reading from stdin

### ISSUE THREAD

**Issue by sjackman** [microsoft/vscode#80755]
Issue Type: <b>Bug</b>

`seq 10 | code -`

Reading from stdin, `code` does not immediately exit as I would expect. It waits as though `--wait` was specified.

A previous locked issues was opened here: https://github.com/Microsoft/vscode/issues/39682

> Currently "as designed". I am setting the `--wait` because I do not know how much data is coming in via stdin so I simply wait until the editor is closed, because then I know that the user does not care anymore about the data.

I suggest reading from stdin until the end of the stream.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
Ended up removing the `--wait` when reading from stdin: https://github.com/microsoft/vscode/issues/199035
