### ISSUE TITLE
Startup args (--disable-gpu) lost from start menu shortcuts on VSCode update

### ISSUE THREAD

**Issue by cpcfreak** [microsoft/vscode#80765]
Issue Type: <b>Bug</b>

On Windows 10 Pro, whenever MS VS Code updates the optional startup arguments are lost from all shortcuts. IN my case I mainly use --disable-gpu due to blurred fonts!

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
@bpasero Any chance we can have `--disable-gpu` as a permanent flag ie setting or a special `argv` file (like in the good old days)?
