### ISSUE TITLE
C/C++ extension is downloading

### ISSUE THREAD

**Issue by liangpu597** [microsoft/vscode#80764]
- VSCode Version: 1.38.1
- OS Version: win7 64

Steps to Reproduce:

1. I install C/C++ entension and  errors:Downloading package 'C/C++ language components (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'ClangFormat (Windows)'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!
Downloading package 'Visual Studio Windows Debugger'  Failed. Retrying... Failed. Retrying... Failed. Retrying...Waiting 8 seconds... Failed. Retrying...Waiting 16 seconds... Failed. Retrying... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

2. I download vsix file from internet use from vsix install reload and it's still downloading

3.I reinstall vscode , it doesn't work!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please file against https://github.com/Microsoft/vscode-cpptools/issues
