### ISSUE TITLE
can not use [save all] from UI, when showTabs is true

### ISSUE THREAD

**Issue by realmx** [Microsoft/vscode#8076]
- VSCode Version: Code - Insiders 1.3.0-insider (5eaf9f05038b0a9818ebff510e1aafe07ac1ae68, 2016-06-23T05:04:13.858Z)
- OS Version: 10.11.5

Steps to Reproduce:

1.custom settings
```javascript
{
    "explorer.openEditors.visible": 0,
    "workbench.editor.showTabs": true
}
```
2.edit some files more then two

**Comment by bpasero** [comment]
@realmx where from do you invoke "Save All" and what is happening then?

**Comment by realmx** [comment]
- `"explorer.openEditors.visible": 9`
![1](https://cloud.githubusercontent.com/assets/6071313/16358773/2e714452-3b51-11e6-93fe-7baaacc0462b.jpg)

- '"explorer.openEditors.visible": 0'
![2](https://cloud.githubusercontent.com/assets/6071313/16358774/34fcdb7e-3b51-11e6-96a5-db64241f8e33.jpg)

@bpasero  when "explorer.openEditors.visible" set 0, how can i do to [save all]?  don't use the menu bar.

**Comment by bpasero** [comment]
@realmx in this case you can
* use the top level menu File > Save All
* use the Save All command from the command palette (View > Command Palette)
