### ISSUE TITLE
我很需要能够支持 TFS功能

### ISSUE THREAD

**Issue by 498184609** [microsoft/vscode#80762]
我需要在vscode里面想git一样方便的使用tfs的功能，现有的tfs插件无法在mac系统下面使用，都需要TFS.exe 

Google translate:
I need to use the tfs function as easy as git in vscode. The existing tfs plugin cannot be used under the mac system. I need TFS.exe.

**Comment by aeschli** [comment]
Please file the issue against the TFS extension that you are using.
