### ISSUE TITLE
XML coloring breaks on certain comments

### ISSUE THREAD

**Issue by TomByrne** [microsoft/vscode#80763]
Issue Type: <b>Bug</b>

XML coloring gets screwed up after there is a comment that contains two dashes ('--').

For example:
```
<!-- <haxeflag name="--macro macro.CustomJSGenerator.use()"/> -->
```

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
vscode-npm-script|eg2|0.3.9
vscode-commandbar|gsp|0.3.1
vscode-docker|ms-|0.7.0
powershell|ms-|2019.5.0
vshaxe|nad|2.16.0
lime-vscode-extension|ope|1.3.1
haxe-debug|vsh|1.2.3

</details>

**Comment by alexr00** [comment]
https://www.w3.org/TR/REC-xml/#sec-comments
