### ISSUE TITLE
Find dialog: vertical size and auto clearing when switch files

### ISSUE THREAD

**Issue by derekwallace** [microsoft/vscode#80770]
VSCode 1.38.0
Windows 10

Ive noticed that the Find / Find and Replace box can misbehave. it sometimes does not show fully.
e.g. here is what it looks like now. A few minutes earlier it was fine.
![image](https://user-images.githubusercontent.com/5574230/64756276-46836300-d526-11e9-89ca-ccb66e56ac6b.png)

![image](https://user-images.githubusercontent.com/5574230/64756288-4be0ad80-d526-11e9-9070-a0741a13713e.png)

If i select a workd and hit Ctrl-F, it now resolves itself
![image](https://user-images.githubusercontent.com/5574230/64756311-6155d780-d526-11e9-8cbd-6d58121518eb.png)

If i switch to another file, the Find text box clears itself. This is the biggest issues as sometimes i switching between files looking for the same string.
![image](https://user-images.githubusercontent.com/5574230/64756354-7fbbd300-d526-11e9-831e-d205f6a80f26.png)

**Comment by alexandrudima** [comment]
@derekwallace I see your screenshot and trust that this does indeed happen, but have you noticed any particular steps that causes this (so we could try to reproduce)?

**Comment by derekwallace** [comment]
it hasnt happened again since i posted. i restarted vscode and maybe this resolved the issue.

**Comment by alexandrudima** [comment]
@derekwallace I think you have hit a real bug, it has been reported also in #80826 , but I cannot reproduce. Can you please reopen this issue if you find any steps? Thank you!

**Comment by derekwallace** [comment]
It happened again today. I dont have specific steps to reproduce. Ill monitor and if i see a pattern ill post.

**Comment by alexandrudima** [comment]
@derekwallace Thank you, we found steps in #80826 and identified the root cause!
