### ISSUE TITLE
can't reflash folder status on time

### ISSUE THREAD

**Issue by LittleControl** [microsoft/vscode#80772]
Issue Type: <b>Bug</b>

Today I find when  I and a file in terminal (not in the vs code),my folder isn't display the file I add just now.
Is't a bug? I don't now

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:24:50.826Z)
OS version: Linux x64 5.0.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.56GB (2.10GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-node-readme|ben|3.0.2
vscode-intelephense-client|bme|1.2.3
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
node-modules-navigation|geg|0.0.2
beautify|Hoo|1.5.0
vscode-exec-node|mir|0.5.1
easy-less|mrc|1.4.5
vscode-less|mrm|0.6.3
markdown-preview-enhanced|shd|0.4.3
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.3.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by aeschli** [comment]
Sorry, I'm not sure I undertand.
The VSCode doesn't show a file that was just added?
Maybe add a screenshot?

**Comment by aeschli** [comment]
Thanks for letting us know. Closing the issue then.
