### ISSUE TITLE
Cannot Attach debug process to C#

### ISSUE THREAD

**Issue by Liam-Fitzpatrick** [microsoft/vscode#80781]
Issue Type: <b>Bug</b>

when ever I attempt to run debug or attach a process to the debug I get the following error

command "csharp.listProcess' not found 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
Can you file this against the cpp extension? https://github.com/microsoft/vscode-cpptools/issues
Thanks a lot!
