### ISSUE TITLE
Add more scopes to Dark+ and Light+ themes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#80783]
Original context: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/388

We should look into adding some of the scopes from https://github.com/microsoft/vscode-cpptools/blob/master/Themes/themes/cpptools_dark_vs.json into the Dark+ and Light+ themes to better highlight C++. If other grammars use those scopes it could improve highlighting for them too.

**Comment by alexr00** [comment]
@Colengms I can go through https://github.com/microsoft/vscode-cpptools/blob/master/Themes/themes/cpptools_dark_vs.json and see if it makes sense to add all the scopes that the VS Code + themes don't have and try to translate the colors to match the existing theme colors, but if there are specific scopes that you think particularly important I can do those first.

**Comment by alexr00** [comment]
I added the scopes you had in the themes to the dark+ and light+ themes. Some of the colors didn't quite match what we already have, so I tweaked them. @Colengms let me know what you think!

**Comment by Colengms** [comment]
Thanks Alex!

@jeff-hykin Are there any C++ TextMate tokens that should be included in the default+ themes?

**Comment by matter123** [comment]
Scope | Should Have the Same Color As | Example
------|------------------------------ |--------
`meta.embedded.assembly` | `string` | `asm("movl %a %b");`
`entity.other.attribute` | `entity.name.namespace` | `[[gnu::hot]]`
`entity.name.operator` | `keyword.other.operator` | `bool operator==()`
`keyword.operator.noexcept` | `storage.modifier` | `void func() noexcept;`

**Comment by jeff-hykin** [comment]
I think `keyword.operator.wordlike` ( `xor`, `and`, `or`, etc) is the only one I'd add to matter's list.
I'd recommend not coloring `meta.preprocessor`, or really any `meta`.

I mostly recommend other themes because of the punctuation and operator highlighting. But that is kind of a fundamental difference since I think Dark+ theme doesn't color operators/punctuation in any languages.

The reason I recommend it in C++ is because it makes most white colored things (the unknown) variables and difficult-to-match types. Since variables can't (yet) be colored directly, this is the next closest thing to highlighting variables directly. By choosing for both punctuation and operators to be white, it can make for a decent number of lines of completely unhighlighted code like `Type value = other_val + val2;`

If you want to be advanced, you can color all of the function-related punctuation yellow, all of the class/struct/enum/union punctuation green.

**Comment by alexr00** [comment]
@Colengms after talking with @aeschli about the history and current state of our themes, I've made a few changes to the scopes I added to better match our current colors and theme philosophy. You can see the changes in https://github.com/microsoft/vscode/commit/c1fdabc4f28f20fd63c6a6ef68d182617fb82813

I do have a few question/comments about some of the scopes that I removed:
`variable.parameter`: We currently don't do special coloring for any language for parameters and we want to stay consistent.
`entity.name.function.operator`: Can you give an example of this? If it makes sense, we could add it to one of our existing color groups.
`entity.name.function.preprocessor`: Since this one claims to be a function, we'd prefer to keep coloring it like a function. If it isn't actually a function, perhaps the scope could be renamed.
`entity.name.operator.custom-literal`: What should this be colored like? Is it a property?

**Comment by alexr00** [comment]
@matter123 and @jeff-hykin I added the specific scopes you mentioned with the exception of the meta scope in https://github.com/microsoft/vscode/commit/6ba021ba320ee21bd533cd51dc756a6a56f92c4c

**Comment by Colengms** [comment]
@alexr00 

entity.name.function.operator is an operator overloaded as a function.  It will color both definition and use of the operator.

entity.name.function.operator.member is similar, but refers to when an operator is overloaded as a member.

entity.name.function.preprocessor is for preprocessor functions.  i.e. macros.

entity.name.operator.custom-literal is for user-defined literals.  https://en.cppreference.com/w/cpp/language/user_literal



![image](https://user-images.githubusercontent.com/49173979/65266395-d47fc080-dac7-11e9-8b7f-d038f2936df6.png)

**Comment by matter123** [comment]
@alexr00 the current color rule for `meta.embedded` causes assembly string literals to be colored white, overriding the previous scope of `stting.quoted.double`.

**Comment by alexr00** [comment]
I've undone the change to have #include be blue instead of purple in dark (and the equivalent in light) because it is a dramatic change that is not also a strict improvement as it is already colored fairly specifically. 

@Colengms and @matter123  I'll look at the remaining proposed changes in October!

**Comment by Colengms** [comment]
Hi @alexr00 , We have https://github.com/microsoft/vscode-cpptools/issues/938 regarding the C++ alignof operator (`keyword.operator.alignof.cpp`) not being colored by default themes.  Could we add that also?

![image](https://user-images.githubusercontent.com/49173979/66616938-b4539680-eb87-11e9-93a1-dcc28553fce0.png)

**Comment by alexr00** [comment]
I added:
`entity.name.operator.custom-literal`, colored as a function
`entity.name.function.preprocessor` colored as preprocessor
`meta.embedded.assembly` colored as a string

I didn't add `entity.name.function.operator`* because it is already colored as a function, which seems ok.

**Comment by alexr00** [comment]
Verified through integration tests.
