### ISSUE TITLE
extensions search bar can't work correctly

### ISSUE THREAD

**Issue by Imputes** [microsoft/vscode#80788]
![image](https://user-images.githubusercontent.com/12896162/64768705-8117ea80-d57c-11e9-9f21-7b27d2eb6e72.png)
When I want to enter characters in the search bar of the extensions, the input goes to the edit page on the left.

**Comment by sandy081** [comment]
I cannot repro it. Are there any special steps to get into this state?
Can you also please try by disabling all extensions?

**Comment by Imputes** [comment]
I find always show the side bar can fix this.

**Comment by sandy081** [comment]
Not sure what you meant by `I find always show the side bar can fix this.`

Can you please provide steps to repro it?

**Comment by Imputes** [comment]
I have found the solution.
