### ISSUE TITLE
No undo changes after file changes

### ISSUE THREAD

**Issue by 1475142232** [microsoft/vscode#80797]
VSCode Version: 1.38.1
提交: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
Steps to Reproduce:

1.Change one when no file changes file
2.The file does not undo the change when it appears in change
![1](https://user-images.githubusercontent.com/25600940/64783150-a109d700-d599-11e9-9421-9f983cd2cac0.jpg)
![2](https://user-images.githubusercontent.com/25600940/64783155-a404c780-d599-11e9-8a59-f327f358687e.png)
This is version 1.32 which is fine.
Reinstallation does not take effect.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Same as #79239
