### ISSUE TITLE
Open file with selected text

### ISSUE THREAD

**Issue by mifas** [microsoft/vscode#80792]
Would like to have a feature, like when selecting a word. Then **Go to File...**, should lists down the selected file.

![intellij](https://user-images.githubusercontent.com/4384874/64772950-14a0e980-d584-11e9-83cb-d81dc7d603c6.gif)

**Comment by sajidali** [comment]
This is still important feature. selected/highlight text should be used to search for file open dialogue.

**Comment by AndrewNR** [comment]
This would definitely increase the productivity, since this is a common action in my daily routine: I select the page controller's name and want to open it (since the Apex + Visualforce language doesn't detect it as a reference to file). So when I open the "Go to File..." dialog, I would like the selected text (controller's file name) to be pre-populated as a searched value.

**Comment by moshfeu** [comment]
@roblourens Why?

**Comment by mifas** [comment]
@roblourens Why did you close this issue?

**Comment by khansharukh** [comment]
Guys, I am using this workaround.

Very lightweight extension - https://marketplace.visualstudio.com/items?itemName=colch.quick-open-prefill-selection

keybindings.json
```
    {
        "key": "ctrl+shift+n",
        "command": "extension.quickOpen.withPrefill",
        "when": "editorTextFocus && editorHasSelection && !editorHasMultipleSelections"
    },
    {
        "key": "ctrl+shift+n",
        "command": "-workbench.action.newWindow"
    },
    {
        "key": "ctrl+p",
        "command": "extension.quickOpen.withPrefill",
        "when": "editorTextFocus && editorHasSelection && !editorHasMultipleSelections"
    }
```

I don't like ctrl+n to open new window, so disabled 😛

Hope it helps.

**Comment by offeria** [comment]
I'm using similar approach. I've downloaded 

https://marketplace.visualstudio.com/items?itemName=geddski.macros

and added the following lines in keybindings.json

```
  {
    "key": "ctrl+shift+N",
    "command": "macros.openFileFromSelectedText",
    "when": "editorTextFocus && editorHasSelection && !editorHasMultipleSelections"
  },
  {
    "key": "ctrl+/",
    "command": "macros.commentDown"
  },
```
and added the following lines in settings.json:

```
    "macros": {
        "openFileFromSelectedText": [
            "editor.action.clipboardCopyAction",
            "workbench.action.quickOpen",
            "editor.action.clipboardPasteAction"
        ],
        "commentDown": [
            "editor.action.commentLine",
            "cursorDown"
        ],
    },
```

You can use the **commentDown** command if you want the cursor to go to the next line when you have commented out the current line of code.

**Comment by 733amir** [comment]
I believe this is a very small and simple feature that can improve the experience. Are there any plans to implement this? 🤔

**Comment by bingxin-xia** [comment]
WebStorm already has this feature, select the file-name in "import" section, double hit Shift key, will search files with selected file-name. A simple feature, but highly efficient.

**Comment by timkindberg** [comment]
Recently migrated to Cursor from Jetbrains and I'm missing this feature :(
