### ISSUE TITLE
JSDoc @author tag email address is obfuscated

### ISSUE THREAD

**Issue by petersandor** [microsoft/vscode#80790]
- VSCode Version: 1.38.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:
1. Create a TS file with some code (empty class/function, anything that can be annotated with JSDoc)
2. Add `@author` JSDoc with email address and then hover/click on the email in the popup

<img width="530" alt="Screenshot 2019-09-12 at 10 56 13" src="https://user-images.githubusercontent.com/3933866/64771066-a7269600-d54e-11e9-909d-0a21f0679c19.png">

Note the parsed JSDoc message from TypeScript server in output log, it sends the email address correctly (unobfuscated).

Does this issue occur when all extensions are disabled?: Yes

**Comment by hypercubestart** [comment]
@mjbvz I can try fixing this issue

**Comment by mjbvz** [comment]
Should be fixed by #80898
