### ISSUE TITLE
Command line option for search and replace

### ISSUE THREAD

**Issue by remy-tiitre** [microsoft/vscode#80795]
It is nice that you can open Visual Studio Code from command line and provide the folder to open as well (`code folder`). With an option `code --diff file1 file2` you can right away get the comparison view.

I would like to be able to execute `code folder --search "some search string"` and `code folder search "old string" --replace "new string"` to open Visual Studio Code in Search tab with appropriate fields filled in and maybe additional parameter `--execute` to perform the search and/or replace immediatly.

**Comment by roblourens** [comment]
I don't think this is likely to happen. Better to use a CLI tool like ripgrep directly.
