### ISSUE TITLE
Make number of items in "Open Recent" -> folders/files configurable

### ISSUE THREAD

**Issue by webmaster128** [microsoft/vscode#80791]
I work with something like 20-30 different projects in a regular basis. Right now, only 10 items are shown in the File -> Open Recent -> Folders section, which requires a lot of manual opening.

It would be great of the number of items in both sections are configurable. Then I could set the number of folders to 20 and the number of files to 0. This would give me a noticable productivity boost.

**Comment by sbatten** [comment]
@webmaster128 The fastest way to access recent files or folders is through the `Open Recent` command. The default keybinding is `Cmd+R` (macOS) or `Ctrl+R` (windows/linux). This command will show you a longer list that you can even type to filter.
