### ISSUE TITLE
regexp used for "Follow link" needs to be smarter

### ISSUE THREAD

**Issue by kaushik-work** [microsoft/vscode#80796]
Issue Type: <b>Bug</b>

The "Follow link" feature in the output window is really useful. In most cases it does a great job of extracting a usable link from any junk that is printed in the window. However, on mac OS X I found that the following path does confuse it:

`/Users/kghose/.local/share/sevenbridges/benten/scratch/Users/kghose/Work/code/benten/tests/cwl/ebi/tools/Trimmomatic/Trimmomatic-v0.36.benten.test.job.yml`

VS Code chooses to extract the path as `/Users/kghose/Work/code/benten/tests/cwl/ebi/tools/Trimmomatic/Trimmomatic-v0.36.benten.test.job.yml`

Very likely we are pattern matching on the `/Users/*` but it is fooled in this case. I wonder if the pattern matching can be improved by matching on the first `/<looks like a path>` that has a gap before it. 

Thanks!

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 17.7.0

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/34026
