### ISSUE TITLE
Extensions icon

### ISSUE THREAD

**Issue by ealsur** [Microsoft/vscode#8079]
- VSCode Version: Code - Insiders 1.3.0-insider (5eaf9f05038b0a9818ebff510e1aafe07ac1ae68, 2016-06-23T05:07:59.360Z)
- OS Version: Windows_NT ia32 10.0.10586

The Extensions icon on the lower left corner dissapeared, I'm assuming there was a reason behind that and wondered which was it. It was quick to check the icon for pending updates, now I have to use the Show Extensions command to view which are pending to update (the new Extensions icon on the vertical bar does not change state).

**Comment by dbaeumer** [comment]
@isidorn FYI.

**Comment by joaomoreno** [comment]
Check it out: now you not only get notifications, but how many and you'll be able to see exactly which extensions need update.

![image](https://cloud.githubusercontent.com/assets/22350/16334871/de7d32c4-3a03-11e6-92f9-199948a72eca.png)

This feature is under heavy changes, so if you don't see this behaviour yet, wait a day or two.

**Comment by ealsur** [comment]
Thanks @joaomoreno for the claryfication :) It must be something with my installation then because I don't get the count on the vertical bar icon.

![image](https://cloud.githubusercontent.com/assets/1633401/16335187/a4ef6c7a-39db-11e6-8235-4c859f809c8d.png)

**Comment by joaomoreno** [comment]
You don't have it yet.

![image](https://cloud.githubusercontent.com/assets/22350/16335826/22e03e20-3a09-11e6-99ca-12e15eaebbfc.png)

Just be patient, it will come with the next update.
