### ISSUE TITLE
GTK (including Electron) applications no longer start when executed from VSCode shell

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#80807]
- VSCode Version: 1.38.1
- OS Version: Fedora 30

This is a fairly large regression imo. Breaks my current dev workflow and used to work in the past. GTK GUI application are no longer able to start up when run from VSCode/xterm.js terminal. This is a regression from previous releases of VSCode which I would assume were also using older versions of xterm.js. The following is the error message:

```
$ gtk3-demo
Unable to init server: Could not connect: Connection refused

(gtk3-demo:7741): Gtk-WARNING **: 21:41:12.079: cannot open display:
```

```
$ flatpak run com.spotify.Client 
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)

(spotify:6): Gtk-WARNING **: 21:41:34.836: cannot open display:
```

This is a transfer from https://github.com/xtermjs/xterm.js/issues/2421 because I incorrectly filed it under the wrong repo.

Steps to Reproduce:

1. Run a GTK or Electron application from the built in VSCode terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you share your settings.json file?

> (spotify:6): Gtk-WARNING **: 21:41:34.836: cannot open display:

Normally this error means `DISPLAY` is configured incorrectly?

**Comment by tristan957** [comment]
@Tyriar https://gist.githubusercontent.com/tristan957/4565ce535310d3e52aea10b7303a7bce/raw/cc533e89fa2ea65c65b2d7a263c87a868eb8496c/settings.json

**Comment by Tyriar** [comment]
This is probably why:

> "terminal.integrated.inheritEnv": false

**Comment by tristan957** [comment]
I don't even remember adding that. I am so dumb some times. @Tyriar sorry for having you chase this issue around.
