### ISSUE TITLE
When I select render whitespace, then language is changed

### ISSUE THREAD

**Issue by stefanJi** [microsoft/vscode#80805]
- VSCode: 1.38.0
- Date: 2019-09-03T21:47:00.464Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.7.0

Steps to Reproduce:

<img width="584" alt="屏幕快照 2019-09-12 下午11 06 34" src="https://user-images.githubusercontent.com/15273198/64796364-2600ea80-d5b2-11e9-9d47-5c0b295a29b3.png">

<img width="584" alt="屏幕快照 2019-09-12 下午11 06 59" src="https://user-images.githubusercontent.com/15273198/64796363-2600ea80-d5b2-11e9-83d8-20bde8e70d8e.png">

<img width="584" alt="屏幕快照 2019-09-12 下午11 07 14" src="https://user-images.githubusercontent.com/15273198/64796361-25685400-d5b2-11e9-933f-f24ca8d030fb.png">

Does this issue occur when all extensions are disabled?: No

**Comment by alexandrudima** [comment]
The action uses the configuration service to write the setting.

**Comment by sandy081** [comment]
Totally strange. Configuration change and language change are not at all related. It generally requires restart for language to change.

**Comment by dbaeumer** [comment]
I tried to reproduce this on Windows and failed using `1.38.1` @sandy081 can you reproduce this on Mac?

**Comment by stefanJi** [comment]
I can't reproduce the problem now. :frowning:

**Comment by dbaeumer** [comment]
@stefanJi thanks for getting back. Without being able to reproduce it is hard to understand what could cause this. I will keep the issue open for a while to see if we can find steps.
