### ISSUE TITLE
Alt Key Release problem

### ISSUE THREAD

**Issue by cristiansc1993** [microsoft/vscode#80809]
Issue Type: <b>Bug</b>

I have the Left Alt key bind to increase the scroll speed of a document while pressing it, the problem is that after I finished scrolling and release the key the Top Bar keeps items selected rendering the next keybinds to trigger the bar not the commands I want

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexandrudima** [comment]
I cannot reproduce with the native menus.

**Comment by sbatten** [comment]
Please try `window.customMenuBarAltFocus` as false. This will prevent alt from focusing the menu bar. Trying truly native application menus like notepad show that alt still focuses the menubar even with scrolling.
