### ISSUE TITLE
Drag and resize broken for terminal / while terminal is open

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#8080]
- VSCode Version:1.2.1
- OS Version: 8.1

Steps to Reproduce:

1.  While terminal is open, try to drag and resize the sidebar
2.  Try to resize the terminal

It jumps, its impossible to resize these windows without running into a huge issue. Often its random where the ui ends up being dragged to, and then its unusable

**Comment by Tyriar** [comment]
Fixed in master

**Comment by isidorn** [comment]
There are still some issues with the horizontal resize (captured in other issues) but other than that looks ok -> verified
