### ISSUE TITLE
Different theme for multiple instances

### ISSUE THREAD

**Issue by saurabhnil** [microsoft/vscode#80802]
Issue Type: <b>Feature Request</b>

Hello team

I usually work with more than one code base and hence keep multiple instances of VS code open. To avoid confusion between which VS Code window to refer and which one to modify - looking to keep separate colour theme for multiple instances. Currently if I change theme - it applies to all opened instances. I am looking to apply Dark theme for first instance, Red theme for second instance and so on...

Can you please take care of this?

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 6.1.7601

**Comment by aeschli** [comment]
You can also set a theme per workspace.
Also there are extension like https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock that help you distinguish windows.
