### ISSUE TITLE
Linux (Gnome DE) `code-workspace` MimeType support

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/vscode#80818]
In the Gnome desktop environment there isn't a MimeType associated with workspace files `*.code-workspace` and thus, they are opened with the default application registered for file type `text/plain`, (If I try to change the default app, all plaintext files default app are changed along with it).

It would be very beneficial to have a separate MimeType associated with `code-workspace` for usability i.e. the ability to have the file icon use the VSCode icon, and for double-click to open the workspace in VSCode.

**Comment by joaomoreno** [comment]
Relevant https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.18.html
