### ISSUE TITLE
Split Terminal Option Dont works

### ISSUE THREAD

**Issue by joxgarcia1997** [microsoft/vscode#80812]
When I was working on some project , was able to split the terminal, now days I cant, i click on the button, and nothing happens, nothing shows on the terminal, I already re-install VSCode, but nothing changes.

- VSCode Version: 1.38.1
- OS Version:Darwin x64 18.7.0

Steps to Reproduce:

1.Open Visual Studio code
2.Click on Split Terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you check devtools console (via help menu) for error?

I can't repro:

<img width="975" alt="Screen Shot 2019-09-13 at 9 41 52 AM" src="https://user-images.githubusercontent.com/2193314/64879405-c5ea6280-d60a-11e9-8f71-2c2270235fce.png">

**Comment by pavelloz** [comment]
Confirming. It stopped working after lastest update.

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 16.7.0
```

**Comment by Tyriar** [comment]
@paveldk 🤔 does it change if you make the window wider?

**Comment by pavelloz** [comment]
Nope, even on 2560px it doesnt do anything.

**Comment by pavelloz** [comment]
*Workaround*

For those who wait for fix, and are working on linux/macos, theres other way, using tmux (very powerful tool):
1) Install tmux (ie `brew install tmux`)
2) `tmux split-window -h -p 66`

Result:
![image](https://user-images.githubusercontent.com/546845/64966177-9bb0d300-d89e-11e9-825e-20df487d74b5.png)

**Comment by pavelloz** [comment]
I have tested on a different mac, with different OS version and it works fine.

Working system info:

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by Tyriar** [comment]
OP is on 18.7 though (me as well), so I doubt it's related to 16.7

**Comment by RyanPWalker** [comment]
Same issue; checked devtools but there are no errors

**Comment by Tyriar** [comment]
I just removed the minimum width check so you can try Insiders in a couple of days to see if that fixes the problem, I think that was the only thing that should prevent a split from being created. Let me know how it goes.

**Comment by RyanPWalker** [comment]
Still an issue.

**Comment by Tyriar** [comment]
If you're still seeing this you can try on Insiders to open devtools and debug into the split command to see what is going on:

https://github.com/microsoft/vscode/blob/c1ffc0ec43d1f9058cfff752c641bed41a94524b/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L418-L431

I can't repro so can't unfortunately.

This line might also be the issue:

https://github.com/microsoft/vscode/blob/c1ffc0ec43d1f9058cfff752c641bed41a94524b/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L423

You could try tweak the `terminal.integrated.splitCwd` setting and see if that resolves it?
