### ISSUE TITLE
Allow keyboard shortcuts for file changes save prompt for Don't Save, Save, and Cancel

### ISSUE THREAD

**Issue by gavin310** [microsoft/vscode#80811]
When closing a file that has been edited, it asks, "Do you want to save the changes you made to...?" Instead of having to click Don't Save or Cancel with your mouse, it should allow you to press D for "Don't Save", C for "Cancel", or S or Enter for "Save".

**Comment by vedipen** [comment]
@gavin310 Not sure which operation system you are talking about, but on Windows 10 with VSCode 1.38, I could find this feature already. And this OS integration feature has always been there as far as I remember.

![image](https://user-images.githubusercontent.com/13337451/65375929-00fa2f00-dcb8-11e9-81cd-81a21f67940f.png)

's' / 'enter' for Save, 'n' for Don't Save, 'esc' to Cancel

**Comment by gavin310** [comment]
@vedipen Sorry I should've clarified. I'm on OS X.

**Comment by bpasero** [comment]
Best you can do on macOS is this:

![Uploading image.png…]()

**Comment by szhu** [comment]
(This is an old issue, but might be useful for those who come across this issue in the future.)

Here are the shortcuts, which are universal across all macOS apps:
- **Don't Save:** ⌘D or ⌘⌫
- **Delete**\*: ⌘⌫
- **Cancel**: Esc
- **Save**: ⌘S or Enter

\* This doesn't apply to VSCode, but since 2011 in OS X Lion [[source 1](https://osxdaily.com/2011/08/15/return-the-dont-save-keyboard-shortcut-to-commandd-in-mac-os-x-lion/)] [[source 2](https://www.betalogue.com/2011/09/06/lion-dontsaveshortcut/)], some of the more native macOS apps show a confirmation dialog that also includes the Save File selector. In these dialogs, the Delete button can only be activated with ⌘⌫.
![image](https://user-images.githubusercontent.com/1570168/142090825-91815695-1eab-48ee-894a-5ac4701ddb37.png)

**Comment by et304383** [comment]
We need a way to make these shortcuts consistent on Windows/MacOS.
* On MacOS, CMD+D is ergonomic and can be done with one hand.
* On Windows, ALT+N is not ergonomic and requires two hands.

**Comment by vaughnkoch** [comment]
A related suggestion: on Windows, there's a visual underline hint that there's a hotkey.
On MacOS, there isn't. Why not make the hotkeys explicit on the actual buttons, e.g.:

Don't Save (⌘D)
Save (⌘S)
Cancel (Esc)

**Comment by yairfine** [comment]
Any new solution to this annoying missing feature?

**Comment by gavin310** [comment]
> Any new solution to this annoying missing feature?

It's such a simple workflow improvement which all macOS apps are implementing. I really don't know why they aren't adding it.

**Comment by szhu** [comment]
All, this has already been implemented. It works. You can use it.

On macOS you can use the standard keyboard shortcuts that all other apps use:

**Don't Save:** ⌘D or ⌘⌫
**Cancel:** Esc
**Save:** ⌘S or Enter

@bpasero consider locking this issue?

**Comment by yairfine** [comment]
Oh, thanks @szhu.
Though it really is working and also not discoverable... A hint would be very useful...

**Comment by cyejing** [comment]
> All, this has already been implemented. It works. You can use it.所有，这已经实施了。有用。你可以使用它。
> 
> On macOS you can use the standard keyboard shortcuts that all other apps use:在 macOS 上，您可以使用所有其他应用程序使用的标准键盘快捷键：
> 
> **Don't Save:** ⌘D or ⌘⌫不保存：⌘D 或 ⌘⌫ **Cancel:** Esc 取消：Esc **Save:** ⌘S or Enter 保存：⌘S 或 Enter
> 
> @bpasero consider locking this issue? 考虑锁定这个问题吗？

Why can't I use these shortcuts now with the latest version?

**Comment by angularsen** [comment]
On Windows, none of the above mentioned hotkeys seem to work (`alt+n`, `ctrl+n`, `alt+d`, `ctrl+d`)
There is no visual underline of any of the letters either.

![image](https://github.com/microsoft/vscode/assets/787816/7a6c3034-306a-4434-aca5-596dd662353e)

**Comment by nightgolfer** [comment]
@szhu 
> All, this has already been implemented. It works. You can use it.
> On macOS you can use the standard keyboard shortcuts that all other apps use:
> **Don't Save:** ⌘D or ⌘⌫ **Cancel:** Esc **Save:** ⌘S or Enter
> @bpasero consider locking this issue?

This does *not* work on MacOS†.

**NOT WORKING**
- ⌘D or ⌘⌫ — nothing happens
- ⌘S — nothing happens

**WORKING**
- Esc — cancels
- Tab or Arrow Keys (left + right) — move selection (thin blue line)
- Enter — chooses the selected button/action

Is there some extra setting that needs to be enabled for this to function, like you say it does?

VSCode v. 1.91.0
† MacOS Monterey 12.6.3

<img width="638" alt="Screen Shot 2024-07-16 at 11 28 51" src="https://github.com/user-attachments/assets/c5e25ea9-d3c5-4b6b-a653-2a932d649a68">

**Comment by AkkarinForest** [comment]
In MacOs Ventura you need to enable this toggle to be able to use Tab to switch between options. ![Screenshot_02_10_2024__11_37](https://github.com/user-attachments/assets/e8b6da64-87b9-4566-b3ae-01bf05874245)
On older systems it was as described above: https://github.com/microsoft/vscode/issues/80811#issuecomment-542057515
