### ISSUE TITLE
confirmedUriHandler clicks do not focus the editor

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#80816]
- VSCode Version: 1.38.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open VS Code
2. Open your browser, but have it on top of VS Code.
3. Click on a link from your browser that vscode can handle: `vscode://your.thing/foo/bar`. You will be switched to VS Code and be prompted if you want to `Allow an extension to open this`. Click `Don't ask again for this extension` then `OK`.
4. Repeat this process, but notice, after you've clicked the link, VS Code did not focus but it _did_ handle the URI correctly when viewing VS Code.

Another way to reproduce this is using multiple virtual desktops:

1. Put your browser on virtual desktop 1.
2. Put VS Code on virtual desktop 2.
3. Click on a link from your browser on virtual desktop 1 that vscode can handle: `vscode://your.thing/foo/bar`. Your virtual desktop should switch to desktop 2 and VS Code will ask if you want to `Allow an extension to open this`. Click `Don't ask again for this extension` then `OK`.
4. Repeat this process, but notice, after you've clicked the link from virtual desktop 1, you are not brought over to desktop 2, yet VS Code did handle the URI correctly when you move to virtual desktop 2.

(My thought is that a side-effect of the confirmation/alert is the editor focus, and that happens to work across apps and virtual desktops)

Does this issue occur when all extensions are disabled?: NA, this requires an extension.

**Comment by joaomoreno** [comment]
Good catch. I believe it works first since a native dialog comes up and Windows automatically calls the window out to the user's attention. Without the dialog we must do this by ourselves. @bpasero @deepak1556 Do you know if there is an Electron API to do this? And whether we have it exposed in our internal API?

@bcanzanella  Dumb question: how do you create a virtual desktop?

**Comment by bpasero** [comment]
Discussed, should always focus the window that the URL is being sent to.

**Comment by bcanzanella** [comment]
@joaomoreno With Windows 10, click the `Task View` button (next to the `Start` menu) -- from there you can add a desktop and/or move apps between desktops. https://community.windows.com/en-us/stories/virtual-desktop-windows-10

macOS and Linux have a similar virtual desktop / workspace feature too.
