### ISSUE TITLE
Add customizable HTML templates.

### ISSUE THREAD

**Issue by 8cy** [microsoft/vscode#80829]
At the moment, in VSCode, when you type, **!**, it creates a **HTML5 template**, it has been very useful for me and I am requesting this to be customizable.

After the **HTML5 template** is created, the first thing I always do is add commenting to seperate different parts of the head, such as invisable scripts, external libraries, css links and such. It would be amazing if in the **HTML tab** in the **preferences** in VSCode, there would be a option to **customize this template** so I can **add my comments/ custom template** there, so whenever I do, "**!**", the template would fit my criteria instantally.

**Comment by aeschli** [comment]
`!` as a emmet template. https://code.visualstudio.com/docs/editor/emmet describes how to configure emmet.

On top of that, VSCode has it's own snippet support, see https://code.visualstudio.com/docs/editor/userdefinedsnippets
