### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ezzelden** [microsoft/vscode#80823]
Issue Type: <b>Bug</b>

Please help me, I can't download any extension from vs code
Error Message: Failed to install '{APP NAME}'.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by agarhy** [comment]
Enable
Help -> Toggle Developer Tools
Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a DNS issue at your end.

To confirm its a DNS issue check if you can access this page 
[https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default]

**How to resolve ?**
1-Try a different connection e.g. mobile broadband 
2-Change your Browser, OS, or Network DNS to google DNS 8.8.8.8 & 8.8.4.4
