### ISSUE TITLE
Can't open .md preview in full tab any more?

### ISSUE THREAD

**Issue by ekpgh** [microsoft/vscode#80821]
Issue Type: <b>Bug</b>

VS Code just updated and now my .md file previews show up in a tiny panel to the right instead of in a full-width tab. I can't find a way to make them go back to the full-width tabs (like my editor tabs). 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
rtf|ale|2.0.2
vscode-markdownlint|Dav|0.30.2
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.17
docs-preview|doc|0.3.29
docs-yaml|doc|0.2.4
restructuredtext|lex|114.0.0
python|ms-|2019.9.34911
team|ms-|1.149.2
vscode-yaml|red|0.5.2
rewrap|stk|1.9.1
code-spell-checker|str|1.7.18

</details>

**Comment by ekpgh** [comment]
Ohhh I figured it out. The button that looks like the "preview" button is now the "side preview button" and there's another button that I didn't recognize for the tab preview. Took forever to find it though - nothing with those words in the menus. In retrospect, I'm not sure why I was cueing off the magnifying glass in the button - that's not really relevant to preview, but maybe it was in the old button for some odd reason.

**Comment by mjbvz** [comment]
Thanks for following up. Closing since this sounds related to [icon update](https://code.visualstudio.com/updates/v1_37#_new-product-icons)
