### ISSUE TITLE
code --list-extensions hangs when using a vpn 

### ISSUE THREAD

**Issue by Rhahkeem** [microsoft/vscode#80827]
- VSCode Version: 
```
1.38.0
3db7e09f3b61f915d03bbfa58e258d6eee843f35
x64
```
- OS Version:
```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```
For my work at my company we're required to use a VPN.

### Steps to Reproduce:
 These are all run from `iterm2` 
#### Connected with VPN  enabled
1.  Run  `code --list-extensions`

 This lists all the extensions and then just hangs as the process never gives control back to the command line. 

#### Disconnected (disabled wifi)
1. Run  `code --list-extensions`

This lists all extensions with no issues and returns control to command line 

#### Connected with VPN disabled
1. Run  `code --list-extensions`

This lists all extensions with no issues and returns control to command line 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate
https://github.com/microsoft/vscode/issues/77201
