### ISSUE TITLE
Selecting the content of the suggested smart prompt directly before the existing content will replace the existing content.

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#80831]
When inserting some content before an existing character, if you do not add a space before the existing content, the content selected by using Enter will replace the existing content, which is different from the expected result.

![vs_suggestion](https://user-images.githubusercontent.com/13393959/64830294-6a1bdb80-d602-11e9-90e0-ef67c636f682.gif)

![vs_suggestion_2](https://user-images.githubusercontent.com/13393959/64830299-71db8000-d602-11e9-8e60-7916247118bd.gif)

**Comment by aeschli** [comment]
That's with Java right?
Please file this directly against the Java extension that you use. I guess it's https://github.com/redhat-developer/vscode-java/issues

**Comment by czfadmin** [comment]
You're right.Thank you
