### ISSUE TITLE
save all and commit option only commits unsaved files

### ISSUE THREAD

**Issue by Truth1984** [microsoft/vscode#80837]
Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.0.0

Steps to Reproduce:

1 open multiple tabs and only save some of them.
2 commit and click `Save All & Commit`

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Oh yeah. Good catch. Want to submit a fix? Problem is [here](https://github.com/microsoft/vscode/blob/c05a0af7dba62a49eee4bb34b6f666f68a9812a5/extensions/git/src/commands.ts#L1271)

**Comment by asutosh97** [comment]
Hey, I am a new contributor here. I want to give a try on this issue.

**Comment by Truth1984** [comment]
@asutosh97 Great. Go ahead.
