### ISSUE TITLE
EditorGroupService.replaceEditors unexpectedly type casts argument type

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80835]
Issue Type: <b>Bug</b>

**Bug**
In `EditorGroupService`, the [`replaceEditors` implementation](https://github.com/microsoft/vscode/blob/e75e71f41911633be838344377df26842f2b8c7c/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1372-L1373
) takes a `EditorReplacement`. However the [public `IEditorReplacement.replaceEditors` api](https://github.com/microsoft/vscode/blob/dedf0de944fae56f0bf748913cbc1b2cc24987d2/src/vs/workbench/services/editor/common/editorGroupsService.ts#L529) only requires a `IEditorReplacement`.

This means that our implementation is performing a hidden type cast that can cause unexpected runtime errors

VS Code version: Code - Insiders 1.39.0-insider (b7a5b7cf39f569a570599530ffc855b454e37b06, 2019-09-12T08:43:00.105Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_4576349|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Here's an example of how the existing code causes problems: https://github.com/microsoft/vscode/blob/ebe12f588977d36739f60b0cf63312aac2e3a508/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L133

Without the call `EditorOptions.create`, we get a crash when trying to invoke `EditorOptions.override()` on a normal `IEditorOptions` object. I wish TS did not allow this but it's type system currently does since the `EditorOptions` used by the implementation implements `IEditorOptions` used by the interface

**Comment by bpasero** [comment]
@mjbvz everything should be OK if you go through the IEditorService interface, no? Because we do:

https://github.com/microsoft/vscode/blob/d3fe5cc0858434e65bba116108d754ea4801aa4e/src/vs/workbench/services/editor/browser/editorService.ts#L366

**Comment by bpasero** [comment]
This was horribly bad, I think I fixed all cases now. I ran into the same issue. You are now free to pass in any kind of options to that method and it will be converted properly.
