### ISSUE TITLE
i can't install any extention pack on VS Code

### ISSUE THREAD

**Issue by Abunagy1** [microsoft/vscode#80846]
<img width="770" alt="Untitled" src="https://user-images.githubusercontent.com/44762983/64848485-9ab74180-d611-11e9-914b-1d56f9ea8b6e.png">
Issue Type: <b>Bug</b>

ms-vscode-remote.remote-wsl / vscjava.vscode-java-pack / vscode.cpptools-0.25.1 why failed to install these packages extention 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (1.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.24.0

</details>

**Comment by Abunagy1** [comment]
can you explain please what did you mean by (Experimental duplicate detection) cause I am new to VS Code and it's the first time to open it

**Comment by alaadahmed** [comment]
I have the same issue exactly. 
I have macOS `10.14.6`
I have vscode ver. `1.38.1`
This issue I have since ver. `1.38.0` I think or maybe `1.37.1` not sure.

**Comment by Abunagy1** [comment]
I think there is something wrong with subsystem like virtual box linux or some other features conflict like java multi  IDE’s which i have on my computer

**Comment by sandy081** [comment]
Looks  DNS issue. #78783 #78872
Can you try to access this image? 

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by Abunagy1** [comment]
thanks dear sandy it looks like you are right i would check for DNS setting thanks again
