### ISSUE TITLE
Collapsing XML documents does not work from a depth of more than 10 levels

### ISSUE THREAD

**Issue by danielMd2805** [microsoft/vscode#80843]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open an XML Document with a XML structure greater 10 flats
2. Collapse all flats until flat 10 thus collapsing flat 11 or greate will not work.
3. You would not see an arrow at the specified line to collapse.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
yes, sorry, there's a limit of 500 folding regions per editor for performance reason.

**Comment by danielMd2805** [comment]
Okay, it is possible to make this adjustable? We are working with large XML-files which works great with code! In order to be able to analyze XML files, we must be able to collapse groups to a level greater than 10.

**Comment by aeschli** [comment]
We have https://github.com/microsoft/vscode/issues/72994 for the request to make the limit configurable.
