### ISSUE TITLE
Build: update node to 12

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80842]
I reverted the build related changes for node via https://github.com/microsoft/vscode/commit/254f6835b73bf7c868dc965649072144530be2b8 but we should eventually consider to bump our node.js version for building to the latest 12.x once we are confident with Electron 6.

**Comment by joaomoreno** [comment]
@bpasero Why the revert?

**Comment by bpasero** [comment]
@joaomoreno oh, I was under the impression that we should take it easy on the node update, but I can also bring it back. I think in the past we kept these two things independent from each other to make it easier to understand where a regression originates from.

**Comment by joaomoreno** [comment]
If this is just something to eventually get done, let's just close the issue and upgrade node when we actually need to. :+1:

**Comment by bpasero** [comment]
Yeah I just filed this as reminder.

**Comment by gjsjohnmurray** [comment]
I'm a bit confused about the status of this. My up-to-date Insider shows it's using Node.js 12.4.0
```
Version: 1.40.0-insider (user setup)
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:48:38.866Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134
```

But when I try to build on Windows from source after having installed that version of Node.js I'm told:
```
PS C:\Users\johnm\Documents\GitHub\vscode> yarn
yarn install v1.17.3
$ node build/npm/preinstall.js
*** Please use node >=8 and <11.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\johnm\Documents\GitHub\vscode>
```

**Comment by bpasero** [comment]
Yeah, we typically do:
* an electron update with a node.js update in one iteration
* an update of our build tools to use node.js in the next iteration

To know if a regression is caused by Electron or our build tools.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/83967
