### ISSUE TITLE
Display auto-import status in the status bar

### ISSUE THREAD

**Issue by jankalfus** [microsoft/vscode#80844]
There's a significant delay before auto-imports are ready in a TypeScript project after a file is opened for the first time, and probably every time the typescript server starts/restarts and a file is opened. I'm not sure if that's caused by the size of a project (about 30k lines of code), but that doesn't really matter.

What bothers me is that there's no way (or I haven't find a way) to tell when is VS Code ready to provide auto-import suggestions. So if I want to add a missing import, I have no other way to find out when the auto-import is ready other than repeatedly press ctrl + . and esc. See the attached GIF.

**It would be really nice to have an indicator in the status bar which displays whether the use of auto-imports is ready or not yet.**

![autoimport](https://user-images.githubusercontent.com/12714276/64846514-1fec2780-d60d-11e9-81f6-8946854e0bab.gif)

**Comment by mjbvz** [comment]
We show:

<img width="532" alt="Screen Shot 2019-09-13 at 10 28 41 AM" src="https://user-images.githubusercontent.com/12821956/64882110-46ac5d00-d611-11e9-81d7-ba7eb06fce5d.png">

When the js/ts service is starting or loading a new project

**Comment by jankalfus** [comment]
Yes, however, it doesn't display in the case I'm describing. If you modify a file outside of VS Code, then open that file in VS Code and try to add a missing import using ctrl + ., no status indicator is displayed and the import is not available until a few seconds later.

**Comment by jankalfus** [comment]
It also doesn't show the status in some other cases.

For a concrete example, I had a file open in the editor for quite some time, I added a ListItem from material-ui, I hit Ctrl+. to get the import suggestions, but there were't any. So I waited a few seconds, and then tried again - and they appeared, so I used them. Right after that, I added a ListItemText and the situation repeats. There is no status displayed anywhere for when these auto-imports are ready.

Please reopen @mjbvz
