### ISSUE TITLE
Display a status indicator when renaming a TypeScript file

### ISSUE THREAD

**Issue by jankalfus** [microsoft/vscode#80847]
When I rename a .ts/.tsx file, it takes some time before the operation completes and all the corresponding imports are changed to the new name. I don't see a way to tell when the operation completes.

I think it would be very useful to display an indicator showing the status of the rename operation in progress (as it takes seconds, maybe even tens of seconds, on large projects to complete) so that I know when I can safely resume editing code.

**Comment by mjbvz** [comment]
We already show:

<img width="388" alt="Screen Shot 2019-09-13 at 10 30 43 AM" src="https://user-images.githubusercontent.com/12821956/64882226-8ecb7f80-d611-11e9-86b9-84c65e9ec417.png">

while this is happening

**Comment by jankalfus** [comment]
I haven't noticed that then. Is it possible there are some occassions on which the status doesn't display?
