### ISSUE TITLE
"'await' has no effect on the type of this expression", setState in react

### ISSUE THREAD

**Issue by TheLogan** [microsoft/vscode#80853]
- VSCode Version: 1.38.1
- OS Version: win 10

Steps to Reproduce:
1. write react code 
2. await a setState function.

Does this issue occur when all extensions are disabled?: Yes

This is all in all a really small issue, but I imagine it would be confusing for some people.
VSCode essentially reports that the await doesn't actually do anything if placed in front of a setState function in React, however it will actually await the statechange, and so the hint is incorrect.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new)
