### ISSUE TITLE
Show Debug View when the debugger breaks due to an exception

### ISSUE THREAD

**Issue by escamoteur** [microsoft/vscode#80852]
Hi,

I was pretty sure that was covered by https://github.com/microsoft/vscode/issues/49677
But recently I observed it doesn't show the debugger on Exceptions anymore or didn't it do it all the time?
I'm really not sure at the moment.
Anyway it would be much more comfortable if it would switch to the debug pane on exceptions

Thanks for this awesome applications.

**Comment by isidorn** [comment]
This works for me, checkout my gif and let me know what you do differently. 
Also you can F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/db8176cb2b11def79ef93a2dac7d124d0edb9e9a/src/vs/workbench/contrib/debug/browser/debugSession.ts#L710) and debug what is going on.

Also try vscode insiders

![breaks](https://user-images.githubusercontent.com/1926584/64876223-f653f000-d64e-11e9-9027-7f4048dbebc9.gif)

**Comment by escamoteur** [comment]
Check out this screen cast https://www.screencast.com/t/ZtNcK9oCV

**Comment by isidorn** [comment]
As mentioned in my previous comment. Please try to repro with vscode insiders.
Also put a breakpoint where I mentioned and you can investigate more. Since I can not repro on my machine.

**Comment by escamoteur** [comment]
Ok, I have never debugged VS code I don't have the dev tools installed. I will try insiders.

**Comment by escamoteur** [comment]
Insiders behaves the same. 
How do I get to the mentioned file when I open the Developer tools?

**Comment by escamoteur** [comment]
Did you do switch back to the explorer view before the exception?

**Comment by escamoteur** [comment]
@DanTup could you try this when you are back?

**Comment by isidorn** [comment]
Under the sources tab, press ctrl/cmd + P and type debugSession
No I did not switch back to explorer before the exception.

**Comment by escamoteur** [comment]
Could you try that? I think that's when it happens.

**Comment by isidorn** [comment]
I tried that now and it does not repro.

**Comment by DanTup** [comment]
I had a go too, but also can't repro. Using Insiders, and I tried throwing exceptions both in user code and "framework code" in both Dart and Flutter projects.

@escamoteur assuming you can still repro, could you send me a copy of your repro project along with a log (the Debugger/Observatory one) and I'll have a scan through to see if there's any obvious reason I'm not seeing it.

It may also be worth checking you do still have `"debug.openDebug": "openOnDebugBreak",` set, and that there aren't errors or similar in your settings JSON that might cause it not to be set properly.
