### ISSUE TITLE
The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

### ISSUE THREAD

**Issue by snalty** [microsoft/vscode#80855]
Issue Type: <b>Bug</b>

When trying to run any integrated terminal in Code I get an error 

"The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})"

With a log level of trace, I get the following output: 
IPty#spawn C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [] {"name":"powershell.exe","cwd":"C:\\Users\\gensan\\Documents\\Competencies","env":{"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\gensan\\AppData\\Roaming","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"---100918","ComSpec":"C:\\Windows\\system32\\cmd.exe","configsetroot":"C:\\Windows\\ConfigSetRoot","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","ENGL_Machine_Type":"Desktop","ENGL_OS":"win10-ent-x64","ENGL_Project":"Win 10 Ent 1803 (x64)","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\------","IMAGE":"v6.1","IMAGEC":"ZENGL","LOCALAPPDATA":"C:\\Users\\gensan\\AppData\\Local","LOGONSERVER":"\\\\CHALLENGER-1","NUMBER_OF_PROCESSORS":"4","NWLANGUAGE":"ENGLISH","NWUSERNAME":"gensan","OneDrive":"C:\\Users\\Administrator\\OneDrive","OS":"Windows_NT","PAR_GLOBAL_TEMP":"C:\\Apps\\temp","Path":"C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Novell\\ZENworks\\bin;C:\\Program Files (x86)\\Novell\\GroupWise;C:\\Program Files\\Common Files\\Philips Speech Shared\\Components;C:\\Program Files\\PuTTY\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Users\\gensan\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Apps\\MiKTeX 2.9\\miktex\\bin\\x64\\","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 42 Stepping 7, GenuineIntel","PROCESSOR_LEVEL":"6","PROCESSOR_REVISION":"2a07","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SCHSITE":"WIN10","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\Windows","TEMP":"C:\\Users\\gensan\\AppData\\Local\\Temp","TMP":"C:\\Users\\gensan\\AppData\\Local\\Temp","USERDNSDOMAIN":"---.---.UK","USERDOMAIN":"---","USERDOMAIN_ROAMINGPROFILE":"---","USERNAME":"------","USERPROFILE":"C:\\Users\\------","windir":"C:\\Windows","WINDOWS_LOGIN":"0","ZENWORKS_HOME":"C:\\Program Files (x86)\\Novell\\ZENworks","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.38.1","LANG":"en_GB.UTF-8","COLORTERM":"truecolor"},"cols":225,"rows":12,"experimentalUseConpty":false,"conptyInheritCursor":false}
[2019-09-13 10:47:25.443] [renderer1] [debug] Terminal process exit (id: 3) with code Error: Error launching WinPTY agent: winpty-agent CreateProcess failed: cmdline='"\\?\c:\Apps\vscode\resources\app\node_modules.asar.unpacked\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-3076-3-1d56a183f56a0e8-8d77cfe72ed675bfc839c0cbeb5acf01 0 1 225 12' err=0x4ec

And in the develepor tools I get the following:
The terminal process command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})
onDidNotificationChange @ notificationsAlerts.ts:40

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.1.1
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5

(2 theme extensions excluded)

</details>

**Comment by snalty** [comment]
Forgot to add that I am on a locked down user account. Running the zip version from C:/Apps as I am allowed to run executable files from that directory.

**Comment by Tyriar** [comment]
I think this is just how the errors where something blocks winpty from creating the process show themselves now. You need to get your admins to whitelist `c:\Apps\vscode\resources\app\node_modules.asar.unpacked\node-pty\build\Release\winpty-agent.exe`

**Comment by snalty** [comment]
I can run any other executable file from that directory though, which I find a little weird. I'll talk to them though and see what they say.

**Comment by snalty** [comment]
Also, I can run that executable from that folder too.

**Comment by Tyriar** [comment]
Some anti-virus software blocks winpty agent from running which is what creates the terminal process, your options are to get admin to allow it or update to Windows 10 1903 where we've moved off that system and onto one provided by the MS console team.

**Comment by snalty** [comment]
Thanks for the help
