### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by edwinjosekdk** [microsoft/vscode#80857]
Issue Type: <b>Bug</b>

Crashes once in 2 days... and reopens

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.24GB free)|
|Process Argv|C:\xampp\htdocs\Creopedia|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
format-html-in-php|rif|1.6.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Unfortunately it is not enough info to understand what happens in your case.
Could you please provide more details like: if you open some specific project, file, or perform some action right before?
