### ISSUE TITLE
Enable crash reporting on the extension host process

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#80858]
* this is only possible once we adopt Electron 6, in Electron 4 we get the error `Cannot initialize out-of-process crash handler` on Windows.
  * This is possible in Electron 6 because it has adopted crashpad for crash reporting on windows, which aligns with what Chromium was doing.
* this can be implemented easily by defining the crash reporter options for the extension host [here](https://github.com/microsoft/vscode/blob/9b0b5968ad18afe511bde480b6dfb04e48ebc377/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L165)

fyi @bpasero

**Comment by bpasero** [comment]
@alexandrudima this is interesting, from the docs:

> Note: On macOS and windows, Electron uses a new crashpad client for crash collection and reporting. If you want to enable crash reporting, initializing crashpad from the main process using crashReporter.start is required regardless of which process you want to collect crashes from. Once initialized this way, the crashpad handler collects crashes from all processes. You still have to call crashReporter.start from the renderer or child process, otherwise crashes from them will get reported without companyName, productName or any of the extra information.

So indeed it seems like the crashpad service has a way to monitor each process that is child of the main one.

**Comment by bpasero** [comment]
High CPU issue when not starting crash reporter: https://github.com/microsoft/vscode/issues/80913

**Comment by bpasero** [comment]
Crashes are not persisted on disk: https://github.com/electron/electron/issues/20234

**Comment by bpasero** [comment]
I just tried these scenarios on macOS with Electron 7 and still see issues:
* as before, crashes in renderer are not persisted or uploaded
* crashes in child processes are not persisted or uploaded

This time I installed the https://github.com/electron/mini-breakpad-server to have a local endpoint for uploads. It works fine for crashes in main, but not the others.

Reported as https://github.com/electron/electron/issues/22552

**Comment by bpasero** [comment]
@alexdima fyi I introduced a new cli flag `--crash-reporter-directory` that you can add even when running out of sources. It will enable the crash reporter for the extension host (via https://github.com/microsoft/vscode/commit/1648decaef77b762f455b81c9dfb1eff7c38c71f) and setup everything to store crashes locally. 

I think this is actually better than asking the user for the AppCenter crash ID and find the crash there (which we have no proof for works). 

Still, unclear to me if with our current Electron version we get the same results on all platforms but we can start to ask users to try this flag once this is in insiders.

**Comment by bpasero** [comment]
I can a quick test and here is the result triggering a `process.crash()` within the extension host
* Windows: works!
* macOS: no crash dump
* Linux: no crash dump

**Comment by alexdima** [comment]
Thank you, this will be very helpful! ❤️

**Comment by bpasero** [comment]
Update: thanks to @deepak1556 for the hint in https://github.com/microsoft/vscode/issues/97123#issuecomment-625559702, there is also crash dumps on macOS now for extension host process. The crash reporter will be started very early if the `--crash-reporter-directory` option is provided.

I have updated https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to ensure every user goes with this new way first.

**Comment by deepak1556** [comment]
with https://github.com/microsoft/vscode/commit/ffc52d7989332eb37665b45854717b45b8ea30e6 crash dumps for extension host process are generated on linux too.

**Comment by bpasero** [comment]
Cool!

**Comment by alexdima** [comment]
Thank you @bpasero @deepak1556 !
