### ISSUE TITLE
Peek/Go To Definition finds same definitions multiple times

### ISSUE THREAD

**Issue by Holo-Viktor** [microsoft/vscode#80854]
Issue Type: <b>Bug</b>

I have a multi-root project with one of the root folder being a subfolder of the other (main) root folder. (because there is no way to focus or pin folders right now)
I'm not sure if this is causing the problem but Go To Definition always shows the multiple peek view because it finds the same definitions twice.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by aeschli** [comment]
What language?
Can you add a small sample code that shows the issue? Or a screenshot?

**Comment by Holo-Viktor** [comment]
C++, I don't think that the error is related to my specific code, there are no circular deps. Just a header defining a type and another struct is using it in the same header file. Maybe it could be related to the fairly recent "find all references" feature?
![image](https://user-images.githubusercontent.com/43336921/64944839-896b7080-d86f-11e9-9a65-864116998179.png)

**Comment by Holo-Viktor** [comment]
For some reason, Go To Definition works normally but Peek Definition stil does this

**Comment by aeschli** [comment]
It's the C++ extension that provides the 'Go to Definition' and 'Peek Definition' results.
Can you file the issue against the CPP extension? https://github.com/microsoft/vscode-cpptools/issues
