### ISSUE TITLE
Markdown preview problem in Chinese

### ISSUE THREAD

**Issue by WitherZuo** [microsoft/vscode#80864]
- VSCode Version: 1.38.1
- OS Version: Windows 10 18362.10019 (19H2) on Slow Ring

Steps to Reproduce:

1.  Open VSCode and create a Markdown document file.
2.  Switch input method to Simplified Chinese (or Traditional) and type some characters, then make them bold or italic and see them.
3.  You will see some problems like cannot render them correctly in some specific circumstances.
**It's so strange**

Does this issue occur when all extensions are disabled?: Yes  

Screenshot:  
![Snipaste_2019-09-13_21-18-40](https://user-images.githubusercontent.com/25317916/64865544-1e058100-d66c-11e9-85f2-d4f5b3ab2f30.png)  

## Source code md file:  
Download it and open with VSCode, you will see effect like above.
[test.zip](https://github.com/microsoft/vscode/files/3610207/test.zip)

**Comment by WitherZuo** [comment]
I test it with [Typora](typora.io), and it can show and render them normally, so I think maybe a problem of Markdown rendering engine.....

**Comment by WitherZuo** [comment]
**I also test in English, and I found that all text and style can normally render and show.** 
## Screenshot:
![Snipaste_2019-09-14_00-19-00](https://user-images.githubusercontent.com/25317916/64878169-7d23bf80-d685-11e9-994d-9b9448b455a4.png)  

## Source code .md file (THE NEWEST):  
Download it and open with VSCode, you will see effect like above.  
[test-new.zip](https://github.com/microsoft/vscode/files/3610855/test-new.zip)

**Comment by mjbvz** [comment]
Thanks for the example files. Our markdown preview is powered by [markdown-it](https://github.com/markdown-it/markdown-it). After [testing your md file in their online tool](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5Cn%2A%2A这是一段示例文字：%2A%2A如果你看到了左侧这些文字，你会发现它们貌似没有加粗，而且出现了异常的渲染%E3%80%82%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), it looks like this an upstream bug with markdown-it. 

Please file an issue against them: https://github.com/markdown-it/markdown-it

**Comment by WitherZuo** [comment]
I searched all issues in markdown-it issues page, and I found something about this, maybe a serious bug of CommonMark, including Simplifed Chinese and Traditional Chinese.  🤔
[CommonMark Issue](https://github.com/markdown-it/markdown-it/issues/340)
