### ISSUE TITLE
(bug/improvement) Show optional return value null or undefined.

### ISSUE THREAD

**Issue by Domvel** [microsoft/vscode#80860]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
TypeScript: all incl. the latest 3.6.3

Steps to Reproduce:

1. Create a method with optional return value `Something | null`.
2. Hover with the mouse over the method or refer it from another code or file.

You see that the `null` return value is hidden. You can't see that the return value is optional.
See the [Demo on Stackblitz](https://stackblitz.com/edit/typescript-vscode-no-optional-indication-signature?embed=1&file=index.ts)

![vscode-optional-return](https://user-images.githubusercontent.com/35452565/64862973-17f3ae00-d634-11e9-9dfb-953eb207337a.gif)

Does this issue occur when all extensions are disabled?: Yes

Maybe this is a wanted behavior. But I can't understand why. For me it's a bug or should be improved. I want always see if the value can be `null` or `undefined`. This should also be visiable in non-strict mode. - Maybe this is a typescript issue?

**Comment by mjbvz** [comment]
This is because strict null checking is not enabled.

Still, it may make sense to include the `null` or `undefined` in hovers / intellisense even if strict null checking is not enabled. Please [file an issue upstream for this](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
