### ISSUE TITLE
"New  File" from context menu doesn't change active window

### ISSUE THREAD

**Issue by jpmckearin** [microsoft/vscode#80869]
- VSCode Version: 1.38.1
- OS Version: macOS Majave 10.14.6 

Steps to Reproduce:

1. Open VSCode and move to a new space, full screen
2. Open another application to a different space, full screen, and ensure it is the active window
3. Right click the explorer menu and click "New File" in the context menu

Notice that you can not immediately begin typing. The other application will still be considered active.
Also, if you do steps 1 and 2, right click the explorer menu and click "New **Folder**" then the expected behavior occurs where the VSCode window becomes active and the cursor is blinking in the location of the new folder, ready for the user to begin typing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
The issue is that the context menu does not focus the window.
There is already an issue where we discuss this. And this is underneath an electron issue.
Please open an issue in electron or just find the duplicate here and read the discussion
