### ISSUE TITLE
Not building new files!

### ISSUE THREAD

**Issue by uloga** [microsoft/vscode#80866]
Issue Type: <b>Bug</b>
Java / spring boot!
VS Code is not rebuilding when new files are created! It was working before after update it's a nightmare to work with, wasting time googling to fix the issues. Moving to intellij voor everything, used to love vscode for angular and frontend but it's becoming useless by the day! 

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:47:00.464Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (6.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.4.1
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.13.0
rest-client|hum|0.22.0
webpack|jer|2.1.3
azure-account|ms-|0.8.4
Go|ms-|0.11.4
editorconfiggenerator|nep|0.2.1
vscode-spring-boot|Piv|1.10.0
java|red|0.48.0
vscode-xml|red|0.9.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.18.2
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6

</details>

**Comment by uloga** [comment]
You have to clean the workspace every time and restart it to work. How do you guys work at microsoft? Any planning before pushing updates or is it do what ever you want F the people rallying on our product!?

**Comment by aeschli** [comment]
VSCode is just an editor, not an IDE. Build tools are typically run separately in a terminal (external and internal) and it's the build tool that observes file events and re-triggers the build.

Java / spring boot specific enhancement requests need to be filed against the Java / spring boot extensions.
