### ISSUE TITLE
Arrow keys in R terminal

### ISSUE THREAD

**Issue by nwillems94** [microsoft/vscode#80865]
Issue Type: <b>Bug</b>

The arrow keys do not work in the R terminal, but they do in the standard terminal (wsl in my case).
 
Using VS code 1.38.1 and Microsoft R open 3.5.3 in windows 10, setting the option
`"r.rterm.windows": "C:\\Program Files\\Microsoft\\R Open\\R-3.5.3\\bin\\x64\\R.exe"`
the arrow keys (up/down & left/right) do not work in the R interactive terminal. Interestingly, tab complete does work, as do the Ctrl+Home/Ctrl+End shortcuts. 

I also tried setting `"terminal.integrated.shell.windows"` to the same executable and disabling all extensions and had the same problem, which leads me to believe it is not a problem with the R extension. 

I tried the other executables in x64 as well as those in parent directory bin.
I have only the defaults in `"terminal.integrated.commandsToSkipShell"`
Everything works as expected in the prompt when I just launch the executable (not in VS code).

I had the same issue on another Windows 10 machine, VS code 1.38.1, but standard R 3.5.2. I just installed R so I'm not sure if this is an outstanding issue (none open found), or an issue with the latest release

UPDATE: The keyboard navigation keys (CTRL F/B) do actually work, previously I though they did not since CTRL P is a global hotkey in VS code. This leads me to believe this should be a simple fix? Is there a way to control key mapping for the R console?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
r|Iku|1.1.2
latex-workshop|Jam|8.1.1
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
resourcemonitor|mut|1.0.6

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does the same thing happen in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701)?

**Comment by nwillems94** [comment]
Yes it does. But starting from the command prompt and calling the executable file, it does not happen.

In both Windows Terminal and VS code the Ctrl +F,B,P,N work

**Comment by Tyriar** [comment]
If the same thing happens in Windows Terminal then please report here https://github.com/microsoft/terminal/issues

It's probably an issue with the backend "conpty" which vscode and Windows Terminal shares.
