### ISSUE TITLE
New context menu Reopen With is rendered at the bottom

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80863]
I use an extension that helps me copy relative paths. Since many years, `Copy Relative Path` was at the bottom of the context menu. After today's update, it is the one behind last and that is annoying to me because I click the wrong action:

![image](https://user-images.githubusercontent.com/5047891/64865480-a74f9000-d639-11e9-9f6d-2676768c7169.png)

fyi @bpasero

**Comment by gjsjohnmurray** [comment]
@alexandrudima  I'm interested that "Copy Relative Path" appears twice in your screenshot. Is one contributed by the extension you referred to, and the other a built-in feature of VSCode?

**Comment by alexandrudima** [comment]
Yes, I wrote my extension many years ago :), and then @bpasero added it to the core I think... I don't like the one built-in because it keeps `\` on Windows...

**Comment by bpasero** [comment]
@mjbvz I would expect "Reopen with" only in the explorer, not the tabs. Let's try to keep these menus unclutterd if possible.

**Comment by gjsjohnmurray** [comment]
> Let's try to keep these menus unclutterd if possible.

Agreed. Especially until we get the ability to have submenus 🙏

**Comment by mjbvz** [comment]
Yes it will not ship for 1.39 like this. I'm still doing a lot of UX exploration for custom editors and having this command has been helpful

I do think we will want a `reopen` action somewhere on the editor itself, although this action should not show up if there are no other editors available for that resource (only images should have custom editors currently). We could also move `reopen with` to be a toolbar item instead

**Comment by bpasero** [comment]
> I do think we will want a reopen action somewhere on the editor itself

I am not sure I would agree. To me the editor is not about opening something but working with the content. The actions should be targeted to the content of the editor. Having the action in the explorer is right imho.
