### ISSUE TITLE
Add option for running the logger with flushing to disk after each log call

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80862]
It is currently very difficult to troubleshoot crashing extension host issues because the logs could be missing data that was not synchronously flushed to disk after each log call.

**Comment by alexandrudima** [comment]
@joaomoreno @sandy081 Could you please squeeze this in for September? I would like to enable the extension host to always use synchronous flushing to disk after each log call so I can troubleshoot crashes...

**Comment by joaomoreno** [comment]
I think we should do this with an env variable or cli argument, since as a setting we might not be able to read it as early as we'd like at startup and we'd only want this for troubleshooting. My preference would be with an env variable, since that propagates effortlessly. Is that OK @alexandrudima?

**Comment by alexandrudima** [comment]
@joaomoreno I would hard-code the extension host to always use synchronous flushing. 

TBH I don't understand why one would ever use logging without synchronously flushing ^^

**Comment by sandy081** [comment]
Because this will block every time a log statement is written. I cannot say how much it will impact the perf but why do not this is optional and enable this only when needed?

**Comment by sandy081** [comment]
Anyways, I have added a constructor option `sync` in `SpdLogService` which is false by default. Passing `true` will flush the log after each call - d34109e2ba87ce3df3e7a77a8beccf1bd606357f

**Comment by sandy081** [comment]
As discussed exposed `flush` method on `logService` to flush logs.

**Comment by alexandrudima** [comment]
Thank you! :heart:
