### ISSUE TITLE
feature request: save all event/trigger

### ISSUE THREAD

**Issue by imthenachoman** [microsoft/vscode#80868]
I would like an event for save-all. There is one for `onDidSaveTextDocument` but, based on my understanding of what the documentation says, that will trigger for every file that is saved.

It would be helpful to have an event for save-all if we need to do specific things only when all files are saved. 

Reference: https://code.visualstudio.com/api/references/vscode-api

**Comment by jrieken** [comment]
This is slightly related to https://github.com/microsoft/vscode/issues/43768 but generally nothing we can do as files aren't saved in one go, we always save file after file and when saving all files there is nothing the prevents another save from occurring. 

> It would be helpful to have an event for save-all if

What exactly is that use-case that requires this? In case you need to know if there are still some unsaved files you can iterate over all text documents and check for [`isDirty`](https://github.com/microsoft/vscode/blob/3fd9684eb554d57f34730e28fe8b76f95da5d73d/src/vs/vscode.d.ts#L128) - that probably the best option for knowing if all saves are written to disk.

**Comment by imthenachoman** [comment]
Then how about an `after save all` event. It wouldn't interfere with the actual saving of the files. The goal is to be able to do something special after all the files are saved. For example, say I am editing 5 files in a project. I don't want to do anything when just one file is saved, I want to do something after all of them are saved.

I know I can use the single on save and iterate through all files to see if any are still un-saved, and this works for now but I think a single event for `after save all` would be more efficient.

**Comment by jrieken** [comment]
> and this works for now but I think a single event for after save all would be more efficient.

Not really - the `onDidSave` and `onDidChange` events are send anyways and if you don't wanna iterate over existing documents then you can use the latter event (which is also fired when documents change dirty state) to increment/decrement a counter. 

I think that's a fair workaround. Generally we try to keep the API small and given the unclarity with a "saved-all-files"-event it's very unlikely that we are going to att it.

**Comment by imthenachoman** [comment]
Is there a fast way to find if there are any unsaved/dirty files? I don't see how `onDidChange` would work. Say you have hundreds of files open for a project, some dirty, some not. Say you want to run some command when all are saved (pushing all the files somewhere for example) then if you use `onDidSave` then you'll have to iterate through all of the open files to see if there are any dirty ones. I mean I am sure it is fast but efficiency is always better. `onDidChange` wouldn't help cause the goal is to do something after all the files are saved.

I disagree with your rational but we'll have to agree to disagree and I understand if y'all don't want to implement this.

**Comment by jrieken** [comment]
> onDidChange wouldn't help cause the goal is to do something after all the files are saved.

You use `onDidChange` to update a data structure (a counter, maybe a set?) that allows you to quickly answer the question if an unsaved files exists. Then during the `onDidSave` event you used that data structure and, voila, no iteration needed.

**Comment by imthenachoman** [comment]
Doesn't `onDidChange` fire every time a file is edited? Wouldn't it be easier and more efficient to just iterate? I guess it depends on how many files you have open.

Either way, on my to do list is to create a new extension to work with Google Apps Script. Something more integrated then making external calls to `clasp`. When I get to writing it I'll figure out the best way to address the need I mentioned in this issue.

**Comment by jrieken** [comment]
Closed as dev question - there are two solutions to know if there are unsaved buffers and that should be enough ;-)

**Comment by imthenachoman** [comment]
Thanks @jrieken. I will check out the Slack group when I get time to sit down start working on it. Based on current capacity I think I'll have time in 2040. :P
