### ISSUE TITLE
Terminal on-load screen errors

### ISSUE THREAD

**Issue by clfaulkner** [microsoft/vscode#80878]
Issue Type: <b>Bug</b>

I get 2 screen errors when starting a new terminal session. These occur no matter how the new terminal is started (menu, right-click filename, etc.). The first problem is the terminal window is blank until I type a command; that is, there is no prompt. When I type a command (any command), the prompt magically appears.

Second, certain command line elements do not appear on the screen. For example, when I type "Set-ExecutionPolicy -ExecutionPolicy bypass -scope process" some of the words do not appear on the screen.

I have screen shots of both errors, if you need them.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (2.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-ionic-snippets|fiv|1.6.0
docthis|joe|0.7.1
Angular2|joh|8.1.1
material-icon-theme|PKi|3.9.0
open-in-browser|tec|2.0.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it related to PowerShell (I guess) or other terminals also has similar problems?

**Comment by clfaulkner** [comment]
It is related to both PowerShell and Windows CMD. Do you need the screen
shots?

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by clfaulkner** [comment]
Actually, I switched to Git-Bash as my terminal and it starts up just fine.
Problem solved for now.
Thank you. 🙂
