### ISSUE TITLE
Make it more obvious branch is ahead of origin

### ISSUE THREAD

**Issue by chucklepie** [microsoft/vscode#80879]
After committing changes to git, it's not really very obvious that you are ahead of origin and need to push. In the 'source control providers' section you get a tiny grey icon beside master/sync with a number.

It would be far better to have a clear idea of changes, such like that shown when you have changes or staged and uncommited changes.

**Comment by IllusionMH** [comment]
VSCode already provides info about current git branch and status in Status bar
![image](https://user-images.githubusercontent.com/1312662/64880660-64a1ae00-d661-11e9-972b-b3d2d19c5392.png)

**Comment by chucklepie** [comment]
What you've done is zoomed up the image a lot. This isn't obvious or easily read on a full screen. Or put it another way why can't it be as prominent as the information showing when the working folder or index has changed with their own sections?

**Comment by IllusionMH** [comment]
> What you've done is zoomed up the image a lot.

It's just difference in screens DPI, it has same size (a bit bigger font) then tree item.

This component has same position from editor release and doesn't depend on whether you have VCS open.
Anyway its up to developers to decide if duplicate functionality of this component is needed.

**Comment by joaomoreno** [comment]
Closing as implemented.
