### ISSUE TITLE
Can't run NPM SCRIPTS when using WSL as default shell

### ISSUE THREAD

**Issue by sebolio** [microsoft/vscode#80875]
- VSCode Version: 1.38.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1.  Open integrated terminal and set default to WSL
2.  Open a NodeJS project with at least one task in the `package.json` file
3.  Try to run any of the tasks, you'll get "The terminal process terminated with exit code: 1"

If you set your integrated terminal to CMD.EXE this will work perfectly (if you have nodejs for windows installed, of course)

Apparently it's trying to send `/d /c npm run` parameters to the shell, which are not supported by WSL executable. Tried setting `terminal.integrated.shell.windows` to "wsl" and it throws:
> The terminal process command 'wsl/d /c npm run front' failed to launch (exit code: {2})
 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexr00** [comment]
I have the following task in the [hello world sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample):
```
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
```
I set:
`    "terminal.integrated.shell.windows": "wsl.exe",`
The tasks works as expected. 

@sebolio can you clone that extension sample and try it? I have Windows version 1909, so it is possible that has something to do with it.
