### ISSUE TITLE
Settings GUI randomly stopped showing text entry fields

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#80877]
Issue Type: <b>Feature</b>

It's quite confusing how the C/C++ settings are supposed to be set. When open VS Code Settings UI, C/C++ settings appear when going to that extension, but sadly, are not GUI friendly, with many "Edit settings.json" links appearing instead of text entry fields. It's quite confusing when trying to remember how to change/fix settings for C/C++ because the entry fields are missing but you remember them being there... from the C/C++ Edit Configuration (UI) command.

It would be great if these could be somehow better integrated or a very visible message would make this clear in case a user happens to be lost and confused trying to sort things out in two (or really, multiple!) places with overlapping settings names.

**Comment by aeschli** [comment]
Can you file it against the C++ extension? https://github.com/microsoft/vscode-cpptools/issues
