### ISSUE TITLE
API for extensions to reuse the Replace Preview

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode#80876]
In Visual Studio, the Visual C++ team is able to show a preview of the symbols that will be renamed during a rename operation.  Like this:
![image](https://user-images.githubusercontent.com/12818240/64875315-af8bd900-d601-11e9-95ec-efbceaeb01c2.png)

This allows us to include suggestions of additional matches for the rename operation that we may not be 100% confident about.

VS Code also has the capability to show a preview of changes for find/replace that would be cool if the C++ extension team could reuse for our implementation of "rename."  It would allow us to show a preview of the pending changes inside the file so that developers could more easily view the context in which the additional rename suggestions reside.
![image](https://user-images.githubusercontent.com/12818240/64875582-4193e180-d602-11e9-83d0-a77aaaf41920.png)

**Comment by sandy081** [comment]
@bobbrow Not sure if I understood your requirement. 

We already have preview for Global Search / Replace. Are you asking for some change here? Or
Are you asking for a rename preview? Or
Are you asking for find/replace preview?

**Comment by bobbrow** [comment]
We are building an experience around "rename" that allows the user to intercept the operation and include or reject matches that we have less confidence about:

![image](https://user-images.githubusercontent.com/12818240/65892987-13c9cf00-e35c-11e9-8cfc-a59102969593.png)

Since this is a kind of "preview", we thought it would be awesome if we could open up a "rename preview" editor when items are selected in the tree view - similar to what you have for find/replace. So we're asking for the preview editor to be extensible or callable in some way such that we can use it.

**Comment by sandy081** [comment]
find/replace uses the normal diff editor which I think is accessible through API.

@alexandrudima Is this correct? If so please let user know how a diff editor can be accessed.

**Comment by alexandrudima** [comment]
It is possible to invoke the `vscode.diff` command and pass two URIs that use a custom scheme like e.g. `file:///real/file/before/rename.cpp` and `my-custom-scheme://file/after/rename.cpp`. Then you can contribute a FS provider or content provider for `my-custom-scheme` and provide the shape of the file after the edit.

On top perhaps you can contribute a custom tree view to show all the files that the rename would change. 

However @jrieken @egamma I don't know if this is something we want to encourage every extension to build an UI for or if we should build a centralized "rename with preview" feature...

**Comment by jrieken** [comment]
> However @jrieken @egamma I don't know if this is something we want to encourage every extension to build an UI for or if we should build a centralized "rename with preview" feature...

Yeah, it should be better to have just one rename experience, not one per language. @bobbrow What are you missing from the current rename flow and API. Are there issues/PRs that we don't have on our radar?

**Comment by bobbrow** [comment]
@jrieken, to be clear, we're not currently missing anything \*essential\* from the current rename flow and API. We are building a custom experience for Rename just like we do for Find All References due to the challenges C++ presents for these features, so we are unsure as to whether it makes sense for you to build a feature just for us. We can try out @alexandrudima's suggestion.

Most other language servers don't seem to need a preview because they have higher certainty of their results.  Though I suppose it might make sense to have this feature for other languages if they wanted to include less certain results in the operation such as string and comment renames like we are offering.

**Comment by jrieken** [comment]
> [...] experience for Rename just like we do for Find All References due to the challenges C++ presents for these features,

Well, I'd say that actually means that you are missing something from the rename/find references experiences... Let me try to explain why I think it's a bad idea to implement custom features that already exist (to some extend) in VS Code

1. If in VS Code we will add "preview-before-rename" than your time was wasted
1. Users will have to learn that rename in C++ is ever so slightly different
1. The extension API isn't designed to allow to implement custom UX flows which means that you are having a harder time than necessary
1. VS Code is open source, if you miss a feature you can add it to the real thing instead of doing a one-off solution that only help a subset of people

**Comment by jrieken** [comment]
Closing this as dev-question but I also want to restate that we aren't happy when extensions invent competing features.
