### ISSUE TITLE
Please increase the indentation in the Explorer folder hierarchy a bit

### ISSUE THREAD

**Issue by escamoteur** [microsoft/vscode#80872]
Hi,

when looking at the folder structure in the explorer view I find it sometimes difficult to distinguish if a File is inside a sub folder or outside see:

![image](https://user-images.githubusercontent.com/16635729/64872872-467b8400-d648-11e9-86c3-8b6a7e893f12.png)

It would much easier if that indentation were some pixel bigger.

**Comment by IllusionMH** [comment]
Have you tried to set `workbench.tree.indent` in Settings?

**Comment by escamoteur** [comment]
Thanks a lot, that solved it. Awesome how flexible Code is
