### ISSUE TITLE
Support QuickDiffProvider without SourceControl

### ISSUE THREAD

**Issue by nbransby** [microsoft/vscode#80870]
I have a requirement to show a quick diff on a document from a custom TextDocumentContentProvider. Currently the only way to do this is to create a new SourceControl which also affects the Source Control UI.

Is it possible to expose a quickDiffProvider property on either a document or editor level so its possible to use without affecting the Source Control UI.

**Comment by joelpryde** [comment]
This would be incredibly useful.  I've been looking for this functionality as well.
