### ISSUE TITLE
Autocompletion blocks the IDE

### ISSUE THREAD

**Issue by cruzortiz99** [microsoft/vscode#80873]
Issue Type: <b>Performance Issue</b>

Usually happens when the autocompletion is writing the option selected. Blocks the screen like for a second or two, some times more. Using emmet for autocompletion also blocks the screen, and other languages autocompletions

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.13.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3068)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (8.75GB free)|
|Process Argv|--new-window|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	  9189	code main
    0	    31	  9193	   zygote
    0	    94	  9301	     shared-process
    0	     0	 11428	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 11429	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   204	 11255	     window (● Arrays.tsx - tsc_react_express_app - Visual Studio Code)
    0	   110	 11289	       extensionHost
    0	    94	 11321	         electron_node tsserver.js 
    0	   220	 11323	         electron_node tsserver.js 
    0	    79	 11353	           electron_node typingsInstaller.js typesMap.js 
    0	    63	 11383	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=11289
    0	    63	 11306	       watcherService
    1	    79	 11405	     window (Issue Reporter)
    0	   110	  9222	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● Arrays.tsx - tsc_react_express_app - Visual Studio Code)
|    Folder (tsc_react_express_app): 182 files
|      File types: js(40) map(39) tsx(39) css(10) json(3) ts(2) prettierrc(1)
|                  eslintrc(1) html(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1) webpack.config.js(1);
```

</details>
Extensions: none

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
