### ISSUE TITLE
Snippet descriptions are hardly readable due to bad word break handling

### ISSUE THREAD

**Issue by Grafu** [microsoft/vscode#80874]
- VSCode Version: 1.38.1
- OS Version: Windows 10 Pro 1809

Steps to Reproduce:

1. Open a longer snipper with description.
2. Try to read the text. It is unconfortable for me.

![image](https://user-images.githubusercontent.com/11540828/64873389-9dd22200-d651-11e9-9cff-9222ad8821c0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux
