### ISSUE TITLE
Can't open a script on Unity

### ISSUE THREAD

**Issue by ProvencalG** [microsoft/vscode#80884]
I'm opening a Unity project, which has the latest Visual Studio Code Editor package, when I double click on a script it does not open. In Unity Preferences/External Tools, I set the External Script Editor to Visual Studio Code.

If I open VS Code and "open file..." to open a script in the Unity project folder it still does not work.

What is weird is that other Unity projects work and that this bug in suddenly appearing, I was working properly on that project before.

**Comment by ProvencalG** [comment]
I'm using Unity 2019.2.0f1.

**Comment by ProvencalG** [comment]
It was a Rider package that blocked VS Code, I uninstalled it and it works now.

**Comment by coreyjs** [comment]
I also ran into this problem with this version and 2019.2.6.  No solution works.

**Comment by max-pi** [comment]
Just started happening to me.  Yesterday was fine.

It seems to only affect specific projects, as other projects open VS code fine..

**Comment by max-pi** [comment]
@ProvencalG what is a Rider package? Could you explain how you got rid of the issue

**Comment by coreyjs** [comment]
I had a rogue vscode process. So I manually killed any process related to vscode and it’s launcher. It solved it. It happens from time to time and this still works.

**Comment by max-pi** [comment]
ah resolved for me as well
I was confused as restarting computer didnt seem to help, but ending vs code through taskmanager seems to have done the trick
Thanks!
