### ISSUE TITLE
f11 key (full screen) does nto work with flutter emulator

### ISSUE THREAD

**Issue by PauloPortfolio** [microsoft/vscode#80883]
Issue Type: <b>Bug</b>

When I press 'f11' to go 'full screen' mode, I am not able to achieve that because Flutter Emulator is working. Therefore, I need to close flutter emulator, and after go to 'Full Screen' mode, when I do that, I can leave 'full screen' mode.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
dart-code|Dar|3.4.1
flutter|Dar|3.4.1
git-graph|mhu|1.15.0
material-icon-theme|PKi|3.9.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Os it a problem with the Flutter Emulator ?

**Comment by PauloPortfolio** [comment]
Yes,

**Comment by chrmarti** [comment]
Closing as this is not an issue with VS Code.
