### ISSUE TITLE
Autosave file after resolve merge conflicts 

### ISSUE THREAD

**Issue by GusGA** [microsoft/vscode#80881]
It would be great if after resolve a git conflict inside vscode, accepts or deny the incoming changes the editor autosave the file without the need to press Control/Command + S.

Will save a lot of headaches since will avoid pushing files without fix.

**Comment by danielo515** [comment]
This is a great source of bugs for me too.
Will love to see this proposal implemented.

**Comment by GusGA** [comment]
This was fixed in version `1.70.0`, I tried and save the file after solve the conflict.

thanks
