### ISSUE TITLE
auto import error

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#80886]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

Steps to Reproduce:

1. open your react project
2. yarn add lodash
3. create a js file
4. type `import isEmp` then select the auto complete
5. you will get this `import {isEmpty} from 'lodash/isEmpty'`

this is wrong

It should be `import isEmpty from 'lodash/isEmpty'`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Are you sure you don't have any extensions enabled? Our built-in js/ts intellisense does not provide suggestions after you type `import isEmp`

**Comment by craigcosmo** [comment]
Nope

Craig

________________________________

**Comment by mjbvz** [comment]
I don't understand the actions you are taking to trigger this issue. Please share a screen recording or screenshots along with the key presses

**Comment by mjbvz** [comment]
Closing this as our builtin extensions do not provide the intellisense in the way described. This must be coming from an extension
