### ISSUE TITLE
Git repositories should be more informative on the remotes

### ISSUE THREAD

**Issue by chucklepie** [microsoft/vscode#80880]
In the git tab, it lists all the repositories (Source Control Providers), but there is nowhere that actually lets you know what the actual remote server(s) is/are. You have to resort to going to the command line and entering 'git remote -v'.

For example in GitLens extension this makes it quite clear by listing the url right  next to the remote alias and providing a hover hint with full fetch/push details.

for example, this is all you see in Git
![image](https://user-images.githubusercontent.com/12863685/64878224-efc37980-d64a-11e9-9428-9834ce3caff7.png)

but this is what you see in git lens
![image](https://user-images.githubusercontent.com/12863685/64878198-e20df400-d64a-11e9-8b3e-4d21c7953ab1.png)

**Comment by joaomoreno** [comment]
Closing with the recommendation to use GitLens.
