### ISSUE TITLE
update import does not update scss

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#80887]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

Steps to Reproduce:

1. When you change scss file in react project
2. The import will not update

Does this issue occur when all extensions are disabled?: Yes

**Comment by craigcosmo** [comment]
this is not a duplicate mate

**Comment by aeschli** [comment]
The import in the SCSS file?

**Comment by craigcosmo** [comment]
`app.js`
```js
import './header.scss'
```

now change file name `header.scss` to `accountHeader.scss`. the import wont auto update

**Comment by octref** [comment]
Only TypeScript language server would have the ability to update the imports. You can open an issue for TS, but I doubt they would consider it as it's something dependent on your setup (webpack loaders etc) but not the language itself.
