### ISSUE TITLE
PATH to VS Code bin directory

### ISSUE THREAD

**Issue by jimf5** [microsoft/vscode#80882]
Issue Type: <b>Feature Request</b>

Use the system variable instead of an absolute path to MS VS Code bin directory in the PATH environment variable when installing MS VSCode on Windows.
e.g. use %UserProfile%\AppData\Local\Programs\Microsoft VS Code\bin
instead of
C:\Users\someuser\AppData\Local\Programs\Microsoft VS Code\bin

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v5 @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (36.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.2
gitlens|eam|9.9.3
git-project-manager|fel|1.7.1
terraform|mau|1.4.0
ecdc|mit|1.3.0
vscode-docker|ms-|0.8.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34911
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.25.1
vscode-yaml|red|0.5.2
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.7.18
rf-intellisense|Tom|2.6.0
jinja|who|0.0.8
change-case|wma|1.0.0

</details>

**Comment by joaomoreno** [comment]
Closing as won't fix. The variable will be set with the value where Code is installed to.
