### ISSUE TITLE
Semantic Completion Snippets

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#80890]
No idea if this is feasible, but it'd be nice to have the ability to tap into semantic suggestions and modify what's inserted when that suggestion is accepted.

Obviously we already have the ability to add our own snippets, but since they aren't semantic, they just appear on character match, causing them to bloat the suggestion list.

Preferably, we could tap into JavaScript's `reduce` completion, for example. And instead of getting the default snippet, `arr.reduce(${0:callbackfn})`, we could customize it to get `arr.reduce((${1:accumulator}, ${2:currentValue}) => { $0 });`

**Comment by jrieken** [comment]
For JS/TS specifically you can add a server plugin that allows you you to do exactly that. As for a generic solution you would need to write an extension that registers a completion item provider that returns semantic snippets. Generic customisations like changing or removing suggestions from extension A by extension B isn't something we want.
