### ISSUE TITLE
MDN Reference

### ISSUE THREAD

**Issue by TABv1** [microsoft/vscode#80894]
Issue Type: <b>Bug</b>

How do I turn this off.  Seriously, it pops up so fast that I am constantly being asked if I want to go to the damn website.  Frustrating.  Where do I turn it off!!!

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by octref** [comment]
Command Palette -> "Configure Trusted Domains for Link Protection" -> select "Open all links without prompt"

![image](https://user-images.githubusercontent.com/4033249/64970728-3982ae80-d85b-11e9-9fff-d35585af3bf8.png)

**Comment by TABv1** [comment]
I guess you really did not understand what I am asking.  How do I turn off the MDN Reference hover pop-up box.  I do not want it to show period.  Then we do not have to worry about accidentally clicking on any links, which, now that I can see what you are showing should be turned off 100% as well.

**Comment by octref** [comment]
There's a small close-box (you can toggle with Ctrl+Space again as well) to close it, so it changes from

![image](https://user-images.githubusercontent.com/4033249/64972895-f0345e00-d85e-11e9-99ab-c43a92a9af62.png)

to

![image](https://user-images.githubusercontent.com/4033249/64972923-faeef300-d85e-11e9-89b3-4e61a90c2856.png)

**Comment by TABv1** [comment]
Hi,  I am talking about this.

![Annotation 2019-09-16 090151](https://user-images.githubusercontent.com/21066267/64973878-a8aed180-d860-11e9-8a3f-e52e5566cad4.png)

It pops up too quickly.  I would prefer to turn it off completely.

**Comment by octref** [comment]
You can control that in `editor.hover.delay` and `editor.hover.enabled`

![image](https://user-images.githubusercontent.com/4033249/64977330-08f54180-d868-11e9-95af-9ffc465aec22.png)

**Comment by TABv1** [comment]
Perfect.  Closed

**Comment by markdavies** [comment]
Sweet relief! My gawd that popup was annoying

**Comment by tim92109** [comment]
That's just plain ignorant to have something that pops up by default, telling you what a basic CSS property does, and causes you to accidentally navigate to a page you don't want to go to. Poor UX, VScode!
