### ISSUE TITLE
Once released new version, please tag it. like 0.10.2

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#809]
Once released new version, please tag it. like 0.10.2

https://github.com/Microsoft/vscode/releases

Can not see 0.10.2 tag here

**Comment by jpierson** [comment]
+1 I checked the same thing as soon as I got the update and was somewhat disappointed that it wasn't in sync.

**Comment by egamma** [comment]
We need to document our branching policy in the wiki. We continue working on master and cherry pick changes into a release branch https://github.com/Microsoft/vscode/tree/release/0.10.2.

**Comment by alexandrudima** [comment]
@aeschli @joaomoreno should we convert the branches to tags once we have finished a release

**Comment by netroby** [comment]
I guess the progress is not working correct. You released a new 0.10.2 version . the tag must be done before it real released. 
Or you can call your working branch as 0.10.3.

The tag 0.10.2 must equals to what you already released. that's the right way to get tags meanful.

**Comment by aeschli** [comment]
I removed the 0.10.2 branch and created a 0.10.2 release.
I update our (for now internal) release checklist on OneNote ('0.10.X Fix Release Template')
@bpasero FYI

**Comment by alexandrudima** [comment]
@netroby Here is our process for making a release:
 1. we use a branch, e.g. 0.10.2
 2. then we build VSCode on that branch
 3. then do cross OS smoke testing
 4. then if we identify any critical issues we deliver fixes to the branch and repeat from step 2.
 5. when step 3 yields no additional critical (ship-blockers) issues we're done
 6. [we forgot this one] "convert" the branch into a tag

**Comment by egamma** [comment]
Captured in the wiki https://github.com/Microsoft/vscode/wiki/Releases-and-Branches

**Comment by jpierson** [comment]
An update came through for 0.10.3 today but again there is no tag.

**Comment by netroby** [comment]
Said again. You need tag first , then release new version. 

The code must be freeze , then you can released .

**Comment by bpasero** [comment]
Release 0.10.3 is out: https://github.com/Microsoft/vscode/releases
