### ISSUE TITLE
Move the stepping controls over to the start debugging button section.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/vscode#80907]
Issue Type: <b>Feature Request</b>

When I start debugging, the stepping controls are shown over the top of the tabs, blocking the tabs! That's obviously a poor design. Why not just have them show up directly underneath the debug / play button.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
`"debug.toolBarLocation": "docked"`

**Comment by Gavin-Williams** [comment]
Great, thank you John.
