### ISSUE TITLE
The extension host is crashing

### ISSUE THREAD

**Issue by aboodh95** [microsoft/vscode#80909]
Issue Type: <b>Bug</b>

Hi,

Recently I'm facing an issue, that the extension host is crashing, I don't know from where i can get a log to know which extension is responsible for this issue, to solve the issue I have to click on Restart Extension Host

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
terminal-commands|adr|1.0.5
vscode-json|and|1.5.0
azds|azu|1.0.120190904
jsonviewer|cci|1.2.2
compulim-vscode-closetag|Com|1.2.0
githistory|don|0.4.6
xml|Dot|2.5.0
vscode-generate-getter-setter|DSK|0.5.0
tslint|eg2|1.0.44
json-tools|eri|1.0.2
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
ftp-simple|hum|0.7.0
vstsbuildstatus|jep|0.7.1
vstsservicestatus|jep|1.3.0
vscode-peacock|joh|3.1.5
minifyall|jos|1.3.9
docomment|k--|0.1.8
chat|kar|0.21.1
vscode-github|Kni|0.30.2
json-to-ts|Mar|1.5.5
git-graph|mhu|1.15.0
xml-format|mik|1.0.2
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.15.0
vscode-azurestorage|ms-|0.7.1
mssql|ms-|1.6.0
python|ms-|2019.9.34911
vscode-ai|ms-|0.6.3
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
csharp|ms-|1.21.2
vsliveshare|ms-|1.0.809
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.7
vscode-json-editor|nic|0.2.3
fix-json|oli|0.1.2
open-html-in-browser|pea|1.3.0
qub-xml-vscode|qub|1.2.8
typescript-hero|rbb|3.0.0
vscode-xml|red|0.9.0
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.18
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.1.9
vscode-wakatime|Wak|2.2.0
json|Zai|1.0.2

</details>

**Comment by alexandrudima** [comment]
We have seen a lot of issues coming in for crashes caused by `karigari.chat`. See https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205 .  Can you try to disable it?

**Comment by aboodh95** [comment]
Hi,

The problem still exists, i open the developer tool and i got this error,
`Error: Uncaught (in promise): Failed to execute git {  "exitCode": 128,  "gitCommand": "rev-parse",  "stdout": "",  "stderr": "fatal: no upstream configured for branch 'quotelineassetDeprecating'\n"}	at new AppInsightsAsyncCorrelatedErrorWrapper (c:\Users\AbdulmonaemAlhamwi\.vscode\extensions\qub.qub-xml-vscode-1.2.8\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)	at resolvePromise (c:\Users\AbdulmonaemAlhamwi\.vscode\extensions\qub.qub-xml-vscode-1.2.8\node_modules\zone.js\dist\zone-node.js:501:31)	at Function.ZoneAwarePromise.reject (c:\Users\AbdulmonaemAlhamwi\.vscode\extensions\qub.qub-xml-vscode-1.2.8\node_modules\zone.js\dist\zone-node.js:564:20)	at t.Git._exec (c:\Users\AbdulmonaemAlhamwi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:30386)`

i will try to disable the git extinction and wait for result

**Comment by aboodh95** [comment]
I will test it for 2 days and give you the result

**Comment by alexandrudima** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!

**Comment by aboodh95** [comment]
Hi,

So far it's not appearing in the vs code insider
