### ISSUE TITLE
Add "Uninstall and remove all data" option for removing extensions

### ISSUE THREAD

**Issue by seva0stapenko** [microsoft/vscode#80904]
Current observed behavior of VS Code (as of 1.38.1) is to keep extension folder and all its contents when extension is uninstalled (observed with ms-python.* extension specifically).
If an extension is subsequently re-installed, existing extension folders are simply reused (apparently without integrity checking).
If extensions folder becomes corrupt for whatever reason, uninstalling and reinstalling extension just preserves corrupted state of the extension, complicating the situation and frustrating the user (see https://github.com/microsoft/vscode-python/issues/7348 issue for additional details on user experience and observed behavior with extension uninstall/reinstall).

It can be argued, that "uninstall" behavior should be "uninstall and wipe out clean" by default, yet, having one more explicit option to "uninstall an remove all data" for an extension should suffice as well.

**Comment by sandy081** [comment]
There is a command `Developer: Reinstall Extension` which does the same as you requested.
