### ISSUE TITLE
Unable to activate VS Code extension

### ISSUE THREAD

**Issue by ankitgupta51** [microsoft/vscode#80901]
I'm getting this error in the console when i updated my VS Code to 1.38.1
 from 1.37 yesterday and now all my salesforce extensions are no longer working . The error in the console is **Cannot activate extension 'Apex Interactive Debugger' because it depends on extension 'salesforce.salesforcedx-vscode-apex', which failed to activate.**

Can someone please help? I tried installing and uninstalling multiple times and reverted to older version but still not working. Same error.
![Screen Shot 2019-09-13 at 8 33 40 PM](https://user-images.githubusercontent.com/3982755/64901361-4d18f400-d666-11e9-8f7a-88a77a68bad9.png)

**Comment by kieferrm** [comment]
I can't tell why `salesforce.salesforcedx-vscode-apex` failed to activate. Please file the issue against the salesforce extension. Thank you!
