### ISSUE TITLE
Search and replaced for almost 380+ files in my project overwrites the files to 0 bytes and the code base disappeared

### ISSUE THREAD

**Issue by rajesh-kc** [microsoft/vscode#80918]
- VSCode Version: 1.38.0
- OS Version: Linux Ubuntu 18.04

Steps to Reproduce:

1. Click on the Search icon, used search and replace in the project root directory
2. Code base in all the files were truncated and nothing found further

Search identified nearly 385 files. When tried to replace, the vscode editor became unresponsive. Now all my entire week's work is gone. Unable to recover the code base in any way. This is the first time happened in my first time during the 8 years of my IT experience. Been using Vscode since past 6 months.

How am i able to answer to my boss & client. They will never get convinced with my explanation.

The error is similar to https://github.com/microsoft/vscode/issues/71489

No solution found

**Comment by roblourens** [comment]
I'm very sorry this happened. Is your disk nearly full? Did vscode stop responding during the replace operation?

Also related to https://github.com/microsoft/vscode/issues/34915

**Comment by rajesh-kc** [comment]
There is lot of diskspace. more than 50gb storage capacity available with 12gb ram. When trying to replace more than 380+ files at a time, the vscode editor became un-responsive. When the editor is reloaded- all the 380+ files were truncated to 0 bytes. Only those files where the search & replace operation took place where effected.

**Comment by roblourens** [comment]
If you are able to recover your code base at all, like from a backup, does this happen if you try the same search/replace again?

**Comment by rajesh-kc** [comment]
I would not be able to test it for you, as i am no longer using vscode anymore. I have done my job by reporting this issue here, immeditely after i found the bug. Further, it would be your turn wether to test on the bug or not and possibly take steps towards resolving it.

Have a good day!
