### ISSUE TITLE
Desaturated colors interface

### ISSUE THREAD

**Issue by Cyberpaul88** [microsoft/vscode#80914]
- VSCode Version: 1.38
- OS Version: windows 10 x64

I've just installed VS Code and there's already a problem.

The interface colors looks desaturated and hard to read.
I tried to take a screenshot, but it comes out with regular brightness.

Can you help me please?

**Comment by infctr** [comment]
I've just updated to 1.39.0-insider 9f6a745027fc7b2a12495970f64625e24f410224 and the interface looks strikingly desaturated. 

@Cyberpaul88 have you found a fix for your issue?

**Comment by Cyberpaul88** [comment]
Yes, I had to **TURN OFF** Windows HD Color. Not the best solution, but it works.
