### ISSUE TITLE
Validate extension folders consistency on extension reinstall, re-enable and update

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#80911]
Reported by @seva0stapenko 

Currently observed VS Code behavior is such that uninstalling an extension does not remove the extension folder (extensions/ms-python.*). On the extension reinstall, existing folders are blindly reused.
If extension folder contents become corrupted (e.g. missing netcore files) corruption will persist across extension removal/re-install cycles as integrity of the existing folders is not validated (as an example , see comments to https://github.com/microsoft/vscode-python/issues/7348).

Having more rigorous checking of extension folders consistency would protect the user from a whole array of possible issues and simplify troubleshooting of errors causes by corrupted extension folders.

Originally reported https://github.com/microsoft/vscode-python/issues/7396

**Comment by jvalkeal** [comment]
It'd be nice if `code --uninstall-extension myextenstion.vsix` would actually wipe out that directory. Took a while to realise that when doing extension development and doing dancing with `--install-extension` and `--uninstall-extension`, you actually need to once start a real instance before that installation directory is removed. Also `--install-extension` don't even install new updated extension(same version) over existing directory.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/80904
