### ISSUE TITLE
[Snippets] - Add support for transformations piping

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [microsoft/vscode#80916]
It would be great to have option of piping transformations on variables and placeholders.

Syntax should be something like this:
```
${1 | (regex|formatter) | (regex|formatter) | ...}
```

Valid use case is converting camelCase to UPPER_SNAKE_CASE

* first stage will be to replace every upper case with _ and itself
* second stage will be to convert everything into upper case

something similar to:
```
${1 | /([A-Z])/_${1}/ | /(.*)/${1:/upcase}/}
```

My use case is creation of redux action where I want to have name of action creator method and type constant with same wording - one is camelCase and another is snake case.

```
export const FETCH_USER = Symbol('FETCH_USER');

export const fetchUserAction = (id) => ({
  type: FETCH_USER,
  payload: { id },
});
```

and currently it is limiting me to have type constant in lower case:

```
        "Redux action": {
		"prefix": "sni_redux_action",
		"body": [
			"export const ${1/([A-Z])/_${1}/} = Symbol('${1/([A-Z])/_${1}/}');",
			"",
			"export const ${1}Action = (${2:param}) => ({",
			"	type: ${1/([A-Z])/_${1}/},",
			"	payload: { ${2:param} },",
			"});"
		],
		"description": "Redux reducer snippet"
	},
```

**Comment by ArturoDent** [comment]
Not sure I completely understand but try this snippet:

```
"Redux action": {
  "prefix": "sni_redux_action",
  "body": [
    "export const ${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/} = Symbol('${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/}');",
    "",
    "export const ${1}Action = (${2:param}) => ({",
    "	type: ${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/},",
    "	payload: { ${2:param} },",
    "});"
  ],
  "description": "Redux reducer snippet"
}
```
then you just type `fetchUser`, tab, type `id`, tab and you get your desired output.  Perhaps I am misunderstanding something in your example.

[It would be nice if you `save` a snippet transform once and just refer to its output later and not have to redo the transform 3 times in your case.]

**Comment by vukasin-nikodijevic** [comment]
@ArturoDent thanks for snippet but it works just partially.

```
export const GET_FETCHUser = Symbol('GET_FETCHUser');

export const getFetchUserAction = (param) => ({
  type: GET_FETCHUser,
  payload: { param },
});
```

Idea behind this feature request is that not everything can be solved into a single and complex REGEX.

On the other side, even if it is possible it is extremely hard for the majority of people to master regex at that level.

**Comment by ArturoDent** [comment]
Just need to use the global flag to work for more than two case:

```
"Redux action": {
  "prefix": "sni_redux_action",
  "body": [
    "export const ${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/g} = Symbol('${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/g}');",
    "",
    "export const ${1}Action = (${2:param}) => ({",
    "	type: ${1/([^A-Z]*)([A-Z])([a-z]+)/${1:/upcase}_$2${3:/upcase}/g},",
    "	payload: { ${2:param} },",
    "});"
  ],
  "description": "Redux reducer snippet"
},
```

I just added the `g` global flag to the end of each transform - try it now.
