### ISSUE TITLE
some files not showing up on the explorer pane

### ISSUE THREAD

**Issue by GitHubFilipe** [microsoft/vscode#80910]
Issue Type: <b>Bug</b>

1- Open folder with code
2 - Navigate to subfolder where the file lives
3 - File doesn't appear (whereas on the terminal does)

![Bugreport1](https://user-images.githubusercontent.com/30056747/64904385-c1d14a00-d6c9-11e9-9eaf-90288e71c3ef.jpg)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz (4 x 2132)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (8.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.9
vscode-pull-request-github|Git|0.11.1
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
debugger-for-chrome|msj|4.11.7

</details>

**Comment by usernamehw** [comment]
What's the value of your `"files.exclude"` setting?

**Comment by aeschli** [comment]
Was the file created since you opened VSCode or was it already there?

Is it reproducible when you restart VSCode?
Can you check if there's a exclusion pattern set in `files.exclude`

**Comment by isidorn** [comment]
@GitHubFilipe Can you please answer @aeschli questsions and can you reproduce with VS Code insiders https://code.visualstudio.com/insiders/

**Comment by GitHubFilipe** [comment]
> Was the file created since you opened VSCode or was it already there?
> 
> Is it reproducible when you restart VSCode?
> Can you check if there's a exclusion pattern set in `files.exclude`

@aeschli It was indeed due to the entry `src/**/*.scss.ts` in the files.exclude setting.
Thank you!
