### ISSUE TITLE
Terminal inside Code

### ISSUE THREAD

**Issue by mafiya69** [Microsoft/vscode#8092]
- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/7235212/16332142/07b112ec-3a12-11e6-8957-aac55721f5c5.png)
- OS Version: Windows 8.1

I am getting this terminal in Code : 
![image](https://cloud.githubusercontent.com/assets/7235212/16332127/f149440c-3a11-11e6-9dad-ab22f7f3d97c.png)
Whats wrong here?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7493
