### ISSUE TITLE
Provide a mechanism by which error pop ups can be clicked on to go to the source of the error.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#80928]
Issue Type: <b>Feature Request</b>

When an error message pops up on the screen, it would be swell if I could click on it (or on a link in it) that leads to the source of the error. For example many messages refer to a setting that they want you to edit or read or something. But sadly, it's not clear to a new user where this is.

Please enable a feature (that also, extensions can easily employ) to allow a user to click and be transported to the relevant place with a nice highlight around the setting.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@danielmrussell 

> When an error message pops up on the screen

Can you share what error message popup you mean?

**Comment by danielmrussell** [comment]
The kind that pop up in little rectangles on the bottom right of the screen.

**Comment by bpasero** [comment]
@danielmrussell and what kind of specific error do you mean, can you maybe post a screenshot of one that you would like to click?

**Comment by danielmrussell** [comment]
Specifically I was thinking that if there was some very easy way to just
mention an error in text by an id or something and automatically, have that
be linkified. Then when the error pops up, with minimal effort on the part
of extension prorgrammers, just by mentioning an error in a setting
somewhere, a hyperlink would be generated.by which the end user could
instantly click on it and be transported to the setting GUI where that is.

I've come to realize I don't know much about how Code's API and
architecture work yet (as a mere software developer doing other projects),
and it's possible this already exists in its own sufficient form. It is
still after all the responsibility of the programmers to at least mention
by name the setting they want you to fix, which in my example they failed
to do in the first instance:

"" could not be found. 'includePath' from c_cpp_properties.json will be
used instead.

That is clearly a bad error message and I submitted a separate bug for it.
It refers to the VALUE of the setting instead of the name of the setting
itself, making it impossible for me, the user to know what to do. However,
I also wanted really badly at that time to be able to click it, and
"includePath" as well, and have myself transported to the settings page
where these could be edited. The fact that this doesn't exist often leaves
me very frustrated as a new user wanting to write code instead of debugging
my workflow for weeks on end haha. You know how it would be as an indie
developer. So much to do.

In this frustration, I have come to realize, a way out would be so simple:
just make it the paradigm to orient around relevant settings. If this
became the culture of VS Code, so that all extension programmers just by
default tended to think in terms of "when there is an error, mention id of
settings that are relevant to user." If this process was so easy as to be
almost implicit, it would greatly encourage developers to use the feature,
and make Code a much better end experience.

As it stands now, it's sorta random whether an extension will bother to go
through the effort of implementing something similar on their own. I want
it to be more strongly de facto. A way of doing things that is consistent
across the board.

**Comment by bpasero** [comment]
Ok I think I am distilling that for example when a notification toast contains a file name (possibly with line number), there could be a link generated automatically (similar how we do it in the output window) to make it clickable and open it.
