### ISSUE TITLE
debug remote in linux with lanch mode

### ISSUE THREAD

**Issue by MacrossYu** [microsoft/vscode#80925]
Issue Type: <b>Bug</b>

steps：
1、debug with lanch mode(c++)
2、source sync with remote setted by sourceMap
3、debuged program run with args and env
4、set breakpoints in local source code
press F5， program is running，but have problem：
program is pauseed somewhere，not pauseed at the breakpoint code， not continue util press F5 several times，then hit the first breakpoint，but do not sync in the local code. the source map do not work

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.9.1
vscode-dash|dee|2.2.0
code-runner|for|0.9.14
vscode-language-pack-zh-hans|MS-|1.38.3
python|ms-|2019.9.34911
remote-ssh|ms-|0.46.0
remote-ssh-edit|ms-|0.46.0
remote-ssh-explorer|ms-|0.46.0
cpptools|ms-|0.25.1
powershell|ms-|2019.5.0
sublime-keybindings|ms-|4.0.3
highlight-words|rsb|0.1.4
vscode-icons|vsc|9.3.0

</details>

**Comment by weinand** [comment]
@MacrossYu what debugger are you using? In step 1. you mention "c++" but later you refer to source maps (which don't exist for c++.
