### ISSUE TITLE
Golang all package level identifiers in folder in outline

### ISSUE THREAD

**Issue by gocs** [microsoft/vscode#80922]
![image](https://user-images.githubusercontent.com/27877342/64908318-06dc9700-d731-11e9-8e76-2fa4ee858890.png)

if a folder in a package contains >20 files it's hard to switch between files.

(actually) i have three folders for every struct

**Comment by aeschli** [comment]
The content of the outline is provided by the go extension.
Can you file the issue there?
(Please reopen if I misunderstood the request)
