### ISSUE TITLE
Multiline editor find doesn't work in regex mode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80927]
- Have an editor with

```
a
b
```

- Copy and paste it into the find widget
- Enable regex mode
- It is not found

You could argue that a regex shouldn't contain a real newline, but I had the same issue in search and found that people expected it to work, so it works in search.

**Comment by rebornix** [comment]
I think it's a dup of https://github.com/microsoft/vscode/issues/41050 .
