### ISSUE TITLE
[emmet] http-equiv="X-UA-Compatible" in 2019

### ISSUE THREAD

**Issue by p0358** [microsoft/vscode#80923]
`html:5` macro still includes `<meta http-equiv="X-UA-Compatible" content="ie=edge">`
According to all the sources, it should be definitely unneeded nowadays.
This has been previously reported in #58796, where issue was locked and limited to collaborators. It was marked as upstream and suggested opening an issue at emmetio/expand-abbreviation (now archived). However https://github.com/emmetio/expand-abbreviation/issues/28 shows that is has already been disabled there.
Why is it still kept in VSCode?

**Comment by t-mart** [comment]
I share the same concern as the OP.

Until the fix (optimistically speaking) is implemented, is there a way to access/update these expansions ourselves?

**Comment by sekti92** [comment]
I believe this meta tag already disabled

**Comment by p0358** [comment]
Yes, looks like that's true, just checked on a recent version. I'm closing the issue then.
