### ISSUE TITLE
vscode how to disable tab autocomplete

### ISSUE THREAD

**Issue by craigcosmo** [microsoft/vscode#80931]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

When type something, vscode show some suggestions, I press tab. the suggestion will autocomplete what I typing.

Now I want to disable that. I want when I press tab, it will not autocomplete.

I do not want to disable suggestion or autocomplete, I just want to disable the tab thing

This is what I've got in the setting

Steps to Reproduce:

```
"editor.acceptSuggestionOnCommitCharacter": false,
"emmet.triggerExpansionOnTab": false,
"editor.tabCompletion": "off",
"editor.suggest.snippetsPreventQuickSuggestions": false
```

doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment]
@craigcosmo  I think you are looking for the `acceptSelectedSuggestion` command in keybindings which is by default <kbd>tab</kbd>

**Comment by craigcosmo** [comment]
ya that works
