### ISSUE TITLE
wayland client started from visual studio code integrated terminal can't connect to weston compositor

### ISSUE THREAD

**Issue by linlangongzi** [microsoft/vscode#80936]
- VSCode Version: 1.38
- OS Version: ubuntu 18.04.3 x64

Steps to Reproduce:

1. start visual studio code
2. lauch weston compositor
3. wayland client launched from terminal integrated in visual studio code, can't connect to weston
4. enviroment variable DISABLE_WAYLAND set to 0.
5. Can't debug wayland client from visuai studio code terminal either
6. It worked ok in previous version
7. Can't use compile and run extension inside visual studio code to debug wayland client either. same behavior as described above. 
8. Wayland client DOES work from external terminal，actually，i have to use Ubuntu system terminal to make it work properly

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by aeschli** [comment]
Does it work from an external terminal?
