### ISSUE TITLE
The issue of the language server hover feature content

### ISSUE THREAD

**Issue by alanchuangi** [microsoft/vscode#80939]
- VSCode Version:1.38.1
- OS Version: win10 10.0.18362

Steps to Reproduce:

About the hover feature
Compare with the document of help, the content providing by language server hover feature doesn't have correct word-wrap or indentation of the sample code
 It is difficultly to read the explain, could any guys tell me how to fix this problem

for example：the content of super(),
[language server](https://i.imgur.com/nhWEFCR.png)
![image](https://user-images.githubusercontent.com/6461412/64953555-664abc00-d883-11e9-936f-e1662a4300ad.png)

[help](https://i.imgur.com/3SSx0ii.png)

Does this issue occur when all extensions are disabled?: No(But, I need to  enable the python extension at least to support the language server, and this situation still keep)

**Comment by aeschli** [comment]
What language and language server is that?
