### ISSUE TITLE
Visual bugs in the integrated terminal

### ISSUE THREAD

**Issue by tunnckoCore** [microsoft/vscode#80934]
- VSCode Version:

```
❯ code --version
1.38.0
3db7e09f3b61f915d03bbfa58e258d6eee843f35
x64
```

- OS Version: ArchLinux

Steps to Reproduce:

1. Not sure. It just appears. 
2. When resizing the terminal window it gets fixed, then after typing a command it shows again.

Does this issue occur when all extensions are disabled?: Yes.

Images:

![2019-09-15-041950_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/64915472-3d85d200-d770-11e9-8de6-608bfbfab6cd.png)
![2019-09-15-002611_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/64915473-3e1e6880-d770-11e9-9ec7-cdb4744d7c0d.png)
![2019-09-15-002037_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/64915474-3e1e6880-d770-11e9-8de8-ddf9c1abb4a4.png)

**Comment by Tyriar** [comment]
Looks like a problem with canvas, you can try updating your graphics driver and if that doesn't work disable the canvas renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```

**Comment by tunnckoCore** [comment]
Thanks, I'll try.

**Comment by tunnckoCore** [comment]
Nope. Except that my fonts changed drastically bad, nothing good happened. :D
