### ISSUE TITLE
无法播放音乐

### ISSUE THREAD

**Issue by Bugatti100Peagle** [microsoft/vscode#80935]
Issue Type: <b>Bug</b>

网页端的网易音乐可以播放，也下载了ffmpeg，可连接登录，就是没有声音

Netease music on the web side can be played, and ffmpeg is also downloaded. You can connect to login, there is no sound.

Extension version: 0.0.24
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Please explain how this is related to VSCode.

**Comment by byyxx128** [comment]
@Bugatti100Peagle This is the issue of extension not vscode. Please report as an extension issue.
I'll show you how to do this——
![image](https://user-images.githubusercontent.com/20079289/64967468-8d4ac300-d86e-11e9-9ab0-f08f77c4a77b.png)
As the extension you are using is built by a Chinese developer , so you can speak Chinese there.
But next time if you report an issue of VS Code, you need to write in English.
***
我给你划下重点：
1. 这是扩展问题，你去按上图报告。
2. 这个扩展是中国人开发的，你可以在那边讲中文。但是下次如果你报告 VS Code 的问题你必须讲英文。

**Comment by kieferrm** [comment]
Based on @byyxx128's comment I close this issue.

**Comment by Bugatti100Peagle** [comment]
Sorry，I didn't notice this is VScode, not netease, I cancel the issue
