### ISSUE TITLE
Case of extension id shown incorrectly

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#80941]
Steps to Reproduce:

1. add an default formater setting for the svelte language id using the id listed on the svelte extension page

![image](https://user-images.githubusercontent.com/618922/64918242-89963e00-d793-11e9-94e6-824b4f969879.png)

```
	"[svelte]": {
		"editor.defaultFormatter": "jamesbirtles.svelte-vscode"
	}
``.

it fails to load.

You need to use the same case as provided in the extension [`package.josn`](https://github.com/UnwrittenFun/svelte-vscode/blob/225a5e17fdc70cf07202b84fde1f2cc764463f70/package.json#L28)

```
	"[svelte]": {
		"editor.defaultFormatter": "JamesBirtles.svelte-vscode"
	}
``.

It appears the id is shown in lowercase when it should have capitals.

**Comment by sandy081** [comment]
extensionId is case insensitive

**Comment by SteveALee** [comment]
But not, it appears when used for edit.defaultFormatter.

Unless, I had something else different which was corrected when I selected it from the intellisense (which also showed the capitals).

**Comment by sandy081** [comment]
I do not think `edit.defaultFormatter.` is handling case insensitivity.

**Comment by jrieken** [comment]
@sandy081 This does use `ExtensionIdentifier.equals`: https://github.com/microsoft/vscode/blob/5c3ac79b0100c8c05c53f11b0039bb35ddc90d49/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L85-L90. So, I think I am doing this correctly.

**Comment by jrieken** [comment]
> it fails to load. You need to use the same case as provided in the extension [`package.josn`](https://github.com/UnwrittenFun/svelte-vscode/blob/225a5e17fdc70cf07202b84fde1f2cc764463f70/package.json#L28)

@SteveALee What does that mean? Can you be more precise?

**Comment by jrieken** [comment]
Do you mean this squiggle by any change? It's correct that IntelliSense uses the extension ids (as defined, we don't use all permutations here) but it shouldn't affect how formatting works. 

<img width="586" alt="Screenshot 2019-09-30 at 14 45 50" src="https://user-images.githubusercontent.com/1794099/65879837-024eea00-e391-11e9-8f48-28a826786161.png">

**Comment by SteveALee** [comment]
@jrieken I revisted this in response and hnow cannot reproduce it. Typical! :)

By 'does not load' what I meant was that the 'svelte files were not getting formatted on save. I defintely had this but do not know what the exact config was at the time.. I can;t be sure but I don't recall seeing the yellow squiggle either.

With this config everything now works as expected whatever case is used (it very was painful to get right)

```
	"editor.formatOnSave": true,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"prettier.disableLanguages": ["vue", "svelte"],
	"[svelte]": {
		"editor.defaultFormatter": "JamesBirtles.svelte-vscode"
	}
```

Please see https://github.com/SteveALee/svelte-code-cypress-project if you want somehting to explore it further.

I'll close this as I cannot repr. Thanks for getting involved.
