### ISSUE TITLE
Debug Toolbar POSITION

### ISSUE THREAD

**Issue by buster95** [microsoft/vscode#80940]
Debug toolbar position is not adequate, actual position is hover the content, when I develop, have to move and move and move and move to see file content and more complicated when I open a lot of tabs, minimap and tabs are perjudicated

Is possible pin to title bar debug toolbar? like this
![image](https://user-images.githubusercontent.com/15637669/64918142-6d74ab80-d757-11e9-9bbd-02537783f056.png)

**Comment by jvalkeal** [comment]
Use setting `"debug.toolBarLocation": "docked"` to dock it to debug bar. It can be `floating`, `docked` or `hidden`.

**Comment by buster95** [comment]
Yes, but is only visible in debug tab, I like that shown always, but actual position is over the content (tabs,  laterals buttons tabs and mini map), I would like docked in another place, always shown
