### ISSUE TITLE
Default Output Colorizer

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#80947]
The [Output Colorizer](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) extension adds syntax highlighting to the output panel.  However, other extensions (e.g. Code runner) can cause conflicts, removing the syntax highlighting.

Apparently [this is a limitation with VSCode](https://github.com/IBM-Cloud/vscode-log-output-colorizer/issues/19#issuecomment-392048256) itself. I'm not exactly sure what needs to be done here to get extensions to play nicely. I suppose we would need to be able to select a default colorizer?

**Comment by isidorn** [comment]
Yeah we currently do have support for users to choose a colorizer.
Thus leaving this open as a feature reuqest.
fyi @jrieken and @sandy081
