### ISSUE TITLE
鼠标无法选中多行

### ISSUE THREAD

**Issue by weirio** [microsoft/vscode#80942]
Issue Type: <b>Bug</b>

用鼠标选中多行时，无法选中，且变为光标

When multiple lines are selected with the mouse, they cannot be selected and become cursor

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-code-run|bra|1.0.2
matlab|Gim|1.2.0
latex-workshop|Jam|8.1.1
vscode-language-pack-zh-hans|MS-|1.38.3
vim|vsc|1.10.2
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by weirio** [comment]
Thanks for your reply first. I have solved the problem by uninstall Vim plugin which I guess disturbs the input in VSCode.------------------ 原始邮件 ------------------发件人: Martin Aeschlimann  <notifications@github.com>发送时间: 2019年9月16日 19:10收件人: microsoft/vscode <vscode@noreply.github.com>抄送: qingwenjie <wenjieqing@mail.nwpu.edu.cn>, Author <author@noreply.github.com>主题: 回复：[microsoft/vscode] 鼠标无法选中多行 (#80942)Can you add a screenshot?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/vscode/issues/80942?email_source=notifications\u0026email_token=AMRC4DZ27ZIZ5W35LMM6WKDQJ5SR3A5CNFSM4IWZ4LMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6YZRTQ#issuecomment-531732686",
"url": "https://github.com/microsoft/vscode/issues/80942?email_source=notifications\u0026email_token=AMRC4DZ27ZIZ5W35LMM6WKDQJ5SR3A5CNFSM4IWZ4LMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6YZRTQ#issuecomment-531732686",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
