### ISSUE TITLE
First window does not restore its former size and location

### ISSUE THREAD

**Issue by jurajkapsz** [microsoft/vscode#80943]
- VSCode Version: 1.38.1 (also couple versions before)
- OS Version: (X)Ubuntu 18.04 (XFCE 4.12)

Steps to Reproduce:

1. Start vscode
2. Resize and/or shift vscode window
3. Restart vscode (close and open)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ddzy** [comment]
> * VSCode Version: 1.38.1 (also couple versions before)
> * OS Version: (X)Ubuntu 18.04 (XFCE 4.12)
> 
> Steps to Reproduce:
> 
> 1. Start vscode
> 2. Resize and/or shift vscode window
> 3. Restart vscode (close and open)
> 
> Does this issue occur when all extensions are disabled?: Yes

Same issue

**Comment by ddzy** [comment]
## Version

版本: 1.39.0-insider (user setup)
提交: d157c2e941cae17acb79bf26a70bbfad732bdc83
日期: 2019-09-16T06:06:10.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

## Current Feature

The restore-button does not work after the editor opened!

![vscode_issue_1](https://user-images.githubusercontent.com/33921398/65003621-e167ad00-d92b-11e9-9f4c-23f686010f4d.png)

**Comment by bihshan** [comment]
Same issue.

**Comment by bpasero** [comment]
@bihshan do thinks improve once you configure `"window.titleBarStyle": "native"` in settings?

**Comment by jurajkapsz** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

@bpasero  Same issue with nightly insider build.

> do thinks improve once you configure `"window.titleBarStyle": "native"` in settings?

No.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
