### ISSUE TITLE
Show files starting with dot in VS Code Command bar

### ISSUE THREAD

**Issue by AlexZeitler** [microsoft/vscode#80949]
- VSCode Version: 
```
Visual Studio Code - Insiders

Version: 1.39.0-insider
Commit: b7a5b7cf39f569a570599530ffc855b454e37b06
Date: 2019-09-12T08:43:00.105Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a folder which includes several files starting with a `.` like `.editorconfig` or `.tmuxinator.yml`
2. Press <kbd> ⌘ </kbd> + <kbd>p</kbd>
3. Type `.tmux`
4. `tmuxinator.yml` isnt suggested

This seems to happen when the folder contains a lot of subfolders and files.

Files starting with a `.` are not excluded in my settings:
![image](https://user-images.githubusercontent.com/287480/64926826-9aca6380-d802-11e9-9b28-1023c952cab6.png)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by roblourens** [comment]
Are they in your .gitignore?

**Comment by AlexZeitler** [comment]
no

**Comment by roblourens** [comment]
I can't reproduce it. So this only affects files that start with `.` and you can find all other files? What if you create a new file that starts with `.` and search for it?
