### ISSUE TITLE
Save/Open local File/Folder commands should move to electron-browser

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80959]
I notice quite a few actions/commands in `browser/workspaceActions` that talk about "local" file access (e.g for saving or opening). These currently live in the `browser` namespace but should move to `electron-browser` as we can never support them in the web.

This probably drags on to the file explorer where they also seem to be used and would require `electron-browser` there too.

List:
* `OpenLocalFileCommand`
* `SaveLocalFileCommand`
* `OpenLocalFolderCommand`
* `OpenLocalFileFolderCommand`

I am about to introduce a `src/vs/workbench/electron-browser/actions/workspaceActions.ts` where you can move them. Alternatively they could also be moved closer to where they are being used (explorer?)

//cc @isidorn

**Comment by isidorn** [comment]
From the explorer land they are only used in the `fileActions.contribution` and we can easily add another `fileActions.contribution` which lives under `electron-browser` and those command would only be contributed when not in web. I can do that right now, so Alex can move those command to wherver is fitting. Having them in the explorer land does not fit really well since they are also included in the `remoteFileDialog`

**Comment by isidorn** [comment]
Actually all these actions are remoteDialog specific, due to that I will introduce `src/vs/workbench/services/dialogs/electron-browser/remoteFileActions.contribution.ts` that will just register them. 
@alexr00 I think that it then makes sense to move this actions close to the `dialogs` folder

**Comment by isidorn** [comment]
Actually I put it here `src/vs/workbench/contrib/remote/electron-browser/remote.contribution.ts`
Feel free to move it around. I felt it belongs there most.

**Comment by alexr00** [comment]
@isidorn thank you for moving the commands. The file you put them in works well.

**Comment by alexr00** [comment]
@bpasero the IDs and LABELS of those commands are used in the remoteFileDialog, which lives at src\vs\workbench\services\dialogs\browser\remoteFileDialog.ts. I can move the commands themselves, but the IDs and LABELS need to stay out of electron-browser.

**Comment by bpasero** [comment]
@alexr00 I find `workbench/common/actions.ts` not a good place for declaring these commands. That module is more about laying the foundation for contributing actions in the wokbench, not so much for declaring available actions. 

I do not fully understand why these things cannot move into the `remoteFileDialog` itself, they only seem to be used from there?

**Comment by alexr00** [comment]
I didn't read carefully enough the first time and thought you wanted them in workspaceAction. Moved as suggested!
