### ISSUE TITLE
Allow explicit text colors for Output Panel

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#80955]
Currently, the Output Panel shares the same text colors as arbitrary Editor text colors (defined in the VSCode theme).  It would be very useful to allow the flexibility to set explicit text colors for the Output Panel (defined in the VSCode theme).  For example, in the below screenshot, the Output Panel has dark-red text that's very hard to read (which shares the same text color as a **string** in the Editor pane).
![CodeRunner](https://user-images.githubusercontent.com/811008/64932442-d0b41b80-d7f3-11e9-9fa7-6b552596c4cf.png)

**Comment by isidorn** [comment]
Please customise this color `panel.background`. That controls what you need.
You can create a custom theme, or just configure `"workbench.colorCustomizations"` setting

**Comment by mkanet** [comment]
It looks like panel.background controls the background for the entire panel.. which is NOT what I was asking for. 
 panel.background doesn't control the text color for the Output panel.

**Comment by isidorn** [comment]
Use an extensions taht contributes syntax colorizing for the output. Or just write a new extension.
Here's one extensions which does that https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

**Comment by mkanet** [comment]
Thank you, I'll check out the output colorizor; as there no way I'd want to use a different color theme.
