### ISSUE TITLE
API request: Tab-Complete event

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#8095]
In the process of working on a [Vim plugin for VSCode](https://github.com/VSCodeVim/Vim) I've run into a number of areas where I need a little bit of API help. Apologies if any of my suggestions already exist!

It would be _very_ useful for me to have some sort of way both to monitor when a tab-complete action is triggered (and in particular to retrieve the text that was completed). I need this for things like macros and the . command, which repeats what the user just did.

**Comment by jrieken** [comment]
> tab-complete action

Not so sure what that means?

**Comment by johnfn** [comment]
Sorry. I want an event that happens when a user presses tab when the completion window is open, and I want to have a string passed as an argument which is the text that was inserted.

**Comment by jrieken** [comment]
Ok - understood. Accepting a completion is the `acceptSelectedSuggestion` command that by default is bound to the <kbd>Tab</kbd> key. That means users might have configured a different key to trigger this action. 

We have a request to send out event before and after a command has executed:  #1431. Closing this as duplicate.
