### ISSUE TITLE
vscode python 格式化插件 yapf无效

### ISSUE THREAD

**Issue by boern** [microsoft/vscode#80956]
问题描述：保存python文件时，状态栏闪现过，Formatting with yapf, 但是python文件并没有格式化

Google translate:
Problem Description: When saving a python file, the status bar flashes, Formatting with yapf, but the python file is not formatted

环境说明：
Win10
vscode 1.38.1
Anaconda3
yapf 0.28

user setings设置：
"editor.formatOnSave": true,
"python.formatting.provider": "yapf"
"python.formatting.yapfArgs": ["--style", "{based_on_style: google, indent_width: 4}"]

但是直接使用yapf命令格式化文件是可以的。
yapf -i filename.py //这样可以成功格式化

这是个bug还是配置问题？

**Comment by boern** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Environment variables are not passed to tasks in 1.37 (#79291)](https://www.github.com/microsoft/vscode/issues/79291)

我认为这是两个不同的问题，不过我很好奇，既然vscode python扩展已经支持yapf，为什么还要通过配置task方式来完成python代码格式化？

**Comment by aeschli** [comment]
Can you file this against the extension that provides the formatter?
