### ISSUE TITLE
VS Code "The windows is crashed..." & "Reopen" in a loop.

### ISSUE THREAD

**Issue by JFDowling** [microsoft/vscode#80950]
Windows 10 Pro Version 10.0.18362 Build 18362
VS Code version:
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Using the link on Start results in  "The windows is crashed...". Same with launch using shortcut and same when using File Open at "code" file location.

Created a new shortcut at "code" location and it works fine.
Copied it to Start Menu location and replace the previous one. No Joy.

Start from command line works just fine. Even opens just-previously opened files.
Also work from double-click of an editable file but does not open just-previously opened files.
Open with Code on right-click of previously-opened folder works just fine. Even opens just-previously opened files.

Odd to me. You?

Problem started two days ago before most recent Windows Update.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by JFDowling** [comment]
Installed 1.3.8.1  to much joy!

Start Menu Icon works properly.
Command Prompt using Code works properly.
Double-click file works properly.
Right-Click file works properly.
Right-Click folder works properly, opens just previously opened files.

I’ll be more diligent keeping up to date.

thnx,

Jim D.

**Comment by JFDowling** [comment]
Again, issues do get resolved quickly with VS Code. My bad for getting behind with updates. Thanks Benjamin and team..
