### ISSUE TITLE
features

### ISSUE THREAD

**Issue by michaellanguage** [microsoft/vscode#80967]
Issue Type: <b>Feature Request</b>

I think the file menu option should receive information about installed file name extention defined in runner bundle.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

**Comment by aeschli** [comment]
Sorry, I'm afraid I don't understand what you are suggesting.
Do you want to configure for which file extensions the VSCode installer registers VSCode?
