### ISSUE TITLE
git diff shown after commit

### ISSUE THREAD

**Issue by gabrielestenico** [microsoft/vscode#80966]
- VSCode Version: 1.38.1
- OS Version: Windows 10 PRO, 1903, build 18362.356

Steps to Reproduce:

1. Edit source file.
2. Stage edited file for commit.
3. Commit.
4. Observe that git diff visualization is still shown near line numbers. 

Does this issue occur when all extensions are disabled?: No

---

 - Source control tab looks fine
 - After vscode reboot all looks fine, until the next commit.
 - Cannot reproduce this 100% of the time

**Comment by joaomoreno** [comment]
Are you editing files in a network share? Or symbolic link? Anything special about your workspace? Can you reproduce on other git repositories?
