### ISSUE TITLE
Improve the API of completion

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#80960]
See https://github.com/microsoft/vscode-languageserver-node/issues/519

So I hope the completion API supports merging result.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by sumneko** [comment]
When installing multi language extensions that provide code completion, the completion items would not show until all extensions response.
However, if one of them response slowly, it blocks all provides.

![不合并](https://user-images.githubusercontent.com/5213431/64611934-2e67f280-d405-11e9-8d13-4c32ef5c4d58.gif)
(I deliberately delayed the response by 3 seconds.)

But I noticed that some times the completion response is recived one by one, then merge them:

![合并](https://user-images.githubusercontent.com/5213431/64612135-a9310d80-d405-11e9-9c71-42c86eee023e.gif)

I hope we can always use this way to merge and show code completions.

Unfortunately, the slowest response is provided by my extension.
When user typing in a very large file, I need to full compile this file, then provided the correctly response.
Maybe there is a way that I can provide a less correct response which generated by text matching and last compiled result, after I fully compiling the file, I provide a correct response again, then the client merge or cover the last completion.

@dbaeumer suggested me to open an issue here, due to the merging is implemented in VSCode, and this is a general problem of the VS Code API, although I don't know what this problem is.

**Comment by jrieken** [comment]
This is not an API problem but a UI problem. How would solve sorting and selecting when completion come in with a delay? Assuming the widget shows results as soon as they come should later results always show at the bottom? Should everything always refresh when new results come in, e.g to support showing the best suggestions atop?
