### ISSUE TITLE
VSCode build on Windows 10 hanging...

### ISSUE THREAD

**Issue by guopingbo** [microsoft/vscode#80969]
- VSCode Version:  the latest version.
- OS Version: win10 professional 1809

Steps to Reproduce:

1.  clone the vscode repo, select master branch.
2.  execute cmd yarn to install deps.
3.  yarn watch to build the project, the hanging:

---------------------------------------------------------------------------
index.js:36
Finished clean-extension-json-language-features-server after 15632 ms
index.js:36
Starting watch-extension:json-language-features-server ...
index.js:36
Finished clean-extension-git after 16772 ms
index.js:36
Starting watch-extension:git ...
index.js:36
Finished clean-extension-html-language-features-server after 19761 ms
index.js:36
Starting watch-extension:html-language-features-server ...
index.js:36
Finished clean-extension-markdown-language-features after 59729 ms
index.js:36
Starting watch-extension:markdown-language-features ...
index.js:36
Finished clean-extension-npm after 62343 ms
index.js:36
Starting watch-extension:npm ...
index.js:36
Finished clean-extension-vscode-test-resolver after 63631 ms
index.js:36
Starting watch-extension:vscode-test-resolver ...
index.js:36
Finished clean-extension-vscode-api-tests after 64583 ms
index.js:36
Starting watch-extension:vscode-api-tests ...
index.js:36
Finished clean-extension-typescript-language-features after 65936 ms
index.js:36
Starting watch-extension:typescript-language-features ...
index.js:36
Finished clean-extension-php-language-features after 68989 ms
index.js:36
Starting watch-extension:php-language-features ...
index.js:36
Finished clean-out after 71417 ms
index.js:36
Starting watch-client ...
index.js:36
Finished compilation with 0 errors after 158671 ms
<cmd not exit, and hang.> 
---------------------------------------------------------------------------

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by guopingbo** [comment]
the release version: vscode-1.36.0 has the same issue.
please help the fix or get some cule.

**Comment by aeschli** [comment]
That's the expected behavior of `yarn watch`. After compilation, it is watching for file changes.

To just compile, use `yarn compile`
