### ISSUE TITLE
js validation doesn't work ?

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#8097]
- VSCode Version: 1.2.1
- OS Version: Windows 10

I open a folder, then create a simple .js file with unvalid syntax but I have no error hightlighted.

Is there something to do to enable js validation errors displayed ?

In user settings, I have `javascript.validate.enable` set to true and it's not overwritten in workspace settings.

For example a file with this code doesn't display any error:

```
functin foo() {
    bar();
}
```

**Comment by dbaeumer** [comment]
Here is what I see using 1.2.1. Does the file exist on disk? Currently JS validation only works for files that exist on disk.

![capture](https://cloud.githubusercontent.com/assets/1931590/16334169/b93e8c1e-39ff-11e6-8a4a-1cb481522d24.png)

**Comment by mjbvz** [comment]
I'm also unable to repo this on VSCode 1.7+.

@warpdesign please give this a try on a more recent release of VSCode and, if this still an issue, let us know in more detail how to reproduce this issue.

Thanks.
