### ISSUE TITLE
Error when launching vscode from terminal: "The "path" argument must be of type string."

### ISSUE THREAD

**Issue by tairosonloa** [microsoft/vscode#80971]
- VSCode Version: 1.38.1 b37e54c98e1a74ba89e03073e5a3761284e3ffb0 x64
- OS Version: Debian GNU/Linux 9.11 (stretch)

Steps to Reproduce:

1. Tried to launch:
```
code --extensions-dir "/opt/vscode" --install-extension "ms-vscode.cpptools"
code --extensions-dir "/opt/vscode" --install-extension ms-vscode.cpptools
code --extensions-dir /opt/vscode --install-extension "ms-vscode.cpptools"
code --extensions-dir /opt/vscode --install-extension ms-vscode.cpptools
```
2. Got the following error, for each:
```
The "path" argument must be of type string. Received type object
```
The four commands gave me the same error about the path. However, when I remove the --install-extension parameter or either the --extensions-dir, all run smooth. I have realized I get the same error when I combine --extensions-dir and --list-extensions.

However, if I launch code in full path (/usr/bin/code) instead of just code it works. I have seen my path and aliases and nothing is rewriting code command. 

Does this issue occur when all extensions are disabled?: Yes/No
It has not sense to launch code without extensions as I want to do extensions stuff.

**Comment by aeschli** [comment]
I'm not able to reproduce on either Linux or Windows

**Comment by tairosonloa** [comment]
Tried on my personal Manjaro Linux, I couldn't reproduce the issue. Tried again on Debian and it stills fails. However, if I launch code in full path (`/usr/bin/code`) instead of just `code` it works. I have seen my path and nothing is rewriting `code` command. That's weird.

**Comment by sandy081** [comment]
@joaomoreno Any insights on this?

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable?

**Comment by tairosonloa** [comment]
> Can you show me your `PATH` variable?

```
testuser@p182:~$ echo $PATH
/users/adm/testuser/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
testuser@p182:~$ whereis code
code: /usr/bin/code /usr/share/code
aalonso@p182:~
```

**Comment by joaomoreno** [comment]
How did you install code?

**Comment by tairosonloa** [comment]
> How did you install code?

Via repository and apt
```
testuser@p182:~$ cat /etc/apt/sources.list.d/vscode.list 
deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
```

**Comment by joaomoreno** [comment]
What does `cat $(which code)` return?

**Comment by tairosonloa** [comment]
> What does `cat $(which code)` return?
```
testuser@p182:~$ cat $(which code)
#!/usr/bin/env bash
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

# test that VSCode wasn't installed inside WSL
if grep -qi Microsoft /proc/version; then
	echo "To use VS Code with the Windows Subsystem for Linux, please install VS Code in Windows and uninstall the Linux version in WSL. You can then use the 'Visual Studio Code' command in a WSL terminal just as you would in a normal command prompt." 1>&2
	read -e -p "Do you want to continue anyways ? [y/N] " YN

	[[ $YN == "n" || $YN == "N" || $YN == "" ]] && exit 1
fi


# If root, ensure that --user-data-dir or --file-write is specified
if [ "$(id -u)" = "0" ]; then
	for i in $@
	do
		if [[ $i == --user-data-dir || $i == --user-data-dir=* || $i == --file-write ]]; then
			CAN_LAUNCH_AS_ROOT=1
		fi
	done
	if [ -z $CAN_LAUNCH_AS_ROOT ]; then
		echo "You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument." 1>&2
		exit 1
	fi
fi

if [ ! -L $0 ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname $0)/.."
else
	if which readlink >/dev/null; then
		# if readlink exists, follow the symlink and find relatively
		VSCODE_PATH="$(dirname $(readlink -f $0))/.."
	else
		# else use the standard install location
		VSCODE_PATH="/usr/share/code"
	fi
fi

ELECTRON="$VSCODE_PATH/code"
CLI="$VSCODE_PATH/resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?

```

**Comment by joaomoreno** [comment]
Hm... does it repro if you remove the quotes?

**Comment by tairosonloa** [comment]
Where? In the _ELECTRON_ var at the end of the script? Or _VSCODE_PATH_ one?

**Comment by joaomoreno** [comment]
Sorry about the ambiguity, I meant this:

```
code --extensions-dir "/opt/vscode" --install-extension "ms-vscode.cpptools"
```

And run this instead:

```
code --extensions-dir /opt/vscode --install-extension ms-vscode.cpptools
```

**Comment by tairosonloa** [comment]
I'm sorry, I didn't post it on the issue, but I tried different ways before opening it. I tried:
```
code --extensions-dir "/opt/vscode" --install-extension "ms-vscode.cpptools"
code --extensions-dir "/opt/vscode" --install-extension ms-vscode.cpptools
code --extensions-dir /opt/vscode --install-extension "ms-vscode.cpptools"
code --extensions-dir /opt/vscode --install-extension ms-vscode.cpptools
```
The four ways gave me the same error about the path. However, when I remove the `--install-extension` parameter or either the `--extensions-dir`, all run smooth. I have realized I get the same error when I combine `--extensions-dir` and `--list-extensions`.

Will edit the first post to reflect all this info.

**Comment by joaomoreno** [comment]
What if you use another extensions dir?

**Comment by tairosonloa** [comment]
Tried with `--extensions-dir /tmp/vscode` and got the same error 
```
The "path" argument must be of type string. Received type object
```

**Comment by joaomoreno** [comment]
Would it be possible for you to run out of sources and try to reproduce this there? https://github.com/microsoft/vscode/wiki/How-to-Contribute That way we can debug it.
