### ISSUE TITLE
UI extension: workspace.openTextDocument() returns untitled file for file URI

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#80977]
In a UI extension (resolver phase):

```ts
workspace.openTextDocument(URI.file('/headless/wm.log'))
```

returns an untitled file when:

```ts
workspace.openTextDocument('/headless/wm.log')
```

returns the actually existing file.

**Comment by bpasero** [comment]
@chrmarti please consider that I am not sure what kind of setup you have and as such to speed things up, provide a reproducible case (ideally even a test that fails) for this so that we can jump on it. I appreciate that 👍

**Comment by chrmarti** [comment]
I only see this within the resolver, it does not reproduce with a UI extension. Using this as a workaround:
```ts
vscode.workspace.openTextDocument(uri.scheme === 'file' ? uri.fsPath as any : uri);
```

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/5c3ac79b0100c8c05c53f11b0039bb35ddc90d49/src/vs/workbench/api/common/extHost.api.impl.ts#L631-L635

That is super weird. When calling `openTextDocument` with a `string` we actually call `URI.file` with that string. It just be exactly the same thing. @chrmarti Do you have a sample extension?

**Comment by chrmarti** [comment]
@jrieken Good point... I just found that I was passing a `vscode-uri` URI in. Fixing with:
```ts
vscode.workspace.openTextDocument(vscode.Uri.parse(uri.toString()));
```

 Thanks.

**Comment by jrieken** [comment]
Hm, I am not sure if `Uri.parse(uri.toString())` has an effect...

**Comment by chrmarti** [comment]
`uri` is `URI` from the `vscode-uri` package and that is not an instanceof `vscode.Uri`. `vscode.Uri.parse(uri.toString())` converts it.

**Comment by jrieken** [comment]
Hm, we should maybe use `Uri.isUri` instead since maybe other extension use this package...
