### ISSUE TITLE
Electron 6 does not start in containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#80975]
Self-hosting containers on Linux:

`code-insiders --verbose`:
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported,
but failed: errno = Operation not permitted
```

Not sure if this is the Electron update, bu the previous insiders build still worked.

**Comment by bpasero** [comment]
@chrmarti what exact environment is that you start code in?

**Comment by chrmarti** [comment]
This is Ubuntu 18.10 with Xfce 4 as a window manager. I run this in a container, so the number of system services is minimal.

**Comment by bpasero** [comment]
@chrmarti does Electron itself already fail to start, can you check with the 6.0.9 release? https://github.com/electron/electron/releases/tag/v6.0.9

Does it help if you use `--no-sandbox` as arg?

**Comment by chrmarti** [comment]
Electron fails with the same error. `--no-sandbox` allows plain Electron and VS Code to start up.

**Comment by bpasero** [comment]
This is similar to https://github.com/microsoft/vscode/issues/76963
