### ISSUE TITLE
Can't turn off IntelliSense explain mode - Poor UX

### ISSUE THREAD

**Issue by Wosi** [microsoft/vscode#80983]
When I accidentally enter IntelliSense explain mode I'm unable to leave it unless I reload the workspace.

Regarding to [this](https://github.com/microsoft/vscode/issues/75500#issuecomment-507172728) I should be able to toggle back with `Ctrl/Cmd+/` but it doesn't work. Maybe it's related to my German keyboard layout.

Neither can I find a command in the command palette to toggle back nor can I find a setting to turn it off permanently.
I think this feature should be disabled by default. Or it should at least provide a hint on how to go back to standard IntelliSense.

**Comment by Wosi** [comment]
I found a way to toggle explain mode:
 - The IntelliSense widget must be visible
 - Press `Ctrl + #` (works with german keyboard layout on Windows 10)

I'm happy I no longer need to reload the workspace when explain mode has been turned on.
But I still don't think it's good everyone can accidentally toggle explain mode since the explanation doesn't help most people and it is very unclear how to toggle back.

**Comment by octref** [comment]
@Wosi There's a close button on the upperright of the explain mode, does that work for you?

Meanwhile you can also press Ctrl+Space again to toggle the explain mode.

![image](https://user-images.githubusercontent.com/4033249/67607451-5dc68a80-f739-11e9-94e3-c4f5aaacb613.png)

**Comment by jrieken** [comment]
To verify:

* you can toggle explain mode via `cmd+/`
* explain mode always resets when suggest widget hides/closes
