### ISSUE TITLE
can't open the terminal

### ISSUE THREAD

**Issue by citrusjunoss** [microsoft/vscode#80989]
bootstrap-window.js:212 [uncaught exception]: Error: connect ENOENT \\.\pipe\winpty-conout-10324-2-1d56c9a87a4066c-662d441aff7ff7f05645de3e53f7b31c

- VSCode Version:1.38.1
- OS Version: win10

Steps to Reproduce:

1. `ctrl + ~`
2. terminal not open, console show 

bootstrap-window.js:212 [uncaught exception]: Error: connect ENOENT \\.\pipe\winpty-conout-10324-2-1d56c9a87a4066c-662d441aff7ff7f05645de3e53f7b31c

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
It looks like anti-virus software is blocking winpty from creating the terminal process. You can either whitelist winpty-agent.exe or upgrade to Windows 10 1903 where we've moved onto a new backend for the terminal provided by the MS console team.
