### ISSUE TITLE
Custom snippets precedence in CSS

### ISSUE THREAD

**Issue by web2033** [microsoft/vscode#80982]
I have a bunch of user snippets for CSS, but they often appear first on autocomplete list in places where it makes no sense, like in this example. Is there smth that can be done to fix it?

![2019-09-16_151356](https://user-images.githubusercontent.com/11320080/64957364-71a6e300-d895-11e9-9b95-01301fda9875.jpg)

Repo with my snippets - https://github.com/web2033/vscode-snippets

**Comment by aeschli** [comment]
Check out the setting 'editor.snippetSuggestions'
