### ISSUE TITLE
VS Code encoding

### ISSUE THREAD

**Issue by SrikantPrasad** [microsoft/vscode#80988]
When we are writing powershell scripts using VSCode having special characters and having UTF-8 as our encoding on our local machine, and then try to run the same powershell on servers, it fails.

Attached are the videos.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by SrikantPrasad** [comment]
I would like you to check my issue._
![FA7C3DEB-AACC-4A06-B468-1EE86FE45E2E](https://user-images.githubusercontent.com/18580078/64981873-9bcec400-d8da-11e9-94ca-fccb02519868.gif)

**Comment by SrikantPrasad** [comment]
Video 2
![FA7C3DEB-AACC-4A06-B468-1EE86FE45E2E](https://user-images.githubusercontent.com/18580078/64981950-c28cfa80-d8da-11e9-845e-58f6fd5a08df.gif)

**Comment by SrikantPrasad** [comment]
[484DDA19-0F9E-47D1-B921-C83726D84E1E.zip](https://github.com/microsoft/vscode/files/3617585/484DDA19-0F9E-47D1-B921-C83726D84E1E.zip)

**Comment by SrikantPrasad** [comment]
> VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:
> 
> ![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)
> 
> There are two options how to configure the encoding for files
> 
> **Configure the encoding as a setting for all files or files of specific type**
> We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:
> 
> ```json
> "[markdown]": {
>     "files.encoding": "utf8"
> }
> ```
> 
> **Configure VS Code to automatically detect the encoding when opening files**
> We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).
> 
> Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

Hello Benjamin,

I have posted the videos which depict my issue, please let me know if you think it still fits the above list.
