### ISSUE TITLE
Discrete color options for terminal & editor (top & bottom panes)

### ISSUE THREAD

**Issue by clsheppard** [microsoft/vscode#80981]
It is not easy to quickly tell where my editor ends and my terminal split begins.  I propose VS Code allow users to set discrete colors for these portions of the window.  Alternatively, a new color option for the bar above the split that selects "problems, output, debug console, terminal" would visually divide the top and bottom panes even if they had the same background.

**Comment by ArturoDent** [comment]
You are aware of:

    "workbench.colorCustomizations": {

        "panel.background": "#292929",   // problems, etc. panel colors
        "panel.border": "#81621d"
    }

**Comment by clsheppard** [comment]
I was not.  I am new to VS Code.  Thanks for the polite and helpful redirection. 👍

**Comment by ArturoDent** [comment]
For the full list, see https://code.visualstudio.com/api/references/theme-color.

**Comment by olingern** [comment]
Looks like this can be closed
