### ISSUE TITLE
Filtering DEBUG CONSOLE

### ISSUE THREAD

**Issue by eliseyOzerov** [microsoft/vscode#80980]
Issue Type: <b>Feature Request</b>

Please, for the love of God, add filtering feature to the debug console. I'm spending hours just searching for my print statements amongst all the logs I don't need.

Search function is cool and all, but I need to be able to clearly see the timeline of MY logs without all the junk around them.

Thank you.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
Cmd + f, start typing and it will filter
For more fancy UX check out this Feature Request https://github.com/microsoft/vscode/issues/4338 and PR in case you want to contribute https://github.com/microsoft/vscode/pull/79620
