### ISSUE TITLE
Terminal: sometimes prompt appears all the way to the bottom

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80991]
Steps to Reproduce:

1. be on a slow Linux OS (e.g. VM while build tasks are running too there)
2. start VSCOde
3. reveal the terminal by dragging from the bottom

![before (2)](https://user-images.githubusercontent.com/900690/64968155-fbf54400-d8a1-11e9-9db2-153925fc98c5.gif)

**Comment by Tyriar** [comment]
@sbatten may be related to grid? I never drag from the bottom and haven't seen this yet (but I don't normally work on a vm)

**Comment by bpasero** [comment]
Small update: this "fixes" itself when I move the sash, so indeed it seems layout related.

**Comment by sbatten** [comment]
@bpasero with your repro, can you use dev tools to log the layout calls in the panel part and the dimensions

**Comment by bpasero** [comment]
@sbatten the thing is, the panel has a proper size which I think makes sense. Is there a place in the terminal to verify the dimension is proper and maybe a place to check if it is applied properly @Tyriar ?

**Comment by Tyriar** [comment]
@bpasero does resizing again after releasing the mouse when you're in that state correctly do a layout and fix everything up?

This is how SplitPaneContainer lays out the SplitViews:

https://github.com/microsoft/vscode/blob/bbb56dba81530874e64b6b9d74339b36375c97b6/src/vs/workbench/contrib/terminal/browser/terminalTab.ts#L132-L142

**Comment by Tyriar** [comment]
I can't repro and don't have enough info to action. @sbatten any ideas?

**Comment by bpasero** [comment]
@Tyriar 

> @bpasero does resizing again after releasing the mouse when you're in that state correctly do a layout and fix everything up?

Yes that seems to be the case. I see the prompt briefly staying at its current position but then moving up or down depending on how I resized. 

I added debug output to the  leading to all layout methods in `terminalTab.ts`:

![image](https://user-images.githubusercontent.com/900690/65938880-87cfaa00-e424-11e9-846b-c74e5319fb49.png)

For broken layout:

![image](https://user-images.githubusercontent.com/900690/65938885-8f8f4e80-e424-11e9-82ba-ac0bdbd64b72.png)

Steps:
* be on a slow VM (any parallels VM with Ubuntu will do)
* start VSCode (out of sources is fine too)
* ensure panel was not visible
* drag the panel to become visible from the statusbar (terminal should appear)

**Comment by NethmiRodrigo** [comment]
I seem to be having the same issue and I've been having it since the day I installed it. The prompt is about 10 lines down all the time. Included video of issue in zip.
[VS Code Issue.zip](https://github.com/microsoft/vscode/files/3908217/VS.Code.Issue.zip)
