### ISSUE TITLE
 y.onDidWriteData is not a function

### ISSUE THREAD

**Issue by audryhome** [microsoft/vscode#80994]
Issue Type: <b>Bug</b>

[17:17:53.171] y.onDidWriteData is not a function
[17:17:53.171] ------

Unable to connect to remote since updated minutes ago... user on MAC OSX

VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:04:26.115Z)
OS version: Darwin x64 17.7.0
Fetching remote diagnostics for 'SSH' failed: y.onDidWriteData is not a function

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 11, 12|
|Memory (System)|8.00GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: y.onDidWriteData is not a function
</details>Extensions: none

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1112
