### ISSUE TITLE
VSCODE slow after last update

### ISSUE THREAD

**Issue by ViniciusFXavier** [microsoft/vscode#80992]
From this last update of VSCode it does not stop crashing, I am unable to perform the click action most of the time in the code editor, when restarting the OS it resolves more only for a while, it is pulling much more process than any other program.

>  @kieferrm  Say:
> 
> > @ViniciusFXavier can you please provide us with more information about the concrete steps and your setup. You list two OS, so I'm guessing you use the remote extensions although you say it's happening without any extensions running? Does this happen with any workspace or empty window?

@kieferrm It happens in any workspace, in the file editor and the file doesn't have to have many lines, I was not using any external extensions I had an up-to-date Ubuntu version because I formatted my machine and got a new version and for example the Windowns version was not the most recent.

To solve the problem I deleted VSCode and re-installed a previous version and it worked correctly on both OS

This problem is happening in more than one OS I will let the spec of the two down.

- VSCode Version:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-62-generic
```
- OS Version:
```
Ubuntu 16.04 LTS
- Processor: Intel I5-7200U
- Memory: 8 Gb
- OS Type: 64-bit
```

```
Windows 10, version 1903
- Processor: Intel I7-7200U
- Memory: 16 Gb
- OS Type: 64-bit
```
Steps to Reproduce:

1.Do anything

Does this issue occur when all extensions are disabled?: Yes/No
- Yes

> @ViniciusFXavier can you please provide us with more information about the concrete steps and your setup. You list two OS, so I'm guessing you use the remote extensions although you say it's happening without any extensions running? Does this happen with any workspace or empty window?

> > @ViniciusFXavier can you please provide us with more information about the concrete steps and your setup. You list two OS, so I'm guessing you use the remote extensions although you say it's happening without any extensions running? Does this happen with any workspace or empty window?
> 
> @kieferrm It happens in any workspace, in the file editor and the file doesn't have to have many lines, I was not using any external extensions I had an up-to-date Ubuntu version because I formatted my machine and got a new version and for example the Windowns version was not the most recent.
> 
> To solve the problem I deleted VSCode and re-installed a previous version and it worked correctly on both OS

**Comment by kieferrm** [comment]
@ViniciusFXavier can you please provide us with more information about the concrete steps and your setup. You list two OS, so I'm guessing you use the remote extensions although you say it's happening without any extensions running? Does this happen with any workspace or empty window?

**Comment by damiangreen** [comment]
Switching to the insiders edition with the updated Electron solved it for us

**Comment by ViniciusFXavier** [comment]
> @ViniciusFXavier can you please provide us with more information about the concrete steps and your setup. You list two OS, so I'm guessing you use the remote extensions although you say it's happening without any extensions running? Does this happen with any workspace or empty window?

@kieferrm It happens in any workspace, in the file editor and the file doesn't have to have many lines, I was not using any external extensions I had an up-to-date Ubuntu version because I formatted my machine and got a new version and for example the Windowns version was not the most recent.

To solve the problem I deleted VSCode and re-installed a previous version and it worked correctly on both OS

**Comment by ViniciusFXavier** [comment]
> Switching to the insiders edition with the updated Electron solved it for us

@damiangreen Thank you so much I will try to do this :smile_cat:

**Comment by ViniciusFXavier** [comment]
Today I started using the Insider version and suddenly had no problems with crashes.
But the major version today is unviable to be used for crashing the computer needing to kill processes.


As I use it I give feedback about the Insiders more just because I do not have to restart the computer is an advantage
- https://code.visualstudio.com/insiders/

**Comment by ViniciusFXavier** [comment]
Is it really necessary all these processes?

Counting over everything used as in print below gives almost 2 Gigabytes of memory usage with no extension installed and only 2 windows open

![image](https://user-images.githubusercontent.com/40774281/65792746-bf93d480-e13a-11e9-879a-9ca1926af409.png)

**Comment by deepak1556** [comment]
@ViniciusFXavier can you try the following builds which is based on Electron 6, to see if the issue appears there. Thanks!

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
