### ISSUE TITLE
Running Spring boot application via launch.json prints classpath and exits

### ISSUE THREAD

**Issue by mkkhedawat** [microsoft/vscode#80990]
- VSCode Version: 1.36.1
- OS Version: Mac OSX

Steps to Reproduce:

1. Create a new springboot project via `JAVA:Overview`
2. Go to Main.java and run the application

Does this issue occur when all extensions are disabled?: Yes/No No

I am using JAVA extension pack from Microsoft. Running the application via Gradle works fine.

**Comment by aeschli** [comment]
Can you file this against the Java extension?  https://github.com/redhat-developer/vscode-java
