### ISSUE TITLE
no intellisense for objects

### ISSUE THREAD

**Issue by tellyarz** [Microsoft/vscode#8099]
- VSCode Version: Version 1.2.1
- OS Version: Linux Mint 17.3

I have a slim application in PHP and wanted to see if the IDE will show the various properties and methods under the slim object. Not happy this was not the case, no intellisense for the slim object. Below is the code snippet:

```
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;
use \Algos\App\classes\PDO_connection;

//slim framework initialization
$app = new \Slim\App;

$container = $app-> //expected list of properties and methods here

```

Is there any work around for this?

**Comment by ciruz** [comment]
There is a extension for this called crane:

https://hvy.io/crane
https://marketplace.visualstudio.com/items?itemName=HvyIndustries.crane

**Comment by tellyarz** [comment]
This is cool
