### ISSUE TITLE
Layout: small window notifications center breaks layout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80995]
Steps to Reproduce:

1. make window very small
2. click on the notification icon (needs a bit of attempts, doesn't always reproduce)

**OLD:**
![image](https://user-images.githubusercontent.com/900690/64971506-19c5a780-d8a8-11e9-905d-bbd9ce14fa22.png)

**NEW:**
![image](https://user-images.githubusercontent.com/900690/64971647-48dc1900-d8a8-11e9-8b9d-3e5141c00553.png)

**Comment by sbatten** [comment]
rob and I looked into this and only could repro with the following steps:
1. Make the window narrow
2. Ensure sidebar is visible
3. Open the notification area with lightbulb
4. Hide the sidebar with keyboard

Using dev tools we could "fix" the issue just by toggling some css properties which makes it difficult to say we are doing something wrong as the resulting DOM is the same but displayed differently. 

While it sucks that this happens, these narrow window issues seem common as we try to render 400px worth of stuff into a 200px window. I still wonder why we don't enforce a minimum width. In Chrome, this is automatically done and makes the repro impossible.
