### ISSUE TITLE
react file with .js extension and JavaScript React language doesn't work very well

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#81]
# errors
![2015-11-18 16_15_18-view js - cis-v2-frontend - visual studio code](https://cloud.githubusercontent.com/assets/941075/11249737/e115e850-8e0f-11e5-9566-3c5ae0164e77.png)
![2015-11-18 16_15_32-view js - cis-v2-frontend - visual studio code](https://cloud.githubusercontent.com/assets/941075/11249738/e135b748-8e0f-11e5-8035-3d0922cd6680.png)

# .js file with errors
![2015-11-18 16_17_12-](https://cloud.githubusercontent.com/assets/941075/11249739/e1423cac-8e0f-11e5-913e-11b7fe65f755.png)

# .jsx file without errors
![image](https://cloud.githubusercontent.com/assets/941075/11249820/57dbe4e4-8e10-11e5-96a4-fee57f5243d4.png)

**Comment by lwansbrough** [comment]
I'm also experiencing this issue. Ignoring it for now, but occasionally I run into an actual syntax that would have been caught if I hadn't trained myself to ignore them! :)

**Comment by tgienger** [comment]
I believe this is because static properties, rather any class property declared this way, is an ES7 feature and code doesn't yet have support for it.

Question though, are you guys getting bracket completion when using .jsx extension? I'm not. I don't get auto indent either, so I've been using Sublime when working with React at all lately.

**Comment by luisrudge** [comment]
Well, it's an ES7 feature, but it doesn't highlight any errors when you use the .jsx extension..
Also, it's even highlighting the `<div>` tag so... Something is wrong :D

**Comment by lwansbrough** [comment]
As far as I'm concerned this fix should be better support of JSX contained in `.jsx` files and an addition of the ability to select which file parsing I want to use for each filetype.

**Comment by davezuko** [comment]
JSX support in `.js` files is one of the only things keeping me from using VSCode as my primary editor. +1 for getting some sort of support for this.

**Comment by Ben07** [comment]
+1.I like this feature.

**Comment by builden** [comment]
+1 add es7 support

**Comment by jedmao** [comment]
same issue here

**Comment by deathmood** [comment]
@tgienger  +1 also have this issue - nor auto indent neither bracket auto close

**Comment by vintem** [comment]
Same here, it would be good to have jsx support on .js files

**Comment by cnjon** [comment]
+1

**Comment by jrieken** [comment]
Yeah, no proper support for JSX yet. Closing as dope of #140

**Comment by vishal18-gupta** [comment]
// Place your settings in this file to overwrite default and user settings.
{
    "files.associations": {
        "*.js": "javascriptreact"
    }
}

**Comment by vishal18-gupta** [comment]
Refer http://stackoverflow.com/questions/32832264/change-language-to-jsx-in-visual-studio-code/37592711#37592711?newreg=f24a9655438c47e2b780380cec1391ef . It worked for me
