### ISSUE TITLE
Extension commands are displayed to user before extension is activated

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#810]
Any commands an extension defines appear to be shown in the command palette even before the extension is activated to contribute a handler for the command.

This leads to issues like https://github.com/Microsoft/vscode-go/issues/124.

Ideally, executing one of these commands would force activation of the extension.

**Comment by egamma** [comment]
You have to register activation events for the commands, e.g.,

```
	"activationEvents": [
		"command:extension.sayHello"
	],
```

At some point before the beta, we have implicitly activated commands, but for consistency we have switched to explicit activation events also for commands.

**Comment by lukehoban** [comment]
Okay - I'll add those.  But it's never correct for me to declare a command in package.json and not ask for it to be an activation event is it (it will always just throw up a confusing error to the user)?

Shouldn't Code either:
1. Not show any commands that are registered but not listed as activation events to the user, or:
2. Automatically treat every registered command as an implicit activation event.

**Comment by egamma** [comment]
Contributions and activation events are separate concepts that cannot always be tied together as you suggest. For example, a contribution wants to be activated when a markdown file is opened, but it didn't contribute the markdown language. This contribution will only register an activation event.

We had implicit activation registration for commands, but this was inconsistent with other contributions, that do not implicitly register an activation event. In the end we have decided to go for consistency and to always require activation event declarations. 

I agree that we should improve the error message, created a separate issue to track this.

**Comment by lukehoban** [comment]
I agree that these concepts can't be combined into a single concept.  But I still think one of the 2 options I mentioned makes sense.  

Right now, every command I add will be shown to the user but will fail by default unless I also add it to the activationEvents.  

It never makes sense for me to add a command but *not* want that command to require activating my extension - since the handler for that command must live in my extension and will fail if executed before my extension is activated.

**Comment by egamma** [comment]
Regarding the suggested options:
>Not show any commands that are registered but not listed as activation events to the user

To not show a contribution when it is declared in the package.json when there is no activation event is problematic. Since in this case the developer gets no feedback that something is wrong. It will be difficult to debug why an extension doesn't show up in the command palette. It is better to show an error with a hint how to fix the problem, than to silently fail.

>Automatically treat every registered command as an implicit activation event.

We did this earlier and we got feedback from internal users that this is inconsistent and confusing. For this reason we now require that the user explicitly declares the activation event.

**Comment by stkb** [comment]
Just came across this problem myself and found this issue.

I agree with @lukehoban that all commands contributed by an extension, should be added as activation events for that extension automatically. Don't really understand how it's "inconsistent and confusing" not to.

The alternative, as it is now, is that the extension author can forget to add commands as activation events (easily done with many commands); and vscode throws the user a needless error when trying to invoke the command, when it knows, in fact, exactly what to do.
