### ISSUE TITLE
vscode extentions' information not loading

### ISSUE THREAD

**Issue by ahmsalah** [microsoft/vscode#81003]
Everything is working properly except that when I open the extenstions tab and click on any extension, this is what I get ↓↓↓
I also can't install or update any extensions, I get an error Failed to update/Install with CTA "Download Manually" as shown in the image below

![Capture](https://user-images.githubusercontent.com/50025978/64984364-fc520700-d8c2-11e9-8501-bc92f77e4402.PNG)

- VSCode Version: 1.38.1
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Looks  DNS issue. #78783 #78872
Can you try to access this image? 

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/
