### ISSUE TITLE
Jump to Markdown source after single click in Markdown preview

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#81000]
It seems this feature is actually supported but requires a double click in Markdown preview. I guess very few people know about this feature. It's unintuitive becauae:

- Markdown preview is a HTML document. Double-click in HTML means selecting the whole word.
- Double clicking to select the whole word actually selects the whole word, but then tab loses focus to the editor.

Changing it to a single click would make it intuitive, used more often. Single click would jump to source, while double click would recover the focus of the Markdown preview and let you finish selecting, without losing the focus to source tab after finishing the selection.

**Comment by Nowaker** [comment]
> Please also check if it is already covered by an existing one

Dear Mr Bot, unfortunately, it's not.

**Comment by mjbvz** [comment]
Please use the issue template. Also check if this reproduces in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled.

/needsMoreInfo
