### ISSUE TITLE
Terminal: resizing the panel clears the display

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#8100]
- VSCode Version: Insider build - 2016-06-24T05:07:35:941Z
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new terminal
2. Type something (I'm running grunt)
3. Resize the panel

The cursor seems to move, and the text disapears.

![terminalvscode](https://cloud.githubusercontent.com/assets/199648/16337252/2eac1a3e-3a14-11e6-9562-fd1da781deb8.gif)

**Comment by Tyriar** [comment]
@warpdesign can you confirm whether this still happens in latest insiders? If it does can you check the console in dev tools (Help > Toggle Developer Tools) for errors?

**Comment by warpdesign** [comment]
@Tyriar it is still present in latest insider build (Insiders 1.4.0-insider (583f439c1d49128a4775c1ba5a1ac8c6ddd63d5f, 2016-07-12T05:07:12.670Z) on Windows_NT ia32 10.0.14385).

**Comment by Tyriar** [comment]
Can reproduce when a program is running

**Comment by Tyriar** [comment]
Reproduces in regular cmd.exe too so closing this off.
