### ISSUE TITLE
Debug Call Stack - Multiple Running Tasks Issue

### ISSUE THREAD

**Issue by timdog** [microsoft/vscode#81005]
Issue Type: <b>Bug</b>

When debugging in VS Code I have multiple apps running in the Debug Call Stack at any given moment. I run NPM as one task and then start and stop a "Lauch Chrome" app to debug my application. Up until the latest VS Code update anytime I would launch the Chrome app it would become highlighted in the call stack and debug widget. This made it easy to stop and start the app quickly without having to stop my NPM. Now it's not highlighting the Chrome app and staying on my NPM App so I have to make an extra click first before being able to stop the web app in Chrome.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:35.387Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (14.23GB free)|
|Process Argv|--folder-uri file:///c%3A/Git%20Repositories/Bolt.Web|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
debugger-for-chrome|msj|4.11.7
vscode-extjs|Sen|1.0.1
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by isidorn** [comment]
As designed.
We have decided to change the focus behavior, that it only gets focused once the breakpoint is hit.
Just startgin a new session is not longer auto focusing it.
If we get more feedback regarding this we might consider introducing an option.
 However for now, closing as designed.
