### ISSUE TITLE
Show tracked files first in git changes list sorting

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#81008]
- VSCode Version: 1.38.1
- OS Version: 10.14.6

Steps to Reproduce:

1. Open git tracked project containing some tracked files (staged and modified), and lots of untracked files (files not intended to be tracked in the repo)

The files are listed in no particular apparent, usable order, meaning the user has to dig through the list to find relevant files to click for staging changes or viewing.
![image](https://user-images.githubusercontent.com/5124946/64990485-e716b180-d89d-11e9-934d-d781a48b5090.png)
all the files with `U` are untracked and not intended to be tracked.

**Expected:** sort by tracked files list first, then unstaged , then untracked files last 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
#40712
