### ISSUE TITLE
Underline key is invisible in terminal

### ISSUE THREAD

**Issue by wedsonlopes** [microsoft/vscode#81011]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by wedsonlopes** [comment]
Underline key"_" is invisible in terminal of visual studio code.

**Comment by jeanp413** [comment]
duplicate of #35901

@wedsonlopes read that post for a workaround like changing `terminal.integrated.fontFamily` or `terminal.integrated.fontSize`
