### ISSUE TITLE
Add secondary tree for directories?

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode#81014]
In the Explorer bar, there's currently one tree view for the current workspace ("Folder"). It might be helpful to add an option for user to add another tree view (or more, but I guess no one has a monitor that high), because some projects' workflow involve actively hacking two subdirectories: e.g. works in LLVM often requires browsing files in include/ and src/.

**Comment by kieferrm** [comment]
It sounds to me that would you describe is what we call 'Multi-root-folder workspaces'. 
<kbd>F1</kbd> > `Workspace: Add Folder to Workspace...`

**Comment by Leedehai** [comment]
I disagree... what I'm proposing is a secondary view of the current workspace's directories, not adding another root.
