### ISSUE TITLE
Can't open more than one file at a time

### ISSUE THREAD

**Issue by richiephp** [microsoft/vscode#81012]
Issue Type: <b>Bug</b>

I can't open two or more files at a time 
When I click files on the left side panel, it closes down the opened file and opens the clicked file, I normally get more than two files opened at a time

I have tried this, 
https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
and the settings, but it just not making it re-appear again

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|2.2.2
Angular2|joh|8.1.1
LiveServer|rit|5.6.1

</details>

**Comment by cj81499** [comment]
Are you single or double clicking? VSCode lets you view a file with a single click and open with a double click.

**Comment by richiephp** [comment]
No, found what the problem was, I didn't have files in the Open Editor section, sorry to bother you lot

**Comment by kieferrm** [comment]
When you set
```json
"workbench.editor.enablePreview": false
```
there are no preview editors. Every file you click in the explorer opens in a persistent editor, i.e. one that you need to close explicitly. If that's not what you see, please attach a screen recording that helps us better understanding the issue.
