### ISSUE TITLE
Re-apply revert of 0772a8fcc90f50bf125c2ab3286a3b950276516b

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81013]
0772a8fcc90f50bf125c2ab3286a3b950276516b seems to have broken oss for me (after a full rebuild, the window is blank)

As I don't know how to fix this, I've reverted two commits: 7a9dfd33eeeec96a39091ba0508b05a8e7c05345 0772a8fcc90f50bf125c2ab3286a3b950276516b

Please look into reapplying them with a fix

**Comment by sandy081** [comment]
Its because of not removing the invalid import from `workbench.common.main.ts` after refactoring.
it was working for me when I pushed the changes. May be it was cached

Fixed it.
