### ISSUE TITLE
not reopening previous session

### ISSUE THREAD

**Issue by badri-n18** [Microsoft/vscode#8101]
- VSCode Version: 1.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. 
2.

**Comment by dbaeumer** [comment]
@badri-n18 Could you provide more details about what is not working?

**Comment by bpasero** [comment]
@badri-n18 if you are not opening a folder in VS Code, we do not restore any previous UI state. Could it be that?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
