### ISSUE TITLE
Blank screen when opening a folder from command line

### ISSUE THREAD

**Issue by clarking** [microsoft/vscode#81025]
When i try to open a project from the command line using the "code ." command it launches a window with no content, if i close it and execute the command again same happens.

the only way to fix it, is quit vscode and then execute the command "code ." again to get a working ui inside the window.

<img width="1440" alt="Screen Shot 2019-09-16 at 9 11 10 PM" src="https://user-images.githubusercontent.com/8283993/65011345-16daaf00-d8c8-11e9-8966-c5f93d1d4ff8.png">

This started happening a couple of weeks ago with an update, im sorry i don't remember exactly wich was.

As a side note: the folder i'm opening is a samba mounted folder inside "/Volumes" from another computer in my local lan.

- VSCode:

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0

To reproduce:
0.- connect to samba server with Finder.
1.- ensure that vscode is closed.
2.- open terminal and navigate to the project folder
3.- execute "code ." inside the folder
4.- wait for a window to appear with no content inside
5.- close the window, and execute the command again from the command line
6.- wait for same empty window
7.- quit code completely and execute the command again
8.- now vscode works

Thanks for the amazing editor guys, cannot live without it.

**Comment by kieferrm** [comment]
@clarking just to make sure that I understand you correctly. You execute the same `code .` three times. During the first and third time vscode is not running. During the second time it's running. 

Where is VS Code installed? Also on the Samba drive or locally on your Mac? 
What happens if you run something like `ls -R` in your samba folder before step 3?

**Comment by clarking** [comment]
@kieferrm yes, it continues launching same blank screen until i quit the program completely and relaunch it from the same command line window.

**Comment by kieferrm** [comment]
@clarking I had one more question: What happens if you run something like ls -R in your samba folder before the first `code .`

**Comment by clarking** [comment]
@kieferrm the `ls -R` command runs normally, lists every subdirectory recursively

**Comment by aeschli** [comment]
Can you try `code . -verbose` ?

**Comment by clarking** [comment]
@aeschli i tried that command and got the following output

```
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
```

code doesn't launch after that output in the terminal

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.
