### ISSUE TITLE
Easily disable syntax highlighting inside typescript comments

### ISSUE THREAD

**Issue by n370** [microsoft/vscode#81020]
It is super confusing to see syntax-highlighted typescript snippets inside TSDoc comments along with actual typescript code as you can see in the image bellow. 

<img width="399" alt="Screen Shot 2019-09-17 at 00 07 04" src="https://user-images.githubusercontent.com/1547648/65008256-20bbdc80-d8df-11e9-922f-afc44ee20686.png">

I wish there was a simple way to disable syntax highlighting inside comments.

**Comment by n370** [comment]
https://github.com/Binaryify/OneDark-Pro/issues/190

**Comment by mjbvz** [comment]
Duplicate of #65780

**Comment by n370** [comment]
Thanks for triaging it @mjbvz and sorry for rushing into creating a new ticket.
