### ISSUE TITLE
Logpoints to show which line they came from

### ISSUE THREAD

**Issue by mendeljacks** [microsoft/vscode#81026]
When using the logpoints feature it is unclear where they came from and there is no way to search which line caused it to happen. It would be nice to see which line they came from as a clickable link in the terminal. Or at least a list of logpoints that can be toggled without having to go to every file and search for them

**Comment by isidorn** [comment]
This works for me perfectly fine for Node debugging.
I suspect that you are not debugging Node but using another debug extension. If that is the case please file this issue against that extension and tell them that for LogPoints they need to send source objects and that VSCode will render the link as clickable (just like it works for node in my picture).
If you are debugging node let me know and provide exact repro steps and I can reopen this. Thanks

![Screenshot 2019-09-18 at 10 17 06](https://user-images.githubusercontent.com/1926584/65130339-7d151e00-d9fd-11e9-87b4-8ff2dd026c56.png)
