### ISSUE TITLE
[BUG] Debugging a single python file

### ISSUE THREAD

**Issue by ChaosGT** [microsoft/vscode#81023]
Issue Type: <b>Bug</b>

1. Open a single python file
2. Choose Debug -> Start without debugging
3. Repeat step 2 for several times
The running command may occasionally include all the system environments, cause the shell get System.ArgumentOutOfRangeException.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.13GB free)|
|Process Argv|C:\Users\nixius\Desktop\x.py|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.0
vscode-language-pack-zh-hans|MS-|1.38.4
python|ms-|2019.9.34911
polacode-fork|Tox|0.5.1

(1 theme extensions excluded)

</details>

**Comment by ChaosGT** [comment]
It makes it worse that after that bug, VSCode will get unresponsive. The only way is to restart it.

**Comment by kieferrm** [comment]
The actual issue appears to be with the Python extension, however, VS Code should not become unresponsive if your machine is still responsive.

**Comment by ChaosGT** [comment]
However the fact is VSCode will got about 1/5 chances to be unresponsive after the bug happened.
Thanks  for your reply. Maybe I should try another Python extension.
