### ISSUE TITLE
VSCode is downgrading/upgrading everytime I start it

### ISSUE THREAD

**Issue by martinwk** [microsoft/vscode#81030]
Version: 1.33.1 (user setup) / 1.38.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. start vscode, it has version 1.38.1
2. than I close and restart vscode and then it is (back) at version 1.33.1, requiring a restart to install update. 
3 After doing this, it is again at version 1.38.1
4 Restarting again will go back to version 1.33.1 and the loop continues forever

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
Please uninstall the old version manually and install the new version. Thanks!
