### ISSUE TITLE
Visual Studio Code shouldn't hijack .config extension association

### ISSUE THREAD

**Issue by MNF** [Microsoft/vscode#8103]
After installing 'Visual Studio Code' .config files started to be associated with VSCode.
I am not sure that VSCode is a better editor for config files than Visual Studio or Notepad++. So user should make a decision which program should be associated with each extension, in particular such multi-purpose as .config. Installation should associate with VSCode only new extensions, that not used by anyone else.

And now in file explorer for files with .config extension type is shown as 'Visual Studio Code'.  It doesn't make any sense.
Please fix the installation ASAP.

It's a second bug with VSCode type associations that I noticed 
[Installation of vscode-powershell replaced File Explorer right-click menus for .ps1 files ](https://github.com/Microsoft/vscode/issues/6387) 

- OS Version:Windows 10

Steps to Reproduce:Install VSCode

**Comment by joaomoreno** [comment]
#8687

**Comment by joaomoreno** [comment]
My belief is that Code doesn't associate itself automatically, but simply registers as a possible editor for such files. You can always change this editor. Not sure why Windows picks Code by default after installation, but will look into it in #8687
