### ISSUE TITLE
A11y_HDInsight Tools for VSCode_HDInteractive: Hive Batch_Keyboard: Focus is not at all going to "Results", "Messages" expandable/collapsible controls and hence we are unable to access those controls

### ISSUE THREAD

**Issue by v-supupp** [microsoft/vscode#81037]
**Environment Details:**
https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
**Version:** 1.34.0
**OS Version:** Windows 10, MAC OS

**Repro Steps:** 
1. Download and install HDInsight's for VS code from the URL: https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
2. Open any hql query and link with the cluster using proper credentials
3. Select the code and press shift + F10
4. Navigate till “HDInteractive: Hive Batch” or use short cut key “Ctrl + Alt + H”
5. Try to tab till "Results", "Messages" expandable/collapsible controls and check whether we are able to access those controls or not

**Actual Result:** 
Focus is not at all going to "Results", "Messages" expandable/collapsible controls and hence we are unable to access those controls

**Expected Result:** 
Focus should go to "Results", "Messages" expandable/collapsible controls and when we press enter expand/collapse actions should get performed

**User Impact:** 
Keyboard only users will find difficult while navigating within the application if controls are not accessible using keyboard

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachment:**
[Bug 81037.pptx](https://github.com/microsoft/vscode/files/3620676/Bug.81037.pptx)

**Comment by isidorn** [comment]
Please file against extension. Extension authors can destill the issue and figure out if this is on the vscode side and if it is they can file this back to the vscode repository using nice bug description and nice readable steps using VSCode terminology. Thanks
