### ISSUE TITLE
Terminal 'on right' - first line hidden

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#81032]
Issue Type: <b>Bug</b>

This only happens sometimes, and I can see no pattern. 

Open the terminal in Windows 10 (at least), and selet 'Move Panel Right' by right-clicking the terminal frame's title bar.

The first line of the terminal is then hidden by its title bar.

Clear the terminal, and you cannot see the line taking input.

But only sometimes.....  The current instance of the issue resolved when I selected the option to file a bug report.

![image](https://user-images.githubusercontent.com/512816/65027594-eb44dc80-d93a-11e9-932d-15f12642f242.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|10.5.0
npm-intellisense|chr|1.3.0
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
rainbow-csv|mec|1.3.1
formate|Mik|1.1.3
dotenv|mik|1.0.1
remote-wsl|ms-|0.39.5
vscode-typescript-tslint-plugin|ms-|1.2.2
vetur|oct|0.22.3
github-actions-vscode|Oma|2.7.0
rust|rus|0.6.3
RustyCode|sav|0.19.1
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.8.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
