### ISSUE TITLE
Docker extension icon missing in remote VS Code Window

### ISSUE THREAD

**Issue by blakeex** [microsoft/vscode#81031]
Issue Type: <b>Bug</b>

Steps to reproduce error:
1) Install Docker extension 0.8.1 (written by Microsoft). Dophin icon is shown at the Activity bar in the main VS Code.
2) Open a new remote windows (press an icon at bottom right corner) in the main VS Code window
3) Click "Remote-WSL: New Window using Distro" at the Command-Palette
4) Click Ubuntu-18.04 (my default Distro).
5) Open any local folder from Ubuntu in a new remote VS Code window.

Actual result:
Dolphin icon is not visible at the Activity Bar of the remote VS Code window.

Expected result:
Dolphin icon should be visible at the Activity Bar of the remote VS Code window.

Note:
Last week I could see Dolphin icon in the remote VS Code window. This bug happens on 16th September 2019, Monday.

![image](https://user-images.githubusercontent.com/14045571/65022389-ce9fa900-d928-11e9-8128-da12ad6ddd47.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7440HQ CPU @ 2.80GHz (4 x 2801)|
|Memory (System)|15.88GB (6.31GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-format|fox|6.1.1
jenkins-declarative-support|jmM|0.1.0
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
jenkinsfile-support|sec|0.1.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

@blakeex I can't see `ms-azuretools.vscode-docker` in your extensions list. Could you please check if it is in list of extensions when you are in Remote VSCode window.

**Comment by blakeex** [comment]
@IllusionMH , I have just installed `ms-azuretools.vscode-docker` in the Remote VSCode window.

I can see the Dolphin icon at the Activity Bar. That is good.

However, all my Docker images, containers, networks are all visible at the Dolphin icon at original VSCode activity bar, not at the Remote VSCode.

In the Remote VSCode window, I got the screenshot below from the Docker extension:
![image](https://user-images.githubusercontent.com/14045571/65151594-4e5b6f80-da1e-11e9-9192-209d5aa6d6dc.png)

Why this behaviour is different from my Remote VSCode user experience last week, where I could see all images, containers at the Remote VSCode?

Thank you

**Comment by blakeex** [comment]
Hi, I have fixed the missing Docker information at the Remote VSCode activity bar.

I run `export` at the Terminal at Remote VSCode, then look for DOCKER_HOST shown in the output. Copy the value.

After that I go to Settings --> Type "docker" to search for the settings of docker extension --> find Docker:Host, then paste the value in it.

We can close this issue now.

Thank you very much.
