### ISSUE TITLE
Intellisense sees exported `exports.property`, but not `module.exports.property`

### ISSUE THREAD

**Issue by shakvaal** [Microsoft/vscode#8104]
Intellisense ignores exported properties when they are written as `module.exports.property`, while `exports.property` works fine.

- VSCode Version: 1.2.1
- OS Version: Windows 10 x64 Enterprise

![jsconfig_david](https://cloud.githubusercontent.com/assets/4275080/16338797/8646dba4-3a27-11e6-9270-b27afac2354e.png)
![b](https://cloud.githubusercontent.com/assets/4275080/16338798/8999b54c-3a27-11e6-84ec-ede9fc6d1e0a.png)
![a](https://cloud.githubusercontent.com/assets/4275080/16338802/8b23ccfe-3a27-11e6-93a2-1ffe1de46d8b.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9360

**Comment by saggafarsyad** [comment]
Hello, I'm having this problem too. I reproduce the same approach but intellisense is not working. Here is my vscode version:

![screenshot_13](https://cloud.githubusercontent.com/assets/7218502/18006164/7c557c18-6bc8-11e6-82ed-770509b7aca1.png)
