### ISSUE TITLE
Toggle all breakpoints

### ISSUE THREAD

**Issue by rolandleth** [microsoft/vscode#81048]
Hello!

Would be nice to have a keybinding to toggle breakpoints, besides de/activate. Or a `when` clause along the lines of `breakpointsDisabled` so we can do this ourselves. Would be a nice quality of life improvement, by having one less keybinding to worry about.

Have a great day!

**Comment by IllusionMH** [comment]
These are list of actions that can be performed with breakpoints.
![image](https://user-images.githubusercontent.com/1312662/65050261-c6b72780-d96f-11e9-9db9-b8e7d584a3ec.png)

You can assign any shortcut to them.

Do you need other actions that are not available with this menu? (unfortunately it is unclear fro me from provided description)

**Comment by rolandleth** [comment]
One that toggles, as in if they’re enabled, it disables them and vice-versa.

Just like the last one, toggle breakpoint, but for all of them at once.

**Comment by isidorn** [comment]
@rolandleth just use the command Debug: Enable All Brekapoint. And Debug" Disable All Breakpoints.
You can also activate / deactivate them

**Comment by rolandleth** [comment]
@isidorn I knew I can do that, @IllusionMH pointed it out as well; the point of the issue was another, though ...
