### ISSUE TITLE
Terminal becomes very, very slow and VSCode freezes

### ISSUE THREAD

**Issue by pintux** [microsoft/vscode#81047]
Issue Type: <b>Performance Issue</b>

It happens often when I open 3-4 terminal "tabs".
When a terminal gets very slow VSCode becomes unresponsive.
In process explorer, the CPU for 
 window (package.json — myproject-feat-openapi)
goes to 285%

And I have to quit VSCode.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    82	 20174	code main
    1	   311	 20175	   gpu-process
    1	   393	 20177	   window (package.json — myproject-feat-openapi)
    0	     0	 20348	     /bin/bash -l
    0	   213	 20352	     extensionHost
    0	    16	 20945	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=20352
    0	     0	 20946	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=20352
    0	    16	 20951	       electron_node tsserver.js 
    0	    82	 20952	       electron_node tsserver.js 
    0	     0	 20954	         electron_node typingsInstaller.js typesMap.js 
    0	     0	 50316	       electron_node server.js 
    0	     0	 50318	       electron_node server.js 
    0	    16	 20355	     watcherService
    0	     0	 21180	     /bin/bash -l
    0	    16	 48454	       node dist/index
    0	    33	 54340	     searchService
    0	     0	 54630	     /bin/bash -l
    7	    33	 20528	   shared-process
    0	     0	 54936	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	 54808	   window (Process Explorer)
    3	    82	 54926	   window (Issue Reporter)
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|10.5.0
pm2-explorer|ale|0.0.6
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.30.2
vscode-dash|dee|2.2.0
githistory|don|0.4.6
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|2.2.2
todo-tree|Gru|0.0.153
rest-client|hum|0.22.0
docthis|joe|0.7.1
vscode-peacock|joh|3.1.5
vscode-docker|ms-|0.8.1
debugger-for-chrome|msj|4.11.7
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.0
quicktype|qui|12.0.46
vscode-yaml|red|0.5.3
ayu|tea|0.18.0
highlight-matching-tag|vin|0.9.5
vscode-icons|vsc|9.3.0
quokka-vscode|Wal|1.0.247
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.4.2

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Please provide the concrete steps that cause the issue for you. What do you run in the terminal when it happens? Please create a process snapshot using `code --status` when the issue occurs.

**Comment by TNkemdilim** [comment]
I have been facing this issue since I updated to the latest version `(1.38.1)`.
Here is the output of `code --status`:

```
[32368:0918/021739.296497:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS Version:       Linux x64 5.0.0-27-generic
CPUs:             Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1797)
Memory (System):  15.39GB (1.09GB free)
Load (avg):       4, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     --unity-launch
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  unavailable_off
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    2	    95	  6273	code main
    0	     0	  6277	   zygote
   20	   568	  6318	     zygote
    0	   173	  6376	       extensionHost
    0	   615	  6498	         PHP Language Server
    0	   300	  8279	         electron_node intelephense.js 
    0	    47	 31971	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=6376
    0	    95	 31972	         /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=6376
    0	   126	  6395	       watcherService
    0	     0	  7256	       /usr/bin/zsh
    0	    16	  7496	         php artisan serve --port 8001
    0	     0	  7502	           sh -c '/usr/bin/php7.3' -S 127.0.0.1:8001 -t '/home/wink/code'/public/
    0	    16	  7503	             /usr/bin/php7.3 -S 127.0.0.1:8001 -t /home/wink/code/public/
    0	    63	 20880	       searchService
    0	     0	 32133	       /usr/bin/zsh
    0	    63	  6473	     zygote
    0	     0	 32380	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 32381	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    79	 31869	     zygote
    5	    95	  6305	   gpu-process

Workspace Stats: 
|  Window (Release Notes: 1.38.1 - Wink (Workspace) - Visual Studio Code)
|    Folder (Wink): more than 22875 files
|      File types: php(13599) md(475) phpt(390) json(347) xml(292) yml(166)
|                  txt(165) gitignore(128) test(124) png(111)
|      Conf files: makefile(10) package.json(3) tsconfig.json(2)
|                  tslint.json(1)
```

**Comment by Tyriar** [comment]
@pintux I've seen this issue before and believe it's related to Electron 4. The Insiders build was recently updated to Electron 6, could you want to try that out and verify if it's fixed that would be great: https://code.visualstudio.com/insiders/

@TNkemdilim sounds like something different.

**Comment by TNkemdilim** [comment]
Looking closely, I discovered that I had the terminal tab opened down for over 12 - 18 hours. 

I guess it freezes whenever I leave any of the tabs open for such a long time.

**Comment by pintux** [comment]
Using the DOM renderer for Terminal, it works well.
As soon as the issue happens I will post the `code --status` result. Thanks.

**Comment by gferreri** [comment]
I have been noticing severe lag in the terminal as well. FWIW I have noticed that clearing the history with CMD-K speeds it back up.

**Comment by Tyriar** [comment]
I'm going to close this off as it should be fixed in Insiders
