### ISSUE TITLE
A11y_HDInsight Tools for VSCode_HDInteractive: Hive Batch_Keyboard: Unable to access Save as CSV, Save as JSON, Save as Excel, Select all, Copy, Copy with Headers list items in the expanded drop down at grid cells using keyboard

### ISSUE THREAD

**Issue by v-supupp** [microsoft/vscode#81042]
**Environment Details:**
https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
**Visual studio code version:** 1.34.0​
**​OS Version:** Mac OS, Windows 10

**Repro Steps:** 
1. Download and install HDInsight's for VS code from the URL: https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
2. Open any hql query and link with the cluster using proper credentials
3. Select the code and press shift + F10
4. Navigate till “HDInteractive: Hive Batch” or use short cut key “Ctrl + Alt + H”
5. Navigate till grid cells and press shift + F10
6. Try to navigate till Save as CSV, Save as JSON, Save as Excel, Select all, Copy, Copy with Headers list items
7.Check whether we are able to access those list items using keyboard or not

**Actual Result:**
Unable to access Save as CSV, Save as JSON, Save as Excel, Select all, Copy, Copy with Headers list items in the expanded drop down at grid cells using keyboard

**Expected Result:**
We should be able to access Save as CSV, Save as JSON, Save as Excel, Select all, Copy, Copy with Headers list items in the expanded drop down at grid cells using keyboard

**User Impact:**
Keyboard user will find difficult while navigating within the application if list items are not accessible using keyboard

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachments:**
[Bug 81042_Keyboard.pptx](https://github.com/microsoft/vscode/files/3621023/Bug.81042_Keyboard.pptx)

**Comment by isidorn** [comment]
Please file against extension. Extension authors can destill the issue and figure out if this is on the vscode side and if it is they can file this back to the vscode repository using nice bug description and nice readable steps using VSCode terminology. Thanks
