### ISSUE TITLE
Uninstall extensions won't remove them from disk

### ISSUE THREAD

**Issue by Betterxuys** [microsoft/vscode#81046]
Issue Type: <b>Bug</b>

Uninstall an extension in vscode, then go to directory: "C:\Users\USER_NAME\\.vscode\extensions".
You will find out that the extension you just uninstalled in vscode never removed from disk. 
Then re-install the same extension will not download it from web, vscode just reload the old extension file in that directory.

BTW, when you uninstall vscode, it will not remove extensions either. 

-----------------------------------
My computer failed and Windows revert make some files damaged. After that, one of my vscode extensions doesn't work properly. 
I installed and uninstalled both vscode and extensions many times to realize this bug. 
Hope fix it soon.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.38.4
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
cpptools|ms-|0.25.1

</details>

**Comment by kieferrm** [comment]
When you uninstall an extension, the extension is marked as uninstalled but not yet removed from the file system. When you quit VS Code and launch it again, the extension is removed from the file system.

**Comment by Friday32** [comment]
The files of the uninstalled extension are removed after I close and reopen VSCode. But, there is an issue with the uninstall feature. 

Files are not removed if I press the "Reload Required" button after uninstallation  (Version 1.36.1) . VSCode will appear to restart, you will notice the extension list updated, and you will expect to be able to reinstall the extension you just removed.

**Comment by frank-dspeed** [comment]
@kieferrm you should reopen maybe and consider adding extension cleanup also to reload
