### ISSUE TITLE
A11y_HDInsight Tools for VSCode_HDInteractive: Hive Batch_Keyboard: Grids present under "Results" section are not accessible using keyboard

### ISSUE THREAD

**Issue by v-supupp** [microsoft/vscode#81041]
**Environment Details:**
https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
**Visual studio code version:**1.34.0​
**OS Version:** Mac OS

**Repro Steps:** 
1. Download and install HDInsight's for VS code from the URL: https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight
2. Open any hql query and link with the cluster using proper credentials
3. Select the code and press shift + F10
4. Navigate till “HDInteractive: Hive Batch” or use short cut key “Ctrl + Alt + H”
5.Try to tab till Grid sections under results section and check whether using keyboard we are able to navigate till grids or not

**Actual Result:**
Grids present under "Results" section are not accessible using keyboard

**Expected Result:**
Grids present under "Results" section should be accessible using keyboard

**User Impact:**
Keyboard user are unable to see/view the data present in the grid if it is not accessible using keyboard

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}

**Attachments:**
[Bug 81041_Keyboard.pptx](https://github.com/microsoft/vscode/files/3620831/Bug.81041_Keyboard.pptx)

**Comment by isidorn** [comment]
Please file against extension. Extension authors can destill the issue and figure out if this is on the vscode side and if it is they can file this back to the vscode repository using nice bug description and nice readable steps using VSCode terminology. Thanks
