### ISSUE TITLE
Artifacts in editor background - macOS X

### ISSUE THREAD

**Issue by electricarts** [microsoft/vscode#81045]
Is the known problem of background artifacts in the editor back? 

[https://github.com/microsoft/vscode/issues/75171](url)

I have problems with the 1.39 Insider (2019-09-17T05:59:55.803Z) as well as with the 1.39 Exploration Build (2019-09-13T06:37:35.080Z). I'm using a special color profile. A change to another profile doesn't change anything.

Since it doesn't appear in the stable build it will probably be the problem of Electron (this time version 6) again, right?

**Comment by bpasero** [comment]
I am not having sufficient information right now what changed in Electron 6 that could cause this. Maybe others can chime in if any of the related GPU command line options work for them (https://peter.sh/experiments/chromium-command-line-switches/).

**Comment by SebSiecz** [comment]
I'm having the same issue, and while digging around in the developer tools, I found a workaround as it seems it might be styling issues, but I don't know enough about electron to say that for sure.

To get rid of the square artifacts in the editor on short lines, the background style in the following class needs removing: `.monaco-editor, .monaco-editor-background, .monaco-editor .inputarea.ime-input`
![Screenshot 2019-09-18 at 12 31 14](https://user-images.githubusercontent.com/25264413/65141107-40065700-da10-11e9-9060-80e4f7dc63df.png)

and then to get rid of the artifacts in the line numbers row when scrolling below numbered lines, the background style in the following class needed removing. `.monaco-editor .margin`
![Screenshot 2019-09-18 at 12 22 23](https://user-images.githubusercontent.com/25264413/65140731-75f70b80-da0f-11e9-9436-64ef5fee0b64.png)

Not sure how useful that is in properly solving this issue, but this works as a workaround for me.

**Comment by bpasero** [comment]
@electricarts @SebSiecz 
I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue **in either or both web and Electron**?
