### ISSUE TITLE
A11y_HDInsight Tools for VSCode_HDInteractive:Hive interactive_Screen Reader:NVDA/JAWS/VO is not reading the role of the button correctly,it's reading button as link

### ISSUE THREAD

**Issue by v-supupp** [microsoft/vscode#81040]
**Environment Details:​**
https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight​
**Visual studio code version:**1.34.0​
**​OS Version:** Mac OS

**Repro Steps:​**
1)Download and install HDInsights for VS code from the URL: https://marketplace.visualstudio.com/items?itemName=mshdinsight.azure-hdinsight​
2)Open any hql query and link with the cluster using proper credentials.​
3)Switch on the Screen Reader​
3)Use the short cut key ctrl+Alt+H to run the code of HDInteractive: Hive Batch​
4)Navigate to (Maximize, save as csv, save as json, save as Excel) and check whether screen reader is reading the role correctly or not​
​
**Actual Result:​**
NVDA is not reading the role of the button correctly, it's reading button as link​
​
**Expected Result:​**
Nvda should read the role of the control correctly.​
i.e Maximize button ,save as csv  button, save as json  button, save as Excel button​
​
**User Impact:​**
Screen Reader users will get confused while navigating to the Result window as screen reader is not reading the role of the control correctly​
​
**Mas Reference:​**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachments:**
[Bug 81040_Buttons are reading as link.pptx](https://github.com/microsoft/vscode/files/3620726/Bug.81040_Buttons.are.reading.as.link.pptx)

**Comment by isidorn** [comment]
Please file against extension. Extension authors can destill the issue and figure out if this is on the vscode side and if it is they can file this back to the vscode repository using nice bug description and nice readable steps using VSCode terminology. Thanks
