### ISSUE TITLE
Playground causes endless TS LS initialization

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#81059]
Issue Type: <b>Bug</b>

1) Help > Open Playground
-> `Initialzing JS/TS language features` status bar message never goes away

VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T05:59:55.803Z)
OS version: Darwin x64 18.6.0

**Comment by corisco33** [comment]
One thing that solves this for me is just opening a new JS tab and typing something.

**Comment by thien-hoang** [comment]
> One thing that solves this for me is just opening a new JS tab and typing something.

Thanks. I just tried this and it went away for me.
