### ISSUE TITLE
namespace of tooling changet to metadata namespace

### ISSUE THREAD

**Issue by zslaykz** [microsoft/vscode#81052]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
@zslaykz looks like your report was bigger that can be prefilled with URL and you should past it from clipboard or create proper report again.

**Comment by zslaykz** [comment]
When we pull our code from gitlab, on salesfroce we have metadata classes where you can use a namespace for these classes, and it was changed after we pull our classes from tooling to metadata

**Comment by zslaykz** [comment]
![image](https://user-images.githubusercontent.com/32461590/65051002-fd417200-d970-11e9-96de-2bafee3d61c2.png)

**Comment by IllusionMH** [comment]
Not sure how it is related to VSCode itself.

/needsMoreInfo
Does it happen when you pull remote repo with CLI?
Are you sure that there are no such changes in repo you are pulling from?
Are you using any extensions specific to Salesforce? Does this happen when you disable these extensions?

**Comment by IllusionMH** [comment]
/duplicate https://github.com/forcedotcom/salesforcedx-vscode/issues/1550

Please check if you have similar issue and continue discussion in that repo.

It doesn't look like issue with VS Code editor itself.
If you are sure that this is problem with the editor - provide steps to reproduce this issue with extensions disabled.
