### ISSUE TITLE
Fold Toggle

### ISSUE THREAD

**Issue by Brocco** [microsoft/vscode#81057]
Currently the keyboard shortcuts for folding are either "fold ___" or "unfold ___". What I would like to have is the behavior similar to cmd+/ which toggles comments, but for folding.

What I would like to see/have is the ability to bind a keyboard shortcut that would fold based upon the current line if unfolded, or unfold if it is folded.

Note: This would not need to be mapped by default, just an option that users could assign a shortcut to.

**Comment by aeschli** [comment]
duplicate of #18549
