### ISSUE TITLE
Java Intellisense/autocomplete slow/not working

### ISSUE THREAD

**Issue by imankur85** [microsoft/vscode#81055]
After a brief period of working, the Java intellisense either stops working or takes a lot of time to load suggestions.

**Comment by imankur85** [comment]
System Info:

CPUs | Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.90GB (6.93GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extensions Info:

Extension | Author (truncated) | Version
-- | -- | --
vscode-eclipse-keybindings | alp | 0.10.0
gitlens | eam | 9.9.3
vsc-material-theme | Equ | 30.0.0
vscode-lombok | Gab | 0.9.9
aws-cli-configure | mar | 0.3.0
java | red | 0.48.0
vscode-rsp-ui | red | 0.20.2
vscode-server-connector | red | 0.20.2
vscode-xml | red | 0.9.0
vscodeintellicode | Vis | 1.1.9
vscode-java-debug | vsc | 0.21.0
vscode-java-dependency | vsc | 0.5.1
vscode-java-pack | vsc | 0.8.0
vscode-java-test | vsc | 0.19.0
vscode-maven | vsc | 0.18.2

**Comment by kieferrm** [comment]
Please file the issue against the java extension: https://github.com/redhat-developer/vscode-java/issues Thanks!
