### ISSUE TITLE
Code-Insiders hangs after paste shortcut or hovering "Edit" menu entry on macOS

### ISSUE THREAD

**Issue by AlexZeitler** [microsoft/vscode#81064]
- VSCode Version:
```
Version: 1.39.0-insider
Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66
Date: 2019-09-17T05:59:55.803Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
```

- OS Version:
```
Darwin x64 18.7.0
```
Steps to Reproduce:

### Method 1:
1. Open Code-Insiders
2. Press <kbd>⌘</kbd> + <kbd>v</kbd>
3. Code Insiders hangs forever

### Method 2:
1. Open Code-Insiders
2. Hover over the menu bar
3. When hovering over "Edit" entry in menu bar, Code Insiders hangs forever

Does this issue occur when all extensions are disabled?: Yes/No

Yes

Sometimes, restarting Code Insiders several times resolves the issue.

Happens since two days.

**Comment by AlexZeitler** [comment]
Two days ago I reported #80949 and the difference to this report seem to be the Node.js versions.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by AlexZeitler** [comment]
I couldn't reproduce since yesterday but I'll post it here as soon as it happens again.

**Comment by AlexZeitler** [comment]
Today it happened again.

Attached please find the log.
[vscode-log.txt](https://github.com/microsoft/vscode/files/3647860/vscode-log.txt)
