### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by FabioCarpi** [Microsoft/vscode#8106]
- VSCode Version: 1.2.1
- OS Version: Windows 10 x64

With the code:
<?php
$site = substr($site, strpos($site, "format-number"));
$site = substr($site, strpos($site, ">") + 1);?>
<tr><td>VQP</td></tr>
<tr><td style="text-align:right"><?php echo number_format(substr($site, 0, strpos($site, "<")), 0, ",", ".");?></td></tr>

Look the color on second <?php

**Comment by aeschli** [comment]
duplicate of #8739
