### ISSUE TITLE
Git: Command to Close All working-tree files 

### ISSUE THREAD

**Issue by damrem** [microsoft/vscode#81067]
There should be an option to close all working-tree files , but leaves the other files open.

_Note: this feature had been requested in #45133 by @ipochi and mistakenly marked as duplicate of #18651 and closed._

**Comment by OneThatWalks** [comment]
I started looking into this.  I am curious if the git extension should be responsible for this action or the workbench.  I don't yet see a close editor(s) function from vscode.d.ts.  It could be implemented in editorCommands.ts in the workbench.  Looking for some thoughts or guidance.

**Comment by joaomoreno** [comment]
Merging into #18651
