### ISSUE TITLE
Remove IElectronService#openExtensionDevelopmentHostWindow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81060]
Follow up from https://github.com/microsoft/vscode/commit/a62c6ee148f724e64b280359040c6c274bec150d where I added a new method to `IExtensionHostDebugService`: `openExtensionDevelopmentHostWindow`. The idea is that this method is to be removed from the renderer facing side of `IWindowsService`. 

I moved @weinand 's code from `web.simpleservices.ts` into the browser variant of `IExtensionHostDebugService`:

https://github.com/microsoft/vscode/blob/a62c6ee148f724e64b280359040c6c274bec150d/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts#L51

The missing piece is to make this nice on the `electron-browser` side of things. That implementation is still talking through the `IWindowsService` to the `electron-main` side. Ideally this goes through a debug specific channel (maybe one exists already?).

**Code pointers:**
https://github.com/microsoft/vscode/blob/a62c6ee148f724e64b280359040c6c274bec150d/src/vs/workbench/contrib/debug/electron-browser/extensionHostDebugService.ts#L25

https://github.com/microsoft/vscode/blob/a62c6ee148f724e64b280359040c6c274bec150d/src/vs/platform/debug/common/extensionHostDebugIpc.ts#L108

It looks like the launch service in electron-main is also using the method to open an extension development window, so we need to figure that out as well. However I am fine having an extension debug related service also in `electron-main`.

**Comment by isidorn** [comment]
Assigning to this milestone so I look into this this or next week.

**Comment by bpasero** [comment]
@isidorn note that in order to be able to delete `IWindowsService`, I have moved that method to `IElectronService`: https://github.com/microsoft/vscode/commit/8e99945e4165265cc889a11023dd74dd3756dd27

**Comment by isidorn** [comment]
Will do it next week in debt week, not for endgame -> october

**Comment by isidorn** [comment]
I am not really sure what is the current state of this.
Should we just create a new extension host debug related servie in the electron-main. 
However also assigning to @weinand so he is in the loop

**Comment by bpasero** [comment]
The state has not changed much, this is about allowing the renderer to call `openExtensionDevelopmentHostWindow` through debug services and nothing else. Please:
* search for all usages of `openExtensionDevelopmentHostWindow`
* ensure this is not provided from `IElectronService` but your own debug service
* having `openExtensionDevelopmentHostWindow` in `IWindowsMainService` is OK and does not need to change

**Comment by weinand** [comment]
More cleanup via https://github.com/microsoft/vscode/commit/4629c5668299efa72e0ed2073ea4d7bfc3b65ffc
