### ISSUE TITLE
The updated it's not working

### ISSUE THREAD

**Issue by Luchooo** [microsoft/vscode#81066]
Issue Type: <b>Bug</b>

I am download the vs and installed every day  

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2934)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.65GB (1.40GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.802.3
vscode-ionic-snippets|fiv|1.7.1
gc-excelviewer|Gra|2.1.32
Angular2|joh|8.1.1
Angular-BeastCode|Mik|8.0.10
vscode-nebular-snippets|sha|1.0.1
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.4.3
vscode-scss-formatter|sib|1.4.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide proper description of the problem and steps to reproduce?
Have you tried to uninstall and install latest version (looks like you are on 1.36 and latest is 1.38)?
