### ISSUE TITLE
Git path on remote-ssh session incorrect

### ISSUE THREAD

**Issue by emanspeaks** [microsoft/vscode#81061]
Issue Type: <b>Bug</b>

Seems to be related to #78819.  Similarly, I ensured that the correct version of git (2.20) is the first thing in my `$PATH`, and `which git` does indeed point to 2.20.  However, every time the remote session starts, it reports the "system" git version of 1.8.3 and provides a warning about not using a version >= 2.  All I have to do is open a new remote session and I can repeat.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.16299
Remote OS version: Linux x64 3.10.0-957.5.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: fsl|
|OS|Linux x64 3.10.0-957.5.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1200)|
|Memory (System)|125.64GB (1.74GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
dotenv|mik|1.0.1
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
debugger-for-chrome|msj|4.11.7
code-settings-sync|Sha|3.4.2
gitconfig|sid|2.0.1
vscode-djaneiro|the|1.4.2
vscode-icons|vsc|9.3.0
jinja|who|0.0.8

</details>

**Comment by roblourens** [comment]
How are you adding it to your PATH? In a bashrc/profile?

**Comment by emanspeaks** [comment]
We have a server that uses [Lmod](https://sourceforge.net/projects/lmod/) to manage user environments.  In my `.bashrc` on the server, I have a line that loads the Git 2.21.0 module.  After .bashrc completes, here is my `PATH` output from a PuTTY terminal:

```
$ echo $PATH
/software/x86_64/git/2.21.0/bin: <...>
```

It literally puts git as the first item in my `PATH`.  To me, it would seem that is sufficient.  Perhaps there is some complication of the fact that we use Lmod, but it would still seem to me to complete the `PATH` variable updates by the time .bashrc completes.

If I open a terminal within VS Code and do the same thing, that git path is not in my PATH.  It's like that line is being skipped in my `.bashrc` file, but I see a message in the server log that indicates that the module was indeed loaded (the version change message, the "in the module block" and "did I make it here" echoes I added while debugging this, and finally an `echo $PATH`), so I am left perplexed.

Remote - SSH log:
```
[23:04:19.437] > 
> The following have been reloaded with a version change:
>   1) git/1.8.3 => git/latest
> 
[23:04:19.463] > 
> 
[23:04:19.559] > in the module block
> did I make it here?
> /software/x86_64/git/2.21.0/bin: <...>
> Running remote connection script
> Acquiring lock on ~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3
> 761284e3ffb0/vscode-remote-lock.b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> 
[23:04:19.586] > Found existing installation at ~/.vscode-server/bin/b37e54c98e1a74b
> a89e03073e5a3761284e3ffb0...
> 
```

In a VS Code terminal in the same session:
```
did I make it here?
< ... path without git>
$ git --version
git version 1.8.3.1
$ module load git/latest

The following have been reloaded with a version change:
  1) git/1.8.3 => git/latest

$ git --version
git version 2.21.0
$ echo $PATH
/software/x86_64/git/2.21.0/bin: <...>
```

So this shows that there's nothing wrong with the module command per se, but that the shell that the VS Code process ends up using somehow is capturing the PATH before the module command runs.

**Comment by emanspeaks** [comment]
Bonus comment: I also tried adding `export PATH` to the file just in case it was a weird situation where that wasn't happening like it already should, but same results as above.

**Comment by roblourens** [comment]
Have you changed anything in your bashrc since you connected for the first time? e.g. if you run "Kill VS Code Server on Host..." then try to connect again, does it work?

**Comment by emanspeaks** [comment]
I had not changed anything in bashrc.  The Kill made no difference.  I've tried deleting the entire vscode-server folder on the server and starting a new session and still no joy.

**Comment by roblourens** [comment]
This is basically the command we run to figure out what the environment for the extension host should be. Can you run it and see if it gives the correct path?

`$SHELL -ilc '~/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/node -p "JSON.stringify(process.env)"'`

(fix the commit/path to node if needed)

**Comment by emanspeaks** [comment]
Ah, this was the key to identifying the problem.  The lines in my bashrc that added git to the path were in fact inside an if block that was not executing on login subshells because of an environment variable set in the "outer" shell, and it seems that my `PATH` was being reset to "default" in the new login shell.

Not a VS Code problem, but good to know for the future that it's launching a login subshell to run the server!
