### ISSUE TITLE
GitLens hovers no longer work in latest insiders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#81079]
Issue Type: <b>Bug</b>

With the latest insiders, none of the GitLens hovers work anymore -- though normal hovers seem to be unaffected.

![image](https://user-images.githubusercontent.com/641685/65111420-03a01000-d9aa-11e9-8e76-fe9eb23a516a.png)

VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T06:02:08.670Z)
OS version: Windows_NT x64 10.0.18980

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.88GB free)|
|Process Argv|--enable-proposed-api eamodio.remotehub|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by octref** [comment]
It does work for me and I'm on the same commit:

![image](https://user-images.githubusercontent.com/4033249/65169605-b9477f00-d9fb-11e9-9ec7-1efb97c8f846.png)

Why does your process argv include `--enable-proposed-api eamodio.remotehub` though? I don't think that's the cause, just asking.

**Comment by eamodio** [comment]
@octref It looks like this was caused by Live Share. If I remove Live Share all is fine -- and if I re-install it it breaks. Probably because it seems to be infinitely downloading dependencies -- and I see this in the console:
![image](https://user-images.githubusercontent.com/641685/65183129-ce8ad080-da30-11e9-9039-025ebd81b75f.png)

I have that in my args, because RemoteHub has more features with proposed apis :)

**Comment by octref** [comment]
Do you mind opening an issue at https://github.com/MicrosoftDocs/live-share then?

**Comment by eamodio** [comment]
Looks like one is already opened - https://github.com/MicrosoftDocs/live-share/issues/2815. I'll close this out now
