### ISSUE TITLE
Don't Show Again button not working for WSL extension pop-up.

### ISSUE THREAD

**Issue by adriangabardo** [microsoft/vscode#81077]
Problem: A popup opens, displaying: "The 'Remote - WSL' extension is recommended for opening a terminal in WSL." It has a 'Dont Show Again' and an 'Install' option. Clicking Don't Show Again has no effect.

Expected Behaviour: Once I click Don't Show Again, this popup doesn't appear every single time I open the WSL terminal in VS Code.

- VSCode Version: 1.38.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Have WSL Ubuntu installed on Windows.
2. Open the WSL integrated terminal on VS Code.

Does this issue occur when all extensions are disabled?: No.

**Comment by ATheCoder** [comment]
I wanna take a shot at this!

**Comment by ATheCoder** [comment]
Does this happen on different workspaces or on the same workspace?

**Comment by adriangabardo** [comment]
Sorry for the late reply. I see you've already pushed a fix for this, so thanks a lot :)

**Comment by adriangabardo** [comment]
Should I close the issue now?
