### ISSUE TITLE
[json] publish schema of the VS Code-specific JSON Schema extensions

### ISSUE THREAD

**Issue by prbsparx** [microsoft/vscode#81078]
Microsoft has extended JSON Schema 7.0 as part of VSCode. It would be great for Microsoft to publish a "VSCode JSON Schema" so that we can easily find all the available elements for our JSON Schemas.

Example extension that Microsoft did:
`defaultSnippets` as mentioned at the bottom of https://code.visualstudio.com/Docs/languages/json

**Comment by prbsparx** [comment]
It looks like someone mentioned in a comment doing this, but the actual feature (“suggest specific schema”) was rejected. https://github.com/microsoft/vscode/issues/67761
I’m now requesting what @octref mentioned in that comment.

**Comment by aeschli** [comment]
These are really meant to be internal, for our settings editors.
Where would you want to use it?

**Comment by prbsparx** [comment]
@aeschli I'm creating a JSON Schema to use with VS Code. (https://github.com/prbsparx/JsonSchemas/blob/master/k8s.networkpolicies.calico.json) I have the YAML extension from Redhat installed, and noticed that when I put in a string that doesn't match my pattern (e.g. IP Address regex) VS code says "string does not match pattern of <pattern>" which is not friendly to me or my coworkers who will be using it. 
I want to be able to say "string is not a valid CIDR Network Address"
I believe that VS Code has the ability to provide a custom error (patternErrorMessage) but can't confirm what the schema terms are that VS Code uses.

**Comment by vepanimas** [comment]
@aeschli, did I understand correctly that "defaultSnippets" is not even supported for the third-party extensions at the moment? Are there any workarounds to make it work, or do we need to wait for implementation in the VSCode itself?

**Comment by aeschli** [comment]
'defaultSnippets' and 'patternErrorMessage;' and others in JSON schemas can be defined by anyone, but is something that the VScode JSON language server invented. It's probably only make sense to use it for schemas used with VSCode.
Here's the full list: https://github.com/microsoft/vscode-json-languageservice/blob/8020161a681184ce13b349731a11cdae76020c9a/src/jsonSchema.ts#L58

**Comment by vepanimas** [comment]
@aeschli ok, great. thank you for the quick response!
