### ISSUE TITLE
Wrapped lines ignored on click  in integrated terminal

### ISSUE THREAD

**Issue by knomdlo** [microsoft/vscode#81073]
- VSCode Version: 1.38
- OS Version: macOS Mojave (10.14.6)

Steps to Reproduce:

1. Open integrated terminal & echo a link big enough to wrap into multiple lines.
2. Press Cmd+Click on the link to open in a browser.

Expected: The link text is picked along with the wrapped line.
Current: Only the first line of the link is picked.

![vs_code_ter_bug_480](https://user-images.githubusercontent.com/23632994/65086880-d3cb2980-d9f6-11e9-84e5-cba30ab92a71.gif)

Does this issue occur when all extensions are disabled?:No

**Comment by krasoffski** [comment]
Have the same issue with the latest vscode.
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-64-generic
```
