### ISSUE TITLE
Show Some Wrong Suggestions In Console When opened TSX File BUT RUN NORMAL

### ISSUE THREAD

**Issue by tribbys** [microsoft/vscode#81076]
- VSCode Version:1.38.1
- OS Version: Win10 64

Steps to Reproduce:

1.A React Product And use TypeScript
2.TSX File IMPORT Some modules

Does this issue occur when all extensions are disabled?: Yes/No
YES
![TIM图片20190918111441](https://user-images.githubusercontent.com/23066315/65104887-a5a11600-da05-11e9-83d8-c463749568da.png)

**Comment by IllusionMH** [comment]
This errors mean that TS doesn't have any type information about these files.
Do you have installed definitions for these libraries? Like `@types/react`.
Have you checked manual https://ant.design/docs/react/use-in-typescript or https://www.typescriptlang.org/docs/handbook/react-&-webpack.html#install-our-dependencies?
