### ISSUE TITLE
Proposal: Let users set the Height of sidebar areas

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#8107]
- VSCode Version: Latest
- OS Version: Any

At the moment the sections can be collapsed, but there is no way to just hover over and set them to the desired size. Let's for example you want to have a large section for Variables, and a small one for callstack & breakpoints. At the moment there's no way to set these yourself, and if you want a section to be large you have to minimize all others.

Just thought it'd be nice for everyone to have more control over them, set them up to exactly what each person likes.

![screen shot 2016-06-24 at 10 54 30 am](https://cloud.githubusercontent.com/assets/2574412/16341260/3ae58a7a-39fa-11e6-892a-64c36947b27e.png)

**Comment by isidorn** [comment]
Currently it is possible to just drag the header and adjust the size of each area. Or this is not the functionality you are looking for?

![splitview](https://cloud.githubusercontent.com/assets/1926584/16376297/d1b5f2f2-3c5f-11e6-8c4c-769675b03123.gif)

**Comment by MarkPieszak** [comment]
Oh wow you can just click and hold on the bar itself? Well I'm embarrassed I never even thought to try that! A popover would be nice to let people know perhaps? Thank you though!
