### ISSUE TITLE
Tasks not autodetected from hidden package.json or tsconfig.json

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [microsoft/vscode#81074]
Issue Type: <b>Bug</b>

1. Make a basic ts web app with a tsconfig.json and package.json
2. Add some scripts to the package.json
3. Note that your tasks are all automatically detected, yay!
4. Add both package.json and tsconfig.json to your excluded files
5. Reload your window
6. Your tasks aren't there, boo.
 
It seems to happen more consistently with the npm tasks than the tsconfig tasks - I think if VS Code detects that I am inside a .ts file it looks for tsconfig.json even if it is excluded. I'm unsure.

Sometimes even configured npm tasks stop working if I do this, though that seems more sporadic. I can get around that by always using "shell" tasks instead of "npm" tasks, but it's not ideal.

I understand that "exclude" is a stronger word than "hide" and maybe it makes sense that these files would also be excluded from the task detector. But I'm trying to hide those files from students, new programmers who get overwhelmed when there are too many files visible, but who still need to be able to run tasks. Maybe the correct solution is simply to add a "hidden" setting that ONLY hides files from the file explorer while still including them everywhere else.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
make-hidden|dev|3.0.3
gitlens|eam|9.9.3
vscode-open-in-application|fab|1.0.5
vscode-open-in-github|fab|1.2.1
nightswitch-lite|gha|2.2.2
vscode-pull-request-github|Git|0.11.1
vscode-nginx-conf-hint|han|0.1.0
vscode-docker|ms-|0.8.1
powershell|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
java|red|0.48.0
LiveServer|rit|5.6.1
assembly-8086|Ron|0.0.4
code-settings-sync|Sha|3.4.2
prettier-plus|svi|2.0.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-icons|vsc|9.3.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
This is by design. If you exclude a file, then is excluded from everything.

The built in npm extension uses VS Code API to find the package.json, and the API doesn't give a way to ignore the excludes from settings. 

The feature request here is to extend the `findFiles` API to use both an `exclude: GlobPattern` and ignore the default excludes.

**Comment by bpasero** [comment]
Swapping with Rob since this is search API.

**Comment by roblourens** [comment]
You can pass `null` to prevent excludes from applying, but you want to prevent the excludes from settings, while also passing some other exclude pattern? Not currently possible. This seems correct to me though. If those files are 'excluded' it seems like we shouldn't show tasks from them.

**Comment by DavidGriswoldTeacher** [comment]
I think I agree. Exclude is a strong word. However, I think that means my
original feature request stands, and we need a new setting for
"explorer.hidden" or something that ONLY affects the explorer, not other
components. I just like to remove clutter, and package.json and
tsconfig.json become clutter after the project initialization is complete.

**Comment by roblourens** [comment]
I disagree, they are important parts of a project which have to be maintained. Allowing the user to hide files that affect the UI in other ways will lead to confusion, I think.

**Comment by DavidGriswoldTeacher** [comment]
Why is that your choice and not mine? Isn't the point of a customizable
editor that I get to make those choices? My specific use case, as
mentioned, is setting up starter projects for students new to programming.
They don't need to understand those files and I also don't want them
accidentally destroying them, so hiding them is valuable.

My workaround right now is simply to manually fill tasks.json with shell
tasks. It works. But I still think that "hiding" and "excluding" should be
different things.

**Comment by alexr00** [comment]
@roblourens thinking about it some more, I agree that excluded files should not generate tasks. The files are excluded.

@DavidGriswoldTeacher is using exclude to _hide_ files, but exclude is too powerful. This sounds like a new setting for only hiding in explorer, not actually excluding.
Possible duplicates: 
https://github.com/microsoft/vscode/issues/67168
https://github.com/microsoft/vscode/issues/19347
