### ISSUE TITLE
Select with keyboard (not the mouse) in the Terminal + IPython not working as it should 

### ISSUE THREAD

**Issue by scoennz** [microsoft/vscode#81086]
I'm running VS Code on Windows 10 and I use IPython in the terminal for numerical analysis (REPL) (not Jupyter, just a normal IPython shell, launched with ipython.exe). I would like to be able to copy/paste pieces of texts from previous inputs. I know I can use the mouse and right click but I would like to do that with keyboard shortcuts.

IPython uses Emacs style shortcuts, and most of them work (Ctrl-Y for Yank/Paste, Ctrl-k to kill/cut end of line, ...) but I cannot actually select the text with the keyboard. Normally - Emacs style- you would do Ctrl-Space to start a selection, then move the cursor and then cut/copy. But Ctrl-Space inside IPython when run in the terminal window of VS-Code doesn't do anything. I tried launching IPython both from 'cmd' and from 'powershell',  same problem. I also tried to use Shift-LeftArrow/RightArrow to no avail. I must note that if I launch IPython from a 'cmd' prompt separate from VS Code, then Ctrl-Space works. So somehow VS-Code seems not to pass Ctrl-Space to IPython.

Note I have also noticed that in the 'cmd' shell, inside VS-Code, selecting text with Shift-Left/Rightarrow doesn't work either (not even launching IPython). Again this works at the 'cmd' prompt in a separate window. It also So maybe this has to do with 'selecting' inside the terminal. But then Shift-Left/Right arrows work as expected inside Powershell. 

Any solution? It would be great to do select/cut/copy/paste without having to reach to the mouse. Everything works except 'select' ... Would be great if Ctrl-Space could work as expected inside IPythion, and even better if I could use Shift-Left/Rightarrow (window-style selection), but maybe IPython doesn't allow that.

Thanks, Stephane

step to reproduce (Windows):
* Terminal: Select default shell -> Command prompt (cmd)
* Type something, try using shift+rightarrow to select (-> nothing is selected)
* Launch ipython from the command prompt
* Type something, hit Ctrl-Space then move cursor to select (-> nothing is selected)

**Comment by Tyriar** [comment]
Can you try this out using [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there report an issue to https://github.com/microsoft/terminal? They provide the backend for our terminal on Windows.

The above only applies if you're on Windows 10 1903+, older is using a legacy system which we won't be considering these types of changes for.

**Comment by scoennz** [comment]
Same problem in Windows Terminal (using 1903)

**Comment by Tyriar** [comment]
You should report to that repo then
