### ISSUE TITLE
Off-by-one error when hiding source control repos.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#81088]
Issue Type: <b>Bug</b>

When hiding repos in source control, the system jumps from 2 to 0. I.e., starting 3 or more repos open, right clicking to hide one by one, once I remove the 2nd to to last, the last one disappears too.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (22.61GB free)|
|Process Argv|../../../..|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.7.0
copy-relative-path|ale|0.0.2
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|9.9.3
code-runner|for|0.9.14
vscode-pull-request-github|Git|0.11.2
CppSnippets|har|0.0.14
latex-workshop|Jam|8.1.1
json-escaper|jos|1.1.0
vscode-cdecl|kae|1.0.0
vscode-language-babel|mgm|0.0.24
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
vscode-json-editor|nic|0.2.3
indent-rainbow|ode|7.4.0
text-power-tools|qcz|1.11.1
shader|sle|1.1.4
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.3.0
cursorCharCode|zei|0.1.1
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by danielmrussell** [comment]
I can't tell, but I think not. Maybe related in some behind-the-scenes way.

**Comment by joaomoreno** [comment]
Can you show me a screen recording of what you mean?

**Comment by danielmrussell** [comment]
That's funny. I just went to do this but now, instead of going from 2 to 0 shown, it refuses to delete the last one. That seems like a "clever," intended feature., i.e. can't hide them all, gotta have at least one showing. Fine.

My guess is it's *that* logic that is sometimes going wrong and sometimes making this one-off error when it doesn't work right.

I'll capture it on screen if i can reproduce it.

**Comment by joaomoreno** [comment]
Alright, show me when you can, thanks!
