### ISSUE TITLE
cannot use operator mono light italic font.

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#8108]
- VSCode Version:1.2.1
- OS Version:arch linux

Steps to Reproduce:

when i define font family as operator mono or operator mono book its working but i cannot use italic versions of those fonts

**Comment by smkamranqadri** [comment]
+1

**Comment by NikosEfthias** [comment]
well i am not the only one seems like

**Comment by Pandahisham** [comment]
+1

**Comment by pvinis** [comment]
this should be fixed. i also put operator mono as the fontFamily and light as the fontWeight but it stays normal.

**Comment by NikosEfthias** [comment]
@pvinis  nothing is changed still doesn't work for me

**Comment by pvinis** [comment]
same problem exists in atom, but atom allows this extra css file and it works when i change it there. but thats not a great solution. and vscode doesnt even have this solution.

**Comment by admiralicic** [comment]
Set fontWeight to 100 instead of light and it works for me.

**Comment by vinhlh** [comment]
+1

**Comment by vinhlh** [comment]
100 is extra light, not light

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
