### ISSUE TITLE
Rust's syntax highlighting breaks after `r#impl`

### ISSUE THREAD

**Issue by rustka** [microsoft/vscode#81085]
Rust's syntax highlighting breaks after using `impl` keyword as a [raw identifier](https://doc.rust-lang.org/1.37.0/rust-by-example/compatibility/raw_identifiers.html).

---

- VSCode version: 1.38.1
- OS version: Linux x64

## Steps to reproduce:

1. Open the editor;
2. Set language mode to Rust;
3. Paste the following code:

```rust
use r#impl;
fn main() {}
```

4. Comment the first line by prefixing it with `//`;
4.1. This failure could also be prevented by replacing `r#impl` with `r#impl {}`, but this is not the real solution for that case.
5. The syntax highlighting works properly back again.

---

P.S.: I did test it on Atom editor (v1.40.1) and it seemed to work correctly.

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/zargony/atom-language-rust/issues/147
