### ISSUE TITLE
Opening a script in unity locks up Visual Studio code

### ISSUE THREAD

**Issue by TheCrake** [microsoft/vscode#81083]
Issue Type: <b>Bug</b>

Trying to open any script in unity fails and locks up Visual Studio code

Any time I try to open a script, visual studio code does not appear. This was not the case in the past when using previous versions of unity

Now, once I've tried to open a script in unity, opening vs code can't be done manually either. If I go to the task manager and end the vs code tasks, then I get an error message I'm able to launch vs code manually through windows.

If I launch vs code manually through windows, then unity is able to open scripts in vs code by clicking on scripts in unity. It would appear that unity is still correctly able to open scripts in unity, but something about how unity is trying to launch vs code causes vs code to not launch correctly.

This occurs with any unity project

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.21.2

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Investigating this issue should start with the unity/C# extension. Please file the issue there.
