### ISSUE TITLE
Use Replace button in "Find and Replace" widthout jumping to next matching word

### ISSUE THREAD

**Issue by MrOtilk** [microsoft/vscode#81087]
When i want to Find and Repalce some text i want to verify and update the whitespace to match the new text. 

Every time i hit replace, the focus jumps to the next matching text, i have to scroll back manually to edit the whitespace (or step back and forth in history), it woult be better if the replace button did not automatically made the editor jump to the next word. Maybe add a setting that chan change the behaviour of the replace button?

In CODEO (eclipse) every other replace button click makes you replace code, or jump to next match, maybe do it like that?

**Comment by mbomb007** [comment]
This isn't really necessary. Find/Replace can be adjusted/improved with a regular expression that takes whitespace into account.

For example, if you want to replace `foo bar` with `foo`, or `foo ` (with a space at the end) if there wasn't one after replacement, use this:

Find (regex): `foo bar ?`
Replace: `foo `

Or all spaces with a single space:

Find (regex): `foo bar *`
Replace: `foo `
