### ISSUE TITLE
Several perl blocks looking as commented regions

### ISSUE THREAD

**Issue by allancm** [Microsoft/vscode#8109]
- VSCode Version:1.2.1
- OS Version:10.0.10586

Steps to Reproduce:

1. Download https://github.com/AlDanial/cloc/releases/download/v1.68/cloc-1.68.pl
2. Search for $Regexp_Common_Contents{'Common'} = <<'EOCommon' or go line 7251
3. Everything after that line looks like commented code which is incorrect.

**Comment by aeschli** [comment]
Isn't <<'EOCommon' a [HERE doc](http://perlmaven.com/here-documents)? So everything after it is a string until the occurrence of EOCommon.

IMO all is fine. Please reopen if you disagree.
