### ISSUE TITLE
File Save As...to work sensibly

### ISSUE THREAD

**Issue by prnulc** [microsoft/vscode#81098]
I tried.

Version 1.38.1, 
OS Windows 7

When invoking **_File save as_** I would like VS Code to save into the Folder, if one is open, or to give choice.

I've twice had the following experience.  

Use file save as (while in one folder).

Later use file save as (while in a different folder).  It saves into the first folder.  

The first time this happened it overwrote an important file which I had to ask to be restored from a backup. 

It is clearly storing the last location where **_save as_** was used and saving there instead of the current folder.

**Comment by bpasero** [comment]
@prnulc what exactly is your suggestion?
