### ISSUE TITLE
Validation of script references in vue html/template stopped working

### ISSUE THREAD

**Issue by alexeigs** [microsoft/vscode#81099]
What I'm using

- VSCode
- Quasar (Vue)
- Typescript
- Eslint/@typescript-eslint
- Prettier / prettierhtml / Vetur

Current issue:

Until recently, injected script in the <template> of vue files (e.g. onSignIn in <div @click="onSignIn"> was checked against available variables/methods in the <script lang="ts"> part. This has now stopped working and I couldn't figure out what's the reason. Playing around with VSCode/Vetur/eslint settings wasn't successful either so far.

As the above hasn't worked earlier either but just since I started my latest project, I'm not sure what settings is responsible for that part anyway (Veturs' HTML > Validate > Scripts apparently is not enough).

This may not be a bug but an issue many others I know struggle with too without seeing through all the available settings/plugins and their effect on the actual outcome.

**Comment by octref** [comment]
Please open a new issue in https://github.com/vuejs/vetur, with repro case created from https://github.com/octref/veturpack.
