### ISSUE TITLE
Missing temporary change button in the source code manager 

### ISSUE THREAD

**Issue by KaoImin** [microsoft/vscode#81092]
Issue Type: <b>Bug</b>

When update the preview version of VS Code, there is no temporary change button in the source code manager.

VS Code version: Code - Insiders 1.39.0-insider (cc481ab31b5827add5f99a770f2c860d0575df69, 2019-09-18T06:57:33.017Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|-psn_0_4047836|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.12.1
markdown-toc|Ala|1.5.6
vscode-sqlite|ale|0.8.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.2
vscode-dash|dee|2.2.0
vscode-wasm|dts|1.2.1
vscode-rust-syntax|dun|0.0.32
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|30.0.0
code-runner|for|0.9.14
vscode-pull-request-github|Git|0.11.2
latex-workshop|Jam|8.1.1
asciidoctor-vscode|joa|2.7.6
rust-doc-viewer|JSc|1.0.8
language-haskell|jus|2.6.0
Lua|key|0.0.9
Lisp|mat|0.1.9
rainbow-csv|mec|1.3.1
Angular-BeastCode|Mik|8.0.10
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
vscode-language-pack-zh-hans|MS-|1.38.4
python|ms-|2019.9.34911
remote-containers|ms-|0.76.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.6
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.25.1
powershell|ms-|2019.5.0
ide-purescript|nwo|0.20.8
language-purescript|nwo|0.2.1
erlang|pgo|0.5.2
phoityne-vscode|pho|0.0.24
material-icon-theme|PKi|3.9.0
typescript-hero|rbb|3.0.0
rust|rus|0.6.3
pytorch-snippets|SBS|1.0.2
vscode-libra-move|SDK|0.0.10
code-settings-sync|Sha|3.4.2
vscode-leetcode|she|0.15.4
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
tabnine-vscode|Tab|2.1.11
latex-support|tor|3.0.1
codelf|unb|11.7.0
vscode-lldb|vad|1.3.0
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.3.0
vim|vsc|1.10.2
autocomplete-english-word|wus|0.1.7
plsql-language|xyz|1.8.2
markdown-all-in-one|yzh|2.4.2
vscode-proto3|zxh|0.3.0

</details>

**Comment by IllusionMH** [comment]
Could you check for updates one more time? Looks like there was bad release and now it is fixed in latest update
Version: 1.39.0-insider (user setup)
Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66

**Comment by KaoImin** [comment]
This is fixed after updating the latest version (Commit: bdd1971)
