### ISSUE TITLE
Allow to single click file to replace active tab and doubleclick to open new tab

### ISSUE THREAD

**Issue by BinaryHammer** [microsoft/vscode#81093]
I can not configure Visual Studio Code in a way, that when single clicking on a file in the file explorer of the project, it just opens the file in the currently active tab.

I did not find any extensions that give me that feature.

Single click open file has been setup by the following configuration.

    "workbench.list.openMode": "singleClick",

I know there are `Preview`-tabs. But it opens in a new tab. That creates a problem that the tab vanishes when in Preview.
When I do not use `Preview`-tabs I get many open tabs after clicking some files, for example when checking or searching for something.

My main use case for me when using the project explorer: Switching to another file without opening new tabs. I have the navigation buttons for going back. I mainly use Xcode and it would be nice to mimic its behavior: Single click to replace current tab with the file you clicked on, double click to open file in new tab.

**Comment by BinaryHammer** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [better file opening & preview (#77338)](https://www.github.com/microsoft/vscode/issues/77338)

No that is not nearly the same. It was a bug.

**Comment by isidorn** [comment]
@bpasero not sure if it can be configurable to always be opened in the same tab.
Why don't you just disable tabs? That seems to be what you want
	`"workbench.editor.showTabs": false`

As for your original question forwarding to @bpasero to answer

**Comment by bpasero** [comment]
> Single click to replace current tab with the file you clicked on, double click to open file in new tab.

How is that not covered by our default preview feature?

**Comment by isidorn** [comment]
I think if you have an all non preview tabs and you open one in preview it goes into a new tab

**Comment by bpasero** [comment]
@BinaryHammer is that it?

**Comment by BinaryHammer** [comment]
Having no tabs is not an option. Tabs are very useful.

@isidorn It opens in a Preview tab, not a normal tab. That means it will vanish if I change to another tab and single clicking again on an unopened file.

@bpasero No. The default feature is to open a Preview tab. A preview tab will vanish. Opening a file in with a single click will create a Preview tab, when I click on another tab and then on a file which is not yet open, the previous selection vanishes. Having the feature to replace the current tab with a single click will never vanish the tab while in another tab. 

As I said, it is the default behavior of `Xcode`. This way I can have tabs open which represent different content and switch the content without affecting anything else but the one tab. For example every tab is for one depth or type in an architecture: One tab is for assets, one for view, one for the Controller, one for the database, while having multiple of each. If I have three controllers for a view and I am not sure in which one.
I know I could just use the preview tab, like I could just disable tabs, like I could just use no IDE at all. For my workflow, which I used and use with `Xcode` successfully for many years now, this feature would be beneficial for the Web Development I do more and more. Since there are many `Xcode` users and with the introduction of Swift on the server possible much more in the Web World, I could imagine it may be a good idea to have an option to mimic this behavior.

**Comment by bpasero** [comment]
@BinaryHammer please explain to me how your suggested feature would work exactly, e.g. with an example where you talk about a set of files you click on one after the other. Explain how tabs are being created or not.

**Comment by BinaryHammer** [comment]
@bpasero Thanks for your interest. Let's say I open a project and have no files open and having some CSS, JS, PNGs and HTML files.

Example workflow where the feature would be included:
I open a project: No tabs open. Since it does not make sense for me having no tab open I immediately would just open the main HTML file with a double click. Now I have 1 tab open. That was maybe the wrong HTML file, so I single click on a specific HTML file: Still 1tab open, but the file of the tab is now the specific HTML file. Then I want to update some images. Double click on an image to open a new tab (in my head this is now my image tab): 2 tabs open, one with a HTML file one with a PNG file which is active. Since I am not sure how the images are named I just single click one some images and every time the file of the active tab will be changed to the new image: Still 2 tabs open. I single click on the HTML tab and add the path of the images I am interested in. Now I need to update a JS file. There are multiple connected to the active open HTML file. I double click on the JS file I thought would include the functionality: 3 tabs open, JS-file tab is active. But then I realize it should be in the other JS-file, I single click the other JS file and the current tab will now show the content of the new JS file. And so on.

Benefit:
If I want to have a tab for only the current image I am interested in, but do not want to manage more than one tab for it. There is a One-to-one relationship as the tabs I see, but a more complex one-to-many in the files. I want to work on a simplified view . It is easy when this feature would be included. I could just go to the *image*-tab select and search through the images by clicking through and am done. Every time I need to look at the current interesting image. No new tabs, no preview tabs, no tabs to close or change I have to worry about.

Feature:
Single clicking a file in the Project Explorer and if a tab is open and active would select the file in the Project Explorer and set the active open tab to the new file. So when index.html is open and active in a tab and I single click on contact.html, contact.html will be selected in the Project Explorer and the file in the active tab will be now contact.html. No new tabs.

Easiest way to understand would just be to try out Xcode.

**Comment by bpasero** [comment]
Thanks I understand this now.
