### ISSUE TITLE
IBM blockchain paltform error on smartcontract

### ISSUE THREAD

**Issue by rameshsentient** [microsoft/vscode#81094]
i had vscode 1.39.0 and IBM blockchain platform 1.0.10. i have issue while building the smartcontract. issue is
![image](https://user-images.githubusercontent.com/51635015/65142356-283ecb00-da30-11e9-845b-70383bda741b.png)

followings are the versions for needed plugins node - v10.16.3 npm - 6.11.3 docker - version 18.03.0-ce docker-compose version 1.20.1 go version go1.12.5 windows/amd64 OS - windows 10

**Comment by IllusionMH** [comment]
Looks like problem with scripts used in extension. Shouldn't this issue be filled in extension repo?

**Comment by kieferrm** [comment]
Please file the issue against the blockchain extension. Thanks!
