### ISSUE TITLE
VS Code shows multiple source code providers when using symlinks

### ISSUE THREAD

**Issue by NotoriousPyro** [microsoft/vscode#81109]
- VSCode Version: 1.38.1
- OS Version: Windows 10 (1809, 17763.678)

Steps to Reproduce:

1. Create a symbolic link holding your source code repositories
2. Open one of the repositories under the symbolic link path
3. Make some changes and notice that there are two source control providers. (it can take time for it to appear)

Does this issue occur when all extensions are disabled?: Yes

```
C:\Users\ccrawford\SourceCode>dir /al
 Volume in drive C is OSDisk
 Volume Serial Number is 941F-A0C0

 Directory of C:\Users\ccrawford\SourceCode

05/06/2019  12:33    <SYMLINKD>     github [C:\src\github]
05/06/2019  12:44    <SYMLINKD>     unversioned [C:\Users\ccrawford\OneDrive - Flexera, Inc\SourceCode]
               0 File(s)              0 bytes
               2 Dir(s)  541,262,200,832 bytes free
```

**Comment by NotoriousPyro** [comment]
Note: I'm not 100% on the reproduction steps as the above doesn't seem to be reproducing it today. The problem appears to be very intermittent.

**Comment by NotoriousPyro** [comment]
![image](https://user-images.githubusercontent.com/706132/65332338-682fba80-dbb6-11e9-94ee-c10d7ad6d2c4.png)
Today the problem appears.

**Comment by joaomoreno** [comment]
#5970
