### ISSUE TITLE
Vscode unity linux c# omnisharp intellisense temporary fix 

### ISSUE THREAD

**Issue by jesh3526** [microsoft/vscode#81104]
So i've been experiencing problems with intellisense when opening a new unity project. it did not work at all even after installing the C# extension. The problem was that Omnisharp could not find the /Debug directory. But i think the fix below is temporary. Does anyone have a better fix to this problem. a fix that does not require changing a root folder to have users permissions.

- VSCode Version: 1.38.0
- OS Version: openSUSE Leap 15.1

Steps to Reproduce:

1. sudo mkdir -v /Debug
2. sudo chown -v "username":users /Debug

That worked for me.

**Comment by kieferrm** [comment]
@jesh3526 Please file the issue against the C# extension. Thanks!
