### ISSUE TITLE
Need an icon for ''show preview to side"

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8111]
The menu contribution story allows to define an alternative command for a menu item. It shows when you press <kbd>Alt</kbd> while hovering over the item. For `Markdown` we have an action _Open Preview_ and _Open Preview to Side_. The latter is the alternative command of the former, but they use the same icon...

![jun-24-2016 18-00-04](https://cloud.githubusercontent.com/assets/1794099/16343198/1250cca0-3a36-11e6-97df-0288fe897001.gif)

@bgashler1 Pretty please make us a nice icon. The declaration and location is here: https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L58

**Comment by jrieken** [comment]
@kieferrm fyi

**Comment by bgashler1** [comment]
@jrieken I just sent a request to our icon graphic design team.  They should be on it soon :)

**Comment by bgashler1** [comment]
I would like to discuss this convention of using the alt key to change command behavior sometime.  In th mean time, here are the icons.

[PreviewOnRightPane_16x.zip](https://github.com/Microsoft/vscode/files/336030/PreviewOnRightPane_16x.zip)

**Comment by jrieken** [comment]
reopening to move them to right place
