### ISSUE TITLE
VsCode Opening random directory after deleting .spec.ts file

### ISSUE THREAD

**Issue by Tiago-Altus** [microsoft/vscode#81114]
Issue Type: <b>Bug</b>

In my angular project i have a component called reports and 2 services in a service folder under the reports folder. When I delete a service.spec.ts file, after moving it to recycle bin, vscode opens report folder and I have to close it each time. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.9
open-in-browser|tec|2.0.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@Tiago-Altus can you please add a screen recording. Thanks!

**Comment by Tiago-Altus** [comment]
The bug isn't occurring anymore after I follow the same steps to make it happen.
