### ISSUE TITLE
We cannot connect to the Extension Marketplace -- No Proxy

### ISSUE THREAD

**Issue by NeoGlitch** [microsoft/vscode#81115]
Issue Type: <b>Bug</b>

When entering even a single letter in "Search Extension in..." get message "We cannot connect to the extensions Marketplae at this time, please try again later."

I am still getting recommended extensions and my exsistng extension do update. My other computers with Visual Studio code on the same network are working correctly.

Things that didn't work:
Restarting computer
resetting Winsock
Turning off Windows defender and firewall
Tried uninstalling the User(stable) build and reinstalling.
Tried install previous User(stable) build
Tried the zip version.  
Deleting the ..AppData\Local\Programs\Microsoft VS Code folder
renameing the ".vscode" folder
clearing storage in Developers Tools

Things that worked:
The insider builds do work.
Creating another user account and installing did work.

Work arounds:
typing in  @sort:name"name of extension" works

[-1568835449265.log](https://github.com/microsoft/vscode/files/3628068/-1568835449265.log)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
hunspell-spellchecker|den|1.0.1
githistory|don|0.4.6
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|2.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
rest-client|hum|0.22.1
python|ms-|2019.9.34911
python-docs|Muk|0.8.3
autodocstring|njp|0.3.0
indent-rainbow|ode|7.4.0
postcss|ric|2.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.2
markdown-preview-enhanced|shd|0.4.3

</details>

**Comment by sandy081** [comment]
Can you please open console `F1 > Toggle Developer Tools` and open network tab and check requests to Marketplace and see if there are any errors?

**Comment by NeoGlitch** [comment]
I "cleared console" then try to search for an extension.
Nothing appears in the networking tab. 
If I search with a filter such as @sort:rating  the networking tab populates with info but no errors.

It does put 3 messages in the log.  I have added the log. 
[-1568835449265.log](https://github.com/microsoft/vscode/files/3636312/-1568835449265.log)

**Comment by sandy081** [comment]
Can you please try on our insiders and see if the issue appears? You can download insiders from here - https://code.visualstudio.com/insiders/

**Comment by NeoGlitch** [comment]
Yes the insider build still works.  
My original post stated the insider build works:

```
"Things that `worked:
The insider builds do work.
Creating another user account and installing did work."
```

I would of normally just went with the create "new user" route but it would of taken a day to copy the data around.   I have a small network and have to have the same user account on all the computers.

Also have some propriety software that requires me to activate it per user account.  It is a real pain in the butt to get all the software reactivated.  

Visual Studio Code is the only software that is malfunctioning.  I have found other tickets with people with the same problem but they were all closed with no solution.

Any help is appreciated.  Thank you.

**Comment by sandy081** [comment]
1. Are there any errors in the console tab?
2. Can you please open shared process using `F1 > Toggle Shared Process` and check if there are any errors in the console tab?

**Comment by NeoGlitch** [comment]
![2019-10-03 10_23_45-](https://user-images.githubusercontent.com/35854182/66149497-1892bb00-e5c8-11e9-89d2-07b0c4758291.png)

**Comment by NeoGlitch** [comment]
Searching with Console opens....
This just recreates the log files I have already attached.
![Searching with Console Open](https://user-images.githubusercontent.com/35854182/66150493-28ab9a00-e5ca-11e9-93d0-29a81305f763.gif)
[-1570124451543.log](https://github.com/microsoft/vscode/files/3687354/-1570124451543.log)

**Comment by NeoGlitch** [comment]
I can search using filter for extentions
![Searching with rating filter](https://user-images.githubusercontent.com/35854182/66150863-f484a900-e5ca-11e9-9c9a-0a13f43f6abf.gif)
[-1570124756217.log](https://github.com/microsoft/vscode/files/3687368/-1570124756217.log)

**Comment by NeoGlitch** [comment]
This is searching normally with network tab open....
![Searching with network tab](https://user-images.githubusercontent.com/35854182/66151351-fb5feb80-e5cb-11e9-80ff-eac73c542aa7.gif)

**Comment by NeoGlitch** [comment]
This is searching with filter and network tab open....
![Searching with filter and network tab](https://user-images.githubusercontent.com/35854182/66151496-4974ef00-e5cc-11e9-8a6c-2e1ed9b627c0.gif)

**Comment by NeoGlitch** [comment]
Tried to open link:
Using DNS: 8.8.8.8 and 8.8.4.4
https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

Edge:
![image](https://user-images.githubusercontent.com/35854182/66224512-d8e0d780-e68a-11e9-8d06-5fc0adbb9b90.png)

Firefox:
![image](https://user-images.githubusercontent.com/35854182/66224789-a08dc900-e68b-11e9-81fe-8094f54515a0.png)

**Comment by NeoGlitch** [comment]
Then I used hh.exe ttps://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

And this loads the PNG.

At this point I was going to say it wasn't a visual studio code issue since I could access the image from hh.exe.  But when I changed back to DNS: 1.1.1.1 and 1.0.0.1 then Firefox and Edge could load the png.

I **would say at this point the issue is there is corruption in a cached file somewhere. 
The other supporting issue is the portable version has the same issue. 
But since I don't know much how VS code works I cannot fix it.** 

And the image loaded. 
![image](https://user-images.githubusercontent.com/35854182/66224864-d3d05800-e68b-11e9-8788-d22f8c569fbd.png)
![image](https://user-images.githubusercontent.com/35854182/66224885-e480ce00-e68b-11e9-9f59-0da3ec156f39.png)

**Comment by NeoGlitch** [comment]
This issue is fixed.

1. In command pallet.
2. Type in 'clear'
3. Click on each one:

- [ ]  Search: Clear Search Results
- [ ]  Search: Clear Search History
- [ ]  Clear Editor History
- [ ]  Clear Command History

I am not sure which one fixed it but now "Searching Extensions in...." works.

**Comment by NeoGlitch** [comment]
**### Postmortem:  This is still a bug.
Visual Studio code isn't able to recover from corruption in the search history cache.**

**Comment by NeoGlitch** [comment]
The issue came back.
I am not able to resolve it with previous steps.

**Comment by Overload119** [comment]
I'm also having the same problem. The steps earlier did not help my situation and the workaround by using filters doesn't either.

`net::ERR_NETWORK_ACCESS_DENIED`

![image](https://user-images.githubusercontent.com/1012072/67150491-ef7f5500-f26c-11e9-9aeb-d6c3e5732083.png)
![image](https://user-images.githubusercontent.com/1012072/67150496-f8702680-f26c-11e9-83d9-9acfca62e55f.png)

```
curl 'https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery' -H 'X-Market-User-Id: dfeb9512-24ef-4f7b-a5e7-838006ffe957' -H 'Accept: application/json;api-version=3.0-preview.1' -H 'Origin: file://' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.36.1 Chrome/69.0.3497.128 Electron/4.2.5 Safari/537.36' -H 'X-Market-Client-Id: VSCode 1.36.1' -H 'Content-Type: application/json' --data-binary '{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"},{"filterType":10,"value":"test"}],"pageNumber":1,"pageSize":50,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":914}' --compressed
```

Running this with CURL works fine in a terminal.

**Comment by pizzacrystal** [comment]
I am suffering to the same issue either.  What is definite is i am not behind a proxy and the extension marketplace can be accessed few days ago with same setup and same network. In addition, I have tried to set a valid proxy for bypassing GFW's possible blocking. However, all attemptions are failed.
![vsc version](https://user-images.githubusercontent.com/11605580/67616000-03473000-f806-11e9-992d-6af2bee74007.png)
![vsc bug](https://user-images.githubusercontent.com/11605580/67616001-06dab700-f806-11e9-8438-c52e080b8a8b.png)

**Comment by NeoGlitch** [comment]
It appears my issue is resolved.  Closing Ticket since there has been no movement on the bug.

**Comment by mihreteab** [comment]
solved
Go to 
>open network and Internet setting
then
 >off all toggles inside proxy 
![Screenshot (18)](https://user-images.githubusercontent.com/17984259/68531508-e2adc880-0323-11ea-8348-9db8314bfffa.png)

**Comment by yagomassiah** [comment]
None of these solutions seem to work for me, trying to  deactivate proxy on windows nor clearing cache for search, history and so on. 

Filtering actually works for me.

**Comment by pizzacrystal** [comment]
@yagomassiah 
hi, what do you mean about "filtering", thanks!

**Comment by yagomassiah** [comment]
@pizzacrystal I meant sorts, sorry. like sort by rating.

**Comment by steal3rd** [comment]
For me, the issue was related to the following files (Windows).

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup
```

I quit Code, and renamed them.

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb-disabled
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup-disabled
```

Code recreated the files, and I was able to search the extensions again.

**Comment by pizzacrystal** [comment]
@steal3rd 
Quite appreciate, thanks a lot !
And I see your reply in [#83399 ](https://github.com/microsoft/vscode/issues/83399#issuecomment-558266534) too, where I submitted my solution.

**Comment by TakesTheBiscuit** [comment]
+1 issue on macbook
