### ISSUE TITLE
Attach fails when DebugConfigurationProvider resolves to 'node' configuration

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#81118]
If a `DebugConfigurationProvider` resolves a configuration of type `'node'`, it will fail to actually connect to the running application, even when a configuration in launch.json with the exact same properties succeeds.  Changing the provider to resolve a configuration of type `'node2'` (with no other changes) successfully attaches.

- VSCode Version: 1.38.1
- OS Version: macOS 10.14.6

Repro steps:

1. Create a `DebugConfigurationProvider`:

```javascript
import * as vscode from 'vscode';

export class NodeProxyDebugConfigurationProvider implements vscode.DebugConfigurationProvider {
    public provideDebugConfigurations(folder: vscode.WorkspaceFolder | undefined, token?: vscode.CancellationToken): vscode.ProviderResult<vscode.DebugConfiguration[]> {
        return undefined;
    }

    public resolveDebugConfiguration(folder: vscode.WorkspaceFolder | undefined, debugConfiguration: vscode.DebugConfiguration, token?: vscode.CancellationToken): vscode.ProviderResult<vscode.DebugConfiguration | undefined> {
        return Promise.resolve({
            name: debugConfiguration.name,
            // Note: 'node' does not work, but 'node2' does.
            type: 'node',
            request: 'attach',
            protocol: 'inspector'
        });
    }
}
```

2. Register the provider:

```javascript
	context.subscriptions.push(vscode.debug.registerDebugConfigurationProvider('node-proxy', new NodeProxyDebugConfigurationProvider()));
```

3. Add provider to extension activations/contributions in `package.json`:

```json	
        "activationEvents": [
		"onDebugResolve:node-proxy"
	],
	"contributes": {
		"debuggers": [
			{
				"type": "node-proxy",
				"label": "Node Proxy",
				"configurationAttributes": {
					"attach": {
					}
				}
			}
		]
	},
```

4. Create a trivial Express app and open in VS Code.

5. Run app with debugging enabled (e.g. `node --inspect=9229 ./bin/www`.

6. Create `launch.json` with `node-proxy` configuration type:

```json
        {
            "name": "Node Proxy",
            "type": "node-proxy",
            "request": "attach"
        }

```

7. Run debug configuration.

Expect:

Debugger should attach to the application

Actual:

Debugger fails to attach with `Cannot connect to runtime via 'legacy' protocol; try to use 'inspector' protocol.` error.  (Note that the `inspector` protocol is specified in the configuration.)

If you switch the provider to return a `'node2'` type, attach will succeed.  If you create a configuration directly within `launch.json` of type `'node'` with the same set of properties returned by the provider, attach will succeed.

**Comment by weinand** [comment]
What you are seeing is the expected behavior.
"DebugConfigurationProvider.resolveDebugConfiguration" are not cascaded/chained.

So your `NodeProxyDebugConfigurationProvider.resolveDebugConfiguration` cannot resolve the debug config's type into a new type that requires another resolve. For example the chain "node-proxy" -> "node" -> "node2" doesn't work.

@isidorn please confirm that my analysis is correct.

**Comment by isidorn** [comment]
@weinand yes, your analysis sounds very correct.

**Comment by philliphoff** [comment]
@isidorn @weinand I'm fine with the current behavior; what prompted filing the issue was that it appears that use of the `node2` type (at least by users directly in `launch.json`) was deprecated and might go away in some future refactoring of the node debugging infrastructure.  (IntelliSense in `launch.json`, for example, warns against using `node2`.)

If there are no issues with providers resolving to a configuration using `node2`, then we'll happily do that.

**Comment by weinand** [comment]
The `node2` type is used internal behind the version magic triggered by the `node` type. 
`node2` is an important implementation detail that is not deprecated and will not go away, but it is just not surfaced to end users (and of course there is no IntelliSense for it).

So there are no issues if your provider resolves a configuration to the `node2` type.
