### ISSUE TITLE
Never-ending LOOKUP for node_modules and bower_components

### ISSUE THREAD

**Issue by pairwiserr** [microsoft/vscode#81112]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.
I have a remote server that I mount to my local machine using `sshfs`. Every time I open a .js file to edit, VS Code does a LOOKUP for node_modules and bower_components. I've tried excluding these search rules in the setting, but it doesn't stop the issue.

**Comment by kieferrm** [comment]
The JS/TS language service is analyzing  your js files when you open them. It's doing so using its understanding of the project. You can use jsconf files to define the project's structure, i.e. to define what files/directories are included and which ones aren't. See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html. 

However, when working on remote ssh machines, using https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh is a better choice then sshfs.

**Comment by pairwiserr** [comment]
@kieferrm, thanks for your reply. Is there any way to disable vscode from analyzing the files/directories completely without use of a jsconf file?
