### ISSUE TITLE
Touch Bar displays text instead of icons on Insider build

### ISSUE THREAD

**Issue by keeganwitt** [microsoft/vscode#81111]
Stable (August 2019, version 1.38.1) shows
![image](https://user-images.githubusercontent.com/64612/65164696-670e5a00-da0b-11e9-827a-5cd5c862abab.png)

But the current Insider build (fa2b3c30adfd4350ff6c8a5e516fb7b7c1ba1468) shows
![image](https://user-images.githubusercontent.com/64612/65164890-b785b780-da0b-11e9-9b41-adeed3fecc7e.png)

It's unclear whether this change was intentional or not.  If it was intentional, think about the impact that'd have on extensions that add additional features to the touch bar, such as

https://marketplace.visualstudio.com/items?itemName=blairleduc.touch-bar-display
![image](https://user-images.githubusercontent.com/64612/65164964-e1d77500-da0b-11e9-8adc-881512cd0a93.png)

https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar
![image](https://user-images.githubusercontent.com/64612/65165230-5ca09000-da0c-11e9-83cc-b5c565c1f8e1.png)

https://marketplace.visualstudio.com/items?itemName=ashhitch.touchbar-command-palette
![image](https://user-images.githubusercontent.com/64612/65165006-f1ef5480-da0b-11e9-955a-701dbf2e3ca5.png)

On the Insider build, none of these are able to show their buttons (I think because there's insufficient space now that the icons are text).

**Comment by kieferrm** [comment]
This is a regression in the latest insider. We'll release a new insider build shortly.

**Comment by jtsom** [comment]
FYI.,.. it's been like this for the past few versions, and the latest, just released still has text labels:

```
Version: 1.39.0-insider
Commit: 6a54c8176fd60745ad7f2ba9dc89af4631752bae
Date: 2019-09-18T15:26:55.541Z
```

**Comment by misolori** [comment]
cc @bpasero @isidorn 

I wonder if this has something to do with our builds or a new version of Electron. On Insiders I see:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/35271042/65178705-282dd380-da0e-11e9-812e-97701fecbaaf.png">



And on master I see:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/35271042/65178689-1cdaa800-da0e-11e9-97b8-84eb7352dd71.png">

This doesn't repro on Stable.

**Comment by misolori** [comment]
Upon further inspecting the build bits, it appears that on Stable the icons are there:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/35271042/65179499-c53d3c00-da0f-11e9-9b79-f8cd47576076.png">

But on Insiders they are missing:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/35271042/65179657-177e5d00-da10-11e9-94f1-6bf4bac93683.png">

So they're not being included in the build process.

**Comment by keeganwitt** [comment]
> 
> 
> FYI.,.. it's been like this for the past few versions, and the latest, just released still has text labels:
> 
> ```
> Version: 1.39.0-insider
> Commit: 6a54c8176fd60745ad7f2ba9dc89af4631752bae
> Date: 2019-09-18T15:26:55.541Z
> ```

Yea, I should have been clearer.  You're right, it's been this way a while.  What I meant was that it _still_ present in the latest build, not that it started in the latest build.  Thanks for clarifying.

**Comment by bpasero** [comment]
It looks like all the touchbar icons are missing from the insiders drop.

**Comment by eamodio** [comment]
I don't know if its 100% related, but I'm also seeing other icons missing with the latest insiders (and it was present in the last couple builds).

Collapse All icon is missing:
![image](https://user-images.githubusercontent.com/641685/65221179-7b456c00-da8a-11e9-8b39-92f4ebe86dd3.png)

Back arrow icon is missing:
![image](https://user-images.githubusercontent.com/641685/65221249-a4fe9300-da8a-11e9-9147-26cdf8feec88.png)

**Comment by isidorn** [comment]
1. Works in stable
2. Wors out of source
3. Does not work in stable, as icons are not there as you mentioned.

Checking if a33e5546930a824f155dc0cad3f3de2b108e0538 broke this

**Comment by isidorn** [comment]
Ok it seems like the native mac touch bar does not allow icons which are contributed there to be inlined. So I will remove our call to `registerAndGetAmdImageURL` when we contribute icons for the native mac touch bar. Verifyign if this indeed fixes the issue
