### ISSUE TITLE
`Ctrl+Alt+Up/Down` is not the default shortcut for "Add Cursor Above/Below" on my installation

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#81110]
- VSCode Version: 1.38.0
- Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
- OS Version: Linux x64 4.15.0-62-generic snap

I see [here](https://github.com/microsoft/vscode/issues/33508) and [here](https://stackoverflow.com/questions/29953479/multiple-cursors-in-visual-studio-code) that the default keyboard shortcut for "Add Cursor Above" should be `Ctrl+Alt+Up`, but it's not:

![keyboard](https://user-images.githubusercontent.com/5044802/65164150-9320df80-d9f9-11e9-9177-49ebdca526d6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
The app default are shown in your screenshot. It's also in our doc and keyboard shortcut summaries you can download.

**Comment by kylrth** [comment]
So you haven't really addressed my concern, which is why these defaults are what they are when on other installations and in [many](https://github.com/microsoft/vscode/issues/33508) [sources](https://stackoverflow.com/questions/29953479/multiple-cursors-in-visual-studio-code) [online](http://www.donovanbrown.com/post/visual-studio-code-keyboard-shortcut-cheat-sheet) the defaults are listed as `Ctrl+Alt+Up/Down`.

Was the default recently changed?

**Comment by kylrth** [comment]
Oh I found it. The defaults for Windows are different than for Linux, which was unexpected.
