### ISSUE TITLE
Caps Lock Prevents Mac OS from Cycling Through Visual Studio Code Windows

### ISSUE THREAD

**Issue by JamesNgo-CoT** [microsoft/vscode#81120]
Issue Type: <b>Bug</b>

Step 1: Open visual studio code.

Step 2: On the file menu, select "New Window"

Step 3: On the file menu, select "New Window" again, so there are atleaset 2 windows

Step 4: Turn the keyboards caps lock key on.

Step 5: Press command+~ to cycle through the windows.

Actual result:
Mac OS does not cycle through all of the Visual Studio Code windows.

Expected result:
Mac OS does cycle through all of the Visual Studio Code windows.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.69GB free)|
|Process Argv|/Users/jngo2/Developer/Projects/lib_dev_proj|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kieferrm** [comment]
Same behavior in plain electron.

**Comment by eyelidlessness** [comment]
I just encountered this and thought something had seriously broken my VSCode install or gotten into some kind of bad system-wide state. It persisted after a relaunch. It was extremely alarming. It's easy to miss that I've inadvertently pressed caps lock if my finger is obscuring the caps lock light.

I'm reasonably certain **all** native Mac keyboard shortcuts are case-insensitive. But this is even more surprising because caps lock doesn't affect the <kbd>`</kbd>/<kbd>~</kbd> key.

**Comment by tcobbs** [comment]
Just to be clear, the actual Mac key combination is Command+\`, not Command+~. And Caps Lock is definitely not supposed to affect any keyboard shortcuts on a Mac. So, for example, Cmd+F will always perform Find, not Find in Files, whether or not Caps Lock is on. (Note that that works fine.)

**Comment by deepak1556** [comment]
Unable to repro in recent versions.
