### ISSUE TITLE
Problem:You are not likely to find a line break symbol with VSCode.

### ISSUE THREAD

**Issue by 807447907** [Microsoft/vscode#8112]
- VSCode Version:1.2.1
- OS Version: Microsoft Windows [Version: 10.0.10586]

Steps to Reproduce:

1. Type a few lines of sentences.
2. Ctrl+F, enable Regular Expression option, input "[\n]" or "[\r]" and search.
3. You can't find any match. 

But when using Visual Studio 2015, it works normally.

**Comment by alexandrudima** [comment]
Multiline find will ship with the June release
