### ISSUE TITLE
"Rename failed to execute" when renaming a variable in TypeScript

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/vscode#81125]
"Rename failed to execute" happens when the rename window loses focus, when renaming a variable.

- VSCode Version: 1.38
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open a TypeScript file
2. Click on a variable
3. Press F2
4. Click on the variable above the rename box that opened (you should be clicking in the *code*)
5. Click in the rename box to put back the focus where you want to rename.
6. Rename the variable and press Enter.

ACTUAL:
Rename failed to execute

EXPECTED:
Rename the variable appropriately.

**Comment by mjbvz** [comment]
I cannot repo this issue (unless I type after clicking back on the variable)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by jsgoupil** [comment]
I'll give that a shot today.

**Comment by mjbvz** [comment]
@jsgoupil Did you get a chance to test this?

**Comment by jsgoupil** [comment]
I can definitely repro.
I think it has one more "rule" to this.
When you click back on the variable, you have to change the cursor position.
So if your variable is "hello" and your cursor is positioned at the end of the word. Press F2, then move the cursor between the two "L".

Attached video.
[● after-view-init.directive.ts - MapRadius.Web.Client - Visual Studio Code - Insiders 2019-09-23 21-40-10.mp4.zip](https://github.com/microsoft/vscode/files/3645241/after-view-init.directive.ts.-.MapRadius.Web.Client.-.Visual.Studio.Code.-.Insiders.2019-09-23.21-40-10.mp4.zip)

**Comment by sandy081** [comment]
I see now rename input is dismissed.
