### ISSUE TITLE
Capture group in regexp find and replace not working.

### ISSUE THREAD

**Issue by vincent-cm** [microsoft/vscode#81129]
Version: 1.38.1
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Insert "(?<=")fa fa-(.*?(?="))(">)" without the wrapper quote, into the find field (Find in Files), enable regular expression.
2. Insert $1 into replace field
3. Press search

Observe that the matched string is replaced to '$1' instead of the actual capture group

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Similar to this issue https://github.com/microsoft/vscode/issues/80667 with newlines in the search field and a literal `$1` inserted as the replacement.  That issue was resolved in the Insider's Build.  But it also happens with lookarounds.

**Comment by IllusionMH** [comment]
Should work as expected in Insiders version. Could you check using lates build https://code.visualstudio.com/insiders/ ?

`<div class="fa fa-works">` replaced to `<div class="works` as expected in Isiders.

**Comment by ArturoDent** [comment]
![lookaroundBug](https://user-images.githubusercontent.com/31813701/65274705-97c4c100-dae9-11e9-9e87-a663e2046917.gif)

Version: 1.39.0-insider (user setup)
Commit: 8b6e0efc0a98639085fabeb5226a516785424796
Date: 2019-09-19T03:15:21.720Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18980

**Comment by IllusionMH** [comment]
@vincent-cm do you also have problem with "Find in files" instead of "Find" (in current editor)?

**Comment by IllusionMH** [comment]
@vincent-cm do you also have problem with "Find in files" instead of "Find" (in current editor)?

I was able to reproduce this in Find in files, but works as expected in Find.

/cc @roblourens

**Comment by vincent-cm** [comment]
I did not try find in files. But it failed when in find in project as described.

**Comment by vincent-cm** [comment]
@IllusionMH Yea I just mean the "find in files"

**Comment by roblourens** [comment]
This is actually a separate issue, now that we support lookback. Thanks
