### ISSUE TITLE
window.showOpenDialog returns an empty Array ([ ]) when canceled 

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode#81123]
- VSCode Version: 1.39.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Show an openDialog
2. Hit cancel without selecting a folder
3. The return value is [] (used to be undefined)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
@isidorn you also were close to this code.
