### ISSUE TITLE
Require is not available in the list

### ISSUE THREAD

**Issue by minkir014** [microsoft/vscode#81128]
Something strange has happened to me `require` isn't on the list of completion

See this image

![Third](https://user-images.githubusercontent.com/42807112/65198409-4b469a80-da83-11e9-9306-1b1d7e95e7fe.gif)

What's the problem??? This wasn't happening to me before.

**Comment by minkir014** [comment]
OS version: Windows 10
Vs code version: 1.38.1

Do you need more information?

**Comment by mjbvz** [comment]
Please use the issue template. What extensions do you have installed and
does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by minkir014** [comment]
OK. I'll try and tell you the results.
