### ISSUE TITLE
Problems in this file Error

### ISSUE THREAD

**Issue by bsgies** [microsoft/vscode#81127]
Hi,

In my project, I have a file that has turned red and it says it has 8 errors. How do I find these errors?

I'm attaching my screenshots below:

<img width="379" alt="problems" src="https://user-images.githubusercontent.com/32961638/65197068-8a6fee00-da79-11e9-971a-98d09ccc0bd5.png">

<img width="1148" alt="error" src="https://user-images.githubusercontent.com/32961638/65197029-8643d080-da79-11e9-9c30-abe4e2243476.png">

**Comment by kieferrm** [comment]
<kbd>F1</kbd> > `View: Toggle Problems` or  click the error icon in the statusbar.
