### ISSUE TITLE
Missing next/previous change buttons in diff peek

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81130]
![image](https://user-images.githubusercontent.com/323878/65198548-56280d80-da38-11e9-8e42-86a75fb3d5bf.png)

I get the tooltips but no icons

**Comment by IllusionMH** [comment]
Just opened repo to report same issue.

Also Close icon is missing in all peek views (diff, definition, references) too.

**Comment by misolori** [comment]
Already fixed via https://github.com/microsoft/vscode/commit/68ee8e9111b93fd90b2992f74cde677ab205a20c
