### ISSUE TITLE
Auto Indent,failure

### ISSUE THREAD

**Issue by qishenliang** [microsoft/vscode#81134]
Issue Type: <b>Feature Request</b>

Auto Indent, which seems to occasionally fail, is worse under HTML than it was when it wasn't used, and is restored after a reboot

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.6.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it feature request or a bug?
Is it reproducible with extensions disabled?

Could you provide examples of code that causes problem and screenshot of result?
