### ISSUE TITLE
Wrong behavior of pressing enter in array

### ISSUE THREAD

**Issue by rabbitooops** [microsoft/vscode#81139]
Issue Type: <b>Bug</b>
```ts
// 1. normal
const a = [
  [1,/* press enter here */]
];
// then:
const a = [
  [1,/* press enter here */
  ]
];
```
```ts
// 2. bug
const a = [
  ['only string would lead to this bug',/* press enter here */]
];
// then:
const a = [
  ['only string would lead to this bug',/* press enter here */
] // <- look
];
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.5.0

**Comment by mjbvz** [comment]
Closing due to lack of further user interest expressed in this issue. I suggest enabling `format on type` which fixes many issues like this and is much more reliable than our indent rules
