### ISSUE TITLE
How to use breakpoints with remote debugger in VScode?

### ISSUE THREAD

**Issue by friendsAI** [microsoft/vscode#81133]
The remote server is visited with SSH, a PySpark program both on server and client. I can run remote debugging in VScode without breakpoints. But when I click "Raised Exceptions" and "Uncaught Exceptions" these two option in VScode to use breakpoints, errors occurs.It says "Unable to open 'protocol.py'" and "Unable to open 'java_gateway.py'". The version of VScode is 1.38.The OS of remote server is centOS,and the client OS is macOS.

**Comment by kieferrm** [comment]
This seems to be an issue with the setup of your python project and the Python extension. Please file the issue against the Python extension. Thank you!
