### ISSUE TITLE
Press F11 while debugging in the Visual Studio Code show the desktop instead of executing "Step Into" function on macOS

### ISSUE THREAD

**Issue by manu-wu** [microsoft/vscode#81136]
**Reproducible Steps:**
1. open any python with breakpoint on macOS 
2. start debugging to reach the breakpoint
3. Press fn+F11

**Actual Result**
The desktop show up .
**Expected Result**
**It should execute "Step Into" function of Debug**

**Comment by kieferrm** [comment]
<kbd>fn</kbd>+<kbd>F11</kbd> is the default keybinding of macOS's mission control. macOS consumes the key squence without us ever seeing it. You can disable it in macOS's System Preferences.
