### ISSUE TITLE
In column mode, allow the selection start position to be set when Shift+Alt is already pressed.

### ISSUE THREAD

**Issue by mfilteau** [microsoft/vscode#81132]
In Visual Studio, the selection start position can be set while Alt is pressed. That is, Alt enters column mode but setting and extending the selection works normally.

In Visual Studio Code, the selection start position must be set before pressing Shift+Alt.

Perhaps, the problem is having Shift+Alt as the keyboard shortcut for column mode in the first place?

**Comment by alexandrudima** [comment]
I haven't tried VS recently, but my mental model of this is that "alt" does everything the regular mouse gesture does, but with column selection.

> what I'm describing works when configuring `"editor.multiCursorModifier": "ctrlCmd"` and using the latest VS Code Insiders

---

If I click and then drag I get a normal selection; if I drag **and have alt pressed** I get a column selection:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/65944089-3ed22280-e431-11e9-90bd-392d7ef77dcc.gif)

---

Similarly, if I shift+click I get an expanded normal selection; If I shift+alt+click I get an expanded column selection. So I am not 100% sure why VS would behave differently, but I think our current behavior (in Insiders) does make sense... Unless I'm missing something, in which case, please explain in finer detail...

**Comment by mfilteau** [comment]
The difference between VSCode and Visual Studio (and most other editors with block selection I've used) is subtile but very annoying.

Let say you have the cursor at line 10, column 25. You press the key combination to enter block selection (Shift+Alt in VSCode, Alt in VS) and click on at line 50, column 40.

On VSCode, a block selection will activate from (10,25) - (50, 40) and keeping the mouse right-button down will extend the selection from (10,25) to the new cursor position.

On VS (and other editors), the cursor will simply move to (50, 40) and keeping the mouse right-button down will extend the selection from (50,40) to the new cursor position.

So, it's really how the selection anchor is defined that sets the VSCode block selection appart.

**Comment by alexandrudima** [comment]
@mfilteau VS Code also has support for what you describe (column selection via alt+click), but out of the box the alt+click is used/"taken" for adding multiple cursors. That's why you need to configure `"editor.multiCursorModifier": "ctrlCmd"` which "frees" up alt+click.

Here is the latest insiders of VS Code where I have configured `"editor.multiCursorModifier": "ctrlCmd"` and where I alt+click:


![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/66040134-ff7e0180-e516-11e9-8cde-7fd7056ff794.gif)
