### ISSUE TITLE
Typescript - Generate accessors autofix removes readonly modifier

### ISSUE THREAD

**Issue by slaneyrw** [microsoft/vscode#81135]
- VSCode Version: 1.38.0 (system setup)
- OS Version: Windows_NT x64 10.0.15063
 
Steps to Reproduce:

1. Create private field with readonly modifier
2. Highlight line and generate accessors
3. get property created without set property ( correct ), but readonly modifier removed from field

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new)
