### ISSUE TITLE
SSHFS Fails to reconnect after network dropouts

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode#81146]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.16299

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
Steps to Reproduce:

1. SSHFS Workfolder connected and operating nicely
2. Network drops while in the middle of editing (I was experiencing lots of temporary drops today)
3. When network recovers, SSHFS is unable to reconnect (all my other processes reconnected fine, so the failure to reconnect is peculiar to SSHFS).
4. SSHFS cannot sync back to the remote workfolder and then I cannot close VSCode, unless I kill it via the Task Manager.  Trying the X in the VSCode window title bar does nothing.
5. Forcibly restarting VSCode allows SSHFS to reconnect.
6. On one occassion, I noticed that the green icon was not lit, yet I was able to save to the remote SSHFS folder.  It seemed the green icon was out of sync, because when it was green, I was unable to write to the remote SSHFS folder.
7. SSHFS does not appear to cache my file edits, because a couple of times I lost my changes across network outages.  It may have been that SSHFS sync'd from the stale file on the remote folder, but I could not confirm that.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
Please file the issue against the SSHFS extension. Thank you!
