### ISSUE TITLE
QuickPick button icons aren't showing in latest insiders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#81142]
Issue Type: <b>Bug</b>

In the latest insiders none of my QuickPick button icons are showing up. It is also affecting the built-in Back arrow as well.

/cc @chrmarti 

VS Code version: Code - Insiders 1.39.0-insider (8b6e0efc0a98639085fabeb5226a516785424796, 2019-09-19T03:15:21.720Z)
OS version: Windows_NT x64 10.0.18980

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Not sure if it is related to this or not: https://github.com/microsoft/vscode/issues/81111#issuecomment-532998326

**Comment by chrmarti** [comment]
Looks like QuickInput needs to update `icon` class to `codicon`. Investigating...

**Comment by bpasero** [comment]
cc @misolori

**Comment by misolori** [comment]
Thanks for fixing @chrmarti!
