### ISSUE TITLE
Replace dialog can't be destroyed

### ISSUE THREAD

**Issue by SanjiApollo** [microsoft/vscode#81147]
Issue Type: <b>Bug</b>

After I replaced some text, the pop-up dialog can't be destroyed totally.
Mybe the replace content contain a line break cause this. I press'shift + Enter' to enter a line break.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1

</details>

**Comment by kieferrm** [comment]
Can you please attach a screenshot? That would help to understand your problem. Thanks!

**Comment by SanjiApollo** [comment]
![bug](https://user-images.githubusercontent.com/29117538/65289981-9e9e1300-db7f-11e9-92a1-6ae8973375c8.png)

'ctrl + h'  --> focus on 'replace' input box --> enter some line break --> 'esc'

**Comment by jeanp413** [comment]
I think this is the same as #81946
