### ISSUE TITLE
yarn watch crashes a lot lately

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81140]
For around 2 weeks maybe I very often see `yarn watch` stopping with this (often when I move or create files). I am on latest of our node modules:

```
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: ENOENT: no such file or directory, stat '/Users/bpasero/Development/Microsoft/monaco/src/vs/platform/menubar/node/menubarIpc.ts'
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path:
     '/Users/bpasero/Development/Microsoft/monaco/src/vs/platform/menubar/node/menubarIpc.ts' },
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } } reason: { [Error: ENOENT: no such file or directory, stat '/Users/bpasero/Development/Microsoft/monaco/src/vs/platform/menubar/node/menubarIpc.ts']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/bpasero/Development/Microsoft/monaco/src/vs/platform/menubar/node/menubarIpc.ts' }
[08:23:54] The following tasks did not complete: watch
[08:23:54] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jrieken** [comment]
I did fix some issues about missing files before vacation but without real steps and cannot know if this issue is fixed or not.

**Comment by bpasero** [comment]
My workflow in the past was very often to move files around between directories, I can try to reproduce this if possible.

**Comment by bpasero** [comment]
@jrieken was able to reproduce just now: I am dragging around files from src/vs/workbench quite aggressively and it is possible that I do a drop operation after I did a drop operation that did not finish the compilation to success. That seems to trigger it more easily.

output this time:

```
[15:38:09] Finished compilation with 17 errors after 1948 ms
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: ENOENT: no such file or directory, stat '/home/bpasero/development/monaco/src/vs/workbench/common/editor.ts'
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path:
     '/home/bpasero/development/monaco/src/vs/workbench/common/editor.ts' },
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } } reason: { [Error: ENOENT: no such file or directory, stat '/home/bpasero/development/monaco/src/vs/workbench/common/editor.ts']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/home/bpasero/development/monaco/src/vs/workbench/common/editor.ts' }
[15:38:13] The following tasks did not complete: watch
[15:38:13] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by jrieken** [comment]
🤷‍♂ I have moved some files around, tried to be aggressive, but I didn't crash. Please try to craft steps as done here https://github.com/microsoft/vscode/issues/80632

**Comment by jrieken** [comment]
Actually, looking at those errors I wonder where this error is coming from. For our sources we don't use the new src-stream which only leaves this place which is doing fs: https://github.com/jrieken/gulp-tsb/blob/15dc5f6d289a1f8f733cd4aeb4626f97a4121094/src/builder.ts#L476-482. However, that's wrapped in try-catch-ignore. Maybe this is something different after all?

**Comment by bpasero** [comment]
@jrieken well, if there is an unhandled rejection error, isn't the node.js process simply going down because we do not have a global rejection error handler installed? I think that is why the process ends?

**Comment by bpasero** [comment]
https://nodejs.org/api/process.html#process_event_unhandledrejection

**Comment by jrieken** [comment]
Sure, but my fs-calls are inside a try-catch which makes this a handled error

**Comment by jrieken** [comment]
I pushed a change that (gulp-tab 4.0.5) that adds a catch to its build-promise. Curious what stack trace this will result in.

**Comment by bpasero** [comment]
Ok will report back when I see it.

**Comment by bpasero** [comment]
Actually I take it back, we have a rejection handler already and it is our own which seems to be doing the right thing (printing the reason). 

I wonder if this could originate from the `monaco.d.ts` updater?

**Comment by bpasero** [comment]
@jrieken output from a fresh yarn installed workspace:

```
[17:29:17] Starting compilation...
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: ENOENT: no such file or directory, stat '/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/buildfile.web.js'
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path:
     '/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/buildfile.web.js' },
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } } reason: { [Error: ENOENT: no such file or directory, stat '/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/buildfile.web.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/buildfile.web.js' }
[17:30:24] The following tasks did not complete: watch
[17:30:24] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`gulp-tsb` is at `4.0.5` in my workspace. I was able to trigger this by switching to a branch `1.38` and then `1.37` from vscode workspace that was under `yarn watch`.

**Comment by jrieken** [comment]
That error makes me think even more that this isn't an error with gulp-tsb. When calling build we now handle all errors (by printing them to the console) which means no unhandled rejection should happen. Also, `buildfile.web.js` is nothing I would ever expect to end up in the compiler.

**Comment by bpasero** [comment]
True. Sucks that we don't get a good stack here because it deep within callback hell of node.js
