### ISSUE TITLE
when i use typescript, vscode does not recognize redux props

### ISSUE THREAD

**Issue by alirezaed** [microsoft/vscode#81148]
Issue Type: <b>Bug</b>

typescript does not recognize redux props and show error on each component that use props as redux provided. this problem occured when i update my vs code to 3.6.2. but 3.4.5 works currectly.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
smarty|imp|0.3.0
mssql|ms-|1.6.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it work as expected when you use TS 3.6 to compile your project?

Most likely it will have same errors and there are two options:
1) Update typings for `redux`, `react-redux` etc and/or your project to versions that support TS 3.6.
2) Use same TS version as your compilation uses. See docs how to use [custom TS versions](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)
