### ISSUE TITLE
I hope it can be launched from terminal on macOS.

### ISSUE THREAD

**Issue by EdwinIZ8** [microsoft/vscode#81143]
Just like how it behaves on Windows and on Ubuntu, vscode should be able to launched from terminal on macOS by typing code and pressing enter.

Besides, PowerShell's color make words hard to distinguish from background. Black and white are best colors.

Thanks!

**Comment by kieferrm** [comment]
Run <kbd>F1</kbd> > `Shell Command: Install 'code' command in PATH`.

**Comment by EdwinIZ8** [comment]
> Install 'code' command in PATH

Firstly, I pressed F1. But nothing happened.
Secondly, I input **Install 'code' command in PATH** in terminal and press return. It print this:
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...**
