### ISSUE TITLE
Bug when running python code in console after running it using the "run the selection" feature

### ISSUE THREAD

**Issue by P-mir** [microsoft/vscode#81149]
Issue Type: <b>Bug</b>

1- Write print('hello') in a new python file
2- Select the chunk of code and run it with run selection (shift+enter)
3- Run the code again, but using run python file in terminal.

expected: hello
actual: 

File "<stdin>", line 1
    & C:/Users/me/AppData/Local/Programs/Python/Python37-32/python.exe "mypath/test.py"
    ^
SyntaxError: invalid syntax

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
Please file  this extension against the Python extension. Thank you!
