### ISSUE TITLE
Allow to define per folder settings in .code-workspace files

### ISSUE THREAD

**Issue by umarcor** [microsoft/vscode#81153]
I'd like to define settings for each folder in a multi-folder workspace. For example, in the following structure `example` and `tool` are submodules of `main`:

```json
{
  "folders": [
    {
      "name": "main",
      "path": ".",
      "files.exclude": {
        "examples": true,
        "tool": true
      }
    },
    {
      "name": "examples",
      "path": "examples"
    },
    {
      "name": "tool",
      "path": "tool"
    },
  ],
}
```

The current workaround is to use a `.vscode/settings` file. However, this does not suffice to provide multiple views of a file. Related to #67168 (/cc @joelgetaction, @DavidGriswoldTeacher), excluding files from `*.code-workspace` would allow to:

```json
{
  "folders": [
    {
      "name": "main",
      "path": ".",
      "files.exclude": {
        "**.test.js": true,
      }
    },
    {
      "name": "examples",
      "path": "examples",
      "files.exclude": {
        "!**.test.js": true,
        "**": true,
      }
    }
  ],
}
```

**Comment by kieferrm** [comment]
It seems what you're a looking for is to define something like 'smart folders'.  Thinking about it, this is a nice extension opportunity. This could either be implemented with a configurable file system provider, or with a custom tree view.

**Comment by umarcor** [comment]
@kieferrm, I'm sorry, but I don't know what you mean with *smart folders*. Nonetheless, from an extension opportunity point of view, this issue is kind of related to #76904.

**Comment by umarcor** [comment]
@isidorn, please consider reopening this issue. AFAIK, currently it is not possible for an extension to modify the TreeView. It is not a matter of writing the extension, but that API support is non-existent.

**Comment by isidorn** [comment]
Extension can contribute to a new tree view.
We will not add API support for this in the explorer.
If you would really like I can of course re-open this issue, however I do not think this will be on our agenda any time in the future or that we would want it in the product.

**Comment by umarcor** [comment]
> If you would really like I can of course re-open this issue, however I do not think this will be on our agenda any time in the future or that we would want it in the product.

May I know why don't you want to support the following syntax in `*.code-workspace` files?

```
{
  "folders": [
    {
      "name": "main",
      "path": ".",
      "files.exclude": {
        "examples": true,
        "tool": true
      }
    },
}
```

**Comment by isidorn** [comment]
Because we already have a `settings` section in the workspace configuration file. This contradicts with that one. `files.exclude` should be a part of the settings section

**Comment by umarcor** [comment]
> Because we already have a `settings` section in the workspace configuration file. This contradicts with that one. `files.exclude` should be a part of the settings section

That's correct. And I opened this issue precisely because I think this is buggy: options defined in the `settings` section of the workspace configuration file affect all the folders. Hence, the following configuration file will hide `./examples`, `./examples/examples` and `../tool/examples`:

```json
{
  "folders": [
    {
      "name": "main",
      "path": ".",
    },
    {
      "name": "examples",
      "path": "examples"
    },
    {
      "name": "tool",
      "path": "../tool"
    },
  ],
  "settings": {
    "files.exclude": {
      "examples": true,
    }
  }
}
```

What is the solution to hide `./examples` only but not any of the other two subdirs (without adding a separate `./vscode/settings.json`)?

**Comment by isidorn** [comment]
Ok i can reopen this one for now. Thanks

**Comment by umarcor** [comment]
@isidorn, would you mind labelling this as `wontfix` instead? I understand that you want to get rid of this issue (remove it from your roadmap), but I believe that `*out-of-scope` is completely out of context here. This is a legit buggy (partial) implementation that just happens to annoy fewer people than it should in order to get attention.

**Comment by umarcor** [comment]
@isidorn, sorry to bring this up again, but although you reacted to my previous comment, this issue is still labeled as `*out-of-scope` and not `wontfix`.

**Comment by isidorn** [comment]
I have updated the label, sorry about that.
