### ISSUE TITLE
Toggle to completely enable/disable ALL autocomplete features.

### ISSUE THREAD

**Issue by SebasSBM** [microsoft/vscode#81159]
I'd like that VSCode editor had a toggle option somewhere (perhaps at Edit menu, for example) that completely enable/disable every single autocomplete feature.

There are times where autocompletion is more annoying than helpful, specially when making Vim macros.

There are some tutorials (like the one in the link below) out there, that supposedly teach you how to disable autocompletion:
https://www.youtube.com/watch?v=s7wfLk7X9mo

It work for the specific settings, but there are still other autocompletion features that are still active (for example, when typing a single or double quote, it autofills the second quote for the pair).

When autocompletion gets in the way, it is extremely annoying having to search for every single autocompletion settings available in VSCode, but most importantly: having to change/undo all those settings every time you want to enable/disable autocompletion is a waste of time when you are creating code.

So, I think this feature would be very useful.

**Comment by SebasSBM** [comment]
Oh, a duplicate detecting bot! That's cute... but no, that auto-suggestion is not related at all with my feature request. Thank you.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler

- editor.parameterHints.enabled
- editor.hover.enabled
- editor.quickSuggestionsDelay
- editor.autoClosingBrackets
- editor.autoClosingQuotes

**Comment by SebasSBM** [comment]
Thanks for the information. However, I couldn't make it work.

I installed the plugin, and tried these two approaches. I couldn't make it work not even closing and reopening the editor after saving `settings.json`, and not even disabling Vim extension:

```
"settings.cycle": [
        {
            "key": "F4",
            "command": "toggle",
            "when": "editorTextFocus",
            "args": {
                "id": "toggleAutocomplete", // must be unique
                "overrideWorkspaceSettings": true,
                "values": [
                    {                    
                        "editor.parameterHints.enabled": true,
                        "editor.hover.enabled": true,
                        "editor.quickSuggestionsDelay": 10,
                        "editor.autoClosingBrackets": "languageDefined",
                        "editor.autoClosingQuotes": "languageDefined",
                        "editor.suggestOnTriggerCharacters": true
                    },
                    {
                        "editor.parameterHints.enabled": false,
                        "editor.hover.enabled": false,
                        "editor.quickSuggestionsDelay": 10,
                        "editor.autoClosingBrackets": "never",
                        "editor.autoClosingQuotes": "never",
                        "editor.suggestOnTriggerCharacters": false
                    }
                ]
            }
        }
    ]
```

```
    "settings.cycle": [
        {
            "id": "toggleAutocomplete", // must be unique
            "overrideWorkspaceSettings": false,
            "values": [
                {                    
                    "editor.parameterHints.enabled": true,
                    "editor.hover.enabled": true,
                    "editor.quickSuggestionsDelay": 10,
                    "editor.autoClosingBrackets": "languageDefined",
                    "editor.autoClosingQuotes": "languageDefined",
                    "editor.suggestOnTriggerCharacters": true
                },
                {
                    "editor.parameterHints.enabled": false,
                    "editor.hover.enabled": false,
                    "editor.quickSuggestionsDelay": 10,
                    "editor.autoClosingBrackets": "never",
                    "editor.autoClosingQuotes": "never",
                    "editor.suggestOnTriggerCharacters": false
                }
            ],
        },
        {
            "key": "F4",
            "command": "settings.cycle.toggleAutocomplete"
        }
    ]
```

The instructions to use it weren't very clear, though. Probably I did it wrong.

Unfortunately, I don't have time to mess with plugins anymore today.

**Comment by usernamehw** [comment]
Are you using `settings.json` or `keybindings.json` approach?

This works for me (`keybindings.json`):
```js
{
	"key": "f4",
	"command": "settings.cycle",
	"args": {
		"id": "autocomplete",
		"values": [{
			"editor.parameterHints.enabled": true,
			"editor.hover.enabled": true,
			"editor.quickSuggestionsDelay": 10,
			"editor.autoClosingBrackets": "languageDefined",
			"editor.autoClosingQuotes": "languageDefined",
		}, {
			"editor.parameterHints.enabled": false,
			"editor.hover.enabled": false,
			"editor.quickSuggestionsDelay": 90000,
			"editor.autoClosingBrackets": "never",
			"editor.autoClosingQuotes": "never",
		}]
	}
}
```

**Comment by SebasSBM** [comment]
@usernamehw I tried both approaches, once at a time (I thought it was obvious through the examples I gave, bot obviously not). Both of them through `settings.json`. Each example is one of those approaches (former is `keysettings` latter is `keybindings`), As I said, none of them work for me, and the instructions weren't clear either.
