### ISSUE TITLE
Bug with CTRL + F in document and regexp (its not possible make a selection of all occurencies)

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#81154]
See video pls (is not possible make a selection with all occurencies and copy to clipboard), its working with simple string ...

shortcut CTRL + d make some strange flash effect in search field 

http://bit.ly/2M5eA7x

**Comment by rebornix** [comment]
@Kcko did you try to use cmd+d when the focus is in the find widget, if that's the case, it's as expected as we run commands only when the focus is in the text editor.

**Comment by Kcko** [comment]
@rebornix of course! I do the same thing all the time

**Comment by rebornix** [comment]
thanks, then I think it should be okay to close the issue now.
