### ISSUE TITLE
Scrollbars set to almost full transparency by default, no option to change

### ISSUE THREAD

**Issue by cjcastro** [microsoft/vscode#81167]
Issue Type: <b>Feature Request</b>

Dear Microsoft,
Thank you for making a great product.
An issue I have is with the scrollbars. Presently they are set to something close to full transparency so that you can't see them very well or know they're there. I went through the options and don't see a way to make them less transparent. It's a neat feature to see what's behind the scrollbar but the way it is now, I can't even find where the scrollbar is exactly as the little squares to drag up/down , left/right are hidden. So I'd like an option to where one can change the transparency of the scrollbar so it's not so dark, maybe a slider where you can make the scrollbar transparency to 10%, 25% 50% 75% 100%. 

I've tried different color themes and it made no difference, it's still hard to see/ takes on the transparency of whatever theme I choose.

Thanks!
Christian

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:51:49.278Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ArturoDent** [comment]
Try setting its color to something non-transparent:

    "workbench.colorCustomizations": {
         "scrollbarSlider.background": "#81621dff",     // last two digits are the alpha value
    }

There are a couple of other scrollbar customizations as well.  I changed my `background` to fully opaque so it always shows quite obviously.

**Comment by misolori** [comment]
As @ArturoDent mentioned, you can overwrite these in your `settings.json` via `workbench.colorCustomizations`. The color token you're looking for is `scrollbarSlider.background`. 

You can see our [color references](https://code.visualstudio.com/api/references/theme-color#scrollbar-control) for all of the available options. Here's a start on how to adjust the opacity (adjust the last two numbers for the alpha channel):
```json
"workbench.colorCustomizations": {
        "scrollbarSlider.background": "#FFFFFF50"
}
```

**Comment by cjcastro** [comment]
Hi Arturo,

Thank you for this. I appreciate it. Now if you could be so kind, where
exactly in VS do I type that in?


Christian

**Comment by misolori** [comment]
@cjcastro here's a link to [how to change your settings](https://code.visualstudio.com/docs/getstarted/settings). Once you're there, click on the "File" icon in the top right corner, this will take you to the JSON version of settings:
 
![image](https://user-images.githubusercontent.com/35271042/65339312-bc1fac80-db80-11e9-95c5-dffd13469347.png)

Then place the `workbench.colorCustomizations` settings here:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/35271042/65339344-d0fc4000-db80-11e9-9a4a-cd8a81f66682.png">

**Comment by cjcastro** [comment]
Thank you Miguel, this worked great.
MS appears to have changed the icon. Now it's not a file icon anymore but a
{} icon.
If you hover over it, it says Open Settings (JSON).

Best regards,
Christian

**Comment by misolori** [comment]
@cjcastro well, it appears that you are on version `1.32.1` and the latest version is `1.38.1`, so the newer versions have the updated icon to what I showed.

I might also suggest you upgrade to the latest 😉
