### ISSUE TITLE
Explorer disappears

### ISSUE THREAD

**Issue by ImenAmmar** [microsoft/vscode#81164]
Issue Type: <b>Bug</b>

When I Click any option in sidebar (ex: Search or git), the explorer disappears and need to manually enable it from view->Open view and then Explorer

I found the following error in the console:

/private/var/folders/kl/m530ywws1mgf_gqffdkt7bfh0000gp/T/AppTranslocation/9EF16F50-907D-46F5-B43A-BE96EB81D739/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235
[IPC Library: File Watcher (nsfw)] (node:4767) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by IllusionMH** [comment]
/needsMoreInfo

> VS Code version: Code **1.33.1**

Looks like you are using pretty old version. Could you check with latest stable version 1.38.1 ?
