### ISSUE TITLE
VS Code opens with different toolbar

### ISSUE THREAD

**Issue by squarewave24** [microsoft/vscode#81166]
when i open code from shell (`code .`), or windows right click (code here), it opens with different  title bar/menu bars.  the colors and layout are different

i have to close it, reopen new code, and navigate to recent workspace to open it again with correct toolbar color. 

![image](https://user-images.githubusercontent.com/843437/65246718-19eac080-dabd-11e9-981a-3a19ad2cddb0.png)

![image](https://user-images.githubusercontent.com/843437/65246851-54545d80-dabd-11e9-8166-5dd9d9c8da30.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

What shell are you using to launch VS Code?
Could you check if user settings has expected values when you see wrong title?

**Comment by kieferrm** [comment]
The appearance of the titlebar is controlled by a user setting: `window.titleBarStyle`.  This is a user setting and cannot be overridden by workspace settings. If you use the same VS Code version in both cases (command line, and task bar), this might suggest that you use different user data directories depending on how VS Code is launched.

**Comment by squarewave24** [comment]
> /needsMoreInfo
> 
> What shell are you using to launch VS Code?
> Could you check if user settings has expected values when you see wrong title?

windows 10 command line 
and MINGW64 (git bash)

both commands running `code ...` have that issue. 

```
$ which code
/c/Program Files/Microsoft VS Code/bin/code
```

**Comment by squarewave24** [comment]
> The appearance of the titlebar is controlled by a user setting: `window.titleBarStyle`. This is a user setting and cannot be overridden by workspace settings. If you use the same VS Code version in both cases (command line, and task bar), this might suggest that you use different user data directories depending on how VS Code is launched.

yep, the issue might be with how shell starts using command (windows 10 cmd and git bash) and using windows wizard. 
right clicking on vscode and selecting a recent workspace also reproduces the issue 

![image](https://user-images.githubusercontent.com/843437/65331978-d1e69f00-db8b-11e9-9145-419b1884cb24.png)

**Comment by IllusionMH** [comment]
Is it possible that you have mix of User and System installations?
If you open **Help > About** do you see same information or there are differences? Especially in version field that has info about installation type (user setup or system).

And are there any differences in User `settings.json` paths?
In both cases <kbd>Ctrl+Shift+P</kbd> and pick `>Preferences: Open Settings (JSON)` and then pick Copy path in context menu for `settings.json` editor tab.

**Comment by squarewave24** [comment]
> Is it possible that you have mix of User and System installations?
> If you open **Help > About** do you see same information or there are differences? Especially in version field that has info about installation type (user setup or system).
> 
> And are there any differences in User `settings.json` paths?
> In both cases Ctrl+Shift+P and pick `>Preferences: Open Settings (JSON)` and then pick Copy path in context menu for `settings.json` editor tab.

yep! 

turns out i have 2 versions (1 in program files and 1 in c:\user\xxx\) and right click / console defaults to the older version :)
