### ISSUE TITLE
Extensions are being recommended to me based on an extension I haven't actually installed

### ISSUE THREAD

**Issue by AnthonyLenglet** [microsoft/vscode#81162]
- VSCode Version: 1.38.1
- OS Version: MacOS Mojave 10.14.5

Steps to Reproduce:

1. Go into the extensions tab
2. The recommended part is recommending me extensions because I have kubernetes installed, when I never did

![image](https://user-images.githubusercontent.com/36004334/65244990-09057380-daec-11e9-83eb-31e7e73458b7.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by chrisdias** [comment]
can you look to see if you have `kubectl` installed on your machine?  just run `which kubectl` and see if it is there.

**Comment by AnthonyLenglet** [comment]
it looks like it is

![image](https://user-images.githubusercontent.com/36004334/65409044-04d89f00-dde7-11e9-8fe4-78830bc203bb.png)

**Comment by chrisdias** [comment]
That's why it is being recommended, not because of an extension being installed, but because you have kubernetes (at least kubectl) installed on your machine.

**Comment by AnthonyLenglet** [comment]
the recommendation makes sense then, though I'm not sure if it should really be here still

kubernetes is installed by docker, but I don't have it enabled at all
![image](https://user-images.githubusercontent.com/36004334/65489004-8e04da00-deaa-11e9-9df3-80ade58241e9.png)

so it is still recommending an extension for something I don't use, not sure how this could be delt with
