### ISSUE TITLE
[Web] Cannot highlight PHP files.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#81168]
Version: 1.39.0-insider
Commit: 8b6e0efc0a98639085fabeb5226a516785424796
Date: 2019-09-19T03:06:11.642Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

Steps to Reproduce:

1. Open any php file like the following image.

![image](https://user-images.githubusercontent.com/7701575/65248677-230f7800-db25-11e9-8fac-dc6fabe11b8b.png)

Does this issue occur when all extensions are disabled?: Yes

And by the way, the error message is really interesting, to read it, you have to parse it by charCode.

![image](https://user-images.githubusercontent.com/7701575/65248827-67027d00-db25-11e9-8a0d-361c230da3ad.png)

**Comment by kieferrm** [comment]
Unsupported configuration.
