### ISSUE TITLE
Loosen/customize fuzzy file search matching (path separator)

### ISSUE THREAD

**Issue by timkelty** [microsoft/vscode#81169]
I'm on a Mac, so my path separator is a forward slash `/`.

In PHP, namespaces are always backslashes `\` and normally reflect the file/folder structure.

In other editors (Atom), the fuzzy matching was looser, so I could `⌘+P` and paste in a PHP namespace (eg `Illuminate\Foundation\Http\Kernel`), and it would still match the path `src/Illuminate/Foundation/Http/Kernel.php`.

Ideally, there could be a setting for a regex exclusion pattern for the fuzzy search.

Or…explicitly just allow both `/` and `\` to still match :)

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603, a backslash on posix platforms is now converted to a slash automatically. We already did this on Windows (slash to backslash).

**Comment by bpasero** [comment]
**Verification**
Verify that on Linux/macOS you can search for file paths even if you separate them by backslash.

**Comment by timkelty** [comment]
@bpasero I tried this on the insiders build and it works! 👯‍♂️

Thanks!
