### ISSUE TITLE
incorrect font in integrated terminal

### ISSUE THREAD

**Issue by macgyver** [microsoft/vscode#81163]
Issue Type: <b>Bug</b>

integrated terminal is not using my configured font, it's used some weird serif font

VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T05:59:55.803Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
vscode-open-in-github|fab|1.2.1
vscode-pull-request-github|Git|0.11.2
vscode-peacock|joh|3.1.5
chat|kar|0.22.1
auto-dark-mode|Lin|0.1.5
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-containers|ms-|0.76.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.6
vscode-remote-extensionpack|ms-|0.17.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.826
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
vetur|oct|0.22.3
vscode-scheme|sjh|0.4.0
vim|vsc|1.10.2
gitblame|wad|3.0.1

</details>

<img width="964" alt="image" src="https://user-images.githubusercontent.com/1163/65245369-831d0480-daba-11e9-8e5e-2b71027ad01b.png">

I feel like this started a few weeks back, but it's been going on long enough now that I thought it should be reported - I do not have the same issue in the stable release.

**Comment by kieferrm** [comment]
@macgyver same when you set `terminal.integrated.fontFamily` explicitly, i.e. don't rely on the fallback to `editor.fontFamily` ?

**Comment by macgyver** [comment]
oh whaaa I didn't know about that setting, must've set it long ago by accident and since then deleted the font it refers to - would be nice if missing fonts didn't default to something crazy but this seems like user error. Thanks!
