### ISSUE TITLE
Powerline fonts not working

### ISSUE THREAD

**Issue by SomeshPatil** [microsoft/vscode#81160]
Issue Type: <b>Bug</b>

Iam using Zsh with agnoster theme and powerline fonts were working perfectly before but now it only shows debian% , I have tried a lot of other fonts as mentioned in other issues of VScode zsh agnoster like Menlo for Powerline, MesloLGM Nerd Font but nothing seems to work.

Also im able to use these fonts perfectly in IntelliJ , so I dont think this issue is from the fonts.
My locale in terminals where powerline fonts are working :
LANG=en_IN
LANGUAGE=en_IN:en
LC_CTYPE="en_IN"
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=

locale in vscode : 

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LANGUAGE=en_IN:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3188)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (7.73GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.25.1
java|red|0.49.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0

</details>

**Comment by Tyriar** [comment]
Attach a screenshot of it not working please.

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/needsMoreInfo

**Comment by SomeshPatil** [comment]
![Screenshot from 2019-09-26 04-50-51](https://user-images.githubusercontent.com/22115248/65646654-64b68c00-e019-11e9-8024-ceca025af374.png)
Heres the screenshot of my normal gnome-terminal and vscode terminal,
This is my Setting.json

{
    "explorer.confirmDelete": false,
    "terminal.integrated.shell.linux": "/bin/zsh",
    "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback',''",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terminal.external.linuxExec": "gnome-terminal",
    "terminal.integrated.fontFamily": "MesloLGM Nerd Font",
}

**Comment by Tyriar** [comment]
This is a problem with how you've set up your shell. Try removing `"terminal.integrated.shell.linux": "/bin/zsh"` and see if that fixes it, otherwise I recommend investigating where you're defining your prompt ($PS1) and why that isn't carrying over.

**Comment by SomeshPatil** [comment]
Well removing "terminal.integrated.shell.linux": "/bin/zsh" did not work, please check the screenshot for reference, I am did not find any explicit setting for my $PS1, I think Oh my Zsh handles the changes from the theme by itself.
Well if it helps here are the values of my prompt string one in gnome-terminal and vscode terminal respectively:

- %{%f%b%k%}$(build_prompt)
-  %m%#
![Screenshot from 2019-09-26 05-45-19](https://user-images.githubusercontent.com/22115248/65648672-d80fcc00-e020-11e9-9f34-f34970d3298c.png)

**Comment by Tyriar** [comment]
Does this setting help? `"terminal.integrated.shellArgs.linux": ["-l"]`?

> %{%f%b%k%}$(build_prompt)

Where ever this is getting set isn't being run in vscode's terminal.
