### ISSUE TITLE
Terminal has display bugs with julia console

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#8117]
- VSCode Version: 1.3.0-insider (de66522)
- OS Version: Win10 x64

Steps to Reproduce:
1. Install [julia v0.4.6](http://julialang.org/downloads/)
2. Configure VS code terminal to use PowerShell
3. Start VS Code terminal, then start a julia instance in the terminal (I have an alias for `julia` in my PowerShell session, you might have to enter the full path)
4. Enter shell mode by typing `;`, then enter the following characters `dir /cmd` or something like that, then hit `Backspace` a couple of times. You might have to fiddle around a little, my repo was not 100%.

I then get a screen that looks like this:
![image](https://cloud.githubusercontent.com/assets/1036561/16347494/db4211b2-3a01-11e6-9ed9-17dcc64d9f55.png)
The prompt now is shown twice. Sometimes I also get the prompt moved to the right, jumping around etc. I have never seen that sort of behavior when I start julia in the normal windows command window, or anywhere else (Mintty etc.).

**Comment by Tyriar** [comment]
This is an upstream issue.

**Comment by davidanthoff** [comment]
I assume you mean upstream in the terminal emulator, not in julia, right?

**Comment by Tyriar** [comment]
Yes, upstream as in xtermjs, pty.js or winpty.

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
