### ISSUE TITLE
Python debug launch command is different for the first execution in a new Terminal

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#81179]
- VSCode Version: 1.37.1
- OS Version: Windows 8.1

I could be that the `ms-python` extension is the cause of this. If so I will ask it there.

Steps to Reproduce:

1.  Write a Python 3 Hello world program
```
print("Hello Word!")
```
2. Create the default `Python: Current File` launch config
```
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
```
3. When launching this program for the first time I get
```
d:\test>C:\Python36\python.exe c:\Users\XXXX\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 54029 d:\test\hello.py
Hello Word!
```
4. The next run I get
```
d:\test>cd d:\test && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Python36\python.exe c:\Users\XXXX\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 54039 d:\test\hello.py "
Hello Word!
```

Every next debug launch uses the second version.

Why is there a different launch command?

The second version is complicating passing arguments with special characters like ", <, >, space that need quotes to escape the string.

If I would need these config variables (PYTHONIOENCODING and PYTHONUNBUFFERED) I would add them to the "env" section.

As a side question:
How do I specify how to quote/escape the argument(s) in the args array of the launch config with single or double quote?
I have read a while ago something about it in the docs but I can't find it any more.
I want to be able to debug this command
```
C:\Python36\python.exe hello.py "<title>Test</title>"
```
It happens automatic correct the first time in a Terminal if I add a space in the argument.

**Comment by kieferrm** [comment]
Please file this issue against the Python extension. Thank you!
