### ISSUE TITLE
Relative files autocompletion for imports

### ISSUE THREAD

**Issue by palerdot** [microsoft/vscode#81176]
Let us say I have a file `file_to_import.js` somewhere in my directory structure like `../../../some-path/another-path/file_to_import.js`

it would be nice if the import statement autocompletes this file, so that we don't have to manually remember the path of the files to be imported like 
```
import something from "file_" // should autosuggest => *../../../some-path/another-path/file_to_import.js*
``` 
I think with the existing editor infrastructure (fuzzy searching files) this should be possible. Is this feature possible or is there something like this hidden somewhere in the settings?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
