### ISSUE TITLE
Question about Marketplace Licence issue when used in Patched vscode version.

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81173]
There is a Project that Patches vscode to run via the browser its code base is over 90% vscode as it is and the main core is simpl vscode there are only some ui changes.

is it allowed to still use the original marketplace? I Think as vscode is OSS this should be no problem can some one confirm that or point me to the right contact to confirm that facts.

https://github.com/cdr/code-server/issues/990

**Comment by chrisdias** [comment]
The information provided in issue 990 is correct, `code-server` is not licensed to access the Visual Studio Marketplace.  Only products which are members of the Visual Studio family of products are licensed to do so per the Marketplace terms of use.  From the [wiki](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code):

> The [Visual Studio Marketplace](https://marketplace.visualstudio.com) is a service that we provide to users of the Visual Studio family of products (Visual Studio for Windows and Mac, Visual Studio Code, and Azure DevOps, formerly Visual Studio Team Services). The Marketplace not only provides discovery and hosting services, it provides ratings, comments, Q&A, publisher verification, virus scanning, conflict resolution services, payment services for Azure DevOps extensions, as well as support for publishers. The Marketplace is not a general purpose store designed to support any distribution or a subset of distributions. Access to the Marketplace is governed by the Marketplace [Terms of Use](https://aka.ms/vsmarketplace-ToU).
