### ISSUE TITLE
Move startDebugging options from proposed to official API

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81170]

**Comment by isidorn** [comment]
I have moved the startDebugging options from proposed to official API (as we have agreed upon previous milestone).
fyi @weinand @jrieken @dgozman

**Comment by dgozman** [comment]
Thanks, sounds good! While playing with it, I found a small UX annoyance, let me file a separate issue for that.

**Comment by weinand** [comment]
Verified by "vscode.d.ts" inspection.
