### ISSUE TITLE
Suggestion: teach debugger about React's tree of components

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#81174]
I often use the debugger to investigate issues inside React components. However, the experience is currently very limited because the debugger is not aware of React's tree of components—it is only aware of the call stack (tree of regular functions).

Specifically, inside a component's render function:

- it is not possible to step into child component invocations
- the call stack does not show you which parent component invoked the current component

Examples:

----

``` tsx
const MyComponent = () => {
  return <div>foo</div>;
}
```

```tsx
const App = () => {
  debugger;
  return <MyComponent />;
}
```

When the debugger is paused on `debugger` inside `App`, I want to be able to step into `MyComponent`'s render function (in the same way you could if `MyComponent` was a regular function call).

----

``` tsx
const MyComponent = () => {
  debugger;
  return <div>foo</div>;
}
```

```tsx
const App = () => {
  return <MyComponent />;
}
```

When the debugger is paused on `debugger` inside `MyComponent`, I want to be able to trace the parent component which invoked `MyComponent` (which in this case is `App`).

**Comment by roblourens** [comment]
The debug adapter only knows about javascript and the javascript call stack, and I don't think we can really support different framework-specific features like this, sorry. Thanks for the suggestion.
