### ISSUE TITLE
Annoying GitHub commit behaviour

### ISSUE THREAD

**Issue by yogesh-aggarwal** [microsoft/vscode#81183]
- VSCode Version: 1.36.1
- OS Version: Linux (Ubuntu 19.04)

**Steps to Reproduce:**

1. Make your default code editor (commit editor) of git to "code".
2. Turn ON autosave on vscode.
3) Try to commit, it will autosave that file and blank commit get passed.

**In my opinion, it should ignore the "COMMIT_EDITMSG" file.**
I faced it first time, on windows no issues are there but on Ubuntu 19.04 there's issue.
Does this issue occur when all extensions are disabled?: Yes

**Comment by yogesh-aggarwal** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Annoying GitHub commit (#77927)](https://www.github.com/microsoft/vscode/issues/77927)

no

**Comment by frank-dspeed** [comment]
@yogesh-aggarwal you can ignore files in your workspace user and global settings to archive your goals.

**Comment by yogesh-aggarwal** [comment]
> @yogesh-aggarwal you can ignore files in your workspace user and global settings to archive your goals.

How?

**Comment by frank-dspeed** [comment]
https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code

and you can also ignore that file inside git via .gitignore

**Comment by yogesh-aggarwal** [comment]
No, I am talking about that it autosaves the commit file too & an empty commit gets passed on. How can I prevent the autosave for the commit file?

**Comment by yogesh-aggarwal** [comment]
**Okay I have figured it out**. Just I have to set the vscode editor for commit with `--wait` flag

```
git config --global core.editor "code --wait"
```
**This solves the issue.**
