### ISSUE TITLE
VS Code doesn't resolve new flutter plugins

### ISSUE THREAD

**Issue by SowingFiber** [microsoft/vscode#81182]
Issue Type: <b>Bug</b>

When using flutter pub get to install packages mentioned in pubspec.yaml, the exit code comes as 0, which means, everything went right. The same can be confirmed in looking at the packages file, which reflects the said success in  installing a new plugin.

However, when importing the installed plugin, the editor fails to recognise it as a valid path. This has happened several times. To reproduce, create a new flutter project and install a few plugins from pub.dev/flutter. Try importing them in the project. If the editor says, the URI doesn't exist, try checking the packages file, right near the pubspec.yaml file. Most certainly the installed plugin will be found in the packages file.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.4.1
flutter|Dar|3.4.1
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|2.2.2
vscode-styled-components|jpo|0.0.26
cpptools|ms-|0.25.1
cmake|twx|0.0.17
vscode-icons|vsc|9.3.0

(2 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Please file the issue against the Flutter extension. Thank you!
