### ISSUE TITLE
Python extension crashes

### ISSUE THREAD

**Issue by yogesh-aggarwal** [microsoft/vscode#81184]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install the python extension
2. Start typing python code, maybe some imports or something else

In most of the cases, the analysis gets stuck and eventually, there will be no suggestions.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yogesh-aggarwal** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Python Extension is disabled (#79555)](https://www.github.com/microsoft/vscode/issues/79555)

No

**Comment by kieferrm** [comment]
Please file the issue against the Python extension. Thank you.
