### ISSUE TITLE
Add an "actionables only" option to editor.hover.sticky

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81181]
The `editor.hover.sticky` setting is `true` by default, which helps with hovers like the color picker. However, I often find myself very annoyingly having to click away of the hover box to see hover information from lines above.

My suggestion is to distinguish between actionable and non-actionable hover boxes so that you can have `"all"`, `"actionableOnly"` and `"off"` options in `editor.hover.sticky`setting, such that actionable hovers like the color picker are still sticky, but non-actionable ones are not.

**Comment by andrecasal** [comment]
My request isn't the same as [Enable Hover: sticky on RGB Color picker only (#69066)](https://www.github.com/microsoft/vscode/issues/69066). I'm requesting a "actionableOnly" option in `editor.hover.sticky` that works with more than just the color picker. It could even work with extensions that add hovers if they use an "actionable" flag somewhere.

**Comment by octref** [comment]
I feel it's better to treat color hover as a special case and always make it sticky, and not add yet-one-more-value to the setting.

Meanwhile you can use ESC to dismiss hover.

**Comment by octref** [comment]
You can use ESC to dismiss the box. When the hover content is long, people would need to move their mouse into the hover box and scroll, so we can't just hide the hover as soon as you leave the hovered content.
