### ISSUE TITLE
editor.suggest.filteredTypes doesn't respect deleting a filter

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#81189]
- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. In settings.json add editor.sugges,t.filterTypes which prefills with keyword and snippet true
2. Bring up suggestions to see other available filters (displayed with property icon).
3. Add "property": false and now IntelliSense doesn't have available filter suggestions.
4. Set "property:" true and filter suggestions are back.
5. Set "property": false again and no filter suggestions as expected.
6. Delete the "property": false entry.

No filter suggestions. editor.suggest.filterTypes doesn't detect that property filter was removed.

7. Reload Window and then filter suggestions come back.

**Comment by jrieken** [comment]
I tracked this down to [`_subsetEquals`](https://github.com/microsoft/vscode/blob/0fc92f222f9b7007240583c090d5c2c748d91938/src/vs/editor/common/config/commonEditorConfig.ts#L307) which (kinda correctly) says that the new config (the one without `property: false`) is a subset of the old one and therefore it ignores the change (early return [here](https://github.com/microsoft/vscode/blob/0fc92f222f9b7007240583c090d5c2c748d91938/src/vs/editor/common/config/commonEditorConfig.ts#L341))

<img width="757" alt="Screenshot 2019-10-08 at 18 44 59" src="https://user-images.githubusercontent.com/1794099/66415396-c7396000-e9fb-11e9-9843-c9f02edd658f.png">

**Comment by alexdima** [comment]
I can no longer reproduce, the `editor.suggest.filterTypes` does not exist anymore.
