### ISSUE TITLE
No comments.

### ISSUE THREAD

**Issue by pritamKarmokar** [microsoft/vscode#81188]
I would like to toggle views with and without comments.
When coding into huge code-bases, I imagine it would help my productivity if I could just look at the code without comments from time to time. 
Sometimes comments eat up a lot of screen estate and navigating becomes cumbersome. The comments do help at first but once its old, it comes in the way more often. A coding experience where I could just look at the comments when I need to, could help me a long way.

**Comment by kieferrm** [comment]
@aeschli what do you think about a `Fold all comments` command?

**Comment by aeschli** [comment]
We already have `Fold all Block Comments` `(Ctrl + K Ctrl + /`)`.

Is that what you are looking for?

**Comment by MarcelloTheArcane** [comment]
Sounds like it should be an extension rather than builtin.

**Comment by aeschli** [comment]
@MarcelloTheArcane Why? Each folding range provider (coming from extensions) tells us which ranges are for comments. So we have a single command.
