### ISSUE TITLE
Searching: Ctrl+Z to previous search after clipboard dump.

### ISSUE THREAD

**Issue by niemeier23** [microsoft/vscode#81185]
Issue Type: <b>Feature Request</b>

I'm actually really happy with the feature where clicking on the Search icon pastes the clipboard's contents into the search field.   However, there are times when something was previously in the search field, and I don't necessarily want to lose that (e.g. a gorgeous RegEx pattern) whenever I click back into the Search pane/tool.  In these cases it would be really helpful to be able to click into the search field and have the Ctrl+Z shortcut to go back to your previous search(es).  The Ctrl+Z shortcut works for other textual changes in the search fields, but not after clipboard dumps, like this.
Otherwise, I'd be glad to have another solution that preserves or prevents the loss of prior search strings, other than keeping a separate note/document.

Thanks for considering the idea.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kieferrm** [comment]
@niemeier23, you can navigate the search history using the Up and Down-Arrow keys.
