### ISSUE TITLE
Ctrl+F5 shortcut does not work the same as manually clicking Debug -> Start Without Debugging

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#81195]
If you have multiple debug configurations, this works:

- Select first debug config on the debug side bar
- Click `Debug` -> `Start Without Debugging`
- Select second debug config on the debug side bar
- Click `Debug` -> `Start Without Debugging`

Against the `Start Without Debugging` menu entry, it says the shortcut key is `Ctrl+F5`. Yet if you perform the same steps above using F5, the second debug configuration will not launch.

I think this is because the keybind has `!inDebugMode` as a condition, but I think this is confusing and unwanted. If a menu entry is enabled, and shows a shortcut key, that shortcut key should do the same thing as clicking on the menu entry.

**Comment by isidorn** [comment]
@DanTup good catch, thanks for reporting. You can try it out with Monday's vscode insiders and let us know if this gets fixed for you.

**Comment by DanTup** [comment]
LGTM, thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label.
