### ISSUE TITLE
Spaces in file paths break stacktrace links in terminal

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#81190]
@Tigraan commented on [Thu Sep 19 2019](https://github.com/microsoft/vscode-python/issues/7491)

## Environment data

- VS Code 1.36.1
- VS Code - Python extension 2019.9.34911
- Win10 [10.0.16299.1387]
- Python version : Python 3.7.4 / Anaconda (conda 1.7.2)

## Expected behaviour

When Python raises an exception, it outputs a stack trace with file paths and line number. In the VS Code terminal, those file paths + line number entries are clickable and open the relevant file and line in the editor.

## Actual behaviour

When the file path contains a space, there is no link.

## Steps to reproduce:
1. Create a python file (that raises an error when executed) at a filepath containing spaces.
2. Run the file in terminal
3. Attempt to click the stacktrace links.

## Example with gif

![linsk](https://user-images.githubusercontent.com/28686753/65261223-0f094d80-db08-11e9-9fbe-b0542462ab30.gif)

Result: there is a link to `/tests/with_ünicode/test.py`, but not to `/tests/with spaces/test.py`. Both those files are the same snippet:

```
import numpy as np
a = np.linspace(0.0, 1.0, num=-2)  # fails when called
```

(You could replace the snippet by `assert False`, but this also demonstrates that the Anaconda distrib links upstream in the stacktrace work.)

**Comment by Tyriar** [comment]
This is by design until we move onto a parser-based link detection system.

/duplicate https://github.com/microsoft/vscode/issues/21125
