### ISSUE TITLE
Sent env to running instance. Terminating

### ISSUE THREAD

**Issue by SkiftCreative** [Microsoft/vscode#8119]
- VSCode Version:
1.3.0-insider
- OS Version:
OSX, El Capitan (10.11.5)

Steps to Reproduce:

1. Start VS Code from the terminal
2. let it fail

I have been using code without much issue. But today I tried to start it (with no other instances already going) from the terminal, and I get this error:
```
> code --verbose
(1:41:04 PM) Sending env to running instance...
(1:41:04 PM) Sent env to running instance. Terminating...
```

The launch icon short for a few seconds, then disappears. I tried launching by clicking the `.app` launcher as well and still crashes. 

Trying to disable extensions as well doesn't seem to help. 
```
> code --verbose --disable-extensions
(1:42:37 PM) Sending env to running instance...
(1:42:37 PM) Sent env to running instance. Terminating...
```

here is the extensions I have installed:

```
EditorConfig.EditorConfig
HvyIndustries.crane
Kasik96.format-indent
PeterJausovec.vscode-docker
TsumiNa.Seti-theme
Tyriar.sort-lines
Zignd.html-css-class-completion
abierbaum.vscode-file-peek
alefragnani.Bookmarks
andrejunges.Handlebars
bbenoist.vagrant
be5invis.toml
codezombiech.gitignore
dbaeumer.vscode-eslint
dbankier.vscode-gist
dbankier.vscode-instant-markdown
donjayamanne.githistory
donjayamanne.python
dzannotti.vscode-babel-coloring
felipecaputo.git-project-manager
gerane.Theme-Github
gerane.Theme-bashling
guodf.vscode-phpfmt
haaaad.ansible
henriiik.docker-linter
himanoa.Python-autopep8
johnpapa.Angular2
mkaufman.HTMLHint
msjsdiag.debugger-for-chrome
nwallace.language-vscode-javascript-angular2
rafaelmaiolla.diff
robinbentley.sass-indented
saviorisdead.RustyCode
shardulm94.trailing-spaces
smkamranqadri.vscode-material-design-lite-snippets
tanato.vscode-gulp
tushortz.python-extended-snippets
twxs.cmake
vilicvane.es-quotes
waderyan.gitblame
wholroyd.jinja
zgudino.editorconfig-vscode-snippet
zhuangtongfa.Material-theme
```

**Comment by dbaeumer** [comment]
@bpasero assigning you as well since @joaomoreno is out next week.

**Comment by SkiftCreative** [comment]
For reference (I forgot to link to this in my issue), i found this possibly related issue that was already closed. https://github.com/Microsoft/vscode/issues/4971

**Comment by bpasero** [comment]
@SkiftCreative this indicates that another instance of Code is already running. It should be fine if you restart or terminate the instance that is running.

It would be interesting to find out how you got into this state in the first place though. Do you remember?

**Comment by SkiftCreative** [comment]
Thats the odd issue. Opening up Task Manager in osx shows no instances of code running. Even then, in the past ive been able to open up another new window from the cli before and it works. So I am not able to even terminate it.

**Comment by SkiftCreative** [comment]
So, as I wrote that I thought of something. I installed `htop` on my system, and did a search through all processes by searching for `code` and  there were 5 instances of some helper running in the background. That I never saw in Task Manager. I may have missed them for some reason.

`/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService`

Running code after killing the `*Helper*` processes that were running seemed to fix it. Code starts now. I am not sure when helpers they were. I stupidly killed them before copying their named. Here is an image of what processes were running:

![image](https://cloud.githubusercontent.com/assets/89895/16360953/09fd6bc4-3b32-11e6-8c00-c4dd0b7c4b68.png)

**Comment by SkiftCreative** [comment]
Looking through all that, i noticed (because I accidentally killed the wrong helper) that I have another electron app open. Nylas N1 (email client). Heres the processes I had (sorry htop isnt letting me copy and paste)

![image](https://cloud.githubusercontent.com/assets/89895/16360970/69d3f4dc-3b32-11e6-9c1b-f4b15d1d2292.png)

Reference: https://github.com/nylas/N1

If theres anything else I can provide let me know. Ill try to reproduce it.

**Comment by bpasero** [comment]
@SkiftCreative yes, htop is a good tool to really find all processes. Happy to hear it works fine again after you close those processes.

Please keep an eye open if this happens again and then maybe you remember what happened to get you there.

Did this ever happen more than once?

**Comment by SkiftCreative** [comment]
Yea i will definitely keep an eye on it. And no this is the only time it has happened. I am trying to break it now, but its not seeming to want to.

**Comment by bpasero** [comment]
When this happens again please post all running processes here and we can reopen the issue (doing some cleanup).

**Comment by GantMan** [comment]
I'm currently in this state as well... I cannot find the correct process or helpers I need to kill to get code back and running.   I closed the ones mentioned above to no avail.

**Comment by bpasero** [comment]
@GantMan restart helps?

**Comment by autoferrit** [comment]
@GantMan for me it happened because i was running another electron app. kill both if you have more than one running. That should fix the issue.

**Comment by atkit** [comment]
I faced with issue on my mac, I found and stopped process called "Electron". It helped.
