### ISSUE TITLE
Hangs Indefinitely if sshfs volume is re-mounted 

### ISSUE THREAD

**Issue by raokrutarth** [microsoft/vscode#81192]
Issue Type: <b>Bug</b>

If the workspace is pointing to a directory that is mounted using sshfs to a netowork drive, remounting the volume on MacOS makes VSCode hang indefenitely. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 8, 8|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
bitbake|Eug|1.1.2
vscode-systemd-support|han|0.1.1
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.4
mssql|ms-|1.6.0
python|ms-|2019.9.34911
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.25.1
Go|ms-|0.11.4
java|red|0.49.0
vscode-xml|red|0.9.0
vscode-yaml|red|0.5.3
scala|sca|0.3.5
metals|sca|1.5.4
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
