### ISSUE TITLE
Problem with Cascadia Code

### ISSUE THREAD

**Issue by dsolodow** [microsoft/vscode#81193]
Environment
Cascadia Code version number: 1909.16
Application (with version) used to display text: VSCode 1.38.1
OS platform and version: Windows 10 Enterprise x64 18362.356
Screen resolution (i.e. 220dpi): 1920x1080, scale 100%

Any other software? nope
Steps to reproduce
Launch VSCode
Open terminal in VSCode
Install Cascadia Code font
Change editor.fontFamily to "Cascadia Code"

Expected behavior
VSCode editor & terminal use Cascadia Code without warning or Error

Actual behavior
Font size in editor is several sizes smaller than configured
Terminal throws warning "The terminal only supports monospace fonts"
image

Other observations
Restarting VSCode after installing & setting the font results in normal behavior
Installing the font while VSCode is closed behaves normally as well.

**Comment by Tyriar** [comment]
I've seen a few reports about this on Twitter, when I tried I couldn't reproduce. I think the problem is that when you install a new font VS Code (electron/chromium) won't pick that up, you need to do close all windows and start again. This is working as it always has and there aren't plans to change.

**Comment by pharrisee** [comment]
Apologies for commenting on a closed issue, but just another note.

I actually had to rebuild the system font cache on Ubuntu as reload/restarting code didn't help.  It was only after running:  

sudo fc-cache -f -s 

that code picked up the font.  

I'd installed Cascadia as a system font.
