### ISSUE TITLE
No Intellisense with typescript

### ISSUE THREAD

**Issue by joesonw** [Microsoft/vscode#812]
It went smoothly at the start. Everything stopped working after a certain point (I use default settings, so nothing about `settings.json`). No autocomplete or type hinting anymore, it's just like a regular text editor to me right now. But it has hints when i was editing`settings.json` though.

**Comment by alexandrudima** [comment]
@joesonw Can you please help us with more steps to reproduce the problem. Does the problem persist for you if you restart VSCode? Does the problem occur only on a certain file/folder?

**Comment by joesonw** [comment]
@alexandrudima  I even tried to reinstall it. I also tried delete everything under `${HOME}/Library/Application Support/Code`, problems still persist.  I can't really tell how did I got into this. I suspect it might be structure of project files? or `package.json`?

**Comment by alexandrudima** [comment]
CCing @dbaeumer who might help you pinpoint the failure better

**Comment by dbaeumer** [comment]
@joesonw would you be able to share your project with me.

**Comment by ucnc** [comment]
I had same experience when completionItemProvider reject the promise.
It might be related to #693 .

**Comment by ucnc** [comment]
@dbaeumer I'm working on completion on #633 try that with this code

```typescript
interface IDosomething{
	getInfo(callback:(another:()=>void)=>void)
}
var x:IDosomething;
x.getI
```

then try to complete x.getI with tab. you will get flowing error and suggestion, completion and quick-info won't work any more. 

Here's what I get when something going wrong in process of suggestion. after this
[4363:1130/154007:INFO:CONSOLE(47)] "WARNING: Promise with no error callback:undefined", source: file:////home/user/vscode/out/vs/base/common/winjs.base.js (47)
[4363:1130/154007:INFO:CONSOLE(48)] "Error: Promise did not implement oncancel", source: file:////home/user/vscode/out/vs/base/common/winjs.base.js (48)

**Comment by dbaeumer** [comment]
@ucnc testing with with a 'plain' VSCode doesn't show any wired behavior nor output written to the log.

**Comment by alexdresko** [comment]
Have you added a tsconfig.json file to the root of the project?

**Comment by RANUX** [comment]
I have issues with intellisense, too. I created isolated project with issue https://github.com/RANUX/vscode-ts-project-tests When i use "exclude" directive in tsconfig.ts, everything works fine, but when i try use "files" directive intellisense doesn't work :( 
VSCode Version is 0.10.10 on OS X Yousemite.
PS in js files intellisense works fine

**Comment by dbaeumer** [comment]
@RANUX the problem with your setup is that as soon as you start using a files section only the files listed there are parts of the project. So in your case the project only consists of  "typings/meteor/meteor.d.ts" and no other files. Hence you don't get intellisense in any of the others. Either remove the files sections or list all files you want to have part of the project.

**Comment by RANUX** [comment]
@dbaeumer thanks for reply! But intellisense doesn't work for listed files in "files" section, that's my problem :(

**Comment by dbaeumer** [comment]
@RANUX but in our example you only list typings/meteor/meteor.d.ts in the file section. So if you add another file the meteor typings will not be available in that files and therefore you will not get intellisense in that file for meteor typings.
