### ISSUE TITLE
Remote Development over SSH doesn't handle large files

### ISSUE THREAD

**Issue by saubhagyarathi** [microsoft/vscode#81202]
Issue Type: <b>Bug</b>

Remote Development over SSH over a fast network doesn't work when editing large files. I really mean large like ~2 MB text files. Keeps losing connection and reloading temporarily fixes it. If I close the file and work on other files, the feature works perfectly.

VS Code version: Code - Insiders 1.39.0-insider (bdd1971f2cd9d08a8a90e02740f1850afe03da66, 2019-09-17T05:59:55.803Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.15.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: batcomputer|
|OS|Linux x64 4.15.0-48-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (56 x 2989)|
|Memory (System)|62.82GB (35.35GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
code-gnu-global|aus|0.2.2
gitlens|eam|9.9.3
prettier-vscode|esb|2.2.2
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
resourcemonitor|mut|1.0.6
codebucket|pst|0.2.0
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
taskrunnercode|San|0.3.0
vscodeintellicode|Vis|1.1.9
atlascode|atl|1.4.3
bracket-pair-colorizer|Coe|1.0.61
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
material-icon-theme|PKi|3.9.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@saubhagyarathi Does this reproduce with any file (even plain text `.txt`) ones or does it reproduce only with certain file extensions?

**Comment by alexandrudima** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
