### ISSUE TITLE
Dataviewer support in the debug window

### ISSUE THREAD

**Issue by suvayu** [microsoft/vscode#81203]
**NOTE**: Initially I was filing this in the `vscode-python` issue tracker, but then I found microsoft/vscode-python#6345.  It mentions there is no configurability from vscode.  So I hope this is the right place for this request.

For production data science projects, it would be really useful if there was dataviewer support for variables during a debugging session.  Currently it looks like this (in the screenshot, `slots` is a dataframe):

![vscode-py-debugging](https://user-images.githubusercontent.com/229540/65296558-61705b80-db54-11e9-95af-ca38f6c1f116.png)

An entry in the context menu along the lines of "View in Dataviewer" would be just amazing.
![vscode-py-debugging-ctx-menu](https://user-images.githubusercontent.com/229540/65296562-66cda600-db54-11e9-87b2-cf7f2a6a5e08.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/70377
