### ISSUE TITLE
Unable to open Code in Admin permission if already open without admin permission

### ISSUE THREAD

**Issue by jigartailor1984** [microsoft/vscode#81206]
Issue Type: <b>Bug</b>

I am working on project that needs some things done with admin permission and some thing without admin permission,
Howerver if i have opened code without admin permission then it is not allowing to open with admin permission with message saying that colse other instance of Code and then retry. I want to open code in both mode admin as well as non admin.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kieferrm** [comment]
As a workaround you can have two VS Code installs and run the independently.
