### ISSUE TITLE
get Invalid character, when I copy number from win10's calculator, and paste to vs code

### ISSUE THREAD

**Issue by ianfang217** [microsoft/vscode#81208]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Copy number string from win 10 calculator (ex:100)
2. Paste this number string to vs code.
3. I get red underline, and receive Invalid character.
![image](https://user-images.githubusercontent.com/35757836/65306169-57cc0f80-dbb7-11e9-8e34-399c9e2bab34.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@ianfang217 Can you please share the file or a subset of it that reproduces the problem? I have looked at your steps and the `100` example you give are regular ASCII numbers. I think perhaps you might have had more in your clipboard than ASCII numbers... ?
