### ISSUE TITLE
Single VSCode Workspace, Multiple Versions of Typescript?

### ISSUE THREAD

**Issue by raychz** [microsoft/vscode#81205]
I'm using a single VSCode workspace for my web app project.  My frontend is in one folder/repo and my backend lives in a separate folder/repo.  They each use a different version of Typescript.  

How can one VSCode workspace be associated with multiple versions of Typescript?  It looks like the `Typescript: Tsdk` setting is available only in the user and workspace scopes, not at the folder scope, so my hunch is that this isn't currently supported.  My workspace folders are configured as follows:
```typescript
// MyProject.code-workspace
"folders": [
	{
	    "path": "folderA" // should be using typescript v2.6.2
	},
	{
	    "path": "folderB" // should be using typescript v3.4.5
	},
    ...
]
```
I'd like VSCode to use the respective Typescript versions within `folderA` and `folderB`'s `node_modules`.

**Comment by mjbvz** [comment]
We've discussed supporting this before but don't think it's worth the engineering effort to support. It would also require running multiple typescript servers (which are expensive in terms of memory usage).

Closing as out of scope

**Comment by raychz** [comment]
I would think that running multiple ts servers in one window is way less expensive than running multiple windows, each with a different ts server.

**Comment by raychz** [comment]
That's fair.  Unfortunately, I'm in a position where the TS version of one of my workspaces is locked at 2.x, which was causing red squiggles where there shouldn't have been with VSCode's default TS.  This is an edge case for sure, but I do miss the cohesiveness that came with having my entire project in one window/workspace.

Thanks anyways though!

**Comment by jayoungers** [comment]
> Our thinking was more: better to use a single window with a single TS server across all folders in your workspace as compatibility problems between TS versions are actually not very common (although certainly not impossible to hit)

I'm in a similar situation as @raychz :  if you're working in projects where one is 2.x and another is 3.x, there are likely compatibility problems on almost every file.

I don't mind manually switching the vscode typescript version when switching between project files, but it's annoying that doing so updates the `.code-workspace` file

**Comment by raychz** [comment]
@jayoungers I ended up pulling the folder using the 2.x of TS into its own separate workspace.  This requires that I have two separate VSCode windows open while working on my project.  I haven't noticed too bad of a hit on my machine's resources when doing this.

**Comment by pqnet** [comment]
From what I see running a language server for typescript 2.0 and typescript 5.0 is not much different that running a language server for Java and C#.

With the same reasoning why run multiple language server for multiple languages in the same window?
Should we only have a single language server for each window?
