### ISSUE TITLE
unable to save the file

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#81209]
- VSCode Version: 1.38.1
- OS Version: windows 10

Steps to Reproduce:

1. open a file(Go file) edit something and save it. (It will save without any issues.)
2. now install Go extension and edit .go file and try to save it. I will remove the lines you added and duplicates the last lines in the file
3. Added the below lines
```
// ExtractParameters will describe all the parameters
// ExtractParameters will describe all the parameters
// ExtractParameters will describe all the parameters
// ExtractParameters will describe all the parameters
// ExtractParameters will describe all the parameters
```
4. after saving it remove the above lines and duplicated the last lines in the file.
```
	case api.SQL_DBCLOB:
		return api.SQL_C_DBCHAR
	default:
		panic(fmt.Errorf("unsupported param type %v at sql.out", sqltype))
	}
}
	default:
		panic(fmt.Errorf("unsupported param type %v at sql.out", sqltype))
	}

```

Does this issue occur when all extensions are disabled?: No

**Comment by kieferrm** [comment]
Please file this issue against the vscode-go extension. Thank you!
