### ISSUE TITLE
Alphabet rendering issue

### ISSUE THREAD

**Issue by SanjayBanjade** [microsoft/vscode#81204]
- VSCode Version: 1.39.0-insider
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:
1. If you type "f" and "l" or "f" and "I", you will see these two characters stick together.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31353695/65297404-600c5680-db87-11e9-88b2-0b168bdb1adc.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Your font has ligatures enabled. Set `"editor.fontLigatures": false`
