### ISSUE TITLE
Weird side effect of typo in Font Family setting

### ISSUE THREAD

**Issue by sba923** [microsoft/vscode#81217]
Issue Type: <b>Bug</b>

I made a typo when changing the Font Family to use the newly released Cascadia Code font:

````
'Cascadia Code, Consolas, 'Courier New', monospace
````

This results in a weird display of the Terminal pane:

![image](https://user-images.githubusercontent.com/12860484/65319322-9eae0b00-db9f-11e9-8891-7465080416b5.png)

I would rather expect some form of error message / notification of the user that the setting is invalid.

----------------------------8<---------------------------------------------

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|10.5.0
ng-template|Ang|0.802.3
vscode-color|ans|0.4.5
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
autoit|Dam|0.2.3
vscode-markdownlint|Dav|0.30.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
platformio|for|0.3.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.153
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
rest-client|hum|0.22.1
angular2-switcher|inf|0.2.0
reg|ion|1.0.1
github-pr|jas|1.0.0
rainbow-csv|mec|1.3.1
Angular-BeastCode|Mik|8.0.10
azure-pipelines|ms-|1.157.3
mssql|ms-|1.6.0
remote-wsl|ms-|0.39.5
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
csharp|ms-|1.21.3
powershell-preview|ms-|2019.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.11.7
angular2-inline|nat|0.0.17
printcode|nob|3.0.0
angular-console|nrw|8.1.2
indent-rainbow|ode|7.4.0
platformio-ide|pla|1.8.3
quicktype|qui|12.0.46
java|red|0.49.0
cmake|twx|0.0.17
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.1.9
vscode-svg-previewer|vit|0.5.1
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by sba923** [comment]
I do understand that some behavior results from what has been implemented if the input data is invalid, which is the case in my example.

However, I think users would appreciate being informed that the data is invalid via some message / notification, so that they have more information to troubleshoot than just... the display is incorrect.

So the incorrect display is expected, while the total absence of any notification to the user that the input data isn't valid is not expected.

Do this shed some light on my... expectations? 😉

**Comment by Tyriar** [comment]
You should already be getting this notification:

![image](https://user-images.githubusercontent.com/2193314/65634161-7f91ed80-df92-11e9-8c6f-bbbd185e9da4.png)

That's as much as we can do as we're telling Chromium what font to render, it happens to be invalid but Chromium still draws text just using a default non-monospace font.

**Comment by sba923** [comment]
I've tried 'Arial' with no typo as the Font Family string, and I get this, without any message:

![image](https://user-images.githubusercontent.com/12860484/65692808-8a707f00-e073-11e9-96ff-1f77df6be1f3.png)

**Comment by Tyriar** [comment]
The warning will only show up if the terminal is visible when it changes.

**Comment by sba923** [comment]
Indeed, I _do_ get the warning if the Terminal is visible and I enter

````
'Arial'
````

into the field.

But if I enter this (note the typo):

````
'Cascadia Code, Consolas, 'Courier New', monospace
````

I don't get any message, and the Terminal becomes 'garbled'.

Moreover, if I fix the field as follows:

````
'Cascadia Code', Consolas, 'Courier New', monospace
````

the Terminal _remains_ garbled. I have to close VScode and run it anew to get the correct display.
