### ISSUE TITLE
Ctrl + Shift + m: the PROBLEMS window doesn't update after renaming a folder

### ISSUE THREAD

**Issue by ZC12121Git** [microsoft/vscode#81219]
Issue Type: <b>Bug</b>

REPRODUCE:
step1: create java package folder:
  E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat
step2:create 3 java files in this folder:
  E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat\ClassA111.java
  E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat\ClassA222.java
  E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat\ClassA333.java
step3: set bindinds in java file:
  package com.zhangchao.zctrain.EgTomcat
step4: package name should be lower-case letters, so I changed the folder name:
from:
  E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat
to:
  E:\1project\1vscode\com\zhangchao\zctrain\egtomcat
step5:also changed it in java file:
from:
  package com.zhangchao.zctrain.EgTomcat
to:
    package com.zhangchao.zctrain.egtomcat

BUGS INCOMING:
In java file, no errors, can be compiled successfully.
But the "PROBLEMS" window(called by Ctrl+Shift+m)  doesn't update the foler name, it shows the original path:E:\1project\1vscode\com\zhangchao\zctrain\EgTomcat.
restart the vscode can fix this issue but I hope it can do realtime update, just like the AndroidStudio does.
By the way, it takes about 1 second for a java syntax check,  while AndroidStudio takes less then 0.1 second.

VS Code version: Code - Insiders 1.39.0-insider (575062278d181c075ea8dce345ab3d20a127309c, 2019-09-20T06:11:13.647Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tomcat|ada|0.11.1
vscode-html-css|ecm|0.2.3
vscode-firefox-debug|fir|2.3.0
java|red|0.49.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0

</details>

**Comment by kieferrm** [comment]
Please file the issue against the java extension. Thank you!
