### ISSUE TITLE
Integrated terminal has wrong PATH components order on MacOS

### ISSUE THREAD

**Issue by captainmalloc** [microsoft/vscode#81213]
When a custom path in prepended in the PATH environment variable in the ~/.bash_profile it  is not correctly available in the PATH environment variable from the integrated terminal (while it is in the Terminal App).

Here is how to reproduce the problem:

1. Create a very simple ~/.bash_profile to prepend custom bin path if they are not already available in PATH:

```
      a_bin_dir=/my/custom/install1/bin
      if [[ ":${PATH}:" != *":${a_bin_dir}:"* ]]; then
          export PATH=${a_bin_dir}${PATH+:${PATH}}
      fi

      a_bin_dir=/my/custom/install2/bin
      if [[ ":${PATH}:" != *":${a_bin_dir}:"* ]]; then
          export PATH=${a_bin_dir}${PATH+:${PATH}}
      fi
```

2. Open the Terminal App and validate the expected output:

```
      $ echo $PATH
      /my/custom/install2/bin:/my/custom/install1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

As expected, '/my/custom/install1/bin' and '/my/custom/install2/bin' are prepended in order after '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', and '/sbin', i.e.: the content of /etc/paths

3. Open Visual Studio Code and an integrated terminal in the IDE:

```
	$ echo $PATH
	/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/my/custom/install2/bin:/my/custom/install1/bin
```

Issue: the custom paths are added in the expected order (relative to each other), but the content of /etc/paths is prepended before them. Unfortunately this is incompatible when using 'brew' to redefine/update standard commands available in Mac OS.	

Here is the current workaround I am adding to my ~/.bash_profile:
```

	# If exists, move to front (Fix for VS-Code Terminal
	#  to avoid it putting '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' in front)
	while read bin_dir; do
	    if [[ ":${PATH}:" == *":${bin_dir}:"* ]]; then
        	PATH=${PATH//":${bin_dir}:"/":"} # delete any instances in the middle
        	PATH=${PATH/#"${bin_dir}:"/} # delete any instance at the beginning
	        PATH=${PATH/%":${bin_dir}"/} # delete any instance in the at the end
        	export PATH=${PATH}:${bin_dir}
    	fi
	done < /etc/paths
```

This loop will move the paths described in the /etc/path to the end of the PATH to match the expected order.

For any question, you can contact me at adriano.scoditti@gmail.com

**Comment by Tyriar** [comment]
This is happening because VS Code launches your login shell and then the terminal uses that environment and runs the login shell as well. You can try this setting:

```
"terminal.integrated.inheritEnv": true
```

Or make your .bash_profile idempotent.

**Comment by captainmalloc** [comment]
Thanks for your feedback @Tyriar but it doesn't fit in my case. In my configuration (quite vanilla) the  `terminal.integrated.inheritEnv` was already set to `true`. I actually tried to set it to `false`, the `PATH` has a better shape, but the integrated terminal is not correctly initialized.

I understand I can workaround the issue in my rc-config, that's actually what I am already doing. Still I was hoping to find a more VSCode-integrated solution.
