### ISSUE TITLE
Ability to set custom colors/bold for certain files explorer tree

### ISSUE THREAD

**Issue by code4bones** [microsoft/vscode#81218]
It's could be very handy to mark some dirs/files in the explorer tree by changing their font attributes,
or to make a logical group from dirs/files.

Thanks !

**Comment by isidorn** [comment]
An extension can do this. It can provide a [`decoration provider`](https://github.com/Microsoft/vscode/blob/cd5625c76605f0377a386e849ccd52912470b937/src/vs/vscode.proposed.d.ts#L596) and a way to configure this.
