### ISSUE TITLE
Global Extensions for Remote Work-spaces

### ISSUE THREAD

**Issue by rawkode** [microsoft/vscode#81211]
I'd like the option to configure some extensions to be installed in all remote work-spaces, which are personal extensions (likes macros) that may not fit the workflow of other developers on the team; hence they wouldn't be specified in the `devcontainer.json`

**Comment by chrmarti** [comment]
@rawkode If this is a request for Remote-Containers, there is a setting for that:
![image](https://user-images.githubusercontent.com/9205389/65493918-25225f80-deb4-11e9-9194-5040c33457de.png)

Does that do what you need?

**Comment by rawkode** [comment]
@chrmarti yes, that's perfect. Sorry, I must have missed that setting. Thank you
