### ISSUE TITLE
VSCode leaves text file without line terminator

### ISSUE THREAD

**Issue by linuxjh** [microsoft/vscode#81214]
Is this a feature?

Xcode editor always appends line terminator at the end of file.

$ cat Textfile.txt 
hello$ 
$
$ file Textfile.txt 
Textfile.txt: ASCII text, with no line terminators
$ 

VSCode Version: 1.38.1
macOS Mojave: 10.14.6

**Comment by kieferrm** [comment]
Please use the following user setting: 
```json
"files.insertFinalNewline": true
```
