### ISSUE TITLE
Problem matcher doesn't work after update

### ISSUE THREAD

**Issue by krzikalla** [microsoft/vscode#81215]
- VSCode Version: 1.38.1
- OS Version: RHEL 7.6

Updated from 1.37.x to 1.38.1. Before the update, errors and warnings were listed in the Problems tab after compiling. Now nothing happens after the compile step.
This is the entry in tasks.json:

"problemMatcher": {
          "base": "$gcc",
          "fileLocation": ["relative","${workspaceFolder}/gaspi"]
        },

**Comment by alexr00** [comment]
The gcc problem matcher comes from an extension.
