### ISSUE TITLE
Extension preview Install button clipped at bottom

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8121]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 10

Steps to Reproduce:

1. Bring up Extension View
2. Click on an extension
3. Look at the banner in the extension preview window.

The green Install button is clipped.
![install-clipped](https://cloud.githubusercontent.com/assets/12818376/16351019/64e89a48-3a17-11e6-8dd5-7cb1a26dd859.png)

**Comment by bpasero** [comment]
Moving to @isidorn since Joao is out next week to consider if this is something for the release. Otherwise feel free to move back.
