### ISSUE TITLE
Please allow overriding theme icon colors

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#81216]
This the original issue: https://github.com/microsoft/vscode-docs/issues/3086

As it stands now, it is impossible to create light theme with dark tab bar. While i understand that allowing to theme every single element is too much work, an easier option would've been to allow overriding "dark" vs "light" type for every icon (e.g. menu key shortcuts, palette key shortcuts, tab bar icons, etc.).

This would allow creation of themes that are reminiscent of Qt Creator interface (light theme), which is nicely balanced and clearly delineates active areas without being all white and in your face like VSCode is.

**Comment by misolori** [comment]
I'm going to say this is covered by https://github.com/microsoft/vscode/issues/78889 which introduces icon fonts and color themes for icons.
