### ISSUE TITLE
Add Block Function/Global code fragments: Each line of code requires double quotation marks and is good for newline

### ISSUE THREAD

**Issue by fanaone** [microsoft/vscode#81210]
Add Block Function/Global code fragments: Each line of code requires double quotation marks and is good for newline.

Web development technology: Template strings use back quotation marks (``) instead of double and single quotation marks in common strings.

for example:

var value=	
`string text line 1
 string text line 2`

I recommend adding support for Template Strings (``) to make it easier to add multiple lines of code blocks.

**Comment by kieferrm** [comment]
Please describe your proposal in more detail. What programming language? What do you concretely propose? Thank you!

**Comment by fanaone** [comment]
When I create global user code and create custom blocks in the body of'<bod>', I need to add double quotation marks to the line-by-line data.
![image](https://user-images.githubusercontent.com/33046803/65499738-adbef100-def0-11e9-936a-32e4194df605.png)
but we can use (``)to represent a string like on the json.
![image](https://user-images.githubusercontent.com/33046803/65499758-b9121c80-def0-11e9-9a96-069610a57a70.png)

Web development technology: Template strings use back quotation marks (``), which can represent string templates
see in here:
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by fanaone** [comment]
as follows：

![image](https://user-images.githubusercontent.com/33046803/65500509-ff1bb000-def1-11e9-9b0d-82c0249af7bd.png)

**Comment by fanaone** [comment]
When I create global user code and create custom blocks in the body of'<bod>', I need to add double quotation marks to the line-by-line data. 





but we can use (``)to represent a string like on the json.



Web development technology: Template strings use back quotation marks (``), which can represent string templates
see in here:
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
------------------ 原始邮件 ------------------
发件人: "vscodebot[bot]"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 上午9:28
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "我忧动甜心"<3096027984@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Add Block Function/Global code fragments: Eachline of code requires double quotation marks and is good for newline (#81210)




Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our issue reporting guidelines. Please take the time to review these and update the issue.
 
Happy Coding!

**Comment by chrmarti** [comment]
We are limited by what the JSON syntax supports and that does not have a way to represent multiline strings (except by using `\n` on a single line).

I'm closing this as we cannot change it. Thanks for your suggestion.
