### ISSUE TITLE
if a bug is related to an extention, please provide link to that extention

### ISSUE THREAD

**Issue by yetanotherlogonfail** [microsoft/vscode#81223]
if a bug is related to an extention, please provide link to that extention - git hub needs to add function to move this 
issue to an issue in extention and leave a link to follow. as a minimum, at best the link could have icon to reflect 
if the new issue has been resolved or not.

im amazed (not) that the bug here has still not been fixed! raised in May 2018

RE: Installing extension dependencies does not clear "Installing packages..." message in Status Bar #49809
https://github.com/Microsoft/vscode/issues/49809

**Comment by gjsjohnmurray** [comment]
If I understand you correctly, you seem to be raising an issue about GitHub , not about VSCode

**Comment by kieferrm** [comment]
We ask the original author of the issue to create a new issue. The author can add a reference if they want to. We can't force them to.
