### ISSUE TITLE
Ctrl+Backspace in terminal

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#81225]
Issue Type: <b>Bug</b>

Ctrl+Backspace in terminal should delete the word to the left of the cursor, but it actually inserts some kind of character that is rendered as `^W`.

Using ctrl+backspace works fine in the native cmd.exe.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (15.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
overtype|ada|0.2.0
Bookmarks|ale|10.5.0
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
file-icons|fil|1.0.19
duplicate|gee|1.0.1
docthis|joe|0.7.1
rainbow-csv|mec|1.3.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|0.8.1
remote-wsl|ms-|0.39.5
vscode-versionlens|pfl|0.24.0
vscode-template-literal-editor|pli|0.9.0
vscode-sort-json|ric|1.14.0
code-settings-sync|Sha|3.4.2
vscode-svg-previewer|vit|0.5.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This is by design currently, we send the sequence for telling bash to delete the word to the left, however you're able to customize exactly what is sent using this https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding

**Comment by thany** [comment]
Expected: delete word left of the cursor.
Not expected: insert `^W`, whatever that is.

That's it.
Just try it in cmd.exe! That's the best way to get it "explained" really.

**Comment by Tyriar** [comment]
It's not possible to send text to do it in cmd afaik due to how the terminal uses a pty->console api emulation layer underneath. Plus the terminal doesn't differentiate shell types for keybindings, you are also to customize it to send whatever you want or disable it completely using the link above though.

**Comment by thany** [comment]
So does it mean that the terminal pane sort of "prefers" bash? Because the way things are now, Ctrl+Backspace sends the correct sequence to bash, but incorrect one for cmd. You could try to send the correct one to cmd, which will probably break it for bash.

I think the terminal pane should be able to differentiate between shells when it comes to "special" shortcut keys like this one. After all, there's more than just cmd and bash, and I think even macOS uses a different one by default, and so to a number of linux flavours. And there's powershell, too. (As I'm sure you know - just pointing it out to be on the safe side)

I'll try to customizing the keybinding so it'll work right for me, but please understand that this is a workaround, and will only work as long as I don't need bash.

**Comment by thany** [comment]
A bit later.
I can't seem to figure out what to put in `"args": { "text": "\u001b[1;5D\u007f" }` from the example.

And since the default keybinding is
```json
{ "key": "ctrl+backspace", "command": "workbench.action.terminal.deleteWordLeft", "when": "terminalFocus" },
```
I actually *can't* customize the control sequence it's sending. I have to make up one myself, and I have absolutely no clue how make it send Ctrl+backspace when I press Ctrl+backspace, and I must put that in a string. Do I need a control sequence like "hold down ctrl, send backspace, release ctrl" or something? Or is there a single magic character that represents ctrl+backspace? No idea. Probably neither 😀

**Comment by Tyriar** [comment]
> You could try to send the correct one to cmd, which will probably break it for bash.

There isn't one for cmd. It's not as trivial as it sounds to do this, otherwise it would work as you're suggest.

**Comment by thany** [comment]
Then why would you suggest the keybinding workaround?
Is there another way to get this to work?
