### ISSUE TITLE
Font ligatures and the Menlo font cause indentation problems

### ISSUE THREAD

**Issue by ashemedai** [microsoft/vscode#81228]
Issue Type: <b>Bug</b>

Using the macOS Menlo font with ligatures turned on causes issues with indentation.

With ligatures on:
![image](https://user-images.githubusercontent.com/610865/65328361-7087f580-dbb6-11e9-8895-0598bb861659.png)

Note the visual indentation being off for the `frontend_ip_configuration_name`. This is purely visual though. The equal signs are all on column 34.

Turning font ligatures off:
![image](https://user-images.githubusercontent.com/610865/65328458-ac22bf80-dbb6-11e9-8eb9-dc7dce764776.png)

As can be seen, the `f` and `i` became a single glyph.

I realise this is most likely not a bug within VS Code, but rather that the font supports more ligatures that you would not expect in a monospace font. I could not find any other issue on this, so hopefully this will help people web searching for something like this.

Would it warrant a warning within VS Code itself if someone has certain fonts configured and tries to enable ligatures? Or would a documentation section be welcomed that details potential issues with certain font selections?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 4, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-modelines|chr|2.0.4
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.2
xml|Dot|2.5.0
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
restructuredtext|lex|114.0.0
terraform|mau|1.4.0
rainbow-csv|mec|1.3.1
hg|mrc|1.3.0
vscode-docker|ms-|0.8.1
pyright|ms-|1.0.63
python|ms-|2019.9.34911
Go|ms-|0.11.5
powershell|ms-|2019.5.0
azurerm-vscode-tools|msa|0.6.0
indent-rainbow|ode|7.4.0
rust|rus|0.6.3
indenticator|Sir|0.6.0
code-spell-checker|str|1.7.18
sort-lines|Tyr|1.8.0

</details>

**Comment by alexandrudima** [comment]
I wouldn't want to do anything too smart with warnings on our side... It is perfectly fine to use Menlo with ligatures, with the side effect that it isn't monospace anymore... There could be any number of folks using VS Code for editing markdown or other such things where having a monospace font is not that important...
