### ISSUE TITLE
VS Code Locks files

### ISSUE THREAD

**Issue by amarth1982** [microsoft/vscode#81224]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Run a node container with a simple node application source mounted to it from WSL
2. Open the Source folder using Remote WSL in VS Code
3.  Open a terminal and bash exec into the container and try the following
4. run npm install some-package command, it will create a temp package.json and package-lock.json
5. run any npm script, like npm start or npm run build, npm will complain that there is no package.json
6. however ls on the folder will still show it
7. when I close vscode, the package.json file would have been removed along with the temp files, it could still be the way npm tries to write to the file, however I guess its because vscode locking the file.
8. instead of npm commands, using command like rm or mv to remove or rename file will throw error that permission denied for any files inside the source folder

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (14.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.52GB (14.75GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.52GB (14.75GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-peacock|joh|3.1.5
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
vscode-icons|vsc|9.3.0
vscode-postgres|cko|1.1.11
docs-markdown|doc|0.2.18
vscode-pull-request-github|Git|0.11.2
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
vscode-typescript-tslint-plugin|ms-|1.2.2
markdown-preview-enhanced|shd|0.4.3

</details>

**Comment by kieferrm** [comment]
This is an issue with the current version of WSL. WLS v2 is in the works that will resolve this issue.

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
