### ISSUE TITLE
App detects a newer version but cannot update itself

### ISSUE THREAD

**Issue by ShiranC** [Microsoft/vscode#8122]
- VSCode Version: 1.1.1 (1.1.1)
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. When app detects availability of newer version, select "Update Now" from prompt at top of window
2.

**Comment by ShiranC** [comment]
I have a similar problem with two other apps: GitHub "Atom" editor and "Brave" browser.
I believe all three apps use the "Electron" shell and "Squirrel" for software updates.

**Comment by joaomoreno** [comment]
Given that you seem to have problems across the whole Squirrel spectrum, I suggest to look into the [Squirrel/Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) project itself.
