### ISSUE TITLE
vs code suddenly stopped responding

### ISSUE THREAD

**Issue by butioy** [microsoft/vscode#81221]
Issue Type: <b>Bug</b>

I want to stitch a panda graphic with characters. When I was about to finish, I typed a "P" character and the vs code suddenly stopped responding. After turning it off and re-entering "P", the problem still occurs.

<b>There is a problem entering "P" at the position of the cursor below:</b>

![Image of Yaktocat](https://raw.githubusercontent.com/butioy/demo/master/vs_code_bug.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-27-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3440)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.61GB (0.70GB free)|
|Process Argv|--unity-launch /home/butioy/Documents/panda.txt|
|Screen Reader|no|
|VM|0%|
|OS|Ubuntu 18.04.3 LTS|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.38.4
vetur|oct|0.22.3

</details>

**Comment by kieferrm** [comment]
Can you pls run `code --status` when it happens?
