### ISSUE TITLE
VSCode Editor Crashes when a folder is deleted

### ISSUE THREAD

**Issue by meatnordrink** [microsoft/vscode#81227]
When I try to delete a folder within a repo, VSCode freezes. 

VS Code 1.38.1
Ubuntu 19.04 (Kubuntu)

And yes, it happens when VScode is launched without extensions. 

Exact steps to reproduce: 

1. Open a multi-folder workspace in VSCode, where each folder is a git repo. 
2. Select a sub-folder of one of the parent folders (repos); in my case, 3rd level in. 
3. Right-click, and select "Delete". 
4. VSCode freezes. 

I have verified that I can delete the same folder without issue using Sublime or Atom.

**Comment by kieferrm** [comment]
Please provide concrete steps to reproduce the problem. Thank you.

**Comment by meatnordrink** [comment]
Updated! Thanks for checking this out.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by meatnordrink** [comment]
> Please see if you can find any logged output that could help us find the source of the issue:

Hi @bpasero , 

Unfortunately, as chance would have it, I just replaced that Kubuntu partition (the day before you asked for the logs), for unrelated reasons, with KDE Neon, and I'm no longer getting the same issue. 

Thanks for your attention to this! I'll close the issue now, as I can no longer reproduce it.
