### ISSUE TITLE
Find a symbol doesn't search across all folders in a workspace

### ISSUE THREAD

**Issue by anirudh1800** [microsoft/vscode#81234]
Issue Type: <b>Bug</b>

Open a multi-root workspace
Go to one of the folders, open a file in editor
Press command + p, #(put symbol from other folder)
Observe no results

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.13GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
java-decompiler|dgi|0.0.2
gitlens|eam|9.9.3
vscode-todo-plus|fab|4.14.1
vscode-lombok|Gab|0.9.9
intellij-idea-keybindings|k--|0.2.34
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
Go|ms-|0.11.5
java|red|0.49.0
vscode-xml|red|0.9.0
vscode-yaml|red|0.5.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.21.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0
vim|vsc|1.10.2

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
This depends on the project notion of the language you are using. If it's language support you got from an extension, pls close this issue and file the issue there. Thanks!
