### ISSUE TITLE
Plugging in 1x monitor to 2x Mac

### ISSUE THREAD

**Issue by PhilSwn** [microsoft/vscode#81239]
Issue Type: <b>Bug</b>

When I plug in a 1x monitor to my 2x Mac and VSC is automatically moved to the 1x monitor from the Mac, the terminal text is broken in a way that is small, thin, and hard to read. It is fixed by resizing the terminal.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.4.0-161-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: yes|
|OS|Linux x64 4.4.0-161-generic|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 1663)|
|Memory (System)|15.63GB (3.13GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|3.1.5
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
debugger-for-chrome|msj|4.11.7
gitlens|eam|9.9.3
git-open-diff|kap|1.3.2
partial-diff|ryu|1.4.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
@PhilSwn can you pls attach a screenshot? Thanks!

**Comment by PhilSwn** [comment]
@kieferrm  This time it only happened with the terminal inputs.
![Screen Shot 2019-09-20 at 11 56 28 AM](https://user-images.githubusercontent.com/779915/65344742-1ed37100-db9e-11e9-9e3c-5f6f9192b2e7.png)

**Comment by PhilSwn** [comment]
Also noticed that a similar reverse effect happens when it is moved from 1x to 2x by unplugging the monitor:
![image](https://user-images.githubusercontent.com/779915/65345438-e339a680-db9f-11e9-9dcd-149aa99e57f3.png)

**Comment by Tyriar** [comment]
Let's track this upstream, some workarounds:

- Change renderer type to "dom" in settings (this will be slower over all but should be correct)
- zoom in and out whenever this happens (ctrl++, ctrl+-)

https://github.com/xtermjs/xterm.js/issues/2438
