### ISSUE TITLE
Feature Request: Sidebar AutoReveal Filtering

### ISSUE THREAD

**Issue by psylum** [microsoft/vscode#81236]
Several people have brought up instances where `explorer.autoReveal`, when activated, causes an undesirable change to the sidebar. It would be nice if there were a richer way to configure this option.

For me, the main complaint with autoReveal is when i ctrl-click on a type in a TypeScript project, which jumps me deep into node_modules where the `.d.ts` file is. i'll usually look through that file, close it, and go back to what i was coding. However, because of autoReveal, i now have node_modules expanded, which on large projects completely overwhelms my sidebar. I'd like to have a way to either explicitly add paths to ignore, or have a way to use say, .gitignore's paths (i know they're evaluated in some fashion since they're de-emphasized visually in the sidebar).

I'm aware that there's a way to hover/display a pop-up of a definition, but more often than not, i'll just use the default 'go to' since its the easiest, and in many cases i do need to see more context from that overall typing definition file.

**Comment by isidorn** [comment]
This is a fair feature request to add an auto reveal ignore setting which contain a glob pattern of files, however we do not have plans to add this in the upcoming time frame. Thus assigning to backlog for now. Thanks
