### ISSUE TITLE
Crash when opening big text file (800MB)

### ISSUE THREAD

**Issue by michalzemko** [microsoft/vscode#81232]
I use VS code to read logs. When I try to open big log file (~800MB text file) VS code crashes. I use few extensions to work with log (highlight-words, filter line, Bookmarks). I trie to set colorizing from .log to Plain Text, but didn't help.
Split file to multiple 500MB works
Let me know, if you need more information.

CPUs | Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 31.86GB (5.80GB free)

Extension | Author (truncated) | Version
-- | -- | --
Bookmarks | ale | 10.5.0
code-gnu-global | aus | 0.2.2
filter-line | eve | 1.3.2
cpptools | ms- | 0.25.1
highlight-words | rsb | 0.1.4

**Comment by kieferrm** [comment]
@michalzemko 

What's your value for max memory?

![image](https://user-images.githubusercontent.com/4674940/65345505-4cfd8480-db8f-11e9-9b8f-3ebae85bc85d.png)

Do you get any notification to restart VS Code with your configured max memory?

![image](https://user-images.githubusercontent.com/4674940/65345887-30ae1780-db90-11e9-95a9-0d35b896f251.png)

I open files of 2GB without any issue.

What happens when you disable your extensions?

**Comment by michalzemko** [comment]
When I've disabled all extensions, VS crashes again. Only "The window has crashed"dialog is shown

![VS crash](https://user-images.githubusercontent.com/4049243/65406831-fc7d6580-dde0-11e9-9990-8adc623fa02d.png)

No aditional dialgo about seting max memory is shown.
When I checked "editor.largeFileOptimizations", VS didn't crash.
When I set "files.maxMemoryForLargeFilesMB" to 8192 or to  16384 VS crashed.

**Comment by alexandrudima** [comment]
> When I checked "editor.largeFileOptimizations", VS didn't crash.

@michalzemko If you plan to open huge files, then please configure `"editor.largeFileOptimizations": true` (the default).

That is the purpose of the setting, if you configure `"editor.largeFileOptimizations": false`, then the editor will burn memory like crazy to give you features such as word wrapping and folding for any file size... That will lead to an out-of-memory crash.
