### ISSUE TITLE
"editor.formatOnType" does not respect "editor.defaultFormatter"

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81235]
This happens with the current insiders version 1.39.0.

- VSCode Version: 1.38.1
- OS Version: macOS 10.14.6

**Steps to Reproduce:**
1. Install the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension
2. Set `"editor.defaultFormatter": "esbenp.prettier-vscode"`, `"prettier.bracketSpacing": false` and `"editor.formatOnType": true`
3. Begin writing an object destructuring line without spaces around the brackets: `const {variable}`

**Expected:**
`const {variable}`

**What actually happens:**
`const { variable }`

**Does this issue occur when all extensions are disabled?**
Can't replicate without the Prettier extension.

**Comment by jrieken** [comment]
Yeah, currently not supported at the moment because few extension implement the format on type ability (e.g prettier also does not which means implementing this feature won't help you)

**Comment by andrecasal** [comment]
That's too bad. If editors don't offer that ability, there's no incentive for extensions to implement it either. I'm thinking it would be relatively easy to implement this feature: send the current line to the extension and parse the result. If someone could point me to the right file, I'd be willing to give this a try.

**Comment by jrieken** [comment]
> If editors don't offer that ability, there's no incentive for extensions to implement it either

The editor has everything it needs - however, the functionality needs to be implemented in the respective extension, prettier in this case.

**Comment by andrecasal** [comment]
I'm confused. VS Code already supports this feature? It's just Prettier that isn't using it?

**Comment by jrieken** [comment]
Yes - prettier isn't implementing the interface to support format on type (https://github.com/microsoft/vscode/blob/d859157d39a846ce58d99f22c8011f5d6a513959/src/vs/vscode.d.ts#L3080)

**Comment by andrecasal** [comment]
Oh cool! I'll request that feature if it isn't already requested. Thanks @jrieken !
