### ISSUE TITLE
Quick Open "ext" and "ext install" not working

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8123]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 10

These commands just hang and never complete. We probably want to remove "ext" now that we have the Extension View but we should keep "ext install blah" working since there is a lot of external documentation that calls out using Quick Open "ext install blah" to install an extension.

The Marketplace also calls out "ext install" and we need to leave this up for at least a couple of VS Code releases for people who aren't yet on the June release.

**Comment by maierson** [comment]
Actually this hangs for a while after which it gives this error:

`Unable to instanciate quick open handler vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen - ExtensionsHandler: {"errorCode":"load","moduleId":"vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen","neededBy":["===anonymous8==="],"detail":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/parts/extensions/electron-browser/extensionsQuickOpen.js"}}`

**Comment by shanselman** [comment]
Why are we removing "Ext install"? The new way is REALLY not intuitive.

**Comment by joaomoreno** [comment]
Damn build errors. When are we going to fix this crap?
