### ISSUE TITLE
Terminal Sidebar

### ISSUE THREAD

**Issue by mscottcam** [microsoft/vscode#81243]
Issue Type: <b>Bug</b>

When I have the terminal/search feature as the sidebar, the width changes on me when I lock my computer and come back to the program later. I like the sidebar wider than the default, but it seems to go back to the default every time. Is there a way to set the default width or is this a bug?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.4.3
vscode-npm-script|eg2|0.3.9
graphql-for-vscode|kum|1.15.1
vscode-language-babel|mgm|0.0.24
debugger-for-chrome|msj|4.11.7
vscode-react-native|msj|0.11.1
material-icon-theme|PKi|3.9.0
highlight-matching-tag|vin|0.9.5
vim|vsc|1.10.2
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@mscottcam Can you clarify your layout a bit for me? It is probably easiest if you share a screenshot of the entire window before and after reproducing the issue. 

Secondly, can you tell me if there are any additional steps besides locking the screen and then unlocking?

**Comment by mscottcam** [comment]
That right sidebar is what gets resized all the time.

On Sep 23, 2019, at 10:31 PM, SteVen Batten <notifications@github.com> wrote:

@mscottcam <https://github.com/mscottcam> Can you clarify your layout a bit for me? It is probably easiest if you share a screenshot of the entire window before and after reproducing the issue.

Secondly, can you tell me if there are any additional steps besides locking the screen and then unlocking?

**Comment by sbatten** [comment]
@mscottcam I still cannot reproduce this issue, can you provide me with a screenshot of before and after? Also, are there any more steps besides lock and unlock? How long do you wait? Is the window remaining open, etc?
