### ISSUE TITLE
broken select

### ISSUE THREAD

**Issue by ethanj** [microsoft/vscode#81249]
Issue Type: <b>Bug</b>

![vscode-bug](https://user-images.githubusercontent.com/1934146/65359678-1c7b1200-dbb2-11e9-9112-8f3b8a4bfa65.gif)

expected behavior: as soon as the cursor turns to text selection, you should be able to select text.

actual behavior: move cursor slowly from left until you see the text selection cursor, then click and try to select text. If you try on the first pixel on which the cursor changes, you cannot select text. Hoever as you can see on the second try, if you move over 1 extra pixel it works correctly.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

**Comment by alexandrudima** [comment]
Interestingly, I cannot reproduce, I can always click when seeing the I cursor. Are you using some kind of zooming? (i.e. `window.zoomLevel` ?)

**Comment by ethanj** [comment]
This appears to be an inconsistent bug. 
Currently, it seems to have gone away but I have noticed it over the last year or so when it rears its ugly head. As you can imagine it is unnerving when selection doesn't work quite right.

I never manually adjusted the window zoom level, but it is currently set to -1.
I will try setting to 0 and let you know if/when the bug shows up again.. not sure if you wanna keep the issue open or not.. up to you.

**Comment by alexandrudima** [comment]
Zooming via `window.zoomLevel` is super convenient for presenting/projecting, but it is implemented by Chromium ... in a way where pixel perfection gets lost... All of our integer coordinates / sizes get then projected via the zoom factor into ugly floats which sometime get rounded in funny way which end up causing 1px gaps here and there, depending on the window position, etc.

My recommendation is to avoid `window.zoomLevel` if you care about pixel perfection and to customize `editor.fontSize`, `editor.lineHeight` and ... to upvote #519 to get this implemented throughout the workbench...
