### ISSUE TITLE
Cannot write user Settings

### ISSUE THREAD

**Issue by svulcans** [microsoft/vscode#81242]
help
vscode Unable to write user Settings.Open user Settings and clear errors or warnings, then try again.Under windowsx

**Comment by svulcans** [comment]
{
    "editor.fontSize": 18,
    "workbench.statusBar.feedback.visible": false,
    "editor.formatOnPaste"                : true,
    "workbench.sideBar.location"          : "right",
    "workbench.startupEditor"             : "newUntitledFile",
    "terminal.integrated.shell.windows"   : "D:\\Program Files\\Git\\bin\\bash.exe",
    "sync.gist"                           : "ced8447aeba1189b4f00d16e2bbeafa4",
    "files.autoSave": "afterDelay",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "explorer.confirmDelete": false,
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "workbench.activityBar.visible": true,
    "[html]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "window.menuBarVisibility": "default",
    "workbench.statusBar.visible": true,
    "editor.minimap.enabled": false,
    "[css]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[php]": {
        "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
    },
    "workbench.colorTheme": "One Dark Pro Monokai Darker",
    "[jsonc]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "vsicons.dontShowNewVersionMessage": true,
    "sync.forceUpload": true,
    "remote.SSH.showLoginTerminal": true,
    "extensions.ignoreRecommendations": false,
    "update.enableWindowsBackgroundUpdates": false,
    "view-in-browser.customBrowser": "mozilla",
    "files.autoGuessEncoding": true
    "code-runner.runInTerminal": true
}

**Comment by svulcans** [comment]
Cannot write user Settings.Open user Settings and clear errors or warnings, then try again.

**Comment by svulcans** [comment]
This is my setup

{
    "editor.fontSize": 18,
    "workbench.statusBar.feedback.visible": false,
    "editor.formatOnPaste"                : true,
    "workbench.sideBar.location"          : "right",
    "workbench.startupEditor"             : "newUntitledFile",
    "terminal.integrated.shell.windows"   : "D:\\Program Files\\Git\\bin\\bash.exe",
    "sync.gist"                           : "ced8447aeba1189b4f00d16e2bbeafa4",
    "files.autoSave": "afterDelay",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "explorer.confirmDelete": false,
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "workbench.activityBar.visible": true,
    "[html]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "window.menuBarVisibility": "default",
    "workbench.statusBar.visible": true,
    "editor.minimap.enabled": false,
    "[css]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[php]": {
        "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
    },
    "workbench.colorTheme": "One Dark Pro Monokai Darker",
    "[jsonc]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "vsicons.dontShowNewVersionMessage": true,
    "sync.forceUpload": true,
    "remote.SSH.showLoginTerminal": true,
    "extensions.ignoreRecommendations": false,
    "update.enableWindowsBackgroundUpdates": false,
    "view-in-browser.customBrowser": "mozilla",
    "files.autoGuessEncoding": true
    "code-runner.runInTerminal": true
}

**Comment by chrmarti** [comment]
What errors are you referring to? Can you attach a screenshot or copy&paste them?
