### ISSUE TITLE
quick open (ctrl+p) speedup suggestion for large projects.

### ISSUE THREAD

**Issue by dibalavs** [microsoft/vscode#81241]
Hello,

I have a large project, contained whole sources of qt libraries and sources of chromium project.
So searching any file with (ctrl + p) takes some seconds.
I have suggestion how it can be improved.

The main idea is that location of file I want to find is near currently opened file in editor.
For example, If I edit some file in blink library of chrome, The most probable that I will find another file inside blink component, or inside chromium project.

So search engine, can start searching from location or currently opened file. And then search files and directories that far away from current location.

This idea is also implemented by "editor.suggest.localityBonus" setting. But it is not used by quick open feature.

**Comment by roblourens** [comment]
We have to seach the full workspace before we can show any results, because they have to be sorted. So something like that won't really help, but thanks for the suggestion.

**Comment by roblourens** [comment]
1. is actually basically what we do. The first search is slow, but the second one will search using the first one's cache.
