### ISSUE TITLE
Please allow user to customize `Go:Switch Editor:Next Editor/Previous Editor` keyboard shortcut

### ISSUE THREAD

**Issue by leozhao0709** [microsoft/vscode#81245]
I want to customize the keyboard shortcut key of cursor jump in split view. I see in the menu, there is `Go:Switch Editor:Next Editor/Previous Editor` can do it, but I didn't find it in keyboard shortcut map.

![keyboardShortcut](https://user-images.githubusercontent.com/10889192/65350337-58a27880-db9a-11e9-9380-4b52eff10f69.png)

**Comment by kieferrm** [comment]
It's "View: Open Previous Editor". It seems like render PageUp as an upward arrow.

**Comment by leizhao-coupa** [comment]
oh, I see. It works then, thanks!
