### ISSUE TITLE
Key Stroke combination in example gif

### ISSUE THREAD

**Issue by OnAll** [microsoft/vscode#81257]
Issue Type: <b>Feature Request</b>

Can you include the key stroke alongwith the example in the gif or any animation that you provide as an exmaple of Extenstion under the Details section.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
Extension authors provide this content, so your request needs to be logged at each extension's repo.
