### ISSUE TITLE
Go to file: prefix with / to prefer results in root

### ISSUE THREAD

**Issue by Nowaker** [microsoft/vscode#81250]
I'd like to open `index.html` in root. Using the "go to file" feature for that is currently not friendly because it's a 14th match. In general, the sorting feels totally random.

![image](https://user-images.githubusercontent.com/611746/65364240-20b92680-dbd6-11e9-8160-c4a941257677.png)

Feature request: prepend the search with `/`, e.g. `/index.html` to indicate which index.html I want.

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/72a381699f549b3f1c7c38b2b9a6d9a1de06f603 the sorting is more predictable now, previously items with same score would be sorted by recency but that would always result in a different sort order depending on what file was opened last. We now simply use the same sorting as for normal file searches and prefer shorter matches over longer.

Nevertheless, a new setting `"search.quickOpen.history.filterSortOrder": "recency"` allows to strictly sort by recency in the history list (https://github.com/microsoft/vscode/issues/35610).

**Comment by bpasero** [comment]
**Verification**
Have a workspace with many files of the same name in different folders and verify that the one with the shorted path appears to the top when you search by name in the "recently opened" bucket (might require that you open each file first once).
