### ISSUE TITLE
Python parameter hint cannot be turned off.

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/vscode#81256]
- VSCode Version: 1.38.1
- OS Version: Ubuntu 18 LTS

Steps to Reproduce:

I've 
    "editor.parameterHints.enabled": false,
    "editor.parameterHints": false,
in my setting file.

Just type
"**print(**" ,eg

Observed:
parameter hint popped out.
![image](https://user-images.githubusercontent.com/12282281/65367827-96c88800-dbec-11e9-8140-7dbf6f371dcb.png)

Expected.
parameter hint should not pop out because of the setting.

Does this issue occur when all extensions are disabled?: It happened in .py code with Python plugin installed.

**Comment by 9527KGG** [comment]
Not the same. That one got closed. However, the issue still repro.

**Comment by 9527KGG** [comment]
I install MS C++ plugin. C++ has the same issue.

![image](https://user-images.githubusercontent.com/12282281/65657771-ae7f8200-dfd9-11e9-8c76-f18cce699702.png)

Thanks.

**Comment by 9527KGG** [comment]
Basically
    "editor.parameterHints.enabled": false,
has no effect. Very annoying.

Thanks for helping

**Comment by 9527KGG** [comment]
what I observed is: for this option:

![image](https://user-images.githubusercontent.com/12282281/65851394-9c6a5000-e307-11e9-9fbb-d3d8ca67ac8e.png)

whenever I unclick it, vscode automatically click it. Weird.

**Comment by jrieken** [comment]
>I've
"editor.parameterHints.enabled": false,
"editor.parameterHints": false,
in my setting file.

Remove this: `"editor.parameterHints": false`

**Comment by jrieken** [comment]
fyi @sandy081, @alexandrudima as this is a case in which an invalid config breaks (sub) configurations.

**Comment by alexandrudima** [comment]
@jrieken here is the place where old option migration needs to happen in the editor land -- https://github.com/microsoft/vscode/blob/d859157d39a846ce58d99f22c8011f5d6a513959/src/vs/editor/common/config/commonEditorConfig.ts#L145

My best guess is that in this case the last one wins (`"editor.parameterHints": false`) and then the editor receives a boolean where it expects an object. I think the validation code would then fall back to use the default.
