### ISSUE TITLE
Not able to load Python Interpreter for Virtual Environment

### ISSUE THREAD

**Issue by devananths** [microsoft/vscode#81259]
Issue Type: <b>Bug</b>

Hi,

I installed a python extension once I installed VS Code. Also I created a virtual enviroment inside my python36 folder. But when I try to select the corresponding python interpreter it is not showing up the same. I tried disabling and enabling as well as uninstalling and installing the python extension as well. I could not fix it, kindly assist me. Thank You.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911

</details>

**Comment by kieferrm** [comment]
Please file this issue against the Python extension. Thank you!
