### ISSUE TITLE
Dependencies not showing latest version on hover

### ISSUE THREAD

**Issue by alexdevero** [microsoft/vscode#81255]
Issue Type: <b>Bug</b>

Dependencies listed in package.json should show the latest version avalable on npm. This worked in previous versions. It no longer works after installing the latest insider version. Now, hovering over dependencies doesn't do anything.

VS Code version: Code - Insiders 1.39.0-insider (8b6e0efc0a98639085fabeb5226a516785424796, 2019-09-19T03:15:21.720Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|10.7.0
color-info|bie|0.5.1
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
javascript-ejs-support|Dig|1.1.3
es7-react-js-snippets|dsz|2.4.3
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
rightclick-git|Eve|1.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
check-npm-updates|iak|1.7.4
svg|joc|1.0.2
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.26
vscode-colorize|kam|0.8.13
wordcounter|kir|1.9.3
contextualduplicate|laf|0.2.0
vscode-language-babel|mgm|0.0.24
postcss-language|mhm|2.1.0
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.2.3
vscode-duplicate|mrm|1.2.1
language-gettext|mro|0.1.1
vscode-azureappservice|ms-|0.16.0
azure-account|ms-|0.8.4
vscode-react-native|msj|0.11.1
react-proptypes-intellisense|OfH|1.0.3
material-icon-theme|PKi|3.9.0
multi-command|ryu|1.3.0
code-settings-sync|Sha|3.4.2
stylelint|shi|0.51.0
code-spell-checker|str|1.7.18
code-spell-checker-czech|str|0.1.0
pdf|tom|0.5.1
vscode-icons|vsc|9.3.0
WebTemplateStudio-dev-nightly|WAS|0.0.1925201
dictionary-completion|yzh|0.8.3

(1 theme extensions excluded)

</details>

**Comment by alexdevero** [comment]
Hmm. So, maybe reinstalling npm and node.js on my system could help?

**Comment by aeschli** [comment]
#77066 got fixed for September. So if npm is not present we fall back to the online info.
