### ISSUE TITLE
When hovering links in markdown, the cursor becomes a hand, not the regular text cursor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8125]
- VSCode Version: master
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open .md file with `[...]()` style link
2. Mouse over `...` portion

![cursor](https://cloud.githubusercontent.com/assets/2193314/16352437/2046cf66-3a23-11e6-9bdf-3df71451c181.jpg)

**Comment by Tyriar** [comment]
It's picking up title's style due to the title scope.

```
.monaco-workbench > .part.editor > .content.multiple-editors .one-editor-container .title,
.monaco-workbench > .part.editor > .content.multiple-editors .one-editor-container .title .title-label a,
.monaco-workbench > .part.editor > .content.multiple-editors .one-editor-container .title .title-label span {
    cursor: -webkit-grab;
}
```

/cc @bpasero

**Comment by Tyriar** [comment]
The short term solution is probably to remove the "title" scope as it seems incorrect, in the long term the title classes should be less generic so they don't mess with the grammar styles.

**Comment by bpasero** [comment]
I cannot reproduce this anymore.
