### ISSUE TITLE
Commands not being added in scm/SourceControl section with SCM API 

### ISSUE THREAD

**Issue by sbeland** [microsoft/vscode#81252]
- VSCode Version: 1.38.1566831676-insiders
- OS Version: MaxOS 10.14.6

Steps to Reproduce:

1. Using SCM API, add a command to package.json in scm/SourceControl section. I have used the other types of command menus and those do work.

Expected: Command is added to top level SCM menu
Actual: Command is not added. I also looked at the Git extension made with the SCM API, and they also add a command to scm/SourceControl but I do not see it appearing in the git extension either.

Does this issue occur when all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
It would be pretty useful to see your `package.json`.
