### ISSUE TITLE
Hex colors are inaccurate when having a alpha code added in prefix

### ISSUE THREAD

**Issue by akshaynexus** [microsoft/vscode#81251]
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1.Create a new CSS file,set color with alpha code,for example #4Db088ff 
2. Check preview of color

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Screenshot of the problem:
<img width="722" alt="Screen Shot 2019-09-21 at 3 01 28 AM" src="https://user-images.githubusercontent.com/25401217/65364771-79131700-dc1c-11e9-921f-93db41654929.png">

The above hex code is shown as green,whereas in reality it is purple in color

**Comment by ArturoDent** [comment]
Are you sure, see https://color-hex.org/color/4db088

**Comment by akshaynexus** [comment]
4Db088ff is the hex color,which would result in the color #b088ff with alpha.Here the alpha is as a prefix,which is 4D.

**Comment by ArturoDent** [comment]
The alphas aren't **prefixes** though.  The alpha values go at the **end**.  As you have written it the `ff` is the alpha value.  What you want is `#b088ff4d`.  That yields a sorta middle purple with a lot of opacity in vscode.

**Comment by kieferrm** [comment]
@akshaynexus we use the #RRGGBBAA format known from web browsers.
