### ISSUE TITLE
Typescript Language Mode missing

### ISSUE THREAD

**Issue by CoreyAR** [microsoft/vscode#81265]
Issue Type: <b>Bug</b>

Built in typescript support seems to be missing. I downloaded a fresh copy of Visual Study Code and then opened up a typescript project. The typescript files are recognized as Plain text files.

When I click the file type in the status bar and try to manually associate the `.ts` files with Typescript, Typescript is missing from the available language modes.

Typescript settings give an unknown configuration warning. Adding the file association manually in settings also doesn't seem to have resolved the issue.
```
"files.associations": {
        "*.ts": "typescript",
    },
```
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
env-vscode|Ber|0.1.1
gitlens|eam|10.0.0
prettier-vscode|esb|2.2.2
flow-for-vscode|flo|1.5.0
rainbow-csv|mec|1.3.1
dotenv|mik|1.0.1
python|ms-|2019.9.34911
vscode-typescript-tslint-plugin|ms-|1.2.2
code-spell-checker|str|1.7.18

</details>

**Comment by mjbvz** [comment]
In the extensions view, can you try searching for `@builtin typescript` and checking if the built-in `JavaScript and TypeScript language features` extension is disabled?
