### ISSUE TITLE
unable to write file

### ISSUE THREAD

**Issue by kingsaad98** [microsoft/vscode#81260]
i just can not save  my index.html , this error pops up : 
Failed to save 'index.html': Unable to write file (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'c:\Users\SAAD\Desktop\Complete Web dev course\Css - MySite\index.html')

**Comment by gjsjohnmurray** [comment]
Maybe another program on your PC has locked the file. Can you edit and save it with Notepad?
