### ISSUE TITLE
Changes v1.38 in to autoClosingBrackets vs Completion order is breaking intellisense

### ISSUE THREAD

**Issue by esbenk** [microsoft/vscode#81261]
- VSCode Version: 1.38
- OS Version: Windows 10 1903 Build 18362.356

In the [AL Language](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al) extension we offer both keyword intellisense and autoClosingBrackets for our block keywords. The AL Language is Pascal based e.g. blocks are surrounded with begin/end.

Our language configuration.json contains 

```
    "autoClosingPairs": [
        { "open": "begin", "close": "end;", "notIn": ["string", "comment"] }
    ],

```

At the same time we offer generic contextual keyword intellisense based on our syntax definition through a CompletionRequest.

Up until v1.38 this worked perfectly. The user started typing "begin" was presented with the begin keyword completion when selected the autoClosingPairs kicked in a inserted the closing pairs. 
Begining from v1.38 something has changed. When begin is typed fully out then closing "end;" is shown but when typing <enter> to split the begin/end; then the closing "end;" is deleted. 

Steps to Reproduce:

1.  Download and install the AL Language extension
2. Use the AL:Go! command from the command palette to get a skeleton project
3. After the Message() in the trigger start type begin followed by <enter>

Does this issue occur when all extensions are disabled?: No

**Comment by esbenk** [comment]
AL Language extension with VsCode v1.37

![before](https://user-images.githubusercontent.com/24257835/65371051-eeeca200-dc5f-11e9-9ae3-c4da290163e1.gif)

Same AL Language extension (same binary) installed on v1.38

![after](https://user-images.githubusercontent.com/24257835/65371052-eeeca200-dc5f-11e9-84ff-4b967027af2c.gif)

**Comment by octref** [comment]
@jrieken Looks like a snippet issue to me

**Comment by esbenk** [comment]
It is caused by a change in VsCode between v1.37 and v1.38 without any change to our extension.

**Comment by jrieken** [comment]
Yes - we did that on purpose because usually closing brackets insert something like `)` and when completions also insert that double brackets would appear. Unsure how to proceed with this...

**Comment by esbenk** [comment]
We have added an exception the generic keyword intellisense in our LanguageServer to create a Snippet for begin/end and not it works with 1.38+ versions.
