### ISSUE TITLE
Key combination "Cmd+Shift+E" does not register (Mac OSx 10.13.6)

### ISSUE THREAD

**Issue by christianbradley** [microsoft/vscode#81266]
- VSCode Version:
1.38.1
- OS Version:
MacOS High Sierra 10.13.6

Steps to Reproduce:

1. Open VS Code
2. Go to Preferences > Open Keyboard Shortcuts
3. In the "Type to search in keybindings" text box, click the keyboard icon to record key combinations
4. Press "Cmd+Shift+E"
5. Only "cmd+shift+" is shown (the "E" key is never registered)

Note that "cmd+shift+r" etc work, as well as  "alt+shift+e" etc

Tested with extensions disabled and latest insiders build.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
This means that VS Code does not receive the keybinding from the OS. Are you able to use this keybinding in other applications? Have you recently installed some software on your machine that would capture Cmd+Shift+E globally?

Unfortunately, this is not an issue with VS Code and there is nothing we can do on our side if we don't receive the keybinding...
