### ISSUE TITLE
Edit menu's position error in settings.json

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode#81267]
- VSCode Version: tested 1.35.1, 1.37, 1.38.1, probably also exists in earlier versions.
- OS Version: Win10 and VM Win7 and VM Debian 10.

Steps to Reproduce:

1. Open Settings.json
2. Click any edit menu which is **on the bottom of the screen**.
3. If you release your mouse, the entry will be selected immediately. Because the menu doesn't show up in the right place.

![图片](https://user-images.githubusercontent.com/24759802/65373772-6c420200-dcb4-11e9-8129-1531a5116e50.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@imba-tjd I cannot repro it. Are there any specific steps to follow?

**Comment by imba-tjd** [comment]
```
    "window.titleBarStyle": "custom",
    "workbench.settings.editor": "json",
    "workbench.settings.useSplitJSON": true,
```

These should be enough. What really matters is the first one.

**Comment by els2520** [comment]
On Sat, 21 Sep 2019 at 14:17, 谭九鼎 <notifications@github.com> wrote:

>
>    - VSCode Version: tested 1.37-1.38.1, probably also exist in earlier
>    versions.
>    - OS Version: Win10 and VM Win7.
>
> Steps to Reproduce:
>
>    1. Open Settings.json
>    2. Click any edit menu which is *on the bottom of the screen*.
>    3. If you release your mouse, the entry will be selected immediately.
>    Because the menu doesn't show up in the right place.
>
> [image: 图片]
>
> Does this issue occur when all extensions are disabled?: Yes
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
null

**Comment by sandy081** [comment]
I could reproduce this in windows. Even though we do not maintain the old settings editor, this looks to me a menu specific issue. Hence assigning to @sbatten
