### ISSUE TITLE
new version cannot execute

### ISSUE THREAD

**Issue by nobleson** [microsoft/vscode#81273]
Am working with windows 10 home and vs code just stop working, i uninstall and install it again and still the same problem, only the old version is working on my windows. please help.
![vs code](https://user-images.githubusercontent.com/14866971/65379507-0dcf5080-dcc1-11e9-90f3-ed6698c99125.PNG)

**Comment by kieferrm** [comment]
Not sure why this is happening in a user install.

**Comment by joaomoreno** [comment]
@nobleson Can you install the system setup instead? https://code.visualstudio.com/docs/?dv=win64
