### ISSUE TITLE
Editor actions in widgets stop working randomly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81272]
- Use vscode for awhile
- Open find widget, press enter to go to next match, or esc to close it
- Nothing happens when I press enter or esc
- Same in other widgets like the f2 "rename" box
- Reload window
- It works again

I've seen this a couple times in the past week and I debugged a bit.

It seems to go wrong at this line to pick which editor to send the command to: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/editorExtensions.ts#L156

After this, `editor` is the debug console repl input which is not focused or open although I used it a lot in this session.

Stepping into here: https://github.com/microsoft/vscode/blob/a817a588c72fe3d41ad0d1d8f3599742dc12267a/src/vs/editor/browser/services/abstractCodeEditorService.ts#L73

the repl editor claims to have widget focus. So I guess it got stuck in a state where widget focus is set to true but never reset to false. Can't figure out how to get it in or out of that state. I see this change which could be related: https://github.com/Microsoft/vscode/commit/a98ae682dca9588eacc633aaebf030ac528595c9

**Comment by alexandrudima** [comment]
Thanks for tracking this down! :heart:

I've logically reverted the change in a98ae68 and also removed an old workaround that we had for IE which was the root cause of #71553
