### ISSUE TITLE
Frequently restart of inside chrome

### ISSUE THREAD

**Issue by incredibleXM** [microsoft/vscode#81271]
Issue Type: <b>Bug</b>

It seems that my vscode frequently restart its inside chrome per 3~5 minutes while using which disturbs me a lot. Usually the interface will turn dark and have nothing left except the window itself, then it will reload the frame immediately. It happens both when I work locally and remotely.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.2.0-27-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: exp|
|OS|Linux x64 4.2.0-27-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 x 1200)|
|Memory (System)|62.80GB (0.27GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911
vscode-language-pack-zh-hans|MS-|1.38.4
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
vscode-icons|vsc|9.3.0

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
Can you please run <kbd>F1</kbd>`Toggle Developer Tools` and tell us what the dev tools console shows? Thanks!
