### ISSUE TITLE
Wrap content in variables and watch views

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/vscode#81275]
During debugging, my variable names are long and its content is long too. So Variables/Watch/CallStack/Breakpoints windows cannot show all contents.

Please support customized font setting for debugger windows. If possible, I want to use smaller font in these windows.

Another request: if the variable is a list and its content is long, current window just show "...". So can the windows "wrap" the text and show all the contents?

**Comment by isidorn** [comment]
For the debug font, dup of https://github.com/microsoft/vscode/issues/519 as we will not allow to customize the font of the debug views and everything else in the workbench to be untouched

As for wrapping the text in the variables view, that is a fair feature request. Thus renaming this issue and leaving it open as a feature request which we might consider in the future.
Thanks

**Comment by 9527KGG** [comment]
Thanks. The situation is different from VS IDE. In the IDE, the watch window is in the bottom. So you can always drag it bigger to see all contents. But in VS code, you cannot move the watch window to the bottom, so "wrap" feature is much more important.

**Comment by joe-gre** [comment]
I disagree with this being closed. As it stands now, if a watch expression is too long it is impossible to see the result of it. You can make the debug pane larger but there is a limit. Hovering over the expression doesn't tell you the value either. I make heavy use of watch expressions, so this is the biggest thing turning me away from debugging in VS code.

**Comment by kgflying** [comment]
Hi @joe-gre . I totally agree with you. I suggest you create another ticket for them  😊

**Comment by stefanpl** [comment]
@weinand in the [follow-up ticket](https://github.com/microsoft/vscode/issues/141665) you suggest moving the pane to the bottom. While this helps for a strings of a certain length, for anything longer than that, I'm still force to copy their value and paste that … anywhere.

Any chance of re-opening? I assume @joe-gre  and @kgfly at least (besides) might appreciate that ✌️ 

Thanks a lot for your consideration 🙏

**Comment by stefanpl** [comment]
😮 Oh wow, I just discovered that hovering the value actually works (by now?).

Nevermind my last comment … sorry and happy coding y'all 😊

**Comment by romanchyla** [comment]
please add your votes to https://github.com/microsoft/vscode/issues/177733 - if you would like this feature to be implemented
