### ISSUE TITLE
[Feature] Allow extension webviews to have proper tooltip in Explorer

### ISSUE THREAD

**Issue by cfehse** [microsoft/vscode#81286]
**Description**
It would be nice if extension webviews could have  a human readable tooltip in the explorer. Not something like "\webview-panel\webview...". I found nothing in the extension API to set the explorer tooltip. The webview-sample (https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample) shows this generic tooltip as well. 

- VSCode Version: 1.38.1
- OS Version: Windows 10 

![Webview-tooltip](https://user-images.githubusercontent.com/55053134/65387233-82e46980-dd45-11e9-9dd0-4163a4c0f5c4.gif)

**Comment by mjbvz** [comment]
@isidorn After reviewing the code, I think this may be a bug with the open editors view. We show the expected title if you hover over the webview's editor tab but show the resource path when you hover over the title in the `open editors` view:

![Sep-30-2019 10-47-14](https://user-images.githubusercontent.com/12821956/65902658-c7888a00-e36f-11e9-8b36-bda683ebd511.gif)

**Comment by isidorn** [comment]
I can look into this next milestone, we were always behaving like this thus not a regression. October.
open editors view is not aware of the type of the editor, thus the editor input description might be more precise than the open editors one. Not if we can improve this, though will give you more details next week.

**Comment by isidorn** [comment]
Thanks for filling this. 
Please try it out with Wednesday VSCode insiders and let me know if the issue is fixed for you.
I tried it out and now it works great for me.

**Comment by cfehse** [comment]
@isidorn 

Yes works like a charm with the insiders build. 

Thank you!
