### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by GaribBeetar** [microsoft/vscode#81289]
Executing this simple class: 

import javax.swing.*;
// Importing the package that contains all the Swing Components and Classes.
    
public class FrameExample {
    
    public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
    
    private static void createAndShowGUI() {
        //Create and set up the frame. 
        //The string passed as an argument will be displayed 
        //as the title.
    
        JFrame frame = new JFrame("[=] Hello World [=]");
    
        //Display the window.
        frame.setSize(400, 100);
        frame.setVisible(true);
    }  
}

The expected output shuould be:

![image](https://user-images.githubusercontent.com/44477240/65392002-7f48e680-dd35-11e9-8da8-02aedd667d20.png)

Produces no output, instead produces this error: 

command 'code-runner.run' not found

**Comment by kieferrm** [comment]
Please file this issue against the Java extension. Thank you!
