### ISSUE TITLE
Intellisense (type script) sorting not alphabetical

### ISSUE THREAD

**Issue by grassgit** [microsoft/vscode#81282]
Issue Type: <b>Feature Request</b>

Either the sorting or the selection of the available options is not working well. I expected sorting in the intellisense to be alphabetical. For some reason imports are sorted above matches that do not match the typed string. This I can understand but what is anoying about this behaviour is that when you start typing intellisense (what feels like randomly) selects the closest entry from the already imported list or the non-imported list. This happens even if alphabetically a beter match is available in the other list.
I have been working with intellisense long enough that I generally know the relative position of a function and key (up/down) to it, but because of the switching start position I either have to key through more lines or type more (both of which break the flow). 
The biggest issue with this is as follows
* you need to import something new
* so you start typing
* the selection is in the currently imported section so you have to go down to the non-imported matches
* you select the entry, it is inserted and auto imported (good)
* I want to use the same entry again
* Start typing and now it is in the non-imported section. So you have to go back up again.

I can understand the use for this but at least the option to go back to a simple alphabetical sort would be great.
Neither VS Code nor the (built-in) typescript plugin seem to have settings to control this behaviour.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
Can you please provide an example that shows this behavior
