### ISSUE TITLE
[npm] Package.json dependencies get filled in with old versions

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#81280]
Issue Type: <b>Bug</b>

When filling in a dependency in a package.json file, the version used can be very, very out of date. Hovers still use the latest version though.

The fix for #75274 (commit 9bc4699) replaced the old API used for this with one from npms.io, but that service apparently has indexing issues.

**Steps to reproduce:**
1. In a package.json file, add a dependency for '@typescript-eslint/eslint-plugin' and press tab.

**Expected result:**
`"@typescript-eslint/eslint-plugin": "2.3.0"`

**Actual result:**
`"@typescript-eslint/eslint-plugin": "1.13.0"` (published on: July 21)

**Notes:**
GET: https://registry.npmjs.com/-/v1/search?text=@typescript-eslint%2Feslint-plugin&size=1

GET: https://registry.npmjs.com/-/package/@typescript-eslint%2Feslint-plugin/dist-tags

This seems to be pretty common unfortunately.

| package | actual | expected |
| :-- | --: | --: |
| @types/node | `10.0.3` | `12.7.5` |
| eslint | `6.1.0` | `6.4.0` |
| typescript | `3.4.3` | `3.6.3` |

VS Code version: Code - Insiders 1.39.0-insider (8b6e0efc0a98639085fabeb5226a516785424796, 2019-09-19T03:15:21.720Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/65518154-1f447280-dee4-11e9-9526-294693709fd5.png)

**Comment by mattacosta** [comment]
Yes, the intellisense results/hover *should* have the most recent versions since they make a separate request to the NPM registry via `npm view --json <package>`. It's the one that gets autocompleted when you start typing a fresh new dependency that seems to use npms.io data.

So basically: `<enter>` `"` `@` `typescript` `<tab>` and let it fill in the rest of the name + version string.

<details><summary>Here is my result when visiting that url:</summary>
<pre>
[
    {
        "package": {
            "name": "typescript",
            "scope": "unscoped",
            "version": "3.4.3",
            "description": "TypeScript is a language for application scale JavaScript development",
            "keywords": [
                "TypeScript",
                "Microsoft",
                "compiler",
                "language",
                "javascript"
            ],
            "date": "2019-04-09T23:21:12.530Z",
            "links": {
                "npm": "https://www.npmjs.com/package/typescript",
                "homepage": "https://www.typescriptlang.org/",
                "repository": "https://github.com/Microsoft/TypeScript",
                "bugs": "https://github.com/Microsoft/TypeScript/issues"
            },
            "author": {
                "name": "Microsoft Corp."
            },
            "publisher": {
                "username": "typescript",
                "email": "typescript@microsoft.com"
            },
            "maintainers": [
                {
                    "username": "typescript",
                    "email": "typescript@microsoft.com"
                }
            ]
        },
        "score": {
            "final": 0.44991672429970486,
            "detail": {
                "quality": 0.29698267740127254,
                "popularity": 0.6975864411790185,
                "maintenance": 0.3333333333333333
            }
        },
        "searchScore": 1010.8733,
        "highlight": "<em>typescript</em>"
    },
    {
        "package": {
            "name": "@typescript-eslint/typescript-estree",
            "scope": "typescript-eslint",
            "version": "1.13.0",
            "description": "A parser that converts TypeScript source code into an ESTree compatible form",
            "keywords": [
                "ast",
                "estree",
                "ecmascript",
                "javascript",
                "typescript",
                "parser",
                "syntax"
            ],
            "date": "2019-07-21T17:03:27.502Z",
            "links": {
                "npm": "https://www.npmjs.com/package/%40typescript-eslint%2Ftypescript-estree",
                "homepage": "https://github.com/typescript-eslint/typescript-eslint#readme",
                "repository": "https://github.com/typescript-eslint/typescript-eslint",
                "bugs": "https://github.com/typescript-eslint/typescript-eslint/issues"
            },
            "publisher": {
                "username": "jameshenry",
                "email": "npm@jameshenry.email"
            },
            "maintainers": [
                {
                    "username": "jameshenry",
                    "email": "james@henry.sc"
                }
            ]
        },
        "score": {
            "final": 0.7935211582302197,
            "detail": {
                "quality": 0.835530206802869,
                "popularity": 0.5512435346582717,
                "maintenance": 0.9997910258827543
            }
        },
        "searchScore": 18.459545,
        "highlight": "@<em>typescript</em>-eslint/<em>typescript</em>-estree"
    }
]
</pre>
</details>

...and when visiting the site:
![npms](https://user-images.githubusercontent.com/1007463/65537971-2b680a00-debb-11e9-9fdf-ac586d9012b4.png)

...and after a bit of digging: https://github.com/npms-io/npms-analyzer/issues/244#issuecomment-528980226

**Comment by aeschli** [comment]
Wow, this morning I no longer get the versions I got yesterday. Now I get 3.4.3 again.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/65581252-70ec0c00-df7b-11e9-9fc7-9cc175885fd6.png)

**Comment by aeschli** [comment]
Sorry, my bad. For code completion on the version (after `:`), we use also use `npm view`
For code completion of the module name, which also inserts a version, we use npms-io.

I suggest we wait for npms-io to fix their issue. If they can't, we have to look out for a better rest service. The challenge is to find one targeted for code complete.

**Comment by aeschli** [comment]
Closing as 'upstream'. I will reopen if this isn't fixed by npms-io in the near future.
