### ISSUE TITLE
Git: "git not found" error, macOS, when xcodebuild license needs renewing

### ISSUE THREAD

**Issue by lukepighetti** [microsoft/vscode#81287]
It appears that on macOS if xcodebuild license needs renewing VSCode throws a "git not found" error.

<img width="493" alt="Screen Shot 2019-09-22 at 10 23 52 AM" src="https://user-images.githubusercontent.com/666539/65389372-88c95300-dd23-11e9-8b3a-6bb90adff791.png">

```
Lukes-iMac-2:skatex lukepighetti$ git

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
```

Aaaaand now it works

**Comment by joaomoreno** [comment]
Which macOS do you have installed?

We do have this old piece of code which was written for an older macOS version: https://github.com/microsoft/vscode/blob/03d6cc42ccaa7d42cd0f34a7f57816d3a54bdd34/extensions/git/src/git.ts#L91 maybe it should be updated to newer macOS versions.

**Comment by lukepighetti** [comment]
I'm on Mojave `10.14.6`

**Comment by lucasengel** [comment]
Just experienced the same issue here on 10.14.6.

1. `which git` points to `/usr/bin/git` which is already in my PATH
2. `git` is  recognized as a command from the terminal
3.  accepting Xcode agreement terms and waiting for the installation to finish gets the issue fixed

IMO it's a matter of adjusting the message. Many users won't even know they have to run Xcode if they don't use it often.

**Comment by Quendrique** [comment]
If I understood correctly, is it sufficient to alter the error message as @lucasengel mentioned? Or should the OSX version be detected and the XCode handler behave accordingly?

**Comment by joaomoreno** [comment]
We should catch that situation and warn the user accordingly and guide him to resolution.
