### ISSUE TITLE
Icon dont show in the taskbar

### ISSUE THREAD

**Issue by crydotsnake** [microsoft/vscode#81285]
- VSCode Version: 1.38.1
- OS Version: Windows 10 64 Bit

Since a few days now, i cant see the vscode icon in the taskbar i just have a white paper. Reinstalling is also not the solution.

**Comment by misolori** [comment]
@crydotsnake can you please provide a screenshot?

**Comment by crydotsnake** [comment]
@misolori I switched to Mac, But i reinstalled my Windows before and it was gone.

**Comment by misolori** [comment]
@crydotsnake so is this no longer an issue?

**Comment by crydotsnake** [comment]
Yes.
