### ISSUE TITLE
Commenting in C++

### ISSUE THREAD

**Issue by SatvikDandale** [microsoft/vscode#81288]
Issue Type: <b>Bug</b>

After using a scope resolution operator along with multiple inheritances in C++, VSCode fails to identify any comment which is written on the same line as that of the scope resolution operator.
Following is the code snippet:

`R r1;`
`r1.P::set(10);  //comment`
The //comment is not highlighted as a comment statement.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2982)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
prettier-vscode|esb|2.2.2
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
material-icon-theme|PKi|3.9.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Can't repro. Looks like it's caused by an extension.
