### ISSUE TITLE
Ctrl + Click  No Longer Opens A Link In Console

### ISSUE THREAD

**Issue by Fateslayer** [microsoft/vscode#81281]
Issue Type: <b>Bug</b>

php artisan serve or node app and then do Ctrl + Click on the links shown in the console window. I'm using bash console.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.95GB (1.42GB free)|
|Process Argv|D:\Development\Web Development\Projects\test|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|10.0.0
prettier-vscode|esb|2.2.2
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
php-cs-fixer|jun|0.1.123
vetur|oct|0.22.3
vscode-icons|vsc|9.4.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Tyriar** [comment]
What links?

**Comment by Fateslayer** [comment]
![Link](https://user-images.githubusercontent.com/14025553/65826820-ec65fa00-e2a8-11e9-9cda-5efe568586f4.png)
Take a look
