### ISSUE TITLE
Setting the options.env PATH for npm not working

### ISSUE THREAD

**Issue by brucebrit** [microsoft/vscode#81284]
Hi, i configure my tasks.json in order to run npm. 
But still, i got the error  " npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program...". Is it due to my configuration of tasks.json incorrect? or vscode bug?

Note: I have no intention to add the npm path via the windows' environment variable setting. That is why i do it here
**tasks.json**

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "start",
            "path": "file-lister-app/",
            "options":{
                "env": {"PATH":"D:/node-v12.10.0"}   <--where my npm is located
            }, 
            "problemMatcher": []
        }
    ]
}
```

**Comment by alexr00** [comment]
Example to test with on Windows:
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "echoPath",
			"options": {
				"env": {
					"PATH": "C:\\Program Files\\nodejs\\;D:/node-v12.10.0"
				}
			},
			"problemMatcher": []
		}
	]
}
```
And add the following script to package.json: `"echoPath": "echo %PATH%"`
