### ISSUE TITLE
Just opened it, that's it!!!

### ISSUE THREAD

**Issue by Lee981265** [microsoft/vscode#81296]
![null](https://img.hacpai.com/file/2019/09/image-d4da078d.png?imageView2/2/interlace/1/format/webp)

**Comment by byyxx128** [comment]
What's your problem?
Please edit and update your issue (with detailed steps to reproduce), or close it if you don't need it anymore.

**Comment by byyxx128** [comment]
Is it your first time to use VS Code? Or did you install lots of extensions?

**Comment by Lee981265** [comment]
The computer just turned on vscode and did not run other items. The memory CPU increased from 197M to 10w.

**Comment by Lee981265** [comment]
![image](https://user-images.githubusercontent.com/29849554/65474751-87c52c80-deaf-11e9-8077-05fa24ab07e1.png)
