### ISSUE TITLE
Get CompletionItemKind at position

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#8129]
I have a `DefinitionProvider`, and I was wondering is there a way to get the `CompletionItemKind` at a particular position?

So take this for example:

```php
Database::get();
```

When I <kbd>Ctrl+Click</kbd> on `Database` I would get the `Class` `CompletionItemKind`

**Comment by jrieken** [comment]
Not really sure what you mean? The `DefinitionProvider` is meant to aid users in navigating source code. Given a position, get the symbol, and return one or many locations where it is defined. Different commands and actions, like _go to definition_, _preview definition_ etc, use this _data provider_.

Is that you want to enrich the hover you see when doing `Ctrl+MouseOver` on a symbol? Generally all language features are also exposed as [commands](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands). Using `executeCommand` you can retrieve the same data the UI gets and use that to implement another data provider - like HoverProvider - tho there is no special gesture for `Ctrl+MouseOver` just the general hover provider.

**Comment by TheColorRed** [comment]
Basically what I want is when you <kbd>ctrl+click</kbd> for it to go to the correct definition. 

Sometimes there are classes with the same name as a method in another class. How does it know which one you actually want?

Currently our provider finds and returns the first one it finds. So you could either go to the class or to the method. When we add properties the same thing goes for here..

I haven't tried using a list of items yet. Will they resolve themselves to the proper item when you <kbd>ctrl+click</kbd>?

**Comment by jrieken** [comment]
To clarify, <kbd>ctrl+click</kbd> is just another gesture for the _Go to Definition_, so I assume you are implementing a `DefinitionProvider`. 

Generally, VS Code does support multiple definition of a symbol cos that actually happens - think of TypeScript interface/variables merge or C# open classes. So, the UI will show a list when multiple definitions for a symbol have been computed:

![screen shot 2016-06-27 at 15 41 03](https://cloud.githubusercontent.com/assets/1794099/16381614/a7d3e264-3c7d-11e6-9214-2d3d3b999371.png)


> Currently our provider finds and returns the first one it finds. 

You mean 'find' as in textual search? That would one way to do but to get a correct result you must run a really semantic analysis which knows these kind of things. What language is this for?

**Comment by TheColorRed** [comment]
The language is `PHP`, and what we do is build the AST using the language server, and then store it in a variable `workspaceTree`. When vscode asks the server for list of items, it searches the tree (this is what I mean by **find**).

Here is the provider I wrote that asks the server for the word it is looking for a definition:

```php
import {
    workspace, Range, Location, Uri,
    DefinitionProvider, TextDocument, Position, CancellationToken
} from 'vscode';
import { RequestType } from 'vscode-languageclient';
import Crane from '../crane';

export class PHPDefinitionProvider implements DefinitionProvider {

    public provideDefinition(document: TextDocument, position: Position, token: CancellationToken): Thenable<Location> {
        return workspace.saveAll(false).then(() => {
            return this.findDefinition(document, position, token);
        });
    }

    public findDefinition(document: TextDocument, position: Position, token: CancellationToken): Thenable<Location> {
        return new Promise((resolve, reject) => {

            let wordRange: Range = document.getWordRangeAtPosition(position);
            let word: string = document.getText(wordRange);

            var findDefinition: RequestType<{path:string,word:string}, {path:string,position:any}, any> = {method: 'findDefinition'};
            Crane.langClient.sendRequest(findDefinition, {
                path: document.uri.fsPath,
                word: word
            }).then(result => {
                var uri: Uri = Uri.parse('file://' + result.path);
                var location = new Location(uri, new Range(result.position.startLine - 1, result.position.startChar, result.position.endLine - 1, result.position.endChar));
                resolve(location);
            });
        });
    }
}
```

as you can see it gets the word using `document.getText(wordRange)`, my thought was that I could also send the `SymbolKind` to the server such as `SymbolKind.Class`, `SymbolKind.Method`, etc. this way I could search the tree for just methods, or just classes instead of searching the tree for everything.

**Comment by jrieken** [comment]
Ok - as said before you could use the [api commands](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) to get to the completion items at a position but someone has to compute that info? The [provider](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) that ships with VS Code isn't very smart but consults a static list of symbols. 

Generally, you need an AST and a symbol/type information. Generally it's like this `ast node` maps to `type` and `type` maps to `symbol`. The symbol knows where it is defined - either a ast location or some lib location (thing of a dll or so). 

Closing this as question since it out of scope for VS Code

**Comment by TheColorRed** [comment]
Okay, I see now! I probably want to execute `vscode.executeWorkspaceSymbolProvider`.

Thanks for the info!
