### ISSUE TITLE
Alt + Click on link in terminal

### ISSUE THREAD

**Issue by Akionka** [microsoft/vscode#81292]
Issue Type: <b>Bug</b>

Alt + Click on links like "/home/akionka/go/src/github.com/akionka/ono-chat-back/internal/app/model/user_test.go:13" doesn't open file. But in WebStorm it does.

VS Code version: Code - Insiders 1.39.0-insider (575062278d181c075ea8dce345ab3d20a127309c, 2019-09-20T06:15:55.999Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2402)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.75GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-custom-css|be5|3.0.7
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.0.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
dotenv|mik|1.0.1
Go|ms-|0.11.6
vscode-typescript-tslint-plugin|ms-|1.2.2
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.9
vscode-wakatime|Wak|2.2.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does ctrl+click work? Did you change the setting to use alt?

**Comment by Akionka** [comment]
> Does ctrl+click work? 

No
> Did you change the setting to use alt?

Yes
> "editor.multiCursorModifier": "ctrlCmd",

If set to default (alt), Ctrl + Click works
