### ISSUE TITLE
Faild to install or update extension 

### ISSUE THREAD

**Issue by m-shouman** [microsoft/vscode#81291]
Issue Type: <b>Bug</b>

After updating vs code to 1.38.1 I can't update any extinsion or install new one and I tried to downgrade vs code to lower version 1.31.1 but the issue still exists. Now I removed all extinsions and I can't install any one

Console log:
![Capture](https://user-images.githubusercontent.com/17672487/65455775-3d5c9500-de48-11e9-8215-9cbe234a1555.PNG)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details>Extensions: none

**Comment by DiHand79** [comment]
My add-on also stopped working. The return to the previous version of the add-on also does not help.
Here is a screenshot that they ask you to make in the description - maybe it will help someone.
![badPython_01](https://user-images.githubusercontent.com/31386937/65434613-c4e5dc00-de27-11e9-9e6f-205bd926537e.JPG)

Python 3.7.4

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by kieferrm** [comment]
@m-shouman Please run <kbd>F1</kbd>`Toggle Developer Tools`. What does the dev tools' console show?

**Comment by m-shouman** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!



> /needsMoreInfo

updated
