### ISSUE TITLE
when wrappingColumn not 0, this function is invalid

### ISSUE THREAD

**Issue by SiriusGuo** [Microsoft/vscode#813]
in settings.json
set editor.wrappingColumn -> 120,
word wrap cannot by window size.
but when the value is 0, it worked.

Test on OSX lastest version.
VSCODE version is 0.10.2.

![111111](https://cloud.githubusercontent.com/assets/6395714/11468843/6b285772-978d-11e5-8f7e-57dbc40b27be.jpg)
![22222](https://cloud.githubusercontent.com/assets/6395714/11468845/720d705e-978d-11e5-89ca-ced63a67f9ac.jpg)

**Comment by alexandrudima** [comment]
@SiriusGuo `editor.wrappingColumn`:
* `0` - means wrap at viewport width (changes as you resize editors)
* `-1` - means never wrap
* `120` - means wrap at 120th column

**Comment by SiriusGuo** [comment]
I know, but when value is 120, it is not worked just like pictures in this topic.

**Comment by alexandrudima** [comment]
@SiriusGuo 

Here I am using `editor.wrappingColumn = 120`. Please notice how the long line which consists of numbers for easy counting wrapps after the 120th character. Also look at the indicator in the bottom right that shows the (line;column)

![image](https://cloud.githubusercontent.com/assets/5047891/11496672/ced47e96-9813-11e5-8382-7137340f5190.png)
