### ISSUE TITLE
Markdown preview does not toggle as expected in tabs

### ISSUE THREAD

**Issue by tedhudek** [Microsoft/vscode#8130]
- VSCode Version: 1.3.0-insider (commit de66522, 2016-06-24)
- OS Version: Win10

Steps to Reproduce:
1. Use 'code-insiders .' to open a repo.
2. Click an md file to open it.  Type some text into the file.
3. Click another md file.  It opens in a new tab.
4. CTRL+SHIFT+V to preview the second file.
5. Three tabs are now open, two raw md and the one with a preview of the second md.
6. Now click tab 1.
7. Now click tab 3.
8. CTRL+SHIFT+V.

Expected: we go back to tab 2, because that is the raw md for the file previewed in tab 3.
Actual: we go back to tab 1, which is raw md for a completely different file.
@gregvanl this is the issue we discussed.

**Comment by bpasero** [comment]
It looks as if this action is simply going back 1 in history? That is not really what should happen if you want to go back to source.

**Comment by mrmlnc** [comment]
@bpasero, Yes, i see this problem after the last update. For example

#### Stable

![2016-06-26_18-20-11](https://cloud.githubusercontent.com/assets/7034281/16363167/ca620f9e-3bca-11e6-9fb0-bc904b8409fd.gif)

#### Insider

![2016-06-26_18-20-43](https://cloud.githubusercontent.com/assets/7034281/16363170/dcf69b8e-3bca-11e6-8e04-2d725da049c8.gif)

:

**Comment by kieferrm** [comment]
Yes, we go one back in history. There is no API for extensions at the moment to get access to the editor showing an html preview. Although this behavior is wrong in some cases, we at least support the switching back and forth between source and preview.

**Comment by bpasero** [comment]
@kieferrm going back to the source should just be a call to opening the editor with the path of the markdown file, no?

**Comment by kieferrm** [comment]
@bpasero When the command is executed, the command can not find out for which editor it has been called. The extension API returns all active text editors but the preview editor is not one of them.

**Comment by bpasero** [comment]
Oh ok, that is indeed a problem...

**Comment by mjbvz** [comment]
I believe this is the same problem as #16298. A fix was checked in and should be available in the next insiders build
