### ISSUE TITLE
Python: good import generate "Problems"

### ISSUE THREAD

**Issue by clem744** [microsoft/vscode#81305]
Issue Type: <b>Bug</b>

In the code problems index,
when you use a __init__.py and use something like `import my_setup.config` or any other file with a path like that, vscode detect it like an error.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics (8 x 2224)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|13.70GB (9.76GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911

</details>

**Comment by clem744** [comment]
![vscode](https://user-images.githubusercontent.com/44908545/65411296-cba32d80-ddec-11e9-92fa-d8fa7a2f36c1.png)

**Comment by kieferrm** [comment]
Please file this issue against the python extension. Thank you!
