### ISSUE TITLE
Crash when search not response

### ISSUE THREAD

**Issue by tranvannhat** [microsoft/vscode#81301]
Issue Type: <b>Bug</b>

Always crash when search :/
https://prntscr.com/p9mx4c

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|22, 7, 4|
|Memory (System)|16.00GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
bemhelper|Box|0.7.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|1.9.1
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|2.4.3
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.13.0
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|2.2.2
vue-snippets|hol|0.1.11
react-native-snippet|jun|0.5.4
vscode-autoprefixer|mrm|2.2.0
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.6.2
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-react-native|msj|0.11.1
color-highlight|nau|2.3.0
vetur|oct|0.22.3
nginx-formatter|ray|0.0.4
typescript-hero|rbb|3.0.0
vue-vscode-snippets|sdr|1.8.0
vscode-nginx|sha|0.6.0
vscode-scss-formatter|sib|1.4.2
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|9.4.0
full-react-snippets|wal|1.3.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by kieferrm** [comment]
Do you search across files or inside the editor? Does it happen when all extensions are disabled?

**Comment by tranvannhat** [comment]
> Do you search across files or inside the editor? Does it happen when all extensions are disabled?

thanks for reply, i turn off all extension and error too, i code nuxtjs and search all project

**Comment by roblourens** [comment]
- Does it happen no matter what you search for?
- When this happens, is there some process using high CPU? Which one?
- Is your project very large, or are you matching results on very long lines?

**Comment by tranvannhat** [comment]
> * Does it happen no matter what you search for?
> * When this happens, is there some process using high CPU? Which one?
> * Is your project very large, or are you matching results on very long lines?

The file is too long and vscode crash

**Comment by roblourens** [comment]
Please explain some more
