### ISSUE TITLE
Emmet not working in Portable Mode

### ISSUE THREAD

**Issue by user474** [microsoft/vscode#81302]
This is my first ever bug report.
I noticed that Emmet doesn't work with VSCode v1.38.1.0 in Portable Mode.

If you start VSCode, Emmet will either work once and then stop working, or it will not work at all.

Changing settings that might be related to auto-suggest and Emmet doesn't make any difference. Pressing [Ctrl+Space] shows "Loading..." in the suggestion menu and it doesn't load any suggestions.

The issue happens even with all extensions disabled.

Portable Mode is setup as described on VSCode [site](https://code.visualstudio.com/docs/editor/portable).
Auto Suggest is ON (also doesn't work with OFF).

Haven't tried the Insider version.

Windows 10 (1809)

**Comment by octref** [comment]
It's working for me though:

![image](https://user-images.githubusercontent.com/4033249/65554164-99252d80-dedd-11e9-9583-33b343ecb50b.png)

Any error in Help -> Toggle Developer Tools? Also does normal installation work for you?

**Comment by user474** [comment]
Please see video inside the zip file. The error messages from Developer Tools are in the text file.
[Emmet not working.zip](https://github.com/microsoft/vscode/files/3650699/Emmet.not.working.zip)
[Errors.txt](https://github.com/microsoft/vscode/files/3650702/Errors.txt)

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/65628036-7c443500-df85-11e9-99f3-a41bd5d42d9c.png)

You have HTML files marked as PHP it seems? If you disable all settings emmet should work for you. You probably had `files.associations` that set HTML as PHP and that extension fails.

**Comment by user474** [comment]
The PHP buttons are for these two extensions: frogthefrog.php-project and brapifra.phpserver.
These buttons are always there regardless of what file is being edited.

I tried disabling all extensions and Emmet still doesn't work for some reason.

Is there anything useful in the error messages I included?

Why does it keep saying "Activating Extensions..." every time I press Tab? It seems like it is failing to load an extension.

I have the same extension installed in both standard installation and in portable mode as well as the same settings on both. Emmet works fine on the installed version but not in the portable version.

**Comment by octref** [comment]
> Why does it keep saying "Activating Extensions..." every time I press Tab?

Any info in Help -> Toggle Developer Tools?

**Comment by user474** [comment]
No info there other than what I attached in the Errors.txt file. That's all the messages that were there.

**Comment by octref** [comment]
@joaomoreno @sandy081 
I'm out of clue, do you have any diagnosis for this symptom? Seems to be portable mode stuck loading extensions.

> Why does it keep saying "Activating Extensions..." every time I press Tab?

**Comment by sandy081** [comment]
Can you please set the log level to `trace` using command `F1 > Set Log Level` and repro this and provide us with `window` and `extension host` logs which are available using command `F1 > Open View > Log (Window)` and ``F1 > Open View > Log (Extension Host)`.

@alexandrudima Any other ways to know what extension is getting activated?

**Comment by alexandrudima** [comment]
@sandy081 The extension host logs shows which extensions are getting loaded/activated, but we only record the fact that we call `activate()`, we don't record if/when `activate()` resolves the returned promise...

---

> Why does it keep saying "Activating Extensions..." every time I press Tab?


The reason is an extension that returns a Promise from its `activate()` function and then forgets to complete the promise.

**Comment by user474** [comment]
So a third-party extension is causing the issue. Is that correct?
At the moment it is working fine, I don't know how or what happened. Everything seems to be the same. 
I'm trying to get it to reproduce the issue so I can get the log files as requested by @sandy081.

**Comment by user474** [comment]
OK, the same error happened today out of nowhere so I recorded it and save the log files (trace level).
It was working fine an hour ago; I closed it and now when I run VSCode, Emmet is not working and it shows "Activating Extensions..." every time I press tab. Ctrl+Space doesn't show any suggestions.

Process Explorer shows several suspended VSCode processes.

Please see attached.
Thank you!

[Extension Host.txt](https://github.com/microsoft/vscode/files/3700270/Extension.Host.txt)
[Window Log.txt](https://github.com/microsoft/vscode/files/3700271/Window.Log.txt)
[Screen Recording.zip](https://github.com/microsoft/vscode/files/3700273/Screen.Recording.zip)
[Process Explorer.zip](https://github.com/microsoft/vscode/files/3700296/Process.Explorer.zip)

**Comment by user474** [comment]
After closing VSCode, the suspended processes didn't terminate. Screenshots attached.
I suspect they have something to do with this issue. If I restart the PC then it starts working again.

![1](https://user-images.githubusercontent.com/55680783/66361377-52016700-e9ca-11e9-9003-d0ee7c42154e.png)
![2](https://user-images.githubusercontent.com/55680783/66361378-5299fd80-e9ca-11e9-9e1b-fac39e6895d5.png)
![3](https://user-images.githubusercontent.com/55680783/66361379-53329400-e9ca-11e9-868b-5cd3bd4edb10.png)
![4](https://user-images.githubusercontent.com/55680783/66361380-53329400-e9ca-11e9-9e64-0da47eec3f97.png)
![5](https://user-images.githubusercontent.com/55680783/66361381-53cb2a80-e9ca-11e9-9d50-e2c051c6dc06.png)

**Comment by alexandrudima** [comment]
The logs don't actually show any errors... From the extension host logs, it appears the following extensions have been loaded:
* `vscode.emmet`
* `vscode.html-language-features`
* `ecmel.vscode-html-css`
* `vscode.debug-auto-launch`
* `vscode.git`
* `vscode.merge-conflict`
* `christian-kohler.path-intellisense`
* `dbaeumer.vscode-eslint`
* `formulahendry.auto-close-tag`
* `formulahendry.auto-rename-tag`
* `HookyQR.beautify`
* `mblode.pretty-formatter`
* `mcright.auto-save`
* `michelemelluso.code-beautifier`
* `mtxr.sqltools`
* `PKief.material-icon-theme`
* `pranaygp.vscode-css-peek`
* `ritwickdey.LiveServer`
* `streetsidesoftware.code-spell-checker`
* `vscode-icons-team.vscode-icons`
* `Zignd.html-css-class-completion`

From the screen recording, it looks like the HTML language service or the extension host are not healthy... 

From the process explorer, the "Suspended" next to the process looks very weird, those processes do not look healthy...

I am not sure how to troubleshoot this further...
