### ISSUE TITLE
Toggling Explorer on should focus to the file on the explorer not the code editor.

### ISSUE THREAD

**Issue by dejavu1987** [microsoft/vscode#81311]
- August 2019 (version 1.38)
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. From code editor press CMD + B to open explorer
2. Use up / down arrow key.

Does this issue occur when all extensions are disabled?: Yes

Expected behaviour:
The focus should be on Explorer and specifically currently open file. so that you can navigate along the files in the explorer.

**Comment by isidorn** [comment]
Disagree. Cmd + B is a lightwieght experience and it was designed like this so you can continue coding without the focus being stolen.
Please use Cmd + Shift + E instaed which was designed to pass faocus.

**Comment by dejavu1987** [comment]
Thanks for the comment @isidorn, because of the fact that the behaviour was otherwise till 1.37, I was used to it as I would very likely want my focus changed to explorer when I am toggling the explorer on, I keep it off while I am writing code to have more room. Anyways if that's how it was supposed to be then I am fine.
