### ISSUE TITLE
SCM: Placeholder text has overflow and is hidden 

### ISSUE THREAD

**Issue by Aryojaam** [microsoft/vscode#81316]
- VSCode Version:1.38.1
- OS Version: Ubuntu Disco Dingo 19.04

Steps to Reproduce:

1. open vscode 
2. go to SCM extension

Does this issue occur when all extensions are disabled?: Yes

The placeholder text in the SCM extention tab (`Message (Ctrl + Enter to commit on <Branchname>)`) is hidden when the width of the bar is not big enough
![Screenshot from 2019-09-23 13-26-37](https://user-images.githubusercontent.com/40788573/65422440-c9e66380-de06-11e9-99ec-e1130c481700.png)

**Comment by joaomoreno** [comment]
This is fixed in `master`.
