### ISSUE TITLE
CompletionItemKind/SymbolKind starts at 1 in languageserver but 0 in vscode

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#8131]
Is there a reason that `CompletionItemKind` starts at `1` in the `vscode-languageserver` and in the `vscode` library it starts at `0`?

```js
export declare enum CompletionItemKind {
    Text = 1,
    Method = 2,
    Function = 3,
    Constructor = 4,
    Field = 5,
    Variable = 6,
    Class = 7,
    Interface = 8,
    Module = 9,
    Property = 10,
    Unit = 11,
    Value = 12,
    Enum = 13,
    Keyword = 14,
    Snippet = 15,
    Color = 16,
    File = 17,
    Reference = 18,
}
```

**Comment by dbaeumer** [comment]
@TheColorRed the language server protocol is supposed to be implemented in language different than JS/TS as well. To not cause any confusion with 0 in the protocol and may be falsy values all enums in the protocol start with 1. New enums (for example TextEditorCursorStyle) in the APi start with one as well. The reason CompletionItemKind starts with 0 is backwards compatibility.
