### ISSUE TITLE
[Feature] Visual Studio Online - running in a browser add build for Plattform server

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81310]
there is a project called cdr/code-server that already implaments that i think we should implament that directly

## Progress Tracking:
- Build web - https://github.com/microsoft/vscode/issues/74393
- Add vscode-web-server - https://github.com/microsoft/vscode/issues/81474
-  Custom Gallery Url Not Merged at present but needs! PR: #81240

## Fix issues with web
- Url Bugs when vscode-web gets served by the server.
- mouse events fix firefox - https://github.com/microsoft/vscode/issues/81472

## Related issues:
- https://github.com/microsoft/vscode/issues/8721
- https://github.com/microsoft/vscode/issues/24320
- https://github.com/microsoft/vscode/issues/63408

we can archive that via the following steps

there are some files that get patched to load existing resources:

- https://github.com/cdr/code-server/blob/master/scripts/vscode.patch 

There are some extra files that get imported for the build 
- https://github.com/cdr/code-server/tree/master/src

The server build gets packaged with node binary it self at present the code-server project is using a own packager called nbin it works and there are other solutions but the nbin one is working well and LGTM

# Issue List
- Create a better way to archive that without patching
  - add https://github.com/microsoft/vscode/tree/master/src/vs/platform /server
- Add missing code from that repo to the main repo 
- add documentation.
- Create Release build chain

# Issues (Patch)
- The Url needs to get Corrected and other Path variables
- Language Pack Loading
- modifyed build from /build/gulpfile.vscode.js => /build/gulpfile.vscode.server.js /build/gulpfile.vscode.electron.js?
- /src/vs/base/common/network.ts
```patch
@@ -82,13 +82,11 @@ class RemoteAuthoritiesImpl {
 	}
 
 	public rewrite(authority: string, path: string): URI {
-		const host = this._hosts[authority];
-		const port = this._ports[authority];
 		const connectionToken = this._connectionTokens[authority];
 		return URI.from({
 			scheme: platform.isWeb ? this._preferredWebSchema : Schemas.vscodeRemoteResource,
-			authority: `${host}:${port}`,
-			path: `/vscode-remote-resource`,
+			authority: window.location.host,
+			path: `${window.location.pathname.replace(/\/+$/, '')}/vscode-remote-resource`,
 			query: `path=${encodeURIComponent(path)}&tkn=${encodeURIComponent(connectionToken)}`
 		});
 	}
```
- Remove Custom Marketplace https://github.com/cdr/code-server/blob/master/src/marketplace.ts

**Comment by frank-dspeed** [comment]
Current iteration in parallel https://github.com/microsoft/vscode/issues/74393

**Comment by chrisdias** [comment]
i think this is now covered by the server and remote tunnels https://code.visualstudio.com/docs/remote/tunnels
