### ISSUE TITLE
Extension development: Add debug-hover-like data navigation to regular hovers

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#81313]
My extension (Calva, a Clojure extension) connects the editor view with the REPL running ”inside” the application under development. It blurs the borders between debugging and coding. In particular, you do not need to be in debug mode to query the value of some variable.

In Calva you can evaluate a form and see the result inline in the editor. I am right now adding a hover so that you can examine the results a bit closer. It looks like so:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/30010/65420127-acae9680-de00-11e9-934e-1650a51c448e.png">

For large data structures, this gets not so nice, though. It would be much better to present it like data is presented in debug hovers, where the user can navigate the data vi unfolding the pieces of interest.

**Comment by octref** [comment]
What you saw was likely a bug. Can you provide a minimal repro case by forking https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample?

Also I'm not sure what you meant by "where the user can navigate the data vi unfolding the pieces of interest".

**Comment by PEZ** [comment]
@octref: My issue is probably too unclear. It is not a bug report, it is a feature request on the API.

> Also I'm not sure what you meant by "where the user can navigate the data vi unfolding the pieces of interest".

When hovering over a variable in debug mode, and the value is some data structure, you get a tree view navigator UI. That is what I want to be able to create in non-debug hovers.

**Comment by octref** [comment]
You'll need to get @jrieken interested, but my guess is this won't fit current API. We support MD in hover/completion/parameter-hints and so far there's no plan to add any interactivity over there.

**Comment by PEZ** [comment]
@jrieken: Pretty please? ❤️ What can I add to the request to make its case better?

There is also #3220, even if that is much more general.

**Comment by PEZ** [comment]
@jrieken: Pretty please? ❤️ 

There is also https://github.com/microsoft/vscode/issues/3220

**Comment by octref** [comment]
I doubt he'd be interested in doing this over doing #3220, which is more generic and covers this case.

**Comment by jrieken** [comment]
Tbh this has no real chance of happening as our UX extensibility story is topic focused and rarely a general purpose story

**Comment by octref** [comment]
Now you are limited to MD. Track #3220 for more possibilities in the future.
