### ISSUE TITLE
Wrapped task output if Terminal not opened

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#81328]
- VSCode Version: 1.38.1
- OS Version: Windows 10, 1709

Steps to Reproduce:

1. Add a task with a problem matcher:
````
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "PMD workspace src",
            "type": "shell",
            "command": "C:\\pmd\\pmd-bin-6.18.0\\bin\\pmd.bat",
            "args": [
                {
                    "value": "-d ${workspaceFolder}\\src",
                    "quoting": "escape"
                },
                {
                    "value": "-R C:\\pmd\\CDS_pmd_ruleset_jee-1.0.xml",
                    "quoting": "escape"
                },
                {
                    "value": "-f csv",
                    "quoting": "escape"
                }
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": false,
                "reveal": "never",
                "revealProblems": "onProblem",
                "focus": false,
                "showReuseMessage": false,
                "clear": true
            },
            "problemMatcher": {
                "owner": "java",
                "fileLocation": ["absolute"],
                "pattern": {
                    "regexp": "^\"([0-9]+)\",\"(.*?)\",\"(.*?)\",\"([0-9]+)\",\"([0-9]+)\",\"(.*?)\",\"(.*?)\",\"(.*?)\"",
                    "file": 3,
                    "line": 5,
                    "severity": 4,
                    "message": 6
                }
            }
        }
    ]
}
````
2. Ensure the Terminal is Killed. (i.e. click the trash bin on the terminal, not the 'x')
3. Run the task
4. Output in is wrapped, breaking the pattern matcher, thus no problems are shown from this task
![image](https://user-images.githubusercontent.com/281700/65449818-a554b080-de33-11e9-8baf-573bfe1ffdb4.png)

This issue does not occur when the task is run while the Terminal is already open
![image](https://user-images.githubusercontent.com/281700/65450171-6b37de80-de34-11e9-8b29-019f8f60bcaf.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is a known limitation and unfortunately I don't see any way to workaround it, the terminal will not know the panel's size until the terminal panel has been displayed, so it defaults to 80x24. This is a particularly bad problem on Windows because reflow of lines is done by the pty, not by the terminal emulator (unlike on Linux and macOS).

Here's an upstream issue that would fix the problem https://github.com/microsoft/terminal/issues/405

**Comment by wolf99** [comment]
So... is pattern matching irrevocably broken? Or is there some workaround implied?

I don't think it's possible to tell the regex to expect a newline anywhere within the pattern is it?

**Comment by Tyriar** [comment]
The workaround is to open the terminal one time before running your task.

On Windows wrapping is "owned" by the backend conpty and will sometimes reflow the page, whereas on Linux and macOS it's owned by VS Code. You should direct your comments to https://github.com/microsoft/terminal/issues/405 as I would love this to get fixed as well.
