### ISSUE TITLE
Ability to disable rendering and code colorizing of suggestion text

### ISSUE THREAD

**Issue by larhun** [microsoft/vscode#81327]
Comments in go code are written for the godoc renderer and may look wrong when rendered as quick suggestions by VSC. I would suggest to add a new `quickSuggestionsFormat` boolean setting for disabling any rendering and code colorizing of suggestion text.

As an example, the suggestion texts for the following fragment of Go code:

![image](https://user-images.githubusercontent.com/33022639/65447911-e51d9700-de37-11e9-9d96-449a9314d1c2.png)

1) shows a bad title style rendering

![image](https://user-images.githubusercontent.com/33022639/65448083-48a7c480-de38-11e9-8b16-756f751b8ecd.png)

2) colorizes the `mul` function name including the left parenthesis 

![image](https://user-images.githubusercontent.com/33022639/65448237-a3412080-de38-11e9-93e1-c1df2476828b.png)

3) does not colorize the `quo` function name 

![image](https://user-images.githubusercontent.com/33022639/65448394-f6b36e80-de38-11e9-9ae4-d3a9d6e22b8c.png)

**Comment by octref** [comment]
You should open an issue for the go extension you are using. By default, hover uses Markdown, so `# of items` is interpreted as `<h1>of items</h1>`. It's possible to avoid this by using `MarkupString.appendText` instead of `new MarkupString()`.

**Comment by octref** [comment]
As for `quickSuggestionsFormat` we won't add it.
