### ISSUE TITLE
Change Explorer Open In New Command Prompt Context Menu to use Integrated Terminal

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#8132]
- VSCode Version: 1.2+
- OS Version: ALL

I would like this to launch the integrated experience to aid in discover-ability.

Steps to Reproduce:
1. Right click on a file
2. Should open in integrated terminal with the right folder context

**Comment by bpasero** [comment]
I would rather suggest to have a setting that controls this for all our terminal commands 👍

**Comment by Tyriar** [comment]
Opening up to PRs, here's what we need:

- A new setting that defines whether the "Open in terminal/command prompt" context menu in the explorer uses the external terminal (current) or integrated terminal
- Support for launching a integrated terminals when it's selected. This involves hooking it up with `TerminalService.createInstance` in https://github.com/Microsoft/vscode/blob/ed91b067e075457791e5e523d25e110c57650a4b/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L52
