### ISSUE TITLE
CompletionItem type definition - range should be nullable

### ISSUE THREAD

**Issue by FreHu** [microsoft/vscode#81326]
I originally mistakenly tracked this to the monarch repo, who pointed me to the correct location: 
https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L455

I think that the range is incorrectly labeled as required. A sensible default is specified in the docstring:
`Defaults to a range from the start of the [current word](#TextDocument.getWordRangeAtPosition) to the current position.`

It is not included in the usage example:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

But when used with typescript definitions, this results in the type error `Property 'range' is missing in type '{ label: string; kind: CompletionItemKind.Function; documentation: string; insertText: string; }' but required in type 'CompletionItem'.`

**Comment by jrieken** [comment]
That's the internal API and we made it required there so that it's safe to be used (internally). The public extension API used the default
