### ISSUE TITLE
"Source" in an error popup can be hidden by buttons

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#81329]
Issue Type: <b>Bug</b>

This error message comes from C# (I know because I clicked the gears icon and then "Manage Extension", otherwise I wouldn't know because the source is hidden by the buttons.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/6913354/65450285-a1a03a00-ddf1-11e9-8be2-c534a5b35b56.png">

VS Code version: Code - Insiders 1.39.0-insider (8b6e0efc0a98639085fabeb5226a516785424796, 2019-09-19T03:13:53.711Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|-psn_0_86037|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
todo-tree|Gru|0.0.153
vscode-antlr4|mik|2.1.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
azure-account|ms-|0.8.4
csharp|ms-|1.21.3
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.6.0
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by bpasero** [comment]
You can still hover over the source and get the full source in the title.
