### ISSUE TITLE
Improve Outline Navigation

### ISSUE THREAD

**Issue by generalbretch** [microsoft/vscode#81323]
When navigating to a function in an open file, I click its name in the outline which works great. The problem is, if I then scroll away from that function and want to go back to it, clicking the function name again does nothing because it's already highlighted.

It would be great if I could just click it again to go back to where I was before

**Comment by themelz** [comment]
This would be solved by my suggestion #81796:

When the current editing line in the source editor changes, by clicking in a new line, by doing a find, etc., the highlighted function should change accordingly.
