### ISSUE TITLE
External terminal not registering Ctrl+C with .NET Core

### ISSUE THREAD

**Issue by guardrex** [microsoft/vscode#81322]
- VSCode Version: 1.38.1
- OS Version: Win10 (10.0.17763)

The following used to work in .NET Core 2.2 app with a debug profile for the `externalTerminal` in earlier versions of VSC (or OmniSharp if that's where the problem actually lies here), but it doesn't work with new 3.0 framework bits and the latest public VSC.

Debug a .NET Core app in the `externalTerminal` using either the `Microsoft.NET.Sdk.Web` or `Microsoft.NET.Sdk.Worker` project SDK that calls [UseConsoleLifetime](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.hostinghostbuilderextensions.useconsolelifetime) on the host builder so that the app should listen for `Ctrl+C` to stop the app. The app doesn't stop.

Steps to Reproduce:

1. Create a .NET Core console app with [UseConsoleLifetime](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.hostinghostbuilderextensions.useconsolelifetime) ...

   ```csharp
   public class Program
   {
       public static async Task Main(string[] args)
       {
           using (var host = Host.CreateDefaultBuilder(args)
               .UseConsoleLifetime()
               .Build())
           {
               // Start the host
               await host.StartAsync();
   
               // Wait for the host to shutdown
               await host.WaitForShutdownAsync();
           }
       }
   }
   ```

   The preceding code works if the app is run with `dotnet run` in a command shell ...

   <img width="503" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65440864-027a4300-ddef-11e9-8b9a-c9a1d8033818.PNG">

2. Use a console debugger profile and run the same app in the `externalTerminal` ...

   ```json
   {
      "version": "0.2.0",
      "configurations": [
          {
              "name": ".NET Core Launch (console)",
              "type": "coreclr",
              "request": "launch",
              "preLaunchTask": "build",
              "program": "${workspaceFolder}/bin/Debug/netcoreapp3.0/ConsoleSample.dll",
              "args": [],
              "cwd": "${workspaceFolder}",
              "stopAtEntry": false,
              "console": "externalTerminal"
          }
       ]
   }
   ```

   The app will not respond to `Ctrl+C`. In prior versions (.NET Core 2.2), `Ctrl+C` would work when using the `externalTerminal` in this scenario.

I asked ASP.NET Core engineering, and they thought it might be on the VSC-side of the equation given that `Ctrl+C` works when the app is run in a command shell. See item response **4** at https://github.com/aspnet/AspNetCore.Docs/issues/12841#issuecomment-533206352.

I put up a repro project at https://github.com/guardrex/ConsoleSample.

The sample app that I put up also has a keystroke-monitoring service that logs presses of the `w` key. That code works. Running in the `externalTerminal`, the app reports that it hears the `w` key clicks, while the app doesn't respond to `Ctrl+C`. Sure, the app could listen for `Ctrl+C` there and shut the app down, but that's not the point ... that would be a hack. `UseConsoleLifetime` should work the way that this app works in a normal command shell (*I think* :smile:).

**Does this issue occur when all extensions are disabled?** That can't be checked because the configured debug type is `coreclr`, which isn't supported without either (or both) C# OmniSharp. In fact, I'm not sure if this bug report should be filed here or over on https://github.com/OmniSharp/omnisharp-vscode.

**Comment by Tyriar** [comment]
Looks close to https://github.com/microsoft/vscode/issues/25195, can you check what your `terminal.external.windowsExec` setting is set to?

**Comment by guardrex** [comment]
Sure ... how do I check that value?

**Comment by guardrex** [comment]
Found it ....

<img width="286" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65450426-b1744a00-de02-11e9-8077-6f85684735ed.PNG">

**Comment by Tyriar** [comment]
@guardrex if it's sysnative that indicates to be that you're running the 32-bit version of VS Code on a 64-bit OS, is that correct?

**Comment by guardrex** [comment]
64-bit OS, yes.

<img width="361" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65451420-c05bfc00-de04-11e9-8b98-d8d653799f58.PNG">

WRT VSC ... How can I tell? ...... I don't recall what I installed, but I imagine that I installed the 64-bit version of VSC.

**Comment by Tyriar** [comment]
@guardrex `code --version` should tell you, if you're on the 64-bit version you should definitely be using System32 not sysnative.

**Comment by guardrex** [comment]
<img width="113" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65452079-13827e80-de06-11e9-87c2-45b3a67e0db3.PNG">

**Comment by guardrex** [comment]
> Does the 64-bit version work?

So .... I should get 64-bit and test. Stand-by ... I'll do that now and let you know what happens.

**Comment by guardrex** [comment]
I suppose that I can install these SxS. 🤞 ...... I'm working ..... on our docs :smile: ... I hope I don't :boom: anything. Should I do this on my laptop, or will SxS be ok?

**Comment by Tyriar** [comment]
@guardrex you can download the zip, close all your current windows and then open the zip executable. If you try running the 64-bit version while the other is running it will probably just open another 32-bit window.

**Comment by guardrex** [comment]
kk .... ran the `ConsoleSample` app with 64-bit VSC ... same behavior. After a few `w` key presses that it heard, I hit `Ctrl+C` ... nothing ... app still running. Only clicking the debugger stop button kills the app.

<img width="515" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65453283-82f96d80-de08-11e9-8498-94315efdcdd7.PNG">

**Comment by Tyriar** [comment]
Does the same thing happen when you launch the external terminal using ctrl+shift+c? Also can you open an integrated cmd.exe terminal and run `echo %COMSPEC%` and paste in the output?

**Comment by guardrex** [comment]
Opening with Ctrl+Shft+C and running the app with `dotnet run` it works ...

<img width="336" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65643937-86335b80-dfb8-11e9-931f-b66b2f871447.PNG">

`echo %COMSPEC%` ...

<img width="424" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/65644077-e5916b80-dfb8-11e9-96d3-35fc9777aa6b.PNG">

**Comment by guardrex** [comment]
btw - It does work in that terminal ...

<img width="476" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/65644163-2b4e3400-dfb9-11e9-82c3-e1658fb4c9df.PNG">

**Comment by guardrex** [comment]
... and thus if I change the profile to ...

```json
"console": "integratedTerminal"
```

it works.

It's when I have it set to ...

```json
"console": "externalTerminal"
```

... that console window that's spawned. That's where Ctrl+C doesn't work to shut the app down.

**Comment by Tyriar** [comment]
@weinand might be an issue with what the debugger is launching, I'm not sure if this is debug or an extension.

**Comment by databasedav** [comment]
For the Python extension this breaks after version 1.46 (specifically `code_1.46.1-1592428892_amd64.deb`). It especially sucks because Pylance was introduced in 1.47 (or maybe 1.48) so I end up flip flopping when I need to ctrl+c out of debugging servers :(

**Comment by weinand** [comment]
The external terminal is typically launched by VS Code. 
And the terminal's executable for Windows is configured via the `terminal.external.windowsExec` setting.
The default is this:
```
"terminal.external.windowsExec": "C:\\Windows\\System32\\cmd.exe"
```

There where no code changes in that area around VS Code 1.46.

**Comment by databasedav** [comment]
sorry this is on Ubuntu 20.04. I commented here because it was the only issue I found with pretty much the exact same issue where ctrl+c doesn't send a SIGINT into the program being debugged and pressing the stop button just closes the terminal and the programs SIGINT handler isn't hit.

I'll post a repro soon.

**Comment by connor4312** [comment]
I can repro this, but have no idea why it is happening. Simple program:

```
process.on('SIGINT', () => {
  console.log('got SIGINT');
  process.exit(0);
})

setInterval(() => {}, 1000)
```

Running the same command that VS Code is running from a cmd.exe instance manually, it works fine. But in an external terminal, no SIGINT is sent.
