### ISSUE TITLE
C Syntax Highlighting Following Type Cast with No Space

### ISSUE THREAD

**Issue by coopermor** [microsoft/vscode#81334]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Write a line of C code with no space following a type cast

Does this issue occur when all extensions are disabled?: Yes
![2019-09-23 16_21_37- test c - Visual Studio Code](https://user-images.githubusercontent.com/8049699/65464109-b8a95100-de1e-11e9-830c-3267475b4c4e.png)

**Comment by alexr00** [comment]
Can you add a copy/pastable example?

**Comment by coopermor** [comment]
```
(float)MovAvgGet( &ave[AUX].rawCounts);		//(HW_GetChnData( AUX ));
(float) MovAvgGet( &ave[AUX].rawCounts);		//(HW_GetChnData( AUX ));
```

**Comment by alexr00** [comment]
Thanks! Looks like this is already fixed in Insiders. You can install the Insiders build or wait for the next stable release.
