### ISSUE TITLE
shortcut for moving to other half of a split view

### ISSUE THREAD

**Issue by MatsLP** [microsoft/vscode#81330]
There is a simple shortcut for moving cursors between "panes", i.e. "ctrl+[Num_of_pane_to_move_to].
But I think there is no shortcut that allows moving to the other side of, e.g. a git diff view.
To me it would feel quite natural if "ctrl+[Num_of_currently_active_pane]" moved the cursor to the other half of the active pane, iff the the active pane has a tab in focus that is split.

I frequently find myself missing that feature to quickly copypaste from the original revision of the file.

Maybe this is a worthwhile idea for a new shortcut, or maybe it already exists and I simply didn't find it yet?
All the Best.

**Comment by kdnk** [comment]
Can I work on this issue?
