### ISSUE TITLE
Insert Line After KeyBinding cannot be overridden

### ISSUE THREAD

**Issue by VohuMana** [microsoft/vscode#81337]
Issue Type: <b>Bug</b>

**Issue**:
In VSCode version 1.38.1 when I tried to find and replace all in a file using "Ctrl+Enter" a message popped up saying "Ctrl+Enter now inserts line break instead of replacing all.  You can modify the keybinding for editor.action.replaceAll to override this behavior." I went to keyboard shortcuts and modified `editor.action.replaceAll` to `Ctrl+Enter` and changed `Insert Line Below` to `Ctrl+Alt+Enter`, after this and after restarting VSCode pressing `Ctrl+Enter` on the flind and replace widget inserts a line break and replaces all, even though `Insert Line Below` has been set to `Ctrl+Alt+Enter`

**Actual**:
1. Change VSCode keybinding for `Insert Line Below` to something other than `Ctrl+Enter` and set `editor.action.replaceAll` to `Ctrl+Enter`
2. Open a file and write a few lines
3. Press `Ctrl+H` to open Flind and Replace
4. Turn on regex search
5. Find `\n` and replace ` ` (single whitespace) this should have the effect of removing all newlines
6. Press `Ctrl+Enter` this inserts a line break in the replace all box event and replaces all in the file

**Expected**:
1. Change VSCode keybinding for `Insert Line Below` to something other than `Ctrl+Enter` and set `editor.action.replaceAll` to `Ctrl+Enter`
2. Open a file and write a few lines
3. Press `Ctrl+H` to open Flind and Replace
4. Turn on regex search
5. Find `\n` and replace ` ` (single whitespace) this should have the effect of removing all newlines
6. Press `Ctrl+Enter` this replaces all in the file

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18990

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (9.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.4.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.0.0
remote-wsl|ms-|0.39.5
azure-account|ms-|0.8.4
csharp|ms-|1.21.3
Go|ms-|0.11.6
sublime-keybindings|ms-|4.0.3

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
We should add this command in the Find Widget scope.

**Comment by dark-swordsman** [comment]
Having the exact same issue here on VSCode 1.40.0.

It's pretty infuriating getting into the zone at work and then having a basic feature be flipped on it's head and broken. Now I had to waste a lot of time trying to fix it, and now I've gotta go and manually replace a bunch of stuff.

And I'd like to confirm, there's nothing about new line bound with my Ctrl+Enter command. 

![image](https://user-images.githubusercontent.com/7909209/68500281-88741100-0218-11ea-8f21-1a55a283b99f.png)

Who decided to change this functionality that's been working fine forever?

**Comment by VohuMana** [comment]
Why is it a feature request to fix broken functionality? I still get the message that pop up saying the functionality has been changed and if I want to change it back I need to go to key bindings and reset the keybinding, the issue is resetting the keybinding does not bring back the old functionality because setting the keybinding seems to be broken or the line break is somehow stealing the key event from replace all.

**Comment by stdedos** [comment]
That's not a feature, it's a bug:
* Removing editor.action.insertLineAfter is a no-op
* Adding/modifying the editor.action.replaceAll does not change the shortcut tooltip
* "Some changes" need a restart which is not informed anywhere
