### ISSUE TITLE
Environment source in console before display

### ISSUE THREAD

**Issue by skinnersBoxy** [microsoft/vscode#81341]
When you're using a python from inside a virtualenv, vscode automatically enters that environment when you open a new console. Unfortunately, it does so by opening a console and then simulating the keypresses that correspond to the command `source env/bin/activate`. I often find myself automatically typing, which mixes with the source command and causes the source to fail. I would much rather get the console slower but already in the correct environment then have this continue to happen. Is there some easy way to fix this?

**Comment by kieferrm** [comment]
Please file this issue against the Python extension. Thank you.
