### ISSUE TITLE
Request an command line option to check if there is updates for extension

### ISSUE THREAD

**Issue by whlkw** [microsoft/vscode#81347]
I am developing a lisp extension for vscode. 
Before user bring up the vscode, I want to prompt user to update its extension if the current installed one is not latest.

I know that vscode now provides the command line option to list all the installed extension and its version.
I want a command line option to get the extension version in market.

**Comment by whlkw** [comment]
or I must to use http lib to get the vscode market page, and interpret the extension version by hand?

**Comment by sandy081** [comment]
Unfortunately this request cannot be supported as we do not have plans in near future to handle this.
