### ISSUE TITLE
VSCode Portable: Distinguish between different machines when restoring session on startup

### ISSUE THREAD

**Issue by gandalfsaxe** [microsoft/vscode#81340]
I was trying to use VSCode Portable on two different Mac machines. An issue I ran into is VSCode's attempt at opening the last open files / windows in the last session when launching the app. I don't have the exact same files on both machines, and would actually just prefer that VSCode portable would distinguish between the two machines and save a set of open windows / files on for each machine.

As a result, when I open VSCode on machine 1, it attempts to open some files that are not present on that machine, which in turn makes VSCode not attempt to open those files when launching on machine 2, which do have the files.

Alternatively I have to maintain two portable versions of VSCode: VSCode-iMac and VSCode-MacbookPro. Currently this is the only feasible option if I want to use portable, but it doubles the disk space usage. Duplicating the app is particularly cumbersome with VSCode because it's a an app that has ~10^4-10^5 files, many more than a typical app. Most of the files are very small, yes, but the sheer amount of files being changed frequently makes VSCode Portable very sync-heavy. All of this is to say, I'd prefer not to have two copies of VSCode for that reason, but I'd still prefer to use portable mode for other reasons (e.g. no need to install on fresh systems + ability to use on system without admin access).

The best would be the ability to group machines together "these two machines are work, these two are personal", allowing the use of one single portable installation for many machines, some sharing the same purpose and set of available projects/files, but otherwise sharing the same extensions and setup by virtue of being one portable installation.

**Comment by joaomoreno** [comment]
This is a good feature request. Pinging @bpasero in case he has an idea of how this can be done today without implementing something special.

**Comment by bpasero** [comment]
Currently not, but a setting to disable restoring of editors altogether might help. I think such feature request exists.

**Comment by GandalfSaxe** [comment]
Personally I'd probably prefer having multiple portable installations rather than disabling restoring sessions altogether. It's really nice not having to open all the things you need after a machine restart.
