### ISSUE TITLE
"Go to Definition" for Absolute path doesn't work with folder named "I18n"

### ISSUE THREAD

**Issue by chungweileong94** [microsoft/vscode#81349]
- VSCode Version: 1.38.1
- OS Version: Windows 10.0.18362

Steps to Reproduce:

1. Create a React app with create react app
2. Create `jsconfig.json` with these settings
```
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": [
    "src"
  ]
}
```
3. Create a folder named `I18n` with some code to export
4. Import the code from `I18n` folder
5. `Ctrl+Click`(Go to definition) the code to navigate to the I18n definition

## Expected Result
- Navigated to the code definition in `I18n` folder

## Actual Result
- It doesn't Navigate at all 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is `I18n` located under `src`? If not, it will not be included in your project due to your `include` config

**Comment by chungweileong94** [comment]
@mjbvz Yeah it is and I did include in the `include` config, my guess is something do with the number in the folder name.

**Comment by mjbvz** [comment]
Doesn't repo for me:

![Screen Shot 2019-10-08 at 4 45 00 PM](https://user-images.githubusercontent.com/12821956/66441282-00b59f80-e9eb-11e9-8605-e2fd0525dee2.png)

 Please share a small example project
