### ISSUE TITLE
Breakpoint blinks red before turning gray

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81343]
- Start debugging
- Add breakpoint that won't be bound
- It blinks red, then turns gray

Guessing this comes after the change to breakpoint coloring, I find it kind of annoying.

**Comment by isidorn** [comment]
I do not get that behavior. I just have the red hint hover, and then it turns gray
What are you doing differently than me here (I am debugging a .js program and adding a breakpoint to a markdown file)

![hello](https://user-images.githubusercontent.com/1926584/65522913-c8429b80-deeb-11e9-99cb-9ebd510c7db0.gif)

**Comment by roblourens** [comment]
Today I don't see it...

**Comment by roblourens** [comment]
Ok here is some more strange color behavior. It's hard to see in the gif but this is a normal scenario where the breakpoint is bound. It actually starts red, then turns gray, then turns red.

![Sep-24-2019 15-34-47](https://user-images.githubusercontent.com/323878/65555272-06868d80-dee1-11e9-9049-6932623f2b30.gif)

**Comment by isidorn** [comment]
I still can not repro that. Is it possible that in that case you first as a response send that the breakpoint is not verified? And latter send a breakpoint event to say that it is verified and good?
If that is the case it explains what you are seeing.
As a fix I could only update the glyph with some timeout to work around scenarios like this.

Let me know what you think

**Comment by roblourens** [comment]
No, the log doesn't show anything weird coming from the debug adapter. And it doesn't happen 100% of the time, just saw it a few times when debugging a lot yesterday.
