### ISSUE TITLE
Debug key shortcut does not work in Mac

### ISSUE THREAD

**Issue by KiritoStudio** [Microsoft/vscode#8134]
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5
 
Steps to Reproduce:

1. Build a simple C# hello world app.
2. Insert a break point and start debug.
3. The key F10(Step Over), F11(Step Into) does not work because the default keyboard function of the two button is volume down and volume up.

**Comment by isidorn** [comment]
This is because you have an inverted keyboard F keys on your mac which is the default behvaior.
System preference > keyboard shortcuts > uncheck Use all F keys....
You can also do fn + F key
