### ISSUE TITLE
[Debug] Launch In Terminal (Git Bash) didn't reuse the previous terminal window

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#81344]
- VSCode Version: 
```
Version: 1.39.0-insider (system setup)
Commit: 8b6e0efc0a98639085fabeb5226a516785424796
Date: 2019-09-19T03:15:21.720Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```
- OS Version:  Windows 10

Steps to Reproduce:
1. Create HelloWorld.java in VS Code.
2. Set Git Bash as the default shell.
3. Click Run codelens on top of main method.
![image](https://user-images.githubusercontent.com/14052197/65474472-8f380600-deae-11e9-94f4-ff252e02b04d.png)
4. Every click on Run codelens will always open a new terminal window. But if i set the default shell to cmd or powershell, VS Code will try to reuse the previous terminal window.

Expected: The git bash behavior is consistent with cmd and powershell.

**Comment by testforstephen** [comment]
i don't think this issue is duplicated with #81345.
#81345 is about debug terminal is not switched after changing the default shell.
However, this issue is about cannot reuse current git bash terminal.

**Comment by Tyriar** [comment]
@testforstephen I think it's the java extension launching the terminal, so both have the same root cause.
