### ISSUE TITLE
Ctrl+C doesn't work sometimes with integrated terminal + git bash shell (windows)

### ISSUE THREAD

**Issue by georgyfarniev** [microsoft/vscode#81354]
- VSCode Version: 1.38.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Launch some node application (like **tsc -w**) and wait for some time
2. Wait for some time (about 30 seconds)
3. Focus on terminal and hit **Ctrl+C**
4. If it worked correctly, then try again until issue reproduced. Usually it takes 1-3 attempts.

Expected:
Program terminated and terminal can be used to launch another command

Actual:
Shell getting "stuck" and cannot be used anymore, only close button can kill the task

Note that this issue is not always reproducible, but in my setup, it happens approximately in 70% cases when I hit **Ctrl+C.**

It's pretty daunting, because terminal cannot be reused with this issues and taking a lot of time. Please let me know how can I help to debug\fix that issue. Thanks!

Does this issue occur when all extensions are disabled?: Yes

UPD: I did some more investigation and found that this bug is reproducible only when I use shell from **Git for windows**. With power shell everything works. So problem is related to bash from **Git for windows** official installer. @Tyriar any ideas what can cause the issue? I can take a look and try to find out.

**Comment by Tyriar** [comment]
I was pretty sure the last of these issues were fixed after https://github.com/microsoft/node-pty/commit/6b5ff701e8e901c0e78e422d8e72386174bdc01a#diff-8fc148e2d2217506b0e485a3033310fe was done 🤔 

I tried to reproduce and could not so maybe it's fixed in the next version of Windows as I'm on build 18985 (insiders fast ring I think).

**Comment by Tyriar** [comment]
I'll close this off but keep a look out for other reports, thanks
