### ISSUE TITLE
Wrong Preserve Case Icon in Find/Replace dialog

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#81353]
@roblourens , I can see that the preserve case icon has been replaced by [this commit](https://github.com/microsoft/vscode/commit/e6ad711936fa9f0f806f2e77a114a243f1365645) to "Aa" instead of the one it was before ( "AB")
The Icon is still "AB" in the global search but it is showing "Aa" in find/replace dialog

<img width="1440" alt="Screen Shot 2019-09-24 at 10 52 29 AM" src="https://user-images.githubusercontent.com/17094832/65483353-754ff080-deb9-11e9-8539-cdf195109e27.png">

**Comment by skprabhanjan** [comment]
@roblourens  , I guess this will be fixed in this release.
Keeping it open for confirmation , Feel free to close it :)

**Comment by misolori** [comment]
Not sure why it's showing like that on Stable when the [release notes show the `AB` icon](https://code.visualstudio.com/updates/v1_37#_preserve-case-in-find-and-replace). At least on Insiders, this is properly updated:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/35271042/65523810-a8868580-dea1-11e9-8984-c9a418a2072e.png">

**Comment by roblourens** [comment]
In today's insiders, it's missing in the search viewlet: 
![image](https://user-images.githubusercontent.com/323878/65530959-c659e780-dead-11e9-869d-637ea36b6046.png)

**Comment by misolori** [comment]
@roblourens just pushed a fix for that (https://github.com/microsoft/vscode/commit/c28cf52befe4759c371f99f95ff7bd35bfce8fe9) however @skprabhanjan is reporting that the icon is incorrect in the find/replace widget, which I see as fixed on Insiders.

**Comment by roblourens** [comment]
Yeah I think we are good in master now.
