### ISSUE TITLE
Duplicate Line or Selection

### ISSUE THREAD

**Issue by Sabesan96** [microsoft/vscode#81356]
One of the ways of creating a code element similar to an existing one (e.g. a new method overload or a new auto-implemented property) is cloning the existing element with copy-paste and then editing the clone.

ReSharper helps you streamline the cloning part — with a single keystroke Ctrl+D the cloned code is inserted right after the original.

**Comment by gjsjohnmurray** [comment]
Try Shift+Alt+DownArrow or Shift+Alt+UpArrow. The VSCode commands these bind to by default are called `Copy Line Down` and `Copy Line Up`.

Without the Shift modifier they become moves.

**Comment by Sabesan96** [comment]
But those are not created, Duplicate Line..

**Comment by chrmarti** [comment]
/needsMoreInfo

@Sabesan96 Could you explain what is missing?
