### ISSUE TITLE
chrome-sandbox mode and owner set incorrectly after unpacking

### ISSUE THREAD

**Issue by mgritz** [microsoft/vscode#81358]
- VSCode Version: 1.39.0-insider 9f6a745027fc7b2a12495970f64625e24f410224 (but also several recent insider builds)
- OS Version: Linux x64 4.9.0-11-amd64 (Debian 9.11)

code-insiders complains about mode and owner of chrome-sandbox being incorrect and refrains from starting. Happens with any recent insiders build.

Happes no matter what way of unpacking I come up with so the tarballs' internal may be broken.

Didn't happen ever before and disables any users that don't have root on their machine from using those builds.

Steps to Reproduce:

1. Download fresh .tar.gz (64bit Linux) from https://code.visualstudio.com/insiders/, unpack to local machine.
2. Start code-insiders from terminal and observe terminal output:
```
$ ./code-insiders
[15113:0924/095256.312581:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly.
Rather than run without sandboxing I'm aborting now. You need to make sure that .../VSCode-linux-x64/chrome-sandbox is owned by root and has mode 4755.
[1]    15113 trace trap (core dumped)  ./code-insiders
```
where `ls -la`says
```
-rwxr-xr-x  1 mgritz Domain Users   5099032 Sep 12 02:54 chrome-sandbox
-rwxr-xr-x  1 mgritz Domain Users 112526104 Sep 12 02:54 code-insiders
```
Workaround (requires root): `$ sudo chown root chrome-sandbox && sudo chmod 4755 chrome-sandbox`

**Comment by bpasero** [comment]
I am not 100% sure we can get this right via tar.gz. But we should investigate the underlying reason for this behavior. If we cannot fix this, then I suggest to close this as wont fix.

**Comment by joaomoreno** [comment]
There's actually another workaround, which is our recommendation since it's virtually impossible for us to fix this while distributing tarballs: simply add `--no-sandbox` when invoking the electron executable directly. We do this automatically when you invoke the CLI script.

**Comment by mgritz** [comment]
Thanks for all your help. Workaround appears to do as expected.

FYI: As of now (code-insider-1570181486.tar.gz) the problem appears to be gone automatically.
