### ISSUE TITLE
why 1.38.1 can't use emmet in vue?

### ISSUE THREAD

**Issue by syymo** [microsoft/vscode#81362]
> Version: 1.38.1 (user setup)
> Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> Date: 2019-09-11T13:35:15.005Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

today update 1.38.1 can't use emmet in vue.

add setting.config
`emmet.includeLanguages": {
        "vue-html": "html",
        "vue": "html"
    },`
but is hard use

**Comment by octref** [comment]
You shouldn't use any `emmet.includeLanguges` for Vue. And please open issues to extensions, not VS Code repo.
