### ISSUE TITLE
Autocomplete variable name: first not used

### ISSUE THREAD

**Issue by ashot11091950** [microsoft/vscode#81369]
### Hi. I have an idea for VSCode autocomplete var name function.
If I has typing var name I want to see first that vars which I not used yet, in practice it will help me and I think others too, to write a little bit quick

![image](https://user-images.githubusercontent.com/40325246/65509737-2f5c5200-dee4-11e9-8170-881e2cab1e8f.png)

this is small example, but if I have many vars with same prefix, it make no sense to use autocomplete

**Comment by mjbvz** [comment]
This is a better fit for something like [IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.VSIntelliCode)

For normal coding, there's nothing to say that referencing an already used variable isn't what the user wants to do
