### ISSUE TITLE
Custom title: move into electron-browser namespace

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81360]
In order to properly separate methods that can only be used from `electron-browser` and not `browser`, we need to move them to a place that is only accessible by `electron-browser`.

Currently a lot of window related methods are used within `titlebarPart.ts` for the custom title (e.g. minimize/maximize). We know already that the custom title will not be present in the web.

Please find a way to move the custom title into `src/vs/workbench/electron-browser`. Feel free to create a new file `windowTitle.ts` along the existing `window.ts` there, or put everything into `window.ts`. 

This is something we should do rather soon, not late.

**Comment by bpasero** [comment]
I started to add an optional dependency to `IElectronService` in the title. That is obviously a workaround until we moved things out.

https://github.com/microsoft/vscode/blob/4439aca7fb939db0309f097d066aa03c7ef8db69/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L103

**Comment by bpasero** [comment]
And here:

https://github.com/microsoft/vscode/blob/f0b99530c857c74bd0cfba6d0f835afc7a56a40f/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L286

**Comment by bpasero** [comment]
I also added another optional dependency to `IElectronEnvironmentService` for the access to `windowId`.

**Comment by bpasero** [comment]
@sbatten can we move this to a milestone? debt week March is fine, but this seems getting old.

**Comment by bpasero** [comment]
One idea, wouldn't it be possible to create a new MenuID for the window controls and then contribute these from a `electron-browser` layer?

**Comment by sbatten** [comment]
I've put it in march as a definite, but if I get a second, I'll be sure to tackle this ASAP

**Comment by bpasero** [comment]
Thanks

**Comment by sbatten** [comment]
first commit above is for breaking up `TitlebarBart`, hopefully it makes sense and doesn't break anything.

the stuff in `CustomMenubarControl`: I don't even know why we update on that change. If you don't know either, I've just deleted it with https://github.com/microsoft/vscode/commit/bc43ec6fd5d4f8686ff6dc41171b30a9f08b437c and will wait for a bug.

**Comment by bpasero** [comment]
Thanks, I think the way you solved this makes sense to me 👍
