### ISSUE TITLE
Zooming Feature not available without tabs

### ISSUE THREAD

**Issue by AKTECHNICAL** [microsoft/vscode#81367]
Zooming Feature not available without tabs zoom So i want to say that please allow this feature

**Comment by rrmistry** [comment]
Hello @AKTECHNICAL , maybe this setting helps?

> Zoom the font of the editor when using mouse wheel and holding `Ctrl`

The JSON setting is:
`"editor.mouseWheelZoom": true`

If this was your issue then it would be nice if this setting was on by default / fresh-install.

**Comment by chrmarti** [comment]
Not sure what 'without tabs' means. Which tabs?
