### ISSUE TITLE
When entering a path, the first backslash is being removed

### ISSUE THREAD

**Issue by kongsted** [microsoft/vscode#81368]
Issue Type: <b>Bug</b>

Hi,

When entering an UNC-path, the initial backslash is being removed when using the suggested path.
Not sure if it's happening in all cases, or only when typing Powershell.
Example - I'm typing:
\\\\servername\share\folder1\fi
and then it will suggest the correct name for "fi". I select that the wanted suggestion and pressing either enter or tab.
Then the string/path will be changed to:
\servername\share\folder1\file.txt

//Kongsted

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.9.0

</details>

**Comment by chrmarti** [comment]
Please file for https://github.com/PowerShell/vscode-powershell
