### ISSUE TITLE
debugging 'continue' shortcut stopped working, tries to relaunch debugging task

### ISSUE THREAD

**Issue by tomrav** [microsoft/vscode#81373]
- VSCode Version: 1.39.0-insider, 9f6a745027fc7b2a12495970f64625e24f410224
- OS Version: Darwin x64 16.7.0

Steps to Reproduce:

1. Using `f5` to cause vscode to run a debug session on a test in my project using the following config.
```json
{
    "type": "node",
    "request": "launch",
    "name": "Mocha Current",
    "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
    "args": ["${file}", "--timeout", "999999", ],
    "internalConsoleOptions": "openOnSessionStart"
}
```

2. stop on a breakpoint, previously pressing `f5` would cause the `continue` command to be executed, and the breakpoint to be released. Now I'm just getting an error `There is already a debug configuration "Mocha Current" running.` and the breakpoint remains as is. I did not change any of the keyboard shortcuts, and see both actions (`start debugging` and `continue`) bound to `f5`

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by bwateratmsft** [comment]
I'm hitting this as well in 1.39.0-insider.

**Comment by isidorn** [comment]
Yeah I totally broke this. Sorry about that!
