### ISSUE TITLE
Limited space to select the first position in a line

### ISSUE THREAD

**Issue by jboeshart** [microsoft/vscode#81378]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

On any line with text, attempt to use the mouse to place the cursor at the beginning of the line, before the first character. The amount of space is so small, it's difficult to get to the first position. Depending on where the mouse is located, you actually can see the mouse change to the text icon, but are unable to click before the first character. The mouse has to be entirely over the first character to get the cursor to the location prior to the first character. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
Let's track in #56920
