### ISSUE TITLE
ctrl+click for select word

### ISSUE THREAD

**Issue by mammadkoma** [microsoft/vscode#81372]
Issue Type: <b>Feature Request</b>

We want to ctrl+click for select word but this capability is not exist !

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.16299

**Comment by Sv443** [comment]
> 
> 
> Please answer us!

CTRL+Click already is "Go to Definition"

**Comment by gjsjohnmurray** [comment]
@mammadkoma double-click already does this.
