### ISSUE TITLE
Cannot debug dotnetcore app in docker

### ISSUE THREAD

**Issue by stsauter** [microsoft/vscode#81374]
Issue Type: <b>Bug</b>

I am trying to debug my dotnetcore app which is deployed in a docker container. But after attaching the remote process, only following message appears in the debug console and the debug symbols have not been loaded.
![debug](https://user-images.githubusercontent.com/43935040/65516390-3cc40d00-dee1-11e9-9f17-17b3fcfc9dd1.JPG)

My dockerfile looks like the following:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2
RUN apt update && \
    apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg
WORKDIR /app

COPY ./bin/Debug/netcoreapp2.2/ /app/
ENTRYPOINT ["dotnet", "Sun.dll"]
```

And I also added a new configuration in the launch.json file:
```
{
    "name": ".NET Core Docker Attach",
    "type": "coreclr",
    "request": "attach",
    "processId": "${command:pickRemoteProcess}",
    "pipeTransport": {
        "pipeProgram": "docker",
        "pipeArgs": [ "exec", "-i", "test_cont" ],
        "debuggerPath": "/vsdbg/vsdbg",
        "pipeCwd": "${workspaceRoot}",
        "quoteArgs": false
    },
    "sourceFileMap": {
        "/app": "${workspaceRoot}"
    }
}
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.83GB (0.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.8.1
azure-account|ms-|0.8.4
csharp|ms-|1.21.3
azure-iot-edge|vsc|1.17.0
azure-iot-toolkit|vsc|2.10.0
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.1.1
vscode-iot-workbench|vsc|0.10.13

</details>

**Comment by chrmarti** [comment]
Please file for https://github.com/OmniSharp/omnisharp-vscode
