### ISSUE TITLE
The API Use to Get Terminal Text

### ISSUE THREAD

**Issue by zhengzongsheng** [microsoft/vscode#81375]
Hello, I am a friend of the vscode plugin developer. I want to translate hover terminal errors into other languages. There is no corresponding API interface in the document. Will the subsequent interface be opened, so that I can get the text of the terminal?
Thanks

**Comment by Tyriar** [comment]
We've discussed this at length but decided against the API for to performance reasons

**Comment by zhengzongsheng** [comment]
Thank you for your patience
