### ISSUE TITLE
Debug nodejs output - incorrect hyperlink 

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#8137]
Version 1.3.0-insider (1.3.0-insider)

de66522e06d74752d48d92e934dcd026050355ba

2016-06-24T05:02:09.613Z

OS X El Capitan

![screen shot 2016-06-25 at 16 27 14](https://cloud.githubusercontent.com/assets/512816/16357264/d92c05ea-3af1-11e6-9968-4a8f531a3067.png)

**Comment by isidorn** [comment]
Dup of #197
