### ISSUE TITLE
Terminal's first command (powershell) does not start from path

### ISSUE THREAD

**Issue by glebdv** [microsoft/vscode#81377]
When I boot up VSCode, and open up the terminal, the command line does not start from an absolute path but rather from the center of the screen (see attached image below). This happened as of two updates ago (I'm on the Aug 2019 update atm). Now this is not much of an issue if you expand the terminal as in the picture, but if it's only 1/5th of the screen, I don't see the command I'm typing. I don't know if I'm alone in this, and sure, it's not a big problem, but visually, it's definitely a pain once you have to do this 4+ times a day over a span of a few weeks. It gets to me. Anyway just as a heads up.
![VSCodeIssue1](https://user-images.githubusercontent.com/33739704/65524595-1475e780-debc-11e9-97ff-1bebbd24c984.PNG)

**Comment by Tyriar** [comment]
Can you include vscode version/os build number?

**Comment by glebdv** [comment]
Yes, of course. Sorry about that. 
Version: 1.38.1
OS: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by glebdv** [comment]
Thank you for looking into it, sorry I didn't see the dupe
