### ISSUE TITLE
Suggestions Menu Should Close Automatically

### ISSUE THREAD

**Issue by Udopia** [microsoft/vscode#81386]
Issue Type: <b>Bug</b>

The Suggestion frame should close automatically as soon as a unique string is selected by typing. It hurts the typing flow when your stuck in a suggestion-window using the arrow keys after having fully typed a suggested keyword.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2677)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (0.37GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
cmake|twx|0.0.17

</details>

**Comment by jrieken** [comment]
The suggest windows hides automatically when it showed automatically (e.g suggestion as you type) but when explicitly requested (e.g via ctrl+space) then it doesn't do that. I think that's fair because the latter mode is more explicit and often used to "explore" suggestions. Also, in both modes the widget hides as soon as the word is finished, e.g. after typing a space.
