### ISSUE TITLE
Workbench to support left hand side of diff editor to be editable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8138]
It seems that the left hand side of a diff editor is now suddenly editable with the new search & replace preview feature. The workbench is not really fit for allowing other editors (non-file, non-file-diff) to be editable nor do I believe is it discoverable or expected to be able to type on the left hand side. You will quickly notice that typing in the left hand side suddenly opens the file (as a tab in the background) and you also do not get any dirty indicators in the title area of the editor.

If we want the diff to be editable I suggest to do what we do when you compare 2 files or open a git change: The right hand side is editable because the right hand side is an instance of `FileEditorInput`.

Otherwise, please disable editing to the left until we have a story from the workbench to make this happen.

**Comment by sandy081** [comment]
@bpasero That's a good input. But in case of replace preview, we would need leftie to be editable and rightie as replace preview. Switching them wont makes sense and I do not think these states are same as in git diff. Here we show now and after and in git it is before and now. IMO leftie state should be older than rightie.

Listing down the issues you mentioned  when making the leftie editable
- Workbench support
- Discoverability 
- Dirty indication

I am disabling this in Search/Replace preview until we get this support from workbench

**Comment by bpasero** [comment]
@sandy081 yes, we are in agreement 👍

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4180
