### ISSUE TITLE
Regression: changes view shows folder hierarchy, adds a lot of noise

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#81384]
I'm typically working with multiple files from different folders at a time. With the latest insiders push, I noticed that my PR files are now shown within folders. This adds a lot of noise into my workflow: every file changed is accompanied with 2-4 folder path to that file. As a result, I can't tell which are files, which are folders and how much actually changed. I strongly prefer the former flat rendering.

**Comment by misolori** [comment]
@paveldk have you tried toggling the view mode?

<img width="341" src="https://user-images.githubusercontent.com/35271042/65540550-79cbd780-dec0-11e9-8e2e-1aba6ee4830a.png">

Which will convert the tree list into a flat list:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/35271042/65540585-86e8c680-dec0-11e9-8429-ab3656aebec6.png">

**Comment by pavelfeldman** [comment]
Ha! Was it introduced recently? If it was, it would be nice to retain behavior by default. Did I accidentally toggle it or does new feature change the default behavior?

**Comment by pavelfeldman** [comment]
@misolori ^^

**Comment by misolori** [comment]
@pavelfeldman yes, this was recently introduced about a week ago, see https://github.com/microsoft/vscode/issues/14582#issuecomment-533601787 for more details. We also introduced a new setting,`scm.defaultViewMode`, where you change the default (`tree` vs `list`). The default is set to `tree`.

cc @joaomoreno in case you have any feedback 😄
