### ISSUE TITLE
Regression: unable to Run via Touch Bar unless in Debug perspective

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#81383]
I'm pretty much never in the Debug perspective, yet, I'm running my app regularly using the Touch Bar. In the latest version of insiders I can't do that.

Version: 1.39.0-insider
Commit: 9f6a745027fc7b2a12495970f64625e24f410224
Date: 2019-09-24T05:24:32.949Z

Fn + F5 still works as a workaround, but it is not that convenient.

**Comment by isidorn** [comment]
@pavelfeldman so you can not start debugging by using the touch bar when not debugging? This works for me using my touch bar simulator. When you say debug perspective I guess you mean that you did not start debugging already?
Let me know what you are doing differently than me (gif attached).

Also nothing changed in this area recently I believe. Does it not display the action in the Touch Bar, or pressing the Touch Bar start action does nothing?
[Code pointer](https://github.com/Microsoft/vscode/blob/4a165370141310d443344d07035951448be56a6b/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L554)

![lala](https://user-images.githubusercontent.com/1926584/65594741-adc3fd00-df93-11e9-9522-1405d035f61b.gif)

**Comment by pavelfeldman** [comment]
@isidorn This appears to be already fixed in the last update. What was happening was that the touch bar only contained debugger control buttons when I was switching to the Debug pane (was clicking the Bug icon)
