### ISSUE TITLE
Markdown in hovers no longer displays links properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#81385]
Issue Type: <b>Bug</b>

Markdown links in hovers aren't rendering properly in the recent insiders builds.
![image](https://user-images.githubusercontent.com/641685/65537495-5199a400-ded3-11e9-90e2-26d0dd1aefb5.png)

//cc @octref 

VS Code version: Code - Insiders 1.39.0-insider (9f6a745027fc7b2a12495970f64625e24f410224, 2019-09-24T05:26:22.699Z)
OS version: Windows_NT x64 10.0.18985

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Maybe related to this: https://github.com/microsoft/vscode/issues/78718?

**Comment by octref** [comment]
I haven't made any changes. What's a minimal repro by using `vscode.languages.registerHoverProvider`?

**Comment by eamodio** [comment]
Doh, this is my issue (I swear I tested in in stable tho!) -- sorry for the noise.
