### ISSUE TITLE
Sidebar icons do not indent/line-up correctly

### ISSUE THREAD

**Issue by bmfb1980** [microsoft/vscode#81380]
Hi, 

I have been writing code for 35 years.  I'm new to using VSC and cannot use it because the icons (or text if no icons) in the explorer/preview/sidebar pane DO NOT LINE UP as every other bit of software for the last 50 years has.   I've looked everywhere on how to "nudge" things over, I've looked for icon sets or no-icon sets but it seems everyone using VSC doesn't use their eyes like i do?  I NEED the indents to line up traditionally and actually look like they are inside a group and not underneath it on the same level.  The icons (and/or text if no icons)... MUST indent fully and not halfway like is the norm now.

Can anyone PLEASE help?  :(

Attached screenshot of what I'm talking about.  I want the bottom pic, like it's always been.  The top is what the rest of the world is apparently now using.  If you can't see a difference, you are not as detail-focused (OCD) as I am ;)

![lineup](https://user-images.githubusercontent.com/55409717/65534505-96bad780-decd-11e9-889f-1c2b6fd452c3.jpg)

**Comment by misolori** [comment]
@bmfb1980 try modifying `workbench.tree.indent` in your settings, this is what controls the indent spacing:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/35271042/65540829-08405900-dec1-11e9-8a5f-4d3c920f3c13.png">
