### ISSUE TITLE
Blank window on insiders under Ubuntu parallels 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81396]
Issue Type: <b>Bug</b>

**Repo**
1. Under parallels on mac os with Ubuntu 18 guest OS
1. Run latest insiders build

**Bug**

![Screen Shot 2019-09-24 at 12 01 46 PM](https://user-images.githubusercontent.com/12821956/65550605-c9b49980-ded4-11e9-9153-62d7face0b7e.png)

(left is insiders, right is stable)

VS Code version: Code - Insiders 1.39.0-insider (9f6a745027fc7b2a12495970f64625e24f410224, 2019-09-24T05:24:32.949Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_5121250|
|Screen Reader|no|
|VM|25%|

|Item|Value|
|---|---|
|Remote|SSH: az-box1|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.79GB (2.25GB free)|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Confirmed by @misolori. I suspect this is a electron 6 regression .You can fix it by launching code with the `--disable-gpu` flag.

**Comment by bpasero** [comment]
Nope, does not reproduce for me on Ubuntu.

What do you get when you run: `lsb_release -a`?

Does it reproduce when you run with a fresh empty user data dir?

**Comment by mjbvz** [comment]
When using a fresh user data dir, the native menu bar shows up but the rest of the window is still white.

**output of `lsb_release -a`**

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Parallels**: 14.1.3 

**MacOS graphics card info**
  
<img width="451" alt="Screen Shot 2019-09-24 at 11 52 49 PM" src="https://user-images.githubusercontent.com/12821956/65576314-9864b980-df26-11e9-9ee4-786f60bde897.png">

**Comment by bpasero** [comment]
@mjbvz I have the exact same setup, except for using Parallels 15, can you update?

**Comment by mjbvz** [comment]
Yep works fine with parallels 15. Seems like a parallels bug
