### ISSUE TITLE
HTML reindent lines with enters in table data cells cause staircase effect

### ISSUE THREAD

**Issue by ashemedai** [microsoft/vscode#81390]
Issue Type: <b>Bug</b>

When using enters in table data cells, the next tags will be indented one indent too far when using reindent lines from the command palette, causing a ripple effect with a lovely table staircase.

Example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <table>
        <tbody>
            <tr>
                <th>Task</th>
                <th>Text</th>
                <th>Text</th>
            </tr>
            
            <tr>
                <td>Text</td>
                <td>More Text</td>
                <td>Text</td>
            </tr>
        </tbody>
    </table>
</body>
</html>
```

Add an enter between More and Text, select `Reindent lines` and watch the staircase effect happen. Remove the enter, select `Reindent lines` and the indentation is as you would expect.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ashemedai** [comment]
Playing around with it some more, it seems the problem might be bigger than just this. Lines with the ending tag not on a separate line also trigger this behaviour. I.e.:

```html
<ul>
  <li>Text
    Text</li>
  <li>Text</li>
</ul>
```

**Comment by octref** [comment]
I suggest that you use a formatter instead of reindent lines, since reindent lines is language agnostic.

**Comment by ashemedai** [comment]
Did some more searching and finally landed on https://code.visualstudio.com/docs/languages/html#_formatting — `Format Document` is what I needed.

Coming from other editors this distinction between `Reindent lines` and `Format Document` is not immediately apparent and could be better highlighted, IMHO.

**Comment by rebornix** [comment]
Let’s use issue #29727 to track. Our auto indentation is based on regex rules while it is not fully aware of the context/scope and it also doesn’t support different indentation formats.
