### ISSUE TITLE
On non-Windows, the debug command line expects a `sh` compliant shell

### ISSUE THREAD

**Issue by SteveL-MSFT** [microsoft/vscode#81399]
- VSCode Version: 1.38.1
- OS Version: macOS 18.7.0

Steps to Reproduce:

1. Install PowerShell 7 Preview 4
2. chsh your default shell to pwsh-preview
3. try to debug in VSCode

VSCode uses a command line like:

```
cd '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/';  '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/vsdbg' '--interpreter=vscode' '--connection=/var/folders/1h/96n_hpk92332gjn6pcz0mvxr0000gn/T/CoreFxPipe_vsdbg-ui-452b151b0eb847fba759ea7337b5af33'
```

The problem is when using PowerShell as the default shell, the `vsdbg` command being in single quotes is treated as a string so that command fails.  Since `cd` is already used to go to that location, there's no need to have the full path to `vsdbg`, if this command line was changed to:

cd '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/';  ./vsdbg '--interpreter=vscode' '--connection=/var/folders/1h/96n_hpk92332gjn6pcz0mvxr0000gn/T/CoreFxPipe_vsdbg-ui-452b151b0eb847fba759ea7337b5af33'

Then it would continue to work with sh, bash, etc... and would also work with PowerShell since it's already changing to working directory to the location of the debugger.

**Comment by SteveL-MSFT** [comment]
Created issue in OmniSharp extension repo: https://github.com/OmniSharp/omnisharp-vscode/issues/3291

**Comment by SteveL-MSFT** [comment]
per @gregg-miskelly this is an issue in VSCode and not OmniSharp

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/3259fbf2674e738233acbec7d8086f9e1ba2d692/src/vs/workbench/api/node/extHostDebugService.ts#L332
Thus assigning to @weinand
Also fyi @Tyriar

**Comment by Tyriar** [comment]
Shouldn't "pwsh-preview" get treated as powershell because of this?

https://github.com/microsoft/vscode/blob/3259fbf2674e738233acbec7d8086f9e1ba2d692/src/vs/workbench/contrib/debug/node/terminals.ts#L87-L88

**Comment by SteveL-MSFT** [comment]
`pwsh-preview` is a symlink to `pwsh` (under the 7-preview path, for example).  Does the debugger command line differ if it's PowerShell?  It doesn't need to with the proposed expected cmdline I suggested above.

**Comment by Tyriar** [comment]
@SteveL-MSFT that was more of a question for @weinand, I think it should be getting treated as powershell unless I'm missing something.

**Comment by SteveL-MSFT** [comment]
The other option if you already special case PowerShell is to change it to look like:

```none
cd '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/';  & '/Users/steve/.vscode/extensions/ms-vscode.csharp-1.21.3/.debugger/vsdbg' '--interpreter=vscode' '--connection=/var/folders/1h/96n_hpk92332gjn6pcz0mvxr0000gn/T/CoreFxPipe_vsdbg-ui-452b151b0eb847fba759ea7337b5af33'
```

Where there is an ampersand (call operator) which will execute the string as an executable rather than treating it as just a string.

**Comment by weinand** [comment]
The `shell.indexOf('pwsh') >= 0` matches all patterns containing a "pwsh", so there is no need to add another check for "pwsh-preview".

**Comment by SteveL-MSFT** [comment]
Here's my launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch",
            "type": "coreclr",
            "request": "launch",
            "justMyCode": false,
            "stopAtEntry": true,
            "program": "${workspaceRoot}/debug/pwsh",
            "preLaunchTask": "Build",
            "externalConsole": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "justMyCode": false,
            "processId": "${command:pickProcess}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File",
            "script": "${file}",
            "args": [],
            "cwd": "${file}"
        },
        {
            "type": "PowerShell",
            "request": "launch",
            "name": "PowerShell Launch Current File w/Args Prompt",
            "script": "${file}",
            "args": [
                "${command:SpecifyScriptArgs}"
            ],
            "cwd": "${file}"
        }
    ]
}
```

**Comment by weinand** [comment]
I assume that only the first launch config (name ".NET Core Launch") is relevant for this issue...

**Comment by SteveL-MSFT** [comment]
@weinand correct, for me, most of the time I'm debugging PowerShell.  I already had set the integrated terminal to PowerShell like that.

**Comment by weinand** [comment]
I've verified that VS Code uses PowerShell syntax when preparing commands for the integrated terminal and the value of the `terminal.integrated.shell.XXX` settings contains a 'pwsh' or 'powershell' string.
