### ISSUE TITLE
vscode.Uri.parse is double encoding certain characters

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#81398]
Version: 1.39.0-insider
Commit: de03947834d0bcf55093b97c292b76faa75cdebc
Date: 2019-09-23T08:23:12.535Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1.
```ts
const body = "[README](https://github.com/PowerShell/vscode-powershell#reporting-problems)";
const encodedBody = encodeURIComponent(body);
const fullUrl = `https://github.com/PowerShell/vscode-powershell/issues/new?body=${encodedBody}`;
vscode.commands.executeCommand("vscode.open", vscode.Uri.parse(fullUrl));
```

2.
You'll notice in your browser that the url will not have a correctly un-encoded pound (#) sign.
For example:
```
https://github.com/PowerShell/vscode-powershell/issues/new?body=%5BREADME%5D(https://github.com/PowerShell/vscode-powershell%2523reporting-problems)
```
Notice the `%2523`. There's some double encoding happening.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/25852

**Comment by TylerLeonhardt** [comment]
Can you explain why this issue is a duplicate of that?

My issue is with _escaping_ of characters that shouldn't be escaped. The issue you linked seems to be about _unescaping_.
