### ISSUE TITLE
Navigating from and to a file stacks the errors instead of overwriting the same error.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#814]
_From @janpieterz on November 25, 2015 15:10_

When navigating from and to a file (without opening it in working files) the errors stack, as shown in the screenshot below.

This behavior isn't present when the file is in working files, only when browsing in and out (taking a peek).

![image](https://cloud.githubusercontent.com/assets/383634/11400691/1550929e-938f-11e5-8838-3916e7870e0a.png)

_Copied from original issue: Microsoft/vscode-jshint#5_

**Comment by dbaeumer** [comment]
This seems to be a problem with our internal JavaScript linter since it refers to the jsconfig.json file.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
