### ISSUE TITLE
Allow stepping from C# to C++ and vice versa when debugging

### ISSUE THREAD

**Issue by ddobrev** [microsoft/vscode#81405]
I have a solution with both C# and C++ projects, the C# project invokes C++ code with P/Invoke. I want to be able to step in and out of the C++ code when debugging, just like Visual Studio can.

**Comment by chrmarti** [comment]
Please file for https://github.com/Microsoft/vscode-cpptools.

**Comment by ddobrev** [comment]
@chrmarti I have clearly explained the issue concerns C# as much as C++ but you decided you've solved it by telling me to go to hell? Why didn't you report the issue yourself then?
Only because it's little effort to copy my title and description to the other project I'll do it. Keep fingers crossed they won't redirect me back to you saying it's a C# problem because you'll then sing praises about the current tone I'm talking to you in.

**Comment by pieandcakes** [comment]
@chrmarti This isn't a C++ issue. @ddobrev is looking for an extension to close the gap and serve both C# and C++, which we don't support.

**Comment by ddobrev** [comment]
@pieandcakes I was just replying that you're supposed to first discuss such issues among yourselves and then present a reply to users. I'm happy you figured it out on your own. @chrmarti the same applies to you, mind you.
