### ISSUE TITLE
Quick fix "Convert function into ES2015 class (ts80002)" doesn't work

### ISSUE THREAD

**Issue by LWChris** [microsoft/vscode#81409]
Issue Type: <b>Bug</b>

In a JS file, write this:

```
(function() {
    let x = () => {
        this.y = 1;
    };
})();
```

VS Code shows dots below the `f` of `function` and suggests (yellow bulb) to convert the function into an ES2015 class. However, applying the quick fix does nothing for me.

I tried it by various ways. These three ways to open the quick fix dropdown:
* Setting the cursor to the `f`, then clicking the bulb
* Setting the cursor to the `f`, then pressing `Ctrl`+`.`
* Hovering the `f`, then clicking on the "Show quick fixes ..." link in the popup's footer

And those two ways to accept the quick fix:
* Clicking the dropdown entry
* Pressing `Enter` on the entry

All 6 combinations to not work.

The quick fix to remove the declaration of `x` _does_ work (blue bulb), so it might either be that particular quick fix or because it's a different issue level.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-de|MS-|1.38.4

</details>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/33600 to track root cause upstream
