### ISSUE TITLE
Support for ProgressLocation.Dialog

### ISSUE THREAD

**Issue by kcaze** [microsoft/vscode#81400]
It looks like `ProgressLocation.Dialog` exists as an option in VS Code but is not exposed in the public VS Code API for extensions to use: https://code.visualstudio.com/api/references/vscode-api#ProgressLocation

Would you accept a pull request to enable extensions to be able to use `ProgressLocation.Dialog` when calling `withProgress()` (perhaps in the the proposed API to start)?

cc @pelmers

**Comment by kcaze** [comment]
I just put up a PR for supporting this and would be happy to update the [progress sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/progress-sample) to also include a sample usage of `ProgressLocation.Dialog`.

**Comment by roblourens** [comment]
Labelling this so it will get discussed. But I am not a big fan because I am worried about abuse. The number of cases where an extension has a legitimate reason to block the UI with a progress bar is extremely small.

**Comment by roblourens** [comment]
I'm going to close this as I don't think it fits and sounds like others agree - https://github.com/microsoft/vscode/pull/81500#issuecomment-536413727
