### ISSUE TITLE
[FR] Place Multi-Cursor before every search result

### ISSUE THREAD

**Issue by dritter** [microsoft/vscode#81407]
Hi!

It would be awesome to easily place a cursor in front of every search result. This could be done via a right click menu. A bonus would be to do this with all search results or with all search results within a file or folder. Extra bonus, if there would be a keyboard shortcut for this.

Disclaimer:
I know there is `⇧⌘L`, but that requires me to switch the windows all the time when I'm done with one file.

Thanks!

**Comment by roblourens** [comment]
This is like `alt+enter` in the find widget. Could work with the same shortcut on the search viewlet.

**Comment by njkevlani** [comment]
@dritter 

If your search term exists in 2 folder then do you want to put multiple cursors in both the files?

> A bonus would be to do this with all search results or with all search results within a file or folder. Extra bonus, if there would be a keyboard shortcut for this.

**Comment by dritter** [comment]
@njkevlani I imagine that feature on multiple layers (switchable through shortcuts):
1. Within the current file
2. Within the current folder
3. In all folders

So, if the search term exists in multiple files/folders, and I press the shortcut for that, then yes, I would want to place multiple cursors in all the files.

**Comment by roblourens** [comment]
Since you can only edit one editor at a time, I think it's not useful to add cursors to different files. The way I imagine this working is a keyboard shortcut that is only active when you have a file row selected in the search results, and when activated, it adds cursors to all results in that file.

**Comment by njkevlani** [comment]
> The way I imagine this working is a keyboard shortcut that is only active when you have a file row selected in the search results, and when activated, it adds cursors to all results in that file.

Let me know if this is enough @dritter 

I would be happy to implement this if we need to add this feature. Let me know if I can take it up @roblourens 

And some code pointer will be really appreciated! :)

**Comment by roblourens** [comment]
Sure, go for it :)

You will have to add a command that can be triggered with a keyboard shortcut. Some other search commands are registered here: https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/workbench/contrib/search/browser/search.contribution.ts#L95

And you will have to get all the results of the selected FileMatch and add cursors to their positions after opening the editor. I'm not sure how to add multiple cursors off the top of my head. But here is where we open the editor: https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/workbench/contrib/search/browser/searchView.ts#L1519
