### ISSUE TITLE
Auto import not working

### ISSUE THREAD

**Issue by aquaductape** [microsoft/vscode#81404]
- VSCode Version:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic snap
```
- OS Version:
```
OS: Ubuntu 18.04.3 LTS x86_64 
Host: HP Pavilion Laptop 15z-cw100 
Kernel: 5.0.0-29-generic 
```

<details>
<summary>settings.json</summary>
<br>
<pre>
{
  "editor.fontSize": 18,
  "editor.wordWrap": "on",
  "editor.lineNumbers": "relative",
  "emmet.triggerExpansionOnTab": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "workbench.startupEditor": "newUntitledFile",
  "window.menuBarVisibility": "toggle",
  "window.zoomLevel": 0,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "emmet.syntaxProfiles": {
    "javascript": "jsx"
  },
  "liveServer.settings.donotVerifyTags": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "terminal.integrated.fontSize": 17,
  "workbench.sideBar.location": "left",
  "workbench.editor.enablePreviewFromQuickOpen": true,
  "editor.showUnused": true,
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "es5",
  "workbench.colorCustomizations": {
    "[Dainty – Nord (chroma 2, lightness 3)]": {
      "list.activeSelectionBackground": "#4a5d7c"
    },
    "[Material Theme Palenight]": {
      "editorCursor.foreground": "#c7c7c7",
      "list.activeSelectionBackground": "#3b4a63"
    }
  },
  "html.autoClosingTags": false,
  "javascript.autoClosingTags": false,
  "vim.easymotion": true,
  "vim.enableNeovim": true,
  "vim.neovimPath": "nvim",
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "<C-n>"
      ],
      "commands": [
        ":nohl"
      ]
    },
    {
      "before": [
        "L"
      ],
      "after": [
        "$"
      ]
    },
    {
      "before": [
        "H"
      ],
      "after": [
        "^"
      ]
    },
    {
      "before": [
        "j"
      ],
      "after": [
        "g",
        "j"
      ]
    },
    {
      "before": [
        "Z",
        "Z"
      ],
      "commands": [
        ":wq"
      ]
    },
    {
      "before": [
        "y",
        "f"
      ],
      "after": [
        "v",
        "a",
        "{",
        "V"
      ]
    }
  ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [
        "p"
      ],
      "after": [
        "p",
        "g",
        "v",
        "y"
      ]
    },
    {
      "before": [
        "y"
      ],
      "after": [
        "y",
        "g",
        "v",
        "<Esc>"
      ]
    }
  ],
  "vim.leader": "<space>",
  "vim.handleKeys": {
    "<C-a>": true,
    "<C-f>": false
  },
  "workbench.colorTheme": "Material Theme Palenight",
  "vim.easymotionMarkerHeight": 20,
  "vsicons.associations.folders": [
    {
      "icon": "container",
      "extensions": [
        "container",
        "containers"
      ],
      "format": "svg"
    }
  ],
  "vsicons.associations.folderDefault.folder": {
    "icon": "myFolder",
    "format": "svg"
  },
  "vsicons.associations.files": [
    {
      "icon": "myMarkdown",
      "extensions": [
        "md",
        "custom.md",
        "markdown",
        "mdown"
      ],
      "format": "svg",
      "overrides": "md"
    }
  ],
  "workbench.iconTheme": "vscode-icons",
  "breadcrumbs.filePath": "off",
  "debug.allowBreakpointsEverywhere": true,
  "terminal.integrated.fontFamily": "'PowerlineSymbols','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
  "vim.easymotionMarkerFontWeight": "bold",
  "vim.easymotionMarkerFontSize": "15"
}
</code>
</details>

- File structure
```
.
├── package.json
├── node_modules
├── public
├── src
│   ├── App.js
│   ├── App.scss
│   ├── App.test.js
│   ├── components
│   │   └── layout
│   │       ├── Landing.js
│   │       └── Navbar.js
│   ├── img
│   │   ├── icon.png
│   │   └── showcase.jpg
│   └── index.js
├── package.json
└── yarn.lock
```

Navbar.js
```
import React from 'react';

const Navbar = () => (
  <nav className="navbar bg-dark">
  </nav>
);

export default Navbar;
```
App.js
```
import React, { Fragment } from 'react';
import './App.scss';

const App = () => (
  <Fragment>
    Navbar
  </Fragment>
);

export default App;
```
Normally what should happen is place the cursor after "Navbar" then press `Ctrl+Space` then auto import suggestions should show. The result is 'No suggestions'. Made sure to restart TS server but that didn't help.

**Comment by mjbvz** [comment]
Have you tried creating a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson)?

**Comment by aquaductape** [comment]
So auto import does work if I am exporting it without using the default keyword `export const Navbar`. I think this is normal? Because it's been while since I worked on a react project and I just remembered that auto import works only when avoiding default. 

In answer to your question. Yes I tried `jsonfig.json` and it didn't solve auto import with export default.

**Comment by Gameghostify** [comment]
This same thing happens for me when using node.js/commonjs style default exports

For example:

foo.js
```js
    const foo = "bar";
    module.exports = foo;
```

what I'll see in another file:

![image](https://user-images.githubusercontent.com/33099493/65840107-f9b8ce00-e314-11e9-8803-cff948b462e0.png)

Adding to that, I've got a jsconfig.json that looks like the following:

```json
{
	"compilerOptions": {
		"target": "es2015",
		"lib": ["es2015"],
		"module": "commonjs",
		"moduleResolution": "node",
		"checkJs": true
	},
	"include": ["./src/**/*", "./test/**/*"],
	"exclude": ["node_modules", "**/node_modules/*"]
}```

However I'm still getting `lib.dom.d.ts` suggestions. Maybe this is connected?

**Comment by Gameghostify** [comment]
To add to my comment from before:

I've tried installing TS versions (all the way back to 3.5.3) globally (I made sure to change the `tsdk` setting) and locally (made sure to select the local version through `> Select TypeScript version`) and restart the TS server every time.

Still, I don't get any suggestions for imports at *all* when in a node.js project

**Comment by fabis94** [comment]
Same, I don't understand how auto import is supposed to work, because it doesn't work at all in a JavaScript (not TypeScript) project. Can't get them to work in a node.js commonJS project and can't get them to work in a simple test project either.

**Comment by mjbvz** [comment]
@Gameghostify @fabis94 Open separate issues with example code. There are a lot of reasons why you may not see auto import working. Separate issues makes investigation easier
