### ISSUE TITLE
Branch sync fails when a different upstream tag was changed

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode#81408]
Issue Type: <b>Bug</b>

Branch sync fails when a different upstream tag was changed:
```

> git pull --tags upstream master
From github.com:kubeflow/pipelines
 * branch              master     -> FETCH_HEAD
 ! [rejected]          0.1.31     -> 0.1.31  (would clobber existing tag)
```
The error happens when I click on the sync button at the lower left part of the window.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.19.37-5+deb10u1rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz (12 x 1351)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.64GB (0.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
vscode-ciderlsp|cid|1.0.0
chmod|dle|1.1.0
python-preview|don|0.0.4
githistory|don|0.4.6
python-extension-pack|don|1.6.0
gitlens|eam|10.0.1
code-runner|for|0.9.14
jsonnet|hep|0.1.0
nbpreviewer|jit|1.2.2
vscode-github|Kni|0.30.2
restructuredtext|lex|114.0.0
MagicPython|mag|1.1.0
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.4
python|ms-|2019.9.34911
vscode-ai|ms-|0.6.5
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
csharp|ms-|1.21.3
Go|ms-|0.11.6
java|red|0.49.0
vscode-yaml|red|0.5.3
vscode-zipexplorer|sle|0.3.1
vscodeintellicode|Vis|1.1.9
jinja|who|0.0.8
vscode-proto3|zxh|0.3.0

</details>

**Comment by joaomoreno** [comment]
https://stackoverflow.com/questions/58031165/how-to-get-rid-of-would-clobber-existing-tag

**Comment by Ark-kun** [comment]
@joaomoreno The issue is not about GIT CLI. This is a usability issue. The VS Code UX (branch changing) is broken when somebody changes something in different area.

/reopen
