### ISSUE TITLE
Color token for status bar colorization

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#81401]
@misolori suggested to us that we request a status bar colorization token so that we can properly add colors to the text in the status bar.

This was originally raised in https://github.com/PowerShell/vscode-powershell/issues/1779#issuecomment-533595174 

The color looks good in dark themes:
![image](https://user-images.githubusercontent.com/2644648/65553909-da690d80-dedc-11e9-8194-e3b49541434a.png)

but not good in light themes:
![image](https://user-images.githubusercontent.com/2644648/65553885-cae9c480-dedc-11e9-8e21-ddfc1a869c81.png)

 Not sure if there's any more detail I need to add here... let me know and I'd be happy to supply it!

**Comment by aeschli** [comment]
You can already set a Color or a ThemedColor as the foreground of a status bar icon.
The Color is a hard-coded color and is not a good idea as it will not work with every theme.
The ThemedColor is the right way to go.
Ideally it's the id of an existing color that exists somewhere else in the UI. It's color value is defined by the current theme.
Alternatively you can also define your own color and define defaults for light, dark and hc. Then users and themes can customize that color: See https://code.visualstudio.com/api/references/contribution-points#contributes.colors
