### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by iSokrat** [microsoft/vscode#81419]
Issue Type: <b>Performance Issue</b>

In the last version of VS Code I've noticed that the search has become quite slow. In order to find something in *.js files, the search spend ~7-8 sec. Recently, the same search took ~1-2 sec.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
mustache|daw|1.1.1
vscode-eslint|dba|1.9.1
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
githd|hui|2.1.0
haml|kar|1.3.0
vscode-css-peek|pra|3.0.2
ruby|reb|0.25.3
code-spell-checker|str|1.7.18
vscode-import-cost|wix|2.12.0

</details>

**Comment by chrmarti** [comment]
There is a toggle button on the right of 'files to exclude' on the Search viewlet. Make sure that is enabled otherwise your exclusions won't be applied.

**Comment by roblourens** [comment]
Also please see whether any tips on this page help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
