### ISSUE TITLE
Lock folders and files

### ISSUE THREAD

**Issue by blackmady** [microsoft/vscode#81410]
Sometimes there are too many files and folders in a project, and some folders we don't want to modify. If the user can lock them, the project directory will be clearer. After locking, it can't be expanded and can't be searched.

**Comment by chrmarti** [comment]
Try adding these folders / files to the file exclusions in the settings:
![image](https://user-images.githubusercontent.com/9205389/65574126-e69cab80-df6c-11e9-9d9c-6cb70b037ed3.png)
That will hide it from the Explorer view and the file / text search.
