### ISSUE TITLE
i am not getting code referance letters not recieving

### ISSUE THREAD

**Issue by aslamsk** [microsoft/vscode#81414]
i am not getting referances wile typing code for example i am typing console i am not getting .log refereance so how can i active that feature or tell me how to reset all settings

**Comment by chrmarti** [comment]
/needsMoreInfo

Could you attach a screenshot of the entire window?

**Comment by aslamsk** [comment]
what i sent you screenshot is my view and check why i am  not getting those
suggestions text this is updated version also

**Comment by mjbvz** [comment]
Upload the screenshot on github

**Comment by aslamsk** [comment]
Ok please wait I will sent now only

**Comment by mjbvz** [comment]
Please just drag and drop the image into the github comment box to upload it

**Comment by mjbvz** [comment]
Closing as not actionable with out repo steps
