### ISSUE TITLE
explorer gets closed automatically

### ISSUE THREAD

**Issue by vimivimal** [microsoft/vscode#81416]
In new window i opened the folder, folder opens successfully.
but when ever i press search/ Source Control/debug/extension then explorer gets closed automatically. even after i use File->Open->Filename then also it is not get opened. after quit and opened the vscode then only explorer is gets opened. after relaunched then also explorer gets closed i press search/ Source Control/debug/extension.

About Visual Studio Code
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

I use Mac os version 10.14.6

**Comment by chrmarti** [comment]
The UI is such that only one of the side-panels can be visible at the same time. This by design. 

There should be an icon to click for the Explorer on the sidebar, if that is missing right-click the sidebar and enable it again.

**Comment by vimivimal** [comment]
Thanks for the reply

the Icon gets vanished and it click others. after switching to other pane i cant even open the the folder again by file->open->foldername. even if i done file->open->foldername then also nothing happens

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by vimivimal** [comment]
<img width="946" alt="Screenshot 2019-09-27 at 1 01 05 PM" src="https://user-images.githubusercontent.com/19769860/65750966-332be680-e127-11e9-97cf-73d18ea8c71a.png">when i open the vscode i can see the explorer

<img width="892" alt="Screenshot 2019-09-27 at 1 02 07 PM" src="https://user-images.githubusercontent.com/19769860/65750967-332be680-e127-11e9-8985-b959e640b360.png">
after i clicked the search icon on the left, the explorer icon vanished
<br>even i tried to open the folder by file->open->filename. then also no effect.

**Comment by chrmarti** [comment]
What do you get when you right-click on any of the icons in the sidebar? Try to enable the explorer there:
![image](https://user-images.githubusercontent.com/9205389/65754325-14225a00-e111-11e9-81ec-0ba5be2f2251.png)

**Comment by vimivimal** [comment]
yes you where correct, explorer was not enabled.
after i enable it works fine.

thanks for the solution @chrmarti
