### ISSUE TITLE
Alt + Left Arrow (return to previous refrenced files)

### ISSUE THREAD

**Issue by abbasghanipour** [microsoft/vscode#81415]
some times in my project (Rectjs + typescript) when i press combination keys (alt + left arrow) for return to previues file after press F12 on every functions , class and ... then vs code open new window for the file, then i have two open window for same file (.tsx) and intellisense don't work correctly.

**Comment by chrmarti** [comment]
/needsMoreInfo

Which OS is this? Does VS Code receive Alt + Left Arrow?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
