### ISSUE TITLE
Completions don't highlight/replace string with a dot

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode#81418]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Have a completion that includes a `.`
2. Type that string, to a part where your after the dot
3. Exit the completions with `esc`
4. Resume the completion with `control + space`
5. Only the part after the dot will highlight

I would expect the whole word to highlight on step 5

This shows me showing, that it works for `console` and `example` which is before the `.`. After that I show of how resuming completion on the part after the `.` does not correctly figure out where the whole word/token ends. If I complete in that state, I end up with `example.example.willWeGetAHighlight` when I would want `example.willWeGetAHighlight`.
![2019-09-25_10-00-11](https://user-images.githubusercontent.com/5943908/65581505-dcce7480-df7b-11e9-8b8c-7cfa65765b29.gif)

VS Code version: Code - Insiders 1.39.0-insider (817eb6b0c720a4ecbc13c020afbbebfed667aa09, 2019-09-25T05:28:51.690Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.21.3

</details>

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/elm-language-server/issues/75#issuecomment-528807966

**Comment by Razzeee** [comment]
It would be really helpful to know, what you found out and why this was closed.

**Comment by jrieken** [comment]
Is this your extension? Do you need guidance in how to implement a completion item providers? Did you check with our sample https://github.com/microsoft/vscode-extension-samples/blob/master/completions-sample/src/extension.ts and did you check with our jsdocs https://github.com/microsoft/vscode/blob/d1be9d02cd07cfc974a93ddf258ba344125d40dc/src/vs/vscode.d.ts#L3336?

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/elm-language-server/issues/75#issuecomment-528807966
Is my extension or well https://github.com/elm-tooling/elm-language-client-vscode is

I mostly referenced the language server docs and samples until now. The example from the initial post is the https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample repo, but with changed completion strings. In hindsight, I should have pushed that repo.

**Comment by Razzeee** [comment]
And I don't think that I have seen any docs that specify that a "." (and maybe more chars? ) are special characters and should not be part of your completions.

**Comment by jrieken** [comment]
Check out this: https://github.com/microsoft/vscode/blob/c0aee712695e0071f56ed881cfb292c26426f62f/src/vs/vscode.d.ts#L3404. A completion item can define the range it replaces. When omitted vscode uses the current word which is likely separated by '.' (default). Now, the replace range consequently defines what text (prefix) is used for filtering. So, given a `foo.bar|` (`|` is the cursor) prefix your extension is telling us (likely by not saying anything) that it will replace `bar`, not `foo.bar`.

FYI - You can use Cmd+? to toggle "explain mode" when showing suggestions. That will show you what word was used to compare/rank suggestions.

**Comment by Razzeee** [comment]
Lsp does not have that. But it has insertText and filterText. https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion

I played around with these, but it resulted in fragile and not very straight forward code (in my opinion). And I don't really agree with the "magical" omission of some chars. At least document it (even if just in this issue).

**Comment by Razzeee** [comment]
I'll try to use the explain mode, next week, when I have a workstation again. Thanks for the hint.

**Comment by jrieken** [comment]
> I played around with these, but it resulted in fragile and not very straight forward code (in my opinion). And I don't really agree with the "magical" omission of some chars. At least document it (even if just in this issue).

In LSP land the range exists inside `CompletionItem#textEdit`. Please clarify what "magical" should mean?

**Comment by Razzeee** [comment]
That should simplify the code a fair bit.

"magical" at the moment is that completionItems with a dot inside their string behave differently then items without.

**Comment by Razzeee** [comment]
So I think I have the completion being replace correctly now. But it's not highlighting the whole string correctly, as you can see in the example gif.

I'm assuming that `filterText` won't help? Cause I'm not setting it, thus should be falsy.

Maybe the resume action (me pressing Control + Space) after the dot does not correctly recognize the label value?

```
/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used.
	 */
	filterText?: string;
```
