### ISSUE TITLE
CTRL+F not working 

### ISSUE THREAD

**Issue by narendrasinghrathore** [microsoft/vscode#81411]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/4208015/65570443-bf4eda00-df7e-11e9-9473-32743bc6503f.png)

Steps to Reproduce:

1. open any files ( for.eg some.ts )
2. CTRL+F

**Comment by chrmarti** [comment]
Are you using `CTRL + F` as the first combination in a multi-keypress keybinding?

**Comment by narendrasinghrathore** [comment]
Yes, 
Scenario is:
I have a open file in editor.
To search text, i use CTRL+f as earlier.
But not working.

**Comment by alexandrudima** [comment]
@narendrasinghrathore Can you please search for Ctrl+F in your keybindings? Can you then share the contents of your `keybindings.json` ?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by narendrasinghrathore** [comment]
@alexandrudima sure, image attached below
![image](https://user-images.githubusercontent.com/4208015/65595039-7d8b5700-dfb1-11e9-8850-adc6891c6fb7.png)

**Comment by alexandrudima** [comment]
@narendrasinghrathore It looks that you have configured `Ctrl+F` to be the beginning of a chord keybinding in your user settings. You have configured `Ctrl+F Ctrl+numpad_add` to zoom in the editor font and `Ctrl+F Ctrl+numpad_subtract` to zoom out the editor font. From your issue, it sounds like you might have done this by accident. So simply go to your `keybindings.json` and fix your bindings or remove them. You can continue using the UI or you can press on the icon in the editor title area to open your `keybindings.json` directly for editing.
