### ISSUE TITLE
F11 not working

### ISSUE THREAD

**Issue by 123harshitsangani456** [microsoft/vscode#81412]
Issue Type: <b>Bug</b>

VsCode not switching to fullScreen mode on pressing F11, We need to manually go to View->Appearence->Full Screen

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.81GB free)|
|Process Argv|--folder-uri file:///d%3A/LCTW/HK%20Byte/ImageLight/App/v1/imagelight|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-extension-pack|and|1.0.2
vue-jumptotag|and|1.3.3
vue-snippets-standardjs|and|1.0.1
vscode-standardjs-snippets|cap|0.8.7
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.4.1
flutter|Dar|3.4.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.0.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
vscode-edge-devtools|ms-|1.0.3
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
vetur|oct|0.22.3
LiveServer|rit|5.6.1
vscode-status-bar-format-toggle|tom|1.5.0

</details>

**Comment by chrmarti** [comment]
Do you have any other applications running that might capture the F11 key?

**Comment by alexandrudima** [comment]
@123harshitsangani456 Does VS Code receive F11 ?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
