### ISSUE TITLE
Side explorer not scrolling with unlocked scrolling wheel

### ISSUE THREAD

**Issue by dikmedvescekmurovec** [microsoft/vscode#81427]
Issue Type: <b>Bug</b>

1) Have a long list of files (e.g. node_modules) open in side file explorer.
2) Unlock mouse wheel
3) Scroll up (or down)
4) Move mouse off the explorer
5) Move mouse back on the explorer
6) Scrolling up (or down) is disabled. 
7) Scroll up a bit and down again - it works again

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.7.0
ng-template|Ang|0.802.3
hex-to-rgba|dak|0.1.1
gitlens|eam|10.0.1
auto-rename-tag|for|0.1.0
sml|fre|0.0.18
rainbow-csv|mec|1.3.1
prettify-json|moh|0.0.3
python|ms-|2019.9.34911
subtitles-editor|pep|1.0.4
java|red|0.49.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0
vscode-icons|vsc|9.4.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by dikmedvescekmurovec** [comment]
> > Unlock mouse wheel
> 
> What does this mean?

It's a special button used for quick scrolling using the mouse wheel.  An example can be seen here: [https://www.youtube.com/watch?v=UvA9-YcDMmg](YouTube)

**Comment by joaomoreno** [comment]
Oh yeah I got one too, from Logitech. I can't reproduce this, everything works as expected though...
