### ISSUE TITLE
Cannot Uninstall Extension because another extension depends on it 

### ISSUE THREAD

**Issue by UmarEjaz** [microsoft/vscode#81420]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by UmarEjaz** [comment]
I've installed an extension pack called "Web Builder Essentials" for VS Code. There are two extensions in it which I want to uninstall but it says Cannot uninstall extension because Web Builder Essentials depends on it.

**Comment by chrmarti** [comment]
You will need to uninstall Web Build Essentials first. 🤷‍♂

**Comment by UmarEjaz** [comment]
Is there any way to remove the dependencies of "Web Development Essentials" without uninstalling it.

**Comment by chrmarti** [comment]
/causedByExtension

Not if "Web Development Essentials" has them as dependencies. If "Web Development Essentials" listed them as part of an extension pack, then yes. Best to file this as a request for "Web Development Essentials": https://github.com/jamesqquick/Web-Development-Essentials-Extension-Pack/issues/new

They might want to check out: https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup
