### ISSUE TITLE
extension marketplace

### ISSUE THREAD

**Issue by Fiifi94** [microsoft/vscode#81422]
Issue Type: <b>Performance Issue</b>

i can't download any extension from the extension marketplace. the feedback i get is "we cannot connect to the extensions marketplace at this time, please try again later". I have internet.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.15063

Extensions: none

**Comment by Fiifi94** [comment]
![vs](https://user-images.githubusercontent.com/45319957/65590872-66357500-df83-11e9-83ac-c46533838fd8.PNG)

**Comment by chrmarti** [comment]
Are you behind a network proxy?
