### ISSUE TITLE
SerializeRequest should throw if an argument can not be serialized

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81424]
Currently the [`seriazlieRequest`](https://github.com/Microsoft/vscode/blob/74731f65aa82e69c28e75a29a0fee7348dd6befa/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L595) does not throw if the argument can not be serialized, it simply converts all the arguments to `null` [here](https://github.com/Microsoft/vscode/blob/74731f65aa82e69c28e75a29a0fee7348dd6befa/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L26)

Just throwing an error is better than a no-op which makes it hard to discover the issue.
Is there some particular reason why we do not throw here?

fyi @alexandrudima @bpasero

**Comment by bpasero** [comment]
+1, I find it weird that we would happily continue to execute a method on the extension host side knowing that the arguments we got could not be serialized?
