### ISSUE TITLE
Mac Console flooded with Faults

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#81429]
Issue Type: <b>Bug</b>
I found vscode sending the following fault up to 10x per second. Maybe it is somehow connected to https://github.com/electron/electron/issues/19519.

Code - Insiders Helper (Renderer)
nw_path_close_fd Failed to close guarded necp fd 72 [9: Bad file descriptor]
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helpter (Renderer) (/usr/lib/system/libsystem_network.dylib)

VS Code version: Code - Insiders 1.39.0-insider (817eb6b0c720a4ecbc13c020afbbebfed667aa09, 2019-09-25T05:27:22.634Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
sort-imports|ama|6.1.0
cypress-snippets|and|1.2.0
jest-snippets|and|1.7.0
atlascode|atl|1.4.3
vscode-custom-css|be5|3.0.7
color-info|bie|0.5.1
markdown-mermaid|bie|1.2.0
mermaid-markdown-syntax-highlighting|bpr|1.0.1
better-toml|bun|0.3.2
twigcs|cer|1.1.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|1.9.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.0.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.2.2
file-icons|fil|1.0.19
vscode-firefox-debug|fir|2.3.1
vscode-architect|gil|0.1.0
vscode-pull-request-github|Git|0.11.2
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.153
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.2
plantuml|jeb|2.12.1
polacode-2019|jef|0.5.1
browsersync|jer|2.1.0
vscode-peacock|joh|3.1.5
vscode-commitizen|Kni|0.8.3
twig-language-2|mbl|0.8.10
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.16.0
auto-barrel|mik|1.6.5
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.77.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
vscode-remote-extensionpack|ms-|0.17.0
references-view|ms-|0.0.30
debugger-for-chrome|msj|4.12.0
ts-prop-dag|nat|1.0.6
gremlins|nho|0.14.4
vscode-jest|Ort|3.0.2
vscode-versionlens|pfl|0.24.0
rpa-eslint-snippets|rav|0.0.2
fabric8-analytics|red|0.0.13
vscode-yaml|red|0.5.3
explorer-exclude-vscode-extension|Red|1.2.0
elastic|ria|0.13.3
preview-vscode|sea|2.0.3
code-settings-sync|Sha|3.4.3
vscode-barreler|shi|0.0.1
sourcegraph|sou|1.0.14
cucumber|ste|0.12.0
gif-code-snippet|sub|1.0.2
easy-snippet-maker|tar|0.0.6
vscode-mermaid-editor|tom|0.4.2
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
snippet|vsc|0.7.0
vim|vsc|1.10.2
vscode-mermaid-preview|vst|1.2.0
quokka-vscode|Wal|1.0.253
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@bm-stschneider and not in stable?

**Comment by bm-stschneider** [comment]
In the stable version as well.

**Comment by bm-stschneider** [comment]
Also, I don't know if it has any impact on anything, I was actually trying to track down com.docker.hyperkit issues :)

**Comment by MatthiasWinkelmann** [comment]
I'm seeing the same problem:

`nw_path_close_fd Failed to close guarded necp fd 45 [9: Bad file descriptor]`

Versions:

```
Version: 1.40.0-insider
Commit: ceeb587991f647659d42a82f87acf3d9778b4d0e
Date: 2019-10-14T10:18:06.503Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.2.0
```

*BUT* I'm seeing the same problem with a completely different application (a VPN client). Searching for nw_path_close_fd shows quite a few similar episodes in all sorts of projects, but not much further information. 

I believe Electron is possibly a LCD for a significant number of these problems.

**Comment by chezsmithy** [comment]
I am also seeing this issue with the latest insiders and non-insiders builds of vscode:

<img width="1211" alt="Screen Shot 2020-04-06 at 4 37 54 PM" src="https://user-images.githubusercontent.com/5754300/78614974-061e6600-7825-11ea-9e8f-c7d634c3ef7c.png">
