### ISSUE TITLE
fetchTasks() does not return custom properties of a task's definition

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#81439]
- VSCode Version: 1.38.1 (as well as 1.39.0-insider)
- OS Version: Mac 10.14.6

When calling `fetchTasks({ type: '<my-custom-type>' })`, any matching tasks returned have been "resolved" into the their underlying ShellExecute/ProcessExecute/CustomExecution types and the `definition` property will not include any properties set by the user in `tasks.json`.  This prevents extensions from (easily) selecting one of those tasks based on a given property of that definition.

For example, in our case we have a property of our custom task that refers to a specific file within the workspace. If we want to execute that task when a command is invoked on the associated file's context menu, we'd like to be able to something along the lines of:

```typescript
const filename = ...;
const tasks = vscode.tasks.fetchTasks({ type: '<my-custom-type'});
const matchingFileTasks = tasks.filter(task => task.definition.filename === filename);

let selectedFileTask;
if (matchingFileTasks.length === 1) {
  selectedFileTask = matchingFileTasks[0];
} else if (matchingFileTasks.length > 1) {
  selectedFileTask = quickPickTask(matchingFileTasks);
} else {
  throw new Error('No tasks found.');
}

vscode.tasks.executeTask(selectedFileTask);
```

**Comment by alexr00** [comment]
@philliphoff once this is makes it into insiders(probably Monday or Tuesday) could you verify that you can see the definition make it back through fetchTasks?

**Comment by bwateratmsft** [comment]
@alexr00 @philliphoff I tried it out in the latest insiders, and it works perfectly. Thank you Alex!
