### ISSUE TITLE
VS Code is not opening

### ISSUE THREAD

**Issue by ChristianDC178** [microsoft/vscode#81431]
- VSCode Version: 1.38
- OS Version: Windows 10 Enterprise

Hi all ! 

I am having problems went I try to open VS Code with the traditional double click. So, I did the following: 

1. In the CMD i ran code.exe --verbose
2. The log contains this: 

Fatal error in , line 0
Check failed: (i_isolate->snapshot_blob()) == nullptr.
FailureMessage Object: 000000C0A6D2E8E8

I tried with code.exe --disable-extensions and got the same. 

What could it be ? 

Thanks.

**Comment by chrmarti** [comment]
Could you try VSCode Insiders? https://code.visualstudio.com/insiders/

**Comment by ChristianDC178** [comment]
> Could you try VSCode Insiders? https://code.visualstudio.com/insiders/

Hi chrmarti, with the reinstallation the problem was solved. 

Thanks for your reply !
