### ISSUE TITLE
require() & import() snippets are at the top in suggestions

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#81438]
- VSCode Version: 1.39.0-insider, happens with 1.38.1 too
- OS Version: macOS
- TS Version: 3.7.0-dev.*, happens with 3.6.3 too

Steps to Reproduce:

1. Use `require()` or `import()` for local files in JS or TS.
2. You will see snippets at the top in the suggestions, but paths should be at the top instead.

This seems like some sort of regression because this wasn't happening with older versions of VS Code. Expected behavior would be to keep snippets at the bottom or none of them in `require()` or `import()` calls.

<img width="880" alt="Screen Shot 2019-09-25 at 22 20 04" src="https://user-images.githubusercontent.com/10441177/65632822-45047100-dfe3-11e9-8b52-3046b553e60e.png">

**EDIT:**

I know why this problem occurs. My snippets contain `/` for e.g. `try/catch`, if I change it to `try catch` it doesn't appear in suggestions list while using `require()` or `import()`.

**Comment by mjbvz** [comment]
What setting do you have for `editor.snippetSuggestions`?

**Comment by svipas** [comment]
@mjbvz I don't have it, I'm using the default one and as I can see default is `"editor.snippetSuggestions": "inline"`.

**Comment by mjbvz** [comment]
Also where are those snippets coming from? They are not included in VS Code.

**Comment by svipas** [comment]
@mjbvz They are coming from User Snippets (`Preferences: Configure User Snippets`) and they are created as "New Global Snippets file...".

Content of my global user snippet:
```
{
  "clog": {
    "prefix": "clog",
    "body": "console.log($0)",
    "description": "Log output to console",
    "scope": "javascript, javascriptreact, typescript, typescriptreact"
  },
  "[SURROUND] try/catch": {
    "prefix": "[SURROUND] try/catch",
    "body": ["try {", "$TM_SELECTED_TEXT", "} catch ($err) {", "$0", "}"],
    "description": "Surround selected text with try/catch block",
    "scope": "javascript, javascriptreact, typescript, typescriptreact"
  },
  "[SURROUND] try/finally": {
    "prefix": "[SURROUND] try/finally",
    "body": ["try {", "$TM_SELECTED_TEXT", "} finally {", "$0", "}"],
    "description": "Surround selected text with try/finally block",
    "scope": "javascript, javascriptreact, typescript, typescriptreact"
  },
  "[SURROUND] try/catch/finally": {
    "prefix": "[SURROUND] try/catch/finally",
    "body": ["try {", "$TM_SELECTED_TEXT", "} catch ($err) {", "$1", "} finally {", "$0", "}"],
    "description": "Surround selected text with try/catch/finally block",
    "scope": "javascript, javascriptreact, typescript, typescriptreact"
  }
}
```

**Comment by mjbvz** [comment]
@jrieken This seems to be about snippets and sort order, not js/ts langauge features

@svipas Change the `prefix` to avoid this. You can probably just remove it entirely since surround style operations usually don't make any sense with a prefix

**Comment by svipas** [comment]
@mjbvz Thanks, after removing `prefix` I no longer see them in suggestions list which is amazing, didn't know about this and as you said it makes sense since these are surround snippets. I really appreciate your help!

**Comment by svipas** [comment]
@mjbvz After removing or keeping `prefix` empty I no longer can see them in `editor.action.insertSnippet`. It would be perfect to keep these snippets enabled, but without them appearing in suggestions list, but unfortunately it doesn't work, so I had to revert the `prefix`...

**Comment by svipas** [comment]
@mjbvz @jrieken I know why this problem occurs. My snippets contain `/` for e.g. `try/catch`, if I change it to `try catch` it doesn't appear in suggestions list while using `require()` or `import()`.

**Comment by jrieken** [comment]
Yes, the prefix is matched against the current line and since that ends in `/` and since the prefix contains `/` it's a match. Today, snippets must have a prefix (there is a separate issue for that) but you could try with a emoji as prefix. That will very, very likely hide them from suggestions and still have them in the "insert snippet" picker

**Comment by jrieken** [comment]
closing this as dupe of https://github.com/microsoft/vscode/issues/73635
