### ISSUE TITLE
Updating dialog on Windows text is clipped

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#81433]
The "Updating Visual Studio Code" dialog on windows looks like the text is clipped or its missing "Studio Code".

![image](https://user-images.githubusercontent.com/1487073/65619644-5adb4d00-df75-11e9-93f9-060a70542c18.png)

If you point me towards the code I can look to make a PR.

**Comment by joaomoreno** [comment]
This is an issue with https://github.com/microsoft/inno-updater which I always found very hard to repro... Not sure what causes it.

**Comment by chrisdias** [comment]
I bet it's something to do with this line :)

```
    LTEXT           "Updating Visual Studio Code...",-1,11,10,66,8
```

**Comment by joaomoreno** [comment]
Ahah, indeed! I should've opened this resource file in VS a loooong time ago. Once I saw it visually it became easy to see the issue.
