### ISSUE TITLE
Cannot switch back to tabs containing images after reloading editor

### ISSUE THREAD

**Issue by Conduitry** [microsoft/vscode#81430]
- VSCode Version: 1.38.1 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open an image in VS Code.
2. Switch to another tab.
3. Use the 'developer: reload window' command, or close and reopen the editor with 'hot exit' enabled.
4. Switch back over to the tab containing the image. The tab will instead close, with an error notification in the lower right about 'Unable to open [file]: Cannot read property 'overwrite' of null.'

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Quite sure I fixed this for insiders, can you try?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Conduitry** [comment]
Yep, sorry, this does look like it's fixed in the nightly build. Thanks!
