### ISSUE TITLE
SCM: Twistie missing from CHANGES section

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#81432]
From @bpasero:

![image](https://user-images.githubusercontent.com/22350/65614880-b2e77300-dfb8-11e9-9721-4c63258b41a0.png)

We have to figure out how to repro this.

**Comment by bpasero** [comment]
This was running from web btw, not sure if it matters.

**Comment by joaomoreno** [comment]
Probably not... but I'll give it a try.

**Comment by bpasero** [comment]
I noticed that the `collapsible` CSS class was missing.

**Comment by joaomoreno** [comment]
Repro:

1. Have changes, stage all of them
2. Reload

The CHANGES section won't have a twistie.
