### ISSUE TITLE
Insiders path too long on Windows

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#81436]
Ref: https://github.com/microsoft/vscode-test/issues/43

- Download VS Code insiders archive on windows to a somewhat long path

![image](https://user-images.githubusercontent.com/4033249/65631546-9c2b2700-df8c-11e9-9b73-8b8564c65a7e.png)

- Extract all
- Boom

I suggest naming them a bit shorter or put them into a higher output dir.

**Comment by roblourens** [comment]
Looked into this together, it either didn't repro or was due to @octref unzipping into a long path.
