### ISSUE TITLE
Defer DebugConfigurationProvider configuration resolution post-task execution

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode#81437]
A `DebugConfigurationProvider` may resolve a configuration that includes a `preLaunchTask`.  This task will be executed after resolution (obviously) but executed before the debugging session starts.

There are several scenarios (e.g. in the case of Docker debugging) where details of the debugging session (e.g. the port to which the debugger should attach) may ultimately depend on that pre-launch task (e.g. mapping a given container port to a host port).  However, because the debug configuration is resolved *before* the task executes, it requires upfront agreement between the task configuration and the debug configuration and precludes the debug configuration being derived from the *result* of the pre-launch task.  E.g. the user must explicitly choose a port for both to use rather than the pre-launch task determine an available port and have debug configuration use that available port.

It would be helpful if a `DebugConfigurationProvider` had a means of deferring resolution of certain properties of its configuration until *after* the pre-launch task (if any) has executed.  The `DebugConfigurationProvider` could then use the results of that execution to alter its previously resolved configuration (if necessary).

An, initial, likely naive API might look like:

```typescript
interface DebugConfigurationProvider {
    // Existing API:
    provideDebugConfigurations(folder: WorkspaceFolder | undefined, token?: CancellationToken): ProviderResult<DebugConfiguration[]>;
    resolveDebugConfiguration(folder: WorkspaceFolder | undefined, debugConfiguration: DebugConfiguration, token?: CancellationToken): ProviderResult<DebugConfiguration | undefined>;

    // Proposed API:
    // Called after the preLaunchTask successfully executes but before debugging starts and includes the executed pre-launch task object (presumably used to derive any necessary changes).
    resolveDebugConfigurationPostLaunchTask?(folder: WorkspaceFolder | undefined, debugConfiguration: DebugConfiguration, preLaunchTask: Task, token?: CancellationToken): ProviderResult<DebugConfiguration | undefined>
}
```

**Comment by isidorn** [comment]
This is a fair feature and a nice api sketch. And yes I understand your use case. However this is currently not on the plan, thus assigning to the backlog.
fyi @weinand

**Comment by philliphoff** [comment]
@isidorn Your workaround is basically how our current implementation (of Docker .NET Core debugging) works, doing all of the work upfront, immediately prior to returning the resolved debug configuration.  However, for a number of reasons we're splitting that `DebugConfigurationProvider` into a simpler debug provider plus several specialized custom tasks providers which perform the much of that same work but in a more granular way.  (Hence the API request.)

I'll look to see whether there's a middle ground we can use in the meantime where we still use our custom tasks for the build/run logic but, as you suggest, force execution of those tasks upfront, before resolving the debug configuration.

One question: how does one await completion of a programmatically executed task?  The API documentation seems to imply that `vscode.tasks.executeTask()` returns a type that can be used to terminate a running task, but doesn't seem to provide a way of awaiting its completion.  Would we use a combination of `vscode.tasks.executeTask()` and `vscode.tasks.onDidEndTask()` to do that?

Another related question: is there a way to determine whether a task has (generally) completed successfully?  (You can hook events that fire when process-based tasks complete, which include an exit code, but there doesn't appear to be a broader pattern for ShellExecution/CustomExecution based events.)

**Comment by isidorn** [comment]
@philliphoff got it. Thanks.
@alexr00 for the api questions in the last two paragraphs.

**Comment by alexr00** [comment]
For listening for the end of a task you would need to use `tasks.onDidEndTask`. 
The API doesn't currently provide a way to tell if the task succeeded.
