### ISSUE TITLE
Feature: paste on right click regardless of selection

### ISSUE THREAD

**Issue by adamburgess** [microsoft/vscode#81447]
With #38287 being merged, I'd now like to be able to directly paste after selection.

The current behaviour with copyOnSelection = true and rightClickBehavior = copyPaste:

1. select text (text is then copied into clipboard)
2. right or left click, this clears the selection
3. right click again to paste

With the proposed mode, copyOnSelection = true and rightClickBehavior = paste:

1. select text (text is then copied into clipboard)
2. right click, and text is pasted

Why do I want this? Simple: it removes an extra click when pasting.
This mirrors how PuTTY's pastes. The new Windows Terminal recently got support for this feature, too - https://github.com/microsoft/terminal/pull/2152

**Comment by Tyriar** [comment]
To verify test on Windows and make sure that `rightClickBehavior` `paste` acts correct (as opposed to the default `copyPaste`)
