### ISSUE TITLE
Webview: Date.parse is not consistent with browsers

### ISSUE THREAD

**Issue by danmarshall** [microsoft/vscode#81445]
Issue Type: <b>Bug</b>

In a VSCode Webview JavaScript console, execute this code:

```js
Date.parse('#876333')
```

Expected:
`NaN`

Actual:
`27592231248000000`

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
xml|Dot|2.5.0
prettier-vscode|esb|2.2.2
glitch|gli|0.1.3
svelte-vscode|Jam|0.9.2
sort-typescript-imports|mic|1.4.1
sqlops-debug|ms-|1.3.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-yaml|red|0.5.3
mdx|sil|0.1.0
vscode-svg-previewer|vit|0.5.1
vscode-mdx-preview|xyc|0.2.2

</details>

**Comment by danmarshall** [comment]
Also get this result in the Debug console, not in a Webview.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by danmarshall** [comment]
No repro in insiders build. Closing this issue. Thanks @mjbvz !
