### ISSUE TITLE
which node 'which' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by skirmish-playz** [microsoft/vscode#81441]
So basically I Want To Run My Script On Visual Studio and as you see underneath its not loading and says this!
![Whats this](https://user-images.githubusercontent.com/55810787/65634047-4d55af80-dfd5-11e9-83c2-d563e5d76c5c.PNG)
what can i do

**Comment by skirmish-playz** [comment]
also this,
![YEET](https://user-images.githubusercontent.com/55810787/65634241-b89f8180-dfd5-11e9-9808-947df88754f3.PNG)

**Comment by malarahfelipe** [comment]
which only works for linux, try ` node -v  `instead
