### ISSUE TITLE
Incorrect HTML formatting with "html.format.indentHandlebars": false

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode#8144]
- VSCode Version: 1.2.1
- OS Version: Mac OS X 10.11.5

Steps to Reproduce:

Here is an extract of HTML (Angular 2) code:

```
  <app-root>Loading...</app-root>
{{#each scripts.polyfills}}
  <script src="{{.}}"></script>
{{/each}}
```

Using `Format code (shift+alt+f)` command with default `"html.format.indentHandlebars": false` setting :

```
  <app-root>Loading...</app-root>
  {{#each scripts.polyfills}}
  <script src="{{.}}"></script> {{/each}}  
```

instead of :

```
  <app-root>Loading...</app-root>
{{#each scripts.polyfills}}
  <script src="{{.}}"></script>
{{/each}}
```

I expect unchanged Angular/handlebar indentation with `"html.format.indentHandlebars": false`

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1127

**Comment by HookyQR** [comment]
@pierredewilde. This is fixed in the [beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) extension if you want it working now.
