### ISSUE TITLE
Untangle titlebar dependency from activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81457]
https://github.com/microsoft/vscode/commit/d49dad0e9a2f5ea141536c9b81989dbf0d1a9762 adds a dependency from activity bar to the title bar for adding the compact menu option.

Rather, I think the activity bar should expose a dynamic menu that can be contributed to, possibly the same menu point we use in the title, so that we just have another location for the main menu.

**Comment by sbatten** [comment]
@bpasero what do you mean by the dependency of the activity bar to the title bar? The activity bar just knows to use the custommenubarcontrol when compact is enabled and the titlebar knows to use it when it is not compact. Neither the activitybar nor the titlebar know about the other.
