### ISSUE TITLE
Auto-indent Always Jumps to End

### ISSUE THREAD

**Issue by C-Liu596** [microsoft/vscode#81453]
The short cut (Shift+alt+F) for auto-indent always jumps to the end of the file, which makes me lost track where I was before. Wish this could be fixed for good.

- VSCode Version: 1.38.1
- OS Version:10.14.5

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/needsMoreInfo

What type of file is this?

**Comment by C-Liu596** [comment]
Java

**Comment by chrmarti** [comment]
You must be using an extension for Java that comes with a formatter. (There is no built-in formatter for Java.) Please file an issue for the extension you are using.
