### ISSUE TITLE
Searching result  from all the project file including  the  dependency  jar 's *.class in a maven project

### ISSUE THREAD

**Issue by jing1213** [microsoft/vscode#81455]
In vscode 1.38, when I search text in a maven java project, only the text in my code can be searched. 
It would be much more convenient that  searching the text from  both my code and the maven dependency jar's *.class, just like Intellij Idea's  feature "double click shift " searching in everywhere.

**Comment by roblourens** [comment]
Thanks for the suggestion but I don't think this fits with VS Code's goal to be a lightweight text editor. Someday an extension might be able to contribute this.
