### ISSUE TITLE
up arrow key in search field does not move line up

### ISSUE THREAD

**Issue by willashley23** [microsoft/vscode#81450]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open the search tab (command+shift+f)
2. type in a multi-line search string in the search box.
3. Starting with your caret at the end of the search string, press the up arrow key. 
4. **observe:** It does not move to the next line, instead it changes the input to the second most recent search string. 

Does this issue occur when all extensions are disabled?: Yes/No

I have no idea if this is an introduced bug or a new feature, but if it is a feature, it  needs an override – this is very disruptive to my workflow and changes a fundamental way we interact with the search box.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide VSCode version, OS version and if it can be reproduces with all extension disabled as mentioned in template?

Also looks like this problem cannot be reproduced Insiders build on Windows. Could you check if it still a problem in insiders build https://code.visualstudio.com/insiders/ ?

<kbd>UpArrow/DownArrow</kbd> moves cursor between lines
<kbd>Alt+UpArrow/DownArrow</kbd> previous/next search string
<kbd>Ctrl+UpArrow/DownArrow</kbd> focuses previous/next field

I think similar shortcuts should be in place for MacOS
