### ISSUE TITLE
vscode.commands.onDidExecuteCommand not exists

### ISSUE THREAD

**Issue by moshfeu** [microsoft/vscode#81458]
```
disposables.push((commands as any).onDidExecuteCommand((e: any) => {
  console.log(e.command);
}));
```

`commands.onDidExecuteCommand` get an error:

> Property 'onDidExecuteCommand' does not exist on type 'typeof commands'

and in runtime

> vscode_1.commands.onDidExecuteCommand is not a function

althought #1431 has been closed and [July's updates](https://code.visualstudio.com/updates/v1_37#_vscodecommandsondidexecutecommand) including that API

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

Also in insider version

```
Version: 1.39.0-insider
Commit: 817eb6b0c720a4ecbc13c020afbbebfed667aa09
Date: 2019-09-25T05:27:22.634Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by usernamehw** [comment]
https://github.com/microsoft/vscode/issues/78091#issuecomment-521640092

**Comment by moshfeu** [comment]
@usernamehw 
 😞
Thanks!
