### ISSUE TITLE
Stuck when typing

### ISSUE THREAD

**Issue by jinlianch** [microsoft/vscode#81452]
Visual Studio Code Information:

> Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

Enabled  extensions

> Extension | Author (truncated) | Version
> -- | -- | --
> go-outliner | 766 | 0.1.20
> copy-on-select | din | 0.0.6
> gitlens | eam | 9.9.3
> Python-autopep8 | him | 1.0.2
> beautify | Hoo | 1.5.0
> mysql-syntax | jak | 1.3.1
> vscode-antlr4 | mik | 2.1.1
> prettify-json | moh | 0.0.3
> python | ms- | 2019.9.34911
> Go | ms- | 0.11.4
> sublime-keybindings | ms- | 4.0.3
> proto | pet | 0.0.2
> autoimport | ste | 1.5.3
> python | tht | 0.2.3
> go-to-method | tri | 0.1.1
> vscode-icons | vsc | 9.3.0
> vim | vsc | 1.10.2
> vscode-proto3 | zxh | 0.3.0

When I am typing(golang file), it will stuck about 2~10 seconds, I can't do anything but wait the vs to response, it start several days ago, might be after I have update the vs to the new vesion.

**Comment by chrmarti** [comment]
Does this also happen with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled`)
