### ISSUE TITLE
Right click doesn't show problem's context menu

### ISSUE THREAD

**Issue by Bingo1392** [microsoft/vscode#81468]
Issue Type: <b>Bug</b>

Hi guys,

I found an annoying UX bug. When I leftclick to a problem in the project's problems panel the background color of the problem will change to blue - the problem is now selected. In that moment I am not able to open context menu by right clicking to it to copy my error message.

Workaround: I can open context menu only if the problem is not selected (problem's background color isn't blue).

I created a reproducing youtube video here: 
https://www.youtube.com/watch?v=DsDSlOIIIq8

Steps to reproduce the bug:
1) Open a project with a TypeScript problem.
2) Open the bottom panel with Problems, Output and Terminal tabs.
3) Select the Problems tab.
4) Select the problem with left mouse button.
5) Try to open problem's context menu with right mouse button. It shouldn't be possible.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.24GB free)|
|Process Argv|C:\WorkSpace\Physter\react-components|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
prettier-vscode|esb|2.2.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
debugger-for-chrome|msj|4.12.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0

</details>

**Comment by sandy081** [comment]
@joaomoreno Tree is not triggering the `onDidChangeFocus` event. Please see the following gif, at the end I am doing `right click` which is not triggering the focus event - https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/markers/browser/markersPanel.ts#L341

![Kapture 2019-09-26 at 23 48 39](https://user-images.githubusercontent.com/10746682/65727565-63886c00-e0b8-11e9-817a-267b687b2e11.gif)
