### ISSUE TITLE
Debug: Console feels janky on high frequency output

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#81464]
Running our selfhost unit tests seems much slower than running it in a terminal. Hypothesis: tree isn't performing well enough for this scenario. We might need a specialized tree API for this.

**Comment by isidorn** [comment]
Assignign to October so we look into this next milestone.

**Comment by joaomoreno** [comment]
Actually forget about this.... it's actually as fast as on the terminal... it's the perceived performance which sucks since rendering is debounced and everything feels sluggish.

**Comment by isidorn** [comment]
Maybe I can decrease the debounce time.
Or we can test the limits of the tree and I no longer de-bounce

**Comment by joaomoreno** [comment]
I think you're gonna have to keep the debounce since the current approach is still refresh root, since we're basically `O(n^3)` right now. If we add some tree API for you to simply append children then we can reduce the whole thing to `O(n)`.

**Comment by isidorn** [comment]
I do not think we do not plan to do anything this milestone.
When we add new tree api we can look into simply adopting that api in the debug console.
Anyways pushing to backlog.

**Comment by isidorn** [comment]
Closing as out of scope, and we can reopen if we ever get passionate about this
