### ISSUE TITLE
Compact menu: make hiding more discoverable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81462]
Should maybe show an entry in the menu to hide the compact menu:

![image](https://user-images.githubusercontent.com/900690/65668958-fbe40980-e042-11e9-91b6-7c373bcbcedd.png)

**Comment by bpasero** [comment]
This is especially true now when I go into fullscreen mode, I am used to not seeing the menu at all, but now I am forced to have it all the time.

**Comment by sbatten** [comment]
@bpasero I don't think this menu entry falls into the same fullscreen hiding logic, the other menu took up a ton of space so hiding it in that focused mode made sense. If one doesn't like having the menu in compact+fullscreen, I don't think one likes the menu at all. In that case, menubarvisibility can be set to hidden.

**Comment by misolori** [comment]
After thinking about this a bit, I agree with @sbatten in that if you don't like the compact menu then you toggle this off via the setting. You can't re-order the menu like other activity bar items, so I wouldn't expect it to inherit the other interactions. I think once we solidify how to make this menu item stand out from the rest it will be more obvious that this item is different.

**Comment by bpasero** [comment]
Oh, somehow I missed the fact that I can configure `window.menuBarVisibility: hidden`. Seems to work fine.

Would it make sense to have a menu entry still to toggle this for the user?

**Comment by sbatten** [comment]
Perhaps we should re-text the menu entry under `View > Appearance` that says `Show Menu Bar` to `Show Application Menu` and let that toggle between hidden and compact for the web

**Comment by bpasero** [comment]
Having this in the menu as option is good, but I think we should also have it in the context menu. We typically make settings like this discoverable to the user through context menu entries.

**Comment by sbatten** [comment]
I will add an entry with no separation. i.e. the Compact menu entry in the context menu will look exactly like the the activity viewlet entries. 

When we finally decide how to separate the compact menu in the activity bar, we will try to map that separation into the context menu as well to avoid conflating the menu with the viewlets.

**Comment by sbatten** [comment]
I changed my mind during implementation due to the logical structure we have already in place for additional context menu entries.

**Comment by bpasero** [comment]
@sbatten thanks, I find "Hide Menu Button" rather technical. Suggest to rename to "Hide Menu" / "Show Menu".

**Comment by sbatten** [comment]
done
