### ISSUE TITLE
shows incorrect current branch in status bar untill restart 

### ISSUE THREAD

**Issue by Alpha-Scorpii** [microsoft/vscode#81470]
Have Multiple branch switch between them, It stuck into showing the last branch even though the branch is already switched to another.
On restart the IDE it switches and starts showing the correct branch.

**Comment by chrmarti** [comment]
/needsMoreInfo

How do you switch the branch? In the UI or the CLI?

**Comment by Alpha-Scorpii** [comment]
switching branch in VS Code CLI

**Comment by joaomoreno** [comment]
Can you show me a screen recording?

What platform? What code version?

**Comment by Alpha-Scorpii** [comment]
Please see if this helps to pinpoint the issue location.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7939874/65896320-a1440800-e3ca-11e9-8016-918d355f8694.gif)

**Comment by joaomoreno** [comment]
Can you run `Developer: Set Log Level...` and change it to `Trace`, then run `Git: Show Git Output` and send me the output you get while you change the branch in the terminal?

**Comment by Alpha-Scorpii** [comment]
Looking for git in: /usr/bin/git
Using git 2.20.1 (Apple Git-117) from /usr/bin/git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /Users/souravchoudhary/Project/payments
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse upload_csv
> git rev-parse --symbolic-full-name upload_csv@{u}
> git rev-list --left-right upload_csv...refs/remotes/origin/upload_csv
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :app/api/services/PaymentService.js
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git ls-tree -l HEAD -- /Users/souravchoudhary/Project/payments/.gitignore
> git show e2b6489b32b211a5d79496a921a1122c32ae6329
> git show HEAD:.gitignore
> git show :app/api/services/PaymentService.js
> git check-ignore -v -z --stdin
> git show :app/api/services/AccountService.js
> git show :app/api/controllers/SupportActionsController.js
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse upload_csv
> git rev-parse --symbolic-full-name upload_csv@{u}
> git rev-list --left-right upload_csv...refs/remotes/origin/upload_csv
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :app/api/controllers/SupportActionsController.js
> git show :app/api/controllers/SupportActionsController.js
> git status -z -u
> git check-ignore -v -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse upload_csv
> git rev-parse --symbolic-full-name upload_csv@{u}
> git rev-list --left-right upload_csv...refs/remotes/origin/upload_csv
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :app/api/controllers/SupportActionsController.js
> git show :app/api/helpers/sync-with-federal.js
> git check-ignore -v -z --stdin
/*removed some file name */
> git check-ignore -v -z --stdin
> git show :app/.gitignore
> git show :.gitignore
> git check-ignore -v -z --stdin
> git show :app/.gitignore
> git show :app/api/services/LoanServices.js
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse supportapi
> git rev-parse --symbolic-full-name supportapi@{u}
> git rev-list --left-right supportapi...refs/remotes/origin/supportapi
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse supportapi
> git rev-parse --symbolic-full-name supportapi@{u}
> git rev-list --left-right supportapi...refs/remotes/origin/supportapi
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :app/api/services/LoanServices.js
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/index
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/HEAD.lock
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/HEAD
/*removed some file name */
> git show :app/api/services/LoanServices.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse backoffice-support
> git rev-parse --symbolic-full-name backoffice-support@{u}
> git rev-list --left-right backoffice-support...refs/remotes/origin/backoffice-support
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/index
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/HEAD.lock
[debug] [.git] Change: /Users/souravchoudhary/Project/payments/.git/HEAD
[debug] [wt] Change: /Users/souravchoudhary/Project/payments/.gitignore
/*removed some file name */
> git show :app/api/services/LoanServices.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse supportapi
> git rev-parse --symbolic-full-name supportapi@{u}
> git rev-list --left-right supportapi...refs/remotes/origin/supportapi
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

**Comment by joaomoreno** [comment]
I fail to see at which point you changed the branch in the terminal. Can you show me a recording of you changing the terminal while the output appears?
