### ISSUE TITLE
Vscode does not debug using WSL for golang project

### ISSUE THREAD

**Issue by chaudharisuresh997** [microsoft/vscode#81479]
- VSCode Version:
- OS Version:UBNTU WSL with windows 10

Steps to Reproduce:

1.install golang in ubuntu WSL in windows 10
2.create one golang simple project.
3.try to debug it
4.even breakpoint is not created in the vscode when u try to debug golang code.
5. i tried to install the delve debugger which is used for golang.
6.it got an issue with goroot.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

Are you using the Remote-WSL extension?

**Comment by chaudharisuresh997** [comment]
will provide additional info
