### ISSUE TITLE
[Bug] Naming of vscode Components vscode-server vscode-remote

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81475]
This project will need a additional server to serve vscode-web at present vscode-remote is called vscode-server as binary it should get renamed to vscode-remote so we can call the server that serves vscode-web vscode-server

also in https://github.com/microsoft/vscode/blob/master/.gitignore src/vs/server is ignored which leads me to the suggestion that @bpasero is using that also for his current server implamentation he should consider joining issue: https://github.com/microsoft/vscode/issues/81474

## notice
Until this is discussed and solved we will process with vscode-web-server

**Comment by chrisdias** [comment]
i think this is now covered by the server and remote tunnels, see https://code.visualstudio.com/docs/remote/tunnels
