### ISSUE TITLE
Bad behavior with limited internet connection

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode#81471]
Issue Type: <b>Bug</b>

When starting vscode with limited internet connection (for instance with an active VPN connection to a company network, which limits access to certain hosts) vscode does not initialize fully (probably the update queries hang). This is especially a problem when launching a extension debug session. In this case the extension is never fully initialized and an error appears after 10 seconds. Additionally, after closing the debug instance of vscode the debug session is not closed and I have to manually stop it.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
numbered-bookmarks|ale|6.2.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
tslint|eg2|1.0.44
php-intellisense|fel|2.3.13
vscode-mysql|for|0.4.0
duk-debug|Har|0.5.0
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
svg|joc|1.0.2
vscode-phpfmt|kok|1.0.30
vscode-antlr4|mik|2.1.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.12.0
java|red|0.49.0
vscode-yacc|se2|1.1.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.19.0
vscode-maven|vsc|0.19.0

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

**Comment by mike-lischke** [comment]
Unfortunately, this is hard debug, because vscode doesn't do all the checks every time it starts up. Currently I see no issue, but I have seen this problem quite a few times before. Is it possible to force vscode to launch as if it wasn't launched for a while, so that it does all the checks in that case?

Side note: there is no `F1 > Developer: Restart With Extensions`, the closest that I could find is: `Reload Window with Extensions Disabled`, which only affects a single window.

**Comment by chrmarti** [comment]
This sounds like an extension might get hung up during startup. What is the error message you get after 10s?

**Comment by mike-lischke** [comment]
Hmm, you are pretty quick with closing issues :-/. I mentioned that this is tricky to reproduce, since this check is done at will by vscode. I cannot trigger it manually. So I have to wait until this comes up again to tell you what you want to know.

Also, I asked **you** to give me feedback:

> Is it possible to force vscode to launch as if it wasn't launched for a while, so that it does all the checks in that case?

which you completely ignored. Extensions don't play the main role here, for sure, because it doesn't happen all the time, but only when vscode does something in the background (indicated by that wait icon overlay on the Manage icon).

**Comment by chrmarti** [comment]
There is no way to tell it to do all checks. You could try with a new user data dir, because then it does not have any previous data: `code --user-data-dir=<path-to-new-folder>`.

**Comment by mike-lischke** [comment]
Thanks to reconsider the closing decision. Unfortunately your instruction didn't help to verify the problem. No attempt was made to check for updates or similar. The IDE was immediately ready for work.

I guess if there's nothing else how we can force vscode to behave like it does when updates are checked then we have no means to verify the issue. We will have to wait until it happens next time (which can be weeks from now). So I leave it to you to decide to close this issue, in which case I will open a new one, once I have more information, or to wait until this happens in this issue at hand.

**Comment by mike-lischke** [comment]
I have some news now, as today it happened again. First, the error message I see on the extension host is pretty well known:

> Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.

And I get an error in the debug console, when I waiting a while (the extension host was closed automatically):

> Error: connect ENOENT /var/folders/03/gj5f1gl92w11zc3l2c526dnm0000gn/T/vscode-ipc-43472bb2-2556-488c-821b-298afd286918.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

Then I tried again and reloaded the window with extensions disabled. This made it indeed work, but the funny thing is: extensions are not disabled, at least not the one I'm debugging. This time I also recreated the issue that the extension debugger hung. After some seconds it stopped here:

<img width="1199" alt="debugger-problem" src="https://user-images.githubusercontent.com/2398704/66297475-067a8a80-e8f0-11e9-8507-85f7fa8e1316.png">

and I got:

```
NodeError: Channel closed
    at process.target.send (internal/child_process.js:628:16)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5:802)
    at Console.true.process.env.VERBOSE_LOGGING.console.log (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5:894)
    at i.startExtensionHostProcess.catch.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:786:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at target.send.process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
The next test was to disable all my extensions, restart vscode and restart the extension debugging session. However, the same problem occured. The only extension that was active in this moment was the one I debugged (even though it said a reload would be required, which was a bit confusing). Also here: when I reloaded the window with extensions disabled, things started to work (well, in a way). My extension still was shown as requiring reload, though. And it was still active.

The functionality of the extension was available, but while I continued to write this comment the extension host was again auto closed and the debugger hung. I killed the session and restarted extension debugging, which now shows odd behavior. It opens an empty window and I have to reload the previous folder I used to test my extension. But even if it looked as if things would work, after about 90 seconds I got the same events.js error as mentioned above. I didn't do anything, but wrote on this comment here. Seems in the background vscode still was on a timeout, which then kicked in.

Hope this helps to debug this issue further for you.

**Comment by chrmarti** [comment]
Does this only occur when you are debugging your extension?

**Comment by bpasero** [comment]
@mike-lischke I am totally lost what your issue is. Can you explain to me in a short sentence, possibly with a screen cast or screen shots?

Here is what I think you see:
* you have a slow internet connection (that should not play a role for VSCode)
* you open VSCode
* after 10s you see a notification that the extension host did not start

Is that it?

**Comment by jrieken** [comment]
My understanding is that in-between 2 and 3 of @bpasero's steps you launch an extension in debug mode and that its extension host doesn't start in time

**Comment by mike-lischke** [comment]
> Does this only occur when you are debugging your extension?

I believe this also happens if I'm not debugging. Though, it's trickier to notice, since then you don't get any error message.

**Comment by mike-lischke** [comment]
@bpasero I have pretty exactly described what happened and for me it's pretty clear what the issue is: vscode hangs and doesn't behave well. To me it looks as if a connection is blocked which vscode is not ready to handle well. I don't know if it is something caused by my extension (vscode-antlr4), as it loads remote web content (3D.js) but only if a web view is openened, not earlier. Or if it is purely a vscode issue. In any case, when I close the VPN, things return immediately to normal and stay so for a while.

Unfortunately, the behavior of vscode seem to change from time to time. Today I recorded a screen cast, however the new experience I have with this issue is different than before (in some aspects), but the overall issue is still there. First, here's a video where the extension host auto closed after a minute: http://www.soft-gems.net/files/vscode1.mov

After that I recorded a short one where I closed the extension host manually, to try to pause the debugging session (which failed, however): http://www.soft-gems.net/files/vscode2.mov

**Comment by bpasero** [comment]
These videos are super helpful to understand the impact better, thanks. 

However, my expertise in the extension host does not go as far to be helpful. I am not even sure why `_tryExtHostHandshake` would take > 10s and under which condition that could be. Leaving up to Alex, sorry.

**Comment by alexandrudima** [comment]
Thanks @mike-lischke 

I think this error message is revealing:
```
Error: connect ENOENT /var/folders/03/gj5f1gl92w11zc3l2c526dnm0000gn/T/vscode-ipc-43472bb2-2556-488c-821b-298afd286918.sock
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

The extension host is a separate process and the extension host communicates back to the renderer process via a named pipe. Before launching the extension host process, the renderer process begins listening on a named pipe, which looks like `${TEMP}/vscode-ipc-${UUID}.sock`. The error message shows up in the debug console, so I think it is a message coming in from the broken extension host process. It appears that the broken extension host process cannot connect to the named pipe on which the renderer process is listening.

@mike-lischke Since you can trivially reproduce when enabling the VPN software and not when disabling it, my best guess is that your VPN software is intercepting all `connect()` system calls and, willingly or unwillingly, intercepts and blocks `connect()` system calls even to named pipes. Unfortunately, there is nothing we can do on our side if the two processes cannot talk to eachother and we correctly show an error box saying that the extension host did not start... well it did start but it did not talk back to the renderer process to let it know that it started...

Given what we know so far, I don't see any reasonable code change to do in VS Code except perhaps to do a dry-run connection from the renderer process to itself to test that `connect()` calls work correctly... But IMHO that is a bit overreacting as this is the first time we have gotten such an issue.

@mike-lischke Is it possible for you to look into the VPN software and check if it messes with named pipes? I would expect a lot of other software on your machine to have issues with that...

**Comment by mike-lischke** [comment]
Thanks @alexandrudima for your explanation. Yes, from the anamnesis it's clear it must have to do with the VPN software ([Cisco AnyConnect Mobility Client](https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/index.html?dtid=osscdc000283)). The point that confuses me is that sometimes it works ok. Once I started the debug session without VPN in place, everything works ok for a while. Only when I didn't debug an extension for a couple of days and then do it again with the VPN being active the described behavior shows up.

That seems to indicated that vscode can well cope with this situation and only sometimes (under some other condition) things start to act strangely.

Maybe one day you feel like digging deeper into this (or a similar) issue, but for now I think it's better to close this one here.

Thanks anyway.
