### ISSUE TITLE
Support using environment variables in settings.json

### ISSUE THREAD

**Issue by janegilring** [Microsoft/vscode#8147]
- VSCode Version: 1.2.1
- OS Version: Windows 10 (1511)

It would be nice to be able to use environment variables in paths in settings.json, this is not possible in build 1.2.1 and older.

In my scenariio I`m syncing VS Code settings between computers, for example:

// Specifies the path to a PowerShell Script Analyzer settings file. Use either an absolute path (to override the default settings for all projects) or use a path relative to your workspace.
    "powershell.scriptAnalysis.settingsPath": "%home%\\.vscode\\PSScriptAnalyzerSettings.psd1"

%home% is different on the computers VS Code is used on, thus it can`t be hardcoded.

**Comment by dbaeumer** [comment]
@bpasero not sure who owns the settings service right now. May be it is @aeschli

**Comment by dlebedynskyi** [comment]
I would really appreciate this feature for dotnet. 
be default launch is picking up environment variable from ASPNETCORE_URLS' and dotnet run on this  url. would be awesome to be able to specify this variable per process started

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2809
