### ISSUE TITLE
Screen shake

### ISSUE THREAD

**Issue by obedabit** [microsoft/vscode#81489]
Issue Type: <b>Bug</b>

I have a small shake in my Visual Studio Code fullscreen panel when I hover over anything that shows a Tooltip and I have the same problem when I hover over an icon on my windows taskbar, The shake goes away when stop hovering. 

![VS code Info](https://user-images.githubusercontent.com/54214435/65808956-103e1880-e1a1-11e9-8ef3-8604593d02c4.jpg)
![Windows Info](https://user-images.githubusercontent.com/54214435/65808976-4380a780-e1a1-11e9-8481-3f37c930b999.jpg)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.01GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.2
vsc-material-theme|Equ|30.0.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|3.9.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.18
bootstrap4-vscode|the|6.1.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please provide screenshot, information about VS Code version and OS version?
Is it reproducible with all extensions disabled?

**Comment by obedabit** [comment]
I have updated the report

> /needsMoreInfo
> 
> Could you please provide screenshot, information about VS Code version and OS version?
> Is it reproducible with all extensions disabled?

I have updated the report information

**Comment by bpasero** [comment]
@obedabit I am not seeing it?

**Comment by chrmarti** [comment]
@obedabit Note that you are on an older version of VS Code, please update. Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

**Comment by obedabit** [comment]
> @obedabit Note that you are on an older version of VS Code, please update. Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/
> 
> Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

I have updated to the latest version of VS code and still have the same problem, I have also tried to disable all my extension and still have a shake in my VS code fullscreen panel.
I have tried the VS code Insiders version and the problem disappeared.

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/81644
