### ISSUE TITLE
Python Interactive window should support raw_input

### ISSUE THREAD

**Issue by hantusk** [microsoft/vscode#81481]
Python Interactive window does not support raw_input() in the ipython session, which is standard in ipython. Enabling support for this would allow for `%debug` magic, the `getpass` stdlib module and a minimum level of interactivity without spinning up a separate interpreter.

Is this possible to add?

see also #11103, #75649, #76464 which were closed without being resolved.

**Comment by chrmarti** [comment]
Please file an issue for the Python extension: https://github.com/microsoft/vscode-python/issues/new/choose
