### ISSUE TITLE
integrated terminal  is always full-width show

### ISSUE THREAD

**Issue by mrwenhui** [microsoft/vscode#81480]
- VSCode Version:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic
- OS Version:
Linux dwh-OptiPlex-7060 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
OS Language:  
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
Steps to Reproduce:

1.Open VS Code
2.Open up the integrated terminal
3. ls

Does this issue occur when all extensions are disabled?: Yes/No
Yes.
![图片1](https://user-images.githubusercontent.com/2619942/65682529-b698f980-e08d-11e9-83c1-ade20dfb7d9c.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide exact expectations and what's the problem?
Is it font/characters layout or anything else?
