### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Screenreader: After activating the popup "Recompare" NVDA announces "Option button first". 

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode#81484]
“[Check out Accessibility Insights](https://accessibilityinsights.io/)! - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #MAS2.4.2; #MAS1.3.2; #NVDA; #Jaws;

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Additional Details:**
Screen reader  : NVDA 2019.2.rc2, Jaws
MAS reference: MAS2.4.2 MAS1.3.2

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Options menu from Schema compare Menu bar & hit enter.
12. Check or uncheck some options & hit Ok.
13. Validate Re compare pop will open
14. Start NVDA and check how it read the information.

**Actual:**
After activating the popup "Re-compare" NVDA reads the information as "Button Options warning Option has changed..." which is not correct.

Same issue is observed with Jaws

**Expected:**
After activating the popup nvda should read the information as "Options has changed ….. Dialog/Alert/Popup "

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader user will not know the information about the dialog.

**MAS Reference:**
MAS2.4.2:[https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={c74ff881-82b6-4401-92cf-8919f9bffaf2}](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={c74ff881-82b6-4401-92cf-8919f9bffaf2})

 MAS1.3.2:[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4})

**Attachment for Reference:**
![6663_ Accessibility A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Screenreader](https://user-images.githubusercontent.com/24580570/62777993-c607b780-bacc-11e9-9118-f0b595198d75.png)

**Comment by chrmarti** [comment]
@fsteffi Should this issue be moved to a different repository?

**Comment by hannahqin** [comment]
@chrmarti This bug was originally filed under Azure Data Studio, but we found the issue to be upstream from vscode https://github.com/microsoft/azuredatastudio/issues/6663

**Comment by isidorn** [comment]
@hannahqin if you think this is an issue in vscode please file the issue in concise steps in humand readable form.  Do not just copy paste it from your extension, please put some effort into this.
Do not mention the Azure Data Srouce extension in your reproducable steps. 
Thank you for your understanding.
