### ISSUE TITLE
Insiders opening "C:\Program Files\Microsoft VS Code Insiders\resources\app\out\cli.js" after every few mins automatically.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#81487]
Issue Type: <b>Bug</b>

Insiders opening "C:\Program Files\Microsoft VS Code Insiders\resources\app\out\cli.js" after every few mins automatically.
A new window is opened every few minutes with "C:\Program Files\Microsoft VS Code Insiders\resources\app\out\cli.js" file opened in it.

VS Code version: Code - Insiders 1.39.0-insider (b0d714d2de2886060e0904bf0cc774e0d70667cd, 2019-09-26T09:07:24.281Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: angular_serve|
|OS|Linux x64 4.15.0-64-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge, IBRS update) (4 x 2399)|
|Memory (System)|7.79GB (4.58GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
gitlens|eam|10.0.1
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.2.2
kite|kit|0.98.0
vscode-azureappservice|ms-|0.16.0
python|ms-|2019.9.34911
remote-containers|ms-|0.77.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.7
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
powershell|ms-|2019.9.0
typescript-javascript-grammar|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.2
cordova-tools|msj|1.8.6
debugger-for-chrome|msj|4.12.0
vscode-spring-boot|Piv|1.11.0
fabric8-analytics|red|0.0.13
java|red|0.49.0
vscode-xml|red|0.9.0
vscode-yaml|red|0.5.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
WebTemplateStudio-dev-nightly|WAS|0.0.1925201

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

**Comment by sanket-bhalerao** [comment]
@chrmarti yes, this issue is replicated after disabling all the extensions.

**Comment by sanket-bhalerao** [comment]
I re-installed the Insiders build, but the problem is still there.
I have user installation, 
I run the app as administrator.
Is anyone else facing this issue?

**Comment by chrmarti** [comment]
@sanket-bhalerao Could you compare with the current stable release 1.38.1? Does it occur there too?

**Comment by sanket-bhalerao** [comment]
@chrmarti i am facing this issue with the stable release.
however, the popup that requests the permission is for insiders.
screenshot for reference.

![issue](https://user-images.githubusercontent.com/9264813/65887490-9df55000-e3bb-11e9-9ad2-95dfde656635.png)

**Comment by chrmarti** [comment]
@sanket-bhalerao Can you uninstall VS Code Insiders?

**Comment by sanket-bhalerao** [comment]
@chrmarti let me try.
i have also removed the .insiders directory which contains the extentions.

**Comment by sanket-bhalerao** [comment]
after re-installing insiders, the issue did not reappear.
