### ISSUE TITLE
Extensions: Double scroll bar on Windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8148]
<img width="258" alt="screen shot 2016-06-26 at 09 20 44" src="https://cloud.githubusercontent.com/assets/900690/16361002/4edb227a-3b7f-11e6-9e9c-0e68c191c42b.png">

This looks super bad and we should use the custom scroll bar if possible for the inner scroll bar and the outer scrollbar should just be hidden via CSS if possible.

@isidorn if you have cycles next week, moving to you.

**Comment by isidorn** [comment]
Dup of #7970 which Joao fixed on friday - I verified and it now looks good on win

**Comment by bpasero** [comment]
Nice!
