### ISSUE TITLE
Split terminal icon should show vertical split when the panel is on the right

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#81491]
Issue Type: <b>Bug</b>

Full screen editor, with Terminal taking 1/3 of the 1920 screen, button as in screenshot suggests Terminal will be split into two vertical side-by-side panes. In fact it correctly splits into horizontal panes (one above the other).

![image](https://user-images.githubusercontent.com/512816/65691820-d28ea200-e071-11e9-8209-1915547cb3bd.png)

VS Code version: Code - Insiders 1.39.0-insider (817eb6b0c720a4ecbc13c020afbbebfed667aa09, 2019-09-25T05:28:51.690Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
remote-wsl|ms-|0.39.6

</details>

**Comment by Tyriar** [comment]
@misolori do we have a vertical split icon?

**Comment by leegee** [comment]
You use one in the monthly stable release, as in the screenshot below:

![image](https://user-images.githubusercontent.com/512816/65725162-4c468000-e0b2-11e9-94fc-dd8b1de2a82e.png)

**Comment by misolori** [comment]
This was on oversight on my part, fixed it now.

When panel is at bottom:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/35271042/65725616-f5b45400-e067-11e9-9163-f2a2a2b0fd4e.png">


When panel is on right:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/35271042/65725642-01a01600-e068-11e9-824f-ca6228440215.png">

**Comment by Tyriar** [comment]
@misolori thanks!
