### ISSUE TITLE
Extensions: bring back the separator from debug to extensions viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8149]
I actually liked the separator because it made it very clear that extensions have nothing to do with the inner-loop of development.

I am not sure why it was removed in the first place.

**Comment by isidorn** [comment]
I did not like the separator visually and I thought the extensions being on the end of the list is a clear enough of an indication. Thus I gave negatvie feedback to joao regarding the seperator.
Not sure if that influenced his decision to remove it.

If you have strong feeling about it - I will bring it back

**Comment by bpasero** [comment]
@isidorn lets talk in the UX meeting.

**Comment by bgashler1** [comment]
I personally don't like the look of it, even though I get the argument for it.  There's also another reason why I don't think we should put it there (which I'll post on Slack).

**Comment by isidorn** [comment]
As far as voting goes we are 3 against 1 for not using the seperator -> thus I am moving this to july, joao so he can decide. So we are shipping without the seperator, later it is easier to add it then to remove it.

**Comment by joaomoreno** [comment]
Well... although I agree with @bpasero, I will simply close this since I removed it because I got another issue that was the exact opposite of this, and Machete don't jump back and forward. Only forward.
