### ISSUE TITLE
Extension host terminated unexpectedly. Code:  7  Signal:  null

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [microsoft/vscode#81494]
Out of nowhere it stopped working. As far as I know it didn't even update VSCode. All warnings and errors bellow:

<details>
<summary>Details</summary>
<h3>WARNING 1:</h3>

/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165 

Overwriting grammar scope name to file mapping for scope text.log.

Old grammar file: file:///c%3A/Users/gabri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/log/syntaxes/log.tmLanguage.json.

New grammar file: file:///c%3A/Users/gabri/.vscode/extensions/emilast.logfilehighlighter-2.5.0/syntaxes/log.tmLanguage

register @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165

<h3>WARNING 2:</h3>
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165 

Overwriting grammar scope name to file mapping for scope source.java.

Old grammar file: file:///c%3A/Users/gabri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.

New grammar file: file:///c%3A/Users/gabri/.vscode/extensions/georgewfraser.vscode-javac-0.2.27/lib/java.tmLanguage.json

register @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165 

<h3>WARNING 3:</h3>
Overwriting grammar scope name to file mapping for scope source.yaml.

Old grammar file: file:///c%3A/Users/gabri/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.

New grammar file: file:///c%3A/Users/gabri/.vscode/extensions/pivotal.vscode-spring-boot-1.11.0/yaml-support/yaml.tmLanguage

register @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165

<h3>WARNING 4:</h3>
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165 

Overwriting grammar scope name to file mapping for scope source.java-properties.

Old grammar file: file:///c%3A/Users/gabri/.vscode/extensions/ithildir.java-properties-0.0.2/syntaxes/java-properties.tmLanguage.
New grammar file: file:///c%3A/Users/gabri/.vscode/extensions/pivotal.vscode-spring-boot-1.11.0/properties-support/java-properties.tmLanguage

register @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4165
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420 

<h3>ERROR 1 (GIVES OUT A CODE 7, WHAT'S THIS?):</h3>
Extension host terminated unexpectedly. Code:  7  Signal:  null

_onExtensionHostCrashed @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420
extensionHost.ts:202

Extension Host
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3577 
c:\Users\gabri\.vscode\extensions\georgewfraser.vscode-javac-0.2.27\node_modules\web-tree-sitter\tree-sitter.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBina
abort({"errno":"UNKNOWN","code":"UNKNOWN","syscall":"spawn"}). Build with -s ASSERTIONS=1 for more info.

<h3>ERROR 2 :</h3>
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420 

Extension host terminated unexpectedly. Code:  7  Signal:  null

_onExtensionHostCrashed @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420
extensionHost.ts:202 

Extension Host
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3577 
c:\Users\gabri\.vscode\extensions\georgewfraser.vscode-javac-0.2.27\node_modules\web-tree-sitter\tree-sitter.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBina
abort({"errno":"UNKNOWN","code":"UNKNOWN","syscall":"spawn"}). Build with -s ASSERTIONS=1 for more info.

<h3>ERROR 3:</h3>
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420 

Extension host terminated unexpectedly. Code:  7  Signal:  null

_onExtensionHostCrashed @ /C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3420
extensionHost.ts:202

Extension Host
/C:/Users/gabri/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3577 
c:\Users\gabri\.vscode\extensions\georgewfraser.vscode-javac-0.2.27\node_modules\web-tree-sitter\tree-sitter.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBina
abort({"errno":"UNKNOWN","code":"UNKNOWN","syscall":"spawn"}). Build with -s ASSERTIONS=1 for more info.

</details>

**Comment by chrmarti** [comment]
This looks like it might be caused by that javac extension which published an update two days ago. Could you file this for: https://github.com/georgewfraser/java-language-server

**Comment by Gabriel-Alves-Cunha** [comment]
Thanks for the help!!
