### ISSUE TITLE
Wrong character encoding with UTF-8 BOM (for g) file-encoding 

### ISSUE THREAD

**Issue by SrikantPrasad** [microsoft/vscode#81490]
Hi Team
 Currently we are facing an issue where the g with accent (i:0ǵ.t) in powershell is changing to i:0Çµ.t, which is creating an issue, when we run the DSC on sharepoint, because the claim value changes for the user account.

**Comment by SrikantPrasad** [comment]
[484DDA19-0F9E-47D1-B921-C83726D84E1E.zip](https://github.com/microsoft/vscode/files/3657970/484DDA19-0F9E-47D1-B921-C83726D84E1E.zip)
More videos attached.

**Comment by chrmarti** [comment]
@SrikantPrasad You have filed this issue with VS Code. Should this be filed with PowerShell or the PowerShell terminal?

**Comment by SrikantPrasad** [comment]
Hi Christof,
Please see the attached video in zip. Ths issue happens when I write powershell on VSCode and try to copy on my VM and execute on powershell ISE.

**Comment by chrmarti** [comment]
I'm not sure I understand where it gets corrupted. When I create a UTF-8 file in VS Code with ǵ, it gets stored as `c7 b5` which is correct according to http://www.fileformat.info/info/charset/UTF-8/list.htm.

**Comment by Jocorteslopez** [comment]
Hello Chris,

this problem was reported to the group of SharePoint DSC here: https://github.com/PowerShell/SharePointDsc/issues/1110  and we were able to determine that the issue was with VSCode and not poweshell. I think if you can get in touch with Yorick Kuijs ( @ykuijs ) we determined the same with a simple scenario comparing the result from Notepad and VsCode

**Comment by Jocorteslopez** [comment]
I took your suggestion and analyzed a very simple scenario. Created to files: 
-test.ps1: Created with VSCode in UTF-8 encoding and the only content of the file is the character **ǵ**
-test2.ps1: Created with NotePad in UTF-8 encoding and the only character of the file is the character **ǵ**

If I open test.ps1 with PowerShell ISE I don't see the **ǵ** but instead I see **Çµ**.
If I open test2.ps1 with PowerShell ISE I see the **ǵ**

So my next step was to analyze the two files with Hexadecimal editor:

- test.ps1 Hexadecimal content is: C7 B5
- test2.ps1 Hexadecimal content is:  EF BB BF C7 B5

So when we are talking about UTF-8, the way is encoding in Notepad and Powershell understands  is UTF-8 with BOM but VSCode editor we need to ensure we "Save with Encoding UTF-8 With BOM" 

Found reference here: https://github.com/Microsoft/vscode/issues/44005

So I think we can close this now
