### ISSUE TITLE
Terminal hangs when typing a command

### ISSUE THREAD

**Issue by domenkozar** [microsoft/vscode#81499]
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.71
```

Steps to Reproduce:

1. Type `cachix push --help` into terminal and get the following output:

```
Usage: cachix push [--compression-level [0..9]] NAME ([PATHS...] |
                   [-w|--watch-store])
  Upload Nix store paths to the binary cache

Available options:
  -h,--help                Show this help text
  --compression-level [0..9]
                           The compression level for XZ compression. Take
                           compressor *and* decompressor memory usage into
                           account before using [7..9]! (default: 2)
  -w,--watch-store         Run in daemon mode and push store paths as they are
                           added to /nix/store
```
2. Observe that window hangs
3. Task manager shows that current file memory grows from 300MB to 2GB and CPU goes up to 70%
4. `Window is no longer responding`

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

**Comment by domenkozar** [comment]
I can not use Insiders, is there something else I can do?

**Comment by Tyriar** [comment]
> Task manager shows that current file memory grows from 300MB to 2GB and CPU goes up to 70%

What is the current file? Can you show a screenshot of this?

**Comment by domenkozar** [comment]
before

![2019-09-27-101707_581x249_escrotum](https://user-images.githubusercontent.com/126339/65753854-218b1480-e110-11e9-9873-a46ed4e51208.png)

after

![2019-09-27-101756_612x229_escrotum](https://user-images.githubusercontent.com/126339/65753853-218b1480-e110-11e9-8f4f-15c678fb5248.png)

**Comment by Tyriar** [comment]
Does typing in the terminal slow things as well? Does this setting change things?

```
"terminal.integrated.rendererType": "dom"
```

**Comment by prokher** [comment]
I experience the same issue as @domenkozar explained. The open file does not matter. This happens even if there is no one.

![VS Code terminal freezes](https://user-images.githubusercontent.com/399393/66116958-48e45480-e5dc-11e9-8bea-f51790b77541.gif)

Please note, that I typed in console commands blazingly fast, it renders letter by letter with approx. 1 sec delay. Also note, that closing terminal panel makes VS Code fast again. And the last thing to note is that it does not happen all the time. If I restart VS Code it runs OK. I experience this approximately once a day.

Switching to the DOM renderer seems to help. I did this and everything became fine even without restarting VS Code.

.

**Comment by Tyriar** [comment]
I suspect this is the electron 4 canvas regression here https://github.com/microsoft/vscode/issues/81047. We're working on updating to v6 but in the meantime you can use the dom renderer.

/duplicate https://github.com/microsoft/vscode/issues/81047
