### ISSUE TITLE
Change terminal font family to nerd font

### ISSUE THREAD

**Issue by engmagdy87** [microsoft/vscode#81497]
when i change terminal font family to "**Hack Nerd Font**", the terminal appears like this
![image](https://user-images.githubusercontent.com/8473421/65700343-cd385400-e07f-11e9-9d02-d3cb32a09aea.png)

**Comment by chrmarti** [comment]
/needsMoreInfo

Is this a monospaced font?

**Comment by Tyriar** [comment]
What's it meant to look like? What do other terminals look like when using this font?

**Comment by engmagdy87** [comment]
@Tyriar 
![Screenshot-20190929125324-723x141](https://user-images.githubusercontent.com/8473421/65831272-2f7b9980-e2b8-11e9-99e9-b406597800f7.png)

**Comment by Tyriar** [comment]
Can you share your settings?

**Comment by engmagdy87** [comment]
@Tyriar 
{
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "terminal.integrated.fontFamily": "\"MesloLGM Nerd Font\"",
  "rest-client.fontFamily": ""
}

**Comment by Tyriar** [comment]
This isn't valid json:

```
"terminal.integrated.fontFamily": ""MesloLGM Nerd Font"",
```

Try:

```
"terminal.integrated.fontFamily": "'MesloLGM Nerd Font'",
```

Or

```
"terminal.integrated.fontFamily": "MesloLGM Nerd Font",
```

Also weren't you using Hack Nerd Font?

**Comment by engmagdy87** [comment]
I try
"'Hack Nerd Font'" and "Hack Nerd Font"
this message appears
![Screenshot-20191003022002-481x107](https://user-images.githubusercontent.com/8473421/66090599-756c8200-e584-11e9-9e62-d2e74c6c071a.png)

**Comment by Tyriar** [comment]
@engmagdy87 does it seem to work if you ignore that? That message should only display is the `i` and `W` characters differ in size when printed by Chromium

**Comment by engmagdy87** [comment]
doesn't work

**Comment by Tyriar** [comment]
If you add this setting:

```
"terminal.integrated.rendererType": "dom"
```

And then inspect a problem cell via devtools (Help menu), what's the font-family listed under computer CSS properties?

**Comment by engmagdy87** [comment]
![image](https://user-images.githubusercontent.com/8473421/66479534-0370cd00-ea9d-11e9-91a9-67758fefe830.png)

**Comment by Tyriar** [comment]
That's `<body>` can you inspect a terminal cell? That should tell you what the font is for the cell.

**Comment by engmagdy87** [comment]
![Screenshot-20191010161738-552x954](https://user-images.githubusercontent.com/8473421/66577404-9aab5280-eb79-11e9-8afa-81b6fbc03b9a.png)

**Comment by Tyriar** [comment]
@engmagdy87 I see `font-family: mMesloLGLpace`, is that what you set `terminal.integrated.fontFamily` to?

**Comment by engmagdy87** [comment]
mMesloLGLpace

**Comment by Tyriar** [comment]
@engmagdy87 where do you download that one?

**Comment by engmagdy87** [comment]
@Tyriar thx for u help
I change font to "Hack Nerd Font **Mono**" NOT "Hack Nerd Font"
