### ISSUE TITLE
Web: implement browser extension debug service properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81493]
Currently https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts is bypassing the host API and uses `window.open` to open a extension host debug window. Instead, we need to make sure to pass this on to the embedder. 

(not critical for September, but wanted to set the milestone to have it "on deck")

**Comment by bpasero** [comment]
One possible idea to start with: use `IHostService.openInWindow` API. Probably would need to be enriched for the additional things to wire in. We can also think about having a separate method for this.

Ideally both implementations (desktop + web) would use the same method with different implementations.

**Comment by bpasero** [comment]
I am also not sure about the `window.close()` call. I don't think you can close a `window` from itself, rather you would need to get hold off the `window` from the previous `window.open()` call. We can think about adding API for that purpose to the host service.

**Comment by isidorn** [comment]
Will not do this in endgame week, this is great for debt week -> next milestone.
