### ISSUE TITLE
Conflicts not Appearing

### ISSUE THREAD

**Issue by oyb1n** [microsoft/vscode#81501]
Issue Type: <b>Bug</b>

Hi, 

I'm running posh-git in addition to visual studio code. 
When i do git merge <branch> I get the following 
"Automatic merge failed; fix conflicts and then commit the result."

That's okay. And in the source control panel, i get one conflict under "Merge changes". 
![image](https://user-images.githubusercontent.com/23700846/65708734-8b170e80-e08f-11e9-96d6-1137fa14801d.png)

However when I open the file, no conflicts appear. I have the code lens setting turned on. In addition if i try to do "Merge Conflict: Next Conflict", I get the error "No merge conflicts found in this file". When clearly there is a conflict showing in the merge changes window. 

If i open the folder in Visual Studio 2019, it has no problems finding the merge conflict. This has now happened on different VSCode editions and on different machines. The one I have trouble with now is a newly provisioned VM. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.0.1
vscode-guid|hea|1.4.18
powershell|ms-|2019.9.0

(1 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
What's the text of the merge conflict? Maybe you have a variation we don't match yet.
