### ISSUE TITLE
PowerShell Suggestion for 'else' is a program in the windows folder?

### ISSUE THREAD

**Issue by kevintbrown** [microsoft/vscode#81509]
Issue Type: <b>Bug</b>

Disable PowerShell Snippets via this setting value:
   "editor.snippetSuggestions": "none"

(this is because the built in else snipped puts the brace on the same line, which I don't like)

Create a PowerShell ps1 file.
Start writing code, write an if block, i.e.

    if ($foo)
    {
    }

Close your if block, write the word else:

VSCode is popping up a suggestion "esentutl.exe"

When I press Enter to move to the next line, because I like to put my open brace on the line following the keyword "else", VSCode decides it would like to replace "else" with "esentutl.exe "

This breaks my scripts, and it feels like VSCode is being discriminatory against me as a dev because I like my open braces on the next line instead of the same line.

How do I disable these suggestions but still keep intellisense for variable names?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (12.97GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.7.1
prettify-json|moh|0.0.3
mssql|ms-|1.6.0
csharp|ms-|1.21.3
powershell|ms-|2019.9.0
control-snippets|svi|1.3.0
vim|vsc|1.10.2

</details>

**Comment by kevintbrown** [comment]
This is my experience:

![image](https://user-images.githubusercontent.com/28372754/65714736-8ed77080-e050-11e9-97c2-a3f3a95a50c5.png)

![image](https://user-images.githubusercontent.com/28372754/65714768-9d258c80-e050-11e9-82df-4f6840662051.png)

![image](https://user-images.githubusercontent.com/28372754/65714782-a1ea4080-e050-11e9-8f53-75502adcc0a4.png)

**Comment by chrmarti** [comment]
Try turning it off in the settings:
![image](https://user-images.githubusercontent.com/9205389/65750465-c0137780-e108-11e9-83de-5ca78083b2cf.png)

Does that help?

**Comment by kevintbrown** [comment]
Ah I had changed the option to Accept Suggestion on Commit Character, but hadn't seen the on Enter one, that's fixed it, thanks!
