### ISSUE TITLE
I am not getting suggest 

### ISSUE THREAD

**Issue by aslamsk** [microsoft/vscode#81506]
I am not getting suggestions while typing code on visual studio code so how can I fix it....![20190926_232612](https://user-images.githubusercontent.com/54580538/65713210-59656e00-e0b6-11e9-9f62-794dc0cb8e30.png)

- VSCode Version: latest 2019.. 
- OS Version: ubantu

Steps to Reproduce:

1. Not getting suggestions 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?
