### ISSUE TITLE
Regex "replace in files" group substitution does not work

### ISSUE THREAD

**Issue by clmay** [microsoft/vscode#81502]
- VSCode Version: 1.38.1
- OS Version: 10.14.6

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. Open "Replace in files"
1. Perform a regex search that includes a group, e.g.:

    ```
    (some_var).method_to_replace(args)
   ```

1. Perform replace using group substitution, e.g.:

    ```
    $1.new_method$2
    ```

Expected results:

```
some_var.new_method(args)
```

Actual result:

```
$1.new_method$2
```

Does this issue occur when all extensions are disabled?: Yes

It is worth noting that the expected results listed above are the _exact_ behavior of the local find and replace feature, but this is for some reason not extended to the project-wide find and replace feature.

**Comment by ArturoDent** [comment]
When I use this search regex it works as expected:

`(some_var)\.method_to_replace(\(args\))`

Do you have a different example where it doesn't work and is unrelated to these fixes:

https://github.com/microsoft/vscode/issues/81129
https://github.com/microsoft/vscode/issues/80667

since your example did not include a newline or lookaround?

**Comment by clmay** [comment]
No, I'm sorry. I was not aware of #80667 and the actual regex I was using did include a newline. I will close this issue, but it does seem that the name of the other could be improved.

**Comment by clmay** [comment]
@ArturoDent when will the fix for #80667 be released?

**Comment by ArturoDent** [comment]
It is already in the Insider's Build so "should" be in the next release - early October 2019.

**Comment by clmay** [comment]
Thank you.
