### ISSUE TITLE
space bar not working

### ISSUE THREAD

**Issue by MoslemParve** [microsoft/vscode#81508]
Issue Type: <b>Bug</b>

Recently I updated my VScode and  when I start editing my code I was not able to add a space with the help of the spacebar instead of that I have to press shift+spacebar, which is quite a lot of work to do every time

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

(Note that you are on an older version of VS Code, please update to the latest.)

**Comment by MoslemParve** [comment]
> /needsMoreInfo
> 
> Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)
> 
> (Note that you are on an older version of VS Code, please update to the latest.)
yes this occur with all extensions disabled..no i am on latest version but it is not working may be it is due to OS.

**Comment by MoslemParve** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

it was working well before os updates..after that it is creating the issue..i checked it by reinstalling many times but it is not fixing the problem

**Comment by alexandrudima** [comment]
@MoslemParve Can you please try to disable all your extensions? Also, can you please try removing all your custom keybindings in your `keybindings.json` ?

**Comment by MoslemParve** [comment]
> @MoslemParve Can you please try to disable all your extensions? Also, can you please try removing all your custom keybindings in your `keybindings.json` ?

i tried but its not working.

**Comment by alexandrudima** [comment]
@MoslemParve Can you please check your `keybindings.json` by running `F1` > `Preferences: Open Keyboard Shortcuts (JSON)` and paste it here...

**Comment by MoslemParve** [comment]
> @MoslemParve Can you please check your `keybindings.json` by running `F1` > `Preferences: Open Keyboard Shortcuts (JSON)` and paste it here...

// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "space ctrl+s",
        "command": "workbench.view.debug"
    },
    {
        "key": "ctrl+shift+d",
        "command": "-workbench.view.debug"
    },
    {
        "key": "ctrl+shift+d",
        "command": "editor.action.copyLinesDownAction",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "shift+alt+down",
        "command": "-editor.action.copyLinesDownAction",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+shift+tab ctrl+shift+w",
        "command": "breadcrumbs.revealFocused",
        "when": "breadcrumbsActive && breadcrumbsVisible"
    },
    {
        "key": "space",
        "command": "-breadcrumbs.revealFocused",
        "when": "breadcrumbsActive && breadcrumbsVisible"
    },
    {
        "key": "ctrl+shift+alt+z",
        "command": "debug.toggleBreakpoint",
        "when": "breakpointsFocused && !inputFocus"
    },
    {
        "key": "space",
        "command": "-debug.toggleBreakpoint",
        "when": "breakpointsFocused && !inputFocus"
    },
    {
        "key": "ctrl+shift+alt+x",
        "command": "list.toggleExpand",
        "when": "listFocus && !inputFocus"
    },
    {
        "key": "space",
        "command": "-list.toggleExpand",
        "when": "listFocus && !inputFocus"
    },
    {
        "key": "ctrl+shift+alt+",
        "command": "notification.toggle",
        "when": "notificationFocus"
    },
    {
        "key": "space",
        "command": "-notification.toggle",
        "when": "notificationFocus"
    },
    {
        "key": "backspace ctrl+shift+space",
        "command": "editor.action.triggerParameterHints",
        "when": "editorHasSignatureHelpProvider && editorTextFocus"
    },
    {
        "key": "ctrl+shift+space",
        "command": "-editor.action.triggerParameterHints",
        "when": "editorHasSignatureHelpProvider && editorTextFocus"
    },
    {
        "key": "ctrl+alt+up",
        "command": "-editor.action.insertCursorAbove",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+down",
        "command": "-editor.action.insertCursorBelow",
        "when": "editorTextFocus"
    },
    {
        "key": "shift+backspace",
        "command": "-deleteLeft",
        "when": "textInputFocus && !editorReadonly"
    }
]

**Comment by alexandrudima** [comment]
@MoslemParve Can you please comment out or delete those entries? That should bring back the default keybindings of VS Code.

**Comment by MoslemParve** [comment]
@alexandrudima  thanku 👍
