### ISSUE TITLE
Font ligatures that start with < do not work in HTML documents

### ISSUE THREAD

**Issue by vaindil** [microsoft/vscode#81504]
Issue Type: <b>Bug</b>

Any character combination that starts with a `<` character does not trigger a font ligature in HTML documents. The only exception is `<!--`. As far as I can tell this is a VS Code thing, not a font thing, because the ligature works properly everywhere else I've tested. I have no extensions enabled and am on the latest preview. In case it helps, I'm using Fira Code 2.0.

![image](https://user-images.githubusercontent.com/771134/65710941-f2b66500-e061-11e9-9d82-43d3b4b52b1f.png)

VS Code version: Code - Insiders 1.39.0-insider (b0d714d2de2886060e0904bf0cc774e0d70667cd, 2019-09-26T09:07:24.281Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (17.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexandrudima** [comment]
@vaindil This is ultimately controlled by the grammar/theme combination. If there are different colors between characters, they will be rendered separately and the ligatures will not apply to them. You can write custom theme rules in your settings to overwrite the theme ones and ensure adjacent characters that you want have the same color / font style, and then they will be rendered in a single `<span>` and ligatures will kick in...

**Comment by vaindil** [comment]
Ah, I understand. Sorry for the bad issue, and thank you!
