### ISSUE TITLE
Negative patterns in exclude settings

### ISSUE THREAD

**Issue by ShimShamSam** [microsoft/vscode#81503]
Issue Type: <b>Bug</b>

The search indexer (ripgrep?) seems to index the entire project before performing a search even if the "files to include" option excludes 99% of the file tree. After indexing is complete, search results are nearly instant, but the index seems to be invalidated at least a couple times a day (I'm not sure what the mechanism is).

Our codebase at work contains at least 10k files, and performing a global search on it literally slows my mouse down if the index has to be rebuilt.

Would it be feasible/faster to glob the "files to include" option first, build a list of files to search, then search only those files?

If not, is there something I can do to prevent the index from being invalidated so often?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
blamer-vs|bea|0.5.0
vscode-intelephense-client|bme|1.2.3
RunOnSave|eme|0.2.0
gc-excelviewer|Gra|2.1.32
svelte-vscode|Jam|0.9.2
sftp|lix|1.12.9
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
vscode-remote-extensionpack|ms-|0.17.0
partial-diff|ryu|1.4.0
explorer-excluded-files|sad|1.0.0
code-settings-sync|Sha|3.4.3
better-align|wwm|1.1.6

</details>

**Comment by chrmarti** [comment]
Do you mean text search across files? Make sure to use the "search exclude" setting, that appears to affect performance more than the includes.

**Comment by ShimShamSam** [comment]
@chrmarti Yes, I'm referring to searching across all files in a project. I wasn't sure what the official name was.

Blacklisting all folders except one is incredibly cumbersome. I would even say it's practically impossible if the folder you want to search within is deeply nested within a highly branched file tree structure.

**Comment by roblourens** [comment]
`files to include` (in the search viewlet) doesn't affect file search (quick open), just text search. You're right that it would be a pain to get the behavior you want with `search.exclude`. I think this is an advanced feature request.

I can show you an undocumented feature that is supported by ripgrep which powers our search. You can add a `.ignore` file to your project which supports the same types of patterns as a gitignore, e.g. so you can use things like negative patterns which make this easier. Just make sure you read carefully about how negative patterns work. https://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder

**Comment by ShimShamSam** [comment]
> files to include (in the search viewlet) doesn't affect file search (quick open), just text search.

@roblourens I am referring to text search across all files in a project

**Comment by roblourens** [comment]
Oh ok I assumed file search because you mentioned "indexing" but there is no indexing in text search. Most likely you are seeing the effect of Windows Defender or another antivirus which can slow down the first search. 

Typically ripgrep has to walk the tree or most of the tree to figure out whether a glob pattern matches. If you use the syntax `./foo/bar` to search a specific folder, then you should see a faster search. Let me know if that doesn't help.

My other comments about `.ignore` and negative patterns still apply.

**Comment by ShimShamSam** [comment]
@roblourens Adding the following process exclusion to Windows Defender solved it:

`C:\Users\*\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe`

This likely affects a lot of users, so it might be worth including it in the [FAQ](https://code.visualstudio.com/docs/supporting/faq).

It's worth noting that the `%LocalAppData%` path variable usually used for stuff like this didn't work for me when adding the exclusion (bug?), but I think wildcarding `C:\Users\*\...` is fairly secure. Any thoughts?

**Comment by roblourens** [comment]
That's great that it worked for you, I have had mixed success and sometimes have to exclude the actual workspace as well. In general I don't think it's a good idea for us to tell everyone to go adding Defender exclusions, seems unsafe.

**Comment by ShimShamSam** [comment]
Perhaps instead of directly recommending an exclusion, just explain that it could be Windows Defender/Antivirus slowing down the process and let the user decide what to do from there. It would certainly have pointed me in the right direction.

**Comment by roblourens** [comment]
I don't think it's common enough to add to the general FAQ but I do mention it in the search troubleshooting wiki: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory maybe I should find a spot for it in the real docs though.

**Comment by ShimShamSam** [comment]
> I don't think it's common enough to add to the general FAQ
Wouldn't this affect all Windows users? Or do you mean most projects aren't large enough for this to take effect?

**Comment by roblourens** [comment]
I have to stick with my answer that it's not safe to tell people to disable their antivirus.
