### ISSUE TITLE
Terminal search upwards is broken again

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#81510]
The same as #73459
Will later attach reproducible example

- VSCode Version: 1.38.1
- OS Version: kubuntu 19.04

Steps to Reproduce:

1. Search for some word upwards
2. Then downwards, you will find skipped entries

PS The output contained very long lines and colors

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Please provide a more detailed repro.

**Comment by Yanpas** [comment]
STR:
1. Open terminal, cat attached file
2. Search for `opencv` upwards, then downwards
3. If you search downwards you will notice that search finds `...contrib/opencv-3...`
[Untitled-1.txt](https://github.com/microsoft/vscode/files/3680624/Untitled-1.txt)

**Comment by Tyriar** [comment]
I am seeing some weird behavior:

- Searching upwards (enter) is skipping wrapped lines
- Searching downwards (shift+enter) is working, but the third wrapped line is not being revealed, this is likely a 1 off error in the logic on whether to scroll up/down

**Comment by Tyriar** [comment]
Created upstream issues.

**Comment by Tyriar** [comment]
Tracking in https://github.com/xtermjs/xterm.js/issues/2444
