### ISSUE TITLE
Update Notification never go away. Restart never bring the IDE back up

### ISSUE THREAD

**Issue by DavidTNguyen** [microsoft/vscode#81511]
- VSCode Version:
- OS Version:
Mc OS Mojave 10.14.3
Steps to Reproduce:

1. Disable all the extension
2. Click on the `Update Now` button

![update_issue](https://user-images.githubusercontent.com/11265859/65716252-63f71780-e064-11e9-85c3-91764ba86df0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/needsMoreInfo

What's your current version of VS Code?

**Comment by DavidTNguyen** [comment]
```

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:47:00.464Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.2.0
```

**Comment by joaomoreno** [comment]
Did you try this? https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

**Comment by DavidTNguyen** [comment]
That's it! Thanks @joaomoreno
