### ISSUE TITLE
TS file watching busted with Electron 6

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81516]
Tracks the VS Code side of https://github.com/microsoft/TypeScript/issues/33564

**Repo**
On MacOS with VS Code insiders

For the project:

`tsconfig.js`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "react"
    }
}
```

`src/main.ts`
```ts
export function foo() {
    add
}
```

1. Open main.ts
1. Create a new file `src/add.ts` in VS Code
```ts
export function add() { }
```

1. Back in `main.ts`, try auto importing `add`

    🐛 Doesn't show up

1. In `add`, run the `TypeScript: Go to project configuration` command. This should open the `tsconfig.json`

    🐛 File is not part of any project

**Investigation**
Something seems busted with using any version of TypeScript + Electron 6 on MacOS. I've tested the following cases so far:

- MacOS, newest TS with VS Code Stable — ✅ works
- MacOS, stable TS with VS Code Stable — ✅ works
- MacOS, stable TS with VS Code insides — ❌ broken
- MacOS, newest TS with VS Code insides — ❌ broken
- MacOS, TS 3.3 (an old version) with VS Code insiders — ❌ broken
- Windows, any TS with VS Code Insiders — ✅ works

Behind the scenes, TS uses node's `fs.watch` by default so I suspect the bug is somewhere with that not firing events properly

As @RyanCavanaugh and @sheetalkamat brought up, we cannot fix this on the TS side old TS versions are also broken

**Comment by mjbvz** [comment]
I also tested `tsc --watch` on MacOS with TypeScript 3.6.3 in the following situations:

### MacOS, use VS Code insider's node version — ❌ broken

```
ELECTRON_RUN_AS_NODE=1 /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron ./node_modules/typescript/lib/tsc.js --watch -p tsconfig.json
```

### MacOS, use VS Code stable (1.38) node version — ✅ works

```
ELECTRON_RUN_AS_NODE=1 /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron ./node_modules/typescript/lib/tsc.js --watch -p tsconfig.json
```

### MacOs, use normal node 12.4 — ✅ works

```
/Users/matb/.nvm/versions/node/v12.4.0/bin/node ./node_modules/typescript/lib/tsc.js --watch -p tsconfig.json 
```

**Comment by bpasero** [comment]
What is not clear to me is how this can be broken in Electron 6 but not node.js 12.4, which should be the same. 

@mjbvz can you please also test a bare GH Electron 6.x release to see if this is an issue on our build?

**Comment by mjbvz** [comment]
Yes also broken with plain Electron 6.1.0. A bit more testing with various electron versions:

```
$ELECTRON_RUN_AS_NODE=1 /Users/matb/Library/Application\ Support/Electron\ Fiddle/electron-bin/VERSION/Electron.app/Contents/MacOS/Electron ./node_modules/typescript/lib/tsc.js --watch -p tsconfig.json 
```

- MacOs, plain electron 7.0.0-beta4 — ❌  broken
- MacOs, plain electron 6.1.0 — ❌  broken
- MacOs, plain electron 6.0.0 — ❌  broken
- MacOs, plain electron 5.0.11 — ❌  broken
- MacOs, plain electron 5.0.8 — ❌  broken
- MacOs, plain electron 5.0.7 — ❌  broken
- MacOs, plain electron 5.0.6 — ❌  broken
- MacOs, plain electron 5.0.5 — ✅  works
- MacOs, plain electron 5.0.0 — ✅  works

This would indicate that 5.0.6 first broke this. Looking at [its commit history](https://github.com/electron/electron/commits/v5.0.6), nothing stands out to be besides possibly the [change to timers](https://github.com/electron/electron/commit/c979c90f46c361bb2d403b0f811a7f46eb0bab9a)

**Comment by mjbvz** [comment]
What's strange is that I can't find any version of plain node that is broken for `tsc --watch`:

```
/Users/matb/.nvm/versions/node/VERSION/bin/node ./node_modules/typescript/lib/tsc.js --watch -p tsconfig.json 
```

Tested:

- 10.16.3
- 11.0.0
- 11.15.0
- 12.0.0
- 12.0.4

**Comment by bpasero** [comment]
@mjbvz well as far as I know, https://github.com/nodejs/node/commit/29ae4fdb846d2e0a95140e04d9695cfc4e4cff80 was never merged to node but rather to Electron. So it is possible that we see a bug that was never there in node.s. We need to revisit this when Deepak is back by looking at that later change in libuv that was merged.
