### ISSUE TITLE
Don't include TS Lint extensions as a generic recommendation 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81515]
The TSLint project has been deprecated in favor of ESLint (which also supports TypeScript). We should no longer recommend our TSLint extension as generic recommendations (we currently recommend it if you workspace has any ts files)

However we can still recommend them if the workspace contains a tslint.json file or similar.

**Comment by jrieken** [comment]
@mjbvz Should we recommend ESLint then?

**Comment by mjbvz** [comment]
I talked about this with the TS team and we decided not for now. Using eslint for TS still requires some extra setup and configuration. We'll still recommend eslint for a ts project if we see any eslint configuration files
