### ISSUE TITLE
Matching Tag for custom extension

### ISSUE THREAD

**Issue by chrischeng0411** [microsoft/vscode#81528]
Issue Type: <b>Feature Request</b>

i have create my own extension (.vbb) which using both html and own customize element. When click the open tag to find the end tag of the element, all the word identical to the open tag is highlighted. Is this a bug or ?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chrmarti** [comment]
This is a feature. You get the same behavior in text and any other files.

**Comment by chrischeng0411** [comment]
What is the solution in order to achieve my expectation ? Is it nothing can do from my side? Sorry I'm new with visual studio code extension.

**Comment by chrmarti** [comment]
You can add your own text decorations: https://github.com/microsoft/vscode-extension-samples/tree/master/decorator-sample

Fancy example: https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag
