### ISSUE TITLE
Extract save / dirty service 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81521]
### Problem

As part of our custom editor exploration (#77131) I believe that we'll need to extract a service that handles saving resources. Currently this is implemented by `ITextFileService`

https://github.com/microsoft/vscode/blob/a3420f633e502289891361a071cf3aceb20c6360/src/vs/workbench/services/textfile/common/textfiles.ts#L65

However it is not clear to me how we can hook custom editors into our `ITextFileService` with out a lot of hacks. We specifically want the file `save`, `save as`, and `save all`  commands to be able to work for writable custom editors

### Proposal
Based on @bpasero's feedback, I propose we introduce a new service called something like `ISaveService` that would have the following functionality:

- Get dirty resources
- Tell if a resource is dirty or not
- Save resources

`ISaveService` would delegate to `ITextFileService` for normal resources, but should also allow our custom editor service to hook into save. As a first step, this service would probably absorb the `save` and `doSave` methods in `fileCommands.ts`:

https://github.com/microsoft/vscode/blob/0796f42a7d5327648eaed2db2f39ae9e9342e005/src/vs/workbench/contrib/files/browser/fileCommands.ts#L106

**Comment by bpasero** [comment]
@mjbvz what happened to the idea of backing custom editors by a resource that is wired into the file service? That would give us this for free basically.

**Comment by mjbvz** [comment]
This is now being handled by the `IWorkingCopyService`
