### ISSUE TITLE
Renamed file still showing in newly-opened 'Problems' report

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#8152]
Latest Insiders build, latest OSX El Capitan.

1. Cause a linting error in a JS file.
1. Rename that file within Code
1. Open the 'Problems' report (CMD+SHIFT M)
1. See a the name of the file as it was before renaming
1. Click it, be asked to create the file

**Comment by dbaeumer** [comment]
@sandy081 starting with you to see if the view is stale. Reporting wise we should delete old errors and create new ones on a file rename.

**Comment by sandy081** [comment]
@dbaeumer I checked that Problems view is working as expected and not stale. Looks like problem with the ts linter. Because, similar scenario with ts server works properly.

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscode-tslint#58
