### ISSUE TITLE
Cannot run Python in VS Code

### ISSUE THREAD

**Issue by Alknoy** [microsoft/vscode#81527]
Issue Type: <b>Performance Issue</b>

When debugging hello.py get "Cannot connect to runtime process after 10000 ms - (reason: Cannot connect to the target connct ECONNREFUSED 127.0.0.1:9229).

Open launch.json is the button window.  This gives you Add Configuration, but there is no meniton of Python in the list.,

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.06GB free)|
|Process Argv|--open-url -- vscode:extension/ms-python.python|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   100	  7164	code main
    0	    81	 10508	   shared-process
    0	    13	 14596	   electron-crash-reporter
    0	   204	 18096	   window (● launch.json - helloworld - Visual Studio Code)
    0	    38	  1188	     searchService
    0	    14	  7668	     watcherService 
    0	    11	  2976	       console-window-host (Windows internal process)
    0	   162	 11312	     extensionHost
    0	    48	   436	       "C:\Users\Al\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Al\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=11312
    0	    33	  4712	       "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" completion.py
    0	    20	 10776	         "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python 3.7.3
    0	    11	 15208	           console-window-host (Windows internal process)
    0	    11	 22052	         console-window-host (Windows internal process)
    0	    14	  6660	       c:\Users\Al\.vscode\extensions\ms-vscode.cpptools-0.25.1\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    11	  2124	         console-window-host (Windows internal process)
    0	    31	  9892	       electron_node eslintServer.js 
    0	    69	 20376	       electron_node tsserver.js 
    0	    87	 21624	       electron_node tsserver.js 
    0	    60	 16368	         electron_node typingsInstaller.js typesMap.js 
    0	     6	 17584	     winpty-process
    0	     4	 15936	       C:\WINDOWS\System32\cmd.exe
    0	    12	 20404	       console-window-host (Windows internal process)
    0	    85	 21464	   window (Issue Reporter)
    0	    97	 22140	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● launch.json - helloworld - Visual Studio Code)
|    Folder (helloworld): 7 files
|      File types: json(4) py(1) cpp(1)
|      Conf files: launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.9.34911
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.25.1
csharp|ms-|1.21.3
team|ms-|1.149.2
vscode-yaml|red|0.5.3

</details>

**Comment by chrmarti** [comment]
/causedByExtension

Please file this issue for the Python extension: https://github.com/microsoft/vscode-python/issues/new/choose
