### ISSUE TITLE
terminal output tab - autoopen problem

### ISSUE THREAD

**Issue by ashot11091950** [microsoft/vscode#81522]
Issue Type: <b>Bug</b>

terminal output tab everytime opens and shows info about parsing files, when I close tab, it reopens after delay

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2086)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.68GB (0.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
php-intellisense|fel|2.3.13
smarty|imp|0.3.0

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

(Note that you are on an older version of VS Code, please update.)

**Comment by dextar1** [comment]
i am also facing the same problem. it is very much annoying

**Comment by chrmarti** [comment]
@dextar1 Does this occur with all extensions disabled? (`F1` > `Developer: Restart With Extensions Disabled` or `code --disable-extensions`)

**Comment by ashot11091950** [comment]
It's not opens again yet, I will try it, for more info logs come from PHP Language Server, is it mean that problem in extensions?

**Comment by chrmarti** [comment]
/causedByExtension

Yes, please file an issue with the PHP extension you have installed.

**Comment by felixfbecker** [comment]
@chrmarti this has already been filed on the PHP extension. `vscode-languageserver-node` has an option on when to reveal the output panel, and it defaults to `OnError`. The users who reported the issue reported that there was no error in the output channel. Therefor this seems to be a VS Code bug.

https://github.com/felixfbecker/vscode-php-intellisense/issues/65#issuecomment-534503296

**Comment by dorianfm** [comment]
It feels like there should be a way to disable this automatic opening, even on error, when using extensions which do a lot of parsing, like vscode-php-intellisense - perhaps a global option that stops the tab being opened on errror, and a report of error counts on the bottom status bar which when clicked opens the output window?

**Comment by dbaeumer** [comment]
@felixfbecker this is actually fully under your control. The default is that the LSP client reveals the output channel if an error is logged into it. However when creating the client you can set this to `Never`. (see https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L339).

If this doesn't work for you please open an issue in the `vscode-languageserver` repository.

**Comment by dbaeumer** [comment]
Just to be clear: the output channel comes to front if an error is logged to it which for example is the case when a server errors a response.

**Comment by felixfbecker** [comment]
According to the comment linked above, there was no error in the output channel (I can't personally reproduce it, I'm only forwarding)

**Comment by dbaeumer** [comment]
How does the output panel look like?

VS Code has no error concept in output channels. It is LSP specific (e.g. `vscode-languageserver`)

**Comment by ashot11091950** [comment]
What you mean, saying how it's looks like?

**Comment by ashot11091950** [comment]
here it is again
but as far as I understand it's extension error because, this error was occured when I deleted the folder, so why extension look for files which are not exists
![vscode_parse_error](https://user-images.githubusercontent.com/40325246/66302436-fc658580-e909-11e9-9ae5-22a4f34a85f3.png)

**Comment by AjXUthaya** [comment]
Can you just add an option to not auto switch even if there is an output, because i have the same issue. It is fucking annoying as hell, when i try to type something in the terminal it switches me over to output every 0.3s. I really like the idea of an integrated terminal, but i have to use iterm2 for now because of this bug :(

**Comment by ashot11091950** [comment]
> Can you just add an option to not auto switch even if there is an output, because i have the same issue. It is fucking annoying as hell, when i try to type something in the terminal it switches me over to output every 0.3s. I really like the idea of an integrated terminal, but i have to use iterm2 for now because of this bug :(

How to add this option?

**Comment by AjXUthaya** [comment]
@ashot11091950 Seems like it is not a VS Code bug, its just a plugin "PHP Language Server" that is calling the reveal output aggressively. You have to report the issue to them. Until then you can just disable the PHP plugin, to find it just disable all the PHP one by one until the issue stops :)
