### ISSUE TITLE
Integrated Terminal not opening

### ISSUE THREAD

**Issue by amit420102** [microsoft/vscode#81524]
Issue Type: <b>Bug</b>

on pressing ctrl + `, the integrated terminal does not open while it opens the command powershell. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-support-client|Hyp|0.19.12
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5

</details>

**Comment by chrmarti** [comment]
The PowerShell terminal must capture the keypress before VS Code receives it. Try to disable the shortcut in the PowerShell terminal settings or assign a different keybinding to it in VS Code.

**Comment by amit420102** [comment]
Hi,

 

This does not seem to work. I changed it to another shortcut but still its opening powershell instead of integrated terminal.

I also deleted the shortcut in settings but it is still opening the powershell instead of integrated terminal.

 

Thanks,

Amit

**Comment by chrmarti** [comment]
Open the keybindings editor and search for Toggle Integrated Terminall to check what the current assignment is:
![image](https://user-images.githubusercontent.com/9205389/65769934-3037f280-e135-11e9-91d2-22e91ed25f21.png)

Sometimes this is auto-reassigned to `Ctrl + '` (tick ' instead of backtick \`).

**Comment by amit420102** [comment]
Hi Christof,

 

There is no shortcut assigned as of now:

**Comment by chrmarti** [comment]
@amit420102 Unfortunately images don't make it through email. Could you attach them directly on GitHub's website?

If there is none assigned, try assigning `Ctrl + '` to it.

**Comment by amit420102** [comment]
i have added keyboard shortcut of ctrl + `, but still on pressing the shortcut it opens powershell instead of integrated terminal. I have attached the images

![Capture](https://user-images.githubusercontent.com/35732764/65795623-b144b900-e138-11e9-8a3f-43ae11c76c4a.JPG)
![Capture2](https://user-images.githubusercontent.com/35732764/65795629-b3a71300-e138-11e9-884a-c119dae50e15.JPG)

**Comment by chrmarti** [comment]
Try adding the shortcut with a single quote (') instead of a backtick (`).

**Comment by amit420102** [comment]
hi Christof,

I am getting same result, its opening the powershell.

Thanks,
Amit

**Comment by amit420102** [comment]
Hi Christof,

 

I found the solution, turning off ConPTY worked for me.

 

I can now have integrated terminal opening in the Visual studio code and not in a new window.

 

Thanks,

Amit

**Comment by chrmarti** [comment]
Closing as solved. Thanks.
