### ISSUE TITLE
Searching with words in "files to include" sometimes doesn't work.

### ISSUE THREAD

**Issue by KunikoTakahashi** [microsoft/vscode#81526]
Issue Type: <b>Bug</b>

VSCode sometimes crashs down when searching with any words in "files to include".
If you don't set words in "files to include", it works.

If you don't set words in "files to include", succeeds, then you set words in "files to include",
it works.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.0.0

**Comment by chrmarti** [comment]
/needsMoreInfo

What do you type into "files to include" when it crashes? How does it crash?
