### ISSUE TITLE
Opened files forward arrow

### ISSUE THREAD

**Issue by gobi004** [microsoft/vscode#81530]
Issue Type: <b>Bug</b>

Hi,
whenever opened multiple files .for ex:if i opened 10 files at a time, moving files navigation  arrow is not displaying to move the hidded files into display  right or left in the top.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:58:59.274Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

Please attach a screenshot.

(Note that you are on an older version of VS Code, please update.)
