### ISSUE TITLE
Unable to open Unity project

### ISSUE THREAD

**Issue by Peaj** [microsoft/vscode#81538]
Issue Type: <b>Bug</b>

Use Unity 2019.2 or newer.
Use any version of the VSCode Unity package.
Try to open a script file (It may work at first)
Open and close the Unity and VSCode project a few times.

Please note that the issue is sporadic. It happened for us on 2 out of 3 machines
and only after working on the project for some time.

VSCode will not open anymore when trying to open script files.
It wont even react when opening a file from the Unity project folder via explorer.
Moving it out of the unity project makes it possible to open this single file.
Opening it as recent project from VSCode does also do nothing.
Also --verbose does not output anything for all these methods.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.53GB free)|
|Process Argv|D:/Git/archicave-core -g D:\Git\archicave-core\Assets\Global\Scripts\Rendering\VirtualScreen.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|2.4.6
php-intellisense|fel|2.3.13
latex-workshop|Jam|8.1.1
language-haskell|jus|2.6.0
docomment|k--|0.1.8
remote-wsl|ms-|0.39.5
csharp|ms-|1.21.3
vscode-witcherscript|nic|1.0.9
vscode-witcherscript-addon|nic|1.0.3
shader|sle|1.1.4
vscode-tidalcycles|tid|1.2.0
unity-debug|Uni|2.7.2

</details>

**Comment by chrmarti** [comment]
/causedByExtension

Please file an issue with the extension for Unity you are using.
