### ISSUE TITLE
Python Debug Console

### ISSUE THREAD

**Issue by icemage1991** [microsoft/vscode#81532]
Please have a look at this, this does not happen in the old version but actually appear in the new version, it loads too many environment variables when I'm trying debug feature. So what is going on with my vscode?

![image](https://user-images.githubusercontent.com/40601414/65750411-88b9c080-e132-11e9-878e-70e9336fe8d9.png)

![image](https://user-images.githubusercontent.com/40601414/65750337-51e3aa80-e132-11e9-9c32-301bc4ba2e67.png)

Thank you all

**Comment by chrmarti** [comment]
/causedByExtension

Please file this issue for the Python extension: https://github.com/microsoft/vscode-python/issues/new/choose
