### ISSUE TITLE
Extensions won't install or update

### ISSUE THREAD

**Issue by Merna-Atef** [microsoft/vscode#81533]
Issue Type: <b>Performance Issue</b>

I can't install or update any extensions. 
![Screenshot (74)](https://user-images.githubusercontent.com/35666049/65753648-15a35080-e118-11e9-8c0d-1845699a9f89.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    78	  9184	code main
    0	    71	  2320	   shared-process
    0	    67	  5128	   window (Issue Reporter)
    0	    13	  6416	   electron-crash-reporter
    1	   135	  7896	   gpu-process
    0	   151	  9472	   window (Extension: Bootstrap 4, Font awesome 4, Font Awesome 5 Free & Pro snippets - trial - Visual Studio Code)
    0	    40	  4200	     searchService
    0	    70	  8820	     extensionHost
    0	    11	 14132	     watcherService 
    0	    11	 13564	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Bootstrap 4, Font awesome 4, Font Awesome 5 Free & Pro snippets - trial - Visual Studio Code)
|    Folder (trial): 48 files
|      File types: ts(15) json(9) scss(4) html(3) js(2) gitignore(1) svg(1)
|                  png(1)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vs-color-picker|lih|1.0.0
vscode-clang|mit|0.2.3
python|ms-|2019.3.6558
vscode-css-peek|pra|3.0.2
vscode-csstree|sme|0.7.0
bootstrap4-vscode|the|6.1.0

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Could you explain more? There is usually no installation of extensions on startup.

**Comment by Merna-Atef** [comment]
i have updated the comment with more info. I can install and update them manually but not from the extensions tab.

**Comment by chrmarti** [comment]
Are you behind a network proxy?

**Comment by Merna-Atef** [comment]
no i am not

**Comment by Merna-Atef** [comment]
no i am not behind a proxy
