### ISSUE TITLE
insiders: many git comands are getting ignored by the ui

### ISSUE THREAD

**Issue by borgdylan** [microsoft/vscode#81534]
- VSCode Version: 1.39-insider
- OS Version: Ubuntu 19.04 on kernel 5.3.1 x64

Steps to Reproduce:

1. Try to stage a change or open a diff using the git side  panel
2. nothing happens

Does this issue occur when all extensions are disabled?: No

**Comment by borgdylan** [comment]
I suspect that there is a conflict with gitlens. If I disable it the isue does not occur.

/cc @eamodio .

**Comment by joaomoreno** [comment]
Interesting. Are all commands ignored? Can you give me an example of a command which works? Can you repro this on multiple different repos?

**Comment by borgdylan** [comment]
The viewlet initializes but then does not detect changes, do not accept ctrl+enter or equivalent ui button to commit etc. Disabling gitlens restores all functionality.

**Comment by borgdylan** [comment]
On the latest builds I'm getting the same issue even with gitlens removed.

**Comment by joaomoreno** [comment]
> On the latest builds I'm getting the same issue even with gitlens removed.

What about disabling all extensions? `code --disable-extensions`?

**Comment by borgdylan** [comment]
Seems to be workign again after updating insiders. Looks like it was some hiccup with a few builds.
