### ISSUE TITLE
Tree: decorations are not centered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81536]
Seeing this today in web:

![image](https://user-images.githubusercontent.com/900690/65753636-ae819e00-e10f-11e9-9194-420c1572ea65.png)

**Comment by joaomoreno** [comment]
@bpasero This is Explorer/decorations, not tree.

**Comment by jrieken** [comment]
Where does the circle come from? I guess that's a regression from that change? @misolori ?

**Comment by misolori** [comment]
Fixed. Needed to adjust the padding to account for the new size (width) in the Octicon update:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/35271042/65906359-433a0500-e377-11e9-8e16-2a6b59094f12.png">


Circle is referenced here (we should change this to a class name, added a TODO):
https://github.com/microsoft/vscode/blob/3f3a9e30db19282e34417935293b5642a2295cc7/src/vs/workbench/services/decorations/browser/decorationsService.ts#L77-L83
