### ISSUE TITLE
search slows down/hangs IDE  

### ISSUE THREAD

**Issue by madhur29shah87** [microsoft/vscode#81545]
Issue Type: <b>Bug</b>

ctrl+shift+f - search - searches in current project, it uses extensive memory and make hangs IDE and displays lagging behaviour till search is being performed. Earlier it used to work fine and didn't block/lag other actions on IDE.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
gitlens|eam|10.0.1
prettier-vscode|esb|2.2.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

Please check: https://github.com/Microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
