### ISSUE TITLE
'Enter' doesn't work to zoom in first result by code navigating.

### ISSUE THREAD

**Issue by kys910524** [microsoft/vscode#81543]
### environment

- VSCode Version: 1.38.1
- OS Version: macOS Mojave 10.14.6 (18G95)

### content

I usually use vscode for developing or analyzing c++ code. I have found an inconvenient problem when I analyzed c++ codes. When I use 'Goto Definition' or 'Peek Definition' for navigating code, This problem happens when I zoom in the first result out of more than two results. I click 'Enter' to watch a mini screen into total screen about the first result. But It doesn't work. If you go to a different result and come back and press enter, then It works. I wish this problem is fixed. :)

#### First, you click 'Go to Definition' about any function.
<img width="606" alt="Screen Shot 2019-09-27 at 6 16 48 PM" src="https://user-images.githubusercontent.com/43584573/65758263-c549e400-e153-11e9-907f-7dd7b17b6a15.png">

#### Second, you click 'Enter' about first result.
<img width="835" alt="Screen Shot 2019-09-27 at 6 24 17 PM" src="https://user-images.githubusercontent.com/43584573/65759591-44d8b280-e156-11e9-9e9f-cbb31ab23a50.png">

#### Result that I expected
<img width="832" alt="Screen Shot 2019-09-27 at 6 27 04 PM" src="https://user-images.githubusercontent.com/43584573/65758666-6c2e8000-e154-11e9-946f-c5562ecc4c8a.png">

**But, It doesn't work.**

**Comment by dwelle** [comment]
Potential duplicate of https://github.com/microsoft/vscode/issues/81200

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

**Comment by kys910524** [comment]
@chrmarti 
Thanks! This works well in insider.
I would expect vscode team to apply this patch next version.
Thanks for helping me!

@vscodebot
okay. When I post issue next time, I will follow the guidelines. 
Thanks for guiding me!
