### ISSUE TITLE
Keybinding config doesn't work.

### ISSUE THREAD

**Issue by zgqq** [microsoft/vscode#81547]
- VSCode Version:  1.38.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. 
Configure key binding
```
	{
		"key": "ctrl+u",
		"command": "deleteAllLeft",
		"when": "textInputFocus && !editorReadonly"
	}
```

2.
Open command window (workbench.action.showCommands), typing some words and pressing 
`ctrl+u`, then the vscode has no response.

**Comment by IllusionMH** [comment]
This configuration works for editor, but looks like this command is not applicable to input fields in Command Palette, Find Widget etc.

**Comment by zgqq** [comment]
@IllusionMH This looks like a bug. Other commands seem to be working.

**Comment by chrmarti** [comment]
`Cmd + Delete` should do that on Mac.

The request to make all commands from the text editor also work in input fields appears out of scope. Closing for that, thanks.
