### ISSUE TITLE
NetBeans like theme

### ISSUE THREAD

**Issue by zipper01** [microsoft/vscode#81557]
See the side to side compare bellow:
<img src="https://i.stack.imgur.com/k75ze.png">
The left side is VS-Code using "Default Material Dark Theme", the best I can find for my coding; the right side is the same piece of JavaScript code in NetBeans. For me, the right side view is much simpler, elegant and focus (while the left side view is messier and primitive--vim-like) especially when going-through lengthy files.

Is there a theme like this, or how can I modify the "Default Material Dark Theme" to make it more like the NetBeans theme I show?

**Comment by chrmarti** [comment]
Have you tried searching on https://vscodethemes.com ?

**Comment by zipper01** [comment]
The fact is I CANNOT find a similar theme anywhere and I had no power to make my own. all themes are basically color-themes only none make real rich-format documents. Cleanness and clarity are good. But none should mean poorer user experience in the long-running. I like this product because it is simple and good. I raised a request because I want it to improve. Great products lasting for a long time are developed based on good philosophies; but never limit themselves to them, they are dirty and rich, not clean and primitive.

**Comment by chrmarti** [comment]
Are you referring to having richer syntax coloring? Semantic highlighting might be what you are looking for. It is currently discussed in https://github.com/microsoft/vscode/issues/77133.
