### ISSUE TITLE
@example tag syntax highlighting in TypeScript files

### ISSUE THREAD

**Issue by rteshnizi** [microsoft/vscode#81559]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.18362

`@example` tags in a Typescript file should use Typescript syntax rules. It seems like JS rules are being used instead. In the screenshot below you can see that I am writing the same piece of code once in the actual code and once under the `@example` tag. Under `@example` however, the syntax highlighting breaks when specifying private modifier, parameter type, and after the generic type.

![image](https://user-images.githubusercontent.com/1209547/65786813-17234780-e11d-11e9-9b7d-c2775287240a.png)

Reproducer:

```ts
/**
 * @example
 * private myFunc(a: number): Promise<string> {
 * 	return e.anotherFunc();
 * }
 */
private myFunc(a: number): Promise<string> {
	return e.anotherFunc();
}
```

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by mjbvz** [comment]
The code snippet in the example is not valid TypeScript code on its own so our syntax highlighter will not be able highlight it properly.

Try pasting

```ts
private myFunc(a: number): Promise<string> {
	return e.anotherFunc();
}
```

in to a blank ts file; you see the same behavior.

Closing as out of scope
