### ISSUE TITLE
Git ssh don't ask password

### ISSUE THREAD

**Issue by optivlad** [microsoft/vscode#81554]
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. choose ssh git link ctrl+shift+P
2. try to pull or push the git link.
3 .Watch my log :
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.19.2.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: c:\XXXXXX
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git show :Equipe.py
> git check-ignore -v -z --stdin
> git pull --tags origin master
> git show :Equipe.py
Permission denied, please try again.
Permission denied, please try again.
git@lXXXXXXXchet.synology.me: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Does this issue occur when all extensions are disabled?: Yes

i can't connect and save my git password to push / pull or anything git command.

Thanks to help me

**Comment by chrmarti** [comment]
/needsMoreInfo

Do you have a credentials manager installed for Git? E.g.: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by optivlad** [comment]
Hello,

I'll try to install Git-Credential-Manager-for-Windows
But i don't have any problem when i use other IDE like Atom / Pycharm. So an update may be usefull.

Thanks

**Comment by chrmarti** [comment]
@joaomoreno In case you have an insight on why it might work with other editors but not with VS Code.

**Comment by joaomoreno** [comment]
What do other IDEs show you when time comes to ask for credentials? Can you share a screenshot?

**Comment by optivlad** [comment]
Sure, but i don't have connexion log. 

First time i use IDE i enter my ssh link and it asked me password (can check remember it).
![Pycharm_update](https://user-images.githubusercontent.com/55888873/65906326-a309cd80-e3c2-11e9-9743-5a78b0c885e6.PNG)
![2Pycharm_clone](https://user-images.githubusercontent.com/55888873/65906459-ec5a1d00-e3c2-11e9-9555-123c97910f47.jpg)
![2Atom_git_fetch](https://user-images.githubusercontent.com/55888873/65906584-1c092500-e3c3-11e9-8807-7d1dd9162b86.jpg)

I hope this will helping u
Regards

**Comment by joaomoreno** [comment]
#13680
