### ISSUE TITLE
Outline view not defaulting to "position" sort order

### ISSUE THREAD

**Issue by sdwheeler** [microsoft/vscode#81556]
Outline view not defaulting to "position" sort order. Sort is defaulting to **Sort by: Type** even though the default is supposed to be **Sort by: Position**. I also have the following setting in my `settings.json` file:

```
"breadcrumbs.symbolSortOrder": "position",
```

It still does not sort correctly.

- VSCode Version:
   ```
   1.38.1
   b37e54c98e1a74ba89e03073e5a3761284e3ffb0
   x64
   ```
- OS Version: `Windows 10.0.18362`

Steps to Reproduce:
1. Open any file that supports the outline feature
2. Open the outline view of the file
3. Click the **...** on the Outline bar and note the **Sort by:** selection.

Does this issue occur when all extensions are disabled?: Yes/No
> Yes

**Comment by jrieken** [comment]
Breadcrumbs are shown above the editor, outline is shown aside. Both a different and don't share settings. The latter uses the menu you have discovered, click position in there

<img width="652" alt="Screenshot 2019-09-30 at 16 07 53" src="https://user-images.githubusercontent.com/1794099/65886421-97a3ab80-e39c-11e9-9280-9faa1fba23bd.png">
