### ISSUE TITLE
Multiline find and replace with capture groups don't work 

### ISSUE THREAD

**Issue by jonopus** [microsoft/vscode#81566]
Issue Type: <b>Bug</b>

Multiline search and replace with capture groups results in literal `$1$2`.

Search:
(.*)(\r?\n)(.*)

Replace:
$1$2$3

Result:
$1$2$3

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ember|emb|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|2.3.0
macros|ged|1.2.1
ember-related-files|jos|1.5.0
sublime-keybindings|ms-|4.0.3
preview-vscode|sea|2.0.3
change-case|wma|1.0.0

</details>

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/81502
