### ISSUE TITLE
I'm getting an error that I don't know how to fix

### ISSUE THREAD

**Issue by markcpalmer** [microsoft/vscode#81560]
Issue Type: <b>Bug</b>

I'm getting a strange error:
Failed to load resource: net::ERR_CONNECTION_REFUSED

This was in the console in google chrome.  I expected a message from javascript saying "Import test" because I'm testing import.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

**Comment by markcpalmer** [comment]
What are VS Code Insiders?  What other information do you need?


-------- Original Message --------
Subject: Re: [microsoft/vscode] I'm getting an error that I don't know
how to fix (#81560)

**Comment by frank-dspeed** [comment]
@markcpalmer https://code.visualstudio.com/insiders/ download and install that vscode version and tell us if that happens there also!!!!!

**Comment by markcpalmer** [comment]
I'm still getting a blank white screen


-------- Original Message --------
Subject: Re: [microsoft/vscode] I'm getting an error that I don't know
how to fix (#81560)

**Comment by markcpalmer** [comment]
yeah I tried with the other visual studio code and it had the same result.  Can you help me?  we could use join.me and I could show you my code.  


-------- Original Message --------
Subject: Re: [microsoft/vscode] I'm getting an error that I don't know
how to fix (#81560)

**Comment by chrmarti** [comment]
Could you attach a screenshot? Is this an issue with your code?

**Comment by markcpalmer** [comment]
I figured it out.  I didn't have this statement:document.getElementById('demo').innerHTML = TestComponent()


-------- Original Message --------
Subject: Re: [microsoft/vscode] I'm getting an error that I don't know
how to fix (#81560)

**Comment by frank-dspeed** [comment]
/close 
@markcpalmer ok you can close this then
