### ISSUE TITLE
open file will kill the next opened editor

### ISSUE THREAD

**Issue by hmassalha** [microsoft/vscode#81568]
- VSCode Version: 1.39.0-insider
- OS Version: macOS 10.14.4

when opening/preview a file while the active editor is not the last one, the opened file will kill and replace the next editor window. But if the active editor window is the last everything is fine.

Steps to Reproduce:

1. open more than one editor
2. activate any editor but not the last (most right)
3. open new file/script

*I found also that when I try to open .log file it replaces the .R file, and vice-a-versa, even though the .log file is the last opened/preview editor

Thanks, HM

**Comment by chrmarti** [comment]
Confirmed. Somehow some other editor instead of the 'preview' editor is replaced.

**Comment by bpasero** [comment]
You can see that the preview editor is replaced, but also moved. This is intentional.
