### ISSUE TITLE
Display license link for VSIX packages in Extensions View

### ISSUE THREAD

**Issue by Friday32** [microsoft/vscode#81563]
You can see information such as download count, link to a repository, and a license link in the extensions view for items downloaded from the marketplace.

My company does not want to publish our extension in the marketplace and instead distribute a VSIX file.  I included license information in the package.json and created a VSIX files for testing.   I am able to see details in the extensions view after installing the VSIX package.  But,  a license link does not appear. I assume you must publish the extension to display the link.

If there is a way to display the license link in this scenario, it's not clear to me how to do it.  So the feature request would be to display a license link or document how to show it if that's already possible.

**Comment by sandy081** [comment]
Sorry, entering into `package.json` is not enough to show the license. It is required to be published as the link is read from Marketplace.

**Comment by Friday32** [comment]
There is a "tabbed view" (lack of a better term) with "Details", "Contributions", and "Changelog".  Could it be possible for an extension author to contribute addition items? Licenses should be prominently displayed.  

( There really should a document on the https://code.visualstudio.com/ about handling license issues. Your package.json is likely have dependencies that also have dependencies,  and all  dependencies have license terms that need to be adhered to. )

**Comment by sandy081** [comment]
@Friday32 Extension authors can contribute the license by having a license file in your repo. This file is indexed in Marketplace and is shown as license link.

**Comment by Friday32** [comment]
The problem is linking the license to marketplace and to a repo.   It should link locally to the file distributed with the extension. Please understand that not everyone can publish their extensions to the marketplace or upload their code to a publicly repository.  

My company produces test and measurement equipment that use Windows 10 embedded.  Some customers install our products in secure lab environments where they are not permitted to connect the equipment to the internet.  In this case, the marketplace details will be hidden including the license link.

**Comment by sandy081** [comment]
I see your issue but since it is not a requirement which can be useful for many users I am not sure if we can take this up soon. But we are open to accept PRs if it is important for you. Hence reopened.

**Comment by frobinsonj** [comment]
I would like to have a go at this.

**Comment by GitMensch** [comment]
@frobinsonj What happened to your PR?
