### ISSUE TITLE
Settings tree outline is hidden when hovering setting rows

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81564]
Hey @isidorn, at some point we started showing the focus outline on the editor, I think due to accessibility changes, do you know anything about that? I don't really understand why it's needed. Is it ok if I hide it on the settings editor page? I can only get it to show by clicking in the margin anyway, I can't tab to it.

And it interacts with the settings rows in a weird way 
![Sep-27-2019 10-34-43](https://user-images.githubusercontent.com/323878/65790095-b3485100-e113-11e9-82f6-b3a216c5aa04.gif)

**Comment by isidorn** [comment]
Yes, feel free to remove it. The point is that we should show focus if you can tab onto it, so the user know where he is. If tabbing via keyboard is not possible, than it is fine to remove the focus border.
Sorry for the slow response I was out on a vacation day.
