### ISSUE TITLE
Can't remove # from Command+T search as default

### ISSUE THREAD

**Issue by wes321** [microsoft/vscode#81565]
Issue Type: <b>Bug</b>

I use Command+T often but it seems like there is no way to remove the # besides backspace everytime I open it up. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

**Comment by chrmarti** [comment]
Try `Cmd + P`!

**Comment by wes321** [comment]
Thanks for the quick reply! Didn't realize same functionality, I just started using it over sublime. So far it's pretty amazing.
