### ISSUE TITLE
Snippets borders overlap

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#81561]
- VSCode Version: 1.38.1 and 1.39.0-Insider
- OS Version: Win10 64bit

Also happens with no extension enabled and html-snippets.

Steps to Reproduce:
Call a snippet that has inputs with one above the other.
Note how the borders are inside of each other near the box that has `expression` in it.
![image](https://user-images.githubusercontent.com/20489521/65788054-8cf9d400-e15a-11e9-93c7-00410f22c716.png)

**Comment by jrieken** [comment]
What theme is this?

**Comment by tweakimp** [comment]
This is my theme: https://marketplace.visualstudio.com/items?itemName=tweakimp.jungle-night
It also happens with the default theme.

**Comment by jrieken** [comment]
> It also happens with the default theme.

I don't think so  - the default theme doesn't use the borders, just background color. Anyways, I can repro with the jungle-night theme.

**Comment by jrieken** [comment]
code pointer: https://github.com/microsoft/vscode/blob/62b2b7098d5096a940c6a8f4f9c136072fae9407/src/vs/editor/contrib/snippet/snippetSession.css#L6

**Comment by tweakimp** [comment]
> > It also happens with the default theme.
> 
> I don't think so - the default theme doesn't use the borders, just background color. Anyways, I can repro with the jungle-night theme.

Choose Dark (Visual Studio).
Add this to your `settings.json`:
```
"workbench.colorCustomizations": {
        "editor.snippetTabstopHighlightBorder": "#ff00ff"
    },
```
See the pink overlapping border around snippet inputs.

**Comment by jrieken** [comment]
This is acknowledged but I don't see an easy fix (this already uses outline style and is a problem of the decoration being to high or the line spacing being too narrow). Given that and the low number of reports (one) I have decided to not fix this issue.
