### ISSUE TITLE
ubuntu vscode can't use F12 searching function define

### ISSUE THREAD

**Issue by ogawa-tech** [microsoft/vscode#81575]
Issue Type: <b>Bug</b>

ubuntu vscode can't use F12 searching function define

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.77GB (3.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
EnglishChineseDictionary|Cod|0.0.11
vscode-language-pack-zh-hans|MS-|1.38.4
cpptools|ms-|0.25.1

</details>

**Comment by huguadou** [comment]
yes,i 'm also ubunt, vscode go to definition and F12 don't be used. do you have a solution way?thanks

**Comment by chrmarti** [comment]
/needsMoreInfo

Does VS Code receive the F12?

![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

Maybe F12 is taken by your OS. In that case try assigning a different keybinding.
