### ISSUE TITLE
Missing beak

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81573]
The notifications thing is missing its beak (blue triangle above the bell)

Before
![image](https://user-images.githubusercontent.com/323878/65807582-f02c3c00-e143-11e9-9418-381bc5cd45c1.png)

After
![image](https://user-images.githubusercontent.com/323878/65807563-e99dc480-e143-11e9-87be-f93c8602c5e1.png)

**Comment by roblourens** [comment]
"before" = stable

Maybe related to icons, maybe not?

**Comment by misolori** [comment]
Looks like @joaomoreno added `overflow: hidden` to the status bar in https://github.com/microsoft/vscode/commit/bd79c20ac85d44a42d28defb6aa280d5e9ab066b so this hides the beak. I'll see if I can get around this.

**Comment by misolori** [comment]
Fixed and added `overflow: visible` to `.part.statusbar`.

@joaomoreno @jrieken, can you verify that this doesn't regress for https://github.com/microsoft/vscode/issues/78167 (I checked and it looks like it doesn't)?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/35271042/65908865-2eac3b80-e37c-11e9-9fd7-f6c0cd213bfe.png">

**Comment by joaomoreno** [comment]
This seems to have regressed https://github.com/microsoft/vscode/issues/78165. cc @bpasero @misolori
