### ISSUE TITLE
[Bug] Trys to setup fswatchers in my home dir on start

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81579]
- VSCode Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic

So let me explain the error more well. When i open vscode on my desktop with no additional folder it starts to watch for my whole home dir as default folder maybe? it should start watching only opened directorys.

its also verifyied that this happens when i open a folder .
```
  ERR [File Watcher (node.js)] Failed to watch /home/frank/.config/Code/User for changes using fs.watch() (Error: ENOSPC: no space left on device, watch '/home/frank/.config/Code/User')
/usr/share/code/reso…esktop.main.js:3579 [Extension Host] debugger listening on port 57389
/usr/share/code/reso…esktop.main.js:1504   ERR Error: [File Watcher (node.js)] Failed to watch /home/frank/.config/Code/logs/20190926T115203/output_4_20190928T094647 for changes using fs.watch() (Error: ENOSPC: no space left on device, watch '/home/frank/.config/Code/logs/20190926T115203/output_4_20190928T094647')
/usr/share/code/reso…esktop.main.js:1504   ERR [File Watcher (node.js)] Failed to watch /home/frank/.config/Code/logs/20190926T115203/output_4_20190928T094647 for changes using fs.watch() (Error: ENOSPC: no space left on device, watch '/home/frank/.config/Code/logs/20190926T115203/output_4_20190928T094647')
/usr/share/code/reso…esktop.main.js:1504   ERR Error: [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
/usr/share/code/reso…esktop.main.js:1504   ERR [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
﻿```

Steps to Reproduce:

1. start vscode 
2. open new window
3. open folder
4. watch console output

<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@frank-dspeed does this help https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc ?

**Comment by frank-dspeed** [comment]
@bpasero you don't understand right look at the path it trys to setup watchers for my home dir with when i have nothing opened in my workspace no folder is open ?

**Comment by frank-dspeed** [comment]
and we have the same bug in the code-server builds from cdr there we also use 1.38.1 https://github.com/cdr/code-server/issues/1036

**Comment by frank-dspeed** [comment]
So let me explain the error more well. When i open vscode on my desktop with no additional folder it starts to watch for my whole home dir as default folder maybe? it should start watching only opened directorys.

**Comment by bpasero** [comment]
Moving to @sandy081 to explain why we watch files/folders in home dir. This seems to be related to output or config watching.

**Comment by sandy081** [comment]
Let me know if it makes sense

**Comment by frank-dspeed** [comment]
@sandy081 i understand that but i am not happy with that design. VSCode killed already a ssd from me by accident.

we can close this i opend a new one with a solution for this.

https://github.com/microsoft/vscode/issues/81702
