### ISSUE TITLE
Error on shorcut with VSCODE using the mouse logitech MX

### ISSUE THREAD

**Issue by pookdeveloper** [microsoft/vscode#81578]
I use the mouse logitech MX, I have shorcuts when I click in one button to close one tab of window, but when I click it paste the clipboard first before closing the window, only pass in visual code not in other app   see this video please:

https://www.loom.com/share/2d593730134e44929d0db150de146ff4

There are more people with the same problem

https://support.logi.com/hc/en-us/community/posts/360034878813-key-assignment-error?page=1#community_comment_360008852314

Thanks

**Comment by alexandrudima** [comment]
Duplicate of #80804
