### ISSUE TITLE
Suggestions about link styles

### ISSUE THREAD

**Issue by zhengzongsheng** [microsoft/vscode#81583]
Hello, can i add a link style for URL in Output and Debug Console and provide an outer chain like a file path?

**Comment by zhengzongsheng** [comment]
like this
![fc56b1fa32896f377accd12cf9c0f95](https://user-images.githubusercontent.com/34943180/65818267-9c544c80-e242-11e9-875b-83f4a214d239.png)
thanks

**Comment by Tyriar** [comment]
Not sure what you're asking for exactly, do you want to style the underline or have the ctrl+click popup inside output and debug console?

**Comment by zhengzongsheng** [comment]
I need to press the ctrl + click popup in the output and debug console so that I don't have to open the browser manually.

**Comment by Tyriar** [comment]
It works in output?

<img width="396" alt="Screen Shot 2019-10-01 at 7 39 13 AM" src="https://user-images.githubusercontent.com/2193314/65972375-9915b800-e41e-11e9-90a2-c2b16a50fe93.png">

**Comment by zhengzongsheng** [comment]
Yes, but I can't seem to implement console.log(url) in the output, and I hope to do this in the debug console as well.

**Comment by Tyriar** [comment]
Debug console doesn't support it apparently.

/duplicate https://github.com/microsoft/vscode/issues/48337
