### ISSUE TITLE
console.log outputs undefined

### ISSUE THREAD

**Issue by gdimauro** [Microsoft/vscode#8158]
- VSCode Version: Code - Insiders 1.3.0-insider (de66522e06d74752d48d92e934dcd026050355ba, 2016-06-24T05:07:35.941Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. in DEBUG CONSOLE write: console.log(100)
2. you'll obtain "undefined"

**Comment by isidorn** [comment]
This is coming from the node debug adapter thus forwarding to @weinand 
Chrome dev tools behaves the same so I think this is desgined behavior but I'll let @weinand decide

**Comment by weinand** [comment]
@gdimauro please run this snippet and you will see that this behaviour is correct:

```js
if (console.log(100) === undefined) {
  console.log("return value from console.log() is indeed undefined");
}
```
