### ISSUE TITLE
Creating a new file in a vscode window does not focus the window

### ISSUE THREAD

**Issue by zcr1** [microsoft/vscode#81588]
- VSCode Version: 1.38.1
- OS Version: Mac Mojave 10.14.6

Steps to Reproduce:

1. Have 2 open windows of vscode side by side
2. Left click to focus a file in window A
3. Right click on window B and hit new file / folder and a text input is displayed to name new file
4. When you start typing it goes into window A instead of B

Vscode should focus the window if a text input is shown no?

**Comment by chrmarti** [comment]
This might be the Mac OS behavior.

**Comment by Box-Of-Hats** [comment]
Could not reproduce on Windows 10

VSCode: 1.38.1

**Comment by zcr1** [comment]
> This might be the Mac OS behavior.

Based on some quick testing of other apps and a quick google search I think you are correct.
