### ISSUE TITLE
Touch Screen not working

### ISSUE THREAD

**Issue by DanTheWebDevMan** [microsoft/vscode#81586]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

the touch screen doesn't work when working on a file, for example, I can not scroll down the lines of code.

However, the scroll bar does work when I scroll in the terminal.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-browser-preview|auc|0.5.9
simple-react-snippets|bur|1.2.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
vscode-peacock|joh|3.1.5
chat|kar|0.22.1
vscode-gutter-preview|kis|0.23.0
mssql|ms-|1.6.0
vsliveshare|ms-|1.0.869
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
debugger-for-chrome|msj|4.12.0
polacode|pnp|0.3.4
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.4.0

</details>

**Comment by DanTheWebDevMan** [comment]
any update on how to fix? none of the other threads provide a solution

**Comment by alexandrudima** [comment]
I have just tested VS Code on a Surface Book and using touch to scroll the editor works fine.

**Comment by DanTheWebDevMan** [comment]
Hello,

I tried again on my Surface Pro 4 and it worked again. Thanks for your help!
