### ISSUE TITLE
Failed to install on Raspbian

### ISSUE THREAD

**Issue by BioHazard1282** [microsoft/vscode#81585]
- VSCode Version: 1.38
- OS Version:
_PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=Debian
Description:	DebianEdu/Skolelinux
Release:	9.9
Code-name:	stretch
uname = Linux_

Steps to Reproduce:

1. Simply download the .deb (Debian) VSC File
2. Install with Package install

**This file will not install on my Raspberry Pi 3 B, because a specific package that is required for installation is missing. Where and what package can I install?**

![Failed to install](https://user-images.githubusercontent.com/44819642/65819460-12709900-e1da-11e9-8ff2-a11b23c0dbe3.png)

**Comment by joaomoreno** [comment]
We do not support VS Code on ARM, not sure where you got that deb from.

**Comment by BioHazard1282** [comment]
What do you mean "where I got that .deb from"? I got it from your own
Visual Studio code website? There were 3 categories: Windows, Linux,
and Apple. In the Linux category, there were two file types, .deb and
.rpm. .deb is the file type that is a closest match to Raspbian, so I
downloaded it. If you don't believe where I got it from, I can post
the link below.

**Comment by joaomoreno** [comment]
We only support

**Comment by BioHazard1282** [comment]
https://code.visualstudio.com/Download

**Comment by frostshoxx** [comment]
Try this instead https://code.headmelted.com/. Note that the code hasn't been maintained recently and there is a specific version you need to use in order to make it run on Raspberry Pi.

**Comment by BioHazard1282** [comment]
Which version of what? Version of VSC or Raspbian?

**Comment by frostshoxx** [comment]
The version of Headmelted's compiled VS Code for ARM. 

Basically, what joaomoreno saying is that the linux build on the download link you mentioned was made for x64 linux, which does not work with ARM processor (Raspberry Pi). You will either have to compile the code yourself or get the pre-build by others. Headmelted was one of the folks who build VS Code on ARM and then share with others. However, his latest build doesn't work and only show blank screen when the app is open.

See this thread for more details: https://github.com/microsoft/vscode/issues/6442

**Comment by BioHazard1282** [comment]
So I should just use Python IDE for python projects if it won't work on my Pi?

**Comment by frostshoxx** [comment]
Personally, I use Thonny IDE for Python as it comes with Raspbian by default. I only use VS Code for JavaScript-based stuff to develop web-application (e.g., Gatsby.js). I find designated Python IDEs that came with Raspbian perform better than VS Code, but to each their own, I guess.
