### ISSUE TITLE
[Bug] Cannot open new terminal dual to last remote directory is not exist

### ISSUE THREAD

**Issue by quangthanh010290** [microsoft/vscode#81580]
- VSCode Version: 1.38.1
- OS Version: Ubuntu 18

Steps to Reproduce:

1. create a sshfs folder
2. Open this new folder with vscode
3. Open new terminal
4. close vscode
5. remove the sshfs folder or disconnect network
6. open vscode
7. Create a new integrated terminal

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
It sounds like you're opening the window in a now non-existent folder? Do other things like the explorer have issues too?

**Comment by quangthanh010290** [comment]
Yes, the folder does not exist at the time I open a new console, It seems that vscode save config somewhere and try to create a new terminal on this folder. 
Even though I open an existed folder on my PC then open a new console, vscode still try to create console on the remote folder.

**Comment by Tyriar** [comment]
Can you show a screenshot of what the explorer pane looks like?
