### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#81581]
<img width="1251" alt="1" src="https://user-images.githubusercontent.com/11925432/65816993-b8e98800-e234-11e9-873f-70026b536dd3.png">

**Comment by chrmarti** [comment]
/needsMoreInfo

Does this also happen with VS Code Insiders? Download: https://code.visualstudio.com/insiders/

**Comment by kzhui125** [comment]
cannot reproduce, thanks
