### ISSUE TITLE
Increase the number of cursors from 10000

### ISSUE THREAD

**Issue by rs6454** [microsoft/vscode#81589]
Hi Team

I do a lot of work editing on text files with line more that 10000,editing of large file is limited due to the The number of cursors has been limited to 10000.

Please increase this limit to 100000 if possible

**Comment by rs6454** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Cannot edit more than 10000 lines in "column edit mode" (#80324)](https://www.github.com/microsoft/vscode/issues/80324)

this duplicate does not have a solution, Please include this feature

**Comment by LesterCovax** [comment]
I just ran into this same limitation when editing 20k+ lines at once.  In my case it wasn't a big deal as I only had to repeat my actions twice, but for larger files it would certainly be a hindrance.  Adding a `defaultSettings.json` preference (e.g. `"editor.multiCursorMaxLines": 10000`) that users could increase in their own environments would be much appreciated.

**Comment by pablo-romano** [comment]
> I just ran into this same limitation when editing 20k+ lines at once. In my case it wasn't a big deal as I only had to repeat my actions twice, but for larger files it would certainly be a hindrance. Adding a `defaultSettings.json` preference (e.g. `"editor.multiCursorMaxLines": 10000`) that users could increase in their own environments would be much appreciated.

And where do you put the `defaultSettings.json` ?

**Comment by LesterCovax** [comment]
@pablo-romano - `defaultSettings.json` is just a built-in reference file that shows all available settings and their default values.  Do a `CTRL+SHIFT+P` and search for `open default settings`.  It's a useful reference when tweaking your settings file.  I just mentioned it, as adding in a new settings option would also imply it's added to the `defaultSettings.json`.

**Comment by LesterCovax** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

@alexdima / @vscodebot (or whoever manages it)
Can you please clarify the language used in the previous message, regarding upvotes needed to move this to the backlog?  Even after reading the included [documentation](https://aka.ms/vscode-issue-lifecycle) link, and the fact that a Github issue itself cannot be upvoted, it's unclear whether one should upvote the [initial post's comment](https://github.com/microsoft/vscode/issues/81589#issue-499816955) or the [comment from vscodebot](https://github.com/microsoft/vscode/issues/81589#issuecomment-580690306) in order to count towards the requisite 20 upvotes for backlog inclusion.  Cheers.

**Comment by alexdima** [comment]
@LesterCovax I think the opening post should be upvoted:
  
> ![image](https://user-images.githubusercontent.com/5047891/73858963-8df1ef00-4839-11ea-87d7-bc2cc4a3ff41.png)

@chrmarti @kieferrm FYI there is some confusion about the bot language.

**Comment by LifeOfJona** [comment]
Was this implemented?

**Comment by mendeljacks** [comment]
This would be very useful for dealing with large files where for example you wanted to add a comma to line

**Comment by FranciscoCaldeira** [comment]
Already did Up vote ... I need this feature to past 300k lines

**Comment by Robert-Saiter** [comment]
Having this configurable would be more useful than increasing it to 100000.  I am just guessing but each machine may have a different limit to how much it can handle and I frequently handle text files with millions of lines.  Whatever the maximum amount is that my machine can handle would be the best case for me.

**Comment by nikbucher** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/controller/cursor.ts#L124

**Comment by riversky0014** [comment]
Seems that it hasn't be implemented? I need this feature a lot, otherwise I have to deal large file with python, it is not so happy.

**Comment by earslap** [comment]
Been waiting for this for a looong time.

For a temporary fix / hack: find file `workbench.desktop.main.js `minified file on your vscode installation and search for the string `MAX_CURSOR_COUNT` in there, change the set value (it is 1e4, make it 1e5 for 100000 for instance), save, restart vscode. Now on each new window, vscode will rightly complain about installation being corrupted but otherwise it will serve your needs until this is implemented.

**Comment by BenRacicot** [comment]
Why would an IDE have a max cursor count that cannot be changed via settings or available memory or something? That's ah, what we need it for.

**Comment by trollfred** [comment]
Please make it happen!

**Comment by marekparticle** [comment]
+1! Would be really useful.

**Comment by HadesWing** [comment]
when cursors more than 10000, why cannot select any one of cursor? why not select  10000 cursor first? or 10000 every time.

**Comment by NullFunctor** [comment]
Please update soon, need to use reg exp on 200k lines

**Comment by tomcastigl** [comment]
please update this! It is a big handicap for me.

**Comment by deltadelta** [comment]
WTB this update!

**Comment by commadelimited** [comment]
I'm working on XML files with millions of lines, and 100,000 top level child elements. Being able to select individual nodes for reporting would be really helpful.

**Comment by gkot-softwaredeveloper** [comment]
I need to change at the same time 600 000 lines 📄. I hope that you'll take care of this 'feature' 👍 . Can't wait for this 🥇

**Comment by michael-ottink** [comment]
Any news on this?

**Comment by trollfred** [comment]
I would suggest learning how to use `sed`. vscode is not the right tool for editing large files. even if it allows unlimited cursors you will probably run out of memory or performance will be extremely poor editing that many lines

**Comment by flamurbeqiraj** [comment]
Can't believe that this big project can't handle big files! It is just necessary!

**Comment by DRSDavidSoft** [comment]
@vscode Team, is there any technical reasons that this value is not configurable by the user, unlike how `json.maxItemsComputed` is for JSON items?

**Comment by K0stov** [comment]
As of the latest update, this no longer seems to work.

**Comment by oiver555** [comment]
Are there workarounds to this issue? Other then doing mass selections manually.

**Comment by brendonlamb** [comment]
bumping into this same constraint here, would love this to be configurable

**Comment by itzBawantha** [comment]
No rush , But waiting for this for 3 years now.

**Comment by cahyowhy** [comment]
leaving dot here in case in the future will be implemented, don't know when thou

**Comment by humanolaranja** [comment]
2022 and still waiting for this feature

**Comment by K0stov** [comment]
> 2022 and still waiting for this feature

Yeeep.

**Comment by sdenni** [comment]
waiting.

**Comment by AlexDiaconu** [comment]
+1. When will this be implemented? Has been added to the backlog almost 2 years ago :-S.

**Comment by marcoantoni0** [comment]
+1

**Comment by antonio-schlappa-motioncx** [comment]
+1

**Comment by mpintob** [comment]
+1

**Comment by a1re1** [comment]
+10001 ;)

**Comment by Jovi-droid** [comment]
+1

**Comment by guidofd** [comment]
+1

**Comment by ronytesler** [comment]
Waiting

**Comment by v1shva** [comment]
Wow, not implemented in VS still? For anyone else having same issue, try Sublime, can edit 50k+ lines simultaneously.

**Comment by lcbotha** [comment]
+1

**Comment by rs6454** [comment]
I think I will have to switch back to Sublime text editor since this is still not implemented after +2 years

**Comment by tiantian1645** [comment]
https://www.emeditor.com/

**Comment by caioagiani** [comment]
+1

**Comment by mowamed** [comment]
+1

**Comment by glorialulu** [comment]
+1

**Comment by rodrigojeansantos** [comment]
+1

**Comment by keremkutlu1234** [comment]
Thanks for @earslap and @nikbucher,

For the Windows solution, (this is not an official solution)...

## **STEP 1**
Open the folder path "C:\Users\USERDIRECTORY\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench"

## **STEP 2**
Open "workbench.desktop.main.js" with  the VSCode 😂

## **STEP 3**
Open finder in the VSCode and write MAX_CURSOR_COUNT=1e4 than it will find one option after thatchange it to what you number what you want but 1e4 is 10000, so if you want 90000 you need to enter 9e4 you can use this website to calculate it
[Calculator](https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php)
than wirte what number do you want to the website after that click calculate than get the value of "scientific e notation", copy it.

## **STEP 4**
Pate the value what you copied to the MAX_CURSOR_COUNT=, it will be like MAX_CURSOR_COUNT=9e4

## **STEP 5**
Than open the second file in the same folder named "workbench.desktop.main.nls.js" and apply the same steps for this file change the value of MAX_CURSOR_COUNT=1e4 to the same number what you want.

## **STEP 6**
And restart the VSCode thats all :)


Now you can select more than 10000 columns



Regards,
KK

**Comment by andig** [comment]
Thanks for sharing. Same on Mac.

I'd still love to see this fixed for good. No sense not using my favourite editor for big files due to an artificial internal limitation!

**Comment by RaphaelSilv** [comment]
+1

**Comment by AbdouMechraoui** [comment]
+1

**Comment by andig** [comment]
Can I suggest that everyone interested in this puts a thumbs up on the original issue? Imho the VSCode team looks at this when prioritizing. +1 comments are not counted.

**Comment by jtsierra** [comment]
This could be very handy for working with json files. Thumbs up

**Comment by andig** [comment]
Linked it to the April plan.

**Comment by bolti95** [comment]
+1

**Comment by Danipulok** [comment]
+1

**Comment by porteron** [comment]
+1

**Comment by rafaelmm899** [comment]
+1

**Comment by DanielLopezOSF** [comment]
+1

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Why not merely not limit this?

**Comment by fabiosoares-cw** [comment]
[It](https://github.com/microsoft/vscode/issues/81589#issuecomment-1059945536) worked here. 🚀 thanks @mioversolna

**Comment by sdhjl2000** [comment]
+1

**Comment by alexdima** [comment]
To verify, configure `"editor.multiCursorLimit": 50000` and create a file with 50k qwerty words in it. Then, select one word and press `cmd+shift+L`. The status bar should show 50k selections.
