### ISSUE TITLE
vscode-go extension cannot install tools in go 1.11

### ISSUE THREAD

**Issue by jdratlif** [microsoft/vscode#81591]
- VSCode Version: 1.38.1
- OS Version: Debian 10 x86_64

Steps to Reproduce:

1. Install VS Code
2. Open a go file
3. Install Go extension
4. Click Install All when it says there is a tool missing
5. Watch is all fail

Does this issue occur when all extensions are disabled?: Yes/No
No

`Installing 17 tools at /home/jdratlif/go/bin
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/cmd/gopkgs FAILED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags FAILED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct FAILED
Installing github.com/haya14busa/goplay/cmd/goplay FAILED
Installing github.com/godoctor/godoctor FAILED
Installing github.com/go-delve/delve/cmd/dlv FAILED
Installing github.com/stamblerre/gocode FAILED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

17 tools failed to install.

gocode:
Error: Command failed: /usr/bin/go get -v github.com/mdempsky/gocode
go: cannot find main module; see 'go help modules'
go: cannot find main module; see 'go help modules'`

I know this has something to do with modules. I have read many issues about modules, but they all seem to be resolved as if there was some fix for this long ago. Maybe there is.

I don't know what adding GO111MODULE means. Is that a goenv? Is that in the settings.json. I tried it in both places and it made no difference what it was set to (on, off, auto, or undefined). Maybe I did it wrong?

I can execute those go get -v commands from a terminal and they work just fine.

I am not using any modules that I know of. I don't even know what modules are. I just know that debian updated my Golang from 1.10 to 1.11 and now I can't use the VS Code go extension.

**Comment by chrmarti** [comment]
Please file for the Go extension you have installed.
