### ISSUE TITLE
Add "Duplicate file" command in file explorer right click menu

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#8159]
- VSCode Version: 1.2.1
- OS Version: MacOS

A native "duplicate file" command next to "copy", "rename" and "delete" is much needed.

**Comment by bpasero** [comment]
For now you can Copy & Paste to get the same behavious.

**Comment by sijad** [comment]
Hey, can I try to add this feature

**Comment by bpasero** [comment]
Should be done as extension (using new menu API).
