### ISSUE TITLE
需求：快速复制选中的内容

### ISSUE THREAD

**Issue by 978165754** [microsoft/vscode#81593]
鼠标选中一行中的某一段（而非一整行），按快捷键实现快速复制选中的这段内容。

例如： let sub=$('#submit_btn') 
我想快速复制选中的 submit_btn ，目前我需要操作三步：
1、 ctrl+C 复制，
2、按右箭头→，到单词结尾
3、ctrl+V 粘贴

我希望能通过一个快捷键就完成这3步。之前用的notepad++，他的快捷键是ctrl+D，用vscode一年多了，一直感觉这个功能是个欠缺，希望能加上，谢谢

**Comment by think2011** [comment]
```js
{ "key": "ctrl+shift+cmd+right",  "command": "editor.action.smartSelect.expand" },
{ "key": "ctrl+shift+cmd+left",   "command": "editor.action.smartSelect.shrink"}
```

**Comment by 978165754** [comment]
@think2011 你好，windows电脑是哪个快捷键？好像没有cmd

**Comment by 978165754** [comment]
@think2011 你好，我找到了你说的这个，windows是alt+shift+left/right， 但是并不是复制功能，而是快速选中
