### ISSUE TITLE
Please keep existing Split Editor settings intact during version update

### ISSUE THREAD

**Issue by TLKG** [microsoft/vscode#81590]
It took me heck of time to find out the name "workbench.editor" something who controls it. But VSC version update erased it and set to vertical default. However type in "workbench.editor" can't find the split editor setting. It can't be found at setting now. Current VSC 1.38.1.

This is NOT what I had:
![image](https://user-images.githubusercontent.com/22269729/65823313-99d50100-e208-11e9-9bba-c5821559a936.png)

Please:
**1) keep existing setting during version update.
2) name it the same name in "settings" with the tooltip of the icon.**

**Comment by bpasero** [comment]
@TLKG what setting exactly are you referring to?
