### ISSUE TITLE
[json] Use textDocument.rangeFormatting.dynamicRegistration instead of workspace.symbol.dynamicRegistration?

### ISSUE THREAD

**Issue by iquiw** [microsoft/vscode#81592]
[VSCode JSON Language Server README](https://github.com/microsoft/vscode/blob/f2d41726ba5a0e8abfe61b2c743022b1b6372010/extensions/json-language-features/server/README.md#settings) says format option `is only applicable if the client supports dynamicRegistration for rangeFormatting`, while [the code](https://github.com/microsoft/vscode/blob/f2d41726ba5a0e8abfe61b2c743022b1b6372010/extensions/json-language-features/server/src/jsonServerMain.ts#L147) uses `workspace.symbol.dynamicRegistration`.

Should it use `textDocument.rangeFormatting.dynamicRegistration`?

[HTML](https://github.com/microsoft/vscode/blob/f2d41726ba5a0e8abfe61b2c743022b1b6372010/extensions/html-language-features/server/src/htmlServerMain.ts#L121) also does the same.

**Comment by aeschli** [comment]
Good catch! Thanks!

**Comment by iquiw** [comment]
`workspace.rangeFormatting.dynamicRegistration` => `textDocument.rangeFormatting.dynamicRegistration` ?

**Comment by aeschli** [comment]
Yes, my bad, thanks!

**Comment by iquiw** [comment]
Thank you!!
