### ISSUE TITLE
The function menu bar becomes a white background

### ISSUE THREAD

**Issue by zhangliqiang34** [microsoft/vscode#81598]
![QQ图片20190929151358](https://user-images.githubusercontent.com/30541603/65828281-cb62d080-e2cb-11e9-8ee2-07a4fb88ed9c.png)
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
<img width="892" alt="image" src="https://user-images.githubusercontent.com/30541603/65828264-8048bd80-e2cb-11e9-8729-a8bf2e7a6564.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/30541603/65828284-d0c01b00-e2cb-11e9-91dc-c8f0e0bfed18.png">

**Comment by chrmarti** [comment]
/needsMoreInfo

Which OS and VS Code version is this? What are the steps to reproduce the problem?

**Comment by zhangliqiang34** [comment]
[cid:image003.png@01D57855.44456710]

[cid:image005.png@01D57855.44456710]

Notebook model：thinkpad e480

[cid:image008.png@01D57855.44456710]

It was normal until now, but it has been updated to the latest version

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Christof Marti <notifications@github.com>
发送时间: Monday, September 30, 2019 3:02:41 PM
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: zhangliqiang34 <wuyaping34@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode] The function menu bar becomes a white background (#81598)


/needsMoreInfo

Which OS and VS Code version is this? What are the steps to reproduce the problem?

―

**Comment by chrmarti** [comment]
Please attach the screenshots through the GitHub website, they don't get through by mail.
