### ISSUE TITLE
vscode+wsl+zsh problem

### ISSUE THREAD

**Issue by txya900619** [microsoft/vscode#81599]
- VSCode Version:1.38.1
- OS Version:Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/23425966/65828665-e8010780-e2cf-11e9-95e2-be90526d6078.png)

In the external terminal all if good , but in the vscode something strange

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/needsMoreInfo

Could you explain what the problem is?

If it is the size: Does it fix itself when you resize the terminal / window?

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
