### ISSUE TITLE
Update extensions from command line

### ISSUE THREAD

**Issue by afattahi54** [microsoft/vscode#81597]
Currently there are commnands for install, list and uninstall extensions
```

code  --install-extension
code  --uninstall-extension 
code --list-extensions

```

I wish there was a command to **update extensions** from command line.

I am using chocolate package manager to keep all my software (including VSCode) updated. 
With this feature, I can write a simple scheduled task which updates its extensions too.

**Comment by sandy081** [comment]
`--install-extension` also updates the extension if it has an update.

**Comment by ndotb** [comment]
@afattahi54 I find it somewhat shameful that sandy081 and the vscode team at large are so callous and dismissive of the large global population that doesn't have broadband.

In searching for this same issue and seeing this poor response to our shared need, I've written a small bash script that I can add to cron:

```
#!/bin/bash
exts=($(code --list-extensions))
for ext in ${exts[*]}
do
        echo "checking $ext"
        code --install-extension $ext
done
```
