### ISSUE TITLE
Markdown footnote

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#81596]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

markdown footnote

Actually
![image](https://user-images.githubusercontent.com/27731323/65826362-4c16d200-e2b6-11e9-8be0-7ab1b75b63d3.png)
Expect
![image](https://user-images.githubusercontent.com/27731323/65826368-5769fd80-e2b6-11e9-8b43-ed7d07c61234.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.3.0
emojisense|bie|0.5.3
vscode-markdownlint|Dav|0.30.2
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.0.1
vsc-material-theme|Equ|30.0.0
code-runner|for|0.9.14
shell-format|fox|6.1.2
vscode-lombok|Gab|0.9.9
java-properties|ith|0.0.2
docthis|joe|0.7.1
intellij-idea-keybindings|k--|0.2.34
vscode-osgi|lgd|1.0.1
vscode-language-pack-zh-hans|MS-|1.38.4
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
sqltools|mtx|0.21.0
vscode-versionlens|pfl|0.24.0
vscode-spring-boot|Piv|1.11.0
material-icon-theme|PKi|3.9.0
java|red|0.49.0
vscode-xml|red|0.9.0
vscode-checkstyle|she|1.2.0
vscode-leetcode|she|0.15.5
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.4.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Try this extension https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes
