### ISSUE TITLE
[html] Autocomplete html tags

### ISSUE THREAD

**Issue by activebiz** [Microsoft/vscode#816]
It would be nice if it can autocomplete html closing tags. 
for e.g.
`  <template> `
`  </template>`

**Comment by aeschli** [comment]
Did you try the emmet completion?
Enter 'template' and press tab will complete to <template></template> 

Closing as works for me. Please reply if this isn't what you meant.

**Comment by kuncevic** [comment]
It wold of being nice to autocorrelate dom events too like if you tupe `<button (mouse...` expecting it will autocomplete with `mouseover`
