### ISSUE TITLE
Missing useful information in notifications

### ISSUE THREAD

**Issue by orshwartz** [microsoft/vscode#81608]
I create a new file, write some things without saving and then select in the menu:
Terminal >> Run Active File

I get the notification:
"Only files on disk can be run in the terminal"
but I ignore it for now. Later, I see there's a notification so I click the :bell: icon and see the above message, but there's no timestamp on it, some text from the file, the tab name or the exact name of the action I was doing to help me identify which file and which action this notification is about.

**Comment by Tyriar** [comment]
More of a general notification feature request than related to terminal.

**Comment by pappy74** [comment]
Trying to resurrect "show timestamp in Notifications" [here](https://github.com/microsoft/vscode/issues/171097). Please upvote if still interested!
