### ISSUE TITLE
files not shown

### ISSUE THREAD

**Issue by sarakanamumamahesh** [microsoft/vscode#81604]
Issue Type: <b>Bug</b>

after creating files from terminal files not shown in explorer,files shown when i reopend vs 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-64-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|5.72GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
vscode-markdownlint|Dav|0.30.2
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
java|vsc|1.0.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
angular2-inline|nat|0.0.17
angular-console|nrw|8.1.2
material-icon-theme|PKi|3.9.0
python|vsc|1.0.0
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|9.4.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
> files shown when i reopend vs

You restart VSCode?
