### ISSUE TITLE
Error on Ubuntu trying to debug using GDB "Invalid launch option type, is not supported"

### ISSUE THREAD

**Issue by wirecat** [Microsoft/vscode#8160]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04 LTS

I am quite new to VS Code and g++... so I am highly suspicious I am the problem. Submitting this issue because I am unable to find anything on SO, github, or google.

Steps to Reproduce:
1. Make a simple HelloWorld.cpp which contains hello world.
2. Compile using "g++: g++ -g HelloWorld.cpp".
3. Add the folder for HelloWorld.cpp to VSCode.
4. Go to the debug tab.
5. Add a debug configuration for "C++ (GDB)".
6. Modify the "program" field to point at the HelloWorld output. Mine is: "${workspaceRoot}/a.out"
7. Receive error: "error while processing request 'launch' (exception: Invalid launch option type, is not supported."

**Comment by zhu-liang** [comment]
Go the same problem here. For step 6, mine was using absolute directory of my g++ compiled binary.

**Comment by zhu-liang** [comment]
Please try add 
 "launchOptionType": "Local",
into your launch.json file and try again. Solved my side. Should be version problem.

**Comment by dbaeumer** [comment]
@wirecat do you have a C++ extension installed.

**Comment by wirecat** [comment]
I hve the C/C++ extension from M$ installed.

**Comment by wirecat** [comment]
@zhu-liang Thank you! After I updated the C/C++ extension and put that option in I was able to start debugging. Is this a long term fix or something temporary on the insiders build?
Unsure of if I should be closing this or not.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscppsamples#86

**Comment by dbaeumer** [comment]
Moving to the owners of the C++ extension then.
