### ISSUE TITLE
VS code not taking PATH of g++ in tasks.json

### ISSUE THREAD

**Issue by anupamkarn** [microsoft/vscode#81600]
- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create tasks.json for your c++ program
2. In Command write only g++
3. Try to build your program with Ctrl+Shift+B
4. The terminal will through an error of "The term 'g++' is not recognized as the name of a 
    cmdlet..." 
5. Change the command in tasks.json with the complete path of g++ in MingW folder, it starts 
    working

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Does it work when you enter `g++` in cmd window? Does it work when you enter it in the integrated terminal in VS Code?
