### ISSUE TITLE
缩进问题.

### ISSUE THREAD

**Issue by zengyuios** [microsoft/vscode#81605]
Issue Type: <b>Bug</b>

缩进经常会自动变成 空格:2, 就算手动设置成 制表符-4 , 还是会变成 空格:2

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (4.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
prettier-vscode|esb|2.3.0
code-runner|for|0.9.14
beautify|Hoo|1.5.0
node-module-intellisense|lei|1.5.0
vscode-fileheader|mik|0.0.2
vscode-filesize|mkx|2.1.3
vscode-language-pack-zh-hans|MS-|1.38.4
typescript-hero|rbb|3.0.0
autoimport|ste|1.5.3
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0

</details>

**Comment by Gameghostify** [comment]
I'm sorry, but are you sure that this is not due to your formatters settings? You might've set your `Beautify` extension to always format code to 2-space indentation.
