### ISSUE TITLE
Support for multiple non-root TypeScript folders in one project

### ISSUE THREAD

**Issue by patarapolw** [microsoft/vscode#81602]
For example, [my recent projects](https://github.com/patarapolw/zhlab) are like this

```
project/
  pages/
  posts/
  assets/
  web/               // Created by Vue CLI
    vue.config.json  // Read .. for static assets
    package.json
  server/            // My personally created TypeScript project
    src/
      declaration.d.ts
    package.json
  lib/               // Additional libraries I have to create, that may share between web and server, and probably with other projects
    lib1/
      package.json
    lib2/
      package.json
  .gitignore
  config.json        // Or YAML, for text-based config
  package.json       // For easy running of shell scripts, and for forcing Heroku to install Node buildpack
  Procfile
  README.md
```

In this case, I have problems with TypeScript failing to pickup `declaration.d.ts`, and `Vetur` failing to pick up `vuetify`.

Do I need to create multiple workspaces?

**Comment by chrmarti** [comment]
Try placing a `tsconfig.json` in the 'web' and one in the 'server' folder. You can configure these to pull in the 'lib' folders. https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by patarapolw** [comment]
@chrmarti My issue is `tsconfig.json` fails to recognize `/project/web/src/declaration.d.ts`. I am forced to use `/project/web/src/declaration.ts` and `import "./declaration"`.

**Comment by chrmarti** [comment]
https://stackoverflow.com/questions/48704150/how-to-configure-tsconfig-json-for-typings-not-in-types ?

**Comment by patarapolw** [comment]
It works, but VSCode detection is sometimes buggy. I have to close and open again.
