### ISSUE TITLE
buildin terminal

### ISSUE THREAD

**Issue by cichy** [microsoft/vscode#81618]
Issue Type: <b>Bug</b>

When I open two split terminal windows runing two servers and close then press up arrow key to return to the last command it works but termianal do not show exactly what I want, meant unecrypted bit code.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (1.80GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
graphql-for-vscode|kum|1.15.1
prisma|Pri|0.0.15

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

What do you expect to be shown and what is actually shown? Please attach a screenshot.

**Comment by cichy** [comment]
<img width="1280" alt="yournotwelcome" src="https://user-images.githubusercontent.com/443253/66150149-da6fb880-e614-11e9-8591-96eb99d164d4.png">
<img width="1280" alt="yourwelcome" src="https://user-images.githubusercontent.com/443253/66150151-da6fb880-e614-11e9-8f53-b51300966949.png">

**Comment by cichy** [comment]
left terminal => yarn start => ctrl + C => arrow up

**Comment by Tyriar** [comment]
^[[A means that what the program said to print after we sent it an up arrow. I suspect the up arrow was handled by your server before it actually terminated.
