### ISSUE TITLE
cannot consistently get vs to run ode

### ISSUE THREAD

**Issue by Nanda234** [microsoft/vscode#81617]
Issue Type: <b>Bug</b>

willing to just screen share or enable remote control of my comuter to the end of fixing whatever the issue is.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.14
vsliveshare|ms-|1.0.869
ruby|reb|0.25.3
vscode-zipexplorer|sle|0.3.1

</details>

**Comment by chrmarti** [comment]
/needsMoreInfo

What do you get as the output for:
```
code --verbose --disable-extensions
```

Please attach a screenshot.
