### ISSUE TITLE
Multi cursor selection does not work with Ctrl+Alt key combinations

### ISSUE THREAD

**Issue by amithegde** [microsoft/vscode#81611]
Issue Type: <b>Bug</b>

Looked through:
https://code.visualstudio.com/docs/getstarted/tips-and-tricks
https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier

Both `Ctrl+Shift+Alt+Down` and `Ctrl+Alt+Down` do not work for me. I have verified that user settings are not overriding these.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (39.32GB free)|
|Process Argv|D:\Code\ng-vibe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.2
xml|Dot|2.5.0
gitlens|eam|10.0.1
json-tools|eri|1.0.2
rest-client|hum|0.22.2
csharpfixformat|Leo|0.0.84
vscode-clang|mit|0.2.3
vscode-azureappservice|ms-|0.16.0
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
csharp|ms-|1.21.3
powershell|ms-|2019.9.0
debugger-for-chrome|msj|4.12.0
debugger-for-edge|msj|1.0.11
gremlins|nho|0.14.4
indent-rainbow|ode|7.4.0
better-readability-extension-pack|pin|2.0.0
LiveServer|rit|5.6.1
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|1.4.2
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
WebTemplateStudio-dev-nightly|WAS|0.0.1925201
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
Do we receive the `ctrl+alt+down` key combination from the OS?
:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
