### ISSUE TITLE
Compile errors are not supported by intellisense in real time

### ISSUE THREAD

**Issue by bastienJS** [Microsoft/vscode#8161]
- VSCode Version: 1.3.0 insider
- OS Version: win 10 x64

Steps to Reproduce:

1. Create a .ts file like an angular customer-edit.component.ts
2. Create another spec.ts file for the above .ts file.
3. Change the constructor of the customer-edit.component.ts by adding a parameter.
4. Open the "Error and Warnings"-Window
5. No errors are displayed although the spec.ts will not be able to compile due to a changed constructor in the customer-edit.component.ts.
6. OPEN the spec.ts file
7. Suddenly in the opened "Error and Warnings"-Windows you get the typescript error.
8. But thats far too late.
9. I do not want to click in every file to see the errors...

**Comment by dbaeumer** [comment]
We are exploring on a TS project builder (see June milestone plan). Still needs some work but will come.

**Comment by AltekkeE** [comment]
This was working in previous builds. Did something change?

**Comment by dbaeumer** [comment]
@AltekkeE See my comments in https://github.com/Microsoft/vscode/issues/8791

**Comment by dbaeumer** [comment]
Dups #8201
