### ISSUE TITLE
ESLint failed to load config file

### ISSUE THREAD

**Issue by DragonOsman** [microsoft/vscode#81612]
When I write code with ESLint enabled in VS Code, I get an error from ESLint saying:
```
ESLint: Failed to load config "default/configurations/eslint" to extend from. Referenced from: C:\Users\<name>\.eslintrc.  Please see ESLint output channel for details
```
How do I fix this problem?  I also don't know how to get to the ESLint output channel.  Any help is appreciated. Thanks.

**Comment by DragonOsman** [comment]
I don't think it's similar to those.  Is it okay to ignore the bot then?

**Comment by krnik** [comment]
You can get to the output by using `Ctrl+Shitf+U` on windows.
![image](https://user-images.githubusercontent.com/26797767/65855737-fc8ce080-e35f-11e9-8ec1-facee2426b2d.png)
From this dropdown select `ESLint`.
For much more info, please go to JSON Settings and add this line, it will increase the amount of information displayed in the output channel.
```
"eslint.trace.server": "verbose"
```

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-eslint/issues/765

**Comment by DragonOsman** [comment]
I opened that issue because I found out about that section of the repo later.  I just forgot to close this one after opening that one.  Sorry about that.  Anyway, I'll try out that advice and see what I get.  I'll post the output here.

**Comment by chrmarti** [comment]
Sorry, but this is not the right repository for ESLint questions.
