### ISSUE TITLE
mem/cpu usage 100% after install python extension while ssh

### ISSUE THREAD

**Issue by Leezj9671** [microsoft/vscode#81619]
- VSCode Version:1.3.81
- OS Version:Windows 10 1903

Steps to Reproduce:

1.Install remote-ssh, ssh to my vps 
2.Install python extension
3.VPS memory usage up to 100% and I do nothing, then ssh lose connect
![image](https://user-images.githubusercontent.com/11917826/65843494-7aeb8180-e364-11e9-85b2-c4e82b2aeefe.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
