### ISSUE TITLE
We cannot connect to the Extenions Marketplace at this time, please try again later

### ISSUE THREAD

**Issue by fcbogle** [microsoft/vscode#81615]
Issue Type: <b>Bug</b>

Using Mac OS Mojave and the latest version of VS Code.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.21GB free)|
|Process Argv|-psn_0_278596|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by fcbogle** [comment]
![Screenshot 2019-09-29 at 19 15 20](https://user-images.githubusercontent.com/15067498/65837310-8f406780-e2ed-11e9-8617-83a81a7281df.png)

**Comment by chrmarti** [comment]
Is this intermittent or permanent? Are you behind a network proxy?

**Comment by fcbogle** [comment]
Hello and thank you for responding. The issue is permanent and I am not using any proxy. I have an iMac connected to a wireless router and the public Internet. I am using the software from home so there is no proxy in place. Regards

**Comment by sandy081** [comment]
Can you please open developer tools using `F1 > Developer Tools` and see if there are any errors in the console or network tab.

Also open Shared Process `F1 > Toggle Shared Process` and see if there are any errors there?

**Comment by fcbogle** [comment]
Hello, 
I am away from the machine until Friday this week. Can you please suggest the commands to follow for use of a Mac? I'd appreciate that i.e. there is no F1 on a mac. Regards

**Comment by sandy081** [comment]
> there is no F1 on a mac

Weird, it should be. It is Function F1 command. If you have touch bar press `fn` command to see the function commands.

F1 is to open command pallette.. You can also open it from bottom left settings icon.

**Comment by lakshaymalhotra** [comment]
hey @sandy081 , i am facing a similar error 
![problem](https://user-images.githubusercontent.com/33951245/66201051-01cf8f80-e6c0-11e9-89ce-871c10591704.PNG)

![Capture](https://user-images.githubusercontent.com/33951245/66200968-d2b91e00-e6bf-11e9-98ec-2b369969988a.PNG) error as shown in developer tools , no errors in toggle shared process

**Comment by fcbogle** [comment]
error in toggle shared process:

![Screenshot 2019-10-04 at 15 34 23](https://user-images.githubusercontent.com/15067498/66216053-a354e200-e6bc-11e9-918a-e509cd6cfa7e.png)

**Comment by fcbogle** [comment]
Hello @sandy081 is there any update on the problems faced here please?

**Comment by rsramkis** [comment]
I have a marketplace that just tries to refresh but nothing is showing. This is what i see in the developer console (system is Manjaro with GNOME 3.34).

![Screenshot from 2019-10-14 19-19-58](https://user-images.githubusercontent.com/14362317/66789075-095d1880-eeb8-11e9-8d50-488c71b67106.png)

**Comment by linanaliu51k** [comment]
try this way to install extensions, code --install-extension octref.vetur-0.22.6.vsix, it works for me

**Comment by sandy081** [comment]
@fcbogle Sorry I missed this notification.

I see from your screenshot that the extensions folder does not exist. Can you please try the following command and see if everything is good with your extensions folder

`View > Command Pallette... > Extensions: Open Extensions Folder`

**Comment by huntermaxfield** [comment]
![Screen Shot 2019-12-31 at 12 12 13 PM](https://user-images.githubusercontent.com/11686627/71631631-e42e9b00-2bc6-11ea-86d7-e8fce1cc806a.png)
![Screen Shot 2019-12-31 at 12 12 38 PM](https://user-images.githubusercontent.com/11686627/71631632-e42e9b00-2bc6-11ea-9fdc-663cce33b067.png)

I'm having a similar issue.  I've attached the output of the developer tools console as well as my extensions folder.  any help here?
