### ISSUE TITLE
Adding a paste keybinding turns off the defaults?

### ISSUE THREAD

**Issue by greggman** [microsoft/vscode#81629]
- VSCode Version: 1.38.1
- OS Version: MacOS

Steps to Reproduce:

1. In your keybindings.json add 

    ```
      { "key": "ctrl+v",  "command": "editor.action.clipboardPasteAction" },
    ```

2. Copy a word
3. Press Cmd-V (not ctrl-v). See it pastes
4. Press Ctrl-V. See it also pastes
5. Press Cmd-F (for find)
6. Press Cmd-V. See it does not paste

Does this issue occur when all extensions are disabled?: Yes

Maybe that is working as intended. The workaround for me was to add Cmd-V in keybindings.json but it seems like it might be bug since Cmd-V is still working (as expected) in the editor, just not in the find UI

**Comment by alexandrudima** [comment]
The keybinding for pasting in native inputs like the find widget works in very funny ways on macOS --- through the menu. If the menu does not have `cmd+v` next to paste, then `cmd+v` does not end up triggering a paste... 

See in depth explanation at https://github.com/microsoft/vscode/issues/74599#issuecomment-516303916

So you would simply need to repeat the defaults after your custom ones, thus making the defaults the "preferred" ones again and they would show up in the top level menu which would cause `<input>`s to support paste:
```
{ "key": "ctrl+v", "command": "editor.action.clipboardPasteAction" },
{ "key": "cmd+v", "command": "editor.action.clipboardPasteAction",
  "when": "textInputFocus && !editorReadonly" },
```
