### ISSUE TITLE
Quick fix of Java imports broken

### ISSUE THREAD

**Issue by NikTJ777** [microsoft/vscode#81623]
I have recently upgraded to 1.38.1.
I am now getting broken "import" statements inserted when I use the "Quick Fix".

- VSCode Version:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 16.7.0

- OS Version:
OSX 10.12.6

Steps to Reproduce:

1. Type some Java code that references a class that has not yet been imported
2. hover on the class name, and select "Quick Fix"

Results are that the "import" statement has been truncated - and the following line gets deleted.

Example:

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Scope;
import org.springframework.boot.autoconfigure.condition.Condit

import org.springframework.beans.factory.annotation.Autowired;
  
 * JsonInstructionProcessor
 * InstructionProcessor for generic Json data
 */
@Component
@ConditionalOnProperty("in.mq")

In the example above, the quick fox for "@ConditionalOnProperty" has inserted the line:
"import org.springframework.boot.autoconfigure.condition.Condit"
and previously inserted import for @Component has been deleted.

Note that the first line of the class-level comment: "/**" has also been deleted, when one of he previous imports was inserted.

Does this issue occur when all extensions are disabled?: Yes/No
Not Applicable.
"Quick Fix"  is not available if all extensions are disabled.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Java extension. Please file a new issue for it: https://github.com/redhat-developer/vscode-java/issues

**Comment by NikTJ777** [comment]
@chrmarti Thank you for the link to the Java extension Repo.

I searched in: https://github.com/Microsoft/vscode/wiki/Related-Projects
for the Java extension, and not finding it there, plus knowing the extension is shipped by Microsoft, I inferred that this was the best place to file my report.

Cheers!
Nik
