### ISSUE TITLE
Redundant blanks in the console make it impossible to copy text

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#81620]
![3333](https://user-images.githubusercontent.com/27546390/65845715-e423c280-e36d-11e9-80f1-27e7e23e6d38.png)
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by 395053994** [comment]
This problem has always existed and no one has solved it.




------------------ 原始邮件 ------------------
发件人: "vscodebot[bot]"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 上午10:37
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Console blank cannot copy text (#81620)




(Experimental duplicate detection)
 Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
  
did not run (#78164) 
 
Extensions don't install (#78873) 
 
Bug Scroll (#77770) 
 
Git not working (#78311) 
 
Debugger not working (#77477)

**Comment by isidorn** [comment]
The gaps are not related to copying. For copying please find duplicate issues in our repository.
As for the gaps, they are there due to clarity and indentiation. Though leaving this open to see if other users also complain and we migh consider addressing this in the future. Thanks
