### ISSUE TITLE
error on trying to open terminal

### ISSUE THREAD

**Issue by Condamner** [microsoft/vscode#81625]
We hav
Issue Type: <b>Bug</b>

When trying to open the terminal with Ctrl `, Visual Studio Code shows the error: The terminal process terminated with exit code: 4294967295.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
easy-cpp-projects|ACh|1.7.7
code-gnu-global|aus|0.2.2
gitkraken-glo|axo|1.1.0
vscode-standardjs-snippets|cap|0.8.7
vscode-standardjs|che|1.2.3
npm-intellisense|chr|1.3.0
c-cpp-compile-run|dan|0.5.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.0.1
tslint|eg2|1.0.44
prettier-vscode|esb|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
sublime-babel-vscode|jos|0.2.10
chat|kar|0.22.1
vscode-github|Kni|0.30.2
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
cpptools|ms-|0.25.1
vsliveshare|ms-|1.0.869
debugger-for-chrome|msj|4.12.0
live-server-preview|neg|0.1.4
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.0
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
stylelint|shi|0.51.0
python|tht|0.2.3
vscode-icons|vsc|9.4.0
html-css-class-completion|Zig|1.19.0
livereload|zii|0.2.5

</details>
e written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by chrmarti** [comment]
/needsMoreInfo

What are your settings for the terminal?

![image](https://user-images.githubusercontent.com/9205389/65858832-32819300-e367-11e9-991f-91e7c2934e88.png)

**Comment by sbrin** [comment]
> /needsMoreInfo
> 
> What are your settings for the terminal?

Hi. I've got the same issue.

My settings is default. I try different options but get no effect.

The only difference is:
- when i enable "Windows Enable Conpty" option, i get the same error, but also i got a terminal in separate window
- without "Windows Enable Conpty" i only got an error message

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
