### ISSUE TITLE
There are many gaps when copying text in the console

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#81621]
We have written the needed data into your clipboard because it was too large to send. Please paste.

![44444](https://user-images.githubusercontent.com/27546390/65846019-ecc8c880-e36e-11e9-8177-131ca27f5679.png)

**Comment by 395053994** [comment]
This problem has always existed and no one has solved it.


------------------ 原始邮件 ------------------
发件人: "vscodebot[bot]"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 上午10:45
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] There are many gaps when copying text in theconsole (#81621)




(Experimental duplicate detection)
 Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
  
did not run (#78164) 
 
Extensions don't install (#78873) 
 
Bug Scroll (#77770) 
 
Git not working (#78311) 
 
Debugger not working (#77477)

**Comment by chrmarti** [comment]
Related #81620
