### ISSUE TITLE
Debug: inline breakpoint is not vertically centered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81624]
I noticed that the new inline debug breakpoints do not have the same height as the editor line and as such appear not centered. 

![image](https://user-images.githubusercontent.com/900690/65853110-b1bb9a80-e358-11e9-9061-249a23e3699d.png)

**Comment by isidorn** [comment]
There height should depend on the font. Maybe I did not get this correctly, thus assigning to this milestone to investigate and fix.

**Comment by isidorn** [comment]
Fixed via 1f70a46308
Now the inline breakpoint widget has the same size as the editor line height and updates when editor configuraiton changes.
![Screenshot 2019-10-02 at 12 05 11](https://user-images.githubusercontent.com/1926584/66036186-ea9c7080-e50c-11e9-912d-f94a5f2e814e.png)
