### ISSUE TITLE
Only immediate file/folder symlinks show up in Explorer panel

### ISSUE THREAD

**Issue by bilogic** [microsoft/vscode#81622]
- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 6.1.7601

I share a Windows folder i.e. ```D:\shared``` with my VirtualBox's Centos via the ```Shared Folder``` setting.
When I create symlinks inside my project folder from Centos, i.e. ```D:\shared\project```, only some of them show up in the ```Explorer panel``` of Windows VS Code. I refer to these as immediate symlinks, please see below for clearer examples.

Steps to Reproduce:

1. Change folder to ```/shared/project```, i.e. ```D:\shared\project```
2. ```ln -s ../repo/ slinkfolder1``` - trying to link to ```D:\shared\repo```, a parent folder
3. ```ln -s storage/app/ slinkfolder2``` - trying to link to ```D:\shared\project\storage\app```, a child folder
4. ```ln -s storage/ slinkfolder3``` - trying to link to ```D:\shared\project\storage```, an immediate folder
5. ```slinkfolder1``` and ```slinkfolder2``` does not show up in the ```Explorer panel```, only ```slinkfolder3``` can be located

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by chrmarti** [comment]
/needsMoreInfo

What does the Windows file explorer show?

**Comment by bilogic** [comment]
Windows file explorer shows all 3 as 0 byte files, unable to follow the symlinks at all.

And since VS Code is able do something different and follow ```slinkfolder3```, it figures that VS Code contains code to follow symlinks. 

As it follows only ```slinkfolder3``` and not the other 2, perhaps there is an issue.

**Comment by isidorn** [comment]
Looks like a dup of https://github.com/microsoft/vscode/issues/75907

**Comment by bilogic** [comment]
@isidorn In my case, the scenario in #75907 worked, i.e. in my case I can see ```what``` inside folder ```a```, I suspect #75907 has somehow been fixed but not totally.

**Comment by isidorn** [comment]
I can reopen this one. Would you like that? However I have no immediate plans to look into this.

**Comment by bilogic** [comment]
Yes, please reopen. Thank you.

**Comment by bilogic** [comment]
@isidorn I played around with it and think I got it figured out. 

The issue is with the back and forward slashes. Centos creates symlinks that have ```/``` as folder separators that Windows VS Code Explorer panel and Windows File Explorer do not accept, thus File Explorer can't use it and VS Code Explorer panel don't show it.

In contrast, when I have "immediate" symlinks, they do not contain any ```/```, thus they show up properly. 

I'm confident this is the issue as the symlinks created by Centos can be seen using a ```dir``` in Windows Command Prompt, it implies Centos is creating them correctly for Windows to recognize them as symlinks.

I hope this info can help you find a quick fix. Thank you.

**Comment by bilogic** [comment]
These are my findings:

A. SYMLINK, [../../realfolder]
- CentOS cd/ls: can follow
- Windows File Explorer: **cannot** follow
- Windows VS Code Explorer panel: **cannot** expand
- Windows VS Code Ctrl-P: **cannot** find files in target

B. SYMLINK, [..\..\realfolder]
- CentOS cd/ls: can follow
- Windows File Explorer: can follow
- Windows VS Code Explorer panel: can expand
- Windows VS Code Ctrl-P: **cannot** find files in target

C. SYMLINKD, [..\..\realfolder]
- CentOS cd/ls: can follow
- Windows File Explorer: can follow
- Windows VS Code Explorer panel: can expand
- Windows VS Code Ctrl-P: can find files in target

Observations and remarks:
1. It is puzzling why VS Code Explorer panel and Ctrl-P are using different mechanisms to enumerate files and folders
2. CentOS does not seem to have a way to create SYMLINKD, which is what is required to work in all scenarios

**Comment by bilogic** [comment]
This seems like a pretty simple fix, can we get Windows VS Code Ctrl-P to work with Scenario B. SYMLINK [..\..\realfolder]? Thanks

**Comment by isidorn** [comment]
If it is a simple fix we are open for an elegant PR that fixes this.
