### ISSUE TITLE
Can't open multiple markdown file preview panes.

### ISSUE THREAD

**Issue by srcdes** [microsoft/vscode#81639]
- VSCode Version: 1.38.1
- OS Version: 10.14.6

Steps to Reproduce:

1. When multiple markdown files exist, i can open one markdown's preview only.
2. Even though i open a new vscode window, they are synced with opened markdown file for preview window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
See the documentation here: https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking
