### ISSUE TITLE
Test Consider API for changing tree view title dynamically

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81635]
refs: https://github.com/microsoft/vscode/issues/80208

- [x] anyOS @isidorn
- [x] Windows @dbaeumer 

Complexity: 3

Test the proposed `title` `TreeView` API:
```typescript
	export interface TreeView<T> {
		/**
		 * The name of the tree view. It is set from the extension package.json and can be changed later.
		 */
		title?: string;
	}
```
The tree view sample extension is a good place to start: https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/testView.ts#L6
- Verify that the inline documentation makes sense.
- Verify that the title of the tree view is correctly sourced from the package.json first
- Verify that you can get the title as set in the package.json even if you never set it.
- Test that you can always get the title.
- Test that you can change the title

**Comment by isidorn** [comment]
Works nicely, nice job! I have tested on the macOS.
