### ISSUE TITLE
introduce Gesture.removeTarget so the addTarget stops leaking

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81630]
Code pointer https://github.com/Microsoft/vscode/blob/3259fbf2674e738233acbec7d8086f9e1ba2d692/src/vs/base/browser/touch.ts#L89

Assigning first to September but might be pushed to next milestone debt week.

**Comment by isidorn** [comment]
Actually the addTarget should just return a `disposable`. That wil be the neatest approach.

**Comment by sbatten** [comment]
oops^
