### ISSUE TITLE
Loose IntelliSense for angularjs updating from 0.10.9

### ISSUE THREAD

**Issue by miguelchico** [Microsoft/vscode#8163]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:
I´m moving from version 0.10.9 to 1.2.1 and I´ve lost IntelliSense information

1. Create a project
2. Create an angular 1 controller like this:
![image](https://cloud.githubusercontent.com/assets/6106661/16364726/95a2ab8c-3bee-11e6-979a-dcd5a0a5757b.png)
3. Create a jsconfig.json like this:

![image](https://cloud.githubusercontent.com/assets/6106661/16364735/aea05012-3bee-11e6-9dee-7cabcc511023.png)
4. Using [typings](https://github.com/typings/typings) install angular TypeScript definition

In version 0.10.9 IntelliSense was working in all places I needed in this controller.
It was working in angular:
![image](https://cloud.githubusercontent.com/assets/6106661/16364791/9f44474e-3bef-11e6-9ade-d2ac896bb069.png)

And it also was working in injected dependencies:
![image](https://cloud.githubusercontent.com/assets/6106661/16364798/c73f0fe0-3bef-11e6-9935-608f30801854.png)

From version 0.10.11 the IntelliSense information for the same file and same project is different.
It still work in angular but it doesn't for injected dependencies anymore:
![image](https://cloud.githubusercontent.com/assets/6106661/16364807/0cd108ec-3bf0-11e6-93ad-be933c3ea053.png)

I've tried with versions 0.10.11 and 1.2.1 and it doesn't work.
I've checked the release notes from 0.10.9 to 1.10.11 and the main difference was the inclusion of Salsa, but I couldn't find any change I have to do in my project to keep it working.

Any suggestion?

**Comment by dbaeumer** [comment]
@egamma assigning to you since you provided quite some support for people switching over to Salsa.

**Comment by egamma** [comment]
@miguelchico we are sorry, but support for intellisense for injected dependencies has been lost as part of the migration to the new Salsa implementation.

**Comment by egamma** [comment]
@miguelchico did you try to type the injected dependencies using JS Doc comments?
https://code.visualstudio.com/docs/languages/javascript#_intellisense

**Comment by miguelchico** [comment]
@egamma that's a pitty....

Yes, I tried using JS Doc comments and it works, but now I have to write a lot of types manually in my comments and maintain them.

There is no play to get back the support?

Thank you.

**Comment by egamma** [comment]
@miguelchico 

>There is no play to get back the support?

To be honest, we did something very 'pragmatic'/hackish to enable this in the past. pls file a feature request against the TypeScript project https://github.com/Microsoft/TypeScript/issues/new

**Comment by bmontgom** [comment]
@miguelchico Did you ever file a feature request? I'm wanting this feature as well.

**Comment by miguelchico** [comment]
I've done right know.

https://github.com/Microsoft/TypeScript/issues/9600

@egamma, could you please check if it's what you needed?

**Comment by bmontgom** [comment]
Thanks, @miguelchico.
@egamma, is this something that will be difficult for the VSCode team to do, and as such should I expect this to take a long time (more than a month) to become available again?

**Comment by egamma** [comment]
@miguelchico issue LGTM, thanks. 

@bmontgom the JS language service is done by the TS team, if they do it (will talk to them), then it would be in a future TypeScript release.

Closing this issue, since it is now tracked in TypeScript repository.

**Comment by egamma** [comment]
@bmontgom @miguelchico one immediate workaround would be to augment one of the JSDoc comment generator extensions and make it angular aware so that it generates the JSDoc comments.

https://marketplace.visualstudio.com/items?itemName=stevencl.addDocComments
https://marketplace.visualstudio.com/items?itemName=joelday.docthis
