### ISSUE TITLE
Regex: \w ignores Latin characters

### ISSUE THREAD

**Issue by pepinows** [microsoft/vscode#81645]
Issue Type: <b>Bug</b>

Given a string: 'O ladrão roubou pão'
'\w' pattern on regex doesn't catches the 'ã' or any other accented letters.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.1.7601

**Comment by IllusionMH** [comment]
/question

`\w` is the same as `[a-zA-Z0-9_]` which shouldn't catch accented letters by design.

You need to use [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) to match any **letter**. In your case it can be `\p{L}`.

**Comment by pepinows** [comment]
![image](https://user-images.githubusercontent.com/32179528/65889415-9a3fda00-e377-11e9-9a28-ddcf47ce7777.png)
What i am doing wrong?

**Comment by IllusionMH** [comment]
You shouldn't put `\p{L}` into character set (inside `[]`), it looses its meaning and in the end you just added `{}` to the list of characters to match.

Just use `\p{L}`.
![image](https://user-images.githubusercontent.com/1312662/65890230-3505dc00-e3ab-11e9-98a6-9f06705b0019.png)

**Comment by pepinows** [comment]
![image](https://user-images.githubusercontent.com/32179528/65890418-3d452380-e379-11e9-9049-cee7b687dd9d.png)
It simply hate me?

**Comment by IllusionMH** [comment]
Looks like it doesn't work in Stable, but works in Insiders https://code.visualstudio.com/insiders

**Comment by pepinows** [comment]
![image](https://user-images.githubusercontent.com/32179528/65893441-556b7180-e37e-11e9-82fb-2c4021f37b71.png)
i'm really intriged now
