### ISSUE TITLE
Debug panel title header actions are broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#81649]
![image](https://user-images.githubusercontent.com/10746682/65883622-b2bfec80-e397-11e9-9ec7-685d70e01617.png)

**Comment by isidorn** [comment]
This is the collapse all action missing. Which is right there in the explorer.
@misolori looks like a regression from the font work. Can you investigate please?

**Comment by misolori** [comment]
@isidorn fixed now, didn't realize the debug viewlet was using icons from the explorer so I added those svgs back as the debug viewlet hasn't adopted the new icon font yet:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/35271042/65902619-b3dd2380-e36f-11e9-91a2-da691d36d57a.png">

**Comment by isidorn** [comment]
Thanks, owkrs liek a charm in latest -> adding verified label
