### ISSUE TITLE
getRecentlyOpened Method Not Found

### ISSUE THREAD

**Issue by kpascascio** [microsoft/vscode#81643]
- VSCode Version: Version: 
1.39.0-insider
Commit: e0762af258c0b20320ed03f3871a41967acc4421
Date: 2019-09-27T05:25:18.884Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
- OS Version: Darwin x64 18.7.0
![image](https://user-images.githubusercontent.com/7727018/65880571-01ea2b00-e360-11e9-8ee8-d01bd422c2e8.png)

Steps to Reproduce:

1. Open new Visual Studio Code Insiders Edition
2. Click on More...
![image](https://user-images.githubusercontent.com/7727018/65880635-1a5a4580-e360-11e9-87f3-8381766af654.png)
3. Error message at the bottom pops up 
![image](https://user-images.githubusercontent.com/7727018/65880685-2ba35200-e360-11e9-8fa0-a79c46def34c.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Additional Details:
Also from the tool bar menu 
![image](https://user-images.githubusercontent.com/7727018/65881008-b71ce300-e360-11e9-8e8d-33191c5062e4.png)

**Comment by chrmarti** [comment]
Still in today's Insiders? (Cannot reproduce.)

**Comment by kpascascio** [comment]
I was off a commit I guess, although VSCode said it was the most recent and there wasn't any Updates 😅. A full system restart was the trick, it might've been a cache issue 🤔
