### ISSUE TITLE
Dimmed / desaturated colors / font rendering issue on latest Insiders build (macOs)

### ISSUE THREAD

**Issue by infctr** [microsoft/vscode#81642]
- VSCode Version:
```sh
❯ code-insiders -v
1.39.0-insider
9f6a745027fc7b2a12495970f64625e24f410224
x64
```
- OS Version:
Mojave 10.14.6 (18G95)

After updating to latest Insiders build all the colors in the editor and explorer look strikingly dimmed / desaturated. No settings were changed during the udpate, so that seems like a regression to me. Used color theme Monokai

Were there any changes to color display specific to mac?

You can still see vibrant colors in the minimap tho

 
![image](https://user-images.githubusercontent.com/15550153/65877728-0aa92400-e395-11e9-9c47-4774cb802334.png)

Same on a stable release

![image](https://user-images.githubusercontent.com/15550153/65882673-26fd8e80-e39e-11e9-9aac-3eb840f811ef.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by infctr** [comment]
Now it more seems like a font rendering issue 

Insiders
![image](https://user-images.githubusercontent.com/15550153/65887658-fbcb6d00-e3a6-11e9-8ace-330971ed54ff.png)
Stable
![image](https://user-images.githubusercontent.com/15550153/65887613-e8200680-e3a6-11e9-9c69-34c3057d71bf.png)

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by infctr** [comment]
@bpasero Thanks for the update!


So from left to right
**Stable**
```sh
❯ code -v
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
```
**Insiders**
```sh
❯ code-insiders -v
1.39.0-insider
313ede61cbad8f9dc748907b3384e059ddddb79a
x64
```
Explorations
```sh
❯ code-exploration -v
1.37.0-exploration
960208fdf9aa06e6892aa14c9c84ddd607fbeb2f
x64
```

The rendering issue seems to be gone on the Insiders build, the Explorations looks werid tho

![image](https://user-images.githubusercontent.com/15550153/66641214-fa116d00-ec22-11e9-8cbd-57a0f9471af7.png)

**Comment by bpasero** [comment]
Thanks, this is fixed then. Our exploration build had an old E version.

**Comment by rodolphito** [comment]
I'm getting this issue on the latest VS Code (non-insiders) version. Everything just looks washed out, on all panels. It autoupdated this morning and something was off but I assumed it was just too much light from outside. The night fell and I stopped believing so I went and checked.
<img width="89" alt="Screen Shot 2019-11-08 at 4 34 01 AM" src="https://user-images.githubusercontent.com/11307157/68476995-1cc28180-01e1-11ea-8dff-5c074d416e53.png">
<img width="76" alt="Screen Shot 2019-11-08 at 4 34 14 AM" src="https://user-images.githubusercontent.com/11307157/68476998-1df3ae80-01e1-11ea-99e5-fee9063e6ae0.png">
Is this fixed in some unreleased version?

**Comment by infctr** [comment]
Oh my god, I can't believe you did this again. Just updated to latest Stable version 

```sh
❯ code -v
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64
```

Font rendering seems fine, but the colors are dimmed

![image](https://user-images.githubusercontent.com/15550153/68489106-7bc2dd80-0257-11ea-9236-ae63402b6c0d.png)
