### ISSUE TITLE
Files and folders opened with VSCode from WSL are locked

### ISSUE THREAD

**Issue by inyoka** [microsoft/vscode#81647]
When using VSCode with WSL it locks all the files and folders, preventing the editing of files outside of VSCode, or with other programs such as GitHub Desktop unless VSCode is shutdown first.  It also prevents the renaming of folders from within VSCode.

Note : Files edited outside of WSL are not locked.  I have reinstalled VSCode and VS Remote Development TNA.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17758
Remote OS version: Linux x64 4.4.0-17758-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17758-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.89GB (5.63GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
hide-gitignored|npx|1.0.1
html-snippets|abu|0.2.1
flask-snippets|cst|0.1.1
dotenv|mik|1.0.1
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
jinjahtml|sam|0.10.6

</details>

**Comment by aeschli** [comment]
Is https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace
what you are seeing?

**Comment by inyoka** [comment]
Yes, setting **remote.WSL.fileWatcher.polling** to **true** in VSCode settings fixed the issue.  
If anyone else has this problem to get **git** / **GitHub Desktop** working again I also had to run :

`$ git gc --prune=now`
`$ git remote prune origin`

It seems WSL2 will fix this.

Many thanks for your help @aeschli
