### ISSUE TITLE
Remember scroll position on Markdown Preview

### ISSUE THREAD

**Issue by joelbiffin** [microsoft/vscode#81646]
Similar to in code editor windows, it would be useful if Markdown preview windows would remember the current scroll position in the file so that re-opening the window would take us back to the same scroll position as we left it in.

**Comment by mjbvz** [comment]
Please provide the exact steps to reproduce this issue

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as not actionable with out repo steps
