### ISSUE TITLE
Add modifier setting for clicking on links in terminal

### ISSUE THREAD

**Issue by zao** [microsoft/vscode#81640]
It seems that on my Ubuntu Linux you need to (nowadays?) in VS Code hold Alt and click on a link in the integrated terminal to open it.

On my reasonably common desktop environment (XFCE4), Alt-click moves the window and I would as such like to change the modifier key to something that would actually reach the window, like Ctrl.

I couldn't find such a setting and it'd be great if it would be possible to modify the modifier.

**Comment by Tyriar** [comment]
ctrl is the default, it will change to alt if you modified `editor.multiCursorModifier`.

/duplicate #3130

**Comment by zao** [comment]
Oh. Oooh.

So you're saying that if I've altered `editor.multiCursorModifier` to be able to place cursors with Ctrl, the modifier to open links silently flips to being Alt? I parsed this comment and other issues about this to be that the key you configured to be the multi-cursor key would also be the URL key.

Considering I've got a completely unused Windows key on my keyboard, it would still be nice if it would be possible to override this auto-mapping. As it stands now, I have to choose between having multiple cursors and having clickable file locations in my terminal build output, both of which are rather useful things to have.

**Comment by zao** [comment]
I was going to mention a perceived lack of documentation on this, but apparently it's kind of documented at https://code.visualstudio.com/docs/editor/codebasics if you know to look under a completely different heading than what you're actually doing.

**Comment by Tyriar** [comment]
Yeah there's a bit of a problem on Linux, you can either unbind the OS-level alt+click binding or wait until we have a more robust system for customizing mouse shortcuts (#3130).

**Comment by zao** [comment]
Considering that multi-selection is not a thing that you can do in the terminal at all, couldn't the shortcut in the terminal stay the same regardless of how someone has changed their editor pane preferences?

I guess that it might be weird to have different modifiers for users depending on if they are in the terminal or editor panes if someone has changed the multi-select modifier.

For me there's a significant difference between being to click links in the editor (something which I can sacrifice trivially) and clicking on tool output in the terminal to navigate to source positions.

It's unfortunately unfeasible to change the window manipulation action for me, it's so deeply rooted in muscle memory that even attempting to map it to another modifier breaks my ability to work effectively. I guess I've got to sacrifice multi-selection and wait for future improvements.

**Comment by Tyriar** [comment]
@zao the consistency problem is the main thing, people would have the inverse complaint when not on Linux. The best thing you can do to push this along is vote on https://github.com/microsoft/vscode/issues/3130, it's one of the top voted items right now which is one of the things that feeds into our prioritization.
