### ISSUE TITLE
Relaunching insiders with custom CLI Args fails due to missing 1.39.0-insider-main.sock

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#81652]
Version: 1.39.0-insider
Commit: 601e3e0762ac93e03cfef8336be8223bf32754e1
Date: 2019-09-30T05:30:22.799Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Download VS Code Insiders
2. Launch Insiders with custom cli args as follows:
Each argument is in a separate line for brevity
```'<vs code dir>/Visual Studio Code - Insiders.app' --user-data-dir='<user dir>'```
3. Exit VS Code after a few seconds.
4. Run the same command once again, and here's the error that is logged:
```
[main 2019-09-30T14:32:33.883Z] Could not delete obsolete instance handle Error: ENOENT: no such file or directory, unlink '<user dir>/1.39.0-insider-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at Object.doStartup (<vs code dir>/Contents/Resources/app/out/vs/code/electron-main/main.js:534:676)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '<user dir>/1.39.0-insider-main.sock'
}
[main 2019-09-30T14:32:33.886Z] Error: ENOENT: no such file or directory, unlink '<user dir>/1.39.0-insider-main.sock'
    at Object.unlinkSync (original-fs.js:976:3)
    at Object.doStartup (<vs code dir>/Contents/Resources/app/out/vs/code/electron-main/main.js:534:676)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(base) 

```

Does this issue occur when all extensions are disabled?: N/A

**Comment by bpasero** [comment]
@DonJayamanne does not reproduce with stable?

**Comment by DonJayamanne** [comment]
No it doesn't

**Comment by bpasero** [comment]
@DonJayamanne I cannot reproduce, but I wonder how you start code from the command line. Are you literally putting in the path to the application bundle? Why not just `code-insiders`

@joaomoreno I wonder what could be going on here:
* starts vscode
* we try to connect to `environmentService.mainIPCHandle` because serving from that handle failed
* this fails again
* now we try to delete the handle and this fails too
* from this moment on we seem to be throwing that error but the comment reads:

```ts
// it happens on Linux and OS X that the pipe is left behind
// let's delete it, since we can't connect to it and then
// retry the whole thing
```

But there is no retry? Did we maybe loose this code during some refactoring?

**Comment by DonJayamanne** [comment]
> cannot reproduce, but I wonder how you start code from the command line. Are you literally putting in the path to the application bundle? Why not just code-insiders

I launch it manually, as this isn't my system wide install of insiders.

**Comment by bpasero** [comment]
@DonJayamanne don't you have to put a `open` command before the `.app` file? What is the full command line?

**Comment by DonJayamanne** [comment]
Sorry, i removed that bit just to make it more readable, here's the full command line:
`'/Users/donjayamanne/Desktop/Development/vsc/pythonVSCode/uitests/.vscode test/insider/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' --user-data-dir='/Users/donjayamanne/Desktop/Development/vsc/pythonVSCode/uitests/.vscode test/user'`

**Comment by bpasero** [comment]
@DonJayamanne ok thanks, still does not reproduce for me. If it is Electron related, we just reverted back to Electron 4. Can you reproduce in todays insider?

**Comment by DonJayamanne** [comment]
Still the same problem.

**Comment by joaomoreno** [comment]
> But there is no retry? Did we maybe loose this code during some refactoring?

No, still looks the same. We try to delete it. If we delete it, we were correct in assuming that _the pipe was left behind_. If we can't delete it (and we can't connect to it)... something is really wrong. So we throw hands up since we ran our of options to create the socket.

**Comment by joaomoreno** [comment]
@DonJayamanne Does the `*.sock` file exist in there? What are its permissions?

**Comment by DonJayamanne** [comment]
There are no *.sock files in there.

**Comment by joaomoreno** [comment]
What about another user data dir? Does that work? Is the one you're using in a special file system (eg. network drive)
