### ISSUE TITLE
Error when Download command is used on a folder

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81654]
- Connect to a remote
- Right click on a folder in the explorer
- Click "Download"
- See an error notification pop up, "Unable to open '<folder name>': File is a directory"

But I do get the save as dialog and can download the folder.

**Comment by bpasero** [comment]
@isidorn this reproduces with 1.39 stable for me:

![image](https://user-images.githubusercontent.com/900690/65939122-44297000-e425-11e9-8ac1-d4ab04a64c00.png)

`ITextFileService` was never implemented in a way that you could use it with folders.

**Comment by isidorn** [comment]
Ok, sounds like debt. Let me assign to next milestone and we can then consider if I shuold use a different service or the TextFileService should handle folder (which does not seem like a good choice)

**Comment by bpasero** [comment]
I would probably have a new service for this. And I also wonder what this command should do for a folder: should it download a zipped version of the folder or each file individually?

**Comment by isidorn** [comment]
Downloading a zipped version sounds like too much work for the use (he has to unzip).
I think it should be more seamless, so we download the whole foder and than each file individually. If people complain that it is slow, we can introduce a heuristic such that for larger folders we download a zipped version.

**Comment by isidorn** [comment]
From Ben: I don’t think ITextFileService is the right place for downloading a folder. I would rather manually bring up a folder picker to ask the user for the target destination and then use IFileService.copy() for the operation to that target folder.

**Comment by isidorn** [comment]
@bpasero thanks for feedback. I am no longer using `textFileService` but I am using the `fileDialogService` and the `fileService`
@roblourens you can try it out and let me know how it behaves now for you. Thanks
