### ISSUE TITLE
Windows reload do not enable extensions after Restart with extesnions disabled

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#81653]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Launch VS Code as usually
2. Pick `>Developer: Restart With Extensions Disabled` from Command palette

    Window will reload and you should see "All installed extensions are temporarily disabled. Reload the window to return to the previous state." notification

3. Click on "Reload" button in notification or run `>Developer: Reload Window`

    Window is reloaded, but extensions are still disabled and notification appears again.

This worked fine couple week ago.

VS Code version: Code - Insiders 1.39.0-insider (601e3e0762ac93e03cfef8336be8223bf32754e1, 2019-09-30T07:41:01.671Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.85GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by RMacfarlane** [comment]
@bpasero Is there any way to preserve the old behavior? https://github.com/microsoft/vscode/commit/1c6938e342a71e43a74eb3d017d02f76575b4128

The issue reporter tries to use this action, if you choose "Don't Know" from the "Source" dropdown, there's text displayed saying you can reload the window with extensions disabled to try to narrow down the problem. Clicking the text tries to run the old action. If updated to the new restart action, this has the effect of completely closing the issue reporter and losing any state it had
