### ISSUE TITLE
Selection and replacement in editor is buggy

### ISSUE THREAD

**Issue by 2gitrepo** [microsoft/vscode#81656]
Issue Type: <b>Bug</b>

After selecting a word in the editor, if I start typing or try pasting a clipboard content, the existing word doesn't get overwritten; instead it gets merged with the clipboard content or whatever I type

Eaxmple (This was a python program)
---------------------------------------
`counter = 4`

When I select "counter" and starts typing `course_counter`, it starts off as `couconter`. This only happens the 1st time for that context. If start selecting again the misspelt word, it replaces as expected. The same can be replicated for a clipboard paste as well.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
vscode-npm-script|eg2|0.3.9
code-runner|for|0.9.14
gc-excelviewer|Gra|2.1.32
terraform|mau|1.4.0
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.4
python|ms-|2019.9.34911
Go|ms-|0.11.7
debugger-for-chrome|msj|4.12.0
java|red|0.49.0
vscode-yaml|red|0.5.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
change-case|wma|1.0.0

</details>

**Comment by Tyriar** [comment]
Does this happen if you close all windows and launch using `code --disable-extensions`?

**Comment by 2gitrepo** [comment]
Interestingly when I opened vscode with --disable-extensions, I could not reproduce the issue.

I had been using primarily the Microsoft python debugger plugin to run my code. Please advise on the next steps and I can help determine what's causing the issue.

**Comment by Tyriar** [comment]
That means it's an issue with one of your 19 extensions, the only way to tell is by disabling individual extensions and seeing if it still happens.
