### ISSUE TITLE
Program doesn't run

### ISSUE THREAD

**Issue by hlin863** [microsoft/vscode#81659]
When I attempt to run a python program even when I downloaded all of the python extensions, the program doesn't work. The program displays the error message as below.:

[Running] python -u "c:\Users\Owner\Documents\University\C\test.py"
'python' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.117 seconds

**Comment by Tyriar** [comment]
That means python isn't on your path. Also this is likely a problem with whatever extension you're using to run it.

**Comment by hlin863** [comment]
![image](https://user-images.githubusercontent.com/55798830/65911702-e9602c00-e3c4-11e9-9f14-94ca3745bd75.png)
