### ISSUE TITLE
Autocomplete not working for javascript on Mac

### ISSUE THREAD

**Issue by corinja** [microsoft/vscode#81651]
Issue Type: <b>Bug</b>

The autocompletion of methods and properties for objects has stopped working.

If I start typing eg. con the editor suggests console and const as word completions, but if I select console and then type a period I don't get any of the methods of the console object.

Similarly if I create an array and then type a period I don't get any of the methods or properties for the array. 

If I hit CTRL + Space after typing console I get "No suggestions".

I've tried disabling extensions and restarting VS Code, and restarting my machine but nothing is working.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (4.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
flow-for-vscode|flo|1.5.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see "Initializing JS/TS language features" in status bar when you open JS file first time? Does it stops to spin?
Is it for any workspace or there are some specifics? Do you have any `jsconfig.json` or `tsconfig.json` files?

Are there any error in DevTools console if you open **Help > Toggle Developer Tools** ?

**Comment by corinja** [comment]
Hi @IllusionMH thanks for the input. I'm afraid I actually got impatient with it and did a complete uninstall/reinstall. It's working now. I will take note of what you said and if the problem re-occurs hopefully I'll be able to provide more information. Thanks again.

**Comment by IllusionMH** [comment]
A bit radical way, but I'm glad that it worked for you.
