### ISSUE TITLE
CSS should show enum property value before everything else

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#81669]
For example, `text-decoration` suggests a lot of irrelevant results on the top:

![image](https://user-images.githubusercontent.com/4033249/65904291-03711e80-e373-11e9-84a4-e1971c49d2fd.png)

**Comment by Tyriar** [comment]
Version: 1.40.0-insider (user setup)
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:48:38.866Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19008

![image](https://user-images.githubusercontent.com/2193314/67813495-e48fa600-fa5e-11e9-85ef-59e9dba2795a.png)

**Comment by octref** [comment]
@Tyriar Sorry, not in today's insider yet, I just pulled in CSS changes.
