### ISSUE TITLE
Chinese characters garbled in task output panel

### ISSUE THREAD

**Issue by fantacytyx** [Microsoft/vscode#8166]
- VSCode Version: 1.3.0-insider 2016-06-24 (commit de6652)
- OS Version: window 10

Steps to Reproduce:

1. Launch the task
2. Chinese characters were display like this
![image](https://cloud.githubusercontent.com/assets/8966236/16367211/d301de2a-3c53-11e6-8638-fe1322021461.png)
3.Normal should be like this
![image](https://cloud.githubusercontent.com/assets/8966236/16367238/00e5329c-3c54-11e6-8f2e-bb7e783f43d1.png)

**Comment by dbaeumer** [comment]
Dups #974 & #3550.
