### ISSUE TITLE
Unable to auto update extensions

### ISSUE THREAD

**Issue by Merith-TK** [microsoft/vscode#81660]
- VSCode Version: 1.38.1
- OS Version: Windows 10, EDU, 1903

Steps to Reproduce:
Unknown if reproducable, this is mysetup
portable mode by unzipping and making data directory
https://i.imgur.com/j6QMj5K.png
Settings.json
```json
{
    // Set EXTERNAL term to msys
    "terminal.external.windowsExec": "\\PortableApps\\msys64\\mingw64.exe",
    
    // Set INTERNAL term to msys
    "terminal.integrated.shell.windows": "\\PortableApps\\msys64\\usr\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["--login", "-i"],
    "terminal.integrated.env.windows":
    {
        "MSYSTEM": "MINGW64",
        "CHERE_INVOKING":"1",
        "GOPATH": "\\Go"
    },

    // Set git binary location
    "git.enabled": true,
    // "git.path": "\\PortableApps\\Git4Win\\bin\\git.exe",
    "git.defaultCloneDirectory": "\\Documents\\Workspace",

    // Hidden Files
    "files.exclude": {
        "**/desktop.ini": true
    },

    // Enhance portability
    "window.restoreWindows": "none",
    "files.hotExit": "off",
    "git.autofetch": true,
    "go.useLanguageServer": true,
}
```
This is setup to make portable mode work

I use a launcher written in go (issue persists without this launcher)
https://github.com/Merith-TK/Personal-Projects/blob/master/Code.go

This just makes it even more portable and fixes some environment issues for portability

I only have one extension, and its the `ms-vscode.go` extension for syntax highlighting, its current version is 0.11.6, and it is supposed to update to 0.11.7 now, but for the past month i have had to manually update via vsix

**Comment by Merith-TK** [comment]
If need be, i can zip my entire thing and share it to you guys,

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/65982116-7213b200-e42f-11e9-83a6-674205bbac42.png)
I also cant see README's for my Extenstions (Marketplace and Installed)

**Comment by sandy081** [comment]
Are you behind any proxy set up? Are you able to access Marketplace from browser?

Is it a DNS issue? #78783 #78872
Can you try to access this image? 
https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default
If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

Can you please share the logs from following locations

- Dev tools console. Use command `F1 -> Toggle Developer Tools`
- Window log. Use command `F1` -> View: Open View -> Window (Log)`
- Shared process log. Use command `F1` -> View: Open View -> Shared (Log)`

**Comment by Merith-TK** [comment]
School district has put a BROAD BLOCK on all `.io` pages (except those i have had to email IT about to get unblocked), to vsassets.io is blocked, 
![image](https://user-images.githubusercontent.com/10422110/65993544-4ea83180-e446-11e9-8032-71ce71195435.png)


Looks to be what is causing the issue, i guess i have to fire yet ANOTHER email (blegh)

**Comment by Merith-TK** [comment]
I am going to request that this remain open incase this happens at my home

**Comment by Merith-TK** [comment]
Turns out it was because the district had accidentally blocked vsassets.io
