### ISSUE TITLE
Support deno-style JSDoc code highlighting

### ISSUE THREAD

**Issue by liamross** [microsoft/vscode#81668]
# Issue

In the [deno styleguide](https://deno.land/style_guide.html) it says to document code examples as follows:

```ts
/** A straight forward comment and an example:
 *
 *       import { foo } from "deno";
 *       foo("bar");
 */
```

Right now, vscode supports highlighting _within the comment AND when hovered_ with the "triple-back tick (```) notation", ***but only supports highlighting when hovered with the indented notation***.

1. triple-back tick (```) notation **(no issues)**
    <img width="500" alt="Screen Shot 2019-09-30 at 10 47 39 AM" src="https://user-images.githubusercontent.com/24969218/65903093-a5433c00-e370-11e9-8cd9-3541b7d4355f.png">
    <img width="500" alt="Screen Shot 2019-09-30 at 10 48 11 AM" src="https://user-images.githubusercontent.com/24969218/65903101-a70cff80-e370-11e9-938c-4a6bc22b3bb1.png">

1. indented notation **(doesn't highlight within comment)**
    <img width="500" alt="Screen Shot 2019-09-30 at 10 52 49 AM" src="https://user-images.githubusercontent.com/24969218/65903106-a96f5980-e370-11e9-85f2-5622d24f59e9.png">
    <img width="500" alt="Screen Shot 2019-09-30 at 10 53 29 AM" src="https://user-images.githubusercontent.com/24969218/65903135-b7bd7580-e370-11e9-941c-865bee35d294.png">

As you can see, it fails to highlight the in-comment code block for indented notation despite highlighting it correctly when hovered.

# Proposal

Highlight the indented code notation by whatever file type the comment is found in.

**Comment by mjbvz** [comment]
This can be contributed by an extension with an injection grammar.

I'm concerned it may end up highlighting some user's documentation unexpectedly so not in favor of making this default behavior for VS Code

**Comment by liamross** [comment]
@mjbvz It seems to already be the behaviour though, since on-hover reveals the highlighting. In my mind, it seemed more like missing behaviour for the actual comment block.

**Comment by liamross** [comment]
@ry Is the indented code block specific to deno, or is that a syntax of JSDoc? I haven't been able to  find any documentation outside of the deno style guide, but given that vscode does the correct highlighting on hover I'm assuming it's not specific to deno
