### ISSUE TITLE
No Folder Opened missing twisties

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81662]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/35271042/65900441-df114400-e36a-11e9-84e5-0a67c4816ece.png">

This is likely not using the tree widget so will need to add the icon classes to this.

FYI @isidorn

**Comment by misolori** [comment]
Fixed

<img width="245" alt="image" src="https://user-images.githubusercontent.com/35271042/65900874-d66d3d80-e36b-11e9-80d4-8fa28da27b31.png">

**Comment by bpasero** [comment]
Can we revisit why the empty view is not calling `super.renderHeader()` in this case? I find it weird that a view would have to repeat code that is already there in the base type for rendering the twisty. Sounds like debt to me.

**Comment by isidorn** [comment]
@bpasero Yes, I can look into this next week. You are correct, looks like debt.
@misolori thanks for fixing it for this milestone though.
