### ISSUE TITLE
Is there any way to make my terminal wont close instantly after the task is finished on vscode?

### ISSUE THREAD

**Issue by MyNameJeff69420** [microsoft/vscode#81676]

**Comment by frank-dspeed** [comment]
@MyNameJeff69420 not at present but a workaround is to design your task to save its output to a file or log?

**Comment by Tyriar** [comment]
The terminal sticks around and gets reused in my experience?

**Comment by alexr00** [comment]
The terminal doesn't close when the task is finished. By default, the terminal sticks around and gets reused by other tasks. It also prints `Terminal will be reused by tasks, press an key to close it` when the task is done.

If you don't want the terminal to be reused by other tasks, you can set:
```json
			"presentation": {
				"panel": "dedicated"
			},
```
on your task.
