### ISSUE TITLE
Settings GUI hover/select color on rows

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81675]
Probably from https://github.com/microsoft/vscode/issues/81564

![image](https://user-images.githubusercontent.com/323878/65906474-84cab000-e377-11e9-993d-d95b4da3b7cf.png)

**Comment by joaomoreno** [comment]
Just saw this

![image](https://user-images.githubusercontent.com/22350/65943223-3f69b980-e42f-11e9-848b-83d889794726.png)

**Comment by roblourens** [comment]
Should be fixed if you are using today's build
