### ISSUE TITLE
Test: New Octicons outline style

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81679]
Refs: https://github.com/microsoft/vscode/issues/76909

- [x] Mac: @alexandrudima 
- [x] Windows: @egamma 
- [x] Linux: @roblourens 

Complexity: 2

We've updated our version of Octicons to use our new outline style. This means that every previous icon is now mapped to an outline version. Please use [our docs as a reference](https://code.visualstudio.com/api/references/icons-in-labels) for the list of icons to test. Below are the areas that should be tested (you can compare with Stable as a reference to the original):

- Status bar
- Quick pick labels
- Issue reporter (related issues)
- Peek view (close button)
- Extensions: workspace recommendations (viewlet header has download all and edit)
- GitHub comment (edit and delete)
- Diff line (show next/prev change)
- Verify that the icons show up properly in each of those areas.

For the Status bar, you can create your own extension or [use my sample](https://github.com/misolori/vscode-octicon-extension-sample) that cycles through all of the icons after you click the status bar item. You can additionally install other extensions that add items to the status bar (GitHub PR, vscode-spotify, Live Share, etc.) and verify that the icons show up correctly.

**Comment by roblourens** [comment]
> Extensions: workspace recommendations (viewlet header has download all and edit)

Where is Download All?

**Comment by misolori** [comment]
@roblourens when you are on a workspace with extension recommendations, they're the actions in the `workspace recommendations` header:

![image](https://user-images.githubusercontent.com/35271042/65995562-a47ed880-e44a-11e9-88a1-823ad91c5100.png)

**Comment by roblourens** [comment]
Oh right I was just looking at "recommendations", thanks
