### ISSUE TITLE
The breakpoints window has frustrating limitations

### ISSUE THREAD

**Issue by mbianucci** [microsoft/vscode#81678]
Issue Type: <b>Bug</b>

The breakpoints window when debugging is confusing, unintuitive, and frustrating. Some of my issues with it:
1. The size is static, I can't expand it to see more breakpoints. Even if I move it up and down the side up, it is stuck at one size.
2. The "All Exceptions" check box at the top is unclear (maybe it prevents breaking on exceptions, but that seems to defeat the purpose of debugging?)
3. The deactivate all break points button deactivates them differently than just unchecking their boxes. Sometimes I just want to deactivate everything, then re-enable a single breakpoint to see if it is hit. I can't do that with this button. And if I have a random number of breakpoints disabled and the rest enabled, I can't use that button to get them all in the same state.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18963

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
cpptools|ms-|0.25.1
vscode-gn|npc|1.1.0
java|red|0.49.0
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1

</details>

**Comment by isidorn** [comment]
1. Is a fari feature request and we might revisit this in the future
2. 3. work as designed. We will not change that.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/6982
