### ISSUE TITLE
Cannot see the full namespace (that is, the package path name)

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#81671]
We have written the needed data into your clipboard because it was too large to send. Please paste.
![2019-10-01_2-01-29](https://user-images.githubusercontent.com/27546390/65904572-4f62a880-e3f1-11e9-9482-269999afecd3.png)

**Comment by 395053994** [comment]
Cannot see the full namespace (that is, the package path name)

**Comment by Tyriar** [comment]
This doesn't look like vscode?

**Comment by 395053994** [comment]
Why can't such a low-level bug be solved? Let's follow eclipse and intellij idea - JetBrains.

**Comment by 395053994** [comment]
Have you changed the theme and you don't know VSCode?

**Comment by 395053994** [comment]
Why can't such a low-level bug be solved? Let's follow eclipse and intellij idea - JetBrains.
Have you changed the theme and you don't know VSCode?


------------------ 原始邮件 ------------------
发件人: "Daniel Imms"<notifications@github.com>;
发送时间: 2019年10月2日(星期三) 凌晨5:02
收件人: "microsoft/vscode"<vscode@noreply.github.com>;
抄送: "青春！"<395053994@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [microsoft/vscode] Cannot see the full namespace (that is, thepackage path name) (#81671)




Closed #81671.

**Comment by Tyriar** [comment]
The gradient on the top item is throwing me off but maybe you changed that. ctrl+shift expands the info box, you can also click the `i` button on the right to do this.
