### ISSUE TITLE
Autocomplete fields don't autosuggest completions themselves

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode#81681]
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.6 (18G95)

Steps to Reproduce:

1. Tab complete some function that has more than 0 parameters. It should look something like the following:
![image](https://user-images.githubusercontent.com/8225332/65911845-3deeb180-e39b-11e9-94c4-0cca7f1d740e.png)
2. Start typing in the first highlighted selection (no need to click anywhere)
3. Notice that none of the local variables, functions, or packages come up unless forced by using the shortcut (macOS CTRL+SPACE)

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`
