### ISSUE TITLE
"Open User Settings" command names inconsistent

### ISSUE THREAD

**Issue by 3nuc** [microsoft/vscode#81684]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Press CTRL+SHIFT+P
2. Type "open settings" and look at the results

Does this issue occur when all extensions are disabled?: Yes

This is not #57381. 

![obraz](https://user-images.githubusercontent.com/5359825/65914435-ae182a00-e3d1-11e9-9560-f0be8936f8f0.png)

The commands are also doubled up - there's also command "Open settings UI" and the visible "open user settings" which do the same thing

Shouldn't "Open settings (JSON)" be called "Open user settings (JSON)"? That way the JSON command is lexically tied to "Open user settings" (without json). Also it doesn't specify which settings it's going to open. Though it's still weird that we have a "open USER settings" command even though there's no "open WORKSPACE settings" command.

**Comment by roblourens** [comment]
I know it's confusing but "Open Settings" uses your configured preferred editor, JSON or GUI, then there are commands to force use one or the other. Also there is an "open workspace settings" command.
