### ISSUE TITLE
File path in Vscode terminal is not clickable to jump into again.

### ISSUE THREAD

**Issue by Clarchik** [microsoft/vscode#81680]
- Version: 1.38.1
- OS Mojave 10.14.6:

Steps to Reproduce:
1. Open terminal, ran Angular project and on purpose made a mistake in file to get error in terminal. For link it works but not for file path.
Installed the same version on Windows 10 and worked but not on MacOS.
![2019-09-30 21 47 25](https://user-images.githubusercontent.com/23317853/65910922-faf90200-e3cb-11e9-9a28-cefac8499c04.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I suspect this has the same root cause as https://github.com/xtermjs/xterm.js/issues/2458
