### ISSUE TITLE
Editor forces word replacement in Typescript

### ISSUE THREAD

**Issue by d-cmyk** [microsoft/vscode#81687]
- VSCode Version: 1.38.1
- OS Version: Darwin x64 18.2.0

Steps to Reproduce:

1. Open VSCode
2. Set language to Typescript
3. Type:
`let pageGrid: Grid;`

Then VSCode decides to replace the word "Grid" with something else.

Does this issue occur when all extensions are disabled?: Yes, but only after VSCode has been open for ~15 seconds or so.

**Comment by mjbvz** [comment]
We treat `;` as a commit character that accepts the current suggestion. Set `"editor.acceptSuggestionOnCommitCharacter": false` to disable this behavior
