### ISSUE TITLE
Test selection decorations in the minimap

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#81689]
Refs: https://github.com/microsoft/vscode/issues/21404

- [x] Mac: @isidorn 
- [x] Windows: @alexandrudima 
- [x] Linux: @mjbvz  

Complexity: 2

The current editor text selection is now rendered as decorations in the minimap. The `minimap.selectionHighlight` theme color can be used to change the color of these decorations. Some things to test:

- Multi-selection
- Interactions with decorations from search
- Different themes
- Changing the `minimap.selectionHighlight` color

**Comment by isidorn** [comment]
This works great, nice work.
