### ISSUE TITLE
Quick Pick not selecting first item

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#81683]
I get this when developing out of master, but not in latest insiders in:

Version: 1.39.0-insider
Commit: 79978f96d3501f14b235ed0a33a7360772a726a3
Date: 2019-09-30T14:14:29.641Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

- Run `Preferences: Color Theme` command
- Type `Dark`
- Expect first item selected
- Nothing is selected 🐛 

Same thing for `Open Recent Folders` etc.

![bug](https://user-images.githubusercontent.com/4033249/65914919-2ad1e680-e387-11e9-8564-8fdb64319493.gif)

**Comment by chrmarti** [comment]
Cannot reproduce. Anything I'm missing?

**Comment by octref** [comment]
I can't repro it anymore out of source => closing.
