### ISSUE TITLE
Task CWD not changing, runs task in workspace root folder

### ISSUE THREAD

**Issue by DeeeeLAN** [microsoft/vscode#81696]
Issue Type: <b>Bug</b>

I am attempting to run a task from a subfolder of the workspace, but no matter what I try, it runs everything in the $workspaceFolder root directory. Here is a simple task that reproduces the error for me:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo",
      "type": "shell",
      "command": "echo ${cwd}",
      "options": {
        "cwd": "${workspaceFolder}/build/",
        "shell": {
          "executable": "tcsh",
          "args": [
            "-c"
          ]
        }
      }
    }
  ]
}
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 3.10.0-957.27.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz (12 x 3324)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 1, 1|
|Memory (System)|157.40GB (144.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-emacs-friendly|lfs|0.9.0
veriloghdl|msh|1.0.3

</details>

**Comment by DeeeeLAN** [comment]
No duplicates that I can see. A branch off of the ticket from a couple years ago where this was added though, #856. Possible duplicate of #58980.

**Comment by alexr00** [comment]
`cwd` is evaluated based on the _task runner's_ current working directory. From the variable completion details (ctrl+. after typing `${` in tasks.json):

> The task runner's current working directory on startup

**Comment by DeeeeLAN** [comment]
What does that mean? What is the task runner, and how do I get my task to change directories? The part of the docs I was reading was not clear on this.

**Comment by DeeeeLAN** [comment]
Hello, @alexr00, is it possible to run a task in a specific directory?
