### ISSUE TITLE
Cursor multi select to single selection by pressing tab

### ISSUE THREAD

**Issue by clh97** [microsoft/vscode#81693]
When using emmet to create multiple html elements you can do this by pressing tab to fill each elements inner content:

![2019-09-30-19-30-25](https://user-images.githubusercontent.com/32719987/65921730-69809480-e3b9-11e9-9acf-6732ecd3ba40.gif)

Is there any way to select each line individually using tab after multi-selecting some lines?

![2019-09-30-19-30-50](https://user-images.githubusercontent.com/32719987/65921899-f7f51600-e3b9-11e9-9613-f72d40cfab6a.gif)

That would be a nice functionality to vscode

**Comment by octref** [comment]
> select each line individually using tab after multi-selecting some lines?

What does that mean?
