### ISSUE TITLE
Disk usage is 100% when VsCode starts

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#81694]
![2019-10-01_6-59-43](https://user-images.githubusercontent.com/27546390/65923080-23a7e880-e41a-11e9-99a9-a826f7bd333d.png)
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Closing, nothing in the screenshot indicated VS Code is consuming a lot of resources, just that you have many VS Code windows opened.
