### ISSUE TITLE
International keyboard layouts not being correctly recognised for shortcuts?

### ISSUE THREAD

**Issue by vitorgalvao** [Microsoft/vscode#817]
By default, <kbd>⌘</kbd><kbd>/</kbd> is `Toggle Line Comment`. Now lets look at the Portuguese keyboard layout:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/KB_Portuguese.svg/900px-KB_Portuguese.svg.png)

As you can see, to do <kbd>/</kbd> we need to <kbd>⇧</kbd><kbd>7</kbd>, so <kbd>⌘</kbd><kbd>/</kbd> is actually <kbd>⌘</kbd><kbd>⇧</kbd><kbd>7</kbd>. This works fine in most apps, but not VSCode, where it was showing the `Help` menu<sup>1</sup>.

Atom has no problem with this (even with the conflicting `Help` menu shortcut) in the same situation, so there might be an insight in the way they do it.

Using VSCode `0.10.2` on OS X `10.11.1 (15B42)`.

---

<sup>1</sup> Default system-wide shortcut is <kbd>⌘</kbd><kbd>⇧</kbd><kbd>/</kbd>, which is interpreted even with <kbd>⌘</kbd><kbd>⇧</kbd><kbd>7</kbd>

**Comment by alexandrudima** [comment]
@vitorgalvao Please see #713 for a detailed explanation of what's going on.

From my "blind" switching to Portuguese keyboard layout under windows, I think the toggle line comment is `Ctrl+~` out of the box for VSCode (the `~^` key).
