### ISSUE TITLE
PR: Add cli arguments to run the electron build as a webserver backend (headless) Replacement for #81474

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81705]
This issue is a part of: #81474 

it offers a secund way to serve vscode-online via the electron build it self without additional nodejs server and additional vscode-web code build.

## Goals
- could reduce the overall maintance overhead if we go with a single code base for both cases.
- don't clashes with currrent vscode-web team
- is maybe faster implamented and will reduce in faster release cycles.

## Create a secund Branch based on electron.
The idea is to combine both to contribute a code-cli --server flag to run headless and get used via the browser.

- We know from the microsoft ai research team that we can run electron headless
```
/*
Now to force Electron in software mode in the cloud, Chrome blacklisted GPUs from running. You
 cannot run it on Azure, AWS, Google Cloud. so you need to disable that by doing the following:
*/
const { app } = require(‘electron’)
app.commandLine.appendSwitch(‘ — ignore-gpu-blacklist’)
//To not render the Electron window, you just hide it when constructing it:
new BrowserWindow({ width: 1280, height: 800, show: false })
```
- We know from the electron team that we can start external reachable server services via child process spawn
```js
const { fork } = require('child_process')
const ps = fork(`${__dirname}/server.js`)
// The __dirname variable is required if you want to deploy on a binary build otherwise the script won’t be reached properly.
```

**Comment by chrisdias** [comment]
I think this is now handled by the Remote Tunnels experience https://code.visualstudio.com/docs/remote/tunnels
