### ISSUE TITLE
Switch to polling for watching changes on config files

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#81702]
https://github.com/microsoft/vscode/issues/81579 got answered by @sandy081 

```
This is to watch changes for user configuration data in VS Code.

Settings
Keybindings
Snippets
It's also to watch log files when output panel is opened.

We do not watch the whole user home directory, but code/User folder under user home directory. code/User folder is the one created by VS Code for storing above user data.
```

I Propose here to add a extra RTC Channel for Settings File Updates to call a reread of a settings file
so on save of a settings file we simply emit a event to that channel and vscode will reread its configuration this saves a ton of filewatchers.

we should also add a reload vscode button.

**Comment by sandy081** [comment]
Can you please be more elaborate on what this channel mean?

**Comment by frank-dspeed** [comment]
## From fs.watch (node)
On Linux systems, this uses inotify(7).
On BSD systems, this uses kqueue(2).
On macOS, this uses kqueue(2) for files and FSEvents for directories.
On SunOS systems (including Solaris and SmartOS), this uses event ports.
On Windows systems, this feature depends on ReadDirectoryChangesW.
On Aix systems, this feature depends on AHAFS, which must be enabled.

## Limitations
The limitations of fswatch depend largely on the monitor being used:

The FSEvents monitor, available only on OS X, has no known limitations, and scales very well with the number of files being observed.

The File Events Notification monitor, available on Solaris kernels and its derivatives, has no known limitations.

The kqueue monitor, available on any *BSD system featuring kqueue, requires a file descriptor to be opened for every file being watched. As a result, this monitor scales badly with the number of files being observed, and may begin to misbehave as soon as the fswatch process runs out of file descriptors. In this case, fswatch dumps one error on standard error for every file that cannot be opened.

The inotify monitor, available on Linux since kernel 2.6.13, may suffer a queue overflow if events are generated faster than they are read from the queue. In any case, the application is guaranteed to receive an overflow notification which can be handled to gracefully recover. fswatch currently throws an exception if a queue overflow occurs. Future versions will handle the overflow by emitting proper notifications.

The Windows monitor can only establish a watch directories, not files. To watch a file, its parent directory must be watched in order to receive change events for all the directory's children, recursively at any depth. Optionally, change events can be filtered to include only changes to the desired file.

The poll monitor, available on any platform, only relies on available CPU and memory to perform its task. The performance of this monitor degrades linearly with the number of files being watched.

**Comment by bpasero** [comment]
@frank-dspeed with your idea how would we be able to detect a change to the settings file that is done outside of the VSCode application?

**Comment by frank-dspeed** [comment]
@bpasero at present by design we would manualy hit reload but we could also simply pool for that every minut getting fs stat serial not in parallel would easy work
