### ISSUE TITLE
Visual Studio Code keeps compiling even if I do not save changes

### ISSUE THREAD

**Issue by himajaM** [microsoft/vscode#81707]
Issue Type: <b>Bug</b>

Visual Studio Code keeps compiling even if I do not save changes, need fix asap

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (7.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-typescript-tslint-plugin|ms-|1.2.2
angular2-inline|nat|0.0.17
angular-console|nrw|8.1.2
material-icon-theme|PKi|3.9.0
jstool|sun|1.1905.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What is it compiling?

**Comment by himajaM** [comment]
GoodMorning!

Thanks for responding ....

I am facing an issue in visual studio code i.e., without saving any file
after changes, vscode is automatically serving to live development for
every 5 min... which is causing very disturbance during our work...


[image: image.png]

Please let me know, what to do to avoid this.

**Comment by Tyriar** [comment]
Images don't attach when you respond via email. You haven't provided enough information. This is very likely a problem with some extension you have installed.
