### ISSUE TITLE
Blank editor group close icon missing

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#81701]
- VSCode Version: `1.39.0-insider`
- OS Version: `Windows_NT x64 10.0.18990`

![image](https://user-images.githubusercontent.com/641685/65935476-4240bc00-e3e7-11e9-8239-0af707ccaf94.png)

**Comment by bpasero** [comment]
Confirmed.

**Comment by misolori** [comment]
Fixed:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/35271042/65995908-40104900-e44b-11e9-8488-ab8953c2bde5.png">
