### ISSUE TITLE
Close button in quick pick not showing

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#81704]
- Run Open Recent command
- Hover over right side of an entry
- No close icon showing

![image](https://user-images.githubusercontent.com/4033249/65936664-2b439f00-e3d2-11e9-993f-265a4eb1de55.png)

**Comment by misolori** [comment]
Fixed:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/35271042/66003363-c08a7600-e45a-11e9-930f-d4603a80636a.png">
