### ISSUE TITLE
Spacing too wide for inline breakpoints

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#81715]
re https://github.com/microsoft/vscode/issues/81175

see attached screen recording, the spacing seems way to wide and is disturbing/nervous. The end of the visible line (`&& editor`) moves by 8 characters (for showing 3 inline breakpoints)

![Oct-01-2019 11-06-25](https://user-images.githubusercontent.com/1794099/65949054-c02eb280-e43b-11e9-8568-fb9e970a0d4a.gif)

**Comment by isidorn** [comment]
Agree. Yeah, let's try to decrease the width.

**Comment by isidorn** [comment]
I have decreased the width. Also there was an issue that they were not being updted when the fontSize changes. Now I fixed that. Here's the picture of the new (top) vs the old (bottom).
As for the flashing please check this issue out which I plan to tackle in the future https://github.com/microsoft/vscode/issues/81716

![Screenshot 2019-10-02 at 11 57 47](https://user-images.githubusercontent.com/1926584/66035773-08b5a100-e50c-11e9-922f-7957b0e0b8d1.png)

**Comment by bpasero** [comment]
I think there is still something off: the very first breakpoint still has a lot of spacing:

![image](https://user-images.githubusercontent.com/900690/66107563-dade6400-e5c0-11e9-95dc-dbe34abcfcc6.png)

@isidorn is that intentional?

**Comment by isidorn** [comment]
That is not intentional, and we should fix.
However since for the very first breakpoint I use some hacks to postiion it correctly (editor does not give me api to put it before first character) I have opened a seperate issue for that one https://github.com/microsoft/vscode/issues/81898
