### ISSUE TITLE
Restart to update loses all CLI args

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#81710]
Issue Type: <b>Bug</b>

I'm starting vscode with a bunch of args, most notably `--enable-proposed-api` and after the update it prevents extensions from activating.

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 6.2.9200

**Comment by Tyriar** [comment]
@usernamehw 6=7, 8+1=10 🧠

**Comment by usernamehw** [comment]
It's plain wrong. Win 10 is not equal Win 8 nor Win2012 Server. Probably the same cause as #81763

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/75241
