### ISSUE TITLE
File Explorer shows up two time in extension sample

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#81713]
Testing https://github.com/microsoft/vscode/issues/81635

See attached screen shot. Not sure if this is wanted.

<img width="389" alt="capture" src="https://user-images.githubusercontent.com/1931590/65948686-046d8300-e43b-11e9-8c88-0465c546d263.png">

**Comment by dbaeumer** [comment]
Note, that I renamed File explorer to My File Explorer

**Comment by alexr00** [comment]
@dbaeumer I can't reproduce this. Did the folder you had open happen to be called "My File Explorer"? In that case, it would show up once as the built-in explorer and once from the sample extension.

**Comment by dbaeumer** [comment]
@alexr00 no I renamed the `File Explorer` to `My File Explorer` in the package.json of the example.

**Comment by sandy081** [comment]
Nopes, #79519 is different and it was caused by changes I did yesterday.
