### ISSUE TITLE
Inline breakpoints flicker and jump

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#81716]
re #81175

* have inline breakpoints
* click one, click it again and again
* :bug: everything is super nervous, instead of enabling/disabling breakpoints seem to disappear/reappear with the consequence of text being shifted around (related to https://github.com/microsoft/vscode/issues/81715)

![Oct-01-2019 11-10-18](https://user-images.githubusercontent.com/1794099/65949264-26b3d080-e43c-11e9-9b43-e2fa4e3fe05c.gif)

**Comment by taciomedeiros** [comment]
+1

**Comment by roblourens** [comment]
Seems fixed
