### ISSUE TITLE
Active inline breakpoint isn't highlighted

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#81718]
re #81175

* set breakpoints as show in this file https://github.com/microsoft/vscode-references-view/blob/a48315c11bfeec50fc0d018f555097f61c888ce4/src/extension.ts#L26
* hide the references viewlet
* the 'editorHighlight.hide()' inline breakpoint is active 
* :bug: the inline breakpoint doesn't get the highlight (yellow arrow enclosing dot), instead the gutter breakpoints is highlighted, step in, step out and the yellow arrow does appear inline. 

![Oct-01-2019 11-21-49](https://user-images.githubusercontent.com/1794099/65950318-1b61a480-e43e-11e9-8145-3980a758ac9a.gif)

**Comment by isidorn** [comment]
Good catch. We currently do not support this.
And yes it makes perfect sense. So assigning first to September though I might move it out to next week.

**Comment by isidorn** [comment]
We now support this as shown by this gif:
Verifier: make sure that when the inline breakpoint is at the same location as the top stack frame indicator that you get one decoration and not two. The one decroation should be the yellow arrow with a red dot inside (as shown in the .gif)

![inlineBreakpoints](https://user-images.githubusercontent.com/1926584/67576189-61a8db80-f73e-11e9-9ee6-246f1116f11a.gif)

**Comment by connor4312** [comment]
I found an issue with this change and opened a PR for it: https://github.com/microsoft/vscode/pull/83851
