### ISSUE TITLE
TypeScript watcher task not revealing terminal on error

### ISSUE THREAD

**Issue by haugerbr** [microsoft/vscode#81711]
Issue Type: <b>Bug</b>

I have the following configuration for a task but it's not revealing the task window whenever there is an error in the TypeScript compilation. I don't know what is causing this issue but it seems like the problem matcher is not parsing the output. 
```        
{
    "label": "Test",
    "type": "shell",
    "command": "${env:SYSTEMDRIVE}\\codets\\.bin\\tsc.cmd",
    "args": [
        "-w",
        "-p",
        "tsconfig.json"
    ],
    "presentation": {
        "reveal": "silent"
    },
    "problemMatcher": [
        "$tsc-watch"
    ],
    "auto": true
}
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (12.80GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
You are using a watching problem matcher, which means you need to include `"isBackground": true`

**Comment by haugerbr** [comment]
Thanks, I guess I missed that in the documentation.
