### ISSUE TITLE
Missing standalone languages `css` (etc) + `json`

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#8172]
Previous report where `css` was removed : https://github.com/Microsoft/vscode/issues/7699

Now json's joined the party 

![](http://assets2.ignimgs.com/2015/05/15/jason-statham-spy-movie-1280jpg-4cf7b9_1280w.jpg)

https://github.com/Microsoft/vscode/commits/master/src/vs/editor/editor.main.ts 

This issue is just for tracking / pinging in case it gets completely lost :) /cc @aeschli :rose:

**Comment by aeschli** [comment]
JSON, CSS, LESS and SCSS are now contributed as monaco editor plugins.
See https://github.com/Microsoft/monaco-editor

**Comment by basarat** [comment]
noice :rose:

**Comment by basarat** [comment]
Looking at the sample : https://microsoft.github.io/monaco-editor/index.html `css` no longer has the nice `color` inline widget that it used to. Should I create an issue? 

![image](https://cloud.githubusercontent.com/assets/874898/16371330/548fb46e-3c89-11e6-9461-7de5f3a075e7.png)

**Comment by aeschli** [comment]
I will add this back ASAP. I'm waiting for some additional API
