### ISSUE TITLE
High contrast: minimap selection color does not match editor selection color

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81728]
Refs: https://github.com/microsoft/vscode/issues/81689

Every theme the selection color matches in the editor and in the minimap. However in the High Contrast theme that is not the case.
I do not understand the incosistency here and I would suggest that we use the same white color as in the editor.
I like how the current solution wokrs so I can be conviced that we should go with that one, I just do not like the inconsistency.

fyi @misolori 

![Screenshot 2019-10-01 at 12 07 30](https://user-images.githubusercontent.com/1926584/65953458-4bac4180-e444-11e9-82de-c085d0c8c4cb.png)

**Comment by isidorn** [comment]
Another downside of this approach is that the search decoration are not that visible (orange on yellow)

**Comment by RMacfarlane** [comment]
Nice catch, I didn't notice this before. High contrast mode seems to use some other color than `editor.selectionBackground` as the editor color here. I'll update to match that color 👍

**Comment by isidorn** [comment]
Adding bug and milestone so we verify this. Thanks for fixing.
