### ISSUE TITLE
No uninstall functionality for MacOS

### ISSUE THREAD

**Issue by d-cmyk** [microsoft/vscode#81725]
There is no uninstalling functionality for MacOS, and there needs to be.

**Comment by scottymcraig** [comment]
Are you talking about removing the settings and extensions?  To uninstall the program on a Mac, you simply move it from the Applications folder to the Trash.

**Comment by d-cmyk** [comment]
I'm specifically talking about how after doing the thing that you describe and then "installing" again you do not start with a fresh copy but everything is the same.

**Comment by Tyriar** [comment]
You can delete `$HOME/Library/Application Support/Code` and `$HOME/.vscode` to remove everything from your system.
