### ISSUE TITLE
Preserve case in Search and Replace isn't working when I use group substitution

### ISSUE THREAD

**Issue by migs911** [microsoft/vscode#81729]
I've been waiting for this feature so long, but preserve case in Replace isn't working, when I use group substitution, like this: `$1`

![2019-10-01_13-06-06](https://user-images.githubusercontent.com/8477533/65953402-887c3680-e44c-11e9-90d8-f143b25e4a9a.png)

**Comment by roblourens** [comment]
Is this expected to work @skprabhanjan?

**Comment by skprabhanjan** [comment]
@roblourens , This is not expected to work in the current implementation , regex was just returning plainly without calling the buildReplacement Functionality.
I have sent a PR to add this feature :)
