### ISSUE TITLE
SCM View: clicking on repository shows animation for no reason

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81722]
Testing: https://github.com/microsoft/vscode/issues/81233

I find the animation when switching repositories does not really add any value.

![before](https://user-images.githubusercontent.com/900690/65952040-8a8cc800-e441-11e9-95d1-45754a38a044.gif)

**Comment by joaomoreno** [comment]
Oh that animation is not on purpose. Good catch. I wonder why people haven't filed this earlier?
