### ISSUE TITLE
SCM View: initial animation is disturbing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81723]
Testing: #81233

Reloading the workbench with the SCM view visible (2 repositories selected) shows a disturbing animation imho:

![before](https://user-images.githubusercontent.com/900690/65952326-0555e300-e442-11e9-9cb2-3bbb6c2033aa.gif)

I see no real value add of having this animation.

**Comment by joaomoreno** [comment]
Since repositories come delayed through extension API, there's no way to prevent this without purposeful delaying showing repositories, thus making everything slightly slower.

There is a view resizing which could potentially be fixed. cc @sandy081 on that.

**Comment by sandy081** [comment]
Assigning myself to investigate view resizing

**Comment by bpasero** [comment]
I verified that this is a bit better, but it still animates on reload.

**Comment by joaomoreno** [comment]
@bpasero Animation should be completely disabled by now. Are you sure that's not just the perception of the views coming in late, spaced out over time?

**Comment by bpasero** [comment]
Still seems animated:

![1](https://user-images.githubusercontent.com/900690/66125479-55ba7580-e5e7-11e9-90cb-7e3298a10c05.gif)
![before](https://user-images.githubusercontent.com/900690/66125480-55ba7580-e5e7-11e9-9593-447bbf53a044.gif)

**Comment by joaomoreno** [comment]
Nope, those repositories are coming in one by one in the first view, so the view grows 20-ish pixels everytime one comes up. There's no animation there.

**Comment by bpasero** [comment]
I think I am referring to the growing "Source Control Providers" view. That one is probably animating its growth after each repo that gets added.

**Comment by joaomoreno** [comment]
No, it just discretely increases the height by 22px each time a new repo comes in. They come in one by one spaced out by a few milliseconds. So the whole thing seems animated. But it isn't.
