### ISSUE TITLE
ChildProcess.spawn never ends

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode#81734]
Issue Type: <b>Bug</b>

I do not know how to reproduce this but it happens quite frequently. At some point one of the extensionhost processes in the explorer is using high cpu and no memory with this as a result. the profile file was too big for upload.

![image](https://user-images.githubusercontent.com/30625381/65954608-b1013200-e446-11e9-9b8a-89c38e8da630.png)

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T05:39:51.694Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv|-psn_0_5059795|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
cypress-snippets|and|1.2.0
atlascode|atl|1.4.3
vscode-custom-css|be5|3.0.8
color-info|bie|0.5.1
markdown-mermaid|bie|1.2.0
mermaid-markdown-syntax-highlighting|bpr|1.0.1
better-toml|bun|0.3.2
twigcs|cer|1.1.0
path-intellisense|chr|1.4.2
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|1.9.1
hsnips|dra|0.0.10
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.0.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.3.0
file-icons|fil|1.0.19
vscode-firefox-debug|fir|2.3.3
vscode-architect|gil|0.1.0
vscode-pull-request-github|Git|0.12.0
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.156
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.2
plantuml|jeb|2.12.1
polacode-2019|jef|0.5.1
browsersync|jer|2.1.0
vscode-peacock|joh|3.1.5
vscode-commitizen|Kni|0.8.3
twig-language-2|mbl|0.8.10
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.16.0
auto-barrel|mik|1.6.5
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.79.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
vscode-remote-extensionpack|ms-|0.17.0
references-view|ms-|0.0.30
debugger-for-chrome|msj|4.12.0
ts-prop-dag|nat|1.0.6
vscode-versionlens|pfl|0.24.0
rpa-eslint-snippets|rav|0.0.2
vscode-yaml|red|0.5.3
explorer-exclude-vscode-extension|Red|1.2.0
elastic|ria|0.13.3
preview-vscode|sea|2.0.3
code-settings-sync|Sha|3.4.3
vscode-barreler|shi|0.0.1
sourcegraph|sou|1.0.14
cucumber|ste|0.12.0
gif-code-snippet|sub|1.0.2
vscode-mermaid-editor|tom|0.4.2
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
snippet|vsc|0.7.0
vim|vsc|1.11.0
vscode-mermaid-preview|vst|1.2.0
quokka-vscode|Wal|1.0.253
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3

(1 theme extensions excluded)

</details>

**Comment by frank-dspeed** [comment]
@bm-stschneider i can verify that this happens also on linux frequently it freezes the whole PC in my case but i also don't know example what conditions are causing this but i propose to add a delay for startup of processes to stop freezing and then we could debug more

**Comment by Tyriar** [comment]
Seems related to auto attach.

**Comment by bm-stschneider** [comment]
is there a way to get more information on the processes running other than the obscure extensionHost process. Would also help with identifying problematic extensions maybe.

**Comment by frank-dspeed** [comment]
@bm-stschneider you can set the VSCODE LOG Level to get such information but its hard to filter then since the problem is not exactly reproduce able maybe you can run vscode in future with a file log

**Comment by connor4312** [comment]
We since have a [new debugger](https://github.com/microsoft/vscode-js-debug/) that handles auto attach in a more relaible way. Please let us know if you're still running into problems, and if so open an issue on that repo.
