### ISSUE TITLE
Delay Javascript/Typescript lint

### ISSUE THREAD

**Issue by d-cmyk** [microsoft/vscode#81737]
When I type code, I don't need a bunch of squiggly lines to pop up to tell me that "namesp", "namespa" and "namespac" are not a thing. I'd like to delay the lint until the time a file is saved.

Unfortunately the list of settings is bloated and unorganized, I'm not sure how I'm supposed to find that functionality in there or if it even exists.

**Comment by MadcowD** [comment]
what?

**Comment by d-cmyk** [comment]
I don't think I could be any clearer

**Comment by doberkofler** [comment]
@d-cmyk I completely agree with you and would also hope fir an option to change the time when the typescript validation is performed similar to what is already available for the eslint validator.
