### ISSUE TITLE
Zoom status bar command is not available for gifs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#81738]
Testing #81674
Linux - Ubuntu 16
Opened - `vscode-docs/release-notes/images/1_38/html-css-mdn-reference.gif`

![image](https://user-images.githubusercontent.com/10746682/65957021-19064700-e44c-11e9-8617-edb456b2f9f1.png)

🐛 No zoom command in the status bar

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/65957291-bbbec580-e44c-11e9-8615-411db0811ab8.png)

Also not shown for pngs

**Comment by mjbvz** [comment]
I can't repo this on Ubuntu 18. 
![Screen Shot 2019-10-01 at 2 09 00 PM](https://user-images.githubusercontent.com/12821956/66000807-13f9c580-e455-11e9-8c1e-bfdcc4161342.png)

Does this happen for all images? Can you please check that these items have not been unchecked in the status bar?

**Comment by sbatten** [comment]
Having the same issue for me on first load of images. Clicking to another image and coming back seems to "fix" the issue.
