### ISSUE TITLE
Emmet - @f+

### ISSUE THREAD

**Issue by flexcodenet** [microsoft/vscode#81735]
Issue Type: <b>Bug</b>

Hello,
Why i can't use command emmet "@f+" in scss files? Only "@f" work.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by flexcodenet** [comment]
But my emmet work, but not all function.

**Comment by octref** [comment]
https://github.com/emmetio/expand-abbreviation/issues/19#issuecomment-374131586

**Comment by flexcodenet** [comment]
So emmet function's doesn't work 100% in vsc?

**Comment by octref** [comment]
vsc uses emmet upstream library and `+` is deprecated & removed upstream.
