### ISSUE TITLE
SCM Views: do not show indentation guide for first level?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81731]
Testing: https://github.com/microsoft/vscode/issues/81233

I switched to the Ayu icon theme and wonder if maybe there should be no indentation line for the first level because it does not nicely align with the twisty of the group?

![image](https://user-images.githubusercontent.com/900690/65953890-34ba1f00-e445-11e9-9c9d-4be8737f74bf.png)

**Comment by joaomoreno** [comment]
Yeah I was aware about this... but I only thought about indenting everything more in order to align. I like the idea of hiding the first level indentation guide. Let's do that.

**Comment by joaomoreno** [comment]
**Verification:** I have disabled the first indent guide **only** in tree mode **and** when using an icon theme which uses folders as twisties (eg Ayu).
