### ISSUE TITLE
sourceRanges confusing in CallHierarchyIncomingCall and CallHierarchyOutgoingCall

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#81746]
Testing https://github.com/microsoft/vscode/issues/81655

The `sourceRanges` denote the range in the from item. However since the `CallHierarchyIncomingCall` has a source property this gets confusing. In addition `source` and `target` aren't easy to understand. For me a call goes `from` function A `to` function B. 

I would opt to name them as follows:

```ts
	export class CallHierarchyOutgoingCall {
		fromRanges: Range[];
		to: CallHierarchyItem;
	}
```

```ts
	export class CallHierarchyIncomingCall {
		from: CallHierarchyItem;
		fromRanges: Range[];
	}
````

**Comment by dbaeumer** [comment]
May be it would be helpful to explain that the graph is basically modeled as an adjacent matrix and that the API we provide gives compressed access (no empty elements) to the rows and columns of that matrix.

**Comment by dbaeumer** [comment]
Basically it is a adjacent list (https://en.wikipedia.org/wiki/Adjacency_list)

**Comment by gregvanl** [comment]
I found this confusing as well. I was going to propose CallHierarchyOutgoingCall parameters be `target` and `targetRanges` but I realized that I was interpreting it incorrectly.
