### ISSUE TITLE
Link to open in binary editor is not shown when image preview extension is disabled 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#81740]
Testing #81674 
Linux

- Open a png file that is rendered by image preview extension
- Disable the image preview extension
- Reload the window
🐛 Png file with empty window opens. No link to open in binary editor is shown.

![image](https://user-images.githubusercontent.com/10746682/65957499-469fc000-e44d-11e9-8d9f-3aa48e716316.png)

**Comment by mjbvz** [comment]
This same bug also exists for serialized webviews. It is not easy to fix and should not be too commonly hit in day to day usage
