### ISSUE TITLE
Diff peek: sizing differences

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81747]
I find the arrow icons in the diff peek odd:

![image](https://user-images.githubusercontent.com/900690/65964013-43600080-e45c-11e9-9dc3-7406deed4309.png)

Seems to me the up/down arrow is much larger compared to the rest.

**Comment by misolori** [comment]
They're all made to be about the same size and fit within a 14x14 square:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/35271042/66002983-c895e600-e459-11e9-9e32-90e9ab9db701.png">

I can try and shorten them so they fit with the others, but it will also affect them in the editor toolbar:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/35271042/66003035-e400f100-e459-11e9-9bdf-648dc28b9825.png">

**Comment by bpasero** [comment]
@misolori in my picture above you can see that the second icon does not seem to be aligned well compared to the others, wouldn't you agree? I feel the second icon can move 1px up. 

Also it is not clear to me why the up and down arrow are not aligned to each other.

**Comment by bpasero** [comment]
@misolori yes on zoom level 1 always.

**Comment by misolori** [comment]
Peek arrows are now shorter so they're closer the size of the others:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/35271042/66610114-88c4b200-eb6f-11e9-99ca-2c731c26b195.png">

**Comment by bpasero** [comment]
Looks better. I still think the undo icon could move 1px up:

![image](https://user-images.githubusercontent.com/900690/67758593-468be380-fa3e-11e9-9f28-19a52b7d6015.png)
