### ISSUE TITLE
Image not updated when replaced

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81751]
- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. open an image (I tried with `resources/linux/code.png`)
2. drop an image with same name into that location in explorer
3. confirm to overwrite

=> 🐛 image is not updated in the editor

**Comment by mjbvz** [comment]
Yeah this seems like a regression from our built-in editor. We should fix this for September
