### ISSUE TITLE
Consider adding documentation to describe that setting message to empty string removes it from TreeView

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#81758]
Issue Type: <b>Feature Request</b>

Testing https://github.com/microsoft/vscode/issues/81634

Everything worked well. The only suggestion I would make is to add to the documentation somewhere that setting message to the empty string removes it from the TreeView. I wasn't sure if that would just leave an empty line at the top of the TreeView but since there wasn't anything like treeView.RemoveMessage I just tried it.

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gregvanl** [comment]
Setting to null also clears the message.
