### ISSUE TITLE
Expect to see root node in call hierarchy viewer

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#81753]
Issue Type: <b>Feature Request</b>

Testing https://github.com/microsoft/vscode/issues/81658

In the call hierarchy view I would expect to see a root node in the tree view. For example, in the screenshot below I would expect to see the start node at the top of the tree on the right hand side.

![image](https://user-images.githubusercontent.com/1704059/65970433-74d9cb80-e45e-11e9-9aef-63f1c6a6e97f.png)

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
Not so easy... We used to have a more complex API that allows to resolve the anchor first and that supports drilling into that anchor. Once we simplifies the API that feature was lost (removed). For the reference viewlet we have a similar problem (as requests are also document/position-based and not anchor-based) and there we simply use the word at position... 

There is the option to extend the API with an new function `prepareCallHierarchy` which resolves the anchor. This is related to https://github.com/microsoft/vscode/issues/81748

**Comment by stevencl** [comment]
I think it would be good to explore if this can be added. One of the problems just now is that the calls/caller toggle sits above the tree view so it can be slightly confusing to click and see the tree change to show calls/caller of the root, when that isn't shown in the tree.

Perhaps it would be possible to:
1. Add a label at the top of the tree, not a root, which says 'Showing calls to foo' or 'Showing callers of foo' depending on the toggle.
2. Or change the tooltip of the toggle so that it says 'Show calls to foo' or 'Show callers of foo' depending on the state of the toggle.
