### ISSUE TITLE
Markdown wrongly highlighting --- horizontal rules as frontmatter

### ISSUE THREAD

**Issue by paulozoom** [microsoft/vscode#81756]
Issue Type: <b>Bug</b>

If a `---`-style horizontal rule is done after the frontmatter, the highlighter considers anything following that rule to be frontmatter, and highlights it as such, even though it isn’t, as frontmatter is only allowed at the beginning.

For example, this block (which is highlighted fine here on GH):

```markdown
---
title: 'Test'
---

## Hi!
Here’s an intro text.

---

## Hi!
After a thematic break, the highlight is broken.
```

Appears as such:

![image](https://user-images.githubusercontent.com/69427/65971749-fc2c3c80-e468-11e9-92fb-1339a6bc8976.png)

This has no effect on the Preview. It’s purely a syntax highlighting issue.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
vscode-dash|dee|2.2.0
xml|Dot|2.5.0
gitlens|eam|10.0.1
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.3.0
code-runner|for|0.9.14
vscode-yarn|gam|1.6.0
nightswitch|gha|1.1.0
vscode-pull-request-github|Git|0.11.2
gc-excelviewer|Gra|2.1.32
applescript|idl|0.18.1
vscode-gist|ken|3.0.3
auto-comment-blocks|kev|1.0.1
expand-region|let|0.1.2
rainbow-csv|mec|1.3.1
dotenv|mik|1.0.1
python|ms-|2019.9.34911
material-icon-theme|PKi|3.9.0
ruby|reb|0.25.3
shopify-liquid|sis|2.3.0
guides|spy|0.9.3
ayu|tea|0.18.0
mako|tom|0.2.0
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
jinja|who|0.0.8
better-align|wwm|1.1.6
cursor-align|yo1|1.0.4
city-lights-icon-vsc|Yum|1.1.3

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
I can't repo this. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by paulozoom** [comment]
@mjbvz Apologies, it doesn't. Sorry for taking your time.
