### ISSUE TITLE
Semicolon is not added after css property completion

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#81752]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/81673

The only time I see a semicolon being added after a css completion is if that property is marked as an emmet abbreviation. In the screenshot below, the only property that will get a semicolon added automatically is counter-reset

![image](https://user-images.githubusercontent.com/1704059/65968536-3bec2780-e45b-11e9-9df0-5f97359e0691.png)

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.17.0
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-containers|ms-|0.79.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.8
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.5
test-search-rg|rob|0.0.3

</details>

**Comment by octref** [comment]
Hey @stevencl, were you editing a CSS or scss/less file?

I see the issue is that `css.completion` settings are not inherited by `scss.completion` or `less.completion`. For example, changing `css.completion.triggerPropertyValueCompletion` has no effect on scss/less.

@aeschli Should we add 3 settings for each lang, or should we just make it inherit?

**Comment by aeschli** [comment]
We always have had separate lint settings for css, less and scss, and this should be the same for completions. -> add `less.completion.completePropertyWithSemicolon`, `scss...`
IMO inheriting would be a new thing and would overcomplicate things, given that we already have a hierarchy of 5 scopes (folder, workspace, machine, user, default).

We can also think of not having a setting at all. That would be my favourite.

**Comment by stevencl** [comment]
As it happens I was editing a CSS file, not a scss or less file.

However, after turning the setting off and back on again, I am now getting the semicolon added after completions.

It definitely didn't work the first time I tried it, and I had checked that the setting was enabled. But it is working now.

**Comment by octref** [comment]
@stevencl Thanks, feel free to reopen if you can find a repro again.
@aeschli I will track that in #81845.

**Comment by bowdenk7** [comment]
I see the same issue but with `columns`

![image](https://user-images.githubusercontent.com/820883/66081759-8e8e1800-e51d-11e9-83aa-f23bbc594c47.png)

**Comment by octref** [comment]
`columns: ;` is coming from emmet and has nothing to do with the other ones.

**Comment by stevencl** [comment]
I can repro this now. It happens consistently when I try to add a css property immediately after opening a css file. I don't get the semi colon added upon completion for the first property I try to add. Then when I add the semicolon myself, then add another property, semi colons are added upon completion as expected.

**Comment by octref** [comment]
@stevencl I still cannot repro — I'm guessing it's because the startup hasn't finished and setting hasn't been synced.

However since this setting defaults to true, I have made its value true when no setting can be found.
