### ISSUE TITLE
context menu appears behind quick pick

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#81750]
Version: 1.39.0-insider
Commit: 313ede61cbad8f9dc748907b3384e059ddddb79a
Date: 2019-10-01T07:29:26.409Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

- Install Remote -SSH extension, invoke `Remote SSH: Connect to Host...`
- right click into the text box
- context menu appears behind the quick pick dialog

![image](https://user-images.githubusercontent.com/6461412/65965997-cfbff280-e45f-11e9-8ea7-db693588f94d.png)

**Comment by TylerLeonhardt** [comment]
Appears fixed.
![image](https://user-images.githubusercontent.com/2644648/138367489-b6a16f34-95d8-474b-be36-73feebf42e3a.png)
