### ISSUE TITLE
Whitespace symbols are missed in the middle of a text

### ISSUE THREAD

**Issue by niberius** [Microsoft/vscode#8175]
- VSCode Version: 1.2.1
- OS Version: Win7 x64 Enterprise (also reproduced under Linux)

Preconditions:
1. User set following option:
{
    "editor.renderWhitespace": true
}

Steps to Reproduce:

1. Create new file
2. Type few spaces, then few words devided by space, then few spaces again.

Actual result: whitespaces shown only before the first word and after the last word. No whitespace symbols between words. Screenshot: http://zoltor.org/scr/2016-06-27_115413.png

Expected result: whitespace symbol is showing everywhere in text where space was typed.

**Comment by alexandrudima** [comment]
Let's track this in #3828
