### ISSUE TITLE
Bug vsCode Structure Static Components

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#81755]
Hey guys, why i cant get `STRUCTURE` correctly expend for the scenario `A2`.

![image](https://user-images.githubusercontent.com/24865815/65969602-11867400-e433-11e9-8403-762ee16251ca.png)

All other test scenario seem work fine, am able to expend `STRUCTURE`.
Did you think it possible to fix this?
Because i'm using the scenario A2 in my project and it an issue for me because intellisense also no seem able to work.

- VSCode Version: 
![image](https://user-images.githubusercontent.com/24865815/65969947-a5f0d680-e433-11e9-9e90-e772dd315430.png)

Steps to Reproduce:

1. copy past this code
```js
class A {
    constructor() {
        this.A1 = class A1 {//#region [rgba(0, 0, 0, 0.3)]
            constructor() {};
            static get getterStatic() {return true}
            get getter() {return true};
            method(){};
        };//#endregion
        var A5 =  class A5 {//#region [rgba(0, 0, 0, 0.3)]
            constructor() {};
            static get getterStatic() {return true}
            get getter() {return true};
            method(){};
        };//#endregion
    };

    static A2 = class A2 {//#region [rgba(0, 0, 0, 0.3)]
        constructor() {};
        static get getterStatic() {return true}
        get getter() {return true};
        method(){};
    };//#endregion
    
    get A3() { 
        return class A3 {//#region [rgba(0, 0, 0, 0.3)]
            constructor() {};
            static get getterStatic() {return true}
            get getter() {return true};
            method(){};
        };//#endregion
    };

    static get A4() {
        return class A4 {//#region [rgba(0, 0, 0, 0.3)]
            constructor() {};
            static get getterStatic() {return true}
            get getter() {return true};
            method(){};
        };//#endregion};
    }; 
};

```
2. Click on `EXPLORER` 
![image](https://user-images.githubusercontent.com/24865815/65970464-9faf2a00-e434-11e9-87a7-081f9ac83b3c.png)
Expand the slot `STRUCTURE`.
![image](https://user-images.githubusercontent.com/24865815/65970443-91f9a480-e434-11e9-9b89-a8f406ddee2a.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/33715 to track upstream
