### ISSUE TITLE
Attach to process: cannot put process '1504' in debug mode.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#81759]
Issue Type: <b>Bug</b>

Running with Remote-Containers attached to a container with Node.js 12. I cannot get a simple sample to switch into debug mode and VS Code attach to it. The sample's says the debugger is listening.

![image](https://user-images.githubusercontent.com/9205389/65974904-0f8dd680-e46e-11e9-86f2-c255ad384c46.png)

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T05:39:51.694Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.9.184-linuxkit
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python Sample|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (0.36GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container node:latest (/quizzical_davinci)|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (0.36GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.79.0

</details>

**Comment by connor4312** [comment]
I was able to repro with the old debugger, but it looks like js-debug works here. Thus closing since node-debug is going away soon.
