### ISSUE TITLE
Expect functions ordered top down in call hierarchy viewer

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#81754]
Issue Type: <b>Feature Request</b>

Testing https://github.com/microsoft/vscode/issues/81658

When invoking the call hierachy viewer I would expect to see the methods ordered by their top down order in the function. I was a bit surprised for example to see that shortcut appears before intermediate1 in the screenshot below.

![image](https://user-images.githubusercontent.com/1704059/65970337-40660f80-e45e-11e9-9a2a-c7d03b98ac6c.png)

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T07:29:05.652Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
The view uses the order that the provider/extension defines. I totally agree that it should be by position but my dummy extension didn't go that far. Leaves the question if the view should overrule the provider order?

**Comment by stevencl** [comment]
I see. I'm not sure about overruling the provider. I don't know the full implications of doing so, but I would imagine that breaking convention and introducing an inconsistency like that might cause issues elsewhere? I might be wrong though, like I said, I'm not completely aware of the full implications of overruling the provider in this instance.
