### ISSUE TITLE
Gracefully handle build errors for preLaunchTask

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81768]
Testing #81637

I tested this on the [vscode-pullrequest-github](https://github.com/microsoft/vscode-pull-request-github) repo with some older npm modules (it had been a while sine I last synced). When I attempted to launch the extension + default build task (via prelaunch task) I was hit with a build error: 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/35271042/65980751-a043c280-e42c-11e9-8fae-6cfb94951204.png">

So I stopped the debug session and also killed the terminal process, but then the debug session continued:

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/35271042/65981255-9078ae00-e42d-11e9-92b4-8be34bccb864.png">

I think that if you launch the default build task via a launch config and you have build errors, the launch task should stop. I would also love it if in this situation when you stop the debug session that it also stops the build process as you likely need to investigate the errors.

**Comment by alexr00** [comment]
Various things required for this:
- Terminal would need to indicate that the terminal was killed in `onExit`
- Tasks that exit because the terminal is killed would need to return a non-zero exit code
- Debug would need to look for that magic error code
- Debug would need to kill the task when debug is stopped

**Comment by isidorn** [comment]
@alexr00 Nice analysis.
For the 4th point there is already a request for this. We could also have a postDebugTask that could be configured to stop it.

**Comment by Tyriar** [comment]
> Terminal would need to indicate that the terminal was killed in onExit

@alexr00 you can probably change this line:

https://github.com/microsoft/vscode/blob/1e7a92b119d68a93b0d33bb83b5d4feee4ff984f/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1108

To just `this._onExit.fire(exitCode);`, that way it will be undefined if the user killed the terminal. Tasks is the only consumer or this so it should be safe.

**Comment by alexr00** [comment]
@Tyriar nice, thanks for the pointer!

**Comment by alexr00** [comment]
It looks like everything already in place from tasks and terminal. The task service returns null instead of a task summary if the terminal is killed while the task is running. The rest is work in debug.

**Comment by alexr00** [comment]
The work needed to propagate an undefined exit code (signalling terminal terminated) through to debug is done. @isidorn over to you to handle the undefined exit code and prevent the launch from proceeding!

**Comment by isidorn** [comment]
@alexr00 oki doki

**Comment by isidorn** [comment]
Pushed a potential fix for this.
@misolori can you please try it out and let us know how it behaves now for you. Thank you

**Comment by misolori** [comment]
It does appear to handle build errors better, but now I run into an issue where it's trying to finishing building + launching the debugger but never proceeds:

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/35271042/67232191-af97a980-f3f5-11e9-8bca-23acbc29937b.png">


Unrelated?

**Comment by isidorn** [comment]
@misolori Is the build finished successfuly here?
@alexr00 it seems like the task does not report it is done to the debug.

Please note that I pushed the change which should just affect the happy no error case

**Comment by alexr00** [comment]
Your task output is missing the start and end pattern that tasks uses to tell debug that the task got far enough. I think you need to add `--info-verbosity verbose` to your webpack task.
See https://github.com/microsoft/vscode/issues/82076#issuecomment-543249046 for more info on that.
