### ISSUE TITLE
Settings UI gear cut off when scrolling near selected TOC item

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81764]
This only happens when you are on an active category and the gear is on the same line, likely due to the list background color:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/35271042/65978147-01b56280-e428-11e9-9eaf-65b38e14dce5.png">

**Comment by roblourens** [comment]
Looks ok for me, I can check on your machine later 
![image](https://user-images.githubusercontent.com/323878/65978511-b18ad000-e428-11e9-99c9-2ff7b40c39fe.png)

**Comment by misolori** [comment]
@roblourens I think you have to make your window smaller where it starts to re-size the content.

**Comment by roblourens** [comment]
Oh I see it. Is the gap between the columns supposed to get smaller? It's so subtle and I can't remember whether it's on purpose.

**Comment by misolori** [comment]
I don't remember 🤷‍♂ , but it should probably stay there so it doesn't overlap with the TOC.
