### ISSUE TITLE
Add icons for built-in extensions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81760]
There is a few more built in extensions without icon:

![image](https://user-images.githubusercontent.com/900690/65964559-84a4e000-e45d-11e9-93ef-f22ad934974e.png)

![image](https://user-images.githubusercontent.com/900690/65964567-88d0fd80-e45d-11e9-9617-44ac71c9221b.png)

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/80677#issuecomment-537028631_

**Comment by misolori** [comment]
Added icons for all of our built-in extensions:

<img width="349" alt="CleanShot 2021-04-20 at 11 53 09" src="https://user-images.githubusercontent.com/35271042/115449461-b14f5280-a1cf-11eb-85e4-07e87dd198bb.png">

Will make PRs for the extensions that are bundled

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/116280561-17684680-a789-11eb-8be8-6c3a4aeefffa.png)

![image](https://user-images.githubusercontent.com/900690/116280575-1cc59100-a789-11eb-9957-956867832375.png)

These 2 still don't have icons.

**Comment by misolori** [comment]
Both of those have already had the PRs merged and @connor4312 just needs to release an update:

1. JavaScript Debugger Companion Extension - https://github.com/microsoft/vscode-js-debug-companion/pull/13
2. vscode-js-profile-table - https://github.com/microsoft/vscode-js-profile-visualizer/pull/34

**Comment by connor4312** [comment]
I will do this as part of endgame (most likely today)

**Comment by rzhao271** [comment]
Reopening this issue for now since we still have https://github.com/microsoft/vscode/issues/81760#issuecomment-827755443

**Comment by misolori** [comment]
@connor4312 can you close this issue once you've published those extensions? Thanks.
