### ISSUE TITLE
About dialog is missing OS on desktop

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81763]
MacOS

The about dialog is supposed to have the OS and electron version, not useragent

![image](https://user-images.githubusercontent.com/323878/65977830-74720e00-e427-11e9-89e0-2eb8bb1905b8.png)

**Comment by sbatten** [comment]
@bpasero looks to be caused by your change 2105bcef65f603bfe364e5bc0e5d2468657f2081

**Comment by bpasero** [comment]
@roblourens @sbatten how exactly do you get that about dialog (custom) on the desktop version?!

**Comment by usernamehw** [comment]
```js
"workbench.dialogs.customEnabled": true,
```
and reload the editor.

**Comment by bpasero** [comment]
I pushed a change to show the about dialog natively always. We should clean this up once https://github.com/microsoft/vscode/issues/81820 is properly implemented.
