### ISSUE TITLE
Canceling default build task via launch config re-appears

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81767]
Testing #81637

![gif](https://user-images.githubusercontent.com/35271042/65980397-ec423780-e42b-11e9-9e87-f007ba058132.gif)

Steps:
1. Create two default build tasks in your `tasks.json`
2. Use the new `"preLaunchTask": "${defaultBuildTask}"` on a launch config
3. Launch a session
4. When prompted to choose a build task, hit cancel
5. :bug: the same prompt appears twice

I expected that when I first hit Cancel that it would either cancel the entire sequence (build + launch) or at least cancel the build. Feels like a bug that I'm asked twice.

VS Code version: Code - Insiders 1.39.0-insider (313ede61cbad8f9dc748907b3384e059ddddb79a, 2019-10-01T05:39:51.694Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_3695494|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.35.1
vscode-eslint|dba|1.9.1
prettier-vscode|esb|2.3.0
vscode-open-in-github|fab|1.2.1
vscode-pull-request-github-insiders|Git|2019.9.38342
todo-tree|Gru|0.0.156
svg|joc|1.0.2
vscode-colorize|kam|0.8.13
vscode-azureappservice|ms-|0.16.0
vscode-azurestorage|ms-|0.7.1
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-containers|ms-|0.79.0
remote-ssh-edit-nightly|ms-|2019.10.900
remote-ssh-explorer-nightly|ms-|2019.10.900
remote-ssh-nightly|ms-|2019.10.900
azure-account|ms-|0.8.5
vscode-typescript-tslint-plugin|ms-|1.2.2
cloudenv|ms-|1.0.899
cloudenv-extensions|ms-|1.0.899
vsliveshare|ms-|1.0.905
azurerm-vscode-tools|msa|0.7.0
rescuetime|Res|1.0.1
code-settings-sync|Sha|3.4.3
notification-tester|svi|2.1.3
ayu|tea|0.18.0
errorlens|use|2.7.1
vscode-open-in-github|ziy|1.3.6

(5 theme extensions excluded)

</details>

**Comment by misolori** [comment]
This also happens when I have an empty `tasks.json` file, it will then ask the same question 3x.

**Comment by alexr00** [comment]
This happens because resolve variables is essentially called twice :(

**Comment by dbaeumer** [comment]
This is IMO still unhappy for a user. If I cancel the task picker I get this:

<img width="326" alt="capture" src="https://user-images.githubusercontent.com/1931590/66126072-d29a1f00-e5e8-11e9-8c99-9085e5f7e7ea.png">

I would rather expect that the whole debug attempt is canceled and that the task quick pick contains an entry 'Continue debugging without prelauch task`

**Comment by alexr00** [comment]
I don't think it makes sense to have a "Continue debugging without prelaunch task" in the quick pick. The person who added the launch config specified that the prelaunch task should be ${defaultBuildTask}. Debug could have a different message there that offers to debug without the prelaunch task.

**Comment by isidorn** [comment]
Pressing escape should just quit the whole operation. Debugging should not start.
User should not get spammed with error messages. It is a user action, no explanation is needed that he just quit it.
If the user wants to start without a prelaunch task he should edit his launch.json
