### ISSUE TITLE
Preserve Case Hyphen and Underscore replacement issues

### ISSUE THREAD

**Issue by skprabhanjan** [microsoft/vscode#81779]
@roblourens ,
Replace string functionality in search does not work properly for hyphen and underscore separated variables , Initially figured it out from this [comment](https://github.com/microsoft/vscode/issues/79525#issuecomment-534383273)
**Example:** 

- Replacing` Foo-Bar `to `test-replace` with preserve case turned on replaces correctly to `Test-Replace`
- Replacing `foo-Bar` to `test-replace` with preserve case turned on replaces incorrectly to `test-replace` instead of `test-Replace`

**PS : Additional Info from the code**
I found out there is a bug in `buildReplaceStringWithCasePreserved` function.
The whole idea to call the replacement function again at [this line](https://github.com/microsoft/vscode/blob/master/src/vs/base/common/search.ts#L43) was to reuse the already existing replacement logic ( First char capital , full caps and full small) but there was a bug as the hyphens and underscores were not even called because of wrong ordering in the condition checking logic.

**Comment by roblourens** [comment]
Thanks for the PR, can you please phrase this issue in the form of a bug report (ie describe what to do, what happens, what is supposed to happen)
