### ISSUE TITLE
Windows key `code` down not find VS Code

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/vscode#81770]
- VSCode Version:
- OS Version:

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install VS code and DO NOT say add a desktop item
2. After install, hit the windows key and type `code`. Notice that VS code is not an option
3. re run the install and check the add desktop item option
4. After done, retry step 2 and notice VS code is found
5. Delete the desktop shortcut
6 Repeat step 2 and VS Code is NOT found

Note that the Windows key workflow works for all my other apps (e.g., slack, ...) and there are no desktop items on my fresh Windows 10 machine.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by hadzhiyski** [comment]
I will take this one

**Comment by hadzhiyski** [comment]
Hello @jeffmcaffer,

Did you chose to create the Start Menu folder?

![image](https://user-images.githubusercontent.com/20074286/68713147-e05aa100-05a5-11ea-8063-8990631e7098.png)

If you select the "Don't create a Start Menu folder" option, vscode will not be available in Windows search. Otherwise, it should always appear in the search.

Is that your case?

**Comment by jeffmcaffer** [comment]
I don't recall that option. There was an option to create a desktop shortcut. If I deselected that or deleted the shortcut, Code would not show up in the search results. Adding the shortcut back would restore search. Note that that behavior is unique to VS Code. Search for all other apps I have works fine (as I have 0 desktop shortcuts).

Note that subsequently I have installed Code on another new laptop and it is working as expected.

**Comment by hadzhiyski** [comment]
I am using Code without Desktop icon (all other apps as well) and the search is working just fine. In my opinion, it is because of the Start Menu option. Windows Search primarily does the search there.

@jeffmcaffer should we consider this issue as closed? If so, @joaomoreno, please close it

**Comment by joaomoreno** [comment]
> Note that subsequently I have installed Code on another new laptop and it is working as expected.

Strange. Must be something in your other machine preventing Windows from finding Code. Closing this issue. I'd still be interested in knowing what it is that breaks this, though.
