### ISSUE TITLE
Provide an 'Extension: Install ' command in the palette

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8177]
The command palette shows several extension related commands:

![image](https://cloud.githubusercontent.com/assets/172399/16374808/7f0dbf46-3c58-11e6-98b8-d6f7d67e320f.png)

For completness we should also add `Extensions: Install` to the 'Extenions' category. It should open the extensions viewlet in a mode for installing an extension.

**Comment by bpasero** [comment]
I do agree. Easy enough as just opening the viewlet.

**Comment by isidorn** [comment]
We already have a view: show extensions action that opens the viewlet - it is named like that for consistency with other openeing the viewlet actions.
I can add another action with a 'Extensions: Install' name that just does the same

![screen shot 2016-06-27 at 14 17 55](https://cloud.githubusercontent.com/assets/1926584/16379479/1091e97e-3c72-11e6-8435-98833a8f9a07.png)

**Comment by bpasero** [comment]
@isidorn yeah, thanks. We should try to drive as much traffic to our new UI.
