### ISSUE TITLE
ctrl+w is closing 2 editors when custom webview editor image preview is focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81771]
#81698

It's closing the webview editor as well as the next editor. There may also be an issue with `editorIsOpen` context key because this keybinding triggers when only the webview is open.

**Comment by mjbvz** [comment]
I've tested this on MacOS and Ubuntu can can't repo this. Any specific steps required?

**Comment by Tyriar** [comment]
Seems fixed now
