### ISSUE TITLE
Chords don't work when webview editor is focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81775]
#81698

Windows

1. Open an image with built-in image preview
2. Click in the image to focus/zoom
3. ctrl+k, the chord status bar item appears as expected
4. ctrl+t, the chord status bar item disappears and the non-chord ctrl+t keybinding executes

![image](https://user-images.githubusercontent.com/2193314/65983540-9624c280-e432-11e9-8c20-76d64cba0713.png)

**Comment by Tyriar** [comment]
ctrl+` also doesn't seem to work when image preview is focused.

**Comment by mjbvz** [comment]
Just tested this on windows and mac and I can't reproduce this. Did you perhaps have experimental iframe based webviews enabled? Keybindings were not working properly in the for a while but also should be fixed now

**Comment by Tyriar** [comment]
@mjbvz I don't think I ever set that, this is working now though. Perhaps Electron 4?
