### ISSUE TITLE
Expensive sync call getWebviewContents is triggered twice when opening webview editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81780]
#81698

Windows

![image](https://user-images.githubusercontent.com/2193314/65984488-bce3f880-e434-11e9-96b8-c469cc096157.png)

https://github.com/microsoft/vscode/blob/9c1fa6f48e19e6424fe082e870317de10dbf6b38/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L54-L55

https://github.com/microsoft/vscode/blob/9c1fa6f48e19e6424fe082e870317de10dbf6b38/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L102-L103

**Comment by Tyriar** [comment]
It's also fetched on layout, can we cache it instead?

https://github.com/microsoft/vscode/blob/9c1fa6f48e19e6424fe082e870317de10dbf6b38/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L574

**Comment by mjbvz** [comment]
Generic webview issue so marking for October
