### ISSUE TITLE
Expensive getWebviewThemeData for webviews happens every time a webview is focused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81788]
#81698

![image](https://user-images.githubusercontent.com/2193314/65986869-97a5b900-e439-11e9-9949-c2cb0bd31a81.png)

https://github.com/microsoft/vscode/blob/9c1fa6f48e19e6424fe082e870317de10dbf6b38/src/vs/workbench/contrib/webview/common/themeing.ts#L25-L31

Some suggestions:

- Cache (only while webviews are active + some expiry?)
- Don't use reduce and assign to `styles` while looping over the registry colors

**Comment by mjbvz** [comment]
Good idea. Generic webview issue so marking for October
