### ISSUE TITLE
Outline reflect current editing line in source file 

### ISSUE THREAD

**Issue by themelz** [microsoft/vscode#81796]
When the current editing line in the source editor changes, by clicking in a new line, by doing a find, etc., the highlighted function should change accordingly. 

This will allow the user to quickly the name of the function and if desired the local variables which should be useful for a lengthy function on a small screen.

It will also remove the need to sometimes click twice to scroll to the desired area of the source file. For example, if you are editing function A but in the outline function B is highlighted, and you want to go straight to function B, you have to click something else in the outline then clicking function B in the outline.

**Comment by jrieken** [comment]
This can be done with the "Follow Cursor" mode

<img width="575" alt="Screenshot 2019-10-02 at 09 25 25" src="https://user-images.githubusercontent.com/1794099/66025363-94243780-e4f6-11e9-8cfe-a2ad8937cf08.png">
