### ISSUE TITLE
Project Tabs

### ISSUE THREAD

**Issue by krastanov-veselin** [microsoft/vscode#81793]
Hi guys!

It would be really awesome to be able to open multiple projects in the same window, since both on Macos and Windows it's becomming difficult navigating to a specific window/project by using MacOS/dock or Windows/Taskbar, especially Windows/Taskbar, since MacOS has dedicated maximizing-ish ability.

Hope you feel the same about this feature.

Kind regards,
V. Krastanov

**Comment by Tyriar** [comment]
We support multi-root workspaces to have multiple folders in the same window as well as native tabs on macos. Check out https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by krastanov-veselin** [comment]
Thanks guys!
