### ISSUE TITLE
Diff editor lightbulb is gone

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81790]
Testing https://github.com/microsoft/vscode/issues/81679

The lightbulb button with the "copy deleted lines" action is gone, I don't see it in the diff editor anymore. Not sure if it's related to icons or something else.

**Comment by misolori** [comment]
Good catch, I haven't touched these icons but the parent class changed. Fixed now.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/35271042/65995317-26223680-e44a-11e9-8557-60bedd57ded9.png">
