### ISSUE TITLE
cmd+k cmd+k shortcut

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81795]
We recently added `cmd+k cmd+k` as a shortcut for "Toggle Fold" but some of us were thinking that it is not a good choice. It is easy to trigger on accident while trying to hit another chord, and it could be very confusing to someone if their code disappears and they don't know how to unfold it.

Also, this shortcut is already used in the keyboard shortcuts JSON editor to add a shortcut, and this now breaks that and triggers Fold instead.

@Tyriar

**Comment by Tyriar** [comment]
I think we should leave cmd+k cmd+k unbound, also k isn't anywhere in "toggle fold" so it doesn't seem like an intuitive choice anyway.

**Comment by aeschli** [comment]
Visual Studio uses `Ctrl + M - Ctrl + M`, and that's why I ended up with `Ctrl + K Ctrl + K`.
I'm fine to change it

**Comment by aeschli** [comment]
I change it to `Ctrl + M - Ctrl + L`
