### ISSUE TITLE
VSCode suggests downloading unusuable version (x64 on non-x64 machine)

### ISSUE THREAD

**Issue by conioh** [microsoft/vscode#81792]
Issue Type: <b>Bug</b>

1. Download and install VSCode x86-32 on an ARM64 machine (Asus NovaGo, HP Envy x2, Lenovo Yoga C630, etc.)
2. Run VSCode.
3. Note the following message:

![image](https://user-images.githubusercontent.com/10606081/65993536-1c282400-e49a-11e9-8aed-030961bc01e6.png)

The link on the word "here" leads to: https://code.visualstudio.com/updates/v1_15#_windows-64-bit

The downloads there are x86-64 however rather than ARM64. This message is wrong or at least _very_ misleading. Please remove it.

You don't yet support ARM64 as requested in #33620? Fine. (Actually not so fine since it seems to be possible now that much work on Chromium and Electron ARM64 has been done. See: https://github.com/ljsabc/Code-OSS-Win32-arm64)

But before telling me to go and download another version, please make sure it can actually run on my machine. Instead of just checking bitness, check the platform too. See the [`IsWow64Process2`](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2) function (in contrast with `IsWow64Process`) for example.

When you finally support ARM64 you could bring the message back, and point the link to the correct (future) blog post.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:35.387Z)
OS version: Windows_NT ia32 10.0.18990

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon(TM) 835 (8 x 1555)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.68GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by conioh** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> Support ARM64 build for Windows (#33620)

Experiment failed.

**Comment by joaomoreno** [comment]
Verification: just code review, everything was removed
