### ISSUE TITLE
Data URI webview editors don't have correct title set

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81791]
#81698

Linux

Regression with image preview.

Insiders:

![image](https://user-images.githubusercontent.com/2193314/65988364-86aa7700-e43c-11e9-85f2-dd5f6275bb56.png)

Stable:

![image](https://user-images.githubusercontent.com/2193314/65988390-94f89300-e43c-11e9-8f23-1a6da132924a.png)

**Comment by mjbvz** [comment]
How did you get into this state?

**Comment by Tyriar** [comment]
@mjbvz delete a file tracked in git and open the file diff from SCM viewlet

**Comment by mjbvz** [comment]
Fixed by 2cf9921ee52b6d602a48dce1d5ebdacdd37bcf6b

**Comment by jrieken** [comment]
Verified, tho the hover title is still weird...

**Comment by bpasero** [comment]
This is not good, we end up putting super large DOM nodes:

![image](https://user-images.githubusercontent.com/900690/66108003-da929880-e5c1-11e9-8965-c1fd7ed72d2f.png)

@mjbvz we need to somehow preserve our logic that checks for `Schemas.data` URIs and in that case, not access the path component which is always super large. If you search for references to `Schemas.data` you can see all the places where we do special treatment for these URIs. My guess is that your URI is using a different scheme maybe or we forgot one place here?

We also heard about reports where the editor became very slow when data URIs of large size entered the system and we would e.g. do mime type detection using regex matching. Thus `mime.ts` also carefully checks for these schemas and avoids computation in that case. We need to make sure we are not regressing now.
