### ISSUE TITLE
Backslash in folder name not handled correctly by flattened tree view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81798]
Testing https://github.com/microsoft/vscode/issues/81233

Sorry for this issue.

- macOS
- Create a folder with \ in the name
- It's shown as a / in SCM, but correctly in other places

Explorer:
![image](https://user-images.githubusercontent.com/323878/66000900-3ab7fc00-e455-11e9-8218-ff4f9d18a75f.png)

SCM:
![image](https://user-images.githubusercontent.com/323878/66000927-4acfdb80-e455-11e9-92e5-b22efa11f999.png)

Editor title:
![image](https://user-images.githubusercontent.com/323878/66000942-58856100-e455-11e9-9bf0-9e9ad97e834e.png)

**Comment by joaomoreno** [comment]
> Sorry for this issue.

:dancer:
