### ISSUE TITLE
Image Preview Extension page feels empty

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#81801]
Testing #81674

Even compared to our other built-in extensions, I expect a features section describing the basic behavior. 

Additionally, are custom editors not surfaced in the "Contributions" tab? Should they be?

**Comment by sbatten** [comment]
dupe of #81741 with additional question

**Comment by mjbvz** [comment]
Yes this should be covered by #81741

Can you please open the contributions point as a separate issue

**Comment by sbatten** [comment]
done #81802
