### ISSUE TITLE
CallHierarchyOutgoingCall and CallHierarchyIncomingCall properties should have comments

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#81809]
Testing #81655

Confusing with CallHierarchyOutgoingCall having sourceRanges and a target.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/81746

**Comment by jrieken** [comment]
Folding into https://github.com/microsoft/vscode/issues/81746 - the needs docs or and diagram explaining how things link up. The domain just happens to be complex...
