### ISSUE TITLE
The html.suggest.html5 disables non-HTML5 features

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81807]
This bug happens in the Insiders v1.39.0

- VSCode Version: 1.39.0
- OS Version: 10.14.6

Steps to Reproduce:

1. Set `html.suggest.html5` to `false`
2. Try getting autocompletion for any non-HTML5 attributes or values, like `class` or `style`.

Expected behavior:
As per the `html.suggest.html5` description (Controls whether the built-in HTML language support suggests HTML5 tags, properties and values) I expected that non-HTML5 tags, properties and values would not be affected, so attributes like `class` or `style` would still have autocompletion.

Actual behavior:
No attributes or values at all have autocompletion, it seems to be completely disabled.

Does this issue occur when all extensions are disabled? Yes

**Comment by andrecasal** [comment]
No, that issue is something completely different.

**Comment by octref** [comment]
We don't tell HTML5 apart form HTML4 yet, but we can do that if the data is there.

**Comment by andrecasal** [comment]
Ok, so I guess it would make sense to change this setting's description to "Controls whether the built-in HTML language support suggests tags, properties and values".

**Comment by pankaj-webkul** [comment]
Doesn't sonarlint extension do that?

**Comment by andrecasal** [comment]
> Doesn't sonarlint extension do that?

It's still an extension. This should be integral to VS Code IMO.
