### ISSUE TITLE
spread syntax always error

### ISSUE THREAD

**Issue by dreamerleolioa** [microsoft/vscode#81813]
Issue Type: <b>Bug</b>

when i use spread syntax like picture below always comes error out.

![test](https://i.imgur.com/fSFJxrj.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.13.0
rest-client|hum|0.22.2
Angular2|joh|8.1.1
ws-frontend|Leo|1.1.0
vscode-language-pack-zh-hant|MS-|1.38.4
csharp|ms-|1.21.3
vscode-yaml|red|0.5.3
sass-indented|rob|1.5.1
vscode-scss-formatter|sib|1.4.2
vscode-icons|vsc|9.4.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by mjbvz** [comment]
Please share example code as text and the text of the error message so I can translate it

**Comment by dreamerleolioa** [comment]
sorry i found solution about my question.

after `npm i tslib` this error just gone.

thanks :D
