### ISSUE TITLE
The function menu bar becomes a white background     

### ISSUE THREAD

**Issue by zhangliqiang34** [microsoft/vscode#81811]
![image](https://user-images.githubusercontent.com/30541603/66009692-31c73900-e4ee-11e9-8d23-7013fbde6b38.png)

![image](https://user-images.githubusercontent.com/30541603/66009700-3ab80a80-e4ee-11e9-8981-15234f679dfc.png)

![image](https://user-images.githubusercontent.com/30541603/66009713-473c6300-e4ee-11e9-9ca1-9f629a85c43b.png)

 
Notebook model：thinkpad e480
 
It was normal until now, but it has been updated to the latest version

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you mean top menu bar?
![image](https://user-images.githubusercontent.com/1312662/66037077-7f0bd080-e517-11e9-9aec-2027fbbab245.png)

What value do you have for **Window: Title Bar Style** (`window.titleBarStyle`) setting?
Make sure it is set to `"custom"` otherwise it will match Windows style.

**Comment by zhangliqiang34** [comment]
You are right! think you very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Andrii Dieiev <notifications@github.com>
发送时间: Wednesday, October 2, 2019 6:25:21 PM
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: zhangliqiang34 <wuyaping34@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode] The function menu bar becomes a white background (#81811)


/needsMoreInfo

Do you mean top menu bar?
[image]<https://user-images.githubusercontent.com/1312662/66037077-7f0bd080-e517-11e9-9aec-2027fbbab245.png>

What value do you have for Window: Title Bar Style (window.titleBarStyle) setting?
Make sure it is set to "custom" otherwise it will match Windows style.

―
