### ISSUE TITLE
demo-callhierarchy would be clearer if didn't use "func" for ABC language items

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#81810]
Testing #81655

I was confused thinking much of the code was returning functions rather than ABC Language items which then become CallHierarchyItems (and only contain properties, no functions).

Suggest renaming example interface AbcLangFunc to AbcLangItem and use 'item' and 'items' to refer to intermediate variables.

**Comment by gregvanl** [comment]
Feel free to move this to the demo-callhierarchy repo.

**Comment by jrieken** [comment]
Sorry, but the demo app is nothing I am planning on productising or sharing with a broader audience. It's only there to enable testing as no language extension has implemented (the latest) API. Things will be easier once TS or Java (has a prototype already) has caught up.
