### ISSUE TITLE
No completion suggestion for '${defaultBuildTask}'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#81816]
Testing #81637

In the `launch.json` file there is no completion suggestion for `${defaultBuildTask}`. There are suggestions for other variables:

![image](https://user-images.githubusercontent.com/172399/66024563-7229b580-e4f4-11e9-8701-aa44799defc7.png)

**Comment by alexr00** [comment]
New completion suggestion text: "The name of the default build task. If there is not a single default build task then a quick pick is shown to choose the build task."
