### ISSUE TITLE
No defaultBuildTask quick pick - improve description

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#81817]
Testing #81637
- `launch.json` refers to `${defaultBuildTask}`
- `task.json` has no build task defined.

When pressing F5 I then get prompted to select the build task (which is good):
![image](https://user-images.githubusercontent.com/172399/66024835-36dbb680-e4f5-11e9-97dc-5814097e40c3.png)

Suggest to state why the picker shows up, e.g., 'Select the build task (there is no default build task defined)' or if the quick pick has a title: 
- title: No default build task defined
- water mark: Select build task

**Comment by alexr00** [comment]
No title, so opting for the suggested 'Select the build task (there is no default build task defined)'
