### ISSUE TITLE
Unable to Search in Marketplace

### ISSUE THREAD

**Issue by scottrinoz** [microsoft/vscode#81814]
Issue Type: <b>Bug</b>

I am unable to search the Marketplace for extesnions. I can see, access and install extensions from the Marketplace ONLy when using the pre-defined Filters, e.g @sort:installs lists the extensions, from where I can select, view the details and install, but I cannot search for extensions  e.g. by @category:keymaps or by Name   e.g. "Notepad", anthing NOT in the predefined filter options ALWAYS shows 'We cannot connect to the Extensions Marketplace at this time, please try again later". Yes I am behind a Coporate Firewall. Yes I have added the required proxy, which works perfectly with Node NPM, Python, PIP & Apache NetBeans etc I also have no issues with Extension Download/Install in VS2017 or VS2019.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|16.00GB (9.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
python|ms-|2019.9.34911
csharp|ms-|1.21.3
powershell|ms-|2019.9.0

</details>

**Comment by sandy081** [comment]
Can you please open developer tools `F1 > Toggle Developer Tools` and let us know if there are any errors in console and network tab?

**Comment by scottrinoz** [comment]
log.ts:173   ERR Unexpected token < in JSON at position 0: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (file:///C:/Users/XXXXXXXX/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:176)
    at Generator.next (<anonymous>)
    at r (file:///C:/Users/XXXXXXXX/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:35:399)

**Comment by scottrinoz** [comment]
extensionsViews.ts:254 Error querying extensions gallery Unexpected token < in JSON at position 0
r.length.e.isLocalExtensionsQuery.test.queryGallery.then.e @ extensionsViews.ts:254
Promise.then (async)
(anonymous) @ extensionsViews.ts:253
(anonymous) @ errors.ts:199
n @ errors.ts:199
query @ extensionsViews.ts:238
V.createCancelablePromise.e @ extensionsViews.ts:202
l @ async.ts:23
(anonymous) @ extensionsViews.ts:202
(anonymous) @ errors.ts:199
n @ errors.ts:199
show @ extensionsViews.ts:165
progress.Promise.all.t.map.e @ extensionsViewlet.ts:540
onDidAddViews @ extensionsViewlet.ts:539
viewsModel.onDidAdd.e @ viewsViewlet.ts:78
fire @ event.ts:572
onDidChangeViewDescriptors @ views.ts:471
E.n._register.n.onDidChangeActiveViews @ views.ts:253
fire @ event.ts:572
onContextChanged @ views.ts:198
fire @ event.ts:574
e @ event.ts:73
fire @ event.ts:572
fire @ event.ts:636
setContext @ contextKeyService.ts:296
set @ contextKeyService.ts:180
doSearch @ extensionsViewlet.ts:527
searchDelayer.trigger @ extensionsViewlet.ts:501
completionPromise.completionPromise.Promise.then @ async.ts:211
Promise.then (async)
trigger @ async.ts:205
triggerSearch @ extensionsViewlet.ts:501
_register.searchBox.onInputDidChange @ extensionsViewlet.ts:420
fire @ event.ts:574
x._register.x.onDidChangeContent @ suggestEnabledInput.ts:164
_eventEmitter.slowEvent.t @ textModel.ts:236
fire @ event.ts:572
endDeferredEmit @ textModel.ts:2835
pushEditOperations @ textModel.ts:1143
_innerExecuteCommands @ cursor.ts:886
executeCommands @ cursor.ts:844
_executeEditOperation @ cursor.ts:476
_type @ cursor.ts:779
trigger @ cursor.ts:700
trigger @ codeEditorWidget.ts:902
type @ codeEditorWidget.ts:1395
type @ viewController.ts:75
C._register._textAreaInput.onType.e @ textAreaHandler.ts:270
fire @ event.ts:572
_register.n.addDisposableListener @ textAreaInput.ts:273

**Comment by scottrinoz** [comment]
& extensionsViews.ts:254 Error querying extensions gallery Unexpected token < in JSON at position 0
r.length.e.isLocalExtensionsQuery.test.queryGallery.then.e @ extensionsViews.ts:254
Promise.then (async)
(anonymous) @ extensionsViews.ts:253
(anonymous) @ errors.ts:199
n @ errors.ts:199
query @ extensionsViews.ts:238
V.createCancelablePromise.e @ extensionsViews.ts:202
l @ async.ts:23
(anonymous) @ extensionsViews.ts:202
(anonymous) @ errors.ts:199
n @ errors.ts:199
show @ extensionsViews.ts:165
progress.Promise.all.t.map.e @ extensionsViewlet.ts:540
onDidAddViews @ extensionsViewlet.ts:539
viewsModel.onDidAdd.e @ viewsViewlet.ts:78
fire @ event.ts:572
onDidChangeViewDescriptors @ views.ts:471
E.n._register.n.onDidChangeActiveViews @ views.ts:253
fire @ event.ts:572
onContextChanged @ views.ts:198
fire @ event.ts:574
e @ event.ts:73
fire @ event.ts:572
fire @ event.ts:636
setContext @ contextKeyService.ts:296
set @ contextKeyService.ts:180
doSearch @ extensionsViewlet.ts:527
searchDelayer.trigger @ extensionsViewlet.ts:501
completionPromise.completionPromise.Promise.then @ async.ts:211
Promise.then (async)
trigger @ async.ts:205
triggerSearch @ extensionsViewlet.ts:501
_register.searchBox.onInputDidChange @ extensionsViewlet.ts:420
fire @ event.ts:574
x._register.x.onDidChangeContent @ suggestEnabledInput.ts:164
_eventEmitter.slowEvent.t @ textModel.ts:236
fire @ event.ts:572
endDeferredEmit @ textModel.ts:2835
pushEditOperations @ textModel.ts:1143
_innerExecuteCommands @ cursor.ts:886
executeCommands @ cursor.ts:844
_executeEditOperation @ cursor.ts:476
_type @ cursor.ts:779
trigger @ cursor.ts:700
trigger @ codeEditorWidget.ts:902
type @ codeEditorWidget.ts:1395
type @ viewController.ts:75
C._register._textAreaInput.onType.e @ textAreaHandler.ts:270
fire @ event.ts:572
_register.n.addDisposableListener @ textAreaInput.ts:273

**Comment by sandy081** [comment]
What is the search input when you see this error?

**Comment by scottrinoz** [comment]
As per initial post, this error was simply on the name 'notepad' as I was looking for the notepad ++ Keymap. But it really doesn't matter what name, it could just as easily be 'blue' or 'pink'.

**Comment by sandy081** [comment]
I am not able to repro this and hence have to ask you to get as much info as possible to know about the issue. Sorry for that.

Can you open network tab in developer tools and let me know the response for the request to Marketplace?
