### ISSUE TITLE
Add Vim Support for jupyter notebook of python interactive window

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/vscode#81812]
![image](https://user-images.githubusercontent.com/44701446/66009876-05f88300-e4ef-11e9-9107-945f396007d8.png)

The new jupyter notebook of python interactive window doesn't support VIM extension. Will Vim extension support be added in the future?

https://github.com/microsoft/vscode-python/issues/5959

**Comment by Tyriar** [comment]
I believe this is more of a consequence of how the extension built the feature, you should go through their repo first and maybe VS Code could provide APIs to help support this.
