### ISSUE TITLE
Click+drag of webview editor only sometimes works

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81829]
Testing https://github.com/microsoft/vscode/issues/81698

Dragging a webview editor only works sometimes (feels like 50%). 

I opened 2 image editors and tried to drag and snap them into the grid. 

![editorDrag](https://user-images.githubusercontent.com/38270282/66033414-80cd9800-e507-11e9-9707-c86445da3d05.gif)

**Comment by mjbvz** [comment]
Duplicate of #25854 I believe
