### ISSUE TITLE
Webview editor eats ctrl+shift+p for opening the command palette

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81823]
Testing https://github.com/microsoft/vscode/issues/81698

Open an image using the image preview.
Click on the image.
Hit tab. At this point I have no idea what has focus.
Ctrl+shift+P to open the command palette.
🐛Nothing appears to happen

**Comment by mjbvz** [comment]
Having trouble reproducing this. I tested on windows with the latest insiders build.

Are there any extra steps required besides hitting tab after clicking on the image?

**Comment by alexr00** [comment]
No, that was it. I could repro it 100% yesterday, but now I can't.
