### ISSUE TITLE
Integration tests require image-preview to be compiled to run?

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#81822]
We had to comment out this test -- https://github.com/microsoft/vscode/commit/3f21572d6afe7f3a3d746243be599435fd40878f

It appears to fail in the integration tests on the remote machine case -- see discussion in release channel. The test is about opening a `.png` file and there is an error above where the `image-preview` extension could not be activated.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/bb0dbb3b9c8f28e2ccacdcc699f4a198ddd1ca98

**Comment by bpasero** [comment]
I would argue my fix is just a workaround. There is something I am not understanding:
* this test did not fail until recently
* this test does not fail when running against local (only remote)
* I do not understand why the integration test would try to activate an extension from `/Users/vsts/agent/2.155.1/work/1/s/extensions/image-preview/out/extension` ([as you can see from here](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=59149&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0&l=899))

As such I wonder if something is broken with regards to the packaging of the product for this extension. 

@mjbvz any clues?

**Comment by bpasero** [comment]
I just ran `yarn gulp vscode-linux-x64-min` locally and could find `image-preview` is part of the built in extensions. However, the folder structure is that the output is in a `dist` folder not `out`. Maybe that is the trouble?

![image](https://user-images.githubusercontent.com/900690/66045622-65bd5100-e524-11e9-9b68-17087c739c94.png)

**Comment by bpasero** [comment]
I just confirmed that the extension is present on disk (which makes sense, otherwise we would see issues from the build opening images). So I am still puzzled about the error.

**Comment by mjbvz** [comment]
Thanks @bpasero! I cannot explain why this just started failing yesterday.

Based on your analysis, here's an overview of what I think is happening:

1. We create a production VS Code build. This uses webpack to compile all the extensions.

    The `image-preview` extension's compiled output goes into `dist`. As part of this, we should also update the `package.json` to point to `dist`: https://github.com/microsoft/vscode/blob/2278f87c1c43f1738b03c62de5e86e5bace89a8d/build/lib/extensions.ts#L98

1. In local integration tests, we either:

     - Build all required extensions normally (not using webpack) and then use them for testing. This would work because building without webpack would generate an `out` directory
    - Run the tests against the production build of vscode that has the correctly patched `package.json` that points to `dist`.

1. In the remote integration tests, we somehow end up running against a production build of the vscode extensions (that have been webpacked) but using the unpacted `package.json` that still points to `out`

/cc @Tyriar  I think you worked on the remote integration tests. Do you have any insights on how it is loading our builtin extensions?

**Comment by Tyriar** [comment]
> In the remote integration tests, we somehow end up running against a production build of the vscode extensions

@bpasero sounds like this could be related to running against the prod server via `VSCODE_REMOTE_SERVER_PATH`? (https://github.com/microsoft/vscode/issues/80308 being the follow up for smoke tests)

**Comment by bpasero** [comment]
I fully understand now. For remote tests I have to point to a different extensions dir because we need the test resolver extension to be present that is normally not shipped. That is unfortunate, but I have pushed a change to compile ALL extensions before running remote tests.
