### ISSUE TITLE
Regex group replacement fails

### ISSUE THREAD

**Issue by saschanaz** [microsoft/vscode#81825]
- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use `^\[((?:(?!Exposed).)*)\ninterface (?!mixin)` and `[Exposed=Window, $1\ninterface ` on the search pane for batch text conversion
2. See the preview, the $1 is not being replaced with the relevant group match.

![image](https://user-images.githubusercontent.com/3396686/66029969-4c73cf00-e53b-11e9-8fae-c1f1ed008296.png)

The same just works with in-file text replacement (Control+H).

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I think this is fixed in Insiders already, please try: 
https://code.visualstudio.com/insiders
