### ISSUE TITLE
Productize or drop workbench.dialogs.customEnabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81820]
Currently it shows as unknown setting.

If this is officially supported, please also provide a good implementation for the about dialog when running desktop. When I added `IDialogService#about()` I was not aware the browser based dialog service was ever used from desktop (from https://github.com/microsoft/vscode/issues/81763)

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/commit/6781d16f05b2e93549675ec79a4ab2917c85faaa
