### ISSUE TITLE
support mime-type when showing source from non-files in editor

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8182]
If a debug adapter returns source from the sourceRequest, the debug UI only recognises the correct (language) type if the name attribute of the source has a proper file extension.
For this reason some debug adapters have to add an extension to the name artificially.

This feature request asks for a more direct mechanism based on a new 'mimeType' attribute on the Source object. If available the debug UI should configure the editor for this mime-type.

**Comment by isidorn** [comment]
This should be possible -> will investigate in debt week thus assigning to July

**Comment by isidorn** [comment]
I have looked into this and it is possible to support this.
E.g passing 'text/x-c' as a mime type will show the source with the languge mode c set.

Assigning to @weinand to add `mimeType` to the protocl and once added I can look into supporting this on the vscode side

**Comment by weinand** [comment]
@isidorn I've added an `mimeType`attribute to the `SourceResponse` and node-debug returns `text/javascript` for source content without extension, e.g. 'eval' content.

**Comment by weinand** [comment]
@felixfbecker you might interested in this.

**Comment by felixfbecker** [comment]
Wouldn't it be easier to use the VS Code language ID?
Another problem I have is that if you run code like `eval("throw new Exception();")` in PHP, my debugger will break inside it and report the eval code `throw new Exception();` via a source request. However, VS Code will not syntax highlight this. I have to add an extra line
```php
<?php
throw new Exception();
```
to the source to get syntax highlighting. That of course means I have to add an offset of 1 to every break and subtract 1 from every breakpoint, but only for source requests. Do you have a better solution for this?

**Comment by weinand** [comment]
@felixfbecker I've CCed you because I saw your code that adds the `<?php`. Instead of doing that you could just return the mime type in the SourceRequest response:

```ts
response.body = { content: source, mimeType: 'application/x-php' };
```

We are not using the language ID because that is a VS Code concept. A mime type is universal. If a debug adapter is run in a different context, it is easier to return a mime type than to return the correct language id.

**Comment by felixfbecker** [comment]
@weinand Sure I could return the mime type instead of returning `eval.php` as the file name. But I will still have to add `<?php`, because otherwise VS Code will use HTML syntax highlighting

**Comment by weinand** [comment]
@felixfbecker I see.
A custom mime type could help here: the type would be associated with a 'php2' language id that is associated with a grammar for raw php (not embedded in html).
