### ISSUE TITLE
output window

### ISSUE THREAD

**Issue by Flava177** [microsoft/vscode#81837]
Issue Type: <b>Bug</b>

The output window keeps popping up randomly and fills alomsot my display screen.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
laravel-extra-intellisense|ami|0.2.3
laravel-blade-spacer|aus|1.0.3
laravel-docs|aus|1.4.1
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.2
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.13.0
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
bootstrap-4-cdn-snippet|eve|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
code-beautifier|mic|2.3.3
theme-monokai-pro-vscode|mon|1.1.14
mssql|ms-|1.6.0
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
material-icon-theme|PKi|3.9.0
laravel-helpers|raf|0.2.2
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.26
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

(5 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Does it happen when you close all windows and launch via `code --disable-extensions`?

**Comment by loopy3025** [comment]
I have the same behavior on my machine. Even when I close the Output window, and am on Terminal. the Output window opens up and starts showing results.

**Comment by Tyriar** [comment]
@loopy3025 same question to you then. This is very likely an extension you have installed.

**Comment by loopy3025** [comment]
@Tyriar  Ya, I'll do that. I just need to wait for a build to finish first. I'd also like to be able to report which extensions I'm running. The instructions for creating a new issue do not include that step. How would I go about doing that?

**Comment by loopy3025** [comment]
Looks like the ones we have in common are the php ones.

**Comment by Flava177** [comment]
@Tyriar : actually it happens when i jux launch vscode . the output window randomly starts running and even after i close it, it reopens after awhile

**Comment by Tyriar** [comment]
Which output channel is opening will probably give you the answer.
