### ISSUE TITLE
Reopen With on the Welcome Page causes an error toast

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81831]
Testing https://github.com/microsoft/vscode/issues/81698

Unable to open 'vs_code_welcome_page': No file system provider found for walkThrough:/c%3A/Users/alros/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D.

**Comment by alexr00** [comment]
Same goes for the settings editor.

**Comment by mjbvz** [comment]
Interesting. 

In addition to fixing this case, we should only show the `reopen with` command if there is at least one custom editor available. Marking for October
