### ISSUE TITLE
What should happen when a new file is saved with a filename pattern that should open in a webview editor?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81832]
Testing https://github.com/microsoft/vscode/issues/81698

Scenario:
Have a webview editor extension installed that contributes for *.txt.
Create a new file. Enter something in it so it isn't empty.
Save it as something.txt
What should happen next?

Currently, nothing happens. It stays in the default VS Code editor. It might make sense to have the choose editor quick pick open.

**Comment by mjbvz** [comment]
Fixing this was more challenging than expected, pushing to November

**Comment by connor4312** [comment]
It looks like renaming works and opens in the custom editor per my preferences, but if I save an untitled file as in the issue, nothing happens. [Recording](https://memes.peet.io/img/20-04-83a49d76-5cda-48ae-a49f-637ea6ba2871.webm)

**Comment by mjbvz** [comment]
Marking for April 

@bpasero Custom editors use `overrideOpenEditor` to open a custom editor in place of the default editor. When a untitled editor is saved, `EditorService.replaceEditors` is called but this goes directly to `EditorGroupView.doOpenEditor` which bypasses the `overrideOpenEditor`. 

Let me know if there's some other event we can listen to to detect when an untitled editor is saved. I couldn't find anything while debugging through the code

**Comment by bpasero** [comment]
I guess this needs to be wired in, PR welcome.

**Comment by mjbvz** [comment]
@rebornix I believe this will also apply to notebooks. I'll let you know what I come up with

**Comment by mjbvz** [comment]
@lramos15 Assigning you since this seems like something we should think about for all editor types, including notebooks

**Comment by lramos15** [comment]
I discussed this issue a bit with Kai and it doesn't sound like we will be fixing this any time soon. The main drive is for notebooks where you see "Hey this is a *.ipnyb file, install the jupyter extension" and then the user clicks install but there ipnyb is still plain JSON. The goal for that is to allow rendering of those files without execution if no extension is installed. For the other cases it's not nearly as important as most files have a usable text editor type. We want to reduce the number of notifications as much as possible and switching the file for the user could be extremely jarring.

**Comment by bpasero** [comment]
Since I just came across the relevant code, we have a way to replace an editor when it is saved (to a different path or when saving untitled):

https://github.com/microsoft/vscode/blob/6b9d5150dc004dd96d52ec12ba73f766bd391a6c/src/vs/workbench/services/editor/browser/editorService.ts#L926-L927

This code does not go through any override but rather takes the typed editor input as it was returned from the `IEditorInput#saveAs` implementation. If we were to change that logic, we probably would have to ask `saveAs` method to return an untyped input without override, or at least make sure the text based editors don't set the override.

**Comment by bpasero** [comment]
Yup agreed, didn't mean to ask to solve this now, just wanted to keep track of the location in code where this is currently decided 👍

**Comment by lramos15** [comment]
To verify:
1. Create an untitled file
2. Save it as `something.ipynb`
3. A jupyter notebook should be created
4. Change your `workbench.editorAssociations` setting to have the entry `"*.ipynb": "default",`
5. Repeat steps 1 and 2 with a different file name
6. It shouldn't switch to a notebook, it should stay as a text

**Comment by bpasero** [comment]
I tried above steps with the GitHub issue notebook extension instead and when I come to step 5. and save an untitled editor as "other.github-issues", that editor actually closes.
