### ISSUE TITLE
Resolving absolute import path

### ISSUE THREAD

**Issue by vuhrmeister** [Microsoft/vscode#8183]
- VSCode Version: 1.2.1
- OS Version: OSX

Only relative import paths are resolved. So jumping to the file that's imported works only with relative paths.

```javascript
// resolves
import '../some-file.js';
// does not resolve
import '/modules/some-file.js';
```

Where `/` is the very root of the project. 

Also it would be nice if automatically resolving index files would work:

```javascript
// imports '../some-module/index.js'
import '../some-module';
```

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9386
