### ISSUE TITLE
[json] indicate that draft-03 schemas are not supported

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#81830]
No duplicate issue exists

- VSCode Version: 1.38.1
- OS Version: MacOS 10.13.6

Steps to Reproduce:

Open a new document.
Set language mode to JSON.
Provide the following content...

```
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "type":"array",
  "items": {}
}
```

`items` is incorrectly highlighted as invalid because it's an object.
This is incorrect, but is likely because the meta-schema is being parsed not as a draft-3 schema.

In draft-3, `type` would accept schemas as well as primitive types as strings.
This was removed in draft-4.

Given that it's not expected many people use draft-3, it may be preferable to not support draft-3 at all, and in stead indicate that draft-3 is not supported.

This case can be identified when loading a schema for a JSON document, and detecting that both `$schema` and `id` (not `$id` for draft-3) are `"http://json-schema.org/draft-03/schema#"`

Does this issue occur when all extensions are disabled?: Yes

FYI: I'm one of the core team on the JSON Schema spec itself.

**Comment by Relequestual** [comment]
None of the above are duplicates.

**Comment by aeschli** [comment]
Thanks for the info. Yes, we should ignore draft-3 schemas and tell the user. I'm not aware of any user request to support draft-3 schemas.

**Comment by Relequestual** [comment]
Welcome. Yeah, I'm by no means suggesting that you support draft-3! We'd probably prefer it if you didn't even!

In an ideal world, it would be great if anything pre 5 could be flagged as depreciated, but I know so many people still need to use 4 because of tooling... ugh.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-json-languageservice/commit/0c11cb056da893e4b823572fffddf9bc9f25c958

**Comment by Relequestual** [comment]
Super. Thanks.
Might I suggest a similar fix for noting that the now released draft-8 is not supported?
Note, that this new release of JSON Schema is "draft `2019-09`".

`$schema` value `https://json-schema.org/draft/2019-09/schema`

Happy to file a new issue or discuss more if required.

**Comment by aeschli** [comment]
added https://github.com/microsoft/vscode-json-languageservice/commit/fa210f6d60f65364dc131a80cc8c6f69a1a543d3

**Comment by Relequestual** [comment]
Thanks for the speedy fix.
The official name for the draft is "draft 2010-09" now.
We do not want to be calling it `draft-08`. The reasons are long and boring.
I've made a PR to reflect this.
