### ISSUE TITLE
Use settings for trusted domains

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#81841]
Testing https://github.com/microsoft/vscode/issues/80595

We should not invent a new story for managing the trusted domains, but use the settings.

- That way the setting will be part of (future) settings sync.
- defaults come from the settings defaults
- make it a map `{ [ domain:string]: boolean; } | false` so you can fine-tune the defaults (and e.g. remove a default entry like localhost) (consistent with other settings like watcher/searc filters)

- make the setting available in user settings only
- disallow that extension make changes to the settings, if that is a concern.
(But note that extensions can cause worse things to your machine than hiding a 'Do you want to open an external website...' dialog)

**Comment by octref** [comment]
> disallow that extension make changes to the settings

That isn't doable now. I did the QuickPick last month and the virtual setting file this month because if it's in settings extensions can write anything to it.

**Comment by JacksonKearl** [comment]
> disallow that extension make changes to the settings

Doesn't seem like this is possible looking at the registry... 

```ts
export interface IConfigurationNode {
	id?: string;
	order?: number;
	type?: string | string[];
	title?: string;
	description?: string;
	properties?: { [path: string]: IConfigurationPropertySchema; };
	allOf?: IConfigurationNode[];
	scope?: ConfigurationScope;
	extensionInfo?: IConfigurationExtensionInfo;
}
```

do you know of a way to do it?

**Comment by JacksonKearl** [comment]
Spoke with Kai and decided to not go this route.
