### ISSUE TITLE
Problem in task: /usr/bin/ld: cannot open output file  ${file}: No such file or directory

### ISSUE THREAD

**Issue by yannl35133** [microsoft/vscode#81844]
- VSCode Version: 1.38.1
- OS Version: Linux Ubuntu 16.04.6 LTS

Steps to Reproduce:

1. tasks.json : 
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Assembly build",
            "type": "shell",
            "linux": {
                "command": "gcc",
                "args": [
                    "-g",
                    "-no-pie",
                    "-o ${fileDirname}/${fileBasenameNoExtension}",
                    "${file}"
                ],
            },
        }
    ]
}
```
2. Try to run this task on a assembly .s file
3. It works well on VSCode's command line

Does this issue occur when all extensions are disabled?: Yes

NB: Don't know how to keep newlines in a code block in Markdown

**Comment by alexr00** [comment]
What is the command line you're using when running from VS Code's integrated terminal?

**Comment by yannl35133** [comment]
bash I suppose, I am not very familiar with Linux yet. The default setting, in any case.

**Comment by alexr00** [comment]
Sorry, I mean you say:

> It works well on VSCode's command line

What is the command you run for that?

**Comment by yannl35133** [comment]
In the integrated terminal, again with default setup, the command `gcc -g [...] ${file} ` works.

**Comment by alexr00** [comment]
What is the whole command though?

**Comment by yannl35133** [comment]
Sorry for this, although I did not recheck, this was probably a problem with my understanding of bash and '/".
