### ISSUE TITLE
Trusted domain editor: Looks like text file, but isn't

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#81843]
Testing #80595

- invoke `Manage Trusted Domains`
- any changes to the file are lost, only the values are kept. e.g. my formatting, commented out domains.

**Comment by octref** [comment]
To verifiers:

Verify that:
- Manage Trusted Domains setting should preserve your commented out parts
- When you have removed the header or end, for example by deleting the first line `// Links matching one or more entries in the list below can be opened without link protection.` or last line `// Save this file to apply the trusted domains rules.`, the next time you run `Manage Trusted Domains` it'll be restored.
