### ISSUE TITLE
Markdown preview broken

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#81847]
Issue Type: <b>Bug</b>

1) Open a `.md` file in your workspace.
2) <kbd>Cmd+k</kbd><kbd>v</kbd> 
-> preview opens but is empty

The following messages are in the dev tools console:
```
16:47:41.341 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/media/pre.js
16:47:41.343 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/media/markdown.css
16:47:41.343 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/markdown-language-features/media/highlight.css
16:47:41.343 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/.vscode-insiders/extensions/bierner.markdown-checkbox-0.1.3/checkboxes.css
16:47:41.344 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/.vscode-insiders/extensions/bierner.markdown-preview-github-styles-0.1.6/base.css
16:47:41.344 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/.vscode-insiders/extensions/bierner.markdown-preview-github-styles-0.1.6/github-markdown.css
16:47:41.344 service-worker.js:135 Could not resolve unknown resource ///Users/kmaetzel/.vscode-insiders/extensions/bierner.markdown-preview-github-styles-0.1.6/node_modules/highlight.js/styles/github.css
```

VS Code version: Code - Insiders 1.39.0-insider (695ee74864ef93d10f5de0861cb66af190e76211, 2019-10-02T08:57:07.116Z)
OS version: Darwin x64 18.6.0

<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
solargraph|cas|0.21.1
vscode-svgviewer|css|2.0.0
gitlens|eam|10.0.1
vsc-material-theme|Equ|30.0.0
vscode-pull-request-github-insiders|Git|2019.9.38342
crazy|kie|0.0.2
svgpreview|kis|0.2.0
rainbow-csv|mec|1.3.1
theme-monokai-pro-vscode|mon|1.1.14
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-containers|ms-|0.79.0
remote-ssh-edit-nightly|ms-|2019.10.1265
remote-ssh-nightly|ms-|2019.10.1265
remote-wsl|ms-|0.39.8
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
Go|ms-|0.11.7
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
material-icon-theme|PKi|3.9.0
ruby|reb|0.25.3
vscode-xml|red|0.9.0
bash-debug|rog|0.3.6
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This should only happen if you are using iframed based webviews which I haven't tested recently on desktop. Make sure you don't have `webview.experimental.useExternalEndpoint` set for now

**Comment by kieferrm** [comment]
I was running with the external endpoint enabled.

**Comment by Tyriar** [comment]
@mjbvz that setting doesn't exist anymore and I can open markdown preview fine. I also notice there are no iframes on the page, not sure how to verify?

**Comment by mjbvz** [comment]
The setting is undocumented but still has an effect. Make sure to restart vscode after setting it
