### ISSUE TITLE
Error when trying to open links in markdown preview

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81849]
Verifying https://github.com/microsoft/vscode/issues/26659

I opened the vscode-docs repo. I started with the markdown preview of identifiers.md. 
When I click on the link to "language mode" in the second line of text, I get:

> Unable to open 'overview.md': Unable to read file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\file\d:\repos\Microsoft\vscode-docs\docs\languages\overview.md').

This happens for every local link in markdown previews. I didn't set any markdown preview settings.

**Comment by tedhudek** [comment]
The link described above is `[language mode](/docs/languages/overview.md#changing-the-language-for-the-selected-file)`. I'm on Windows and this works in .md preview `[test](test.md#hello-world)`.  So maybe it's the absolute path?
