### ISSUE TITLE
Add global commands to move an editor one group to the left or right

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8185]
Moving editors across groups. Should work in the same way as when using DND and possibly share the same code by pushing it into `IEditorGroupService.moveEditor()` even when the target group does not exist.

**Comment by vogler** [comment]
`Cmd+Ctrl+Left/Right` is fine, but `Shift+Cmd+1/2/3` doesn't seem to be taken (`Cmd+1/2/3` focuses group).
Faster and easier to remember IMO.

**Comment by bpasero** [comment]
Phew, not sure. I think both key bindings are muscle memory to keep...

**Comment by Tyriar** [comment]
ctrl+alt+left/right is no good on Ubuntu since it's an OS-level keybinding. There aren't many options at this point though and this is a pretty niche command imo.

Created minor bug https://github.com/Microsoft/vscode/issues/9873 during verification

**Comment by adrianoresende** [comment]
`If the right group does not exist, it should be created (similar to split action).`
+1 This is excelent idea, i need this.

**Comment by inkhsutesou** [comment]
I'm just here to write that I really want this feature, and the bindings don't matter as much because I'm just going to change it to ctrl + alt || shift + left || right ( windows )

**Comment by ecbrodie** [comment]
This is an action that I use frequently in the Jetbrains IDEs that I use frequently (IntelliJ, RubyMine). I would bind the action `Main menu --> Window --> Editor Tabs --> Move Right` to `shift-cmd-m`, which would take the current window I'm working on and move it to a new split on the right, without duplicating it in my current split.

Overall, we should be support both splitting with and without duplication. There are valid use cases for both behaviour, as well as enough people having a strong preference of either. This sentiment of mine is a bit of a reaction to the conversation from #8888.

**Comment by mix3d** [comment]
This is the behavior I WANT the split action to do. Duplication is weird to me.

 Since I haven't seen much interest in both behaviors simultaneously, could you have a config flag that controls duplication on the split command, defaulting to duplicating? This way you don't have an extra keybind to worry about either.
