### ISSUE TITLE
Files: decoration for deleted file no longer applied

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81852]
Steps to Reproduce:

1. open a file
2. delete it outside vscode

=> 🐛 you do not see a "(deleted)" decoration in the tab label

Likely a regression from the work to memoize the labels.

**Comment by isidorn** [comment]
Good catch. 
Unfortunetly the memoizer is static so this way when the label changes I have to drop cash for all instances. But I think that is fine. If you have a better idea let me know.

**Comment by bpasero** [comment]
@isidorn thats fine, thanks for prompt fix
