### ISSUE TITLE
Should call hierarchy arrows be chevrons like breadcrumbs?

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81859]
Testing #81658

It feels like the `foo → bar` title should follow the breadcrumbs `foo > bar` pattern to be consistent:

**Call hierarchy**
<img width="705" alt="image" src="https://user-images.githubusercontent.com/35271042/66065800-10217e00-e4fd-11e9-9ac2-01dd775c9bc5.png">

**Breadcrumbs**
<img width="488" alt="image" src="https://user-images.githubusercontent.com/35271042/66065913-4b23b180-e4fd-11e9-9bc0-cfc8eb79409d.png">

Peek widget probably doesn't support this but it's something worth thinking about for consistency.

**Comment by jrieken** [comment]
Actually, closing this in favour of https://github.com/microsoft/vscode/issues/71191. I will remove the pseudo breadcrumbs from the title and we should have an indication the tree nodes instead
