### ISSUE TITLE
Add action to expand/collapse all nodes in call hierarchy

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#81857]
Testing #81658

As I'm drilling through the nodes, it would be handy to have a toggle for expanding/collapsing all nodes, or at least the ones I'm active on to save several clicks. The screenshot below took me 7 clicks.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/35271042/66065384-1b27de80-e4fc-11e9-900b-2fa908d13f15.png">

**Comment by jrieken** [comment]
Hm, that's hard because each time a node is expanded we need to check with the language service what calls/callers are used. Additionally, there can be loop: 'foo' calls 'bar' calls 'foo'.  Technically, this is similar to the explorer and I don't believe we have smart magic there.

**Comment by jrieken** [comment]
closing because expand all isn't possible. collapse all should be available as standard tree command
