### ISSUE TITLE
Source control add message not responding

### ISSUE THREAD

**Issue by calumryan** [microsoft/vscode#81850]
Issue Type: <b>Performance Issue</b>

Numerous occasions when saving a new commit message by clicking on the tick symbol VSCode does not respond or hangs. Have to restart VSCode to get round this.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    90	 21908	code main
    0	   139	 21910	   gpu-process
    0	   205	 21912	   window (Extension: Bracket Pair Colorizer — hd-prototype-kit)
    0	     0	 22277	     /bin/bash -l
    0	    98	 22280	     extensionHost
    0	    49	 22284	       electron_node server.js 
    0	    49	 22281	     watcherService
    0	    41	 22286	     searchService
    0	    98	 22292	   shared-process
    0	     0	 25239	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 22681	   window (undefined)
    0	    74	 24878	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Bracket Pair Colorizer — hd-prototype-kit)
|    Folder (hd-prototype-kit): 1666 files
|      File types: html(564) scss(271) twig(202) js(136) woff2(48) woff(48)
|                  ttf(40) eot(40) json(37) svg(35)
|      Conf files: gulp.js(1) package.json(1);
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ACF-Snippet|ant|1.9.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.30.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
php-debug|fel|1.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
pug2html|gin|0.0.5
search-node-modules|jas|1.3.0
twig-language|mbl|0.8.10
twig-language-2|mbl|0.8.10
code-beautifier|mic|2.3.3
vscode-html-format|moh|0.0.3
vuejs-extension-pack|mub|1.1.5
vetur|oct|0.22.4
format-html-in-php|rif|1.6.1
vscode-essentials-snippets|rob|2.0.0
sass-indented|rob|1.5.1
vscode-scss-formatter|sib|1.4.2
code-spell-checker|str|1.7.18
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
tachyons-snippets|tho|0.0.3
vscode-status-bar-format-toggle|tom|1.5.0
refactor-css|urb|0.4.2
twig|wha|1.0.2
vscode-import-cost|wix|2.12.0
wordpress-toolbox|wor|1.3.5
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you reproduce this with `code --disable-extensions`?
