### ISSUE TITLE
New setting debug.onTaskErrors values are missing descriptions

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#81868]
debug.onTaskErrors has values: "debugAnyway", "prompt", and "showErrors".

There are no descriptions for the three possible values so nothing is displayed in the Settings editor enum dropdown nor IntelliSense in the JSON editor.

**Comment by isidorn** [comment]
@gregvanl Great catch. Adding bug label so we verify this.

**Comment by misolori** [comment]
Verified that the description shows up, but should the description be unique to each value? That's how our other settings work.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/35271042/66154960-82649200-e5d3-11e9-9c12-3e98a5235bfc.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/35271042/66154975-885a7300-e5d3-11e9-8cd2-8564e7005067.png">

**Comment by misolori** [comment]
Actually, re-opening as it appears the commit has a description for each value but only one is ever shown:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/35271042/66155133-d66f7680-e5d3-11e9-8be1-64d356821fdc.png">

<img width="696" alt="image" src="https://user-images.githubusercontent.com/35271042/66155129-d4a5b300-e5d3-11e9-8b3b-f5a56225cdac.png">

**Comment by isidorn** [comment]
@misolori the description is only shown in the Settings UX. Please verify it there :)
The inteli-sense always shows the description of the whole setting, not of the value.

**Comment by misolori** [comment]
@isidorn never mind, I'm an idiot and didn't realize this isn't on Insiders yet. Verified out of master that this is fixed in both:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/35271042/66159256-78935c80-e5dc-11e9-96d3-e354c7c17f44.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/35271042/66159275-8517b500-e5dc-11e9-95b6-d602930f846c.png">

**Comment by isidorn** [comment]
Oh I was not aware that we even show it in settings json - sweet.
