### ISSUE TITLE
Two launch configurations with the same preLaunchTask trigger "already running" warning

### ISSUE THREAD

**Issue by nevir** [microsoft/vscode#81860]
- VSCode Version: 1.38.1
- OS Version: OS X 10.14.6

Steps to Reproduce:

With the following .vscode/launch.json:
```json
{
  "version": "0.2.0",
  "compounds": [
    {
      "name": "all",
      "configurations": ["web-server", "web-ui"]
    }
  ],
  "configurations": [
    {
      "name": "web-server",
      "type": "node",
      "request": "attach",
      "port": 20006,
      "restart": true,
      "preLaunchTask": "npm: dev-web"
    },
    {
      "name": "web-ui",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:20005/",
      "timeout": 20000,
      "webRoot": "${workspaceFolder}/web",
      "preLaunchTask": "npm: dev-web"
    }
  ]
}
```

Launching the "all" configuration works properly, but presents the following:

![image](https://user-images.githubusercontent.com/41373/66068681-e66b5580-e502-11e9-8b90-531f18cb47c7.png)

**Comment by alexr00** [comment]
@isidorn a task is considered active after we fire the task active event. It looks like the launch configurations are not waiting for this and are just firing off the launch configurations in parallel. I'm not sure there's a good solution from the tasks side.

**Comment by isidorn** [comment]
Yes, debug is just launching debug configurations in parallel which just run preLaunchTasks in parallel.
It is very rare that both configuratinos depend on the same task.
The only way to work around this would be if the taskService exposes a flag to suppress this warning and debug would pass true to this flag.
However I think this is pretty minor and I think we can ignore for now
@alexr00 leaving up to you to decide what to do here
