### ISSUE TITLE
"Format on paste" repeatedly re-enables

### ISSUE THREAD

**Issue by vcarl** [microsoft/vscode#81862]
- VSCode Version: 1.38.1 (but also many past versions as well)
- OS Version: MacOS 10.14.6

Steps to Reproduce:

Unclear what triggers this. As often as twice a week, I'll paste something and the formatting adjusts, and I'll go into settings to find the `Editor: Format On Paste` setting to be enabled. I've been having this problem for months, I [tweeted](https://twitter.com/vcarl_/status/1095805177678962690) several occurrences. 

Does this issue occur when all extensions are disabled?: Yes/No

Unclear, because it takes several days to recur and I'm not sure how to trigger it.

**Comment by Tyriar** [comment]
Sounds like an extension might be doing it? Does it repro when you close all windows and relaunch with `code --disable-extensions`?

**Comment by vcarl** [comment]
I can't repro other than working as usual for a few days, so disabling all my extensions would be pretty disruptive. I don't have anything crazy though, only have prettier + a "toggle format" extension. I'll try disabling formatting extensions and see if it still recurs.

**Comment by Tyriar** [comment]
Prettier and format toggle seem like prime candidates for changing the setting, it is extremely unlikely that the core of VS Code would be changing a setting like this (or we would be getting a lot more reports) so I suggest you find out which extension is the problem and disable/reach out to them.

**Comment by vcarl** [comment]
Ah, it does appear to be from the formatting toggle, I've opened an issue there to try and save others some pain. Sorry for the goose chase!

**Comment by Tyriar** [comment]
np, glad you figured it out 👍
