### ISSUE TITLE
Add Task functionality to run extension code prior to executing ShellExecution or ProcessExecution.

### ISSUE THREAD

**Issue by Friday32** [microsoft/vscode#81863]
I have a TaskProvider in my extension that generates a couple build tasks.   I'd like to present a quickpick to select a component to build;  The selection will determine the shell command used.  If there is a way to do this, it's not obvious to me.  

I noticed a proposed API that includes a new execution type,  CustomExecution. Perhaps, that will solve my issue in a future releae. But, I'm hoping there is something I can do with the current version of VSCode.

**Comment by alexr00** [comment]
https://code.visualstudio.com/Docs/editor/tasks
Otherwise you can follow the issue for finalizing CustomExecution: https://github.com/microsoft/vscode/issues/80375
