### ISSUE TITLE
Disabling/Re-enabling image preview extension steals focus

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#81864]
Testing https://github.com/microsoft/vscode/issues/81674

Steps to reproduce:
* Open an image
* Open image preview extension page, disable and reload
* The image view tab has a loading indicator
* Switch to the extension page to enable it, but nothing is clickable
* Go back to the image tab and revisit the extension page fixes the issue

**Comment by mjbvz** [comment]
Closing as we have not see other reports since this issue was opened
