### ISSUE TITLE
Git smoke tests are broken

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81871]
See comments at https://github.com/microsoft/vscode/commit/615e262789c3f1872758c119a095254fa5316ad7, tested on mac

**Comment by joaomoreno** [comment]
@Tyriar We should just adapt the tests to use the tree.

When I run them, I see the explorer popping up after we unstage the change... that's what's causing the problem. Now... where does that come from?

**Comment by joaomoreno** [comment]
They come from attempting to get the X Y coordinates of a `display: none` element, which ends up returning 0, 0. Another reason to drop DOM elements and pixels and just go for a widget object model.
