### ISSUE TITLE
Image preview should zoom into center of image

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81876]
**Repo**
1. Open an image
1. Start zooming in to the image (both using pinch to zoom and using click)

**Bug**
The zoom goes towards the top left corner of the image. It should go towards the center

**Comment by mjbvz** [comment]
Here's the relevant code:

https://github.com/microsoft/vscode/blob/04d0cf6ad6ce2c18afc651e7ba13c97827ae3d6f/extensions/image-preview/media/main.js#L164

Let me know if you are interested in fixing this and have any questions about the code

**Comment by jeanp413** [comment]
I'll take this
