### ISSUE TITLE
Unable to select content of last folded section if file ends with a folded section

### ISSUE THREAD

**Issue by michaelt42** [microsoft/vscode#81870]
Issue Type: <b>Bug</b>

1. Create a new file
![image](https://user-images.githubusercontent.com/10199486/66083026-4fad9180-e520-11e9-8e96-63b4e5ef9665.png)
2. Collapse the last folding section so the file ends with a collapsed section
![image](https://user-images.githubusercontent.com/10199486/66083223-b59a1900-e520-11e9-8a42-d24ae6066310.png)
3. Select all, cut, paste

Expected result, original text
Actual result, content of last folded section missing
![image](https://user-images.githubusercontent.com/10199486/66083276-ca76ac80-e520-11e9-949c-e90554888aa9.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (27.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|0.8.1
duffle-vscode|ms-|0.3.0
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
powershell|ms-|2019.9.0
vscode-yaml|red|0.5.3

</details>

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/41744
