### ISSUE TITLE
Control + Tilde does not open Terminal

### ISSUE THREAD

**Issue by pauelm** [microsoft/vscode#81875]
Despite CNTRL+' being the advertised, default hotkeys for opening the Terminal window, this functionality no longer appears to be functioning properly.

Steps:

Open a .py file in your project workspace.
Press CNTRL + '.

Actual Results:
Nothing happens, yet the Terminal window can be opened manually without any issue.

Expected Results:
Terminal window should immediately open and have focus.

Environment:
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Running:
Python Version 3.7.4
Windows 10 Pro
(Running on Windows 10 Pro)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.21
docs-preview|doc|0.3.32
docs-yaml|doc|0.2.4
docker-explorer|for|0.1.6
vscode-test-explorer|hbe|2.14.6
rest-client|hum|0.22.2
vscode-peacock|joh|3.1.5
chat|kar|0.22.1
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-docker|ms-|0.8.1
mssql|ms-|1.6.0
python|ms-|2019.9.34911
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
sublime-keybindings|ms-|4.0.3
vscode-node-azure-pack|ms-|0.0.9
vsliveshare|ms-|1.0.905
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
azurerm-vscode-tools|msa|0.7.0
tabnine-vscode|Tab|2.1.11
ayu|tea|0.18.0
vscodeintellicode|Vis|1.1.9
azure-iot-toolkit|vsc|2.10.0
vscode-icons|vsc|9.4.0
WebTemplateStudio-dev-nightly|WAS|0.0.1925201

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
What keyboard layout are you using?

**Comment by pauelm** [comment]
English (US)

**Comment by Tyriar** [comment]
Are you using tilde or single quote as you say both in your report.

Also if you enter keybindings (ctrl+k, ctrl+s) it should tell you what the right key is.

**Comment by pauelm** [comment]
It turned out it is was a problem between the keyboard and the chair.  I had been switching between desktop machine with its keyboard, and the laptop.  The tilde on my specific laptop keyboard is located in a completely different location, and it was throwing me off after using hotkey sequences many times on a more standardized keyboard, when using my desktop.

Also, ctrl+s works correctly as saving a file (as well as ctrl+shft-s as "Save As").

This issue can be closed.
