### ISSUE TITLE
Highlighting in tsx seems broken

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vscode#8188]
- VSCode Version: Code - Insiders 1.3.0-insider (41f53d27a8cb477130f84116c78f43ddacbaf24b, 2016-06-27T05:07:29.758Z)
- OS Version: Windows_NT ia32 10.0.10586

It seems to break on the <T,T> parts

Steps to Reproduce:

1. Create a tsx file with at least one class that extends React.Component 
2. See!

``` tsx
import * as React from 'react';

class Test extends React.Component<{},{}> {
    public constructor() {
        super();
        console.log('created');
    }
}

class OtherTest extends React.Component<{},{}> {
    public constructor(){
        super();
        console.log('created');
    }
}
``` 

![image](https://cloud.githubusercontent.com/assets/383634/16380484/a0fbbb3e-3c77-11e6-96fa-6e28587891d5.png)

**Comment by boxstart** [comment]
This seems to be related to commit 88f88a90938243434488ed72a81498651782607b, where the processing of angle brackets has been changed.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#196
