### ISSUE TITLE
Image zoom status bar reports wrong zoom level

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#81889]
Related to https://github.com/microsoft/vscode/issues/81799

1. Open 2 images in VS Code in 2 separate tabs
2. Zoom in on both, with different zoom levels
3. Focus one and then the other (clicking the editor titlebar)

:bug: => As you focus one or the other, one of them will report `Whole Image` in the status bar even though it is zoomed in.

**Comment by mjbvz** [comment]
Good catch!
