### ISSUE TITLE
Specified task cannot be tracked

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#81887]
* clone and open https://github.com/microsoft/vscode-references-view/
* run `npm i`
* press F5 to start
* :bug: you can an error about tasks not being able to be tracked. this used work in the past 

<img width="1070" alt="Screenshot 2019-10-03 at 11 52 00" src="https://user-images.githubusercontent.com/1794099/66117216-6b726f80-e5d4-11e9-90e1-10ad5c3868ed.png">

**Comment by jrieken** [comment]
Yeah, I do have https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher installed. Unsure if that broke/changed?

**Comment by alexr00** [comment]
I never would have expected that to work. You had a non-watching problem matcher(`$ts-webpack`) on a watching task(`"isBackground":"true"`). To have it work I'd expect you to need to use `$ts-webpack-watch`.

**Comment by alexr00** [comment]
I went back to 1.37.1, and it had the same behavior there. If this used to work, it was before then.

**Comment by jrieken** [comment]
idk - unsure if it worked but it surely never prompted me. the config is roughly 8 months old, the extension a year so I don't think anything there has changed. Is there a less aggressive and more informative way of telling me that the problem matcher is wrong? Like, create an error (diagnostic) instead?

**Comment by alexr00** [comment]
For the aggressive message: for debug to proceed past the prelaunch task it needs the task to either exit or for a watching problem matcher to be working. In this case, it can't proceed so an aggressive message makes sense to me.

For a more descriptive error: I can (and should) add a tasks error that says that the problem matcher isn't a watching problem matcher.

**Comment by alexr00** [comment]
To verify you can use an watching task with a non watching problem matcher. For example from the hello world sample:
```
{
            "type": "npm",
            "script": "watch",
            "problemMatcher": "$tsc", // note that this is tsc, not tsc-watch
            "isBackground": true,
            "presentation": {
                "reveal": "never"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
        }
```
