### ISSUE TITLE
[json] JSON formatter does not allow vertical alignment

### ISSUE THREAD

**Issue by madpipeline** [microsoft/vscode#81886]
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.14-200.fc30.x86_64
```
All whitespace formatting is lost:

* vertical value alignment
* value grouping (using an empty line)
* single item lists are expanded to multiple lines

Steps to Reproduce:

1. Write a JSON file and whitespace align values:
```
{
    "foo": {
        "foo1":         "var1",
        "somelongname": "another value",
        
        "anothergroupofvariables":  "separated by an empty line",
        "key":                      "value",
        
        "singlelistitem": [ "oneitem" ]
    }
}
```
2. Format the document using `Ctrl + Shift + I`
```
{
    "foo": {
        "foo1": "var1",
        "somelongname": "another value",
        "anothergroupofvariables": "separated by an empty line",
        "key": "value",
        "singlelistitem": [
            "oneitem"
        ]
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

According to the RFC7159 JSON standard whitespace alignment is allowed: https://www.rfc-editor.org/rfc/pdfrfc/rfc7159.txt.pdf.

I'm reporting this here, since this is affecting the default JSON formatter. Please advise if I should report this elsewhere.

I agree whitespace alignment makes no sense for JSON strings generated and read mainly by machines, but for JSON strings written and maintained by humans, whitespace alignment is essential for good readability and quick object identification.

**Comment by aeschli** [comment]
Thanks for filing. There are currently no plans to implement this feature but I put this as a request on the backlog to see if other users have the same request.

**Comment by aeschli** [comment]
Closing as out of scope. The feature can be provided by an extension.
