### ISSUE TITLE
Do not show message to restart VSCode after uninstall extension

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#8189]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Do not show message to restart VSCode after uninstall extension

**Comment by bpasero** [comment]
@isidorn is this fixed with the new viewlet?

**Comment by isidorn** [comment]
Yes this is fixed with the new viewlet, once an extension is uninstalled we do not show the message to restart vscode

**Comment by Tekbr** [comment]
I think it would be better warn you, if you have problems with the extension. Not least because it continues to function until it is restarted.

Example:

![exem](https://cloud.githubusercontent.com/assets/19866231/16417652/1bab2f9a-3d1d-11e6-9442-43429a88eef6.JPG)

**Comment by isidorn** [comment]
Oh you want the exactly opposite of what I understood from you.
In the meantime we got this issue which captures your concern - #8298 though I like your scatch and will look into it.

**Comment by Tekbr** [comment]
I mean when you install the extension, and for some reason the extension does not work properly (e.g. a conflict or bug). So we need to uninstall and reinstall for the extension to work properly. Currently it seems that the extension has been removed successfully, but it wasn't until the restart the VSCode.

The example image is simple, better than the notification at the top all the time. Thank you.

* Sorry, I speak English so so.

**Comment by isidorn** [comment]
Thanks for the clarification!
