### ISSUE TITLE
color preview bug

### ISSUE THREAD

**Issue by ChanyaKushima** [microsoft/vscode#81892]
Issue Type: <b>Bug</b>

On html or css, the color preview, for example background-color property's color, has a bug.
For example,

~~~css
*{
    background-color: #FFFF00FE;
}
~~~

#FFFF00FE is the color like yellow. But the preview color is black....
Output in web browers is as close as possible 
to yellow.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.30.2
vscodeintellicode|Vis|1.1.9

</details>

**Comment by Tyriar** [comment]
Please update to latest to verify it's not fixed, you're on a very old version.
