### ISSUE TITLE
Integracion de Terminal

### ISSUE THREAD

**Issue by MrRayBen** [microsoft/vscode#81894]
Issue Type: <b>Bug</b>

Cuando ejecuto la terminal integrada de Visual Studio Code se me abre una terminal externa al programa y al ejecutarlo con extenciones como Run code no se puede compilar tanto en C/C++ como en C#.

![image](https://user-images.githubusercontent.com/40451847/66121325-36b6e600-e5dd-11e9-934a-d2d3bdbb3b3d.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.58GB free)|
|Process Argv|G:\Mi unidad\ASIX2\Programació\UF1\Practica\ACT2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
c-cpp-makefile-project|adr|1.1.0
include-autocomplete|ajs|0.0.4
vscode-http-proxy|axe|0.1.3
LinkCheckMD|bla|0.1.5
phpserver|bra|2.4.6
c-cpp-compile-run|dan|0.5.0
c-cpp-project-generator|dan|1.1.1
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
extbundles-csharp|Fel|2.0.0
code-runner|for|0.9.14
html-preview-vscode|geo|0.2.5
cxx-compiler-explorer|har|0.2.0
CppSnippets|har|0.0.14
ftp-simple|hum|0.7.1
vscode-gnu-global|jay|0.3.1
c-cpp-flylint|jbe|1.2.4
csharpextensions|jch|1.3.0
docomment|k--|0.1.8
csharpextensions|kre|1.3.0
ccpp-extension-pack|Leo|0.2.1
csharpfixformat|Leo|0.0.84
csharp-colors|log|0.1.7
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-clang|mit|0.2.3
vscode-http-client|mkl|0.34.0
vscode-html-format|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-language-pack-es|MS-|1.38.4
mssql|ms-|1.6.0
python|ms-|2019.9.34911
cpptools|ms-|0.26.0-insiders
csharp|ms-|1.21.3
epitech-c-cpp-headers|nic|1.13.0
vscode-versionlens|pfl|0.24.0
phpserver|piy|1.0.0
c-cpp-definition-generator|rei|0.0.2
reloaded-cpp|rel|0.1.9
php-live-server|Teo|0.0.1
msbuild-project-tools|tin|0.2.55
cmake-tools|vec|1.1.3
vscode-maven|vsc|0.19.1
html-snippets|wge|0.1.5

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
