### ISSUE TITLE
Renaming a file doesn't update imports and shows "(deleted)"

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81897]
This only happens in current Insiders build v1.39.0

- VSCode Version: 1.39.0 (Insiders)
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Set `"javascript.updateImportsOnFileMove.enabled": "prompt"`
2. Rename a JS file that has an import statement somewhere (prompt will trigger)
3. Rename it back to original name
4. Observe that the prompt does not trigger (and the import statement does not update) and that now you have a "`(deleted)`" in front of your file name in the editor ([screenshot](https://imgur.com/8VZ85Ie)).

Does this issue occur when all extensions are disabled?
Yes

**Comment by SAkhil95** [comment]
Hey @mjbvz @Tyriar ,

I am not seeing the (deleted) in front of my file name but as mentioned by @andrecasal, my imports also are not getting updated after modifying the file name. 

checked with both : 
1. "javascript.updateImportsOnFileMove.enabled": "prompt"
2. "javascript.updateImportsOnFileMove.enabled": "always" **but no luck**

**VS code version details** : 
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

Also, I noticed there's a duplicate of this : <https://github.com/microsoft/vscode/issues/58987>

**Comment by andrecasal** [comment]
The imports not updating part is a duplicate of #58987. The showing "(deleted)" in the file name doesn't seem like it's duplicated. I guess we can narrow this issue down to that. Thanks for the heads up @SAkhil95 👍

**Comment by SAkhil95** [comment]
Hey @andrecasal,

Thanks for the clarification mate. I noticed that the auto import issue which I was talking is now resolved in latest **1.40.1** release.

However.. it is not prompting even if I selected prompt.

I have mentioned in detail, please find it in #58987 thread

**Comment by mjbvz** [comment]
@andrecasal Can you please provide concrete repo steps with a small example project? I can't seem to trigger this

**Comment by andrecasal** [comment]
I'm not able to trigger this problem anymore. It seems to have been fixed in version 1.40.
