### ISSUE TITLE
markdown preview wrongly creates http links on words ending with .py

### ISSUE THREAD

**Issue by JMVOLLE** [microsoft/vscode#81891]
- VSCode Version: 1.38.1
- OS Version:  Windows 10  Entreprise 10.0.16299 build 16299

Steps to Reproduce:

1. Edit a text file with following content:
~~~
- hello.cpp
- hello.py
- hello.json
~~~
2. Open markdown preview
hello.py is displayed as an html link pointing to http://hello.py/

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/16287266/66118292-4bdc4680-e5d6-11e9-8ed9-bdb939e0adf4.png)

**Comment by mjbvz** [comment]
https://en.wikipedia.org/wiki/.py

The preview attempts turn things that look like potential domains into links. You can disable this by setting: `"markdown.preview.linkify": false`
