### ISSUE TITLE
First inline breakpoint on line: too much width

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81898]
![image](https://user-images.githubusercontent.com/1926584/66125640-d11c2700-e5e7-11e9-90c1-5f0344d5d016.png)

by @bpasero

**Comment by isidorn** [comment]
This works fine with latest (I seem to have fixed it in the meantime)
@bpasero let me know if you still see it

![Screenshot 2019-10-18 at 15 37 37](https://user-images.githubusercontent.com/1926584/67098901-43cafc00-f1bd-11e9-9dd8-17d04961e639.png)

**Comment by bpasero** [comment]
@isidorn I see it in web

![image](https://user-images.githubusercontent.com/900690/67107759-564d3180-f1cd-11e9-8ec9-14cd4ba6fc34.png)

**Comment by Tyriar** [comment]
I'm still seeing this as very wonky:

![wonky](https://user-images.githubusercontent.com/2193314/67974494-c9907380-fbcf-11e9-822a-9b6c82e41ee2.gif)

Version: 1.40.0-insider (user setup)
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T05:42:33.138Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
@Tyriar this issue is about the first inline breakpoint on line, that should be fixed, thus closing.
As for the wonkiness I do agree it is a bit wonky, however that is covered by this issue https://github.com/microsoft/vscode/issues/81716
