### ISSUE TITLE
XML color highlight appears to be broken

### ISSUE THREAD

**Issue by regs01** [Microsoft/vscode#819]
Just no highlight at all, if XML is selected. Everything is just maroon.
![2015-11-30 17-04-46 ames lps - visual studio code](https://cloud.githubusercontent.com/assets/10468217/11473673/bde1c344-9784-11e5-83e1-656d2f9cf2b1.png)

**Comment by alexandrudima** [comment]
@regs01 What version of VSCode are you using? I think we have improved this very recently in 0.10.2.

**Comment by aeschli** [comment]
duplicate of #23
