### ISSUE TITLE
Inline breakpoint: combine current step marker and breakpoint?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81900]
I find that this takes a lot of space:

![image](https://user-images.githubusercontent.com/900690/66127347-b2b82a80-e5eb-11e9-98a9-94ffbcf33b09.png)

Why can the breakpoint not somehow indicate that it is the currently stepped thing?

Indicator in Chrome Dev Tools: seems to select the token

![image](https://user-images.githubusercontent.com/900690/66127408-e3985f80-e5eb-11e9-9248-1d65e7272831.png)

//cc @misolori

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/81718
