### ISSUE TITLE
Define named problemMatchers in task.json

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#81901]
It is possible to define 1 global `problemMatcher` in task.json.

It is possible to define multiple **named** `problemMatcher`s in `package.json` (`contributes.problemMatchers`). They are used with 
```
    "problemMatcher": "$abcdef"
```

Request is to add named (global) `problemMatcher` in taks.json.

Will it also allow the `base` attribute?

**Comment by alexr00** [comment]
duplicate of https://github.com/microsoft/vscode/issues/61497
