### ISSUE TITLE
Test theme hint in previewHtml

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8190]
tests #7589

- [x] any os - @weinand 

When previewing html we now indicate the active theme group. Those are `vscode-light`, `vscode-dark`, and `vscode-high-contrast`. Make sure one and only one of them is always set on the document. Switch another theme and make sure it updates

**Comment by weinand** [comment]
tested by previewing a markdown file with this contents:
```html
<script language="JavaScript">
  document.write(document.body.className);
</script>
```
