### ISSUE TITLE
Source Control is showing some unmodified files as changed

### ISSUE THREAD

**Issue by credencie1** [microsoft/vscode#81903]
Sometimes, in Source Control Panel appears one or more files not changed. When Working Tree is opened for these files, there are not differences between them (the file was not modified).

 (Report Issue is not working)
- VSCode Version: 1.36.1
- OS Version: Windows 10 Pro v.1903

Steps to Reproduce:
This is a random event, I already do not know which other event trigger this one.

Does this issue occur when all extensions are disabled?: I do not test that (random event!)

**Comment by Tyriar** [comment]
Please update vscode to latest and verify it's not fixed there.
