### ISSUE TITLE
Psuedoterminal implementations should be able to clear the terminal output.

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#81908]
In our extension that implements a pseudoterminal and custom executions for a build task, it is desirable to clear the terminal from build to build automatically. This functionality is simlar to what Visual Studio does from build to build as we.. We've receieved feedback from our extension users that this would be a great feature. What is happning is that our developers do not get confused by a previous build's output when scrolling through the terminal output.

The proposal is to add an optional event to Pseudoterminal:

```TypeScript
	/**
	 * Defines the interface of a terminal pty, enabling extensions to control a terminal.
	 */
	interface Pseudoterminal {
		onDidClear?: Event<void>;
        }
```

In response VSCode would call clear on xterm.

As a note, I've tried writing this sequence:
```TypeScript
        // Clear the terminal for the next build
        this.terminalWriteEventEmitter.fire('\x1b[2J\x1b[;H');
```
Which actually seems to have no effect and doesn't actually clear the buffers.

**Comment by Tyriar** [comment]
I just added a clear command to the sample and it works fine: https://github.com/microsoft/vscode-extension-samples/commit/9f5fff5669782aff41505eefb871c7bea82e9b15

I only tested on mac so far but I'd expect it to be the same on Windows, does the sample work for you?

**Comment by GabeDeBacker** [comment]
Correct, it does not work. It clears "some stuff", but not the entire buffer.

After a task completes the terminal shows this for our build task (some info redacted):

```
BUILD: Done
    7 directories scanned

echo {%errorlevel%}:{e1366bfe-7277-46a7-b3a8-2c1bb95e49d4}
{0}:{e1366bfe-7277-46a7-b3a8-2c1bb95e49d4}
Terminal will be reused by tasks, press any key to close it.
```

Executing the ondDidWrite with that exact escape sequence causes "some" of it to be removed when the next build task starts.

Here is what happens to the terminal text when that escape sequence is executed:

```
BUILD: Done
    7 directories scanned

echo {%errorlevel%}:{e1366bfe-7277-46a7-b3a8-2c1bb95e49d4}
{0}:{e1366bfe-7277-46a7-b3a8-2c1bb95e49d4}
cd /d "*********"

echo {%errorlevel%}:{364a3f5a-7962-443b-8a7d-e83f0c2472f1}
{0}:{364a3f5a-7962-443b-8a7d-e83f0c2472f1}
set ****
```
You can see the "BUILD: Done" is still in the terminal, and you can still scroll through the buffer. The goal is to clear everything, terminal screen and the scroll buffer.

**Comment by Tyriar** [comment]
That's expected, 3J clears the scrollback if that's what you're after. Try this:

`\x1b[2J\x1b[3J\x1b[;H`

**Comment by GabeDeBacker** [comment]
That's "closer" still leaves about 20 lines :) @Tyriar  - thanks for your help.

**Comment by GabeDeBacker** [comment]
The sequence I ended up having to send to get this to work reliably is:
```
        // \x1bc => Reset terminal
        // \x1b[0J => Clear screen from cursor down
        // \x1b[1J => Clear screen from cursor up
        // \x1b[2J => Clear entire screen
        // \x1b[3J   => Clears scroll back buffer (not documented)
        // \x1b[0;0H => Move cursor to 0,0

'\x1bc\x1b[0J\x1b[1J\x1b[2J\x1b[3J\x1b[0;0H'
```
