### ISSUE TITLE
Unable to stage single lines

### ISSUE THREAD

**Issue by kimbar** [microsoft/vscode#81912]
Issue Type: <b>Bug</b>

The gif below shows how to reproduce the issue. I made two (important for this issue) changes in the file: (1) changed `address` to `_address` and (2) moved the line `manager.refresh()` and changed `manager` to `_manager`. I want to stage the first change and leave the second to another commit. Staging of (1) always drags along removal in (2).

![Selecting two lines and "stage selected ranges"](https://user-images.githubusercontent.com/16984571/66145498-41886f80-e60b-11e9-91a2-9168be2ba007.gif)

I managed to do it in Git, but at the end it was wrong too, because the "manager" line moved one line too high (under `for`). I'm not sure if this is my Git incompetence or it can't be done in this source code. However, it still should be possible to stage single lines in VSCode.

The issue persists w/o extensions.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:35.387Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
I think the tool is doing the correct thing, given the analysis of the diff. That section gets identified as: lines 26 and 27 got replaced with line 23. So, when you try to stage that *range*, it will actually do that: stage that *range*.

What you want is #9475

**Comment by kimbar** [comment]
Oh, If you're right then it is a terminology issue. I thought that "range" refers to the selected range in the diff, so when I select a line the line is the range. What you call "range" in this context is called "hunk" in diff lingo.
