### ISSUE TITLE
dead license link in win32 license.rtf agreement

### ISSUE THREAD

**Issue by estevezluis1** [microsoft/vscode#81919]
- VSCode Version: 1.38.1 prod build
- OS Version: Windows

Steps to Reproduce:

1. Stop at first process of win32 installation, license agreement.
2. Click on the link in the sentence "under the MIT license agreement at https://github.com/Microsoft/vscode/blob/master/license.txt."

The correct link is https://github.com/Microsoft/vscode/blob/master/LICENSE.txt

**Comment by alexr00** [comment]
I tried to verify by installing insiders again, but it still has a broken link. Is this the correct way to verify?

**Comment by joaomoreno** [comment]
Oh the Insiders might actually still be broken...

**Comment by JacksonKearl** [comment]
Not yet in the build. Will check tomorrow.
