### ISSUE TITLE
Custom file dialog: do not show folders with trailing slash/backslash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81911]
I am not entirely sure why we chose to do that. From my knowledge of native file dialogs, I have never seen trailing slash or backslash.

From: https://github.com/microsoft/vscode-remote-release/issues/1597

**Comment by alexr00** [comment]
It is to make typing/navigating easier. Example:
I'm in C:\users
I want to navigate to a user, so I type Alex
I now have C:\usersAlex, not C:\users\Alex

**Comment by bpasero** [comment]
@alexr00 but can we not add the path separator when I accept a folder via Enter or Mouse automatically instead of seeing it in the list?

**Comment by alexr00** [comment]
I misunderstood, I thought you were talking about the input box, not the list. 
Yes, we can do that.
