### ISSUE TITLE
Breadcrumbs move when clicking on tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81914]
Repro:

1. Open an editor with breadcrumbs
2. Make the editor width small enough that the breadcrumbs have a scroll bar
3. Click on the tab, notice that the breadcrumbs scroll to the very right (seems like odd behavior but maybe as designed?)
4. Successive clicks on the tab will shift the breadcrumbs to the left and immediately back to the right

![Kapture 2019-10-03 at 10 41 34](https://user-images.githubusercontent.com/2193314/66150606-67d9eb00-e5ca-11e9-954e-4ebf1012d604.gif)

**Comment by jrieken** [comment]
Yeah, I would say what is that click the tab focus into the editor and that the breadcrumb reveal the symbol under the cursor. Tho, unsure why there is more wiggle after that...

**Comment by jrieken** [comment]
@Tyriar Can you please share that file, the editor settings, and where the cursor is located when that happens? I am not able to reproduce this...

![Oct-09-2019 15-11-23](https://user-images.githubusercontent.com/1794099/66484345-14bed700-eaa7-11e9-8d42-322477347b4d.gif)

**Comment by Tyriar** [comment]
I can't repro it anymore either 🤷‍♂ one less issue.
