### ISSUE TITLE
Double click a file will open in single tab

### ISSUE THREAD

**Issue by designergulshan** [microsoft/vscode#81913]
Issue Type: <b>Bug</b>

Not able to open files in multiple tabs even after edit file or double click from explorer.
If I try to click or double-click on the tab(the only single tab), the quick open menu activates, seems like a click event for the quick open menu.

It was working fine but suddenly giving unexpected behavior. I took VS code updates but the issue still persists.

open project --> open file(ctrl + p) --> edit file  --> open new file --> opening in the same tab.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.10.0
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.3
prettier-vscode|esb|2.3.0
flow-for-vscode|flo|1.5.0
vscode-peacock|joh|3.1.5
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
vscode-graphql|Pri|0.2.2
LiveServer|rit|5.6.1
vscode-icons|vsc|9.4.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you show a screenshot of before, after and what you expect to happen? It's not super clear from your text.

**Comment by designergulshan** [comment]
It's little hard to explain it via text or screenshots so, I'm sharing a recording via YouTube:
https://youtu.be/RfZxbr4QHz0

**Comment by bpasero** [comment]
@designergulshan you seem to have tabs disabled, is that intentional? Try configuring:

`"workbench.editor.showTabs": true`

If tabs are disabled, we have always opened the quick open dialog upon single click. I see how this is a bit odd for the case of wanting to keep the editor.

**Comment by designergulshan** [comment]
Woo@!! 😱
It worked, thank you so much for your help. I didn't do it intentionally might be I pressed some shortcut keys...

Thank you again, it's really appricated to get quick responses.
**VS code** is become my habit now and it was really hectic for me to work with `"workbench.editor.showTabs": false` and I really don't wanna use any other IDE.


❤ **VS Code**
