### ISSUE TITLE
Async function response arguments not inferred correctly

### ISSUE THREAD

**Issue by fab1o** [microsoft/vscode#81929]
- VSCode Version: 1.39.0-insiders
- OS Version: MacOs

I have a bug to report, I'll leave this here because it seems related but I'm not sure if it's TypeScript or VSCode responsiblity, since this is just JavaScript in VSCode using JSDocs/ESDocs. But I guess VSCode uses TypeScript to infer types? Please let me know if I should report this in the TypeScript issues instead.

x is inferred with any instead of null:
```js
 /**
  * @returns {Promise<null>} 
  */
 async method(listener) { }

 var x = await method(); // x is 'any' but it should be null
```

It only fails for null or undefined. It works for other types.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new)
