### ISSUE TITLE
Should be able to trigger checkbox on custom dialog by clicking its label

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81924]
- Get a dialog with a checkbox to show up (e.g. open this url in a browser: `vscode-insiders://vscode.git/asdf`)
- Click "Don't ask again" text
- That shouldu toggle the checkbox

![image](https://user-images.githubusercontent.com/323878/66165581-e5f9ba00-e5e9-11e9-96a9-c5e07d6a2e39.png)

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/83406

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/e57eb9b95f9255054909924b3bf45fdc5b1eb955

**Comment by sbatten** [comment]
AFAICT the checkbox message text is not selectable in native macOS and click the text kept selecting for me, thus adding `user-select: none`

**Comment by JacksonKearl** [comment]
Is there a specific platform this is on? Or a setting? My dialog looks like 
![image](https://user-images.githubusercontent.com/8586769/67887809-3bea5080-fb09-11e9-8826-c5da5f2751ba.png)
and I am unable to repro in 1.39

**Comment by sbatten** [comment]
must have custom dialogs enabled. this can be done on any platform with "workbench.dialogs.customEnabled": true
