### ISSUE TITLE
Terminal split button should un-split back when clicked again

### ISSUE THREAD

**Issue by fouaddev** [microsoft/vscode#81922]
**The issue:**
When we click on the terminal split button " [ | ] " it splits the terminal window, but there is no way to unsplit it back to a single full window.

**The feature I would like to have:**
click on terminal split button => split the window.
click on it again => un-split the window back to full size.

**Comment by mdgozza** [comment]
That button does not split the window so much as it create two terminals in the same view? You can close out of any of these spawned terminals by clicking the trash can icon while the terminal is active.

What is the experience you were expecting?

![ezgif com-optimize](https://user-images.githubusercontent.com/9098106/66168297-ea829a80-e60a-11e9-8898-303de0713faf.gif)

**Comment by fouaddev** [comment]
mdgossa Yeah I see, it works great. Thanks for pointing this out.
