### ISSUE TITLE
VSCode complains about own settings.json/workspaceSettings.json (trailing comma)

### ISSUE THREAD

**Issue by SHxKM** [microsoft/vscode#81920]
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Start a new Python projects
2. Open `settings.json`
3. See errors:

<img width="379" alt="Screen Shot 2019-10-03 at 22 50 06" src="https://user-images.githubusercontent.com/6573474/66159592-fed98e00-e630-11e9-8119-19442e7e1808.png">

Referring to this (uneditable) line:

<img width="668" alt="Screen Shot 2019-10-03 at 22 51 37" src="https://user-images.githubusercontent.com/6573474/66159614-0731c900-e631-11e9-801c-7f161c1242bf.png">

I don't recall ever enabling an extension `jsonc`, nor can I find any reference to it so I think it should be what VSCode uses by default. How can I get rid of this?

Does this issue occur when all extensions are disabled?: 

No, because linting isn't enabled.

**Comment by Tyriar** [comment]
VS Code settings are jsonc, you need to remove the trailing comma from the settings.

**Comment by SHxKM** [comment]
But I cannot edit that file because it’s “read only”.

**Comment by SHxKM** [comment]
I have now ran the JSON file through a validator. Fixed all issues (unrelated to what's being reported by VSCode), and I still get this warning.

**Comment by sandy081** [comment]
/duplicate 

#80419
