### ISSUE TITLE
Debugging C/C++ over Remote-SSH connection not working

### ISSUE THREAD

**Issue by pkholland** [microsoft/vscode#81928]
Perhaps I just can't figure out the steps to making it work.
I want to use Remote-SSH to connect to and debug a C/C++ application that is running on an AWS EC2 instance (which is running Ubuntu 18.04), but can't figure out how to do that.  Online discussions describe how to connect to the remote host, and this works fine for me.  The remote host needs to have some extensions installed, which I think I have done correctly.  For example, I can build my application on the remote host.  The remote host has gdb installed, and in the vsCode Terminal I can run gdb on the code I have built there.

But doing something like 'F5' in vsCode for that remote-connected vsCode project looks like it is trying to start a debugger, but no terminal window ever opens.  While it is in this state executing a command like `ps aux | grep myApp` doesn't show my application started, nor gdb started.  I am not sure what steps are needed to make this work or if it is a bug or unfinished feature in vsCode.

I am not running the Insiders build of vsCode, but other than that have a current build.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode-cpptools
