### ISSUE TITLE
VSCode persists on all virtual desktop

### ISSUE THREAD

**Issue by piyushagade** [microsoft/vscode#81932]
Issue Type: <b>Bug</b>

On switching from one virtual desktop to another, the vscode window follows. The vscode window doesn't belong to a particular virtual desktop. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
minify|Hoo|0.4.3
vscode-cdnjs|Jak|0.18.0
cortex-debug|mar|0.3.1
rainbow-csv|mec|1.3.1
cpptools|ms-|0.25.1
particle-vscode-core|par|1.6.1
particle-vscode-pack|par|1.6.1
particle-vscode-snippets|par|1.6.1
java|red|0.50.0
vscodeintellicode|Vis|1.1.9
vscode-arduino|vsc|0.2.27
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I can't reproduce on Windows 10 Version 10.0.18990.1
