### ISSUE TITLE
Docker: pressing Enter in picker does not move focus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81937]
I was trying to connect to Docker Hub and pressed enter after typing my user id, focus was not put into the password prompt.

![image](https://user-images.githubusercontent.com/900690/66189759-ccf51580-e68a-11e9-9fde-972685898255.png)

**Comment by chrmarti** [comment]
@bpasero How do you get to that? Is that from the Docker extension?

**Comment by bpasero** [comment]
@chrmarti yes, connecting to a registry.

**Comment by chrmarti** [comment]
Cannot reproduce in the latest Insiders on Mac. Could you retry and provide steps to repro?
