### ISSUE TITLE
Remote-containers: compress statusbar label

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81939]
![image](https://user-images.githubusercontent.com/900690/66190421-39244900-e68c-11e9-9826-996cfd0514b8.png)

Can we just have an aggressive max length and put "..." into the middle of the label?

**Comment by chrmarti** [comment]
This would seem to make most sense workbench-side to cover all extensions.

**Comment by bpasero** [comment]
@chrmarti you mean to compress any text in the statusbar from any extension that is put there? I am not entirely sure, I just think that the remote case can easily produce strings of length that are long for no helpful reason.

**Comment by aeschli** [comment]
The expension needs to register a `resourceLabelFormatters` that returns `workspaceSuffix` that is human readable and not too long.

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1470
