### ISSUE TITLE
Test asynchronous source map handling of node-debug

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8193]
Test for https://github.com/Microsoft/vscode/issues/8162:

- [x] Windows - @dbaeumer 
- [x] OS X - @isidorn 
- [x] Linux - @chrmarti

In order to support more - especially slow loading - source map scenarios, I've rewritten the source map management to become asynchronous and promise based.

The first benefit from this is that extension host debugging can use the source map available from our CDN. 

Since the change behind this feature request is big and risky, we have to verify that all source map related functionality still works.

**Please note**: since we will not release this feature in the June drop you have to test this with a special build from the **aweinand/asyncsourcemaps** branch on https://vscode-builds.azurewebsites.net/insider.

Verify any scenario that involves source maps:
Just pick or invent a sample that uses source maps and verify that setting breakpoints and hitting them works as expected.

Some examples:
- VS Code extension host debugging (please note: hitting the first breakpoints takes some time until the 3 MB sourcemap has been downloaded)
- VS Code selfhosting scenario: attach to extension host
- any TypeScript program: try to vary the uses source map style:
   - separate file
   - inlined source map
   - inlined source map with inlined source
- coffescript
- mocha tests
- etc.

**Comment by dbaeumer** [comment]
Tested everything except coffeescript.

**Comment by isidorn** [comment]
I tested mocha tests and extension host debugging
