### ISSUE TITLE
argument quoting in launch.json

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#81944]
In task.json it is possible to [specify the quoting of the argument](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks).

```
  "args": [
    {
      "value": "folder with spaces",
      "quoting": "escape"
    }
  ]
```

In launch.json this is not accepted.

Quoting is done automatic if the argument contains a space but I want to control it the same as in task.json because my argument does not contain a space but needs to be quoted or escaped.

**Comment by rioj7** [comment]
Can we have a quoting option of `none`. No automatic quoting. This allows you to pass multiple arguments from a command variable expansion `${command:function_name}`. Or the possibility to quote the argument yourself in case the automatic version is wrong.

**Comment by weinand** [comment]
VS Code does not "own" launch config properties like `args`, so it cannot introduce an alternative "quoting" representation.
Launch configuration properties (and their schemas) are contributed by individual debug extensions.

I suggest to file this feature request against the debug extension you are using.
