### ISSUE TITLE
Explorer is blurry on every other step with display scale 1.3 on KDE

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#81941]
Issue Type: <b>Bug</b>

I'm running KDE Plasma and has display scaling set to 1.3 in the KDE settings. When I have that, every other scroll step in the Explorer makes the fonts blurry.

The list is sharp in the first screenshot, and in the second on I've scrolled down one step and the list has become blurry.

![Screenshot_20191004_103014](https://user-images.githubusercontent.com/3390621/66193456-dd10f300-e692-11e9-902e-96cb1c9c13cc.png)
![Screenshot_20191004_103031](https://user-images.githubusercontent.com/3390621/66193457-dd10f300-e692-11e9-8caa-dcf58e541378.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.12.14-lp151.28.13-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.84GB (46.84GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-markdownlint|Dav|0.30.2
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.0.1
language-cython|guy|0.0.6
python|ms-|2019.9.34911
cpptools|ms-|0.25.1
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
markdown-preview-enhanced|shd|0.4.3

</details>

**Comment by isidorn** [comment]
This should be fixed with new electron (I hope)
Please try out vscode insiders next week and let us know if you still see this
