### ISSUE TITLE
SASS Modules (@forward and @use)

### ISSUE THREAD

**Issue by wongjn** [microsoft/vscode#81943]
Dart Sass 1.23.0 dropped recently and with it, [a new module system](http://sass.logdown.com/posts/7858341-the-module-system-is-launched).
It would be great if this was added into the language features for SCSS/SASS.

Documentation pages for each of the new at-rules:

- [@use](https://sass-lang.com/documentation/at-rules/use)
- [@forward](https://sass-lang.com/documentation/at-rules/forward)

**Comment by wongjn** [comment]
[I've made an extension](https://marketplace.visualstudio.com/items?itemName=wongjn.scss-modules) that adds highlighting in SCSS until this gets added to core.

**Comment by octref** [comment]
@alexr00 FYI — The upstream change is in. I pulled in the grammars.

**Comment by wongjn** [comment]
I'm wondering if this can actually be closed; there is still the need to update the SCSS parser to understand the new syntax via microsoft/vscode-css-languageservice#183.

**Comment by octref** [comment]
OK, I'll keep it open until I have time to review that PR.

**Comment by octref** [comment]
Thanks to the great work of @wongjn, now we have both syntax highlighting and language server support for SCSS modules.
