### ISSUE TITLE
Debug console scrolls near top after each evaluated line

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#81951]
Although the debug console scrolls to top after evaluation of an expression is marked as solved [ see #70331](https://github.com/Microsoft/vscode/issues/70331#issuecomment-508223382) I still experience this problem. I would, therefore, like to verify what goes wrong on my system.

## Screen recoding
![scroll_problem_04-10-2019](https://user-images.githubusercontent.com/17570430/66201398-8cee5c80-e6a3-11e9-8db4-790c2a823832.gif)

## System information
OS: Ubuntu 18.04
VSCODE version: 1.39.0-insiders

## What I tried
- Installing the newest insider release.

**Comment by buckstephenh** [comment]
Same thing occurring for me, but scroll goes to top during code execution out without any user interaction at all with debug panel.  If I scroll to the bottom and another event comes in, scroll returns to the top.

Version: 1.39.0-insider
Commit: c8252b63f547674d2faf361d4181bb76b0b5f81a
Date: 2019-10-04T09:23:20.797Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Comment by isidorn** [comment]
Fixed via a6ac3e5634

**Comment by isidorn** [comment]
Reopening so we can discuss if this goes to the release branch. I think it should

**Comment by rickstaa** [comment]
Great thanks a lot! I will verify the fix if it is released to vscode-insiders.

**Comment by rickstaa** [comment]
The fix is working thanks!

**Comment by rickstaa** [comment]
The fix is not working anymore. Do I have the right release (1.40.0-insiders)?

**Comment by isidorn** [comment]
Please follow this issue https://github.com/microsoft/vscode/issues/77837

**Comment by rickstaa** [comment]
Thanks, I didn't see your last message stating that you reverted the fix.
