### ISSUE TITLE
FileSystemProvider doesn't have the correct return type

### ISSUE THREAD

**Issue by Tpuljak** [microsoft/vscode#81957]
- VSCode Version: 1.38.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Create custom implementation of vscode.FileSystemProvider.
2. Send a _rename_, _createDirectory_ or _writeFile_ command.

First of all, It seems a little bit confusing to me that before the _rename_, _createDirectory_ or _writeFile_ commands, the _stat_ command is called. I would say it is kind of logical since the stat should check if the file or directory already exists.
The thing that isn't clear in the docs is what should the stat return so the commands can proceed. Later I figured out that the stat should resolve to `undefined`.
The actual bug is in the fact that stats return type is `FileStat` but it allows for an undefined resolve therefore the return type should actually be `FileStat | undefined`.

P.S. I would suggest that you update the docs with a more clear explanation of how the _rename_, _createDirectory_ and _writeFile_ command chain is executed.

**Comment by jrieken** [comment]
> Later I figured out that the stat should resolve to undefined.

The `stat` function is spec'd to return `FileStat` or `Promise<FileState` or throw, it should not return `undefined`. Please attach an extension (snippet) and steps that allow me to reproduce this issue.

**Comment by Tpuljak** [comment]
Sorry @jrieken for the wrong expression. I meant, return a Promise that can resolve to `undefined` like so: 
 ```
return new Promise(resolve => {
        const interval = setInterval(() => {
          const cached = this.statCache.get(uri.toString());
          if (cached) {
            if (cached.ctime === 0 && cached.mtime === 0 && cached.size === 0 && cached.type === vscode.FileType.Unknown) {
              resolve(undefined);

              throw vscode.FileSystemError.FileNotFound(uri);
            } else {
              resolve(cached);
            }

            clearInterval(interval);
          }
        }, 100);
      });
```

So what I'm doing here is waiting until the host file provider sends a `default` (or empty FileStat)  and then I resolve the promise to `undefined`. I believe the error here is that the Promise should have a resolve type of `FileStat | undefined` rather than just `FileStat` even though the above code works.

**Comment by jrieken** [comment]
> The resolve(undefined) is needed for the commands I mentioned in the first comment to work.

No, you need to call the `reject`-handler of your promise. The throw-statement doesn't do anything like that.

**Comment by jrieken** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise for more details on resolving or rejecting promises.
