### ISSUE TITLE
Disable all extensions and allow to enable selectively

### ISSUE THREAD

**Issue by xahon** [microsoft/vscode#81950]
I cannot check for an issue in extension because I need to disable all except that target extension. Option `--disable-extensions` allow us to disable all extensions at once but it doesn't allow to enable specific extensions
![image](https://user-images.githubusercontent.com/18731681/66200822-3570e080-e6e5-11e9-9ae5-8cd2749213d2.png)
Or it should be `--disable-extensions-except ID1 ID2 ID3`
I don't know which one is the best

**Comment by madarsbiss** [comment]
As far as I know and https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions documents it, `--disable-extensions` do not support any additional parameters yet.

The reason for this most likely is: The possibility of you having like 20+ of extensions is pretty low (when you would really starting need this), so in rare cases like these you can disable them manually.

**Comment by xahon** [comment]
@madarsbiss when I worked with javascript, nodejs, react, npm, html, css it's already about ~60 extensions + debugger for chrome/firefox, prettier, json tools, etc.. and you can have some extensions temporarily disabled and when you do `Disable all extensions` -> Test something -> `Enable all extensions` previously disabled extensions will become enabled again and you will need to disable every single one again. Quite time consuming thing

**Comment by sandy081** [comment]
Yes, you cannot enable extension when you start in extensions disabled mode. There is another UI gesture to disable all installed extensions which allows enabling extension one by one. 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/10746682/69041625-1fe31c00-09f0-11ea-823e-495253d712f4.png">
