### ISSUE TITLE
Add data for how many screen reader users we have

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81964]

**Comment by connor4312** [comment]
I see this telemetry event getting sent when toggling the screen reader on whilst vscode is open, however if a screenreader is already on when the editor is opened, the telemetry event doesn't get fired as it's only triggered by Electron's `accessibility-support-changed` event. This probably isn't the desired implementation here.

**Comment by joaomoreno** [comment]
I can take this.

**Comment by isidorn** [comment]
@connor4312 @joaomoreno  Thanks for catching and fixing this
