### ISSUE TITLE
Intellisense for launch.json

### ISSUE THREAD

**Issue by LindsayFowler** [microsoft/vscode#81966]
Issue Type: <b>Feature Request</b>

When creating new configurations for launching Python,  entering "cwd": provides just one intellisense option; the default value:
"${workspaceFolder}"

The comment at the top of the file says "Use IntelliSense to learn about possible attributes. Hover to view descriptions of existing attributes."

The question is, how is anyone supposed to find ${fileDirname} when there is no intellisense for it or any other keyword attribute applicable to "cwd:"? I always have to spend time looking up these keywords online.

If users are forced to set edit a JSON file in order to set their debug options, then the intellisense should at least be comprehensive.

Thank you

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
This works fine for me
I understand that not in all cases we correctly show the varialbe name. For instance if you start typing `file` however that is a limiation of the JSON scheme intelisense and not sure how I could improve this @aeschli Problem being that JSON probably treats the `${` as part of the word, and thus on typing file it filters out ${fileDirname}

![Screenshot 2019-10-07 at 11 26 03](https://user-images.githubusercontent.com/1926584/66300286-4859ff80-e8f5-11e9-9486-c0bb3b1018b2.png)
