### ISSUE TITLE
Shoudn't the shortcut for "Toggle Developer Tools" be set to "editorFocus" for "when" parameter?

### ISSUE THREAD

**Issue by ParkerPy** [microsoft/vscode#81965]
I was frustrated I could never open the Developer Tools with the default shortcut `Ctrl + Shift + I`. 
After going through all extensions, I realized it was set to only work when Developer Tools is open: `"when": "isDevelopment"`. 
Shouldn't this also be set to **"editorFocus"** and maybe even more, so its actually a toggle?  Here's how I edited my keybindings.json for others with this issue (Also added them to **"reloadWindow,"** so you didn't have to be in Developer mode):
```
{
    "key": "ctrl+shift+i",
    "command": "workbench.action.toggleDevTools",
    "when": "isDevelopment || editorFocus || terminalFocus"
},

{
    "key": "ctrl+alt+r",
    "command": "workbench.action.reloadWindow",
    "when": "isDevelopment || editorFocus || terminalFocus"
},
```

**Comment by Tyriar** [comment]
The typical user shouldn't need the devtools, it's primarily for development. If you need them always just add a custom keybinding. Here are mine:

```
{ "key": "ctrl+shift+i",     "command": "workbench.action.toggleDevTools", "when": "!isMac" },
{ "key": "cmd+alt+i",        "command": "workbench.action.toggleDevTools", "when": "isMac" }
```
