### ISSUE TITLE
The on-screen keyboard does not display and does not work properly.

### ISSUE THREAD

**Issue by PsiACE** [microsoft/vscode#81962]
Issue Type: Bug

Recently, my laptop broke some buttons and had to resort to the on-screen keyboard. 
Unfortunately, vscode does not seem to support it at this time.

I think there may be some other accidents that have caused this problem.

Vscode version: 1.38.1
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.2-300.fc31.x86_64

**Comment by PsiACE** [comment]
I am working under the Fedora31 Beta, using the gnome desktop, and the latest stable version of vscode, it seems that the on-screen keyboard is completely out of work.

I think there may be some other accidents that have caused this problem.

**Comment by Tyriar** [comment]
Please explain what doesn't work.

**Comment by PsiACE** [comment]
Hi, @Tyriar. The on-screen keyboard does not work. In fact, I can't see the on-screen keyboard when I use vscode. But in `firefox` or `gnome builder`, everything is ok.

**Comment by PsiACE** [comment]
Since this on-screen keyboard feature comes from gnome, these may be useful information:

OS: Fedora 31 (Workstation Edition) x86_64
DE: GNOME 3.34.0

**Comment by Tyriar** [comment]
Since the on screen keyboard works fine in macOS and Windows this seems to be an issue with either Electron or Chromium's support for on screen keyboards on Linux.
