### ISSUE TITLE
Hovering the glyph margin makes editor jump-scroll with editor.cursorSurroundingLines

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81967]
This happens in the current Insiders v1.39.0

- VSCode Version: 1.39.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Set `"editor.cursorSurroundingLines": 5`
2. Open your settings.json file (`cmd+,`)
3. Hover the glyph margin
4. Notice that the editor scroll jumps to make the line you hovered stay within the surrounding lines.

[Demo](https://gph.is/g/Z2V2ObD)

Expectation:
The editor scroll doesn't move while you're hovering the glyph margin.

Does this issue occur when all extensions are disabled? Yes

**Comment by andrecasal** [comment]
That issue had nothing to do with mine.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue anymore in latest VS Code.
