### ISSUE TITLE
YAML: Bad syntax highlighting

### ISSUE THREAD

**Issue by pjww** [microsoft/vscode#81969]
- VSCode Version: 1.35.0
- OS Version: Windows 10, version 1903

Steps to Reproduce:

1. Write in an *.yml file:

```
some_bash_script:
  content: |
            echo 'Some multi-line echo...

            ...ending with two line breaks. 

            ' > some_file.txt
  some:
  further:
  yaml:
  parts:

```

Effect:

![vscode bug](https://user-images.githubusercontent.com/16942221/66219849-36494880-e6cc-11e9-8660-1db826108870.png)

You can, however, work this around with not-so-pretty-trick...

![vscode bug 2](https://user-images.githubusercontent.com/16942221/66220006-84f6e280-e6cc-11e9-86d0-0e1998d509ed.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/textmate/yaml.tmbundle/issues/31
