### ISSUE TITLE
Commit Staged (ammend) will corrupt commit message

### ISSUE THREAD

**Issue by jseward** [microsoft/vscode#81979]
Issue Type: <b>Bug</b>

1. Use vs.code to make a commit with newlines in the message

ex.
```
a
b
c
```

2. Use vs.code to Commit Staged (ammend)

Notice that the commit message is now:

```
abc
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (2.05GB free)|
|Process Argv|--folder-uri file:///c%3A/ironclad/sins2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.2.6
gitlens|eam|10.0.1
prettier-vscode|esb|2.3.0
gc-excelviewer|Gra|2.1.32
jbockle-format-files|jbo|3.0.0
better-cpp-syntax|jef|1.14.7
vscode-peacock|joh|3.1.5
chat|kar|0.22.1
vsls-whiteboard|los|0.0.9
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
powershell|ms-|2019.9.0
vsliveshare|ms-|1.0.905
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
hlsltools|Tim|1.0.4
vscode-lua|tri|0.12.4
vscode-icons|vsc|9.4.0
vscode-proto3|zxh|0.3.0

</details>

**Comment by joaomoreno** [comment]
#40295
