### ISSUE TITLE
Links to Slack extension workspace invite expired

### ISSUE THREAD

**Issue by bkelley13** [microsoft/vscode#81972]
Steps to Reproduce:

1.  https://github.com/Microsoft/vscode/wiki/Feedback-Channels
2. Click on the " join the Slack workspace" link
You see "This invite link is no longer active."

**Comment by Tyriar** [comment]
@eamodio do we need to update the aka.ms link?

**Comment by eamodio** [comment]
@Tyriar Argh -- the "non-expiring" slack invite link expired again (sadly it expires based on usage -- 2000 invites, so its hard to keep track of). I've update my redirect to point to the new link, so once the DNS change propagates it should work again.

**Comment by eamodio** [comment]
This is now fixed

**Comment by bkelley13** [comment]
Thank you!!
