### ISSUE TITLE
Support font transparency in minimap

### ISSUE THREAD

**Issue by JonathanTroyer** [microsoft/vscode#81971]
I don't know how feasible this is, but it would be great if the minimap used the same font transparency as the editor.

For instance:
![image](https://user-images.githubusercontent.com/15098499/66222386-a9d06300-e696-11e9-9f52-71c0fd7fe474.png)
corresponds to 
![image](https://user-images.githubusercontent.com/15098499/66222406-b48af800-e696-11e9-9c13-6f2821d6adf6.png)

It gets very confusing when you have a lot of comments.
![image](https://user-images.githubusercontent.com/15098499/66222541-029ffb80-e697-11e9-9b59-d96362a4a836.png)

I'm sure you can tell the bottom right block are comments. But did you know the top block also are?

Yes, I know, I could pick a color that more closely resembles the grey I'm after without using transparency. And that works out great. But from a theme creators perspective, not being able to use font transparency really cuts down on your ability to easily tweak things and make scalable systems of color.

**Comment by alexdima** [comment]
This is now possible (via https://github.com/microsoft/vscode/pull/132681) using:
```
"workbench.colorCustomizations": {
  "minimap.foregroundOpacity": "#ffffff91",
  "minimap.background": "#ffffff00",
}
```
