### ISSUE TITLE
VSCode won't launch on mac

### ISSUE THREAD

**Issue by darzu** [microsoft/vscode#81970]
- VSCode Version: 1.38.1 "b37e54c98e1a74ba89e03073e5a3761284e3ffb0 x64"
- OS Version: MacOS 10.14.6 (18G103)

For the last couple weeks (I wish I could be more precise, although I know it first happened sometime within the last two months), my laptop gets into a state where it can no longer launch VSCode from the command line or app icon. This happens most days. There are three separate work arounds that I have found (listed below), however each of these only works temporarily, inevitably I end up in this broken state again.

Steps to Reproduce (icon):
1. Click on "Visual Studio Code" app icon
2. Nothing happens, no window appears, no dot appears by the icon
Steps to Reproduce (command line):
1. Run "code ." in some folder in my user directory
2. Nothing happens, no window appears, no dot appears by the icon

If I launch with "--verbose" I see:
```
~/mc/pxt(master=) $ code --verbose
[main 2019-10-04T15:38:02.271Z] Sending env to running instance...
[main 2019-10-04T15:38:02.277Z] Sent env to running instance. Terminating...
[main 2019-10-04T15:38:02.277Z] Lifecycle#kill()
```
If I launch with "--verbose --disable-gpu" (which doesn't fix the issue) I see:
```
~/mc/pxt(dazuniga/docs_header *=) $ code --disable-gpu --verbose
[20394:1004/083920.476724:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
[main 2019-10-04T15:39:20.568Z] Sending env to running instance...
[main 2019-10-04T15:39:20.572Z] Sent env to running instance. Terminating...
[main 2019-10-04T15:39:20.572Z] Lifecycle#kill()
```

Doing any of the following will **temporarily** fix the issue:
1. launch with the "--user-data-dir ~" command line option. VSCode will open fine. I'm not running vscode from any remote location or using sudo however.
2. Rebooting my laptop. When I reboot, vscode will launch again, but inevitably I get into this broken state again within a day or so.
3. If I search for "Electron" processes and kill them all:
![image](https://user-images.githubusercontent.com/6453828/66221703-71278e00-e684-11e9-87ef-a86ed61d3de7.png)
then vscode will launch again.
Edit: Actually, after kill these electron processes vscode will start but none of my keyboard strokes are making into the window. Keycords don't work and I can't type in buffers.

Does this issue occur when all extensions are disabled?: Yes

The most recent time this happened is this morning. Last night my laptop died because it ran out of power, and I then charged it over night and opened it this morning. As MacOS does, it restored all the windows and processes I had running before it died from low-power. There were likely vscode windows running when my laptop ran out of power. My suspicion is that macos brought back some subset of resources vscode needs when it restored my state after regaining power, but somehow this left vscode in an inoperable state.

**Comment by Tyriar** [comment]
FWIW this means that there is a "main process" running so it asks it to open the window:

```
[main 2019-10-04T15:38:02.271Z] Sending env to running instance...
[main 2019-10-04T15:38:02.277Z] Sent env to running instance. Terminating...
```

When you get into this state you can kill any existing instances and it should work again without a full reboot.

**Comment by darzu** [comment]
> When you get into this state you can kill any existing instances and it should work again without a full reboot.

Thanks for the info. I'm unsure how to find the "main process" however. There's no vscode/code in MacOS's task manager, and grep'ing for "code" or "vscode" in running processes turns up nothing.

What's the name of / how does one find the "main process" ?

**Comment by Tyriar** [comment]
Try `ps aux | grep Code.app` then use `kill <pid>` to kill it.

**Comment by bpasero** [comment]
@darzu it would be interesting, if this happens again:
* what exact process is hanging (all of them or just one) and what their command line arguments are
* how you got into that state, e.g. did VSCode crash or did you quit it normally?

**Comment by darzu** [comment]
Thanks, I'll try to gather this next time I see the issue.

It definitely wasn't after VSCode crashed. The last time I saw it it was after MacOS shut down unexpectedly (low power) and then rebooted and restored all my applications. So MacOS may have not restored VS Code properly.

**Comment by bpasero** [comment]
Ok thanks. The macOS shutdown thing sounds like it may not be under our control.

**Comment by HzrdIRL** [comment]
Same issue happening to me. Cannot kill pid because it's constantly changing. I suspect that it's stuck in a loop trying to bring itself back to life. I'm uninstalling/reinstalling and will report back.
