### ISSUE TITLE
Git commit message format not reflected in git log

### ISSUE THREAD

**Issue by cakeray** [microsoft/vscode#81978]
I recently decided to use VS code as my main git editor, seeing as how I can use a terminal, write commit messages, and view my git history all in one place. I was previously using git bash, Gitk, and Git Gui as a part of my git workflow. One of the reasons I switched to VS code was its ability to format git commit messages so I wouldn't have to wrap the contents of the message manually. The following options are included in my settings file...

`"[git-commit]": {
        "editor.rulers": [72],
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 72
    }`

This does seem to work when I write a git message using `git commit` or `git commit --amend` using the terminal. A new tab pops up where I can write my commit message as so...

![image](https://user-images.githubusercontent.com/22112595/66236669-f7a19700-e6a7-11e9-910f-fc7d87952318.png)

However, when I run git log, the commit message does not have any line wrapping or formatting.

![image](https://user-images.githubusercontent.com/22112595/66236944-9e863300-e6a8-11e9-8f0a-fd14e713200d.png)

Shouldn't the formatting apply so it's the same when viewed in git log too? I'm not sure if there is a setting that I've missed, or if there's something else going on here.

Here are my settings...

- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.17134
- Git Version: 2.22.0.windows.1

Steps to Reproduce:

1. Include the settings mentioned above in your settings file.
2. Create a commit message using the terminal (`git commit` or `git commit --amend`) with some lines going over the 72 column limit (or whatever limit you decide to use in your settings file)
3. Save and close the git commit tab.
4. Run `git log` and note absence of formatting for the commit message.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
That's because the word wrap is doesn't add line breaks, you should use the ruler and manually put in the lines. Or maybe there's an extension out there that can format git commit type files.

**Comment by cakeray** [comment]
I know this issue has been closed but would it be possible to provide the rationale behind having a method to format a git commit message (or anything else, I'm assuming) within the editor but not have it saved with the desired format?

**Comment by Tyriar** [comment]
I don't think we have a built-in formatter for git, but an extension could add one that does what you ask.
