### ISSUE TITLE
VS Code's UI rendering freezes until I switch to any other app.

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#81976]
- VSCode Version: 1.38.1
- OS Version: macOS 10.14.6 (18G87)

Steps to Reproduce:

1. Not sure how to get into this state

Does this issue occur when all extensions are disabled?: I haven't tried it yet.

---

Basically what happens is VS Code's UI rendering gets entirely frozen (though it seems to still work behind the scenes, just not visible), until I press `cmd-tab` to switch to any other app.

As soon as I switch to another app, the rendering of VS Code (now not the focused window) jumps to where it should be.

When I switch back to VS Code, I can continue for a few seconds until the rendering freezes again.

VS Code is still operational in this state (except for rendering), because I can type sequences of keys, and knowing what to expect the edited text to be, I can switch to another app and come back, and see the expected text.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
