### ISSUE TITLE
Test Open in Terminal settings for OS X

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8198]
Test for https://github.com/Microsoft/vscode/pull/6136:

- [x] OS X - @sandy081 

Thanks to PR https://github.com/Microsoft/vscode/pull/6136 it is now possible to configure which terminal application to use for the "Open in Terminal" action.
The name of the corresponding setting is `terminal.external.osxExec`.

Verify that
- this works with common terminal applications for OS X.
- the newly created terminal/shell opens in the correct directory
- try to break it by using directories with funny characters in the path.

**Comment by sandy081** [comment]
Tested with Terminal and iTerm app with simple to complex folder names

**Comment by jaime-olivares** [comment]
Is it possible to configure VSCode for using the integrated terminal when selecting the option 'Open in terminal' in the folder explorer?

**Comment by weinand** [comment]
@jaime-olivares this is not yet possible, but a feature request for this exists.

**Comment by jaime-olivares** [comment]
@weinand do you know the FR number, so I can pile on?

**Comment by weinand** [comment]
@Tyriar do you know the issue number for the feature request raised by @jaime-olivares?

**Comment by Tyriar** [comment]
@jaime-olivares #8132 is for just the context menu on the explorer.

@weinand I think there's an issue somewhere for enabling *either* the integrated or external but I can't find it. Plus I'm generally against it, preferring to expose both commands to users can use either fi they want.
