### ISSUE TITLE
Webview: Cannot bypass self-signed certificate error

### ISSUE THREAD

**Issue by queeniema** [microsoft/vscode#81985]
Issue Type: <b>Bug</b>

I am using [axios](https://github.com/axios/axios) to make `GET` requests to fetch some JSON data. This is code I'm using:

```js
const config = {
  url: <MY_REST_URL>,
  headers: { Authorization: `Bearer <MY_TOKEN>` }
};
return axios(config).then((response) => {
  console.log(response);
}).catch((error) => {
  console.log(error);
});
```

There are two scenarios that I'm testing this in: when the request is made in the extension code and when it is made in a webview.

### Extension

Making the request above returns an error response (this is expected for the REST URL I'm using):
```json
{
  "code": "DEPTH_ZERO_SELF_SIGNED_CERT",
  "isAxiosError": true,
  "message": "self signed certificate",
  ...
}
```

To bypass this self-signed certificate error, I added `httpsAgent: new https.Agent({ rejectUnauthorized: false })` to the `config` object. After doing so, I get a response with the correct status code and the JSON data I expect.

```js
const config = {
  url,
  headers: { Authorization: `Bearer ${token}` },
  httpsAgent: new https.Agent({ rejectUnauthorized: false })
};
```

### Webview

When I make the request with `httpsAgent` omitted from `config`, I see the following error in the webview developer tools.

<img width="833" alt="Screen Shot 2019-10-04 at 4 32 58 PM" src="https://user-images.githubusercontent.com/2454818/66245770-bc619100-e6c4-11e9-835b-72c252e66797.png">

The issue is this: when I add in `httpsAgent: new https.Agent({ rejectUnauthorized: false })`, I **still** see the same error:
```
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
```

---

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Does this approach work in normal Chrome outside of a VS Code extension?

**Comment by queeniema** [comment]
I tried in normal Chrome and the `httpsAgent` approach does _not_ work (I still see the certificate error). So I'm not quite sure how it is working in the extension code.

**Comment by mjbvz** [comment]
They are run in different environments: extensions run as node while webviews are run a browser environment. 

Since this issue is not specific to VS Code, I don't think there's any action for us on the VS Code side here. As potential solutions: your webview could funnel all these requests through your extension, or there may be a workaround you can use inside the webview itself. Try researching how other people handle this on the web
