### ISSUE TITLE
File tree stuck in a dimmed state

### ISSUE THREAD

**Issue by tehshane** [microsoft/vscode#81981]
Issue Type: <b>Bug</b>

1. Run a script or process that will eventually add/remove files from the project
2. While the script runs, use the "New File" command and begin typing the filename.
3. Before committing the filename, the script finishes and the file explorer tries to update
4. The filename input disappears and the file explorer remains stuck in a dimmed state. Reloading the window or creating/renaming another file restores the opacity.

![vscode-bug](https://user-images.githubusercontent.com/3360089/66241404-d646a800-e6b3-11e9-8084-b32aafa03543.gif)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (7.68GB free)|
|Process Argv|C:\2h\Projects\REDACTED|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
atlascode|atl|2.0.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.0.1
beautify|Hoo|1.5.0
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
presentationmode|jsp|1.1.5
chat|kar|0.22.1
vscode-commitizen|Kni|0.8.3
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.8.1
python|ms-|2019.9.34911
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
vsliveshare|ms-|1.0.905
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
debugger-for-chrome|msj|4.12.0
material-icon-theme|PKi|3.9.0
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-yaml|red|0.5.3
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.0.3
swdc-vscode|sof|1.1.30
wordpress-snippet|tun|1.1.5
vscodeintellicode|Vis|1.1.9

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This is fixed in insiders. Please let u know if you can reproduce with latest vscode insiders or if you can reproduce after our next vscode stable update and we can reopen this. Thanks
