### ISSUE TITLE
Painfully Slow Startup and Render Times

### ISSUE THREAD

**Issue by Krxnky** [microsoft/vscode#81984]
Issue Type: <b>Performance Issue</b>

My Visual Studio Code and electron apps take ages to load, I've tried running with no extensions and did not help at all. This all started happening a few weeks ago. Any help?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    76	  1056	code main
    0	   198	 10868	   window (Startup Performance - group-watch - Visual Studio Code)
    0	    11	  1880	     watcherService 
    0	    11	 15660	       console-window-host (Windows internal process)
    0	    39	 12412	     searchService
    0	    88	 12676	     extensionHost
    0	    70	 17292	       electron_node tsserver.js 
    0	   109	 20548	       electron_node tsserver.js 
    0	    46	 19096	         electron_node typingsInstaller.js typesMap.js 
    0	     5	 15116	     console-window-host (Windows internal process)
    0	     5	 21892	     "C:\Program Files\Git\bin\bash.exe"
    0	     9	  1912	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    13	 12444	   electron-crash-reporter
    1	    67	 13804	   window (Issue Reporter)
    1	    89	 18796	   gpu-process
    0	    65	 23028	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Startup Performance - group-watch - Visual Studio Code)
|    Folder (group-watch): 11 files
|      File types: js(3) html(2) css(2) json(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
discord-vscode|icr|3.8.3
LiveServer|rit|5.6.1

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Krxnky** [comment]
VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:24:45.690Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (19.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|3.8.3


</details>

**Comment by Krxnky** [comment]
VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:24:45.690Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (19.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    83	 58492	code-insiders main
    2	    69	  9948	   window (Issue Reporter)
    0	   167	 11032	   window (Startup Performance - Visual Studio Code - Insiders)
    0	    81	 46324	     extensionHost
    0	    73	 57356	   gpu-process
    0	    68	 59444	   shared-process
    0	    13	 59880	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|3.8.3


</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by valeriterziev** [comment]
Tested insider and exploration builds:

# 1.39.0-insider

## System Info

* Code - Insiders: 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a)
* OS: win32(10.0.18362)
* CPUs: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz(8 x 2592)
* Memory(System): 15.87 GB(9.30GB free)
* Memory(Process): 187.96 MB working set(164.15MB private, 1.05MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process          | Info                                     |
| --------------------------------------------------------------- | -------- | ---------------- | ---------------------------------------- |
| start => app.isReady                                            | 54       | [main]           | initial startup: true                    |
| nls:start => nls:end                                            | 0        | [main]           | initial startup: true                    |
| require(main.bundle.js)                                         | 116      | [main]           | initial startup: true                    |
| app.isReady => window.loadUrl()                                 | 209      | [main]           | initial startup: true                    |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 4227     | [main->renderer] | NewWindow                                |
| require(workbench.desktop.main.js)                              | 456      | [renderer]       | cached data: YES, node_modules took 70ms |
| require & init workspace storage                                | 32       | [renderer]       | -                                        |
| init workspace service                                          | 21       | [renderer]       | -                                        |
| register extensions & spawn extension host                      | 5812     | [renderer]       | -                                        |
| restore viewlet                                                 | 0        | [renderer]       | -                                        |
| restore panel                                                   | 0        | [renderer]       | -                                        |
| restore editors                                                 | 146      | [renderer]       | 1: PerfviewInput                         |
| overall workbench load                                          | 279      | [renderer]       | -                                        |
| workbench ready                                                 | 5276     | [main->renderer] | -                                        |
| extensions registered                                           | 11234    | [renderer]       | -                                        |


# 1.37.0-exploration

## System Info

* Code - Exploration: 1.37.0-exploration (960208fdf9aa06e6892aa14c9c84ddd607fbeb2f)
* OS: win32(10.0.18362)
* CPUs: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz(8 x 2592)
* Memory(System): 15.87 GB(9.76GB free)
* Memory(Process): 154.60 MB working set(129.67MB private, 1.03MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                    | Duration | Process          | Info                                     |
| ------------------------------------------------------- | -------- | ---------------- | ---------------------------------------- |
| start => app.isReady                                    | 74       | [main]           | initial startup: true                    |
| nls:start => nls:end                                    | 0        | [main]           | initial startup: true                    |
| require(main.bundle.js)                                 | 98       | [main]           | initial startup: true                    |
| app.isReady => window.loadUrl()                         | 165      | [main]           | initial startup: true                    |
| window.loadUrl() => begin to require(workbench.main.js) | 4535     | [main->renderer] | NewWindow                                |
| require(workbench.main.js)                              | 328      | [renderer]       | cached data: YES, node_modules took 63ms |
| require & init workspace storage                        | 25       | [renderer]       | -                                        |
| init workspace service                                  | 13       | [renderer]       | -                                        |
| register extensions & spawn extension host              | 206      | [renderer]       | -                                        |
| restore viewlet                                         | 0        | [renderer]       | -                                        |
| restore panel                                           | 0        | [renderer]       | -                                        |
| restore editors                                         | 72       | [renderer]       | 1: PerfviewInput                         |
| overall workbench load                                  | 190      | [renderer]       | -                                        |
| workbench ready                                         | 5335     | [main->renderer] | -                                        |
| extensions registered                                   | 5694     | [renderer]       | -                                        |

**Comment by bpasero** [comment]
@valeriterziev so to confirm, it takes around 5s until you see the editor right? Is it possible that some AV software is checking VSCode installation on startup?
