### ISSUE TITLE
Emmet Abbrevation html:5 for pug doesn't produce doctype shortcut

### ISSUE THREAD

**Issue by Shinigami92** [microsoft/vscode#81993]
I don't know if this is the right repo,
but when I open a `pug`-file and use `html:5` emmet,
it produces `<!DOCTYPE html>` in the first line instead of using the `pug`'s [doctype shortcut](https://pugjs.org/language/doctype.html#doctype-shortcuts)

![image](https://user-images.githubusercontent.com/7195563/66252920-5c6cf800-e761-11e9-92fc-ad102d55fbbc.png)

**Comment by octref** [comment]
`html:5` does the same expansion on emmet.io. You should open an upstream issue at https://github.com/emmetio/emmet.
