### ISSUE TITLE
Test 'Variable Type Hover'

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8199]
Test for https://github.com/Microsoft/vscode/issues/8040:

- [ ] all platforms - @aeschli 

In the latest revision of the VS Code debug protocol Variables can use an optional 'type' attribute. VS Code shows this attribute when hovering over the name of a Variable (hovering over the value of a variable still shows the long version of the value).

The only debug-adpater that supports this right now is [mock-debug](https://marketplace.visualstudio.com/items?itemName=andreweinand.mock-debug) (from the Marketplace).
Install mock-debug, create a launch config and a markdown file `readme.md` with some lines of text. Then start debugging.

Verify that the (fake) variables in the Variables view show a type when hovering over the variable's name and that the value is still shown when hovering over the variable's value.

**Comment by aeschli** [comment]
Tested on Linux, Mac and Windows
