### ISSUE TITLE
Hide "(Workspace)" and "[Administrator]" suffixes from the window title

### ISSUE THREAD

**Issue by arthurjosse** [microsoft/vscode#81995]
A tiny request.

- VSCode version: 1.38.1
- OS: Windows 10

Steps to reproduce:
1. Run VS Code as administrator 
2. Set the window title to "${rootName}"
3. Observe suffixes are added to the workspace name is the window title

While this suffixes are useful I would like an option to hide them to only display the workspace/folder name. Minimalist, clearer title when switching between several projects opened in VS Code. Plus those suffixes are of no use if VS Code is always launched as admin with always rootName as window title.

Actual window title:
![explorer_CRLYDmycKM](https://user-images.githubusercontent.com/37088908/66253297-43b31100-e766-11e9-9e45-88cf0865ebb6.png)

Would prefer: MyProject

**Comment by stiang** [comment]
I was just about to request this very thing, so I was disappointed to see there was already an issue for it that had been closed.

It would be really nice if there was an alternative to `rootName` that consisted of just the workspace/folder name, nothing else. Like this:

```
hma-admin-web                               <--- yes, good!
hma-admin-web (Workspace) [SSH: srv1]       <--- too much information
```

Might I suggest `rootNameShort` to keep it similar to other title variables? 

From browsing the source code, it looks like this might be possible for me to contribute. Does the closing of this issue mean that a PR adding `rootNameShort` would have no chance of getting merged?

**Comment by misaki-web** [comment]
Duplicate of #145238. The variable `${rootNameShort}` was [added in version 1.75](https://code.visualstudio.com/updates/v1_75#_pull-requests).

**Comment by adyz** [comment]
It seems like this is better, but it still holds the "[Administrator]" thing.

using ` "window.title": "${rootNameShort}",` in my `settings.json` file

**Comment by adamerose** [comment]
It's not that `[Administrator]` is included in `rootNameShort` but it's included in the title regardless of your setting for `window.title`

![image](https://github.com/microsoft/vscode/assets/10884874/f05f8748-fce5-4959-aff9-a550e824ff79)
