### ISSUE TITLE
Open terminal error - cannot type into node terminal

### ISSUE THREAD

**Issue by zamird** [microsoft/vscode#81998]
**Steps to reproduce:**
I opened a new node terminal, and tried to type into it.

**Result:** 
1. No chars were typed into terminal.
2. Scroller jumped.

**See as attachment:** Video screencast of bug.

[2019-10-05 15-23-08.zip](https://github.com/microsoft/vscode/files/3693218/2019-10-05.15-23-08.zip)

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
