### ISSUE TITLE
Alt+Z does not work

### ISSUE THREAD

**Issue by gmikhail** [microsoft/vscode#81991]
Issue Type: <b>Bug</b>

Because Alt+Z (wrapping) overrided by Nvidia Overlay (GeForce Experience) by default

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.35GB free)|
|Process Argv|\\NETBOOK\Users\Mikhail\Desktop\TODO.txt|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
python|ms-|2019.9.34911
csharp|ms-|1.21.4

</details>

**Comment by Tyriar** [comment]
Disable it in the Nvidia software if you want to use it in other apps.
