### ISSUE TITLE
we need a shortcut to escape/close the control palette selection (when auto-selection is activated)

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#81992]
By pressing `ctrl`+`P` the command palette opens. If we keep pressing `ctrl`, we can move the selection down simply by pressing `P`. We only need to release `ctrl` to open the file. It's a great feature but once we are on it, it's difficult to escape (when I don't find the file I search, I often end up opening the random file that is currently selected). 

It's possible to escape the auto selection by pressing `esc` while pressing `ctrl`, but this combination of key isn't really easy.

 It would be much easier to escape the control palette using `shift` (or, even better, using a keyboard shortcut we could choose)

**Comment by chrmarti** [comment]
`shift` would be hard to discover. `esc` seems intuitive.

**Comment by chrmarti** [comment]
Closing as "wont fix" since there already is a way to do that and it is unclear how much value this would add for all but a few who would know about the additional shortcut.
