### ISSUE TITLE
Auto import with alphabetized order

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#81994]
![image](https://user-images.githubusercontent.com/32427260/66253400-5f380f00-e79a-11e9-9a79-4e69cf85b9f6.png)

Currently, VS Code auto-import just add the new module at the end. It will be better if it can auto-import with alphabetized order :)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
