### ISSUE TITLE
Extension docs page gives a 404

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode#82]
This page: https://code.visualstudio.com/docs/extensions linked from the bottom of https://www.visualstudio.com/en-us/products/code-vs.aspx is returning a 404.

**Comment by gregvanl** [comment]
Thanks for reporting this.  It should be fixed shortly.

**Comment by rictic** [comment]
I'm still getting a 404 at the link above.

**Comment by gregvanl** [comment]
Please give it another try, it can take some time for the link changes to propagate.  I can no longer repro the issue.

**Comment by rictic** [comment]
Got it, I wasn't revisiting the original site to get the updated link.

Can confirm this is fixed.
