### ISSUE TITLE
[xml] entities are not highlighted 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#820]
XML highlighting is also not ideal, I would expect the leading `&` and trailing `;` to also be highlighted.

![xml_entity](https://cloud.githubusercontent.com/assets/2193314/11454772/f80321b8-95ee-11e5-9d93-101e5ff97c7f.png)

- [List of XML and HTML character entity references](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)
- [HTML5 named character references](http://www.w3.org/TR/html5/syntax.html#named-character-references)

**Comment by AdamDotNet** [comment]
If I may add, XML as a whole is not highlighting correctly. All text is red. Windows, 0.10.2.

**Comment by Tyriar** [comment]
@AdamDotNet that should be fixed in an upcoming release.

**Comment by aeschli** [comment]
@AdamDotNet It's bug #23

**Comment by AdamDotNet** [comment]
Thanks, sorry I missed the existing bug.

**Comment by aeschli** [comment]
Fix delivered
