### ISSUE TITLE
Renaming files doesn't update the label in a tab if you're just changing the case

### ISSUE THREAD

**Issue by theobourikos** [microsoft/vscode#82004]
- VSCode Version: 1.38.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Rename file in the left project window by just changing the case of any letter
2. If the file is already open, then filename is not updated with the new name.

Workaround:
1. Closing the open file and re-opening it will refresh the tab label

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
![before](https://user-images.githubusercontent.com/900690/66315811-d2669000-e916-11e9-9010-1c5a7e4c0c68.gif)

I cannot reproduce, what are you doing differently?
