### ISSUE TITLE
Rename "Soft Undo" to "Cursor Undo" in the Command Palette

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82008]
There is a **command called "cursorUndo"**, which undo's cursor and selection movements.
In the command palette it is called "Soft Undo".

I think the **name in the command palette should be changed from "Soft Undo" to "Cursor Undo"**.

#### Motivation:

This will make the command more discoverable, and more intuitive for users to figure out what it does.

When I found this command in the command palette, I tried typing "hello" and then using it, but it did nothing, because the cursor hasn't moved since the last edit.
I had to google it to figure out what the command does.

#### Reasoning:

Even though the command also undo's selection changes and not just cursor movements, I think "cursor" is a general term the refers to both "cursor" and "selection".

Also, the command name itself is already "cursorUndo", it makes sense for the name in the command palette to use the same term.

Having "cursor" in the command's name will make it clear it undo's things that the cursor does, such as moving and selecting text.
A user that will find this command in the command palette will most likely attempt to move the cursor and then use the command, and then will understand what it does.

#### System Info:

VSCode Version: 1.38.1
OS: Windows

**Comment by NotWearingPants** [comment]
This issue is different than the suggested duplicates.

**Comment by BLJS2warchief** [comment]
Can I work on this

**Comment by NotWearingPants** [comment]
Even the post and comments when it was named "Soft Undo" agree it should have the word "cursor" or "selection" - https://github.com/microsoft/vscode/issues/50689

**Comment by NotWearingPants** [comment]
Now that `cursorRedo` command was merged (PR#82620) it also should have its label renamed from "Soft Redo" to "Cursor Redo".
