### ISSUE TITLE
Rename does not update a folders mtime (only works for files)

### ISSUE THREAD

**Issue by KevinMongiello** [microsoft/vscode#82015]
Issue Type: <b>Bug</b>

1) Open finder, locate a folder / file that has a 'Date Modified' property set to 1+ days ago.
2) Open the folder/file in VSCode.  Right click > Rename file or folder.
3) Switch back to file/folder in Finder.  Right click > Get Info.
See that 'Date Modified' has not changed.

If I change the name of the file /folder via Finder, that metadata property changes.  I would expect the same behavior when editing the file via VSCode.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (7.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Yeah I can see in our code that we have an explicit check to not change the mtime for folders after a move:

```ts
async function updateMtime(path: string): Promise<void> {
	const stat = await lstat(path);
	if (stat.isDirectory() || stat.isSymbolicLink()) {
		return Promise.resolve(); // only for files
	}

	const fd = await promisify(fs.open)(path, 'a');
	try {
		await promisify(fs.futimes)(fd, stat.atime, new Date());
	} catch (error) {
		//ignore
	}

	return promisify(fs.close)(fd);
}
```

@joaomoreno was this maybe from you? must be incredibly old, but I see no reason why a folder would not get an updated `mtime`, if that is the native behaviour.

**Comment by bpasero** [comment]
@KevinMongiello to confirm, this works fine for files right?

**Comment by bpasero** [comment]
I cannot reproduce a change in `mtime` neither on macOS nor on Windows using Finder or Windows explorer, so I am not sure we should change this. Arguably we should have maybe never changed the `mtime` for files either, but I am not brave enough to change this now.
