### ISSUE TITLE
Webview embedding of YouTube video worked in May 2019, but no longer does

### ISSUE THREAD

**Issue by mtkennerly** [microsoft/vscode#82012]
- VSCode Version: 1.38.1
- OS Version: Windows 10

I have [an extension](https://marketplace.visualstudio.com/items?itemName=mtkennerly.gfmarkup) that, at least as recently as May 2019, was able to embed YouTube videos in a webview using this code:

```
<iframe width="480" height="270" class="video" src="https://www.youtube.com/embed/S-thTTqefls" frameborder="0"></iframe>
```

It used to show a thumbnail, but now shows an error about not recognizing the video format. I did see a similar issue, #54097, attributed to VSCode's Electron build not having ffmpeg, but that issue was posted in July 2018, almost a year before I released my extension with functional embedding. I just wanted to confirm if this is the same underlying issue or if something else changed in VSCode? (If there wasn't a change on the VSCode side, then I suppose YouTube must no longer be offering a format that VSCode supports.)

You can see an example of how it used to look on the extension's page in the animated demo. Here's a still:

> ![image](https://user-images.githubusercontent.com/4934192/66260656-4d9d3a00-e78f-11e9-89aa-e468676d39ce.png)

But now it just shows this:

> ![image](https://user-images.githubusercontent.com/4934192/66260641-03b45400-e78f-11e9-8132-93a4cbfe668e.png)

Does this issue occur when all extensions are disabled?: Yes (except for running my extension in VSCode debugger)

**Comment by mjbvz** [comment]
Same as #54097. VS Code's electron version has changed since then which could have caused this, or youtube may have changed something on their side. However video has never officially been supported inside of webviews due to our lack of ffmpeg
