### ISSUE TITLE
File resolution in "node_modules/.bin" should be relative to the module

### ISSUE THREAD

**Issue by connorjclark** [microsoft/vscode#82014]
Issue Type: <b>Feature Request</b>

For an example, `yarn add nyc` and open `node_modules/.bin/nyc`. The relative requires do not link to the files that are required at runtime.

Would need to know which module installed each bin. Probably by parsing all the package.json's in `node_modules`. After a quick glance, I see there is not a way to query yarn or npm for this information.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
It's not clear what you're asking here, can you give more details? If this a problem with yarn, npm or vscode?

**Comment by connorjclark** [comment]
`node_modules/.bin/nyc`:
![image](https://user-images.githubusercontent.com/4071474/66336325-b56b9600-e8f1-11e9-8fbb-bc6edb87fe20.png)

CMD + click normally opens the file. Node (somehow) resolves this fine at runtime (`node node_modules/.bin/nyc --help` works fine), but VSCode doesn't know to look in `node_module/bin` when resolving the highlighted relative path.

I would expect VSCode to know how to resolve files just like how Node does.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request for this upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by connorjclark** [comment]
Can you just [move](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) this issue to that repo?

**Comment by mjbvz** [comment]
Please file upstream and fill out their issue template
