### ISSUE TITLE
Terminal folders (unlike files) open new instance/window

### ISSUE THREAD

**Issue by hedefalk** [microsoft/vscode#82010]
I use the feature in iterm2 to link from external builds into vscode for errors. It works fine for absolute paths to files - if I have a current workspace open containing this file, that one is focused.

However, with folder paths like the ones produced by my current webpack/marko build:

```
ERROR in ../web/src/marko/pages/admin/users.component.js
Module not found: Error: Can't resolve 'web/services/users' in '/Users/viktor/dev/projects/kb-frontend/packages/web/src/marko/pages/admin'
 @ ../web/src/marko/pages/admin/users.component.js 2:15-44
 @ ../web/src/marko/pages/admin/users.marko
 @ ../web/src/marko/index.marko
 @ ../web/src/marko/marko-bootstrap.js
 @ multi @babel/polyfill ../web/src/marko/marko-bootstrap ../web/src/materialize/kb-materialize.scss
```

If I click the absolute path to the folder, a new window of vscode is launched instead of my current workspace even though it is contained there.

My iterm2 settings look like this:

![image](https://user-images.githubusercontent.com/116520/66259726-e5f9e580-e7b4-11e9-8741-f9b8d8d048c3.png)

It would be awesome if vscode could handle folders just like it handles files and putting me into my existing session instead of a new.

**Comment by Tyriar** [comment]
To clarify, this is when you're in an _external_ terminal, clicking on an absolute _folder_ path such as `/Users/viktor/dev/projects/kb-frontend/packages/web/src/marko/pages/admin`, and it opens a new VS Code window?

**Comment by hedefalk** [comment]
@Tyriar Exactly. Files works fine, re-using my existing workspace, but folders always open new windows.

**Comment by Tyriar** [comment]
What do you expect to happen? I'm assuming the window you have opened is `/Users/viktor/dev/projects/kb-frontend` and you want to do something within that window?

**Comment by hedefalk** [comment]
Really good question actually :)

Well, since it works so well with files - a link to a file contained within current session focuses that file in existing window, it would be really awesome if the same could happen with folders.

If it's a folder contained within an existing/open workspace, I'd like that to be focused in tree-view?

And yes, `/Users/viktor/dev/projects/kb-frontend` is a root folder in my existing workspace.

**Comment by Tyriar** [comment]
@isidorn @bpasero what are your thoughts on having `code <folder>` focus and reveal the folder in the explorer when `<folder>` is a sub-directory of an already opened folder?

**Comment by hedefalk** [comment]
I guess this is a bunch of unfortunate formats from the build where all the files are relative and only a folder is absolute so I have no way to get back to vscode from the external build which I'm used/spoiled to be able to… Maybe this is not super a common scenario…

**Comment by isidorn** [comment]
@Tyriar makes sense to me. Currently I think we just open an already opened folder.
Just use [`ExplorerService.select`](https://github.com/Microsoft/vscode/blob/a51693925e032b65c8facd046ec58a2f5827bfe5/src/vs/workbench/contrib/files/common/files.ts#L67)

**Comment by Tyriar** [comment]
We could do the same for integrated terminal links in https://github.com/microsoft/vscode/issues/29499

**Comment by bpasero** [comment]
Maybe needs to be another option in our setting for this:

![image](https://user-images.githubusercontent.com/900690/66337216-0a81c900-e93f-11e9-9af6-c35a4ef229c0.png)

**Comment by Tyriar** [comment]
@bpasero maybe, but I would think this is good default behavior (-n can always force?).

**Comment by bpasero** [comment]
I am not sure I want to change that behavior for all users. This could easily backfire.
