### ISSUE TITLE
Explore project wide builder for TS

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8201]
Explore a project wide builder for TypeScript. Things to do:
- decide where such a builder is best integrated. Options are: tsserver, wrapper server, or own extension
- decide on feature set (diagnostics, emit, ...)
- decide on supported module systems (commonjs, amd, internal, ...)

The builder should be able to scale to large workspaces (e.g. like VS Code)
### Definition of Done
- [ ] Test Plan Item created
- [ ] Release notes updated

**Comment by dbaeumer** [comment]
We decided to do the work in the tsserver. The branch is: https://github.com/Microsoft/TypeScript/tree/dbaeumer/9125

**Comment by mjbvz** [comment]
Closing in favor of #7342 since this was an exploration plan item
