### ISSUE TITLE
Debugging output is too long in python. I hope the output can be automatically line-wrapped.

### ISSUE THREAD

**Issue by 1470391328** [microsoft/vscode#82017]
🚨 The issue tracker is not for questions 🚨
Debugging output is too long in python such as list,tuple,dict and so on. I hope the output can be automatically line-wrapped according to the width of the debugging window。

![image](https://user-images.githubusercontent.com/33288114/66263262-25125000-e822-11e9-9489-5d56867d2aaa.png)

**Comment by 1470391328** [comment]
Debugging output is too long to read

**Comment by Tyriar** [comment]
The `>` button on the left allows you to expand, if it wrapped automatically it could take up a huge amount of lines.
