### ISSUE TITLE
Please add support for html, css and javascript intellisense in `html.erb` file!

### ISSUE THREAD

**Issue by guledali** [microsoft/vscode#82025]
### My enviroment 

- VSCode Version: 1.38.1
- OS Version: 10.14.5

### Summary

I'm not getting the default intellense support for javascript, css or even html in a `.html.erb` file.
### Expected behaviour 
<img width="1073" alt="Screen Shot 2019-10-06 at 12 47 17 PM" src="https://user-images.githubusercontent.com/20647282/66267995-a07efc00-e838-11e9-80dc-cd3b4126342d.png">

_**Here you can see the red squarebox next to the value**_

### Actual behaviour 
<img width="1073" alt="Screen Shot 2019-10-06 at 12 51 03 PM" src="https://user-images.githubusercontent.com/20647282/66268026-0b303780-e839-11e9-951f-dae73209e6da.png">

I'm sorry vscode team but I consider this to be a bug and it's unacceptable bug that slows down my workflow!

**Comment by octref** [comment]
You can try to configure `html.erb` files to be `html` files with either:

- F1 -> Change Language Mode -> `html`
- In `files.associations` setting, set `"*.html.erb": "html"`

Not all features are promised to work correctly though, as we don't support ERB files out of the box. You might try one of the ERB extensions: https://marketplace.visualstudio.com/search?term=erb&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by guledali** [comment]
What!, why did you close it???

**Comment by octref** [comment]
Because there's **no official support for erb file**. You can install an extension to support it or make it recognized as HTML file to get partial HTML editing features.
