### ISSUE TITLE
Cannot attach to root process

### ISSUE THREAD

**Issue by DavHack** [microsoft/vscode#82028]
- VSCode Version: Newest (Couldn't figure how to check VSCode version in MacOS).
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Launch the debuggable process as root.
2.Launch VSCode as normal user privilege.
3. Try to attach from VSCode to the debuggable process.
4. It will elevate you with password prompt.
5. Fail to attach.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@DavHack if you use VSCode's  "Help > Report Issue" menu action to file an issue, all relevant  information will be added to the github issue automatically. Alternatively you can use VS Code's "About" menu action to find the version.

**Comment by DavHack** [comment]
@weinand 
Sure, new ticket submitted here:
https://github.com/microsoft/vscode/issues/82680
