### ISSUE TITLE
Git: Errors when staging changes in new repository

### ISSUE THREAD

**Issue by cdoublev** [microsoft/vscode#82026]
- VSCode Version: 1.38.1
- OS Version: Windows 10 v1903

Steps to Reproduce:

1. Add a folder in workspace
2. Init a git repository in this folder
3. Create a new file in this folder
4. Stage change from the source control providers (scp) panel
5. Append/change content in the file
6. Stage change by using the blue icon in the left gutter (not from scp panel)

An error (OS) window pops up with the message "Git fatal: Not a valid object name HEAD".

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
I don't even see a gutter decoration.

**Comment by cdoublev** [comment]
Thank you for looking at this. It seems that the file needs to have an extension in order to have the gutter indicators from git.

**Comment by anirudhrb** [comment]
Since the repo is empty, there is no HEAD. That's what causes the error. I have attempted a PR (#82995). @joaomoreno please have a look.
