### ISSUE TITLE
Explorer shortcut for linux seems to some times type a letter "E" in window

### ISSUE THREAD

**Issue by henrytseng** [microsoft/vscode#82037]
Open up a new file with side pane closed.   Navigate down the file and press Ctl-E to open the side Explorer up.  A letter "E" is typed.

**Comment by Tyriar** [comment]
The shortcut for the explorer is ctrl+shift+e?

**Comment by henrytseng** [comment]
Yes, my mistake. I'm pressing the right sequence.

**Comment by isidorn** [comment]
Can not reproduce. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by henrytseng** [comment]
Seems like vscode insiders fixes it.

**Comment by isidorn** [comment]
Glad to hear, closing then.
Make sure that no extension breaks your flow in stable. I would check them.
