### ISSUE TITLE
October Issue Grooming - review, categorization, assignment

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#82032]
During October we groom our open issues.

## Preparation
- [x] review [issue types](https://github.com/microsoft/vscode/wiki/Issues-Triaging#categorizing-issues)
- [x] review [feature areas](https://github.com/Microsoft/vscode/wiki/Feature-Areas)
- [x] review [issue grooming](https://github.com/Microsoft/vscode/wiki/Issue-Grooming)

## Review Guidelines

In the first pass reviewing the issues has a higher priority than fixing issues. Clearly, we'll use common sense, i.e. we'll make easy fixes on the fly. During review please make sure:

- to close obsolete/fixed issues and mark duplicates as appropriate,
- that each issue has a [type](https://github.com/microsoft/vscode/wiki/Issues-Triaging#categorizing-issues) 
- that each issue is assigned to a [feature area](https://github.com/Microsoft/vscode/wiki/Feature-Areas)
- that bugs that you plan to fix during October are assigned to the October milestone. Since the main focus is on housekeeping, be conservative.
- to close out-of-scope feature requests assign the `*out-of-scope` label. Take into account that we'll have a "polishing, take care of smaller issues" milestone in early 2020. There is no value in keeping issues open that don't have any realistic chance of being addressed.
- close bugs as "won't fix" if there is no cost-benefit balance. It's not that we don't care about users who are affected by an issue but, for example, if the fix is so involved that we risk regressions for many, fixing is not a reasonable choice.

Otherwise the normal rules apply:
- assign the `important` label to issues that
  -  result in data loss
  - a breakage of extension
  - critical security, performance issues
  - UI issue that makes a feature unusable
- issues that the community can take up should be labeled as `help-wanted`
- if issues are suitable for beginners you can also add the `good-first-issue` label and add code pointers that help beginners to get started with a PR
- feature requests that should be implemented as extensions should be labeled `extensions-candidate` and be closed

## Tracking

Please make sure that you also do this grooming in our satellite repositories.

### Issues assigned to you
- [x] @aeschli 
- [ ] @alexandrudima
- [x] @alexr00
- [ ] @bowdenk7
- [x] @bpasero
- [ ] @chrisdias
- [x] @chrmarti
- [x] @chuxel
- [x] @dbaeumer
- [x] @deepak1556
- [x] @egamma
- [ ] @fiveisprime
- [x] @gregvanl
- [ ] @isidorn
- [x] @joaomoreno
- [x] @jrieken
- [x] @kieferrm
- [x] @misolori
- [x] @mjbvz
- [x] @octref
- [x] @rebornix
- [x] @rmacfarlane
- [x] @roblourens
- [ ] @sana-ajani
- [ ] @sandy081
- [x] @sbatten
- [ ] @stevencl
- [x] @tyriar
- [x] @weinand

### Issues assigned to feature areas but without owner
- [ ] [`api`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aapi)
- [x] [`api-finalization`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aapi-finalization)
- [x] [`api-proposal`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aapi-proposal)
- [x] [`breadcrumbs`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Abreadcrumbs)
- [x] [`callhierarchy`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acallhierarchy)
- [x] [`color-palette`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acolor-palette)
- [x] [`comments`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acomments)
- [ ] [`config`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aconfig)
- [x] [`context-keys`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acontext-keys)
- [x] [`css-less-scss`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Acss-less-scss)
- [x] [`debug`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adebug)
- [x] [`debug-console`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adebug-console)
- [x] [`dialogs`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adialogs)
- [x] [`diff-editor`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adiff-editor)
- [x] [`dropdown`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Adropdown)
- [x] [`editor`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor)
- [x] [`editor-autoclosing`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-autoclosing)
- [x] [`editor-autoindent`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-autoindent)
- [x] [`editor-bracket-matching`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-bracket-matching)
- [x] [`editor-clipboard`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-clipboard)
- [x] [`editor-code-actions`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-code-actions)
- [x] [`editor-code-lens`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-code-lens)
- [x] [`editor-color-picker`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-color-picker)
- [x] [`editor-columnselect`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-columnselect)
- [ ] [`editor-commands`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-commands)
- [x] [`editor-comment-commands`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-comment-commands)
- [x] [`editor-contrib`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-contrib)
- [ ] [`editor-core`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-core)
- [x] [`editor-drag-and-drop`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-drag-and-drop)
- [ ] [`editor-error-widget`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-error-widget)
- [x] [`editor-find`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-find)
- [ ] [`editor-folding`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-folding)
- [ ] [`editor-hover`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-hover)
- [x] [`editor-ime`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-ime)
- [x] [`editor-indent-guides`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-indent-guides)
- [x] [`editor-input`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-input)
- [ ] [`editor-insets`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-insets)
- [x] [`editor-minimap`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-minimap)
- [ ] [`editor-multicursor`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-multicursor)
- [x] [`editor-parameter-hints`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-parameter-hints)
- [x] [`editor-render-whitespace`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-render-whitespace)
- [x] [`editor-rendering`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-rendering)
- [ ] [`editor-scrollbar`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-scrollbar)
- [ ] [`editor-symbols`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-symbols)
- [x] [`editor-textbuffer`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-textbuffer)
- [ ] [`editor-theming`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-theming)
- [ ] [`editor-wordnav`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-wordnav)
- [ ] [`editor-wrapping`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aeditor-wrapping)
- [x] [`emmet`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aemmet)
- [ ] [`error-list`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aerror-list)
- [x] [`explorer-custom`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aexplorer-custom)
- [ ] [`extension-host`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aextension-host)
- [ ] [`extensions`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aextensions)
- [x] [`extensions-development`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aextensions-development)
- [x] [`file-decorations`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-decorations)
- [x] [`file-encoding`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-encoding)
- [x] [`file-explorer`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-explorer)
- [x] [`file-glob`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-glob)
- [x] [`file-guess-encoding`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-guess-encoding)
- [x] [`file-io`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-io)
- [x] [`file-watcher`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afile-watcher)
- [x] [`font-rendering`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Afont-rendering)
- [x] [`formatting`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aformatting)
- [x] [`git`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Agit)
- [x] [`git-merge`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Agit-merge)
- [x] [`gpu`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Agpu)
- [ ] [`grammar`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Agrammar)
- [ ] [`grid-view`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Agrid-view)
- [x] [`html`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ahtml)
- [x] [`i18n`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ai18n)
- [x] [`icon-brand`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aicon-brand)
- [x] [`icons-product`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aicons-product)
- [ ] [`install-update`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ainstall-update)
- [x] [`integrated-terminal`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aintegrated-terminal)
- [x] [`integrated-terminal-conpty`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aintegrated-terminal-conpty)
- [x] [`integrated-terminal-winpty`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aintegrated-terminal-winpty)
- [x] [`integration-test`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aintegration-test)
- [x] [`intellisense-config`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aintellisense-config)
- [x] [`ipc`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aipc)
- [x] [`issue-bot`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aissue-bot)
- [x] [`issue-reporter`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aissue-reporter)
- [x] [`javascript`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ajavascript)
- [x] [`json`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ajson)
- [ ] [`keybindings`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Akeybindings)
- [ ] [`keybindings-editor`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Akeybindings-editor)
- [ ] [`keyboard-layout`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Akeyboard-layout)
- [x] [`L10N`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3AL10N)
- [ ] [`label-provider`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alabel-provider)
- [ ] [`languages-basic`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alanguages-basic)
- [ ] [`languages-diagnostics`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alanguages-diagnostics)
- [ ] [`languages-guessing`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alanguages-guessing)
- [x] [`layout`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alayout)
- [x] [`list`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alist)
- [x] [`log`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Alog)
- [x] [`markdown`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Amarkdown)
- [ ] [`marketplace`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Amarketplace)
- [x] [`menus`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Amenus)
- [x] [`merge-conflict`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Amerge-conflict)
- [x] [`outline`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aoutline)
- [ ] [`output`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aoutput)
- [x] [`perf`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aperf)
- [x] [`perf-bloat`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aperf-bloat)
- [x] [`perf-startup`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aperf-startup)
- [x] [`php`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aphp)
- [x] [`portable-mode`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aportable-mode)
- [x] [`proxy`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aproxy)
- [x] [`quick-pick`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aquick-pick)
- [x] [`references-viewlet`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Areferences-viewlet)
- [x] [`release-notes`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Arelease-notes)
- [x] [`remote`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aremote)
- [x] [`rename`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Arename)
- [x] [`samples`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asamples)
- [x] [`scm`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ascm)
- [x] [`screencast-mode`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ascreencast-mode)
- [x] [`search`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asearch)
- [ ] [`search-replace`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asearch-replace)
- [ ] [`semantic-coloring`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asemantic-coloring)
- [x] [`settings-editor`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asettings-editor)
- [ ] [`shared-process`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Ashared-process)
- [x] [`simple-file-dialog`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asimple-file-dialog)
- [x] [`smart-select`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asmart-select)
- [x] [`smoke-test`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asmoke-test)
- [x] [`snap`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asnap)
- [x] [`snippets`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asnippets)
- [x] [`splitview`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asplitview)
- [x] [`suggest`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Asuggest)
- [x] [`tasks`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atasks)
- [ ] [`telemetry`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atelemetry)
- [ ] [`themes`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Athemes)
- [ ] [`titlebar`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atitlebar)
- [ ] [`tokenization`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atokenization)
- [x] [`trackpad/scroll`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atrackpad/scroll)
- [x] [`tree`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atree)
- [x] [`typescript`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Atypescript)
- [ ] [`unit-test`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aunit-test)
- [x] [`uri`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Auri)
- [x] [`ux`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aux)
- [ ] [`variable-resolving`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Avariable-resolving)
- [ ] [`VIM`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3AVIM)
- [x] [`vscode-build`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Avscode-build)
- [x] [`vscode-website`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Avscode-website)
- [ ] [`web`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aweb)
- [x] [`webview`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Awebview)
- [ ] [`workbench-cli`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-cli)
- [ ] [`workbench-diagnostics`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-diagnostics)
- [x] [`workbench-dnd`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-dnd)
- [x] [`workbench-editor-grid`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-editor-grid)
- [x] [`workbench-editors`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-editors)
- [x] [`workbench-electron`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-electron)
- [x] [`workbench-feedback`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-feedback)
- [x] [`workbench-history`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-history)
- [x] [`workbench-hot-exit`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-hot-exit)
- [ ] [`workbench-launch`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-launch)
- [x] [`workbench-link`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-link)
- [x] [`workbench-multiroot`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-multiroot)
- [x] [`workbench-notifications`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-notifications)
- [ ] [`workbench-os-integration`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-os-integration)
- [ ] [`workbench-rapid-render`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-rapid-render)
- [x] [`workbench-run-as-admin`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-run-as-admin)
- [x] [`workbench-state`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-state)
- [x] [`workbench-status`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-status)
- [x] [`workbench-tabs`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-tabs)
- [x] [`workbench-touchbar`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-touchbar)
- [ ] [`workbench-views`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-views)
- [x] [`workbench-welcome`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-welcome)
- [x] [`workbench-window`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-window)
- [ ] [`workbench-zen`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkbench-zen)
- [ ] [`workspace-edit`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkspace-edit)
- [ ] [`workspace-symbols`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aworkspace-symbols)
- [ ] [`zoom`](https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Azoom)

### Other issues
- [x] ensure we don't have any issues assigned to people who are no longer on the team @kieferrm

**Comment by lannonbr** [comment]
As I did last year with this topic, my issue tracker site is still up and running so it's a good visual reference to see progress: https://vscode-issue-tracker.netlify.com/

I'm in talks with @chrisdias on an updated version of the tracker to have even more datapoints on the site (tracking closed issue count, PRs, stars, etc).
