### ISSUE TITLE
Impossible to rebind command+r

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/vscode#82034]
- VSCode Version: 1.38.1
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Add the following keybindings:
    ```json
    {
        "key": "cmd+r",
        "command": "-workbench.action.reloadWindow",
        "when": "isDevelopment"
    },
    {
        "key": "cmd+r",
        "command": "editor.action.rename",
        "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
    }
    ```

2. Try to use `cmd+r` to rename a symbol. Nothing happens. Changes the keyboard shortcut to anything besides `cmd+r` and the renaming works. VSCode shows no other commands bound to `cmd+r`. Total guess: perhaps this has to do with the [hardcoded check here](https://github.com/microsoft/vscode/blob/c617db19b08bfdae8e2c540470bf82dd405c3895/src/bootstrap-window.js#L182)?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I can rebind it fine with this:

```
{ "key": "cmd+r", "command": "workbench.action.terminal.toggleTerminal" }
```

I think the issue is that the rename command probably only works when you're focusing the explorer (just a guess).
