### ISSUE TITLE
Support for inferring the possible types of parameters from the default value using ES6

### ISSUE THREAD

**Issue by redblue9771** [microsoft/vscode#82030]
simply put,

```JavaScript
function f( a=0 ) {
   console.log(a)
}
```
When we give **`a`** a default value of 0, can we **simply** infer that **`a`** parameter may be a number?

**Comment by mjbvz** [comment]
What isn't working?

<img width="406" alt="Screen Shot 2019-10-07 at 9 23 15 AM" src="https://user-images.githubusercontent.com/12821956/66329872-2310c580-e8e4-11e9-8116-6b68896155ec.png">


/needsMoreInfo

**Comment by redblue9771** [comment]
Sorry,  it is working,  the extra plugin slows it down.
