### ISSUE TITLE
Tree fade out remain after escaping rename file

### ISSUE THREAD

**Issue by sebdoucet** [microsoft/vscode#82048]
- VSCode Version: 1.38.1
- OS Version: Window 10

Steps to Reproduce:

1. F2 to rename a file
2. Escape

The tree fade out activated during rename is not remove when escaping.

You have to reload or rename a file to remove this.

**Comment by isidorn** [comment]
Fixed in latest. Checkout insiders and the next stable release. If you still see this let us know and we will reopen thanks.
