### ISSUE TITLE
Language specific indentation doesn't seem to work

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#82044]
Issue Type: <b>Bug</b>
With the following setup vscode still shows indentation of tabSize 2 for yml files. Same for html or twig and so on.
```
"editor.autoIndent": true,
"editor.detectIndentation": false,
"editor.insertSpaces": true,
"editor.tabSize": 2,
"[yaml]": {
    "editor.tabSize": 4,
    "editor.defaultFormatter": "redhat.vscode-yaml"
  },
```

VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:23:20.797Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cucumberautocomplete|ale|2.14.1
cypress-snippets|and|1.2.0
atlascode|atl|2.0.2
vscode-custom-css|be5|3.0.8
color-info|bie|0.5.1
markdown-mermaid|bie|1.2.0
mermaid-markdown-syntax-highlighting|bpr|1.0.1
better-toml|bun|0.3.2
twigcs|cer|1.1.0
path-intellisense|chr|1.4.2
scss-grammar-extended|dan|1.0.0
vscode-eslint|dba|1.9.1
hsnips|dra|0.0.15
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.1.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.3.0
file-icons|fil|1.0.19
vscode-firefox-debug|fir|2.3.4
vscode-architect|gil|0.1.0
vscode-pull-request-github|Git|0.12.0
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.158
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.3
plantuml|jeb|2.12.1
polacode-2019|jef|0.5.1
browsersync|jer|2.1.0
vscode-peacock|joh|3.1.5
vscode-commitizen|Kni|0.8.3
twig-language-2|mbl|0.8.10
plantumlpreviewer|Meb|0.6.0
git-graph|mhu|1.16.0
auto-barrel|mik|1.6.5
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
vscode-remote-extensionpack|ms-|0.17.0
references-view|ms-|0.0.30
debugger-for-chrome|msj|4.12.0
ts-prop-dag|nat|1.0.6
vscode-versionlens|pfl|0.24.0
rpa-eslint-snippets|rav|0.0.2
vscode-yaml|red|0.5.3
explorer-exclude-vscode-extension|Red|1.2.0
elastic|ria|0.13.3
preview-vscode|sea|2.0.3
code-settings-sync|Sha|3.4.3
vscode-barreler|shi|0.0.1
sourcegraph|sou|1.0.14
cucumber|ste|0.12.0
gif-code-snippet|sub|1.0.2
vscode-mermaid-editor|tom|0.4.3
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
snippet|vsc|0.7.0
vim|vsc|1.11.0
vscode-mermaid-preview|vst|1.2.0
quokka-vscode|Wal|1.0.254
literally-html|web|0.1.1
highlight-bad-chars|wen|0.0.3

(1 theme extensions excluded)

</details>

**Comment by bm-stschneider** [comment]
Okay it seems related to #80848, but as you can see I used a different formatter so how can other formatters interfere?

**Comment by bm-stschneider** [comment]
Also even when disabling prettier I still have it for html

**Comment by bm-stschneider** [comment]
This is also odd, vscode is using some other indentation as configured
![image](https://user-images.githubusercontent.com/30625381/66304507-a12d9600-e8fd-11e9-8b59-f6bb916df643.png)

**Comment by Tyriar** [comment]
Changing the tab size worked fine for me with:

```
  "[yaml]": {
    "editor.detectIndentation": false,
    "editor.tabSize": 4
  }
```

![image](https://user-images.githubusercontent.com/2193314/66311693-e46b1300-e8c3-11e9-9dec-7a2601f7fcb2.png)

Are you sure it happens after disabling all extensions?

**Comment by bm-stschneider** [comment]
With prettier, yes, without no. So how do I find out which extension overrides the setting?

**Comment by bm-stschneider** [comment]
Also, if I reload with extensions, the correct indentation is kept when the file is still open. Reopen will get me the wrong indentation again.

**Comment by Tyriar** [comment]
> With prettier, yes, without no. So how do I find out which extension overrides the setting?

Doesn't that mean it's prettier? You can report to them, I suspect it's by design though.

**Comment by bm-stschneider** [comment]
no, since I removed prettier already.

**Comment by alexandrudima** [comment]
@bm-stschneider You have 68 installed extensions. Anyone of the extensions that have code and are activated (you can find them via F1 > Show Running Extensions) can exercise vscode API to change the indentation settings.

Given EditorConfig is an extension that is built to tweak indentation settings based on a global `.editorconfig` file, my money is on that one.

**Comment by bm-stschneider** [comment]
Is there a hierarchy who has priority on changing such values?

**Comment by bm-stschneider** [comment]
It seems editorconfig was a good hint though. It seems to resolve the issue. Although I don't even have an .editorconfig file anywhere, which is weird.

**Comment by alexandrudima** [comment]
@bm-stschneider I guess that is the built-in default they fall back to.

> Is there a hierarchy who has priority on changing such values?
There is no hierarchy. We offer imperative API to change the indentation and whichever extension calls that API will change the indentation.
