### ISSUE TITLE
typescript.reportStyleChecksAsWarnings doesn't work

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82042]
This issue occurs in Insiders v1.39.0

- VSCode Version: 1.39.0
- OS Version: macOS 10.14.6

Steps to Reproduce:
1. On an empty folder, initialize npm package.json with `npm init --yes`
2. Install development dependencies with:
    - `npm i -D eslint`
    - `npm i -D typescript`
    - `npm i -D @typescript-eslint/parser`
    - `npm i -D @typescript-eslint/eslint-plugin@latest`
3. Initialize eslintrc.json with `node_modules/.bin/eslint --init`
4. Copy `"scripts": { "lint": "eslint ./*.ts ./*.js" }` to package.json
5. Create an index.ts file with the following contents:

        const unusedVariable = 'Hello world';
        
        function f() {
    	    const message = 'I like logs';
        	for (let i = 0; i < 5; i++) {
        		console.log(message);
        	}
        }

6. Run `npm --silent run lint` to check that it works correctly and gives out two errors:
        
        1:7   error  'unusedVariable' is assigned a value but never used  no-unused-vars
        3:10  error  'f' is defined but never used                        no-unused-vars
        
6. Install the [ESLint extention][1]
7. Copy the following ESLint-contributed settings to your  VS Code's settings.

        "eslint.lintTask.enable": true,
    	"eslint.validate": [
    		"javascript",
    		"javascriptreact",
    		"typescript"
    	]

8. TS files should now be automatically linted and problems will show up in the Problems panel.

Great! However, as per this [PR][2], the `typescript.reportStyleChecksAsWarnings` should change the following style errors into warnings:

- `--noUnusedLocals`
- `--noUnusedParameters`
- `--noImplicitReturns`
- `--noFallthroughCasesInSwitch`
- `--allowUnusedLabels`
- `--allowUnreachableCode`

**But that doesn't work.** The only way, that I know of, to change those errors into warnings is changing ESLint's rules inside the `.eslintrc.json` file, like for example:

    "rules": {
    	"no-unused-vars": [
    		"warn",
    		{
    			"vars": "all",
    			"args": "after-used",
    			"ignoreRestSiblings": false
    		}
    	]
    }

  [1]: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
  [2]: https://github.com/microsoft/vscode/pull/37616

Does this issue occur when all extensions are disabled?
Can't reproduce without the ESlint extention

**Comment by mjbvz** [comment]
Are the errors from eslint? That setting only effects errors/warnings generated by TypeScript itself

**Comment by andrecasal** [comment]
Yes. But now I'm confused. How do you get the errors/warnings the `typescript.reportStyleChecksAsWarnings` refers to without a linter? I've just created a typescript project with the following tsconfig.json
```
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"noUnusedLocals": true
	},
	"compileOnSave": true,
	"typeAcquisition": {
		"enable": false
	}
}
```

and I get no warnings or errors for this index.ts file:
```
const unusedVariable = "Hello world";


function f() {
	const message = "I like logs";
	for (let i = 0; i < 5; i++) {
		console.log(message);
	}
}
```
Wasn't VS Code supposed to report a warning for that unused variable?

**Comment by mjbvz** [comment]
In your example, `unusedVariable` is in the global scope. TS considers this being reachable while eslint may not.

If you make your file into a module by adding an import or export, you will see the expected behavior

```js
const unusedVariable = "Hello world";

export function f() { }
```


Closing as as-designed

**Comment by andrecasal** [comment]
Got it, thank you @mjbvz!
