### ISSUE TITLE
Snippets can't be called inside quotes (single or double)

### ISSUE THREAD

**Issue by angusmglfraser** [microsoft/vscode#82041]
- VSCode Version: 1.38.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Create a snippet
2. Try to use the snippet inside any pair of quotes, single or double.

Does this issue occur when all extensions are disabled?: Yes

I saw this issue thread from about a year ago: https://github.com/Microsoft/vscode/issues/38952

The screenshot jrieken is showing is a different behaviour (and I'm kind of annoyed at how rude he was in dismissing and closing the original ticket since he clearly didn't understand what was being described, even after clarification). The things the editor are suggesting are just the strings 'alert', 'bugs' and so on, but not full snippets with tab stops and whatnot. 

I have the following snippet: 
```
        "Text Block": {
		"prefix": ["textblock"],
		"body": [
			"<TextBlock text={$1} />$0"
		]
	}
```

And I can call it outside of a string, like so: 
![image](https://user-images.githubusercontent.com/9136149/66299523-9cf87d00-e8eb-11e9-8ed6-13c2ee87b285.png)
![image](https://user-images.githubusercontent.com/9136149/66299546-a41f8b00-e8eb-11e9-8e73-0403857c18a8.png)

but if I try to call it inside a string, I can't use the snippet: 
![image](https://user-images.githubusercontent.com/9136149/66298641-fd86ba80-e8e9-11e9-92f1-7134bb65c7ac.png)

At best, I can get the editor to suggest the string 'TextBlock' if I'm in a file in which that string appears frequently, but I'm unable to use the whole snippet. 

This behaviour also happens if you are typing after an opening quote that doesn't have a closing quote before the end of the file.

**Comment by jrieken** [comment]
What does "to call it inside a string" means? Do you type and expect snippets/sugestions to show up or do you press Ctrl+Space to show snippets/suggestions?

**Comment by ArturoDent** [comment]
```
 "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  },
```

`"strings": true` is what you are looking for.

**Comment by jrieken** [comment]
@angusmglfraser fyi
