### ISSUE TITLE
Exclude folders from automatic task detection

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82043]
I'd love it if we could have a setting like `tasks.autoDetection.exclude: ["**/.history/**"]` where we could insert directories to exclude automatic task detection from.

I'm using the [local history extension](https://marketplace.visualstudio.com/items?itemName=xyz.local-history) until VS Code implements [that functionality natively](https://github.com/microsoft/vscode/issues/26339) and my `(Shift+Cmd+P) > Tasks > Configure Tasks` and `(Shift+Cmd+P) > Tasks > Run Tasks` [gets polluted](https://imgur.com/VitPIJh) by all the *.json files inside the .history directory.

**Comment by andrecasal** [comment]
It's a different issue from the one suggested.

**Comment by alexr00** [comment]
Does the `"files.exclude"` setting solve this?

**Comment by andrecasal** [comment]
Yes, but that's not a good solution because I want to be able to explore the .history folder.

**Comment by TriMoon** [comment]
@alexr00,
I was about to submit an issue just like this...

In my case i have a subdirectory `templates` with template files that get processed by `sed`, to replace specific strings, to auto generate files in other places.
It's rather weird to be restricted to not use any file extension in this sub-directory just so VSC does not auto-fill it's tasks list...
It is also not an option to use `files.exclude` as the files inside are meant to be edited from within VSC when needed by the coder(s).

**Comment by julien-c** [comment]
I second this. I have a large (several GBs) folder tree inside my project and since adding it, task auto-detection takes a few seconds (when it used to be near-instant).

May I suggest that this at least honors the `search.exclude` setting?

Any other workaround for this? cc @pierrci
