### ISSUE TITLE
Test the Atom JavaScript grammar

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8204]
- [x] @egamma 

Several users have asked for syntax highlighting similar to Atom, in particular for variable and function references (not just declarations). I published a extension containing the Atom grammar to try this out.

- in the extension viewlet search for 'Atom JavaScript Grammar'

**Comment by egamma** [comment]
Tested  with light/dark themes and also compared with the monokai theme in different editors. The grammar is descent.

**Comment by paulirish** [comment]
Not sure what's going on but the extension is not working well for me.

Here's atom & vscode side by side:

![image](https://cloud.githubusercontent.com/assets/39191/16434395/64c4d57e-3d44-11e6-8ef7-85332c4a40e9.png)

**Comment by aeschli** [comment]
What theme are you using?

**Comment by egamma** [comment]
@aeschli @paulirish I can reproduce this when using the Oceanic Next theme. I've filed #8613.
