### ISSUE TITLE
When using jsconfig with baseUrl, alt+click does not work

### ISSUE THREAD

**Issue by SirCameron** [microsoft/vscode#82051]
Hi

So, when I use a jsconfig file with baseUrl defined, VsCode will offer suggestions for paths when importing, but it will not allow me to click the path with alt+click to go to the imported file.

context: javascript + react

steps to reproduce:
- create a react app and add a jsconfig file with baseUrl
- import a component and then alt+click the import.

While I'm here, the path suggestions when typing the import also don't always work.

**Comment by SirCameron** [comment]
what more info could I give?

**Comment by mjbvz** [comment]
Fill out the issue template and provide complete repo steps (with example code)
