### ISSUE TITLE
Replace TSLint with ESLint in ExtensionPack Suggestion on Welcome

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode#82053]
First, thanks for making VSCode soooo awesome! Wouldn't be as productive as I am without it 💙

### Problem: 

Currently, VSCode suggests installing the [TSLint extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) to have support for TypeScript.

However, [TSLint](https://github.com/palantir/tslint) is supposedly going to be deprecated sometime this year. 

![image](https://user-images.githubusercontent.com/3806031/66325136-96faa000-e8db-11e9-8b74-70a38f8755a0.png)

### Proposed Solution:

Change the suggested extension to ESLint instead. This way, we're providing a solution to the community that is future-proof (at least for the foreseeable future) 😄

I'd be happy to open a PR if you were to accept this proposed solution. 

(it looks like this would be a matter of replacing the extension id here: [line 148](https://github.com/microsoft/vscode/blob/e81ee538090aa08b348f61414fcb74548506a2e8/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L148))

**Comment by mjbvz** [comment]
Removing it sounds good. We already stopped recommending tslint for general ts users: #81515

Probably just remove the whole typescript section for now. Setting up eslint for TypeScript is not simple enough at the moment to show on the welcome page in my opinion

**Comment by jsjoeio** [comment]
> Setting up eslint for TypeScript is not simple enough at the moment to show on the welcome page in my opinion

Agree with you there. 

> Can you submit a PR that does that?

Definitely!

**Comment by jsjoeio** [comment]
@mjbvz I noticed you added the "help wanted". I'm planning to submit a PR. Is that a more appropriate label to indicate this issue is in progress or taken?
