### ISSUE TITLE
Emmet completions appearing in JS files

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#82056]
- VSCode Version: 1.38.1
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Have settings like screenshot
2. Type inside .js file

![image](https://user-images.githubusercontent.com/208149/66400044-0908dd00-e9e1-11e9-90f8-5eb558d2f8c3.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by franciscolourenco** [comment]
Doesn't seem to cover the problem

**Comment by mjbvz** [comment]
Please upload the screenshot again

Also this doesn't happen if you disable all extensions?

**Comment by franciscolourenco** [comment]
I realize that the completions are coming from https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion so not vscode related. Closing.
