### ISSUE TITLE
Emmet: emmet actions are not atomically undoable

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8205]
- Execute 'Emmet: update tag' or 'Emmet: delete tag'
- undo

You have to undo more than once to get back to the original state.

**Comment by mrmlnc** [comment]
And  `Expand Abbreviation` by `tab` and `F1` also. 

#### VS Code stable
![2016-06-27_20-07-38](https://cloud.githubusercontent.com/assets/7034281/16388711/faa9bfc0-3ca2-11e6-9944-deb6e689761f.gif)

#### VS Code inside
![2016-06-27_20-08-26](https://cloud.githubusercontent.com/assets/7034281/16388730/154c6490-3ca3-11e6-8d61-fc3ad969d4f5.gif)

**Comment by Tyriar** [comment]
It applies to all commands as far as I'm aware.

**Comment by yisibl** [comment]
@alexandrudima The cursor position is not correct after the selected(used cmd+shift+z).

![demo](http://ww3.sinaimg.cn/mw1024/534b48acgw1f5es77q98gg20a409un2b.gif)
