### ISSUE TITLE
[emmet] Duplicate classname suggestions/completions form emmet/css

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#82050]
- VSCode Version:  1.38.1
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Have emmet suggestions enabled
1. Start typing a classname inside some html

![image](https://user-images.githubusercontent.com/208149/66319198-fb8a1f00-e91c-11e9-9f3f-88a9abf66a12.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by octref** [comment]
Does this repro if you disable all extensions?

Can you provide a minimal reproducible example? Like the text of an HTML file.
