### ISSUE TITLE
Extension host keeps crashing: vscode.json-language-features

### ISSUE THREAD

**Issue by baumatron** [microsoft/vscode#82066]
Issue Type: <b>Bug</b>

Based on console output seems this is an OOM issue, potentially caused by vscode.json-language-features. I have a ~12 MB json file open.

![image](https://user-images.githubusercontent.com/8376410/66352079-c62d0380-e913-11e9-8914-3b711c918043.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.27GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.0
vscode-npm-script|eg2|0.3.9
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|0.18.1
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5
azure-account|ms-|0.8.4
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
debugger-for-edge|msj|1.0.11
vscode-jest|Ort|3.0.2
vscode-hexdump|sle|1.7.2

</details>

**Comment by aeschli** [comment]
The screenshot mentions a cpuprofile file that was created.
If you still have it, please attach it here....

dup of https://github.com/microsoft/vscode/issues/80691
