### ISSUE TITLE
debug console keeps going back to top

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#82069]
Issue Type: <b>Bug</b>

Whenever text is sent to the debug console, it scrolls to the top.  Extremely annoying when I have lots of test results.

Worse, if I evaluate an expression, it scrolls back to the top again

You can see this by F5 running the tests in https://github.com/microsoft/vscode-azurearmtools.git (first run npm install).

VS Code version: Code - Insiders 1.39.0-insider (a655c0836de8b8e06f4d56fa4e581b0ced53f56f, 2019-10-03T05:36:55.111Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.89GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.7.0

</details>

**Comment by isidorn** [comment]
Dup of #81951
Will fix today. Thanks for reporting and for using insiders!
