### ISSUE TITLE
Extension host crashes on diff for EntityFramework snapshot files

### ISSUE THREAD

**Issue by robertsimmons** [microsoft/vscode#82063]
Issue Type: <b>Bug</b>

1. Have an EntityFramework project in git
2. Generate a migration so that the Snapshot file is updated
3. Select that file on the source control tab
4. Crash

Started happening maybe a month or two ago. Note that this is a larger file - about 7k lines. Doesn't happen with extensions disabled, but I'm not sure what I have that's causing issues. Once it crashes.

Once it crashes any logs are gone, but the dev tools shows this:

Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:154
_onExtensionHostCrashed @ extensionService.ts:371
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:146
e.onDidExit @ abstractExtensionService.ts:136
fire @ event.ts:572
_onExtHostProcessExit @ extensionHost.ts:464
_extensionHostProcess.on @ extensionHost.ts:217
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:572
addNotification @ notifications.ts:156
notify @ notificationService.ts:101
prompt @ notificationService.ts:166
_onExtensionHostCrashed @ extensionService.ts:391
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:146
e.onDidExit @ abstractExtensionService.ts:136
fire @ event.ts:572
_onExtHostProcessExit @ extensionHost.ts:464
_extensionHostProcess.on @ extensionHost.ts:217
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
supersharp|cra|0.1.4
angular-schematics|cyr|1.27.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.0
EditorConfig|Edi|0.13.0
prettier-vscode|esb|2.3.0
vscode-firefox-debug|fir|2.3.4
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
dotnet-test-explorer|for|0.7.1
todo-tree|Gru|0.0.158
beautify|Hoo|1.5.0
angular2-switcher|inf|0.2.0
vscode-peacock|joh|3.1.5
docomment|k--|0.1.8
chat|kar|0.22.1
dotnet-core-essentials|Kis|0.0.8
csharpfixformat|Leo|0.0.84
Angular-BeastCode|Mik|8.0.10
prettify-json|moh|0.0.3
mssql|ms-|1.6.0
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.905
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
debugger-for-chrome|msj|4.12.0
syncing|non|3.0.9
angular-console|nrw|8.1.2
vetur|oct|0.22.4
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.1
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
csharp2ts|raf|0.0.22
simontest|Sim|1.5.3
move-ts|str|1.11.5
msbuild-project-tools|tin|0.2.55
vscode-angular-support|vis|0.1.4
markdown-all-in-one|yzh|2.4.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by alexandrudima** [comment]
@robertsimmons Does this reproduce when disabling all extensions? Can you please attach here the two files that you are comparing?

**Comment by robertsimmons** [comment]
@alexandrudima As I said in the report, no, it does not happen once all extensions are disabled

The file is a little over 7000 lines. I'm not comparing 2 files, but this is one when even one line has a change in it, and trying to view the diff in the source control tab. I've attached an obfuscated version of ours.

https://gist.github.com/robertsimmons/bf5ce3ce2c7f01118daac48ca9ecd9ff

**Comment by alexandrudima** [comment]
> As I said in the report, no, it does not happen once all extensions are disabled

Thank you, I am sorry I missed that. I also cannot reproduce a crash without any extensions...

I have seen multiple reports of the `karigari.chat` extension causing crashes. [e.g.](https://github.com/microsoft/vscode/issues/77099#issuecomment-514844205). Could you please attempt to disable it?

If this always crashes for you, could you please contribute to the issue at https://github.com/vsls-contrib/chat/issues/410 to help them finally reproduce...

**Comment by robertsimmons** [comment]
@alexandrudima That seems to be the culprit (or at least one of them). Disabling it stopped it from crashing, but now I'm getting errors in the debugger about the bracket colorizer extension. Progress!

I'll close this bug, share it with the vsls-contrib/chat team, and check out the bracket colorizer plugin's issue page as well.
