### ISSUE TITLE
fails to open 4GB text files

### ISSUE THREAD

**Issue by sumonto** [microsoft/vscode#82068]
- VSCode Version: 1.38.1
- OS Version: Lastest MacOS

Steps to Reproduce:

1. Open a 4+GB system log file
2. VS Code will take for ever to open

Does this issue occur when all extensions are disabled?: Yes

I frequently work with large system dump files glog or vim handle these files very easily
Difficult to open/search using VSCode

**Comment by alexandrudima** [comment]
@sumonto Does it work when killing VSCode and starting it with `code-insiders --max-memory 8000` ?

**Comment by sumonto** [comment]
@alexandrudima Thanks for the suggestion, I am able to open the file with --max-memory...
However if you search for something and then come back and try to edit the search values is extremly slow..

I am glad it does not crash though..

Wondering if you can do something to improve the search experience

**Comment by alexandrudima** [comment]
@sumonto Could you perhaps share with me a program that generates a file like the one you're looking at and a search string. Are you searching using regex? Are you searching using match case?

**Comment by sumonto** [comment]
Hi @alexandrudima my searches are primarily without case, sometimes with regex
The closest I could get was as below, this would genearate ~750KB file
1) https://loremipsum.io/generator/?n=999&t=p
2) Copy the paragraph to dummy.txt
3) cat dummy.txt a2.h >> a2.h
     (a) let this run for 5 seconds you shall have a 4.5 GB file
     (b) Ctrl + C

Also if there is already a file opened with --max... opening another large file freezes the editor, I understand this is a stretch

Thanks for helping!

**Comment by jorgegarciamule** [comment]
I'm opening a 2.4 GB CSV in VSCode (Mac Version: 1.39.1) and I'm getting this error: 

`Unable to open 'some_file.csv': Unable to read file (Error: To open a file of this size, you need to restart and allow it to use more memory).`

I clicked on `Restart with 4096 MB` and the same issue. 

Last week the file opened in a mode without the formatting magic but at least I was able to see it. Then I restarted VSCode, it was updated, and now It doesn't open anymore.

**Comment by rebornix** [comment]
Let's use https://github.com/microsoft/vscode/issues/78394to track and the reason why current implementation doesn't handle it properly is described in https://github.com/microsoft/vscode/issues/78394#issuecomment-544717420 .
