### ISSUE TITLE
invalid syntax on 4th line 

### ISSUE THREAD

**Issue by Mwashington15** [microsoft/vscode#82067]
Issue Type: <b>Bug</b>

hello_world_text = 'Hello World Variable'
print ('Hello World!!!')
print('hello_world_text')
print('hello_world_text')!!!!! duh run the test Mr_robot
print ('hello_world_text')
It shouldn't be invalid but it is. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (10.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.9.34911
remote-wsl|ms-|0.39.5

</details>

**Comment by alexr00** [comment]
Does it reproduce if you disable all extensions?

Please add screen shots of your issue.

**Comment by Mwashington15** [comment]
I will try that first. Thank you! 

Malik Washington M.Ed Candidate Georgia State University. Social Studies Department Chair Dekalb County Public Schools
