### ISSUE TITLE
Test new emmet features

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8207]
Testing #7909

- [x] any platform @Tyriar 

Known limitation #8205 (no atomic undo).

## Features to test

- [x] Emmet preferences/settings (see #7926 for a demo)

For documentation and demos of these features pls see description of #8155.
- [x] Expand Abbreviation
- [x] Balance
- [x] Go to Matching Pair
- [x] Wrap with Abbreviation
- [x] Go to Edit Point
- [x] Select Item
- [ ] ~~Toggle Comment~~ (@Tyriar: "does not seem to be supported #8452")
- [x] Split/Join Tag
- [x] Remove Tag
- [x] Merge Lines
- [x] Update Image Size
- [x] Evaluate Math Expression
- [x] Increment/Decrement Number
- [x] Reflect CSS Value
- [x] Encode/Decode Image to data:URL

**Comment by mrmlnc** [comment]
PR welcome?
