### ISSUE TITLE
Code file replaced in view

### ISSUE THREAD

**Issue by Rayapur** [microsoft/vscode#82070]
Issue Type: <b>Bug</b>

Hi,
Thanks for providing a fantastic editor, VSCode.

When I open, say, File A and then open another file B, the first file 'A' is gone from the view and replaced by file 'B' in the window. This happens sporadically (not all the time). Not sure of the root cause but this is obviously annoying. 

I have checked list of opened windows under 'WINDOW' menu, there is only one item mentioned, which is the replaced file. Can you please fix this - I anticipate that I should be able to open multiple files in the VSCode editor. 

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (4.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
exuberant-ctags|chr|0.0.12
python-preview|don|0.0.4
code-runner|for|0.9.14
vsc-python-indent|Kev|1.5.0
kite|kit|0.98.0
MagicPython|mag|1.1.0
python|ms-|2019.9.34911
team|ms-|1.149.2
vscode-sanddance|msr|1.2.9
printcode|nob|3.0.0
vscode-print|pdc|0.7.12
vscode-data-preview|Ran|1.48.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Are the editors opened as previews? See this question: https://stackoverflow.com/questions/38713405/open-files-always-in-a-new-tab

Set `"workbench.editor.enablePreview": false` to disable this

**Comment by Rayapur** [comment]
Thanks for the swift response. The link you have provided answers to my query. Appreciate it.
