### ISSUE TITLE
NODE_MODULE_VERSION Error with Kerberos NPM library in Extension

### ISSUE THREAD

**Issue by brandonkoch6** [microsoft/vscode#82075]
- VSCode Version: 1.38.1
- OS Version: Windows 10.0.18362

Steps to Reproduce:

1. Create a VS Code Extension and install the npm kerberos library
2. Import the kerberos library into your extension and use it
3. Run your extension in debug mode
4. You will see a message along these lines:

vscode\node_modules\kerberos\build\Release\kerberos.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 64. This version of Node.js requires NODE_MODULE_VERSION 69. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)

**Comment by jrieken** [comment]
search for vscode and native modules

**Comment by brandonkoch6** [comment]
It seems that native modules are discouraged from being used in the docs.  Is there a way to make them work that is well-documented?
