### ISSUE TITLE
Compact menu icon flickering

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#82078]
Steps to Reproduce:

1. Click compact menu icon to open it
2. Click again to hide it. Observe icon flickering for a split second

![compactmenuiconflicker](https://user-images.githubusercontent.com/25115070/66364066-0b6e2700-e94e-11e9-8a15-d214de36ec7c.gif)

**Comment by caiges** [comment]
`src/vs/base/browser/ui/menu/menubar.ts` is removing and adding the button element during  `updateOverFlowAction`. I don't quite understand the intent of that method but that's why it's behaving this way.

**Comment by jeanp413** [comment]
@caiges Thanks for the pointer. I took a look and I fixed it, gonna make a PR.
