### ISSUE TITLE
Let me choose the language for file with unknown extension.

### ISSUE THREAD

**Issue by wow056** [microsoft/vscode#82079]
I am coding pintos and there are *.ck files for test cases written in perl.
It has the comment on top of it.
`# -*- perl -*-`
However vscode cannot highlight with perl language.
I tried to choose language, however there was no button to choose language
![image](https://user-images.githubusercontent.com/38684189/66369035-a231f680-e9d5-11e9-89e0-41cc1dfbbac3.png)

Please let me choose the language for file with unknown extension.

**Comment by bpasero** [comment]
@wow056 can you right click on the status bar and see if you have the language picker hidden?

**Comment by wow056** [comment]
OMG. I didn't notice... Thank you.
