### ISSUE TITLE
Ability to add format to untitled files

### ISSUE THREAD

**Issue by sinadarvi** [microsoft/vscode#82082]
i know that we can use untitled files for scratch file but some thing missing here, how we can add format to that file so we can see more and better with highlight feature.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by IllusionMH** [comment]
You can pick `>Change Language Mode` from Command palette and set language for Untitled files.
Then syntax highlight and formatting should work.

**Comment by sinadarvi** [comment]
@IllusionMH thanks, I didn't notice that! 😃
