### ISSUE TITLE
C++使用模板类后，无法在函数实现中使用this指针，并且无法通过域作用符直接创建函数实现

### ISSUE THREAD

**Issue by Liuary** [microsoft/vscode#82080]
Issue Type: <b>Bug</b>

创建如下类：
```c++
template <class T>
class Temp
{
private:
int a;
public:
void tempFunction();
}

template <class T>
Temp::tempFunction()
{
this-> // 这里不会有任何代码提示
}
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.27GB free)|
|Process Argv|D:\Users\Liuary\Documents\Liuary\programming\cpp\2\2.3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
code-gnu-global|aus|0.2.2
unity-code-snippets-improved|ble|1.4.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
auto-close-tag|for|0.5.6
auto-using|Fud|0.7.9
beautify|Hoo|1.5.0
docthis|joe|0.7.1
unity-code-snippets|kle|1.3.0
csharpfixformat|Leo|0.0.84
vscode-language-pack-zh-hans|MS-|1.38.4
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
vscode-css-peek|pra|3.0.2
unity-tools|Tob|1.1.1
unity-debug|Uni|2.7.2
code-navigation|vik|0.2.0
unity-snippets|Ycl|0.1.2

</details>

**Comment by elemount** [comment]
I think it should be put in https://github.com/microsoft/vscode-cpptools not in here

**Comment by Liuary** [comment]
> I think it should be put in https://github.com/microsoft/vscode-cpptools not in here

Oh thanks
