### ISSUE TITLE
Test the VS Code JSON Mode

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8208]
- [x] @seanmcbreen 

As the JSON language smarts got extracted to a node module, we should test that JSON language features still work:

- validate:
   - syntax errors
   - schema-driven validation
      - user defined schema (either through the $schema property or by configuration)
      - preconfigured schema from a schema server package.json, project.json, bower.json
      - preconfigured schema from vscode (settings.json)
      - https://code.visualstudio.com/docs/languages/json has more details on the different ways schemas can be associated and defined.
- hover
- code completion
- symbol information (outline)
- format

**Comment by seanmcbreen** [comment]
Nice work!
