### ISSUE TITLE
Drag-and-drop indented blocks of code

### ISSUE THREAD

**Issue by mindey** [microsoft/vscode#82084]
Make it possible to move blocks of code by indentation levels, like so:
https://wiki.mindey.com/shared/shots/0cbe7349349c0b14efabbbcd7-vscode-feature-request--moving-indented-blocks-with-mouse-to-other-levels-of-indentation.mp4

https://user-images.githubusercontent.com/384735/103430679-6547b600-4bbe-11eb-81b6-073b757ad596.mp4

Related idea: https://www.halfbakery.com/idea/Software_20Development_20IDE_20as_20Lists_20Editor

**Comment by jrieken** [comment]
/needsMoreInfo

@mindey Do you want drag and drop in the outline view or inside the editor. Which exists via the `editor.dragAndDrop` setting

**Comment by mindey** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Add the option to hide the indentation up to a certain level (#55157)](https://www.github.com/microsoft/vscode/issues/55157)

Not related.

> Do you want drag and drop in the outline view or inside the editor.

Inside the editor of course. Take a look at the video @jrieken

**Comment by mindey** [comment]
So, how is this going? :)
