### ISSUE TITLE
Allow users to clear confirmedUriHandlerExtensionIds

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82085]
From https://github.com/microsoft/vscode/issues/80054#issuecomment-539052951

Using a quick open interface.

**Comment by joaomoreno** [comment]
Pushed `Extensions: Manage Authorized Extension URIs...`

cc @sguillia

**Comment by sguillia** [comment]
Great, thanks!

The allows extensions in user setting `extensions.confirmedUriHandlerExtensionIds` are not displayed in the quick pick. I wouldn't expect it, but for a moment I forgot they were in my settings :-)
