### ISSUE TITLE
ChromeOS - when ALT TAB into Visual Studio Code from tab on different Desk 

### ISSUE THREAD

**Issue by c0d3rm0nk3y** [microsoft/vscode#82094]
Issue Type: <b>Bug</b>

What Alt Tab into visual studio from a different tab on a different Desk (latest feature in beta as of 10/8/19) a repeating tab is inserted until a key is pressed.  

This however does not happen when using the multi-finger swipe between Desks.

I am uncertain if it is ChromeOS inserting a repeating tab character or Visual Studio is perceiving a false one or some odd repeating event when getting focus

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.19.69-06666-g6c4f8cbba24e

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/5c (2 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|2.73GB (0.49GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icons|Arc|0.2.0
vscode-markdownlint|Dav|0.30.2
prettier-vscode|esb|2.3.0
python|ms-|2019.9.34911
Go|ms-|0.11.7
deepdark-material|Nim|3.2.0
material-icon-theme|PKi|3.9.1
LiveServer|rit|5.6.1
swdc-vscode|sof|1.1.30

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@c0d3rm0nk3y this sounds like an upstream issue that should filed against the upstream component. Thanks
