### ISSUE TITLE
Lost a whole day of work

### ISSUE THREAD

**Issue by SergioRius** [microsoft/vscode#82096]
Today I started Visual Studio Code and it opened by default the project I was working on yesterday. The project is a Vuejs web application, opened as a **local folder**, and **not included into any version control**. I noticed that as I clicked, two instances of VSCode where opened, that seemed equal to me, so I closed the one opened last.
When running the aplication I saw multiple errors that shouldn't be there, and when I checked the files all the changes for the last 24 hours where reverted.
No message was shown, no confirmation dialogs and no questions for actions. It simply ate the work. Now:

- Is this supposed to be normal? If so, I would drop that environment at lightspeed (perhaps I will do anyways)
- How I can get back my work? Yesterday it all was saved right, without issues, this should be anywhere.
- How can I stop it doing this shit? For being able to revert It should have been saving incremental files without permission. How can this be stopped?
- Should I also scan all the solution for plugins and node components silently deleted, and configurations altered, even when internal?

My system runs Kubuntu 19.04 and VSCode v1.38.1

> Version: 1.38.1
> Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
> Date: 2019-09-11T13:30:08.229Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Linux x64 5.0.0-29-generic snap

**Comment by jrieken** [comment]
I am sorry this happened to you but I also can't say how and why. There is no such "feature" as reverting files, esp. when there is no version control set up.  Files are saved when they change in the editor, there is no history concept which would allow to retrieve and save a previous state. 

Are you sure that this was trigger from VS Code and from another program? Can you remember steps that you did so that we can reproduce this? Do you have extensions installed that are maybe in charge of this?

**Comment by SergioRius** [comment]
Thanks for your response. In this case, I don't know how and what I can do to supply more info.
At the time, I simply created the project using command line vue-cli commands in the user folder. So to me it should be a simple folder with a bunch of files to vsc.
I was using vsc for editing iot sketches before, so basically I have installed platformio, but not using on this, obviously.
I don't know to do an extensions output, but I can copy them there:

> C/C++
> Dark+ Material
> Docker
> PlatformIO IDE
> Python
> TSLint
> Vetur

I still have VSC on it's first open after the problem. Can I extract an action log or something?

**Comment by jrieken** [comment]
adding @joaomoreno since source control shows things

**Comment by joaomoreno** [comment]
@SergioRius Can you run `Git: Show Git Output` and show us the full contents of that?

**Comment by SergioRius** [comment]
@joaomoreno Hi Joao, of course:

```
Looking for git in: git
Using git 2.20.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /home/sergio/iot-dashboard
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git show :src/views/AdminGroups.vue
> git ls-files --stage -- src/views/
> git check-ignore -v -z --stdin
> git ls-tree -l HEAD -- /home/sergio/iot-dashboard/src/views/AdminGroups.vue
> git show HEAD:src/views/AdminGroups.vue
> git ls-tree -l HEAD -- src/views/
> git show :src/router/index.js
> git ls-files --stage -- src/router/
> git ls-tree -l HEAD -- /home/sergio/iot-dashboard/src/views/AdminGroups.vue
> git show HEAD:src/views/AdminGroups.vue
> git ls-tree -l HEAD -- src/views/
> git ls-tree -l HEAD -- /home/sergio/iot-dashboard/src/views/AdminDevices.vue
> git show HEAD:src/views/AdminDevices.vue
> git ls-tree -l HEAD -- src/views/
> git ls-tree -l HEAD -- /home/sergio/iot-dashboard/src/views/AdminGroups.vue
> git show HEAD:src/views/AdminGroups.vue
> git ls-tree -l HEAD -- src/views/
> git show :src/views/AdminDevices.vue
> git ls-files --stage -- src/views/
> git show :src/views/AdminGroups.vue
> git ls-files --stage -- src/views/
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/views/AdminGroups.vue
> git ls-files --stage -- src/views/
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/views/AdminDevices.vue
> git ls-files --stage -- src/views/
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/views/AdminGroups.vue
> git ls-files --stage -- src/views/
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```

I have some more info that I would share.
Yesterday, before shutting off the station, I was working on the project, while picking code parts from another project that I have, and also at intervals looking at a sample project. All two also opened in VSC. So I had three live instances of it running.
I don't know if that's relevant, but I have a very slow internet connection, and that's the reason I don't live sync my changes to a cloud repo. I don't know if the vsc feature of retain unsaved changes or code is online, and if that could be involved.
Related, and also strange, is that after more than an hour idling unattended, I recovered almost all the changes I apparently had lost. That's why I ask about connected sync.
After checking that I recovered part of the code I tried to transfer changes from two similar files, a service entity (poco) to another that still had it's code lost. I could not write to it and VSC always showed a message saying that **the file was locked**.

**Comment by indraraj26** [comment]
May be Vue cli is initializing the git just like angular cli does.

can you create another project and check git status

**Comment by SergioRius** [comment]
Yes, of course:
```
Looking for git in: git
Using git 2.20.1 from git
> git rev-parse --show-toplevel
> git rev-parse --git-dir
> git config --get commit.template
Open repository: /home/sergio/sources/test
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
fatal: no upstream configured for branch 'master'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
```
This is the output from a newly created project, with the same options as the other. Without plugins and aditional dependencies.

Also I see that today vscode has updated:
> Version: 1.39.0
> Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
> Date: 2019-10-09T06:58:03.188Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Linux x64 5.0.0-31-generic snap

Note: The version of node installed global in my system is different that the one shown in vscode:
```
$ node --version
v12.11.1
```

**Comment by joaomoreno** [comment]
> The project is a Vuejs web application, opened as a local folder, and not included into any version control.

@SergioRius you mention that the project isn't in any source control, but the git log shows that there is a git repository in `/home/sergio/iot-dashboard`. That still doesn't explain why your files are gone, though. But I'm confused why you would mention that the files aren't in source control.

**Comment by SergioRius** [comment]
@joaomoreno Joao, I trust you, but believe me that it's nothing that I had setup. I can see git folder, gitignore... Is there something you want me to send to you?
All the files and folders are dated from the past monday at 12:49. And one "COMMIT_EDITMSG"

*That address you posted is the folder where the project is stored. On linux: User folder/name of the project. I was just opening my user folder with the file manager, right click at this folder and "open with VsCode".

The project was creates only by executing in terminal: `vue create iot-dashboard`
And this is the content of the package.json (as by now)
```
{
  "name": "iot-dashboard",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "bootstrap-vue": "^2.0.0-rc.19",
    "core-js": "^2.6.5",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-moment": "^4.0.0",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.4.4",
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-pwa": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "axios": "^0.18.0",
    "babel-eslint": "^10.0.1",
    "bootstrap": "^4.3.1",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "mutationobserver-shim": "^0.3.3",
    "node-sass": "^4.12.0",
    "popper.js": "^1.15.0",
    "portal-vue": "^2.1.4",
    "prettier": "^1.18.2",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-axios": "0.0.4",
    "vue-cli-plugin-bootstrap-vue": "^0.4.0",
    "vue-template-compiler": "^2.6.10"
  }
}
```

**Comment by EdwardGoomba** [comment]
@SergioRius Weighing in here, vue cli initializes a git repository for you automatically when creating a new project. You have to pass in a flag in order for it to not do so.

So while you didnt explicitly initialize git, the cli did so for you. This doesnt clear up unsaved work - but solves why you had a git initialized when you didnt explicitly do so.

**Comment by joaomoreno** [comment]
@SergioRius I believe @EdwardGoomba has nailed on the reason why you had a git repository in place. I'm not sure why some of your files disappeared but without being able to reproduce this issue, it's going to be hard to find the root cause for it.
