### ISSUE TITLE
Please stop closing valid issues "to keep the number of issues (to) a manageable level"

### ISSUE THREAD

**Issue by gingerbeardman** [microsoft/vscode#82095]
I have seen this for many issues I spent my valuable time filing:

(from vscode bot)
> This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.
> 
> If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Thanks for your understanding and happy coding!

Closing valid issues in this way continues to be a truly obnoxious way of dealing with them. It's a real 🖕 to people who spend their valuable time adding them. 

I'd like to know why a slightly smaller list of issues is justifiably more manageable than a slightly longer one? Especially when we are already well in the ~5000 anyway. I don't get it. Surely you're filtering issues by keywords, labels, assignees, milestones etc, so the actual size of the number of issues is surely largely irrelevant?

Anyway, for this reason I no longer use vscode.

Please treat your users with more respect.

**Comment by egamma** [comment]
@gingerbeardman we have started our annual housekeeping iteration. Please see the iteration plan for more background https://github.com/microsoft/vscode/issues/82194.  The reason for doing such housekeeping iterations is described in our [issue grooming](https://github.com/microsoft/vscode/wiki/Issue-Grooming) page.

**Comment by gingerbeardman** [comment]
In other words, you just don't care.

Nice approach.

**Comment by mi-hol** [comment]
@gingerbeardman finding the right balance is always a challenge.
To turn this into a positive direction, maybe you want to pinpoint the part of the policy you do perceive as disrespectful?

**Comment by gingerbeardman** [comment]
Anything that means closing of issues users have spent valuable time filing, and that are still relevant and valid but are closed to make the lighten the perceived workload of issues.

> **Out-of-Scope Feature Requests**
> But this makes it hard for you to understand what has realistic chances to ever make it into the repository. We therefore close feature requests we won't address.

I feel it is disingenuous to say that these issues are being closed to "help the user understand" when in fact it has been stated elsewhere (I'll keep looking for this reference, I don't have it to hand) that it is really to keep bugs "below a XXXX number of issues" for team management reasons.
