### ISSUE TITLE
when debugging extension, value 'Infinity' in Debug Console showed as `null`

### ISSUE THREAD

**Issue by aprilandjan** [microsoft/vscode#82104]
I made a simple vscode extension [ascii-tree-generator](https://github.com/aprilandjan/ascii-tree-generator) months ago. Recently I found that, when press <kbd>F5</kbd> and enter extention debugging, and use `console.log` to output a variable which is actually `Infinity`, the `Debug Console` showed it as `null` instead of `Infinity`. This is confusing and seems buggy.

I tried a newly created extension project from `yo code` template, it is still the same.

![image](https://user-images.githubusercontent.com/7011247/66399539-62d5cb00-ea12-11e9-8c5a-85ba5b81e01c.png)

in `Debug Console`:

![image](https://user-images.githubusercontent.com/7011247/66399585-7aad4f00-ea12-11e9-9eb2-ccee79a13724.png)

- VSCode Version: 1.38.1
- OS Version: macOS 10.14.4

Steps to Reproduce:

1. create a template extension project follow this [official guide](https://code.visualstudio.com/api/get-started/your-first-extension)
2. add test script in `activate` method:

```typescript
console.log('Congratulations, your extension "test-ext" is now active!');
const a: number = Infinity;
console.log(a, null, a === null);
```

3. press <kbd>F5</kbd> to enter extension debugging;
4. run this extension command to activate the extension;
5. check the `Debug Console` in source project window. It showed as:

```bash
Congratulations, your extension "test-ext" is now active!
null null false
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Yes I can reproduce this, and I can only reproduce this with the extension sample. I can not reproduce this with a regular node program.
However this is coming from the debug extension, thus forwarding to @roblourens

**Comment by roblourens** [comment]
`console.log` in the extension host doesn't go through the debug adapter.

This is probably due to "infinity" not being JSON serializable: 
![image](https://user-images.githubusercontent.com/323878/66504605-538c6700-ea7e-11e9-975a-2d2143f67f93.png)

**Comment by isidorn** [comment]
@roblourens good point and you are correct

**Comment by aprilandjan** [comment]
@roblourens Thanks for your tips, That's something I didn't know before! It will be much better if we can have these un-serializable values displayed correctly in host console.
