### ISSUE TITLE
vscode is sharing environment variables between 2 unrelated instances

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#82107]
If I launch 2 different vscode instances from two different command prompts on windows, the second instance of vscode will end up getting the environment variables of the first instance.

- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. launch 2 different command prompts on windows
2. in the first one, type `set zzz=ZZZ`
3. launch code
4. from the second command prompt, launch another instance of code
5. go to the terminal of both instances and check the environment variables, both of them will have the environment variable `zzz`

I tried it also with `Git Bash` on windows and the same thing happens.

**Comment by Tyriar** [comment]
This is by design currently as the windows share the same "main process".

/duplicate https://github.com/microsoft/vscode/issues/15452
