### ISSUE TITLE
JSON in the monaco editor

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8210]
- [x] @chrmarti

- clone https://github.com/Microsoft/monaco-editor 
- npm install
- npm run simpleserver and open http://localhost:8080/monaco-editor/test
- open and edit the json sample
- validate:
   - syntax errors
   - schema-driven validation:
    Note, the standalone editor sample editor page can not fetch any remote schemas. The only schema available is currently the schema-schema.
    Create a json file with `"$schema": "http://json-schema.org/draft-04/schema#"`
- hover
- code completion
- symbol information (outline)
- format
- https://code.visualstudio.com/docs/languages/json has more information on the various features

**Comment by jrieken** [comment]
@aeschli Pls add steps how to get the editor etc
