### ISSUE TITLE
`workbench.action.terminal.rename` should accept name as an argument

### ISSUE THREAD

**Issue by vintprox** [microsoft/vscode#82105]
Currently, `workbench.action.terminal.rename` command doesn't accept any argument. I wanted to make macros that renames current terminal after performing some other actions.

At the moment, it requires user prompt interaction.

https://github.com/microsoft/vscode/blob/f0faef0dd7abdb4e823d32ef21c557123427e0b3/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1053-L1066

**Comment by vintprox** [comment]
@Tyriar no, I am using custom fork of `macros`, which is addressed [here](https://marketplace.visualstudio.com/items?itemName=l7ssha.macrosRe). I needed some delays between sending terminal sequences: https://github.com/geddski/macros/issues/9#issuecomment-322806597

Fortunatelly, it solves issues with providing some dynamic input like passphrase (because I couldn't establish SSH without passphrase prompt, unluckily, so I have to use bad technique atm), running console program on remote computer after SSH login, REPL commands to 3DX MQL.

Thank you for advising `fabiospampinato.vscode-terminals` extension! I will try it tomorrow.

**Comment by vintprox** [comment]
I think I know how to make rename feature programmatic (with simple `title` argument), but it takes a time to contribute here, hehe.

**Comment by vintprox** [comment]
@Tyriar thank you again for recommending [Terminals Manager](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals), it feels great to use and it's packed with custom delays, which helps me to perform time-consuming tasks. 🎉

**Comment by Tyriar** [comment]
@perceptron007 right now the rename command is defined here:

https://github.com/microsoft/vscode/blob/8a806778ea25e16314750eb4c3fc313f736442a6/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L1039-L1067

I think we need to convert it into a `Command` to accept an arg like this one:

https://github.com/microsoft/vscode/blob/8a806778ea25e16314750eb4c3fc313f736442a6/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L301-L325

**Comment by vintprox** [comment]
@perceptron007 Sorry for late response. I made some changes to code, please review it and cover with some test if needed. I'm not ready to make pull request yet, so I derive it to you, guys.

**Comment by Tyriar** [comment]
@vintprox I would have thought you'd need to convert it to a `Command`, does passing in the arg in a keybinding work there?

We want this keybinding to be able to rename the terminal by executing it:

```json
{
  "key": "cmd+shift+h",
  "command": "workbench.action.terminal.rename",
  "args": {
    "title": "My term"
  }
}
```

Also you can get intellisense for `title`, see the `workbench.action.terminal.newWithCwd` command for how to do this:

![image](https://user-images.githubusercontent.com/2193314/67099949-b0210d80-f173-11e9-8ef5-70bd65a709e0.png)

**Comment by vintprox** [comment]
@Tyliar
Oh, didn't think about that. How do I deal with `entry?: TerminalEntry` argument though?
Made another commit for review.

**Comment by Tyriar** [comment]
@vintprox hmm, we may just need to make a new command just like `newWithCwd` I guess `renameActiveTerminal`? You're pretty close, you can put a PR out as it will be easier to give feedback there.

**Comment by vintprox** [comment]
You are right! I completely forgot what pull requests are for here.

**Comment by sksaifuddin** [comment]
Hello @vintprox  did you create the PR ? is this issue resolved ?

**Comment by vintprox** [comment]
Uh-oh, I'm kind of busy right now and cannot find a right time. You can make it, if you want to solve the issue!

**Comment by petevdp** [comment]
Hey, if this issue is open I'd like to pick it up!

**Comment by vintprox** [comment]
Of course, why not, proceed! @petevdp
