### ISSUE TITLE
Ambiguous/confusing implicit workspace settings feedback

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82117]
This happens in both VS Code v1.38.1 and Insiders v1.39.0

- VSCode Version: v1.38.1 and v1.39.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Copy all your default settings to any repository's /.vscode/settings.json
2. Notice that a few settings show the message "This setting cannot be applied now. It will be applied when you open this folder directly."

This message implies that these settings cannot be applied _now_, but may _sometime in the future_ and that opening the .vscode folder directly would apply them, which makes no sense.

I suggest changing the message to: "This setting is not applicable in an implicit workspace's .vscode folder's settings. It is only applicable in your user settings.json file or in an explicit workspace .code-workspace file."

Does this issue occur when all extensions are disabled? Yes

**Comment by sandy081** [comment]
To explain clearly, Some of the settings in the workspace folder cannot be applied when the folder is part of a multi folder workspace. They are enabled only when the workspace folder is opened directly.

I see there is some confusion with statement `open this folder directly`. instead it should be `open the containing workspace folder directly`. Also `This setting cannot be applied now` can be rephrased to `This setting cannot be applied in this workspace`.

`This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly`

**Comment by andrecasal** [comment]
@sandy081 if I may, there's more confusing than that:
1. Both implicit (the untitled workspace automatically created when VS Code opens a folder) and explicit (a .code-workspace file) workspaces can be multi folder and a workspace explicit in a .code-workspace file can have no folders in it. By "multi folder workspace" you mean a workspace that's explicit in a .code-workspace file, right?
2. The concept of `opening a workspace folder` doesn't make sense, because a workspace is not a folder. An implicit workspace is a set of one or more folders and an explicit workspace is a set of zero or more folders.

My suggestion would be to change `This setting cannot be applied now` to `This setting cannot be applied in an implicit (.vscode) workspace` and `open this folder directly` to `open a workspace file directly`.

**Comment by sandy081** [comment]
> An implicit workspace is a set of one or more folders and an explicit workspace is a set of zero or more folders.

Sorry you are mistaken. There are 3 states. 

1. Empty Window - No Folder, No Workspace.
2. Folder - Single Folder. Opening a folder directly in VS Code.
3. Workspace - Zero or Many Folders.

We have `Folder` because of legacy as `Workspace` was introduced after. So some folder settings are applied only in Single Folder and are inactive when the folder is opened in Workspace.

**Comment by andrecasal** [comment]
Ah I think I finally have a complete mental model for how VS Code handles this.

Some settings are applied at the `repository level`, some settings are applied at the `single-folder/workspace level` and some settings are applied at the `user level`.

Thanks @sandy081 👍
