### ISSUE TITLE
Integrated Terminal Splitting Not working on Mac

### ISSUE THREAD

**Issue by RyanPWalker** [microsoft/vscode#82118]
Issue Type: <b>Bug</b>

I use the integrated terminal 99% of the time.  I open it with ctrl + ` on my Mac.  Starting several months ago (I really can't remember when) clicking the split terminal icon does not split the terminal into two baby windows.  I miss this, please bring it back.  I now use the plus button next to the split terminal button to open a second terminal, but life hasn't been the same.  My version is up to date.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.00GB free)|
|Process Argv|-psn_0_151589|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
project-manager|ale|10.8.0
path-intellisense|chr|1.4.2
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.1.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|2.3.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-yarn|gam|1.6.0
beautify|Hoo|1.5.0
relativepathrefactor|jak|0.9.0
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.24
vscode-postcss-sorting|mrm|3.0.1
vscode-docker|ms-|0.8.1
mssql|ms-|1.6.0
debugger-for-chrome|msj|4.12.0
vscode-react-native|msj|0.12.0
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.0.1
quicktype|qui|12.0.46
java|red|0.50.0
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Strange, I had one other report of this but it's never happened to me... Any errors in the devtools console (via help menu)? Or any notifications when you try to split?

**Comment by RyanPWalker** [comment]
Checked devtools, no logged errors
