### ISSUE TITLE
Rearranging folders and files with drag 'n' drop in the Explorer panel

### ISSUE THREAD

**Issue by zolomatok** [microsoft/vscode#82110]
Why is there no drag 'n' drop feature for rearranging files and folders in the Explorer panel? Only a handful of automatic sorting methods. I'd like to arrange my files & folders manually, in an order I see fit.

This has been requested before, the issues were closed, but seems like it wasn't solved adequately.
https://github.com/Microsoft/vscode/issues/44205
https://github.com/microsoft/vscode/issues/29715

Opening a folder or a workspace makes no difference in the matter.

**Comment by isidorn** [comment]
Dup of sorting in files explorer. Please search for that issue. Thank you
