### ISSUE TITLE
Provide fs.openDir() API over fs.readDir() to scale better for large directory structures

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/vscode#82116]
NodeJS > 12.11.1 will have async readdir support Landed in cbd8d71 ( https://github.com/nodejs/node/commit/cbd8d715b2286e5726e6988921f5c870cbf74127 ) as fs{Promises}.opendir(), which returns an fs.Dir, which exposes an async iterator.

This will allow us to open big directorys without issues. 

first step would be identify all places that do the old readdir calls and refactor them to use iterators till we switch to node > 12.11.1 when we then have switched we can simply replace the function name and are ready.

### Current State
- Promoting change in existing module dependencys from 3th
- Explore and create other Tickets here to use the new functionality,

**Comment by bpasero** [comment]
@frank-dspeed there is more to it than just using this new method right? If a component requires all children of a folder to be resolved, we would still need to iterate over all children right?

In other words: if this new API is so efficient, I would expect `fs.readdir` to also use that API under the hood.

**Comment by frank-dspeed** [comment]
@bpasero the main problem with fs.readdir is that it reads all befor it returns the new api can return while reading.

**Comment by bpasero** [comment]
@frank-dspeed understood, but in most cases where we call fs.readdir we actually need all the children (e.g. copy them over into some of our data structures like the file explorer). Do you have a concrete example where we should use this new API

**Comment by frank-dspeed** [comment]
@bpasero  https://github.com/Microsoft/vscode/issues/43838

we need it at last in the file explorer and general even if we copy over structures we can do that incremental we will never whant to wait for 1 mio directorys to be loaded complet we can process each item

**Comment by bpasero** [comment]
@frank-dspeed are you speculating or have a real world example where VSCode today is slow handling this?

**Comment by frank-dspeed** [comment]
@bpasero i will prepare a demo no problem its a general nodejs problem not related to vscode alone i will prepare a demo project to open then you can play around with it

**Comment by bpasero** [comment]
OK

**Comment by frank-dspeed** [comment]
@bpasero i have verifyed it a bit but i used a big Ram disk as i have only ssd drives here and they would get killed to fast.

## Example Demo Project 
```
# Lets Create half million entrys 
mkdir -p ~/project/src/module{1.5000000}/{1..2}
```
- Open it even from a ram drive on a big i9 machine this took me a minut till it got responsiv.
- When this gets opened on a laptop you can get a coffe in that time. (Starbucks one not the one from the local coffe machine )

**Comment by bpasero** [comment]
The file IO layer can provide this iterator but that is not the hard task. Adopting this e.g. in the explorer to scale well is the real work. We can explore once we get access to the API, which is likely 6-9 months out given Electron is behind.

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/81473

**Comment by paulmillr** [comment]
I've tested opendir in readdirp and commented in the issue.

Good news: we can speed up walking the filesystem walk 3x compared to current version by using `dirent` with node 10.x+.
Bad news: `opendir` is shit, it will slow down the process by 300%.

**Comment by frank-dspeed** [comment]
@paulmillr you don't understand it correct the issu is not the speed till fully readed the case here is that there are directorys with files more then 100k and we need to stay responsiv.

## Goal here is
- Reduce time till first entry is emmited.

**Comment by frank-dspeed** [comment]
## Addition only for documentation
The fastest dir listing with minimum resource usage is parsing a nodeStream of spawn find(posix) that supports backpressure and also don't needs to wait till fully read.

but openDir will improve soon at present its the libuv2 binding and its only the first version of the code.

**Comment by paulmillr** [comment]
I understand the issue fully, it’s just we should not switch to new apis until they are polished. In this case, it’s 3x slower. They’re improving the perf right now. Let’s see how it works out.
