### ISSUE TITLE
When exiting an Integrated Terminal with `exit` the next Integrated Terminal should get focus

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8211]
- VSCode Version: Code - Insiders 1.3.0-insider (41f53d27a8cb477130f84116c78f43ddacbaf24b, 2016-06-27T05:07:29.758Z)
- OS Version: Windows_NT ia32 10.0.14366

Steps to Reproduce:

1. Open Integrated Terminal
2. Open a second Integrated Terminal
3. Type exit
4. Observe that no editor or terminal has focus

To get focus in an editor or terminal, one must now click or close and/or reopen the terminal via clicks or hotkeys.

Suggested fix:

The terminal that is visible after exiting one of the terminals should get focus.

**Comment by dilijev** [comment]
@Tyriar thanks for the quick response!

**Comment by Tyriar** [comment]
@dilijev :+1: let me know if there are any more issues with it on tomorrow's Insiders.
