### ISSUE TITLE
typescript.tsdk setting not applied as an implicit workspace /.vscode/settings.json setting

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82119]
This happens in both VS Code v1.38.1 and Insiders v1.39.0

VSCode Version: v1.38.1 and v1.39.0
OS Version: macOS 10.14.6

Steps to Reproduce:

1. Add the following to your /.vscode/settings.json
```
{
    "typescript.tsdk": null
}
```
2. Notice that the `typescript.tsdk` setting shows the message "This setting cannot be applied now. It will be applied when you open this folder directly.", meaning that this setting is not valid as an [implicit workspace setting](https://github.com/microsoft/vscode/issues/77718#issuecomment-539662926).

This is half bug report, half feature request: the setting 's description states:
```
Specifies the folder path to the tsserver and lib*.d.ts files under a TypeScript
install to use for IntelliSense, for example: ./node_modules/typescript/lib.

When specified as a user setting, the TypeScript version from typescript.tsdk
automatically replaces the built-in TypeScript version.

When specified as a workspace setting, typescript.tsdk allows you to switch to use
that workspace version of TypeScript for IntelliSense with the TypeScript: Select
TypeScript version command.

See the TypeScript documentation for more detail about managing TypeScript versions.
```

Even though the description doesn't differentiate between [implicit and explicit workspaces](https://github.com/microsoft/vscode/issues/77718#issuecomment-539662926), it would be expected that this setting would work inside the `/.vscode/settings.json` file. If that expectation is correct, this is a bug report. If it doesn't yet work inside an implicit workspace, it's a feature request - and in that case, I'll create a bug report asking to clarify the setting's description in the meanwhile.

Does this issue occur when all extensions are disabled? Yes

**Comment by mjbvz** [comment]
Not seeing any error for a single folder workspace:

![Screen Shot 2020-01-22 at 6 48 29 PM](https://user-images.githubusercontent.com/12821956/72952791-d09ace00-3d47-11ea-8d5f-f160a41b4165.png)

In a multiroot workspace, we only load a single TS Server instance (not one per folder). That's why the setting is disabled in the per-folder settings.

Please submit a PR if you feel the documentation is unclear
