### ISSUE TITLE
Update test explorer beaker icon to match new UI 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#82123]
I believe right now this is the icon that is being used by VS Code: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/browser/media/test.svg

 It'd be great if that could be updated to match the new UI.

**Comment by misolori** [comment]
This should be fixed now and using the [`beaker`](https://github.com/microsoft/vscode-icons/blob/master/icons/light/beaker.svg) icon:

![image](https://user-images.githubusercontent.com/35271042/66510909-d1ef0600-ea8a-11e9-9aa5-0590f43272d5.png)
