### ISSUE TITLE
Visual Studio Code becomes unresponsive

### ISSUE THREAD

**Issue by acube3** [microsoft/vscode#82129]
Issue Type: <b>Performance Issue</b>

While debugging python code, VS code becomes unresponsive.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (64 x 1000)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 1|
|Memory (System)|125.61GB (121.67GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   129	  2923	code main
    0	     0	  2925	   zygote
    1	     0	  3199	     shared-process
    0	     0	  4006	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4007	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   257	  3673	     window (train.py - singleshot (Workspace) - Visual Studio Code)
    0	   129	  3708	       extensionHost
    0	     0	  3881	         /home/amol/anaconda3/envs/sxomr/bin/python completion.py
    0	     0	  3892	           /home/amol/anaconda3/envs/sxomr/bin/python lib/python/jedi/evaluate/compiled/subprocess/__main__.py lib/python 3.7.4
    0	   257	  3733	       watcherService
    0	     0	  3745	       /bin/bash
    0	     0	  3788	       searchService
    0	     0	  3970	     window (Issue Reporter)
    0	     0	  2956	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (train.py - singleshot (Workspace) - Visual Studio Code)
|    Folder (singleshot6Dpose): more than 109749 files
|      File types: txt(10199) png(8254) jpg(1236) DS_Store(29) weights(29)
|                  data(24) py(20) out(15) err(13) ply(13)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python(8);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
cpptools|ms-|0.25.1

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
