### ISSUE TITLE
Webview: Maintaining context when when passing messages back and forth

### ISSUE THREAD

**Issue by queeniema** [microsoft/vscode#82126]
Using the documentation [here](https://code.visualstudio.com/api/extension-guides/webview#scripts-and-message-passing), I am able to pass messages back and forth between my webview and my extension.

However, I am not sure how to maintain context. For instance, suppose when a user clicks a button in the webview, a function is called (e.g., `handleButtonClick()`) to fetch some data from the extension (e.g., some configuration setting value). I then send a message back to extension to call the proper VS Code API functions to get that setting value, but how can I return that value back to same webview function context (i.e., `handleButtonClick()`) so I do something with that value (e.g., display it to the user)?

I don't think I can pass a callback function since that the message needs to be JSON serializable?

**Comment by mjbvz** [comment]
This is up to the extension. You can build proper RPC style helpers on top of `postMessage` if you like but the VS Code api here is intentionally very simple. As an example, look at what the issue reporter extension does: https://github.com/microsoft/vscode-pull-request-github/blob/master/preview-src/message.ts
