### ISSUE TITLE
After withProgress Clear Notification is clicked, vscode.CancellationToken.isCancellationRequested is set to true in non-Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#82120]
- VSCode Version: 1.38.1, doesn't repro with 1.39.0-insiders
- OS Version: Windows (others probably)

Steps to Reproduce:

1. Do something to cause a vscode.window.withProgress to appear with Cancellable enabled, such as using a Find All References command with the C/C++ extension on something that takes a long time like a std::vector.
2. Click the Clear Noticiation "X" button in the top right of the progress window.

Bug: vscode.CancellationToken.isCancellationRequested gets set to true with 1.38.1 (canceling the operation), but remains false with Vs Code Insiders (the operation keeps running, just the notification window disappears). We actually prefer the Insiders behavior, so it seems like this bug is fixed already, but I wasn't able to locate an issue or PR on this, so we wanted to double check that it is an intentional change. If the 1.38.1 behavior is desired, we'd prefer the API to add some vscode.ClearedToken so we can differentiate clear versus cancel.

UPDATE:
In our scenario, we ideally would want the X button to not cancel for users who just want to dismiss the progress indicator for a long-running operation (i.e. because it's blocking their UI). We add a task bar icon during the long-running operation that allows users to click it to re-show the progress indicator and press Cancel if they really wanted to Cancel.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Please bisect and let me know what caused this.

**Comment by sean-mcmanus** [comment]
What do you mean by "bisect"? Did you want me to do that? I searched the issues and pull requests, but I couldn't find anything relevant.

**Comment by bpasero** [comment]
@sean-mcmanus I added the "help wanted" label for someone to chime in to find the change that caused this. I was not necessarily asking you to do that. "git bisect" is a way to find a commit that caused a change (but requires to run VSCode out of sources). Helping me here increases the chance of resolving the issue.

**Comment by bpasero** [comment]
Extensions code to reproduce:

```ts
vscode.commands.registerCommand('extension.helloWorld', async () => {
	vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, cancellable: true }, (progress, token) => {
		setInterval(() => {
			console.log(token.isCancellationRequested);
		}, 1000);

		progress.report({ message: "Hello World" });
		return new Promise(resolve => {
			setTimeout(() => {
				resolve();
			}, 5000);
		});
	});
});
```

**Comment by roblourens** [comment]
If I remember correctly, this was actually restoring the behavior from a couple releases ago. But I guess now you can't tell the difference between clicking cancel and the progress completing.

**Comment by sbatten** [comment]
OP requests new API only if we were to revert the behavior. The new behavior seems correct to me. X is not a cancel, just a dismissal. With insiders behavior, you can differentiate between cancel and dismissal which is OP's request.

**Comment by sean-mcmanus** [comment]
Yeah, current behavior seems good -- thanks for clarifying for us.
