### ISSUE TITLE
Debug Console does not scroll

### ISSUE THREAD

**Issue by omartin2010** [microsoft/vscode#82133]
Issue Type: <b>Bug</b>

I've written a simple python file that generates generates output in a loop, the debug console is filling with text and when it's full, instead of showing the last line of text, it doesn't scroll down. My `launch.json` file looks like this:

```json
        {
            "name": "PI - Gyro Testing - Wired",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "192.168.32.50",
            "preLaunchTask": "Launch Remote PI Wired Testing Container",
            "pathMappings": [
                {
                    "localRoot": "c:\\Users\\omart\\Project",
                    "remoteRoot": "/src/repos/"
                }
            ],
            "internalConsoleOptions": "openOnSessionStart",            
            "postDebugTask": "Kill Remote PI Testing Container",
            "justMyCode": false,
        }
```

and the code I run looks like this :  
```python
from gyrosensor import GyroSensor
from ev3dev2.sensor import INPUT_4
import time
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s:%(levelname)s:%(threadName)s:%(message)s')
log = logging.getLogger(__name__)

sensor6 = GyroSensor(INPUT_4, 6)
print('sensor created...')
while True:
    time.sleep(5)
    print('5 sec passed...')
```
The class implements a thread that loops and sends things to the logger, which prints it on the debug console. But then it won't scroll automatically and I'm pretty certain it did before...

VS Code version: Code - Insiders 1.39.0-insider (c8252b63f547674d2faf361d4181bb76b0b5f81a, 2019-10-04T09:24:45.690Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.30.2
rest-client|hum|0.22.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
vscode-node-azure-pack|ms-|0.0.9
azurerm-vscode-tools|msa|0.7.0
azure-iot-toolkit|vsc|2.10.0

</details>

**Comment by isidorn** [comment]
Fixed in latest. Let me know if you can still see it with todays vscode insiders

**Comment by omartin2010** [comment]
Excellent, it works now!! :) thanks for fixing this.

**Comment by isidorn** [comment]
Thanks for letting us know
