### ISSUE TITLE
Debugging is not working on MacOS Catalina

### ISSUE THREAD

**Issue by lagmcfag** [microsoft/vscode#82138]
Using 'CMake Tools' from vector-of-bool

Expected Behavior:
Pause on breakpoint

Actual Behavior:
Ignores breakpoint

Note: lldb via command line works

### launch.json

```json
    "version": "2.0.0",
    "configurations": [
        {
            "name": "(lldb) Launch Program",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}/build",
            "targetArchitecture": "x64",
            "environment": [],
            "internalConsoleOptions": "openOnSessionStart",
            "externalConsole": false,
            "MIMode": "lldb"
        }
    ]
}
```

Same configuration worked on Mojave

### VS Code Info
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Comment by isidorn** [comment]
Please file against cppdbg extension https://github.com/microsoft/vscode-cpptools . Thank you
