### ISSUE TITLE
rg process high cpu usage on remote server when open /

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#82136]
- VSCode Version:  1.38.1
- OS Version: Linux x64 4.15.0-64-generic

Steps to Reproduce:

1. Use Remote ssh and open the / folder on remote server
2. see cpu usage by rg

![image](https://user-images.githubusercontent.com/1189869/66446995-3c9a4480-ea7f-11e9-8f3d-4d29a02ea69d.png)

 I have no extension installed on remote server.
![image](https://user-images.githubusercontent.com/1189869/66447006-4ae86080-ea7f-11e9-95e4-fa2e97a754c1.png)

**Comment by xgdgsc** [comment]
This one is pretty reproducible for me, it occurs on several servers when you open / on the server.

**Comment by roblourens** [comment]
Have you triggered a file search with ctrl+p? If so, there shouldn't be more than one going at a time.

Can you try this:

- Run the command "Set log level" and change it to "Trace"
- Reload the window
- Show the search-related messages in the "Log (Window)" output panel and possibly also the "Log (Remote Extension Host)" panel

That will tell us what is triggering a search.

**Comment by xgdgsc** [comment]
Thanks. From the log
```
[2019-10-10 09:00:36.852] [exthost] [trace] extHostWorkspace#findFiles: fileSearch, extension: vscode-icons-team.vscode-icons, entryPoint: findFiles
```
It seems vscode-icons is triggering the search, disabling it works.

**Comment by roblourens** [comment]
Thanks. I filed https://github.com/vscode-icons/vscode-icons/issues/2264, not sure whether your issue is related.
