### ISSUE TITLE
~30% GPU usage from playing gif from Remote - SSH page

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#82134]
Issue Type: <b>Bug</b>

1. Open "https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh"
2. Click "Install"

Windows shows that GPU usage jumps and stays at ~30%

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.16GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
EditorConfig|Edi|0.13.0
terminal|for|0.0.10
matlab|Gim|1.3.0
nbpreviewer|jit|1.2.2
language-julia|jul|0.12.3
markdown-converter|man|3.0.2
python|ms-|2019.10.41019
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
sublime-keybindings|ms-|4.0.3
vscode-fileutils|sle|3.0.0

(1 theme extensions excluded)

</details>

**Comment by pedrogarcia** [comment]
Is this really caused by the high resolution gif demoing the extension? 

I knew vs code was slow, but I did not knew it was `that slow`.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by pedrogarcia** [comment]
@mjbvz commented:
> Also, do you see similar perf numbers if you view the same page in Chrome?

Nope. Cpu jumps to ~10% in chrome, but that's it. 


@jrieken commented:
> /needsMoreInfo
> 
> Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

I could not find any information on GPU usage problems on the wiki page. What other info is needed?

**Comment by pedrogarcia** [comment]
This is issue is reproducible with the extensions turned of, using `code --disable-extensions`

Also, this is the output of the process explorer:

![Snipaste_2019-10-09_12-40-44](https://user-images.githubusercontent.com/2473545/66496965-247ff080-ea92-11e9-987c-a69fd555b540.png)

Is it normal to have 500 MB of memory and 400 of gpu memory with a single tab opened?

**Comment by pedrogarcia** [comment]
`code --status` outputs:


```
Version:          Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
Memory (System):  7.89GB (1.25GB free)
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        enabled
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    87	  9896	code main
    0	    13	  5136	   electron-crash-reporter
    5	   596	  8704	   window (undefined)
    3	   432	 11064	   gpu-process
    0	   132	 13156	   window (Extension: Remote - SSH - Visual Studio Code)
    0	    63	 11816	     extensionHost
    0	    67	 13472	   shared-process

```

**Comment by jrieken** [comment]
Hm, those traces don't show high CPU load

**Comment by pedrogarcia** [comment]
> Hm, those traces don't show high CPU load

Yes, because the problem is **GPU** load.

**Comment by jrieken** [comment]
Then how about expanding the "Visual Studio Code (9)" node in task manager, find the process with high gpu load, and share its command line info here?

**Comment by pedrogarcia** [comment]
@jrieken 
Like this? 
![gpu_node](https://user-images.githubusercontent.com/2473545/66505268-65cbcc80-eaa1-11e9-9d70-3c737a96ed7a.png)

**Comment by pedrogarcia** [comment]
@jrieken if I drag and drop the [gif from the extension](https://microsoft.github.io/vscode-remote-release/images/ssh-readme.gif) from chrome into vscode, memory and GPU increase a lot, but it is half as bad as clicking the link to open the extension page in vscode.

**Comment by jrieken** [comment]
Right click on the process - somewhere in there you find a way to get the command line options the process has been started with.

**Comment by pedrogarcia** [comment]
@jrieken
These are the option I get:
![image](https://user-images.githubusercontent.com/2473545/66508990-83506480-eaa8-11e9-9923-e9d25db9af9d.png)

**Comment by jrieken** [comment]
try properties

**Comment by pedrogarcia** [comment]
@jrieken 
> try properties

This is what shows up:
![image](https://user-images.githubusercontent.com/2473545/66585192-c8ce6980-eb5c-11e9-911e-68c106c935f6.png)
I Don't understand how this is relevant to determine the issue. Have you tried reproducing it?

**Comment by IllusionMH** [comment]
Tried this case and yes - there is spike in GPU load when extension tab is open, however it is 12-16% for my PC and does down as soon as I close extension tab.

Opening extension description if Edge (Chromium) only uses 5-6% GPU, however as soon as I apply zoom to Edge tab - GPU goes to 15-16%.

I tried disabling zoom in VS Code but haven't seen big difference `window.zoomLevel` is removed or `1`. Some difference is noticeable if width of Extension tab is small and gif is scaled down, than GPU goes down by 1-2%.

Version: 1.40.0-insider (user setup)
Commit: 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb
Date: 2019-10-11T05:44:05.506Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by deepak1556** [comment]
@IllusionMH the spike should be fixed now with latest insiders, can you verify. Thanks!
