### ISSUE TITLE
Add an option in Issue Reporter to append to existing bug

### ISSUE THREAD

**Issue by LWChris** [microsoft/vscode#82141]
Since #62741 was closed by @RMacfarlane and she suggests to open a new issue when we can't do what we want to do only using the issue reporter, here I go:

I want to comment on an **existing** GitHub issue, and still provide my specs properly formatted. Since apparently we are not going to get a straightforward "Copy specs to clipboard" button or command as requested in #62741, but instead are forced to use the longer, weirder (when replying) and cumbersome route via issue reporter, then issue reporter needs to be able to append your input to an existing issue by adding a field for the issue id.

Maybe add a toggle "Create a new issue" or "Append to an existing issue", where when the latter is selected an additional "Issue ID" input is shown.

**Comment by RMacfarlane** [comment]
@LWChris Sorry for not understanding your use case when I closed the original issue. I agree with you that it's an easier flow to use a copy command than go through the issue reporter for this case. So, I'm reopening the old issue and will close this one.

**Comment by LWChris** [comment]
Thank you!
