### ISSUE TITLE
Code completion closes when typing a number as the first item instead of filtering the results

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#82147]
If you type a number as the first character to filter code completion, all of the results are filtered out:

<img width="288" alt="Screenshot 2019-10-09 at 9 43 57 am" src="https://user-images.githubusercontent.com/1078012/66465767-65b7d680-ea79-11e9-9cca-b19b0d3f6ddb.png">

If you press `1` here, the completion list just closes, but I would expect it to remain open and filter to those items that have a `1` in them. It only happens if the first character typed is numeric, typing `a1` works fine.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/53715
