### ISSUE TITLE
PHP hereDoc and nowDoc incorrect indentation and folding

### ISSUE THREAD

**Issue by khooz** [microsoft/vscode#82148]
Issue Type: <b>Bug</b>

Using a hereDoc or nowDoc, the folding and indentations mess up.

```php
$variable = <<<"DOC"
this is a test doc
DOC;
function x()
{
    someFunction();
}
$other_vaiable = <<<"OTHERDOC"
this is another test doc
OTHERDOC;
```

The folding should fold out the Doc block into this

```php
$variable = <<<"DOC"...
DOC;
function x()
{...
}
$other_vaiable = <<<"OTHERDOC" ...
OTHERDOC;
```

but it folds like this:

```php
$variable = <<<"DOC"...
DOC; ...
$other_vaiable = <<<"OTHERDOC" ...
OTHERDOC; ...
// until end of file
```

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|1.0.120191007
vscode-intelephense-client|bme|1.2.3
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.44
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
todo-tree|Gru|0.0.158
gitignore|mic|1.0.1
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
azure-pipelines|ms-|1.157.4
vscode-azureappservice|ms-|0.16.0
vscode-azurestorage|ms-|0.7.1
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.4
python|ms-|2019.9.34911
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
Go|ms-|0.11.7
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.950
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
azure-hdinsight|msh|1.1.7
debugger-for-chrome|msj|4.12.0
php-docblocker|nei|2.0.1
laravel-blade|one|1.20.0
vscode-yaml|red|0.5.3
sass-indented|rob|1.5.1
azure-iot-toolkit|vsc|2.10.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by aeschli** [comment]
You need to file this against a PHP extension. Such extension have a parser and know where the here docs start. There's the folding range provider API that allows the extension to tell where the folding regions are. If no extension provides folding ranges, we fall back to indentation based folding ranges.

**Comment by khooz** [comment]
Is there anyway I could find out which extension decides formatting and folding for a particular action? anywhere on logs? Truth be told, non of extensions installed that I have listed, mentions formatting.

**Comment by aeschli** [comment]
Formatting and folding are provided in code, so we also don't know beforehand which extension contributes what. We don't have a feature to log what was contributed by who, but that would make sense. Please file an issue.
