### ISSUE TITLE
Markdown highlighting issue in nested lists

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8214]
1. create a markdown file with the following content

```
* xxx
    * xxx
    * `xx.xx` `yy.yy`
```

-> `yy.yy` has the wrong color

**Comment by mjbvz** [comment]
This was fixed by #14634:

![screen shot 2016-11-08 at 4 06 58 pm](https://cloud.githubusercontent.com/assets/12821956/20122553/785279ec-a5cd-11e6-9cc3-21118c322591.png)
