### ISSUE TITLE
ANSI escape code in debug cosole does not keep new lines.

### ISSUE THREAD

**Issue by actboy168** [microsoft/vscode#82144]
Issue Type: <b>Bug</b>

For ex. this code:

```lua
print("\x1b[31mtest")
print("test")
print("\x1b[0m")
```
Debug console
![1](https://user-images.githubusercontent.com/1836844/66458995-abd75f00-eaa6-11e9-9c76-5b6988602558.PNG)

Terminal
![2](https://user-images.githubusercontent.com/1836844/66458998-abd75f00-eaa6-11e9-9f61-54da55c62a77.PNG)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (17.45GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/ejoy/Desktop|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
extension-path|act|0.0.2
lua-debug|act|1.15.0
tasks|act|0.2.8
mock-debug|and|0.35.1
vscode-language-pack-zh-hans|MS-|1.38.4
remote-wsl|ms-|0.39.5
material-icon-theme|PKi|3.9.1
vscode-hexdump|sle|1.7.2
lua|sum|0.12.12

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Yes this is not currently supported.
fyy @dgozman @iansan5653

**Comment by iansan5653** [comment]
Yeah, currently no styles carry over from one message to another - they are treated in isolation. An alternative for now would be to log `\x1b[31mtest\ntest\n\x1b[0m` in one statement.

**Comment by iansan5653** [comment]
Personally I'm not convinced that they _should_ carry over - the debug console imitates a terminal in some ways but I don't know that it should act exactly as one. What would be the expected behavior if I do something like the following?

```js
console.log("\x1b[31mtest");
let sampleObj = {example: true};
console.log(sampleObj);
console.log("test");
```

Should the logged object be red? What if I add a breakpoint and inspect it?
![image](https://user-images.githubusercontent.com/2294248/66494916-6c991600-ea86-11e9-816e-4f22abd55160.png)
