### ISSUE TITLE
[Feature Request] Port CSS "font-feature-settings" in settings.json

### ISSUE THREAD

**Issue by qrqiuren** [microsoft/vscode#82153]
See [the instructions of enabling Fira Code's stylistic sets in editors](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets).

In VS Code, we have to hack the editor to override CSS's `font-feature-settings` to change the stylistic sets. I hope we can configure this option directly in `settings.json`.

**Comment by alexandrudima** [comment]
It will be possible to define via e.g.:
```
"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"
```

**Comment by wboka** [comment]
This doesn't seem to work in VS Code v1.40.0 and v1.40.1. See #84917.

Has anyone had any luck getting this to work?

A few people on #84917 have been able to get the following code snippet to work but not the `ssxx` notation.

```jsonc
{
  // Code omitted for brevity
  "editor.fontLigatures": "'zero', 'onum'"
}
```

## Versions

- OS: Windows 10, 64-bit
- VS Code: v1.40 and v1.40.1
- Fira Code: 2.0

**Comment by alexandrudima** [comment]
Resolved in https://github.com/microsoft/vscode/issues/84917#issuecomment-555133092
