### ISSUE TITLE
Support list settings for extensions

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#82155]
If I understand https://code.visualstudio.com/api/references/contribution-points#contributes.configuration correctly, then it is currently impossible for an extension to add a multi-option list-like setting.

For example: I have an extension that supports multiple accounts which I want to configure via vscode's settings. Each account would have an entry with `username`, `email`, etc. I can do this for **one** account, but not for multiple (without resorting to dirty hacks).

Could this be added to the configuration contribution point to support some form of arrays of classes/containers?

**Comment by sandy081** [comment]
Configuration value can be of any type `string`, `boolean`, `number`, `array`, `object`. For your example, it can be an array of objects. You can define the schema to be array of objects and also specify what properties the object can have. At the end it is nothing but a json and you can use the same schema.

**Comment by dcermak** [comment]
You are actually right! I didn't know that and unfortunately the documentation doesn't make that really apparent.

There's also a pretty big catch though: defining a relatively complex schema (e.g. an array of objects) means that you loose the ability to modify settings via the UI (as seen [here](https://code.visualstudio.com/assets/api/references/contribution-points/settings-ui.png) where each entry has a description), you can **only** modify the settings by editing `settings.json` directly. That delivers pretty bad UX and means that I'd have to provide wrapper functions to modify all the settings.

Would it be possible to add a more complex example to the documentation, so that people are aware that this is actually possible? And would extending the UI to support more complex schemas be something that could be implemented at some point?

**Comment by sandy081** [comment]
Yeah there are plans to improve the UI for all types but not sure how deep it can go. And the documentation is available here - https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

**Comment by dcermak** [comment]
> Yeah there are plans to improve the UI for all types but not sure how deep it can go.

Well you already have a nice UI for all the basic types in place, so all that is missing (yeah I know bold words) is some form of recursion to replicate this UI for the types `array` and `object`.

> And the documentation is available here - https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

I know where the docs are. What I wanted to say: as a newcomer you'll glance over the examples and see the basic types: `number`, `enum`, `string` and `boolean`. While not written there, it's quite easy to jump to the conclusion that nothing more complicated is possible, because the docs don't mention it (especially if one is not familiar with JSON schema definitions). So what imho would help here, would be to add a more complex example of a JSON schema (thus people will be easier made aware of that).

**Comment by sandy081** [comment]
We have samples repo that list various samples - https://github.com/microsoft/vscode-extension-samples/blob/master/configuration-sample

Please feel free to contribute.
