### ISSUE TITLE
Files leaked to github by using vscode

### ISSUE THREAD

**Issue by asianati** [microsoft/vscode#82158]
Hello,

i am using vscode for my c/c++ development and recently a very strange thing happened. 
one of my source files was sent to public internet(Microsoft, github) without my consent. I have a monitoring app on my machine to alert me when security risks are exposed and that's how i found out about this incident.

the command which triggered this file upload was:

/usr/bin/git->/vscode/code --nolazy --inspect 13242 /vscode/resources/app/out/bootstrap-fork --type=extensionHost

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 3.10.0-693.11.6.el7.x86_64

i wonder if this is related to a crash or some other activities in vscode

thanks
Ali

**Comment by jrieken** [comment]
/needsMoreInfo

Are you sure that a source file has been send? That would be surprising and concerning. From your repot It's a little hard to understand if the process in question was git or code? If the latter then your information hints towards the extension host, e.g any extension can in theory do that. So, I'd check the list of installed extensions. 


In case this was not a source file, just VS Code contacting the internet, revisit the list of setting that control online services (telemetry etc). Select the Gear Icon > Online Service Settings to revisit and disable them. 

<img width="331" alt="Screenshot 2019-10-09 at 16 37 30" src="https://user-images.githubusercontent.com/1794099/66491783-a03e6500-eab3-11e9-99a0-2168064c1c41.png">

**Comment by asianati** [comment]
the leak was a source file plus some git related file from .git folder. Report exactly points to the file and its location.

 at the time of incident i had 3 extensions installed: C/C++ and GItLens.

after this incident i disabled all telemetry stuff and non Microsoft extensions

the file has been leaked to these ip addresses

93.184.215.201
65.55.44.109
184.84.66.166
140.82.113.5

**Comment by jrieken** [comment]
> /usr/bin/git->/vscode/code --nolazy --inspect 13242 /vscode/resources/app/out/bootstrap-fork --type=extensionHost

Ok, can then please explain this line then? How should I read/understand this? Is `/usr/bin/git` the executable accessing the file or `/vscode/code`?
