### ISSUE TITLE
Extensions UI

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8215]
- [x] win - @alexandrudima 
- [x] mac - @weinand 
- [x] linux - @Tyriar 

We have introduced a new viewlet to improve the extensions management scenario. All the old extension management funcitonality is preserved. Verify:
* you can browse extensions from the marketplace
* you can install / uninstall an extension
* you get notified that there is an extension upgrade
* you get extenion recommendations based on your project
* clicking on an extension shows the extension description
* extension list is synchronized accross multiple vscode instances

Note: this feature has been developed by @joaomoreno however since he is on vacation this week assign all issues to @isidorn

**Comment by bgse** [comment]
@isidorn What about the 'enable extension' thing after you've installed, or is that gone already (didn't update my insiders today)?

**Comment by shanselman** [comment]
In the Insiders build I'm not seeing "Ext install foo" working anymore. I hope we keep that!

**Comment by isidorn** [comment]
@bgse enable / disable will come in the future. Can you please create a seperate bug for the issue you just described - thank you.

@shanselman in the latest version of vscode ext install works as following - hope that works for you also
![extinstall](https://cloud.githubusercontent.com/assets/1926584/16406649/b1589572-3d0f-11e6-8c6b-59aac7d77553.gif)

**Comment by isidorn** [comment]
@bgse I think #8298 captures the issue you outlined quite well - please comment on the issue if there is something missing
