### ISSUE TITLE
Typing a closing bracket when one already exists should skip over it

### ISSUE THREAD

**Issue by ebatsin** [microsoft/vscode#82163]
- VSCode Version: 1.38.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Open a new empty tab (any language will do. I saw this problem on javascript & C++)
2. Type `myFunc()` (do not copy paste)
3. When typing the opening parenthesis, it will auto-complete the closing one
4. Type the closing parenthesis (`)`). This should move your cursor to the right of the existing closing parenthesis instead of creating a new one.
5. Now, move your cursor back in between the opening & closing parenthesis.
6. Type the closing parenthesis
7. Now, a closing parenthesis is added before the existing one

 - Depending on the context, doing the same thing (typing a closing parenthesis) gives different outcomes which is weird.
 - I'm pretty sure this behavior changed recently. I have always typed `)` instead of *right arrow* to go over parenthesis and it stopped working on this release.
 - This behavior is the same for all of the following: `() [] {}`

Here is an example of what I'm talking about:
[imgur gif](https://i.imgur.com/ZsiQLVm.gif)
The first time I go over the closing parenthesis, I typed a `)`.
The second time, it adds it before the existing one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ebatsin** [comment]
I didn't searched with the right keywords. Didn't found the already existing issues.

The solution is adding the setting `"editor.autoClosingOvertype": "always"` for anyone having the same problem.

Closing now

**Comment by dark-swordsman** [comment]
Thank you, that worked! I know it was set to "always" before, but then it was unset.

They've been making some decisions recently, or have been causing bugs, that make workflow impossible. For example, `Ctrl + Enter` used to auto-replace all matching items in the find and replace window. Now they changed it, and changing it back doesn't fix it and is bugged.
