### ISSUE TITLE
Debugging simple javascript file triggers lengthy download

### ISSUE THREAD

**Issue by markkra** [microsoft/vscode#82167]
Issue Type: <b>Bug</b>

Wanted to step through some simple JS functions and went to  kick off a simple node debug session only to have to wait a super long time for OmniSharp and .NET Core Debugger to load. What the heck does C# and .NET core have to do with node debugging?

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide exact steps that you used and configuration in `launch.json`?
