### ISSUE TITLE
Branch selector combobox 

### ISSUE THREAD

**Issue by stefanofavero** [microsoft/vscode#82160]
Issue Type: <b>Bug</b>

the combobox to select a git branch can be closed only by selecting one of the branches. Add the possibility to close it by clicking outside, like the run command combobox

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.10.0
ng-template|Ang|0.802.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
gitlens|eam|10.1.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
vscode-peacock|joh|3.1.5
mssql|ms-|1.6.0
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.0
angular2-inline|nat|0.0.17
material-icon-theme|PKi|3.9.1
java|red|0.50.0
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
local-history|xyz|1.7.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
That is the default behaviour. We purposefully made it sticky since it happens often that you need to navigate outside VS Code in order to make the decision of what branch to choose.
