### ISSUE TITLE
focused node always white (foreground) in debug window

### ISSUE THREAD

**Issue by chuling** [microsoft/vscode#82165]
It seems that, while in debug mode, vscode set foreground for the focused item in list to `#ffffff`, and **I didn't find any way to change that behavior.**

This behavior leads some "bug" for material-like design, in which the focused item doesn't have background. 

See <https://github.com/chuling/vscode-theme-github-light/issues/4>.

And the popular material theme

![image](https://user-images.githubusercontent.com/23468295/66498129-2b3d5080-eaf0-11e9-995d-4874b614f0dd.png)

It's wired that `list.activeSelectionForeground` doesn't have effect in debug mode, for **any focused item in debug window**, their foreground was set to `#ffffff`.

*****
update

I check vscode's src, it seems that `listFocusAndSelectionBackground` and `listFocusAndSelectionForeground` are controlling this behavior.
<https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/base/browser/ui/list/listWidget.ts#L872-L873>

but there is no registered entry in `src/vs/platform/theme/common/colorRegistry.ts`
<https://github.com/microsoft/vscode/blob/ab0eb6de2d5fb4563385d98f302f78caa1767efd/src/vs/platform/theme/common/colorRegistry.ts#L230-L247>

**Comment by isidorn** [comment]
Please file this against the theme extension you are using. Since the colors they are using seem to cause this.

**Comment by chuling** [comment]
I think this was not caused by the extension, because **ANY THEME EXTENSION, INCLUDING THE BUILDIN THEME**, their focused item in list was colored with pure white foreground.

Extension I am using: <https://github.com/chuling/vscode-theme-github-light/> 
 <https://github.com/material-theme/vsc-material-theme> and many others...

Just download any theme you name, and begin debugging, you will see this problem...

**Comment by isidorn** [comment]
I can not reproduce this with the Github-light vscode theme that I use. Neither with our builtin theme.
Please try reproducing with vscode insiders  https://code.visualstudio.com/insiders/
I thikn you have some extension which breaks this.

![Screenshot 2019-10-10 at 16 40 42](https://user-images.githubusercontent.com/1926584/66579217-c1b75380-eb7c-11e9-9397-57229c48bed7.png)
![Screenshot 2019-10-10 at 16 40 59](https://user-images.githubusercontent.com/1926584/66579218-c1b75380-eb7c-11e9-93e8-8f61f76d093b.png)

**Comment by chuling** [comment]
@isidorn Sorry, maybe I am not express clearly :sob: :sob: :sob:, you have to focus your mouse on the list to see this problem (while debugging) ... I will post some screenshot later :joy: :joy: :joy:, and thanks for replying so quickly.

**Comment by chuling** [comment]
* material theme lighter

![image](https://user-images.githubusercontent.com/23468295/66657393-551e8080-ec72-11e9-9f51-91bc8809061a.png)

* Github-light vscode theme you use

![image](https://user-images.githubusercontent.com/23468295/66657423-61a2d900-ec72-11e9-91ba-bf32c57c94b9.png)

**Comment by chuling** [comment]
Just confused that why these node respect `list.activeSelectionBackground` but not respect `list.activeSelectionForeground`...:confused::confused::confused:

So the only solution is to add background for these active selected node...

Anyway, thanks for replying.

**Comment by misolori** [comment]
So it does look like there is a bug, we explicitly set the foreground color in:

https://github.com/microsoft/vscode/blob/2d87c95e53471539a1fab25a5367bb3eeffc9456/src/vs/workbench/contrib/debug/browser/media/debug.contribution.css#L175-L179

I'm going to change this to make it inherit, so that it will properly themes when you set `list.activeSelectionForeground`:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35271042/66662501-cbcd6680-ebfd-11e9-8e1b-396c8fe3c96c.png">

**Comment by misolori** [comment]
@isidorn we should also take a look at the hovers of these list items as those also run into a similar problem where there are no color tokens:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/35271042/66662938-9e34ed00-ebfe-11e9-83aa-d4b98c0b79e3.png">

Should we apply the same treatment?

**Comment by isidorn** [comment]
@misolori yes we could introduce token colors for this, I am not against this, we just never did it. If you would like to add them let me know and I can provide pointers.
