### ISSUE TITLE
Unsaved file removed from editor when 'run in terminal'

### ISSUE THREAD

**Issue by Tiltowaite** [microsoft/vscode#82166]
Issue Type: <b>Bug</b>

Repro may require some extensions to support running python code. 

repro: at CMD line "code foo.py" to create and start editing a new python file.  Type some code: "import os".  Do NOT save the file (editor tab shows circle).  (Autosave is turned on, but only applied to existing files).  The "Run in terminal" chevron is in the upper right. Press the "run in terminal" button.  The file is saved to disk and runs in the terminal, but the editor tab for "foo.py" is closed in the editor.  I can re-open the file using the File->open recent menu, but I did not expect to need to. 

If 'foo.py' is the only file open in the editor, Code stays open with no files open. If there are other files open, Code keeps the other editor tabs.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.46GB (6.60GB free)|
|Process Argv|foo.py|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
graphviz-preview|EFa|1.3.3
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
powershell|ms-|2019.9.0
team|ms-|1.149.2
vscode-print|pdc|0.7.12
show-offset|ram|0.0.4

</details>

**Comment by bpasero** [comment]
I dont know what this command is.
