### ISSUE TITLE
Integrated Terminal Appends ^V to the prompt when switching spaces

### ISSUE THREAD

**Issue by ReagentX** [microsoft/vscode#82175]
- VSCode Version: 1.38.1

    Version: 1.38.1
    Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
    Date: 2019-09-11T13:31:32.854Z
    Electron: 4.2.10
    Chrome: 69.0.3497.128
    Node.js: 10.11.0
    V8: 6.9.427.31-electron.0
    OS: Darwin x64 18.7.0

- OS Version: 10.14.6 (18G103)

Steps to Reproduce:

1. Open VSCode in fullscreen mode
2. Open another app in the main desktop so that you have two spaces: one desktop, one VSCode
4. Every time you switch between spaces, ^V will be appended to the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
How are you switching spaces?

**Comment by ReagentX** [comment]
⌃→ and ⌃←

**Comment by Tyriar** [comment]
I can't repro unfortunately and haven't had any other reports on this, let me know if you find out any more details.
