### ISSUE TITLE
Unsaved file warning for deleted files inside a deleted folder

### ISSUE THREAD

**Issue by aliry** [Microsoft/vscode#8217]
- VSCode Version: 1.3.0-insider
- OS Version: win server 2012 R2

Steps to Reproduce:

1. create a new folder and create a file inside it.
2. add some content to the new file and save
3. add more content to the file and do **NOT** save
4. one unsaved file should be marked in VSCode Open Editors section in explorer tab
5. Right click on the newly created folder and delete the folder

**Actual**:  Open editors section still shows "1 unsaved" label while that file is deleted with folder delete.
It's kind of confusing what the unsaved file is and there is no way to ignore or save it in the UI unless closing the VSCode.

**Expected**: If I'm deleting a folder it means I don't care about the files inside that folder whether they are saved or not. Therefore, VSCode should ignore all unsaved files inside the deleted folder.

**Comment by bpasero** [comment]
We cannot just throw away the dirty file because it contains user written content. This is to prevent data loss.

**Comment by aliry** [comment]
Then VSCode need to have better way to show the unsaved file. because right now it only shows a label that there is an unsaved file but there is no way for the user to save or ignore that unless closing the VSCode.

**Comment by bpasero** [comment]
@aliry does this still happen in insiders build (http://code.visualstudio.com/Download#insiders)?

**Comment by aliry** [comment]
yes, on version 1.3.0-insider

Its interesting that it actually asks user to confirm the deletion of the folder and all content inside it while it keeps the dirty files content as unsaved. Even after clicking on save icon the unsaved label does not go away.
![1](https://cloud.githubusercontent.com/assets/6610388/16549300/474d34d2-4163-11e6-95e1-175a6f91abd7.png)


I still think when user confirms the deletion of a folder with all its content there is no reason for the editor to keep the unsaved content. At least other edits (Atom, Sublime) does not do that.

**Comment by bpasero** [comment]
I filed https://github.com/Microsoft/vscode/issues/8704 for the bug about the dirty files closing. This is a regression.
