### ISSUE TITLE
Terminal always starts blank

### ISSUE THREAD

**Issue by gandroz** [microsoft/vscode#82176]
- VSCode Version: 1.38.1
- OS Version: Ubuntu 18.04

The terminal always starts blank and I am not able to write anything. I tried several shells, all renderer types but nothing works.

**UPDATE**
I tried with the new 1.39 version (septembre release) and still got the issue. Notice that I dont have and cant select a default shell. I set one in the settings but nothing visible nor available in the terminal bar

![image](https://user-images.githubusercontent.com/38106881/66535722-85d2ae80-eae8-11e9-8b9b-e4f464432541.png)
![image](https://user-images.githubusercontent.com/38106881/66535837-f8dc2500-eae8-11e9-9073-748fc41cea52.png)

**Comment by Tyriar** [comment]
Can you enable trace logging and check the logs when you try open a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
