### ISSUE TITLE
Integrated terminal double click doesn't use comma as word separator

### ISSUE THREAD

**Issue by Ulchie** [microsoft/vscode#82173]
Issue Type: <b>Bug</b>

Just echo any words separated by comma and double click and you'll note the selection doesn't use ',' as a word boundary.

This is particularly annoying when selecting push tags, branches, etc from a git log:

commit abcdefgzagd (HEAD -> myBranch, tag: myBranch-1000, origin/myBranch, origin/HEAD)

Double clicking on 'myBranch' will result in a selection of 'myBranch,'

This looks similar/partially related to https://github.com/microsoft/vscode/issues/21125, but that bug is explicitly referring to links, whereas this bug is less specific.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.4.0-145-generic

<details>
<summary>System Info</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.74.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.5
vscode-remote-extensionpack|ms-|0.17.0
vim|vsc|1.11.0
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
seito-openfile|Fr4|1.8.5
python|ms-|2019.10.41019
cpptools|ms-|0.26.0-insiders3
multi-command|ryu|1.3.0
clang-format|xav|1.9.0

</details>

I'm on a MacBook Pro running MacOS Mojave.

**Comment by Ulchie** [comment]
Looks like there is a wordSeparator option in xterm.js that can be set.

Default value is 
`wordSeparator: ' ()[]{}\'"''`

I'd appreciate an option to expose this so that I could set it myself. I might submit a PR myself

**Comment by Tyriar** [comment]
Maybe the default should change in xterm.js? @Ulchie I created https://github.com/xtermjs/xterm.js/issues/2463 if you want to make a PR over there, should just be a single character change, plus a simple test 😛

**Comment by Ulchie** [comment]
Well it also extends to colon. I’m not a Windows user but I would expect that excluding colon from the double click word boundary would be annoying for Windows paths so that’s why I suggested the option. I’d expect the behavior will need to differ by platform.

**Comment by Tyriar** [comment]
@Ulchie sounds good 👍

**Comment by sohailrajdev97** [comment]
@Tyriar I would like to take up this issue. Will try to raise a PR for this soon.

**Comment by sohailrajdev97** [comment]
I have raised a PR for this here #82366
