### ISSUE TITLE
circuit-board octicon is difficult to read on status bar

### ISSUE THREAD

**Issue by ChaosinaCan** [microsoft/vscode#82177]
Issue Type: <b>Bug</b>

The circuit-board octicon is very dense with VS Code 1.39.0, which makes it difficult to identify as a circuit board when it is on the status bar or any other location where it is very small. Unless you look at it very closely, it just looks like a square with some sort of pattern in the center:

![image](https://user-images.githubusercontent.com/760836/66517253-69af1d00-eaa8-11e9-8f3f-92a4f28811e8.png)

It would be easier to identify as a circuit board if there were fewer traces with larger pads in the center, like with the previous icon.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (14.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

**Comment by faldor20** [comment]
I have a similar problem with the omnisharp flame. it has gone from a flame to a cone blob. it is just far too hard to make it out in the corner of the display

**Comment by misolori** [comment]
@faldor20 there was some discussion around how the flame icon came about, see the comments in https://github.com/microsoft/vscode/issues/76909

**Comment by misolori** [comment]
We simplified the circuit board icon so it's easier to see:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/35271042/69073688-bad4f980-09e2-11ea-9e77-54ac0cc375d7.png">

**Comment by ChaosinaCan** [comment]
Looks much better. Thanks!
