### ISSUE TITLE
Git status on editor left and right show changes already commited

### ISSUE THREAD

**Issue by godiard** [microsoft/vscode#82172]
![Captura de pantalla de 2019-10-09 15-59-06](https://user-images.githubusercontent.com/4050778/66511780-01633a00-eaae-11e9-8593-0913fe2a325c.png)
Issue Type: <b>Bug</b>

1) Modify a file
2) Save
3) Commit
4) The file still show the lines highlited at left on green as not commited
5) Close the file and open again (I have other files opened on other tabs)
6) The status is still wrong

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.2.18-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (3.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python-coding-conventions|igr|0.0.4
kite|kit|0.98.0

</details>

**Comment by joaomoreno** [comment]
@godiard Can you reproduce this in other repositories?

**Comment by godiard** [comment]
Could not reproduce the issue later.  If you want, close the issue, and I can reopen with more information if happen again
