### ISSUE TITLE
[css] fix parsing of custom properties in @supports

### ISSUE THREAD

**Issue by James0x57** [microsoft/vscode#82178]
- VSCode Version: 1.39.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a CSS file with this code:
```css
.test {
    --validValue: , 0 0;
}
@supports not (--validValue: , 0 0) {
  .vscode-parsing-error {
      content: "";
  }
}
```

2. You'll get these errors:
![image](https://user-images.githubusercontent.com/7545075/66519383-d9bfa200-eaac-11e9-96f2-0f07113135aa.png)

Does this issue occur when all extensions are disabled?: Yes, no extensions installed

**Comment by aeschli** [comment]
Are you sure that starting with a comma is valid CSS?

https://www.sassmeister.com/ also shows an error on the comma ( I know that SASS, but also understands CSS).

**Comment by James0x57** [comment]
Hello @aechan 

Yes, I am certain.

Earlier versions of Safari on iOS erroneously counted it as invalid too, but that has since been fixed. You can feature detect that fix with this CSS I provided:
```css
@supports not (--validValue: , 0 0) {
  .vscode-parsing-error {
      content: "";
  }
}
```

## Here are some resources on the validity of the value

I've quoted the relevant pieces in a human-readable order for your convenience:

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Validity_and_values
> The classical CSS concept of validity, tied to each property, is not very useful in regard to custom properties. When the values of the custom properties are parsed, the browser doesn't know where they will be used, so must, therefore, consider nearly all values as valid.

https://drafts.csswg.org/css-variables/#invalid-variables
> variables can’t "fail early" like other syntax errors can

> A declaration can be invalid at computed-value time if it contains a var() that references a custom property with the guaranteed-invalid value [...] or if it uses a valid custom property, but the property value, after substituting its var() functions, is invalid.

https://drafts.csswg.org/css-variables/#guaranteed-invalid
> The initial value of a custom property is a guaranteed-invalid value.

> This value serializes as the empty string, but actually writing an empty value into a custom property, like --foo: ;, is a valid (empty) value, not the guaranteed-invalid value. If, for whatever reason, one wants to manually reset a variable to the guaranteed-invalid value, using the keyword initial will do this.

https://developer.mozilla.org/en-US/docs/Web/CSS/--*#Syntax
> Formal Syntax &lt;declaration-value>

https://drafts.csswg.org/css-syntax-3/#typedef-declaration-value
> The &lt;declaration-value> production matches any sequence of one or more tokens, so long as the sequence does not contain &lt;bad-string-token>, &lt;bad-url-token>, unmatched &lt;)-token>, &lt;]-token>, or &lt;}-token>, or top-level &lt;semicolon-token> tokens or &lt;delim-token> tokens with a value of "!". It represents the entirety of what a valid declaration can have as its value.

&lt;bad-string-token>, &lt;bad-url-token>, and &lt;delim-token> are variations of code points, typically beginning with "U+":
https://infra.spec.whatwg.org/#code-point

--------

[augmented-ui](http://augmented-ui.com/) relies heavily on this to compose dynamic clip-path values if you would like a real world example:
https://github.com/propjockey/augmented-ui/blob/master/augmented.css#L251

Thank you,
//James

**Comment by James0x57** [comment]
@octref @aeschli pinging in case the notification was lost over the weekend since the issue was closed early

thank you!

**Comment by aeschli** [comment]
@James0x57 Thanks for the pointers!

**Comment by James0x57** [comment]
@aeschli Could you please re-open this issue?

Values of a custom property should not be parsed for commas - they have no meaning in this context.

Safari on iOS had the same issue and they've fixed it.

SASS also has this issue but they only handle it incorrectly in the @supports statements now.

The only work around is to disable the entire problem-checking feature in Visual Studio

**Comment by James0x57** [comment]
Here is a minimal JSBin using this feature of CSS in case it's useful to you:
https://jsbin.com/kohogozoji/edit?html,css,output

The leading comma allows for dynamic, optional, composition of comma separated standard properties.

**Comment by trusktr** [comment]
Great catch! The main thing is that CSS variables can be composed, so for example this is valid:

```css
.foo {
  --a: anim;
  --b: 1s ,;
  --c: anim2 1s;
  --d: , anim3 2s;
  animation: var(--a) var(--b) var(--c) var(--d);
}
```

and now `animation` has the effective value `anim 1s, anim2 1s, anim3 2s`.

**Comment by James0x57** [comment]
Any chance of getting this back on the radar? In the last year since I filed this, VSCode has become my favorite editor but I still cannot use CSS Validation because of the false negative in the `@supports` statement:

![image](https://user-images.githubusercontent.com/7545075/99139832-d842a080-2601-11eb-9cc8-eb3449e7bdb8.png)

Thank you for your consideration
