### ISSUE TITLE
Add option to disable arrows in the explorer menu 

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#82183]
![image](https://user-images.githubusercontent.com/4319522/66523548-2c558a00-eabe-11e9-8e92-1039bd2cfce4.png)

I don't need additional arrows, I can already tell by the iconography that it is a folder.

**Comment by misolori** [comment]
File icons can actually define custom chevrons and decide to hide. See the [Ayu icons](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu) that do this:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/35271042/66535211-b822e280-eacd-11e9-9246-b232b5b61ea9.png">

I don't think we'd ever introduce this as a setting as our default (seti ui) doesn't show icons for a folder, so we'd let the file icons decide that.
