### ISSUE TITLE
Lines containing unicode characters in integrated terminal differ in height

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8219]
See https://github.com/sourcelair/xterm.js/issues/149, the fix will probably be added to the custom `style` element. The main thing to consider is how to allow line height customization and get the lines aligned correctly at the same time.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/149

**Comment by Treri** [comment]
@Tyriar Excuse me, was this problem fixed in 1.4.0 stable?

I downloaded the latest 1.4.0 stable, but still have this problem

![image](https://cloud.githubusercontent.com/assets/2631733/17474614/6af97098-5d89-11e6-9cae-f20da6e34a24.png)

the console top is cut in vscode terminal

**Comment by Treri** [comment]
And, different terminal height cut different height console top

![c](https://cloud.githubusercontent.com/assets/2631733/17475437/9dd52c2e-5d8d-11e6-8d66-fae9ef796504.gif)

**Comment by Treri** [comment]
The last, If I was on the bottom of terminal, when I input or click, the console output will scroll up automatically.

**Also, the `ls` output is firstly correct(no new line for every file), then it become uncorrect(`drwxrw-rw-` goto next line)**

![d](https://cloud.githubusercontent.com/assets/2631733/17475490/cd82f2b2-5d8d-11e6-9049-894761490168.gif)

**Comment by Treri** [comment]
Oh!

I found the problem. I extract the new vscode(1.4.0) to /Application to override the old one( version 1.3.1). So these problems is not solved.

Just now, I completely deleted old vscode in my `/Application` folder, then extract the new vscode into /Application, the console top is not cut!

I think the problem is OS X not removed the old files completely when I select override the old one with new vscode. so the vscode I used is a version mixed the files in 1.3.1 and 1.4.0.

Maybe some users like me should remove old vscode completely to solve these problems.

**Comment by Tyriar** [comment]
@Treri it was supposed to be fixed in v1.4.0 yes, do you have a custom line height set by chance in settings?

**Comment by Treri** [comment]
@Tyriar no, I did not set line-height in my setting

my setting is below, the last `terminal.integrated.fontFamily` was added today.

```json
// Place your settings in this file to overwrite the default settings
{
  //-------- Editor configuration --------
  "editor.fontFamily": "Source Code Pro",
  "editor.fontSize": 13,
  "editor.rulers": [80, 100],
  "editor.tabSize": 2,
  "editor.wrappingColumn": 0,
  "editor.renderIndentGuides": true,
  "diffEditor.ignoreTrimWhitespace": false,

  "window.reopenFolders": "none",

  "projectManager.openInNewWindow": false,

  "terminal.integrated.fontFamily": "Menlo, Monaco, 'Courier New', monospace"
}

```

**Comment by Tyriar** [comment]
@Treri thanks! Also can you copy special characters in your prompt and paste them here?

**Comment by Treri** [comment]
@Tyriar 
Sorry, I did not know what the special characters are. I just use oh-my-zsh default theme `robbyrussell`

The theme file and prompt are https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme

**Comment by Tyriar** [comment]
I mean the arrow and cross characters in your prompt

**Comment by eladcandroid** [comment]
I'm using VSCode 1.4 and have the same problem like @Treri described with oh-my-zsh default theme.

**Comment by Tyriar** [comment]
@Treri @eladcandroid do you mind testing if this is still happening in [Insiders](https://code.visualstudio.com/insiders)? Stuff to do with line height was changed with the introduction of the scroll bar so it might have been fixed.

**Comment by Treri** [comment]
@Tyriar 
I tested the insider version. the console problem have been fixed. but I can't scroll to console bottom. I can only goto console bottom when I input something. But If I press enter, the console output will goto top again.

And I can't see the scroll bar?

![insider2](https://cloud.githubusercontent.com/assets/2631733/17641531/9013f120-6156-11e6-9040-ba88dcb385e5.gif)

**Comment by Tyriar** [comment]
Hmm, I think oh-my-zsh may be using the application keypad mode then which is what i was using to turn off the scroll bar, otherwise it would show up in programs like vim.

**Comment by Treri** [comment]
@Tyriar I will use bash to test again

**Comment by Treri** [comment]
@Tyriar The problem is oh-my-zsh/lib/key-bindings.zsh#L14

```sh
# Make sure that the terminal is in application mode when zle is active, since
# only then values from $terminfo are valid
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
  function zle-line-init() {
    echoti smkx
  }
  function zle-line-finish() {
    echoti rmkx
  }
  zle -N zle-line-init # By treri: If I comment out this line, my terminal works well
  zle -N zle-line-finish
fi
```

**Comment by Tyriar** [comment]
I believe this issue is fixed. The situation will improve further after https://github.com/Microsoft/vscode/issues/18588 is resoled
