### ISSUE TITLE
Large Webview.HTML on a remote connection is unusable

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#82190]
This is somewhat related to this issue:
https://github.com/microsoft/vscode/issues/26784

Our extension (https://marketplace.visualstudio.com/items?itemName=ms-python.python) has webviews on the order 16 or 17MB. 

When opening a webview over some remote-ssh connections it can take minutes to load.

It would be great if there was some way to help speed this up

Maybe:
- Some sort of compression on the webview html
- A way to load the html into the UI (outside of webview creation) and have the webview load it from there

**Comment by mjbvz** [comment]
Can you share some details about why the html is so large? Is it all scripts? Data?

**Comment by rchiodo** [comment]
Dependencies mostly. We pull in a lot of stuff

Here's our dependency list:
https://github.com/microsoft/vscode-python/blob/master/package.datascience-ui.dependencies.json

There's also a number of svg files that are inlined, but I believe it's mostly dependencies.

**Comment by rchiodo** [comment]
We webpack this all up into a single js file.

**Comment by mjbvz** [comment]
Some quick thoughts:

- Can you use code splitting?

- Does all this functionality need to live in the webview or can you extract some of it back the extension. Ideally the webview should just be the view layer

**Comment by rchiodo** [comment]
Not sure what code splitting is? You mean split the js into smaller pieces? 

The functionality is displaying a jupyter notebook. Our dependencies revolve around showing that. 

Regardless of what it is, it seems like there could be a way other than don't have so much stuff to get this to work? If we had a way to preload the html, or at least just get it across to the UI side, that would solve most of the problem.

**Comment by rchiodo** [comment]
I don't think code splitting helps as we don't have a way to load the js later? Perhaps I'm missing something. Would it be possible to load the js later dynamically? The overall time would be the same I believe. 

Or maybe something that loads a stub that then through a message passes the JS zipped. The stub on the page then unzips the js and loads it into the frame? Hmm.

**Comment by rchiodo** [comment]
That would make it 3MB instead. So 4 times faster. Still 15 seconds to load though not including unzip time.

**Comment by rchiodo** [comment]
Having some caching mechanism would still be a great help even if we reworked everything to load the js after zipping it. Otherwise the user has to wait 15 seconds every time they open a notebook file. 

The remote docs talk about [UI ](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types) extensions being on the UI side. Can we have code in a UI extension or are they simply data? We might be able to use that combined with the dynamic script update to cache the data ourselves.

**Comment by mjbvz** [comment]
Check out documentation on splitting here: https://webpack.js.org/guides/code-splitting/ If the notebook has no graphs for example, you should not need to load d3 and friends. May take some tweaking but I believe it should work for webview

---

Yes UI extensions are stored on the client in the remote case. This should make loading faster (although you should ideally always target under ~1MB or so on initial load for the best user experience). However this would require you to split the python extension into workspace and ui components

**Comment by mjbvz** [comment]
I think this request is already covered by #79147
