### ISSUE TITLE
Updating Visual Studio Code Twice

### ISSUE THREAD

**Issue by fadihania** [microsoft/vscode#82197]
Issue Type: <b>Bug</b>

It seems like VSCode has two separate instances running on machine, one used when opening a folder or Workspace and the other when opening a single file.
I always have to update VSCode twice once for instance I use to open folders/workspaces and a second for instance running single files.
To reproduce that issue:
 - Update VSCode to latest code while opening a folder
 - Close VSCode
 - Open a single file using Windows context menu Open with Code
 - Check version, it should be the previous version and you still need to update that instance again to newer version

Currently, this instance I'm submitting the bug from is on 1.38.1 but I've already updated the folder/workspace instance to 1.39. So, have both running on my computer at the same time but I'll be updating it shortly.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
If you have two installations in your computer, it's only normal that you get two updates. If you don't want two installations, find them and delete one of them.
