### ISSUE TITLE
comment marks don't work

### ISSUE THREAD

**Issue by Ankras78** [microsoft/vscode#82191]
Issue Type: <b>Bug</b>

Hi! accured some bug:
Comment tools like `"// <?\p\h\p ... ?>"`, `"/* <?php ... ?> */"`, `"<!-- <?php ... ?> -->"` don't work properly. Don't make `"<?php ... ?>"` comment-colorised.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Ankras78** [comment]
pls don't delete "<?php ... ?> " - problem axactly with this part of code !!!

**Comment by Ankras78** [comment]
![1](https://user-images.githubusercontent.com/54276616/66531023-ee368580-eb12-11e9-9966-f17a295085d9.jpg)
![2](https://user-images.githubusercontent.com/54276616/66531032-f2fb3980-eb12-11e9-93ad-f5c6085e5270.jpg)

**Comment by Ankras78** [comment]
What does "new release" mean? Have to wait for VSCode update? I'm new on Github, sorry for the stupid questions ))

**Comment by alexr00** [comment]
Our bot adds the "new release" label when we have just released (in this case 1.39) and you are seeing the issue on the new release.

**Comment by alexr00** [comment]
Does this reproduce with all extensions disabled?
Can you provided a complete copy/pastable example?

**Comment by Ankras78** [comment]
![3](https://user-images.githubusercontent.com/54276616/66551654-8ef76600-eb50-11e9-8f63-b2db81390cf5.jpg)


<select id='trns_sort-actions' class='trns_sort-select actions'>
    <option value=''>- actions -</option>
    <option value="cash_indrpbx">propbox</option>

    <option value="chips"><?=$titles[$lng][118]?></option>
</select>

**Comment by roblourens** [comment]
I think this is ok. The PHP is still executing, it's not commented out by html comments.

```
<html>

<!--
<?php
echo "foo"
?>
-->

</html>
```

output:

```
<html>

<!--
foo-->

</html>
```
