### ISSUE TITLE
Markdown: color of numbers in code blocks is not suitable with light theme at Preview

### ISSUE THREAD

**Issue by ganxy1028** [microsoft/vscode#82199]
In Markdown preview with light theme, numbers in code blocks are not clearly distinguishable because of their color. It will be good if a different color can be switched in light theme mode

![image](https://user-images.githubusercontent.com/26629457/66537698-f9f66c00-eb53-11e9-85ab-0ae43ea800c8.png)

It seems that in `/extensions/markdown-language-features/media/highlight.css` , the following part may add a `.vscode-light` switch. Thank you!

 ```css
.hljs-number,
.hljs-class {
	color: #B8D7A3;
}
```

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by ganxy1028** [comment]
Actually, code itself does't matter this issue. It influences on any kind of code with numbers.

[test.txt](https://github.com/microsoft/vscode/files/3715228/test.txt)

**Comment by jfhr** [comment]
Hey, I am a new contributor here. I want to give a try on this issue.

**Comment by ganxy1028** [comment]
> Hey, I am a new contributor here. I want to give a try on this issue.

Thanks very much for your contribution.
I have learned `.css` code after opening this issue, and then opened a PR #82453 after yours, which resets the colors of more than numbers. It may be mine to be merged, but greatly appreciate your help.
