### ISSUE TITLE
"Replace all" icon is not centered in search viewlet

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82192]
@misolori?

![image](https://user-images.githubusercontent.com/323878/66531575-20b79280-eac1-11e9-9192-057970305293.png)

**Comment by misolori** [comment]
Good catch, fixed:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/35271042/66535820-bc4fff80-eacf-11e9-8bc4-176484bc65c2.png">
