### ISSUE TITLE
VS Code very slow. Make it fast like Notepad++ or Sublime Text. Develop with C++

### ISSUE THREAD

**Issue by vkamath2018** [microsoft/vscode#82207]
**EVEN THOUGH VS CODE IS EXCELLENT TO USE**

VS Code very slow. 

Please 
make it fast like Notepad++ or Sublime Text. 
Develop (rewrite) VS Code with C++

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
