### ISSUE TITLE
Markdown preview: incorrect preview for ordered lists when list numbering doesn't start at 1

### ISSUE THREAD

**Issue by sivaraam** [microsoft/vscode#82205]
Issue Type: <b>Bug</b>

1. Create a markdown file.
2. Copy the following to the file
    ```
    ## My list
    8. Item 1
    16. Item 2
    24. Item 3
    ```
3. See the preview for the above markdown.

### Expected results
The numbering should start at 1.

### Actual results
The numbering starts at 8 (the first number of the ordered list).

## Reference
[Markdown: Syntax - Daring Fireball](https://daringfireball.net/projects/markdown/syntax#list)

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Our markdown preview targets common mark so this is the expected behavior: https://spec.commonmark.org/0.29/#example-235

Github's markdown also handles ordered lists this way
