### ISSUE TITLE
Default settings does not retain position in document when put in background

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8220]
- VSCode Version: Code - Insiders 1.3.0-insider (41f53d27a8cb477130f84116c78f43ddacbaf24b, 2016-06-27T05:15:21.343Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open settings
2. Focus Default Settings editor
3. Scroll down, put cursor somewhere
4. Open a file in the same editor
5. Open Default Settings tab, notice the cursor is at `0,0` in the document

**Comment by bpasero** [comment]
Yeah we do not store view state for readonly editors. There is another issue on it that Isidor filed for debug.
