### ISSUE TITLE
vscode://file/... does not work any longer

### ISSUE THREAD

**Issue by NKarolak** [microsoft/vscode#82212]
Issue Type: <b>Bug</b>

Since the update to 1.39, opening files running vscode://file/myfilepath does not work anymore: VS Code will open (if not started yet) correctly, but the file would not be opened.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (14.34GB free)|
|Process Argv|--open-url -- vscode://file/C:/Development/Repositories/DevOps/AMP-On-Premise/RoutingSkillSetEntries.Page.al|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.19
gitlens|eam|10.1.1
docker-explorer|for|0.1.6
vscode-guid|hea|1.4.18
nav-cside-color-theme|mar|0.0.7
al|Mic|4.0.176004
powershell|ms-|2019.9.0
crs-al-language-extension|wal|1.1.17

</details>

**Comment by MagTun** [comment]
Same here: since the 1.39.0 update , I can't use the url to open files in vscode.

**Comment by NKarolak** [comment]
@MagTun As a workaround, you can easily downgrade by installing the previous version https://update.code.visualstudio.com/1.38.1/win32-x64/stable (without uninstalling anything first)

**Comment by joaomoreno** [comment]
Broken by https://github.com/microsoft/vscode/commit/8e99945e4165265cc889a11023dd74dd3756dd27#diff-fc6683f92061646324644f2cd92304cfR591

**Comment by MagTun** [comment]
Thanks @joaomoreno  for fixing this so quickly! 

I run the .exe on the link given by @NKarolak to go back to the version 1.38.1, but vscode wasn't downgraded, so I still on 1.39. Is there a was to install a specific commit or to manually edit a vscode file?

**Comment by NKarolak** [comment]
@MagTun Did you remember to turn off automatic updates first (using the settings wheel at the bottom left corner), prior to installing?

**Comment by joaomoreno** [comment]
**Verification:**

- Open Command Palette and run `Developer: Open URL`
- Paste `vscode://file/PATH/TO/FILE` and replace `/PATH/TO/FILE` with a proper path to a file

The file should open.

**Comment by mi5ha** [comment]
The problem is that when you call vscode://file/PATH/TO/FILE externally it doesnt work. For example if you paste that URL in browser it used to work and it doesnt in the current build.

**Comment by piascikj** [comment]
@joaomoreno I'm on version 1.39.1 and still can't open files with the URL.  Will the fix be released soon?

**Comment by joaomoreno** [comment]
Yes, it will be fixed in 1.39.2, coming soon.

**Comment by MagTun** [comment]
I have installed the 1.39.2 version and it's working again! Thanks a lot!
