### ISSUE TITLE
open a new tab  will create black fullscreen on fullscreen mode

### ISSUE THREAD

**Issue by cp1001** [microsoft/vscode#82216]
- VSCode Version: from 1.36 to latest 1.39.0.
- OS Version:macOS 10.12.6

Steps to Reproduce:

1. Open VSCode, then click fullscreen button.
2.Select 'Window -> New tab'.
Then a whole  black full screen will created.I have to force quit VSCode to dismiss the screen.

Does this issue occur when all extensions are disabled?: Yes

VSCode 1.35 works fine on my mac, So please check what changes on 1.36.
If i open several tabs on none fullscreen mode, then click fullscreen button, it works fine too.

**Comment by bpasero** [comment]
Sorry, but we do not support native tabs in 10.12 anymore.

**Comment by bpasero** [comment]
See: https://github.com/microsoft/vscode/issues/76537
