### ISSUE TITLE
Invisible dirty icon

### ISSUE THREAD

**Issue by kdlslyv** [microsoft/vscode#82213]
- VSCode Version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. set `"workbench.editor.tabCloseButton": "off"`
2. dirty icon is blank

Does this issue occur when all extensions are disabled?: Yes

![nodirtyicon](https://user-images.githubusercontent.com/13890151/66548505-a713b900-eb41-11e9-9890-673aec273483.png)

**Comment by bpasero** [comment]
@misolori my guess would be a regression from icon font

**Comment by misolori** [comment]
Fixed via 21ec3bc89310d6e458a703d4cfc09c6e9e082a20
