### ISSUE TITLE
Update JSON Schema for JS and TS

### ISSUE THREAD

**Issue by yuit** [Microsoft/vscode#8221]
We are updating schema store [here](https://github.com/SchemaStore/schemastore). Could you guys update your schema to include new flag as well? thanks you !

Also, just wonder how you guys consume JSON schema for tsconfig.json as I don't see any of them [here](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/schemas/tsconfig.schema.json)

**Comment by aeschli** [comment]
The tsconfig JSON schema is always fetched from http://json.schemastore.org/tsconfig. See the association here: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L238
We added an additional property `allowJs` which I see is now available.

For the jsconfig schema we used our local version as there was none on the schemastore before. I will update to use the one from schema store.

**Comment by aeschli** [comment]
@yuit In our own version of the jsconfig we updated some of the descriptions of those options that only apply when downlevel compiling. Where can I file a feature request to consider this in http://json.schemastore.org/jsconfig ?

**Comment by yuit** [comment]
@aeschli you can make an edit and send a PR directly to the schemastore.

**Comment by aeschli** [comment]
Created https://github.com/Microsoft/TypeScript/issues/9387 directly against TS.

**Comment by aeschli** [comment]
We now use the jsconfig schema from http://json.schemastore.org/jsconfig
