### ISSUE TITLE
Cannot type numbers in terminal when switching to Chinese input

### ISSUE THREAD

**Issue by zingdle** [microsoft/vscode#82215]
Steps to Reproduce:

1. Switch to Chinese input and open terminal.
2. Type number key, the number won't appear. Type same number keys several times then only one number shows up.
3. It occurs on both Powershell and Bash for WSL.

Does this issue occur when all extensions are disabled?: Yes

Environment:

```
Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Tyriar** [comment]
Which chinese input are you using?

**Comment by zingdle** [comment]
@Tyriar Default Microsoft Pinyin input on Windows 10

**Comment by Tyriar** [comment]
Can you elaborate a little? Seems to work here:

![pinyin](https://user-images.githubusercontent.com/2193314/66943982-1c2f3480-f001-11e9-855e-001530d30aa3.gif)

**Comment by zingdle** [comment]
I switched to an older version and the problem stays. Looks like it's not a vscode problem. Closing...
