### ISSUE TITLE
Changes dont show in SCM view

### ISSUE THREAD

**Issue by JohnstonCode** [microsoft/vscode#82220]
- VSCode Version: 1.39.0
- OS Version: Fedora 30

https://github.com/JohnstonCode/svn-scm/issues/681

![image](https://user-images.githubusercontent.com/10222719/66551625-5bf4a880-eb37-11e9-9af6-a06feab28227.png)

This issue is with the SVN extension. Changes that add folders dont appear. Sometimes toggling the view mode gets them to appear.

**Comment by jrieken** [comment]
Looks like the API can break the tree/list widget
