### ISSUE TITLE
Vs code terminal looks broken when resizing

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode#82221]
I attached a gif which shows exactly the problem :

![2019-10-10_11-27-05](https://user-images.githubusercontent.com/20374208/66551861-f0b7d000-eb50-11e9-8b78-e28e41888996.gif)

At first it works then , some more resizing and it brakes :) 

`Vs Code 1.39`

**Comment by Tyriar** [comment]
This is just a consequence of how pty-based terminals work
