### ISSUE TITLE
drag window with mouse cause ^c in the terminal

### ISSUE THREAD

**Issue by VCBE123** [microsoft/vscode#82228]
- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. open cscode 
2. drag window
![image](https://user-images.githubusercontent.com/30370620/66554882-50799f80-eb80-11e9-980b-db2c5d2b6685.png)

3. there will be ^c in the terminal

Does this issue occur when all extensions are disabled?: Yes!

**Comment by VCBE123** [comment]
![gifhome_640x432_15s](https://user-images.githubusercontent.com/30370620/66556421-c7179c80-eb82-11e9-9559-aeaa0b1400a2.gif)

**Comment by Tyriar** [comment]
I've never seen this before, ^C should only happen when you hit ctrl+c while the terminal is focused.
