### ISSUE TITLE
Editor Context Menu will do the actions on mouse up evnet

### ISSUE THREAD

**Issue by rhdlilj** [microsoft/vscode#82225]
- VSCode Version: 1.39.0
- OS Version: ubuntu 14.04 LTS

Steps to Reproduce:

1.Mouse  right button press down pop out the menu.
2.Do not move the mouse, and hold a short time.
3.Releasing the right button, if there is a item be selected, it will do the selected item actions.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rhdlilj** [comment]
Holding the mouse button down is trying to explain the problem.
In fact, I was selected the code and trying to copy it, but as clicking the mouse it do the paste.
That was feeling bad.

**Comment by rhdlilj** [comment]
![out](https://user-images.githubusercontent.com/55023294/66628608-e4f00a80-ec31-11e9-9e03-dfcc22d9b056.gif)
@sbatten

**Comment by sbatten** [comment]
@rhdlilj can you check your setting for `window.titleBarStyle`

**Comment by rhdlilj** [comment]
@sbatten "window.titleBarStyle": "custom"
I try "native", it's find, no this issue.
