### ISSUE TITLE
Update service notification spam

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#82229]
* I work on a train with spotty internet connection
* I see a notification from the update service (but I never interacted with the update service, e.g I never asked to check for updates...)

<img width="621" alt="Screenshot 2019-10-10 at 10 01 22" src="https://user-images.githubusercontent.com/1794099/66555198-8ef66680-eb4e-11e9-8141-e0270308896f.png">

**Comment by jrieken** [comment]
verified via code review. I will test this the next time I am passing through the Lötschbergtunnel

**Comment by joaomoreno** [comment]
![tunnel](https://media.giphy.com/media/zFCFZzX0KkJnW/giphy.gif)
