### ISSUE TITLE
Vs code can not open on mac os catalina

### ISSUE THREAD

**Issue by DarrenDe** [microsoft/vscode#82237]
- VSCode Version: 1.39
- OS Version: catalina

Steps to Reproduce:

can not open when I updated to Catalina
![Screenshot 2019-10-10 at 12 02 51](https://user-images.githubusercontent.com/43689169/66563541-e51ad800-eb55-11e9-9bac-31bb0228bd57.jpg)

**Comment by schka17** [comment]
you can even follow this procedure to start vs code https://support.apple.com/en-us/HT202491

**Comment by mobimation** [comment]
Check if it is blocked under System Preferences->Security&Privacy->General.
There may be an "Open anyway" option offered.

**Comment by schka17** [comment]
thanks, now its working
