### ISSUE TITLE
search: exclude doesn't work with full path 

### ISSUE THREAD

**Issue by WiliTest** [microsoft/vscode#82231]
Issue Type: <b>Bug</b>

I finally understood how the search work, but it's not logical to don't be able to exclude a file/folder using its full path.

Writing several paths (of folder or files) separated by a coma should work to exclude them.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
replacerules|bhu|0.2.7
transformer|dak|1.6.0
vscode-todo-plus|fab|4.14.1
code-runner|for|0.9.14
macros|ged|1.2.1
beautify|Hoo|1.5.0
vscode-favorites|how|1.4.0
reg|ion|1.0.1
vscode-opn|lfu|1.1.2
python|ms-|2019.10.41019
powershell|ms-|2019.9.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
html-preview-vscode|tht|0.2.5
local-history|xyz|1.7.0

</details>

**Comment by roblourens** [comment]
Can you give an example? I don't follow

**Comment by WiliTest** [comment]
An example: 
My vscode workspace is in `C:\Users\Me\Desktop\my_codes`
When I search the keyword "test" this file is showing: `C:\Users\Me\Desktop\my_codes\A\x.py` 

If in "files to exclude" I write `A\x.py,` it will be excluded. 
But If I write `C:\Users\Me\Desktop\my_codes\A\x.py,` it won't be excluded, which isn't really logical.

**Comment by roblourens** [comment]
It's better for these paths to just be considered as relative paths inside your workspace, so the settings will still apply if you copy your projects to a new location.
