### ISSUE TITLE
No inline breakpoint suggested for promise

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#82238]
Issue Type: <b>Bug</b>

1. Run [fixed] Express code from OpenTok without API key:

```
app.get('/viewer', (req, res) => {
  opentok.getCredentials('viewer')
    .then(credentials => res.render('pages/viewer', {credentials: JSON.stringify(credentials)}))
    .catch(error => res.status(500).send("" + error))
})
```

2. Break on catch to view error - you can't.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:03.188Z)
OS version: Linux x64 4.15.0-1056-oem snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.33GB (1.93GB free)|
|Process Argv|--force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
rainbow-csv|mec|1.3.1
vscode-typescript-tslint-plugin|ms-|1.2.2
indent-rainbow|ode|7.4.0
rainbow-tags|vol|0.0.3

</details>

**Comment by isidorn** [comment]
I do not see the correlation between the title of this issue and the description.
Isn't the issue that you can not break on error? Why mention inline breakpoints? Or did you try to add a breakpoint and it somehow failed?

**Comment by isidorn** [comment]
Well it is not needed. 
Are you saying that the inlinbe breakpoints are not suggeted on that line?
What is the actually issue here?

**Comment by roblourens** [comment]
This works for me: 
![image](https://user-images.githubusercontent.com/323878/66771984-78168380-ee70-11e9-8408-9df253973036.png)

Can you share your project so I can see how its transpiled?

Or, do you see them in chrome devtools? Or if you set an inline breakpoint in that position using shift+f9 does it work?

**Comment by CTimmerman** [comment]
Shift+F9 sets at the proper place while not debugging, but debugging appears to move the breakpoint to the start of the line (68:1). Also there was a tip about adding curly braces to the function.
![image](https://user-images.githubusercontent.com/9662163/66998777-1efb5980-f0d5-11e9-8a0c-5669613f65eb.png)

**Comment by roblourens** [comment]
What version of Node are you using? Seems like this works inconsistently in Node 12 due to an issue with the adapter...

**Comment by roblourens** [comment]
Should be fixed in the next insiders build

**Comment by CTimmerman** [comment]
What version of Node are you using?
```
cees@cees-XPS-13-9380:~/code/test$ node -v
v13.0.0-nightly20190802452b393c1f
```

> Should be fixed in the next insiders build

Sweet. Thanks!
