### ISSUE TITLE
salesforce developer org connecting issue

### ISSUE THREAD

**Issue by masthankhan1** [microsoft/vscode#82239]
My official mail id is masthan.khan@jadeglobal.com.

while i am trying to connect with salesforce personal   developer org it showing following error...
Steps I  had followed:
After creating  project,
I am authorising Org  with Custom URl,
after giving cutom URL giving Alias user name. 
then below errors are coming.
Kindly Help me..

Starting SFDX: Authorize an Org

16:41:31.581 sfdx force:auth:web:login --setalias mkhan@jade.com --instanceurl https://masthankhan-dev-ed.my.salesforce.com --setdefaultusername
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://masthankhan-dev-ed.my.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=9135e6529264^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=xFO4f9MTpXCKTz5qwUJWhbh8_7JshIGFqVOAkmdSLmY' ] }

**Comment by jrieken** [comment]
/needsMoreInfo

How is this related to VSCode, and not an issue with sfdx?
