### ISSUE TITLE
VSCode Incorrect Syntax Highlight for C/C++ with std::filesystem

### ISSUE THREAD

**Issue by TH3CHARLie** [microsoft/vscode#82240]
- VSCode Version: 1.39.0
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Use the following code
```c++
#include <filesystem>
#include <iostream>
namespace fs = std::filesystem;
const std::string FOLDER_PATH = "./";
int main() {
  for (auto& entry : fs::recursive_directory_iterator(FOLDER_PATH)) {
    std::cout << entry.path() << std::endl;
  }
  for (auto& entry : fs::directory_iterator(FOLDER_PATH)) {
    std::cout << entry.path() << std::endl;
  }
}
```
2. At line 6 and 9, incorrect highlights of ```fs::r``` and ```fs::d``` instead of ```fs::```.

Does this issue occur when all extensions are disabled?: No

So this may be caused by C/C++ plugin.

**Comment by alexr00** [comment]
I couldn't repro with the C/C++ extension disabled. Please open the issue on repository for that extension.
