### ISSUE TITLE
"Reveal Active File in Sidebar" no longer works with Jupyter notebooks

### ISSUE THREAD

**Issue by carbocation** [microsoft/vscode#82242]
- VSCode Version: 
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
- OS: Linux x64 4.15.0-66-generic

Steps to Reproduce:

1. Upgrade to the latest VSCode (1.38.1) and have the default (Microsoft) python extension enabled.
1. Open a jupyter notebook with the Visual Studio Code Python extension enabled.
1. Attempt to run command "reveal active file in side bar", note that it doesn't reveal the active file in the side bar.
1. Open a regular file, run command "reveal active file in side bar", note that it works as expected.

Does this issue occur when all extensions are disabled?: No, with all extensions disabled, revealing the file works as expected.

**Comment by mjbvz** [comment]
This is because Python uses `WebviewPanel` for showing their notebooks. This will be fixed if they use `WebviewEditor` based ones instead
