### ISSUE TITLE
directory rename jump file view display many file

### ISSUE THREAD

**Issue by fjqingyou** [microsoft/vscode#82246]
-  VSCode Version:
版本: 1.39.0
提交: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
日期: 2019-10-09T06:57:43.593Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

- OS Version:
macOS Mojave 10.14.6 (18G95)

# Steps to Reproduce:
directory rename, jump file input many file instance in this's directory

## step 1.
create directory "Test"

## step 2.
create a File "Test.ts" in "Test" directory

## step 3.
open Test.ts file

## step 4.
rename "Test" Directory to "test"

## step 5.
Keyboard: command + P, Input "Test", display double "Test/Test.ts" and "test/Test.ts"

# Does this issue occur when all extensions are disabled?:  Yes

**Comment by isidorn** [comment]
There is already an issue about  wrong file casing in the workbench, please find it from our open issues and you can upvote it if you like. THanks
