### ISSUE TITLE
Output file (firmware.bin) not updated upon compilation completion

### ISSUE THREAD

**Issue by skypuppy** [microsoft/vscode#82248]
Issue Type: <b>Bug</b>

mvsc, marlin 2.0.xbugfix.  Now sure how to "share" steps needed, but msvc will not update the "firmware.bin" file regardless of what changes are made in configuration.h or configuration_adv.h.  The "new" firmware.bin is exactly identical to something from an unknown time ago and running "diff" on them shows they are IDENTICAL!!!

Also, random and frequent of complete msvc crashes.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:03.188Z)
OS version: Linux x64 4.9.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1550)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|21, 20, 19|
|Memory (System)|31.42GB (0.23GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-build|mar|0.1.0
code-gnu-global|aus|0.2.2
cpptools|ms-|0.26.0-insiders3
platformio-ide|pla|1.8.3

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

How is this related to vscode? How can we reproduce this?
