### ISSUE TITLE
VSCode 1.39 Regression: regexp expression in snippet does not work

### ISSUE THREAD

**Issue by BartolomeSintes** [microsoft/vscode#82258]
A snippet that worked OK in VSCode 1.38 does not work anymore after updating to VSCode 1.39.
Tested in
- VSCode Version: 1.39 (user) or 1.40.0-insider (user)
- OS Version: Windows 10 19.03 x64

Steps to Reproduce:
1. Install this extension that contains three snippets and keybindings: https://marketplace.visualstudio.com/items?itemName=BartolomeSintes.mclibre-org-snippets
2. Create a .php file in VSCode
3. Copy some lines from the source code of a web page
For instance,
```html
<p title="test">
  This is a test
</p>
```
4. Paste them in the document usin the keybinding Ctrl+Alt+v Ctrl+Alt+l
The snippet just replaces " with \\" and add prints in every line.
In VScode 1.38 the obtained result was:
```php
print "<p title=\"test\">\n";
print " This is a test\n";
print "</p>\n";
```
In VScode 1.39, the obtained result is garbage:
```php
print "<p title=${1:+\"}${2:+\n";
print "}${1:+\"}${2:+\n";
print "}test${1:+\"}${2:+\n";
print "}>${1:+\"}${2:+\n";
print "}  This is a test${1:+\"}${2:+\n";
print "}</p>\n";
````
5. By the way, the other two snippets included in the extension work OK (both in VSCode 1.39 and 1.40 insiders)
Ctrl+Alt+v Ctrl+Alt+b pastes the text in one print:
```php
print "<p title=\"test\">
  This is a test
</p>\n";
```
Ctrl+Alt+v Ctrl+Alt+q pastes the text replacing quotes:
```php
<p title=\"\"test\">
  This is a test
</p>
```
6. The problem seems to be with the regexp of the first snippet. This snippet makes two substitutions:
```json
        "body": [
            "print \"${CLIPBOARD/(\")|(\\r\\n)/${1:+\\\"}${2:+\\n\";\nprint \"}/g}\\n\";\n"
        ],
´```
Does this issue occur when all extensions are disabled?: Yes/No
The snippet is installed as an extension, but the snippet extension is the only one installed.

**Comment by jeanp413** [comment]
@BartolomeSintes Try this
```
"body": [
  "print \"${CLIPBOARD/(\")|(\\r\\n)/${1:+\\\\\"}${2:+\\\\n\";\nprint \"}/g}\\n\";\n"
],
```
There was a bug #80394 which is fixed now

**Comment by BartolomeSintes** [comment]
I have tried your regexp in VSCOde 1.39 and 1.40 insiders and it works. I have tried to use it VSCode 1.38.1 but I failed because VSCode is updated automatically (even if I have disabled the updates ;-(
Anyway, what do I have to do? Publish a new version of the extension with your regexp? 
As I understand, escape characters in the output should be written with four backslashes \\\\\\\\ in the regexp. Will VSCode need these \\\\\\\\ from now on?
Thank you very much for your help.

**Comment by jeanp413** [comment]
Yes, `\\\\` generates `\` (you need to escape twice, one for the json string, and again for the snippet parser to interpret it correctly, the previous behavior was a bug).
You need to publish a new version with the updated regex.

**Comment by BartolomeSintes** [comment]
I have republished the extension. I suppose this issue can be closed now.

**Comment by isidorn** [comment]
Ok, closing the issue then
fyi @jrieken
