### ISSUE TITLE
Enable the bracket pair colorizer V2 extension for remote

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#82252]
For details pls see https://github.com/microsoft/vscode-remote-release/issues/1440.

I've updated the product.json of insider/stable to define the extension as a UI extension https://github.com/microsoft/vscode-distro/blob/distro/quality/stable/product.json#L782

Candidate since the bracket pair colorizer is a popular extension and we should also enable users that use the V2 version.

**Comment by mjbvz** [comment]
I also previously pinged the extension about fixing this: https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/108
