### ISSUE TITLE
Privilege elevation is required in order to install update when istalled using System Installer

### ISSUE THREAD

**Issue by letrec** [microsoft/vscode#82256]
- VSCode Version: 1.39
- OS Version: Windows 10 (18362.418)

Steps to Reproduce:

1. Click "Install Update" when update is available
2. Privilege elevation will be requested for it to install

Does this issue occur when all extensions are disabled?:
Yes.

Mozilla Firefox is also installed system-wide and uses a service to facilitate updates, but no privilege elevation is required in order to install them, which makes it a better user experience.

**Comment by joaomoreno** [comment]
This is why we distribute a user install, please use that instead if you'd like to avoid escalation.

**Comment by letrec** [comment]
I'm well aware of the user install option, but it's beside the point.
Update of a system-wide installed component doesn't have to require privilege elevation.
Mozilla Firefox, Microsoft Office and Windows itself are good examples of that.
The requirement of privilege elevation defers delivery of updates in cases like kids using VS Code on machines where they don't have admin privileges (they have to wait for someone who does have them).
