### ISSUE TITLE
SCM: SVN extension decorations are misaligned

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82257]
![image](https://user-images.githubusercontent.com/22350/66584997-5c686000-eb86-11e9-97a6-99d3873c0213.png)

Here's stable, as a reference:

![image](https://user-images.githubusercontent.com/22350/66585017-65593180-eb86-11e9-9504-44c4d146883b.png)

**Comment by alexandrudima** [comment]
We discussed in the stand-up and would like to take it.

**Comment by joaomoreno** [comment]
**Verification:**

- Install SVN and the SVN extension
- Run `svn co https://svn.apache.org/repos/asf/subversion/site/staging/docs/release-notes/` to checkout that repository
- Open the `release-notes` folder in VS Code
- Make some changes

The decoration icons of those changes should be properly aligned.
