### ISSUE TITLE
Go to definition stopped working

### ISSUE THREAD

**Issue by pirix-gh** [microsoft/vscode#82263]
I use to have `alt+click` to go to definition. But it stopped working.

- VSCode Version: 1.39.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. `"editor.multiCursorModifier": "ctrlCmd",`

I tried `"editor.multiCursorModifier": "alt",` and it makes multi-cursor not to work. So it seems that there is problems with `alt`. The rest of the shorcuts work weel with `alt`, though.

(& my `alt` button isn't broken :laughing:)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by pirix-gh** [comment]
@vscodebot, mine isn't overriden by the system. It was working 2 days ago

**Comment by alexandrudima** [comment]
@pirix-gh I could never use Alt+click on Ubuntu (the windows would always move when doing so), so I wonder how come this ever worked for you?

**Comment by pirix-gh** [comment]
Hi @alexandrudima. I had disabled the window drag with dconf https://askubuntu.com/questions/521423/how-can-i-disable-altclick-window-dragging (that I replaced with the <super> button). Like I said, it was working a few days ago until the update came.

**Comment by pirix-gh** [comment]
@alexandrudima Nevermind, I'll use `shift+alt+click`.

**Comment by pirix-gh** [comment]
And just for info, I also disabled mnemonics (hotkeys `alt+menukey`) system-wide and in vscode via the `window` setting but it still had the same behavior.

**Comment by pirix-gh** [comment]
btw, what is your alternative (setting) to handle this?

**Comment by alexandrudima** [comment]
@pirix-gh I have just tried in `Ubuntu 19.10`. I have configured `"editor.multiCursorModifier": "ctrlCmd"` and I can use `alt+click` to jump to definition fine:

![Kapture 2019-10-30 at 12 43 35](https://user-images.githubusercontent.com/5047891/67855568-f468c200-fb12-11e9-8bdc-f2325b317cae.gif)

**Comment by pirix-gh** [comment]
I tested, and it's the same. It seems like something else is capturing the mouse when I use `alt`... So this is probably not an issue, even though I'm on ubuntu 18.04.

Does the `alt` work out of the box on ubuntu 19.10? Or did you also have to disable the window dragging?

**Comment by alexandrudima** [comment]
I was pleasantly surprised to see that `alt` works out-of-the-box on Ubuntu 19.10 ... I'm pretty happy they decided to let that `alt` + drag crap go...
