### ISSUE TITLE
Regression: Cannot edit code in right pane in the Source Control diff view

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/vscode#82262]
This was my regular workflow, edit a bunch of code in C++, and see the diff (in the Source Control view) and edit. But I am getting: "Cannot edit in read-only editor"

No extensions are installed, (even used the switch --disable-extensions), I searched online, and they said to install "Code Runner" and use terminal, that didn't help.

Now my workflow is interrupted, if I see anything wrong in my PR, I need to Ctrl+P to find the file and open it in the Files View., I have hundred thousands of files and it becomes a hassle. (I am working on the Chromium code base).

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363
Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@mohamedmansour Are you sure the file isn't staged? Can you show me a screenshot of the SCM view?
