### ISSUE TITLE
ArchLinux: Support saving as sudo

### ISSUE THREAD

**Issue by sarpik** [microsoft/vscode#82266]
Hello,

the issue #70403 turns down the blame to `upstream` (arch linux), but arch linux turns down the blame back to `vscode`. See https://bugs.archlinux.org/task/61516, specifically the comments.

> No, it is an upstream [vscode] issue. We [arch linux] are sane people so we don't distribute a full copy of electron with VS Code, we use the electron already present on your system. This is the exact same reason why we use dynamic libraries instead of statically linking everything. It is on the upstream for not supporting this properly, I already took the appropriate actions to try get them to look into this but they don't seem interested. I can't do anything other that hope someone looks into this.

The bugfix of #70403 would be really appreciated - it's troublesome not being able to use the `save file as sudo` feature.

See also:

https://wiki.archlinux.org/index.php/Visual_Studio_Code#Saving_with_%22Retry_as_Sudo%22_does_not_work

Many thanks!

**Comment by bpasero** [comment]
I have to ask for help from ArchLinux, we officially support the following platforms on Linux: https://code.visualstudio.com/docs/supporting/requirements#_platforms

If they are willing to do a PR for a fix, I am happy to review and approve. Can you ask?

**Comment by sarpik** [comment]
Hello there,

I don't know if they're willing to do a PR - I sure hope though!
I've requested to reopen the https://bugs.archlinux.org/task/61516 issue; I'll try creating an issue if there's no response.

Anything else I could do?

---

fyi, I didn't mention explicitly, but in the [arch wiki's vscode article](https://wiki.archlinux.org/index.php/Visual_Studio_Code#Saving_with_%22Retry_as_Sudo%22_does_not_work) it's mentioned that
> The binary release visual-studio-code-bin does not have this issue, and the feature works there.

which does not solve the issue (since we're using the oss version), but I just wanted to mention this.

---

Thank you for your time, I hope this can be resolved:)

**Comment by FFY00** [comment]
What are we supposed to do? This is a huge codebase and I really can't find the source of this issue. I already put a enormous amount of time trying to figure this out but without success. My requests for help were ignored, what else should I do? This really is a simple issue but I can't fix it without proper knowledge of the codebase. The vscode team should be able to fix rather quickly but they don't really want to.

**Comment by bpasero** [comment]
@FFY00 I would start by looking if the fix has to go into https://github.com/jorangreef/sudo-prompt which is the library we are using for saving as sudo. It is being triggered from https://github.com/microsoft/vscode/blob/8a806778ea25e16314750eb4c3fc313f736442a6/src/vs/workbench/services/textfile/electron-browser/nativeTextFileService.ts#L268

**Comment by bpasero** [comment]
Thanks for your time to look into it. Moving forward I suggest to create this issue in sudo-prompt. It seems that a fix in VSCode itself is not possible, as such I will go ahead and close this one.

**Comment by sarpik** [comment]
Please head over to https://github.com/jorangreef/sudo-prompt/issues/113.
