### ISSUE TITLE
SCM: Allow folders as resources when rendering as tree

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82264]
Users have found out in https://github.com/microsoft/vscode/issues/82203 that most other SCM providers break the tree rendering. This happens because they provide folders as resources themselves, which simply breaks the tree.

This should actually just be supported, but we need to address what happens to the contextual menus. With the tree rendering addition, folders have their own context key for menus. Currently in these SCM providers, the folders have the same actions as the files and maybe that's intended, so we should preserve that.

I suggest the following:

1. If a folder is provided as a resource, simply use the regular resource context key, thus maintaining the current behavior. Also, we need to change the _should expand on twistie click only_ behavior, since those resources might have a command to run when clicked.
2. Else, populate the menu using the new folder context key.
3. Remove the proposed API additions introduced in https://github.com/microsoft/vscode/issues/82203

This allows us to continue to move forward without adding or removing anything from the API.

**Comment by fr43nk** [comment]
Hi,
I don't fully understand the technical details, why it broke the scm view. So my question is: What needs to be done from my side as a extension maintainer (vscode-clearcase) to make use of the tree rendering? Perhaps you can give some kind of advice about that. 
Thank you in advance.

**Comment by joaomoreno** [comment]
@fr43nk Absolutely. What I argue in this issue is that you, as an extension maintainer, should not have to do anything to benefit from this feature. It should just work.

**Comment by fr43nk** [comment]
@joaomoreno  Ok, so if you want me to test the new feature with my extension, I can do this.

**Comment by joaomoreno** [comment]
Pinging a few SCM Provider devs: @fr43nk, @jeffyoung, @jpricket, @JohnstonCode, @edgardmessias, @ivangabriele, @mrcrowl, @stef-levesque.

As you might know, this iteration we shipped rendering SCM as a tree. This broke for 3-rd praty SCM Providers and a fix is coming today or tomorrow to address this. The recovery fix simply disables tree rendering for all SCM providers except git. This was an oversight from us and we apologize for the disruption.

---

Thinking forward, I've pushed some changes to support tree rendering for all SCM providers. The problem here was that some SCM providers are sending folders as SourceControlResource instances and this broke some assumptions. Given these changes, list rendering (default) is left untouched but tree rendering has the following implications:

- Those folders won't be compressible, so if there is a long chain of these folders, the SCM tree won't compress it;
- Those folders will have the same inline and context menu actions as SourceControlResource instances;
- Those folders won't have a click command any more, since clicking them will expand/collapse those tree nodes.

You can try this on [insiders](https://code.visualstudio.com/insiders) from tomorrow onwards. I've tried a couple of extensions and they seem to play along nicely. Let me know your thoughts.

**Comment by fr43nk** [comment]
I tried the latest insider build with my extension and it still works :smile: 
In the current release version the button to toggle list or tree view is available for my extension and seems to work. In the insider build this button is gone. Is this by intension? 

Thanks

**Comment by joaomoreno** [comment]
**Verification:**

- Install SVN
- Install the [SVN extension](https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm)
- `svn co https://svn.apache.org/repos/asf/subversion/site/staging/docs/release-notes/`
- Open the `release-notes` folder in VS Code
- The SVN extension should be rendered in the SCM view

**Comment by JohnstonCode** [comment]
Works perfectly
