### ISSUE TITLE
Generic react component (TSX) and intellisense not working

### ISSUE THREAD

**Issue by martinsura** [microsoft/vscode#82276]
- VSCode Version: 1.39.0
- OS Version: Widnows 10.0.18362

Steps to Reproduce:
Have code:
```
type Props<T> = {
  name: keyof T;
  isActive: boolean;
  children: React.ReactNode;
};

type User = {
  firstName: string;
  lastName: string;
};

export const CustomComponent = <T extends {}>(props: Props<T>) => {
  return <React.Fragment>{props.name}</React.Fragment>;
};

export const TestComponent = () => {
  return (
    <CustomComponent<User> name="firstName" isActive>
      <div></div>
    </CustomComponent>
  );
};
```
While i use CustomComponent in TestComponent intellisense not working. After define first props, then intellisense start working.

![image](https://user-images.githubusercontent.com/333932/66597218-cbea4980-eb9e-11e9-81ab-ed00a9e94511.png)

![image](https://user-images.githubusercontent.com/333932/66597243-defd1980-eb9e-11e9-872c-3606bfee3466.png)

I am using last typescript and last react with react-dom.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I can't reproduce this. What is the version of TypeScript you have in your workspace?

**Comment by martinsura** [comment]
```
"typescript": "^3.6.3",
"react": "^16.9.0",
"react-dom": "^16.9.0",
```
Also try install latest vs code insider, disable all extensions and results is same.

After typing CutstomComponent<User> and try suggest first prop -> no intellisense.

**Comment by martinsura** [comment]
Btw Sandbox (react+tsx) has same problem. 

https://codesandbox.io/s/blue-river-9gy5j?fontsize=14&module=%2Fsrc%2Fcustom.tsx

**Comment by mjbvz** [comment]
e

**Comment by martinsura** [comment]
Hmm still same issue. Disabled all extensions and enable only "JavaScript and TypeScript Nightly.
Console looks clear -> 
![image](https://user-images.githubusercontent.com/333932/66703357-0b857280-ed12-11e9-9a3b-319d24c92417.png)
 
Code -> 
![image](https://user-images.githubusercontent.com/333932/66703348-f4df1b80-ed11-11e9-8036-219f898bab84.png)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/34110 to track this upstream
