### ISSUE TITLE
Opening VS Code with URLs not working

### ISSUE THREAD

**Issue by webmasterMeyers** [microsoft/vscode#82278]
Issue Type: <b>Bug</b>

As per https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls clicking links such as "vscode://file//var/www/html/thegridsf/templates/nbp/familyAndContacts.html.twig:1" in Chrome (Version 77.0.3865.90 (Official Build) (64-bit)) does not open the file.  VS code will open if it is closed, but not the file.

----
VS Code Version: 1.39.0
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:03.188Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic, Ubuntu 18.10, GNOME: 3.30.1

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:03.188Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4017)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.32GB (1.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by garyking** [comment]
I noticed this bug appeared recently too. Maybe a day or two ago. Perhaps since the 1.39.0 release.

**Comment by isidorn** [comment]
Assignig also to @bpasero and @joaomoreno since @aechan is out today
Adding candidate since it sounds like a regression

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82212
