### ISSUE TITLE
Long time to load source control providers

### ISSUE THREAD

**Issue by skeeler** [microsoft/vscode#82283]
Issue Type: <b>Performance Issue</b>

When starting Visual Code in a folder with a cloned Git repo, it takes between 20-30 seconds for the Git source view to connect - shows message "No source control providers registered" for this period of time. Given how quickly Visual Code responds in just about every other way, it would be nice (and more consistent) if the source control provider registration could be optimized to complete in less than 5 seconds.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - AzureCloudOperations - Visual Studio Code)
|    Folder (AzureCloudOperations): 13 files
|      File types: md(5) json(2) ps1(1)
|      Conf files:;
```

</details>

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions` as well?

**Comment by skeeler** [comment]
Can't reproduce using --disable-extensions, both it and git status are immediate (less than 1 second). Interestingly, even without the --disable-extensions option the source control providers are registering in about 5-6 seconds today where it was taking closer to 30 seconds yesterday. Looks like an extension issue. I have the GitLens extension installed, so might be that one (unsure if any other extensions are using source control).
