### ISSUE TITLE
Opening a link in editor should focus opened browser & support filesystem paths

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8228]
- VSCode Version: Code - Insiders 1.3.0-insider (41f53d27a8cb477130f84116c78f43ddacbaf24b, 2016-06-27T05:07:29.758Z)
- OS Version: Windows_NT ia32 10.0.14366

Using the links generated for URLs could be improved:
- When Ctrl+Clicking on a link, please focus the opened browser (when the link opens in Edge, Edge flashes orange but is not brought into focus). This is true whether opening in an existing browser window or opening a new one.
- Please support file system paths and UNC paths (starting with \\) being auto-linked in VS Code (similar to email clients like Outlook auto-detecting such links). Ctrl+Click on such a link would open up the path in the OS's file browser on the computer. It wouldn't be perfect for systems like Windows which tend to put spaces in paths, but developers even on Windows often enough choose paths without spaces and VS Code is mainly an editor for developers so I think it would be good enough to simply treat a space as a delimiter for the link.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
