### ISSUE TITLE
set syntax command

### ISSUE THREAD

**Issue by NaveenDA** [microsoft/vscode#82282]
Previously I am using sublime text editor, which allows setting the syntax language via command.
In VSCode I see option on the bottom right corner to "Select Language Mode", but need to click using the mouse then type/select the language, I would like to change the language mode by keyboard.

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/66646537-ba4c8480-ec26-11e9-9253-6e3f931be091.png)

**Comment by NaveenDA** [comment]
since I got exactly what I need, so I close this issue.

**Comment by ArturoDent** [comment]
There is a shortcut to open the language mode setting panel.   Did you try it?

**Comment by NaveenDA** [comment]
Yes off course. 🤩
<img width="620" alt="Screenshot 2019-10-13 at 12 43 06 AM" src="https://user-images.githubusercontent.com/20555082/66706611-78b8f800-ed52-11e9-9fed-71aa53b5cb64.png">
