### ISSUE TITLE
Bug when maximizing and toggling panel

### ISSUE THREAD

**Issue by alvitawa** [microsoft/vscode#82285]
- VSCode Version: 1.28.1
- OS Version: WSL2

Steps to Reproduce:

1.  Press 'Maximize Panel Size' (workbench.action.toggleMaximizedPanel)
2.  Press "workbench.action.terminal.toggleTerminal" hotkey.
3.  Press "workbench.action.terminal.toggleTerminal" hotkey again.

The panel has now been resized to almost but not quite cover the editor. It needs to be resized back manually with the mouse to see the editor again.

It should either go back to the original size from before it was maximized, or still be maximized when brought back up.

Does this issue occur when all extensions are disabled?: Yes

Not exactly the same as #79891 but if you fix one you could fix the other too.

**Comment by sbatten** [comment]
This is resolved in the latest version
