### ISSUE TITLE
VS Code and Polish charaters bug

### ISSUE THREAD

**Issue by janzal123** [microsoft/vscode#82281]
Ubuntu 19.04, Visual Studio Code 1.38.1:

When I type text and press polish character the cursor moves left so that the order of letters is reversed. Say I wanted to type abc', where c was Polish c with an accent then when I have typed ab and start typing c' the cursor moves before b, so that I am typing like: ac'b.

In fact the cursor moves to the left when I press the polich characters selector which is the right Alt Gr on polish programmers keyboard.

Any time I press "Alt Gr" the cursor moves to the left, like as I was pressing the left arrow. Perhaps some bug in Linux or in VS Code. But it make typing quite impossible.

I've checked it does not occur in Windows 10/VS Code 1.38.1.

**Comment by janzal123** [comment]
enabled extensions:

**Comment by janzal123** [comment]
Extension | Author (truncated) | Version
-- | -- | --
delphi-keybindings | ale | 8.1.0
delphi-pack | ale | 2.0.0
numbered-bookmarks | ale | 6.2.1
pascal-formatter | ale | 2.2.0
vscode-groovy | Arg | 0.0.1
bracket-pair-colorizer | Coe | 1.0.61
githistory | don | 0.4.6
gitlens | eam | 10.1.1
jenkinsfile-support | ivo | 0.4.4
jenkins-pipeline-linter-connector | jan | 1.2.0
terraform | mau | 1.4.0
vscode-docker | ms- | 0.8.1
vscode-kubernetes-tools | ms- | 1.0.4
powershell | ms- | 2019.9.0
gradle-language | nac | 0.2.3
vscode-yaml | red | 0.5.3
vscodeintellicode | Vis | 1.1.9

**Comment by janzal123** [comment]
system info:
CPUs	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (4 x 3990)
GPU Status	2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
oop_rasterization: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: disabled_software
viz_display_compositor: disabled_off
webgl: unavailable_software
webgl2: unavailable_software
Load (avg)	1, 1, 1
Memory (System)	27.61GB (12.49GB free)
Process Argv	
Screen Reader	no
VM	0%

**Comment by janzal123** [comment]
Ubuntu 19.04 here is the version of Ubuntu made available for HyperV virtualization, so I am using Ubuntu 19.04 under HyperV in Windows 10.

**Comment by alexandrudima** [comment]
Here is a self-help troubleshooting wiki -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

![image](https://user-images.githubusercontent.com/5047891/66990929-65e25280-f0c7-11e9-8544-a0c8b174c144.png)
