### ISSUE TITLE
Source control default message disappears after a commit sometimes

### ISSUE THREAD

**Issue by timdeng2324** [microsoft/vscode#82297]
- VSCode Version: 1.36.1
- OS Version: macOS mojave 10.14.6

Steps to Reproduce:
Doesn't consistently happen.

1. Make changes to a file (on remote ssh, for me)
2. Stage changes using the source control feature in vs code
3. Edit commit message (at this point, the default commit message is usually there in vs code source control feature)
4. Commit changes (using command line or feature in vs code)
5. When it finishes, sometimes it has no default commit message

Have also tried invoking git: refresh but it doesn't come back without sshing back in.

When it breaks:
![image](https://user-images.githubusercontent.com/6328033/66614508-2e7f1d80-eb7e-11e9-95d9-8645738af090.png)
After I restart vs code & sign back in to remote ssh, it works again. Isn't a breaking bug, but it does take me out of my workflow because I have to restart the application.
After restart / before it breaks:
![image](https://user-images.githubusercontent.com/6328033/66614513-33dc6800-eb7e-11e9-96a2-f9220ea41d90.png)

Does this issue occur when all extensions are disabled?: Yes/No
Can't launch without extensions because using remote ssh

**Comment by joaomoreno** [comment]
Has this happened at all without using remote SSH?

**Comment by timdeng2324** [comment]
i'm not sure, i only have a repository that I use every day on remote, & it doesn't happen very often. haven't been able to reproduce by trying a few times locally.

**Comment by timdeng2324** [comment]
this happens sometimes if i stage my changes by using the selector, and then typing "git commit" in the integrated terminal. since my git message uses vim, it will open up vim in the terminal, i will commit, and then the template message disappears from the sidebar. shouldn't be like that because after a commit, i should be ready to make another commit, so it should reset

**Comment by joaomoreno** [comment]
@timdeng2324 Has this still been happening?

**Comment by timdeng2324** [comment]
not sure, sorry! switched workplaces and i don't use remote ssh anymore

**Comment by joaomoreno** [comment]
Closing for now, until someone else reports the issue.
