### ISSUE TITLE
Minimap: Render warning and error decorations

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#82291]
Would also like to see linter errors/warnings:

![screen shot 2017-05-04 at 10 42 32](https://cloud.githubusercontent.com/assets/40524/25694274/89fed630-30b6-11e7-8372-2f1246b45d1f.png)

By the way, great job on the minimap. Love this feature. Thanks for the work you put into it!

_Originally posted by @bjunix in https://github.com/microsoft/vscode/issues/20934#issuecomment-299117437_

**Comment by isidorn** [comment]
Works for me. Might be a bit too strong for my personal taste, though I understand it is configurable. Adding verified label

![Screenshot 2019-12-03 at 16 41 12](https://user-images.githubusercontent.com/1926584/70065669-c849d080-15eb-11ea-941a-cdc74513957f.png)
