### ISSUE TITLE
September 2019 Recovery Endgame

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82295]
- [x] Create a milestone `<Month> Recovery <year>` **owner**
- [x] Bump the version number **owner**
- [x] Include an issue 'update translations' **owner**
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Make rpm signing request **@Tyriar**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - **owner**
  - [x] OS X - **owner**
  - [x] Linux - **owner**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit **owner**
    - [x] signed installer 32-bit @sbatten 
    - [x] signed user installer 32-bit @sbatten 
    - [x] zip 32-bit @mjbvz 
  - [x] Windows 64 bit @roblourens 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [X] OS X - @mjbvz
  - [x] Linux
    - [X] deb package 64-bit  @mjbvz
    - [x] rpm package 64-bit @roblourens 
    - [X] archives  @mjbvz
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [ ] Publish rpm to repository manually **@Tyriar**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`

**Comment by mjbvz** [comment]
Closing as we've shipped the recovery
