### ISSUE TITLE
Please add a configuration file to control which extensions are enabled or disabled

### ISSUE THREAD

**Issue by GWIian** [microsoft/vscode#82299]
Overall, vscode is great, and I'd like you to add a new feature: for extensions, you can have a special configuration file under the.vscode folder to control which plug-ins you need to enable for the project itself. Plug-ins not in the list are automatically disabled in the workspace, plug-ins in the list are automatically enabled, and uninstalled plug-ins can be automatically installed. I thought it would be cool and we could make sure that all the plug-ins we enabled were needed for the project.

**Comment by sandy081** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/18386
