### ISSUE TITLE
Debug EH action tries to start debugging when canceled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82294]
- Open Show Running Extensions
- Click "Start Debugging Extensions"
- Prompt should ask you to restart to do this
- Click cancel
- Debugging starts unsuccessfully

**Comment by isidorn** [comment]
Happens due to weird timing of events between the EH and the renderer which I am too scared to touch since the current combination seems to work just fine on various builds / platforms / start scenarios.
So will not tackle this immediatly. If you really hate this let me know and I can look into.

**Comment by roblourens** [comment]
Are you sure? It seems like it's just not paying attention to the dialog's response. I click cancel, then it should do nothing.

**Comment by isidorn** [comment]
@roblourens you are correct, I misread the original comment
