### ISSUE TITLE
VSCode Version: 1.39 OS Version: catalina Steps to Reproduce:  can not open when I updated to Catalina

### ISSUE THREAD

**Issue by Asheshp23** [microsoft/vscode#82292]
<img width="492" alt="Screen Shot 2019-10-09 at 10 53 32 PM" src="https://user-images.githubusercontent.com/22404192/66612129-c6850300-eb8e-11e9-9184-66291c7addb9.png">

**Comment by misolori** [comment]
Please see #74782
