### ISSUE TITLE
VSCode cannot open on macos Catalina

### ISSUE THREAD

**Issue by afkratien** [microsoft/vscode#82302]
- VSCode Version: 1.39
- OS Version: macos Catalina

<img width="896" alt="Screenshot 2019-10-11 at 09 08 10" src="https://user-images.githubusercontent.com/28397259/66619390-f40d9300-ec06-11e9-8cfc-162e2717a7ad.png">

**Comment by trapias** [comment]
I have the same error, tried downloading latest version and reinstalling without success.

**Comment by trapias** [comment]
Found the solution [here](https://github.com/microsoft/vscode/issues/74782)

**Comment by nsuchy** [comment]
It may be relevant to copy this comment over from a duplicate issue.

https://github.com/microsoft/vscode/issues/82353#issuecomment-541082764

> <img alt="Screen Shot 2019-10-11 at 10 13 29 AM" width="475" src="https://user-images.githubusercontent.com/8227641/66658629-dbee4180-ec0f-11e9-83eb-baed4453ed2e.png">
> I get this same error on VS Code Stable. I was able to open by pressing option in finder and opening it that way to bypass to check. For the time being you'll need to let Gatekeeper know you trust the software regardless of what it's checks say.

**Comment by misolori** [comment]
Please see #74782

**Comment by tmekos** [comment]
1. download homebrew:::::  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2.  brew update
3.   brew cask install visual-studio-code
4.  '/usr/local/bin/code'
that's it!!

**Comment by katsaldavid** [comment]
still getting the same error message, nothing works yet!!
<img width="970" alt="Screen Shot 2019-11-19 at 7 27 35 PM" src="https://user-images.githubusercontent.com/57975202/69206931-fd8df300-0b02-11ea-8ad2-e092f31dd80f.png">
