### ISSUE TITLE
search file on selected characters

### ISSUE THREAD

**Issue by cnjeffliu** [microsoft/vscode#82306]
Issue Type: <b>Feature Request</b>

when i want to search an file, whose name prefix in editor, I hope the selected characters can fill in search edittext automatically. 

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17134

**Comment by roblourens** [comment]
You mean for cmd+p? I think that would lead to lots of accidental searching and confusion. I prefer having users copy/paste the selected text into quickopen.
