### ISSUE TITLE
Multiline find

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8230]
You can test in any OS
- [x] any os - @Tyriar 
- [x] any os - @dbaeumer 

If you turn on the regex checkbox in the find widget, you can now search for `\r` or `\n`. Please check cases with different end of line sequences (CRLF vs LF). Please check find prev, find next, replace next, replace all, etc individually (they point to different implementations).

It is unclear to me what to do with the find in selection, I have a feeling it is now too eagerly activating. Please let me know in issues how you feel about it.

**Comment by dbaeumer** [comment]
@alexandrudima I did the testing and I agree that the find in selection versus prepopulating the find box is now a little inconsistent. I would suggest the following:

- if text is selected that spawns more than  one line we still assume that the user wants to find in selection.
- if he unchecks the FInd in Selection and didn't type and search text we can repopulate the search field with the selected text as a regular expression.
