### ISSUE TITLE
Settings getting overlapped

### ISSUE THREAD

**Issue by code-knayam** [microsoft/vscode#82308]
Issue
![Screenshot from 2019-10-11 11-00-30](https://user-images.githubusercontent.com/23213159/66626572-5de16900-ec16-11e9-9ba5-834c5e5e1139.png)
 Type: <b>Bug</b>

Under the workspace settings tab, when you scroll down multiple settings are getting overlapped. Not able to identify what settings are present where.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2618)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.68GB (0.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
That looks like an old version of vscode, I think this was already fixed.
