### ISSUE TITLE
 Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#82310]
Issue Id: <b>f2246a63-a8e6-9b9a-f92c-bc61d6bae743</b><br /><br />*Versions* <br />- 1.39.0-insider (10/9/2019 8:11:06 AM)<br />-  c8252b63f547674d2faf361d4181bb76b0b5f81a<br />*Stack* <br />TypeError: Cannot read property 'substring' of undefined<br />	at t.ExtHostDocumentData._acceptInsertText (<REDACTED: user-file-path>:217:448)<br />	at t.ExtHostDocumentData.onEvents (<REDACTED: user-file-path>:216:57)<br />	at t.ExtHostDocuments.$acceptModelChanged (<REDACTED: user-file-path>:554:931)<br />	at p._doInvokeHandler (<REDACTED: user-file-path>:652:275)<br />	at p._invokeHandler (<REDACTED: user-file-path>:651:971)<br />	at p._receiveRequest (<REDACTED: user-file-path>:650:639)<br />	at p._receiveOneMessage (<REDACTED: user-file-path>:649:468)<br />	at _protocol.onMessage.e (<REDACTED: user-file-path>:647:691)<br />	at l.fire (<REDACTED: user-file-path>:50:519)<br />	at _.fire (<REDACTED: user-file-path>:181:274)<br />	at e.onMessage.e (<REDACTED: user-file-path>:804:104)<br />	at l.fire (<REDACTED: user-file-path>:50:519)<br />	at _.fire (<REDACTED: user-file-path>:181:274)<br />	at t.PersistentProtocol._receiveMessage (<REDACTED: user-file-path>:185:629)<br />	at _socketDisposables.push._socketReader.onMessage.e (<REDACTED: user-file-path>:184:786)<br />	at l.fire (<REDAC<br />

**Comment by alexdima** [comment]
I could not figure out what is the root cause and I would not change anything in that area without clear steps...
