### ISSUE TITLE
 Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#82314]
Issue Id: <b>62907399-48b8-de2c-b980-2b73e661055d</b><br /><br />*Versions* <br />- 1.39.0-insider (10/9/2019 8:11:06 AM)<br />-  c8252b63f547674d2faf361d4181bb76b0b5f81a<br />*Stack* <br />TypeError: Cannot read property 'scope' of undefined<br />[/vs/workbench/services/configuration/common/configurationEditingService.ts#446:47 (resolveAndValidate)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L446:47 (resolveAndValidate))<br />[/vs/workbench/services/configuration/common/configurationEditingService.ts#173:14 (doWriteConfiguration)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L173:14 (doWriteConfiguration))<br />[/vs/workbench/services/configuration/common/configurationEditingService.ts#160:53 (factory)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L160:53 (factory))<br />[/vs/base/common/async.ts#441:32 (consume)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/base/common/async.ts#L441:32 (consume))<br />[/vs/base/common/async.ts#432:8](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/base/common/async.ts#L432:8)<br />    at new Promise (<anonymous>)<br />[/vs/base/common/async.ts#430:9 (queue)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/base/common/async.ts#L430:9 (queue))<br />[/vs/workbench/services/configuration/common/configurationEditingService.ts#160:36 (writeConfiguration)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L160:36 (writeConfiguration))<br />[/vs/workbench/services/configuration/browser/configurationService.ts#630:42 (writeConfigurationValue)](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/browser/configurationService.ts#L630:42 (writeConfigurationValue))<br />[/vs/workbench/services/configuration/browser/configurationService.ts#260:24](https://github.com/microsoft/vscode/blob/9df03c6d6ce97c6645c5846f6dfa2a6a7d276515/src/vs/workbench/services/configuration/browser/configurationService.ts#L260:24)<br />    at process._tickCallback (<REDACTED: user-file-path>:68:7)<br />

**Comment by sandy081** [comment]
/duplicate

#84528
