### ISSUE TITLE
Signing GPG keys failing to validate

### ISSUE THREAD

**Issue by deelaka** [microsoft/vscode#82317]
Apologies if this is not the place to highlight this issue.

On [https://packages.microsoft.com/yumrepos/vscode/repodata/](https://packages.microsoft.com/yumrepos/vscode/repodata/)

The GPG keys have been failing to validate `repomd.xml.asc` with the `repomd.xml` file using `Microsoft (Release signing) <gpgsecurity@microsoft.com> (EB3E 94AD BE12 29CF)`.

Thus the package management system on my machine which is `zypper` complains that the file has been altered after it has been signed, thus it could be potentially malicious. 

I am confident that this is a simple case of not re-signing the `xml` file after it has been updated thus kindly request to resign and upload the new `asc` file.

Regards.

**Comment by Tyriar** [comment]
I reported to the repo admin team.

**Comment by deelaka** [comment]
Thanks @Tyriar, the issue has been resolved.
