### ISSUE TITLE
 Cannot read property 'resize' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#82312]
Issue Id: <b>26abe9a0-1ac7-981e-40af-bc6da2caad42</b><br /><br />*Versions* <br />- 1.39.0-insider (10/9/2019 8:11:06 AM)<br />-  c8252b63f547674d2faf361d4181bb76b0b5f81a<br />-  d3eb24828e2d977e4f3ac16ff1a332a020028464<br />*Stack* <br />TypeError: Cannot read property 'resize' of undefined<br />	at y.$acceptProcessResize (<REDACTED: user-file-path>:628:418)<br />	at p._doInvokeHandler (<REDACTED: user-file-path>:652:275)<br />	at p._invokeHandler (<REDACTED: user-file-path>:651:971)<br />	at p._receiveRequest (<REDACTED: user-file-path>:650:639)<br />	at p._receiveOneMessage (<REDACTED: user-file-path>:649:468)<br />	at _protocol.onMessage.e (<REDACTED: user-file-path>:647:691)<br />	at l.fire (<REDACTED: user-file-path>:50:519)<br />	at _.fire (<REDACTED: user-file-path>:181:274)<br />	at e.onMessage.e (<REDACTED: user-file-path>:804:104)<br />	at l.fire (<REDACTED: user-file-path>:50:519)<br />	at _.fire (<REDACTED: user-file-path>:181:274)<br />	at t.PersistentProtocol._receiveMessage (<REDACTED: user-file-path>:185:629)<br />	at _socketDisposables.push._socketReader.onMessage.e (<REDACTED: user-file-path>:182:824)<br />	at l.fire (<REDACTED: user-file-path>:50:519)<br />	at p.acceptChunk (<REDACTED: user-file-path>:178:588)<br />	at _register._socket.onData.e (<REDACTED: user-file-path>:177:958)<br />	at Socket.t (<REDA<br />

**Comment by isidorn** [comment]
Bad stack trace -> closing
