### ISSUE TITLE
Typescript highlighting, show union type name rather than its components

### ISSUE THREAD

**Issue by alshdavid** [microsoft/vscode#82313]
Version: 1.39.0
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:57:43.593Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

In the scenario where I have a type which is composed of multiple interfaces, the intellisense prompt shows the types which the type contains rather than the named parent type. 

Example:

Say I have these interfaces

![image](https://user-images.githubusercontent.com/12656294/66627159-8c773800-ec46-11e9-9f0b-42d823e2a2bf.png)

a function consuming this type

![image](https://user-images.githubusercontent.com/12656294/66627262-d19b6a00-ec46-11e9-9916-33cab38b9adb.png)

When I hover over the type, it shows the composition of the type, rather than the name of the parent type.

![image](https://user-images.githubusercontent.com/12656294/66627365-2fc84d00-ec47-11e9-971d-dab6b8eadc16.png)

I would expect hovering over `useAB` to show the `target` type as `AB`

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
