### ISSUE TITLE
Terminal window is blank

### ISSUE THREAD

**Issue by sandheepp** [microsoft/vscode#82319]
Issue Type: <b>Bug</b>

Randomly, when I startup code sometimes.
I don't know why this occurs

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 5.0.0-31-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2833)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|7.70GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
LiveServer|rit|5.6.1

</details>

**Comment by fedorg** [comment]
This happens for me when i start debugging Python when the terminal panel is closed. I'm using conda environments. Only started happening in 1.40, Python extension tracks weekly insiders build.
If the terminal panel is open, most of the time it works fine. Toggling the panel with Ctrl+J from this broken state results in a blank panel and "Cannot read property 'style' of undefined" message.
Then the terminal stops working completely.
![image](https://user-images.githubusercontent.com/4352852/66649913-0b18a900-ec38-11e9-8775-99d291496c2c.png)

If I then use "focus next terminal" the terminal window reappears in a broken state. (see picture)
![image](https://user-images.githubusercontent.com/4352852/66649885-f2a88e80-ec37-11e9-9e88-a47595f00192.png)

**Comment by JuggerNau** [comment]
The same bug occurs to me.
And if I open VSCode with the terminal panel, it will work well. But if I run the VSCode with Terminator, the Terminal Window in VSC will be blank.

**Comment by lfjbb** [comment]
the same issue
