### ISSUE TITLE
Editor removes all text after cursor when using autocomplete to import

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#82323]
- Version: 1.40.0-insider (user setup)
- Commit: 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb
- Date: 2019-10-11T05:44:05.506Z
- Electron: 6.0.12
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Write a line of code including a function that needs to be imported and that has a callback (there's probably plenty of ways to reproduce this one)
2. Place cursor at the end of the name that needs to be importerd.
3. Press Ctrl+Space
4. Choose option in list
5. Press enter

VSCode now removes everything to the right of the the cursor.

Image to illustrate the issue:
![image](https://user-images.githubusercontent.com/5993909/66631965-b0ffef80-ec07-11e9-8922-47cc3991ce98.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Sounds like a dup of https://github.com/microsoft/vscode/issues/82324
Though leaving to @jrieken to decide

**Comment by JonWallsten** [comment]
@isidorn Yeah, should be the same issue. We must have written them at the same time by the look of the issue numbers. Mine is #82323 and theirs is #82324.
