### ISSUE TITLE
Expand "choice" functionality to multiline and variables

### ISSUE THREAD

**Issue by Moghul** [microsoft/vscode#82328]
I'm trying to create a more complex 'function' snippet, by allowing you to select different options for the signature after the snippet was selected.

For example, right now, I have a 'choice' for the visibility of the function, like
`${1|public,private,protected|}`

I want to be able to use the same functionality for the number of params and return type hints, including "none" as an option.

Right now, it seems like multiline code will break the 'choice' syntax, and $variables don't work as options.

Here's an example of what I'd like to be able to make work:

```
"Fancy function with options": {
	"scope": "php",
	"prefix": ["function", "func"],
	"body": [
		"/**",
		" *",
		" *",
		" * {|2@param $type $param,",
		" * @param $type1 $param1",
		" * @param $type2 $param2|}",
		" * {4|@return $returntype, |}",
		" */",
		"${1|public,private,protected|} function $functionName({3|$type $param, $type1 $param1\, $type2 $param2|}) {5|: $returntype, |} {",
		"    $0",
		"}"
	],
	"description": "Function"
},
```

This snippet would let me choose the visibility of the function
then how many params I show in the doc (1 or 2)
then how many params I show in the function (1 or 2)
then whether I return something in the doc
then whether there's a typehint on the function
then it would let me set the $returnType, $types, $params, and the $functionName
before dropping me off at $0.

I can achieve a similar result by implementing multiple snippets, but I would like something like what I described above.

PS: If this is already possible somehow, I apologize in advance; I couldn't make it work.

**Comment by jrieken** [comment]
/needsMoreInfo

Not sure if this is a question or a feature request? The provided sample above doesn't seem to be a valid snippet. Have you checked with https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax - that guide explains the snippet syntax in detail

**Comment by Moghul** [comment]
Yeah, sorry about that @jrieken, this is indeed a feature request. As the text of the issue is, the snippet is something "I'd like to be able to make work", followed by how I would exect it to work.

**Comment by jrieken** [comment]
Yeah, but it doesn't seem that you have reached the end of snippet features yet. All those choice options can be added. Do you want them to be linked? Is there a bug with choice elements containing new line characters?

Also, there is little chance that we will wildly differ from the "standard" text mate syntax (defined by TextMate itself).

**Comment by Moghul** [comment]
Alright, so I've played a bit more with the snippet, and I've found I can do multiline choices like this:

`${1|$type $param,$type1 $param1\n$type2 $param2|}`

However, after I select one of the options, I am still not prompted to change the values of the $param and $type variables. They're just treated like strings.

**Comment by jrieken** [comment]
Yes, having placeholders inside snippet choice isn't supported and if start doing so, we would break existing snippets.

**Comment by Moghul** [comment]
That's... really unfortunate. It would be nice if they were supported, maybe with some kind of custom syntax.
