### ISSUE TITLE
How could I create an interactive terminal

### ISSUE THREAD

**Issue by yuxuan** [microsoft/vscode#82329]
I created an extension, which creates a new terminal and executes some shell commands (there are some logic around each commands output, I was using `onDidWriteData` to do that), then users can keep working with terminal. 

I notice that the new terminal api finalized, the `onDidWriteData` function is gone. The pseudoterminal seems not able to be interactive, well the terminal doesn't have `onDidWriteData` anymore. 

I am not sure if I missed something. Is there an option to turn pseudoterminal to be interactively? Or how can I listen terminal output data (like `onDidWriteData` before) ?

**Comment by Tyriar** [comment]
Terminals using `Pseudoterminal` are interactive it can implement `onDidWrite` (for output) and `handleInput`. `onDidWriteData` changed to `window.onDidTerminalWriteData` and it remains proposed, chances are that it won't become stable API.

**Comment by yuxuan** [comment]
Cool, thanks for the explanation. 

The way `Pseduoterminal` interactive is different with normal terminal. It's like `TerminalRenerer` (not sure if I remember correctly). I mean, base on the new api example, with `Pseduoterminal` users can type simple characters, such as 'Y|N' to do their tasks, but not like normal terminal can use shell.

> onDidWriteData changed to window.onDidTerminalWriteData and it remains proposed, chances are that it won't become stable API.

I am also wondering what is your guys concern about this? For security reasons or performance ? I mean do you think should not give extensions the power of creating terminal instance? 

By the way `window.onDidTerminalWriteData` this api seems not been documented.

**Comment by Tyriar** [comment]
> with Pseduoterminal users can type simple characters, such as 'Y|N' to do their tasks, but not like normal terminal can use shell

You can theoretically do everything that you can do with a shell as Pseudoterminal is pretending to be the shell, it's implementing the same interface as a regular process pty is.

> I am also wondering what is your guys concern about this? For security reasons or performance ?

Both security and performance.
