### ISSUE TITLE
Blinking cursor when window not focused

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#82326]
Issue Type: <b>Bug</b>

Happens on Mac.
Can reproduce constantly by having a (one or more) Visual Studio Code editor and another window (Chrome for me). Let the other window have focus, lock the screen (apple icon -> lock screen), log in again and then all visual studio code editors have blinking cursors even though the other app has focus.
The blinking cursors don't go away until the editor has regained focus and lost it again.

(Just as an FYI this report was not possible to submit through the in-editor-report-button. When pressing "Preview on GitHub" all I got was a server-error)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|24.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexandrudima** [comment]
I can reproduce in any `<input>` field, like in the search input or the find widget input, so this is not an issue specific to the editor.

Knowing how the editor works, my best guess is that the DOM believes it gains focus and emits `focus` events...

**Comment by bpasero** [comment]
@MrAndersen1 I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue **in either or both web and Electron**?

**Comment by MrAndersen1** [comment]
@bpasero If you still need me to reproduce the issue in web and/or Electron you will have to give me more detailed instructions how to proceed, sorry, as I'm only familiar with yarn and Electron by name.
The first step of cloning the repo is fine but I don't even have yarn to my knowledge.

**Comment by bpasero** [comment]
@MrAndersen1 are you able to install a bit of additional software? Specifically:
* node.js: https://nodejs.org/en/download/
* yarn: https://yarnpkg.com/lang/en/docs/install/#mac-stable

Then you should be good to go

**Comment by bpasero** [comment]
Nevermind, I am able to reproduce in Chrome.

@alexandrudima this is not an Electron issue, thereby moving back to you to decide to report this against Chrome or if there is a workaround possible on our end.

**Comment by alexandrudima** [comment]
@bpasero This reproduces in any input so this is not an issue specific to the editor.

**Comment by bpasero** [comment]
Wow, true. I can report.

**Comment by alexandrudima** [comment]
I've reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1015798

**Comment by bpasero** [comment]
Ah you beat me to it, I added a screenshot at least 👍

**Comment by MrAndersen1** [comment]
Hehe the diff for the fix made me chuckle since I had imagined it being a larger problem :) at least it was an easy fix. 

-#if defined(OS_MACOSX)
\-      view->SetActive(true);
-#endif

**Comment by deepak1556** [comment]
Based on the crbug, the fix for this issue went in chromium 80 and should be available in our current stable. Closing this, can reopen if the bug still continues. Thanks!

**Comment by MrAndersen1** [comment]
Quick test seemed to behave correctly.
