### ISSUE TITLE
debugger not working after fresh install (tried twice)

### ISSUE THREAD

**Issue by noferusername** [microsoft/vscode#82322]
Issue Type: <b>Bug</b>

Debugger runs but no variables show up. Everything is freshly installed. I did no changes, anything. I simply try it on a simple code and does nothing

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (25.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.41019

</details>
![launch json](https://user-images.githubusercontent.com/56319690/66632091-8f2d4b00-ebbc-11e9-80b3-9d018c17bb65.png)
![running-nothing-afterwards](https://user-images.githubusercontent.com/56319690/66632098-918fa500-ebbc-11e9-8e07-fcad400bdfc8.png)

**Comment by gerk59** [comment]
I observed the same behavior on version 1.39, using Python extension (while starting unittests)
Version 1.38.1 still runs all tests, the new version(s) most of the time don't start to run / debug individual tests.

**Comment by isidorn** [comment]
Please file this against the python extension here https://github.com/microsoft/vscode-python
Thanks!
