### ISSUE TITLE
Source control

### ISSUE THREAD

**Issue by vadimmos** [microsoft/vscode#82325]
In the version control panel, sometimes nothing is displayed, although there are modified files, both local and remote. Sometimes only local changes are displayed, with the update button at the bottom left showing that there are remote changes. Even the "Remote Changes" tab is present and shows the number of files changed remotely, but does not show the files themselves.

**Comment by seveneye** [comment]
Same here. Source control shows nothing.. no tabs no text anything.. 

![image](https://user-images.githubusercontent.com/34580189/66635034-f391ee00-ec40-11e9-8b1b-2b3b209fcbae.png)

**Comment by joaomoreno** [comment]
#82203
