### ISSUE TITLE
please merge this color for c/c++ marco

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#82321]
[dimmed-monokai-color-theme.json](extensions/theme-monokai-dimmed/themes/dimmed-monokai-color-theme.json)
please add this color  for c/c++ in order to identity macro and processor in c/c++ ;
3q
`{
			"name": "Function name",
			"scope": "entity.name.function",
			"settings": {
				"fontStyle": "",
				"foreground": "#CE6700"
			}
		},

		{
            "name": "Macro Preprocessor of c/c++",
            "scope": "entity.name.function.preprocessor, meta.preprocessor.macro",
            "settings": {
                "fontStyle": "",
                "foreground": "#c70095"
            }
        },
`
otherwise macros and processors will display as same as functions. thx a lot

**Comment by alexr00** [comment]
That foreground color isn't used in this theme currently. To match how the dark and light themes work, it should use the same color as Storage (#9872A2).

@aeschli what do you want to do here? We only do `meta.preprocessor` in the dark and light themes.

**Comment by aeschli** [comment]
@heartacker You can do that by putting this in your settings:
```
"editor.tokenColorCustomizations": { 
	"[Monokai Dimmed]": {
		"textMateRules": [
			{
				"scope": [
					"entity.name.function.preprocessor",
					"meta.preprocessor.macro"
				],
				"settings": {
					"foreground": "#c70095",
					"fontStyle": ""
				}
			}
		]
	}
},
```
How did you come to this chaneg request? Is it personal preference or is it how  'dimmed monokai' is supposed to do it?
Given that also the regular Monokai also doesn't distinguish between preprocessor and regular functions, I think we should rather not do the change.
If you feel that other users think the same you can also come up with your own variant of the dimmed Monokai theme and make it available in the Marketplace.
