### ISSUE TITLE
Browser instances opened from VS Code will be sorted under the Code icon in the task bar

### ISSUE THREAD

**Issue by MariusJost** [microsoft/vscode#82333]
- **VSCode Version**: 1.39.0
- **OS Version**: Linux x64 5.0, Ubuntu 18.04.3, GNOME 3.28.2
- **Firefox**: 69.0.2
- **Extensions**:
Bookmarks | ale | 10.5.0
vscode-terminal-themes | ctf | 0.0.6
vscode-eslint | dba | 1.9.1
gitlens | eam | 10.1.1
vscode-html-css | ecm | 0.2.3
LogFileHighlighter | emi | 2.6.0
php-debug | fel | 1.13.0
php-intellisense | fel | 2.3.13
php-pack | fel | 1.0.2
todo-tree | Gru | 0.0.158
output-colorizer | IBM | 0.1.2
vscode-format-context-menu | lac | 1.0.4
git-tree-compare | let | 1.7.0
git-graph | mhu | 1.17.0
code-beautifier | mic | 2.3.3
vscode-docker | ms- | 0.8.1
LiveServer | rit | 5.6.1
code-settings-sync | Sha | 3.4.3
laravel-goto-controller | ste | 0.0.7
errorlens | use | 2.7.1

**Steps to Reproduce**:
1. Do not have an instance of your default browser running
2. Open a link from Visual Studio Code

**Expected Behaviour**:
An instance of my default browser gets opened showing the clicked link.

**Actual Outcome**:
It kind of worked as expected but the browser instance gets stacked as a VS Code instance in the taskbar. Opening more browser instances (e.g. File > New Window) will also collect them as Code instances. Happened the first time while clicking the "If you'd like to read these release notes online, go to Updates on code.visualstudio.com." link on the "Release Notes" page but can also occur when opening the "MDN Reference" link while hovering over a CSS property.

![Step2](https://user-images.githubusercontent.com/45714854/66635586-d2fd7000-ec0f-11e9-8404-9f601ba539a0.png)

![Step3](https://user-images.githubusercontent.com/45714854/66635628-ea3c5d80-ec0f-11e9-9cfe-e07fb9248798.png)

The browser works normal it just gets sorted as VS Code instance. At first I even thought it is some kind of new build in browsing feature but stacking the new browser windows under the VS Code icon is not an intended behaviour, I guess :wink:

**Comment by octref** [comment]
@Tyriar @bpasero Seems to be an issue with Electron's OS integration. Are you aware of any such issues upstream?

**Comment by bpasero** [comment]
No, never heard of.

**Comment by bpasero** [comment]
@MariusJost are you willing to try to reproduce this with Electron standalone? That would allow us to file an issue against Electron.

**Comment by MariusJost** [comment]
@bpasero sure thing, but I need to know how exactly? :slightly_smiling_face:

**Comment by bpasero** [comment]
@MariusJost start with installing Electron Fiddle: https://electronjs.org/fiddle

Then you should be able to run Electron hello world application out of that quickly. Let me know if that succeeds. Next step is to add a bit of code to do a `window.open()` and see if the task bar overlaps.

**Comment by MariusJost** [comment]
@bpasero I set it up and the hello world application did run successfully, given that this is the desired outcome:
![Screenshot from 2019-10-18 16-56-27](https://user-images.githubusercontent.com/45714854/67105450-171ce180-f1c9-11e9-9382-a721ea7bd6bc.png)

Executing window.open() within the index.html opens a new empty/blank window, sorted under the hello world fiddle
![Screenshot from 2019-10-18 17-06-40](https://user-images.githubusercontent.com/45714854/67105846-d8d3f200-f1c9-11e9-9847-db9f8437c0b2.png)

**Comment by bpasero** [comment]
@MariusJost to be clear, you are able to reproduce this issue with Fiddle, correct? Then it should be reported to Electron here: https://github.com/atom/electron

Can you do that with steps?
