### ISSUE TITLE
Webview.asWebviewUri not working in Remote

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#82336]
VS Code version: Code - Insiders 1.40.0-insider (193fead4103363d1a14873bcf38181d97cf611f6, 2019-10-10T05:26:43.233Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create webview extension with explorer context menu item
2. Use `webview.asWebviewUri(resource)` to load file within webview.
3. Install extension in Remote SSH target and try it out.

Error is: `Failed to load resource: net::ERR_FAILED`
Url is `vscode-resource://file///data/model.onnx?1570781905835`

A trivial demo extension which also tries out the new custom editor feature is at https://github.com/letmaik/vscode-netron.

**Comment by benc-uk** [comment]
I also reported this on the vscode-remote-release repo as I couldn't determine if it is the remote extension or VS Code at fault

https://github.com/microsoft/vscode-remote-release/issues/1643

**Comment by benc-uk** [comment]
It also breaks the "Markdown Preview Github Styling" extension
https://github.com/mjbvz/vscode-github-markdown-preview-style

With the same `Unable to read file (Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"))` error

**Comment by mjbvz** [comment]
Should be fixed by aeca02ae3cdf57ed91151e63b7758f88e978efb0. Will look into getting this into the VS Code 1.39.2 recovery build early this week

**Comment by letmaik** [comment]
@mjbvz Confirmed, works in Insiders. Thanks!
