### ISSUE TITLE
Can not open local file with url scheme

### ISSUE THREAD

**Issue by kanami1990** [microsoft/vscode#82338]
- VSCode Version: 1.39.1
- OS Version: MACOS 10.14.6

Steps to Reproduce:

1. use chrome open url "vscode://file/full/path/to/file"

Does this issue occur when all extensions are disabled?: Yes

it can work with 1.35 version, after update to 1.39 ,when I open url scheme,it only open a untitled-1 table

**Comment by ornic** [comment]
It worked in all versions since April patch, including 1.38.1. In 1.39 it is not. :(

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/82278
