### ISSUE TITLE
Debug: Support launch config grouping and sorting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82332]
It would be cool to support grouping in the debug launch configs, such that we can minimize the noise in the picker:

![image](https://user-images.githubusercontent.com/22350/66636353-51a6dd00-ec11-11e9-805c-fca2e3003055.png)

One idea is to mimic the menu API: https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups

We could support a `group` option which would allow to join launch configs together as well as sort them.

We can even have special groups like `commandPalette` which means that the launch config should only appear in the command palette.
Some other special groups could be `hidden` - so the launch can only be referenced by compounds, but not launched by the user.

**Comment by isidorn** [comment]
This makes sense. Assigning to October to look into it this milestone.
The `group` option would be in the launch configuration. We should maybe filter it out before sending it out to the debug adapter. Whoever we already have some "UX" attributes in the configuration so this shuold not be new teritory.

Related - duplicate https://github.com/microsoft/vscode/issues/64624

fyi @weinand @roblourens

**Comment by isidorn** [comment]
Ok, so let's recap what we want to tackle here:
1. Abitility to hide launch configurations from the dropdown and from the command palette (after typing `debug `)
2. Ability to group launch configurations / compounds (groups seperated by a visible separator)
3. Ability to sort launch configurations 

Here are some proposalls how to do that:
1. We add a attribute `presentation` in the launch configuration which is a strucutred object. `presentation` has the following fields (we can add more later):
* `visibility`: can be `hidden`, `visible`, `commandPalette`
* `group`: open ended string (name of the group which is not visible in the UX, just used for separation and sorting)
* `order`: number user for sorgin inside a group

Not that `group` and `order` could potentially be merged into one. Example: `1_groupName@5`. Here the group is 1_groupName and 5 is the order. We use this for our commands.
The name `presentation` is taken from `tasks` [reference](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks), however `tasks` use `group` for something else (for what we use compounds for)

Example 
```json
{
			"name": "Server",
			"type": "node",
			"request": "launch",
			"program": "${workspaceFolder}/src/debugAdapter.ts",
		        "presentation": {
                             "visibility": "hidden",
                             "group": "1_firstGroup"
                             "order": 3
                         }
}
```


fyi @cstavaru @grbd @alexr00 @weinand @roblourens @joaomoreno 

Looking forward to the feedback

**Comment by alexr00** [comment]
In `package.json` for ordering of context menu items we just have `group`, no `order`. Order is instead expressed by @ and then a number:
```
{
	"command": "command1",
	"group": "1_firstGroup@1"
},
{
	"command": "command1",
	"group": "1_firstGroup@2"
}
```
For consistency we could keep that pattern.

**Comment by cstavaru** [comment]
Proposal looks good to me, @alexr00 may also have a valid point.

**Comment by isidorn** [comment]
@joaomoreno deep appologies since I did not find time for this before going to Spain (requires some refactoring and is not that low hanging). I'll try to put it on a plan for next milestone.

**Comment by joaomoreno** [comment]
![ay caramba](https://media.giphy.com/media/26FmS0Hh04k0zC9R6/giphy.gif)

**Comment by smorel** [comment]
Can't wait to see that coming that would be really great!

**Comment by isidorn** [comment]
As suggested in my [comment above](https://github.com/microsoft/vscode/issues/82332#issuecomment-542624859) it is now possible to specify the `presentation` of a debug configuration or a compound.

For an example usage here is me adopting it for our `launch.json` in this repo https://github.com/microsoft/vscode/commit/ecc140e81dc5f2934181ddd40ff733a68646e149

For now I am not redenregin separators between groups. Native drop downs give me limiations on how to render, and these fake separators are just taking up space and I am not a big fan of that. I can of course add tham on top of this work.

**Comment by weinand** [comment]
@isidorn please explain "redenregin" above.

**Comment by isidorn** [comment]
@weinand sorry! Rendering was the word.

**Comment by isidorn** [comment]
We are now rendering separtors, I have updated the top picture.

To verify: make sure that you can specify the `presentation` field both for configuration and compounts and that it sorts, groups and hides as expected.
