### ISSUE TITLE
Git commits stop working... no errors!

### ISSUE THREAD

**Issue by Klian** [microsoft/vscode#82334]
- VSCode Version: 1.38.1
- OS Version: MacOS X 10.13.6

Steps to Reproduce:

1. Make some changes into a git repository
2. Try to commit clicking the check button

Does this issue occur when all extensions are disabled?:  Yes

Hello,

I cannot make git commits anymore from VSCode . I hit the "check" button and nothing happens.

Git works in my system, because I can make commit from command line in terminal.

Any idea how to solve it ?

Thanks!

**Comment by joaomoreno** [comment]
Can you reproduce in another project?

Can you reproduce this in the [insider release](https://code.visualstudio.com/insiders)?

Can you reproduce with `--disable-extensions`?

**Comment by Klian** [comment]
Thanks for your reply:

**Can you reproduce in another project?** 
Not working

**Can you reproduce this in the insider release?**
It works!

**Can you reproduce with --disable-extensions?**
Not working

**Comment by joaomoreno** [comment]
One final test: can you try running code against a new user data directory? `code --user-data-dir NEWDIR`

**Comment by Klian** [comment]
After running that command is working with vscode Version: 1.39.1

**Comment by Klian** [comment]
Solved. 

I had this setting disabled:
**Suggest Smart Commit**
