### ISSUE TITLE
CSS property completion with semicolon should place cursor at the end after inserting value

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/vscode#82330]
This is pretty self-explanatory. Before "CSS property completion with semicolon" was added my workflow was okay, the feature was really missing(!) but:

1. inserted `colo`
2. selected color from dropdown
3.  inserted `red;`
4. pressed enter to go to next line for new prop

And now it is:

1. inserted `colo`
2. selected color from dropdown
3.  inserted `red`
4. move cursor one right
5. pressed enter to go to next line for new prop

So it's really making it worse now to move the cursor to go to the next line.

**Comment by JBrown-Ascedia** [comment]
You can press ctrl/cmd + enter to jump over the semicolon.

**Comment by cfxd** [comment]
I really thought I was losing my mind because this setting wasn't taking effect no matter what I tried. Restarted vscode, rebooted my machine, etc. Turns out there are three settings to watch out for:

```
css.completion.completePropertyWithSemicolon
scss.completion.completePropertyWithSemicolon
less.completion.completePropertyWithSemicolon
```

Since I despise the new workflow it made sense for me to set them all to false.
