### ISSUE TITLE
How to debounce when the  provideCompletionItems is triggered in high frequency 

### ISSUE THREAD

**Issue by xiaoxiao426** [microsoft/vscode#82335]
- description:
I add implement of provideCompletionItems， and it will provide some customize items. when the function of provideCompletionItems id trggered, firstly, i send the restful service to acquire data for completionItems. now my question is that: the restful service is sent in high frequency, this is not reasonable, I want to debounce  when the  provideCompletionItems is triggered in high frequency 
I tried to set the property: quickSuggestionsDelay, but not worked。the "quickSuggestionsDelay" is woeked for native completion actions, not for customize.

**Comment by jrieken** [comment]
Please attach sample code or a snippet that shows this problem

**Comment by xiaoxiao426** [comment]
class myClass implements monaco.languages.CompletionItemProvider {
    provideCompletionItems(model, positon) {
       .....
    }

}
the provideCompletionItems function is called by monaco. now I want to call provideCompletionItems by myself, under the circumstance, I can put the provideCompletionItems in the function of setTimeout.

**Comment by jrieken** [comment]
Well, you need to show what's inside the `provideCompletionItems`-function. It's not true that quickSuggestDelay is only honour nor native completion providers nor that we constantly ask for results. No request is fired while one is active (not resolved, not cancelled) and unless results are marked as incomplete no further requests are made during one session
