### ISSUE TITLE
Can't show the folder or file of name 'tmp'.

### ISSUE THREAD

**Issue by senique** [microsoft/vscode#82348]
- VSCode Version: 1.39
- OS Version: Mac Mojave 10.14.6 

Steps to Reproduce:

1.Create workspace like this (tmp, tmp1, cantShow.txt are files.):
test-issue/
test-issue/testTmpFile/
**test-issue/testTmpFile/tmp**
test-issue/testTmpFile/tmp1
test-issue/testTmpFolder/
**test-issue/testTmpFolder/tmp/**
**test-issue/testTmpFolder/tmp/cantShow.txt**
2.Use VSCode open this workspace 'test-issue', it only shows:
test-issue/
test-issue/testTmpFile/
test-issue/testTmpFile/tmp1
test-issue/testTmpFolder/

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
Can you include some picttures?

**Comment by IllusionMH** [comment]
Another question : What do you have in User and Workspace settings for **Files: Exclude** (`files.exclude`)?

**Comment by senique** [comment]
> Another question : What do you have in User and Workspace settings for **Files: Exclude** (`files.exclude`)?

U r right. Cause use files.exclude for '**/tmp'.

**Comment by senique** [comment]
> Can you reproduce this with vscode insiders https://code.visualstudio.com/insiders/
> Can you include some picttures?

Remove files.exclude for '**/tmp', file and folder show right. Thanks.
