### ISSUE TITLE
Regression with Ctr+F when large data is Selected

### ISSUE THREAD

**Issue by Avinm** [microsoft/vscode#82343]
- VSCode Version: 1.39.0
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Open a file in VS Code
2. Select a large portion of the file
3. Hit Ctrl+F for search
4. Ctrl + F autopopulates data from selection
5. VSCode hangs.

Does this issue occur when all extensions are disabled?: Yes

While a possible work around is to disable the setting "Seed Search String From Selection", vscode could prevent accidental triggering of search with large seeds that would definitely crash.

**Comment by isidorn** [comment]
Potential regression, adding regression label.
I can not repro

**Comment by alexandrudima** [comment]
Multiline find input shipped with August 2019...

**Comment by Avinm** [comment]
I'm confused. Is there an update that already fixes this? And my selections had really long individual lines as well, so not sure if multiline find fixes this.

**Comment by alexandrudima** [comment]
@Avinm The issue is still open, so it has not been fixed yet.

**Comment by Avinm** [comment]
Cool.

**Comment by rebornix** [comment]
Feeding large content into the find widget input box can hang the system, no matter whether it's single line or multiple line. However it's easier to run into this case after we support multiple line find.

I'd like to call it a duplicate.
