### ISSUE TITLE
problem about touch bar

### ISSUE THREAD

**Issue by Unlocku** [microsoft/vscode#82340]
Issue Type: <b>Performance Issue</b>

There are some problems in vscode, I can not use touch bar to debug the code, which means "step into" "step over" are invalid. However, "start with debugging" and "start without debugging" are normal.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 2|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   106	   639	code main
    0	    57	   640	   gpu-process
    0	   205	   642	   window (cal_valid.py — Smart_contract)
    0	    90	   648	     extensionHost
    1	   131	   667	       /Users/ZhiChunLu/.vscode/extensions/ms-python.python-2019.10.41019/languageServer.0.4.58/Microsoft.Python.LanguageServer
    0	     0	   649	     /bin/zsh -l
    0	    33	   652	     watcherService
    0	    41	   668	     searchService
    0	     0	   698	     /bin/zsh
    2	    82	   694	   shared-process
    0	     0	   738	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    74	   723	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cal_valid.py — Smart_contract)
|    Folder (Smart_contract): 2618 files
|      File types: py(972) pyc(793) txt(385) rc(128) pyd(27) exe(17) json(12)
|                  DS_Store(12) md(8) dll(6)
|      Conf files: launch.json(7) settings.json(2)
|      Launch Configs: python;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.1
solidity|Jua|0.0.64
python|ms-|2019.10.41019

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/82222
The new release will have the fix
