### ISSUE TITLE
Filename number sort in search result 

### ISSUE THREAD

**Issue by oncealong** [microsoft/vscode#82352]
Like below, you can set the sort options in Settings, I also want to sort the file in search result.
![image](https://user-images.githubusercontent.com/5340073/66647777-6492cf00-ec5c-11e9-97db-6816e46a6499.png)

---
https://github.com/Microsoft/vscode/issues/5066

**Comment by roblourens** [comment]
I would take a PR that adds a setting with the same options.

**Comment by skprabhanjan** [comment]
@roblourens , I am working on this :)

**Comment by Wowol** [comment]
@skprabhanjan, are you still working on this? If not, I can take this. With your previous changes, it will be easier for me to implement this feature.

**Comment by skprabhanjan** [comment]
Hey @Wowol  , Please go ahead and take this up :)
