### ISSUE TITLE
buffers problem when running pwsh throught ssh with git bash integrated console

### ISSUE THREAD

**Issue by gvcgael** [microsoft/vscode#82357]
- VSCode Version: 1.37.0 and VScode Insiders
- OS Version: Windows 7

Steps to Reproduce:
See https://github.com/PowerShell/PowerShell/issues/10699#issuecomment-541006925
1. Open integrated terminal Git bash session 
2. Connect to a debian 10 Virtual machine where pwsh is installed
3. Run pwsh
4. There seems to be a problem with the buffers. Typing commands and running them does not work after the first one. Like if the buffers get unsynchronized with the inputs/outputs of the terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
