### ISSUE TITLE
Easy setting of a extension from multiple

### ISSUE THREAD

**Issue by SandeepNdd** [microsoft/vscode#82351]
Issue Type: <b>Bug</b>

Hi Team, 

It is very difficult to re set the default extension if we modified, how it is asking to configure like there should be a way to reset or modify the extension user selected other than default. Example: If i  configure Prettier formatter it will ask to configure, but once you set user cannot figure out how to reset it. Again user has to google what has to be done.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
prettier-vscode|esb|2.3.0
powershell|ms-|2019.9.0
vetur|oct|0.22.4
vscode-icons|vsc|9.4.0

</details>

**Comment by sandy081** [comment]
What kind of configuration you are talking about? If these are settings, you can open settings editor and look for modified settings from the extension and remove them. If these are other configurations please ask extension to provide a way to reset.
