### ISSUE TITLE
VS Code Insiders V1.39.1 file cannot be opened with Mac Catalina

### ISSUE THREAD

**Issue by kiwibrit** [microsoft/vscode#82353]
- VSCode Version: 1.39.1
- OS Version: Mac OS Catalina 10.15

Attempting to open downloaded file in Finder produces following error message:

_“Visual Studio Code - Insiders” can’t be opened because Apple cannot check it for malicious software._
Steps to Reproduce:

1.Download from web site 
2. Double click file in Finder

Does this issue occur when all extensions are disabled?: N/A

**Comment by nsuchy** [comment]
<img width="475" alt="Screen Shot 2019-10-11 at 10 13 29 AM" src="https://user-images.githubusercontent.com/8227641/66658629-dbee4180-ec0f-11e9-83eb-baed4453ed2e.png">
I get this same error on VS Code Stable. I was able to open by pressing option in finder and opening it that way to bypass to check. For the time being you'll need to let Gatekeeper know you trust the software regardless of what it's checks say.

**Comment by kiwibrit** [comment]
**nsuchy**, thank you - that has let me use the app.

**Comment by bhandaribhumin** [comment]
@kiwibrit https://github.com/microsoft/vscode/issues/74782
