### ISSUE TITLE
Staging/Unstaging commands missing in Diff View with Tabs enabled

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#8235]
- VSCode Version: 1.3.0-Insider
- OS Version: OSX

Steps to Reproduce:

1. Turn on Tabs
2. Make some changes to a git repo
3. Navigate to Diff View, `stage selected lines` is missing from right-up corner menu section.

**Comment by bpasero** [comment]
@rebornix editor actions moved into the tabs context menu, there you will find it.

**Comment by rebornix** [comment]
@bpasero , I didn't know tabs have context menu previously. It made those commands less discoverable but they still work well.

**Comment by bpasero** [comment]
Yeah we have a UX issue about discoverability.
