### ISSUE TITLE
i can't install extensions

### ISSUE THREAD

**Issue by abdo-cell** [microsoft/vscode#82367]
Issue Type: <b>Performance Issue</b>

i can't install extensions automaticly, there is problem when create html file in .html but it works when write in .htm format

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	  6256	code main
    0	   134	  9024	   gpu-process
    0	    66	 11460	   window (Issue Reporter)
    0	   185	 12012	   window (card.html - waqf - Visual Studio Code)
    0	     6	  2408	     winpty-process
    0	    62	  1008	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	  1292	       console-window-host (Windows internal process)
    0	    95	  4868	     extensionHost
    0	    33	 13064	       "C:\Users\Abdulrhman yusef\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Abdulrhman yusef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=4868
    0	    77	 16256	       "C:\Users\Abdulrhman yusef\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Abdulrhman yusef\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=4868
    0	    47	 16636	       electron_node server.js 
    0	    39	 10992	     searchService
    0	    13	 14476	     watcherService 
    0	    11	 14244	       console-window-host (Windows internal process)
    0	    13	 16284	   electron-crash-reporter
    0	    68	 16320	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (card.html - waqf - Visual Studio Code)
|    Folder (waqf): 3 files
|      File types: html(1) htm(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-django|bat|0.19.0
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
CppSnippets|har|0.0.14
live-html-previewer|hdg|0.3.0
HTMLHint|mka|0.6.0
mssql|ms-|1.6.0
python|ms-|2019.9.34911
atom-keybindings|ms-|3.0.6
cpptools|ms-|0.26.0-insiders2
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
html-preview-vscode|tht|0.2.5
html-css-class-completion|Zig|1.19.0

</details>

**Comment by isidorn** [comment]
Please provide more details and steps I have no clue what you are trying to say

**Comment by soo-zie** [comment]
I think I'm also facing something similar. On a fresh install of vscode I tried installing Python extension but it failed and asks for manual installation.
OS: Debian Buster (linux)
VSCode Version: 1.39.1

**Comment by abdo-cell** [comment]
First On a fresh install of vscode I tried installing a lotof  extensions but it failed and asks for manual installation.

**Comment by jrieken** [comment]
How does it fail? What's the messages that you are seeing?
