### ISSUE TITLE
Git not installed, even when it's installed (NOT DUPLICATE)

### ISSUE THREAD

**Issue by cyberhck** [Microsoft/vscode#8236]
Okay, this might be the worst bug report ever, because I'm completely new to Microsoft technologies, I'll try my best to keep it accurate and easy for you guys :)
- VSCode Version: Don't know, today I clicked on download and it downloaded me a file vscode-amd64.deb without version number on file (maybe should start version numbers on files) I went back to that site, then I couldn't find anything on versions.
- OS Version: Well, I'm running Manjaro and my `uname -r` gives me `4.1.26-1-MANJARO` which is a arch linux based OS

Description:
I tried to `sudo dpkg -i vscode-amd64.deb` and it resulted in following error:
```
(Reading database ... 2602 files and directories currently installed.)
Preparing to unpack vscode-amd64.deb ...
Unpacking visual-studio-code (1.2.1-1465908640) over (1.2.1-1465908640) ...
dpkg: dependency problems prevent configuration of visual-studio-code:
 visual-studio-code depends on git; however:
  Package git is not installed.

dpkg: error processing package visual-studio-code (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 visual-studio-code
```

I know I have git installed, so I tried `which git` and it returns `/usr/bin/git` then I thought maybe it is looking for something else, so I did a re-install of `git` by executing `sudo pacman -Syu` and it re installed my git but there was no version change as I had updated git already.

Then I try to execute `sudo dpkg -i vscode-amd64.deb` then I get the same error message

Steps to Reproduce:

1. execute `sudo dpkg -i vscode-amd64.deb`

**Comment by Tyriar** [comment]
This is happened because you probably installed `git` in a non-standard way that is not recognized by your package manager. Good news is the package's dependency on git was removed since it was a soft dependency and is no longer required on the Insiders build and v1.3.0 (coming soon). To work around this you can use the stable zip file or try out the [Insiders build](https://code.visualstudio.com/insiders) (daily build).

**Comment by cyberhck** [comment]
What do you mean by non-standard way? `pacman -S git` is the standard way to install `git` in systems with `pacman` as package manager.

**Comment by Tyriar** [comment]
@cyberhck what was the issue you had with the insiders build? It shouldn't have complained about git.

But yes, the AUR build should be good https://aur.archlinux.org/packages/visual-studio-code/, I've communicated with the package maintainers and they seem to be doing a good job.

**Comment by cyberhck** [comment]
Well, it complained that I had few other libraries missing, which pacman can't find, so I just installed from AUR, so maybe you can mention that for arch linux or pacman based users somewhere, maybe in README or in website

**Comment by Tyriar** [comment]
@cyberhck as I understand, while it's possible, Arch Linux users [shouldn't generally try install deb packages](http://unix.stackexchange.com/a/83544/115410) for these very reasons. I've had discussions with the website team about adding more detailed Linux setup advice on a per-distribution level to https://code.visualstudio.com/docs/setup/linux, that will happen eventually which will remedy this :smiley:
