### ISSUE TITLE
IntelliSense autocomplete replacing next word / special character

### ISSUE THREAD

**Issue by bdesales** [microsoft/vscode#82363]
Hi there, since today's VSCode Insiders update IntelliSense is acting weird. It removes or replaces whatever is next to it when enter is pressed, words, bracket ending, parenthesis ending (Even when auto-completing inside a function parameter). This is really annoying, specially when working with typescript. Can anybody fix this, please? Appreciated.

**Comment by OfficerHalf** [comment]
It seems to have something to do with speed - if I let the suggestion sit for a second, using the completion does not overwrite the next word. Perhaps a regression of this issue: #56026?

**Comment by isidorn** [comment]
Duplicate. We already pushed a fix, coming to insders on Monday. Sorry about this!
