### ISSUE TITLE
Autocomplete to responding to keyboard

### ISSUE THREAD

**Issue by aholla** [microsoft/vscode#82361]
Hi, since the last update my auto complete is not working as expected. Before I could tap Enter or use the arrow keys to change the selection, now nothing happens when i press the keyboard and it seems to be tied to my mouse.

This might be a setting that has been reverted but I dont know where.

Thanks.

**Comment by isidorn** [comment]
We are aware of a breakage in this area and we will tackle this soon - Monday. There is already a PR which tackles this
