### ISSUE TITLE
git index file gets locked on local network server

### ISSUE THREAD

**Issue by X-Tender** [microsoft/vscode#82370]
- VSCode Version:  1.39.1
- OS Version: MacOS High-Sierra

We have a Ubuntu Server in our network where we work on our projects.
When I work on some files in VS code and try to stage them via vscode git plugin, CLI or a GIT Client (GitKraken) I get the error "index file locked". Then I delete the index file, clean up after that (because after deleting the index file and staging 1 File, all files are marked as deleted, so I unstage everything and everything is good again) Then I can stage files and commit them.

Then I continue with my work, do some code and try to stage/commit again. And then the error appears again.

When I disable the GIT plugin via `"git.enabled": false`  in the `settings.json` then the problem never appear.

However I would like to have the git feature in vscode to see my changes and untracked files .. So what could cause the problem?

**Comment by joaomoreno** [comment]
Can you reproduce this issue by using command line git, without using VS Code as well?

**Comment by joaomoreno** [comment]
> However I would like to have the git feature in vscode to see my changes and untracked files .. So what could cause the problem?

I highly recommend trying [VS Code Remote SSH](https://code.visualstudio.com/docs/remote/ssh) to edit remote files.

**Comment by X-Tender** [comment]
It only happens when I have VSCode open and edit files + have the git extension.
It's also happen when I close vscode before staging/comiting any files.
The server is in our local network, we access it via a network drive.

**Comment by joaomoreno** [comment]
I mean, if you use the command line to run `git add`, `git commit`, etc... this does not reproduec?

**Comment by X-Tender** [comment]
When I use `git add myfile` then I get `fatal: Unable to write new index file`after I worked on some files.

**Comment by joaomoreno** [comment]
Alright. I'm interested in knowing whether you can reproduce this only with the command line and Notepad (I suspect you can) which would mean you simply have a setup issue, by using git through a network share.

**Comment by X-Tender** [comment]
I just tested it with the good ol' Sublime TextEditor and no problems with it. It also have a git integration. So it have something to do with the git integration in vscode :/
I also tried it with disabled autosync but that doesn't changed anything.

**Comment by joaomoreno** [comment]
VS Code simply spawns git, so it must be very reproducible simply running `git add` and `git commit` commands. Have you tried that?

**Comment by joaomoreno** [comment]
Also which version of git do you have installed?

**Comment by X-Tender** [comment]
I only experience the problem when I have vscode open and have the git plugin enabled.
It just require to enable it, no staging noch commiting, I just enable it and right after that when I try to stage a file (via terminal or another git GUI) git tells me that he cant stage because the index file is locked.

git version 2.17.2 (Apple Git-113)

**Comment by joaomoreno** [comment]
Can you update to a fresher git (current is 2.23.0)? You can use Homebrew for that. Let me know how it goes.
