### ISSUE TITLE
When terminal is focused, selecting test in editor won't focus the editor

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#8237]
- VSCode Version: 1.2.1
- OS Version: OS X

Steps to Reproduce:

1. Open terminal 
2. Open a text editor as well
3. Execute a command in terminal 
4. Using mouse make a selection in editor 

Editor is not focused. You have to click on editor again to focus in it

**Comment by bpasero** [comment]
I cannot reproduce, @mohsen1 any more details? video / screenshot maybe?

**Comment by mohsen1** [comment]
It's actually not just by selecting. Clicking on the editor won't switch the focus either. 

I use [Fish](http://fish.sh/) if that matters.

here is a screencapture:
https://gfycat.com/ImpeccableFluidLabradorretriever

**Comment by bpasero** [comment]
@Tyriar can you reproduce?

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/7684, fixed in Insiders
