### ISSUE TITLE
git.confirmEmptyCommits setting no longer relevant

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82388]
This happens in Insiders v.1.40.0

- VSCode Version: v1.39.1 and Insiders v.1.40.0
- OS Version: macOS 10.15

Steps to Reproduce:

1. Set `"git.confirmEmptyCommits": true`
2. Notice that VS Code still doesn't allow you to submit an empty commit

Does this issue occur when all extensions are disabled? Yes

**Comment by joaomoreno** [comment]
This is for the `Git: Commit Empty` command.
