### ISSUE TITLE
Word being deleted by parentheses

### ISSUE THREAD

**Issue by malarahfelipe** [microsoft/vscode#82381]
VSCode Version: 1.40.0-insider 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb 29-10-11
OS: Linux x64 5.0.0-31-generic snap
OS Version: Ubuntu 18.04.3 LTS

Steps to reproduce:

1.Write any random word in a .js or .ts file
2.Instantiate any function before next to the text and open the parentheses 
3.The word will be deleted instead being wrapped by the parentheses

Does this issue occur when all extensions are disabled?: Yes

**Comment by pocesar** [comment]
also happens with quotes `"` `'` and brackets `[` `]`

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/82324
