### ISSUE TITLE
Quick Suggestions in Markdown treat Virama as a word separator

### ISSUE THREAD

**Issue by vizzmay** [microsoft/vscode#82386]
- VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
- OS version: Windows_NT x64 10.0.18362

**Virama** or Halant is a diacritic used in Brahmic scripts such as Devanagari to suppress the inherent vowel of a consonant. (क = *ka* + ् (virama)  becomes क् = *k*.) It’s most often used in writing conjunct characters. (e.g. *kṣa*, क्ष = क + ् + ष)

Since Virama is a part of a word, if I were to turn on quick suggestions and type a word with a Virama in it, I would expect the entire word to be shown as a suggestion. This is true for a plaintext file.

However, if I am typing in a markdown file, VSCode suggests a truncated word, possibly because it treats the Virama as a punctuation mark or a word separator and assumes that the word ends there.

**Example:** राजेन्द्र has the conjunct न्द्र (न + ् + द + ् + र). When it is a plaintext file, the entire word is shown in quick suggestions.

![rajendra-plaintext](https://user-images.githubusercontent.com/10206339/66673369-0b3b9780-ec7e-11e9-9e16-13f75f33c246.png)

When it is a markdown file, only राजेन is shown as a suggestion.

![rajendra-markdown](https://user-images.githubusercontent.com/10206339/66673388-18588680-ec7e-11e9-8bcb-8ed0ce1855d4.png)

This behavior is observed for Devanagari and Gujarati, and possibly for every language that has a Virama character in it.

This behavior is observed in Markdown, but not in other filetypes.

**Possibly related behavior:**

When you put the cursor in the middle of a word and press Ctrl+F, the entire word is selected and taken as a search parameter. This is true for plaintext, but not for markdown. In markdown, the word is truncated at Virama.

In plaintext file:

![search-plaintext](https://user-images.githubusercontent.com/10206339/66673414-23abb200-ec7e-11e9-8a4e-25243a2a4667.png)

In markdown file:

![search-markdown](https://user-images.githubusercontent.com/10206339/66673425-28706600-ec7e-11e9-852e-d1de7a237503.png)

**Comment by alexandrudima** [comment]
This is caused by the word pattern [used in markdown](https://github.com/microsoft/vscode/blob/2a8cc9c067b7003a94e6d6e77e5506b4b0427ffd/extensions/markdown-language-features/src/extension.ts#L59):

```
wordPattern: new RegExp('(\\p{Alphabetic}|\\p{Number})+', 'ug'),
```

The default (plain text files) is:

```
/(-?\d*\.\d\w*)|([^\`\~\!\@\#\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g
```

The second one is friendly towards unknown scripts because it targets what are word separator characters, not what are word characters.
