### ISSUE TITLE
UI blanks out portion of screen

### ISSUE THREAD

**Issue by pyuser00** [microsoft/vscode#82385]
In the last several releases of VScode (going back to about v1.35) , I periodically experience an issue with the user interface where the top 10-15% of my screen (from about the search icon up) goes completely white or black and nothing on the portion of the screen responds to the mouse. 
'Alt' key does not access the menus so that I can move or resize the window. Restarting VScode does not the resolve the issue. Display is fine because moving another window to same position results in full functionality. 

VScode v1.35 through 1.39
Win10
Disabling all extensions does not resolve the issue.

**Comment by sbatten** [comment]
@deepak1556 does this align with an electron upgrade?

**Comment by deepak1556** [comment]
@pyuser00 can you try the latest insiders https://code.visualstudio.com/insiders/ to see if the issue repros. Also can you try launching code with `--disable-gpu` if the issue is present ? thanks!

**Comment by pyuser00** [comment]
--disable-gpu switch does not resolve the issue. Noticed the blank part of the Code UI is the same size as the Google Chrome top menu bar - any possible conflict there, especially when pulling off tabs into another window?

**Comment by qodfathr** [comment]
I just noticed something similar with 1.40.0-insider. I have dual monitors; full-screen on secondary 1920x1200 monitor is fine, but on primary 4k monitor the top section of the window isn't rendering properly. (gray and black rectangular areas where menus should be):
![image](https://user-images.githubusercontent.com/16322190/67505240-e0c3e400-f658-11e9-8e3e-d35ae613bdf3.png)

If I right-click in this area, I get the pop-up menu for Windows' desktop:
![image](https://user-images.githubusercontent.com/16322190/67505351-14067300-f659-11e9-98a4-29dbc7924643.png)

**Comment by qodfathr** [comment]
FWIW, my NVIDIA driver got updated and the problem went away for me. (Did not even require a reboot.)

**Comment by deepak1556** [comment]
@pyuser00 does it still repro with latest stable ?
