### ISSUE TITLE
editor.renderControlCharacters setting isn't working

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82387]
This happens in Insiders v1.40.0

- VSCode Version: 1.39.1 and Insiders v1.40.0
- OS Version: macOS 10.15

Steps to Reproduce:

1. Set "editor.renderControlCharacters": true
2. Notice that control characters like CR, LF or EOF don't show up

Does this issue occur when all extensions are disabled? Yes

**Comment by alexandrudima** [comment]
Duplicate of #12223
