### ISSUE TITLE
Wrong state of Maximize/Restore button after exiting Fullscreen and then Restoring window

### ISSUE THREAD

**Issue by Eldaw** [microsoft/vscode#82384]
Using VS Code 1.39.1 on Windows 10, here are the steps to reproduce:

1. Start with a normal, non-maximized window.
2. Maximize the window. The maximize button in the top right turns into a Restore button (as expected).
3. Hit F11 to enable Fullscreen.
4. Hit F11 again to disable Fullscreen.
5. Click the Restore button to return to a non-maximized window.
6. Notice that the Restore button has not gone back to being a Maximize button. Instead, it remains as a Restore button (not expected).

**Comment by sbatten** [comment]
great repro steps, can confirm in both electron4 and electron6

**Comment by sbatten** [comment]
On the final restore, we are not getting an unmaximize event.

https://github.com/microsoft/vscode/blob/43ca0e302989a85d0ef0d0e63119d5d66cc0b12a/src/vs/workbench/electron-browser/window.ts#L288

I've tried removing the filter at the step above in case we were at fault, but still no event is triggered. 

We are listening to the following event:
https://github.com/microsoft/vscode/blob/a949694b25eb9e01998b4033103e0420ab18674c/src/vs/platform/electron/electron-main/electronMainService.ts#L46

**Comment by Eldaw** [comment]
@deepak1556 Is this bug known about upstream? Just curious about what's currently happening with it.

**Comment by deepak1556** [comment]
Caption buttons are now natively rendered by the runtime with WCO.
