### ISSUE TITLE
source control not working

### ISSUE THREAD

**Issue by ccellhb** [microsoft/vscode#82390]
Issue Type: <b>Bug</b>

Changes number is shown, but blank window after click source control button

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

**Comment by isidorn** [comment]
fyi @joaomoreno
