### ISSUE TITLE
search fails on query string found by grep

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#82391]
- VSCode Version: 1.39.1
- OS Version: macOS Mojave 10.14.3 18D109 x86_64
Does this issue occur when all extensions are disabled?: Yes

search does not find string

![Screen Shot 2019-10-11 at 2 27 14 PM](https://user-images.githubusercontent.com/11388735/66675733-f2a68f80-ec33-11e9-983d-953d613e57bc.png)

but grep does

![Screen Shot 2019-10-11 at 2 27 22 PM](https://user-images.githubusercontent.com/11388735/66675751-f803da00-ec33-11e9-82da-1ec72b91212e.png)

**Comment by roblourens** [comment]
You have selected the "whole word" option (the blue outlined box in the search input). If you deselect that it should work.

**Comment by zachvalenta** [comment]
😔 my bad y'all!
