### ISSUE TITLE
Close All should close all tabs, not just those in the pane

### ISSUE THREAD

**Issue by jsuddsjr** [microsoft/vscode#82396]
Issue Type: <b>Bug</b>

Open several files. Drag a few to new panes in the editor. Then, right-click on a tab and select Close All (Ctrl+K, W). Only the files in the pane are closed. I have to close "All" several time until all files are closed. Suggest adding another command to close the files in the pane.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jest-snippets|and|1.7.0
code-gnu-global|aus|0.2.2
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|2.4.3
find-related|eam|0.8.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.1
vscode-npm-script|eg2|0.3.9
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|2.3.0
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.1.0
vscode-google-translate|fun|1.4.2
vscode-test-explorer|hbe|2.14.6
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
react-jest-vscode-snippets|jal|0.0.3
vscode-nuget-package-manager|jmr|1.1.6
import-sorter|mik|3.3.1
vscode-scss|mrm|0.6.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-edge-devtools|ms-|1.0.4
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vs-keybindings|ms-|0.2.0
vscode-node-azure-pack|ms-|0.0.9
vsliveshare|ms-|1.0.950
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
debugger-for-chrome|msj|4.12.0
debugger-for-edge|msj|1.0.11
gulptasks|nic|1.3.1
printcode|nob|3.0.0
react-proptypes-intellisense|OfH|1.0.3
vscode-versionlens|pfl|0.24.0
nested-comments|phi|2.3.1
tsimporter|pmn|2.0.1
sass-helper|ram|0.0.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-jest-test-adapter|rtb|0.2.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.18
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.1.9
vscode-icons|vsc|9.4.0
quokka-vscode|Wal|1.0.254
wallaby-vscode|Wal|1.0.146
vscode-webhint|web|1.3.2
glean|wix|4.16.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
ReactSnippets|xab|2.3.0
markdown-pdf|yza|1.3.1
markdown-all-in-one|yzh|2.5.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/66758218-271d8400-ee9e-11e9-9ce7-0c9339d9be26.png)
