### ISSUE TITLE
Right clicking on a file again with a wait crashes VM.

### ISSUE THREAD

**Issue by T-Younce** [microsoft/vscode#82393]
Issue Type: <b>Bug</b>

When you right click on a open folder. It works fine at first. But after a little bit, when you right click on the mini window, the entire virtual machine crashes due to a memory error.
Edit: Here's a link to a picture
[https://1drv.ms/u/s!AiPenPxifnh8hp4A8JwVJIIecOwOgQ?e=m6veF7](url)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|7.40GB (4.83GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.5.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
vscode-yaml|red|0.5.3

</details>

**Comment by deepak1556** [comment]
@T-Younce can you provide more info about your VM setup and some steps to repro. The linked attached in the issue is broken. Also a video/gif demo of the issue would be great, Thanks!

**Comment by T-Younce** [comment]
I actually got it fixed by reinstalling the program. Thanks. I don't know why that happened. But reinstalling VSCode seemed to fix it.




Get Outlook for Android







On Fri, Oct 11, 2019 at 6:59 PM -0600, "Robo" <notifications@github.com> wrote:












@T-Younce can you provide more info about your VM setup and some steps to repro. The linked attached in the issue is broken. Also a video/gif demo of the issue would be great, Thanks!
