### ISSUE TITLE
Cannot run Visual Studio Code on macOS 10.15

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vscode#82406]
- VSCode Version: 1.39.1
- OS Version: 10.15

Steps to Reproduce:

1. `brew cask install visual-studio-code`
2. `code`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![Screen Shot 2019-10-11 at 6 19 43 PM](https://user-images.githubusercontent.com/434849/66692507-f0542d80-ec53-11e9-9884-b2ca94fc55c9.png)

You should notarize your app.

https://support.apple.com/en-us/HT202491

**Comment by kjhx** [comment]
As a temporary fix, you can run the app by going to System Preferences -> Security & Privacy -> General -> and clicking Open Anyway.
