### ISSUE TITLE
when open vscode , alert window has crashed,how to solve

### ISSUE THREAD

**Issue by jialadi-WEB** [microsoft/vscode#82402]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
