### ISSUE TITLE
The Markdown Typescript code parser is bailing on a very specific snippet containing generics and a lambda arrow

### ISSUE THREAD

**Issue by ChristianIvicevic** [microsoft/vscode#82400]
- VSCode Version: 1.39.1
- OS Version: Windows x64 10.0.17763

Steps to Reproduce:

1. Create a new Markdown file
2. Add the following snippet
````md
```typescript
const array = [1, 2, 3].reduce<number[]>((acc, next) => [...acc, next], []);
//                             ~~~~~~~~
// Type of the initial value, in our case making it an array of numbers.
```
````

Doing so will make the formatter bail and the comment below won't be recognized as a comment:

![image](https://user-images.githubusercontent.com/45569997/66688262-23afb000-ec86-11e9-9658-de58a7f860b9.png)

However when removing the arrowhead of the lambda it works as expected:

![image](https://user-images.githubusercontent.com/45569997/66688278-3aee9d80-ec86-11e9-9ddd-7a5b938d71ab.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is in the markdown preview, correct? The highlighter in the markdown preview uses highlightjs by default. 

Please file an issue against that project: https://github.com/highlightjs/highlight.js

**Comment by ChristianIvicevic** [comment]
@mjbvz Alright, thanks for pointing me in the right direction. On a slightly different "off"topic, I stumbled upon highlightjs myself yesterday since I am moving from Markdown to Asciidoc and noticed their Typescript highlighting isn't too advanced yet (only keywords, built ins, strings and numbers are highlighted, no members, function invocations, parameters or 3rd party types) in comparison to Githubs Markdown highlighting. Let's see whether I can contribute there to improve upon that a bit.

**Comment by ChristianIvicevic** [comment]
Here is the new issue for anybody noticing the same problems: https://github.com/highlightjs/highlight.js/issues/2189
