### ISSUE TITLE
Window Title Not Instantly Updated when showTabs Enabled

### ISSUE THREAD

**Issue by ijat** [Microsoft/vscode#8240]
- VSCode Version: 1.3 insider
- OS Version: Win7

Steps to Reproduce:

1. Enable tab in user settings => "workbench.editor.showTabs": true
2. Open many files.
3. Select other tab.
4. The window title doesnt change instantly. Unless you resize/change other window or redraw occur?.

**Comment by bpasero** [comment]
@ijat the window updating should happen in any case also when tabs are not enabled. you say you only see this when tabs are enabled?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
