### ISSUE TITLE
The terminal process terminated with exit code: 3221225506

### ISSUE THREAD

**Issue by xfxf521** [microsoft/vscode#82411]
Issue Type: <b>Bug</b>

click terminal show
'The terminal process terminated with exit code: 3221225506' error

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (11.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.9.0

</details>

**Comment by Tyriar** [comment]
Does the same occur in Windows Terminal? https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701

Can you share your settings.json

**Comment by xfxf521** [comment]
I didn't make any configuration changes for settings.json。
this is my setting.json file.
{
    "terminal.integrated.enableBell": true,
    "workbench.startupEditor": "newUntitledFile"
}

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
