### ISSUE TITLE
Screen cheese when close all to the right

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8241]
#7854

- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

In the second editor group:
1.  open two tabs
2.  open two / three more untitled tabs by double clicking on margin
3. second tab context menu -> close all to the right
4. I get screen cheese

Please try a couple of times since I do not repro this 100% but happens every other time..

![screen shot 2016-06-28 at 09 24 02](https://cloud.githubusercontent.com/assets/1926584/16407081/176d9dd8-3d12-11e6-9936-a29ece241dc3.png)

**Comment by bpasero** [comment]
Verified this is fixed with Chrome >=  51. I do not want to add hacks to  force a repaint.

**Comment by isidorn** [comment]
Agree - it is nothing mayor, any update in the header area fixes the issue

**Comment by bpasero** [comment]
I think our Electron update fixed this.
