### ISSUE TITLE
Font Aliansing is not working

### ISSUE THREAD

**Issue by pavangayakwad** [microsoft/vscode#82414]
Issue Type: <b>Bug</b>

On my Windows 10 machines, font aliasing never worked. 

VS Code version: Code - Exploration 1.39.0-exploration (a715df3459718a501686bd03414f69929bf6e9a2, 2019-09-13T06:41:33.699Z)
OS version: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/1834890/66696299-6d30e700-ece8-11e9-8483-30e198255eb7.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
@pavangayakwad can you try the latest insiders https://code.visualstudio.com/insiders/ and report back if the issue still persists. Thanks!

**Comment by pavangayakwad** [comment]
Sure. 

Here is the screenshot. issue persists.

![image](https://user-images.githubusercontent.com/1834890/66865616-33e0cb80-efb5-11e9-92ff-60a87d143a98.png)

**Comment by pavangayakwad** [comment]
So is that it? no more actions/resolutions on this?
