### ISSUE TITLE
Multiple code edits doesn't work

### ISSUE THREAD

**Issue by MaxBec** [microsoft/vscode#82421]
Hey guys,

i want to edit a code file multiple times. First delete all unnecessary line breaks. And then with the newly formatted file do a column style edit of the code. Unfortunately if i call the applyEdit the code is altered once. That's correct. But the new selections, ranges, etc. don't work with the new but with the old code. I have fire the command for the extension again and then the second edit is done. How can i refresh the editor in the code itself? So i can work on the newly formatted code?

```
workEdits.set(doc.uri, textEdits); // give the edits
vscode.workspace.applyEdit(workEdits);
```

**Comment by Cardoso222** [comment]
Could you please share more info about your environment ?

**Comment by MaxBec** [comment]
Of course. I am running VSC on a Mac. Newest OS version.

The problem is that I need to make two changes on the code. First delete unnecessary line breaks and then, WITH the newly formatted code some other changes. The problem is that the while the extension running the changes aren't updated on the editor. So I can't work on the new code with no line breaks to make the other changes. I need to call the command on the code twice. Only then it works.

So I guess you cannot call workspace.applyEdit twice, right? Cause it's somehow blocked?

Mit freundlichen Grüßen
Maximilian Beckenbauer
Am 13. Okt. 2019, 06:32 +0200 schrieb Paulo Henrique <notifications@github.com>:

**Comment by usernamehw** [comment]
https://github.com/Microsoft/vscode/issues/48908#issuecomment-385326765 ?

**Comment by MaxBec** [comment]
Yeah I saw it. But how would a solution with the thenable look like?

**Comment by usernamehw** [comment]
```ts
async function doSmth() {
	const activeTextEditor = window.activeTextEditor;
	if (!activeTextEditor) {
		return;
	}
	const edit1 = new vscode.WorkspaceEdit();
	const edit2 = new vscode.WorkspaceEdit();
	edit1.delete(activeTextEditor.document.uri, new vscode.Range(0, 0, 0, 5));
	edit2.delete(activeTextEditor.document.uri, new vscode.Range(1, 0, 1, 5));
	await vscode.workspace.applyEdit(edit1);
	await vscode.workspace.applyEdit(edit2);
}
doSmth();
```

**Comment by MaxBec** [comment]
Ok. But i want to apply the first edit and then with the newly formatted code do something else. In your example you are doing two different things but on the same code.

**Comment by jbracer19** [comment]
Can just get a little help to start?

On Oct 13, 2019, at 1:21 PM, Max Beckenbauer <notifications@github.com> wrote:

﻿

Yeah I saw it. But how would a solution with the thenable look like?

**Comment by MaxBec** [comment]
> ```ts
> async function doSmth() {
> 	const { activeTextEditor } = window;
> 	if (!activeTextEditor) {
> 		return;
> 	}
> 	const edit1 = new vscode.WorkspaceEdit();
> 	const edit2 = new vscode.WorkspaceEdit();
> 	edit1.delete(activeTextEditor.document.uri, new vscode.Range(0, 0, 0, 5));
> 	edit2.delete(activeTextEditor.document.uri, new vscode.Range(1, 0, 1, 5));
> 	await vscode.workspace.applyEdit(edit1);
> 	await vscode.workspace.applyEdit(edit2);
> }
> doSmth();
> ```

Thank you! It worked with the async function!
