### ISSUE TITLE
Rust: cargo build produces huge load on file watcher (Linux)

### ISSUE THREAD

**Issue by gophobic** [microsoft/vscode#82427]
RLS on Linux is already very buggy and causes memory leak, but it stabilizes after eating around 1GB, but today after I updated VSCode to 1.39.1, now VSCode itself, namely `code /BIN_HOME/visual-studio-code/resources/app/out/bootstrap-fork --type=watcherService` component eats more RAM on each file save until the system totally freezes. I am not sure whether something changed in this component in 1.39 release. Downgrading solves the problem, also note that `rls-vscode` extension hasn't been updated for a while so it's not the extension's problem.

**Comment by bpasero** [comment]
@gophobic any chance you maybe have a cyclic symbolic link?

**Comment by MusiKid** [comment]
I got the same problem with even worse performance...
![memory](https://user-images.githubusercontent.com/12956751/66783335-fc502180-eed7-11e9-914d-f9c8881ae205.png)
I tested for circular and broken symbolic links but didn't find anything.

**Comment by bpasero** [comment]
@gophobic @MusiKid any chance the folder you open is something that is shareable (open source) so that I could try to reproduce?

**Comment by MusiKid** [comment]
I can reproduce it with all Rust repod but you can try with *ripgrep-all*

**Comment by bpasero** [comment]
@MusiKid link?

**Comment by MusiKid** [comment]
Here: https://github.com/phiresky/ripgrep-all

**Comment by bpasero** [comment]
@MusiKid does it reproduce if you open that folder as part of a multi-root setup? We use a different file watcher in that case, just File > Save Workspace As and add another folder.

**Comment by MusiKid** [comment]
It consumes much less RAM so I think it's not reproducing this bug
![mem leak](https://user-images.githubusercontent.com/12956751/66875306-1e1bd800-efae-11e9-87be-ea0d4986286a.png)

**Comment by bpasero** [comment]
@MusiKid I cannot reproduce with that folder. It also does not contain a lot of files it seems, can you share how many files you see in that repository?

![image](https://user-images.githubusercontent.com/900690/66912202-6cfb5900-f012-11e9-9faa-be2a4c5236d7.png)

If you have a single large folder with lots of files, try setting the `files.watcherExclude` setting to ignore it.

**Comment by MusiKid** [comment]
It's weird, I got much more files in my folder.
![files](https://user-images.githubusercontent.com/12956751/66933055-c8d8d880-f038-11e9-883b-d195d88b95e2.png)
Maybe you can try to remove the *target* folder and restart vscode.

**Comment by bpasero** [comment]
@MusiKid did you maybe run some kind of installation tool in that repo that added lots of files into? If so, can you share it or find another sample?

**Comment by MusiKid** [comment]
Nothing special, I just removed the target folder because RLS was building indefinitely.

**Comment by bpasero** [comment]
@MusiKid without a reproducible case (= a folder I can checkout locally), there is not much I can do, sorry.

**Comment by MusiKid** [comment]
I uploaded my repo so you can take a look at this: https://send.firefox.com/download/b3e7d4f9973b2402/#vnfmN78g-TJlydhApd7i-g
You can check the VirusTotal scan if you don't trust it (just 2 false positives): https://www.virustotal.com/gui/file/f861d64440e13668845c16f3dfcf284d33e58e1cf1126a18f1d8ac2024cd9ce3/detection

**Comment by bpasero** [comment]
Thank you but I would prefer a GitHub OSS repository and not download something from elsewhere.

**Comment by MusiKid** [comment]
I created a `debug` branch on my fork with all files included in: https://github.com/MusiKid/ripgrep-all.git

**Comment by bpasero** [comment]
@MusiKid great thanks, however I do not see a spike on my Ubuntu VM:

![image](https://user-images.githubusercontent.com/900690/67007488-cda89580-f0e7-11e9-879d-1c5d9f011300.png)

Can you share your htop?

**Comment by MusiKid** [comment]
Sure.
![Capture d’écran de 2019-10-19 18-56-25](https://user-images.githubusercontent.com/12956751/67148679-7ac70d80-f2a2-11e9-9107-e628449ecda7.png)
Also, thanks for taking time to resolve this problem!

**Comment by elomatreb** [comment]
I am also seeing this behavior, and I am also experiencing crashes (SIGABRT) of the affected process. It stops happening when I switch the project to multiple root directories as well.

**Comment by bpasero** [comment]
@MusiKid @elomatreb can we try an experiment to ensure no extension or setting is involved.
* download VSCode insiders (can be run alongside stable): https://code.visualstudio.com/insiders/
* open a command line prompt
* `git clone https://github.com/MusiKid/ripgrep-all.git`
* `git checkout debug`
* `code-insiders --disable-extensions --user-data-dir <some empty directory>`
* open the checked out folder
* watch `htop` on the watcher service process of code insiders (!)

What is the result?

**Comment by elomatreb** [comment]
Following the above steps, the process does not start to grow in memory by itself. When I start a `cargo build` however, it consumes multiple cores worth of CPU, and its memory use starts to grow rapidly. When I stop the build or it finishes, the memory use does not go back down, and when I repeat this it sometimes results in the SIGABRT I mentioned above (and the resulting coredump file being written causes the entire PC to become very close to freezing).

I can provide one of these coredump files if there's nothing sensitive in them, but apparently they were too large and they are "truncated", so I don't know if they're still useful

**Comment by bpasero** [comment]
@elomatreb I assume `cargo build` is causing tons of files to be created in some build directory? Typically it is wise to exclude such folders via the files.watcherExclude setting. By default we exclude `node_modules` but we can tweak this setting default to exclude more if you can find that folder.

**Comment by elomatreb** [comment]
Cargo puts lots of build artifacts into `target/`, adding a pattern for it to the watcher ignore list does fix the behavior. I'm not sure why this wasn't a problem before, but this is an easy fix, thanks for the suggestion.

**Comment by bpasero** [comment]
@MusiKid can you confirm you are doing the same?

**Comment by elomatreb** [comment]
Ignoring the folder in Rust projects would probably make sense in 99.9% of cases, but since it's such a generic name I'm not sure.

**Comment by bpasero** [comment]
Yeah I am worried that it would cause issues for people using this folder for a different purpose.

**Comment by bpasero** [comment]
I reported this as https://github.com/paulmillr/chokidar/issues/922 and we have to wait for an official fix. Until then, excluding this directory is the correct workaround.

**Comment by escape0707** [comment]
Hi, there. I think I just get caught by the same issue but this time it's under a `g++` compiling process. I first encountered this problem on my  Arch laptop, and I've reproduced it just a min ago using Ubuntu 19.10 inside a Hyper-V VM on latest Win 10 stable version.

![image](https://user-images.githubusercontent.com/11014745/67613795-206b0700-f7e4-11e9-96cb-03e4beb0da60.png)

You can pull my repo on GitHub and give it a test. The repo contains only some ~~(stupid, sorry, just ignore the logic errors in it for now)~~ exercises code for C++ Primer and don't contain a lot of files even during building process. So I don't think the problem is affected by the number of files inside the workspace.

```bash
# on latest Ubuntu
git clone https://github.com/escape0707/cplusplus-primer-exercises.git
cd cplusplus-primer-exercises
code .
g++ -std=c++17 StrBlobPtr.h -o a.out
```

The `g++` compiler should give compile error quickly after a short time and finished. But the watcherService shows that it's continuously eating up CPU and RAM resources. And when this phenomenon appears on my Arch laptop, the laptop will finally get frozen.

Note that compiling some other files like `1.1.cpp`, `1.11.cpp`, `Date.h`don't seems to trigger this issue, but `Sales_item.h` and `StrBlobPtr.h` will. If it doesn't happen, maybe compile `StrBlobPtr.h` for a second time will do.

And when I try to reproduce this on latest Manjaro distro which comes with a VSCode version 1.28.1, the problem will not show.

I wish the info provided above could help to locate the issue clearer.

**Comment by bpasero** [comment]
Thanks!
