### ISSUE TITLE
The ability to scrool sideways and to zoom with trackpad at anything!!!

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [microsoft/vscode#82429]
![Captura de Tela (3)_LI](https://user-images.githubusercontent.com/52057747/66702807-00b2e980-ece2-11e9-8a8b-66a6336845a0.jpg)

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
