### ISSUE TITLE
[SCM tree]: Keep first level indent the same as list

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#82420]
Pretty similar to #66863. SCM tree should exclude first level items and keep indent at `8px`

1. 
```js
"scm.defaultViewMode": "tree",
```
2. Indent for first level items is too big, because of
```js
"workbench.tree.indent": 20,
```

**Comment by joaomoreno** [comment]
I actually think this is OK as it is, since the resource groups are "folders"
