### ISSUE TITLE
language extention issues on macOS Catalina

### ISSUE THREAD

**Issue by AndreaElijha** [microsoft/vscode#82431]
when i update my system to macOS 15，vscode stick on crush in annoying problems.
1、c/c++ language support problem：when i open a new folder on my workspace，compile and run cpp using launch.json and tasks.json，it alert that cannot create json file. Then i have to uninstall my c++ extension and reinstall it. but just after a littel time，if i delete .vscode or open a new folder，this problem comes again. having tried to fix this by chmod command line, but didn't work out
same the issues  when i remote to docker and my ubuntu serve
2、lldb and debug：it cannot hit the breakpoint in debug panel，just skip them. however i am sure json files dont have any problem, for the projects come form old ones passed debugging，it can hit breakpoint before system update. what's more,lldb is allright when using it alone in command line
3、python file：when i double click the errors and warings in problems lists，it alert that cannot open the python file，and cant position the cursor to the right line
4、ssh remote serve crush in strange error occasionally. trouble ssh to docker and linux serve

**Comment by AndreaElijha** [comment]
all this was not solved after tried to reinstall vscode many times......

**Comment by mjbvz** [comment]
Please only include one problem issue

File the problems 1 and against the c++ extension. File 3 against the python extension python
