### ISSUE TITLE
[Snap] Opening external links does not work, results in high cpu utilization

### ISSUE THREAD

**Issue by muhammetsait** [microsoft/vscode#82430]
Trying to open external links does not launch the web browser, instead it seems that an infinite number of kde-open5 instances are being spawned and killed which results in very high CPU utilization.

This issue affects versions 1.39.1 and 1.40 Insiders installed from snap store. The `.tar.gz` version works fine.

OS Info:

```
Kernel: 5.3.5-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.16.5 Distro: Manjaro Linux
```

Affected Code versions:
```
$snap list
Name           Version   Rev   Tracking  Publisher   Notes
code           88f15d17  17    stable    vscode✓     classic
code-insiders  72bc289d  273   stable    vscode✓     classic
core           16-2.42   7917  stable    canonical✓  core


Version: 1.40.0-insider
Commit: 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb
Date: 2019-10-11T05:31:05.355Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.5-1-MANJARO snap

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.5-1-MANJARO snap
```

**Comment by joaomoreno** [comment]
Might be related to Manjaro...

I'm using the snap package on Ubuntu and this just works.

Can you check what process is causing the high CPU?

**Comment by muhammetsait** [comment]
Yeah could be related to the distro or Desktop Environment... it seems that after clicking a link (multiple times) several instances of `kde-open5` processes are running and the cpu is utilized to 100%. 

Trying to kill those doesn't work; most of them can be killed but then there are a few that keep "changing" their ID, which I believe means they are dying and new ones are re-spawned indefinitely. I have to restart the machine to get of them all.

I am not sure how can I collect more info to track what's going on exactly.. if there's anything I can do I'd be happy to help.

**Comment by joaomoreno** [comment]
Do other snap packages open URLs without issues?

**Comment by alok1111** [comment]
I don't use VS Code, but for me Slack acts the same. Created bug report [here](https://bugs.kde.org/show_bug.cgi?id=412965).

**Comment by muhammetsait** [comment]
Oh I didn't test that ! I didn't have any other snaps :confused: Anyway, turns out that other packages also had the same problem.

After some digging I managed to solve it: I needed to install `xdg-desktop-portal` and `xdg-desktop-portal-kde` packages. Now it works fine.
