### ISSUE TITLE
Make it easier to download early insiders version

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#82434]
Last insiders made JS and TS programming impossible (as per #82381), and I couldn't find anywhere to download an earlier vscode insiders version (that was at least workable).

Have a page with at least past 3 insiders releases, since the page https://code.visualstudio.com/insiders/ always force you to download the latest defective one. Add a link "earlier builds" to that page or mention somewhere that you are able to do this, since it's isn't clear which commit to the masters triggered the insiders build (I know there's a new one near 3 AM for me every day on working days)

**Comment by joaomoreno** [comment]
URL Template: `https://update.code.visualstudio.com/VERSION-insider/PLATFORM/insider`

Available platforms:

- `win32-x64`
- `win32`
- `win32-archive-x64`
- `win32-archive`
- `win32-x64-user`
- `win32-user`
- `linux-x64`
- `linux-deb-x64`
- `linux-rpm-x64`
- `darwin`

Example: `https://update.code.visualstudio.com/1.39.0-insider/win32-x64/insider`

**Comment by ratatoeey** [comment]
https://github.com/microsoft/vscode/issues/82434#issuecomment-541579147 does not work for what I want to do.
