### ISSUE TITLE
Automatic update even though background update unchecked and Update mode set to manual

### ISSUE THREAD

**Issue by MagTun** [microsoft/vscode#82433]
Issue Type: <b>Bug</b>

I would like to stay on VS Code  1.38.1 until some bugs in 1.39 are fixed. 
I have unchecked "background update " and set "Update mode" to manual and then I reinstall VSCode 1.38.1. The install is successful, until I close VSCode et reopen it : then I am back on VSCode 1.39. 

---

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
project-manager|ale|10.8.0
All-Autocomplete|Ati|0.0.20
replacerules|bhu|0.3.1
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.31.0
xml|Dot|2.5.0
vscode-install-vsix|fab|1.4.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
macros|ged|1.2.1
gc-excelviewer|Gra|2.1.32
beautify|Hoo|1.5.0
vscode-favorites|how|1.4.0
reg|ion|1.0.1
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
powershell|ms-|2019.9.0
debugger-for-chrome|msj|4.12.0
codemap|ole|1.10.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
vscode-autohotkey|sle|0.2.2
local-history|xyz|1.7.0

</details>

**Comment by joaomoreno** [comment]
Is it possible that the update was downloaded and applied *before* you changed the setting?

**Comment by MagTun** [comment]
Yes, that's what happened. I looked for the folder where the updates are downloaded so I could delete it but I couldn't find it . It would be great to purge the update folder when the update settings is set to manual.

**Comment by joaomoreno** [comment]
Got it. Closing this for now. Thanks!
