### ISSUE TITLE
Installing updates disables --extension-dir property until restart

### ISSUE THREAD

**Issue by KytoDragon** [microsoft/vscode#82442]
I use the "--extensions-dir" option to relocate the extension folder to "%appdata%\.vscode", but every time I install an update all my extensions will be gone from the extensions pane and the program creates a new ".vscode" subfolder in my user folder. When I close and restart VS Code after the update the extensions will be back to normal, I just have to delete the newly created ".vscode" folder.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Relocate the ".vscode" folder.
2. Open VS Code via a shortcut that passes the "--extensions-dir" parameter with the new location.
3. Install an update.
4. Notice that a new ".vscode" folder was created and that all extensions are missing until the next restart.

**Comment by arsari** [comment]
After updating to v1.39.1 all the extensions were disabled. I enable then again but when I close the program and open it again all the extensions are disabled again.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/75241
