### ISSUE TITLE
Variadic Expansion operator ... causes incorrect syntax highlight

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode#82441]
When using the ... operator after a variadic parameter to expand it, for example:

`
template <typename... Cs>
struct incorrect
{
        static const int value{std::is_same_v<int, Cs...>};
};
`

Here "Cs..." will not be correctly highlighted unless you insert a space before ...

This space is reverted however upon formatting the document with Clang-format.

It should not matter whether there is a space between a template parameter at point-of-use and the ... variadic expansion operator.

**Comment by alexr00** [comment]
I cannot reproduce. Does this reproduce if you disable all extensions?
