### ISSUE TITLE
文件展示异常

### ISSUE THREAD

**Issue by chenzuoli** [microsoft/vscode#82447]
Issue Type: <b>Bug</b>

我用hexo项目在mac terminal在项目下创建了一个文件，但是在vs code中没有立刻显示出来，需要退出vs code才能显示，这是为什么？

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
javadebugger|don|0.1.5
prettier-vscode|esb|2.3.0
javac-linter|fau|1.3.1
vscode-javac|geo|0.2.27
solidity|Jua|0.0.64
markdown-formatter|mer|0.7.5
evermonkey|mic|2.4.5
python|ms-|2019.10.41019
Go|ms-|0.11.7
java|red|0.50.0
markdown-preview-enhanced|shd|0.4.3
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
markdown-all-in-one|yzh|2.5.1
swig-tpl|zha|0.0.6

</details>

![image](https://user-images.githubusercontent.com/28354442/66710383-af6e2d00-eda9-11e9-9c2d-f533071f181a.png)
![image](https://user-images.githubusercontent.com/28354442/66710387-c1e86680-eda9-11e9-8e59-4b5a59bfbf7c.png)

**Comment by zwuis** [comment]
@chenzuoli please use English.

There is a REFRESH buttom.
You can click it.
