### ISSUE TITLE
Is there a quick way to jump into JS source code from TS?

### ISSUE THREAD

**Issue by frogcjn** [Microsoft/vscode#8244]
Intellisense allows us using command + click to jump into definition (*.d.ts) or other typescript source files,
but some module needs us to quick view its javascript source file. like 'express' module or 'mongoose' module.

Is there is a quick way to jump into /node_modules/express/index.js or /node_module/express/mongoose/index.js from symbols in TypeScript source file?

**Comment by dbaeumer** [comment]
I am not aware of one. I tried to do a import and then use navigation but that didn't work. Will move to the TS team since such a smartness has to come from them.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#9413
