### ISSUE TITLE
Opening files through vscode:// URL handling broke in 1.39

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#82443]
Opening files through URL handling with a URL such as `vscode://file/path/to/file:123` stopped working in 1.39. I rolled back to 1.38 and confirmed that it works as expected in 1.38.

- VSCode Version: 1.39.1
- OS Version: macOS 10.14.5

Steps to Reproduce:

1. Visit a URL such as `vscode://file/path/to/file:123` in your web browser.
2. Observe that Code opens but it does not open the file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82212
