### ISSUE TITLE
HTML Autocompletion closes the tag by pressing the angle-bracket inside of a tag

### ISSUE THREAD

**Issue by fieteboerner** [microsoft/vscode#82445]
Issue Type: <b>Bug</b>

If a press the closing angle bracket `>` inside of a tag, a closing tag will be inserted into the actual tag. This breaks up the actual valid dom and does not make sense.
(see screenshot)
![Bildschirmfoto von 2019-10-12 23-54-34](https://user-images.githubusercontent.com/8209685/66708159-676ced00-ed4c-11e9-84c3-c41e2a1072c7.png)

What do I expect: When I am inserting the closing angle bracket `>` into a html tag, that the tag does not close the actual tag. At least inside of curly braces `{}` or an angle bracket `>` right after an equal sign `=` (arrow function) should not close the actual tag.

What ist the case why I get to this issue: By developing in svelte, the syntax to handle events is: `<button on:click={() => doSomething(param) }>do something</button>`

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:31:05.355Z)
OS version: Linux x64 5.3.1-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3440)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.37GB (1.65GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
It's a bit of a special as you are in a template language. `{() => doSomething(param) }` is not valid is HTML and `>` is not a valid character in an HTML attribute. The HTML parser if completely off here.
Just saying that after `=` we don't close is hackish. I'd rather not start that. This leads to code that hard to maintain and understand later. We have issue #49210 to allow configuring HTML with template syntax. That way we really understand where to disable auto-close.

The workaround for you is the press `Undo` after `>`. Or disable autoclose: `"html.autoClosingTags": false`
