### ISSUE TITLE
Markdown link on local files with spaces

### ISSUE THREAD

**Issue by alex75it** [microsoft/vscode#82454]
Issue Type: <b>Bug</b>

Hi, 
I noticed a difference in the behavior of links within _spaces_ or "_" in the name.

link 1: ``[Config](<SSH_Config.md>)``  ("_")  
link 2: ``[Config](<SSH Config.md>)``   (" ")  

When I am on the preview of README.md and I click the link 1 it opens in "preview", so I can navigate back and forth like I'm on a website.    
When I click the link 2 it opens both the "code" view and "preview" of "SSH Config.md".  
Link 2 should have the same correct behavior of link 1.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.5
eml|lei|0.3.2
Kotlin|mat|1.7.0
terraform|mau|1.4.0
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
remote-wsl|ms-|0.39.9
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vscode-spring-boot|Piv|1.11.0
java|red|0.50.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
