### ISSUE TITLE
Preview tab does not have a stable position

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8245]
#7854

- VSCode Version: insiders
- OS Version: os x

Steps to Reproduce:

1. Have a regular and a preview tab
2. Let the active be a regular tab and click on a new file
3. Notice the preview tab and regular tab change positions in the tab header view
4. I would expect that my stable tab is left at the same position and that the preview tab stays on the same position and becomes active

![tabposition](https://cloud.githubusercontent.com/assets/1926584/16407421/e6b5eaea-3d13-11e6-9a89-8f8307c77f78.gif)

**Comment by bpasero** [comment]
@isidorn did you configure to open new tabs to the left maybe?

**Comment by isidorn** [comment]
@bpasero I did, but only after filing this bug. So no.

**Comment by bpasero** [comment]
Weird, can easily reproduce with 2 tabs already.
