### ISSUE TITLE
Red Heart Emoji greys out

### ISSUE THREAD

**Issue by Gizmo-Rishab** [microsoft/vscode#82458]
Issue Type: <b>Bug</b>

##Description
Upon typing a red heart in vs code , it greys out! :heart: is expected and the image below pops up. :(
![image](https://user-images.githubusercontent.com/29125087/67159091-a5c26780-f35d-11e9-8603-aa382c94c425.png)

##Steps to obtain error
1. Copy a heart emoji on any document using vs code
2. It looks like the image linked above

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18932

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
npm-intellisense|chr|1.3.0
bracket-pair-colorizer-2|Coe|0.0.28
vscode-babel-coloring|dza|0.0.4
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
material-icon-theme|PKi|3.9.1
platformio-ide|pla|1.9.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by Gizmo-Rishab** [comment]
Actually it also blacks out in the browser.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
