### ISSUE TITLE
Sometimes expand is not working on html files

### ISSUE THREAD

**Issue by emirhanengn** [microsoft/vscode#82456]
- VSCode Version: 1.39.1
- OS Version: Windows 10

Hello! When i get new update, exand started to doesn't work on html files.

![issue](https://user-images.githubusercontent.com/21215832/66716745-0c81d700-edda-11e9-89b4-411faa7d0e37.gif)

**Comment by aeschli** [comment]
Do I get this right:
- You start with 'category.html' and see the folding markers
- Switch to `about.html`and see no markers
- Switch again to 'category.html' and see no markers as well?
Can you try to run without any extension (close all windows and start code with `code --diable-extensions`)?
Also, can you set `"html.trace.server": "messages"` and look at the `Output` view, `HTML Language Server` tab while you toggle the editors?

**Comment by emirhanengn** [comment]
> Do I get this right:
> 
> * You start with `category.html` and see the folding markers
> * Switch to `about.html`and see no markers
> * Switch again to `category.html` and see no markers as well?
>   Can you try to run without any extension (close all windows and start code with `code --diable-extensions`)?
>   Also, can you set `"html.trace.server": "messages"` and look at the `Output` view, `HTML Language Server` tab while you toggle the editors?

**Comment by emirhanengn** [comment]
> Do I get this right:
> 
> * You start with `category.html` and see the folding markers
> * Switch to `about.html`and see no markers
> * Switch again to `category.html` and see no markers as well?
>   Can you try to run without any extension (close all windows and start code with `code --diable-extensions`)?
>   Also, can you set `"html.trace.server": "messages"` and look at the `Output` view, `HTML Language Server` tab while you toggle the editors?

Yes you're right, when i try to close all extension, it still doesn't work

**Comment by aeschli** [comment]
Also, can you set `"html.trace.server": "messages"` and look at the `Output view, HTML Language Server tab` while you toggle the editors?
![image](https://user-images.githubusercontent.com/6461412/67192287-9988e980-f3f3-11e9-8a58-fd30854132ae.png)

You should see the folding ranges request every time you switch between the html editors.

**Comment by emirhanengn** [comment]
I was close the VS code and after that i opened it. It started to working... Thank you for help 👍
