### ISSUE TITLE
Tab should move focus from search to replace box

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8246]
#8184

1. Open search viewlet, open replace box, focus the input box
2. Press tab - notice how focus is moved to the actions inside the input, the focus should move to the replace box - same as we do it in the find widget

**Comment by sandy081** [comment]
Tab, in general, should navigate as per the flow of dom elements position. The way tabbing behaves in Find widget looks jumpy to me.

I like that navigation in Search view (was same even before) - When all input boxes are open, up or down arrow navigates among them. Tabbing navigates as per dom elements

**Comment by isidorn** [comment]
I think you will get a lot of users complaing about this - as I know they were complaing about tab behavior in find widget so Alex had to change it.
But time will tell and then later you can reopen this one

**Comment by sandy081** [comment]
> But time will tell and then later you can reopen this one

Sure, always welcome for feedback :)
