### ISSUE TITLE
update fails everyday

### ISSUE THREAD

**Issue by johnykes** [microsoft/vscode#82465]
Issue Type: <b>Bug</b>

The software is trying to get the update everyday but fails all the time...

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.88GB (13.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
python|ms-|2019.10.41019
powershell|ms-|2019.9.0
vetur|oct|0.22.4

</details>

**Comment by navneethc** [comment]
Are you getting an error window which has Abort/Retry/Ingore options? I came here to report an update issue as well and thought that this might be related.

I'm working on Windows 10.

VS Code: I think I had the latest update until today. Please read further.

Extensions:
Python
Remote WSL
Julia
Rust (in WSL)

I noticed that there was an update and let it install and restart. During that process, I got the window mentioned above. It asked me to close other applications which were supposedly using some file (never seen this error before, and no I didn't have any files open). Tried retry a couple of times, didn't work. So aborted the process.

Then I checked if there were any other VSCode processes running. Noticed one background process and killed it. When I tried to open VSCode again, I got the error shown below. I even tried restarting my laptop to no avail.

Now, I can't open VSCode to give more information, even if I want to.


![image](https://user-images.githubusercontent.com/4192839/66719873-01976880-ee13-11e9-8eb0-f1acc6df9253.png)

**Comment by johnykes** [comment]
Yeah, it has the Abort/Retry/Ingore options, but that's all, vs code is working, but it's always prompting me to update it and this is annoying.

**Comment by navneethc** [comment]
So, it's not just me. Thanks for confirming.

**Comment by joaomoreno** [comment]
@johnykes Can you show me a screenshot of the error?

**Comment by johnykes** [comment]
![image](https://user-images.githubusercontent.com/48965850/67152064-4a01cb00-f2d8-11e9-8f2c-a67dcf0618ff.png)
