### ISSUE TITLE
Auto complete sometimes eats the rest of the line when auto-completing

### ISSUE THREAD

**Issue by cmcarey** [microsoft/vscode#82462]
# System information

**Version** 1.40.0-insider (user setup)
**Commit** 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb
**Date** 2019-10-11T05:44:05.506Z
**Electron** 6.0.12
**Chrome** 76.0.3809.146
**Node.js** 12.4.0
**V8** 7.6.303.31-electron.0
**OS** Windows_NT x64 10.0.18362

**Does this issue occur when all extensions are disabled?** Yes

---

**NOTE** I have since realized this is an editor issue and not a Typescript issue - it happens across every language.

---

# Steps to reproduce

1. Open a new window, set syntax type to typescript
2. Type something on a line (e.g. `// Comment`)
3. Move the cursor to the start of the line and start typing something else
4. Hit tab to auto fill
5. Watch following characters be randomly eaten

# Example

![9bquIbqerL](https://user-images.githubusercontent.com/32423458/66718018-0f2efd00-edd7-11e9-8127-2de132115e9f.gif)

In the above recording, observe how on the first line it eats the first few characters of the comment, and on the second line, eats the closing parenthesis.

---

As you can imagine, this is something of an irritating bug, as parts of lines will randomly be deleted as I'm working on them.

**Comment by GeorgeIpsum** [comment]
This is apparently fixed in [d952f6b](https://github.com/microsoft/vscode/commit/d952f6bfc1083ce5a913e07dfc4b8895ef0589ef), which should be out in the Insiders build on Monday

**Comment by cmcarey** [comment]
> 
> 
> This is apparently fixed in [`d952f6b`](https://github.com/microsoft/vscode/commit/d952f6bfc1083ce5a913e07dfc4b8895ef0589ef), which should be out in the Insiders build on Monday

Fantastic, thank you.

Out of curiosity what is the Insiders build cycle like?  Releases every week?

**Comment by GeorgeIpsum** [comment]
I believe (someone please correct me if I'm wrong!) that there are daily builds for Insiders on weekdays
