### ISSUE TITLE
[Insiders] Autocomplete removing brackets

### ISSUE THREAD

**Issue by lonkaars** [microsoft/vscode#82466]
# Autocomplete removing brackets

> OS Version: Windows 10, 1903, Build 18362.418
> VSCode Version: 1.40.0-insider, 72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, x64

I don't know for sure if this is a bug or a feature, but it's annoying and as far as I know, there isn't a setting for it. What's happening is that when I use autocomplete inside of brackets, it removes the closing bracket.

Here's a video showcasing the bug: https://youtu.be/c1KWqnXqgOg

This only occurs when you start typing the first few characters of an autocomplete suggestion.

**Comment by JoelNieto** [comment]
> Version: 1.40.0-insider
> OS: Darwin x64 19.0.0

Same thing

**Comment by GeorgeIpsum** [comment]
This should be fixed in [`d952f6b`](https://github.com/microsoft/vscode/commit/d952f6bfc1083ce5a913e07dfc4b8895ef0589ef), and will probably be out for Monday's Insiders build

**Comment by charlex** [comment]
@GeorgeIpsum Thank you for that update. I too am experiencing this.
