### ISSUE TITLE
Unable to shift focus back to the editor

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#82461]
The snippet below in my `keyboards.json` is **not** working for me. When I'm in the terminal, and I press `ctrl+x e` the focus remains in the terminal. 

```
   {   "key": "ctrl+x e", 
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "terminalFocus" 
    },
```

```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by Tyriar** [comment]
Chords historically don't work in the terminal, they should work in the insiders build though, try it out at https://code.visualstudio.com/insiders and see the new `terminal.integrated.allowChords` setting
