### ISSUE TITLE
terminal shows abnormal

### ISSUE THREAD

**Issue by shuihan03** [microsoft/vscode#82475]
Issue Type: <b>Feature Request</b>

when debug vue program ,the terminal sometimes shows abnormal,not show the words but show the square with green or blue.
![image](https://user-images.githubusercontent.com/15643529/66728333-bd3db400-ee76-11e9-83aa-9eb7a9fa97f9.png)

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

**Comment by fedorg** [comment]
Duplicate #82543

**Comment by Tyriar** [comment]
Please try out the steps outlined in https://github.com/microsoft/vscode/wiki/Terminal-Issues#rendering-problems to help diagnose the problem.
