### ISSUE TITLE
In VsCode 1.39 

### ISSUE THREAD

**Issue by rajb2m19** [microsoft/vscode#82478]
Hello Team!

May I Know How we can control our source code through TFS. Beacause We are not find the updated list of change in our Project Files.
![Display_VsCode1 39](https://user-images.githubusercontent.com/44677785/66730423-43ee9300-ee6f-11e9-94dc-343b16c93819.PNG)

Kindly guide us.

Thanks in Advance.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82203

Fix is coming this week.
