### ISSUE TITLE
API Set/Get active launch configuration

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#82477]
An API to get / set the current (active) launch configuration as seen on the debug panel:

![image](https://user-images.githubusercontent.com/966863/66729182-a466db80-ee41-11e9-8b84-57aacf6e8efa.png)

**Comment by isidorn** [comment]
This is a fair feature request, however it is not currently on our plan thus assigning to backlog.
fyi @weinand

**Comment by weinand** [comment]
@GordonSmith please add your use case to #77138
