### ISSUE TITLE
Theme cannot be changed in vscode for linux

### ISSUE THREAD

**Issue by dhqdqk** [microsoft/vscode#82479]
- VSCode Version: AMD64
- OS Version:Linux manjaro AMD64

Steps to Reproduce:

1. In vscode for linux, theme cannot be chaned by methd of "File/settings/apperace/color-theme".
![2019-10-14_13-08](https://user-images.githubusercontent.com/11811250/66730525-f11fd600-ee84-11e9-8a4d-ac580bf729dd.png)
![2019-10-14_13-09](https://user-images.githubusercontent.com/11811250/66730528-f2510300-ee84-11e9-82de-fa8bad930b14.png)
2.But, theme can be changed by method of "ctrl+k then ctrl+t".
![2019-10-14_13-09_1](https://user-images.githubusercontent.com/11811250/66730526-f1b86c80-ee84-11e9-8a1c-aa504bd3fa98.png)

3.Another problem about the theme "solaried light", in terminal the output's color is too light to be see clearly, it should be more black. 
![2019-10-14_13-10](https://user-images.githubusercontent.com/11811250/66730529-f2510300-ee84-11e9-9145-2f279842d189.png)

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
@dhqdqk Do you maybe have the color theme also set in the workspace settings?

**Comment by dhqdqk** [comment]
> @dhqdqk Do you maybe have the color theme also set in the workspace settings?

as you think, the issue is solved.
