### ISSUE TITLE
Using the keyboard Alt shortcuts for menus and the arrow keys seems inconsistent

### ISSUE THREAD

**Issue by StingyJack** [microsoft/vscode#82470]
Issue Type: <b>Bug</b>

I wanted to open the Settings in VSC. I used (Alt+F, P) and "Preferences" was selected and the flyout menu for it opened. I then hit the right arrow key to move the selection and instead of moving the selection, the Edit menu was activated.   If I instead hit the down arrow twice, the selection moves to the flyout menu and starts moving down it

I'm not sure if this is a problem with the selection by keyboard, or that the selected item isn't actually what is selected.  Its not that big of a problem but it may end up being frustrating  after a while.

VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.55GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
vscode-solution-explorer|fer|0.3.5
beautify|Hoo|1.5.0
vscode-docker|ms-|0.8.1
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vs-keybindings|ms-|0.2.0
team|ms-|1.149.2

(1 theme extensions excluded)

</details>

**Comment by StingyJack** [comment]
@sbatten - I'd expect an explanation for the closure, but the activity after it doesnt look like closing it was intended. Can you provide some info on this topic?

**Comment by sbatten** [comment]
@StingyJack it's closed because I fixed the issue in commit https://github.com/microsoft/vscode/commit/2c535a36e9d6427261b537da0859dafb6f686357

**Comment by StingyJack** [comment]
As someone who probably reads a lot of things for a living, can you tell me which of these two descriptions is clearer?

- Visual Studio 2019 on Windows 2019
- windows-2019

If you didn't consider "clearer for what purpose", the purpose is to build an application with VS 2019. 

It's also probably important to take into context that the other choices in the second items list all mention a version of visual studio.

If you said the first one was clearer, congratulations! Unfortunately this means your commit has codified someone else's stupid decision, and users may rag on this point every time they now have to check a docs page for something that was immediately clear before. 

Hopefully it's not too late. If you can, please withdraw the commit at least until the issue I already have open with the target team is addressed.
