### ISSUE TITLE
snippets error

### ISSUE THREAD

**Issue by kotot** [microsoft/vscode#82473]
- VSCode Version: 1.40.0-insider
- OS Version: MAC 10.15 

Steps to Reproduce:

[屏幕录制2019-10-14上午11.00.16.mov.zip](https://github.com/microsoft/vscode/files/3722787/2019-10-14.11.00.16.mov.zip)

Does this issue occur when all extensions are disabled?: NO, BUT SAME

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
