### ISSUE TITLE
Bugs in VSCode Python Jupyter Notebook when using Ctrl+Z

### ISSUE THREAD

**Issue by Toni-Chan** [microsoft/vscode#82474]
Issue Type: <b>Bug</b>

When I try to undo some typing work, the results can be unexpected and can't describe the exact output. It may reserve the currently newly typed characters and not undo them, but replacing in-line character by character....

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0
Remote OS version: Linux x64 5.0.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ***.***.***.***|
|OS|Linux x64 5.0.0-29-generic|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 1596)|
|Memory (System)|15.62GB (1.21GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.31.0
rainbow-csv|mec|1.3.1
vscode-language-pack-zh-hans|MS-|1.39.3
python|ms-|2019.10.41019
vscode-language-pack-zh-hans|MS-|1.39.3
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1

</details>

**Comment by roblourens** [comment]
Please file this on the vscode python extension's repo: https://github.com/microsoft/vscode-python
