### ISSUE TITLE
Ability to more effectively run unit tests for extension development

### ISSUE THREAD

**Issue by Almenon** [microsoft/vscode#82471]
The vscode-test package allows you to run integration tests where you launch the tests through vscode and a instance of vscode opens up. But if I want to do normal unit tests against code that has even a single reference to vscode I am not able to do so due to https://github.com/Microsoft/vscode/issues/6586. There are several workarounds:

* stick with integration tests (slow, not usable with test explorer UI, and not really usable with command line either†)
* _completely_ extract out your logic to not reference vscode at all. Easier said than done. See https://github.com/Microsoft/vscode-wordcount/issues/5#issuecomment-171050759
* mock require to return a mocked vscode (see https://github.com/rokucommunity/vscode-brightscript-language/blob/master/src/BrightScriptCommands.spec.ts)

None of these workarounds are ideal. As @georgejecook pointed out "it seems most people (judging by github repos) simply don’t do a lot of testing". Making it easier to write unit tests would encourage extension authors to do more testing, thereby decreasing bugs and making users and authors happier.

† tests ran from command line can't be run while vscode is opened :(

**Comment by Almenon** [comment]
To clarify this is a feature request. Thought it would get labeled automatically 🤔

**Comment by octref** [comment]
I think you should have some layering logic so that unit tests can run without access to vscode module. For example: https://github.com/microsoft/vscode-wordcount/issues/5#issuecomment-171050759
