### ISSUE TITLE
Hard to move split bar

### ISSUE THREAD

**Issue by mooreaa** [microsoft/vscode#82480]
Issue Type: <b>Bug</b>

When using the split view, it is hard to get the handle on the 1px width bar to change/adjust the width of the split view. The cursor ends up accidently creating debug points or jumps on the doc-nav view. 

Would be nice to make it easier to change the split view size.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.2.0

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/68962
