### ISSUE TITLE
Incorrect keyboard input when using "AltGr" key.

### ISSUE THREAD

**Issue by willemavjc** [microsoft/vscode#82489]
- VSCode Version: 1.39.1
- OS Version: Microsoft Windows (Pro) Version 1903 (OS Build 10.18362.418)
- PowerShell Version: 5.1

Steps to Reproduce:

1. Open VSCode
2. Open a Terminal
3. Make keyboard keys input combination of "AltGr + 2 then Space" or "AltGr + 7 then Space"
4. You get the standard key (unexpected) plus the AltGr key (expected)

This happens on an AZERTY keyboard (a Surface Type Cover). I am not able to confirm if this happens on QWERTY too.

On AZERTY keyboards, the keys "2" and "7" consist in 3 characters:
- Keyboard key "2": é (standard) + 2 (shift) + ~ (AltGr+Space)
- Keyboard key "7": è (standard) + 7 (shift) + ` (AltGr+Space)

Note: **This dysfunction only affects PowerShell through VSCode. Code workspace is not affected. And native PowerShell also behaves perfectly.**

These keys are quite intensively used. Any solution would be appreciated.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by willemavjc** [comment]
**Was able to test with VSCode 1.38.1: No issue.

Some bug brought by 1.39.x?**

**Comment by willemavjc** [comment]
Added a few information in the issue description. (Bold)

**Comment by Tyriar** [comment]
What language/locale are you using?

**Comment by willemavjc** [comment]
From Windows Settings / Time & Language / Language:
- Windows display language : English (United States)
- Preferred languages : English (United States)

In Preferred languages sub-menu : 
- Keyboards : French / AZERTY

Is that what you were looking for?

By the way, I was able to observe the same issue on others computers of the company (with VSCode 1.38.1) with the following settings:

From Windows Settings / Time & Language / Language:
- Windows display language : France
- Preferred languages : French

In Preferred languages sub-menu : 
- Keyboards : French / AZERTY

Note: Either git-bash via VSCode or powershell via VSCode suffer the same thing (and only occur via VSCode)

**Comment by Tyriar** [comment]
Ok I reproduced the problem. Expected:

- 2: é
- 7: è
- altgr+2: (nothing)
- altgr+7: (nothing)
- altgr+2, space: ~
- altgr+7, space: `

Actual:

- 2: é
- 7: è
- altgr+2: é
- altgr+7: è
- altgr+2, space: é~
- altgr+7, space: è`

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2479

**Comment by utybo** [comment]
I found a temporary workaround (works on Windows at least): use Ctrl+Alt instead of AltGr. Far from practical but hey, it's something.

**Comment by utybo** [comment]
The issue is either not from xterm.js or has been fixed upstream, because I can't replicate this issue using xterm.js's test webserver with the latest sources

**Comment by Tyriar** [comment]
@utybo oh really? VS Code insiders is basically on xterm.js master right now and we haven't touched the IME/input code for a while... It could be related to Electron? 🤔

**Comment by utybo** [comment]
Possibly. In case someone with a QWERTY keyboard wants to try, the right Alt key should be considered as the AltGr key when using AZERTY keymaps, so that could be used for devs debugging this maybe? (AltGr (or Right Alt) + 2 then Space should give ~)

**Comment by willemavjc** [comment]
@Tyriar I know you're probably busy with a million issues but... Any update on that? It's still troublesome :(

**Comment by Tyriar** [comment]
@willemavjc no update, fixing it is one of the long standing todo items to switch over to using the `input` event (primarily, will likely still need keydown). I doubt I'll have time for it in the foreseeable future.

**Comment by jarcos** [comment]
I have a similar issue using Spanish Keyboard (QWERTY distribution). When I try to write `@`, using Alt-gr + 2, or any Alt-gr + key combination, I have nothing, but an empty space or some tabulations...

**Comment by rzhao271** [comment]
Verified with https://github.com/microsoft/vscode/issues/82489#issuecomment-543258250

**Comment by MrLuje** [comment]
Looks like it is still not good for me with the 1.60 version

Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z (2 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

I'm still getting the exact "actual" result from https://github.com/microsoft/vscode/issues/82489#issuecomment-543258250

**Comment by rzhao271** [comment]
Are you using the French/AZERTY keyboard to test, and are you on a PowerShell 7 or Git Bash terminal?
I'm unable to reproduce the issue using that build.

**Comment by willemavjc** [comment]
I can confirm what sees @MrLuje and what was explained by @Tyriar 

- `2` gives `é`
- `AltGr` + `2` gives `é`
- `AltGr` + `2` + `Space` gives `é~`

Version: 1.60.0 (system setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

PowerShell here is 7.1.4.

**Comment by willemavjc** [comment]
@Tyriar Please reopen the issue :)

**Comment by MrLuje** [comment]
> Are you using the French/AZERTY keyboard to test, and are you on a PowerShell 7 or Git Bash terminal?
> I'm unable to reproduce the issue using that build.

Yes, french keyboard & language ( (Get-Culture).KeyboardLayoutID => 1036 if it helps)
Tested with powershell 7.1, regular CMD & git bash; same output on all

While typing this, I couldn't reproduce the issue for some time and it went back.
It looks like it is related to "NumLock" key being active or not.

While active, I reproduce the issue (I have a numeric keyboard on my laptop so it's active most of the time)
While inactive, I get the proper output 👍 

Hope it helps fixing this issue

**Comment by willemavjc** [comment]
> It looks like it is related to "NumLock" key being active or not.

Hmm... No dedicated numpad on my hand so no numlock key and still can reproduce it.

**Comment by MrLuje** [comment]
@rzhao271 Is there any way to record the sequence of strokes (received by vscode) on our side ?
Maybe an eventhandler from vscode Developer Tools ?

**Comment by Tyriar** [comment]
I believe this is fixed upstream with a follow up PR but we didn't end up updating to it, pushing to September.

**Comment by Tyriar** [comment]
Relevant PRs: https://github.com/xtermjs/xterm.js/pull/3430, https://github.com/xtermjs/xterm.js/pull/3432, https://github.com/xtermjs/xterm.js/pull/3437

**Comment by willemavjc** [comment]
Eager to see that :)

**Comment by rzhao271** [comment]
Hi @willemavjc and @MrLuje, has the issue been fixed for either of you?
