### ISSUE TITLE
remote-monitoring-services-dotnet-master\storage-adapter running error

### ISSUE THREAD

**Issue by pw007** [microsoft/vscode#82482]
Issue Type: <b>Bug</b>

when I Ran the storage adapter microservice in Visual Studio Code.  VS shows there are some projects miss loading error.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-6800K APU with Radeon(tm) HD Graphics   (4 x 4120)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.20GB (3.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.16.0
azure-account|ms-|0.8.4
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
azure-iot-edge|vsc|1.17.0
azure-iot-toolkit|vsc|2.11.0
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.2.27
vscode-iot-device-cube|vsc|0.1.1
vscode-iot-workbench|vsc|0.10.15

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

How is this related to VS Code? Is this an extension?

**Comment by pw007** [comment]
I try this project: https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-create-simulated-device
When I ran the storage adaptor microservice, VS prompts:
Exception has occurred: CLR/Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Exceptions.InvalidConfigurationException
“Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Exceptions.InvalidConfigurationException”类型的未经处理的异常在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.dll 中发生 : 'Environment variables not found: , PCS_AAD_APPID'
在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Runtime.ConfigData.ProcessMandatoryPlaceholders(String& value) 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Runtime\ConfigData.cs 中: 第 160 行 在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Runtime.ConfigData.ReplaceEnvironmentVariables(String& value, String defaultValue) 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Runtime\ConfigData.cs 中: 第 123 行 在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Runtime.ConfigData.GetEnvironmentVariable(String key, String defaultValue) 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Runtime\ConfigData.cs 中: 第 115 行 在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Runtime.ConfigData.SetUpKeyVault() 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Runtime\ConfigData.cs 中: 第 82 行 在 Microsoft.Azure.IoTSolutions.StorageAdapter.Services.Runtime.ConfigData..ctor(ILogger logger) 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Runtime\ConfigData.cs 中: 第 45 行 在 Microsoft.Azure.IoTSolutions.StorageAdapter.WebService.Program.Main(String[] args) 在 C:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService\Program.cs 中: 第 16 行
I don’t know how to fix it. So I asked for help.

Brgs,

Peter Wen


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Johannes Rieken <notifications@github.com>
发送时间: Monday, October 14, 2019 3:04:49 PM
收件人: microsoft/vscode <vscode@noreply.github.com>
抄送: pw007 <wdy_sw@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vscode] remote-monitoring-services-dotnet-master\storage-adapter running error (#82482)


/needsMoreInfo

How is this related to VS Code? Is this an extension?

―

**Comment by jrieken** [comment]
This is not the right place to find an answer.
