### ISSUE TITLE
scrolling lags

### ISSUE THREAD

**Issue by kkonevets** [microsoft/vscode#82488]
Issue Type: <b>Performance Issue</b>

When scrolling source code files lags a little bit, it's annoying

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (2.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    82	  8292	code main
    0	    66	  8294	   gpu-process
    4	   311	  8300	   window (lib.rs — kribrum)
    0	   147	  8340	     extensionHost
    0	    16	  8381	       /Users/guyos/.vscode/extensions/ms-vscode.cpptools-0.25.1/bin/Microsoft.VSCode.CPP.Extension.darwin
    1	   393	  8446	       /Users/guyos/.vscode/extensions/ms-python.python-2019.10.41019/languageServer.0.4.64/Microsoft.Python.LanguageServer
    0	    66	 10983	       /Users/guyos/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rls
    0	     0	  8341	     /bin/bash -l
    0	     0	  8441	       ssh c8l1
    0	    33	  8377	     watcherService
    0	    33	  8395	     searchService
    0	     0	  8762	     /bin/bash -l
    0	     0	  8887	     /bin/bash -l
    0	     0	  8923	       ssh video001
    0	    82	  8413	   shared-process
    0	     0	 11155	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 11138	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (lib.rs — kribrum)
|    Folder (kribrum): 1695 files
|      File types: json(228) timestamp(143) d(122) bin(115) rmeta(98) lock(38)
|                  plist(24) rlib(17) py(13) ll(13)
|      Conf files: cmake(11) makefile(1) launch.json(1) settings.json(1)
|      Launch Configs: lldb(8) cppdbg;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
rust|rus|0.6.3
sync-rsync|vsc|0.36.0

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by arnelenero** [comment]
I use the same version of VSCode 1.39.1 on MacOS Mojave 10.14.6, and not only the scrolling is lagging, but pretty much everything I do with the UI.  

I observe no such lag with latest Insiders version.

**Comment by alexandrudima** [comment]
@arnelenero I think you might suffer from a different issue than the OP (different operating system versions, macOS Mojave vs macOS Catalina).

Can you please follow some of the guidance in https://github.com/microsoft/vscode/wiki/Performance-Issues and create a separate issue?

**Comment by alexandrudima** [comment]
@kkonevets When you say that scrolling lags, do you mean that scrolling with the touchpad is slow/janky? Is scrolling with an external mouse with a scroll wheel or by click & dragging the scrollbar also slow/janky for you?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kkonevets** [comment]
@alexandrudima I had the same problem on both macOS Mojave and macOS Catalina
