### ISSUE TITLE
AI智能提示代码回车导致删除后面的内容

### ISSUE THREAD

**Issue by CN-Yi** [microsoft/vscode#82492]
We have written the needed data into your clipboard because it was too large to send. Please paste.
我在操作如下：
if()
当在括号里面输入一个有智能提示的操作输入thi这时会出现this等智能提示
但是当我按下回车的时候  就变成了if(this   后面的括号被删除了

**Comment by bdss58** [comment]
maybe you use Monday's Insiders build. this bug has fixed. reference #82466
