### ISSUE TITLE
Indent NPM Scripts

### ISSUE THREAD

**Issue by jornare** [microsoft/vscode#82496]
We have a monorepo frontend with multiple applications, which in turn results in a lot of scripts in package.json.

We love the "npm scripts" panel, but it would be even better if we in some way could arrange the scripts as one application typically has run, build, test, testonce, analyze and maybe even more sub-features.

It seems to be a pattern to name scripts with a colon separator "myapp:run", "myapp:test" and so on.

If the panel could make a tree-like structure of the scripts, based on splitting the names on ":", it would be more readable and easier to find the script you need.

Coloring and/or icons for keywords(like run, test, build) could also provide useful

The result could then be something like:
```
myapp1
        run
        test
        build
myapp2
        run
        test
        build
```

**Comment by egamma** [comment]
@jornare we have just merged a PR that allows to runs scripts from the explorer and I wonder whether this helps your scenario, pls see https://github.com/microsoft/vscode/pull/79960

**Comment by jornare** [comment]
My wife categorize developers into "clickers" and "typers", and she puts me into the latter category because i mostly use the keyboard. However, navigating the IDE I prefer using the mouse without having to type commands that I need to remember.

Also, being a consultant, I tend to work in environments where teams change. Showing someone the list of scripts is a lot easier than having to document how to use the explorer and what scripts are available there. I know it's not a big deal for most people, but for many developers there are enough other things to learn when they have little experience with the editor, and usually also the language, framework and many other things.

So, the short answer is no.

By the way, thank you very much for making the best editor ever! I love VSCode more than anything I have used before in my 30 years of coding.

**Comment by egamma** [comment]
Still do not really feel how big the pain is in your setup, can you share a screenshot that illustrates the problem? I assume that `myapp1` and `myapp2` are in separate folders and you already get a hierarchy level for that.

There is also another way to run an pick a task using 'Terminal>Run Task...', pls give it a try.

![image](https://user-images.githubusercontent.com/172399/66825866-740b6400-ef4b-11e9-8f3e-e29d4c08807a.png)

BTW, thanks for the kind words.

**Comment by jornare** [comment]
It's not a BIG pain, mostly convenience.

The selected view covers roughly 50% of my scripts, and there are more to come.

![image](https://user-images.githubusercontent.com/1435941/66851090-55709180-ef7a-11e9-9cc9-b9f89b34f3b0.png)
