### ISSUE TITLE
Cmd+D (select multiple search occurences) is not working

### ISSUE THREAD

**Issue by tetsuo** [microsoft/vscode#82493]
- VSCode Version: 1.39.1
- OS Version: macOS Mojave (10.14.6) & macOS Catalina (10.15)

Steps to Reproduce:

1. While another Electron app is opened, cmd+D toggles the developer tools on the other screen 

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by tetsuo** [comment]
It looks like this only happens when another Electron app is running

**Comment by tetsuo** [comment]
I think I found the cause, while another Electron app is opened, cmd+D toggles the developer tools on the other screen :)

**Comment by alexandrudima** [comment]
@tetsuo I am not sure I understand the steps, nor the problem. Can you please break down the step and add more details? What Electron app do you open? Which Electron app has focus when you press cmd+D?

**Comment by tetsuo** [comment]
@alexandrudima 

Hey I am using an Electron application which seems to be adding global shortcuts using electron's [GlobalShortcut API](https://electronjs.org/docs/api/global-shortcut).

Not sure if this is expected, but it looks like they are overriding VScode's own shortcuts.

**Comment by alexandrudima** [comment]
@tetsuo Thank you for following through. 

I think this is expected. If another application "steals" `cmd+D`, then no other running application, including VS Code receives the key combination anymore. 

This is considered unfriendly, so my recommendation is to contact the other Electron application author and ask them for a configuration option to disable their global keybindings...
