### ISSUE TITLE
Auto-import removes everything after the insertion point

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#82491]
Related to  #82466 

- VSCode Version:
Version: 1.40.0-insider (user setup)
Commit: a30e88aca126b9a02414ad79fb3626a5d4dd47f5
Date: 2019-10-14T05:42:51.751Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

- OS Version:
Windows x64 10.0.18362

Steps to Reproduce:

See attached animated gif - as soon as the suggestion is accepted with ENTER key, everything after it is removed.

1. Create new class definition
```
export class Test {
}
```
2. Start defining constructor with a single parameter (notice that VSCode automatically adds closing bracket when you type the open bracket for the constructor and places the cursor inside the brackets)
```
constructor (private x: )
```
3. Start typing the parameter type name and wait for suggestions to show
4. Select something from the suggestion list

What happens:
Instead of ending up with something like this:
```
import { SomeType } from './somewhere';

export class Test {
  constructor(private x: SomeType)
}
```

You end up with this (notice the closing bracket is removed - this happens with everything after the auto-inserted type name)
```import { SomeType } from './somewhere';

export class Test {
  constructor(private x: SomeType
}
```

Does this issue occur when all extensions are disabled?: Yes

Animated gif:

![vscode-auto-import-bug](https://user-images.githubusercontent.com/7610713/66739863-5a4e1c00-ee7a-11e9-85c2-8a29b63bf6ca.gif)

**Comment by jrieken** [comment]
re-triggering insiders for that one

**Comment by JetLua** [comment]
The latest version of insider still has this problem.

![Oct-16-2019 10-22-31](https://user-images.githubusercontent.com/6738986/66883160-77f8be00-efff-11e9-83be-1a2ce185d136.gif)

**Comment by jrieken** [comment]
@JetLua That's the idea behind https://github.com/microsoft/vscode/issues/10266. Pressing shift+enter or shift+tab will insert and not replace, just pressing enter or tab will replace the current word. We can add yet another setting for this but I wonder if the two keyboard shortcuts are enough

**Comment by JetLua** [comment]
Thanks for the instructions. I see.

**Comment by jrieken** [comment]
Let me know if that works for you.

**Comment by JetLua** [comment]
ok，it's good to me.

**Comment by JetLua** [comment]
@jrieken Getting used to pressing the `enter` key(not replace) , is there any way to rebind the keys ? Custom configurations do not take effect.

**Comment by jrieken** [comment]
Should be better with tomorrows insiders, see https://github.com/microsoft/vscode/issues/10266#issuecomment-543104017
