### ISSUE TITLE
Error: /Users/bpasero/Development/monaco/extensions/markdown/src/extension.ts(11,31): Cannot find module 'vscode-extension-telemetry'

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8249]
Getting this error running out of source.

**Comment by kieferrm** [comment]
That would indicate that the module is not in your `node_modules` folder. I just deleted my `node_modules` folder and ran `./scripts/npm.sh install`. It's installing it fine. The only recommendation I have is to rerun `./scripts/npm.sh install` on your machine.
