### ISSUE TITLE
No Intellisense with Javascript React

### ISSUE THREAD

**Issue by baoziv587** [Microsoft/vscode#825]
might    be structure  of some setting files?

**Comment by alexandrudima** [comment]
@jrieken I think we don't support rich language features for jsx, right?

**Comment by egamma** [comment]
Correct, the plan is to collaborate with the TS team on Salsa Microsoft/TypeScript#4789

**Comment by fhelwanger** [comment]
For now, you can use eslint as a workaround: https://github.com/Microsoft/vscode/issues/140#issuecomment-158673051

**Comment by didierfranc** [comment]
I made this to get everything working OOTB https://github.com/didierfranc/vscode-react-intellisense

**Comment by jrieken** [comment]
Closing since we now use TypeScript for this.
