### ISSUE TITLE
Improve handling of invalid built-in extension manifest files

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82504]
https://github.com/microsoft/vscode/issues/82359 Shows how fragile the extensions system is wrt built-in extension loading errors. We should improve the following:

- A single thrown exception in [`ExtensionManifestParser`](https://github.com/microsoft/vscode/blob/2e5e00128caf847cc6630e69af34810d4d042668/src/vs/workbench/services/extensions/node/extensionPoints.ts#L50) should not disable all built-in extensions
- That exception message should contain information about [which extension failed to load](https://github.com/microsoft/vscode/issues/82181#issue-504906007).
- Failure to load a built-in extension currently shows no error message whatsoever.

I could confirm none of these points are respected by forcing an error when parsing the manifest file by simply wiping out the contents of a built-in extension's `package.json`.

cc @aeschli

**Comment by alexandrudima** [comment]
@joaomoreno I cannot reproduce. I have emptied out a `.json` file in one of our built-in extensions and everything except that extension works fine.

Some background:
1. the code used to have a try-catch around parsing JSON using JSON.parse
2. the try-catch was removed by @aeschli

Of course the code becomes fragile if a try-catch is removed and it now throws where it never threw before.

@aeschli IMHO the code has been made fragile by https://github.com/microsoft/vscode/commit/479563e361f3face96b36220e7fe75384377e17f, please review and harden with a try-catch.

**Comment by aeschli** [comment]
@alexandrudima our (vs.)json.parse does not throw, it adds errors to the error array
 json.parse can return undefined or null. That was fixed for #82359 (In the meantime I also went over other places where that's the case).

**Comment by aeschli** [comment]
@alexdima try catch is no longer needed (our (vs.)json.parse does not throw).
I added a error message if the manifest is not an object as expected.

**Comment by aeschli** [comment]
To verify: In the vscode repo, go to teh package.json of a built-in extension and clear the full content (make it empty) or replace it with an array or literal.
