### ISSUE TITLE
Python extension squashes notebooks to single line

### ISSUE THREAD

**Issue by twolodzko** [microsoft/vscode#82500]
- VSCode Version: 1.39.1
- OS Version: Ubuntu 

Steps to Reproduce:

1. Create a notebook in Jupyter / JupyterLab
2. Open the notebook in VS Code 
3. Save the notebook

After creating the notebook in Jupyter, it has the following formatting:

```
{
 "cells": [
 {
   "cell_type": 
      ...
```

after editing and saving in VS code, it gets squashed into long single line:

```
{"cells": [{"cell_type": ...
```

Expected outcome: keep the initial formatting. This increases readability when using code diff tools (e.g. git diff).

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
It must be an extension that causes this. The built-in JSON formatter does not put everything on a line. Maybe it's another formatter?
Note that you can enable format on save using this:
`"[json]": { "editor.formatOnSave": false }` (just for JSON if that's what you want)

**Comment by aeschli** [comment]
Please reopen if this is not caused by an extension.
