### ISSUE TITLE
$LMOD_SETTARG_CMD VS Code error message

### ISSUE THREAD

**Issue by PeterJPRoche** [microsoft/vscode#82508]
I have looked for an existing issue about this but don't see any. I have also tried VS Code Insiders and get the same error message.

When I run a debug session, I get the following error message prompt and the debug session fails. I can open the "launch.json" and see the debug settings. 

![image](https://user-images.githubusercontent.com/19158178/66757371-f59fbb00-ee93-11e9-84cf-0dcb875900f8.png)

I haven't got a clue what this could be, hence why i raise it here. Also, all my debugging sessions worked last week when I tried them last, this just seems to have started not working. I appreciate that's not much to go on, but it is all I have got a the moment!

Any help/guidance appreciated as I cannot now debug any of my (Python) applications. 

- VSCode Version: 1.39.1
- OS Version: Win 10, Version 1809

Steps to Reproduce:

1. Press F5 or click the debug menu icon and select config to debug

**Comment by isidorn** [comment]
I am 99% sure this is an issue in the pyhton extensino, can you please file it there so they invesigate first. Thanks a lot
https://github.com/microsoft/vscode-python

**Comment by PeterJPRoche** [comment]
The issue does not seem to be the extension, see https://github.com/microsoft/vscode-python/issues/7971. They are suggesting it is an issue with VS Code ...

I downgraded VS Code to 1.38.1 and that has fixed the issue

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/82611
