### ISSUE TITLE
VSCode Interface turns gray when HDR mode is on.

### ISSUE THREAD

**Issue by RA1NN1AR** [microsoft/vscode#82501]
![image](https://user-images.githubusercontent.com/25654559/66746875-a4a0be80-eeb5-11e9-8a5d-12cf67377eba.png)
Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by anemitz** [comment]
I think this is a bug with Electron. Had a fresh Win10 install with HDR on and 2 electron based apps had this issue. Turning off HDR fixed it.

**Comment by RA1NN1AR** [comment]
Tried , unbelivable it's solved! Thank you !
