### ISSUE TITLE
Startup ~100ms slower with Electron 6

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#82509]
The perf bot shows that builds running Electron 6 are starting roughly 100ms slower (1835ms vs 1723ms). We should understand why and we should try to get that time back. Seems to only happen with windows.

**Comment by deepak1556** [comment]
Pending verification once https://github.com/electron/electron/pull/20709 gets into the next electron version bump.

**Comment by pedrogarcia** [comment]
VS Code keeps increasing the startup time. Meanwhile, Sublime Text is just freaking amazing and starts faster than the time of realizing you launched it. 

Launching Sublime Text is so seamless and fast that it becomes muscle memory. It's so fast you don't even have the time to realize you launched a crazy complex program to do some very complex task. 

When I launch VS Code, I have the time to realize I am launching a text editor, to realize "if I launched Sublime Text it would be much faster and this editing would be done already", and I also have the time to become frustrated and annoyed. When launching VS Code, I have the time to realize I launched a text editor.

This issue indicates that startup time will not be getting any better with VS Code, if anything, it will just be getting worse. 😞

**Comment by jrieken** [comment]
Looking at telemetry it seems that getting the workbench ready takes longer now. Since day 284 it dropped by a lot which might hint towards the code mitigation change

<img width="412" alt="Screenshot 2019-10-28 at 17 46 42" src="https://user-images.githubusercontent.com/1794099/67698600-ef88fe80-f9aa-11e9-8354-5237ec2faf06.png">

**Comment by deepak1556** [comment]
Build a release config with that flag turned off to verify the difference, will post updates shortly.

**Comment by jrieken** [comment]
@deepak1556 With electron fiddle and this gist https://gist.github.com/3d4909b7a1fc1664b962fb108de2d150 and I can also see how electron 6 is somewhat slower

**Comment by jrieken** [comment]
I assume nothing will happen for the October timeframe... 😭

**Comment by deepak1556** [comment]
@bpasero I tried that, there was no difference that was consistent enough to point it as the cause. I am now tracking down the regression on electron side.

**Comment by bpasero** [comment]
Makes sense.

**Comment by jrieken** [comment]
I guess we won't do anything except for hoping that this is getting better with the next version of electron.
