### ISSUE TITLE
Display stuck

### ISSUE THREAD

**Issue by lukacg** [microsoft/vscode#82519]
When I'm using VSCode on HP ProBook 650, about 1/5 of display are frozen( on right side).
This problem is present while the application is active

**Comment by roblourens** [comment]
Can you explain some more about exactly what you are seeing, preferably with pictures?

**Comment by lukacg** [comment]
Sorry, I didn't express myself correctly. The software displays everything
correctly, but when I'm using VSC, one part of the screen does not respond
to mouse commands. I can't manage the code that is in that part of the
screen. And when the VSC is minimized, other applications also don't work
on that part of the screen.

**Comment by roblourens** [comment]
> And when the VSC is minimized, other applications also don't work
on that part of the screen.

This sounds like a strange problem. If you quit vscode, then everything works as expected?

Can you attach a video? That would be really helpful.

**Comment by lukacg** [comment]
Sorry I didn't answer you earlier.
The problem occurs only when I'm ussing VSC.
But the problem temporarily disappeared as the project progressed.
I had trouble using "Fraps" but I will do my best to record this
problem, if it comes up again.
