### ISSUE TITLE
Octicons not Rendering in bottom task bar

### ISSUE THREAD

**Issue by mcollier** [microsoft/vscode#82511]
Issue Type: <b>Bug</b>

Git icons are not showing on the bottom task bar.  Instead of the icon, I see placeholders such as "$(icon octicon-getpull-request)" and "$(icon octicon-package)"  There are 5 placeholders that all begin with "$(icon octicon-)".

![vscode octicon error](https://user-images.githubusercontent.com/1142273/66762203-61653200-ee5a-11e9-9e4c-ff398c1de94c.png)

VS Code version: Code - Insiders 1.40.0-insider (ceeb587991f647659d42a82f87acf3d9778b4d0e, 2019-10-14T10:20:22.455Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
armview|ben|0.3.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.31.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.22
docs-preview|doc|0.3.34
docs-yaml|doc|0.2.4
xml|Dot|2.5.0
gitlens|eam|10.1.1
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
code-runner|for|0.9.14
docker-explorer|for|0.1.6
dotnet-test-explorer|for|0.7.1
vscode-pull-request-github|Git|0.12.0
rest-client|hum|0.22.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.18.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-logicapps|ms-|0.2.18
vscode-asa|ms-|0.1.5
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.4
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.7.0
material-icon-theme|PKi|3.9.1
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-yaml|red|0.5.3
bash-debug|rog|0.3.6
gi|rub|0.2.11
arm-snippets|sam|1.4.19
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.18
azure-event-hub-explorer|Sum|0.1.2
todo-list|Tza|1.5.1
vscodeintellicode|Vis|1.1.9
azure-iot-toolkit|vsc|2.11.0
vscode-icons|vsc|9.4.0

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
@mcollier this looks like it's coming from an extension and not referencing them correctly, can you try disabling your extensions to see if this persists? Then re-enable one by one until you find the culprit and let me know the name of the extension.

**Comment by misolori** [comment]
@mcollier  I've done some digging and it appears that this is an issue with the [Azure Repo](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) extension:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/35271042/66787517-de170100-ee98-11e9-9863-1788657a7621.png">

Please file a bug with the the extension as this is not something we control.

**Comment by misolori** [comment]
This appears to be fixed with today's Azure Repos extension update:

![image](https://user-images.githubusercontent.com/35271042/68417947-306fd880-014c-11ea-902e-54d1261c906b.png)
