### ISSUE TITLE
Make coding inside notebook has the same experience as coding in vscode tab

### ISSUE THREAD

**Issue by quanvuong** [microsoft/vscode#82516]
I'm loving the ability to directly open and edit notebook in vscode 1.39.1. However, many of the things I love about vscode does not work in the notebook tab. For example:

- Jump to definition of variable by Cmd + Click
- Search (Cmd + F does not work)

Is it possible to give coding inside notebook the same experience as coding in a normal vscode tab? Thanks!

**Comment by nchammas** [comment]
Save and undo also seem to be broken when working with Jupyter Notebooks.

See: #82474, https://github.com/microsoft/vscode/issues/77131#issuecomment-532905497

**Comment by roblourens** [comment]
Please file this on the vscode python extension's repo: https://github.com/microsoft/vscode-python
