### ISSUE TITLE
Dependencies: update to node @types 12.x

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82514]
When we ship with Electron 6, we should update our `@types/node` dependency to 12.x as well for:
* [ ] vscode core
* [x] all our built in extensions

I would wait before updating `build/package.json` until we do https://github.com/microsoft/vscode/issues/80842

**Comment by bpasero** [comment]
Something bizarre is going on when I change our `package.json` `@types/node` to 12.x. One of the first errors I see is this:

![image](https://user-images.githubusercontent.com/900690/67663816-9a2afe00-f966-11e9-86da-f8e259f00597.png)

(which means "Duplicate declaration of promises"). 

It looks like we are having our own definiton of promise (`es6-promise.d.ts`) for some reason. I wonder if we are sitting on a very old definition of promises that was always dragged in. Because a ton of other errors I see all seem to originate from more correct typing of promises in our code:

![image](https://user-images.githubusercontent.com/900690/67663929-dbbba900-f966-11e9-9ab2-de1144638523.png)

@mjbvz adding you, I wonder if we never saw these promise issues because of our own definition. Then we should possibly remove it or bring it to latest.

**Comment by bpasero** [comment]
Oh, maybe I did something wrong: I used VSCodes built in task to compile:

![image](https://user-images.githubusercontent.com/900690/67664333-bd09e200-f967-11e9-8e80-52cd4ff5cd1e.png)

That possibly used TS 3.7 to compile?

Still, the duplicate promise issue sounds fishy.

**Comment by mjbvz** [comment]
Yes everything should be building using TS 3.7 now. 

I suspect that we've always had multiple definitions of `Promise`, but that node 12 typings somehow pull in an incompatible type definition for `Promise`. I'll take a look in November

**Comment by bpasero** [comment]
I actually do think that all of the errors produced make sense, they are actual bugs with our code.

**Comment by mjbvz** [comment]
@jrieken Assigning you for help with the es6.promise typings, see https://github.com/microsoft/vscode/pull/85578

**Comment by jrieken** [comment]
What exactly is the problem here? Is that that node.d.ts pull in a depdency onto a different Promise-definition? Where does that come from?

**Comment by mjbvz** [comment]
I've reverted the changes to `es6-promise.d.ts` in #85578 to get back to the original error:

![Screen Shot 2019-12-16 at 3 59 46 PM](https://user-images.githubusercontent.com/12821956/70953125-34312d80-201d-11ea-882c-97a9ffec2447.png)

I believe that the promise definition in `es6-promise.d.ts` is incompatible with the other promises, but am having trouble tracking down why this is the case

**Comment by jrieken** [comment]
I guess that's because `es6-promise.d.ts` doesn't use the new symbol-based properties. Maybe, we need to exclude that from the normal build and only have it in the Monaco/IE11 build. Tho, I am still unsure from where the "new" promise leaks into the compilation but I guess that's just TypeScript and the fact that node API refer to promise...

**Comment by jrieken** [comment]
Confirmed - excluding es-promise from the vscode compile removes these issues. That sounds like a plan but I am still unsure how the other promise definition comes into the system...
