### ISSUE TITLE
Bugs After Update

### ISSUE THREAD

**Issue by GSKarthik369** [microsoft/vscode#82515]
Issue Type: <b>Bug</b>

Bug List after new version update

1) Unable to use terminal inside VSCode

2) Unable to goto the page using definition inside a file

3) Disconnects Frequently when we use ssh

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 2.6.32-754.18.2.el6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3380M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ec2-3-94-21-64.compute-1.amazonaws.com|
|OS|Linux x64 2.6.32-754.18.2.el6.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (1 x 2400)|
|Memory (System)|1.83GB (0.08GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
vscode-icons|vsc|9.4.0
vscode-twig-pack|baj|1.1.0
vscode-intelephense-client|bme|1.2.3
phpunit|ema|4.0.2
php-debug|fel|1.13.0
unibeautify-vscode|Gla|0.7.0
phpcs|ika|1.0.5
twig-language-2|mbl|0.8.10
vscode-typescript-tslint-plugin|ms-|1.2.2
php-docblocker|nei|2.0.1
vscode-phpcbf|per|0.0.8
git-autoconfig|shy|0.0.1
vscode-link|sle|1.0.0

</details>

**Comment by roblourens** [comment]
Thanks but I'm going to need more details. Please open separate issues for each, with detailed directions for how to reproduce the issue.
