### ISSUE TITLE
Add margin/padding to webview hosting extension readme

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8251]
Testing #8215 

It would look a lot better

![image](https://cloud.githubusercontent.com/assets/5047891/16409608/c5cdfab0-3d1e-11e6-9df9-364a7245bc1f.png)

**Comment by isidorn** [comment]
Not critical - assigning to Joao and July so he can decide.

**Comment by isidorn** [comment]
Actually the fix is easy and would make it look considerbly better -> june and me

**Comment by Tyriar** [comment]
I agree, this should go in for June.

**Comment by joaomoreno** [comment]
Argh I hate these build issues...
