### ISSUE TITLE
Support for interactive git hooks?

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode#82512]
I wrote a global `git` hook for spell checking commit messages. It displays to the user a list of possible spelling mistakes (if any) and prompts to either abort the commit and modify the message or proceed anyway.

Everything works as expected on the command line. But using VS Code's built-in source control UI, I get the error `/dev/tty: Device not configured`.

Any way for VS Code to support interactive `git` hooks?

**Global `commit-msg` hook**
```sh
#!/bin/sh

if ! command -v aspell &>/dev/null; then
  printf "%s\n" "[commit-msg hook] Warning: 'aspell' not installed. Unable to spell check commit message."
else
  wordList=( $(grep -v "^  " "$1" | aspell list) )
fi

if (( "${#wordList[@]}" > 0 )); then
  printf "%s\n" "[commit-msg hook] Possible spelling errors found in commit message:" "${wordList[@]}"
fi

exec < /dev/tty

while true; do
  read -p "[commit-msg hook] Proceed anyway? (y/n) " yn
  if [ "$yn" = "" ]; then
    yn='y'
  fi
  case $yn in
      [Yy] ) break;;
      [Nn] ) exit 1;;
      * ) echo "Please answer y for yes or n for no.";;
  esac
done
```

**Comment by joaomoreno** [comment]
Very likely there won't be any support more than the current API. You can add some way to call back to an extension running in VSCode which would show up some UI for the user to interact with.
