### ISSUE TITLE
Make it more obvious that issue can't be submitted without a selected source

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#82518]
VS Code Insiders.

Selecting the 'Preview' button has no effect

![image](https://user-images.githubusercontent.com/172399/64551778-2ab96a80-d336-11e9-9c2a-ea699e0e4897.png)

**Comment by RMacfarlane** [comment]
Added validation messages to empty fields with https://github.com/microsoft/vscode/commit/fe4d4f7d027ed65cd02197e73b364548e6b6ef13
