### ISSUE TITLE
Python test not stopping after error

### ISSUE THREAD

**Issue by filipe-guerra** [microsoft/vscode#82526]
Create a pytest in a python with selenium webdriver project and execute it clicking on play button. After the execution stopped by an error or if it ends, the status of test continue like an execution status (I don't see anymore a X - error or a V - pass, only a rotating arrow - executing). This error starts after the last 2 updates.
![bug](https://user-images.githubusercontent.com/8474726/66778778-115e8d80-eea3-11e9-9872-abffe37c4b72.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python repo.
