### ISSUE TITLE
Don't auto expand tree in source control

### ISSUE THREAD

**Issue by levani** [microsoft/vscode#82527]
- VSCode Version: 1.39.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Set source control view to tree mode
2. Collapse all items
3. Add or remove item to/from staged area.

Does this issue occur when all extensions are disabled?: Yes

Right now all collapsed state is lost when items are added or removed from staged area. Small example video below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/184472/66779387-15a89c00-eedf-11e9-9564-c5ecf964f17d.gif)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82346
