### ISSUE TITLE
can not install extension online or offline

### ISSUE THREAD

**Issue by Soolizo** [microsoft/vscode#82525]
🚨 The issue tracker is not for questions 🚨

Hi, I have uptaded to the latest version of mac(10.15), but i found that the vscode can not install any extention from the store, it just shows that failed to install xxxx. Even if i download the .vsix file and install it from the terminal using` sudo code --install -extension "EXTENTION NAME"`, it shows successfully with waring " Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. But in the store they still ask me to install the extentions.
And i found that the extension i intalled before required me to install again.
What should I do ?

**Comment by sandy081** [comment]
Which version of VS Code are you on?
