### ISSUE TITLE
Resize doesn't fire on integrated terminal

### ISSUE THREAD

**Issue by 8HoLoN** [microsoft/vscode#82522]
- VSCode Version: 1.39.1
- OS Version: W10P : 10.0.18362.418
[cmd-resize-bug.zip](https://github.com/microsoft/vscode/files/3725942/cmd-resize-bug.zip)

Steps to Reproduce:

1. Open cmd or powershell on integrated terminal on VSCode
2. run `node test.js` (after `npm i`)
3. resize the panel or window => the number of column or row is not modified, resize event is not fired
4. run the same `node test.js` on native cmd or powershell => everything is OK

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
What resize event?

**Comment by 8HoLoN** [comment]
https://nodejs.org/api/tty.html#tty_event_resize

Have you tried the script I provided ?

It works well within an native cmd but not in an integrated terminal on vscode.

Regard,

**Comment by Tyriar** [comment]
This is likely a problem with the conpty backend we use. You can try to reproduce the problem in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and if it happens there as well, report to [microsoft/terminal](https://github.com/microsoft/terminal).

**Comment by 8HoLoN** [comment]
OK, thx. I'm going to do that, it doesn't works on the new Windows Terminal.

Regards,
