### ISSUE TITLE
Debugging with 'autoAttachChildProcesses' not working

### ISSUE THREAD

**Issue by samtstern** [microsoft/vscode#82523]
Issue Type: <b>Bug</b>

I wrote this small script to use `cluster` to launch some subprocesses:

**index.js**
```js
const cluster = require('cluster');

if (cluster.isMaster) {
    console.log(`Master ${process.pid} is running`);

    // Fork 4 workers.
    for (let i = 0; i < 4; i++) {
        const WORKER_NUM = i;
        cluster.fork({
            WORKER_NUM
        });
    }

    cluster.on('exit', (worker, code, signal) => {
        console.log(`worker ${worker.process.pid} died`);
    });
} else {
    console.log(`Worker ${process.pid} started ${process.env.WORKER_NUM}`);

    // Add a breakpoint on only the 3rd worker
    if (process.env.WORKER_NUM === '3') {
        console.log("I am worker 3!");
    }
}
```

This is my `launch.json` file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Cluster",
            "program": "${workspaceFolder}/index.js",
            "autoAttachChildProcesses": true
        }
    ]
}
```

When I hit the "play" button on that config it looks like the subprocesses never run:
```
$ cd /tmp/tmp.Y3yEbU3KdQ ; /usr/local/google/home/samstern/.nvm/versions/node/v10.16.0/bin/node --inspect-brk=40242 index.js 
Debugger listening on ws://127.0.0.1:40242/b3cb7ac5-3710-42f9-b1be-9d9ca4fb4560
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Master 236270 is running
Debugger listening on ws://127.0.0.1:40243/7bf74bcc-fefc-4198-9401-de7800347383
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:40244/2781e1a6-92b5-4c08-87c7-4e3a02fbbf11
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:40245/dea14bce-05f5-4251-9c31-3982199abc11
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:40246/06effd32-5b73-434a-b83f-5787446de974
For help, see: https://nodejs.org/en/docs/inspector
```

If I just run the script, they do run;
```
$ node index.js
Master 236586 is running
Worker 236595 started 1
Worker 236594 started 0
Worker 236596 started 2
Worker 236598 started 3
I am worker 3!
```

So it looks like the subprocesses are getting `--inspect-brk` but the debugger is never attaching (and giving a continue signal) so they can't actually get to my code.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 4.19.37-5+deb10u2rodete2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|62.90GB (7.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mjml|att|1.6.0
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
vue|liu|0.1.5
Kotlin|mat|1.7.0
python|ms-|2019.10.41019
Go|ms-|0.11.7
sublime-keybindings|ms-|4.0.3
vetur|oct|0.22.4
vsfire|tob|1.4.1

</details>

**Comment by roblourens** [comment]
I can't reproduce this. What version of node are you using?

**Comment by samtstern** [comment]
```
$ node --version
v10.16.0
```

Interestingly this bug does not occur on my Mac running Node 8 (identical code).

**Comment by samtstern** [comment]
Confirmed that if I add:
```json
            "runtimeExecutable": "/usr/local/google/home/samstern/.nvm/versions/node/v8.16.0/bin/node",
```

This still happens on my Linux machine.  So I think it's a Linux vs Mac thing more than a Node version thing.

**Comment by fuguohong** [comment]
Not just Linux, I got the same problem on windows 10. 
Node version: v12.13.0
VSCode version: 1.40.0 (system setup)

**Comment by kmelmon** [comment]
I am facing a very similar issue trying to debug the workers created by Metro, the javascript bundler created by facebook (see https://facebook.github.io/metro/).

Metro internally uses the child_process.fork() method to spawn its child processes.  See:
https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

These processes cannot be debugged in VS Code using the autoAttachChildProcesses option.  I'm currently having to work around this by limiting Metro to use no workers, which makes things run much more slowly.

Ideally this would "just work" in VS Code without any workarounds.

**Comment by roblourens** [comment]
@kmelmon You might have luck with our new js debugger implementation which uses a different strategy that might work for you.

https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger

**Comment by connor4312** [comment]
As Rob mentioned, we since have a [new debugger](https://github.com/microsoft/vscode-js-debug/) that handles debugging children in a more reliable way. Please let us know if you're still running into problems, and if so open an issue on that repo.
