### ISSUE TITLE
Una mejora interesante.

### ISSUE THREAD

**Issue by shinoblackss** [microsoft/vscode#82520]
Hola soy fans de VSCode, quisiera saber si existe alguna manera de guardar su configuracion, extentension, entre otras cosas. Es algo tedioso tener que re configurar mi editor de texto cada vez que estoy en una pc diferente. Y si esta funcion ya existe, pro favor explicadme como se usa.

**Comment by roblourens** [comment]
> Hi, I'm VSCode fans, I would like to know if there is any way to save your configuration, extentension, among other things. It's a tedious thing to have to re-configure my text editor every time I'm on a different pc. And if this function already exists, please explain to me how it is used.

This extension is probably what you are looking for: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
