### ISSUE TITLE
KeyBinding Problem

### ISSUE THREAD

**Issue by ghassemiehsan** [microsoft/vscode#82532]
Issue Type: <b>Bug</b>

sometimes with toggling recording button it is still stuck in recording mode

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
Are you talking about the "recording" mode in the keybindings editor? Can you give exact steps to reproduce this issue?

**Comment by ghassemiehsan** [comment]
hi
sorry for my bad english.
yes i'm takling about recording mode in keybindings editor
step:
1.opening keyboard shortcuts
2.pressing record keys button to record a hotkey for example :ctrl + s
3.turning off and again on
4.after step 3 when i turn the recording mode off ,text input section only accept a hot key

**Comment by koseki** [comment]
@roblourens 
This is what happening in my environment.

 1. Start with command `$ code --disable-extensions`.
 2. Enable screencast mode.
 3. See the below screencast.

![20191103115153](https://user-images.githubusercontent.com/11028/68079750-f8a61f80-fe31-11e9-93e8-879d9b684130.gif)


> Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by chrisdias** [comment]
this is a dupe of #82714 (or vice versa, the other one is still open)
