### ISSUE TITLE
Welcome screen text rendering issue

### ISSUE THREAD

**Issue by sghitch** [microsoft/vscode#82537]
Issue Type: <b>Bug</b>

Opening a second instance of VSCode creates odd text rendering artifacts in the Welcome Menu/File explorer 
![image](https://user-images.githubusercontent.com/10263742/66787636-4960d300-ee99-11e9-827f-3109bedf6ba8.png)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.1.1
githistory|don|0.4.6
python|ms-|2019.10.41019
vscode-yaml|red|0.5.3
vscode-open|san|0.1.0

</details>

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by roblourens** [comment]
> Opening a second instance of VSCode creates odd text rendering artifacts in the Welcome Menu/File explorer


Also can you explain this in more detail... how are you opening vscode? Is it only the second window that shows these glitches or both?
