### ISSUE TITLE
“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by simonzoeger** [microsoft/vscode#82534]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bhandaribhumin** [comment]
@simonzoeger https://github.com/microsoft/vscode/issues/74782

**Comment by JManuel-industrialist** [comment]
i am having the same issue. what is the fix?

**Comment by Nandulucky** [comment]
macOS Catalina requires apps to be notarized by Apple. Your version of Visual Studio Code is yet to be updated by Microsoft for the new OS.

Please try the following:

Right-click on the app and select Open.

If this did not work, remove the quarantine extended attribute that’s set on the app:

Move the app to the Applications folder
Open Terminal.app, then paste and execute the following command:
**xattr -d com.apple.quarantine /Applications/Visual\ Studio\ Code.app**

**Comment by RatkoG** [comment]
Thank you this fixed my issue for now...

**Comment by GoldenBharanipept** [comment]
@Nandulucky  thank you mate!!

**Comment by FlorianWendelborn** [comment]
@Nandulucky please credit your sources when you plagiarize an answer: https://stackoverflow.com/a/58458252/2857873

**Comment by eddiemonge** [comment]
This is also not a good answer because this merely bypasses the security instead of actually getting the software signed.

**Comment by stonedreamforest** [comment]
+1

**Comment by kaustubhShetty** [comment]
Just right click on the app in finder, then again click on open. Worked for me this way.

**Comment by Sarathphd** [comment]
select vscode icon and right click open, again select open its working.
