### ISSUE TITLE
Edge case with cursorUndo

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82535]
After making edits that don't move the cursor (with commands such as `deleteRight`, `deleteWordRight`, `copyLinesUp`, `deleteLines`) the first cursor move following it is ignored by `cursorUndo`.

Steps to Reproduce:

1. Type <kbd>hello</kbd>
2. Press <kbd>Left</kbd>
3. Press <kbd>Delete</kbd>, the `o` should be deleted
4. Press <kbd>Left</kbd>
5. Press <kbd>Ctrl</kbd>+<kbd>U</kbd> - nothing happens

Expected behavior: The cursor should move back to the end.

The implementation of the `cursorUndo` command assumes that an edit will be immediately followed by a cursor move. This is usually true but not always, as you can make modifications without moving the cursor. And those will cause the next cursor move to not be registered in the cursor undo stack.

- VSCode Version: 1.39.1
- OS Version: Windows 10
- Does this issue occur when all extensions are disabled?: Yes

**Comment by NotWearingPants** [comment]
I am working on a fix for this. PR will be submitted soon.

**Comment by NotWearingPants** [comment]
I suspect that fixing this is impossible without changing things in the core editor as well.
**I've stopped working on a fix for this**, because this requires discussing changes to the monaco API.

---

### The problem:

Editor contribs receive an editor instance implementing `ICodeEditor` in their constructor.

`ICodeEditor` exposes the ability to listen to text changes or cursor changes - using the methods `onDidChangeModelContent` and `onDidChangeCursorSelection` respectively.

Naturally, when the text changes it *can* cause a cursor change as well, but not always.
**There is no way of knowing the initial state of the cursor after a text change using the `ICodeEditor` API.**

If the text change *does not* change the cursor, we need to look at the cursor positions at the time of the text change event.

If the text change *does* change the cursor, we need to wait for the first cursor change event after the text change event fires, and then look at the cursor positions.

There is also no way of knowing whether a text change changed the cursor.

---

### What I discovered so far:

The main participants seem to be:

- `src/vs/editor/common/controller/cursor.ts`
- `src/vs/editor/common/model/textModel.ts`
- `src/vs/editor/common/model/editStack.ts`

It looks like the `Cursor` class has three methods that eventually can cause one or both of the events in question to fire:

- `trigger`
- `setStates`
- `executeEdits`

The text change event is fired by `TextModel._emitContentChangedEvent`, and the cursor change event is fired by `Cursor._emitStateChangedIfNecessary`.

**Comment by NotWearingPants** [comment]
This awaits resolution of #82929

**Comment by NotWearingPants** [comment]
@alexandrudima your fix is wrong and still has the bug in it, just the second variation of it.

Please re-read the description:
>
  If the text change does change the cursor, we need to wait for the first cursor change event after the text change event fires, and  then look at the cursor positions.

Steps to reproduce for this reversed edge-case:
1. Type <kbd>hello</kbd>
2. Press <kbd>Ctrl</kbd>+<kbd>U</kbd> - the cursor moves back to before the `o` even though the cursor should not be undo-able after a content change (as you can see by pressing it again - the cursor won't move again).

Reopen this issue, and also reopen #82929 because this is the only way of fixing it.

**Comment by alexandrudima** [comment]
@NotWearingPants Thank you for being vigilant and for your patience. I've chosen to tweak the cursor change event and add to it the needed metadata.
