### ISSUE TITLE
Support evolving Golang syntax by switching grammar repo

### ISSUE THREAD

**Issue by flowchartsman** [microsoft/vscode#82549]
The Go grammar for Vscode is effectively [frozen](https://github.com/microsoft/vscode/pull/81015) at this time since the atom syntax it is built from [is no longer maintained](https://github.com/atom/language-go/pull/178#issuecomment-532508206). To my knowledge, the only real change to go syntax highlighting that this affects is for the new print verb `%w` introduced in Go1.13, but there will definitely be more. I would support VScode switching to a community-maintained fork such as [this one](https://github.com/jeff-hykin/better-go-syntax/) or forking and maintaining their own until such time (hopefully) as [tree sitter](https://github.com/microsoft/vscode/issues/50140) is a thing and we can resume "borrowing" from Atom once again ;)

**Comment by Jacalz** [comment]
Could this also be the reason for the issues that I reported in https://github.com/microsoft/vscode-go/issues/2892? If that is the case, then I would really love to see this being fixed. Only thing keeping me fro switching from Atom at the moment.

**Comment by flowchartsman** [comment]
@Jacalz If it involves the grammar, then yes. The grammar for Go is effectively frozen at the moment, since it's derived from the old Atom grammar, which is now deprecated.

**Comment by Jacalz** [comment]
Thanks for the information. Hopefully this will be fixed sooner rather than later because it is definitely holding back my switch to vscode and I could see it doing the same for some others too.

**Comment by alexr00** [comment]
@jeff-hykin, Your repo https://github.com/jeff-hykin/better-go-syntax/ is mentioned at the top of this issue. Will it be getting the same TLC as the C++ grammar?

**Comment by jeff-hykin** [comment]
Sadly, I won't be able to put in the amount of effort like I have for C++. With that said:

Most TM grammar repos are simply a `.json`, `.plist`, or `.yaml` file and https://github.com/jeff-hykin/better-go-syntax/ would at least be that. The Go syntax is vastly more simple than C++, so I expect it will not need nearly as much attention. While at the moment I can't create advanced new features, I can approve merge requests and do basic fixes on a weekly or monthly timeframe to prevent the grammar from stagnating.

Switching would certainly net positive, however it would not be anything close to the level of improvement C++ has seen.

If switching right now, the Go syntax
- wouldn't have unit tests
- wouldn't have integration tests
- would not be generated by a scripting language (which, in my opinion, is necessary for long term maintenance of any TM grammar)

Those things will be possible once Matter123 and I get the Textmate grammar library finalized, which could possibly be done the end of winter break. I likely still won't be able to do advanced support, but those additions will make it very easy for outsiders to contribute in a safe and reliable way.

**Comment by alexr00** [comment]
That does sound like a net positive, thanks for the details. VS Code has it's own integration tests for each language, so there will be some coverage for now. I'll look at switching in December.

**Comment by alexr00** [comment]
@jeff-hykin I've pulled in your go grammar. The diff between it and the old one are pretty minimal, so it seems low risk right now. We will likely release the next version of VS Code at the end of January or beginning of February 2020, so there's plenty of time to revert if you're not ready for it to go out in the release!

**Comment by Jacalz** [comment]
I will do some testing with those changes to see if they fix my issues. Thanks for pulling in that better syntax highlighting 🙂

**Comment by jeff-hykin** [comment]
Thanks @alexr00 ! Just wanted to let you know I cleaned up the go syntax repo today so its ready for contributions.

There's already a few hard to fix bugs (a performance bug) that I won't be able to put in the time to address. But I can guide people to fix them and verify their fixes which should keep the syntax from stagnating.

**Comment by ramya-rao-a** [comment]
@alexr00 Is the associated change here part of the January release or available only in the current Insiders?

**Comment by alexr00** [comment]
Currently available only insiders, but will be going to stable in the January release.

**Comment by isavcic** [comment]
Note that, compared to Sublime, VS Code Go syntax highlighting is lacking. Notice the function signatures. You could find more examples of methods etc. being treated as normal text instead of "special".

![Side by side comparison of Go syntax highlighting with Sublime](https://user-images.githubusercontent.com/23181878/57653641-d4bffa80-75c1-11e9-9b6e-26f6da16f2c8.png)

**Comment by Jacalz** [comment]
I totally agree with you @isavcic,  vscode is very lacking sadly :(

**Comment by jeff-hykin** [comment]
@isavcic any idea where Sublime is getting it's syntax files? Its likely we can pull in their changes if they're using open source code.

I remember editing the syntax files in Sublime several years ago, but after downloading it and digging through the files I can't find the source of their Go syntax. The filename should be `Go.sublime-syntax`.
