### ISSUE TITLE
Source control badge shows incorrect changes count

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#82547]
Issue Type: <b>Bug</b>

My project has 0 changes, but the source control icon on the sidebar shows 49 changes.

![image](https://user-images.githubusercontent.com/379339/66793790-50a5d200-eed5-11e9-87b4-b0c94d2fd648.png)

(NOTICE: It's a Flutter project and the C:\Flutter folder has 49 changes, but this is nothing to do with my project >.< My project is in another disk!)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
flutter-stylizer|gml|0.0.14
pubspec-assist|jer|0.3.6
svg|joc|1.0.2
vscode-gutter-preview|kis|0.23.0
regionfolder|map|1.0.5
tgit-cmds|mbi|1.2.2
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-taskexplorer|spm|1.20.1
comment-divider|sta|0.2.1
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.8.0
vscode-icons|vsc|9.4.0

</details>

**Comment by joaomoreno** [comment]
If you right click on the title `Source Control: Git` do you see any other repositories in the context menu?

**Comment by JCKodel** [comment]
Tried to open the "solution" now and the bug is gone (no update on VSCode). No other repo in the context menu, besides the correct one.

**Comment by amcolash** [comment]
I had a similar issue and it looks like if you open a file (outside of the base folder opened) in the same window it will then start looking at the 2nd repository. Not sure if this is a "feature"

Repro for me (sorry a bit lengthy):
- Open folder1/
- Git shows 0 changes
- Modify folder1/file1, shows 1 change
- Open folder2/file2
- Git shows 0 changes
- Close folder2/file2
- Modify/Save folder2/file2
- Git shows 1 change
- Close folder2/file2
- Git shows 1 change

What I would expect is for the source control tab to only look at _currently open files/folders_

**Comment by JCKodel** [comment]
@amcolash Confirmed:

1) Open solution with 0 changes: Icon show no badge
2) Use `Go to definition` in Flutter opens a .dart file from Flutter SDK path
3) Icon now shows 49 changes
4) Close all files: icon keep showing 49 changes =(

Notice that despite Flutter's being displayed on this menu, it is not selected:
![image](https://user-images.githubusercontent.com/379339/66871068-40473300-ef79-11e9-8b7f-9616e4336f71.png)

Perhaps a good solution would only show badge if the folder is being displayed in the Source Control window.

**Comment by joaomoreno** [comment]
> Perhaps a good solution would only show badge if the folder is being displayed in the Source Control window.

Interesting... but I'm not so sure about it. I'll close this issue for now and see if more people come with this request.

If you'd like, you can ignore certain repositories from being automatically loaded by VS Code using the `git.ignoredRepositories` setting.

**Comment by JCKodel** [comment]
@joaomoreno 

![image](https://user-images.githubusercontent.com/379339/66952789-a98b7c80-f033-11e9-8e12-a90e49883ee1.png)

No fix (I'm not sure what to fill in here, so I tried every combination, still showing 49 changes when I open any file from that folder)

**Comment by joaomoreno** [comment]
Which repository is it coming from? Again, use the context menu to show it. You can also use `Git: Show Git Output` and you'll see the path of the repo in the log. That setting also only works after reload, btw.

**Comment by amcolash** [comment]
Why is this closed? Disabling repos is a workaround for specific use cases but not a solution to the problem I mentioned.

**Comment by joaomoreno** [comment]
@amcolash You can disable the automatic repository detection as well: `git.autoRepositoryDetection`.
