### ISSUE TITLE
Python GoToDefinition going to correct line in wrong file

### ISSUE THREAD

**Issue by bethebunny** [microsoft/vscode#82548]
- VSCode Version:
Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
(I'm using python 3.6.8 64-bit
1. $ git clone https://github.com/takluyver/bash_kernel
2. $ python -m venv ~/.venvs/debug_venv
3. $ source ~/.venvs/debug_venv/bin/activate
4. $ pip install bash_kernel
5. $ python -m bash_kernel.install
6. in VScode, select debug_venv python version
7. open bash_kernel/kernel.py
8. go to line 40, and attempt to go to definition on the `expect_exact` token

Expected behavior:
Should navigate to expect_exact, defined in pexpect's spawnbase.py on line 371

Actual behavior:
Navigates to line 371 in pexpect's pty_spawn.py file

I suspect the issue is that VSCode is recognizing that the `self.child` object is a `pty_spawn.spawn` instance, which is defined in `pty_spawn` and subclasses `SpawnBase` (which is defined in `spawnbase.py`.); when hovering it even shows the correct function definition for `SpawnBase.expect_exact`. It then navigates to the line where the function is defined, in the file where the _class_ is defined, rather than where the actual function is defined.

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension repo
