### ISSUE TITLE
Support to install on Windows 10 S Mode

### ISSUE THREAD

**Issue by dilijev** [microsoft/vscode#82542]
Issue Type: <b>Feature Request</b>

VS Code cannot be installed in S mode because it is not signed.

Some basic development activities like working on web pages would be nice to do in S mode, or even just the ability to have VS Code as a better editor than Notepad from first-party for editing text.

Having the binary signed by Microsoft in such a way that makes Windows 10 S mode happy would probably be a good thing in any case.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
//cc @joaomoreno

**Comment by UnsaidAverage** [comment]
Why not make it a Store-App for Windows 10 Platform?
like [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701)

**Comment by VSG24** [comment]
I'm also looking forward to this.

**Comment by joaomoreno** [comment]
Although not 100% a duplicate, I'll merge this with https://github.com/microsoft/vscode/issues/10759

**Comment by dilijev** [comment]
That works for me. Looking for VS Code in the store is the first thing I tried.
