### ISSUE TITLE
alt+drag for column selection executes jump to definition

### ISSUE THREAD

**Issue by jasonbodily** [microsoft/vscode#82540]
- VSCode Version: 1.39.1
- OS Version: Mojave 10.14.6

Steps to Reproduce:

1. Go to `Selection` > `Switch to Alt+Click for Multi-Cursor`
2. In any Javascript or JSX file, hold Alt (same key as `option` on macbook pro) and click and drag down onto a word that is recognized as defineable.
3. One of two bugs will happen: 1) The editor will pop the definition window breaking the multi-line selection or 2) VScode moves the cursor to the beginning of the word last touched by the multi-line selection

![IMB_Fv6nhj](https://user-images.githubusercontent.com/2155466/66789910-df512980-eeaa-11e9-9673-12960a47e2a3.gif)

With no extensions installed this still occurs.

**Comment by alexandrudima** [comment]
@jasonbodily Could you please check the `settings.json` > `"editor.multiCursorModifier"` value?

When that is configured with `"editor.multiCursorModifier": "ctrlCmd"`, then cmd+click will add multiple cursors and alt+click will jump to definition.

When that is configured with `"editor.multiCursorModifier": "alt"`, then alt+click will add multiple cursors and cmd+click will jump to definition.

What is the value you have it configured with, and what exactly is going wrong?

**Comment by jasonbodily** [comment]
Here is my settings.json file: 
```
{
    "workbench.colorTheme": "Monokai",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": false,
    "editor.formatOnType": false,
    "workbench.iconTheme": "Monokai Classic Monochrome Icons",
    "files.associations": {
        ".sequelizerc": "javascript"
    },
    "window.zoomLevel": 0,
    "editor.hover": false,
    "workbench.startupEditor": "welcomePage",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.multiCursorModifier": "alt",
    "workbench.tree.indent": 20,
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "editor.fontSize": 12,
    "editor.snippetSuggestions": "top"
}
```

As to "what exactly is happening", I would refer you to the gif I included above. I would like to edit those three lines simultaneously, but when I release the "alt + click" selection, it brings up the definition of the last word I've selected, and deselects the my intended multicursor selection.

I mentioned there was a second side effect. Here is a gif of that:

![IMB_jsGcat](https://user-images.githubusercontent.com/2155466/66852358-03a81700-ef3a-11e9-943e-f0fbab048614.gif)


The problem is the same, except the cursor invokes 'cursorWordLeft' action instead. I am not pushing the left arrow, this just happens when I release my selection.

In case it's not clear, the behavior I'm expecting is that I make a multicursor selection, and on releasing from the click of my selection, I can type and have my input appear at all cursor selections.

**Comment by jasonbodily** [comment]
I have completely uninstalled vscode (removing all files at ~/Library/Application Support/Code) and redownloaded VSCode. The problem persists.

**Comment by jasonbodily** [comment]
A couple more things to highlight: 

- I have my selection set to "Alt+Click"
- I can only reproduce this error when my multicursor selection ends on a word that VSCode knows how to find the definition of, or when the word I end in is a key in a javascript object.
- If, while making the multi-line selection, I accidentally move the cursor left or right and temporarily highlight a column of adjacent characters, then bring my mouse back into one vertical line, the errors do not happen.

**Comment by ivosabev** [comment]
Same issue on MacOS Catalina after the recent VSCode upgrade, `ctrl+alt+shift+(arrow left/right)` stopped working.

```
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by alexandrudima** [comment]
@ivosabev I am fairly confident that you do not have the same issue. Please create a separate issue.

---

@jasonbodily Thank you for the extra information, I can reproduce, but only with the following precise steps:
- configure `"editor.multiCursorModifier":"ctrlCmd"`
- press alt
- press mouse down and then drag
- release on top of a symbol that has jump to definition available like e.g.:

```ts
const obj = {
  something: [0, 1, 2],
  somekey: true,
  another: [3, 4, 5]
}
```

If the configuration is `"editor.multiCursorModifier":"alt"`, it does not reproduce. If you first press mouse down and then press alt, it does not reproduce.

**Comment by jasonbodily** [comment]
@alexandrudima - I have the same oddity: If I click, then press `alt` and then drag it works. However, if I click `alt`, and then drag it doesn't work for me. I'm coming from Sublime, and the default behavior is as long as you're holding alt you can make multi-line selections so I'm afraid I'm in the habit of holding alt first.
