### ISSUE TITLE
Problem with launch.json args having spaces and ampersand

### ISSUE THREAD

**Issue by c094728** [microsoft/vscode#82541]
VS Version 1.38.1
I am running a node.js and passing these args.  If I remove the 1st one (breadcrumbtext) all of the other args pass in fine.  But with it, the last arg gets truncated at the 1st ampersand and any arguments I place after it will be missing.  If I remove the spaces from the 1st arg it works fine. 

```
 "args": [
                "breadcrumbText=My Breadcrumb Text",
                "filename=developer-cloud.zip",
                "artifactoryGroup=selfpub.test.downloadable-zip-build/output",
                "artifactoryArtifact=developer-cloud",
                "artifactoryVersion=1",
                "targetDocServer=https://docs.oracle.com",
                "publicationsUrl=http://test.com/api/v1/publications?category=cloud&suite=paas&productGroup=app-dev&product=developer-cloud&checkpointName=promoted&checkpointPassed=true&checkpointEnv=docs"
                
                
            ],
```

**Comment by roblourens** [comment]
I don't think this is a vscode issue. We just pass the arguments directly to the program. It seems most likely that your program is not interpeting them correctly. If you think it's a vscode issue, please provide a sample that I can run to see the problem.
