### ISSUE TITLE
can not get env data when debug a python file with root privilege

### ISSUE THREAD

**Issue by enginespot** [microsoft/vscode#82544]
- VSCode Version: 88f15d17dca836346e787762685a40bb5cce75a8
- OS Version:macOS Catalina

Steps to Reproduce:

1. create a python file 
```
import os

print(os.getenv('ENV_DATA'))

```
2.add launch.json debug file
```
{
            "name": "python dev",
            "type": "python",
            "request": "launch",
            "console": "integratedTerminal",
            "args": [
                "${file}"
            ],
            "envFile": "${workspaceFolder}/.vscode/dev.env",
            "sudo": true
}
```
3. create dev.env file
# dev.env - development configuration
ENV_DATA=hello

4. debug the python file , the print result is "None", expect result should be "hello"

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension repo.
