### ISSUE TITLE
Error icons not showing up properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82557]
Seeing this in the stable from https://az764295.vo.msecnd.net/stable/7af863136f4856cdc6893e3f45d050a9a7fce3bf/VSCode-darwin-stable.zip

![image](https://user-images.githubusercontent.com/900690/66804028-ae600b80-ef21-11e9-810e-e426c5a6cda2.png)

**Comment by misolori** [comment]
This should be fixed via https://github.com/microsoft/vscode/pull/82553

**Comment by alexandrudima** [comment]
We have discussed and we must take this.

**Comment by misolori** [comment]
Fixed via https://github.com/microsoft/vscode/pull/82553
