### ISSUE TITLE
JavaScript function parameters hint tooltip not working

### ISSUE THREAD

**Issue by bwanamaina** [microsoft/vscode#82559]
Issue Type: <b>Bug</b>

JavaScript function parameters hint tooltip doesn't appear as i type function arguments, this was working with previous versions.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Please steps to reproduce this. 

/needMoreInfo
