### ISSUE TITLE
TSX: Enhance emmet vs. property selection intellisense

### ISSUE THREAD

**Issue by ArashMotamedi** [microsoft/vscode#82556]
Issue Type: <b>Bug</b>

**Description**
In TSX, inside an open curly brace, intellisense must prioritize **property access** over **emmet**.

**Video**
[https://i.imgur.com/G0DVocP.mp4](https://i.imgur.com/G0DVocP.mp4)

**Repro**
Create a new TSX (React TypeScript) file and start typing a simple component:

    function Badge(props: {children?: React.ReactNode}) { }

Now, in the body of the function component, let's try to return a `div` with class `badge` wrapped around `props.children`. Start by typing: `return div.badge` **And hit tab**. Sweet! That got correctly expanded to:

    return <div className="badge"></div>

Fantastic. Ok, now the pesky part. Let's continue: `return <div className="badge">{props.chil` **And hit tab**. Oh no:

    return <div className="badge">{<props className="chil"></props></div>

**We can do better! In TSX, inside an open curly brace, it makes sense to prioritize property access auto complete suggestion over emmet.** 

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by octref** [comment]
Same behavior on https://docs.emmet.io/. Please open an issue on https://github.com/emmetio/emmet first.
