### ISSUE TITLE
The window has crashed

### ISSUE THREAD

**Issue by Nakiswen** [microsoft/vscode#82560]
- VSCode Version: 1.39
- OS Version: Windows 10

Steps to Reproduce:

1.open vscode
2.occured like this picture
![image](https://user-images.githubusercontent.com/12215349/66808873-b4c0a880-ef5e-11e9-8660-d689520e1777.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Alex-Hou** [comment]
Same issue here.

**Comment by anngitta** [comment]
Mine to. with same appearance as in the top comment. Attached is the log after running the debub diagnostic tool described here: 
https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues
[Code__PID__19140__Date__10_15_2019__Time_12_41_13PM__360__Log.txt](https://github.com/microsoft/vscode/files/3729217/Code__PID__19140__Date__10_15_2019__Time_12_41_13PM__360__Log.txt)

**Comment by roblourens** [comment]
Did this work before? Did it start crashing after updating vscode? Or have you updated windows recently?

**Comment by anngitta** [comment]
Yes, it did work before. I have tried different types of script now to check wether it was one particular. My instiute did some updates recently actuallly. Should I try to reinstall Visual Studio Code. 

This is my code status: 

Version:          Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz (8 x 3600)
Memory (System):  31.93GB (23.09GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       97   15332  code main
    0       73    2620     shared-process
    0       19   12112     electron-crash-reporter
    0      155   13688     window (Settings - SATINNDIR (Workspace) - Visual Studio Code)
    0        6    5448       winpty-process
    0        9    1304         console-window-host (Windows internal process)
    0        4    2936         C:\WINDOWS\System32\cmd.exe
    0       34   16292           electron_node cli.js
    0       53   14476             "C:\Data\Microsoft VS Code\Code.exe" --status
    0       11    5688       watcherService
    0       10    8864         console-window-host (Windows internal process)
    0       58   18492       extensionHost
    0       87   18296     gpu-process

Workspace Stats:
|  Window (Settings - SATINNDIR (Workspace) - Visual Studio Code)
|    Folder (Kopi_import_MERIS_ftp): 2198 files
|      File types: top(692) inn(321) hdr(148) img(147) py(63) xml(45)
|                  prefs(31) csv(26) launch(16) pyc(15)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python

**Comment by roblourens** [comment]
Yeah try reinstalling vscode.

@deepak1556 I'm not sure whether I should assign these to you. I tried to use the electron-atos tool from https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues#read-the-stacktrace. It runs for awhile but doesn't print anything.

**Comment by anngitta** [comment]
I have now reinstalled visual studio code and it still crashes. I have no idea why.

**Comment by jesse-thomas** [comment]
+1 
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by sainulabidnv** [comment]
Hi, 
I am facing the same issue. 
I tried to uninstall and reinstall the latest version, but no luck. 
how do I fix this ?. 
![image](https://user-images.githubusercontent.com/10548248/68637013-608bf280-0523-11ea-94e4-fa77a4be07b6.png)

**Comment by sainulabidnv** [comment]
My problem Solved (--disable-gpu)

Right-click on Shortcut and add --disable-gpu to Target
"C:\Program Files\Microsoft VS Code\Code.exe" --disable-gpu

![image](https://user-images.githubusercontent.com/10548248/68644922-896cb180-053c-11ea-98c7-02c628a47c8c.png)

**Comment by deepak1556** [comment]
Others traces also indicate crash after starting the gpu process, would be good to try launching with `--disable-gpu`. If that helps please update to latest stable and you can permanently configure this option via:

* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by sainulabidnv** [comment]
@deepak1556 
I am working with windows 7, how can I update this ?.

**Comment by Sookdeo** [comment]
Clean up your temp files. Worked for me. Type %temp% on windows search - delete temp files. Open vscode.
