### ISSUE TITLE
Search results: show same line occurrences in same result

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode#82566]
Occurrences that actually belong to the same line are shown as different search results entirely. This gives me a frustrating side-effect: clicking on the second result, thinking it is related to a completely different line, whereas I might have simply looked at the code to find out the next occurrence is at the same line.

<img width="215" alt="screen" src="https://user-images.githubusercontent.com/5409469/66811768-f555fd00-ef31-11e9-8ad1-19d98a33c4f3.png">

Could you add an option to switch between the two behaviours?

**Comment by roblourens** [comment]
The problem is that the second result may or may not be visible, depending on the width of the narrow search view.

The goal of this view is to show individual results, it's not a good place to read code, so I will stick to 1 row = 1 result.

**Comment by niccolomineo** [comment]
Even with the "1 row = 1 result" scheme you could think of adding ellipses to make the difference between the consecutive results more obvious.
