### ISSUE TITLE
Need a keyboard shortcut to Cycle between multiple opened terminals

### ISSUE THREAD

**Issue by justrajeshkp** [microsoft/vscode#82565]
Need a keyboard shortcut to Cycle between multiple opened terminals

Clicking and then selecting for seeing each of the terminal is very cumbersome. Please add a shortcut key for the same

Thanks

**Comment by Tyriar** [comment]
Here are the ones I use:

```
{ "key": "ctrl+shift+j",     "command": "workbench.action.terminal.focusNext" },
{ "key": "ctrl+shift+k",     "command": "workbench.action.terminal.focusPrevious" },
```

See https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by justrajeshkp** [comment]
Thanks,
This was nice information

Regards,
Rajesh
