### ISSUE TITLE
Theme default color is not showing up properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82561]
I am sure the activity background color is not red by default:

![image](https://user-images.githubusercontent.com/900690/66810487-a4dda000-ef2f-11e9-8191-3c96f17d45ca.png)

**Comment by bpasero** [comment]
Still:

![image](https://user-images.githubusercontent.com/900690/67756882-1c84f200-fa3b-11e9-8fc2-d6675d06d92c.png)

**Comment by bpasero** [comment]
Or did you just remove the "Default Value" label?

**Comment by aeschli** [comment]
Getting the actual default color would mean to update the settings defaults on every theme change.
Possible but I thought that would be too much.

**Comment by aeschli** [comment]
Yes, #25633 is the request to fill in the current theme values as default. That's still not implemented as described.
