### ISSUE TITLE
Option to enable vertical scrollbar for output of cell related to jupyter notebook support

### ISSUE THREAD

**Issue by M-Younus** [microsoft/vscode#82573]
I again creating this issue because didn't get reply on old one.Thanks

I checked with insiders it doesn't open ipynb as notebook it just open it as json file.

- VSCode Version: 1.39.1
88f15d17dca836346e787762685a40bb5cce75a8
x64
- OS Version:window 10,64bit,1903

Steps to Reproduce:

1.install latest VS code
2.open the any notebook(ipynb file),there will be no vertical scrollbar for long outputs

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
