### ISSUE TITLE
Compact menu has no hover

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#82577]
There is no hover shown for the compact menu activity bar contribution:

![image](https://user-images.githubusercontent.com/172399/66831985-3281b580-ef59-11e9-95a1-0d4b6f0e3f98.png)

**Comment by sbatten** [comment]
I cannot reproduce on any platform. The hover animation is working for @misolori and myself.

**Comment by egamma** [comment]
@sbatten I can still reproduce this on OS X,  pls see the attached recording:
![missing-hover](https://user-images.githubusercontent.com/172399/68039920-713f9b80-fccd-11e9-8fb6-00a1621ca867.gif)

To reproduce:
- enable the setting: `remote.containers.enableWebAccess": true`
- open a folder in a container
- copy the web URL from the output shown when provisioning the container
![image](https://user-images.githubusercontent.com/172399/68040128-e4e1a880-fccd-11e9-9a51-23e687ee6819.png)

Open the URL in Chrome or Safari.

**Comment by sbatten** [comment]
@egamma OH! I see, I thought you meant the hover highlighting, not the hover text.
