### ISSUE TITLE
could you provide registerCodeLensProvider for the diff-editor?

### ISSUE THREAD

**Issue by 6peiweb** [microsoft/vscode#82572]
I'd love to code some codelens for diff-editor like 
![image](https://user-images.githubusercontent.com/28392443/66825186-56a2be00-ef7c-11e9-866e-d47e884a47ba.png)
please!!!

**Comment by jrieken** [comment]
I don't understand the issue here. Code lens can work for any editor and there is no API limitation that would prevent them from working inside a diff editor.
