### ISSUE TITLE
1.39.1 upgrade - no longer open project from URL vscode://

### ISSUE THREAD

**Issue by hookedupjoe** [microsoft/vscode#82578]
Issue Type: <b>Bug</b>

Using the prefix vscode://file ... in the browser used to open vs code and then open the project.  Now it opens VS Code, but not the project.  I tried this in more then one browser.  I had used the feature, then updated .. and the feature no longer worked .. this AM.  So it has to be related to the release it seems. 

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82212
