### ISSUE TITLE
Extension UI: introduce a small margin around the  

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8257]
Extension description is too close to the view edge and looks cutoff:

![2016-06-28_11-01-48](https://cloud.githubusercontent.com/assets/1898161/16409869/f8f30c86-3d1f-11e6-8e5a-2c4d66b985f8.png)

I suggest to introduce a small margin around the Extension description.

**Comment by isidorn** [comment]
Dup of #8251
