### ISSUE TITLE
Math with double dollar symbol does not render properly

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [microsoft/vscode#82575]
When using Jupyter notebooks in VSCode, math with double dollar symbols does not render.

It works fine with Jupyter Lab but not in VS Code. Screenshots attached for both.

![image](https://user-images.githubusercontent.com/6263572/66830492-84244300-ef4d-11e9-8b5b-0217d0ef2a18.png)

![image](https://user-images.githubusercontent.com/6263572/66830567-a918b600-ef4d-11e9-8ad2-a5029c004d9f.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
