### ISSUE TITLE
 Illegal argument: source must be a string of length > 0

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#82580]
Issue Id: <b>0df1b54d-14ea-f280-323b-64054adad4b7</b><br /><br />*Versions* <br />- 1.39.1<br />-  9df03c6d6ce97c6645c5846f6dfa2a6a7d276515<br />-  c8252b63f547674d2faf361d4181bb76b0b5f81a<br />-  d3eb24828e2d977e4f3ac16ff1a332a020028464<br />-  5cd3b2abc98ebc8c8e226f0cd95a9bca93e2b4ad<br />*Stack* <br />Error: Illegal argument: source must be a string of length > 0<br />[/vs/base/common/errors.ts#156:9 (illegalArgument)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/base/common/errors.ts#L156:9 (illegalArgument))<br />[/vs/workbench/api/common/extHostTypes.ts#2001:9 (arg4)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTypes.ts#L2001:9 (arg4))<br />[/vs/workbench/api/common/extHostTypes.ts#1839:17 (construct)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTypes.ts#L1839:17 (construct))<br />[/vs/workbench/api/common/extHostTypes.ts#20:31](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTypes.ts#L20:31)<br />[/vs/workbench/api/common/extHostTask.ts#293:17 (to)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTask.ts#L293:17 (to))<br />[/vs/workbench/api/common/extHostTask.ts#612:51 (getTaskExecution)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTask.ts#L612:51 (getTaskExecution))<br />[/vs/workbench/api/common/extHostTask.ts#470:25 (apply)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/api/common/extHostTask.ts#L470:25 (apply))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#398:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L398:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#383:31](https://github.com/microsoft/vscode/blob/88f15d17dca836346e787762685a40bb5cce75a8/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L383:31)<br />	at p._receiveRequest (\out\vs\workbench\services\extensions\node\extensionHostProcess<br />

**Comment by alexr00** [comment]
@vscodeerrors what were you doing when this occurred?
Can you reproduce it? If you can reproduce it, does it happen when you disable extensions?
