### ISSUE TITLE
Web: Unable to open a workspace with absolute paths on windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82589]
Folders having absolute windows paths inside a workspace configuration file are not supported in web. 

Reply from @aeschli 

> Absolute path in workspace files can be formatted as be os paths (c:\ddd). To be able to correctly resolve that for remote workspaces, we need to pass the platform of the workspace file to toWorkspace
> 
> Agree that this needs to be fixed, but IMO using absolute paths in the workspace file is not recommended and should be avoided. From what I know, we always create relative paths if possible.

**Comment by aeschli** [comment]
@bpasero What do you suggest we do? 
How was that workspace file created? IMO that's the problematic point.

**Comment by bpasero** [comment]
@aeschli should have made clear, I only moved the issue. @lramos15 reported it. Maybe @sbatten and @sandy081 also have additional context. 

However, given that someone may just check in a workspace file to a repository with absolute paths, I guess we could always end up in that situation.

**Comment by sbatten** [comment]
Copied from previous issue:

@bpasero @aeschli I created my workspace file by saving workspace as and it used absolute paths.

To reproduce that on Windows, I open a folder in VS Code at C:\Users\sbatten\Source\folder then save the workspace as C:\Users\sbatten\Desktop\workspace.code-workspace

**Comment by aeschli** [comment]
@sbatten Can you verify? You know the setup.
