### ISSUE TITLE
Web: Can't switch keyboard layout on Linux

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82587]
If I select any of the Keyboard Layouts (Linux), it gets set at first in the status bar, but quickly goes back to us as soon as I type a non-alphanumeric character.

Reply from @rebornix 

> @joaomoreno thanks for this issue. I didn't test Linux thoroughly before but after digging into this one, many interesting findings and improvements are made.
> 
> Firstly, Auto Detect doesn't work for self host on Chrome/Linux, the reason is when running a website from static ip address, `navigator.keyboard` is not initialized, which means we can't get keymap info from browser. We didn't see this in other platforms and  I already created an issue for chromium https://bugs.chromium.org/p/chromium/issues/detail?id=978708
> 
> Since auto detect is not there, it should fall back to post key-event-detection but unluckily it didn't. The symptom is 
> 
> * Switch to German keyboard layout
> * Type `z`, keybinding service switches `de` successfully
> * Press backspace, it switches back to `us`, which is unexpected.
> 
> The reason for that is `backspace` key event info doesn't match the `de` keyboard layout info we generate from `node-native-keymap` (we should look into this issue in next iteration). Current logic switches back to `us` as it doesn't understand.
> 
> My fix for this one is whenever we find the best matched keymap, only replace the active one if it has higher score. In this case, `backspace` won't match anyone, so we stay with the current keyboard layout.
> 
> ---
> 
> For short, with latest Chromium on Linux, before the bug is fixed, no auto detect in web companion. It should behave the same as Safari on macOS.

**Comment by bpasero** [comment]
I can still reproduce this. Selecting another keyboard layout (e.g. FR) on Linux I get back to DE soon after typing.

**Comment by rebornix** [comment]
With the fix, we will not validate keyboard events as long as the keyboard layout is not `autodetect`. The keymap API is often wrong (for example, currently chromium returns US keymap when using German keyboard layout) so if we ever pick a keyboard layout ourselves, we should stick with it.

**Comment by rebornix** [comment]
Verifier:

Open VS Code in Web on Linux, switch to another keyboard layout (from the status bar, bottom right) and typing in the editor will not switch the keyboard layout.
