### ISSUE TITLE
Web: Support for translations/language packs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82595]
Currently we do not support switching display language in the web.

**Comment by yuxuan** [comment]
We currently mainly depend on  VSCode web. And our main language is not English. It would be great helpful to us if VSCode web can support localization on web. Thanks.

**Comment by jsjoeio** [comment]
Hi there!

I'm one of the maintainers of [coder/code-server](https://github.com/coder/code-server). We've (@code-asher and myself) modified our vscode fork to support changing the display language. Here is the PR: https://github.com/coder/vscode/pull/34

@TylerLeonhardt I see you're planning to look into this for Jan. 2022. Is this something we can help with?

**Comment by TylerLeonhardt** [comment]
@jsjoeio If I understand the change correctly, you essentially offload all translation handling to the remote side? Yeah this would be generally good for any "server-full" vscode offerings. If you would like to contribute a similar change, we'd love that!

That solution won't work for serverless environments like vscode.dev so we'll have to approach that differently.

**Comment by jsjoeio** [comment]
@TylerLeonhardt yes! Awesome. I'll see if I can get started on this next week.

**Comment by jsjoeio** [comment]
Heads-up. Some other priorities have come up and I haven't been able to get to this yet. I hope to soon, but if not, someone else feel free to tackle.

**Comment by Mister-Hope** [comment]
Emm, this issue title is hard to search, could we mention it in https://code.visualstudio.com/docs/getstarted/locales that it's not supported on the web yet and ask user to track this issue?

**Comment by TylerLeonhardt** [comment]
@gregvanl what are your thoughts on updating the doc that @Mister-Hope suggested?

**Comment by TylerLeonhardt** [comment]
@jsjoeio FYI, I may end up tackling the part that you did later this month (translations working when there's compute on the server side) because it's a feature we're looking to light up.

I just wanna let you know because I think it would be awesome to see this contributed by the community especially since you already did the work basically :) but also no pressure whatsoever. If you beat me to it, awesome. If not, totally fine of course!

**Comment by jsjoeio** [comment]
Oh awesome! 

I agree, it would be really cool for us to contribute that back :) Well, if I can squeeze it in this month, I will. Thanks for the heads-up!

**Comment by gregvanl** [comment]
Added mention that VS Code for the Web doesn't support Language Packs https://github.com/microsoft/vscode-docs/commit/da8ff664125b301f5b583c76b4cfbe3b49cb7da6

**Comment by TylerLeonhardt** [comment]
@jsjoeio I wasn't able to get to this and will try to pick it up next month. Feel free to grab it if you can :)

**Comment by jsjoeio** [comment]
@TylerLeonhardt buying me more time! Haha thanks for mentioning - going to see if I can squeeze it in for March's sprint 👀

**Comment by TylerLeonhardt** [comment]
One of these days, I promise lol

**Comment by jsjoeio** [comment]
Lol my feelings exactly. We're moving to a patches approach with https://github.com/coder/code-server/pull/4997 so it should be easier to start working on this next month 🤞🏼

**Comment by jsjoeio** [comment]
I started working on this but I'm having a hard time getting Code Web to run with Extensions. I don't want to blow up everyone's notifications so what's the best place to ask questions/get help/etc.?

**Comment by TylerLeonhardt** [comment]
@jsjoeio I think in your case you want to run server-full which is `./scripts/code-server.sh` instead of `code-web.sh` which is serverless.

My understanding of your change is that you defer translations handling to the remote side so in this case, we do need server-full experience.

**Comment by jsjoeio** [comment]
@TylerLeonhardt ahhh! Didn't realize that. That worked! Thank you. 

I'll update this comment to keep track of my notes

## Notes

Added VS Code Marketplace to `product.json` and searched for Spanish extension. I was able to install it successfully, but then it added the "Install in Browser" button even though it's technically installed. 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/3806031/159984791-def11107-302e-413c-b0ec-3b142a58a3a7.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3806031/159985184-e914a2b4-897e-47af-a3a4-5b906f771564.png">

**Comment by jsjoeio** [comment]
@TylerLeonhardt yes! Same way. I didn't author this patch so still understanding this patch as well but I am guessing that is from the `LocalizationService` we create [here](https://github.com/coder/code-server/blob/main/patches/display-language.diff#L221-L250)

@code-asher can correct me though

**Comment by jsjoeio** [comment]
@TylerLeonhardt I have a PR open ready for feedback! I ran into build issues so couldn't get the demo video in but maybe you can help (details in PR).

**Comment by code-asher** [comment]
Sorry for the late response.  The `Configure Display Language` command is contributed by importing  `localizations.contribution.ts`

https://github.com/microsoft/vscode/blob/6a6df96d5e276dc9586741d27d289beac0891957/src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts#L31-L32

Here is the import in the diff:

https://github.com/coder/code-server/blob/d796cc20e0cb6fa231173e93d8d2df654f8e7e40/patches/display-language.diff#L260

But using the command in web does not actually work as it writes to browser storage so the server has no access to it (`--locale` works though).  The way we "fixed" this was to write the `argv.json` file (and all user settings actually) to the server's disk instead.

**Comment by TylerLeonhardt** [comment]
@vmasse-gir that command is available in insiders.vscode.dev and will be in the next stable release.

**Comment by TylerLeonhardt** [comment]
:globe_with_meridians: :warning: :mega:  I have published a new version of [vscode-nls](https://github.com/microsoft/vscode-nls/pull/42) and merged in the PRs ([one](https://github.com/microsoft/vscode/pull/155355) and [two](https://github.com/microsoft/vscode/pull/157530)) into Core that should enable translations for the web for built-in extensions. I have also updated Azure Repos extension as the guinea pig to make sure this all works properly.

This means that at this point, all “feature bits” are done with translations for the web. We just have some bugs to iron out. Since those bugs are tracked in other issues I will close this now.

Tomorrow, all built-in extensions should be localized and the Azure Repos extension. If all goes smoothly, I'll start updating other extensions to take advantage of these changes.

**Comment by jsjoeio** [comment]
@TylerLeonhardt that's wonderful to hear! When will this be available in Core/Stable release?


(asking because that will allow us to remove our patch)

**Comment by TylerLeonhardt** [comment]
Unfortunately, I need to reopen this as we need to take a slightly different approach.

**Comment by vedg** [comment]
We need this feature for https://github.com/microsoft/vscode-dev/issues/477 as well.

**Comment by TylerLeonhardt** [comment]
With the new l10n API that has been finalized, this item is "done". https://github.com/microsoft/vscode/issues/164438 will track onboarding built-in extensions to the new API.
