### ISSUE TITLE
Web: Workbench layout/styling adjustments for browser and PWA

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82600]
This is to track the work to adjust the workbench layout/styling on the web (browsers and PWA):

- [x] Move menu bar into a custom menu for the web
- [x] Update title attributes on the Mac to include dirty states (only works on Win)

# Custom web menu
We'll start by using a custom menu above the activity that will match the styling of the sidebar title:

## Web
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/35271042/64638405-83cae200-d3ba-11e9-8a50-71b386484fcf.png">

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/35271042/64638418-8af1f000-d3ba-11e9-8b56-ceb69106d886.png">

## PWA 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/35271042/64638298-541bda00-d3ba-11e9-9f22-9903188aedea.png">

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/35271042/64638321-5d0cab80-d3ba-11e9-8800-505b6ad0a009.png">

**Comment by misolori** [comment]
Mac dirty state has been added for some quite time now so this wraps up the work for this item:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/35271042/67224433-04cbbf00-f3e6-11e9-952d-33a37c4651a7.png">
