### ISSUE TITLE
Hide certain launch configurations because they don't make sense without a compound

### ISSUE THREAD

**Issue by cstavaru** [microsoft/vscode#82609]
Hello everyone,

I have the following issue in several large(r) projects: 

There are a lot of different launch configurations, for example a frontend web site that launches Chrome with a certain URL which at a point in time calls a NodeJS web service started using another launch configuration. I have these set up in a compound so when the frontend starts, the backend web application also starts.

However, launching that specific web service without the frontend does not make sense for debugging purposes, so it would be nice to have an attribute like "display: false" on a launch configuration, specifying if the configuration should be displayed in the debug pane / launch configuration list. 

This would add a lot of sense to the (more and more extensive) launch configuration list shown in the debug pane for a large project, and new developers would more easily be able to start debugging the project.

Thanks !

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/82332
Since we plan to have a special `group: hidden` there
