### ISSUE TITLE
Get directory of VSCode for Portable Setup

### ISSUE THREAD

**Issue by weingaunity** [microsoft/vscode#82602]
Hi,
i try to create a portable bundle of VSCode with Arduino.

I try to set a relative arduino.path within the VSCode Arduino extension but i do not find any way to get a placeholder for the vscode-directors (in the example below:   C:\basedir\vscode).

I want the config "arduino.path":"${vscodepath}/../arduino".

${execPath} does not do the job, because it returns $C:\basedir\vscode\code.exe"

C:\basedir
    > vscode
         >code.exe
         > ....
    > arduino
         > arduino.exe
         > ....

Please give me an advice.

Thx. Klaus

**Comment by roblourens** [comment]
I don't understand what you are looking for exactly, what is `vscodepath` supposed to be?

**Comment by weingaunity** [comment]
As mentioned above.
${execPath}  is C:\basedir\vscode\code.exe

but i ned something like

${vscodepath} with C:\basedir\vscode

**Comment by roblourens** [comment]
Does this assume that arduino is installed next to vscode? I am not sure we should do this because I don't think extensions should make assumptions about the install location of vscode.

**Comment by weingaunity** [comment]
Yes, arduino is installed next to VSCode and it will be a portable bundle for our students.
Everything works fine except the relaive path to arduino relative to the vscode path.

Can you give me any advice to fix this?

Thx, Klaus

**Comment by roblourens** [comment]
You can use an absolute path to where Arduino is installed, or you can ask the Arduino extension for some support, for example if Arduino is installed in different places, they can detect the install directory.

**Comment by weingaunity** [comment]
Hi,we build a portable bundle that contains arduino, vscode and maybe some other tools in future and so i have to use relative pathes for the configuration. So arduino is not installed. It's just in the same parent directory as vscode.So there exists ${execPath}but the Code.exe at the end of the string makes it unusable for my usecase.I think this is a feature that may be required for a lot of usecases. Is there no way to get the directory path within the configs?Any advice?Klaus-------- Ursprüngliche Nachricht --------Betreff: Re: [microsoft/vscode] Get directory of VSCode for Portable Setup (#82602)Von: Rob Lourens An: microsoft/vscode Cc: weingaunity ,Author You can use an absolute path to where Arduino is installed, or you can ask the Arduino extension for some support, for example if Arduino is installed in different places, they can detect the install directory.

**Comment by weingaunity** [comment]
Hi,

we build a portable bundle that contains arduino, vscode and maybe some other tools in future and so i have to use relative pathes for the configuration.

So arduino is not installed. It's just in the same parent directory as vscode.

So there exists ${execPath} but the Code.exe at the end of the string makes it unusable for my usecase.

I think this is a feature that may be required for a lot of usecases. Is there no way to get the directory path within the configs like

"arduino.path":"${vscodedir}/../arduino"

Any advice?

Klaus
