### ISSUE TITLE
debug doesn't show completion

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8260]
* have the snippet below (`npm i github`)
* run on the console `node app.js` it terminates quickly
* run the same with the generated launch config and the stop/resume control keep showing

![jun-28-2016 11-04-39](https://cloud.githubusercontent.com/assets/1794099/16409963/6ff2e644-3d20-11e6-9748-179c15f94e77.gif)

```
'use strict';

const GitHubApi = require("github");
const github = new GitHubApi({
    // debug: true 
});

github.issues.getForRepo({
    user: 'Microsoft',
    repo: 'vscode',
    milestone: 20,
    labels: 'testplan-item'
}, function (err, res) {
    for (let item of res) {
        console.log(`- [${item.state === 'open' ? ' ' : 'x'}] ${item.title}, #${item.number}`)
    }
});
```

**Comment by isidorn** [comment]
I think this is designed node behavior that it does not exit in this case. Forwarding to @weinand to decide.

**Comment by weinand** [comment]
This is a node bug: https://github.com/Microsoft/vscode/issues/5831
You will see the same behaviour with node-inspector.
