### ISSUE TITLE
Web: support selection clipboard

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82603]
It looks like we have an editor contribution for selection clipboard that on Linux copies to the selection clipboard each time you make a selection.

On Web, we ignore the `type` parameter and blindly write into the normal clipboard, overwriting whatever was there.

I pushed https://github.com/microsoft/vscode/commit/40b5ba9cf24e344db916a5ab65e79ca4b3b636fa to ignore read/writes when type is provided. 

Ideally I think that we should either:
* find out if this clipboard type can be supported in the web
* or remove this contribution from `browser` and move it to `electron-browser`

**Comment by alexandrudima** [comment]
From my reading the w3c spec, it does not appear to cover the selection clipboard. If it will cover it, we can add this back and adopt the w3c spec, in the meantime I have refactored how editor contributions work such that simple inputs (like the repl) will get the SelectionClipboard contribution in the rich client and will not get it in the web client...

**Comment by bpasero** [comment]
@alexandrudima can you explain what to verify here?

**Comment by alexandrudima** [comment]
Sorry about that, the complexity comes from the `SelectionClipboard` being used by inputs which ship on the web ui (like settings search input box, debug repl), and on the web ui the `SelectionClipboard` should not be available, but it should continue to work fine under the rich client. Detailed verification steps:

---

#### `SelectionClipboard` controller does not ship in the web ui
- open the web ui
- check that `SelectionClipboard` (`src/vs/workbench/contrib/codeEditor/electron-browser/selectionClipboard.ts`) is not loaded in the web ui

---

#### `SelectionClipboard` controller is working on simple inputs that ship in the web ui when running on desktop linux
- open the rich client on linux
- check that you can select text in the settings search input box and in the debug repl (they both use an editor behind the scene) and that the text is placed in the selection clipboard. You can use middle click in another editor on linux to check that it works correctly.
