### ISSUE TITLE
Web: editor does not provide a "Paste" action

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82604]
Since we now have the `IClipboardService` in the web, I think we should offer the Paste command.

![image](https://user-images.githubusercontent.com/900690/63093149-5c702900-bf64-11e9-8263-0280b926b35a.png)

**Comment by tikaro** [comment]
I was mystified by the absence of "paste" in the context menu in VS Code Online, and after I opened https://github.com/MicrosoftDocs/vsonline/issues/299 , jkeech discovered this issue.  Yes! I, for one would love to see this.

**Comment by bpasero** [comment]
I looked a bit into this and sketched up a possible solution using the `IClipboardService`. It is a bit hacky though and I have not yet figured out how to support multi-cursor, but I suggest to continue in a PR.

**Comment by bpasero** [comment]
**Verification:** run web and verify you see a `Paste` action in the context menu of the editor that does what it tells. It should also work with multi-cursor.

**Comment by aeschli** [comment]
Works on Chrome, but not yet on Firefox. Let me know if we need an issue for that.

**Comment by bpasero** [comment]
We have https://github.com/microsoft/vscode/issues/84084
