### ISSUE TITLE
Extensions should be allowed to define a light icon and a dark icon,

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8261]
Testing #8215 

Because a single icon might not work good for both.

Examples:

![image](https://cloud.githubusercontent.com/assets/5047891/16410050/e3174976-3d20-11e6-8221-5a09036d2e9a.png)

**Comment by isidorn** [comment]
Agree, feature request, july, assinging to joao

**Comment by joaomoreno** [comment]
I don't think we have control over this.

@modigrv any ideas here?

**Comment by modigrv** [comment]
Marketplace currently expects only one icon type. There is no way to specify any other icon.
I will convey this up with Marketplace PM to see what can be done here.

**Comment by joaomoreno** [comment]
Likely won't happen. Also haven't received any feedback about this from actual extension authors.
