### ISSUE TITLE
Move Panel Right destroys webview content

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#82619]
Steps to Reproduce:

1. Create a markdown file
1. Add some markdown
1. Open the preview
1. Goto View | Move Panel Down/Right

Expected result:
Preview pane is still rendering after moving

Actual result:
Preview pane is empty.

**Comment by mjbvz** [comment]
Oh actually was able to hit this

**Comment by mjbvz** [comment]
This is caused by the dom node getting re-parented during this operation

**Comment by JacksonKearl** [comment]
@mjbvz  How did you hit this?

**Comment by mjbvz** [comment]
1. Open a webview (such as md preview)
1. Open terminal below.
1. Move the terminal panel to the right
