### ISSUE TITLE
Menubar apparence text is same as disabled

### ISSUE THREAD

**Issue by Xarkam** [microsoft/vscode#82618]
Issue Type: <b>Bug</b>

I'm under Kde Neon and the menubar apparence text is same as disabled:
![image](https://user-images.githubusercontent.com/331816/66849098-a1213c00-ef76-11e9-8bd2-c85c75f30759.png)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3298)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.58GB (7.13GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by sbatten** [comment]
I can reproduce this in electron fiddle so it is not specific to VS Code. Either electron is pulling the wrong theming keys or KDE is not setting them properly. /cc @deepak1556
