### ISSUE TITLE
Touchbar debug doesn't work anymore

### ISSUE THREAD

**Issue by galvesribeiro** [microsoft/vscode#82616]
Issue Type: <b>Bug</b>

After the latest update VSCode debug buttons (play, stop, step-into, step-over, step-out) on Macbook Pro touchbar doesn't work anymore.

To repro:

1. Run a project (I've tried .Net Core) - Funny enough, the play button on the touchbar start the debug process
2. Try to step into or over a method on a breakption

Expected result: 

It should move the debugger forward as usual

Actual result:

Nothing happens. It only work if I press F10/F11.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (1.49GB free)|
|Process Argv|-psn_0_1085705|
|Screen Reader|no|
|VM|15%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
chromium-codesearch|cha|0.0.7
systemd-unit-file|coo|1.0.5
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
vscode-pull-request-github|Git|0.12.0
docomment|k--|0.1.8
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.19.0
vscode-docker|ms-|0.8.1
vscode-service-fabric-reliable-services|ms-|0.1.6
vscode-kubernetes-tools|ms-|1.0.4
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.6
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
Go|ms-|0.11.7
powershell|ms-|2019.9.0
debugger-for-chrome|msj|4.12.0
vscode-gn|npc|1.1.0
vscode-gnformat|per|0.0.3
java|red|0.50.0
vscode-yaml|red|0.5.3
bash-beautify|sha|0.1.1
msbuild-project-tools|tin|0.2.55
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.9
azure-iot-edge|vsc|1.17.0
azure-iot-toolkit|vsc|2.11.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.5.1
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1

</details>

**Comment by isidorn** [comment]
Fixed in latest. So just update and it should work. Thanks

**Comment by galvesribeiro** [comment]
I just got the update today and I can confirm it is working now.

Thank you all!
