### ISSUE TITLE
Cannot enable themes

### ISSUE THREAD

**Issue by CloudSecuritySmith** [microsoft/vscode#82610]
Issue Type: <b>Bug</b>

Get a "Cannot read property 'id' of undefined" error when trying to enable any theme. 

Have tried uninstall (including clearing theme and settings files from disk) and restart several times. Only get error once I try to enable a theme.

Installing other extensions appears to work as expected but any theme, on a fresh install, results in the error.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (25.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.41019

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Do you see a full stack trace in the developer tools? (Help > Toggle developer tools)

**Comment by CloudSecuritySmith** [comment]
`notificationsAlerts.ts:38 TypeError: Cannot read property 'id' of undefined
    at o.some.e (extensionsActions.ts:1305)
    at Array.some (<anonymous>)
    at e.run (extensionsActions.ts:1305)
    at t.ActionRunner.runAction (actions.ts:216)
    at t.ActionRunner.run (actions.ts:208)
    at p.onClick (actionbar.ts:168)
    at Immediate.options.options.isMenu.i.setImmediate (actionbar.ts:138)
    at runCallback (timers.js:694)
    at tryOnImmediate (timers.js:665)
    at processImmediate (timers.js:647)
`

Above is the output from the developer tools. This is after a fresh install with previous extensions and settings removed. Get same error regardless of the theme I try to install.

**Comment by AJStacy** [comment]
I too am experiencing this.

**Comment by rustiphyde** [comment]
Me as well...it keeps reverting back to "Default Dark+" even when I delete the settings.json file and replace it with a brand new one that I code myself to have the color theme be anything other than "Default Dark+" it still changes the content of that settings.json file to have the theme be "Default Dark+". Somewhere someone must have broke the code during the last update.

**Comment by rustiphyde** [comment]
Why do people keep closing these issues when it obviously isn't resolved?

**Comment by gjsjohnmurray** [comment]
> Why do people keep closing these issues when it obviously isn't resolved?

This one hasn't been closed. Others that are duplicates have been as part of issue management procedures.

**Comment by sandy081** [comment]
Steps to repro:

- Open Settings and set theme to a random value that does not exist
`"workbench.colorTheme": "abcd"`
- Open Extension Viewlet and make sure you have any theme extension installed
- Click on the gear icon of the theme extension and Select `Set Color Theme` action
🐛 "Cannot read property 'id' of undefined" error appears
