### ISSUE TITLE
HTML comments not marked as comments in JavaScript

### ISSUE THREAD

**Issue by RadiatedMonkey** [microsoft/vscode#82612]
- VSCode Version: 1.39.1
- OS Version: Windows 10 Pro 10.0.18362 Build 18362

Steps to Reproduce:

1. Create an HTML comment in a JavaScript file, 
Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Why is that wrong? That is not valid javascript

**Comment by NotWearingPants** [comment]
@roblourens try it in a browser and then try it in node.js and then reopen this issue.
You are wrong.

This issue should be reopened, HTML comments are valid JS.

**Comment by NotWearingPants** [comment]
I have reported this issue in the relevant repo: microsoft/TypeScript-TmLanguage#781

**Comment by roblourens** [comment]
OMG. You're right. Will reopen but I still feel like this would fall out of scope...

**Comment by mjbvz** [comment]
See discussion on if this is really part of JavaScript: https://github.com/microsoft/TypeScript/issues/10512#issuecomment-242205893


While node supports these comments this is likely only as a legacy of it using V8. Our TypeScript tooling does not support or understand them, and [the request](https://github.com/microsoft/TypeScript/issues/10512) has accumulated a total of 5 upvotes over the past three years

Closing as out of scope for normal js/ts files

**Comment by NotWearingPants** [comment]
This has nothing to do with any engines or implementations such as V8, node.js, or TypeScript.

This is to do with existing JS files that use this syntax whether you like it or not, and vscode wrongly detects it as a syntax error, in contrast to the ECMAScript spec.
