### ISSUE TITLE
Zen Mode doesn't show unsaved changes to files

### ISSUE THREAD

**Issue by jermainerf** [microsoft/vscode#82625]
Issue Type: <b>Bug</b>

Zen Mode doesn't show the little white circle that indicates unsaved changes to files.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by noeRls** [comment]
Hi, I'm taking a look at this one, if anyone can give me some code pointers it would be a great help ;)

**Comment by isidorn** [comment]
Zen mode shows it for me in the top right corner you can see a black dot
If you want to see the activity bar while you are in zenMode, you should use 
	`"zenMode.hideActivityBar": false` 
And make sure to toggle zen mode after changing this setting

![Screenshot 2019-10-16 at 10 58 08](https://user-images.githubusercontent.com/1926584/66904152-e6d81600-f003-11e9-9e1e-544a4bee7174.png)


Let me know if I did not cover your issue with this and we can reopen this issue. Thanks
