### ISSUE TITLE
"The specified task cannot be tracked"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82621]
I got this error while trying to set up a task to run when a debug config is started, and was very confused. I had to google the message and read some vscode issues. I think it could explain the problem some more, or point to this doc section: https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks

**Comment by roblourens** [comment]
Also, now I get the error _sometimes_ but not all the time. I think just when the task is already running. Example task:

```
		{
			"type": "npm",
			"script": "web",
			"label": "Run web",
			"isBackground": true,
			"problemMatcher": {
				// This section to make error go away when launching the debug config
				"pattern": {
					"regexp": ""
				},
				 "background": {
					 "beginsPattern": ".*node.*",
					"endsPattern": "Web UI available at .*"
				}
			},
			"presentation": {
				"reveal": "never"
			}
		},
```

Can you explain how to set this up? I just want to run "npm run web" then run a launch config, and I have absolutely no idea how to do that.

**Comment by isidorn** [comment]
This error message happens when we do not get `taskStarted` event from the `taskService`. Thus meaning that the task can not be tracked. However why that is and what needs to be changed in your tasks.json, I am not sure and I am leaving that up to @alexr00

**Comment by alexr00** [comment]
@roblourens your task and launch config work great for me. I did command palette -> Run Task -> Run web to start the task since your issue is running launch config when the task is already running.
Then I ran the launch config. 

Am I doing something different from what you are doing?

**Comment by alexr00** [comment]
I think I see what is happening now.

After the web UI is working for a bit I got some errors in my task terminal from the Run web task:
```
Error: ENOENT: no such file or directory, stat 'D:\repos\Microsoft\vscode\remote\web\node_modules\vscode-textmate\release\main.js.map'
```
This matches your begins pattern. So now the task hasn't "completed" enough for the launch since the ends pattern hasn't matched again.

If you make the beginsPattern more specific so it doesn't match to that terminal line you should be good to go.

**Comment by alexr00** [comment]
I made the beginsPattern slightly more specific to confirm that this was the problem and pushed the change since that appears to have been the only issue.

**Comment by roblourens** [comment]
Oh I see, thanks. The bigger problem here is that I don't want a begins and ends pattern, I want one pattern that is triggered when the server starts listening, and then it never leaves the "completed" state after that. Is there any way we can make one of the patterns optional, or make it easier to write a simpler version? Is there an issue for that already?

**Comment by alexr00** [comment]
There isn't a way to do that, but there is an `"activeOnStart"` that gets us halfway there. I think it `"activeOnStart":true` then the beginsPattern could be made optional.
