### ISSUE TITLE
Pass args to npm tasks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82626]
I want to write an npm task and pass some args, but it doesn't look like this is possible. 

I tried

```
"type": "npm",
"script": "web -- --no-launch",
```

and it ran the task but the arg was lost. But this works:

```
"type": "shell",
"command": "yarn web -- --no-launch",
```

**Comment by alexr00** [comment]
@egamma FYI since this is in the npm extension. I'd be happy to accept a PR to add an `args` property to npm tasks that `resolveTask` knows how to handle.

**Comment by sohailrajdev97** [comment]
@alexr00, this looks similar to the one added in #82819. So, can I take this up ?

**Comment by alexr00** [comment]
@sohailrajdev97 go for it!

**Comment by sohailrajdev97** [comment]
@alexr00. Passing arguments to npm scripts works as-it-is in the current release. The steps which I followed to reproduce the issue are:

1. Created a npm script which executes a grunt task to echo some text (received as argument) on the console as below:
```
"scripts": {
    "hello": "grunt echoFromArgs"
  }
```

2. Defined a task in tasks.json as below:

```    
{
      "label": "Say Hi To Bob via npm",
      "type": "npm",
      "script": "hello -- --name=Bob"
}
```

3. The Gruntfile is as below:

```
module.exports = grunt => {
    grunt.loadNpmTasks('grunt-shell');
    grunt.initConfig({
        shell: {
            greet: {
                command: name => `echo Hi ${name || "Anonymous"} !`
            }
        }
    });
    let nameFromCLI = grunt.option("name") || "Anonymous";
    grunt.registerTask('echoFromArgs', [`shell:greet:${nameFromCLI}`]);
}
```

The output of the above steps is as expected. `Hi Bob !`

I have pushed the sample code to a repository [here](https://github.com/sohailrajdev97/grunt-sandbox)

**Comment by roblourens** [comment]
Now it seems to work. I'm not sure what I saw, sorry.
