### ISSUE TITLE
Markdown: preview opens to the side when being opened from tab context menu

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8262]
Refs: https://github.com/Microsoft/vscode/issues/7945

I would expect it to open on the same side unless I press the modifier key and click (note that support for detecting the pressed key for context menus is coming in future versions of electron).

**Comment by jrieken** [comment]
@bpasero Any other markdown'ish editor that you open or does this happen when nothing is open?

**Comment by bpasero** [comment]
Just one open:

![untitled](https://cloud.githubusercontent.com/assets/900690/16410854/b1579450-3d24-11e6-9162-5be7de8fd0ca.gif)

**Comment by jrieken** [comment]
yeah, should not be like that...
