### ISSUE TITLE
GNOME animation settings is ignored

### ISSUE THREAD

**Issue by taka-hkd** [microsoft/vscode#82637]
As the title says, code shows animation regardless of the GNOME setting. This is annoying when the Linux instance is used via xrdp, in which case RDP requires much more bandwidth, therefore, the instance is slowed down for users with a slow connection like tethering.

- VSCode Version: Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-1020-gcp

- OS Version: Ubuntu 18.04 on Google compute engine

Steps to Reproduce:
1. Install vscode on Ubuntu 18.04 with gnome installed
2. Turn animation off with "gsettings set org.gnome.desktop.interface enable-animations false" from the terminal
Vscode is expected to work without animation. Especially, animation with right-click should be disabled.

**Comment by bpasero** [comment]
@taka-hkd 

> Vscode is expected to work without animation. 

Where exactly should animation not show where it currently shows? Opening a context menu?
