### ISSUE TITLE
onDidOpenTextDocument fired incorrectly & with the wrong Uri scheme

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#82636]
Version: 1.40.0-insider
Commit: ceeb587991f647659d42a82f87acf3d9778b4d0e
Date: 2019-10-14T10:18:06.503Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

**First setup test data**
1. Open a workspace with a file named `abc.ipynb` that has been commited in a git repo.
2. Edit the above file to ensure it is marked as dirty.

**Debug extension to replicate issue**
1. Create a new extension (`yo code`)
2. Add a handler to `vscode.workspace.onDidOpenTextDocument` and display the `uri` as follows:
```typescript
vscode.workspace.onDidOpenTextDocument(e=> vscode.window.showInformationMessage(e.uri.toString()));
```
3. Configure the above extension to activate always
4. Debug the above extension
5. Go into `Source Control` activity bar
6. You'll see the file `abc.ipynb` has changes.
7. Click on this file
    * On Mac, we'll get events fired for `onDidOpenTextDocument` with a uri = `git://.....`
    * On Windows, we'll get events fired for `onDidOpenTexxtDocument` with uri = `file://` **and** `git://`

The bug is in Windows.
We didn't open the file, we only opened the diff view, but VS Code is firing an event for text document opened with **uri = `file://`**

There seem to be other bugs in mac and windows:
* Open file explorer, and click on the file `abc.ipynb`
* You'll have two events fired for `onDidOpenTextDocument` event thought we opened one document!
    * First event `uri = 'file://`
    * Second event `uri = 'git://`

Bug, why is a second event fired for a document opened with a uri = `git`. This isn't right. we didn't open such a text document. Why is the uri = `git` when the file is opened from the file explorer view.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by joaomoreno** [comment]
@jrieken I don't know why on Windows you'd get one extra event. I also don't know why `onDidOpenTextDocument` is fired just by creating a text model. We need to create a text model to compute diffs, btw.

**Comment by jrieken** [comment]
> I also don't know why onDidOpenTextDocument is fired just by creating a text model

You should, you are causing it. A text document is a text model and that is not an editor.

**Comment by joaomoreno** [comment]
@jrieken Hmm maybe I'm misunderstanding something. I'm just using `createModelReference` (just like References et al) and I use the URI of the model to compute a diff. The dirty diff editor doesn't really open a file. :thinking: 

https://github.com/microsoft/vscode/blob/be68a4e14c28cc81cdf422739af23123b3c91fd2/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1082-L1095

I can debug it and try to figure out where it's coming from.

**Comment by jrieken** [comment]
Yes, in API lingo you "open a text document". Nothing new or wrong here and actually the reason why `git:///`-resources have a different file suffix. It's just that extension authors are often surprised by this. The [doc](https://github.com/microsoft/vscode/blob/6b0613aabacbce9dc8e96360288706c41d0345bd/src/vs/vscode.d.ts#L8109-L8120) tries to explain this but it seems hard to understand or isn't read much

**Comment by joaomoreno** [comment]
@jrieken There are two things reported here. You seem to be talking about the  second one, which we all know about and decided to live with it: events firing for `git://` documents.

I'm talking about the first one: extra event on Windows only.

**Comment by jrieken** [comment]
> I'm talking about the first one: extra event on Windows only.

Yeah, that's on your plate but `createModelReference` does create a text model and therefore fires said event unless the model already exists. Maybe that's different on windows 🤷‍♂

**Comment by joaomoreno** [comment]
Actually @DonJayamanne I don't understand. It **is** expected for you to get **two** events: one for `git://` (left side) and one for `file://` (right side). Can you reconfirm that one macOS you only get one event?

**Comment by joaomoreno** [comment]
> On Mac I get two events fired and both are git

Are you sure you're not comparing between a staged change (mac) vs an unstaged change (windows)?

**Comment by DonJayamanne** [comment]
Ahh yes, thats correct. Apologies for taking you on a wild goose chase.
