### ISSUE TITLE
Live Share collaboration not working on VSCode

### ISSUE THREAD

**Issue by rasavant-ms** [microsoft/vscode#82635]
Issue Type: <b>Bug</b>

VS Live Share does not let collaborators debug and does not let me change settings to enable this. This is the error message seen - Unable to write to Workspace Settings because liveshare.allowGuestTaskControl is not a registered configuration.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.22.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azurefunctions|ms-|0.19.0
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
vscode-logicapps|ms-|0.2.18
mssql|ms-|1.6.0
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
vscode-node-azure-pack|ms-|0.0.9
vsliveshare|ms-|1.0.950
azurerm-vscode-tools|msa|0.7.0
azure-iot-toolkit|vsc|2.11.0

</details>

**Comment by roblourens** [comment]
Please file this on the live share repo, thanks.
