### ISSUE TITLE
vscode.extensions.all only gives extensions running on the same machine

### ISSUE THREAD

**Issue by ChaosinaCan** [microsoft/vscode#82633]
Issue Type: <b>Bug</b>

To work around #21839, I am working on an extension that can install other extensions from a private server for extensions internal to my company that cannot be published to the public marketplace. 

To check for updates, I need to be able to see which extensions are installed so I can compare them to the versions available on the server. When I am using a local workspace, `vscode.extensions.getExtension()` works perfectly for this, but when I am connected to a Linux machine with the Remote SSH extension, no extensions with `extensionKind: ExtensionKind.UI` show up in `vscode.extensions.all`, nor will `vscode.extensions.getExtension()` return any information for these extensions. This makes it impossible to me check for updates to UI extensions such as code snippet packages and custom language support extensions.

I am using the `workbench.extensions.installExtension` command to install extensions, and it correctly determines whether to install extensions on the local or remote machine, so it seems like I should be able to see information about both local and remote extensions. I don't expect to be able to use parts of the API such as `Extension.exports`, but I do expect to be able to see whether each extension is installed regardless of where it is installed, and ideally to read its `packageJSON` so I can see its version (though if this is not possible I can simply tell the user that I can't check check this extension for updates when in a remote workspace). If I can only see `ExtensionKind.Workspace` extensions when in a remote workspace, then the `Extension.extensionKind` API does not seem particularly useful.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (12.97GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2B10.30.192.26/home/spadin/projects/redacted|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.30.192.26|
|OS|Linux x64 4.15.0-65-generic|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 800)|
|Memory (System)|31.31GB (1.16GB free)|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
xml|Dot|2.5.0
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
json-tools|eri|1.0.2
prettier-vscode|esb|2.3.0
bitbake|Eug|1.1.2
tabsanity|jed|0.0.11
svg|joc|1.0.2
bash-ide-vscode|mad|1.3.3
rainbow-csv|mec|1.3.1
git-graph|mhu|1.17.0
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
vscode-typescript-tslint-plugin|ms-|1.2.2
config-defaults|spa|1.1.0
rewrap|stk|1.9.1
git-commit-helper-vscode|tre|1.0.1
better-align|wwm|1.1.6
arm|dan|0.5.0
javascript-ejs-support|Dig|1.1.3
tsl-problem-matcher|eam|0.0.4
vscode-peacock|joh|3.1.5
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
vscode-icons|vsc|9.4.0

</details>

**Comment by ChaosinaCan** [comment]
It appears that vscode inferred my extension to be a workspace extension. If I set `"extensionKind": "ui"` in my package.json to force my extension to run locally, then `vscode.extensions.all` only shows UI extensions and provides no info about extensions running in the remote workspace.

To summarize, when using remote development, `vscode.extensions.all` only shows extensions running on the same machine as the executing extension. A UI extension cannot see extensions in the remote workspace, and an extension in the remote workspace cannot see UI extensions.

**Comment by alexandrudima** [comment]
You are correct.

This is done intentionally in order to not break existing extensions. Extensions can "reflect" via the `extensions.all` API only on extensions that run or would run (once activated) on the same machine, mainly due to our existing API `Extension.exports`.

In this case affecting your sync/management extension, perhaps the best way to tackle this is to distribute two extensions, one with `"extensionKind": "ui"` and one with `"extensionKind": "workspace"` and have each one operate on the set of extensions they can access.

Alternatively, you can mark all of the company extensions as `"extensionKind": "workspace"` and then you know for a fact that they will all run remotely and you don't need to manage in any special way the UI extensions.

**Comment by ChaosinaCan** [comment]
Thanks. I think it would still be nice if the extensions API exposed info about extensions on the other machine, but I think we can fairly easily make a second extension that implements commands to let the main extension ask about extensions on the other machine.

Then we can just do something like:

```typescript
// workspace extension
if (vscode.env.remoteName && extension.extensionKind == ExtensionKind.UI) {
    return await vscode.commands.executeCommand('otherExtension.getPackageJSON', extension.id);
} else {
    return vscode.extensions.getExtension(extension.id)?.packageJSON;
}

// ui extension
vscode.commands.registerCommand('otherExtension.getPackageJSON', id => {
    return vscode.extensions.getExtension(id)?.packageJSON;
});
```
