### ISSUE TITLE
"rename symbol" ignores file:excludes in settings

### ISSUE THREAD

**Issue by frostius** [microsoft/vscode#82638]
- VSCode Version:1.39
- OS Version:Win 10

Steps to Reproduce:

1.  Create a project that has an excluded symlink folder that points to a shared folder
2. Modify a file that is both visible to the project and also in the excluded symlinked folder (doesn't happen when the file has not been modified)
3. Rename a symbol
4. A second copy of the file with the symlink path will be opened and modified

Extra credit: sometimes rename causes *hundreds* of files to be opened and matching symbols renamed.  Don't know how to duplicate it, but I'm hoping its related.

![rename](https://user-images.githubusercontent.com/3818866/66873724-b018e600-ef98-11e9-9e45-fcbab45076eb.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by frostius** [comment]
@mjbvz Just tried to reproduce it on 1.39 before trying it on insider.  When I tried (on 1.39), I got "can't rename this symbol".  I restarted and was able to rename but can't reproduce the bug.   It frequently renames the symbol in all files in my project instead of being limited to the current function of the file.  

Happens so frequently I generally avoid using the rename symbol.  If you have any suggestions for troubleshooting, I'd be happy to help

**Comment by mjbvz** [comment]
Can you please try with [all extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) too

**Comment by frostius** [comment]
@mjbvz  I'll run with "all disabled" this week and see if I can find a repeatable sequence.

**Comment by frostius** [comment]
@mjbvz 
Updated to 1.39.2 and spent the week failing to reproduce (had extensions enabled).  Either it got fixed after 1.39 or there's something that triggers it that I haven't done in the last week.  Feel free to close it and I'll repost if happens again

**Comment by mjbvz** [comment]
Thanks for testing. Closing for now but let me know if you see this again
