### ISSUE TITLE
"Move Caret Left/Right" commands act very weird and should be removed

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82631]
The "Move Caret Left" and "Move Caret Right" commands act very very weird and seem broken.

They are very misleading - I opened the Command Palette and searched for "left" to find the command `cursorLeft`. I found "Move Caret Left", and assumes it was `cursorLeft`, but it wasn't.

Issue #51054 is a good example of a user getting confused when encountering those commands.

What these commands do is also very unintuitive and they behave differently in different situations.
Either they are implemented very badly, or I'm missing something.

I believe they should be removed to prevent confusion and also because they don't do anything useful it seems.

---

## Examples of different weird behaviors:

-
  1. Type <kbd>hello</kbd>
  2. Run the "Move Caret Left" command - `hell` is selected for some reason

-
  1. Type <kbd>hello</kbd>
  2. Move left one character by pressing <kbd>Left</kbd>
  3. Run the "Move Caret Left" command - the cursor moves left one more character
  4. Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> - the text didn't change, but it is still undo-able for some reason

-
  1. Type <kbd>hello</kbd>
  2. Select the `o` with <kbd>Shift</kbd>+<kbd>Left</kbd>
  3. Run the "Move Caret Left" command - the selection moves left, resulting in `helol`

-
  1. Type <kbd>hello</kbd> and <kbd>world</kbd> in different lines
  2. Place a cursor on each line with <kbd>Ctrl</kbd>+<kbd>A</kbd> followed by <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>
  3. Select the `o` in `hello` and the `d` in `world` by pressing <kbd>Shift</kbd>+<kbd>Left</kbd>
  4. Run the "Move Caret Left" command - both of the selections move left, resulting in `helol` and `wordl`

-
  1. Type <kbd>what what</kbd>
  2. Select both `a`s by pressing <kbd>Left</kbd>, <kbd>Shift</kbd>+<kbd>Left</kbd>, <kbd>Ctrl</kbd>+<kbd>D</kbd>
  3. Run the "Move Caret Left" command - only one selection moves left this time, resulting in `what waht`

---

- VSCode Version: 1.39.1
- OS Version: Windows 10
- Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I agree that the implementation was not very good. A lot of these weird cases now work better with 811c4b5552e4165262cb25eeb6480e04c295bd9a.

The commands are about moving the selected text left or right. I will rename them to "Move selected text left" and "Move selected text right".
