### ISSUE TITLE
Inno_updater.exe -Entry Point Not Found

### ISSUE THREAD

**Issue by Vesvold** [microsoft/vscode#82645]
When i click on update now it just gives me this error 
The procedure entry point terminate could not be located in the dynamic link library
C:\Users\username\AppData\Local\Programs\Microsoft Vs Code\tools\VCRUNTIME140.dll.

I have attached the screenshot of error too.

- VSCode Version: 1.35.1 (user setup)
- OS Version: Windows 8.1 Pro 64-bit (6.3 , Build 9600)

Steps to Reproduce:

1. After Clicking Update Now 

2. ![Capture](https://user-images.githubusercontent.com/41279301/66883347-7a690280-ef82-11e9-9e0e-ec1005d53638.PNG)

Does this issue occur when all extensions are disabled?:  Yes

**Comment by roblourens** [comment]
Can you uninstall and reinstall vscode instead?

**Comment by Vesvold** [comment]
Worked after reinstalling.
Thanks
