### ISSUE TITLE
Markdown: links not colored when indented

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8264]
Refs: https://github.com/Microsoft/vscode/issues/7945

![image](https://cloud.githubusercontent.com/assets/900690/16410166/7e476a48-3d21-11e6-9018-0485fd793c9e.png)

**Comment by bpasero** [comment]
I am still seeing this with latest:

![image](https://cloud.githubusercontent.com/assets/900690/18913816/48eddace-858a-11e6-85f6-068d44286106.png)

**Comment by mjbvz** [comment]
@bpasero How many spaces is the indent? If it's 4 or more, then the text becomes a code block which will not be highlighted

**Comment by bpasero** [comment]
@mjbvz this was one Tab. My original bug report was likely also doing that.

**Comment by mjbvz** [comment]
@bpasero Take a look at the markdown preview and see how the text is rendered. Our highlighting tries to match what it does.

Content indented using either a four space tab or a literal tab both render as code blocks in my testing:

![screen shot 2016-09-28 at 10 39 08 am](https://cloud.githubusercontent.com/assets/12821956/18925200/d424109a-8567-11e6-8184-b384cab2d68a.png)

**Comment by bpasero** [comment]
Ok. Just fyi here is how Atom renders it:

![image](https://cloud.githubusercontent.com/assets/900690/18941792/406924aa-8614-11e6-9ddf-ea324194ce11.png)

**Comment by mjbvz** [comment]
As long as there are four spaces in front of the link, this behavior is expected:

```md
- VSCode Version:
- OS Version:

Steps to Reproduce:

    [foo](aaa)
```

Here's the preview we show:

![screen shot 2016-11-11 at 2 51 51 pm](https://cloud.githubusercontent.com/assets/12821956/20232623/637cd032-a81e-11e6-8cf6-2eb904357fe9.png)

And here's how github renders it:

![screen shot 2016-11-11 at 2 51 34 pm](https://cloud.githubusercontent.com/assets/12821956/20232609/56cc8db4-a81e-11e6-977a-ef35edf7dca5.png)


Atom is incorrect in this case.
