### ISSUE TITLE
Debugger doesn't work on macOS

### ISSUE THREAD

**Issue by Stormwaker** [microsoft/vscode#82640]
- VSCode Version: 1.39.1
- OS Version: macOS 10.15

Steps to Reproduce - follow this tutorial: https://code.visualstudio.com/docs/cpp/config-clang-mac

Here is repository with the files I created following the tutorial: https://github.com/Stormwaker/VSCode

No matter how many breakpoints I set, code runs from beginning to end without stopping.

**Comment by roblourens** [comment]
Please file this on the repo for the c++ extension - https://github.com/microsoft/vscode-cpptools
