### ISSUE TITLE
Update Chokidar to 3.2.2

### ISSUE THREAD

**Issue by paulmillr** [microsoft/vscode#82646]
1. The performance was improved once again. 50% improvement in low-level readdirp. 50% RAM usage decrease on Linux.
2. Fixes fsevents getting stuck on resource-starved CPUs
3. Stability improvements: now using tight dependency versions
4. Fixes various race conditions on all platforms that can happen when closing or re-opening chokidar instances.

**Comment by bpasero** [comment]
Thanks, will give it a try 👍

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/82686
