### ISSUE TITLE
[Bug] ipynb debugger stack trace shows incorrect version of imported external code

### ISSUE THREAD

**Issue by silverNitrateIon** [microsoft/vscode#82641]
Noticed that the stack-trace for the ipynb extension appears to output the wrong version of the packages loaded when it encounters an error. [I've attached an example of the issue which I found.
](https://imgur.com/a/6E23JQi) This should provide greater clarity than a written explanation.

- VSCode Version: 1.36.1
- OS Version: Ubuntu Bionic LTS

Issue type: **Bug**

Steps to Reproduce:

1. Import external .py file into ipynb project.
2. Run call to imported function in a cell.
3. Modify function external code.
4. Re-run the cell containing the import as well as the code in step 2

Restarting the kernel fixes this, however the nature of this bug could lead users to think the kernel is operating on a different version of the external code that it actually is. For me at least, this was confusing. That, and the stack trace _should_ output the external file that the kernel is working from.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
