### ISSUE TITLE
VScode freezes on pressing "Open Folder"/"Open File..."

### ISSUE THREAD

**Issue by vroson** [microsoft/vscode#82644]
VScode version: 1.39
OS: Windows 7 Pro

Opening files in VScode by double-click work fine. However, when you open VScode and then press "Open Folder"/"Open File..." it freezes completely. Have to close it using Task Manager.

Then same happens with VScode version newer than 1.35. VScode 1.35 works just fine.

**Comment by roblourens** [comment]
Was there an electron update after 1.35 @deepak1556?

**Comment by deepak1556** [comment]
@roblourens yup we updated to Electron 4.

@vroson can you try our latest insiders which is based on Electron 6 and see if the issue persists https://code.visualstudio.com/insiders/ . Thanks!

**Comment by vroson** [comment]
@deepak1556 Just now tried latest vscode insiders. The problem is still there.

**Comment by deepak1556** [comment]
@vroson how is it with latest stable ?

**Comment by vroson** [comment]
@deepak1556 , couldn't test on the same system, because I moved to Win10 recently.
But I tried it on another machine with Win7 and it still freezes.

This issue can be closed for me. I moved to Win10, since Win7 extended support will end very soon.
Consequently, this issue won't be relevant.

Thank you!
