### ISSUE TITLE
Return type listed along with function name in Outline view

### ISSUE THREAD

**Issue by linuxjh** [microsoft/vscode#82648]
ms-vscode.cpptools, Version: 0.26.0

![Screen Shot 2019-10-16 at 11 40 43 AM](https://user-images.githubusercontent.com/9011764/66886647-ab8d1580-f00a-11e9-90b9-2aa93ff0ea5d.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-cpptools extension repo
