### ISSUE TITLE
Switching tab without move file list items

### ISSUE THREAD

**Issue by linuxjh** [microsoft/vscode#82657]
![Screen Shot 2019-10-16 at 2 01 59 PM](https://user-images.githubusercontent.com/9011764/66892979-9cfd2900-f01f-11e9-90c6-d054c6e43160.png)

When switching tabs of opened files from one to another, and the opened file names can all be seen on the current file list window at the same time, can you just move the highlight to the next file, without move the whole list items on the current file list window?

Version: 1.39.2

**Comment by roblourens** [comment]
> without move the whole list items on the current file list window

Sorry, I don't quite understand, can you explain some more?

**Comment by linuxjh** [comment]
When I switch tabs of opened files, I want the list of filenames in EXPLORER window unchanged if the opened files are already shown in the current EXPLORER window.

If the name entry of opened file is outside the current EXPLORER window - it’s now shown in EXPLORER window, move it at the middle when switch to it through tabbar.

**Comment by roblourens** [comment]
Got it, thanks.

**Comment by isidorn** [comment]
Use the following setting please `explorer.autoReveal: false`

**Comment by linuxjh** [comment]
It's not the same thing. please reopen it. with this setting, it won't highlight the current file.
explorer.autoReveal: false

the EXPLORER window highlights the current file but doesn't scroll up or down in the EXPLORER window if the current filename isn't outside the current visible section of EXPLORER.

the outline view of ms-vscode.cpptools does highlight the current symbol correctly. maybe EXPLORER window should highlight filename this way.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/23902 and https://github.com/microsoft/vscode/issues/38899
Please upvote there

**Comment by linuxjh** [comment]
autoReveal always move the filename entry to the middle in explorer window, right?
if the file is not visible in the explorer window, this is ok.

if the file is visible in the current explorer window, it should not move the filename entry to the middle in explorer window, and just highlight the filename entry where it is.
