### ISSUE TITLE
can not search for any text, for workspaces on network.

### ISSUE THREAD

**Issue by ashjas** [microsoft/vscode#82656]
- VSCode Version: 1.39.1
- OS Version: windows 10

Steps to Reproduce:

1. Open a workspace thats on network path : `\\myworkspace`
2. try to search any thing in the workspace using ctrl+shift+f
3. Error: No file system provider found for ssh://ssh-fs/
4. This started appearing when i updated to latest version 1.39.1. The previous version didnt had this issue.

Does this issue occur when all extensions are disabled?: Yes

On reverting to 1.38.1 the issue is not seen.

**Comment by roblourens** [comment]
What extension are you using for the file system provider? Can you open and browse files as usual? I don't know why you would only see that error when searching.

**Comment by ashjas** [comment]
As i mentioned, this error also appears without any extensions loaded.
secondly, there is no extension needed to browse `\\networkpath` on windows right??
So i have opened a workspace/folder that is on this network path.
And when i search anything, i get the error.

**Comment by roblourens** [comment]
Oh strange, but this is the exact error you see, even with extensions disabled?  `Error: No file system provider found for ssh://ssh-fs/`?

**Comment by roblourens** [comment]
It seems likely that you have an ssh folder in your workspace. Do you see it if you open the .code-workspace file?

**Comment by ashjas** [comment]
as i mentioned i get it even if i disable all extensions.
Secondly, 
the .code-workspace file has this:
```
"folders": [
		{
			"path": "."
		},
		{
			"name": "SSH FS - ssh-fs",
			"uri": "ssh://ssh-fs/"
		}
]
```
But the previous vscode version has no problem with this workspace file, as search works.

Strange, i removed the above entry, and updated vscode, and the issue has gone.
So, if you are interested, maybe you can reproduce the issue, by adding the above entry to your workspace file on a network path.

I remember testing out some ssh plugin, that might have introduced that entry in the workspace file.

**Comment by roblourens** [comment]
Yeah there is an issue for search failing when a nonexistent workspace folder is present. Looks like you hit that.
