### ISSUE TITLE
use golang language server,the computer  become so slow

### ISSUE THREAD

**Issue by xcrossed** [microsoft/vscode#82659]
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-65-generic snap

when i set language server in setting.json,reload,the computer is card and slow.

  "go.useLanguageServer": true,
    "go.formatTool": "gofmt",
    "[go]": {},
    "go.languageServerExperimentalFeatures": {
        "format": false,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true,
        "workspaceSymbols": true,
        "findReferences": true,
        "diagnostics": false
    },
    "go.languageServerFlags": [
        "-rpc.trace", // for more detailed debug logging
        "serve",
        "--debug=localhost:6060", // to investigate memory usage, see profiles 
    ],
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "workspace",
    "go.gocodeAutoBuild": true,
    "go.lintOnSave": "workspace",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by xcrossed** [comment]
Ok,I will read it .

**Comment by xcrossed** [comment]
19192 root  20   0 7806028 6.216g    908 S 100.3 80.7   3:33.74 /data/softwares/go_packages/bin/gopls -mode=stdio

**Comment by xcrossed** [comment]
use this issue .
https://github.com/Microsoft/vscode-go/issues/2391#issuecomment-475917144

update my setting.json,the gopls cost cpu load high is stop.


"go.useLanguageServer": true,
"go.alternateTools": {
     "go-langserver": "gopls"
},
"go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true,
    "goToDefinition": true,
    "hover": true,
    "signatureHelp": true,
    "goToTypeDefinition": true
},
"go.buildOnSave": "off",
"go.vetOnSave": "off",
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
    "source.organizeImports": true
},
