### ISSUE TITLE
Extension Images should be painted in the tree only once fully loaded

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8265]
Testing #8215

A gif will not capture properly what I mean:
- it looks like the `<img>` is added as soon as an element is rendered
- this causes everyone to observe the "loading" of a file (especially with non progressive JPEG icons). I mean the "line-by-line" loading.
- IMHO when a tree element is rendered an `<img>` node should be created with `visibility:hidden` and once the `onload` fires, the `visibility` can be reset.
- IMHO this cheap trick makes a much better user experience

**Comment by isidorn** [comment]
Feature request -> july, joao
