### ISSUE TITLE
Extension point for adding context menus to diagnostic items

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode#82650]
I would like an extension point in the API that allows the addition of a context menu for the Problems pane.

This could be very useful for extension authors (particularly language servers, linters) to use the context of the problem and provide additional information.

(It would allow adding entries in the menu below)
![image](https://user-images.githubusercontent.com/13103165/66888487-9c1eb580-ef93-11e9-8c3d-5faecc8b543e.png)

**Comment by sandy081** [comment]
Can you please provide what additional action items you want to show? (Real time examples)

**Comment by radu-matei** [comment]
The point would be allowing individual extensions to add items in this menu, not having more actions built-in VS Code itself.

**Comment by sandy081** [comment]
May I know what could be those items are? Generally we do not add API without real use cases with proper examples
