### ISSUE TITLE
Cannot run theme "Afterglow Theme"

### ISSUE THREAD

**Issue by major697** [microsoft/vscode#82658]
Hi, I install theme [Afterglow Theme](https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Afterglow), But I can't run this theme I have not this theme on list:

Version: 1.39.2 (user setup)
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

![Bez tytułu](https://user-images.githubusercontent.com/18541212/66893356-33b0f200-efee-11e9-834b-262f54074e4e.png)

**Comment by Enrika** [comment]
I'm having the exact same problem with the Easyballs theme as of this evening.

**Comment by roblourens** [comment]
Works for me, does it still not show up if you reload the window? What if you just seting that setting manually?

**Comment by roblourens** [comment]
FYI @aeschli others have reported this, do you know anything about it?

**Comment by aeschli** [comment]
It also works for me.
