### ISSUE TITLE
WSL: renaming dirs impossible from explorer

### ISSUE THREAD

**Issue by neurotronix** [microsoft/vscode#82669]
Issue Type: <b>Bug</b>

## Actual result
- right click directory
- select 'Rename'
- nothing changes

## Expected result
- repeat first 2 steps from above
- directory name changes

Renaming works fine for files!

The previous workaround of enabling fileWatcher polling, seems to have stopped working. Here the snippet from my settings:
```json
  "remote.WSL.fileWatcher.polling": true,
  "remote.WSL.fileWatcher.pollingInterval": 10,
``` 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.21GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/c/Users/Stephan/Projects/trading-reporting --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.85GB (3.21GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
Go|ms-|0.11.7
vscode-typescript-tslint-plugin|ms-|1.2.2
autodocstring|njp|0.3.0
vscode-yaml|red|0.5.3
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.1.9
dotenv|mik|1.0.1
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
material-icon-theme|PKi|3.9.1

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I believe this is a WSL issue that rename is broken.
@aeschli would know more

**Comment by aeschli** [comment]
Its a regression in 1.39 that  "remote.WSL.fileWatcher.polling": true no longer is used.

Fixed for October.

**Comment by aeschli** [comment]
To verify:
- configure` "remote.WSL.fileWatcher.polling": true`
- set log level to `trace`
- open a folder in a WSL window
- check the Log (Remote Server) for `File Watcher`. Should say:  `File Watcher (chokidar)] Use polling instead of fs.watch: Polling interval 5000 ms`

**Comment by weinand** [comment]
Works:
![2019-10-31_12-57-41](https://user-images.githubusercontent.com/1898161/67944972-18dda080-fbde-11e9-85a9-0338321b7d14.png)
