### ISSUE TITLE
Replace insert behaviour doesn't work well with JSON

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#82666]
from https://github.com/microsoft/vscode/issues/82324#issuecomment-542492708

I'm seeing weird behavior on quotes as well. if you type inside `""`, the last quote is removed, like in tsconfig.json: 

```json5
"includes": [
  "./" // << Ctrl + Space here
]
```

becomes

```json
"includes": [
  "./server.ts
]
```

**Comment by jrieken** [comment]
@pocesar In your sample where does the `server.ts` completion come from? Is that an extension?

**Comment by pocesar** [comment]
@jrieken oh, it is! I just noticed that I have one installed called "Path Autocomplete". I disabled it and it works as it should

Name: Path Autocomplete
Id: ionutvmi.path-autocomplete
Description: Provides path completion for visual studio code.
Version: 1.13.3
Publisher: Mihai Vilcu
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete

**Comment by jrieken** [comment]
Yeah, something is definitely broken. The root problem is that the JSON language defines `"` as word characters, e.g `"foo"` is considered a word, not just `foo` (without double quotes). The new replace-on-accept-behaviour uses the range of the current word. E.g when accepting `server.ts` it replaces the current word first. For JSON  and in your case this is `./"` (not `./`). That's not so good ;-) Needs some thinking how we should tackle this...

**Comment by jrieken** [comment]
Some ideas are collected here https://github.com/microsoft/vscode/issues/10266#issuecomment-544520553. This likely requires new API and adoption work, hence making this slower...

**Comment by pocesar** [comment]
I noticed, since the last update, when trying to edit the tsconfig.json (without any paths), between quotes, it becomes `"", "`, like:

![image](https://user-images.githubusercontent.com/461084/67232389-a61f3900-f417-11e9-9477-18ec1e2eb515.png)

select `esModuleInterop` from the suggestion, becomes:

![image](https://user-images.githubusercontent.com/461084/67232434-bafbcc80-f417-11e9-97d1-5c5a0afaf1ac.png)

**Comment by jrieken** [comment]
fixed via https://github.com/microsoft/vscode/pull/83075

**Comment by jrieken** [comment]
self-verified because we don't ship this feature anymore
