### ISSUE TITLE
Compact menu doesn't take 100% of the activity bar width in fullscreen

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#82668]
Issue Type: <b>Bug</b>

```js
"window.menuBarVisibility": "compact",
```

1. Go fullscreen
1. Try to click on the menu icon at the leftmost part

VS Code version: Code - Insiders 1.40.0-insider (3f6ed25939b8ef157a7a41e0dc43b517898d4005, 2019-10-15T05:26:38.861Z)
OS version: Windows_NT x64 6.2.9200

**Comment by syed-sohaib7** [comment]
Cannot find this as an issue !
