### ISSUE TITLE
Shortcut ctrl+` fail after reactivate vscode window

### ISSUE THREAD

**Issue by illava** [microsoft/vscode#82667]
Issue Type: <b>Bug</b>
File on: <b>Visual Studio Code</b>
## Reproduce steps
1. Open vscode 
2. now deactivate vscode window (switch to other program) and activate vscode window again.
## Actual
* Ctrl + \` no responce, not open nor close terminal
* In Preference-->Keyboard Shortcuts-->Record Keys, when recording shortcut "Ctrl + \`", "Ctrl + " appear and not seaching

## Expacted
* Ctrl + \` works fine, open terminal and close
* In Preference-->Keyboard Shortcuts-->Record Keys, when recording "Ctrl + \`", "ctrl+oem_3" should appear and begin to search

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by perceptron007** [comment]
Not able to create the bug. Can you verify the steps again, anything you have done before you got the issue?

With the steps, you mentioned to reproduce, the bug is not happening.

**Comment by alexandrudima** [comment]
@illava I cannot reproduce. `` ctrl+` `` works reliably for me, even if I focus another application and return to VS Code later. Do you happen to use a specific keyboard layout where this reproduces?

**Comment by illava** [comment]
I figure out the issue is related to IME(QQPinyin). Repaired after uninstalling. 
Thanks for your help.

**Comment by illava** [comment]
That‘s why it appears only my home and office PC.
Don't know what's the exact problem with IME. Since it is rare used and lacks feedback methods. Simply change to another IME will be fine.

**Comment by alexandrudima** [comment]
Ok, it seems that you have a similar issue as #70482 . `` ctrl+` `` is simply reserved and used by the IME, therefore the keybinding does not reach VS Code.
