### ISSUE TITLE
Miss recognizing file type (gulpfile)

### ISSUE THREAD

**Issue by dtvn** [microsoft/vscode#82661]
The Gulp tool only use `gulpfile.js` so vscode should see that file as Gulp file, not JS file. However, it has a mistake in vscode about this. When you use name `gulpfile` only, vscode will display gulp icon before it. This could confuse people, especially newbie.

I suggest we set a special rule for `gulpfile.js` so it won't be seen as JS file but Gulp file. Like webpack you know, webpack.config.js actually displays webpack icon not Js.

**Comment by NizamLZ** [comment]
I think this needs to be addressed. I will raise a PR shortly.

**Comment by roblourens** [comment]
I also see this in the builtin vscode file icon theme.

**Comment by NizamLZ** [comment]
@roblourens Should the change be done in the source repo or in vscode? Is my PR valid?

**Comment by aeschli** [comment]
The PR needs to be made against https://github.com/jesseweed/seti-ui. The built-in vscode file icon theme is generated from the content there.
