### ISSUE TITLE
Markdown: shades of blue in dark theme when using lists

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8266]
![image](https://cloud.githubusercontent.com/assets/900690/16410258/f3a5147a-3d21-11e6-8dad-544f1ebf9cf6.png)

**Comment by kieferrm** [comment]
This is in the Dark+ theme. In the Dark theme we only color the character used as bullet.

**Comment by bpasero** [comment]
This is even worse when you have the following (our smoke test):

![image](https://cloud.githubusercontent.com/assets/900690/16516954/375e559a-3f7b-11e6-8a46-dde895ca86cb.png)

**Comment by bpasero** [comment]
In stable:

![image](https://cloud.githubusercontent.com/assets/900690/16516976/5a003438-3f7b-11e6-983c-01c78aa3fe0f.png)

**Comment by bpasero** [comment]
@kieferrm thanks. please also update the tests, otherwise our builds are failing (https://travis-ci.org/Microsoft/vscode/builds/141740263)

**Comment by bpasero** [comment]
To unblock our CI, I pushed https://github.com/Microsoft/vscode/commit/4e72dcc35954ae36a277983922926f3f5a971d0c

**Comment by kieferrm** [comment]
@bpasero thanks for fixing this.

**Comment by bpasero** [comment]
Looks ok in dark theme, but in light theme it still has lots of blue:

![image](https://cloud.githubusercontent.com/assets/900690/16555879/3c1f5bac-41d7-11e6-87da-96d829f3e52b.png)

**Comment by gerane** [comment]
What about every other theme? Now, dark+ is the only theme that has proper lists, every other theme is broken.
