### ISSUE TITLE
User Snippets not suggested

### ISSUE THREAD

**Issue by brandonkal** [microsoft/vscode#82664]
- VSCode Version: 1.39.1
- Local OS Version: macOS 10.12.6
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create user snippet. On my Mac I have a file named `~/Library/Application Support/Code/User/snippets/imr.code-snippets`. Here is the first snippet in that file for reproduction:
```json
{
  "Import CSS": {
    "scope": "javascriptreact,typescriptreact,typescript",
    "prefix": "icss",
    "body": ["import { css, cx } from '@brandonkal/linaria'"]
  },
}
```

2. Type `icss` in a jsx file via SSH remote. VSCode does not suggest anything.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I should note that user snippets do not appear when pressing "ctrl+space" either.

I also have issues with other snippets. For instance, with the Kubernetes extension, typing "pod" in a YAML file should prompt for a snippet. In that case, a "ctrl+space" is required to see the suggestion.

**Comment by jrieken** [comment]
@brandonkal Can you test if this works when you remove the `scope` attribute?

**Comment by brandonkal** [comment]
@jrieken When `scope` is removed it works over SSH which is interesting. Then of course the suggestions show in the wrong languages.

**Comment by jrieken** [comment]
And when opening a `jsx` file what does the language indicator at the lower right show?

**Comment by brandonkal** [comment]
Babel JavaScript...
Adding `javascript` in the scope fixed things. Thank you for the help.

Though the issue with the required "ctrl+space" in YAML files remains so I probably should not close this just yet.

**Comment by jrieken** [comment]
please file a separate issue for that, include sample and steps. thanks

**Comment by brandonkal** [comment]
Here or the remote release repo?

**Comment by jrieken** [comment]
here
