### ISSUE TITLE
Find All References and interface implementation

### ISSUE THREAD

**Issue by xuxicheta** [microsoft/vscode#82679]
Typescript
I have interface and many classes with this interface implementation.
I look at method of one of this classes and want to know where this method used.
I have "Find All References" action but it shows me all same methods from all those classes and interface at all.

How to find references to concrete **this** method at **this** class?

**Comment by jrieken** [comment]
We are working on API and UI for call hierarchy. Once that is done and supported by TypeScript (see their repo for their tracking item) you can do this.
