### ISSUE TITLE
Extension update and platform update are inconsistent when no updates available

### ISSUE THREAD

**Issue by patrys** [microsoft/vscode#82677]
- VSCode Version: 1.40.0-insider
- OS Version: macOS Mojave

Steps to Reproduce:

1. In the Extensions pane run the "Check for Extension Updates" command
2. From the gear icon choose "Check for Updates..."

One uses a notification while the other displays a modal:

![Zrzut ekranu 2019-10-16 o 11 52 36](https://user-images.githubusercontent.com/81205/66908907-2a368280-f00c-11e9-94a1-c7f90f4c5574.png)

![Zrzut ekranu 2019-10-16 o 11 53 07](https://user-images.githubusercontent.com/81205/66908919-2e62a000-f00c-11e9-837e-9e4ca9eedd45.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
They should both be modal dialogs since they are user initiatied IMHO.
They should not be notifications.

Especailly since me as a User am now surprised by not getting feedback when cehcking for udpates (the notification is on the bottom right corner of my screen which I easily miss)

**Comment by joaomoreno** [comment]
I hate going back and forward on stuff like this, but I do agree with @isidorn. Reverting and moving forward to @sandy081.
