### ISSUE TITLE
Parallel scrolling when opening similar files side-by-side

### ISSUE THREAD

**Issue by TheEny53** [microsoft/vscode#82673]
When using the side-by-side view with two structurally similar files (e.g. package.json or manifest,json), the option to scroll both files in parallel would be really helpful when comparing differences between said files. Until now, this is not possible afaik and would really help speed up dev workflows when dealing with projects that contain lots of similar files.

**Comment by roblourens** [comment]
You can load the two files into the diff editor, if that helps. Right click "Select for Compare", or run the "Compare Active File With..." command
