### ISSUE TITLE
Initiating drag and drop from explorer reveals file or opens it in a preview tab

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#8267]
- VSCode Version:1.3.0-insider
- OS Version: windows 10

Steps to Reproduce:

1. Mouse down on a file in explorer then move to drag the file into an editor
2. If the file has not previously been opened in the active editor group it is opened in a preview tab before the user gets to drop the file where they want it.

Expected: the file should not be revealed or opened in a preview tab if the user moves the mouse after mousedown within a specific threshold (in VS this is 250 ms)

Found while testing: Drag and Drop editors and tabs #7852

**Comment by bpasero** [comment]
@stevencl I can change this but this will cause any operation that involves opening an editor to be noticeably slower (by 250ms). That is why I decided to not push for it for now because I am worried this makes the overall perceived performance slower.

**Comment by stevencl** [comment]
It's worth experimenting I think. This is where we landed in Visual Studio but we can always try and come up with a different threshold. Without it, drag and drop from the explorer often ends up opening additional editors.

**Comment by bpasero** [comment]
This is also a very new feature so maybe we gather additional feedback from the community?

**Comment by bpasero** [comment]
Btw a better solution to waiting arbitrary 250ms is to just only open the editor on mouse up and not mouse down. Any reason VS chose 250ms delay?

**Comment by stevencl** [comment]
We got this feedback in VS for this exact same scenario so I'm just trying to pre-empt community and team feedback.

We went with the 250ms delay before previewing and opening editors because we also preview items when the user arrows up and down through the list. So with the delay they can arrow up and down very quickly without needing to wait for a preview to open.

Since we don't do that we could just open on mouse up. Using the arrow keys to move up and down the list in explorer is also a good experience though. Something we don't support just now but with the preview tab, we might consider it for the future?

**Comment by bpasero** [comment]
Agrees. But I want one milestone of user feedback before making such a change.

**Comment by bpasero** [comment]
@stevencl also I wonder if there are other options: e.g. we could open the editor as before but as soon as we detect the user is dragging we actually take the editor that we just opened and move it.

**Comment by eByte23** [comment]
@bpasero trying not to duplicate tickets, but is this for when dragging and dropping a selected file in file explorer(windows explorer/finder etc.) into code. As its an annoying not having this as you have then manually open it or another instance of code

**Comment by bpasero** [comment]
No that should work just fine.

**Comment by bpasero** [comment]
Due to https://github.com/Microsoft/vscode/issues/10775 I decided to change the explorer to open the file only on mouse up.

@stevencl fyi

**Comment by Tyriar** [comment]
:+1: for opening on mouse up only, verified
