### ISSUE TITLE
When open file, file listing blocks opening a file path 

### ISSUE THREAD

**Issue by innerlee** [microsoft/vscode#82675]
- VSCode Version: 1.38.1
- Local OS Version: ubuntu 18.04
- Remote OS Version: centos
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. ctrl+shift+p -> select open file
2. enter a path that contains lots of files, say, > 20k, then the listing window would take a lot time to respond
3. in this case, even you have entered a full filename, you cannot open the file by clicking ok, but need to wait for the long background file listing

Suggestion:
1. kill the listing process of old folder when your typing has changed to another folder. 
2. able to open a file instantly if you have entered a full path

Does this issue occur when you try this locally?: YNo. Locally it opens a dialogue to open a file.
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by alexr00** [comment]
I assume that this would also happen if you enable the simple file picker locally so moving to the vscode repo.

**Comment by innerlee** [comment]
Yea, but the issue is only noticeable when connected to a remote via ssh, when a single `ls` may need to transfer several `MB`s data

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/pull/235740!
