### ISSUE TITLE
setImmediate shim is incorrect

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#82674]
![image](https://user-images.githubusercontent.com/5047891/66908227-00309080-f00b-11e9-926a-c9cca5af23f7.png)

**Comment by bpasero** [comment]
Noticed while selfhosting on web in Chromium browsers.

**Comment by alexandrudima** [comment]
To verify: open a large file like `checker.ts` in the browser and check that the browser is responsive.
