### ISSUE TITLE
 extension store  can not open

### ISSUE THREAD

**Issue by chenyi729** [microsoft/vscode#82672]
my laptop can connect to the internet  but  VS  Code  can not connect to extension store。
The version of my VSCode  is   1.39.2

**Comment by roblourens** [comment]
Please give some more details about what you are seeing.

Are you using a proxy? Have you set the proxy settings in vscode?

**Comment by chenyi729** [comment]
i am not using proxy and never set proxy setting in vscode。
but  i can connect to the extension store without any operation（such as set proxy setting etc.） today。
Thank you all。
