### ISSUE TITLE
VS Code often does not close after test runs complete

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#82676]
For the last few weeks, my automated test runs have been intermittently (but very frequently) hanging after the tests complete. Mocha writes that the tests completed, with the number of passes, but the VS Code process never terminates, so on Travis we end up with something like:

```
 ✓ Dart: New Project can be invoked and creates trigger file
  3 passing (5s)

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

When it works, the next line printed after `x passing` would be `Exit code:     x` which is printed by [`vscode-test`](https://github.com/microsoft/vscode-test/blob/bcd614f7a13f3422b530f5f07034d9a7b5f3979c/lib/runTest.ts#L117).

I added some code to log before the callback passed into the test runner is called, as well as logging if the process is still alive after 10 seconds:

https://github.com/Dart-Code/Dart-Code/blob/291489432857a433308ab43910d0bbb225cdbfd4/src/test/test_runner.ts#L30-L37

And the output now looks like:

```
 3 passing (3s)

Test run is complete! Calling VS Code callback with (null, 0)

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

This suggests that Mocha is correctly finishing the run, and that the test runner code (which I adapted from https://github.com/microsoft/vscode-test/blob/master/sample/test/suite/index.ts) is correctly calling the callback, and the extension host is disappearing within 10 seconds (since it didn't print the second line), yet VS Code never quit so the CI build just hung.

I tried passing `--verbose` to Code, and then the output ended like this:

```
Test run is complete! Calling VS Code callback with (null, 0)

[main 2019-10-16T07:52:02.179Z] IPC#vscode:exit 0
[main 2019-10-16T07:52:02.180Z] Lifecycle#kill()
[main 2019-10-16T07:52:02.181Z] Lifecycle#window.on('closed') - window ID 1

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

So my guess is that either

- VS Code is not terminating; or
- The [`close` event is not firing in `vscode-test`](https://github.com/microsoft/vscode-test/blob/master/lib/runTest.ts#L100) so it never completes its promise.

I spent a lot of time last week and this week trying to diagnose this, but I feel like I'm running out of ideas. I am completely unable to reproduce it locally (and as far as I can tell, it only happens on macOS on Travis - I don't think I've seen it on Linux).

~~I'm trying to make a smaller repo that has this issue (my test runs are quit big and involve downloading SDKs), but I figured it was worth opening an issue in case others are seeing it, or you have any suggestions on how to track down.~~

**Edit: Repro is further down in the comments.**

I don't know if it's related (wouldn't explain why it's intermittent), but the [example test runner script](https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-runner-script) on the website is very different to the one in the sample repo (one returns a promise, the other takes a callback). I couldn't find any explanation for the difference.

**Comment by DanTup** [comment]
I don't know if it's related, but https://github.com/microsoft/vscode/issues/77513 appears to also be an issue with test runs not completing properly since v1.36 (though it sounds like they're not even running to completion, so it may be entirely unrelated).

**Comment by DanTup** [comment]
Here is a tiny repro:

https://github.com/DanTup/vscode-repro-82676

Extension code looks like this:

```ts
export async function activate(context: vs.ExtensionContext, isRestart: boolean = false) {
	console.log("Activating extension!");

	console.log("Has finished activating extension!");
}

export async function deactivate(isRestart: boolean = false): Promise<void> {
	console.log("Extension deactivating!");
}
```

Test code looks like this:

```ts
describe("test environment", () => {
	it("dummy test that passes", () => {
		console.log("Running test!");
	});
});
```

It's set to run  5 identical bots on Travis:

https://github.com/DanTup/vscode-repro-82676/blob/master/.travis.yml#L13

And 1/5 of them hung as described above:

https://travis-ci.org/DanTup/vscode-repro-82676/builds/598641378
https://travis-ci.org/DanTup/vscode-repro-82676/jobs/598641382

I've deleted absolutely all of my extension code and test code, and stripped out everything I could from the repo, and it still happens.

**Comment by DanTup** [comment]
I tried switching to returning a promise from the `run` method in the test runner, but it didn't make any difference, seems to sometimes hang in the same way:

https://travis-ci.org/DanTup/vscode-repro-82676/jobs/598649977

**Comment by DanTup** [comment]
This happens on GitHub Actions macOS too, not only Travis.

**Comment by tiagobento** [comment]
Hi @DanTup! I'm so glad I found this issue 😅🙏 That means I'm not the only one experiencing it. 

I'm running `vscode-test` inside a GitHub Workflow too and I can tell that the exact same thing it happening to me. I was, however, *able* to reproduce it locally. Since GitHub Workflows "workers" are [relatively slow](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources) machines, I figured that if I tried long enough on a slower machine I would be able to reproduce it.

That's how I got it
---
I ran a very CPU-consuming process at the same time as my VSCode extension tests. It's not a consistent behaviour, though, so I used the most advanced technique to solve probably-concurrency-related-problems:

```
for (( ; ; )); do    npx lerna run test:it --stream;    sleep 1; done
```

And waited. Eventually, that hung up. (🎉?) I used this command because I'm on a monorepo and that's the command I use to run the integration tests on my GitHub Workflow. Nothing special about it.

So what?
---
I now had a stuck process that would never terminate so my first thought was to take a memory dump and do something with it. All that just happened, so I didn't have time to try and learn what exactly to do. I googled "macOS process memory dump" or something like that and found this command:

```
lldb --attach-pid $PID
process save-core "filename"
```

The supposedly dump file is about 3GB big (which is too much I think). Do you have any idea how that could help us understand what's going on?

**Comment by DanTup** [comment]
Glad to hear it's not just me! Not having test run results is painful! I've had to disable macOS everywhere for now. I'm not sure why Code isn't seeing this in its own test runs though (maybe it is, but I would expect it would be picked up pretty quick if so).

I don't really know the best way to debug this - I'm not very familiar with Electron (or macOS). Probably needs some input from someone else (hopefully the Code team).

**Comment by DanTup** [comment]
@octref do you need any more info for this issue? It seems like a significant regression that means extension authors can't run tests on macOS. I've had to disable all my macOS testing and that makes me somewhat uncomfortable - I really hoped it might be looked at before the next release 😞

**Comment by octref** [comment]
@DanTup Is there a specific version since which this started to happen? I don't think there's any changes in vscode-test recently so it might be something related to VS Code's shutdown.
@bpasero Are you aware of any changes recently? It seems to me that `close` event is not emitted from the CLI process when this happens.

**Comment by DanTup** [comment]
I don't know for sure when it started (as it took me a while to understand what was going on). I think it was likely the last 1-2 stable versions of Code.

I don't know if it's at all related, but another issue I opened (which may have started around the same time) had a fix that may be related to close events. Could be coincidence though, I'm not familiar with the workings of this:

https://github.com/microsoft/vscode/issues/81090

**Comment by bpasero** [comment]
I think @weinand recently was in this area where we would accidentally close the main window after tests complete. What was the code change again?

**Comment by DanTup** [comment]
Yeah, that was in the issue linked above (https://github.com/microsoft/vscode/issues/81090#issuecomment-545023356 / 860d2aca1f7cf46112633f8d2f673c901e510e93). I'm wondering if the issue may have also caused this (maybe it's closing in a way that doesn't fire the event vstest-close is waiting for?).

I'll try switching my repro repo over to insiders and give it some runs to see if the change to fix that has had any effect.

**Comment by DanTup** [comment]
🤷‍♂️

![Screenshot 2019-10-31 at 8 19 01 am](https://user-images.githubusercontent.com/1078012/67930214-216eb080-fbb7-11e9-81cb-4f79ae1391b1.png)

**Comment by DanTup** [comment]
Second run, 10/10 passes for insiders, but only 8/10 for stable.
Third run, 10/10 passes for insiders, 9/10 for stable.

Seems to be happening less than when I raised this even for stable (maybe Travis machines are less slow when the US is sleeping - it's intermittent so seems like it may have a race), but insiders hasn't failed yet.

I'll try again later today and if the results are the same I'll enable my macOS bots again for Dart-Code and report back.

**Comment by DanTup** [comment]
I don't know what's going on anymore :)

I ran it again and there are Insiders builds that have also hung:

https://travis-ci.org/DanTup/vscode-repro-82676/jobs/605374295

However the output makes it seem like the tests have completely finished, and now *Travis* is inexplicably hanging:

```
Exit code:   0
Done
Test run complete!
The command "npm test" exited with 0.
cache.2
store build cache
Done. Your build exited with 0.
```

This could be an unrelated Travis bug and a coincidence, but I also don't know whether it might be something like leaked processes causing Travis not to terminate. It's also intermittent - 4 runs so far, 2 of them passes (on Insiders) and two are stalled like that (also Insiders) 🤷‍♂️

**Comment by tiagobento** [comment]
@DanTup I don't think this is a Travis bug since I'm having the same issue on GitHub Actions. Yesterday I got a build that was stuck for 6 hours until GitHub decided to kill it, since the time limit for a job is 6 hours.

**Comment by DanTup** [comment]
@tiagobento I don't think the general issue here is a Travis bug, but the last few failures I have I think might be (so it's possible this is fixed in Insiders, but it's hard to say when the Travis builds are hanging in a different way).

I'll try enabling it for Insiders on my main repo soon - though if you're able to switch to Insiders, I'd be interested to know if the issue goes away for you there (it's possible the fix for the issue I linked above solves this too - it's related to VS Code quitting - but I don't understand it well enough to know if it could affect this :-))

**Comment by tiagobento** [comment]
@DanTup Ah, ok, got it :)

I'm going to see if I can enable insiders on my CI. Will follow up then. Thx!

**Comment by DanTup** [comment]
Weirdly, despite hanging at the end, the job I linked above now shows green with "Ran for 1 min 11 sec". So for Insiders it does seem like VS Code is terminating as expected, but Travis runs are sometimes hanging at the end (but that time is not considered part of the build once it finally completes) and it's not clear if that's related. It's intermittent with about the same frequency (10-20%) so I'm wondering if VS Code is still doing something that's keeping the build job from terminating.

I'm going to enable it for Dart-Code on GH Actions (I'm trying to move away from Travis anyway) and see how it behaves there.

**Comment by DanTup** [comment]
I re-enabled this on my builds after the stable releasing thinking it may have gone away with the fix discussed above, however I just saw a hang again (on GH Actions - after 5 hours I clicked cancel, which terminated the step and moved on). This time it wrote that the render process crashed though:

```
  3 passing (6s)
Test run is complete! Calling VS Code callback with (null, 0)

[main 2019-11-11T09:23:43.901Z] [VS Code]: render process crashed!

[main 2019-11-11T09:23:50.593Z] update#setState checking for updates

[main 2019-11-11T09:23:50.656Z] update#setState idle

[main 2019-11-11T10:23:50.737Z] update#setState checking for updates

[main 2019-11-11T10:23:51.045Z] update#setState idle

[main 2019-11-11T11:23:50.868Z] update#setState checking for updates
```

**Comment by DanTup** [comment]
Oh interestingly, this one was on Windows - it's possible it's unrelated - but it seems suspicious that it also happened after the test run had completed.

**Comment by octref** [comment]
@DanTup Is this still happening to you?

**Comment by DanTup** [comment]
Hard to say for certain because on Travis I often hit a 50min limit (integration tests are sloooow) and GH actions has weird issues where it shows builds still running after a week (and sometimes it won't show the output of the test run)...

I *think* it may be fixed (at least ignoring the unrelated "VS render process crashed" error above which seem pretty common on Windows). I'll likely be digging through test results more this week so feel free to close this and I can shout back if I come across builds that suggest it's still happening.
