### ISSUE TITLE
sendSequence should support addNewLine argument

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#82671]
Issue Type: <b>Feature Request</b>

Auto typing <kbd>Enter</kbd> just like `addNewLine` at `Terminal.sendText`:

```js
{
	"key": "ctrl+i",
	"command": "workbench.action.terminal.sendSequence",
	"args": {
		"text": "test",
		"addNewLine": true
	}
}
```

**Comment by Anamika28** [comment]
<img width="1680" alt="Screenshot 2019-10-16 at 8 27 51 PM" src="https://user-images.githubusercontent.com/14240904/66931268-79ec6c80-f053-11e9-900b-bcb5a4e0e4d0.png">

**Comment by usernamehw** [comment]
That works.
