### ISSUE TITLE
Breadcrumbs don't show folder icons from icon themes

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#82684]
This happens in Insiders v1.40.0

- VSCode Version: v1.39.2 and Insiders v1.40.0
- OS Version: macOS 10.15

Steps to Reproduce:

1. Copy the following to your settings.json file:
```
"breadcrumbs.enabled": true,
"breadcrumbs.filePath": "on",
"breadcrumbs.icons": true,
"workbench.iconTheme": "vs-minimal", // Or any icon theme with folder icons
```
2. Open a file that's inside a folder (ex: `repository/assets/css/main.css`)
3. Notice that in your file explorer all folders have icons, including the `assets` and `css` folders, but your breadcrumbs doesn't show those icons in the file path.

Does this issue occur when all extensions are disabled? Yes

**Comment by misolori** [comment]
I think what you're saying is the when an icon theme has folder icons these are not reflected in the breadcrumbs:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/35271042/66937575-868da800-eff4-11e9-966a-b3d9b8325dfc.png">

**Comment by andrecasal** [comment]
Yes, that's exactly right. Thanks for the better articulation 👍

**Comment by jrieken** [comment]
Yes, this is done on purpose to safe screen real estate.

**Comment by andrecasal** [comment]
Ok, thanks. I may create a feature request for this, if there isn't one.
