### ISSUE TITLE
Code Section Collapsing

### ISSUE THREAD

**Issue by Ebuka18** [microsoft/vscode#82688]
Issue Type: <b>Bug</b>

Collapse a code segment on a page (Page A)
Go on to another page (Page B)
Return to the previous page (Page A)
All the collapsed code segment would expand
And the icon for collapsing and expanding code takes few seconds before showing up, and also takes few more seconds to respond to clicks. 

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
Angular-BeastCode|Mik|8.0.10
vscode-antlr4|mik|2.1.1
mssql|ms-|1.6.0
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
csharp|ms-|1.21.4
twig|wha|1.0.2

</details>

**Comment by sksaifuddin** [comment]
Its not producible, can you please provide more info

**Comment by ayqy** [comment]
@aeschli Same problem here, code collapsing for some js file does not work as intend *occasionally*:

- Collapsing and expanding code takes few more seconds to respond to clicks.

- And sometimes, the icon disappeared...

No specified steps found to reproduce now.

(OSX 10.13.6 and VS Code 1.38.0)

**Comment by aeschli** [comment]
@Ebuka18 What type of files is that? HTML, JSON, ... Does it reproduce with all extensions disabled?
@ayqy If you have any steps or code sample, please file a separate issue.
