### ISSUE TITLE
Code_Helper is taking 100% usage

### ISSUE THREAD

**Issue by Tanvir-rahman** [microsoft/vscode#82681]
Issue Type: <b>Performance Issue</b>

Code_Helper is taking 100% usage

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_8112060|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    90	 73773	code main
    8	    49	 73776	   gpu-process
    0	     0	 73781	   (Code Helper)
    9	    74	 73806	   shared-process
    0	     0	 84092	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   229	 84032	   window (package.json — dakpeon)
    0	   123	 84033	     extensionHost
    0	    57	 84045	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=84033
    0	    66	 84049	       electron_node server.js 
    0	    49	 84034	     watcherService
    0	    41	 84035	     searchService
    4	    74	 84090	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (package.json — dakpeon)
|  Window (ProductItem.js — NativeShop)
|    Folder (NativeShop): 99 files
|      File types: js(64) json(5) png(2) ttf(2) gitignore(1) watchmanconfig(1)
|                  lock(1) log(1)
|      Conf files: package.json(1) settings.json(1)
|    Folder (dakpeon): 171 files
|      File types: js(47) vue(28) png(14) yaml(10) scss(7) json(3) md(2)
|                  helmignore(2) ttf(2) editorconfig(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-goto-view|cod|1.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.31.0
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.3
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
php-debug|fel|1.13.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.0
githd|hui|2.1.0
search-node-modules|jas|1.3.0
sublime-babel-vscode|jos|0.2.10
rn-full-pack|kel|0.4.0
vscode-language-babel|mgm|0.0.24
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-postcss-sorting|mrm|3.0.1
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
azure-account|ms-|0.8.6
color-highlight|nau|2.3.0
vetur|oct|0.22.4
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
material-icon-theme|PKi|3.9.1
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.26
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.7.18
vscode-icons|vsc|9.4.0
gitblame|wad|3.0.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It wasn't happening when you filed the issue so we don't know which process it was. When you see it again, please share the output from `code --status` and more details about exactly what you are doing, or how often you see it, etc.
