### ISSUE TITLE
Method collapses to first same indent line for cls files

### ISSUE THREAD

**Issue by kochengin** [microsoft/vscode#82689]
Whenever i try to collapse method in my *.cls class it collapses as is should, until there is an line on the same indentations as method initialization. In that case  method collapses to that line, ignoring method`s figure brackets.

Case1 all good, for case2 only line  

> do.this();

will collapse.

//at *.cls file:
```
//case1
public method() {
    do.this();
    donotdo.that();
    do.that();
}
```
```
//case2
public method() {
    do.this();
donotdo.that();
    do.that();
}
```

Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by aeschli** [comment]
The default folding strategy for cls (without any extensions) is based on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be smarter and to be cls aware, a cls extension needs to do this. Please file an issue against the cls extension that you use.
