### ISSUE TITLE
CPU consistently >200% and RAM >2GB. No extensions!

### ISSUE THREAD

**Issue by jgclark** [microsoft/vscode#82693]
Issue Type: <b>Performance Issue</b>

Even with *all extensions disabled* and VSCode reloaded.
And only one small markdown document loaded.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   21	    49	 11701	code main
   10	    16	 11702	   gpu-process
   41	    49	 11727	   shared-process
    0	     0	 11947	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	    49	 11880	   window (_cong_email.md — jonathan)
    0	    16	 11883	     extensionHost
  106	  1679	 11884	     watcherService
    8	    66	 11942	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (_cong_email.md — jonathan)
|    Folder (jonathan): more than 100644 files
|      File types: png(2247) pdf(2173) jpg(1429) plist(812) md(570) txt(477)
|                  doc(447) ttf(371) JPG(313) zsh(275)
|      Conf files: package.json(16) makefile(2) launch.json(1) tslint.json(1)
|                  webpack.config.js(1);
```

</details>

Extensions: none

**Comment by Ronkiro** [comment]
Maybe related? #82690

**Comment by roblourens** [comment]
Did you open large workspace? Are there lots of changes in git? Is it different depending on which folder you open?

**Comment by jgclark** [comment]
Thanks. 
I'd never yet explicitly saved a workspace. I'd only added a folder to an implicit workspace, which has 340 files in it, though only a few open at a time. 
I don't use git.

When I opened it again today, the odd behaviour had stopped. I've re-enabled some extensions and still OK. I have now saved this folder as an explicit workspace.
I will add more if I find it happening again soon.

**Comment by Ronkiro** [comment]
@jgclark i've had some problems with Python Language Server before that were causing similar issues, but the issues only started when running after 1/2 hours.
I recommend checking if the error doesn't occurs after some time of use.

**Comment by roblourens** [comment]
Let me know if you see it again, please run `code --status` so we can info about which process is causing the issue, and see whether any of the tips in https://github.com/microsoft/vscode/wiki/Performance-Issues are helpful.
