### ISSUE TITLE
Reloading a window should restore the active viewlet

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8269]
Testing #8215

* I installed an extension
* I clicked Enable
* I accepted to restart
* I expected the extension viewlet to come back, preferably with the same search query and the same scroll position that now shows the "Enabled" in green or something.

**Comment by isidorn** [comment]
This is a concussion decision made by our PM team that we always open the explorer viewlet on start.
Anyways, assingning to July and chris to decide if we want to make an exception in this case

**Comment by egamma** [comment]
Deferring to August

**Comment by bpasero** [comment]
As designed, unless @chrisdias says otherwise.

**Comment by alexandrudima** [comment]
But this is not a start. This is a restart initiated from the extension itself.

**Comment by bpasero** [comment]
@chrisdias do you receive GH notifications?

**Comment by bpasero** [comment]
Maybe for when the window reloads we should always restore the last used viewlet. Imho it does not make sense to reload and jump back to the explorer.

@chrisdias point  was to show the explorer when opening a folder or starting VS Code fresh. I can see if this would be possible (e.g. finding out that a window was reloaded).

**Comment by isidorn** [comment]
I do not think we should ever jump back to the explorer - all across our UI we preserve state and I am not sure why explorer is such a special case?

**Comment by bpasero** [comment]
@isidorn it is about helping users to explore a project, if you open a folder from command line with VS Code you do not expect to see the extensions viewlet that you might have had opened 3 months ago. I think it makes perfect sense to show the files of the workspace.

The "Reload Windows" case is special and should restore the last used viewlet.

**Comment by isidorn** [comment]
I thought we would store this per workspace. So if I closed a workspace in git viewlet I would expect to see it on reopen.
Sure on a new workspace we should always show explorer since that would be the default and we wuold not have anything stored per that workspace.

Just my 2 cents

**Comment by bpasero** [comment]
@isidorn we do store it per workspace but you can still have it stored there for 3 months and come back to it and why would you want to see the extensions viewlet then.

**Comment by bpasero** [comment]
Verify: triggering any of the actions that causes a window reload (e.g. from F1, install extension) should restore the viewlet you had active.
