### ISSUE TITLE
IntelliCode keeps breaking for external libraries for Java Development (without any build tools)

### ISSUE THREAD

**Issue by shrinidhi111** [microsoft/vscode#82692]
- VSCode Version: 
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Clone my project from https://gitlab.com/shrinidhiinstasafe/iptables-wrapper 
2. Switch to "new" branch,
3. Install all required Java and Spring Boot extensions,
4. Notice that the import of the jar files from the `external` folder keeps breaking in IntelliCode continously.

Details ::

I am currently doing all the development in a server and use Remote SSH. (It is such an excellent feature).

For this particular Java project, I am not using any build tools like gradle and maven. I created a basic Java project in VSCode and it gave me .project and .classpath files.

I needed to use two external libraries for my project, Json Simple and Hamcrest. I downloaded both the jar files, added them to the project and changed the .classpath to :: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="output" path="bin"/>
	<classpathentry kind="lib" path="external/json-simple-1.1.1.jar" />
	<classpathentry kind="lib" path="external/hamcrest-all-1.3.jar" />
</classpath>
```

Everything works perfectly for sometime. VSCode IntelliCode is able to recognize the libraries, import works, documentation tips while hovering works, even the build works. 

But exactly some 5 mins later, for no reason at all, it stops recognizing the existence of the external libraries completely. 

I tried reloading the window, restarting the server, uninstalling all Java related extensions and installing again but it the exact same behavior.

It simply cannot acknowledge external libraries for more than a few minutes and I have no idea what the cause maybe. After lots of efforts from past few days, I have come to you all for help.

See the below screenshot. This is how it becomes just a few minutes later.

![Screenshot (2)](https://user-images.githubusercontent.com/10372299/66924102-a5695a00-f047-11e9-8662-7912dec440b3.png)

**Comment by roblourens** [comment]
Please file this issue on the intellicode repo https://github.com/MicrosoftDocs/intellicode. It's not clear to me whether you are actually using the intellicode extension but if not, I assume you are using the Java language extension and you can file this issue there: https://marketplace.visualstudio.com/items?itemName=redhat.java
