### ISSUE TITLE
Integrated Terminal is skipping letters randomly

### ISSUE THREAD

**Issue by reaktivo** [microsoft/vscode#82696]
- VSCode Version:  1.39.1
- OS Version: OS X 10.15 Catalina

Steps to Reproduce:

1. Issue randomly occurs while typing in the integrated terminal

<img width="359" alt="Screenshot 2019-10-16 at 16 33 18" src="https://user-images.githubusercontent.com/13637/66930138-739ac800-f034-11e9-8fec-bc03a0b1eab2.png">

**Comment by Tyriar** [comment]
Can you turn on escape sequence logging when this happens so we can see what is being sent to/from the terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging
