### ISSUE TITLE
Open vscode://file/<path> no longer works (no error message)

### ISSUE THREAD

**Issue by devonpmack** [microsoft/vscode#82694]
Issue Type: <b>Bug</b>

1. Developer: Open URL
2. Type vscode://file/\<path\>

Expected Result: File opens
Actual Result: VSCode opens but file does not (no error message)

This used to work but not in the latest few updates. I use a [chrome extension](https://github.com/aberonni/open-in-vscode) to open GitHub files in VSCode but this extension doesn't work correctly without the URL feature of VSCode.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-erb-beautify|ali|0.2.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.1
shopify-i18n|moh|0.0.4
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
debugger-for-chrome|msj|4.12.0
vscode-graphql|Pri|0.2.2
ruby|reb|0.25.3
java|red|0.50.0
LiveServer|rit|5.6.1
stylelint|shi|0.51.0
tabnine-vscode|Tab|2.1.11
vscodeintellicode|Vis|1.1.9
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1

</details>

**Comment by devonpmack** [comment]
Update:
After closing VSCode and then going to the URL it works. But on my friends laptop with same specs (macOS) it has the same problem.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82212
