### ISSUE TITLE
Sudden memory peak

### ISSUE THREAD

**Issue by bergolho** [microsoft/vscode#82690]
Issue Type: <b>Performance Issue</b>

There is an sudden memory peak of 3.0GiB when I am using Visual Studio Code. It last for about 10 seconds, but is enough to generate performance issues

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 5.0.16-100.fc28.x86_64

<details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  3700	code main
    0	    32	  3736	   zygote
    0	    95	  3864	     shared-process
    0	     0	 11030	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   174	 10898	     window (cable_mesh_with_tt3.ini - MonoAlg3D_C - Visual Studio Code)
    0	    95	 10933	       extensionHost
    0	   127	 10937	       watcherService
    0	    79	 10998	     window (Issue Reporter)
    0	   111	  3769	   gpu-process
```

</details>

**Comment by roblourens** [comment]
In what process? What did you do when this happenedd? Does it happen often or just one time ranodmly? Need more details.
