### ISSUE TITLE
Crashes on regex find and replace

### ISSUE THREAD

**Issue by jaydattc** [microsoft/vscode#82698]
On using the below regex (without quotations) in find and replace box, vscode just freezes and and gives a prompt to reopen or close a few seconds after
> "/*(.+)*/"

VSCode version - 1.36.1
OS - Windows 10 1803 x64

**Comment by sksaifuddin** [comment]
I am not able reproduce the issue, Please provide more details or steps to reproduce it.

**Comment by roblourens** [comment]
This regex will suffer from catastrophic backtracking, https://github.com/microsoft/vscode/issues/30874
