### ISSUE TITLE
Manually changing to git-bash in terminal ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#82697]
When in terminal I can change the shell I'm in between powershell and command (DOS) although I can't simply type `git-bash` to change to `git-bash`.  Within the integrated terminal setting for my workspace setting I supplied the path to `git-bash` although that doesn't work, as in; I cannot simple type `git-bash` in the terminal and the shell changes to `git-bash`. 

Must I include not the windows path to the `git-bash` executable, rather the path to either the `.bashrc` or `.bash_profile` file within the workspace setting ? 

I don't want to replace what is the shell for the setting `terminal.integrated.shell.windows` I want to add so I can type `git-bash` and my shell will change to *git-bash*.

**Comment by roblourens** [comment]
If there is an executable named `git-bash` on your PATH, then you can type `git-bash` and the shell will execute it. This doesn't really sound like a vscode issue, sorry.

**Comment by SheepDomination** [comment]
I'm giving it the path to `git-bash` in PATH within my workspace setting but it's not being recognized ?
