### ISSUE TITLE
Not expected } input when using Chinese input method

### ISSUE THREAD

**Issue by yoshiyone** [microsoft/vscode#82701]
Issue Type: <b>Bug</b>

This problem can input } not expected when you are using Chinese input method and trying to delete what you have inputted. Next I will tell you how to repeat this problem:
1. Input a pair of bracket {} in English input method (Or just input a { is also OK to repeat the problem.)
2. Input any letters between the left and right bracket with Chinese input method but don't press Enter or Space or numbers. (So that it doesn't actually written into the file).
3. Press Backspace many times until you have deleted all the letters you have inputted with Chinese input method.
4. You will discover that there is a } inputted onto the screen, which made me mad.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (11.28GB free)|
|Process Argv|D:\study\Jimmy\Experiment_reports\2019autumn\ciguang\ciguang.tex|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.2.0
vscode-language-pack-zh-hans|MS-|1.39.3
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0

</details>

<img width="459" alt="微信图片_20191016231622" src="https://user-images.githubusercontent.com/38660350/66933038-0e15fe00-f06b-11e9-96df-06248c822f8d.png">
<img width="421" alt="微信图片_20191016231709" src="https://user-images.githubusercontent.com/38660350/66933105-2a199f80-f06b-11e9-8be4-4de064f9daba.png">

**Comment by rebornix** [comment]
@alexandrudima is it possible that composition events break the state of bracket pairs?
