### ISSUE TITLE
Potential breakpoint indicators appear in wrong place after editing a file

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#82708]
When editing a file and pressing Save during a debug session, the TypeScript breakpoint indicators end up in the wrong place:

<img width="694" alt="Screenshot 2019-10-16 at 5 01 33 pm" src="https://user-images.githubusercontent.com/1078012/66937161-e147f380-f036-11e9-8b65-44e7b8160445.png">

They were correct until I hit save, then  they jumped into the comment. I don't expect them to be correct (since I've modified the code, but the source maps are based on the old code), but it's weird to have this happen too.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/81986
