### ISSUE TITLE
Unable to create 'launch.json' file inside the '.vscode' folder 

### ISSUE THREAD

**Issue by 3d4d5d17d** [microsoft/vscode#82700]
C++
vscode 1.39.2

After pressing F5 ,there is nothing happening but a window said:
"Unable to create 'launch.json' file inside the '.vscode' folder
 (Cannot read property 'name' of undefined)."
No matter the ".vscode" folder is created, the launch.json wouldn't be created.

**Comment by isidorn** [comment]
Can you reproduce this with vscode insiders?
https://code.visualstudio.com/insiders/

**Comment by anhellwig** [comment]
I don't know of this is related or if I should file another issue. After a fresh install of VS Code and the ms-vscode.cpptools extension, if I open a a .cpp file, press F5 and select "C++ (Windows)", an error message pops up: "Unable to create 'launch.json' file inside the '.vscode' folder (Unexpected token $ in JSON at position 119)." This happens in both 1.39.2 and 1.40.0-insider.

**Comment by isidorn** [comment]
@anhellwig please file that one against the C++ extension. It seems that they might be providing a weird configuratino which can not be json parsed. Thanks

**Comment by FantasqueX** [comment]
Same problem🙃

**Comment by xiehao** [comment]
Same problem.

**Comment by JanHelbling** [comment]
Same Problem

**Comment by AsceticBoy** [comment]
Same Problem

**Comment by JanHelbling** [comment]
> I don't know of this is related or if I should file another issue. After a fresh install of VS Code and the ms-vscode.cpptools extension, if I open a a .cpp file, press F5 and select "C++ (Windows)", an error message pops up: "Unable to create 'launch.json' file inside the '.vscode' folder (Unexpected token $ in JSON at position 119)." This happens in both 1.39.2 and 1.40.0-insider.

I've the same Problem with Linux: (Unexpected token $ in JSON at position 113), for my this .vscode config is working:  [vscode.zip](https://github.com/microsoft/vscode/files/3750124/vscode.zip)

**Comment by isidorn** [comment]
This works fine for me.
![hello](https://user-images.githubusercontent.com/1926584/67210311-2a25f080-f419-11e9-9b36-310da17fde7c.gif)

Please file against C++ extension here https://github.com/microsoft/vscode-cpptools

**Comment by isidorn** [comment]
Actually here is the issue, please follow it there https://github.com/microsoft/vscode-cpptools/issues/4464
