### ISSUE TITLE
Wrong syntax highlighting with division on new line

### ISSUE THREAD

**Issue by klinki** [Microsoft/vscode#8270]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Start any valid arithmetic expression 
2. Place / on new line

Screenshot: 
![syntax-hl](https://cloud.githubusercontent.com/assets/1476175/16410486/f8332350-3d22-11e6-8e90-dd1e2ad4838e.png)

**Comment by bpasero** [comment]
@klinki what language are you in?

**Comment by klinki** [comment]
TypeScript but it is the same for JavaScript as well.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#198
