### ISSUE TITLE
Integrated Terminal Not Working

### ISSUE THREAD

**Issue by micahpearlman** [microsoft/vscode#82709]
Issue Type: <b>Bug</b>

Integrated terminal does not load and cannot select a "default shell".

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.35GB (23.99GB free)|
|Process Argv|/home/micahpearlman/dev/work/fs/thirdwave/forklift-sim/tw-forklift-sim-unity -g /home/micahpearlman/dev/work/fs/thirdwave/forklift-sim/tw-forklift-sim-unity/Assets/TWSim/Scripts/VehicleControllers/TWRaymond7500VehicleController.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.5
path-intellisense|chr|1.4.2
xml|Dot|2.5.0
docker-explorer|for|0.1.6
auto-using|Fud|0.7.9
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.8
unity-code-snippets|kle|1.3.0
shaderlabformatter|lit|0.3.0
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
csharp|ms-|1.21.5
shader|sle|1.1.4
urdf|smi|0.1.0
unity-tools|Tob|1.1.1
unity-debug|Uni|2.7.2
vscode-lldb|vad|1.3.0
cmake-tools|vec|1.1.3
clang-format|xav|1.9.0

</details>

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by chikaj** [comment]
My setup is a little different than above, but I have the same issue.

![integrated_terminal_not_working](https://user-images.githubusercontent.com/10135346/66974334-5c71cf80-f060-11e9-8028-c25df24cd558.png)

Version: 1.40.0-insider
Commit: be68a4e14c28cc81cdf422739af23123b3c91fd2
Date: 2019-10-16T09:58:27.703Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-31-generic snap

**Comment by micahpearlman** [comment]
I uninstalled and reinstalled and now it works.  :-/

**Comment by Tyriar** [comment]
@micahpearlman did you reinstall using the snap?

@chikaj any errors in devtools? Can you share your settings.json file? Trace logging could help identify where the init process breaks down https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by micahpearlman** [comment]
@Tyriar I did reinstall using snap.  FYI:  My issue looked exactly the same as @chikaj

**Comment by micahpearlman** [comment]
FYI: The issue came back.  Not clear if it auto-updated and I didn't notice.

**Comment by micahpearlman** [comment]
Video of the issue: https://www.dropbox.com/s/ikt3ymnz41s9nmv/broken-vscode-integrated-terminal.mp4?dl=0

**Comment by Tyriar** [comment]
@micahpearlman please try enabling trace logging and see what the logs say when you open a terminal https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by micahpearlman** [comment]
@Tyriar `[2019-10-18 09:35:26.421] [renderer3] [error] A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'`

**Comment by Tyriar** [comment]
Ah, remove the inheritEnv setting

/duplicate https://github.com/microsoft/vscode/issues/76542
