### ISSUE TITLE
Quick fix doesn't show add import option when it should

### ISSUE THREAD

**Issue by jmbockhorst** [microsoft/vscode#82717]
Quick fix doesn't show add import option when there is an import option. Intelisense shows the auto-import. This happens in a simple React, Webpack, Javascript app.

![quickFixImport](https://user-images.githubusercontent.com/44308390/66943692-50aaec80-f011-11e9-8f0b-f66050c4cdba.gif)

Version: 1.40.0-insider (user setup)
Commit: 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Date: 2019-10-15T05:26:38.861Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18990

Steps to Reproduce:
1. Create simple react app (create-react-app)
2. Create a class
3. Use that class in another file without importing with intelisense
4. Try to use quick fix to import it

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Try creating a simple [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) at the root of your project:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```
