### ISSUE TITLE
Choosing Search Marketplace causes VSCODE to search endlessly (no timeout)

### ISSUE THREAD

**Issue by rsramkis** [microsoft/vscode#82712]
For the past month I have noticed that I am unable to see any extensions which were installed or able to see any extensions which I could choose to install. The activity cursor moves across the screen (left to right) and never seems to finish. I can use the filter "@sort:name " and the cursor stops moving. But then no inventory of possible extension shows.

Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:30:33.955Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.79-1-MANJARO

Steps to Reproduce:

1.Open VS Code
2.Open Extensions Market place.
3.Marketplace busy cursor will update showing no extensions loading.

![Screenshot from 2019-10-16 12-57-08](https://user-images.githubusercontent.com/14362317/66941270-8bfaea80-f014-11e9-93cf-50e21536445a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rsramkis** [comment]
Did some additional looking around and noticed that \\Home\.vscode\extensions directory does not appear to update. I can see all the plugins I had previously installed when extensions was working.

To troubleshoot I renamed the 'extensions' directory to 'extensions-old'. When I launch Visual Studio Code the extensions directory gets re-created but no content is put in the directory.

**Comment by rsramkis** [comment]
Any update on this issue?

Do you need me to disable the extension? If yes, how should I do it?

**Comment by sandy081** [comment]
Can you please try with our insiders and let us know if you see the issue?

https://code.visualstudio.com/insiders/

**Comment by rsramkis** [comment]
I re-tested 2 days ago with the below release and it all of a sudden the market place started working. Its too bad we did not capture any debugging prior.

Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.81-1-MANJARO snap
