### ISSUE TITLE
Can't get out of 'Recording Keys'

### ISSUE THREAD

**Issue by tshino** [microsoft/vscode#82714]
Issue Type: <b>Bug</b>

1. Open Keyboard Shortcuts by CTRL+K CTRL+S
2. Start Recording Keys by ALT+K
3. Stop it by ESC key
4. Again start Recording Keys by ALT+K
5. Again stop it by ESC key

Then, if I hit some keys like the Space key, it shows "space" on the search input box.
The expected result is just a space character not spelling "space".
It is expected that the Recording Keys mode has been stopped, but it seems not.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by mceachen** [comment]
FWIW I haven't seen this bug in prior versions, and *man* is it frustrating. `Reload window` fixes it, but that's a pretty big hammer.

**Comment by chrisdias** [comment]
I see this on Mac, insiders as well.

**Comment by SpontaneousDuck** [comment]
Another way to reproduce:
1. Enable record keys and enter any key combination
2. Close the keyboard shortcuts tab
3. Open the keyboard shortcuts tab again and disable record keys without hitting anything else.
4. The search will now be stuck in record keys mode and toggling the record keys option has no effect

**Comment by sandy081** [comment]
This was broken while adopting to disposable store - e8b2096646935502b1af21e5cf888539ffe8a1ce @mjbvz FYI

This is because the disposable store that holds recording listeners is getting disposed on stopping recording. Instead it has to be cleared because the recording listeners are added to the same store after starting recording again.

**Comment by mjbvz** [comment]
Sorry about that @sandy081. Fix looks good to me

**Comment by chrisdias** [comment]
I tested out of sources and it looks good there.
