### ISSUE TITLE
Missing a global command to open markdown preview to the side

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8271]
Refs: https://github.com/Microsoft/vscode/issues/7945

We should add one.

**Comment by kieferrm** [comment]
@bpasero Can you pls clarify: What do you mean by global command?

**Comment by bpasero** [comment]
@kieferrm in the F1 command palette

**Comment by kieferrm** [comment]
The issue was that the command declaration was missing a category. Thus, it showed up under "Open to the Side" rather than "Markdown: Open to the Side".
