### ISSUE TITLE
Conda-based python debugging is broken

### ISSUE THREAD

**Issue by baumatron** [microsoft/vscode#82725]
Issue Type: <b>Bug</b>

1. Install python and libraries via conda
2. Write a script that uses said version of python and libraries
3. Select the conda environment option in vscode
4. Launch debugger with config:
       {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
Expected:
program runs
Actual
Python throws an exception because it doesn't find the installed libraries. Program runs fine from an anaconda prompt.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
vscode-npm-script|eg2|0.3.9
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|0.19.0
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
debugger-for-edge|msj|1.0.11
vscode-jest|Ort|3.0.2
vscode-hexdump|sle|1.7.2

</details>

**Comment by baumatron** [comment]
Only seem to be able to get this to work when I launch vscode from the anaconda command prompt.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
