### ISSUE TITLE
Internal line breakpoint dots create difficult editing

### ISSUE THREAD

**Issue by eddie-at-curve10** [microsoft/vscode#82721]
Issue Type: <b>Feature Request</b>

In a recent release, when there is a breakpoint on a line where there are multiple steps (using node.js, so javascript), the dot that indicates there's a breakpoint appears throughout the line.

This makes it very difficult to see where the cursor is and how you can edit the line... while I appreciate the idea, it's quite cumbersome and would request to provide a way to turn that off or just remove it altogether.

Having said that, I continue to be impressed with the product and all the great improvements!!!

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 18.7.0

**Comment by roblourens** [comment]
This is by design, when there are multiple valid spots to set a breakpoint. If you are seeing it in places where you don't expect to see it (like where chrome devtools doesn't show the same thing) then please give a code sample and screenshot.
