### ISSUE TITLE
New .NET Core MVC mvc missing references

### ISSUE THREAD

**Issue by schoesa** [microsoft/vscode#82724]
I have created a new .NET Core MVC app (3.0.0) via CLI (dotnet new mvc). After opening the folder in VS Code I get missing references and assemblies infos. VS Code wants several times to restore the project, but with no effect.
<img width="1433" alt="screenshot" src="https://user-images.githubusercontent.com/34265840/66956520-cf7d4500-f064-11e9-98e8-e736c51ab85e.png">

- VSCode Version: 1.39.2
- OS Version: 10.15 (Catalina)

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Steps to Reproduce:

1. Create a new mvc app with dotnet new mvc
2. Open VS Code
3. Missing references and assemblies

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension: https://github.com/OmniSharp/omnisharp-vscode
