### ISSUE TITLE
Markdown: navigating to local links jumps to source file

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8272]
Refs: #7945

On Mac this seems to work nicely, but on Windows when I click on a local anchor, I am jumping into the markdown source code?

The document I used was this: http://daringfireball.net/projects/markdown/syntax.text

**Comment by kieferrm** [comment]
That is a regression introduced by https://github.com/Microsoft/vscode/commit/0a386aea9cd22a246cf3b6a23a378cd7ae9c2d3a.
