### ISSUE TITLE
CSS property completion with semicolon: multiple semicolons

### ISSUE THREAD

**Issue by JBrown-Ascedia** [microsoft/vscode#82726]
If the wrong property is completed and you backspace to delete then tab to complete the correct property, another semicolon is outputted.

Suggestions:
On the deletion of the colon, delete the semicolon.

OR

On completion of the correct property, check to see if semicolon already exists.

**Comment by octref** [comment]
Verifier:
- Try you can complete `.foo { colo|: ; }` to get `. foo { color: ; }`
- Try you can complete `.foo { colo; }` to get `.foo { color: ; }`
