### ISSUE TITLE
VSCode draws 1-pixel black line on adjacent monitor when maximized

### ISSUE THREAD

**Issue by kjcolley7** [microsoft/vscode#82723]
Issue Type: <b>Bug</b>

When VSCode is maximized on a monitor, it will draw a 1-pixel black line on the adjacent monitor. It appears to be like a border around the window that only appears when VSCode is maximized. I'm using the dark theme in VSCode, so maybe the line would be a different color if I were using a different theme.

For example, if you only have VSCode open and no other apps, and VSCode is maximized on your right monitor, then on your left monitor the far-right column of pixels above the task bar will be a black line drawn by VSCode, even though it isn't on this monitor at all.

This might be a generic Electron problem rather than a VSCode problem, but I'm not sure. I say this because Microsoft Teams exhibits a similar problem when maximized, except the line that it draws on the opposite monitor is far more noticeable because it is white instead of black. Even if it is a generic Electron problem, maybe VSCode can come up with some workaround for this issue.

Here are screenshots displaying the issue. This screenshot is taken across the top corner of two monitors. Here's what it looks like when file explorer is the top (active) window (no black line):

![File explorer on top, no black line](https://i.imgur.com/ObzcVjy.png)

And here's what it looks like when VSCode is the top window (gray line):
![VSCode on top, black line](https://i.imgur.com/DNn4njy.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.19002

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
@kjcolley7 can you reproduce with running other Electron apps or even just Electron itself? https://github.com/atom/electron or Electron Fiddle: https://electronjs.org/fiddle
