### ISSUE TITLE
Remote paths aren't generally handled correctly in cross-OS remote window

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82739]
path.ts has implementations of path helper functions for win32 and posix paths. It picks the implementation to use based on `process.platform`: https://github.com/microsoft/vscode/blob/master/src/vs/base/common/path.ts#L1673-L1686

This is not correct because a window on Linux can be connected to a Windows remote, and handle Windows paths, and vice-versa. These functions are used in a lot of places and almost all of the time, they are dealing with paths on the same local machine, but there are a few that seem wrong.

I think it causes these issues:

![image](https://user-images.githubusercontent.com/323878/66970204-76e88080-f041-11e9-9087-639a173b7de8.png)

![image](https://user-images.githubusercontent.com/323878/66970217-87006000-f041-11e9-916a-d1ccfdeb6f04.png)

Maybe https://github.com/microsoft/vscode/issues/77303

We should either
- Add a set of functions that can detect the path type and pick the correct implementation based on that
  - This is hard for the edge cases and potentially slow, if you look at all the work the two `parse` functions do
- Pick the path implementation based on the remote OS
  - Then we would also have to keep track of whether this is a local path or a remote path

These functions are used in 1000s of places so I'm guessing that this will just be an opt-in thing for paths that are known to be remote, otherwise it could be very painful.

**Comment by roblourens** [comment]
We could add a service which uses `IRemoteAgentService#getEnvironment` and exposes the right paths implementation

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/remote/common/remoteAgentService.ts#L24

**Comment by alexandrudima** [comment]
I'm not sure what the screenshot shows, but that looks like a place which does not use the `ILabelService`. The `ILabelService` is the place which knows how to render URIs, even `vscode-remote` ones, correctly.

cc @isidorn

**Comment by roblourens** [comment]
This is about path manipulation, not rendering URIs. The first one uses https://github.com/microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L389 which is not correct.

The label service is one place these functions could live. They should probably be based on the uri formatter's registered separator, not the remote OS like I said before. @isidorn I can't remember why the formatter registers which separator to use though. Is there a case where Windows would have to use `/`?

**Comment by chrmarti** [comment]
Remote Containers has some code that deals with both local and remote paths. That code is using URIs for representation and `path.posix` for path manipulation. Not sure if that can be used in general, but that at least pushes the awareness if a path is local or remote away from common code towards fewer places.

**Comment by aeschli** [comment]
@roblourens On the renderer: Don't use path. Stick with URI's and use the util `resources.ts` that contains all the path manipulation APIs like `basename`, `dirname`, `join`, `resolve`  but for URIs. Use the LabelService for rendering.
In extensions: Workspace extensions typically deal with workspace paths and they are local `file`. So you can use `path` as usual. UI extensions (like resolvers) see `vscode-remote` URIs and need to use `path.posix` for manipulating these URIs. (Again, stick with URIs, never use `resource.fsPath` unless it's a `file` URI)

There are not many usages of `path` anymore in our code as you can see. Most code now uses resources.
![image](https://user-images.githubusercontent.com/6461412/67042706-b76ef980-f128-11e9-9fff-1e3b35306d3d.png)

**Comment by roblourens** [comment]
I agree that we should use URIs whenever possible. I think that is still quite a few references. There are definitely some places where we start with URIs then use path methods on the .fsPath or .path where we could probably use `resources.ts` instead. 

There are places where we never have URIs, or have user input or path fragments. This affects search quite a bit. Here is a better example bug: in quick open, you can enter an absolute path and it will let you open that file directly. We check the user input with `isAbsolute`, in code running locally, and know it refers to a remote path. So here I will use the new stuff I'm adding to do `isAbsolute` correctly for the remote type.

**Comment by roblourens** [comment]
Then trying to use this to fix a bug, I realize that `URI.file` doesn't work for windows-type paths on Linux because it is platform-dependent too. 

I am trying to convert a windows path for a file on the remote to a remote URI. So I think what I want to do is

```
toLocalResource(URI.file('C:\\foo'), authority)
```

(where toLocalResource converts to a remote resource when you pass an authority)

You could argue that `URI.file` with a windows path on a non-windows OS doesn't make sense, then I just need some other way to get the path in the right format to build a remote URI. @jrieken could `URI.file` take an optional parameter `isWindows`?

**Comment by roblourens** [comment]
I pushed a RemotePathService (feel free to suggest a better name). I added a method to create a file URI without the local `isWindows` check because I figured that's the best way to illustrate the actual problem.

I also fixed the quick open bug I mentioned above.

**Comment by roblourens** [comment]
Related to all of this, there is a `isWindows` reference in LabelService which causes Windows path labels to be formatted incorrectly on non-Windows: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/label/common/labelService.ts#L74

**Comment by isidorn** [comment]
@roblourens that seems incorrect. For that I filled this issue https://github.com/microsoft/vscode/issues/82821

**Comment by aeschli** [comment]
@roblourens 
If I understand right, the issue is that you have the list of the current workspace folders and a search string that needs to be untildified and verified (turned in an URI).
Workspace folders are typically all local or all remote, but you can also consist of URIs of other file system providers, think of `remotehub:/...`. or ftp ect.

IMO the untildifying and verifying needs to happen on the search provider of each folders file search provider. Why not passing the raw search string to each provider which knows its OS and it home directory.

I'd rather wait with adding a RemotePathService before we need it at multiple places.

**Comment by stevenguh** [comment]
I would also like to add to it as an extension developer, handling path for remote host without local installation is extremely difficult to account for all the edge cases because of the early separator normalization for windows host.

Some API issues I ran into:

1. `Uri.fsPath`:
- Return path with the host's separator which means
    + `C:/path/to/file` is returned if *nix remoting into a Windows
    + `\path\to\file` is returned if Windows machine remoting into *nix
    + Normalization to Windows path (`\` separator, *nix remoting  into Windows) cause any path that has `\` in the *nix remote indistinguishable from separator. Hence, force developer to use other properties like `Uri.path` to handle the case when a path contains `\` character in the *nix remote.

2. `workspace.asRelativePath`:
- Always return `/` as separator if the input uri is in any of the workspace folders.
- Else return `Uri.fsPath` of the input uri
    + The normalization of `Uri.fsPath` means that it will return path with `\` on Windows machine
    + The inconsistent separator will make this API difficult to use and as well as to handle the edge case I mentioned above

3. Lack of API to detect if the remote environment is Windows or *nix.

Overall, path manipulation as developer seems to more difficult than I would expect especially factoring into vscode-remote. I apologize if this comment is not related to this issue. Please let me know if I should open a new issue.

**Comment by roblourens** [comment]
@stevenguh that all sounds like it should be looked into. Could you please open a new issue?

I'm going to close this one, it was regarding some internal issues but it's not clear that there is any remaining actionable issue. I know that Ben or other people did more work in this direction at some point.

**Comment by stevenguh** [comment]
@roblourens Thank you for your response. Just want to make sure I do the right thing here, should this new issue be bug/feature request? I can see it being applicable either way.

**Comment by roblourens** [comment]
I could see it either way too, just give us the details we'll work it out 😁

**Comment by stevenguh** [comment]
Opened #105969 🙂 Let me know any of the described issues is confusing.
