### ISSUE TITLE
Quick open can be too narrow to show file name

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#82737]
Steps to Reproduce:

1. Add a file with long name
2. Search for it with quick-open (cmd-p)

Actual behavior:
The filename is truncated with a ... at the end

Expected behavior:
The filename does not overflow by either wrapping to a second line or resizing the quick open box

Note: I can see the width is set to 600px here: https://github.com/microsoft/vscode/blob/c21f5c293bd727d23feaf914d832c38ab27bd95b/src/vs/base/parts/quickopen/browser/quickopen.css#L8

**Comment by dalongi** [comment]
@bpasero: Is there a reason for choosing 600px? Our repo has some longer filenames coming out of codegen. Multiple files are prefixed similarly but differ at the end of the name -- but this end is truncated in the current UI so it appears we get duplicate results.

**Comment by bpasero** [comment]
No real reason, has been like this since day 1.
