### ISSUE TITLE
Improve Search History

### ISSUE THREAD

**Issue by DStradley** [microsoft/vscode#82731]
1. Keep search histories across runs of VSCode (don't lose them on exit)
2. Have some sort of pulldown menu, or some such, to see list of history and pick from with mouse

(See Visual Studio for possible examples of both of these)
#2 would also help with discoverability of even having a search history

**Comment by roblourens** [comment]
1 already should work, they are saved per workspace. If it doesn't work for you, please give some more details.

2 is tracked here: https://github.com/microsoft/vscode/issues/23099

**Comment by roblourens** [comment]
The ctrl+f history is saved per file, and persisting it could end up producing a ton of data. So I think this is by design.

**Comment by DStradley** [comment]
Thankfully, the ctrl+f history is NOT per file, at least not in typescript files (what I mainly edit).  That would be a pain.

Actually, I would not mind if ctrl+f history was shared with the global search history (like Visual Studio).  There are a lot of times I search local to a file, then end up doing a global search for the same thing.

But if others find a shared history not viable for some reason, then I would still request that the ctrl+f history be persisted.
