### ISSUE TITLE
With Remote Development, WebView with portMapping does not work well.

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#82735]
VS Code
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

macOS High Sierra 10.13.6（17G8037）

Steps to Reproduce:

1. Execute the following `t.js` in a remote system.
2. Execute the following sample code with Remote Development in the remote system.
3. Any request to `http://127.0.0.1:3000/?file=abc` is not sent. And the webview is blank. Even an indicator of a corrupted image is not displayed.

With both docker container and ssh remote server, this does not work well.

`t.js`

```javascript
var http = require('http');
var server = http.createServer();

server.on('request', function(req, res) {
    console.log(req.url)
    res.writeHead(200, {'Content-Type' : 'text/plain'});
    res.write('hello world');
    res.end();
});

server.listen(3000);
```

Sample code.

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  const rootUrl = vscode.Uri.file(context.extensionPath)
  const disposable = vscode.commands.registerCommand('extension.helloWorld', async (args, brgs, crgs) => {
    if (!vscode.window.activeTextEditor) {
      return;
    }
    
    const panel = vscode.window.createWebviewPanel(
      'catCoding',
      'Cat Coding',
      { preserveFocus: true, viewColumn: vscode.ViewColumn.Beside },
      { enableScripts: true, localResourceRoots: [ rootUrl ],
        portMapping : [{webviewPort: 3000, extensionHostPort: 4000}]
        }
    );
    panel.webview.html = getHtml();
  });
  context.subscriptions.push(disposable);
}

function getHtml() {
	return `
<!DOCTYPE html><html>
<img src='http://127.0.0.1:3000/?file=abc' />
`;
}

// this method is called when your extension is deactivated
export function deactivate() {}

```

![スクリーンショット 2019-10-17 8 29 51](https://user-images.githubusercontent.com/10665499/66966532-7dfea580-f0b8-11e9-8e3c-01f8ea72b9b6.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This works for me but I think you have your ports mixed up. The server is spawned on port `3000` so `extensionHostPort` should be `3000`, not `4000`. What do you see if you run `Developer: Toggle Webview developer tools`?

However I did discover a nasty infinite redirects bug if you set `webviewPort` and `extensionHostPort` to the same value (`3000`). Will push fix for that to next insiders build

**Comment by tamuratak** [comment]
Thank you. I try it later.

**Comment by tamuratak** [comment]
I have confirmed WebView works as expected if setting `4000` to `extensionHostPort`. 

![スクリーンショット 2019-10-17 19 52 48](https://user-images.githubusercontent.com/10665499/67002950-e2048680-f117-11e9-9cd3-28822378994a.png)

And, the problem of the same ports you describe is the one I encountered with LaTeX Workshop and Remote Development. Thank you.
