### ISSUE TITLE
Terminal colors not working with python print

### ISSUE THREAD

**Issue by st3v0** [microsoft/vscode#82738]
- VSCode Version: 1.32.3
- OS Version: Windows_NT x64 10.0.17134

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

![terminal-colors](https://user-images.githubusercontent.com/2800093/66967521-88bf3780-f0c4-11e9-9c63-d769f473dd97.png)

Steps to Reproduce:
1. Create a python file with the following content: (I was using python 3.6)
```python 
print("\033[94m BLUE \033[0m")
print("\033[32m GREEN \033[0m")
print("\033[33m YELLOW \033[0m")
print("\033[91m RED \033[0m")
```
2. Run in vscode git-bash terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
