### ISSUE TITLE
Large text file content not updated when the file is changed

### ISSUE THREAD

**Issue by limaoyang** [microsoft/vscode#82736]
Issue Type: <b>Bug</b>

I opened a log file of ~400mb. Close it, has a new log file replaced the last one on the same location and name. VScode is still showing the content of the last file when I open it.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|2.0.190927009
cpptools|ms-|0.26.0

</details>

**Comment by bpasero** [comment]
@limaoyang I need exact steps how to reproduce step by step
