### ISSUE TITLE
Open binary files directly without displaying the "Do you want to open it anyway?"

### ISSUE THREAD

**Issue by iruletheworld** [microsoft/vscode#82730]
🚨 The issue tracker is not for questions 🚨
Is there any way to disable the warning when trying to open a binary file, i.e., the "Do you want to open it anyway?" warning. 

I have LaTex-Workshop installed which can view PDFs but I would have to click on the warning to get a PDF viewed. It would be nice if could just disable this warning.

**Comment by mjbvz** [comment]
Not currently but the feature request falls under #82115
