### ISSUE TITLE
cmd-shift-l (multicursor select) no longer works

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#82743]
Issue Type: <b>Bug</b>

I haven't touched my keybindings and a behavior that used to work no longer does.

I'm attaching an image of keybinding search - this keybinding shows only one match which i assumes means this keybinding is still associated with the action I am expecting and what was the old default behavior.

![image](https://user-images.githubusercontent.com/434034/66975632-5548c280-f05c-11e9-8a16-82404663abf6.png)

The behavior I am expecting is to select all text in the editor window matching the highlighted text with multi-cursor selection.  It doesn't work anymore (even if I invoke the operation above via cmd-shift-p).

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|../../itsacheckmate.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
vscode-erb-beautify|ali|0.2.0
vscode-apollo|apo|1.11.0
atlascode|atl|2.1.1
ohm|att|1.0.0
better-toml|bun|0.3.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
erb|Cra|0.0.1
vscode-markdownlint|Dav|0.31.0
vscode-eslint|dba|1.9.1
vscode-dash|dee|2.2.0
githistory|don|0.4.6
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.1.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
simple-new-file|fay|1.1.1
vscode-pull-request-github|Git|0.12.0
path-autocomplete|ion|1.13.3
vscode-heroku|iva|1.4.3
search-node-modules|jas|1.3.0
vscode-rufo|jnb|0.0.1
vscode-mdx|Jou|0.1.3
vscode-gutter-preview|kis|0.23.0
restructuredtext|lex|114.0.0
fish-ide|lun|0.4.0
bash-ide-vscode|mad|1.3.3
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
Go|ms-|0.11.7
vsliveshare|ms-|1.0.950
debugger-for-chrome|msj|4.12.0
sqltools|mtx|0.21.0
vscode-versionlens|pfl|0.24.0
gitlink|qez|0.5.1
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
bash-debug|rog|0.3.6
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
fish-vscode|sky|0.2.1
vscode-hexdump|sle|1.7.2
cmake|twx|0.0.17
highlight-matching-tag|vin|0.9.5
simple-ruby-erb|vor|0.2.1
vscode-ansible|vsc|0.5.2
quokka-vscode|Wal|1.0.256
wallaby-vscode|Wal|1.0.151
vscode-import-cost|wix|2.12.0
vscode-mdx-preview|xyc|0.2.2

</details>

**Comment by alexandrudima** [comment]
@breathe `cmd+shift+L` will respect the find widget modifiers (whole words, match case). If you start it without having a selection, it will expand to search for the current word with the settings whole words, match case. Have you tried tweaking those?

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/67095531-6ad1ff80-f1b6-11e9-8b55-4dcbb99a8da4.gif)
