### ISSUE TITLE
Can't copy command to primary selection on marketplace

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#82747]
When you view an extension in the Visual Studio marketplace, and click the installation command, the whole textbox is highlighted. This prevents you from highlighting it with the mouse, and thus breaks primary selection. The copy button also doesn't copy into primary selection.

**Comment by LinAGKar** [comment]
The website, e.g. `https://marketplace.visualstudio.com/items?itemName=ms-python.python`.

**Comment by roblourens** [comment]
That button should launch vscode. Not sure which textbox you are talking about.

**Comment by LinAGKar** [comment]
What button? The only button there is the button to copy to clipboard under "Installation", near the top of the page, and the textbox is right next to it.

**Comment by roblourens** [comment]
On other systems, we see this:

![image](https://user-images.githubusercontent.com/323878/67254546-76c9f580-f432-11e9-82f2-3e8a015b8f97.png)

I forgot that you can also get

![image](https://user-images.githubusercontent.com/323878/67254564-8fd2a680-f432-11e9-853e-1c070200db33.png)

I see that the copy button doesn't work. I don't see

> click the installation command, the whole textbox is highlighted

which browser are you using?

I will try to forward your feedback to the team that owns this site.

**Comment by LinAGKar** [comment]
I've tried it in both Firefox and Chromium, and it auto highlights it in both. In Chromium, the text is apparently put into primary selection when it auto highlights or you press the "Copy" button, but in Firefox it's nearly impossible to get it into primary selection.

**Comment by pkuma-msft** [comment]
HI @LinAGKar , can you confirm that you are trying this from a linux machine?

**Comment by LinAGKar** [comment]
I am, yes.

**Comment by roblourens** [comment]
Still doesn't work, but this has been sent upstream to the marketplace team.
