### ISSUE TITLE
Latest version not showing on marketplace after running `vsce publish`(however showing inside VS Code)

### ISSUE THREAD

**Issue by chenyong** [microsoft/vscode#82746]
- VSCode Version: 1.39.1
- OS Version:  Darwin x64 17.5.0

Steps to Reproduce:

1. visit https://marketplace.visualstudio.com/itemdetails?itemName=chenyong.jimeng-react-snippets, the latest version is `0.1.5`
2. search "jimengio" in VS Code extensions, the latest version is `0.1.6`

Does this issue occur when all extensions are disabled?: Yes

Details:

I published my package with `vsce publish` command, but found the marketplace website not showing the latest version `0.1.6` after days. I tried to publish again with same version, it shows that the version already existed:

```
=>> vsce publish
Publishing chenyong.jimeng-react-snippets@0.1.6...
 ERROR  chenyong.jimeng-react-snippets@0.1.6 already exists. Version number cannot be the same.
=>> vsce --version
1.67.1
```

but I checked in VS Code later `0.1.6` is listed in search results. Probably a bug in the website of marketplace. It's still showing the old version:

https://marketplace.visualstudio.com/itemdetails?itemName=chenyong.jimeng-react-snippets

```
Version | 0.1.5 |  
-- | -- | --
Released on | 4/10/2019, 11:24:12 AM |  

Last updated | 10/14/2019, 3:07:13 PM |  
Publisher | ChenYong |  
Unique Identifier | chenyong.jimeng-react-snippets
```

`2019-10-14` is the correct date I published by `0.1.6`.

**Comment by sandy081** [comment]
Could be a caching issue on market place. 

@kesane-msft  FYI. If possible please create an issue in Marketplace repo.

**Comment by kesane-msft** [comment]
@sandy081 could this be related to #83926

**Comment by sandy081** [comment]
You are right it is.

**Comment by chenyong** [comment]
> which fails the version validation on Marketplace

what does it mean? I didn't see warning related to validations.

**Comment by kesane-msft** [comment]
@chenyong - whenever you publish a new extension or an update to an existing extension on the Marketplace, there are a few extension validations that are performed. You would be receiving an email in case of version validation failing. Additionally you would even be able to see the same in the Marketplace publisher portal for  your publisher.

**Comment by chenyong** [comment]
got some error....

![image](https://user-images.githubusercontent.com/25790987/69302122-959af200-0c53-11ea-964d-413cd4bc26d6.png)

> Something went wrong, please retry after sometime.

![image](https://user-images.githubusercontent.com/25790987/69302154-a8152b80-0c53-11ea-803c-1a75c94ad5b1.png)

at least it's working now in 0.1.8 .

**Comment by kesane-msft** [comment]
@chenyong - Yep, that is the email. We had a transient issue on the Marketplace side which was resulting in some extension validation failures around 11th October. I see the failure mail is around the same time. That issue has been identified and fixed and your extension publishing should go through smoothly.

**Comment by chenyong** [comment]
cool.
