### ISSUE TITLE
Is there a way to get supports provides by the vs code to the.js file types to a custom extesion type

### ISSUE THREAD

**Issue by Wathsara** [microsoft/vscode#82749]
We don't need to add a third-party extensions for the .js file types to edit in vscode. What I need is I am going to create a file with .abc extension type and still I need to get the syntax highlight and the keyword suggestions provided by the vscode to the js files to my extension type as well. Is there a way to bind .js type with .abc type

**Comment by roblourens** [comment]
Yes, see the `files.associations` setting, it is for exactly this purpose.

**Comment by Wathsara** [comment]
can I append my own set of keywords to the completion list when creating this method? example i have .abc extension and 
```
"files.associations": {
			"*.abc": "javascript"			
		}

```
and also I need to set of keywords to send onCompletion in .abc extension type as well.
