### ISSUE TITLE
Drag-lock mouse device not supported

### ISSUE THREAD

**Issue by BCSharp** [microsoft/vscode#82745]
Issue Type: <b>Bug</b>

I am using a trackball (Kensington SlimBlade) on which one button is configured as drag-lock (simulating left click and hold). It works in every Windows application (inc. Visual Studio), but not in Visual Studio Code.  I cant't even select text in this way.

How to reproduce:
1. Install Kensington SlimBlade
2. Configure one button to be drag-lock
3. Open VS Code with any text file
4. Click the drag-lock button over the text and move the cursor with th trackball => selection is NOT being made
5. Open Visual Studion 2019 with any text file
6. Click the drag-lock button over the text and move the cursor with th trackball => selection is being made

Expected: VS Code supports drag-lock functionality like VS and any other application.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.1
python|ms-|2019.10.41019
cpptools|ms-|0.25.1
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vs-keybindings|ms-|0.2.0

</details>

**Comment by roblourens** [comment]
Do you have any other Electron apps you could test it with? Atom, Slack, etc

**Comment by BCSharp** [comment]
No, but will install one of them and test it.

**Comment by BCSharp** [comment]
Tested with Atom, it has the same problem as VS Code.

**Comment by alexandrudima** [comment]
@BCSharp VS Code is built on Electron, which is built on Chromium. I think this is an issue in how Chromium maps raw mouse events to w3c mouse events (which we use).

Could you please try to select in the editor at https://microsoft.github.io/monaco-editor/ in Chrome and in Firefox/Edge (the one that is not based on Chromium)? Does selecting in any one of those work as expected?

**Comment by BCSharp** [comment]
Tested Monaco with Chrome 77.0.3865.120 (Official Build) (64-bit): the drag-lock problem **exists**.
Tested Monaco with Firefox 69.0.3 (64-bit): the drag-lock functionality works fine.
Tested Monaco with Microsoft Edge 44.18362.387.0 (uses EdgeHTML 18.18362): the drag-lock functionality works fine.

The above tests are on Windows 10 (ver. 1903). 

Further: Drag-lock in VS Code on macOS (10.13.6) and Ubuntu Linux (18.04.3)  works just fine. But then again, those OSes use different input device drivers.

**Comment by dojiao** [comment]
I have the same problem with BCSharp. Somehow I meet it in contrast scene. 
1. My mouse didn't open drag-lock
2. VS Code 1.39.2/Chrome 75.0.3770.100 on Ubuntu (18.04.3) could not select normally in editor.
3. VS Code/Chrome on Windows 10 (ver.1903) has no problem.

Otherwise, selecting works out of editor's area.

**Comment by BCSharp** [comment]
@alexandrudima, is there any more info needed to complete triaging this issue?

**Comment by alexandrudima** [comment]
Thank you for the extra information. AFAICT this is an upstream issue with Chromium. The next step to get this resolved would be to create a separate HTML page that logs the mouse down, mouse move an mouse up events and to file an issue against Chromium showing how it works correctly in FF and in Edge, but not in Chromium.

I have found already a page online that logs the mouse events -- https://dvcs.w3.org/hg/d4e/raw-file/tip/mouse-event-test.html . Maybe you can try with your device and see the difference between FF/Edge and Chrome. Normally, it should look like "mousedown", N x "mousemove", "mouseup":

Once you observe a difference, please create an issue with complete steps at https://bugs.chromium.org/p/chromium/issues/list and link to it here.

Here is me doing it on my machine, there is some noise with the mouseout, but the pattern "mousedown", N x "mousemove", "mouseup" is visible:
![Kapture 2019-11-18 at 15 19 19](https://user-images.githubusercontent.com/5047891/69059972-d6f28e00-0a16-11ea-9017-35e451e6f446.gif)

**Comment by BCSharp** [comment]
Reported to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1026141
