### ISSUE TITLE
Extra characters appearing in integrated terminal with completion

### ISSUE THREAD

**Issue by aral** [microsoft/vscode#82751]
- VSCode Version: 1.39.2
- OS Version: Pop!_OS 19.04 (based on Ubuntu 19.04)
- zsh version: zsh 5.5.1 (x86_64-ubuntu-linux-gnu). Using oh-my-zsh with agnoster theme and powerline fonts.

Steps to Reproduce:

1. Open integrated terminal
2. `cd ~/directory/`
3. Press tab twice to bring up the visual completion

I see the `cd …` replaced with `ccd …`

![Screenshot from 2019-10-17 09-03-05](https://user-images.githubusercontent.com/41798/66990074-6e359000-f0bd-11e9-9fd5-668aaff688ec.png)

I’ve also had random characters added at other times in the integrated terminal but this is one I can always reproduce. This was not an issue until a couple of updates ago (quite possibly since the last one but I’m not sure.)

Note that the inserted character is purely cosmetic. It is not actually editable and does not form part of the command if you submit it. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It looks like the monkey emoji is making the width of the line off (due to https://github.com/xtermjs/xterm.js/issues/1709) and that's causing zsh when it reprints the line to start printing at the wrong spot.

/duplicate
