### ISSUE TITLE
Clear output doesn't clear output buffer, it just pretends by only clearing the output screen

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode#82750]
https://github.com/microsoft/vscode-go/issues/2835

vscode: 1.39.2
extension: 0.11.7

any go test code will do

```
func ExampleUnmarshal() {
	m := make(map[string]interface{})
	if err := json.Unmarshal([]byte(`{"test":1}`), &m); err != nil {
		fmt.Println(err)
	}
	fmt.Println(m["test"])
	// Output:
	// 2
}
```

Step 1) Click run test

![image](https://user-images.githubusercontent.com/863731/66951578-fc2c5f00-f05a-11e9-8172-cebe9a7559eb.png)

Step 2)

![image](https://user-images.githubusercontent.com/863731/66951337-6b558380-f05a-11e9-9b3a-79b7d3288731.png)

Step 3) Clear output 

![image](https://user-images.githubusercontent.com/863731/66951356-75778200-f05a-11e9-8451-0fcf4ba1a071.png)

Step 4) Repeat steps above until the output buffer gets so large it freezes vscode despite clearing it every time.

**Comment by sandy081** [comment]
Can you please create a sample extension to repro it and provide us. It will be easy for us to investigate.

**Comment by gertcuykens** [comment]
There are 4 easy steps to reproduce it with the vscode-go extension described above and you could also ask your colleague @ramya-rao-a for a bit of advice to point to the part that is responsible for the output buffer. I know this bug is difficult to fix but at least you could write a counter example to your colleague @ramya-rao-a indicating that it's not reproducible on the vscode side and it has to do with the plugin itself. I understand it's hard but the appropriate label would be `don't have time to fix this` instead :)

**Comment by ramya-rao-a** [comment]
@gertcuykens Do you recall the number of times you had to run the test, followed by clearing of the output before you saw it freezing vscode? I tried about 20 times and couldn't see any issues.

Do you also see the problem if you skip the step where you clear the output? The vscode-go extension clears the output for every test run.

**Comment by gertcuykens** [comment]
Tested it again with plugin version v0.11.9 this time and you are correct it does clear the output now instead of only the screen but internally appending to previous output. Thanks closing
