### ISSUE TITLE
Extension UI: don't apply themes to extension description  

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8275]
for https://github.com/Microsoft/vscode/issues/8215:

Since the Marketplace doesn't support themes, all extension descriptions where 'designed' with the default light theme in mind.

Applying other themes to an extension description make them look bad. 

We should consider whether we really want to apply themes here.

**Comment by isidorn** [comment]
Not cruical, assigning to Joao and July

**Comment by joaomoreno** [comment]
Very tricky as a white theme would look really out of place in a dark workbench...

Are there any really bad examples?
