### ISSUE TITLE
extensionHostProcess.js file is removed When running vscode

### ISSUE THREAD

**Issue by JinHyukParkk** [microsoft/vscode#82752]
- VSCode Version: 1.39.2
- OS Version: Window 10 pro

Steps to Reproduce:
1. Open vscode
2. Check file:///C:/Users/[UserId]/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js

![bug](https://user-images.githubusercontent.com/22048280/66991071-52081200-f102-11e9-9973-b26d3ef49109.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JuliusGoddard** [comment]
Same problem... need solution urgently.

**Comment by roblourens** [comment]
Is it possible that an antivirus is removing it?

Can you try reinstalling?
