### ISSUE TITLE
Code Helper has 100% CPU usage

### ISSUE THREAD

**Issue by vedmant** [microsoft/vscode#82755]
Issue Type: <b>Performance Issue</b>

My project has just two files, index.html and style.css, both are under 100 lines, however code Helper has 100% CPU usage and my laptop fans are on full speed.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    82	 48725	code main
    0	    33	 48726	   gpu-process
    0	   172	 48728	   window (index.html — landing-video)
  100	    33	 48782	     extensionHost
    0	    25	 48802	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=48782
    0	    25	 48805	       electron_node server.js 
    0	    25	 48996	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain --node-ipc --clientProcessId=48782
    0	    25	 48783	     watcherService
    0	    25	 48787	     searchService
    0	     0	 48806	     /bin/bash -l
    0	    66	 48786	   shared-process
    0	     0	 50092	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    74	 50088	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html — landing-video)
|    Folder (landing-video): 3 files
|      File types: html(1) png(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-routes|aki|0.3.1
laravel-extra-intellisense|ami|0.2.3
svelte-intellisense|ard|0.7.0
vscode-mjml|att|1.6.0
laravel-blade-spacer|aus|1.0.3
vscode-intelephense-client|bme|1.2.3
vscode-tailwindcss|bra|0.2.0
rails|bun|0.13.1
vscode-gemfile|bun|0.0.2
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
laravel-blade|cjh|1.1.2
vue-peek|dar|1.0.2
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
activitusbar|Gru|0.0.21
crane|Hvy|0.3.8
classic-asp|ili|0.0.4
svelte-vscode|Jam|0.9.3
auto-comment-blocks|kev|1.0.1
node-module-intellisense|lei|1.5.0
sftp|lix|1.12.9
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
python|ms-|2019.10.41019
php-docblocker|nei|2.0.1
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.22.4
laravel-blade|one|1.20.0
vscode-css-peek|pra|3.0.2
ruby|reb|0.25.3
slim|sia|0.1.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by octref** [comment]
Please read this page to figure out which extension was causing issues, and you can uninstall them: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions
