### ISSUE TITLE
In Split View Mode, Go-to-definition opens file in new tab rather than navigating already opened tab in other view pane

### ISSUE THREAD

**Issue by royki** [microsoft/vscode#82767]
1. Open Vscode, spilt it and open two different files in two split pane
![2019-10-17_14h25_30](https://user-images.githubusercontent.com/1545990/67008647-3f81de80-f0ea-11e9-8417-3418a279a2b7.jpg)

2. Pick for `Go-to-definition`, click `F12`
![2019-10-17_14h27_08](https://user-images.githubusercontent.com/1545990/67008657-44df2900-f0ea-11e9-8516-bae7f9ec3058.jpg)

It opened the file in new tab, in the same pane which is already opened in other pane view. It doesn't navigate to the file to other pane.

3. Opened same file in two different pane. 
![2019-10-17_14h27_08](https://user-images.githubusercontent.com/1545990/67008681-4f99be00-f0ea-11e9-8c12-d83aa51d7237.jpg)

**Comment by jrieken** [comment]
use the `workbench.editor.revealIfOpen` setting
