### ISSUE TITLE
a keyboard shortcut function about copy line down or upper

### ISSUE THREAD

**Issue by ZhaoQiang2015** [microsoft/vscode#82768]
Issue Type: <b>Bug</b>

when I use the keyboard shortcut ctrl+shift+alt+downarrow to copy line down.
I find if I only press once it will not copy line down. and when I keep it pressed in some seconds, it will copy line down for many lines. 
I don't know whether it is a Bug, but I think it should copy one line down when I press once, that's looks normals.
I very like vscode, thanks.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (2.82GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
Bookmarks|ale|10.5.0
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.31.0
gitlens|eam|10.1.1
matlab|Gim|1.4.0
gc-excelviewer|Gra|2.1.32
vscode-peacock|joh|3.1.5
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
material-icon-theme|PKi|3.9.1
markdown-preview-enhanced|shd|0.4.3
python|tht|0.2.3
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.4.0
markdown-pdf|yza|1.3.1
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by roblourens** [comment]
Is it possible that this is a problem with your OS? Does the down arrow work normally by itself (without ctrl+shift+alt)?

Also can you check whether any of the troubleshooting tips on this page help? https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by ZhaoQiang2015** [comment]
Thank you for you reply. My OS is ubuntu 16.04, and I used the default keymap of vscode. last night, I try the operation of copy line down in my Mac laptop. It's behavior is normal. may it only accurs in the Ubuntu's OS?,

**Comment by roblourens** [comment]
Does the down arrow work normally by itself (without ctrl+shift+alt)?

Also can you check whether any of the troubleshooting tips on this page help? https://github.com/microsoft/vscode/wiki/Keybinding-Issues
