### ISSUE TITLE
German translation: issue with git extension in notification

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82769]
Just noticed this issue in the german translation:

![image](https://user-images.githubusercontent.com/900690/67012527-d736fb00-f0f1-11e9-9c0d-3fd138118e05.png)

Looks like the markdown characters for rendering links are broken in this case.

**Comment by lukaschal** [comment]
@bpasero Is this repro on RUS as well ? DEU translation looks like a same like ENU. Maybe double quotes inside brackets could by an issue.

ENU: Would   you like Code to [periodically run 'git fetch']({0})?
DEU: Möchten Sie Code [regelmäßig "git fetch" ausführen lassen] ({0})?

**Comment by lukaschal** [comment]
ENU: Would you like Code to periodically run "git fetch"?

**Comment by lukaschal** [comment]
Would you like Code to [periodically run "git fetch"]({0})?

**Comment by lukaschal** [comment]
Code が   [定期的に 'git fetch']({0}) を実行してもよろしいですか?

**Comment by lukaschal** [comment]
Вы   хотите, чтобы среда Code [периодически выполняла команду "git   fetch"]({0})?

**Comment by lukaschal** [comment]
Fixed. 

TGT: Möchten Sie Code [regelmäßig "git fetch" ausführen lassen] ({0})?
NEW TGT: Möchten Sie Code [regelmäßig "git fetch" ausführen lassen]({0})?

**Comment by danyeh** [comment]
Close as fixed. FYI. @weeteckt
