### ISSUE TITLE
Ctrl + . (fixes shortcut) not working using Microsoft Pinyin (even in English mode)

### ISSUE THREAD

**Issue by vilic** [microsoft/vscode#82762]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18999

Steps to Reproduce:

1. Type some code that has fixes.
2. Switch input method to Microsoft Pinyin.
3. Press `Ctrl + .` and fixes are not showing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@vilic could you please go to Keybindings editor, turn on recording mode and type in `ctrl+.` to see what's the result from it?

**Comment by vilic** [comment]
@rebornix it gives `"ctrl+"` for both English/Chinese  mode under Pinyin keyboard.

**Comment by rebornix** [comment]
I see the problem now. Our keybinding doesn't work with Pinyin keyboard, no matter it's English or Chinese as the keyboard layout is the same. Switching to English IME should work.

**Comment by vilic** [comment]
This is really confusing though, in a really long time I thought it was the auto fixes stuff being unstable. If I remember it correctly, the English mode used work with the `Ctrl + .` keybinding, not sure whether this is a problem of newer Chinese Pinyin keyboard introduced in Windows Insider or a problem of VSCode changes.

**Comment by vilic** [comment]
@rebornix I see the problem now, the new Pinyin IME by defaults use `Ctrl + .` as the shortcut toggling Chinese/English punctuation. Turning off the shortcut solves this issue.
