### ISSUE TITLE
ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#82765]
It occurs in DEBUG CONSLOE: `On mac`
```
[foxundermoon.shell-format] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'editor.formatOnSave', provide the URI of a resource or 'null' for any resource.
extensionHostProcess.js:660
(node:32397) ExperimentalWarning: The fs.promises API is experimental
```
I'm trying to create a Extension . But when i debug it , the question occurs. It appears even when there is just a helloworld demo. Thanks for your help.

**Comment by roblourens** [comment]
What version of vscode?

**Comment by roblourens** [comment]
Actually it seems most likely this is triggered by another extension. You can try disabling extensions to figure out which one it is.
