### ISSUE TITLE
Help us improve our support for Javascript

### ISSUE THREAD

**Issue by murpg** [microsoft/vscode#82764]
Issue Type: <b>Bug</b>

The notification titled "Help us improve our support for Javascript" does not close  when I click the X. The buttons  "Take a short Survery", "Remind Me later" do nothing when I click this.

The steps to reproduce this is to just open VS Code and wait for that notification to appear and try and close it or click the above mentioned buttons.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (3.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
prettier-vscode|esb|2.3.0
auto-close-tag|for|0.5.6
beautify|Hoo|1.5.0
reg|ion|1.0.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-cfml|Kam|0.5.3
cf-filefinder|kev|0.0.2
terraform|mau|1.4.0
gitignore|mic|1.0.1
vscode-docker|ms-|0.8.1
mssql|ms-|1.6.0
powershell|ms-|2019.9.0
sublime-keybindings|ms-|4.0.3
vsliveshare|ms-|1.0.988
team|ms-|1.149.2
vetur|oct|0.22.4
vscode-coldbox|ort|0.1.0
vscode-testbox|ort|0.2.0
code-settings-sync|Sha|3.4.3
plsql-language|xyz|1.8.2
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
