### ISSUE TITLE
IPC library watcher spitting errors like crazy

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8276]
- VSCode Version: insider
- OS Version: linux

Steps to Reproduce:

1. Open vscode repo
2. Notice a bunch of exceptions in the  console
3. After some time vscode crashes
4. I guess there is something wrong with my configuration - we might have discussed this in the past

![screen shot 2016-06-28 at 11 32 51](https://cloud.githubusercontent.com/assets/1926584/16410737/36b5b308-3d24-11e6-995c-058094c44733.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7950
