### ISSUE TITLE
Parse temp file as certain file type

### ISSUE THREAD

**Issue by zxeoc** [microsoft/vscode#82761]
Sometimes I would write a "temp file" like a code snippet or a short markdown document but not really save it ( just paste it into other apps like email client or IM). It would be helpful if there's a function that I can tell vscode to parse the temp file as a certain type ( .md or .java, etc) and active highlight and plugins about the type ( markdown support, code completion, etc).

**Comment by roblourens** [comment]
You can! You can click the language mode in the status bar ("plain text" by default) to pick a language mode. Or run the command "Change Language Mode".

**Comment by zxeoc** [comment]
Thank you roblourens. It helps a lot. But I found it doesn't active all plugins related to the chosen type. For example, in a saved Java file:
![image](https://user-images.githubusercontent.com/4046320/67062157-25510a80-f195-11e9-9331-b216b526b1e9.png)
in the temp Java file:
![image](https://user-images.githubusercontent.com/4046320/67061792-f9815500-f193-11e9-9048-b79b7937abd6.png)

**Comment by roblourens** [comment]
That's up to the language extension, you can file an issue on them.

**Comment by zxeoc** [comment]
OK, thank you.
