### ISSUE TITLE
Hope `command+click` can jump to module(less/json/txt,...)

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [microsoft/vscode#82771]
```js
import LangJson from '../../../data/lang.json';
```

I hope while `command`+`click` the module `LangJson`, it can jump to the file of `lang.json`

**Comment by mjbvz** [comment]
Try creating a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) and setting [`"resolveJsonModule": true`](https://mariusschulz.com/blog/importing-json-modules-in-typescript)

**Comment by Mr-jiangzhiguo** [comment]
> Try creating a [`jsconfig.json`](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) and setting [`"resolveJsonModule": true`](https://mariusschulz.com/blog/importing-json-modules-in-typescript)

thx, it worked for `*.json`, 

but `*.less` or other ext file how to do
