### ISSUE TITLE
Focus Window On Break setting not working

### ISSUE THREAD

**Issue by jordanyoungs** [microsoft/vscode#82770]
Issue Type: <b>Bug</b>

I am using VSCode Remote SSH for debugging a php app using xdebug and the xdebug chrome extension. I have turned off the Focus Window On Break setting for User, Remote, and Workspace. When I start the debugger, it correctly stops at the first breakpoint. However, the app sends additional requests and when any of these newer requests hits a breakpoint/error, focus is taken away from whatever I am doing and goes to that breakpoint/error. I just want to inspect the first request without being interrupted constantly.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-161-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2691)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: suitecrm|
|OS|Linux x64 4.4.0-161-generic|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (1 x 2691)|
|Memory (System)|0.97GB (0.06GB free)|
|VM|100%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
smarty|imp|0.3.0
remote-containers|ms-|0.81.0
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
sublime-keybindings|ms-|4.0.3
php-debug|fel|1.13.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This works fine for me.
Please try with a very simple javascript sample. And try using vscode insdiers https://code.visualstudio.com/insiders/

If you can repro with a simle javacscript sample please share it so I can investigate
Thanks
