### ISSUE TITLE
Allow Line Height to be Any number

### ISSUE THREAD

**Issue by ahmadawais** [microsoft/vscode#82778]
I like to follow the golden ratio rule of design and calculate the exact line height required by a font face for it to look good. For that, `1.2 to 1.45` times the font size is the best size bracket.

I currently use:

```json
"editor.lineHeight": 24.65,
```

My claim is backed by some of the industry-leading typographers like Matthew Butterick [recommends line-height to be 120–145% of the font size](https://practicaltypography.com/line-spacing.html).

---

But I am currently having issues with it.

![img](https://on.ahmda.ws/bd4c53/c)

Whereas the debug console line-height still works as a non-integer.

```json
"debug.console.lineHeight": 24.65,
```

Can you folks allow any number value to be used for `"editor.lineHeight"` property as well?

Peace! ✌️

**Comment by usernamehw** [comment]
I don't understand the obsession with absolute `line-height`. Wouldn't it make sense to request relative `line-height` support (That would actually scale depending on `font-size`).

**Comment by cpsauer** [comment]
@ahmadawais, @usernamehw and anyone else following this issue that would like the option to specify proportional line heights: Any chance we could get your upvote on #115960? We're aligned on goals and have few more days to get those last few votes.

**Comment by usernamehw** [comment]
I've already upvoted it and even made an extension:

https://marketplace.visualstudio.com/items?itemName=usernamehw.relative-line-height

**Comment by cpsauer** [comment]
Doesn't get any better than that. Thank you (and sorry)!
