### ISSUE TITLE
Specify document type without needing to save it

### ISSUE THREAD

**Issue by heriberto-delgado** [microsoft/vscode#82777]
Lately, as a software developer, I've been working with multiple, interconnected (yet unrelated) systems to provide additional functionalities for each one.

As a result, during my tests, I need to parse and understand outputs with wildly varied formats.

VSCode has been of great help to understand these outputs - colored syntax and the ability to format text in a file is a big time saver when doing this.

Thing is, sometimes the output I get does not always come as a file, per se. Sometimes I need to deal with data copied & pasted from other tools (such as Visual Studio, when debugging). So, for example, when I need to quickly look at an XML output of a process, most of the time I need to copy the output into VSCode, *save it* to a new file with the correct extension (usually at the Desktop folder), and *only then* VSCode recognizes it as an XML file that I can format and visualize correctly.

It would be of great help if I had a way to quickly specify the type / format of the text I'm currently pasting into VSCode without resorting to save a blob of text that I won't need to see again after 5 minutes, as a file with a specific extension, taking unnecessary space into my hard drive.

For example, being able to rename (and specify an extension to) a newly opened (but not yet saved) document, by clicking on its name in the upper tab bar, does the trick for me.

**Comment by roblourens** [comment]
You can change the language mode by clicking "Plain text" in the status bar or running the "Change Language Mode" command. Does that help?

**Comment by heriberto-delgado** [comment]
Oh. Yes, that actually helped. 
My apologies. Wasn't aware of that feature.
Thanks!
