### ISSUE TITLE
Debugger scrolling on new input doesn't take size of expanded objects into account

### ISSUE THREAD

**Issue by orta** [microsoft/vscode#82782]
:wave:
- VSCode Version: Insiders at c8252b63f547674d2faf361d4181bb76b0b5f81a
- OS Version: Mac

Steps to Reproduce:

1. Expand an object longer than the debugger size
2. Run a new expression
3. Don't see the new expression result

1:
![Screen Shot 2019-10-17 at 11 41 11 AM](https://user-images.githubusercontent.com/49038/67024900-27eb2b80-f0d3-11e9-9b6b-11226577fb86.png)

2:
![Screen Shot 2019-10-17 at 11 41 33 AM](https://user-images.githubusercontent.com/49038/67024844-1570f200-f0d3-11e9-9bf7-4f0c60c0d436.png)

3:
![Screen Shot 2019-10-17 at 11 41 45 AM](https://user-images.githubusercontent.com/49038/67024871-1d309680-f0d3-11e9-9181-d1096d883651.png)

Does this issue occur when all extensions are disabled?: Shouldn't be relevant I think

**Comment by isidorn** [comment]
Thanks for the issue.
However we do have some issues already with auto scroll and reval in the debug console. ONce we fix those we might look into this one.
