### ISSUE TITLE
The terminal is no longer integrated

### ISSUE THREAD

**Issue by Sukaato** [microsoft/vscode#82786]
- VSCode Version: 1.39.2
- OS Version: Windows 1903

Steps to Reproduce:

1. Start Vs code
2. Open the integrated terminal with `CTRL + SHIFT + %` or other macro

Does this issue occur when all extensions are disabled?: Yes

**Comment by Sukaato** [comment]
Error message when closing my open terminal: The terminal process terminated with exit code: 3221225786

**Comment by Sukaato** [comment]
And on VS Code insiders the bug is not fixed

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.

**Comment by Tyriar** [comment]
I'll add a specific error for this, I also added it to the docs https://github.com/microsoft/vscode-docs/commit/bdfca92dfccc4f660ae341632ad7c8e1a87f2c99

**Comment by Tyriar** [comment]
To verify:

- Enable "Use legacy console" in Windows 10 1903+ conhost settings
- Try launch terminal, you should get a tailored error message
