### ISSUE TITLE
Processor Architecture for AnyCPU Projects x86 not working for MS tests

### ISSUE THREAD

**Issue by JDFocus** [microsoft/vscode#82780]
- VSCode Version: 16.4.0 Preview 2.0
- OS Version: Windows 10(64-bit)

### Steps to Reproduce:

1.Download the sample unit-testing-using-mstest from
https://github.com/dotnet/samples/tree/master/core/getting-started/unit-testing-using-mstest
2.Append a new [TestMethod] Is32Bit() in the PrimeService_IsPrimeShould.cs
````
namespace PrimeServicesTests
{
    [TestClass]
    public class PrimeService_IsPrimeShould
    {
        private readonly PrimeService _primeService;

        public PrimeService_IsPrimeShould()
        {
            _primeService = new PrimeService();
        }

        [TestMethod]
        public void IsPrime_InputIs1_ReturnFalse()
        {
            var result = _primeService.IsPrime(1);

            Assert.IsFalse(result, "1 should not be prime");
        }

        [TestMethod]
        public void Is32bit()
        {
            Assert.IsFalse(Environment.Is64BitProcess);
        }
    }
}
````
3. The BuildConfiguration of both the projects(class library and test) in the test solution is AnyCPU platform
4. Select Test->Processor Architecture for AnyCPU Projects->x86
5. Run All Tests in the Test Explorer window

### Expected behavior
Test Explorer -> Run All Tests should pass  the test Is32bit() despite
    1. AnyCPU/x86 BuildConfiguration for the test project when the DefaultArchitecture is selected as 
        Test->Processor Architecture for AnyCPU Projects->x86

### Current behavior
MSTest : GUI
````
Group Name: PrimeServicesTests
Duration: 0:00:00.055
1 test(s) failed
0 test(s) skipped
1 test(s) passed
````
Command line 
````
PM> dotnet test PrimeServicesTests.dll --platform:x86
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 2
     Passed: 2
 Total time: 1.9630 Seconds
````

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
I assume this test UI comes from the C# extension, please file this on their repo: https://github.com/OmniSharp/omnisharp-vscode
