### ISSUE TITLE
Max line length and autopep8 are not working

### ISSUE THREAD

**Issue by Buuntu** [microsoft/vscode#82792]
- VSCode Version: 1.39.1
- OS Version: OS X (10.14.6) Mojave

Steps to Reproduce:

1. Install autopep8 and pylint in environment
2. While some lines are reformatted on save, most are not even with a max-line length set to 80.  This means that I have to go individually and change all of these lines to be under 80 lines and re-run `pycodestyle` separately.
My settings.json file looks like this:
```
// Place your settings in this file to overwrite default and user settings.
{
    "python.formatting.autopep8Args": [
        "--max-line-length=80"
    ],
    "editor.fontSize": 15,
    "terminal.integrated.fontSize": 14,
    "python.formatting.provider": "autopep8",
    "editor.formatOnSave": true,
    "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false
}
```
I am running inside of a conda environment with all of the necessary packages installed, and set the python interpreter inside VSCode appropriately.  If the issue is that autopep8 cannot resolve these, is there a line marker that can be displayed or can I have `pycodestyle` warnings displayed on save?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Sukaato** [comment]
VSCode is now in 1.39.2, try to update you and then update your issue

**Comment by Buuntu** [comment]
@Sukaato still the same issue

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
