### ISSUE TITLE
Memory Use

### ISSUE THREAD

**Issue by cawell** [microsoft/vscode#82798]
Issue Type: <b>Bug</b>

Too much memory usage just when opening VSCODE.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1778)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|11.63GB (1.00GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.1.1
vscode-scss|mrm|0.6.2
sublime-keybindings|ms-|4.0.3
indent-rainbow|ode|7.4.0
ruby|reb|0.25.3
highlight-matching-tag|vin|0.9.5
simple-ruby-erb|vor|0.2.1
vscode-nginx|wil|0.7.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information

/needsMoreInfo

**Comment by SupinePandora43** [comment]
gitlens and bracket colorizer are half of problem, other half is chromium
