### ISSUE TITLE
Search results message is selectable ("x results in y files")

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82795]
When performing a search using the search panel, the result count message can be selected with the mouse.

This breaks consistency of the UI as normally nothing is selectable. It also looks like a mistake.

This also causes the search string to be selectable from outside of the textbox by pressing <kbd>Ctrl</kbd>+<kbd>A</kbd> when focused on the search results message:
![image](https://user-images.githubusercontent.com/26556598/67038578-5cd59d80-f128-11e9-84a9-13e41b786f6b.png)
which is even more weird.

This exists as a weird "feature" requested in #18568
I believe it should be removed.
As you can see in #20617, even when it *is* selectable, the cursor being a caret is weird to users.

The fix would be to delete [this line](https://github.com/microsoft/vscode/blob/ede82b16387ecbebadadcc3a72f511be13434e20/src/vs/workbench/contrib/search/browser/media/searchview.css#L159).

If the esoteric use-case the user in #18568 should still be supported, then it is better to add a button next to the message (with a descriptive tooltip) that copies the message, because currently it just looks and feels weird that it is selectable.

**Comment by NotWearingPants** [comment]
This problem also causes this message to be selectable, which is more weird since it has a link in it:
![image](https://user-images.githubusercontent.com/26556598/67038821-d9687c00-f128-11e9-95dd-622177781bb5.png)

**Comment by roblourens** [comment]
Huh, I've never noticed that in 2.5 years. I don't think it's a big deal. Other messages like on dialogs and notifications are selectable. I think we should leave it.

**Comment by NotWearingPants** [comment]
If I submit a PR removing this would you consider accepting it?

**Comment by roblourens** [comment]
No, sorry
