### ISSUE TITLE
Open editors list jumps after selecting an editor in the list

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#8279]
- VSCode Version:1.3.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Turn tabs on
2. Open multiple editors in three editor groups
3. Select an editor in the left or the right group
4. Click on one of the editors in the centre group
Expected: the editor to be selected and the list to remain static
Actual: the editor is selected but the list moves so that the selected item is no longer under the mouse

I found this quite hard to repro. I noticed it happen occasionally but each time it happened I couldn't easily make it happen again. The above steps are the best repro steps I could find. 

If you have to scroll the list of open editors so that the centre group becomes visible, it doesn't repro so easily.

This was found while testing Drag and Drop editors and tabs #7852 but is not about drag and drop.

**Comment by bpasero** [comment]
@stevencl is this using the "opened editors" view or the tabs in the editor pane?

**Comment by stevencl** [comment]
Sorry, this is using the opened editors view.

**Comment by isidorn** [comment]
I can reproduce this seldomly, not cruical -> july.
This is how the tree.reveal behaves for me, currently the tree API can take a number with the reveal to know how much to scroll to the top when revealing this element. However there is api missing to never scroll if the element is already revealed. I would need some better tree api or advice from joao thus also assigning him

**Comment by joaomoreno** [comment]
Lies. There is [getRelativeTop](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/tree.ts#L132).
