### ISSUE TITLE
Flickering in full screen or zen mode

### ISSUE THREAD

**Issue by pdxDev** [microsoft/vscode#82790]
Issue Type: <b>Bug</b>

With the latest update, I can no longer go into full screen or zen mode without the screen constantly flickering.   Can reproduce every time.  Have restarted computer with same issue coming back.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
Can you reproduce with VSCode insiders (that uses the new electron)
https://code.visualstudio.com/insiders/

**Comment by pdxDev** [comment]
I tried with VSCode insiders and I do not experience the same issue.

**Comment by isidorn** [comment]
Then please use vscode insiders. 
It seems to be fixed with latest electron which we will ship soon in stable.
Thanks
