### ISSUE TITLE
Source Control checkout Menu does not close, even after Close Repository

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#82797]
- VSCode Version: 1.39.2
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. git project open
2. Source Control Providers, click on the branch
3. checkout menu opens 
![image](https://user-images.githubusercontent.com/5124946/67040598-cf775680-f0f1-11e9-8c1e-aa5d8d4efb01.png)
4. click Close Repository on the repo
try to close the menu - doesn't close

Hide and close repository on the pane does not close the menu

How does one close this menu ?

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does the Escape key do the job?

**Comment by misolori** [comment]
@bpasero @joaomoreno we're seeing a growing number of issues related to this changed behavior in the quick pick (came from https://github.com/microsoft/vscode/issues/71355). None of our other quick picks behave this way and this creates an inconsistency, which then leads to confusion like the issue above. Can we revisit this change?

**Comment by wesinator** [comment]
> Does the Escape key do the job?

no, it did not 
(touch bar escape key)

**Comment by bpasero** [comment]
I do not have a strong opinion and we can revert that change. You would need to talk to @chrmarti for showing a close button in quick input.

**Comment by joaomoreno** [comment]
Reverted. 👍
