### ISSUE TITLE
Terminal Log displaying not right with emoji

### ISSUE THREAD

**Issue by hcsgzh** [microsoft/vscode#82801]
- VSCode Version:
1.39.2
- OS Version:
Windows_NT x64 10.0.17763

```
console.log('Log Level: %c ⚠️🐞OK', 'color: skyblue');
```

### In terminal, it looks bellow.
![vs_log_01](https://user-images.githubusercontent.com/6902389/67043172-fc754900-f185-11e9-99aa-cd4098e87c45.PNG)

### In DevTools, Chrome. It looks like this.
![vs_log_02](https://user-images.githubusercontent.com/6902389/67043232-262e7000-f186-11e9-85ec-07ea58c5f7ee.PNG)

I really enjoy the VS Code. Hope it will become better!
Cheers!

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

---

For conpty (Windows 1903+) this is tracked in https://github.com/microsoft/vscode/issues/76842
