### ISSUE TITLE
Overl agressive file save prevention

### ISSUE THREAD

**Issue by aplatypus** [microsoft/vscode#82807]
Issue Type: <b>Bug</b>

 1. Open file: junk.txt
 2. Make some changes to the file.
 3. Use touch or another program to  change timestamp on junk.txt
 4. Use [save as] for junk.txt
 5. Press [SAVE]
 6. Pop-up shows to tell me the file already exists
 7. click [replace]
 8. file save fails --> error panel (shown in screenshot)
 9. This panel says refused to save because files are different or the version on-disk is newer.
10. I haver run all the possible variations on to just save and overwrite the junk.txt file.

<b>Expected / prefered  behaviour</b> 

 * The check on the difference or newer timestamp can be part of the first pop-up
       x that way i can still clikc [replace] full knowing the file I'm saving is 'older'

 * they way things work now I can never resave junk.txt no matter what I do
    and I would need to save junk as "junk 2" and remove the junk on disk.

This kind of well meaning not completely though out hand-holding puts a block in my workflow.  I can easily work around it -- the role of an editor however is to facilitate productivity not reduce it!

----

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.7-050007-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3864)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.5.0
vscode-groovy|Arg|0.0.1
vscode-markdownlint|Dav|0.31.0
xml|Dot|2.5.0
LogFileHighlighter|emi|2.6.0
ada|Ent|0.88.0
vscode-diff|fab|1.4.0
javac-linter|fau|1.3.1
seito-openfile|Fr4|1.8.5
vscode-awk-hint|han|0.0.2
java-properties|ith|0.0.2
vscode-edit-csv|jan|0.1.4
diff-tool|jin|0.0.1
git-tree-compare|let|1.7.0
AWK|lug|0.0.2
bash-ide-vscode|mad|1.3.3
gradle-language|nac|0.2.3
printcode|nob|3.0.0
java|red|0.51.0
markdown-preview-enhanced|shd|0.4.3
vscode-taskexplorer|spm|1.20.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
markdown-pdf|yza|1.3.1

</details>

**Comment by bpasero** [comment]
@aplatypus there is a duplicate issue that asks for disabling this check or allowing to save from the notification.

You can save, but you need to review your changes compared to the ones on disk first. The flow is explained from the notification.

**Comment by aplatypus** [comment]
That's the bug -- I do NOT wish to compare the file versions.  Ergo, I just want to press "No thank you", or something, and press "Save".

That is not possible currently.

I am Happy to see the check, and get the warning.  I am even happy with an _option_ to use diff to compare files. 

The error as I perceive it here, is that there's no override or (as I mentioned) "No thank you, save the file." step.
