### ISSUE TITLE
TypeError: vscode.CustomExecution is not a constructor

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode#82806]
When renaming `CustomExecution2` to `CustomeExecution` in my extension, in response to dc4b1c2, I get the following error at run time:

`TypeError: vscode.CustomExecution is not a constructor`

Any ideas?

**Comment by alexr00** [comment]
@sherryyshi thanks for trying out the proposed API! 

I update the task provider extension sample to see if I could get the same error: https://github.com/microsoft/vscode-extension-samples/commit/0d75c547555a098f8438007c39ca432f819c5354

I didn't see any errors though. A few ideas:
Did you update your package.json?
Maybe try a `git clean -xfd` then `npm install` again.
Not sure how this could result in an that error, but are you on the latest insiders build?

**Comment by sherryyshi** [comment]
@alexr00 Thanks for taking a look.

My package.json situation is a bit weird - I didn't have `@types/vscode`, but instead had `npx vscode-dts master` to work around  #80498. However I also tried upgrading to `"@types/vscode": "^1.39.0"`, and the issue still repro'ed. This is on the latest released build 1.39.2.

Interestingly though, I tried it on the latest insider (1.40) and did not repro the issue...

**Comment by sherryyshi** [comment]
So this is what I'm seeing:
`CustomExecution2` works on 1.39.2, but NOT on 1.40, and `CustomExecution` does NOT work on 1.39.2 but works for 1.40.

Since our build definition always installs the latest proposed API, our builds will be broken for 1.39. Any suggestions?

**Comment by alexr00** [comment]
In preparation for stabilizing the CustomExecution API I renamed it to remove the 2. Looks like that's what you're seeing.
Can you do a VS Code version check and then use the appropriate name depending on the version?

**Comment by sherryyshi** [comment]
I don't think I can do that because the Typescript won't be able to compile the version that is not in the `vscode.proposed.ts` that I have.

I ended up taking a dependency on the version of `vscode.proposed.ts` prior to the rename (`npx vscode-dts dev afa911d942f60aff56a65be989eb8c74d9cc56a5`) :) I'll have to change it back once 1.40 is released.

Thanks for your help!

**Comment by alexr00** [comment]
I've seen some cases where the object in question is cast to `any`, of course this isn't ideal either and would also result in something you want to change later.

Glad you found a work around!
