### ISSUE TITLE
Can't click-to-open absolute path in `require()` in `.ts` file

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#82803]
Issue Type: <b>Bug</b>

In a `.ts` file, I've got `import config from '/Users/gary/config.js'`. On my Mac, I can cmd-click on the path, to open the file in VSC. 

But if I change it to `const config = require('/Users/gary/config.js')`, then I can't click on it to open the file.

In a .js file, I can click on both styles, to open the files.

Why is it not possible to click on an absolute path, in .ts files, only for `require`?

My tsconfig.json contents (would be preferable if I don't need to update `rootDir` or `rootDirs` to fix this issue, although I don't even know if using those would fix this?):

```json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "module": "CommonJS",
    "outDir": "./dist/",
    "rootDir": "./src/",
    "target": "ES2020"
  },
  "include": ["./src/"],
  "exclude": ["**/dist/**", "**/node_modules/**"]
}
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose) for this
