### ISSUE TITLE
when i input {} in the editer,the windows is freeze

### ISSUE THREAD

**Issue by 1XiaSheng** [microsoft/vscode#82810]
- VSCode Version: 1.39.2
- OS Version:Windows_NT x64 10.0.18362

Steps to Reproduce:

1. open editer, input {} use shift + {;
2. then the window is feezing

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Does this happen if you start with `--disable-extensions`?
