### ISSUE TITLE
autoClosingBrackets setting prevents jsdoc auto completion

### ISSUE THREAD

**Issue by CreativeTechGuy** [microsoft/vscode#82814]
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Type `/**` above a JavaScript function.
2. Autocomplete will suggest an auto-generated jsdoc comment.
3. Change `editor.autoClosingBrackets` setting to `"never"`
4. Type `/**` above a JavaScript function.
5. Autocomplete will no longer suggest a jsdoc.

Does this issue occur when all extensions are disabled?: Yes

I was able to narrow this issue down to this specific setting. JSDocs shouldn't be included in this setting.

**Comment by mjbvz** [comment]
Discussed before with https://github.com/microsoft/TypeScript/issues/24468

Thee TS team was previously reluctant to support this case it would add a lot of complexity. From their point of view, when you are in this state, the entire rest of the document is a commen. Feel free to raise this again upstream if you are passionate about it

**Comment by mjbvz** [comment]
Also note that we removed the workaround mentioned as it did not perform well and potentially caused a flash of code while requesting completions

**Comment by CreativeTechGuy** [comment]
@mjbvz Just to be clear then, if you want JSDoc auto completion, you must have the `autoClosingBrackets` setting enabled? Is there no other way to manually trigger this auto create feature for JSDocs?

**Comment by jbracer19** [comment]
i feel like i could be more help but unfortunately still lack clarity on exact folder paths. i’ll keep working on it though

**Comment by jbracer19** [comment]
All i can say is i promise even though i’m coming in late, a bit in the dark and challenged to say the least , to all those working with me that i won’t let you down or put you in a compromising position, well at least not intentionally. Yes discouraged with my comprehension in coding issues yet i still feel like this is exactly what i needed. passionate yes, but i’ll keep it clean.  Happy coding!

**Comment by mjbvz** [comment]
@CreativeTechGuy No it does not depend on that setting but it requires that you have a complete comment, i.e. not just the opening `/**`
