### ISSUE TITLE
Wrong animation when inline breakpoint decorations show up

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82812]
![Oct-17-2019 20-40-19](https://user-images.githubusercontent.com/323878/67064191-6b1ebc00-f11e-11e9-8b11-edc3f4b9e427.gif)

Pressing F9 on that line. I see this sometimes - the text behind the breakpoint decoration jumps too far to the right, then jumps back to the left.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/81716
Also doing this with a timeout might help
