### ISSUE TITLE
Unable to debug the Coroutine

### ISSUE THREAD

**Issue by ycxalyn** [microsoft/vscode#82817]
Unable to debug the Coroutine，When i debug the Coroutline， it jump out of the Coroutline

**Comment by ycxalyn** [comment]
it is a new issue，please help me look what is wrong， when i debug the Coroutline(c#), it jump out the 
Cououtline, so I cannot debug it step by setp

**Comment by roblourens** [comment]
Please file this issue on the C# extension repo
