### ISSUE TITLE
C++ debugger looks for main.cpp file in the wrong location

### ISSUE THREAD

**Issue by micobanovic** [microsoft/vscode#82824]
**You'll need access to Microsoft OS repo and tools to repro this.**
1. Install Microsoft internal "WAVE for VS Code" extension from here: https://aka.ms/joinTheWave. 
2. It will show no issues installing the extension. It's listed as "vscode-nmake-tools" in the extensions info attached.
3. Start debugging (F5). 

### The issue
VSCode will issue an error like:
"Unable to open 'main.cpp': Unable to read file (Error: File not found (d:\Program Files\Microsoft VS Code\analog\...\main.cpp))."
It seems it's looking for the main.cpp in the VSCode.exe folder, rather than the source root folder. The source root folder should be set by the WAVE extension.

### Tried to
- Reinstall WAVE extension.
- Reinstall VSCode.
- Contact the WAVE team. They found no issues with the extension itself and directed me to the VSCode team.

**Comment by roblourens** [comment]
Sorry but we need more details than this. What workspace did you open, what is your launch config, where does the extension team think the problem is?
