### ISSUE TITLE
autoReveal highlight filename where it is without always moving it to the middle in explorer

### ISSUE THREAD

**Issue by linuxjh** [microsoft/vscode#82828]
![Screen Shot 2019-10-18 at 5 03 38 PM](https://user-images.githubusercontent.com/9011764/67082869-995ad500-f1cc-11e9-962e-41a465027498.png)
![Screen Shot 2019-10-18 at 5 03 49 PM](https://user-images.githubusercontent.com/9011764/67082881-a081e300-f1cc-11e9-8276-25d5b4252a75.png)

Version: 1.39.2

autoReveal always moves the filename entry to the middle in file explorer window when we select a file on tab. if the filename is not visible in the explorer, this is ok.

if the filename is visible in explorer, it should not move the filename to the middle in explorer, just highlight the filename where it is, right there in explorer.

thanks!

**Comment by callummr** [comment]
I've taken a stab at this in #89818 89818 as it's something that annoys me, hope that's alright 👌
