### ISSUE TITLE
Errors in the console are not displayed

### ISSUE THREAD

**Issue by wengshenggui** [microsoft/vscode#82820]
Issue Type: <b>Bug</b>

Errors in the console are not displayed

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel Core Processor (Haswell, no TSX) (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.07GB free)|
|Process Argv|D:\Deploy\client\iCenterBrowser|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
auto-close-tag|for|0.5.6
search-node-modules|jas|1.3.0
vetur|oct|0.22.4
indent-rainbow|ode|7.4.0
code-spell-checker|str|1.7.18
highlight-matching-tag|vin|0.9.5
vscode-icons|vsc|9.4.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please give more details.

**Comment by wengshenggui** [comment]
![2019-10-18_152139](https://user-images.githubusercontent.com/28017224/67195797-35364c00-f42c-11e9-94a3-b1c816896a01.png)
