### ISSUE TITLE
"Loaded scripts" pane doesn't handle file:/// URIs properly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#82826]
From chrome-debug:

![image](https://user-images.githubusercontent.com/323878/29989400-8262b674-8f27-11e7-947d-0163f41a6507.png)

**Comment by connor4312** [comment]
I'm not sure there's an expectation for the loaded scripts pane to handle URIs. Generally elsewhere we'll always have file paths, and js-debug will always send some kind of file path rather than URI, so closing this for grooming.
