### ISSUE TITLE
Extension Not working

### ISSUE THREAD

**Issue by abrahamwilliam** [microsoft/vscode#82822]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.https://marketplace.visualstudio.com/items?itemName=abrahamwilliam007.es7-javascript-class-snippets ,working in Host development Environment
2.Not working as extension

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please file a more specific bug or report it to the extension author.
