### ISSUE TITLE
Highlight question popups

### ISSUE THREAD

**Issue by pid73** [microsoft/vscode#82823]
Question popups (such as username/password on git's push command) are visually not highlighted and may not be noticed at first. A 1px red border would suffice to attract user attention so that it's evident that a user interaction/input is required to proceed. This highlight would probably be helpful in all popup cases. This may be put into the theme configuration, but what I'm talking about is setting it in the default theme, if not having this theme option at all.

**Comment by roblourens** [comment]
Thanks for the suggestion, but I disagree. Like you say, they are customizable. I think an extra highlight would be overkill.
