### ISSUE TITLE
How to set "auto scrolling" for the output panel on by default?

### ISSUE THREAD

**Issue by jaques-sam** [microsoft/vscode#82835]
There should be a setting that auto scrolling for the output panel is enabled by default so that a user doesn't need to click on the ![image](https://user-images.githubusercontent.com/42445148/67091725-b92ed080-f1ad-11e9-95c2-69d98e976ff9.png) every time.

**Comment by sandy081** [comment]
Auto scrolling is enabled by default. 
Not sure how a setting is helpful given that UI toggles it.

**Comment by jaques-sam** [comment]
Then there is an issue, because it's not the case for me.
Like any other terminal or output window, it should work like this:
- Enable auto scrolling by default -> expect an open lock symbol
- When scrolling while new output is printed, the scroll bar should not automatically go to the end -> expect no auto scrolling
- When the user hits the end of the scroll bar again, the auto scroll should be enabled again -> expect auto scrolling

**Comment by sandy081** [comment]
> When scrolling while new output is printed, the scroll bar should not automatically go to the end -> expect no auto scrolling

Scrolling does not prevent auto scroll but clicking inside will prevent and again placing the cursor at the end will enable it again.

**Comment by jaques-sam** [comment]
Okay, this was new for me. Thanks!
