### ISSUE TITLE
emmet tab completion is slow on linux ubuntu

### ISSUE THREAD

**Issue by akshat-mewada** [microsoft/vscode#82843]
Hi,

I have gone through "emmet tab completion is slow in large files #70371" which fixed in July and then it works fine on Windows (don't know about Mac), but I am Ubuntu user and I often use VSCode for Angular development on my Linux system. But it's performance is still the same as it was on Windows previously before solving the issue.

So can you please solve the issue for the Linux system, or maybe you can guide how to solve issue.

I am using a Laptop with 8GB RAM, 1TB HDD and 1.9 GHz Intel i3 processor.

**Comment by octref** [comment]
Are you hitting https://github.com/microsoft/vscode/issues/71996 with `triggerExpansionOnTab`? Or is this specific to angular files but not HTML files?

**Comment by akshat-mewada** [comment]
Majority time i use emmet for CSS, and for that i use triggerExpansionOnTab .

**Comment by octref** [comment]
So this is happening to you on large HTML and CSS files, correct? Please follow #71996 then.

**Comment by akshat-mewada** [comment]
Yes, it is happening on large CSS files, not sure about large HTML file.

But I am unable to find solution at #71996

I think in #71996, there is just instructions to upgrade to latest insiders, and I am already using latest version of VSCode available for Ubuntu.

**Comment by octref** [comment]
@akshat-mewada #71996 is not fixed yet.

Are you using the auto-completion like this:
![image](https://user-images.githubusercontent.com/4033249/67584894-70be6800-f703-11e9-9700-0388940cf605.png)

Or do you use tab to expand them?
