### ISSUE TITLE
Can not use any comand hot key on extensions install search area

### ISSUE THREAD

**Issue by CHN-STUDENT** [microsoft/vscode#82841]
- VSCode Version: 1.39.1
- OS Version: Win10 V1809

Steps to Reproduce:

1. Open the extension menu
2. Try to use any comand Hot key on  extensions install search area,It can not be used on it.
![image](https://user-images.githubusercontent.com/21209416/67096065-eac58d00-f1e9-11e9-8305-806f8ec5c54b.png)
3. also the settings search area can not use hot key too
![image](https://user-images.githubusercontent.com/21209416/67096709-45abb400-f1eb-11e9-9162-91a4d02e9a52.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please give some more details, what command do you mean?

**Comment by CHN-STUDENT** [comment]
@roblourens hey thanks for your reply. I mean those area can not use any hot key command like `Ctrl+A` `Ctrl+V` `Ctrl+C` , I think it is not convenient for inputing something, So could you improve it? Thanks. If you need more info, i am glad to send to you.

**Comment by roblourens** [comment]
Hm, do they work in the normal editor?

**Comment by CHN-STUDENT** [comment]
@roblourens hello roblourens, the textbox seems work normorlly on normal editor but can not in extenstion search or setting search (can not use the command hot key)  
![image](https://user-images.githubusercontent.com/21209416/67170209-e2847200-f3e2-11e9-973c-5b02e74965ee.png)

**Comment by alexandrudima** [comment]
@CHN-STUDENT Can you try disabling all extensions and removing all your keybindings from `keybindings.json` ?

**Comment by CHN-STUDENT** [comment]
@alexandrudima hi,alexandru when i disabled all extensions and all my keybings, it works normolly, also i try to enable all extensions and all my keybings, it can works normolly. I do not know why,

thanks for your help.

![image](https://user-images.githubusercontent.com/21209416/67542068-d7e91600-f71d-11e9-9c9c-18987e5b47b6.png)

![image](https://user-images.githubusercontent.com/21209416/67542076-dd466080-f71d-11e9-865a-6bcf3862eda0.png)
