### ISSUE TITLE
Global replace all not very accessible

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8284]
#8184

1. Currently using the keyboard you can do the global find replace by pressing shit + tab
2. I have concerns that this is not very discoverable for people that use accessibility
3. I propose we introduce a global workbench command which would just open the search viewlet and toggle the replace box.

**Comment by sandy081** [comment]
- Added an entry under Edit -> Replace in Files with keyboard shortcut Cmd / Ctrl + Shift + H
- From the editor above command takes to search view with replace open
- Whenever a user opens search for the first time, I show replace so that user will be aware of it

**Comment by bpasero** [comment]
@sandy081 looks good, maybe for the global command in F1 do not use "Edit" as prefix, I think we are not using this prefix in other places either.

**Comment by sandy081** [comment]
Done. Also added a keyboard shortcut Alt + Cmd  + Enter to replace all just like in Find widget

**Comment by isidorn** [comment]
Looks good, created #8626 as a related but not important bug
