### ISSUE TITLE
Collapse takes a while to appear when editing HTML files

### ISSUE THREAD

**Issue by thiagosantoscunha** [microsoft/vscode#82847]
- VSCode Version: 1.39.2
- OS Version: Windows 10 Pro 1903

Steps to Reproduce:

1. Open an HTML file
2. Try to hide part of the HTML code using the collapse feature
3. The collapse does not appear

Does this issue occur when all extensions are disabled?: Yes

Collapse takes a long time to be enabled on files with the extension '.html'. I already disabled all plugins and the same problem persists. On my machine, it takes about 2-4 minutes to open, and that's annoying stress, because it gets in the way of productivity.

Note: I've checked similar articles, but no compatible solution.

**Comment by roblourens** [comment]
Is it a very large file? Can you share the file? Are other things slow too?

**Comment by thiagosantoscunha** [comment]
@roblourens The files that are giving problem are extremely small files. Contains an average of 3Kb and has 30 to 50 lines of code.

**Comment by insinfo** [comment]
@roblourens 
This is happening to me too, regardless of file size whether it is in a few line HTMl files, in files under 50 lines.
I am currently editing html files in an AngularDart project, and every time I quit editing the html file to dart and when I go back to html editing the Collapse icons disappear and don't appear anytime soon after a while clicking several times next to the line number there appears finely.

**Comment by aeschli** [comment]
> it takes about 2-4 minutes to open

Are you on a very slow machine? That would explain the folding ranges to not appear. There's a timeout of 30 seconds before we give up waiting for the language server to return the results.

Also, can you set `"html.trace.server": "messages"` and look at the `Output view, HTML Language Server tab` while you toggle the editors?
![image](https://user-images.githubusercontent.com/6461412/67192287-9988e980-f3f3-11e9-8a58-fd30854132ae.png)

You should see the folding ranges request every time you switch between a html editor.

**Comment by insinfo** [comment]
The machine is a sixth generation core i5 2.4 with 16GB of memory DDR4. In webstorm jetbrains this does not happen.
I will do it tomorrow
> set "html.trace.server": "messages" and look at the Output view, HTML Language Server tab while you toggle the editors

**Comment by thiagosantoscunha** [comment]
My computer have the settings:

Core i7 8700k
16GB RAM
NVidea 1050TI
SSD 420GB + 10TB HD

**Comment by aeschli** [comment]
@thiagosantoscunha That's strange. If you could turn on tracing as described in https://github.com/microsoft/vscode/issues/82847#issuecomment-544903933 ?

**Comment by insinfo** [comment]
This problem occurs in AngularDart projects
