### ISSUE TITLE
Keep Open is disabled on the file tab right click menu

### ISSUE THREAD

**Issue by jcollum-autodesk** [microsoft/vscode#82855]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open a file
1. Right click

![image](https://user-images.githubusercontent.com/55416082/67109240-eb780800-f184-11e9-944c-f8c5a0b35791.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 4|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
django-html|bib|1.3.0
jsrefactor|cms|2.20.4
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|2.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
intellij-idea-keybindings|k--|0.2.34
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
vscode-yaml|red|0.5.3
git-merger|sha|0.4.1
local-history|xyz|1.7.0

</details>

**Comment by roblourens** [comment]
That is for "preview" tabs which have their title in italics. That is not a preview tab so it's not relevant.

**Comment by jcollum-autodesk** [comment]
There are no italics on the tab I'm clicking on. Reopen please.

**Comment by jcollum-autodesk** [comment]
If I can't use "Keep Open" for a file then that option just shouldn't be on the menu. As it is it's misleading -- it's telling me that there is a "never close" option akin to a pinned tab but that for some reason that option is not available for this file. 

I suggest that: 

1. if a file is opened in preview, Keep Open is available on right-click 
1. if a file is opened with double-click (actually open) Keep Open is not available on right-click -- the file is already "open", so why have the dialog option there? It's misleading the user.

**Comment by roblourens** [comment]
Well it's disabled when it's not applicable to the current state, but present so you know that it exists for other cases. That's a typical way to deal with this situation and matches what we do with all menus in other cases.

**Comment by jcollum-autodesk** [comment]
I don't see the benefit of having it there if I can literally never use it. It implies that I can sometimes use it -- but I can't. Not for a file that is opened normally. It's just confusing to have it there.
