### ISSUE TITLE
An issue in the "Report Issue" dialog with a normal sized headline and one character in "Steps" section is too much data to send to github

### ISSUE THREAD

**Issue by jcollum-autodesk** [microsoft/vscode#82856]
This is the issue I was trying to report: https://github.com/microsoft/vscode/issues/82855

I took the"Steps" section down to one character and I still got the above warning. 

I'm sure there are reasons for this but the dialog doesn't seem very useful if it can't send an issue with system info and a single character in the dialog box. Maybe you need to refactor this UX. 

![image](https://user-images.githubusercontent.com/55416082/67109711-faab8580-f185-11e9-86bf-d7a73c94a998.png)

**Comment by RMacfarlane** [comment]
@jcollum-autodesk To open the new issue page on GitHub with data prefilled, we have to send data through the url query. We don't know what the default browser is, and for some browsers, a url that is too long will result in the page not loading. (There's also a bug with GitHubs login page and long urls even for browsers that don't have a restrictive character limit.)

If we posted the data and actually created the issue on click instead, we
1. need an auth flow for GitHub
2. should add a way of previewing the issue text
3. aren't able to let users attach screenshots at that time since there is no public GitHub api for uploading files

**Comment by jcollum-autodesk** [comment]
The system/extension information is probably the culprit. Maybe those should have a copy button for that information that shows after the issue is submitted?

**Comment by RMacfarlane** [comment]
Yeah, that information is very long.

I don't think separating out the step to include them is a good idea, though. That seems like it would just create more burden to the user, since you would have to go back and forth between the browser and VSCode copying information.

**Comment by jcollum-autodesk** [comment]
No matter how you slice it I'm gonna have to do this in a 2 step process: 

1. enter a full description of the issue, come back to grab the system information
1. get all the system information and then enter the actual description of the issue on the github page

The process would be cleaner if it was clear that I won't be able to put in all the information necessary on the first pass. 

How about: 

1. I enter an issue
1. when I click send a dialog comes up that says "your system information has been copied to the clipboard, please paste into the github issue when that page shows up" 
1. it gets sent to github
1. when that issue page comes up, I paste the system information into a placeholder section of the issue 

Alternately the flow could just ask me to write the issue out when I get to github's issue page. \

It looks like no matter what it's going to be a 2 step process.

**Comment by RMacfarlane** [comment]
I'm a bit confused, as the flow you've described is what should happen currently. Perhaps the wording of the dialog could be made clearer?

**Comment by jcollum-autodesk** [comment]
I was 100% expecting to be able to enter the issue and all the system information in that dialog box. I wasn't able to. That was surprising. [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) says that I should be able to put all the necessary info in that dialog, since there are places for all of it. 

I'm saying the workflow needs to be clearer -- I definitely have to do this in 2 passes, since even a few characters in the issue description will result in a failure.  I shouldn't be hitting failures as part of a normal workflow.

**Comment by RMacfarlane** [comment]
Sorry, I'm still missing something here, I don't understand why 2 passes are needed. If you click the "Yes" button shown in the original screenshot, everything you have typed in the issue and all of the system information should be copied to the clipboard. The browser should be opened to GitHub and you can then paste it. The current message doesn't indicate that the GitHub issue page will still be opened, which is confusing

**Comment by jcollum-autodesk** [comment]
> everything you have typed in the issue

But I typed one character, what's the use of that? Why have the textbox at all? 

If I am unable to actually type my "Steps to Reproduce" in to that dialog, what is the point of having that textbox there? It's confusing/misleading. 

> everything you have typed in the issue and all of the system information should be copied to the clipboard.

What? There's no message of any kind telling me that. 

-----

2 passes: 

1. enter a full description of the issue, 
1. come back to grab the system information

OR 

1. get all the system information, send to github
1. enter the actual description of the issue on the github page

**Comment by RMacfarlane** [comment]
> What? There's no message of any kind telling me that.

Once again, I think the text of this message needs revising, but this is what I meant:

![Screen Shot 2019-10-21 at 11 53 15 AM](https://user-images.githubusercontent.com/3672607/67234141-6ea19400-f3f9-11e9-91ff-79348629aff9.png)

The intended flow is that you

- type the title and complete steps to reproduce in the issue reporter
- if this + system information is too long, the dialog appears asking to use your clipboard
- github is opened and you paste everything

Yes, with even a small number of extensions installed the dialog is likely to appear, but it shouldn't prevent you from writing out the complete "Steps to Reproduce" and having that copied into the issue

**Comment by jcollum-autodesk** [comment]
OK yeah I see the message you mean now. 

I only have like 6 extensions installed. I suspect that's a normal amount. Keeping that in mind I suspect most users will hit this message. 

The flow could be improved. If the list of extensions and system information is too large how about just replacing the "Steps" textbox with a message like "Too much data to send to github, your issue will be created but you'll have to enter Steps to reproduce after the issue is created." 

That way I know what's going to happen before I hit an error message.

**Comment by RMacfarlane** [comment]
@jcollum-autodesk Can you please try pressing the "Yes" button in that dialog to understand the current flow?

**Comment by jcollum-autodesk** [comment]
I did that. But before that I trimmed off the "steps to reproduce" a few times to try to get it to fit. I was just thrown off by the error and assumed I had to trim down so it would work. 

I was being a bad user and just reacting to the first sentence. I think just changing the string would probably help, something like "This message is too large to send to github directly, please press Yes and we will copy it to your clipboard so you can paste it in to the description box on the github issue that we are about to create" 

Something like that but less wordy :D

**Comment by RMacfarlane** [comment]
Yeah the first sentences does make it sound like it has completely failed. Thanks, I like your suggestion!

**Comment by jcollum-autodesk** [comment]
Cool thanks for working through it with me
