### ISSUE TITLE
ctrl+d and paste behavior

### ISSUE THREAD

**Issue by evheath** [microsoft/vscode#82850]
Issue Type: <b>Bug</b>

Ctrl+d selects multiple items of the same type; creating multiple cursors

Ctrl+v (paste) no longer pastes at all the cursors
-previously it did
-now it just pastes at initial cursor 

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
vscode-eslint|dba|1.9.1
dotenv|mik|1.0.1
sublime-keybindings|ms-|4.0.3
vetur|oct|0.22.4
material-icon-theme|PKi|3.9.1
java|red|0.51.0
rust|rus|0.7.0
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.4.0

</details>

**Comment by evheath** [comment]
Also of note:

Typing at multiple cursors still works just fine.

If text is copied from multiple cursors then pasted somewhere else, **all** selections are pasted to first cursor

**Comment by roblourens** [comment]
I can't repro this. Can you include a video?

**Comment by evheath** [comment]
Likely a client side issue. After your comment I re-installed and restarted. Problem did not persist.

This issue can be considered closed

**Comment by johnquintal** [comment]
Apologies for commenting on a closed issue. But I can reproduce this so I reinstalled VSCode. The problem persisted. With ALL extensions disabled, the problem goes away. I turned off all my extensions and turned them on one by one to determine if it was an extension causing the problem.

In MY case it was, at least: Pivotal.vscode-manifest-yaml@1.11.0 extension. As @evheath does not appear to have that extension, I would suggest that some extensions can cause the problem, but, of course, YMMV.

**Comment by alexandrudima** [comment]
This seems to be caused by the `redhat.java` extension which overrides the paste implementation [here](https://github.com/redhat-developer/vscode-java/blob/4a9389e580b9f7c7fa8c4d2e0140e7a588fffcf0/src/settings.ts#L154). I have opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1115) directly against the extension.

Possible workarounds: configure `"java.actionsOnPaste.organizeImports": false` or disable/uninstall the `redhat.java` extension.
