### ISSUE TITLE
How to add or remove the above button, such as add Forword

### ISSUE THREAD

**Issue by shishi614** [microsoft/vscode#82854]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by shishi614** [comment]
I looked at the previous one and asked something different, StackOverflow no one answered, I mean how to display the frequently used commands in the toolbar under the VScode menu bar, thank you

**Comment by roblourens** [comment]
Sorry, not sure what you are talking about, please give more details.

**Comment by shishi614** [comment]
![image](https://user-images.githubusercontent.com/20469171/67109833-e8702c80-f203-11e9-83a2-887d9b8fff73.png)
I want to customize other commands I want to use in this toolbar. Can I do that now

**Comment by shishi614** [comment]
Such as forward and backward commands, I can delete unnecessary commands

**Comment by roblourens** [comment]
You already filed this bug in https://github.com/microsoft/vscode/issues/82830. You can look at the code for extensions to see how they did things, or look through our docs.
