### ISSUE TITLE
Can't type in Integrated Terminal

### ISSUE THREAD

**Issue by Li0nh3art** [microsoft/vscode#82858]
- VSCode Version: 1.39.2
- OS Version: Window 10 64bit

Steps to Reproduce:

1. Open the terminal using ctrl+`
2. The cmd will open but I am unable to type in the integrated terminal within VS code. I have attempted to use the Insiders build of VS Code and I still can't type in the integrated terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Run `ver` in cmd.exe and paste the output

**Comment by Li0nh3art** [comment]
![image](https://user-images.githubusercontent.com/56652334/67314569-e099dc00-f4d2-11e9-8c1c-9d1605fc1820.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
