### ISSUE TITLE
For the writing of the java language, this is a fatal bug, because you can't see the complete package namespace, which makes it impossible to select the correct class for code writing. This fatal bug has been proposed for more than two years. Why no one has priority to solve this problem? The problem, if it is a technical problem, you can refer to the relevant implementation and source code of Eclipse or VisualStudio2019!

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#82853]
For the writing of the java language, this is a fatal bug, because you can't see the complete package namespace, which makes it impossible to select the correct class for code writing. This fatal bug has been proposed for more than two years. Why no one has priority to solve this problem? The problem, if it is a technical problem, you can refer to the relevant implementation and source code of Eclipse or VisualStudio2019!
![vscode](https://user-images.githubusercontent.com/27546390/67107584-4fd7ad80-f1ff-11e9-8d3a-3d6e10347bad.png)

**Comment by 395053994** [comment]
Take a look at Eclipse
![2019-10-18_233732](https://user-images.githubusercontent.com/27546390/67108369-f7091480-f200-11e9-91b1-c2a6d3ee0471.png)
![2019-10-18_234117](https://user-images.githubusercontent.com/27546390/67108412-02f4d680-f201-11e9-9958-5f0cdef35b0a.png)
This logic function is very simple to implement! Nothing is difficult! Why hasn't it been repaired?

**Comment by 395053994** [comment]
This logic function written by Visual Studio 2019 in C# is better and worth learning.

**Comment by roblourens** [comment]
The suggest widget can show more details in a flyout box on each item. Try clicking the `(i)` button. If the Java extension doesn't use it, you can file a feature request on their repo.
