### ISSUE TITLE
Incorrect C statement code reduction when define in the middle

### ISSUE THREAD

**Issue by jaudiger** [microsoft/vscode#82851]
- VSCode Version: 1.39.2
- OS Version: Windows 10 (64 bits) + ArchLinux WSL

Steps to Reproduce:

1. Use the following code inside a `test.c` file:

```c
void my_function()
{
    if (1)
    {
        int a;

#ifdef MY_DEFINE
        a = 0;
#else
        a = 1;
#endif
    }
}
```

2. Try to minimize the if statement with this arrow:

![image](https://user-images.githubusercontent.com/31616285/67106490-066d6b00-f1cb-11e9-84d1-e897366678a5.png)

![image](https://user-images.githubusercontent.com/31616285/67106524-17b67780-f1cb-11e9-8071-7aef6f819fd7.png)

Expected: I would have expected the same behaviour as in Visual Studio 2019: 
![image](https://user-images.githubusercontent.com/31616285/67106808-96abb000-f1cb-11e9-963f-b98bb43636ea.png)

Does this issue occur when C/C++ extension is disabled?: Yes

**Comment by aeschli** [comment]
You need to file this against the extension that you use for C/C++. The folding range provider that defines the folding ranges is defined there.
