### ISSUE TITLE
Replace vs search background color difference too subtle

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8286]
#8184

Steps to Reproduce:

1. I like how we use a different background color in the search box depending if we show search results or replaced results
2. However the color difference is very subtle - it should be much more prominent IMHO
3. You just change the transparency by 0.15 - maybe increase this, and also you might need different change based on light / dark theme

**Comment by sandy081** [comment]
This will be handled with #8302. 

Duplicates #8302
