### ISSUE TITLE
Interactive merge deletes extra chunks

### ISSUE THREAD

**Issue by MiddleMan5** [microsoft/vscode#82861]
Issue Type: <b>Bug</b>

When performing an interactive merge (using the interactive diff view) the "Accept ... Change" buttons delete more code than what is highlighted. The dialog also takes upwards of 5 seconds to disappear and allows for multiple clicks which continue deleting unmarked code blocks

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4389)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.34GB (16.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
systemd-unit-file|coo|1.0.5
arm|dan|0.5.0
vscode-markdownlint|Dav|0.31.0
make-hidden|dev|3.0.3
gitlens|eam|10.1.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|30.0.0
bitbake|Eug|1.1.2
vscode-highlight|fab|1.3.4
html-preview-vscode|geo|0.2.5
beautify|Hoo|1.5.0
jenkinsfile-support|ivo|0.4.4
vscode-edit-csv|jan|0.1.4
markdown-shortcuts|mdi|0.11.0
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
vsliveshare|ms-|1.0.988
codemap|ole|1.10.0
material-icon-theme|PKi|3.9.1
devicetree|plo|0.1.1
vscode-yaml|red|0.5.3
bash-beautify|sha|0.1.1
debug|web|0.23.1
markdown-all-in-one|yzh|2.5.1
linkerscript|Zix|1.0.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
You're going to have to provide more information than that... what are the **exact** steps to reproduce what you are seeing?
