### ISSUE TITLE
 Marketplace not loading anything unless vscode is started from the terminal

### ISSUE THREAD

**Issue by hamid-r-shakibi** [microsoft/vscode#82868]
Hi, im using this version of vscode:

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-29-generic

when I run vscode from shortcut icon, when I go to the extensions marketplace it doesn't show anything. it's just loading all the time and not showing any extensions.
but when I run it from the terminal it works!
this is a picture after 15 minutes waiting :

![image](https://user-images.githubusercontent.com/34796399/67128427-7a7a3400-f208-11e9-898f-afa05042a603.png)

**Comment by roblourens** [comment]
Any errors in the developer tools (Help > Toggle Developer Tools)?

Are you behind a proxy? Maybe your proxy is configured with environment variables in the terminal?

**Comment by hamid-r-shakibi** [comment]
> Any errors in the developer tools (Help > Toggle Developer Tools)?
> 
> Are you behind a proxy? Is it configured in vscode?

yes, the terminal always runs under tor socks .this is Console output:
![image](https://user-images.githubusercontent.com/34796399/67140309-269e3800-f266-11e9-961f-7d1e6077b55a.png)

**Comment by hamid-r-shakibi** [comment]
Any solution?!

**Comment by sandy081** [comment]
Can you try opening shared process developer tools using command `F1 > Developer: Toggle Shared Process` and see if there are any errors?
