### ISSUE TITLE
[BUG] Persistent JSON Parser Error

### ISSUE THREAD

**Issue by angelhdz** [microsoft/vscode#82866]
- VSCode Version: 1.39.1
- OS Version: Windows 10 Pro 64bit

Steps to Reproduce:

1. Write invalid JSON in any JSON file (launch.json, tasks.json, theme or settings JSON, or in a NodeJS project in the package.json, etc.)
2. JSON Parser throws errors (expected)
3- Fix the invalid JSON.
4- Errors don't go away, even by saving the current file.

More info:

Errors only go away if I reload the workspace.  This happens in every workspace of every programming language, with any extension. 

Steps to fix or debug:

1. Tried uninstalling all extensions. Errors keep happening.

This started to happen in the latest VSCode updates.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you set `"json.trace.server": "messages"` and check out the `Output > JSON Language Server` tab. On every modification of save you should see a 'textDocument/publishDiagnostics' message.

![image](https://user-images.githubusercontent.com/6461412/67278999-7715cf80-f4ca-11e9-92c2-68f07279703e.png)

**Comment by angelhdz** [comment]
Thanks for replying @aeschli . I will leave `"json.trace.server": "messages"` for a while so if it happens again, I can provide that info, but since I updated VSCode yesterday, I haven't had the issue.

I just tried to deliberately provoke errors on many JSON files in 2 of my workspaces, and then I fix the invalid JSON and save the file, errors go away as expected.

Will keep you posted. Cheers!

**Comment by aeschli** [comment]
Clsoing, Please reopen if you have steps to reproduce.
