### ISSUE TITLE
VSCode no longer showing Go To Definition on right click has returned 

### ISSUE THREAD

**Issue by Sevensnake** [microsoft/vscode#82860]
Right click go to definition has returned in Version: 1.39.2.  I know this has been and on and off return. It has returned. Please fix.

- VSCode Version:  .39.2.
- OS Version:  Windows 10 pro

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please describe in more detail. If there was a previous issue it would help to link it.

**Comment by Sevensnake** [comment]
There is really no detail to provide.  I open a folder project.  I go to the code and it is not there. I will get a screen shot for you on Monday. Thanks.

**Comment by roblourens** [comment]
What language? What extensions are you using?
