### ISSUE TITLE
Marketplace URL handler

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#82869]
These URLs trigger the vscode default URL handlers.
```
vscode:extension/ms-vscode.csharp
vscode-insiders:extension/ms-vscode.csharp
```

They work great when VS Code is already open: the extension `ms-vscode.csharp` opens up in the marketplace.

When no instance of VS Code is running, VS Code opens, but the marketplace doesn't show up.

Fixing this would allow an `Open in marketplace` button.

VS Code version: Code - Insiders 1.40.0-insider (3f6ed25939b8ef157a7a41e0dc43b517898d4005, 2019-10-15T05:26:04.723Z)
OS version: Linux x64 4.15.0-65-generic

**Comment by SupinePandora43** [comment]
also: when vscode trying to open url with extension page on marketplace, it opens browser!

**Comment by joaomoreno** [comment]
Why does this keep breaking.

**Comment by joaomoreno** [comment]
Very likely the same as https://github.com/microsoft/vscode/issues/73101

cc @bpasero

**Comment by joaomoreno** [comment]
Actually, no... the fix for #73101 caused this issue!

**Comment by SupinePandora43** [comment]
@joaomoreno, can i make issue for https://github.com/microsoft/vscode/issues/82869#issuecomment-544117145 ?

**Comment by joaomoreno** [comment]
> also: when vscode trying to open url with extension page on marketplace, it opens browser!

What are the steps to reproduce?

**Comment by SupinePandora43** [comment]
@joaomoreno , write in some file vscode marketplace extension url, and open it (CTRL+Click)
