### ISSUE TITLE
Certain file with certain grammar causes vscode to hang (in colorization code)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#82865]
Issue Type: <b>Bug</b>

1) Make sure the extension "Azure Resource Manager Tools" is installed (this bug only repros when the arm-expression-string.tmLanguage.json grammar from this extension is installed)
2) New file
3) copy the following string into this file:
```
"            \"xmlCfg\": \"[base64('<WadCfg> <DiagnosticMonitorConfiguration overallQuotaInMB=\\\"4096\\\" xmlns=\\\"http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration\\\"> <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter=\\\"Error\\\"/> <Logs scheduledTransferPeriod=\\\"PT1M\\\" scheduledTransferLogLevelFilter=\\\"Error\\\" /> <Directories scheduledTransferPeriod=\\\"PT1M\\\"> <IISLogs containerName =\\\"wad-iis-logfiles\\\" /> <FailedRequestLogs containerName =\\\"wad-failedrequestlogs\\\" /> </Directories> <WindowsEventLog scheduledTransferPeriod=\\\"PT1M\\\" > <DataSource name=\\\"Application!*\\\" /> </WindowsEventLog> <CrashDumps containerName=\\\"wad-crashdumps\\\" dumpType=\\\"Mini\\\"> <CrashDumpConfiguration processName=\\\"WaIISHost.exe\\\"/> <CrashDumpConfiguration processName=\\\"WaWorkerHost.exe\\\"/> <CrashDumpConfiguration processName=\\\"w3wp.exe\\\"/> </CrashDumps> <PerformanceCounters scheduledTransferPeriod=\\\"PT1M\\\"> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\Memory\\\\\\\\Available MBytes\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\Web Service(_Total)\\\\\\\\ISAPI Extension Requests/sec\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\Web Service(_Total)\\\\\\\\Bytes Total/Sec\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\ASP.NET Applications(__Total__)\\\\\\\\Requests/Sec\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\ASP.NET Applications(__Total__)\\\\\\\\Errors Total/Sec\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\ASP.NET\\\\\\\\Requests Queued\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\ASP.NET\\\\\\\\Requests Rejected\\\" sampleRate=\\\"PT3M\\\" /> <PerformanceCounterConfiguration counterSpecifier=\\\"\\\\\\\\Processor(_Total)\\\\\\\\% Processor Time\\\" sampleRate=\\\"PT3M\\\" /> </PerformanceCounters> </DiagnosticMonitorConfiguration> </WadCfg>')]\","
```
4) Set the language to Azure Resource Manager Template
!) vscode hangs

NOTE: This code is *not* a normal string to have in an ARM template file. Rather, it's from a snippet for such files (i.e., it's encoded an extra time).  I found this scenario by accidentally setting the language to arm-template while I had the snippet file open.  I haven't heard of any customers hitting this yet, so I'll let you guys decide on the priority.  I tried to narrow down the string further, but the repro became inconsistent at that point.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|28, 34, 29|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-antlr4|mik|2.1.1
vscode-azureappservice|ms-|0.16.0
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|0.19.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
azure-account|ms-|0.8.6
csharp|ms-|1.21.5
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.7.0
azure-hdinsight|msh|1.1.7
arm-snippets|sam|1.4.19
tmcolor|sle|0.0.1
testlicense-donotuse|Ste|0.0.6
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This is your extension right? It's possible for the expressions in tm language files to blow up, and there isn't much vscode can do about it unfortunately. Here's a tip for figuring out which pattern has the problem: https://github.com/microsoft/vscode/issues/40279#issuecomment-361405690
