### ISSUE TITLE
"Maximize Window" doesn't change window state

### ISSUE THREAD

**Issue by Gameghostify** [microsoft/vscode#82864]
- VSCode Version: 1.40.0-insider (system setup) commit `be68a4e`
- OS Version: Windows Version 10.0.18362 Build 18362

---

Steps to Reproduce:

1. Click the "Maximize Window" Button

The window will now have the dimensions of the screen, which is correct behavior. However, the "Maximize Window" Button has not changed state to the "Restore Window" state, so pressing it again will not restore the previous window dimensions

This **does not happen** when using the ["Snap Window"](https://support.microsoft.com/en-us/help/4027324/windows-10-snap-your-windows) function (might be because this way, Windows/the OS handles the window positioning and size); the "Maximize Window" button will correctly change to the "Restore Window" button when using window snapping

---

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by yume-chan** [comment]
duplicate of #81102

**Comment by Gameghostify** [comment]
@yume-chan 

Thanks, I didn't see that one.

Closing this issue since this is already discussed in #81102 (and an Electron issue)
