### ISSUE TITLE
Add Settings option to keep terminal maximized

### ISSUE THREAD

**Issue by andradei** [microsoft/vscode#82867]
Proposal to add a setting option for the terminal panel to remember if it is maximized.

Current workflow for those who want to see a maximized terminal panel is tedious and repetitive:
Toggle Terminal (show it) -> Toggle Maximize Panel Size -> Use terminal (read, type commands, etc) -> Toggle Terminal (hide it)

Would be nice to toggle the terminal and see it already maximized. So an option for it to remember that would be great.

**Comment by sbatten** [comment]
/duplicate #82722

resolving to previous request to aggregate support
