### ISSUE TITLE
Invisible Prompt / Directory Upon Terminal Launch

### ISSUE THREAD

**Issue by HoopsFTWGG** [microsoft/vscode#82872]
- VSCode Version: 
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

- OS Version:
Windows 10 Home
Version 1809
OS Build 17763.805

Steps to Reproduce:

1. open vsc (by any method)
2. open the terminal

Does this issue occur when all extensions are disabled?: Yes

This is the exact same issue as [#57803](https://github.com/microsoft/vscode/issues/57803) and [#61172](https://github.com/microsoft/vscode/issues/61172) which was supposedly resolved.

![empty](https://user-images.githubusercontent.com/35324691/67131108-3fe8ab00-f1b8-11e9-9ca1-3a115f6a3f06.PNG)

UPDATE: changing the shell to bash instead of powershell seems to be a fix.

**Comment by Tyriar** [comment]
The duplicate issue you linked tells you what the problem is https://github.com/microsoft/vscode/issues/57803#issuecomment-449495423
