### ISSUE TITLE
Custom markdown styles not working?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8287]
Refs: https://github.com/Microsoft/vscode/issues/7945

I tried to configure a custom CSS with 3 different approaches:
* relative file
* absolute file path
* URL

I do not seem to get it to work:

![image](https://cloud.githubusercontent.com/assets/900690/16411303/b5fda0d8-3d26-11e6-8026-d20cabe3f016.png)

**Comment by sandy081** [comment]
It does not seem to work to me neither

**Comment by kieferrm** [comment]
I improved the documentation in the user settings. You can use URLs like `file:///your file path` or `http://...`. I also made a couple changes to ensure we look workspace relative if there is an open workspace.

**Comment by bpasero** [comment]
Works for me when using a local file path or absolute path, but not when using a URL like https://gist.githubusercontent.com/bpasero/5574e2cb0cd47aaf9870f956adcc7ff5/raw/bf2a775e5c71eda058b534ae37fa03b930026a60/gistfile1.css or https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css

**Comment by kieferrm** [comment]
What I'm seeing is that the stylesheet is correctly added to the html page that is being displayed. However, when I open the dev tools inside the webview, the stylesheets don't seem to have any content.

**Comment by kieferrm** [comment]
The issue is that GitHub responses with `X-Frame-Options: deny`.

**Comment by bpasero** [comment]
Ah ok, sorry about that...

**Comment by wghglory** [comment]
@kieferrm @bpasero @sandy081  I figured out a way. If you paste your gist url(i.e https://gist.githubusercontent.com/wghglory/9b6e502a0c81d135e83fce87be83a18c/raw/7a9bdd06e9f2fe4a53d84900d5ac77912f939873/github-markdown.css) here: https://rawgit.com, it will generate a new url for you. You can paste that into your settings.json.

```
"markdown.styles": [
    // your gist url, not working
    // "https://gist.githubusercontent.com/wghglory/9b6e502a0c81d135e83fce87be83a18c/raw/7a9bdd06e9f2fe4a53d84900d5ac77912f939873/github-markdown.css"

    // use this generated new url
    "https://cdn.rawgit.com/wghglory/9b6e502a0c81d135e83fce87be83a18c/raw/7a9bdd06e9f2fe4a53d84900d5ac77912f939873/github-markdown.css"
],
```

**Comment by Molunerfinn** [comment]
In macOS, the `file:///your file path` seems not working....

**Comment by wghglory** [comment]
@Molunerfinn use `file:/your path`

**Comment by Molunerfinn** [comment]
@wghglory still not working....

**Comment by kieferrm** [comment]
@Molunerfinn I use the following in my settings:
```json
"markdown.styles": [
        "/Users/kieferrm/Development/markdown.css"
    ]
```
