### ISSUE TITLE
Provide versions of extensions in 'About' window

### ISSUE THREAD

**Issue by kichalla** [microsoft/vscode#82878]
Issue Type: <b>Feature Request</b>

I was trying to report a bug for an extension and wanted to give information about VS Code version as well as the version of the extension that I am using, but I noticed that only VS Code information is present in 'About' window. It would be nice if the 'About' window gives information of all extensions being used too.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
Use the extension view to get version info, such search `@installed`

Many users have quite a few extension installed and it would not be practical or helpful to shove all the information for these into the about window
