### ISSUE TITLE
For the writing of the java language, this is a fatal bug, because you can't see the complete package namespace, which makes it impossible to select the correct class for code writing. This fatal bug has been proposed for more than two years. Why no one has priority to solve this problem? The problem, if it is a technical problem, you can refer to the relevant implementation and source code of Eclipse or VisualStudio2019!

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#82879]
For the writing of the java language, this is a fatal bug, because you can't see the complete package namespace, which makes it impossible to select the correct class for code writing. This fatal bug has been proposed for more than two years. Why no one has priority to solve this problem? The problem, if it is a technical problem, you can refer to the relevant implementation and source code of Eclipse or VisualStudio2019!
![vscode](https://user-images.githubusercontent.com/27546390/67135916-f187ea80-f251-11e9-8f02-3b10b87bda48.png)
Take a look at Eclipse
![2019-10-18_233732](https://user-images.githubusercontent.com/27546390/67135924-0a909b80-f252-11e9-9bca-af95f631739b.png)
![2019-10-18_234117](https://user-images.githubusercontent.com/27546390/67135936-1e3c0200-f252-11e9-97a6-abcc48cf4cf7.png)
This logic function is very simple to implement! Nothing is difficult! Why hasn't it been repaired?
This logic function written by Visual Studio 2019 in C# is better and worth learning.

**Comment by roblourens** [comment]
You already filed this issue and I already replied, you can reply there if needed.
