### ISSUE TITLE
typescript language service fails to report tsc error and suggest incorrect informations

### ISSUE THREAD

**Issue by falsyvalues** [microsoft/vscode#82870]
- VSCode Version: 1.39.2 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Enter following snippet from [typescriptlang.org](http://www.typescriptlang.org/play/#code/KYOwrgtgBAkgCgS2AY2FA3gKCj2ATKAXigCIE8SAabXAMQQCcBnAFwDkBDCNYkgM0asQXYFRo4AMh1aduRUgBtpLYdzG4oAQQDmPUh10lMAX0yYEIFsAZ8OqWIhTA41pgHsQGcVADa8JKgAdDB4ALoAXFCsDBbaUAA+UOAKCgDc3n6OQfTM7CIRUSwxIHGJyWkZ-k6BUjL5kdGxCUlgKekamQHAgTrABeAQAEbWzeXppph8YCDILAgeULosWc6uHgA8ACpQwAAeViB4TA5dAHwAFAAOXZHbiZs+oQCUkYjIANbrVaguzB6UUE2py8GmQHlYUGuTmOxHOjyg0kBjyegTBMw4LCuXSe6W8aIhlzWIEi31Wf08xCwGg05EiJAAjOpqTgBLlVMA6ayhCImcylNzuHT+SoedRmTgDByoABmAAM3mMuI0DGALDADE8UNQTECKrwYFQ6zen1Jv3cIABQIuVwBWuAISeRGBVPFKrVGsh7VwxltRJxJjM+JYUDc8iWKzNHnOpJ6un9AHp44CABYIY5MZNuVoEWwIBRQCw7PAIFhuBhQQZgYMlqB4NzAJggADkLEwbk61VqeW4oTbgWF7KAA) to editor
2. Access to unknown property should report error, but it doesn't:

**Expected behaviour:**
```typescript
o[IPiece.LastName]
// => Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>'.
o.lastname
// => Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>'.
```
**Current behaviour:**
```typescript
o[IPiece.LastName]
// => No error at all
o.lastname
// => Property 'lastname' does not exist on type 'Pick<IPiecePerson, IPiece.Age>'.
```
3. Trigger suggest `control + space`

**Expected behaviour:**
```typescript
age
```
**Current behaviour:**
```typescript
IPiece enum
```

~~Does this issue occur when all extensions are disabled?: Yes/No~~

**Comment by mjbvz** [comment]
This is expected. The website essentially sets `"strict": true` (look at the config). VS Code does not enable strict mode for typescript by default; you have to configure it in your `tsconfig.json`

**Comment by falsyvalues** [comment]
Hi @mjbvz,
You have intentionally skipped point 3?

**Comment by mjbvz** [comment]
One point per issue please. And explain where you are triggering the completions

**Comment by falsyvalues** [comment]
@mjbvz It's just step by step, screenshot added to explain triggering suggestion.

**Comment by falsyvalues** [comment]
@mjbvz Should I create another one then?

**Comment by falsyvalues** [comment]
Moved to #83097.
