### ISSUE TITLE
"overwriteOnAccept": false breaks jsdoc completions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#82874]
Issue Type: <b>Bug</b>

**Repo**
For the js file:

```js
/** */
function foo(x) {}
```

1. Place cursor inside the jsdoc comment after the `/**` and request completions
1. Accept the jsdoc completion

**Expected**

```js
/**
 * 
 * @param {*} x 
 * @param {*} y 
 */
function abcdef(x, y) { }
```

**Actual**
Extra trailing `*/` in the result

```js
/**
 * 
 * @param {*} x 
 */ */
function foo(x) {}
```

This works as expeted if I set `"editor.suggest.overwriteOnAccept": true`

VS Code version: Code - OSS Dev 1.40.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|18%|
</details>

**Comment by mjbvz** [comment]
@jrieken For JSDoc completions, I try to explicitly set the completion item range to cover the entire `/** */`.

**Comment by jrieken** [comment]
Hm, that's interesting and tricky. The feature is implemented by either extending or cropping the provided range... This is the unwanted consequence of that and I am not sure how to handle this...

**Comment by jrieken** [comment]
This also happens with JSON...

**Comment by jrieken** [comment]
Closing this after pushing a workaround. A proper fix requires new API and extension-buy-in. That's tracked here https://github.com/microsoft/vscode/issues/10266#issuecomment-544520553

**Comment by JacksonKearl** [comment]
Unable to verify the old behaviour... `"editor.suggest.overwriteOnAccept": false` seems to be missing?

**Comment by mjbvz** [comment]
@JacksonKearl For testing, please make sure that  jsdoc completion does not cause a duplicate closing `*/` to be be inserted
