### ISSUE TITLE
Expose dialog title in extensions API

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#82871]
The current openDialogOptions are:
```
canSelectFiles?: boolean
canSelectFolders?: boolean
canSelectMany?: boolean
defaultUri?: Uri
filters?:
openLabel?: string
```

Could we also have access to the dialog title?<br />I believe electron does expose it [here](https://electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options).

**Comment by sguillia** [comment]
lol if this gets 20 upvotes I'll pay you a beer

**Comment by GustavoASC** [comment]
@aeschli @alexr00
I believe it's easy to expose dialog title in public API. Can I help you making a pull request on this?

We need to:
1. Add an optional parameter named _title_ on both _OpenDialogOptions_ and _SaveDialogOptions_ interfaces (which are currently located on vscode.d.ts)
2. Add the same optional parameter on _MainThreadDialogOpenOptions_ and _MainThreadDialogSaveOptions_ interfaces
3. Modify _MainThreadDialogs.convertOpenOptions()_ method, delegating this new parameter to IOpenDialogOptions.title

According to [this guide](https://github.com/Microsoft/vscode/wiki/Extension-API-process) the API modifications should be done on _vscode.proposed.d.ts_ for later discussions, right?

(This is the first time I try to contribute to a public VSCode API, so I'm still getting familiar with the overall process).

Thanks in advance!

**Comment by alexr00** [comment]
@GustavoASC all that is correct. I would accept a PR for this (assuming @aeschli doesn't have any concerns).

**Comment by alexr00** [comment]
Re-opening since we now try to keep issues around for proposed API.

**Comment by GustavoASC** [comment]
Hello @sguillia! Could you tell us if these new _title_ parameters on _OpenDialogOptions_ and _SaveDialogOptions_ are OK for you?

They are currently available under proposed API :+1:

**Comment by GustavoASC** [comment]
@alexr00 I would like to use this parameter on an extension we are developing here at the company... Could we move this from proposed to stable API on the next release? Thank you!

**Comment by GustavoASC** [comment]
@alexr00 If it's simply move code from vscode.proposed.d.ts to vscode.d.ts I can do that with a PR :smiley:.
Can we do it on this issue or should we create another issue with _api-finalization_ tag?

**Comment by alexr00** [comment]
@GustavoASC we take all API finalizations to an API discussion with the team first. Once we've approved the API, then I'll move the API over from vscode.proposed.d.ts to vscode.d.ts.

**Comment by GustavoASC** [comment]
@alexr00 Thank you very much for finalizing this API! :heart:
Will _title_ parameter of SaveDialogOptions be moved from proposed to vscode.d.ts too?

**Comment by jrieken** [comment]
> Will title parameter of SaveDialogOptions be moved from proposed to vscode.d.ts too?

👍 for that

**Comment by alexr00** [comment]
Yes, thanks for catching!
