### ISSUE TITLE
API: Finalize env.createAppUri

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82884]
We should move `env.createAppUri` out of proposed API to stable.

**Comment by bpasero** [comment]
Better idea that does not require new API in: https://github.com/microsoft/vscode/pull/83045

**Comment by 928PJY** [comment]
Hey @bpasero, will this change be included in the next stable release version?

**Comment by bpasero** [comment]
@928PJY yes

To clarify: `vscode.env.createAppUri` will not exist in that form, but rather `vscode.env.asExternalUri` will support URIs created with `vscode.env.uriScheme`.
