### ISSUE TITLE
VS does not intellisense for HTML

### ISSUE THREAD

**Issue by MahmoudMabrok** [microsoft/vscode#82889]
when i create a html file
and want to write for example <html> **tag** it does not auto complete or intelligent text.
and i also added extensions but also did not work.

**Comment by MahmoudMabrok** [comment]
#82774 lack of information for issue.

**Comment by krnik** [comment]
Please provide more information on you issue (as the label on your previus issue suggests).
Ideally you'd want to provide steps to reproduce with build version + screen capture with screencast option turned on i VSCode.

Otherwise this issue will face the same fate as the previous one.

**Comment by MahmoudMabrok** [comment]
For steps
- create a new file with extension .html 
- try to write html tags but it does not autocomplete. 

@krnik recently
 I installed the latest version and problem solved
