### ISSUE TITLE
Will not open Chrome When i run in Live Server

### ISSUE THREAD

**Issue by zocom-kim-vagi** [microsoft/vscode#82886]
Issue Type: <b>Bug</b>

Will not open Chrome When i run in Live Server,
It started when I tryed to run debug NodeJs

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-devtools-for-chrome|cod|0.0.5
vscode-eslint|dba|1.9.1
beautify|Hoo|1.5.0
open-html-in-browser|pea|1.3.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details>

**Comment by SupinePandora43** [comment]
can you attach debug configuration?

**Comment by zocom-kim-vagi** [comment]
I cant find a "debug configuration" in the list to add in launch.json. It looks like this ...
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [        
        
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceFolder}"
        },

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:5500",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

**Comment by zocom-kim-vagi** [comment]
Get this error when I run debug - Attach to Chrome
![image](https://user-images.githubusercontent.com/54845585/67158454-8107c900-f338-11e9-9a39-f59846eb44ce.png)

**Comment by SupinePandora43** [comment]
```
	{
		"name": "(Electron) Attach Renderer",
		"type": "chrome",
		"request": "attach",
		"port": 9223,
		"timeout": 30000
	},
	{
		"type": "chrome",
		"request": "launch",
		"name": "(React) Launch",
		"runtimeExecutable": "F:/Program Files/Google/Chrome/Application/chrome.exe",
		"url": "http://localhost:3000",
		"timeout": 60000,
		"userDataDir": "C:/samples/electron-app/.chrome",
		"runtimeArgs": [
			"--disable-session-crashed-bubble",
			"--disable-infobars"
		]
	}
```

###### ***as an example***

**Comment by roblourens** [comment]
Please give more details about exactly what you are doing. Are you saying that you expect Live Server to launch Chrome? Or if you want the launch config to launch Chrome, you will have to run the "launch" type config.

**Comment by LukeWolfGames** [comment]
I actively use VS code and have a live server running whilst doing game development course work.

If VS code has been open for some time, the extension for live server seems to become unresponsive.
In order to work around this, VS code needs to be closed and opened again.

As I was writing this; the live server had opened but only after like 10-20 minutes after I clicked "Run Live Server".

I have only experienced this issue recently. I cannot pin point the exact version it started on since VS code has had a few updates recently but I would say the time frame is accurate with the start of this bug report.

![](https://i.imgur.com/jRH932M.png)

Please let me know if you need additional information to help resolve this issue.

**Comment by roblourens** [comment]
@LukeWolfGames check for some process using lots of CPU and slowing down your machine. Possibly file an issue on Live Server. I am closing this, no response from OP.
