### ISSUE TITLE
每次启动springboot程序CPU占用非常高

### ISSUE THREAD

**Issue by 395053994** [microsoft/vscode#82880]
- VSCode Version:1.39.2
- OS Version:win10 x64 18362
- jdk 1.8
![CPU占用很高](https://user-images.githubusercontent.com/27546390/67136007-f26d4c00-f252-11e9-9b76-34c3a5f079d8.png)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No
发项是该扩展 Spring Boot Dashboard 的问题

**Comment by roblourens** [comment]
Please file this on the repo for the Java extension (or the Spring Boot Dashboard extension)
