### ISSUE TITLE
Slow terminal

### ISSUE THREAD

**Issue by ChavanSamp** [microsoft/vscode#82885]
Issue Type: <b>Performance Issue</b>

I have a system where I need to start an .exe file, it takes 61 seconds to boot into the terminal, whereas in windows cmd it only takes 13 seconds.

Test Terminal VSCode: http://prntscr.com/ple19s
Test Windows Cmd: http://prntscr.com/ple1m0

Sometimes it arrives almost 200 seconds in the terminal VSCode.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ChavanSamp** [comment]
> Issue Type: Performance Issue
> 
> I have a system where I need to start an .exe file, it takes 61 seconds to boot into the terminal, whereas in windows cmd it only takes 12 seconds.
>Test Terminal VSCode: http://prntscr.com/ple19s
> 
> VS Code version: Code 1.39.2 ([6ab5985](https://github.com/microsoft/vscode/commit/6ab598523be7a800d7f3eb4d92d7ab9a66069390), 2019-10-15T15:35:18.241Z)
> OS version: Windows_NT x64 10.0.18999
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)
> GPU Status	2d_canvas: enabled
> flash_3d: enabled
> flash_stage3d: enabled
> flash_stage3d_baseline: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> native_gpu_memory_buffers: disabled_software
> oop_rasterization: unavailable_off
> protected_video_decode: unavailable_off
> rasterization: unavailable_off
> skia_deferred_display_list: disabled_off
> skia_renderer: disabled_off
> surface_synchronization: enabled_on
> video_decode: enabled
> viz_display_compositor: disabled_off
> webgl: enabled
> webgl2: enabled
> Load (avg)	undefined
> Memory (System)	5.95GB (1.98GB free)
> Process Argv	
> Screen Reader	no
> VM	0%

**Comment by Tyriar** [comment]
Those are milliseconds, not seconds. Changing terminal.integrated.rendererType might help, but the additional slowness may be attributed to additional overhead of going via node or https://github.com/microsoft/vscode/issues/74620

**Comment by ChavanSamp** [comment]
@Tyriar Excuse me, it really is milliseconds. But it's still a perfomace problem, I'll take a look at what you mentioned.
