### ISSUE TITLE
same advice about switch case 

### ISSUE THREAD

**Issue by unkownY** [microsoft/vscode#82882]
under switch 

```node
switch(conditions){
    case 'a':
        ....
        break;
    case 'b':
        ....
        break;
}
```
now the vscode just can fold `switch` line
but  the `case` line is which i want to fold.

**Comment by aeschli** [comment]
What language? TypeScript?

**Comment by unkownY** [comment]
I use the Node.js

**Comment by aeschli** [comment]
JavaScript/TypeScript then.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/23380
