### ISSUE TITLE
Portable Mode, storing files in userprofile

### ISSUE THREAD

**Issue by versamodule** [microsoft/vscode#82893]
- VSCode Version: 1.39.2
- OS Version:  10.0.18362

Steps to Reproduce:

1. unzip VSC Portable to a new folder on C drive. Create the data folder in the same, and inside this create a tmp folder. 
2. install an extension. Exit and reload VSCP. 

I have 2 portable portable installs on my PC. I have installed the platformio extension for one, and the PyMakr extension for the other, both are storing information in %USERPROFILE%\AppData\Roaming\Code\User. 

Wiping this %USERPROFILE%\AppData\Roaming\Code folder and reloading either VSCP.exe causes both extensions to think its a new install again. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
You should file this issue to both extensions instead.

**Comment by versamodule** [comment]
If an extensions is installed through VSCP, it should be contained in the portable folder location.

**Comment by joaomoreno** [comment]
You might want to follow https://github.com/microsoft/vscode/issues/52116
