### ISSUE TITLE
Ignore definition files when using "Peek References"

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#82899]
Issue Type: <b>Bug</b>

When using "Peek References" (or presumably, "Find References") on an imported package, like Lodash, references found in `node_modules/@types/lodash` are also included. Instead, only references in my own code should be included.

This only happens when using `import` (in either JS or TS), and not when using `require`.

This is in a TypeScript project, with the following `tsconfig.json`:

```typescript
{
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "module": "CommonJS",
    "outDir": "./dist/",
    "resolveJsonModule": true,
    "rootDir": "./src/",
    "sourceMap": true,
    "strict": true,
    "target": "ES2020",
    "typeRoots": ["./node_modules/@types", "./typings"]
  },
  "include": ["./src/"],
  "exclude": [
    "**/build/**",
    "**/coverage/**",
    "**/dist/**",
    "**/node_modules/**"
  ]
}
```

Global VS Code settings includes:

```json
{
  "files.exclude": {
    "**/node_modules": true
  }
}
```

I've also attached a screenshot below (the screenshot was taken in the file `src/Calendar.ts`), to show all the extraneous references from the `node_modules` folder:

![Peek References](https://user-images.githubusercontent.com/343940/67149449-63275f00-f279-11e9-9d57-2d10cab83674.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for this
