### ISSUE TITLE
DefaultSettings.json doesn't open even if option is checked

### ISSUE THREAD

**Issue by sukiletxe** [microsoft/vscode#82895]
Issue Type: <b>Bug</b>

1. Open settings, having previously checked `workbench.settings.openDefaultSettings`

Expected: Default settings should open.

Actual: tbh,  it did that just once, then stopped doing it. The only change from then was changing `files.hotExit` to `off`.

Below is my `settings.json` (disregard the `workbench.settings.editor`, as it is `ui` by default and I poked with it just to see if it made any difference before resetting):

```
{
    "workbench.startupEditor": "newUntitledFile",
    "[markdown]": {},
    "editor.accessibilitySupport": "on",
    "window.zoomLevel": 1,
    "[vb]": {},
    "diffEditor.renderSideBySide": false,
    "workbench.settings.openDefaultSettings": true,
    "workbench.settings.openDefaultKeybindings": true,
    "files.hotExit": "off",
    "workbench.settings.editor": "ui"
}
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz (2 x 2926)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.97GB (0.78GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|yes|
|VM|0%|
</details>Extensions disabled

**Comment by roblourens** [comment]
To be clear, this only has an effect when opening the JSON version of the settings. You can do that through the command or the button in the GUI settings editor. Is that what you are trying to do?

**Comment by sukiletxe** [comment]
No, I wasn't doing that. Now I've switched to json editor for settings and it works. Closing. Thank you very much.
