### ISSUE TITLE
Alert dialog not keyboard accessible

### ISSUE THREAD

**Issue by spmealin** [microsoft/vscode#82898]
Description:

I have my terminal launch settings (e.g. “terminal.integrated.shellArgs.windows”) customized in the user settings.json.  For a particular project, I needed different launch settings, so I customized the same settings in a . code-workspace file to overwrite the user settings default.  When I launch a terminal, an alert dialog pops up with the question “Do you allow this workspace to modify your terminal shell?” and two buttons which state allow and deny.  From my experimentation, I am unable to set focus to this dialog to respond.

I am a screen reader user, and the alert dialog is read out by NVDA when it shows, but I can not find it in the tab order nor can I find the “allow” button using NVDA’s object navigation.  This happens regardless of extension status.

VSCode version: 1.39.2

Steps to reproduce:
1. In the user settings file, customize “terminal.integrated.shellArgs.windows”
2. In a workspace settings file, also set “terminal.integrated.shellArgs.windows”
3. Launch a terminal

Expected result: The alert dialog opens and focus is set to either the allow or deny buttons

Actual result: The dialog opens and focus remains on the console.  The alert is not to be found within the tab order.

**Comment by bpasero** [comment]
Possibly a candidate to turn into a modal dialog. We cannot change notifications to take focus, that would be quite horrible with the amount of notifications that popup.

**Comment by Tyriar** [comment]
@bpasero both the status bar and notifications are not in the tab order or accessible via keyboard, isn't that the real issue here?

**Comment by bpasero** [comment]
@Tyriar we explicitly take out status bar entries from `tabindex` because we felt it would generate too much tab stops to be any useful. 

As for notifications accessibility, I have to disagree. There is tons of commands to interact with them:

![image](https://user-images.githubusercontent.com/900690/67228669-12ab2f80-f43a-11e9-8a3b-8cfc960d00e8.png)

We do not have a default keybinding associated though, so arguable we could add one.

**Comment by bpasero** [comment]
Related / duplicate: https://github.com/microsoft/vscode/issues/81786

**Comment by spmealin** [comment]
I can see how stealing focus for every notification could become annoying for the user.  Since this particular popup seems to be pretty important (i.e. a complete showstopper for this workflow), I would argue that a way to deal with it should be a bit more discoverable than an unassigned hotkey.

But thanks for the tip on the “Notifications: Show Notifications” action, I’ve assigned that to a hotkey so I can deal with this and other notifications.

Just throwing out half-baked ideas, maybe on the accessibility page (https://code.visualstudio.com/docs/editor/accessibility), we could add a list of useful tips like this one for keyboard only access?

**Comment by Tyriar** [comment]
`Notifications: Show Notifications` does seem to cover it, maybe a doc update like @spmealin suggests? Unassigning myself since I don't think we should have a modal for this.
