### ISSUE TITLE
Renaming "Revert file" to "Reload from disk"

### ISSUE THREAD

**Issue by Yivan** [microsoft/vscode#82894]
Hello,

Same as https://github.com/Microsoft/vscode/issues/3498 il was asking myself the purpose of this.
Will it revert to the last commit, to the disk version, depending local history, etc... I was suspicious about it.

After testing i undestanded that it reload the file from the disk.
I think it shoud clearly be renamed "Reload from disk", it is al lot more explicit and not ambiguous in a git context.

Thanks.

**Comment by Yivan** [comment]
(by the way, from a user perspective, i found this menu option because i wanted to reload my file from the disk, but i didn't know how to do it... it take me some times to get it as "revert file" was not very clear)

**Comment by isidorn** [comment]
Thanks for the feedback. However we would not rename the action now since users got used to it. ANd I htink revert file is not such a bad name now.
Thus closing as designed. Thanks for understanding
