### ISSUE TITLE
Workspace directory selection and configurations for hiding directories

### ISSUE THREAD

**Issue by stefan-toubia** [microsoft/vscode#82897]
I work on a monorepo setup, and because of this my main workspace root has a good number of directories.  I rarely need to be working in more than a few at a time, so it would be great to have the ability to hide specific workspace directories directly from the explorer.

I know this is sort of the idea behind a workspace, and I've tried making this work for my needs.  I can go make a couple workspaces that have the specific directories I need for a given workflow.  There are two issues here, one is that I will occasionally need quick access to a file from anywhere in my repo, and similarly I would like to retain full workspace search capabilities across the whole repo.

Other IDEs have this concept, take Jetbrain's DataGrip as an example.  In the DB explorer you can select specific DBs that are shown at a given time with an easy to use select menu.
![Screen Shot 2019-10-19 at 10 30 06 AM](https://user-images.githubusercontent.com/4265922/67149049-7f1c0800-f25b-11e9-9b3c-cbb8ed6f6b80.png)
This would be a great addition to Visual Studio Code.
What would be even better cherry on top would be saved configurations for your selections, so you can easily hop between preset selections, but this is much less important.

**Comment by isidorn** [comment]
@stefan-toubia thanks for the feature request. However I think this can be achieved via `"files.exclude"` setting. And an extension can potentially add a context menu command that ouwld modify this setting underaneath.
