### ISSUE TITLE
Extensions: styling is bad for links in markdown preview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8290]
![image](https://cloud.githubusercontent.com/assets/900690/16411515/b80c56a2-3d27-11e6-8e8c-c0856603cc9c.png)

We could maybe revive the CSS we used for the built in markdown preview?

**Comment by isidorn** [comment]
Dup of #8258
Yes - I can look into those css styles - thanks!

**Comment by bpasero** [comment]
@isidorn you can find them here: https://github.com/Microsoft/vscode/blob/1.2.1/src/vs/languages/markdown/common/markdown.css

**Comment by isidorn** [comment]
@bpasero awesome - thanks!
