### ISSUE TITLE
Menu Bar Compact option broken on Kubuntu 18.04

### ISSUE THREAD

**Issue by Kuhluh** [microsoft/vscode#82907]
VSCode Version: snap 1.39.2
OS Version: Kubuntu 18.04

Steps to Reproduce:
1. switch menu bar visibility to "compact"

Does this issue occur when all extensions are disabled?: Yes

![Screenshot_20191020_030140](https://user-images.githubusercontent.com/56777478/67153353-031bd180-f2e8-11e9-9721-898b49942f52.png)

As seen in the screenshot, if you switch the menu bar visibility to "compact", you have 2 on at least Kubuntu 18.04 because the old one doesn't go away.
It doesn't matter if I build it myself or use the official snap package (or the unofficial flatpaks).

**Comment by Kuhluh** [comment]
PS: before anyone asks, I searched about this for about 5 hours now on the Internet and found nothing. I have seen no screenshot

**Comment by Kuhluh** [comment]
About the closed/reopen, I misclicked, sorry.

**Comment by sbatten** [comment]
@Kuhluh the compact option is not compatible with the native titlebar (default on linux) as noted in the setting description. however, it is a bug that the compact menu shows up with that setting as it should be ignored.

**Comment by Kuhluh** [comment]
Well, good to know, and thanks for the information.

**Comment by sbatten** [comment]
re-opening to fix the second part mentioned above
