### ISSUE TITLE
Cannot access the Marketplace on Catalina

### ISSUE THREAD

**Issue by Overload119** [microsoft/vscode#82908]
Issue Type: <b>Bug</b>

"We cannot connect..." - error shown.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|-psn_0_1720740|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Overload119** [comment]
- There are no proxy settings.
- I've changed DNS to 1.1.1.1 which also did not help.

**Comment by Overload119** [comment]
I posted some the console errors here. In short, the message I see is `Failed to load resource: net::ERR_NETWORK_ACCESS_DENIED`.

https://github.com/microsoft/vscode/issues/81115

I've also tried nuking my settings in both places.
```
`~/.vscode`
`/Users/amirsharif/Library/Application Support/Code`
```

I've also tried using VS Code Insiders (which has the same problem).

I've also tried modifying my `/etc/hosts/` file (it had some entries that I removed).

**Comment by Overload119** [comment]
Just tried connecting to a different WiFi network. Still no luck. Same error.

**Comment by Overload119** [comment]
Some more things I've been trying and I scour the surprising number of issues related to this.

- I'm able to access this [image](https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default) in Chrome. 
- I've used TunnelBear to use a Proxy and VSCode shows the same error.

Running the command: `Developer: Show Logs`

`[2019-10-20 12:46:25.686] [renderer1] [error] net::ERR_NETWORK_ACCESS_DENIED: Error: net::ERR_NETWORK_ACCESS_DENIED`

**Comment by joaomoreno** [comment]
Is there anything special about your network?

**Comment by Overload119** [comment]
Not that I'm aware of. I have no other issues, and in fact I've tried sending the exact same request in `curl` and I'm able to get a response just fine.

Are there any flags I can turn on? It looks like --disable-ssl-certificates was recently removed so I was unable to try that step.

This is on my personal laptop, at home, connected via WiFi. I don't use a proxy or have any other special issues.

Coincidentally, I upgraded to Catalina yesterday and the issue persisted even after that.

**Comment by Overload119** [comment]
I used https://radiosilenceapp.com/ to check out the connections.
Strangely, it started working although I didn't do anything specific with that app.

**Comment by joaomoreno** [comment]
It just works now?

**Comment by Overload119** [comment]
Yes. I'm not longer blocked. 🤷

**Comment by steal3rd** [comment]
For me, the issue was related to the following files (Windows).

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup
```

I quit Code, and renamed them.

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb-disabled
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup-disabled
```

Code recreated the files, and I was able to search the extensions again.

**Comment by joaomoreno** [comment]
cc @bpasero
