### ISSUE TITLE
Toggling find features from command palette doesn't work

### ISSUE THREAD

**Issue by Madd0g** [microsoft/vscode#82901]
- VSCode Version: 1.39.2
- OS Version: OSX 10.14.6 (Darwin x64 18.7.0)

Steps to Reproduce:

1. Open search box with cmd+f
2. Use keyboard shortcuts to try to toggle "find using regex" and "find using whole word" - the buttons toggle correctly
3. Try toggling from the palette - it doesn't work

**Comment by rebornix** [comment]
We didn't expose those commands for the Find Widget in the editor, the commands you see are from Terminal. @Tyriar we may want to add Terminal prefixes for them.

**Comment by Madd0g** [comment]
Oh both these commands are meant for the terminal?

![image](https://user-images.githubusercontent.com/1171003/67244897-9b60a600-f40f-11e9-9c8b-0c39b07fc30b.png)

**Comment by Tyriar** [comment]
Apparently there are 2 terminal commands, one with prefix and one without 🤷‍♂

**Comment by sohailrajdev97** [comment]
@Tyriar There are two entries defined in `terminal.contribution.ts` for toggling regex find. I tried removing one of those and the extra command did not show up in the command palette. I'm not sure whether this is the correct way for doing this. Will be happy to raise a PR for the same.

Refer: 

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L518

```
actionRegistry.registerWorkbenchAction(new SyncActionDescriptor(ToggleRegexCommand, ToggleRegexCommand.ID, ToggleRegexCommand.LABEL, {
	primary: KeyMod.Alt | KeyCode.KEY_R,
	mac: { primary: KeyMod.CtrlCmd | KeyMod.Alt | KeyCode.KEY_R }
}, KEYBINDING_CONTEXT_TERMINAL_FIND_WIDGET_FOCUSED), 'Terminal: Toggle find using regex');
```

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L522

```
actionRegistry.registerWorkbenchAction(new SyncActionDescriptor(ToggleRegexCommand, ToggleRegexCommand.ID_TERMINAL_FOCUS, ToggleRegexCommand.LABEL, {
	primary: KeyMod.Alt | KeyCode.KEY_R,
	mac: { primary: KeyMod.CtrlCmd | KeyMod.Alt | KeyCode.KEY_R }
}, KEYBINDING_CONTEXT_TERMINAL_FOCUS), 'Terminal: Toggle find using regex', category);
```

**Comment by Tyriar** [comment]
@sohailrajdev97 thanks for looking into it and the offer, I put a PR together as it needed some experimentation to figure out the right fix https://github.com/microsoft/vscode/pull/83091
