### ISSUE TITLE
Intellisense says Jest is not recognized when code compiles from command line

### ISSUE THREAD

**Issue by andkvo** [microsoft/vscode#82902]
Issue Type: <b>Bug</b>

This really sucks. VSCode is giving red lines for TS code (jest function like describe and expect) THAT COMPILES AND WORKS CORRECTLY IN THE COMMAND LINE. I have tried absolutely everything in tsconfig, jsconfig, npm i, npm uninstall, tsdk settings, etc AND NOTHING HELPS. why can't it tell me what tsc is doing so i can fix this?

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (3.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
Can you show an example of your code?
