### ISSUE TITLE
Nodejs BreakpointLocations Broken after upgrade

### ISSUE THREAD

**Issue by posdroid** [microsoft/vscode#82905]
Issue Type: <b>Bug</b>

Add a break point to the application by clicking in the margin.
Hit F5 to build and run the Nodejs App.
Run the App
Launch Config.

"configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/src/index.ts",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "outputCapture": "std",
            "env": {"CONFIGFILE" : "dev"}
        }
    ]

TS Config
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "target": "es5",
        "outDir": "out",
        "lib": ["es2018", "dom"],
        "allowJs": true,
        "moduleResolution": "node"
    },
    "include": [
        "./src/**/*.ts"
    ],
    "exclude": [
        "**/node_modules/**/*",
        "node_modules",
    ]
}

Error processing "breakpointLocations": TypeError: Cannot read property 'line' of undefined
    at breakpoints.forEach (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:156:55)
    at Array.forEach (<anonymous>)
    at EagerSourceMapTransformer.setBreakpointsResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:147:29)
    at NodeBreakpoints.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:309:69)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:7:58)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.13GB free)|
|Process Argv|C:\code\PosDroid\WaiterServer|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
prettier-vscode|esb|2.3.0
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0
debugger-for-chrome|msj|4.12.0
change-case|wma|1.0.0

</details>

**Comment by v-andrew** [comment]
I have the same issue.
Trying to debug  https://github.com/v-andrew/ts-template

I found that debugging nodejs application with `(async ()=>{}) construction produces mentioned error

Try to debug:

```JS
(async () => {
  console.log('Test')
})()
```

**Comment by posdroid** [comment]
The problem appears transient and has cleared up after another couple of restarted and rebuilds.

It was putting little red breakpoint dots in amongst the code, which seems to have stopped now as well.

**Comment by posdroid** [comment]
@v-andrew Yea debugging that code sems to mess up the code around it. for instance I jsut stuck it into the botting of my app and.....


logger.info('booting...')
(async () => {
	console.log('Test');
})()

Debugger attached.
c:\code\PosDroid\WaiterServer\out\index.js:43
logger_1.logger.info('booting...')(function () { return __awaiter(_this, void 0, void 0, function () {
                                  ^

TypeError: logger_1.logger.info(...) is not a function
    at Object.<anonymous> (c:\code\PosDroid\WaiterServer\out\index.js:43:35)

Where are theres nothing wrong with logger.info('booting...') it's been running for ages, could use a semi I suppose.
