### ISSUE TITLE
Current MacOS Download Zip broken

### ISSUE THREAD

**Issue by ntatko** [microsoft/vscode#82900]
I'm not sure this is the right place to bring this up, as technically this is not an issue with the program, but rather the current zip download for MacOS. Anyway, here are my steps to reproduce:

* Navigate to [the download page](https://code.visualstudio.com/download)

* Click on the download for mac option, for versions `10.10+`
<img width="304" alt="Screen Shot 2019-10-19 at 14 11 59" src="https://user-images.githubusercontent.com/37306038/67150249-d41b4680-f27a-11e9-93f4-737a0af207b1.png">
You should see the download zip in your downloads bar
<img width="248" alt="Screen Shot 2019-10-19 at 14 12 05" src="https://user-images.githubusercontent.com/37306038/67150258-f90fb980-f27a-11e9-9f41-6613e6e249aa.png">

* Click on that download once complete

* MacOS will automatically attempt to unzip the files, briefly showing a status bar, then returning this error
<img width="436" alt="Screen Shot 2019-10-19 at 14 12 12" src="https://user-images.githubusercontent.com/37306038/67150278-20ff1d00-f27b-11e9-974c-5dc450568832.png">

* Unzipping with command line returns a more descriptive error
<img width="546" alt="Screen Shot 2019-10-19 at 14 12 47" src="https://user-images.githubusercontent.com/37306038/67150281-34aa8380-f27b-11e9-9de7-db2f6abc90cc.png">

I was able to download VSCode by going to the release archive, but I thought this should be documented somewhere, as I didn't see any reports of this issue. I am running MacOS Catilina on a Macbook Pro 2015.

**Comment by roblourens** [comment]
Weird, it must be related to the other catalina issues somehow although it doesn't look like them https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Amacos-catalina+

The zip looks valid for me (on non-catalina)

**Comment by joaomoreno** [comment]
@ntatko What is the SHA1 checksum of that file? What is its full byte size?
