### ISSUE TITLE
VSCode Window not showing despite process running (C#, Unity)

### ISSUE THREAD

**Issue by Ivanca** [microsoft/vscode#82915]
Issue Type: <b>Bug</b>

Sometimes trying to open a C# file that belongs to a project does nothing, when I open the "process explorer" I can see that the process exists but is not being rendered (the window is nowhere to be found, doesn't appear on mouse over taskbar or alt-tab, or anywhere). In the attached screenshot you can see that the "process explorer" is claiming that 2 windows exist but is only showing one at all.

The only workaround I found is to force-kill the (hidden) window process from the "process explorer" and then reopening the project.

![windowInvisible](https://user-images.githubusercontent.com/907138/67154910-4f0b4e00-f2c9-11e9-80d3-a7161b0e5738.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (7.68GB free)|
|Process Argv|D:/Dropbox/Laserlogic -g D:\Dropbox\Laserlogic\Assets\ErbGameArt\3D Lasers Pack\Demo scene lasers\EGA_Laser.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.41019
remote-wsl|ms-|0.39.9
csharp|ms-|1.21.5
sublime-keybindings|ms-|4.0.3
vetur|oct|0.22.4

</details>

**Comment by jbracer19** [comment]
eta 10 minutes to terminal

On Oct 19, 2019, at 11:42 PM, Ivan <notifications@github.com> wrote:

﻿

Issue Type: Bug

Sometimes trying to open a C# file that belongs to a (Unity) project does nothing at all, after opening the "process explorer" I can confirm that the proccess exist and is running but is hidden in some way (the window is nowhere to be found, doesn't appear on mouse over taskbar or alt-tab, or anywhere). In the attached screenshot you can see that the process explorer is claiming that 2 windows exist but is only showing one at all.

The only workaround I found is to force-kill the (hidden) window process from the "process explorer" and then opening the project, but is tiresome so please fix this bug.

[windowInvisible]<https://user-images.githubusercontent.com/907138/67154910-4f0b4e00-f2c9-11e9-80d3-a7161b0e5738.png>

VS Code version: Code 1.39.2 (6ab5985<https://github.com/microsoft/vscode/commit/6ab598523be7a800d7f3eb4d92d7ab9a66069390>, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

System Info
Item    Value
CPUs    Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3499)
GPU Status      2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)      undefined
Memory (System) 11.95GB (7.68GB free)
Process Argv    D:/Dropbox/Laserlogic -g D:\Dropbox\Laserlogic\Assets\ErbGameArt\3D Lasers Pack\Demo scene lasers\EGA_Laser.cs:1:0
Screen Reader   no
VM      0%
Extensions (5)
Extension       Author (truncated)      Version
python  ms-     2019.10.41019
remote-wsl      ms-     0.39.9
csharp  ms-     1.21.5
sublime-keybindings     ms-     4.0.3
vetur   oct     0.22.4

**Comment by roblourens** [comment]
Please file this on the repo for the C# extension: https://github.com/OmniSharp/omnisharp-vscode
