### ISSUE TITLE
Cannot start Jupyter server

### ISSUE THREAD

**Issue by dg1223** [microsoft/vscode#82919]
Issue Type: <b>Bug</b>

OS: Win10 64 bit
Exising Python: 2.7.13 (installed along with Canopy)
Installed Python 3.7.5.64 after installing VS code
Tried to open a ipython notebook by selecting a local folder

The issue is not fixed for sure although I see so many identical issues labeled 'fixed' on GitHub

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
nbpreviewer|jit|1.2.2
python|ms-|2019.10.41019

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo with more details: https://github.com/microsoft/vscode-python/issues
