### ISSUE TITLE
no such file or directory in debug

### ISSUE THREAD

**Issue by tcitr-m** [microsoft/vscode#82914]
Issue Type: <b>Feature Request</b>
Update to the version1.39.2 are also problematic。
```
demo3
|--views
| |--login.ejs
|--1.js
```
```
1.js
ejs.renderFile('views/login.ejs', {}, (err, data) => {
        if (err) {
            res.send(err.message)
        }
        res.send(data)
    })
```
Using debug or 'F5'  ```Error: ENOENT: no such file or directory, open 'views/login.ejs'```,
 no error is reported when  using ```node 1.js``` in poweshell or cmd in the terminal,

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

**Comment by byyxx128** [comment]
1. English please.
2. Your VS Code is out-of-date. Please update and try the latest version.
3. Please provide detailed steps to reproduce.
4. This is not a Feature Request...

**Comment by roblourens** [comment]
I assume you are running the program from inside the `demo3/` folder. You will have to set `cwd` in your launch config to `${workspaceFolder}/demo3` to get the same effect. Let me know if that helps.

**Comment by tcitr-m** [comment]
thanks, In the **launch.js** file , ```\\``` can be changed to```/```

**Comment by tcitr-m** [comment]
Why is the default `\\`

**Comment by roblourens** [comment]
I didn't mean change the slashes, I just meant set the `cwd`. There isn't a cache, but I'm glad it's working now!
