### ISSUE TITLE
Extensions: markdown preview links cannot be clicked

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8291]
On Windows 7 I click on a link in the preview but the link does not open. Since it works when using markdown preview I suspect this is an issue with the extension preview.

**Comment by isidorn** [comment]
Does not sound cruical -> July, joao
Let me know if you disagree

**Comment by bpasero** [comment]
@isidorn might be as easy as producing links with target="blank". I wonder if that would fix it

**Comment by joaomoreno** [comment]
@bpasero Can we debug this in your Win7 VM? I don't have one currently.

**Comment by isidorn** [comment]
@joaomoreno I have a win7 VM I can investigate. Also notice that this was filed when markdown.css was not being packaged - not sure if related at all

**Comment by bpasero** [comment]
I cannot reproduce anymore.
