### ISSUE TITLE
Integrated terminal can not support bold character.

### ISSUE THREAD

**Issue by Suyun514** [microsoft/vscode#82918]
- VSCode Version: 1.40.0-insider
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install Cygwin.
2. Set the default shell as `bash.exe`(for Cygwin) in Viaual Studio Code, and the args as `--login`.
3. Run `ls --color=auto`.
4. Normally, the executable files and the folders' names are displayed in bold, but they are not in Viaual Studio Code. (You can check the bold character in MinTTY with the option `Show bold ad font`.)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by Suyun514** [comment]
It seems that ConPTY also have the problem.
I made a new issue at [microsoft/terminal](https://github.com/microsoft/terminal).
[#3297](https://github.com/microsoft/terminal/issues/3297)
