### ISSUE TITLE
auto import not working

### ISSUE THREAD

**Issue by faycito** [microsoft/vscode#82913]
I ever use the auto-import tool from vs code but, after the update in September, it can't work. 

VS code version: 1.39.2

**Comment by jbracer19** [comment]
sofa king we todd did.


On Oct 19, 2019, at 9:30 PM, vscodebot[bot] <notifications@github.com> wrote:

﻿

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:

  *   Extension Download not Work (#81186)<https://www.github.com/microsoft/vscode/issues/81186>
  *   issue with include in c++ (#82371)<https://www.github.com/microsoft/vscode/issues/82371>
  *   Debug don't view any value (#82562)<https://www.github.com/microsoft/vscode/issues/82562>
  *   Cursor move to end of file (#81607)<https://www.github.com/microsoft/vscode/issues/81607>
  *   Visual bug side menu (#81961)<https://www.github.com/microsoft/vscode/issues/81961>

**Comment by iamdamilola** [comment]
@faycito Concerning the issue you mentioned. Do you mean `auto-import` when you change a folder's directory or a file directory ? If so a workaround would  be to hit `command + s` on Mac or `ctrl +s` on a windows. That worked for me.

**Comment by roblourens** [comment]
Please share the file where this doesn't work and give some more details

**Comment by pedronasser** [comment]
Definitely something is wrong on importing.

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster
