### ISSUE TITLE
Please make the variable pop up window resizable in the debugging mode

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#82916]
- VSCode Version: 1.39.2 zip 64 bit installer
- OS Version: Windows 10

When debugging a TypeScript project, hover mouse on a variable, it pops up a window showing the values of the variable and its properties, as **`this`** shown in the screenshot below. This window is usually too small and isn't resizable particularly the horizontal dimension, so have to keep scrolling from the left end to the right end, back and forth, to check those values, which isn't ideal for variables having a lot properties and their values are long. So if make the window resizable, it will be much more convenient!
![image](https://user-images.githubusercontent.com/19678455/67155249-dc04e480-f367-11e9-816f-72717d67673e.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/67620
And another issue
