### ISSUE TITLE
<windows.h> bug when using TEXT macro

### ISSUE THREAD

**Issue by JaiSh12345** [microsoft/vscode#82923]
>- VSCode Version: 1.39
>- OS Version: Intel(R) Core (TM) i5-7300HQ, 64 bit Windows 10 and x64 processer.

## Steps to Reproduce:

>1. Create a C++ project.  Type in 
```c++
#include <windows.h>  
int main(){  
    const char * c = "Hello";  
    TEXT("Hello");      // No error.  
    TEXT(c);            // 5 : Error: Lc not defined  
    return 0;  
}  
```
>2. The Intellisense highlights line 5 and says `identifier "Lc" is undefined`.

## Does this issue occur when all extensions are disabled? _Yes_

See here:
![vscode_bug_#1](https://user-images.githubusercontent.com/43960624/67157789-d949c580-f34e-11e9-8a45-7a78779fd0ac.png)

__Note:__ `TEXT` expands to `__TEXT(q) L##q`, which is causing the issue.   
Comments?

**Comment by roblourens** [comment]
Please file this on the repo for the C++ extension: https://github.com/microsoft/vscode-cpptools
