### ISSUE TITLE
eprecationWarning: Buffer() is deprecated and git installation not found

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [microsoft/vscode#82920]
Issue Type: <b>Bug</b>

Console output

[Extension Host] activating extension
console.ts:137 [Extension Host] starting language server
console.ts:137 [Extension Host] (node:10044) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
console.ts:137 [Extension Host] runCommand platformio Array(1) Object
console.ts:137 [Extension Host] Found PIO Core 4.0.3
console.ts:137 [Extension Host] runCommand platformio Array(8) Object
console.ts:137 [Extension Host] runCommand platformio Array(8) Object
console.ts:137 [Extension Host] runCommand platformio Array(7) Object
console.ts:137 [Extension Host] runCommand C:\Users\MuhammadQaisaraAli\.platformio\penv\Scripts\python.exe Array(2) Object
console.ts:137 [Extension Host] runCommand C:\Users\MuhammadQaisaraAli\.platformio\penv\Scripts\python.exe Array(2) Object
console.ts:137 [Extension Host] runCommand C:\Users\MuhammadQaisaraAli\.platformio\penv\Scripts\python.exe (2) ["-c", "import os;from platformio.project import helpers;l…oin(libdeps_dir, d)));print(":".join(watch_dirs))"] {spawnOptions: {…}}

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.58GB (3.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.26.0
platformio-ide|pla|1.9.2

</details>

![bug](https://user-images.githubusercontent.com/45729347/67156466-4c940d00-f338-11e9-8335-35cd55492f1e.PNG)

**Comment by roblourens** [comment]
You can ignore the deprecation warning. If there is a problem with git not working, please give more details.
