### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by SteveChinburg** [microsoft/vscode#82927]
We have written the needed
Issue Type: <b>Bug</b>

after I got a up date from Micosoft the terminal , before was on the same screen now a differant screen 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
npm-intellisense|chr|1.3.0
gitlens|eam|10.1.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
cordova-dev-essentials|jew|0.0.1
Angular2|joh|8.1.1
cortex-debug|mar|0.3.3
mssql|ms-|1.7.0
team|ms-|1.149.2
cordova-tools|msj|1.9.0
debugger-for-chrome|msj|4.12.0
vscode-react-native|msj|0.12.1
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
JavaScriptSnippets|xab|1.7.2

</details>
 data into your clipboard because it was too large to send. Please paste.

**Comment by roblourens** [comment]
Need more details

**Comment by SteveChinburg** [comment]
The Vsc terminal doesn’t open in VSO a second terminal opens,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
