### ISSUE TITLE
Process Picker to picky?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8292]
re #8196

* run tsc -w in a TypeScript project
* run gulp watch in the VSCode sources
* use the node-debug attach to process UI
* ⚡ I don't see the gulp watch process which I know runs on nodejs

**Comment by weinand** [comment]
@jrieken `tsc -w` works fine for me because it results in a node process that the picker can find.
But gulp seem to be a node process that disguises itself as gulp. I've enabled `gulp` for the picker.

**Comment by jrieken** [comment]
yeah, `tsc -w` I see
