### ISSUE TITLE
Cann't show menu bar after pressing "Alt".

### ISSUE THREAD

**Issue by zwuis** [microsoft/vscode#82921]
Steps to reproduce:

1. Set `"window.menuBarVisibility": "toggle"`.
2. Open Release Notes.
3. Press "Alt".
4. Menu bar isn't shown.

<details>
<summary>Other information</summary>

|||
|---|---|
|Version|1.40.0-insider (user setup)|
|Commit|5aec74ad3b55bb9463e717ec950e665288accd0f|
|Date|2019-10-18T05:36:22.378Z|
|Electron|6.0.12|
|Chrome|76.0.3809.146|
|Node.js|12.4.0|
|V8|7.6.303.31-electron.0|
|OS|Windows_NT ia32 10.0.18362|
</details>

**Comment by ArturoDent** [comment]
Funny that only happens when the "Release Notes" is the active editor.  Seems to work fine elsewhere even if an extension homepage is the active editor.  Weird.
