### ISSUE TITLE
Add tracing to the DAP protocol

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82928]
Many extensions implementing LSP support logging traces of the protocol JSON messages going around.

As far as I can tell there is no equivalent for DAP, so it's very hard to see what's going on.

I'm not sure whether this repo is the best place to ask, but can you support tracing the DAP?

**Comment by weinand** [comment]
DAP can be traced in VS Code easily by registering a `DebugAdapterTrackerFactory` via the `vscode.debug.registerDebugAdapterTrackerFactory` method.

See section "Finalized Debug Adapter Tracker API" in https://code.visualstudio.com/updates/v1_30.

Please free free to create a DAP tracing extension and make it available via the marketplace.
