### ISSUE TITLE
Error loading css styles from URLs

### ISSUE THREAD

**Issue by WyRe** [microsoft/vscode#82924]
- VSCode Version: 1.39.2
- OS Version: Arch Linux x86_64 with 5.3.7 Linux kernel

Steps to Reproduce:

1. Modify `markdown.styles` property with a [remote css](https://raw.githubusercontent.com/raycon/vscode-markdown-style/master/preview/github.css) 
2. Try the preview of your `.md` file
3. You'll get a warning. 

Does this issue occur when all extensions are disabled?: Yes/No
I need [Markdown All In One](https://github.com/yzhang-gh/vscode-markdown) to preview `.md` files but I've already reported in there, In fact I'm coming [from here](https://github.com/yzhang-gh/vscode-markdown/issues/538#issuecomment-544249064)

Thank you all.

**Comment by mjbvz** [comment]
This is not a VS Code issue. Github explicitly serves content from raw with the content-type `text/plain`. Most modern browsers will refuse to treat this as a stylesheet

If you use an https style, make sure it is served up with the correct content-type
