### ISSUE TITLE
editor-contrib: get initial selections on content change

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82929]
**Using the `ICodeEditor` interface there is no way of knowing what are the selections (and where the cursor is) after a content change.**

### Explanation:

Editor contributions (`registerEditorContribution`) and editor actions (`registerEditorAction`) receive an instance of `ICodeEditor` to work with.

Using this interface you can listen for *content changes* to a document using `onDidChangeModelContent`.
You can also listen for changes to the *cursor selections* using `onDidChangeCursorSelection`.

When the content changes, it might also cause the selections to change, but it also might not:
- Typing <kbd>a</kbd> will trigger a content change *followed by* a selections change,
- Pressing <kbd>Delete</kbd> when the cursor is before a letter will trigger a content change *without* a selections change.

*The problem is* that using the `ICodeEditor` interface there is no way of knowing what is the state of the selections after a content change.

- If the content change *does not* change the selections - we need to look at the selections at the time of the content change event.
- If the content change *does* change the cursor - we need to wait for the first selections change event after the content change event fires, and then look at the selections.

There is also no way of knowing whether a text change changed the cursor, so this is impossible.

### Use cases:

- After using **undo** not only does the content revert back, also the cursor moves back to where it was when the change was made.
   So to implement undo as a contrib you need to know where the selections are after each content change.

- The command **cursorUndo** is an editor contrib.
   It keeps track of selection changes and can undo them, and its undo stack is flushed when the content changes.
   This means that after a content change it needs to know where the selections are, to be able to restore them after the selections change and a cursor-undo is requested.
   The lack of such an API forces the current implementation to assume a content change always causes a selections change, thus causing a bug - #82535

### Footnote:

#82535 depends on this issue being fixed as previously mentioned in use-cases.

**Comment by NotWearingPants** [comment]
### Suggestions for solutions to this problem:

- Trigger a selection-change event after the content changes even when the selections don't change.

   *Why it is wrong:* The selection-change event is assumed (I think) to only be triggered when the selections *actually* change, so code listening to selection-changes will get fake selection changes.

- Adding the state of the selections after a change to the content-change event object, and never triggering a selection-change event even if the selections do change.

   *Why it is wrong*: Code listening to selection-changes will not get notified about all selection changes.

- Adding the state of the selections after a change to the content-change event object, and keeping the current behavior of triggering a selections-change only if it really changed.

   *This is what I think the solution is.*

Any other suggestions or should I implement my solution?

**Comment by NotWearingPants** [comment]
### Code pointers:

The main participants seem to be:

- `src/vs/editor/common/controller/cursor.ts`
- `src/vs/editor/common/model/textModel.ts`
- `src/vs/editor/common/model/editStack.ts`

It looks like the `Cursor` class has three methods that eventually can cause one or both of the events in question to fire:

- `trigger`
- `setStates`
- `executeEdits`

The content-change event is fired by `TextModel._emitContentChangedEvent`, and the selections-change event is fired by `Cursor._emitStateChangedIfNecessary`.

**Comment by alexandrudima** [comment]
Thank you for the analysis, I managed to create a localized fix where the cursor state is read also in the content change listener.

**Comment by NotWearingPants** [comment]
@alexandrudima as mentioned in [#82535](https://github.com/microsoft/vscode/issues/82535#issuecomment-545263987), this is still a problem and this issue should be re-opened.
