### ISSUE TITLE
Code deletes lines from files when saving Go files

### ISSUE THREAD

**Issue by btmura** [microsoft/vscode#82926]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Resume from suspend state (sleep mode).
2. Edit Go files and save.
3. Notice that Go format doesn't work.
4. Restart VS Code.
5. Add some spaces and notice Go format works.
6. Try to compile.
7. VS Code has deleted some lines later in the file. Why?
8. Try to put back the lines.
9. Save the files. VS Code stubbornly deletes the same random lines in the file. Why???
10. Keep restarting VS Code until it behaves.

Does this issue occur when all extensions are disabled?: Yes/No - I will try it.

In the last month or two, there have been many breaking changes like not being able to run tests and now VS code deleting code. Maybe there was a recent big change that is causing these issues.

**Comment by roblourens** [comment]
Please file this on the repo for the Go extension: https://github.com/microsoft/vscode-go
