### ISSUE TITLE
PATH not loading when running tasks

### ISSUE THREAD

**Issue by Alfred75** [microsoft/vscode#82925]
Issue Type: <b>Bug</b>

Just follow these steps:
https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos

Unable to run tasks. The integrated terminal is able to run the commands but the tasks do not execute. This has to do with $PATH variable not set correctly when running task.
I have added the "dummy" task below to check PATH: it returns

/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.

$PATH in integrated terminal is correct (includes path to dotnet)

my tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/app/app.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/app/app.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/app/app.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "dummy",
            "command": "echo",
            "type": "shell",
            "args": [
                "$PATH",
            ]
        }
    ]
}
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.1
Python-autopep8|him|1.0.2
openapi-lint|mer|1.0.4
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
csharp|ms-|1.21.5
azurerm-vscode-tools|msa|0.7.0
autodocstring|njp|0.3.0
vetur|oct|0.22.4
platformio-ide|pla|1.9.2
vscode-css-peek|pra|3.0.2
java|red|0.51.0
vscode-yaml|red|0.5.3
LiveServer|rit|5.6.1
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
vuetify-vscode|vue|0.2.0

</details>

**Comment by Alfred75** [comment]
this is not a dup. It's not the command (as in build, restore, etc...) that is not found but dotnet itself

**Comment by alexr00** [comment]
This is most likely an issue with the code that adds your environment to VS Code on launch (related: https://github.com/microsoft/vscode/issues/21655). Terminal is unaffected because it runs an interactive login shell. 
Can you open the dev tools (Toggle Dev Tools) and try running `process.env` in the console? If your path is also wrong there then the issue is with that environment copying code.

**Comment by Alfred75** [comment]
Thanks,

Just tried but  I get the correct path in the console :

  1.  PATH: "/usr/local/mysql/bin:/Users/urbanmac/miniconda3/bin:/Users/urbanmac/miniconda3/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin"
  2.  PWD: "/"

**Comment by alexr00** [comment]
What is the exact error you get when you try to run your task?

**Comment by alexr00** [comment]
Can you also try disabling all extensions and running the task?
