### ISSUE TITLE
Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by RadioMan116** [microsoft/vscode#82922]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

**Comment by RadioMan116** [comment]
less not compille 

worked yesterday

**Comment by roblourens** [comment]
Need more details

**Comment by RadioMan116** [comment]
Inline JavaScript is a feature of LESS that used to be enabled by default. It was disabled by default in v3.0.0 of LESS for security reasons. You can use the javascriptEnabled setting to override this behaviour by setting the value to true.

If you receive this error unintentionally, there are most likely one or more backticks (``) in your .less file. }
