### ISSUE TITLE
"Failed to save" dialog with compare option is missing a settings gear/icon/option

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#82934]
When trying to save a file that is older than what's already on disk, VSCode throws up the following error:

![image](https://user-images.githubusercontent.com/177243/67163463-fd43e180-f323-11e9-9797-b2245c739394.png)

However, there is nothing in that error that allows users to search the settings in order to disable this (often unwanted) dialog, and the dialog itself does not offer the usual gear icon to quick-change its settings.

On that note: where _are_ its settings? There should absolutely be a way to disable this "helpful" feature, and there should absolutely be a way for users to find those settings based on the information presented in the dialog (e.g. if the settings for this are something about "dirty files", the dialog should at the very least use those terms so that users can search for those settings themselves)

**Comment by Pomax** [comment]
@bpasero can you please mention which issue this is supposedly a duplicate of? Because I don't see a single one that talks about the fact that this dialog is missing settings and a corresponding settings option.

**Comment by Pomax** [comment]
I already upvoted that one - I can add more details but it doesn't look like anyone even triaged that issue yet? If we're flagging this as duplicate, can that issue be labeled etc.?

**Comment by bpasero** [comment]
@Pomax I can assure you that the issue is not lost if it is still open and was not closed as "out of scope". But we have probably thousands of feature requests that fall into this category, so they may not get a lot of attention in the near term (12-24 months).

**Comment by Pomax** [comment]
Is there a way to sponsor an issue, then? Because this is borderline a bug: it literally prevents people from doing work in VS Code by going "no, you don't get to save your file, I don't care if you know better and you know I should save this, I will not let you, the user, do what you, the user, know should happen". 

I don't have time to work on this, but I'll happily pitch in a few donation bucks if it means fixing a workflow-breaking-ly bad bit of UI.

**Comment by bpasero** [comment]
@Pomax wait a second...

>  "no, you don't get to save your file, I don't care if you know better and you know I should save this, I will not let you, the user, do what you, the user, know what should happen".

There is a reason the notification appears in the first place and it should absolutely be the exception. If a file has changed on disk while it is open and dirty in VSCode, we alert you that saving will overwrite whatever state there was on disk. If we would not have such an experience, there would be a large number of users complaining that VSCode caused data loss because it just overwrote changes that were made outside of VSCode.

And there is a straight forward flow for getting out of the situation: you compare the changes on disk with yours and click "Overwrite" button to accept them. Does that not work for you?

**Comment by Pomax** [comment]
yes, but this will pop up even when _as the person working on this file, I know my copy is _not_ dirty, and instead something outside of VSCode changed the file on disk and I _want_ what I have open to save. 

Having to do a compare view for every one of those files is not "straight forward", it's workflow breakingly annoying, and not even having the option to say "force save" so I can continue instead of interrupt my work really should be base line, not "a nice to have".

**Comment by bpasero** [comment]
> yes, but this will pop up even when as the person working on this file, I know my copy is not dirty, and instead something outside of VSCode changed the file on disk and I want what I have open to save.

So how exactly do you get into that state? The file is dirty in VSCode to begin with right? A good option is to enable auto-save in VSCode so that you never get into the state of the working copy in VSCode being out of sync with disk.

**Comment by Pomax** [comment]
Dude, you tell me. If the dialog popping up had anything predictable about it, I wouldn't be complaining about it. VSCode will literally for seemingly _no reason at all_ pop up this dialog, when I'm working on a branch with 100 file changes, and not being able to say "I don't give an f, save my file because I know that nothing else should have touched this while I was working on it" is infuriating when it keeps happening, and I keep not being able to just click "force save".

As for auto-save: no thanks, that interferes too much while running dev/debug tasks that have an "rebuild on file changes" aspect to them (which is quite a few fo the tasks in quite a few of the projects I work on in my day job).

I don't know why I keep getting this dialog, but it's heavily interfering with your work when it pops up without anything happening that should cause it to pop up, and for _those_ people, that "force save" option is critical. It won't make things worse for anyone else, but it will make things better for quite a lot of folks (especially the ones who don't file issues but run into this quite a lot. That's four people in my team alone, at least).
