### ISSUE TITLE
"dependsOn" task not getting executed.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#82938]
- VSCode Version:
```
1.40.0-insider
5aec74ad3b55bb9463e717ec950e665288accd0f
x64
```
- OS Version: `Linux 5.3.7-arch1-1-ARCH`

Steps to Reproduce:

1. Create a simple workspace as follows:
![image](https://user-images.githubusercontent.com/31551546/67165039-8ff97600-f34e-11e9-81e5-95bb58fe234f.png)
2. Try to run task "main"

Only "world" will be printed as the dependency task is never run.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thanks for catching and reporting!
