### ISSUE TITLE
Explorer search is useless with collapsed folders

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#82941]
- VSCode Version: 1.39.2
- OS Version: Windows 1903

Steps to Reproduce:

1. Open any workspace or folder
2. Make sure all folders are collapsed
3. Click on explorer, then try search for a file name
4. It won't find the file nor mark or decorate anything to give us a hint where the file is

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Expected behavior:
a) Filter out all files, except the one's found by the search term (and its respective folders)
or
b) Automatically open all folders until the file is visible
or
c) Mark the folders where files were found in italic or with some icon or color

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/66971
