### ISSUE TITLE
CTRL+LF is not supported in WSL and should not be used.

### ISSUE THREAD

**Issue by b-hayes** [microsoft/vscode#82947]
Issue Type: <b>Bug</b>

I am editing bash scripts and profiles that are breaking.

I have WSL supposrt installed I amd launching vs code from WSL to edit the files yet it is adding windows line endings and breaking everything.

This makes vscode unsuable.

I really do not understand why windows needs to add Ctrl+LF in everyhting when It understands using just LF.

Windows should follow the standard everyone else is using and stop breaking eveything and causing headaches for developers.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.92GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu-18.04/home/brad/.zprofile --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|Memory (System)|15.93GB (4.92GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-line-endings|jha|0.2.0
auto-close-tag|for|0.5.6
remote-wsl|ms-|0.39.9
vscode-icons|vsc|9.4.0

</details>

**Comment by roblourens** [comment]
You can configure this with the `files.eol` setting, otherwise it detects what the file is using already.

**Comment by b-hayes** [comment]
Cool thanks where can I find this setting?
And how can I change the line endings on existing files?
I tried some extensions that show line endings but they cant change them.

Still think LF should be the default esp considering im launching it from wsl or at least offer some visible options for line endings.

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/49418 fixed that shellscripts now use LF by default.

If you start code out of WSL (using the Remote-WSL extension), we use LF as default for all files, unless you have changed the `files.eol` setting. The default is used for new files. For existing files we always detect what's already there and stay consistent. There are command to switch the line delimiters.
