### ISSUE TITLE
Tab title background should not be current line highlight

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8294]
This is a unhappy collision of styles (GitHub Clean White theme) and the background color of the tab area. I wonder if we should use the background color of viewlets inside of the darker tone?

![screen shot 2016-06-28 at 12 02 21](https://cloud.githubusercontent.com/assets/1794099/16411638/4958b704-3d28-11e6-9b39-e62f3c0b43de.png)

**Comment by bpasero** [comment]
Yeah, @bgashler1 and me work on this still and we will pick a color closer to viewlet.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8564
