### ISSUE TITLE
TS status can still show in status bar when going from TS File -> Output Panel -> Settings Editor

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#82940]
Issue Type: <b>Bug</b>

The `onDidChangeActiveTextEditor` event does not seem to be fired when the previous editor was the output panel and the new editor is `undefined`, resulting in slightly buggy UI behavior.

**Steps to reproduce:**
1. Open a typescript file and the settings page.
2. Show the output panel.
3. Select the typescript file, then click somewhere in the output panel, then select the settings page.

![activetexteditor](https://user-images.githubusercontent.com/1007463/67166396-bebe1f00-f343-11e9-991e-dd00ceaa7255.png)

VS Code version: Code - Insiders 1.40.0-insider (5aec74ad3b55bb9463e717ec950e665288accd0f, 2019-10-18T05:33:48.915Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
That's the defined behaviour. From the doc

> The currently active editor or `undefined`. The active editor is the one
		 * that currently has focus or, when none has focus, the one that has changed
		 * input most recently.

**Comment by mattacosta** [comment]
That is not what happens in practice. When going from the typescript editor directly to the settings page, an event is triggered because the value changes to `undefined`. Therefore, when going from the output editor to the settings page, either the same event should be triggered or the first event was triggered in error. Either way there's a bug.

**Comment by mattacosta** [comment]
@jrieken Thoughts? The status bar item of vscode's built-in extension clearly isn't being hidden when it should be, so...

**Comment by jrieken** [comment]
Thanks for clarifying and the ping - this almost got lost... Needs some investigation but sound like a bug. @bpasero When no code editor has focus we use the workbench active editor. In the case of the setting UI would that be the active editor?

**Comment by bpasero** [comment]
@jrieken yes, as far as the workbench is concerned there is always an active editor unless a group is active that has no editor open (e.g. when all editors are closed or when enabling the setting to not close empty editor groups).

In this particular case, the following code seems to get hit:

```ts
if (!activeEditor) {
	let candidate: IEditor | undefined;
	if (this._activeEditorOrder === ActiveEditorOrder.Editor) {
		candidate = this._getActiveEditorFromEditorPart() || this._getActiveEditorFromPanel();
	} else {
		candidate = this._getActiveEditorFromPanel() || this._getActiveEditorFromEditorPart();
	}

	if (candidate) {
		editors.forEach(snapshot => {
			if (candidate === snapshot.editor) {
				activeEditor = snapshot.id;
			}
		});
	}
}
```

`_getActiveEditorFromEditorPart` returns undefined because there is no text editor control (it is settings). as such we are hitting `_getActiveEditorFromPanel` which seems to be returning the output panel text editor.

**Comment by bpasero** [comment]
Relevant code from TS version updater (which gets hit):

```ts
private showHideStatus() {
	if (!vscode.window.activeTextEditor) {
		this._versionBarEntry.hide();
		return;
	}

	const doc = vscode.window.activeTextEditor.document;
	if (vscode.languages.match([languageModeIds.typescript, languageModeIds.typescriptreact], doc)) {
		if (this._normalizePath(doc.uri)) {
			this._versionBarEntry.show();
		} else {
			this._versionBarEntry.hide();
		}
		return;
	}

	if (!vscode.window.activeTextEditor.viewColumn) {
		// viewColumn is undefined for the debug/output panel, but we still want
		// to show the version info in the existing editor
		return;
	}

	this._versionBarEntry.hide();
}
```

**Comment by jrieken** [comment]
Assigning to @mjbvz. For the active editor point of view things work as specified - since the output channel got focus last it continues to be the active editor.

**Comment by mjbvz** [comment]
@jrieken What you to propose extensions do in this case? No events are fired in this case. 

All TS really cares about is the active text editor (the full editors, not the output pane one).

**Comment by jrieken** [comment]
idk - how about this: when an output panel is the active editor you could hide the TS status in case no TS editor is visible

**Comment by mjbvz** [comment]
That was the old behavior but it causes the TS status bar items to disappear when you focus the output and then reappear when you switch back to the editor. Everyone hated this, so I added the workaround to not hide the status bar items when the output channel is focused

**Comment by mattacosta** [comment]
For what it's worth, I originally came across this issue because I was able to cause an exception in an extension's view that is designed to only show up when the editor is set to a file that belongs to a particular language. By never notifying it of the change to undefined, it wasn't able to automatically hide itself and prevent clicks that triggered the error. That can probably be worked around, but this could affect more than just a simple status bar item.
