### ISSUE TITLE
multiple redundant dock items

### ISSUE THREAD

**Issue by marclundgren** [microsoft/vscode#82949]
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

I haven't been able to isolate the steps to reproduce the problem. I did a fresh OS X install yesterday, downloaded vscode first and this is already happening.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

## Screenshot
![Screen Shot 2019-10-20 at 9 39 38 PM](https://user-images.githubusercontent.com/1154834/67177344-087a2a00-f383-11e9-91c6-6654b929f460.jpg)

**Comment by joaomoreno** [comment]
@bpasero Do you know what it means when icons appear to the right of that separator?

**Comment by joaomoreno** [comment]
YES! I've added the `mac` label to that issue, that's why I couldn't find it...
