### ISSUE TITLE
activationEvents.workspaceContains for directories

### ISSUE THREAD

**Issue by vuhrmeister** [Microsoft/vscode#8295]
I'm currently creating an extension for Meteor. I only want to activate it if the workspace contains a Meteor project. For that I would like to check for the presence of a `.meteor` directory.

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostMain.ts#L249 should accept folders besides files

**Comment by iambibhas** [comment]
This will be very helpful. Been stuck playing with `activationEvents` with no luck whatsoever. All the commands are activated even when the `activationEvents` dont match. E.g. I've put only `"workspaceContains:.git/config"` in there and the commands still got activated. Not sure how this works. If none of the criteria matches, then the commands shouldn't be activated, right?
