### ISSUE TITLE
gray out unused variables in jsx is not working in the version 1.39.2

### ISSUE THREAD

**Issue by xuanxuan321** [microsoft/vscode#82959]

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example and a screen shot? Does this issue still occur if you disable all extension?

**Comment by xuanxuan321** [comment]
@alexr00 

I found that unused variables will be gray out after I disable the eslint plugin，So how do I leave unused variables in grey when I turn on the eslint plugin
