### ISSUE TITLE
editor.action.moveCarretRightAction   when trigger by alt+l, the line text display disordered

### ISSUE THREAD

**Issue by whiter001** [microsoft/vscode#82958]
This problem is likely to recur.

**Comment by alexandrudima** [comment]
@whiter001 I'm sorry I don't understand what you mean. Can you please explain in greater detail with steps, and what happens vs. what you expect to happen?

**Comment by whiter001** [comment]
my mistake!
before:
![image](https://user-images.githubusercontent.com/19288411/67555043-2ceb5300-f743-11e9-91fc-4926f65e414e.png)

then  
`editor.action.moveCarretLeftAction` by `alt+h` the left words selected
![image](https://user-images.githubusercontent.com/19288411/67555241-7b005680-f743-11e9-98e4-c97847972c53.png)

then:
trigger `editor.action.moveCarretRightAction` by `alt+l`
![image](https://user-images.githubusercontent.com/19288411/67555416-d5011c00-f743-11e9-9a7e-4b20937a1898.png)

Is this expected? I don't know.
I thought default have not selected when trigger by left action.

**Comment by Powerful24HS** [comment]
> my mistake!
> before:
> ![image](https://user-images.githubusercontent.com/19288411/67555043-2ceb5300-f743-11e9-91fc-4926f65e414e.png)
> 
> then
> `editor.action.moveCarretLeftAction` by `alt+h` the left words selected
> ![image](https://user-images.githubusercontent.com/19288411/67555241-7b005680-f743-11e9-98e4-c97847972c53.png)
> 
> then:
> trigger `editor.action.moveCarretRightAction` by `alt+l`
> ![image](https://user-images.githubusercontent.com/19288411/67555416-d5011c00-f743-11e9-9a7e-4b20937a1898.png)
> 
> Is this expected? I don't know.
> I thought default have not selected when trigger by left action.

same as me, that always happen  in windows10 and ubuntu 19.10 , maybe it is a bug.
