### ISSUE TITLE
Export  text from terminal

### ISSUE THREAD

**Issue by Air-EL** [microsoft/vscode#82953]
Issue Type: <b>Feature Request</b>

Sometimes, we may need to export the results of running the program as text to help us analyze the program's problems. 
![image](https://user-images.githubusercontent.com/56814839/67179786-13c46880-f40a-11e9-9235-2af9b49fc95c.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
No plans to expose this right now for security and performance reasons, we may reconsider in the future.
