### ISSUE TITLE
Strange debugger work 

### ISSUE THREAD

**Issue by Alexzanderk** [microsoft/vscode#82956]
Issue Type: <b>Performance Issue</b>
Hi, please look at! As for me, it's strange behavior form debugger work on the first time and other times. 
At the bottom I pinned video
https://youtu.be/W8pXzo_AZ3s

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   22	    98	  3747	code main
    9	    41	  3748	   gpu-process
    0	   205	  3750	   window (helpers.js — migrationsrv)
    0	    66	  3798	     extensionHost
    0	    41	  4239	       electron_node nodeDebug.js 
    0	    66	  4256	         /usr/local/bin/node --inspect-brk=45300 parser/dist/listener.js
    0	    74	  4248	       electron_node tsserver.js 
    0	   205	  4249	       electron_node tsserver.js 
    0	    49	  4257	         electron_node typingsInstaller.js typesMap.js 
    0	    41	  4267	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3798
    0	    33	  3825	     watcherService
    0	    25	  3868	     searchService
    0	    25	  4443	     npm
    0	    25	  4468	       node /Users/admin/Documents/work/projects/smartexe/migrationsrv/audit-service/node_modules/.bin/nodemon
    0	    25	  4476	         npm
    0	   131	  4478	           node --inspect=5858 -r ts-node/register ./src/index.ts
    0	    25	  4481	     npm
    0	    16	  4482	       node /Users/admin/Documents/work/projects/smartexe/migrationsrv/audit-ui/node_modules/.bin/react-scripts start
    0	   246	  4483	         node /Users/admin/Documents/work/projects/smartexe/migrationsrv/node_modules/react-scripts/scripts/start.js
    2	   279	  4484	           /usr/local/bin/node --max-old-space-size=2048 /Users/admin/Documents/work/projects/smartexe/migrationsrv/node_modules/fork-ts-checker-webpack-plugin/lib/service.js
    0	    41	  4548	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork ms-vscode.node2 {"common.vscodemachineid":"879ff515e3ea427bdfa9cf5bb9344551ed7d8d24ae5c8a4410aced3d2a1f5b6d","common.vscodesessionid":"b9009d4b-849e-4f39-9a43-009f6d568e0b1571643840435"} AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
   20	    66	  3866	   shared-process
    0	     0	  4602	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  4600	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (helpers.js — migrationsrv)
|    Folder (migrationsrv): 920 files
|      File types: ts(213) js(199) map(193) wt(53) tsx(35) json(28) md(10)
|                  env(7) lock(4) sh(2)
|      Conf files: package.json(4) tsconfig.json(3) tslint.json(2)
|                  launch.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nvm|abu|0.0.1
jest-snippets|and|1.7.0
vscode-color|ans|0.4.5
gitstash|art|3.1.0
snapshot-tools|asv|0.4.0
vscode-raml|blz|3.0.1
turbo-console-log|Cha|1.3.1
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.5.1
vscode-markdownlint|Dav|0.31.1
vscode-faker|dee|1.3.0
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.4.3
vsc-material-theme|Equ|30.0.0
json-tools|eri|1.0.2
prettier-vscode|esb|2.3.0
nasc-touchbar|fel|1.12.0
output-colorizer|IBM|0.1.2
vscode-react-typescript|inf|1.3.1
vscode-styled-components|jpo|0.0.26
solidity|Jua|0.0.64
graphql-for-vscode|kum|1.15.1
restructuredtext|lex|114.0.0
git-graph|mhu|1.17.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|0.8.1
vscode-language-pack-ru|MS-|1.39.3
python|ms-|2019.10.41019
vsliveshare|ms-|1.0.988
debugger-for-chrome|msj|4.12.0
chai-snippets|nwh|0.1.0
fix-json|oli|0.1.2
vscode-jest|Ort|3.0.2
material-icon-theme|PKi|3.9.1
vscode-graphql|Pri|0.2.2
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
addDocComments|ste|0.0.8
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0
quokka-vscode|Wal|1.0.256
vsc-jsonsnippets|wmo|0.1.4
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Use the following setting please
"debug.internalConsoleOptions": "openOnSessionStart",

**Comment by Alexzanderk** [comment]
Amazing, thanks!
