### ISSUE TITLE
JSON: Key completion inserts one quote too many

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82967]
![Peek 2019-10-21 12-22](https://user-images.githubusercontent.com/22350/67197634-8549ea00-f3fd-11e9-8bdb-a07b806491f9.gif)

**Comment by aeschli** [comment]
@jrieken Duplicate of which issue?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/10266
