### ISSUE TITLE
Replace tree refresh feels a bit slugish

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8297]
#8184
Just the impression I got - so feel free to close

Steps to Reproduce:

1. Search  / replace for some term
2. Remove results one by one (not by file, but by result)
3. The whole tree update feels a bit slow to me
4. You should refresh just that node in the tree (the file) - not the whole tree in this case. Not sure if you are doing that

**Comment by sandy081** [comment]
I am refreshing the parent of the element that is being removed. So for single match, file entry is refreshed. And I do not see any issues.
