### ISSUE TITLE
Closed search bar visible when Replace field is multiline

### ISSUE THREAD

**Issue by glecetre** [microsoft/vscode#82978]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open any file
1. Hit `CTRL+H` to open the Search and Replace bar
1. In the Replace field, hit `Shift+Enter` to add a line return
1. Close the bar

--> The bottom of the bar is visible while closed.

![image](https://user-images.githubusercontent.com/43233602/67205696-89333780-f410-11e9-8b8b-7fc34ca6e8d6.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2873)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.63GB (4.55GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
vscode-tailwindcss|bra|0.2.0
gitlens|eam|10.1.1
auto-rename-tag|for|0.1.0
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.160
graphql-for-vscode|kum|1.15.1
rainbow-csv|mec|1.3.1
git-graph|mhu|1.17.0
dotenv|mik|1.0.1
language-gettext|mro|0.1.1
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.988
debugger-for-chrome|msj|4.12.0
material-icon-theme|PKi|3.9.1
partial-diff|ryu|1.4.0
ayu|tea|0.18.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by glecetre** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Edit > Replace / Ctrl-H loses focus (#73347)](https://www.github.com/microsoft/vscode/issues/73347)

This is not a duplicate.

**Comment by frobinsonj** [comment]
@rebornix, I hope you don't mind but I had a look into this and I've fixed it. Should I bother with a PR or leave it to you?

**Comment by rebornix** [comment]
@frobinsonj not at all, feel free to send out your work and thanks for your contribution!
