### ISSUE TITLE
Git version manger

### ISSUE THREAD

**Issue by danijel1108** [microsoft/vscode#82979]
Other project's changes numbers still remain in the left side activity bar.

Here are steps you can get issue.
1. Open one project (there isn't any git changes)
2. Open one file of the other project (there are 3 git changes which not committed yet)
3. Remove second project in the git manger.
4. Number 3 still remain with first project although there isn't any changes at all.

**Comment by joaomoreno** [comment]
I can't reproduce this. Can you share a screenshot? Can you right click on the top of Source Control and confirm that there are no more repositories open?

**Comment by danijel1108** [comment]
https://user-images.githubusercontent.com/42989968/67210389-97527980-f44b-11e9-966c-617e60a9016f.png

**Comment by joaomoreno** [comment]
Can you right click on the top of Source Control and confirm that there are no more repositories open?
