### ISSUE TITLE
Typescript: Missing suggestions in field initializers

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#82989]
I'm finding that TypeScript fails to provide suggestions in very easy places. Check this out:

![Peek 2019-10-21 16-41](https://user-images.githubusercontent.com/22350/67215425-b76d4300-f421-11e9-8449-dfb3a65b6c63.gif)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/vscode/issues/82989 to track this upstream

**Comment by joaomoreno** [comment]
@mjbvz You might've missed a copy, that points to this issue.

**Comment by mjbvz** [comment]
Fixed https://github.com/microsoft/TypeScript/issues/34621
