### ISSUE TITLE
Provides a way to determine which rows currently handle the folded state

### ISSUE THREAD

**Issue by xucongli1989** [microsoft/vscode#82980]
I'm writing a plugin for folding areas, but I can't find the API I need.
I think an API can be provided, which will have the following functions:
- Determine which rows handle the folded state
- Whether a row is in a folded region
- It is best to customize the folding symbol, such as "{..."

**Comment by aeschli** [comment]
The API to define folding ranges is:
https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider

We don't have an APIs to let you find out out whether a line is folded or not:
Issue is https://github.com/microsoft/vscode/issues/36638

The request to customize `...` is https://github.com/microsoft/vscode/issues/70794
