### ISSUE TITLE
Add proper HEALTHCHECK colorization/intellisense (Dockerfile language)

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#82984]
Copied from @lostintangent original issue here: https://github.com/microsoft/vscode-docker/issues/43

> This PR introduces basic colorization of the HEALTHCECK command in Dockerfiles, however, it doesn't support colorization of the healtcheck sub-commands (NONE and CMD) or any of the options (--interval, --timeout, --retry).
> 
> ![image](https://user-images.githubusercontent.com/36966225/67211956-938e0b00-f3e9-11e9-869e-521fa728e26b.png)
>
> Additionally, the Dockerfile language service should provide auto-completion support for the HEALTHCHECK command, in order to make it easier to author.
>
> The newly added linting support already fully supports validating the various permutations of the HEALTHCHECK command, and we have a snippet as well, so we just need to finish the colorization/auto-complete.

**Comment by alexr00** [comment]
Moved to owning repo

**Comment by bwateratmsft** [comment]
Ah, sorry--didn't realize that file comes from further upstream.
