### ISSUE TITLE
Dockerfile syntax highlighting for escaped quotes is not quite right (Dockerfile language)

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#82988]
Copy from @dlech original issue here: https://github.com/microsoft/vscode-docker/issues/75

> Given the following dockerfile snippet...
>
```
# setup a new user
COPY compiler.sudoers /etc/sudoers.d/compiler
RUN chmod 0440 /etc/sudoers.d/compiler && \
    adduser --disabled-password --gecos \"\" compiler && \
    usermod -a -G sudo compiler
USER compiler
WORKDIR /home/compiler
CMD ["/bin/bash"] ["--login"]
```

> The escaped quotes after `gecos` appear to throw off the syntax highlighting.
>
> ![image](https://user-images.githubusercontent.com/36966225/67213825-b79f1b80-f3ec-11e9-9caa-6cc4e1326ab3.png)

**Comment by alexr00** [comment]
Moved to upstream reop

**Comment by bwateratmsft** [comment]
Ah, sorry--didn't realize that file comes from upstream.
