### ISSUE TITLE
Decrease Activity Bar size

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#82996]
I always have the activity bar turned off, because it just feels very large and it bothers me. 
However, many extensions often add useful buttons and items there. 

Currently, it looks like this for me:

![Snipaste_2019-10-21_13-49-51](https://user-images.githubusercontent.com/2473545/67225516-c811bf00-f409-11e9-9ffb-cb3009dc1fb4.png)

But I would like to have it a little bit smaller. That would bother me a bit less. And that's considering that I already have
```
    "window.zoomLevel": -1,
    "editor.fontSize": 16,
```

Also, the icons look a little bit misaligned.

**Comment by isidorn** [comment]
I am +1 for making the activity bar a bit thiner and more sexy

**Comment by misolori** [comment]
This is the same request as #73713, which I marked out of scope due to the low upvotes. I also attempted this in #52641 but it wasn't configurable.

**Comment by DeltaRazero** [comment]
I would rather see it be resizable like the sidebar and let the icons scale based on the width that way. Of course you'd need to define a minimum and maximum width somehow too.

However, if the activity bar bothers you, I think you should rather upvote https://github.com/microsoft/vscode/issues/12377#issuecomment-248738612 so the suggestion for setting the activity bar at the top or bottom gets more votes. It'll take up even less space then.

Also: setting the activity bar at the bottom is actually possible with some trickery, but this extension does that for you https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui

**Comment by pedrogarcia** [comment]
Yes, but the sidebar really are like tabs, but look and behave as buttons (when toggling). It's a mess conceptually, it does let me put a lot of things at the same time when I want and it also does not allow me to have a minimalist editor when needing focus.

**Comment by musm** [comment]
Agreed, it would be nice if the size was user configurable. RIght now they take up too much valuable screen real estate.

**Comment by isidorn** [comment]
I am all up of decreasing activity bar size, though not sure how well it plays with our icons. Thus leaving to @misolori to decide what to do here

**Comment by misolori** [comment]
Since this has been marked as a backlog candidate for nearly 6 months and hasn't received many upvotes, I'll be closing this issue.
