### ISSUE TITLE
SSH: Build task fails on Windows Remotes: ${__process__} does not exist

### ISSUE THREAD

**Issue by xJonathanLEI** [microsoft/vscode#82994]
- VSCode Version: 1.40.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18362

**Steps to Reproduce:**

1. Establish a Remote Development session to a Windows host
2. Create a new .NET Core project with (I happen to do C# development):

        dotnet new console -o Reproduce

3. Open the project folder just created in the Remote Development session
4. Create file `.vscode/tasks.json` with the following content (the auto-generated stuff):

        {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": "build",
                    "command": "dotnet",
                    "type": "process",
                    "args": [
                        "build",
                        "${workspaceFolder}/Reproduce.csproj",
                        "/property:GenerateFullPaths=true",
                        "/consoleloggerparameters:NoSummary"
                    ],
                    "problemMatcher": "$msCompile"
                }
            ]
        }

5. Run the build task

**Expected Result:**

The build task succeeds as it would natively on the Windows host.

**Actual Result:**

The build task fails with the following output:

    > Executing task: ${__process__} build MY_PATH_TO_PROJECT/Reproduce.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

    The terminal shell path "${__process__}" does not exist

Does this issue occur when all extensions are disabled?: N/A

**Comment by xJonathanLEI** [comment]
Workaround: Change `"type":"process"` to `"type":"shell"`

**Comment by alexr00** [comment]
It looks like the fix I made worked. Can folks who were seeing the issue try again and confirm?

**Comment by xJonathanLEI** [comment]
> It looks like the fix I made worked. Can folks who were seeing the issue try again with the latest insiders and confirm?

I can confirm the bug has been fixed in the latest insider build :)

**Comment by alexr00** [comment]
Thank you for verifying!
