### ISSUE TITLE
Add context menu option to toggle side bar visibility into the "more actions..." menu

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#82998]
I often have the activity bar turned off.
However, the side bars are actually useful, but not all the time.

It would be great to have a context menu option to toggle the side bar visibility. 

![Snipaste_2019-10-21_13-59-20](https://user-images.githubusercontent.com/2473545/67226307-00fe6380-f40b-11e9-9f88-3dd2a5fb5140.png)

**Comment by pedrogarcia** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [[Feature] An option to move the activity bar to the top  (#72443)](https://www.github.com/microsoft/vscode/issues/72443)
> * [Menu bar toggling is inconsistent with the rest of Windows (#58377)](https://www.github.com/microsoft/vscode/issues/58377)
> * [Icon for menus (#65723)](https://www.github.com/microsoft/vscode/issues/65723)

None of these are duplicates.

**Comment by bpasero** [comment]
This menu is specifically for editor actions, not the sidebar.
