### ISSUE TITLE
Debug console output doesn't scroll on highlight + drag of mouse

### ISSUE THREAD

**Issue by ebluestein** [microsoft/vscode#82997]
- VSCode Version: 1.39
- OS Version: Any (Verified on Windows 10 and Mac)

Steps to Reproduce:

1. Run any debug session that generates a bunch of output text (any amount > the height of the pane)
2. Start selecting the text with the mouse to highlight it. Without releasing the mouse button drag the mouse to the top of the debug console output pane
3. In the ordinary output pane, the pane would scroll to allow you to keep selecting text upward. The debug console does not scroll, making it very difficult to copy-paste large amounts of debug output text.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/2163
