### ISSUE TITLE
Paste shortcut not working anymore

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vscode#83002]
- Version: 1.39.2
- Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- Date: 2019-10-15T15:33:00.827Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.7.0

it seems to me that we could copy/paste in the terminal using the usual shortcut. But it seems that the shortcut for paste does not exist anymore:

![image](https://user-images.githubusercontent.com/15056323/67231662-a62f3100-f437-11e9-9c47-651da98113b4.png)

It is a little bit strange since all the other usual shortcuts are defined.

**Comment by PierreMarchand20** [comment]
Even in the editor actually it disappeared 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/15056323/67245673-76425680-f454-11e9-956f-950fff97ba16.png">
and this with all extensions disabled and after reloading the window

**Comment by sbatten** [comment]
I can reproduce in stable and insiders in the terminal. @PierreMarchand20 I cannot reproduce inside the editor.

**Comment by sbatten** [comment]
@Tyriar seems intentional? https://github.com/microsoft/vscode/blob/877ce7ac034390e31c5ecebccbb0683bd2c51c3d/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L362-L366

**Comment by Tyriar** [comment]
Works for me in the editor as well 🤷‍♂ 

Please open a new issue if that still happens on the latest insiders version
