### ISSUE TITLE
onDidChangeActiveTextEditorsLanguage event

### ISSUE THREAD

**Issue by Alvain1980** [microsoft/vscode#83009]
I make an extension. My task is to add an element to the status bar when working with a specific language, for example, SQL. For other languages, the element should not be displayed.
The problem is that the extension is activated when you change the language in the editor to SQL or open the * .sql file (as per the condition in package.json). The status bar element is shown, but then the extension is considered active and I couldn't find the way to hide the status bar element if editor's language is set back to "plaintext", for example.
It would be very good to have an event named like "onDidChangeActiveTextEditorsLanguage".

**Comment by jrieken** [comment]
When the language of a document changes the `onDidCloseTextDocument` and `onDidOpenTextDocument` events are fired: https://github.com/microsoft/vscode/blob/f1583f11ab8ce7f9d4356ce238c2cd36b26f54c5/src/vs/vscode.d.ts#L8157-L8179
