### ISSUE TITLE
Empty terminal when task has "reveal: never"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83016]
I have this task:

```json
{
  "type": "npm",
  "script": "watch",
  "problemMatcher": "$gulp-tsc",
  "isBackground": true,
  "presentation": {
    "reveal": "never"
  },
  "group": {
    "kind": "build",
    "isDefault": true
  }
}
```

- Run the task
- Open the terminal
- There is no text in the terminal

**Comment by roblourens** [comment]
Got errors like this:

![image](https://user-images.githubusercontent.com/323878/67247443-3ceaf600-f416-11e9-8d5e-1cf096bbee20.png)

**Comment by alexr00** [comment]
@Tyriar this seems likely an issue in terminal, since tasks doesn't know or care about whether the terminal is visible. I tried to bisect, but someone made a complicated merge commit so it got messy.

**Comment by Tyriar** [comment]
@alexr00 yep this is related to a change in xterm.js where I throw an exception which was too aggressive

**Comment by JacksonKearl** [comment]
Cant repro on stable, was this just on an intermediary Insiders?

**Comment by Tyriar** [comment]
@JacksonKearl yes insiders only.
