### ISSUE TITLE
Problems: allow me to navigate from filter box to error list

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8301]
Refs: https://github.com/Microsoft/vscode/issues/7601

Either by allowing arrow-down to go to the list (as extensions viewlet) or maybe when I press enter move focus to the tree.

**Comment by sandy081** [comment]
A new command to focus problems from filter is added with default keybinding `cmd+down` and another command to focus filter from problems panel with default keybinding `cmd+f`.
