### ISSUE TITLE
Selected whitespace is not rendered correctly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83012]
Look at this text in the editor with the mode enabled to show selected whitespace.

`// foo   bar`

insiders:
![image](https://user-images.githubusercontent.com/323878/67245019-debb1480-f40f-11e9-9cd0-4410cd82ca52.png)

stable:
![image](https://user-images.githubusercontent.com/323878/67245064-f72b2f00-f40f-11e9-89f8-796689cfc506.png)

**Comment by RMacfarlane** [comment]
@roblourens I'm having trouble reproducing, do you still see this when your settings file is commented out? Or with extensions disabled?

**Comment by roblourens** [comment]
Oh, it happens with `"editor.fontFamily": "Cascadia Code"`

I guess there is a character missing from that font?

**Comment by alexdima** [comment]
@roblourens I think this was fixed in the meantime. Can you please confirm?

**Comment by roblourens** [comment]
Yeah I think I filed another issue about exactly this...
