### ISSUE TITLE
terminal.newWithCwd not working over Remote - SSH

### ISSUE THREAD

**Issue by ynma** [microsoft/vscode#83011]
- VSCode Version: 1.39.2
- OS Version: macOS 10.14.3

**Steps to Reproduce:**

1. Add the new terminal.newWithCwd command as a new keybinding:

```
{
  "key": "cmd+shift+h",
  "command": "workbench.action.terminal.newWithCwd",
  "args": {
    "cwd": "${fileDirname}"
  }
}
```

2. Attempt to use the new keybinding with an open editor while using VS Code Remote - SSH.

**Expected Result:** 

New terminal created with the cwd set at ${fileDirname}

**Actual Result:**

Error: '${fileDirname}' can not be resolved. Please open an editor.

**Notes:**

The keybinding works correctly when working with local directories. The issue only appears over SSH.

The Terminal Here extension does work over SSH and accomplishes the same thing, but I would rather use the native feature if possible. The "echo ${fileDirname}" command (run through a task) prints the correct directory over SSH.

**Comment by Tyriar** [comment]
@sandy081 is the resolver service being used incorrectly here?

https://github.com/microsoft/vscode/blob/62f9bd73d86c40fedd0e889dac2cf01bcd8111d0/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L194-L203

`${lineNumber}` seems to resolve fine but not `${workspaceFolder}` or `${fileDirname}`.

**Comment by sandy081** [comment]
Configuration resolver is owned by @isidorn, hence assigning to him.

**Comment by isidorn** [comment]
@Tyriar that usage seems good. Just make sure you always pass a workspace in.

Also note that might be working as expacted
${workspaceFolder} can only be resolved if a folder is opened in VSCode, not in the pruple vscode.

${fileDirname} should always be resolved if there is an open file

fyi @alexr00
