### ISSUE TITLE
Interactive playground's suggest widget styled everything as links

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83024]
Issue Type: <b>Bug</b>

**Repo**
1. Open interactive playground and trigger suggest widget

**Bug**
The styling of the suggest widget shows everything in blue:

![Screen Shot 2019-10-21 at 6 07 08 PM](https://user-images.githubusercontent.com/12821956/67253746-3a949600-f42e-11e9-9d7d-fde7b1f10513.png)

Here's a normal suggest widget for comparison:

![Screen Shot 2019-10-21 at 6 07 11 PM](https://user-images.githubusercontent.com/12821956/67253758-497b4880-f42e-11e9-83ab-9c2f6142405a.png)

VS Code version: Code - Insiders 1.40.0-insider (82ca6ba87f450245f665ab7a5f3a686e2cd00045, 2019-10-21T05:39:31.415Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 5|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AlexStrNik** [comment]
Ok. I founded a line of code that causes this. 

```ts
collector.addRule(`.monaco-workbench .part.editor > .content .walkThroughContent a { color: ${link}; }`);
```

This CSS rule has a larger priority than CSS rules that styles `suggest-widget` highlighted labels.
So here are two ways to fix this:

1. Lower the priority, e.g
```ts
collector.addRule(`.walkThroughContent a { color: ${link}; }`);
```
2. Modify this rule to apply only for such tags that have non-empty `href` attribute
```ts
collector.addRule(`.monaco-workbench .part.editor > .content .walkThroughContent a:non([href='']) { color: ${link}; }`);
```
