### ISSUE TITLE
Can not jump to symbol with a folder on a read only directory in workspace

### ISSUE THREAD

**Issue by oglops** [microsoft/vscode#83022]
- VSCode Version: 1.39.1
- OS Version: Fedora 30

Steps to Reproduce:

1. add any folder which is read only to workspace 
2. change interpreter settings then you will see

Failed to set 'pythonPath'. Error: Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/path/to/dir/.vscode')

Then because the file is a python 2 file, default interpreter is 3.5, it says symbol not found when ctrl+shift+o is pressed

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
pythonPath is not part of VS Code. It is in an extension.
