### ISSUE TITLE
Replace mode needs more UX affordance

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8302]
#8184 

Currently the search / replace widget behaves quite differently if the replace box is visible or not. The differences are what results are outlined in the viewlet (searched or replaced) and what file is opened when you click on a result.
There is a large difference in behavior and the only way a user can see in what mode he is is whether a replace box is visible. I propose to add some more UX affordance - maybe updating the title of SEARCH to SEARCH / REPLACE. Or some more styling with colors.
This might get fixed by addressing #8286

ping @stevencl, @bpasero  for opinions

**Comment by bpasero** [comment]
After discussion with @isidorn and @sandy081 suggest to do the following:
* replace is disabled if there are no search results or the search criteria changed (maybe we give a hint how to enable it in the tooltip of the action or the backgroung text of the replace box)
* if replace is visible and something is typed we show a preview of the diff in the same colors as the diff editor (green, red) and probably also with strikethrough for people that cannot read colors
* we do not show such a preview if replace is empty (but you can still trigger the replace action to replace with empty string)
* if you had something in replace and remove the text in replace we switch back to showing the search results (but replace action is still enabled)
* we no more do anything if focus moves between search and replace, all is dependent on having a value in the replace box

**Comment by sandy081** [comment]
Here is the replace preview in different themes. 

In Replace preview I used same color as in Search results for search string but with strike through.

![screen shot 2016-06-29 at 11 43 13 am](https://cloud.githubusercontent.com/assets/10746682/16448332/308e488c-3df1-11e6-8b9e-6e01f786ab5f.png)


![screen shot 2016-06-29 at 11 43 31 am](https://cloud.githubusercontent.com/assets/10746682/16448338/35f407da-3df1-11e6-8c85-5612a7e537cd.png)

**Comment by bpasero** [comment]
@sandy081 nice, can you also attach when using same as diff colors?

**Comment by isidorn** [comment]
@sandy081 I would use the same color we use in the diff editor. The impression I got from looking at these images is that it is a different one (might be due ot the gray background)

**Comment by sandy081** [comment]
Reason being, there will be more color changes user has to adopt to.. 

Search - 1 color
Replace - 2 colors

If we use single color for Search results, then only difference user will see is Replace color

**Comment by isidorn** [comment]
I do not think it is bad that we use 2 completly different colors than regular search results as that address my concern that the replace mode needs more ux affordance. So the colors could differntiate it.

Only if it turns into the disco mode I would go back to your suggestion

**Comment by sandy081** [comment]
Attaching pictures using Diff editor color

![screen shot 2016-06-29 at 12 14 10 pm](https://cloud.githubusercontent.com/assets/10746682/16448732/48053fe6-3df3-11e6-9444-26533c22d03f.png)
![screen shot 2016-06-29 at 12 15 49 pm](https://cloud.githubusercontent.com/assets/10746682/16448734/4afac716-3df3-11e6-964c-5a4967bc70de.png)

**Comment by isidorn** [comment]
I like this more, though it is just my personal preference (due to the reasons specified above).

**Comment by sandy081** [comment]
Thanks @isidorn @bpasero 

I will go with this and we can always change with feedback.

**Comment by bpasero** [comment]
Love it!
