### ISSUE TITLE
Creating a folder opens the selected file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83028]
- Close all open editors
- Focus the explorer, use the arrow keys to move focus to a file
- Click the "new folder" button
- The focused file is opened

**Comment by isidorn** [comment]
We alwasy beahved like this.
Issue being: whenever explorer gets focused if there is no file open we open the focused file. More details https://github.com/microsoft/vscode/issues/67708
The issue which surfaces this is that when the new folder is clicked, we always focus the explorer.

I understand that this is not nice behavior, however I will not change it atm.

**Comment by isidorn** [comment]
This is fixed in latest I belive, thus closing
