### ISSUE TITLE
Test media query symbols

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83020]
Refs: https://github.com/microsoft/vscode/issues/74635

- [x] Windows @eamodio
- [x] anyOS @JacksonKearl (MacOS)

Complexity: 1

Description: Media query now show as symbols. That means they show up in:

- Outline View
- Go to Symbols in File command
- Breadcrumbs

Write some media queries and make sure the outline look alright for you. To start, you can do

```css
@media screen, print {
  .foo {
  }
}
```

Useful: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by eamodio** [comment]
- Outline view, _Go to Symbol in File_, Breadcrumbs all look good
-  _Go to Symbol in File by Category_ also works, but I didn't really see any difference with how the symbols were presented (other than `symbols (<count>)` changes to `classes  (<count>)` -- would have expected a break up of ids, classes, & elements or something like that

Also should _Go to Symbol in Workspace_ work? (it doesn't)

**Comment by octref** [comment]
> Go to Symbol in Workspace

No. Workspace Symbol provider is different than the file-based provider.

> I didn't really see any difference with how the symbols were presented (other than symbols (<count>) changes to classes (<count>) -- would have expected a break up of ids, classes, & elements or something like that

What "differences" were you expecting to see? Currently the difference with stable is that, for the given CSS:

```css
@media screen, print {
  .foo {
  }
}

.foo {
  color: i;
}
```

Stable doesn't handle media query at all:
![image](https://user-images.githubusercontent.com/4033249/67799083-ef880d80-fa41-11e9-93fd-14a24ffce5f4.png)

Insider does:

![image](https://user-images.githubusercontent.com/4033249/67799102-f57dee80-fa41-11e9-92aa-9f2c040a50ed.png)

**Comment by eamodio** [comment]
@octref that feedback is probably outside the scope of this issue. But I just would have expected to have things categorized when using `Go to Symbol in File by Category` but it seems that everything is just grouped under a single `classes` category, rather than by something like: ids, classes, elements, media queries, etc

**Comment by octref** [comment]
@eamodio Can you can open a new feature request with more specifics? Thanks.
