### ISSUE TITLE
Remote: download folder experience is not ideal

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83035]
![image](https://user-images.githubusercontent.com/900690/67264090-5ccbf980-f4aa-11e9-97fe-710b2e5c4d27.png)

I don’t think `ITextFileService` is the right place for downloading a folder. I would rather manually bring up a folder picker to ask the user for the target destination and then use `IFileService.copy()` for the operation to that target folder.

**Comment by isidorn** [comment]
Thanks for creating this, however we already have this https://github.com/microsoft/vscode/pull/82881
Thus closing as duplicate and copying your comment there
