### ISSUE TITLE
Search text in loaded project inside a specific file type is not working fine

### ISSUE THREAD

**Issue by samadmeets** [microsoft/vscode#83032]
While searching for some text "abc" in all files "*.xml" of a specific file type inside a loaded project that has a diverse file structure containing .py, .json, .xml,  and so on.

Shows only few results of the complete results when the same project is loaded in different IDE like Eclipse.

**Comment by roblourens** [comment]
Can you see whether any of these tips help? https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results
