### ISSUE TITLE
Related: VS Code is hard to use on a shared user account and multiple RDP

### ISSUE THREAD

**Issue by TheInnovativeTechnologist** [microsoft/vscode#83030]
I have read thru the following closed issues and cannot see a solution to this problem.  Help please. :)

[VS Code is hard to use on a shared user account and multiple RDP #15674](https://github.com/microsoft/vscode/issues/15674)

[Multi remote desktop session use of VS Code does not behave as expected #31288](https://github.com/microsoft/vscode/issues/31288)

[Windows : Opens in wrong RDP Session #22955](https://github.com/microsoft/vscode/issues/22955)

**Comment by joaomoreno** [comment]
We simply do not support this use case. My recommendation would be to have multiple Code installations per user that would use RDP, maybe using Portable Mode.
