### ISSUE TITLE
Web: allow to drop files into the explorer to upload them

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83036]
As a user of web, I want to drag and drop files (1-N) into a folder of the explorer to have them uploaded there. https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications seems relevant on the topic **Selecting files using drag and drop**

//cc @egamma @lostintangent

**Comment by isidorn** [comment]
Thanks for the docs pointer.
I was able to use the `FileReader` api to extract the data url for each dropped item.
Now I am looking into connecting the dots to use the data url to upload it.

**Comment by bpasero** [comment]
@isidorn wouldn't [`FileReader.readAsArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer) work and simply convert that buffer into a `VSBuffer` and write it via `IFileService.write`?
