### ISSUE TITLE
Multiple Problem Matchers on same task clears out each other

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#8304]
- VSCode Version: Insiders

I have these problem matchers on watching build command. (First one matches on Tslint, second on forked type checker of typescript.)

```JSON
"problemMatcher": [
	{
		"owner": "typescript",
		"fileLocation": "relative",
		"pattern": [
			{
				"regexp": "^(ERROR|WARNING) in (.+)$",
				"severity" : 1,
				"file": 2
			},
			{
				"regexp": "^\\[(\\d+), (\\d+)\\]: (.+)$",
				"line": 1,
				"column": 2,
				"message": 3,
				"loop": true
			}
		],
		"watching": {
			"activeOnStart": false,
			"beginsPattern": "Time: \\d+ms",
			"endsPattern": "webpack: bundle is now VALID."
		}
	},
	{
		"owner": "typescript",
		"fileLocation": ["relative", "${workspaceRoot}"],
		"pattern": [
			{
				"regexp": "^\\[default\\] (.*\\.tsx?) (\\d+,\\d+):$",
				"file": 1,
				"line": 2,
				"column": 3
			},
			{
				"regexp": "(.*)$",
				"message": 1
			}
		],
		"watching": {
			"activeOnStart": true,
			"beginsPattern": "^\\[default\\] Checking started in a separate process...$",
			"endsPattern": "^\\[default\\] Ok"
		}
	}
]
```

They work individually correctly, but when on array they clear each other out with output e.g.

```
Listening at http://localhost:3333. Please wait, I'm building things for you...
Time: 6247ms
WARNING in ./App/o2c.ts
[36, 38]: block is empty
[38, 41]: block is empty
[21, 30]: expected nospace before colon in index-signature

WARNING in ./App/Index.tsx
[2, 13]: unused variable: 'React'

WARNING in ./App/Utils/OpenIdClient.ts
[204, 57]: block is empty
[210, 28]: block is empty
[42, 5]: unused variable: 'AUTHORIZATION'
[48, 13]: unused variable: 'state'
[202, 22]: missing radix parameter
[213, 6]: missing semicolon

WARNING in ./App/Containers/Login.tsx
[29, 1]: exceeds maximum line length of 140

WARNING in ./App/Containers/Sample/WorkListing.tsx
[47, 1]: exceeds maximum line length of 140

webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] Ok, 1.035 sec.
```

Problem is that both problem matchers has different begin and end. Which they should, but because of that the second matcher can't find problems and clears out the errors of first matcher. I can see the warnings appearing in the list shortly, only to be cleared by second matcher.

P.S. workaround is to put same values in end and begin patterns, the values that span the whole output, in my case 

```
"beginsPattern": "Time: \\d+ms",
"endsPattern": "^\\[default\\] Ok"
```

But this is not a solution, since it makes writing problem matchers dependent on other matchers in the array.

**Comment by dbaeumer** [comment]
Good catch.

**Comment by dbaeumer** [comment]
After commenting on #1397 I wonder if the problem is that both of your matchers are using "typescript" as a owner. By design problems have an owner and they override each other when reported on a specific resource. What happens if you give them both different owners.

**Comment by Ciantic** [comment]
@dbaeumer having unique string in "owner" works, it doesn't work if I leave it empty, then it cancels each other out again.

It's very unclear what owner property even means, I was in a illusion it should be the language (because it auto-completed to that). The tooltip is not very clear either:

![image](https://cloud.githubusercontent.com/assets/64731/16450490/e2869a30-3e05-11e6-8d08-a1c18ff8f0ae.png)

It should say it must be unique string if multiple problem matchers are used. Preferrably one should always define unique string there, to avoid copy & paste problems.

**Comment by dbaeumer** [comment]
Fully agree with the unique ID. Opened: https://github.com/Microsoft/vscode/issues/8562
