### ISSUE TITLE
Show opening bracket line when closing bracket is selected

### ISSUE THREAD

**Issue by mtsh1000** [microsoft/vscode#83042]
It would be very useful to show opening bracket line when selecting closing bracket to quickly see the condition or function params your currently in. This could be a breadcrumbs option (second line maybe?)

**Comment by alexandrudima** [comment]
@mtsh1000 I'm not 100% sure I understand what you mean. Can you please describe this in more detail or post a screenshot?

**Comment by mtsh1000** [comment]
@alexandrudima I'm basicly talking about the feature that i'm using a lot in netbeans:
![obraz](https://user-images.githubusercontent.com/32628738/67361453-fb1e9480-f568-11e9-97cb-aca07e245926.png)
![obraz](https://user-images.githubusercontent.com/32628738/67361469-05409300-f569-11e9-9846-14eaefb46fd5.png)

**Comment by alexandrudima** [comment]
Let's track in #55075
