### ISSUE TITLE
Do not encode URIs when asking to open?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83043]
![image](https://user-images.githubusercontent.com/900690/67269252-a7ec0980-f4b6-11e9-84d8-7e7923940906.png)

Maybe use `toString(false)` in https://github.com/microsoft/vscode/blob/c58aaab8a1cc22a7139b761166a0d4f37d41e998/src/vs/workbench/services/extensions/browser/extensionUrlHandler.ts#L145

**Comment by bpasero** [comment]
Verified by code review, I am currently not sure anymore how to trigger this...

**Comment by joaomoreno** [comment]
@bpasero 

1. `Developer: Open URL`
2. `code-insiders://bpasero.test-ts/blabla` (make sure you use the right scheme here)

**Comment by bpasero** [comment]
Ah yes, thanks!
