### ISSUE TITLE
Allow Github workflow badges in extension readme

### ISSUE THREAD

**Issue by notskm** [microsoft/vscode#83047]
Github workflows provide badges to display their status. [Unfortunately, these aren't whitelisted currently.](https://code.visualstudio.com/api/references/extension-manifest#approved-badges) Whitelisting them would be greatly appreciated.

**Example badge URL and documentation:**
`https://github.com/<OWNER>/<REPOSITORY>/workflows/<WORKFLOW_NAME>/badge.svg`

https://help.github.com/en/github/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode-vsce/issues/389
