### ISSUE TITLE
Problems: Improve filter text

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8305]
Refs: https://github.com/Microsoft/vscode/issues/7601

I was initially confused by the filter text "Filter by type or text" because I did not make the connection from "type" to problem type.

I would make it more explicit: "Filter by problem type or text".

@weinand who is best in finding good wording :)

**Comment by sandy081** [comment]
I would probably call it simply "Filter", since one can filter by

- type
- description
- source
- file name

**Comment by weinand** [comment]
@sandy081 I agree, getting a description of all the different filter types into the initial text is not possible. 
So "Filter" sounds ok to me.
But there is still a need for some guidance or help:
Could intellisense be used? You could propose the available problem types and file names.
Or you could have a longer description in some hover?

**Comment by sandy081** [comment]
@weinand I think intellisense would be very nice, but that needs coming up with some grammar/standard to provide the filter which probably does not worth for this filter box.

I think for this case, just providing information would be sufficient.
To have an hover we need some filter icon which has to be in textbox. I had a filter icon in the beginning but removed it later. We can also check with UX for this

**Comment by oriash93** [comment]
Might be solved already, look at #22289 and commit `6f32564`.

**Comment by sandy081** [comment]
Yeah, it got better.
