### ISSUE TITLE
Tool for prototyping TypeScript types faster

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#83052]
Currently, it's very difficult to develop / debug complex types and there seems to be no official tool for prototyping, or not one the community is aware of.

---
Copy pasted from StackOverflow

https://stackoverflow.com/questions/58500139/tool-for-prototyping-typescript-types-faster

Is there an online tool, IDE or VSCode settings option/extension that allows to prototype type definitions (easier/faster)?

The only option I am aware of is to hover over a typed statement which displays the associated type in a tooltip. It's very impractical to use as the types are trimmed and non-interactive, i.e. I cannot hover over a type sub-component to see the trimmed part. Also it's impossible to say which sub-type failed as it's not highlighted.
[![vscode type hint displayed in a tooltip][1]][1]

If I need to step through a complex type to discover the error, I have to deconstruct it like below and then keep hovering over each statement, which is very inconvenient. Maybe if only the IDE could generate those "result comments" automatically, that would make life easier.
[![lots of small test type statements][2]][2]

  [1]: https://i.stack.imgur.com/09c0U.png
  [2]: https://i.stack.imgur.com/KgSky.png

**Comment by mjbvz** [comment]
For example: https://marketplace.visualstudio.com/items?itemName=sokra.ts-inline-types

**Comment by ackvf** [comment]
Unfortunatelly this extension is very resource demanding up to the point of killing the extension host and it doesn't work with type definitions and declarations as in the screenshot. It does seem interesting though, as it names the function parameters.

It think the VSCode's inherent feature should at least be little more friendly than it is now. Can we at least somehow get the full message from the tooltip and get what's hidden under all those `<...>`? Creating extension just to expand the trimmed parts seems like an overkill to me.

If I hover over an interface in the tooltip, I would also like to see the properties or be able to click on a name and go to definition.
[![vscode type hint displayed in a tooltip][1]][1]

  [1]: https://i.stack.imgur.com/09c0U.png
