### ISSUE TITLE
ALWAYS happen, search input covered by search title after a replacement excuted

### ISSUE THREAD

**Issue by energygreek** [microsoft/vscode#83059]
1. open search bar, input content to search
2. open replace bar, input content to replace
3. press enter  and it happends

the search input element is covered by the 'SEARCH' title
![image](https://user-images.githubusercontent.com/25223558/67278876-79911d00-f4fc-11e9-8879-bb528950a799.png)

btw, search input have no boarder in Light+ color theme, that makes it hard to use.

**Comment by roblourens** [comment]
I can repro this on Windows.
