### ISSUE TITLE
Install extension click is not showing up in VS Code editor

### ISSUE THREAD

**Issue by ashukum-msft** [microsoft/vscode#83066]
- VSCode Version: 1.39.2
- OS Version:

**We are observing one issue with VsCode editor. When we click on Install Button on web, it’s not showing up extension details in VsCode Editor**

**Steps to Reproduce:**

1. Go To VS Code extension details page
2. Click on install button 
3. Click on open VS Code button from popup

**Expected:**
1. Extension should  show up in VS Code editor right pane with 'install' button.

**Actual:**
1. Extension is not showing up in VS Code editor 
2. If we click on install button from same extension details page 2nd time, then it is showing up in VS code editor.

It was working fine earlier and It seems like it got regressed with latest VsCode update. We observed that if we click on extension details page 2nd time with VsCode editor already opened, then extension details are showing up in the VsCode editor.
I took a quick look on this issue and analyzed the fiddler calls. You can find the snapshot below. 
Please find the attached fiddler trace for more details.
![ExtensionDEtailsNotLoading](https://user-images.githubusercontent.com/56161576/67289772-c2e16c80-f4fc-11e9-83f6-b1f9d46acfd4.png)

[VsCodeExtensionDetailsNotLoadingIssue.zip](https://github.com/microsoft/vscode/files/3755848/VsCodeExtensionDetailsNotLoadingIssue.zip)

As we can see that VsCode is not calling CDN to get the extensions assets to show the extension details and icon during first time VsCode launch. That’s why it’s not showing up there.
Could you please have a look on this?  Do let me know, if you need more info.

**Comment by bpasero** [comment]
Not sure if this is our URL handler again.

**Comment by ashukum-msft** [comment]
Please find the attached GIF file.

![VsCodeBug](https://user-images.githubusercontent.com/56161576/67475762-6bfea300-f674-11e9-8251-d7d4227d9b96.gif)

**Comment by joaomoreno** [comment]
Cool. This is fixed in `master`: https://github.com/microsoft/vscode/issues/82869
