### ISSUE TITLE
Improve description specificity of the git.confirmEmptyCommits

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#83061]
I'd love it if the `git.confirmEmptyCommits` description would specify that this setting only pertains to the `Git: Commit Empty` command as explained in [#82388](https://github.com/microsoft/vscode/issues/82388#issue-505988675), as opposed to the SCM interface, which would be the expected behavior according to the current description.

**Comment by joaomoreno** [comment]
Feel free to submit a PR for this instead.

**Comment by andrecasal** [comment]
Cool, thanks!
