### ISSUE TITLE
indentationRule doesn't work in language-configuration.json

### ISSUE THREAD

**Issue by AlienKevin** [microsoft/vscode#83064]
I'm working on a custom language extension for vscode. In the `language-configuration.json` file, I tried to specify the `indentationRules` like this:
```json
"indentationRules": {
      "increaseIndentPattern": "^\\s*(if|elif|else|while).*$",
}
```
This is to supposed to support some Python-style indentations like:
```
if 3 > 2
      print(True)
```
However, the auto indentation never works.<br>
The [doc](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules) says that `increaseIndentPattern` is supposed to be a regex that matches the line before the indentation, which I think my regex does match the line `if 3 > 2`.

**Comment by alexr00** [comment]
Looks like your regex is wrong. Check out https://rubular.com/

**Comment by AlienKevin** [comment]
@alexr00 I checked it in rubular and it works for simple strings like "if abc". Can you point out what's wrong with the regex?
