### ISSUE TITLE
Extension UI mixes with editors

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8306]
* two editors open
* endup in the extension viewlet
* select an extension
* you have the extension 'viewlet', a code editor, and an extension view which looks all wrong

![screen shot 2016-06-28 at 12 32 32](https://cloud.githubusercontent.com/assets/1794099/16412450/8fbd9b7a-3d2c-11e6-9f50-8fa09673fc2e.png)

**Comment by isidorn** [comment]
Dup of #7961
