### ISSUE TITLE
Test: no notifications in Zen Mode

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#83067]
Refs: https://github.com/microsoft/vscode/issues/82233

- [x] any os @joaomoreno
- [x] any os @roblourens

Complexity: 2

We no longer show notifications while users are in Zen Mode.
Have some notifications and enter zen mode and verify:
* All the notifications get hidden when you entered zen mode
* You get no more notifications while you are in zen mode
* Error notifications are the exceptions which you still get while in zen mode
* Once you leave zen mode make sure you get notifications normally
* You can control this behavior via setting 	`"zenMode.silentNotifications"`

**Comment by joaomoreno** [comment]
Here's an extension which makes this easy to test: https://github.com/joaomoreno/vscode-extension-sample-notifications

![image](https://user-images.githubusercontent.com/22350/67771665-071ec080-fa59-11e9-93e9-a09842ee6ab2.png)
