### ISSUE TITLE
prettify do not respect indentation settings

### ISSUE THREAD

**Issue by themnd** [microsoft/vscode#83074]
Issue Type: <b>Bug</b>

1. open a new document
2. change indentation settings to spaces with 2 spaces
3. create some json structure
4. apply the Prettify JSON command
5. BUG: verify that 4 spaces indentation is applied instead of 2 spaces.

Extension version: 0.0.3
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by themnd** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Convert width of space indentation (#17802)](https://www.github.com/microsoft/vscode/issues/17802)

nope

**Comment by alexr00** [comment]
That command is contributed by an extension!
