### ISSUE TITLE
Issue with Powershell Terminal in vscode on ubuntu

### ISSUE THREAD

**Issue by WembleyFord2** [microsoft/vscode#83076]
With a clean copy (removed ~/.code and ~/.config/Code folder), on Ubuntu 18.04, I've having problems with lines that are longer than the terminal width once the cursor has reached the last line of the terminal when in Powershell, using the Powershell 2019.9.0 extension.

Specifically, once the active line in the terminal has reached the bottom of the terminal window, it fails to wrap and the keystrokes overwrite the prompt. 

Visiting the history using up and down does print the line with the correct wrapping.

Moving the cursor left past the newline causes the cursor to appear on the right of the same line, not at the end of the line above. 

Tab completion  reprints lines unexpectedly, and attempting to use the backspace to affect text in the line before the line break causes a new lines to be generated printing the text to the right of the cursor on each new line per backspace keypress.

It's feels like a terminal emulation problem - something doesn't know how to deal with newlines and the bottom of the terminal.  This only occurs in a Powershell Terminal, not the bash terminal, and not in a stand-alone pwsh session in a gnome or xterm.

I've no extensions other than the Powershell extension. 

Any advice would be gratefully received.

**Comment by Tyriar** [comment]
@WembleyFord2 does this happen in gnome-terminal?

**Comment by WembleyFord2** [comment]
No, only in Visual Studio code.

**Comment by WembleyFord2** [comment]
I've just tried installing VSCode, via the .deb package, and the latest Powershell from the MS repositories onto a new Ubuntu installation and I see the same behaviour.

**Comment by Tyriar** [comment]
Everything seems fine to me, I'm guessing it's an issue with the powershell extension?

![pwsh](https://user-images.githubusercontent.com/2193314/67313620-1da4a500-f4b8-11e9-9245-7670ec3b1016.gif)
