### ISSUE TITLE
Snippet with choices not working

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#83086]
Issue Type: <b>Bug</b>

Using a custom-made snippet that had a select menu which used to work fine:
```
  "DS Version Badge": {
    "prefix": "ds-versionbadge",
    "body": "<app-version-badge type=\"${1|added,updated,deprecated,removed|}\" version=\"${2:6.0.0}\"></app-version-badge>",
    "description": "Adds a version badge component."
  },
```

Invoke the snippet.  The first item is highlighted which is the dropdown with `added,updated,deprecated,removed`.  Choose anything  but the first item.  The one you chose _and_ the first item are added, which make the snippet useless. I have several snippets like this and they all do this now.

It used to work fine. Not sure when it broke..

![CleanShot 2019-10-22 at 12 56 45](https://user-images.githubusercontent.com/835148/67310524-eb04a780-f4cb-11e9-956a-d7445099c82a.gif)

VS Code version: Code - Insiders 1.40.0-insider (c58aaab8a1cc22a7139b761166a0d4f37d41e998, 2019-10-22T05:25:41.549Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_761083302|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
ng-template|Ang|0.802.3
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.3
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
auto-rename-tag|for|0.1.0
html-slim-scss-css-class-completion|gen|1.5.20
svg|joc|1.0.2
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
vscode-scss|mrm|0.6.2
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|0.24.0
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
rewrap|stk|1.9.1
sort-lines|Tyr|1.8.0
vscode-icons|vsc|9.4.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
May be related to https://github.com/microsoft/vscode/pull/82349

**Comment by jrieken** [comment]
Will be fixed via https://github.com/microsoft/vscode/pull/83075

**Comment by jrieken** [comment]
fixed
