### ISSUE TITLE
Add [Dollar], [Percent], [Plus], [Star] to the accepted scan codes

### ISSUE THREAD

**Issue by 3v1n0** [microsoft/vscode#83087]
I'd like to have `Alt+$` to go to the end of the line (similar to vim), but as per https://code.visualstudio.com/docs/getstarted/keybindings there's no `[Dollar]` key scan code translation and same for other common mentioned ops

**Comment by alexandrudima** [comment]
The values for scan codes (https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-layoutindependent-bindings) come from a spec -- https://developer.mozilla.org/en-US/ocs/Web/API/KeyboardEvent/code/code_values ... Scan codes refer to physical keys and not to produced characters...
