### ISSUE TITLE
extensions have split editor button which doesn't make sense

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8308]
![screen shot 2016-06-28 at 12 36 09](https://cloud.githubusercontent.com/assets/1794099/16412514/f0c1b636-3d2c-11e6-9c1f-2e4a32f32fe4.png)

**Comment by isidorn** [comment]
Agree - not cruical - moving to july and joao

**Comment by joaomoreno** [comment]
@bpasero Any way to remove it?

**Comment by bpasero** [comment]
@joaomoreno yes you can override it here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L127
