### ISSUE TITLE
Command Palette key shortcut not working on Windows when there are several keyboard layouts installed.

### ISSUE THREAD

**Issue by studiosi** [microsoft/vscode#83081]
- VSCode Version: 1.39.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install several keyboard layouts on Windows, the keyboard layout selector should appear next to the clock on the bar at the bottom of the desktop.
2. Open VSCode
3. Try to open the Command Palette by pressing CTRL+SHIFT+P

CTRL+SHIFT triggers the keyboard layout change on Windows, and the chord does not open the command palette as expected.

Maybe (untested) all the chords that use CTRL+SHIFT+* are affected, I could not test all of them exhaustively.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I think Windows can be configured to disable this. There is nothing we can do in VS Code if the OS is not sending keybindings to us.

**Comment by studiosi** [comment]
So the solution is to change the behavior of the host OS?

I wonder how people in corporate environments without access to an admin account are gonna deal with this. 

Amazing.

**Comment by alexandrudima** [comment]
@studiosi First hit when I search for "Windows ctrl shift"

https://superuser.com/questions/109066/how-to-disable-ctrlshift-keyboard-layout-switch-for-the-same-input-language-i

![image](https://user-images.githubusercontent.com/5047891/67340228-38fdc780-f52d-11e9-9290-7301e2363113.png)

Note how that has nothing to do with VS Code.
