### ISSUE TITLE
Intellisense suggests invalid path when defined baseUrl in jsconfig|tsconfig

### ISSUE THREAD

**Issue by onka13** [microsoft/vscode#83088]
Case 1; No baseUrl and paths in tsconfig;

- All url will be relative. So I want to use "common" prefix for commonlibs files.

Case 2; Define baseUrl and paths;

- intellisense working fine for files in same folder, parent folder and commonlib. 
- however up to 2 level parents intellisense suggests wrong path.  

- VSCode Version: 1.39.2
- OS: Win x64-10.0.18362

![image](https://user-images.githubusercontent.com/11014350/67310961-5ddf4400-f507-11e9-8204-4680ed3a07ed.png)

Correct;
```
import Test1 from "../test1";
import Test12 from "./test12";
import CommonLibA from "common/folderA/commonLibA";
import CommonLibAA from "common/folderA/folderAA/commonLibAA";
```

Wrong;
```
import Test2 from "src/folder2/test2";
import Test22 from "src/folder2/folder22/test22";
import Test0 from "src/test0";
```

Files in same project imports should be relative paths.

```
import Test2 from "../../folder2/test2";
import Test22 from "../../folder2/folder22/test22";
import Test0 from "../../test0";

```

I've created a sample project.
[https://github.com/onka13/vscode-tsconfig-bug](https://github.com/onka13/vscode-tsconfig-bug)

**Comment by mjbvz** [comment]
Thanks for the example project. However I don't understand what is going wrong. 

Can you please provide:

* Steps to reproduce the problem in the example project
* An explanation of the expected behavior
* An explanation of the actual behavior

Thanks

**Comment by onka13** [comment]
@mjbvz Thank for reply.

-> 1. scenario
1. Go to test11.ts file.
2. Try to import test2 or test22 file. (using intellisense ctrl+space)
3. You will see the path like this;
import Test22 from "src/folder2/folder22/test22";
So path is invalid. There is no "src" prefix defined in tsconfig. 

The path should be relative;
import Test22 from "../../folder2/folder22/test22";

-> 2. scenario
1. Go to test11.ts file.
2. Try to import test1.
3. So path is ok. No problem.
import Test1 from "../test1";

**Comment by mjbvz** [comment]
Your tsconfig sets `"baseUrl": "./",`. BaseUrl is resolved relative to the location of the tsconfig file, so all non-relative imports will start at the root of `my-project` (and therefore include the `src` prefix). 

If you don't want `src` included in non-relative imports, just set `"baseUrl": "./src"`.

You can also force TS to always use relative imports by setting `"typescript.preferences.importModuleSpecifier": "relative"`

**Comment by onka13** [comment]
@mjbvz Thanks for your explanation.
As default with no tsconfig; In my project all paths are relative. This is vs code default behaviour.
Additionally I just want to use commonlibs folder with "common/" prefix.

So is this possible?
