### ISSUE TITLE
Problem saving

### ISSUE THREAD

**Issue by JesseLevesque** [microsoft/vscode#83099]
Issue Type: <b>Bug</b>

When saving, it will sometimes errase the last bit of code since last being saved.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
debugger-for-chrome|msj|4.12.0
LiveServer|rit|5.6.1

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by JesseLevesque** [comment]
I executed the code and tested vs code but I'm still getting the issue that trying to save erases the previous input.

**Comment by JesseLevesque** [comment]
I'm not sure what other info you would need, I'm new to my computer science program. I noticed that the extension Debugger for Chrome offers a temporary fix. I tried to send a video but it seems to be too big to send on GitHub.



![Capture](https://user-images.githubusercontent.com/56256707/67393646-cc0c2100-f570-11e9-953a-36946098aa29.PNG)

![Capture2](https://user-images.githubusercontent.com/56256707/67393664-d4fcf280-f570-11e9-8288-71297e87ec20.PNG)

**Comment by bpasero** [comment]
@JesseLevesque no worries, what i asked for is more exact steps how to reproduce. What file are you typing in what are your settings. What is open in browser?

**Comment by JesseLevesque** [comment]
So when I type out code (or erase) and save, then open in live server or refresh an open live server, it reverts to a previous save. It does this in both HTML and CSS files. The drive I'm using is a school H drive. The only websites open in my browser are my school website, outlook and the live server.

**Comment by bpasero** [comment]
@JesseLevesque so would you agree that "Live Server" is an extension that might trigger this? Do you see the text getting removed when you type and save without using any extension?

**Comment by JesseLevesque** [comment]
Possibly. I can't seem to open my HTML in the browser without live server and using live server currently is a requirement in my course. Me and one other student have this problem but the whole class uses live server.

**Comment by bpasero** [comment]
@JesseLevesque to clarify:

> When saving, it will sometimes errase the last bit of code since last being saved.

This only surfaces when you try things out in the HTML live server right, not in the editor?

**Comment by JesseLevesque** [comment]
After I save, it's still there but once I go to the live server to test the HTML page and come back after to vs code, it reverts back to a previous save. This affects both my HTML and CSS code.

**Comment by bpasero** [comment]
@JesseLevesque do you also see this when Live Server is not involved?

**Comment by JesseLevesque** [comment]
Without live server, it doesn't let me open the site using the path so I'm unable to verify this. The other student that is also having this problem with VS code can open using the path and his VS code does the same issue with saving with or without live server.

**Comment by bpasero** [comment]
@JesseLevesque I am sorry, but I suggest you look into reporting this issue against that extension to get further.
