### ISSUE TITLE
Unnecessary indent after source tag in html

### ISSUE THREAD

**Issue by mohsennirouzad** [microsoft/vscode#83092]
Issue Type: <b>Performance Issue</b>

in the beggining of a line following an HTML5 tag of source an additional indent is added. Considering the fact that when closing the tag in the old way (< />) the problem is solved, it is probably an HTML5 incompatibility issue.

Since I have problem embedding a picture, here is an imgur of it:
https://imgur.com/a/LYlyrRU

VS Code version: VSCodium 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-12T10:46:51.689Z)
OS version: Linux x64 5.2.0-2parrot1-amd64

**Comment by octref** [comment]
This is intended — when you have self-closing tag VS Code stays on the same level. Otherwise it indents.

**Comment by mohsennirouzad** [comment]
That is the problem. VSCodiom does not stay on the same level after the `<source>` tag, but it indents. Look at the pictures in my question.

**Comment by octref** [comment]
Yes, VS Code doesn't do indentation by HTML semantics, but by its syntax. So irrelevant of what's inside `<>`, if it's not closed with `/>`, VS Code indents.
