### ISSUE TITLE
Automatic --signoff via settings

### ISSUE THREAD

**Issue by bnb** [microsoft/vscode#83096]
It seems that presently, you can use the `-s` or `--signoff` command on your git commits by opening up the git commit dropdown and selecting signoff. This was implemented as a "fix" for #7010 in #10410.

However, there doesn't seem to be a setting within VS Code itself that enables end-users to enable this feature as a part of their git commit messages by default without taking those extra steps of opening a dropdown and selecting the right option.

Given the prevalence of the [Developer Certificate of Origin](https://developercertificate.org/) and it's hard requirement of the -s flag in massive open source projects projects like Node.js, Helm, Prometheus, and Moby, it would be super awesome to have the ability to turn this on as a setting in VS Code.

**Comment by joaomoreno** [comment]
The setting is `git.alwaysSignOff`

![image](https://user-images.githubusercontent.com/22350/67377682-59a63b80-f586-11e9-8e80-a07757c976a9.png)
