### ISSUE TITLE
Automatic breakpoint and logpoint for 'On Enter Function' in debug

### ISSUE THREAD

**Issue by rubengmurray** [microsoft/vscode#83095]
_I've searched around the repository for this and couldn't find a request similar, which surprised me, so apologies if one exists. I searched for: `debug, every, function, breakpoint, dynamic, logpoint, log and enter` in various combinations._

### Suggestion
I'd really like to be able to get the debug feature to dynamically break and / or log on every function that is called within a particular function, nested through the whole chain until the initial function returns.

At the moment it seems this behaviour is limited to breaking on a function only when its name is known, and that's only breakpoints, not logpoints.

 I currently have to go through the various parts of the code that a particular function may call - and those that the nested functions may call - manually adding break points at each stage.

### Use Cases
I want to trace and log out state at every function call along with the function name & location, rather than going through multiple files and manually marking each function.

This would also allow one to map a particular functions path across a code-base for generally faster debugging.

### Notes
I believe this functionality already exists in other version of Visual Studio such as VS for Mac as referenced in this comment: https://github.com/microsoft/vscode-node-debug2/issues/163#issuecomment-365570247 ?

**Comment by isidorn** [comment]
If I undestand correctly you are asking for function breakpoints? However we already support those https://code.visualstudio.com/docs/editor/debugging#_function-breakpoints

We do not support adding log statments to function breakpoints atm. And I think there is already a feature request for this.

Also assigning to @weinand

**Comment by rubengmurray** [comment]
I am looking for something more than the current 'function breakpoints'.

From what I understand, every functionName needs to be entered manually into the debugger for it to break on it. I am asking that the debugger recognise when the code path enters a new function, and breaks at the point (actually if I had to choose between breakpoint and logpoints for this request, I'd rather these were logpoints).

**Comment by isidorn** [comment]
So you want like a wildcard function breakpoint.
Also you want the function breakpoint to turn into a logpoint (which the protocol does support but we just do not surface in the UX)

**Comment by weinand** [comment]
You are asking for a feature that creates a dynamic call graph of your program.
Typically this is done via some "trace" functionality of the runtime or by instrumenting the code before running it.

It is out of scope for VS Code.

**Comment by rubengmurray** [comment]
Hi Weinand,

I'm looking for a feature that allows me to use the debugger option more easily / find bugs quicker. Debugging legacy code that travels all over the place is obviously time consuming.

I do understand why in isolation this could be considered 'out-of-scope' for a code editor, but then again, this code editor has a feature called 'debugger', so i'm curious why this feature in particular would be considered out of scope?

Even if I had the dynamic call graph, I'd have to go and add all the breakpoints in manually.

It also exists in other version of VS (apparently)?

In any case, thanks for the attached PDF, i'll have a read.
