### ISSUE TITLE
typescript language service suggest incorrect informations

### ISSUE THREAD

**Issue by falsyvalues** [microsoft/vscode#83097]
- VSCode Version: 1.39.2 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Enter following snippet from [typescriptlang.org](http://www.typescriptlang.org/play/#code/KYOwrgtgBAkgCgS2AY2FA3gKCj2ATKAXigCIE8SAabXAMQQCcBnAFwDkBDCNYkgM0asQXYFRo4AMh1aduRUgBtpLYdzG4oAQQDmPUh10lMAX0yYEIFsAZ8OqWIhTA41pgHsQGcVADa8JKgAdDB4ALoAXFCsDBbaUAA+UOAKCgDc3n6OQfTM7CIRUSwxIHGJyWkZ-k6BUjL5kdGxCUlgKekamQHAgTrABeAQAEbWzeXppph8YCDILAgeULosWc6uHgA8ACpQwAAeViB4TA5dAHwAFAAOXZHbiZs+oQCUkYjIANbrVaguzB6UUE2py8GmQHlYUGuTmOxHOjyg0kBjyegTBMw4LCuXSe6W8aIhlzWIEi31Wf08xCwGg05EiJAAjOpqTgBLlVMA6ayhCImcylNzuHT+SoedRmTgDByoABmAAM3mMuI0DGALDADE8UNQTECKrwYFQ6zen1Jv3cIABQIuVwBWuAISeRGBVPFKrVGsh7VwxltRJxJjM+JYUDc8iWKzNHnOpJ6un9bkCQA) to editor

2. Trigger suggest `control + space`

<img width="677" alt="Zrzut ekranu 2019-10-19 o 07 52 27" src="https://user-images.githubusercontent.com/1199350/67138560-9e0f9f80-f245-11e9-9100-f5579f733937.png">

**Expected behaviour:**
```typescript
age
```
**Current behaviour:**
```typescript
IPiece enum
```

~~Does this issue occur when all extensions are disabled?: Yes/No~~

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project and the website also shows the incorrect behavior (the suggestion for `Age` is just a word based suggestion, not intellisense). Please [file the issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
