### ISSUE TITLE
 TypeError: Cannot read property 'getRangeFromSpan' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#831]
Issue Id: <b>38ef9451-7d4b-2f2f-e705-51738c6590ba</b><br /><br />*Versions* <br />- 0.10.2<br />-  df352367df2efcfa9d602d471e4e2f42140a0f05<br />*Stack* <br />TypeError: Cannot read property 'getRangeFromSpan' of undefined<br />[/vs/languages/typescript/common/features/definitions.ts#L34:54 (findDeclaration)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/languages/typescript/common/features/definitions.ts#L34:54 (findDeclaration))<br />[/vs/languages/javascript/common/javascriptWorker.ts#L156:27 (JavaScriptWorker._findTypeScriptDeclaration)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/languages/javascript/common/javascriptWorker.ts#L156:27 (JavaScriptWorker._findTypeScriptDeclaration))<br />[/vs/languages/typescript/common/typescriptWorker2.ts#L237:14 (TypeScriptWorker2.findDeclaration)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/languages/typescript/common/typescriptWorker2.ts#L237:14 (TypeScriptWorker2.findDeclaration))<br />[/vs/languages/typescript/common/typescriptMode.ts#L484:31 (TypeScriptMode.findDeclaration)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/languages/typescript/common/typescriptMode.ts#L484:31 (TypeScriptMode.findDeclaration))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />[/vs/editor/common/modes/abstractMode.ts#L122:35 (AbstractMode._worker)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/editor/common/modes/abstractMode.ts#L122:35 (AbstractMode._worker))<br />[/vs/languages/typescript/common/typescriptMode.ts#L484:14 (TypeScriptMode.findDeclaration)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/languages/typescript/common/typescriptMode.ts#L484:14 (TypeScriptMode.findDeclaration))<br />[/vs/platform/thread/common/workerThreadService.ts#L89:16 (WorkerThreadService.OneWorker)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/platform/thread/common/workerThreadService.ts#L89:16 (WorkerThreadService.OneWorker))<br />[/vs/platform/thread/common/threadService.ts#L69:35 (OneWorker)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/src/vs/platform/thread/common/threadService.ts#L69:35 (OneWorker))<br />[vs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete)](https://github.com/microsoft/vscode/blob/7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066/srcvs/base/common/worker/vs/base/common/winjs.base.raw.js#L1826:0 (onComplete))<br />

**Comment by jrieken** [comment]
Code is gone
