### ISSUE TITLE
Option for putting curly brackets on "new line" after method declaration for C#

### ISSUE THREAD

**Issue by natemakesgames** [microsoft/vscode#83105]
I would appreciate an option for putting curly brackets on "new line" after method declaration. This seems to exist in the options for JavaScript but not C#. Other people have requested this, but the developers seemed to say that it is "out of scope" of the project.  If users want it, then it's time to increase the scope! :) Thank you.

**Comment by alexr00** [comment]
This would need to be implemented in the C# extension since VS Code doesn't have more then syntax highlighting for C# built in.
