### ISSUE TITLE
VScode internal terminal not working

### ISSUE THREAD

**Issue by AkshitAggarwal** [microsoft/vscode#83100]
Issue Type: <b>Bug</b>

The internal terminal in my vscode running on an Ubuntu 18.04 suddenly stopped working. The terminal window has turned blank and nothing can be typed. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 3060)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|7.48GB (4.59GB free)|
|Process Argv|--force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.0.28
pop-n-lock-theme-vscode|Lux|3.18.4
vscode-clang|mit|0.2.3
python|ms-|2019.10.41019
cpptools|ms-|0.26.0
material-icon-theme|PKi|3.9.1
vscode-icons|vsc|9.4.0
clang-format|xav|1.9.0

(2 theme extensions excluded)

</details>

**Comment by kewellcjj** [comment]
Same issue on linxu, I think happened after the recent update.

**Comment by kewellcjj** [comment]
The issue exists when I launch vscode from Docklets (Dock or Plank or whatever). It works fine by typing ```code``` in the terminal or just launch from my system default menu. Not sure if @AkshitAggarwal has the same issue.

**Comment by Tyriar** [comment]
Enable trace logging to see where it's failing: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by J370** [comment]
Had this issue as well on Ubuntu after the update.

However, terminal appears again when launching through terminal with `code` command.

**Comment by AkshitAggarwal** [comment]
The issue got resolved after clearing JSON in settings.
