### ISSUE TITLE
Logpoint does not work while debugging vscode project/repo

### ISSUE THREAD

**Issue by Ragnoroct** [microsoft/vscode#83106]
- OS Version: Windows 10 Version	10.0.17763 Build 17763
- VSCode Version: 
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Clone vscode repo
2. yarn (to build)
3. yarn watch (to build tsc)
4. .\scripts\code.bat
5. Open extensions/html-language-features/server in new vscode window
6. Attach to running dev instance html language server with F5 (attach)
7. Set logpoint with asdf in htmlServerMain.ts:265
8. Go to dev vscode instance running, set language to html and start typing to trigger autocomplete

What I see: Nothing

What I expect: To see asdf in the debug console of the vscode instance doing the debugging.

I tested breakpoints and that works.

**Comment by isidorn** [comment]
Putting logpoints when debugging vscode works just fine for me.
However your case might be special since you are putting logpoints in the extensino host, thus assigning to @roblourens since the issue seems to be on the adapter side.

**Comment by roblourens** [comment]
You are putting logpoints in a language server, does `console.log` work in the same place? Logpoints literally just add a `console.log`.

**Comment by Ragnoroct** [comment]
I haven't tried adding a console.log yet. I did try adding a breakpoint. I was able to hit breakpoints in the same spot where the logpoint did not work.
