### ISSUE TITLE
Too much empty space between terminal header and first line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8310]
#8222 

@Tyriar all the bugs I file are on mac and insiders vscode.

IMHO there is too much space between the terminal header and the first line, I would expect this to be more compact - especially since most of the time the vertical space is very limited.

![screen shot 2016-06-28 at 12 45 04](https://cloud.githubusercontent.com/assets/1926584/16412760/4da9ad3a-3d2e-11e6-82ed-82729399b72b.png)

**Comment by Tyriar** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/8219, https://github.com/sourcelair/xterm.js/issues/149

**Comment by Tyriar** [comment]
Closing in favor of #8219, there typically be a gap as the terminal is aligned to the bottom, it would look wonky if it was aligned to the top too and resizing would look even worse imo. Verifying all lines/characters are the same height in #8219 will make the row/col calculation fit as good as possible.
