### ISSUE TITLE
Placeholders get not replaced if the variable is used more than one time

### ISSUE THREAD

**Issue by MrTango** [microsoft/vscode#83107]
Version: 1.40.0-insider
Commit: c58aaab8a1cc22a7139b761166a0d4f37d41e998
Date: 2019-10-22T05:27:42.088Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.0-6-amd64- 

Steps to Reproduce:

1. use a snippet with a variable (placeholder used in two places)
2. when you type it should replace the placeholder text, which works as long as the variable is used only once, but not if it is used more than that.

You can try it with https://marketplace.visualstudio.com/items?itemName=Derico.plone-vs-snippets by adding a "plonechoicefield"

**Comment by jrieken** [comment]
```
    "Choice Field (plone.schema)": {
        "body": [
            "# Make sure to import: plone.app.vocabularies as vocabs",
            "${1:name} = ${2:schema.Choice}(",
            "    title=_(",
            "        u'${3}',",
            "    ),",
            "    description=_(",
            "        u'${4}',",
            "    ),",
            "    vocabulary=${5:u'vocabs.PortalTypes'},",
            "    default=u'${6}',",
            "    # defaultFactory=${7:get_default_${1}},",
            "    required=${8|False,True|},",
            "    readonly=${9|False,True|},",
            ")"
        ],
        "prefix": "PloneChoiceField"
    },
```

Assuming you mean 🔝 that snippet and placeholder `$1` than I have to say that I cannot reproduce. Please clarify what you expect, tho a confusion might be that the second occurrence of placeholder 1 is enclosed by placeholder 7 and therefore typing 7 will overtype 1

**Comment by MrTango** [comment]
I have a simple version where i can see the same issue. It only occurs when you use a placeholder.
![vscode_snippet](https://user-images.githubusercontent.com/1113628/68947853-c7750a00-07b6-11ea-8e64-2758a1f0aca8.png)
![vscode_bug](https://user-images.githubusercontent.com/1113628/68947854-c7750a00-07b6-11ea-9ccd-7a6c0a53819a.png)
