### ISSUE TITLE
zsh: segmentation fault (core dumped)  when running a python file with only import statements

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode#83115]
Issue Type: <b>Bug</b>

I'm getting seg fault memory errors even though I'm only using 2.56/7 GB of memory and I have over 1Gb of swp memory available. The python file I'm running is only running import statements. I'm using the most recent version of VScode. Below is the error

```
 rave at rave-thinkpad in ~/pyMETRIC on git:xarray-lazy ✖︎ [16:40:30]
→ /home/rave/miniconda3/envs/METRIC/bin/python /home/rave/pyMETRIC/pyMETRIC/PyMETRIC_xarray.py
zsh: segmentation fault (core dumped)  /home/rave/miniconda3/envs/METRIC/bin/python 
(base) 
```

The imports that cause the fail are

```
# import pyTSEB.meteo_utils as met
# import pyTSEB.resistances as res
# import pyTSEB.MO_similarity as MO
# import pyTSEB.TSEB as tseb
```
I can import these in a jupyter notebook. The pyTSEB package was installed with setup.py from here: https://github.com/hectornieto/pyTSEB

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.08GB (2.56GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.1
Python-autopep8|him|1.0.2
terraform|mau|1.4.0
vscode-azurestorage|ms-|0.7.2
vscode-azureterraform|ms-|0.2.4
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
vscode-ai|ms-|0.6.6
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-ssh-explorer|ms-|0.47.1
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
azurerm-vscode-tools|msa|0.7.0
vetur|oct|0.22.5

</details>

**Comment by rbavery** [comment]
solved by `conda install pyopengl`

**Comment by rbavery** [comment]
This actually only solved the issue for pycharm and I assumed it would work for vscode (pycharm was having the same segfault error with the same steps). But the segfault issue is still present in VScode, so I'm re-opening.

I tried to follow these instructions for linux: https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues , but they don't look up to date, I can't run `gdb` on my code executable located at `usr/bin/code` and I'm not sure where `code-oss` is or if it exists on my system.

**Comment by alexr00** [comment]
This sounds like an issue with your project, not with VS Code since you say you are running a python file.
