### ISSUE TITLE
Text color from wsl into integrated terminal is reversed

### ISSUE THREAD

**Issue by mark-hahn** [microsoft/vscode#83120]
Issue Type: <b>Bug</b>

When I run wsl from cmd.exe everything works as expected.  When I run wsl in the vscode integrated terminal the colors are reversed. 

![Annotation 2019-10-22 200528](https://user-images.githubusercontent.com/811455/67353406-5750cc80-f507-11e9-80d4-706ecf1c5310.png)

I have tried changing workspace themes and I tried this in `settings.json` ...
```
"workbench.colorCustomizations": {
      "terminal.background":          "#fff",
      "terminal.foreground":          "#000",
      "terminal.ansiBlack":           "#fff",
      "terminal.ansiWhite":          "#000",
      "terminal.ansiWhite":          "#000",
      "terminal.selectionBackground": "#fff",
      "terminalCursor.background":    "#fff",
      "terminalCursor.foreground":    "#000"
    },
```

I didn't have this problem until I had to do a fresh install on a new computer.  It worked fine for months. 

Any suggestions?

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (11.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by mark-hahn** [comment]
I've tried winpty and conpty with no luck.  WSL is unusable at the moment because large portions have unreadable colors.

I used WSL in vscode for some time with no problem.  Are you sure nothing has changed recently?

I guess I could try reloading everything from scratch.

**Comment by Tyriar** [comment]
@mark-hahn your version of Windows 10 doesn't support conpty even if you use the setting, it needs 18309+. The fix here is to upgrade Windows 10.

**Comment by mark-hahn** [comment]
Thanks.  That fixed it.

I didn't think my new laptop would have an older windows than my previous laptop.

**Comment by Tyriar** [comment]
Good to hear 🙂
