### ISSUE TITLE
Not possible to open command pallete from terminal by F1

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8312]
#8222

There is not way to open the command pallet from within the terminal using the F1 key.
This is especailly troublesome since some of the terminal commands are in the command pallete, so optimally I could F1 > focus next terminal...

I can open quick open from within the terminal by cmd + E, but F1 seems to be ignored

**Comment by Tyriar** [comment]
Dupicate of https://github.com/Microsoft/vscode/issues/7269, @isidorn interested in your thoughts on this if you use <kbd>F1</kbd>. If think the eventual solution to this is being able to tell the terminal which keystrokes to not pass to the terminal, it could be a bit tricky to do though.

**Comment by isidorn** [comment]
@Tyriar yes I use F1 and I can see that some of our users do too, so we should look into a solution to this problem. The issue is that user can have custom keybindings so it becomes more tricky. Though sometimes that covers the 90% case should be fine in this case imho
