### ISSUE TITLE
High load & CPU Usage 99% where use remote-ssh.

### ISSUE THREAD

**Issue by alansplaza** [microsoft/vscode#83126]
版本: 1.39.2
提交: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
日期: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. Install remote-ssh, ssh to the remote linux.
2. Wait and the linux load will increase and cpu usage can reach to 99%.

Does this issue occur when all extensions are disabled?: Yes/No
Haven't try this.

Please help fix this, Thanks.

**Comment by roblourens** [comment]
Please try this with `--disable-extensions` to check whether it's an extension.

You are talking abou tthe CPU usage on the remote, not the local machine, right?
