### ISSUE TITLE
Debug - GUI changes

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#83129]
Hi,

We need change here some things in my opinion.

**Part.A**
Eg. in Python when runing `Debug` mode then VSC opening "pop-up" GUI with btns `pause` .. `stop` to move this in any place. This is stupid in my opinion and made disonanse.
Eg. in Python are "enviorments" like ` "name": "Python36 Django",` and we see in Debug `Python36 Django` in combolist that is not so usable view in fact that we not changing env soo often maybe, and this information is not needed. Soo.. in the label of env can be all "pop-up" GUI maybe. 
This can be replaced as if not debuging then we see label and when debugig the btns are visible.
Then icon as "::" to move is not needed maybe and can offer more place for other icons. 
In the settings of VSC can be options as "old method" with `"dynamic pop-up"` or `static pop-up` or contex menu for this as `detach` to "pop-up GUI" and then turn back "::".

1. "pop-up" GUI in `env-name`
2. detach for `debug tool` "pop-up"
3. option to easy managment of `debug tool` by extensions as API

**Part.B**
I'm always angry in debuging that often don't know what was previous in errors/log and current state - I mind compare the current state and previous before changes in code and after results. I expecting something that can allow show old errors that was solved and not exist after changes. It's not so easy manage this with #git but maybe need some support here (as sugestion for me, users) or for VSC ext for git - can conect this functions/feature for both (debug and git managment). 
The "logToFile": true, must be dedicated for unique projects and laguages. What this mind.. that some of plans to debug should be as named logs maybe to history (e.g. for git as `.logs`). Why? Some tracebar logs can be similar with some changes, other totaly diffrent. Maybe related with files that have code with bugs? Then logs can be as name_datetime and the prefixes can be compareated?

Other problem that new case of debuging clearing previos tracebar log.
Some `event datetime` belt in dock of debuging can be usefull as back to previous date/time of debug logs and compare, see some differences, `time of executions` - compare this summary.

As in "btw" part of issue https://github.com/microsoft/vscode/issues/83127 there is often in code language problems to spy place of error from tracebar like line/cols (I mind click line and move to this part of code/file not working) - in some langs works in other not (this is not first IDE that made this experience). 
https://github.com/microsoft/vscode/issues/26283

Other.. the no. of line errors.. I'm seek when see community citing part of errors not the numbers of them.. soo.. should exit option to paste tracebar with lines #no. after copy log with numbers.
I belive some standard as 1, 2, 3 and 1.1, 1.2, 1.2.3 as levels of erros intree of some clases.. Option to turn of lines if this idea is bad or copy without lines as old standard. Soo the numbers can help in comparations of logs.

Sometimes we need to plan some cases of debug with changes, this can be issue for attribution changes to debug plans (eg. TODO - TOCHeck, FIXCheck, FIXTest, Branch, GTAG).
Need this plan corelate and connect with git commints like "this plan" was tested and ok and this is here "some git part of changes" or something.
There are TODO exts but maybe should exist in debugs?

For example is hard to force in default debug functions for python djange due to many --arg https://github.com/microsoft/ptvsd/issues/1866
Soo we often ommiting access to `vars, watch, cal stack, breakpoints` features in VSC.

We must safe our time, respect target for progress of work.

1. Show solved errors/changes in tracebar log
2. Compare tracebar log
3. Numbers for lines for tracebar log
4. SubNumbers/Index for lines for tracebar log and tree elements
5. Settings for Numbers SubNumbers/Index
6. Management `debug events` as `datetime` log labels/tree - list/tree
- unique log names for files and for projects, languages
- commitments for logs files for git
7. Plans for Debug - the Git branch, tags
8. Shortcuts to show/hide  `vars, watch, cal stack, breakpoints` and `events/tracebar logs`, `notes` - as TODO, FIX separately (to accees to comfort area of workspace)
9. Some stats/summary after debug

**Comment by ManPython** [comment]
@isidorn soo.. the "gui-pop-up" as debug tool is extension?

**Comment by gjsjohnmurray** [comment]
> 
> 
> @isidorn soo.. the "gui-pop-up" as debug tool is extension?

@ManPython did you try "debug.toolBarLocation": "docked" ?

**Comment by ManPython** [comment]
@gjsjohnmurray now.. yes. Thx.. I missed this option. Should be setted as default.

**Comment by gjsjohnmurray** [comment]
> 
> 
> ...Should be setted as default.

Why?

**Comment by ManPython** [comment]
> 
> 
> > ...Should be setted as default.
> 
> Why?
Docked version is more comfy with this functionality due to the description of issue. By this option undocked has rarey ocasion to usage and made users confused with place to the friendly place.
