### ISSUE TITLE
New Outline 

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#83127]
What I need

1. Colapse all
2. Expand all
3. Colapse level of tree  (like in MS Word for heads/index)
4. Expand level of tree
5. Numbers of outlines
6. Follow code - outline replicate state of colapese or expand functions in code by arrows
7. Searching contex - in outline for functions, clases to easy and quick access to element and click (need magnifier icon in next to "Collapse all"). 
- similar in explorer, open editors
6. Sumary - how much of main elements are in outline (not sure how to solve in relation to levels)
- can be show/hide belt for all as small tree 
- can be in brakets near elements [1/2/3]
7. Managment to hide/show explorer and outline by friendly shortcuts

3,4 as context menu on all outline or some part of tree element
BTW the indention line for tree looks poor (as to near to elements and not separating levels enough clear in my opinion) like in explorer.
BTW2 I'm looking some stats for git.. eg. how many lines was changed, added, how many LOC in all code, LOC for code typy (.js .py .sql), how many new files or deleted, maybe charts for this. Not sure that is feature for ext #gitlens

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ManPython** [comment]
@jrieken this probly need more reflections and decisions about changes. Hope that I should not wire story lines or epic as PO.. we all here coders probably?

**Comment by jrieken** [comment]
The ask was to file one issue per feature request or to clarify what this issue is about. We don't accept collective feedback items in the style of: "I want this, that,  and also the other thing". That's doesn't match well on how our team in organised make it easy to loose things.

**Comment by ManPython** [comment]
Thats why Microsoft developing often sh*t.. : )
We can not be procedural in any case with details if are clarified for users of product.
I listed missed functions that can be usfeul and was added as feature not bug. Soo.. what is problem?
