### ISSUE TITLE
Implement revised issues triaging flow

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#83125]
Steps to implements the flow revised in https://github.com/microsoft/vscode/issues/83124.

- [x] Create **`Backlog Candidates`** milestone
- [ ] Create `wont-fix` label
- [ ] :runner: Implement bot that assigns the **`Backlog Candidates`** milestone to issues with no milestone 2 minutes after they receive the `feature-request` label
- [ ] :runner: Implement bot that comments on `feature-requests` that are newly assigned to the **`Backlog Candidates`** milestone
- [ ] :runner: Implement bot that monitors `feature-requests` assigned to **`Backlog Candidates`** for upvotes and assigns those to **`Backlog`**

**Comment by tamuratak** [comment]
Some issues with more than 20 up-votes have been assigned as `Backlog Candidates`, not as `Backlog`. See [link](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22Backlog+Candidates%22+sort%3Areactions-%2B1-desc).

Sorry in advance if this is not the right place to report. I am a big fan of #1751.
