### ISSUE TITLE
Inline breadcrumbs show arrow icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83138]
<img width="1018" alt="Screenshot 2019-10-23 at 11 29 35" src="https://user-images.githubusercontent.com/1794099/67378983-6a57b100-f588-11e9-8780-23c0b4ebbc85.png">

This must have slipped the review but when not using editor tabs, breadcrumb elements should not show arrow icons as they already show paths

**Comment by misolori** [comment]
Fixed and also tweaked the padding of the symbol icons in the no tab view:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/35271042/67423728-a17a9200-f589-11e9-94df-208a1da3f298.png">

**Comment by jrieken** [comment]
Thanks
