### ISSUE TITLE
Integrated terminal auto completaion produces bogus prefix

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8313]
#8222

1. Open vscode repo, open terminal
2. type 'sc' press tab
3. I get scsc as result and can not delete the first sc

Most of the time I use completion in the integrated terminal I get some bogus prefix rendered

**Comment by Tyriar** [comment]
@isidorn what OS and shell are you using?

**Comment by isidorn** [comment]
All my issues are OS X, shell oh my zsh
https://github.com/robbyrussell/oh-my-zsh

**Comment by Tyriar** [comment]
Seems fine on Linux

**Comment by isidorn** [comment]
@weinand can also reproduce on his mac but only for zsh. For regular shell it works fine

**Comment by Tyriar** [comment]
Looks like this is actually a duplicate of https://github.com/Microsoft/vscode/issues/6793
