### ISSUE TITLE
Intellisense undo

### ISSUE THREAD

**Issue by paweston70** [microsoft/vscode#83131]
Issue Type: <b>Feature Request</b>

One of the main issues I have with this implementation of intellisense is the back-out plan - if I use tab after any word with an intellisense suggestion, I get it whether I want it or not - backspace and retabbing just applies the same suggestion; I have to use escape to get out of the suggestion, which feels a little unnatural.

One method to get around this is the mobile keyboard method, wherein, if you don't want the suggested auto-correct option, pressing backspace reverts the previously changed word to what it was previously, without removing the last typed character; so, if you type 'ban' and 'bananas' was suggested using intellisense, then tab is pressed (as this is the name of a variable I'm using, or whatever), the word expands to 'bananas<tab>'. Pressing backspace should then revert the word to 'ban<tab>'.

Note that some mobile keyboards keep track of which words have been expanded, so you can go back through the text and undo the changes. I don't expect the world, but this would be a fantastic feature to implement.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<!-- gener

**Comment by octref** [comment]
@pawelurbanski You can just use Cmd+Z to undo, can't you?

![demo](https://user-images.githubusercontent.com/4033249/67607751-6bc8db00-f73a-11e9-9f3e-6065cae83301.gif)

**Comment by paweston70** [comment]
Apologies - I haven't been around to look at this.

It's all to do with the flow of typing; backspacing is a more natural function of typing, rather than typing **Ctrl / Func + Z**.  Microsoft Word provides the functionality with its auto-formatting tools; for instance, if you type **1.** at the start of a line then press **Tab**, the line will be numbered, as per the command on the ribbon.  Pressing return at the end of the line will give the next number in the sequence, etc.  However, if you press backspace immediately after pressing **Tab**, the formatting is undone and reverts back to what it was.

**Comment by octref** [comment]
I think that behavior would be really hard for users to understand. Besides, it would be a rare case to regret right after taking an auto completion, so pressing a chord shortcut in that case seems fine for me.
