### ISSUE TITLE
VSC  --settings for settings.json

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#83132]
Regarding the issue https://github.com/microsoft/vscode/issues/20724
I expeting to set "universal" settings.json for all projects (where have many pythons, go, php, js, etc). Don't know how to do this as portable version. I using `--user-data-dir` and `--extensions-dir` whre are compiled to .exe shortcut from .bat to ommit cmd window.

I'm not convicted to `.vscode` for any project and setting this to `.gitingore`
For exmpale there is `"wolf.disableHotModeWarning": true` for `settings.json` that sitll is changes from true to false and made changes for .git soo.. don't know.. ignore all `settings.json` and `.vscode`.. use this.. not use.. 
In fact I duplicated `.vscode` folder for many many projects.. and when starting new often have problem to easy access to right env with these settings.

**Comment by sandy081** [comment]
Global settings are always supported. May I know if you do not see User Settings in VS Code?

**Comment by ManPython** [comment]
> May I know if you do not see User Settings in VS Code?

Not sure that I'm corectly understand this question. I using user settings.. I changing to customize VSC, but when opening new project folder or starting new project then all setings for enviorment is empty. I doing this wrong way? I using VSC portable version as .zip file without installation, but as I wrote using  --user-data-dir and --extensions-dir to ommit some issues when formating OS or using other.

**Comment by sandy081** [comment]
Sorry I do not understand what you mean by 

>  but as I wrote using --user-data-dir and --extensions-dir to ommit some issues when formating OS or using other.

Can you please explain why using `--user-data-dir` not solving this issue?

**Comment by ManPython** [comment]
> Can you please explain why using `--user-data-dir` not solving this issue?

Coz if I adding new dir to VSC with the project then VSC creating new `.vscode` in this dir with setting for env.. as in 1st post.

**Comment by sandy081** [comment]
Yes but the settings in user dir still get applied. Settings from `.vscode` can override the global settings if wanted.

**Comment by ManPython** [comment]
1. Not sure.. you talking about `settings` but  `vscode` have:
launch.json
settings.json
tasks.json

2. In `User` exist:
settings.json
syncLocalSettings.json
workspaceStorage
snippets
globalStorage

3. Should I copy these from 1 to 2? 
a) Specially `launch.json` and `tasks.json`?
b) Is this included procedure?

I think that is still misunderstanding in #83134 issue as local/global settings.

**Comment by sandy081** [comment]
Sorry, I am totally lost now. Can you please be clear and specific about the issue you are having in VS Code?

**Comment by ManPython** [comment]
Just want launch.json settings.json tasks.json as globaly for all projects that creating - without .vscode in any project dir.

**Comment by sandy081** [comment]
There is only global settings no global launch.json and tasks.json. You can have global launches in global settings.json just by adding your launch configurations using setting 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/10746682/69035754-a691fc00-09e4-11ea-9b91-04e7d23d15be.png">

And we are planning to support global tasks in this milestone.
