### ISSUE TITLE
Text in Problems view shifts when hovering over it if there are code actions available

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#83135]
In the problems view I have two similar entries like this:

<img width="525" alt="Screenshot 2019-10-23 at 9 48 35 am" src="https://user-images.githubusercontent.com/1078012/67375321-57d67b00-f57a-11e9-882f-5ee33d442617.png">

When I hover my mouse over one, the icon changes from a warning triangle to a lightbulb:

<img width="588" alt="Screenshot 2019-10-23 at 9 46 52 am" src="https://user-images.githubusercontent.com/1078012/67375230-3d040680-f57a-11e9-841b-fbb30174ef25.png">

It seems like the lightbulb is wider, and it causes the text to shift to the right (note that the word "Shadowed" no longer lines up across the two lines). I don't think this is intended - I think the text should be aligned correctly and not jump around as you move the mouse over the list.

**Comment by sandy081** [comment]
@misolori Not sure why an additional `2px` left margin was added. This is causing above mis-alignment. Removed it.
