### ISSUE TITLE
Search result 'show in Explorer' shows in side-panel

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#83139]
Issue Type: <b>Bug</b>

* Perform a search
* In the results panel, right-click a filename
* Select 'Reveal in Explorer'
* File is highlighted in the 'Files' side panel.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
cucumberautocomplete|ale|2.14.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.31.1
vscode-eslint|dba|1.9.1
vscode-scss-formatter|sib|1.4.2
perforce|sle|3.2.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
@leegee what you refer to as "the 'Files' side panel" is called Explorer. So the current behaviour of 'Reveal in Explorer' from a filename in Search results makes sense. But I can see it's confusing because when you then right-click on the filename that's been revealed in VS Code's Explorer, you get another 'Reveal in Explorer', and that one opens a **Windows** Explorer onto the folder containing the file and highlights the file. I guess on macOS the equivalent context menu will say 'Reveal in Finder'.

**Comment by leegee** [comment]
Exactly.

**Comment by gjsjohnmurray** [comment]
So maybe the option in the Search side bar's context menu should be recaptioned 'Reveal in Explorer Side Bar' (1 change):
https://github.com/microsoft/vscode/blob/0a9f99aa4b37141d3bf563095c6fff5dad4a3290/src/vs/workbench/contrib/search/browser/search.contribution.ts#L337

Alternatively, make the Explorer side bar context menu on Windows use the caption 'Reveal in Windows Explorer' (3 changes):
https://github.com/microsoft/vscode/blob/0a9f99aa4b37141d3bf563095c6fff5dad4a3290/src/vs/workbench/contrib/files/electron-browser/fileActions.contribution.ts#L29
https://github.com/microsoft/vscode/blob/0a9f99aa4b37141d3bf563095c6fff5dad4a3290/src/vs/workbench/contrib/files/electron-browser/fileActions.contribution.ts#L65
https://github.com/microsoft/vscode/blob/0a9f99aa4b37141d3bf563095c6fff5dad4a3290/src/vs/workbench/contrib/files/electron-browser/fileActions.contribution.ts#L86

**Comment by leegee** [comment]
I'm still on Windows, I right-click the tab of an open file, and it offers `Open in Explorer` and `Open in Side Bar`.

**Comment by gjsjohnmurray** [comment]
> 
> 
> I'm still on Windows, I right-click the tab of an open file, and it offers `Open in Explorer` and `Open in Side Bar`.

@leegee on my 1.39.2 on Windows the context menu from a file tab captions the options "**Reveal** in Explorer" and "**Reveal** in Side Bar" (not "Open in ..." as you wrote).

So for consistency I think the context menu from the filename on the Search list should be changed on this line to become `Reveal in Side Bar`
https://github.com/microsoft/vscode/blob/0a9f99aa4b37141d3bf563095c6fff5dad4a3290/src/vs/workbench/contrib/search/browser/search.contribution.ts#L337

**Comment by leegee** [comment]
Fair enough. My point, though, was obviously regarding the
inconsistency in numerology across the application.

**Comment by roblourens** [comment]
We talked about this at the time. The thing is, "Explorer" is used in a bunch of places to refer to the file explorer in vscode and it doesn't seem like a big deal to me. However I realized that there is precedent for referring to it as "Side bar", the command "File: Reveal active file in side bar".

Anyway, I don't have a strong opinion.

**Comment by bpasero** [comment]
We have been using the term "side bar" exactly for this reason: to have a way to distinguish between the Windows Explorer and the explorer in VSCode. We could in theory refer to it as "Explorer View", but that may cause frustration when users search for "reveal explorer" and find 2 results.

I think no matter what we do, both commands should have a similar label. I don't think there is an issue calling the command in the search results "Reveal in Side Bar".

**Comment by leegee** [comment]
That'd be nice and clear.

**Comment by gjsjohnmurray** [comment]
@isidorn are you willing to take my PR for this? It failed CI on windows and darwin but as far as I can tell that wasn't caused by anything in my PR itself.
