### ISSUE TITLE
Terminal colors are different (lighter) after upgrading to macOS Catalina

### ISSUE THREAD

**Issue by ay0o** [microsoft/vscode#83130]
- VSCode Version: 1.39.2
- OS Version: macOS Catalina 10.15

Steps to Reproduce:

1. Upgrade to macOS Catalina and notice the color change right away.
2. If you are already on macOS Catalina, open terminal / iTerm and compare with VSCode's terminal.

Images:

VSCode:
<img width="423" alt="Screenshot 2019-10-23 at 09 19 47" src="https://user-images.githubusercontent.com/23629729/67372758-5014d780-f576-11e9-875f-025689f66543.png">

iTerm2 / Terminal:
<img width="552" alt="Screenshot 2019-10-23 at 09 17 41" src="https://user-images.githubusercontent.com/23629729/67372759-5014d780-f576-11e9-8b0f-9e9e4bd0b983.png">

Back in Mojave there was no such difference. VSCode's terminal displayed the same color.

**Comment by Tyriar** [comment]
The colors the terminal draws is based on the vscode theme. You can try change the renderer to see if that changes the colors https://github.com/microsoft/vscode/wiki/Terminal-Issues#rendering-problems

**Comment by ay0o** [comment]
Tried both renderers, neither seem to impact the color. With the dom-based renderer the font looks slightly bigger, but that's all, nothing else changes.

**Comment by Tyriar** [comment]
@ay0o pretty sure your theme is saying to use that color then? You can set them in settings manually:

![image](https://user-images.githubusercontent.com/2193314/67441882-87ee4000-f5b3-11e9-9184-f27e7cbe907b.png)

**Comment by ay0o** [comment]
yes @Tyriar , you are right that I can manually force them to match the color I want by manually setting each of them, but this wasn't the behavior prior to the update to macOS Catalina, that's why I opened this ticket.

Before, both VSCode and iTerm2 had the same scheme without manual changes. In either case, I'm closing the ticket as the solution is as simple as:

1) Open iTerm2 / Terminal
2) Copy the color code (in my case, ansi blue and green)
3) Force that setting in VSCode's settings.json
