### ISSUE TITLE
UI can get overloaded when extensions add many primary actions

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#83133]
Here is how looks my VSC GUI
![VSC icons menu_](https://user-images.githubusercontent.com/25403861/67374254-37f68580-f581-11e9-8092-03c3d4e29aae.png)
![VSC icons menu other_](https://user-images.githubusercontent.com/25403861/67374268-3b8a0c80-f581-11e9-822b-77045765f9a6.png)

I have not enough place for file cards and problems to find them, easy managment. 
The cards are in conflit with `open editors` from `Explorer`
https://github.com/microsoft/vscode/issues/83127

In related problem I sugested changes to turn on horizontal menu for icons, and for this type maybe we need `menu toolbar` with normal icons, shortcut to hide this toolbar and icons
https://github.com/microsoft/vscode/issues/20485
(https://cloud.githubusercontent.com/assets/25403861/22858261/07e83abc-f0b8-11e6-99f5-0617d8852cf9.png)

There is other problem with VSC and cognitive thinking/mindset. The all menu in top don't have icons. Try understand that "Reading" is "Observing" proces, thats mind any sign of word is graphical and visual efect and tranlated to database of sense, thats mind that we "working" to recognize functions many times..waste "human resoureces" - thats why icons are more friendly, thats shortcuts icons are "nice". VSC need some `kansei` thinkig and mindset.. UX specialist?

**Comment by bpasero** [comment]
@misolori I remember when we initially designed this experience (cc @stevencl) that we never wanted to show more than 3 actions until we put the rest into overflow menu. I have a feeling since there is no way to disable UI contributions individually, we might need to enforce this experience when we detect too many icons.

Should we force actions to appear in the "..." menu if we see > 3?

@ManPython the only workaround for you currently is to:
* either disable extensions individually that add these actions
* maybe disable tabs (via settings) so that you get the full width of the editor for the title

**Comment by misolori** [comment]
I do think it's worth setting a limit on the number of actions shown and placing the rest in the overflow menu (that's a common pattern). Though I'm not sure what the right number would be, as certain cases require more than others: 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/35271042/67404512-5bf99d00-f568-11e9-80b3-7d3ee35b82e3.png">

I would also expect this to be configurable via a user setting, and also allow users to right-click on icons and hide them just as we do in the activity bar, status bar, and panels.

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/46403

**Comment by ManPython** [comment]
I think that the best solution is to move these part with icon to special menu as toolbar or made class that colectin icons from eny ext as part of toolbar and offer to colect this type toolbars in global class and for this offer show/hide toolbars from menu view as in classic GUI in other software. Then we have freedom for cards as normaly. In setting we can offer option to hide some toolbar icons maybe.

**Comment by eamodio** [comment]
IMO, the best option would be to allow the user to easily decide if an icon should be in the "toolbar" or in the menu. And then I would also go further to allow users to hide/remove menu contributions.

**Comment by torchlard** [comment]
just add an option allow all icons hide in "..."

**Comment by bpasero** [comment]
Let's fold this into https://github.com/microsoft/vscode/issues/46403
