### ISSUE TITLE
Selected text by double clicking in the integrated terminal

### ISSUE THREAD

**Issue by 0x01L** [microsoft/vscode#83149]
1. run some cmds in the terminal
2. select text by double click on the cmds' output
3. issue: some extra symbols around the target text will also be selected, such as':', '`', and so on

example:
> [ubt@ubuntu]$> echo 'abc:123 ABC'
> abc:123 ABC

when double click on "abc", "abc:123" will be selected, but in the ubuntu terminal, only "abc" will be selected via the same way.

![Snipaste_2019-10-23_20-11-59](https://user-images.githubusercontent.com/50935207/67391510-69973d00-f5d1-11e9-9f19-332a861c9ede.png)

I tried to change the font of the terminal, but not works.
Is there anyway to set how the strings will be split by which "word breakers"?

**Comment by 0x01L** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Word wrap should not break before a space (#47990)](https://www.github.com/microsoft/vscode/issues/47990)
> * [Sometimes TAB do strange action when use  a fullwidth symbols. (#53919)](https://www.github.com/microsoft/vscode/issues/53919)

not covered

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Tyriar** [comment]
colons, semi-colons and commas are now work separators as of about a week ago
