### ISSUE TITLE
Initialize JS/TS language support snippest take 100% cpu and high battery usage for long time

### ISSUE THREAD

**Issue by jadeja-rajdeep** [microsoft/vscode#83141]
Issue Type: <b>Bug</b>

currently i am working on php project.

whenever i open large .js file from my project i see status at the footer of vs code that say "Initialize JS/TS language support snippest"

when its loading this feature for .js file its take 100% cpu usage and very high battery power.

and its stay like this for like 5 minutes. before its slow down the cpu.

thanks

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
php-intellisense|fel|2.3.13
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
vscode-apache|mrm|1.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this only happen when you open one JavaScript file in particular?

**Comment by jadeja-rajdeep** [comment]
hello

i think its only happen when we directly open the first large .js file cause the file that i am talking about is have around 17000 line of code in it.

so if we open smaller files its fine i think its initialize js/ts features very fast. but if file is larger then this problem start occurring.

thanks

**Comment by mjbvz** [comment]
Can you share the file?

Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) to see if that fixes the problem.

**Comment by jadeja-rajdeep** [comment]
sorry but i am not allowed to share the file.

but yes i can try that JavaScript and TypeScript Nightly plugins and let you know if its solve the problem or not

thanks

**Comment by mjbvz** [comment]
Did the nightly builds help?

**Comment by jadeja-rajdeep** [comment]
sorry i forget to submit my review for typescript@next 
once we use next version of this plugin the issue is still there but not stay for longer time compare to the regular version of typescript/javascript plugin
