### ISSUE TITLE
JSDoc/TSDoc - code block formatting and syntax highlight.

### ISSUE THREAD

**Issue by McLisak** [microsoft/vscode#83146]
JSDoc/TSDoc 

- VSCode Version: 1.39.2
- OS Version: MacOS Mojave (10.14.6)

Steps to Reproduce:

1. Create any function or variable (JS/TS)
2. Add JSDoc/TSDoc comment
3. Put MD code block syntax.

Expected behaviour:
When docs pop-up appears for that function the code block should get properly syntax highlighted. Like it does using `@example` tag:
![image](https://user-images.githubusercontent.com/15079435/67385563-9d537200-f593-11e9-995f-edf5929c52f8.png)

Actual behaviour:
The code block is displayed as following:
![image](https://user-images.githubusercontent.com/15079435/67384855-3bded380-f592-11e9-9e80-22e7b1c7ee6e.png)

Background:
Unfortunately, using docs generator - like TSDoc - I need to use md code-block syntax to get it rendered properly in output html.

FAQ:
- Was it working before?: **Yes** - but not sure which version broke that.
- Does this issue occur when all extensions are disabled?: **Yes**
- Does the issue occur in the VSCode Insiders: **Did not check** - sorry for that.

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by McLisak** [comment]
Hi. Sure, there is the text example:
```ts
/**
 * ```ts
 * const something = test(false);
 * ```
 * @param bool
 */
function test(bool: boolean) {
  return !bool;
}
```

**Comment by mjbvz** [comment]
Thanks. This seems to works properly for me in the latest insiders builds:

![Screen Shot 2019-10-24 at 2 16 21 PM (3)](https://user-images.githubusercontent.com/12821956/67526099-ec1f0b80-f668-11e9-8da8-7f9203f5f5fc.png)

![Screen Shot 2019-10-24 at 2 16 26 PM](https://user-images.githubusercontent.com/12821956/67526075-df9ab300-f668-11e9-8aae-dd169fc513e8.png)


Can you please confirm
