### ISSUE TITLE
Issue with terminal display on Windows 10 Enterprise, Version 1809 Dark Mode

### ISSUE THREAD

**Issue by Shashidanand** [microsoft/vscode#83142]
![image](https://user-images.githubusercontent.com/1199387/67381239-3b9e0280-f5a9-11e9-88d7-f25ffdd04c23.png)

Issue with terminal display on Windows 10 Enterprise, Version 1809 Dark Mode. Font color and background is not compatible with current theme.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
