### ISSUE TITLE
Debug: toolbar grabbing cursor does not show up until you release the mouse

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8314]

**Comment by isidorn** [comment]
I think this is the chrome bug on your machine - the grabbing cursor looks good on my machine

![grab](https://cloud.githubusercontent.com/assets/1926584/16590723/f7031c9a-42d8-11e6-8240-f9ba6705c9ec.gif)

**Comment by bpasero** [comment]
I think I fixed this for the editor part by changing the cursor on mouse down (I was not doing that before). So if you change it on mouse down, then indeed a chrome bug maybe.

**Comment by isidorn** [comment]
Yes, i am doing it on [mouse down](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActionsWidget.ts#L96)
