### ISSUE TITLE
The terminal process terminated with exit code: 126

### ISSUE THREAD

**Issue by AkshitAggarwal** [microsoft/vscode#83147]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Running linux Ubuntu Version 18.04.3 LTS, at first the Integrated Terminal stopped working all of a sudden I could not type anything, later while trying to fix it I made some changes, I tried reinstalling it multiple times. I guess I made some change in terminal.integrated.config and now I can't even seem to open Terminal with above exit code. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2578)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.48GB (2.09GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.3
cpptools|ms-|0.26.0
vscode-icons|vsc|9.5.0

</details>

**Comment by AkshitAggarwal** [comment]
How can I remove vscode entirely, I have installed it through sudo apt and snap, now it says I have two copies of it. I cannot seem to figure out to remove vscode entirely from Ubuntu 18.04.3 and reinstall it from scratch.

**Comment by Tyriar** [comment]
If you installed either apt or snap package you should remove them using the regular means. Try using trace logging to find out where the terminal is failing:

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by AkshitAggarwal** [comment]
I tried removing and installing with both of them. But the issue remains. Enabling Trace Logging opens a log but I'm unsure how to find the exact issue. 
`[2019-10-24 08:54:26.707] [renderer1] [error] ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF
    at UnixTerminal.resize (/snap/code/18/usr/share/code/resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:227:13)
    at S.resize (file:///snap/code/18/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2888:940)
    at w.setDimensions (file:///snap/code/18/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4077:437)
    at _processManager.ptyProcessReady.then (file:///snap/code/18/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4103:111)`

I've pasted the exact message I'm getting in the log after I try to open the terminal using ctr + `.

**Comment by AkshitAggarwal** [comment]
![image](https://user-images.githubusercontent.com/40717067/67451933-6d61a880-f63f-11e9-8ca5-695b706a1eaa.png)

**Comment by Tyriar** [comment]
You spawning `/bin/rbash /bin/bash`, ie. `/bin/bash` is the first argument for the executable `/bin/rbash`, that doesn't seem right?

**Comment by AkshitAggarwal** [comment]
Yes, I made some changes in terminal.integrated.linux I added `/bin/bash` somwhere which causes exit code:126. How do I change it back?

**Comment by AkshitAggarwal** [comment]
![image](https://user-images.githubusercontent.com/40717067/67459244-b6245c00-f655-11e9-90cc-43bd9e8bfb29.png)
Here is what I was attempting to do.

**Comment by Tyriar** [comment]
Two settings drive this `terminal.integrated.shell.linux` and `terminal.integrated.shellArgs.linux`. Open the json file by clicking the button in the top-right:

![image](https://user-images.githubusercontent.com/2193314/67507735-6ab58200-f644-11e9-8362-3d6c164baff9.png)

Remove what you have completely and see if it works, if it doesn't try adding this explicitly:

```
"terminal.integrated.shell.linux": "/bin/bash"
```

**Comment by AkshitAggarwal** [comment]
Removing everything from the JSON resolved the issue, thanks a lot.
