### ISSUE TITLE
Visual code extension: ms-python.python incorrectly showing problems in python code

### ISSUE THREAD

**Issue by elizeuangelo** [microsoft/vscode#83151]
Issue Type: <b>Bug</b>

Everytime I use np.timedelta64() [numpy.timedelta64()] function with more than one argument Visual Studio alerts, either A: Unexpected keyword argument 'dtype' in constructor callpylint(unexpected-keyword-arg) [when ysing dtype argument for instance], or B: Too many positional arguments for constructor callpylint(too-many-function-args).

The code works fine and the arguments are correct and needed:

Example code from problem A: np.timedelta64(1,dtype='datetime64[ms]')
Example code from problem B: np.timedelta64(1,'ms')

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
vscode-yaml|red|0.5.3

</details>

**Comment by alexr00** [comment]
Does this reproduce if you disable all extensions?

**Comment by elizeuangelo** [comment]
> Does this reproduce if you disable all extensions?

Actually, If I disable the Python extension it doesnt acuse problems anymore.

So, the problem is with the extension: ms-python.python

**Comment by elizeuangelo** [comment]
Im closing this and posting on the extension page
