### ISSUE TITLE
Titles are not showing when hovering action icons

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#83159]
We have written the needed data into your clipboard because it was too large to send. Please paste.

| Latest stable | Latest insiders |
|-|-|
|<img width="336" alt="Screenshot 2019-10-23 17 55 00" src="https://user-images.githubusercontent.com/6418145/67406942-71e67c80-f5bf-11e9-9cf8-a77aa3303473.png">|<img width="396" alt="Screenshot 2019-10-23 17 55 34" src="https://user-images.githubusercontent.com/6418145/67407031-8d518780-f5bf-11e9-8371-42ea22708ef0.png">|

**Does this happen with all plugins turned off?** Yes
```
Version: 1.40.0-insider
Commit: f5d3ffa6a0d655c87e1eb0e1e90773df58f7ff25
Date: 2019-10-23T05:24:32.072Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by alexr00** [comment]
Does not repro on Windows or Mac with the latest insiders. Did you try rebooting?

**Comment by ivanvoznyakovsky** [comment]
@alexr00 just figured that it only happens in zen mode. switching back to normal mode brings titles back.

**Comment by alexr00** [comment]
I tried it out on a mac with zen mode, and I still can't see it. I think you are seeing some issue with chrome full screen + titles. There's not much we can do about that, but thank you for reporting.

**Comment by ivanvoznyakovsky** [comment]
@alexr00 not sure I understand what you mean by `you are seeing some issue with chrome full screen + titles`. there's no problem w/ titles in zen mode in stable release. it's only in insiders.
here are screencasts of both versions
stable - https://youtu.be/IcYvbao86xk
insider - https://youtu.be/1T9AN1ZVvZg
