### ISSUE TITLE
Editor: sometimes doubleclick into word is not fully selecting it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83150]
* I have zoom enabled (2) (macOS, browser: Edge dev)
* code is:

```js
function createSVGEllipsePolar(angle:number,radius:number,tx:number,ty:number,
                                cxo:number,cyo:number) {
    var ell = document.createElementNS(svgNS,'ellipse');
    ell.setAttribute('rx',radius.toString());
    ell.setAttribute('ry',(radius/3).toString());
    ell.setAttribute('cx',cxo.toString());
    ell.setAttribute('cy',cyo.toString());
    var dangle = angle*(180/Math.PI);
    ell.setAttribute('transform','rotate('+dangle+','+cxo+','+cyo+') translate('+tx+
                        ','+ty+')');
    return ell;
}
```

* I run from web
* I doubleclick somewhere into the `document` of (`document.createElementNS)` and the click does not select the entire word

The exact location for me is somewhere between `e` and `n`

![before](https://user-images.githubusercontent.com/900690/67391844-c24de200-f59f-11e9-9a19-67fc59e53cda.gif)

**Comment by LeeMellinger** [comment]
I'm having this issue as well. I have not been able to identify a pattern yet. Using VSCODE on a Mac (Catalina).

**Comment by sourcegr** [comment]
Me too. This is very frustrating... :( 

(Mac / Catalina)

**Comment by bkarlson** [comment]
same here, sorry for double posting, but this needs more attention and fixed asap

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by RusseII** [comment]
Me as well. Its driving me CRAZY

![image](https://user-images.githubusercontent.com/15036618/69659583-1f780000-1044-11ea-82f8-79704b5982c4.png)

![image](https://user-images.githubusercontent.com/15036618/69659596-29016800-1044-11ea-8808-6e4ef3f104ec.png)

**Comment by lastobelus** [comment]
seems to be happening more frequently in the last two weeks.

This is a **massive** productivity killer. Totally interrupts flow.

**Comment by pihomeserver** [comment]
Same here on VSCode 1.40.2 on Mac Catalina (10.15.1)

```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by LeeMellinger** [comment]
> I'm having this issue as well. I have not been able to identify a pattern yet. Using VSCODE on a Mac (Catalina).

Still having this issue with the latest version of VSCODE:

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by MLWDev** [comment]
Was following issue #85446 which has been closed as it is related to this one, still a major issue for us today. You have to slow yourself down and check that everything selected properly each time which slows productivity

**Comment by alexdima** [comment]
@MLWDev The fix is available on the Insiders release channel. Please use that one until Stable updates.
