### ISSUE TITLE
Using the mouse wheel on terminals with scrollback 0 will output weird characters

### ISSUE THREAD

**Issue by vladkarnhuji** [microsoft/vscode#83154]
Issue Type: <b>Bug</b>

if I set Terminal › Integrated: Scrollback to 0 in settings, (i did that because i thought it would result in "unlimited scrollback"), if prints weird charecters on the terminal when I use the touchpad to scroll through terminal

Edit: I see it isn't in system info, I'm on Mac.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
python|ms-|2019.10.41019

</details>

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/2500

**Comment by Tyriar** [comment]
What shell are you using?

Also unlimited scrollback doesn't exist, you can set scrollback to a very large number though (it will hold extra memory for the buffer though).

**Comment by jerch** [comment]
@vladkarnhuji About high numbers for scrollback - the mem usage is roughly proportional to numbers of cells * 12, example for 100 cols width:
- 1000 lines ~1.2 MB
- 10000 lines ~12 MB
- 100000 lines ~120 MB

Note that JS engines have strict mem limits (around 2GB imho regardless of total RAM installed), thus avoid going any higher than 100k or you risk running into OOM and vscode will most likely segfault. If your terminal is much wider than 100 cols even 100k might be be to much.

**Comment by Tyriar** [comment]
I think this is fixed
