### ISSUE TITLE
CTRL + . (dot) import suggestions doesn't work anymore

### ISSUE THREAD

**Issue by dompedro-jonathborg** [microsoft/vscode#83160]
- Issues for this are already closed without response.
- Tested with code insiders.

- VSCode Version: 1.40.0-insider
- OS Version: Linux joe-PC 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 19.04)

yarn add semantic-ui-react

use ```<Header>``` or other jsx tags without import. CTRL + . (dot) and nothing.

Zero extensions installed.

CTRL + . (dot) doesn't work. I exptected this shows import suggestions.

![Suggestions](https://i.imgur.com/PWGcwwB.png)

**Comment by mjbvz** [comment]
Is this in a TypeScript file or a JavaScript file? 

In JavaScript, we only show errors by default so we would not create an error for a missing import (hence no quickfix)

**Comment by dompedro-jonathborg** [comment]
It's a javascript file. I could do this in old versions. But... it's a semantic question. I understand. I'm closing. Thaks you.
