### ISSUE TITLE
(Insiders) Can't build extension without vscode.proposed.d.ts because vscode.d.ts references it

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#83167]
The [vscode.d.ts](https://github.com/microsoft/vscode/blob/d0cbf5660fafcb2681d4e08d6cc5992764b21279/src/vs/vscode.d.ts#L9378) file references `DebugSessionOptions`, which is defined in [vscode.proposed.d.ts](https://github.com/microsoft/vscode/blob/d0cbf5660fafcb2681d4e08d6cc5992764b21279/src/vs/vscode.proposed.d.ts#L638). This was added in [this commit](https://github.com/microsoft/vscode/commit/24bf6ecccb876f0301338f2bfa61a694e999be57). As a result my extension's build is failing on an experimental branch. I don't have the `enableProposedApi` flag as it is not needed in my branch, but insiders build 1.40 is needed. If I put vscode.proposed.d.ts back in, build is successful, so I have a workaround.

Shouldn't vscode.d.ts not be referencing vscode.proposed.d.ts?

**Comment by bwateratmsft** [comment]
@isidorn, @dgozman who look like they've worked in these areas.

**Comment by isidorn** [comment]
@bwateratmsft great catch. I have just pushed a fix for this
@weinand fyi for the order I placed this in the `vscode.d.ts`, maybe you prefer a different order. I put the interfaces outisde of the debug namespace (as are our other debug interfaces and classes)
