### ISSUE TITLE
Add action to transpose editor splits

### ISSUE THREAD

**Issue by armarti** [microsoft/vscode#83168]
It would be neat if we could transpose the current splits we have in the editor. See the below screenshots for what I mean.

The reason (for me) is twofold:
- When I'm working in vscode fullscreen and have several editor tabs open, stacked left-right, and I want to move it to the left side of the screen so I can put another application on the right side of the screen, the editor tabs end up very close together, and I need to manually transpose them to a up-down stack arrangement.
- When I'm working on a landscape-oriented monitor, and I switch to a portrait oriented monitor, I need to manually transpose again.

So it'd be a nice convenience to have an action that I could assign to a keybinding to do this transpose automatically.

#### Transposing
Before:
![before](https://user-images.githubusercontent.com/13367887/67410002-537a8400-f5b3-11e9-8dcc-3b851bdd1d90.png)

After:
![after](https://user-images.githubusercontent.com/13367887/67410092-76a53380-f5b3-11e9-8436-4ac3e9b05dff.png)

#### Cluttered arrangement when using another app
![image](https://user-images.githubusercontent.com/13367887/67411227-32b32e00-f5b5-11e9-8130-04199ba3fd54.png)

#### Cluttered arrangement when moving to portrait-oriented monitor
![image](https://user-images.githubusercontent.com/13367887/67411477-9d646980-f5b5-11e9-94fa-eda813f911b5.png)

**Comment by armarti** [comment]
That involves transposing text.

**Comment by sbatten** [comment]
@armarti The command is `Flip Layout`, you can find it in the `View > Editor Layout` Menu and the default keybinding is `Cmd+Alt+0` on mac

**Comment by armarti** [comment]
Man. I thought I had an original idea. But you all have thought of everything. Thanks.
