### ISSUE TITLE
Emmet: error decoding DataURI without workspace

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#8316]
Help to testing #8207 

- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10 Pro (build 10586.420)

Steps to Reproduce:

  1. Create untitled file without workspace
  2. Set `css` syntax
  3. Create selector with `backdround-image` property and `https://avatars1.githubusercontent.com/u/7034281?v=3&s=460` value
  4. Press `F1` and run `Emmet: Encode\Decode data:URL image`
  5. Press `F1` and run `Emmet: Encode\Decode data:URL image`
  6. Will show the file name input box

**Problem**: We cannot work with files outside the workspace.

**Comment by jrieken** [comment]
@egamma I don't see `Encode/Decode` actions anymore. Is that the intent?

**Comment by mrmlnc** [comment]
@jrieken, yes, https://github.com/Microsoft/vscode/issues/8603.

**Comment by jrieken** [comment]
Thanks
