### ISSUE TITLE
Missing English text in Command Palette

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode#83174]
- VSCode Version: `1.39.2` with **Traditional Chinese** language enabled
- OS Version: `Windows 10.0.18362.418`

Steps to Reproduce:

1. Hit `F1`
2. Type `Manage Trusted Domains`

I can't find `Manage Trusted Domains` in **Traditional Chinese** language mode. It suppose have Chinese and English version together. In this version of VSCode, the English text is missing.

![image](https://user-images.githubusercontent.com/88981/67420108-8b5be880-f600-11e9-89d7-14ba5a62cca5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by byyxx128** [comment]
Occured in simplified Chinese as well.
![image](https://user-images.githubusercontent.com/20079289/67423780-e101a800-f5a2-11e9-9424-6f3e280d4d24.png)
Japanese as well.
![image](https://user-images.githubusercontent.com/20079289/67423937-2a51f780-f5a3-11e9-856c-873470626631.png)

So I can absolutely ensure it is not related to which language pack is using.

**Comment by dbaeumer** [comment]
Assigning to @octref who seems to own this. Command needs to specify both the title and an original value if an original value should be presented.

See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/browser/task.contribution.ts#L231

for an example

**Comment by octref** [comment]
Good catch, I didn't realize I have to put `original`.
