### ISSUE TITLE
editor.tabSize not respected when line has tabs already

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/vscode#83177]
Issue Type: <b>Bug</b>

When tabbing a block or line that already has tabs, the `editor.tabSize` setting is ignored, and instead the tabs are moved to where the next tab would be. For example if a line has been indented 7 characters, and the `editor.tabSize` has a value of `4`, pressing <kbd>Tab</kbd> will not move the line to start at position 11, it will be moved to start at position 8.

If you then untab (<kbd>Shift</kbd>+<kbd>Tab</kbd>) the line you tabbed above, it also will therefore not move back to position 7, it will move to position 4; losing any allignment you had previously.

The image below demonstrates this, and the odd behaviour; firstly moving the already tabbed lines from position 7 to 8 when tabbed, and then from 8 to 4 when untabbed. It ends on what the expected result should be.

![Odd Tab Behaviour](https://user-images.githubusercontent.com/20837086/67423494-474ef080-f5cc-11e9-9659-a0c75caa5204.gif)

Perhaps there is a setting for this, however, if so I cannot see it listed under "Tab". If there isn't a setting, this should certainly be one. VSCode (and Azure Data Studio) making the wrong decisions about where the tab should go is quite frustrating.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic
Remote OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (5.19GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Qebui|
|OS|Linux x64 5.0.0-32-generic|
|CPUs|Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz (4 x 1995)|
|Memory (System)|7.62GB (1.25GB free)|
|VM|100%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
vscode-language-pack-en-GB|MS-|1.39.3
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
material-icon-theme|PKi|3.9.1
SecurityIntelliSense|azs|0.8.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
shell-format|fox|6.1.2
vscode-pull-request-github|Git|0.12.0
vscode-language-pack-en-GB|MS-|1.39.3
csharp|ms-|1.21.5
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bmewburn** [comment]
Have you tried `editor.detectIndentation`?

**Comment by LarnuUK** [comment]
@bmewburn that setting has nothing to do with the problem. It is defined as:

> Controls with `Editor:Tab Size` and `Editor: Insert Spaces` will be automatically detected when a file is opened based on the file contents

The file above wasn't opened to start with, it's a new file, and (in my opinion) that setting is awful at detecting Tab Size, so I have it off. I actually raised a "bug" on it on ADS the other week, as it was even overriding the settings in a workspace `settings.json`.

**Comment by alexandrudima** [comment]
Please use:
```
// Inserting and deleting whitespace follows tab stops.
"editor.useTabStops": false,
```

This will make it that indenting/unindenting will not make lines "snap" to tab stops.

**Comment by LarnuUK** [comment]
Thanks @alexandrudima , that's the setting.
