### ISSUE TITLE
Allow setting window size and position from command line

### ISSUE THREAD

**Issue by rcdailey** [microsoft/vscode#83170]
As a user, I'd like to be able to specify the window's size and position from the command line. This will improve the usability of VS Code as a general text editor with Git (using the `core.editor` setting). Right now, the only mechanism to affect window size is in VS Code settings, which are for a different use case entirely.

Right now to start up VS Code for editing commit messages, interactive rebase, or any other Git operation requiring the editor, I use this command:

```
code --wait --new-window
```

In my case, on Windows, since I have `window.newWindowDimensions` set to `inherit` for my normal day to day usage of VS Code as an IDE, and usually keep my windows maximized for this purpose, I instead want the window to be smaller and in a specific area of my screen when I use it for Git.

Basically these are two distinct workflows (VS Code as an IDE and VS Code as an editor for Git). I think being able to configure the window size (maybe not the position, for portability to different computers) is important. Even if it isn't the size directly, maybe having VS remember the window state separately when launched from the command line would be another option. In this case you'd add a `window.newWindowDimensionsCommandLine` setting that is only used when VS Code is invoked using the `--new-window` option from command line (not when launched through the shortcut). Using `inherit` on this setting would keep the last state of the window from when it was last launched on command line. This means that once I launch it through Git once, and configure the window how I like it, the next time the window is launched from command line it will reuse that size & position if I have it set to `inherit`.

**Comment by joaomoreno** [comment]
This sounds like a feature for a window manager, not the application itself.

https://gallery.technet.microsoft.com/scriptcenter/Set-the-position-and-size-54853527

**Comment by rcdailey** [comment]
@joaomoreno Isn't that debatable? I'm not sure what the "window manager" is in this case, can you explain? Are you implying the operating system? Maybe understanding your answer also requires and understanding of the architecture of VS Code itself. I don't have any understanding of that. From my perspective, this is an application feature because I consider VS Code holistically to be the application.

I personally feel there should be a more thorough audit for my issue. I put in a lot of time & effort to explain the request, and provide details and a use case. I'd like to see a little more effort put into considering this feature. It's very upsetting and personally insulting to see my issue closed so quickly with what appears to be very little consideration and thought.

**Comment by rcdailey** [comment]
I'd also like to add:

1. There are other features that control the size & position of the Window built natively into the application. How is this any different?

2. The PowerShell script idea is not portable. Window managers (if you are referring to the OS) are different per platform, if VS Code implements this feature it can be made consistent and portable to other operating systems.

**Comment by joaomoreno** [comment]
@rcdailey Sorry for being blunt. I don't think this feature warrants spending time on it, especially since it would not impact a lot of users and there are external tools that can solve that problem, even if platform dependent. But we can keep this in the Backlog Candidate milestone and ask @bpasero whether he knows of other people who are interested in this.

**Comment by rcdailey** [comment]
Thanks @joaomoreno, I appreciate your involvement and consideration. I'm OK with external tooling as a short term solution, but having this functionality implemented as a first-class citizen would be the better long term solution IMHO. Would it be possible to write an extension for this? Can extensions control the window size & position in a platform agnostic way? Just trying to think of other solutions.

**Comment by joaomoreno** [comment]
> Would it be possible to write an extension for this? Can extensions control the window size & position in a platform agnostic way?

Not currently, no. Why is window size and position so important to use Code as a git editor? It's not really critical, especially since in that use case you can simply close VS Code once you're done editing your commit message.

**Comment by rcdailey** [comment]
I just don't think it's appropriate to use a full screen, maximized window on a 1440p display to edit a few lines of commit message text. A smaller non-maximized window is desired. You're right, it's not critical, and I have not asserted that it is. But it's also not a complex issue. I just want it to make it into a backlog for consideration.

It could very well be that VS Code just ends up not being the right tool for this kind of use case. Either by virtue or inflexibility.

**Comment by DavidDeprost** [comment]
I believe a middle road between both of these views would be ideal:
have `window.newWindowDimensions` take 'halfscreen left' and 'halfscreen right'.

This is useful for much more than commit messages; e.g. some of my zsh aliases:
```
alias zshrc='code -n -w ~/.zshrc && . ~/.zshrc'
alias gitconf='code -n -w ~/.gitconfig'
alias vsconf='code -n -w ~/.config/Code/User/settings.json'
```
On large displays, half a screen is ideal for such small config edits, especially since it's pretty common to have a terminal sized at half a screen too.
Even more convenient would be to detect what side the parent terminal is located, and position the new vscode window on the opposite side.

I'm not familiar with vscode internals, so I don't know how challenging this would be. I'm just throwing around some ideas, in the hope that anything sticks ;)
Personally, I would *love* this convenience.

**Comment by DavidDeprost** [comment]
@joaomoreno @bpasero @rcdailey Thoughts anyone?
Is this feasible or out of scope?

**Comment by rcdailey** [comment]
I've already clearly stated my use case and what would work best for me. Half screen is not what I personally want. I would recommend you open a separate issue for that request.
