### ISSUE TITLE
Allow a way to detect extensions in the activity bar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83171]
Related to the discussion in #83113, we need to find a cleaner way to detect if an item in the activity bar is an extension:

https://github.com/microsoft/vscode/blob/e1987504a17bd9fd805f84ba3bc6cea2e5c260c6/src/vs/workbench/browser/parts/compositeBarActions.ts#L162-L165

This is due to the fact that extensions provide a custom svg and use a mask + background color to make them themeable. However our activity bar now uses an icon font and needs to use the color property instead.

FYI @isidorn

**Comment by frobinsonj** [comment]
@misolori I have a local fix that makes the first case of the `isExtension` check redundant. Would you be interested in a PR that only fixes this first case?

https://github.com/frobinsonj/vscode/commit/9e16f664b6d867056fe02c74666f091c6f43eb9d

**Comment by misolori** [comment]
@frobinsonj ideally we'd like to solve this for both parts

**Comment by sandy081** [comment]
@misolori Cleaned it up. It seems, you do not need to know if the activity item is coming from extension or not, instead you have to know if the activity item is using iconUrl to render icon. So changed the code to use this as a differentiation factor to apply proper styles.

**Comment by misolori** [comment]
This is great, thanks for updating this!
