### ISSUE TITLE
Not respond any feature (Search, Consoles, .....)

### ISSUE THREAD

**Issue by apenab** [microsoft/vscode#83178]
Issue Type: <b>Bug</b>

Open de vscode and after a few minutes the search does not work

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|15.89GB (8.61GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.39.9
vscode-icons|vsc|9.5.0
vim|vsc|1.11.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
prettier-vscode|esb|2.3.0
python|ms-|2019.10.41019

(1 theme extensions excluded)

</details>

**Comment by apenab** [comment]
I noticed that the bug only persists if I have the [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) extension activated.

**Comment by roblourens** [comment]
Can you explain some more? What exactly does not work and what do you think GitLens has to do with it?

**Comment by apenab** [comment]
When I have active GitLens and integration with WSL, after a while the search and other functionalities are blocked and do not work, just like the integrated console.

**Comment by roblourens** [comment]
Can you check whether some process is using high CPU? https://github.com/microsoft/vscode/wiki/Performance-Issues

What exactly do you see when you say they are "blocked"?
