### ISSUE TITLE
API: document.save closes document

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#83179]
Issue Type: <b>Bug</b>

Steps to reproduce

1. git clone https://github.com/sguillia/vscode-bug-repro
2. cd vscode-bug-repro
3. npm ci
4. code-insiders .
5. Press F5 (start debugging session)
6. In the guest, run command `Hello world`
7. Watch as an editor opens and immediatly closes
8. Look at source code, I never asked the editor to close

Make sure that `hello.txt` does not exist if you test several times.

Reproduces without extensions in the debuggee.

VS Code version: Code - Insiders 1.40.0-insider (c58aaab8a1cc22a7139b761166a0d4f37d41e998, 2019-10-22T05:27:42.088Z)
OS version: Linux x64 4.15.0-65-generic
Extensions: none

I'll remove the demo repo once this is closed, here is code for future readers
<details>

```typescript
async function bugrepro(filePath: string) {
	var uri = vscode.Uri.parse('untitled:' + filePath);
	var newDocument = await vscode.workspace.openTextDocument(uri);

	let newEditor = await vscode.window.showTextDocument(newDocument);
	let success = await newDocument.save(); // <-- closes document
	console.log("Save success:", success);

	// This work-around does not work (either warns in the console "Should open in editor #undefined" or opens up document with full path as title)
	// await vscode.window.showTextDocument(newDocument);
}
```
```typescript
let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		bugrepro(context.extensionPath + '/hello.txt');
	});
```

</details>

**Comment by jrieken** [comment]
Pretty sure that's the design. You create an untitled editor and when saving that the untitled document is closed and the actual document on disk is opened instead

**Comment by sguillia** [comment]
> the actual document on disk is opened instead

It isn't. do you mean I should call `showTextDocument` again with the `file` scheme?

**Comment by sguillia** [comment]
I'm sorry I don't agree @bpasero 

I'd like to merely open a new file, programmatically write text in it and save it.

I expect document.save() to write my changes on disk.
I do not expect document.save() to close the document.

If this is really as designed, at least it should be documented that save() closes the document.
If this is really as designed, at least there should be a save() function and a saveAndClose() function.

It is not ok for the user to see the file being opened, closed, and opened again.

How can I create a document and save it while keeping it open?

Perhaps I got something wrong in which case I apologize.

The only workaround I can think of is, important an external library, create file on disk, then only open it, but this seems like a hack to me.
```typescript
import * as fs from 'fs';
if (!fs.existsSync(...)) {
    fs.writeFileSync(...);
}
showTextDocument(openTextDocument("file:..."));
```

**Comment by jrieken** [comment]
> The only workaround I can think of is, important an external library, create file on disk, then only open it, but this seems like a hack to me.

Yes, if that's really want you want, e.g create a file on disk and show it to users with them being able to pick the name then you do that. Better, ignore external libraries and use `vscode.workspace.fs`

**Comment by sguillia** [comment]
Okay, thank you
