### ISSUE TITLE
Terminal split line right click issue

### ISSUE THREAD

**Issue by spiska** [microsoft/vscode#83172]
- VSCode Version: 1.39.2
- OS Version: macOS 10.15 (19A602)

Steps to Reproduce:

1. View -> Terminal
2. Split Terminal
3. Right mouse click on split line
4. Click (left mouse btn) somewhere to dismiss context menu

'split line' keep moving between terminals

![right-click_bug](https://user-images.githubusercontent.com/29575947/67417490-318bfc00-f5c9-11e9-8c1a-322cb61bf16d.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Seems fixed
