### ISSUE TITLE
Ability to invert Invert text under block cursor for readability

### ISSUE THREAD

**Issue by josb** [microsoft/vscode#83183]
# Issue Type
Feature Request

# Description
Theme: Solarized (https://marketplace.visualstudio.com/items?itemName=ryanolsonx.solarized)

The character under the block cursor is hard to read. Compare:

VS Code:
text foreground color remains the same when cursor is over character
<img width="224" alt="Screen Shot 2019-10-23 at 1 16 37 PM" src="https://user-images.githubusercontent.com/50617/67430854-f58c7300-f597-11e9-850a-badd897130c3.png">

Compare NeoVim running in iTerm2:
inverted foreground color

![image](https://user-images.githubusercontent.com/50617/67430516-3afc7080-f597-11e9-8422-bc3582e6b1fe.png)

What setting, if any, inverts the foreground color of the character under the block cursor?

Also see https://github.com/Microsoft/vscode/issues/43130.

# VS Code info
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by ArturoDent** [comment]
Perhaps unintuitively ` editorCursor.background` within your `colorCustomizations` does change the text color "under" a block cursor.

So ` editorCursor.foreground`  changes the block color itself and ` editorCursor.background`  the text within the block cursor.

It will not automatically invert the colors given a some ` editorCursor.foreground`  setting, you would have to chose some contrasting color yourself for ` editorCursor.background`.

And see the same answer at https://www.github.com/microsoft/vscode/issues/43130

**Comment by josb** [comment]
That is pretty unintuitive, indeed. I have produced the desired result with:
```
 "workbench.colorCustomizations": {
      "editorCursor.background": "#ffffffff",
      "editorCursor.foreground": "#808080ff",
  }
```
Thanks!
