### ISSUE TITLE
Adding another keybinding to "cut" breaks cmd+x in text inputs

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#83189]
Issue Type: <b>Bug</b>

Unable to cut either search or replace using key-command %x. Seems like you've dropped a rather common key command. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (2.69GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Can you explain some more? Do you mean cmd+x? In an editor? Do you have any keybindings extensions installed?

**Comment by dfdumaresq** [comment]
Yes, I mean cmd-x. I'm using VS code. 

![image](https://user-images.githubusercontent.com/20051/67607447-5b643080-f739-11e9-9032-960adf35ebe9.png)

Yes, I do have keybindings extensions installed (e.g. IntelliJ IDEA Keybindings).

Are you suggesting that in a previous version of VSC, the search ui used keybindings, but the current version does not?

**Comment by roblourens** [comment]
I just need you to explain exactly what the problem is. What are you trying to do, what happens, etc. "Search/Replace in source control" where does source control come in.

You can try disabling the keybindings extension to see if that works to give us more info.

**Comment by roblourens** [comment]
I see the same when I install that extension and I can't figure out whether the extension has registered that keybinding, will investigate.

**Comment by dfdumaresq** [comment]
I also have this extension installed: Sublime Text Keymap and Settings Importer

**Comment by roblourens** [comment]
I see that the extension has also registered `cmd+delete` as a keyboard shortcut. Both work in the editor, but in the search textbox, only `cmd+delete` works. I think that's wrong.

Shorter repro steps:

- Add this keybinding:

```
    {
        "key": "cmd+delete",
        "command": "editor.action.clipboardCutAction"
    }
```
- Now cmd+x doesn't work in the simple text boxes but it does in the editor

**Comment by roblourens** [comment]
I realized this is probably the same as https://github.com/microsoft/vscode/issues/82841
