### ISSUE TITLE
Open browser [Node.js]

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#8318]
Hi, is it possible to open the browser after starting a Node.js application? This feature can be appreciated in Node.js tools for visual studio.

Thanks.

**Comment by isidorn** [comment]
This would need to come from the node debug adapter - thus forwarding to @weinand

**Comment by weinand** [comment]
@sant123 this is not possible, but it is a valid feature request.

**Comment by sant123** [comment]
Thank you @weinand ☺

**Comment by weinand** [comment]
duplicate of #2405
