### ISSUE TITLE
the Commit in the source does not work

### ISSUE THREAD

**Issue by ashah86** [microsoft/vscode#83193]
Issue Type: <b>Bug</b>

the Commit in the source does not work when I click on the commit icon. This is the first time it has happened to me. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (3.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.44104

</details>

**Comment by joaomoreno** [comment]
Do you have changes and did you type a commit message? Is there any error showing up? What are your full user settings?

**Comment by ashah86** [comment]
yes, I have created a few test files and i have entered the messages in the commit, however, when I press the commit, the dialog box that would normally appear to ask if you would like to commit does not appear.  I am not sure why that is the case and this is the first time this issue actually came up. The sync dialog box appears no problem and I have been running into this error as well.  Provided a screenshot below:

-Amy

[cid:54c4aadd-226e-4adf-a202-f90249eb1460]
________________________________

**Comment by joaomoreno** [comment]
I can't see the screenshot, you have to post it in the github issue. Also, what are your full user settings?

**Comment by ayami123** [comment]
your commit is broken, doesn't even tell why we can't commit
