### ISSUE TITLE
Expose Elevated Save to the User

### ISSUE THREAD

**Issue by mahsoommoosa42** [microsoft/vscode#83190]
Currently, let's say we are modifying something in a protected directory where we require admin or sudo access. We need to attempt a save first, be met with insufficient permissions prompt and then hit the "Retry as Sudo" button. Why not make this available as an option in the "File" dropdown. Additionally, It could be an action which could be manually assigned to a keyoboard shortcut if the user wishes to.

**Comment by robbuckley** [comment]
i see the same issue, on ubuntu 16.04 i get the following error

**Comment by mahsoommoosa42** [comment]
@robbuckley<mailto:notifications@github.com> what I'm suggesting is making the 'save as admin/sudo' an accessible option from the file menu, command palette. So, we no longer need to wait for the prompt. Additionally, we could assign it to a keyboard shortcut.
________________________________

**Comment by palto42** [comment]
I would also appreciate an "Open as sudo" option to allow opening files where the current user has no read access.
The current "Retry as Sudo..." only works if the current user has read access to the file to open it.

**Comment by mahsoommoosa42** [comment]
A temporary work around is opening code as sudo with the user_data_dir argument specified. However, I'm just not comfortable doing that. I'm willing to contribute towards this feature as well.

**Comment by mahsoommoosa42** [comment]
I'm willing to contribute to this particular issue. It would be great if someone could me some pointers on where to start. I have already read the contributions guide.
