### ISSUE TITLE
Wrong position of the selector in the debugging console

### ISSUE THREAD

**Issue by huashi001** [microsoft/vscode#83198]
- VSCode Version: 1.39.2
- OS Version:

Steps to Reproduce:

1.open the selector in the debugging console
2.change the height of the debugging console
3. problem occurs

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
Can you post a screen shot of this issue?

**Comment by huashi001** [comment]
like this：
![image](https://user-images.githubusercontent.com/28703635/67497786-10063f80-f6b1-11e9-8658-7c874b4b9e1d.png)

**Comment by isidorn** [comment]
@cleidigh assiggning to you if you have time to look into this.
I can not reproduce this.
