### ISSUE TITLE
--gpu-preferences has suspicious default setting (possible security issue?)

### ISSUE THREAD

**Issue by jsgoller1** [microsoft/vscode#83192]
After killing VSCode when it locked up, I executed `ps aux | grep code` and found the following (of several) processes running:

```
joshua.+ 18474  0.5  0.2 614280 149620 ?       Sl   16:22   0:03 /usr/share/code/code --type=gpu-process --enable-features=SharedArrayBuffer --disable-features=SpareRendererForSitePerProcess --disable-color-correct-rendering --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=3390307351534986627
```

The `--gpu-preferences` setting doesn't look sane; it looks like input you'd use to overflow an unsantized string buffer. Is this normal?

Version info:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.4.0-148-generic, 
Ubuntu 14.04 LTS
```

Steps to Reproduce:

1. Open VSCode from the launcher. 
2. Execute `ps aux | grep code` to see the output. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is expected https://stackoverflow.com/questions/52677555/strange-gpu-preferences-of-chrome
