### ISSUE TITLE
Can't trigger breakpoint in a local file that is called by the current file on VSCode remote ssh

### ISSUE THREAD

**Issue by rbavery** [microsoft/vscode#83195]
Issue Type: <b>Bug</b>

I can trigger the breakpoint in my current file that calles the other local file, but no breakpoints can be triggered outside of the current file for some reason. I'm using VSCode remote on the Azure Data Science VM.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic
Remote OS version: Linux x64 4.15.0-1060-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.08GB (2.04GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 52.175.218.134|
|OS|Linux x64 4.15.0-1060-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2294)|
|Memory (System)|31.39GB (27.55GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.1
remote-ssh-edit|ms-|0.47.1
Python-autopep8|him|1.0.2
python|ms-|2019.10.44104

</details>

**Comment by isidorn** [comment]
Looking at your extension list you seem to be using pythong. So I believe you are debugging python, so I would file thiss against the python extension since they are in charge of handling breakpoints.
Thanks
