### ISSUE TITLE
rendering minimap region colors

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#83206]
hey all, how i can render the `#regions` colors in the `minimap` ?
![image](https://user-images.githubusercontent.com/24865815/67464840-0bd71500-f612-11e9-9537-fabf5b18b88a.png)

is it a bug ? because it seem rendering all other colors.
I also open a question here.
https://stackoverflow.com/questions/58536628/vscode-minimap-region-color
thanks

**VERSION**
- Version : 1.39.2 (user setup)
- Validation : 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- Date : 2019-10-15T15:35:18.241Z
- Électron : 4.2.10
- Chrome : 69.0.3497.128
- Node.js : 10.11.0
- V8 : 6.9.427.31-electron.0
- OS : Windows_NT x64 10.0.18362

**Comment by RMacfarlane** [comment]
This is currently not possible, there's an existing feature request to allow extensions to render decorations in the minimap: https://github.com/microsoft/vscode/issues/82808
 Closing as a duplicate
