### ISSUE TITLE
Terminal Not Opening

### ISSUE THREAD

**Issue by sjagmeet37** [microsoft/vscode#83203]
Hi Team,
when I try to open terminal it shows a blank screen. earlier I was able to see some text but I wasn't able to write any command in it.

Thanks

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by sjagmeet37** [comment]
OS Version: Windows 10 Enterprise 1809
vs code : 
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
![image](https://user-images.githubusercontent.com/27469815/67619444-5c6c8f00-f819-11e9-9191-68864b0160a7.png)
may be this helps.
Everything is running smoothly once I changed from **power shell to cmd**

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803
