### ISSUE TITLE
VS Code occasionally forgets all of my recently opened documents

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode#83207]
- VSCode Version: 1.39.2
- OS Version: Ubuntu 18.10

Every now and then (maybe once a month), I'll turn on my computer, open up VS Code, and all of my recently opened workspaces will be gone. That is, there's nothing in the "Recent" section of the Welcome page, and nothing under File > Open Recent. This seems to happen at random.

Does this issue occur when all extensions are disabled?: I don't know. I would have to run VS Code without extensions for weeks in order to find out. Running with extensions disabled certainly doesn't bring back

**Comment by bpasero** [comment]
> This seems to happen at random.

That will make it hard for us to push a change that results in a fix. Unless you can find steps to reproduce, I will have to close this issue.

We do save this state in a file in the user data dir, and maybe it gets corrupt, e.g. when shutting down the machine while VSCode is running.

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
