### ISSUE TITLE
Using Regex Replace To Replace Target

### ISSUE THREAD

**Issue by ThanLoo** [microsoft/vscode#83201]
- VSCode Version:1.39.2
- OS Version:Win10 1809

Steps to Reproduce:

It dont work to use search with regular expression to replace the first charector of the word to upper case . FYI:
![image](https://user-images.githubusercontent.com/46884137/67449444-c84dcc80-f64c-11e9-92e6-761221df7d5e.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/12185
