### ISSUE TITLE
Keyboard and Mouse become super laggy and unresponsive

### ISSUE THREAD

**Issue by qadszilla** [microsoft/vscode#83202]
Issue Type: <b>Performance Issue</b>

The issue happens within random minutes of starting the editor and gets worse with time. Once the issue starts, the editor must be closed completely for the system to recover.

I've experienced this issue before but its the worst in 1.39.2 - to the point that it becomes impossible to work.

Adding these flag to the startup path stops the issue completely:
--disable-gpu
--disable-gpu-compositing

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    79	  8456	code main
    0	   149	  4984	   window (dev - Visual Studio Code)
    0	    11	  7412	     watcherService 
    0	    11	   236	       console-window-host (Windows internal process)
    0	    59	 15232	     extensionHost
    0	    74	 12280	   shared-process
    1	    66	 12972	   window (Issue Reporter)
    1	    96	 13144	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dev - Visual Studio Code)
|    Folder (dev): 13 files
|      File types: php(4) ftpconfig(1) sql(1) json(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by alexr00** [comment]
Please checkout the performance section of our wiki: https://github.com/microsoft/vscode/wiki/Performance-Issues
