### ISSUE TITLE
Standalone editor css: no code assist on color values:

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8321]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10.

![capture](https://cloud.githubusercontent.com/assets/1931590/16413547/cbdb95ca-3d32-11e6-8349-92d35723b12d.png)

**Comment by dbaeumer** [comment]
I also see very strange code complete behavior in less and scss

**Comment by aeschli** [comment]
`#` needs to be added to the word rule

**Comment by aeschli** [comment]
same bug as in #8325
