### ISSUE TITLE
stops scrolling in trackpad

### ISSUE THREAD

**Issue by hariprasad26091993** [microsoft/vscode#83217]
Issue Type: <b>Bug</b>

Please stop this annoying bug. Complete Scrolling stops suddenly in Visual Studio Code Editor(might be forcefully done because to push updates)....plz stop

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
elmmet|nec|1.0.1
LiveServer|rit|5.6.1
emmet-live|yse|1.0.0

</details>

**Comment by alexandrudima** [comment]
@hariprasad26091993 I am not sure I understand what is the exact issue that you have? Can you please explain in greater detail?
