### ISSUE TITLE
userHome is not correctly used in remote environments

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83213]
While looking into how to support `IEnvironmentService.userHome` in web, I realized that most usages are wrong to begin with: if you are connected to a remote file system, the local `userHome` is typically not what you want. Rather, `IRemoteAgentEnvironment.userHome` should be used. 

You can easily see this for example in quick open: type `~/.bash_profile` and it will not show you a file in remote even if this file exists in the user home on the remote. 

I see a bit of overlap with the recently introduced `IRemotePathService` where maybe this should be added too?

**Locations:**
* [x] [`linkDetector`](https://github.com/microsoft/vscode/blob/a143fc36f8ee58db069c0bd2a14ec4ddeb29a009/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L121) @isidorn 
* [x] [`loadedScriptsView`](https://github.com/microsoft/vscode/blob/a143fc36f8ee58db069c0bd2a14ec4ddeb29a009/src/vs/workbench/contrib/debug/browser/loadedScriptsView.ts#L354) @weinand 
* [x] [`openFileHandler`](https://github.com/microsoft/vscode/blob/a143fc36f8ee58db069c0bd2a14ec4ddeb29a009/src/vs/workbench/contrib/search/browser/openFileHandler.ts#L190) @roblourens 
* [ ] [`queryBuilder`](https://github.com/microsoft/vscode/blob/a143fc36f8ee58db069c0bd2a14ec4ddeb29a009/src/vs/workbench/contrib/search/common/queryBuilder.ts#L237) @roblourens 
* [x] [`labelService`](https://github.com/microsoft/vscode/blob/a143fc36f8ee58db069c0bd2a14ec4ddeb29a009/src/vs/workbench/services/label/common/labelService.ts#L266) @isidorn 

I think a good example of a proper use is this code from `terminalTaskSystem`:

```ts
private async getUserHome(): Promise<URI> {
	const env = await this.remoteAgentService.getEnvironment();
	if (env) {
		return env.userHome;
	}
	return URI.from({ scheme: Schemas.file, path: this.environmentService.userHome }); //
}
```

I think a more generalized solution would be something along the lines of:

```ts
async resolveUserHome(): Promise<void> {

	// No remote: user home can only be local
	if (!this.environmentService.configuration.remoteAuthority) {
		this._userHome = URI.file(this.environmentService.userHome);
	}

	// Remote: resolve user home from remote
	else {
		const remoteAgentEnvironment = await this.remoteAgentService.getEnvironment();
		if (remoteAgentEnvironment) {
			this._userHome = remoteAgentEnvironment.userHome;
		}
	}
}
```

**Comment by roblourens** [comment]
Yeah I was looking at that too then got sidetracked by trying to decide whether RemotePathService should exist at all. @aeschli made a good point that maybe all path operations should happen in the remote.

From https://github.com/microsoft/vscode/issues/82739#issuecomment-544892299 it sounds like we are also thinking about workspaces that mix different types of remotes, which require even fancier handling.

**Comment by bpasero** [comment]
I added `IRemotePathService.userHome` and adopted it for the file quick open.

**Comment by isidorn** [comment]
I acknowledge the issue, however it is a bit problemtic to change since it would make all the call async since `IRemotePathService.userHome` is a `Promise`. This would spread to all the users of the `labelService` making them `async`.
Thus I will make no changes atm.

**Comment by bpasero** [comment]
@isidorn one way out here would be to resolve the user home in the remote service and provide a sync getter which is possibly undefined. You could then use that as a hint in the label service if defined. The service could even have an event when the value is resolved for labels to resolve again (though not sure that would be really needed).

**Comment by isidorn** [comment]
Yes that makes sense.

**Comment by isidorn** [comment]
This is a duplicate, you just reopend this same issue I bleive. Thus closing
