### ISSUE TITLE
Merge-conflict code lenses missing

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#83221]
Hello, I'd like to add to this - the shortcuts disappear for me too! This happens always since I've updated vscode from 1.38 to 1.39.2.

I opened the same merge conflict with vscode 1.38 / vscode-insiders 1.39.0 and it works absolutely fine.

Can we get this re-opened?

/cc @chrmarti 

Let's create a sample conflict:

```sh
mkdir repo
cd repo
git init
touch file
echo "1" > file
git add file
git commit -m "master: init & write '1' to file"
git checkout -b other-branch
echo "2" > file
git add file
git commit -m "other branch: change '1' to '2' in file"
git checkout master
echo "3" > file
git add file
git commit -m "master again: change '1' to '3' in file"
git checkout other-branch
git rebase -i master
# <confirm>
```

```console
Auto-merging file
CONFLICT (content): Merge conflict in file
error: could not apply 0d65af8... other branch: change '1' to '2' in file
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 0d65af8... other branch: change '1' to '2' in file
```

```sh
cat file
```

```console
<<<<<<< HEAD
3
=======
2
>>>>>>> 0d65af8... other branch: change '1' to '2' in file
```

```sh
code .
```

![vscode-normal-nope](https://user-images.githubusercontent.com/29430509/67404265-c982e900-f5bb-11e9-9fa8-46e12ea32f7c.png)

As you can see - the `resolve merge conflict` buttons are nowhere to be found. There is no way in hell that vscode cannot support this.

Now, if I open up an older version of vscode (`1.39.0-insider` instead of `1.39.2`), it all works fine:

![vscode-insiders-works-thought](https://user-images.githubusercontent.com/29430509/67404280-ce479d00-f5bb-11e9-87be-afac7747701d.png)

it will probably work with vscode `1.38.x`.

---

My setup:

```console
$ uname -a
Linux arch-usb 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux

$ code -v
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64
```

_Originally posted by @sarpik in https://github.com/microsoft/vscode/issues/82946#issuecomment-545476881_

**Comment by chrmarti** [comment]
@sarpik Could you check your settings and make sure code lenses are enabled:
![image](https://user-images.githubusercontent.com/9205389/67484719-f7723700-f668-11e9-9d29-1e8d60a64123.png)

And:
![image](https://user-images.githubusercontent.com/9205389/67484740-022ccc00-f669-11e9-98ef-f100f923bbc3.png)

**Comment by sarpik** [comment]
@chrmarti that's it! :tada:  Both of them were disabled:D 

I don't know how this happened though - it seems like the update from 1.38 to 1.39 changed the settings or something, because I've never touched these.

---

For anyone reading - after enabling `Code Lens`, I didn't like all the `x num of references` around every variable, so I kept `Code Lens` enabled, but disabled the referencesCodelens, and ended up like this:
```json
"editor.codeLens": true,
"merge-conflict.codeLens.enabled": true,
"typescript.referencesCodeLens.enabled": false,
"typescript.implementationsCodeLens.enabled": false,
"javascript.referencesCodeLens.enabled": false
```

and that's it!

/cc @ZhangPuXi (he had the original issue)

Thanks again Christof:)
