### ISSUE TITLE
Test: download and upload in explorer in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83225]
Refs: https://github.com/microsoft/vscode/issues/83037

- [x] any os @eamodio
- [x] any os @connor4312 

Complexity: 2

* Using the web UI, right click on file(s) from the explorer and verify you can trigger a download and that the contents are OK. 
* Also verify that you can drag multiple files from your desktop to the web UI. Make sure that they get uploaded properly and that the content is correct. Make sure that you get a confirmation dialog in case of a name clash.
* Drag a file onto the desktop and verify it gets downloaded there

**Comment by eamodio** [comment]
- Dragging multiple files into the vscode explorer works fine on Windows, although if there name conflicts in the set of files you are dragging, you will get a confirmation dialog for each of them, but there isn't any way to tell which file conflicted so at first I thought the confirmation dialog wasn't working, but in reality it was, I was just cancelling each of the conflicts one by one. We probably should add the file name in that confirmation dialog.

- Like @connor4312 above, dragging multiple files to the desktop on Windows doesn't work. Only the first file is downloaded.

- Again same as @connor4312, dragging folders in or out on Windows doesn't do anything.

- I tried dragging a file into the editor area (like you can on desktop) and expected the file to be opened in a new tab. But nothing happens. If this isn't going to be supported we maybe should disable the drop target.

**Comment by bpasero** [comment]
@connor4312 @eamodio can you maybe coordinate and report a bunch of individual issues? Then we can continue from there. Quick feedback:
* multiple file download is nothing we can support currently when using drag and drop, at least I am not aware of a way to do this with Chromes `DownloadURL` type

I think being able to drop a file into the editor area to open it would be nice, but not sure how to do that because we would almost have to create a temporary file on the remote to open it. Not sure if disabling the drop target is possible either because we still want the DND feedback when dragging from the file explorer inside VSCode.

**Comment by connor4312** [comment]
> multiple file download is nothing we can support currently when using drag and drop, at least I am not aware of a way to do this with Chromes DownloadURL type

Erg, yea, that's a pain. It's possible to attach multiple Files to the drag event, but these object [must be created with](https://w3c.github.io/FileAPI/#file-constructor-params) some binary sequence--they don't support streams--so you'd need to have the file contents at hand, loaded into memory, to actually support that. I'm guessing that's why Chrome implemented the non-standard downloadUrl 😛  I'll work with Eric to get some issues opened for the other points.

**Comment by bpasero** [comment]
I think its fine, for multi-download we offer a command in the file explorer context menu that works with multi-select.
