### ISSUE TITLE
Deeper inspection when CTRL+hovering over imported symbols

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/vscode#8322]
For example, I have this file:

```
import { Part } from "./parts"

/**
 * This class implements communications with the server back-end API.
 */
class EditorClient {
    renderPart(part: Part) : string {
        return '' // TODO
    }
}
```

If I CTRL+hover over `Part` in `renderPart`, what's display isn't information about the imported symbol `Part`, but rather the `import` statement itself, which is rather uninteresting.

The same is true for "Go to definition", which goes to the `import` statement at the top of the file, from where I have to then trace it back to the actual declaration in the file - again, not very useful.

The same is true for "Peek definition", which lets me peek at the `import` statement a few lines above - not helpful.

Finally, "Find all references" also doesn't do what you'd hope for - it just gives you a list of references to the local symbol in the current file, rather than references to the imported symbol.

I suspect this boils down to one issue - that imported symbols resolve as just the local symbol, rather than the imported symbol?

I think that there is no real use, for any of the mentioned features, for imported symbols - the local symbols are pretty uninteresting, and it would make a lot more sense to resolve them in advance, so that I don't have to manually drill through them?

I think that they should probably even resolve recursively - because it's quite common to collect a bunch of imports and re-exports for the sole purpose of collecting them; it's a common enough pattern, and in every case, what's interesting is the concrete resolved symbol at the end of that import chain - the local symbols are not very interesting.

Thoughts?

**Comment by bpasero** [comment]
I think everyone suffers from this one...

**Comment by mindplay-dk** [comment]
@bpasero what do you mean? every user or other editors have the same problem? (maybe this is an issue with the TS language service?)

**Comment by dbaeumer** [comment]
Yes, it is a issue with the TS language server and it shows when Ctrl+Clicking as well. I know that they are working on it for 2.0. The idea is that if the symbol is not renamed we directly show the information of the definition. However it renamed we jump to the import statement.

I will close this one since there is nothing we can do in the editor itself. Please ping if you think otherwise.

**Comment by mindplay-dk** [comment]
Great, we'll wait and see what happens with 2.0 :-)
