### ISSUE TITLE
Command + A no longer selects all text in "Find" field

### ISSUE THREAD

**Issue by abejfehr** [microsoft/vscode#83228]
Issue Type: <b>Bug</b>

1. Press command + F to open the "find" bar
2. Type something
3. Realize it's wrong, press Command + A to select it all
4. Type something correct
5. Realize it didn't replace the wrong thing with the right thing, because it was never selected in step 3

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|-psn_0_15593182|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
prettier-vscode|esb|2.3.0
flow-for-vscode|flo|1.5.0
plantuml|jeb|2.12.1
svg|joc|1.0.2
turndown-vscode|kur|1.0.2
csharpfixformat|Leo|0.0.84
HTMLHint|mka|0.6.0
vscode-html-format|moh|0.0.3
mssql|ms-|1.7.0
csharp|ms-|1.21.5
vsliveshare|ms-|1.0.1056
vetur|oct|0.22.5
vscode-jest|Ort|3.0.2
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
stylelint|shi|0.51.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by gjsjohnmurray** [comment]
@abejfehr does this also happen if you run with all extensions disabled?

I just tried to reproduce it (admittedly on Windows) but wasn't able to. Ctrl+A did as expected.

**Comment by abejfehr** [comment]
Shoot, it _does_ work with all extensions disabled 😞 

I'll re-enable them one by one and see if I can find the problematic extension. Sorry about this!
