### ISSUE TITLE
VSCode Can't create launch.json in .vscode folder

### ISSUE THREAD

**Issue by 31029** [microsoft/vscode#83222]
when I create a cpp file and try to debug but it didn't work .it said that Can't create launch.json in .vscode folder-------无法在 ".vscode" 文件夹(Cannot read property 'name' of undefined)内创建 "launch.json" 文件。

Vscode Version: 1.39.2 (user setup)
OS: Windows_NT x64 10.0.17134

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide all info from template - VSCode version, OS version etc.

**Comment by 31029** [comment]
> /needsMoreInfo
> 
> Could you provide all info from template - VSCode version, OS version, does it happen with extension disabled etc.

Vscode Version: 1.39.2 (user setup)
OS: Windows_NT x64 10.0.17134
