### ISSUE TITLE
Display full text in Problems pane.

### ISSUE THREAD

**Issue by hxlnt** [microsoft/vscode#83235]
Allow text in problems to word wrap or display full text on hover. 

See https://github.com/webhintio/hint/issues/3175

![image](https://user-images.githubusercontent.com/9647195/67503250-28884280-f63c-11e9-81bc-0bd656a450fd.png)

Version: 1.39.2 (user setup)
OS: Windows 10.0.18362

**Comment by IllusionMH** [comment]
In the meantime workaround would be setting `"workbench.list.horizontalScrolling": true`, however it affects all list/tree components.

**Comment by sandy081** [comment]
#83336
