### ISSUE TITLE
enable to change the font family and size of debug panel

### ISSUE THREAD

**Issue by p-se** [microsoft/vscode#83236]
_Background_

I don't like the font that remembers me of Times New Roman (maybe it is?) and would like to have the ability to choose any font to be displayed for the debug panel and its variables and data. Like the font familiy for the editor and the console can already be chosen.

_Summary_

Have the debug panel follow the existing editor font options such as debug.console.fontSize and debug.console.fontFamily.

OR

Add configuration options for the debug panel such as:

debug.panel.fontSize
debug.panel.fontFamily
debug.panel.lineSpacing for space between lines

Better naming conventions are welcome.

Linux , VSCode 1.39.2

![vscode-debug-panel-font](https://user-images.githubusercontent.com/9606095/67506400-48942200-f68d-11e9-9f6c-90ff46b669fd.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/519
