### ISSUE TITLE
Completions with SnippetStrings do not select the correct range for placeholders

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#83239]
Given this `CompletionItemProvider` implementation:

```ts
public async provideCompletionItems(
	document: TextDocument, position: Position, token: CancellationToken, context: CompletionContext,
): Promise<CompletionList | undefined> {
	const item = new CompletionItem("name => …");
	item.keepWhitespace = true;
	item.insertText = new SnippetString();
	item.insertText.appendText("@override\n  // TODO: implement name\n  String get name => ");
	item.insertText.appendPlaceholder("null", 1);
	item.insertText.appendText(";");

	return new CompletionList([item]);
}
```

If you run it on Windows in a document with CRLF, selecting the completion item results in a range that does not match the actual placeholder range being selected:

![Untitled](https://user-images.githubusercontent.com/1078012/67507791-960d9080-f687-11e9-90ef-a3574c3f9b40.png)

I'm not certain, but I think this used to work fine - I have integration tests that are failing on Windows because of this (though I can repro locally), but I'm sure they used to pass.

**Comment by DanTup** [comment]
I repro'd locally with stable, but my CI builds are failing for both stable and insiders.

My guess is that the `\n` in the snippet string is confusing things, because the document it's inserted into is `\r\n`, but that's a bit of a stab in the dark :)

**Comment by jrieken** [comment]
> I'm not certain, but I think this used to work fine

So, you added that test recently or why does this fail for stable a while after we have released that?

**Comment by DanTup** [comment]
I added the test in March, but for the last month or so I haven't paid much attention to test results because the runs have been completely flaky (because of https://github.com/microsoft/vscode/issues/82676 - which I didn't realise was only happening on macOS until much more recently).

I'm pretty sure I've had green Windows test results since March, but I don't keep all the history (I delete them periodically because the logs are large and cost on S3) so I can't be certain.

Are you unable to repro?

**Comment by jrieken** [comment]
I can repo - I was just confused by when this started to happen. From looking at the sources this should be broken ever since...

**Comment by DanTup** [comment]
Ok great!

It's definitely possible it's been broken since I added the test. I thought I would've noticed it, but integration tests against VS Code can be pretty flaky (for many reasons - not least because the APIs make it difficult) and sometimes if a test seems to pass on most of the bots, I might assumed it's random flakes, so if there's nothing obvious that broke it then assume that's the case :-)

**Comment by jrieken** [comment]
This is an unwanted side effect of `keepWhitespace` since the (leading) whitespace treatment and the newline massage are done in one. Both should be done individually

**Comment by DanTup** [comment]
Aha, that's probably when it started failing then - the test only compared the selected text so wouldn't have been affected by the general whitespace change.

Tested the fix in insiders and it looks good, thanks!

**Comment by jrieken** [comment]
Adding verified based on the above comment
