### ISSUE TITLE
When using a git filter in .gitattributes vscode scm shows everything as modified

### ISSUE THREAD

**Issue by cuhland** [microsoft/vscode#83232]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

# Steps to Reproduce:
1. Create a .gitattibutes in your git repository
```
*.json filter=tabspace
```
2. Create a .gitconfig file or save this as global
```
[filter "tabspace"]
	clean = expand --tabs=4 --initial
	smudge = unexpand --tabs=4 --first-only
```
3. Create a json file with `tabs` as indention character.
```
{
	"list" : [
		{
			"name": "foo",
			"id": 1
		},
		{
			"name": "bar",
			"id": 2
		},
		{
			"id": 3,
			"name": "buz"
		}
	]
}
```
4. Commit the file. 

## Problem 

The gutter indicator shows all lines as modified because of whitespace. The file in the working directory has tabs, but the the git filter was applied when git stashed the file and in the index you will have 4 whitespace instead of the tab.

## Example repository

I created a example repository: https://github.com/cuhland/vscode-git-attributes-filter

## Git attributes
See [git attributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#filters_a).

### smudge
![git smudge](https://git-scm.com/book/en/v2/images/smudge.png)

### clean
![git clean](https://git-scm.com/book/en/v2/images/clean.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
VS Code simply spawns `git status`, so what does `git status` say in your machine?

**Comment by joaomoreno** [comment]
Oh do you mean just the _gutter indicator_ specifically?

**Comment by cuhland** [comment]
If I run `git status` it shows me 
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
and also vscode scm does not show any change. But **gutter indicator** shows the file (see example.json in this [repository](https://github.com/cuhland/vscode-git-attributes-filter.git)) as modified. 

When I look at git output from vscode I can see this output
```
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :example.json
```

Is gutter indicator maybe using `git show` even if `git status` say something different?
