### ISSUE TITLE
[css/less/scss] validation on values

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#8323]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10.

See screen shot. Shouldn't bld have a squiggle

![capture](https://cloud.githubusercontent.com/assets/1931590/16413770/4e075bfa-3d34-11e6-8c96-299a997ac03d.png)

**Comment by dbaeumer** [comment]
Same is true for scss and css

**Comment by dbaeumer** [comment]
Also happens in VS Code.

**Comment by aeschli** [comment]
Not a regression, we never did any validation on values. Could be trivial for some properties where we know all values, but trickier for others that take multiple arguments.

**Comment by connorshea** [comment]
I think https://github.com/Microsoft/vscode-css-languageservice/issues/93 is relevant to this issue?
