### ISSUE TITLE
UNC server missing from path on new files

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#83237]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Have VS Code open already
2. Use a shell to launch code.cmd with a new file resource.  In this case, in PowerShell ->

```PowerShell
code $profile # $profile = the non-existent file '\\RK-VS-FS1\Users Folders\cmorris\My Documents\PowerShell\Microsoft.PowerShell_profile.ps1'
```
3. Inspect the path when the editor for the new (and marked dirty) file opens, the UNC server portion is missing.

![image](https://user-images.githubusercontent.com/26179051/67506863-75c3de80-f653-11e9-9889-9483baa74789.png)

Once the file is saved, the server portion of the UNC path appears.

![image](https://user-images.githubusercontent.com/26179051/67507132-f4b91700-f653-11e9-967f-84b364f7a053.png)

Possible relationship to #39596.

**Comment by bpasero** [comment]
Sounds like a label provider issue to me.

**Comment by aeschli** [comment]
I still see the same issue in
1.40.0-insider (user setup)
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T05:42:33.138Z

![image](https://user-images.githubusercontent.com/6461412/67966037-6c161a00-fc03-11e9-91dd-cbead159a276.png)
