### ISSUE TITLE
"No build task to run found. Configure build task" - Clicking does nothing.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#83246]
- VSCode Version:
```
1.40.0-insider
b53811e67e65c6a564a80e1c412ca2b13de02907
x64
```
- OS Version: `Linux 5.3.7-arch1-1-ARCH GNU/Linux`

Steps to Reproduce:

1. Open up an empty workspace.
2. Attempt to run a build task (which doesn't exist yet), prompting the message,
`No build task to run found. Configure build task`
When you click on this message or hit enter, the next dialog simply flashes open for a moment before closing, not allowing any input.

Previously, this used to show you detected tasks, or otherwise automatically create an empty template `tasks.json` file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@sarahkittyy thanks for reporting this! I fixed it yesterday, so it should be available in the next insiders build of VS Code.

**Comment by sarahkittyy** [comment]
@alexr00 This issue is still occuring as of version:
```
1.40.0-insider
31f577ec88dc96ad2028699fb597b19022224b46
x64
```

**Comment by alexr00** [comment]
Thanks for checking this! Should be fixed for real now.
