### ISSUE TITLE
Emmet: error handler for read function

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#8324]
Help to testing #8207 
- VSCode Version: 1.3.0-insiders
- OS Version: Windows 10 Pro (build 10586.420)

Steps to Reproduce:
1. Create file with `css` syntax
2. Create selector with `backdround-image` property and fake URL value (for example, `http://test-28062016.com/`)
3. Run `Emmet: Encode\Decode data:URL image`

**Error**:

```
index.html:28 [uncaught exception]: Unable to read http://test-28062016.com/: Error: getaddrinfo ENOTFOUND test-28062016.com test-28062016.com:80
```

**Comment by mrmlnc** [comment]
Original **read** function: https://github.com/emmetio/emmet/blob/master/lib/plugin/file.js#L72-L118

As an option:

```ts
import {text as requestText} from 'vs/base/node/request';
import {readFile, mkdirp, writeFile} from 'vs/base/node/pfs';

// fileAccessor
export function read(path: string, callback: any): any {
	if (isURL(path)) {
		requestText({ url: path }).then(buf => callback(null, buf), err => {
			//
		});
	} else {
		readFile(path).then(buf => callback(null, buf), err => {
			//
		});
	}
}
``

**Comment by mrmlnc** [comment]
Original Emmet **read** function: https://github.com/emmetio/emmet/blob/master/lib/plugin/file.js#L72-L118

As variant:

#### vs/base/node/request.ts

```ts
export function buffer(opts: IRequestOptions): TPromise<string> {
	return request(opts).then(pair => new Promise((c, e) => {
		if (!((pair.res.statusCode >= 200 && pair.res.statusCode < 300) || pair.res.statusCode === 1223)) {
			return e('Server returned ' + pair.res.statusCode);
		}

		if (pair.res.statusCode === 204) {
			return c(null);
		}

		let buffer: Buffer[] = [];
		pair.res.on('data', d => buffer.push(d));
		pair.res.on('end', () => c(Buffer.concat(buffer)));
		pair.res.on('error', e);
	}));
}
```

#### vs/workbench/parts/emmet/node/fileAccessor.ts

```ts
import {buffer as requestBuffer} from 'vs/base/node/request';
import {readFile, mkdirp, writeFile} from 'vs/base/node/pfs';

export function read(path: string, callback: any): any {
	if (isURL(path)) {
		requestBuffer({ url: path }).then(buf => callback(null, bts(buf)), err => {
			//
		});
	} else {
		readFile(path).then(buf => callback(null, bts(buf)), err => {
			//
		});
	}
}
```

**Comment by mrmlnc** [comment]
Behavior in Sublime Text:
![image](https://cloud.githubusercontent.com/assets/7034281/16485040/4dab32ca-3ec5-11e6-8e22-e96a7558c76f.png)

Behavior in Atom:
![2016-06-30_13-23-13](https://cloud.githubusercontent.com/assets/7034281/16485159/010818b0-3ec6-11e6-8e5f-8540b3da6272.gif)

**Comment by ramya-rao-a** [comment]
Closing this issue as the related implementation for encode/decode no longer exists.
#27978 tracks the new feature request for encode/decode
