### ISSUE TITLE
Can't drag to select linkified text in the debug console

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83264]
```js
console.log('http://microsoft.com')
```

- Run a program with the above text
- Click to select the text in the debug console
- I can't do it unless I hold cmd like I am going to click the link

![Oct-24-2019 18-05-01](https://user-images.githubusercontent.com/323878/67535758-e33e3200-f688-11e9-894f-2c955440a6e5.gif)

- On the third try I am holding cmd

**Comment by isidorn** [comment]
Good catch, I acknowledge the issue.
@dgozman let me know if you are interested in fixing this. Otherwise I can also look into it once I am back from vacation in 2 weeks.
