### ISSUE TITLE
Explorer seems not case sensitive ?

### ISSUE THREAD

**Issue by MartinXM** [microsoft/vscode#83267]
It seems I can not create files with same characters but difference cases.

For example:
If I already have abc.py in my directory, I can not create Abc.py in explorer. 

![image](https://user-images.githubusercontent.com/6717931/67537480-2d1d2b80-f70e-11e9-9712-ec754f5275dd.png)

![image](https://user-images.githubusercontent.com/6717931/67537497-3efece80-f70e-11e9-98b3-27caad96ecbd.png)

Also, if files already exists (abc.py and Abc.py), the Abc.py would be invisible in explorer, but can still be founded by searching. 

- VSCode Version: 1.39.2
- OS Version: MacOS 10.15

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
You are on a mac. And explorer respects how your mac is behaving.
Try your native mac finder and you will also see it is not possible what you are trying to do.
