### ISSUE TITLE
Replace in search viewlet is hard to discover

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8327]
Refs: https://github.com/Microsoft/vscode/issues/8184

I think what we have now is a good start but I fear that people will not find the affordance to bring search into replace mode:

![image](https://cloud.githubusercontent.com/assets/900690/16414775/fb54687a-3d39-11e6-9c0c-3cebd969d899.png)

We should look into alternatives how to design this experience.

**Comment by bpasero** [comment]
Maybe one idea would be to change the message in the input field to somehow indicate how to get into replace mode?

**Comment by sandy081** [comment]
How about expanding the Replace input box by default and users can collapse it if they do not want to do replace. This will help the user in discovering replace for the first time. 

Also we can have a entry in Views menu for replace which will open replace by default?

**Comment by bpasero** [comment]
Yes, all good ideas to begin with 👍

**Comment by sandy081** [comment]
duplicates #8284
