### ISSUE TITLE
I can not preview the sequence diagram in default Markdown Preview tab

### ISSUE THREAD

**Issue by NigelBoxing** [microsoft/vscode#83271]
- VSCode Version: 1.39.2
- OS Version:  Linux x64 4.15.0-30deepin-generic  && Windows 10 1903
Steps to Reproduce:

1. creat a Markdown file
2. input something like
\```sequence
\```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
For example: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid
