### ISSUE TITLE
Add keybind for intellisense line up/down

### ISSUE THREAD

**Issue by reZach** [microsoft/vscode#83270]
I frequently use alt+j and alt+k to move up and down intellisense options while using Visual Studio, I would _love_ to have these same keybinds in VSCode.

Binding to cursorUp/cursorDown does not give the functionality that you can achieve in Visual Studio, in fact, doing so simply moves up your cursor and exits the intellisense window in VSCode.

I would happily work on a PR if someone could point me to the right direction. Thanks!

**Comment by usernamehw** [comment]
```js
{
	"key": "alt+j",
	"command": "selectNextSuggestion",
	"when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
},
{
	"key": "alt+k",
	"command": "selectPrevSuggestion",
	"when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
}
```

**Comment by alexr00** [comment]
Good suggestion @usernamehw !
