### ISSUE TITLE
Web Firefox: dropping a file onto itself navigates the page

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83287]
Steps to Reproduce:

1. run from web (Firefox)
2. dnd a file onto itself
3. 🐛 => the page navigates

![image](https://user-images.githubusercontent.com/900690/67561398-0b777080-f71d-11e9-9e5b-720cfb5c2ec3.png)

This may be a general tree issue, not sure.

**Comment by joaomoreno** [comment]
It's 2013 all over again.

![image](https://user-images.githubusercontent.com/22350/67579020-f530db00-f743-11e9-8720-58bfef685878.png)

**Comment by bpasero** [comment]
Up for grab.
