### ISSUE TITLE
When selection clipboard is disabled, the middle button pastes if released outside editor

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#83282]
Extracted from @AndBroPLAYipp in https://github.com/microsoft/vscode/issues/64856#issuecomment-545897875

---

Updated to insider build;
The middle mouse button paste is disabled which is awesome.
BUT; If you move the mouse, while holding middle mouse, any were outside the document you will instantly paste were your line cursor is located.
This include; top document path and tabs, left tab panel, integrated terminal. and outside the document.

**Comment by alexandrudima** [comment]
To verify, set `editor.selectionClipboard: false` and drag from the editor and release outside VS Code. It should not paste the selection clipboard.

**Comment by joaomoreno** [comment]
@alexandrudima I'm testing from `master`. Yeah those are the steps I'm doing. They do nothing in my system, there's no data being dragged out of VS Code in any case. But maybe my i3 setup is preventing stuff from happening. I'll let someone else with Ubuntu test this.

**Comment by aeschli** [comment]
Verified on Ubuntu 18.04.3
