### ISSUE TITLE
Web: cannot go fullscreen or copy via Quick Open from Firefox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83288]
Looks like:
* we need to support the `moz`-prefix
* it still fails when doing that for me:

`Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler.`

**Comment by rebornix** [comment]
> ... was not called from inside a short running user-generated event handler

This is related to how a command is being executed. For example, Toggle Full Screen from Menu works, run the same command from Quick Open doesn't and the reason for that is we do `setTimeout` to let Quick Open close first. The `setTimeout` tricks Firefox and it longer thinks it's from a user-generate event ;(

https://github.com/microsoft/vscode/blob/749a0232bf96b9a0a3cb2f93a79981708327f44e/src/vs/workbench/contrib/quickopen/browser/commandsHandler.ts#L316-L338

So this affects everything that requires a `user generated event`, for example Copy and Paste. If we run Copy from the Command Palette, it fails for the same reason. I like how Firefox tries its best to be safe but then we need to look into how many actions/commands are affected (IMO no a lot).

**Comment by bpasero** [comment]
@rebornix good finding. If you add the code for supporting fullscreen for Firefox, I can look into fixing quick open. We may have to add a firefox check there...

**Comment by bpasero** [comment]
Ah I get it, fullscreen works already, just not from quick pick 👍
