### ISSUE TITLE
PickProcess don't work in ArchLinux

### ISSUE THREAD

**Issue by Deliay** [microsoft/vscode#83290]
Issue Type: <b>Bug</b>

launch configuration:
```
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach by Process ID",
      "processId": "${command:PickProcess}",
      "port": 9229
    }
  ]
```

no any process can pick when execute `PickProcess` command :
![Screenshot_20191025_180308](https://user-images.githubusercontent.com/5661435/67562945-46e06200-f752-11e9-8ca8-6d82d39c49ce.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.7-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3955)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|62.80GB (54.95GB free)|
|Process Argv|./|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
csharp|ms-|1.21.5

</details>

**Comment by isidorn** [comment]
pick process commend is coming from the node adapter, I also think @weinand is the author thus forwarding to him
aslo fyi @roblourens

**Comment by Deliay** [comment]
![Screenshot_20191028_132033](https://user-images.githubusercontent.com/5661435/67653768-db7ed600-f985-11e9-89b1-70926e3ef93b.png)

seem resolved in latest release
