### ISSUE TITLE
Web: cross browser testing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83296]
Refs: none

- [x] macOS @mjbvz
- [x] Linux @octref
- [x] Windows @sbatten
- [x] iPadOS @rebornix 

Complexity: 4

* Make sure you have latest browsers installed:
  * macOS: Safari, Firefox
  * Linux: Firefox
  * Windows: Firefox

Do exploratory testing in the assigned browsers (macOS: both Safari and Firefox) and report issues here (use the browser specific labels to signal the browser). 

**Also watch out for rendering issues and messages printed to the developer console that could hint to issues.** 

Areas:
* Editor usage
* Layout / Grid / View Manipulation
* File manipulation
* Search
* Debugging (e.g. debug hello world extension)
* Terminal
* Problems
* SCM, Diff
* Extensions Management
* Settings
* etc...

**Comment by bpasero** [comment]
@rebornix fyi I added you for iPadOS testing (if possible) with keyboard and mouse. Feel free to pass along a test plan item in return to me 👍

**Comment by octref** [comment]
@bpasero Not sure if I should assign to you or the area owners, I assigned you for now so it show up in your notification, feel free to give to others.

**Comment by bpasero** [comment]
That is ok, thanks.

**Comment by octref** [comment]
Also I didn't open an issue, but Ctrl+Shift+P is bound by Firefox and not being able to override that is not feeling good.

**Comment by rebornix** [comment]
Finished my first round of iPadOS/iOS testing, in overall it works as expected. Some core components feel wrong for following reasons 

* We didn't listen to Pointer Events https://github.com/microsoft/vscode/issues/83719
* We didn't handle touch down/drag/move properly https://github.com/microsoft/vscode/issues/83720
* iOS particular safe area / visual area management 

Rest of the issues are mostly minor ux issues from my limited testing. IMO after we have above three major painpoints resolved then we can do more testing on iOS/iPadOS/touchscreen to see how we can provide smooth experience.
