### ISSUE TITLE
Web: simple file dialog acts up in Firefox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83292]
Steps to Reproduce:

1. run web from Firefox
2. File > Open...
3. play around with typing paths and hit enter, the picker does not like that. The OK button does not seem to work either

![image](https://user-images.githubusercontent.com/900690/67564322-01587080-f723-11e9-914c-3d3510a7721c.png)

**Comment by alexr00** [comment]
Looks like a Firefox bug: https://stackoverflow.com/questions/33480562/firefox-document-execcommandinserttext
However, I can have better fallback behavior.

**Comment by alexr00** [comment]
Added better fallback, but it does mean that the undo buffer for the simple file dialog will be broken in Firefox and anywhere else that insertText doesn't work.

**Comment by joaomoreno** [comment]
Thanks for this! :clap:
