### ISSUE TITLE
Debugger stopping randomly

### ISSUE THREAD

**Issue by AlexPoirier1** [microsoft/vscode#83304]
Issue Type: <b>Bug</b>

Since I updated yesterday, my debugger keeps stopping in random files (but always the same files each executions) like `node_modules/mongodb/node_modules/bson/lib/bson/long.js` and things like that. 

![image](https://user-images.githubusercontent.com/7539455/67571559-3d2f0e00-f702-11e9-94e8-74cf72dca1a5.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 9, 8|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
twig-to-jsx|ale|1.2.1
swagger-viewer|Arj|2.2.2
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
code-runner|for|0.9.14
gc-excelviewer|Gra|2.1.32
output-colorizer|IBM|0.1.2
vscode-styled-components|jpo|0.0.26
intellij-idea-keybindings|k--|0.2.36
vscode-mocha-sidebar|mat|0.22.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
python|ms-|2019.10.44104
azure-account|ms-|0.8.6
vscode-typescript-tslint-plugin|ms-|1.2.2
language-liquid|nei|0.1.1
indent-rainbow|ode|7.4.0
ruby|reb|0.25.3
todotasks|san|0.5.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
vscode-icons|vsc|9.5.0
gitblame|wad|3.0.1
vscode-todo-highlight|way|1.0.4
ReactSnippets|xab|2.3.0

(5 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can you reproduce with vscode insdiers https://code.visualstudio.com/insiders/
If yes, can you please share exact minimal reproducable steps. Thank you

**Comment by AlexPoirier1** [comment]
I just tried running the same code in command line and I got this
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003d035 node::Abort() [/usr/local/bin/node]
 2: 0x10003d23f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
```
So I guess this is why the debugger stops ! It wasn't very clear since the error didn't trickle back to the console output. I will go ahead and close this issue. Thanks!
