### ISSUE TITLE
Editor colors subtly washed out in Insiders build.

### ISSUE THREAD

**Issue by phyllisstein** [microsoft/vscode#83306]
This sounds not wholly uncrazy, but it seems like the Insiders build is rendering editor colors a little off. To my eye, they’re just _a little_ less vibrant, even on a brand-new, extension-free, unconfigured installation:

<img width="1680" alt="Screen Shot 4 copy" src="https://user-images.githubusercontent.com/2207980/67571032-ee34a900-f700-11e9-992f-c9d4e20ed13f.png">

On my display, I get...

| | Code | Code Insiders |
|:--:|:--:|:--:|
| **Blue** | `#569cd6` | `#6398cb` |
| **Pink** | `#c586c0` | `#bc8abd` |
| **Green** | `#5cc9b0` | `#71c6b1` |

It’s subtle in Dark+, which is... well, dark. But once you start switching themes around it becomes way more pronounced. Here’s Monokai Pro:

<img width="1680" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/2207980/67571287-964a7200-f701-11e9-8a6e-5ae1a4882706.png">

Can’t imagine this is the highest of priorities, but I noticed it as soon as I switched over to Insiders to avail myself of the fix for #82346.

---

- VSCode Version: 1.40.0-insider
- OS Version: macOS 10.15 (19A582a)

Steps to Reproduce:

1. Run the Insiders build.
2. Wonder if you’re going nuts for a couple minutes.
3. Take screenshots.
4. Eyedropper them in Photoshop.
5. Okay, it’s not just you.
6. Probably.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mitchellwarr** [comment]
Getting this in the normal build after upgrading to 1.40, but seems like a greater difference than listed here. I've no before and after however as I didn't expect to need to take a screenshot before upgrading

**Comment by deepak1556** [comment]
Thanks for the report @phyllisstein @mitchellwarr , I would like to continue the conversation in https://github.com/microsoft/vscode/issues/83306

**Comment by phyllisstein** [comment]
Sure thing. What's the linked issue?

**Comment by deepak1556** [comment]
Sorry here is the link https://github.com/microsoft/vscode/issues/84154

**Comment by phyllisstein** [comment]
Thanks!
