### ISSUE TITLE
Wait doesn't wait when using with extensionDevelopmentPath

### ISSUE THREAD

**Issue by olivernybroe** [microsoft/vscode#83301]
- VSCode Version: 1.39.0
- OS Version: macOS 10.14.4 (18E226)

Steps to Reproduce:
1. Open terminal and run `code --wait --extensionDevelopmentPath=path`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce.

**Comment by olivernybroe** [comment]
![example](https://user-images.githubusercontent.com/5870441/67670905-29d7a900-f975-11e9-9e2c-20357f3ebe70.gif)
Here is an example video of it happening. 

@bpasero What other information do you need? I don't really see what I can give here to help as this is basically just a one step error.

**Comment by bpasero** [comment]
I cannot reproduce this is the issue:

![image](https://user-images.githubusercontent.com/900690/67671494-5c35d600-f976-11e9-9283-2716474d6bc5.png)

**Comment by olivernybroe** [comment]
Hmm, might be a Mac specific bug or a bug specific for my system I guess.

**Comment by bpasero** [comment]
I also tried Mac, sorry. Does it work otherwise when you do not add that parm?

**Comment by olivernybroe** [comment]
@bpasero Yep, wait works just fine.
I'll upgrade to MacOs Catalina soon and see if the error is still there. 
Else I guess it's some weird bug on my computer, hopefully no one else have it.

**Comment by bpasero** [comment]
Ok let's close it then.

**Comment by olivernybroe** [comment]
@bpasero So it was fixed by updating to MacOS Catalina. 

Did you test on MacOS Majove or Catalina?

**Comment by bpasero** [comment]
I am still on Mojave.

**Comment by olivernybroe** [comment]
Alright, then it was specific to me. That's a relief
