### ISSUE TITLE
Search dont find content in files with too long file paths

### ISSUE THREAD

**Issue by alfnielsen** [microsoft/vscode#83305]
_I have search for duplicate bug, tested this in 'insider' and run it with 'code --disable-extensions'._

Search dont find string in files with to long file paths.
In my test the file that was not found, had a total path length 227.
When I move the file up to a shorter path, it had no problem finding it.

Note: If the file it opened in vsc, the search also find it?
And when the file is closed it again dont find it.

**VSCode Version:**

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

 **OS Version:**

Edition: Window 10 Pro
Version: 1903
OS build: 18362.418

Steps to Reproduce:

1. Create a folder structure with a total length more then 227
2. Create a file there with some content that you can search
3. Go into Search and search for the content
3.1 Try the search with the file open in vsc and where its not open in vsc.

**Comment by monkeythedev** [comment]
Same error here:
![image](https://user-images.githubusercontent.com/53383860/77601921-6dc2e000-6f0c-11ea-9cf4-e606b10a34ca.png)
