### ISSUE TITLE
Auto-unindent triggered too early for ruby end markers

### ISSUE THREAD

**Issue by jonmchan** [microsoft/vscode#83309]
Issue Type: <b>Bug</b>

1. Load up a ruby file. Paste in the following code:

```
def test 
  if true
  end
end
```

2. Try to type the word `endpoint` on a new line within the if statement:

Actual (wrong tabbing for endpoint): 
```
def test 
  if true
  endpoint = "123"
  end
end
```

Expected:

```
def test 
  if true
    endpoint = "123"
  end
end
```

Details: 
Whenever the letters "end" is typed, VSCode instantly unindents that line considering the end of the block. This is erroneous because it does not allow any variables or functions that begin with the letters "end" to be used such as `endpoint` in the example. 

The autoindent / auto-unindent functionality should not be triggered until a space or newline is created. /^end/ is too rapid of a trigger.

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rails|bun|0.13.1
vscode-gemfile|bun|0.0.2
solargraph|cas|0.21.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
endwise|kai|1.4.2
debugger-for-chrome|msj|4.12.0
rails-run-spec-vscode|nok|0.1.3
ruby|reb|0.25.3
slim|sia|0.1.2
code-spell-checker|str|1.7.18
common-pack|Swe|0.2.9
ti-vscode-extensions|Tai|0.0.1

</details>

**Comment by rebornix** [comment]
This is a limitation of current architecture, the auto indentation is based on regex indentation rules and not stateful. Considering it's complicated and hard to make it sound, we recommend to use formatters to ensure a correct indentation on type.
