### ISSUE TITLE
Visual Studio terminal can't open Windows subsystem Linux folder

### ISSUE THREAD

**Issue by aliarousyoucef** [microsoft/vscode#83315]
Issue Type: <b>Bug</b>

I'm working with Visual Studio code and I need to open Windows subsystem Linux terminal in a specific location `/Home/Workspace/OZVA/Staging` by right-clicking the folder in the explorer window, But Windows subsystem linux point to root/folder and not the folder requested.

This function work with Powershell terminal.
  [1]: https://i.stack.imgur.com/SYJ70.png

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

Extensions: none

**Comment by Tyriar** [comment]
Please provide more steps, I can set my default shell to WSL then right click on folder in the explorer to open a terminal and it works fine. Also try insiders to see if it's fixed https://code.visualstudio.com/insiders/
