### ISSUE TITLE
Button "Find in selection" poor background contrast when active

### ISSUE THREAD

**Issue by nicolagranata** [microsoft/vscode#83317]
Issue Type: <b>Feature Request</b>

Hi, button "Find in selection" has a low background contrast when it's active (in dark themes) and the active background color doesn't seem to be customizable in the themes (or am I not able to find the right rule for customization?).

Thanks,

Nicola Granata

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.19008

**Comment by usernamehw** [comment]
```js
"workbench.colorCustomizations": {
	"inputOption.activeBackground": "#ffff00",// all themes
	"[Default Dark+]": {// target one theme
		"inputOption.activeBackground": "#ff0000",
	},
}
```

**Comment by nicolagranata** [comment]
Hi,
"inputOption.activeBackground" colorize background of option IN Find/Replace field (cyan circle) BUT NOT background of button "Find in selection" (red circle) - see attachment.
Thanks,
Nicola Granata

![vscode_find_replace_find_in_selection_issue](https://user-images.githubusercontent.com/49106793/67582919-e7cb1f00-f74a-11e9-8352-c7ee9be18a47.jpg)

**Comment by usernamehw** [comment]
Strange, it also doesn't toggle when pressing <kbd>Spacebar</kbd>.

@alexr00

**Comment by rebornix** [comment]
This is because Find In Selection is not using the same checkbox element used by Find Options.
