### ISSUE TITLE
Web: compact menu icon moves on click (Safari)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83318]
Steps to Reproduce:

1. open web in Safari
2. click on compact menu

=> 🐛 it moves

![before](https://user-images.githubusercontent.com/900690/67579154-31fcd200-f744-11e9-877f-50665d302797.gif)

**Comment by bpasero** [comment]
@sbatten I diagnosed this and see 2 issues:
* the menu items are not removed from the DOM when menu is not showing (https://github.com/microsoft/vscode/issues/83638)
* you seem to be using `visibility: none` instead of `display: none` to hide the menu items, is there any particular reason? using `display: none` the issue is not as bad anymore (I only see one initial jump)

I suggest we use `DOM.hide()` / `DOM.show()` (our helper), but I am not sure if you rely on the behavior of visibility?

**Comment by sbatten** [comment]
I mentioned the reasoning in the linked issue, but in the compact case we can remove them from the DOM safely so patching that should help here.
