### ISSUE TITLE
Icons appearing blurry and thicker

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83316]
![image](https://user-images.githubusercontent.com/35271042/67578349-1ddeb380-f6f7-11e9-9716-f6aaa4edf557.png)

Comparing stable (left) vs insiders (right) it appears that the new activity bar icons that are using the icon font are thicker for some reason.

**Comment by misolori** [comment]
Looking into this more, I realize that all of our icons are slightly off-grid, which makes them pixelated as well:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/35271042/67890785-9639e000-fb0e-11e9-8ac4-cd42af15d1ba.png">

Compared to how they are designed:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/35271042/67890848-b49fdb80-fb0e-11e9-9aa7-bac408401128.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/35271042/67890881-c1bcca80-fb0e-11e9-9b84-706365f8504b.png">

**Comment by misolori** [comment]
My findings were about how some platforms/browsers render font glyphs and I was able to update these via https://github.com/microsoft/vscode/pull/83951. However, it appears that the original issue with the activity bar appearing blurry is related to an issue where icons rendered on Windows appear bold. Below is a comparison of macOS (top) and Windows (bottom):

![image](https://user-images.githubusercontent.com/35271042/68165293-ec928e80-ff13-11e9-9708-a2d527a0b388.png)

**Comment by misolori** [comment]
@deepak1556 would you know if this is related to an electron change (possibly https://github.com/microsoft/vscode/issues/59887) that affects window font renderings?

**Comment by misolori** [comment]
@deepak1556 wondering if this is related to the font rendering issue? https://github.com/microsoft/vscode/issues/84154

**Comment by Guema** [comment]
Noticed this too.
It is probably Windows only as you said.
Saw screenshots of MacOS or Linux, and it seems not suffering from it.
As icons seems to be blurrier as they was, it could be related to Electron 6 or new chromium version.
Probably depending of the way it is rendered (SVG ? Font-Icon ?)

**Comment by Guema** [comment]
May be related to #84698

**Comment by bpasero** [comment]
@misolori @Guema how does it look like with todays insider build? Make sure to update if you did not yet: https://code.visualstudio.com/insiders/

Version must be `b6a486e34fe3715f6edec0cdb11138b1672d33bd` (check from about dialog).

**Comment by Guema** [comment]
I downloaded last Insider build, looks like the problem is still here

![image](https://user-images.githubusercontent.com/8943532/68847340-cf597f00-06ce-11ea-93e2-248bcc3cab67.png)

**Comment by Guema** [comment]
Here is a 1.39.2 (Left) <-> Insiders (Right) build comparison

![image](https://user-images.githubusercontent.com/8943532/68847949-c6b57880-06cf-11ea-8c94-82732a5d8b8d.png)

![image](https://user-images.githubusercontent.com/8943532/68848121-0d0ad780-06d0-11ea-89d3-7a8f2cb7b195.png)

**Comment by bpasero** [comment]
Oh I am sorry, there is a change missing on my end to get this right. Hold on...

**Comment by bpasero** [comment]
@Guema how about: https://az764295.vo.msecnd.net/insider/dccaf037f35ed2d73fa97e48e8e053887d0366b1/VSCode-win32-x64-1.41.0-insider.zip

**Comment by eamodio** [comment]
@bpasero That version looks much better to me (its no longer grayscale AA). Although just like the editor text, it is still much "smoother" than 1.39.2 was.

**Comment by bpasero** [comment]
@eamodio can you spot a difference in the area of the activity bar or just in general?

**Comment by Guema** [comment]
> 
> 
> @Guema how about: https://az764295.vo.msecnd.net/insider/dccaf037f35ed2d73fa97e48e8e053887d0366b1/VSCode-win32-x64-1.41.0-insider.zip

Seems closer to the initial look, even if there it is still different when looking closer.

![image](https://user-images.githubusercontent.com/8943532/68876771-46aa0580-0705-11ea-8250-cd3d8f03a5d8.png)

(1.39.2 vs this insiders build vs Exploration)

![image](https://user-images.githubusercontent.com/8943532/68877061-bb7d3f80-0705-11ea-8bb2-d9c4520712f1.png)

![image](https://user-images.githubusercontent.com/8943532/68877232-08f9ac80-0706-11ea-88d0-af8ac8b87629.png)

The gear icon is where it is the more visible. the 3 versions are different.

Finally, here is a Windows-Zoomed version where we can see the differences well. It seems related to anti-aliasing method :

![image](https://user-images.githubusercontent.com/8943532/68877464-6b52ad00-0706-11ea-9921-3ee116a3d744.png)

**Comment by bpasero** [comment]
@Guema i am not sure about using the exploration build, that one lags behind a lot of changes we did and only comes with Electron 7. Best to compare current stable 1.40.1 with the version from the zip I posted.

**Comment by Guema** [comment]
> 
> 
> @Guema i am not sure about using the exploration build, that one lags behind a lot of changes we did and only comes with Electron 7. Best to compare current stable 1.40.1 with the version from the zip I posted.

Yeah i could do that, but it seems that launching an instance of the same build type just launch an instance of the already launched editor (If i want to compare 1.39, 1.40 and insiders) I already tried to launch insiders production build and the one you shared, but only could launch one of them at the time

**Comment by bpasero** [comment]
@Guema you can solve this by providing (from the command line when putting the full path to the code EXE): `--user-data-dir <unique dir>`

**Comment by eamodio** [comment]
@bpasero in general, but imo its most noticeable on the activity bar

**Comment by bpasero** [comment]
I see a difference still (left stable 1.39, right latest insiders):

![image](https://user-images.githubusercontent.com/900690/68923317-544fa180-077e-11ea-9f99-df374774843d.png)

I am not sure what the cause is, possibly Chrome decides to render colors differently when transparency is applied or we changed something with our Codicons that could have an impact.

@misolori I can get it to look almost the same as before if I use a stronger color (#AAAAAA) for the inactive foreground:

![image](https://user-images.githubusercontent.com/900690/68923551-dc35ab80-077e-11ea-98ac-bdebf8f3d9ea.png)

Unfortunately this is probably platform dependent and also should account for the active color, not be hardcoded.

**Comment by bpasero** [comment]
Oh wait, there was a change in opacity in insiders from 0.6 to 0.4, that could explain it!

**Comment by bpasero** [comment]
Yeap I see no more difference when manually changing to the previous transparency:

![image](https://user-images.githubusercontent.com/900690/68924512-4fd8b800-0781-11ea-8d7c-d73406c308a2.png)

**Comment by eamodio** [comment]
@bpasero I still see a difference in your last screen shot -- the left on is thinner and less fuzzy. But yeah, with the transparency change they are indeed closer.

**Comment by kanlukasz** [comment]
> 
> 
> I still see a difference in your last screen shot -- the left on is thinner and less fuzzy. 

I see the same

**Comment by bpasero** [comment]
> @bpasero I still see a difference in your last screen shot -- the left one is thinner and less fuzzy.

Well to be fair, `master` includes the changes so that all icons in the activity bar are rendered with LCD-anti-aliasing, while previously it was greyscale. So I would think you notice a difference already because of that. 

I think we have to live with the fact that browsers change and accept that. I do not think this is an issue on our end nor Electron.

**Comment by Guema** [comment]
imo the fix you done make it far more close to initial design.
It is really acceptable now.
If your UX team feels like they need to fine-tune it, they could probably re-fit the icons or ask for font-icons generator changes.
Thanks for your time and your work @bpasero

**Comment by misolori** [comment]
Removing milestone as this was handled by https://github.com/microsoft/vscode/issues/84584
