### ISSUE TITLE
High CPU and RAM consumption

### ISSUE THREAD

**Issue by khteh** [microsoft/vscode#83319]
Issue Type: <b>Performance Issue</b>
![VSCodePerformance](https://user-images.githubusercontent.com/3871483/67838330-073bc080-fb2c-11e9-8738-5cc0300ecc53.png)

[CPU-20191025T144926.821Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/3772577/CPU-20191025T144926.821Z.cpuprofile.txt)
[DevToolsJavascript.profile.txt](https://github.com/microsoft/vscode/files/3772736/DevToolsJavascript.profile.txt)

```
$ code --status
[2874:1025/225138.768555:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS Version:       Linux x64 5.0.0-32-generic
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1971)
Memory (System):  23.20GB (3.86GB free)
Load (avg):       5, 7, 8
VM:               0%
Screen Reader:    no
Process Argv:     --inspect-extensions=8888
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  unavailable_off
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    1	   119	 16200	code main
    0	    24	 16202	   zygote
    5	   261	 16244	     window (Running Extensions - Biz4x (Workspace) - Visual Studio Code)
    6	   214	 16274	       extensionHost
    0	   119	 16608	         /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.razor/rzls -lsp --logLevel None
    0	     0	 16646	         bash /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/run -s /usr/src/4xlabs/bz-frontend/bz-frontend.sln --hostPID 16274 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.razor/OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	   974	 16650	           /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/bin/mono /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.omnisharp/1.34.5/omnisharp/OmniSharp.exe -s /usr/src/4xlabs/bz-frontend/bz-frontend.sln --hostPID 16274 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.razor/OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	  1022	 16297	       watcherService
    0	    48	 16370	       searchService
    0	     0	 19554	       /bin/bash
    0	    71	 16320	     shared-process
    1	    71	 16231	   gpu-process

Workspace Stats: 
|  Window (Running Extensions - Biz4x (Workspace) - Visual Studio Code)
|    Folder (bz-frontend): more than 27325 files
|      File types: dll(7798) cs(2786) svg(1400) png(1037) jpg(928) webp(925)
|                  pdb(702) json(551) html(346) cache(300)
|      Conf files: csproj(43) package.json(11) sln(2) launch.json(2)
|                  tasks.json(2) gulp.js(2) settings.json(1) grunt.js(1)
|      Launch Configs: coreclr(3)
```
https://github.com/microsoft/vscode/issues/83275#issuecomment-546225314

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1599)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 11|
|Memory (System)|23.20GB (3.62GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   166	 24486	code main
    0	    24	 24490	   zygote
    2	   499	 24547	     window (ComplianceClient.cs - Biz4x (Workspace) - Visual Studio Code)
    4	   309	 24616	       extensionHost
    0	   119	 24880	         /home/khteh/.vscode/extensions/ms-vscode.csharp-1.21.5/.razor/rzls -lsp --logLevel None
    0	     0	 24617	       /bin/bash
    0	   119	 24717	       searchService
   13	    95	 24686	     shared-process
    2	   238	 26869	     window (appsettings.json - RabbitMQ (Workspace) - Visual Studio Code)
    4	   190	 27141	       extensionHost
    0	    48	 28466	         /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=27141
    0	    48	 27191	       watcherService
    6	    95	 24534	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (appsettings.json - RabbitMQ (Workspace) - Visual Studio Code)
|  Window (Worker.cs - Untitled (Workspace) - Visual Studio Code)
|  Window (ComplianceClient.cs - Biz4x (Workspace) - Visual Studio Code)
|    Folder (WorkQueue): 77 files
|      File types: json(10) cache(10) dll(6) pdb(4) cs(4) props(2) csproj(2)
|                  targets(2) CopyComplete(2) txt(2)
|      Conf files: csproj(2) sln(1)
|    Folder (RabbitMQ): 428 files
|      File types: dll(181) cs(61) json(30) cache(27) pdb(22) txt(7)
|                  CopyComplete(4) csproj(4) props(3) targets(3)
|      Conf files: csproj(4) sln(1)
|    Folder (bz-frontend): more than 27324 files
|      File types: dll(7798) cs(2786) svg(1400) png(1037) jpg(929) webp(925)
|                  pdb(702) json(551) html(346) cache(300)
|      Conf files: csproj(43) package.json(11) sln(2) launch.json(2)
|                  tasks.json(2) gulp.js(2) settings.json(1) grunt.js(1)
|      Launch Configs: coreclr(3);
```

</details>
<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
add-reference|adr|1.0.2
namespace|adr|1.1.2
net-core-starters-pack|bla|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
supersharp|cra|0.1.4
vscode-quick-select|dba|0.2.8
netcore-extension-pack|dog|0.8.0
netcore-snippets|dog|0.2.7
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
extbundles-csharp|Fel|2.0.0
vscode-solution-explorer|fer|0.3.5
scaffold|fir|1.0.0
code-runner|for|0.9.14
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.1
auto-using|Fud|0.7.9
todo-tree|Gru|0.0.160
mysql-syntax|jak|1.3.1
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
vscodeilviewer|jos|0.0.1
docomment|k--|0.1.8
dotnet-core-essentials|Kis|0.0.8
csharpfixformat|Leo|0.0.84
csharp-colors|log|0.1.7
dotnet-core-commands|mat|1.0.6
vscode-docker|ms-|0.8.1
mssql|ms-|1.7.0
csharp|ms-|1.21.5
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.1
quicktype|qui|12.0.46
awesome-dotnetcore-pack|sal|1.8.0
copy-text|sal|0.4.3
msbuild-project-tools|tin|0.2.55
vscode-todo-highlight|way|1.0.4
libman|wei|0.1.1
highlight-trailing-white-spaces|yba|0.0.2

</details>

**Comment by jrieken** [comment]
Anything specific? The screen shot shows nothing abnormal, the CPU profile does tho. Where did you capture that? Is that the extension host?

**Comment by jrieken** [comment]
It looks like constantly processes (language servers) die and get restarted - over and over again. What do your logs show?

**Comment by khteh** [comment]
What logs?

**Comment by khteh** [comment]
This is how I captured the CPI profile: https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by jrieken** [comment]
F1 > Show Logs > Extension Host

**Comment by khteh** [comment]
[vscode.log](https://github.com/microsoft/vscode/files/3787495/vscode.log)

**Comment by jrieken** [comment]
Thanks. This seems to be the `jchannon.csharpextensions-1.3.0`-extension
