### ISSUE TITLE
Selecting command "Debug: Enable All Breakpoints" doesn't fully enable

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/vscode#83323]
Issue Type: <b>Bug</b>

If you open the Debug view and use the toggle button to "Deactive Breakpoints" then later use the command "Debug: Enable All Breakpoints" it does not enable them.

![image](https://user-images.githubusercontent.com/2856501/67589132-9bf98500-f70c-11e9-853d-6da006a241f4.png)

It seems the setting or Activation/Deactivation is a different higher level than the Enable/Disable which is lower level.

![image](https://user-images.githubusercontent.com/2856501/67589135-9f8d0c00-f70c-11e9-83ab-1dcf31f29bef.png)

The Enable/ Disable correctly toggles the individual checkmarks but it has no effect if breakpoints are still Deactivated.

I see two solutions:
1. Change the command "Enable All Breakpoints" to also ensure they are activate, not just enabled.
This could be riskier change if people don't want it, although I don't see what intent you could have for trying to enable them and them still not being enabled.

2. Add new commands to toggle Activation.
Debug: Activate Breakpoints
Debug: Deactivate Breakpoints

These would directly have same affect as clicking the button on the Debug view. It would also be non breaking.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (13.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-markdownlint|Dav|0.31.1
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.2
docs-markdown|doc|0.2.23
docs-preview|doc|0.3.34
docs-yaml|doc|0.2.4
gitlens|eam|10.1.1
dotenv|mik|1.0.1
python|ms-|2019.10.44104
csharp|ms-|1.21.5
debugger-for-chrome|msj|4.12.0
vscode-yaml|red|0.5.3
code-spell-checker|str|1.7.18
vscode-markdown-paste-image|tel|0.12.3

</details>

**Comment by mattmazzola** [comment]
I looked at https://github.com/microsoft/vscode/issues/65394 it looks related but is focused around the context menu options. This issue is focused on the commands. 

Current command is a bit misleading as it would require user to know how VSCode interprets difference between Activate/Enable or Deactivate/Disable.  As far as I know outside of VSCode these words are synonyms and it would confuse people.

Solution A removes the confusion as it consolidates the terms "Enable" for both. But it looks some flexibitly. Solution B helps because it can show the user there is difference between the terms when they see two different commands related.

**Comment by isidorn** [comment]
To verify:

1. Deactivate all breakpoint by clicking on the breakpoint view title action
2. Enable some breakpoint and make sure all the breakpoints get activated
3. Also make sure that enabling all breakpoints make the brekapoint activated

@mattmazzola you can try out the new behavior in tomorrow's vscode insiders

**Comment by alexr00** [comment]
Functionally, this works:
- Launch extension debugging
- Extension hasn't activated yet (ex. hello world sample)
- Deactivate breakpoints using the title action
- Click a check box on a breakpoint (check goes away)
- Click same check box on a breakpoint to enable.
- Activate extension and break points are enabled+activated and hit!
However, there's a confusing flicker:
![breakpointflicker](https://user-images.githubusercontent.com/38270282/70158772-1c21eb80-16b8-11ea-9a03-1761fcd33f08.gif)

**Comment by isidorn** [comment]
You enable them all, vs code shows them as good and sends them to the debug adapter, the debug adapter reports back and says that they are not valid.
The issue here is that the breakpoints are reported as unbound by the debug adapter. So there is not a lot we can do.
Not sure why the debug adapter marks them as unbound. That would be a seperate issue.
