### ISSUE TITLE
Additional views alignment is off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83327]
![image](https://user-images.githubusercontent.com/2193314/67596341-601aeb80-f71d-11e9-80c0-8ac4bc12da19.png)

Might be related to recently vendor prefix clean up?

**Comment by isidorn** [comment]
Sorry for the slow response, I was on vacation. I can not repro this with latest insiders.
@Tyriar do you still see this?

![Screenshot 2019-11-11 at 11 23 59](https://user-images.githubusercontent.com/1926584/68580021-c7eb6900-0475-11ea-87f5-97e29b75f397.png)

**Comment by Tyriar** [comment]
Seems fine now
