### ISSUE TITLE
Perl syntax breaks while using underscore in function name and @_

### ISSUE THREAD

**Issue by gilsanx** [microsoft/vscode#83321]
- VSCode Version: 1.39.2
- OS Version: Fedora 20

Steps to Reproduce:

1. Have a perl function that has an underscore in its name. Example: s_expand()
2. Pass @_ as parameter. s_expand(@_)
3. The syntax is broken until another character breaks the highlight, for instance, another underscore.

```
sub myExample()
{
  s_expand(@_);
}

sub fixHighlight()
{
  #perl comment_
}

```
![image](https://user-images.githubusercontent.com/57008015/67581729-25f61d80-f70e-11e9-90e7-d511fce54595.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/textmate/perl.tmbundle/issues/40
