### ISSUE TITLE
Terminal text disappears

### ISSUE THREAD

**Issue by AbdouMoumen** [microsoft/vscode#83324]
Issue Type: <b>Bug</b>

Whenever I go back to a VS Code instance, I find the text in the Terminal window disappear. Interacting with the Terminal doesn't bring the text back.
Note that background color for text still shows.
![image](https://user-images.githubusercontent.com/640973/67590492-0d870280-f710-11e9-80db-d0c3b41d6e73.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (11.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-svgviewer|css|2.0.0
inception|dav|0.0.2
vscode-stylesheet-formatter|dba|0.2.0
githistory|don|0.4.6
xml|Dot|2.5.0
easy68k|dsi|0.0.2
gitlens|eam|10.1.1
tslint|eg2|1.0.44
prettier-vscode|esb|2.3.0
docthis|joe|0.7.1
vscode-peacock|joh|3.1.5
chat|kar|0.25.0
python|ms-|2019.10.44104
cpptools|ms-|0.26.0
powershell|ms-|2019.9.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1056
vsliveshare-audio|ms-|0.1.66
vsliveshare-pack|ms-|0.3.3
debugger-for-chrome|msj|4.12.0
debugger-for-edge|msj|1.0.12
amiga-assembly|prb|0.18.1
java|red|0.52.0
vscode-hexdump|sle|1.7.2
m68k|ste|0.0.1
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0
ReactSnippets|xab|2.3.0

(5 theme extensions excluded)

</details>

**Comment by NotWearingPants** [comment]
I've looked into this issue in the past.
If this is what I had, then this is a **Chrome bug**, not VSCode's.

But I forgot about this, I mostly ignore it. Tomorrow I will investigate it again and report the issue to Chrome if it's the same issue I am familiar with.

My issue was reproducible by killing the GPU process, can you do that and see if it produces similar results?

**Comment by Tyriar** [comment]
Please share your settings.json

**Comment by AbdouMoumen** [comment]
```
// Place your settings in this file to overwrite default and user settings.
{
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true,
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "**/bin": true,
        "**/obj": true,
        "**/objd": true,
        "**/bld": true,
        "**/*.g.js": true,
        "**/*.g.css": true,
        "**/*.js": { "when": "$(basename).ts" },
        "**/*.css": { "when": "$(basename).less" },
        "**/www/**": true,
        "**/_generated/**": true
    },
    "typescript.referencesCodeLens.enabled": false,
    "editor.formatOnType": true,
    "editor.renderIndentGuides": true,
    "editor.renderWhitespace": "boundary",
    "editor.trimAutoWhitespace": true,
    "terminal.integrated.shell.windows": "\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "extensions.autoUpdate": true,
    "workbench.quickOpen.closeOnFocusLost": false,
    "workbench.editor.revealIfOpen": true,
    "tslint.enable": true,
    "tslint.run": "onSave",
    "window.zoomLevel": 0,
    "window.menuBarVisibility": "default",
    "search.useIgnoreFiles": true,
    "editor.snippetSuggestions": "bottom",
    "gitlens.currentLine.enabled": false,
    "gitlens.hovers.currentLine.enabled": false,
    "gitlens.keymap": "alternate",
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.views.fileHistory.enabled": true,
    "gitlens.views.lineHistory.enabled": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "breadcrumbs.enabled": true,
    "editor.renderControlCharacters": false,
    "git.autofetch": true,
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "diffEditor.ignoreTrimWhitespace": true,
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "diffEditor.renderSideBySide": true,
    "terminal.integrated.rendererType": "dom"
}
```

**Comment by AbdouMoumen** [comment]
I don't think I've see it happening since switching to `"terminal.integrated.rendererType": "dom"`

**Comment by Tyriar** [comment]
Does zooming in and out fix the problem when you hit it? (ctrl++, ctrl+-)

**Comment by mapra99** [comment]
Yes @Tyriar. In my case it solves the issue zooming in and out

**Comment by Tyriar** [comment]
I think this is another case of Chromium corrupting the texture on the GPU somehow.

/duplicate https://github.com/Microsoft/vscode/issues/69665

**Comment by AbdouMoumen** [comment]
@Tyriar Yes, that solved the issue.
