### ISSUE TITLE
Add ability to define rules to control which window group a file opens in

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#83330]
Issue Type: <b>Feature Request</b>

I use multi-root workspaces for a mono-repo project.  At the root of the project is a .workspace file which has workspaces defined that point to various folders within my mono-repo associated with different projects.  

There's a large number of files/projects involved and several  languages.  Editing files across projects is common in this world -- but I need more help from vscode to stay organized.  I typically use a three-column two-row view so I have six editor views open at any given time to make simultaneous viewing/editing easy.  Its very difficult to stay organized as I open files/navigate around, check references etc with files associated with different information/contexts ending up in random window groups over time and migrating around randomly between window groups as I cmd-p to pull them into view.

It would be amazing if I could define criteria to map files to particular window groups so that editor views on those files always open in a particular window group.

For Example - in a rails project I would love to always open all the files in my app/graphql/types folder in one window, app/graphql/inputs in another, app/graphql/mutations in another, app/models/ in another ... etc.  

Another good rule would be to be able to tell vscode that I want to always edit certain file extensions in a particular window group -- say all .md files in the window associated with row 1, column 3.

In addition to helping me stay organized and to allow efficient use of spatial eye memory -- this would be a fantastic way to just generally mange my window splits.  Sometimes I close all the tabs in a project and proceed from scratch as I work -- I'd love to just organically return to my preferred 3-column 2-row view as my usage proceeds.  Sometimes I might close all the tabs in a window-group because I'm not working on those files or interested them in a particular moment and I'll regain some real estate for other uses -- but then when I do need to reference those files, I'll easy return to organized view as my needs require it -- without having to expend thought/energy to return to this organized window arrangement.

The more I think about it -- the more I want this feature.  I would absolutely love if this could be made part of a future release.

Thanks!!

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by jskene** [comment]
I am also keen on this feature.  I use a two column layout for C++ editing, and would like the .h files on the left and the .cpp files on the right.
