### ISSUE TITLE
Context menu in terminal

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8333]
#8222

Like other terminals (terminal, iTerm) I would expect that we have a context menu on right click in our integrated terminal.
Potential actions to have there would be copy / paste, new terminal window, close terminal window...

**Comment by Tyriar** [comment]
This may be improved with the IME support work in https://github.com/sourcelair/xterm.js/issues/124

**Comment by Tyriar** [comment]
Blocked on https://github.com/sourcelair/xterm.js/pull/175 which removed the `click` handler.
