### ISSUE TITLE
SEARCH fails if exclude icon highlighted

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#83333]
Issue Type: <b>Bug</b>

1. type a known value in the Search field
2. tap on the icon in the 'file to exclude' field but do not add any files to exclude. see that the icon is highlighted
3. press enter in the Search field
No files are found

![image](https://user-images.githubusercontent.com/20051/67604672-0e7c5c00-f731-11e9-8fe9-0ca8dc25741f.png)

4. tap on the icon again to remove the highlighting.
5. press enter again in the Search field
See that files are found

![image](https://user-images.githubusercontent.com/20051/67604701-1dfba500-f731-11e9-811b-ddbd8173c4f7.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

IMO this is a bug -- or perhaps an anti-feature -- because the result of hitting that icon and removing the entire collection from the search is not obvious, possibly even _inconceivable_. ;^)

**Comment by dfdumaresq** [comment]
This is not covered in the suggested duplicate.

**Comment by gjsjohnmurray** [comment]
What tip displays when you hover the mouse over that button?

**Comment by dfdumaresq** [comment]
"Use Exclude Settings and Ignore Files"
When I discovered this button had been activated I was surprised and frustrated because I had not consciously tapped it.

**Comment by gjsjohnmurray** [comment]
Did you notice the message at the bottom of your screenshot number 3 that tells you which settings will have caused files to be excluded from your search?

**Comment by dfdumaresq** [comment]
I noticed the message. It tells me that no results have been found. Period. If I’m to conclude or extrapolate that files have been found but excluded then the UI is not doing its job properly. 
For example it would be helpful to say something like 4 files have been dound and excluded from results.

**Comment by roblourens** [comment]
When that button is toggled on`search.exclude` and `files.exclude` and `.gitignore` are respected. https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results
