### ISSUE TITLE
Coping files from one window to another deletes the file from the original

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/vscode#83335]
Issue Type: <b>Bug</b>

#81594 looks like the same issue, not sure why the opener closed it.

When copying a file from one window to another, the file in the original window is deleted.

VS Code version: Code - Insiders 1.40.0-insider (29ffbfe3f1c21b01a2d0670170855669dd2b3b4f, 2019-10-25T14:03:31.497Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (27.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
git-branch|ale|1.4.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|2.3.0
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.8.1
python|ms-|2019.10.44104
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.0
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.6
cpptools|ms-|0.26.0
csharp|ms-|1.21.5
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
debugger-for-chrome|msj|4.12.0
material-icon-theme|PKi|3.9.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|9.5.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I cannot reproduce (tried on Linux):
* drag and drop into other window explorer
* using Copy/Cut from the context menu and paste into other window explorer

**Comment by anthonydresser** [comment]
I'm no longer experiencing this issue. I'll reopen with better repro steps if I experience it again.
