### ISSUE TITLE
Web: expanded find widget needs more height (Firefox)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83344]
Steps to Reproduce:

1. use Firefox
2. expand the find widget to show replace

![image](https://user-images.githubusercontent.com/900690/67615398-2d7bfc00-f7cc-11e9-8061-98b314b8dd52.png)

I would even say that in Chrome the border around the boxes is not the same to the bottom as it is to the top:

![image](https://user-images.githubusercontent.com/900690/67615401-3b318180-f7cc-11e9-8bb7-7659f53e3047.png)

**Comment by rebornix** [comment]
Thanks and good catch. FF has its own predefined css for textarea (`margin top/bottom: 1px`). Currently I disable it only for Find Widget as I didn't see any other component (Search, Git) suffers from it. If I do see that happening, then I'll force the margin for basic input component.
