### ISSUE TITLE
Markdown preview should be able to render images

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#8334]
- VSCode Version:1.2.1
- OS Version: OSX

Steps to Reproduce:

1. Preview a Markdown image with a simple link to an image in the same folder
2. You get a broken image.

**Comment by bpasero** [comment]
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by krvajal** [comment]
I am in version 1.16 and this is still an issue
