### ISSUE TITLE
my js files arent colorful

### ISSUE THREAD

**Issue by sepehr71** [microsoft/vscode#83346]
Issue Type: <b>Bug</b>

my js files arent colorful

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0

</details>

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you run with all extensions disabled?

If so, maybe add a screenshot? 

What language mode shows in the status bar when your JS file is open?

**Comment by sepehr71** [comment]
yes it reproduce.
but i solved it by adding atom dark theme extension . it made it colorful.
since my workplace system got this issue i cant screen shot till monday.
but tnx for your your time sir
