### ISSUE TITLE
Expose `jsonc-parser` 

### ISSUE THREAD

**Issue by seivan** [microsoft/vscode#83352]
Seems like vscode uses jsonc-parser internally, but doesn't expose it. Forcing developers to add jsonc-parser to their extension.
It would be useful if the typescript definition exposed the parser directly, removing an additional dependency.

**Comment by mjbvz** [comment]
This is intentional. We want to be able to upgrade our internal dependencies—such as `jsonc`—without having to worry about potentially breaking extensions
