### ISSUE TITLE
VSCode strangely stops at non-breakpoint line of code

### ISSUE THREAD

**Issue by khteh** [microsoft/vscode#83355]
Issue Type: <b>Bug</b>

No breakpoint, no exception but why does it alway stops at this particular line of code?
![VSCodeStrangelyStopsAtNonBreakpoint](https://user-images.githubusercontent.com/3871483/67622785-65c51e00-f850-11e9-98fa-d63539cb8f29.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 8|
|Memory (System)|23.20GB (4.39GB free)|
|Process Argv|--inspect-extensions=8888|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
add-reference|adr|1.0.2
namespace|adr|1.1.2
net-core-starters-pack|bla|1.0.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
supersharp|cra|0.1.4
vscode-quick-select|dba|0.2.8
netcore-extension-pack|dog|0.8.0
netcore-snippets|dog|0.2.7
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
extbundles-csharp|Fel|2.0.0
vscode-solution-explorer|fer|0.3.5
scaffold|fir|1.0.0
code-runner|for|0.9.14
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.1
auto-using|Fud|0.7.9
todo-tree|Gru|0.0.160
mysql-syntax|jak|1.3.1
csharpextensions|jch|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|0.3.1
vscodeilviewer|jos|0.0.1
docomment|k--|0.1.8
dotnet-core-essentials|Kis|0.0.8
csharpfixformat|Leo|0.0.84
csharp-colors|log|0.1.7
dotnet-core-commands|mat|1.0.6
vscode-docker|ms-|0.8.1
mssql|ms-|1.7.0
csharp|ms-|1.21.5
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.0
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.1
quicktype|qui|12.0.46
awesome-dotnetcore-pack|sal|1.8.0
copy-text|sal|0.4.3
msbuild-project-tools|tin|0.2.55
vscode-todo-highlight|way|1.0.4
libman|wei|0.1.1
highlight-trailing-white-spaces|yba|0.0.2

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem still occur if you run with all extensions disabled?

**Comment by khteh** [comment]
Yes it does!

**Comment by isidorn** [comment]
Please file this against the debug extension you are using to debug that piece of code. Thanks
