### ISSUE TITLE
Source control is not working properly

### ISSUE THREAD

**Issue by yu-coder** [microsoft/vscode#83356]
Issue Type: <b>Bug</b>

First, I change one file.
Second, I expected the bage on the source control happens immediately because I changed file
Third, When I refresh explorer, the badge shows.
http://prntscr.com/poh8zm

Looking forward to fix this issue on next version.
Thank you.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 x 3433)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|6.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by joaomoreno** [comment]
Are you working in a network share? Does your workspace folder path chain contain a symlink?  Does the badge appear if you wait at least 10 seconds? Can you show the the full output of `Git: Show Git Output`?

**Comment by yu-coder** [comment]
Thanks for your reply.
Sorry for the late reply.
I am working on Local.
It seems it shows in 5~6 seconds. 😄
