### ISSUE TITLE
Debugger takes no changes any more

### ISSUE THREAD

**Issue by MaxBec** [microsoft/vscode#83351]
Hello guys,

suddenly my debugger takes no changes anymore. I change the code of extension.ts file but the debugger executes some older vresion. Even the breakpoints get executed on the wrong lines.

New file:
`	console.log('Congratulations, your extension "OpenHAB Alignment Tool" is now active...');
`Output:
`Congratulations, your extension "OpenHAB Alignment Tool" is now active!
`
What can i do? I have no idea. I saved the file, i restarted VSC, i rebooted my pc. Nothing changes.

**Comment by isidorn** [comment]
I can not reproduce this issue.
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
If yes, can you please share a repository which I can just clone and see the breakage on my machine so I can investigate more. Thanks
