### ISSUE TITLE
Avoid unfolding when typing `

### ISSUE THREAD

**Issue by akimikimikimikimikimikimika** [microsoft/vscode#83353]
Issue Type: <b>Feature Request</b>

When I am editing my JavaScript source and use the character "\`" for creating a string expression, I am always careful because JSLint regards whole the source after it as one string and unfolds all foldings after it. Of course, to prevent the problem, I need to type another "\`" soon after the first one.
But if I forget it, this happens and I need to refold manually.
So I want JSLint to evaluate the source more slowly, especially deciding string or regex expressions.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

**Comment by aeschli** [comment]
Normally we autoclose the backtick (\`\`) which avoids any dangling backticks that break the syntax tree.

**Comment by akimikimikimikimikimikimika** [comment]
That's true. In most cases, autoclosing worked in my environment.
I found a case where I'm in trouble.
When I have a source like that:
```javascript
let x=extremelyLongString;
… // enclosing like functions, objects, arrays are following
```
And to create:
```javascript
let x=`extremelyLongString`;
```
In this case, if I select the text `extremelyLongString` and type \`, closing will work correctly, but when the cursor is after the equal sign (=) and type \`, all foldings in following source are unfolded.
This often happens when enclosing an extremely long string literary by mistake.

**Comment by aeschli** [comment]
This is the same issue as https://github.com/microsoft/vscode/issues/76990

Some ideas to try out:
- if there's a syntax error due to an unclosed backtick do not report any folding regions (return undefined, not an empty []!). In that case fodling will just continue with what it has.
- if there's a syntax error due to an unclosed backtick, try an error recovery: iteratate over all multi-line backtick strings and close them on on the same line. Then reparse and see if this fixed the issue This might involve several passes to find the right backtick to close (the one that causes the issue might be closed by an other opening backtick).

**Comment by akimikimikimikimikimikimika** [comment]
I cannot understand when autoclosing fired or not.  
I opened several JS documents and HTML documents (with `<script>`) and tried.
- In JS file, with just typing \` in any empty region, closing \` was inserted, but in HTML file, didn't work.
- typing \` before variables will always unfold. (previous my comment)  

Choosing `"indentation"` instead of `"auto"` in the setting `"editor.foldingStrategy"` might be better idea for me.

**Comment by cwewells** [comment]
I ran into this issue also. For me, unfolding happens with opening braces and brackets. I can avoid unfolding if I enclose portions of code in "#region" comments (i.e. for javascript), but overal not an elegant solution.

**Comment by thany** [comment]
Maybe VScode can somehow remember the contents of a line where code has been folded, and find those lines and restore fold state once the ` `` ` or `/* */` block is closed?

**Comment by cleverActon0126** [comment]
I am having the same issue.
