### ISSUE TITLE
Integrated terminal with git bash - backspace left and right does not work

### ISSUE THREAD

**Issue by jychia** [microsoft/vscode#83354]
Issue Type: <b>Bug</b>

I am using windows version of visual studio code. When I use the integrated terminal with git bash, the backspace, left and right key does not work as intended. They will just randomly add space or previously typed characters into the terminal

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (24.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
vscode-yaml|red|0.5.3

</details>

**Comment by Tyriar** [comment]
There's no way to support this currently across the board since we're using a pty-backend rather than communicating via the Windows console API. Some of these work in powershell as it can take instructions for cursor movement via text..
