### ISSUE TITLE
Code Fails to start. -- Heap Corrupted.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/vscode#83364]
- VSCode Version:  1.39.2.0
- OS Version: Win 7

Steps to Reproduce:
**Step 1:**
Install VS Code from the 64bit msi installer ("as administrator")
Ran from desktop shortcut or command line.
Either will produce:

Exception:
Unhandled exception at 0x000000007736F302 (ntdll.dll) in Code.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00000000773D7C70). occurred

**Uninstall then reinstall** 
This time the 32-bit msi (again as administrator)
Ran again the desktop icon or command line...
Again appears to be a heap corruption issue...

Same exception:
Unhandled exception at 0x000000007736F302 (ntdll.dll) in Code.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00000000773D7C70). occurred 

Tryed with the --disable-extentions again same "Heap Corruption" exception...

Does this issue occur when all extensions are disabled?: Yes/No  -- YES

Anything else you might need, ask.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ZooDoo4U** [comment]
Thanks for getting back to me.  I'm getting mixed results.    With the v.40 (latest nightly as of now)  it will work from the start menu or shortcut,  strange had selected "Add to Path" but it appears the path wasn't updated.   I'll note for clarity, no cmd prompt was open before/while the installing only after install finished.  What was in the path was:   

"C:\Program Files\Microsoft VS Code\bin"

But it fails to start or attempt to launch,  Checking the program shortcut i'm seeing it is pointing to:

"C:\Program Files\Microsoft VS Code Insiders"

So completely understandable why running from a cmd prompt fails.  So then it seems there is a bug in the setup "Add To Path". 

So it seem the installer is messed up still?  I tried opening a bug (a year or more back) detailing problems with Code's installer, was  bit put off as is had detailed the problem,  Code wouldn't properly update the path correctly and more often simply/blindly concatenated a new path segment, not cleaning up older portions for itself, sure seemed like things got messed up from that.   So i'm thinking ultimately the issue is the install/uninstall are not working correctly as old versions path segments are remaining causing issue such as the Heap corrupted as i was seeing,  really feels like HEAPs from different dll will get intermixed i.e. release vs debug heap routines... 

So going forward  seems at the least "Add to Path" in the installer is broke since the "Insider Path" wasn't added properly...  Seems this should be an easy BVT test that has never been there.

Possibly the "Insider" version is how the nightly builds are distinguished,  but would assert it really highlights how brittle the setup is.   Shouldn't matter if the path expected would be "C:\abc"  as a single complete unit shouldn't it all still work...?

**Comment by bpasero** [comment]
I am not sure about the installer paths, adding @joaomoreno

**Comment by joaomoreno** [comment]
I suggest to completely uninstall VS Code and reinstall whichever version you'd like.

**Comment by ZooDoo4U** [comment]
@joaomoreno  With the release MS Code  (v 39) , i had uninstalled, thus my comments that the path is not cleaned up...  Buyt v39 will result in the "Bad Heap error"  complete uninstall and re-install a number of times...  While an issue using the v.40 (insider version) looks like and i'm guessing the install is effectively doing Path.Contains("Microsoft Code") sees that it is present and won't update the path, but the old path from the v39 doesn't have the "insider" and my cmd's path won't have the right path...  I've run through most of the iterations to verify  this is repeatable...

Anything or any info i might provide let me know...

**Comment by bpasero** [comment]
@ZooDoo4U does it fail already when you try to run Code Insiders from this archive, that does not require any installation?

https://az764295.vo.msecnd.net/insider/c8846de84ab2f0a9279a41d80414465124c52a7a/VSCode-win32-x64-1.40.0-insider.zip

**Comment by ZooDoo4U** [comment]
To be sure,  downloaded the zip, uncompressed to a temp folder, and launched it from a windows explorer, seems to come up just fine.

Is that all you would like to check?

**Comment by bpasero** [comment]
Yes, so then I guess it must be installation related.

**Comment by ZooDoo4U** [comment]
Thanks for the attention,  anything you'd like me to try/test.... Will be glad to help out.

**Comment by joaomoreno** [comment]
@ZooDoo4U Do this:

1. Fully and completely uninstall all versions of VS Code in your system. Look for all the folders and environment variables. Make sure it's all gone.
2. Reinstall from https://code.visualstudio.com/insiders/

Let me know what the result is.
