### ISSUE TITLE
Add folder to new workspace causes two VSCode instances when reopen VSCode

### ISSUE THREAD

**Issue by avelinobego** [microsoft/vscode#83360]
Issue Type: <b>Bug</b>

Add folder to new workspace causes two VSCode instances when reopen VSCode. One of instances make workspace "not saved"

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0
csharp|ms-|1.21.5
Go|ms-|0.11.7
subtitles-editor|pep|1.0.4
material-icon-theme|PKi|3.9.1
ruby|reb|0.25.3
vscode-yaml|red|0.5.3

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by bpasero** [comment]
This is expected for untitled workspaces, see https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file
