### ISSUE TITLE
Resizing window is extremely slow and laggy

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#83366]
Issue Type: <b>Bug</b>

See this screen recording illustrating the problem:
![repro](https://user-images.githubusercontent.com/2473545/67627198-e58dc100-f82d-11e9-84ca-dbbdb1a9c5b2.gif)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.92GB free)|
|Process Argv|C:\Users\phg\OneDrive\Apps\.config\.gitconfig|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
matlab-formatter|Aff|2.4.12
vscode-dash|dee|2.2.0
EditorConfig|Edi|0.14.2
terminal|for|0.0.10
matlab|Gim|1.4.0
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.2.0
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0
sublime-keybindings|ms-|4.0.3
latex-utilities|tec|0.3.3
latex-support|tor|3.1.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by pedrogarcia** [comment]
> Does the problem also happen if you launch with all extensions disabled?

Yes.
