### ISSUE TITLE
Update code lens of inactive editors when typing in another editor

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#83363]
Little bug here with `codelens` and multiple `splitted window editor`.
codelens will auto update only if we nav between slots from the same window editor.
But if we toggle between 2 windows frames, codelens will not auto update.

So i alway need to switch between files in the same window to get codelens auto update.
It possible to add codelens update between toggle window editors ?
it's a bit boring for productivity, i toggle a lot between editors groups.

-----------------
![codelends bug](https://user-images.githubusercontent.com/24865815/67626252-b1f36c80-f816-11e9-901c-3691b79b38f3.gif)

You can try with this setup and share reference between those files.
Then with your mouse or keyboard toggle change `ctrl+p` *2 time. 
codelens will not detect update.
![image](https://user-images.githubusercontent.com/24865815/67626279-f848cb80-f816-11e9-9471-eac3b81dd81a.png)

--------------
**files0.js** ex: in bottom window editor frame
```js
class test0 {
    constructor() {
 
    };
};
```
files1.js ex: in upper window editor frame
```js
class test1 {
    constructor() {
// add after created the 2 test files and toggle between files, codelens will not update!
        console.log(test0);  
    };
};
```
---------------------
**Possible solution?**
Maybe add a update between toggle window ?!

------------------
**Version.**
Version : 1.39.2 (user setup)
Validation : 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date : 2019-10-15T15:35:18.241Z
Électron : 4.2.10
Chrome : 69.0.3497.128
Node.js : 10.11.0
V8 : 6.9.427.31-electron.0
OS : Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
We do update when toggling but depending on the project size it might take a while to happen (this depends on how fast extensions can run). Can you try to simply wait after switching to the editor? It should eventually update

**Comment by djmisterjon** [comment]
@jrieken I just make a try and wait about ~2min and nothing happen.
Maybe something is break in the refresh sorry.
It a very big projet, but i also have a very big machine, so i dont think is related to the latence update.

**Comment by jrieken** [comment]
can you try with a smaller project then? as said, there is an explicit update when changing editors and it seems that your update missing because of something else.

**Comment by djmisterjon** [comment]
Try in empty project, 3 min ...
![image](https://user-images.githubusercontent.com/24865815/67676413-cf7c1f80-f957-11e9-84c4-ee2bc9decd3f.png)

The update work only if we change file from same editor focused.
If i change file and come back the update is instant.
![image](https://user-images.githubusercontent.com/24865815/67676578-2eda2f80-f958-11e9-9bbb-03dc34b2960d.png)

**Comment by jrieken** [comment]
ok, now you have just changed (or clarified) the steps here. Yes, when typing a file A and file B is visible then its code lenses don't update. That kinda by design because it quite expensive to update N editor when typing in 1 editor...

**Comment by djmisterjon** [comment]
ok sure, i made you a video thats show the workflow issue.
I dont think is critical ! but a little embarrassing because the information is misleading and it can become confusing in a big projects with a lot of references.
https://youtu.be/LFlq4KBXW3w
thanks again and hope the video will help you understand how i use vscode in my workflow.

**Comment by jrieken** [comment]
I have pushed a change that updates code lenses of an editor when it gains focus. That means inactive editor won't update while typing in another editor but as soon as you make them active again.

**Comment by jrieken** [comment]
\closedWith 351e617
