### ISSUE TITLE
Toggle Terminal Icon

### ISSUE THREAD

**Issue by muhammadfajarb** [microsoft/vscode#83367]
Issue Type: <b>Feature Request</b>

Please bring back the toggle terminal icon on the bottom right corner. That was a powerfull feature. It should not be removed. Thank you.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

**Comment by Tyriar** [comment]
What icon are you talking about?
