### ISSUE TITLE
unable start debugging.launch option string provided by the project system invaild. "<",шестнадцатеричные значение 0x3c,является недоступным для атрибута знаком,строка 6,позиция 13.

### ISSUE THREAD

**Issue by almuradovdaut** [microsoft/vscode#83362]
![bug](https://user-images.githubusercontent.com/57047802/67625424-a5433880-f857-11e9-8274-6038f6698e1e.png)

- VSCode Version:1.39.2
- OS Version:10
problem:unable start debugging.launch option string provided by the project system invaild, шестнадцатеричные значение 0x3c,является недоступным для атрибута знаком,строка 6,позиция 13

Steps to Reproduce:

code

  "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Запуск канала",
            "type": "cppdbg",
            "request": "launch",
            "program": "Введите имя программы, например: ${workspaceFolder}/a.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:\\Compiler\\MinGW\\mingw64\\bin",
            "environment": [],
            "externalConsole":false,
            "pipeTransport": {
                "debuggerPath": "C:\\Compiler\\MinGW\\mingw64\\bin\\gdb.exe",
                "pipeProgram": "<Полный путь к программе канала, например: plink.exe>",
                "pipeArgs": [],
                "pipeCwd": ""
            },
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Включить автоматическое форматирование для gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }

        
    ]
}

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
It seems the same bug of the extension rather than vscode.
https://github.com/microsoft/vscode-cpptools/issues/4464
