### ISSUE TITLE
Ubuntu 19.10 apt-update fails with vscode repository

### ISSUE THREAD

**Issue by shangles** [microsoft/vscode#83372]
I recently updated my laptop to the latest version of Ubuntu Desktop (19.10 (eoan)) and when I do an apt-get update command now there are failures for the vscode repository.

Repository URI: http://packages.microsoft.com/repos/vscode
Distribution:  stable
Components:  main

VSCode is installed and still runs.  About info:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.0-19-generic

If I check for updates from within the app it says no updates available.  Not sure if this is a really issue or not.  I'm not a Linux expert so I could be barking up the wrong tree here.

Console log:
root@Tangles-Ubuntu:/home/chris# apt update
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu eoan InRelease                                                                                                          
Hit:3 http://archive.canonical.com/ubuntu eoan InRelease                                                                                                          
Get:4 http://security.ubuntu.com/ubuntu eoan-security InRelease [88.4 kB]                                                
Get:5 http://packages.microsoft.com/repos/vscode stable InRelease [3,938 B]    
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease                            
Hit:7 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease                       
Get:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [148 kB]     
Fetched 240 kB in 1s (167 kB/s)   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'i386'

**Comment by joaomoreno** [comment]
You seem to still have the 32-bit repo installed. Let's fix that by reinstalling VS Code:

```bash
# uninstall code
sudo apt remove code
sudo rm /etc/apt/sources.list.d/vscode.list
sudo apt update # should succeed now

# download code and reinstall it
wget -O ~/Downloads/code.deb https://update.code.visualstudio.com/latest/linux-deb-x64/stable
sudo dpkg -i ~/Downloads/code.deb
sudo apt update # should keep succeeding from now on
```

**Comment by shangles** [comment]
This worked.  Thanks a million.  Marking this as Closed.
