### ISSUE TITLE
Add "Esc" keyboard shortcut to dismiss things

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#83371]
This is a specific example, but one of the things that I found very annoying in general with vs code and also with web apps in general, but something that true desktop apps seem to just get right every time:

In sublime text, pressing ctrl+shift+f open the "view files". But, you can get out of there by pressing "Esc".  This is not specific to the "view files" command. In general, it feels like you can get out or close things with "Esc".  
On vs code... nothing happens.

**Comment by jhasse** [comment]
This is because the global search in VS Code is a "tab" of the activity bar while in Sublime Text it's a dialog. Dialogs in VS Code (e.g. Ctrl+F in a file) can be dismissed using Escape.

**Comment by bpasero** [comment]
And btw you can configure ESC to close the search sidebar.
