### ISSUE TITLE
Custom task group property does not seem to work as expected

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vscode#83378]
Adding task from custom VS Code extension I set:
```
task.group = vscode.TaskGroup.Build;
task.problemMatchers = ['$tsc'];
```
This does not seem to work, custom task does not show up when Ctrl+Shift+B is pressed.
Complete repro below.
```
import * as vscode from 'vscode';

const ExtensionId: string = "simple-test-extension";
let _taskProvider: vscode.Disposable | undefined;

export function activate(context: vscode.ExtensionContext): void {
	_taskProvider = vscode.tasks.registerTaskProvider(ExtensionId, {
		provideTasks(): vscode.Task[] {
			let task = new vscode.Task({ type: ExtensionId }, 'test task', ExtensionId, new vscode.ShellExecution(`echo src/extension.ts:10:13 - error TS2532: This does not seem to work.`));
			task.group = vscode.TaskGroup.Build; // this does not seem to work
			task.problemMatchers = ['$tsc'];
			return [task];
		},
		resolveTask(task: vscode.Task): vscode.Task | undefined {
			return undefined;
		}
	});
}

export function deactivate(): void {
	if (_taskProvider) {
		_taskProvider.dispose();
	}
}
```

**Comment by alexr00** [comment]
I cannot reproduce. Is your extension activated? For extensions that provide tasks activation on "run task" is often used:
```
	"activationEvents": [
		"onCommand:workbench.action.tasks.runTask"
	],
```

**Comment by tdjastrzebski** [comment]
Correct, that's the activation event I use.

**Comment by alexr00** [comment]
Can you provide a sample repo I can use to test this? I cannot reproduce the issue.

**Comment by tdjastrzebski** [comment]
Complete repro and screen shoots attached.
Custom task is not available when Ctrl+Shift+B is pressed but it is listed as 'regular', plain task.

<img width="579" alt="vscode-83378-build tasks" src="https://user-images.githubusercontent.com/7325277/67871444-a82c7a80-fb30-11e9-9532-5449fe822bd0.png">

<img width="581" alt="vscode-83378-all tasks" src="https://user-images.githubusercontent.com/7325277/67871450-abc00180-fb30-11e9-9425-b8b6bd6197b3.png">

[simple-task-provider.zip](https://github.com/microsoft/vscode/files/3789676/simple-task-provider.zip)

**Comment by alexr00** [comment]
This is interesting. If you have _any_ tasks configured in the tasks.json of the folder you have open to be build tasks, then we only show those build tasks. If you don't have any tasks.json build tasks, then your contributed build task shows up. 
This behavior is intentional, but does seem a bit confusing. It's been that way for two years and no one has said anything so perhaps it's actually doing what users want most of the time.

**Comment by alexr00** [comment]
The problem matcher is fine. It's the shell execution that's the problem. Change to:
`let task = new vscode.Task({ type: ExtensionId }, 'test task', ExtensionId, new vscode.ShellExecution(`echo`, ['src/extension.ts:10:13 - error TS2532: This does not seem to work.']));
`

**Comment by tdjastrzebski** [comment]
@alexr00 Correct, problemMatchers is not a problem.
Yeah, it looks like once "build" task in **tasks.json** is defined, other, programtically added "build" tasks are removed.
I do not believe this is the desired behavior.
What would be the motivation? I cannot think of any.

**Comment by alexr00** [comment]
It looks like the intention is to show only the build tasks that a user has shown that they care about (the use show's that they care about the build task by adding it to tasks.json).

**Comment by tdjastrzebski** [comment]
@alexr00 Hence, setting task group programmatically does not really make sense. The little trouble is that not every task can be easily added to **tasks.json** and marked as as **build**. Anyway, thank you, at least I know what is going on.
