### ISSUE TITLE
Custom problemMatcher for dart-sass seems to be impossible

### ISSUE THREAD

**Issue by jeffrson** [microsoft/vscode#83384]
- VSCode Version: 1.39.1
- OS Version: Windows 10

Dart-Sass (https://www.npmjs.com/package/sass) reports warnings or errors like this:
```
Warning: TEST
    abstracts\rfid\test1.scss 1:1  @import
    abstracts\variables.scss 1:9   @import
    test.scss 1:9                  root stylesheet

Error: Incompatible units em and px.
  ╷
9 │ $container-height: 200px + 1em;
  │                    ^^^^^^^^^^^
  ╵
  abstracts\rfid\test1.scss 9:20  @import
  abstracts\variables.scss 1:9    @import
  test.scss 1:9                   root stylesheet
```

AFAICT I need a multiline problemMatcher (https://code.visualstudio.com/docs/editor/tasks#_defining-a-multiline-problem-matcher). However, as it seems, to get to the filename and location I need to describe the output exactly line-by-line until then. This means, I would need to provide two different problemMatchers to describe this warning and the simple error. However, errors might as well look like this:
```
Error: Incompatible units em and px.
  ╷
9 │   $container-height: 200px +
  │ ┌────────────────────^
10│ │    1em;
  │ └──────^
  ╵
  abstracts\rfid\test1.scss 9:20  @import
  abstracts\variables.scss 1:9    @import
  test.scss 1:9                   root stylesheet
```

which adds more lines - and another problemMatcher? What if there are more output formats?

Shouldn't there be a way to ignore an (indefinite) number of lines from output of the task? IMO there isn't so far.

BTW, at first I thought, that "loop" might help here - but

> The loop property is only supported on the last line matcher.

**Comment by alexr00** [comment]
The problem matcher functionality is lacking here. This would be solved by programmatic problem matching: https://github.com/microsoft/vscode/issues/59337
