### ISSUE TITLE
ts intellisense displays wrong message

### ISSUE THREAD

**Issue by charbelsako** [microsoft/vscode#83383]
![bug2](https://user-images.githubusercontent.com/26299987/67635223-33a5d180-f8cd-11e9-9b49-8991769e5772.png)

As you can see, the typescript extension suggests removing the `await` keyword even though it is useful here (i.e removing it would cause a bug).

 Could be related to #60385.

Suggestions to improve this issue are appreciated.

**Comment by mjbvz** [comment]
Please text source for a minimal example of this (not just screenshot)

**Comment by charbelsako** [comment]
Just made a github repo with the code and the needed files.
[my repo](https://github.com/charbelsako/web-2)
I hope this helps.

**Comment by mjbvz** [comment]
Your JSDoc annotations are incorrect. `loadData` should be needs to return a promise: ` @returns {Promise<JSON>} `

**Comment by charbelsako** [comment]
Ok, thanks
