### ISSUE TITLE
Problems with debug

### ISSUE THREAD

**Issue by Bendtion1** [microsoft/vscode#83380]
Here's a common error, did not understand where the hidden problem, the Internet is a little information.
Unable to start debugging. Unexpected GDB output from command "-environment-cd C:\\Users\\я\\Desktop\\HELLOWORLD-MINGW". C:\\Users\\я\\Desktop\\HELLOWORLD-MINGW: No such file or directory.
code Launch.json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/helloworld.exe",
      "args": [],
      "stopAtEntry": true,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": true,
      "MIMode": "gdb",
      "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gdb.exe",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}

**Comment by repo-wiseacre** [comment]
Hi Team,
One small suggestion.
Can we analyse the problem as follows.
-> if the user is using a single package or folder path the we can pass the command prototype to the terminal to run the code.
`D:\vs-workspace> & C:/Users/shuvagho/Anaconda3/python.exe d:/vs-workspace/python/com/python/core/modules/cursesio/cursesio.py`
-> In case if the user is using multiple packages and one file is importing other package as a module then we can pass the command prototype to the terminal to run the code
` & C:/Users/shuvagho/Anaconda3/python.exe -m  python.com.python.core.modules.cursesio.cursesio`
