### ISSUE TITLE
Debug Console very slow during debugging

### ISSUE THREAD

**Issue by ALicu** [microsoft/vscode#83393]
Issue Type: <b>Performance Issue</b>

The entire VS Code UI is very slow during debugging of my game application (C++) and having the debug console opened. The game is under debugger and running in background, and outputted several pages to the debug console. Trying to manipulate the debug console makes the entire VS Code very slow. Seems that this is unoptimized and unusable. Also it doesn't have any search capabilities in it, page up/page doune, control + end don't work, what you normally expect from a debug console. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    61	  5516	code main
    1	    65	  6568	   window (Issue Reporter)
    0	     2	 12944	   electron-crash-reporter
    0	    80	 15104	   gpu-process
    4	    47	 18316	   shared-process
    0	   552	 21604	   window (current.h - Dev - Visual Studio Code)
    0	     5	 19224	     watcherService 
    0	     1	 16168	       console-window-host (Windows internal process)
    0	     2	 20196	     winpty-process
    0	     3	   324	       console-window-host (Windows internal process)
    0	     1	  7668	       cmd.exe
    0	   138	 22556	     extensionHost
    0	    20	  6424	       "C:\Tools\Dev\Microsoft VS Code\Code.exe" "c:\Tools\Dev\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=22556
    0	    45	 22376	       c:\Users\Adria\.vscode\extensions\ms-vscode.cpptools-0.26.0\bin\Microsoft.VSCode.CPP.Extension.exe
    0	    33	  7400	         "c:\Users\Adria\.vscode\extensions\ms-vscode.cpptools-0.26.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 22376 299
    0	    12	 11420	         "c:\Users\Adria\.vscode\extensions\ms-vscode.cpptools-0.26.0/bin/Microsoft.VSCode.CPP.IntelliSense.Msvc.exe" 22376 300
    0	     1	 19184	         console-window-host (Windows internal process)
    0	     8	 23876	       C:\Tools\Dev\CMake\bin\cmake.EXE -E server --experimental --pipe=\\?\pipe\q:\Dev\CoreGame\core_src\Dev\.vscode\.cmserver-pipe
    0	     1	  8936	         console-window-host (Windows internal process)
    0	    39	 29344	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (current.h - Dev - Visual Studio Code)
|    Folder (Dev): 3768 files
|      File types: h(1399) cpp(850) obj(180) c(88) html(72) tlog(72) txt(70)
|                  png(49) vcxproj(48) filters(34)
|      Conf files: sln(17) makefile(10) launch.json(1) tasks.json(1)
|                  settings.json(1) csproj(1)
|      Launch Configs: cppvsdbg(2);
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
better-toml|bun|0.3.2
vsc-material-theme|Equ|30.0.0
vscode-test-explorer|hbe|2.14.6
cpptools|ms-|0.26.0
Go|ms-|0.11.7
rust|rus|0.7.0
crates|ser|0.4.4
rust-pack|Swe|0.2.23
vscode-rust-test-adapter|Swe|0.8.0
cmake|twx|0.0.17
cmake-tools|vec|1.1.3
vscode-icons|vsc|9.5.0
debug|web|0.23.1

</details>

**Comment by isidorn** [comment]
You are correct that the debug console can be improved, however we already have issues that capture this. You can see them linked by the bot, or you can search for issues with the label "debug" and comment on then

**Comment by ALicu** [comment]
Which one? I don't see any related to actual console being so slow makes program unusable (above listed are all valid issues, again very annoying: no search, really? cannot select all text, huh? scroll unpredictable, blah). Can't the bot just point to the duplicate? It let me search for it in gazillion number of issues. Such an important piece of any IDE is the console and this is unusable. Any ETA on this?
