### ISSUE TITLE
Git stage selected range duplicates lines after extensive usage

### ISSUE THREAD

**Issue by ttxxxx** [microsoft/vscode#83398]
Issue Type: <b>Bug</b>

-break down a long line of code with many multiplications into multiple lines:

```
var a = b * c * d * e * f * g
```

=>

```
var a = b * c
             * d * e
             * f * g
```

-stage selected range
-create switch statement around that code
-stage selected range
-manipulate code countless times, however never touching the code inside the switch statement, and stage selected range repeatedly
-noticed suddenly, that in the staged code some of the lines were duplicated, respectively removed again in the unstaged code:

```
var a = b * c
         * d * e
             * d * e
             * d * e
         * f * g
             * f * g
             * f * g
```

=> I don't know if the lines were actually duplicated and when the duplicates vanished in the working code since it did not cause a compiler error (multiplications across multiple lines are valid) and I did not fully check staged+unstaged code every single time; however, I am certain that I did not cause this duplication accidentially
=> this same error pattern happened at multiple places at once, since the multiplications were repeated with slight variations in some of the terms...
=> the first duplicate was always indented with one tab space less
=> sometimes a line was repeated two times, sometimes three times

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 v6 @ 3.70GHz (8 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.56GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
unicode-latex|oij|1.1.2

</details>

**Comment by joaomoreno** [comment]
@ttxxxx I can't understand the exact steps. Can you maybe send a screen recording of you reproducing the issue?

**Comment by ttxxxx** [comment]
@joaomoreno I cannot reproduce the bug
