### ISSUE TITLE
Themes deosn't work

### ISSUE THREAD

**Issue by darbouz** [microsoft/vscode#83391]
Issue Type: <b>Bug</b>

'Cannot read property 'id' of undefined'

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.72GB (2.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.19.0
python-extension-pack|don|1.6.0
output-colorizer|IBM|0.1.2
MagicPython|mag|1.1.0
python|ms-|2019.10.44104
material-icon-theme|PKi|3.9.1
vscodeintellicode|Vis|1.2.0
jinja|who|0.0.8

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by aeschli** [comment]
@darbouz  Can you check the Log (`Open Log File... Window`) or the Dev Tools (`Developer: Toggle Developer Tools`) to get a full stack trace?

**Comment by darbouz** [comment]
I found the solution but i don't know how

**Comment by aeschli** [comment]
Where was the problem?
Can we close the issue?

**Comment by darbouz** [comment]
Yes
