### ISSUE TITLE
cannot connect to the marketplace

### ISSUE THREAD

**Issue by pizzacrystal** [microsoft/vscode#83399]
Issue Type: Bug

when searching anything from marketplace there is an error message "We cannot connect to the marketplace now, please try again later".

What is definite
1. marketplace was working some days ago
2. working environment is unchanged (OS, libs, network, etc) except for normal extension updating
3. my computer is not behind any proxy
4. network works and dns is ok (same version and setup VSC on another PC using the same network works normally)
5. GFW is not the culprit (either Google, Youtobe, or Github, Twitter are accessible, and marketplace homesite can be opened with browser)

Here is the log screenshot got under developer console
![vsc bug](https://user-images.githubusercontent.com/11605580/67646424-11619180-f969-11e9-9f28-a569b212169b.png)

Here is the setup info
![vsc version](https://user-images.githubusercontent.com/11605580/67646442-29391580-f969-11e9-92bd-6a32bd363f67.png)

In addition, I have reviewed some old posts such as
https://github.com/microsoft/vscode/issues/81115
almost the same issue, there was no resolution in detail though it was said "solved" and closed, therefore I have to post it again, sorry for this.

**Comment by pizzacrystal** [comment]
here are some supplements:
1. extension update works normally
2. extension recommendation works normally

but still cannot connect to extension gallery

**Comment by pizzacrystal** [comment]
update:

as mentioned above, VSC with the same version and setup installed on another PC behind the same network works normally, I have compared the script file in which the error occurred as logged to the normal one. Surprisingly, they are absolutely the same, not a bit different.

**Comment by pizzacrystal** [comment]
update 2:

I have reviewed some similar issues submitted by others and found this image link below,

[https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default](url)

and yes, it is accessible in my browser.

**Comment by sandy081** [comment]
@pizzacrystal May I know what is the response of the marketplace request, you can find it in the network tab

**Comment by pizzacrystal** [comment]
@sandy081
Thanks for your question.
the first figure below shows network responses right after starting up of VSC and clicking extension button. the second figure below illustrates responses when i search something on searching box of marketplace (surrounded by red rect).
![vsc bug 1](https://user-images.githubusercontent.com/11605580/68596508-4d9f0100-04d6-11ea-85b9-eef496bcbeee.png)
![vsc bug 2](https://user-images.githubusercontent.com/11605580/68596524-58599600-04d6-11ea-94dc-df19b38be84a.png)

**Comment by sandy081** [comment]
Seems network requests are good.

Which version are you on? Please try on latest and insiders?

**Comment by pizzacrystal** [comment]
I just updated VSC to latest version, here it is
![vsc version](https://user-images.githubusercontent.com/11605580/68633114-9df47e00-052b-11ea-9a42-5f4a6d81e5b9.png)
but this issue still exists

I will try insiders as soon as i go back home, thanks!

**Comment by bestekov** [comment]
Experiencing this same issue.

```
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

I am not on any insiders build. Same symptoms:
* Can update existing extensions
* Can install recommended extensions
* CANNOT search any other extensions

**Comment by sandy081** [comment]
@bestekov Are you also seeing the same error as in description? 

@pizzacrystal Please confirm after updating.

**Comment by bestekov** [comment]
@sandy081 , where would I go to find those error logs?

**Comment by pizzacrystal** [comment]
@sandy081 
sorry for updating so late
yes, i tried insiders but no lucky
and i have updated to the latest release version, the issue is still there.
--------------------------------------------
版本: 1.40.1 (system setup)
提交: 8795a9889db74563ddd43eb0a897a2384129a619
日期: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
-----------------------------------------

**Comment by sandy081** [comment]
@pizzacrystal 

Can you please show the response of the request `extensionsQuery` below

https://user-images.githubusercontent.com/11605580/68596524-58599600-04d6-11ea-94dc-df19b38be84a.png

**Comment by pizzacrystal** [comment]
@sandy081
do you mean this?
![vsc bug 3 response](https://user-images.githubusercontent.com/11605580/68907584-5831f280-0783-11ea-83f1-f330dbb5caf2.png)

**Comment by pizzacrystal** [comment]
@sandy081 
i don't know why but the 'extensionquery' item never shows up. please check below,
![vsc bug 4 response](https://user-images.githubusercontent.com/11605580/69042789-cf3de400-0a2c-11ea-85d1-f9273d919036.png)

**Comment by sandy081** [comment]
Try typing in the search box and you shall see the request.

**Comment by pizzacrystal** [comment]
@sandy081 
here the response is, for your convinience, I put them into a file.
![vsc bug 4 response](https://user-images.githubusercontent.com/11605580/69121968-8f343b00-0ad8-11ea-8212-71b4eedcb0d7.png)


[response.txt](https://github.com/microsoft/vscode/files/3861967/response.txt)

**Comment by sandy081** [comment]
Response looks good. 

I am running out of ideas what would have caused it. 

- Please open shared process dev tools and see if there are any errors. Use command `Developer: Toggle Shared Process`
- Try to reproduce by launching VS Code with different user data directory from command line. `code --user-data-dir <path-to-user-data-dir>`
- Try to reproduce by launching VS Code with different extensions directory from command line. `code --extensions-dir <path-to-extensions-dir>`

**Comment by pizzacrystal** [comment]
@sandy081 

- no error shows up in "shared process" window

- **GOOD NEWS**, extension gallery can be accessed again with tmp user data directory.
Therefore, I made some attempts further --
go to my user data folder, **DELETE "cache" sub folder under it**, and restart vscode again, extension gallery came back!

I am not clear why it works, frankly i don't care, but here is my question :
Is there any side effect as I deleted "cache" folder? Though as far as now, I did not find any one. Thanks!

**Comment by sandy081** [comment]
This cache folder is from chromium in electron on which VS Code is built on. I guess there won't be any major side affects.

Thanks for confirming.

**Comment by steal3rd** [comment]
For me, the issue was related to the following files (Windows).

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup
```

I quit Code, and renamed them.

```
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb-disabled
C:\Users\USERNAME\AppData\Roaming\Code\User\globalStorage\state.vscdb.backup-disabled
```

Code recreated the files, and I was able to search the extensions again.
