### ISSUE TITLE
Outline view for Markdown symbols shows key icon

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#83395]
- VSCode Version: 1.40 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Markdown file with some number of H1 and H2 headers
2. Expand the Outline view

The symbol icon for Markdown headers had been an "abc" icon and not it is a confusing key icon.

Stable:

![image](https://user-images.githubusercontent.com/12818376/67643246-b3429900-f8eb-11e9-8eb2-5a85273edf71.png)

Insiders:

![image](https://user-images.githubusercontent.com/12818376/67643232-88f0db80-f8eb-11e9-9d44-af0e1fa7815a.png)

**Comment by gregvanl** [comment]
The key icon is also displayed in breadcrumbs

![image](https://user-images.githubusercontent.com/12818376/67643265-eab14580-f8eb-11e9-9874-2777e70397c8.png)

**Comment by misolori** [comment]
Good catch, this should be updated properly now:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/35271042/67700015-6356e700-f96a-11e9-95a1-ac601952866c.png">

**Comment by svipas** [comment]
I also saw the same issue in suggestion widget with word based suggestions thought to create an issue, could you check @misolori is it still shows `key` icon in suggestion widget or `abc` as supposed to? Thanks!

**Comment by misolori** [comment]
@svipas this is fixed where all symbols are shown: outline, breadcrumb, and suggest widget. This also affected strings and text kinds.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/35271042/67705475-517a4180-f974-11e9-876b-35d691be94bf.png">

**Comment by svipas** [comment]
@misolori Thanks! Nice work! 🚀
