### ISSUE TITLE
Allow to dim inactive editors making it easier to focus on the the active editor

### ISSUE THREAD

**Issue by breathe** [microsoft/vscode#83394]
Issue Type: <b>Feature Request</b>

I typically use vscode with 6 editor groups -- 3 columns and 2 rows.  Sometimes I command-click on file paths to quickly navigate to a particular line number in vscode -- (eg: clicking on file:line_number outputs from terminal commands).  Its often hard to find the active window group after clicking on one of these links -- there is not sufficiently clear indication in the UI which is the active window group.

Dimming the non-active windows (similar to the way iterm2 dim's not selected terminal panes) could be a nice touch.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by sbatten** [comment]
@breathe when you say "window groups", you mean editors or windows?

i.e. do you want 5 of your 6 editors to go dim or those 6 to be normal and another window to be dim?

**Comment by breathe** [comment]
@sbatten mmm -- i'm not 100% sure on the terminology -- I have one window with six views on editor buffers -- (does that means six 'editor groups')?.  I want the active one to be non-dim and the other five to be dim.

I actually found an extension which does a reasonable job of this -- https://marketplace.visualstudio.com/items?itemName=ojkwon.vscode-activedocumentindicator -- and some notes from the author that he hopes this will one day be built in behavior.
