### ISSUE TITLE
Move Folder Prompt

### ISSUE THREAD

**Issue by Lee182** [microsoft/vscode#83396]
Issue Type: <b>Feature Request</b>

Would if the Move Folder Prompt be tell you where the folder is moving.
The path I assume would be relative to the project root.

From
"Are you sure you want to move 'hebcal-js'?"
To
"Are you sure you want to move 'hebcal-js' into '.vscode/'?"

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
@Lee182 thanks for the suggestion. You can try out the new behavior in tomorrow's vscode insiders.
To verify:
Drag some files in the explorer and when you get the prompt make sure the name of the destination is also shown.
