### ISSUE TITLE
No 'File Open' dialog is displayed when attempting to open a folder

### ISSUE THREAD

**Issue by brandon-fridley** [Microsoft/vscode#834]
I'm running Ubutu in a VM.  
I've shared a folder in ubuntu using samba.  
I open the folder in Visual Studio code.  
I make my changes, close VS Code and shut down the VM.  
Hours later....
I start VS code.  
I select 'File' -> 'Open Folder'
No dialog is displayed so I choose 'File' -> 'Open Folder' again.  Nothing happens.  Eventually many file open dialogs appear.  

I expected it to be fast and allow me to open a folder on my local computer.

**Comment by bpasero** [comment]
Maybe the dialog blocks because it tries to restore the connection?

**Comment by brandon-fridley** [comment]
Yes, I assume it's doing that.  I expected it to respond faster (cancel the attempt to open the folder and instead open the default folder) or provide status as to what it is doing and I expected it to not show multiple 'File Open' dialogs.  (Because nothing appeared to be happening when I chose 'File' -> 'Open Folder', I selected it multiple times.  So when it eventually gave up trying to open the network folder that wasn't there anymore, a 'File Open' dialog appeared for each time I tried to open the folder).

**Comment by bpasero** [comment]
@brandon-fridley does this reproduce with other applications that have a file picker?

**Comment by brandon-fridley** [comment]
I tried it in Visual Studio... it just hangs and displays (Not Responding).  Eventually it opens to the default folder %USER%\Visual Studio 2015\Projects.  

It's not a big issue, however because it tries to open the files again on startup, it takes a while before the application is displayed.  Again, it's not a big deal, just wanted to make you guys aware.  I'll just need to be sure to close the files and folder before exiting or turn that setting off :-).

**Comment by bpasero** [comment]
This is OS behavior then and nothing we can prevent.
