### ISSUE TITLE
Extensions installation: failing to install due to version should be modal dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83405]
Steps to Reproduce:

1. be on an old VSCode version
2. try to install an extension that requires a newer version by clicking "Install"

=> 🐛 you get a notification that installation is not possible
=> I would turn this into a modal dialog since it originated from a direct user action

**Comment by sandy081** [comment]
But there is no action that user can be taken right. It is just an error message, is it helpful to show an error message as modal dialog?

**Comment by bpasero** [comment]
How about showing a button to open our website to download a new version? Or triggering the update flow?

**Comment by sandy081** [comment]
Yeah we can, but not super keen on supporting this. Not sure how often users get into this because we show the compatible extension in the view.
