### ISSUE TITLE
uppercase/lowercase string - use String.toUppercase() etc.

### ISSUE THREAD

**Issue by mbana** [Microsoft/vscode#8340]
Hi All,

Can we make available some text manipulation functions - this is routine stuff, e.g., even the JavaScript console supports uppercasing the string:

``` javascript
'some_string'.toUpperCase()
"SOME_STRING"
```

I can write the code myself to do this as long as it ends up in the core of the editor.

**Comment by bpasero** [comment]
@mbana sounds like a good chance for writing an extension? Or maybe check if an extension provides this already?

**Comment by alexandrudima** [comment]
:+1: PR welcome

**Comment by mjbvz** [comment]
I believe these commands were implemented by https://github.com/Microsoft/vscode/pull/15787
