### ISSUE TITLE
Move breadcrumbs to a separate line if tabs are hidden

### ISSUE THREAD

**Issue by vilic** [microsoft/vscode#83402]
![image](https://user-images.githubusercontent.com/970430/67649882-c39f5600-f975-11e9-9cf5-421092f65822.png)

![image](https://user-images.githubusercontent.com/970430/67650056-54763180-f976-11e9-98cc-03c96e4177e1.png)

Currently the breadcrumbs is basically unusable for some of our projects using a smaller screen with two editor groups / large screen with two editor groups and sidebar expanded.

**Comment by PeterShinners** [comment]
I found if I hide the editor tabs with `workbench.editor.showTabs` then the breadcrumbs are also hidden. I would like the breadcrumbs visible but not the editor tabs.

**Comment by vilic** [comment]
20 upvotes for moving to backlog? Seriously? I think this is a UI bug rather than a feature request.
