### ISSUE TITLE
Tabs: tab size changes when no icon theme is enabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83407]
@misolori can you take a look, I can reproduce in stable already, I think this maybe a regression from the icon font work.

Steps:
* disable icons (icon theme = null)
* open some tabs
* open a side editor
* reduce the size of the first editor group until a scrollbar should appear

=> 🐛 the tab close button moves

![before](https://user-images.githubusercontent.com/900690/67657008-c5592180-f955-11e9-9d10-54ba4a5c500f.gif)

**Comment by bpasero** [comment]
To be clear: we have a setting for this where I would expect the tab size of reduce its size:

![image](https://user-images.githubusercontent.com/900690/67657045-e1f55980-f955-11e9-89eb-b9da9761c49a.png)

So we need to make sure that things still work with that enabled

**Comment by misolori** [comment]
I just tested this in earlier versions ([June update](https://code.visualstudio.com/updates/v1_36)) and it reproduces the same behavior, so it's not a regression from the icon work. This appears to happen when the length of the tab name doesn't pass our min-width of 120px, if the tab name is longer than it will always fit.

Is the expected (default) behavior that the tab button never shrinks unless enabled by `workbench.editor.tabSizing`?

**Comment by bpasero** [comment]
OK let me assign myself to revisit this.

**Comment by bpasero** [comment]
Yeah it should never shrink. And the fact that it does not when icons are enabled shows that something is off.

**Comment by misolori** [comment]
This was an easy fix, applied `flex-shrink: 0` when tab sizing is `fit` (which is the default):

![gif](https://user-images.githubusercontent.com/35271042/67697233-74e9c000-f965-11e9-8342-b52e8e5ce9bc.gif)

**Comment by bpasero** [comment]
ok, maybe that got lost a while ago, thanks
