### ISSUE TITLE
Tabs: no longer show dirty indicator with "workbench.editor.highlightModifiedTabs": true

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83416]
Steps to Reproduce:

1. Configure `"workbench.editor.highlightModifiedTabs": true`
2. Make a file dirty

=> 🐛 the dirty indicator does not show up anymore

![image](https://user-images.githubusercontent.com/900690/67667780-e4b07880-f96e-11e9-8ac4-92d7ead4dcac.png)

Compared to stable:

![image](https://user-images.githubusercontent.com/900690/67667791-ebd78680-f96e-11e9-96d6-d9d53637896d.png)

I feel we had an issue in this area fixed but I think the rule is:
* if the tab close button is visible we still show the dirty indicator even when this setting is on

**Comment by misolori** [comment]
This is getting confusing. https://github.com/microsoft/vscode/issues/83157 was created because the dot was visible when `"workbench.editor.highlightModifiedTabs": true` was set, so I fixed that but now that appears that this is not expected.

I will follow your rule as guidance and update verification steps for https://github.com/microsoft/vscode/issues/64684.

**Comment by bpasero** [comment]
Yeah sorry for that, unfortunately there are many settings involved for tabs.

**Comment by bpasero** [comment]
Maybe best to quickly grab an old stable VSCode and compare how it behaves there with all the settings involved? E.g.:
* tab close button visible/hidden
* tab close button left/right
* tab sizing shrink/fit
* highlight modified tabs
* tabs disabled

**Comment by misolori** [comment]
Fixed and also verified in an older version of stable with the various settings from above:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/35271042/67696068-70240c80-f963-11e9-96c8-ba081acd1d47.png">

**Comment by bpasero** [comment]
Thanks!
