### ISSUE TITLE
Emmet Response very Slow

### ISSUE THREAD

**Issue by cng18** [microsoft/vscode#83423]
When I try Emmet command, Balance Outwards on XML files then the selection appears after a noticeable period of time (10 to 15 secs). During this time the editor stops taking keyboard input. I tried this with an XML file  having 4000 lines and another XML file with 44800 lines. The response is same. 

I tried the same files on Sublime text and there is no lag at all.  (CTRL+SHIFT+A) and boom the selection happens. Another CTRL+SHIFT+A another level. No lag at all.

**Comment by cng18** [comment]
With the smaller XML(4000lines) file its 5 to 7 secs and with the larger XML file(44800 lines) its between 10 to 15 secs. Sublime text behaves same for both the files.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions. Thanks.

**Comment by cng18** [comment]
Version:          Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS Version:       Windows_NT x64 10.0.16299
CPUs:             Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)
Memory (System):  7.88GB (2.75GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --inspect-extensions=9993
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  native_gpu_memory_buffers:     disabled_software
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_deferred_display_list:    disabled_off
                  skia_renderer:                 disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    87	  6072	code main
    0	   161	  9128	   window (Running Extensions - ipflow - Visual Studio Code)
    0	   500	 17260	     extensionHost
    0	    11	 23956	     watcherService 
    0	    10	 34528	       console-window-host (Windows internal process)
    0	    23	 19156	   utility
    0	    73	 19616	   window (Issue Reporter)
    0	    80	 20920	   gpu-process
    0	    71	 21592	   shared-process
    0	    15	 26312	   electron-crash-reporter

Workspace Stats: 
|  Window (Running Extensions - ipflow - Visual Studio Code)
|    Folder (ipflow): 247 files
|      File types: txt(18) tcl(14) csv(12) py(11) xml(9) pyc(8) yaml(7)
|                  pptx(4) pdf(3) json(2)
|      Conf files: settings.json(1)

**Comment by cng18** [comment]
I tried running with all extensions disabled. The issue still persists.

I ran the extension profiling. It shows Emmet unresponsive. I am not able to figure out how to attach the profile file to this message. Every time I drop the file into this window it opens the file

**Comment by cng18** [comment]
[vscode.emmet-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode/files/3779615/vscode.emmet-unresponsive.cpuprofile.txt)

**Comment by octref** [comment]
Yeah, the emmet parser is very slow...We replaced it for auto-completion, but I guess we need to do it in other places as well.

**Comment by stormrockwell** [comment]
I recently swapped to VSCode and I have to say my biggest gripe is how brutally slow emmet can be. It seems to require the dropdown to load to run the expand command.

**Comment by Alex1990** [comment]
I write css in Vue component file. The emmet dropdown showed slowly after my typing end. Maybe, it takes 3~5 seconds.

**Comment by Landen13** [comment]
I have this problem. I type very fast, and sometimes after typing `div.test-class` and pressing `Tab` I get `div` expanded **without** class and `.test-class` as a plain text coming after the closing `div` tag.

**Comment by muthuweb** [comment]
I too have the problem, Emmet response is very slow, for example if I type div.header and quick tab press it's not works, instead either I need to wait few seconds or use SHIFT + SPACEBAR key to achieve that .. it's annoying.

Please, guys share if you find any solution for this, thanks

**Comment by rzhao271** [comment]
@stormrockwell @Alex1990 have you two tried enabling trigger expansion on tab?
@muthuweb I'm wondering what you have shift+space mapped to? For me it doesn't expand the abbreviation at all

**Comment by Ciantic** [comment]
This can also be a problem with extension. For me if I remember correctly the Bracket Colorizer 2 caused Emmet to perform extremely poorly. I suspect there are plenty other extensions that run too early as you type, and causes some issues with autocompletions like Emmet.

**Comment by rzhao271** [comment]
Turns out replacing the parser with the language-server one as @octref suggested in https://github.com/microsoft/vscode/issues/71996#issuecomment-562273179 might help.
Closing this in favour of https://github.com/microsoft/vscode/issues/71996
