### ISSUE TITLE
Our src/typings folder needs to go away

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83421]
Rather, we should move to a model where we reference the types from our `package.json`. Unfortunately this will mean quite a bit of work for all modules that currently either do not ship with types or do not have an entry in the `DefinitelyTyped` repository. 

We can split this up by module owner, but someone needs to drive this ideally.

- [x] electron.d.ts @deepak1556  
- [x] lib.es2018.promise.d.ts @jrieken
- [x] semver-umd.d.ts @sandy081 
- [x] thenable.d.ts @jrieken
- [x] vscode-windows-registry.d.ts @sbatten (MUST go through @types/xyz because optional dep)
- [x] vsda.d.ts @weinand
- [x] windows-mutex.d.ts @bpasero (MUST go through @types/xyz because optional dep)

**Comment by bpasero** [comment]
I removed the following:
* `chokidar`
* `iconv-lite`
* `graceful-fs`

**Comment by Tyriar** [comment]
I removed modifications to xterm.d.ts, will it work by pulling the types from the module now or does it need `@types`?

**Comment by mjbvz** [comment]
Opened https://github.com/the-ress/node-windows-foreground-love/pull/4 for moving typings into the library itself. However since this library is optional and not installed on Mac/Linux builds, I'm not sure if this is the correct solution

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/node-spdlog/pull/7 for spdlog

**Comment by joaomoreno** [comment]
`spdlog@0.11.1` has been released with typings

**Comment by mjbvz** [comment]
@joaomoreno Can you please pick up the new spdlog version. I reverted my change with 768399bbe2378e0848f3d6d0cffbc65630ace3ab since it broken the remote checks

**Comment by joaomoreno** [comment]
@mjbvz Done!

**Comment by jrieken** [comment]
fyi - I have added trustworthy checkboxes and names as good as I could. also, to clarify: we cannot get rid of everything here (e.g IE11 specials) but we should aim at removing all d.ts-files for node_modules. If you/we own a node_module they should ship a d.ts-file and otherwise we need to adding to the typings registry

**Comment by Tyriar** [comment]
Note that for optional ones like windows-process-tree we probably need to keep the typings around as they won't install on non-Windows and that will result in a TS compile error.

**Comment by deepak1556** [comment]
nsfw has been addressed in https://github.com/microsoft/vscode/pull/83796, I will send a PR to bump that version against master now.

**Comment by Tyriar** [comment]
@deepak1556 was just looking at that 😄 switched to your name

**Comment by joaomoreno** [comment]
:heavy_check_mark: `windows-mutex` https://github.com/microsoft/vscode/commit/bf1ee601655388e8f57ec900f1d4098864fc720e

**Comment by joaomoreno** [comment]
Aaaaaaaaaaaand reverted bf1ee601655388e8f57ec900f1d4098864fc720e

That was fast. @bpasero @mjbvz: `windows-mutex` is an optional dependency, so it doesn't get installed on Linux and macOS. That means we get compile errors on those platforms now... is Definitely Typed the solution for this?

**Comment by bpasero** [comment]
Yes good idea, I will update the list to mention that.

**Comment by sbatten** [comment]
sorry about the unassigns

**Comment by bpasero** [comment]
I updated the list based on what we still have. 

@weinand I think VSDA was signed off but I still see it.

@jrieken there are quite a bit of d.ts still around which I think are not there because of a node module dependency. I was not sure if the 2 in the list fall into that category, please check.

**Comment by jrieken** [comment]
Yeah, they are both needed. The Thenable is required to implement the API and the promise extension is for our finally-polyfill that we have.

**Comment by weinand** [comment]
@bpasero I've added a index.d.ts to vsda but I was not able to remove vsda from typings because vsda is an optional dependency. Therefore I've added the "(MUST go through @types/xyz because optional dep)".
If you know a better solution please let me know.

**Comment by bpasero** [comment]
@weinand right, it needs to go to DefnitleyTyped 👍

**Comment by weinand** [comment]
There is now a SignService without a dependency on vsda.

**Comment by bpasero** [comment]
Created the following PRs for the remaining types:
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40962
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40873
