### ISSUE TITLE
Means to Change Terminal Text Colors

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#83426]
Issue Type: <b>Bug</b>

The integrated terminal uses dark colours on black, which I find very hard to see. I can find no way to change them, only to change the 'foreground' and 'background' colours, which helps not, as these are current white and black respectively. 
Please provide a way to change the dark blue, dark red, etc.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
cucumberautocomplete|ale|2.14.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.31.2
vscode-scss-formatter|sib|1.4.2
perforce|sle|3.2.0

(1 theme extensions excluded)

</details>

**Comment by leegee** [comment]
Maaaaaaaaaany thanks for that. 

Now I have the search terms 'terminal.ansiBlue' I see some people writing about this, but is this officially documented? 

Thanks again.

**Comment by Tyriar** [comment]
@leegee here it is: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
