### ISSUE TITLE
Destination folder for downloaded files in remote

### ISSUE THREAD

**Issue by ilsergente1993** [microsoft/vscode#83433]
I'm currently working in remote using the awesome Remote-SSH connection. While downloading many files from the host, VS code asks me the destination folder for each file. Even more the destination folder is set to `/var/` (I use Linux) forgetting my last destination. Annoying with many files.

My suggestion is to:

-  remember last destination path I've used to save downloaded files and open the save window on that path.

**OR**

- if I have selected many files would be nice to choose the destination path one time and download all the files/folders keeping the structure at the destination path on the host.

**Comment by isidorn** [comment]
Agree this makes sense. Thanks for the feedback
fyi @bpasero

**Comment by isidorn** [comment]
This should also handle the default name
