### ISSUE TITLE
Test task detail proposed API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83436]
Ref: https://github.com/microsoft/vscode/issues/69785

- [x] macOS @misolori
- [x] anyOS @stevencl  

Complexity: 3

Verify `detail` with API:
- This is already implemented in the built-in npm extension. You can verify by opening a folder that has npm scripts then running the Run Task command. Verify that each npm task as a detail in the task quick pick that shows the npm script.
- Look at the [API ](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L786) and see if it makes sense.

Verify `detail` with tasks.json:
- Try adding a `detail` to a shell or process task in tasks.json.
- Try adding a `detail` to a contributed task in tasks.json. In particular, try adding a `detail` to an npm task (since it already has a contributed detail) in tasks.json and verify that the tasks.json detail wins.

Other:
- Verify that the setting `"task.quickOpen.detail"` disables the detail from showing in the quick pick when set to false.

**Comment by misolori** [comment]
It appears that proposed api link doesn't have line 943, which line should I be looking at?

**Comment by alexr00** [comment]
You can do a find for "Task2", since the API lives in that class. I've also updated the link again.

**Comment by misolori** [comment]
This works great, loving the attention to detail in having this also show up in the npm scripts explorer:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/35271042/67779272-a1631200-fa21-11e9-8e3d-300117c8e6e2.png">

**Comment by stevencl** [comment]
Sorry I didn't get around to this yesterday. I tested on Windows and filed one bug.

**Comment by bpasero** [comment]
Ok thanks, closing then.
