### ISSUE TITLE
Terminal does not support ballistic scroll

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8343]
#8222

1. Open integrated terminal with lots of output
2. Use the trackpad to scroll a lot
3. Notice how the terminal does not respect the balistic scroll - e.g it always scrolls the same not matter how strong I scrolled

**Comment by Tyriar** [comment]
This should work if a native scroll bar is added to the integrated terminal. It was mentioned in https://github.com/sourcelair/xterm.js/issues/150 to use [clusterize](https://clusterize.js.org/) to implement native scrolling, that may have its own set of issues. Closing in favor of https://github.com/Microsoft/vscode/issues/6602
