### ISSUE TITLE
Slime theme in Web has strange line highlight

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#83432]
![capture](https://user-images.githubusercontent.com/1931590/67682508-d58df280-f98f-11e9-861a-1e947ca95ce4.png)

No sure. Starting with @bpasero

**Comment by bpasero** [comment]
Possibly something in the editor that we only see in certain themes that enable this coloring. Moving to Alex and Pung.

**Comment by alexandrudima** [comment]
well, there is the line highlight which is rendered in a bright color and on top of that is the bracket match highlight which is rendered in a less bright color.

@dbaeumer Not sure what exactly is wrong here? Does it look differently in the rich client?

**Comment by dbaeumer** [comment]
This is how it looks in the rich UI

![capture](https://user-images.githubusercontent.com/1931590/67859585-4bbf6000-fb1c-11e9-87ec-025ec57f2904.png)

**Comment by dbaeumer** [comment]
Will check again.

**Comment by dbaeumer** [comment]
I checked this week and it didn't reproduce for me.
