### ISSUE TITLE
Annoying pop-up telling me to install Java Developer Kit in order to use "java"

### ISSUE THREAD

**Issue by matgd** [microsoft/vscode#83430]
Issue Type: <b>Bug</b>

1. Open Visual Studio Code
2. Pop-up appears

I don't plan to work with Java, I'd like to see notification go.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
Actually,

**Comment by matgd** [comment]
Sure. 

<img width="532" alt="Zrzut ekranu 2019-10-28 o 17 24 12" src="https://user-images.githubusercontent.com/28411337/67696812-d16dcf00-f9a7-11e9-8467-8d651f5fd8b0.png">

**Comment by matgd** [comment]
Here are installed extensions if you suspect there might be a problem with them.

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
latex-workshop|Jam|8.2.0
html-to-jsx|ria|0.0.1
latex-utilities|tec|0.3.3
vim|vsc|1.11.3
markdown-pdf|yza|1.4.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Thanks. That popup should not come from VS Code itself. I believe one of your extensions or some action you are taking in the editor is triggering this

Please try using the `Developer: Show Running Extensions` command to see which extension is causing this

**Comment by matgd** [comment]
You're right. One of the extensions requires Java.  

It's vscode-languagetool.

Thanks for the help and sorry for trouble.
