### ISSUE TITLE
Option to disable breakpoint candidates inline

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#83446]
There was a feature request to disablie the grey dots that appear within the text of breakpoint. I first noticed the dots beginning with the release Version: 1.39.2. I think this feature needs to be escalated because the breakpoint dots have become a total nuisance.

![image](https://user-images.githubusercontent.com/1051118/67694662-1bd85700-f97a-11e9-8e67-d6d4b7af2f64.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/83018
