### ISSUE TITLE
Failed to install 'ms-python.python'

### ISSUE THREAD

**Issue by domokane** [microsoft/vscode#83448]
Issue Type: <b>Bug</b>

Python extension is suggested. But when I select it I get this error message. I have tried turning off defender but it does not help.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
Please enable the log level to `trace` using the command `F1 > Set Log Level` and try to reproduce and provide us following

- Shared log `F1 > Open View > Log (Shared)`
- Window log `F1 > Open View > Log (Window)`
