### ISSUE TITLE
Support running npm scripts from a folder in the Explorer

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#83447]
This is a feature request for the PR https://github.com/microsoft/vscode/pull/79960

To test:
- create a mono repo with different folders containing a package.json, see https://github.com/microsoft/vscode/pull/79960#issuecomment-540121382
- enable the setting `npm.runScriptFromFolder`
- select a folder in the Explorer that contains `package.json` files and run 'Run NPM Script in Folder...'. This should propose the scripts from the contained package.json files.

**Comment by rebornix** [comment]
Not sure if I miss anything but I didn't get it working

* Open a folder which contains package.json
* Add another project into the workspace, now we have two folders containing package.json
* The NPM Scripts view is not updated at all, only displaying scripts from the first folder
* Turn on setting `"npm.enableRunFromFolder": true` (there is no `npm.runScriptFromFolder`)
* Didn't find command 'Run NPM Script in Folder...'.

**Comment by egamma** [comment]
@rebornix 

>Didn't find command 'Run NPM Script in Folder...'.

The command shows up when you select a folder and open the context menu. 

Tried to reproduce using the steps you have provided and I see the action in the context menu.

@alexr00 can you please try to verify.

**Comment by alexr00** [comment]
Tested feature and it works nicely. 
I used microsoft/vscode-extension-samples as an easy way to test a single folder with many subfolders containing package.json.
