### ISSUE TITLE
PWA: starting to drag crashes app

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83441]
Steps to Reproduce:

1. run web as PWA
2. start to drag

=> 🐛 crash

**Comment by joaomoreno** [comment]
I assume you mean dragging a file from the explorer, for example. If so, this doesn't crash on Chrome in Linux. Marking it as verified.

**Comment by bpasero** [comment]
Yeah, be in PWA mode (web) and start to drag a file from the VSCode file explorer.
