### ISSUE TITLE
Debugger: after step into with source maps current line not highlighted

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#8344]
Testing https://github.com/Microsoft/vscode/issues/8193:
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10.

Testing new source map handling. See attached screen shot: I stepped into onDidCloseTextDocument and the TS code was properly shown but the current line didn't get highlighted.

![capture](https://cloud.githubusercontent.com/assets/1931590/16415911/fa93e770-3d3f-11e6-8026-a2333caf2149.png)

Selecting onDidCloseTextDocument in the Call Stack highlights correctly

**Comment by weinand** [comment]
Since we are not shipping this in June, I'll investigate in July.

**Comment by weinand** [comment]
I wasn't able to reproduce this in recent builds.
