### ISSUE TITLE
SCM: UI breaks with Azure Repos extension

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83440]
Reported by @timdang and confirmed by @zatchgordon in https://github.com/microsoft/vscode/issues/82203

If one manages to create a local workspace of a TFS repo (https://gist.github.com/counterlogik/8191caf05ee119b93073c6dd14c0c7fa) and use the [Azure Repos](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) extension, you'll notice that the whole UI breaks:

![image](https://user-images.githubusercontent.com/22350/67688381-096e1580-f99a-11e9-85a5-3f1457b8a712.png)

**Comment by joaomoreno** [comment]
@alexandrudima I call a proxy method with `undefined` in an argument:

https://github.com/microsoft/vscode/blob/741e26edea3a67ba382d0f0e1890261d7580ce2b/src/vs/workbench/api/common/extHostSCM.ts#L462

It comes out as `null` on the other side:

https://github.com/microsoft/vscode/blob/741e26edea3a67ba382d0f0e1890261d7580ce2b/src/vs/workbench/api/browser/mainThreadSCM.ts#L290

This took a while to figure out. Is there anything we should fix in that layer or is this a known kink of the proxy stuff? If so, should we `WARN` every time an `undefined` value gets sent?

**Comment by joaomoreno** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/22350/67689631-e2184800-f99b-11e9-86d4-a6cd8523fad3.png)

@timdang Do you mind confirming this tomorrow or the day after, in Insiders? Thank you!

**Comment by timdang** [comment]
@joaomoreno Confirmed that we're back in business. Thank you for all your help with this!!!
