### ISSUE TITLE
Global search case-sensitive option broken

### ISSUE THREAD

**Issue by jamesgrant** [microsoft/vscode#83443]
Issue Type: <b>Bug</b>

Video: https://imgur.com/a/jFtJvSw

1. Open global search sidebar (cmd-shift-f).
2. Disable the 'match case' option (cmd-opt-c).
3. Search for a known lower- or mixed-case term in your project using only uppercase characters (e.g for the term '#168dbf' search '#168DBF').

Expected result: Case-insensitive results are returned.
Actual result: Only case-sensitive results are returned.

Note: Search works correctly the other way around (searching with a lowercase term returns mixed- and uppercase resutls).

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
vscode-intelephense-client|bme|1.2.3
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.14.2
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|2.3.0
php-debug|fel|1.13.0
todo-tree|Gru|0.0.160
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
sublime-keybindings|ms-|4.0.3
vsliveshare|ms-|1.0.1056
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.2
sass-indented|rob|1.5.1
gitblame|wad|3.0.1

(4 theme extensions excluded)

</details>

**Comment by ManPython** [comment]
In occasion.. we need functionality for ctr+f as open search and again this shortcut to close search.

Bug can be related with difrent coding in files as asci, utf.

**Comment by roblourens** [comment]
It looks like you have the `search.smartCase` setting enabled, please check.

**Comment by jamesgrant** [comment]
Thanks @roblourens, that was it 👍 

I'm a little surprised there is no indication that `search.smartCase` is on when searching, but I guess that's a whole other concern.

**Comment by roblourens** [comment]
There is an issue for better UI. But I'm not sure about that setting in general... I might delete it
