### ISSUE TITLE
"Select a default formatter for {0}-files" shouldn't have a hyphen

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode#83452]
Steps to Reproduce:

1. choose Format Document from command palette when there are multiple formatters
2. the placeholder for the box to choose which formatter to use says "Select a default formatter for Flow-files" (in my case, the language is set to "Flow")

"Flow-files" is weird, I don't think there should be a hyphen:

https://github.com/microsoft/vscode/blob/ac719087ef99fe95ed1555da517b040a7e83e3d5/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L137

Also here, but I don't know how to repro this one:
https://github.com/microsoft/vscode/blob/ac719087ef99fe95ed1555da517b040a7e83e3d5/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L109

**Comment by gjsjohnmurray** [comment]
I will prepare a PR.
