### ISSUE TITLE
path separator missing from task args

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vscode#83457]
VS Code 1.93.2 on Windows 10
I have a simple custom task defined as:
```
{
    "label": "test task",
    "type": "shell",
    "command": "echo",
    "args": ["${workspaceRoot}/test"],
    "problemMatcher": []
}
```
Depending on the default shell this echoes:
Windows cmd: `H:\blank-task/test`
Git Bash: `H:blank-task/test`
PowerShell: `H:\blank-task/test`
WSL Bash: `H:\blank-task/test`

Only Git Bash is clearly incorrect - missing `\` after `H:`, which causes errors when I try to pass current path as some command line argument.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/84016
