### ISSUE TITLE
Monaco Editor / CSS: Intellisense for variables is not using 'var'

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8345]
#8229
Safari

Steps to Reproduce:
In Monaco Editor
1. Change the Language to css
2. Write a :root rule with a variable declaration
3. In other rules, use Intellisense to select the above variable

Expected: Intellisense should set var(--variable)
Actual: Intellisense is placing let(--variable)

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-css-languageservice/commit/243bf6a546bf1be5880c1176119eb1debd5aca60

**Comment by sandy081** [comment]
@aeschli Is not this fix yet available in monaco-editor here https://microsoft.github.io/monaco-editor/index.html

**Comment by aeschli** [comment]
You have to test that in the all source mode (https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) or wait for all versions to be bumped. @alexandrudima should do that soon.

@alexandrudima I update all version number for monaco-css / -json and -languages and published these. I updated the dependencies monaco-editor to these, but did not increase the monaco-editor version nor did I publish. I leave this up to you.
