### ISSUE TITLE
(Terminal) Option+delete doesn't delete previous word on MacOS

### ISSUE THREAD

**Issue by ns-cweber** [microsoft/vscode#83453]
On standard terminal editors on mac (as well as virtually all GUI apps, including the VS Code text editor widget), the option+delete key combination deletes the previous word. In VS Code's integrated terminal, it deletes everything up to the previous space, including multiple words separated by special characters. For example, given the cursor is at the end of the string `https://foo-bar.org/baz#qux` and option+delete is pressed, it should delete the `qux` part such that the remnant is `https://foo-bar.org/baz#`. In the integrated terminal, the entire string is deleted.

Note also that the integrated terminal behaves as expected for option+left/right--given the cursor at the end of `https://foo-bar.org/baz#qux` as before, if you press option+left, the cursor will be between the `#` and `q` characters.

I tried asking around on StackOverflow to see if I was missing something, but none of the answers addressed this issue (see this post for information about the myriad things I've already tried): https://stackoverflow.com/questions/57824640/how-to-delete-the-prior-word-with-vs-code-terminal.

Also note that this issue appears to be similar, but is in fact different (https://github.com/Microsoft/vscode/issues/11314). #11314 notes that the old option+delete behavior deleted a single character instead of a whole word, this issue is about deleting too much.

Lastly, I beg pardon if "word" is the wrong semantic. Whatever the correct label may be, the issue is the divergent behavior between the integrated terminal and other terminals.

**Comment by Tyriar** [comment]
@ns-cweber both Terminal.app and iTerm2 only delete a single character by default when using option+delete?

`alt+backspace` (option+delete on mac) is bound to the VS Code command `workbench.action.terminal.deleteWordRight` which simply sends ctrl+w:

https://github.com/microsoft/vscode/blob/e30276a213cd1adb727adcc66d12f9af444f42bc/src/vs/workbench/contrib/terminal/browser/terminalActions.ts#L220-L221

You can change this to whatever you want with a custom keybinding:

```
{
    "key": "alt+backspace",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
        "text": "send whatever you want to shell"
    },
    "when": "terminalFocus"
}
```

**Comment by Tyriar** [comment]
You should try setting `terminal.integrated.macOptionIsMeta` to true then and unbind the alt+backspace keybinding by adding this to your keybindings.json:

```
Daniel Imms 11:55 AM
{
  "key": "alt+backspace",
  "command": "-workbench.action.terminal.deleteWordLeft",
  "when": "terminalFocus"
}
```

That will mean meta+backspace gets sent to the shell for evaluation.

**Comment by mkosma** [comment]
This should not be closed. 

The problem is that command workbench.action.terminal.deleteWordRight deletes beyond non-space end-of-word boundaries, such as underscore. This is markedly different from the behavior in vsCode editor windows as well as in mac osx Terminal and iTerm. 

Ctrl+W exhibits the same, incorrect behavior.

**Comment by mkosma** [comment]
For me, I seem to be able to get the desired behavior by simply deleting the keybindings for Terminal: Delete Word Left and Terminal: Delete Word Right. Perhaps this is what @Tyriar was implying above.

**Comment by Tyriar** [comment]
@mkosma since shells are different we can't get it right everywhere, I believe the current behavior would be beneficial to more people in general. For example the current behavior works in powershell as well, if that keybinding was removed then it would not.
