### ISSUE TITLE
[Live Share] Guest initiated debugging throws exception "Configured debug type ‘vslsRemoteLauch’ is not supported"

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#83455]
- VSCode Version:

Version: 1.40.0-insider (user setup)
Commit: 33cc09da7a314ea0ee5677d1927739af60d16734
Date: 2019-10-28T11:50:41.596Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

Note: This issue repros with the latest Live Share extension from the marketplace but doesn’t repro when using VS Code Stable - so it is due to a recent change in Insiders

1.	VS Host: opens a NodeJS console app and starts a Live Share session.
2.	VS Code Insiders Guest: joins the collaboration session and Starts Debugging 

Error: Configured debug type ‘vslsRemoteLauch’ is not supported

It looks like the issue was introduced with this PR:

[debug configuration manager: async await](https://github.com/microsoft/vscode/commit/3bbd6bfd034c7d50bbfd51382bb87645b5c83fdd#diff-1356390d3ad65f9fe10d4c9fc3be8518L193)

VS Code’s DebugConfiguarationManager calls into Live Share’s JoinDebugManager to resolveDebugConfiguation. When a Live Share guest initiates a remote debug session our provider sends a message to the host to launch the debug configuration. We then return ’undefined’ to abort the remote launch and prevent launch.json from appearing.

It looks like resolveConfigurationByProviders no longer accepts undefined. When undefined is returned the original config is now used. This leads to the new unsupported error being thrown in our scenario.

This is the issue:
config = (await provider.resolveDebugConfiguration!(folderUri, config, token)) **|| config;**

**Comment by weinand** [comment]
I've reverted the commit that introduced the problem with this commit: https://github.com/microsoft/vscode/commit/d2baccdf91b5dbe7aa43a774cf34c27b10113e13

**Comment by weinand** [comment]
The LiveShare team has confirmed that the issue no longer occurs with Insiders.
