### ISSUE TITLE
Leaving Full Screen or Zen Mode leads to wrong window dimensions

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#83456]
Issue Type: <b>Bug</b>

If I enter Full Screen or Zen mode when VS Code window was maximized then exit - it will have dimensions larges than monitor.

Happens only with `"window.titleBarStyle": "custom"` (default value) and doesn't depend on `window.zoomLevel`.

Steps to preroduce:
1. Maximize VS Code window. [Screenshot](https://user-images.githubusercontent.com/1312662/67703364-fec47800-f9bb-11e9-848b-dc70d662daee.png)

1. Press <kbd>F11</kbd> or <kbd>Ctrl+K Z</kbd> twice to enter/exit full screen.
1. Window elements are now closer to screen edge or cropped because window become larger (its edges can be seen on other monitors). [Screenshot](https://user-images.githubusercontent.com/1312662/67703417-11d74800-f9bc-11e9-8ebb-1edd15678de8.png)

Clicking on Restore Down and then Maximize fixes window dimensions.

~Moreover something goes wrong with Maximize/Restore down button:~
~1. After exiting Full Screen click on Restore down button~
~2. Button doesn't change to Maximize. [Screenshot](https://user-images.githubusercontent.com/1312662/67703468-287d9f00-f9bc-11e9-885b-cd7bf122e4c2.png)~
~3. Click Maximize and then Restore Down to see that button changes to proper icon. [Screenshot](https://user-images.githubusercontent.com/1312662/67703594-59f66a80-f9bc-11e9-8391-1b9ecf476ba8.png)~
Maximize/Restore down button issue is tracked in #82384

VS Code version: Code - Insiders 1.40.0-insider (33cc09da7a314ea0ee5677d1927739af60d16734, 2019-10-28T11:50:41.596Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bpasero** [comment]
Seems like another issue with custom titlebar. I think this one might have been reported already.

**Comment by IllusionMH** [comment]
Checked with VSCode 1.39 (zip) and I cannot reproduce issue with window sizing (except it was [always 1px wider than monitor when maximized](https://user-images.githubusercontent.com/1312662/67760907-e0f22400-fa4a-11e9-8ade-50f346a8564d.png), but works properly with 1.40-insiders)

So I think it is most likely related to Electron 6.x update and I haven't found similar issues.

**Comment by bpasero** [comment]
//cc @deepak1556

**Comment by bpasero** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/84343 and/or https://github.com/microsoft/vscode/issues/81102

**Comment by deepak1556** [comment]
https://github.com/electron/electron/pull/21164 will fix this issue

**Comment by IllusionMH** [comment]
Yay! Fixed in Insiders build!

However issue mentioned in https://github.com/microsoft/vscode/issues/83456#issuecomment-547364739 returned

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/85266
