### ISSUE TITLE
[web] Source Control context menu missing some items

### ISSUE THREAD

**Issue by JtMotoX** [microsoft/vscode#83454]
- VSCode Version:
- OS Version:  macOS Mojave 10.14.6

## Description

Source Control context menu missing some items that I use frequently in VSC.
- Stage Selected Ranges
- Unstage Selected Ranges
- Revert Selected Ranges

## Steps to Reproduce

1. Git clone a repo
1. Make some changes to a file
1. Open the file diff working tree in Source Control
1. Right click one of the modified lines in the right pane
1. Underneath the "Change All Occurrences" option there should be 3 additional options (listed in the description above)

![3](https://user-images.githubusercontent.com/7191259/67701114-97330c00-f96c-11e9-874e-5627f28ab19c.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is not a bug of VS Code, these commands do appear in VS Code.

**Comment by JtMotoX** [comment]
That is my point.  Those options are missing from the web-based editor.  Please re-open this case as these options are still missing.
