### ISSUE TITLE
CSS Variable swatch in suggest widget has large gap

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83461]
<img width="119" alt="image" src="https://user-images.githubusercontent.com/35271042/67706270-b5513a00-f975-11e9-8d84-112ac1bdbfc4.png">

We recently introduced a new icon container for the symbol icons in the suggest widget, not sure if this is affected by it but it's being added to the dom twice:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35271042/67706377-e03b8e00-f975-11e9-865f-69befd50248d.png">

**Comment by octref** [comment]
@jrieken I don't think this commit looks right: https://github.com/microsoft/vscode/commit/bd6c4a88fe5a481bf23b030e6df5af07ee958216

What do you think? I can put a quick fix to make the `iconContainer`'s class `icon hide` just for release, but I feel the DOM has become more complicated than it needs to be.

**Comment by jrieken** [comment]
I trust you making the right call here 👍

**Comment by octref** [comment]
Verifier: Complete `color: i|` in CSS. Verify you don't see the gap:

![image](https://user-images.githubusercontent.com/4033249/67811963-29194280-fa5b-11e9-9bd4-0b8020ce3e7f.png)
