### ISSUE TITLE
Cannot download any json schema files when behind a proxy

### ISSUE THREAD

**Issue by TheBeardedLlama** [microsoft/vscode#83469]
Issue Type: <b>Bug</b>

When trying to fetch json schema files, VS Code ignores the proxy credential settings.
The result is that the proxy bounces back the request saying that it's unauthenticated.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz (4 x 2100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|10.00GB (3.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
ng-template|Ang|0.802.3
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
FreeMarker|dco|0.0.9
githistory|don|0.4.6
gitlens|eam|10.1.1
EditorConfig|Edi|0.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
seito-openfile|Fr4|1.8.5
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
icon-fonts|idl|2.2.2
l13-diff|L13|0.21.0
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1056
debugger-for-chrome|msj|4.12.1
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
java|red|0.52.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
Your 1.37 is two versions behind current. Are you able to update and then re-test?

**Comment by TheBeardedLlama** [comment]
after an extensive research session this issue has persisted for years

I'm sure the new version will not have fixed it (also I cannot update as my current client is unnecessarily strict with software controls)

**Comment by TheBeardedLlama** [comment]
this is not the only part of vscode that ignores proxy credentials but it is the most annoying one

**Comment by TheBeardedLlama** [comment]
I forgot to say that I'm happy to attempt a PR if someone could point me in the right direction :)

**Comment by aeschli** [comment]
Can you do the following to get more information?
- Run `Set Log Level...` and pick 'Trace'
- Open the Output view, `Log (Extension Host)` tab
- Open a JSON file add a line `"$schema": "http://json.schemastore.org/bower#",` on top
- The output should show information on how the proxu resolved the address:
E.g. in my case (no proxy)
[2019-12-05 11:09:55.241] [exthost] [trace] ProxyResolver#resolveProxy cached http://json.schemastore.org/bower DIRECT
