### ISSUE TITLE
SCM statusbar contribution invisible until extension is activated

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#83464]
Issue Type: <b>Bug</b>

1) open a folder that has changes in the remote (ensure SCM provider is not activated)
-> Normally the statusbar indicates the incoming changes, but there is no Source Control status bar item. Also, the statusbar context menu, does not show teh Source Control entry.
2) Open the SCM view
-> statusbar item shows up

VS Code version: Code - Insiders 1.40.0-insider (33cc09da7a314ea0ee5677d1927739af60d16734, 2019-10-28T11:46:25.634Z)
OS version: Darwin x64 18.7.0
Fetching remote diagnostics for 'vsonline+a9b3b743-0322-4bb5-8085-a84534b4a3c3' timed out.
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|-psn_0_2216477|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'vsonline+a9b3b743-0322-4bb5-8085-a84534b4a3c3' timed out.

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.0.0-1022-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (9.16GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.0.0-1022-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (9.16GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.0.0-1022-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (9.16GB free)|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Broken by 79566

**Comment by joaomoreno** [comment]
@bpasero Yeah you're right, let's clean that up as well.
