### ISSUE TITLE
Paths after unrecognized options are ignored

### ISSUE THREAD

**Issue by travisdowns** [microsoft/vscode#83460]
- VSCode Version: 1.39.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. mkdir foo
2. Run `code --enable-native-gpu-memory-buffers foo`

You get a warning:

    Option 'enable-native-gpu-memory-buffers' is unknown. Ignoring.

However, the warning is wrong - the option is not ignored but understood by electron (use `code --status` to confirm that native buffers are used with this, but not without).

The problem is that the path `foo` is now ignored: `code` will open in the last used directory, not `foo`.

Per `code --help` paths should appear after options:

~~~
$ code --help
Visual Studio Code 1.39.2

Usage: code [options][paths...]
~~~

... but in this case it isn't working. 

It works if you put `foo` first, before the unknown option, but this doesn't work for me because I have `alias code='code --enable-native-gpu-memory-buffers'` so paths necessarily go at the end.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
There a huge number of chromium command line switches (https://peter.sh/experiments/chromium-command-line-switches/). We can't add them all to our list of supported arguments, as we don't know which of them work and what the side effects are.

But we should add the ones that are useful. Then we no longer will show the warning and we also know that it's a boolean argument.

Can you describe what's the need for `enable-native-gpu-memory-buffers` ? 

We could also decide to add add a -chromiumflags argument where the user can add any kind of flags that we don't need to check.
@bpasero @joaomoreno FYI

**Comment by travisdowns** [comment]
@aeschli - well I guess most of them are potentially useful in that they were useful for Chrome rending and I suppose could be useful in some scenario in VSCode rendering as well.

My use case for `--enable-native-gpu-memory-buffers` is to greatly reduce the flickering  described in #69432. Unfortunately that was closed as a dupe, but it's duped against something which suggests `--disable-gpu` - but for me `--disable-gpu` causes another type of artifact (vertical corruption/lines appearing usually near the cursor), so I am using `--enable-native-gpu-memory-buffers` which suffers no corruption and minimal flickering. Basically it whitelists your machine on Linux, as Chromium I think disabled native GPU buffers on Linux due to bugs with many drivers.

That said, I wouldn't like this issue to become a discussion of `--enable-native-gpu-memory-buffers` specifically, since I imagine passing arguments to the chromium core is useful in general.

My personal feeling is the `--chromiumflags` approach makes a lot of sense.

**Comment by aeschli** [comment]
In the meantime I have improved the message to a warning:
`Warning: 'enable-native-gpu-memory-buffers' is not in the list of known options, but still passed to Electron/Chromium.`
