### ISSUE TITLE
Terminal settings per OS not alligned with rest of vscode

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8346]
#8222

1. Open settings.json and checkout terminal settings
2. Notice how there are 3x some settings for each OS
3. This is not alligned with rest of vscode (tasks.json, launch.json) where a user can specify an OS as field of a setting. By doing this we will not have so many settings for the terminal which will make it more compact and easier to read.

e.g
```json
 "terminal.integrated.shell": {
  "osx": "lala",
  "linux": "asdasd"
}
```

![screen shot 2016-06-28 at 14 52 00](https://cloud.githubusercontent.com/assets/1926584/16415921/05c97ede-3d40-11e6-8282-817038cb7c2b.png)

**Comment by Tyriar** [comment]
Requesting feedback @Microsoft/vscode

What is the ideal format for the settings? :+1: the comment you like if you can't be bothered talking :smiley:

**Comment by Tyriar** [comment]
#### Option 1

What is currently done:

```json
{
  "terminal.integrated.shell.linux": "bash",
  "terminal.integrated.shellArgs.linux": ["-l"]
}
```

**Comment by Tyriar** [comment]
#### Option 2

```json
"terminal.integrated.shell": {
  "linux": "bash"
}
"terminal.integrated.shellArgs": {
  "linux": ["-l"]
}
```

**Comment by Tyriar** [comment]
#### Option 3

Put both the shell executable and args into OS key:

```json
"terminal.integrated.shell": {
  "linux": {
    "exec": "bash",
    "args": ["-l"],
  }
}
```

**Comment by Tyriar** [comment]
#### Option 4

Hybrid of Option 2 and 3, where the os key can take either a string (the executable), or an object (the executable and optionally the args array).

```json
"terminal.integrated.shell": {
  "linux": {
    "shell": "bash",
    "args": ["-l"],
  },
  "osx": "bash"
}
```

**Comment by egamma** [comment]
Settings are different from launch.json and task.json and we intentionally made them as flat as possible so Option 1 is consistent with the existing practice.

**Comment by Tyriar** [comment]
Closing as designed, we want to keep settings as flag as possible.
