### ISSUE TITLE
Allow extensions to control order of FileSearch results

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#83462]
Currently the 'proposed' API lets extensions provide file search results with a list of URIs:

https://github.com/microsoft/vscode/blob/df17be45e3035d9642f59136a07cd7452ef55060/src/vs/vscode.proposed.d.ts#L338-L346

However the results are re-ordered in `openAnythingHandler`: https://github.com/microsoft/vscode/blob/e65a9f0a1053865e4533545aba81b6f88644a9d2/src/vs/workbench/contrib/search/browser/openAnythingHandler.ts#L125-L127

The problem is my file search results are already sorted by my relevance metric, but our extension has no control over how they are displayed.

Idea: Add `score` parameter to the proposed API return value, so it would become `{uri: Uri, score: number}[]`, and use the score when displaying results

Similar to https://github.com/microsoft/vscode/issues/73904

**Comment by pelmers** [comment]
If someone were to contribute this change, do you have any suggestions on the new API signature?

Would it need to be backwards-compatible or could it use a new type?

**Comment by roblourens** [comment]
I kind of like the idea of just including an optional 'score' on the result. The questions I have are

- Should it be per-provider or per-response? In other words, would a provider ever do its own sorting for one request and let vscode sort for another request? Alternatively when the provider is registered, it could have a set of options or "capabilities" that enables or disables sorting for calls to that provider
- Pros/cons of giving a "score" vs just ordering results in the order that they are returned
- What about mixed workspaces with two folders that have different search providers. How do we sort results when one opts in to vscode's sorting and the other does its own sorting?
- Is this relevant to text search? Can we say the scoring only happens at the file level, or are individual matches scored differently?

Anyway I am open to taking a PR for this so you can try it out. I will definitely be working on search API again at some point but can't say when exactly that will be...
