### ISSUE TITLE
Drag & Drop overwrites file without asking

### ISSUE THREAD

**Issue by LeoDJ** [microsoft/vscode#83478]
- VSCode Version: 1.38.1
- OS Version: Windows 10 1903

Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce

1. Open project in VS Code
2. Drag a file with the same name as a file already existing in the project from the Windows Explorer into the VS Code folder structure
3. The file in the project gets overwritten without asking first, if it has any uppercase letters in the filename

## Expected behaviour
VS Code should ask if the file should be overwritten. Just like it already does when doing a drag & drop from inside VS Code or with files that only contain lowercase letters

**Comment by LeoDJ** [comment]
Addition: It only happens, when the file inside VS Code has uppercase letters.

E.g. drag ReadMe.md onto readme.md => VS Code asks
drag readme.md or ReadMe.md onto ReadMe.md => VS Code doesn't ask

**Comment by isidorn** [comment]
@LeoDJ thanks for reproting this.
