### ISSUE TITLE
--diff does not work with WSL

### ISSUE THREAD

**Issue by jedislight** [microsoft/vscode#83473]
Issue Type: <b>Bug</b>

On a WSL environment
code --diff a.file b.file

observe: file a and b are opened in a new editor

expected: file a and b are opened in a unified diff view in a new editor

Extension version: 0.39.5
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

**Comment by aeschli** [comment]
TO verify:
Run `code-insider -d file1 file2` in a WSL shell (not the integrated shell)

**Comment by alexr00** [comment]
Ran ` code-insiders -d script.bat script.js` wsl.exe (which I launched from cmd.exe) and ended up in a weird state:
![wsldiff](https://user-images.githubusercontent.com/38270282/67948409-ee8fe100-fbe5-11e9-9499-1ccf4dec0482.gif)

**Comment by aeschli** [comment]
Are the files existing?
The error says somthing about WSL remote extension not installed?

I tried and it works for me:
![image](https://user-images.githubusercontent.com/6461412/67957146-78937600-fbf5-11e9-9d1b-5409acc34002.png)

**Comment by alexr00** [comment]
User error. I had two version of insiders installed. Thanks for looking!
