### ISSUE TITLE
Extensive CPU usage / Slow TypeScript Intellisense

### ISSUE THREAD

**Issue by panchalkalpesh** [microsoft/vscode#83474]
## Description: 
VS Code Intellisense takes extremely longer to suggest keywords while typing in a TypeScript project. 

- VSCode Versions:
   - 1.39.2 
   - 1.40.0-insider
- OS: macOS Mojave 10.14.6 (18G95)

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

```
Version: 1.40.0-insider
Commit: 33cc09da7a314ea0ee5677d1927739af60d16734
Date: 2019-10-28T11:46:25.634Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

## Steps to Reproduce:

1. Open VS Code
2. Open a typescript project (Angular 8 used for this Bug report)
3. Open any `.ts` file
4. Type the name of a component/service within your project

Does this issue occur when all extensions are disabled?: **Yes**

## Process Explorer:
![Screen Shot 2019-10-28 at 3 09 03 PM](https://user-images.githubusercontent.com/1808686/67710046-9662a000-f995-11e9-8508-ac651dfa8e44.png)
![Screen Shot 2019-10-28 at 3 09 31 PM](https://user-images.githubusercontent.com/1808686/67710235-f3f6ec80-f995-11e9-8cc4-c2a328703c40.png)

Issue created in response to: https://github.com/microsoft/vscode/issues/82846#issuecomment-546436267

**Comment by mjbvz** [comment]
What cases do the two screenshots show? 

Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that help?

**Comment by panchalkalpesh** [comment]
It shows the CPU and Memory utilization per process. 
TypeScript server is consuming most of it. 

Also, I see the following in VS Code status bar: 
![Screen Shot 2019-10-29 at 10 26 25 AM](https://user-images.githubusercontent.com/1808686/67776477-bd24e300-fa36-11e9-81d1-d2930c17b3f8.png)

**Comment by panchalkalpesh** [comment]
> Also please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next). Does that help?

I've installed this extension and now using the following version: 
![Screen Shot 2019-10-29 at 10 32 45 AM](https://user-images.githubusercontent.com/1808686/67777056-97e4a480-fa37-11e9-80df-d2e99d8f4163.png)

**Comment by mjbvz** [comment]
Did the help? Are there any errors in the developer console? Run `Developer: Toggle Developer tools` to check

**Comment by ymoran00** [comment]
I had the same problem, and it seems that using the next version solved it. :)
