### ISSUE TITLE
Selection Highlight in Scroll Bar Broken for C++/C#

### ISSUE THREAD

**Issue by yxrkt** [microsoft/vscode#83475]
Issue Type: <b>Bug</b>

1. New File (Ctrl+N)
2. Enter the following text
```
class Foo
{
}

class Bar
{
}
```
3. Double click one of the `class` words
4. Notice the scroll bar: Both selections are marked
5. Change the language to C++ or C# (Ctrl+K, M)
6. Double click one of the `class` words again
-> Notice the scroll bar no longer marks each selection

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (37.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.1.6
insertnumbers|Asu|0.9.1
unique-lines|bib|1.0.0
vscode-svgviewer|css|2.0.0
gc-excelviewer|Gra|2.1.32
jsonnet|hep|0.1.0
reg|ion|1.0.1
center-editor-window|kai|2.3.0
cpptools|ms-|0.26.1
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
todotasks|san|0.5.0
vscode-autohotkey|sle|0.2.2
overwatch|vic|0.1.3
t4-support|zbe|0.4.3

</details>

**Comment by mjbvz** [comment]
This sounds expected. The scrollbar occurrences markers have the following behavior:

* in plain text files, or in languages that don't have intellisense, show all text occurrences of the highlighted word

* For languages that have IntelliSense, show the semantics occurrences of the highlighted word.

C++ and C# have support for showing semantic occurrences, so simple plain text matches will not be shown. Please file an issue against one of those extensions if you want this behavior changed

**Comment by hummerd** [comment]
@mjbvz 
Can it be customizable setting
"editor.occurrencesHighlight": ["semantic" | "text" | "none"]
?
Since semantic highlight does not cover all user cases, for example:
I can search for different variables with same name.
I can search just word (part of function or variable name).
