### ISSUE TITLE
Outline issues with Twistie in Find and replace widget 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8347]
#8229 
Safari

Steps to Reproduce:
In Monaco Editor
1. Ctrl + F to open Find and replace widget
2. Shift Tab to select Twistie button

Expected: Outline on Twistie button should be complete
Actual: Not properly outlined

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#139

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
