### ISSUE TITLE
showQuickPick with single item missing label causes entire quickPick to be blank

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#83485]
We have an extension where we are reading JSON and converting it into a QuickPickItem in order to display a selector to the user. However, we had an issue where a release was made with the `label` key mispelled. This is a quick pick of about 35 items, and just this one missing caused the quick pick to show up with 0 items. The quick pick window still poped up however, which was very confusing. I think this should either ignore any quick picks with missing label properties, or give an error rather then just showing an empty quick pick.

- VSCode Version: 1.39.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. use showQuickPick with an array of QuickPickItem elements, with one item missing having the label key missing or mispelled.
2. Observe the quick pick being empty.

**Comment by chrmarti** [comment]
Our typings require a `label` property.

**Comment by devanshj** [comment]
vscode apis don't do runtime type checking so isn't this "as-designed" instead of "bug" and should be closed? As far as solving the original problem is concerned runtime type checking can be done userland.
