### ISSUE TITLE
Test: Active/Inactive themable window border

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83486]
Refs: https://github.com/microsoft/vscode/issues/71690 & https://github.com/microsoft/vscode/issues/54507

- [x] macOS @alexandrudima
- [x] windows @joaomoreno
- [x] Linux @bpasero

Complexity: 2

Using the new `window.activeBorder` & `window.inactiveBorder` theme colors, ensure that they are appropriately applied and on macOS have a border radius that matches the OS. Note, these colors should **only** be applied on the desktop and only if the custom titlebar is enabled. Also, if only one of these colors is set, it should fallback to which ever one is set.

**Comment by bpasero** [comment]
Note: this requires a custom titlebar to be enabled, which is the default on macOS and Windows.

**Comment by zhyy2008z** [comment]
When full screen, can you hide the borders?  Borders can't be drag. I prefer to drag menu bar,  when I  drag on those borders, it does not work. Forgive my poor english, thank you!
