### ISSUE TITLE
Java braceless conditionals

### ISSUE THREAD

**Issue by PeaProtein** [microsoft/vscode#83482]
Issue Type: <b>Bug</b>

Issue is a midpoint between a bug and a feature request, but I went with bug for priority.

Whenever I write an if-statement without a curly brace such that there is only 1 line following the if, the vertical line indicating the scope of the if doesn't terminate until a new line of code.

What I write:
if (some condition)
    doThis;

other;
lines;
of code;

What it shows:
if (some condition)
|   doThis;
|
other;
lines;
of code;

The vertical line continued beyond the statement "doThis;" and only terminated once it encountered "other;". I am not using any extensions.

What it should show:
if (some condition)
|   doThis;

other;
lines;
of code;

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Could it be as simple as configuring Java to use [offSide folding](https://github.com/Microsoft/vscode/issues/3353#issuecomment-330797736)?

**Comment by rebornix** [comment]
Solution proposed above. Thanks all!
