### ISSUE TITLE
VS code has been crashing 

### ISSUE THREAD

**Issue by K10shah** [microsoft/vscode#83480]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by K10shah** [comment]
![image](https://user-images.githubusercontent.com/10755483/67724415-273c7a00-f99c-11e9-894d-ba22b308299e.png)

**Comment by K10shah** [comment]
Ever since I opened a very long file on Code, every subsequent fresh window(the first instance of vscode to start) off VScode crashed

**Comment by mjbvz** [comment]
Please fill out the issue template (the required info was copied to your clipboard when you first filed this issue)

/needsMoreInfo
