### ISSUE TITLE
Replace: Pressing enter in replace input field should invoke the replace all action

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8348]
Refs: https://github.com/Microsoft/vscode/issues/8184

Since you get a confirm dialog anyways, I think that is fine to do!

Maybe if you do not yet have any search results we run the search on enter?

**Comment by sandy081** [comment]
@bpasero Yes, there would be a flow where users will put text in search and replace text boxes and submit in replace. So on enter always goes for search results. 

If we have to change, then, we need to make a case where it runs only replace and we will have different behavior for enter. I do not know if it is good.

**Comment by sandy081** [comment]
I am closing this in favor of returning search results on enter.
