### ISSUE TITLE
Ctrl+K, ctrl+D: Language client is not ready yet

### ISSUE THREAD

**Issue by rosanch** [microsoft/vscode#83488]
If I right-click the PowerShell file it does nothing and when I type the shortcut ctrl+K, ctrl+D shows the error: 
Language client is not ready yet.

I do have install the PowerShell extension

**Comment by mjbvz** [comment]
Please start by filing this against the powershell extension

**Comment by rosanch** [comment]
@mjbvz  does the formating is part of the extension? I thought it was a feature of Vscode.
