### ISSUE TITLE
[debug] variables hovers switches between type and value hover

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8349]
- Follow steps https://github.com/Microsoft/vscode/issues/8199
- Move mouse over a variable name and move it slowly to name below
- observe that the hover shows first a name, then the value then the next name. Looks strange, should only show types.

**Comment by aeschli** [comment]
![variable-hover](https://cloud.githubusercontent.com/assets/6461412/16417370/de36db04-3d45-11e6-8e8f-1aa8eebe094e.gif)

**Comment by isidorn** [comment]
When you hover over the name we show the type, when you hover over the value we show the value (useful for long values).
Not sure where you are hovering over in the gif since I do not see your mouse.

**Comment by aeschli** [comment]
Sorry for not showing the mouse pointer (it is camera shy).
I only move over the types, vertically down.
