### ISSUE TITLE
terminal.integrataed.splitCwd inherited doesn't work correctly for unicode characters

### ISSUE THREAD

**Issue by CrazyF-wind** [microsoft/vscode#83496]
when split terminal in chinese path,error!

**Comment by CrazyF-wind** [comment]
I think this is language's problem.

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by CrazyF-wind** [comment]
Thanks for your reply!

**Comment by Tyriar** [comment]
Thanks, you can probably workaround this with this setting:

```
"terminal.integrated.splitCwd": "initial"
```

**Comment by CrazyF-wind** [comment]
I has try this settings by your suggestion. And it really not error.Thanks!But this way to create a terminal is not my default way.When I create a new terminal.It go to its father's file path , not it is before. If has a way to realize my need?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5964554/67911440-87f8cc00-fbc1-11e9-96c9-51c6bf7d38cf.gif)

**Comment by Tyriar** [comment]
Yeah that's what the setting does, you can't get what you're after until we fix this bug.

**Comment by CrazyF-wind** [comment]
OK!I understand.Thank you!

**Comment by Arnaud73** [comment]
I guess this is obvious, but the problem also occurs with European characters (at least french), and very likely with Arabic, Japanese, Indian, Korean characters as well.

I also switched to `"terminal.integrated.splitCwd": "initial"` in order to work around the problem.

**Comment by Recmo** [comment]
I had this issue with the project folder itself containing unicode (greek letters). To my surprise, the `"terminal.integrated.splitCwd": "initial"` hack still worked, the new terminal now sucesfully launches in the project folder.

**Comment by Tyriar** [comment]
To verifier: When testing make sure shell integration is off
