### ISSUE TITLE
Editor: Font Ligatures setting missing comment and not displayed as boolean

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#83491]
- VSCode Version: 1.40 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open the Settings editor and search for "font".

Notice that the Editor: Font Ligatures settings is no longer shown as a boolean checkbox, has no description, and shows "Edit in settings.json".

Something may have been lost in a recent refactoring.

**Comment by gregvanl** [comment]
OK, then the issue is just that the setting doesn't have a description.

**Comment by roblourens** [comment]
Not planning on supporting complex types like that right now. But it does need a description.

**Comment by gregvanl** [comment]
Looks like the EditorOption definition is missing a description at the outer object. Once the type is known, either boolean or string, there is an appropriate description on hover but there is nothing if the type isn't known.
There should be a general description of true, false, or the new advanced setting. This description will show up in the Settings editor, initial IntelliSense in settings.json (before the type is known), and the Default Settings (JSON). 
Right now in Default Settings (JSON), the users sees an empty comment:
```json
	// 
	"editor.fontLigatures": false,
```

**Comment by Angelki** [comment]
Change the value to string. `"editor.fontLigatures": "true",`
