### ISSUE TITLE
Files menu and Explorer disappearing on Windows 7

### ISSUE THREAD

**Issue by debabratapatra** [microsoft/vscode#83498]
Files menu and Explorer disappearing on clicking on search menu(from left) on windows 7.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.44GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
python|ms-|2019.10.44104
java|red|0.52.0
vscode-xml|red|0.9.1
vscode-scss-formatter|sib|1.4.2
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-maven|vsc|0.19.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.7.2

</details>

![image](https://user-images.githubusercontent.com/5602062/67741451-2c063a00-fa3f-11e9-9a52-a6b49677f429.png)

**Comment by sbatten** [comment]
@debabratapatra can you clarify what you mean by files menu?

**Comment by debabratapatra** [comment]
@sbatten, Sorry for the confusion. Explorer icon(Highlighted below) disappears when you click on Search, Source Control icons. Please see the image below.

![image](https://user-images.githubusercontent.com/5602062/67830976-c3809100-fb02-11e9-83db-d6b9c36d719d.png)

**Comment by sbatten** [comment]
@debabratapatra when it is hidden, what do the contents of the context menu show (right-click any icon)

![image](https://user-images.githubusercontent.com/6561887/67886307-7e5e5e00-fb06-11e9-91ee-016353a2d16b.png)

**Comment by debabratapatra** [comment]
@sbatten yes that's how(right-click) I was bringing the explorer section back. Interestingly I am not seeing this issue from yesterday. Seems to be working fine now!

**Comment by sbatten** [comment]
@debabratapatra please re-open if it comes back, thanks
