### ISSUE TITLE
win32.findExecutable should check if the found file entry is a file and ignore directories.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#83509]
See https://github.com/OmniSharp/omnisharp-vscode/pull/3372 for a full explanation on what the underlying problem is.

The code part to be fixed in VS Code is here: instead of doing an exist we should stat and check whether it is a directory or a file. Only if it is a file we should return.

https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/processes.ts#L467

**Comment by dbaeumer** [comment]
Should try to fix this for October.

**Comment by connor4312** [comment]
I can verify the resolution, but the user reported earlier today it's still happening for him. Following up on the linked issue.

**Comment by connor4312** [comment]
The commit fixed one issue which I easily reproduced and verified on Windows, but it appears to be different than the one that the user is running into (see https://github.com/OmniSharp/omnisharp-vscode/pull/3372#issuecomment-548446833)
