### ISSUE TITLE
5 problems  in settings.json

### ISSUE THREAD

**Issue by erickxs** [microsoft/vscode#83504]
Issue Type: <b>Bug</b>

I just open the console and I saw that error...

http://prntscr.com/pphz36

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
turbo-console-log|Cha|1.3.1
bracket-pair-colorizer-2|Coe|0.0.28
codealignment-vscode|cpm|2.0.19
vscode-faker|dee|1.3.0
vsc-material-theme|Equ|30.0.0
php-intellisense|fel|2.3.13
vscode-mysql|for|0.4.0
jsx-beautify|gog|0.0.5
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
html-tag-wrapper|hwe|0.2.3
path-autocomplete|ion|1.13.3
mysql-syntax|jak|1.3.1
php-cs-fixer|jun|0.1.127
mirc|lol|0.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.6.2
vscode-language-pack-es|MS-|1.39.3
vs-keybindings|ms-|0.2.0
php-docblocker|nei|2.0.1
material-icon-theme|PKi|3.9.1
format-html-in-php|rif|1.6.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
vscode-icons|vsc|9.5.0
wordpress-toolbox|wor|1.3.5
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Clearly line 183 of your settings.json file is not valid JSON. It's probably intended to be a comment, so you should prefix it with `//` just like has been done with the adjacent lines.

/question
