### ISSUE TITLE
Unclear wording

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83508]
re #83033

> // If the command line argument does not have any values, simply assign
// it in the JSON below with a value of 'true'. Otherwise, put the value
// directly.

🔝 that's quite hard to understand. unsure if should differentiate between switches and arguments? I would add a sample tho, e.g `--disable-gpu` becomes "disable-gpu": true, etc

**Comment by jrieken** [comment]
Related to the description, I would add `disable-gpu` as commented out config value. So instead of 

```
// If you see rendering issues in VSCode and have a better experience
// with software rendering, you can configure this by adding:
//
// 'disable-gpu': true
```

I would use 

```
...
// NOTE: Changing this file requires a restart of VSCode.
{
  // Enabled by default by VSCode to resolve color issues in the renderer
  // See https://github.com/Microsoft/vscode/issues/51791 for details
  "disable-color-correct-rendering": true,

  // Use software rendering instead of GPU rendering. Often helps when seeing rendering issues.
  // 'disable-gpu': true
}
```

**Comment by bpasero** [comment]
I think the documentation of the file is from a time where I thought I would support any kind of CLI args. This is no longer the case so I will update it.

**Comment by bpasero** [comment]
I think given the intellisense help, there is no need to explain how the file works. If we add another argument to this list, the JSON validation will make sure the user is typing the right thing.

New contents:

```json
// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelyhood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
	// Enabled by default by VS Code to resolve color issues in the renderer
	// See https://github.com/Microsoft/vscode/issues/51791 for details
	"disable-color-correct-rendering": true,

	// Use software rendering instead of hardware accelerated rendering.
	// This can help in cases where you see rendering issues in VS Code.
	// "disable-hardware-acceleration": true
}
```

**Comment by jrieken** [comment]
verified - tho it's a little unfortunate that all existing files (for insiders) aren't regenerated and hence unfixed
