### ISSUE TITLE
Initial task loading is extremely slow with Gulp, even when using tasks.json

### ISSUE THREAD

**Issue by PFight** [microsoft/vscode#83506]
Still having https://github.com/Microsoft/vscode/issues/9613 reproduced.

There are no any comments in referenced ticket, and it is closed. Please, consider to explain, why ticket is closed and how to manage this problem. It is very very frustrating. It is easier for me to open terminal and enter command by hands then using task runner. I quite often restart VSCode due to some reasons (bugs in TS language services and syntax highligthing, switching over projects, changing TS configurations etc.), so I meet this problem almost every time I going to run some task.

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by alexr00** [comment]
Gulp is just slow, not much we can do about that. You can turn off gulp task auto detection with `"gulp.autoDetect": "off" and just put the gulp tasks you need in your tasks.json.
`
