### ISSUE TITLE
Undo action on Find/Replace widget should undo in the editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8350]
#8229

Safari

Steps to Reproduce:
1. Open Find/Replace widget
2. Type a find term and replace term
3. Press Enter to replace
4. Do undo

Expected: This should undo the replace
Actual: This is calling browser undo

**Comment by alexandrudima** [comment]
@sandy081 Where is the focus when you undo? The UI element that has focus should handle undo. If your focus is in the replace input box, then that input box should handle the undo. Or you think that is unexpected?

**Comment by sandy081** [comment]
Focus is in replace input box. I think in this case, it would be nice to undo the last replace done in the editor.

**Comment by alexandrudima** [comment]
I don't agree. In my opinion, each input box should have its own undo stack that allows you to undo mistakes. We can discuss this in next's week UX meeting.
