### ISSUE TITLE
Unable to Debug Go Program in Visual Studio Code

### ISSUE THREAD

**Issue by mrkkishan** [microsoft/vscode#83505]
I have written a go program, but from past one week i am not able to debug the code that i have written in go. I get the following error when i try to debug. Can you please help?

Console Output:

could not launch process: fork/exec d:\Work Stuff\GoWork\Practice\codewars\6kyu\Vasya - Clerk\__debug_bin: This program is blocked by group policy. For more information, contact your system administrator.
could not remove d:\Work Stuff\GoWork\Practice\codewars\6kyu\Vasya - Clerk\__debug_bin: remove d:\Work Stuff\GoWork\Practice\codewars\6kyu\Vasya - Clerk\__debug_bin: Access is denied.
Process exiting with code: 1

Launch.json:
{
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }

**Comment by mjbvz** [comment]
Please file this against the go extension

**Comment by Al-Mond** [comment]
This was the hit for my search, so I'll post here. This looks to be cause by git. If you add *__ in general or specifically that *__debug_bin to your gitignore file thingy, the error goes away.
