### ISSUE TITLE
Disable GPU not suggested

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83507]
re https://github.com/microsoft/vscode/issues/83033

* open the runtime args file
* trigger intellisense
* :bug: no disable gpu despite it being documented a few lines above

<img width="679" alt="Screenshot 2019-10-29 at 09 34 29" src="https://user-images.githubusercontent.com/1794099/67750388-6962cb80-fa2f-11e9-8087-1854e8a9d0db.png">

**Comment by bpasero** [comment]
Yeah good catch, I renamed it later...

**Comment by bpasero** [comment]
Oh I think you had the file from a previous version in your data folder. Can you ensure to delete the file first and then start insiders again to have it recreated, it should look something like this then:

**Comment by bpasero** [comment]
With my fix for https://github.com/microsoft/vscode/issues/83508, the contents should be:

```jsonc
// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelyhood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
	// Enabled by default by VS Code to resolve color issues in the renderer
	// See https://github.com/Microsoft/vscode/issues/51791 for details
	"disable-color-correct-rendering": true,

	// Use software rendering instead of hardware accelerated rendering.
	// This can help in cases where you see rendering issues in VS Code.
	// "disable-hardware-acceleration": true
}
```
