### ISSUE TITLE
Replace: removing last match of a file should not show "no matches"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8351]
Refs: #8184

Instead it should just be removed from the list as long as I am in replace mode.

![image](https://cloud.githubusercontent.com/assets/900690/16416449/951a2c1c-3d42-11e6-9870-81d890666283.png)

Same for when applying a replacement.

**Comment by sandy081** [comment]
#8278 is for similar issue. Hence marking this as duplicate.

duplicates #8278
