### ISSUE TITLE
Cannot run VS code to my mac

### ISSUE THREAD

**Issue by Fishbunny** [microsoft/vscode#83516]
Downloaded, dropped into application folder however when I tried to launch the program I got the following:

Process:               Electron [43319]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [43319]
User ID:               502

Date/Time:             2019-10-29 18:34:56.817 +0900
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        29D093B9-45FE-FDF9-9F53-149BBC50CA56

Sleep/Wake UUID:       5F427638-0D55-48D4-A137-016ED28E8651

Time Awake Since Boot: 710000 seconds
Time Since Wake:       1200 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short

Binary Images:
    0x7fff6f872000 -     0x7fff6f8a892f  dyld (353.2.4) <3C068A0D-69D5-3AD6-86D9-6261D3B1564E> /usr/lib/dyld
    0x7fff8b1cc000 -     0x7fff8b244ff7  com.apple.SystemConfiguration (1.14.4 - 1.14) <B835C014-901E-37B7-BD09-2EFF5FFEB910> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff8e9d9000 -     0x7fff8ea4bfff  com.apple.framework.IOKit (2.0.2 - 1050.20.2) <09C0518C-90DF-3FC3-96D6-34D35F72C8EF> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8f78d000 -     0x7fff8f78dfff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff90424000 -     0x7fff9069afff  com.apple.security (7.0 - 57031.40.9) <8D9CB878-BB71-3CF1-88CE-9E6FAC4043ED> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff92323000 -     0x7fff92654ff7  com.apple.Foundation (6.9 - 1154.20) <3D37F9B8-96CC-324B-9062-0A7E4ABCDC1F> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

Model: MacBookPro7,1, BootROM MBP71.0039.B0B, 2 processors, Intel Core 2 Duo, 2.4 GHz, 4 GB, SMC 1.62f7
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x802C, 0x384A53463235363634485A2D314731443120
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x802C, 0x384A53463235363634485A2D314731443120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.3.6f4 17916, 3 services, 27 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: TOSHIBA MK2555GSXF, 250,06 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: Internal Memory Card Reader
USB Device: Built-in iSight
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus:

**Comment by Fishbunny** [comment]
![image](https://user-images.githubusercontent.com/57133464/67756077-b3be6980-fa7c-11e9-9cc3-772f556274d0.png)

**Comment by skywinder** [comment]
Confirmed. Can't run vs code on her. machine. The MacBook is pretty old, but satisfy the installation requirements

**Comment by deepak1556** [comment]
Seems like an incomplete framework downloaded, can you try the latest stable from https://code.visualstudio.com/ ?
