### ISSUE TITLE
[json] file schema loaded on client instead of server

### ISSUE THREAD

**Issue by TheBeardedLlama** [microsoft/vscode#83515]
Issue Type: <b>Bug</b>

Due to issue #83469 I am trying to work around it until it gets fixed.
I found out that you can use file urls to point a particular schema to a local copy.
However, when I do, VSCode still insists on trying to download it over the wire.
The interesting thing is that if the path is not well formed and doesn't map to a real file, I get an error about the path. However, when the path is well formed and the file exists it just ignores it and goes over the wire instead...

This is my `json.schemas` section:

        "json.schemas": [
                {
                        "fileMatch": [
                                "/package.json"
                        ],
                        "url": "file:///C:/Users/user/Downloads/schemas/package.json"
                },
                {
                        "fileMatch": [
                                "/tsconfig.json"
                        ],
                        "url": "file:///C:/Users/user/Downloads/schemas/tsconfig.json"
                },
                {
                        "fileMatch": [
                                "/tslint.json"
                        ],
                        "url": "file:///C:/Users/user/Downloads/schemas/tslint.json"
                }
        ]

Update: the schema does get imported, however it still tries to download it and raises "problems" for those files that the schema applies to.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz (4 x 2100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|10.00GB (4.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
ng-template|Ang|0.802.3
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|1.9.1
FreeMarker|dco|0.0.9
githistory|don|0.4.6
gitlens|eam|10.1.1
EditorConfig|Edi|0.13.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
seito-openfile|Fr4|1.8.5
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
icon-fonts|idl|2.2.2
l13-diff|L13|0.21.0
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1056
debugger-for-chrome|msj|4.12.1
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
java|red|0.52.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.7.18
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Forlini91** [comment]
You don't need to type "file://" and the path must be relative to the project folder
Example, if folder "schema" is in the project root folder:
```
{
    "fileMatch": [
            "/tslint.json"
    ],
    "url": "./schemas/tslint.json"
}
```

**Comment by TheBeardedLlama** [comment]
Hey @Forlini91 what you're referring to is another way to reference schemas.
I'm specifically referring to file URLs, which is different to the relative path method that you're describing.

**Comment by aeschli** [comment]
We currently only support relative paths as shown here:
https://code.visualstudio.com/docs/languages/json#_mapping-to-a-schema-in-the-workspace

**Comment by TheBeardedLlama** [comment]
I'm sorry @aeschli but you do support them and I'm surprised you don't know this already. It's even mentioned in other tickets (that's where I got the idea from).

Please read my report above again and carefully.

I'm not saying it's not working.

I'm saying that even though the schema is loaded from the file, it still tries to go over the wire and throws an error because it can't. If it has the schema loaded already it should not be trying to go over the wire IMHO.

**Comment by aeschli** [comment]
Thanks for your investigations.

**Comment by aeschli** [comment]
To verify:
- in the settings add
```
    "json.trace.server": "messages"
    "json.schemas": [{ "fileMatch": ["foo.json"], "url": "file:///not/here" }]
```
- create a file 'foo.json'
- verify that the file has warning 'Unable to load schema...`
- verify that `Log (JSON Language Server) has no message `vscode/content`
