### ISSUE TITLE
Launch configurations doesn't listen for changes in code-workspace file

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83523]
Testing https://github.com/microsoft/vscode/issues/83065

I added some launch configurations in a the code-workspace file for my workspace. The changes didn't show up in the Debug dropdown until after I reloaded.

**Comment by isidorn** [comment]
This works fine for me with the latest on macOS. Please let me know if you are doing something differently.
If you can still repro can you please put a breakpoint [here](https://github.com/Microsoft/vscode/blob/a1f97981859d42036236fcdf010ffcd08bc97038/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L294) and let me know if the breakpoint gets hit. If not, then there is some missing file event and the Configuration service is to blame. Thanks

![workspaceConfig](https://user-images.githubusercontent.com/1926584/69965607-edb7db00-1514-11ea-902a-6f8fd0649d63.gif)

**Comment by alexr00** [comment]
The breakpoint is hit but the issue still happens. It only seems to happen when I have just created the workspace file:
- Open a folder
- Have a launch.json with something in it so the new debug getting started view is gone
- Save workspace as
- Add a launch configuration in the .code-workspace file
- The break point gets hit after saving the file
- The drop down still doesn't update with the new workspace configuration.

**Comment by isidorn** [comment]
Good steps, thanks.
