### ISSUE TITLE
`launch` in code-workspace file requires `configurations` 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83525]
Testing https://github.com/microsoft/vscode/issues/83065

I created a code-workspace file for the vscode repo and added:
```jsonc
        "tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "My Task",
				"type": "shell",
				"command": "npm",
				"args": [
					"run",
					"compile"
				],
				"problemMatcher": []
			}
		]
	},
	"launch": {
		"configurations": [], // This line appears to be required
		"compounds": [
			{
				"name": "TEST IT",
				"configurations": [
					"Launch VS Code",
					"Attach to Main Process"
				],
				"preLaunchTask": "My Task"
			},
		]
	}
```
The line with the comment appears to be required but that's not clear.

**Comment by alexr00** [comment]
Also, that compound doesn't work. The prelaunchtask works, then the launch configurations try to start. However, they don't appear to be able to connect.

**Comment by isidorn** [comment]
@alexr00 good catch. I have pushed a fix that the launch gets detected even if you do not have `configurations` specified. 
As for the compoound not working can you create a follow up issue if that is needed? Thanks!
