### ISSUE TITLE
Outline cap message doesn't make sense

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83526]
re https://github.com/microsoft/vscode/issues/80691

* open JSON-file from https://github.com/microsoft/vscode/issues/80691
* a message shows that outline is capped at 5000
* open quick outline
* :bug: it has 3472 symbols

<img width="844" alt="Screenshot 2019-10-29 at 11 41 05" src="https://user-images.githubusercontent.com/1794099/67760266-4b05cb80-fa41-11e9-9b07-a05334a3ad25.png">

**Comment by aeschli** [comment]
Seems to be fixed by my latest fixes to the JSON language service
