### ISSUE TITLE
Tab suffix (deleted) stays when file is resurrected

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#83529]
Issue Type: <b>Bug</b>

The usage scenario is as follows:

1. Work on `git` branch where a file is present. Keep this file open in VS Code.
2. Switch to another branch where the file does not exist. The tab is appended with the `(deleted)` suffix.
3. Switch back to the first branch. The (deleted) suffix will stay, even though the file is now present.

Here is an example of what it looks like (internal project so most of the content is obscured):

![image](https://user-images.githubusercontent.com/630613/67763575-b30fde00-fa50-11e9-849e-25ab8893af20.png)

VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:30:33.955Z)
OS version: Linux x64 4.19.0-6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2676)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.93GB (2.57GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|19%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-json|and|1.5.0
haproxy|bma|0.1.2
better-toml|bun|0.3.2
solargraph|cas|0.21.1
vscode-modelines|chr|2.0.4
systemd-unit-file|coo|1.0.5
gitlens|eam|10.1.1
beautify|Hoo|1.5.0
mysql-syntax|jak|1.3.1
puppet-vscode|jpo|0.21.0
restructuredtext|lex|114.0.0
VS-code-vagrantfile|mar|0.0.7
code-beautifier|mic|2.3.3
xml-format|mik|1.0.2
binary-viewer|mom|0.0.1
vscode-docker|ms-|0.8.1
python|ms-|2019.10.44104
remote-ssh-edit|ms-|0.47.2
cpptools|ms-|0.26.1
Go|ms-|0.11.7
color-highlight|nau|2.3.0
vetur|oct|0.22.6
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
jinjahtml|sam|0.10.6
scala|sca|0.3.8
vscode-nginx|sha|0.6.0
rewrap|stk|1.9.1
code-spell-checker|str|1.7.18
code-spell-checker-swedish|str|0.1.1
vcl|tho|0.1.2
selectline-statusbar|tom|0.0.2
vscode-icons|vsc|9.5.0
vscode-ansible|vsc|0.5.2
vscode-wakatime|Wak|2.2.1
vscode-proto3|zxh|0.3.0

(4 theme extensions excluded)

</details>

**Comment by perlun** [comment]
(Btw, if I close this tab and reopen the file the `(deleted)` suffix goes away. That's the current workaround for this bug.)

**Comment by gjsjohnmurray** [comment]
@isidorn maybe similar to #82964

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by perlun** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Sure. This is the behavior in 1.40.0-insider now (version details below). After switching to a branch where files are gone, it looks like this. Note how the `README.md` tab lacks the `(deleted)` suffix, but if I hover it, it's correctly displayed.

![image](https://user-images.githubusercontent.com/630613/67954701-0d986e00-fbfa-11e9-84c4-c5e4cb1ea8e8.png)

Switching back to the branch where these files exist, it looks like this:

![image](https://user-images.githubusercontent.com/630613/67954846-489aa180-fbfa-11e9-9285-b91d9af464e2.png)

Hovering over these tabs also display the correct values.

I retried the exact same process with VSCode non-insiders, but unfortunately it behaved the same there. I wonder if there are some other circumstances around the branch switching/specific tab being open that might affect this...

----

Version: 1.40.0-insider
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T06:28:32.160Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.0-6-amd64

**Comment by bpasero** [comment]
It is possible that we have missing file events here. If the tab does not detect the file was restored, it would not be able to update its suffix. Can you run "code --verbose" and check the chrome dev tools console for file watcher output to see if the file is included?

**Comment by perlun** [comment]
@bpasero Thanks. Restarted vscode now with the `--verbose` flag and will keep it running like that for a while until I see the problem the next time.

One immediate thing I noticed when switching branches (note: not yet reproducing the bug) was messages like this being logged (file names edited for privacy & security). Potentially related to the same root cause?

```
[22047:1105/101435.172350:INFO:CONSOLE(4350)] "File exists even though we received a delete event: file:///home/per/some/project/roles/foo/templates/systemd/foo.service", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4350)
[22047:1105/101435.172394:INFO:CONSOLE(4350)] "File exists even though we received a delete event: file:///home/per/some/project/roles/foo/files/bar.py", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4350)
[22047:1105/101435.172431:INFO:CONSOLE(4350)] "File exists even though we received a delete event: file:///home/per/some/project/roles/foo/templates/bin/baz.sh", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4350)
[22047:1105/101435.172452:INFO:CONSOLE(4350)] "File exists even though we received a delete event: file:///home/per/some/project/roles/foo/tasks/main.yml", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4350)
[22047:1105/101435.172477:INFO:CONSOLE(4350)] "File exists even though we received a delete event: file:///home/per/some/project/roles/foo/templates/etc/foo.yaml.j2", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (4350)
```

**Comment by bpasero** [comment]
Yeah, we have some logic in place for the case of a sudden delete with a sudden recreate of a file. We wait for 100ms after receiving a file delete event and then check if the file came back meanwhile before really declaring the file as deleted.

**Comment by perlun** [comment]
OK, I see. This is likely to be timing related/intermittent in nature. I just tested a branch switch (to a branch that doesn't contain a particular file) and the VS Code icon/label in the task bar (Cinnamon in my case) reacted to this event. Switching back to the branch where it existed removed the "deleted" part of the label as it ought to.

Nonetheless, I'll keep you posted if/when I'm able to nail this down again.

**Comment by bpasero** [comment]
Ok

**Comment by perlun** [comment]
@bpasero Managed to reproduce it now, again by switching branches in the `git` repo I am working with. Unfortunately, no file events got logged into the terminal this time. :cry: 

(It might be that this is more easily reproduced if the tab in question is not the _active_ tab, but another file happens to be opened.)
