### ISSUE TITLE
add a option "current" for "editor.lineNumbers"

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode#83528]
We have the following options for "editor.lineNumbers":

> on
> off
> interval
> relative

Example of interval:
<img width="464" alt="Screen Shot 2019-10-29 at 12 02 56" src="https://user-images.githubusercontent.com/738650/67761696-1f381500-fa44-11e9-8c82-9883bf79e412.png">

I would really like a option where it only shows the current line number (almost like interval without the interval).

**Comment by usernamehw** [comment]
```js
"workbench.colorCustomizations": {
    "editorLineNumber.foreground": "#fff0",
}
```

**Comment by clankill3r** [comment]
Thanks, that works great.
Although I think it still would be valuable to have as an option.

Also why does this not clear the current line color?

Op di 29 okt. 2019 om 14:29 schreef Alexander <notifications@github.com>:

**Comment by usernamehw** [comment]
Current line uses another color: `editorLineNumber.activeForeground`.

**Comment by clankill3r** [comment]
Whenever I switch a tab, my line numbers disappear. Even if I remove your code snippet.

This is when I set it:
<img width="279" alt="Screen Shot 2019-10-29 at 19 57 28" src="https://user-images.githubusercontent.com/738650/67799870-7fe84180-fa86-11e9-9f79-a77273bc557d.png">

This is when I change a tab and come back.
<img width="276" alt="Screen Shot 2019-10-29 at 19 57 36" src="https://user-images.githubusercontent.com/738650/67799877-837bc880-fa86-11e9-89d9-4b62e2788aad.png">

Restarting vscode has no effect. I have no settings in the workspace settings related to lines or whatever (only folder paths).

**Comment by clankill3r** [comment]
I got it:

`"zenMode.hideLineNumbers": false`

**Comment by clankill3r** [comment]
The hacky `"editorLineNumber.foreground": "#fff0",` solution stopped working.
I think it happened since the latest VSCode release.
Here is my whole user config:

https://pastebin.com/VQuVqkLn

**Comment by isidorn** [comment]
Ok, so the zenMode setting you figured out
The general editor feature request is still valid, thus I am leaving it open
fyi @rebornix

**Comment by clankill3r** [comment]
@isidorn can you confirm that `"editorLineNumber.activeForeground"` is currently broken in vscode? Cause I think it is.

**Comment by isidorn** [comment]
Might be broken, you can file a new issue for that please. Thanks

**Comment by clankill3r** [comment]
Someone beat me to it:
https://github.com/microsoft/vscode/issues/84772

**Comment by isidorn** [comment]
Accidently closed, reopening
