### ISSUE TITLE
Source control tree-view mode collapse on source-control action

### ISSUE THREAD

**Issue by itamar-dw** [microsoft/vscode#83527]
Issue Type: <b>Bug</b>

When I manually un-collapse all folders in the source control view and make some change, for example commit a modified file, the view collapse all folders again which makes the view too packed (tons of unversioned files in unversioned folders)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2986)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.48GB (0.90GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vsc-material-theme|Equ|30.0.0
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
cpptools|ms-|0.26.1
autodocstring|njp|0.3.0
vscode-ipython|pan|0.5.0
vscode-hexdump|sle|1.7.2
vim|vsc|1.11.3

(3 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/82346
