### ISSUE TITLE
Web: "Download" on Explorer background

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#83521]
Testing #83137

Doesn't do anything:

![image](https://user-images.githubusercontent.com/9205389/67758315-c1083380-fa3d-11e9-9a9c-49b45eea1ab5.png)

Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by bpasero** [comment]
@isidorn need more context key cleverness from you here 👍

**Comment by isidorn** [comment]
Haha, no problem
