### ISSUE TITLE
macOS Catalina: Insiders UI frozen working with SMB files

### ISSUE THREAD

**Issue by andig** [microsoft/vscode#83530]
Version
```
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:46:37.742Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

Steps to Reproduce:

1. Start Insiders and open file from SMB share
2. Sooner or later, Insiders UI will freeze

Checking with "activity monitor" shows that Insiders is still responsive but doesn't take any user input.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by andig** [comment]
Closing until I can provide better details/ steps to reproduce.
