### ISSUE TITLE
'${file}' can not be resolved. Please open an editor

### ISSUE THREAD

**Issue by UGuntupalli** [microsoft/vscode#83533]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1.Install Anaconda (conda version - 4.7.12, python version: 3.7.4.final.0) 
2.Create an anaconda environment
  a. Add jupyter to the environment 
3.Install VS Code 
4.Launch VS Code from the conda environment 
5.Configure launch.json, settings.json and .env 
6. Open a new folder under the project 
   a. Add a jupyter notebook file 
7. Debug (F5) the notebook file 

![image](https://user-images.githubusercontent.com/47903157/67766269-50482380-fa0b-11e9-885c-f144629cbc3c.png)

Does this issue occur when all extensions are disabled?: No

Since Jupyter is an extension, i was not expecting this to work/ the error to occur. Here is the result of launching code by disabling extensions 
![image](https://user-images.githubusercontent.com/47903157/67766343-75d52d00-fa0b-11e9-804b-e80518ccbe9e.png)

**Comment by mjbvz** [comment]
Please start by filing this against the python extension
