### ISSUE TITLE
Files not showing on explorer panel

### ISSUE THREAD

**Issue by themzed** [microsoft/vscode#83536]
- VSCode Version: 1.39.2
- OS Version: macOS Mojave 10.14.6

When I clone a repo with 'git clone repo-url' folder not showing on directory and I should restart VSCode to solve this.

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
