### ISSUE TITLE
Theme dropdown should be re-placed appropriately

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8353]
#8229
Safari

In https://microsoft.github.io/monaco-editor/index.html 

There are two sections, 1.Editor and 2.Diff Editor
First section has two dropdown - Language and Theme
Language dropdown applies only to Editor where as Theme applies to both sections.

May be we should re-place themes dropdown at a place where it is known to be applied for both sections

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#140

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
