### ISSUE TITLE
Should editor.suggest.filteredTypes have a deprecated message

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#83537]
- VSCode Version: 1.40 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Bring over editor.suggest.filteredTypes from 1.39 settings and paste into 1.40 settings.json

editor.suggest.filteredTypes just shows faded with "Unknown Configuration Setting" hover.

Should we add a deprecated message something like "This setting is deprecated, please use 'editor.suggest.filterTypes.*' instead.". It would also be good if there was a warning squiggle in settings.json.

**Comment by jrieken** [comment]
I am afraid that's not possible or at least I don't know how to proceed here... I will check with @sandy081 or @aeschli

**Comment by gregvanl** [comment]
Looking at `workbench.tree.horizontalScrolling` as an example, I think you leave the old setting and add a `deprecationMessage`.

**Comment by jrieken** [comment]
Thanks @gregvanl

**Comment by jrieken** [comment]
Adding the definition of that property caused a meltdown... The problem is that the old setting is a prefix of the new settings and our config model doesn't like that much.

**Comment by jrieken** [comment]
The plan to rename these settings to `editor.suggest.showXYZ`. That avoid the conflict and help with clarity
