### ISSUE TITLE
git svc show that all files are uncommited in wsl

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#83540]
- VSCode Version: 1.39.2
- OS Version: windows x64 1909
- WSL:ubuntu

I clone a git repo form github wthin windows_git, and than I open this folder in vscode-remote  on WSL, git svc shows that all files are nucommited;
![Snipaste_2019-10-29_22-02-24](https://user-images.githubusercontent.com/1876302/67774669-c5156f00-fa98-11e9-949c-f5cc288d99c4.png)

**Comment by joaomoreno** [comment]
Do things work if you clone from within WSL?

**Comment by heartacker** [comment]
> Do things work if you clone from within WSL?

ok, I clone a repo in wsl, and it works well using vscode-remote

**Comment by joaomoreno** [comment]
Alright, closing it then. That's the recommended way to do things.
