### ISSUE TITLE
HLSL numeric syntax highlight wrong/incomplete

### ISSUE THREAD

**Issue by Jlkam** [microsoft/vscode#83549]
Issue Type: <b>Bug</b>

Number like 0.0f will only be colorized to the first dot.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/tgjones/shaders-tmLanguage/issues/2
