### ISSUE TITLE
Task detail configure gear misaligned

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83542]
Testing #83436

Minor UI bug, but it appears that the gear to configure a task (in a detail task) is not on the same line as the single line tasks:

![image](https://user-images.githubusercontent.com/35271042/67776643-d5d4cf00-fa1d-11e9-8bce-ee4cbf6e24a7.png)

**Comment by alexr00** [comment]
@chrmarti is the icon alignment something we would want to change for all quick picks with inline buttons?

**Comment by misolori** [comment]
Btw, I realized that this icon is not using the icon font, so you can easily update the class of the gear to include `codicon-gear` and it will auto-align:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/35271042/67778579-9e1b5680-fa20-11e9-86e3-5198cc083225.png">

**Comment by chrmarti** [comment]
Yes, this should be consistent for all QuickPicks.

**Comment by alexr00** [comment]
@misolori very cool and very easy! I incorrectly assumed it would need a quick pick change.
