### ISSUE TITLE
program location only shown for active session

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#83543]
Testing #83065:

- create two simple node.js programs that just loop, e.g.:
  ```js
  let i = 0;
  setInterval(_ => {
	console.log("hello " + i++);
  }, 500);
  ```
- create two launch configs based on the two programs
- in both programs set a breakpoint on the line with "console.log"
- start two debug session 
- open the source code of the two programs in two editor tabs

Observe: both programs are paused but only one editor shows the program location with a yellow line (the program of the active debug session). When switching to the editor tab, no yellow line is shown in that editor because the editor contains the source of the non-active debug session.

This is unexpected and confusing.
I suggest that we show all program locations (but with different intensities).

**Comment by isidorn** [comment]
I agree. However not for endgame. Pushing out to next Milestone.

**Comment by isidorn** [comment]
This is done via https://github.com/microsoft/vscode/commit/cd5784cc271107281c71484be8ad40955b2fe6f0
