### ISSUE TITLE
Test: default node internals in skipFiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#83546]
Refs: https://github.com/microsoft/vscode/issues/69959

 - [x] any os @RMacfarlane
 - [x] Windows @eamodio

Complexity: 3

1. Run the following command in an empty folder, then open that folder in VS Code

   ```
   echo '{"main":"foo.js"}' > package.json && echo "debugger; require('fs').readFileSync('package.json');" > foo.js
   ```
 2. F5 and choose the "Node.js" debugging type.
 3. The process should boot and you should hit a breakpoint. Repeatedly "Step Into". You should *not* step into the `require` or `readFileSync` functions.
 4. Create a new Node.js launch config using the configured snippets. `"skipFiles": ["<node_internals>/**"]` should be set for you.
 5. Run the process using the launch config, and repeat step 3.
 6. Remove `skipFiles` from your launch config. You should now be able to step into the require and readFileSync functions.

**Comment by eamodio** [comment]
All of those steps look good. Although when I removed the `skipFiles` to step into the different calls, `F10` (step over) isn't behaving as I'd expect. `F11` (step into) seems to work fine.

1. Using the launch config in # 4 above, start debugging
1. When it breaks, hit `F10`, which will step over the debugger call 👍 
1. `F10` again, but this time it steps over the `require` call AND also the `readFileSync` call :bug:
  I would expect it to just step over the `require` call and allow me to step into the `readFileSync` call if I wanted
1. `F10` again, here I would expect the debugging session to end, but instead I end up inside `loader.js` -- this may be desired, but I found it unexpected (at the same time, if I pressed `F11` then I think this behavior is good -- which is what happens too)

**Comment by connor4312** [comment]
`require('fs').readFileSync('package.json');` is a single statement, I believe it's intended that F10 steps at a statement level. E.g. running this in vs code or Chrome, even though it contains many different expressions, is stepped over as a single statement.

```js
const getter = () => ({ getFoo(obj) { return obj.foo } });
const getBar = () => 'bar';

debugger;
const result = getter().getFoo({ foo: getBar() });
console.log(result);
```

![Kapture 2019-10-29 at 13 46 47](https://user-images.githubusercontent.com/2230985/67807723-996f9600-fa52-11e9-9b3c-368e05fc53ae.gif)

**Comment by eamodio** [comment]
Hrm, OK -- thanks for the info. Is # 4 an issue or also expected?

**Comment by connor4312** [comment]
I'm not sure actually. I can reproduce it on stable, so it's probably not related to this changeset, but we may want to open an issue on it or target it for a fix in PWA. @roblourens thoughts?

![Kapture 2019-10-29 at 14 02 19](https://user-images.githubusercontent.com/2230985/67808869-c7ee7080-fa54-11e9-8fbe-3a4a45442570.gif)

**Comment by roblourens** [comment]
This is by design, you are just stepping back up the stack to loader.js. If you set skipFiles to skip node_internals files, then it will not stop there, that's what that feature is for.
