### ISSUE TITLE
Updating task name and detail don't auto-update

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83545]
Testing #83436

Steps
1. Open a `tasks.json` file
2. Edit the name or detail fields and save
3. Run the "Run Task" command
4. :bug: the name/detail fields have not updated their strings

This doesn't happen on stable when you update the task name. This also requires a full reload of the window in order to get them to update. I'd expect them to be updated automatically.

**Comment by alexr00** [comment]
@misolori I think you might just seeing the 1 second delay I added from https://github.com/microsoft/vscode/issues/82623
If you save then wait just over a second does it work?

**Comment by misolori** [comment]
@alexr00 yes, after waiting for 1 sec the label does get updated.
