### ISSUE TITLE
Test: minimap scale

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#83544]
Refs: https://github.com/microsoft/vscode/issues/21773

- [x] any os @jrieken
 - [x] any os @alexr00

 1. In VS Code, turn on the minimap (`"editor.minimap.enabled": true`)
 2. Verify that the minimap renders and lays out correctly, and at various scales (`editor.minimap.scale` with values 1, 2, and 3). 
 3. Turn the minimap into block rendering mode `"editor.minimap.renderCharacters": false` and do the same

**Comment by alexr00** [comment]
Tested on Windows. Looks good!

**Comment by jrieken** [comment]
looking good on mac
