### ISSUE TITLE
Missing JavaScript syntax highlight in HTML

### ISSUE THREAD

**Issue by Provice911** [microsoft/vscode#83541]
After last update (~29.10.2019) JavaScript syntax not highlight in HTML between tags <script> (InteliSense yet works)
_UPD: Issue has only on VSCode Insider_
![image](https://user-images.githubusercontent.com/22263818/67776649-a8197580-fa71-11e9-8363-0cdce3d02683.png)

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>History Random Date Selector</title>
</head>

<body>


    <script>

        function shuffle() {
            $("#text").text('');
            // var arrOneDate = ['862-879', '882', '988', '1019-1054', '1116', '1147', '1223', '1237-1240', '1240', '1242', '1380', '1425-1462', '1462-1505', '1497', '1530-1584', '1550', '1565-1572', '1598-1613', '1610-1612', '4 ноя. 1612'];

            // var arrTwoDate = ['1613-1645', '1645-1676', '1649', '1672-1725', '1700-1721', '1709', '1714', '1720', '1725-1762', '1762-1796'];

            var arrOne = [
                // 'Княжение Рюрика в Новгороде', 'Объединение Руси по властью Олега, образование Киевской Руси', 'Крещение Руси (Владимир)', 'Правление Ярослава Мудрого', 'Летопись "Повесть Временных лет"', '1-ое упоминание Москвы (Долгорукий)', 'Битва на р. Калка', 'Походы Батыя на Русь', 'Невская битва', 'Ледовое побоище', 'Куликовская битва', 'Княжение Василия II-Тёмного', 'Княжение Ивана III', 'Судебник Ивана III', 'Годы жизни Ивана Грозного', 'Судебник Ивана Грозного', 'Период опричнины', 'Смутное время', 'Окупация Москвы польскими войсками', 'Освобождение Москвы от интервентов'
            ];

            var arrTwo = ['Период царствования Михаила Романова', 'Царствование Алексея Михайловича', 'Соборное уложение Алексея Михайловича', 'Годы жизни Петра I', 'Северная война'/*, 'Полтавская битва', 'Победа русского флота при мысе Гангут', 'Победа русского флота у о. Гернгам', 'Дворцовые перевороты', 'Царствование Екатеринаы II'*/];

            console.log(arrOne.length);
            console.log(arrTwo.length);




            var arr = arrOne.concat(arrTwo);

            console.log(arr.length);

            var j, temp;
            for (var i = arr.length - 1; i >= 0; i--) {
                console.log(i);
                
                j = Math.floor(Math.random() * (i + 1));
                temp = arr[j];
                arr[j] = arr[i];
                arr[i] = temp;
                // document.write(arr[i] + "<br>");
                $("#text").append(arr[i] + "<br><br>");
            }
            // return arr;
            // document.write(arr);
        }
    // shuffle();
    </script>

    <input type="button" onclick="shuffle()" value="press for date">
    <br>
    <br>
    <br>
    <div id="text">

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</body>

</html>
```

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by alexr00** [comment]
Also, does this reproduce if you disable all extensions?

**Comment by Provice911** [comment]
> Please share the text of the code along with screenshots

Just a random selector of events Russian history from array. Private use

`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>History Random Date Selector</title>
</head>

<body>


    <script>

        function shuffle() {
            $("#text").text('');
            // var arrOneDate = ['862-879', '882', '988', '1019-1054', '1116', '1147', '1223', '1237-1240', '1240', '1242', '1380', '1425-1462', '1462-1505', '1497', '1530-1584', '1550', '1565-1572', '1598-1613', '1610-1612', '4 ноя. 1612'];

            // var arrTwoDate = ['1613-1645', '1645-1676', '1649', '1672-1725', '1700-1721', '1709', '1714', '1720', '1725-1762', '1762-1796'];

            var arrOne = [
                // 'Княжение Рюрика в Новгороде', 'Объединение Руси по властью Олега, образование Киевской Руси', 'Крещение Руси (Владимир)', 'Правление Ярослава Мудрого', 'Летопись "Повесть Временных лет"', '1-ое упоминание Москвы (Долгорукий)', 'Битва на р. Калка', 'Походы Батыя на Русь', 'Невская битва', 'Ледовое побоище', 'Куликовская битва', 'Княжение Василия II-Тёмного', 'Княжение Ивана III', 'Судебник Ивана III', 'Годы жизни Ивана Грозного', 'Судебник Ивана Грозного', 'Период опричнины', 'Смутное время', 'Окупация Москвы польскими войсками', 'Освобождение Москвы от интервентов'
            ];

            var arrTwo = ['Период царствования Михаила Романова', 'Царствование Алексея Михайловича', 'Соборное уложение Алексея Михайловича', 'Годы жизни Петра I', 'Северная война'/*, 'Полтавская битва', 'Победа русского флота при мысе Гангут', 'Победа русского флота у о. Гернгам', 'Дворцовые перевороты', 'Царствование Екатеринаы II'*/];

            console.log(arrOne.length);
            console.log(arrTwo.length);




            var arr = arrOne.concat(arrTwo);

            console.log(arr.length);

            var j, temp;
            for (var i = arr.length - 1; i >= 0; i--) {
                console.log(i);
                
                j = Math.floor(Math.random() * (i + 1));
                temp = arr[j];
                arr[j] = arr[i];
                arr[i] = temp;
                // document.write(arr[i] + "<br>");
                $("#text").append(arr[i] + "<br><br>");
            }
            // return arr;
            // document.write(arr);
        }
    // shuffle();
    </script>

    <input type="button" onclick="shuffle()" value="press for date">
    <br>
    <br>
    <br>
    <div id="text">

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</body>

</html>`

**Comment by Provice911** [comment]
> Also, does this reproduce if you disable all extensions?

By disabling all extensions nothing happened. But accidentally, when touching extension which has affect on editor, syntax highlight can randomly turning on. After restarting Visual Code syntax highlight again disappeared

**Comment by alexr00** [comment]
Looks like this is extension related then. I can't reproduce with the example. Did you reload after disabling the extensions so that the disable took effect?

**Comment by Provice911** [comment]
> Looks like this is extension related then. I can't reproduce with the example. Did you reload after disabling the extensions so that the disable took effect?

Yes, I disable all extentions nad reload. No JS syntax in HTML

**Comment by Provice911** [comment]
> Looks like this is extension related then. I can't reproduce with the example. Did you reload after disabling the extensions so that the disable took effect?

Also I forgot notice, that issue caused only on VSCode Insider version. Sorry

**Comment by dragz** [comment]
I have the same issue with the latest Insiders. See screenshot with VS Code Insiders to the left and VS Code to the right. Both are reloaded with extensions disabled. 

The code is trivial.

![image](https://user-images.githubusercontent.com/2721495/68252521-0e7c3600-0026-11ea-89ec-8ba55a5a685a.png)

**Comment by alexr00** [comment]
simple copy pastable example:
```html
<html>
	<body>
		<h1>testing</h1>
		Just a hightlight test.
		<script>
			const avar = 1.0;
		</script>
	</body>
</html>
```
Issue only occurs when you don't first open a ts/js file. Simple exact steps:
1. Open VS Code
2. Close all files
3. Reload 
4. Open or create a file with the above html and set the language to html for it

@mjbvz could this be related to the injection work you've done?
