### ISSUE TITLE
Clonar repositorio Git

### ISSUE THREAD

**Issue by Alberto5577** [microsoft/vscode#83547]
Issue Type: <b>Bug</b>

Command git.clone was not found

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-8650 Radeon R7, 10 Compute Cores 4C+6G   (4 x 3194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (2.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
compulim-vscode-closetag|Com|1.2.0
vscode-language-pack-es|MS-|1.39.3
material-icon-theme|PKi|3.9.1
pdf|tom|0.5.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Is Git installed?

From https://code.visualstudio.com/docs/editor/versioncontrol
![image](https://user-images.githubusercontent.com/6726799/67781945-08072080-fa60-11e9-952b-af56d0b63c6e.png)

That link is to https://git-scm.com/download

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate this
