### ISSUE TITLE
Test Web: Some shortcut doesn't work in terminal

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83559]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

For example, Ctrl+B work when focused into editor but not terminal.

![toggle sidebar](https://user-images.githubusercontent.com/4033249/67792070-c2356280-fa35-11e9-8a73-afde531b9399.gif)

**Comment by bpasero** [comment]
@octref can you try when doing View > Appearance > Fullscreen? A ton of keybindings will only work in fullscreen or PWA mode.

**Comment by octref** [comment]
Confirmed it doesn't work in terminal, even in fullscreen mode.

**Comment by rebornix** [comment]
As we discussed yesterday during standup, `Ctrl+B` is received by Terminal and if you don't want that from happening, you can whitelist it by `terminal.integrated.commandsToSkipShell`. You don't see this issue on macOS as `Cmd+B` is not handled the same as `Ctrl+B`. @Tyriar can confirm.
