### ISSUE TITLE
Notification: Should not reflow text when hovering

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83555]
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:46:37.742Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

![reflow](https://user-images.githubusercontent.com/4033249/67790556-33bfe180-fa33-11e9-8758-2ee95b33f155.gif)

IMO they should be have like a floating overlay that's shown when hovering, but not actually squeeze out the text.

Steps to Reproduce:

1. Have a notification longer than 1 line
2. Hover over it

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I am not convinced, there is a mode where actions will appear, e.g. when focus is inside the notification:

![image](https://user-images.githubusercontent.com/900690/67793115-91c3e780-fa7a-11e9-8ddd-9eae962ab9bf.png)

In that case wouldn't you still want to be able to read the text?

**Comment by octref** [comment]
I hope the actions can be a small button group floating above the message (maybe half-transparent), not "inserted" into the text flow. Something like Slack:

![message-overflow](https://user-images.githubusercontent.com/4033249/67798311-7f2cbc80-fa40-11e9-8a57-1a81cc9f833c.gif)

I know this doesn't apply 1-1 to our case, when we don't have the name line and extra space on top, but I assume if you are hovering over there, you have already consumed the text and are looking for actions. Hovering-then-reflowing the text makes me feel I need to reread it again.

**Comment by bpasero** [comment]
I am not sure this works well. We need to have a mode where actions are not showing up on hover for accessibility reasons. I think I would not want to change the design at the moment.

**Comment by misolori** [comment]
I'd be ok if we reverted the change to only shoe actions on hover/focus as it feels worse to have the text jump or have a big gap.

**Comment by bpasero** [comment]
@misolori I believe [this change](https://github.com/microsoft/vscode/commit/4a0295161abeb5b6e1f179a9edc22258c2ee08b2) was the only thing that we changed, please check.
