### ISSUE TITLE
High Contast Dark theme looks fuzzy 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8355]
#8229 
Safari

Change the theme to High Contrast and text looks fuzzy

![high contrast](https://cloud.githubusercontent.com/assets/10746682/16416672/a8bba628-3d43-11e6-8b57-63aa1a276f62.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#141

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
