### ISSUE TITLE
Web: select dropdown widgets are not themed and look out of place

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83556]
Testing #83296:

They feel like the only thing not being themed in the whole workspace...

Web:

![image](https://user-images.githubusercontent.com/4033249/67790972-e85a0300-fa33-11e9-979a-c8afdd910446.png)

In some state, it looks like a hole on a smooth surface...

![image](https://user-images.githubusercontent.com/4033249/67791142-30792580-fa34-11e9-8988-31c2f7eef1aa.png)

Insiders:

![image](https://user-images.githubusercontent.com/4033249/67790939-de380480-fa33-11e9-85bf-e07436f82599.png)

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

**Comment by misolori** [comment]
Is there any way to use our custom styling, like on Windows? I agree that we should at the very least make it look better for the worse ones.

Also, Safari's dropdown selector is bad but their list picker is fine:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/35271042/67795062-f65f5200-fa3a-11e9-80c5-6956c9ad473d.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/35271042/67795075-f9f2d900-fa3a-11e9-9f96-a0ff30cdf08d.png">

**Comment by bpasero** [comment]
@misolori as far as I know, we do not style the widget itself, only the dropdown list when expanded. Yes, we can enable that for Safari and FF, but I think this issue is more about the widget when it is collapsed.

**Comment by bpasero** [comment]
I found no other way than changing the appearance of the dropdown to be of type button. This unfortunately removes the arrow (which we could possibly add back somehow), but makes it look nice and flat. I do not think there is a way to theme the arrow within the dropdown.

**Before:**
![image](https://user-images.githubusercontent.com/900690/67937138-4ec65900-fbcd-11e9-8be9-835d7a53c105.png)

**After:**
![image](https://user-images.githubusercontent.com/900690/67937158-5554d080-fbcd-11e9-9902-529a4b5b7a5c.png)

**Comment by alexr00** [comment]
Verified from source.

**Comment by misolori** [comment]
@bpasero do we set any css properties for FF/Safari? We could embed a chevron via the `content` property for those browsers, like `content: "\f11e"`. It's not the prettiest but it's also the fewest amounts of code and we already do this with the list decorations (git dot).

**Comment by bpasero** [comment]
@misolori sounds good to me, if you want to give it a try, fire up a PR and I can review + merge tomorrow.
