### ISSUE TITLE
tracing visible in command window where vscode was launched

### ISSUE THREAD

**Issue by emanpal** [microsoft/vscode#83552]
I launch an .xml file from the command prompt.
Visual Studio Code starts, as expected.
What's not expected is the tracing that in leaves in the command window, such as
C:\$WINDOWS.~BT\Sources>uninstall_data.xml

C:\$WINDOWS.~BT\Sources>
 [main 2019-10-29T16:34:02.726Z] update#setState idle
[main 2019-10-29T16:34:32.728Z] update#setState checking for updates
[main 2019-10-29T16:34:32.756Z] update#setState downloading
[main 2019-10-29T16:34:33.583Z] update#setState downloaded

**Comment by joaomoreno** [comment]
Can you show me your `%Path%` variable?
