### ISSUE TITLE
SCM: Support filtering on file paths and contents

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#83550]
I often make a lot of changes at once, and then need to commit them.  Some changes don't belong together in the same commit, and some aren't ready to be committed at all.

The current UI allows me to select some files to be staged for commit and exclude others, but it requires me to carefully select my changes from a potentially very long list.

It would be incredibly useful if I could search or filter files by path pattern and stage/unstage all search results.

Even better would be if I could search for lines of code and either stage files containing those lines or just the matched lines.

This would streamline my git workflow by a lot.

**Comment by joaomoreno** [comment]
Since last month, SCM supports fancy keyboard navigation and filtering. Simply start typing when focused on the view. A widget will appear which you can use to toggle between simple highlighting and filtering. Currently filtering is done only on file names though, not paths or even code.
