### ISSUE TITLE
Web: folder upload no-ops

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#83569]
- VSCode Version: 1.40.0-insider @ b7b21844e760e632f39bedf651da2bc93f54b0cc
- OS Version: OS X Mojave 10.14

Steps to Reproduce:

1. Open a web workspace, try to upload a folder via drag
2. Nothing happens

We should probably either support folder uploads or show an error when the user tries to upload a folder.

Does this issue occur when all extensions are disabled?: Yes

Ref: https://github.com/microsoft/vscode/issues/83225

**Comment by bpasero** [comment]
I am not sure we can detect that a folder is being draggd.
