### ISSUE TITLE
Web: certain special characters in paths are not preserved when downloading

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#83563]
- VSCode Version: 1.40.0-insider @ b7b21844e760e632f39bedf651da2bc93f54b0cc
- OS Version: OS X Mojave 10.14

Steps to Reproduce:

1. Create a file named `weird:file.txt` in your web workspace
2. Download the file
3. Observe its downloaded name is `weird_file.txt`

Does this issue occur when all extensions are disabled?: Yes

Ref: https://github.com/microsoft/vscode/issues/83225

**Comment by bpasero** [comment]
We may not be able to fix this.

**Comment by bpasero** [comment]
I think this is not critical enough to invest. Bottom line, we create a `DownloadURL` transfer type (docs: https://www.html5rocks.com/en/tutorials/casestudies/box_dnd_download/) and that requires us to produce a string that is colon-separated. 

I found no docs on how to escape this, if someone has an idea, feel free to chime in.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/61f36a2346a0e2d621ea26f5a4b3b0db912198ce/src/vs/workbench/browser/dnd.ts#L334
