### ISSUE TITLE
Web: folder downloads fail

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#83567]
- VSCode Version: 1.40.0-insider @ b7b21844e760e632f39bedf651da2bc93f54b0cc
- OS Version: OS X Mojave 10.14 (@eamodio also confirmed on Windows)

Steps to Reproduce:

1. Create a folder in your web workspace
2. Try to drag it to your desktop
3. On OSX, an empty, zero-byte file is created with the folder name. (Eric reports this doesn't happen on Windows.) After some time, Chrome will give you an "network error" in your download. The download doesn't complete.

![image](https://user-images.githubusercontent.com/2230985/67797167-979bd780-fa3e-11e9-8d79-905db0b6f2ce.png)

![image](https://user-images.githubusercontent.com/2230985/67797175-9a96c800-fa3e-11e9-90a3-5894c6201cd7.png)

Does this issue occur when all extensions are disabled?: Yes

Ref: https://github.com/microsoft/vscode/issues/83225

**Comment by bpasero** [comment]
Same for desktop. We should possibly not set the download transfer when a folder is dragged.

**Comment by bpasero** [comment]
I pushed a change to not set `DownloadURL` data type when dragging a folder.
