### ISSUE TITLE
Web: Buttons in notification area are cropped off with enough space

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83573]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

1. Open vscode repo (or any large repo)
2. See the "unable to watch file changes in this large workspace..." message
3. Notice the button is cropped

![image](https://user-images.githubusercontent.com/4033249/67799565-d03db000-fa42-11e9-99f9-5a03db8daaec.png)

**Comment by bpasero** [comment]
Saw this as well in @sbatten custom dialogs. So possibly the fix for buttons would fix this everywhere.

**Comment by joaomoreno** [comment]
Verified in dev.
