### ISSUE TITLE
Web: Number widget in settings GUI look bad

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83572]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

Settings editor - number widget looks bad with the default control on Firefox Linux:

![image](https://user-images.githubusercontent.com/4033249/67799248-41c92e80-fa42-11e9-884f-b73b2c571a52.png)

**Comment by bpasero** [comment]
//cc @misolori similar to the select dropdown issue we have

**Comment by bpasero** [comment]
Since I looked into this from https://github.com/microsoft/vscode/issues/83556 I pushed a change. 

@roblourens please note: https://github.com/microsoft/vscode/commit/b7e9344c5de8d87d92751d9eef867b2a42d5f1c1
