### ISSUE TITLE
[css] classifiy document symbols by id/class/element

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83577]
- VSCode Version: 1.40.0-insider @ b7b2184
- OS Version: Windows 10 (1903)

I would expect that when using _Go to Symbol in File by Category_ the symbols would be grouped by type, `ids`, `classes`, `elements`, `media queries`, etc. While it seems that everything is grouped under a single `classes` group.

![image](https://user-images.githubusercontent.com/641685/67803357-4225f180-fa63-11e9-91d1-2ee8b842f5be.png)

Ref: https://github.com/microsoft/vscode/issues/83020

**Comment by aeschli** [comment]
`classes`comes from the SymbolInformation.kind and we are limited following [kinds](https://github.com/microsoft/vscode/blob/b8b1752036e0dc2017f84ac786033777a4c1c231/src/vs/vscode.d.ts#L2619-L2619)

Implementing that request would require new VSCode and LSP APIs.
