### ISSUE TITLE
Process explorer with OS scrollbars instead of VSCode scrollbars

### ISSUE THREAD

**Issue by Logerfo** [microsoft/vscode#83571]
![image](https://user-images.githubusercontent.com/19306384/67798929-333f3f00-fa63-11e9-9def-3b73f1e27450.png)

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/138020 reports seeing multiple scroll bars:

![image](https://user-images.githubusercontent.com/2193314/143890398-2a42ea59-20c2-4348-b5d5-25fd5bc5f793.png)

**Comment by Tyriar** [comment]
Fixed
