### ISSUE TITLE
Web: support dragging file/files from desktop directly to editors

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83578]
- VSCode Version: 1.40.0-insider @ b7b2184
- OS Version: Windows 10 (1903)

Steps to Reproduce:

1. Drag a file(s) from the desktop into the editor area
2. Expect that new editors would be open for the files dragged in, but nothing happens

If 2 can't happen, I would expect that there would not be drag feedback making it seem like it should work.

Does this issue occur when all extensions are disabled?: Yes

Ref: #83225

**Comment by bpasero** [comment]
Now preventing to drop a local file into editor area as well as "open editors" view if running in web.
