### ISSUE TITLE
Web: Support a Download action on folder context menus in explorer

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83579]
- VSCode Version: 1.40.0-insider @ b7b2184
- OS Version: Windows 10 (1903)

It would be nice to support a _Download_ option for folders in the explorer just like with files.

Ref: #83225

**Comment by bpasero** [comment]
Exploration in https://github.com/microsoft/vscode/compare/ben/chrome-fs-api leveraging new Chrome native fs APIs. 

More context in https://github.com/MicrosoftDocs/vsonline/issues/57#issuecomment-581017834

**Comment by Chuxel** [comment]
@bpasero I think this is starting to become a bit of an issue. Has there been any investigations here?  Rather than using native fs APIs, couldn't we just zip and return a single file?

**Comment by bpasero** [comment]
> Has there been any investigations here

None that lead to a conclusion I would say.

> Rather than using native fs APIs, couldn't we just zip and return a single file?

We would need to use a third party library for this purpose, as there is no built in zip support in node.js for multi-file archives. We already have some usage of such a library in core (I think to extract extensions) so I think it is doable. Probably needs a bit of investigation if we can do it in a clever way that involves streams and not requires all of the files to be compressed in-memory or even to disk.

**Comment by bpasero** [comment]
Leveraging new Chrome/Edge file system access API (https://wicg.github.io/file-system-access/) to support downloading folders or large files.

**Comment by isidorn** [comment]
Very cool 👏
