### ISSUE TITLE
Web: Open Folder shows `/Desktop`even if the path is wrong

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83574]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

After I press Ctrl+K, Ctrl+O, the picker shows path `/home/parallels/` but the options were generated from `/home/parallels/Desktop`:

![image](https://user-images.githubusercontent.com/4033249/67800050-d1231180-fa43-11e9-9d49-9034405171cb.png)

**Comment by alexr00** [comment]
@octref are you still seeing this? I tried it on an Ubuntu based container in Firefox and it worked as expected.

**Comment by octref** [comment]
Fixed in latest for me.
