### ISSUE TITLE
Prefer "enabled"/"disabled" not "true"/"false"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83582]
We should terms like "enabled" and "disabled" in bool setting descriptions because "true" and "false" don't make sense in the settings GUI: 
![image](https://user-images.githubusercontent.com/323878/67807639-71803280-fa52-11e9-9c3c-851255ce4bfb.png)

**Comment by jrieken** [comment]
We need to find a balance between the UI and the JSON editor...
