### ISSUE TITLE
Color picker feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83589]
![image](https://user-images.githubusercontent.com/2193314/67813673-5ec02a80-fa5f-11e9-89e7-4450fe9df863.png)

- The title is not centered
- It wasn't clear to me until reading https://github.com/microsoft/vscode/issues/81890 that the title bar toggled between tgb, hsl and #rrggbb - is there a better way we could imply this?
- Showing the description for `color` inside the color picker doesn't seem useful and makes it kind of ugly with the scroll bar. Shouldn't the description only be while hovering the property, not the value?

**Comment by probablykasper** [comment]
Strongly agree all three points.

Atom's [color-picker](https://atom.io/packages/color-picker) extension shows buttons to toggle between each format (which would be my preference):
![colorpickeratom](https://user-images.githubusercontent.com/11315492/79693761-ec414200-826c-11ea-821d-2d13eb30c1a9.png)

VSCode's [Color Manager](https://marketplace.visualstudio.com/items?itemName=RoyAction.color-manager) extension shows an arrow button to change formats:
![colormanager](https://user-images.githubusercontent.com/11315492/79693810-27437580-826d-11ea-9346-5c80009bda4a.jpg)

**Comment by ghiscoding** [comment]
I also wish to complement it with this issue #33568 that I've opened a long time ago. Which basically says, If I start changing color, I don't the picker to close so easily just because my mouse is no longer hovering the color variable.

**Comment by misolori** [comment]
Pushed a couple of polish tweaks to the color picker:

- There's an icon for higher discoverability
- Also added a tooltip to explain the clicking toggle
- We don't show the "color" at the bottom anymore

https://user-images.githubusercontent.com/35271042/137558687-cc9bfd2d-cf20-4bad-a631-0c6042518b20.mp4

**Comment by ghiscoding** [comment]
@misolori 
will it ever possible to have the color picker remain open when you start changing a color? (until you click outside or maybe an extra X close button). I find that so annoying that if you start changing color, and you move your mouse outside the container, the picker closes and you have to start over (chrome picker doesn't do that, if you start the color well it remains open), I find that a pain in the b... would be really really happy to get this fix... which issue #33568 that I opened in 2017

cheers and happy coding (I love VSCode) ❤️

**Comment by misolori** [comment]
@ghiscoding this behavior matches our hovers throughout the workbench (which I agree is not great) so it would need to be addressed by the hover widget (see https://github.com/microsoft/vscode/issues/95816 and https://github.com/microsoft/vscode/issues/130248)
