### ISSUE TITLE
Scroll off background color looks off in dark themes

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83587]
**Repo**
1. In Safari
1. Open a webview
1. Scroll up to trigger rubber banding

**Bug**
The scroll off background color is white, which is jarring on dark themes 

![Screen Shot 2019-10-29 at 2 59 25 PM (2)](https://user-images.githubusercontent.com/12821956/67812639-e35d7980-fa5c-11e9-92b2-90ffc359030b.png)

**Comment by lgraziani2712** [comment]
I don't know if this is related, but since version v1.40.1 to latest, dark themes has this bug where the background color doesn't really works:

![image](https://user-images.githubusercontent.com/15050200/70911230-30d37d00-1ff0-11ea-953e-cd47c247790c.png)

I happens in linux.

**Comment by mjbvz** [comment]
@lgraziani2712 Please file a new issue for that

**Comment by rebornix** [comment]
I'm not seeing this issue on Safari/iPadOS anymore.
