### ISSUE TITLE
SCM Viewlet not add modified files to changes section automatically, only after manual update

### ISSUE THREAD

**Issue by volkoff-pro** [microsoft/vscode#83581]
Issue Type: <b>Bug</b>

Open folder contains project with Git repo initialized, all files controlled by SCM.

Actual:
Edit file, then save. Modified files not shown in SCM Viewlet. After pushing 'Refresh' button in SCM Viewlet modified files shown in 'Changes' section. Changes not tracked by viewlet automatically.

Expected:

Edit file, then save. Saved file should be visible as modified in SCM Viewlet in 'Changes' section

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|2, 2, 6|
|Memory (System)|8.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
es7-react-js-snippets|dsz|2.4.3
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
code-runner|for|0.9.14
dotnet-test-explorer|for|0.7.1
rest-client|hum|0.22.2
vscode-nuget-package-manager|jmr|1.1.6
dotenv|mik|1.0.1
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.19.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
mssql|ms-|1.7.0
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.149.2
azurerm-vscode-tools|msa|0.8.0
debugger-for-chrome|msj|4.12.1
material-icon-theme|PKi|3.9.1
heroku-command|pko|0.0.8
swdc-vscode|sof|1.1.32
vscodeintellicode|Vis|1.2.0
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joaomoreno** [comment]
Please go through the following steps:

1. Run `Developer: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Make some file changes and wait 10-20 seconds
4. Paste the whole output here

Thanks!
