### ISSUE TITLE
Web: Opening large file completely freezes tab

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83584]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

- Open a compressed JS file or any large file (such as https://github.com/microsoft/TypeScript/blob/master/src/compiler/checker.ts)
- No syntax highlighting. Browser tab freezes

**Comment by alexandrudima** [comment]
I have tried Firefox on Windows and it works fine, perhaps it is a linux only issue

**Comment by alexandrudima** [comment]
I have also tried Firefox on Linux and I cannot reproduce. Opening `checker.ts` works fine for me.

@bpasero Can you please also quickly give this a try?

**Comment by bpasero** [comment]
checker.ts works fine for me on Ubuntu 18 using VSCode web selfhost in PWA.

**Comment by bpasero** [comment]
Oh, Firefox: seems to be OK as well (ver. 70).

**Comment by octref** [comment]
Strangely, I tried the same thing today and it didn't happen. If I can find the repro I'll attach more details or open a new issue.
