### ISSUE TITLE
keymapinfo: s is undefined

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83580]
Testing https://github.com/microsoft/vscode/issues/83296

Seems to be on this line from console output:
https://github.com/microsoft/vscode/blob/dedf0de944fae56f0bf748913cbc1b2cc24987d2/src/vs/workbench/services/keybinding/common/keymapInfo.ts#L302

**Comment by rebornix** [comment]
The fix is straightforward (checking npe) so verifier can check the code for verification.
