### ISSUE TITLE
Test Web: first breakpoint in extension not always hit

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83583]
Testing #83296:

Visual Studio Code - Insiders
Version: 1.40.0-insider
Commit: b7b21844e760e632f39bedf651da2bc93f54b0cc
Date: 2019-10-29T06:38:51.389Z
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

1. Open Web
2. Load https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample
3. Set a breakpoint
4. Start debugging. You can hit breakpoints.
5. Reload current page.
4. Start debugging. You still see the breakpoints there, but cannot hit it 🐛

**Comment by bpasero** [comment]
This sounds familar to extension host debugging.

**Comment by weinand** [comment]
@octref since there are two "pages" (tabs) involved here, let's clarify what do you mean by "current page" in your step 5: "Reload current page".

1. If you mean the "debuggee page/tab", then reloading that page should restart the extension host and the corresponding debug session. So "Start debugging" should not be necessary as it happens automatically. This worked for me fine and I could hit breakpoints after the reload.

 2. If you mean the "debugger page/tab", then It could be that you hit the (known) problem that the first breakpoint is not hit, but all subsequent breakpoints are hit. Could you please verify that this the case?

**Comment by octref** [comment]
@weinand  Your 2nd choice is exactly what I experienced. I couldn't hit the first breakpoint but I could hit later breakpoints, when the extension is activated with `activationEvents` as `*`. This seems unrelated to tab reloading.

New repro steps:

- Open [this sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample) in web / stable
- In `package.json`, change activation events to `*`
- Set a breakpoint in [this line](https://github.com/microsoft/vscode-extension-samples/blob/a8af0838d6b3228bbebddb3727d1360829d7cd0a/helloworld-minimal-sample/extension.js#L14)
- Native: You can hit the breakpoint
- Web: You can't

**Comment by weinand** [comment]
I've changed the title of this issue to better reflect the problem.

**Comment by weinand** [comment]
I can reliably reproduce the problem with the steps from above.

**Comment by weinand** [comment]
@roblourens I've compared the traces produced by the Web UI and the desktop version and it looks like that in the Web UI the debugger does not "pause on entry" before setting the breakpoints.

As a result, the debuggee has already continued over the activation code before the breakpoint could be set.

Do you have any idea why the debugger does not pause on entry for the Web UI?

Here are the two relevant trace items from the Web UI:
```
vscode-node-debug2.txt:[11:59:06.727 UTC] 1573127946.727: Waiting for initial debugger pause
...
vscode-node-debug2.txt:[11:59:12.008 UTC] 1573127952.008: Did not get a pause event after starting, so continuing
```

and here the ones from from the desktop version:
```
[14:59:53.080 UTC] 1573138793.08: Waiting for initial debugger pause
...
[[14:59:53.143 UTC] ← From target: {"method":"Debugger.paused","params":{"callFrames":[{"callFrameId":"{\"ordinal\":0,\"injectedScriptId\":1}","functionName":"","functionLocation":{"scriptId":"91","lineNumber":0,"columnNumber":0},"location":{"scriptId":"91","lineNumber":4,"columnNumber":29
```
And here are the full traces:

[webui-vscode-node-debug2.txt](https://github.com/microsoft/vscode/files/3820335/webui-vscode-node-debug2.txt)

[desktop-vscode-node-debug2.txt](https://github.com/microsoft/vscode/files/3820337/desktop-vscode-node-debug2.txt)

**Comment by roblourens** [comment]
In the original issue I suggested that the extension host probably isn't started with `--inspect-brk`, but it's launched by vscode, not the DA, so I think you should check that.

**Comment by weinand** [comment]
@roblourens Bingo - that was it.
Thanks a lot.
