### ISSUE TITLE
big type check when class internals change

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8358]
re #8203

* open `src/vs/base/common/event.ts`
* add a private field/copy `_disposed`
* 🐛 many files get re-checked tho no public shape has changed

**Comment by jrieken** [comment]
This is because TypeScript includes private member in the `d.ts` representation of the world

**Comment by dbaeumer** [comment]
Good catch. Will check with them why they do this ?

**Comment by dbaeumer** [comment]
This is on purpose since the TS compiler warns about overriding privates with same name in subclasses. However the signature are generated minimal (no type information) to make them more stable.
