### ISSUE TITLE
Safari cannot copy problem text to clipboard

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83598]
Testing #83296

**Repo**
1. Using safari
1. Create a ts file: 

```ts
// @ts-check
"use strict";
const a = 1;
a = 2
```

3. In the problems view, right click on the error and select `copy`

**bug**
Nothing copied

If I instead press `cmd+c`, I see a message stating:

```
undefined is not an object (evaluating 'navigator.clipboard.writeText')
```

**Comment by bpasero** [comment]
Duplicate? https://github.com/microsoft/vscode/issues/83595

**Comment by mjbvz** [comment]
@bpasero Different root cause I think, so reopening. `navigator.clipboard` does not seem to exist at all on Safari. It does in firefox
