### ISSUE TITLE
Dynamic Custom Data loading

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83594]
From https://github.com/microsoft/vscode-html-languageservice/issues/50.

I think we should do two things:

1. Offer an API for `vscode-[html|css]-languageservice` to load additional datasets to extends its catalog of tags/attributes etc.
2. Offer an extension API from `extensions/[html|css]-language-features` that allows extensions to contribute dynamically generated tags/attributes etc at runtime. This would make it possible to write extensions, such as a WebComponent extension, that would look into `node_modules` for WebComponents, analyze them and then add their tags to the html language server.

@aeschli What do you think?

**Comment by aeschli** [comment]
I'd rather stick with custom data to be static.
- Dynamic stuff should be done in the domain-specific extensions using the provider mechanism. (completion and hover providers) on a per-document basis.
- I want to avoid an APIs for css & html as to
   - avoid tight coupling
   - allow the user to disable or replace the html -/ css-language-feature extensions

**Comment by octref** [comment]
@aeschli So the suggestion for WC support extension would be:

- Clone the whole html language server
- Register all providers again
- Try to avoid feature conflicts (completion, hover, folding, etc)?

This is a LOT to ask from an extension.

**Comment by aeschli** [comment]
No, one would not replace and reimplement the HTML language server but have a server that adds additional proposals/hovers on top of it. 

- implement a server that provides a completion and hover provider. Register for HTML as well.
- use the HTMLScanner from 'vscode-html-languageservice' to find out what location you are, or use the ICompletionParticipant*.
- provide the proposals/hovers you want to add based on the additional context you have (e.g. WebComponents found in node modules, config files in the current files context)

An example for that is https://github.com/Microsoft/vscode/blob/master/extensions/npm/src/features/packageJSONContribution. `package.json` dependency proposals/hovers are added on top of the proposals coming from the JSON language server.

If we have good APIs in the languageservices it will be easy to implement such a server.
(*ICompletionParticipant could use some more methods..)

**Comment by octref** [comment]
OK, closing as out-of-scope then.
