### ISSUE TITLE
Insert Line Above command does not insert indentation

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#83596]
Testing #51802.

Have code (typescript here, but other languages too):
```
function main() {
  println("Hello world!");

  println("Goo|dbye!");

}
```

Carat at pipe, no whitespace in line 3. Insert Line Above does not add any indentation, whereas Insert Line Below does.

This is a regression from 1.39.

**Comment by ven5067** [comment]
@JacksonKearl We are not able to reproduce this in Version: 1.40.0. Can you please check it in this version and conform.

**Comment by JacksonKearl** [comment]
That being said, now that I've discovered its from a setting, its actually not a regression.

**Comment by rebornix** [comment]
`"editor.autoIndent": "none"` should now disable this completely.
