### ISSUE TITLE
Allow text editor commands to set the end selection

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#83590]
Issue Type: <b>Bug</b>

Consider an extension that registers a command using `registerTextEditorCommand`.  The desired behaviour is to move a block of text containing the cursor, and to keep the cursor at the "same" position relative to the block of text (in the block's new position).

This is implemented using the following code:

```
function oncmd(editor: vscode.TextEditor, edit: vscode.TextEditorEdit, ...args: any[]): void {
    const [rangeToMove, textToMove, lineCountToMove, destinationPos] = workOutTheBits();
    const newCursorPosition = editor.selection.active.translate(lineCountToMove, 0);
    edit.delete(rangeToMove);
    edit.insert(destinationPos, textToMove);
    editor.selection = new vscode.Selection(newCursorPosition, newCursorPosition);
}
```

However, after this, the text has moved, but the cursor is placed at the end of the inserted block, not at the position specified.

I believe the cursor position is being calculated correctly, but I think what is happening is that the new position is set _before_ the command handler returns, and the edit is applied by the VS Code text command infrastructure _after_ the command handler returns, and the edit resets the cursor position just as if the insert had been a paste.

**Expected behaviour:** An editor selection set within a text editor command should be respected after the edit completes.

**Actual behaviour:** The selection set within the command is lost when the edit is applied.

For a fully working repro see https://github.com/itowlson/porter-vscode/blob/move-step-up-down/src/commands/movestep.ts

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18912

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (47.80GB free)|
|Process Argv|--folder-uri file:///d%3A/GitHub/porter-vscode|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
gitlens|eam|10.1.1
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
vscode-pull-request-github|Git|0.12.0
terraform|mau|1.4.0
vscode-docker|ms-|0.8.1
duffle-vscode|ms-|0.3.0
python|ms-|2019.10.44104
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
csharp|ms-|1.21.5
Go|ms-|0.11.7
powershell|ms-|2019.9.0
vscode-typescript-tslint-plugin|ms-|1.2.2
quicktype|qui|12.0.46
java|red|0.52.0
vscode-yaml|red|0.5.3
rust|rus|0.7.0

</details>

**Comment by itowlson** [comment]
There is a workaround by using a normal command - we can get the active TextEditor via the API, perform the edit via the `edit()` method, and then set the selection in the continuation of the `edit` promise.  (This may in fact be more robust given that the edit could fail and we wouldn't want to move the selection in this case.)  Just seemed like a text editor command would be a more natural fit.

**Comment by alexandrudima** [comment]
This is an interesting use-case which we haven't thought about. The `edit` that is passed in is only executed later, on the UI thread. You can notice this by looking at the document content in between the delete and the insert, which is unchanged. Effectively, the `edit` object that is passed in is actually an edit builder (it collects the edits you wish to do) and then the edits are transferred to the UI thread, where they are executed.

```
function oncmd(editor: vscode.TextEditor, edit: vscode.TextEditorEdit, ...args: any[]): void {
    const [rangeToMove, textToMove, lineCountToMove, destinationPos] = workOutTheBits();
    const newCursorPosition = editor.selection.active.translate(lineCountToMove, 0);
    edit.delete(rangeToMove);
    edit.insert(destinationPos, textToMove);
    editor.selection = new vscode.Selection(newCursorPosition, newCursorPosition);
}
```
