### ISSUE TITLE
Allow extensions to contribute environment variables

### ISSUE THREAD

**Issue by stepro** [microsoft/vscode#83593]
We are exploring a VS Code extension that is intended to customize the behavior of external processes launched from the workspace such as tasks, terminals and debug sessions. This customization comes largely in the form of additional environment variables that are made available to those child processes.

It seems there is a hook point for debug launch profiles through a debug configuration provider, but no similar capability exists when running tasks or terminals. We can't find a workaround for tasks, and for terminals the only option seems to be to add a new command to launch a new specialized terminal, but that is awkward when the intent is for any terminal launched to receive these environment variables.

**Comment by alexr00** [comment]
Do you need to provide environment variables for tasks and terminals, or just tasks?

For tasks, can you use the `ShellExecutionOptions`? One of the options is to provide an `env`. https://github.com/microsoft/vscode/blob/58479e80ab899402283b522da173c34867d7c78f/src/vs/vscode.d.ts#L5295

**Comment by stepro** [comment]
The idea here is not that an extension explicitly launches a terminal but that an extension can _contribute_ environment variables to any call to launch a terminal. Similar to how a debug configuration provider can inject specific settings into a launch profile prior to a debug session starting.

**Comment by stepro** [comment]
> Do you need to provide environment variables for tasks and terminals, or just tasks?

Really we would need it for terminals, and it would be nice to have it for tasks as well, but that's less important.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/46696

**Comment by Tyriar** [comment]
Actually I'll close it in favor of #46696 as it's essentially the same ask, would be good to get more feedback over there @alexr00 @stepro
