### ISSUE TITLE
OSS: Extension pages not loading in safari

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83591]
Testing #83296

**Repo**
1. Using safari
1. View an extension page

**Bug**
It doesn't load. See the errors:

<img width="1267" alt="Screen Shot 2019-10-29 at 3 41 35 PM" src="https://user-images.githubusercontent.com/12821956/67814901-9bd9ec00-fa62-11e9-88f6-ca6268e32db9.png">

**Comment by rebornix** [comment]
The error message said we need `allow-scripts` on `./fake.html`, otherwise it can't be loaded on Safari. I'm wondering if we have to sanitize the extension page content and turn on `allow-scripts` to fix this issue and be secure.

**Comment by mjbvz** [comment]
This error is really weird and difficult to debug. I do not think enabling `allow-scripts` is what we want since other browsers don't complain about this pattern

**Comment by mjbvz** [comment]
Moving to backlog since this doesn't show up in VSO itself. It seems to be a safari bug

**Comment by rebornix** [comment]
Very likely related to security check and only exist in selfhost.

**Comment by mjbvz** [comment]
Should be fixed in latest insiders (see linked issue)
