### ISSUE TITLE
Escape does not clear selection on safari 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83599]
Testing #83296

**Repo**
1. Using Safari, select some text
1. Now press <kbd>escape</kbd> to clear the selection

**Bug**
Nothing happens

**Comment by rebornix** [comment]
I didn't reproduce issue on Safari. More details to help reproduce?

**Comment by mjbvz** [comment]
Having trouble narrowing down. It seems to happen after switching between text editors when you have an active selection

A few times I've also gotten into a state in Safari where keyboard events don't seem to work at all in the editor (I can't type anything in the editor but can type in input boxes). I will keep testing this afternoon

**Comment by mjbvz** [comment]
Got it. Is somehow related to the settings editor. Repo:

1. In safari with no folder open
1. Open an untitled text editor
1. Write some random text in it
1. Now open the user settings editor from the command palette
1. Then switch back to the untitled text editor
1. Make a selection and press `escape`
1. 🐛 Nothing happens

**Comment by mjbvz** [comment]
On Firefox, I also just hit the case where I can't type anything in the normal text editor. It also seems related to having the settings editor open. What happens is:

1. I switch back to the text editor and start typing
1. Nothing happens
1. When I then switch to the settings editor, I see that my input has been going into the settings search box instead

**Comment by rebornix** [comment]
@mjbvz thanks for the detailed steps, I can reproduce this now.

**Comment by rebornix** [comment]
After digging into it for a while, I found it pretty interesting. You can reproduce this issue on Safari/Firefox/Edge however it works fine in Chrome. Here is what happens in the product

1. Users open a file, a monaco editor is created and appended to the editor group container
2. Users open the Settings Editor (you can open the Keybinding Editor as well, doesn't matter too much as long as it contains another Monaco Editor). Settings Editor is appended to the editor group as well and previous Monaco Editor is detached.
3. Settings Editor contributes a context key for Input Box Focus.
4. Settings Editor listens to the `blur` event on the textarea of the Monaco Editor in the Input Box. Once it receives the `blur` event, it will clear the focus context key.
5. Users switch to the previous file, we will detach the Settings Editor from the editor group container and attach the previous Monaco Editor for that file

In VS Code or Chrome, when Step 5 happens, the `blur` event is triggered so we clean the Settings Editor Focus context key successfully. Everything is in a good state.

In Safari/Edge/Firefox, when Step 5 happens, no `blur` event is triggered. Thus when users press Escape in the file editor, our keybinding services will find the command contributed by Settings Editor. The selection in the file editor won't be cleared. Even worse, you can't dismiss Find Widget, Suggestion, almost anything relies on Escape key.

I can't say which browser is definitely correct. Ultimately, it's all about whether the `blur` event should be emitted when the element is being detached from the DOM tree.

Say there is a simple 3 layer DOM tree in your page

```
- root
  - container
     - texarea (focused)
```

If we run `root.removeChild(container)` on Chrome, `blur` event is emitted on `textarea` but we don't receive any event on Safari/FF/Edge.

---

One workaround is triggering `blur` on `container` and then remove `container` from `root in next tick. In our code base, it's delaying `this.parent.removeChild(controlInstanceContainer)`.

https://github.com/microsoft/vscode/blob/245b4dad4579b07b01f18e7d6b9895b49c6af3a9/src/vs/workbench/browser/parts/editor/editorControl.ts#L207-L211

cc @bpasero and see if you get better ideas on this issue.

**Comment by bpasero** [comment]
@rebornix I think firing the blur event is probably fine, but why the `process.nextTick`? that sounds a bit scary. 

Besides, isn't the editor instance that gets focus emiting a focus event that we should react to?

**Comment by rebornix** [comment]
> but why the process.nextTick?

A `blur()` followed by node removal won't work. The browser engine still thinks the `blur` event should not be triggered as it sees node removal from the `document.body` right after. A `setTimeout` ensures that those event listeners are handled but I agree, it looks a bit scary.

Monaco Editor internally listens to `textarea`'s blur event to update its internal state of `editorFocus` and `editorTextFocus`. To ensure all Monaco related features work properly, we'd better trigger a blur on `textarea`. We can have a new code path to update Monaco's internal state completely but the catch here is, any code which listens to a DOM node's `blur` event (probably all events) might break when the DOM node is detached from `document.body`. For example, `/vs/base/browser/browser#FocusTracker` has the same bug ;(

Based on above reasons, I propose that we make `doHideActiveEditorControl` async and wrap `this.parent.removeChild(controlInstanceContainer);` into a `setTimeout` and resolve the promise once the removal happens. This way we can ensure that all `blur` event listeners receive those events.

**Comment by rebornix** [comment]
I don’t think it’s a good idea to go with above approach as it will make literally everything related to the editor Async. For now, an easier approach is implementing onHide hook in BaseEditor to at least let Monaco refresh its focus state when it’s being removed/hide.

**Comment by bpasero** [comment]
> I don’t think it’s a good idea to go with above approach as it will make literally everything related to the editor Async. 

Yeah, I never want to add any async things related to DOM manipulation, that just asks for trouble and weird bugs. I can call a method on the editor if it helps before it is removed from the DOM if you add one.

**Comment by rebornix** [comment]
`CodeEditorWidget` already has `onHide` hook without any implementation, now we will check if current textarea is in the DOM tree and focused or not when `onHide` is invoked.

**Comment by rebornix** [comment]
Verifiers:

* Steps
  * Open a file, select some text
  * Open the Settings Editor
  * Switch to the previous file
  * Press Escape, make sure it clears the selection
  * CMD+F to open the find widget
  * Press Escape, make sure the find widget is dismissed
* Matrix
  * Safari and Firefox

**Comment by RMacfarlane** [comment]
Clearing selection works as expected, but the find widget still isn't getting dismissed on Escape on Safari and Firefox

**Comment by rebornix** [comment]
@RMacfarlane good catch. My previous fix only clears the text focus state but didn't clear the widget focus state, which is tracked by blur listeners on container DOM node.
