### ISSUE TITLE
Cannot paste into terminal

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83595]
Testing https://github.com/microsoft/vscode/issues/83296

On Windows+FF

1. Open the terminal and select some text with the mouse
2. Right-click to copy
3. Right-click to paste

🐛 Text is not pasted

This may be the fault of the clipboard service (my doing), but can you check your handler first and assign back if the service doing something wrong?

**Comment by sbatten** [comment]
it's the clipboard service

**Comment by Tyriar** [comment]
Was there a permissions dialog that popped up? Did it work with regular pasting?

**Comment by sr229** [comment]
@Tyriar We've triaged it that Chrome and Firefox blocks the Clipboard API if its not `localhost` or `.local`, so I don't think VSCode would catch that.

**Comment by rebornix** [comment]
`paste`/clipboard is only accessible from browser extensions in FF. To enable pasting, we need

* Do not register Paste command for `cmd/ctrl+v` in FF
* Thus do not register the command to Context Menu

@Tyriar I can send you a PR to get above commands registration removed from `isWeb && isFirefox`. Xterm listens to `paste` on the textarea, once the keybindings are removed, users can at least paste.

**Comment by Tyriar** [comment]
Sure just removing the keybindings for firefox sounds good to me, those keybindings where only added very recently.

**Comment by rebornix** [comment]
Verifier, please test both Safari and Firefox.
