### ISSUE TITLE
Webview: links show status bar hover

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83609]
**repo**
1. On web
1. Open welcome page.
1. Hover over a link such as the one to `JavaScript` under `Tools and languages`

**Bug**
Notice the browser's default link destination is display in the lower left corner, on top of the status bar:

![Screen Shot 2019-10-29 at 5 18 21 PM (2)](https://user-images.githubusercontent.com/12821956/67818963-6805c300-fa70-11e9-81c8-d9b8fed5f9ac.png)

This may be useful for external links, but it is almost never useful for our internal links (such as command uris)

**Comment by bpasero** [comment]
I am not sure we can disable that.

**Comment by bpasero** [comment]
I have not seen this so far in other places, so it seems specific to our iframes. I can reproduce from the markdown preview as well as welcome.

**Comment by mjbvz** [comment]
I can't figure out a good way to disable this for webviews without potentially impacting extension. 

@chrmarti Assigning you for the welcome page but feel free to close this if it's already been addressed or want to won't-fix this

**Comment by chrmarti** [comment]
Removing the `href` makes it render like regular text and it cannot be tabbed to anymore. Closing without change.
