### ISSUE TITLE
Vscode icon shrunk and unable to delete

### ISSUE THREAD

**Issue by ricardooow** [microsoft/vscode#83601]
Issue Type: <b>Bug</b>

Updated to the last insider, after the restart required was pressed the vscode icon shrunk to minimalistic size in the dock on mac. Unable to interact with it or get rid of it anymore as usual when vscode is turned off and you open enough apps it closes.

On the picture the VSCode icon is small/not really visible but the dot of being active is present and next to it the normal Icon size.

<img width="69" alt="Schermafbeelding 2019-10-30 om 00 36 46" src="https://user-images.githubusercontent.com/28981399/67817633-66f38680-faae-11e9-8ac5-bcaee1eaa2bc.png">

VS Code version: Code - Insiders 1.40.0-insider (b7b21844e760e632f39bedf651da2bc93f54b0cc, 2019-10-29T06:46:37.742Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (7.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
prettier-vscode|esb|2.3.0
pop-n-lock-theme-vscode|Lux|3.18.10
python|ms-|2019.10.44104
vsliveshare|ms-|1.0.1056
nested-comments|phi|2.3.1
polacode|pnp|0.3.4
vscode-icons|vsc|9.5.0

(3 theme extensions excluded)

</details>

**Comment by misolori** [comment]
See https://github.com/Microsoft/vscode/issues/63068. Running `killall Dock` from the terminal appears to fix this issue.
