### ISSUE TITLE
Interface overview is off then compact menu is enabled

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83607]
Testing #83296

**repo**
1. Using web
1. Open welcome page and go to `interface overview`

**bug**
Due to the new compact menu bar, the indicators are slightly off vertically:

![Screen Shot 2019-10-29 at 5 07 16 PM](https://user-images.githubusercontent.com/12821956/67818484-a7331480-fa6e-11e9-9df6-d9fc7a0ee2d5.png)

**Comment by bpasero** [comment]
Funky, this is actually an issue for desktop too if the compact menu is enabled.

**Comment by joaomoreno** [comment]
Verified in dev.
