### ISSUE TITLE
Safari still is able to trigger a user-selection on parts of workbench

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83602]
Testing #83296

**Repo**
1. Using safari. 
1. Open an editor and an empty debug panel
1. Click down in the debug panel and drag upwards

**Bug**
We start selecting parts of the workbench:

![Screen Shot 2019-10-29 at 4 44 48 PM](https://user-images.githubusercontent.com/12821956/67817680-992fc480-fa6b-11e9-9307-5eef179f3e81.png)

**Comment by bpasero** [comment]
This is odd behaviour in Safari: when I add `-webkit-user-select: none` to the `body` element, I can fix this issue, but then suddenly no text selection works in the monaco editor.

As a workaround, I am setting the following rule only on Safari:

```css
.monaco-workbench .monaco-editor .view-lines {
	user-select: text;
	-webkit-user-select: text;
}
```

And that seems to make it work again, but I am not sure if that catches all the cases.

@alexandrudima @rebornix maybe you have a clue what could be going on with Safari. I am sure users of the standalone editor must be hitting this issue as well in Safari.

**Comment by alexandrudima** [comment]
@bpasero I think your change is good and needs to live in the workbench layer, so it all looks good.

The standalone editor also uses `user-select: none`, with the exception of Safari and macOS webviews. See [the css](https://github.com/microsoft/vscode/blob/0ba9f6631daec96a2b71eeb337e29f50dd21c7e1/src/vs/editor/browser/viewParts/lines/viewLines.css#L17-L23) which is used everywhere [except Safari](https://github.com/microsoft/vscode/blob/0ba9f6631daec96a2b71eeb337e29f50dd21c7e1/src/vs/editor/browser/config/configuration.ts#L359-L362).

**Comment by alexandrudima** [comment]
I don't really remember... :) Let's leave as it is and intervene only if necessary.

**Comment by connor4312** [comment]
Seems to work well off master, I'm not able to get into weird selection statese.
