### ISSUE TITLE
Editor `...` icon not centered in high contrast mode

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83605]
**Repo**
1. Open a md file
1. Switch to the `high contrast` theme

**Bug**
Notice that the `...` icon in the editor bar is a the top. It should be centered:

![Screen Shot 2019-10-29 at 4 55 14 PM](https://user-images.githubusercontent.com/12821956/67818035-11e35080-fa6d-11e9-9622-67ef0451a7c5.png)

**Comment by wattledcord** [comment]
hi @mjbvz I have identified the issue and fixed it and ready for PR
