### ISSUE TITLE
Pinch to zoom image editor doesn't work on safari

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83606]
Testing #83296

**Repo**
1. Using Safari
1. Open an image editor
1. Try to pinch to zoom in

**Bug**
The entire webpage zooms

**Comment by bpasero** [comment]
We are setting this in our HTML to prevent pinch zooming:

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">`

Possible that if you are pinch-zooming into an iframe the rule is disabled. Maybe you need to add something like that too?

**Comment by mjbvz** [comment]
Hmm, I think that used to work but now safari may ignore `user-scalable=no` (I know safari on iOS ignores this setting). Even with that tag I can still pinch to zoom the entire workbench 

We may have to intercept touch events to block the browser level zoom in safari

**Comment by bpasero** [comment]
Yeah I noticed this too, but when I added the web to home screen (I guess that means doing PWA on iPad) I could not pinch zoom anymore. So maybe that is working only in PWA mode?

**Comment by rebornix** [comment]
I don't think it's possible to disable pinch zoom possible right now in iOS (accessibility concern) and desktop (based on my current testing). There are a few issues tracking in webkit like https://bugs.webkit.org/show_bug.cgi?id=145214 without any official response. CSS tricks like `touch-action: none` doesn't work as well, it can disable scrolling but can't disable pinch zoom.

**Comment by rebornix** [comment]
Right now zoom works in an image editor but it zooms the whole workbench (looks like the zoom event bleeds), but if we focus on a monaco editor or just welcome page or watermark, it doesn't zoom at all.

**Comment by isidorn** [comment]
@bpasero I think Pinch zooming on the iPad might make sense for accessibility reasons (easy way to zoom) so I will experiment with removing that `user-scalable` attribute.

**Comment by bpasero** [comment]
Just make sure to not accidentally allow to pinch zoom on the desktop. We don't want people to zoom into parts of VSCode on desktop.

**Comment by isidorn** [comment]
I just tried this out on the whole workbench and it just does not work nicely. Our UI is not designed for this. Thus just enabling it on the whole workbench does not make sense. Enabling it on the image editor might make more sense.

**Comment by yiliang114** [comment]
> Right now zoom works in an image editor but it zooms the whole workbench (looks like the zoom event bleeds), but if we focus on a monaco editor or just welcome page or watermark, it doesn't zoom at all.

The same behavior is true in webview, which scales the whole workspace, although I didn't mean to scale the whole workspace.  

There is also the forward and backward behavior of the trackpad or mouse, which will not be triggered in the workspace, but will also be triggered in the webview. Is this unexpected? @rebornix @mjbvz

**Comment by yiliang114** [comment]
> > Right now zoom works in an image editor but it zooms the whole workbench (looks like the zoom event bleeds), but if we focus on a monaco editor or just welcome page or watermark, it doesn't zoom at all.
> 
> The same behavior is true in webview, which scales the whole workspace, although I didn't mean to scale the whole workspace.
> 
> There is also the forward and backward behavior of the trackpad or mouse, which will not be triggered in the workspace, but will also be triggered in the webview. Is this unexpected? @rebornix @mjbvz

![image](https://github.com/microsoft/vscode/assets/11473889/98b59b7a-b995-46ee-880e-ceffac9f2b67)
