### ISSUE TITLE
Saving an untitled file (ex: temp.txt) adds extra extension temp.txt.txt on save dialog

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/vscode#83603]
- VSCode Version: 1.39.2
- OS Version: Win and Mac

Steps to Reproduce:

1. Open any existing file resource with untitled schema : ex: notebook1.ipynb
2. Make changes to the file 
3. Hit close, it prompts to save/discard the file with changes, choose save 
4. You'll see the save file dialog with name notebook1.ipynb.ipynb

Refer: https://github.com/microsoft/azuredatastudio/issues/7641

Proposed fix we made:
mime.ts under vs/base/common has the method: suggestFilename which appends the extension type.  (Below code snippet)

if (extensionsWithDotFirst.length > 0) {
		return prefix + extensionsWithDotFirst[0];
	}

Fix:
if (extensionsWithDotFirst.length > 0) {
		return prefix.endsWith(extensionsWithDotFirst[0]) ? prefix : prefix + extensionsWithDotFirst[0]; // {{SQL CARBON EDIT}}
	}

**Comment by bpasero** [comment]
@MaddyDev I pushed the change you suggested. In the future feel free to open PRs. If there are other things you currently have to patch but could be useful for VSCode, let me know.
