### ISSUE TITLE
Terminal and Minimap glitches.

### ISSUE THREAD

**Issue by tykonin** [microsoft/vscode#83604]
![Screenshot](https://user-images.githubusercontent.com/36377395/67817757-5eec1480-fab7-11e9-9660-be000ad3af6d.png)

This is how it looks, the same happens with the minimap. 
Nothing changes if I disable the extensions or start vscode with --disable-gpu  

I can't state exact steps to reproduce, but it happens at least once every 30 minutes of just editing or debugging, sometimes right after vscode is started.  

- VSCode Version:1.39.2
- OS Version: Arch Linux

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by Tyriar** [comment]
Looks like a problem with canvas, you can try updating your graphics driver and if that doesn't work disable the canvas renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```
