### ISSUE TITLE
Allow extensions to modify the type of a file as used by 'extension.sortOrder'

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#83618]
I want to be able to sort files in the explorer using an attribute provided by an extension. I think the simplest way to achieve this would be via allowing extensions to modify the type of a file within the context of setting `extension.sortOrder` to `type`. This would be very helpful for large projects written in Go because of how Go expects tests to be structured.

For example, let's say I have a workspace with the following files:

  - `.gitlab-ci.yml`
  - `a.go`
  - `a_test.go`
  - `b.go`
  - `b_test.go`
  - `go.mod`
  - `go.sum`
  - `README.md`
  - `x.go`
  - `x_test.go`

If I set `extension.sortOrder` to `type`, this becomes:

  - `a.go`
  - `a_test.go`
  - `b.go`
  - `b_test.go`
  - `x.go`
  - `x_test.go`
  - `README.md`
  - `go.mod`
  - `go.sum`
  - `.gitlab-ci.yml`

This is better than purely alphabetical sorting, but as the number of files grows, browsing the project becomes increasingly unwieldy. I want to be able to create an extension that would allow me to sort in the following way:

  - `a.go`
  - `b.go`
  - `x.go`
  - `a_test.go`
  - `b_test.go`
  - `x_test.go`
  - `README.md`
  - `go.mod`
  - `go.sum`
  - `.gitlab-ci.yml`

If extensions could modify the sort type of a file, I could achieve this by changing the type of `*_test.go` from `go` to `go_test`.

**Comment by firelizzard18** [comment]
I've looked and I couldn't find what this is a duplicate of. Would you please specify which existing issue this duplicates?

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/27286
