### ISSUE TITLE
Hello, when downloading to my MacBook, it keep saying, 'it cannot be downloaded.'

### ISSUE THREAD

**Issue by aydidmohamed** [microsoft/vscode#83613]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aydidmohamed** [comment]
![Screen Shot 2019-10-29 at 9 50 46 PM](https://user-images.githubusercontent.com/54713520/67822552-20466200-fa97-11e9-9f2b-10d574479ae8.png)

**Comment by aydidmohamed** [comment]
that was what i was talking about

**Comment by mjbvz** [comment]
See #74782
