### ISSUE TITLE
have problem with macbook

### ISSUE THREAD

**Issue by aydidmohamed** [microsoft/vscode#83615]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by importnetminecraft** [comment]
Why did you open 3 issues for one problem? You are slowing the dev team down by spamming them and so your problem is less likely to be fixed in a timely manner.

**Comment by aydidmohamed** [comment]
Hello,

Am sorry guys. How long do you think I get the next respond concerning my issues. Thank you

**Comment by gjsjohnmurray** [comment]
What does your Service Level Agreement promise about the response time?

/duplicate #83613
