### ISSUE TITLE
Dragging a folder onto  a tab should not show drop acceptance feedback

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8362]
testing #7852 

- select a folder in the explorer
- drag it onto a tab

![image](https://cloud.githubusercontent.com/assets/172399/16417502/6ff336be-3d46-11e6-8c4f-758658f9c81c.png)

-> the tab shows acceptance feedback, but when dropping the folder nothing happens, except some temporary flickering.

I would have expect that no drop acceptance feedback is shown.

**Comment by bpasero** [comment]
@egamma unfortunately all I have is a resource URI and from that I do not know if it is a folder or not. Same is true when dragging from the desktop.

**Comment by bpasero** [comment]
Some things:
* dragging from the desktop ideally contains information about the resource being dragged being a folder or not
* dragging a file from the tree should use the same native file transfer

I think there is some upstream dependencies on this issue.
