### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by ashish336b** [microsoft/vscode#83626]
After VS code run autosave , cursor is moved to very last line of the file which make you to type in very last line

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you run with all extensions disabled?

**Comment by ven5067** [comment]
@ashish336b Can you help us understand what do you mean by run autosave. VS code has a toggling autosave feature which will help in saving your files.

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate this

**Comment by ashish336b** [comment]
It was due to vs-code extension "html-css-js" formatting tool

**Comment by ashish336b** [comment]
solved it was due to extension of html-css-js formatter
