### ISSUE TITLE
Cannot Debug in VS COde when using typescript 3.7

### ISSUE THREAD

**Issue by shahabganji** [microsoft/vscode#83628]
- VSCode Version: 1.39.2
- OS Version: Windows 10, Mac OS X Mojave

Steps to Reproduce:

1. Use Null Check operator, introduced in 3.7
2. Debug the application.

Does this issue occur when all extensions are disabled?: Yes
<hr />
I have a codebase in which I am willing to use `typescript@3.7.1-rc`, I have set the version of typescript for the VS Code. I could build and run tests using the command line, but when I want to debug the application it claims there are errors, when I ask to show errors there is nothing in the `Problems` tab, but a whole bunch of error messages in the `Output` tab. I also figured out that the corresponding javascript generated codes are different from what I get for different modules when using the command line.

*example*

```ts
if (filterElements || configuration.classes?.filterElements) {
            const filter = filterElements || configuration.classes!.filterElements;
}
```

The errors are like:

```bash
sample.ts(42,53): error TS1109: Expression expected.
sample.ts(42,68): error TS1005: ':' expected.
```

Wherever I used `3.7` features like the null check, I got the same issue.

column `53` is where the `question mark` is, and `68` is the place of `)`.

__generated code__  **when debugging**
```js
if (filterElements || configurations_1.configuration.classes ? .filterElements : ) {
    const filter = filterElements || configurations_1.configuration.classes.filterElements;
}
```

__generated  code__ **commonjs**
```js
 if (filterElements || ((_a = configurations_1.configuration.classes) === null || _a === void 0 ? void 0 : _a.filterElements)) {
            var filter = filterElements || configurations_1.configuration.classes.filterElements;
}
```

And here is my `tsconfig.json` file:

```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "lib": [
            "esnext"
        ],
        "declaration": false,
        "sourceMap": true,
        "removeComments": true,
        "importHelpers": true,
        "strict": true,
        "downlevelIteration": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noImplicitReturns": true,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "skipLibCheck": true
    },
    "baseUrl": "src",
    "paths": {
        "@utils/*": [
            "utils/*"
        ]
    },

    "exclude": [
        "node_modules",
        "wwwroot",
        "typings",
        "test",
        "dist"
    ]
}
```

**Comment by roblourens** [comment]
Can you explain "generated code when debugging", do you build differently when starting the debugger?

@mjbvz  I don't think this actually involves the debugger

**Comment by shahabganji** [comment]
@roblourens I just hit `F5`, nothing more nothin less.

**Comment by mjbvz** [comment]
@shahabganji Have you [switched your workspace version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to 3.7-rc?

**Comment by roblourens** [comment]
> nothing more nothing less, and I see some js files generated next to each ts file.

VS Code doesn't automatically build anything for you, you probably have a preLaunchTask in your launch config. If you can share your project or more info, we can probably figure out why it's building incorrectly. Maybe you have an old version of `tsc` on the PATH and it's referencing that.

**Comment by shahabganji** [comment]
> @shahabganji Have you [switched your workspace version of TypeScript](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions) to 3.7-rc?

Yes, I did, I mentioned that above too, I guess the problem is related to what @roblourens said above, I have a `preLaunchTask` which uses the global `tsc` installed, in my case, it is `3.6`, I thought when we change the workspace typescript version, it also uses that version but is looks not to. So I updated my globally installed typescript to `3.7.1-rd` as well, however, I share the `launch.json` file, if it is possible please guide me how to set it to use the workspace typescript 🙏 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/index.ts",
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "tsc",
            "outFiles": [
                "${workspaceRoot}/**/*.js"
            ],
            "sourceMaps": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-r",
                "scripts/tshook.js",
                "--timeout",
                "10000",
                "--recursive",
                "--watch",
                "--colors",
                "test/**/*.ts",
                "test/**/**/*.ts"
            ],
            "cwd": "${workspaceRoot}",
            "internalConsoleOptions": "openOnSessionStart",
            "skipFiles": [
                "<node_internals>/"
            ],
        }
    ]
}
```

**Comment by roblourens** [comment]
It depends on what that task is, can you share the tasks.json?

**Comment by shahabganji** [comment]
@roblourens 

This is my `task.json`

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-p", "."],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}
```

**Comment by mjbvz** [comment]
This is a configuration issue/question. See the typescript and tasks guides for help making sure you are suing the correct ts version in your task: https://code.visualstudio.com/docs/typescript/typescript-compiling#_transpile-typescript-into-javascript

**Comment by shahabganji** [comment]
Thanks @mjbvz and @roblourens  for your help and support. @vscodebot I have asked it first on StackOverflow, [here](https://stackoverflow.com/questions/58614630/why-vs-code-fails-to-debug-sources-with-ts-3-7-1-rc-syntax-support?noredirect=1#comment103539236_58614630), but got no feedback.
