### ISSUE TITLE
Recent items are not updating

### ISSUE THREAD

**Issue by davidc555** [microsoft/vscode#83622]
Issue Type: <b>Bug</b>

Open an existing local file, edit it, then Save As a new file name.  Close the tab for that file, then go to File, then Open Recent and you don't see the latest file listed there.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (10.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
@davidc555 can you share how you are opening the file?
