### ISSUE TITLE
run golangci-lint error, msg="Parallel golangci-lint is running"

### ISSUE THREAD

**Issue by fantianjin** [microsoft/vscode#83621]
/home/faneluo/QQMail/gobackend/server/mmocadbinlogreader/binlog
Error while running tool: /data/go/bin/golangci-lint run --print-issued-lines=false level=error msg="Parallel golangci-lint is running"

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0049

**Comment by rafaelvanoni** [comment]
I just started hitting this issue with golangci-lint v1.21.0 on the command line. No extensions or any options specified, just running `golangci-lint run`. It doesn't even print a help message if I pass `-h` to it.
