### ISSUE TITLE
Replace: viewlet size broken when replace expanded

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8363]
Refs: https://github.com/Microsoft/vscode/issues/8184

Check how this is done for when the search details are expanded, you need to accomodate this in the layouting of the viewlet:

![image](https://cloud.githubusercontent.com/assets/900690/16417695/227cb378-3d47-11e6-948f-6446d3b7acb6.png)

**Comment by sandy081** [comment]
@bpasero I am not able to reproduce this.. I tried navigating into different views back and forth. Let me know if you are able to reproduce it?

**Comment by bpasero** [comment]
Will do!
