### ISSUE TITLE
Add option to disable automatic selection on focus in explorer

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#83639]
At the moment, when you focus the explorer view, currently current files is *simultaneously* focused and added to selection. If you move the cursor in the explorer, you get into a situation where one file is selected, and another file is focused:

![image](https://user-images.githubusercontent.com/1711539/67842150-a6e85700-fb0a-11e9-9dc1-10dadfd889be.png)

For me personally, it is super confusing because, if I invoke action such as "rename", I don't know off hand which of the two files will be acted upon. I think the action works for the current file, unless the selection contains more than one file, which is not super obvious.

I suggest splitting Auto reveal setting which currently control *both* revealing and focusing behavior into to.

Now:

![image](https://user-images.githubusercontent.com/1711539/67842460-41e13100-fb0b-11e9-8b2a-a5af46579cad.png)

My Suggestion:

* Auto Reveal: controls whether the explorer should automatically revel files when opening them
* Select on Reveal: controls whether the explorer should automatically select revealed files

If the second option is checked, revelaing file in the explorer by clicking with a mouse on it or opening a file in the editor should not select it.

**Comment by matklad** [comment]
See also [this UI bug](https://github.com/microsoft/vscode/issues/83640) which exacerbates the confusion here.

**Comment by matklad** [comment]
Not sure why this was marked as a duplicate: #75181 seems unrelated. Does this duplicate some other issue?

**Comment by isidorn** [comment]
Please search for all issues tagged with `File-Explorer` and you will find the duplicate. Thank you

**Comment by matklad** [comment]
For posterity:

Looks like I was for https://github.com/microsoft/vscode/issues/67697#issuecomment-459675914, which was implemented without an option and reverted, to maintain the old behavior.

**Comment by isidorn** [comment]
Let's reopen this issue, and we can discuss on how to improve this behavior.
I will not have time to look into this this milestone, thus assigning to December in case we get to a good idea that we can implement something. Thanks

**Comment by isidorn** [comment]
I have looke into this and was not happy with the solution and how this felt.
Due to that I am pushing out this to the backlog.
I have created this PR in case somebody from the community has a better idea on how to solve this so they can potentially pick up my work https://github.com/microsoft/vscode/pull/88046

**Comment by isidorn** [comment]
This is fixed now actually with latest vscode insiders
Please use explorer.autoReval: focusNoScroll
