### ISSUE TITLE
Compact menu should not move up when space is small

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83637]
I think it should stay to the top permanently and not move:

![image](https://user-images.githubusercontent.com/900690/67842059-b7dc9c80-faf9-11e9-954f-114a2c4a97c6.png)

**Comment by sksaifuddin** [comment]
Hello, I am looking for good first issues, this issue looks good for me. @bpasero  can you please guide me a little on how to solve it.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/84074
