### ISSUE TITLE
Compact menu: should remove DOM nodes after use

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83638]
If you inspect the compact menu, I can see that all the top level menu items are in the dom even though I did not click:

![image](https://user-images.githubusercontent.com/900690/67842529-9e882000-fafa-11e9-8d14-752613464711.png)

Imho DOM nodes that are not visible by default should be created lazily and removed after being used.

**Comment by sbatten** [comment]
Yea these are there as an artifact of the original menu. They are never shown in the compact case. The reason they are there normally and set to visibility hidden is to ensure we can do math on the dimensions of the full menu bar. Keeping them around made it easy to switch between menu modes but cleanup can be done.
