### ISSUE TITLE
Update https-proxy-agent

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#83647]
https://www.npmjs.com/advisories/1184

**Comment by chrmarti** [comment]
@RMacfarlane We should also update the Pull Request and Azure Account extensions to use https-proxy-agent 2.2.3 or later. Could you take care of that?

For some reason GitHub does not report this security issue (yet?).

**Comment by aeschli** [comment]
published request-ligh@0.2.5, update usage: 7b944a16f52843b44cede123dd43ae36c0405dfd

**Comment by chrmarti** [comment]
@RMacfarlane Pull Request gets it from `vscode-test`. You can switch to the newer version by updating the `yarn.lock` (I once did that manually, not sure if yarn can update a single subdependency). /cc @octref

**Comment by octref** [comment]
Fixed as of vscode-test@1.2.1.
