### ISSUE TITLE
go code deleted after save

### ISSUE THREAD

**Issue by rangangwei** [microsoft/vscode#83642]
Issue Type: <b>Feature Request</b>

sometimes, I save my code, but code deleted, maybe I upgraded go program

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 6.1.7601

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate this
