### ISSUE TITLE
Js intellisense does not work instead I see CSS intellisense in a JS file

### ISSUE THREAD

**Issue by Jakub41** [microsoft/vscode#83641]
- VSCode Version: 
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
- OS Version: MacOs Catalina 10.15 (19A602)

Steps to Reproduce:

1. Open a JS file and try to use the IntelliSense
2. try to add a JS method as addEventListner to an element
3. the CSS IntelliSense is showed only
4. check the attached screenshot 
ScreenShot
![Screenshot 2019-10-30 at 09 40 48](https://user-images.githubusercontent.com/8559542/67842443-77315300-fafa-11e9-9cb9-23b59cb904bf.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes and also with the only IntelliSense enable

**Comment by Jakub41** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Disable intellisense when typing <?php in php documents (#68535)](https://www.github.com/microsoft/vscode/issues/68535)

This what the bot shows is not relevant to my issue as in my case I don't have the JS IntelliSense working as should be in a JS file but I see the CSS shortcuts instead as in my screenshot that the strange part I would like to resolve.
Thank you for helping me out :)

**Comment by jrieken** [comment]
what you see are snippets, which are always shown unconditionally... you can use the use th `editor.snippetSuggestions` setting to disable them or disable/uninstall the extension that has contributed them
