### ISSUE TITLE
"Webview: Cannot load resource outside of protocol root", if .md source is an network share

### ISSUE THREAD

**Issue by SebastianBaeumler** [microsoft/vscode#83646]
if a markdown file is located on a network share, images `![test](./2019-10-30-10-04-55.png)` can not be loaded in preview.
Same folder on the local filesystem work fine.
![image](https://user-images.githubusercontent.com/39997594/67849571-13615700-fb07-11e9-8a08-943bf4e01062.png)

Console display the error

webviewProtocols.ts:27 Webview: Cannot load resource outside of protocol root
e.session.protocol.registerBufferProtocol | @ | webviewProtocols.ts:27
-- | -- | --
  | async function (async) |   |  
  | e.session.protocol.registerBufferProtocol | @ | webviewProtocols.ts:19
  | apply | @ | C:\Users\adbase2\App…acks-registry.js:47
  | handleMessage | @ | C:\Users\adbase2\App…r\api\remote.js:285
  | ipcRenderer.on.args | @ | C:\Users\adbase2\App…r\api\remote.js:275
  | emit | @ | events.js:182

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. create a markdown file with images on a network share.
2. markdown file and image are in the same notwork folder.
3. open preview

Does this issue occur when all extensions are disabled?: Yes

**Comment by hadzhiyski** [comment]
I am starting working on this one
