### ISSUE TITLE
URI vs URL and going forward

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83645]
Nobody can say that I haven't tried... In fact, I have tried twice but "fixing" our uri implementation isn't possible anymore. 

Basically there are two camps - camp A correctly says that our URI has encoding/decoding issues and looses data. After fixing said issues, camp B correctly says that the URI behaviour has changed and breaks their extensions/persisted data. We are dead in the water as it seems and we need to find a way forward. 

Generally, the URI doesn't cause trouble when its used "internally", e.g. renderer talking to extension host or other pieces, but its decode/encode problems show when interacting with a 3rd player, usually a browser when clicking a link or when calling `vscode.env.openExternal`. Instead of changing the whole of our uri we should look at those problems specifically and I believe the way out is the use of the standard URL-object, e.g places that feed urls into the system, namely link detection and openExternal, should accept an URL-object in addition to our URI object. While adding overload/confusion it provides a clear separation and ends our catchup game.

**Comment by jrieken** [comment]
Work packages

* [ ] use URL for our internal link detection. This will help with the majority of cases, like this https://github.com/microsoft/vscode/issues/45515
* [ ] support URL in our API, namely openExternal and DocumentLinkProvider. This will help with custom links, like here https://github.com/microsoft/vscode/issues/79474

**Comment by DanTup** [comment]
@jrieken I just hit an issue today with dollars in a URLs becoming encoded:

```
vs.Uri.parse("http://localhost:1234/$debug").toString()
"http://localhost:1234/%24debug"
```

I'm not sure whether this is a known issue and/or covered by this one (the above mentions openExternal, but I'm not using that here, I'm just passing the URL around through some service, and one seems to fail if I give it `%24` where there was a dollar - I don't know if that's reasonable for it to do though).

**Comment by jrieken** [comment]
@mjbvz fyi - I have pushed https://github.com/microsoft/vscode/commit/a71694386db4d321ccb6cafcc9e796e320319183 which helps with links that are rendered in Webviews.

**Comment by jrieken** [comment]
To verify

* use this link https://firebasestorage.googleapis.com/v0/b/brewlangerie.appspot.com/o/products%2FzVNZkudXJyq8bPGTXUxx%2FBetterave-Sesame.jpg?alt=media&token=0b2310c4-3ea6-4207-bbde-9c3710ba0437
* have it inside an editor and click on it from the editor
* have it as rendered in markdown and click on it from the markdown preview
* have it as jsdoc-markdown hover and click on it from there
* have it in the terminal (echo ...) and click on it from there
* in ALL cases it should show a loaf of bread
