### ISSUE TITLE
Green check mark becomes black & white

### ISSUE THREAD

**Issue by generateui** [microsoft/vscode#83658]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Type windows key + .
2. Pick the green check mark ✔️
3. Enter
4. A non-green check mark appears
5. goto https://emojipedia.org/heavy-check-mark/
6. Copy the symbol
7. paste into vscode

Note the second trial to input the character results in a green check mark, the first one in a black & white variant.

**Comment by sksaifuddin** [comment]
Hello @generateui , I tried this issue and couldn't reproduce. Can you please may be provide more info on this.

**Comment by generateui** [comment]
https://imgur.com/a/fd1jMC7

**Comment by alexandrudima** [comment]
Duplicate of #32840
