### ISSUE TITLE
Problems: selecting problem should highlight problem line in editor

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8365]
Testing https://github.com/Microsoft/vscode/issues/7601:

Single clicking an item in the problems view reveals the problem in the editor.
But if the problem is only flagged with a squiggly for a single character, it is very difficult to spot the problem.

In the example below try to quickly spot the problem in the editor after the item has been selected in the problems view:

![2016-06-28_15-34-11](https://cloud.githubusercontent.com/assets/1898161/16417389/f6e0bd14-3d45-11e6-931f-c7c862322646.gif)

It would be helpful if the line of the problem could be highlighted briefly.

**Comment by sandy081** [comment]
Verification:

**Note:** Line highlight used should be same as in Find / Search / Go to line / Outline

- Single click on the problem -> Line highlight is shown.
- Toggle Problems view -> Line highlight is also toggled.
- Click inside editor -> Line highlight is removed.
- Double click on the problem -> No line highlight is shown.
- When Problems view is hidden, no line highlights from problems view are shown.
- When problem is fixed, no line highlights are shown.

**Comment by bpasero** [comment]
Verified that clicking a problem shows the line highlighted. I think the rest was part of the test plan.
