### ISSUE TITLE
icons for elixir files

### ISSUE THREAD

**Issue by cysiegel** [microsoft/vscode#83659]
Is it possible to add in default icons for elixir files (extensions .ex .exs and .eex) for the finder (file-explorer) to display in mac
I tried adding it to the info.plist file but it just created errors

Thanks

**Comment by misolori** [comment]
For file icons, we use [seti-ui](https://github.com/jesseweed/seti-ui), so if you have any requests please make them there. Once the changes are there we update our version to the latest.
