### ISSUE TITLE
remoteAuthority setting inside a .code-workspace file lacks description

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#83657]
This happens in Insiders v1.40.0

- VSCode Version: 1.39.2
- OS Version: macOS 10.15

Steps to Reproduce:
1. Create a `.code-workspace` file
2. Press `cmd+space` (or `ctrl+space`) for autocomplete and choose the `remoteAuthority` setting
3. Notice it doesn't provide a description for what this setting does.

I also can't find any information in VS Code's documentation, Google, GitHub or StackOverflow.

Does this issue occur when all extensions are disabled? Yes

**Comment by aeschli** [comment]
I will remove it. It's only used internally.

**Comment by aeschli** [comment]
To verify:

- you no longer get code assist proposals in a workspace file for `remoteAuthority`
- if added manually (`"remoteAuthority": "test+test"`) you will not geta  warning but a hover that says that's its an internal property.
