### ISSUE TITLE
“search.exclude” option cannot exclude the ".vscode" directory

### ISSUE THREAD

**Issue by liangjiancang** [microsoft/vscode#83652]
Issue Type: <b>Bug</b>

```
"search.exclude": {
    "**/.vscode": true
}
```

You can still global search files within ".vscode". Other glob patterns are OK.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by liangjiancang** [comment]
More inf:

pattern | can be excluded?
-|-
file | yes
dir/file | yes
.file | no
.dir/file | no
.dir/dir2/file | yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have any files from `.vscode` folder open when you perform search?
Can you reproduce this issue if you have all editors closed?

**Comment by liangjiancang** [comment]
> /needsMoreInfo
> 
> Do you have any files from `.vscode` folder open when you perform search?
> Can you reproduce this issue if you have all editors closed?

OK, I've figured out what had happened.

This is absolutely a **BUG**. Opening a file does not mean I want to global search sth in this file. And this is confusing for users.

**Comment by IllusionMH** [comment]
My questions were only to narrow problem scope since I wasn't able to reproduce this issue initially.

I wasn't able to find other issues tracking same problem and IMHO it is reasonable to change this behavior so I not sure why this one was closed.

@roblourens I'm not sure why opened files are not checked against exclusion/inclusion. Is it intentional, design limitation or there are no blockers to implement it?

**Comment by roblourens** [comment]
Yeah, bug: https://github.com/microsoft/vscode/issues/31819
