### ISSUE TITLE
No task detail for npm: install

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#83654]
Issue Type: <b>Bug</b>
Testing: https://github.com/microsoft/vscode/issues/83436

Steps:
1. Create a package.json with one or more npm scripts
2. Create a tasks.json and add one or more npm tasks but do not add a details field to each task
3. Execute the run tasks command
4. See that the npm scripts in package.json have a details field shown but the npm task in tasks.json does not

Expected: All npm tasks/scripts to be rendered consistently. The npm task in tasks.json should show the script as the detail field just like the ones in package.json

![image](https://user-images.githubusercontent.com/1704059/67855577-e9407280-facf-11e9-85aa-b9279f9da219.png)

VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:39:27.063Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.44
vscode-github-releases-updater|joa|0.18.0
vscode-docker|ms-|0.8.1
python|ms-|2019.10.44104
remote-containers|ms-|0.82.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.0
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.6
test-search-rg|rob|0.0.3

</details>

**Comment by alexr00** [comment]
@stevencl which of the tasks listed in your screen shot are from the tasks.json?

**Comment by stevencl** [comment]
The npm install task is the one in tasks.json:

**Comment by stevencl** [comment]
Sorry, seemed to close the issue by mistake while trying to paste a snippet from tasks.json:

        {
            "type": "npm",
            "script": "install",
            "problemMatcher": []
        }

**Comment by stevencl** [comment]
And this is in package.json:

  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "random": "do something else"
  },

**Comment by alexr00** [comment]
Thank you! There is no detail to provide for install since it's not running a script defined in package.json to pull the detail from. I figured there wasn't a good detail to show for it, but I'm all for it having a detail if there's something relevant we can put there. Is there something in particular that you want to see as the detail for the install task?

**Comment by stevencl** [comment]
I just thought it should do similar to the scripts in the package.json and show the script field?

**Comment by alexr00** [comment]
I see, so it should just show "install" as the detail.

**Comment by alexr00** [comment]
Upcoming behavior:
![image](https://user-images.githubusercontent.com/38270282/67961669-4b969180-fbfc-11e9-9c1b-0e857a058c12.png)
