### ISSUE TITLE
Native crash 

### ISSUE THREAD

**Issue by FredCoen** [microsoft/vscode#83651]
- VSCode Version: 1.39.2
- OS Version:10.14.6

Steps to Reproduce:

1.happens randomly once a day
2.

Does this issue occur when all extensions are disabled?: Yes

[crash1.txt](https://github.com/microsoft/vscode/files/3788445/crash1.txt)

**Comment by FredCoen** [comment]
No its not the same issue

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
