### ISSUE TITLE
Debugger combobox bug for cluster/forked processes (autoAttachChildProcesses)

### ISSUE THREAD

**Issue by gustavomassa** [microsoft/vscode#83665]
- OS Version: Linux Mint 19.3 64
- VSCode Version: 
![image](https://user-images.githubusercontent.com/16235598/67867145-dbb3d880-fb21-11e9-8162-087c40d48fed.png)

Debugguer combobox not showing the correct information about the process master/workers when debugging.
Debugguer combobox not stopping the process correctly, the process is still running, you can check the call stack.

How to reproduce:
1 - Debug a multi-process application that has cluster/forked processes using autoAttachChildProcesses. Stop the debug using the combo box.

![image](https://user-images.githubusercontent.com/16235598/67867009-af985780-fb21-11e9-8ad2-1c1f1d34b6e7.png)

**Comment by gustavomassa** [comment]
The DEBUG CONSOLE combo-box is not removing old child process from the list from previous debuggers:
![image](https://user-images.githubusercontent.com/16235598/68243752-f38fce80-fff1-11e9-9e51-94748a26c221.png)

**Comment by isidorn** [comment]
This should be fixed with the newer version of node debuggers since they can decide to put all the output of child cluster sessions into one debug console. However @weinand would know better if this setting is picked up by the node extension thus forwarding to him

**Comment by connor4312** [comment]
In js-debug we combine the consoles of all sessions under a single parent, so this should be fixed.
