### ISSUE TITLE
Implement interface code fix inserts above ctor

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#83662]
* Write a class and a ctor for the class.
* Try to use the implement interface quick fix.
* The methods are inserted above the ctor.

![image](https://user-images.githubusercontent.com/5047891/67865500-a611ee00-fb27-11e9-8e64-7e2016587ba5.png)

![image](https://user-images.githubusercontent.com/5047891/67865550-b88c2780-fb27-11e9-88a4-c62ccc9efcb9.png)

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/34841 to track upstrream
