### ISSUE TITLE
Dragging file tab to reorder them causes multi-second delay & Not Responding

### ISSUE THREAD

**Issue by guywood13** [microsoft/vscode#83669]
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

When trying to drag and drop file tabs that you have open into a different order it causes my system to lag for several seconds and VScode to, sometimes, show 'Not Responding' but does eventually work and move the tab.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by guywood13** [comment]
Same issue in latest insider build I'm afraid:

Version: 1.40.0-insider (system setup)
Commit: a14de79ac74f2e0e6566d3cc9410eeb7dc769cde
Date: 2019-11-02T00:39:42.595Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by bpasero** [comment]
Are you running as admin or different user?
