### ISSUE TITLE
Monaco editor page could have some revisions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8366]
ref: #8229

I like the simplicity and content of https://microsoft.github.io/monaco-editor/index.html
However I feel like the sentences could be improved by a native speaker - editor. This includes the description at https://www.npmjs.com/package/monaco-editor
So assigning this to @gregvanl so he takes a quick look at the site content.

ping @alexandrudima

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#142

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
