### ISSUE TITLE
Errors from evaluateRequest should be red in the debug console

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#83668]
If `evaluateRequest` sends an error response, it's coloured red in the Watch window, but just white in the Debug Console. I think it should also be read in the debug console so it's clear it was an error response.

![Screenshot 2019-10-30 at 3 30 46 pm](https://user-images.githubusercontent.com/1078012/67872801-64367700-fb2a-11e9-85b9-30fd365f544d.png)

![Screenshot 2019-10-30 at 3 30 52 pm](https://user-images.githubusercontent.com/1078012/67872814-67c9fe00-fb2a-11e9-9859-3d4c93441211.png)

```ts
protected evaluateRequest(response: DebugProtocol.EvaluateResponse, args: DebugProtocol.EvaluateArguments) {
	response.success = false;
	response.message = message;
	this.sendResponse(response);
}
```

**Comment by isidorn** [comment]
@DanTup you can try it out in tomorrow's vscode insiders and let us know if this is now fixed for you. Thanks!

**Comment by DanTup** [comment]
Fix LGTM, thanks!

(the directional arrows here are really nice too!)

<img width="495" alt="Screenshot 2019-12-03 at 10 33 03 am" src="https://user-images.githubusercontent.com/1078012/70043502-818eb300-15b8-11ea-84d9-09a41c8b1a09.png">

**Comment by isidorn** [comment]
Thanks, adding verified label.
