### ISSUE TITLE
Inline buttons in extensions viewlet do not work

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#83664]
Issue Type: <b>Bug</b>

Like 'Reload Required' and 'Install in <Container>'.

VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:36:49.155Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|-psn_0_3625845|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
ssh|chr|0.0.4
ghlink|dt|1.2.0
remotehub|eam|0.5.0
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.12.0
rest-client|hum|0.22.2
solidity|Jua|0.0.64
theme-karyfoundation-themes|kar|18.2.1
graphql-for-vscode|kum|1.15.1
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.82.0
remote-wsl|ms-|0.40.0
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
github-issues-prs|ms-|0.9.2
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.5.3
vscode-workspacecontains-canary|rob|0.0.2
vscode-open-in-github|sys|1.13.0
ayu|tea|0.18.0
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
"Reload Required" works for me on Linux at least.

**Comment by bpasero** [comment]
When this happens again, check for output in the devtools.

**Comment by sandy081** [comment]
Please reopen with necessary info to reproduce if it happens again.
