### ISSUE TITLE
A long running blocking UI task might trigger reconnection to kick in

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#83672]
* open a large file like `checker.ts`
* run `F1 > Developer: Force Retokenize`
* this blocks the UI thread for a time period >10s
* the reconnection dialog pops up when tokenization is finished

The disconnection check should be tweaked to run every 1s and after 10 runs to consider things disconnected rather than the current implementation where it runs once every 10s...

**Comment by bpasero** [comment]
I can open `checker.ts` just fine in todays web selfhost, but I also think that we have improved tokenization so much that this file is no longer slow or blocking when opening. Not sure if there is another way to verify this?

**Comment by alexdima** [comment]
Thanks for looking to verify. Just run `F1 > Developer: Force Retokenize` on `checker.ts`. That will block the UI thread for a while.

**Comment by bpasero** [comment]
@alexdima cool, I can tell that this dialog appears (after copying `checker.ts` 10 times into the same file):

![image](https://user-images.githubusercontent.com/900690/92233203-23c52980-eeb0-11ea-8ae6-52ce3f912189.png)

And our reconnection dialog did not ;)

**Comment by bpasero** [comment]
PS: and we did recover!
