### ISSUE TITLE
type check all in `internal` projects

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#8367]
re #8203

> Test how sufficient that strategy is.

I think it's insufficient to not do project validation for non-external module projects. We shouldn't make that decision for the user but allow to configure what to do when. Not all projects are large and type check slowly. Also we have a good queue so it might not be as impact full as we think

**Comment by dbaeumer** [comment]
Makes sense to me, but need to cycle back to the TS team

**Comment by dbaeumer** [comment]
Builder work got push out of TS 2.0 by the TS team. Moving.

**Comment by dbaeumer** [comment]
Still no builder :-(

**Comment by dbaeumer** [comment]
Closing as out of scope.
