### ISSUE TITLE
File Untitled-1 must be saved

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#83677]
Issue Type: <b>Bug</b>

When saving a project file, a new file must also be saved.

1) open project file. E.g. myfile.tsx
2) create new file and add some text. Labelled Untitled-1
3) make a change to myfile.tsx and save
4) a Save dialog for Untitled-1 will be presented.

This is annoying because it interrupts my work flow when I often just need a scratch file that I don't plan on saving. 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dfdumaresq** [comment]
I'll check. How do I disable all extensions?

**Comment by mjbvz** [comment]
[Running with extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by dfdumaresq** [comment]
The issue disappears after disabling all (70) extensions.

**Comment by dfdumaresq** [comment]
I'm looking at keyboard shortcuts and see that there are two entries for cmd%-s. One is saveAll.

![image](https://user-images.githubusercontent.com/20051/67890132-5aeae180-fb0d-11e9-88cd-9dea58ed24ec.png)
