### ISSUE TITLE
Open external terminal command should not show on web

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83689]
**Repo**
1. Using web
1. With no folder open
1. In command palette, run the `open new external terminal` command

**Bug**
This command does nothing

When you have a folder open, it instead opens the integrated terminal

**Comment by Tyriar** [comment]
I've kept it in so that users can keep their muscle memory, it just redirects to the integrated terminal. It opens an integrated terminal for me, is that not working?

**Comment by mjbvz** [comment]
ok, I see it working that way when you have a folder open. It does nothing for me when I have no folder open (http://localhost:9888) which is why I thought it was broken

**Comment by Tyriar** [comment]
@mjbvz that sounds like a bug 👍

**Comment by bpasero** [comment]
This has been fixed?

![image](https://user-images.githubusercontent.com/900690/80181541-55c2a700-8605-11ea-996f-b58742bec730.png)

**Comment by Tyriar** [comment]
Yep, the ctrl+shift+c keybindings is now applied to create new integrated terminal if on web.
