### ISSUE TITLE
Title bar style setting takes effect immediately

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83682]
- Set title bar to "native"
- Restart, then back to "custom"
- Get two title bars

![image](https://user-images.githubusercontent.com/323878/67889879-e2842080-fb0c-11e9-84fc-dc59c55b648e.png)

If I go the other way, then there is no title bar, so no X button which could confuse some people. In stable it doesn't take effect until vscode is restarted

**Comment by sbatten** [comment]
I actually can't reproduce this in today's insiders, @roblourens can you verify?

**Comment by roblourens** [comment]
Never mind, I probably hadn't updated Insiders recently on that machine.
