### ISSUE TITLE
Add snippet command to get author

### ISSUE THREAD

**Issue by GlenNicholls** [microsoft/vscode#83688]
Currently, VS code does not have any snippets to get the author. Currently theres simple variables, time/date, and comments. However, when making new files and inserting my companies disclaimer, we are required to fill in the author. In slick edit this is automatic with `%/a`, but does not exist in VS code. 

I would like something like this in my language.json:

```
...
"body": ["Author : $GET_USER"],
...
```

This will produce, for me, the following:

```
Author : Glen.Nicholls
```

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/64599
