### ISSUE TITLE
Killing Terminal while running Python

### ISSUE THREAD

**Issue by exumaaa** [microsoft/vscode#83687]
Issue Type: <b>Performance Issue</b>

The Applications lags when I kill the terminal while running a loop in python. A few updates ago this didn't happen.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	 11040	code main
    1	    66	  2664	   window (Issue Reporter)
    0	   194	  4780	   window (help.py - emilia.py - Visual Studio Code)
    0	    15	  1736	     watcherService 
    0	    11	 19592	       console-window-host (Windows internal process)
    0	    38	 16348	     searchService
    0	   122	 19596	     extensionHost
    0	   260	 20164	       c:\Users\Dominik\.vscode\extensions\ms-python.python-2019.10.44104\languageServer.0.4.71\Microsoft.Python.LanguageServer.exe
    0	    11	 16036	         console-window-host (Windows internal process)
    0	   113	  9380	   gpu-process
    0	    14	 18496	   electron-crash-reporter
    0	    69	 19448	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (help.py - emilia.py - Visual Studio Code)
|    Folder (emilia.py): 23 files
|      File types: pyc(8) py(5) 63062832(1) 67380552(1) 62202368(1)
|                  67379712(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
stack-overflow-view|4tr|0.1.1
beautify|Hoo|1.5.0
discord-vscode|icr|3.8.3
vscode-github|Kni|0.30.3
python|ms-|2019.10.44104
java|red|0.52.0
LiveServer|rit|5.6.1
vscode-autohotkey|sle|0.2.2
vscodeintellicode|Vis|1.2.0
vscode-swift-development-environment|vkn|2.8.1
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you explain a little more what lag means?

**Comment by exumaaa** [comment]
With lag, I mean that Vscode is not responding. I can't click on buttons, open menus and the cursor does not update. The lag occurs every time I kill the console, not only when I kill a loop in python. I thought it was only when I kill a loop because the problem occurred first when I killed one. The lag occurs every time I kill the terminal, even if I have nothing running, just Powershell waiting for commands.
