### ISSUE TITLE
No margin between Extensions viewlet and the editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8368]
No margin between Extensions viewlet and the editor. When selecting an extension, selection outline is almost overlapping with content in the editor
![screen shot 2016-06-28 at 3 49 07 pm](https://cloud.githubusercontent.com/assets/10746682/16417864/e012a618-3d47-11e6-941f-ffd7c242084f.png)

**Comment by isidorn** [comment]
Dup of #8251
