### ISSUE TITLE
syntax highlighting for diff in Markdown codeblock

### ISSUE THREAD

**Issue by zachvalenta** [microsoft/vscode#83683]
At present, code blocks have syntax highlighting in both the editor and in Markdown preview. The exact colors aren't a 1-to-1 match, but it's more or less the same.

* editor
![Screen Shot 2019-10-30 at 2 59 29 PM](https://user-images.githubusercontent.com/11388735/67889949-2cc5cb80-fb26-11e9-8e50-a7147db8d27d.png)

* preview
![Screen Shot 2019-10-30 at 2 59 36 PM](https://user-images.githubusercontent.com/11388735/67889951-2cc5cb80-fb26-11e9-9e45-2ad2f8925692.png)

For `diff` code blocks, however, the *only* highlighting comes in Markdown preview. 

* editor
![Screen Shot 2019-10-30 at 3 01 59 PM](https://user-images.githubusercontent.com/11388735/67890027-49fa9a00-fb26-11e9-963a-e2a2a0468466.png)

* preview
![Screen Shot 2019-10-30 at 3 02 11 PM](https://user-images.githubusercontent.com/11388735/67890028-49fa9a00-fb26-11e9-957b-72df86b7562c.png)

Be nice if this highlighting were also displayed in the editor.

**Comment by mjbvz** [comment]
Works for me in VS Code and in the current insiders build:

![Screen Shot 2019-10-30 at 4 47 42 PM](https://user-images.githubusercontent.com/12821956/67907437-15daa580-fb35-11e9-82f2-c87830884a16.png)

This is likely theme specific. What theme are you using?

/needsMoreInfo

**Comment by zachvalenta** [comment]
Yep, it is the theme :/ 

sorry for the bother!
