### ISSUE TITLE
Add "Most Recently Used" Tab Sorting

### ISSUE THREAD

**Issue by mbianucci** [microsoft/vscode#83692]
I would love an option to right click on my list of tabs and see a "Sort by Most Recently Used" option. This would then sort my tabs from most recently used on the left side, to least recently used on the right end. Then I could easily close a ton of tabs that I haven't used recently by right clicking on a sufficiently unused tab, and click "Close to the Right."

This would really help with my organization, as I'm a serial non-closer when working until I'm at the point of frustration trying to find the files I'm using most often in the list!

**Comment by JTensai** [comment]
Would also be great to have default sort options for tabs (Alphabetical, Tree based, recently used, etc.)
