### ISSUE TITLE
[Firefox] Firefox errors on the markdown's unicode regular expression for word definitions 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83698]
**Repo**
1. Using firefox
1. Open a markdown file

**Bug**
In dev tools, see:

```
invalid identity escape in regular expression: _reviveRegExp@http://localhost:9888/static/out/vs/workbench/api/browser/mainThreadLanguageFeatures.js:460:20
$setLanguageConfiguration@http://localhost:9888/static/out/vs/workbench/api/browser/mainThreadLanguageFeatures.js:485:88
_doInvokeHandler@http://localhost:9888/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:331:27
_invokeHandler@http://localhost:9888/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:316:45
_receiveRequest@http://localhost:9888/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32
_receiveOneMessage@http://localhost:9888/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26
RPCProtocol/<@http://localhost:9888/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52
fire@http://localhost:9888/static/out/vs/base/common/event.js:458:38
```

**Comment by rebornix** [comment]
It's already being tracked in Firefox bugzilla as it doesn't implement RegExp Unicode Property Escapes yet https://bugzilla.mozilla.org/show_bug.cgi?id=1361876

https://github.com/microsoft/vscode/blob/9b34464c6657b68322efa360f18a58ab6abcdda5/src/vs/base/common/strings.ts#L239-L244

I'm not a fan of having special logic for Firefox to stop unicode escaping and creating regex without `u` flag. The error is thrown from word pattern regex parsing and as I didn't see any misbehavior of word related operations in Markdown files, I'll recommend to put this issue in backlog and ask for Firefox to catch up.

**Comment by connorshea** [comment]
Looks like this is coming in Firefox 78 :) https://bugzilla.mozilla.org/show_bug.cgi?id=1361876#c16

**Comment by mjbvz** [comment]
Confirmed this is fixed in the latest Firefox release
