### ISSUE TITLE
Search: did we loose the upper limit for search results?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8369]
Refs: https://github.com/Microsoft/vscode/issues/8184

When I now search for "e" in our workspace I seem to get all the results back? I think as long as I am not replacing, it is fine to cut the results as we used to.

**Comment by bpasero** [comment]
Marking as important because even for replace I see the entire UI freezing and things getting slow. Imho as long as we are not fit for this in the UI we should maybe keep the 2000er limit alive even for replace.

**Comment by sandy081** [comment]
Agreed.
