### ISSUE TITLE
[Safari] Cannot type in setting editor after switching back to it

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83696]
**Repo**
1. Using safari
1. Open a workspace and open a text file
1. Now open the settings editor
1. Switch back to the text file
1. Switch back to settings editor.
1. Try typing in settings search text area

**Bug**
Nothing happens

**Comment by mjbvz** [comment]
Potentially related to #83599

This does not happen in Chrome or Firefox

**Comment by mjbvz** [comment]
Not 100% reliable repo for me. If you don't see it happen the first time, try switching back and forth to the text editor a few times and typing in it and in the settings editor

**Comment by roblourens** [comment]
This is also a monaco instance, someone mentioned similar issues in Slack

**Comment by bpasero** [comment]
@mjbvz @roblourens can you try to reproduce after commenting out this rule: 

https://github.com/microsoft/vscode/blob/14e2178b7f204c99a860cd92425408be058f45a2/src/vs/workbench/browser/media/style.css#L40

**Comment by mjbvz** [comment]
@bpasero Commenting out that line seems to have fixed the issue for me

**Comment by bpasero** [comment]
@mjbvz what are you doing different from me?

![before](https://user-images.githubusercontent.com/900690/68011841-a83f8e00-fc88-11e9-91a0-ca34575d0a5d.gif)

@roblourens what is the purpose of having a full editor in the search input field?

![image](https://user-images.githubusercontent.com/900690/68011960-f3f23780-fc88-11e9-89a8-1e5d0b4628b5.png)

**Comment by roblourens** [comment]
Suggestions for `@`

**Comment by bpasero** [comment]
Still waiting for steps from @mjbvz or you

**Comment by mjbvz** [comment]
Not sure. Try also typing in the text editor. Like I said, the error goes away when I comment out that line of css however

**Comment by bpasero** [comment]
@mjbvz when this happens again, can you please open devtools and see if the CSS rule for the editor in the settings editor has `user-select: text`? Specifically this one: `.monaco-workbench .monaco-editor .view-lines`

**Comment by bpasero** [comment]
@mjbvz ping

**Comment by mjbvz** [comment]
Same root cause as #83599 I believe
