### ISSUE TITLE
"New file" / "New folder" on file context menu

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#83693]
There is no option to "create a new file here" when right clicking in the tree view in the project root:

![image](https://user-images.githubusercontent.com/490562/67902259-abc20f00-fbcd-11e9-8417-e350cb37a498.png)

Your only option is to select "new file relative to project root" and then wait for folders to load and go through the obnoxious dialogs to create a simple blank new file in the root.

When right clicking on a folder, there is the obvious option:

![image](https://user-images.githubusercontent.com/490562/67902336-d1e7af00-fbcd-11e9-9352-0bff4b9485ac.png)

Can this option be available anywhere you right click in the tree view please? Regardless of whether I click on a folder or a file in a folder, having the new file command there is handy.

So right clicking on a file and selecting add new file, will obviously add it the the same folder.

Atom operates this way too and it's a good approach imo, keeping it simple and consistent to add files and not having to worry about right clicking exactly on the folder.

**Comment by adamreisnz** [comment]
This is really not an extension candidate.

**Comment by isidorn** [comment]
Ok, we can reopen and leave this as a feature request

**Comment by adamreisnz** [comment]
Thank you 👍

**Comment by adamreisnz** [comment]
Could you point me in the direction of where I might find this behaviour and I'll have a crack at making a PR for it.

**Comment by isidorn** [comment]
Even though this is open as a feature request we do not want to incoporate this in the vscode code right now. We might change that in the future, but for now we think that using an extension is the proper way to tackle this issue.

**Comment by adamreisnz** [comment]
Can you explain why please?

**Comment by isidorn** [comment]
Context menus become too big, vscode is a minimalistic code editor we try not to add bloat.

**Comment by eamodio** [comment]
I hit this often myself -- right-clicking on a file trying to add a new one in the same parent folder. I think we should add this, but maybe do it with a submenu -- so just one `New` entry, that would open to both New File and New Folder -- and we can use the same for Folders too.

**Comment by sombriks** [comment]
so anyone knows an extension for this need?

**Comment by BartaG512** [comment]
> so anyone knows an extension for this need?

I think it can do it https://marketplace.visualstudio.com/items?itemName=wenfang.faster-new

**Comment by wenfangdu** [comment]
I created [Faster New File And Folder](https://marketplace.visualstudio.com/items?itemName=wenfang.faster-new) specifically for this, please give it a try.

**Comment by adamreisnz** [comment]
@wenfangdu Awesome!

**Comment by fofr** [comment]
Thank you @wenfangdu. This was driving me mad.
