### ISSUE TITLE
Option to hide/disable "Commit all ..."

### ISSUE THREAD

**Issue by AndrewKvalheim** [microsoft/vscode#83707]
> Before you create a new issue, please do a search in open issues to see if the issue or feature request has already been filed.

I found #76510.

> If you find your issue already exists, make relevant comments and add your reaction.

I can't because it's locked. I would have upvoted the issue and replied in-thread:

```markdown
No, `Undo Last Commit` doesn't undo `Commit All…`. It 1) doesn't restore the
index and 2) doesn't undo amendments.
```

> If you believe the bot got something wrong, please open a new issue and let us know.

The issue was closed based on a misunderstanding, someone immediately replied to correct the misunderstanding, and then the thread was locked without anyone addressing the correction.

**Comment by joaomoreno** [comment]
@AndrewKvalheim Care to submit a PR?

**Comment by AndrewKvalheim** [comment]
Not any time soon; I'm unfamiliar with the codebase and regardless I think there's more discussion to be had before implementing anything. For example:

  - Could the problem be avoided in the first place by a simple UI change such as rearranging menu items?
  - Instead of removing the menu item, would a confirmation step suffice?
  - Should the behavior change depending on the status of the index?
  - In "stage all and commit", is the dangerous part the "stage *all*" or the "stage *and commit*"?

All I wanted to do now was upvote the issue and maybe step the discussion forward. This is a low priority so it might be a month or more before I revisit it again. When that happens it would be helpful to not have to create yet another new issue just to add the next comment in the discussion.

**Comment by aterenin** [comment]
+1. I do not ever want to "commit all" in my workflow, and have clicked this by accident multiple times before.
