### ISSUE TITLE
Web: native dropdown on iPadOS looks verbose on iPadOS

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83708]
Re #83296

* Run self hosting bits in iPadOS
* Click Debugger options and Terminal selector to trigger native dropdown

![image](https://user-images.githubusercontent.com/876920/67908793-145fac00-fb3a-11e9-8710-775f8773f3ac.png)

![image](https://user-images.githubusercontent.com/876920/67909457-80431400-fb3c-11e9-9fc9-f9744c615a66.png)

The separator looks weird especially. We may want to use custom menu on iOS/iPadOS.

**Comment by bpasero** [comment]
Should this merge into https://github.com/microsoft/vscode/issues/83556 ?
