### ISSUE TITLE
[Firefox] Will-change memory consumption is too high

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83700]
**Repo**
1. Using Firefox
1. Open the user settings editor

**Bug**
In devtools, see the warning:

```
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1761280 px). Occurrences of will-change over the budget will be ignored.
```

This seems to only happen when I open the user settings editor

**Comment by roblourens** [comment]
wat

**Comment by cmcarey** [comment]
I think this is an issue with Monaco.

I also get the issue when I have a site with Monaco (and only that) open in Firefox.

> Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (36366 px). Occurrences of will-change over the budget will be ignored.

**Comment by rebornix** [comment]
🤷🏻‍♂️

**Comment by rebornix** [comment]
Per https://developer.mozilla.org/en-US/docs/Web/CSS/will-change,

>  So it is a good practice to switch will-change on and off using script code before and after the change occurs.

We can probably do that when scrolling in the list view but I'm not confident that how that will affect browsers creating new layers.

**Comment by joaomoreno** [comment]
This was _fixed_ yesterday accidentally by @alexandrudima  https://github.com/microsoft/vscode/commit/c6388baf2b155f4e90fd8bf58167a7511395f27e#diff-bc80460db7fa6e585859804d50b57039R237
