### ISSUE TITLE
Incorrect syntax colouring of YAML multi-line values containing colons

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#83709]
Issue Type: <b>Bug</b>

_Note: This was originally reported on the Kubernetes extension at https://github.com/Azure/vscode-kubernetes-tools/issues/639, and traced upstream to the Red Hat YAML extension at https://github.com/redhat-developer/vscode-yaml/issues/242, but it looks like it affects all YAML files even without those extensions being installed, and appears to be down to the VS Code built-in YAML highlighter at https://github.com/microsoft/vscode/blob/master/extensions/yaml/syntaxes/yaml.tmLanguage.json._

The syntax highlighting of multi-line values containing colon characters doesn't look right.  For example, consider the following YAML:

```yaml
foo:
  bar: |
    set_header 'Server: '
    set_header 'Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS'
    set_header 'Access-Control-Allow-Origin: https://snip'
```

Here's how this gets highlighted:

![image](https://user-images.githubusercontent.com/865538/67818060-c4bab980-fb14-11e9-8755-2c05016a892f.png)

Note that the first line of the multiline value gets 'key' colouring (blue) up to the colon, then the closing quote and start of next line get 'value" (brown) colouring until the next quote, then key again until the colon, then value...

If I remove the colons, everything in the multi-line value is correctly coloured brown.

I tried this in an online YAML parser and it treated the multi-line section as a single value, so I think this should be valid - the colons shouldn't be being handled as key-value separators.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.1
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
vscode-peacock|joh|3.1.6
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.6
remote-wsl|ms-|0.39.9
azure-account|ms-|0.8.6
azurerm-vscode-tools|msa|0.8.0
vscode-yaml|red|0.5.3

</details>

**Comment by alexr00** [comment]
Looks like this is the upstream issue https://github.com/textmate/yaml.tmbundle/issues/17

**Comment by itowlson** [comment]
The trouble with closing this as an upstream issue is that the last comment in that upstream issue is them requesting help from the VS Code team: "Since @infininight has kindly explained the issue in a very detailed way, maybe someone familiar with VSCode would be willing to take a look at it :) It seems we're stuck without some help. Sorry for tagging you out of the blue @alexandrudima @bpasero, is there a chance you could take a quick look at this issue (or tag someone who could)? Would be very much appreciated!"  So it sounds like Code is waiting for a fix from upstream, while upstream is appealing to Code to do the fix!

How do we break this circle?

**Comment by alexr00** [comment]
From what I understand from https://github.com/textmate/yaml.tmbundle/issues/17#issuecomment-418602300, this is a limitation of using textmate. There's not much to be done about that other than maybe https://github.com/microsoft/vscode/issues/77140 will help.
