### ISSUE TITLE
In product release notes could use some styling polish

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83703]
## Problem
Our in product release notes could use some styling polish. It would be nicer if they were closer in style to what we show on our website

Here are some quick thoughts on the main things that could be improved:

* No maximum width. This means that a single of text can stretch for hundreds of characters
* Images can be extremely large
* ~No outline of the document~
* Extremely thin header fonts used on desktop MacOS VS Code 
* ~No follow up section (the `Tweet this link` area from web)~

*(update to remove items that were not delivered this iteration. These can be split into separate feature requests)*

**Comment by mjbvz** [comment]
Pushed max width fix

My proposal for outline is that instead of adding a table of contents like our settings page has, we reuse our outline, document nav, and breadcrumbs views

**Comment by misolori** [comment]
My vote would be to make the webviews on the extension page left-aligned since the rest of the content + tabs is left-aligned and looks odd centered: 

![image](https://user-images.githubusercontent.com/35271042/68163638-d7b3fc00-ff0f-11e9-9ed6-7f1f816c8a98.png)

**Comment by mjbvz** [comment]
Closing this for verification. This iteration we only did some minor styling fixes and added a max width. Adding a proper outline would be difficult and should be tracked by a separate item
