### ISSUE TITLE
Cannot distinguish where focus is when `terminal.integrated.cursorStyle` is not block

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#83706]
Issue Type: <b>Bug</b>

Follow up to https://github.com/microsoft/vscode/issues/67410

1. Set `"terminal.integrated.cursorStyle": "line"` and make sure `terminal.integrated.cursorBlinking` is false

The cursor is always rendered as a line in the terminal, and without blinking, it is unclear when it actually has focus

VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:36:49.155Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
As designed, that was my argument for being resistant to the feature in the first place. I think most people will use blink when they use other cursor styles so it's not a big deal.
