### ISSUE TITLE
Weird things happen when I debug + preLaunchTask

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#83705]
Trying to verify https://github.com/microsoft/vscode/issues/82076

- Followed the setup steps in the issue, installed Eric's webpack problem matcher extension
- I got into a state where the task was running, but starting a debug session didn't work, it just hung at the debug viewlet progress bar
- I kill the task and the pending debug session
- I tried to start it again, and nothing happened
- I looked around for logs, didn't see any errors
- Then suddenly I had 3 instances of the same task running, and 3 instances of the debug session
- Killed them all, and the call stack still showed two debug sessions (but there was no debug viewlet)

![image](https://user-images.githubusercontent.com/323878/67905195-d5c3f480-fb2d-11e9-83d3-e9e798573900.png)

![image](https://user-images.githubusercontent.com/323878/67905338-3eab6c80-fb2e-11e9-94ee-2e9217fbfa7c.png)

**Comment by alexr00** [comment]
I can't get the many instances of the task running, but I do see the debug session starting even after I cancel it. 
Steps:
- Start a debug config with a slow background prelaunch task
- Wait for the task to start, but not finish
- Cancel the debug session before the task finishes, but let the task keep running
- When the task completes the debug starts even though I cancelled it.

**Comment by isidorn** [comment]
I think we always had this behavior. Unfortunetly I will not have time to tackle this in the endgame. Thus moving to next milestone
Here's a code poitner in case somebody is interested in investigating in the meantime
https://github.com/Microsoft/vscode/blob/721f2274694681dadd860dc2a6e5c986f869b6df/src/vs/workbench/contrib/debug/browser/debugService.ts#L768

**Comment by isidorn** [comment]
I was able to reproduce what @alexr00 mentioned [here](https://github.com/microsoft/vscode/issues/83705#issuecomment-548314731)
I have pushed a fix for this particular behavior with follow up work captured here https://github.com/microsoft/vscode/issues/87638
