### ISSUE TITLE
Web: Listen to pointer events for assistive touch devices

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83719]
Re #83296

Currently we listen to `mousemove/out/enter/` events in quite a few places (global, list view, editor, etc) but we never listen to pointer events.

On iOS/iPadOS, pointer events are triggered by Pencil, Mouse or Touch and PointerEvent is subclass of MouseEvent so at least we can listen to PointerEvents for iOS/iPadOS.

We can also look into how other browsers behave with pointer events on devices with touch screens and see if this logic can be generic.

**Comment by bpasero** [comment]
Drag and drop works really well for me in Chrome on iPadOS. So they must be emulating the proper events that it works for us.

**Comment by rebornix** [comment]
Good to know that, then we can cross compare the events emitted from Safari and Chrome to achieve the same behavior.
