### ISSUE TITLE
Replace: is very slow for many results

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8371]
Refs: https://github.com/Microsoft/vscode/issues/8184

In selfhost, search for `editor` and replace with something. Run a profile while doing the operation. When looking at the profile, I see half of the time spend in `Tokenizer.tokenize`:

![image](https://cloud.githubusercontent.com/assets/900690/16418386/e27637ce-3d49-11e6-99ab-731d7c1b3fc3.png)

[CPU-20160628T160331.cpuprofile.zip](https://github.com/Microsoft/vscode/files/337183/CPU-20160628T160331.cpuprofile.zip)

I am not sure why we need to run the tokenize even though we are not even opening the editors?

**Comment by sandy081** [comment]
Underlying bulk edit is opening models and updating models so probably @jrieken @alexandrudima would have some insight.

**Comment by jrieken** [comment]
Yeah, seems like we start to tokenise the model... @bpasero it's not that you open editors for them, right?

**Comment by bpasero** [comment]
@jrieken yeah I was thinking the same and quickly disabled opening of editors and still found the same issue. In the future editors will open in the background anyways, so I would not assume any tokenization work from happening even when they open.

**Comment by jrieken** [comment]
> In the future editors will open in the background anyways,

Which means at most three models will be attached to an editor but not the others. Pretty sure something is wrong with the model that makes it tokenise eagerly

**Comment by jrieken** [comment]
Yeah, [`TextModelWithMarker`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModelWithMarkers.ts#L50) set itself to `autoTokenize` which is cause this...
