### ISSUE TITLE
Web: Workbench doesn't respond to window change on iPadOS

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83717]
Re #83296

* Run self hosting bits in iPadOS
* Split the window
* The workbench doesn't always relayout

![image](https://user-images.githubusercontent.com/876920/67909363-2e01f300-fb3c-11e9-8b76-bf2bbcdf4404.png)

**Comment by bpasero** [comment]
That sounds more like an upstream bug to me. We simply listen to the `RESIZE` event on the window. I am not sure why that would not fire in this case.

**Comment by bpasero** [comment]
I cannot reproduce. I tried with putting calendar to the side and the workbench sized accordingly.

**Comment by rebornix** [comment]
@bpasero did yo then try to drag the Sash between browser and calendar to resize them ?

**Comment by bpasero** [comment]
@rebornix sure, that worked fine for me
