### ISSUE TITLE
Web: Toggle Full Screen should not be registered on mobile

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83712]
Re #83296

As title, this command does nothing in PWA mode so we'd better hide it.

**Comment by bpasero** [comment]
@rebornix I am using that command all the time, why do you say we should remove it?

**Comment by rebornix** [comment]
oh sorry, I missed the context. I mean PWA on Mobile. At this moment, PWA on mobile (say iOS/iPadOS) is Full Screen by nature.

**Comment by bpasero** [comment]
Yeah that makes sense I guess.

**Comment by isidorn** [comment]
When I trigger the `Toggle Full Screen ` from a safari on iPad the whole screen transitions to full screen and immediatly transitions out of it. So there is no effect. I would expect that Safari might block this but why is there a transition for a split of a second? Might you be aware of some limitations here?

Bonus: it would be very cool if we were able to hide the safari toolbar programmatically, but that is probably not possible.

**Comment by bpasero** [comment]
Isn't this done?

https://github.com/microsoft/vscode/blob/68fa627d9aafda0c9722e5d8af40bf8789d4467e/src/vs/workbench/browser/actions/windowActions.ts#L300

**Comment by isidorn** [comment]
Yeah, I just verified on my iPad that I do not have the toggle full screen command. Let's close .
