### ISSUE TITLE
Conflict detected editor.action.quickCommand

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8372]
Ref: #8229

Open https://microsoft.github.io/monaco-editor/index.html in IE11 notice conflicts in developer console

![screen shot 2016-06-28 at 16 04 31](https://cloud.githubusercontent.com/assets/1926584/16418473/40f12322-3d4a-11e6-91be-ae725a44107a.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#143

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
