### ISSUE TITLE
Web: can't change opacity and hue in Color Picker on iPadOS

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83721]
#83296

* Run self hosting bits in iPadOS
* Can't dnd in Color Picker then we can't change the hue or opacity.

This might be a duplicate of #83719 but this one is talking about particular feature.

**Comment by sbatten** [comment]
This is fixed when using the Apple Pencil or pointing device but touch is still not supported. Additionally, the scroll bar in the hover widget is not usable with the pencil but the pencil is required to open it. Strange, but the main issue is fixed.
