### ISSUE TITLE
Can't get ctrl + shift + alt key even Intel Graphics doesn't  capture the hotkey.

### ISSUE THREAD

**Issue by SainoNamkho** [microsoft/vscode#83728]
- VSCode Version: 1.39.2
- OS Version: Windows 10 1903 18363.356

Steps to Reproduce:

1. Close shortcut in intel graphics control panel
2. Programs such as [keycastow](http://web.archive.org/web/20170510080951/https://brookhong.github.io/2014/04/28/keycast-on-windows.html) can grab the keystroke but VSCode cannot.
![screenshot](https://user-images.githubusercontent.com/23036788/67916560-10329d80-fbd1-11e9-8170-4213e91b6dd7.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@SainoNamkho I think software such as the keycast one listen to keyboard events globally (outside of a window). VS Code listens to the keyboard events that are delivered by the OS to its window. 

What does VS Code detect when you press the desired key combination? 
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
