### ISSUE TITLE
Is there a way to use electron.remote methods?

### ISSUE THREAD

**Issue by lopugit** [microsoft/vscode#83724]
They all seem to be blocked for security reasons.

Is there any way to use them, through vscode extensions maybe? Loading securely?

**Comment by mjbvz** [comment]
No, extensions cannot use them  and we are actively moving away from using them anywhere in VS Code

**Comment by lopugit** [comment]
> No, extensions cannot use them and we are actively moving away from using them anywhere in VS Code

why? moddability is core to open-source.

You just end up with hacks like injecting into main.js of vscode .. ?
