### ISSUE TITLE
iPadOS: Support drag and drop via touch

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#83720]
#83296 

* Run self hosting bits in iPadOS
* Try to drag and drop in File Explorer or in the editor, no luck

This might be a duplicate of https://github.com/microsoft/vscode/issues/83719 but this one is talking about particular feature.

**Comment by bpasero** [comment]
I think in general we lack support for DND with touch gestures. Not sure that is limited to iPad.

**Comment by bpasero** [comment]
Btw: drag and drop works really well for me in Chrome on iPadOS. So they must be emulating the proper events that it works for us.

**Comment by HundredYearRain** [comment]
How use it in iPadOS, is there any doc?

**Comment by bpasero** [comment]
See https://code.visualstudio.com/docs/remote/vsonline
