### ISSUE TITLE
VSCode can't correctly parse .tsx file with React hooks 

### ISSUE THREAD

**Issue by woohling** [microsoft/vscode#83725]
- VSCode Version:  1.39.2
- OS Version: MacOS 10.14.6

It seems that VSCode can't correctly parse my .tsx file syntax. We're using React hooks and EmtionCSS, other than that, I don't see anything packages out of ordinary that we're using. And this project is built on create-react-app. We're also using prettier as code formatter. 

Steps to Reproduce:
1. using create-react-app as boilerplate to start a project
2. create a file using emotionCSS and react hooks component in a .tsx file.

Does this issue occur when all extensions are disabled?: Yes

here's the screenshot for your info. 
![Xnip2019-10-31_10-47-22](https://user-images.githubusercontent.com/10751371/67914875-62bd8b00-fbcc-11e9-93f2-b0d7650fddd4.jpg)

BTW, my coworkers are using windows, and the problem won't show up

**Comment by mjbvz** [comment]
What is the error? Does still happen with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by woohling** [comment]
still happened with all extensions disabled, and with both of my Mac laptops.
There're tons of error msg displayed. Simply put, just like you write the HTML template in a JS file and the AST tree can't parse it. 

Here's one small snippet of the error msg. 

![image](https://user-images.githubusercontent.com/10751371/67925655-ee481380-fbee-11e9-86cf-15f2f2480c11.png)

**Comment by woohling** [comment]
I created a little demo and reproduce this scenario, link is: https://github.com/woohling/vscode-issue-demo/tree/master/src

Hope you find it useful, and below is the screenshot
![image](https://user-images.githubusercontent.com/10751371/67929752-0a50b280-fbf9-11e9-8ab2-540078a09147.png)

**Comment by mjbvz** [comment]
Thanks for the example code. I can't reproduce the issue in the current insiders build however. What is the [language mode](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) of the file?

**Comment by woohling** [comment]
oh, Thanks @mjbvz, the auto language detection for this file is typescript. I changed it to typescript react, and everything works just fine.
Thank u :)
