### ISSUE TITLE
Add a one-click cancel syntax highlighting and auto completion

### ISSUE THREAD

**Issue by zhangddjs** [microsoft/vscode#83738]
## 🚀 Feature Proposal

As title, can you add two switchs in the settings or anywhere else to close/open all syntax highlighting and close/open all auto-completion? Thank you.

**Comment by zhangddjs** [comment]
That issue 增加一键取消语法高亮和自动补全 (#83499) has been closed because the description is not in English. So I create an English version issue, so they look like duplicate but they are not duplicate.

**Comment by mjbvz** [comment]
Just switch the language mode to `plain text`. It has no highlighting and only word based suggestions (which you can disable by setting `"editor.wordBasedSuggestions": false`)

**Comment by zhangddjs** [comment]
too much help for me, Thank you.
