### ISSUE TITLE
Web: Dragging multiple files when some will conflict is hard/impossible to know which one(s) is conflicting

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83736]
- VSCode Version: 1.40.0-insider @ b7b2184
- OS Version: Windows 10 (1903)

Dragging multiple files when there are name conflicts in the set of files you are dragging, you will get a confirmation dialog for each of them 👍, but there isn't any way to tell which file conflicted 😢. At first I thought the confirmation dialog wasn't working, but in reality it was, I was just cancelling each of the conflicts one by one. We probably should add the file name in that confirmation dialog.

Steps to Reproduce:

1. Drag a set files from the desktop into the explorer where at least some of the file will conflict because they have the same name as existing files
1. Currently you will see a confirmation dialog for each conflicting file, but it doesn't contain any information in the dialog to know which file it is for

Does this issue occur when all extensions are disabled?: Yes

Ref: #83225

**Comment by isidorn** [comment]
Thanks for filing this.
Please try it out in tomorrow's vscode insiders and let me know if it behaves good now for you.

**Comment by alexr00** [comment]
I tried dragging 4 different files with the same name as files in my open folder from my desktop. I only got two dialogs asking if I wanted to replace It ignored half of the files. Tested with Edge and Firefox.
