### ISSUE TITLE
Merge Conflict: Compair changes(code lens) opens a different tab/panel. should replace the existing tab.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#83737]
Issue Type: <b>Feature Request</b>

Problem statement: Every time merge conflict -> compare change is clicked, the window is split horizontally in 2 and the compare change part is opened in the bottom half.
if the step is repeated the window is split in half and the second merge conflict compare changes is opened in it.

expected: 
Every time the compare changes is clicked the resulting compare tab should open in same split tab.
in my case its a vertical split. it should not open a different split.
```
===========
conlict file.ts__________________________________________________________________________
compare changes
<!-- this is panel 1-->

--------------------------------------Horizantal split------------------------------------------
=====================
conflict file -> conflict file (acdsdf)_____________________________________________________

<!-- new conflict should always open in this split pane  (panel 2)-->
<!-- it can be a second tab or can replace the existing compare changes tab opened. -->


```
VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:39:27.063Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

**Comment by rebornix** [comment]
Currently this is limited to the API we have for opening editors.

**Comment by rebornix** [comment]
We now have a new merge editor which can be turned on by git.mergeEditor
