### ISSUE TITLE
Allow more specific trusted domains rule

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#83731]
1.40.0-insider
31f577ec88dc96ad2028699fb597b19022224b46
x64

At some point I had chosen "Trust all domain".
When I now edit the trusted domains using `Manage Trusted Domains` and remove the `*` from the list there is no effect. I can still access all domains without any problem. 

In stable, this works as expected.

**Comment by octref** [comment]
I'm on the same commit.

Version: 1.40.0-insider
Commit: 31f577ec88dc96ad2028699fb597b19022224b46
Date: 2019-10-30T05:36:49.155Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

And this does not reproduce for me.

What I tried:
- Run `Manage Trusted Domains`
- Open an untrusted link in markdown by Cmd+Click

Where in the workbench is the protected link? Also, did you run save in the "Manage Trusted Domains" tab? If not it won't persist the rules.

**Comment by octref** [comment]
What we learned after chatting:

- Currently, a rule like `https://foo.com/bar` allows ALL links on `https://foo.com`
- For next month, we should start allowing rules more specific than a domain, so `https://foo.com/bar` would make below accessible:
    - `https://foo.com/bar`
    - `https://foo.com/bar/baz`

**Comment by octref** [comment]
Verifier:

- Add rules such as `https://foo.com/bar` with command `Manage Trusted Domains`
- Make sure https://foo.com/bar, https://foo.com/bar/baz are accessible
- Make sure https://foo.com/baz, https://foo.com/bar2 etc are unaccessible
