### ISSUE TITLE
source control git bugs

### ISSUE THREAD

**Issue by 17Edwin** [microsoft/vscode#83730]
Issue Type: <b>Bug</b>

source control git: more actions button when i click its not absolutely open for me, when mouse over it disapper

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by dhairyanadapara** [comment]
Hey @17Edwin,  I can't re produce same in insider build
![ss](https://user-images.githubusercontent.com/19250981/67931935-ee451500-fbe8-11e9-8f05-79c8f992f593.png)
can you please verify this issue in insider build. Please correct me if I'm in wrong direction to understand the issue. Thanks :)

**Comment by 17Edwin** [comment]
[image: image.png]
i think because of my screen size, its not above the more actions when i
click, so i auto pull rebase although i dont click that option.

**Comment by joaomoreno** [comment]
I can't see your screenshot if you attach it via email, please post it on Github.

**Comment by dhairyanadapara** [comment]
I think we should add a scrollbar to tall menus.

**Comment by 17Edwin** [comment]
yep, i think so, be the way, thanks for support me. ^^
