### ISSUE TITLE
"unable to verify the first certificate" error when issuing https request

### ISSUE THREAD

**Issue by blackchoey** [microsoft/vscode#83732]
This is an issue met by our user. According to our investigation, there should be something wrong with the user's VS Code networking. Please help on this.

Steps to Reproduce (on user's machine):
1. Install [Azure IoT Edge](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-edge) extension.
2. Invoke command "Azure IoT Edge: New IoT Edge Solution". Follow the guidance to create a Python module.
3. "unable to verify the first certificate" error will occur when the extension tries to download GitHub repo as zip

Some investigations result and helpful information:
1. The user can visit GitHub website without any cert errors using Chrome. The user also checks the cert of GitHub, it's issued by DigiCert which is a well known CA. So no MITM attack exists.
2. The user can git clone/download as zip the target GitHub repo successfully using Chrome
3. The extension issues a https request to download the target GitHub repo, which is same with download as zip on GitHub

Since user can visit GitHub website and download repo as zip successfully from GitHub website. And there's no MITM attack in the user's network environment. The same download GitHub repo https request issued by the extension should success without error. But there's cert error in the request.

**Comment by chrmarti** [comment]
Is the user behind a proxy?

Try disabling loading of System Certificates in the VS Code user settings. Uncheck:
![image](https://user-images.githubusercontent.com/9205389/67931048-63045900-fbc1-11e9-9fba-2058f7da5975.png)

**Comment by daelsala** [comment]
@chrmarti FYI The customer tried setting the enviornemnt vairable NPM_CONFIG_STRICT_SSL to false, if you see below, he receives the same python module error
 
![aaa](https://user-images.githubusercontent.com/57229540/67965220-a49c0080-fbcf-11e9-8515-99c1bc2e1f8e.jpg)

**Comment by chrmarti** [comment]
Is the customer behind a network proxy? Try disabling 'Http: Proxy Support' in the settings too.

**Comment by daelsala** [comment]
Customer verbatim: (Still seeing issue)  
I’m working from home, I disabled my corporate VPN and disabled http: Proxy Support, gives the same error:

 
![proxy](https://user-images.githubusercontent.com/57229540/68041972-c4025e80-fc9f-11e9-9b8b-17bbd06aea20.jpg)

**Comment by chrmarti** [comment]
1) Is the setting `"azure-iot-edge.version.pythonmodule"` set? To which value?

2) Does it work with the VS Code Insiders build? (Download: https://code.visualstudio.com/insiders/)

3) Can they run the following using Node.js (first `npm install download-git-repo`, then `node testcode.js`):
```js
const download = require('download-git-repo');
const path = require('path');

download('github:Azure/cookiecutter-azure-iot-edge-module#master', path.join(process.cwd(), 'download'), err => {
	if (err) {
		console.error(err);
	} else {
		console.log('Done.');
	}
});
```
Does that succeed?

**Comment by daelsala** [comment]
@chrmarti Thank you. I will let the customer know. Just an fyi, this issue is for a Premier Customer and we need as much help as we can get to resolve this issue as quickly as possible Since this case has been open for a month now with ZERO progress.

I will let you know of the customers response

**Comment by daelsala** [comment]
Customer tried the following. @chrmarti  Can we set up a teams call with you and the customer where you can help troubleshoot this issue live, this way we do not have to keep going back and forth. Can you please provide me your work hours or timezone


1)	azure-iot-edge.version.pythonmodule  is set to:  master
 
![i1](https://user-images.githubusercontent.com/57229540/68320974-80846780-0086-11ea-82f9-00ebb82119e1.jpg)


2)	Using insiders build gives this message when creating new IoT edge solution:
 
![i2](https://user-images.githubusercontent.com/57229540/68320995-88dca280-0086-11ea-84c3-27c639ed14df.jpg)


3)	Using insiders build, let me know if I missed something…
PS C:\Mark\IoT\Junk\python_edge_troubleshooting9> npm install download-git-repo
npm WARN saveError ENOENT: no such file or directory, open 'C:\Mark\IoT\Junk\python_edge_troubleshooting9\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Mark\IoT\Junk\python_edge_troubleshooting9\package.json'
npm WARN python_edge_troubleshooting9 No description
npm WARN python_edge_troubleshooting9 No repository field.
npm WARN python_edge_troubleshooting9 No README data
npm WARN python_edge_troubleshooting9 No license field.

+ download-git-repo@3.0.2
added 124 packages from 46 contributors and audited 240 packages in 26.703s
found 0 vulnerabilities
   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.4.1 -> 6.13.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯
![i3](https://user-images.githubusercontent.com/57229540/68321010-91cd7400-0086-11ea-952d-c859fe14e406.jpg)

**Comment by daelsala** [comment]
Customers availability:
I’m free tomorrow between 10am – 3:30pm CST (except for just a half hour from 1 - 1:30).  I’m out of office on Friday and will be in workshop the whole following week

Can you or anyone else on your time create some time to be able to meet with the customer during a time that will work with the customer?

**Comment by chrmarti** [comment]
I'm still trying to understand if VS Code is part of the problem. The user ran `testcode.js` from the command line without Node.js, but that does not work. They need to run `node testcode.js` from the command line instead. What's the output of that?

**Comment by daelsala** [comment]
@chrmarti 
Customers output:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Mark\IoT\Junk\python_edge_troubleshooting9> node --version
v10.15.0
PS C:\Mark\IoT\Junk\python_edge_troubleshooting9> node testcode.js
{ RequestError: unable to verify the first certificate
    at ClientRequest.req.once.err (C:\Mark\IoT\Junk\python_edge_troubleshooting9\node_modules\got\index.js:182:22)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  host: 'codeload.github.com',
  hostname: 'codeload.github.com',
  method: 'GET',
  path: '/Azure/cookiecutter-azure-iot-edge-module/zip/master',
  protocol: 'https:',
  url:
   'https://codeload.github.com/Azure/cookiecutter-azure-iot-edge-module/zip/master' }
PS C:\Mark\IoT\Junk\python_edge_troubleshooting9>

**Comment by chrmarti** [comment]
Something seems to replace the certificate. Does Chrome download the ZIP from https://codeload.github.com/Azure/cookiecutter-azure-iot-edge-module/zip/master?

If you have `openssl` installed, you can check the certificate with:
```sh
openssl s_client -showcerts -connect codeload.github.com:443
```

**Comment by daelsala** [comment]
@chrmarti The customer is unable to access that site.  they tried both on and off corporate network, but it is restricted by the corporate virus software. (see below)
![mark_1](https://user-images.githubusercontent.com/57229540/68709905-33a80180-055c-11ea-81a2-2dc1af87b8fe.jpg)

**Comment by chrmarti** [comment]
Thanks, closing the issue.

**Comment by daelsala** [comment]
@chrmarti why did you close? what does this mean?

**Comment by daelsala** [comment]
@blackchoey

**Comment by chrmarti** [comment]
It seems the antivirus of the user is the cause of the failure to verify the certificate.

The antivirus presents its own reply in the browser. It looks like that is a complete HTTPS reply, including a certificate, and that certificate is not valid for the given URL.

I closed this issue because VS Code is not part of the cause.
