### ISSUE TITLE
Persisted data breakpoints are not registered when starting a new debug session

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#83743]
VS Code didn't respect the canPersist attribute of DataBreakpointInfoResponse well. When it is true, the BREAKPOINTS viewlet will keep it there after the debug session terminates. But when launching a new debug session, no setDataBreakpoints request are sent to debugger during initialization. The debugger has no chance to enable the persisted data breakpoints.

**Comment by isidorn** [comment]
Can not reproduce with Mock Debug which I changed to return `canPersist: true` for every data breakpoint.
VSCode sends the data breakopints when the new session is initalised [here](https://github.com/Microsoft/vscode/blob/ac3fab27bdc63be0825faf52f2e27ee359cc8c14/src/vs/workbench/contrib/debug/browser/debugService.ts#L1030)
Can you please create a fork of mock debug that shows this issue so I can investigate more? Thank you

Here's the gif showing that I send the persisted data breakpoint:
![data](https://user-images.githubusercontent.com/1926584/70252150-29ef7380-1781-11ea-8091-b67be6199505.gif)

**Comment by weinand** [comment]
Maybe it got fixed by me reverting your async/await change...

**Comment by isidorn** [comment]
The async await chainges I have reaplied after fixing the issue for which you did the revert. But it might be some other change in the meantime fixed this

**Comment by weinand** [comment]
Aha, the issue is that the "setDataBreakpoints" is not called after a **restart** of VS Code.

So my bug description was wrong: instead of "But when launching a new debug session" I meant "But when launching a new VS Code session".

**Comment by isidorn** [comment]
Hmm I also can not reproduce if I restart VS Code.
Sicne we properly store data breakpoints as all other breakpoints in local storage via this code [here](https://github.com/Microsoft/vscode/blob/57bb2ca49a494a8f1d5f7cf7c23d1b96f4fa1c7d/src/vs/workbench/contrib/debug/browser/debugService.ts#L1145)
When I restart VS Code I get the data breakpoints back from local storage and send them properly to mock debug.

**Comment by weinand** [comment]
And you hit them properly?

**Comment by isidorn** [comment]
I forgot when mock debug hits data breakpoints. But I don't see why not, I send them properly to the adapter, it is up to the adapter to send a stopped event.
Or you can refersh my memory as to the data breakpoint logic in mock debug?

**Comment by testforstephen** [comment]
In the latest insider, i see the persisted data breakpoints are being resent to DAP during restarting debug session. Thanks.

But i found another problem about the **verified** icon update.

In Java Debugger, we take async mechanism to verify the breakpoint. For example, in the **setDataBreakpoints** response, i initially return the breakpoint with **verified** attribute being **false**.
```
[request]
{"command":"setDataBreakpoints","arguments":{"breakpoints":[{"enabled":true,"id":"5db1323a-4c0a-4663-ac50-3c1a1b89e14a","sessionData":{},"description":"Owner.telephone : String","dataId":"org.springframework.samples.petclinic.owner.Owner#telephone","canPersist":true,"accessTypes":["read","write","readWrite"]}]},"type":"request","seq":5}

[[RESPONSE]]
Content-Length: 149

{"success":true,"request_seq":5,"command":"setDataBreakpoints","body":{"breakpoints":[{"id":2,"verified":false,"line":0}]},"seq":6,"type":"response"}
```

Then later when the associated context is fully ready, the debugger will send a breakpoint event to client, where the breakpoint event will mark verified being true.
```
[[EVENT]]
Content-Length: 141

{"event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":2,"verified":true,"line":0},"type":"breakpoint"},"seq":34,"type":"event"}
```
But the breakpoints viewlet still shows a grey icon before the verified data breakpoints.
![image](https://user-images.githubusercontent.com/14052197/70502868-f172df80-1b5c-11ea-95fd-fb1eefc07638.png)

**Comment by isidorn** [comment]
@testforstephen that sounds like an unrelated issue.
Can you only reproduce this with data breakpoints? Or with all breakpoints? Can you please file a new issue and ping me on the issue? Thank you very much!

**Comment by testforstephen** [comment]
thanks @connor4312 to create a new issue for this.
