### ISSUE TITLE
Unpredictable behaviour when pressing TAB-key

### ISSUE THREAD

**Issue by vontompers** [microsoft/vscode#83744]
Issue Type: <b>Bug</b>

Place cursor at the beginning of a row in the editor window. Press the TAB-key. Instead of inserting four spaces, focus changes to the console/output window. 

VS Code version: Code - Insiders 1.40.0-insider (93ee2fc3121b7f66ddf568c051f3bfff7db8d618, 2019-10-31T06:28:32.160Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2648)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.69GB (2.33GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
docker-explorer|for|0.1.6
experimental-fsharp|Ion|0.3.5
Ionide-fsharp|Ion|4.2.0
vscode-github|Kni|0.30.3
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.82.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.0
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.1
cmake|twx|0.0.17

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it enough to create new Untitled file and press <kbd>Tab</kbd> in it to reproduce this issue or it should be specific file? (wasn't able to repro on Windows with these steps)
Is it reproducible with extension disabled?
Do you have any custom shortcuts?

**Comment by IllusionMH** [comment]
Do you have "Tab moves focus" in the status bar?
See details here https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping

**Comment by vontompers** [comment]
My bad. The problem was "Tab moves focus". Thanks for the help though and I'm sorry for my stupid mistake! Kind regards.
