### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by JeyesHan** [microsoft/vscode#83748]
I am trying to do remote debug on a remote ubuntu server. I can run my python script with my laptop. However, when I try to debug my program. I got the connection refused error. Does anyone can help me? Please~
![image](https://user-images.githubusercontent.com/25529815/67944015-6249e200-fc16-11e9-9a54-a9122dba59f5.png)

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate this
