### ISSUE TITLE
HC theme selection makes the text unreadable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8374]
Ref: #8229

IE 11

1. https://microsoft.github.io/monaco-editor/index.html
2. HC theme -> select some text -> notice how the text is unreadable
This looks good in chrome

![screen shot 2016-06-28 at 16 09 04](https://cloud.githubusercontent.com/assets/1926584/16418570/ba62186a-3d4a-11e6-8a01-e94ca2d45afc.png)

**Comment by alexandrudima** [comment]
This has been fixed for August.
