### ISSUE TITLE
'More Actions' menu of Outline panel uses 'Type' in two different ways

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#83751]
![image](https://user-images.githubusercontent.com/6726799/67947217-13328b80-fbdb-11e9-996e-da564afb88b0.png)

I suggest "Filter on Type" becomes "Filter on Typing" or "Filter on Keystrokes" to eliminate the confusion.

I'm willing to prepare a PR for this if it's agreed.

VS Code version: Code - Insiders 1.40.0-insider (93ee2fc3121b7f66ddf568c051f3bfff7db8d618, 2019-10-31T05:42:33.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by gjsjohnmurray** [comment]
Actually, perhaps that menu option could reasonably be removed now that the widget appearing when you type also displays a toggle for that feature when hovered over:
![image](https://user-images.githubusercontent.com/6726799/67947557-cdc28e00-fbdb-11e9-9aac-d5a4b3aadcd8.png)

**Comment by gjsjohnmurray** [comment]
And/or maybe "Sort By: Type" should become "Sort By: Category" so it aligns with the helptext item from the quickopen field (or whatever it's called):

![image](https://user-images.githubusercontent.com/6726799/67948320-6279bb80-fbdd-11e9-8e90-69c380a409a4.png)

**Comment by jrieken** [comment]
I have kept the entry event after adopting the new tree because I assumed users would miss it ;-). Aligning the wording between outline and quick outline makes sense. So, two time category or maybe kind?

**Comment by gjsjohnmurray** [comment]
My vote is for 'Sort By: Type' to become 'Sort By: Category'

Shall I go ahead and prepare a PR?

**Comment by jrieken** [comment]
yeah, please go ahead
