### ISSUE TITLE
Draw custom drop-down picker (Desktop, Web)

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83756]
Web on the left, electron on the right:
![image](https://user-images.githubusercontent.com/38270282/67950178-817e4a80-fbe9-11e9-8ecb-1321ae0581b2.png)

**Comment by alexr00** [comment]
Just found https://github.com/microsoft/vscode/issues/83556 so now I now the why.

**Comment by bpasero** [comment]
@alexr00 what browser is that? In Chrome it should still look OK:

![image](https://user-images.githubusercontent.com/900690/67950982-f605b900-fbea-11e9-821c-d7962953a31e.png)

**Comment by alexr00** [comment]
FireFox

**Comment by bpasero** [comment]
Work happening in https://github.com/microsoft/vscode/pull/83793

**Comment by bpasero** [comment]
Setting "feature-request" as this probably needs a test plan item on all platforms + web.
