### ISSUE TITLE
Slow scrolling through suggetions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8375]
Refs: #8229 

1. IE, open https://microsoft.github.io/monaco-editor/index.html
2. Trigger suggestion and hold the down key to go through the suggestions
3. This is very slow when compared to vscode

![slowsuggestion](https://cloud.githubusercontent.com/assets/1926584/16418692/3873c73a-3d4b-11e6-8065-69d25dc3b4c1.gif)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#144

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
