### ISSUE TITLE
Configure "Change Language Mode" picker to not close on focus lost

### ISSUE THREAD

**Issue by ulistaerk** [microsoft/vscode#83750]
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. STRG+SHIFT+P
2. Select "Change language mode"
3. Press ALT+TAB twice
5. Command palette disappeared and all input is lost

Does this issue occur when all extensions are disabled?: Yes

Expected Behaviour: Palette is still there with all my Input.

**Comment by ulistaerk** [comment]
This feature-request is not tied to "Change Language Mode", but an easy-to-demonstrate case. Root cause is the behaviour of the Command Palette.

**Comment by ulistaerk** [comment]
In the mean time I discovered the feature "Preserve Input". This has no effect on described the behaviour.

@alexandrudima As this is tagged as a future request, what is the backstory of closing the command palette if focus changes?

**Comment by bpasero** [comment]
@ulistaerk did you try to configure: `"workbench.quickOpen.closeOnFocusLost": false` in settings?
