### ISSUE TITLE
Line breakpoint disappears once hit

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83757]
Once hit, a line breakpoint will disappear. The red dot should stay inside the yellow chevron.

![Peek 2019-10-31 14-26](https://user-images.githubusercontent.com/22350/67950687-64964700-fbea-11e9-99b7-a4365fe94359.gif)

**Comment by neilong31** [comment]
If possible, would I still be able to give this issue a shot please?

**Comment by joaomoreno** [comment]
@neilong31 Sure, give it a try.

**Comment by joaomoreno** [comment]
@neilong31 Let's wait for @isidorn's opinion first. I would look for [`help wanted`](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+) issues, if you'd like to help out.

**Comment by neilong31** [comment]
@joaomoreno Sorry, for the late reply! I'll hold off for now then.

**Comment by roblourens** [comment]
Technically this lives on in https://github.com/microsoft/vscode/issues/85148
