### ISSUE TITLE
Editor Highlights Full String

### ISSUE THREAD

**Issue by natejcho** [microsoft/vscode#83768]
- VSCode Version:  1.37.1
- OS Version: Darwin x64 17.7.0

Steps to Reproduce:

1. Highlight a substring
2. Rest of the string will get highlighted

- using slack theme
- Language - JS

![Screen Shot 2019-10-31 at 12 19 04 PM](https://user-images.githubusercontent.com/9434077/67965600-bcc44d80-fbd8-11e9-91a0-fe85d2b27a15.png)

Everything was highlighted, though I only selected 'valid'

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
