### ISSUE TITLE
Header tags are not rendered correctly in preview if not separated by space

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8376]
Refs: #7945 

![screen shot 2016-06-28 at 4 14 42 pm](https://cloud.githubusercontent.com/assets/10746682/16418746/7279981a-3d4b-11e6-81ab-fcd4ccb8c589.png)

**Comment by cbreeden** [comment]
Is this a bug?  This is the correct rendering according to the CommonMark specification for [ATX Headings](http://spec.commonmark.org/0.25/#atx-headings).  It goes to show that that things like this should not be rendered as a header:

`#5 bolt` should be rendered `<p>#5 bolt</p>` and `#hashtag` should be rendered as `<p>#hashtag</p>`

**Comment by kieferrm** [comment]
As @cbreeden points your header is not a header according to the CommonMark spec. However GitHub allows it. So, we could add our own handler to support to support that. See https://github.com/markdown-it/markdown-it/issues/240.

**Comment by mjbvz** [comment]
Closing as as-designed according to the common-mark spec
