### ISSUE TITLE
error while building tasks.json

### ISSUE THREAD

**Issue by hinduvanshi** [microsoft/vscode#83761]
error:cl.exe : The term 'cl.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ cl.exe /EHsc /Zi /Fe: helloworld.exe helloworld.cpp
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (cl.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process terminated with exit code: 1

**Comment by dhairyanadapara** [comment]
Hey @hinduvanshi, I think `cl.exe` is not added to the environment variables. You can try to add that or provide an absolute path for `cl.exe`. If you need reference https://stackoverflow.com/a/8800422. :)
