### ISSUE TITLE
Go to symbol not working

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8377]
Refs: #8229

1. Any browser, goto https://microsoft.github.io/monaco-editor/index.html
2. Open typescript sample, goto symbol from context menu is not working
3. Notice errors in console

![screen shot 2016-06-28 at 16 18 07](https://cloud.githubusercontent.com/assets/1926584/16418864/ed050cf4-3d4b-11e6-817f-aed354099f5e.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#145

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
