### ISSUE TITLE
Terminal integration tests are flaky and assertions are not getting passed to done

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83780]
A few issues:

- Assertions are failing but they are getting ignored since they're not passed to `done`
- Listeners are leaking across tests causing false positives/flakiness/non-determinism
- Exceptions being thrown: https://github.com/microsoft/vscode/issues/81821

WIP: https://github.com/microsoft/vscode/tree/tyriar/integration_test

**Comment by chrmarti** [comment]
Change looks good. Marking verified.
