### ISSUE TITLE
SCM status bar contribution missing under some condition

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83781]
I am not sure what cause the issue but the SCM status bar entry was missing. I went to check for updates and saw the entry for check for updates was also missing. Perhaps these share a condition that can hint at why the status bar entry was missing. A reload fixed the issue.

**Comment by joaomoreno** [comment]
Could the SCM bar be this? https://github.com/microsoft/vscode/issues/67670

Now sure what the check for updates missing would mean. They share nothing in common. :think

**Comment by sbatten** [comment]
my case was single root/single folder

**Comment by joaomoreno** [comment]
Oops, I actually meant this https://github.com/microsoft/vscode/issues/83464 which seems remote related but it's not, notice the steps at the end of the thread.

**Comment by sbatten** [comment]
I can't be certain, but I was convinced that the contribution actually disappeared. Additionally, this happened in today's latest insiders. So, shouldn't it have been resolved?

**Comment by joaomoreno** [comment]
Yup. Then, let me know if it comes back. Since this is the first report I've ever gotten like this, I'm taking it with some salt. :green_salad:

**Comment by sbatten** [comment]
The exact same issue happened to me again today. I was working in one folder, then opened a second window from an external terminal. Check for updates + SCM Status bar contrib were both missing.

**Comment by sbatten** [comment]
only console errors seem unrelated but not sure.

![image](https://user-images.githubusercontent.com/6561887/69387634-49fc3e80-0c7b-11ea-9c63-1c2ba3b077ef.png)
