### ISSUE TITLE
save of json with comments defaults to code-workspace file extension

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#83787]
* File -> New File, you get `Untitled-1`
* In lower right corner, change the language mode to `JSON with Comments`
* Save the file

Result: the default file name given is `Untitled-1.code-workspace`

![image](https://user-images.githubusercontent.com/1487073/67984970-19c60080-fbe5-11e9-9e13-9b0052e0b80b.png)

Expected: the default file name is `Untitled-1.json` 

I actually thought it was trying to create a mulit-root workspace...

**Comment by bpasero** [comment]
Seems to be coming from the configuration editing extension:

![image](https://user-images.githubusercontent.com/900690/68013837-44b85f00-fc8e-11e9-80a8-534c3fafd853.png)

I do not know how to change this, our [`suggestFilename`](https://github.com/microsoft/vscode/blob/ea89eb903fed2af8506e9621da7b7f9a913c6413/src/vs/base/common/mime.ts#L257) method looks at registered associations and picks the first one which happens to be `.code-workspace`. 

Back to Martin for advice.

**Comment by aeschli** [comment]
@bpasero We're missing a way to define the default extension for a given language. Maybe a new property?

**Comment by bpasero** [comment]
Yeah possibly.

**Comment by bpasero** [comment]
Sorry, I don't think this is important enough. On a operating system that is nice (like Windows) you should see a dropdown with all the extensions that are possible.
