### ISSUE TITLE
"Cannot edit in read-only editor" when trying to edit .py file after debugging Jupyter cell

### ISSUE THREAD

**Issue by arniwesth** [microsoft/vscode#83784]
### Info:
- VSCode Version: 1.39.2
- OS Version: Linux Mint 19.2
- Does this issue occur when all extensions are disabled?: Does not apply in this case.

### Problem:
"Cannot edit in read-only editor" pop-up when trying to edit .py file. See image below.

### Steps to reproduce:

1) Debug a cell in a Jupyter notebook (.py).
2) Step into another code file.
3) Stop debugger
4) Try to edit. The editor is now in read-only mode.

### Workaround:
Of course, you can just open the file and edit. But you have to find the right line to edit. This is cumbersome, especially in large projects.

![read-only](https://user-images.githubusercontent.com/409051/67988765-3a1bac80-fc31-11e9-8b66-57b28278fd1d.png)

**Comment by isidorn** [comment]
Please file this against the python debugger, the issue here is that they send a Source object for the file, instead of sending a path to the local file on disk. Thus the Source object is opened from memoery which you can not edit
