### ISSUE TITLE
Broken SCM tree

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83782]
From @sploders101:

> @joaomoreno Currently, this is what is happening. The exact same thing happens on the insiders build. I am on Linux if that makes a difference. I also have no extensions on the insiders build, as I only installed it to test this, so that shouldn't be an issue either.
![simplescreenrecorder](https://user-images.githubusercontent.com/26530958/67960663-3b60c100-fbc0-11e9-80c2-ab510e1738e4.gif)

Steps:

1. Rename a file inside a folder
2. Go to SCM view, switch to tree mode
3. Stage the untracked file.
4. Stage the deleted file. Tree gets broken:

![image](https://user-images.githubusercontent.com/22350/67978182-d6d25000-fc19-11e9-9177-bd2c76448b82.png)

**Comment by sploders101** [comment]
Thanks for submitting this! Sorry, I originally wrote one up, but then found #82481 and commented there to avoid duplicates.
