### ISSUE TITLE
code helper is using more than 300% macbook pro and cpu fan running at  high speed

### ISSUE THREAD

**Issue by manu-eng** [microsoft/vscode#83791]
- VSCode Version: 1.39.2
- OS Version: mac 10.15.1

Steps to Reproduce:

1. open vs-code
2. it just shoot up cpu usage to 300% or more

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by manu-eng** [comment]
Issue was with @typescript-eslint/parser version 2.4.0. I have upgraded it to 2.5.0.  Issue seems to be fixed.
