### ISSUE TITLE
warn about duplicate debug type ids

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#838]
I made a bug fix for mono-debug available to an external user. For this I had changed the publisher id to myself. The user was not able to use that extension.

Problem: publishing an extension with the same name but a different publisher ID creates a new extension that has nothing to do with the original extension.
The debug UI code that collects the extension does not seem to detect the problem that a debug type is redefined. Subsequently it is not clear what debug adapter extension is actually used.

I suggest, that we support that debug adapter extensions for an existing debug type but with a different publisher are allowed but result in a warning.

**Comment by isidorn** [comment]
Now I ovewrite attributes so the user extension will have priority.
For showing the message we need to discuss with @egamma which would be a seperate item.
