### ISSUE TITLE
Open Preview action on a markdown file is not shown when right clicking on the file in tabs mode

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8380]
#7945 

Steps to Reproduce:

1. Enable Tabs
2. Open any md file
3. Right click on the file title to open preview
4. Right click on the source file again (Note that source file is not in focus)

Open preview action is not shown

![screen shot 2016-06-28 at 4 21 19 pm](https://cloud.githubusercontent.com/assets/10746682/16418987/5ddd5e40-3d4c-11e6-9e05-bc143bd61a86.png)

**Comment by jrieken** [comment]
I wasn't able to reproduce but iff it's an issue with the context menu not picking up any contributed commands. Also the (at least disabled) 'Switch to Changes View' action doesn't show.

![screen shot 2016-06-29 at 11 22 46](https://cloud.githubusercontent.com/assets/1794099/16447281/0096ea3a-3dec-11e6-9240-6c7394e37398.png)

**Comment by sandy081** [comment]
@bpasero 

I am still able to reproduce this in this build - a21c12346f388e51858c930875ca30968604c116 with following steps:

- Enable tabs
- Open a .md file
- Open any other file. Now this file is active
- Right click on the tab of .md file

You do not see the options

<img width="777" alt="screen shot 2016-06-30 at 6 55 46 pm" src="https://cloud.githubusercontent.com/assets/10746682/16496830/46f0621e-3ef4-11e6-887e-0ec2fbea7716.png">

**Comment by bpasero** [comment]
@sandy081 this is currently as designed, we do not show editor actions for an editor that is not active.

**Comment by sandy081** [comment]
@bpasero Then I see some inconsistency here. See the pictures with tabs disabled and enabled.

When tabs are disabled, actions are not shown on editor which is not active.
When tabs are enabled, actions are shown on editor which is not active.
That's why I expected to see actions in above case.

<img width="1154" alt="screen shot 2016-06-30 at 7 24 13 pm" src="https://cloud.githubusercontent.com/assets/10746682/16497620/412312a6-3ef8-11e6-806b-a2b5848bef87.png">

<img width="1018" alt="screen shot 2016-06-30 at 7 25 58 pm" src="https://cloud.githubusercontent.com/assets/10746682/16497675/7fccf134-3ef8-11e6-86c1-cb6f237b6589.png">

**Comment by bpasero** [comment]
@sandy081 that is true but that is a different case. In your issue you right click on an editor that is NOT EVEN visible and expect editor actions to show.

In your new example, all editors are visible and so we can show those actions in the menu. Initially I did not have those actions in there but I got another bug where someone was looking for them.

It is purly a UX decision to not show the actions when tabs are disabled and the editor is inactive. No technical reason otherwise.
