### ISSUE TITLE
Preferences smoke tests are broken

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83802]
The keybinding cannot be updated because keybindings.json is invalid:

<img width="723" alt="Screen Shot 2019-10-31 at 5 52 18 PM" src="https://user-images.githubusercontent.com/2193314/67995493-e5177080-fc07-11e9-82f0-1b63aab5d0e7.png">

```
    Preferences
      ✓ turns off editor line numbers and verifies the live change
** Timeout!
Did not pass accept function
      1) changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it
```

**Comment by bpasero** [comment]
Sandeep is still out.

@aeschli could this be a JSON issue? The keybindings file looks like this:

![image](https://user-images.githubusercontent.com/900690/68007746-cc956d80-fc7c-11e9-9637-3f4e71dd4cf9.png)

(notice the thing at the end)

**Comment by alexr00** [comment]
I'm not seeing this failure. Verified.
