### ISSUE TITLE
设置字体失效

### ISSUE THREAD

**Issue by yangbo990713** [microsoft/vscode#83806]
Issue Type: <b>Bug</b>

设置第三方字体时失效，只能设置系统自带字体

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.6
gitlens|eam|10.1.1
beautify|Hoo|1.5.0
vue-alias-skip|lih|0.0.14
vscode-language-pack-zh-hans|MS-|1.39.3
vetur|oct|0.22.6
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
eno|Wsc|2.0.9

(1 theme extensions excluded)

</details>

**Comment by byyxx128** [comment]
1. Always English please. You should already see this:
![image](https://user-images.githubusercontent.com/20079289/67997813-2caff380-fc2c-11e9-9ed3-780832426c00.png)

2. What font are you using? Third-party fonts are working fine to me. Double check your font name and settings. Or you can attach your font file here.

**Comment by yangbo990713** [comment]
The Cascadia Code font I used can be used at the beginning, but after the computer is restarted, it can no longer be used. Whether it is reinstalling vscode or font, it can't be used.
