### ISSUE TITLE
Web smoke tests fail because encoding status bar item isn't available

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83805]
Not sure why it's not there on web? That difference causes 2 smoke tests to fail https://github.com/microsoft/vscode/blob/c8846de84ab2f0a9279a41d80414465124c52a7a/test/smoke/src/areas/statusbar/statusbar.test.ts#L21-L39

**Comment by bpasero** [comment]
@Tyriar we do not support any other encoding than UTF-8 in web currently (see https://github.com/microsoft/vscode/issues/79275).

Is there a way I can find out if smoke tests run against web? Then I suggest to do the check conditionally or check for another status entry.
