### ISSUE TITLE
terminal not working

### ISSUE THREAD

**Issue by try24hard** [microsoft/vscode#83811]
Issue Type: <b>Bug</b>

The terminal process terminated with exit code: 4294967295

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.3
vsc-material-theme|Equ|30.0.0
beautify|Hoo|1.5.0
python|ms-|2019.10.44104
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.1
csharp|ms-|1.21.5
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Did you all existing issues mentioning that error code? My filter was `is:issue 4294967295`

#83006 looks relevant, but there are other matches too.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.
