### ISSUE TITLE
Double click on find all references view throws exception

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8381]
Refs: #8229

1. IE11 open https://microsoft.github.io/monaco-editor/index.html, TS sample
2. Find all references on something, double click inside find all references view
3. Notice exception in console

![screen shot 2016-06-28 at 16 21 27 1](https://cloud.githubusercontent.com/assets/1926584/16418992/6329f282-3d4c-11e6-8321-5778ba306f78.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#146

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
