### ISSUE TITLE
Debug: Provide hierarchy of debug targets for compound targets

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83810]
Whenever I run the `Debug VS Code Main, Renderer & Extension Host` target, I want it to run 

- `Launch VS Code`
- `Attach to Main Process`
- `Attach to Extension Host`

But then the debug toolbar always shows me a random target:

![image](https://user-images.githubusercontent.com/22350/68011183-e3d95880-fc86-11e9-859c-ebaef5d4a56c.png)

I want the `Launch VS Code` target to be chosen by default, since that's the one that has the `stop` button that will stop all 3 targets.

![image](https://user-images.githubusercontent.com/22350/68011207-f9e71900-fc86-11e9-87da-00a673103e08.png)

I really don't ever care about detaching from the other two.

---

Compound targets are meant to address running N debug targets, which is very generic. But tackling our selfhost use case (I want to run 1 target which has 3 attach points) becomes suboptimal due to the generic nature of compounds.

cc @weinand for thoughts

**Comment by gjsjohnmurray** [comment]
Similar to #64624 but that one was recently closed as out-of-scope

**Comment by weinand** [comment]
Yes, the old item #64624 had been closed because we are planning to work on the new request #82332 in November.
