### ISSUE TITLE
Polish description text for workbench.editor.enablePreviewFromQuickOpen setting

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#83818]
![image](https://user-images.githubusercontent.com/6726799/68019381-7e3f9900-fc93-11e9-99dd-8ac5d305341e.png)

I suggest 'Controls whether opened editors from Quick Open...' gets changed to read 'Controls whether editors opened from Quick Open...' 

Will you take a PR?

VS Code version: Code - Insiders 1.40.0-insider (c8846de84ab2f0a9279a41d80414465124c52a7a, 2019-11-01T05:37:54.405Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
> Will you take a PR?

Sure 👍
