### ISSUE TITLE
Provide setting to ignore .gitignore filter for Go To File (Quick Open)

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#83817]
I have looked at existing issues. #70595 is similar, but I believe it may have been marked as duplicate by mistake, as it's slightly different.

I would like to be able to define a setting which allows for "Go To File" (Quick Open) to include indexing files excluded by my .gitignore files.

I have a global config to ignore node_modules and other files, but I also have some data files our project generates, which we don't want to commit. They are included in our .gitignore, and I'd like to be able to find them when using Quick Open.

Related to https://github.com/Microsoft/vscode/issues/70595
Not asking for a button, but a setting.
I wish to change this setting on a workspace basis.

**Comment by gjsjohnmurray** [comment]
See also #15604 though unlike yours that one isn't for a per-workspace setting.

**Comment by Relequestual** [comment]
I assumed any setting could also be per-workspace. Is that not the case?

**Comment by Relequestual** [comment]
Also, I don't want to turn off ALL exclusions, just those in my .gitignore. I still want the ones defined in settings to apply.

**Comment by roblourens** [comment]
Does `search.useIgnoreFiles` work for you?

**Comment by Relequestual** [comment]
Let me check that and get back to you today.

**Comment by Relequestual** [comment]
This works. My worry was that this would then go ahead and index node_modules, but it seems to not be doing that.

**Comment by roblourens** [comment]
Those are excluded by default in the `search.exclude` setting.
