### ISSUE TITLE
Tree label rendered incorrectly

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#83812]
The label of a tree node in a custom view (npm scripts explorer) gets over painted, pls see the screenshot below:

![image](https://user-images.githubusercontent.com/172399/68013729-fb680f80-fc8d-11e9-8a9c-10013ba68a64.png)

- git clone https://github.com/microsoft/vscode-remote-try-node.git
- rename the cloned folder to vscode-remote-try-node1
- clone the same repository again
- open `vscode-remote-try-node1`
- Add Folder `vscode-remote-try-node`

▶️ the 'start' script node is not rendered correctly.

**Comment by joaomoreno** [comment]
@alexr00 Could these two nodes use exactly the same IDs?

**Comment by alexr00** [comment]
@joaomoreno I wouldn't expect them too use exactly the same ID. The ID can come from two places:
1) The extension provides the ID
2) We create the ID by using the parentID, the element position, and the element label or resource URI.

It looks like the npm script tree elements don't provide an ID, so the ID would be generated using option 2. They are also clearly set with different labels (compile and start) so they _should_ have different IDs.

**Comment by egamma** [comment]
@alexr00 I cannot reproduce it consistently. When I ran into it I've also added/removed workspace folders. I've tried to do this again, but I cannot repro.

>They are also clearly set with different labels (compile and start)

What is interesting is that in the test setup there is no `compile` script in the package.json files, there is only a `start`.

**Comment by alexr00** [comment]
That is very interesting. I will spend some more time trying to reproduced it. There must be some stale state left somewhere.

**Comment by alexr00** [comment]
I haven't been able to make this happen, but it's possible that the new tree feature from Joao that lets the custom tree make one call to update an render has fixed this. If we see it again I'll investigate some more.
