### ISSUE TITLE
Smoke test failure: Debug stepOver, stepIn, stepOut

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#83819]
Insider version: 

Version: 1.40.0-insider
Commit: c8846de84ab2f0a9279a41d80414465124c52a7a
Date: 2019-11-01T05:35:06.002Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-19-generic

Running Code
       Debug
         stepOver, stepIn, stepOut:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)

**Comment by dbaeumer** [comment]
Fails also under:

Version: 1.40.0-insider (user setup)
Commit: 37d34176a6ecf1d09b16a0cad11bb619f3b1e48f
Date: 2019-11-01T10:19:19.506Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
Problem with the tests on linux. 
Debugging works fine when running the smoketest manually.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/85378
