### ISSUE TITLE
Context menu + scrolling moves the context menu to unexpected locations

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8382]
Ref: #8229

1. Any browser, open https://microsoft.github.io/monaco-editor/index.html
2. Trigger context menu and while the context menu is open scroll using the mouse
3. The context menu follows the mouse
4. I would expect similar behavior to vscode - where scroll is disabled if context menu is shown

![contextmenu](https://cloud.githubusercontent.com/assets/1926584/16419118/d011a066-3d4c-11e6-86d9-3ec2ca24b598.gif)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#147

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
