### ISSUE TITLE
Git Inconsistent Colors between current changes and incoming changes

### ISSUE THREAD

**Issue by rhires** [microsoft/vscode#83827]
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:
When looking at the Git compare for current changes vs incoming changes, depending on the view, the colors are different:
![image](https://user-images.githubusercontent.com/12577765/68025984-ac69ac80-fc84-11e9-838b-d8c0f61c589c.png)

![image](https://user-images.githubusercontent.com/12577765/68025996-b4295100-fc84-11e9-9ecc-2b64f6c158a9.png)

Compare changes view:
![image](https://user-images.githubusercontent.com/12577765/68026004-bab7c880-fc84-11e9-9cc1-bbed270cb1c3.png)

Current changes should be the same color regardless of the view. Incoming changes as one color, current changes as the other color. 

Does this issue occur when all extensions are disabled?: Yes

Thanks!

**Comment by joaomoreno** [comment]
They are two different conceptual views.

The top view shows two different changes.

The bottom view shows one change, split into its two parts: the deletion and the insertion.
