### ISSUE TITLE
Freeze Issue

### ISSUE THREAD

**Issue by aknewlife** [microsoft/vscode#83824]
Issue Type: <b>Performance Issue</b>

Hello,

The code area and live server and other services freezes this has been happening even after application re installation
.
1 Observation is my html uses a lot of svg code in html and has been happening after i paste new svg code text.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    73	 12580	code main
    0	   179	  6008	   window (● index.html - template - Visual Studio Code)
    0	    80	 14260	     extensionHost
    0	   117	   528	       "C:\Users\ankitk\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\ankitk\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=14260
    0	    88	  3352	       electron_node server.js 
    0	    11	 15212	     watcherService 
    0	    11	  8104	       console-window-host (Windows internal process)
    0	    38	 15444	     searchService
    2	    65	  8240	   window (Issue Reporter)
    1	    91	 15964	   gpu-process
    0	    64	 16852	   shared-process
    0	    13	 17268	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● index.html - template - Visual Studio Code)
|    Folder (template): 213 files
|      File types: scss(33) jpg(33) svg(20) DS_Store(18) js(18) html(18)
|                  css(8) ttf(6) woff(6) woff2(6)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
beautify|Hoo|1.5.0
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
