### ISSUE TITLE
Cmd + Shift + Left Arrow in editor selects opposite direction

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#83823]
Issue Type: <b>Bug</b>

![bug](https://user-images.githubusercontent.com/35271042/68023727-55a0aa80-fc65-11e9-9209-54b0804ca5ae.gif)

Steps
1. Have a first line that is indented, and a second line that is also indented (child)
2. Navigate to the start of line 2
3. Backspace (should be on line 1), then hit enter
4. :bug: type Cmd + Shift + Left arrow to select all text to the beginning of line, notice how it selects the opposite direction

VS Code version: Code - Insiders 1.40.0-insider (93ee2fc3121b7f66ddf568c051f3bfff7db8d618, 2019-10-31T05:39:25.980Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.35.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
prettier-vscode|esb|2.3.0
vscode-open-in-github|fab|1.2.2
vscode-pull-request-github-insiders|Git|2019.10.44104
svg|joc|1.0.5
all-symbol-kinds|jri|0.0.1
vscode-colorize|kam|0.8.15
remote-containers|ms-|0.83.0
remote-ssh-edit-nightly|ms-|2019.10.42662
remote-ssh-nightly|ms-|2019.10.42662
azure-account|ms-|0.8.7
vscode-typescript-tslint-plugin|ms-|1.2.2
cloudenv-extensions|ms-|1.0.1173
vsonline|ms-|1.0.1173
debugger-for-chrome|msj|4.12.1
rescuetime|Res|1.0.1
notification-tester|svi|2.1.5
enumerator|swi|0.0.6
ayu|tea|0.18.0

(8 theme extensions excluded)

</details>

**Comment by NotWearingPants** [comment]
I believe this is the expected behavior.
This is the equivalent of <kbd>Shift</kbd>+<kbd>Home</kbd> in Windows.
Since pressing <kbd>Home</kbd> toggles moving the cursor between the beginning of the line and the first non-whitespace character in the line, it is very logical that when you press it with <kbd>Shift</kbd> it will toggle selecting until the same two places.

This should be closed.

**Comment by misolori** [comment]
@NotWearingPants no, when you are on an indented line it will always go to the left, so this should never go to the right.

**Comment by alexandrudima** [comment]
@misolori I agree this might appear weird (that `home`/`cmd+shift+left` would go to the right), but the `cursorHome` command is implemented to work in the following way:
1. go to the first non-whitespace character in the line.
2. if already at the first non-whitespace character, go to column 1.

This is pretty useful for editing, as oftentimes there's something wrong at the "beginning" of a line... I have double checked this is also the behavior of SublimeText, so I don't think we have a quirk.
