### ISSUE TITLE
Smoke test failure: Git reflects working tree changes

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#83820]
Version: 

Version: 1.40.0-insider
Commit: c8846de84ab2f0a9279a41d80414465124c52a7a
Date: 2019-11-01T05:35:06.002Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-19-generic

```
       Git
         reflects working tree changes:
     Error: Timeout: get elements 'div[id="workbench.view.scm"] .monaco-list-row .resource' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)
```

AND

```
Git
         stages, commits changes and verifies outgoing change:
     Error: Timeout: get elements 'div[id="workbench.view.scm"] .monaco-list-row .resource' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)
```

**Comment by dbaeumer** [comment]
Both still fail under:

Version: 1.40.0-insider (user setup)
Commit: 37d34176a6ecf1d09b16a0cad11bb619f3b1e48f
Date: 2019-11-01T10:19:19.506Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
On macOS I'm seeing three git tests failing:

![2019-11-01_12-43-50](https://user-images.githubusercontent.com/1898161/68022698-6244f300-fca5-11e9-9b8d-e6b2f238f12d.png)

**Comment by joaomoreno** [comment]
@dbaeumer  @weinand Can you reproduce when running it with `-f Git`?


![image](https://user-images.githubusercontent.com/22350/68024239-ca95d380-fca9-11e9-9d72-bda109b2a903.png)

**Comment by dbaeumer** [comment]
Works for me with `-f Git`

**Comment by weinand** [comment]
Running smoke test with "-f Git" works for me too

**Comment by joaomoreno** [comment]
Were there other errors, other than git?

**Comment by weinand** [comment]
yes:
https://github.com/microsoft/vscode/issues/78385
https://github.com/microsoft/vscode/issues/83821
https://github.com/microsoft/vscode/issues/83819

**Comment by joaomoreno** [comment]
Since all smoke test suites are tied together, any failures on some suites will cause failures on others. This is one drawback of our smoketest and should be cleaned up asap.
