### ISSUE TITLE
Debug console hijacks focus from Find Widget

### ISSUE THREAD

**Issue by osharaki** [microsoft/vscode#83829]
Issue Type: <b>Bug</b>

1. Start a debugging session (Tested with Python and Flutter and issue appears in both). In Flutter, _Start without debugging_ also leads to the issue.
2. Open up the debug console, if not already open.
3. Attempt to use the in-file search widget with keyboard shortcuts.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

While debugging with the debug console open, I can no longer control the Find Widget properly using the default keyboard shortcuts. _Ctrl+F_ still opens up the Find Widget and I can type inside it, but _Enter_ and _Shift+Enter_ no longer perform **Find Next** and **Find Previous**, respectively. I'm also unable to close the Find Widget with _Escape_ (the same goes for the Replace Widget). Once I close/minimize the debug console, however, everything is back to normal. 
I couldn't find any keyboard shortcuts specific to the debug console that may be overriding the find widget shortcuts. Also, all find widget shortcuts are set to default.
A similar issue seems to have already been discussed and dealt with in #81272.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.5.1
flutter|Dar|3.5.1
code-runner|for|0.9.14
macros|ged|1.2.1
Kotlin|mat|1.7.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
autodocstring|njp|0.3.0
java|red|0.52.0
vscode-yaml|red|0.5.3
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
cif|thi|0.2.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1

</details>

**Comment by isidorn** [comment]
This is as designed, since the cmd + f focused the debug console and you can start typing to filter.
I understand this might not be the optimal behavior now but we are looking into improving the find in the debug console, thus cmd + f will also in the future not open the editor find widget.

Please unset this keybinding 
repl.action.filter

![Screenshot 2019-11-15 at 15 49 04](https://user-images.githubusercontent.com/1926584/68952049-787fa280-07bf-11ea-8750-5ac6a281fa28.png)
