### ISSUE TITLE
Tab indentation keeps changing only for TypeScript files

### ISSUE THREAD

**Issue by NotoriousPyro** [microsoft/vscode#83837]
- VSCode: 1.39.2
- OS Version: 10.0.18362 x64

Steps to Reproduce:
1. Use the following settings.json:

```
{
    "diffEditor.ignoreTrimWhitespace": false,
    "git.confirmSync": false,
    "git.autofetch": true,
    "go.useLanguageServer": true,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "workbench.tree.indent": 32,
    "editor.renderWhitespace": "all",
    "git.suggestSmartCommit": false,
    "editor.autoIndent": false
}
```

2. Open a .ts file and set the spaces to 4.
3. Navigate to a different file and then back to the .ts file, the spaces is now back to 1.

Does this issue occur when all extensions are disabled?: Yes

Even with tab size configured to 4 and auto-detect indentation to off, the file is still incredibly hard to read due to the formatting problem of changing back to 1 space...
![image](https://user-images.githubusercontent.com/706132/68032722-2ebe9480-fcb6-11e9-86af-51b08e3e64b0.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is this issue reproducible with all extensions disabled?
Do you have any extensions that perform formatting (Prettier, Editorconfig etc.)?

**Comment by NotoriousPyro** [comment]
> Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Yes, sorry for that - usually this line is last one so missed this line in the middle.

May be related to #52321? If detected was cached before disabled?

Do I understand correctly that there no similar behavior with non `.ts` files?

This behavior us controlled with ` "editor.tabSize"` setting, so you can check if there is similar configurations in  Workspace settings (may be in language specific section `"[typescript]"`)?

In the mean time options are:
1. Remove ` "editor.tabSize": 1` if it exists in any config file.
1. Add `"editor.tabSize": 4` to force required indentations.
1. Explicitly pick Convert Indentation to Spaces with if this one is needed ("set the spaces to 4.").


/cc @rebornix

**Comment by alexandrudima** [comment]
@NotoriousPyro Does this occur in any folder that you open? (Maybe there is a `settings.json` in `.vscode` in the folder you open?)

Are you sure you don't have `editorconfig` running (that extension is usually overriding the indentation settings of VS Code)?

**Comment by NotoriousPyro** [comment]
Resolved:
> Are you sure you don't have editorconfig running (that extension is usually overriding the indentation settings of VS Code)?
