### ISSUE TITLE
A tiny little ambiguity problem with markdown in comments

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#8383]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.3

<img width="625" alt="screen shot 2016-06-28 at 6 40 17 pm" src="https://cloud.githubusercontent.com/assets/2157285/16419066/9b199da4-3d61-11e6-9620-462d24c5a9ae.png">

This is a very tiny ambiguity with the markdown's grammar inside a comment. I think it's maybe nothing and not even worth checking but I think having a slash scape sequence would be nice.

**Comment by bpasero** [comment]
@pmkary whatever you can do there is defined by the typescript language. I am not sure what you are asking for, please report it to the typescript team.

**Comment by pmkary** [comment]
@bpasero oh I'm terribly sorry, I thought the markdown thing is a native vscode module. thanks for your time :D.

**Comment by bpasero** [comment]
@pmkary from the screenshot it looks as if you are typing into a JS or TS file?

**Comment by pmkary** [comment]
Yes. you see, when you want to use markdown commenting in JS/TS or anything that comes in flavor of c comment style, there comes a problem when you want to bold a path as `**/` in start of these pats indicates comment's ending. I thought it would be good to have `\/` scape sequence so that you can do so. But I'm not sure if this has anything to do with vscode.

**Comment by bpasero** [comment]
Right, but this is really something the language has to support, nothing we can do on top.

**Comment by pmkary** [comment]
thanks a lot again 👍
