### ISSUE TITLE
improve tdd ability

### ISSUE THREAD

**Issue by peni4142** [microsoft/vscode#83839]
Hi guys,

I don't like to close VSCode, run a test, wait for a new VSCode instance while developing.
I am ok with that, that some VSCode API need that, but when I think of interfaces like TreeDataProvider, I think there should be no problem to use that in a unit test.

Best regards
Peer

**Comment by octref** [comment]
If you meant you'd like to run the integration test while running VS Code, you can either:
- Use a `launch.json`
- Develop on https://code.visualstudio.com/insiders/ and run the tests in stable
