### ISSUE TITLE
Adopt insert&replace range for snippet completions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#83834]
For https://github.com/microsoft/vscode/issues/10266 we are adding insert and replace ranges to completion items. Provider that currently provide a range only need to be adopted and snippets is one of them.

**Comment by TylerLeonhardt** [comment]
Nice! How do I use this? Since snippets are static I'm curious how I specify the range in the json file

**Comment by jrieken** [comment]
The snippet prefix decides: https://github.com/microsoft/vscode-internalbacklog/issues/745#issue-481027114

**Comment by TylerLeonhardt** [comment]
So if the prefix is exactly the same as the start of the snippet, it will do a replace? Am I interpreting that correctly?

And if they're not exact, no replace happens?

**Comment by jrieken** [comment]
yes

**Comment by jrieken** [comment]
To verify: have a snippet with prefix "foo" and insert it at '|foo', 'f|oo', and 'foo|'. Insert via tab and shift+tab to toggle between insert and replace mode

**Comment by rebornix** [comment]
Tested all three cases for `foo`, `f|oo` and `foo|` work as expected but `|foo` doesn't.

Snippet

```
{
	 "Print to console": {
		"prefix": "foo",
		"body": [
			"console.log('$1');"
		],
		"description": "Log foo to console"
	}

}
```

* Put cursor before `foo`
* Trigger suggest
* Move focus to `foo` snippet in suggest widget
* Shift+Tab and Tab behave the same

**Comment by TylerLeonhardt** [comment]
This is working! (minus the scenario @rebornix mentioned) I'll update our snippets to have a prefix that lines up with the body. Thanks!

**Comment by jrieken** [comment]
I have extracted https://github.com/microsoft/vscode/issues/86386
