### ISSUE TITLE
Separate terminal window opens when I use ssh client in integrated terminal

### ISSUE THREAD

**Issue by JeffyOLOLO** [microsoft/vscode#83830]
Issue Type: <b>Bug</b>

Every day I connect to a remote machine using ssh (not Remote-SSH, just Windows OpenSSH native client) and internal terminal.

After some time (a few tens of minutes) terminal window with ssh session opens in a separate window. When I scroll the window int. terminal is also scrolled, but not vice versa.

I did not find out why this happens. Just after some command, the window opens.

It lasts at least six months.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
gitlens|eam|10.1.1
tslint|eg2|1.0.44
vscode-terminals|fab|1.12.6
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
remote-browser|spr|0.7.3

</details>

**Comment by JeffyOLOLO** [comment]
Attaching screenshot:

![image](https://user-images.githubusercontent.com/34167060/68029571-28cdb100-fcc0-11e9-8e2c-fe67e44b7397.png)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
