### ISSUE TITLE
Unlock issue #10121 to allow people voting for it

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#83843]
Issue #10121 is about allowing for floating and detachable windows for better multimonitor support. 

Detachable workbench parts are on the [2019 Roadmap](https://github.com/microsoft/vscode/wiki/Roadmap) since the beginning of the year. 

It's the most upvoted feature request, but in Dec 3, 2018 microsoft has locked and limited the conversation, with the justification that this would be addressed in the future. 

But since then, no progress has been made and people cannot upvote this feature anymore. 

If it's not going to be addressed in the future due to "architectural issues" then at least the conversation should be unlocked and the community should be allowed to vote for it and comment in the issue.

**Comment by gjsjohnmurray** [comment]
Perhaps also add your vote to https://github.com/isaacs/github/issues/771

**Comment by egamma** [comment]
@pedrogarcia we have already acknowledged this feature request on the roadmap (see below). Therefore no more upvotes are needed. 

Apologies that we did not yet get to this feature request yet. We will not remove it from the Roadmap when we update it (which will be soon). 

>Support for detachable workbench parts is our most upvoted feature request which due to architectural issues is challenging to implement. We will explore how we can work around this limitation. This investigation will focus on detaching terminals (2nd most upvoted feature request) and editors.
