### ISSUE TITLE
Zoom in one window zooms them all

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/vscode#83848]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.19008

Steps to Reproduce:
1. Open multiple VS Code windows with files open
2. Press Ctrl-+ in one of them

Does this issue occur when all extensions are disabled?: No

#24226 is related here but it talks more about setting the defaults for a window separate from another window. In this case I'm interested in zooming only the contents of one windows interactively and independently from all others. There are several scenarios including the multi monitor case.

**Comment by bpasero** [comment]
To zoom the current window only, add it to workspace settings.

**Comment by jeffmcaffer** [comment]
Thanks for the pointer Ben but I'm bot sure where I would use that in my daily life as it is not the workspace that needs zooming, rather a particular window on that monitor at that point in time. For example, I am demoing or just moved a window to a different monitor for a bit. I have 4k on my laptop but only HD on the projector etc etc.

The precedent that I'm used to and appreciate is Chrome. Open two Chrome windows and press Ctrl-+ in one. Only that window changes. (actually there appear to be some scenario of duplicate tabs zooming together).  Even multiple tabs in the same window zoom independently. Given that VS Code content tends to be more consistent than web pages, I'm not sure that would be good but whole windows zooming independently makes sense at least to me.

**Comment by jeffmcaffer** [comment]
@bpasero, thoughts on revisiting this? Another related scenario is that I often end up running standalone (just with the laptop screen), with 3 screens (laptop and two external 4k montiors), or with 2 screens (one external projector/TV with varying resolution). Depending on the situation, different windows will be on different monitors and need to be zoomed or not. In most cases the situation is "transient" in that a minute later I'll move to a different room/situation and need different zooming.

**Comment by bpasero** [comment]
Hey Jeff :). Sorry, I think I should have not closed this issue directly as we have a new process in place for features like this (https://github.com/microsoft/vscode/wiki/Issues-Triaging#managing-feature-requests).

**Comment by ds0nt** [comment]
VSCODE cannot be used on multidisplay setups involving more than one DPI.

With a 4k monitor beside a 1080p monitor, it results in one monitor having giant text, and one having tiny text. 

So you must keep all your vscode windows on one screen.. or change your display settings constantly, if you have a (more and more common) setup like this.

Been annoying for some time :p as I have a 4kres zenbook pro

**Comment by ds0nt** [comment]
Dragging a window from one screen to the other blows the text up to twice the real-world size. in this case.
