### ISSUE TITLE
Icons missing in find widget in IE

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8384]
Ref: #8229

1. IE11, open https://microsoft.github.io/monaco-editor/index.html
2. Open the find widget - notice how match case and match whole world icons are missing

![screen shot 2016-06-28 at 16 26 25](https://cloud.githubusercontent.com/assets/1926584/16419241/3f199950-3d4d-11e6-9f40-0f07069b364a.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#148

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
