### ISSUE TITLE
Breadbrumbs: Don't select first symbol automatically when opening the picker

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83842]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.40.0-insider (37d34176a6ecf1d09b16a0cad11bb619f3b1e48f, 2019-11-01T10:19:19.506Z)
OS version: Windows_NT x64 10.0.19013

If you click the `...` breadcrumb to open the picker, we auto-select the first symbol, which also highlights the symbol in the editor and scrolls to it. This behavior can be jumpy/unexpected especially when the first symbol isn't close to the cursor (which can happen because of hidden symbols or symbol sorting settings). 

Here is an example of that (I have set  `"breadcrumbs.showFunctions": false`):
![jumping](https://user-images.githubusercontent.com/641685/68032841-ddea7400-fc94-11e9-8f55-9e7b2b0f5926.gif)

Ref: #69279

**Comment by jrieken** [comment]
verifier: selecting `...` doesn't select/reveal an item in the picker but selecting a symbol in breadcrumbs selects & reveals that item in the picker and editor.
