### ISSUE TITLE
Git asks for credentials twice

### ISSUE THREAD

**Issue by JMS55** [microsoft/vscode#83847]
Issue Type: <b>Bug</b>

* Commit locally
* Try to sync to a remote repository
* Put in username and password once
* VSCode asks for the username and password again

Log output after putting in the credentials the first time, and cancelling the second:
```
> git pull --tags origin master
> git show :src/player_controller.rs
From https://github.com/JMS55/roguelike
 * branch            master     -> FETCH_HEAD
> git push origin master:master
> git show :src/player_controller.rs
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/JMS55/roguelike.git/'
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.7-301.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1965)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|7.68GB (0.81GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-icon-theme|jtl|1.6.5
git-graph|mhu|1.17.0
rust|rus|0.7.0
tabnine-vscode|Tab|2.1.11

(1 theme extensions excluded)

</details>

**Comment by rmw1075** [comment]
I am experiencing this too, especially when I change directories. Both Putty and linux terminal do not ask me to input my password more than once to log in, and never when I change to a directory while within my account. 

Log output when I tried to log in and it prompted me for my password twice. Both times I typed in my correct password.

[14:12:46.926] Running script with connection command: ssh -T -D 41945 -o ConnectTimeout=15 **MYSERVERNAME** bash
[14:12:46.926] Install and start server if needed
[14:12:47.183] > Password:
[14:12:47.183] Got some output, clearing connection timeout
[14:12:47.184] Showing password prompt
[14:12:54.207] Got password response
[14:12:54.208] "install" wrote data to terminal: "********************"
[14:12:54.214] > 
[14:12:54.280] > Password:
[14:12:54.280] Showing password prompt
[14:13:00.401] Got password response
[14:13:00.402] "install" wrote data to terminal: "********************"
[14:13:00.443] > 
[14:13:02.979] > **redacted**: running

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the dialog which asks for credentials?

**Comment by JMS55** [comment]
![image](https://user-images.githubusercontent.com/47158642/68171647-a274d180-ff42-11e9-993e-ca3deee1b1aa.png)

**Comment by joaomoreno** [comment]
Got it. VS Code doesn't have a secure API to store credentials so we don't do it. I suggest you set up a credential manager such as https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by JMS55** [comment]
I'm sorry if I wasn't clear the first time. When I say that VSCode asks for credentials twice, I mean that when I want to sync my repo, it asks for it once, then *immediately* asks for it again right afterwards, even though I just gave it my info. Not giving it a second time causes the whole operation to fail. The issue isn't that it doesn't remember my info, it's that it asks for it twice for one operation. Additionally, VSCode used to save the info so long as I kept the window open. Was that removed?

**Comment by joaomoreno** [comment]
The sync operation is actually a pull and a push, that's why there are two prompts for auth. Not really sure why this broke for you, but VS Code was never saving the credentials. Maybe you had a storage credential helper configured and that stopped working all of a sudden?
