### ISSUE TITLE
[Web] Disable standard browser select all in settings editor 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83850]
**Repo**
1. On web
1. Go to settings editor and make sure it is focused
1. Use the browser/os select all keyboard shortcut (cmd+a)

**Bug**
All text on the page is selected

![Screen Shot 2019-11-01 at 11 18 33 AM](https://user-images.githubusercontent.com/12821956/68046542-58b58e00-fc99-11e9-9f27-0710fe5ee7c5.png)

**Comment by roblourens** [comment]
Can I disable "select all" without disabling text selection? I want names and descriptions to be select/copyable.

**Comment by mjbvz** [comment]
In the editor, don't we intercept the cmd+a keyboard event and call preventDefault if required?

**Comment by roblourens** [comment]
In desktop, I get this when pressing cmd+a on the settings page

```
[renderer1] [trace] CommandService#executeCommand editor.action.selectAll
[renderer1] [trace] telemetry/commandExecuted {"id":"editor.action.selectAll","from":"menu"}
```

which is weird
