### ISSUE TITLE
Random Freezes (100% CPU Usage) on Linux

### ISSUE THREAD

**Issue by luciancaetano** [microsoft/vscode#83859]
- VSCode Version: 1.39.2-1571154070_amd64
- OS Version: Linux Mint 19

Steps to Reproduce:

1. Open a project and change code and save
2. Randomly the code begins to consume high cpu usage and freezes the entire environment, leaving the ide completely unproductive in linux.
This error occurs on many bd-based systems (these are the ones I tested 

I do not bring more information because due to the high use of cpu can not reliate a ctions, just wait about 5 minutes for vscode to present a crash message, asking to reopen

Ocurr with extensions disabled.

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information
