### ISSUE TITLE
Feature Request: Allow to play Audio on Webview

### ISSUE THREAD

**Issue by nicolasshu** [microsoft/vscode#83853]
Hey, I'm definitely not as a good programmer as you guys, but because I deal with a lot of audio, I would really appreciate if you guys could add in a feature to work with IPython.display.Audio or with videos as per 

- https://github.com/microsoft/vscode-python/issues/3405
- https://github.com/microsoft/vscode/issues/66050
- https://github.com/microsoft/vscode/issues/80196
etc

I don't know how difficult this would be to do, but I'd really appreciate it. Although I really like VS Code, I keep finding myself going back to Atom ONLY because of this issue. 

Thank you very much! Much appreciated!

**Comment by mjbvz** [comment]
The thinking on supporting audio and video in webviews hasn't changed. Still out of scope

**Comment by mcmar** [comment]
@mjbvz Why is that out of scope? This is 100% killing every data science application on VS Code. Microsoft seems to care a lot about data science with VS Code. @jchlus is a Program Manager, Python AI/ Visual Studios dedicated to promoting data science in VS Code. 
And according to your past comment, all that's needed to support it is shipping a single codec in the build. https://github.com/microsoft/vscode/issues/32540#issuecomment-381847598
Maybe you could ship an alternative binary with the ffmpeg codec included? Or can you at least provide instructions on how to compile from source with ffmpeg support, like you say you do internally?

**Comment by mjbvz** [comment]
We have no plans to address this in the short term

The normal OSS builds should already include FFMpeg. Just follow the normal build instructions
