### ISSUE TITLE
Preview is in stale state after undoing changes in source from Git view

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8385]
#7945

Steps to Reproduce:

1. Open a .md file (You can use the one in vscode workspace)
2. Open the preview on the right
3. Delete some content in the source and observe the preview is also updated
4. Close the source file
5. Go to Git view and undo the changes done to the source file

Observe that preview is still stale

**Comment by mjbvz** [comment]
It looks like this has been fixed:

![sep-20-2016 17-59-54](https://cloud.githubusercontent.com/assets/12821956/18694105/367ecf4e-7f5c-11e6-8cd0-2b203d7d71c8.gif)

You still have to have the file open in a VS editor. If you use the command line to revert the change, we do not pick it up. That work is tracked by #5687
