### ISSUE TITLE
Assignee search doesn't find users

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#83858]
[ this was pasted from my clipboard from the VS Code Issue Reporter as it claimed there was too much info to post ]

Issue Type: <b>Bug</b>

I am trying to enter an issue in Jira.  Everything goes smoothly until I have to assign it to somebody.  First of all there isn't a "assign to me" option.  There should be.

But moreso, I click in the field and am prompted to type to search.  So I enter my own userid.  It says Loading and doesn't find me and just says Type to search again.  Assignee is required so I can't complete the issue.

Extension version: 2.1.4
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.2.15-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2350)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.33GB (3.24GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Unclear what entering an issue into Jira has to do with a possible VSCode bug. If related to an extension, maybe report on the extension's support site.

**Comment by brianjmurrell** [comment]
As I prefixed the issue with, I tried to file this within VS Code and claimed there was too much info to post and directed me to here with a clipboard to paste into the issue.

**Comment by gjsjohnmurray** [comment]
I still don't understand how Jira fits into the picture.

Talking of pictures - can you post screenshots?

**Comment by brianjmurrell** [comment]
Jira is the VS Code plutin I was trying to report the issue about, using the VS Code "Help: Report Issue" feature, when it told me it couldn't post the report and instead copied it to my clipboard and opened this github issue for me to paste into.

Clearly **VS Code** did the **wrong** thing here and opened an issue against itself instead of the plugin that I was trying to report the issue against.

**Comment by gjsjohnmurray** [comment]
> Clearly **VS Code** did the **wrong** thing here and opened an issue against itself instead of the plugin that I was trying to report the issue against.

Agreed. Assuming the specific plugin/extension you tried to report the issue on uses a repository other than GitHub, this problem with the VS Code issue reporter is already logged as #73515

**Comment by alexandrudima** [comment]
Let's continue tracking in #73515
