### ISSUE TITLE
Extension viewlet uses weird clear icon

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#8386]
We don't use that icon anywhere else. I think we should align with search

![screen shot 2016-06-28 at 16 32 30](https://cloud.githubusercontent.com/assets/1794099/16419421/f701b962-3d4d-11e6-9727-8b44687229bc.png)

**Comment by bgashler1** [comment]
@jrieken you're correct.  @joaomoreno let me know if you need anything from me to make this happen.

**Comment by jrieken** [comment]
@isidorn Can you jump in for @joaomoreno 

@egamma, @bgashler1 pls yell stop if we shouldn't do this for June

**Comment by isidorn** [comment]
I think this should not be in for june - especially since we are now only fixing critical issues. 
If we still decide to do it I can look into it - it would have been easier if I was originally assigned to this issue though.
