### ISSUE TITLE
Markdown Preview Incorrectly Parsing and Rendering

### ISSUE THREAD

**Issue by falderol** [microsoft/vscode#83864]
Issue Type: <b>Bug</b>

Happens with and without extentions.

1. Make a codeblock with markdown syntax
2. Put in emphasis syntax
3. Activate markdown preview

\`\`\`markdown
no emphasis__emphasis__
no emphasis\*\*emphasis\*\*
no split emphasis
\*\* no \_\_split\_\_ emphasis \*\*
\`\`\`
![Capture](https://user-images.githubusercontent.com/27891045/68064375-b2917480-fce8-11e9-9e3b-f2cde94d627e.PNG)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (23.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-pdf|yza|1.4.1

</details>

**Comment by mjbvz** [comment]
The default highlighter is highlight.js but this can be customized: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-shiki
