### ISSUE TITLE
Marketplace returns net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by elsandosgrande** [microsoft/vscode#83860]
Though it might be in bad taste, I have already documented the issue in detail here: https://superuser.com/questions/1490528/visual-studio-code-marketplace-returns-err-empty-response

The issue persists with the latest update available to me, 1.40.0-insider ( https://az764295.vo.msecnd.net/insider/37d34176a6ecf1d09b16a0cad11bb619f3b1e48f/code-insider-1572603801.tar.gz ; I am using the script provided by https://gist.github.com/joaomoreno/7d3926e67e91317cd9d053c2c3956ddc to update). I am on Gentoo, latest updates. 
The system's GCC flags, which I have set in make.conf, are highly unlikely to be related to the issue in any way whatsoever, as the marketplace did work before some time around mid-August with pretty similar flags and the link which returns the empty response in VS Code has a proper response in Firefox Nightly.

And yes, I tried `--disable-extensions`, but it did not help. And no, I am not behind any kind of proxy.

**Comment by joaomoreno** [comment]
This seems more related to your system setup than an issue in VS Code. Do you have a firewall installed? Do you have connectivity issues in other apps?

**Comment by elsandosgrande** [comment]
No and no.

**Comment by joaomoreno** [comment]
Got it. If you disable the firewall does it work?

**Comment by elsandosgrande** [comment]
I am not certain if it is even enabled and my laptop is currently off. I shall report some time in the morning.

**Comment by joaomoreno** [comment]
OK let me know.

**Comment by elsandosgrande** [comment]
So...

~~~ bash
sandy@sandys-pavilion:~$ sudo iptables -vL -t filter && sudo iptables -vL -t nat && sudo iptables -vL -t mangle && sudo iptables -vL -t raw && sudo iptables -vL -t security
Chain INPUT (policy ACCEPT 484K packets, 652M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 240K packets, 21M bytes)
 pkts bytes target     prot opt in     out     source               destination         
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
Chain PREROUTING (policy ACCEPT 488K packets, 653M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 484K packets, 652M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 240K packets, 21M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 240K packets, 21M bytes)
 pkts bytes target     prot opt in     out     source               destination         
iptables v1.8.3 (legacy): can't initialize iptables table `raw': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
sandy@sandys-pavilion:~$ sudo iptables -vL -t security
iptables v1.8.3 (legacy): can't initialize iptables table `security': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
~~~

My guess is that it is not a firewall issue.

**Comment by joaomoreno** [comment]
I don't understand that output, since I'm not familiar with iptables. Can you completely disable iptables and see if you still hit the issue?

**Comment by elsandosgrande** [comment]
Going off of https://wiki.gentoo.org/wiki/Iptables, I don't think that iptables are an issue, since all of the policies are set to ACCEPT, as shown in the output above. That, and I haven't really found a way to "disable" iptables. At least not one which I understand.

After updating to https://az764295.vo.msecnd.net/insider/86405ea23e3937316009fc27c9361deee66ffbf5/code-insider-1573062315.tar.gz, the issue persists. This time, I decided to take a peek at the network tab in the developer tools. It shows that a few `extensionquery` requests get canceled.

![extqry canceled proof](https://user-images.githubusercontent.com/40576902/68382603-5d27ee00-0154-11ea-9248-3d8ad48cbadb.png)

**Comment by joaomoreno** [comment]
Right. Since no one else reports this, it can't really be an issue with VS Code. There's something in your system/network which is blocking these requests... we really can't help you with that.

**Comment by elsandosgrande** [comment]
The weirdest thing is that I can actually get a response if I copy the exact address into Firefox. Then the response is JSON that states that POST requests are not supported. If it were something on my network, would it really be able to discriminate between Firefox and VS Code if the request is the same?

Also, those cancelled request appear to have never been sent in the first place, which is just perplexing.

If you know somewhere better than SuperUser to post this question, I'm all ears. StackOverflow is not an option, since they always point to the former service for asking these kinds of questions.

**Comment by enderdzz** [comment]
Hi, @elsandosgrande I met the same issue unsolved this week until I realized that maybe it's a matter of my environment variables setting for network proxy use. So I just unset $http_proxy / $https_proxy / $all_proxy and corresponding uppercase of these vars.
And it works! A little wired though..

> vscode pkg i installed: code_1.40.2-1574694120_amd64.deb
> os: ubuntu 18.04.3 LTS

**Comment by elsandosgrande** [comment]
@enderdzz 

~~~ bash
root@sandys-pavilion:/usr/src/linux# unset $http_proxy $https_proxy $all_proxy $HTTP_PROXY $HTTPS_PROXY $ALL_PROXY
root@sandys-pavilion:/usr/src/linux# unset ${http_proxy} ${https_proxy} ${all_proxy} ${HTTP_PROXY} ${HTTPS_PROXY} ${ALL_PROXY}
~~~

This made no difference. I have never used a proxy in my life for that matter...

**Comment by elsandosgrande** [comment]
@joaomoreno @enderdzz 

I have finally found a solution! I came across https://github.com/electron/electron/issues/13829 today. In there, I saw an option, `--no-proxy-server`. I went like "Eh, might as well...". Well, **it works**!!! 

Now, I also came across this ticket as well: https://github.com/electron/electron/issues/21253
According to it, it is a confirmed issue with Electron version 7. Why did I think to look into Electron itself? Well, I already said it here: https://forum.level1techs.com/t/electron-applications-unable-to-connect-to-internet/151788

Once you have examined this reply, do with the ticket as you see fit.

**Comment by joaomoreno** [comment]
Thanks for the update @elsandosgrande, great findings! Let's keep the current strategy and use the flag workaround for now.

**Comment by elsandosgrande** [comment]
@joaomoreno On that note, how about having `--no-proxy-server` as one of the flags to use during troubleshooting instead of just saying "Check your proxy settings.", especially given that it's possible to be in a situation similar to mine? Just a though.

Have a nice day!
