### ISSUE TITLE
Install from VSIX... does not install from VSIX if extension has been uninstalled

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#83861]
Issue Type: <b>Bug</b>

We've had cases where installing a new version of our beta extension doesn't seem to actually install it.  This is one scenario where I can definitely repro, although I'm not positive it's the only one.

1. Find a VSIX to experiment with (I can e-mail mine two versions if you want)
2. Make a copy of the VSIX, rename both to be clear (e.g. vsix1.vsix, vsix2.vsix)
3. Rename them to .zip files
4. Add a version1.txt file to vsix1 and a version2.txt file to vsix2 (in the extensions folder)
5. Rename back to .vsix
6. Use Install from VSIX...  to install vsix1, then vsix2, then vsix1.  After each install, verify on disk that the expected version{1,2}.txt file is in the extension folder (home/.vscode-insiders/extensions/{extensionfolder}
7. Install vsix1
8. disable the extension from vscode's extensions pane
9. Use Install from VSIX... again to install vsix2
!) If you check on disk, you'll see that it's actually vsix1 that is installed
EXPECTED: For Install from VSIX..., it should always install from the actual VSIX, and not simply restore what is currently on disk.

VS Code version: Code - Insiders 1.40.0-insider (37d34176a6ecf1d09b16a0cad11bb619f3b1e48f, 2019-11-01T10:19:19.506Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.16GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.8.1-alpha

</details>

**Comment by sandy081** [comment]
Can you please provide the vsixs you used, so that it will be easy for me to reproduce what you are seeing. Guess the steps remain same with the vsixs you provided.

**Comment by StephenWeatherford** [comment]
Simplified the repro.  However, the bug seems to have been fixed (and in particular, rather than simply enabling the extension disabled extension when vsix2 is installed and vsix1 is disabled,  it installs vsix2 but keeps it disabled).  Thanks.
