### ISSUE TITLE
Terminal not launching

### ISSUE THREAD

**Issue by haysaaron** [microsoft/vscode#83865]
The terminal process command 'C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: {2})

This issue just started today out of nowhere as I used VSC yesterday with no issues
I have tried my best for 5hours. Resetting my computer but no joy.

**Comment by gjsjohnmurray** [comment]
Maybe caused by a Windows update you just got? Did you look at suggestions in #73790?

**Comment by Tyriar** [comment]
> C:\WINDOWS\Sysnative

Are you using the 32-bit client on a 64-bit machine?
