### ISSUE TITLE
#region folding/expanding stops working with PowrShell ps1 file

### ISSUE THREAD

**Issue by tinojr** [microsoft/vscode#83877]
I have the latest update of vscode. i added #region stuff #endregion stuff to portions of my code (.ps1 file) and it all worked well. while most of the regions were collapsed, i did a search and replace for a line of code, selected replace all. afterwards my collapsed regions were not expandable. Even if i removed the #region, the code inbetween dissappeared. I opened in ISE editor and everythign works as expected collapse/expand and code is there. so it's an issue with vscode.s too large to send. Please paste.

**Comment by tinojr** [comment]
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

This seems to affect more than regions. i can't expand or collapse anything, such as functions, if statements, etc. Have not experience this problem ever, not sure if it's coincidence or result of trying to use #region .
Step 1: open ps1 file, expand collapse different areas.
Step2: add #region #endregion to various sections of code.
Step3: Do a search and replace (CNTRL+H) and replace all
Now nothing is able to collapse and expand.
Resolution: close vscode, reopen vscode. seems to work now.

**Comment by mjbvz** [comment]
Please file this against the powershell extension
