### ISSUE TITLE
Horizontal lines glitch in editor selection (Edge)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8387]
#8229

1. Edge, open https://microsoft.github.io/monaco-editor/index.html
2. Select some text in editor -> notice horizontal lines in selection that have the color of the editor background (both in light and dark theme)

![screen shot 2016-06-28 at 16 35 58](https://cloud.githubusercontent.com/assets/1926584/16419581/88052eb2-3d4e-11e6-9115-8d8d41a83488.png)

**Comment by alexandrudima** [comment]
This has already been fixed for August
