### ISSUE TITLE
Slight red warning on vs code while wrapping react components in <> and </>

### ISSUE THREAD

**Issue by ratnabh** [microsoft/vscode#83872]
![Screenshot 2019-11-02 at 7 46 24 PM](https://user-images.githubusercontent.com/38026695/68072239-783bdc00-fda9-11e9-8aa5-8673e025b1ba.png)
You see when i use <> tags and ended with </> tag after that vs code shows me slight red warning by showing all the code in dim red colour ...any possible solution ?

**Comment by mjbvz** [comment]
This is caused by the babel grammar extension
