### ISSUE TITLE
can we register/unregister keybinding dynamicly?

### ISSUE THREAD

**Issue by fatfatson** [microsoft/vscode#83871]
now a keybinding could only be configured in manifest,
but if I want to make an extension for changing keybinding at runtime according to a workspace based config file, there's no API for it.

my final purpose is to have a workspace based keybindings, 
in different workspace I may bind 'alt+x' to different task,
so I will make a binding config for each workspace and let the extension read it then do something.

**Comment by alexandrudima** [comment]
@fatfatson keybindings can be made "dynamic" in two ways:
1. use context keys. You can define a keybinding to run a certain command when a certain context holds. [Here](https://github.com/microsoft/vscode-extension-samples/blob/a8af0838d6b3228bbebddb3727d1360829d7cd0a/vim-sample/src/extension.ts#L233-L248) is an example of how you can create custom context keys and set them to custom values.
2. use a command that is implemented in your extension and which executes different things based on the current workspace.
