### ISSUE TITLE
download insiders versions more easily

### ISSUE THREAD

**Issue by ratatoeey** [microsoft/vscode#83874]
https://github.com/microsoft/vscode/issues/82434 is not a duplicate. I think.

so here's what I wanted to do. insider updates need resources and I don't want to waste them. And I only want specific versions of vscode insiders that meet a criteria, for me its electron version updates. But no good solution was found, so I either don't update or have to go through a tedious process.

**the process->**
first, open vscode-insiders.
check for updates.
click on download updates to find the url of the file. `https://az764295.vo.msecnd.net/insider/a14de79ac74f2e0e6566d3cc9410eeb7dc769cde/VSCode-win32-ia32-1.40.0-insider.zip`

from that you get the commit `a14de79ac74f2e0e6566d3cc9410eeb7dc769cde`, now go to `https://github.com/microsoft/vscode/compare/` 
now, check the version of installed vscode-insiders from Help->about and copy that. get the commit from that which is->
`b7b21844e760e632f39bedf651da2bc93f54b0cc`

on the `https://github.com/microsoft/vscode/compare/`  page, select `b7b21844e760e632f39bedf651da2bc93f54b0cc` as base and the other commit as compare.
check if the `.yarnrc` file was changed. 

if it was, go to the url and download it. then go to `https://code.visualstudio.com/insiders/` and click on the link look at the sha256 hash, copy it and paste it in a text file. verify the expectd and calculated file hashes.

----

this is not perfect and only possible when I have (too much) free time. a better solution would be welcome.

I think being able to find the commits for previous insider releases might improve the lives of insiders that don't want to waste resources. I hope improvements will help everyone that uses it.

also please see https://github.com/microsoft/vscode/issues/82434#issuecomment-549058102

----

regards ratatoeey

**Comment by ratatoeey** [comment]
here is the current link, till it gets outdated.
https://github.com/microsoft/vscode/compare/b7b21844e760e632f39bedf651da2bc93f54b0cc...a14de79ac74f2e0e6566d3cc9410eeb7dc769cde



----

regards ratatoeey

**Comment by joaomoreno** [comment]
This doesn't seem like a useful thing for many people, definitely out of scope for us.

But here's something which can help you: https://update.code.visualstudio.com/api/update/win32-x64/insider/latest It provides information about the latest available version for `win32-x64`, insider.

**Comment by liyuhang1997** [comment]
> This doesn't seem like a useful thing for many people, definitely out of scope for us.
> 
> But here's something which can help you creating some automation: https://update.code.visualstudio.com/api/update/win32-x64/insider/latest It provides information about the latest available version for `win32-x64`, insider.

The tools you provide are really useful, but limited to the latest version.
I'm trying to find out in which insider version a bug was introduced, but vscode only seems to keep the latest insider version in the server
