### ISSUE TITLE
Search and replace box bleed

### ISSUE THREAD

**Issue by Richienb** [microsoft/vscode#83882]
- VSCode Version: 1.39.2
- OS Version: Windows 10 Version 1903

Steps to Reproduce:

1. In any file, open the search and replace box.
2. Scroll up in the editor.
3. You get this:
![Search and replace box bleed](https://user-images.githubusercontent.com/29491356/68080241-5c454280-fe5c-11e9-9e12-8ef7cbaf0364.png)

Does this issue occur when all extensions are disabled? **Yes**

**Comment by usernamehw** [comment]
```js
"editor.find.addExtraSpaceOnTop": false,
```

**Comment by Richienb** [comment]
Whoops.
