### ISSUE TITLE
Editor context menu on diff view has strange text color

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8388]
Ref: #8229

1. Any browser, open https://microsoft.github.io/monaco-editor/index.html#
2. Trigger context menu on a diff view, notice how the text is blue - not like if I would to trigger a context menu on a regular editor

![screen shot 2016-06-28 at 16 39 44](https://cloud.githubusercontent.com/assets/1926584/16419734/1bd9c300-3d4f-11e6-97fa-ca0b095aa589.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#149

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
