### ISSUE TITLE
Weird visual bug

### ISSUE THREAD

**Issue by happynger** [microsoft/vscode#83881]
Issue Type: <b>Bug</b>

The issue is purely visual. It only appears when I don't do anything for about 2 seconds. Unfortunately I can't reliably reproduce this issue and the developer tools console doesn't have any errors in it. The screenshot has the extensions enabled but I checked and it still persists with them disabled. The bug disappears whenever something happens, including button presses, mouse movement, etc.

VS Code version: Code - Insiders 1.40.0-insider (a14de79ac74f2e0e6566d3cc9410eeb7dc769cde, 2019-11-02T00:39:42.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
gitlens|eam|10.1.1
better-cpp-syntax|jef|1.14.12
python|ms-|2019.11.42643-dev
cpptools|ms-|0.26.1
debugger-for-chrome|msj|4.12.1
awesome-flutter-snippets|Nas|2.0.3
material-icon-theme|PKi|3.9.1
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0
city-lights-icon-vsc|Yum|1.1.3

(4 theme extensions excluded)

</details>

<details>
<summary>Additional</summary>

![vscbug](https://user-images.githubusercontent.com/43358033/68078164-f094a400-fd8d-11e9-80c7-f8f56eee4736.png)

This is the developer tools performance tab profile. The issue starts at about 20000ms when cpu starts rasterizer thread 2
[Profile-20191102T165402.zip](https://github.com/microsoft/vscode/files/3801079/Profile-20191102T165402.zip)

This is what happened with vscode when i left it on for a little bit
(This was captured on my phone since trying to make a snippet removes the visual)
![IMG_20191102_180640](https://user-images.githubusercontent.com/43358033/68078837-d792ef80-fd9b-11e9-891c-f874503160e4.jpg)

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

**Comment by happynger** [comment]
Sorry It took so long but the problem with this bug is that its inconsistent. I had this bug before (on a different computer) once but it resolved itself in a day or two which was very strange. As of right now this bug has "fixed" itself on my computer and doesn't occur anymore thus I can't really test the disable GPU support. So i think I will close this issue soon and if it ever comes back I will send you the results of the command you said to run, thanks and sorry I couldn't help much...

**Comment by happynger** [comment]
Just wanted to put it here last time I found out that the issue also repeated on the windows app "Trello" which i found out is also built on electron framework so i assume its the problem on their part...
