### ISSUE TITLE
Only a window of VSCode is whitish.

### ISSUE THREAD

**Issue by kohei84** [microsoft/vscode#83885]
Though the response was normal, only a window of Visual Studio Code seems to be white fog, in every monitor.
That was a sudden affair, but I was doing then, only seeing WEB on GoogleChrome.
The following I had tried, but a result didn't change.
1.OS(Windows 10) restart, included Windows Update.
2.I had uninstalled VSCode, I had deleted all setting files . Next, I had installed VSCode once again.
![window_of_VSCode_is_active](https://user-images.githubusercontent.com/44178629/68080737-b508e100-fe44-11e9-8434-90fc5c645233.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by kohei84** [comment]
Thank you for the information.
I could confirm that there was no problem, I tried using this.

**Comment by bpasero** [comment]
Ok, this will be released as 1.40 this week.
