### ISSUE TITLE
VSCode cannot open Unity C# project

### ISSUE THREAD

**Issue by mattylase** [microsoft/vscode#83893]
- VSCode Version: 1.39.2
- OS Version: Windows 10.0.18362 Build 18362

Steps to Reproduce:

1. Attempt to open C# file from Unity by double clicking on a file
2. Observe the "thinking" wheel by the cursor for a moment, but VSCode does not launch.

Alternatively:
1. Open VSCode
2. Attempt to open Unity C# project by using `File -> Open Recent -> {Project Name}`
3. Nothing happens

Alternatively:
1. Open VSCode
2. Attempt to open Unity C# project by using `File -> Open Folder -> {Project Top Level Directory}`
3. Nothing happens

Alternatively:
1. Open VSCode
2. Attempt to open Unity C# project by clicking on the project name in *Recent* list on Welcome page
3. Nothing happens

Alternatively:
1. Open Powershell
2. Execute `code {project-directory}`
3. Command executes, VSCode does not open

Alternatively:
1. Open Powershell
2. Execute `code --disable-extension {project-directory}`
3. Command executes, VSCode does not open

Does this issue occur when all extensions are disabled?: Yes

**Comment by mattylase** [comment]
I'm able to open folders nested within the project's main directory and then open C# scripts that way way, however there is no Intellisense, error highlighting, linting, etc.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by mattylase** [comment]
@bpasero looking good in the latest insider! Apologies on not testing before opening the issue, but was frustrated on my Saturday. 🍻
