### ISSUE TITLE
MacOS "Git not found" error, unable to use git tools

### ISSUE THREAD

**Issue by kbakk** [microsoft/vscode#83896]
On MacOS 10.14.6. Git and VS Code has worked without issues until recently (~Thu. Oct 31).

No issues with git

```
$ git --version
git version 2.23.0
git
usage: git [--version] [--help] <snip>
```

Issue seems similar to #81287. Running Xcode command returns an error

```
sudo xcodebuild -license
Password:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Tried to reinstall xcode commandline tools, but the license command still behaves the same. Running `/Library/Developer/CommandLineTools/usr/bin/git` does not return any license prompts (just standard git help output), so I don't think this is license related. Doubt it's Xcode git which is being used in the first place, `which git` returns `/usr/local/bin/git` (symlinked to brew managed git). 

Also, the Kubernetes extension (by Microsoft) also reports issues with kubectl in path: "Could not find "kubectl" binary. Cannot execute command."

Checking to see if the node process can find these tools using Developer Tools console:

```
const { spawnSync} = require('child_process');
spawnSync('command', ['-v', 'git']).stdout.toString()
spawnSync('git', ['--version']).stdout.toString()
spawnSync('kubectl', ['version', ' --client']).stdout.toString()
```

Output:

```
"/usr/local/bin/git
"
"git version 2.23.0
"
"Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
"
```

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
cucumberautocomplete|ale|2.14.1
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.2.3
better-toml|bun|0.3.2
solargraph|cas|0.21.1
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
gitlab-ci-validator|cst|1.0.0
vscode-markdownlint|Dav|0.31.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
xml|Dot|2.5.0
gitlens|eam|10.1.1
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
prettier-vscode|esb|2.3.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
vscode-pull-request-github|Git|0.12.0
jsonnet|hep|0.1.0
jmespath-vscode|jam|0.0.3
vscode-peacock|joh|3.1.6
json-escaper|jos|1.1.0
php-cs-fixer|jun|0.1.127
AWK|lug|0.0.2
VS-code-vagrantfile|mar|0.0.7
vscode-rufo|mbe|0.1.1
dotenv|mik|1.0.1
swagger-doc-viewer|mim|1.0.4
azure-pipelines|ms-|1.157.4
vscode-docker|ms-|0.8.2
vscode-kubernetes-tools|ms-|1.0.6
python|ms-|2019.11.44724-dev
azure-account|ms-|0.8.7
debugger-for-chrome|msj|4.12.1
autodocstring|njp|0.3.0
indent-rainbow|ode|7.4.0
ruby|reb|0.25.3
vscode-yaml|red|0.5.3
vscode-table-formatter|shu|1.2.1
vscode-spotify|shy|3.1.0
code-spell-checker|str|1.7.18
html-preview-vscode|tht|0.2.5
vscode-todo-highlight|way|1.0.4
highlight-bad-chars|wen|0.0.3
jinja|who|0.0.8
copy-with-line-numbers|yas|0.0.4
markdown-all-in-one|yzh|2.5.1

(4 theme extensions excluded)

</details>

Steps to Reproduce:

1. Open directory with git initialized
2. Notice error "Git not found. Install it or configure it using the 'git.path' setting."

Expects: 

If I set `"git.path": "/usr/local/bin/git",` as suggested, it will work. 

It will then log

```
Looking for git in: /usr/local/bin/git
Using git 2.23.0 from /usr/local/bin/git
```

However, since git is in path, I'd expect it to work automatically (as it has been since I started to use VS Code).

Also, kubectl is not detected. There's probably a setting for this as well, but it should be picked up automatically. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What does the log say, if you don't set the setting?

**Comment by kbakk** [comment]
I removed `"git.path": "/usr/local/bin/git"` from settings to check the logs, and it works again as expected. I'm confused about this... Closing since I can't reproduce.
