### ISSUE TITLE
Duplicate defintion of json modules

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8389]
Ref: #8229

1. Any browser, open https://microsoft.github.io/monaco-editor/monarch.html
2. Notice duplicate definition of json modules warnings in console

![screen shot 2016-06-28 at 16 44 56](https://cloud.githubusercontent.com/assets/1926584/16419957/d7e5e808-3d4f-11e6-903c-43d8009624e2.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#150

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
