### ISSUE TITLE
${workspaceFolderBasename} invalid variable reference

### ISSUE THREAD

**Issue by tst-dsugar** [microsoft/vscode#83894]
I understand that ${workspaceRootFolderName} is deprecated.  However, I find that the replacement, ${workspaceFolderBasename}, does not work in string expansions, while the replacement for ${workspaceRoot}, ${workspaceFolder}, actually does.  In fact, I get "Invalid variable reference" for "${workspaceFolderBasename}".  This is in the cmake extension, expanding out build directory from:  

${workspaceFolder}/../../Builds/${workspaceFolderBasename}-Code-${buildType}

While this (and workspaceFolder) does work as expected:

${workspaceFolder}/../../Builds/${workspaceRootFolderName}-Code-${buildType}

Version: 1.39.2
cmake plugin 0.0.17

- VSCode Version: 1.39.2
- OS Version: OSX 10.14.6

Steps to Reproduce:

1. Set cmake build path to ${workspaceFolder}/../../Builds/${workspaceFolderBasename}-Code-${buildType}

2. Build cmake project

3. Get invalid error reference expanding workspaceFolderBasename, failure to build

4. Note it does produce a ../../Builds/${workspaceFolderBasename}-Code-Debug directory, so it only fails to expand this variable...

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
@tst-dsugar I tried with a simple task and I don't see the same issue. Do you see the same issue with this task:
```json
        {
            "type": "shell",
            "label": "Test workspaceFolderBasename",
            "command": "echo",
            "args": [
                "${workspaceFolderBasename}"
            ]
        }
```
Does the issue occur if you disable all extensions?
