### ISSUE TITLE
Wordwrap (Wrapcolumn) at specific character [plugin]

### ISSUE THREAD

**Issue by Tanato** [Microsoft/vscode#839]
First like to state that I know about the property "editor.wrappingColumn" but that's not what I'm looking for.

I was looking for some "smart" way of wrapping lines to be used mainly in JSON files (like in snippets for example) and I'm interested in build a plugin to wrap lines at a specific set of characters, like "\n" for example.

I did some search for some way to do that, but as I couldn't find any means seems to me that it's not possible with the API available today.

Any hints about this matter? Seems to me that is not the hardest thing to do, as it don't wrap lines in middle of words, but it will be really helpful.

**Comment by Bill-Stewart** [comment]
There is a good extension that may do what you want: https://marketplace.visualstudio.com/items?itemName=stkb.rewrap

**Comment by Tanato** [comment]
@Bill-Stewart that's an interesting extension but don't solve the main issue that is wrap line without creating a new one, so it can work without really create changes in your code so it can work seamless with source version control or in JSON files for example that you can't have a new line.

**Comment by Bill-Stewart** [comment]
Sorry, I misunderstood what you are asking. If I understand, you are asking about virtual line wrapping at specific characters rather than at a column width.
