### ISSUE TITLE
Editor view sometime jumps to first of the file

### ISSUE THREAD

**Issue by 2hamed** [microsoft/vscode#83907]
Issue Type: <b>Bug</b>

Some times when I switch back to VSCode from and another applications the editor view jumps to the beginning of the active source file.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3121)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.52GB (4.16GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
increment-selection|alb|0.0.6
vscode-database|baj|2.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.2.3
vscode-markdownlint|Dav|0.31.2
gitlens|eam|10.1.1
phpunit|ema|4.0.2
vsc-material-theme|Equ|30.0.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.2
Go|ms-|0.11.7
go-doc|msy|0.1.1
vscode-yaml|red|0.5.3
laravel-artisan|rya|0.0.26
tabnine-vscode|Tab|2.1.11
vscode-wakatime|Wak|2.2.1

(4 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Can you reproduce this when you are running with all your extensions disabled?

**Comment by 2hamed** [comment]
@gjsjohnmurray I will try, but since it's a random happenstance it may take some time.

**Comment by alexandrudima** [comment]
I think you are running into #28795
