### ISSUE TITLE
"reevaluateOnRerun": false should not reevaluate ${input:Go Run}

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode#83909]
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

`"reevaluateOnRerun": false` should not reevaluate `${input:Go Run}`
```
    {
      "label": "Go Run",
      "command": "go",
      "args": [
        "run",
        ".",
        "--",
        "${input:Go Run}"
      ],
      "isBackground": true,
      "runOptions": {
        "reevaluateOnRerun": false
      }
    }
```
```
"inputs": [
    {
      "id": "Go Run",
      "description": "go run . -- ${input:Go Run}",
      "default": "-v",
      "type": "promptString"
    },
  ]
```

It popups the input field on every `workbench.action.tasks.restartTask`

**Comment by alexr00** [comment]
`reevaluateOnRerun` is specific to `workbench.action.tasks.reRunTask` and not used in `workbench.action.tasks.restartTask`. We _could_ use it in Restart too, but then the naming is a bit confusing (rerun !== restart).

**Comment by gertcuykens** [comment]
Yes please because it doesn't make any sense to only allow it for rerun and not restart. Thanks

**Comment by gertcuykens** [comment]
What kind of `feature` policy is this? Suppose this was a security bug, are you going to close it if less then 20 people got there credentials stolen? I understand it's not important but just closing because nobody has time for it sounds wrong on so many levels. It's not a new feature, it's making a exiting feature consistent...
