### ISSUE TITLE
openOnFirstSessionStart does not work with git bash on windows

### ISSUE THREAD

**Issue by cemoktra** [microsoft/vscode#83905]
I'm using the git bash as the default shell on windows. When launching the the debugger a new terminal is opened every time. The openOnFirstSessionStart just works with cmd and PowerShell

**Comment by weinand** [comment]
How does your launch configuration (launch.json) look like?

**Comment by cemoktra** [comment]
Well one year later I'm working for a new company and have no windows setup anymore

**Comment by cemoktra** [comment]
Trying to add some more information. I was making cross platform builds. Uses MSYS and git bash as default terminal in vscode Then using gdb to debug a C++ application caused this problem.
