### ISSUE TITLE
launch: program 'mysqld' does not exist

### ISSUE THREAD

**Issue by RahulSisondia** [microsoft/vscode#83902]
Hi, 
I am able to compile mysql source with VSCode on **mac.**  
But, I am unable to launch the debugger with mysqld executable
 despite providing the correct path in the launch.json. 
VSCode keeps complaining that mysqld does not exist even though I have specified the correct path. I  tried specifying the complete path in the "program",  override in the  in the "cwd" but not none of them helped. 

Steps could be easily reproducible by downloading the mysql source from https://github.com/mysql/mysql-server

Installed the following program before compiling the source 
<img width="247" alt="Screenshot 2019-11-04 at 6 59 03 AM" src="https://user-images.githubusercontent.com/4783163/68095651-37d77d80-fed1-11e9-8bcb-548821afbfb2.png">

And the follow along the screenshots for other configuration files.

<img width="864" alt="Directory_structure" src="https://user-images.githubusercontent.com/4783163/68095664-60f80e00-fed1-11e9-9fb9-599c79a34c1c.png">

![launch_json](https://user-images.githubusercontent.com/4783163/68095757-29d62c80-fed2-11e9-917f-397bef3347b6.png)

<img width="838" alt="c_ccp_properties_json" src="https://user-images.githubusercontent.com/4783163/68095663-605f7780-fed1-11e9-85da-69161baa063b.png">

Here is **track.json**

{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "options": {
        "cwd": "../build_trunk"
    },
    "tasks": [
        {
            "label": "Server Cmake",
            "type": "shell",
            "command": "cmake",
            "args": [
                "-S~/work/mysql-dev/src",
                "-GNinja",
                "-DESIGNCODE=0",
                "-DIGNORE_AIO_CHECK=1", 
                "-DENABLE_DOWNLOADS=1",
                "-DWITH_DEBUG=ON",
                "-DENABLED_DEBUG_SYNC=1", 
                "-DBUNDLE_MECAB=OFF", 
                "-DWITH_MEB=0",
                "-DWITH_ROUTER=0",
                "-DWITH_BOOST=~/work/boost_1_70_0/",
                "-DWITH_CURL=system",
                "-DWITH_SSL=~/work/openssl-1.1.1d-macos10.14-x86-64bit"
            ],
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
               // "$gcc"
            ]
        },
        {
            "label": "Server Compile",
            "type": "shell",
            "command": "ninja",
            "args": [],
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}

**Comment by RahulSisondia** [comment]
I think I found the problem so I had to specify the **absolute path* , of executable in the **program** variable and, of current directory in **cwd** variable.  

 "program": "/Users/neo/work/mysql-dev/build_trunk/runtime_output_directory/mysqld",
 "cwd": "/Users/neo/work/mysql-dev/build_trunk/runtime_output_directory/",


Symbolic links in the path or relative paths did not work in my case.   Should those be considered an issue ?

**Comment by alexr00** [comment]
Glad you found the problem!

**Comment by RahulSisondia** [comment]
Hi  Alexr00, 
I have no problem with closing the issue but I am just  wondering. 
Should not the variable "program" accept the relative path w.r.t.  variable "cwd" ? 
Why symbolic links do not work here but they do in the track.json file ? 
If not fix at least should not this information be documented so that people don't waste hours troubleshooting what's going on. I spent hours to figure this out.

**Comment by alexr00** [comment]
I suspect that launch configurations don't expand `~`.
@weinand to confirm.
