### ISSUE TITLE
Menus missing with MacOS Catalina

### ISSUE THREAD

**Issue by nukdcbear** [microsoft/vscode#83904]
Upgraded to MacOS Catalina and menus disappeared in VS Code and cannot get them to display properly.

- VSCode Version: 1.39.2
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Upgrade MacOS to Catalina with system that already has VS Code installed

2. Uninstalled and reinstalled, after getting around the Apple has not verified the app error, and menu is still missing.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
@nukdcbear can you share a screenshot of the menu to which you are referring?

**Comment by nukdcbear** [comment]
![92E52C12-31C8-49C5-B12C-94BE8F7CB362_4_5005_c](https://user-images.githubusercontent.com/4625170/68157468-8e10e480-ff02-11e9-886d-03ec77b6c5ce.jpeg)

**Comment by nukdcbear** [comment]
Please close this ticket. Figured out what was missing and where it is.
