### ISSUE TITLE
Left Column window view change  

### ISSUE THREAD

**Issue by arpadpall21** [microsoft/vscode#83908]
Issue Type: <b>Feature Request</b>

I had hard time to figure out how to change the view in the left column window (must go through the view menu and even there is no self explanatory what those menu items will change) 
- I would love to see a view change icon on the top in the left  column window directly to easily change the views (between explorer, extensions, etc..)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sbatten** [comment]
If I understand correctly, what you were looking for is the icons on the left of the sidebar. The icons are in something called the "Activity Bar". It is used to changed the view in the "Sidebar".

![image](https://user-images.githubusercontent.com/6561887/68148732-66fde700-fef1-11e9-987e-abf4cf4bb9ed.png)
