### ISSUE TITLE
Syntax highlighting example does not highlight syntax

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8390]
Ref: #8229

1. Any browser, https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-syntax-highlighting-for-html-elements
2. Notice how the result has no coloring - I would expect some colors - or am I misunderstanding the sample?

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#151

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
