### ISSUE TITLE
terminal control + ` returen this massgae

### ISSUE THREAD

**Issue by mahmoudeldawy** [microsoft/vscode#83916]
Issue Type: <b>Bug</b>

when i click control + ` 
mac os mojave

The terminal shell path "shell" does not exist

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal|for|0.0.10

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by mahmoudeldawy** [comment]
this is gif of issue i can`t find log or something to trace 
this is the only error massage 
The terminal shell path "shell" does not exist
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47973839/68286661-25ed0a80-008a-11ea-8e96-516716cf4bbd.gif)

**Comment by Tyriar** [comment]
It looks like you either have `terminal.integrated.shell.osx` set to `"shell"` in your settings or the `$SHELL` environment variable is set to `"shell"` which is a problem you need to resolve outside VS Code.
