### ISSUE TITLE
Scroll bars in high contrast theme look broken (Edge)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8391]
Ref: #8229

1. Microsoft edge, open https://microsoft.github.io/monaco-editor/playground.html
2. Change to high contrast theme, notice how the scroll bars look broken (large light blue boxes)

![screen shot 2016-06-28 at 16 54 07](https://cloud.githubusercontent.com/assets/1926584/16420430/98753514-3d51-11e6-95df-650f7541677e.png)

**Comment by alexandrudima** [comment]
This has already been fixed for August
