### ISSUE TITLE
Support WebViews in extension contributed custom views

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83911]
Currently we only support trees. WebViews would open up many new possibilities.

**Comment by solomatov** [comment]
Are you interested in external contributions for this task? Do you have any WIP branch for it?

**Comment by alexr00** [comment]
I haven't had a chance to start on this yet and I wouldn't recommend it for PR since it's likely going to be big and complicated.

**Comment by usernamehw** [comment]
@mjbvz is this a duplicate of #46585?

**Comment by alexr00** [comment]
Yes, this is a duplicate of https://github.com/microsoft/vscode/issues/46585
