### ISSUE TITLE
Show Control Hover is not a good name for the action

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#83912]
IMHO using the keyboard modifier name in the action is not good, as IMHO the action name should describe what the action does, not one way in which the action is triggered.

This gets very confusing when configuring `"editor.multiCursorModifier": "ctrlCmd"`. In this case, the definition preview is rendered in the editor hover with `alt` + hover.

Perhaps a better name would be "Show Definition Preview Hover".

**Comment by alexandrudima** [comment]
Thank you!

**Comment by gjsjohnmurray** [comment]
Release notes still use the old terminology:
![image](https://user-images.githubusercontent.com/6726799/68379590-129f7500-0146-11ea-84a7-18c612846361.png)

Version: 1.40.0-insider (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T16:58:49.777Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by sbatten** [comment]
@gjsjohnmurray stable release notes should have the updates, thanks for checking it out
