### ISSUE TITLE
Web: support workspace files for extension development

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83922]
It looks like today we do not support opening of a code-workspace file for ext host development:

```ts
const f = findArgument('folder-uri');
if (f) {
	const u = URI.parse(f);
	gotFolder = true;
	addQueryParameter('folder', u.path);
}
if (!gotFolder) {
	// request empty window
	addQueryParameter('ew', 'true');
}
```

**Comment by weinand** [comment]
The problem is that in https://github.com/microsoft/vscode/blob/1711f6e293d72350df2d1d480f8bb2066100b87e/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts#L63-L105 file arguments are not handled at all. This includes both regular files as well as workspace files ("*.code-workspace").

**Comment by bpasero** [comment]
I think the only file to support would be those that end with `*.code-workspace`.

**Comment by weinand** [comment]
@bpasero Changing the code to this, solves the issue at hand:

![2019-11-05_15-47-18](https://user-images.githubusercontent.com/1898161/68218151-2632ca80-ffe4-11e9-8203-2179e9072197.png)

But there is still the problem of a non-folder workspace (green arrow above): if a file is passed from the launch config, how can I pass this into `workspaceProvider.open`?

![2019-11-05_15-52-28](https://user-images.githubusercontent.com/1898161/68218242-4c586a80-ffe4-11e9-8d7f-08e9ffda153f.png)

**Comment by weinand** [comment]
I've created https://github.com/microsoft/vscode/issues/83997 for the open issue.

**Comment by bpasero** [comment]
Thanks, works fine!
