### ISSUE TITLE
Ctrl+click navigation doesn't work for super class methods

### ISSUE THREAD

**Issue by beastie1888** [microsoft/vscode#83921]
- VSCode Version: 1.39.2
- OS Version: Linux x64

Steps to Reproduce:

1. Create a python class and inherit it in a separate python file.
2. In the inherrited class try to navigate to a method definition from the super-class (using CTRL + mouse click). The IDE navigates to the right line of the code but remains in the same file, not the super-class.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please file this against the python extension
