### ISSUE TITLE
Pressing up arrow in PowerShell terminal causes display glitch

### ISSUE THREAD

**Issue by bobbytreed** [microsoft/vscode#83920]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Run code containing backticks using F8
2. Press up arrow

Does this issue occur when all extensions are disabled?: Yes/No

Everytime I press up arrow to go back through history, VSCode extension output glitches.  Doesn't affect actual command being run.

Code run:           $results =
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $authHeader

After one up arrow: $results =
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $aut$results =iPrefix + "Microsoft.Advisor/" + "metadata/e2fa79e2-b3e0-11e9-a2a3-2a2ae2dbcce4" + "?api-version=2017-04-19"
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $aut$uri

After two up arrow:  $results =
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $aut$results =iPrefix + "Microsoft.Advisor/" + "metadata/e2fa79e2-b3e0-11e9-a2a3-2a2ae2dbcce4" + "?api-version=2017-04-19"
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $aut$results =    
                    Invoke-RestMethod `
                        -ContentType $contentType `
                        -Uri $uri `
                        -Method $action `
                        -Headers $aut$uri

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
