### ISSUE TITLE
Extensions search is including non validated extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#83926]
- Open Extensions viewlet and search for `nox`
🐛 Results include non validated extension `Nox Caleo` which is not found in Marketplace

**Comment by sandy081** [comment]
I can no longer repro this. So closing.

**Comment by kesane-msft** [comment]
@sandy081 - this might not be reproducing since the extension is now validated. You would need an extension which fails the version validation on Marketplace.
I believe #82746 is also related to this.

**Comment by sandy081** [comment]
@kesane-msft It would be great if you can help me coming up with such an extension?

**Comment by kesane-msft** [comment]
@sandy081 - try having an SVG badge from the non-whitelisted sources. That should endup giving you a version validation error.

**Comment by sandy081** [comment]
I came up with a vsix that has non-whitelisted svg path in the read me and I cannot publish it from Marketplace website has it is says invalid manifest. 

@joaomoreno @kesane-msft it would be great if you can suggest a way to publish such an extension.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/issues/98366
