### ISSUE TITLE
All terminal lines are being re-rendered, even when just a single line updates

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83936]
This increases the amount of work done when typing commands to be significantly more.

Upstream: https://github.com/xtermjs/xterm.js/issues/2534

**Comment by Tyriar** [comment]
Can't really verify this issue without debugging into the code, inside xterm.js (formatted) you will see an `onGridChanged` function, the args are start/end. Add a breakpoint to that function and verify the args are a range for a single like (eg. 15, 15) after typing a single character into the terminal. Here is the failing case where the terminal is re-rendering lines 0-15:

![image](https://user-images.githubusercontent.com/2193314/68148436-d921fc00-fef0-11e9-9e41-36f40946239a.png)

Use the canvas renderer to verify.

**Comment by Tyriar** [comment]
A better way to verify:

1. Switch to DOM renderer
2. Enable paint flashing:
   ![image](https://user-images.githubusercontent.com/2193314/68165743-0ed8dc00-ff15-11e9-87d9-6dceac074551.png)
3. When you type into the prompt only a single line will flash

**Comment by chrmarti** [comment]
Verified in latest (d39e6b39). Can this issue be closed?
