### ISSUE TITLE
Unable to configure tasks 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#83947]
When opening the command palette, followed by going to `configure tasks` the `tasks.json` file doesn't open ?

**Comment by rccoleman** [comment]
I suspect that this is related to this: https://github.com/cdr/code-server/issues/999

**Comment by SheepDomination** [comment]
Not completely, I'm not able to even create or open a `tasks.json` file ?

**Comment by rccoleman** [comment]
In my installation I just created a tasks.json file in my .vscode directory according to the instructions: https://code.visualstudio.com/docs/editor/tasks

But both ‘run task’ and ‘configure tasks’ behave as they do in the issue I linked to. Both used to work fine with the same tasks.json.

**Comment by alexandrudima** [comment]
Possibly related - #83946

**Comment by alexr00** [comment]
@SheepDomination What version are you using? There is https://github.com/microsoft/vscode/issues/83836, which would cause this behavior.

**Comment by SheepDomination** [comment]
@alexr00 1.36.2

**Comment by alexr00** [comment]
Can you try updating to 1.39.2? Also, after you run the Configure Task command, what does the next quick pick show? What option are you selecting from that quick pick? If you run the Run Task command are there any tasks listed?

**Comment by SheepDomination** [comment]
@alexr00 I make a mistake, I am running 1.39.2. 

The next quick pick shows; *Create `tasks.json` file from template*. I'm trying to select the option *Create `tasks.json` file from template*.  When I try to `Run Task` command, there are no tasks listed.

**Comment by alexr00** [comment]
Thanks for the details. I'm still not able to reproduce the issue though. Are there any other details about your setup? If you open the Developer Tools, do you see any errors in the console when you try to create the tasks.json file from the template?

This strongly resembles an issue that is in the insiders build 1.40, so I'm surprised you are seeing it here.

**Comment by SheepDomination** [comment]
There is this error from the console, when I try to create the tasks.json file from template;
``` 
ERR Cannot read property 'toResource' of undefined: TypeError: Cannot read property 'toResource' of undefined
    at quickInputService.pick.then.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4470:454)
```

**Comment by alexr00** [comment]
I was able to reproduce the error, but only with a strange setup: I have a workspace open, but the workspace doesn't have any folders. Is that your setup?

**Comment by SheepDomination** [comment]
@alexr00 My workspace has folders.

**Comment by sandy081** [comment]
@alexr00 Are you able to repro it? If so did you figure out the root cause? Can you also please check if #83946 is reproducible? 

Thanks

**Comment by alexr00** [comment]
I was not able to reproduce the error unless I have a workspace that doesn't have any folders. However, that isn't what @SheepDomination appears to be seeing.

@SheepDomination do you have a sample repository I can try with? Do you also see the issue from #83946?

**Comment by SheepDomination** [comment]
@alexr00 I saw the issue from #83946, I know it is mentioned they *may* related but I don't see how ?

**Comment by sandy081** [comment]
@SheepDomination Looks like you created both the issues. Can you please provide the set up (sample repo) to reproduce both issues.

**Comment by SheepDomination** [comment]
@sandy081 I simply tried to open my workspace settings and when I do, the file doesn't open.  If you want I can create a brief video ?

**Comment by sandy081** [comment]
We would need the set up, can you please create a sample repo in GitHub that can be used to repro.

**Comment by SheepDomination** [comment]
@sandy081 I'm new to repositories, I hope [this](https://github.com/SheepDomination/tcs/blob/master/settingsvscode) helps ?

**Comment by sandy081** [comment]
> I simply tried to open my workspace settings and when I do, the file doesn't open. If you want I can create a brief video ?

It would be great.

**Comment by SheepDomination** [comment]
@sandy081 
> We would need the set up, can you please create a sample repo in GitHub that can be used to repro.
I was wondering if the repository I created was what you wanted; if not, what is it you wanted ?

**Comment by sandy081** [comment]
I do not want to side track this issue with other issue. Sorry for doing so. I will move above recording to other issue and continue there.

It would be also great if you can provide a repo/gif to repro this issue.

**Comment by SheepDomination** [comment]
In the short clip, when I try to make a `tasks.json` file, nothing is created ?
![configure_tasks](https://user-images.githubusercontent.com/6827459/68910020-4e29d880-071e-11ea-907d-b18c85228886.gif)

**Comment by alexr00** [comment]
@sandy081 they do appear to be the same issue.

**Comment by sandy081** [comment]
Seems user cannot able to open/create configuration files under `.vscode` folder. 

@SheepDomination Do you see any errors in console or in logs `F1 > Open View > Log (Window)` while opening this?

**Comment by SheepDomination** [comment]
@sandy081 
This is the error when attempting to `create ttasks.json file from template`.
```
[2019-11-15 07:51:02.007] [renderer1] [error] Cannot read property 'toResource' of undefined: TypeError: Cannot read property 'toResource' of undefined
    at handleSelection (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4542:98)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4543:776
```

**Comment by SheepDomination** [comment]
Apparently some of my settings files became corrupt resulting in my *tasks.json* file among a few other files to become corrupt as well; although it is working again.
