### ISSUE TITLE
Git - extension host crashes when merging

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/vscode#83945]
Issue Type: <b>Bug</b>

I am trying to complete a git merge with a few hundred conflicts. If I pick a range of files , right click and choose "Accept all incoming" , about 50% of the time the extension host crashes.
The git repo is in Azure Devops.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
tslint|eg2|1.0.44
mssql|ms-|1.7.0
csharp|ms-|1.21.5
notepadplusplus-keybindings|ms-|1.0.3
powershell|ms-|2019.11.0
debugger-for-chrome|msj|4.12.1

</details>

**Comment by shueybubbles** [comment]
restarting code seems to have "fixed" it.

**Comment by joaomoreno** [comment]
Can you reproduce this still?
