### ISSUE TITLE
WorkSpace settings file doesn't open ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode#83946]
As of version 1.39.2, I'm unable to open my workspace.json file ? 
I first open the command palette then I go to *workspace settings*, followed by `Edit in settings.json` but the *workspace.json* file doesn't open ?

**Comment by alexandrudima** [comment]
Possibly related -- #83947

**Comment by SheepDomination** [comment]
That is related to `tasks.json` not `workspace setting` ?

**Comment by SheepDomination** [comment]
This error is different.
```
  ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e.textFileService.read.then.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4582:264)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sandy081** [comment]
![workspaceSettingsError](https://user-images.githubusercontent.com/6827459/68867681-3faed300-06c4-11ea-8cee-322a6ed599df.gif)

**Comment by SheepDomination** [comment]
@roblourens 
This is the error seen when attempting to open my `workspace.json` file using the procedure shown in the clip above;
```
[2019-11-15 07:53:06.878] [renderer1] [error] Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4657:264
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/blob/d2411100df7cbd76b3acdcd54d3925a146f50af5/src/vs/workbench/services/preferences/browser/preferencesService.ts#L559

@SheepDomination is your workspace configuration file invalid? Can you run "Open workspace configuration file" and share it?

**Comment by SheepDomination** [comment]
> This is
> 
> https://github.com/microsoft/vscode/blob/d2411100df7cbd76b3acdcd54d3925a146f50af5/src/vs/workbench/services/preferences/browser/preferencesService.ts#L559
> 
> @SheepDomination is your workspace configuration file invalid? Can you run "Open workspace configuration file" and share it?

@roblourens It is empty ?

**Comment by SheepDomination** [comment]
I cannot open the workspace settings, from `Open Workspace Settings` but `Open Workspace configuration file` works; although it is empty ?
Is there a difference, should I have put my settings in the `Workspace configuration file` instead of the `workspace settings` file ?

**Comment by roblourens** [comment]
I am not sure how you got into this state. The code-workspace file (from "Open Workspace configuration file") should have a list of folders open in the workspace, and also can have workspace-specific settings. Do you remember creating one of these? Is there an open folder in the window? How did you open this window?

I assume if you open a new window, you won't see this?

**Comment by SheepDomination** [comment]
@roblourens I can tell you something changed, for the longest time I was able to open the command palette followed by; `Open workspace settings` then clicking on `edit in settings.json` and my workspace settings file would open up, with all my settings; since opening this issue that no longer works ? 

I do not remember creating a *Workspace configuration file*. What do you mean is there an open folder in the window ? As for the rest of your questions, it appears the answer is no.

**Comment by roblourens** [comment]
I don't know what happened to your settings, it sounds like they were previously in a workspace config file which is now empty. I am trying to understand how you are using vscode now with an empty workspace config file. Do you have a folder open, and how do you open that folder? Can you share screenshots?

**Comment by SheepDomination** [comment]
@roblourens I just want to get this resolved as soon as possible. 
There are no folders open, as I mentioned before this occurred I had folders open, but whatever caused this, or how it happened is unknown but now there are no folders open.

Is there any way to recover the the `workspace settings` file ? 

What I find odd is that when opening strictly the *workspace settings* from the command palette there is a series of options which is more user friendly but I prefer to work with the *JSON* file therefore I click `Edit in settings.json` but nothing happens, the `settings.json` file doesn't open. I'm using version 1.40.1 of VSCode, I was hoping the point one release would resolve this, unfortunately it hasn't.  I've been left in this limbo for weeks. If I could recover my *workspace settings* and understand why clicking on `Edit in settings.json` doesn't work it would be helpful ?

**Comment by roblourens** [comment]
> and understand why clicking on Edit in settings.json doesn't work it would be helpful ?

Well, I think it just won't work for the same reason, that the workspace configuration file has gone empty. That label is not totally precise, in this case it's opening the workspace config file, not a settings.json.

Unfortunately I don't know what would have happened to your workspace config file. Is it saved somewhere where it might have been wiped by mistake? Do you remember what you were doing the problem first happened? Unless it is saved or backed up somewhere else, you will probably just have to recreate the workspace. For example, open a new window, add folders to it, etc.

**Comment by SheepDomination** [comment]
@roblourens I honestly do not remember what caused the *workspace settings* file to become corrupt. I'm going to search, whether I find the workspace configuration file or not, remains to be known,  

Although as you said, I'm going to have to, unfortunately re-create my workspace settings file from scratch.   The only other thing that just came to mind is *maybe* an extension, somehow caused it to be come corrupt, it's unfortunate that I'll have to do it all from scratch, again.
