### ISSUE TITLE
command 'emmet.expandAbbreviation' not found

### ISSUE THREAD

**Issue by dwyn** [microsoft/vscode#83944]
I have seen this bug posted in other threads, but those threads have been closed. Furthermore, the fixes mentioned in those threads are not working for me.

I am not using insiders build.

- VSCode Version: 1.39.2
OS Version: macOS Catalina 10.15.1

Steps to Reproduce:
1. Press Tab ↹
2. error comes back with command `'emmet.expandAbbreviation' not found`

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
If you run the command `Developer: Show running extensions`, does it include emmet?

Mine:

![image](https://user-images.githubusercontent.com/4033249/68322304-0d73f480-0078-11ea-8176-fcfd1efb5c9d.png)
