### ISSUE TITLE
Build/Environment Variables

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/vscode#83943]
When building for a web browser, it can be hard to build for different environments (prod, dev, staging, etc.), because sometimes you need to uses different variables based on where the script(s) are running. For example when using a production environment, you may need a url to go to a production url such as http://example.com but when in development you may need it to go to http://dev.example.com. Modifying the hosts file is not necessarily ideal. This solution might also work with nodejs where the dotenv module would possibly no longer be necessary.

I would like to suggest for the ability of adding a builds variables file, where you can define your variables then build to that environment, it would be possible that it would look something like this:

**/.env.json**
```
{
  "prod": {
    "endpoint": "ws://example.com"
  },
  "stage": {
    "endpoint": "ws://stage.example.com"
  },
  "dev": {
    "endpoint": "ws://127.0.0.1",
    "port": 1234
  }
}
```

Then when you are ready to build you would run one of the following:

```
tsc -p . --env=prod
tsc -p . --env=dev
```

Lets say your TypeScript file looks like this:

```
let master = new WebSocket(env.endpoint);
```

When built, the variables from the build file would be injected into the final build. Let's assume we ran `tsc -p . --env=prod`, the variable `port` exists in `dev` but not `prod`, it probably should still be added to the output variables no matter what environment you select.

```
window.env = {
  endpoint: "ws://example.com",
  port: undefined
};
let master = new WebSocket(window.env.endpoint);
```
Or maybe you want to build for `dev` with `tsc -p . --env=dev` the output would then look something like this:
```
window.env = {
  endpoint: "ws://127.0.0.1",
  port: undefined
};
let master = new WebSocket(window.env.endpoint);
```

**Comment by alexr00** [comment]
@TheColorRed are you using VS Code to build today? If so, how to do you use it?

**Comment by TheColorRed** [comment]
@alexr00 Ohh wow, I posted this in the wrong repository. Sorry.
