### ISSUE TITLE
Intellisense autocomplete not working with Powershell (module version 0.6.1)

### ISSUE THREAD

**Issue by lc9er** [Microsoft/vscode#8394]
- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Edit a ps1 file, verify language set as 'Powershell'.
2. Attempt to autocomplete a cmdlet like 'get-host', by typing 'get-'. No suggestions pop up.
3. Attempt to manually get suggestions by typing Ctrl-Space. VS Code replies "No suggestions"

**Comment by bpasero** [comment]
@lc9er please report this to the powershell extension.
