### ISSUE TITLE
"Open with Code" context menu is not localized

### ISSUE THREAD

**Issue by smares** [microsoft/vscode#83940]
The context menu "Open with Code" is not localized on my German Windows 10 Pro x64 system. A screenshot is attached showing the Desktop context menu, but the entry is in English for files and regular directories as well.

![image](https://user-images.githubusercontent.com/818380/68150600-5cb70980-ff40-11e9-8d0b-a436591f4c4e.png)

Related to #11804.

Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Datum: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
I installed Insiders fresh with that option enabled, and it still says "Open with Code Insiders", are we waiting for a localized string to come in?

**Comment by roblourens** [comment]
I went back to take a screenshot and now it's working, I guess it needed a minute after install

**Comment by smares** [comment]
Are existing installations going to be fixed as well or does the fix apply only to new installs?
