### ISSUE TITLE
Autocomplete should be case insensitive for suggesting strings

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#8395]
- VSCode Version: 1.21

Steps to Reproduce:

1. Type some code starting with capital letter
2. Type the same words again with small letter

Expected output: auto complete should have suggested me the word starting with capital letter, 
Actual output: It doesn't.

**Comment by thewhitetulip** [comment]
Something had gone wrong, it is fine the way it is.

**Comment by thewhitetulip** [comment]
Found out the issue. While writing strings intellisense isn't case insensitive

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/16561709/ead67130-41fa-11e6-9f90-42a1e4305362.png)

**Comment by thewhitetulip** [comment]
@joaomoreno 
Put a single quote around what_do_you_mean!

'what_do_you_mean'
then type WH and it won't suggest you the above statement.

**Comment by joaomoreno** [comment]
Wow!

**Comment by joaomoreno** [comment]
@jrieken Is this filter label vs sort label vs visible label?

**Comment by jrieken** [comment]
I don't think so but there is also too little information to know. As always it all depends on the language that is used.

**Comment by joaomoreno** [comment]
I get it on plain text:

![image](https://cloud.githubusercontent.com/assets/22350/16566244/1a42e288-4213-11e6-99e9-04a41f527f61.png)

**Comment by jrieken** [comment]
Ever since textual completions use the [`strict prefix matcher`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/suggestSupport.ts#L44) to not be too spamy. Maybe it's time to revisit that.

**Comment by joaomoreno** [comment]
Do you happen to know who the person to talk to is?

**Comment by jrieken** [comment]
Maybe 🙈

**Comment by joaomoreno** [comment]
Just I just drop the strict?

**Comment by jrieken** [comment]
Yeah - and since that's the last usage of another than default filter I would drop the whole concept of support specific filters
