### ISSUE TITLE
Clicking on call stack step creates tab with enormous name

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83954]
1. Add breakpoint to terminal.test.ts API tests
2. Start debugging API tests
3. When breakpoint is hit, click on callstack entry in extHostTerminalService.ts

![image](https://user-images.githubusercontent.com/2193314/68170636-78f97d00-ff25-11e9-9194-e730db00cd94.png)

Version: 1.40.0-insider (user setup)
Commit: a14de79ac74f2e0e6566d3cc9410eeb7dc769cde
Date: 2019-11-02T00:39:42.595Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19013

**Comment by Tyriar** [comment]
Also I'm confused what this file actually is, it seems to be out of date:

![image](https://user-images.githubusercontent.com/2193314/68170839-29678100-ff26-11e9-9223-da6b0bc10476.png)

Actual ts file:

![image](https://user-images.githubusercontent.com/2193314/68170856-35ebd980-ff26-11e9-9df9-8ade5a198be9.png)

Actual js file correctly has `setExitCode` too.

**Comment by Tyriar** [comment]
Might be this?

https://github.com/microsoft/vscode/blob/7ab195a8973c74871c22b2add0f810b716028940/.vscode/launch.json#L78

Just did a clean and trying again and heading home. Will check again tomorrow.

**Comment by isidorn** [comment]
@Tyriar sorry for the slow response, I was on vacation.
I tried reproducing this and when I run "VS Code API Tests (single folder)" I do not hit the terminal test breakpoints but I get the `The Terminal Process Failed to Launch` in the other window. How can I get around this?
Also do you still see this issue?
Btw this file is probably coming from the node2 adapter, thus @roblourens fyi

**Comment by Tyriar** [comment]
@isidorn debugging out of sources seemed a little broken, it might be related to why I was seeing this.

**Comment by Tyriar** [comment]
Actually, I think I found that it wasn't debugging out of sources but it was launching a new _Insiders_ window which is why that path is long, it was running the api tests in the insiders ext host which is what the start of that path is pointing at.
