### ISSUE TITLE
Shortcut key for opening folders does not work when executed immediately upon launch

### ISSUE THREAD

**Issue by eddylu94** [microsoft/vscode#83953]
- VSCode Version: 1.38.1
- OS Version: Linux x64, Windows 10

Steps to Reproduce:

1. Launch Visual Studio Code
2. After VSCode completely loads, launch a new VSCode window using the shortcut key (Ctrl + Shift + N)
3. Immediately (within one second) after the new VSCode window is rendered, attempt to open a folder using the shortcut key (Ctrl + K, Ctrl + O)
4. A new dialog will appear, but the dialog will only provide the user the option to open **files**, not **folders**
5. However, if the user waits for at least a few seconds after the VSCode window has rendered before attempting to open the folder using the shortcut key, then the presented dialog will provide the user with the expected option to open **folders**

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@eddylu94 I cannot reproduce anymore:

![Kapture 2020-12-09 at 09 58 12](https://user-images.githubusercontent.com/5047891/101607616-149ccd00-3a05-11eb-9490-3dd1ffa46a5a.gif)

Please let me know if you can still reproduce.

**Comment by eddylu94** [comment]
Hi @alexdima, thanks for following up with this issue. Since this ticket was created, I have actually changed platforms and no longer utilize an environment in which I can test/reproduce this issue. Therefore, if no other tickets have been filed for this issue, and since there have been no upvotes for this ticket, then I believe it is reasonable to close this ticket.
