### ISSUE TITLE
On Markdown editor, Shift+Enter (Previous match) does not work for find text

### ISSUE THREAD

**Issue by kntmr** [microsoft/vscode#83960]
On Markdown editor, `Shift+Enter` (Previous match) does not work for find text.
On other files (ex. .txt, .js, ...), it does work well.

VSCode Version: 1.39.2
OS Version: Windows 10

**Comment by mjbvz** [comment]
I can't repo this. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by kntmr** [comment]
I am very sorry. It was caused by extension "Markdown Preview Enhanced".
