### ISSUE TITLE
Sidebar jumps when renaming an image file.

### ISSUE THREAD

**Issue by routbisu** [microsoft/vscode#83961]
Issue Type: <b>Bug</b>

Details are present in this video - 
https://youtu.be/U6MQ2OKlG5A

Open a folder with several files.
Click on an image file and rename it.
The side bars scrolls automatically (jumps) to the bottom.

Details are present in this video - 
https://youtu.be/U6MQ2OKlG5A

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.4.3
prettier-vscode|esb|2.3.0
dotenv|mik|1.0.1

</details>

**Comment by bpasero** [comment]
I think the unexpected part is that the binary editor closes, but then the behavior is as designed, we simply reveal the next file that opens in the explorer.

**Comment by routbisu** [comment]
Can you change the behavior so that it opens the renamed file in the binary editor rather than closing it?
When I rename text files, the editor does not close rather the renamed file is opened. Why is the behavior different for binary files?

**Comment by mjbvz** [comment]
Fixed by 5ec2e40b21a4cd5ce6a5ed4eb3f509dc280a0d53

Note that renames in the explorer always seem to center the renamed file. This happens for regular files too
