### ISSUE TITLE
maximized vscode window content 1px leak through monitor edge

### ISSUE THREAD

**Issue by noe132** [microsoft/vscode#83968]
- VSCode Version: 1.39.2
- OS Version: windows 10

Steps to Reproduce:

1. open vscode with dual monitor
2. maximize vscode

left edge
![](https://user-images.githubusercontent.com/2271900/68193423-fc7ea100-ffed-11e9-8f41-0ae80a3de1ef.jpg)

right edge
![](https://user-images.githubusercontent.com/2271900/68193415-fb4d7400-ffed-11e9-884b-e9e487745fef.jpg)

Does this issue occur when all extensions are disabled?: No

Running in fullscreen is fine.
I'm using 4k resolution on all monitors with 200% system scaling

**Comment by IllusionMH** [comment]
Could you check in Insiders build? https://code.visualstudio.com/insiders/

Should be fixed there (may be related to Electron update)

**Comment by noe132** [comment]
Great! Insider build doesn't have this issue. Closing this now.
