### ISSUE TITLE
CTRL-C without line selection unexpectedly copies the whole line of text

### ISSUE THREAD

**Issue by khteh** [microsoft/vscode#83963]
I am not sure if this is the expected behaviour but it annoyingly copies the whole line of text when I only want to copy a selection. This is not the case compared to other editor, Notepad++, for instance. This is especially disturbing the the WORD at the mouse cursor appears in block-highlighted color (also unexpectedly) and I thought I have selected that word to copy, press CTRL-C, and the whole line, instead of the desired WORD is pasted onto another code editor tab!

- VSCode Version: 1.39.2
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by usernamehw** [comment]
```js
"editor.emptySelectionClipboard": false,
```

**Comment by khteh** [comment]
That works. Thanks. Why need this extra config? Why is this not the default behaviour?

**Comment by khteh** [comment]
Hi, no, that doesn't work well. Now I cannot delete the WHOLE line of code at the cursor position with CTRL-X!

**Comment by alexandrudima** [comment]
@khteh That is how the feature works. `editor.emptySelectionClipboard` drives if the editor should handle `Ctrl+C` and `Ctrl+X` when not having a selection. It is true by default so pressing `Ctrl+C` and `Ctrl+X` will copy/delete the entire line when there is no selection. When changing the setting to false, `Ctrl+C` and `Ctrl+X` will not do anything.

If you want to target solely `Ctrl+C` and have it not do anything you can try the following:
- configure back `"editor.emptySelectionClipboard": true`
- add the following keybinding:
```
{ "key": "ctrl+c", "when": "textInputFocus && !editorHasSelection" }
```
