### ISSUE TITLE
Не отображается нижний дефис в терминале

### ISSUE THREAD

**Issue by yuri-velmesov** [microsoft/vscode#83977]
Issue Type: <b>Bug</b>

В терминале если писать слова через нижнее подчеркивание, например при указании флагов или допустим вывод какой то программы, то в таких словах не отображается нижнее подчеркивание и получается в терминале как будто два слова и это мешает работе и отладке.

Как проверить, открыть терминал -> ввести к примеру:
seo_name
product_code

Операционная система  Ubuntu.
Данная проблема наблюдается мной в версиях Ubuntu от 18.04 и выше.

В родном стандартном терминале Ubuntu все отображается нормально.

Проблема точно не в плагинах, потому, что данная проблема наблюдается и при чистой установке редактора.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.0-19-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.31GB (8.37GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
systemd-unit-file|coo|1.0.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
php-cs-fixer|jun|0.1.127
vscode-gist|ken|3.0.3
sftp|lix|1.12.9
twig-language-2|mbl|0.8.10
vscode-apache|mrm|1.2.0
language-gettext|mro|0.1.1
vscode-language-pack-ru|MS-|1.39.3
python|ms-|2019.10.44104
Go|ms-|0.11.8
php-docblocker|nei|2.0.1
vscode-scss-formatter|sib|1.4.2
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by krupenja** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/35901
