### ISSUE TITLE
Variable substitution doesn't seem to work when running in extension dev host

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8397]
Testing #8196 on Linux
- clone https://github.com/Microsoft/vscode-node-debug.git
- npm install
- gulp compile
- run the extension with F5
- In the extension dev host try to attach to a node process

Error: Attach to process: '${command.PickProcess}' doesn't look like a process id.

It looks like variables are not detected and replaced

**Comment by weinand** [comment]
@aeschli I'm not able to reproduce this problem on elementary:
![2016-06-29_12-42-09](https://cloud.githubusercontent.com/assets/1898161/16449303/e7e7c2e2-3df6-11e6-9a29-dc4d45595a36.png)

Variable substitution works fine for me.
