### ISSUE TITLE
Script reopening (duplicaton) not necessary 

### ISSUE THREAD

**Issue by smjure** [microsoft/vscode#83971]
Issue Type: <b>Feature Request</b>

For example, one uses split screen with a main script on left and module library on right of the screen. If you place your coursor on a module in the main (left) script and press shortcut key (F12) to go to that particular module which is in the right script, VSCode opens new tab on the left side where the main script is, instead of using already opened module script on the right. Reopening of the script with module is not necessary, plus it covers your main script. Would recommend to fix that issue.   

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/68213327-a3a60d00-ffdb-11e9-8d97-9b1c90899964.png)
