### ISSUE TITLE
Setting PowerShell 7 as the default shell causes intermittent crash

### ISSUE THREAD

**Issue by saschanaz** [microsoft/vscode#83980]
- VSCode Version: 1.39.2 user setup
- OS Version: Microsoft Windows 10.0.19013

Steps to Reproduce:

1. [Install PowerShell 7 Preview 5](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.0-preview.5) with the new MSIX installer.
2. Set the default Windows shell as PowerShell 7. (Set `"terminal.integrated.shell.windows": "C:/Program Files/WindowsApps/Microsoft.PowerShell_7.0.5.0_neutral__8wekyb3d8bbwe/pwsh.exe"` in `settings.json`)
3. Tap `` Control+` `` to open shell
4. See intermittent crash

Does this issue occur when all extensions are disabled?: Yes

Cross-posted with https://github.com/PowerShell/PowerShell/issues/10988

**Comment by Tyriar** [comment]
Does powershell crash of vscode? Does PS say it exited? Does it happen immediately after opening the terminal or closing?

**Comment by saschanaz** [comment]
This is what immediately happens when I press Control+`:

![image](https://user-images.githubusercontent.com/3396686/68219355-328d4680-0029-11ea-909f-cdc87aeebce0.png)

I can see nothing except this message.

**Comment by Tyriar** [comment]
Looks like an issue I haven't had reports for before.

**Comment by the-ress** [comment]
The issue might be related to [10.0.19013 being an insider build](https://blogs.windows.com/windowsexperience/2019/10/29/announcing-windows-10-insider-preview-build-19013/).

I'm not able to reproduce this on Windows 10.0.18363.

```
Version: 1.41.0-insider (user setup)
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1
```

**Comment by saschanaz** [comment]
>The issue might be related to 10.0.19013 being an insider build.

I guess so. Couldn't reproduce in recent builds, so closing.
