### ISSUE TITLE
Web: severity icon not aligned in error peek

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83987]
![image](https://user-images.githubusercontent.com/900690/68216327-04841400-ffe1-11e9-9612-0a95c9f86863.png)

(I added support to have problems from `yarn web`)

**Comment by misolori** [comment]
This also appears on OSS. This is now fixed:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/35271042/68248391-95eb8a00-ffd1-11e9-8892-1a01a81e93f0.png">
