### ISSUE TITLE
Tab does not always gets revealed when activating it via keyboard

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8398]
**Findings**: the tabs widget currently does not detect when the underlying div scrolls. Need to listen for scrolling (e.g. caused by going through elements with tab and focussing them) and update the custom scrollbar accordingly.

Testing #7854 

* a lot of ctrl+m to get all editors move focus
* shift-tab to reach the tab
* space to select the tab
* doing it with the mouse seems to always reveal it

![vqzovjcrlg](https://cloud.githubusercontent.com/assets/5047891/16424528/d3f55e52-3d60-11e6-8dc2-03698465c770.gif)

**Comment by bpasero** [comment]
Weird, works for me on Mac at least.

**Comment by bpasero** [comment]
For me it even reveals the tab while I am tabbing through. 

![jun-29-2016 08-38-01](https://cloud.githubusercontent.com/assets/900690/16442742/e4d0006e-3dd4-11e6-9f7b-530ca338cb55.gif)

**Comment by alexandrudima** [comment]
Sometimes it works, but maybe after clicking on them or selecting a few it stops working. I will try to see if I find what brings it in this state...

**Comment by bpasero** [comment]
Thanks!
