### ISSUE TITLE
[folding] highlight folded line

### ISSUE THREAD

**Issue by mymage** [microsoft/vscode#83983]
It would be useful if the collapsed lines were highlighted.

Actual code expanded:
![0000000](https://user-images.githubusercontent.com/26981549/68210528-02688800-ffd6-11e9-935b-80e661a758fc.png)

Actual code collapsed:
![11111](https://user-images.githubusercontent.com/26981549/68210577-1dd39300-ffd6-11e9-8ff9-8cbcfe67241e.png)

Proposal for an highlight of collapsed code:
![22222](https://user-images.githubusercontent.com/26981549/68210609-2b891880-ffd6-11e9-8b7d-fa5140948642.png)
Perfect if with color highlight configurable on settings.

Thanks

**Comment by dbeigi** [comment]
Hi @aeschli, I would like to give this a shot.

**Comment by aeschli** [comment]
@dbeigi Great. Have a look at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/folding/foldingModel.ts#L91
There we create a decoration that is used not only for the +/- action but alsofor the `...`
Righ now it starts at the last character.
A simple fix might be to have it start at character 0, and give it a background color

**Comment by dbeigi** [comment]
@aeschli appreciate the direction

**Comment by dbeigi** [comment]
@aeschli do you have any suggestions on adding the background color?

**Comment by aeschli** [comment]
@mymage https://github.com/microsoft/vscode/blob/53210edd7991627f4af6725ccc2be2a1ad68f2cf/src/vs/editor/contrib/folding/foldingDecorations.ts#L13 defines a decoration that you can use to also add a background color:
```
	private static readonly COLLAPSED_VISUAL_DECORATION = ModelDecorationOptions.register({
		stickiness: TrackedRangeStickiness.GrowsOnlyWhenTypingBefore,
		afterContentClassName: 'inline-folded',
		className: 'folded-background',
		isWholeLine: true,
		linesDecorationsClassName: 'codicon codicon-chevron-right'
	});
```
And in folding.css
````
.monaco-editor .folded-background {
	background-color: yellow;
}
```

Now the remaining work is to make the color configurable.
https://github.com/microsoft/vscode/blob/4e8ef4cf4deaefa8d9f4383e937cb10ea6958a92/src/vs/editor/contrib/find/findOptionsWidget.ts#L197
is an example on a css that is generated based on theme colors.

**Comment by mymage** [comment]
@aeschli , sorry I'm not very confident with these language: you intend that I can apply these code on my local files to try the feature?

**Comment by aeschli** [comment]
@mymage Sorry, no, this was just intended to help @dbeigi which offered to work on a PR implementing the feature.

**Comment by ianwesterfield** [comment]
Am I missing where this can be disabled in settings?

**Comment by usernamehw** [comment]
You can use transparent color:
```js
"workbench.colorCustomizations": {
	"editor.foldBackground": "#fff0",
}
```
The reason is probably because there's a lot of settings already.

**Comment by aeschli** [comment]
I added a setting `editor.foldingHighlight`

**Comment by aeschli** [comment]
To verify:
- configure folded region highlight color:
```
"workbench.colorCustomizations": {
	"editor.foldBackground": "#fff0",
}
```
- enable/disable feature:
`"editor.foldingHighlight": false`
