### ISSUE TITLE
VSCode hangs in Ubuntu 19 in VirtualBox

### ISSUE THREAD

**Issue by jim-king-2000** [microsoft/vscode#83996]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install Ubuntu 19 x64 in VirtualBox 6.0.14, host is win10.
2. Install vscode.
3. Open any folder which contains source code files.
4. Notice it will hang soon. And the main menu turns white.
<img width="548" alt="Untitled" src="https://user-images.githubusercontent.com/7019050/68221662-bd1f7700-0024-11ea-98fe-eafd49323757.png">

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jim-king-2000** [comment]
Sure, I'll do it and keep you posted.

**Comment by bpasero** [comment]
Thanks

**Comment by jim-king-2000** [comment]
Fantastic! It works perfectly. I'll keep trying it.

**Comment by jim-king-2000** [comment]
It hangs when it starts the second time. After being reinstalled, it works the first time, and still hangs the second time.

**Comment by jim-king-2000** [comment]
After trying several times, I find that the culprit is the 'c/c++' extension which will be recommend automatically. It works if the extension is not installed.

**Comment by jim-king-2000** [comment]
It still hangs. This time, no extension.

**Comment by bpasero** [comment]
Does it reproduce with another Electron application such as https://electronjs.org/fiddle ?

**Comment by jim-king-2000** [comment]
I'll try it. By the way, sublime-text 3 works well in my env.

**Comment by bpasero** [comment]
Please do, Sublime Text is not using that framework we do.

**Comment by jim-king-2000** [comment]
Electron-fiddler is too large to download. But I build "electron-quick-start" with electron@6.0.0. It works well.

**Comment by jim-king-2000** [comment]
I start the "electron-quick-start" again, the bug occurs.
<img width="503" alt="Untitled" src="https://user-images.githubusercontent.com/7019050/68363767-e811e400-0166-11ea-987f-399a6c09ee01.png">
So, should I report the bug to electron?

**Comment by bpasero** [comment]
@jim-king-2000 yes that would be great. You can report the issue back here maybe then we can link them together?
