### ISSUE TITLE
OSX WindowServer high cpu load showing ProgressBar

### ISSUE THREAD

**Issue by stffabi** [microsoft/vscode#83991]
I've seen a really high CPU load of the WindowServer process on OSX during the use of the dart-code extension. I could track it down the displayed progress bar, whenever I've hidden it, the cpu usage of the process immediately dropped down to 4-5% from before over 70%.

I could see a similar behaviour with the following test extensions. As long as no progress is reported and the Blue ProgressBar runs through indefinitely, the CPU load of the WindowServer is about 22-25%. As soon as the first progress value is reported, the CPU load immediately drops to 2-4%.

```ts
import { ExtensionContext, StatusBarAlignment, window, StatusBarItem, Selection, workspace, TextEditor, commands, ProgressLocation } from 'vscode';

export function activate(context: ExtensionContext) {
	context.subscriptions.push(commands.registerCommand('extension.startTask', () => {
		window.withProgress({
			location: ProgressLocation.Notification,
			title: "I am long running!",
		}, (progress) => {
			// 22-25% CPU of WindowServer
			setTimeout(() => {
				progress.report({ increment: 50, message: "I am long running! - almost there..." });
				// After this report cpu of WindowServer drops to 2-3%
			}, 10000);

			var p = new Promise(resolve => {
				setTimeout(() => {
					resolve();
				}, 20000);
			});

			return p;
		});
	}));
}

```

- VSCode Version: 1.39.2
- OS Version: macOS Catalina 10.15.1

Steps to Reproduce:

1. Use the above test-extension and watch CPU load of WindowServer process in the Activity Monitor.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by stffabi** [comment]
@bpasero I'm seeing the same 22-25% CPU load with VS code insiders

```
Version: 1.40.0-insider
Commit: 515f496d9a7617caf07f38298f610920f60834d6
```

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by stffabi** [comment]
Disabling the gpu didn't have any noticeable effect.

**Comment by bpasero** [comment]
Does it reproduce with a normal Windows VM? I wonder if this is an issue with the Windows Server OS.

**Comment by stffabi** [comment]
It's not a MS Windows problem. The problem occurs on `macOS Catalina 10.15.1` and the `WindowServer` process has a high CPU usage.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jedwards1211** [comment]
I just started building an extension that uses `withProgress` and it's taking the progress bar several seconds to move, even when I'm reporting progress updates continuously.  I'm pretty sure something is wrong with it
