### ISSUE TITLE
UX meeting agenda 29th June 2016

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#8399]
- Search and replace #8302
- Discussion on tab colours https://github.com/Microsoft/vscode/pull/8238

@Microsoft/vscode - if anyone else wants to join, please let me know

**Comment by isidorn** [comment]
Separator in activity bar? #8149

**Comment by bgashler1** [comment]
Using <kbd>Alt</kbd> key to modify commands #8255

**Comment by gregvanl** [comment]
Different icons for Extension View buttons https://github.com/Microsoft/vscode/issues/8461.
