### ISSUE TITLE
Folding shows odd chars in place of ellipsis 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83990]
Doing smoke test on web:

![image](https://user-images.githubusercontent.com/2193314/68219361-b6e4b880-ff9a-11e9-939b-b6c6e52bcf2e.png)

![image](https://user-images.githubusercontent.com/2193314/68219373-bd733000-ff9a-11e9-81dd-d0ecfb7b8214.png)

Version: 1.40.0-insider
Commit: d39e6b396c3ea364584126316a0fcf30f9cb378e
Date: 2019-11-05T01:41:42.901Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.16 Safari/537.36 Edg/79.0.309.11

**Comment by alexandrudima** [comment]
@Tyriar @bpasero This looks like an encoding issue. Are the `.js` files served as UTF8?

**Comment by alexandrudima** [comment]
This character is coming from CSS here -- https://github.com/microsoft/vscode/blob/308ff31f9585211a12e95afbab6829c088b2bc72/src/vs/editor/contrib/folding/folding.css#L27

**Comment by alexandrudima** [comment]
This works fine in VSO + Edge Dev: 
![image](https://user-images.githubusercontent.com/5047891/68223896-f25ca280-ffed-11e9-8e18-8530d3836b8e.png)

**Comment by alexandrudima** [comment]
This also works for me running from source on Windows + Firefox

**Comment by bpasero** [comment]
> This looks like an encoding issue. Are the .js files served as UTF8?

Yes, from the server and also indicated in the HTML page:

![image](https://user-images.githubusercontent.com/900690/68226988-44ec8d80-fff3-11e9-838c-a9eba7a07732.png)

**Comment by Tyriar** [comment]
I can't reproduce this anymore using the same server, browser and workspace 🤷‍♂

**Comment by bpasero** [comment]
Ok let's close it then.
