### ISSUE TITLE
Web: Support to open VS Code on a file for extension development

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#83997]
Currently it is not possible to open VS Code on a file (instead of a workspace folder), e.g.:

```js
{
	"name": "Run Extension",
	"type": "extensionHost",
	"request": "launch",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}",
		"/Users/weinand/file.txt"
	],
	"outFiles": [
		"${workspaceFolder}/out/**/*.js"
	],
	"preLaunchTask": "npm: watch"
},
```

The "TODO" shows the location where some API is missing: https://github.com/microsoft/vscode/blob/ab89935fd348d023fe34dc8070d105080e1a9652/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts#L71-L86

**Comment by bpasero** [comment]
Yes, we need to wire this into the payload.

**Comment by bpasero** [comment]
**Verification:** make sure that debugging an extension where you pass a file name to open in the config, opens that file name.

**Comment by weinand** [comment]
Great, thanks!

I've verified all three cases:
-  file 
-  folder
-  workspace file

All work fine.
