### ISSUE TITLE
Portable tmp should set %tmp% also

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#83998]
It’s great that having a data/tmp dir redirects the %TEMP% env var, but it would be great if it also redirects %TMP% also as building unix-like stuff on windows can often rely on %tmp%. 

By setting both you cover all cases and have happier users as more stuff works first time.

**Comment by joaomoreno** [comment]
This sounds like a feature for terminal, tasks & debug, or wherever we spawn processes from.

**Comment by Tyriar** [comment]
@joaomoreno doesn't it make more sense to set this on the main process' environment instead of special casing something for portable in several different features?

**Comment by joaomoreno** [comment]
:thinking: My bad... this is actually implemented: https://github.com/microsoft/vscode/blob/109c51997b73730eab72c0a8d2ddbdc95b7c11f6/src/bootstrap.js#L266

![image](https://user-images.githubusercontent.com/22350/68371413-f6e4a080-013e-11ea-8855-4cc0ec4cbb1b.png)

@gilescope In Windows, the `TEMP` directory should be redirected, don't you see that behavior?

**Comment by gilescope** [comment]
I do see `TEMP` dir is redirected. `cargo install cargo-watch` is what's running foul and digging into the issue it seems that rust checks 'TMP' env before checking 'TEMP'. It does this in accordence with: https://docs.microsoft.com/en-gb/windows/win32/api/fileapi/nf-fileapi-gettemppatha

My suggestion for peace and harmony is to remove the OS check and redirect both TMP and TEMP on all OSes.

**Comment by gilescope** [comment]
Thank you  - much appreciated!
