### ISSUE TITLE
Core dump: Windows 10 machine running Xming as an X server

### ISSUE THREAD

**Issue by jakeoshins** [Microsoft/vscode#840]
When I try to start code in Ubuntu 14.04, using my local Windows 10 machine running Xming as an X server, code crashes before I even see a window.

~$ code &
[2] 7847
~$ bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
/bin/VSCode-linux-x64/Code: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
cd vscode/
[2]+  Aborted                 (core dumped) code  (wd: ~)
(wd now: ~/vscode)
~/vscode$ code . &
[2] 7949
~/vscode$ bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
/bin/VSCode-linux-x64/Code .: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
ls
[2]+  Aborted                 (core dumped) code .

**Comment by bpasero** [comment]
I honestly don't know if we support this setup.

**Comment by gmalenko** [comment]
Any updates regarding this?  Got this error too today trying the same setup (using ubuntu 16.04).  I happened to stumble across this in a google search for a solution.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by gmalenko** [comment]
Hey bpasero, I downloaded the tar.gz inside file (code-insider-1.6.0-1475776934_amd64.tar.gz).  I extracted it and ran "./code-insiders"

I got 

gmalenko@ubuntu:~/VSCode-linux-x64$ ./code-insiders
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ome/gmalenko/VSCode-linux-x64/code-insiders: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

**Comment by uael** [comment]
Same here, currently nothing happens :
```bash
$ ./code &
[1] 16395
```
ubuntu 16.04 gest (vagrant) / windows 10 host

**Comment by cashlalala** [comment]
I encountered the same issue. Simply extracted the code-stable-code_1.6.1-1476373175_amd64.tar.gz & call ./code, then got the same error.

[cash@ubuntu1404 VSCode-linux-x64]$./code
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
roj/cash/VSCode-linux-x64/code: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

**Comment by b1es** [comment]
The same issue.  I downloaded the tar.gz and than:
```
$ ./code

[516:1107/131853:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument
#0 0x000001e0962e <unknown>
#1 0x000001e1f23b <unknown>
#2 0x000001e1f7fd <unknown>
#3 0x000002892e52 <unknown>
#4 0x00000265e2f9 <unknown>
#5 0x0000026648bf <unknown>
#6 0x00000265d996 <unknown>
#7 0x000001203e97 <unknown>
#8 0x000001202970 <unknown>
#9 0x0000033a9313 main
#10 0x7f704c6e1f45 __libc_start_main
#11 0x000000574d79 <unknown>

Aborted (core dumped)
```

**Comment by PunchyRascal** [comment]
I am trying to make this work too, but the problem is still there. This would be an ideal setup for me, as I work from Windows on a remote linux server, but using remote drive in windows or syncing from windows is both problematic and slow. Other windowed applications work fine.

**Comment by brice-gros** [comment]
@b1es @PunchyRascal Got the same issue, but it is not related to vscode, I got the same one with atom. I assume than you are not using a windows 10 insider build, but win10 anniversary update as I do. This is due to shutdown not being implemented for sockets. Though it is already fixed for insider builds: https://github.com/Microsoft/BashOnWindows/issues/758

**Comment by PunchyRascal** [comment]
Yes, like you say. But I reverted to using samba-connected linux share on windows, which is rather slow, but otherwise it has pretty much the best native feel anyway.

**Comment by mindis** [comment]
same issue here

**Comment by olikasg** [comment]
I ran into the same problem with Win7 and Xming. Later I tried to VcXsrv and it worked with that.
