### ISSUE TITLE
Horizontal white lines in drop down windows in Ubuntu 18.03.4

### ISSUE THREAD

**Issue by masonedmison** [microsoft/vscode#84003]
- VSCode Version: 1.39.2
- OS Version: Ubuntu 18.04.3

As the title says, I am experiencing horizontal white bars on all of the drop down windows and menus. I am running the 5.3 kernel on Ubuntu 18.04.3. Has anyone else had this issue and if so, is there a fix?

**Comment by alexandrudima** [comment]
@masonedmison It is difficult to know what you mean only from the textual description. Can you please include a screenshot?
