### ISSUE TITLE
Watch Add Expression doesn't focus input nor scroll into view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#84006]
Issue Type: <b>Bug</b>

When choosing _Add Expression_ from the debug _Watch_ view, the input box doesn't seem to be focused, and it won't even scroll the view to see the box.

VS Code version: Code - Insiders 1.40.0-insider (515f496d9a7617caf07f38298f610920f60834d6, 2019-11-05T14:32:05.211Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
For me the input always gets focus.
However it does not scroll into view and that I just fixed.
@eamodio please let me know if with this fix you see that the input box still does not have focus. And if yes can you let me know how to trigger the Add Expression - via mouse?

**Comment by eamodio** [comment]
@isidorn it looks good to me now - thanks!
