### ISSUE TITLE
Crashing/failing to open on new install

### ISSUE THREAD

**Issue by hjdarnel** [Microsoft/vscode#8400]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. [Download zip](https://code.visualstudio.com/Download)
2. Unzip
3. Open application (accepting security prompt)

Expected outcome: VS Code opens as a fresh install
Actual: Program closes itself.

I've restarted my Mac, redownloaded the .zip and unzipped, nothing's solved. I can provide a screen cap if you want it for debug purposes.

**Comment by hjdarnel** [comment]
Workaround by opening via CLI. `code .`

**Comment by bpasero** [comment]
We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by hjdarnel** [comment]
The latest build seems to work properly, at least allowing me to open via double clicking the app. I'll probably still just use Stable since I usually call from the CLI anyway, and that's working fine for me. Thanks guys.
