### ISSUE TITLE
Source Control Sync Doesn't Work With Password on SSH Key

### ISSUE THREAD

**Issue by Chiramisu** [microsoft/vscode#84009]
Issue Type: <b>Bug</b>

When I generate an SSH key with a password, add it to my Git account, then try the "Sync" button on the source control tab, it just spins and spins. However, when I do this by the command line, I am prompted for my password and it works correctly. This button should implement a password prompt when clicked and the key is protected.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.67GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2701)|
|Memory (System)|31.75GB (16.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2701)|
|Memory (System)|31.75GB (16.67GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
jenkins-status|ale|3.1.2
project-manager|ale|10.8.0
gitignore|cod|0.6.0
gdb-debug|Dam|1.0.7
xml|Dot|2.5.0
gitlens|eam|10.1.1
code-runner|for|0.9.14
jenkinsfile-support|ivo|0.4.4
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
vsliveshare|ms-|1.0.1123
autodocstring|njp|0.3.0
bash-debug|rog|0.3.6
code-spell-checker|str|1.7.18
jenkins-jack|tab|1.0.1
vscodeintellicode|Vis|1.2.0
debug|web|0.23.1
markdown-all-in-one|yzh|2.5.1
better-comments|aar|2.0.5
dokuwiki|kir|1.4.0
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.39.9
vscode-remote-extensionpack|ms-|0.17.0
debugger-for-chrome|msj|4.12.1
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4

(5 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
#13680
