### ISSUE TITLE
Watch Add Expression should auto-fill based on selected expression property (if there is one)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#84008]
Issue Type: <b>Feature Request</b>

If you right-click on an entry in the debug _Watch_ view and choose _Add Expression_, it should auto-fill the watch expression with the selected entry's property

For example below, I would like the input box to be auto-filled to `modes_1.LinkProviderRegistry._entries`
![image](https://user-images.githubusercontent.com/641685/68236446-30000200-ffd3-11e9-885b-d3e0336e3b95.png)

VS Code version: Code - Insiders 1.40.0-insider (515f496d9a7617caf07f38298f610920f60834d6, 2019-11-05T14:32:05.211Z)
OS version: Windows_NT x64 10.0.19013

**Comment by isidorn** [comment]
@eamodio this is a good suggestion and a fair feature request.
The `AddWatchExpression` would have to get an optional string paramter in the constructor which it would pass to the addWatchExpression and all should hopefully work.
Code pointer https://github.com/microsoft/vscode/blob/f43d8bc01242d2d309419091140c5cd52e4563ed/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L188
