### ISSUE TITLE
Run command from Command ID

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#84011]
Say I want to invoke a command with a specific **command ID**.  For some commands, like `workbench.action.toggleEditorVisibility` the command palette does **not** return any results (e.g. if I type `toggleEditorVisibility` nothing comes out). 

How can I invoke a command by directly typing its command ID?

Note: I opened this issue as a feature request. This is also tracked in [this question](https://stackoverflow.com/questions/58382100/triggering-commands-by-their-command-id-or-string-alias) in SO.

**Comment by jrieken** [comment]
You cannot. If you are an extension you can use the `vscode.commands.executeCommand`-api, you can assign a keybinding (F1> Open Keyboard Shortcuts), and there is a request for user configurable menus (https://github.com/microsoft/vscode/issues/9285)
