### ISSUE TITLE
Keybindings Editor stuck in "Record Keys" mode if enabled while in debug mode

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#84019]
1. Start a debug session
2. In keybindings editor, enable "Record Keys", and type in the search bar.
3. Disable it. Type in the search bar again. 

Bug: the search bar will continue to be in record keys mode even when the UI says that mode has been disabled. This persists until the application is reloaded.

This is a regression from stable.

**Comment by sandy081** [comment]
/duplicate

#82714
