### ISSUE TITLE
Remote Desktop: Mouse cursor for text selection is black on black

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8401]
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Remote Desktop for OSX to Windows 8.1 (not sure if RD matters).
2. Move the mouse inside the editor area or console text area.
3. The cursor for text selection shows mostly black on black background and is very difficult to see at all.

**Comment by alexandrudima** [comment]
@chrmarti I'm assuming you're using the dark theme. I tried on Windows 10 and the `I` is rendered by Windows in white. Maybe it does have something to do with your setup? Do you see the Windows cursor or the OSX cursor?

**Comment by chrmarti** [comment]
I'm using the default Dark+. The cursor seems to be from Windows (no extra horizontal line in the middle). It's Windows 8.1, but nothing else I'm aware of that would make the setup special. Also the hand and the arrow cursors both are white with a black outline (as expected I think).

**Comment by alexandrudima** [comment]
This is how it looks for me:

![wehff1hkma](https://cloud.githubusercontent.com/assets/5047891/16459704/297cfe48-3e24-11e6-9bfa-64cde2b78b8a.gif)

Here are my [cursor pointer settings](http://nexxtep.com/2012/02/how-to-change-the-color-of-your-mouse-cursor-in-windows):
![image](https://cloud.githubusercontent.com/assets/5047891/16459722/3ac47e88-3e24-11e6-8778-c5c6fc81b95f.png)

I am on Windows 10. How does the cursor look like for you if you visit https://code.visualstudio.com/ and hover over the copyright text at the bottom in Chrome?

![dwxafr3zv8](https://cloud.githubusercontent.com/assets/5047891/16459814/a664bd60-3e24-11e6-96f4-ff491073b4ec.gif)

**Comment by chrmarti** [comment]
Indeed, the cursor shows the same behavior (black on black text selection cursor) on the code.visualstudio.com website.

**Comment by alexandrudima** [comment]
@chrmarti In this case, please file a bug against Chromium (or if the black on black text selection is reproducible in IE against Windows)

**Comment by chrmarti** [comment]
Appears to be a known issue with Remote Desktop for OSX. Older versions reportedly did not have this. The discussion linked below suggests to swap out the text selection pointer with "beam_r.cur", that works for me.

(https://social.technet.microsoft.com/Forums/windowsserver/en-US/cf05826e-63a4-49d9-b812-7a4695832ab8/rdc-mac-version-8024091-can-not-see-cursor-in-any-editor-with-black-background-because-it-is?forum=winRDc)

**Comment by alexandrudima** [comment]
@chrmarti Nice!

**Comment by chrmarti** [comment]
@alexandrudima Thanks for helping track this down!
