### ISSUE TITLE
Quickpick item implementation that returns $(XXX) for description or detail results in blank UI

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#84012]
- VSCode Version: 1.39.2
- OS Version: Windows X64 Build 19510

Steps to Reproduce:
```typescript
class BlankQuickPickItems implements vscode.QuickPickItem {
    public get label(): string {
        return "$(HELLO)";
    }

    public get description(): string {
        return "$(HELLO)";
    }

    public static async  demonstrateBug(): Promise<void> {
        await vscode.window.showQuickPick( [ new BlankQuickPickItems(), new BlankQuickPickItems() ]);
    }
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@GabeDeBacker Could you attach a screenshot?

**Comment by GabeDeBacker** [comment]
Sure, no problem.

![image](https://user-images.githubusercontent.com/6741868/68980707-1a01f680-07b6-11ea-9ec0-81a77053ec1c.png)

**Comment by chrmarti** [comment]
`$(...)` is the Codicon notation. What would you expect to be shown? Literal `$(HELLO)`?
