### ISSUE TITLE
Run selected text in terminal fails with error

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8402]
Testing #8222
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

0. Close terminal, restart VS Code
1. Open test.txt, select "echo 123"
2. Run selected text in terminal
3. -> Error: Cannot read property 'process' of undefined

**Comment by Tyriar** [comment]
Good find :smiley:

**Comment by sandy081** [comment]
While verifying this on windows 8.1 with insiders latest build 716f76458e4dc93e865b6a999e437ed45774744e

Action Run selected text in terminal is opening terminal and copying text but not running the command. Focus remains in the editor.

I am opening a new issue for this.
