### ISSUE TITLE
Shortcut key conflict

### ISSUE THREAD

**Issue by CwjXFH** [microsoft/vscode#84022]
- VSCode Version:  1.39.2
- OS Version:  WIndows10  1903

Steps to Reproduce:

1.  Set Change Language Model shortcut  ctrl+c l
2.  Set Copy shortcut ctrl+c

When I copy something from the text editor, I press ctrl+c, the editor prompts:`(Ctrl+C) was pressed. Waiting for second key of chord...`.  The `ctrl+c l` shortcut is ok when I delete it,  the Copy shortcut is ok.

That means, when I set  `ctrl+c` as a shortcut, then I can't set other shortcuts begin with `ctrl+c`.

![](https://user-images.githubusercontent.com/11468733/68265381-d527e280-0086-11ea-9fb5-f8ece50da18d.png)

![change language model](https://user-images.githubusercontent.com/11468733/68265820-22f11a80-0088-11ea-8eee-52c413c71d72.png)

![copy](https://user-images.githubusercontent.com/11468733/68265950-7f543a00-0088-11ea-8274-461896ad16e0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
The way in which keyboard dispatching works is documented at https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules

In the keybindings editor UI, you can click "Sort by Precedence" which will sort the keybindings by the order in which they are evaluated.

From what I can see from your screenshot, you have defined `ctrl+c l` to be a global shortcut (without any when condition) and it has precedence over the built in `ctrl+c`. That means that `ctrl+c` is globally a chord start keybinding.

If you want to use `ctrl+c` as both a chord start and an independent keybinding, you can only do so in different/exclusive contexts. For example, you could use the context key "inTerminal" or "textEditorFocus" to have your chord `ctrl+c l` be bound only in certain contexts.
