### ISSUE TITLE
Workspace setting to configure port forwarding for a remote SSH connection

### ISSUE THREAD

**Issue by tobico** [microsoft/vscode#84021]
I absolutely love the new SSH remote development support in Code, but one small aspect of it doesn't quite work exactly how I'd hoped.

The [instructions for Remote SSH](https://code.visualstudio.com/docs/remote/ssh#_always-forwarding-a-port) recommend configuring persistent port forwarding for a project by adding a `LocalForward` directive to the system SSH config file.

It would be a lot more convenient for my workflow if I could configure these port forwards on a per-project basis in my workspace settings, as different projects that I work on need different ports to be forwarded for each project, but all projects are developed on the same remote machine.

**Comment by roblourens** [comment]
You can 😁 

See the setting `remote.SSH.defaultForwardedPorts`

**Comment by tobico** [comment]
@roblourens thanks for your help, but this feature doesn't seem to be working correctly. When I configure port forwarding in my workspace and reload the window, I get ports forwarded to random port numbers rather than the port numbers I specified:

![port-forwarding](https://user-images.githubusercontent.com/125108/68732963-64a23800-0629-11ea-9be0-dd81868fc153.PNG)

**Comment by roblourens** [comment]
Oops, yes this is https://github.com/microsoft/vscode-remote-release/issues/1786
