### ISSUE TITLE
Flakey test: Terminal Extension pty terminals should respect dimension overrides

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#84030]
Sometimes fails on the build agents:
![image](https://user-images.githubusercontent.com/9205389/68275178-3346cc80-006b-11ea-913f-b52754a130bf.png)

**Comment by chrmarti** [comment]
Seen twice with Windows 32bit.

**Comment by Tyriar** [comment]
Was reported 2 years ago and haven't seen any flakiness reported to me basically since then.
