### ISSUE TITLE
vscode freezed 

### ISSUE THREAD

**Issue by janwilmans** [microsoft/vscode#84035]
vscode freezed 

![image](https://user-images.githubusercontent.com/5933444/68282315-be2ec380-0079-11ea-8c62-a519b6b232a4.png)

Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.0-6-amd64

Steps to Reproduce:

1. it happened while compiling a single file within a c++ cmake project
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@janwilmans Can you please report against https://github.com/microsoft/vscode-cpptools

**Comment by janwilmans** [comment]
will do, its not easy to make the distinction sometimes, but I guess from the stacktrace I should have known better
