### ISSUE TITLE
Code action intellisense in the keybindings JSON editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84033]
## Feature request
When creating a keybinding for a specific code action, such as:

```json
	{
		"key": "shift+ctrl+e",
		"command": "editor.action.codeAction",
		"args": {
			"kind": "refactor.extract",
			"preferred": true
		}
	}
```

We should show intellisense for the `args` property and also intellisense for code action kind by leveraging the new contribution point from #82718

/cc @sandy081

**Comment by mjbvz** [comment]
@sandy081 Please take a look at the changes in 166f925. I added a new method in `KeybindingService` to support contributing a dynamic json schema for a command. This seemed like the clearest way to achieve this

**Comment by sandy081** [comment]
@alexandrudima owns this code and hence mentioning him.

**Comment by alexandrudima** [comment]
:+1:
