### ISSUE TITLE
Editor not coloring JS comments correct

### ISSUE THREAD

**Issue by Loffis** [microsoft/vscode#84034]
Issue Type: <b>Bug</b>

Hi,

The editor won't color the comments correct in row 2 & 3. See below.

1 console.log("4" * "5"); // 20
2 console.log('4' / '2'); // 2
3 console.log("4" / "2"); // 2
4 console.log(4 / 2); // 2
5 console.log(4 * "5"); // 20

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.00GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1
html-preview-vscode|tht|0.2.5

</details>

**Comment by gjsjohnmurray** [comment]
/confirm
![image](https://user-images.githubusercontent.com/6726799/68292807-942ece80-0084-11ea-9e4c-9dae417bec08.png)

Also happens in 1.40.0-insider

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript-TmLanguage/issues/787 to track upstream
