### ISSUE TITLE
Activating replace in file when focus is on find in file dialog should not change the find keyword

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8403]
#8230
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:
1. Open a new file, paste in:
   
   ```
   commit 27d5c0e2d7a1e877e094d9a6fc65c5071b797636
   Author: Daniel Imms <tyriar@tyriar.com>
   Date:   Mon Jun 27 16:22:42 2016 -0700
   
       Prevent multiple terminals from being created via createNew
   
       Fixes an exception was being caused because the panel was not initialized
       when calling into createNew. This also fixes multiple terminal instances being
       spawned if the panel WAS initialized but contained 0 processes.
   
       Fixes #8209
   
   commit 8468572d058dfa1eb41d1f82bbb3e01f3eeb0a57
   Author: Daniel Imms <tyriar@tyriar.com>
   Date:   Mon Jun 27 14:29:41 2016 -0700
   
       Uplevel xterm.js
   
   commit 96452b48e70ba0005b46bd529b6538b5e8b92c36
   Author: Martin Aeschlimann <martinae@microsoft.com>
   Date:   Mon Jun 27 22:38:25 2016 +0200
   
       Do not rely on codeSnippet for filtering fixes #6620
   ```
2. Open find in file: <kbd>ctrl</kbd>+<kbd>f</kbd>
3. Toggle regex find: <kbd>alt</kbd>+<kbd>r</kbd>
4. Type `commit.*`
5. <kbd>f3</kbd> to find first instance
6. (Decide that I actually want to replace) <kbd>ctrl</kbd>+<kbd>h</kbd>, notice that the find keyword changes from `commit.*` to `commit\ 8468572d058dfa1eb41d1f82bbb3e01f3eeb0a57` (or whatever commit was highlighted in step 4).

**Comment by alexandrudima** [comment]
postponing after endgame

**Comment by rebornix** [comment]
Played with latest insider, not longer existed.

**Comment by mjbvz** [comment]
I'm still seeing this issue in 3a6eda74ead5b5b041da0bbc18b70218e8c95bba:

![may-31-2017 18-01-57](https://cloud.githubusercontent.com/assets/12821956/26660218/47713fd0-462b-11e7-8dc3-c24d3f302aee.gif)

**Comment by alexandrudima** [comment]
@rebornix If you wanna look into it. Perhaps a fix would consist of remembering if the last editor selection was set via move to next/prev match (i.e. by the find widget) and, if that is the case, the search string should not be seeded from the editor selection when ctrl+f is pressed.

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/44984
