### ISSUE TITLE
Replace custom view item tooltips with a richer UI with the markdown support (like hovers)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#84032]
Currently the tooltip support on custom view items is limited to browser title attribute rendering. It would be great to replace that native tooltip support with a much richer UI -- maybe similar to hovers. This richer UI would support markdown just like hovers do today,

This would allow extensions like GitLens to provide a rich hover over custom view items, just like the blame hovers in the editor -- which would enable, links, commands, and just much richer formatting.

Here is a hover for commit `9f40bf03`:
![image](https://user-images.githubusercontent.com/641685/68279464-79873600-0041-11ea-9e2e-bfe7ffd3aaf3.png)

Here is the same tooltip for that same commit:
![image](https://user-images.githubusercontent.com/641685/68279575-b3f0d300-0041-11ea-8b3a-89d42519c96f.png)

In the hover, there are links to email the user, open the PR, etc. Where as none of that is possible in the tooltip.

**Comment by eamodio** [comment]
Related, I would also really like these more advanced "hovers" to have a call back for when they would be shown. Because right now in GitLens, I sometimes have to make expensive calls when creating tree items, just to fill out the tooltip that is unlikely to be used (at least in relation to all the tree items).

**Comment by eamodio** [comment]
Here is a use-case for this and a dynamic call. I'm adding a new feature to GitLens to provide the Pull Request which introduced a commit (if any), and I would love to have that information in the hover/tooltip of the commit nodes in the tree, but that query is far too expensive to run on every commit and the current tooltip doesn't provide any good way to interact with the information (e.g. click on a link to jump to the PR)

**Comment by tbennun** [comment]
Would inline images work as well?
