### ISSUE TITLE
Append highlight "End With" for VB syntax.

### ISSUE THREAD

**Issue by fujitatakesh** [microsoft/vscode#84037]
Please append a highlight syntax. Target file is below:
/extensions/vb/syntaxes/asp-vb-net.tmlanguage.json line 98

...Next|With|Exit Do... -> ...Next|With|End With|Exit Do...

**Comment by alexr00** [comment]
We get our VB syntax from https://github.com/textmate/asp.vb.net.tmbundle
Feel free to make a PR there and if it's approved then we'll pull in the changes!
