### ISSUE TITLE
Switching focus between webviews in split mode not working correctly

### ISSUE THREAD

**Issue by MartinBrathen** [microsoft/vscode#84042]
- VSCode Version: Stable 1.39.2, Insiders 1.40.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open two images in split view.
2. Ensure one of the images has focus by clicking on it.
3. Press ```ctrl + [appropriate number key]``` to give the other image focus.
4. Click on the same image you clicked on in step 2.

Expected result: The image clicked on in step 4 should get focus again.

Actual result: It does not get focus again.

- I have not tested this on mac, but if you want to, you need to press ```alt``` instead of  ```ctrl``` in step 3.
- This bug can be reproduced using a Markdown preview instead of one of the images.
- This bug can not be reproduced with a text file instead of one of the images. I tested with ```.md```.
- The following event handlers should be triggered in step 4, but are not:
https://github.com/microsoft/vscode/blob/c53db9ba76c06c41b45c7765b143d1f925233f80/extensions/image-preview/src/preview.ts#L38
https://github.com/microsoft/vscode/blob/c53db9ba76c06c41b45c7765b143d1f925233f80/extensions/image-preview/src/preview.ts#L116
[This](https://github.com/MartinBrathen/vscode/blob/focus/extensions/image-preview/src/preview.ts) file can be used to test when the event handlers are triggered or not. Use with Developer Tools in VS Code.
- This is what i mean by focus:
![focus](https://user-images.githubusercontent.com/16407364/68290694-a874ca80-0088-11ea-9556-a69130b13d0c.png)
The image preview on the right has focus in this picture.

I unofficially assign this to @mjbvz 

Please let me know if any additional information is required. I will answer within 24 hours.

**Comment by roguexiaohuihui** [comment]
I had the same problem:
when switching webview, the newly activated webview cannot focus. When the mouse is clicked on the webview page, the focus will be normal

**Comment by emilyoon** [comment]
@alexandrudima  @mjbvz I would like to work on this with @jhuree. Has any work been done on this issue yet?

**Comment by mjbvz** [comment]
I just tested this again and believe it is working as expected in the latest insiders. If not, please share a recording of this so I can make sure I am following the exact steps to reproduce the problem
