### ISSUE TITLE
Hide all comments (python) toggle

### ISSUE THREAD

**Issue by settlej** [microsoft/vscode#84047]
Ability to minimize/hide all "#" comments in python

**Comment by aeschli** [comment]
What you are requesting needs to be implemented in the Python extension which creates the language aware folding ranges.
The python extension should also create a folding range for  `# `comments that go over multiple lines.
By giving it the 'comment' folding range kind, users can then use the `Fold All Block Comments` command.

**Comment by aeschli** [comment]
@settlej Please file the request against https://github.com/Microsoft/vscode-python
