### ISSUE TITLE
copy files to the specified format

### ISSUE THREAD

**Issue by kebyn** [microsoft/vscode#84041]
In order to quickly copy the text to the terminal, I will add a shell cat syntax to all the files, but this method will be marked as a syntax error in the file. 
I want to try to propose a function, you can directly right-click or shortcut the file. Copy text into this format
If there are existing plugins to meet my needs, please let me know, thank you
```
cat > filename <<\EOF
and so on ....
EOF
```
![image](https://user-images.githubusercontent.com/9145323/68287844-5b135000-00be-11ea-8b9a-f4333b793384.png)

**Comment by gjsjohnmurray** [comment]
Judging by your screenshot this is the responsibility of the Docker extension you are using, so probably needs to be logged at https://github.com/microsoft/vscode-docker and closed here.

**Comment by kebyn** [comment]
@gjsjohnmurray I will mark it in all the files, just use the Dockerfile to show this usage.
