### ISSUE TITLE
One file to rule them all [config]

### ISSUE THREAD

**Issue by atilkan** [microsoft/vscode#84059]
Hi,
Let's say i have a project folder. I have many configuration file in the project root (tsconfig, prettier, eslint, etc.)
It could be nice to move them in a sub-folder and link them by the one linker file which vscode recognizes.
All purpose is to make root folder a little bit cleaner.

**Comment by sandy081** [comment]
These files belong to separate applications/libraries like tslint, eslint etc., and do not belong to VS Code.

**Comment by atilkan** [comment]
@sandy081 I am aware of this. If these applications work on terminal we can point them. But at the same time those applications work on VSCode. VSCode can help these programs find their configs.  This may require something new.

**Comment by sandy081** [comment]
This cannot be done out of the box in VS Code as it does not has any knowledge about this. So this has to be an extension.

**Comment by atilkan** [comment]
Yep. It is like map for config files. Currently there are too many configs to have in a project and this is just an idea.
