### ISSUE TITLE
Minimap pixelation after system sleep

### ISSUE THREAD

**Issue by Javanmardi** [microsoft/vscode#84054]
- VSCode Version: 1.39.2 via official deb offered by code.visualstudio.com
- OS Version: Ubuntu 18.04.3 bionic on Xorg
- Kernel: 5.0.0-32-generic
- Graphic driver: nvidia-driver-390.116-0ubuntu0.18.04.1

Steps to Reproduce:

1. A system sleep would produce the problem in which the minimap is fully pixelized. To prevent the problem one should close VSCode before sleep or close and reopen tabs after system start.
2. Disabling all the extensions won't prevent this problem. Also I didn't check if there is such a problem on nouveau (open-source driver).
3. A screenshot may help to picture the problem.

Does this issue occur when all extensions are disabled?: Yes

![VSCode-Screenshot](https://user-images.githubusercontent.com/16988499/68303912-079f0300-00ba-11ea-80d9-4686bbb3c034.png)

**Comment by alexandrudima** [comment]
Let's track in #69665
