### ISSUE TITLE
Tasks.json escaping quotes is not working

### ISSUE THREAD

**Issue by NikkiSharmaT1** [microsoft/vscode#84058]
Issue Type: <b>Bug</b>

Oon running a task which executes an SF query, it doesnt escape quotes and parses the query incorrectly.

This is the query i am trying to execute: 
```
"command": "sfdx force:data:soql:query -q \"Select Name, T1C_FR__External_Id__c, T1C_FR__Name__c, T1C_FR__Permission_Required__c FROM T1C_FR__Feature__c WHERE T1C_FR__Core_Feature__c = '' ORDER BY T1C_FR__Name__c ASC\" -r csv > data/t1-afr/t1-feature.csv"
```
But VS code parses it wrong and throws the following error: ERROR running force:data:soql:query:  Unexpected arguments: Name, T1C_FR__Feature__r.T1C_FR__External_Id__c, T1C_FR__User_Overridable__c, T1C_FR__Value__c, T1C_FR__External_Id__c, FROM, T1C_FR__Attribute__c, WHERE, T1C_FR__Feature__r.T1C_FR__Core_Feature__c, =, ORDER, BY, T1C_FR__Feature__r.T1C_FR__Name__c, Name, ASC
See more help with --help
The terminal process terminated with exit code: 1

It adds unnecessary commas in the query and fails.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
escape-quotes|mil|1.0.5
salesforcedx-vscode|sal|47.4.0
salesforcedx-vscode-apex|sal|47.4.0
salesforcedx-vscode-apex-debugger|sal|47.4.0
salesforcedx-vscode-apex-replay-debugger|sal|47.4.0
salesforcedx-vscode-core|sal|47.4.0
salesforcedx-vscode-lightning|sal|47.4.0
salesforcedx-vscode-lwc|sal|47.4.0
salesforcedx-vscode-visualforce|sal|47.4.0

</details>

**Comment by alexr00** [comment]
What shell are you using? You probably just need to update your command to use appropriate escaping for your shell.

**Comment by NikkiSharmaT1** [comment]
Hi Alex,

Thank you for getting back. I am using power shells. Its actually breaking only on my machine – it works fine on my colleagues machin who is using the same repo and the same scripts. I cloned it using his repo.

Can something be missed during the clone process?

Thanks,
[T1_Logo_Blue_FS_1in]
Nikki Sharma | Business Analyst
T: +1.647.251.3873 M: +1(437)240-3535  | nikki.sharma@tier1fin.com<mailto:nikki.sharma@tier1fin.com>
www.tier1fin.com<http://www.tier1fin.com/> | Recipient of Deloitte Technology – Fast 500 in NA
[linkedin]<https://www.linkedin.com/company/tier1fin>[cid:image003.png@01D59559.4B8AE740]<https://twitter.com/Tier1Fin>[cid:image004.png@01D59559.4B8AE740]<https://tier1fin.com/insights/>

**Comment by alexr00** [comment]
If it's working on one machine and not another then you have some setup difference. I recommend checking these settings: `terminal.integrated.automationShell.windows` and `terminal.integrated.shell.windows`
