### ISSUE TITLE
C_Cpp.dimInactiveRegions not working with #if false in VSCodeVim with Light+ theme

### ISSUE THREAD

**Issue by emmenlau** [microsoft/vscode#84057]
Issue Type: <b>Bug</b>

I've enabled `"C_Cpp.dimInactiveRegions": true` and set `"C_Cpp.inactiveRegionOpacity": 0.45` in `settings.json`. However code blocks in
```
#if false
    // some code here
#endif
```
do not show any change in color or opacity. I've tried various other values for background color or opacity, and tried other types of undefined statements, all to no avail. See attached image for an example. I would expect the code inside `#if false` to have reduced opacity.

![screenshot](https://user-images.githubusercontent.com/1098087/68305631-52178400-00a8-11ea-913c-a6a131b8aac5.png)

I'm not certain if this is affected by the theme? I'm using a theme called `Light+ (default light)`. Also I have extensions `VSCodeVim` and `Bracket Pair Colorizer 2` active.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.86GB (26.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
doxdocgen|csc|0.5.2
gitlens|eam|10.1.2
vscode-test-explorer|hbe|2.14.6
vscode-catch2-test-adapter|mat|2.7.6
cpptools|ms-|0.26.1
rewrap|stk|1.9.1
vim|vsc|1.11.3

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
Can you please open an issue directly against the C++ extension at https://github.com/microsoft/vscode-cpptools

**Comment by emmenlau** [comment]
For future reference, this issue is now tracked here: https://github.com/microsoft/vscode-cpptools/issues/4564
