### ISSUE TITLE
Adopt Cascadia Code as the default font on first install.

### ISSUE THREAD

**Issue by otaconjh** [microsoft/vscode#84064]
Cascadia Code

**Comment by misolori** [comment]
Our default font stack is optimized for local OS fonts:

https://github.com/microsoft/vscode/blob/00ebabb065f988e9b88ca621066e9ba15b1bd619/src/vs/editor/common/config/editorOptions.ts#L2873-L2875

Given that you need to install Cascadia Code (it's not pre-installed) and it's a very new (young) font, I don't think this will be possible. Thanks for the suggestion but I'll close this as out of scope. If it ever becomes bundled in Windows and has better character support we might re-consider.
