### ISSUE TITLE
Internal console will hangs on java exception text.

### ISSUE THREAD

**Issue by fdurajka** [microsoft/vscode#84061]
- VSCode Version: 1.40.0-insider
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Install clean VS code insider 
2. Install Java extension pack
3. Run java application below, redirect output to internalConsole via launch.json
4. Internal console will show only two first lines, then hangs.

Application to reproduce - will just print this exception instead of raising it, result is the same.
```java
public class TestApplication {
    public static void main(String[] args) {
        System.out.println("Exception in thread \"main\" java.lang.IllegalArgumentException: failed");
        System.out.println("	at TestApplication.main(TestApplication.java:7)");
        System.out.println("	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)");
        System.out.println("	at TestApplication.main(TestApplication.java:7)");
    }
}
```

Does this issue occur when all extensions are disabled?: No (we need java to run java programs)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by fdurajka** [comment]
Hi Daniel, just to be sure - the output is actually going into "debug console" and not into "terminal" window.  Is the winpty/conpty actually used when rendering "debug console" window?

**Comment by Tyriar** [comment]
@fdurajka oh I missed that sorry

**Comment by isidorn** [comment]
This works just fine when I print those message using node debugging.
@fdurajka can you please file this issue against the java extension so they investigate first if the issue is on their end. Thank you very much
https://github.com/microsoft/vscode-java-debug
