### ISSUE TITLE
Default extension image contrast ratio is very low

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8406]
#8215
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

The low contrast makes it's difficult to make out that the top-right corner is not the same as the rest, ie. it looks like a square inside a circle.

![image](https://cloud.githubusercontent.com/assets/2193314/16426485/106c85a6-3d1e-11e6-9572-c856a260ef8c.png)

**Comment by bgashler1** [comment]
Let's talk about this in UX sync next week.

**Comment by joaomoreno** [comment]
This comes from the Marketplace. cc @modigrv

**Comment by modigrv** [comment]
The default image is also different from one shown on marketplace website. I am creating a bug to fix and give correct default image.

**Comment by joaomoreno** [comment]
Feedback sent.
