### ISSUE TITLE
Cannot access extensions market behind corporate authenticated proxy

### ISSUE THREAD

**Issue by marcosjl** [microsoft/vscode#84065]
Using VS Code 1.39.2 under both  Centos 7.3.1611 and Windows 10 os, behind corporate authenticated proxy.

No problem with Windows : proxy server is defined at OS level through proxy.pac file.

Under Centos 7, i use http_proxy="http://login:password@proxy.domain:8080" ; export http_proxy to define the proxy information.
VS Code seems to ignore the http_proxy env and prompts me for proper login/password. But no information is retrieved from Internet.

Capturing traffic (wireshark) shows that no login/password are provided to the proxy resulting in a 407 error.

I ran VS Code with '--verbose' parameter; logs show 2 traces refering to "getUnixShellEnvironment" : 

- the first one (getUnixShellEnvironment#env) contains the correct http_proxy variable with login/password in it : http_proxy="http://login:password@proxy.domain8080";

-  the second one (getUnixShellEnvironment#raw) contains the http_proxy without login/password information in it :  http_proxy="http://proxy.domain8080"

Thus : no access to extensions marketplace nor update server...

- VSCode Version: 1.39.2
- OS Version: Centos 7.3.1611

**Comment by chrmarti** [comment]
Try starting with `code --proxy-server=<full proxy url>` (https://code.visualstudio.com/docs/setup/network#_proxy-server-support).

**Comment by marcosjl** [comment]
Tried : does not work either.
When using '--verbose --log trace', I see this error message :
`[Error: net:: ERR_NO_SUPPORTED_PROXIES`

**Comment by marcosjl** [comment]
Ok.. 
I get the `[Error: net:: ERR_NO_SUPPORTED_PROXIES` message when I use : '--proxy-server="http://login:password@proxy.domain".

If I use '--proxy-server="http://proxy.domain", VS Code prompts me for proxy credentials but no Inernet access is done and I get a 'net:: ERR_TUNNEL_CONNECTION_FAILED' (in Developper Tools window)

**Comment by chrmarti** [comment]
Looks like passing credentials there is not supported: https://bugs.chromium.org/p/chromium/issues/detail?id=615947

Some have pointed to https://github.com/sjitech/proxy-login-automator to help solve this problem.
