### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by Julius-Nepos** [microsoft/vscode#84069]
Trying to install VS Code from the installer  VSCodeUserSetup-x64-1.39.2.exe onto a Windows-10 64 bit computer.  Every turn get an error.  Wanted to install it to C:/Programs x86 rather than an unknown App data folder (where I'll never find it).   First it couldn't make the directory, so I created that with all permissions, now it has another error.  Every install attempt gets an error, tried 3-4 times.  It doesn't want to me install as Administrator.

**Comment by joaomoreno** [comment]
If you'd like to install it in Programs x86, simply use the System Steup: https://code.visualstudio.com/docs/?dv=win64
