### ISSUE TITLE
The file HTML isn't recognize by vsCode

### ISSUE THREAD

**Issue by SaintLuan** [microsoft/vscode#84067]
Issue Type: <b>Bug</b>

I'm writing a code at HTML, but the file don't recognize, unless i use HTM.

Extension version: 0.2.3
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (7.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexandrudima** [comment]
@SaintLuan I am sorry, but I don't quite understand what you mean. Do you have a `file.html` that does not open correctly? If that is the case, can you please attach it here?
