### ISSUE TITLE
Extension tests fail with vscode 1.39.2

### ISSUE THREAD

**Issue by Friday32** [microsoft/vscode#84063]
I used the the yeoman generator to create a skeleton for my extension and tests months ago.  I've been adding tests and running them with no issue until recently.  The test script downloads the latest copy of vscode. The current version is 1.39.2.

Running the tests with 1.39.2 results in errors such as "Uncaught Error: connect ECONNREFUSED 127.0.0.1:8080" .  

 I thought it might have something to do with my async tests. After hours of debugging, I eventually disabled all but a few synchronous tests.  Still had the problem.  I re-enabled all my tests and found disabling code within my extension's activate method allow my tests to run issue free .  There's nothing obvious to me in this code that should cause a problem. It's probably some timing issue affected by activation startup time; I get different results on different machines.  My development PC is the fastest and doesn't fail, my build machine is the slowest and fails every time, and another machine sometimes fails.

I updated my test runner to download and use vscode 1.38.0. The tests run perfectly on all three machines.

**Comment by octref** [comment]
> Running the tests with 1.39.2 results in errors such as "Uncaught Error: connect ECONNREFUSED 127.0.0.1:8080" .

How are you running the test, and where are you seeing the errors?
Does it happen if you add `--disable-extensions` to the `launchArgs`? Example here: https://github.com/Microsoft/vscode-test

**Comment by Friday32** [comment]
I'm running a npm script on the command line, "npm test". My setup is similar to the one at https://github.com/microsoft/vscode-extension-samples/blob/master/helloworld-test-sample.  The error is reported in the console output between individual test results.  It doesn't always occur in the same sequence.  I get  slightly different results running in vscode with a launch configuration where the tests seem to fail less often.  
 
I ran with and without the --disable-extensions flag.

**Comment by octref** [comment]
Does this still happen with latest version? Latest sample should work on all 3 platforms: https://dev.azure.com/vscode/vscode-test/_build?definitionId=15

**Comment by Friday32** [comment]
I have not seen the problem recently.
