### ISSUE TITLE
Flickering and garbled text in fullscreen or zen mode

### ISSUE THREAD

**Issue by pdxDev** [microsoft/vscode#84068]
I reported a similar problem here:
https://github.com/microsoft/vscode/issues/82790

That thread was closed as it was thought to be fixed in the insider's edition.  I am now having this problem in 1.39.2 and insiders.  See image for example.  The artifacts will keep spreading until the entire screen is covered and completely unreadable.  Moving the mouse will clear it up and then 5-10 seconds later it comes back and starts growing again.

![visual problem](https://user-images.githubusercontent.com/42416428/68325146-b5d88780-007d-11ea-8a02-defda1b7c39b.jpg)

- VSCode Version:  1.39.2 (or insiders)
- OS Version:  Win 10  x64

Steps to Reproduce:

1.  Edit code in fullscreen or zen mode.
2. Can happen while NOT in fullscreen/zen mode.  I've not been able to make it happen consistently in the normal windowed mode however.

Does this issue occur when all extensions are disabled?:  Yes

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by pdxDev** [comment]
Using code --disable-gpu seemed to have worked in my limited testing so far.

I'd like to make this change permanent, but there does not seem to be a Configure Runtime Arguments with my setup.  The Command Palette did not return any results while searching.  Any ideas?  

Thanks.

**Comment by bpasero** [comment]
@pdxDev great, yes you need our next update which should come out today.
