### ISSUE TITLE
Add key binding to focus next terminal within project only

### ISSUE THREAD

**Issue by kumar303** [microsoft/vscode#84076]
I would like to assign a key binding to something like `terminal.focusNextPaneInProject` that would work like `workbench.action.terminal.focusNextPane` but it would only cycle through terminals in the *current* project.

As it is in VSCode 1.39.2, if you have multiple projects open in separate windows, `focusNextPane` will cycle through each terminal across all open projects.

**Comment by Tyriar** [comment]
I feel like this is too niche to be built into the core product. It will however be possible and quite easy to put an extension together that does this once this API becomes stable: https://github.com/microsoft/vscode/pull/84005

**Comment by kumar303** [comment]
OK, thanks. Cycling through all project terminals is surprising behavior to me. I expected it to work more like `workbench.action.navigateEditorGroups`.
