### ISSUE TITLE
Menus Scroll to Top when zoomed in

### ISSUE THREAD

**Issue by Wavelord** [microsoft/vscode#84073]
Issue Type: <b>Bug</b>

When you zoom in on the VS Code editor (such as if you need to view text much larger so it is readable from further away), a scrollbar will appear on the context menus (File, Edit, Selection, View, etc.) if they are long enough.

When this scrollbar is present, if you scroll down, you'll notice it immediately starts scrolling back to the top wihout user input, where as it remaining still is expected. I discovered this when I zoomed in and couldn't remember the keyboard shortcut for resetting zoom and was digging for it in the menus.

Long story short: When you zoom in, context menus may gain scrollbars. When they do, the functionality of the scrollbars reacts unexpectedly.

Expected functionality would be to allow you to scroll to a specific position and remain there.

Actual functionality is that when you scroll to a specific position, it immediately (without input) scrolls back up to the top, preventing the ability to interact with lower menu items.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.15063

<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vscode-faker|dee|1.3.0
xml|Dot|2.5.0
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
prettier-vscode|esb|2.3.0
code-runner|for|0.9.14
minify|Hoo|0.4.3
Ionide-fsharp|Ion|4.2.0
svg|joc|1.0.5
codeacejumper|luc|2.1.6
Kotlin|mat|1.7.0
mssql|ms-|1.7.0
csharp|ms-|1.21.6
powershell|ms-|2019.11.0
material-icon-theme|PKi|3.9.1
vscode-sort-json|ric|1.18.0
closure-compiler|rua|1.2.12
sort-lines|Tyr|1.8.0
change-case|wma|1.0.0

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@Wavelord this will be fixed in the next release by https://github.com/microsoft/vscode/pull/80965
