### ISSUE TITLE
command git clone not found

### ISSUE THREAD

**Issue by okon32** [microsoft/vscode#84077]
![error](https://user-images.githubusercontent.com/47580367/68337693-54e29b00-00e1-11ea-8766-09cea4a01aa4.jpg)
Issue Type: <b>Bug</b>

1. Ctrl + Shift + P and type "git clone"
2. Press Enter

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1

</details>

**Comment by joaomoreno** [comment]
Can you run `Developer: Toggle Developer Tools` and see if you have any errors in the console?

**Comment by okon32** [comment]
I'm sorry, I just thought that Git extension is enough. After installing Git software "git clone" command works well.
