### ISSUE TITLE
Launch args adds double quotes to input variables

### ISSUE THREAD

**Issue by yeggles** [microsoft/vscode#84071]
I was having troubles coming up with a good title, but either way here is the issue I am seeing.  I was trying to use an input variable to allow the users to specify what command line arguments they would like to use when launching one the apps in my solution.  The input works but, launch args adds double quotes to whatever the user chose to input.  This causes 1+ arguments to be seen as a single argument by the program.

Using input variables work for tasks since the "command" variable allows me to put the input variable after the application's name, but if I try to add the input variable to "program" then it will throw an error.  I don't see a work around, but I don't consider myself to be a VS Code expert.

launch.json example:
```jsonc
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations":
    [
        {
            "name": "Launch",
            "type": "cppdbg",
            "request": "launch",
            "cwd": "${workspaceRoot}/.vscode/Launch/",
            "program": "${workspaceRoot}/.vscode/Launch/${input:App List}",
            "args":
            [
                "${input:App Arguments}"
            ],
            "stopAtEntry": true,
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "/usr/bin/gdb",
            "miDebuggerArgs": "",
            "setupCommands":
            [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "filterStderr": true,
            "filterStdout": true,
            "logging":
            {
                "engineLogging": false,
                "exceptions": true,
                "moduleLoad": true,
                "programOutput": true,
                "trace": false,
                "traceResponse": false
            }
        },
    ]
    "inputs":
    [
        {
            "id": "App List",
            "description": "Select the desired application to debug",
            "type": "pickString",
            "default": "bin/app1",
            "options":
            [
                "bin/app1",
                "bin/app2",
                "tools/ex1",
                "tools/ex2"
            ]
        },
        {
            "id": "App Arguments",
            "description": "Optional:  Input command arguments",
            "type": "promptString",
            "default": ""
        },
    ]
}
```

**Comment by yeggles** [comment]
I have attached additional information about my VS Code setup in case you need more information.

VS Code - Help - About:
- Version: 1.39.2 (user setup)
- Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- Date: 2019-10-15T15:35:18.241Z
- Electron: 4.2.10
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17134

All of my extension:
- ms-vscode-remote.vscode-remote-extensionpack
- ms-vscode.cpptools
- ibm.output-colorizer
- mhutchie.git-graph

**Comment by weinand** [comment]
Please file a feature request against the C++ debugger to support an alternative string property in the launch configuration that takes a full command line.
