### ISSUE TITLE
Allow to pass in a filename to use for stdin piping

### ISSUE THREAD

**Issue by Neaox** [microsoft/vscode#84079]
Currently, you can pipe text into `code` and a temp file will be created, written to and opened in vscode, this temp file is named `stdin-xxxx.txt`.

The issue with this is that the name has no meaning, and syntax highlighting does not work for this new file.

### Why not create a file yourself, name it whatever you want and open that via the CLI?

Because it would be great to be able to present a file open in vscode to a user with a suggested filename but they get to choose if and where they save it. This would use some of the untitled file/unsaved file logic.

This would be useful for instance, if you wanted to open some sort of log automatically after a script has run. The user then may or may not save it.

<img width="454" alt="Run command" src="https://user-images.githubusercontent.com/13699847/68344052-08d03e80-0153-11ea-94da-8ed6d6c27cee.png">

<img width="558" alt="Unsaved file is opened" src="https://user-images.githubusercontent.com/13699847/68344057-0d94f280-0153-11ea-8345-2368e3cbf120.png">

<img width="1188" alt="Confirm close" src="https://user-images.githubusercontent.com/13699847/68344085-15549700-0153-11ea-9164-6ec06319aeca.png">

<img width="850" alt="Save Dialog" src="https://user-images.githubusercontent.com/13699847/68344097-1b4a7800-0153-11ea-8513-f4a7a8052823.png">

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/62929

Challenge is that stdin might still write after VSCode has opened and we currently have no communication from the process to VSCode (we basically use the temp file and file change events as a solution for that).
