### ISSUE TITLE
Freezes and Multiwindow Problems

### ISSUE THREAD

**Issue by Cryptobyte** [microsoft/vscode#84085]
Issue Type: <b>Bug</b>

When I switching windows between multiple maximized VSCode windows with different projects in each window it shows the wrong window. It also randomly freezes the editor completely seemingly at random.

Definately not a system issue as all other applications do not have either issues. Even when VSCode is completely frozen the rest of the system works perfectly fine without stutter or freezing. Other multi window applications can switch between windows like normal. 

The window issue only occurs when VSCode is maximized it does not happen when the window is not maximized.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3604)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
vscode-npm-script|eg2|0.3.9
react-native-snippet|jun|0.5.5
vscode-react-native|msj|0.13.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Cryptobyte** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Thank you for the reply, I will test it out today.

**Comment by bpasero** [comment]
Thanks

**Comment by Cryptobyte** [comment]
It looks like the Insiders build is not facing the same problems.
