### ISSUE TITLE
terminal.integrated.windowsEnableConpty is not being respected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#84082]
An issue with the node-pty update caused the conpty setting to not do anything, instead reverting to the node-pty default for conpty (always when Windows 18309+ is being used). Since I've recommended using that setting as a workaround for certain ConPTY issues (like https://github.com/microsoft/vscode/issues/71966), this feels like it meets the bar for 1.40.

**Comment by Tyriar** [comment]
To verify on a Window 10 build 18309+ machine (run ver to check build number):

1. Set `terminal.integrated.windowsEnableConpty` to true and verify that a conpty process gets created. Check the process explorer for conpty process.
2. Set it to false and verify a winpty process gets created.

conpty processes look like the ones in red under the window, winpty are in blue:

![image](https://user-images.githubusercontent.com/2193314/68346255-855a1300-00a8-11ea-9129-0b2df4e5c246.png)

**Comment by mjbvz** [comment]
Closing to make sure this shows up in our verification query. Testing now

**Comment by Tyriar** [comment]
Moved to recovery as we didn't want to push the release out another day.
