### ISSUE TITLE
Consider workspace dirname in multi-root Go to File

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#84086]
If you have a multiroot solution with, for instance, many `index.js`'s, you have no way to easily go to one using Ctrl+P.

```
workspace
├── foo
│   └── index.js
├── bar
│   └── index.js
├── baz
│   └── index.js
└── my.code-workspace
```

I'd like to be able to ctrl+P for `foo/index.js` to find that version of the file, but doing so right now will show no results.

**Comment by iansan5653** [comment]
It works right now for me 
![image](https://user-images.githubusercontent.com/2294248/68351854-b51e1080-00d2-11ea-9c2b-ac72ac109f4d.png)

**Comment by iansan5653** [comment]
Looks like it's working already:
![image](https://user-images.githubusercontent.com/2294248/68351954-f8787f00-00d2-11ea-9d95-129ccac63e72.png)

**Comment by connor4312** [comment]
Hm, not so for me...

![](https://memes.peet.io/img/19-11-ac5df785-ba7b-4ea7-9612-cbe407a85712.gif)

**Comment by iansan5653** [comment]
Oh I see. So you have a multi-root workspace and VSCode doesn't include the root folder names in its index. I was using a single-root workspace with multiple subfolders.
