### ISSUE TITLE
Clipboard Service API not supported in FF

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#84084]
Firefox does not support `navigator.clipboard` read and write API.

refs https://github.com/microsoft/vscode/issues/83595

**Comment by rebornix** [comment]
Based on https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API, right now in Firefox, there are quite a few limitations with Clipboard API, quote:

* `readText`: only available in Browser extensions
* `writeText`: available without permission in secure contexts and browser extensions, but **only from** user-initiated event callbacks
* `read`/`write`: available when users have browser preference `dom.events.asyncClipboard.dataTransfer` set to `true`

Taking above limitations into account, we may want to rely on browser behaviors only for clipboard related actions.

**Comment by plisy** [comment]
Would it be possible to surface an error message if the clipboard isn't available?

**Comment by hsinyi** [comment]
clipboard.read/writeText() and read/write() are now supported, since Fx 127. 
https://www.mozilla.org/en-US/firefox/127.0/releasenotes/
