### ISSUE TITLE
Use shell command output for command input variables

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode#84081]
Support shell command output as input variables in `launch.json` and `tasks.json`. Maybe it deserves to be a new input type of `"shell"`, and it should have basically all the abilities and parameters of a shell task.

**Comment by alexr00** [comment]
While this would be cool, I'm inclined to call it out of scope. Tasks is intended to make running of existing scripts and processes easy, not to provide a programming language. If you need to run a script from your script, you can write another script to do so. I'll leave launch for @weinand

**Comment by weinand** [comment]
I fully agree with @alexr00.

In addition it is already possible to write an extension that contributes a command `runMyShellCommand` that executes the shell script and returns "shell command output" as a string.
This command can then be used as a variable via this syntax `${command:runMyShellCommand}`
