### ISSUE TITLE
Feature: Add CTRL+SHIFT+* Support in Terminal

### ISSUE THREAD

**Issue by tracker1** [microsoft/vscode#84080]
Much like the new Windows Terminal, and various terminal applications on other OSes, it would be nice of the terminal panel in VS Code supported CTRL+SHIFT+*, such as `CTRL+SHIFT+C` for copy and `CTRL+SHIFT+V` for paste.

This is pretty much built into muscle memory and it's annoying on windows in VS Code (I think it already works this way at least in Linux) when the behavior is different and/or unsupported.

**Comment by Tyriar** [comment]
FYI you can configure this pretty easily: https://www.growingwiththeweb.com/2017/03/mastering-vscodes-terminal.html#copy-and-paste

**Comment by Grommers00** [comment]
Could I try tackling this?

**Comment by tracker1** [comment]
@Tyriar thanks, had to add a keybindings.json file to %APPDATA%/Code

@Grommers00 hopefully your PR is accepted, would be nice if the defaults supported both... for me muscle memory has gotten pretty strong.. I tend to split my time pretty evenly on Windows and Linux lately, though less time on Mac since I switched to Linux at home, and will probably swap out my Macbook later in the year.

**Comment by tracker1** [comment]
Also, it is the default in the new windows terminal itself, so would be nice to support it.. may even want to align the default with a big release note.

**Comment by Tyriar** [comment]
@Grommers00 sure, let's align since Windows Terminal does it. It should be fairly easy to do, here's the code pointer:

https://github.com/microsoft/vscode/blob/e18864d486e3b81c4db40033771e1802ede54f77/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L557-L566

**Comment by Grommers00** [comment]
Awesome thanks! I'll be trying it out this weekend!

@Tyriar thanks for pointing me in the right direction :).

**Comment by Grommers00** [comment]
I believe this is good, the comment line above also had a spelling mistake, miht instead of might. So I included that as well. Also, I tested and seemed to work well. 

Let me know if this is good or if I need to make additional changes.
