### ISSUE TITLE
Can't format an especific .js file

### ISSUE THREAD

**Issue by gabrielbarbosanascimento** [microsoft/vscode#84095]
<syntax> TypeScript Server Error (3.6.3) Debug Failure. False expression: Token end is child end Error: Debug Failure. False expression: Token end is child end at processChildNode (tsserver.js:113630:34) at tsserver.js:113577:21 at visitNode (tsserver.js:17019:24) at Object.forEachChild (tsserver.js:17423:21) at processNode (tsserver.js:113576:20) at processChildNode (tsserver.js:113636:21) at processChildNodes (tsserver.js:113687:48) at tsserver.js:113579:21 at visitNodes (tsserver.js:17024:24) at Object.forEachChild (tsserver.js:17420:24) at processNode (tsserver.js:113576:20) at processChildNode (tsserver.js:113636:21) at tsserver.js:113577:21 at visitNode (tsserver.js:17019:24) at Object.forEachChild (tsserver.js:17418:21) at processNode (tsserver.js:113576:20) at processChildNode (tsserver.js:113636:21) at processChildNodes (tsserver.js:113687:48) at tsserver.js:113579:21 at visitNodes (tsserver.js:170...

- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open the .js file (React Native JSX)
2. Press shift + alt + f to format my code (it works in any other file)

**Comment by mjbvz** [comment]
Please share the file

**Comment by gabrielbarbosanascimento** [comment]
`render() {
        const { selectedLocation } = this.props;
        return (
            <Container>
                <Header title="Locais de Entrega" />
                <AvisoLogin
                    text="Endereços de entrega estão apenas disponíveis para usuários cadastrados. 
                    Crie sua conta para pode cadastra endereços de entregas para continuar com suas compras"
                    visible={this.state.avisoLogin}
                    popOnCancel
                    dismiss={this.dismissAvisoLogin.bind(this)} />
                <NumEnderecoBottomSheet
                    visible={this.state.showModalNum}
                    dismiss={() => this.toggleModal()}
                    onPress={(num) => this.onPressNum(num)} />
                <EnderecoOptionsBottomSheet 
                visible={this.state.enderecoEdit != null}
                endereco={this.state.enderecoEdit}
                dismiss={()=> this.toggleEnderecoOptions() }
                onPressDelete={()=> this.deleteEndereco()}
                />
                <View style={Styles.container}>
                    <View
                        style={{ padding: 16, paddingBottom: 0 }}>
                        <Input
                            value={this.state.search}
                            onChangeText={(text) => this.onChangeSearchText(text)}
                            icon="search"
                            placeholder="Digite um endereço para adicionar"
                            colored
                            label={{ backgroundColor: Theme.background, text: "Pesquisar" }} />
                    </View>
                    {this.state.loading ? (
                        <View style={{ alignItems: "center" }}>
                            <Lottie
                                style={{ height: 50 }}
                                resizeMode="contain"
                                source={require('../../lotties/loading.json')}
                                autoPlay
                                loop
                            />
                        </View>
                    ) : (
                            <View style={{ flex: 1 }}>
                                {this.state.search.length > 0 ? (
                                    <FlatList
                                        contentContainerStyle={{ flexGrow: 1, paddingHorizontal: 16, paddingTop: 12 }}
                                        style={{ flex: 1 }}
                                        keyExtractor={(item, index) => 'local' + index}
                                        renderItem={({ item, index }) =>
                                            <Endereco 
                                            item={item}  
                                            onPress={(endereco) => this.onPressEndereco(endereco)} />
                                        }
                                        data={this.state.searchResults} />
                                ) : (
                                        <FlatList
                                            contentContainerStyle={{ flexGrow: 1, backgroundColor: '#EEE', paddingHorizontal: 16, paddingTop: 8 }}
                                            style={{ flex: 1 }}
                                            keyExtractor={(item) => 'localsalvo' + item.id}
                                            renderItem={({ item }) =>
                                                <EnderecoSalvo 
                                                selectedLocation={selectedLocation} 
                                                onPress={() => this.setLocation(item)} 
                                                onPressOptions={()=> this.setState({enderecoEdit: item})}
                                                endereco={item}/>
                                            }
                                            data={this.state.enderecosSalvos} />
                                    )}
                            </View>
                        )
                    }
                </View>
            </Container>
        );
    }`

**Comment by gabrielbarbosanascimento** [comment]
```<Container>
                <Header title="Locais de Entrega" />
                <AvisoLogin
                    text="Endereços de entrega estão apenas disponíveis para usuários cadastrados. 
                    Crie sua conta para pode cadastra endereços de entregas para continuar com suas compras"
                    visible={this.state.avisoLogin}
                    popOnCancel
                    dismiss={this.dismissAvisoLogin.bind(this)} />
                <NumEnderecoBottomSheet
                    visible={this.state.showModalNum}
                    dismiss={() => this.toggleModal()}
                    onPress={(num) => this.onPressNum(num)} />
                <EnderecoOptionsBottomSheet 
                visible={this.state.enderecoEdit != null}
                endereco={this.state.enderecoEdit}
                dismiss={()=> this.toggleEnderecoOptions() }
                onPressDelete={()=> this.deleteEndereco()} />
                <View style={Styles.container}>
                    <View
                        style={{ padding: 16, paddingBottom: 0 }}>
                        <Input
                            value={this.state.search}
                            onChangeText={(text) => this.onChangeSearchText(text)}
                            icon="search"
                            placeholder="Digite um endereço para adicionar"
                            colored
                            label={{ backgroundColor: Theme.background, text: "Pesquisar" }} />
                    </View>
                    {this.state.loading ? (
                        <View style={{ alignItems: "center" }}>
                            <Lottie
                                style={{ height: 50 }}
                                resizeMode="contain"
                                source={require('../../lotties/loading.json')}
                                autoPlay
                                loop
                            />
                        </View>
                    ) : (
                            <View style={{ flex: 1 }}>
                                {this.state.search.length > 0 ? (
                                    <FlatList
                                        contentContainerStyle={{ flexGrow: 1, paddingHorizontal: 16, paddingTop: 12 }}
                                        style={{ flex: 1 }}
                                        keyExtractor={(item, index) => 'local' + index}
                                        renderItem={({ item, index }) =>
                                            <Endereco 
                                            item={item}  
                                            onPress={(endereco) => this.onPressEndereco(endereco)} />
                                        }
                                        data={this.state.searchResults} />
                                ) : (
                                        <FlatList
                                            contentContainerStyle={{ flexGrow: 1, backgroundColor: '#EEE', paddingHorizontal: 16, paddingTop: 8 }}
                                            style={{ flex: 1 }}
                                            keyExtractor={(item) => 'localsalvo' + item.id}
                                            renderItem={({ item }) =>
                                                <EnderecoSalvo 
                                                selectedLocation={selectedLocation} 
                                                onPress={() => this.setLocation(item)} 
                                                onPressOptions={()=> this.setState({enderecoEdit: item})}
                                                endereco={item}/>
                                            }
                                            data={this.state.enderecosSalvos} />
                                    )}
                            </View>
                        )
                    }
                </View>
            </Container>

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/34982 to track upstream
