### ISSUE TITLE
Terminal pops out in new window always

### ISSUE THREAD

**Issue by mrkarthi** [microsoft/vscode#84099]
Issue Type: <b>Bug</b>

Open any file in editor (say index.js).
Press CTRL + `
Terminal (Powershell / Command Prompt) is opened in a new window.
Upon closing the new window, the below error is displayed.
"The terminal process terminated with exit code: 3221225786"

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/73790, you need to disable legacy console mode in cmd.exe/conhost's properties.

**Comment by mrkarthi** [comment]
Resolved @Tyriar. Thanks!
