### ISSUE TITLE
Extension README content should be wrapped to 80-100 characters

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8409]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Extension README content should be wrapped to 80-100 characters to significantly improve readability/presentation (just like how this GitHub issue is wrapped).

This is bad:

![image](https://cloud.githubusercontent.com/assets/2193314/16426771/4a2acb58-3d1f-11e6-858a-b3cda2742d56.png)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/8251

**Comment by joaomoreno** [comment]
Bad build...

![image](https://cloud.githubusercontent.com/assets/22350/16563390/162e01ca-4202-11e6-9d8e-468645f70f7d.png)
