### ISSUE TITLE
"$(icon octioicon-git-pull-request)" in status bar instead of icon

### ISSUE THREAD

**Issue by binarycrusader** [microsoft/vscode#84090]
Issue Type: <b>Bug</b>

I see $(icon octicon-git-pull-request) etc. in my status bar instead of actual icons.  Guessing this is a problem with WAVE plugin?

Extension version: 2.0.191022002
VS Code version: Code - Insiders 1.40.0-insider (a14de79ac74f2e0e6566d3cc9410eeb7dc769cde, 2019-11-02T00:39:42.595Z)
OS version: Windows_NT x64 10.0.19511

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/83210

**Comment by misolori** [comment]
Do you have the Azure Repos extension installed?

**Comment by misolori** [comment]
Pretty sure this is the same issue as #83210, which is caused by the Azure Repos extensions and they already have a fix, see https://github.com/microsoft/azure-repos-vscode/issues/572.

**Comment by binarycrusader** [comment]
Yes, it is, and now it's fixed.  Thanks.
