### ISSUE TITLE
Characters overlaps emoji

### ISSUE THREAD

**Issue by kecoliva** [microsoft/vscode#84098]
- VSCode Version: 1.39.2
- OS Version: Version 1709 (OS Build 16299.1451)

Issue:
![Capture](https://user-images.githubusercontent.com/46006869/68357809-81ce9680-0151-11ea-8602-dbcf176359ce.PNG)

Steps to Reproduce:

1. Given WSL is installed, inside .bashrc `export PS1='🥝hello'.`
2. Open a bash terminal using the integrated terminal in vscode

Does this issue occur when all extensions are disabled?: Yes

**Comment by pradjeet** [comment]
why

**Comment by kecoliva** [comment]
@pradjeet what do you mean why?
