### ISSUE TITLE
Annoying bar

### ISSUE THREAD

**Issue by thedobbles** [Microsoft/vscode#841]
Although this is somewhat small, this really gets me; whenever I create a new file (that is the key here, this doesn't happen with ones previously created and opened using the "open with code" context menu) after passing line 25 there is a bar that is a different color overlayed on the line numbers, which as far as I can tell extends infinitely.

**Comment by alexandrudima** [comment]
@thedobbles Can you please add a screenshot, I'm not really sure what you mean

**Comment by thedobbles** [comment]
It usually starts around line 25, but in the images below it started on
line 36... It is an imgur ablum to show that this bug happens with more
then one theme.
http://imgur.com/a/fvCmG

**Comment by deathmood** [comment]
+1 also have this issue - it appears not only in light theme, but in Monokai and some others. To reproduce:
 - open any file
 - add 30 empty newlines to the end of the file (press Enter 30 times)

![image](https://cloud.githubusercontent.com/assets/2758540/11505788/d8fd041a-9854-11e5-8ad8-a7e27085ea02.png)

![image](https://cloud.githubusercontent.com/assets/2758540/11505803/e630acb8-9854-11e5-9d0f-deac98691600.png)

![image](https://cloud.githubusercontent.com/assets/2758540/11505817/f3bf2c9c-9854-11e5-81e4-cf0fe2e146a3.png)

**Comment by alexandrudima** [comment]
@thedobbles thank you for the extra details, I can now reproduce!

**Comment by deathmood** [comment]
ur welcome)) hope it'll be fixed soon!

**Comment by thedobbles** [comment]
It seems variable for me. Sometimes it only takes 25 lines, this morning it
took me 36. I'm glad I'm no the only one. It should also be noted that I
have been using self-created themes recently.

**Comment by thedobbles** [comment]
Oh oops, didn't see that it was fixed...

**Comment by alexandrudima** [comment]
@thedobbles if you want to workaround, the bar goes away if you cause an editor layout (aka resize the window or the editor) or if you reopen the file (e.g. by switching to another one, etc.). 

But I have delivered a fix for it.
