### ISSUE TITLE
Emmet doesn't work

### ISSUE THREAD

**Issue by TonyRak** [microsoft/vscode#84108]
Issue Type: <b>Bug</b>

when i edit a twig file, emmet doesn't work, I have already install extensions but it does'nt work

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.29GB free)|
|Process Argv|C:\xampp\htdocs\pulse-portal|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
mithril-emmet|Fal|0.7.3
php-debug|fel|1.13.0
twig-language|mbl|0.8.10
mssql|ms-|1.7.0
powershell|ms-|2019.11.0
twig|wha|1.0.2

</details>

**Comment by octref** [comment]
Set this setting.
```json
"emmet.includeLanguages": {
    "twig": "html"
}
```
