### ISSUE TITLE
Indentation guides hard to see in darker themes

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8410]
Testing #8232 on a MacBook Pro Retina display with brightness 2 steps below max while using a power adapter. This is my usual setting a regularly lit environments.

In the following themes the indentation guides should be changed to improve their visibility:

- [x] * Abyss
- [x] * High Contrast
- [x] * Monokai

In the following themes the indentation guides are subtle and easy to miss. However, changing those is optional.

- [x] * Dark (and Dark+)

**Comment by alexandrudima** [comment]
I am using the `invisibles` color from the theme, 100% the same as `renderWhitespace`. @aeschli owns the Dark and Dark+ themes (including the `invisibles` color):

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/themeService.ts#L385

**Comment by aeschli** [comment]
@bgashler1 Assigning to the UX team to decide on changes to the default colors.

**Comment by sandy081** [comment]
Some of the reported themes (Dark, Dark+, High Contrast) are owned by us. Others (Abyss, Monokai) are cloned and packaged along with VS Code. It means indirectly we own them and have to maintain them. So we should provide proper color for indent guides for all these themes.

@bgashler1 Can you please go through all our default packaged themes and come with a nice indentation guides color ?

**Note:** TM theme setting to use for identation guides is `guide`.

**Comment by bgashler1** [comment]
Reopening until PR is merged in

**Comment by sandy081** [comment]
Moving this to September milestone, since it is too late to make into August
