### ISSUE TITLE
Terminal goes blank when in Zen mode

### ISSUE THREAD

**Issue by Rocky49** [microsoft/vscode#84105]
when i opened my project in Zen mode at first its showing the terminal but after some time it goes blank also when i type on it, It shows me the character i typed except for the first character, Also when I opened new terminal it appears for sometime and wents blank again

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
