### ISSUE TITLE
Navigating C++ code may chage the modification date for a header

### ISSUE THREAD

**Issue by ibukanov** [microsoft/vscode#84114]
When opening a C++ file via Intelli Sense navigation, the file modification time may change. This is very annoying when working on a big C++ project when pressing F12 to go to the symbol definition results in timestamp update for a header resulting in lengthy re-compilation.

I noticed that this especially likely when Intelli Sense cannot decide which symbol to open and shows a list of headers to choose the definition from.

Note that I use "Tag parser" mode for Intelli Sense engine as the Default mode is not usable when working on Chromium sources.

Extension version: 0.26.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.1.8-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2364)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|8, 7, 4|
|Memory (System)|15.43GB (2.55GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexandrudima** [comment]
Please create an issue directly against https://github.com/microsoft/vscode-cpptools
