### ISSUE TITLE
API: text search provider only returns one result

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84110]
* checkout https://github.com/microsoft/vscode/pull/84109
* yarn web
* close editor
* search for "reference"

=> 🐛  only one result found even though there are multiple

Implementation:

https://github.com/microsoft/vscode/blob/61fa38ce473b15f4bd83831f3911099d90580e7d/extensions/vscode-api-tests/src/extension.ts#L832

**Comment by bpasero** [comment]
When editor is open:

![image](https://user-images.githubusercontent.com/900690/68368875-39a37a00-0139-11ea-9987-950ddc6b598a.png)

When closed:

![image](https://user-images.githubusercontent.com/900690/68368884-4031f180-0139-11ea-8516-6c9faefc9979.png)

**Comment by roblourens** [comment]
Seems like I can only find results on line 1. I think the provider is not returning correct results

**Comment by bpasero** [comment]
Works now after merging the PR.
