### ISSUE TITLE
Moving folded text using "Move Line Down", "Move Line Up" deletes text

### ISSUE THREAD

**Issue by gonsalu** [microsoft/vscode#84115]
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

Short video showing the issue: https://i.imgur.com/viKPLnN.mp4

1. Have the following text file contents:

```
test
    test2
test3
```

2. Fold on text _test_
3. Select whole folding on _test_
4. Move folded text down with Alt+Down
5. Move folded text back up with Alt+Up

Both _test2_ and _test3_ lines are unexpectedly deleted.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gonsalu** [comment]
I did check other open issues before creating this one, and none of them seem to cover the same bug.

**Comment by alexandrudima** [comment]
I can reproduce on Stable, but I can no longer reproduce on the latest Insiders. 

(I think the bug on Stable is that the folding model is not rendering an expand. The text is not deleted, it is just folded in a broken way...)

fyi @aeschli
