### ISSUE TITLE
PowerShell Syntax Highlighting Broken

### ISSUE THREAD

**Issue by SimonHounsell** [microsoft/vscode#84118]
Issue Type: <b>Bug</b>

Visual Studio Code's syntax highlighting for PowerShell appears to be broken for functions - the code blocks initially have syntax highlighting but then they turn grey after some time (typically within 20 seconds). Switching tabs temporarily fixes the issue but then within a few seconds, syntax highlighting is lost again. Copying a section of the code block to the clipboard preserves the syntax highlighting in the clipboard despite not seeing it in the source copied text in VSC - so this suggets it's a rendering issue as opposed to calculation issue. Single line cmdlets and variable declarations etc don't appear to have this problem. It appears to be related to any code blocks that VSC attempts to display references for. I've tried manually setting the language mode for the file and changed the colour theme, neither of which have helped.

Having said all that, I've sent the same source file to a colleague who has to all intents and purposes the same environment as me (same VSC version, same extension and version etc) and he's unable to re-create the issue.

![image](https://user-images.githubusercontent.com/37800313/68378831-b1c36d00-0144-11ea-9543-859ad6c4e3ca.png)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
gitlens|eam|10.1.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
dotnet-test-explorer|for|0.7.1
vscode-angular-html|gha|1.3.1
vscode-pull-request-github|Git|0.12.0
vscode-test-explorer|hbe|2.14.6
csharpextensions|jch|1.3.1
docomment|k--|0.1.8
auto-comment-blocks|kev|1.0.1
dotnet-core-essentials|Kis|0.0.8
typelens|kis|1.9.2
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
csharp|ms-|1.21.6
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1123
debugger-for-chrome|msj|4.12.1
vscode-css-peek|pra|3.0.2
angular-karma-test-explorer|raa|1.2.3
vscode-yaml|red|0.5.3
comment-ts|sal|0.9.11
vscode-scss-formatter|sib|1.4.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by alexr00** [comment]
Does this occur if you disable the powershell extension you have installed?

**Comment by SimonHounsell** [comment]
> Does this occur if you disable the powershell extension you have installed?

No it doesn't - disabling the extension resolves the issue. However obviously disabling it removes the 'find references' functionality and as mentioned previously, it feels like the issue is directly related to loading references, as highlighting works at first until references are attempted to be loaded - so I'm not sure if this is a fault of VSC or the PowerShell extension itself.

Again it's strange as my colleague who is running exactly the same version of VSC and the PS extension with the same source file, doesn't experience this issue.

**Comment by alexr00** [comment]
Find references doesn't do anything to syntax highlighting, but the powershell extension provides the language smarts to find the references and could be influencing syntax highlighting.

**Comment by rjmholt** [comment]
@alexr00 is there a recent VSCode feature that would automatically change highlighting based on context information (like references)?

The PowerShell extension doesn't touch highlighting; it relies on the [syntax grammar](https://github.com/powershell/editorsyntax) shipped with VSCode for that. But if there's a VSCode feature that rehighlights things based on a codelens, then maybe this is caused by that?

**Comment by alexr00** [comment]
I don't think there's anything in VS Code that would be re-highlighting anything based on references. I know that other language extensions do change highlighting based on things in the language server, so I assumed that PowerShell could be doing the same thing. If PowerShell _doesn't_ do any additional colorizing based on info only it knows, then I'll re-open this and we can investigate.

**Comment by rjmholt** [comment]
Looks like this might be an issue in the TypeLens extension. We'll redirect there,
