### ISSUE TITLE
Extension README license is so far from everything

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8411]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

The license is so lonely :cry: 

![image](https://cloud.githubusercontent.com/assets/2193314/16426860/a6d3f0b4-3d1f-11e6-912e-4ddef4dfc3d4.png)

**Comment by joaomoreno** [comment]
I know 😢
