### ISSUE TITLE
Image size that showed on the status bar is not being displayed

### ISSUE THREAD

**Issue by summersnow-wakabayashi** [microsoft/vscode#84111]
When you clicked on a picture, there used to displayed the image size on the status bar.
After the last update only the  image dimension is showing up.

![Image of Status_bar](https://cdn-ak.f.st-hatena.com/images/fotolife/m/minami_SC/20161012/20161012004734.png)

**Comment by negreirosleo** [comment]
Hello, may I take care of this issue?

**Comment by mjbvz** [comment]
Sure. Here's the code where the image preview computes the width and height: 
https://github.com/microsoft/vscode/blob/c53db9ba76c06c41b45c7765b143d1f925233f80/extensions/image-preview/media/main.js#L282

And where the value is set in the status bar:

https://github.com/microsoft/vscode/blob/c53db9ba76c06c41b45c7765b143d1f925233f80/extensions/image-preview/src/preview.ts#L93

You should see if there is an efficient way to get the binary size as well

**Comment by negreirosleo** [comment]
Nice, thanks for the attention :)
