### ISSUE TITLE
characters not align

### ISSUE THREAD

**Issue by ahdung** [microsoft/vscode#84119]
- VSCode Version: 1.39.2
- OS Version: Windows server 2008 R2 x64 sp1 chs (6.1.7601)

![微信截图_20191107174746](https://user-images.githubusercontent.com/12094247/68378856-cd039c00-0187-11ea-92e6-16792ad795e9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@ahdung Are you using `window.zoomLevel`? Can you please share a copy-paste friendly version of the code so I can try to reproduce? I see that the lines with `,1-(CASE WHEN` are not aligned, so I wonder if those are ASCII characters in there or the hyphen is some Unicode hyphen. Also, have you tried with another font like `Inconsolata` or with only `Consolas`?

**Comment by ahdung** [comment]
@alexandrudima Thank you.
- `window.zoomLevel` = `0`
- this is simplified texts (do not missing any char even space):
    ```
    ,sssssss when sss同
    ,ssssssssssssssss
    ```
    AND MAKE SURE LANGUAGE IS `SQL`
- font is `Consolas`
- screenshot:
  ![微信截图_20191107220234](https://user-images.githubusercontent.com/12094247/68395275-5cba4200-01aa-11ea-8e7f-17a8bc8f6507.png)

**Comment by ahdung** [comment]
and my another pc's vscode is 1.37.0,  same issue.

**Comment by alexandrudima** [comment]
@ahdung Have you installed some extensions that change our installation files CSS? Can you please try disabling all extensions? I see something is off in your file because the `when` text from your screenshot is not rendered "selected":
![image](https://user-images.githubusercontent.com/5047891/68396761-5dcf7d00-0172-11ea-8f38-2028cb8be01c.png)

**Comment by ahdung** [comment]
@alexandrudima 
- disabled all extensions and restart vscode, same issue
- I just selected last two `s`, select like your still have issue
- I saw your `同` is different with mine, can you set second font to `微软雅黑`? https://docs.microsoft.com/en-us/typography/font-list/microsoft-yahei

**Comment by alexandrudima** [comment]
@ahdung What does the title of VS Code say in `[`,`]`, the non-English part? Are you certain you have not installed an extension that modifies the on-disk CSS that shipped with VS Code? Can you please download VS Code again, close all running instances, and unzip it in a folder, just to rule out any tampering with the VS Code bits on disk. You can download the zip from here -- https://code.visualstudio.com/#alt-downloads

![image](https://user-images.githubusercontent.com/5047891/68399084-1cd96780-0176-11ea-9255-b78457775d20.png)

Here I am trying again with the fontFamily / fontSize settings you have indicated and it looks fine for me:

![image](https://user-images.githubusercontent.com/5047891/68399195-5316e700-0176-11ea-9f04-6b33ab5fc51d.png)

**Comment by ahdung** [comment]
@alexandrudima 
- `[管理员]` means `[Administrator]`
- this is the zip edition:
    ![image](https://user-images.githubusercontent.com/12094247/68400638-541a3980-01b3-11ea-9d3d-eccfdc432b9f.png)
    I don't know why it is chinese lang, why it already have extensions

**Comment by ahdung** [comment]
@alexandrudima I saw your UI really bigger, and the texts very smooth, like bottom-right, so did you zoomed the view by `zoomLevel` or mousewheel ?

**Comment by alexandrudima** [comment]
@ahdung I have a high DPI monitor and use it at 200%, so the zoom factor is 2, which does not produce any pixel grid related artifacts. Have you tried with another font, like Inconsolata ?

**Comment by ahdung** [comment]
@alexandrudima I tried `Courier New`, it's aligned, but problem still here, can you please test on a non-high DPI monitor?

**Comment by alexandrudima** [comment]
@ahdung I have tried on a non-high DPI monitor with Consolas, and the text aligns for me:
![image](https://user-images.githubusercontent.com/5047891/69221189-f86a8b80-0b76-11ea-9c12-e4c6c15f791d.png)

**Comment by ahdung** [comment]
@alexandrudima Thanks for not forgetting me, I miss you so much haha.
Don't forget `SQL` please. and I seem your UI still little bigger, are you sure `zoomLevel = 0`?

![image](https://user-images.githubusercontent.com/12094247/69225787-ffff5400-0bb9-11ea-9f83-b592b27824e3.png)

**Comment by ahdung** [comment]
I found that your "同" word has a problem, unlike `Microsoft yahei` font.

**Comment by alexandrudima** [comment]
@ahdung I can see that it is not aligned for you, but maybe it is not aligned exactly because you use the `Microsoft yahei` font? If monospacing is important for you, why don't you please try another (a single) font that does not have this problem? I am not sure how you would expect this to work. Most of the line is rendered with `Consolas`, and the last character is rendered with `Microsoft yahei`. Even if they are individually monospace fonts by themselves, there is no guarantee that combining them in a line will result in a cohesive monospace font. So my recommendation is to try to stick with a single font that is created by the font designer to be monospace, and not try to combine them, there is no guarantee the result will be monospace.

**Comment by ahdung** [comment]
@alexandrudima 
Yes, it's easy to change a font for me, but the problem is still there. In fact, even if I change the font or even use only the `consolas`, there is still same problem.

And, your explanation doesn't make sense:
- after deleting any characters, it's aligned
- non `SQL` documents can be aligned
  ![微信截图_20191121091848](https://user-images.githubusercontent.com/12094247/69293937-55cd0e00-0c45-11ea-8d1a-79dd0fa5aba6.png)


This problem is not very important to me personally, but is very important to the user feeling of vscode i think. This is about software quality, as an editor, even the basic functions of text alignment are not good, how can we expect others, right?

**Comment by ahdung** [comment]
This is the screenshot that was just capture in another computer. It has the same OS(win2k8R2 x64 sp1 chs). The vscode is just downloaded from the [official website](https://vscode.cdn.azure.cn/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip). There is no any extension. The only option change is to change the font size from `14 `to `13`.
![无标题](https://user-images.githubusercontent.com/12094247/69298089-d42aaf80-0c47-11ea-8757-990db127bc40.png)

**Comment by ahdung** [comment]
I found this is not about text not aligned, it's about the selection block not aligned, so maybe problem is about drawing.

**Comment by alexdima** [comment]
@ahdung I am sorry for the delayed response. I now understand what is different between those two lines:
- the font is detected as monospace
- the second line contains only ASCII characters and we create a `FastRenderedViewLine`. For such lines, we do not go and ask the browser for character positions. We simply take the width of one character and multiply by the number of characters and thus determine the position.
- the first line contains a non-ASCII character. For such lines, we go and ask the browser for character positions.

The two methods of determining the character position (one by multiplying character count times character width and the other by asking the browser about the character position) do not give the same exact result for this particular font family / font size.

To workaround, you can use `"editor.disableMonospaceOptimizations": true` in your settings file. This setting is an "internal" one, so it will render greyed out, but it will take effect.

I agree that this is a real issue, but I believe it is acceptable given the performance benefits of using the `FastRenderedViewLine`, so in the end I would just like to ask that you use `"editor.disableMonospaceOptimizations": true`.

Thank you!

**Comment by ahdung** [comment]
@alexdima Thank you very much, but:
![image](https://user-images.githubusercontent.com/12094247/76404948-57703c80-63c2-11ea-8072-9eca5e762d93.png)

I tried restart vscode.
I think your explanation can't explain why just `sql` occurred.

**Comment by alexdima** [comment]
I am sorry, I cannot reproduce this on any Windows 10 machine, I have tried on 2 different machines and in one VM.

Does `"editor.disableLayerHinting": true` make any difference?

**Comment by ahdung** [comment]
@alexdima I can only say that I don't see any difference. Thank you.
