### ISSUE TITLE
vscode's extensions (on my ubuntun18.04) can't work

### ISSUE THREAD

**Issue by sundongwei** [microsoft/vscode#84112]
Issue Type: <b>Feature Request</b>

I installed a lot of extensions on my vscode ,but they can not work,even auto-bracket can not use , so I have to type bracket "(" input something then type ")", even the brackets  have not a color match function.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

**Comment by alexandrudima** [comment]
@sundongwei The auto-insertion of a closing bracket `)` after an opening bracket `(` is a feature that is coming from the core VS Code (not from an extension). Can you please check your `settings.json` file and see, perhaps you have disabled the feature using `editor.autoClosing`-settings.
