### ISSUE TITLE
Compact option don't hide menu bar in GTK.

### ISSUE THREAD

**Issue by MartinPL** [microsoft/vscode#84128]
Changing Menu Bar Visiblity to compact don't hide menu in GTK. Hidden option work fine.
(https://webm.red/view/8wK9.webm).

Could just hidden option feature can be added to compact?

- VSCode Version: 1.39.2 / 1.40.0-insider 
- OS Version: Arch Linux

Steps to Reproduce:

1. Open VSC on Linux
2. Change "Window: Menu Bar Visibility" to compact
3. No profit 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
![image](https://user-images.githubusercontent.com/6561887/68422371-e808e880-0154-11ea-8f12-8fcb005a5400.png)

**Comment by MartinPL** [comment]
For me it's broken design.
