### ISSUE TITLE
Quick open: Icon vertical alignment is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84124]
Before:

![image](https://user-images.githubusercontent.com/22350/68382512-1d610680-0154-11ea-8998-97944bdd118a.png)

Now: 

![image](https://user-images.githubusercontent.com/22350/68382529-281b9b80-0154-11ea-9eb9-223f70c2a0d3.png)

I tried to bisect and found the culprit... but I failed miserably. This got broken somewhere between 86405ea23e3937316009fc27c9361deee66ffbf5 and 43deb16c6926224ddafd3cb4f6fb6dae4abafe39

cc @chrmarti

**Comment by misolori** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/35271042/68416596-9e66d080-0149-11ea-89fb-272714be8e67.png)


Also fixed configure icons on the right:

![image](https://user-images.githubusercontent.com/35271042/68416571-9313a500-0149-11ea-97c9-f409143042c1.png)
