### ISSUE TITLE
Freezing on search mode selecting

### ISSUE THREAD

**Issue by bucherok** [microsoft/vscode#84129]
Issue Type: <b>Performance Issue</b>

Perform global search(sidebar) by some string, for ex. 'Logger', after getting results click "Match case" or "Whole word" option, after that all freeze, including operation system. No touch pad or keyboard actions getting response. This stops after search with selected params completed.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 15, 9|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.2.3
gitlens|eam|10.1.2
vsc-material-theme|Equ|30.0.0
docthis|joe|0.7.1
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.2
copy-json-path|nid|0.0.5
material-icon-theme|PKi|3.9.1

</details>

**Comment by bucherok** [comment]
Still reproducing clearly: change global search mode while in search progress.
Same on teammates VS code same version.

**Comment by roblourens** [comment]
- How many results are there? 
- Can you check whether there is some process using a lot of CPU while this happens, and which process exactly?
- If you leave it for awhile, does it start responding again?

**Comment by bucherok** [comment]
Hi @roblourens 
 - Not depends on potential result count, even for 10 results
 - Unfortunately cant, system freezes, mouse pointer stops to react on touchpad inputs, no actions allowed
 - For some time 2-5 mins it return with result as normal

Teammate, who has VSСode Insiders catch a "Page is not responding" or some like this popup.

**Comment by roblourens** [comment]
Can you share the folder/repo that you are searching, so I can try?

**Comment by bucherok** [comment]
@roblourens unfortunatelly i can't share
The problem goes to very serious issue.
 I've updated to Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

And now search freezes OS until it's restarted.
