### ISSUE TITLE
Conpty: Terminal rendering very slow with huge output

### ISSUE THREAD

**Issue by GoaLitiuM** [microsoft/vscode#84137]
Conpty renders terminal window almost unusable when a compiler suddenly emits hundreds of hundreds of error lines.

For example, running `tree /F` in my dev folder took this long to finish:
- ~12sec in Command Prompt
- ~11sec in VSCode without Conpty
- ~65sec in VSCode with Conpty

Renderer type has minor difference to the execution speed where DOM being slightly slower, but these were observed with Canvas rendering enabled.

Steps to Reproduce:
1. Enable Conpty.
2. Run a command which produces lots of lines (like `tree C: /F`)
3. Repeat without Conpty and observe how much longer it takes to finish the command.

- VSCode Version: 1.39.2
- OS Version: Windows 10 build 18362

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Speed should improve somewhat in 1.40 but the root cause of this is https://github.com/microsoft/vscode/issues/74620

/duplicate

**Comment by GoaLitiuM** [comment]
Confirmed, 1.40 has similar performance between those two modes. Thanks.
