### ISSUE TITLE
Move Show tabs to view panel

### ISSUE THREAD

**Issue by gonardfreeman** [microsoft/vscode#84132]
Hi!
Can you please move setting: `Workbench->Editor->Show Tabs` to `View panel`

![Screenshot 2019-11-07 at 15 29 02](https://user-images.githubusercontent.com/16113714/68393007-b94e3a80-0173-11ea-994f-4c3386098353.png)
![Screenshot 2019-11-07 at 15 28 35](https://user-images.githubusercontent.com/16113714/68393013-ba7f6780-0173-11ea-8c60-8366f6ccbdae.png)

**Comment by bpasero** [comment]
@gonardfreeman not convinced, there is a command in the command palette to quickly switch and a keybinding, isn't that enough?

![image](https://user-images.githubusercontent.com/900690/68399616-f536cf00-0176-11ea-8f6c-eb738d935882.png)
