### ISSUE TITLE
On macOS, When vscode is opened from sudo mode, the input method cannot be switched to non-English

### ISSUE THREAD

**Issue by zhanzhenzhen** [microsoft/vscode#84143]
Issue Type: <b>Bug</b>

```bash
sudo -i
code .
```

In the opened window, try to switch IME to non-English. You'll find you can't switch IME.

This issue exists not only when you open as root, but when you open as any user other than the current user.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.56GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|17%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1

</details>

**Comment by alexandrudima** [comment]
This is a problem with the mac OS that has no solution. It is not clear if this problem was ever reported to Apple . Please see https://github.com/microsoft/vscode/issues/66578#issuecomment-512784154
