### ISSUE TITLE
Integrated terminal resets scroll position to top when emacs is closed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84145]
Issue Type: <b>Bug</b>

Reopening of #62329

**steps**
1. In the intergrated terminal.
1. Run a command that generates more than one screen of content: `ls -alF /dev/`
1. Scroll to bottom
1. Now run emacs and then close emacs using ctrl+c ctrl+x

**Bug**
Terminal scroll position is sometimes reset to top of buffer

![Nov-07-2019 10-24-45](https://user-images.githubusercontent.com/12821956/68416232-ef29f980-0148-11ea-9985-05e2d679f6b9.gif)

VS Code version: Code - Insiders 1.40.0-insider (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T16:56:25.487Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_1614218|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by Tyriar** [comment]
Can't repro 🙁 some things that might help diagnose:

- Debug VS Code to see what's getting hitting hit. Calls to this when exiting would be particularly interesting https://github.com/xtermjs/xterm.js/blob/dd4eb7bdecf1c13748c27de65c7bc32d95e3d30e/src/Terminal.ts#L1027
- Try repro in the xterm.js demo
- Enable escape sequence logging and capture the entering emacs logs and exit emacs logs for both the case where it's fine and the case where the scroll is off.

**Comment by mjbvz** [comment]
Seems to happen most reliably when I run emacs as the git editor, but as the screenshot shows it can also happen for normal runs.

From debugging:

**Normal case**
- `scroll` called with `undefined`
- `_onScroll` called twice with `_ignoreNextScrollEvent == true`
- `scrollLines` not called by `_onScroll`

**Bugged case**
- `scroll` called with `undefined`
- `_onScroll` called with `_ignoreNextScrollEvent == true`
- `_onScroll` called again `_ignoreNextScrollEvent == false`
- `scrollLines` called by `_onScroll` with `-3145`

**Comment by Tyriar** [comment]
> _onScroll called again _ignoreNextScrollEvent == false
> scrollLines called by _onScroll with -3145

That's definitely the problem, could you get the stacktrace for both of those?

**Comment by mjbvz** [comment]
Stacks look the same. Here `_onScroll` called with `_ignoreNextScrollEvent === true
![Screen Shot 2019-11-08 at 3 07 03 PM](https://user-images.githubusercontent.com/12821956/68516644-72c31380-0239-11ea-82d3-7b45f28e4543.png)
`:

And with `_ignoreNextScrollEvent === false`:

![Screen Shot 2019-11-08 at 3 07 38 PM](https://user-images.githubusercontent.com/12821956/68516690-8e2e1e80-0239-11ea-9c6c-15e2136a6e73.png)


It seems like a timing issue. Between the call to `_innerRefresh` which sets `_ignoreNextScrollEvent  = true` and `_scroll`, someone else is setting `_ignoreNextScrollEvent = false`. Here's one possible call sequences I see opening emacs in the bad case (true/false is the value of `_ignoreNextScrollEvent `):

![Screen Shot 2019-11-08 at 3 20 05 PM](https://user-images.githubusercontent.com/12821956/68517166-4a3c1900-023b-11ea-9171-5c6908d36a65.png)

And from the good case:

![Screen Shot 2019-11-08 at 3 21 23 PM](https://user-images.githubusercontent.com/12821956/68517207-75bf0380-023b-11ea-9274-473994675e17.png)


For what it's worth, I also currently see this more often in insiders (vs OSS)

**Comment by Yanpas** [comment]
I don't use emacs or something, just run some tests which output a lot of stuff, then hide and unhide terminal - after a couple of moments I am on top of terminal. Scrolling it with a scrollbar to the bottom doesn't bring me to the last line, so I press enter

**Comment by rianquinn** [comment]
Yeah, I have to press enter to get to the bottom of the terminal. I can confirm that this is an issue with Linux and Windows (I see this on both), so it doesn't appear to be specific to any OS. This also happens with both native and remote development, so it is not specific to remote development (which I use a lot). For me, it starts happening after about an hour of use, and then becomes really frequent (almost every time I open the terminal). Its causing me to form a habitual response to just always press enter when I open the terminal :frowning_face:

**Comment by Tyriar** [comment]
Another repro: https://github.com/microsoft/vscode/issues/87477

**Comment by Olovan** [comment]
The #87477 case seems to be a symptom of the TerminalPanel onDidChangeVisibility callback not triggering a setVisible call on the active terminal instance.
 
https://github.com/microsoft/vscode/blob/df48af1684713cb61c1efbe05a73d1494e1d294a/src/vs/workbench/contrib/terminal/browser/terminalPanel.ts#L98

The code to re-sync the the Terminal viewport and scrollbar is in the TerminalInstance setVisible method.

https://github.com/microsoft/vscode/blob/df48af1684713cb61c1efbe05a73d1494e1d294a/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L904

I'm not sure if it's the same issue as the Emacs variation of the bug.

**Comment by jcsagrero** [comment]
I'm also having this issue. When I toggle open the terminal on WSL and PowerShell, the terminal is scrolled to the top, even with all extensions disabled. Focusing on the terminal doesn't have this behavior.

**Comment by jcsagrero** [comment]
Update: for anyone looking for a temporary fix, I used the extension "multi-command" and set up a shortcut to scroll the terminal to the bottom when opening it. Since I needed to first focus the terminal after opening it, I had to set up two cases, toggling when it's closed and toggling when it's already open: 

"multiCommand.commands": [
        {
            "command": "multiCommand.toggleTermClosed",
            "sequence": [
                "workbench.action.terminal.toggleTerminal",
                "workbench.action.terminal.focus",                
                "workbench.action.terminal.scrollToBottom",
                
            ]
        },
        {
            "command": "multiCommand.toggleTermOpen",
            "sequence": [
                "workbench.action.terminal.toggleTerminal",
            ]
        }
    ]

**Comment by aeschli** [comment]
verified with steps from https://github.com/microsoft/vscode/issues/87477
