### ISSUE TITLE
Extension buttons are inconsistent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8414]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Viewlet:

![image](https://cloud.githubusercontent.com/assets/2193314/16427126/c923db60-3d20-11e6-8247-d1faa42276de.png)

Preview (bolded):

![image](https://cloud.githubusercontent.com/assets/2193314/16427150/ead1e892-3d20-11e6-9326-363486a1b228.png)
![image](https://cloud.githubusercontent.com/assets/2193314/16427162/f4c7d406-3d20-11e6-872e-8e841b84303c.png)

The size/spacing is also inconsistent:

![image](https://cloud.githubusercontent.com/assets/2193314/16427263/58c15b26-3d21-11e6-927f-7bfd04dbc7c6.png)

**Comment by joaomoreno** [comment]
This was on purpose. They are meant to be _bigger_ in the preview.
