### ISSUE TITLE
Create-React-App Issue

### ISSUE THREAD

**Issue by ipapoutsidis** [microsoft/vscode#84146]
Hello, everyone, I am trying to run my react app and I have this error on the terminal. I try to find a solution to throw the internet but unsuccessful. 
Can anyone help me?

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/ipapoutsidis/Desktop/document/developer/development/production/test/app/public/favicon.ico ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/chokidar/lib/nodefs-handler.js:262:21)
    at FSWatcher.<anonymous> (/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/chokidar/lib/nodefs-handler.js:495:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ipapoutsidis/.npm/_logs/2019-11-07T18_15_23_979Z-debug.log

And this is a debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.12.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle app@0.1.0~prestart: app@0.1.0
6 info lifecycle app@0.1.0~start: app@0.1.0
7 verbose lifecycle app@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle app@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ipapoutsidis/Desktop/document/developer/development/production/test/app/node_modules/.bin:/usr/local/lib/nodejs/node-v10.16.3-linux-x64/bin:/usr/local/lib/nodejs/node-v10.16.3-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle app@0.1.0~start: CWD: /home/ipapoutsidis/Desktop/document/developer/development/production/test/app
10 silly lifecycle app@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle app@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle app@0.1.0~start: Failed to exec start script
13 verbose stack Error: app@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid app@0.1.0
15 verbose cwd /home/ipapoutsidis/Desktop/document/developer/development/production/test/app
16 verbose Linux 4.15.0-66-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.10.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error app@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the app@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thank in advance!

**Comment by ArsalanWahid** [comment]
can you share the output of this file , im getting the same issue

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ipapoutsidis/.npm/_logs/2019-11-07T18_15_23_979Z-debug.log

**Comment by ipapoutsidis** [comment]
**ArsalanWahid** Thank you for your response.
The issue was that the create-react-app has changed the installation process. nothing more.
The solution is below:
https://create-react-app.dev/docs/getting-started/
