### ISSUE TITLE
Stars can be pushed off the right side of the extension viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8415]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

I think this happened after resizing the viewlet:

![image](https://cloud.githubusercontent.com/assets/2193314/16427353/d0c105b8-3d21-11e6-971a-69cc3891b48c.png)
![image](https://cloud.githubusercontent.com/assets/2193314/16427376/e6409eee-3d21-11e6-8b9d-a6528aa27080.png)

**Comment by bgashler1** [comment]
Just noticed this as well.

I'm also missing how many ratings an extension received (what if it's like 5 stars but only 1 person rated it).  For products on Amazon's website, they show stars and then the number of ratings next to it.

**Comment by joaomoreno** [comment]
It there any suggestion of what should happen instead?

If the whole ratings widget becomes unbreakable, you'd easily miss ratings for long titles.

If we decide to cut down on the extension's name, the ratings would be all you see.

**Comment by lafe** [comment]
Just wanted to add the same issue myself :) 
I would propose to use a responsive approach. If there is enough space leave it as it is (maybe truncate the title if necessary; a 200 character extension name might always cause issues). If there is not enough space move the ratings (and maybe the downloads) to the next line. This would cause bigger items but you get all information.

**Comment by Tyriar** [comment]
Making everything more squished up just like a responsive website is the way to go imo, \[:star::star::star::star::star:\] could become \[5:star:\] when space is constrainted. Same goes for changing the install text to an icon at the same breakpoint.

**Comment by joaomoreno** [comment]
This was already pushed yesterday:

![image](https://cloud.githubusercontent.com/assets/22350/16758847/66394f9a-4814-11e6-9ee4-7433c9ebee23.png)

@Tyriar It's like you're a mind reader. 👍

**Comment by Tyriar** [comment]
Looks good! :sparkles:
