### ISSUE TITLE
Webview steals focus?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#84156]
Issue Type: <b>Bug</b>

1. Open markdown preview
1. Click branch icon in status bar
1. Click (with mouse) `Create new branch...`
1. The input is not focused

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by hadzhiyski** [comment]
Hello,
I will take this one

**Comment by Wowol** [comment]
I would like to have a go at this.

**Comment by mjbvz** [comment]
I'm not able to reproduce this with VS Code insiders following the instructions so hopefully this has already been fixed

Tested on Windows and MacOS
