### ISSUE TITLE
Add Preference to Set Focus on Newly Opened Editor

### ISSUE THREAD

**Issue by claytoncarney** [microsoft/vscode#84158]
Issue Type: <b>Feature Request</b>

Currently, when a file is clicked in the Explorer, a new editor tab is opened, but the focus remains on the Explorer.

I find this disruptive and unlike other text editors. Usually opening a file also sets focus to the newly opened file so one can begin editing.

Please consider adding a Preference Setting to change the behavior so that an editor receives focus when it is opened.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
Please double click to move focus.
However this is a fair feature request, thus leaving it open for now.

**Comment by brgrz** [comment]
absolutely crucial feature

**Comment by claytoncarney** [comment]
Just a note. I find it is not possible to double click as suggested. The first click opens the file, adding it to the Open Editors list, which scrolls down the list, The second click then opens the previous file in the list. The only way to double click on a file is after it is already open; then yes it receives focus. However, that requires a total of three clicks and a mouse move.
