### ISSUE TITLE
QuickPick item list does not initially show first item 

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode#84150]
Quickpick item list does not initially show the first item only after an InputBox is displayed.
If a QuickPick is displayed right after an InputBox is displayed, the QuickPick's list of items is scrolled so that the first item is not initially visible.

I have a small VS Code extension that reproduces the problem: https://github.com/xorye/quickPick_scroll_problem

The extension contributes two commands:
Quick Pick -> displays a quick pick
Quick Input -> displays an input box

This problem seems to happen only if there are a lot of Quick Pick items (about 25).

For the small extension I linked above, this problem only happens in VS Code Insiders, not with regular VS Code.

However, if this line is removed: https://github.com/xorye/quickPick_scroll_problem/blob/0afee153556d6f1a89d09b2adc128eb0124dfebc/src/showQuickPick.ts#L11
this problem appears in both Insiders and regular VS Code.

Steps to Reproduce:

1. Clone https://github.com/xorye/quickPick_scroll_problem
2. Run the extension
3. Call the `Quick Pick` command in the command palette
4. Either click one of the options, or hit escape
5. Call the `Quick Input` command
6. Either click one of the options, or hit escape
7. Call the `Quick Pick` command in the command palette
8. The first item is not visible

Here is a gif:
![gif reproducing the issue](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/quickpick.gif?token=AE3CR5JOHX6YF3SXEF2EQE25ZWLOK)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gjsjohnmurray** [comment]
Is this #84125 ?

**Comment by xorye** [comment]
@gjsjohnmurray yes, that seems like the same problem. Clicking `Create new branch...` opens an input box. Closing it and then calling `Git: Checkout to...` opens the quick pick with the wrong scroll position
