### ISSUE TITLE
VS Code hang updating from 1.39.2 to 1.40.0 on macOS

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#84155]
- VSCode Version: 1.40.0
- OS Version: macOS 10.14.6

**Steps to Reproduce:**
1. VS code updated to 1.40.0 (helper tool admin login prompt)
2. Restart to Update

After clicking update, application window closed but application hung with `not responding`. After force quit and reopening , gave a scary error message "your installation is corrupted." asking to reinstall, and UI features such as syntax highlighting and side pane did not work. 
After restarting several times, VS Code seems to be normal at version 1.40.0.

Does this issue occur when all extensions are disabled?: N/A

**Comment by cpreston321** [comment]
@wesinator Had the same issue. Had to redownload the latest version from Microsoft. Then delete the older version now it's works. That's if you want the latest update 💯 

Have a good one,
CP

**Comment by wesinator** [comment]
> @wesinator Had the same issue. Had to redownload the latest version from Microsoft. Then delete the older version now it's works. That's if you want the latest update 💯
> 
> Have a good one,
> -C

Thanks Christian, It did update to the latest one after restarting 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/5124946/68425989-2d3d1280-0175-11ea-8123-f6f5e4f00277.png">

**Comment by joaomoreno** [comment]
> After restarting several times, VS Code seems to be normal at version 1.40.0.

Glad to know you're OK now. Thanks.

**Comment by wesinator** [comment]
> > After restarting several times, VS Code seems to be normal at version 1.40.0.
> 
> Glad to know you're OK now. Thanks.

you're not going to try to reproduce this and see what's going on ?
definitely looked really bad, and there could still be issues behind the scenes.
