### ISSUE TITLE
Missing property in LSP completionItem/resolve request

### ISSUE THREAD

**Issue by MrTrillian** [microsoft/vscode#84167]
Issue Type: <b>Bug</b>

When VSCode connects to the VS C++ language server and include completion is used, icons in the completion list change as the user uses the down arrow to change the selection.

![image](https://user-images.githubusercontent.com/2314287/68434003-bef45200-016c-11ea-87e3-384c3d2acc72.png)

The problem is that, when VSCode sends the LSP `completionItem/resolve` request, it doesn't fill in the `kind` property with the value that was originally returned on the `CompletionItem` by `textDocument/completion`. The C++ language server returns the `CompletionItem` without modifying that property, and VSCode then changes the icon because the resulting `kind` property doesn't match the original value.

This same issue as https://github.com/microsoft/vscode-languageserver-node/issues/438 , which was closed for unclear reasons.

VS Code version: Code - Insiders 1.40.0-insider (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T16:58:49.777Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|3.1.6
chat|kar|0.29.0
cmake-tools|ms-|1.2.1
cpptools|ms-|0.26.1
csharp|ms-|1.21.6
powershell|ms-|2019.11.0
vsliveshare|ms-|1.0.1123
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
team|ms-|1.161.0
partial-diff|ryu|1.4.0

</details>

**Comment by MrTrillian** [comment]
@dbaeumer , you were assigned the original issue. Do you know why it was closed?

**Comment by dbaeumer** [comment]
@MrTrillian this should work on the latest next version of the library. It is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/codeConverter.ts#L467

Which version of the client libs are you using ?

**Comment by MrTrillian** [comment]
@dbaeumer How would I know which version of the client libs I'm using? I only updated VSCode to the latest insider build before filing this issue. If it'll be fixed soon, I can verify my scenario afterwards

**Comment by dbaeumer** [comment]
@MrTrillian every extension manages its own version of the client libs. VS Code itself doesn't ship with a LSP client to avoid version problems. Usually your extension's package.json has an entry like this: 

```
	"dependencies": {
		"vscode-languageclient": "6.0.0-next.5"
	}
```

**Comment by MrTrillian** [comment]
@dbaeumer I'm confused, what extension? I guess I'm using VSCode's Live Share extension version 1.0.1123 in VS code, and my LSP server is the Visual C++ one in Visual Studio. It's not clear how to find VSCode Live Share's `package.json`, I can't find that in my VSCode installation directory.

**Comment by dbaeumer** [comment]
@MrTrillian now I see. I missed the Live Share setup. I am pretty sure LiveShare for VS Code pulls in the VS Code client libraries. Since Live Share is an extension is lives in our ${home}\.vscode\extensions. In my installation their package.json has the following entry:

```
"vscode-languageclient": "^4.4.2",
``` 

which is a very old version. The latest is 5.3.1 and the newest next is 6.0.0-next.4. So the problem might go away if at least upgrading to the latest library version.

**Comment by dbaeumer** [comment]
There is nothing VS Code or the LSP libraries can do about this. I will close the issue since it is something LiveShare has to handle correctly.
