### ISSUE TITLE
Terminal not working over remote

### ISSUE THREAD

**Issue by oldjacket** [microsoft/vscode#84163]
Issue Type: <b>Bug</b>

after opening folder in remote trying to open terminal results in error e terminal shell CWD "path" does not exist

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.15.0-1047-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: box.dev.devoted.com|
|OS|Linux x64 4.15.0-1047-aws|
|CPUs|AMD EPYC 7571 (64 x 2430)|
|Memory (System)|499.47GB (66.56GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
vscode-icons|vsc|9.5.0
mssql|ms-|1.7.0

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json?

/needsMoreInfo
