### ISSUE TITLE
Old Windows Terminal Problem(s)

### ISSUE THREAD

**Issue by bencecile** [microsoft/vscode#84161]
Issue Type: <b>Bug</b>

I should start off with saying that these are old problems that I've had before with VS code and have come back to haunt me.

1. There is extra white space whenever I open a new terminal. The terminal is scrolled to the bottom such that I can't see anything. Oh ya, and the prompt disappears until I hit enter. This only appears to happen on the first terminal tab, when it pops it up for the first time (if I make another tab while it's already open, this doesn't happen).

2. Whenever the terminal can scroll and I minimize it, when it comes back up with the scroll bar at the top of the terminal. However, it does show the content at the bottom, where it should be. Any mouse wheel scrolling in this state pages the terminal up to where the scroll bar says in the terminal. Resizing the terminal right after it's come back up in the goofy state does reset the scroll bar to the correct place.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.0
matlab|Gim|1.4.0
gc-excelviewer|Gra|2.1.32
latex-workshop|Jam|8.3.1
svg|joc|1.0.5
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
powershell|ms-|2019.11.0
vetur|oct|0.22.6
shader|sle|1.1.4
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
The blank initial terminal is a bug in Windows and you need to upgrade to fix it: https://github.com/Microsoft/vscode/issues/57803

I'm not so sure about the second, could you put a gif together showing the problem with some more detailed steps?

/needsMoreInfo

**Comment by bencecile** [comment]
Ok, the windows update worked to fix the first issue (I didn't realize that it didn't get auto-updated).

A gif for the second issue: https://imgur.com/a/Xk2FCZO
Let me know if you need anything else

**Comment by rianquinn** [comment]
I just opened this:
https://github.com/microsoft/vscode/issues/84379

It's the same problem here (#2 that is). Really... really annoying.

**Comment by rianquinn** [comment]
Restarting VSCode does _not_ seem to solve the issue.

**Comment by ratatoeey** [comment]
its safer to use github for images and gifs. also ,https://imgur.com loads really slow.

----

regards ratatoeey

**Comment by Tyriar** [comment]
Scroll issue is captured in https://github.com/microsoft/vscode/issues/84145
