### ISSUE TITLE
Get the workspace folder of the current file

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode#84162]
I have a multi folder workspace.
I have in launch.json with `"cwd": "${workspaceFolder}",`.
However when I press f5 to start debugging, it often takes the workspaceFolder of another workspace.

There should be something like `"${workspaceFolderOfCurrentFile}".
Using mutli folder workspaces is still such a pain due to lack of flexibility / configuration.

**Comment by weinand** [comment]
Since the "launch.json" always lives in a specific workspace folder, `${workspaceFolder}` is tied to that folder.

**Comment by clankill3r** [comment]
To clarify a bit more, I only have one launch.json.
It's setup like this:

```
/ws
   /.vscode
        launch.json
/proj_a
   /scr
/proj_b
   /scr
/proj_c
   /scr
/proj_d
   /scr
```

Where /ws and /proj_* are all folders added to create the multi folder workspace.
But `${workspaceFolder}` always is `/ws`

**Comment by weinand** [comment]
As I said above: the "launch.json" lives in the specific workspace folder "/ws", so `${workspaceFolder}` is expected to have the value "/ws".

To refer to other folders, you can use something like this: `${workspaceFolder:proj_a}`.

**Comment by clankill3r** [comment]
This is really painfull, therefor something like `workspaceFolderOfCurrentFile` would be really great.

My workaround:

Right now I made a agent for java that runs `premain` before the actually `main` runs.
I pass `"${file}"` to the arguments of the agent. Based on that String I strip it down to remove everything after and including `/src`. Then I know the root of the workspace of the current file and I can set the system property `user.dir` so java behaves correct. It works but it is to complex to my liking.

**Comment by weinand** [comment]
Please correct me if the following does not describe your use case:

You have a debug configuration in `/ws/.vscode/launch.json` that uses `${file}` and you want to be able to use this configuration on all files in your multi-root setup. And in order to establish the correct working directory for your debuggee you need a way to derive the workspace folder path from `${file}`.

**Comment by clankill3r** [comment]
Yes that is correct.

**Comment by weinand** [comment]
Proposal:
let's introduce a new variable `fileWorkspaceFolder`

Alternative name: `workspaceFolderOfFile`

For comparison here is the list of other variables: https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables-examples

@isidorn  @alexr00 what do you think?

**Comment by alexr00** [comment]
This makes sense to me. I prefer the name `fileWorkspaceFolder`.

**Comment by isidorn** [comment]
Makes sense. I prefer the `workspaceFolderOfFile` since it is a bit clearer what it is when you read it.
Though both work for me :)

**Comment by weinand** [comment]
@isidorn I agree, `workspaceFolderOfFile` is clearer, but we are not using the "x-Of-y" pattern anywhere else, so I will go with the `fileWorkspaceFolder`.

**Comment by isidorn** [comment]
Works for me.

**Comment by weinand** [comment]
verification steps:

- use a multifolder workspace
- add the following launch config to your user settings or workspace settings:
  ```js
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "WorkspaceFolder for editor",
                "runtimeArgs": [
                    "-e",
                    "console.log('fileWorkspaceFolder: ' + process.argv[1])"
                ],
                "args": [
                    "${fileWorkspaceFolder}",
                ],
            }
        ]
    },
  ```
- open the debug viewlet
- in the debug drop down select the "WorkspaceFolder for editor" debug config
- open a random workspace file in the editor
- press 'F5'
  you should see a "fileWorkspaceFolder: workspace folder path" in the debug console
- make sure that the path is the correct workspace folder of the file
 
Try this with different files from different workspace folders.

**Comment by clankill3r** [comment]
@github-actions  (not sure if I should at a bot...), @weinand 
I'm in the process of reinstalling my OS, I will test a.s.a.p.

**Comment by weinand** [comment]
@clankill3r great, thanks (from a human, not a bot..)
