### ISSUE TITLE
VSC doesn't execute - error given on cmd line

### ISSUE THREAD

**Issue by scottfurry** [microsoft/vscode#84166]
- VSCode Version: 1.40.0
- OS Version: 4.19.67_p2-r2 (Funtoo)

Steps to Reproduce:

1. Update VSC to latest version
2. Attempt to open from menu item

Does this issue occur when all extensions are disabled?: Yes

Error message produced when VSC is executed from the command line:
```
[17750:1107/151441.923171:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that [install path]/code/chrome-sandbox is owned by root and has mode 4755.
```

Newest and latest release (tar.gz, RPM, and DEB) has the permissions of `chrome-sandbox` set to 0755 (file owned by root, rwx for user, r+x for group and other). Manual intervention is required to set the correct, and now newly required, permissions VSC expects.

Change doesn't appear described or mentioned in change notes.

**Comment by alexandrudima** [comment]
@bpasero @deepak1556 @Tyriar @joaomoreno Sorry I don't know who to assign if this is a problem with the build or with Electron itself... Can you please investigate...

**Comment by scottfurry** [comment]
For *nix users - `sudo chmod 4755 [path to install]/code/chrome-sandbox`

**Comment by deepak1556** [comment]
@scottfurry sorry about that, yup this is due to new sandbox binary shipped with the electron update https://github.com/electron/electron/issues/17972. This should have been updated in the release notes.

@Tyriar @joaomoreno can we set the permission of `chrome-sandbox` in the packaged apps to 4755 if those packages can preserve the permissions ?

**Comment by scottfurry** [comment]
@deepak1556 - reading through the commentary on the bug you referenced is <i>rather scary</i>.
This has been on-going for almost 8 months? Wow...

Okay. This has a workaround. Looks like install/distribution will have to force/fix permissions in the interim. I can work with that. I'll make a note to my self to circle back on the next point release(or sooner) to double check this problem still persists.

**Comment by Tyriar** [comment]
@deepak1556 we create all the packages here: https://github.com/microsoft/vscode/blob/master/build/gulpfile.vscode.linux.js and tarball here:

https://github.com/microsoft/vscode/blob/245b4dad4579b07b01f18e7d6b9895b49c6af3a9/build/azure-pipelines/linux/publish.sh#L15

Pretty sure we don't touch the permissions of chrome-sandbox anywhere though, is the actual issue that Electron isn't distributed with the right permissions on chrome-sandbox?

**Comment by scottfurry** [comment]
@Tyriar - not sure about Electron/VSC seperation of concern, but from the end-user's perspective all of the linux distributions (rpm, deb, and tar.gz) all have the wrong permissions. The issue that @deepak1556 referenced above seems to suggest that permissions need to be changed for proper execution.

**Comment by bpasero** [comment]
@scottfurry 

> Attempt to open from menu item

We add --no-sandbox to our code.desktop file that I thought was used on Linux distros when launching from the OS:

https://github.com/microsoft/vscode/blob/fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347/resources/linux/code.desktop#L5

Are you on an OS that does not go through this file?

**Comment by scottfurry** [comment]
@bpasero  - You're right. I just had a look at the desktop file in the rpm.
I'm on Funtoo (gentoo derivative). The ebuild we use has it's own desktop file but was originally another persons work.
I'm a little confused about the '--unity-launch' item, though.

**Comment by scottfurry** [comment]
Weird... I tried executing from cmd line with `--no-sandbox` switch. VSC starts up as expected. There is no error reporting (as shown in original post), but I keep getting `Option 'sandbox' is unknown. Ignoring'`.

**Comment by bpasero** [comment]
> The ebuild we use has it's own desktop file but was originally another persons work.

Then I suggest you report this to them and we close this here because VSCode cannot change this for other distributions that forked our desktop file.

**Comment by scottfurry** [comment]
Closing seems premature.
Even with corrections to the desktop file, there appears to be issues with sandbox switch.

**Comment by scottfurry** [comment]
Issue w/ `no-sandbox` issues appears to be referenced in [#84238](https://github.com/microsoft/vscode/issues/84238) and a fix appears to be incorporated for next release.

**Comment by scottfurry** [comment]
@bpasero - just one problem... (not to pile on too much here but)
rpm and deb have a desktop file. Latest release of VSC (1.40.1) tar.gz doesn't include a desktop file.
