### ISSUE TITLE
vscode.workspace.fs.remove() (and copy()) succeed unexpectedly.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84177]
- VSCode Version: 1.40.0
- OS: linux

(working on an extension remotely over SSH; haven't tried local)

The following worked unexpectedly:

* `remove()`:
   * for directories (with `{ recursive: true }`), does not fail if the directory does not exist
* `copy()`:
   * (with `{ overwrite: true }`), does not fail if the dest's parent directory does not exist

[The docs](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) say:

* copy() - "throws - FileNotFound when parent of destination doesn't exist"
* remove() - "throws - FileNotFound when uri doesn't exist."

**Comment by jrieken** [comment]
@ericsnowcurrently Regarding the `stat` calls: what scheme is this? Just `file` or something other scheme? Generally the provider decides what to return and unless it's our provider there is little we can do.

@bpasero for `remove` and `copy`. This is how we call the internal file service: https://github.com/microsoft/vscode/blob/a97738297d3c1c96dd18094fef108d70a0cc569a/src/vs/workbench/api/browser/mainThreadFileSystem.ts#L87-L95

**Comment by bpasero** [comment]
The file service is `mkdirp`'ing the target [here](https://github.com/Microsoft/vscode/blob/15bfc4022232afb4de238334b02e03919dcd73ea/src/vs/platform/files/common/fileService.ts#L581) for both `move` and `copy`. This is how it used to be in the old file service and I did not want to change this logic.

**Comment by ericsnowcurrently** [comment]
I've moved the stat-related problems to their own issues.

[Original]

Title: Problems with new "vscode.workspace.fs" API.

I'm working on using the new "vscode.workspace.fs" API in the Python extension.  I may have found some bugs.  There is a real chance that I have some of this wrong, but I've been working from [the docs](https://code.visualstudio.com/api/references/vscode-api#FileSystem).

* `stat()`:
   * `FileStat.ctime` and `FileStat.mtime` have granularity of 1 second (rather than 1 millisecond) #84526
      * node's `fs.Stats` has millisecond granularity
   * `FileStat.ctime` is always 0 rather than the correct ctime #84525
   * (also for `readDirectory()`) for a socket `FileStat.type` is `File` rather than the expected `Unknown` #84524
      * honestly it isn't clear what `Unknown` is for

(Also see #84175 for missing functionality.)

**Comment by bpasero** [comment]
With the fix for https://github.com/microsoft/vscode/issues/86217, you should now see an error when deleting a resource that does not exist.

**Comment by jrieken** [comment]
Verified that the remove case works, the copy case is as described above. Closing this issue, esp since this isn't against the aforementioned docs which are about the providers, this API is about us as a consumer of those APIs
