### ISSUE TITLE
Problems with SHIFT & ENTER in IDE

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#84178]
When a person presses by mistake the SHIFT & Enter at the same time, because 
they are use to pressing that command on other softwares or online areas.
And then when mistakenly done in VS-Code, the IDE throws an error,
and for some reason cant get out of that error to continue coding. 
It will mess up the terminal to the point that every time this happens,
I am forced to completely shut down VS-Code and restart it.
Which is now getting extremely annoying.
I tried breaking this habbit, but Ive been pressing SHIFT & Enter for other softwares and
online forums which forces the cursor to continue to the next line and prevent the cursor from jumping down 2 lines down. 
Not to mention other softwares that have this command as well.
I dont know how to get out of it after the situation, as I get a error message with  >>>
and wont let me continue to code or output to terminal or even use the terminal.
forcing me to completely force restart the IDE. This happens around 20 times or more while im using the IDE.  its a bit frustrating.

- VSCode Version:
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5

- OS Version: 
Windows 10

Steps to Reproduce:

1. Write a valid code several lines long
2. Press SHIFT and ENTER

**Comment by alexandrudima** [comment]
@RobFosterNYC I cannot reproduce with the following steps:
- I have opened a `.txt` file
- I typed some characters in it
- I pressed `shift+enter`.


![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/68462445-d6831780-020c-11ea-873a-f661d8081d1a.gif)

Pressing Shift+Enter is not bound to anything out of the box in an editor. Here are the defaults for the keybinding (Ctrl+K Ctrl+S):

![image](https://user-images.githubusercontent.com/5047891/68462389-b7848580-020c-11ea-8120-0aae19a5938d.png)

**Comment by RobFosterNYC** [comment]
When I do it even with a simple code.  This is what happens to me when I press SHFT & Enter.
I get this error in the terminal then it gets stuck and wont let me out.
I get those (3) >>>  arrows and every time i do anything, it just repeats.
So im forced to do a hard restart of the IDE to go back to normal
.
![CNTRL and ENTER](https://user-images.githubusercontent.com/18384135/68516632-8f1f7a00-0252-11ea-9958-d07310e3a84b.png)

It also does this when I also accidentally press SHFT & Enter.
I get these (3) ... dots and it also just repeats with anything I do.
And I also have to do a hard restart of the IDE.
.
![stuck in VS-Code](https://user-images.githubusercontent.com/18384135/68516781-005f2d00-0253-11ea-98f6-56087d7ec537.png)

**Comment by RobFosterNYC** [comment]
This is the list I have for keyboard shortcuts.
.
![Shortcut list](https://user-images.githubusercontent.com/18384135/68517092-1d483000-0254-11ea-91e9-0d84f312ff0a.png)

**Comment by alexandrudima** [comment]
@RobFosterNYC Thanks for the extra details. I think you are in a python file and then you press shift+enter and that evaluates the selection/line in the python terminal. I believe this is a feature that comes with the python extension. You can:
1. Disable/uninstall the python extension if you don't want it at all
2. Log an issue directly against https://github.com/microsoft/vscode-python and complain (not sure what about)
3. Remove the keybindings contributed by the python extension by pressing right click > Remove Keybinding in the keyboard shortcuts editor.

**Comment by RobFosterNYC** [comment]
If disable/uninstall the python extension, then I wont be able to code in python.
So im a bit confused by this or dont understand what your mean.
Also there are several keybindings for Python in the keybindings.
I dont know which one I should disable as I dont want to cripple python that will prevent me from coding in python.
I will post a link to this entire post over at the link your supplied, in hopes that someone can come up with something to solve this issue. as its now getting really annoying.
