### ISSUE TITLE
Search hit rectangle makes highlighting text impossible

### ISSUE THREAD

**Issue by willashley23** [microsoft/vscode#84172]
- VSCode Version: 1.36.1 (1.36.1)
- OS Version: 10.14.6

Steps to Reproduce:

1. perform a global search with cmd+shift+f
2. click on a search result in the side pane (a specific line, not just the file name)
3. When it takes you to the line in the file where the search hit was found, observe the rectangle around the hit. 
4. attempt to highlight the text inside the rectangle. It is not possible. There is absolutley no UX indication that anything is happening. Further, it is not possible to get the rectangle to go away unless you literally close the search box or of course change the search query to break the match. Escape key **should** cancel out the global search or at least the rectangle. 

Does this issue occur when all extensions are disabled?: Yes

![demo](https://user-images.githubusercontent.com/9400869/68437806-e94b0d00-0176-11ea-9f96-9da50757c0f6.gif)

**Comment by gjsjohnmurray** [comment]
What color theme are you using?

**Comment by alexandrudima** [comment]
@willashley23 The decorations are rendered on top of the selection? Have you done any color customizations where you define non-transparent colors?

**Comment by willashley23** [comment]
@gjsjohnmurray I am using the default Material Theme
