### ISSUE TITLE
error warning ejs dynamic element style

### ISSUE THREAD

**Issue by osmanraifgunes** [microsoft/vscode#84170]
- VSCode Version: 1.40.0
- OS Version: windows 10

Steps to Reproduce:

1. create an html file and change extention to ejs
2. past the sample code in this issue into the the body tags

I have an element that should have dynamic style :

`<div class="d-none" style="left: <%=i%>px; top: <%=i%>px;">
`for style part `(style="left: <%=i%>px; top: <%=i%>px;")` vscode says

> at-rule or selector expectedcss(css-ruleorselectorexpected).

I installed ejs language support plugin but still error.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Please start by filing this against your ejs extension
