### ISSUE TITLE
Extension README headers are really big

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8417]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

They should be a little smaller like the marketplace in my opinion.

![image](https://cloud.githubusercontent.com/assets/2193314/16427540/a2b1ce0e-3d22-11e6-98d9-af4d380928e3.png)

**Comment by isidorn** [comment]
I like the current design, but that is just me, letting @joaomoreno decide in july

**Comment by joaomoreno** [comment]
The amount of issues I got simply because a CSS file was missing from the build is incredible.
