### ISSUE TITLE
PseudoTerminal.open isn't called in some circumstances

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#84174]
I have the following problem in one of the extensions:
- Extension uses Terminal.create with Pseudoterminal API
- In some circumstances pseudoterminal.open isn't called, though, when I resize and close it, events come

In extHostTerminalService I found the following code:
```
		let retries = 5;
		while (retries-- > 0) {
			if (this._terminalProcesses[id]) {
				(this._terminalProcesses[id] as ExtHostPseudoterminal).startSendingEvents(initialDimensions);
				return;
			}
			await timeout(50);
		}
```

It gives only 250ms for terminal to create and it seems that in my circumstances it's not enough. What's worse not even an error message is displayed. It's completely ignored. Could you do something around it, please?

**Comment by connor4312** [comment]
@Tyriar could you add steps for this?

**Comment by Tyriar** [comment]
@connor4312 I don't know how to reproduce the problem, an extra code review of the PR might be good enough?

@solomatov could you verify whether the fix worked?

**Comment by connor4312** [comment]
Code lgtm

**Comment by solomatov** [comment]
@Tyriar The PR fixes the repro for the problem I had. I haven't encountered this error in other circumstance.s

**Comment by Tyriar** [comment]
@solomatov thanks, the best verification is from the OP 😃
