### ISSUE TITLE
Extension install button text is not centered on Ubuntu

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8418]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

2px margin on top, 4px on bottom.

![image](https://cloud.githubusercontent.com/assets/2193314/16426969/1d9e64ae-3d20-11e6-9e75-0c487f832e81.png)

**Comment by joaomoreno** [comment]
I've recently moved to the `Ubuntu` font, which looks great:

![image](https://cloud.githubusercontent.com/assets/22350/16808839/6a05bc84-491e-11e6-870a-044c6d932fb1.png)

**Comment by Tyriar** [comment]
:+1: looks much nicer
