### ISSUE TITLE
Shortcut for Copy Line Down/Up does not work

### ISSUE THREAD

**Issue by nidhinmtw** [microsoft/vscode#84188]
- VSCode Version:1.40.0
- OS Version:Windows 7 64bit

Steps to Reproduce:

1. Place the cursor on the line you want to duplicate and do Shift + Alt + Down(Up) arrow
2. Nothing happens
Expected: The line should get duplicated below(above).
It was working in 1.39, stopped worked after update to 1.40
Sometimes, if we do line move by Alt + Down Arrow, then do the above Line Copy shortcut, it seems to work occasionally.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@nidhinmtw AFAIK we haven't changed this with 1.40. Can you please double check the following:
- open the keybindings editor (ctrl+k ctrl+s)
- search for `"shift+alt+down"`

Can you check if this is the only keybinding bound to `shift+alt+down` ?
![image](https://user-images.githubusercontent.com/5047891/68460651-afc2e200-0208-11ea-9769-271fd341b934.png)

**Comment by JonWallsten** [comment]
@alexandrudima: Just stumbled upon this. There are multiple commands connected to the same keys.
![image](https://user-images.githubusercontent.com/5993909/68836309-55b79600-06ba-11ea-8c96-e98e84f5fd9a.png)

**Comment by alexandrudima** [comment]
I think this has been fixed in the meantime.
