### ISSUE TITLE
1.40 breaks Arduino Extension Serial connection... again

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode#84192]
Same problem as #76538. From that issue:

> OK. This explains it. The problem is that the Arduino extension uses native node modules (which is not official supported right now in VS Code) and the node version of VS Code has changed. This basically means that the Arduino folks need to ship a new version of their extension.

No action is required from the VSCode team, I've opened this issue as a signpost for users of the Arduino extension so please leave it open for a couple of weeks to make it easy to find.

The best workaround is to revert to 1.39.2 pending an extension update. Don't forget to turn off auto-update in your settings. Here's how: https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates

**Comment by bpasero** [comment]
@PeterWone is it possible for Arduino to implement the native module using N-API? That should make it possible to use the same native module across different node.js versions.

**Comment by PeterWone** [comment]
@bpasero I had a similar thought but It's not an aspect on which I've previously worked. I'm still reading through the code.

**Comment by bpasero** [comment]
I am fine leaving this open, but adding "needs more info" to close automatically in 7 days. I do not think VSCode can do anything about it. I really recommend N-API. We have also started to convert our dependencies. 

//cc @deepak1556

**Comment by PeterWone** [comment]
vscode-arduino 0.2.28 has been updated to the same node version as vscode 1.40
