### ISSUE TITLE
asExternalUri requires flag `--enable-proposed-api`

### ISSUE THREAD

**Issue by 928PJY** [microsoft/vscode#84196]
- VSCode Version: 1.40
- OS Version: win10

Steps to Reproduce:

1. use asExternalUri for uriScheme URIs

Does this issue occur when all extensions are disabled?: No

Hi, it is glad to see the release VS Code 1.40.  
With this new version, the `env.createAppUri` has been moved from proposed API to stable(by supporting using asExternalUri for uriScheme URIs #82884 & #83055), which can empower my extension to support login scenarios without running with `--enable-proposed-api` flag(I notice that there are several extensions, .e.g. [Azure account](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) and [GitHub pull requests](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github), using this API but they can run without this flag, is there an extension whitelist or something?).  
But after I try the new API, I got the following error:
> Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ceapex.docs-build

Here is a part of the error stack:
```
Error: [ceapex.docs-build]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ceapex.docs-build
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:490:143)
	at Object.t.checkProposedApiEnabled (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:490:505)
	at Object.asExternalUri (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:217)
	at CredentialController.<anonymous> (e:\vscode\vscode-docs-build\out\credential\credentialController.js:123:50)
```
In my understanding, you should not do `checkProposedApiEnabled` inside the createAppUri function now, right?

**Comment by bpasero** [comment]
@928PJY please do not use `vscode.env.createAppUri` anymore but use `vscode.env.asExternalUri`. I just verified this works in stable. 

See https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_40.md#vscodeenvasexternaluri

**Comment by 928PJY** [comment]
@bpasero Thanks for your reply.  
Actually, I am using the `vscode.env.asExternalUri`(You can see from the error stack), have you try using `vscode.env.asExternalUri` with a `vscode.env.uriScheme` URIs, or just `http(s)` schema URIs?  
here is my real case:
```js
// getExtensionId() is a function to get my extension id
await vscode.env.asExternalUri(vscode.Uri.parse(`${vscode.env.uriScheme}://${getExtensionId()}/aad-authenticate`));
```

**Comment by bpasero** [comment]
@928PJY yes I tried all that works fine for me. I am clueless, assigning to @mjbvz

**Comment by bpasero** [comment]
@928PJY are you sure this is Stable 1.40? can you show the about dialog?

**Comment by 928PJY** [comment]
Sorry, it is my fault, I just update the package version of `@type/vscode` without update the VS Code.
Close this issue as it has been verified.
