### ISSUE TITLE
Long line of hover text gets cut off instead of line wrapping

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#842]
https://github.com/Microsoft/vscode-go/issues/131 appears to be unfixable with the current API, since lines aren't being automatically wrapped, there is no way to request them to be wrapped, and there is no apriori known length at which to proactively wrap that will look good in general.

**Comment by alexandrudima** [comment]
@jrieken I think the hovers coming from extensions now always produce <pre>, which prevents DOM wrapping
