### ISSUE TITLE
the "enter" key doesn't work after uninstall python-indent extension

### ISSUE THREAD

**Issue by lfjbb** [microsoft/vscode#84207]
![捕获](https://user-images.githubusercontent.com/35714131/68453086-823d5f00-022f-11ea-9d65-314538d1a5b5.PNG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lfjbb** [comment]
how can I solve this。 and auto indent doesn't work when I work with C/C++

**Comment by bucengfangqi** [comment]
not only enter,all way of commit is invalid~~~~~~~~~

**Comment by bucengfangqi** [comment]
if you commit something,commit message whit # start,you will can't commit git

**Comment by alexandrudima** [comment]
@bucengfangqi That is tracked in #84201

@lfjbb Can you please try looking at your `keybindings.json` and comment it out, or otherwise can you please open the keybindings editor at ctrl+k ctrl+s and search for "enter"?

Here is the defaults we ship with:
![image](https://user-images.githubusercontent.com/5047891/68461177-e8af8680-0209-11ea-8596-a419a12e03ac.png)

**Comment by alexandrudima** [comment]
Also, have you tried disabling all extensions? I have searched online and found a hit for `pythonIndent.newlineAndIndent` at https://github.com/kbrose/vsc-python-indent , so it appears to me you have installed an extension that "steals" <kbd>Enter</kbd>

**Comment by lfjbb** [comment]
> @bucengfangqi That is tracked in #84201
> 
> @lfjbb Can you please try looking at your `keybindings.json` and comment it out, or otherwise can you please open the keybindings editor at ctrl+k ctrl+s and search for "enter"?
> 
> Here is the defaults we ship with:
> ![image](https://user-images.githubusercontent.com/5047891/68461177-e8af8680-0209-11ea-8596-a419a12e03ac.png)

I search for "enter" in keybindings editor and find two come from user defiend delete them then everything is fine。   this two keybindings may come from python-indent extension。 I never define them。this problem is after I uninstall the python-indent extension and I cannot repeat it.
thanks!!!
