### ISSUE TITLE
can not search extensions

### ISSUE THREAD

**Issue by whitefirer** [microsoft/vscode#84209]
Issue Type: <b>Bug</b>

cant type the search words in the input

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 3.10.0-862.14.4.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 3.10.0-862.14.4.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 61xx CPU (4 x 2494)|
|Memory (System)|7.64GB (0.19GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.40.2
remote-containers|ms-|0.83.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
vscode-icons|vsc|9.5.0
jinja|who|0.0.8
yaml2json|ahe|0.0.3
gitstash|art|3.1.0
bala-bks-kubernetes-snippets|bal|0.2.2
vscode-linkerd|bha|0.1.4
githistory|don|0.4.6
gitlens|eam|10.1.2
code-runner|for|0.9.14
kubernetes-snippets|ipe|0.1.9
MagicPython|mag|1.1.0
git-graph|mhu|1.18.0
vscode-language-pack-zh-hans|MS-|1.40.2
kind-vscode|ms-|0.0.2
vscode-kubernetes-tools|ms-|1.0.6
python|ms-|2019.10.44104
VSNotebooks|pav|1.4.4
emoji|Per|0.0.3
vscode-yaml|red|0.5.3
trailing-spaces|sha|0.3.1
swdc-vscode|sof|1.2.0
json2yaml|tux|0.2.0
nodejs-devops-extension-pack|vym|0.0.1
gitblame|wad|3.0.1
vscode-wakatime|Wak|2.2.1

(1 theme extensions excluded)

</details>

<summary>More Info</summary>
@rebornix I use the SouguoWuBi，
Download Page url is [http://wubi.sogou.com/](url)

default input is Chinese，I type words just like this:
![vscode](https://user-images.githubusercontent.com/12084604/68652034-9bae1600-0563-11ea-8b8a-e7e2ca864ea1.gif)

My  setting:
![image](https://user-images.githubusercontent.com/12084604/68653137-fea0ac80-0565-11ea-8072-db8c4c6627ab.png)

![image](https://user-images.githubusercontent.com/12084604/68653322-75d64080-0566-11ea-9aa2-3a6290730c81.png)

**Comment by whitefirer** [comment]
![image](https://user-images.githubusercontent.com/12084604/68454082-8323c000-0232-11ea-925a-c4214a9c44c3.png)

the search input is the black area and too small!

**Comment by whitefirer** [comment]
and canot search by enter

**Comment by whitefirer** [comment]
I know how it happened. when i use  sougou input to typing chinese word, I change to type english words， then it happaned, and I must restart the vs code for work. If i type english chars directly, it is ok. so this is a bug for chinese input.

**Comment by whitefirer** [comment]
A bug of vscode. the extesions' search input area has been changed sometimes.

**Comment by alexandrudima** [comment]
@rebornix Are you familiar with this input method? Could you please try to repro?

**Comment by rebornix** [comment]
> I know how it happened. when i use sougou input to typing chinese word, I change to type english words， then it happaned, and I must restart the vs code for work. If i type english chars directly, it is ok. so this is a bug for chinese input.

@whitefirer can you help understand how you switch to English mode when using Sougou IME? I can't reproduce this issue on Windows and in Chinese or English mode. Besides, can you reproduce this issue in the editor?

**Comment by whitefirer** [comment]
@rebornix I use the SouguoWuBi，
Download Page url is [http://wubi.sogou.com/](url)

default input is Chinese，I type words just like this:
![vscode](https://user-images.githubusercontent.com/12084604/68652034-9bae1600-0563-11ea-8b8a-e7e2ca864ea1.gif)

My  setting:
![image](https://user-images.githubusercontent.com/12084604/68653137-fea0ac80-0565-11ea-8072-db8c4c6627ab.png)

![image](https://user-images.githubusercontent.com/12084604/68653322-75d64080-0566-11ea-9aa2-3a6290730c81.png)

**Comment by whitefirer** [comment]
Type "git" with Chinese input，and then press 'Ctrl+SPACE' change to english input
