### ISSUE TITLE
Takes some time to maximize window

### ISSUE THREAD

**Issue by alvin30595** [microsoft/vscode#84204]
Take a longer time to maximize VSC after the latest release updates

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    63	  5976	code main
    0	   326	  6564	   gpu-process
    1	    67	  9056	   window (Issue Reporter)
    3	    41	 10848	   shared-process
    0	     5	 12600	   electron-crash-reporter
    0	   276	 16236	   window (queueList.js - Encoremed - Visual Studio Code)
    0	     8	  6224	     watcherService 
    0	     2	 15032	       console-window-host (Windows internal process)
    0	   103	 16180	     extensionHost
    0	   170	   448	       electron_node tsserver.js 
    0	    10	  9596	         electron_node typingsInstaller.js typesMap.js 
    0	    22	  9148	       electron_node intelephense.js 
    0	    37	  9652	       electron_node tsserver.js 
    0	    14	 15296	       "C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=16180
    0	    10	 16452	       "C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=16180
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (queueList.js - Encoremed - Visual Studio Code)
|    Folder (Encoremed): 3623 files
|      File types: svn-base(1396) js(600) php(564) html(215) css(87) png(44)
|                  json(22) sql(9) gif(7) woff(7)
|      Conf files: package.json(8);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.2.3
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
tortoise-svn|fan|0.1.1
beautify|Hoo|1.5.0
svn-scm|joh|1.54.11
partial-diff|ryu|1.4.0
vscodeintellicode|Vis|1.2.0
change-case|wma|1.0.0
local-history|xyz|1.7.0
current-file-path|Yos|2.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by bpasero** [comment]
@alvin30595 to clarify, you click on the maximize window button and that is slow? Can you compare with 1.39: https://az764295.vo.msecnd.net/stable/6ab598523be7a800d7f3eb4d92d7ab9a66069390/vscode-server-win32-x64.zip

Also, does it change if you configure `"window.titleBarStyle": "native"`?

**Comment by alvin30595** [comment]
when i maximize the window, it just show a blank screen for a second, it does react faster when i change the titleBarStyle to native.

**Comment by ogmios-voice** [comment]
It can be reproduced by minimizing the window and restoring it (e.g. by clicking on the application on the taskbar twice):

1. in case of normal windows it is fast, w/o any extra resize/repaint operations
2. in case of a **maximized window** most of the time the window is black for >=1s, then it starts to rebuild/reposition every component (can be observed most notably on the scroll bars).

**Comment by sbatten** [comment]
seems the same as #84343 which as I'm getting through notifications just has more traction so closing this one as duplicate even though it is older.
