### ISSUE TITLE
Activity Bar Icons

### ISSUE THREAD

**Issue by dcbacarro** [microsoft/vscode#84205]
The activity bar icons became like this after I upgraded to 1.40.0
![image](https://user-images.githubusercontent.com/49216769/68452431-6f298f80-022d-11ea-8b44-b6d9bfff69b8.png)

- VSCode Version: 1.40.0
- OS Version: Linux x64 5.0.0-32-generic

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@dcbacarro what theme are you using? does it change when you change themes?

**Comment by misolori** [comment]
@dcbacarro also, what Linux distro are you seeing this on?

**Comment by dcbacarro** [comment]
> @dcbacarro what theme are you using? does it change when you change themes?

I'm using Ocean Space theme (oscarmcm.ocean-space). The icons stay the same even on other themes. I also tried to disable all extensions, no effect. The activity bar icons are still small.

**Comment by dcbacarro** [comment]
> @dcbacarro also, what Linux distro are you seeing this on?

@misolori  I'm using Ubuntu 19.04

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by misolori** [comment]
I tested this on Ubuntu 19.10 and can't repro this:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35271042/68534238-e8d18400-02e6-11ea-8ca9-066f8fe831a1.png">

@dcbacarro do you have any custom customizations either in VS Code or in Ubuntu? Does this also repro when all extensions are disabled?

**Comment by Ikos9** [comment]
I've the same problem on macOS 10.15.1, it seems fine on the Insider build tho.
I'll wait for the first recovery build (waiting for the font issues) then report back if there is still this problem.

**Comment by bpasero** [comment]
@dcbacarro can you report back how it is with insidersß

**Comment by dcbacarro** [comment]
@bpasero It is the same with insiders.

FYI. I am using Customize UI extension with MonkeyPatch. I disabled both and the icons were back to normal. It is just odd that it didn't work when i run vscode with --disable-extensions flag.
