### ISSUE TITLE
After upgrade, for plugin of C/C++, no Suspended prompt

### ISSUE THREAD

**Issue by cui3093** [microsoft/vscode#84203]
- VSCode Version: 1.40
- OS Version: CentOS Linux release 7.7.1908 (Core)

Steps to Reproduce:

as title.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@cui3093 I am sorry, I do not understand what is exactly the issue. Can you please add more detailed steps, what you would expect to happen vs. what happens? Sometimes, a screenshot demonstrating the problem might be useful for us as well.

**Comment by sean-mcmanus** [comment]
@cui3093 If this is a C/C++ extension bug, you could file more info at https://github.com/Microsoft/vscode-cpptools/issues .

**Comment by cui3093** [comment]
Let me describe the issue in chinese.
1 当前版本安装C/C++扩展插件， 大型项目资源管理器->大纲只要源文件有改动，大纲内容就无法展示
2 当前版本鼠标停留在宏调用或者变量或者函数或者类上，不提示定义信息，一直提示加载中
3 鼠标右键查看定义信息，一直提示加载中。
把vscode卸载重装，插件卸载重装，还是一样的问题。

**Comment by sean-mcmanus** [comment]
1 The current version of the installation of the C/C?extension, large project explorer - as long as the source file has been changed, the outline content can not be displayed
2 The current version mouse stays on a macro call or a variable or a function or class, does not prompt for the definition of information, always prompts to load
3 Right mouse button to view the definition information, always prompted to load.
Reloading vscode, plug-in uninstall reloading, or the same problem.

This sounds like a C/C++ extension bug. I'm not aware of other bug reports like this. I don't think we have enough repro info though. We're releasing a 0.26.2-insiders tomorrow with a bunch of bug fixes which may address this.

**Comment by cui3093** [comment]
> 
> 
> 1 The current version of the installation of the C/C?extension, large project explorer - as long as the source file has been changed, the outline content can not be displayed
> 2 The current version mouse stays on a macro call or a variable or a function or class, does not prompt for the definition of information, always prompts to load
> 3 Right mouse button to view the definition information, always prompted to load.
> Reloading vscode, plug-in uninstall reloading, or the same problem.
> 
> This sounds like a C/C++ extension bug. I'm not aware of other bug reports like this. I don't think we have enough repro info though. We're releasing a 0.26.2-insiders tomorrow with a bunch of bug fixes which may address this.

Hi, sean, thank you for your reply. I did not suffer the issue for 1.39, and turned back to 1.39, all issues encountered gone.

**Comment by sean-mcmanus** [comment]
@alexandrudima If going to 1.39 solves the issue for the user, it seems like it may be some VS Code regression -- we're not aware of a 1.40 change that would cause our extension to break.
