### ISSUE TITLE
Extension recommendations should say why they're recommended

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8421]
#8215
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Something like "These extensions may be useful based on the files you have viewed" may be useful? It wasn't immediately obvious to me and would help illustrate the differentiate between @popular.

**Comment by isidorn** [comment]
Not cruical, feature request, july

**Comment by joaomoreno** [comment]
It now says `The '{0}' extension is recommended for this file type.`
