### ISSUE TITLE
Font become bolder after 1.14.0

### ISSUE THREAD

**Issue by Acmu** [microsoft/vscode#84211]
- VSCode Version: 1.40.0
- OS Version: mac os 10.14.6 

1. Why font font become bolder than before? I want original font weight, how can I do this?

Does this issue occur when all extensions are disabled?: Yes

**Comment by litao1993** [comment]
:+1:

**Comment by mother99b4x** [comment]
Go to Settings/ Workbench: Font Aliasing
Select antialiased

**Comment by Acmu** [comment]
> Go to Settings/ Workbench: Font Aliasing
> Select antialiased

Awesome, thank you!

**Comment by crysislinux** [comment]
But the terminal still has blod font.

**Comment by jediyozh** [comment]
@mother99b4x thanks!
