### ISSUE TITLE
Find & Replace adding random text in random files

### ISSUE THREAD

**Issue by AaronLavers** [microsoft/vscode#84218]
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Have a large directory of assorted files
2. Perform a large find and replace across the root dir
3. Inspect files that have been modified

I have a large email template directory which I was performing bulk URL updates. Our URL's are formed as such: {{SITE_URL}}/invitation-card/?invitationID={{INVITATION_ID}}

Changing this line with find & replace files resulted in VSCode adding this to random parts of files, often adding it into the doctype line randomly in some files (but not all!), leaving me with scattered files that have: 
'!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http:/{{SITE_URL}}/invitation-card/?invitationID={{INVITATION_ID}}/www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"' 
in the top line. 
Other files end up having parts duplicated, like:

  {{SITE_URL}}{{SITE_URL}}/invitation-card/?invitationID={{INVITATION_ID}}

I am wondering if the {{ }} brackets are messing up VS Code's regex perhaps. Even some of the variable text within brackets are being added into random parts of the files after a find and replace, even if the text added was not what was searched for.

i.e. One file had:

!DOCTYPE html PUBLIC {{FIRST_NAME}}{{LAST_NAME}}{{CONTACT_NUMBER}}{{CONTACT_EMAIL}}

Which was totally incorrect. Unfortunately we've had to manually check around 200+ files for errors this afternoon.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Sorry that this happened, is it possible that you have bare CR line endings in these files? (not LF or CRLF) Can you share the files and the exact find/replace text?

**Comment by AaronLavers** [comment]
> Sorry that this happened, is it possible that you have bare CR line endings in these files? (not LF or CRLF) Can you share the files and the exact find/replace text?

Unfortunately I can't share files sorry due to business constraints, however I have updated to the latest release and so far haven't been able to replicate the problem... I can re-open this if I come across the issue again and do a more thorough report.

**Comment by roblourens** [comment]
Ok, FYI this sounds a lot like issues we have had with files that have some CR characters, where we only really work correctly with LF or CRLF line endings.
