### ISSUE TITLE
After 1.40 update, switch between console (alt-arrow) loses focus

### ISSUE THREAD

**Issue by hokkanen** [microsoft/vscode#84212]
- VSCode Version: 1.40.0
- OS Version: Ubuntu 19

Steps to Reproduce:

1. Open 2 console instances
2. Use ALT-RIGHT/LEFT ARROW to navigate
3. After moving to another console instance, the focus is lost (is returned by hitting ESC)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
Possibly related - #84227

**Comment by Tyriar** [comment]
Yes it sounds like it.

/duplicate
