### ISSUE TITLE
One Dark Pro theme is darker than usual

### ISSUE THREAD

**Issue by StarHyx** [microsoft/vscode#84213]
+ VSCode Version: 1.40.0
+ OS Version: mac os 10.14.4

After updating to 1.40.0, One Dark Pro theme becomes **darker than usual**  (see images below) , is anything change here? How can I set to recover it?

### 1.40.0
<img width="477" alt="Jietu20191108-144106@2x" src="https://user-images.githubusercontent.com/31642906/68456567-195ae480-0239-11ea-89a1-c4e87e6cd084.png">

### 1.39.2
<img width="461" alt="Jietu20191108-144227@2x" src="https://user-images.githubusercontent.com/31642906/68456575-1c55d500-0239-11ea-91c5-977224dc8fbd.png">

**Comment by trananhmanh89** [comment]
Same
I'm using vscode 14 on windows 10

**Comment by andreyjamer** [comment]
The same issue. Theme now is darker.

**Comment by OlivierLicorn** [comment]
Same "problem" here.
1) My custom theme disappeared
2) The colors seem bland

VSCode Version: 1.40.0
Windows 7

**Comment by bpasero** [comment]
I would think this is probably https://github.com/microsoft/vscode/issues/84154

**Comment by bpasero** [comment]
Out of curiosity, we recently started to build VSCode with the latest Electron 7.x that comes with Chrome 78. Does something change in those versions?

Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration_1.41.0-1573181501_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1.41.0-1573181670.el7.x86_64.rpm)
* Linux (ZIP): [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/code-exploration-1573181432.tar.gz)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/fbad8db043f1ef8e3b4031d46057edb5911f92ba/VSCodeSetup-x64-1.41.0-exploration.exe)
