### ISSUE TITLE
I can't commit git

### ISSUE THREAD

**Issue by bucengfangqi** [microsoft/vscode#84210]
Issue Type: <b>Bug</b>

file update can't commit ！

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.802.3
path-intellisense|chr|1.4.2
ng-alain-extension-pack|cip|7.1.0
ng-alain-vscode|cip|7.0.0
ng-zorro-vscode|cip|8.3.1
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|2.2.0
markdown-table-prettify|dar|2.4.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.2
prettier-vscode|esb|2.3.0
auto-rename-tag|for|0.1.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
angular2-switcher|inf|0.2.0
Angular2|joh|8.1.1
vscode-language-pack-zh-hans|MS-|1.40.2
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
quicktype|qui|12.0.46
vue-vscode-snippets|sdr|1.8.0
vscode-scss-formatter|sib|1.4.2
move-ts|str|1.11.5
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by gjsjohnmurray** [comment]
Does this reproduce if you run with all extensions disabled?

**Comment by gjsjohnmurray** [comment]
Is #84201 relevant?

**Comment by bucengfangqi** [comment]
this is a interesting bug
if  you commit something,commit message whit  # start,you will can't commit git

**Comment by bucengfangqi** [comment]
Before this VScode update, I can commit like this
![image](https://user-images.githubusercontent.com/22071679/68455272-f24ee380-0235-11ea-948b-3cc21da3f82b.png)
Now  I have to remove  #
