### ISSUE TITLE
Web: trusted domain dialog does not persist my choice

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84215]
Steps to Reproduce:

1. selfhost web
2. open package.json
3. hover over a package
4. click on a link
5. configure links to open all
6. click again

=> 🐛 dialog still shows

![image](https://user-images.githubusercontent.com/900690/68457413-88681700-0200-11ea-9c20-6b2356a6cb54.png)

Btw I think after I configured the trusted links, I would expect the link to open right after.

**Comment by octref** [comment]
@sbatten Seems to be caused by your changes

**Comment by sbatten** [comment]
@octref why would my change have anything to do with this? Mine is just display logic. This reproduces with or without my commit.

**Comment by sbatten** [comment]
@octref this only reproduces in OSS if you populate `linkProtectionTrustedDomains`

**Comment by octref** [comment]
Sorry for wrong diagnosis. The root cause is I used `UInt8Array.toString` on web whereas I should have used `VSBuffer.wrap(arr).toString`, which would use the `TextEncoder` as `Buffer` doesn't exist on web.
