### ISSUE TITLE
Cannot read property 'searchInput' of undefined

### ISSUE THREAD

**Issue by AIluffy** [microsoft/vscode#84220]
Issue Type: <b>Bug</b>

global search does not work, vs code reports " Cannot read property 'searchInput' of undefined " error message.

VS Code version: Code - Insiders 1.41.0-insider (fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347, 2019-11-08T05:28:30.394Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.19GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bdefault/home/ailuffy/Projects/daily-work-note|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|15.87GB (6.19GB free)|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
color-info|bie|0.5.1
bracket-pair-colorizer|Coe|1.0.61
FreeMarker|dco|0.0.9
es7-react-js-snippets|dsz|2.4.4
vscode-great-icons|emm|2.1.47
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
vscode-react-typescript|inf|1.3.1
remote-wsl|ms-|0.40.2
material-icon-theme|PKi|3.9.1
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
Bookmarks|ale|10.5.0
project-manager|ale|10.8.0
emojis4git|ben|2.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
clipboard-manager|Edg|1.2.0
vscode-npm-script|eg2|0.3.9
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|2.3.0
nunjucks-template|ese|0.2.0
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.1.1
todo-tree|Gru|0.0.162
docthis|joe|0.7.1
google-search|kam|0.0.1
vscode-codemetrics|kis|1.23.0
vscode-gutter-preview|kis|0.23.0
vs-color-picker|lih|1.0.0
vscode-fileheader|mik|0.0.2
python|ms-|2019.10.44104
vscode-react-native|msj|0.13.0
clear-console|mwo|0.0.3
vetur|oct|0.22.6
polacode|pnp|0.3.4
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.0
vscode-leetcode|she|0.15.7
stylelint|shi|0.51.0
mdx|sil|0.1.0
language-stylus|sys|1.11.0
vscode-status-bar-format-toggle|tom|2.0.0
pdf|tom|0.5.1
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
vscode-mdx-preview|xyc|0.2.2
markdown-pdf|yza|1.4.1
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by AIluffy** [comment]
![image](https://user-images.githubusercontent.com/13102620/68460382-bbcb9580-0242-11ea-96af-320fc7257988.png)
no search ui shows

**Comment by JacksonKearl** [comment]
Thanks for reporting! Fixed in 777ad667, the next insiders release will have it.

**Comment by JacksonKearl** [comment]
Reverted that commit because some validation errors were being thrown. Looking more into it now.
