### ISSUE TITLE
Stuttering in various scenarios

### ISSUE THREAD

**Issue by psukys** [microsoft/vscode#84221]
Issue Type: <b>Performance Issue</b>

At first I thought that it might be related to some extensions, but after disabling and still getting stuttering, which happens randomly.
Another cause could've been some other applications and/or OS related issues, which I rejected as only after starting VSCode the stutters started and I couldn't reproduce them even when trying to run multiple applications (firefox, intellij, slack, etc), or running VSCode only.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.3.6-200.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2669)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|7.68GB (2.85GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    87	 21151	code main
    0	     8	 21153	   zygote
   14	    63	 21400	     shared-process
    0	     0	 24452	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   134	 21955	     window (test.py - foundation-accelerator-4.0 - Visual Studio Code)
    0	    39	 21992	       extensionHost
    0	     0	 21993	       /bin/bash
    0	   189	 22056	       watcherService
    0	    39	 22292	     window (Process Explorer)
    1	    87	 23981	     window (Issue Reporter)
    0	    87	 21181	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.py - foundation-accelerator-4.0 - Visual Studio Code)
|    Folder (foundation-accelerator-4.0): more than 26849 files
|      File types: py(5470) pyc(3460) sql(1860) class(1330) xml(1096) dat(760)
|                  so(635) h(308) SQL(284) json(204)
|      Conf files: makefile(4) settings.json(3) package.json(3) launch.json(1)
|                  gulp.js(1) tasks.json(1) tsconfig.json(1)
|                  webpack.config.js(1)
|      Launch Configs: python;
```

</details>
Extensions: none

**Comment by alexandrudima** [comment]
@psukys We have a guide to better help with filing performance issues at https://github.com/microsoft/vscode/wiki/Performance-Issues . Can you please follow some of the steps in there to help identify which process is consuming a lot of CPU... and then following through with more information that we could use to figure out what's going wrong.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
