### ISSUE TITLE
Explorer: multi-select commands no longer work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84225]
Steps to Reproduce:

1. multi-select files in explorer
2. "compare selected"

=> 🐛 does not work

Culprit: [`getMultiSelectedResources`](https://github.com/Microsoft/vscode/blob/15bfc4022232afb4de238334b02e03919dcd73ea/src/vs/workbench/contrib/files/browser/files.ts#L47) has questionable checks for the instance of the tree that no longer works with the compressible tree this now is. 

There are possible more instance of checks that need to be looked at.

**Comment by joaomoreno** [comment]
Very questionable!

**Comment by joaomoreno** [comment]
cc @isidorn

**Comment by isidorn** [comment]
Thanks for fixing this. Yeah the checks are questionable I confess.
