### ISSUE TITLE
Search Bug

### ISSUE THREAD

**Issue by xiaoshude** [microsoft/vscode#84223]
Issue Type: <b>Bug</b>

On Mac,using cmd + F trigger search， cursor don't focus on search input, while previous version do.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.6.0

**Comment by MartinNuc** [comment]
Any news regarding this bug? Its very annoying :-(

**Comment by rebornix** [comment]
Could you please provide more information, like screenshots, gif to help trouble?

**Comment by arthurmasl** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7428203/68814721-356be500-0682-11ea-8eae-ba84e12885e4.gif)


> Could you please provide more information, like screenshots, gif to help trouble?

**Comment by JsanchezSeyte** [comment]
Same bug here, not breaking but very annoying, anything we can do for fix it till next update?

**Comment by MartinNuc** [comment]
@JsanchezSeyte confirmed. This actually solved my issue too.

**Comment by yordis** [comment]
When I reset `Find With Selection` it defaulted to `CMD+E` which made it worse for me.

**Comment by yordis** [comment]
@rebornix any updates on this?

**Comment by yordis** [comment]
https://github.com/microsoft/vscode/issues/44093#issuecomment-546157573 

..................................................................

**Comment by yordis** [comment]
@rebornix @xiaoshude open pull request pending: https://github.com/microsoft/vscode/pull/95314

**Comment by rebornix** [comment]
@yordis are you still seeing this issue in current Insiders? I can't reproduce this issue, sorry.

**Comment by yordis** [comment]
@rebornix problem fixed in Insiders version.

Should I close #95314?

**Comment by rebornix** [comment]
Thanks for closing it :)
