### ISSUE TITLE
Alt-key behavior on Linux

### ISSUE THREAD

**Issue by xuxicheta** [microsoft/vscode#84227]
- VSCode Version: 1.40
- OS Version: Ubuntu Linux 18.10

After 1.40 updates:
When I press Alt button it activates menu bar and loose cursor focus. 
It's wrong. I have many hot-key shortcuts starting with Alt, including keyboard layout change, and this breaks them all.

Pressing "Alt" have not to activate menu bar. 
Only cominations with menu hot buttons as Alt-F, Alt-S and menu-cursor moving combination as Alt-Left and Alt-Right can activate menu.

**Comment by sbatten** [comment]
Can you confirm that you are using `window.titleBarStyle` as `native`?

**Comment by xuxicheta** [comment]
> Can you confirm that you are using `window.titleBarStyle` as `native`?

yes. native

**Comment by sbatten** [comment]
@bpasero @deepak1556 with the electron upgrade, it seems they fixed the issue on Windows to have alt actually focus the menu bar, but on Linux, this behaviour seems unexpected to users. I did not find a way to disable this which is an option I provide for the custom menu.

**Comment by bpasero** [comment]
Looks like related: https://github.com/electron/electron/issues/2504

**Comment by desthercz** [comment]
> > Can you confirm that you are using `window.titleBarStyle` as `native`?
> 
> yes. native.
> Changed to 'custom', problem is gone. Well, will use it, so 'native' is unusable now.

Didn't worked for me :-/

**Comment by sbatten** [comment]
@desthercz for that workaround, also add `"window.customMenuBarAltFocus": true`

**Comment by desthercz** [comment]
> @desthercz for that workaround, also add `"window.customMenuBarAltFocus": true`
Thanks, that works fine. I liked the "native" option more, but atleast now i don't loose focus everytime i press alt + shift for different keyboard layout, that was super annoying.

**Comment by bpasero** [comment]
@desthercz not sure I understand the issue fully, I think moving focus to menu bar when you press Alt-key and release it is correct for accessibility reasons.

I can bind a command to e.g. Alt+D and see it getting invoked with the native title. What are your steps to reproduce? Are you releasing Alt+key too soon maybe?

**Comment by desthercz** [comment]
> @desthercz not sure I understand the issue fully, I think moving focus to menu bar when you press Alt-key and release it is correct for accessibility reasons.
> 
> I can bind a command to e.g. Alt+D and see it getting invoked with the native title. What are your steps to reproduce? Are you releasing Alt+key too soon maybe?

Commands are indeed invoked, but focus move from code window to top menu and stays there even after keys release.

**Comment by gusbemacbe** [comment]
I use KDE. <kbd>Alt</kbd> depends on KDE's window behaviour. You can check and change the modifier key (replace <kbd>Alt</kbd> for <kbd>Meta</kbd>):

![image](https://user-images.githubusercontent.com/2257024/68617359-e10c0e00-04a5-11ea-830e-0d4e05b1c5e1.png)

**Comment by bpasero** [comment]
> Commands are indeed invoked, but focus move from code window to top menu and stays there even after keys release.

I cannot reproduce that, works totally fine for me.

**Comment by xuxicheta** [comment]
@bpasero  Skype for Linux have exactly same problem. And Postman, Slack have it.

**Comment by bpasero** [comment]
Got it. Please then report it to https://github.com/atom/electron.

**Comment by desthercz** [comment]
@gusbemacbe I also use KDE (Kubuntu 19.04), but sadly your solution don't work for me.

**Comment by gusbemacbe** [comment]
Hello @desthercz 

And this?

![image](https://user-images.githubusercontent.com/2257024/68705995-d321c000-056d-11ea-9f06-0911dfc8377c.png)

**Comment by dafanasiev** [comment]
> @bpasero Skype for Linux have exactly same problem. And Postman, Slack have it.

xkb bug: https://bugs.freedesktop.org/show_bug.cgi?id=865
discussion: https://gitlab.freedesktop.org/xorg/xserver/issues/258
