### ISSUE TITLE
Extension @popular and @recommendations should be searchable or not feature the textbox

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8422]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Since `@popular` was added to the textbox I assumed I could filter it. No point having the textbox there if you can't filter.

![image](https://cloud.githubusercontent.com/assets/2193314/16428082/1b16901c-3d25-11e6-80c0-a2c52340dafc.png)

**Comment by isidorn** [comment]
Not cruical -> july

**Comment by joaomoreno** [comment]
Interesting.
