### ISSUE TITLE
All non ASCII characters are rendered incorrectly in Minimap

### ISSUE THREAD

**Issue by cheronder** [microsoft/vscode#84226]
Issue Type: <b>Bug</b>

![图片](https://user-images.githubusercontent.com/8509523/68461672-bb80c980-0245-11ea-990c-0c41235e4b97.png)

related text:

``` text
# Summary

* [前言](README.md)
* [差的栈实现](first.md)
    * [内存布局](first-layout.md)
    * [New 方法](first-new.md)
    * [所有权初探](first-ownership.md)
    * [Push 方法](first-push.md)
    * [Pop 方法](first-pop.md)
    * [单元测试](first-test.md)
    * [Drop 方法](first-drop.md)
    * [最终代码](first-final.md)
* [好的栈实现](second.md)
* [可持久化的栈实现](third.md)
* [差的双端队列实现](fourth.md)
* [不安全的队列实现](fifth.md)
* [又好又安全的双端队列实现](sixth.md)
* [一些有问题的链表实现](infinity.md)
```

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>Extensions: none

**Comment by alexandrudima** [comment]
The same happens with Cyrillic:

![image](https://user-images.githubusercontent.com/3350070/68479737-187b8000-0244-11ea-8a2c-8f2471391f19.png)

**Comment by ornic** [comment]
I also include here my two other examples :)

As I see, the whole minimap rendering became more Visual-Studio-like. I always wanted that VS's minimap became so smooth and pretty as VS.Code's But it came other way. :(

These two made with the same settings.

Before 1.40.0 | After upgrading to 1.40.0:
-- | --
![image](https://user-images.githubusercontent.com/3350070/68482801-5f20a880-024b-11ea-902a-a77766e25e8a.png) | ![image](https://user-images.githubusercontent.com/3350070/68489528-52ef1800-0258-11ea-8aae-c93a06674ebe.png)

**Comment by wlnirvana** [comment]
any update?

**Comment by AlseinX** [comment]
I don't think it a feature request to upvote but a bug to solve.
Any text that is rendered should be correctly displayed.
