### ISSUE TITLE
Low contrast with own theme after update on 1.40

### ISSUE THREAD

**Issue by Kcko** [microsoft/vscode#84236]
Hi,
I created own theme which comes out from MONOKAI (some small improvement).
After update on new version (1.40) i see very low contrast.

Pls see a big difference http://bit.ly/34Bhpom  

Whats changed? How can i set previous contrast or something  (other settings)... these colors are very non-contrast and weak.

**Comment by Kcko** [comment]
Screen from 1.39 ![](http://bit.ly/2WWjRmS)

**Comment by Kcko** [comment]
Screen from 1.40
![](http://bit.ly/2rq2xej)

**Comment by David-Else** [comment]
I think it relates to this, which also affects PC and Linux https://github.com/microsoft/vscode/issues/84154

**Comment by Kcko** [comment]
@David-Else  yes, it will probably be the same!

**Comment by solesensei** [comment]
@David-Else have the same issue but high contrast instead of normal
