### ISSUE TITLE
[Regression]vscode-test can hit --no-sandbox issue with VS Code 1.40.0

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#84238]
- VSCode Version: 1.40.0
- OS Version: RHEL 7

Steps to Reproduce:

1. use vscode-test
2. launch test on a system requiring `--no-sandbox `workaround

This is a regression, all our jobs started to fail on the release of VS Code 1.40.0.

error message:
```
Downloading VS Code 1.40.0 from https://update.code.visualstudio.com/1.40.0/linux-x64/stable
Downloaded VS Code 1.40.0 into .vscode-test/vscode-1.40.0
[8978:1108/023921.458640:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /mnt/hudson_workspace/workspace/vscode-openshift-build/.vscode-test/vscode-1.40.0/VSCode-linux-x64/chrome-sandbox is owned by root and has mode 4755.

Exit code:   null
Done

Failed
npm ERR! Test failed.  See above for more details.
```

**Comment by apupier** [comment]
a workaround seems to provide `--no-sandbox` for launchArgs 

something like https://github.com/apupier/camel-lsp-client-vscode/commit/3923230f8f4477aa940ed1a19324ef481f9a4d5f

**Comment by bpasero** [comment]
@octref this is something vscode-test needs to provide automatically, it should not have any harms for older Electron versions.

**Comment by octref** [comment]
> Option 'sandbox' is unknown. Ignoring.

I see that as well. I'll add that to release notes.

I added the option. Will release in v1.2.3.

To Verifier:
- You need to be on Ubuntu or Fedora linux
- Clone https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
- `npm i -D vscode-test@1.2.2`
- Modify [this line](https://github.com/microsoft/vscode-extension-samples/blob/a8af0838d6b3228bbebddb3727d1360829d7cd0a/helloworld-test-sample/src/test/runTest.ts#L16) to include `launchArgs: ['--disable-namespace-sandbox']`
- `npm install && npm run test`
- You should see the above error
- Now upgrade vscode-test, `npm i -D vscode-test@1.2.3`
- You shouldn't see the above error

**Comment by awschristou** [comment]
@bpasero  @octref  would it be possible to update the ["legacy" package](https://github.com/microsoft/vscode-extension-vscode/blob/0090df8e01649f76a8a3a72d7edb78aa41c7e910/bin/test#L28) with a similar change too?

**Comment by octref** [comment]
I'm not sure if adding this would break other people sitting on a legacy version of vscode and the `vscode` module. I'd rather not. You should use the new `@types/vscode` and `vscode-test`. Here's the migration guide: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
