### ISSUE TITLE
Problems panel: tune alignment of filter drop down

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#84231]
pls see the screenshot below, suggest to shift it down so that it doesn't overlap with the filter icon.

![image](https://user-images.githubusercontent.com/172399/68464101-4a72ef00-0210-11ea-8881-9afe02dd8f98.png)

**Comment by sandy081** [comment]
This is shown correctly left to the icon. Menu is rendered according to the given anchor (action element).

**Comment by sbatten** [comment]
typically dropdowns are using an icon that doesn't really extend to the bottom of the anchor element. (usually ...)

on macOS, the top position of the menu aligns with the top of the first element, not the top of the full container, giving this alignment.

see windows native
![image](https://user-images.githubusercontent.com/6561887/68626180-9b444b00-048f-11ea-8735-4b821032f918.png)

see windows custom
![image](https://user-images.githubusercontent.com/6561887/68626141-836cc700-048f-11ea-98da-28f3c9f43644.png)

we could either shift all dropdowns on macOS a few pixels by adding some extra dimension to the anchor, or we could adjust all context menus to account for the top padding of macOS menus.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
> we could either shift all dropdowns on macOS a few pixels by adding some extra dimension to the anchor

:+1:
