### ISSUE TITLE
User profiles/Extension groups

### ISSUE THREAD

**Issue by xahon** [microsoft/vscode#84237]
I don't get the idea completely but I think vscode needs some mechanism to group extensions and to choose which group/profile to use in addition to ambient/globally installed extensions. I think it will be useful to save a group in project settings (like recommended extensions, but recommended profiles/groups) and other developers could easily "use" that group without mixing their own extensions with "recommended" ones. When developer decided to quit the project, he could just remove the group and all extensions in it (except user's global scoped extensions) will be removed automatically. When group extension version is different from the same extension user has - group's extension version should override the other. Sorry if my english is bad, this is not my native language

**Comment by sandy081** [comment]
/duplicate

#68527
