### ISSUE TITLE
RunInTerminal debug request doesn't need escape the double quotes inside the argument

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#84235]
Below is the DAP request sent from debugger:
```json
{
    "command": "runInTerminal",
    "arguments": {
        "kind": "integrated",
        "title": "Java Process Console",
        "cwd": "c:\\Demo",
        "args": [
            "C:\\Users\\jinbwan\\.vscode\\extensions\\vscjava.vscode-java-debug-0.23.0\\scripts\\launcher.bat",
            "C:\\Program Files\\Java\\jdk-13.0.1\\bin\\java",
            "-DmyAgent\u003d\"agent1;agent2\"",
            "-Dfile.encoding\u003dUTF-8",
            "@C:\\Users\\jinbwan\\AppData\\Local\\Temp\\cp_1aju9o61n3rxdn7fhamoes99a.argfile",
            "app.Config"
        ]
    },
    "seq": 2,
    "type": "request"
}
```

When the integrated terminal is cmd, it escapes **-DmyAgent="agent1;agent2"** to **"-DmyAgent=""agent1;agent2"""** . Its running result is a different with the expected behavior **-DmyAgent="agent1;agent2"**
![image](https://user-images.githubusercontent.com/14052197/68463689-2a602180-024a-11ea-8867-162228eabe79.png)

When it's git bash, it escapes **-DmyAgent="agent1;agent2"** to **-DmyAgent=\\\"agent1;agent2\\\"**. This will make the original **;** inside the argument become a separator instead of a normal argument text. This is not expected.
![image](https://user-images.githubusercontent.com/14052197/68463912-9478c680-024a-11ea-9fd4-ad7be4413f9a.png)

What i expected is showing the argument as **-DmyAgent="agent1;agent2"** directly, because the terminal (such as cmd, git bash) supports this kind of argument format.

**Comment by clankill3r** [comment]
https://github.com/microsoft/vscode-java-debug/issues/707

**Comment by weinand** [comment]
@testforstephen does it work if you remove the extra quotes from `-DmyAgent="agent1;agent2"` and add a space, e.g.: `-DmyAgent=agent1; agent2`

**Comment by testforstephen** [comment]
It doesn't work in cmd and git bash. They will take `agent2` as a new argument.

**Comment by roblourens** [comment]
There were a bunch of changes to escaping, and if it still reproes, you can file an issue on the Java debug extension
