### ISSUE TITLE
Linux font rendering is blurry in 1.40.0

### ISSUE THREAD

**Issue by David-Else** [microsoft/vscode#84244]
Just creating a separate issue for the awful problem with fonts with Code 1.40.0 on Linux as there seems to be one for Mac and Windows. You can delete this if it is not necessary.

Here is the full report with a demo GIF in the Mac thread:

https://github.com/microsoft/vscode/issues/84154#issuecomment-551526708

**Comment by bpasero** [comment]
Actually merging this into: https://github.com/microsoft/vscode/issues/84214
