### ISSUE TITLE
October 2019 Recovery Endgame

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#84242]
- [x] Create a milestone `<Month> Recovery <year>` **owner**
- [x] Bump the version number **owner**
- [x] Include an issue 'update translations' **owner**
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Make rpm signing request **@RMacfarlane**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - @sbatten 
  - [x] OS X - @rebornix
  - [x] Linux - @RMacfarlane 
- [x] Sanity check of installable bits
  - [x] Windows 32 bit **owner**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit 
    - [x] signed installer 64-bit @mjbvz 
    - [x] signed user installer 64-bit @mjbvz 
    - [x] zip 64-bit @mjbvz 
  - [x] OS X - **owner**
  - [x] Linux
    - [x] deb package 64-bit **owner**
    - [x] rpm package 64-bit @RMacfarlane 
    - [x] archives **owner**
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Publish rpm to repository manually **@RMacfarlane**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z`

**Comment by Dean-NC** [comment]
Does this mean there will be an October release...like maybe 1.40?  When will that be?

**Comment by stefnotch** [comment]
@Dean-NC There was an October release a few days ago https://github.com/microsoft/vscode/issues/83503

**Comment by Dean-NC** [comment]
@stefnotch Thanks!

**Comment by chrmarti** [comment]
@Dean-NC This issue is tracking the work towards the 1.40.1 release which will add only critical fixes to 1.40.0.

**Comment by Dean-NC** [comment]
@chrmarti Thanks. I'm somewhat new to github, and the releases page was confusing to me, because I see 1.39.2 listed as the "latest release". I also see the 1.40 release above that, but I thought it might be beta. Anyway, I've installed the 1.40 and it's fine.

**Comment by mjbvz** [comment]
1.40.1 has shipped
