### ISSUE TITLE
Source control "Commit" doesn't work after 1.40v update

### ISSUE THREAD

**Issue by frezo00** [microsoft/vscode#84248]
Issue Type: <b>Bug</b>

Related issues: #83193 and #84201

After update to 1.40 version, the commit message starting with the **#** sign doesn't work inside the "Source control". I tried both the "check" icon and the "More options (...) -> Commit  Staged".

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

My user settings:
<details>
<summary>User Settings</summary>
{
  /* Editor settings */
  "editor.autoIndent": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": false
  },
  // "editor.fontSize": 14,
  // "editor.letterSpacing": 0.5,
  // "editor.lineHeight": 20,
  "editor.codeLens": false,
  "editor.cursorBlinking": "solid",
  "editor.cursorSmoothCaretAnimation": true,
  "editor.cursorStyle": "line",
  "editor.fontFamily": "Dank Mono, Operator Mono, Fira Code, Inconsolata, Menlo",
  "editor.fontLigatures": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": false,
  "editor.minimap.enabled": false,
  "editor.renderWhitespace": "none",
  "editor.tabCompletion": "on",
  "editor.tabSize": 2,
  "editor.wordWrap": "off",

  /* File settings */
  // "files.autoSave": "afterDelay",
  // "files.autoSaveDelay": 1000,
  "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true,
    "**/*.js": {
      "when": "$(basename).ts"
    },
    "**/*.js.map": {
      "when": "$(basename)"
    }
  },
  "files.hotExit": "onExit",
  "files.defaultLanguage": "typescript",
  "files.trimTrailingWhitespace": true,

  /* Prettier settings */
  "prettier.singleQuote": true,
  "prettier.printWidth": 100,

  /* Peacock settings */
  "peacock.affectActivityBar": true,
  "peacock.affectStatusBar": true,
  "peacock.affectTitleBar": false,
  "peacock.keepBadgeColor": false,
  "peacock.keepForegroundColor": false,
  "peacock.favoriteColors": [
    {
      "name": "Angular Red",
      "value": "#b52e31"
    },
    {
      "name": "Auth0 Orange",
      "value": "#eb5424"
    },
    {
      "name": "Azure Blue",
      "value": "#007fff"
    },
    {
      "name": "C# Purple",
      "value": "#68217A"
    },
    {
      "name": "Gatsby Purple",
      "value": "#639"
    },
    {
      "name": "Go Cyan",
      "value": "#5dc9e2"
    },
    {
      "name": "Java Blue-Gray",
      "value": "#557c9b"
    },
    {
      "name": "JavaScript Yellow",
      "value": "#f9e64f"
    },
    {
      "name": "Mandalorian Blue",
      "value": "#1857a4"
    },
    {
      "name": "Node Green",
      "value": "#215732"
    },
    {
      "name": "React Blue",
      "value": "#00b3e6"
    },
    {
      "name": "Something Different",
      "value": "#832561"
    },
    {
      "name": "Vue Green",
      "value": "#42b883"
    }
  ],
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "workbench.iconTheme": "material-icon-theme",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "git.autofetch": true,
  "window.zoomLevel": 1,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },

  /* Other settings */
  "material-icon-theme.folders.associations": {
    "directives": "ngrx-actions",
    "store": "ngrx-store",
    "actions": "ngrx-actions",
    "effects": "ngrx-effects",
    "reducers": "ngrx-reducer",
    "selectors": "ngrx-entities"
  },
  "breadcrumbs.enabled": false,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[less]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "svelte.language-server.runtime": "/usr/local/bin/node"
}

</details>

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_5162220|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Is #84201 affecting you?

**Comment by frezo00** [comment]
@gjsjohnmurray Yes it does, we have the same standard starting our commits with the #<story/task_number>. If this will be treated as a comment, then I'll use some other Git GUI.
