### ISSUE TITLE
Am unable to save new files in Vs code. How do I solve this error ?

### ISSUE THREAD

**Issue by Ericgacoki** [microsoft/vscode#84240]
Issue Type: **Performance Issue**

unable to write file.(No Permissions). EACCES permission denied.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 1904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|3.75GB (0.17GB free)|
|Process Argv|--force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	  2760	code main
    0	     8	  2762	   zygote
    0	   184	  2812	     window (Untitled-2 - Untitled (Workspace) - Visual Studio Code)
    0	    88	  2879	       extensionHost
    0	    23	  3193	         /snap/code/18/usr/share/code/code /snap/code/18/usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=2879
    0	    58	  2855	     shared-process
    0	     0	 12925	       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 12926	         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    88	 12900	     window (Issue Reporter)
    0	    12	  2805	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
emulate|Die|1.3.0
code-runner|for|0.9.14
vscode-javac|geo|0.2.28
python|ms-|2019.10.44104
cpptools|ms-|0.26.1

</details>

**Comment by alexandrudima** [comment]
@Ericgacoki I cannot reproduce. When I use VS Code on Linux I can write files. Please make sure you are attempting to write a file in a folder you have correct permissions for.
