### ISSUE TITLE
Scrolling down @popular extension viewlet rapidly shows many loading indicators

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8424]
#8215

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Is there a nicer way that loading could be indicated? It would look better with no indicator imo.

![image](https://cloud.githubusercontent.com/assets/2193314/16428338/4728c3d6-3d26-11e6-8880-42228be2ab8c.png)

**Comment by isidorn** [comment]
This is as designed by joao, leaving it for him and july for more comments

**Comment by joaomoreno** [comment]
No indicator? I'd just get another issue saying *why is this empty*?
