### ISSUE TITLE
Workspace folder names reset

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode#84241]
Issue Type: <b>Bug</b>

It seems you use the name property in a multi root workspace, when you click the folder in the explorer the name gets reset to the folder name.

Steps:
* Open multiroot workspace config and add names to folders and save
* Click on a root folder in the explorer
* Display name should reset

VS Code version: Code - Insiders 1.41.0-insider (fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347, 2019-11-08T05:26:43.949Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_426088|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by petval** [comment]
Also have this issue, happens with --disable-extensions too.

**Comment by IZEDx** [comment]
Same issue here. It's getting quite confusing now having workspaces point to different "src" folders.

**Comment by isidorn** [comment]
Thanks a lot for reproting this. Great catch!

**Comment by bm-stschneider** [comment]
you're welcome
