### ISSUE TITLE
the bugs for vscode_1.40

### ISSUE THREAD

**Issue by sundongwei** [microsoft/vscode#84252]
Issue Type: <b>Bug</b>

Sometimes, the code typed in jupyter notebook will auto-disappear on vscode 1.40

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2152)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.40GB (25.58GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.40.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
material-icon-theme|PKi|3.9.1
vscode-yaml|red|0.5.3

</details>

**Comment by alexandrudima** [comment]
Please report directly against https://github.com/microsoft/vscode-python
