### ISSUE TITLE
[json] make result limit configurable

### ISSUE THREAD

**Issue by zogga007** [microsoft/vscode#84259]
VSCode 1.40.0 introduced the resultLimit to json-language-features, which obviously breaks outline/breadcrumbs for large json files.
As it happens, we work with those and having an outline/breadcrumb trail of the current cursor position is critical.
I'd like to suggest to add this to the configuration, so the user can overwrite the default limit of 5000 symbols, if necessary.

**Comment by rlmcneary2** [comment]
I naively thought changing this existing setting would remove the symbol limit, it does not.
```
"[json]": {
    "editor.largeFileOptimizations": false
}

```

**Comment by aeschli** [comment]
There's now a setting `json.maxItemsComputed` to configure the limit.

**Comment by aeschli** [comment]
to verify: Use insider build from 2019-12-05

**Comment by sandy081** [comment]
I do not see this setting yet in today's build

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/70224742-1676e500-174e-11ea-9381-27cec251e037.png)

**Comment by sandy081** [comment]
There was no new insiders then and verified after getting new insiders.

**Comment by m1kkoh3** [comment]
How can I change the value of settings?

**Comment by aeschli** [comment]
@m1kkoh3 `Ctrl + ,` and use the settings UI  as showed in the screenshot above. Or use the Settings JSON editor and add `"json.maxItemsComputed": 5000`
