### ISSUE TITLE
The list.collapseAll keybinding stopped working after 1.40 version

### ISSUE THREAD

**Issue by in-in** [microsoft/vscode#84256]
- VSCode Version: 1.40 (1.41.0-insider)
- OS Version: Linux Mint 19.2

Steps to Reproduce:

1. Go to files Explorer and use `ctrl+leftArrow` keybinding
2. Nothing happens :man_shrugging: 

Keyboard Shortcuts say it should work

![193121573213178](https://user-images.githubusercontent.com/8797432/68474113-a69c3a00-0235-11ea-863f-567a09e924d1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
My bad.

Workaround until fix comes out: In keyboard shortcuts find `list.scrollLeft`, right click and select `Remove Keybinding`

Fix will also come soon on Insiders.
