### ISSUE TITLE
October update reverted back to "dull colors"

### ISSUE THREAD

**Issue by canpoyrazoglu** [microsoft/vscode#84257]
- VSCode Version: 1.40
- OS Version: macOS 10.15

Steps to Reproduce:

1. Open Vscode.
2. Open any file, check the colors.

A few months ago Vscode started to support wider-gamut colors which was a BIG visual improvement. After the auto-update (which I'll be rolling back to September version solely for this reason) it reverted back to old/dull colors that apparently ignores wide gamut.

**Comment by ajmalabu** [comment]
@canpoyrazoglu Is it just me, or does it look low-res to anyone? It looks blurry to me (the text especially) after the update to 1.40 on macOS 10.15.

**Comment by nodeful** [comment]
Same here. After updating to the October release the font colors became very dull. The font is also less sharp on Non-retina screens. I think VSCode stopped using native macOS font smoothing.
