### ISSUE TITLE
Extension debug: cannot set breakpoint at location

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84255]
Steps to Reproduce:

1. use macOS Code stable 1.40
2. open hello world extension
3. add usage of `vscode.env.asExternalUri`
4. F5 and step into

![before](https://user-images.githubusercontent.com/900690/68473752-17d2f180-0224-11ea-849e-0323d9a3a0db.gif)

I am not up to speed with sourcemaps, but a couple of changes that maybe are related?
* TS 3.7 update
* ES6 output (for VSCode core) since 1.39
* Terser (our minifier) update since 1.39

**Comment by roblourens** [comment]
I'm not going to mess with this in vscode-chrome-debug-core anymore, this works with vscode-pwa. I suspect that the strategy there is swapping this for other issues but we'll see.
