### ISSUE TITLE
Extension debugging broken in 1.41

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#84251]
* use this repo: https://github.com/microsoft/vscode-references-view
* make sure to have `eamodio.tsl-problem-matcher` installed
* press F5
* 🐛 nothing happens
* kill the task and confirm to start debugging
* 🐛 extension host not starting

This has been working yesterday with 1.40 and stopped working today with 1.41

**Comment by weinand** [comment]
Before installing "eamodio.tsl-problem-matcher":

What I did and what I'm seeing:

- "git clone https://github.com/microsoft/vscode-references-view"
- cd vscode-references-view
- npm install
- opened vscode-references-view in VS Code 
- F5 resulted in this:

![2019-11-08_13-17-20](https://user-images.githubusercontent.com/1898161/68476191-59ff3180-022a-11ea-8426-53f98b46193d.png)

![2019-11-08_13-17-27](https://user-images.githubusercontent.com/1898161/68476198-5d92b880-022a-11ea-9c59-11aa8af8bc86.png)

![2019-11-08_13-17-41](https://user-images.githubusercontent.com/1898161/68476205-61bed600-022a-11ea-9755-3fc50efa3d78.png)

- after dismissing the error dialogs and pressing F5 again, the extension launched fine.

Then I installed "eamodio.tsl-problem-matcher".

- F5 started a debug session but no VS Code window opens.

After disabling  the debug configuration "preLaunchTask" debugging seems to work fine again.

@alexr00 something seems to have changed in task land.
