### ISSUE TITLE
Different thickness of icons in the sidebar (Win vs Ubutnu & Mac)

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#84266]
- VSCode Version:
```
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```
- OS Version:
```
Win 10 1903
```

#### Steps to Reproduce:

I found this problem with the guys from the [TodoTree ](https://github.com/Gruntfuggly/todo-tree) plugin, when we talked about changing the plugin icon
Basically VSCode icons at sidebar have a different thickness on Windows (on Ubuntu and Mac works fine)
To get details please see this ticket https://github.com/Gruntfuggly/todo-tree/issues/243 - there we talk about it and compare screens

**Comment by misolori** [comment]
Please see https://github.com/microsoft/vscode/issues/83316
