### ISSUE TITLE
Make the filename sticky in search results across multiple files

### ISSUE THREAD

**Issue by waldyrious** [microsoft/vscode#84260]
When searching for a pattern that matches the content of multiple files, the search result panel will display a tree widget where each result is nested under a header for the file it belongs to. For files with lots of matches, the header can easily be scrolled out of view before we get to the end of the list of matches.

This request is to make the file name stick to the top of the list view until the last of its matches scrolls out of view. A good example of this behavior is how file headers on GitHub PRs are kept sticky when scrolling through the diff with many files.

**Note:** I'm aware of a similar issue requesting this functionality for the explorer sidebar (#54206), but I imagine that can be harder to implement due to multiple nesting levels. Hopefully in the search panel it's easier since there's always only one level of nesting.

**Comment by roblourens** [comment]
This is essentially the same as https://github.com/microsoft/vscode/issues/54206 (and search will get an option to nest results in folders), have to close as a duplicate, sorry
