### ISSUE TITLE
window.activeBorder should not show the border when application is maximized

### ISSUE THREAD

**Issue by stepanhakobyan** [microsoft/vscode#84267]
Issue Type: <b>Bug</b>

On Windows 10 the border for applications are not shown when they are maximized.
When setting the new `window.activeBorder` setting in settings.json the border for VSCode window becomes visible.

After that 
1. I cannot close window when moving the mouse cursor to top right pixel of the screen.
2. I cannot move the window while trying to grab from top pixel.

![image](https://user-images.githubusercontent.com/26157959/68479995-1f5ac080-024d-11ea-94c8-395ab25d2f2b.png)

Steps to Reproduce:

1. window.activeBorder in settings.json
2. Maximize VSCode
3. Move mouse cursor to top right pixel.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.0
gitstash|art|3.1.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
githistory|don|0.4.6
gitlens|eam|10.1.2
vscode-npm-script|eg2|0.3.9
file-icons|fil|1.0.19
vscode-pull-request-github|Git|0.12.0
rest-client|hum|0.22.2
reg|ion|1.0.1
vsclassic-icon-theme|jez|1.2.1
vscode-icon-theme|jtl|1.6.5
typescript-auto-compiler|mor|0.7.0
mssql|ms-|1.7.0
remote-wsl|ms-|0.40.2
cpptools|ms-|0.26.1
csharp|ms-|1.21.6
powershell|ms-|2019.11.0
vs-keybindings|ms-|0.2.0
team|ms-|1.161.0
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
vba|spe|1.2.0

(1 theme extensions excluded)

</details>

**Comment by chenxuuu** [comment]
same problem, when I close vscode, it always be resized

----

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
blamer-vs|bea|0.5.0
luatcode|che|0.19.0
vscode-markdownlint|Dav|0.31.2
xml|Dot|2.5.0
gitlens|eam|10.1.2
vscode-power-mode|hoo|2.2.0
diff-tool|jin|0.0.1
svn-scm|joh|2.0.1
vscode-language-pack-zh-hans|MS-|1.40.2
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
csharp|ms-|1.21.6
vsliveshare|ms-|1.0.1123
indent-rainbow|ode|7.4.0
sharecode|Rol|0.4.1
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.7.2
lua|sum|0.13.1


</details>
