### ISSUE TITLE
Cyrillic symbols are rendered too bold in Minimap

### ISSUE THREAD

**Issue by ornic** [microsoft/vscode#84264]
- VSCode Version: 1.40.0 user setup
- OS Version: Win10 x64 10.0.18362

Steps to Reproduce:

1. Enable Minimap with enabled Render actual characters
2. Open any file with non-latin (for example - cyrllic) letters

![image](https://user-images.githubusercontent.com/3350070/68479737-187b8000-0244-11ea-8a2c-8f2471391f19.png)

#84226 may be a duplicate, but I suppose this should be cosidered as regression bug, not feature request, since there were no such problems in previous version.

**Comment by alexandrudima** [comment]
The same problem existed before, just before you could not scale so much as to be able to see it :D.

Let's track in #84226 since all non-latin characters are rendered with the unicode replacement character

**Comment by ornic** [comment]
@alexandrudima I can't agree with you :)

Before upgrading to 1.40.0:
![image](https://user-images.githubusercontent.com/3350070/68482597-fa654e00-024a-11ea-8df8-04e23d0a06e1.png)

After upgrading:
![image](https://user-images.githubusercontent.com/3350070/68482635-0e10b480-024b-11ea-91fe-76a57cf08785.png)

for me the diffrerence is very huge and clearly visible, Minimap for any file with partial non-latin characters looks awful now.

Real life example:

Before:
![image](https://user-images.githubusercontent.com/3350070/68482801-5f20a880-024b-11ea-902a-a77766e25e8a.png)

After:
![image](https://user-images.githubusercontent.com/3350070/68482755-46b08e00-024b-11ea-9b1b-3181dff66663.png)
