### ISSUE TITLE
Help - display on examples

### ISSUE THREAD

**Issue by amitjslearn** [microsoft/vscode#84262]
- VSCode Version: 1.40 (code_1.40.0-1573064499_amd64)
- OS Version: Ubuntu 18.04.3 LTS
- python
Steps to Reproduce:

1. Hover the mouse pointer over a function
2. Scroll down to the examples
![full hover](https://user-images.githubusercontent.com/27467368/68479296-00156080-0258-11ea-9ca2-c7e8f5eb3d8c.png)
when typed help(function_name) in Ipython
![ex-help](https://user-images.githubusercontent.com/27467368/68479288-fd1a7000-0257-11ea-9cff-bb261deeb8bb.png)

Does this issue occur when all extensions are disabled?: Yes/No - extension doesn't matter I think.

**Comment by alexandrudima** [comment]
Can you please create the issue directly against the extension at https://github.com/microsoft/vscode-python

**Comment by amitjslearn** [comment]
> Can you please create the issue directly against the extension at https://github.com/microsoft/vscode-python

Okay done.
