### ISSUE TITLE
Git: Support ignoring comments out of a restored commit template file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84274]
From @gaetawoo at https://github.com/microsoft/vscode/issues/81569#issuecomment-551365295

**Comment by joaomoreno** [comment]
Setting is `git.restoreCommitTemplateComments`

**Comment by joaomoreno** [comment]
@gaetawoo I will have to revert this setting. I can no longer respect comments in the input box. The input box will be taken literally until further work.

**Comment by gaetawoo** [comment]
@joaomoreno wow... I was gonna be sad and then I read all those other issues and though... my usecase isn't _that_ big of a problem. Lol. 

But I do agree with one of the last commenters saying that it should just be a basic text input taken literally... and should NOT use the git message template as a starting point. That's how it was forever, and it seems like me and others liked it that way. Just ignore the git template for that box. It's too small a box for the template to be useful anyway to my mind, and it's not monospaced, etc.. it's not a text editor.
