### ISSUE TITLE
Feature request: Right-click on docker-compose.yml -> Compose Up and Attach

### ISSUE THREAD

**Issue by arniwesth** [microsoft/vscode#84275]
## Current version
Visual Studio Code: 1.40.0-insider

## Feature request:
Currently: Right-click on docker-compose.yml -> Compose Up -> Navigate to Docker extension -> Find and right-click on the container just launched -> Attach Visual Studio Code

Suggestion: Right-click on docker-compose.yml -> Compose Up and Attach

Result should be the same. I do almost all development inside containers these days and anything that can ease the process is greatly appreciated.

**Comment by IllusionMH** [comment]
This functionality is provided by 2 extensions: Docker or Remote - Containers.
Most likely you should make this request in https://github.com/Microsoft/vscode-remote-release repo

**Comment by arniwesth** [comment]
Done
