### ISSUE TITLE
Lines containing spaces should be handled the same no matter where in a file

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8427]
Testing #8232. Create a simple file without any file extension.

In the following picture all green areas are showing lines that only contain whitespace characters.  I can come up with rules why indentation guides are shown the way they are but I think all non-empty lines (including those containing whitespace only) should be handled the same no matter where they are in a file. I.e. the context of  the line should be ignored.

<img width="557" alt="screen shot 2016-06-28 at 11 48 50 am" src="https://cloud.githubusercontent.com/assets/4674940/16428415/a7ae37c2-3d26-11e6-8805-b83a40a1772c.png">

**Comment by alexandrudima** [comment]
@kieferrm 
The indent guides use 100% the folding regions. I have just pushed a change that improves whitespace-only or empty lines:

This is the new rendering:
![image](https://cloud.githubusercontent.com/assets/5047891/16450215/3d9212e2-3dfc-11e6-8b82-6d78eeff99ff.png)

My change also makes it that the indent guides respect 100% the folding regions -- you can inspect this by hovering over the line decorations area between the line numbers and the content and the folding regions should reflect the indent guides.

I don't know why we don't create a folding region for the last lines in the file. @aeschli here is a copy-paste friendly version of Kai's screen shot:

```

	indent1
		indent2
		indent2
	indent1

          

indent0
	indent1

 indent 0.5
				 
	             
                  

indent0
	indent1
	indent1
	                



indent0
                    
		


      



	  
```

**Comment by alexandrudima** [comment]
@aeschli Here is where I moved your code that computes folding regions:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/indentRanges.ts#L32

**Comment by aeschli** [comment]
@alexandrudima A folding region only exists if there it at least one non empty line that has a larger indent than a non-empty line before

```
line 1

line 2

```
does not have any folding regions. Think of code like
```
console.log('hello');

console.log('world');

```
line 1

line 2
  line 3

```
has one folding region at line 2 (ending at the end of the file).

IMO from the perspective of folding regions the algorithm does the right thing.

**Comment by alexandrudima** [comment]
Closing as per Martin's explanation
