### ISSUE TITLE
Add "x" to remove a file from recently opened (quick pick)

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#84271]
The **File: Open Recent...** command has a convenient way to remove items from recent history:

![Screenshot 2019-11-08 at 15 11 49](https://user-images.githubusercontent.com/101152/68482617-3fcd4f80-023a-11ea-8334-58a3442fb484.png)

It would be great to have the same UI in the quick pick UI / recently opened files:

![Screenshot 2019-11-08 at 15 13 52](https://user-images.githubusercontent.com/101152/68482733-7a36ec80-023a-11ea-851f-5252d1146086.png)

A workaround is to open a file and run the **Remove From History** command, but it's not that intuitive, IMO.

---

Previous mention of this (from 2016): https://github.com/Microsoft/vscode/issues/3260#issuecomment-239730713

**Comment by Wowol** [comment]
If we want this feature, I can develop this @chrmarti

**Comment by chrmarti** [comment]
We still want to remove the old QuickOpen widget and have QuickOpen use the newer QuickInput widget. That's why we are reluctant to add features here.

**Comment by bpasero** [comment]
The new quick access handler adds the "X" to the right hand side to allow to quickly remove history entries:

![image](https://user-images.githubusercontent.com/900690/76947603-27ff8980-6906-11ea-9ab9-e1957de0926e.png)

**Comment by adelineu** [comment]
This update removed the "Remove from history" command?

**Comment by bpasero** [comment]
@adelineu yeah that is actually true, I should have documented that in the release notes.

**Comment by adelineu** [comment]
@bpasero Shouldn't that feature be optional?  I already miss it.

**Comment by bpasero** [comment]
Can you explain how the current (new) way of removing entries does not work for you?

**Comment by adelineu** [comment]
@bpasero It's about speed and "muscle memory". By writing something like "rem" in that input and selecting that command to remove a specific item it feels faster for me. Also, that command gets stashed into the recent used commands and in the end I don't even need to type "rem".
I also don't use a mouse or the pad that much. The list elements and the X is too small, it needs a level of precision and it makes it easier to remove the wrong item.

**Comment by bpasero** [comment]
The X is keyboard accessible though when you Tab. I think the new model works better:
* you search something
* you see something you don't like
* you can tab to the X

Related, I am was actually thinking of introducing a new command to remove an entry from the picker (if supported). Basically a way to trigger the X with a keyboard shortcut.

**Comment by thw0rted** [comment]
Chrome uses Shift+Delete to remove entries from a suggestion list and IMHO it should be a standard everywhere.

**Comment by borekb** [comment]
> Chrome uses Shift+Delete to remove entries from a suggestion list and IMHO it should be a standard everywhere.

That's a nice suggestion, I like it. (On macOS, it's Fn+Shift+Backspace as Fn+Backspace mean "delete".)

**Comment by bpasero** [comment]
Sounds good, can someone suggest this as new feature request.

**Comment by thw0rted** [comment]
I filed #92358 but it got closed as a duplicate.

**Comment by bpasero** [comment]
Ok I renamed and reopened that issue.
