### ISSUE TITLE
support read-only settings files

### ISSUE THREAD

**Issue by hyperfekt** [microsoft/vscode#84270]
Steps to Reproduce:

1. make sure the `settings.json` file is read-only
2. take an action that attempts to modify the settings file (like zooming)
3. observe the error
```
Failed to save 'settings.json': Unable to write file (Unknown (FileSystemError): Error: EROFS: read-only file system, open '/home/[username]/.config/Code/User/settings.json')
```
3. try to take another action that attempts to modify the settings file (like zooming again)
4. observe it not have an effect and show the error
```
Unable to write into user settings because the file is dirty. Please save the user settings file first and then try again.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by NotWearingPants** [comment]
This is very useful for users who keep the settings.json in a dotfiles git repo, and don't want vscode to change the settings without intending, so they need to be able to make it read only.

**Comment by sandy081** [comment]
It is not designed to make settings read only and it is required to be updatable for lot of functions. So I do not think this feature can be provided.
