### ISSUE TITLE
Shortcuts with missing when conditions in 1.40

### ISSUE THREAD

**Issue by SurgeS** [microsoft/vscode#84279]
Issue Type: <b>Bug</b>

Some key sequence shortcuts do not have when condition defined. This causes problems in integrated terminal since vscode is _"Waiting for second key of chord..."_ and shortcut in the terminal is not executed.

**Expected behaviour**
1. run the `git rebase -i` command in integrated terminal (for example)
2. press any of the suggested shortcuts, for example `Ctrl + K` to delete a line
3. line is deleted

**Actual behaviour**
After user presses `Ctrl + K` nothing happens and vscode is _"Waiting for second key of chord..."_

**Partial workaround**
I've added `!terminalFocus` to a few keybindings but I'm sure I'll come across more while using more shortcuts in terminal and editing each one is really tedious.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: 1.40, 1.41.0-insider 
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2468)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|23.31GB (9.06GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**EDIT**
So apparently this is a feature [Chords are now supported by default](https://code.visualstudio.com/updates/v1_40#_chords-are-now-supported-by-default) but I still think that shortcuts unrelated to terminal should have proper `when` definitons or this feature should be turned off by default.

**Comment by Tyriar** [comment]
It's not as simple as just checking `when` unfortunately as only the highest-priority keybinding is checked. What you're seeing is as designed and you can get your flow working by setting allowChords to false.
