### ISSUE TITLE
Changing a single character hides or shows indentation guides in unpredictable way

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8428]
Testing #8232. Create a simple file without any file extension. See before and after.

Before:
<img width="680" alt="screen shot 2016-06-28 at 11 57 02 am" src="https://cloud.githubusercontent.com/assets/4674940/16428729/0a1b3af8-3d28-11e6-9aa7-4b83a08dba1e.png">

After:
<img width="492" alt="screen shot 2016-06-28 at 11 44 38 am" src="https://cloud.githubusercontent.com/assets/4674940/16428708/f471d8d8-3d27-11e6-9329-06739606f620.png">

**Comment by alexandrudima** [comment]
Same as #8427 , the indent guides now reflect the folding regions

@aeschli see copy-paste friendly version in the comments of #8427

**Comment by alexandrudima** [comment]
It might be on my side, it is not clear to me how these indent guides should be rendered in this case. I am unsure if there is a "correct" way

**Comment by alexandrudima** [comment]
IMHO not a blocker

**Comment by alexandrudima** [comment]
This has been fixed ~1 or 2 months ago.
