### ISSUE TITLE
Make "editor.codeActionsOnSave" a resource setting

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#84288]
Currently the setting `"editor.codeActionsOnSave"` is not defined as a resource setting and therefore can't be overriden on a folder level.

However to migrate existing willSave handlers to code actions on save it would be very helpful if the setting can be overridden on a folder level as well. Then for ESLint I would add something like this to the settings:

```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}
```

which will enable source fix all for eslint. 

Without this I need to tell users that they have to maintain to settings one eslint specific and the `"editor.codeActionsOnSave"` to enable / disable this.

**Comment by dbaeumer** [comment]
More background: I wanted to use this setting to allow users to configure whether eslint auto fix on save is enabled or not. I can easily see use cases where this is enabled for eslint for a workspace folder A but disabled for a workspace folder B. This is currently supported for the eslint specific setting `eslint.autoFixOnSave` which I wanted to migrate to the new `editor.codeActionsOnSave`.

**Comment by dbaeumer** [comment]
Actually the setting is read here: 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/browser/mainThreadSaveParticipant.ts#L260

So I think it would make perfect sense to declare the settings as a resource setting since it is always read relative to a resource.

@mattbierner any objection if I change this in VS Code source code.

**Comment by mjbvz** [comment]
No, I think this was just an oversight. Making it a resource setting sounds good

**Comment by dbaeumer** [comment]
Thanks for addressing this so quickly.
