### ISSUE TITLE
Automatic Scrolling Icon Not Intuitive

### ISSUE THREAD

**Issue by DonaldTrumpFR** [microsoft/vscode#84282]
The current icon for automatic scrolling (a lock) in the terminal is not intuitive. In fact, at the beginning i was thinking that the feature was missing.
An icon such as an arrow with the word Auto would be clearer.

**Comment by Tyriar** [comment]
This is talking about output, not terminal.

**Comment by sandy081** [comment]
This has been there from the beginning and no complains were seen. @misolori assigning to you if you have better icon otherwise feel free to close it.
