### ISSUE TITLE
Error installing intellisense

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#84286]
Acquiring model 'intellisense-members' for sql

Querying IntelliCode service for available models.

Downloading model.

Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C?sv=2018-03-28&sr=b&sig=GIGFIk4EHcECFvzpKAEEqJIBadDRD7HHEOwQ%2BJrPtmw%3D&se=2019-11-08T16%3A48%3A06Z&sp=r

Download complete.

vs-intellicode-SQL was passed a model: {"modelPath":"c:\\Users\\BRITTG2\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.2.0\\cache\\99136CA159AB897D942412E976015B8C9EC2_6D6727BA7E6347BE9124EF572943AC5C","modelId":"99136CA159AB897D942412E976015B8C9EC2","outputId":"6D6727BA7E6347BE9124EF572943AC5C"}.

Error while activating SQL: {"pkg":{"installPath":"c:\\Users\\BRITTG2\\.vscode\\extensions\\ms-mssql.mssql-1.7.0\\sqltoolsservice\\1.7.0\\Windows","url":"https://download.microsoft.com/download/c/2/f/c2f482e1-ceb3-4f6a-a8b7-1f8115fc0a44/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.2.zip","tmpFile":{"name":"C:\\Users\\BRITTG2\\AppData\\Local\\Temp\\package-7156MZ2oUHUqE8m5.tmp","fd":4}},"innerError":{"code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}}

 

 

CPUs | Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)

-- | --

GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled

Load (avg) | undefined

Memory (System) | 31.84GB (16.05GB free)

Process Argv |  

Screen Reader | no

VM | 0%

 

 

Extension | Author (truncated) | Version

-- | -- | --

xml | Dot | 2.5.0

gitlens | eam | 10.1.2

code-runner | for | 0.9.14

code-groovy | mar | 0.1.2

mssql | ms- | 1.7.0

python | ms- | 2019.10.44104

csharp | ms- | 1.21.6

powershell | ms- | 2019.11.0

gradle-language | nac | 0.2.3

java | red | 0.52.0

partial-diff | ryu | 1.4.0

jenkinsfile-support | sec | 0.1.0

vscode-hexdump | sle | 1.7.2

vscodeintellicode | Vis | 1.2.0

vscode-java-debug | vsc | 0.23.0

vscode-java-dependency | vsc | 0.6.0

vscode-java-pack | vsc | 0.8.0

vscode-java-test | vsc | 0.21.0

vscode-maven | vsc | 0.19.1

**Comment by alexandrudima** [comment]
Can you please open an issue directly against the extension at https://github.com/microsoft/vscode-mssql
