### ISSUE TITLE
'import sitecustomize' failed; use -v for traceback

### ISSUE THREAD

**Issue by Matt-Gleich** [microsoft/vscode#84289]
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Run `code` command to open a folder

**THIS ERROR IS NOW A PROBLEM BECAUSE I SWITCHED TO ZSH FROM BASH**

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
What does `which code` return? Did you run `Shell Command: Install 'code' command in PATH`?

**Comment by Matt-Gleich** [comment]
@joaomoreno 
This is the output of the `which code` command:
```
/usr/local/bin/code
```

**Comment by joaomoreno** [comment]
What does `ls -la /usr/local/bin/code` return?

**Comment by Matt-Gleich** [comment]
The output of `ls -la /usr/local/bin/code` is:
```
lrwxr-xr-x  1 matthewgleich  admin  68 Nov  8 19:28 /usr/local/bin/code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
```

**Comment by joaomoreno** [comment]
Can you show me a **screenshot** of the error?

**Comment by Matt-Gleich** [comment]
<img width="1440" alt="Screen Shot 2019-11-14 at 7 26 04 AM" src="https://user-images.githubusercontent.com/43759105/68857087-0ff5d000-06b0-11ea-8ab1-47212f4f50d8.png">

**Comment by joaomoreno** [comment]
I really don't know where that comes from. We don't have that string in our sources. Not sure how I can help here.
