### ISSUE TITLE
Cursor is not visible, lines have become un-selectable, terminal invisible, etc.

### ISSUE THREAD

**Issue by plibither8** [microsoft/vscode#84285]
- Version: 1.40.0
- Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
- Date: 2019-11-06T18:14:08.920Z
- Electron: 6.1.2
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Linux x64 5.0.0-31-generic (Ubuntu 18.04)

Steps to Reproduce:

1. Open any file on VS Code
2. Try editing content

Does this issue occur when all extensions are disabled?: **Yes**

**More info:**

* The text in the editor cannot be selected
* I cannot see the cursor in the editor anymore
* The text in the lines seem "shifted" upwards
* Menu items don't respond to hover (styles don't change)
* Can't see anything in the terminal - whatever I'm typing is invisible

This is a small summary of the various issues I'm facing currently. These issue started today, right after the automatic update to the VS Code October 2019 version. I tried to downgrade to the September version but the issue persists there too.

I have tried uninstalling and reinstalling Code, rebooting my system and looked through all issues on GitHub. Nothing seems to work. Any ideas?

**Screencaps:**

![code](https://user-images.githubusercontent.com/31861755/68494110-d79b5f80-0273-11ea-8054-ca531f3a1e1b.gif)

![image](https://user-images.githubusercontent.com/31861755/68494139-e5e97b80-0273-11ea-8a0c-c43198ea302f.png)

**Comment by alexandrudima** [comment]
@plibither8 Can you please try some of the following:
- commenting out your settings.json
- disabling all extensions
- reinstalling VS Code

**Comment by plibither8** [comment]
Beautiful! Commenting out my `settings.json` did the trick. I'll look into which setting in particular is messing around with the UI. Thanks :)

**Comment by plibither8** [comment]
Was a problem with `editor.fontFamily`. "Fixed" an invalid font and everything seems to work perfectly now. Thank you
