### ISSUE TITLE
MAC java plugin error

### ISSUE THREAD

**Issue by Mon-ius** [microsoft/vscode#84287]
Every time I run the java from vscode "Run| Debug" button.

it will give 

`prompt_ip:8: command not found: networksetup                                                                                                                     
prompt_load:29: command not found: sysctl
prompt_load:31: command not found: sysctl
prompt_load:44: bad math expression: operand expected at `* 0.7'
` following the result.

It looks that it will run the ` /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 @/var/folders/9m/wk4wyf8n6_s6fhryl541tp9w0000gn/T/cp_7casio0lyeeq4l687bbee3z8n.argfile`

which cause the problem. 

Does anyone ever met the same problem like me?

**Comment by alexandrudima** [comment]
Can you please open an issue directly against https://github.com/redhat-developer/vscode-java
