### ISSUE TITLE
Builtin Git is not working

### ISSUE THREAD

**Issue by mpoeckl** [microsoft/vscode#84291]
Issue Type: <b>Bug</b>

There is no "Initialize Repository" command/button available in the VS Code Source Control Window. Executing the command "Git: Initialize Repository" raises the following error: `Command "Git.init" not found`. The builtin Git Extension is enabled (disable/enable/restart did not help).

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.22.2
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.20.0
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.0
python|ms-|2019.10.44104
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cpptools|ms-|0.26.1
vscode-node-azure-pack|ms-|0.0.10
azurerm-vscode-tools|msa|0.8.1
azure-iot-edge|vsc|1.18.0
azure-iot-toolkit|vsc|2.12.0
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.2.27
vscode-iot-device-cube|vsc|0.1.4
vscode-iot-workbench|vsc|0.10.16

</details>

**Comment by gjsjohnmurray** [comment]
is Git installed on this machine?

From https://code.visualstudio.com/docs/editor/versioncontrol#_git-support

> Note: VS Code will leverage your machine's Git installation, so you need to install Git first before you get these features. Make sure you install at least version 2.0.0.

**Comment by mpoeckl** [comment]
Git was not installed... I reset my development virtual machine to an earlier checkpoint and obviously Git was not installed yet. Re-installing Git solved the issue!
