### ISSUE TITLE
Notebook implementations analysis and exploration

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#84293]
There are now quite a few notebook like features contributed by extensions, which usually leverage Web View API and Monaco Editor. We may want to look into what we can do from the core side to improve the user and/or development experience for notebooks.

*--Update--*

To track the analysis of different existing notebook implementation, we put the samples and benchmarks in a dedicated repository [rebornix/notebook-test](https://github.com/rebornix/notebook-test), which consists of following content

* [x] Python notebook 
  * [x] [Samples](https://github.com/rebornix/notebook-test/tree/master/python/samples)
  * [x] [Technical details](https://github.com/rebornix/notebook-test/tree/master/python#technical-details)
  * [x] [Benchmark](https://github.com/rebornix/notebook-test/issues/1)
* [x] Azure Data Studio notebook
  * [x] Samples
  * [x] Technical details
  * [x] Benchmark

**Comment by mytototo** [comment]
Isn't it possible to make the notebook awesome integration and database connection of Azure Data Studio available in VS Code ?

Currently I'm using both apps because the database connection and notebook support is really great on Azure Data Studio and I was looking for a unique solution coupling both worlds.

**Comment by rebornix** [comment]
@mytototo thanks for your feedback.

> Currently I'm using both apps because the database connection and notebook support is really great on Azure Data Studio and I was looking for a unique solution coupling both worlds.

The short answer for it is no at this moment. We are at still at the very early stage and trying to figure out what we can do to enable extensions to implement notebooks in VS Code. We can have better answers for you once we finish this task.
