### ISSUE TITLE
Updater fails with unhelpful message

### ISSUE THREAD

**Issue by angusgraham** [microsoft/vscode#84298]
See image.
No indication as to which file failed.
As you can see VS Code is not running.
<img width="375" alt="Capture" src="https://user-images.githubusercontent.com/11641291/68499594-683f5480-020e-11ea-8d30-8b067a746e41.PNG">

**Comment by joaomoreno** [comment]
@angusgraham Did you install the User Setup or System Setup? Under which directory did you install?

**Comment by angusgraham** [comment]
Hi Joao,
I wasn't running setup, this happened when VSCode tried to update itself.

**Comment by joaomoreno** [comment]
I meant: when you installed VS Code.

**Comment by angusgraham** [comment]
Code.exe is in C:\Program Files\Microsoft VS Code
Not sure about User Setup vs System Setup. I imagine I would have installed for all users if given the option, so System Setup I guess?

**Comment by joaomoreno** [comment]
Can you fully uninstall VS Code and reinstall it? https://code.visualstudio.com/docs/?dv=win64

**Comment by angusgraham** [comment]
I don't get why this issue is closed. Even if I were to reinstall VS and even if that made the error go away it wouldn't change the fact that the error message the next time it appears for someone would still be unhelpful - it doesn't tell you what file is causing the issue or what log to look in to find that out.
