### ISSUE TITLE
Data breakpoints break Exception breakpoints

### ISSUE THREAD

**Issue by hbenl** [microsoft/vscode#84295]
- VSCode Version: 1.40.0
- OS Version: Arch Linux (64bit)

I am developing a [debug adapter](https://github.com/firefox-devtools/vscode-firefox-debug/) that supports data breakpoints. Recently, this debugger breaks on exceptions even though I have all exception breakpoints disabled in the UI. I found out that if my adapter tells VS Code that it supports data breakpoints (`supportsDataBreakpoints: true` in the `InitializeResponse`) then VS Code will **not** send the initial `setExceptionBreakPointsRequest`, so my debug adapter doesn't know that I want exception breakpoints to be disabled.

**Comment by hbenl** [comment]
This is not a duplicate of any of the listed issues.

**Comment by hbenl** [comment]
I just checked with 1.39 and found that this issue is indeed new in 1.40.

**Comment by isidorn** [comment]
@hbenl can you please F1 > developer tools > put a breakpoint [here](https://github.com/Microsoft/vscode/blob/f0f6c8dc4ceda13c9e935895ead2538dff352641/src/vs/workbench/contrib/debug/browser/debugService.ts#L995)
And try to investigate what is going on.
What could be happening is that when sending initial data breakpoint an error is thrown and due to that, exception breakpoints do not get sent initialy.
Also do you see some errorr in the F1 > developer tools > console?

Thanks!

**Comment by hbenl** [comment]
@isidorn thanks, I saw an error in the console that told me what was happening: VS Code sends an empty `setDataBreakpoints` request during initialization which I didn't expect - it confuses my adapter and it replies with an error response. That is turned into an exception in VS Code which aborts the initialization process, hence no `setExceptionBreakpoints` request.
I will fix my adapter to not send an error response for this request, but I think VS Code should also be fixed to handle error responses during initialization more gracefully. I would expect that error responses during initialization should have the same effect as after initialization: the error is shown to the user and the debugger carries on.

**Comment by isidorn** [comment]
@hbenl thanks for providing more details. Agree, we can handle errors more gracefully.

**Comment by isidorn** [comment]
I have pushed a change that even on an error in the initialisation breakpoint phase we continue with the initialisiation
