### ISSUE TITLE
Support real Integration/UI Tests

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#8430]
I was looking into the extension `vscode-api-tests`, this seems to be a very limited integration test suite for vscode.  It doesn't look like there is any harness or way to do more advanced integration tests, for example clicking items in the UI.

Is there plans for this or what are your thoughts on expanding the integration test framework?

**Comment by bpasero** [comment]
Currently no plans, but we can use this item as discussion place for people.

**Comment by jsloyer** [comment]
My suggestion would be building a framework around Selenium that tests UI behavior.

**Comment by mjbvz** [comment]
I believe this is now covered by our automated smoke tests: https://github.com/Microsoft/vscode/wiki/Smoke-Test
