### ISSUE TITLE
Terminal open/cd failure when path contains '[' and ']'

### ISSUE THREAD

**Issue by AntonKhurs** [microsoft/vscode#84305]
- VSCode Version: 1.39.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with brackets in the path (for me it was 'something/[PROD]ProjectName')
2. See the terminal opened for 'PS C:\Windows\System32\WindowsPowerShell\v1.0>'
3. 'cd' command doesn't help and shows error:
```
cd : Cannot find path 'D:\work_folder\[PROD]ProjectName' because it does not exist.
At line:1 char:1
+ cd 'D:\work_folder\[PROD]ProjectN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\work_folder\...tName) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```

**Comment by asim-rehman** [comment]
> * VSCode Version: 1.39.2
> * OS Version: Windows 10
> 
> Steps to Reproduce:
> 
> 1. Open a folder with brackets in the path (for me it was 'something/[PROD]ProjectName')
> 2. See the terminal opened for 'PS C:\Windows\System32\WindowsPowerShell\v1.0>'
> 3. 'cd' command doesn't help and shows error:
> 
> ```
> cd : Cannot find path 'D:\work_folder\[PROD]ProjectName' because it does not exist.
> At line:1 char:1
> + cd 'D:\work_folder\[PROD]ProjectN ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (D:\work_folder\...tName) [Set-Location], ItemNotFoundException
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
> ```

This is not a bug of VSCode, this is standard behavior of Powershell, has problems with special characters in folder names, you need to use escape characters, so it would be like this:

> D:\work_folder\``[PROD``]ProjectName

The two back ticks are escape characters in VSCode.

**Comment by AntonKhurs** [comment]
yes, after googling a bit I found that this is kind of common issue with brackets in path. But it is strange. I've opene vscode now and this time its okay, terminal is opened with correct directory.
