### ISSUE TITLE
Identify design inconsistencies with UI + JSON expriences

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#84309]
## Overview
This issues is to cover the various experiences where we have a rich editing experiences (UI) and a  text based configuration (JSON). Some of these experiences have overlap while others have gaps that we'd like to be covered. Below is a list of areas where we have these experience with a list of features that are either missing or need better coverage.

- [x] Settings
- [x] Keybindings
- [x] Snippets
- [x] Extensions

### UI
- Objects
  - `files.associations`
  - `emmet.includeLanguages`
  - `editor.codeActionsOnSave`
  - `editor.quickSuggestions`
  - `editor.tokenColorCustomizationsExperimental`
  - `terminal.integrated.env.linux`
  - `terminal.integrated.env.osx`
  - `terminal.integrated.env.windows`
  - `remote.extensionKind`
  - `sync.ignoredSettings`
  - `emmet.syntaxProfiles`
  - `emmet.variables`
- Nested Objects
  - `editor.tokenColorCustomizations`
  - `workbench.colorCustomizations`
  - `workbench.experimental.editorAssociations`
  - `launch`
  - `extensions.confirmedUriHandlerExtensionIds`
  - `workbench.experimental.editorAssociations`
  - `remote.extensionKind`
- Arrays
  - `editor.rulers`
- Boolean or Strings
  - `editor.fontLigatures`
- Inputs
  - `terminal.integrated.automationShell.linux`
  - `terminal.integrated.automationShell.osx`
  - `terminal.integrated.automationShell.windows`

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35271042/68499694-a9cfff80-020e-11ea-8ec4-7d166c9646d5.png">

### JSON
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35271042/68499698-ae94b380-020e-11ea-9f87-6fbc56925a4a.png">

### UI
- IntelliSense for `when` clause
- Sorting columns
- Reset keys recorder

![image](https://user-images.githubusercontent.com/35271042/74571155-4c94ca00-4f32-11ea-9fd6-af575565c27e.png)

### JSON
![image](https://user-images.githubusercontent.com/35271042/74571136-47377f80-4f32-11ea-8500-5749eb479843.png)

### UI
- Configuring snippets

![image](https://user-images.githubusercontent.com/35271042/75199059-f46e7c80-5716-11ea-9bbb-a32e997383eb.png)

### JSON
- Central management of all snippets

![image](https://user-images.githubusercontent.com/35271042/74571222-60403080-4f32-11ea-96a0-641196bfedd6.png)

### UI
- Bulk install/uninstall

![image](https://user-images.githubusercontent.com/35271042/74570207-0d19ae00-4f31-11ea-8d87-87d2ef26fd9a.png)

### CLI
`code --install-extension ms-azuretools.vscode-azurefunctions`

### JSON
- No experience

`devcontainers.json` is a configuration file for our remote containers, and in that configuration file you can specify extensions via:
```json
{
    "extensions": [
        "ms-azuretools.vscode-azurefunctions",
        "ms-vscode.csharp"
    ]
}
```

We should look at adopting a similar patter for user extensions, in the same way that you can edit user settings via JSON.

**Comment by NotWearingPants** [comment]
Don't forget extension settings, such as an array of dictionary words in a spell checker extension

**Comment by misolori** [comment]
@NotWearingPants I don't think extension experiences will be part of this scope as we don't control their UI.

**Comment by usernamehw** [comment]
> [ ] Boolean
> * `editor.fontLigatures`

`editor.fontLigatures` is not boolean, but `boolean` or `string` (from **1.40**?). It doesn't work in GUI version because of that now.

**Comment by beastdestroyer** [comment]
I am not sure but when inputting settimgs via UI, I notice that they aren't sorted (ie, not all the `files.*` are together), 
Is it possible to have them auto-sorted into their respective categories, as I thinl that would be very beneficial, if it isn't implemented already

**Comment by gulshan** [comment]
I mostly use JSON settings editor. One thing I always want to know is- what is the default value of this settings. It was possible in he side-by-side UI.

**Comment by misolori** [comment]
@gulshan you can still see the default value from intellisense:

![image](https://user-images.githubusercontent.com/35271042/73697994-d02dfb80-4694-11ea-8a65-c42aab1df8a2.png)

**Comment by gulshan** [comment]
I think this is a new feature. Not getting it, in the 1.41.1 stable version, unless it is part of documentation tooltip. Also, this info should be shown in the line edit button.

**Comment by Gama11** [comment]
@gulshan I'm getting it in 1.41.1.

Note that that "detail" string of a completion item is only shown when it's selected, so if the default of a boolean setting is `false` (like with `outline.showVariables` for instance), you'd have to press "down" once to see it:

![](https://i.imgur.com/CLFVhkc.gif)

**Comment by gulshan** [comment]
I see this-

![code_settings](https://user-images.githubusercontent.com/751732/73762665-a19a4880-479a-11ea-8200-46aadf0d359f.png)
You got the tip inlined somehow.

**Comment by Gama11** [comment]
You can toggle between those two display modes with Ctrl+Space.

**Comment by gulshan** [comment]
The default values will be more useful for open value settings involving numbers, strings and arrays. What I feel important in this regard is, a clear way to view the default value of a setting, in both json and visual editor.

**Comment by regs01** [comment]
workbench.settings.useSplitJSON should be true by default. It's far easier to look default and explore settings when you see options. And it's easier to switch off than to switch on.

**Comment by usernamehw** [comment]
Settings UI are not showing deprecated settings. When you mark a setting with `deprecationMessage` - the message is visible in `settings.json`, but UI simply ignores those settings.

**Comment by misolori** [comment]
@usernamehw what is your expectation for what you'd want to see from the UI side? Something like below?

![image](https://user-images.githubusercontent.com/35271042/75201298-f8050200-571c-11ea-8a52-ee90b4d77896.png)

**Comment by misolori** [comment]
Closing this issue as it has identified the areas/gaps between our UI and JSON experiences. Feel free to keep commenting on this issue if there are other items that come up that were missed.

**Comment by usernamehw** [comment]
> @usernamehw what is your expectation for what you'd want to see from the UI side? Something like below?
> 
> ![image](https://user-images.githubusercontent.com/35271042/75201298-f8050200-571c-11ea-8a52-ee90b4d77896.png)

@misolori Yes, the purpose of `deprecationMessage` is so that people would read it.
