### ISSUE TITLE
Control behavior of "Next" operations (to not always cycle back to beginning)

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#84304]
Currently, in a Diff view, when I use the command to view the next difference, after the last one, VS Code goes back to the first one.  This also happens with text search and other "next" operations.  This is certainly a handy behavior that I'm sure many people like.  However, when there are more than several items (e.g., hundreds), I don't pay attention to the scroll bar and don't remember if what I am looking at I have seen before or not.  This has caused me wasted effort in reviewing things I had already reviewed.  I would prefer a more obvious way to avoid repeating/cycling.

I, therefore, suggest the following (but there may be other ways to solve my issue as well):
Add a "nextBehavior" option that would affect all the "next" operations.  By default, it can be set to "cycle" for the current behavior.  But it could be set to "stopAtEnd" to not cycle.  This should also affect any "previous" commands from cycling.  Another possible setting would be to cycle with a notification (e.g., beep and/or flash and/or message that appears somewhere) when going from the end back to the beginning.

FWIW, I would be happy if the only behavior were the last option (without a new setting) -- which would work as it does now, just with a new notification.  But this might annoy others (who have been using VS Code without such notifications).  If this setting exists now, I did not see it.  Thank you.

**Comment by GustavoASC** [comment]
I created PR #92243 with a setting which controls whether the search automatically restarts from the beginning (or the end) when no further matches can be found.

This setting is under Find group of settings and then do not affect Diff Editor. Maybe we can create another setting only for Diff Editor!?

**Comment by rebornix** [comment]
@gubikmic thanks for your help! This issue is also a dup of https://github.com/microsoft/vscode/issues/28666 .
