### ISSUE TITLE
Enable extension according to file type

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#84303]
Issue Type: <b>Feature Request</b>

In order to make my VSCode more lightweight, I disable extensions related to some programming languages (like Python, Pascal, Clojure extensions).

I did this because, some times, I use VSCode to write SQL scripts, making notes and other stuff not related to these programming languages. But if I need to open a file of these languages (not in a workspace) I've to manually enable the extensions.

Would be great if we could set, in settings.json, which extensions we want to enable per language, like:

"[python]": {
&nbsp;&nbsp;&nbsp;&nbsp;"files.insertFinalNewline": true,
&nbsp;&nbsp;&nbsp;&nbsp;"files.encoding": "utf8",
&nbsp;&nbsp;&nbsp;&nbsp;"Extensions.Enabled": [ms-python.python, donjayamanne.python-extension-pack, ms-python.anaconda-extension-pack]
&nbsp;&nbsp;&nbsp;&nbsp;    }

VS Code version: Code - Insiders 1.41.0-insider (fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347, 2019-11-08T05:28:30.394Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexandrudima** [comment]
@RicaBenhossi VS Code extensions are usually behaving in the way in which you describe. Simply having an extension installed and enabled does not mean it is executing any code. Extensions in VS Code activate on activation events and one such event is `onLanguage:X`. Most extensions respect this and do not activate on `*` (startup). You can check this by running `F1 > Show running extensions`.
