### ISSUE TITLE
Changing default shell breaks terminal if shellArgs script used.

### ISSUE THREAD

**Issue by Amleto** [microsoft/vscode#84307]
- VSCode Version: 1.39.2
- OS Version: win 10 home (10.0.18362)

Steps to Reproduce:

1. install vs code & cmder & git bash (
2. configure cmder to be used in terminal ([link](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration)) i.e. set,

```
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k", "%CMDER_ROOT%\\vendor\\init.bat"
    ],
``` 

3. Observe that Terminal -> new terminal works.
4. ctrl + shift + p -> "default shell"
5. Select "Terminal: Select Default Shell"
6. Choose bash
7. Terminal -> new terminal now results in,

```
The terminal process terminated with exit code: 127
```
and no terminal pane at all.

At first I thought there was no way to fix this because I had been using the terminal window's drop-down box to change the default, and due to the exit code, there was no longer any terminal window.

I did manage to find the correct lines in settings.json to revert (by luck), and later learnt about `ctrl + shift + p -> "default shell"`. However, initially I thought I had caused a more serious issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This goes into the bigger discussion of supporting profiles in the terminal that are more than just the executable: https://github.com/microsoft/vscode/issues/45444, we need the same to be able to automatically expose the different flavors of WSL conveniently.

/duplicate https://github.com/microsoft/vscode/issues/45444
