### ISSUE TITLE
Easily find changed settings

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#84308]
There have been times I wanted to find a setting I had changed, but couldn't remember the setting's name.  I think this would be useful in some other scenarios as well (such as finding what you've changed for setting up a new system or telling a friend).  Currently, the changed settings show a bar along the left margin.

It would be nice if I could filter the settings list to only show ones that have been changed.

It would also be nice if an indication of setting groups with changes could appear in the tree on the left.  This might make them easier to find and navigate to.

Note that I do not have that many settings with changes.  I suspect this would be less useful for users with tons of changes.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/68505633-9330a500-021c-11ea-8735-507787e9c43f.png)
You can use the `@modified` tag in the settings search bar, or the "Show Modified Settings" item in the settings title bar. 
![image](https://user-images.githubusercontent.com/8586769/68505687-b6f3eb00-021c-11ea-959d-e42d63fa5996.png)

**Comment by andyj513** [comment]
Awesome!  Thank you.
