### ISSUE TITLE
"Configure Trusted Domains" strange behaviour

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#84301]
0. Trusted domains: `[ "https://github.com" ]`
1. Attempt to open a link to github
2. "Configure Trusted Domains" dialogue appears (Bug, the link should open)
3. "Configure Trusted Domains" -> "Trust https://github.com"
4. Bug, the link does not open.

Observation: `"Configure Trusted Domains" -> "Mangage Trusted Domains"` and `"Configure Trusted Domains" -> "Trust github and all its subdomains"` do cause the link to open.

Alternate:

0. Trusted domains: `[ "*.github.com" ]`
1. Attempt to open a link to github
2. "Configure Trusted Domains" dialogue appears (Bug, the link should open)
3. "Configure Trusted Domains" -> "Trust github and all its subdomains"
4. Bug, the link does not open.

Observation: `"Configure Trusted Domains" -> "Mangage Trusted Domains"` and `"Configure Trusted Domains" -> "Trust https://github.com"` do cause the link to open.

Alternate alternate:

0. Trusted domains: `[ "*.github.com", "https://github.com" ]`
1. Attempt to open a link to github
2. "Configure Trusted Domains" dialogue appears (Bug, the link should open)
3. "Configure Trusted Domains" -> "Trust github and all its subdomains" OR "Configure Trusted Domains" -> "Trust https://github.com"
4. Bug, the link does not open.

Observation: `"Configure Trusted Domains" -> "Mangage Trusted Domains"` does cause the link to open.

Seems like a) the links do not actually get trusted, and b) on attempting to re-trust a link in the same way it had previously been trusted (single subdomain vs. all), the link will not open.

**Comment by octref** [comment]
No longer reproducible in latest dev version.

**Comment by sbatten** [comment]
can still repro this even after the fix for web.

1. Populate the `linkProtectionTrustedDomains` in product
2. Open editor and type https://github.com
3. Click link and configure to trust
:bug: => it will not be observed

**Comment by octref** [comment]
I see, the problem is that a more specific rule in the bundled https://github.com/MicrosoftDocs/vsonline invalidated https://github.com, so the later rules were not checked.
