### ISSUE TITLE
Window freeze every day for me, and have to wait till re-open

### ISSUE THREAD

**Issue by Octavianus** [microsoft/vscode#84313]
Issue Type: <b>Bug</b>

It happened almost everyday.
Most of the time it happened when I try to type a git command.
Then window freeze, and have to wait till re-open

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.89GB (11.50GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|9.9.3
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|2.3.0
vscode-nuget-package-manager|jmr|1.1.6
graphql-for-vscode|kum|1.15.3
python|ms-|2019.10.41019
cpptools|ms-|0.26.1
csharp|ms-|1.21.6
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.2
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.1
markdown-preview-enhanced|shd|0.5.0
vim|vsc|1.10.2

</details>

**Comment by alexandrudima** [comment]
@Octavianus Where do you type the git command when the freeze occurs?
