### ISSUE TITLE
newest update has unexpected behavior

### ISSUE THREAD

**Issue by smartpcr** [microsoft/vscode#84318]
- VSCode Version:
- OS Version:
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Problems:
- select a word include spaces on the right side
- outdent no longer works with "shift-tab" keyboard shortcut

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexandrudima** [comment]
@smartpcr Can you please try to disable all extensions?

**Comment by ratatoeey** [comment]
clean up last line to `Does this issue occur when all extensions are disabled?: ` if you haven't tested with extensions disabled. its confusing.

the command line paramter is `--disable-extensions`, here are other options https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

----

regards ratatoeey
