### ISSUE TITLE
Sluggish performance while typing in editor

### ISSUE THREAD

**Issue by morganwdavis** [microsoft/vscode#84312]
Issue Type: <b>Bug</b>

In the latest 1.40 release, typing and moving around in the editor seems unusually sluggish.  It's not unusable, but noticeably labored compared to previous versions. 

To repro:

1. Open new editor tab
2. Set editor type to Plain Text and disable all extensions (using "Disable All Installed Extensions" command)
3. Open Task Manager and view Visual Studio Code processes
4. Hold down a key and let it repeat for at least 10 seconds
5. Notice how CPU load for VSCode processes increases as key repeats (up to about 10% on my system). Characters appear delayed and bursty.  Power Usage column goes from "Very Low" "Very High".
6. Release key and CPU load for VSCode returns back down to normal

Simply typing characters like this should not cause VSCode to require 10% of the CPU and dramatically increase power usage, especially in Plain Text mode where affect from extensions should be minimal.

While entering this issue report using the built-in issue reporter dialog, I tried repeating a key and watching the task manager, and the CPU does not increase over 3%.  Doing the same thing in the terminal pane only goes to 4% max. This indicates the issue is constrained to the primary editing space.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.95GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
sqlformatter|bre|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|2.3.0
unicode-substitutions|Gle|2.2.2
vscode-phpfmt|kok|1.0.30
vscode-apache|mrm|1.2.0
python|ms-|2019.10.44104
vscode-typescript-tslint-plugin|ms-|1.2.2
php-docblocker|nei|2.0.1
material-icon-theme|PKi|3.9.1
partial-diff|ryu|1.4.0
rewrap|stk|1.9.1
change-case|wma|1.0.0
markdown-pdf|yza|1.4.1
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by ConduciveMammal** [comment]
Getting this also. CPU is getting hammered almost immediately after opening VSCode.

Macbook Pro
MacOS X Catalina.

**Comment by morganwdavis** [comment]
@ConduciveMammal your experience differs from mine.  You may have a different issue.

Adding clarity for my case: CPU load at idle (not typing or doing anything in the editor) is fine/typical.  It's when I start typing rapidly (e.g., repeating a key) that I see the lag correlating to CPU usage increase.  It feels like I'm typing ahead of VSCode's ability to update the screen and move the cursor.  Again, it's not unusable -- just slower than before.  As soon as I stop typing, CPU returns to a reasonable idle level (0%).

Here's a screenshot during repeating the x key after 10 seconds:

<img width="870" alt="Annotation 2019-11-08 160257" src="https://user-images.githubusercontent.com/4434533/68518592-778bc580-0241-11ea-9341-401dad562d77.png">

**Comment by willyarisky** [comment]
I got the same issue, also the CPU usage of Code Helper increased to 95%. The issue solved after disable the hardware acceleration.
