### ISSUE TITLE
Start up takes pretty long

### ISSUE THREAD

**Issue by C00ckieHunter** [microsoft/vscode#84314]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

So I do have Performance Issues on my Windows PC for around 5 months. I noticed it when I started coding more on my second PC (MAC) and Visual Studio Code is starting in around 5secs there even tho the PC is about 7 years old. When ever I start the Programm on my Windows PC it at least costs me aroudn 15secs. Which isnt making sense for me since my windows pc has more Performance Power. More over I open the latest Files on my MAC. This option was enabled on the Windows PC too but I disabled it when I tried to improve the Performance, but I didnt feel a difference.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	 22908	code main
    0	    97	 23096	   gpu-process
    0	    66	 61328	   window (Issue Reporter)
    0	    67	 71224	   shared-process
    0	    14	 76824	   electron-crash-reporter
    0	   198	106564	   window (Untitled-1 - Visual Studio Code)
    0	    86	118968	     extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer|Coe|1.0.61
console-log|dot|0.6.2
glitch|gli|0.1.3
beautify|Hoo|1.5.0
vs-color-picker|lih|1.0.0
vsliveshare|ms-|1.0.1123
color-highlight|nau|2.3.0
sc2galaxy|tal|1.10.0

</details>

**Comment by alexandrudima** [comment]
@C00ckieHunter We have a wiki to help identify performance problems / help create good performance issues that would allow us to investigate. Please follow the steps in https://github.com/microsoft/vscode/wiki/Performance-Issues#reporting-a-performance-issue
