### ISSUE TITLE
Cannot type ~ character in terminal due to allow chords feature

### ISSUE THREAD

**Issue by joshualamusga1** [microsoft/vscode#84311]
Issue Type: <b>Bug</b>

**Description**
It's not possible to type the tilde character in the terminal, at all, for commands like `git reset head~1 --soft` which I do with high frequency when the newly-enabled option `Terminal -> Integrated -> Allow Chords` is `true`. I have no keyboard shortcuts that include the tilde character.

Typing tilde requires holding shift on my keyboard. This shouldn't count as a modifier key and thus shouldn't trigger any waiting for second key... chord logic.

**Expected behavior**
The tilde character should be typed in the terminal as with any other normal character press.

**Actual behavior**
Pressing shift + backtick to produce a tilde is triggering "waiting for second key..." and makes it impossible to type a tilde.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
Do you have a chord setup that starts with shift+~ then? Or did an extension contribute it?

You can look at your keybindings.json file via the command palette and also look at the default keybindings.json file to see all internal and extension keybindings.

**Comment by Tyriar** [comment]
Also what keyboard layout are you using?

**Comment by joshualamusga1** [comment]
As I said, I have no keyboard shortcuts that include the tilde character. The only extension in use is prettier. en-US keyboard layout.

**Comment by Tyriar** [comment]
@joshualamusga1 after pressing shift+` what happens when you go to the editor and finish the chord with something that doesn't exist? You should see something like this in the status bar:

![image](https://user-images.githubusercontent.com/2193314/68596748-92805480-0450-11ea-93ee-4fc5e2809876.png)

**Comment by joshualamusga1** [comment]
@Tyriar I was looking for Shift+~ which of course there are no keyboard shortcuts for. I have two shift+` shortcuts which I have just removed (they are defaults, though, so there is still a minor conflict of shortcuts here). Closing unless you feel the need to re-open.

**Comment by Tyriar** [comment]
@joshualamusga1 this should be the only keybinding close to that by default on Windows:

```
{ "key": "ctrl+shift+`",          "command": "workbench.action.terminal.new" }
```

Is it some extension contributing them? The most popular prettier extension doesn't seem to contribute it https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by joshualamusga1** [comment]
There were two and I don't remember if any started with Shift+` or not. I unassigned the shortcuts entirely so I don't know how to tell what they were.

**Comment by Tyriar** [comment]
@joshualamusga1 if you open keybindings (ctrl+k, ctrl+s) you can open the backing file which should have the removals in it by clicking this button in the top-right:

![image](https://user-images.githubusercontent.com/2193314/68613072-cc625280-0472-11ea-8f74-9f194797c0ca.png)

**Comment by joshualamusga1** [comment]
@Tyriar Yeah, I only see the keyboard shortcut you named. Let's chalk this up to assigning something to an unlikely keybinding once as a lazy way to "remove" a keybinding only to be bitten by it later. Guessing that's what happened.
