### ISSUE TITLE
Multi app projects are problematic

### ISSUE THREAD

**Issue by serkanyersen** [Microsoft/vscode#8431]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.6 Beta (15G7b)

Problems:

 I have a repo structured as the following

```
.
├── .vscode
│   └── tasks.json
├── client
│   ├── .eslintrc
│   ├── node_modules
│   ├── package.json
│   └── src
│       └── app.js
└── server
    ├── index.ts
    ├── node_modules
    ├── package.json
    ├── src
    │   └── app.ts
    ├── tsconfig.json
    └── tslint.json
```
- When `tslint` and `eslint` extensions are installed, vscode is unable to find the binaries or configs for these tools. It simply looks for them in workspaceRoot.
  - it's however, able to find `tsconfig.json` without a problem.
- I've defined tasks like `npm run build` `npm run lint` in my sub projects. They are just simple shortcuts to tslint or eslint and tsc or webpack. When I create `npm` tasks in `tasks.json`, vscode is unable to detect the package.json file.
  - I can fix this by using `options.cwd = '${cwd}/app/'` but then vscode is unable to match the errors to the correct files. vscode runs the commands from workspaceRoot, but npm's output is relative to the project.
  - I cannot use `problemMatcher.fileLocation` to fix this issue because `global matchers and tasks can't be mixed. Ignoring global matchers.`

Expected:
- when running tasks, vscode should look for configs and binaries relative to open file location, unless configured other vise.
- when linting, vscode should look for configs relative to open file location.

This setup works without a problem on Sublime Text and Atom.

Hope this helps, let me know if I can provide more information.

**Comment by dbaeumer** [comment]
@serkanyersen can you please provide your tasks.json file so that I can see if there are possible workarounds.

You can always declare a matcher per task. In addition you can redefine global available matchers as well:

```json
    "problemMatcher": {
        "base": "$tsc",
        "fileLocation": "relative"
    }
```
This takes the gobal $tsc matcher and changes its fileLocation property.

**Comment by serkanyersen** [comment]
Here is my tasks.json

I've included your suggestion but it didn't fix the issue.
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "options": {
      // to be able to find the package.json
      "cwd": "${cwd}/app/"
    },
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "build",
            "isBuildCommand": true,
            "problemMatcher": {
                "base": "$tsc",
                "fileLocation": "relative"
            },
            "args": ["run", "build"]
        },
        {
          "taskName": "lint",
          "problemMatcher": {
              "base": "$tsc",
              "fileLocation": "relative"
          },
          "args": [
            "run", "lint"
          ]
        },
        {
            "taskName": "test",
            "isTestCommand": true,
            "args": ["run", "test"]
        }
    ]
}
```

Actually issue itself is not about the tasks but it's mostly not being able to run these linters and tasks relative to the file location.

I'm unable to use any linters in the editor. Also cannot have tasks per project, I can only configure it to work on one of the folders.

If I could tell where to find eslint or tslint to vscode or making them behave just like the discovery of `tsconfig.json` would probably solve the first problem.

Second problem is more about the design of the whole tasks system, it needs either additional features or complete behavioral change to accommodate nested project structures.

**Comment by dbaeumer** [comment]
@serkanyersen two questions: 

- why do you cwd into ${cwd}/app/. Where is your app directory in our layout?
- from where do you run your build task normally (e.g npm run build). And if a TS file has errors how does the error message look like in a terminal.

**Comment by serkanyersen** [comment]
@dbaeumer 
 - /app is just one of the nested apps in the repo. it could be server in the file tree I posted above. I need to cwd into it because vscode cannot find `package.json` in the root.
 - I run my npm tasks on each nested app folder.

I get the tasks running correctly now with the following configuration
```js
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "options": {
      // to be able to find the package.json
      "cwd": "${cwd}/app/"
    },
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "build",
            "isBuildCommand": true,
            "problemMatcher": {
                "base": "$tsc",
                "fileLocation": ["relative", "${cwd}/app/"]
            },
            "args": ["run", "build"]
        },
        {
          "taskName": "lint",
          "problemMatcher": {
              "owner": "tslint",
              "fileLocation": ["relative", "${cwd}/app/"],
              "severity": "warning",
              "pattern": {
                "regexp": "^(.*?)\\[(\\d+),\\s(\\d+)\\]:\\s(.*)$",
                "file": 1,
                "line": 2,
                "column": 3,
                "message": 4
              }
          },
          "args": [
            "run", "lint"
          ]
        },
        {
            "taskName": "test",
            "isTestCommand": true,
            "args": ["run", "test"]
        }
    ]
}
```

But I still cannot run linters on the files while editing them. I keep getting these errors because binaries are not found.

![screen shot 2016-06-30 at 12 47 12](https://cloud.githubusercontent.com/assets/30582/16501927/cf5447ee-3ec0-11e6-9867-66068889b10b.PNG)

As I said, this is the result of nested folder structure and I need a way to tell vscode where to look for these binaries.

**Comment by dbaeumer** [comment]
The eslint, tslint problems are know and there are separate issues for them in their corresponding git repositories. To workaround it you can install eslint and the plugins you use globally as well. Same true for tslint.

**Comment by serkanyersen** [comment]
I already have them installed globally as well. I still get the same error. Even if I install linters in the root folder of the project, they still are not working because they cannot find the config files.

```
.
├── WHERE LINTER IS INSTALLED   <---- installed in the project root, just to try
├── .vscode
│   └── tasks.json
├── client
│   ├── .eslintrc  <----- CONFIG FILE
│   ├── node_modules
│   ├── package.json
│   └── src
│       └── app.js
└── server
    ├── index.ts
    ├── node_modules  <----- where it should have been found
    ├── package.json
    ├── src
    │   └── app.ts
    ├── tsconfig.json
    └── tslint.json  <------ CONFIG FILE
```

I've checked the source code on the extensions and they use the plugin api to resolve these libraries and configs like so

```
    return server.Files.resolveModule(rootFolder, 'tslint').
```

That's why I created this issue on this repo. They are just using the suggested way.

Do you want me to open the same issue on each of these linter's repo?

Thanks for the help so far.

**Comment by dbaeumer** [comment]
@serkanyersen no need for separate issue for the linters. It is a know issue. However a globally or in the project root installed linter should work. It tested it and it worked for me. Is there any project I can clone to see what is going on ?

**Comment by serkanyersen** [comment]
I think this issue has been fixed, probably by linters. I'm not having this problem anymore. Closing.
