### ISSUE TITLE
Unable to start recent versions of VSCode

### ISSUE THREAD

**Issue by dclemmerwork** [microsoft/vscode#84323]
However, I had 1.33.1, then 1.34.0, then 1.38 versions of VSCode working on my (Windows 10) machine. One day, for no apparent reason (I hadn't just installed something, for instance), 1.38 stopped working. It wouldn't even start up. Running 'Code --verbose' from the command line produced no output (the mouse cursor turned briefly to a spinner, but nothing even showed up in Task Manager, let alone something like a splash screen).

I did get an error message in the Application log, which included the lines (more or less; remember, no cut-n-paste possible): 
Faulting Application Code.exe, version: 1.38.0 
Faulting module ntdll.dll, version 10.0.16299.936 
Exception code: 0xc0000374 
Faulting Application path: c:\Program Files\Microsoft VS Code\Code.exe 
Faulting module path: c:\Windows\System32\ntdll.dll

Re-installing VS Code (with or without system restart after uninstall) did nothing. Removing all extensions (we have a bunch) did nothing. Installing 1.39.2 did nothing.

The only good thing is that I can still run 1.34.0, if I reinstall that (did not try 1.33.1, and I don't have any in-between versions from 1.34 to 1.38 to try). So at least I'm not completely shut out.

I also tried deleting basically all of workspaceStorage, to no effect. Nor did renaming my storage.json (saw some suggestions that that fixed some other problem that led to the same exception code).

The biggest weirdness, to me, is that the path to ntdll.dll is in System32, rather than in SysWOW64 (is there some way to force usage of the latter?). Second, why did 1.38.0 work just fine for a while, and then stop?

I also got one additional datum today.  My boss installed 1.39.2 on her machine, and she was able to run it three or four times without problem.  But since then, with nothing additional being done on the machine (literally, just quitting it and restarting), she started seeing the exact same error I am.

- VSCode Version: 1.38.0 and 1.39.2
- OS Version: Windows 10 (1709)

Steps to Reproduce:
I had VSCode working fine under 1.34.0 for a while.  We finally got 1.38.0 in, and I installed that.  It worked ok for a while, but then suddenly stopped working.  When I tried to start it
1.  Run Code.exe from command line (or by double-clicking in Explorer, or from start menu; doesn't matter)
2.  There is no step two.

Does this issue occur when all extensions are disabled?: Yes/No
Occurs when they're actually deleted; never tried just disabling them.

Would love to hear any suggestions for further things to look at.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by dclemmerwork** [comment]
It takes me 3-4 days (at best; I don't control the process) to get new
versions in to try.  Is it worth it?

**Comment by bpasero** [comment]
Yes, worth it for us.

**Comment by deepak1556** [comment]
> The biggest weirdness, to me, is that the path to ntdll.dll is in System32, rather than in SysWOW64 (is there some way to force usage of the latter?)

you can edit the `PATH` environemt variable to change the order of DLL lookup.
