### ISSUE TITLE
Open specific extension settings command

### ISSUE THREAD

**Issue by Meshredded** [microsoft/vscode#84324]
The feature has been requested since April 2017 and is available for insiders since then:
https://github.com/Microsoft/vscode/issues/25012

Is it planned to add it in a future release ? (it's much needed for extension developers)

**Comment by usernamehw** [comment]
Have you tried running code from #25012 ?

```js
vscode.commands.executeCommand('workbench.action.openSettings', `@ext:vscode.git`);
```
Replace `vscode.git` with extension id.

**Comment by Meshredded** [comment]
> Have you tried running code from #25012 ?
> 
> ```js
> vscode.commands.executeCommand('workbench.action.openSettings', `@ext:vscode.git`);
> ```
> 
> Replace `vscode.git` with extension id.

Yes i did try this, it woks fine in an extension host, but once i package my extension the command don't work anymore, that's why i said that the feature is only available for insiders.

**Comment by usernamehw** [comment]
Works for me. Except for when I have `json` editor configured: #84355 (But this reproduces in extension host also). 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Meshredded** [comment]
Not working for me, event when i don't have json editor configured.
Extension example : https://marketplace.visualstudio.com/items?itemName=meshredded.robusta

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by usernamehw** [comment]
Are you using `workbench.action.openGlobalSettings` instead of `workbench.action.openSettings` ?

https://github.com/Meshredded/vscode-robusta/commit/38822ab6464534ba85feb6e6d39f4119b3808212

**Comment by Meshredded** [comment]
Yes

**Comment by usernamehw** [comment]
Why?

**Comment by Meshredded** [comment]
It's an error that i did not notice actually.

**Comment by Meshredded** [comment]
It works perfectly after that i changed from `workbench.action.openGlobalSettings` to `workbench.action.openSettings`  Thank you :)

**Comment by usernamehw** [comment]
You're welcome. Happens to everyone :)

**Comment by roblourens** [comment]
Thanks @usernamehw!
