### ISSUE TITLE
window.showOpenDialog throws "TypeError: Default path must be a string" with defaultUri = null

### ISSUE THREAD

**Issue by Kruemelkatze** [microsoft/vscode#84325]
My extension has a function that opens a dialog on a given path, which may be null (which is fine for my intended behaviour). Since version 1.40.0, I get following exception (it worked < 1.40.0):

When calling ```vscode.showOpenDialog({ defaultUri });```, it throws ```TypeError: Default path must be a string``` when ```defaultUri: null```. ```defaultUri: undefined``` resolves this and I can change that without problems. It's still possibly an undocumented breaking change in the extension API, if I'm not wrong.

I interpret the [documentation for the OpenDialogOptions ](https://code.visualstudio.com/api/references/vscode-api#OpenDialogOptions) as that the defaultUri is nullable.

- VSCode Version: 1.40.0
- OS Version: Windows 10 18362

Steps to Reproduce:
1) Use ```vscode.showOpenDialog({ defaultUri: null });``` on 1.40.0 to get an exception
2) Use the same on e.g. 1.39, where it worked fine.

Does this issue occur when all extensions are disabled?: Yes/No
It effects extension authoring. So... no?

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/68601380-81f9c980-04a4-11ea-91da-cd3b41d2e0b8.png)
```ts
	export interface OpenDialogOptions {
		/**
		 * The resource the dialog shows when opened.
		 */
		defaultUri?: Uri;
                //....
}
```

`defaultUri` is an optional parameter of type Uri. Null is not a valid value.
