### ISSUE TITLE
Provide login support for settings sync

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#84332]
With work on settings sync (https://github.com/microsoft/vscode/issues/2743), there needs to be a login mechanism to sync to a specific account.

**Comment by zackschuster** [comment]
will this support cloudkit?

**Comment by RMacfarlane** [comment]
@zackschuster Initial support will be for Azure Active Directory only

**Comment by sanket-bhalerao** [comment]
Is this going to be "Login using Github" option to login? 
if that is the case, then is there a possibility to have all extensions (from Microsoft) can be logged in in a single login? no need to have a separate login and access request for extensions.
- github
- github issues
- vscode live share
- *settings sync

**Comment by RMacfarlane** [comment]
@sanket-bhalerao For the initial implementation for settings sync, no. The backend we've currently written for setting sync accepts Azure Active Directory access tokens. But we do want to make it possible for other extensions to be able to use the same login data. I've written up an API proposal [here](https://github.com/microsoft/vscode/issues/88309) which I'm working on using for this. This would make it possible to write other extensions that provide authentication. The plan with it is to write two different extensions, one contributing AAD auth that would be used by settings sync and built in to VSCode, and one for GitHub that other GitHub extensions could depend on for authentication

**Comment by IllusionMH** [comment]
To clarify: It will be possible to use outlook.com account (not sure if its AAD under the hood for non org users) or it will be available only to org users?

**Comment by RMacfarlane** [comment]
Yes, our intention is to allow outlook.com/personal accounts. My understanding is that these accounts may not be in AAD itself, but the AAD login endpoint is able to federate to a service that handles such accounts

**Comment by RMacfarlane** [comment]
There's an initial implementation of this now being used by settings sync that allows logging in with a Microsoft account (any work/school/personal account):

![sign_in_2](https://user-images.githubusercontent.com/3672607/73224174-7a4dd680-411d-11ea-8223-38fc29129ac0.gif)

With the [authentication provider API](https://github.com/microsoft/vscode/issues/88309) introduced to create this, I'll be working on creating a GitHub authentication extension that could be leveraged by other extensions as well. (It's possible we'll use GitHub sign in for settings sync in the future, TBD.)

There's still some work to do on how to best display login information, I'll create a separate issue to track that.

**Comment by IllusionMH** [comment]
@RMacfarlane with personal accounts support implemented - is there a change to test sync before release (early February if its still targeted for January 2020 milestone)?

**Comment by RMacfarlane** [comment]
I believe our plan is to begin previewing it in Insiders in February at the earliest. @sandy081  @Tyriar, any additional comments on the timeline?

**Comment by FernandoMiguel** [comment]
i'm on the latest insider.
was trying to enable sync.
I have multiple chrome profiles, a mix of personal and work.
the current implementation open a link randomly on the last chrome used.

can an option to copy paste the login link be added?
also, can i not login with just githubs? 
keeps asking for a microsoft account after creating the trust with github

**Comment by RMacfarlane** [comment]
@FernandoMiguel There's an existing issue to add an option to copy the sign in link: https://github.com/microsoft/vscode/issues/86083

Currently, a Microsoft account is still required for settings sync, and GitHub can only be used as a link to a new or existing Microsoft account. I'll update the documentation to clarify this.

**Comment by markcarroll** [comment]
Any chance you could add iCloud sync? With both my Macs already syncing everything else through iCloud with no login required, it would be nice if this feature supported that too. Having to create a Microsoft account just for this seems annoying (love the feature though).
