### ISSUE TITLE
Debugger stalls trying to inspect XDocument variable

### ISSUE THREAD

**Issue by iRonJ** [Microsoft/vscode#8433]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: 10.11.5 (15F34)
- dotnet --version: 1.0.0-preview2-003121
Steps to Reproduce:

1. Create a file with this line of code, linking to a 4MB XML file:
`System.Xml.Linq.XDocument newXMLDoc=XDocument.Load(@"/Users/ron/Documents/xmlFile.xml");`
2. Set a break point just after this line
3. In the debugger, inspect the variable "newXMLDoc"

Debugger stalls for dozens of seconds while trying to inspect the variable

**Comment by bpasero** [comment]
@iRonJ please report this to the debugger extension you are using for debugging.
