### ISSUE TITLE
yarn web, can't found vs/loader.js

### ISSUE THREAD

**Issue by mowangjuanzi** [microsoft/vscode#84339]
run command `yarn web ` in project root path.

tip: Error: ENOENT: no such file or directory, stat '/project_path/out/vs/loader.js'

github project commit: 

```bash
commit 696465bdddabf3ceb0b71ab8e47bc1d7c8b8e1f3 (HEAD -> master, origin/master, origin/HEAD)
Author: Pine Wu <octref@gmail.com>
Date:   Fri Nov 8 16:11:29 2019 -0800

    Fix #84215
```

**Comment by bpasero** [comment]
@mowangjuanzi I cannot reproduce, did you run `yarn watch` before running `yarn web`?

**Comment by mowangjuanzi** [comment]
When I run the command, it works. Thank you !

**Comment by nagstaku** [comment]
> @mowangjuanzi I cannot reproduce, did you run `yarn watch` before running `yarn web`?

I also ran into this problem, and solved it by running `yarn watch` first. I was pretty blindly following the [release notes](https://code.visualstudio.com/updates/v1_40#_engineering) which simply stated:

> In your local fork of the vscode repository, execute yarn web from the command line and access http://localhost:8080/. For more details about cloning and building the vscode repo, see the setup instructions.

**Comment by cnryb** [comment]
> @mowangjuanzi I cannot reproduce, did you run `yarn watch` before running `yarn web`?

It works for me. Why not write this successful method here
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#run
