### ISSUE TITLE
Windows taskbar does not auto reveal when VSCode is maximized and taskbar configured to auto-hide

### ISSUE THREAD

**Issue by MolusMS** [microsoft/vscode#84342]
Issue Type: <b>Bug</b>

1.- Set windows taskbar to auto hide and to be on the top.
2.- Maximized VSCode.
3.- Move mouse to the top of the window.

Expected behavior:
  Taskbar shows.

Actual behavior:
 Can't reach taskbar and need to resize VSCode window to use windows.

VS Code version: Code - Insiders 1.41.0-insider (27cd33d891eb23e370b672e751be9fe8b3748ac1, 2019-11-08T19:12:35.358Z)
OS version: Windows_NT x64 10.0.19513

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (47.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nmake-tools|Mic|2.0.191107007
cpptools|ms-|0.26.1
powershell-preview|ms-|2019.11.0

</details>

**Comment by mysticatea** [comment]
I have likely encountered this problem. I cannot show the Windows taskbar by moving the mouse cursor to the edge of the display if VSCode is maximized.

![vscode-taskbar](https://user-images.githubusercontent.com/1937871/68553386-f9f3cf80-0463-11ea-87de-1add51a5164f.gif)

**Comment by mysticatea** [comment]
Workaround:

`"window.titleBarStyle": "native"` setting fixes this issue.

**Comment by imraja** [comment]
I'm also facing the same issue. The issue is happening in task bar (using left side) auto hide mode.

Actual screen after maximize:
![image](https://user-images.githubusercontent.com/7325757/68561915-86ef5680-046d-11ea-84c5-3f9f08524a25.png)
Expected screen after maximize:
![image](https://user-images.githubusercontent.com/7325757/68561960-b2724100-046d-11ea-8961-a9cdc28ca878.png)

**Comment by SuperSupermario24** [comment]
To add on some information: it looks like this issue was introduced in 1.40.0. If I roll back to 1.39.2, the taskbar appears as expected, but if I upgrade again to 1.40.0, it doesn't appear.

**Comment by deepak1556** [comment]
I am merging this to https://github.com/microsoft/vscode/issues/81102 since they have same root cause.
