### ISSUE TITLE
1.40.0 has rendering lag and flickers when minimize/maximize window with custom title

### ISSUE THREAD

**Issue by halega** [microsoft/vscode#84343]
- VSCode Version: 1.40.0
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Open VSCode 1.40.0 and maximize its window.
2. Click VSCode icon on the task bar to minimize the window.
3. Click VSCode icon on the task bar to restore the window.

**Expected result**
Window restored instantly without flickering.

**Actual result**
Window flickers and there's a small lag in rendering status bar. Sometimes the window is restored empty for 2-3 seconds. Look at screencast: [vscode-1.40-rendering-lag.mp4.zip](https://github.com/microsoft/vscode/files/3826889/vscode-1.40-rendering-lag.mp4.zip).

Does this issue occur when all extensions are disabled?: **Yes**

It's a regression in 1.40.0. In 1.39.2 all is OK.

**Comment by Zaseth** [comment]
I'm having the exact same issue. It could happen with any file and it seems like it's not affected by extensions or settings.

**Comment by imba-tjd** [comment]
Probably the same reason as https://github.com/microsoft/vscode/issues/84342

**Comment by HosseinAlipour** [comment]
I experience the same behavior from vscode, this issue happen specifically when 'minimizing/maximizing' not when scrolling through `alt+tab`

**Comment by thermarthae** [comment]
Related with [https://github.com/microsoft/vscode/issues/81102](https://github.com/microsoft/vscode/issues/81102).
It's a known problem with Electron: [https://github.com/electron/electron/issues/19934](https://github.com/electron/electron/issues/19934)

**Comment by bpasero** [comment]
@halega does it reproduce if you configure `"window.titleBarStyle": "native"` ?

**Comment by Zaseth** [comment]
> @halega does it reproduce if you configure `"window.titleBarStyle": "native"` ?

Using that setting **fixes** it.

**Comment by IDaveYoung** [comment]
Same issue here, can confirm the workaround also seems to speed things up so must be related to custom title bar style

**Comment by halega** [comment]
> @halega does it reproduce if you configure `"window.titleBarStyle": "native"` ?

Yes, it helps: no more lag in restoring window.

**Comment by Zaseth** [comment]
The rendering lag is a first issue, but the difference in performance when enabling `window.titleBarStyle` is really big, maybe there is something more going on with this? It seems like the performance increases overall.

**Comment by deepak1556** [comment]
This should be fixed in our insiders build https://code.visualstudio.com/insiders/, can you please verify ?

**Comment by bpasero** [comment]
@deepak1556 did we update Electron already?

**Comment by deepak1556** [comment]
@bpasero yeah we updated it in master a while back so insiders should have it.

**Comment by sbatten** [comment]
still seeing some issue with 6.1.4

**Comment by deepak1556** [comment]
Can confirm issue is still present, working on a fix.

**Comment by deepak1556** [comment]
Electron PR https://github.com/electron/electron/pull/21164

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/85266
