### ISSUE TITLE
Toggle Developer Tools doesn't work any more

### ISSUE THREAD

**Issue by abist** [microsoft/vscode#84340]
Toggle dev tools or toggle webview dev tools don't work any more with the latest VSCode

**Comment by alexandrudima** [comment]
@abist This works fine for me:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/68529316-b2ebca00-02fd-11ea-91ff-e48999e77e54.gif)

**Comment by dp3496** [comment]
It is not working with the keyboard shortcut "Ctrl+Shift+I"

**Comment by IllusionMH** [comment]
> It is not working with the keyboard shortcut "Ctrl+Shift+I"

@dp3496  While command has assigned shortcut it also has `when` condition
![image](https://user-images.githubusercontent.com/1312662/68580761-b60ec380-047f-11ea-950c-d14c4675a3ce.png)
This shortcut will be activated during Extensions or VS Code (run from sources) development.

To make this command always available:
right click on this command in shortcuts list and "Change When Expression" and remove existing text from input
or
add next config to your `keybindings.json`

```json
{
    "key": "ctrl+shift+i",
    "command": "workbench.action.toggleDevTools"
},
{
    "key": "ctrl+shift+i",
    "command": "-workbench.action.toggleDevTools",
    "when": "isDevelopment"
}
```

**Comment by abist** [comment]
@alexandrudima I still can't access the developer tools either with the shortcut or with the command palette. If it helps, this is my VS Code version - 

![Capture](https://user-images.githubusercontent.com/6411451/68608840-c0719300-0468-11ea-9f58-803f5324bce8.JPG)

**Comment by bpasero** [comment]
Works for me too:

![image](https://user-images.githubusercontent.com/900690/68650135-849c0380-0524-11ea-82e3-7487827d91bb.png)

Maybe check if the developer tools are opening in a separate window for you on another monitor.
