### ISSUE TITLE
Extensions UI renders over the Problems UI

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#84341]
- VSCode Version: 1.40.0 and the latest insiders.
- OS Version: Windows.

Steps to Reproduce:

1. Click on some extension in the Extension view, such as C/C++, C#, or Remote - WSL (others don't repro the bug).
2. Make sure the Problems pane is showing.

Bug: See the screenshot. It renders incorrectly. I think it's a recent regression.

![image](https://user-images.githubusercontent.com/19859882/68521821-bc235b00-0259-11ea-8d27-a524b42cb034.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Possible dup of #83209
