### ISSUE TITLE
Display problems for non existance file

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#84345]
Issue Type: <b>Bug</b>

Renamed a file, but in the terminal under the "PROBLEMS" tab keep displaying an error and will not refresh and go away.

When an error is selected, throw up the following error:

"Unable to open 'heap.tf': Unable to read file (Error: File not found (/home/yadav/H1/yadav/dev/javascript/js-interview-prep/src/datastructures/heap.tf))."

![problems](https://user-images.githubusercontent.com/439226/68522586-cb66d080-027a-11ea-9ff7-f68adb46cf64.png)

VS Code version: Code - Insiders 1.40.0-insider (515f496d9a7617caf07f38298f610920f60834d6, 2019-11-05T14:32:00.229Z)
OS version: Linux x64 5.3.7-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X4 940 Processor (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|15.63GB (2.32GB free)|
|Process Argv|/home/yadav/dev/docs/guides --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
markdown-navigation|Ala|1.0.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|10.5.0
dep|car|0.1.0
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.9.1
java-debug|DSn|0.0.2
EditorConfig|Edi|0.14.2
tslint|eg2|1.0.44
prettier-vscode|esb|2.3.0
markdown-preview-bitbucket|hbr|1.0.0
Scala|itr|0.1.7
vscode-peacock|joh|3.1.6
md-navigate|jri|0.0.1
solidity|Jua|0.0.64
terraform|mau|1.4.0
sort-typescript-imports|mic|1.4.1
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
cmake-tools|ms-|1.2.0
cpptools|ms-|0.26.1
Go|ms-|0.11.9
node-debug2|ms-|1.39.3
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.1
angular2-inline|nat|0.0.17
java|red|0.52.0
vscode-yaml|red|0.5.3
editorconfig-gen|Ryu|0.0.2
markdown-preview-enhanced|shd|0.5.0
language-stylus|sys|1.11.0
sort-lines|Tyr|1.8.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-icons|vsc|9.5.0
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.1

(5 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@rajinder-yadav You have installed an extension which generates Problems in the problems tab. But I think it generates them with the wrong URI or something. Can you please create an issue directly against the extension that generates those problems.

**Comment by rajinder-yadav** [comment]
OK I thought this was core typescript checking in vscode, you're saying this is from an extension?
