### ISSUE TITLE
Maximized VSCode window obstructs autohiding Start menu

### ISSUE THREAD

**Issue by ketsuban** [microsoft/vscode#84349]
Issue Type: <b>Bug</b>

1. Put the Start menu on the left of the screen and set it to autohide.
2. Maximize VSCode on the same monitor as the Start menu.
3. Attempt to use the mouse to reveal the Start menu.

Expected outcome: the Start menu pops out over the top of the VSCode window.

Actual outcome: Nothing visibly happens. The Start menu either doesn't pop out, or pops out underneath the VSCode window where you can't interact with it.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.99GB (5.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by imba-tjd** [comment]
dup of https://github.com/microsoft/vscode/issues/84342
