### ISSUE TITLE
`workbench.action.openSettings` doesn't work when settings editor is json

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#84355]
Issue Type: <b>Bug</b>

```js
"workbench.settings.editor": "json",
```
1. `vscode.commands.executeCommand('workbench.action.openSettings', '@ext:vscode.git');`

**Actual**: opens `settings.json`
**Expected**: opens Settings GUI with query `@ext:vscode.git`

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
Hm, if you specifically wanted it to open with a query, then wouldn't it make sense to open it in a filtered view?

**Comment by usernamehw** [comment]
> Hm, if you specifically wanted it to open with a query, then wouldn't it make sense to open it in a filtered view?

What is a `filtered view`? I don't understand this sentence.

**Comment by roblourens** [comment]
Well it should open the settings GUI with the search box set to `@ext:vscode.git` so that you only see settings from the Git extension (that's what I mean by filtered view). If that's what the extension author intended, that seems better than just opening settings.json.

**Comment by usernamehw** [comment]
Well, that's what this issue about, isn't it?
> **Actual**: opens `settings.json`
**Expected**: opens Settings GUI with query `@ext:vscode.git`

**Comment by roblourens** [comment]
I thought you were saying the opposite...

**Comment by roblourens** [comment]
Althought honestly I am hesitant to change it because I think that some people who set that setting just never want to see the settings GUI and now they will complain...

**Comment by roblourens** [comment]
Do you think that this should depend on whether the query argument is passed?

**Comment by usernamehw** [comment]
Yes.
