### ISSUE TITLE
alternative menu command doesn't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8435]
Testing https://github.com/Microsoft/vscode/issues/8197:

I tried to configure an alternative command via these contributions:

![2016-06-28_22-43-18](https://cloud.githubusercontent.com/assets/1898161/16431641/cc916cde-3d81-11e6-9314-1f4b7c82036f.png)

But I was not able to make the 'Pocker' menu action to show up.

**Comment by jrieken** [comment]
@weinand Can you pls provide more detail?

**Comment by weinand** [comment]
@jrieken since I had no `group` specified, the menu item was defaulting to the overflow area where an `alt` command is not supported. After adding a `"group": "navigation"` the menu showed up and had an 'alt' command on hover.

It would be more consistent if menu items in the overflow area could show an alt command too.
