### ISSUE TITLE
Text are bolder that it should be using M+ 1mn

### ISSUE THREAD

**Issue by jingsam** [microsoft/vscode#84358]
版本: 1.40.0
提交: 86405ea23e3937316009fc27c9361deee66ffbf5
日期: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1.  When I upgrade to 1.40.0, my text looks more thicker that previous:

![image](https://user-images.githubusercontent.com/1522494/68526015-7080b800-0312-11ea-9ed1-0d75f690d370.png)

I use the font [M+ 1mn](https://zh.osdn.net/projects/mplus-fonts/downloads/62344/mplus-TESTFLIGHT-063.tar.xz/), set font size as 18. On the right is macOs builtin text editor.

2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jingsam** [comment]
Another issue is that I set font to `M+ 1mn light` or `M+ 1mn thin`, It fallback to the default font.

**Comment by alexandrudima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/84154
