### ISSUE TITLE
[Outline] Differentiate JS function vars from other vars

### ISSUE THREAD

**Issue by minj** [microsoft/vscode#84359]
I've looked at microsoft/TypeScript#14830 and microsoft/TypeScript#29036 but they seem to be not quite what I want.

With the new "outline.show{Symbol}" settings in v1.40 one can customize the outline panel. However, it's not really useful to do `"outline.showVariables": false` if all your functions are declared like so:

```js
var fn = function() {};
```

I.e. they are all detected as vars and disabling them leaves you with an empty outline :confused: 

I know it's technically a variable but this is a common pattern, one would imagine.

**Comment by mjbvz** [comment]
We've discussed this before in https://github.com/microsoft/TypeScript/issues/14830

Trying to be clever and say that `var x = function` is a function can cause unexpected behavior in other cases. If you feel this should be revisited, please [file a an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
