### ISSUE TITLE
Activity Bar UI Quirks

### ISSUE THREAD

**Issue by ahmadawais** [microsoft/vscode#84353]
The latest VSCode activity element background color makes it easy to redesign the interface in a sidebar-connected to the activity style as shown below:

![vscode](https://on.ahmda.ws/c922e7/c)

There's a weird looking extra space at the top though. Can we make it better?

![vscode](https://on.ahmda.ws/9cd84b/c)

You can test this with latest version of my 🦄 [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) theme.
 
- VSCode Version: 1.40
- OS Version: macOS High Sierra

Does this issue occur when all extensions are disabled?: Yes

Looking forward!

**Comment by ahmadawais** [comment]
Another issue. If I zoom in with <kbd>COMMAND (⌘)</kbd> + <kbd>+</kbd> or zoom out with <kbd>COMMAND (⌘)</kbd> + <kbd>-</kbd> — I see an extra 1px of border on the right side.

Here's a gif demo:

![issue](https://on.ahmda.ws/e95884/c)

**Comment by misolori** [comment]
Activity bar highlight background should be fixed and we've removed the top space up top:

![image](https://user-images.githubusercontent.com/35271042/68967849-00e94d80-0796-11ea-9878-bbdd0060c865.png)

**Comment by ahmadawais** [comment]
Awesome thank you so much!
