### ISSUE TITLE
F2 stopped working properly after recent update

### ISSUE THREAD

**Issue by Avivhdr** [microsoft/vscode#84356]
- VSCode Version: 1.40.0 (user setup)
- OS Version: Microsoft Windows 10 Enterprise

Steps to Reproduce:

1. Putting the cursor on a variable inside a function
2. pressing F2
3. Renaming the variable in the input that apears.
4. Pressing Enter.

Expected results:
1. All appearances of the variable in the scoop will be renamed
2. No error should appear.
2. I could preform the same action again (on the same variable or on another one).

Actual Results:
1. All appearances of the variable in the scoop were renamed.
1. I got the following error message:
![image](https://user-images.githubusercontent.com/23265867/68510282-c2c2ca00-027b-11ea-8c63-56bfcf73b327.png)
2. When trying F2 for the second time i got the following message and the input in which i should enter the new name didn't appear:
(I was pressing F2 when the cursor was on "_channel_index_") :
![image](https://user-images.githubusercontent.com/23265867/68510343-f30a6880-027b-11ea-8171-672ab35ec258.png).

Does this issue occur when all extensions are disabled?: 
No, when the extension is disabled, pressing F2 doesn't trigger any reaction.

The extension is called "TypeScript and JavaScript Language Features".
The error indicates a TypeScript issue.
I don't use typescript at all so i do not need it's features.

Restarting vscode and disabling & enabling the extension didn't help,

Thanks a lot!

**Comment by mjbvz** [comment]
Can you please share the TS Server log so we understand why the server restarts in the first place:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. Back in VS Code, go to the `TypeScript` section of output panel
1. At the very top of this output, there should be a line that prints the path to the main server log. It look like this (note the `<semantic>` part) :

```
[Info  - 4:06:59 PM] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191111T144045/exthost1/vscode.typescript-language-features/tsserver-log-F2rDlk/tsserver.log
```

Please look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate
