### ISSUE TITLE
NO SUCH FILE OR DIRECTORY

### ISSUE THREAD

**Issue by Yash10bloodstorm** [microsoft/vscode#84363]
![fjejef](https://user-images.githubusercontent.com/52369876/68527178-2693d400-030a-11ea-899e-18f37bbe325c.PNG)

- VSCode Version: 1.40.0
- OS Version : windows 10

Steps to Reproduce:

1.Clone a repo with github desktop 
2.Run a file in the cloned repo

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Yash10bloodstorm** [comment]
![Capture](https://user-images.githubusercontent.com/52369876/68527607-c0f61680-030e-11ea-8f2f-3b3a04a2c92b.PNG)
changed when i reloaded the window

**Comment by alexandrudima** [comment]
Please create an issue directly against https://github.com/microsoft/vscode-python
