### ISSUE TITLE
Zen mode toggle in full screen - window restored goes over the screen

### ISSUE THREAD

**Issue by laimonas** [microsoft/vscode#84362]
-  Maximize vscode
-  Enter Zen mode
-  Leave Zen mode
-  Restored window goes beyond screen resolution

Version 1.40

**Comment by imba-tjd** [comment]
Probably dup of https://github.com/microsoft/vscode/issues/84362

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/84343
