### ISSUE TITLE
explorer.confirmDelete: false - does not work with right click-delete in file explorer

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#84361]
- VSCode Version: Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version: 1903 (18362.418)

Steps to Reproduce:

1. Set `"explorer.confirmDelete": false,`
2. Try to delete a file in the file explorer by right-clicking and selecting Delete. You will still get a question to confirm the delete.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce. Are you doing something differently than me?
Can you reproduce with latest vscode insiders 
https://code.visualstudio.com/insiders/

![he](https://user-images.githubusercontent.com/1926584/68691314-d324be80-0573-11ea-8f50-e234e3842721.gif)

**Comment by thernstig** [comment]
It fails for me on latest insiders as well. It might be worth to note that I am using VS Code Remote with wsl (1.0) with Ubuntu. So I try to delete a file via a Windows 10 VS Code installation for a file in /home/username/project

![example](https://user-images.githubusercontent.com/30827238/68693087-ee44fd80-0576-11ea-8c29-dbdb374cd12b.png)

**Comment by isidorn** [comment]
Because the confirmDelete setting is only for moving files to trash.
Not for permant deletions. And when on WSL the file system provider simply does not support moving files to trash.

So this is designed behavior. Since for permant deletion we always ask (you can not get the file back).
However I can understand how you would like the confirmDelete to aslo cover this case. Thus I will leave this open as a feature request.

**Comment by thernstig** [comment]
@isidorn I know you closed this one https://github.com/microsoft/vscode/issues/80309 but it would make more sense for permanent deletion (without a confirmation dialog) in case the file deleted is git controlled.

**Comment by isidorn** [comment]
Sure. However git is an extension, and we support other scm providers and the explorer is scm agnostic. So not possible atm.
