### ISSUE TITLE
Updated to 1.40.0, code not starting

### ISSUE THREAD

**Issue by miku86** [microsoft/vscode#84360]
Hey folks,

Problem:
After updating my `code` version, it won't start.

VS Code version: Code - OSS 1.40.0
OS version: Linux x64 5.3.8-arch1-1

![code-update-error](https://user-images.githubusercontent.com/7271016/68526907-24694f80-02e1-11ea-818c-20ae7ef94879.png)

Steps to Reproduce:

1. Upgrade from `1.39.2 => 1.40.0`
2. Try to open `code` from terminal
3. Error `electron4[4139]: ../../third_party/electron_node/src/node_file.cc:897:void node::fs::InternalModuleStat(const FunctionCallbackInfo<v8::Value> &): Assertion args[0]->IsString() failed.`

Solution:
1. Downgrade `1.40.0 => 1.39.2`

Does this issue occur when all extensions are disabled?: Yes

Thanks for reading.

**Comment by nobol** [comment]
Seems to be arch related: https://bugs.archlinux.org/task/64432?project=5&string=code

**Comment by Berkmann18** [comment]
I have the same issue on GNU/Linux 5.3.8-arch1-1 x64.

**Comment by wedeluxe** [comment]
I ran into the very same issue moments ago on my
Arch Linux (5.3.8-arch1-1 x86_64) system.

**Comment by tort-dla-psa** [comment]
can confirm this for arch too, happened to me just now

**Comment by Berkmann18** [comment]
`code-1.40.0-2` seems to have this issue fixed :tada:.

**Comment by miku86** [comment]
> `code-1.40.0-2` seems to have this issue fixed tada.

Exactly, Electron 6 was added and it is working again.
Thanks for contributing, I'll close it.
