### ISSUE TITLE
The execution directory of the native jupyter should be aligned to the original one.

### ISSUE THREAD

**Issue by S-aiueo32** [microsoft/vscode#84375]
Thank you for your native support for jupyter notebooks recently.
However, I'm afraid the execution directory specification is not compatible with the original one.
I'll show the concrete explanation as follow.

---

In this explanation, we will work with the following data structure:
```
[root]
  |--[notebooks]
  |    |-[foo.ipynb]
  |--[data]
       |-[bar.jpg]
```

**[CASE1]**
If we start the original jupyter server on `root`, we can access `bar.jpg` as `../data/bar.jpg` from `foo.ipynb`.

**[CASE2]**
If we work with vscode opened on `root`, we can only access `bar.jpg` as `./data/bar.jpg` from `foo.ipynb`.

These different behaviors will confuse users and decrease code compatibility, so the specification should be aligned to the original one.

**Comment by alexandrudima** [comment]
Please create an issue directly against https://github.com/microsoft/vscode-python

**Comment by S-aiueo32** [comment]
thx your pointing
