### ISSUE TITLE
Reloading UI

### ISSUE THREAD

**Issue by gs8407** [microsoft/vscode#84378]
Hi,

I have a problem on my work and home PC (Windows 7 and 10) with reloading UI of the VS Code on Minimize/Maximize. It takes 2-3 seconds, and it is annoying for the front end development. That started from th 1.40 update. I've tried with both hardware acceleration and without.

Please solve the issue.

Thanks,
Goran

**Comment by bpasero** [comment]
@gs8407 does it reproduce if you configure `"window.titleBarStyle": "native"`?

**Comment by gs8407** [comment]
It works fine with native settings for Title Bar Style. Why does it make the problem?

**Comment by bpasero** [comment]
This sounds like a duplicate of recently opened https://github.com/microsoft/vscode/issues/84343
