### ISSUE TITLE
property focus on tasks configuration not working

### ISSUE THREAD

**Issue by filucian** [microsoft/vscode#84377]
Issue Type: <b>Bug</b>

I run a task that watches all files and displays problems in the problems tab of the terminal. Need this because VSCode does not recognize errors in files not open in editor.

_**The cursor keeps jumping from editor into the problems tab filter input when the compiler detects any error.**_

The property **focus** does not prevent this behaviour. Have tried restarting the task and also the editor to no avail.

Please advise as the jumps happen in the middle of edits. Even if the problems tab is minimised, the terminal opens up and cursor jumps again. 

tasks.json for your reference.
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "watch",
      "problemMatcher": "$tsc-watch",
      "isBackground": true,
      "presentation": {
        "reveal": "silent",
        "revealProblems": "onProblem",
        "focus": false
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.89GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
custom-window-zoom|cra|1.1.4
vscode-eslint|dba|1.9.1
vscode-quick-select|dba|0.2.8
vscode-faker|dee|1.3.0
gitlens|eam|10.1.2
react-native-react-redux|EQu|2.0.3
prettier-vscode|esb|2.3.0
auto-rename-tag|for|0.1.1
RelativePath|jak|1.4.0
vscode-peacock|joh|3.1.6
better-line-select|kai|1.1.1
wrapSelection|kon|0.6.8
vscode-dashboard|kru|1.5.5
graphql-for-vscode|kum|1.15.3
metago|met|2.11.0
vscode-scss|mrm|0.6.2
vscode-typescript-next|ms-|3.8.20191105
vscode-typescript-tslint-plugin|ms-|1.2.2
debugger-for-chrome|msj|4.12.1
vscode-jest|Ort|3.0.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.0
autoimport|ste|1.5.3
lorem-ipsum|Tyr|1.2.0
vscode-icons|vsc|9.5.0
quokka-vscode|Wal|1.0.259
wallaby-vscode|Wal|1.0.156
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
You have `"revealProblems": "onProblem",`, which is literally designed to do this.

**Comment by filucian** [comment]
Hi Alex,

Many Thanks for your quick reply. 
Removing revealProblems from tasks.json did stop the editor from losing focus. 

Please do humour me and correct me if my reading of the documentation for _focus_ and _revealProblems_ is incorrect.

From [focus documentation](https://code.visualstudio.com/Docs/editor/tasks#_output-behavior)

``` focus: Controls whether the terminal is taking input focus or not. Default is false. ```

From [revealProblems documentation](https://code.visualstudio.com/updates/v1_34#_tasks) 

``` The new revealProblems task property allows you to automatically show the Problems panel. ```

My understanding is: 
1. _focus_ should control how terminal pane receives focus. However, in both scenarios above, I find that _focus_ value has no impact on the terminal pane.
2. _revealProblems_ should control if problems panel shows or not. It should not affect focus.


 
Bugs Observed:
---

* Bug 1: 
**Observed behaviour**:  tasks.json configuration displays Problems panel AND _**grabs focus from the editor**_
    ```
    "presentation": {
      "revealProblems" : "onProblem",
      "focus": false 
     }
    ```
    **Expected Behaviour**: Problems tab should show on Error but should NOT grab focus.


* Bug 2: 
    **Observed behaviour**:  below tasks.json configuration does not display a minimised Terminal tab, and does NOT grab focus
    ```
    "presentation": {
        "focus": true,
        "reveal": "silent"
     },
     ```
    **Expected behaviour**: Terminal should show up regardless of errors AND editor should lose focus.
---

Please close the topic if my understanding above is not correct.

**Comment by alexr00** [comment]
`focus` only concerns the terminal, not the problems panel. It would probably make sense for `focus` to apply to the problems panel and the terminal though.

`reveal: silent` only shows the terminal if there are errors.
