### ISSUE TITLE
Terminal scrolled to top unexpectedly immediately after opening

### ISSUE THREAD

**Issue by rianquinn** [microsoft/vscode#84379]
- VSCode Version: 1.40 (but has been for a while now)
- OS Version: Windows (might be on Linux too but cannot remember... definitely on Windows)

Steps to Reproduce:

1. Work for a while
2. Close terminal
3. Open terminal
4. The terminal will be scrolled to the top, and show the last thing you saw. When you attempt to scroll up, however, that doesn't work. If you scroll to the bottom, you will see the same thing you saw on the top. 

![image](https://user-images.githubusercontent.com/5932003/68529945-b9794200-02fb-11ea-99f6-ae7de0b5c9d7.png)

You cannot tell... but the terminal is scrolled to the top after I opened it even though there is a lot of stuff in the terminal. 

Does this issue occur when all extensions are disabled?: Not sure. I only use remote development (I don't have a way to use VSCode without that feature).

**Comment by ratatoeey** [comment]
a gif or screencast or multiple screenshots would be nice to help understand the issue.

**maybe its because I don't use the built-in terminal in any app.** I will, once they get good enough.

----

regards ratatoeey

**Comment by Tyriar** [comment]
Related: Integrated terminal resets scroll position to top when emacs is closed

**Comment by Yanpas** [comment]
Confirm that it appeared after 1.40

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/84145
