### ISSUE TITLE
Low latency canvas w/Electron 6

### ISSUE THREAD

**Issue by gonzalezjo** [microsoft/vscode#84376]
Electron 6 supports [low latency canvas contexts](https://blog.chromium.org/2019/05/chrome-75-beta-low-latency-canvas.html) which are designed to massively cut down on latency in input areas. This feature was originally developed for things like [drawing](https://developers.google.com/web/updates/2019/05/desynchronized) (in the literal sense of the word) using a stylus on a screen using NaCl, but it has since made its way into more traditional JS. 

It's really only 1-2 lines of code added, and should (in theory) improve both responsiveness and performance for VS Code's canvases. (Not that the integrated terminal isn't fast enough!)

**Comment by alexandrudima** [comment]
Let's start with the integrated terminal to see if this can indeed help and then we can look into adopting it everywhere...

**Comment by Tyriar** [comment]
So I tried this out and I can't really tell whether it makes a different, I mean it feels like it's a little faster I guess but I can't tell if that's just my mind knowing it's the tab with desync or not. It's also a little tough to actually measure this sort of thing, there's this app https://github.com/pavelfatin/typometer but I'm not on a Windows machine right now and I had trouble running that on xterm.js-based terminals in the past.

Regarding WebGL, if you weren't aware I made a WebGL renderer sometime ago but never got around to polishing it up. The desync guide explicitly calls out that you must use `preserveDrawingBuffer: true` or you'll get tearing, which we do _not_ set (we set it only for tests). The reason for `preserveDrawingBuffer` is that it was faster to maintain 2 buffers on the web side and _swap_ them, handing off one to the GPU and continuing the next frame on the other buffer, than _copying_ the single buffer over to the GPU and potentially blocking on the following frame when it's time to update the buffer. I tried setting desync there and it didn't seem to cause tearing and again couldn't really eyeball a difference 🤷‍♂

The hope is to eventually remove the canvas renderer and replace it with the webgl one so maybe it's not worth pursuing this at all?

**Comment by gonzalezjo** [comment]
Thank you for the update, and thanks for linking me to Typometer. 

I had no issues using xterm.js and Typometer together on a Linux machine. Interestingly, though, I measured a regression when I patched xterm.js to use desynchronized. I had my system run at 800 mh/z to run these tests to exaggerate any performance issues.



![Patched800mhz VS Original800mhz distrib](https://user-images.githubusercontent.com/22648562/68543457-3d2b4100-0385-11ea-9ad2-1b5f018dcb88.png)
![Patched800mhz VS Original800mhz](https://user-images.githubusercontent.com/22648562/68543458-40263180-0385-11ea-9041-e9b157edf1e5.png)



A slowdown and spikier distribution for desynchronized canvases was observed over 4-5 repetitions of this and across two repetitions when running at 3.2 gh/z. 


While there's a chance that desynchronized is more efficient with different graphics drivers, OSes, hardware configurations, etc., I'm not convinced at all by what I'm seeing right now. 


I think this issue can be closed. Just out of curiosity, before I close this, would you be able to link to your branch (if it's public) with the WebGL renderer?

**Comment by Tyriar** [comment]
Nice, thanks for looking into that!

> Just out of curiosity, before I close this, would you be able to link to your branch with the WebGL renderer?

It's actually in master and this issue inspired me to work some more on it over the weekend, adding true color support and selection colors. To get it to work you just need to click the "webgl" checkbox under the addons section. I'd be very interested to see the latency when using the webgl addon.

**Comment by gonzalezjo** [comment]
@Tyriar I would be glad to check. Do you mind explaining where the addons section is? I'm having difficulties finding it.

**Comment by Tyriar** [comment]
@gonzalezjo down towards the bottom of the demo page:

<img width="586" alt="Screen Shot 2019-11-24 at 12 02 33 PM" src="https://user-images.githubusercontent.com/2193314/69500703-528a8a00-0eb2-11ea-871b-1ca24d0d9afb.png">
