### ISSUE TITLE
Live Share login issue with browser callback

### ISSUE THREAD

**Issue by dasiii** [microsoft/vscode#84389]
- VSCode Version:
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64
- OS Version:
Mac OS Catalina 10.15.1 

Steps to Reproduce: 

1. Click Live Share to prompt browser window sign in
2. Sign in and authorize with GitHub
3. Redirected to "Visual Studio Live Share: Sign In Success"
4. However, "Starting collaboration session: Sign in to proceed" notification still shown in vscode and never signed in.

Tried the following:
- Safari Version 13.0.3 and Google Chrome Version 78.0.3904.97
- Fresh install of vscode after full uninstall https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac
- Removing the live share folder in `.vscode/extensions` and reinstalling Live Share.
- Added `// - "https://*.visualstudio.com"` to the bottom of the list in `\Trusted Domains`

Happy to provide more info upon request, no visible error messages shown.

**Comment by alexandrudima** [comment]
Can you please report directly against https://github.com/MicrosoftDocs/live-share
