### ISSUE TITLE
Jupyter Notebook: Markdown cell not saved on when cursor escapes cell

### ISSUE THREAD

**Issue by sataset** [microsoft/vscode#84381]
- __Description__: Markdown cell not saved on when cursor escapes cell

- __Type__: Bug (?)

- __Steps to reproduce__:
  1. Type something in markdown cell
  2. Press `Down` key to move cursor to the next cell
  3. Markdown cell looses content that were just typed in 

- __Expected behaviour__: Cell content is saved (as it works when changing focus to another cell by click)

- __VSCode Version__: 1.39.2
- __OS Version__: Ubuntu 18.04.3

**Comment by usernamehw** [comment]
You should file this against the corresponding extension.
