### ISSUE TITLE
The 'Additional Views' overflow action only shows up on hover

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#84387]
Please see the attached video. Notice that the overflow '...' action is only shown on hover, which means the user already has to know that there are more views available in order to find the action and to use it. In other places of the UI the overflow action is always visible. For example, in the activity bar the action is always shown (see below)

![overflow](https://user-images.githubusercontent.com/172399/68531537-8773da00-0313-11ea-9e66-1a426b929367.gif)

![image](https://user-images.githubusercontent.com/172399/68531578-1f71c380-0314-11ea-9973-8763181c662c.png)

**Comment by bpasero** [comment]
@misolori should this be a candidate for recovery?

**Comment by egamma** [comment]
Added the `candidate` label for discussion.

**Comment by chrmarti** [comment]
Reopening for book-keeping.

**Comment by chrmarti** [comment]
Discussed at standup. Please push to release branch.

**Comment by misolori** [comment]
Fixed via https://github.com/microsoft/vscode/pull/84493, will queue up a build to verify my fix.
