### ISSUE TITLE
[Bot] Add `/causedByExtension` tag

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#84385]
For community issue tracking it would be helpful to have `/causedByExtension` command that would add `*caused-by-extension` label and close the issue with the appropriate message.

**Comment by ratatoeey** [comment]
> close the issue with the appropriate message

if its a extension built-in to vscode?
----

regards ratatoeey

**Comment by usernamehw** [comment]
Except `built-in` extensions.

**Comment by chrmarti** [comment]
Turns out that was already there, I have now also documented it: https://github.com/microsoft/vscode/wiki/Community-Issue-Tracking 👍
