### ISSUE TITLE
I cannot download any extensions on VSCODE

### ISSUE THREAD

**Issue by Dan245** [microsoft/vscode#84388]
Issue Type: <b>Bug</b>

Hi, I recently downloaded vscode for school, and everything was working great (I was able to download extensions no problem)! A couple weeks later though, I'm unable to install any extensions. The messages stated: "failed to download [extension], try downloading manually", which I've tried to no avail. I've tried all the tips I've seen online of this issue and nothing is working. I reinstalled vscode, but the same problem occurred. I tried disabling my proxy's, but that didn't work either. Please help.

P.S. The extensions I am mainly trying to install are: WPIlib, C/C++, and LiveShare. I have also tried to install other extensions to no avail.

Update: I was able to install the following extensions: Markdownlint, HTML Snippets, and HTML CSS Support. I tried other extensions but was unable to install them.

Update 2: I can now install extension again! Not sure what I did exactly, I was fiddling around with my computer for something different, maybe I fixed he problem? Either way I'm happy. I'll keep this feed open for another day in case something goes wrong.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3530  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.44104
java|red|0.52.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1

</details>

**Comment by Dan245** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Hello, when downloading to my MacBook, it keep saying, 'it cannot be downloaded.' (#83613)](https://www.github.com/microsoft/vscode/issues/83613)

I checked and it's not the same issue but thank you Mr.Bot

**Comment by sandy081** [comment]
Closing this as the issue got fixed.

**Comment by Dan245** [comment]
Thanks, sorry I completely forgot about it.
