### ISSUE TITLE
Feature Request: html.format.preserveNewTextLines

### ISSUE THREAD

**Issue by rasamassen** [microsoft/vscode#84386]
VSC 1.4.0 on Win10
Steps: HTML File "Format Document" (Shift+Alt+F)
[https://code.visualstudio.com/docs/languages/html#_formatting](https://code.visualstudio.com/docs/languages/html#_formatting)

The current html.format.preserveNewLines, as described in Settings, "only works before elements, not inside tags or for text"

Rendered HTML does not respect new lines in text, but Format Document will auto-wrap at 120 (the default; or whatever html.format.wrapLineLength is set at).

The result of multiple Format Documents after multiple edits is this:
```
        <p>When many related provisions are parts of a unit that are considered <b>inseparable</b>, they normally
            are <b>lettered</b>
            “a,” “b,” “c,” etc. When related provisions are part of a unit but considered <b>separable</b>, such as a
            list of
            duties, they are normally <b>numbered</b> in sequence. If the related provisions cannot be clearly judged to
            be
            separable or inseparable, preference will be given to a number sequence.</p>
```

A huge number (half in this case) of lines that are wrapped prematurely because as text was changed, wraps were inserted by Format Document but never removed.

Again,
```
            <dd><u>The policies and procedures for such and such</u> shall be developed by the appropriate organization
                unit,
                reviewed
                by the Leadership Board.</dd>
```

It would be really nice if Format Document (Shift+Alt+F) would take the above HTML and make it

```
            <dd><u>The policies and procedures for such and such</u> shall be developed by the appropriate organization
                unit, reviewed by the Leadership Board.</dd>
```
Obviously this should be an Setting, as some programmers may intentionally want to preserve new lines in text, but if html.format.preserveNewLines can retain or remove line breaks before elements, there should be a setting to do the same for text inside tags.

This setting would clear a huge headache for programmers that are constantly editing their HTML text.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
