### ISSUE TITLE
migration to electron 7 for insiders

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#84384]
done.

"electron 7" in vscode. assuming its the preferred instead of beta releases of electron.

saw https://github.com/microsoft/vscode/issues/83930, but there was no companion issue. 

main benefit seems to be https://github.com/electron/electron/pull/20789, in addition to usual updates. 

----

regards ratatoeey

**Comment by ratatoeey** [comment]
i would test but multiple reasons just make me avoid it. the yarn requirement being one of them.

also would it be easier to migrate to electron 8 as its not stable yet?
----

regards ratatoeey

**Comment by ratatoeey** [comment]
from https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
 can it be installed using scoop? that would be great.
----

regards ratatoeey

**Comment by ShubhamBelwal** [comment]
There is no companion issue for electron 7 upgrade, but there is a pull request: #83796

**Comment by deepak1556** [comment]
This has been completed, electron 7 is in current stable release `1.43.x`
