### ISSUE TITLE
Support undo and redo in input fields and native dialogs

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#8439]
- VSCode Version: 1.2.1
- OS Version: OS X

It's  nice feature of Sublime Text that you can undo what you typed in the search box. Please add that feature to VSCode.

**Comment by bpasero** [comment]
Related https://github.com/Microsoft/vscode/issues/11011

**Comment by bpasero** [comment]
We do some magic with Cut, Copy, Paste where we send the command to the browser if no editor is focussed. I think we should do the same for Undo/Redo if possible.

See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L28

**Comment by atombender** [comment]
I think this deserves the labels "bug" and "important". Having no undo/redo in the find/replace input fields, in 2016, is a bit of a shock.

**Comment by bpasero** [comment]
@atombender you can right click and pick Undo/Redo easily, so there is a workaround.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/151
