### ISSUE TITLE
Visual bug after resizing interactive Python shell

### ISSUE THREAD

**Issue by siddharthbakshi** [microsoft/vscode#84396]
- VSCode Version: 1.40.0
- OS Version: Windows 10 1903
- Python Version: 3.7.5
- ipython Version: 7.9.0
- pylint Version: 2.4.3

Issue:
After resizing the interactive Python shell and printing a list from the shell, there is dead space beneath the shell's input box (please refer to the lower right side of the screenshot). This bug is not present in VS Code 1.39.2.

![image](https://user-images.githubusercontent.com/43690825/68533277-72d41980-02f4-11ea-8c6a-2b392d121fe9.png)

Steps to Reproduce:

1. Launch an interactive Python shell.
2. Print a list using the shell's input box.
3. Dead space is added beneath the input box.

Does this issue occur when all extensions are disabled?: No. However, Python code cannot be run without the Python extension (ms-python.python).

**Comment by sbatten** [comment]
@mjbvz Is the webview getting shorter dimensions somehow?

**Comment by mjbvz** [comment]
@sbatten This looks more like a bug with the python extension. Our editor layout seems ok, it's the webview content itself that seems off

@siddharthbakshi Please file this against the python extension
