### ISSUE TITLE
Hope vscode provide account login function

### ISSUE THREAD

**Issue by hanzebang** [microsoft/vscode#84391]
I hope that vscode provides account login function. You can synchronize the custom configuration and corresponding plug-ins on different devices. I believe many people hope to have such a function. Many programmers have their own preferences, whether it's a shortcut or a variety of plugins. When we replace the device, we have to reconfigure it. I hope to add the account login function, which is more convenient for configuration synchronization. thank you very much!

**Comment by sandy081** [comment]
*duplicate
