### ISSUE TITLE
CSS: Terminal has a mistake when to see Extension detail.

### ISSUE THREAD

**Issue by linbingquan** [microsoft/vscode#84395]
- VSCode Version: 1.40.0
- OS Version: Win10

Steps to Reproduce:

1. Ctrl + ` open terminal
2. Open Extensions and click Python

Does this issue occur when all extensions are disabled?: Yes

![图片](https://user-images.githubusercontent.com/23699926/68533284-836ea900-0361-11ea-8c4d-05359061cab1.png)

**Comment by sbatten** [comment]
@mjbvz also a dupe of https://github.com/microsoft/vscode/issues/83209?

**Comment by mjbvz** [comment]
Yep, duplicate of #83209
