### ISSUE TITLE
Visual Code crashed firefox on running live server

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#84392]
I am using Visual Studio Code October Version 1.40.
The issue I am facing with the Visual Code is that it does fail to launch Live Server in the Mozilla Firefox. 
I have installed following extensions:
1. Live Server
2. Docker
3. ESLint
4. C/C++
5. PHP Debug
6. PHP Extension Pack
7. PHP Intellisense
8. Python
9. React Native Tools
10.SQL Server

**Comment by iaxat** [comment]
I would like to explain the issue a bit more, I am running Ubuntu 19.10, the browser I use as default is Mozilla Firefox 70. When I try to launch the web-server, it directly shows a crash report, but instead Firefox is already running in the background without any issues. I tried to send the crash report to the Firefox but the visual code does not let me click on anything and it doesn't matter wherever I click on the crash window, it closes automatically. There is no problem with the Firfox.

**Comment by alexandrudima** [comment]
@iaxat I am still a bit confused about your setup. What exact steps are you doing and what exactly are you opening in Firefox?

**Comment by iaxat** [comment]
I am trying to run HTML code and use the plugin for live edit. Basically I am doing what the plugin is used for. And I use firefox, and it is not working. The plugin is not able to launch firefox and shows that firefox crashed, but at the same time I am using firefox in the background.

**Comment by alexandrudima** [comment]
Thank you for the extra information. Please report this issue directly against LiveServer at https://github.com/ritwickdey/vscode-live-server/issues
