### ISSUE TITLE
Debugger dosn't show variables from std::map when that variable type has configured in natvis

### ISSUE THREAD

**Issue by ykuchin** [microsoft/vscode#84397]
- VSCode Version:
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64

- OS Version:
Linux portable 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2

Steps to Reproduce:
1. build and run attached project
2. stop at nb.cpp:30
3. look at variable 'm' and 'v' in 'locals' 

You can see natvis-configured variables in vector, but you can't see variables in map. 

Also you can enable debug pretty printing from gdb in launch.json, by adding '-x ${workspaceFolder}/nb.gdb' to miDebuggerArgs. Pretty printers from gdb always shows variables from vector and map.

[natvis_bug.zip](https://github.com/microsoft/vscode/files/3827699/natvis_bug.zip)

**Comment by alexandrudima** [comment]
Can you please open directly against https://github.com/microsoft/vscode-cpptools
