### ISSUE TITLE
Window min height

### ISSUE THREAD

**Issue by DoctorRu** [microsoft/vscode#84398]
Can't resize editor main window to a smaller height (it's useful when you are coding and watching a tutorial)

**Comment by cfxd** [comment]
I'm experiencing this too. It's only recent (last 2-3 days). I'm on OS X 10.12.16. Here's my version info:

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 16.7.0
```

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/84134
