### ISSUE TITLE
Separate sections for installed Features and Themes in default view of Extensions sidebar

### ISSUE THREAD

**Issue by alexleduc76** [microsoft/vscode#84390]
In the Extensions sidebar, clicking the "..." menu at the top-right gives the option to filter by built-in extensions. In this view, it separates extension by Features, Programming Languages and Themes. 

My feature request is to be able to filter the user installed extensions by these categories too.

As many other VS code users, I sometimes go crazy and install dozens of different themes, but unfortunately it ends up cluttering the default Extensions view and there is no was to filter/classify them by the above mentioned categories.

**Comment by sandy081** [comment]
Re https://github.com/microsoft/vscode/issues/68527
