### ISSUE TITLE
default encoding

### ISSUE THREAD

**Issue by godwish** [Microsoft/vscode#844]
i love vs code 

i want fix default encoding.

1. open txt

2. default encoding is utf-8

3. i will reopen with encoding. why? open txt is different encoding (save euc-kr, but open utf-8)

but notepad show well.

i know utf-8 have signature at front from file

have no signature -> open system default encoding.

please fix this issue.

i wan't more good program.

**Comment by bpasero** [comment]
You can change the default encoding in settings.

**Comment by godwish** [comment]
ok i see. i test your story.

set encoding euckr 

ok first solved

but i have new problem

save utf-8 -> load file -> txt is crash

why? vs code load default encoding.

utf-8 , euckr 2 file load only default encoding. (now euckr)

i think this is problem.

vs code must support identify file encoding.

will be more useful tool.

**Comment by bpasero** [comment]
we do support detecting the encoding when you use a BOM for UTF-8, 16 LE and 16 BE.

**Comment by godwish** [comment]
Thank you for letting me reply.

i afraid..my answer make you tired.

run save file and open file. ( set default encoding - euckr )
1. utf-16 le - is ok
2. utf-16 be - is ok
3. utf-8 crash

loaded utf-8 txt read encoding  = euc-kr

all txt saved vs code .

Not a lie.

It was not found.

save with encoding option utf-8 bom.

only utf-8

**Comment by bpasero** [comment]
Thats true, we don't offer a way to save UTF-8 with BOM, but see #751
