### ISSUE TITLE
Links open an empty chrome browser

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#84409]
VSCode Ubuntu 19.10

I was unable to update VS code:  when I clicked the "Download Update" button I get an empty google chrome browser.

So I updated thusly:
```
wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb
sudo dpkg -i /tmp/code_latest_amd64.deb
```

After the successful update I clicked on a link in the releasenotes markdown of VScode and it similarly opened an empty chrome window.

I have no trusted domains and just click "Open Link" when prompted.

This may be similar to #84265

**Comment by cawoodm** [comment]
Running `require('electron').shell.openExternal('https://google.com')` produces no error in the developer tools but again Chrome is opened without a URL.

**Comment by cawoodm** [comment]
```
$ electron --version
v5.0.1
```

**Comment by Tyriar** [comment]
@deepak1556 links not opening correctly under Ubuntu 19.10?

**Comment by cawoodm** [comment]
I can confirm that `google-chrome http://google.com`  works from the terminal but `xdg-open http://google.com` does not. It could well be an issue with my chrome...

**Comment by cawoodm** [comment]
OK, fixed thanks to [this guy](https://askubuntu.com/questions/540939/xdg-open-only-opens-a-new-tab-in-a-new-chromium-window-despite-passing-it-a-url/540940#540940).

## Solution
* Edit the file `~/.local/share/applications/google-chrome.desktop`
* Ensure the `Exec=` line contains `%U` in my case `Exec=/usr/bin/google-chrome-stable  --password-store=basic %U`
