### ISSUE TITLE
The column order in DataViewer in Python extension is mixed up

### ISSUE THREAD

**Issue by CoarseSand** [microsoft/vscode#84408]
- VSCode Version: 1.38.1
- OS Version: Ubuntu 18.04.3 LTS
- Python Extension version: 2019.10.44104

I am currently debugging python code that involves numpy arrays within jupyter using the DataViewer feature of the Python extension. However, the order in which the columns of every 2D numpy.ndarray I try to view using the DataViewer is mixed up.

![dataviewer](https://user-images.githubusercontent.com/26901008/68540073-78526200-03cf-11ea-88f9-a08b3e9454c2.png)

I'm developing in a remote container that is attached to a docker container that's running:

Ubuntu 16.04.6 LTS
Python 2.7.12
numpy 1.16.5
jupyter 1.0.0
jupyter-client 5.3.4
jupyter-console 5.2.0
jupyter-core 4.6.0
notebook 5.7.8

How would I be able to change the column order back to normal i.e., in increasing order 1, 2, 3, ...?

**Comment by alexandrudima** [comment]
Please report directly against https://github.com/microsoft/vscode-python
