### ISSUE TITLE
Error when starting code from within WSL

### ISSUE THREAD

**Issue by shelmire** [microsoft/vscode#84400]
- VSCode Version: 1.40+
- OS Version: Windows 10 Pro OS build 17134.48

Steps to Reproduce:

1. Upgrade VS code to 1.40 (or use latest code-insiders).
2. From WSL / Ubuntu shell, try to open something with code (like `code foldername`).
3. Get error: Error: EINVAL: invalid argument, uv_pipe_open vscode

Downgrading to 1.39 resolves the issue. This has been reported on other issues (linked) and was marked as resolved, but it seems that there has been a regression. I also get the error with latest code-insiders.

https://github.com/microsoft/vscode-remote-release/issues/1420
https://github.com/microsoft/vscode-remote-release/issues/1490

**Comment by aeschli** [comment]
What verison of Remote WSL do you use?

When you see the error message, is there still a remote WSL window opened, or is the command no longer working?

I'm not able to reproduce on 
Remote WSL version: 0.40.2,
VSCode 1.41.0-insider (user setup)
Commit: 213bdddb72ff7a6c8eed071420de8ddac4293cb1
Date: 2019-11-11T05:40:31.150Z
OS: Windows_NT x64 10.0.17134
