### ISSUE TITLE
Image preview: can no longer scroll with mouse wheel

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#84406]
- Version: 1.40.0
- OS: Linux x64 4.18.0-041800-generic

Steps to Reproduce:

1. Open an image
2. Zoom until scrollbars appear
3. Try to scroll with `mouse wheel` and <kbd>shift</kbd> + `mouse wheel`

**Comment by hologerry** [comment]
Can't scroll with trackpad either.
