### ISSUE TITLE
"code ." command isnt working after October update in Vscode.

### ISSUE THREAD

**Issue by ggoel1998** [microsoft/vscode#84407]
code . command which ran in terminal of Ubuntu 18.04 stopped responding and returns error "command not found"
1.40- VSCode Version
18.04 LTS Ubuntu- OS Version:

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What does `which code` return?

**Comment by ggoel1998** [comment]
Using command `code .` runs VScode in that particular directory in which terminal is opened .
After update ,1.40, this command isnt recognized by shell .
I installed VS code using `sudo` apt-get install `command`

**Comment by joaomoreno** [comment]
If you roll forwards, can you reproduce?

**Comment by ggoel1998** [comment]
Okay so i did that, using `which code` it returns "command code not found"

**Comment by joaomoreno** [comment]
How did you roll forward/backward?

**Comment by Tyriar** [comment]
Works for me. Nothing changed in the deb package around this.

**Comment by sartrey** [comment]
similar problem found.
my env is WSL + Ubuntu 18.04 + VSCode 1.40.1.
at first i installed VSCode in Windows by installer and cannot find “install <code> command in PATH”.
so i installed WSL extension for VSCode, opened a new WSL terminal in VSCode and tried to run <code> in it.
then I installed nvm + node in an external WSL terminal.
after these actions, problem solved.

**Comment by joaomoreno** [comment]
@sartrey This is about Linux. WSL seems to be a separate issue, so please file one.

**Comment by ggoel1998** [comment]
> How did you roll forward/backward?

using `sudo apt-get update`

**Comment by Tyriar** [comment]
@ggoel1998 can you run the following?

```
ls -la /usr/bin | grep code
ls -la /usr/share/code/bin | grep code
```

Also did you get any errors/warnings when you updated?

The symlink is installed here: https://github.com/microsoft/vscode/blob/6b78be028629ac52ba980ace1d60f077d9493c9b/resources/linux/debian/postinst.template#L8
