### ISSUE TITLE
建议vscoder改进功能

### ISSUE THREAD

**Issue by manhoo** [microsoft/vscode#84405]
Issue Type: <b>Feature Request</b>

现在开发人员都使用多个监视器，终端无法浮动，不方便

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by zwuis** [comment]
@manhoo English please.

**Comment by hua03** [comment]
He needs a terminal window that can move freely outside of vscode main window.
