### ISSUE TITLE
Unable to restore down window size

### ISSUE THREAD

**Issue by Liang-Chu** [microsoft/vscode#84402]
Issue Type: <b>Bug</b>

After I maximum the window size, the "maximum" button still remain there instead of become a "restore down" button

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362
>

**Comment by imba-tjd** [comment]
dup of https://github.com/microsoft/vscode/issues/84343

**Comment by wineinpink** [comment]
Just double click the title bar, the maximum button would become a restore button and then you can't resize the window by dragging the edges.
