### ISSUE TITLE
CSS and JS embedded inside HTML documents no longer has colorized syntax

### ISSUE THREAD

**Issue by shsui5379** [microsoft/vscode#84401]
Issue Type: <b>Bug</b>

Update VSCode to a recent Insider release (ex: on 11/8)
Create an HTML document and populate its <style></style> wtih CSS and its <script></script> with JavaScript
Notice how CSS/JS syntax is no longer colorized.  Only HTML is colorized now.  All 3 languages are supposed to be colorized by syntax.    

VS Code version: Code - Insiders 1.41.0-insider (27cd33d891eb23e370b672e751be9fe8b3748ac1, 2019-11-08T19:12:35.358Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.13.0
discord-vscode|icr|3.13.0
vscode-github|Kni|0.30.3
vscode-edge-devtools|ms-|1.0.4
debugger-for-edge|msj|1.0.12
material-icon-theme|PKi|3.9.1
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.0

(2 theme extensions excluded)

</details>

**Comment by Verduurzaming** [comment]
I have the same issue with HTML embedded in PHP files and vice versa. Only the primary language is tokenized.

**Comment by rodrigoelp** [comment]
Ah, I was about to submit the issue from my Mac. I can see it is broken as well on Windows.
I have disabled all the extensions and I still have the same issue.
