### ISSUE TITLE
Suggestion and Go to definition not working

### ISSUE THREAD

**Issue by nguyentd-uet** [microsoft/vscode#84413]
Issue Type: <b>Bug</b>

I cannot use suggestion and go to definition feature anywhere, any language. I tried deleting all settings and reinstalling but it didn't work. Please help me.
Thanks

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.93GB (17.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-react-native|msj|0.13.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by zasuh** [comment]
Same issue after 1.40.0 update

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by zasuh** [comment]
Would like to report that it's working now! 😄

**Comment by jrieken** [comment]
@nguyentd-uet ping for repro steps

**Comment by nguyentd-uet** [comment]
I think it happened when I initialized a react native project with expo, using nativebase and customized the theme following this tutorial:
https://docs.nativebase.io/Customize.html#theaming-nb-headref

**Comment by jrieken** [comment]
Can you try to repro a second time with that?

**Comment by nguyentd-uet** [comment]
I have reproduced that way.

**Comment by jrieken** [comment]
Does it reproduce when disabling extensions?

**Comment by nguyentd-uet** [comment]
Yes. I tried disabled all extensions but it still doesn't work. And I can use 2 features (Suggestion and Go to definition) when I start the app for few seconds.

**Comment by jrieken** [comment]
and in what files are you editing? JS, HTML, CSS?

**Comment by nguyentd-uet** [comment]
It's JS file.

**Comment by jrieken** [comment]
Ok, then please add the file and the *exact* steps that you are doing in that file so that it reproduces this

**Comment by nguyentd-uet** [comment]
This is the project I reproduced: https://github.com/nguyentd-uet/AwesomeProject
Steps to reproduce:
1. Init a **React native** project with **Expo**: https://facebook.github.io/react-native/docs/getting-started
2. Install **Nativebase** (setup with Expo): https://docs.nativebase.io/docs/GetStarted.html
3. Customize Nativebase theme by following this toturial: https://docs.nativebase.io/Customize.html#theaming-nb-headref

**Comment by jrieken** [comment]
> Install Nativebase (setup with Expo):

Sorry, but not doing that. This should reproduce without that, eg. by opening a file and interacting with that file

**Comment by nguyentd-uet** [comment]
2. Install Nativebase with Expo:
- Install NativeBase by: `yarn add native-base --save`
- Install Expo Fonts: `expo install expo-font`
3. Customize Nativebase theme:
- Run this command from your terminal: `node node_modules/native-base/ejectTheme.js`
- Raplace App.js by:
`import React, { Component } from 'react';
import { Container, Content, Text, StyleProvider } from 'native-base';
import getTheme from './native-base-theme/components';
import material from './native-base-theme/variables/material';
​export default class ThemeExample extends Component {
  render() {
    return (
      <StyleProvider style={getTheme(material)}>
        <Container>
          <Content>
            <Text>
              I have changed the text color.
            </Text>
          </Content>
        </Container>
      </StyleProvider>
    );
  }
}`

- After that I could not use Go to difinition and Suggestion

**Comment by jrieken** [comment]
<img width="797" alt="Screenshot 2019-11-12 at 13 53 14" src="https://user-images.githubusercontent.com/1794099/68673338-c7c19b00-0553-11ea-86d6-f828e6e816a6.png">

Works for me

**Comment by nguyentd-uet** [comment]
I don't know why but I tried on 3 different computers and all had the same error.
