### ISSUE TITLE
Font rendering messed up on macOS with non-default font, showing emoji instead of "fi"

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#84418]
- VSCode Version: 1.40.0
- OS Version: macOS 10.14.6

Steps to Reproduce:
1. Set font to `MesloLGM Nerd Font` installed via `brew install cask-fonts/font-meslo-nerd-font`
2. Try to autocomplete anything with "fi", for example `import fab<ctrl><space>` in Python in a file called `fabfile.py`.

This only happens in the auto-complete popup for now and seems to be caused by incorrectly enabling fontLigatures there despite it not being correctly supported by the font. The fact that the messed up ligature shows up is probably a bug in the font itself, but enabling ligatures shouldn't be done when the setting is disabled. I think the issue might be that the CSS for controlling ligatures doesn't make it's way somehow into the auto-complete hover, and maybe other locations.

![screenshot](https://user-images.githubusercontent.com/24731903/68545495-54464f00-03d6-11ea-97ab-cf9311c877df.png)

Does this issue occur when all extensions are disabled?: No

<details><summary>Extension versions</summary>

```
bungcip.better-toml@0.3.2
dbaeumer.vscode-eslint@1.9.1
eamodio.gitlens@10.1.2
ms-azuretools.vscode-docker@0.8.2
ms-kubernetes-tools.vscode-kubernetes-tools@1.0.6
ms-python.python@2019.10.44104
ms-vscode.cpptools@0.26.1
ms-vscode.Go@0.11.9
redhat.vscode-yaml@0.5.3
stkb.rewrap@1.9.1
```

</details>

**Comment by alexandrudima** [comment]
@segevfiner  That appears to be an issue with the font. Pleae report against the font itself.

**Comment by segevfiner** [comment]
@alexandrudima It is. But there is also an issue here of showing ligatures in autocomplete hovers despite them being disabled by VS Code's config.

**Comment by segevfiner** [comment]
The CSS that controls ligatures in other areas of the editor isn't applied there. VS Code didn't enable ligatures there in the previous version. This can cause ligatures to show up even for fonts that have working ligatures in auto-complete hovers.

**Comment by segevfiner** [comment]
For anyone coming here because they have this issue. I previously updated the unpatched Meslo LG font used by Nerd Fonts to a newer version and that one doesn't seem to have that problem (The guy who made the unpatched one explicitly removed the ligatures). The unpatched version is simply the powerline patched one, so the latest version of that one also won't have that problem. The old version of the powerline one will show a badly renedered fi ligature rather then a phone icon.

The versions from homebrew of both fonts are old. Nerd fonts hasn't made a release in a long time. And the powerline Meslo is simply outdated
