### ISSUE TITLE
Becomes unresponsive

### ISSUE THREAD

**Issue by halcwb** [microsoft/vscode#84415]
Issue Type: <b>Bug</b>

While editing an fsx file VSC becomes unresponsive for minutes. See screen shot.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|4.2.0
Ionide-Paket|Ion|1.12.0

</details>

![VSC unresponsive](https://user-images.githubusercontent.com/683631/68544612-4e943d80-03c5-11ea-9736-d06dfdf38d90.png)

**Comment by alexandrudima** [comment]
@halcwb Does this issue reproduce when disabling all extensions?

**Comment by hKaspy** [comment]
Maybe connected with https://github.com/microsoft/vscode/issues/84326?

**Comment by xuxicheta** [comment]
I have similar behavior.
Here is Typescript server log
```
[Info  - 7:47:39 PM] TSServer exited
[Info  - 7:47:39 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 7:47:39 PM] <syntax> Forking...
[Info  - 7:47:39 PM] <syntax> Starting...
[Info  - 7:47:39 PM] <semantic> Forking...
[Info  - 7:47:39 PM] <semantic> Starting...
[Info  - 7:49:44 PM] TSServer exited
[Info  - 7:49:44 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 7:49:44 PM] <syntax> Forking...
[Info  - 7:49:44 PM] <syntax> Starting...
[Info  - 7:49:44 PM] <semantic> Forking...
[Info  - 7:49:44 PM] <semantic> Starting...
[Info  - 7:52:09 PM] TSServer exited
[Info  - 7:52:10 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 7:52:10 PM] <syntax> Forking...
[Info  - 7:52:10 PM] <syntax> Starting...
[Info  - 7:52:10 PM] <semantic> Forking...
[Info  - 7:52:10 PM] <semantic> Starting...
[Info  - 7:53:53 PM] TSServer exited
[Info  - 7:53:53 PM] Using tsserver from: /usr/share/code/resources/app/extensions/node_modules/typescript/lib
[Info  - 7:53:53 PM] <syntax> Forking...
[Info  - 7:53:54 PM] <syntax> Starting...
[Info  - 7:53:54 PM] <semantic> Forking...
[Info  - 7:53:54 PM] <semantic> Starting...
```

**Comment by alexandrudima** [comment]
@xuxicheta Please open a separate issue

**Comment by egamma** [comment]
@halcwb this looks looks like an issue with the F# extension, please report the issue against this extension.
