### ISSUE TITLE
vscode.workspace.fs.readFile fails to open file via absolute path

### ISSUE THREAD

**Issue by jan-dolejsi** [microsoft/vscode#84416]
Following call to the `workspace.fs.readFile` causes an unexpected error

```typescript
vscode.workspace.fs.readFile(vscode.Uri.parse(context.asAbsolutePath('package.json')))
```

Error:

```txt
Error (FileSystemError): The path of resource 'c:\vscode-extension-samples\call-hierarchy-sample\package.json' must be absolute
extensionHostProcess.js:798
stack trace: Error (FileSystemError): The path of resource 'c:\vscode-extension-samples\call-hierarchy-sample\package.json' must be absolute
	at _handleError (c:\Users\[user]\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:552:466)
```

The path is obviously absolute.

- VSCode Version: 1.40.0
- OS Version: Win10

Steps to Reproduce:

There is no workspace folder open when I call this function and get the error. I call it from within the `activate` function.

Does this issue occur when all extensions are disabled?: It is caused by an extension code.

**Comment by jrieken** [comment]
`asAbsolutePath` returns a path and `Uri.parse` expects a uri, e.g something in this for `file:///path`. Please the `Uri.file` which works with paths.

**Comment by jan-dolejsi** [comment]
Indeed. My coding error! Sorry for the noise.
My wrong hypothesis that this is a bug was confirmed by the _The path of resource 'c:\...' must be absolute_.
