### ISSUE TITLE
what hightlight bug this is?

### ISSUE THREAD

**Issue by peaceshi** [microsoft/vscode#84410]
1.41.0-insider (system setup)
27cd33d891eb23e370b672e751be9fe8b3748ac1
2019-11-08T19:12:35.358Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

![20191110173447](https://user-images.githubusercontent.com/10380828/68541915-7218b180-03e0-11ea-953a-a6a0566fe2f9.png)

https://github.com/kcat/openal-soft/blob/74cbba511d6b71634d07d44a822c826400fe967d/al/error.cpp#L95

**Comment by peaceshi** [comment]
disable all extensions is useless.

**Comment by alexr00** [comment]
Moved to owning repo, but leaving open so I remember to pull in the fix when it happens. https://github.com/jeff-hykin/cpp-textmate-grammar/issues/414
