### ISSUE TITLE
Visual studio code frequently crashes since Catalina OS release

### ISSUE THREAD

**Issue by ConnectedReasoning** [microsoft/vscode#84417]
Issue Type: <b>Bug</b>

The crashes occcur on multiple scenarios but the most recen was when running reac-native run-ios on a fairly mature and stable react native application.  I has also happened when I attempted to run the view history

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|24, 14, 8|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
githistory|don|0.4.6
gitlens|eam|8.5.6
flow-for-vscode|flo|1.0.1
lintlens|ghm|2.7.0
beautify|Hoo|1.5.0
vscode-gutter-preview|kis|0.15.3
python|ms-|2019.1.0
debugger-for-chrome|msj|4.12.1
git-merger|sha|0.4.1
markdown-preview-enhanced|shd|0.3.11
html-preview-vscode|tht|0.2.5

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@ConnectedReasoning Can you please add some steps that cause crashes for you?

**Comment by ConnectedReasoning** [comment]
I will keep this updated as the crashes occur

**Comment by alexandrudima** [comment]
Ok

**Comment by ConnectedReasoning** [comment]
It just occurred. I woke up the mac, my screen was already in vscode. I moved my mouse over a folder in the explorer panel. I right clicked the folder and selected 'new file'. it happened twice in a row.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
