### ISSUE TITLE
Panel overflow icon no longer shows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84419]
Compare 1.40 stable:

![image](https://user-images.githubusercontent.com/900690/68546541-9754f200-03d7-11ea-8210-f13cff15b7e8.png)

To 1.39:

![image](https://user-images.githubusercontent.com/900690/68546543-9de36980-03d7-11ea-9203-7fd8af563081.png)

I am not seeing the "..." action anymore when panels are narrow. The element is in the dom though. Maybe a icon regression?

**Comment by bpasero** [comment]
Oh, on hover it appears to the top:

![image](https://user-images.githubusercontent.com/900690/68546551-b8b5de00-03d7-11ea-8a0e-a641962090be.png)

**Comment by gjsjohnmurray** [comment]
Already logged as #84387

**Comment by misolori** [comment]
Duplicate of #84387
