### ISSUE TITLE
Window Restore Button not working

### ISSUE THREAD

**Issue by josenriagu** [microsoft/vscode#84411]
Issue Type: <b>Bug</b>

I am on Windows 10 64-bit.
I noticed that that when I maximize the window and want to restore it to the  resized window, it doesnt have that restoe button again. I will have to manually resize it again.

Ideally Windows will have 3 buttons, minimize, maximise(if resized)/restore(if maximized), and close.

restore(if maximized) is the issue. it doesn't seem to appear when I have clicked mazimized. I will have to drag and resize the window manually each time.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/81102

**Comment by josenriagu** [comment]
Awesome! Keep it up

> Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!
