### ISSUE TITLE
Integrated terminal: Setting font size to 1 freezes application

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8441]
Testing #8222 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Open user settings, set terminal.integrated.fontSize to 1
2. Open console -> application freezes

**Comment by Tyriar** [comment]
Work on Linux:

![image](https://cloud.githubusercontent.com/assets/2193314/16484198/d0c1b32c-3e6c-11e6-9267-81bc2c452821.png)

**Comment by csholmq** [comment]
Works on macOS.

**Comment by chrmarti** [comment]
Can't reproduce anymore... (Tried Windows 8.1 and 10.)

**Comment by Tyriar** [comment]
Closing then, maybe you hit some other issue disguised as this?
