### ISSUE TITLE
Symbol renames get very slow and sometimes fail/timeout

### ISSUE THREAD

**Issue by brentwa** [Microsoft/vscode#8442]
- VSCode Version: 1.2.1
- OS Version: OSX 10.11.5 (El Capitan)

This is while editing Unity CSharp scripts.  I'm using the DotBunny Unity integration.

Steps to Reproduce:
1. Use the "Rename Symbol" command to rename a private member variable.
2. Repeat step #1 a few times (1-3).

After pressing <enter> on the rename prompt, there is a pause before the code changes.  The pause seems to get longer after each rename.  The first symbol is almost instantaneous.  The second can take several seconds.  Then 10-20 seconds.  Sometimes the code never updates.

If I quit and restart VSCode (or wait a few min), the first few renames are fast again, but then slow down.

ActivityMonitor shows very little CPU usage by VSCode while the rename is processing.

First noticed this with the June release (1.2.0, I think).

**Comment by bpasero** [comment]
@brentwa please report this against the Omnisharp repository.
