### ISSUE TITLE
Emojis not displayed correctly in the editor windows

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#84423]
Issue Type: <b>Bug</b>

1. Type the heart emoji – ❤️–  in a Markdown file.
2. Open Markdown Preview
Expected: The heart in the editor should display as a red and nice heart, like it does in the preview.
Actual: The heart displays as a small character (still heart shaped, but not the real emoji).

VS Code version: Code - Insiders 1.41.0-insider (27cd33d891eb23e370b672e751be9fe8b3748ac1, 2019-11-08T19:11:22.061Z)
OS version: Darwin x64 19.0.0

(The issue was introduced with VS Code 1.40.0. I just used Insiders to check that it hadn't already been fixed.)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|-psn_0_3580778|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Hey @alexandrudima, I think issue is that the editor itself doesn't display the colorful emoji (while the markdown preview does, as expected)

<img width="493" alt="Screen Shot 2019-11-11 at 10 12 44 AM" src="https://user-images.githubusercontent.com/12821956/68610103-da60a500-046b-11ea-9790-195992cd5888.png">

Assigning back to you

**Comment by PEZ** [comment]
This now seems fixed in `1.40.1`.

**Comment by PEZ** [comment]
Actually. That is not the case at all. On my computer (a MacBook Pro, see system info in the OP) I have two user accounts. If I start code `--disable-extensions` from one of the accounts I have the issue, from the other I don't. Please let me know if there is some diagnostics I can provide that could help pinpoint the source of the problem.

**Comment by alexandrudima** [comment]
@PEZ The emoji is ultimately rendered with a font. Can you please:
1. Clarify if the emoji is not rendered correctly in the editor or in the markdown preview. Please include a screenshot to remove any possible misinterpretation.
2. Check to see what are the differences in `settings.json` between the two user accounts
3. (if you have customized the font family) Check that you have installed fonts in a way that they are available to all users.
