### ISSUE TITLE
macOS: File > Open no longer adds files to recently opened

### ISSUE THREAD

**Issue by TuulaP** [microsoft/vscode#84421]
Issue Type: <b>Bug</b>

I have number of files and folders which I work with. I have opened them with Code and then closed editor. Usually they have been available via the File > Open Recent -feature the next day, but now have noticed that list is empty. There are only files which I have open today, but all earlier files are gone. (VS Code Insiders seems to remember its recent files, but now for some time the Code side has not.) 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (18.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.31.2
vscode-eslint|dba|1.9.1
php-debug|fel|1.13.0
terminal|for|0.0.10
gc-excelviewer|Gra|2.1.32
Python-autopep8|him|1.0.2
rest-client|hum|0.22.2
latex-workshop|Jam|8.3.1
vscode-language-opensees|jam|0.1.2
praat-vscode|jor|0.0.1
restructuredtext|lex|116.0.0
python|ms-|2019.10.44104
remote-containers|ms-|0.83.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
cpptools|ms-|0.26.1
remote-vscode|raf|1.1.0
java|red|0.52.0
datetime|rid|1.0.5
jupyter-notebook-vscode|sam|0.0.2
tcl|sle|0.2.0
Align|ste|0.2.0
unique-window-colors|stu|1.0.51
tpsnippet|vii|0.0.1
lorem-ipsum|Tyr|1.2.0
terminal-tabs|Tyr|0.2.0
vscodeintellicode|Vis|1.2.0
robotframework|viv|0.1.3
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details>

**Comment by TuulaP** [comment]
/wave bot ;)   I open the file via File-> open from within the Code. I can concur with the earlier one, but since it is closed maybe it is good to have a another reminder.

**Comment by bpasero** [comment]
Did you maybe invoke "Clear Recently Opened"? That would remove all entries.

**Comment by et304383** [comment]
Not sure if related, but I have noticed that recently the open recent list is not being updated with files I open and close.  New bug?

**Comment by bpasero** [comment]
Depends on how you open them, e.g. the list is only updated via File > Open.

**Comment by et304383** [comment]
> Depends on how you open them, e.g. the list is only updated via File > Open.

Pretty sure that wasn't the case.  Never mattered how the file was opened.

**Comment by bpasero** [comment]
Can you provide exact steps? And run code with `--user-data-dir` to ensure a fresh state.

**Comment by et304383** [comment]
```
mkdir ~/vscode
code --user-data-dir ~/vscode
```
Open file via File -> Open
Close file tab
Open recent
Recent list is empty

**Comment by et304383** [comment]
FYI: rolled back to 1.39.2 and the issue disappears.  This is definitely part of the latest release (1.40.0)

**Comment by bpasero** [comment]
True, I can confirm that.

**Comment by bpasero** [comment]
Up for grab, somehow we no longer add files to the recent list when opened via File > Open on macOS. The method to call is `IWorkspacesService.addRecentlyOpened`. I can confirm that this used to work in version `1.39.x`.

**Comment by et304383** [comment]
Should note that if I open from the CLI it doesn't help either:

```
code file.txt
```

**Comment by TuulaP** [comment]
In my case I'm on windows, so did

### 1st run:
> 
> cd C:\dev\
> mkdir codetemp
> code --user-data-dir  C:\dev\codetemp

I get this warning, dunno if it has any impact, but if it helps:
"You are running the system-wide installation of Code, while having the user-wide distribution installed as well" ok for that.
 
File > Open Recent is now empty

I go File -> open and pick F:\somerandomtest\kirk.txt  add a line, and save it and exit code via the window close x at top right.

### 2nd run:

I start up code again via the same user-data-dir and the 1st file is there and it is also in the recent file list.  So I close that tab, and open another file via File -> Open and pick janeway.txt and edit it a bit and then close its tab, and exit code via File->Exit.

### 3rd run:

I open the code again using the same dir, both files are available in the recent files, too.

### Workaround

Weird, with --user-data-dir everything seemed to work as expected, so I can use that as an workaround. 

(Anyhow I used to have huge number of files, and even had to search some from the open recent->more list and they were there. So whole feature was very useful and helpful).  I'll hope that custom directory content stays put even after reboot, or after the next time code updates itself, but we shall see. (Or I just backup that folder and restore it if something weird happens).

(I also have the code insiders version 1.41 installed and there the recent file list has happily stayed put, at least so far... )

**Comment by bpasero** [comment]
@aeschli this broke with https://github.com/microsoft/vscode/commit/6c0fe8cb04ff9acdbabe9ac83ee7b7c39bb4f049, I can see that filesToDiff is always an empty array so we never add to history anymore.

Putting as candidate.

**Comment by aeschli** [comment]
Thanks for catching this.
@bpasero Thanks for the investigation
