### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by pim-pesochek** [microsoft/vscode#84426]
Issue Type: <b>Bug</b>

When I use my touchpad to scroll the source code, sometimes when I do this fast I see that editor starts freezing the scrolling process. From that moment  every attempt to scroll source code is stucking.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (6 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (8.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
font-switcher|eva|3.1.0
intellij-idea-keybindings|k--|0.2.37
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
rust|rus|0.7.0
crates|ser|0.4.5
vscode-make|tec|1.0.2

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/76594
