### ISSUE TITLE
Version 1.40 does not start anymore on Win 7 SP 1 with NET 4.5.2 installed

### ISSUE THREAD

**Issue by whiffee** [microsoft/vscode#84428]
Hi All,

version 1.39.2 will install and run on Win 7 SP 1 with NET 4.5.2 installed (and no updates), but 1.40.0 shows a black screen on launch.

**Comment by uki-tz** [comment]
I just installed 1.40.0 on Win 7 SP1 and have the same problem

**Comment by bpasero** [comment]
@whiffee @uki-tz odd, can you try another Electron based application and see if that opens? Thinking about Electron Fiddle: https://electronjs.org/fiddle

**Comment by whiffee** [comment]
electron-fiddle-0.11.0-x64-setup would not run. The msg was "The procedure entry point SetDefaultDllDirectives could not be located in the dynamic link library KERNEL32.dll."

I could add that installing 169 updates does fix the problem, though at the cost of partially breaking Parallels 10.4. (and adding 16.5 GB of weight).

**Comment by bpasero** [comment]
@deepak1556 you might want to update our platform requirements (at https://code.visualstudio.com/docs/supporting/requirements) if there is a more recent SP required for Windows 7.

//cc @gregvanl

**Comment by whiffee** [comment]
@bpasero Deferring to your judgment and authority, but it might be nice to let people know that 1.39 runs without updates. If so then the note

/*Additional Windows requirements

.NET Framework 4.5.2 is required for VS Code. If you are using Windows 7, please make sure .NET Framework 4.5.2 is installed.*/

could become some thing like

/*Additional Windows requirements

.NET Framework 4.5.2 is required for VS Code. If you are using Windows 7, (and wish to install version 1.40 of VS Code or later), Windows Updates beyond SP 1 may be required. */

**Comment by deepak1556** [comment]
Windows 7 is no longer supported, for additional context please refer https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7
