### ISSUE TITLE
Respect Windows Metered Connection when downloading extensions automatically

### ISSUE THREAD

**Issue by Tracy-P** [microsoft/vscode#84424]
Issue Type: <b>Feature Request</b>

I started VS Code on Windows today on a network connection I have set as a metered connection. VS Code downloaded nearly 100 MB on a slow connection. Slow as in dialup slow. 

Would you please consider adding a popup dialog asking if the downloads should occur on the metered connection?

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
You can disable auto updates.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/10746682/68579476-7a223100-0474-11ea-9af3-3f88513d5e98.png">
