### ISSUE TITLE
Python Interactive display bug

### ISSUE THREAD

**Issue by arotem3** [microsoft/vscode#84427]
Issue Type: <b>Bug</b>

Python interactive prompt line moves up the screen after 'shift-enter' with blank space appearing underneath. 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 5.3.0-19-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.16GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|3.0.8
vsc-material-theme|Equ|30.0.0
fortran|Gim|0.2.0
matlab|Gim|1.4.0
mdmath|goe|2.4.0
language-cython|guy|0.0.6
python|ms-|2019.10.44104
cmake-tools|ms-|1.2.1
cpptools|ms-|0.26.1
cmake|twx|0.0.17

(3 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@arotem3 I am not sure if this is an issue with VS Code or the [python extension](https://github.com/microsoft/vscode-python). Can you please share a screenshot?

**Comment by arotem3** [comment]
![Screenshot from 2019-11-12 11-03-28](https://user-images.githubusercontent.com/40644295/68697601-680bc580-053c-11ea-80af-c55c08218d8a.png)

The command line shifts up the screen. I am also able to scroll its location up and down the screen once it happens.

**Comment by JDisselhorst** [comment]
I have this same issue on Windows, it appeared after the October update. It is also present in the insiders build. 
The command line moves up after typing a command, it can be moved back by scrolling, but this has to be done every time. In my case it does _not_ happen when I use print, e.g., `print('a')`, but it does when I do for example `import os` or `np.zeros((50,50))`. In fact, just typing `print(` without executing will fix the location of the command line (for that moment, afterwards the same wrong behavior happens after executing non-print statements).
My versions:
Version: 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5)
Version: 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37)
OS: Windows_NT x64 10.0.17134

**Comment by jadhosn** [comment]
Also facing the same issue
![image](https://user-images.githubusercontent.com/17963295/68873491-f5762380-06bc-11ea-8b08-7bcd92d395c0.png)

**Comment by egamma** [comment]
Thank you for the screenshots. Please file the issue against the python extension.
