### ISSUE TITLE
The integrated terminal `zsh` doesn't take effect of new changes.

### ISSUE THREAD

**Issue by tuanbs** [microsoft/vscode#84434]
Issue Type: <b>Bug</b>

The integrated terminal `zsh` doesn't take effect of new changes. For example, I use macOS terminal (`zsh` as default shell) to install `npm`. But when I open VS Code integrated terminal, it doesn't know `npm`. I even restarted it but no luck.

Then I notice if I select default shell as `bash`, then it works. So I guess must be something wrong with VS Code integrated terminal using `zsh`.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
csharp|ms-|1.21.6

</details>

**Comment by tuanbs** [comment]
I notice if I select default shell as `bash`, then it works. The default shell is `zsh`. So I guess must be something wrong with VS Code integrated terminal using `zsh`.

**Comment by Tyriar** [comment]
These types of issues are related to your setup. Things to try:

- Look into where in your zshrc/profile aren't getting run
- Do you want to run as a login shell or not? Check the `terminal.integrated.shellArgs.osx` setting
- Did you setup npm in your .bashrc but not your .zshrc?

**Comment by tuanbs** [comment]
> These types of issues are related to your setup. Things to try:
> 
> * Look into where in your zshrc/profile aren't getting run
> * Do you want to run as a login shell or not? Check the `terminal.integrated.shellArgs.osx` setting
> * Did you setup npm in your .bashrc but not your .zshrc?

Thanks for your suggestions. I fixed it by creating `~/.zshrc` file and adding this line `export ASPNETCORE_ENVIRONMENT=Development` into `~/.zshrc` file, then refresh it. Cheers.

@vscodebot Wow, didn't know the VS Code team now uses the Bot to close the github issue automatically. :)))

**Comment by Tyriar** [comment]
@tuanbs I closed it because I identified it as an issue with your environment; the issue tracker is not a support forum for general questions but a way to report bugs and ask for features.
