### ISSUE TITLE
Allow Extensions to use native modules shipped with vscode

### ISSUE THREAD

**Issue by go2sh** [microsoft/vscode#84439]
It would be nice to use the node-pty module shipped with vscode in an extension. Currently, I'am doing the following:
```
//@ts-ignore
const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
const moduleName = path.join(vscode.env.appRoot, "node_modules.asar", "node-pty");
const spawn: typeof import('node-pty').spawn = requireFunc(moduleName).spawn;
```
It should be possible to create a require interceptor injecting the parrents `node-pty` object into the extension.

This is especially nice as there is no general way of loading platform dependent code.

**Comment by alexandrudima** [comment]
@go2sh Well, keep doing what you're doing... But keep an eye out, as your extension might get broken by a future VS Code update... Platform specific extensions is something we have on our radar and we track that at https://github.com/microsoft/vscode/issues/23251

Here is the code pattern that you can use:
```
/**
 * Returns a node module installed with VSCode, or null if it fails.
 */
function getCoreNodeModule(moduleName: string) {
    try {
        return require(`${vscode.env.appRoot}/node_modules.asar/${moduleName}`);
    } catch (err) { }

    try {
        return require(`${vscode.env.appRoot}/node_modules/${moduleName}`);
    } catch (err) { }

    return null;
}
```

i.e. please always handle the failure case and inform users...
