### ISSUE TITLE
Unable to add new keybindings - “value is not accepted” 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#84436]
Issue Type: <b>Bug</b>

As I also reported in [this SO question]((https://stackoverflow.com/questions/58793414/keybindings-value-is-not-accepted-after-the-1-40-update)), a number of us experienced this problem. Warnings in `keybindings.json` prevent us from adding new shortcuts. In my case, this happens with a particular extension [vscode-emacs-mcx](https://github.com/tuttieee/vscode-emacs-mcx)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.1.4
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.31.2
gitlens|eam|10.1.2
LogFileHighlighter|emi|2.6.0
shell-format|fox|6.1.3
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.32
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.3.1
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
sqltools|mtx|0.21.2
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.5.3
vscode-dired|rru|0.0.4
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.0
emacs-mcx|tut|0.13.0
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
org-mode|vsc|1.0.0
highlight-trailing-white-spaces|yba|0.0.2
markdown-all-in-one|yzh|2.5.1

</details>

**Comment by ArturoDent** [comment]
And in my case, creating a keybinding with the mulit-command extension works just fine but has been labelled with a warning for a few updates now.  And only after the v1.40 update vscode can no longer write into keybindings.json because of this error notification

<img width="541" alt="vscodeError" src="https://user-images.githubusercontent.com/31813701/68552871-9fb22a80-03e1-11ea-8a52-a51f0e0c2c9d.png">
 And so vscode refuses to write into keybindings.json, as when removing keybindings from "Keyboard Shortcuts".

![vscodeError2](https://user-images.githubusercontent.com/31813701/68552924-4696c680-03e2-11ea-87f0-fae4418d0505.jpg)Version: 1.40.0 (user setup)


Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19018

**Comment by sandy081** [comment]
This is because the parser needs option `allowTrailingComma` to be set to `true`. It was default to `true` before. @aeschli Looks like this was added in last milestone and not adopted in keybindings service.

https://github.com/microsoft/vscode/commit/ce9f8e1c94fe768d555bd57061942ddc86cda944

**Comment by sandy081** [comment]
Verification Steps:

- Open `keybindings.json` file
- Add a trailing comma to the entries
- Open keybindings editor and change a keybinding
- Make sure keybinding is changed without any errors

**Comment by amelio-vazquez-reina** [comment]
Thanks @sandy081 👍 

QQs:

1. For users in 1.40, what options do they have until the November release?
2. Since #84472 was just merged, is it safe to assume that this would be fixed in the  **Insiders** version tonight?

**Comment by sandy081** [comment]
1. This is accepted for October recovery release which will be available soon.
2. Yes this will be available in tomorrow's insiders

**Comment by ArturoDent** [comment]
This appears to be fixed in today's Insiders' Build.  Thank you.  

Something also got rid of the `Value is not accepted.` warnings that I was getting whether there was a trailing comma or not for a few releases.   Was this commit the fix for that as well?

**Comment by sandy081** [comment]
I would think so. Please try out and let us know.

**Comment by ArturoDent** [comment]
Yes, those warnings - I understand a few extensions started showing those warnings back with the February 2019 release - have now disappeared from my Insiders' Build.  I had those warnings whether there was a trailing comma or not.  That is why I was wondering if this commit (which I thought was about trailing commas) was intended to also fix those warnings - which certainly seemed to be unrelated to a trailing comma issue.

**Comment by ultraGentle** [comment]
I am still experiencing this issue.  
VSCode Version: 1.40.1

Despite the warning, the highlighted keybinding works as expected. 

Additionally, if I wish to add a new keybinding from the GUI, I must temporarily cut the block in the picture, then paste back after the new command has been added.  

![Screen Shot 2019-11-14 at 1 38 57 PM](https://user-images.githubusercontent.com/41548755/68886098-772d7780-06e4-11ea-8123-06625c762414.png)

**Comment by sandy081** [comment]
Can you please try to filter entries in your file and provide us with the minimal contents with which you can reproduce this?

**Comment by ultraGentle** [comment]
It happens even if it is the only entry in the file (see screenshot).  

Please note that the same error has occurred with keybindings assigned to trigger other extensions, so it's not unique to "Tab Out."   

![Screen Shot 2019-11-14 at 2 46 22 PM](https://user-images.githubusercontent.com/41548755/68890916-e360a900-06ed-11ea-8f48-0b9534c40eac.png)

If I misunderstood your request, please let me know and I'll provide additional info.

**Comment by sandy081** [comment]
@ultraGentle I am able to update keybinding when I have above entry in my keybindings file. Which version of VS Code are you on?

**Comment by ultraGentle** [comment]
Updating keybindings:
• from text file --> works
• from GUI --> fails: "error, unable to write to keybindings file, please correct errors or warnings."

However, GUI works if I temporarily remove the offending block (see my previous).  

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Comment by sandy081** [comment]
What is the error you are getting?

**Comment by ultraGentle** [comment]
Same error as reported by Arturo Dent at the top of this thread (see screenshots from that post).

**Comment by sandy081** [comment]
I am not able to reproduce it with 1.40.1 and with latest insiders. Can you please try insiders and let me know if it still occurs?

https://code.visualstudio.com/insiders/

**Comment by ultraGentle** [comment]
I can no longer reproduce the main issue, which was that a warning in the custom keybindings text file prevented new keyboard shortcuts from being added from the GUI.  I can't think of anything I did to resolve it, but still, good news.  

Just FYI, the more minor issue is that the "value not accepted" warning still appears in the custom keybindings file, even though the keybinding does actually work.
