### ISSUE TITLE
Some dates in front matter (yaml) are not being marked as timestamps

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#84435]
```
---
a: b
a: 2019-10-1
a: 2019-10-10
---
```

![image](https://user-images.githubusercontent.com/2193314/68552393-67075680-03cb-11ea-90d0-6e449f37963e.png)
![image](https://user-images.githubusercontent.com/2193314/68552399-6c64a100-03cb-11ea-9da7-9fe94ef13a7e.png)
![image](https://user-images.githubusercontent.com/2193314/68552401-71c1eb80-03cb-11ea-82fc-f24cc869b263.png)

Version: 1.41.0-insider (user setup)
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1
Date: 2019-11-08T19:12:35.358Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/microsoft/vscode/issues/84435
