### ISSUE TITLE
Add "Add Config (user settings)..." option in  Debug view dropdown

### ISSUE THREAD

**Issue by Pytal** [microsoft/vscode#84433]
I recently stumbled upon the [Global Launch Configuration](https://code.visualstudio.com/docs/editor/debugging#_global-launch-configuration) feature  in which launch configuration settings are stored within the user's settings.json file instead of within the launch.json file inside the .vscode workspace folder.

It would be great if this feature was made more discoverable by adding an "Add Config (user settings)..." option under the Debug view dropdown 👌.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not plan to tackle it in the near future.
Thus leaving it open for now.
