### ISSUE TITLE
Settings sync for settings GUI

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84431]
We need to provide some UI for settings sync, especially for resolving simple conflicts without dropping the user into a JSON diff.

https://github.com/microsoft/vscode/issues/78966

**Comment by misolori** [comment]
Here's the conceptual mockups for resolving conflicts. When we detect that there are conflicts, we will prompt the user either via a notification:

<img width="75%" src="https://user-images.githubusercontent.com/35271042/71297522-a5802180-2338-11ea-829f-49a12c8f0e7e.png">

Or via the settings gear:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/71297532-b0d34d00-2338-11ea-977a-1975021e9671.png">

This will lead them to the Settings GUI (if `workbench.settings.editor` is set to `ui`) and we'll enter the `@conflicts` query into the search bar which will bring up the conflicts UI:

<img width="1024" alt="Ressolve Conflict - Large" src="https://user-images.githubusercontent.com/35271042/71297640-23dcc380-2339-11ea-8e9c-0d8cf7363d6d.png">

- If there is more than 1 conflict, we will add a "Sync All..." action at the top
- We'll show two primary options for each setting, similar to our merge conflicts UI 
- Additionally we'll provide an option to "ignore" the conflict, which adds the setting to the "do not sync" list
- After the user selects an option, this should remove it from the list
- When all conflicts are resolved, we should automatically update the server

When we get to in narrow views, we'll adjust the layout and stack the conflicts:

<img width="852" alt="Ressolve Conflict - Small" src="https://user-images.githubusercontent.com/35271042/71297641-24755a00-2339-11ea-8749-f68f41d959cb.png">

If strings are long and require it to wrap, we'll grow the conflict container (making sure the "Ignore Setting" action is adjusted):

![image](https://user-images.githubusercontent.com/35271042/71297945-6783fd00-233a-11ea-9cdc-d7e81d809514.png)

**Comment by sanket-bhalerao** [comment]
1. Is vscode insiders build and vscode stable going to be treated differently?
As we can install/enable experimental extension/setting in insiders build.
2. is there going to be separate installed/enabled extension sync for insiders and stable vscode installations?

**Comment by misolori** [comment]
@sanket-bhalerao please see https://github.com/microsoft/vscode/issues/2743#issuecomment-560116420 for all things related to Settings Sync, this issue is specifically for the UI in the Settings GUI.

**Comment by thernstig** [comment]
The terms `Sync Local` and `Sync Remote` does not make it immediately obvious what they mean. Does `Sync Local` mean I will upload my local settings to the remote (i.e. overwrite the remote settings), or does it mean that I will synchronize my local settings with the remote (i.e. overwrite the local settings)?

I feel the terms will be interepreted differently by users.

Would e.g. writing `Select` or `Pick` or `Choose this` or `Use this` or something else instead on both sides make more sense? Because I assume that selecting either one will still sync the selected setting to the remote?

**Comment by misolori** [comment]
@thernstig I think this is something we'll iterate on to find the right verbiage to describe this behavior. This is also why we decided to add icons to help illustrate it better. IMO, select/pick/choose doesn't bring any more clarity.

**Comment by sandy081** [comment]
@roblourens 

Implemented `ISettingsSyncService` that can provide the state of settings sync and also can access conflicts and resolve them

https://github.com/microsoft/vscode/blob/f14dd3f77f87f93a2d59b4f9b2ebf5913a8c5063/src/vs/platform/userDataSync/common/userDataSync.ts#L201-L206

**Comment by roblourens** [comment]
Notes on the API

- I need an event for when conflicts change, not just when we change from not having conflicts to having conflicts
- I'm not sure about getConflicts returning a Promise. Ideally I would just listen for the event that says there are conflicts, and at that moment, there would be an array of conflicts. Since this is used in the process of rendering the settings UI, I don't want to block that on file accesses or IPC. If it's not easy for the SettingsSyncService to make that change, it can be worked around on my end. But if the SettingsSyncService can work that way, it would be slightly more convenient.

**Comment by sandy081** [comment]
@roblourens Changed it as requested

https://github.com/microsoft/vscode/blob/cd4472ed5fd79551d95acf7d9ed23ce20cb2233d/src/vs/platform/userDataSync/common/userDataSync.ts#L201-L206
