### ISSUE TITLE
Add symbol kind or symbol tag to express that some is local to a function 

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#84443]
Issue Type: <b>Feature Request</b>

It's great to see filtering of the outline by type - `outline.showVariables` in particular makes it much more useful for navigation by removing the clutter of listing every individual variable.  So thanks!  However, I'd still like the ability to hide _function_ locals (while still showing class or module level functions), specifically callbacks.

For example, I have this function in my project:

```javascript
function categoryCompletions(concreteCompletions: string[]): string[] {
    return concreteCompletions.map((c) => c.split('.'))
                              .filter((bits) => bits.length >= 2)
                              .map((bits) => bits[1])
                              .distinct()
                              .map((c) => `bundle.${c}`);
}
```

As I've configured the Outline view to hide variables, I'd like this to appear as a single entry with no children.  Instead, what I see is this:

![image](https://user-images.githubusercontent.com/865538/68557925-3e02c680-049c-11ea-8853-ea317cc074ad.png)

It doesn't take many functions like this before the Outline view becomes so busy that I can't easily find my top-level items.  And to me, those callbacks aren't really _functions_ - they're arguments to the `map`, `filter` etc. calls which _happen to be of function type_.  It would make sense if they were large named functions that were part of the overall structure of the function... but in this case at least they are not...

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18912

**Comment by jrieken** [comment]
requires new API and extensions to adopt it

**Comment by custompro12** [comment]
+1 for being able to keep function declarations, but hide callbacks.  I think even just an `Outline: Show Callbacks` option would be great.

**Comment by custompro12** [comment]
> +1 for being able to keep function declarations, but hide callbacks. I think even just an `Outline: Show Callbacks` option would be great.

With the ultimate goal of being able to hide all function locals, but still show class/module level property/function declarations.

**Comment by thorn0** [comment]
@itowlson Renaming this issue might make it more noticeable. Something along the lines "Filter out callbacks from Outline" would be good.
