### ISSUE TITLE
Very slow with 1.40 update

### ISSUE THREAD

**Issue by KalDhondup** [microsoft/vscode#84446]
Issue Type: <b>Bug</b>

very slow experience compare to previous version. my gulp serve takes hell lot of time to start. Please check.

-in help it says Checking for update ( infinite ) though my network speed is 36Mbps.
-in task manager it has multiple process task with huge value of memory value. but CPU value is 0 for all.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
tortoise-svn|fan|0.1.1
vscode-edge-devtools|ms-|1.0.4
csharp|ms-|1.21.6

</details>

**Comment by hKaspy** [comment]
Maybe connected with https://github.com/microsoft/vscode/issues/84326?
