### ISSUE TITLE
Window flickers when resizing from borders

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#8444]
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 10.0.14366

Steps to Reproduce:

1. Open VS Code
2. Try resizing from a corner
3. Observe that the entire contents of the window flickers with black

**Comment by bpasero** [comment]
@dilijev did this not happen before in 1.2.x? can you attach a video?

**Comment by dilijev** [comment]
@bpasero it *does* seem to happen in 1.2.1. It might be related to graphics card or windows graphics stack with multiple graphics cards, since I've only observed this on my third monitor which is driven by my second graphics card.

I haven't had problems with any other windows except (a possibly unrelated symptom) when maximized UWP windows are closed on that monitor, it shows the desktop briefly and then re-renders whatever was underneath. It's also possible this is an issue with the window handling model in 14366.

Happy to attach a video. What screen recording tool would you recommend?

**Comment by bpasero** [comment]
Does it also happen when you disable GPU in Code by running `code --disable-gpu`? Are you running inside a VM?

**Comment by dilijev** [comment]
Nope, running on insider previews on my desktop. I just got updated to 14372. I'll see if I can still repro.

**Comment by bpasero** [comment]
@dilijev "nope" you cannot repro when GPU disabled?

**Comment by dilijev** [comment]
Sorry -- should have been more clear.

No I am not running in a VM -- instead running on my desktop in an insider build.

I am trying the --disable-gpu option now.

**Comment by dilijev** [comment]
I tried with

```
code-insiders -n
code-insiders --disable-extensions -n
code-insiders --disable-gpu -n
code-insiders --disable-extensions --disable-gpu -n
```

No repro on any mode on any monitor with the following system setup:

- VSCode Version: Code - Insiders 1.3.0-insider (a21c12346f388e51858c930875ca30968604c116, 2016-06-30T05:07:11.570Z)
- OS Version: Windows_NT ia32 10.0.14372

I'll close this issue.

**Comment by dilijev** [comment]
Side note: `code-insiders -h` does not show the `--disable-gpu` option.

**Comment by bpasero** [comment]
Yes, it is very internal from Chromium framework.

**Comment by dilijev** [comment]
@bpasero Ah, that makes sense. I noticed some similar flags between Chrome and VS Code when I looked at the command lines in Task Manager. Figured Chromium was the reason.
