### ISSUE TITLE
Cannot open VSCode snap package after October 2019 update!

### ISSUE THREAD

**Issue by farzadmf** [microsoft/vscode#84448]
Maybe worth noting: VSCode is installed as a snap package

- VSCode Version:
```
code --version

1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64
```
- OS Version: Manjaro Linux, kernel version: `5.3.8-1-MANJARO`

Steps to Reproduce:
1. Open VSCode
2. Wait a couple of seconds and it closes by itself

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
Does running `code --verbose` say anything? Can you try download the tarball from the website and see if that opens?

**Comment by farzadmf** [comment]
Thank you @Tyriar for your reply, I'll try what you suggested in a few hours (when I get back to my computer at home)

**Comment by dvail** [comment]
Same issue on Ubuntu 18.04 after the 1.40 update. Code opens up, then hangs and crashes after about 4-10 seconds. Running `code -n --disable-extensions --disable-gpu` and all combinations of these flags gives the same behavior. `code --verbose` doesn't give any obvious errors.

Running `gdb /usr/snap/code core` against the core file shows a Seg Fault again with nothing I can make sense of.

**Comment by farzadmf** [comment]
I don't think I see any errors with `code --verbose`, but I can confirm that the tarball does **NOT** have this problem

**Comment by farzadmf** [comment]
I saw that version `1.40.1` was released, and I was hoping that the snap issue would be fixed, but the problem still exists

**Comment by joaomoreno** [comment]
@farzadmf Is this still a problem?

**Comment by farzadmf** [comment]
@joaomoreno Unfortunately, I gave up on using the snap package after this 😞, so I guess I can close this since I have no information to add
