### ISSUE TITLE
Pressing the key `TAB` can't insert '\t' in editor

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#84442]
Issue Type: <b>Bug</b>

When I press `Tab` in editor, it won't insert '\t', the focus will go somewhere else.

You know, that's very very frustrating: you can't insert '\t'!

This is weird thing. Even weird: the markdown file won't encounter this problem. But while editing some programming languages like Java or C++, this will happen.

Here's what happened:[twitter](https://twitter.com/i/status/1193545288440406017)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.66GB free)|
|Process Argv|C:\Users\Rxy\Desktop\线代.code-workspace|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|3.0.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-clock|Com|0.0.1
xml|Dot|2.5.0
gitlens|eam|10.1.2
todo-tree|Gru|0.0.162
beautify|Hoo|1.5.0
vscode-peacock|joh|3.2.0
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
cpptools|ms-|0.26.1
material-icon-theme|PKi|3.9.1
java|red|0.52.0
vscode-xml|red|0.9.1
LiveServer|rit|5.6.1
vscode-markdown-paste-image|tel|0.12.3
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
markdown-all-in-one|yzh|2.5.1

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@JoeyRxy For accessibility purposes we have a mode where Tab moves focus. This is toggleable with Ctrl+M and is rendered in the status bar:

![image](https://user-images.githubusercontent.com/5047891/68569093-8f3f9580-045d-11ea-99c5-ea0dc85c7b41.png)

You can:
1. Press Ctrl+M again to toggle the mode
2. Restart VS Code (which leaves the mode)
3. Remove the keybinding if you don't need it.

**Comment by JoeyRxy** [comment]
Oh thx a lot.

btw, I think this keybinding should be remove, anyone will use this?

**Comment by alexandrudima** [comment]
@JoeyRxy This default keybinding is very useful for users who want to or must use only the keyboard to operate VS Code. It is very easy for you to remove it on your machine via the keybindings editor (ctrl+k ctrl+s).
