### ISSUE TITLE
Click PROBLEMS view and receive error "Unable to open 'project folder': File is a directory"

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#84459]
For Java language server, it will report diagnostics for project level errors, and the URI will point to the project path (it's a folder). When clicking it, VS Code will throw error "**Unable to open 'project folder': File is a directory**".

For Example,
![image](https://user-images.githubusercontent.com/14052197/68567352-c6309e00-0493-11ea-9464-51e7316a8983.png)

Error:
![image](https://user-images.githubusercontent.com/14052197/68569298-ba93a600-0498-11ea-885e-f8131836023d.png)

This error will confuse the user. The VS Code client should not pop up error for folder level diagnostics.

**Comment by alexandrudima** [comment]
Please report directly against https://github.com/redhat-developer/vscode-java

**Comment by testforstephen** [comment]
@alexandrudima Reporting problems for project folder is a sensible case for Java language server, and the real problem is VS Code tries to use a file editor to open a folder uri because it's uri schema is file. How do you expect the vscode-java extension to fix the issue?

**Comment by alexandrudima** [comment]
@testforstephen Let me redirect you to @sandy081 who owns the Problems UI.

I believe the current thinking is that problems should always point to files such that end-users can click on the problem and type in an editor to fix the problem. I think this would be the first time a problem exists with a folder. Could you not create a diagnostic pointing to the project configuration file?

**Comment by testforstephen** [comment]
java project config file such as .classpath, they are auto generated by the jdt tool, we may not want to expose them to user directly. We're trying to hide these temp files by some way. So jumping to these files is not a good option for us.

**Comment by sandy081** [comment]
When there are problems shown in the problems UI it is expected that user can open that resource and fix it. Just showing the problem and not allowing user to interact with it Is not correct. I would recommend to point to the real file where user can open and fix it.

**Comment by testforstephen** [comment]
@sandy081 Must open a specific project file is a bit too restrictive for our case. I'm wondering is it possible to allow the extension to open a customized webview for the project root resource?

Currently i have a try to return a customized uri (e.g. jdtproject://projectName) for the project root diagnostics, and register a content provider to return html page, but the VS Code just opens the returned html as the raw plaintext.

Besides, i tried to return a command uri (e.g. command://java.showProjectStructure) for project root diagnostics, and try to trigger a command when the user clicks the diagnostics in the PROBLEMS view, but VS Code just throws exception saying "resource is not available".

**Comment by sandy081** [comment]
May be if there is a custom editor associated to that resource. Not sure how it is wired. 

@mjbvz Since @bpasero is on holiday, Do you know if it is possible opening a custom editor for a custom resoruce displayed in problems view?

**Comment by mjbvz** [comment]
Custom editors are only proposed api at the moment but the intent is that they’d replace the normal text editor without requiring a special uri

**Comment by testforstephen** [comment]
Thanks for the information.

@mjbvz i'm interested in the custom editors. Is there any documentation for it?

**Comment by testforstephen** [comment]
@mjbvz I have updated my use case in the custom editor thread https://github.com/microsoft/vscode/issues/77131#issuecomment-558452703, but i'd like to continue the discussion in this thread.

Maybe i didn't say clear about content provider in that thread.

I understand content provider could provide all kinds of contents, but the editor has the power to determine how to render those contents. In the past, i have experience in the vscode-arduino extension to use content provider to show a rich manager UI, where the content provider will return a html page, and then use **vscode.previewHtml** command to render them.

The question i got here is that even though i use content provider to return a html page for the special uri resource, the **PROBLEMS** diagnostics open logic will always use a file service to open the contents, that means they just show the html raw text directly. So i want to know whether to have some way to intercept the default open handler of **PROBLEMS** view, and use custom editor to open the special uri resource instead of file editor.
