### ISSUE TITLE
Terminal dosen't work 50% of the time after latest update

### ISSUE THREAD

**Issue by Akashdesarda** [microsoft/vscode#84452]
Issue Type: <b>Bug</b>

Terminal doesn't work 50% of the time after the latest update. I have to restart VS Code again & hope that it will work. Again the chances that it will work are random.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 2815)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
monokai-charcoal-high-contrast|74t|2.0.1
vscode-json|and|1.5.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.31.2
docs-yaml|doc|0.2.4
githistory|don|0.4.6
gitlens|eam|10.1.2
vsc-material-theme|Equ|30.0.0
Python-autopep8|him|1.0.2
vscode-auto-open-markdown-preview|hnw|0.0.4
path-autocomplete|ion|1.13.3
nbpreviewer|jit|1.2.2
vsc-python-indent|Kev|1.5.0
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.8.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
remote-containers|ms-|0.81.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
resourcemonitor|mut|1.0.6
autodocstring|njp|0.3.0
remote-vscode|raf|1.1.0
vscode-data-preview|Ran|1.48.0
vscode-yaml|red|0.5.3
code-spell-checker|str|1.7.20
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
json|Zai|1.0.2

(1 theme extensions excluded)

</details>

**Comment by cocoroise** [comment]
me too😥

**Comment by Tyriar** [comment]
> VS Code version: Code 1.39.2

You didn't report from the latest release?

Also this is likely https://github.com/microsoft/vscode/issues/84082 which will be fixed in 1.40.1

/duplicate
