### ISSUE TITLE
Integrated terminal: "editor.cursorBlinking": "hidden" not applied

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8445]
Testing #8222 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:07:32.441Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Change settings to "editor.cursorBlinking": "hidden"
2. -> Cursor in integrated terminal doesn't hide

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/8088

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/7923

**Comment by Tyriar** [comment]
The answer to this may be to just add another setting an not rely on the editor one. If #7923 gets implemented this will probably have to be done.

**Comment by Tyriar** [comment]
Superseded by #9089
