### ISSUE TITLE
 Support toml format in custom snippets' config

### ISSUE THREAD

**Issue by KoyamaSohei** [microsoft/vscode#84461]
related issue: 
https://github.com/microsoft/vscode/issues/15140
https://github.com/microsoft/vscode/issues/21465

Supporting [toml format](https://github.com/toml-lang/toml) can 
- reduce the effort required to create snippets 
- improve readability.

### jsonc(Now using)

```jsonc
{
  "hello": {
    "prefix": "hello",
    "body": [
      "int main() {",
      "  some();",
      "  greeting();",
      "}",
    ]
  }
}
```

or 
```jsonc
{
  "hello": {
    "prefix": "hello",
    "body": "int main() {\n some();\n  greeting();\n}"
  }
}
```

### toml 

```toml
[hello]
prefix = "hello"
body = """
int main() {
  some();
  greeting();
}"""
```

**Comment by jrieken** [comment]
We know the shortcoming of JSON but also the up and there are no plans to change this
