### ISSUE TITLE
[html] In HTML/XML, go to bracket would be more useful if it went to matching tag

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8446]
#8207
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

/cc @alexandrudima 

Currently in a HTML/XML file, go to bracket will literally jump to matching brackets. In HTML and XML, tags serve a similar purpose to brackets, you indent at them, they open and close, just like brackets. It would be intuitive imo if go to bracket went to the matching HTML tag instead of work on brackets (ie. the `Emmet: Go to Matching Pair` command).

**Comment by aeschli** [comment]
We now have the `Emmet: Go to Matching Pair` command built-in.
