### ISSUE TITLE
[Solved, and not a real issue] Snippet definition in php.json cannot show when typing, while other langs can!

### ISSUE THREAD

**Issue by pytkr** [microsoft/vscode#84462]
- **VSCode Version**: **1.40.0** (user setup)
- **OS Version**: Windows_NT x64 10.0.17134
- **Others**: 
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

Steps to Reproduce:

1. **Open Config file**: F1 > search `Snippets` > click `php.json`
2. **Edit Config and save**: Uncomment the example snippet and save it, namely, 
```json
{
		"Print to console": {
			"prefix": "log",
			"body": [
				"console.log('$1');",
				"$2"
			],
			"description": "Log output to console"
		}
}
```

3. **Use Case**: type `log` in test.php file (an empty file), and the prompt menu doesn't contain it, thus, unable to use it.

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**, after disabling all extensions and restart vscode still with the same problem.

Other languages, like css, htm, and js file are all ok, however, php failed, strangely.

**Comment by jrieken** [comment]
Does the snippet show when running F1 > Insert Snippet? Also can you share the file and the location in that file where you are trying this?

**Comment by pytkr** [comment]
> Does the snippet show when running F1 > Insert Snippet? Also can you share the file and the location in that file where you are trying this?

All extensions disabled then Irestart to make sure, and I try to use this snippet in files of 3 states, and type `log`, only normal option in prompt menu:
1. create new empty file and change to php format, with UTF-8, tried but failed
2. open an empty php file, with UTF-8, tried but failed
3. open an non-empty php file, with UTF-8, tried but failed

munu looks like this:
![Snipaste_2019-11-13_11-40-14](https://user-images.githubusercontent.com/45117726/68731362-bab3b300-060a-11ea-8621-46718735c3d6.png)

**Comment by jrieken** [comment]
Please run "F1 > Inspect TM Scopes", select the position at which you want this snippet to be inserted, and share the information the hover shows.

**Comment by pytkr** [comment]
> Please run "F1 > Inspect TM Scopes", select the position at which you want this snippet to be inserted, and share the information the hover shows.

Solved! 
It works if I type `log` in position `<HERE>` following code

```
<link rel="stylesheet" href="<?php bloginfo('stylesheet_url') <HERE>?>" type="text/css" media="screen" />
```

I just **misunderstanded** the logic of snippet, I should type php snippet **in** php tags, not **in** html tags...

So, the `solution` is to configure htm.json for snippet of `<?php ?>`, and configure php.json for snippet of `bloginfo()` or s.th. of php function.

Thanks so much
