### ISSUE TITLE
Vscode Cmake

### ISSUE THREAD

**Issue by Aprilhui** [microsoft/vscode#84468]
already get the right path about Cmake but it still not working

**Comment by Aprilhui** [comment]
not covering

**Comment by qbisicwate** [comment]
cmake generator not specified ,error: generators unavailalbe.
However i can configure my project using the shell cmd : cmake -G "Unix Makefiles" .. in cmd.exe

**Comment by Aprilhui** [comment]
error happened while trying to do like that
error info：
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "C:/Users/August" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by Aprilhui** [comment]
> cmake generator not specified ,error: generators unavailalbe.
> However i can configure my project using the shell cmd : cmake -G "Unix Makefiles" .. in cmd.exe

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "C:/Users/August" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
