### ISSUE TITLE
When renaming a compressed folder then the UI stays in a disabled state

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#84467]
- open the try java repository in a container https://github.com/microsoft/vscode-remote-try-java
- select a compressed folder and try to rename it
- the UI is 'stuck' and stays in the disabled state.

![image](https://user-images.githubusercontent.com/172399/68576750-f31e8a00-046e-11ea-92ff-2d14e9fef371.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/84658
