### ISSUE TITLE
Ctrl+shift+E not working on Kubuntu 19.10

### ISSUE THREAD

**Issue by lcswillems** [microsoft/vscode#84464]
- VSCode Version: 1.40
- OS Version: Kubuntu 19.10 with i3wm

Steps to Reproduce:

1. Launch VSCode
2. Press `ctrl+shift+e` in the code view. The file pane should be display but `e` is written in the view.

For VSCode, "Ctrl+shift+e" is "Ctrl+shift+unknown" whereas ctrl+shift+e is well captured by i3wm.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lcswillems** [comment]
I also have the bug with VSCode 1.39

**Comment by lcswillems** [comment]
After searching more, it seems it is the same issue as this one: https://github.com/Microsoft/vscode/issues/72947

For VSCode, "Ctrl+shift+e" is "Ctrl+shift+unknown" whereas ctrl+shift+e is well captured by i3wm.

**Comment by alexandrudima** [comment]
Indeed, https://github.com/microsoft/vscode/issues/48480#issuecomment-414464079 documents what needs to be done. The keybinding is taken by the OS.

**Comment by evenfrost** [comment]
The linked comment didn't work for me, emoji shortcut was already disabled.

What helped though, is this solution: https://superuser.com/a/1421979. I'm currently using Ubuntu 19.10 with GNOME.

In short, go to **Language Support** > **Language** tab > Select **XIM** in **Keyboard input method system** dropdown, then **reboot**.

After this, both <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> keybindings work as expected.
