### ISSUE TITLE
VS Online proxy "login page" breaks requests to hosted APIs

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#84469]
~~I don't know if this is the correct place to raise this (it feels more like VS Online infrastructure than VS Code code), but it appears that when exposing a port through VS Online (using `asExternalUri`), the `Access-Control-Allow-` headers don't seem to come through.~~

**Comment by DanTup** [comment]
Actually, this is because of this weird login page that's served up:

```
Visual Studio Online
You need to sign in first, redirecting...

Click here if your browser does not automatically redirect.
```

The application connecting to this endpoint does not expect to get a HTML redirect page like this. Is there a way to suppress it? This is a URL that was forwarded using `asExternalUrl` and not `openExternal`.

**Comment by alexandrudima** [comment]
@DanTup I'm not 100% sure I understand what the issue is. Can you please elaborate a bit?

**Comment by DanTup** [comment]
@alexandrudima when you use `asExternalUri` so that VS Online sets up a tunnel into the container and then load it in your browser, you'll see an intermediate page that says "You need to sign in first" and then automatically reloads/redirects and the page works.

However, if the thing you're exposing is an API/service then having VS Code output this intermediate HTML page on the first request to it is an issue, because the client script expects an API response, not an HTML page (which is also missing the CORS headers that the real service would output, which causes the browser error).

Dose this make sense?

**Comment by DanTup** [comment]
I found that MicrosoftDocs/vsonline is the issue tracker for Online issue, so I've moved this to https://github.com/MicrosoftDocs/vsonline/issues/164.
