### ISSUE TITLE
TS doesn't exclude constructor declaration when being asked for

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#84478]
* invoke find references on a ctor and make sure `{ includeDeclaration: false }` is passed
* :bug: ctor is part of the results

**Comment by mjbvz** [comment]
Example code:

```ts
class Foo {
    constructor() {}
}

new Foo()
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35043 to track root cause upstream
