### ISSUE TITLE
VS Online adds extra output before/after web requests

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#84475]
I can't figure out what's happening here, but if you run a simple Dart web server in VS Online, the output is preceded by a `D` and ends with `0`. These do not show up if you run locally, now do they show up if the same Dart script sends a request to itself and prints the response to the console:

![Screenshot 2019-11-11 at 10 38 08 am](https://user-images.githubusercontent.com/1078012/68581173-c323b680-046f-11ea-83b3-dfed57252e2a.png)

Here is the Dart code for the repro:

```dart
import 'dart:convert';
import 'dart:io';

const port = 4030;

Future main() async {
  var server = await HttpServer.bind(InternetAddress.loopbackIPv4, port);
  print('Listening on 127.0.0.1:${server.port} !!');

  Future.delayed(const Duration(seconds: 5)).then((_) => sendRequest());

  await for (HttpRequest request in server) {
    request.response.write('Hello, world!');
    await request.response.close();
  }
}

void sendRequest() {
  final client = new HttpClient();
  client.getUrl(Uri.parse('http://127.0.0.1:$port/'))
    .then((request) => request.close())
    .then((HttpClientResponse response) => response.transform(Utf8Decoder()).listen(print));
}
```

And here is the launch.json:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Dart",
			"request": "launch",
			"type": "dart",
			"program": "bin/server_test.dart",
			"serverReadyAction": {
				"pattern": "Listening on 127.0.0.1:([0-9]+)",
				"uriFormat": "http://127.0.0.1:%s",
				"action": "openExternally"
			},
		}
	]
}
```

Interestingly I can't repro with a NodeJS script that does roughly the same.

**Comment by mjbvz** [comment]
This bug seems VSOnline specific to me. Can you please file an issue against this repo so that someone can look into it: https://github.com/MicrosoftDocs/vsonline/issues/new

(unfortunately I can't move issues between organizations or else I'd move it over myself)

**Comment by DanTup** [comment]
Thanks - didn't realise there was a repo for it. I've opened https://github.com/MicrosoftDocs/vsonline/issues/163. Thanks!
