### ISSUE TITLE
Code result different between "vscode" and "intellij idea"

### ISSUE THREAD

**Issue by 15050050972** [microsoft/vscode#84474]
here is the code, about 3DES encryption
```
import java.security.Key;
import java.util.Base64;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;

public class Main {

    static String key = "693207DB8148FBC9D8410179";
    static String iv = "20190225";
    static String encoding = "gb2312";
    static String data = "{\"parkCode\":\"1\",\"plateNo\":\"京A11113\"}";

    
    public static String encrypt(String data) throws Exception {
        DESedeKeySpec keySpec = new DESedeKeySpec(key.getBytes());
        SecretKeyFactory keyFactory = SecretKeyFactory.getInstance("desede");
        Key deskey = keyFactory.generateSecret(keySpec);

        Cipher cipher = Cipher.getInstance("desede/CBC/PKCS5Padding");
        IvParameterSpec ips = new IvParameterSpec(iv.getBytes());
        cipher.init(Cipher.ENCRYPT_MODE, deskey, ips);
        byte[] encryptData = cipher.doFinal(data.getBytes(encoding));
        return Base64.getEncoder().encodeToString(encryptData);
    }

    public static void main(String[] args) throws Exception {
        System.out.println(encrypt(data));
    }

}
```

in `vscode`, the result is 

![image](https://user-images.githubusercontent.com/23148429/68580721-e7a08280-04b1-11ea-9461-2eed6d79f07e.png)
```
0edFaLw+X+9J2LHbzKQa0zo3RGmHII0JhagfRQLJhEVodBeA8XO6rw==
```

in `intellij idea`, the result is :
![image](https://user-images.githubusercontent.com/23148429/68580773-06067e00-04b2-11ea-8609-6fd193030db8.png)

```
0edFaLw+X+9J2LHbzKQa0zo3RGmHII0JXoSLu19d+/pvYydg1qZV5A==
```

I checked the class file, the Main.class in `vscode` size is 2KB.

The Main.class size in 'intellij idea` is 3KB.

Here is the file:
[two classes.zip](https://github.com/microsoft/vscode/files/3830901/two.classes.zip)

Please check the problem, thank you for your time.

**Comment by IllusionMH** [comment]
Not sure how exactly this is VS Code issue - it is an editor that doesn't execute Java by itself.
So most likely this is problem with an extension that you are using to run Java code and issue should be created there, not in this repo.

**Comment by alexandrudima** [comment]
Please create an issue directly against the extension at https://github.com/redhat-developer/vscode-java/issues
