### ISSUE TITLE
Visual glitches in the last release 1.40.0 on Linux Mint 

### ISSUE THREAD

**Issue by moooises** [microsoft/vscode#84476]
- VSCode Version: 1.40.0
- OS Version: Linux Mint 19.2 Tina (Linux x64 4.15.0-66-generic)

Steps to Reproduce:

1. Just open the code editor and where the cursor is many visual glitches appear. Usually black rectangles for a few seconds. And the same happens when you move with the key arrow.
It happens when the new release appear, until then It was running ok. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by asim-rehman** [comment]
/needs-more-info

I cannot reproduce the issue you are experiencing, can you provide an image or video of the issue you are having. Also maybe list your system specification (Graphics Card etc)

Also does this issue occur with a particular type of file Java/C# or just in general? 

**System Info**
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic (Linux Mint 19.2)
```

**Comment by moooises** [comment]
The laptop where I have the problem has a Intel i7-8750H, 8 GB Ram and the graphic card is GeForce GTX 1050 Ti Mobile 4GB

This is the visual glitch I refer
https://drive.google.com/file/d/1HteUtegTxNYPja7J94QvpeTGVxMQY80p/view?usp=sharing

It might be graphic driver problem with my laptop, but it only happens in this version of VScode, the previous version from the Snap Store of Ubuntu, which had the old version, worked fine until It was update and in another code editor, Atom, I don't have this problem

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
