### ISSUE TITLE
in Java programming opens twice times the same source file causing confusion

### ISSUE THREAD

**Issue by moisesbites** [microsoft/vscode#84489]
When I am programing in Java, on clicked in a error/warning in Problems, the Code opens some source files twice times, and it is confusing. This confuses, because the same file is opened without warning, with different versions. This is very bad. 

Please, this need to be fixed.

**Comment by alexandrudima** [comment]
Please report directly against https://github.com/redhat-developer/vscode-java/issues

This is most likely caused by the Java extension which is adding those errors/warnings in the Problems view, but possibly using different URIs to refer to the same files...
