### ISSUE TITLE
Explorer: Can't select all and delete

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84484]
I can repro this even in last month's stable:

1. Focus explorer's root
2. `Ctrl A` and `Delete`

Nothing happens.

If you use the mouse and `Shift` key to select all items and then `Delete`, that works.

**Comment by isidorn** [comment]
Good catch. Thanks
The issue was that the focus was undefined. I changed the context logic, when the focus is undefined it is fine to respect the selection. Hopefully that does not hit me back.
