### ISSUE TITLE
Debug Console: Use openExternal() to open URIs in the click handler

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#84480]
When running with a Remote extension the Terminal goes through the forwarding logic openExternal() uses when a URI is Ctrl/Cmd+Clicked. The Debug Console should do the same.

Currently the local browser opens with the port not being forwarded and the browser shows a failure to connect.

**Comment by isidorn** [comment]
Currently I am using the openerService to open URI's [here](https://github.com/Microsoft/vscode/blob/6245d67152fd77ac7560f62a58a58cdeaf4a9047/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L99)
The opener service seem to use the openExternal [here](https://github.com/Microsoft/vscode/blob/6245d67152fd77ac7560f62a58a58cdeaf4a9047/src/vs/editor/browser/services/openerService.ts#L164)

So I do not really understand what I should do differenetly?

**Comment by chrmarti** [comment]
You might need to tell it that the URI comes from 'remote'. @mjbvz for advice.

**Comment by isidorn** [comment]
Shouldn't that be infered from looking at the URI?
The debug console is not aware of remote or any meaning of URIs, I can not interpreet the meaning of URIs in the debug console.

**Comment by mjbvz** [comment]
Yes, the opener service will not open a tunnel by default. The  `allowTunneling` option enables this: https://github.com/microsoft/vscode/blob/cec8079c59d66374e1b20d97a4ad7a1743d74008/src/vs/platform/opener/common/opener.ts#L27

**Comment by isidorn** [comment]
@mattbierner but that option is not exposed in the `open` call in the `openerService`.
As far as I understand that option is set while registering an external uri resolver. So it does not feel like any change needs to be done in the debug console.
If there is something needed to be done, please assign the issue back to me.
Thanks

**Comment by mjbvz** [comment]
@isidorn The caller of the `OpenerService.open` decides if tunneling should be enabled or not. We do not enable tunneling by default (expect possibly in the VSO case).

Take a look at how this is implemented by our integrated terminal:

https://github.com/microsoft/vscode/blob/481485b354b6a32eac31101daaf8cd1cc81787da/src/vs/workbench/contrib/terminal/browser/terminalLinkHandler.ts#L269

**Comment by isidorn** [comment]
Thanks for the pointer. I was missing something, since on friday when I checked this I did not see the `allowTunneling` flag.
Adding bug label so we get this verified.
