### ISSUE TITLE
Emmet wrap with abbreviation dialog should go away when it loses focus

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8449]
#8207

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to reproduce:

1. Trigger Emmet: Wrap with Abbreviation command
2. Focus editor

![image](https://cloud.githubusercontent.com/assets/2193314/16432929/7f42551e-3d3c-11e6-8b1d-b49a7a10dc0a.png)

This gets particularly bad when you try to use the command palette now:

![image](https://cloud.githubusercontent.com/assets/2193314/16432972/af2d9b76-3d3c-11e6-9da5-5105a7e64b93.png)

**Comment by Tyriar** [comment]
The same applied top the decode data image uri command.

**Comment by mrmlnc** [comment]
As I understand it, the inputBox (`quickOpenService.input`) has no automatic closing when you change focus? I found this opportunity only for Pick.

**Comment by egamma** [comment]
I've also checked other uses of `IQuickOpenService.input`, e.g. `git commit` and they expose the same behaviour, e.g., the quick box remains open also when it loses focus.

Assigning to @bpasero for further investigation.

**Comment by mrmlnc** [comment]
@bpasero, it seems to me that this is «hard code»:

```ts
this.doPick(TPromise.as([{ label: currentPick }]), {
	ignoreFocusLost: true,	// <------------------------- this
	autoFocus: { autoFocusFirstEntry: true },
```

I created a branch in my fork. Maybe this will help you. Link to [commit](https://github.com/mrmlnc/vscode/commit/857a5ed6f7c977b8b512912c020dde7b658f71f4). This option is not described in the documentation.

**Comment by bpasero** [comment]
Moving to @jrieken who added this in https://github.com/Microsoft/vscode/commit/7a626a94ea1b0b9c6b5f43f1b0038cccb9da0fef
