### ISSUE TITLE
Marketplace broken when proxy blocks the experiment service endpoint

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84496]
I debugged this issue with someone at Ignite. When he searched the marketplace in vscode, he got an error, and I found that this was from failing to download the experiments. But when we disabled experiments, searching worked fine.

He didn't have a proxy configured in VS Code, and he said that he wasn't using one, but he actually was using some company proxy or VPN. We found that some domains like `microsoft.com` or `visualstudio.com` were whitelisted and could be accessed, but the experiments domain `msecnd.net` was not. Also when VS Code accessed it, it got a "successful" response with a non-JSON response (the login page for the VPN). Normally if the request fails we handle that gracefully. But here, all requests to the marketplace first await the experiment service, and that failed, so no searches went through.

So I guess two issues

- Handle an invalid response for the experiments data - I technically own this and will fix it
- Should we provide a list of domains that we access for this sort of scenario? Or try to use recognizable domains like microsoft and visualstudio? @sandy081 do you know anything about this?

**Comment by sandy081** [comment]
>  But when we disabled experiments, searching worked fine.

I am wondering how experiment services is related to marketplace search. Marketplace search should work irrespective of that. Are you able to repro this?

> Should we provide a list of domains that we access for this sort of scenario? Or try to use recognizable domains like microsoft and visualstudio? @sandy081 do you know anything about this?

These services are listed in our `product.json`. We can go through them and whitelist.

**Comment by roblourens** [comment]
Experiments can affect marketplace search results, so we have to load them first.

> These services are listed in our product.json. We can go through them and whitelist.

This isn't exposed to users, I wouldn't expect them to look through it for things to whitelist. Also I think the whitelisting is something the IT department did, probably not for VS Code in particular.

**Comment by sandy081** [comment]
> Experiments can affect marketplace search results, so we have to load them first.

Still I do not think marketplace request shall fail when loading experiments fails. In such a case why don't marketplace requests can be made as if experiments are disabled?

**Comment by sandy081** [comment]
> This isn't exposed to users, I wouldn't expect them to look through it for things to whitelist. Also I think the whitelisting is something the IT department did, probably not for VS Code in particular.

Sorry then I have not understood your initial question regarding this.

**Comment by roblourens** [comment]
> Still I do not think marketplace request shall fail when loading experiments fails. In such a case why don't marketplace requests can be made as if experiments are disabled?

It shouldn't, but it does, I will fix that. And if they are disabled, then we skip that step entirely so it doesn't matter.

I guess I'm wondering whether we've thought about this before and how someone would know that VS Code needs to access the `msecnd.net` domain so they can whitelist it.
