### ISSUE TITLE
Support utf-8 encoding guessing 

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode#84495]
utf-8(`['ascii', 'utf-8', 'utf-16', 'utf-32']`) encoding guessing is disabled by this line. [ Ignore encodings that cannot guess correctly](https://github.com/microsoft/vscode/blob/b8bb1770a5897e1dcbc9608d2280a3e765777ae5/src/vs/base/node/encoding.ts#L217.)
But this [link](https://chardet.readthedocs.io/en/latest/supported-encodings.html) didn't mention it.
And in my test,the follow text will be guessing as utf-8 correctly(result='utf-8'). 
![image](https://user-images.githubusercontent.com/7285119/68597276-a622ce00-04d7-11ea-95e9-a77d30e501ea.png)

jschardet result:

![image](https://user-images.githubusercontent.com/7285119/68597171-75db2f80-04d7-11ea-8d46-aa0e4272e200.png)

In the other hand,with the follow setting, it will be detect as `GBK`

![image](https://user-images.githubusercontent.com/7285119/68598309-7f659700-04d9-11ea-92b7-b1c0658015eb.png)

![image](https://user-images.githubusercontent.com/7285119/68596491-45df5c80-04d6-11ea-998b-b83d004f11d7.png)

**Comment by byyxx128** [comment]
Not as simple as you see...
See these issues https://github.com/microsoft/vscode/labels/file-guess-encoding

**Comment by byyxx128** [comment]
Not as simple as you see...
See these issues:
https://github.com/microsoft/vscode/labels/file-guess-encoding
https://github.com/aadsm/jschardet/issues/48
https://github.com/aadsm/jschardet/issues/49

**Comment by sunbohong** [comment]
> Not as simple as you see...
> See these issues:
> https://github.com/microsoft/vscode/labels/file-guess-encoding
> [aadsm/jschardet#48](https://github.com/aadsm/jschardet/issues/48)
> [aadsm/jschardet#49](https://github.com/aadsm/jschardet/issues/49)

These issues will be solve by https://github.com/microsoft/vscode/issues/84503

**Comment by sunbohong** [comment]
> Not as simple as you see...
> See these issues:
> https://github.com/microsoft/vscode/labels/file-guess-encoding
> [aadsm/jschardet#48](https://github.com/aadsm/jschardet/issues/48)
> [aadsm/jschardet#49](https://github.com/aadsm/jschardet/issues/49)

In particular, https://github.com/aadsm/jschardet/issues/48  will be treat as `utf-8` 

![image](https://user-images.githubusercontent.com/7285119/68646356-e58fff80-0555-11ea-9907-dd8f154cd60d.png)

**Comment by bpasero** [comment]
I like this change, specifically because this gives full control to `jschardet` for guessing encoding. If there are issues with this approach then I think we should start to tweak the minimum threshold for confidence.

**Comment by bpasero** [comment]
I like this change because it makes `jschardet` more deterministic by giving it full control over the detection. I still think more work is needed to increase the confidence of the detection, but that can continue in other issues.

**Comment by bpasero** [comment]
@sunbohong I noticed a bad regression though that made me push https://github.com/microsoft/vscode/commit/ddfca307b1bd29da040e82c8389638fc508248aa to ignore the guessed encoding "ascii" for a simple reason:
* user opens a text file with just ascii characters
* we guess the encoding to be "ascii"
* user types special characters (like german umlaut)
* user saves and closes the file
* user reopens the file

=> the file is still guessed as "ascii" because it was not saved with a proper encoding

**Comment by bpasero** [comment]
**Verification:**
* configure `"files.autoGuessEncoding": true`
* configure `"files.encoding": "windows1252"`
* save a file with special characters contents (e.g. `私は和食が好きです。`) as UTF-8
* close all files
* open it in VSCode

=> the encoding should be UTF-8

**Comment by connor4312** [comment]
Running these steps, I get a bunch of question marks when I reopen the file, and still with windows1252 encoding, on OS X.

![image](https://user-images.githubusercontent.com/2230985/70097661-b9a8ec80-15de-11ea-944e-87b34b284250.png)

**Comment by bpasero** [comment]
Given scary issues such as https://github.com/microsoft/vscode/issues/85821 I am putting UTF-16 and 32 back to the list of ignored encodings for guessing. Still, UTF-8 can be guessed.

**Comment by sunbohong** [comment]
@bpasero  From this issue #85821, we really need to replace jschardet with a new library
