### ISSUE TITLE
Find references: expanding an element for the first time selects it and all children

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#84491]
1. Find all references
2. Click on a file
3. It expands, and it gets selected with all of its children

This is different behavior from before and I find it a bit strange since no other tree behaves like this.
Is there some motivation for this change? If yes, then I would expect that every time I expand I folder all the children would be selected.  Though I would prefer that we go for the old behavior.

![references](https://user-images.githubusercontent.com/1926584/68595252-5fae7e80-0499-11ea-8f10-d78eeca3f048.gif)

**Comment by jrieken** [comment]
Yeah, I pushed a fix for that today.
