### ISSUE TITLE
Command prompt width & autowrap setting suggestion

### ISSUE THREAD

**Issue by AshCoolman** [microsoft/vscode#845]
(On OSX) my errors often get cut off from the "Errors and warnings" menu that appears when I press ⌘ + ALT + SHIFT.

It would be nice to have settings to:
- increase prompt width
- make prompt items wrap

http://stackoverflow.com/questions/33757338/increase-vscodes-error-and-warnings-menu-width-or-make-it-wrap

**Comment by alexandrudima** [comment]
:+1: I am also not happy with our error list

**Comment by egamma** [comment]
Added error list improvements to our roadmap

**Comment by jskrepnek** [comment]
:+1: and if someone has discovered a work around, please share.

**Comment by sandy081** [comment]
They are shown now in problems view as a separate panel.
