### ISSUE TITLE
vscode-remote/wsl: Cannot access .git from Windows

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#84509]
# Setup

- VSCode Version: 1.40.0
- OS Version: Win 1903
## Installed components
- WSL (Ubuntu 18.04.3 LTS)
- Git for Windows
- VSCode extension: WSL - Remote

# Steps to reproduce
1. Using Git for Windows, clone some repo into some folder
2. Use WSL to navigate to the folder
3. Still in WSL, run `code .`
4. Change some files
5. Using Git for Windows, try to commit/add a file/...
 Example command:  `
 git add *
 `

# Expected behavior
Can use git as usual.

# Actual behavior
git displays an error: "fatal: Unable to write new index file"

Just to clarify: If I quit VS Code and run the command again, this is working fine ...

**Comment by aeschli** [comment]
This is caused as there's now the Linux Git running in the WSL window, conflicting with Git on Windows.

**Comment by LinqLover** [comment]
I did not perform any action that indicates I would like to run Linux git. Why does git in VS Code permanently lock all files? This is not happening if I run VS Code natively on Windows.

**Comment by joaomoreno** [comment]
I suggest to keep things separate, since both gits don't seem compatible. If you clone on Windows, please only use Git for Windows. Likewise for WSL. This seems more like a bug for Windows or Git.
