### ISSUE TITLE
Maximize/Restore button bug

### ISSUE THREAD

**Issue by kerim878** [microsoft/vscode#84508]
Issue Type: <b>Bug</b>

Hi, devs! The resize button isn't functioning correctly after the 1.40 update. It's only maximizing, not restoring to the smaller size.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.96GB free)|
|Process Argv|C:\Users\Kerim Ellezov\Documents\GitHub\aspnet-core-jwt-authentication-api|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
beautify|Hoo|1.5.0
mssql|ms-|1.7.0
csharp|ms-|1.21.6
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.1123
debugger-for-chrome|msj|4.12.1
vscode-versionlens|pfl|0.24.0
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
stylelint|shi|0.51.0
sass-indented|syl|1.6.8
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0

</details>

**Comment by af4jm** [comment]
Seeing the same thing here, also running 1.40 on Win10.

**Comment by tukno** [comment]
I have a similar issue. The maximize button does not shows in the window at the top right corner after the last update (only the minimize and close button shows).

SYSTEM INFO
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic


![image](https://user-images.githubusercontent.com/14236708/68616887-5a066800-049c-11ea-83df-837b4ea63833.png)
