### ISSUE TITLE
CTL-H Window - Enter hotkey is showing twice

### ISSUE THREAD

**Issue by MichaelRybicki** [microsoft/vscode#84500]
In a batch file, I press CTL-H for the Find and Replace window. The mouse over shows that Enter will find the next occurence and it also shows that Enter will Replace the next one. When I press Enter it just goes to the next one and I have to click on the Replace button for it to actually replace that occurence.

**Comment by Kai-Richardson** [comment]
The UI could be more clear, but the Enter-pressing functionality does work. To have it replace the next occurrence, you must select the `Replace` input field and then press Enter.

[Video example here](https://gfycat.com/homelygloomybobcat)

**Comment by jzyrobert** [comment]
Would it make sense to only show the keybinds for the appropriate buttons if you are focused on that input?
Eg

- Focus on find input, only the up/down arrows have the keybinding on hover
- Focus on replace input, only the replace buttons have their keybinding on hover

**Comment by MichaelRybicki** [comment]
I think it would make more sense to use Enter on the currently focused one but still allow CTL-Enter to work on the other one. That way there's no change in functionality for people that are used to it working like this but you get the added functionality - allowing users to do a Replace Next without having to change their cursor focus.
