### ISSUE TITLE
Canceling wrap with abbreviation adds a tab to the active editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8450]
#8207

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to reproduce:

1. Trigger Emmet: Wrap with Abbreviation command
2. Press <kbd>esc</kbd>, notice a tab was added to the file

Before:

![image](https://cloud.githubusercontent.com/assets/2193314/16433019/ea18cdaa-3d3c-11e6-84c2-807d868bc713.png)

After:

![image](https://cloud.githubusercontent.com/assets/2193314/16433043/0b2e9dd0-3d3d-11e6-99fb-bcd8d36fc41d.png)

**Comment by mrmlnc** [comment]
The same applied the top update Tag command.
