### ISSUE TITLE
Add vscode.workspace.fs.mkdirp().

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84516]
(see #84175)

For the Python extension, we had been using fs-extra's `mkdirp()`, though we could have used node's `mkdir()` with the `recursive: true` option.  T he new filesystem API provides `createDirectory()`, but that fails if the parent directory is missing.  So we wrote a wrapper around that.  However, it isn't an obvious solution, so it would be nice if the extension provided the equivalent of `mkdirp()`.

@jrieken

**Comment by jrieken** [comment]
`fs.createDirectory` does this, see https://github.com/microsoft/vscode/blob/b272a9e0013e141de30fafb5108fa56d2402caaa/src/vs/vscode.d.ts#L5991. I will update the docs

**Comment by ericsnowcurrently** [comment]
Thanks, @jrieken!
