### ISSUE TITLE
ActivityBar activeBorder doesn't show if you set a color for activityBar.border and sidebar is on the right

### ISSUE THREAD

**Issue by Dean-NC** [microsoft/vscode#84511]
- VSCode Version: 1.40
- OS Version: Windows 10 18362 (x64)

Steps to Reproduce:

1. Provide a border color to the activity bar (activityBar.border), OR use a theme that does (like Cobalt2)
2. Set sidebar to right-side
3. Try resizing the main window using the right-side of the window. The new activeBorder usually won't show, but sometimes does, based on resizing of the window. When it shows, it's usually a thinner line than normal.

In my example, I'm using the Cobalt2 theme, which sets a color for activityBar.border.

![Untitled3](https://user-images.githubusercontent.com/12361341/68611046-3553c580-0487-11ea-8297-a1b2f7a79385.png)

Sidebar on the left
![Untitled3b](https://user-images.githubusercontent.com/12361341/68611603-84e6c100-0488-11ea-953f-36f3c3357e32.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Fixed in latest insiders

**Comment by Dean-NC** [comment]
@isidorn Thanks. It wasn't a big deal, but I wanted you to know.
