### ISSUE TITLE
Add vscode.workspace.fs.chmod().

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84513]
(see #84175)

For the Python extension, we need the ability to change file permissions.  For example: https://github.com/microsoft/vscode-python/blob/master/src/client/activation/languageServer/downloader.ts#L165.  Currently we are using node's `fs.chmod()`.

@jrieken

**Comment by ericsnowcurrently** [comment]
According to https://github.com/microsoft/vscode/issues/84175#issuecomment-551445383, this is a dupe of #73122.  However, that issue is about seeing if a file is readonly or not.  This one is about *changing* the permissions on the filesystem (including the "executable" bit).  A more closely related issue is #48659.

**Comment by jrieken** [comment]
>  this is a dupe of #73122. However, that issue is about seeing if a file is readonly or not. This one is about changing the permissions on the filesystem (including the "executable" bit). A more closely related issue is #48659.

Once we start on this, we won't do something half-basked
