### ISSUE TITLE
Debug mode 

### ISSUE THREAD

**Issue by Alcasczar** [microsoft/vscode#84512]
Issue Type: <b>Bug</b>

Press F5 to enable debugging or click the option on the Debug menu to enable it.
Run through a few break points, press F5 to coninue.
(get side tracked,  deal with users,  boss ,  tickets)
Forget you had it on,   and then enable debugging again from the menu it tends to freeze and then eventually it causes the terminal to die and then you have to restart the terminal.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edit-csv|jan|0.2.3
powershell|ms-|2019.11.0
sqltools|mtx|0.21.2

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with vscode insiders 
If yes can you provide a repository which we can simply clone and reproduce this problem

https://code.visualstudio.com/insiders/
