### ISSUE TITLE
Colour profile change between 1.39.2 and 1.41-insider

### ISSUE THREAD

**Issue by dhowden** [microsoft/vscode#84521]
Version: 1.41.0-insider
Commit: 213bdddb72ff7a6c8eed071420de8ddac4293cb1
Date: 2019-11-11T05:36:13.475Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

OS Version: MacOS Mojave (Retina).

Steps to Reproduce:

1. Launch 1.39.2 and take a screenshot.
2. Launch 1.41-insider and take a screenshot.

Does this issue occur when all extensions are disabled?: Yes

This is not related to the #84154, but this is in response to https://github.com/microsoft/vscode/issues/84154#issuecomment-552313003 which asks for new issues which highlight regressions from the Electron 6 update (other than that fixed due to #84154).

1.39.2

<img width="1401" alt="Screen Shot 2019-11-11 at 8 38 49 am" src="https://user-images.githubusercontent.com/2822/68615370-07b65d00-0517-11ea-965f-a46765d85a5d.png">

 1.41.0-insider

<img width="1400" alt="Screen Shot 2019-11-11 at 8 41 39 am" src="https://user-images.githubusercontent.com/2822/68615387-143ab580-0517-11ea-9853-95339b879e36.png">

@bpasero @deepak1556

**Comment by rmtracey** [comment]
Same here. Font colors are washed out starting with 1.40.0, and whatever fixes were applied for https://github.com/microsoft/vscode/issues/84154 (assuming they're in the current Insiders build) have not fixed the issue.

Screenshot:
![colors](https://user-images.githubusercontent.com/3460875/68632471-a95c9080-04bc-11ea-96d1-e621faa1adda.png)

Left is 1.39.2, center is 1.40.0, right is 1.41.0-insider.

**Comment by bpasero** [comment]
I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net

Does the issue reproduce in that setup in the browser?

**Comment by rmtracey** [comment]
I'm not able to run locally - there seems to be some issue with the manifest. Didn't see any errors during package installation or during build. I just see a white page:
![local](https://user-images.githubusercontent.com/3460875/68669931-b9ef2400-0519-11ea-9588-1097f841de00.png)

Tried the playground as well, and it has the same issue. Left side is 1.39.2:
![playground](https://user-images.githubusercontent.com/3460875/68669995-d25f3e80-0519-11ea-90fb-a53fd45e88d5.png)

**Comment by rmtracey** [comment]
Got the local version working...my ad blocker was blocking one of the scripts from loading. 🙄

Color issue is present there as well:
![localworking](https://user-images.githubusercontent.com/3460875/68725818-8fd74980-058d-11ea-98f5-55feb53dcd64.png)

**Comment by bpasero** [comment]
@dhowden @rmtracey how does it look like with todays insider build? Make sure to update if you did not yet: https://code.visualstudio.com/insiders/

Version must be `b6a486e34fe3715f6edec0cdb11138b1672d33bd` (check from about dialog).

**Comment by rmtracey** [comment]
Looks much better! 👍 However, the version of Insiders I downloaded isn't the same version you specified - I'm running `eccf417b72fc0a632ec2cbd7855a681cdb8c81fa`. Seems like that commit came after the one you specified, so I'm guessing that's fine?

Screenshot (1.39.2 on the left, Insiders on the right):
![better](https://user-images.githubusercontent.com/3460875/68857136-2bf97180-06b0-11ea-826d-60a31c47b2aa.png)

**Comment by bpasero** [comment]
Yeah we got a new insiders build meanwhile, great to hear. This change should also be in stable now (1.40.1).

**Comment by dhowden** [comment]
@bpasero Results (posting for completeness!).  MacOS Mojave (Retina)

1.39.2

<img width="1401" alt="Screen Shot 2019-11-15 at 7 40 46 am" src="https://user-images.githubusercontent.com/2822/68894625-c2df3000-077b-11ea-9840-49e6c7db64a2.png">

1.41.0-insider(eccf417b72fc0a632ec2cbd7855a681cdb8c81fa)

<img width="1402" alt="Screen Shot 2019-11-15 at 7 41 51 am" src="https://user-images.githubusercontent.com/2822/68894646-cc689800-077b-11ea-8b1d-41850003de7d.png">

Much improved!  Thanks.
