### ISSUE TITLE
The line highlight that appears where the cursor is located has unpredictable behavior when multiple cursors are created

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#84523]
When multiple cursors are created (ie with <kbd>alt</kbd>+click or using the middle mouse button), the background highlight that appears behind the cursor sometimes does not appear behind the first couple of lines. 

This is best described with examples. Unfortunately I can't get the cursor to show up in screenshots so you'll have to trust that these lines have cursors or try it yourself.

Test file:
```text
1
2
3

4
5
6

7
8
9

10
11
12
```

Here I used the middle mouse button starting at the 0,0 position and dragging to the bottom of the document. I would expect all lines to be highlighted.
![image](https://user-images.githubusercontent.com/2294248/68615856-dc3d5f00-0491-11ea-857a-394dfd223181.png)

Here I used <kbd>alt</kbd>+click to place cursors at the beginning of the 2nd, 3rd, and 4th blocks. I would expect 4, 7, and 10 to be highlighted.
![image](https://user-images.githubusercontent.com/2294248/68615929-0000a500-0492-11ea-8188-4e5124abb467.png)

Here I places cursors at the beginning of the lines with the 4, 5, 6, 7, 8, and 9 on them (using <kbd>alt</kbd>+click). I would expect 4, 5, 6, 7, 8, and 9 to be highlighted.
![image](https://user-images.githubusercontent.com/2294248/68616017-2de5e980-0492-11ea-8883-0e034c21f9bc.png)

Version: 1.41.0-insider (system setup)
Commit: 213bdddb72ff7a6c8eed071420de8ddac4293cb1
Date: 2019-11-11T05:40:31.150Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by rebornix** [comment]
I remember @alexandrudima had change which made this possible.

**Comment by alexandrudima** [comment]
I could reproduce:

![image](https://user-images.githubusercontent.com/5047891/68674582-6b13af80-0556-11ea-91f4-d0437c7301d5.png)

**Comment by iansan5653** [comment]
If you can give me a code pointer I can try to work on a PR.
