### ISSUE TITLE
vscode.workspace.fs.stat(): sockets identified as "regular" files.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84524]
VSCode Version: 1.40.0
OS: linux
(working on an extension remotely over SSH; haven't tried local)

If you call `vscode.workspace.fs.stat()` on a socket "file", the resulting `FileStat.type` is `FileType.File`.  Isn't that meant to indicate a ["regular" file](https://linux.die.net/man/2/stat)?  Instead I would expect a socket to be identified as `FileType.Unknown`.

To create a socket:

```typescript
async function createSocket(filename: string): Promise<net.Server> {
    const filename = '/tmp/foo.sock';
    const server = net.createServer();
    await new Promise(resolve => srv.listen(filename, 0, resolve));
    return server;
}
```

Note that this also applies to `vscode.workspace.fs.readDirectory()`.

@jrieken

**Comment by ericsnowcurrently** [comment]
If assigning sockets `FileType.File` isn't going to change then it would be nice to know what kind of file will result in `FileType.Unknown`.

**Comment by bpasero** [comment]
The type gets lost here: 

https://github.com/microsoft/vscode/blob/9b620f43def06692d006f63af991c59fb40bb459/src/vs/workbench/api/browser/mainThreadFileSystem.ts#L75

**Comment by jrieken** [comment]
@bpasero So how does the internal API represent this? What flag are supported to set/unset in the internal model?

**Comment by bpasero** [comment]
@jrieken I added `IFileStat.isFile`, can you please adopt that in `mainThreadFileSystem`?

**Comment by jrieken** [comment]
YEah, will do

**Comment by ericsnowcurrently** [comment]
@bpasero & @jrieken, thanks!
