### ISSUE TITLE
vscode.workspace.fs.stat(): wrong creation time.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84525]
VSCode Version: 1.40.0
OS: linux
(working on an extension remotely over SSH; haven't tried local)

When calling `vscode.workspace.fs.stat()`, the resulting `FileStat.ctime` is consistently `0` rather than the correct creation time.

@jrieken

**Comment by bpasero** [comment]
Coming from:

https://github.com/microsoft/vscode/blob/9b620f43def06692d006f63af991c59fb40bb459/src/vs/workbench/api/browser/mainThreadFileSystem.ts#L55

**Comment by jrieken** [comment]
@bpasero That's because the internal API drops this information, e.g there is no ctime on `IBaseStat`. Are you adding this or should I?

**Comment by bpasero** [comment]
Hm, not sure why it was never there, I can add it.

**Comment by bpasero** [comment]
I pushed a change to use fs.stat().birthtime for ctime. We are a bit diverging from the posix spec that says ctime is "last changed time". But I leave that decision up to @jrieken if we maybe need to be more specific.

**Comment by ericsnowcurrently** [comment]
Thanks @bpasero and @jrieken!
