### ISSUE TITLE
Set focus to editor after selecting a file in explorer

### ISSUE THREAD

**Issue by brgrz** [microsoft/vscode#84527]
It seems there is no way to automatically switch focus to the editor after selecting a file in Explorer bar either by clicking once or double clicking the file.

To me, the most natural way of work is when I select a file focus should move to the editor either to the start of file or, if some sort of history was enabled, to the last edited line.

As it stands now, focus remains within the Explorer bar and if start typing it switches to inline search and if do up/down/pageup/pagedown it scrolls through the files.

**Comment by isidorn** [comment]
Double click swithces focus to the editor. Please try that

**Comment by brgrz** [comment]
@isidorn I know but that only helps when working with files that are being edited yet. If I'm switching clicking on opened files either in Explorer or Open Editors it makes no sense to be double clicking them.

**Comment by isidorn** [comment]
There are duplicates of this request I belive you can search for it and upvote it. Look for issues tagged with file-explorer. Thanks
