### ISSUE TITLE
Cant download VSC to windows link not working 

### ISSUE THREAD

**Issue by timothypinarex3** [microsoft/vscode#84530]
Cant dowload VSC for windows link in not working the redirect takes me to an empty page. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by octref** [comment]
If you open the Developer Tools for your browser, do you see any input?

You can try this link as well https://aka.ms/win32-x64-user-stable.

Note that you would need to enable JavaScript to be able to download it.
