### ISSUE TITLE
Emmet split/join tag eats opening bracket of following tag

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8453]
#8207

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Steps to Reproduce:

1. Paste `<li><a href="">Item 3</a></li>`
2. Put cursor before `I` in `Item`
3. Trigger Emmet: Split/Join tag, notice the opening `<` from the closing `li` tag is missing

![image](https://cloud.githubusercontent.com/assets/2193314/16433471/3b274e72-3d3f-11e6-8618-98addde5b7e7.png)

This is likely happening because vscode is trying being clever when the edit is applied, so it omits adding another opening `<`.

**Comment by Tyriar** [comment]
Potentially related: https://github.com/Microsoft/vscode/issues/8447

**Comment by mrmlnc** [comment]
Exactly the same problem: #8136

**Comment by Tyriar** [comment]
Closing as duplicate of #8136
