### ISSUE TITLE
New window uses old theme

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84539]
- Open vscode
- Change the theme
- Open a new window
- The window is the old theme I guess until the EH starts up, at which point it switches to the new theme

I know that we try to quick restore the theme when starting a window, but did this work at some point after changing the theme? If I restart VS Code after changing the theme then I get the expected behavior.

It might just be more noticeable for me now because if I open a remote window, then the theme isn't fixed until the remote resolver completes, so I might be looking at a window in a different theme for quite awhile until connection finishes.

**Comment by jrieken** [comment]
I'd say this is because the theme is installed in the remote EH and therefore comes in late

**Comment by aeschli** [comment]
@roblourens I can see some strangeness if the theme is defined in the workspace settings. Is that your setup?

**Comment by roblourens** [comment]
I am using builtin themes. Also just changing the theme through the normal command that sets user settings.

**Comment by roblourens** [comment]
Also I see this without having remote involved

**Comment by roblourens** [comment]
Oh, this only happens for the first new window after changing the theme. Maybe that helps.

**Comment by aeschli** [comment]
It's a bug that happens when 2 windows are open while switching themes.
To verify:
- open 2 VS Code windows
- switch the theme from light to dark (or vice versa): theme is applied in both windows
- exit VS Code
- restart VS Code. Both windows open with the colors of the theme selected
