### ISSUE TITLE
Off-center placeholder in extension viewlet

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84538]
![image](https://user-images.githubusercontent.com/323878/68628354-f5500b00-04a5-11ea-88c4-9eddcce23af5.png)

**Comment by misolori** [comment]
@roblourens do you have any repro steps? I'm not seeing this:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/35271042/68694313-cb422b80-052d-11ea-82f9-c6b100094c21.png">

**Comment by roblourens** [comment]
When I search, then click a result, then the list seems to shift upwards. So there might be a sizing issue with the contents of the viewlet.

**Comment by fsauceda** [comment]
may I tackle this issue?

**Comment by sandy081** [comment]
I am not able to repro this. @joaomoreno fixed a layout issue in extensions viewlet yesterday. Can you please try to repro again on latest insiders?

**Comment by roblourens** [comment]
Yeah seems ok now, thanks
