### ISSUE TITLE
.tga image files don't load

### ISSUE THREAD

**Issue by dhrdlicka** [microsoft/vscode#84533]
Issue Type: <b>Bug</b>

1. Open sample images from the [TGA 2.0 conformance suite](https://github.com/image-rs/image/tree/master/tests/images/tga/testsuite) in Code
2. Image preview shows "An error occured while loading the image"

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.19018

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Looks like Chrome does not support tga images (and therefore we wont support them in Electron either)

Bug is that we should not try using the builtin image preview for them
