### ISSUE TITLE
child_process results in ENOMEM error with empty options.env 

### ISSUE THREAD

**Issue by jaycetyle** [microsoft/vscode#84540]
It seens like that there's a known issue in the Nodejs that caused my VSCode extension fail. Please refer to [this link](https://github.com/nodejs/node/issues/29008).

It can be reproduced in the extension just like the steps described by [the issue](https://github.com/nodejs/node/issues/29008).
```
const { execSync } = require('child_process');
execSync('node', {env: {}}) // Fails with ENOMEM error
execSync('node', {env: {x: 0}}) // Works
```

- VSCode Version: 1.40.0
- OS Version: Windows_NT x64 10.0.18362

**Comment by deepak1556** [comment]
@bpasero should we consider backporting this libuv patch https://github.com/libuv/libuv/pull/2408 for recovery ? This is fixed in electron 7, as it contains the necessary node version.

**Comment by bpasero** [comment]
Sure why not, together with the other fix for Windows frameless window maybe.

**Comment by deepak1556** [comment]
PR up at https://github.com/electron/electron/pull/21141

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/85266
