### ISSUE TITLE
Add tests for emmet commands

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8454]
#8207
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

Little excuse not to have tests here considering they should be really easy to write and potentially leverage an official test suite.

**Comment by egamma** [comment]
I agree that we should have tests for the emmet `integration` (EditorAccessor class) but not for emmet itself. Emmet is an upstream component and the testing belongs to the component.

**Comment by ramya-rao-a** [comment]
Now that we have the new emmet model in the extension, I'll use this issue for adding tests to the emmet extension

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/tree/master/extensions/emmet/src/test is the location of tests for all of the Emmet actions coming from the new emmet extension
