### ISSUE TITLE
Devtools for Webview activeFrame does not show Elements

### ISSUE THREAD

**Issue by snoop244** [microsoft/vscode#84544]
- VSCode Version: 1.40.0
- OS Version: Window 10 Pro 1809
- Using a script (working well) from an embedded React TSX.

Steps to Reproduce:

1. Create a webview
2. launch with F5
3. Open Webview Developer Tools from the new instance of VSCode
4. Go to Console, select activeFrame

dropdown item (activeFrame) turns pink and no additional information is provided on the Elements tab as per the Webview docs.  

![image](https://user-images.githubusercontent.com/7346594/68636133-29d0c080-04c0-11ea-81c3-3895c808fe1e.png)

On Elements tab I expect to be able to see my elements within the iFrame, but all I get is:

![image](https://user-images.githubusercontent.com/7346594/68636256-859b4980-04c0-11ea-8bd4-717ee9c36f27.png)

**Comment by mjbvz** [comment]
Just expand those elements. Webview use nested iframes internally

**Comment by snoop244** [comment]
I did that. They are all open in the screenshot. Go ahead and close this, but I tried multiple webview examples and none of them worked.   Either your docs are out of date or this is a bug.

**Comment by snoop244** [comment]
I do wonder if your docs are out of date - and your sample repos (at least Webview sample) because when I git clone, npm install and then "F5" your samples repo. VSCode 1.40.0 does not create the test instance and sits perpetually in "Building..." mode.  The only way I could get a Webview to work was by using Yeoman `yo code` followed by working through your excellent guide on Webview.  Even then, the activeFrame does not work as your docs indicate and the elements on the page cannot be inspected.

**Comment by snoop244** [comment]
Disregard.  I hadn't scrolled all the way down. Apologies.
