### ISSUE TITLE
Upgrade version issue

### ISSUE THREAD

**Issue by giftmy** [microsoft/vscode#84548]
Issue Type: <b>Bug</b>

In Anaconda3 (64-bit) use and pop-up vscode version 1.39 upgrade to 1.4 normal, but call the desktop vscode installation version shortcut vscode version upgrade to 1.4, restart vscode back to 1.39, can not be upgraded to 1.4

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
arepl|alm|1.0.19
vscode-django|bat|0.19.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
open-html-in-browser|cod|0.1.21
vscode-eslint|dba|1.9.1
python-extension-pack|don|1.6.0
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
code-runner|for|0.9.14
vscode-test-explorer|hbe|2.14.6
beautify|Hoo|1.5.0
comment-translate|int|1.4.2
search-node-modules|jas|1.3.0
nbpreviewer|jit|1.2.2
vscode-view-in-browser|kop|1.0.5
vscode-python-test-adapter|lit|0.3.14
MagicPython|mag|1.1.0
python-path|mge|0.0.11
Angular-BeastCode|Mik|8.0.10
vscode-language-pack-zh-hans|MS-|1.40.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
csharp|ms-|1.21.7
vscode-typescript-tslint-plugin|ms-|1.2.3
chrome-tools|msh|0.0.3
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
vscode-yaml|red|0.5.3
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.0.3
vscode-sftp|sun|1.1.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
nodejs-extension-pack|wad|0.1.9
jinja|who|0.0.8
JavaScriptSnippets|xab|1.7.2
vscode-jupyter|yzh|1.2.3

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Are you using Anaconda3 instead of VS Code? If so please file issue against them.

**Comment by giftmy** [comment]
> 您正在使用Anaconda3而不是VS Code吗？如果是这样，请向他们提出问题。

I am using vscode to open vscode prompt version 1.39 to 1.4 upgrade after restarting vscode for version 1.4 to close vscode and open again to version 1.39
But open the vscode version from Anaconda3 to 1.4

**Comment by rebornix** [comment]
It would be great if recordings/gifs are provided to help troubleshoot. I didn't get what's going on here.

**Comment by giftmy** [comment]
> 如果提供录音/ gif文件来帮助进行故障排除，那就太好了。我不知道这里发生了什么。
The upgrade version is 1.4, and after opening, it will change back to 1.39
![未标题-1](https://user-images.githubusercontent.com/44667287/68861766-20955d00-0727-11ea-9e1e-e38ea07bc88c.gif)

**Comment by rebornix** [comment]
The issue above user ran into

* Upgrade to latest version 1.40
* Open
* Close
* Open again, it's showing 1.39 release note

**Comment by joaomoreno** [comment]
I'm not sure what to do here. Please check with the Anaconda project.
