### ISSUE TITLE
module win32api unresolved import 'win32api'Python(unresolved-import)

### ISSUE THREAD

**Issue by asgg4321** [microsoft/vscode#84545]
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

python version: 3.7.5
conda version: 4.7.12

The problem appear in my vscode, but my pycharm is not。

**Comment by rebornix** [comment]
Please file issue against the Python extension you are using.
