### ISSUE TITLE
Performance and repeating characters

### ISSUE THREAD

**Issue by eduardoroliveira** [microsoft/vscode#84551]
Issue Type: <b>Bug</b>

I don' t know what happened but after a recent update, VS Code is too slow  to edit ( big delay) and also it repeats characters, for example when I try to write drive it writes drrrrrriiiiiiive by itself. 

I thouth that was another thing on OS but I tested on other editors and the problem only occurs in VSCode.

Best, 

eduardo.oliveirared@gmail.com

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.18GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|2.4.6
simple-react-snippets|bur|1.2.2
vscode-eslint|dba|1.9.1
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.1.2
prettier-vscode|esb|3.2.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
python|ms-|2019.10.44104
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-react-native|msj|0.13.1
format-html-in-php|rif|1.6.1

</details>

**Comment by eduardoroliveira** [comment]
Also the terminal is completely messed out with replaced characters...

**Comment by gjsjohnmurray** [comment]
Please run with all extensions disabled and see if the problem remains
