### ISSUE TITLE
settings.json intellisense not working again

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8455]
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:01:27.563Z)
- OS Version: Linux x64 4.4.0-24-generic, Ubuntu 16.04

This seems to happen quite a bit, can we add some automated tests to catch it?

![image](https://cloud.githubusercontent.com/assets/2193314/16433846/16682bb8-3d41-11e6-8b09-dc4333437d5d.png)

**Comment by aeschli** [comment]
The problem is that the filtering of the proposals is in the UI code. But yes, we should really have a test.

**Comment by aeschli** [comment]
I can't reproduce this with 798b41ab1cf 2016-06-29T05:14:50.570Z. Also there hasn't been any changes on the filtering side.
![image](https://cloud.githubusercontent.com/assets/6461412/16443333/813673fe-3dd8-11e6-8588-268d272917b8.png)
Maybe something special with the settings file? What about other settings?

**Comment by Tyriar** [comment]
Still reproducing for me in the Insiders build you mention:

Version 1.3.0-insider
Commit 798b41ab1cf3636a27042020a54ddfb4cfb8d23c
Date 2016-06-29T05:14:50.570Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

However it's seems fine in my dev build at 1739c99c7255a22c588d9a1aaa141fdc38c90813. This is happening in master as well https://github.com/Microsoft/vscode/issues/8531

**Comment by Tyriar** [comment]
This is in the console:

```
workbench.main.js:115 vscode_jsonrpc_1.Emitter is not a constructor: TypeError: vscode_jsonrpc_1.Emitter is not a constructor
    at new LanguageClient (/usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-languageclient/lib/main.js:208:34)
    at /usr/share/code-insiders/resources/app/extensions/json/client/out/jsonMain.js:47:22
    at Object.m [as _notify] (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9154)
    at Object.j.enter (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:12732)
    at n.Class.define._run (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14560)
    at n.Class.define._completed (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14001)
    at e.resolveOk (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:7288)
    at p (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:8:5770)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by aeschli** [comment]
Maybe a packaging issue? Can you check your install that you have /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-jsonrpc.
In there should be lib/main.js and lib/events.js

I installed my build from the from the x64.rpm package. Installed it again, still works.
It would be great if you could investigate.

@dbaeumer Dirk, the exception seems to happen when setting up the language client.
I'm out from tomorrow to Tuesday, can you take this? 
@Tyriar Can you add the setting "json.trace.server", and open the output view? If the JSON server starts, this should gibe you a css channel. But if that exception is real, the server probably never is started.

**Comment by dbaeumer** [comment]
@Tyriar it looks like your dev workspace hasn't updated the json-rpc npm module. Could you delete the node_modules folder in extensions/json and run scripts\npm install again to see if that fixes the problem. 

If not could you provide me with the version number of the json rpc  and language client node module in the extensions/json folder.

**Comment by Tyriar** [comment]
@dbaeumer I'm reproducing on the Insiders build though so node modules should be correct, master works fine. I'll double check versions tomorrow in the office.

**Comment by dbaeumer** [comment]
@Tyriar This works for me on the latest insider. Any additional info ?
![cast](https://cloud.githubusercontent.com/assets/1931590/16490634/db1d0272-3eda-11e6-98b2-770bacc79e08.gif)

**Comment by dbaeumer** [comment]
Works under Linux as well.

**Comment by dbaeumer** [comment]
I check what happens if you install the vscode-languageclient via npm install vscode-languageclient@^2.2.1 and that install looks totally ok. Interestingly the stack trace in makes not much sense since on line 208 there is no reference to Emitter. The only one in on line 146. 

Would be really interesting to know how vscode-languageclient/lib/main.js:208:34 looks like

**Comment by dbaeumer** [comment]
The Windows build installs version 2.3.0 of the language client which is also compatible with json rpc 2.2.0.

**Comment by Tyriar** [comment]
@aeschli 

```
❯ ls /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-jsonrpc/lib/
cancellation.d.ts  events.js  main.d.ts           messageReader.js  messageWriter.d.ts
cancellation.js    is.d.ts    main.js             messages.d.ts     messageWriter.js
events.d.ts        is.js      messageReader.d.ts  messages.js

❯ cat /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-jsonrpc/package.json  | grep version
  "version": "2.2.0"
```

@dbaeumer see comment `// line 208` for that line:

```ts
    function LanguageClient(name, serverOptions, languageOptions, forceDebug) {
        var _this = this;
        if (forceDebug === void 0) { forceDebug = false; }
        this._name = name;
        this._serverOptions = serverOptions;
        this._languageOptions = languageOptions || {};
        this._languageOptions.synchronize = this._languageOptions.synchronize || {};
        this._languageOptions.errorHandler = this._languageOptions.errorHandler || new DefaultErrorHandler(name);
        this._syncExpression = this.computeSyncExpression();
        this._forceDebug = forceDebug;
        this._state = ClientState.Initial;
        this._connection = null;
        this._childProcess = null;
        this._outputChannel = null;
        this._listeners = null;
        this._providers = null;
        this._diagnostics = null;
        this._fileEvents = [];
        this._fileEventDelayer = new async_1.Delayer(250);
        this._onReady = new Promise(function (resolve, reject) {
            _this._onReadyCallbacks = { resolve: resolve, reject: reject };
        });
        this._onReady.then(null, function () {
            // Do nothing for now. We shut down after the initialize.
            // However to make the promise reject handler happy we register
            // an empty callback.
        });
        this._telemetryEmitter = new vscode_jsonrpc_1.Emitter(); // line 208
        this._tracer = {
            log: function (message) {
                _this.outputChannel.appendLine(message);
            }
        };
    }
```

```
❯ cat /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-languageclient/package.json | grep version
  "version": "2.3.0"
```

**Comment by dbaeumer** [comment]
@Tyriar can you to one more thing. Can you check that the code in vscode-jsonrpc/lib/main.js as the following line 18: `exports.Emitter = events_1.Emitter;`

**Comment by dbaeumer** [comment]
And I have the exact two same version under Windows and its working there.

**Comment by dbaeumer** [comment]
And on my Linux VM which doesn't show the problem I also see:

```
cat  /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-languageclient/package.json | grep version
  "version": "2.3.0"

cat  /usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-jsonrpc/package.json | grep version
  "version": "2.2.0"
```

So I have no idea what the difference is.

**Comment by dbaeumer** [comment]
The version I run under Linux is:
```
Version 1.3.0-insider
Commit a21c12346f388e51858c930875ca30968604c116
Date 2016-06-30T05:01:41.590Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

**Comment by Tyriar** [comment]
@dbaeumer see `// line 18` comment:

```ts
/* --------------------------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * ------------------------------------------------------------------------------------------ */
'use strict';
var is = require('./is');
var messages_1 = require('./messages');
exports.ResponseError = messages_1.ResponseError;
exports.ErrorCodes = messages_1.ErrorCodes;
var messageReader_1 = require('./messageReader');
exports.StreamMessageReader = messageReader_1.StreamMessageReader;
exports.IPCMessageReader = messageReader_1.IPCMessageReader;
var messageWriter_1 = require('./messageWriter');
exports.StreamMessageWriter = messageWriter_1.StreamMessageWriter;
exports.IPCMessageWriter = messageWriter_1.IPCMessageWriter;
var events_1 = require('./events');
exports.Event = events_1.Event;
exports.Emitter = events_1.Emitter; // line 18
var cancellation_1 = require('./cancellation');
exports.CancellationTokenSource = cancellation_1.CancellationTokenSource;
exports.CancellationToken = cancellation_1.CancellationToken;
var CancelNotification;
(function (CancelNotification) {
    CancelNotification.type = { get method() { return '$/cancelRequest'; } };
})(CancelNotification || (CancelNotification = {}));
(function (Trace) {
    Trace[Trace["Off"] = 0] = "Off";
    Trace[Trace["Messages"] = 1] = "Messages";
    Trace[Trace["Verbose"] = 2] = "Verbose";
...
```

**Comment by dbaeumer** [comment]
This looks fine for me. I checked my Windows and Linux installation and both have the same version for these files. The is one additional file that could make this being broken. That is the events.js file imported on line 16.

@Tyriar can you check that that file has the same content than this file

Also @bpasero tested this on his Linux install without being able to reproduce.

@Tyriar I get the feeling that your install is somehow broken. Besides checking the additional file, could you do the following: uninstall and reinstall VS Code. If it goes away it looks like an update problem. If not, could you do the following:

- open jsonMain.js in the location: `/usr/share/code-insiders/resources/app/extensions/json/client/out`
- change line 26 to `var debugOptions = { execArgv: ['--nolazy', '--debug-brk=6004'] };`
- change line 30 to `run: { module: serverModule, transport: vscode_languageclient_1.TransportKind.ipc, options: debugOptions },`
- start VS Code and attach, open a json file and attach a debugger to 6004. Set a breakpoint in `/usr/share/code-insiders/resources/app/extensions/json/node_modules/vscode-languageclient/lib/main.js' line 208 and check how `vscode_jsonrpc_1` looks like (e.g. is the Emitter property missing, not a function, ...)

**Comment by Tyriar** [comment]
It's working again, closing off for now as I can't repro anymore.
