### ISSUE TITLE
Colors are still dimmed in 1.41

### ISSUE THREAD

**Issue by andreyjamer** [microsoft/vscode#84557]
After #84154 was closed, I tried the latest insiders build to check if colors are really fixed. But seems like there is no changes. 
Here is screenshot from 1.41
![1 41](https://user-images.githubusercontent.com/5379101/68647607-254bec80-0540-11ea-84a1-2b68fb24ef59.png)
Here is the same file in 1.40
![1 40](https://user-images.githubusercontent.com/5379101/68647632-339a0880-0540-11ea-8175-b34ab551f472.png)

Version: 1.41.0-insider (user setup)
Commit: 0d728c31ebdf03869d2687d9be0b017667c9ff37
Date: 2019-11-12T05:39:58.193Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. I set true for `disable-color-correct-rendering` option in argv.json
2. Restarted
3. Also i tried different combinations of values for `disable-hardware-acceleration` and `disable-color-correct-rendering`. No effect.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net

Does the issue reproduce in that setup in the browser?

**Comment by andreyjamer** [comment]
Yes, the colors are also dimmed in web version.
I tried hosted version in Firefox.

**Comment by bpasero** [comment]
@andreyjamer that is great news because it allows us to start investigating which change in Chrome caused this issue for you. There is a straightforward way to try all versions of Chrome from 69 to the 76 we are using via: https://www.chromium.org/developers/bisect-builds-py

Would you be willing to run this experiment and see which change has caused that color change for you?

@alexandrudima can maybe chime in and provide you with the commit ID where to start from because he recently did the same.

**Comment by andreyjamer** [comment]
@bpasero But Firefox has the same issue. So seems like it is not related to Chrome only.

**Comment by bpasero** [comment]
@andreyjamer I would not compare them. It looks like Chrome did a change from 69 to 76 that has caused this, otherwise we would not have seen any change.

**Comment by andreyjamer** [comment]
@bpasero Ok, i can help with checking. Can @alexandrudima provide the commit ID where to start?

**Comment by bpasero** [comment]
@andreyjamer here you go:
* from: `c6a08e5368de4352903e702cde750b33239a50ab`
* to: `91f08db83c2ce8c722ddf0911ead8f7c473bedfa`

**Comment by andreyjamer** [comment]
Well, i checked all versions from 69 to 76 (by `python bisect-builds.py -a win64 -g 665002 -b 576753`) and they all are good. Color are brighter than in the latest Chrome (78.0.3904.97)
So seems something is broken after version 76

**Comment by bpasero** [comment]
@andreyjamer strange. Can you go on and test until that chrome version? The commit is `2fa4ee555b8b5b382d68e1118ab7e6eac293a039`. Btw I am using http://omahaproxy.appspot.com/ to find out.

**Comment by andreyjamer** [comment]
@bpasero Yes. I'll check
Yes, me too

**Comment by bpasero** [comment]
In theory it could be possible that Electron decided to backport a change from Chrome after 76.

**Comment by andreyjamer** [comment]
Well, bisect-builds.py says that some of these commits causes the issue:
https://chromium.googlesource.com/chromium/src/+log/1d3102350fe9eed56fe890814c0a2f492db8a07e..b66e336b79ba4b5926554551ac549c234203dd37

I checked with `python bisect-builds.py -a win64 -g 617353 -b 665013`

But during test in some revisions (5) there was no bug, in others 8 i got the bug. But bug appeared not after the exact revision, but occasionally.

**Comment by alexandrudima** [comment]
Interesting, that is the same bisect result I got with the LCD text bisect I did at https://bugs.chromium.org/p/chromium/issues/detail?id=1016062#c24

**Comment by bpasero** [comment]
@andreyjamer how does it look like with todays insider build? Make sure to update if you did not yet: https://code.visualstudio.com/insiders/

Version must be `b6a486e34fe3715f6edec0cdb11138b1672d33bd` (check from about dialog).

**Comment by andreyjamer** [comment]
@bpasero Colors are fixed! Cool! Thank you!

**Comment by andreyjamer** [comment]
Just got the update for stable and colors are also fixed.
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

But for web version colors are still dimmed for Firefox only. In Chrome colors are fine.

Version: 1.41.0-insider
Commit: b6a486e34fe3715f6edec0cdb11138b1672d33bd
Date: 2019-11-14T05:24:02.319Z (product build time)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

**Comment by bpasero** [comment]
Awesome.

**Comment by andreyjamer** [comment]
@bpasero You've seen my notice about Firefox? I'm think it should work the same for all browsers, but not sure if it is related to the bug somehow.

**Comment by bpasero** [comment]
Can you proof that Firefox supports LCD font rendering? E.g. by checking a normal website and attaching a screenshot that shows fonts.

**Comment by andreyjamer** [comment]
You mean my Firefox? Not sure about it. I use 70.0.1 (64-bit) on Windows_NT x64 10.0.18363
Screenshots of the page https://www.theguardian.com/lifeandstyle/shortcuts/2019/nov/13/fat-cats-how-to-get-a-lazy-obese-feline-into-perfect-shape

100% scale
![ff_font_1](https://user-images.githubusercontent.com/5379101/68837710-f9b33880-06de-11ea-9101-e31c46b6f7fb.png)

200% scale:
![ff_font_200](https://user-images.githubusercontent.com/5379101/68837725-05066400-06df-11ea-95c2-9cd26c4f1282.png)

**Comment by bpasero** [comment]
I opened https://github.com/microsoft/vscode/issues/84786 to follow up.

**Comment by andreyjamer** [comment]
Thank you!
