### ISSUE TITLE
Irratic Jumping Behaviour Of Cursor

### ISSUE THREAD

**Issue by sandeepksharma15** [microsoft/vscode#84559]
This behavior doesn't have concrete steps for reproduction but whenever there is a pause in my typing and the cursor jumps to some other location, typically, last character, or last line, some time to the last word.

I found some references to this bug in 2018 but it seems to have been fixed in the past. It has appeared only after the last update

CPUs | AMD Ryzen 7 1800X Eight-Core Processor (16 x 3600)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 63.95GB (53.05GB free)
Process Argv | .
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
scss-lint | ada | 0.1.9
bracket-pair-colorizer | Coe | 1.0.61
react-template | dab | 0.0.5
es7-react-js-snippets | dsz | 2.4.4
prettier-vscode | esb | 3.2.1
auto-rename-tag | for | 0.1.1
vscode-styled-components | jpo | 0.0.27
code-beautifier | mic | 2.3.3
remote-wsl | ms- | 0.40.2
csharp | ms- | 1.21.7
vscode-typescript-tslint-plugin | ms- | 1.2.3
elmmet | nec | 1.0.1
indent-rainbow | ode | 7.4.0
vscode-css-peek | pra | 3.0.2
psi-header | psi | 1.8.1
quicktype | qui | 12.0.46
LiveServer | rit | 5.6.1
code-settings-sync | Sha | 3.4.3
stylelint | shi | 0.51.0
highlight-matching-tag | vin | 0.9.5
vscode-icons | vsc | 9.5.0
vscode-todo-highlight | way | 1.0.4
vscode-import-cost | wix | 2.12.0
vscode-preview-server | yui | 1.3.0
html-css-class-completion | Zig | 1.19.0

**Comment by rebornix** [comment]
@sandeepksharma15 can you reproduce this issue by disabling all extensions?
