### ISSUE TITLE
S.resolve (file:///C:/Users/Someone/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1555:706)

### ISSUE THREAD

**Issue by TLKG** [microsoft/vscode#84554]
[renderer3] [error] File not found (c:\Program): Error: File not found (c:\Program)
    at S.resolve (file:///C:/Users/Someone/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1555:706)

- VSCode Version: 1.40.0
- OS Version: Win10 (Windows_NT x64 10.0.18362)

Steps to Reproduce:

1. have a NODE REST API project, build and run ok.
2. but <OUTPUT> output this

> [renderer3] [error] File not found (c:\Program): Error: File not found (c:\Program)
>     at S.resolve (file:///C:/Users/Someone/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1555:706)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please put some effor into filling an issue.
https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by TLKG** [comment]
Isidor,
What's missing?

On November 14, 2019 at 7:01 AM, Isidor Nikolic <notifications@github.com> wrote:



Please put some effor into filling an issue.
https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by isidorn** [comment]
Effort

**Comment by TLKG** [comment]
Confused. 
Details are provided.

**Comment by weinand** [comment]
@TLKG for one: the title is not helpful for understanding the issue.
