### ISSUE TITLE
Go to definition should highlight the new focus

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#84553]
If the `Go to definition` jumped to a .java source file, there will be a cursor blinking in the new position, that's OK.

But if the `Go to definition` jumped to a .class file, which vscode-java extension used a customized content provider to render the class's source contents, there is only a static cursor hanging in the new place. Sometimes it's hard for me to find the new focus. See the screenshot below.
![goToDefinition](https://user-images.githubusercontent.com/14052197/68644584-68ae5700-0550-11ea-8da6-df150f49c943.gif)

I expect the cursor to blink in the contributed content provider, or highlight the range with the selection because the definition response returns the range info.

**Comment by akaroml** [comment]
Interesting one. With editable files, the cursor blinks so it's easy to locate the symbol. But in readonly files, the cursor is not blink, and the symbol is not highlighted either. So it's a bit challenging to find where the focus is.

**Comment by jrieken** [comment]
I have pushed - for goto commands and symbol navigation

![Nov-15-2019 15-47-03](https://user-images.githubusercontent.com/1794099/68952473-3440d200-07c0-11ea-83f5-8cba2270e582.gif)

**Comment by testforstephen** [comment]
How to try the new UX? I tried the latest insider, still old behavior.

Version: 1.41.0-insider (system setup)
Commit: fe03510f9e9fb269ca35da0ea600dd95279fa2b7
Date: 2019-11-18T05:31:02.684Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
Yeah, it is in the build. It uses the range highlight color, e.g the color that quick outline preview uses. What theme are you using? Could it be that the color isn't prominent in that theme?

**Comment by testforstephen** [comment]
default dark. It's really hard to notice the quick blink in dark theme.

However, light theme looks good.

**Comment by jrieken** [comment]
Hm, we might wanna add a new theme color in that case, one which is more prominent for this case

**Comment by jrieken** [comment]
I have pushed new theme colors: `editor.symbolHighlightBackground` and `editor.symbolHighlightBorder`. Currently they default to the range highlight color but we can now take something strong. Adding @misolori for color-consulting.

**Comment by misolori** [comment]
@jrieken is there a reason why the background color doesn't stay when you cycle through? I don't think we do any flashing of colors like that.

**Comment by jrieken** [comment]
I am open for suggestion but I wouldn't know when else to remove the highlight. Should it stay until you move the cursor out of the definition or when you start typing? Often you go to a definition and that's it, e.g. there is no "I am done" gesture. To make matters worst, often definition ranges aren't just an identifier but the whole thing, e.g the whole function, and that make detecting you move away harder

**Comment by jrieken** [comment]
Closing for now - accepting more feedback via issues ;-)

**Comment by jrieken** [comment]
to verify: trigger go to definition, notice a highlight for a short while. verify that the highlight color can be tweaked via: `'editor.symbolHighlightBackground'` and `'editor.symbolHighlightBorder'`

**Comment by testforstephen** [comment]
Can VS Code provide a more contrasting highlight color for dark theme by default? i believe most of users don't know how to customize the color for a specific theme.

**Comment by jrieken** [comment]
@misolori can you help with that 🔝

**Comment by connor4312** [comment]
Imo the duration should be configurable. The quick highlight is a good, but depending on how contrasting the color is it might be difficult to notice in the few hundred ms of display, and in general (non-configurable) duration-based visual effects are not good for vision impaired users.

**Comment by misolori** [comment]
I’ll tweak the colors so it has a stronger contrast.

**Comment by jrieken** [comment]
@misolori Re-opening so that we don't forget the color tweak

**Comment by misolori** [comment]
What about using the same color as either `editor.wordHighlightStrongBackground` or `editor.findMatchHighlightBackground`? I personally prefer the latter.

## `editor.wordHighlightStrongBackground`

![ezgif com-gif-maker (13)](https://user-images.githubusercontent.com/35271042/70260594-79b04980-1745-11ea-9c43-e52cd1cf9762.gif)


## `editor.findMatchHighlightBackground`
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/35271042/70261559-8b92ec00-1747-11ea-950f-57be4efdb2a4.gif)

**Comment by jrieken** [comment]
I have pushed a change to use `editorFindMatchHighlight`

**Comment by akaroml** [comment]
Thank you both @misolori @jrieken
