### ISSUE TITLE
Cannot commit if message has `#` character

### ISSUE THREAD

**Issue by huytrongnguyen** [microsoft/vscode#84567]
- VSCode Version: 1.40.0
- OS Version: macOS Catalina

Steps to Reproduce:

1. Write a commit with message has `#` character, for example: #1 Test a commit
2. Try to click on commit button, nothing happened
3. Remove `#` character
4. Click on commit button, it works

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/84201
