### ISSUE TITLE
CLI does not support chrome flags anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84564]
![image](https://user-images.githubusercontent.com/900690/68654482-4f94ae80-052e-11ea-9c44-a0758517c5f5.png)

**Comment by bpasero** [comment]
This makes it very hard for us to diagnose issues. At least there should be a way to pass Chrome flags still over.

**Comment by nogeenkopjethee** [comment]
This is mentioned in the October 2019 changelog: https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration.

You can now use Chrome flags by using a preferences file.

**Comment by aeschli** [comment]
In the meantime the message has been changed to
`Warning: '{0}' is not in the list of known options, but still passed to Electron/Chromium.`
