### ISSUE TITLE
Copy n' Paste text selection behaves strangely

### ISSUE THREAD

**Issue by QAnders** [microsoft/vscode#84566]
- VSCode Version: 1.39.1
- OS Version: Win10 18362

Steps to Reproduce:

1. Double-click any text, e.g. variable, and copy by CTRL+C (or from context menu
2. Double-click any other text and chose Paste and (most often) it Paste's the copied text in the middle instead of replacing the text as expected. Manually selecting text and Paste replaces the text as expected.
![copypastevscode1](https://user-images.githubusercontent.com/12028885/68657480-1d864b00-0534-11ea-92ea-0c955533dde0.gif)

It seems as it is the double-click that actually not makes the text a selection to replace the selected text.

Does this issue occur when all extensions are disabled?: Yes

**Comment by uziel200** [comment]
Is the same that #84319

**Comment by QAnders** [comment]
Indeed @uziel200 ... Sorry about that, didn't find it...
Resetting the Zoom level seems to have solved this issue for me!
