### ISSUE TITLE
Codeblocks in Markdown Preview don't use theme colors

### ISSUE THREAD

**Issue by davidbernegger** [microsoft/vscode#84572]
- VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
- OS version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. write markdown
2. open markdown preview
3. markdown preview does not use theme of code 
![image](https://user-images.githubusercontent.com/16232537/68661693-a5bc1e80-053b-11ea-84e1-9e94264b37da.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
As designed. We use highlight.js in the preview since many websites also use this for highlighting

Try this extension to have the preview's highlighting better match VS Code's colors: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-shiki
