### ISSUE TITLE
Toggle Word wrap is not working.

### ISSUE THREAD

**Issue by krishnachouhan** [microsoft/vscode#84571]
Issue Type: <b>Bug</b>

VS Code: Version 1.40.0
OS:          Windows_NT x64 10.0.17763

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.88GB free)|
|Process Argv|C:\Users\212574384\Box Sync\HealthCare\1\AT\ErrorCode Analysis\data\processed\table\lcs_all_srs_msg_code_output_TABLE.csv|
|Screen Reader|no|
|VM|0%|
</details>

Extensions:

Issue Type: <b>Bug</b>

VS Code: Version 1.40.0
OS:          Windows_NT x64 10.0.17763

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.88GB free)|
|Process Argv|C:\Users\212574384\Box Sync\HealthCare\1\AT\ErrorCode Analysis\data\processed\table\lcs_all_srs_msg_code_output_TABLE.csv|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension
|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.21
gc-excelviewer|Gra|2.1.32
prettify-json|moh|0.0.3
mssql|ms-|1.7.0
python|ms-|2019.10.44104
vscode-sql-beautify|sen|0.0.4
pico8-simple-outline|unr|0.0.2
crs-al-language-extension|wal|1.1.21

</details>

**Comment by gjsjohnmurray** [comment]
Do you also have the problem if you disable all extensions? If yes, please post screenshots.

**Comment by krishnachouhan** [comment]
sorry about late reply but i think vscode is working just great as always. Possible issue was hotkey conflict with nvidia's hotkey. (Not sure but shutting its processor down solved it then.)
