### ISSUE TITLE
Code Trembling

### ISSUE THREAD

**Issue by McVinnich** [microsoft/vscode#84577]
Issue Type: <b>Bug</b>

with the new version, the text starts to tremble when I start editing it

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
shaderlabvscodefree|aml|1.1.5
csharpfixformatfixed|Aww|0.0.81
unity3d-pack|dim|1.0.0
gitlens|eam|10.1.2
vscode-csharp-snippets|jor|0.3.1
docomment|k--|0.1.8
favorites|kdc|2.4.5
unity-code-snippets|kle|1.3.0
csharpfixformat|Leo|0.0.84
colored-regions|mih|0.0.3
csharp|ms-|1.21.7
qub-xml-vscode|qub|1.2.8
shader|sle|1.1.4
unity-tools|Tob|1.1.1
statusbar-format-on-save|tre|1.1.0
unity-debug|Uni|2.7.2

</details>

**Comment by McVinnich** [comment]
Video
https://monosnap.com/file/EdeUhSUqZaQjghc8r8doEdlg8qZKHG

**Comment by rebornix** [comment]
@McVinnich do you have word wrap turned on? Does it happen in all files you are editing?

**Comment by McVinnich** [comment]
> @McVinnich do you have word wrap turned on? Does it happen in all files you are editing?

i dont use word wrap;
it happens for all files;

My settings.json
{
    "files.autoSave": "afterDelay",
    "csharp.format.enable": false,
    "csharpfixformat.style.braces.onSameLine": false,
    "csharpfixformat.style.newline.elseCatch": true,
    "csharpfixformat.style.spaces.beforeIndexerBracket": false,
    "csharpfixformat.style.spaces.insideEmptyBraces": false,
    "explorer.confirmDelete": false,
    "[csharp]": {
        "editor.defaultFormatter": "Leopotam.csharpfixformat"
    },
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "editor.fontSize": 15,
    "editor.formatOnSave": true,
    "editor.minimap.renderCharacters": false,
    "editor.minimap.scale": 1.5,
    "editor.snippetSuggestions": "top",
    "explorer.confirmDragAndDrop": false,
    "coloredRegions.namedColors": {
        "DarkBlue": "rgba(50, 150, 220, 0.15)",
        "Purple": "rgba(150, 90, 180, 0.15)",
        "Mint": "rgba(30, 190, 150, 0.15)",
    },
    "favorites.storageFilePath": ".vscode/favorites.json",
}


p.s. reinstalling vscode solved my problem

**Comment by rebornix** [comment]
Thanks, good to know reinstalling fixes for you. Close it now and we can reopen when necessary.
