### ISSUE TITLE
TypeScript doesn't set selection range properly

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#84576]
* open document symbols on a test-files
* :bug: the selection range is always the (full) range

**Comment by jrieken** [comment]
@mjbvz fyi - I have pushed a commit that fixes most of these cases but there is still an issue with TS and I believe it's a tsserver bug. With the snippet below, the `IFoo2` will have two spans but only one nameSpan and therefore only is contained. Do you know if that's a known bug to them?

```
interface IFoo2 {
    foo: any;
}

interface IFoo2 {
    foo2: any;
}
``

**Comment by mjbvz** [comment]
Thanks for the fix @jrieken 

Opened https://github.com/microsoft/TypeScript/issues/35068 to track root cause upstream
