### ISSUE TITLE
VSCode - Insiders 1.41.0, bug in creating sub folders

### ISSUE THREAD

**Issue by ZaJarv** [microsoft/vscode#84583]
- VSCode Version: 1.41.0-insider
- OS Version: macOS Catalina 10.15.1

With today update found interesting bug in VSCode Insiders build, when tried to create subfolder, VSCode behaves very strange, just take a look at screenshot and you will understand.

![image](https://user-images.githubusercontent.com/50248102/68667705-b5496080-0557-11ea-9ab0-5fafcf53dd08.png)

As you can see, it shows 'component/header' path as one, instead of nested/tree view. But when i checked folder structure in terminal, everything looks ok, there was 'components' folder and 'header' folder inside it.

But with such bug i cannot create subfolders. When i try to create folders under 'components', name of new folders just appends to 'components' name and new folder goes right into 'header' folder, instead to be right under 'components' folder🤔

But, if you create any file, even just empty, inside folder where you want to put your new folders, everything works cool🤷‍♀️

**Comment by IllusionMH** [comment]
In the meantime you can disable this feature settings **Explorer: Compress Single Child Folders** (`explorer.compressSingleChildFolders`) to `false` to see whole tree.
Or select `src` folder click on New Folder and enter `components/footer` which will create all nested folders in path.

**Comment by IllusionMH** [comment]
@joaomoreno is it possible to add quick pick or something like this with possible paths for New File/Folder when activated on "compressed" node?

**Comment by joaomoreno** [comment]
@ZaJarv This is because we now automatically compress single-child folder sequences. Everything works fine here... you're just lacking actions in the `components` folder when it's compressed together with `header`. Moving to #84597
