### ISSUE TITLE
Mark typescript class or function as deprecated with jsDoc

### ISSUE THREAD

**Issue by FINAs** [microsoft/vscode#84580]
It's glad to  see jsdoc is supported in typescript default and  comment a class is easy.I'm searching a advanced usage for code hint intergated with jsdoc.

```ts
/**
 @author kbg
 @deprecated removed in future
*/
class DeprecatedClass{
}
```
hope to see the hint for warnning like this
![](https://code.visualstudio.com/assets/updates/1_38/suggest-deprecated.png)

**Comment by spahnke** [comment]
This would have to be implemented in the TypeScript service first. AFAICT the upstream issues are
* https://github.com/microsoft/TypeScript/issues/33092 and
* https://github.com/microsoft/TypeScript/issues/33093

**Comment by mjbvz** [comment]
Track upstream by https://github.com/microsoft/TypeScript/issues/33092
