### ISSUE TITLE
User snippets no longer take precedence

### ISSUE THREAD

**Issue by tj** [microsoft/vscode#84587]
- VSCode Version: 1.40.0
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

Type a user snippet prefix `ij` in this case, and see that while it's above the others, it is not selected first.

<img width="761" alt="Screen Shot 2019-11-12 at 12 29 52 PM" src="https://user-images.githubusercontent.com/25254/68671877-4a445d80-0548-11ea-8184-e2da5beadf41.png">

Pressing the up arrow then selects the correct one:

<img width="743" alt="Screen Shot 2019-11-12 at 12 29 58 PM" src="https://user-images.githubusercontent.com/25254/68671908-60eab480-0548-11ea-8107-486e8547bc62.png">

In the previous release I was using this worked fine, but I'm not sure if it's intentional or a bug.

**Comment by jrieken** [comment]
/needsMoreInfo

This works find for me and I also don't recall any changes in that area. Please add  steps that allow me to reproduce this.

<img width="582" alt="Screenshot 2019-11-13 at 09 56 03" src="https://user-images.githubusercontent.com/1794099/68747932-cf3c7f00-05fb-11ea-9ba9-a5f42fedcf07.png">

**Comment by tj** [comment]
Hmm if it works for you I'm not sure how to reproduce it, but it is consistent, I get it all the time and with all my snippets, it could be an extension or something. Let me know if there's anything which would help narrow it down!

**Comment by jrieken** [comment]
Is another item selected, maybe the last? Can you try this setting "editor.suggestSelection": "first"?

**Comment by tj** [comment]
No luck, I didn't have `editor.suggestSelection` but I added "first" and it still autocompletes to other things first, oddly it selects ones which aren't even really good matches like in the screenshot

**Comment by jrieken** [comment]
When you press Cmd+? while showing suggestions (and details) then the details pane goes into an explain mode. Can you attach a screen shot of the first two item?

**Comment by tj** [comment]
Done! Thanks for the help.

<img width="735" alt="Screen Shot 2019-11-19 at 2 20 49 PM" src="https://user-images.githubusercontent.com/25254/69154525-13d28980-0ad8-11ea-9f7f-3746b657ee3d.png">
<img width="715" alt="Screen Shot 2019-11-19 at 2 21 34 PM" src="https://user-images.githubusercontent.com/25254/69154526-13d28980-0ad8-11ea-8557-bd78c34b7273.png">

My snippet uses "tr" here for context, but matches `true` first, even though it's an exact match:

<img width="715" alt="Screen Shot 2019-11-19 at 2 21 08 PM" src="https://user-images.githubusercontent.com/25254/69154558-1d5bf180-0ad8-11ea-8580-a39fcdf60a2c.png">

**Comment by jrieken** [comment]
What extension is this? From the second screen shot it seems that it creates suggestions that enforce the behaviour. It sets `ij` as filter text meaning the editor compares `ij` (filterText) with `ij` (prefix) and that explains the high rank

**Comment by tj** [comment]
Hmm I'm not intentionally using anything which would manipulate whatever VSCode does by default for snippets

**Comment by jrieken** [comment]
What extension is this. I mean in what language are you coding? What extension is providing those suggestions?

**Comment by tj** [comment]
It's Go, and the suggestions that I'm worried about at least are just from my snippets. If there are other suggestions in there I'm not sure where they come from aside from VS Code itself.

**Comment by jrieken** [comment]
Thanks for following up. This is the GO extension and please follow up with them because they monopolise the suggestion flow with their behaviour which enforcing "their ordering" of items - which isn't what users always want.
