### ISSUE TITLE
Compress Single Child Folders: Delete whole compressed tree

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#84589]
Issue Type: <b>Feature Request</b>

There should be an option to delete whole nested tree when Delete used on compressed node.

I have folder `a/b/c/d/e`. If I use <kbd>Delete</kbd> on this item and confirm deletion it will only remove `e` leaving `a/b/c/d` tree node.
Even worse - selection(cursor) is not applied to new these new node and I have to go to that node again and again after each deletion.

VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:39:58.193Z)
OS version: Windows_NT x64 10.0.18362

/cc @joaomoreno

**Comment by joaomoreno** [comment]
Yeah, this is something we're working on, but don't have an issue for. There are more UX things around it, so let's just move to: https://github.com/microsoft/vscode/issues/84597

> Even worse - selection(cursor) is not applied to new these new node and I have to go to that node again and again after each deletion.

I'm currently working on this as a bug fix.
