### ISSUE TITLE
Ctrl + Shift + E doesn't work on Ubuntu 19.10

### ISSUE THREAD

**Issue by Eli-Goldberg** [microsoft/vscode#84582]
Using the File Explorere shortcut in Ubuntu 19.10 ignores the shortcut combination,
and instead writes the actual keys pressed, with an error sound (chime).
Tested without extensions on both code and code-insiders.

- VSCode Version: 
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-19-generic snap

- OS Version: 
Ubuntu 19.10

Steps to Reproduce:

1. Open any file
2. Press Ctrl + Shift + E
3. the letter **e** will be inserted (instead of opening the file explorer)
4. any following key stroke is not recognized as a shortcut, and plays an error sound (chime),
until clicked with the mouse anywhere

**Comment by Eli-Goldberg** [comment]
Definitely related to:
#72947 
#72642

and possibly related to:
#48480
#84633

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/84633

**Comment by evenfrost** [comment]
For actual solution see my https://github.com/microsoft/vscode/issues/84464#issuecomment-559415030.
