### ISSUE TITLE
Integrated terminal not showing up

### ISSUE THREAD

**Issue by arjunbox** [microsoft/vscode#84596]
- VSCode Version: 1.40.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open VS Code
2. Click on Terminal - New Terminal

Does this issue occur when all extensions are disabled?: Yes

Integrated terminal is a black screen without any prompt.

**Comment by rebornix** [comment]
@arjunbox can you open Developer Tools (F1 -> Toggle Developer Tools) to see if there is any error logged there?

**Comment by arjunbox** [comment]
VSCode Version: 1.40.0
OS Version: Windows_NT x64 10.0.17763
Extensions: None. Its a fresh install. .vscode/extensions folder is empty.

Steps to Reproduce:
Open VS Code
Click on Terminal - New Terminal
Integrated terminal is a black screen without any prompt.

There are no errors in Dev Tools console.

![image](https://user-images.githubusercontent.com/23155794/68765435-c68f7d00-05ea-11ea-8853-201208d66545.png)

Please let me know if you need any other information.

**Comment by tufei** [comment]
Same issue happens after upgrading to the latest 1.40.1.

I found a workaround that you can try. Enable the '--verbose' option on the command line, then the terminal will show up. Otherwise it gets stuck forever, cannot do debugging, cannot build.

This is on amd64 Ubuntu 16.04.

**Comment by Tyriar** [comment]
This is a bug in Windows 10 1809, unfortunately we have no way to work around the issue so you will need to wait until you get the next version of Windows 10 (1903).

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by Tyriar** [comment]
@tufei please create a new issue as I believe this one is a Windows 10 problem.
