### ISSUE TITLE
Preferences fails to show all language-specific settings

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#84590]
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Add the following to your user-level settings.json file:

```
    "[javascript]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2
    },
    "[python]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
```

2. Open preferences using cmd+,
3. Search for tabSize

Note that the resulting preferences will show your custom [yaml] settings but neither the custom [python] nor [javascript] settings.

![vscode-tabsize](https://user-images.githubusercontent.com/3178883/68676020-14db4800-0527-11ea-9f75-26ceca19efe9.png)

**Comment by roblourens** [comment]
We have https://github.com/microsoft/vscode/issues/74195 for this
