### ISSUE TITLE
Terrible Pined Window

### ISSUE THREAD

**Issue by wulichenyang** [microsoft/vscode#84594]
Issue Type: <b>Performance Issue</b>

Don't make the current window pined since I could not toggle my window through the hidden windows menu.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.47GB free)|
|Process Argv|--folder-uri file:///f%3A/%E9%9D%A2%E8%AF%95|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   102	  4336	code main
    0	   271	  2852	   window (post.ts - vue-muse-forum - Visual Studio Code)
    0	     1	  1848	     winpty-process
    0	     0	 13768	       D:\git\bin\bash.exe
    0	     5	  2944	         "D:\Git\bin\..\usr\bin\bash.exe"
    0	    50	  3352	     extensionHost
    0	    12	  5320	       "D:\vscode\Microsoft VS Code\Code.exe" "d:\vscode\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=3352
    0	    96	  9072	       electron_node tsserver.js 
    0	     8	 14492	         electron_node typingsInstaller.js typesMap.js 
    0	   157	 11524	       electron_node vueServerMain.js 
    0	    33	 13032	       electron_node tsserver.js 
    0	     6	 13572	       "D:\vscode\Microsoft VS Code\Code.exe" "d:\vscode\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=3352
    0	    18	  5788	     searchService
    0	     5	 14604	     watcherService 
    0	     2	 15196	     winpty-process
    0	     0	  6348	       D:\git\bin\bash.exe
    0	     1	  8528	         "D:\Git\bin\..\usr\bin\bash.exe"
    0	   115	  3956	   gpu-process
    0	   216	  3996	   window (follow.js - vue-blog-server - Visual Studio Code)
    0	     2	  3800	     winpty-process
    0	     0	  8152	       D:\git\bin\bash.exe
    0	     1	 11336	         "D:\Git\bin\..\usr\bin\bash.exe"
    0	    58	  8820	     extensionHost
    0	    37	  7952	       electron_node tsserver.js 
    0	   177	  9740	       electron_node tsserver.js 
    0	    18	 13316	         electron_node typingsInstaller.js typesMap.js 
    0	     4	  9808	     watcherService 
    0	    33	 11416	     searchService
    0	     1	  6524	   electron-crash-reporter
    0	    39	  9152	   shared-process
    0	    63	 12568	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (follow.js - vue-blog-server - Visual Studio Code)
|  Window (post.ts - vue-muse-forum - Visual Studio Code)
|    Folder (vue-muse-forum): 208 files
|      File types: jpg(64) vue(46) ts(37) json(5) js(4) css(3) scss(2)
|                  browserslistrc(1) gitignore(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1) tslint.json(1)
|    Folder (vue-blog-server): 119 files
|      File types: js(50) log(46) pug(3) gitignore(1) json(1) md(1) lock(1)
|                  css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.4.4
beautify|Hoo|1.5.0
vscode-clang|mit|0.2.3
python|ms-|2019.10.44104
cpptools|ms-|0.26.1
vetur|oct|0.22.6
scala|sca|0.3.8
vscode-icons|vsc|9.5.0
clang-format|xav|1.9.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@wulichenyang Sorry, I don't understand the issue fully. What do you mean by pinned window?
