### ISSUE TITLE
Support mix-encodings file search.

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode#84592]
Vs-code file search supports only-one encoding only.

![image](https://user-images.githubusercontent.com/7285119/68674563-117ca680-0591-11ea-8f83-1abbd7ffb051.png)
![image](https://user-images.githubusercontent.com/7285119/68676869-e9437680-0595-11ea-876e-b382b5d6fb31.png)

I am planning to add support for users of vs Code with an optional advanced search capability that supports multiple file codes.

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/34315 and we won't be able to support it, sorry.

**Comment by sunbohong** [comment]
@roblourens 

ripgrep supports searching files in text encodings other than UTF-8, such as UTF-16, latin-1, GBK, EUC-JP, Shift_JIS and more. (Some support for automatically detecting UTF-16 is provided. Other text encodings must be specifically specified with the -E/--encoding flag.)

https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#file-encoding

**We can guess the file's encoding and provide it to riggrep.**

**Comment by roblourens** [comment]
We can't do that without massively slowing down search.

**Comment by sunbohong** [comment]
> We can't do that without massively slowing down search.
This will slowing down search,so i only want it to be **an optional advanced**
