### ISSUE TITLE
Support reading and writing language specific settings in the API

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#84599]
To migrate onto the new code actions on save model it would be great to be able to write language specific settings programmatically to support disabling code actions on save for certain language types. For example enable it for ESLint for JavaScript but disable it for TypeScript.

**Comment by dbaeumer** [comment]
A good example for reading is 

```json
	"eslint.validate": [
		"javascript",
		"html",
		"vue"
	]
```

**Comment by sandy081** [comment]
/duplicate


#26707
