### ISSUE TITLE
Explorer: Improve compressed folder actions

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84597]
We want to support the following use cases on a compressed folder row:

- [x] Context clicking each folder
- [x] Keyboard navigation among compressed folders
- [x] Multiple selection should include all the folders in a compressed row
- [x] Drag & drop 
- [x] Rename

**Comment by IllusionMH** [comment]
Do I understand correctly that problem described in #84583 will be handled in "Context clicking each folder" item?

**Comment by joaomoreno** [comment]
Yes!

**Comment by isidorn** [comment]
Adding on test-plan item since there will be a test plan item for this feature request.
@joaomoreno let me know if you would like me to write a test plan item for the compact trees in the explorer
