### ISSUE TITLE
Cannot validate the php file. The php program was not found.

### ISSUE THREAD

**Issue by cra0kalo** [Microsoft/vscode#846]
Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

I put php in a folder and set the path like so:
set "php.validate.executablePath" : "E:\Program Files (x86)\VSRes\php\php.exe"

and yet it keeps throwing this error!

**Comment by cra0kalo** [comment]
Issue fixed adding
// Place your settings in this file to overwrite default and user settings.
{
    "php.validate.executablePath" : "E:\\Program Files (x86)\\VSRes\\php\\php.exe",
	"php.validate.run": "onType"
	
}

to the config file works

**Comment by tmd-uk** [comment]
Just a quick one on that - I noticed an error when it was entered that way. Instead use / instead of \ ( I hope that makes sense?).

**Comment by vkleidaras** [comment]
One small detail please give the path using "slash" otherwise it doesn't work so it should be like this...

// Place your settings in this file to overwrite default and user settings.
{
    
	// Points to the php executable.
	"php.validate.executablePath": "C:/wamp/bin/php/php5.5.12/php.exe",
    
	// Whether the linter is run on save or on type.
	"php.validate.run": "onType"
}
