### ISSUE TITLE
{# Breaks html auto format

### ISSUE THREAD

**Issue by DubiousDoggo** [microsoft/vscode#84606]
Issue Type: <b>Bug</b>

Typing `{#` causes the html auto format to stop

Steps to Reproduce:

1. Type some html containing `{#`
2. Auto Format  

Example:
```html
      <html>
        <div>
     <p>   Sample Text    </p>
  </div>    <div>
      <p>   Typing {# breaks vscode </p>

       <p>     
             This part is not formatted
             </p>
         </div>
</html>
```
Expected:
```html
<html>
<div>
    <p> Sample Text </p>
</div>
<div>
    <p> Typing {# breaks vscode </p>

    <p>
        This part is not formatted
    </p>
</div>

</html>
```
Actual:
```html
<html>
<div>
    <p> Sample Text </p>
</div>
<div>
    <p> Typing {# breaks vscode </p>

       <p>     
             This part is not formatted
             </p>
         </div>
</html>
```

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none  

Does this issue occur when all extensions are disabled?: Yes

**Comment by rcgardne** [comment]
This is relevant for any Thymeleaf templates, which make extensive use of '{#' syntax, as seen [here](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#strings)

**Comment by timcluyts** [comment]
This is still the case. Will this ever be picked up?
Thymeleaf is a popular templating engine and this seems like a thing that could be fixed rather quickly.

**Comment by TimBroddin** [comment]
Got the same problem :(

**Comment by bogdankatishev** [comment]
Same problem here

**Comment by rubencausyn** [comment]
Same problem here

**Comment by KieferBE** [comment]
Same problem

**Comment by BavoVanGeit** [comment]
Same problem here

**Comment by DubiousDoggo** [comment]
Got a response from beautifyjs
https://github.com/beautify-web/js-beautify/issues/1847#issuecomment-723344984
I'm not sure if this still an upstream issue but the problem still occurs as of Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
