### ISSUE TITLE
Allow multiple formatters to be specified in order for `editor.defaultFormatter`

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode#84603]
Currently if multiple formatters are available for a language, Code asks which one you'd like to use or set as default. If you want to use others, you have to use the `Format Document With...` command.

In certain cases, it may be desirable to run multiple formatters in order on save. For example, you might run a general formatter like Prettier for TypeScript, and then run an additional more specific formatter for formatting TSDoc comments. Or maybe if the Eslint extension registered a formatter that auto-runs `eslint --fix`, you might set that to run. If "Organize Imports" was registered as a formatter, it would be simple to add this to the list of formatters as well.

This could be done as a non-breaking change by simple allowing either a string or an array of strings as a value for `editor.defaultFormatter`, ie:
```json
    "[typescript]": {
      "editor.defaultFormatter": ["esbenp.prettier-vscode", "publisher.some-other-formatter"]
    }
```

I would propose that the current UI where the user selects a default formatter be left the same for simplicity's sake, but allow more advanced users to have the option to run more than one.

**Comment by jrieken** [comment]
Things like organize imports etc integrate via the code actions API and that allows to run multiple, formatter do not support that
