### ISSUE TITLE
Autoformat not working

### ISSUE THREAD

**Issue by miqmago** [Microsoft/vscode#8460]
- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:04:06.083Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
In workspace and user settings:

1. Set `"editor.tabSize": 4`
2. Set `"editor.detectIndentation": false,`
3. Autoformat javascript code (Alt+F)

Will format code with 2 spaces and remove semicolons. It was not happening in last release.

**Comment by dbaeumer** [comment]
I can not reproduce this. Do you have any formatting extension installed.

The formatter usually honors the setting of a file, not the gobal settings. So if the editor detects that a file uses 2 spaces as indent the formatter will format it with two.

**Comment by miqmago** [comment]
Sorry, it was because of this extension https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standard-format (that maybe I was completly blink and out of myself when installed it...)

However I don't understand why before updating, this extension was not interfering and so was after update.
