### ISSUE TITLE
1.40.0 launches with a blank window but function works

### ISSUE THREAD

**Issue by hsupu** [microsoft/vscode#84607]
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic
```

After `apt upgrade` to the latest version, my vscode couldn't render anything in the window, but it reacts normally when my mouse hovers.

I tried "Toggle Developer Tools" and it has no difference.

I tried `code --disable-extensions` and it has no difference.

<img width="367" alt="图片" src="https://user-images.githubusercontent.com/5724214/68691929-8ced5080-05af-11ea-9a71-b7af5c54e688.png">

**Comment by hsupu** [comment]
It seems the tab is here, nothing wrong except UI rendering.

<img width="340" alt="图片" src="https://user-images.githubusercontent.com/5724214/68692113-e2296200-05af-11ea-8675-267a03a1cf50.png">

**Comment by europaisch** [comment]
Try this in the terminal:
`code --disable-gpu`

**Comment by hsupu** [comment]
@europaisch it works. thank you.
FYI, I use vscode in a `Ubuntu 16.04.6 LTS` virtual machine on `Parallels Desktop 14.1.2 for Mac`. The mac version is `macOS Mojave 10.14.6`, and graphic cards are `AMD Radeon R9 M370X 2 GB`
and `Intel Iris Pro 1536 MB`.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by europaisch** [comment]
I have been having this issue many times when using a virtual machine myself, so I can confirm @bpasero's fix does work.

**Comment by hsupu** [comment]
@bpasero Thank you for your reply. After disabled the GPU support, my UI recovered. So is it a bug and will it be fixed in the future?

**Comment by bpasero** [comment]
You can use this as a workaround.
