### ISSUE TITLE
When debugging multiple targets the call stack panel has poor UX 

### ISSUE THREAD

**Issue by TobyEalden** [microsoft/vscode#84601]
When debugging two or more targets, an entry for each target appears in the Call Stack panel which is nice and allows you to easily switch between targets when debugging.

However, when one or more of the debug targets ends such that there is only one target left running, the last remaining target disappears from the Call Stack panel.

It would be great to have an option to always leave the single debug target in the Call Stack panel.

![ScreenRecording2019-11-12at14471](https://user-images.githubusercontent.com/1628365/68682551-36efbd00-055d-11ea-877d-f0394778b3dc.gif)

**Comment by isidorn** [comment]
This is a good point, and i do agree that it is weird.
Currently we are over protective when we show debug sessions.
And yes I prefer the previous solution, where we show multiple sessions as long as we showed multiple sessions once. 

@weinand @joaomoreno let me know what you think

**Comment by weinand** [comment]
As done in other places, we should not clear the view if only one target is left. I think that was the "previous solution" you are referring to.

**Comment by isidorn** [comment]
Agree.

Adding bug, so we get this verified.
To verify: start two debugging sessions, stop one, and make sure the other session is still shown in the call stack view.
