### ISSUE TITLE
Code actions on Save can't be configured correctly

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#84602]
I tried to move ESlint autoFix to the new code actions API but I struggle to support a flexible enable and disablement. What I try to do is the following:

- if `source.fixAll` is set to true provide eslint auto fix options.
- allow users to disable eslint fix all by having a setup like this:

```
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
		"source.fixAll.eslint": false
	}
```

Since I register for `source.fixAll` code actions I still get called even though the eslint specific setting is false. The code actions I returned do have the `source.fixAll.eslint` kind set correctly however are not filter and still applied.

I could interpret the `source.fixAll.eslint` myself to work around this but it fails if the user uses language specific settings. Consider an example like this

```json
	"editor.codeActionsOnSave": {
		"source.fixAll": true
	},
       "[html]: {
		"source.fixAll.eslint": false
       }
```

This should only disables it for html files. But I can't interpret this setting since the extension host API provide no API to read language ID specific settings.

I see a couple of solutions:

- the code action on save core feature post processes provided code actions and filters the once where the kind is set to false. This has the big downside that computing the code action can be quite expensive and is therfore a waste of time on a time critical operation.
- the code action provider gets access to the full `"editor.codeActionsOnSave"` setting so that it can find out if his specific code action kind is enabled or disabled.
- a different interpretation model for `"editor.codeActionsOnSave"`.

**Comment by mjbvz** [comment]
This use case hasn’t been considered before. Do you think it blocks you from adopting source actions? We don’t have many fixAll providers at the moment so I’m not sure how often users will need to selectively disable just eslint

We should support the config you show though. My proposal is:

* your provider should return the most specific type of code action in its metadata. We can then use this to decide if we should call The provider of not

* filter out returned actions on the vscode side

**Comment by dbaeumer** [comment]
> We don’t have many fixAll providers at the moment so I’m not sure how often users will need to selectively disable just eslint

ESLint provides source actions for JS and TS and I was concerned that they might overlap with the TS/JS language server hence. If those don't provide code actions on save I think we could be fine for now.

I alreadz tried tried this but then the source actions are not applied when the config only lists:

```
	"editor.codeActionsOnSave": {
		"source.fixAll": true
	}
```

I need to add this as well:

```
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
		"source.fixAll.eslint": true
	}
```

The source action provide is registered like this:

![capture](https://user-images.githubusercontent.com/1931590/68707844-d2e7eb80-0592-11ea-8a0b-033b42c149de.png)

I found a work around for interpreting the language specific setting using a trick @sandy081 showed me. I will use that for now until we settle on a right way forward.

**Comment by mjbvz** [comment]
JS/TS does not provide fixAll actions so I think we should be good

**Comment by mjbvz** [comment]
I checked in fix to support the `editor.codeActionsOnSave` you suggest.  To verify:

1. Set:

```
 "typescript.experimental.autoFix.enabled": true,
    "editor.codeActionsOnSave": {
        "source.fixAll.ts": true,
        "source.fixAll": false
    }
```

1. Open a TS file:

```ts
interface IFoo {
    a: number
}

class Foo implements IFoo {}
```

1. Save and confirm the fix to implement the interface is applied.
1. Play around with the settings and confirm that you can enable/disable the TS code action using various settings of `true`/`false`/`undefined` for `source.fixAll.ts` and `source.fixAll`

**Comment by dbaeumer** [comment]
I tried to adapt the improved filtering but it resulted in a unhappy user experience. I tried the following:

- compute the code action with a text edit. If `source.fixAll.eslint` is false the save will still have a noticeable delay since computing the eslint fixes is quite expensive (it is actually a n path run due to the nature of eslint). It can easily delay the save for the whole time budget.
- compute a code action with a command and apply the edits when the command is executed. This makes the save fast even if `source.fixAll.eslint` is false but has another wired side effect. The file sometime is dirty after the save. The reason for this is as follows:
- command gets executed
- server computes the fixes
- save hook gets canceled since the time budget is out. The command is not canceled since there is no cancel support. And even if there would be in an async environment it will be hard to implement correctly
- core saves the file and after that applies the edits executed from the server => file is dirty

So the best for now is IMO to keep the workaround in I have which does the following:

- the code action for the save contains a text edit
- I interpret the "editor.codeActionsOnSave" myself for now. If eslint is in any form disabled I don't compute a code action on save.

To make this a nice story I think we should:

- for `source.fixAll` only support code actions with text edits to ensure the file is saved after the user hits save.
- allow to register a code action provider that is called once with all `source.fixAll*` code action kinds it registered for even if the kind is set to false. Then the provider can react appropriately. We could indicate that mode with an additional property on `CodeActionProviderMetadata`.

**Comment by dbaeumer** [comment]
@mjbvz I reopen the issue since IMO the current solution is not a good fix.

**Comment by mjbvz** [comment]
So the main issue is that your provider is still called on save with the example config of:

```json
  "editor.codeActionsOnSave": {
        "source.fixAll.eslint": false,
        "source.fixAll": true
    }
```

I intentionally didn’t address that as the returned actions will be dropped anyways and this is a pretty niche config setup (most users will either enable fix all for everything or just for eslint, not enable it for everything except eslint)

Can you make your provider explicitly state that it returns `source.fixAll.eslint` actions. I should be able to add filtering to prevent the provider from being asked in those cases as well since it is expensive to resolve the actions

**Comment by dbaeumer** [comment]
> So the main issue is that your provider is still called on save with the example config of:

Yes

> Can you make your provider explicitly state that it returns source.fixAll.eslint actions.

I tried this as well but then my provider is not called if the configuration only lists 

```
"editor.codeActionsOnSave": {
        "source.fixAll": true
}
```

which I think is still a valid use case. What I want to support is:

```
"editor.codeActionsOnSave": {
        "source.fixAll": true
}
```

==> ESLint provides code action

```
"editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.fixAll.eslint": false  
}
```

==> ESLint doesn't provide code actions

```
"editor.codeActionsOnSave": {
        "source.fixAll": false,
        "source.fixAll.eslint": true  
}
```

==> ESLint does provide code actions

Plus all these combinations in language specific settings.

**Comment by mjbvz** [comment]
I can't repo the issue with:

```
"editor.codeActionsOnSave": {
        "source.fixAll": true
}
```

TypeScript's [fixAll provider](https://github.com/microsoft/vscode/blob/1f3642a07d8787e014ce6620580866b50cd16585/extensions/typescript-language-features/src/features/fixAll.ts#L39) returns actions with the kind `source.fixAll.ts`. Are you sure there's not some filtering happening in your provider on the language service implementation?

**Comment by dbaeumer** [comment]
I tested it again and it is not auto fix that is not working. Is is the normal code actions that don't work if I only register my code action provider for `source.fixAll.eslint`. Sorry for pointing into the wrong direction. In general this is very confusing for me.  

I am now registering with CodeActionKind.QuickFix and `source.fixAll.eslint` and it seems to work with one strange oddity: I am still called with context.only undefined when normal code actions are requested and with CodeActionKind.QuickFix when called for code actions in hover. I would expect that I always get called with a set `context.only` if I have registered with a metadata. Otherwise I have no clue how to interpret the `undefined` context (to make sure I am not returning wrong code actions I need to interpret the settings myself). 

Or spec that the context.only is only undefined in the code action light bulb case. However I would prefer to always be called with a kind if I have registered for kinds. May be we need another kind `CodeActionKind.LightBulb`

**Comment by mjbvz** [comment]
@dbaeumer Do you have a single code action provider that returns both normal quick fixes and the `fixAll` action? It may be easier if you had separate providers for the two (although [checking `context.only`](https://github.com/microsoft/vscode/blob/1f3642a07d8787e014ce6620580866b50cd16585/extensions/typescript-language-features/src/features/fixAll.ts#L43) should also work)

The second part of by-design:

- Lightbulbs request all code actions (except source actions). This includes both refactorings and refactorings. Don't specify `context.only` because we are telling the provider that we are interested in every type of code action (again, source actions are the one special case here).

- For `quick fix` in problem hovers, we only care about quick fixes so we explicitly request just quick fixes. That's why we set `context.only: CodeActionKind.QuickFix`

**Comment by dbaeumer** [comment]
I do register a single provider. Registering two will not make a difference I guess because I will still be called with undefined for both of them. My biggest problem is to interpret the undefined case. What I want to do is the following:

- in the case of `fixAll` on save I want to compute a code action with text edits to ensure that the save works correctly
- in all other cases I want to compute (especially for fixing all problems) a code action with commands since computing these fixes is expensive and there is no need to let the user wait for it to get a menu populated.

I think this can be done with your explanation:

> Lightbulbs request all code actions (except source actions). This includes quick fixes, refactorings, and whatever custom code actions a provider may supply. We don't specify context.only in this case because we want to indicate to the providers that we are interested in every type of code action (again, source actions are the one special case here).

However I would highly suggest that this is documented somewhere since it was not clear to me that if context.only === undefined that no `source` code actions should be included.

**Comment by mjbvz** [comment]
Yes that should be possible with the current AP. Let me know if you run into any issues. I've also clarified how source actions are used in 3711773

Anything left to do on this issue?

**Comment by dbaeumer** [comment]
Closing the issue.

**Comment by dbaeumer** [comment]
@mjbvz I need to reopen this since I am still called in the following setup:

- code action provider registered for `quickfix`, `source.fixAll.eslint`

<img width="354" alt="capture" src="https://user-images.githubusercontent.com/1931590/70229747-1202fa00-1757-11ea-953d-908122c6bba1.png">

- configuration set to: 

```
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
		"source.fixAll.eslint": false
	}
```

As I pointed out here https://github.com/microsoft/vscode/issues/84602#issuecomment-553324626 computing the code actions on save is quite expensiven and can delay the whole save to the point that other registered providers might not get a change although I didn't compute anything.

IMO the core has all the necessary information to not call me in this setup since `source.fixAll.eslint` is more concrete than `source.fixAll` and my provider is only registered for `source.fixAll.eslint`.

**Comment by mjbvz** [comment]
Pushing to December as this only effects eslint and doesn't break things (just causes some unnecessary work)

**Comment by mjbvz** [comment]
@dbaeumer Can you please test the next insiders build. I believe it should now have the behavior you are after

Let me know if you still notice any issues

**Comment by dbaeumer** [comment]
@mjbvz will do.

**Comment by dbaeumer** [comment]
Works as expected.

**Comment by jvilk-stripe** [comment]
@mjbvz Quick question while you have this context -- does setting

```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": true
}
```

cause VS Code to wait for all code action providers for JavaScript documents as "save participants"?

Even with the Insiders build, I'm seeing heavily degraded auto-formatting performance (ESLint + Prettier taking 1-2 seconds to run) that isn't explained with the wall clock time of those respective tools that I found via their tracing/debug output (~250ms for ESLint, ~50ms for Prettier) but may be explained with slow code actions from the Flow language server (~1.5s sometimes). In LSP traces, I noticed VS Code asks Flow for code actions for ESLint errors, which seems to be a red flag.

**Comment by jvilk-stripe** [comment]
FWIW I'm willing to do some legwork here if the answer is 'no that shouldn't happen', but I'm unfamiliar with what debug output VS Code provides (if any) for sanity checking save participants.

(Maybe I have to build VS Code from source and use a debugger on a dev build? Would be painful without the marketplace to quickly install the extensions, but doable.)
