### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by miekesmith** [microsoft/vscode#84615]
I'm trying to download VSC on my brand new MacBook Pro and I get the error message attached..."Can't be opened because Apple cannot check it for malicious software." 

Please advise.
Mieke
mieke.smith@yahoo.com

<img width="1055" alt="Screen Shot 2019-11-12 at 1 40 12 PM" src="https://user-images.githubusercontent.com/56131055/68699954-0fdfbe00-0552-11ea-8fca-c72c72ecf22c.png">

**Comment by bpasero** [comment]
@miekesmith are you on macOS Catalina?

**Comment by AndyS-vc** [comment]
I saw the exact same issue yesterday, noticed this issue logged and refrained from posting "yeh, me too". 

Tried again today, and although the d/loaded archive was a different size (some ~3 MB larger), precisely the same symptoms as yesterday/reported above.

I am running Catalina (10.15.1), as I suspect the OP is (based on "brand new Macbook Pro", also my situation). Thanks!

**Comment by miekesmith** [comment]
Glad I'm not alone!! After some snarky back and forth, I was finally directed to issue #74782 for the fix. Basically if you have Catalina, you have to go to system preferences/security and privacy/general. Then under "Allow apps downloaded from" you have to select the box to override the security check. Once I did that, I was able to open the app. Clearly VSC needs to fix this!
<img width="663" alt="Screen Shot 2019-11-13 at 1 42 24 PM" src="https://user-images.githubusercontent.com/56131055/68793645-741a8480-061b-11ea-97f6-62410126b70e.png">

**Comment by AndyS-vc** [comment]
Great, glad that works for you!

However, I would observe that I do not seem to get that option; yes, I have admin privs.

<img width="665" alt="Screen Shot 2019-11-13 at 12 04 04 PM" src="https://user-images.githubusercontent.com/57463928/68800109-4bd85900-060e-11ea-88a1-523546e04ff7.png">

**Comment by miekesmith** [comment]
Try downloading VSC again and open it up. When you get the error message, try the steps above again. Im no expert but it might be that VSC is no longer in your cache?

**Comment by AndyS-vc** [comment]
Makes no difference for me; same error and S&P dialog always looks like the one above.

**Comment by AndyS-vc** [comment]
For the benefit of anyone else stuck/searching, resorting to spctl will take care of it.
