### ISSUE TITLE
Support programatically terminating a debug session

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#84612]
I'm trying to run a debug session in a pseudoterminal, and would like to terminate the debug session when the user closes the terminal (by clicking the bin icon). There's a `close()` event on the pseudoterminal, but as far as I can tell there is no API to tell VS Code to send a termination request.

I could add a custom request to the debug adapter, but it feels weird when there are already requests for terminating/disconnecting so it would be nice if extensions can just call them (we can programatically start the session with [debug.startDebugging](https://code.visualstudio.com/api/references/vscode-api#debug.startDebugging).

**Comment by isidorn** [comment]
This is a fair feature request, however it is currently directly not possible.

As a workaround I suggest the following:
* Get the `ActiveSession` using the vscode debug api
* Send the `customRequest` which is a disconnect to the debug adapter

**Comment by DanTup** [comment]
Ah, I didn't realise I could just send requests like `disconnectRequest` through `customRequest`, I'll give that a go - thanks!
