### ISSUE TITLE
Search does not exclude node_modules even after including in Search: Exclude

### ISSUE THREAD

**Issue by Riseley** [microsoft/vscode#84619]
- VSCode Version: 1.40.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Use default VS Code (already has **/node_modules search exclusion on by default)
2. Open any workplace that uses npm or yarn and install and get node_modules
3. Ctrl+Shift+F, then search for anything
4. Search includes node_modules

Does this issue occur when all extensions are disabled?: Yes

![Screenshot from 2019-11-13 04-35-29](https://user-images.githubusercontent.com/8508355/68704447-abfbda80-05cf-11ea-8750-92c1b7fbde2c.png)

**Comment by roblourens** [comment]
Are you sure those are from node_modules? Can you show the full path of those results?

**Comment by Riseley** [comment]
Right, sorry, a stupid mistake from my end, those are from .next not from node_modules.

Closing this issue.
