### ISSUE TITLE
Suggestion: Use different icons for Extension View popular and recommended buttons

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#8461]
- VSCode Version:1.3.0-insiders
- OS Version:Windows 7

The flame icon for popular is confusing with the OmniSharp flame and perhaps offensive ("hot").  The gift icon is difficult to see and understand.

Suggestion: Use a star icon for popular.  This matches the star ratings we show in the extension items.

Suggestion: Use a thumbs up hand image for recommended.  The thumbs up image is very popular on GitHub and easily understood.

**Comment by bgashler1** [comment]
Yes, just saw these and agree these could be improved.  We might want to make this part of #8017

**Comment by gregvanl** [comment]
Can we use octicon-star and octicon-thumbsup?  These are already available in the included octicon css.

**Comment by bgashler1** [comment]
I emailed the icon team a request for new icons for this.  Will update this issue when I hear back.

**Comment by stevencl** [comment]
We have an icon for View - clicking on this we show a list of actions - show popular, show recommended, show installed, show updates.
Clicking these actions will populate the textbox with the appropriate command to perform the search.
Brad will get assets from the VS icon team to deliver to Isidor.

**Comment by bgashler1** [comment]
Since all these commands are essentially filtering the list of all extensions, the icon team and I felt that a "Filter" icon would be appropriate.

I've attached the asset here.
[Filter_16x.zip](https://github.com/Microsoft/vscode/files/339931/Filter_16x.zip)


![screen-shot-2016-06-29-at-10 59 43-am](https://cloud.githubusercontent.com/assets/11839736/16463667/a87949e2-3deb-11e6-9aea-f609b1b5540c.png)

**Comment by gregvanl** [comment]
Given that some of the actions are filtering (@popular, @recommended) and some are local (installed, installed and outdated), I think a filter icon is confusing.  I'd prefer "..." which is clear to mean a dropdown will appear.

**Comment by bgashler1** [comment]
@gregvanl They're actually still filtered from all available extensions.  If you were to scroll to each point in the entire list of extensions where you have installed an extension, you will see the same stuff.

**Comment by isidorn** [comment]
After getting negative feedback for the filter icon we have chosen to go with the elipses. Our concern with the elipses is that it goes against our design principle if it is the only action. So we also moved the clear action top level to also address #8386.
We felt this solution is a nice compromise between various suggestions.

![screen shot 2016-07-01 at 12 23 08](https://cloud.githubusercontent.com/assets/1926584/16519038/a0da29c6-3f86-11e6-9cf2-9ffb7ee70745.png)

**Comment by bpasero** [comment]
@isidorn make sure to fix the bad outline you now get that you removed the search attribute from input.
