### ISSUE TITLE
Offer option not to syntax-highlight JSDoc's @example snippet in IntelliSense

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode#84614]
Current implementation:

JSDoc's [@example](https://jsdoc.app/tags-example.html) snippet is treated as code (added by [this commit](https://github.com/microsoft/vscode/commit/24423dd529ef5a08ba00bb9528fd05281835a6b9)), which means, among other things, that
- in comment blocks, code snippets under @example will be syntax-highlighted, and
- in Intellisense popover (quick suggestion? not sure what the name is) the code gets monspace code font and is syntax-highlighted.

Feature I'd like:

I'd like to have an option to disable these code snippets' syntax highlighting (but do keep the monospace font), because the snippets themselves are in comment blocks, and therefore if they get syntax-highlighted like actual code, they will unnecessarily distract me from reading actual code.

**Comment by mjbvz** [comment]
Are you talking about code in the editor? Or in IntelliSense (such as hover or suggestions)?

/needsMoreInfo

**Comment by Leedehai** [comment]
@mjbvz I'm talking about both :)

**Comment by mjbvz** [comment]
It's not enabled in the editor as of 1.40 (instead you can install an extension for this)
 
Waiting for more feedback on disabling highlighting in hover

**Comment by Leedehai** [comment]
Thanks. Can confirm the highlight in the editor is disabled on 1.40.0 (my old version was 1.39.2).
As for the IntelliSense hover, I wish to disable highlighting there as well.

**Comment by mjbvz** [comment]
Can I ask why? Is there a bug where it causes problem? Or just too colorful?

**Comment by Leedehai** [comment]
@mjbvz it's just too colorful kind of distracting

**Comment by Leedehai** [comment]
I even don't know how to upvote this issue myself. Do you mean this?
<img width="296" alt="Screen Shot 2020-01-15 at 21 50 21" src="https://user-images.githubusercontent.com/18319900/72489169-3f74a600-37e1-11ea-837b-9fd978718918.png"> It feels we can improve the [documentation mentioned above](https://github.com/microsoft/vscode/wiki/Issues-Triaging#our-triaging-flow).

**Comment by mjbvz** [comment]
I'm closing this as realistically we have no plans to address this. Backlog candidate gives false hope
