### ISSUE TITLE
A way to filter Themes and Icons from the Enabled extensions List

### ISSUE THREAD

**Issue by altimmons** [microsoft/vscode#84613]
I like themes, I install a lot to try them out.

I try lots of extensions in fact, so much so that my VSCode buckles under the weight of having scores of plugins for Python, Java, JS, HTML, Microcontrollers, and whatever else I am experimenting with at the moment.

I have a hard time controlling the right plugins being active at the right time.  It would be great if I could hide all the themes and icons and other 'passive' extensions so that I can better see what is currently enabled.  Themes sort of fall into a different class then extensions anyway.

In this category, I might include Keymaps, and maybe some templates and such.

**Comment by altimmons** [comment]
A simple solution, thats practically already there. would be to allow inverted syntax in the search:
     
          @enabled -@category:themes  

`@category:!themes`, or `!@category:themes` or `-@category:!themes` or not etc...

**Comment by CallumCarmicheal** [comment]
This has been a huge issue of mine for awhile, I happen to switch themes on a daily / weekly to biweekly frequency to help keep the feeling of a "fresh" look in VSC. This leaves me a lot of extensions installed which are just themes. 

I also happen to work in many different languages for different projects such as PHP, C#, C++, Java and Python. This has the side effect of having to have the language extensions installed for all of these languages, to stop any issues of having a million different group panes open I disable all extensions which do not affect my target language and this is a difficult task if i have to keep scrolling past various theme extensions.

+1.
