### ISSUE TITLE
Newlines written to Pseudoterminal do not move cursor back to column 0

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#84611]
If you send newlines to a pseudoterminal like this:

```js
const pseudoterminal = {
	close: () => { console.log("Closed!"); },
	onDidWrite: this.emitter.event,
	open: () => this.emitter.fire("Hello!\nHello2!\nHello3!"),
};
```

The output doesn't move back to column 0 after each newline, so it looks like this:

![Screenshot 2019-11-12 at 5 49 01 pm](https://user-images.githubusercontent.com/1078012/68696361-bb016f00-0574-11ea-9649-559645a20922.png)

**Comment by Tyriar** [comment]
As designed, you need to use a carriage return to return the cursor to 0 `\n\r`. Tweaks docs to call this out explicitly.

**Comment by DanTup** [comment]
Is it safe to assume that additional `\r`'s will never cause any ill-effects? This data is coming from the output of another process, so massaging it beyond just doing a simple replace of `\r` with `\r\n` is complicated (since the data is chunked and knowing what the next character is in advance would mean buffering it).

I test it with multiple `\r`'s both before and after `\n` and it didn't do anything bad (which is what you'd expect if `\r` does nothing but move back to col 0) but if something like `\r\n\r` started moving down more than one line, things would appear incorrectly.

**Comment by Tyriar** [comment]
All \r ever does I believe is move the cursor to the start of the line, writing it twice should be fine

**Comment by mjbvz** [comment]
Verified documentation change
