### ISSUE TITLE
Find in editor controls not keyboard accessible

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#84629]
Issue Type: <b>Bug</b>

Happening only on insiders for me.

1. Cmd F in file to bring up find control
2. Press tab repeatedly

Focus gets stuck on the match case option, I'm not able to focus next or previous elements

VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:36:54.895Z)
OS version: Darwin x64 18.7.0

**Comment by rebornix** [comment]
Probably provide a screen recoding? I didn't reproduce this.

**Comment by RMacfarlane** [comment]
Sorry, I forgot to try disabling extensions - this seems to be caused by the Vim extension
