### ISSUE TITLE
Inconsistent UI Languages

### ISSUE THREAD

**Issue by E-train-Liu** [microsoft/vscode#84625]
- VSCode Version: 1.39.2
- OS Version: Windows 10 Family 18362.418
    - Default Language: zh-CN
    - The display language have been set to en-US

No language extension for Chinese have been installed in my VSCode. The text in some menus, however, is mixed with English and Chinese.
 
![image](https://user-images.githubusercontent.com/38714576/68712497-c31cd700-0593-11ea-87d5-625495dc663f.png)

![image](https://user-images.githubusercontent.com/38714576/68712924-9f0dc580-0594-11ea-8086-4ae1e80b0404.png)

The problem disappeared when switch the Title Bar style to "custom".

![image](https://user-images.githubusercontent.com/38714576/68713084-f875f480-0594-11ea-98b8-b3a4e32bc84d.png)

The error information reported by C/C++ extension is also mixed with Chinese and there seems to be no way to config it. 

![image](https://user-images.githubusercontent.com/38714576/68713224-45f26180-0595-11ea-8b12-3895d3ff30f8.png)

Does this issue occur when all extensions are disabled?: No

**Comment by alengYuan** [comment]
Hi, dude! In fact I didn't encounter this problem with my editor, I have tried to reproduce your bug by coding with JS and Rust, but it works normally.
Maybe you should update your editor or **reinstall** it, and then try again.

**Comment by sbatten** [comment]
@E-train-Liu I could also not reproduce this. Any additional info would be helpful.

**Comment by E-train-Liu** [comment]
I think I maybe have found where this problem comes from. It can be reproduced on Windows 10 Family Chinese Edition.

**Comment by alengYuan** [comment]
> 
> 
> I think I maybe have found where this problem comes from. It can be reproduced on Windows 10 Family Chinese Edition.

Well... I think that is not the key of this bug, my Windows has the same version with yours.

Whether you once installed "Chinese (Simplified) Language Pack for Visual Studio Code"? If so, may be something of this extension has been left over.
