### ISSUE TITLE
unable to show "Source Control Providers" with a single repo workspace

### ISSUE THREAD

**Issue by pytheous** [microsoft/vscode#84627]
From the source control section:
right click SOURCE CONTROL.

if you have multiple source control providers you can select 'Source Control Privders' and you can view all your providers and their status
![image](https://user-images.githubusercontent.com/57333962/68716012-20933280-0558-11ea-89e4-c509795935ab.png)

if you only have a single provider you cannot view this any more.
![image](https://user-images.githubusercontent.com/57333962/68716025-26891380-0558-11ea-8118-0d80e4d59868.png)

can we have this option back for single source control projects.

**Comment by gjsjohnmurray** [comment]
Try adding this setting:
```
"scm.alwaysShowProviders": true
```
