### ISSUE TITLE
Lua Regions/Collapsing of String Literals

### ISSUE THREAD

**Issue by giaffodesigns** [microsoft/vscode#84621]
Issue Type: <b>Feature Request</b>

I am working in Lua in VSCode. The editor is able to properly identify string literals for color coding. However, the collapsing function works by indentation rather than by reading the start and end of the brackets. I am forced to embed strings upward of 20k lines in many of my files, which I cannot alter indentation to, so I was hoping being able to collapse by interpreting brackets may be an option. Alternatively, marking regions as I would in C# in Visual Studio would work just as well, maybe better.

Thanks for your time and efforts!

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
Language aware folding regions need to come from a language extension as this requires a Lua scanner/parser
Can you file the issue against the Lua extensions of your choice?
