### ISSUE TITLE
Python interactive over scrolls

### ISSUE THREAD

**Issue by yumeng426** [microsoft/vscode#84623]
Recently, my visual studio code behaves weirdly. 

every time I hit shift+enter to execute the line, the result is covered and the new input line is at the top. There is huge area left below and the scroll bar is only at the center. I can keep scrolling down. 

Anther thing is that when the intellisense window pops up as I type, it is no long at the normal position. As you can see in the pic, it is offset above. 

Can anyone suggest me what to do to make it back to normal. I have tried deleting code folder to reset visual studio code and remove and clean install python. Neither of them resolved. Thank you.

![interactive](https://user-images.githubusercontent.com/11802847/68709561-e9c31980-0563-11ea-8c0d-601573a72bed.JPG)
![scroll](https://user-images.githubusercontent.com/11802847/68709562-e9c31980-0563-11ea-9d3e-e73651b13a32.JPG)

**Comment by rebornix** [comment]
Please file the issue against the Python extension which provides this feature.
