### ISSUE TITLE
Проблема с работой в react-app

### ISSUE THREAD

**Issue by Velmoren** [microsoft/vscode#84639]
Issue Type: <b>Bug</b>

Доброй ночи. Столкнулся с такой проблемой: при работе с react приложением, а именно при добавлении react-router-dom я меняю стандартные ссылки <a> на <NavLink> и ожидаю, что стандартно активным ссылкам будет назначаться класс active. Но ксласс не добавляется. Если запустить react приложение из обычной консоли (из любой другой, не относящейся к VS) все отлично работает, но если запускаю из любой консоли внутри VS - активные классы не добавляются.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.46GB free)|
|Process Argv|C:\Users\BLUE-PC\Desktop\IT-kamasutra|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
All-Autocomplete|Ati|0.0.20
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
vsc-material-theme|Equ|30.0.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
vscode-github|Kni|0.30.3
vscode-autoprefixer|mrm|2.2.0
vscode-language-pack-ru|MS-|1.40.2
sublime-keybindings|ms-|4.0.3
color-highlight|nau|2.3.0
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.9.5
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by EvgeniyMakhmudov** [comment]
Пишите пожалуйста ваши issue на English языке, что бы разработчики могли лучше Вас понимать.

**Comment by Velmoren** [comment]
Проблема найдена, это происходит только при запуске приложения react из git bash консоли в VS code, в остальных все отлично отрабатывает

**Comment by Velmoren** [comment]
уже не актуально, спасибо
