### ISSUE TITLE
After focusing on any input box in sidebar, default shortcut "Ctrl+Shift+E" does not work

### ISSUE THREAD

**Issue by OneQuid** [microsoft/vscode#84633]
- VSCode Version: 1.40.0
- OS Version: Linux Mint 19.2 Tina/Cinnamon

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T18:14:08.920Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-66-generic
```
I'm afraid it was there at latest since 1.36.0
1.36 to 1.40 on Linux Mint 19.2

Steps to Reproduce:

1. Press "Ctrl+Shift+F"
2. Press "Ctrl+Shift+E"

Other shortcuts of sidebar views would work
And one more situation here :

Steps to Reproduce:

1. Click any tab of opened files in editor view
2. Press "Ctrl+Shift+E"

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirmationPending unable to reproduce it in 1.40 on Windows.

In Keyboard Shortcuts what do you find when you search for that key combo? My result:
![image](https://user-images.githubusercontent.com/6726799/68728332-ef018200-05be-11ea-891f-673b77a9638a.png)

**Comment by OneQuid** [comment]
@gjsjohnmurray exactly the same as your screenshot 
By pressing "Ctrl+Shift+F", focusing on the input box of the "Search" and the "Debug" views of sidebar might be a more accurate description. 

It is weird that other shortcuts for sidebar still work

**Comment by diegoquintanav** [comment]
I'm on mint and I'm having the same issue. Pressing `ctrl + shift + e` types in a letter `e`.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 19.2 Tina
Release:        19.2
Codename:       tina
```

```
$ code --version
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64
```

**Comment by OneQuid** [comment]
@diegoquintanav 
In the case mentioned above, it would not input an `e`. 
What you met might be related to [this comment of #48480](https://github.com/microsoft/vscode/issues/48480#issuecomment-414464079)
I am a bit confused if it is just me having this issue. 
Could you do me a favor to try to reproduce this issue by pressing `Ctrl+Shift+F` and then `Ctrl+Shift+E`?

**Comment by isidorn** [comment]
@joaomoreno Can you repro on Linux? It might be the tree is eating up the E keybinding as it did many times before?

**Comment by OneQuid** [comment]
Thank you very much for your replies so far.
I tried to reproduce this on live image of VM Linux and another gnome distro, but I cannot.

I also found that this happened on some other applications, it is related to the distro or the DE, not vscode. I will check if linux mint or cinnamon did anything with this shortcut.

Thanks again and appologize for the mistake

**Comment by evenfrost** [comment]
For possible solution see my #84464 (comment).

**Comment by evenfrost** [comment]
For possible solution see https://github.com/microsoft/vscode/issues/84464#issuecomment-559415030.
