### ISSUE TITLE
"..." button spins when publishing a new branch in the Git side bar

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#84632]
- VSCode Version: 1.40.0
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a workspace with multiple Git repos (such as a repo with a submodule).
2. Make sure the side bar is narrow enough that the 🔁 doesn't show up.
3. Create a new branch, make some edits, and commit the changes to one repo.
4. Click the "..." to publish changes.

The "...' spins around. Looks weird! I did not expect the 🔁 to disappear even for a narrow side bar.

I was expecting 🔁 to spin around, not the "..."!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you share a screen recording?

**Comment by craxal** [comment]
I was afraid you'd ask. 😅

![SpinningEllipsis](https://user-images.githubusercontent.com/3473026/68983849-dc0acf80-07c1-11ea-9f50-d66b16d2fcbb.gif)

**Comment by misolori** [comment]
I set a min-width on the containers so that the sync icon is always visible:

![gif](https://user-images.githubusercontent.com/35271042/69170888-b9253780-0aaf-11ea-9647-2f75dcc81627.gif)
