### ISSUE TITLE
VSC will not download

### ISSUE THREAD

**Issue by miekesmith** [microsoft/vscode#84634]
Why won't VSC download to my brand new, fully updated MacBook Pro? When I try to open it after install, error message is Visual Studio Code can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information." ?????

**Comment by ZachBucek** [comment]
Seems like all of these threads lead back to the same dead-end with duplicate issue threads being closed. Has this bug been resolved? I have tried updating the latest version of VSC, but no luck.

**Comment by gjsjohnmurray** [comment]
#74782
