### ISSUE TITLE
Source control is not detecting SVN repository since update to 1.41.0

### ISSUE THREAD

**Issue by Roshkj** [microsoft/vscode#84630]
Issue Type: <b>Bug</b>

I can see the changes when open in normal visula studio code. This folder has svn information, that is not able to be detected in Source Control. When opening this folder, I am getting a message saying "No Source control providers registered". But when opening the message in vscode 40, i can see the correct file that is linked

VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:39:58.193Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
blamer-vs|bea|0.5.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.32.0
vscode-pandoc|Dou|0.0.8
vscode-svn|eli|0.1.0
LogFileHighlighter|emi|2.6.0
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.3.3
file-icons|fil|1.0.19
gc-excelviewer|Gra|2.1.32
path-autocomplete|ion|1.13.3
latex-workshop|Jam|8.3.1
vscode-edit-csv|jan|0.2.3
plantuml|jeb|2.13.2
svn-scm|joh|2.0.2
vscode-cdecl|kae|1.0.0
hex-fmt|ker|1.0.0
auto-comment-blocks|kev|1.0.1
rainbow-csv|mec|1.3.1
cpplint|min|0.1.3
remote-wsl|ms-|0.40.2
cpptools|ms-|0.26.1
markdown-preview-enhanced|shd|0.5.0
rewrap|stk|1.9.1
code-spell-checker|str|1.7.20
linenote|tkr|1.2.1
remove-empty-lines|use|0.0.6
vscode-icons|vsc|9.5.0
markdown-pdf|yza|1.4.1
markdown-all-in-one|yzh|2.5.1

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
It looks like an issue with the SVN extension you are using, please file issue against them.

**Comment by Roshkj** [comment]
Thank you for your response, though. But I can use the same version extension with the vscode (release build). But what does it has to do with the source control? And also I can use it with the vs code using the same extension.

The change monitoring was working in V1.40 of insiders. So you still think it is caused by extension?

**Comment by Roshkj** [comment]
I understand. SVN is supported by extension, but the GIT is supported natively. Thank you once again. I also understand this will, then be caused by extension. Once again, thank you!
