### ISSUE TITLE
Paste long command line into PowerShell terminal 

### ISSUE THREAD

**Issue by roxxette** [microsoft/vscode#84644]
Issue Type: <b>Bug</b>

Paste long command line into PowerShell terminal.

If the terminal width couldn't hold the whole line, the command will be cut to 2 broken commands.

![1](https://user-images.githubusercontent.com/2785724/68724939-dcf00580-05f7-11ea-9b60-334acf00e803.png)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A12-8830B R7, 10 COMPUTE CORES 4C+6G    (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.41GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|27%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
githistory|don|0.4.6
xml|Dot|2.5.0
vscode-pull-request-github|Git|0.13.0
vscode-aks-tools|ms-|0.0.1
vscode-kubernetes-tools|ms-|1.0.6
python|ms-|2019.10.44104
remote-wsl|ms-|0.40.2
azure-account|ms-|0.8.7
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
azurerm-vscode-tools|msa|0.8.2
azure-hdinsight|msh|1.1.7
java|red|0.52.0
vscode-yaml|red|0.5.3
vscode-java-debug|vsc|0.23.0

</details>

**Comment by NizamLZ** [comment]
Unable to reproduce. Works as expected. 

Does this occur repeatedly?

![long-cmnd-v2](https://user-images.githubusercontent.com/9017268/68768679-01280280-0649-11ea-9cd4-3c8d62eda3dc.gif)

**Comment by Tyriar** [comment]
/duplicate https://github.com/PowerShell/vscode-powershell/issues/702
