### ISSUE TITLE
Web: support all built in extensions in hosted version

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#84647]
Using the info from #84485 I launched the web test playground in Chrome and looked for the built-in extensions:

![image](https://user-images.githubusercontent.com/6726799/68729523-1dcd2780-05c2-11ea-9e1e-4d9f12e00d25.png)

This probably explains why most of the in-mem files get treated as Plain Text.

**Comment by gjsjohnmurray** [comment]
It can't find Marketplace extensions either. Maybe related?

**Comment by echarles** [comment]
Same issue and question here.

- Updating the `product.json` allows the desktop vscode (launched via `./scripts/code.sh`) to find extensions.
- The same env with same `product.json` launched with `yarn web` does not allow the WEB version to find extensions.

**Comment by sandy081** [comment]
Web hosted version does not have any ui or workspace extensions and we do not yet support managing web extensions.

**Comment by bpasero** [comment]
@gjsjohnmurray yeah, use `yarn web` out of sources to get all built in extensions

**Comment by echarles** [comment]
@bpasero @sandy081 Thx for helping. I am still a bit confused...

As written in my previous comment, `yarn web` does not support extension, while `./dev/script.sh` supports them. Is this the expected behaviour for now? Before closing this issue, it would be good to have confirmation on this. If it is not supported today, the next question would be "is there a plan to support it?"

**Comment by bpasero** [comment]
Yeah currently no plans to support more built in extensions, but I am open to reopen this to signal the intent.

**Comment by echarles** [comment]
PS: I have read too fast and thought initial @gjsjohnmurray issue report was related to a local dev env, but is was related to the new [hosted version](https://vscode-web-test-playground.azurewebsites.net) - I have opened #84894 to further discuss my issue related to extension support with local dev env `yarn web`. Sorry for the confusion...

**Comment by sandy081** [comment]
Closing this in favor of https://github.com/microsoft/vscode/issues/84901
