### ISSUE TITLE
“Visual Studio Code” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by BennyLouie** [microsoft/vscode#84649]
- VSCode Version: 1.40
- OS Version:

Steps to Reproduce:

1. Install VS Code
2. 

Does this issue occur when all extensions are disabled?: Yes/No

Issue: This software needs to be updated. Contact the developer for more information.

**Comment by giunit** [comment]
Was this issue fixed? Currently having the same issue.

**Comment by acobbjones** [comment]
+1 
I am, as well.

**Comment by gjsjohnmurray** [comment]
#74782 is on the iteration plan for 1.41, which is expected to be released next week.
