### ISSUE TITLE
Finger imitation

### ISSUE THREAD

**Issue by Plavozont** [microsoft/vscode#84646]
Issue Type: <b>Feature Request</b>

Please make it possible to scroll editor with mouse just like finger. For example I need to hold ctrl or alt key, then the mouse pointer turns to a hand and I can move my code around. It is not comfortable to use scroll bar most the time

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by BieleckiLtd** [comment]
I think #137056 is about the same nature. Please upvote to show your support.
