### ISSUE TITLE
Integrated terminal: Title bar should pass focus to text area

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8464]
When testing #8222 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:04:06.083Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. When terminal is shown, click on its title bar 'TERMINAL'.
2. -> The focus is not passed to the terminal's text area, which seems like to only possible intent of the click.

**Comment by Tyriar** [comment]
Consistent with the rest of the panels, currently all of them are non-interactive. The debug output in particular is very similar.
