### ISSUE TITLE
Backquote position is incorrect with Ricty Diminished font

### ISSUE THREAD

**Issue by coponhub** [microsoft/vscode#84648]
The backquote display position is incorrect like below 

![image](https://user-images.githubusercontent.com/7829325/68730155-3fa0cb80-060f-11ea-9427-2326f1a94555.png)

It occur in Ricty based fonts.

- VSCode Version: 1.40.0
- OS Version: Windows 10

Steps to Reproduce:

1. Change Font to Ricty Diminished
2. Show Text Using backquote such as \`some_text\`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@coponhub Please contact the font developer, I believe this to be a problem with the font.

**Comment by coponhub** [comment]
@coponhub Thank you for response.

**Comment by coponhub** [comment]
This problem not happened in emacs.
I think Ricty font users ware enough to many notice this problem If this problem ware continue to occur in long time.
I want to know scope and why occur this problem.

**Comment by alexandrudima** [comment]
@coponhub VSCode is built with Electron, which is built with Chromium. Chrome is also built with Chromium. I think this is an issue with the font or with the font rendering of Chromium. Can you please open https://jsfiddle.net/yhd06wm2/1/ in Chrome and Firefox, and compare the rendering.
