### ISSUE TITLE
Add way to force expand a compressed directory in the explorer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84659]
Issue Type: <b>Bug</b>

For #41627

**Repo**
Open a workspace with the structure:

```
src/
  sub/
    code.ts
```

Using compressed folders, this should display as:

```
src/sub
   code.ts
```

in the explorer

**Bug**
I could not find how to create a new file under just the `src` directory. The new file command always creates it under `src/sub`.

I proposed we add a way to force expand a compressed folder in the explorer (maybe this already exists but I couldn't discover it)

VS Code version: Code - Insiders 1.41.0-insider (0d728c31ebdf03869d2687d9be0b017667c9ff37, 2019-11-12T05:36:54.895Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_8009635|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by joaomoreno** [comment]
We're going with something else instead, having demoed in UX call yesterday: https://github.com/microsoft/vscode/issues/84597 Each folder label in a compressed label will be actionable.
