### ISSUE TITLE
cannot install extensions

### ISSUE THREAD

**Issue by amryounis** [microsoft/vscode#84657]
We have written the needed data int
Issue Type: <b>Bug</b>

click on any extension

The details pane (right window) shows only the headline description but the details do not show, only this line: No README available.

if you press install you get a notification: failed to installed "ms-python.python" as an example,

and asks to install manually

-----------------------------------------

I had earlier version of VS Code before and was running perfectly, was removed for clearing hard disk.

I deleted .vscode to see if resolves the issue with no luck
uninstalled, reinstalled with no luck

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (11.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>Extensions: none
o your clipboard because it was too large to send. Please paste.

**Comment by a-eid** [comment]
having the same issue, I'm unable to connect to marketplace, extensions are not loading readmes or able to update ..  

```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by sandy081** [comment]
Looks  DNS issue. #78783 #78872
Can you try to access this image? 

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

**Comment by sandy081** [comment]
It's been more than a year that requested for additional info. Hence closing this. Please check with latest release and if it is not working yet, reopen it with requested info.
