### ISSUE TITLE
Uri.with: Cannot remove authority

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8465]
Testing #8192 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:04:06.083Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. I can add an authority: vscode.Uri.parse("scheme:/path").with({ authority: "authority" }).toString()
=> "scheme://authority/path"
2. But I cannot remove it: vscode.Uri.parse("scheme:/path").with({ authority: "authority" }).with({ authority: "" }).toString()
=> "scheme://authority/path"

**Comment by chrmarti** [comment]
Same with the other parts: scheme, path, query and fragment.

**Comment by jrieken** [comment]
We consider the empty string as `null`/`undefined`

**Comment by jrieken** [comment]
Now `null` or the empty string unset an URI component
