### ISSUE TITLE
Cannot rename compressed folders in explorer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84658]
Issue Type: <b>Bug</b>

**Repo**
1. Create a project with two directories and the structure:

```
src/
   sub/
```

2. In explorer, see the directory is compressed and displayed as `src/sub`
3. Trigger a rename in the explorer on `src/sub`

**Bug**
The entire explorer becomes greyed out. No rename happens:

<img width="257" alt="Screen Shot 2019-11-12 at 10 27 34 PM" src="https://user-images.githubusercontent.com/12821956/68738739-f2cfdd00-059b-11ea-97cb-5f643212f766.png">

VS Code version: Code - OSS Dev 1.41.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by mjbvz** [comment]
One interesting option would to let users enter a new folder path in the rename dialog. For example, while renaming `src/sub` the dialog would show `src/sub`. If I enter `code/cat/bla`, it would create a new directory structure:

```
code/
  cat/
    bla/
       ...files previously under `src/sub`
```

**Comment by NizamLZ** [comment]
I would like to work on this issue.
