### ISSUE TITLE
从后台再次打开vscode会出现界面空白异常

### ISSUE THREAD

**Issue by Hxy1992** [microsoft/vscode#84656]
系统：win7
重现步骤：
①正常打开vscode使用；
②在任务栏点击vscode图标将其隐藏
③再次点击vscode图标将其打开显示，会出现卡顿（空白界面）若干秒。

CPUs | Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: unavailable_offskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.96GB (8.81GB free)
Screen Reader | no
-- | --
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vscode-markdownlint | Dav | 0.32.0
beautify | Hoo | 1.5.0
smarty | imp | 0.3.0
vscode-language-pack-zh-hans | MS- | 1.40.2
mssql | ms- | 1.7.0
python | ms- | 2019.10.44104
debugger-for-chrome | msj | 4.12.1
vetur | oct | 0.22.6
vuehelper | oys | 0.1.0
markdown-all-in-one | yzh | 2.5.1

**Comment by Meyond** [comment]
这是Electron出现的问题[https://github.com/electron/electron/issues/12854](url)估计要等他们修复

**Comment by Hxy1992** [comment]
@Meyond 还以为中文没人回复的嘞，O(∩_∩)O哈哈~

**Comment by Meyond** [comment]
> @Meyond 还以为中文没人回复的嘞，O(∩_∩)O哈哈~

我是闲的没事，正常情况你提的这个issue的确很少有人回复

**Comment by rebornix** [comment]
As mentioned above, it's the same as https://github.com/electron/electron/issues/12854

**Comment by rebornix** [comment]
It's saying when the window is brought to front from background, it's blank. Seems there is already an Electron bug reported.

**Comment by deepak1556** [comment]
That electron bug is specific to transparent windows, @rebornix can you ask for exact repro steps ? A video demo would also help. There are couple of issues with frameless window , need to make sure its not duplicate.

**Comment by Hxy1992** [comment]
![ezgif-1-819f5afb5050](https://user-images.githubusercontent.com/14800641/68824721-c8347000-06d2-11ea-8417-e37fe811b7ac.gif)
