### ISSUE TITLE
revert to 1.9.2

### ISSUE THREAD

**Issue by RudyBenner** [microsoft/vscode#84650]
Issue Type: <b>Bug</b>

1.4.0 is buggy. Have turned off updates.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  J2900  @ 2.41GHz (4 x 2417)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.32.0
githistory|don|0.4.6
gitlens|eam|10.1.2
git-project-manager|fel|1.7.1
cpptools|ms-|0.26.1
platformio-ide|pla|1.9.3

</details>

**Comment by yordis** [comment]
- `CMD+F` does not highlight the search bar
- Git does not work unless you open the project from the Git root
- The prettier plugin is broken

**Comment by mjbvz** [comment]
/needsMoreInfo

@yordis Please open separate issues
