### ISSUE TITLE
Can't Handle Mixed Display Resolutions Well (Windows 10)

### ISSUE THREAD

**Issue by 51ngul4r1ty** [microsoft/vscode#84653]
Issue Type: <b>Bug</b>

I have a 4K (3840x2160) Dell XPS 15 laptop with an external 2560x1080 monitor and I was unable to resize VS Code on the external monitor.  The vertical height of VS Code also exceeded the height of the monitor so it makes it impossible to use on this monitor unless I maximize it to the full screen size.  This only started happening after upgrading to the latest VS Code.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (16.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|10.5.0
ts-loader-problem-matcher|alq|0.3.0
snapshot-tools|asv|0.4.0
markdown-emoji|bie|0.0.9
markdown-footnotes|bie|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
markdown-table-prettify|dar|2.4.0
vscode-eslint|dba|1.9.1
githistory|don|0.4.6
gitlens|eam|10.1.2
toggle-excluded-files|eam|1.7.0
graphviz-preview|EFa|1.3.3
tslint|eg2|1.0.44
prettier-vscode|esb|3.3.5
graphviz-markdown-preview|gee|0.0.8
mdmath|goe|2.4.0
todo-tree|Gru|0.0.162
triggertaskonsave|Gru|0.2.11
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
vue|jcb|0.1.5
plantuml|jeb|2.13.2
nbpreviewer|jit|1.2.2
docthis|joe|0.7.1
codeshell|Kip|0.2.2
markdown-converter|man|3.0.2
vscode-docker|ms-|0.8.2
remote-wsl|ms-|0.40.2
powershell|ms-|2019.11.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1123
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
okazukiplantuml|oka|0.2.2
vscode-versionlens|pfl|0.24.0
node-tdd|pra|0.2.4
vscode-coverage-gutters|rya|2.4.2
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
jenkinsfile-support|sec|0.1.0
ayu|tea|0.18.0
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|2.0.0
vscode-icons|vsc|9.5.0
gitblame|wad|3.0.1
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2

(3 theme extensions excluded)

</details>

**Comment by 51ngul4r1ty** [comment]
^^^ not sure that this is the same issue, but I'll be happy if the resolution for that defect fixes the problem I'm encountering

**Comment by 51ngul4r1ty** [comment]
Actually, I'm sure it isn't the same issue because I was able to get it "working" by decreasing my 4K display to half the resolution and that fixed the problem on the external monitor (they ended up with the same vertical resolutions of 1080px).  So, this seems to be a different issue.  I really don't want to downscale my 4K monitor just to get both monitors working with VS Code so please fix this issue.

**Comment by sbatten** [comment]
@51ngul4r1ty it is the same issue. setting the 4k monitor down a resolution is a valid "workaround" but not what we expect. Today, we shipped a recovery build which should allow you to fit the window on your external monitor. The scaling issue is still present which we are also tracking to fix soon.
