### ISSUE TITLE
path name in VS Code terminal was capitalized

### ISSUE THREAD

**Issue by m3mobile-jyj** [microsoft/vscode#84660]
I don't know to reproduce this case,
however, it is clear to capitalize specific path in new opened terminal.
As below, real path is not "Source" but "source".
This was caused many case warnings.

![image](https://user-images.githubusercontent.com/47553130/68740981-d3828f80-062f-11ea-8229-4f84841ba1b1.png)

**Comment by IllusionMH** [comment]
/question
Could you specify how it is related to VSCode? If you run same command in cmd do you see same error?

This is output from build tool (most likely Webpack) that warns about possible wrong case in import path. See https://stackoverflow.com/questions/47534267/webpack-there-are-multiple-modules-with-names-that-only-differ-in-casing-but
