### ISSUE TITLE
Uri.toString() encodes '=' in query

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8466]
Testing #8192 

- VSCode Version: Code - Insiders 1.3.0-insider (d0c2b891903d73e83dcdc7786398ebfa764fc4ee, 2016-06-28T05:04:06.083Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. vscode.Uri.parse("scheme://authority/path/?param=value#fragment").toString()
=> "scheme://authority/path/?param%3Dvalue#fragment"
2. The percent encoding of '=' is unexpected.

**Comment by chrmarti** [comment]
Also with .toString(false)

**Comment by jrieken** [comment]
June to clarify. Petty sure only honour `=` in the `query` part of `http` uri not others cos only http defines this 'grammar' on the query part

**Comment by jrieken** [comment]
> Also with .toString(false)

I don't believe that cos there is [test](https://github.com/Microsoft/vscode/blob/master/src/vs/base/test/common/uri.test.ts#L327) for it ;-)


Encoding the query in `toString` is a little unhappy esp for html. Tho from the URI spec it's (at least not to me) not obvious that `=` has a special meaning. Therefore no further action planned.

**Comment by chrmarti** [comment]
It will be unexpected to see `=` encoded if it passed through Uri before being passed on somewhere external as string. (Not arguing with the spec.)

**Comment by jrieken** [comment]
I agree and that's one of the reasons I have added `toString(false)`. One of the reasons I am slightly conservative with this is that have used `someUri.toString()` often as key to store stuff (like in local browser storage). Even though I don't think we overly often use the query bit, it will break those cos string identify isn't given anymore...

**Comment by chrmarti** [comment]
Makes sense, thanks. Btw., checked toString(true) works as expected (I was wrongly passing false before).
