### ISSUE TITLE
Cannot commit if message starts with a hash

### ISSUE THREAD

**Issue by corretge** [microsoft/vscode#84663]
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Steps to Reproduce:

1. modify a file
2. go to Source Control
3. stage changes
4. Write a message that begins with a hash, i.e., #241 check issue in vscode
5. click on the "Commit" button or use shortcuts, nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by corretge** [comment]
> /findDuplicates

ops sorry a lot! I search before to create a new issue but I didn't find it.

Sorry again

**Comment by usernamehw** [comment]
That was a command for the bot, not a passive aggressive comment :)

**Comment by corretge** [comment]
the boot works better than the search engine ;)

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/228097/68753061-a5d42100-0604-11ea-82df-5cbbfbef7f6c.png">

Ops! I realize that the issue is closed, and I search for open issues 😅
