### ISSUE TITLE
[Editor] Using Alt+Tab to navigate doesn't open file when keys are release unless you press tab at least two times

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#84666]
<pre>
Version: 1.41.0-insider (user setup)
Commit: c408a2c02d78982b1f83819c587c02bb59af9f93
Date: 2019-11-13T06:25:23.355Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
</pre>

Steps to Reproduce:

1. Open at least two files
2. Press Alt+Tab one to navigate from one to the other
3. Navigation doesn't occur when unless you press Tab at least two time. Instead focus stays in the list of files.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by NizamLZ** [comment]
Could not reproduce. File switch happens as it should, as soon as you release the Ctrl button, until then, each tab press will cycle among the open files. Nothing unusual. 

Used the latest master. 
```
Version: 1.41.0
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by ayyash** [comment]
My version is  Code - Insiders 1.41.0-insider and I too face the same issue, how do I generate the other information like you did?

**Comment by JonWallsten** [comment]
@NizamLZ: I'm using the latest insider-release. It worked fine before I updated today.

**Comment by NizamLZ** [comment]
@JonWallsten @ayyash, I am able to reproduce the issue in the commit you guys posted. Looks like the issue is fixed after that and the fix is present in the master branch. It will be resolved in the next insider build.

**Comment by JonWallsten** [comment]
@NizamLZ: Great!
