### ISSUE TITLE
shortcut defined on task

### ISSUE THREAD

**Issue by TheLogan** [microsoft/vscode#84668]
Tasks can be saved in .vscode and shared with the project, it would be nice to define shortcuts to run them in the project too.

I can think of two different ways of doing this. Method 1 would be to have the key directly on the task
```
{
    "tasks": [
        {
            "label": "runProject",
            "key": "ctrl+h",
            "command": "do stuff!"
        }
    ]
}
```
Method 2 would be to have reserved keywords
```

{
    "tasks": [
        {
            "label": "runProject",
            "key": "runtask1",
            "command": "do stuff!"
        }
    ]
}
```

And then have them show up in the keybinding.json so people can choose to change them if they want.

**Comment by alexr00** [comment]
You can already do this in your keybindings json file:
```
	{
		"key": "ctrl+shift+alt+t",
		"command": "workbench.action.tasks.runTask",
		"args": "npm: install"
	}
```
Where `args` is the label of the task.

**Comment by TheLogan** [comment]
Sorry it's taken me this long to respond, but that's sort of the reverse of what I meant, what you're suggesting is adding the task to a keybinding, what I suggested is adding a keybinding to a task. (so it can be shared with the task with the project)
