### ISSUE TITLE
Support for custom editors in the workbench

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84672]
To support custom editors (https://github.com/microsoft/vscode/issues/77131, https://github.com/Microsoft/vscode/issues/12176) we need our [`IWorkingCopyService`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/workingCopy/common/workingCopyService.ts) to become more powerful, specifically taking over responsibility of:

Work Areas:
* [x] dirty tracking
* [x] save/revert
* [x] auto save
* [x] hot exit
* [x] structural changes (move, delete, create, copy)
* [x] ~~save participants~~ (text file based only, we do not plan for an API for other extensions to modify the custom editor data)

**Comment by bpasero** [comment]
I think we settled on saving everything, even working copies.

**Comment by DonJayamanne** [comment]
@bpasero @mjbvz Is the plan to (`try`) ship the custom editor in the next release?
I'd like to ensure we (Python Extension) uses this when its available.

**Comment by mjbvz** [comment]
No. It will remain in proposed

**Comment by bpasero** [comment]
All editor auto save functionality will no work for custom editors as well.
