### ISSUE TITLE
Make type filters for outline and breadcrumbs language specific

### ISSUE THREAD

**Issue by Nutznieser** [microsoft/vscode#84678]
Is it possible to make type filters for outline and breadcrumbs (new in V1.4) language specific?
For example something like this:
```
{
    "[python]": {
        "outline.showConstants": false,
        "outline.showConstructors": false,
        "outline.showVariables": false,        
    },
}
```
It seems it will not work currently. I got the error: `Unknown Identifier. Use language identifiers`

**Comment by hrvoj3e** [comment]
:+1:  First thing I tried today.

**Comment by petevdp** [comment]
I'd like to work on this if possible!

**Comment by jrieken** [comment]
Ok, this is there config for the outline are defined: https://github.com/microsoft/vscode/blob/73e605653d45e8c64ee6390d5c5f5bcfabd3e7d0/src/vs/workbench/contrib/outline/browser/outline.contribution.ts#L30 and this is for breadcrumbs: https://github.com/microsoft/vscode/blob/3d8a749238cf85052bcf76039166ae3494422a91/src/vs/workbench/browser/parts/editor/breadcrumbs.ts#L121. You need to define that as resource specific and then adopt usages accordingly. This is a sample of doing that: https://github.com/microsoft/vscode/blob/9727eb60500657cd2c30e4a3992e17940c2cefba/src/vs/workbench/api/browser/mainThreadSaveParticipant.ts#L225

**Comment by petevdp** [comment]
@jrieken Perfect, thanks!
