### ISSUE TITLE
Add API to parse/update Uri.query

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#8467]
Testing #8192

Currently Uri.query needs to be parsed and updated through Uri.with() by the extension author. It would be nice to offer API doing that.

**Comment by jrieken** [comment]
I would refer folks to https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html since the format of the `query` is actually `scheme` dependent... Not very eager to open also that can of worms ;-)

**Comment by chrmarti** [comment]
Makes sense. Thanks.
