### ISSUE TITLE
File operations on compressed folder structures seems to be problematic (cut/copy/paste)

### ISSUE THREAD

**Issue by mustafakemalgilor** [microsoft/vscode#84671]
File operations on compressed folders are seems to be problematic. For instance, when I try to cut or copy a compressed folder, and paste it to other folder, only last child is pasted under the target directory. (parent folder structure is not preserved) I don't know whether this is the desired behaviour, but at least there should be a shortcut to copy/cut compressed folder as-is, with all the parents.

Steps to Reproduce:

1. Create a folder named foo in top level
2. Create a folder named bar under folder foo
3. Create a folder named baz in top level
4. Copy or Cut folder bar
5. Paste it under folder baz

> Version: 1.41.0-insider
> Commit: 0d728c31ebdf03869d2687d9be0b017667c9ff37
> Date: 2019-11-12T05:32:12.922Z
> Electron: 6.1.4
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Linux x64 5.3.0-1-amd64

**Comment by IllusionMH** [comment]
Should be handled as part of #84597 in "Context clicking each folder" item
