### ISSUE TITLE
VSCode 1.40 fails to run in User Mode

### ISSUE THREAD

**Issue by pmartinou** [microsoft/vscode#84675]
- VSCode Version: 1.40 ( code-stable-1573064450.tar.gz )
- OS Version: RHEL 7.4

Steps to Reproduce:

(as a normal user, non-root)

1. Download the .tar.gz version in a directory containing the VSCode-linux-x64 subdirectory
2. Untar it to apply the update:
-rw-rw-r--   1 pmart012 nmsuser 80513543 Nov 13 10:24 code-stable-1573064450.tar.gz
drwxrwxr-x   6 pmart012 nmsuser      108 May 28 23:36 node-v10.16.0-linux-x64
vxl:apps pmart012 $ **tar zxvf code-stable-1571154019.tar.gz**
3. Enter the VSCode-linux-x64 subdirectory
4. run VSCode:  it fails to run with the following indications:

vxl:apps pmart012 $ **cd VSCode-linux-x64/**
vxl:VSCode-linux-x64 pmart012 $ **./code**
```
./code: /lib64/libdbus-1.so.3: no version information available (required by ./code)
[28461:1113/102517.579125:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /local/NOT_SAVED/apps/VSCode-linux-x64/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

=== Same issue with a fresh install of:  code-insider-1573628741.tar.gz

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by joaomoreno** [comment]
If you launch the executable directly, please use `--no-sandbox`.

**Comment by pmartinou** [comment]
After upgrading to 1.40.0, running VSCode with:
`./code --no-sandbox` 
successfully launches VSCode (thanks !). The following warnings are shown, but do not prevent the application from running.

```
vxl:VSCode-linux-x64 pmart012 $ **./code --no-sandbox**
./code: /lib64/libdbus-1.so.3: no version information available (required by ./code)
/local/NOT_SAVED/apps/VSCode-linux-x64/code: /lib64/libdbus-1.so.3: no version information available (required by /local/NOT_SAVED/apps/VSCode-linux-x64/code)
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
/proc/self/exe: /lib64/libdbus-1.so.3: no version information available (required by /proc/self/exe)
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Option 'sandbox' is unknown. Ignoring.
```

**Comment by pmartinou** [comment]
Same result with VSCode 1.40.1 ( code-stable-1573664143.tar.gz ) : 
Fails to run in user mode with **./code**
Successfully runs in user mode with **./code --no-sandbox**

**Comment by eddyp** [comment]
I am also running VSCode from ~/opt/VSCode-linux-x64 and get the same error.

Since this was supported in the past without any parameters, shouldn't this be auto-detected and this issue considered a regression?

**Comment by eddyp** [comment]
BTW, I am finding the introduction of a SUID executable which will SUID as root a severe security issue; security is the reason I am *NOT* installing VSCode in the system, but in ~ . (well, security and convenience).
