### ISSUE TITLE
Search: `Enter` should be ignored when automatically searching

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84674]
My brain is hard writed to press <kbd>Enter</kbd> after typing a search term, which isn't needed any more. When I press <kbd>Enter</kbd> now, the viewlet flickers. The <kbd>Enter</kbd> key should just be ignored since the search term didn't change since the last key stroke.

**Comment by NizamLZ** [comment]
Which search box are you referring to here? Search in side panel or search in a single file (top right box)?

Side panel does not automatically search, so I assume you are referring to, search in a single file. Here, hitting enter takes you to the next occurrence, hence it cannot be ignored.

**Comment by JacksonKearl** [comment]
@NizamLZ the sidebar full text search actually does now search on type. its only available in Insiders though.

@joaomoreno with #84547 the flickering should be reduced/removed, can you let me know if this is still a problem in the latest Insiders?

**Comment by joaomoreno** [comment]
Let's close it up.
