### ISSUE TITLE
Commit to Git does't work with last VS Code Update

### ISSUE THREAD

**Issue by HubGitke** [microsoft/vscode#84676]
Issue Type: <b>Bug</b>

Entering a Message plus Ctrl+Enter does not make any result. Commits to be done manually on git bash 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|1.0.21
vscode-install-vsix|fab|1.4.0
docker-explorer|for|0.1.6
vscode-guid|hea|1.4.19
al|ms-|4.0.199169
powershell|ms-|2019.11.0
crs-al-language-extension|wal|1.1.21

</details>

**Comment by gjsjohnmurray** [comment]
Please see #84201 and close this if it is a duplicate

**Comment by HubGitke** [comment]
#84201
