### ISSUE TITLE
Azure Repos

### ISSUE THREAD

**Issue by joeyhofstede** [microsoft/vscode#84684]
Issue Type: <b>Bug</b>

Since 1.4.0 cannot log in to Azure DevOps anymore.
Keep getting Login screen in stead of device trus.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18956

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.12GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/joeyh/source/repos/ITON%20Blueprint|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.32.0
gitlens|eam|10.1.2
remote-wsl|ms-|0.40.2
csharp|ms-|1.21.7
powershell|ms-|2019.11.0
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.2

</details>

**Comment by rebornix** [comment]
Please file issues against the extension you use to login.
