### ISSUE TITLE
C# parameter hint not showing total overload count

### ISSUE THREAD

**Issue by keikay** [microsoft/vscode#84682]
I have seen animated screenshots around where by pressing CTRL + Shift + Space will open the parameter hint of an existing function. The parameter hint would then display \<hint number\>/\<hint count\> along with its details.

However, it isn't displaying the count, only the number of the current hint I am within.
![2019-11-13_19 41 26_Wednesday](https://user-images.githubusercontent.com/7377351/68760774-988f5480-064d-11ea-89c5-5bda85a54cde.png)

It should be showing 12 / 18 instead. But for whatever reason, it's just showing 12. The 18 is completely missing.

Is this a bug or did I screw up something?
Thanks!

**Comment by Sovgut** [comment]
What the hell with your font rendering?

**Comment by keikay** [comment]
> 
> 
> What the hell with your font rendering?

I have windows font anti-alias disabled because I hate the blurriness of it. However, it seems Visual Code is not following windows font, and there's no option to disable the anti-alias in Visual Code.

How do I disable that as well? Thanks!

**Comment by mjbvz** [comment]
Currently by design: https://github.com/microsoft/vscode/blob/59ffb0702fb77d21a966a41ec67c0a4fa94cf88f/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L243

**Simple repo:**

1. Create a TS file:

```ts
function foo(a: '1'): void;
function foo(a: '2'): void;
function foo(a: '3'): void;
function foo(a: '4'): void;
function foo(a: '5'): void;
function foo(a: '6'): void;
function foo(a: '7'): void;
function foo(a: '8'): void;
function foo(a: '9'): void;
function foo(a: '10'): void;
function foo(a: '11'): void;
function foo(a: '12'): void;
function foo(a: any): void {}

foo()
``` 

2. Trigger parameter hints for `foo`

/cc @misolori For alternative UI ideas

**Comment by misolori** [comment]
We could just dynamically grow the parameter hints box, though there's a lot of fixed height/widths in this widget:

![image](https://user-images.githubusercontent.com/35271042/68812485-032d9980-0628-11ea-8bdf-f98d90d273b1.png)

**Comment by mjbvz** [comment]
@misolori I changed it to always show the numbers (and use flexboxes for layout).

As I didn't want the left side to grow larger when you go from signature `9` -> `10`, I also added padding. Here's what it looks like now:

<img width="287" alt="Screen Shot 2019-11-13 at 9 27 24 PM" src="https://user-images.githubusercontent.com/12821956/68829044-73561280-065c-11ea-95b9-9cb5f3a3cae3.png">

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/86334
