### ISSUE TITLE
JavaScript IntelliSense and ECMAScript 5.1

### ISSUE THREAD

**Issue by benjibee** [microsoft/vscode#84687]
Many new to web development code _exclusively_ with features and syntax found in ECMAScript 2015 and newer, and are often working within runtimes such as Node.js, coding using supersets such as TypeScript, or syntax extensions like JSX.

I'd like to ask the members and contributors working so very hard on Visual Studio Code to please not neglect the needs of the majority of web developers who code daily using the widely supported ECMAScript 5.1 standard, even if those members and contributors don't use it daily themselves. I don't believe it warrants being viewed as a second-class citizen within the VSCode JavaScript world.

Scanning this repo's issues, I see many [legitimate](https://github.com/Microsoft/vscode/issues/43200) [issues](https://github.com/microsoft/vscode/issues/37842) have been closed or [comments dismissed ](https://github.com/Microsoft/vscode/issues/43200#issuecomment-364209278)with replies such as "_this is what most developers are now working in_." Well that was 2017 and it's still not true for the majority of web development.

A simple method of switching the built-in JavaScript IntelliSense features between newer and not fully supported standards and the older still not out-of-date ECMAScript 5.1 is a reasonable expectation and should be standard, not an extension, packet of snippets, etc.

**Comment by mjbvz** [comment]
What specifically is the problem?

**Comment by benjibee** [comment]
If you have a look at the linked issues (both of which you closed) you'll see specific examples of JavaScript snippets defaulting to ECMAScript 2015 syntax. As mentioned by @redfellow in #37842 VSCode switched to this syntax making them useless to those of us working on the web with the latest widely supported standard of ECMAScript 5 (referred to as vanilla previously). I wanted to bring this up again because I feel it was brushed off previously.

As for the proposed solution, I'll quote from my initial issue above:

_A simple method of switching the built-in JavaScript IntelliSense features between newer and not fully supported standards and the older still not out-of-date ECMAScript 5.1 is a reasonable expectation and should be standard, not an extension, packet of snippets, etc._

**Comment by mjbvz** [comment]
The thinking has not changed on snippets: we provide sensible defaults that extensions (or users) can customize. In late 2017— and certainly 2019—targeting es6 is the most sensible out of the box default.
