### ISSUE TITLE
Green area around code

### ISSUE THREAD

**Issue by jacoblindberg18** [microsoft/vscode#84690]
![Screenshot 2019-11-13 at 14 15 57](https://user-images.githubusercontent.com/57676261/68766988-38ce8480-0620-11ea-80e2-68c90ecf514a.png)
Issue Type: <b>Bug</b>

For some reason there is a green area(in this color theme) to the right and bottom of my code. Can't figure out why.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.4.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
HTMLHint|mka|0.6.0
LiveServer|rit|5.6.1
html-to-css-autocompletion|sol|1.1.2

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@jacoblindberg18 could you please run vs code with gpu optimization disabled, `code --disable-gpu`

**Comment by gguidotti** [comment]
I ran into the same issue this morning after VS Code upgraded to 1.40.1, never seen this behavior before. I had the same problem with "Dark (Visual Studio)" theme and the "One Dark Pro" theme which I've been using since ever. I did what @rebornix said and I'm now good. Instead of passing that parameter when opening VS Code, I decided to add the option inside the argv.json as explained in this SO post: https://stackoverflow.com/a/58762168/10310363

**Comment by alexalannunes** [comment]
Works for me! Thanks @gguidotti 

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code **`--disable-gpu`** --no-sandbox --unity-launch %F
Icon=/usr/share/pixmaps/com.visualstudio.code.png
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.22

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code **`--disable-gpu`** --no-sandbox --new-window %F
Icon=/usr/share/pixmaps/com.visualstudio.code.png

**Comment by alexalannunes** [comment]
surely must be the option --disable-gpu

**Comment by deepak1556** [comment]
You can set this option permanently now from with vscode

```
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
```

Since its a gpu issue there is nothing vscode can do our end as the fix needs to come from chromium.
