### ISSUE TITLE
Window resizing stopped working via spectacle or by mouse

### ISSUE THREAD

**Issue by romenigld** [microsoft/vscode#84693]
I do an update for the Mac OS Mojave and Window resizing stopped working for Spectacle and even I try to do with the mouse it isn't posible to resize. 

- VSCode Version: Version: 1.40.0
- OS Version: 10.14.6 (18G95)

**Comment by deepak1556** [comment]
Can you provide the exact steps to repro this issue, would help debug the issue further.

**Comment by evancharlton** [comment]
I have the same issue here. I don't really have repro steps other than "use @evancharlton's macbook", sadly.

I can resize the VS Code windows by mouse, though.

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by deepak1556** [comment]
@evancharlton can you attach a video showing the issue, that would help as well.

**Comment by romenigld** [comment]
Hello I update right now for the version:
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
And now I can resize and work's very well with the Spectacle App.
Thank's!

**Comment by evancharlton** [comment]
It seemed to resolve itself, despite me updating nothing. No idea what happened, but good work team! 😉 

If it happens again, I'll get some video or other debugging information.
