### ISSUE TITLE
debug process fails (exits)

### ISSUE THREAD

**Issue by comjun04** [microsoft/vscode#84694]
Issue Type: <b>Bug</b>

When I press restart button on debugger, it stops.

Steps to Reproduce:

1. Open any JavaScript file.
2. Run debugger (with `node`)
3. press `restart`.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Quad-Core Processor              (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.43GB (0.29GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by roblourens** [comment]
Please give more details about what happens when it "stops"

**Comment by comjun04** [comment]
Sorry for this issue.
I found the exact same problem (#85386) describing this.
