### ISSUE TITLE
VS Code asks which remote to push to, despite there being only one.

### ISSUE THREAD

**Issue by waynebloss** [microsoft/vscode#84697]
- VSCode Version: 1.40.0
- OS Version: Linux x64 4.19.81-1-MANJARO

Steps to Reproduce:

1. Create a git branch
2. git push
3. VS Code asks which remote to push to, despite there being only one.

Does this issue occur when all extensions are disabled?: Not applicable. Git functionality is from a built-in extension.

More information:

[This had been fixed in the past](https://github.com/microsoft/vscode/issues/35373). Seems like a good first issue for someone who is interested in contributing. Thanks!

**Comment by joaomoreno** [comment]
This came in as a PR on purpose in case you'd like to add a new remote from that action.

**Comment by waynebloss** [comment]
OK, it’s really no big deal I was just pointing out that there had been a change in the workflow and that it had been fixed in the past. I can live with the new change, no problem. Thank you!

**Comment by alejandroiglesias** [comment]
@joaomoreno I am actually annoyed by this since it pops up every time I push a new branch. How can I disable this?

**Comment by joaomoreno** [comment]
Yeah I'm also annoyed. I'll revert this change.

**Comment by waynebloss** [comment]
@joaomoreno Any chance you can influence this other set of issues that are related to each other? You seem to have the power to just decide what you want to do and do it, so I figured it wouldn't hurt to ask...

- `83639` - Add option to disable automatic selection on focus in explorer
- `75181` - Explorer: option to disable auto open of files when no editor active
- `67708` - New explorer: going back to explorer no longer opens active file

No links to them since I didn't want to create references to this issue because there's no relation.

The decision in `67708` to just keep the behavior since it had been there for a long time was a bad decision IMO and people are going to keep asking to fix it since the UX is just wrong.

**Comment by waynebloss** [comment]
@joaomoreno I see that you were already involved in the comments on `67697`, so I'm sorry if this request is redundant.

Thanks for your work!

**Comment by joaomoreno** [comment]
@waynebloss Thanks for raising the issues and for not linking them! I'll bring @isidorn in for looking into them once again, since he's the area owner.

**Comment by isidorn** [comment]
@waynebloss I have reopend the issue https://github.com/microsoft/vscode/issues/83639 and we can continue the discussion there.
Thanks
