### ISSUE TITLE
git spawn ENAMETOOLONG when adding/removing a large directory

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#84696]
Issue Type: <b>Bug</b>

1. Have a repo with a large amount of changed files in one folder and use the tree view
2. Click <kbd>+</kbd> next to the folder to stage the changes or <kbd>-</kbd> to unstage them.
3.:
![grafik](https://user-images.githubusercontent.com/17641229/68774214-0a0adb00-062d-11ea-8dee-933c13681311.png)

This was supposedly fixed in https://github.com/microsoft/vscode/pull/66095 for the discard command but either the other commands or the tree view was forgotten as a potential source of problems.
Clicking the button next to "changes" works fine:
![grafik](https://user-images.githubusercontent.com/17641229/68774395-56561b00-062d-11ea-8c6b-be208dc95309.png)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.14.2
RunOnSave|eme|0.2.0
prettier-vscode|esb|3.3.5
vscode-test-explorer|hbe|2.14.6
rest-client|hum|0.22.2
vscode-docker|ms-|0.8.2
vscode-language-pack-de|MS-|1.40.2
vscode-jest|Ort|3.0.2
project-snippets|reb|0.5.0
java|red|0.52.0
vscode-coverage-gutters|rya|2.4.2
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by joaomoreno** [comment]
Yup, the same fix as https://github.com/microsoft/vscode/pull/66095/files needs to be applied to the stage action.

**Comment by Friksel** [comment]
+1
Same issue here in the latest vs code and latest git

**Windows 10 home:** v10.0.18362
**VS Code:** 1.44.2
**Git version:** 2.26.2.windows.1
