### ISSUE TITLE
Code Editor text rendering is using grayscale

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#84698]
* open one or multiple editors on Windows
* the text inside the editor is rendered with grayscale antialising
![image](https://user-images.githubusercontent.com/5047891/68776558-9539a000-0630-11ea-8833-bb535ab96981.png)
* it should use subpixel AA:
![image](https://user-images.githubusercontent.com/5047891/68776966-358fc480-0631-11ea-8d6d-5b3dcae5d0a2.png)

**Comment by nklmilojevic** [comment]
I just tried 1.40.1. This doesn't fix it on macOS Catalina.

1.39.2:

![CleanShot 2019-11-13 at 22 37 21](https://user-images.githubusercontent.com/9573356/68806455-37c04600-0666-11ea-98f7-d68757c29716.png)

1.40.1:

![CleanShot 2019-11-13 at 22 37 29](https://user-images.githubusercontent.com/9573356/68806474-4149ae00-0666-11ea-90bb-a6066866d540.png)

**Comment by forivall** [comment]
It did, however, fix the issue on Mojave (as I haven't updated to Catalina yet)
