### ISSUE TITLE
Please stop the permanent "'mysql' extension is recommended" suggestion box

### ISSUE THREAD

**Issue by kralcifer** [microsoft/vscode#84705]
Someone mentioned this a year ago in issue #63624.

I use postgres.  If there was an extension I liked I would use it but I haven't seen one that I like yet.  But that's not really the point.

The point is that many/most suggestion boxes fade away but the mysql extension suggestion stays until dismissed.  This is very annoying.  Please make it auto dismiss.

**Comment by chrisdias** [comment]
this was fixed a while ago, please let me know if its still an issue.
