### ISSUE TITLE
Use original-fs instead of manually ignoring ASAR files

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8470]

**Comment by bpasero** [comment]
@alexandrudima for now I am only replacing `fs` with `original-fs` in the renderer. All other forked processes run with "`process.noAsar = true`" except for the main process.

**Comment by alexandrudima** [comment]
@bpasero Does this change come from a bug that is reproducible or do you want me to review the commit? Also, how do you handle the git service, search service, etc.

**Comment by alexandrudima** [comment]
Ah ok, I didn't see your comment. Ok, the first question still remains Does this change come from a bug that is reproducible or do you want me to review the commit?

**Comment by bpasero** [comment]
@alexandrudima yes sorry, it is the bug where you cannot delete a *.asar file once it becomes visible in the explorer.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7751
