### ISSUE TITLE
Collapsed explorer nodes only show up after expanding a folder

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#84703]
Is this how it's supposed to work? It makes sense that we don't look inside a folder until it's opened, but it was a little surprising.

![Nov-13-2019 09-44-12](https://user-images.githubusercontent.com/323878/68779564-76201b80-05fa-11ea-83d2-69b99f4a4c3e.gif)

**Comment by joaomoreno** [comment]
Unfortunately yeah... otherwise we have to call `readdir` on every rendered folder. Currently we don't. Leaving this to @isidorn.

**Comment by isidorn** [comment]
Yeah, it would be a perf hit if we did this. Leavign this open as a feature request for now, and we can decide in the future what to do.

**Comment by jrieken** [comment]
Honestly - I'd say this is stretching the limits of feature request and I'd say that's how I expect the feature to work/to be defined.

**Comment by roblourens** [comment]
After using this feature for awhile, I don't think this is necessarily an issue.

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/66971
Since it goes in the same direction of resolving all folders before hand
