### ISSUE TITLE
Bad svg image in jupyter notebook

### ISSUE THREAD

**Issue by YuanshengZhao** [microsoft/vscode#84709]
- VSCode Version: 1.40.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open `jupyter notebook` in command line. (NOT in vs code!)
2. Create a new `ipynb` file in the browser and type the following code and execute it.
```
%config InlineBackend.figure_formats = ['svg']
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

x=np.arange(-2.0, 2.0, 0.01)
y=2**x

fig,ax=plt.subplots()
ax.plot(x,y,label='$2^x$')
plt.legend()
plt.show()
```
3. Save the file.
4. Open it in vs code, and the bad image appears.
![image](https://user-images.githubusercontent.com/37881856/68780464-b07ccd80-0679-11ea-983d-51b9bf1578f8.png)

Note: If everything is done in vs code, the image appears to be all right.

**Comment by IllusionMH** [comment]
This functionality is provided by an extension and issue should be filled in extensions repo first.
