### ISSUE TITLE
No longer possible to resize VS.code windows below a certain minimum size

### ISSUE THREAD

**Issue by jlarcombe** [microsoft/vscode#84708]
- VSCode Version: 1.40.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open a new VS.code window.
2. Ensure the status bar and activity bar are both turned off.
3. Attempt to make the window very small.

In old versions, it was possible to get the Window extremely small, which I found very useful. Now, you can't resize it below 1424x1424.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Probably a duplicate. See https://github.com/microsoft/vscode/issues/84164#issuecomment-551318961 for explanations by @sbatten

**Comment by jlarcombe** [comment]
Thanks, I see. I've added a comment there asking if this minimum size could be exposed as an option - I much preferred the old minimum of 200x120, which is practical for tiny 'notepad' files if you don't have the other panes visible.
