### ISSUE TITLE
createCursor command throws error when used in keybinding

### ISSUE THREAD

**Issue by duanehutchins** [microsoft/vscode#84707]
- VSCode Version: 1.40
- OS Version: Windows 10
- Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Add a keybinding for `createCursor` to `ctrl+alt+enter` when `editorTextFocus`
2. Use keybinding
3. Error thrown: `Cannot read property 'lineNumber' of undefined`

Expected results: The cursor is moved to the location of the mouse or the middle of the editor view. This would be helpful for when I scroll using the keyboard commands and want to drop my cursor where I'm looking without picking up my mouse to click the screen.

**Comment by usernamehw** [comment]
```js
{
	"key": "ctrl+alt+enter",
	"command": "cursorMove",
	"when": "editorTextFocus",
	"args": {
		"to": "viewPortCenter"
	}
},
```

**Comment by duanehutchins** [comment]
I didn't know about this.  Thank you!  Closing ticket.
