### ISSUE TITLE
Unable to link work items to a commit

### ISSUE THREAD

**Issue by TheGhost2804** [microsoft/vscode#84717]
- VSCode Version: 1.40
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Type #nnn (nnn being the workitem number) in the commit field
2. Hit commit and watch how nothing happens
3. Type another character as first character and the commit will happen but is still not linked to the workitem.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by TheGhost2804** [comment]
May be a duplicate, but that duplicate is also closed! The issue is still present!

**Comment by usernamehw** [comment]
It will be released in version **1.40.1**
