### ISSUE TITLE
Keyboard Maestro's Activate Window Switcher could not work when update to 14.0

### ISSUE THREAD

**Issue by kyochou** [microsoft/vscode#84716]
- VSCode Version: 14.0
- OS Version: macOS Catalina Version 10.15.1 (19B88)

Steps to Reproduce:

1. open vscode, open multiple windows, use Keyboard Maestro's "Activate Window Switcher" to switch window.
2. when i use version 13.9.2, it's show every opened windows title, but in 14.0, it only show "no window available".

Does this issue occur when all extensions are disabled?: No, but same in 13.9.2

**Comment by rebornix** [comment]
@deepak1556 seems quite a few window manager on macOS stops working with our latest stable.
