### ISSUE TITLE
Cannot Open any File or Path in web vscode by run yarn web in docker

### ISSUE THREAD

**Issue by jinmu333** [microsoft/vscode#84718]
- VSCode Version: git master
- OS Version: docker debian bluster

Steps to Reproduce:

1. yarn

![image](https://user-images.githubusercontent.com/32295532/68822797-d54e6080-06cc-11ea-917e-2b02c9a4f537.png)

2. yarn watch

It stop here

![image](https://user-images.githubusercontent.com/32295532/68822730-a801b280-06cc-11ea-943e-458f0547d9ac.png)

3. yarn web

![image](https://user-images.githubusercontent.com/32295532/68786533-e79fae80-067a-11ea-87c8-225d27125ae7.png)

**Comment by bpasero** [comment]
Yes, this is by design. The web version running out of sources is very limited currently and only provides a in memory fs.

**Comment by jinmu333** [comment]
> Yes, this is by design. The web version running out of sources is very limited currently and only provides a in memory fs.
Ok thanks
