### ISSUE TITLE
Unable to Save a file in different extension as well as to other Location

### ISSUE THREAD

**Issue by theprashantb** [microsoft/vscode#84713]
Issue Type: <b>Bug</b>

Open a File > Make Some Changes > Go to File->Save As

VS Code vers
![issue](https://user-images.githubusercontent.com/42715437/68784255-4a388080-0662-11ea-8fb0-c384d25697b6.png)
ion: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.22GB free)|
|Process Argv|D:\xampp\htdocs\miniorange\js\report-form.js|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
prettier-vscode|esb|3.4.1
php-intellisense|fel|2.3.13
pretty-formatter|mbl|0.1.6
python|ms-|2019.10.44104
awesome-flutter-snippets|Nas|2.0.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I cannot reproduce, does it work when saving NOT in OneDrive?

**Comment by theprashantb** [comment]
Yeah, It is working.
