### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by troyacodes** [microsoft/vscode#84727]
Issue Type: <b>Bug</b>

Prettier not showing in status bar anymore

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.2.0

**Comment by usernamehw** [comment]
/causedByExtension https://github.com/prettier/prettier-vscode/issues/1044
