### ISSUE TITLE
Monotype font is not used when set.

### ISSUE THREAD

**Issue by aquilax** [Microsoft/vscode#8472]
I cannot set my code font to Monotype in VSC. Both sublime text and Google Chrome render Monotype well.

![Monotype](http://i.imgur.com/GoxoZOt.png) 

- VSCode Version:
Version 1.2.1
Commit fe7f407b95b7f78405846188259504b34ef72761
Date 2016-06-14T12:54:38.105Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
Xubuntu  (Ubuntu 16.04 LTS)

Steps to Reproduce:

1. Add this in your setting 
```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "monospace",
    "editor.fontSize": 16
}
````
2. Restart VSC just in case
3. Check the code rendered font

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/5742
