### ISSUE TITLE
[html] Unquoted HTML attributes are parsed/displayed incorrectly

### ISSUE THREAD

**Issue by Aloso** [microsoft/vscode#84729]
### Bug:

Unquoted HTML attributes containing slashes (`/`) are parsed incorrectly:

- If the attribute is an URL, only the part _before_ the first slash is underlined and opened when following the link with Ctrl+Click.
- When reformatting the document, indentation is buggy after the unquoted attribute

### Steps to Reproduce:

1. Open the following HTML document:

    ```html
    <!DOCTYPE html>
    <html>
    <body>
        <a href=http://www.example.com></a>
    </body>
    </html>
    ```
    You should see the incorrect link underline.

2. Reformat the document. It now looks like this:

    ```html
    <!DOCTYPE html>
    <html>
    
    <body>
      <a href=http://www.example.com> </a> </body> </html>
    ```

VS Code version: VSCodium 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-07T19:55:05.094Z)
OS version: Linux x64 5.3.8-3-MANJARO

I also tested it in the latest insider version (1.41.0-1573628786)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 x 2152)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.58GB (1.78GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
toml|be5|0.4.0
ra-lsp|mat|0.0.1

</details>

**Comment by mjbvz** [comment]
Still seeing this in 7f1975a4fb29d0a788c21f17eb2aad056fec22d8

**Comment by aeschli** [comment]
Sorry, I forgot to add that I just fixed the link detection.
Formatting is done by jsbeautify: https://github.com/beautify-web/js-beautify/issues/1736
