### ISSUE TITLE
Escape should cancel "Find in Files"

### ISSUE THREAD

**Issue by glittle** [microsoft/vscode#84724]
When using "Find in Files" pressing Escape should focus back on the current document.

**Comment by JacksonKearl** [comment]
Escape currently cancels the active search, I think this is the correct behavior in general. However if you'd like to configure this, you can add the following to your `keybindings.json` ("Preferences: Open Keyboard Shortcuts (JSON)" in the command pallette):

```
  {
    "key": "escape",
    "command": "workbench.action.focusActiveEditorGroup",
  	"when": "searchViewletFocus"
  },
```

**Comment by fulldecent** [comment]
Possible remaining scope for this issue added to #85706
