### ISSUE TITLE
Markdown preview no longer shows images with root relative path after update to 1.40.0

### ISSUE THREAD

**Issue by NathanielACollier** [microsoft/vscode#84728]
Markdown preview of images using this syntax `![](/assets/2019-10-24_07_56_26.png)` no longer works after updating to 1.40.0.

`/assets/` is a folder in the root of the folder open in vscode.

- VSCode Version:  1.40.0, 1.40.1
- OS Version:  Windows 10 1903

Steps to Reproduce:

1. git clone https://github.com/NathanielACollier/issues_vscode_1_40_0_markdownPreviewRootRelativeImg
2. cd issues_vscode_1_40_0_markdownPreviewRootRelativeImg
3. code .
4. Image doesn't display in readme.md

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**11/14/2019 11:15 AM - Reformatted**

**Comment by mjbvz** [comment]
Works for me. Please fill out the issue template and provide steps to reproduce this

/needsMoreInfo

**Comment by NathanielACollier** [comment]
I'll work on the issue template.  This is the minimal folder that would reproduce the problem.  The problem is still present in 1.40.1.
https://github.com/NathanielACollier/issues_vscode_1_40_0_markdownPreviewRootRelativeImg

We've seen the problem on every windows 10 1903 computer we've tried it on.  We are going to try it on macos and ubuntu.

**Comment by pingu8007** [comment]
I got the same issue on Windows 10 1903, and every time I open the preview page I got following lines in console:

```
[Embedded Page] Not allowed to load local resource: file:///D:/%5Copt%5CDocuments%5Cwww%5Cassets%5C2019%5CIMG_20191003_184153.jpg
  ERR Invalid regular expression: /^image\\jpeg;label:IMG_20191003_184153\.jpg;description:HEAD;size:313833;base64...
```

![image](https://user-images.githubusercontent.com/8936513/68844623-0cd8ff00-0705-11ea-8d72-3fbe414ca5a5.png)

**Comment by inliquid** [comment]
Same for me;
![изображение](https://user-images.githubusercontent.com/6797881/69061262-dc0d0880-0a29-11ea-809d-f065468a4fdd.png)

Windows 10 1903 / VS Code 1.40.1

**Comment by NathanielACollier** [comment]
I found out today that the `Markdown Preview Enhanced` extension still functions correctly.  So if your on windows and use vscode for  markdown  you can [install it](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) and your images with root folder paths should function again.

**Comment by NewFuture** [comment]
@mjbvz 
It still reproduces in Vscode `14.0.2` on Windows 10.

**Comment by NewFuture** [comment]
As @pingu8007 mentioned, the reason is, that it can not load local images in schema such as `file:///D:/...`.
It may be a  problem with security policies.

**Comment by P0oOOOo0YA** [comment]
Same here on Linux it seems this feature is broken in all major operating systems. Absoulte path, Relative path, Absolute with `file` protocol to make it a valid URI, no matter what i do it doesn't load images. :(

**Comment by pingu8007** [comment]
> Same here on Linux it seems this feature is broken in all major operating systems. Absoulte path, Relative path, Absolute with `file` protocol to make it a valid URI, no matter what i do it doesn't load images. :(

It's strange. Did your update to latest version?
It should be fixed in last few updates and I can confirm it's works in vscode 1.14.1
