### ISSUE TITLE
VSCode : End of line Sequence issues

### ISSUE THREAD

**Issue by av1422** [microsoft/vscode#84735]
Issue Type: <b>Bug</b>
I noticed these issues from this morning, 
1. I'm trying to set end of line sequence to 'LF', its not effecting any of the existing files. By default its auto, VS code is unable to detect the OS i guess (not sure 🤔 ). 
2. So i changed in the right bottom from CRLF to LF, its fixes only in the current file and it was registered as a change to the git (weird). So I have to change all my files manually implies that all my files are in the git changes. Not sure why the change is effected as a change to the file.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 17.7.0

**Comment by yume-chan** [comment]
> I'm trying to set end of line sequence to 'LF', its not effecting any of the existing files.

Where did you "set end of line sequence to 'LF'"?

> change all my files manually implies that all my files are in the git changes. (**not** weird)

Changing eof to LF means replacing all `\r\n` in your text file to `\n`, that will definitely count as file changes.

If you want to work with Git, check your [core.autocrlf](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code) setting. You may had set it `true` when you was installing Git for Windows. And you may want `input` from your statement.

**Comment by av1422** [comment]
> Where did you "set end of line sequence to 'LF'"?
> In the VScode settings.. Prefernces -> settings -> Text Editor -> Files -> Eol

> Changing eof to LF means replacing all `\r\n` in your text file to `\n`, that will definitely count as file changes.
> Thanks noted. Thats a valid answer.

 **EDIT:** I see you are using macOS. so maybe your `core.autocrlf` is `false` (default), and the problem is that your repository is in CRLF eof. In this case there is no way to checkout as LF and commit as CRLF, so don't change it...
--I may have to change it because, There is a linting error across my code i.e., (Expected linebreaks to be 'LF' but found 'CRLF'.eslint(linebreak-style)).. It is occurring only on my machine

**Comment by rebornix** [comment]
Thanks for your feedback, VS Code will only modify line break of active file in the editor instead of all files in the workbench, that's as expected.
