### ISSUE TITLE
Quick pick with many items cuts off vertically on small screens

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#84734]
- VSCode Version: 1.40.0
- OS Version: Windows 10

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/530988/68799986-23be1980-0651-11ea-87ae-d6bb6fa97b72.png)

See the last entry at the bottom which is cut off.

**Comment by chrmarti** [comment]
@letmaik There should be a vertical scrollbar when the mouse cursor is inside the list. Keyboard navigation should work too. Does it not?

**Comment by letmaik** [comment]
The title of this issue was misleading, I changed it. Just create a quick pick with 9 or 10 items like in the screenshot and then make your window smaller vertically. You will see that no scrollbar is appearing and it just cuts off without any way to get to the bottom items.

**Comment by letmaik** [comment]
@chrmarti I tried your fix, but it only kicks in when you've resized the window at least once. If you haven't resized it then it's the old behaviour.

**Comment by chrmarti** [comment]
@letmaik Fixed, thanks!
