### ISSUE TITLE
Make JavaScript comment blocks collapsible

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#84732]
Issue Type: <b>Feature Request</b>

JavaScript comment blocks aren't able to be collapsed and they should be.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/22732
