### ISSUE TITLE
Multiple setBreakpoints requests sent over DAP

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#84741]
- VSCode Version:

```
Version: 1.41.0-insider
Commit: 213bdddb72ff7a6c8eed071420de8ddac4293cb1
Date: 2019-11-11T05:36:13.475Z
```

- OS Version: MacOS Mojave 10.14

Something I've been seeing for a while is that whenever we set a breakpoint VS Code sends us `setBreakpoint` multiple times over the DAP. In one of our test projects, it's sending the breakpoint 4 times. PWA right now just increments the breakpoint ID each time it receives a request.

![image](https://user-images.githubusercontent.com/2230985/68803713-200ca180-0615-11ea-8045-732c9d6c15e7.png)

PWA isn't handling this super well right now; it's verifying one of the breakpoints but depending on which one it verifies VS Code's UI doesn't always update. 

Steps to Reproduce:

1. Clone and run PWA (https://github.com/microsoft/vscode-pwa, npm install, npm watch, debug the "extension" launch config)
2. Open demos/node, run `[Node] Launch program`. 
3. Open the trace file in https://microsoft.github.io/vscode-pwa-analyzer/index.html and observe the duplicate setBreakpoints calls:

![image](https://user-images.githubusercontent.com/2230985/68807609-f9eaff80-061c-11ea-9a2b-b45ed319a1c3.png)

Here's the log of the 4x duplicates I got using the `web-worker-ts`. There's some noise in here, look at the calls around +14.428:  https://memes.peet.io/img/15fb5036-986b-4ae7-abb4-770fc6b64983.json

I could get around this by tracking and deduplicating the requests that VS Code sends to the debug adapter, but this seems like something we shouldn't have to do.

**Comment by isidorn** [comment]
Thanks for the steps, however I just got back from vacation and will not have time to look into this the next couple of days.
To proceed I suggest that you simply put a breakpoint [here](https://github.com/Microsoft/vscode/blob/c1997dcd4bc2ee23c39349218ee1828dd99bb9d1/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L349) and figure out why is VSCode callling all those `setBreakpoints` requests.
Please note that the `setBreakpoints` requrest is called for each file that you have a breakpoint in. 

Also you can check if this can be reproduced using a simple node sample.

**Comment by isidorn** [comment]
@connor4312 let me know if this is important for pwa, otherwise I plan to not look into it.

**Comment by connor4312** [comment]
This is actually fine, thanks for the reminder!

 1. One duplicate was because the setBreakpoint is sent to both the parent and child sessions. I didn't realize this at the time.
 2. The other was because we reinitialized the logger for both sessions, which was causing logs to be written twice.
