### ISSUE TITLE
Linux Mint Guest OS crashes while using VSCode

### ISSUE THREAD

**Issue by prjemian** [microsoft/vscode#84745]
Issue Type: <b>Bug</b>

problem:
VirtualBoxVM crashes with Application Error while running VSCode

1. start with Windows 10
1. Run Oracle VirtualBox
1. create linux mint VM
1. run linux mint VM
1. install VSCode for Linux from tar.gz
1. clone some repo from GitHub
1. cd into local repo and start editor (usually `code -a .`)
1. work with VSCode in local clone (unsure exactly what activity triggers this)

After some unpredictable amount of time, clicking on a menu or the settings icon (maybe some other actions also trigger), the expected pop-up menu will be all black instead of filled with content.  A short time (usually no more than a minute) later, the guest VM will be unresponsive and an Application Error dialog will appear in the Win10 host.  The VM is dead at this point.  Here is the content of the dialog just received:

```
The instruction at 0x00007FF84210F161 referenced memory at 
0x00000000000000000000000000000000.  The memory could not be written.

Click on OK to terminate the program
```

This has been a consistent problem in the VSCode versions since I started.  May be tied to git plugin and editing in a directory that is a git repo.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T18:14:08.920Z)
OS version: Linux x64 4.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (1 x 1991)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|5.82GB (3.37GB free)|
|Process Argv|-a . --no-sandbox|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.1.2
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
cpptools|ms-|0.26.2-insiders
preview-vscode|myh|1.3.0
vscode-print|pdc|0.7.13

</details>

Also:

```
(base) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ more /etc/os-release 
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tina
UBUNTU_CODENAME=bionic
```

------

Windows 10 host details (running Oracle VirtualBox)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.32GB free)|
|Process Argv|-a .|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by prjemian** [comment]
screen shot at time of recent crash
![VSCode-crash](https://user-images.githubusercontent.com/2279984/68811120-7c7fb900-0635-11ea-88d3-b4865f9972e5.jpg)

Linux Mint Guest VM is in right panel

**Comment by prjemian** [comment]
Suspecting that git is involved, will try working without plugins next.

**Comment by prjemian** [comment]
FYI: `code -a --disable-extensions .`

System still crashed.

**Comment by prjemian** [comment]
This screen shows one of the symptoms.  In this case (just installed VSCode-linux-x64-1573664143 now), starting with: `code -a --disable-extensions .`, opened one of the python source code files.  Then clicked on the *settings* gear (planning to look for plugin configuration to verify that plugins are still off) and received this black box instead of a pop-up menu:
![Clipboard01](https://user-images.githubusercontent.com/2279984/68812698-552aeb00-0639-11ea-8394-000a675450e0.jpg)

**Comment by prjemian** [comment]
And now the VM has crashed with exactly the same *VirtualBoxVM.exe - Application Error* dialog as originally posted: `The instruction at 0x00007FF84210F161 referenced memory ` ...

Hope this is enough info for y'all to figure this one out.

**Comment by prjemian** [comment]
Ok, one more variation to try (don't use the `-a` option), once the VM is restarted.  `code --disable-extensions`

**Comment by prjemian** [comment]
This is not a good sign (tried clicking the *settings* gear):
![Clipboard01](https://user-images.githubusercontent.com/2279984/68812998-1a758280-063a-11ea-863f-993282f506d6.jpg)

**Comment by prjemian** [comment]
Any other diagnostics?

**Comment by prjemian** [comment]
... and system has now crashed again

Was moving mouse between menus, looking if any of them would appear with text content rather than all black.  Started with *Help* (all black), slid left to *Terminal* (text content), back to *Help* (all black and VM crashed right away.)

**Comment by deepak1556** [comment]
Can you run with `code --disable-gpu` and see if it still crashes ?

**Comment by prjemian** [comment]
Started with `code --disable-gpu ` and observe no initial problems while clicking the *settings* gear or moving between the different items in the menu bar.  Before, symptoms were displayed during these activities as shown above.

Before we declare this to be a *finding*, let's work with it a bit, typical activities, and see if problem recurs.

**Comment by prjemian** [comment]
Here's the VirtualBox Display setup for this VM:
![Clipboard01](https://user-images.githubusercontent.com/2279984/68865899-2ce2d100-06b9-11ea-8229-3d8daec09fab.jpg)

**Comment by prjemian** [comment]
restarted *code* as `code --disable-gpu -a .` and still no problems

This "works for me now".  However, not closing the issue since it remains a bug.  I assume you have all you need to resolve it?

**Comment by prjemian** [comment]
Oh, two more things that may not have been clear about the system description:

* VSCode is installed by the unprivileged user, not root account, in subdirectory of ~/Apps/, subdir includes the build number so I can easily revert if desired
* linux mint *Mate* variant is used

**Comment by prjemian** [comment]
update:  worked with that (`code --disable-gpu -a .`) all day with no problems

Looks like a NULL pointer was not checked, perhaps related to when GPU use is enabled.

Once that line of code is found, will you follow up with Oracle VirtualBox?  There is *no way* that a user program on linux (even in a VM) should crash the entire machine.

**Comment by prjemian** [comment]
It just crashed out.  Same error message.  Crashes only happen when interacting with VSCode editor.

**Comment by deepak1556** [comment]
Thanks for testing this, the fix for it has to come from chromium. I am leaving the issue open until the fix is landed in future versions, can you test our exploration build from https://github.com/microsoft/vscode/issues/84574#issuecomment-553260601 that has newer chromium runtime to see if its fixed.

**Comment by prjemian** [comment]
On it now.  And, thanks for being responsive!

**Comment by prjemian** [comment]
Youch!  Crashed right out in this many minutes!  (started with `code -a .`)

**Comment by prjemian** [comment]
Specifically, had been editing python code.  Needed to configure the new app with theme and extensions (GitLens, Python).  Ran debugger once.  No problems yet.  Edited a [.coveragerc](https://coverage.readthedocs.io/en/v4.5.x/config.html) file and git commit.  When trying to do the git push, got the black pop-up menu.  Tried using the menubar.  Help menu OK, Debug menu all black and then VM crashed.

**Comment by deepak1556** [comment]
Thanks for the repro steps, I will see if I can narrow down the issue from upstream. Will ping back if needed addional info.

**Comment by prjemian** [comment]
FYI, this installation detail:

```
(base) mintadmin@mint-vm:~/.../eclipse/adl2pydm$ ll ~/Apps/VSCode-linux-x64/bin/
total 4.0K
lrwxrwxrwx 1 mintadmin mintadmin   18 Nov 18 17:10 code -> ./code-exploration*
-rwxr-xr-x 1 mintadmin mintadmin 1.7K Nov  7 20:47 code-exploration*
```

**Comment by jrial** [comment]
This is a known issue when running Chrome (and Electron, and anything built on Electron) under VirtualBox. See https://www.virtualbox.org/ticket/15417 and https://www.virtualbox.org/ticket/12738

The issue has been known for many years. Apparently there aren't enough resources at VirtualBox to work on a fix, so don't expect one soon. For now your best bet is either using the `--disable-gpu` flag, or moving to a different virtualization software, e.g. VMWare Workstation, if you don't mind going proprietary. I can confirm these issues went away when I migrated my VM from VirtualBox to VMWare Workstation.

**Comment by jrial** [comment]
Additionally, if memory serves well, I believe my workaround back in the day was to quit the application with `ctrl-q` as soon as the graphical glitches started to appear. If you catch it in time, you can simply quit and relaunch the application and your VM will keep on truckin'.

**Comment by prjemian** [comment]
Aha!  Well, thanks for getting to the root cause of this issue.  I confirm your empirical approach to *quit as soon as glitches start to appear*.  That has worked for me as well.  For now, this conversation has helped me remember to use `--disable-gpu` when in the VM.

Let's leave this issue open until the upstream (VirtualBox) issues are resolved, if ever.  That would be helpful to others who encounter this problem, seeing it as yet unresolved.

**Comment by prjemian** [comment]
@deepak1556 & @jrial: I applaud you both on your responsiveness and diligence on this issue.

**Comment by jmaha** [comment]
Understood this issue is closed, but as a note for future visitors, this issue affects VMWare Fusion as well.

**Comment by jrial** [comment]
jmaha: no, this issue is still open. It was mentioned in another issue, which has been closed.

Quoting @prjemian:
> Let's leave this issue open until the upstream (VirtualBox) issues are resolved, if ever. That would be helpful to others who encounter this problem, seeing it as yet unresolved.

**Comment by jmaha** [comment]
@jrial Aha, thanks for the clarification. Well I can confirm the same issue with VMWare Fusion, and also can confirm that setting the --disable-gpu flag in all VSCode (and disabling hardware acceleration in my Chromium-based Electron app in development) eliminates the graphical corruption -> OS crash issue described here.

**Comment by tahaimt** [comment]
I just tried this with the latest version of VSCode on a ubuntu VM. After opening VSCode and pressing right click on a file in the side panel shows an empty context menu. Second right click crashes the VM.

**Comment by dandymon** [comment]
Same symptoms here with Centos7.
Followed these instructions insode VSCode to fix - no performance changes other than it doesn't crash!


Open the Command Palette (Ctrl+Shift+P).
Run the Preferences: Configure Runtime Arguments command. This command will open a argv.json file to configure runtime arguments.
You might see some default arguments there already.
Add
"disable-hardware-acceleration": true
Restart VS Code.

**Comment by prjemian** [comment]
On my linux mint, that file is `${HOME}/.vscode/argv.json`

**Comment by AndyXan** [comment]
Also happens on Ubuntu 19.10, fully updated, latest vs code

**Comment by d-daniel** [comment]
I have the very same issue using Virtual Box and Red Hat 7.8 as the guest OS. Using VS Code version 1.44.2. The only way to make it stable is to open it with `code --disable-gpu -a`

**Comment by danogburn** [comment]
I'm having this same issue with a centos 7 in a virtual box vm.  Opening right-click context menus will eventually crash the whole VM.

![image](https://user-images.githubusercontent.com/32211755/81246013-7d8e1380-8fe4-11ea-86c2-fcb0dbf99f1d.png)

**Comment by mathisgag** [comment]
Related?  #98924

**Comment by prjemian** [comment]
Yes.

**Comment by HasneinTareque** [comment]
Still experiencing the same crash when clicking VSCode menu on LinuxMint VM. VSCode menus turns black and the whole VM is crashed. Experienced each time tried to use the VSCode menu.

**Comment by studiozandra** [comment]
Ran into the same issue (although no crash dialog pops up) with Ubuntu 20 (guest) on Windows 10 with Virtual box. After losing many hours of work time to this, I found the [workaround here](https://www.reddit.com/r/vscode/comments/5iu2mq/does_vs_code_works_in_linux_inside_virtual_box/dbctmoq/?utm_source=reddit&utm_medium=web2x&context=3) but it doesn't seem to be a long term solution.

**Comment by mathisgag** [comment]
You should check out a more permanent fix [here](https://github.com/microsoft/vscode/issues/98924).
Until they fix it, it's the better we got.
P.S. Can you confirm it still works.

**Comment by studiozandra** [comment]
> You should check out a more permanent fix [here](https://github.com/microsoft/vscode/issues/98924).
> Until they fix it, it's the better we got.
> P.S. Can you confirm it still works.

no, it did not work for me, thanks anyway! I have finally switched to a dual boot machine.

**Comment by bongraster** [comment]
At least you can spend many hours to all the guys trying to work with Visual Studio Code And add a banner with All Red CAPS on the homepage stating that VirtualBox is not compatible with this app!

**Comment by bongraster** [comment]
Same issue - seems like dual boot is the solution

**Comment by vivekkarne** [comment]
Same issue when working with xubuntu on virtualbox, centos works fine.

**Comment by hello-smile6** [comment]
> Same issue when working with xubuntu on virtualbox, centos works fine.

Can you reproduce with v86? https://copy.sh/v86/

If you want to try with Arch, https://copy.sh/v86/?profile=archlinux&c=.%2Fnetworking.sh%3Bdate%20--set%3D%22%60hwclock%60%22%3B.%2Fstartx.sh

**Comment by deepak1556** [comment]
Closing as the upstream issues https://github.com/microsoft/vscode/issues/84745#issuecomment-561645280 have not gained any momentum. Please continue to disable hardware acceleration in VSCode for this specific setup as workaround.

**Comment by prjemian** [comment]
The upstream issues are cited [above](https://github.com/microsoft/vscode/issues/84745#issuecomment-561645280).
