### ISSUE TITLE
VS Code running slow on my machine

### ISSUE THREAD

**Issue by MrSiliconGuy** [microsoft/vscode#84743]
Issue Type: <b>Performance Issue</b>

VS Code seems to be running sluggishly on my machine. Text editing is fine, but things like debugging and reloading the window take more than 10 seconds to load and sometimes uses 30% of the CPU.

I've tried both on Windows and Linux on my machine (dual booted), I have also just recently un-installed and reinstalled a fresh copy of VS Code on Windows, deleting the folder containing extensions and user settings.

This has occurred in a recent update (<2 weeks ago), as VS Code hasn't run as slowly before.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   102	 41560	code main
    0	    13	 32072	   electron-crash-reporter
    1	    66	 33596	   window (Issue Reporter)
    0	    68	 40140	   shared-process
    0	   225	 40916	   gpu-process
    0	   218	 41568	   window (science_club_element_game.py - Science Club Element Game - Visual Studio Code)
    0	    14	 34252	     watcherService 
    0	    11	 29716	       console-window-host (Windows internal process)
    0	     6	 40388	     console-window-host (Windows internal process)
    0	    34	 40924	     searchService
    0	    78	 41088	     "C:\Program Files\PowerShell\6\pwsh.exe"
    0	    30	 43648	       "C:\Users\Bryan C\AppData\Local\Python\Python36\python.exe" "c:\Users\Bryan C\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py" --default --client --host localhost --port 64850 "c:\Users\Bryan C\GithubRepos\Python-Code\Random\Science Club Element Game\science_club_element_game.py"
    0	    95	 43884	     extensionHost
    0	    33	 38368	       electron_node main.js 
    0	    41	 39880	       "C:\Users\Bryan C\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Bryan C\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=43884
    0	    41	 41508	       "C:\Users\Bryan C\AppData\Local\Python\Python36\python.exe" completion.py
    0	    22	  9076	         "C:\Users\Bryan C\AppData\Local\Python\Python36\python.exe" lib\python\jedi\evaluate\compiled\subprocess\__main__.py lib\python 3.6.4
    0	    11	 42256	           console-window-host (Windows internal process)
    0	    11	 37676	         console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (science_club_element_game.py - Science Club Element Game - Visual Studio Code)
|    Folder (Science Club Element Game): 5 files
|      File types: json(2) csv(1) py(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: python(6);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
nightswitch-lite|gha|2.2.2
python|ms-|2019.10.44104
remote-wsl|ms-|0.40.2

</details>

**Comment by MrSiliconGuy** [comment]
[Process Explorer during python debugging and reloading window](https://imgur.com/a/6H7OrNM)

**Comment by davalapar** [comment]
Same on windows 7 x64 with 8gigs of ram, I'm getting a steady 35% usage even if I'm doing friggin nothing.

**Comment by AlbertoBonfiglio** [comment]
My VS Code is also been running slowly for the past couple of days. I found out somehow it instantiates several rg.exe which take 30 to 40% of cpu each.I had to disable a few extensions (one of which was liveServer) to make it workable again. Not sure if it's related but the timing is suspicious.

**Comment by rebornix** [comment]
Thanks for reporting the issue, could you please follow our wiki to provide more info https://github.com/microsoft/vscode/wiki/Performance-Issues ?

**Comment by rebornix** [comment]
@AlbertoBonfiglio thanks, can you share which extensions you disable to make VS Code fast again?

**Comment by AlbertoBonfiglio** [comment]
@rebornix LiveServer was spawning 2 instances of  rg.exe. 
.NET Core Test Explorer also was spawning an rg.exe consitetly with cpu usage of 60%
 Now only occasionally i get an rg instance getting spawned.  
The behavior was common in both the regular (latest) and insider versions of VScode on Windows 10. The rg version is 11.xx i believe 
It would be cool to know how to find out which extension spawns what, without having to disable all and re enable them, one by one.

**Comment by AlbertoBonfiglio** [comment]
@rebornix 
Actually the problem still occurs. Also the rg.exe seems to stay even after vs code is closed..
See capture 1 (insiders) and 2 (latest)

![Capture1](https://user-images.githubusercontent.com/15167415/68881329-c9a96c80-06c1-11ea-9d27-b97f93a89150.PNG)
![Capture2](https://user-images.githubusercontent.com/15167415/68881330-c9a96c80-06c1-11ea-9877-6edce2b30c65.PNG)

**Comment by AlbertoBonfiglio** [comment]
Ok, Sorry for the many messages. the extension Gruntfuggly/todo-tree was running a riprep and once i excluded many folders it seems to have fixed the issue for me.
    "todo-tree.filtering.excludeGlobs": [
        "**/vendor/**",
        "**/node_modules/**",
        "**/dist/**",
        "**/bower_components/**",
        "**/build/**",
        "**/.vscode/**",
        "**/.github/**",
        "**/_output/**",
        "**/*.min.*",
        "**/*.map"
    ],

**Comment by MrSiliconGuy** [comment]
@rebornix 

After further testing, the issue seems to be the biggest while starting up the application. It doesn't seem to be occuring from any extension.

Here is a [Google Drive folder](https://drive.google.com/drive/folders/1xYAWthQmxDBfUz95u-hVurxSDdaK15Ls?usp=sharing) with some hopefully useful information.

**Comment by rebornix** [comment]
For @MrSiliconGuy 's issue, it seems GPU is running really hard when VS Code is opened, you can probably try disabling GPU optimization by `code --disable-gpu`

@AlbertoBonfiglio please file issues against those extensions, which are responsible for those rg.exe processes, thanks!

**Comment by AlbertoBonfiglio** [comment]
@rebornix I am starting to wonder if it isn't the extensions. I use settings sync to keep my setings updated between machines. On my windows box i have the regular and the insiders editions both synced and therefore with identical settings and extensions. When i open a project with the regular rg.exe executes quickly and disappears. When I open the same project (or any project) with insiders the rg.exe loads and persists in memory with high COP use

**Comment by MrSiliconGuy** [comment]
I will add another comment.

I have installed VSCode on Linux, and it's running fine.

Meanwhile, it seems like other applications that use a blink-based rendering engine seem to be slow too.
i.e Discord seems to be slower than usual, chrome is taking longer than before to start up.

Basically I don't think the root problem is something with VSCode, it's probably some sort of configuration on my machine that is messed up.

**Comment by MrSiliconGuy** [comment]
@AlbertoBonfiglio I think your issue is different from mine, because I don't have any like rg.exe running, either in the VSCode process manager nor Windows task manager.

**Comment by DarthBert** [comment]
@MrSiliconGuy Yeah, looks like. I will probably open a new issue. Thanks!
