### ISSUE TITLE
Visual Studio Code not working

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#84747]
I just installed Visual Studio Code and it does not seem to work even a small bit. It starts and open up like a black screen not showing anything other than plain and blank pages. I tried clicking on various options and menus but nothing seems to work. Screenshot of the issue is attached with this 
![Screenshot from 2019-11-13 16-20-10](https://user-images.githubusercontent.com/55215422/68813017-c49cdc80-0631-11ea-98a3-42509c86abb4.png)

**Comment by europaisch** [comment]
Try opening the terminal and launching it like this:
`code --disable-gpu`

**Comment by rebornix** [comment]
@iaxat can you try the suggestion above?

**Comment by iaxat** [comment]
I did try it did not work

**Comment by deepak1556** [comment]
@iaxat does the problem exit with latest stable 1.40.2 ? Can you launch with `code --verbose` from terminal and attach the log. Thanks!
