### ISSUE TITLE
laggy terminal on high contrast color theme [1.40.1]

### ISSUE THREAD

**Issue by rafmsou** [microsoft/vscode#84749]
It also occurs on the insiders release.

Steps to Reproduce:

1. Enable high contrast color theme
2. Open up integrated terminal and run any command that will output more than one page (so the scroll bar is visible)

The integrated terminal and the editor becomes laggy, it takes some time for typed letters to render. It's almost impossible to work with. 

Version info:
```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by rafmsou** [comment]
> Can you share your settings.json file?

```
// Place your settings in this file to overwrite the default settings
{
    "workbench.colorTheme": "Default High Contrast"
}
```

**Comment by rafmsou** [comment]
@Tyriar It looks like it got fixed in the insiders release today.
