### ISSUE TITLE
Fix $msCompile regex to match Microsoft C++ Compiler messages

### ISSUE THREAD

**Issue by db4** [Microsoft/vscode#8474]
- VSCode Version: 1.2.1

The fix is rather trivial: in `problemMatcher.ts` replace `msCompile` regex
```
/^([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\):\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$/
```
with
```
/^([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$/
```
BTW, what predefined pattern is expected to be used with MSVC compiler? `msComplie` or `cpp`? If the latter, `cpp` regex should fixed instead.

**Comment by dbaeumer** [comment]
Thanks. The msCompiler pattern is used for MS compilers including C/C++.
