### ISSUE TITLE
When pasting, formatting indents way to the right

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode#84757]
Issue Type: <b>Bug</b>

I paste the comment, the entire block of code indents. Then I save the file and it formats properly. See image 

VS Code version: Code - Insiders 1.41.0-insider (c408a2c02d78982b1f83819c587c02bb59af9f93, 2019-11-13T06:24:06.004Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|-psn_0_15879972|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
vscode-browser-preview|auc|0.5.9
spellright|ban|3.0.48
lit-html|bie|1.11.1
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
prettier-vscode|esb|3.5.0
vscode-pull-request-github|Git|0.13.0
angular-essentials|joh|0.6.3
Angular1|joh|0.2.1
Angular2|joh|8.1.1
read-time|joh|0.2.0
vscode-peacock|joh|3.2.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.157.4
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.20.0
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
remote-containers|ms-|0.84.0
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cloudenv-extensions|ms-|1.0.1173
vsliveshare|ms-|1.0.1123
vsonline|ms-|1.0.1214
debugger-for-chrome|msj|4.12.1
angular2-inline|nat|0.0.17
angular-console|nrw|9.0.0
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.1
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

![format-issue](https://user-images.githubusercontent.com/1202528/68821250-d1cec100-065b-11ea-9a51-46f454ec5c18.gif)

![format-issue](https://user-images.githubusercontent.com/1202528/68821268-e0b57380-065b-11ea-97ca-42b2a76c5dad.gif)

**Comment by Grsmto** [comment]
Enabling `esbenp.prettier-vscode` as a formatter in the setting was causing this issue to happen to me.

**Comment by rebornix** [comment]
The indentation rules in VS Code are regex based and not sound, you can turn it off by `editor.autoIndent` and use formatters for that purpose.
