### ISSUE TITLE
fontAliasing antialiased doesn't work for canvas terminal

### ISSUE THREAD

**Issue by wlchn** [microsoft/vscode#84758]
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.2.0

I set `antialiased` font and `canvas` terminal as below, It doesn't work for the canvas terminal
```
  "workbench.fontAliasing": "antialiased",
  "terminal.integrated.rendererType": "canvas",
```
When I change `canvas` to `dom`, it looks working well.

`canvas` terminal, `antialiased` doesn't work:

![image](https://user-images.githubusercontent.com/4652410/68822446-e5b20b80-06cb-11ea-81cf-89bd41d82b85.png)

`dom` terminal,  `antialiased` works:

![image](https://user-images.githubusercontent.com/4652410/68822476-f82c4500-06cb-11ea-905d-eaffa116371f.png)
You could see the difference. And `antialiased` has no effect on `canvas` terminal.

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/2464

/duplicate
