### ISSUE TITLE
code .rpm package failing update. Needs to be signed

### ISSUE THREAD

**Issue by alxmel** [microsoft/vscode#84752]
Updating the **.rpm** package `code` on **Fedora 31** fails because the package is not signed.

`cat /etc/yum.repos.d/vscode.repo` output:

```
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```

`dnf update code` output:

```
========================================================================================================================================
 Package                    Architecture                 Version                                       Repository                  Size
========================================================================================================================================
Upgrading:
 code                       x86_64                       1.40.1-1573664332.el7                         code                        78 M

Transaction Summary
========================================================================================================================================
Upgrade  1 Package

Total download size: 78 M
Downloading Packages:
code-1.40.1-1573664332.el7.x86_64.rpm                                                                   7.8 MB/s |  78 MB     00:09    
----------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                   7.8 MB/s |  78 MB     00:09     
Package code-1.40.1-1573664332.el7.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by wtagnew** [comment]
Same problem here for initial install, holding off...

**Comment by wotmshuaisi** [comment]
try `sudo dnf upgrade code --nogpgcheck`

**Comment by lxbarbosa** [comment]
same here, unable to install code

Fedora 31 Mate
Lenovo T430

**Comment by tristan957** [comment]
Workaround works @wotmshuaisi . Hopefully it doesn't bite me in the butt :P

**Comment by TheCedarPrince** [comment]
Can confirm the issue is not yet resolved - running Fedora 30 KDE Plasma Spin. Had to use @wotmshuaisi's method but this is not a solution I want to be using...

**Comment by PauloBoaventura** [comment]
Thank you after a good search ...
I found you guys ..
The same day ... kk
So thanks for the help @wotmshuaisi

**Comment by ender672** [comment]
Rather than skipping the gpg check, I recommend skipping the vs code update until this is fixed:
`$ sudo dnf update -y --exclude "code"`

**Comment by adhisimon** [comment]
I confirm this on Fedora 31

**Comment by danielsun3164** [comment]
I am using Fedora 30 and got the same error.

**Comment by yogdutt** [comment]
Same problem on CentOS Linux release 7.7.1908 (Core)

**Comment by netsensei** [comment]
Fedora 30. I'm seeing the same error.

**Comment by aweibell** [comment]
I installed the previous version. I assume there will be a new signed version out quite soon?
`sudo dnf install code-1.40.0-1573064644.el7`

**Comment by crash1013** [comment]
Same issue, I will wait for the signed package

**Comment by pizzadude** [comment]
same issue

**Comment by NicoGim** [comment]
For those of you who, like me, thought it was smart to uninstall Visual Studio Code before upgrading it, because for some reasons you couldn't get "yum update" to work, and you don't want to install unsigned package on your computer, browse this site directly:
https://packages.microsoft.com/yumrepos/vscode/
Download code-1.40.0-1573064644.el7.x86_64.rpm, it's the version just before the latest one, it is signed and works well.

**Comment by natiiix** [comment]
Still an active issue on `Linux 5.3.9-300.fc31.x86_64 Wed Nov 6 16:13:19 UTC 2019 x86_64 GNU/Linux (Fedora 31)`

It's quite surprising that sometimes like this happens to Microsoft. You'd think they have a CI/CD set up that would prevent an unsigned package from getting into production repositories.

**Comment by fierg** [comment]
I am using Fedora 30 and got the same error.

**Comment by ricardojohnny** [comment]
Updating the .rpm package code on Fedora 31 fails because the package is not signed.

cat /etc/yum.repos.d/vscode.repo output:

```
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```
change value for _gpgcheck=0_ and update now!

**Comment by pizzadude** [comment]
@ricardojohnny Bad security practice.

**Comment by Dusty211** [comment]
Signed software exists for a reason.  All of the workarounds assume it was a mistake (which it probably was), but by circumventing the GPG check you are essentially taking food from a total stranger and eating it. Best of luck with that, but the best answer on here is Ender672's answer of skipping the update until this is fixed properly.

**Comment by lxbarbosa** [comment]
devs should listen random 'advices' about security... just like the ones installing npm and pip packages with sudo.

**Comment by mzabaluev** [comment]
> but by circumventing the GPG check you are essentially taking food from a total stranger and eating it.

There is a level of trust in the repository being served by an https: URL. So, _provided that_ dnf/yum properly validates the TLS certificate, or if you validate it yourself while downloading the package by other means, you can be sure that the repository server is at least nominally controlled by Microsoft. 
This is, of course, weaker than proof that the package is signed by the official GPG key of the release team.

**Comment by Dusty211** [comment]
Ok, my metaphor stands corrected. The person is verified, but the food is not. All the TLS certificate proves is that it came from a verified authentic URL.  The code itself can still be compromised. All the ins and outs can be debated, and yeah, it's probably a mistake, but it is bad practice and there is no real reason to trust the update when you can just ignore this version in dnf or if you need to install it from scratch, specify an earlier GPG verified version.

**Comment by mario-d-s** [comment]
As @natiiix mentions above you would expect signed packages coming off a CI server especially from a large organisation like Microsoft who has abundant resources to ensure this.

That is also the **very reason** I don't feel comfortable skipping the GPG check - call me paranoid but this is quite the red flag in my opinion.

**Comment by NicoGim** [comment]
@mario-d-s while I understand that the point is to make sure you get the actually binaries validated by Microsoft, and nobody else, and that's all what this GPG check is about, the only way to make sure you're not running a malware/spyware if you're really paranoid would be to use a free (as in freedom as opposed to OSS) alternative to Visual Studio Code. But VS Code is MIT+proprietary so to be fair, we can't _really_ know what's in there. At the end of the day it's all about trust.

**Comment by mario-d-s** [comment]
@NicoGim absolutely, that is a fair and valid point. Of course, I still trust "genuine Microsoft" over "random binary (as far as we know)" :)

**Comment by Zaya6** [comment]
Getting this error on fedora 31 as well, thanks for the workaround @wotmshuaisi

**Comment by W3SS** [comment]
> skip gpg check for now, hopefully next time they don't forget to sign their package
> try **sudo dnf upgrade code --nogpgcheck**

Thanks @ender672

**Comment by Dusty211** [comment]
> > skip gpg check for now, hopefully next time they don't forget to sign their package
> > try **sudo dnf upgrade code --nogpgcheck**
> 
> Thanks @ender672

That was not @ender672 's post.  The consensus of the current discussion is that that command is bad security practice.  ender672 recommended a different command that is the safe way to go until this potential security vulnerability is fixed. Please be careful people, and know what you are doing.

**Comment by clairtonluz** [comment]
Only import cert again
`sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc`

the command above I copy from [https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)

its works  to me

**Comment by mzabaluev** [comment]
It seems resolved with no package version change, just the repo update.

**Comment by bsidhipong** [comment]
If a package is stopping you from updating your system with the typical "dnf update", then please by all means "--exclude" it.  Excluding a package allows the update process to continue while Microsoft figures out what went wrong.  In all likelihood they just forgot to sign it, as difficult as it is to believe.  In the worst case, somebody put malicious code in the Visual Studio repo and y'all just blindly install it ignoring the GPG signature ... that's not worth it.

**Comment by RMacfarlane** [comment]
I've removed the unsigned version of the package and am working on publishing a signed version. Sorry everyone, thanks for your patience

**Comment by crash1013** [comment]
It's working as it should for me now., To complete my Fedora 31 upgrade earlier I just did this
**sudo dnf --disablerepo code upgrade**
I changed disablerepo to enablerepo after the GPG signature was in the package
A good exercise for me, I learned that dnf repos are in /etc/yum.repos.d and not /etc/dnf/dnf.conf directory and not dnf.conf.

**Comment by RMacfarlane** [comment]
Signed 1.40.1 should be available now.

**Comment by TheCedarPrince** [comment]
@RMacfarlane - this works. Thanks!

**Comment by PauloLaScience** [comment]
@RMacfarlane Working fine on Fedora 31
Many thanks for quick reaction!
