### ISSUE TITLE
Vscode config tab size is turned back on and reset

### ISSUE THREAD

**Issue by XiaoLiz** [microsoft/vscode#84750]
- VSCode Version:  October 2019 (version 1.40)
- OS Version:  MacOS Catalina 10.15.1 (19B88)

Steps to Reproduce:

1. Setting config Tab Size(spaces) to 4  and save file
2. Open the file again, Tab size is reset spaces to 2

Does this issue occur when all extensions are disabled?: Yes

**Comment by XiaoLiz** [comment]
Thank you very much for your reply！In order to avoid the coverage problem, I turned off the vscode indent indent autodetections
 
settings.json configuration：
```json
{
    "editor.detectIndentation": false,
    "editor.minimap.enabled": false
}
```

The final solution is to configure the third-party detection tool .editorconfig

```editorconfig
# top-most EditorConfig file
root = true
[*]
charset = utf-8
indent_style = space
indent_size = 4
end_of_line = lf
```

**Comment by XiaoLiz** [comment]
For configuration replication, I think it is a bug in vscode.

**Comment by rebornix** [comment]
`editor.detectIndentation` overrides the indentation setting you picked in a session, so when the workspace is reloaded, VS Code will detect the indentation again.
