### ISSUE TITLE
Decide which extension should be actively recommended

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8476]
@seanmcbreen pls chime in:

Current list:
- C#
- Go

## checked in list
- C#
- Go
- C++
- python
- powershel

**Comment by seanmcbreen** [comment]
Python
C++
PowerShell

Less Important but we can guess of file type
EditorConfig
Linter config files e.g. eslintrc

**Comment by egamma** [comment]
@jrieken @seanmcbreen please verify.

**Comment by egamma** [comment]
@seanmcbreen when verifying you must install a recently built insiders build.
