### ISSUE TITLE
No ssh installed extnesions were found in insiders

### ISSUE THREAD

**Issue by zsddyd** [microsoft/vscode#84769]
Issue Type: <b>Bug</b>

Download the extension "Remote - SSH" and connect to my server, but there is no my own installed extensions in the EXTENSION bar.
What is more, the extensions works and display well in vscode stable version.

VS Code version: Code - Insiders 1.41.0-insider (c408a2c02d78982b1f83819c587c02bb59af9f93, 2019-11-13T06:25:23.355Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zsddyd.top|
|OS|Linux x64 4.15.0-52-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz (1 x 2500)|
|Memory (System)|1.95GB (0.61GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vsc-material-theme|Equ|30.0.0
vscode-language-pack-zh-hans|MS-|1.40.2
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
material-icon-theme|PKi|3.9.1
code-settings-sync|Sha|3.4.3
matlab-complete|Sla|1.0.3
file-icons-mac|way|1.0.1

(4 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
You will have to install extensions on your remote after connecting to it. I assume that's what you mean. Give some more details if not.
