### ISSUE TITLE
Add option to restart VSCode

### ISSUE THREAD

**Issue by kaosaxis** [microsoft/vscode#84760]
Searched but query returned previous results ?!

Currently, if you make some environment change you'll have to exit and reload or hope that VScode has an update to be presented with the option to reload VSCode. It would be nice if there was an option under help that had a static "Restart VSCode". It could be helpful if something isn't working right to be able to reload it.

Thank you for your consideration.

**Comment by faabiopontes** [comment]
Hello @kaosaxis !

What version of VS Code are you using? On older versions you had indeed to restart manually after installing extensions. But since 1.37, I guess, VS Code doesn't need to restart anymore in most of the changes..

You are referring to what use cases?..

**Comment by alvitawa** [comment]
It is a basic feature, even if it is not supposed to be necessary, restarting solves 90% of bugs (short term).
