### ISSUE TITLE
GPG check FAILED 

### ISSUE THREAD

**Issue by faezebax** [microsoft/vscode#84762]
I did a system update on my fedora machine via `sudo dnf upgrade` and noticed an update came out for VSCode, But it says:
```
Package code-1.40.1-1573664332.el7.x86_64.rpm is not signed
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by faezebax** [comment]
duplicate #84753

**Comment by ekremkaraca** [comment]
@faezebax why not just redirecting to #84752?
