### ISSUE TITLE
editorLineNumber.activeForeground not working

### ISSUE THREAD

**Issue by oyasin** [microsoft/vscode#84772]
- VSCode Version: 1.40.1
- OS Version: OSX Catalina

Steps to Reproduce:

1. Set  "editorLineNumber.activeForeground": "#27e8a7ff", or any colour you want.
2. the active line number does not change colour.

Does this issue occur when all extensions are disabled?: Yes
<img width="633" alt="Screen Shot 2019-11-14 at 7 22 55 AM" src="https://user-images.githubusercontent.com/50802294/68828799-9c53c300-06af-11ea-9cd5-814ef25e8cc5.png">

**Comment by rebornix** [comment]
Currently `activeLineNumber.activeForeground` applies only when `editor.renderLineHighlight` is set to `all` or `gutter`.

**Comment by yoyoys** [comment]
same on 10.14.6 (Mojave)

**Comment by rip3rs** [comment]
This should be added on the documentation.
https://code.visualstudio.com/api/references/theme-color

Or be more prominent so that people don't go everywhere to find this specific issue :)

**Comment by VideoPlayerCode** [comment]
Thanks for this ticket. I upgraded VSCode and noticed that the highlight stopped working. Thanks @rebornix for clarifying that an extra setting is needed now.

**Comment by VideoPlayerCode** [comment]
Uhm... I spoke too soon. `"editor.renderLineHighlight": "all",` does bring back the highlight but it seems like a downgrade from earlier VSCode versions. Pretty sure earlier versions did not make the highlight box cover the line AND the gutter. I think it used to highlight the line number via color, and only draw the highlight-box within the code area. Oh well I'll use the `all` mode for now...

**Comment by just-joshing** [comment]
Thanks @rebornix for the note about the extra setting.

I've been having a lot of difficulty lately figuring out what line my cursor jumps to when I use ctrl+f to find text in my code. Now my highlight color is back.

I can't figure out what renderLineHighlight is changing though. Might be my theme, but I don't see anything change no matter which setting I pick for it.

**Comment by Eldaw** [comment]
I agree with @VideoPlayerCode. I can't stand 'all' for the "editor.renderLineHighlight" setting. Things were much better the way they were before. I'm not happy that @rebornix closed the separate issue I created, https://github.com/microsoft/vscode/issues/86840, as if the matter is now settled.

**Comment by Eldaw** [comment]
I hope the bold line number can be brought back soon. I miss it.

**Comment by Eldaw** [comment]
@rebornix Thanks for implementing this in v1.52.0. Unfortunately, there is a small bug relating to when the caret is on Line 1. I've created a new issue for that, https://github.com/microsoft/vscode/issues/112353
