### ISSUE TITLE
Weird one column rendering when opening new file (IE10)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8477]
Ref: #8229

1. IE10, https://microsoft.github.io/monaco-editor/index.html
2. Notice how for a short period of time all text is rendered weirdly in one column

![onecolumnrender](https://cloud.githubusercontent.com/assets/1926584/16444185/29e37002-3ddd-11e6-9150-5916cb8bab37.gif)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#152

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
