### ISSUE TITLE
Clarifying Code as VS Code in readme

### ISSUE THREAD

**Issue by waterpolymer** [microsoft/vscode#84770]
I was looking through the readme and [some of the other documentation](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run) for Visual Studio Code and noticed how it flip-flops between calling itself Code and alternatively VS Code. The inconsistency is a little confusing and I think Code alone is a little too ambiguous. I believe it would be more clear to consistently refer to itself as VS Code in documentation.

**Comment by gregvanl** [comment]
@waterpolymer I've updated the How to Contribute wiki page as well. Thanks for pointing this out.
