### ISSUE TITLE
when do update vs code not open

### ISSUE THREAD

**Issue by mwbexpert** [microsoft/vscode#84779]
Issue Type: <b>Bug</b>

when do update vs code not open
it's load many time and finaly say not respone
when uninstall then re install old version work
new update has bug

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (6.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular-BeastCode|Mik|8.0.10

</details>

**Comment by rebornix** [comment]
@mwbexpert can you try our latest version 1.40.1 to see if you can still reproduce this issue? Currently the version 1.35.1 you are using is an old one.
