### ISSUE TITLE
Japanese fallback font is changed on Windows

### ISSUE THREAD

**Issue by ichi-kotobuki** [microsoft/vscode#84774]
- VSCode Version: 1.40.1 (system setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Install Visual Studio Code version 1.39.2 and input Japanese text on Windows.
![VSCode139](https://user-images.githubusercontent.com/47664578/68829438-3cc7d880-06ec-11ea-9539-7502a62b034e.png)

2. Update Visual Studio Code version 1.40.0 or 1.40.1 and input Japanese text on Windows.
![VSCode140](https://user-images.githubusercontent.com/47664578/68829466-52d59900-06ec-11ea-8790-ce7d0398e1a8.png)

On Windows, Japanese fallback font is Meiryo with default font settings on version 1.39.2 or earlier. But, that is suddenly changed to MS Gothic on version 1.40.0. This is unwanted behavior.

**Comment by octref** [comment]
@ichi-kotobuki This is an intended change. Can't you configure the font to whatever font you want with `editor.fontFamily`?

**Comment by ichi-kotobuki** [comment]
Oops, sorry! I understand that. And I tried to configure `editor.fontFamily` setting, then it works well for me!
