### ISSUE TITLE
Switching from another window to the VS Code will appear blank.

### ISSUE THREAD

**Issue by nailao** [microsoft/vscode#84775]
- VSCode Version: 1.40.1
- OS Version: Windowns 7

Steps to Reproduce:

![2019-11-14](https://user-images.githubusercontent.com/19665552/68830784-a2fe2c80-06e7-11ea-98bb-a0c50da76f8c.gif)

Switching from another window to VS Code will appear blank and will need to wait for more than 1 second. It used to be normal until I updated to 1.40.

**Comment by rebornix** [comment]
It's a duplicate of https://github.com/microsoft/vscode/issues/84656 , but with recording.

**Comment by deepak1556** [comment]
You can use `"window.titleBarStyle": "native"` as a temporary workaround.
