### ISSUE TITLE
Selection not displayed properly (IE10)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8478]
Ref: #8229

1. IE10, https://microsoft.github.io/monaco-editor/index.html
2. Try to select something and notice how selection is not working

I have selected everything from line 5 to 18 in this example: 

![screen shot 2016-06-29 at 09 39 41](https://cloud.githubusercontent.com/assets/1926584/16444244/6f79a974-3ddd-11e6-934f-c12cef1c8ad9.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#153

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
