### ISSUE TITLE
Allow copy/paste to work in Release Notes

### ISSUE THREAD

**Issue by PaulPCIO** [microsoft/vscode#84781]
Issue Type: <b>Bug</b>

This issue relates to https://github.com/microsoft/vscode/issues/32524

**Steps to Reproduce:**
- Open a Release Note
- Select some text
- copy (cmd + c)

**Expected Results:**
Should copy the selected text to allow and paste where needed

**Actual Results:**
I can't copy any content/text inside release notes
There is no context menu
Same issue in extensions

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
cmd+c works for me. Is this just the context menu?

**Comment by PaulPCIO** [comment]
It seems to be fixed in the last Release Notes, still the same problem in the extension page.

![copy from extention](https://user-images.githubusercontent.com/39598117/69939186-829fe180-14df-11ea-87b1-b0b91ddb3359.gif)
