### ISSUE TITLE
"Go to Symbol" with the exact method name doesn't work as expected

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#84787]
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.Open a file with any extension with following methods (get(), getSomethingElse(), getAnotherThing())
2.Execute the command "Go to Symbol in File..." (in my case Ctrl+R)
3. type ":" (colon after "@") such that the final string is "@:get"
4. Editor doesn't scroll to the method "get()"
5. Remove ONE caracter from the search string so you have "@:ge"
6. Editor correctly scrolls to the start of the "get()" method

Note: it happens with any methods with the same prefixes, for instance: 3 methods "set(), setThing1(), setThing2()... etc" wont scroll to "set()" if I wrote "@:set"

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
to verify:

* have the TS snippet below
* open quick outline and type `@:get`

```ts
class Hello {
    get(){} 
    getSomethingElse(){}     
}
```
