### ISSUE TITLE
VS Code slow on large project 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#84784]
There is a very interesting blog post [Switching back to my old buddy Sublime Text from VS Code](https://dev.to/teamxenox/switching-back-to-my-old-buddy-sublime-text-from-vs-code-57mp) from @sarthology. It mentions that:

>...while we were working on a big old project... and I found out that the culprit was VS Code.

I'd like to find out more about the structure of this project. From the screen shot in the blog it looks like it is a TS project. @sarthology could you please run `code --status` from a command prompt while you have your project in VS Code opened. This command dumps the running processes and some statistics about your workspace.

We have several settings that help to tune the setup to increase scalability. @sarthology have you tried one of these?

`files.exclude` - allows to hide files from the explorer, for example, this is how we have it configured for the VS Code project. This can be used to exclude generated assets from the explorer:

```json
	"files.exclude": {
		".git": true,
		".build": true,
		"**/.DS_Store": true,
		"build/**/*.js": {
			"when": "$(basename).ts"
		}
	},
```

`files.watcherExclude` - allows to exclude files/folders from file watching, for example:

```json
	"files.watcherExclude": {
		"**/.git/objects/**": true,
		"**/.git/subtree-cache/**": true,
		"**/node_modules/**": true
	},
```

We need to make sure that we cover these 'large projects' settings in our documentation.

**Comment by sarthology** [comment]
Hey @egamma, They helped to some extent but could only do so much.  I appreciate your gesture and as a long-time VS Code user, I hope we can help make it run even better on older systems.

Btw that's the output

```
Version:          Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS Version:       Darwin x64 19.0.0
CPUs:             Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)
Memory (System):  4.00GB (0.05GB free)
Load (avg):       14, 8, 7
VM:               0%
Screen Reader:    no
Process Argv:     .
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    5       33    3967  code main
   22       20    4003     gpu-process
    6       66    4004     window (show-my-task.component.ts — causeBox)
    1       33    4010       extensionHost
    0        4    4019         /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=4010
    0       37    4020         electron_node tslintServer.js 
    0        4    4040         electron_node server.js 
    0        8    4685         electron_node tsserver.js 
   31       90    4686         electron_node tsserver.js 
    0       16    4689           electron_node typingsInstaller.js typesMap.js 
   35       90    4694             npm
    0        4    4012       watcherService
    0        4    4027       searchService
    0        4    4071       /bin/zsh -l
    0        0    4696         bash /usr/local/bin/code --status
    0       16    4706           electron_node cli.js 
    4       20    4007     shared-process
    0        0    4713       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (show-my-task.component.ts — causeBox)
|    Folder (causeBox): 975 files
|      File types: ts(295) js(123) html(94) scss(92) svg(57) png(29) jpg(24)
|                  json(22) DS_Store(14) otf(14)
|      Conf files: tslint.json(4) package.json(3) tsconfig.json(2)
|                  settings.json(1)
```

**Comment by egamma** [comment]
@sarthology thank you very much for following up 🌷 

I assume you ran the command right after start-up of the project and not when VS Code was performing poorly?

Can you please also include the list of extensions you are running `code --list-extensions`? It would also be interesting whether one of these extensions contributes to the slowness. 

From the process tree it looks like you are using the older version of the tslint extension which accounts for 37MB. 
![image](https://user-images.githubusercontent.com/172399/68932686-6982fb00-0793-11ea-9caf-d6ad9f2d97ce.png)

The new [tslint extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) runs as TypeScript plugin and should consume less memory. 

It also looks like you have the TypeScript syntax server enabled, this is why you have 2 TS Servers
![image](https://user-images.githubusercontent.com/172399/68932862-c1b9fd00-0793-11ea-8d29-b998f21badf0.png)

You can disable the syntax server in the settings:
![image](https://user-images.githubusercontent.com/172399/68932804-a5b65b80-0793-11ea-8628-5875532ae5c7.png).
