### ISSUE TITLE
Force outline update button or faster automatic update of outline

### ISSUE THREAD

**Issue by canigia72** [microsoft/vscode#84780]
Hi,

I've frequently trouble that for source files (typically C++) the outline was present, and after slight modification or in between switch to another editor it vanishes with the note "The active editor cannot provide outline information". Sometimes after minutes it will come back. For efficient coding I actually don't want to wait minutes (or longer) for the symbols (most of the times fast navigation to function definitions to quickly navigate through the code). Other editors like geany display symbols instantaneously. 

So I'd like to request a better/faster update of the outline, perhaps with a force re-scan option.

Cheers and thanks, Klaus

My vscode version 1.40 on linux

**Comment by jrieken** [comment]
Yeah, it's not on VS Code but its the c/cpp extension that's slow.
