### ISSUE TITLE
Web: text colors look dimmed in firefox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84786]
As reported in https://github.com/microsoft/vscode/issues/84557#issuecomment-553772028 looks like we do not support LCD rendering in Firefox. Possibly our tricks are not working there.

//cc @alexandrudima

**Comment by bpasero** [comment]
Adding help wanted label if someone wants to chime in and diagnose.

**Comment by bpasero** [comment]
@andreyjamer I just gave latest Firefox on Windows a try for the web version of VSCode and I see perfect LCD-AA in all parts:

![Screenshot 2019-11-15 at 10 05 14](https://user-images.githubusercontent.com/900690/68930864-946b5000-078f-11ea-9e71-78c42095cfe7.png)

What are you seeing?

I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net

Does the issue reproduce in that setup in the browser?

**Comment by andreyjamer** [comment]
The problem is not with text. The problem is with colors of text.
Firefox has pale colors in comparison with Chrome. See screenshot:
![chrome_vs_firefox](https://user-images.githubusercontent.com/5379101/68932996-91835600-07b5-11ea-9d0d-abe36034526c.png)

Also you can try by yourself. Just open VS Code in Chrome and Firefox and compare side-by-side.
The colors looks exact the same as they were in desktop VS Code before fixes for #84557

**Comment by bpasero** [comment]
I do not see any difference:

![image](https://user-images.githubusercontent.com/900690/68939063-f92ea680-079f-11ea-9e35-f1a98796d43a.png)

![image](https://user-images.githubusercontent.com/900690/68939103-0f3c6700-07a0-11ea-9c18-a8241e875e2a.png)

Is this on Windows? Are you running latest?

**Comment by andreyjamer** [comment]
Yes, Windows.
I checked using https://vscode-web-test-playground.azurewebsites.net/?enter=true

**Comment by bpasero** [comment]
Weird, I cannot explain that.

**Comment by bpasero** [comment]
Can you report this to them?

**Comment by andreyjamer** [comment]
I do not understand.
To whom? To Firefox team?

**Comment by bpasero** [comment]
@andreyjamer yes, to understand why in your case FF decides to render greyscale and for me it works with LCD. This makes me think that probably the bug exists on their end and not VSCode, would you agree?

**Comment by andreyjamer** [comment]
Yes. BTW what version of Firefox do you use?

**Comment by andreyjamer** [comment]
Oh, i found another interesting thing! The problem is connected with monitor.
I compared browsers on my Dell monitor and have problem with color. But after i moved windows to laptop monitor - there is no problem.

Seems like Firefox checks for the monitor color profile and breaks color.

**Comment by bpasero** [comment]
Ok so I think there is really nothing we can do then. Please go ahead and report it.

**Comment by andreyjamer** [comment]
Ok, thank you!
