### ISSUE TITLE
MInimize maximize window

### ISSUE THREAD

**Issue by pasiasach** [microsoft/vscode#84798]
Issue Type: <b>Bug</b>

The minimize maximize button does not work or when it works it doestn work as expected

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
Possible duplicate of #81102

**Comment by deepak1556** [comment]
Please follow the other issue for updates, thanks!
