### ISSUE TITLE
WIndows bar

### ISSUE THREAD

**Issue by pasiasach** [microsoft/vscode#84797]
Issue Type: <b>Bug</b>

My taskbar at windows 10 is set to autohide. With the new update when i am on vs code my taskbard doesnt show up

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by rebornix** [comment]
@pasiasach does it only happen with VS Code but not other applications?

**Comment by pasiasach** [comment]
Hello. I don't know the steps to reproduce this, because it happens randomly only in vs code.

**Comment by pasiasach** [comment]
I reproduced it. When the window is maximized the maximize minimize button is bugged. Hence, in order to exit full screen i double click the bar of the window. When i double click the bar the mentioned bug occures.

**Comment by eeasoftware** [comment]
This bug started happening to me within the last few days.  I know there was a recent update.  It is simple and reproducible every time.  Doesn't matter how many times I open/close vscode or other applications nor does it matter what order I open them or what combination they are opened in.

When my focus is on vscode (I have 3 monitors), the windows taskbar does not auto-pop-up.  When I focus on another application in a different screen or a different application in the same screen, doesn't really matter, I can unhide/auto-hide the task bar.

Specifically when vscode is focused and I'm working in it, the taskbar is hidden and will not show.  I can minimize, then maximize it, then it's available until I click to another application then back to vscode.  At that point it stops responding again.

vscode: 1.40.1
1 installed extension: PHP Tools for VS Code 1.0.4187
os: windows 7

If there is a setting I'm missing or something please let me know.  This just started recently.

Thank you.
