### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by pasiasach** [microsoft/vscode#84796]
Issue Type: <b>Bug</b>

WIth the new update i use tab and instead to create spaces it starts navigates to the menu.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have "Tab moves focus" in the status bar?
See details here https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping
