### ISSUE TITLE
October 2019 Recovery Endgame 2

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#84791]
#### Check list
- [x] Create a milestone `<Month> Recovery <year>` **owner**
- [x] Bump the version number **owner**
- [x] Include an issue 'update translations' **owner**
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Make rpm signing request **@Tyriar**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [x] Update the release notes and include a link to a query for the fixed issues @chrmarti
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows @Tyriar 
  - [x] OS X @mjbvz
  - [x] Linux @mjbvz
- [x] Sanity check of installable bits
  - [x] Windows 32 bit @aeschli
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @aeschli
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] OS X - @weinand
  - [x] Linux @chrmarti 
    - [x] deb package 64-bit 
    - [X] rpm package 64-bit 
    - [x] archives 
- [x] Publish website @chrmarti
- [x] Publish stable build @chrmarti
- [x] Publish rpm to repository manually @Tyriar 
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` @chrmarti

**Comment by gjsjohnmurray** [comment]
I wish the first item in every endgame got linked to the milestone.

In this case https://github.com/microsoft/vscode/milestone/109

 It would give me easier access via the pinned endgame issue, especially when I am using the mobile version of the GH site, which doesn't seem to offer a Milestones view of Issues.
