### ISSUE TITLE
Find all references window wrongly rendered (IE10)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8479]
Ref: #8229

1. IE10, https://microsoft.github.io/monaco-editor/index.html
2. Open typescript sample, find all references
3. Click on some found references on the side -> notice how the find all references window jumps and is wrongly rendered

![findallreferences](https://cloud.githubusercontent.com/assets/1926584/16444357/ed7b88ba-3ddd-11e6-810f-e7e2f3d5e71b.gif)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#154

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
