### ISSUE TITLE
[c#] No syntax colors in C# for usings out of namespace

### ISSUE THREAD

**Issue by vbfox** [Microsoft/vscode#848]
![2015-12-01 09_59_56-searchkey cs - rfq-hub - visual studio code](https://cloud.githubusercontent.com/assets/131878/11496467/5428b2b2-9812-11e5-8f87-30d22807d50e.png)

In the following code :

```csharp
using System.Linq;

namespace MyNamespaceIsFoo
{
    using System;
    
    public class SearchKey
    {
    }
}
```

`using System` get colored correctly but `using System.Linq` isn't.

*Version 0.12.2*

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#45

**Comment by aeschli** [comment]
Now tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/101
