### ISSUE TITLE
Custom title: enable LCD rendering

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84806]
`.monaco-workbench .part.titlebar` has sufficient things going on that:
* text within is not rendered with LCD 
* other layers that share with title bar get the same punishment

Some CSS rule inside the title bar is causing the text to render with non-LCD. Various reasons:
* transparent background
* overflowing elements
* z-index?
* zoom

This impacts Linux, Windows and Web but not macOS.

![image](https://user-images.githubusercontent.com/900690/68851793-d84e4e80-06d6-11ea-901b-3eeac8a2ef92.png)

//cc @alexandrudima

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/71ea9ad65172947e955745c514af153f86f8523e as a workaround that puts the title bar on its own layer so that other layers are not impacted.

**Comment by bpasero** [comment]
The culprit seems to be that we use a color with transparency whenever the title gets inactive. This will turn the layer into non-LCD rendering.

@aeschli can we find a different way of computing a transparent color that does not require the usage of transparency in CSS?

Refs:

```ts
export const TITLE_BAR_INACTIVE_BACKGROUND = registerColor('titleBar.inactiveBackground', {
	dark: transparent(TITLE_BAR_ACTIVE_BACKGROUND, 0.6),
	light: transparent(TITLE_BAR_ACTIVE_BACKGROUND, 0.6),
	hc: null
})
```

**Comment by bpasero** [comment]
@sbatten I had to [revert](https://github.com/microsoft/vscode/commit/71107e37e8bb494f9223ed6490b24cf2fba6bff8) the layer promotion because if I do that, I can no longer click any menu item to show the menu. Unclear to me how that is possibly, maybe you could have a look and then revert my [revert](https://github.com/microsoft/vscode/commit/71107e37e8bb494f9223ed6490b24cf2fba6bff8).

**Comment by sbatten** [comment]
@bpasero took some experimentation but it looks like creating the new layer locks in z-index below the rest of the workbench so no matter what you set on child elements it has no effect. the change I made pushes the titlebar up one level meaning everything inside of it will always be at 1 relative to anything outside of the titlebar.

I tested with custom modal dialogs and context menus and the only major change is that the window controls (min, max, close) will not be accessible when a custom modal is present. This is the same as native so it could be argued correct, but I used to let them be accessible for convenience.

**Comment by bpasero** [comment]
@sbatten thanks, however I am not seeing LCD-AA being used unless I comment out this rule:

`z-index: -1;` in `.monaco-workbench .part.titlebar > .titlebar-drag-region`

I have a feeling messing with the index here causes trouble. What is the reason? Can we solve this differently?

**Comment by sbatten** [comment]
@bpasero we need the drag region, which spans the entire bar to be below everything else, for whatever reason, removing the negative value from the titlebar and adding positive values to the rest of the elements seems to fix it. see above commit. give it a try.

**Comment by bpasero** [comment]
@sbatten I think with your latest changes I can no longer interact with the custom menu at all. And the icon does not appear anymore:

![image](https://user-images.githubusercontent.com/900690/68989515-5d0caa00-0848-11ea-834a-9edb37d509e3.png)

On the upside, I see LCD-rendering though:

![image](https://user-images.githubusercontent.com/900690/68989522-6dbd2000-0848-11ea-8030-1eff9d40ca32.png)

**Comment by sbatten** [comment]
css comment fixes addressed the issue.
