### ISSUE TITLE
Rendering glitches in diff editor (IE10)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8480]
Ref: #8229

1. IE10, https://microsoft.github.io/monaco-editor/index.html
2. Look at the diff editor and notice the rendering glitches

![screen shot 2016-06-29 at 09 45 18](https://cloud.githubusercontent.com/assets/1926584/16444443/4728bfea-3dde-11e6-9d6a-1c59a3bdcda9.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/monaco-editor#155

Due to so many issues being opened straight in Microsoft/monaco-editor let's also move this one over there
