### ISSUE TITLE
Commit now commits regardless of wheter or not a file is staged for commit

### ISSUE THREAD

**Issue by TheGhost2804** [microsoft/vscode#84817]
- VSCode Version: 1.40.1
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Edit/save multiple files
2. Stage one file
3. hit commit
4. you'll see all files are beeing committed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
I can't reproduce. Can you show me your full settings?
