### ISSUE TITLE
Terminal & zsh color scheme

### ISSUE THREAD

**Issue by thomas-leroy** [Microsoft/vscode#8481]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Install and define zsh as your default $SHELL
2. Toggle terminal

Color scheme is not the one set in terminal.

**Comment by Tyriar** [comment]
@thomas-leroy do you mean the color scheme from `gnome-terminal` does not carry over? This is by design, the theme of the terminal will eventually be customizable but it will not integrate with `gnome-terminal` or similar applications. https://github.com/Microsoft/vscode/issues/6979
