### ISSUE TITLE
Set workbench editor tab placement to right

### ISSUE THREAD

**Issue by mdre** [microsoft/vscode#84815]
Allow to set the workbench editor tabs to appear to the right.
In Netbeans I use this config because is more useful to see more open files that what I see in the upper tab. Moreover, Netbeans colors tab based on the project name so all tab of one project has same color.
VSCode has the "Open Editors" but it is shown only on the "side bar" and I don't won't to see all the side bar to the right.
Here is a screenshoot:

![Screenshot_20191114_083113](https://user-images.githubusercontent.com/5312780/68854555-0aea4e00-06bb-11ea-8995-e9fc19bbb85f.png)

**Comment by gjsjohnmurray** [comment]
/duplicate covered by #26777 and #49923 as long as they are implemented in a generalized way.

**Comment by mdre** [comment]
I thinks this is not duplicated. In the other post, talk about duplicate the side bar or have a part of it on the right. 
What Is suggest is to let select where to put the editor tab position and color the tabs of the same projects.

**Comment by gjsjohnmurray** [comment]
@bpasero for a second opinion on whether reopen this and tag it appropriately.

**Comment by bpasero** [comment]
I think what you can do is disable tabs and use the File Explorer > "Open Editors" view? It is a list of all opened tabs.

**Comment by mdre** [comment]
In that case, I could not set it to the right outside of sidebar. 
I have found this plugins:

[vertical-tab-bar](https://marketplace.visualstudio.com/items?itemName=pzuraq.vertical-tab-bar)

that's do, in some way, what I want.
It seems it is possible to do just setting the correct CSS classes.
