### ISSUE TITLE
"Save Workspace As..." does not save with correct extension

### ISSUE THREAD

**Issue by nunojsa** [microsoft/vscode#84818]
Hi,

I'm not sure if this is really a bug or if I'm missing something. On linux, the normal procedure of opening folder -> save workspace as is not working as I expected. After doing this, if I close and open the workspace I loose all my folders and open files. In fact it only opens the json file. I realized that the the workspace config file is not being saved with the `.code-workspace` extension. Changing this manually make it work but it is rather annoying doing this manually... I guess this is not expected.

- VSCode Version: 1.40
- OS Version: Linux (tested on both Arch and Ubuntu18.04)

Steps to Reproduce:

1. Open Folder
2. Save workspace as
3. Add some file
4. Close workspace
5. Reopen workspace

Expected behavior after saving a workspace:

- To have my workspace file with .code-workspace extension;

- To be able to open my newly created workspace.

After saving a workspace with the name `sample-ws` this is what i get on my folder:
```
[nsa@nsa sample_ws]$ ls -la
total 12
drwxr-xr-x  2 nsa nsa 4096 Nov 15 11:42 .
drwxr-xr-x 30 nsa nsa 4096 Nov 15 11:41 ..
-rw-r--r--  1 nsa nsa   60 Nov 15 11:42 sample-ws
-rw-r--r--  1 nsa nsa    0 Nov 15 11:42 test.c
[nsa@nsa sample_ws]$ 

```

Image before closing the workspace:
![image](https://user-images.githubusercontent.com/28741857/68937927-9e944b00-079d-11ea-8fa0-2dc5f863d0e8.png)

Image after closing and reopening the same workspace:
![image](https://user-images.githubusercontent.com/28741857/68938009-c1befa80-079d-11ea-8b1f-4d57340a29e4.png)

Does this issue occur when all extensions are disabled?: Yes

As I said, If I manually add the ".code-workspace" extension, then it works but this should  be done automatically by the editor.

**Comment by jacobwindsor** [comment]
I have the same issue. Manually renaming the file to add a `code-workspace` extension fixes it but it should be automatically done this way

**Comment by nunojsa** [comment]
Yeps, I tested on windows and there it works as expected.

**Comment by bpasero** [comment]
@nunojsa this sounds like an issue with the save dialog to me, are you not seeing the ".code-workspace" extension added when saving?

**Comment by nunojsa** [comment]
@bpasero I do see the extension, however it's not adding the extension for some reason...

![image](https://user-images.githubusercontent.com/28741857/68944676-b9bb8680-07ae-11ea-8412-03bcdf97a7d7.png)

**Comment by bpasero** [comment]
Are you willing to conduct a little experiment and see if this reproduces in a small Electron app? Can you install https://electronjs.org/fiddle and verify you can run Electron 6 out of there, I can then provide some code.

**Comment by nunojsa** [comment]
Yes, I have it...

![image](https://user-images.githubusercontent.com/28741857/68947209-2e91bf00-07b5-11ea-9775-c4f1b90bcd52.png)

**Comment by bpasero** [comment]
@nunojsa ok here is the code for the left hand editor to try:

```js
// Display native system dialogs for opening and saving files, alerting, etc.
//
// For more info, see:
// https://electronjs.org/docs/api/dialog

const { app, BrowserWindow, dialog } = require('electron')

let mainWindow = null

app.on('ready', () => {
  mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.
  //
  // If you provide a callback, the method will be asynchronous,
  // but in thise case, we'll just use the synchronous variant.
  const file = dialog.showSaveDialogSync({
    title: 'Hello!',
    defaultPath: 'test.code-workspace',
    filters: [{extensions: 'code-workspace'}]
  });

  console.log(file);

  mainWindow.loadURL(`file://${file}`)
})

```

That should open a file dialog and when you press ok, print the path to the console.

**Comment by nunojsa** [comment]
This looks good...

![image](https://user-images.githubusercontent.com/28741857/68951576-aadcd000-07be-11ea-85c7-5a3bcf948d60.png)

**Comment by bpasero** [comment]
As a first change, I pushed that when providing a path that does not end in `.code-workspace` we do not consider the path as valid and do not change the window to enter it. 

@nunojsa what about changing the filter to:

[{ name: "Code Workspace", extensions: ['code-workspace'] }]

**Comment by bpasero** [comment]
Oh and can you put in just a folder for `defaultPath` instead of a file? That is what we do in VSCode. Try once with an existing and once with a non existing folder.

**Comment by nunojsa** [comment]
So, sorry if it's a basic question...

Where do I change the filter to `code-workspace`?
Also, can you explain what you mean by setting `defaultPath` to a folder?

Not sure If I can do this today anyways...

**Comment by nunojsa** [comment]
Hmm, you mean on the example code??

**Comment by bpasero** [comment]
Here:

![image](https://user-images.githubusercontent.com/900690/68956964-660a6680-07c9-11ea-9c58-3539fdc31150.png)
 In the sample code I provided

**Comment by nunojsa** [comment]
Here it goes with the changes:

Only with the change on `[{ name: "Code Workspace", extensions: ['code-workspace'] }]`

![image](https://user-images.githubusercontent.com/28741857/68957171-c39eb300-07c9-11ea-963d-37a20739a08d.png)

Non existing folder:

![image](https://user-images.githubusercontent.com/28741857/68957322-17110100-07ca-11ea-9db9-20d6147f21e1.png)

Existing folder:

![image](https://user-images.githubusercontent.com/28741857/68957415-46277280-07ca-11ea-99dd-53f9d1477b6f.png)

Here, I had to give it a name otherwise i could not continue... So, it didn't replaced the existing folder

Hope it helps!

**Comment by bpasero** [comment]
Oh, I can see the issue. And I can reproduce on Linux too. Thanks for the help.

**Comment by bpasero** [comment]
Up for grab, somehow we end up not putting a good filepath to the file dialog. Or Electron is to blame for not adding the extension automatically.

@nunojsa did this work before?

**Comment by bpasero** [comment]
I just verified this seems to be a regression, we used to have the extension. Not sure if Electron related or not.

**Comment by nunojsa** [comment]
> @nunojsa did this work before?

Not sure, I just started to give a try to vscode this week and I came across with this...

Happy to see that the issue was identified...
