### ISSUE TITLE
Extra breakpoint and indenting in text area when setting breakpoint while running debugger

### ISSUE THREAD

**Issue by alientourist** [microsoft/vscode#84813]
For some reason when setting a breakpoint while the debugger runs I get a visual bug. The breakpoint is shown in the text area in addition to the breakpoint column. See attached image.

Best regards,
Andreas Nilsson

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Install Debugger for Chrome 4.12.1
2. Start debugger and set breakpoint in code

Does this issue occur when all extensions are disabled?:  No, but then I can't run the debugger either

![breakpoint bug](https://user-images.githubusercontent.com/6361645/68854526-7f81b480-06dc-11ea-8b4d-e776af475fe3.png)
.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/81898
