### ISSUE TITLE
Debug toolbar position resetting

### ISSUE THREAD

**Issue by IcedAnt** [microsoft/vscode#84810]
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393
Extensions: Java Extension Pack, Spring Boot Tools, Spring Initializr, Spring Boot Dashboard, TSLint, Visual Studio IntelliCode

Issue: Closing or opening the terminal when debug is running will reset the position of the floating debug toolbar to the top. See gif below.

![vscode](https://user-images.githubusercontent.com/27441619/68852391-0da76c00-06d8-11ea-8bb0-370dda230245.gif)

This is my launch config in case it helps. The task it attaches to is a shell mvnDebug build task.
```
{
  "type": "java",
  "name": "Debug Rest",
  "request": "attach",
  "hostName": "localhost",
  "port": 8000
}
```

**Comment by gjsjohnmurray** [comment]
/confirm - I am able to reproduce this.

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
Sauron thanks for filling issues.
