### ISSUE TITLE
vscode appears to lose git in scm when saving workspace

### ISSUE THREAD

**Issue by dlmunk** [microsoft/vscode#84811]
- VSCode Version: 1.40.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open new window in vscode
2. Add a folder to the project
3. git clone bitbucket repo into a sub folder within project
4. vscode shows it correctly under source control tab
5. All works fine until you save the workspace
6. After saving workspace now 'No source control providers registered'
7. Making a change and saving inside the cloned repo then reactivates the source control providers panel. I would expect git to remain on the scm panel, it gave the impression it had lost the link with git.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Is the subfolder a direct child of the top-level workspace folder?

**Comment by dlmunk** [comment]
Nope, the workspace contains a Wordpress site with 3 repos, one for a plugin, one for a parent theme and one for a child theme. So that's:
/wp-content/plugins/plugin
/wp-content/themes/parent
/wp-content/themes/child

**Comment by joaomoreno** [comment]
Right. Git won't go and try to find repositories in deep folders of your workspace, since that would be expensive. You can tweak the `git.scanRepositories` workspace setting and explicitly list those folders as potential repositories to be scanned.

**Comment by dlmunk** [comment]
Great thanks João, i'll give that a go.
