### ISSUE TITLE
PHP SQL markdown

### ISSUE THREAD

**Issue by arlandantas** [microsoft/vscode#84829]
Issue Type: <b>Bug</b>

When I use single quotes inside double quoted SQL string without close him, the markdown fails.
Example:

```
$v2 = "SELECT field FROM my_table WHERE code IN ('".implode("', '", [0, 1, 2])."')";
```

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.71GB free)|
|Process Argv|--folder-uri file:///z%3A/www/ipcustos|
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
xml|Dot|2.5.0
prettier-vscode|esb|3.5.1
vscode-mysql|for|0.4.0
beautify|Hoo|1.5.0
easy-less|mrc|1.5.1
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.0
python|ms-|2019.10.44104
remote-wsl|ms-|0.40.2
oracle-plsql|myc|1.0.3
vetur|oct|0.22.6

</details>

**Comment by rebornix** [comment]
@arlandantas may I ask what do you mean by `markdown` fails? A recording / screenshot can help.
