### ISSUE TITLE
Task chained commands plus arguments are not working

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#84823]
When I use chained commands in the task `command` key (.. && .. &&) and add my catkin build arguments to the tasks `args` key (Build 1) I get the following error:

```
> Executing task in folder panda_autograsp_ws: 'catkin config --extend /opt/ros/melodic && catkin build' "-j4" <

bash: catkin config --extend /opt/ros/melodic && catkin build: No such file or directory
The terminal process terminated with exit code: 127
```

If I, however, include the additional arguments inside the command key it works (Build 2).

**Task.json file**

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build 1",
            "type": "shell",
            "command": "catkin config --extend /opt/ros/melodic && catkin build",
            "args": [
                "-j4",
                "-DCMAKE_BUILD_TYPE=Debug",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=1",
                "-DCMAKE_CXX_STANDARD=14",
                "-DFranka_DIR:PATH=\"$HOME/libfranka/build\"",
                "-Dfreenect2_DIR=\"$HOME/freenect2/lib/cmake/freenect2\"",
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [],
        },
        {
            "label": "build 2",
            "type": "shell",
            "command": "catkin config --extend /opt/ros/melodic && catkin build -j4 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_CXX_STANDARD=14 -DFranka_DIR:PATH=\"$HOME/libfranka/build\" -Dfreenect2_DIR=\"$HOME/freenect2/lib/cmake/freenect2\"",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [],
        },
]
```
## System information
**Version:** 1.41.0-insider
**Commit:** b6a486e34fe3715f6edec0cdb11138b1672d33bd
**Date:** 2019-11-14T05:30:39.779Z
**Electron:** 6.1.4
**Chrome:** 76.0.3809.146
**Node.js:** 12.4.0
**V8**: 7.6.303.31-electron.0
**OS:** Linux x64 5.0.0-36-generic (ubuntu 18.04)
**Does this issue occur when all extensions are disabled?:** Yes

## Steps to Reproduce:

1. Clone a simple catkin_ws. For example, the [ROS tutorials ws](https://wiki.ros.org/ROS/Tutorials).
2. Add the above task.json file to your .vscode folder.
3. Run the task

**Comment by EternalPhane** [comment]
The reason why `build 1` failed is obvious since vscode treat `catkin config --extend /opt/ros/melodic && catkin build` as a single command, and indeed this monster is not a command nor an executable. I guess this is intended feature, as mentioned in the comment below: https://github.com/microsoft/vscode/blob/c861fe99c18aac7a9289a5b411d8124b81ef1163/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1162-L1167

**Comment by rickstaa** [comment]
@EternalPhane Thanks for the clarification. I already suspected something like that was happening.
