### ISSUE TITLE
Change minimal windows size

### ISSUE THREAD

**Issue by algiuxass** [microsoft/vscode#84821]
Linux user with tiling manager here.
It's a huge pain to use vscode with the new window dimensions.

Example if I have 3 windows vertically:
![image](https://user-images.githubusercontent.com/33424336/68859453-f1172e00-06ef-11ea-9fde-94c708bca4e2.png)

There's not enough space for other 2 windows! Also some programs tend to freeze/crash if the window size is too small because vscode uses a lot of space. I've experienced that 2 times today.

Any suggestion if that's possible to change?

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/84568#issuecomment-553538179 by @sbatten indicates no current plans to change this.

**Comment by sbatten** [comment]
@algiuxass when you say vertically, do you mean

A> 1|2|3

or

B>
1
.
2
.
3

**Comment by algiuxass** [comment]
@sbatten B. 
The problem is that vscode has slightly big minimal window dimensions, it's pain for small displays.

**Comment by algiuxass** [comment]
For Linux I found a quick way to fix this:
Edit with sudo this file: `/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js`
Replace r.MIN_WIDTH and r.MIN_HEIGHT with whatever you want to. (I set it to 10)

**Comment by sbatten** [comment]
closing this as min height was adjusted and the electron fix is incoming.

**Comment by algiuxass** [comment]
It's fixed, but it still could be smaller at least for me, but for everyone else it's fine I guess.
Every update I have to manually replace r.MIN_WIDTH and r.MIN_HEIGHT, so if someone wants to easily fix that, use this:
```sudo sed -i -e 's/r.MIN_WIDTH/10/g' -e 's/r.MIN_HEIGHT/10/g' /opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js```
Replace 10 with width and height.
