### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by roshandhabekar** [microsoft/vscode#84822]
<b>Performance Issue</b>

As of working with this current version, it's crashing continuously

VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   21	    98	 23426	code main
    1	    98	 23427	   gpu-process
    0	    82	 23447	   shared-process
    0	   311	 23479	   window (Avplat-Ionic-3)
    0	     0	 23486	     /bin/bash -l
    0	    33	 23854	       ionic
  196	   311	 23856	         node /Users/avplat/Roshan/Avplat-Ionic-3/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
    0	   180	 23489	     extensionHost
    0	    49	 23498	       electron_node server.js 
    0	   262	 23499	       electron_node tsserver.js 
    0	    66	 23526	         electron_node typingsInstaller.js typesMap.js 
    0	    82	 23501	       /usr/bin/java -classpath /Users/avplat/.vscode/extensions/adamvoss.vscode-languagetool-3.8.0/lib/languagetool-languageserver/build/install/languagetool-languageserver/lib/*:/Users/avplat/.vscode/extensions/adamvoss.vscode-languagetool-en-3.8.0/lib/* App 56282
    0	  1491	 23539	       electron_node server.js 
    0	    49	 23576	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=23489
    0	    49	 23490	     watcherService
    0	    33	 23500	     searchService
    5	    66	 23914	   window (Issue Reporter)
    0	     0	 23930	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Avplat-Ionic-3)
|    Folder (Avplat-Ionic-3): 8632 files
|      File types: js(1572) class(1548) map(806) ts(642) dex(509) png(437)
|                  md(323) h(301) scss(255) json(252)
|      Conf files: package.json(57) tsconfig.json(2) tslint.json(2) gulp.js(1)
|                  launch.json(1) sln(1) csproj(1) settings.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
flutter-snippets|ale|2.0.0
jsonviewer|cci|1.2.2
exttla|cha|0.0.8
mdtools|con|0.14.0
dart-code|Dar|2.25.1
flutter|Dar|2.25.1
xml|Dot|2.5.0
gitlens|eam|9.9.1
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|29.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
flutter-stylizer|gml|0.0.14
vscode-flutter-files|gor|1.5.4
beautify|Hoo|1.5.0
smarty|imp|0.3.0
Angular2|joh|8.1.1
vscode-phpfmt|kok|1.0.30
php-symbols|lin|2.1.0
dart-import|lua|0.1.5
code-beautifier|mic|2.3.3
prettify-json|moh|0.0.3
vscode-scss|mrm|0.6.2
vscode-devskim|MS-|0.2.2
mssql|ms-|1.5.0
cordova-tools|msj|1.9.0
debugger-for-chrome|msj|4.12.1
awesome-flutter-snippets|Nas|2.0.1
php-docblocker|nei|2.0.1
fix-json|oli|0.1.2
dart-syntax-highlighting-only|osc|1.0.0
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|3.9.1
vscode-css-peek|pra|3.0.2
LiveServer|rit|5.6.1
rapp-smarty|toy|1.0.0
autocomplete-english-word|wus|0.1.7
JavaScriptSnippets|xab|1.7.2
chaos|xu|0.1.1
json|Zai|1.0.2
swig-tpl|zha|0.0.6
swig|zhu|0.0.5

(4 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Your version info shows as 1.32.1 but the latest is now 1.40.1. Can you upgrade?

**Comment by roshandhabekar** [comment]
Thanks, I will update and get back to you.

**Comment by roshandhabekar** [comment]
VSCode Updated working fine, for now, let see.
Thanks, @gjsjohnmurray  for helping out in this.
