### ISSUE TITLE
VSCode RPM package is not signed

### ISSUE THREAD

**Issue by tvieira** [microsoft/vscode#84825]
- VSCode Version: 1.40.1-1573664332.el7
- OS Version: Fedora 30

Steps to Reproduce:

1. Install latest VS Code

Results:
code-1.40.1-1573664332.el7.x86_64.rpm: Already downloaded                                                                                          
Package code-1.40.1-1573664332.el7.x86_64.rpm is not signed

**Comment by clmbmb** [comment]
I can confirm.
