### ISSUE TITLE
Source Control: "open changes" menu item shows twice

### ISSUE THREAD

**Issue by ItaHeld90** [microsoft/vscode#84824]
- VSCode Version: 1.40.1
- OS Version:

Steps to Reproduce:

1. Open some project with Git as the source control
2. make some changes
3. open the source control panel
4. right-click on one of the files

Result: the item "Open Changes" shows twice

snapshot: 

![image](https://user-images.githubusercontent.com/20743167/68860333-fd9c8600-06f1-11ea-8fc3-abf7f6e8cf6a.png)

**Comment by jardelnovaes** [comment]
Hi @joaomoreno 

I think someone has alredy solved it.
The lastest version **(v1.40.1)** from https://code.visualstudio.com/ really has this "bug", but I wasn't able to reproduce it from the source code.
I packaged it and wasn't able to reproduce the "bug" as well **(v1.41.0)**
I suggest to close this issue.

![VSCode-win32-x64_Issue_84824](https://user-images.githubusercontent.com/20839085/69010999-73982b80-0944-11ea-9762-23d467cc926a.png)

**Comment by joaomoreno** [comment]
Yup, I've fixed this in `master`. Didn't make the recovery candidate, so it will come in November's stable release.
