### ISSUE TITLE
multiply files are not opening simultaneously

### ISSUE THREAD

**Issue by manit1dinesh** [microsoft/vscode#84835]
Issue Type: <b>Bug</b>

i am unable to open working files simultaneously in single window. please help

VS Code version: Code 1.40.1 , 2019-11-13 T16:49:35.976Z)
OS version: Windows10 x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
Please review https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode and close this issue if that is what you are seeing.

**Comment by rebornix** [comment]
It would be great if you can provide more information like screenshots, recordings to help understand the problem you run into.
