### ISSUE TITLE
Command pallete rendering broken (IE9)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8483]
Ref: #8229

1. IE9, https://microsoft.github.io/monaco-editor/index.html
2. open the command pallete, scroll down, scroll up, after scrolling up notice how the command pallette is broken

![screen shot 2016-06-29 at 11 14 09](https://cloud.githubusercontent.com/assets/1926584/16447018/ba3b9988-3dea-11e6-8bed-4ccc15eed97f.png)

**Comment by bpasero** [comment]
Likely the tree...

**Comment by joaomoreno** [comment]
Microsoft/monaco-editor#50...
