### ISSUE TITLE
Support for `--force-renderer-accessibility` Electron argument, needed for Linux accessibility

### ISSUE THREAD

**Issue by ndarilek** [microsoft/vscode#84833]
Lots of work has gone into Chromium accessibility under Linux, and many Electron apps are becoming accessible under Orca. Unfortunately, as of now this requires passing a `--force-renderer-accessibility` command line parameter, which presumably Electron/Chromium handles under the hood. Many Electron apps handle this, but VSCode seems to intercept command line parsing and doesn't support this flag.

Is it possible to either support this flag directly in VSCode, or to offer a command line parameter for passing additional flags directly to Electron?

I'm not sure if using this flag will even make a difference now, since this work is still in its early stages. But without it, VSCode can't currently use *any* of the current Linux accessibility work, and likely won't become even slightly usable until the late stages when the command line flag becomes unnecessary.

Thanks.

**Comment by adil-s** [comment]
👍

**Comment by aeschli** [comment]
added `--force-renderer-accessibility` to the list of accepted cli arguments.

**Comment by jrieken** [comment]
@aeschli Does it make sense to support this flag in the runtime args file?

**Comment by aeschli** [comment]
@1`

> @aeschli Does it make sense to support this flag in the runtime args file?

I guess yes, @bpasero manages that.

**Comment by bpasero** [comment]
Let's do it when we have an overwhelming set of people asking for it. Also note that not every command line flag can be defined programmatically. Some need to be on the CLI for Chrome to pick up early.
