### ISSUE TITLE
Background highlight shows two colors

### ISSUE THREAD

**Issue by alexalannunes** [microsoft/vscode#84838]
After I upgraded the VS CODE to version **`1.40.1`**, my themes is showing two different colors

Themes testeds:
* Dracula (Soft too)
* Monokai

### Follow screenshots
![bug](https://user-images.githubusercontent.com/16847836/68869798-83133c80-06d8-11ea-82d3-e5669e09853b.png)
![bug1](https://user-images.githubusercontent.com/16847836/68869799-83133c80-06d8-11ea-8e95-81da0cf2e295.png)

---

I know this issue is duplicate but I didn't see a solution.
I decided to downgrade (to **`v1.39`**)

### related
#15934

## VS CODE
```
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-66-generic
```

**Comment by gjsjohnmurray** [comment]
Please see #84690 and close this if it is a duplicate.

**Comment by alexalannunes** [comment]
Fixed: 84838

[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --disable-gpu --no-sandbox --unity-launch %F
Icon=/usr/share/pixmaps/com.visualstudio.code.png
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.22

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --disable-gpu --no-sandbox --new-window %F
Icon=/usr/share/pixmaps/com.visualstudio.code.png
