### ISSUE TITLE
Git: Adopt editor in SCM input

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#84831]
The Monaco editor can be used as the SCM input widget

**Comment by skarcha** [comment]
It'd cool that commit message editor breaks lines at defined line size (for example, 72)

**Comment by joaomoreno** [comment]
Actually, reverting https://github.com/microsoft/vscode/issues/84201 or implementing https://github.com/microsoft/vscode/issues/6403 isn't dependent on this. Will remove this from the current plan as it was a tentative item.

@skarcha #2718
