### ISSUE TITLE
Suggest widget rendering broken (IE9)

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8484]
1. IE9, https://microsoft.github.io/monaco-editor/index.html
2. Trigger suggest widget, scroll down, scroll back up -> notice how the rendering is broken, none of the suggestions get rendered

![screen shot 2016-06-29 at 11 16 44](https://cloud.githubusercontent.com/assets/1926584/16447098/24dabef4-3deb-11e6-8550-e737cafccd1a.png)

**Comment by joaomoreno** [comment]
Microsoft/monaco-editor#49
