### ISSUE TITLE
Add command line argument for running a command in an intergrated terminal

### ISSUE THREAD

**Issue by Jtkantor198** [microsoft/vscode#84848]
I often find myself running multiple vscode instances for different projects. I open these projects daily and run commands in the integrated terminal on each. I have a shell script to open the projects, but it would be convenient to pass an argument to `code ./` allowing it to run the start up commands for each of these projects. Something as simple as `code ./ --run-it="npm run serve"`. I imagine this is a common problem for people but haven't yet found such an option.

If this is done, it would be nice to support running multiple commands in separate integrated terminals. One project has a few sims I run simultaneously. 

Thank you

**Comment by Tyriar** [comment]
We defer this sort of functionality to extensions, https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals might fit your needs.
