### ISSUE TITLE
VS Code does not use environment variable http_proxy

### ISSUE THREAD

**Issue by simue** [microsoft/vscode#84845]
Issue Type: <b>Bug</b>

 1. Go to VS Code settings, section Application>Proxy.
 1. See Proxy setting whose clarification is "The proxy setting to use. If not set, will be inherited from the http_proxy and https_proxy environment variables."
 1. Set environment variable http_proxy.
 1. Do networking stuff. E.g. try to sign in to Azure via Azure Account Extension: Press F1 ">Azure: Sign In".
 1. Get Error notification saying "You appear to be offline. Please check your network connection." which is generated by Azure Account Extension.

 1. Go to Settings.json, set "http.proxy": "http://server:port"
 1. Try to log in again.
 1. Success!

I consider this a Bug, as the help text in the settings dialogue states that environment variables are loaded and used centrally, when they are not.

Further more, it is not the case that proxy settings can't be used by the extension since written directly into the settings.json everything works.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (24.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.10.44104
vscode-ai|ms-|0.6.7
azure-account|ms-|0.8.7
team|ms-|1.161.0
azure-iot-edge|vsc|1.18.0
azure-iot-toolkit|vsc|2.13.0
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.1.4
vscode-iot-workbench|vsc|0.10.16

</details>

**Comment by simue** [comment]
Based on the observation, that setting the proxy address explicitly via the setting dialogue or in settings.json, I disagree the classification of this Issue as a duplicate.

**Comment by chrmarti** [comment]
Try setting the proxy environment variable and then restart VS Code (if that doesn't work try rebooting the machine after setting the environment variable). We do look at the environment variables, note that if the setting is present, that wins over the environment variables.

**Comment by simue** [comment]
Thank you for your input!
I did restart the PC after removing the explicit proxy setting and assuring that the environment variable is set correctly. This did not work. The environment variable was written all uppercase: HTTP_PROXY.
I then changed it to all lowercase which worked fine.
Additionally, since my last post here I observed the behaviour of the Sign In. Most of the times it worked, sometimes not. I can not see a pattern there. Maybe it also didn't not work because of the uppercase/lowercase, but because of other reasons (maybe not in relation to VS Code and the Azure plugin)?

Could you please confirm/disprove the uppercase/lowercase suspicion?

**Comment by chrmarti** [comment]
I read the lower- and uppercase names: https://github.com/microsoft/vscode/blob/615732feae7228502eab60919d67837f7a625e7c/src/vs/workbench/services/extensions/node/proxyResolver.ts#L61

Note that the setting wins over the environment variables. So if the setting had an invalid value, that would be tried and not the environment variables.

**Comment by simue** [comment]
The proxy setting was empty.
Are there any logfiles that one could look into when the error occurs again?

**Comment by chrmarti** [comment]
You can set the log level to `Trace` (`F1` > `Developer: Set Log Level...`) to get logging in the Output panel's Extension Host channel. Look for lines with 'ProxyResolver#'.

**Comment by simue** [comment]
Will this have to be done after every start of VS Code, or is this a permanent setting?

**Comment by chrmarti** [comment]
The log level is preserved for as long as at least one window is open (or being reloaded).

**Comment by simue** [comment]
Since the problem did, until now, not reoccur, I assume that this issue is related to my company's proxy.
If the problem reoccurs, I am going to get the logs and get back here.
Thank you very much for your help!
