### ISSUE TITLE
Un smiley dans la barre d'état

### ISSUE THREAD

**Issue by bobanum** [microsoft/vscode#84849]
Issue Type: <b>Bug</b>

1) Ouvrir VS Code

2) Il y a un smiley dans la barre d'état qui me permet de tweeter. Je n'ai jamais installé d'extension de la sorte. Il n'y a pas d'extension à cet effet. Je ne vois pas pourquoi cette fonctionnalité serait installée par défaut dans une __éditeur__ de __CODE__. Pourquoi _Tweeter_? Peut-on changer de réseau? Peut-on le désinstaller? Peut-on vous demander de le mettre en extention et de mettre des extensions plus utiles par défaut comme un serveur WEB?
Merci

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.2
vscode-sqlite|ale|0.8.0
vscode-intelephense-client|bme|1.2.3
phpserver|bra|2.4.6
laravel-goto-view|cod|1.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
EditorConfig|Edi|0.14.2
php-debug|fel|1.13.0
vscode-firefox-debug|fir|2.5.1
todo-tree|Gru|0.0.162
vscode-ungit|Hir|2.1.0
beautify|Hoo|1.5.0
svg|joc|1.0.5
docthis|joe|0.7.1
dartsass|mal|0.0.79
dotenv|mik|1.0.1
ecdc|mit|1.3.0
easy-less|mrc|1.5.1
vscode-apache|mrm|1.2.0
vscode-language-pack-fr|MS-|1.40.2
vsliveshare|ms-|1.0.1123
debugger-for-chrome|msj|4.12.1
sqltools|mtx|0.21.3
vetur|oct|0.22.6
laravel-blade|one|1.20.0
laravel-extension-pack|one|0.6.1
laravel5-snippets|one|1.7.0
classlens|rex|0.7.1
LiveServer|rit|5.6.1
ftp-kr|rua|1.3.16
laravel-artisan|rya|0.0.26
vscode-microsoftteams|ste|1.0.6
vscode-svg-previewer|vit|0.5.1
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2

</details>

**Comment by byyxx128** [comment]
1. English please.
2. Ask questions [here](https://stackoverflow.com/questions/tagged/visual-studio-code).
3. The smiley you seemed in status bar is not provided by an extension. You can ignore it if you don't use Twitter...

**Comment by bobanum** [comment]
Do you mind me asking... Why is there a Tweeter feature? Why not Facebook, Linkedin, Youtube, MySpace, ThePirateBay...?
My questions are rhetorical. I didn't think the __french__ dialog box in VS Code would file a bug report.
I know it's not an extension. It's just a bad UX choice.
Thanks

**Comment by bpasero** [comment]
Oh, only now saw the second comment. Can you clarify?

**Comment by bobanum** [comment]
This is a question and an opinion : Why put by default a button to a social media? Is there a use I don't see in relation with the act of coding? VS Code's interface can quickly become cluttered. Shouldn't we only have useful features? I mean directly useful to what we do with the app. Like _Live Server_ by default, _Emmet_ shortcuts (for Wrap with abbreviation...). I teach in a lab where I have to install every extension every time I log in (College policy or inadequacy). It's a little frustrating having an unwanted feature right on the status bar. Unless I should want this feature for some reason. Thanks for your response.
Martin Boudreau

**Comment by bpasero** [comment]
@bobanum did you notice that you can hide the smiley, e.g. via right click? Getting feedback from our users is very important to us, so we have it there.

**Comment by bobanum** [comment]
You just said it : It's important to __you__. It still is a bad idea from our perspective. It already is in the menu. I'm new to the VS Code _community_ and I like all the powerful features, but the "out of the box" usability and over all user interface leave to be desired. Sadly, the phrase "you can disable it" and "there's a plugin" comes too quickly. 2 out of 2 in my case. (https://github.com/microsoft/vscode/issues/30114). Is there a forum where users can discuss about the UI before it is baked? Is there a user interface guideline manual? There's no reason for the "Live Server" and the "PHP Server" to be in different places, and clearer directives might avoid those kind of inconsistencies. Thanks.
