### ISSUE TITLE
Automatic folding/collapsing of specified HTML tags (ie. <svg>) on file load

### ISSUE THREAD

**Issue by nereusz** [microsoft/vscode#84844]
I would like to make PHP Storm fold specific tags on file open.

I have a file with SVG image inline:
```
        <div class="btn-header">
          <div class="btn-inner">
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12">
              <path class="stroke" d="M6,1V11"
                    style="fill: none;stroke-linecap: square;stroke-linejoin: round;stroke-width: 2px" />
              <path class="stroke" d="M11,6H1"
                    style="fill: none;stroke-linecap: square;stroke-linejoin: round;stroke-width: 2px" />
            </svg>
            <span>Add</span>
          </div>
        </div>
```

But just after a few such elements HTML is getting messy. Code is much clearer when I fold this tag. Then I see only one line for whole image:

```
        <div class="btn-header">
          <div class="btn-inner">
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12">... (folded)
            </svg>
            <span>Add</span>
          </div>
        </div>
```

It's much clearer. But now I need to fold them manually.

I see is as list of tags that are collapsed by default when I open HTML file (for me it's SVG, but maybe someone would like to add other tags).

**Comment by nereusz** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [[html] fold attributes (#57520)](https://www.github.com/microsoft/vscode/issues/57520)

I've checked it. Unfortunately it's not relevant.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/40338
