### ISSUE TITLE
Cursor Jump to top page

### ISSUE THREAD

**Issue by tuanphongvo** [microsoft/vscode#84840]
Issue Type: <b>Bug</b>

I am working with golang in VS Code. 
When I save the files,  my cursor jump to the top of files.
I don't know problem from the plugin or VS Code.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.84GB (15.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
go-prof|Max|0.0.4
vscode-docker|ms-|0.8.2
Go|ms-|0.11.9
debugger-for-chrome|msj|4.12.1

</details>

**Comment by gjsjohnmurray** [comment]
Please launch with all extensions disabled. If this solves the problem try enabling one at a time to discover which one is causing the issue.

**Comment by tuanphongvo** [comment]
I tried disable all the extensions, But the problem still there.
I can re-produce the issue. I changed the code and save, then Ctr+ Z to undo the happen came.

**Comment by rebornix** [comment]
@tuanphongvo does it mean you can reproduce this issue in all files with all extensions disabled?
