### ISSUE TITLE
Expose MarkdownEngine.currentDocument to contributed extensions

### ISSUE THREAD

**Issue by yhatt** [microsoft/vscode#84846]
VS Code's Markdown engine has stored the URI of document under parsing but it's not exposed to Markdown preview extensions (markdown-it plugins).

Exposing the location of current document (`MarkdownEngine.currentDocument`) to the second argument of markdown-it functions (`env` object) would like to be good for contributed extensions. Please let me hear if there is any concern.

## Motivation

My extension, [`marp-team.marp-vscode`](https://github.com/marp-team/marp-vscode), has implemented the support of CSS themeing that is separated from `markdown.styles` built-in preference. I have used a hacky way (execute `md.normalizeLink()` directly) to get the placed directory of Markdown under parsing. I need it for matching the rule of CSS path resolution into `markdown.styles`.

https://github.com/marp-team/marp-vscode/blob/a3dc7bd8d50e97b995a2c7b57f38479cf1696334/src/extension.ts#L30-L32

Until VS Code 1.39.x, that was expected to get URI to the workspace folder Markdown belongs, or the directory that Markdown is placed.

Unfortunately this is no longer working since 1.40.0 by the change in 36aa903 (reported in marp-team/marp-vscode#100). I tried to fix this but failured because I could not find the correct way to get current document while parsing.

I have recognized the design of `markdown.styles` to avoid reading arbitrary files (#75039), and I'm sure following this principle should be better to make extension secure.

**Comment by christianvoigt** [comment]
I know I am too late for this feature request, but I think this is comparatively easy to fix and would improve the configurability of markdown-it plugins a lot. 

I am currently adding a markdown-it plugin to the [Argdown VSCode extension](https://argdown.org) and want to load configuration files specific to the workspace of the currently previewed document. As I do not want to use a "messy workaround" as in the marp plugin, I think I have to give up on this.

**Comment by yhatt** [comment]
@christianvoigt Thanks for having same opinion!

[The workaround](https://github.com/marp-team/marp-vscode/blob/5fffce4fe38827d70012ad7644f523389dbe1382/src/extension.ts#L34-L40) may have misdetection the location of workspace while opening the exactly same 2 Markdowns in different workspaces, so I don't want to use this trick if possible.

Should I open as a new issue to continue this?
