### ISSUE TITLE
Allow "Explorer: Incremental Naming" to have Disabled option for Paste

### ISSUE THREAD

**Issue by virgofx** [microsoft/vscode#84857]
Please add an option to **disable** incremental naming. By disabling ... the end effect should be to  effectively overwrite existing files when pasting.

The current options of `smart` and `simple` are helpful; however, not useful in my context. For myself and those users who commonly do file operations in the host OS file explorer, the expected behavior when copying files/folders in the VSCode explorer is to similarly have these overwritten.

**Comment by isidorn** [comment]
We are open to a PR which adds the `disabled` option to the `incrementalNaming` setting.
Code pointer https://github.com/microsoft/vscode/blob/970f3543b8fb3a35ea2ba36587859297d851ac18/src/vs/workbench/contrib/files/browser/fileActions.ts#L353

**Comment by lramos15** [comment]
To verify set `"explorer.incrementalNaming": "disabled"` and copy and paste a file to ensure its name isn't changed and if a file of the same name exists in that directory it asks to overwrite the file
