### ISSUE TITLE
Word highlighting now mishandles underscores

### ISSUE THREAD

**Issue by tbfleming** [microsoft/vscode#84858]
Issue Type: <b>Bug</b>

Place the cursor in the middle of an identifier with underscores. e.g. `db_it_next`. If the cursor is in the middle if `it`, it highlights `it` throughout the source instead of highlighting `db_it_next`. It used to highlight `db_it_next`.

This also impacts "Add Selection To Next Find Match". This used to grab the `db_it_next`, it now grabs `it`.

I made sure the "Match Whole Word" option is checked in the find box and that the "Match Whole Word" option is checked in the box that pops up with the "Add Selection To Next Find Match" command.

I also made sure the underscore character isn't in `editor.wordSeparators`.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz (20 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|128.00GB (42.71GB free)|
|Process Argv|-psn_0_8390656|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.5.0
gitlens|eam|10.1.2
svgeditor|hen|2.9.0
swift|Kas|0.1.0
code-beautifier|mic|2.3.3
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
cpptools|ms-|0.26.1
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
code-spell-checker|str|1.7.20
cmake|twx|0.0.17
html-css-class-completion|Zig|1.19.0

</details>

**Comment by tbfleming** [comment]
Update: I just noticed that it varies with context in unusual ways. The above behavior is within an `.md` file, but not within a C++ code block. Within C++ code blocks it behaves as expected.

**Comment by rebornix** [comment]
Not sure if we have any update in markdown side.

**Comment by mjbvz** [comment]
`_` can have semantic meaning in markdown: https://spec.commonmark.org/0.29/#can-open-emphasis

I've update our word pattern to match words so long as they do not start or end with `_`

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/commit/40b8c9d073ec19274f6376f77b879f4fcf39ab43

**Comment by Tyriar** [comment]
I would expect `_` to act exactly the same as `*` but the highlighting only occurs with `*` now:

![image](https://user-images.githubusercontent.com/2193314/70188890-bd07ab00-16a6-11ea-9909-bd16c8840685.png)

**Comment by mjbvz** [comment]
Not a regression from this fix. This is weird because we do highlight the `it` in `*it*` if you are on `it` in `_it_`:

![Screen Shot 2019-12-04 at 3 09 51 PM](https://user-images.githubusercontent.com/12821956/70189440-2cca6580-16a8-11ea-8262-13bc0945ca88.png)

**Comment by mjbvz** [comment]
Extracting this to new issue: https://github.com/microsoft/vscode/issues/86332

Please verify the original reported problem with underscores inside words
