### ISSUE TITLE
Integrated Terminal Kill Text (Control K) Requires Different Keypress

### ISSUE THREAD

**Issue by rbrianhazzard** [microsoft/vscode#84855]
Version of VS Code: 1.40.1

Your operating system: Windows 7

Quick Summary:

I'm finding that the Kill Text command is not working properly after updating to 1.40.1. When focusing an integrated terminal using **git bash** as the shell, using the bash keyboard shortcut Control + K does not cut to the end of the line from my cursor. I similarly cannot use Yank / Control + Y to paste this.

It seems like if I hit control + K a second time, the command works as expected. I am able to use control Y afterwards no problem. 

Steps to Reproduce:

1) Terminal: Focus Terminal

2) Select Default Terminal (git bash)

3) New Terminal 

4) Type anything and go back to start of the line

5) Control K

6) See text in the bottom pane saying (Ctrl + K) was pressed. Waiting for second key of chord...

![image](https://user-images.githubusercontent.com/45824358/68889421-e0b08480-06ea-11ea-8329-2fc988e081cb.png)

7) Nothing happens. I have to hit Ctrl + K again to properly cut text to the end of the line

Honestly, not a huge deal since I can work around it by hitting Ctrl + K a second time, just thought I would bring it up since this was not the same behavior as in version 1.39.2, and the integrated terminal follows other bash defaults fine (like Ctrl + y for yank, for example).

**Comment by usernamehw** [comment]
Related https://code.visualstudio.com/updates/v1_40#_chords-are-now-supported-by-default

**Comment by rbrianhazzard** [comment]
Thanks @usernamehw that was it, didn't catch that in the release notes
