### ISSUE TITLE
Web: mouse treated as touch on iPadOS

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#84856]
Currently if you are using external mouse through assistive touch on iPadOS, the mouse is still treated as touch. It seems that this issue was fixed via https://bugs.webkit.org/show_bug.cgi?id=202789 but didn't land in iOS/iPadOS yet.

**Comment by rebornix** [comment]
To test if what kind of pointer type a point device is treated by the OS, please try https://people.igalia.com/clopez/wkbug/pointer-events/test.html

**Comment by GalacticLion7** [comment]
Maybe the new adaptive cursor on iPadOS 13.4 fixed this issue?

**Comment by rebornix** [comment]
@GalacticLion7 yes I tested on the new iPadOS and it's already fixed, we should reevaluate this issue.
