### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by justgrumpy** [microsoft/vscode#84869]
- VSCode Version: 1.40.1 _(same behavior with 1.40.0-insider)_
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Attempt to update or install **any** extension either from inside VSCode or from the Marketplace results in the following error:

```
[2019-11-14 15:27:57.135] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:386:115

```
2. Installing the same extension from the `.vsix` file works fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by justgrumpy** [comment]
Someone near me with a Mac and on 1.36.1 was able to install extensions just fine. Once they installed the newest version, they were no longer able to install extensions.

**Comment by sandy081** [comment]
Can you please try with a new user data directory by starting VS Code from command line using arg `--user-data-dir <path_to_new_dir>` and let us know if you are seeing same issue?

**Comment by justgrumpy** [comment]
@sandy081 - I started VS Code with the following, `code --user-data-dir c:/dev/userDir`. I am still getting similar errors...

```
[2019-11-15 09:31:14.555] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:386:115
```
By the way, `<user>` is not the actual folder name. I inserted that in place of my actual user name.

I'm not sure the `--user-data-dir flag` worked?

**Comment by sandy081** [comment]
You can check if it worked or not by opening the user settings file which shall come from the user data directory you provided.

**Comment by justgrumpy** [comment]
The `--user-data-dir` flag did create a new folder, but the install and update still do not work. I get the same error.

**Comment by justgrumpy** [comment]
Is there a way to install previous versions of VS Code pre 1.40.x? Install and update works fine in versions prior to 1.40.0.

**Comment by sandy081** [comment]
Can you please try https://code.visualstudio.com/insiders/insiders?

**Comment by justgrumpy** [comment]
I already tried the insiders.

It appears the problem is a change in the `User-Agent`. The `User-Agent` used to be something like `VSCode 1.39.2`. With 1.40.0, the `User-Agent` changed to something like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.40.1 Chrome/76.0.3809.146 Electron/6.1.2 Safari/537.36`. 

This new `User-Agent` appears to be blocked by our firewall. I will agree our firewall rules are our problem, but the change to the `User-Agent` is something unexpected that appears to have caused this issue.

**Comment by justgrumpy** [comment]
@sandy081 any more you can do to assist with this?

**Comment by sandy081** [comment]
@deepak1556 Is this a change caused by electron update?

**Comment by deepak1556** [comment]
There has been no change in the user agent format across the versions, its always followed https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

> The User-Agent used to be something like VSCode 1.39.2

@justgrumpy how did you confirm this ?

Can you follow the steps below and attach the log from it

* Open devtools
* Try to install an extension from the marketplace
* From the `Network` panel in devtools, use the `Export HAR..` option and attach the .har file here.

**Comment by justgrumpy** [comment]
@deepak1556 - I'll have to get back to you on this. I don't have access to the older version of VS Code to test it myself and the person that gave me the information is out.

**Comment by justgrumpy** [comment]
I was able to get information about the User-Agent from an older version of VS Code along with that of the current:
```
User-Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.36.1 Chrome/69.0.3497.128 Electron/4.2.5 Safari/537.36
User-Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.40.1 Chrome/76.0.3809.146 Electron/6.1.2 Safari/537.36
```
The `Code/1.XX.Y` portion changed. I'm guessing the rule we had was too restrictive. Changes have been made and we are able to install/update again.

Thank you

**Comment by deepak1556** [comment]
Thanks for the update, and yes that part of the user agent will vary just like any other applications user agent. Closing as no further action is needed here.
