### ISSUE TITLE
Why does monaco-editor support IE9 and IE10?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8486]
Refs: #8229

Why does monaco-editor support IE9 and IE10, looking at the [issues](https://github.com/Microsoft/vscode/labels/monaco-editor) we found during this endgame I do not think there are users that use our editor or IE9 or IE10 (otherwise they would complain).

ping @alexandrudima @egamma

**Comment by egamma** [comment]
Need to also check this with our partners.

**Comment by alexandrudima** [comment]
ping @chrisdias @egamma -- I believe we can drop IE9 and IE10

(Tomorrow is September)

https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/16/team-services-ending-support-for-internet-explorer-9-and-10-in-september/
![image](https://cloud.githubusercontent.com/assets/5047891/18127600/badeab46-6f81-11e6-9fcf-3ad0d83b6b86.png)


https://feedback.azure.com/forums/223579-azure-portal/suggestions/6590349-fix-internet-explorer-so-that-you-can-log-into-the
![image](https://cloud.githubusercontent.com/assets/5047891/18127589/b01b4cd2-6f81-11e6-900e-b12c4036d8d0.png)

**Comment by chrisdias** [comment]
Confirmed with OneDrive that we can drop support, as long as we do a major/minor version bump.

**Comment by chrisdias** [comment]
F12 approves as well, so i think that covers the major partners (vsts, onedrive, azure, f12/IE).
