### ISSUE TITLE
PowerShell Intellisense forever processing, causing f5 and f8 keys to not work

### ISSUE THREAD

**Issue by ajacks88** [microsoft/vscode#84865]
We have written the needed data into your clipboard becaus
Issue Type: <b>Bug</b>

Ever since today ( this used to work) when i use PowerShell and i start typing a command it will use intellisense to tab complete the command i am looking for. After the first command is entered, i start typing the next command and i notice the powershell spinning arrows at the bottom-left of VS code just continually spinning. Once it is in this state you cannot use f5 or f8 to run sections or a whole script. You can re-launch VS code and it will work until you use intellisense again.

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.40.2
powershell|ms-|2019.11.0

</details>
e it was too large to send. Please paste.

**Comment by rebornix** [comment]
Please file issue against Powershell extension, which seems to cause the issue you run into.
