### ISSUE TITLE
VS Code takes long time to startup and also after running commands

### ISSUE THREAD

**Issue by headstrongme** [microsoft/vscode#84867]
Issue Type: <b>Bug</b>

It takes a lot of time for extensions to load and to start the VS code. I compared it with another user who has very little start-up time as compared to my vs code application. I have Salesforce lightning experience related extensions added to my vs code. Thanks.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|10.8.0
vscode-eslint|dba|1.9.1
prettier-vscode|esb|3.6.0
vscode-xml|red|0.9.1
salesforcedx-vscode|sal|47.6.0
salesforcedx-vscode-apex|sal|47.4.0
salesforcedx-vscode-apex-debugger|sal|47.4.0
salesforcedx-vscode-apex-replay-debugger|sal|47.4.0
salesforcedx-vscode-core|sal|47.4.0
salesforcedx-vscode-lightning|sal|47.4.0
salesforcedx-vscode-lwc|sal|47.4.0
salesforcedx-vscode-visualforce|sal|47.4.0

</details>

**Comment by alexandrudima** [comment]
@headstrongme Please open an issue against the Salesforce extension directly.
