### ISSUE TITLE
Cursor is not visible on inverted terminal

### ISSUE THREAD

**Issue by jplatte** [microsoft/vscode#84863]
This was previously reported at #73603 but closed (as "maybe this is expected") and locked due to inactivity without any discussion. This is an issue in some terminal UI programs, notably the CMake curses UI, where one only knows the cursor position because there's a status line (this is with the default dark theme):

![Screenshot_2019-11-14_215808](https://user-images.githubusercontent.com/951129/68895641-ff823b80-0729-11ea-8b79-2b534489f8bb.png)

**Comment by Tyriar** [comment]
Thanks, let's continue the discussion here: https://github.com/xtermjs/xterm.js/issues/2064
