### ISSUE TITLE
Editor background has a wierd greenish tint wrapped around the code

### ISSUE THREAD

**Issue by apoorvagarwal41** [microsoft/vscode#84860]
Issue Type: <b>Bug</b>

The editor has a greenish background wrapped around the code.
It's very subtle but really hurts the eyes while working.

![Screenshot from 2019-11-15 02-14-05](https://user-images.githubusercontent.com/34867904/68894812-120e6c00-074e-11ea-8d6c-b6834b414ffc.png)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:30.162Z)
OS version: Linux x64 5.0.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2689)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|7.68GB (1.52GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (101)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|10.5.0
project-manager|ale|10.8.0
stackoverflow-search|Ale|1.2.0
ng-template|Ang|0.802.3
vscode-color|ans|0.4.5
svelte-intellisense|ard|0.7.1
All-Autocomplete|Ati|0.0.20
vscode-custom-css|be5|3.0.8
emojisense|bie|0.5.3
vscode-toggle-quotes|Bri|0.3.2
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
flask-snippets|cst|0.1.1
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-eslint|dba|1.9.1
vscode-faker|dee|1.3.0
javascript-ejs-support|Dig|1.1.3
githistory|don|0.4.6
jquerysnippets|don|0.0.1
xml|Dot|2.5.0
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.1.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.14.2
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.6.0
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
todo-tree|Gru|0.0.162
beautify|Hoo|1.5.0
rest-client|hum|0.22.2
vscode-cdnjs|Jak|0.18.0
vscode-placeholder-images|Jak|0.1.0
svelte-vscode|Jam|0.9.3
docthis|joe|0.7.1
angular-essentials|joh|0.6.3
Angular2|joh|8.1.1
solidity|Jua|0.0.64
theme-karyfoundation-themes|kar|18.2.1
vscode-sshfs|Kel|1.16.3
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.25
dotenv|mik|1.0.1
vscode-scss|mrm|0.6.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.44104
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
vscode-remote-extensionpack|ms-|0.17.0
azure-account|ms-|0.8.7
cpptools|ms-|0.26.1
Go|ms-|0.11.9
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1245
debugger-for-chrome|msj|4.12.1
vscode-react-native|msj|0.13.1
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
angular-console|nrw|9.0.0
vetur|oct|0.22.6
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.9.1
vscode-template-literal-editor|pli|0.9.0
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
vscode-data-preview|Ran|1.49.0
project-snippets|reb|0.5.0
vscode-yaml|red|0.5.3
datetime|rid|1.0.5
LiveServer|rit|5.6.1
jinjahtml|sam|0.10.6
vscode-sass-format|sas|1.1.6
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
vscode-fileutils|sle|3.0.0
sass-indented|syl|1.6.9
vscode-status-bar-format-toggle|tom|2.0.0
errorlens|use|2.7.2
vscodeintellicode|Vis|1.2.0
vscode-icons|vsc|9.5.0
vuetify-vscode|vue|0.2.0
quokka-vscode|Wal|1.0.259
wallaby-vscode|Wal|1.0.156
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.5.1
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@apoorvagarwal41 can you try to run VS Code by disabling gpu and see if you can reproduce (`code --disable-gpu`)

**Comment by apoorvagarwal41** [comment]
If you will open the image in a separate tab and see carefully you will be able to notice a greenish background wrapped around the text. This problem occurred after the latest update.

**Comment by apoorvagarwal41** [comment]
@rebornix You were right, the background disappeared after I launched vscode with GPU disabled. Is there a way where I can fix this problem, without always passing the --disbable-gpu attribute in the terminal.

**Comment by mdelclaro** [comment]
`code --disable-gpu` didn't work for me.

![image](https://user-images.githubusercontent.com/32961172/69054523-806f5a80-09ea-11ea-84e0-e87e5ee26af6.png)

**Comment by deepak1556** [comment]
@apoorvagarwal41 see https://github.com/microsoft/vscode/issues/84992#issuecomment-555175745 for setting this from the editor.

Closing this as no further action can be taken from vscode at the moment.
