### ISSUE TITLE
Search Fields Missing regex icon, others

### ISSUE THREAD

**Issue by ThomasGHenry** [microsoft/vscode#84861]
![image](https://user-images.githubusercontent.com/97537/68895158-896cdd00-0707-11ea-9075-4c3ca386228c.png)
Issue Type: <b>Bug</b>

I'm not seeing how to toggle this in the settings. Is this a bug?

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (185)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
logcat|abh|0.0.7
react-hooks-snippets|AlD|1.1.6
Bookmarks|ale|10.5.0
project-manager|ale|10.8.0
pm2-explorer|ale|0.0.6
cucumberautocomplete|ale|2.14.1
jest-snippets|and|1.7.0
react-pure-to-class-vscode|ang|1.1.8
ACF-Snippet|ant|1.9.0
react-nitro-snippets|are|1.0.2
snapshot-tools|asv|0.4.0
atlascode|atl|2.1.5
code-gnu-global|aus|0.2.2
vsc-sort-react|avr|1.4.2
vscode-changelog-generator|axe|0.4.1
vagrant|bbe|0.5.0
markdown-mermaid|bie|1.4.1
vscode-intelephense-client|bme|1.2.3
mermaid-markdown-syntax-highlighting|bpr|1.0.1
file-properties-viewer|bru|0.3.3
turbo-console-log|Cha|1.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
regex|chr|0.2.0
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
jsrefactor|cms|2.20.5
codealike-code|Cod|0.0.24
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-react-proptypes-intellisense|cun|0.0.3
vscode-markdownlint|Dav|0.32.0
vscode-eslint|dba|1.9.1
vscode-dash|dee|2.2.0
bazel-code|Dev|0.1.9
mern-snippets|dev|1.5.0
xml|Dot|2.5.0
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|2.4.4
viml|dun|0.1.7
gitlens|eam|10.1.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.9
apacheconf-snippets|eim|1.3.0
LogFileHighlighter|emi|2.6.0
react-native-react-redux|EQu|2.0.3
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.6.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
vscode-jest-runner|fir|0.4.2
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.1
code-runner|for|0.9.14
cursoruler|fre|0.0.4
kotlin|fwc|0.2.10
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.162
vscode-nginx-conf-hint|han|0.1.0
vscode-test-explorer|hbe|2.14.6
svgeditor|hen|2.9.0
rest-client|hum|0.22.2
output-colorizer|IBM|0.1.2
phpcs|ika|1.0.5
search-node-modules|jas|1.3.0
vscode-redux-devtools|jin|1.0.2
svg|joc|1.0.5
docthis|joe|0.7.1
mongo-runner|Joe|0.5.8
vscode-peacock|joh|3.2.0
wordpress-vscode-extensionpack|jpa|1.2.0
vscode-insertdatestring|jsy|2.2.4
vscode-sshfs|Kel|1.16.3
vscode-gutter-preview|kis|0.23.0
vscode-commitizen|Kni|0.8.4
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
vs-color-picker|lih|1.0.0
google-fonts|lio|0.0.1
sftp|lix|1.12.9
tmux|mal|0.1.0
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.0
vscode-mocha-sidebar|mat|0.22.2
rainbow-csv|mec|1.3.1
vscode-language-babel|mgm|0.0.25
git-graph|mhu|1.18.0
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
ecdc|mit|1.3.0
HTMLHint|mka|0.6.0
vscode-remote-workspace|mkl|0.43.1
vscode-apache|mrm|1.2.0
vscode-azureappservice|ms-|0.16.1
vscode-docker|ms-|0.8.2
python|ms-|2019.10.44104
remote-containers|ms-|0.83.1
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-ssh-explorer|ms-|0.47.2
azure-account|ms-|0.8.7
cpptools|ms-|0.26.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.1
vscode-react-native|msj|0.13.1
gradle-language|nac|0.2.3
vscode-stencil-tools|nat|2.0.1
color-highlight|nau|2.3.0
php-docblocker|nei|2.0.1
indent-rainbow|ode|7.4.0
react-proptypes-intellisense|OfH|1.0.3
vscode-ios-common-files|Ort|1.0.5
vscode-jest|Ort|3.0.2
vscode-react-native-storybooks|Ort|2.7.0
lanes-navigator|PBe|0.3.1
vscode-spring-boot|Piv|1.12.0
material-icon-theme|PKi|3.9.1
polacode|pnp|0.3.4
vscode-css-peek|pra|3.0.2
node-tdd|pra|0.2.4
vscode-graphql|Pri|0.2.2
quicktype|qui|12.0.46
java|red|0.53.0
vscode-yaml|red|0.5.3
rescuetime|Res|1.0.1
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
bash-debug|rog|0.3.6
vscode-jest-test-adapter|rtb|0.2.0
partial-diff|ryu|1.4.0
esdoc-mdn|sam|0.8.0
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.0
stylelint|shi|0.51.0
numbermonger|sof|0.5.0
swdc-vscode|sof|1.2.1
sonarlint-vscode|Son|1.11.0
php-formatter|Sop|0.2.4
vscode-taskexplorer|spm|1.20.1
es6-mocha-snippets|spo|0.2.2
code-spell-checker|str|1.7.20
code-spell-checker-spanish|str|1.0.1
react-proptypes-generate|sum|1.3.0
ayu|tea|0.18.0
html-preview-vscode|tht|0.2.5
ghosttext|tok|1.1.0
hosts|tom|1.1.1
selectline-statusbar|tom|0.0.2
vscode-workspace-explorer|tom|1.2.2
java-imports-snippets|tus|0.0.1
sort-lines|Tyr|1.8.0
vscode-terminal-here|Tyr|0.2.4
code-navigation|vik|0.2.0
highlight-matching-tag|vin|0.9.5
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-icons|vsc|9.5.0
vim|vsc|1.11.3
nodejs-extension-pack|wad|0.1.9
vscode-wakatime|Wak|2.2.1
quokka-vscode|Wal|1.0.259
wallaby-vscode|Wal|1.0.156
full-react-snippets|wal|1.4.0
WebTemplateStudio-dev-nightly|WAS|0.0.1929801
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
wordpress-toolbox|wor|1.3.5
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
clang-format|xav|1.9.0
local-history|xyz|1.7.0
vscode-surround|yat|1.0.2
markdown-all-in-one|yzh|2.5.1
propertylist|zho|0.0.2

(6 theme extensions excluded)

</details>

**Comment by ThomasGHenry** [comment]
Checked. Not it.

**Comment by rebornix** [comment]
Thanks for reporting, it looks really weird. I didn't see this issue on Catalina at all. Can you try to run `code --disable-gpu` to see if it works or not? Can you also open Dev Tools (F1 -> Open Developer Tools) to see if there is any error there?

**Comment by ThomasGHenry** [comment]
Thanks! The primsa plugin had some errors related to not finding a .graphqlconfig file in my project, but I disabled that and reloaded and that went away. Now it's just some warnings related to grammar. Starting with the gpu flag didn't appear to make a difference. 

![image](https://user-images.githubusercontent.com/97537/68897098-91c71700-070b-11ea-8c7d-7d1ff941b497.png)

**Comment by rebornix** [comment]
@ThomasGHenry does you mean that after disabling the extension, you can still see the issue?

**Comment by ThomasGHenry** [comment]
Correct. There were errors in the log and disabling Prisma made those errors in the log go away, but the original issue has not changed. Thanks for your attention!

**Comment by ThomasGHenry** [comment]
Quick update: I don't yet know the cause, but it's actually not a matter of them missing, it's a matter of them being the same color as the background.
