### ISSUE TITLE
Open File Command take parameters

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#8487]
- VSCode Version: 1.3.0-Insiders
- OS Version: OSX

We expose `workbench.action.files.openFile` for users to open file but seems it doesn't take any parameter or is it just me failing to figure it out from documentation? Open files in Tabs/Windows through API would be perfect IMHO.

BTW, @bpasero mentioned kindly in https://github.com/Microsoft/vscode/issues/5437 that we need to use `workbench.action.files.openFileFolder` but it's not updated in our documentation https://code.visualstudio.com/Docs/customization/keybindings#_file-management which might bothers our users.

**Comment by bpasero** [comment]
@rebornix what are you trying to do? the command we expose is only `vscode.openFolder` at the moment.

**Comment by rebornix** [comment]
I suppose the doc issue is because we only show different key  bindings per OS but not command name.

**Comment by rebornix** [comment]
I'm trying to implement Vim's `:e filename.js` but seems I can't do this directly with command ?

**Comment by bpasero** [comment]
@rebornix what are you trying to do? Please more verbose 👍

**Comment by bpasero** [comment]
1.3 introduces a new `vscode.open` command that can be used to open any resource in Code. See https://github.com/Microsoft/vscode/issues/8195
