### ISSUE TITLE
RIght-click Add Folder to Workspace

### ISSUE THREAD

**Issue by brunoborges** [microsoft/vscode#84876]
Let me right-click-add-to-workspace on a sub-folder of an already opened folder in the workspace:

![image](https://user-images.githubusercontent.com/129743/68904456-d2666680-06f2-11ea-8487-8bde538c494c.png)

**Comment by brunoborges** [comment]
This can be done with Cmd+P for "Add Folder to Workspace". Not sure why what I am proposing has to be an extension.

**Comment by isidorn** [comment]
Because we do not to overflow the context menu and try to keep the prodcut lean.
Extension are for extending the product, like the feature you requested. Thanks

**Comment by brunoborges** [comment]
Seems like you already have "Add Folder to Workspace" on the context menu. But it appears only when I select this kind of node: (in the case of this screenshot, the node 'hellofx')

![image](https://user-images.githubusercontent.com/129743/69109465-b7fef680-0a2c-11ea-979b-0f151d2eb1bd.png)

**Comment by isidorn** [comment]
Yes, that is a workspace root folder, thus we have root folder specific actions on it.
