### ISSUE TITLE
Web: Scrollbar in Editor doesn't work with Touch

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#84871]
* Open Web selfhost on iPad
* Open an editor
* Try to drag the scrollbar to scroll the editor, currently nothing happens.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/01a1603d5139ad433968c51d20948987ab8b76f5.

**Comment by sbatten** [comment]
It requires a first touch to focus the scrollbar before you can drag it, but works. Since you can drag scroll the editor, I think this is okay.
