### ISSUE TITLE
Go to definition hover preview should not open a document on TS Server

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#84875]
Issue Type: <b>Bug</b>

**Repo**
1. Enable ts server logging: `"typescript.tsserver.log": "verbose"`
1. With a workspace:

`index.ts`
```ts
import { a } from "./a";

console.log(a);
```

`a.ts`
```ts
export const a = 1;
```

2. Close all files and restart VS Code
3. Open `index.ts`
4. Hover over `a` in `console.log(a)` and trigger preview

**Bug**
This causes `a.ts` to be opened by the JS/TS extension (through `onDidOpenTextDocument`)

To confirm this, look through the ts server logs

/cc @amcasey 

VS Code version: Code - Insiders 1.41.0-insider (eccf417b72fc0a632ec2cbd7855a681cdb8c81fa, 2019-11-14T09:48:11.894Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_2519655|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Place in code where this is triggered: https://github.com/microsoft/vscode/blob/a537d00e71b17b74e85551eb1183ac1c55e02731/src/vs/editor/contrib/gotoSymbol/link/goToDefinitionAtPosition.ts#L177

**Comment by jrieken** [comment]
There is only that one way to load a document, esp when being in the editor layer, this won't change. I don't understand why typescript reacts to this "in a bad way" but I guess what you want is something is knowledge about open editors/tabs, e.g this https://github.com/microsoft/vscode/issues/15178.

**Comment by jrieken** [comment]
Closing as designed since there is no alternative and since text documents can be opened via various different paths (e.g by another extensions). Band aiding won't help the root issue which I believe is the lack of reflecting open editors or maybe TS being less aggressive in starting "an expensive project load"

**Comment by mjbvz** [comment]
This was a pain point that TS specifically brought up so we should prioritize addressing it (like they do for our issues). TypeScript is seeing users report unexpected project loads reported, and it seems these are most often triggered by hover (although you are correct that extensions can also trigger this by opening text documents)

#15178 would let us fix the issue. However are there any other workarounds we can try before #15178 is addressed? I'm tempted to try checking the file against `visibleTextEditors` but have a feeling that may not work

**Comment by jrieken** [comment]
> This was a pain point that TS specifically brought up so we should prioritize addressing it (like they do for our issues).

I am all for that, I just don't wanna do a hack which then only works half of the time.

>  I'm tempted to try checking the file against visibleTextEditors but have a feeling that may not work

That could work - it's by definition a subset of what open editors will be so you might miss things. You could try to wait a little when a document appears, esp one without an editor. In the hover case the model should be unref'ed/disposed very shortly after opening it. That could make things less aggressive

**Comment by amcasey** [comment]
Could there be an intermediate state where VS Code regards the document as open but doesn't tell the TS server about it?  That would be enough to prevent project load.

**Comment by mjbvz** [comment]
Reopening and making this JS/TS specific. Will look into the fix today

**Comment by mjbvz** [comment]
To verify this, use the listed repo steps. In the TS Server log, look for lines that show `updateOpen` requests:

```
    {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/matb/projects/san/index.ts","fileContent":"import { a } from \"./a\";\n\nconsole.log(a)\n","projectRootPath":"/Users/matb/projects/san","scriptKindName":"TS"}]}}
```

Make sure that `a.ts` is never listed in one of these `updateOpen` requests on hover
