### ISSUE TITLE
Extensions keeps crashing

### ISSUE THREAD

**Issue by meghanking** [microsoft/vscode#84881]
After a minute of open VS Code, extensions are all crashing.

I am unable to use github, typescript support is completely gone. I cant even use function keys to rename variables, or shortcuts to format pages.

**Comment by meghanking** [comment]
CPUs | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 31.79GB (13.80GB free)
Process Argv | .
Screen Reader | no
VM | 0%


Extension | Author (truncated) | Version
-- | -- | --
vscode-markdownlint | Dav | 0.32.0
vscode-eslint | dba | 1.9.1
xml | Dot | 2.5.0
vscode-ts-whitespace-converter | joh | 1.1.1
vscode-tsmix-linter | mic | 1.4.3
csharp | ms- | 1.21.7
vscode-typescript-tslint-plugin | ms- | 1.2.3
back-n-forth | nic | 0.2.1
prettier-vscode-with-tabs | pas | 1.1.0
subtle-brackets | raf | 3.0.0
markdown-preview-enhanced | shd | 0.5.0
easysass | spo | 0.0.6
vscode-todo-highlight | way | 1.0.4
markdown-all-in-one | yzh | 2.5.1

**Comment by gjsjohnmurray** [comment]
I suggest you disable half of your extensions. If problem remains, disable half of those that are still active. When the problem disappears, start reenabling to find the culprit.

**Comment by rebornix** [comment]
@meghanking does it happen when you disable all extensions? As suggested above, please try to disable them all or some of them to see if it still happens.
