### ISSUE TITLE
Debug python in virtual environment(virtualenv module)

### ISSUE THREAD

**Issue by cloudeal** [microsoft/vscode#84884]
Issue Type: <b>Bug</b>

VSCode will create new terminal everytime when i press F5 key if i debug python code in virtual environment. And, shift+command+F5(Restart debug) only stop and won't start debug if i active virtual environment.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.92GB free)|
|Process Argv|-psn_0_40970|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
gitlens|eam|10.1.2
vscode-npm-script|eg2|0.3.9
vsc-material-theme|Equ|30.0.0
prettier-vscode|esb|3.5.0
vscode-mysql|for|0.4.0
ldif|jta|0.2.0
git-graph|mhu|1.18.0
vscode-csscomb|mrm|5.3.0
mssql|ms-|1.7.0
python|ms-|2019.10.44104
debugger-for-chrome|msj|4.12.1
vetur|oct|0.22.6
indent-rainbow|ode|7.4.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.12.0
vscode-manifest-yaml|Piv|1.12.0
vscode-spring-boot|Piv|1.12.0
material-icon-theme|PKi|3.9.1
java|red|0.52.0
LiveServer|rit|5.6.1
vsc-material-theme-italicize|Ser|0.0.14
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6

(8 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
It seems the issue is related to the Python extension you are using, please file issues there.
