### ISSUE TITLE
 Display different ICON on taskbar according to different  project   

### ISSUE THREAD

**Issue by 5dao** [microsoft/vscode#84888]
Issue Type: <b>Feature Request</b>

Open many  vscode instance, with documents and projects in different languages, but  taskbar icon is too single to distinguish easily 

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

**Comment by akrymskiy** [comment]
Yes this would be great - it is very hard to switch instances when having many different projects open. Ideally this would be something configurable per Folder/Project allowing to override default VS icon or at least provide an overlay.

**Comment by edenprojectde** [comment]
Yes please, i just wanted to open an issue about this. It's the only thing that is missing to really manage multiple projects without this. Please add this.

**Comment by 5dao** [comment]
> Yes this would be great - it is very hard to switch instances when having many different projects open. Ideally this would be something configurable per Folder/Project allowing to override default VS icon or at least provide an overlay.

If it receives 20 upvotes we will move it to our backlog @edenprojectde @akrymskiy

**Comment by mfearby** [comment]
> Yes this would be great - it is very hard to switch instances when having many different projects open. Ideally this would be something configurable per Folder/Project allowing to override default VS icon or at least provide an overlay.

I created an [feature](https://github.com/microsoft/vscode/issues/88819) request asking if we could change the icon colour because I have so many blue icons in my taskbar, but this would also be great!

**Comment by 5dao** [comment]
> This feature request has not yet received the 20 community upvotes it takes to make to our backlog. 10 days to go. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding

@akrymskiy @edenprojectde @mfearby @bpasero 

how to upvotes?

**Comment by akrymskiy** [comment]
> how to upvotes?
I believe you just have to add a +1 / Thumbs-Up reaction to the first comment of the thread - there are currently 13 as of now

**Comment by akrymskiy** [comment]
Just to illustrate the feature as implemented in SQL Workbench/J - compared to the current state of VS.Code. Setting different icons per project gives a much better clarity when switching among multiple instances. Would also be okay if we could at least do icon overlay like Windows shortcuts - or anything really to make it easier to get back to the right instance :)
![image](https://user-images.githubusercontent.com/9452607/76434471-1b21e980-638c-11ea-81bd-5637bbe2a7f8.png)
