### ISSUE TITLE
mac os 切换界面工作区不定时出现横向滚动条问题

### ISSUE THREAD

**Issue by fangyu2017** [microsoft/vscode#84887]
- VSCode Version: 1.40.1
- OS Version: 10.15.1

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
1. English please.
2. Detailed steps with screenshot please.
***
你这是贴吧发帖发习惯了么……就标题一句话让老外怎么看……
You should always provide steps to reproduce.

**Comment by rebornix** [comment]
It would be great if you can provide more info like screenshots, recordings, etc to help troubleshoot.

**Comment by fangyu2017** [comment]
![image](https://user-images.githubusercontent.com/26027008/69517856-eaf73c00-0f90-11ea-96f3-0ad8f0862d45.png)

就是这个问题

**Comment by rebornix** [comment]
@fangyu2017 do you have word wrap turned on? If so that might be expected as we show the horizontal scrollbar when the editor gets focus.
