### ISSUE TITLE
Strings from extension are displayed in incorrect language (vscode-nls)

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#84883]
This issue is similar to https://github.com/microsoft/vscode/issues/82791 , and related to [this issue](https://github.com/microsoft/vscode-cpptools/issues/4600) reported in cpptools.  It's unclear if this is an issue with VS Code or isolated to [vscode-nls](https://github.com/microsoft/vscode-nls).

The user has a Windows 10 install that was initially zh-CN, but is now set to en-US.  They are using VS Code in English, having not installed the Chinese language pack extension.  Yet, strings from cpptools (from calls to localize() in vscode-nls) are being displayed in Chinese.

I assume this is due to VS Code defaulting to the original OS language.  Since that language pack extension was never installed, VS Code strings are falling back to English.  Whereas, cpptools is distributed with all language strings, so vscode-nls finds and displays Chinese strings.

The fix would seem to be to always default to en-US, as no language packs are installed by default.(?)  If the language pack were installed, the current OS language would seem preferable over the original OS language.

**Comment by dbaeumer** [comment]
What language is configured in the `locale.json` in the user data directory (under Windows in `AppData\Roaming\Code\User`). If this still list Chinese we set the UI language to Chinese which then the CPP tools correctly honor. The main Window fails since the LP is not installed. 

Is this the case for you?
