### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by Shirsendu-Bairagi** [microsoft/vscode#84890]
Hello Developers I have a issue with the serial port on the Arduino Extension, The Problem is when i click the serial port button the right bottom corner of VSCODE its does noting. I have to manually set the port on arduino.json file. But after the setting of port i uploaded a sketch with serial output but the when i click the plug button it says Failed to open serial port COM4 due to error: + TypeError: Cannot read property 'close' of null. And the port manager failed to open.

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
Steps to Reproduce:

**Comment by mjbvz** [comment]
Please file this against the Arduino extension
