### ISSUE TITLE
Debugging in a terminal always launches $SHELL even though an override is set

### ISSUE THREAD

**Issue by zeroxfourc** [microsoft/vscode#84893]
- VSCode Version: 1.40.0
- OS Version: Linux x64 5.3.11-1-ck

Even though I've set `terminal.integrated.shell.linux` and `terminal.integrated.automationShell.linux`, whenever I debug in a terminal, the command launches in my user's shell, specified in $SHELL.

Steps to Reproduce:

1. Set `terminal.integrated.shell.linux` and `terminal.integrated.automationShell.linux` to something other than your default shell.
2. Try to debug a Python file (it's the only one I've tried).
3. The debug terminal will launch your default shell instead of the shell you specified earlier.

Does this issue occur when all extensions are disabled?: Don't know, I can't debug anything with them off.

**Comment by Tyriar** [comment]
Try going through the Python extension repo first, they might not be doing something right https://github.com/microsoft/vscode-python

**Comment by zeroxfourc** [comment]
Alright, I'll check there. Thanks!
